### ISSUE TITLE
when I [fastlane env]  ----- fastlane: command not found

### ISSUE THREAD

**Issue by tanghaiyang1992** [fastlane/fastlane#10008]
### New Issue Checklist

when I [fastlane env]  ----- fastlane: command not found

### Issue Description

when I [fastlane env]  ----- fastlane: command not found
### Environment

[INSERT OUTPUT HERE]

**Comment by pav1790** [comment]
I feel like you dont have the path to fastlane binary included in $PATH. Happens with rbenv for me sometimes.

**Comment by ohayon** [comment]
Hey @tanghaiyang1992 ! I think @pav1790 is probably right. Did you install fastlane using `gem install fastlane` or `brew cask install fastlane`?

**Comment by MegaManX32** [comment]
same issue here, installed via "brew cask install fastlane". Interestinglly on one mac fastlane is working correctly, but on this one, i don't have fastlane command

**Comment by ohayon** [comment]
@MegaManX32 could you share the output of your `$PATH` variable? It's possible you need to add a line to your shell configuration to append it into your path to make it accessible. 🐙
