### ISSUE TITLE
When requesting to remove a user output states 'tester_id' is required

### ISSUE THREAD

**Issue by allensmith81** [fastlane/fastlane#10006]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When requesting fastline pilot to remove a user it fails to remove the user with an error requesting a tester_id.
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane pilot remove xxxx -a app_id
sh: /Library/Developer/CommandLineTools//usr/bin/xcodebuild: No such file or directory
[01:20:39]: undefined method `split' for nil:NilClass
[01:20:56]: Found existing tester xxxx
[01:20:57]: Could not remove xxxxx from app: `tester_id' is a required parameter
[01:20:57]: `tester_id' is a required parameter

[!] Some operations failed: `tester_id' is a required parameter
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13                                |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.13.2 (Apple Git-90)    |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.13 (17A315i)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | true                                 |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.51.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-09**
</details>

**Comment by KrauseFx** [comment]
First thing I noticed is that your xcodebuild command can't be found, make sure to run `sudo xcode-select -s /Applications/Xcode.app`.

If I run 
```
be fastlane pilot remove -a net.sunapps.1
```
it's asking me for the user to remove, what did you enter there? Could you share the complete output please? 

Mine works as expected:
```
be fastlane pilot remove -a net.com.app -e myemail@gmail.com
[17:26:29]: To not be asked about this value, you can specify it using 'username'
[17:26:29]: Your Apple ID Username: felix@...
[17:26:34]: Login to iTunes Connect (felix@....)
Multiple iTunes Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "11795"

or

  itc_team_name "Felix Krause"

1) "Felix Krause" (117951)
2) "Felix GmbH" (18800)
2
[17:26:52]: Login successful
[17:26:55]: Found existing tester sdfsdfds@gmail.com
[17:26:56]: Successfully removed tester, sdfjsdf@gmail.com, from app: My App
```

**Comment by allensmith81** [comment]
what is -e?

**Comment by allensmith81** [comment]
I see if I run:

fastlane pilot remove --help that -e is the testers e-mail so this is where i will be going wrong.. the documentation doesn't mention -e and simply shows passing in the email address directly. Could we amend the documentation?

**Comment by allensmith81** [comment]
Although typing:

fastlane pilot remove -a app_id -u my_username_email -e email_i_want_to_remove

results in same error.. Just installing xcode now to see if that fixes it.

**Comment by allensmith81** [comment]
Ok so xCode installed and its still not working:

fastlane pilot remove -a com.app.id -e allen.xxxxx@blueyonder.co.uk
[01:45:23]: To not be asked about this value, you can specify it using 'username'
[01:45:23]: Your Apple ID Username: a-user@testflight.com
[01:45:31]: Login to iTunes Connect (a-user@testflight.com)
[01:45:34]: Login successful
[01:45:42]: Found existing tester allen.xxxxx@blueyonder.co.uk
[01:45:42]: Could not remove allen.xxxxx@blueyonder.co.uk from app: `tester_id' is a required parameter
[01:45:42]: `tester_id' is a required parameter

[!] Some operations failed: `tester_id' is a required parameter

**Comment by KrauseFx** [comment]
Please run everything with `--verbose`, and share the complete output, the command you're using and the stack trace. Thanks :)

**Comment by allensmith81** [comment]
`fastlane pilot remove -a app.id --verbose
 [2017-08-09 08:53:51.12]: Email address of the tester: xxxxxxxxx@blueyonder.co.uk
WARN [2017-08-09 08:54:02.97]: To not be asked about this value, you can specify it using 'username'
 [2017-08-09 08:54:02.97]: Your Apple ID Username: xxxxxxxxxx
INFO [2017-08-09 08:54:09.72]: Login to iTunes Connect (xxxxxxxxxx)
Looking for iTunes Connect Team with ID 30244
INFO [2017-08-09 08:54:12.97]: Login successful
INFO [2017-08-09 08:54:20.31]: Found existing tester xxxxxxxx@blueyonder.co.uk
ERROR [2017-08-09 08:54:20.78]: Could not remove xxxxxxx@blueyonder.co.uk from app: `tester_id' is a required parameter
ERROR [2017-08-09 08:54:20.78]: `tester_id' is a required parameter
/Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Some operations failed: `tester_id' is a required parameter (FastlaneCore::Interface::FastlaneError)
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/allensmith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/bin/fastlane:20:in `<top (required)>'
	from /Users/allensmith/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/allensmith/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'`

**Comment by allensmith81** [comment]
I think I figured this out.. it appears the user I was trying to remove was an itunes connect user as well as an external user..

sorry for the noise
