### ISSUE TITLE
Fastlane doesn't acknowledge 'opt_out_usage' option

### ISSUE THREAD

**Issue by twealm** [fastlane/fastlane#1000]
I might be wrong, but it seems that `opt_out_usage` does nothing:
<img width="1070" alt="screenshot 2015-12-18 01 09 10" src="https://cloud.githubusercontent.com/assets/610678/11884669/0a0f9e10-a524-11e5-88e0-8ccf274cdc39.png">

I just typed `fastlane beta` and after `pod install` line was printed in terminal, [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) showed that `ruby` is trying to connect to fastlane-refresher.herokuapp.com (this also happened right before I saw output from `sigh` command, and twice after I hit `Ctrl+C` instead of typing password when `sigh` asked for it), though you can see that it should be disabled (and crash reporting is disable too - I choose not to enable it when performing `fastlane init` and disabled it manually later just to be sure).

fastlane 1.48.0, 
command I used: `fastlane beta`.
[Fastfile.txt](https://github.com/fastlane/fastlane/files/66045/Fastfile.txt)
[output.txt](https://github.com/fastlane/fastlane/files/66046/output.txt)

**Comment by KrauseFx** [comment]
Thanks for this report. The `opt_out_usage` indicates that you don't `fastlane` to collect the number of runs per integration. To also disable update checks, add this to your `Fastfile` or shell environment

```ruby
ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "1"
```

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
