### ISSUE TITLE
No action available to modify the app services (capabilities)

### ISSUE THREAD

**Issue by bhimsenpadalkar** [fastlane/fastlane#10007]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
There is no action available to modify the services.
Currently there are two places(options) where services can be modified
1. While creating the app id using 'produce' action: This option modifies the services only while creating the app. If app is already existing in dev center, running this action does not modifies the services.
2. Running 'fastlane produce enable_services .....' from command line.

This blocks a developer from modifying the services using a lane in Fastfile

**Comment by KrauseFx** [comment]
Wohooo, thanks ❤️
