### ISSUE TITLE
Remove underline from suggestion to run update_plugins

### ISSUE THREAD

**Issue by pmcgaley** [fastlane/fastlane#10014]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If plugins are out of date, fastlane recommends running `fastlane update_plugins`. However (at least in my default MacOS terminal setup), the command is underlined, which completely obscures the underscore in `update_plugins`. I wasted a silly amount of time trying to figure out why `fastlane update plugins` without the underscore was failing.

##### Complete output when running fastlane, including the stack trace and command used

Screenshot is more useful than text of output here:

![image](https://user-images.githubusercontent.com/18594548/29122614-e1b41cd2-7d0a-11e7-8ed1-1c53f01ae382.png)

**Comment by pmcgaley** [comment]
@fastlane-bot to be honest, I ran `fastlane env`, saw it contained my developer ID, apple ID e-mail address etc. and decided I didn't want to publish that stuff here.

**Comment by KrauseFx** [comment]
Ahhh, nice catch, that's a great point, I'll think about how we can solve it 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/10018
