### ISSUE TITLE
Run fastlane with directory stored elsewhere?

### ISSUE THREAD

**Issue by drosenstark** [fastlane/fastlane#10017]
Is it possible to store my `fastlane` directory in another place on disk than where I'm running `fastlane`? If so, how can I tell `fastlane` where it's stored?

Thanks.

**Comment by KrauseFx** [comment]
Sorry no, you could probably use symlinks if you wanted to. Alternatively check out the [import action](https://docs.fastlane.tools/actions/#import), but this will only import the Fastfile as far as I know.

**Comment by drosenstark** [comment]
Thanks so much @KrauseFx! Yeah I'm using some rudimentary symlink'ing, works fine.
