### ISSUE TITLE
"badge" action is outdated

### ISSUE THREAD

**Issue by kevin-hirsch** [fastlane/fastlane#10015]
Hello,

I've seen that the `badge` action is missing some parameter (that are available through `badge` command line tool). Those parameters are `shield_scale` and `shield_geometry`.
Digging more, I've found there is also a plugin called `badge`. It is the same tool as the action from fastlane itself but the plugin one is actually up to date and contains the 2 parameters.

I don't know what's the best to do:
- update the `badge` action
- or remove/deprecate the `badge` action in favour of using the `badge` plugin?

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.12.6                                        |
| Ruby                        | 2.3.2                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.13.3 (Apple Git-91)              |
| Installation Source         | ~/.rbenv/versions/2.3.2/bin/fastlane           |
| Host                        | Mac OS X 10.12.6 (16G29)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.2/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | ~/Downloads/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.51.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.3        |
| fastimage                 | 2.1.0        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| badge                     | 0.8.4        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| cocoapods                 | 1.3.1        |
</details>

*generated on:* **2017-08-09**
</details>

**Comment by carlosefonseca** [comment]
I'm looking into replacing the action with the plugin but I think I'm missing something… I read #10127 about the deprecation of the action but adding the plugin and removing the gem still seems to use the action. 

On running fastlane I get this
[23:11:22]: Plugin 'Badge' overwrites already loaded action 'badge'
[…]
[23:11:25]: -------------------
[23:11:25]: --- Step: badge ---
[23:11:25]: -------------------
==========================================
This action (badge) is deprecated
==========================================

I think this is because they have the same name, and the plugin depends on the `badge` gem…
Is there something that can be done here or is just waiting for the action to be removed from fastlane itself?

**Comment by beloso** [comment]
I have the same issue

**Comment by kevin-hirsch** [comment]
I am also facing the issue where it's writing in console:
```bash
[23:11:22]: Plugin 'Badge' overwrites already loaded action 'badge'
[…]
[23:11:25]: -------------------
[23:11:25]: --- Step: badge ---
[23:11:25]: -------------------
==========================================
This action (badge) is deprecated
==========================================
```

But the badge action that is used is the badge plugin.

**Comment by HazAT** [comment]
Hey, I've just released version `1.0.0` which renames the plugin action to `add_badge`, this should resolve the conflict you guys are having with the old `badge` action.
Please upgrade and use `add_badge` then everything should work fine :)

**Comment by KrauseFx** [comment]
Wohooo, awesome, thanks @HazAT ❤️

**Comment by beloso** [comment]
🎉  thank you
