### ISSUE TITLE
UITargetAppPath should be provided

### ISSUE THREAD

**Issue by SupreeSeekSter** [fastlane/fastlane#10013]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I can build the app with the Xcode. The problem only occurs while I was trying  to use fastlane. Please help.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

2017-08-09 19:23:47.132 xcodebuild[46936:333890]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/supreenuritanon/Library/Developer/Xcode/DerivedData/Seeker-dddoqsnzkrqggmgwswwhdezkcgyh/Logs/Test/597C8BA2-04AA-49F1-8B21-C87D3A14605B/Session-SeekerTests-2560-08-09_192347-Aq984x.log
2017-08-09 19:23:47.133 xcodebuild[46936:333837] [MT] IDETestOperationsObserverDebug: (7C5908C9-45D6-4813-BDF4-4EBCF3D62677) Beginning test session SeekerTests-7C5908C9-45D6-4813-BDF4-4EBCF3D62677 at 2017-08-09 19:23:47.133 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fa86cf7bea0> {
SimDevice: SimDevice : iPhone 5s (1FA4AD72-259A-4387-B801-C214C6281A2C) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))
xcodebuild: error: Failed to build workspace Seeker with scheme Seeker Staging.
Reason: Validation for test run specification failed: UITargetAppPath should be provided
[19:23:47]: Exit status: 70
+----------------------------+--------------------------------------+
|                           Lane Context                            |
+----------------------------+--------------------------------------+
| DEFAULT_PLATFORM           | ios                                  |
| PLATFORM_NAME              | ios                                  |
| LANE_NAME                  | ios staging                          |
| SCAN_DERIVED_DATA_PATH     | /Users/supreenuritanon/Library/Deve  |
|                            | loper/Xcode/DerivedData/Seeker-dddo  |
|                            | qsnzkrqggmgwswwhdezkcgyh             |
| SCAN_GENERATED_PLIST_FILES | []                                   |
| SCAN_GENERATED_PLIST_FILE  |                                      |
+----------------------------+--------------------------------------+
[19:23:47]: Error building/testing the application - see the log above

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | carthage            | 165         |
| 💥   | scan                | 228         |
+------+---------------------+-------------+

[19:23:47]: fastlane finished with errors

[!] Error building/testing the application - see the log above

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
Could you provide a sample project for us, so we're able to reproduce?
