### ISSUE TITLE
Any way to create a new app in the playstore?

### ISSUE THREAD

**Issue by mdanics** [fastlane/fastlane#10019]
I saw post from 2015 where this was not possible, have things changed?

**Comment by KrauseFx** [comment]
Sorry, it's not possible due to API limitations 😢 As soon as the API allows it we can implement it

**Comment by mdanics** [comment]
@KrauseFx  Does the app have to be fully published for supply to work?

**Comment by KrauseFx** [comment]
I think there has to be at least one release out there to make it work

**Comment by mdanics** [comment]
tested, confirmed
