### ISSUE TITLE
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: badRequest: Bad Request

### ISSUE THREAD

**Issue by jayenashar** [fastlane/fastlane#10022]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Old fastlane setup from September 2016.  Trying to update store description using same command as last year.  Didn't work.  Upgraded ruby, fastlane, and supply.  Same error.  Have run the command a few times and once I saw it get past the first `Uploading image file` and move on to the second before throwing this error.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Notes: `--capture_output` doesn't work as the last commandline argument.  It's weird that it's mixing `--` and `_`.  It causes a different issue than the one I'm experiencing, so I've put two outputs here: first `--capture_output` and second my command's output.

### Captured Output

Command Used: `supply`
<details><summary>Output/Log</summary>

```

DEBUG [2017-08-10 12:44:24.89]: Checking if there are any plugins that should be loaded...
INFO [2017-08-10 12:44:25.01]: -------------------------------------------------
INFO [2017-08-10 12:44:25.01]: --- Step: Verifying required fastlane version ---
INFO [2017-08-10 12:44:25.01]: -------------------------------------------------
INFO [2017-08-10 12:44:25.01]: Your fastlane version 2.52.0 matches the minimum requirement of 1.100.0  ✅
INFO [2017-08-10 12:44:25.02]: ------------------------------
INFO [2017-08-10 12:44:25.02]: --- Step: default_platform ---
INFO [2017-08-10 12:44:25.02]: ------------------------------
WARN [2017-08-10 12:44:25.02]: Lane Context:
INFO [2017-08-10 12:44:25.02]: {:DEFAULT_PLATFORM=>:android}
ERROR [2017-08-10 12:44:25.02]: Could not find lane 'android supply'. Available lanes: android test, android beta, android deploy
INFO [2017-08-10 12:44:25.02]: Successfully generated documentation at path '/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
+------+---------------------+-------------+

ERROR [2017-08-10 12:44:25.03]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                      |
| --------------------------- | ---------------------------------------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                                                    |
| Ruby                        | 2.3.1                                                                                                      |
| Bundler?                    | true                                                                                                       |
| Git                         | git version 2.9.2                                                                                          |
| Installation Source         | ~/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib                                                                           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                                                                 |
| Is contained                | false                                                                                                      |
| Is homebrew                 | false                                                                                                      |
| Is installed via Fabric.app | false                                                                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                                |
| Xcode Version               | 8.3.3                                                                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "Google Play Android Developer-e8b8bd28a486.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.finderful" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.52.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-10**
</details>
<details><summary><b>--capture_output Issue</b></summary>

```
 [2017-08-10 12:44:26.51]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
y
bundler: failed to load command: fastlane (/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Could not find lane 'android supply'. Available lanes: android test, android beta, android deploy
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/runner.rb:29:in `execute'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/bin/fastlane:20:in `<top (required)>'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

</details>
<details><summary><b>Actual Issue</b></summary>

`SUPPLY_SKIP_UPLOAD_APK=true ~/.gem/ruby/2.3.0/bin/bundle exec fastlane supply --verbose`

```
INFO [2017-08-10 12:50:16.94]: Successfully loaded '/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/fastlane/Supplyfile' 📄

+-----------+----------------------------------------------------------------------------------------------+
|                               Detected Values from './fastlane/Supplyfile'                               |
+-----------+----------------------------------------------------------------------------------------------+
| track     | alpha                                                                                        |
| apk_paths | ["build/outputs/apk/android-armv7-release.apk", "build/outputs/apk/android-x86-release.apk"] |
+-----------+----------------------------------------------------------------------------------------------+

DEBUG [2017-08-10 12:50:16.94]: Taking value for 'skip_upload_apk' from environment variable 'SUPPLY_SKIP_UPLOAD_APK'

+-------------------------+----------------------------------------------------------------------------------------------+
|                                               Summary for supply 2.52.0                                                |
+-------------------------+----------------------------------------------------------------------------------------------+
| track                   | alpha                                                                                        |
| apk_paths               | ["build/outputs/apk/android-armv7-release.apk", "build/outputs/apk/android-x86-release.apk"] |
| package_name            | com.finderful                                                                                |
| metadata_path           | ./fastlane/metadata/android                                                                  |
| json_key                | Google Play Android Developer-e8b8bd28a486.json                                              |
| skip_upload_apk         | true                                                                                         |
| skip_upload_metadata    | false                                                                                        |
| skip_upload_images      | false                                                                                        |
| skip_upload_screenshots | false                                                                                        |
| validate_only           | false                                                                                        |
| check_superseded_tracks | false                                                                                        |
+-------------------------+----------------------------------------------------------------------------------------------+

DEBUG [2017-08-10 12:50:16.95]: Fetching a new access token from Google...
INFO [2017-08-10 12:50:18.03]: Preparing to upload for language 'en-US'...
INFO [2017-08-10 12:50:19.01]: Uploading image file ./fastlane/metadata/android/en-US/images/featureGraphic.png...
bundler: failed to load command: fastlane (/Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: badRequest: Bad Request
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/client.rb:369:in `rescue in call_google_api'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/client.rb:367:in `call_google_api'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/client.rb:320:in `upload_image'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/uploader.rb:84:in `block in upload_images'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/uploader.rb:78:in `each'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/uploader.rb:78:in `upload_images'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/uploader.rb:20:in `block in perform_upload'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/uploader.rb:13:in `each'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/uploader.rb:13:in `perform_upload'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/commands_generator.rb:59:in `run'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/supply/lib/supply/commands_generator.rb:12:in `start'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.52.0/bin/fastlane:20:in `<top (required)>'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/jayen/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                      |
| --------------------------- | ---------------------------------------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                                                    |
| Ruby                        | 2.3.1                                                                                                      |
| Bundler?                    | true                                                                                                       |
| Git                         | git version 2.9.2                                                                                          |
| Installation Source         | ~/Downloads/finderful.com-backend/frontend/cordova/platforms/android/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib                                                                           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                                                                 |
| Is contained                | false                                                                                                      |
| Is homebrew                 | false                                                                                                      |
| Is installed via Fabric.app | false                                                                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                                |
| Xcode Version               | 8.3.3                                                                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "Google Play Android Developer-e8b8bd28a486.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.finderful" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.52.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-10**
</details>

**Comment by harikishan7** [comment]
Today when I ran supply to update screenshots I ran into the same issue and I get the exact same error. In some instances the error occurs after several screenshots get uploaded. I tried multiple times but it keeps happening.

**Comment by Matt029847294** [comment]
Just had the same issue as well. uploading metadata only works, but fails on images (mine was the promotional artwork)

**Comment by amadofelipe** [comment]
Same here :worried:

**Comment by singletondejan** [comment]
Same here. Using fastlane on daily base. I did no updates nor changes on fastlane files. Got for the first time this error message yesterday. Based on that I assume it is related to google and not fastlane?

**Comment by Vetryanuj** [comment]
The same situation(

**Comment by moga1111** [comment]
It happened this morning too, Yesterday I was able to upload screenshots, today I ran the same one and gave me the `Google Api Error: badRequest: Bad Request` error

**Comment by emcniece** [comment]
Same issue. I was able to modify my `supply` command to exclude images and screenshots, and it worked:

```
    supply(
      json_key: "fastlane/android-developer.json",
      apk: "./platforms/android/build/outputs/apk/android-release-signed.apk",
      track: "alpha",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      package_name: "bob"
    )
```

**Comment by singletondejan** [comment]
Thanks @emcniece, adding skip images and screenshots helped in my case. I consider it as temporary solution, because if I want to upload images and screenshots, this needs to work.

**Comment by moga1111** [comment]
I found that if you do it twice in a row (with images) it will fail the second time. Try again after a while it works. Feels like a cooldown to me. It always works when I try after waiting a while.

**Comment by amadofelipe** [comment]
I tried again today and it worked.Odd.

**Comment by harikishan7** [comment]
Yes it worked for me as well. I also updated to the latest version.

**Comment by jayenashar** [comment]
images seem to work fine now.  but now i also know that it wasn't me.

but now it's bailing out at:

```
INFO [2017-08-15 20:26:03.41]: Uploading all changes to Google Play...
Google::Apis::ServerError: [!] Server error
```

How can I know if it's a bug I should report to fastlane in case of an API change, or if it's an issue on Google's end?

**Comment by platedbay** [comment]
+1 to getting the `Google::Apis::ServerError: [!] Server error`. We're just uploading the APK, nothing else.

**Comment by viniciusoh** [comment]
@jayenashar @platedbay I also had this `Google::Apis::ServerError: [!] Server error ` error today, but It was because Google Play added a new item at the _Prices and distribution_ section in Google Play Console, for apps directed to children below 13 years.

Try filling it up and uploading again that it might work now :)

**Comment by platedbay** [comment]
@viniciusoh I actually just saw that, accepted it and updated it. I just tried a reupload and I'm still getting the error. Maybe the update needs more time to propagate through the console. I'll try again in an hour or so.

**Comment by platedbay** [comment]
Tried again recently and still getting the server error. Had to upload the APK manually to get this out.
