### ISSUE TITLE
[snapshot] Delay in second screenshot

### ISSUE THREAD

**Issue by IchHabRecht** [fastlane/fastlane#10023]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In my UI test I have following steps:

- swipe down on a table view to activate the refresh item
- a second view flies in as kind of notification
- screenshot is taken
- rotate the device to landscape
- swipe down again -> show notification view again
- screenshot is taken

The first screenshot is taken correctly and the notification is fully captured.  The second screenshot is taken with some delay and the notification is already on its way of disappearing.

I already disabled the "waiting for idle" state (https://stackoverflow.com/a/45515130/7291607) which I needed to get the first screenshot running. Is there any best practice or any settings I can use to capture the second screenshot in time?

I already tried to separate both screenshots in different UI test functions but this didn't solve the problem unfortunately.

**Comment by KrauseFx** [comment]
Hey @IchHabRecht, mh, this doesn't sound like it's a fastlane snapshot issue?

**Comment by IchHabRecht** [comment]
Thanks for your answer @KrauseFx. But the tests in Xcode are working fine. I think the problem is because of the disappearing view. I don't know how to solve this. Will add some images once I'm home.

**Comment by KrauseFx** [comment]
Cool, thanks 👍

**Comment by IchHabRecht** [comment]
Hi Felix,

Please find attached the promised images.

First the one captured first:
 ![headerportrait](https://user-images.githubusercontent.com/1453345/29192449-c58ebdf6-7e21-11e7-9f0d-619a840f846d.png)

And the one captured second:
![headerlandscape](https://user-images.githubusercontent.com/1453345/29192453-cc7d0096-7e21-11e7-8700-aca6aeffacd6.png)

As you can see the second image is missing the full overlay as it was on the way of disappearing.

The code I use in the UI test:
```
XCUIDevice().orientation = UIDeviceOrientation.portrait      
swipeDownAndUp()        
snapshot("01 List Pink Portrait")

XCUIDevice().orientation = UIDeviceOrientation.landscapeLeft
swipeDownAndUp()
snapshot("01 List Pink Landscape")
```

swipeDownAndUp() ensures the first table cell is dragged down to activate the refreshControl. Hopes this helps to understand my current problem.

**Comment by KrauseFx** [comment]
Right right, but I'm unsure of how fastlane can change its behavior to make it work, this looks like an UITest issue to me. fastlane snapshot just shells out to `xcodebuild` to run the snapshot tests.

**Comment by janpio** [comment]
Could the issue here be that `snapshot()` is executed while the animation that is the result of `swipeDownandUp` is still in progress, @IchHabRecht? 

I have similar "problems" (everything works as intended, just not as hoped) with `screengrab` and added manual "sleeps" before the screenshot creation as a temporary workaround until I find out how exactly I can properly fix this.

**Comment by IchHabRecht** [comment]
My problem is that the animation is already on its way back (after 3 seconds of delay) instead of not finished in snapshot. Increasing the delay helps to ensure everything is visible even for the second screenshot. 
Seems I have to configure a delay variable that is increased for given launch arguments. Would that be a valid solution for this problem?

@KrauseFx I hope to get some "how to solve this issue" solutions, not wanted to say anything is done wrong in snapshot ;-)

**Comment by KrauseFx** [comment]
If you look at the `snapshot` method in your `SnapshotHelper.swift`, you'll see that by default _snapshot_ will wait for the loading indicator to disappear. You might want to disable that behavior if you want

**Comment by IchHabRecht** [comment]
@KrauseFx Thank you so much. That was the answer I was looking for ^^

Seems although I don't have any indicator available, the query caused the delay.
