### ISSUE TITLE
precheck unclear error message

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#10036]
<img width="948" alt="screen shot 2017-08-11 at 1 47 30 pm" src="https://user-images.githubusercontent.com/869950/29231442-085dfb0e-7e9c-11e7-8124-2da9ab1f611c.png">

Steps to reproduce
1. `fastlane deliver init` for any app
2. `fastlane deliver --force`

Expected result:
Successful upload with some kind of success message

Actual result:
For the user it looks like the build failed, and it wasn't successful, it took me a while to figure that out

**Comment by taquitos** [comment]
Yeah, good call @KrauseFx, let's make this more friendly, especially if we're not failing, maybe we can change these lines to yellow and add something like "_deliver_ was successful 👍 "
"Even though we found potential problems, things look good 👍 "

**Comment by KrauseFx** [comment]
Sounds great 👍
