### ISSUE TITLE
if API 404s fastlane dies

### ISSUE THREAD

**Issue by taquitos** [fastlane/fastlane#10043]
Sometimes Apple just 404s
<title>Error 404 </title> </head> <body> <h2>HTTP ERROR: 404</h2> <p>Problem accessing /v2/providers/488224/apps/1059454626/groups/3a512fc0-34e6-44bf-a537-ac3a45bf13e7/testers/f1db6ae5-b6b1-4840-9c86-b94be78a36ac. Reason: <pre> Not Found</pre>

also got this
Could not add <email> to app: (app name)
#<Spaceship::Client::InternalServerError: Server error got 500>

we should be trapping this and trying again. This issue is to investigate.

**Comment by KrauseFx** [comment]
Ha

**Comment by taquitos** [comment]
Best response

**Comment by joshdholtz** [comment]
@taquitos What you wanna do about this? 😉

**Comment by taquitos** [comment]
> we should be trapping this and trying again.

**Comment by taquitos** [comment]
I think anything that we can do to make fastlane more robust when it comes to handling flaky API is a huge win.
