### ISSUE TITLE
Check signing before gym

### ISSUE THREAD

**Issue by NikKovIos** [fastlane/fastlane#10047]
Hello, i just want to ask if there a way for **gym** to check if it can sign before compiling.

The problem is that when i use gym it firstly compile all files and then throws error:  
 ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'

Compiling takes a lot of time and it would be great to firstly check it with signing and then compile. If there any way to do that?

Sorry if there already exist a question like this.

**Comment by taquitos** [comment]
This is a great question, we've been trying to think of ways where we can do something like check signing. It seems like the only reliable way is to build an app and then try to sign it. There might be some things we can do to check is certs exist for specific app ids which wouldn't require any building.

**Comment by thasegaw** [comment]
I would like to check not only code signing but also expiration of FASTLANE_SESSION before execution of `gym` because compiling time of `gym` is too long.
