### ISSUE TITLE
Can I use Fastlane on Amazon Linux?

### ISSUE THREAD

**Issue by lugrace** [fastlane/fastlane#10049]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ ]x I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to use Fastlane on Amazon Linux for iOS submissions. But I need to install xcode, which is only available on Apple machines. Is there a way around this/put Fastlane on Amazon Linux?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
/usr/local/share/ruby/gems/2.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/usr/share/ruby/2.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[19:35:47]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-08-14 19:35:50.08]: Checking if there are any plugins that should be loaded...
INFO [2017-08-14 19:35:50.09]: Detected iOS/Mac project in current directory...
INFO [2017-08-14 19:35:50.09]: This setup will help you get up and running in no time.
INFO [2017-08-14 19:35:50.09]: fastlane will check what tools you're already using and set up
INFO [2017-08-14 19:35:50.09]: the tool automatically for you. Have fun! 
WARN [2017-08-14 19:35:50.50]: Generating fastlane environment output, this might take a few seconds...
ERROR [2017-08-14 19:35:50.52]: undefined method `strip' for nil:NilClass
ERROR [2017-08-14 19:35:50.52]: Error rendering markdown table using the following text:
INFO [2017-08-14 19:35:50.52]: | Key | Value |
| fastlane | 2.53.1 |
| OS | Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.0.0 |
| Bundler? | false |
| Git | git version 2.7.5 |
| Installation Source | /usr/local/bin/fastlane |
| Host | Amazon Linux AMI release 2017.03
Kernel \r on an \m Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (4.9.32-15.41.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
DEBUG [2017-08-14 19:35:50.67]: Checking if there are any plugins that should be loaded...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.53.1 |
| OS | Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.0.0 |
| Bundler? | false |
| Git | git version 2.7.5 |
| Installation Source | /usr/local/bin/fastlane |
| Host | Amazon Linux AMI release 2017.03
Kernel \r on an \m Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (4.9.32-15.41.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
</details>

*generated on:* **2017-08-14**
</details>
INFO [2017-08-14 19:35:50.68]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
/usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Unable to locate Xcode. Please make sure to have Xcode installed on your machine (FastlaneCore::Interface::FastlaneError)
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/helper.rb:158:in `xcode_at_least?'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/project.rb:285:in `build_xcodebuild_showbuildsettings_command'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/project.rb:306:in `build_settings'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/project.rb:343:in `default_build_settings'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/project.rb:160:in `default_app_identifier'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/setup/setup_ios.rb:140:in `setup_project'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/setup/setup_ios.rb:26:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/setup/setup.rb:29:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /usr/local/share/ruby/gems/2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/share/ruby/gems/2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/share/ruby/gems/2.0/gems/fastlane-2.53.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
/usr/local/share/ruby/gems/2.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/usr/share/ruby/2.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[19:37:00]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
WARN [2017-08-14 19:37:03.19]: Generating fastlane environment output, this might take a few seconds...
ERROR [2017-08-14 19:37:03.20]: undefined method `strip' for nil:NilClass
ERROR [2017-08-14 19:37:03.20]: Error rendering markdown table using the following text:
INFO [2017-08-14 19:37:03.20]: | Key | Value |
| fastlane | 2.53.1 |
| OS | Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.0.0 |
| Bundler? | false |
| Git | git version 2.7.5 |
| Installation Source | /usr/local/bin/fastlane |
| Host | Amazon Linux AMI release 2017.03
Kernel \r on an \m Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (4.9.32-15.41.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
DEBUG [2017-08-14 19:37:03.63]: Checking if there are any plugins that should be loaded...
INFO [2017-08-14 19:37:03.64]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
WARN [2017-08-14 19:37:03.64]: Generating fastlane environment output, this might take a few seconds...
ERROR [2017-08-14 19:37:03.66]: undefined method `strip' for nil:NilClass
ERROR [2017-08-14 19:37:03.66]: Error rendering markdown table using the following text:
INFO [2017-08-14 19:37:03.66]: | Key | Value |
| fastlane | 2.53.1 |
| OS | Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.0.0 |
| Bundler? | false |
| Git | git version 2.7.5 |
| Installation Source | /usr/local/bin/fastlane |
| Host | Amazon Linux AMI release 2017.03
Kernel \r on an \m Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (4.9.32-15.41.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
DEBUG [2017-08-14 19:37:03.82]: Checking if there are any plugins that should be loaded...
### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.53.1 |
| OS | Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.0.0 |
| Bundler? | false |
| Git | git version 2.7.5 |
| Installation Source | /usr/local/bin/fastlane |
| Host | Amazon Linux AMI release 2017.03
Kernel \r on an \m Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (4.9.32-15.41.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
</details>


*generated on:* **2017-08-14**
</details>


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.53.1 |
| OS | Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.0.0 |
| Bundler? | false |
| Git | git version 2.7.5 |
| Installation Source | /usr/local/bin/fastlane |
| Host | Amazon Linux AMI release 2017.03
Kernel \r on an \m Linux ip-172-31-8-75 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (4.9.32-15.41.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
</details>

**Comment by PetrosIchor** [comment]
Fastlane can run on Linux, however, any iOS/OSX specific features will not work. 

In order to build iOS apps or communicate with Apple's services you have to be on OS X. This is a requirement by apple for all iOS development.
