### ISSUE TITLE
What it do 

### ISSUE THREAD

**Issue by augmen** [fastlane/fastlane#10044]
what actually fast lane do. Does it convert the app.js to android app and test it and deploy to google play store ? Can any one define the workflow ?

**Comment by PetrosIchor** [comment]
There's many ways to answer that question.  If start by just reading the language on the homepage.  

https://fastlane.tools

From my perspective, fastlane is a collection of open source tools that help automate complicated, repeatable tasks when building and distributing mobile applications. Like any type of engineering, you have to first understand what your building before you can pick the tools to accomplish that task. 

That said, while Fastlane's goal is to focus on mobile, it can be extended to assist with a variety of automation tasks.  Personally, I use fastlane for mobile as well as other automation such as packaging node modules, deploying micro services, and documentation generation.

**Comment by taquitos** [comment]
Great description of _fastlane_ @PetrosIchor. Definitely check out the docs @augmen 👍
