### ISSUE TITLE
Can't access environment variable for Match certificate's Common Name

### ISSUE THREAD

**Issue by EricNetsch** [fastlane/fastlane#10048]
I have a fairly complex Fastlane setup working to Match my certs for my main app target as well as my notification extension. 

As a result of running into issues with signing the Notification Extension and I have turned off Automatic code signing. Instead I am creating a custom keychain, setting provisioning profiles for both targets manually (main and extension) then passing the Certificates "Common Name " to the XCARGS -> CODE_SIGN_IDENTITY of my gym step. 

`xcargs:"CODE_SIGN_IDENTITY='iPhone Distribution: Company Name Inc. (XXXXXXXXX)'"
`

This works great, although I need a solution that can use the Common Name of the Certificate stores in the keychain. So far there is no way to access the common name within Fastlane. 
Ex:" iPhone Distribution: Company Name Inc. (XXXXXXXXX)"

This appears to be the same closed issue as #6654

Also, please let me know if there is a simpler way to layout my Fastfile. It is currently not as simple as I had hoped but it has been the only way to codesign the Notification Extension properly. 

The Common Name Env var should be an pretty easy addition to Match and I would be happy to contribute that if it makes sense. I have read of multiple people running into needed to access the Signing Identity or Common Name within their Fastlane. 
Thanks.

```
create_keychain(
      name: "Release",
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: true,
      timeout: false,
      password:"XXXXX",
      unlock: true
 )
match(
        git_url:"git@github.comXXXXXXXXXX",
        git_branch:"XXX",
        type: 'appstore',
        app_identifier: ["com.tapcart.XXX", "com.tapcart.XXX.notification"],
        team_id:"XXX",
        git_full_name: "XXX",
        readonly: false,
        git_user_email:"XXX",
        username:"XXX",
        shallow_clone:true,
        keychain_name:"Release",
        keychain_password:"XXX",
    )
    disable_automatic_code_signing(
      path: "Tapcart.xcodeproj",
      team_id: "XXX"
    )
    update_project_team(
      path: "Tapcart.xcodeproj",
      teamid: "XXX"
    )
    update_project_provisioning(
      xcodeproj: "Tapcart.xcodeproj",
      profile: ENV['sigh_com.tapcart.XXX_appstore_profile-path'],
      target_filter: "Tapcart"
    )
    update_project_provisioning(
      xcodeproj: "Tapcart.xcodeproj",
      profile: ENV['sigh_com.tapcart.XXX.notification_appstore_profile-path'],
      target_filter: "notification"
    )
    gym(
        workspace: "Tapcart.xcworkspace",
        scheme: "Tapcart",
        silent: true,
        clean: true,
        output_name: "Tapcart.ipa",
        export_method: "app-store",
        export_team_id: "XXX",
        xcargs:"CODE_SIGN_IDENTITY='iPhone Distribution: Company Name Inc. (XXXXXXXXX)"
    )



```
@KrauseFx

**Comment by taquitos** [comment]
@EricNetsch if a `Common Name Env` was added, how would that change your current setup? I'm not as familiar with _match_ 😞

**Comment by EricNetsch** [comment]
@taquitos 
I would be able to pass the the Common Name variable to my gym step to manually set the CODE_SIGN_IDENTITY='iPhone Distribution: Company Name Inc. (XXXXXXXXX)

Since I have over 1000+ different iTunes Connect accounts (clients) it is important for this value to be dynamic.

**Comment by taquitos** [comment]
That setup is typically a lot more complicated than what we generally advise. There seems to be a lot of steps that *should* be taken of for you. For example, we recommend disabling automatic code signing in the project, and setting things using environment variables within the xcode project (it's being set from within _fastlane_, but used on the xcode project). We have some examples of how to set up this stuff in our [Code Signing Guide](https://docs.fastlane.tools/codesigning/getting-started/).
