### ISSUE TITLE
Display error message when an error occurs 

### ISSUE THREAD

**Issue by chrismanahan** [fastlane/fastlane#1004]
Crash report: `b10a15ae2bf1de9cf6c4c97dc04953c5`

I think when an error occurs, the message part of the crash report should be displayed to the user. When running `deliver` during the initial setup, I logged in and got the message `Error occurred with the setup program! Reverting changes now!`. It would be more helpful to pull the message from the json crash report to display to the user. In my case, the issue was as simple as not putting the app into iTunesConnect: 

    "message": "RuntimeError: \u001b[31mCould not find app with app identifier 'com.manahan.MyApp' in your iTunes Connect account (chrismanahan - Team: 477707)\u001b[0m",

**Comment by KrauseFx** [comment]
Oh yeah, @ohwutup is currently working on rewriting the setup, this will also include this change. Thanks for your feedback :+1:
