### ISSUE TITLE
Is fastlane compatible with xcode 9?

### ISSUE THREAD

**Issue by reshadf** [fastlane/fastlane#10056]
I changed my commandline version of xcode to 9.0 and my projects timeout when running fastlane. Is this because its not supported yet?

**Comment by taquitos** [comment]
Yeah, it's mostly working with the exception of screenshots. 
Please file any issues you see, as we're trying to make sure it works 💯 
👍

**Comment by st3fan** [comment]
@taquitos what is the best issue to follow for the screenshots work?

**Comment by taquitos** [comment]
The PR we're working on is: https://github.com/fastlane/fastlane/pull/9570
I think because there are so many issues, it's best to just watch that PR 😄
