### ISSUE TITLE
Snapshot Xcode 9 Concurrent Devices 

### ISSUE THREAD

**Issue by fishcharlie** [fastlane/fastlane#10057]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In Xcode 9 Apple released concurrent simulator devices. Is this supported in Fastlane Snapshot to speed up the time of taking these screenshots? I tried to search on the documentation and through the issues and can't find anything related to this.

If it is supported is there documentation for how to enable this? If not is this a feature that is planned or in development?

**Comment by ohayon** [comment]
Hey @fishcharlie - we are currently working on this! 😄  You can track the PR here: https://github.com/fastlane/fastlane/pull/9570 🚀

**Comment by fishcharlie** [comment]
@ohayon Awesome! Is there an ETA for when this will be released? And I take it documentation will be added/updated?

**Comment by ohayon** [comment]
@fishcharlie no firm ETA at the moment, but we are working to get it out there as soon as we can. Definitely we will make sure to update all relevant docs as well! 😄

**Comment by fishcharlie** [comment]
@ohayon Looks like this was released but I can't find any documentation regarding this. Mind providing an update on documentation?

**Comment by mpirri** [comment]
@fishcharlie Look into using the `concurrent_simulators` option when calling `shapshot`. You can learn more by doing `fastlane snapshot --help` to read about the option.  I hope this is helpful, please let us know if you have other questions about _fastlane_! 🚀

**Comment by fishcharlie** [comment]
@mpirri I feel like this should be included in the GitHub docs as well, with maybe an example. Just out of curiosity what does `[VALUE]` relate to? Is that the max number of concurrent simulators that I want to run at any given time?

**Comment by ohayon** [comment]
Hey @fishcharlie just updated docs here: https://github.com/fastlane/fastlane/pull/10182

**Comment by ohayon** [comment]
🚀
