### ISSUE TITLE
resign problem

### ISSUE THREAD

**Issue by LZS-bobo** [fastlane/fastlane#10054]
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: write permissions error
security: problem decoding
Print: Entry, ":Entitlements:application-identifier", Does Not Exist
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: write permissions error
security: problem decoding
Print: Entry, ":Entitlements:application-identifier", Does Not Exist
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: write permissions error
security: problem decoding
Encountered an error, aborting!

**Comment by taquitos** [comment]
Hey @LZS-bobo, could you attach your complete output from the tool along with `fastlane env` as well? That should help us diagnose this stuff 🔑

**Comment by LZS-bobo** [comment]
@taquitos

**Comment by LZS-bobo** [comment]
@taquitos

**Comment by LZS-bobo** [comment]
fastlane 2.50.0
when I use php to run  ` system("cd /Applications/MAMP/htdocs/spaceship;fastlane sigh resign --signing_identity 87F59F4A0D5ED24740FB7167940833E441B13928");` 

There are.Ipa and.Mobileprovision under the /Applications/MAMP/htdocs/spaceship folder
