### ISSUE TITLE
Running Snapshot On a Real Device, How To?

### ISSUE THREAD

**Issue by dannyiss** [fastlane/fastlane#10065]
### New Issue Checklist

- [✅  ] Updated fastlane to the latest version
- [ ✅ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅  ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

When I am trying to run Snapshot on a real device, it is not letting me select the device by UUID or Device Name, I have looked at other github issues and it seems to be possible but through the snapfile & command line I am not able to get this to work. I have not been able to find the exact command to run either.

Error setting value '["XXXXXXXXX"]' for option 'devices'

[!] Device 'XXXXXXXX' not in list of available simulators 'iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, iPhone 6s Plus, iPhone 7, iPhone 7 Plus, iPhone SE, iPad Air, iPad Air 2, generation), iPad Pro (9.7 inch), iPad Pro (12.9 inch), iPad Pro (10.5-inch), Apple TV 1080p, Apple Watch - 38mm, Apple Watch - 42mm, Apple Watch Series 2 - 38mm, Apple Watch Series 2 - 42mm'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.6                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.2 (Apple Git-90)                |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.6 (16G29)                         |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.41.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode-beta.app/Contents/Developer'
    #cocoapods
    xcode_select "/Applications/Xcode-beta.app"
  end

  desc "Runs all the tests"
  lane :test do
    scan(
  workspace: "Hurdlr.xcworkspace",
  scheme: "HurdlrTests",
  clean: false
)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
   workspace: 'Hurdlr.xcworkspace',
   export_options: './ExportOptions.plist',
   scheme: 'Hurdlr',
   silent: true,
   clean: true,
   output_directory: '/Users/u590214/Desktop',
   output_name: 'Hurdlr.ipa'
 )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.wellsfargo.dct.Hurdlr" # The bundle identifier of your app
apple_id "daniel.isserow@wellsfargo.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.41.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| excon                     | 0.57.0       |
| plist                     | 3.3.0        |
| claide                    | 1.0.2        |
</details>

*generated on:* **2017-08-16**
</details>

**Comment by taquitos** [comment]
Currently not supported. It looks like @matthewellis was working on this in https://github.com/fastlane/fastlane/pull/5159

**Comment by dannyiss** [comment]
AHHH, I didn't scroll that far down to see that it was still in development! Thanks, been scratching my head all day thinking why isn't it working? If I could use a proxy on the simulator then I wouldn't need this feature.

**Comment by taquitos** [comment]
@dannyiss you can use a proxy! I use [Charles](https://www.charlesproxy.com)
It's the best 👍

**Comment by dannyiss** [comment]
Enterprise environment 👎  if it was a local env I know snapshot & all other fastlane tools work. But yeah. Thanks though!

**Comment by jgavris** [comment]
With Xcode 9 coming soon, I also plan to jump in and hopefully get #5159 over the line (our project is somehow broken on 8 wrt the injected `LD_LIBRARY_PATH`, is fixed in 9). So it would be great to unlock device testing.

**Comment by matthewellis** [comment]
Hey @jgavris i would be happy to collaborate on getting this feature done. Feel free to contact me and check out the branch i have for this on my fork.
