### ISSUE TITLE
Building fine locally, failing on the Bitrise build server

### ISSUE THREAD

**Issue by lukaleli** [fastlane/fastlane#10062]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to automate uploading my app for beta testing to Crashlytics. It works well locally when running `fastlane ios beta`, but I have a problem to make it working on the Bitrise build server.

**NOTE**: 
Before that I was using Testflight and it was working correctly. The only difference was that I was using `appstore` match type, rather than `adhoc`.

In the Bitrise log output I can see it successfully downloads all certificates and provisioning profiles, but eventually it fails with the error below:

```Shell
...
▸ Check Dependencies
❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'
❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'
** ARCHIVE FAILED **
The following build commands failed:
Check dependencies
(1 failure)
ERROR [2017-08-16 03:44:50.75]: Exit status: 65
+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.53.1                  |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS10.3.sdk        |
+---------------+-------------------------+
INFO [2017-08-16 03:44:50.80]: ▸ Check dependencies
INFO [2017-08-16 03:44:50.80]: ▸ No iOS profile matching '42XXXXXXch AppStore de.XXX.XXXl' found:  Xcode couldn't find a profile matching '42XXXXXXU9/match AppStore de.XXX.XXX'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
INFO [2017-08-16 03:44:50.80]: ▸ Code signing is required for product type 'Application' in SDK 'iOS 10.3'
INFO [2017-08-16 03:44:50.80]: ▸ Code signing is required for product type 'Application' in SDK 'iOS 10.3'
INFO [2017-08-16 03:44:50.80]: 
ERROR [2017-08-16 03:44:50.80]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2017-08-16 03:44:50.81]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2017-08-16 03:44:50.81]: 📋  /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/fastlane_logs732274838/gym/goodly-staging.log
INFO [2017-08-16 03:44:50.81]: 
ERROR [2017-08-16 03:44:50.81]: Looks like fastlane ran into a build/archive error with your project
ERROR [2017-08-16 03:44:50.81]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2017-08-16 03:44:50.81]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2017-08-16 03:44:50.81]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2017-08-16 03:44:50.81]: sure your project is set up correctly.
ERROR [2017-08-16 03:44:50.81]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2017-08-16 03:44:50.81]: the full commands printed out in yellow in the above log.
ERROR [2017-08-16 03:44:50.81]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2017-08-16 03:44:50.81]: 
WARN [2017-08-16 03:44:50.81]: Lane Context:
INFO [2017-08-16 03:44:50.81]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_TYPE=>"ad-hoc", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"de.XXX.XXX"=>"match AdHoc de.XXX.XXX"}}
ERROR [2017-08-16 03:44:50.81]: Error building the application - see the log above
INFO [2017-08-16 03:44:50.82]: Successfully generated documentation at path '/Users/vagrant/git/ios/fastlane/README.md'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.9"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Crashlytics"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: 'development', 
      git_url: "git@github.com:XXX/certs.git",
      verbose: true,
      skip_docs: true,
      force_for_new_devices: true
    )
    match(
      type: "adhoc", 
      force_for_new_devices: true,
      git_url: "git@github.com:XXX/certs.git",
      verbose: true,
      skip_docs: true
    )
    gym(scheme: "staging", export_method: "ad-hoc")
    crashlytics(api_token: ENV["CRASHLYTICS_API_KEY"],
              build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
              groups: "internal")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(
    type: "appstore",
    readonly: true,
    verbose: true,
    git_url: "git@github.com:XXX/certs.git"
    )
    # snapshot
    gym(scheme: "goodly") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # This block is called when there's an error
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "de.XXX.XXX"
apple_id "dev@XXX.de"

team_id "42XXXXXXU9"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.6        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-16**
</details>

I'm fighting with this the second day and I've read a lot of issues. Still without any success. Would appreciate any hints.

**Comment by taquitos** [comment]
Yup, you nailed it. If `export_method: ad-hoc` is being used, it's going to fail if it tries to use the `AppStore` cert (which is definitely the problem here). 
So, the question is: why is it using the `AppStore` cert if everything specified is `ad-hoc`? My first guess would be to examine how the project is setup in Xcode and see how you have setup your provisioning profiles. _match_ sets up some environment variables that can be picked up there, so if you're not using that, I would suggest giving that a try.
In the past, I've used this to help: [Xcode project setup guide](https://docs.fastlane.tools/codesigning/xcode-project/)

**Comment by lukaleli** [comment]
@taquitos Yeah, I've read it and I'm using provisioning profiles generated by match:
![provprof](https://user-images.githubusercontent.com/2745825/29378232-956f3230-82be-11e7-884a-b211909394c3.png)
Why is it working locally and not on the build server? 
PS. I've pasted the most relevant part of the output log. I truncated build logs which were pretty normal.

**Comment by taquitos** [comment]
My guess at the reason why it's working locally is because you have all the certs installed (App Store). I'm thinking that your app is actually getting signed by the App Store certs on your local machine.

**Comment by lukaleli** [comment]
Yeah, that was it! Thanks for the hints. Anyway it's weird because when I want to use `export_method: ad-hoc` I need to match appstore provisioning profile as well to make it work.

**Comment by taquitos** [comment]
Yeah, that's still weird to me, maybe the closest match is your App Store provisioning profiles. You should have separate ad-hoc provisioning profiles too.
Although... if it works now, my motto is "why fix what isn't broken" 😂
