### ISSUE TITLE
Permission Error OSX El Capitan

### ISSUE THREAD

**Issue by scisci** [fastlane/fastlane#1006]
When installing the gem under El Capitan, there is a permission error on my machine. Installing using this instead worked:

`sudo gem install -n /usr/local/bin fastlane`

Might want to mention in the docs.

**Comment by xfreebird** [comment]
@scisci strange, I never had such issues, despite using El Capitan.

**Comment by scisci** [comment]
OK, yeah I have an old machine that's been through many years of different environments so it could be fairly specific. Nevertheless it was an issue, but perhaps not fastlane specific. so just an FYI i guess.

**Comment by ianblair44** [comment]
@scisci I have been trying to figure this out for hours! This definitely worked. I would highly recommend including this as a common issue.

**Comment by scisci** [comment]
hi @ianblair44, I ended up finding a better solution which was to fix the permissions on usr/local folder (I think). Somehow I had lost permissions and therefore was having trouble installing a lot of stuff. Anyway, both ways work.

**Comment by ianblair44** [comment]
@scisci what commands did you run to repair the permissions? That definitely seems to be the issue.

**Comment by vpolouchkine** [comment]
@ianblair44 Is this still an issue for you?

**Comment by ianblair44** [comment]
@vpolouchkine not anymore. When I installed it using scisci's advice it worked just fine. 

sudo gem install -n /usr/local/bin fastlane

Maybe a few things I should note. I don't have RVM installed or anything like that, just running default Ruby on OSX. I'm not a Ruby dev, so I don't have much of a reason to go the extra mile to try and get a Ruby environment set up.

**Comment by vpolouchkine** [comment]
OK, great! Thanks for confirming.

**Comment by mosesoak** [comment]
@vpolouchkine I hit this as well with a non-RVM machine that lost its connection to fastlane after upgrading to El Capitan. The special gem install command suggested above fixed it for me but I'm hoping that I don't have to do it in the future and can just return to a regular sudo gem install fastlane - time will tell.

**Comment by TKBurner** [comment]
@mosesoak Thanks for following up. This all depends if you want to use Fastlane on system ruby or with RVM.

**Comment by mosesoak** [comment]
I think I uninstalled RVM because I don't use Ruby enough to make it worth the potential issues, so I'm just doing system Ruby for now...

**Comment by TKBurner** [comment]
Thanks for following up @mosesoak! Because you are using the system Ruby, for now you'll need to add this extra info to the command. If you type 'which ruby' into a command line, you can see that the path is the same.
