### ISSUE TITLE
Scan: test_without_building not working like expected

### ISSUE THREAD

**Issue by eikebartels** [fastlane/fastlane#10061]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I used this [examples from the docs](https://docs.fastlane.tools/actions/#scan)

I would like to use scan to build it once (build_for_testing) and then test different tests in different lanes. 

For creating the `xctestrun` I use the following command which works like expected:

```
scan(
      workspace: 'Awesome.xcworkspace',
      scheme: 'AwesomeScheme',
      derived_data_path: "target/derivedData",
      sdk:'iphonesimulator',
      build_for_testing: true,
      slack_only_on_failure:true
    )
```

In the next step I would like to use the generated `xctestrun` file to run the `UnitTests`. This is not working. 

```
scan(
        xctestrun: 'target/derivedData/Build/Products/Awesome_iphonesimulator10.3-x86_64.xctestrun',
        destination: '"platform=iOS Simulator,name=iPhone 6',
        only_testing:'UnitTests'
    )
```

The output is: 

```
DEBUG [2017-08-16 10:27:35.78]: Checking if there are any plugins that should be loaded...
INFO [2017-08-16 10:27:35.99]: -------------------------------------------------
INFO [2017-08-16 10:27:35.99]: --- Step: Verifying required fastlane version ---
INFO [2017-08-16 10:27:35.99]: -------------------------------------------------
INFO [2017-08-16 10:27:35.99]: Your fastlane version 2.53.1 matches the minimum requirement of 2.53.1  ✅
INFO [2017-08-16 10:27:35.99]: ------------------------------
INFO [2017-08-16 10:27:35.99]: --- Step: default_platform ---
INFO [2017-08-16 10:27:35.99]: ------------------------------
INFO [2017-08-16 10:27:36.01]: Driving the lane 'ios unit_test' 🚀
INFO [2017-08-16 10:27:36.01]: ------------------
INFO [2017-08-16 10:27:36.01]: --- Step: scan ---
INFO [2017-08-16 10:27:36.01]: ------------------
INFO [2017-08-16 10:27:36.05]: $ xcodebuild -list -workspace ./Awesome.xcworkspace
Select Scheme:
1. Awesome Alpha
2. App Store Screenshots
3. Awesome
```

Before fastlane I was using the following command which works correctly: 

`xcodebuild test-without-building -xctestrun "target/derivedData/Build/Products/Awesome_iphonesimulator10.3-x86_64.xctestrun" -destination "platform=iOS Simulator,name=iPhone 6" -only-testing:UnitTests`

From this I would assume that scan should looks like: 

```
scan(
        xctestrun: 'target/derivedData/Build/Products/Awesome_iphonesimulator10.3-x86_64.xctestrun',
        destination: '"platform=iOS Simulator,name=iPhone 6',
        only_testing:'UnitTests',
        test_without_building:true
    )
```

But the output is the following:

```
INFO [2017-08-16 10:33:54.41]: -------------------------------------------------
INFO [2017-08-16 10:33:54.41]: --- Step: Verifying required fastlane version ---
INFO [2017-08-16 10:33:54.41]: -------------------------------------------------
INFO [2017-08-16 10:33:54.41]: Your fastlane version 2.53.1 matches the minimum requirement of 2.53.1  ✅
INFO [2017-08-16 10:33:54.42]: ------------------------------
INFO [2017-08-16 10:33:54.42]: --- Step: default_platform ---
INFO [2017-08-16 10:33:54.42]: ------------------------------
INFO [2017-08-16 10:33:54.43]: Driving the lane 'ios unit_test' 🚀
INFO [2017-08-16 10:33:54.44]: ------------------
INFO [2017-08-16 10:33:54.44]: --- Step: scan ---
INFO [2017-08-16 10:33:54.44]: ------------------
ERROR [2017-08-16 10:33:54.46]: You passed invalid parameters to 'scan'.
ERROR [2017-08-16 10:33:54.46]: Check out the error below and available options by running `fastlane action scan`
WARN [2017-08-16 10:33:56.61]: Lane Context:
INFO [2017-08-16 10:33:56.61]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios unit_test"}
ERROR [2017-08-16 10:33:56.61]: Unresolved conflict between options: 'xctestrun' and 'test_without_building'
```

### Environment
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13 (17A330h)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :ios

platform :ios do

  ############################## PRE ##############################

  before_all do
    ENV["SLACK_URL"] = ""
  end

  desc "Build for testing"
  lane :build_for_testing do
    scan(
      workspace: 'Awesome.xcworkspace',
      scheme: 'AwesomeScheme',
      derived_data_path: "target/derivedData",
      sdk:'iphonesimulator',
      build_for_testing: true,
      slack_only_on_failure:true
    )

    slack(
      message: "Successfully built for testing"
    )
  end

  desc "Unit test on iPhone"
  lane :unit_test do
    scan(
        xctestrun: 'target/derivedData/Build/Products/Awesome_iphonesimulator10.3-x86_64.xctestrun',
        destination: '"platform=iOS Simulator,name=iPhone 6',
        only_testing:'UnitTests'
    )
    
    slack(
      message: "Successfully unit tested"
    )
  end

  

  after_all do |lane|
  
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.....lab" # The bundle identifier of your app
apple_id "...@com" # Your Apple email address

team_id "...." # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| plist                     | 3.3.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
</details>

*generated on:* **2017-08-16**
</details>
```

**Comment by taquitos** [comment]
Yeah, it looks like we restrict `xctestrun`, it's not allowed to run with `build_for_testing` or `test_without_building`
which, looking at the docs (as I suspected) you're totally right... you should be able to do what you're trying to do.

one thing you can try is running _fastlane_ from a local checkout. inside `scan/lib/scan/options.rb#159`, you can remove `test_without_building` from `conflicting_options:`  array

**Comment by eikebartels** [comment]
@taquitos great thanks a lot and thanks for the fix! :)
