### ISSUE TITLE
Error when trying to upload file(s) to HockeyApp: 422

### ISSUE THREAD

**Issue by Andrey-Tsiporin-Yumasoft** [fastlane/fastlane#10072]
### New Issue Checklist

- ✅  Updated fastlane to the latest version
- ✅  I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- ✅  I read [docs.fastlane.tools](https://docs.fastlane.tools)
- ✅  I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I’ve tried to use Fastlane to download dSYMs from iTunes Connect and upload it to HockeyApp.
dSYMs download is fine, dSYM.zip looks normal (It works fine if I upload it manually to HockeyApp)

However, with Fastlane I have an error:
[!] Error when trying to upload file(s) to HockeyApp: 422 - {"status"=>"error", "message"=>"Bundle version is blank or could not be parsed. Please check the file format of your symbols file and make sure the bundle identifier of your app matches the value on HockeyApp."}

But bundle identifiers are the same.

When I tried to use local dSYMs without bitcode, they worked fine with Fastlane.
##### Complete output when running fastlane, including the stack trace and command used

download_dsyms(
     team_id:team_id,
     app_identifier:identifier,
     version: version,
     build_number: build)

hockey(api_token: token,
              dsym:dSYM_path,
              upload_dsym_only:true,
              public_identifier:hockeyId,
              strategy:'replace',
              notify:'0',
              bundle_short_version:version,
              bundle_version:[version, build].join(''))

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

**Comment by gtatgh** [comment]
Maybe the following link helps you: [support.hockeyapp.net](https://support.hockeyapp.net/discussions/problems/52733-dsym-symbolication-failing-with-bitcode-enabled)

**Comment by taquitos** [comment]
@gtatgh good find with that help doc, that seems to describe exactly the problem @Andrey-Tsiporin-Yumasoft is seeing.

Apple is mangling the info.plist files, and HockyApp is refusing them since they don't match what is expected anymore. 

They claim it works if you upload via their mac app too. So maybe we need to find a new API to use.

**Comment by taquitos** [comment]
Also, HockyApp has a fastlane plugin that looks like it might be able to help. Have you tried that yet?

**Comment by Andrey-Tsiporin-Yumasoft** [comment]
Thank you both. It really helped.
I’ve changed content of dSYMs plist and now it works.
