### ISSUE TITLE
Screenshots are not uploaded after delivere for some languages like ru, it etc.

### ISSUE THREAD

**Issue by StefaniOS** [fastlane/fastlane#10073]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My issue is similar to #9340: screenshots are fine, but some of them are missing by delivery to ITC .
My problematic  languages are defined in snapfile like this: "it-IT", "ru-RU" and the folder names for the generated screenshots have the same names, which causes the issue, I guess.

 When I manually rename folders to "it"  and "ru" everything works fine and all screenshots can be uploaded. So the correct folder names for Russian and Italian should be "ru" and "it" to be accepted by ITC.

When I use just "it" and "ru" in snapfile, the folder names are exactly what I want, but then the _countryCode_ for _NSLocale_ is _nil_  in the App, and the snapshots are incorrect.

I tried the other format like: ["it", "it_IT"], ["ru", "ru_RU"], it works fine for screenshots, but again, the folder names are invalid.

Anyways, since we use fastlane, there should be a better solution, than changing folder names manually.
I guess, there is a bug in the code: so instead of naming the folders by the second parameter, which indicates the region, snapshot should  name the folders by the first argument, which shows the language.

Unfortunately I'm not a ruby expert to test it myself. If someone could check it please... @joshdholtz   @KrauseFx

**Comment by joshdholtz** [comment]
@StefaniOS I totes have a fix started for this I should really finish 😇 I will work on this tonight cause I really need to finish this 🙃
