### ISSUE TITLE
match [re]create certificate without nuking

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#10076]
We do work for other companies and usually have to live with multiple Accounts and Certificates co-existing on the Member Center. Also sometimes our certificates get revoked by mistake by other teams.

How can we make our match create/renew the certificates/provisioning just for the ids we should have access to?

**Comment by taquitos** [comment]
So you're basically looking for "here are a bunch of app ids, nuke them, and recreate them"? Is that what you're saying?

**Comment by lkraider** [comment]
Indeed, specially to avoid nuking other appids and unrelated signing certificates.

**Comment by divick** [comment]
+1

**Comment by Felipe-Banno** [comment]
This is very important feature... Nuke deletes everything.
We need at least a way to nuke only the certificates and provision profiles created by Match

**Comment by lkraider** [comment]
Don't nuke me bot 😢

**Comment by lkraider** [comment]
Just checked, still not available in fastlane-2.80.0

**Comment by KrauseFx** [comment]
Sorry, we don't plan on extending the nuke feature as of now. For now, does it work for you to just manually revoke the certificates and profiles, and potentially also delete them from the match git repo?

**Comment by lkraider** [comment]
Hi, yes can be done manually, although it's a pain.

No problem if it's not on the roadmap, just wanted to make aware of this request. Sorry I can't supply a PR either. Issue can be closed if there are no plans to add this. 👍

**Comment by joshdholtz** [comment]
@lkraider I'm going to close this issue for now but I will keep this as a feature on the back burner incase I'm ever needing some more work to do 🙃
