### ISSUE TITLE
How to auto-upload generated apk to Slack?

### ISSUE THREAD

**Issue by joegoodall1** [fastlane/fastlane#10079]
Despite Googling and looked through the issues here I've failed to find a way to auto-upload an apk that has been built using Fastlane to a Slack channel.

Has anybody else managed to do this and if so, how?

**Comment by taquitos** [comment]
While totally possible, it's not implemented in _fastlane_, but it would be a really cool addition to the slack action that we have. It looks pretty complicated (https://api.slack.com/tutorials/working-with-files) but definitely possible 👍

**Comment by joegoodall1** [comment]
Hi @taquitos, thanks for getting back to me. 

Is there any way this might be officially implemented in the near future?

If not I could have a go and share it with the community if I work it out.

**Comment by taquitos** [comment]
We're super busy at the moment, but it could be something somebody in the community might want to pick up and run with. If that's something you'd like to do, we have a getting started guide: [Your First PR](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) and we'd be happy to provide any guidance 😄
