### ISSUE TITLE
testflight is not updating What to Test and ignores skip_submission

### ISSUE THREAD

**Issue by neilco** [fastlane/fastlane#10074]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

- Setting the `changelog` parameter does not update **What to Test** in iTunes Connect. 
- Setting `skip_submission` to `true` does not skip submission. My iTunes Connect User are still receiving the build notifications. 

`testflight` command used in my Fastfile: 

```ruby
testflight(changelog: release_notes, 
           skip_submission: true, 
           skip_waiting_for_build_processing: true)
```

`release_notes` is a multi-line string read from a text file. 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.gem/ruby/2.3.2/bin/fastlane              |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-table            | 1.4.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| plist                     | 3.2.0        |
| faraday                   | 0.11.0       |
| faraday_middleware        | 0.11.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
</details>

*generated on:* **2017-08-17**
</details>

**Comment by taquitos** [comment]
Hey @neilco, could you attach your complete output from the tool, and your fastfile as well? That should help us diagnose this stuff.

**Comment by neilco** [comment]
Here's the captured output with sensitive info redacted out:

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/neil/Desktop/SimpleFastlane/fastlane/Appfile'
- apple_id: '▉▉▉▉▉▉▉▉▉▉▉▉'
- team_id: '▉▉▉▉▉▉'
- app_identifier: 'co.cwbrn.FastlaneSample'
-------

+----------+--------------------------------------+
|   Detected Values from './fastlane/Matchfile'   |
+----------+--------------------------------------+
| git_url  | git@github.com:neilco/▉▉▉▉▉▉▉▉▉.git  |
| username | ▉▉▉▉▉▉▉▉▉▉▉▉                         |
+----------+--------------------------------------+


+-----------------------+--------------------------------------+
|                   Summary for match 2.53.1                   |
+-----------------------+--------------------------------------+
| type                  | appstore                             |
| force_for_new_devices | true                                 |
| git_url               | git@github.com:neilco/Apple-Certifi  |
|                       | cates.git                            |
| username              | ▉▉▉▉▉▉▉▉▉▉▉▉                         |
| git_branch            | master                               |
| app_identifier        | co.cwbrn.FastlaneSample              |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| team_id               | ▉▉▉▉▉▉                               |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

Loading session from '/Users/neil/.fastlane/spaceship/▉▉▉▉▉▉▉▉▉▉▉▉/cookie'

+-------------------+------------------------------------------------+
|                       Installed Certificate                        |
+-------------------+------------------------------------------------+
| User ID           | ▉▉▉▉▉▉                                         |
| Common Name       | iPhone Distribution: Neil Cowburn (▉▉▉▉▉▉)     |
| Organisation Unit | ▉▉▉▉▉▉                                         |
| Organisation      | Neil Cowburn                                   |
| Country           | US                                             |
| Start Datetime    | Aug 18 08:56:11 2017 GMT                       |
| End Datetime      | Aug 18 08:56:11 2018 GMT                       |
+-------------------+------------------------------------------------+


+-------------------------------------+-------------------------+
|                    Summary for sigh 2.53.1                    |
+-------------------------------------+-------------------------+
| app_identifier                      | co.cwbrn.FastlaneSample |
| username                            | ▉▉▉▉▉▉▉▉▉▉▉▉            |
| force                               | true                    |
| cert_id                             | ▉▉▉▉▉▉                  |
| provisioning_name                   | match AppStore          |
|                                     | co.cwbrn.FastlaneSample |
| ignore_profiles_with_different_name | true                    |
| team_id                             | ▉▉▉▉▉▉                  |
| platform                            | ios                     |
| adhoc                               | false                   |
| development                         | false                   |
| skip_install                        | false                   |
| skip_fetch_profiles                 | false                   |
| skip_certificate_verification       | false                   |
+-------------------------------------+-------------------------+

Loading session from '/Users/neil/.fastlane/spaceship/▉▉▉▉▉▉▉▉▉▉▉▉/cookie'
/var/folders/bq/3sn8hm7d565g6f1y4kb9yzf40000gn/T/d20170818-64644-1hftinz/profiles/appstore/AppStore_co.cwbrn.FastlaneSample.mobileprovision

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | co.cwbrn.FastlaneSamp  |
|                     |                        | le                     |
| Type                |                        | appstore               |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_co.cwbrn.Fastlan  | 4c0e2574-81fa-4448-9f  |
|                     | eSample_appstore       | 5a-ca2baad96a1c        |
| Profile Name        | sigh_co.cwbrn.Fastlan  | match AppStore         |
|                     | eSample_appstore_prof  | co.cwbrn.FastlaneSamp  |
|                     | ile-name               | le                     |
| Profile Path        | sigh_co.cwbrn.Fastlan  | /Users/neil/Library/M  |
|                     | eSample_appstore_prof  | obileDevice/Provision  |
|                     | ile-path               | ing                    |
|                     |                        | Profiles/4c0e2574-81f  |
|                     |                        | a-4448-9f5a-ca2baad96  |
|                     |                        | a1c.mobileprovision    |
| Development Team ID | sigh_co.cwbrn.Fastlan  | ▉▉▉▉▉▉                 |
|                     | eSample_appstore_team  |                        |
|                     | -id                    |                        |
+---------------------+------------------------+------------------------+


+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.53.1                            |
+--------------------------------------+--------------------------------------+
| scheme                               | Beta                                 |
| include_bitcode                      | false                                |
| export_method                        | app-store                            |
| export_options.provisioningProfiles  | match AppStore                       |
| .co.cwbrn.FastlaneSample             | co.cwbrn.FastlaneSample              |
| project                              | ./SimpleFastlane.xcodeproj           |
| destination                          | generic/platform=iOS                 |
| output_name                          | SimpleFastlane                       |
| build_path                           | /Users/neil/Library/Developer/Xcode  |
|                                      | /Archives/2017-08-18                 |
| clean                                | false                                |
| output_directory                     | .                                    |
| silent                               | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| xcode_path                           | /Applications/Xcode.app              |
+--------------------------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -scheme Beta                         |                      |
| -project ./SimpleFastlane.xcodeproj  |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/neil/Library/Developer/Xcode  |                      |
| /Archives/2017-08-18/SimpleFastlane  |                      |
| \ 2017-08-18\ 11.02.25.xcarchive     |                      |
| archive                              |                      |
| | tee                                |                      |
| /Users/neil/Library/Logs/gym/Simple  |                      |
| Fastlane-Beta.log                    |                      |
| | xcpretty                           |                      |
+--------------------------------------+----------------------+
+--------------------------------------+--------------------------------------+
|                          Generated Package Command                          |
+--------------------------------------+--------------------------------------+
| Option                               | Value                                |
+--------------------------------------+--------------------------------------+
| /usr/bin/xcrun                       |                                      |
| /Users/neil/.fastlane/bin/bundle/li  |                                      |
| b/ruby/gems/2.2.0/gems/fastlane-2.5  |                                      |
| 3.1/gym/lib/assets/wrap_xcodebuild/  |                                      |
| xcbuild-safe.sh -exportArchive       |                                      |
| -exportOptionsPlist                  | /var/folders/bq/3sn8hm7d565g6f1y4kb  |
|                                      | 9yzf40000gn/T/gym_config20170818-64  |
|                                      | 644-18ja1jj.plist                    |
| -archivePath                         |                                      |
| /Users/neil/Library/Developer/Xcode  |                                      |
| /Archives/2017-08-18/SimpleFastlane  |                                      |
| \ 2017-08-18\ 11.02.25.xcarchive     |                                      |
| -exportPath                          | /var/folders/bq/3sn8hm7d565g6f1y4kb  |
|                                      | 9yzf40000gn/T/gym_output20170818-64  |
|                                      | 644-expi7l                           |
+--------------------------------------+--------------------------------------+

Loading session from '/Users/neil/.fastlane/spaceship/▉▉▉▉▉▉▉▉▉▉▉▉/cookie'
Looking for iTunes Connect Team with ID 19328

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | match                  | 22          |
| 4    | number_of_commits      | 0           |
| 5    | increment_build_numbe  | 1           |
|      | r                      |             |
| 6    | get_version_number     | 0           |
| 7    | get_version_number     | 0           |
| 8    | feeld_release_notes    | 0           |
| 9    | commit_build_if_neces  | 0           |
|      | sary                   |             |
| 10   | gym                    | 19          |
| 11   | get_version_number     | 0           |
| 12   | testflight             | 58          |
+------+------------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.52.0"
default_platform :ios

def carthage_needs_update
    md5hash = File.read(".carthage/cache")
    unless md5hash.nil?
        return Digest::MD5.hexdigest(File.read("../Cartfile.resolved")) == md5hash
    end
    return true
end

platform :ios do
  error do  |lane, exception|
    # Reset the app icons
    app_icon_files = Dir["#{File.expand_path('..')}/iOS-Client/**/AppIcon.appiconset/*.png"]
    reset_git_repo(files: app_icon_files, force: true) if app_icon_files.length > 0
  end
  
  private_lane :run_carthage_update do 
    if carthage_needs_update
      carthage(platform: 'ios', use_binaries: false)
    end
  end

  # ----------------------------------------------------------------------------------------------------------------------------------------

  desc "Submit a new beta build to TestFlight"
  desc "This will use the production server"
  lane :beta do
    # Make sure the repository is in a good state before deploying
    # ensure_git_status_clean
    # ensure_git_release_branch

    # Update certs and profiles if necessary
    match(type: "appstore", force_for_new_devices: true)

    # Increment the build number using the number of git commits
    build_number = number_of_commits + 1 # Add one here so that it matches the repo when we next commit
    increment_build_number(build_number: build_number)
    app_version = "#{get_version_number}-#{build_number}"

    # Now we have the version number, check for the release notes
    # and fail if the release notes cannot be found
    release_notes = read_release_notes(version: get_version_number)
    if release_notes.nil?
      return
    end

    # Commit version number bump if that is appropriate
    if commit_build_if_necessary(xcodeproj: "SimpleFastlane.xcodeproj") == false
      UI.message("Commit skipped. Reverting build number increment to #{build_number - 1}")
      build_number = number_of_commits
      increment_build_number(build_number: build_number)
      app_version = "#{get_version_number}-#{build_number}"
    end

    # Build the app
    gym(scheme: "Beta", include_bitcode: false)

    # Distribute the build to the Internal group via TestFlight
    UI.message("Uploading v#{get_version_number} to TestFlight")
    testflight(changelog: release_notes, skip_submission: true, skip_waiting_for_build_processing: true)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "▉▉▉▉▉▉▉▉▉▉▉▉"
team_id "▉▉▉▉▉▉"

app_identifier "co.cwbrn.FastlaneSample"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| psych                     | 2.0.8        |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2017-08-18**
</details>
