### ISSUE TITLE
issue template: fastlane's --capture_output includes Fastfile and other config files, which have Slack webhook URLs and other private credentials in them

### ISSUE THREAD

**Issue by cbowns** [fastlane/fastlane#10082]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When attaching fastlane output to an issue with `--capture_output`, I was surprised to find my full Fastfile in the output as well. I'm now changing a webhook URL and some S3 credentials as a result.

While I understand that it's really useful to have these in the issue, it's also an information disclosure problem: there are usernames for `match` in our Matchfile, webhooks in the Fastfile, and other bits of private information in these files.

**Comment by taquitos** [comment]
Wooof, yeah that's a good call out. We should probably scrub web hook urls and credentials if they follow a really standard format.

**Comment by cbowns** [comment]
@taquitos I want to see this issue kept open.

**Comment by janpio** [comment]
@cbowns Although this is a valid point (I also hate so scrub them from the output each time I post an issue...), do you have an idea how this could be realized?

A good first step would probably be to identify a list of sensitive bits. 
Is the team id and login email address a sensitive information for example?

**Comment by cbowns** [comment]
Yes, those always are.

**Comment by KrauseFx** [comment]
Seems like a can of worms, as there is an unlimited numbers of things that could be considered sensitive... I'm all for removing output, but it's gonna be tricky to implement it the right way

**Comment by cbowns** [comment]
Agreed.

How about changing/adding a mention of this in the issue template or in fastlane's debug-for-an-issue output? I'm fine with scrubbing things out, I was just surprised by what was in there.

**Comment by taquitos** [comment]
Updated our issue template: https://github.com/fastlane/fastlane/pull/11412

**Comment by KrauseFx** [comment]
Awesome 👍 Fixed with https://github.com/fastlane/fastlane/pull/11412
