### ISSUE TITLE
[match] force_for_new_devices always recreates App Store profiles

### ISSUE THREAD

**Issue by Boerworz** [fastlane/fastlane#10103]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We use `match` on our CI server when making AdHoc and App Store builds, and specify `force_for_new_devices: true` for both of these types since we figured we'd always want to recreate the profiles when there were new devices in the developer portal. However, we recently noticed that the App Store provisioning profile was _always_ recreated, bloating our match repository.

After looking through the source code for `match`, we realized that this is due to how `match` checks if there are new devices in the developer portal. What it does is that it retrieves the (App Store) provisioning profile from the developer portal and compares the number of devices in the profile with the total number of devices in the developer portal. This works well for Development and Ad Hoc provisioning profiles, but since App Store provisioning profiles don't contain any devices, the [`device_count_different?`](https://github.com/fastlane/fastlane/blob/master/match/lib/match/runner.rb#L180) method always returns true (if there are more than 0 devices in the developer portal, which we can probably safely assume 🙂).

We can avoid this issue by specifying `false` for `force_for_new_devices`, but since the documentation for `force_for_new_devices` states that the provisioning profile should be renewed if _the device count on the developer portal has changed_, we believe this is a bug. We propose that the `force_for_new_devices` flag be ignored when invoking `match` for App Store profiles. If you want to force the App Store profiles to be renewed, the `force` flag should be used.

If this is something you agree with, I'd be happy to create a pull request that implements this change.

**Comment by Boerworz** [comment]
Oops, I pressed Enter before I was done writing the issue 😬 I'm editing it now.

**Comment by mpirri** [comment]
This sounds like an amazing contribution - we would love to review a PR to add this functionality! Thanks so much for reaching out! 🚀

**Comment by Boerworz** [comment]
Cool, I'll get started on a PR! 😃

**Comment by JagCesar** [comment]
This has been fixed in https://github.com/fastlane/fastlane/pull/10141. Kill it with fire 🔥🚒

**Comment by KrauseFx** [comment]
Awesome, thanks for confirming 👍
