### ISSUE TITLE
gym log is to big,how to print only error?

### ISSUE THREAD

**Issue by yaochenfeng** [fastlane/fastlane#10102]
### Issue Description

I use CI, this log file is too big, there's 10M of content.
How can I only display the error log?

### Environment

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2i  22 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3

[INSERT OUTPUT HERE]

**Comment by mpirri** [comment]
@yaochenfeng Thanks so much for writing in!

You say that 10MB of content is too big - is this a limit of your CI system, or is there another reason why this is too big?

Do you have a sample of the log data so we can see what is taking up so much space? Usually `xcpretty` (which _fastlane_ runs over all of its build output) trims out a lot of excess log content. Is it possible that you have the `--verbose` flag enabled?

Finally, from the `Fastfile` that you uploaded, it doesn't look like you are calling `gym` to build your project. Is it possible that there is a different `Fastfile` you are using to build?

Thanks again! 🚀
