### ISSUE TITLE
Your Apple ID or password was entered incorrectly.

### ISSUE THREAD

**Issue by appcelerate** [fastlane/fastlane#10104]
### Issue Description

> Password contains special characters, which may not be handled properly by iTMSTransporter. If you experience problems uploading to iTunes Connect, please consider changing your password to something with only alphanumeric characters.

How can i solve this by NOT resetting the password. One week ago it works and now it doesnt.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.3 (Apple Git-91)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"
xcversion(version: "8.3.3")
# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "32c3eb40-173d-4b22-9826-9d6887ec9cc1"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
before_all do
	#
end

desc "Runs linting (and eventually static analysis)"
  lane :analyze do
    xcodebuild(
      workspace: "Wikipedia.xcworkspace",
      scheme: "Wikipedia",
      configuration: "Debug",
      sdk: 'iphonesimulator',
      destination: 'platform=iOS Simulator,OS=9.3,name=iPhone 6',
      analyze: true
    )
  end

  desc ""
  lane :build_number_plus do
    increment_build_number
  end

desc "Creates and submit a new testflight version" 
lane :testflight do
  #sh "cd ..; sh ./download_translations.sh"
 	cocoapods
 	match(app_identifier: ["com.asanayoga.asanarebel", "com.asanayoga.asanarebel.Today-Extension", "com.asanayoga.asanarebel.Rich-Notification", "com.asanayoga.asanarebel.Message-Extension", "com.asanayoga.asanarebel.watchkitapp", "com.asanayoga.asanarebel.watchkitapp.watchkitextension"], type: "appstore")
	increment_build_number
  gym(scheme: "Asana Rebel")
  testflight(skip_waiting_for_build_processing:true) 
 	clean_build_artifacts
end

desc "increment_build_number" 
lane :increment_build_number do
  increment_build_number
end

lane :generate_appstore_prov do
  match(app_identifier: ["com.asanayoga.asanarebel", "com.asanayoga.asanarebel.Today-Extension", "com.asanayoga.asanarebel.Rich-Notification", "com.asanayoga.asanarebel.Message-Extension", "com.asanayoga.asanarebel.watchkitapp", "com.asanayoga.asanarebel.watchkitapp.watchkitextension"], type: "appstore", force:true)
end

lane :generate_dev_prov do
  match(app_identifier: ["com.asanayoga.asanarebel", "com.asanayoga.asanarebel.Today-Extension", "com.asanayoga.asanarebel.Rich-Notification", "com.asanayoga.asanarebel.Message-Extension", "com.asanayoga.asanarebel.watchkitapp", "com.asanayoga.asanarebel.watchkitapp.watchkitextension"], type: "development", force:true)
end

desc "Upload Build to iTunes Connect"
lane :upload_build do
 	cocoapods
 	match(app_identifier: ["com.asanayoga.asanarebel", "com.asanayoga.asanarebel.Today-Extension", "com.asanayoga.asanarebel.Rich-Notification", "com.asanayoga.asanarebel.Message-Extension", "com.asanayoga.asanarebel.watchkitapp", "com.asanayoga.asanarebel.watchkitapp.watchkitextension"], type: "appstore")
	increment_build_number
  gym(scheme: "Asana Rebel")
  pilot(skip_waiting_for_build_processing:true) 
  crashlytics(api_token: "2afec78719b43aaaa201ce5df7047c2958547809",
              build_secret: "21bf81abd1690f20355b8b22ff85a206c11757bce8c10525e6a0dad5acae036f")
  clean_build_artifacts
end

lane :check_metadata do
  precheck
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

app_identifier "com.asanayoga.asanarebel" # the bundle identifier of your app
apple_id "it@asanarebel.com" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.4        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.2.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-22**
</details>

**Comment by mpirri** [comment]
It seems very weird that this error would have started happening all of the sudden. Can you check your Keychain to see if maybe you have two separate entries for your account, as in this ticket: https://github.com/fastlane/fastlane/issues/9729

Thanks! 🚀

**Comment by appcelerate** [comment]
@mpirri Thanks for your reply,
i tried to find two items in keychain for deliver but there was only one. i deleted it, then run fastlane again type my password in and then same error :/

**Comment by ohayon** [comment]
Hmmm. @appcelerate is your password also stored in an environment variable at all?

**Comment by appcelerate** [comment]
@ohayon  No i dont use it , i used iTerm with ZSH and a friend of mine using the same and a previous version of fastlane and there it works :/

**Comment by appcelerate** [comment]
Ok now it works, i uninalled the xcode beta and now it works :)

**Comment by ohayon** [comment]
Hmmm weird. But glad to see that it started working! I have definitely had weird string escaping issues with zsh too, but I just love it so much more than bash!! 🚀  🎉
