### ISSUE TITLE
Removing a Localization in IOS

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#10107]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The addition of a new localization is rather simply, you just simply create a folder and named it with the corresponding language code. However, is there a way to remove/delete a localization using Fastlane?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

N/A

**Comment by mpirri** [comment]
@pparmaei Just to make sure I understand, are you asking about localized app metadata (titles, description, screenshots, etc) here, or something else? Is there a particular use case you have in mind?

Thanks for writing in!  🚀

**Comment by pparmaei** [comment]
@mpirri yes, I am talking about localized app metadata. I just want to know if I am able to remove a localization from fastlane or spaceship. For example, if I have the 'Korean' localization enabled, and want to remove it in the next version update, is it possible to do this with fastlane or spaceship commands? Or is the only way of doing this through iTunes Connect?

Thanks

**Comment by mpirri** [comment]
That is correct, currently there isn't a way to do this in `spaceship`.  I don't suppose that you might be interested in trying to build this functionality and submitting it as a pull request to _fastlane_ though?  We are always looking for really cool _fastlane_ enhancements from contributors.  We have some pretty helpful [docs](https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md) to help you get started.  Let us know if you might be interested - thanks!
