### ISSUE TITLE
Optional Shared User For Match

### ISSUE THREAD

**Issue by Brandt1981** [fastlane/fastlane#10110]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In the "setup" instructions for Match the following is stated:

>Optional: Create a new, shared Apple Developer Portal account, something like office@company.com that will be shared across your team from now on (for more information visit codesigning.guide)

If a shared portal account is not created, what is the alternative? In this case only the client product owner has the ability to add certs, provisioning profiles, etc to the portal.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mpirri** [comment]
@Brandt1981 The alternative to the shared portal account would be having one user with access to the portal (and the rest of the team only having access to the git repository). In this case, only the user with access to the developer portal can generate the certs and profiles using `match`.

Based on your description, I think this would work for your usage case, no?

Thanks for contacting us about this! 🚀

**Comment by Brandt1981** [comment]
This is what I was thinking as well, however it doesn't seem like the person in this role is familiar with match....Also, because of another issue (https://github.com/fastlane/fastlane/issues/9908) we are having associated a CarPlay entitlement with our provisioning profile seems to have to be done manually, this would require this person to manually encrypt the profiles and certs and push to the git branch.

openssl aes-256-cbc -k abc123 -in ~/Downloads/match_Development_comxyz.mobileprovision -out Development_com.xyz.mobileprovision

**Comment by nicolasbraun** [comment]
Hello @Brandt1981 ,

The way we currently do it:
• Run match -> It will generate / retrieve the certificate and a profile which does not have the carplay entitlement
• Run sigh alone to retrieve a valid profile that you generated by hand on the portal, use sigh output for the codesign un the following gym action.

Basically it is a workaround to share the private key using match, and the profile using sigh

**Comment by Brandt1981** [comment]
Can you give examples of the commands?

**Comment by nicolasbraun** [comment]
it depends on your codesign setup.
We use an evar `PROFILE_UDID` as value in the xcodeproj for provisionning profile it is something like

```ruby
# Call match to retrieve the certificate and a not working PP
match(
...
)
# Call sigh to retrieve the PP you generated by hand; say it is named "myWorkingProfile"
# The pp UUID is directly outputed by sigh so set your can directly store in.

ENV['PROFILE_UDID'] = sigh(
...
provisioning_name: "myWorkingProfile",
ignore_profiles_with_different_name: true
)
gym(
...
)
```

This is based on an oldschool codesigning method but this works well for 2 years now and never broke so with sticked with it.
