### ISSUE TITLE
Match complains about missing certificate in the dev portal.

### ISSUE THREAD

**Issue by AndyIbanez** [fastlane/fastlane#10114]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I keep getting the error message in the output below. I have googled like crazy and I have done both solutions I found:

1. To run `fastlane match nuke`
2. To manually delete the certs and profiles from the repository.

And the issue is persisting.

My intention is to deploy an iOS 11 app to my beta testers with the following lane:

```
  lane :beta do
    match(type: "appstore", git_branch: "MY REAL NAME", username: "<REDACTED>", app_identifier: ["<REDACTED>"], git_url: "git@bitbucket.org:fairese/ios-certificates.git")
    scan(scheme: "<REDACTED>")
    gym(export_method: "app-store", scheme: "<REDACTED>") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
Andys-MacBook-Pro:Mignori andyibanez$ fastlane beta
[21:10:37]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:10:40]: -------------------------------------------------
[21:10:40]: --- Step: Verifying required fastlane version ---
[21:10:40]: -------------------------------------------------
[21:10:40]: Your fastlane version 2.54.0 matches the minimum requirement of 2.28.7  ✅
[21:10:40]: --------------------------
[21:10:40]: --- Step: xcode_select ---
[21:10:40]: --------------------------
[21:10:40]: Setting Xcode version to /Applications/Xcode-beta.app for all build steps
[21:10:40]: ------------------------------
[21:10:40]: --- Step: default_platform ---
[21:10:40]: ------------------------------
[21:10:40]: Driving the lane 'ios beta' 🚀
[21:10:40]: -----------------------
[21:10:40]: --- Step: cocoapods ---
[21:10:40]: -----------------------
[21:10:40]: $ pod install
[21:10:43]: ▸ Analyzing dependencies
[21:10:43]: ▸ Downloading dependencies
[21:10:43]: ▸ Using DACircularProgress (2.3.1)
[21:10:43]: ▸ Using Eureka (3.0.0)
[21:10:43]: ▸ Using MBProgressHUD (0.9.2)
[21:10:43]: ▸ Using MWPhotoBrowser (2.1.2)
[21:10:43]: ▸ Using SDWebImage (3.8.2)
[21:10:43]: ▸ Using SwiftKeychainWrapper (3.0.1)
[21:10:43]: ▸ Generating Pods project
[21:10:43]: ▸ Integrating client project
[21:10:44]: ▸ Sending stats
[21:10:44]: ▸ Pod installation complete! There are 3 dependencies from the Podfile and 6 total pods installed.
[21:10:44]: ▸ [!] Automatically assigning platform ios with version 11.0 on target Mignori because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
[21:10:44]: -------------------
[21:10:44]: --- Step: match ---
[21:10:44]: -------------------

+-----------------------+--------------------------------------+
|                   Summary for match 2.54.0                   |
+-----------------------+--------------------------------------+
| type                  | appstore                             |
| git_branch            | sergio-andres-ibanez-kautsch         |
| username              | atanacross@gmail.com                 |
| app_identifier        | ["com.fairese.Mignori"]              |
| git_url               | git@bitbucket.org:fairese/ios-certi  |
|                       | ficates.git                          |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| team_id               | 7X7FABXK4C                           |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

[21:10:44]: Cloning remote git repo...
[21:10:44]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[21:10:57]: Checking out branch sergio-andres-ibanez-kautsch...
[21:10:57]: 🔓  Successfully decrypted certificates repo
[21:10:57]: Verifying that the certificate and profile are still valid on the Dev Portal...
[21:11:04]: Installing certificate...

+-------------------+----------------------------------------------------------------+
|                               Installed Certificate                                |
+-------------------+----------------------------------------------------------------+
| User ID           | 7X7FABXK4C                                                     |
| Common Name       | iPhone Distribution: Sergio Andres Ibanez Kautsch (7X7FABXK4C) |
| Organisation Unit | 7X7FABXK4C                                                     |
| Organisation      | Sergio Andres Ibanez Kautsch                                   |
| Country           | US                                                             |
| Start Datetime    | May  4 20:29:33 2017 GMT                                       |
| End Datetime      | May  4 20:29:33 2018 GMT                                       |
+-------------------+----------------------------------------------------------------+

[21:11:06]: Certificate 'N365A7RF37' (stored in your git repo) is not available on the Developer Portal
[21:11:06]: for the user atanacross@gmail.com
[21:11:06]: Make sure to use the same user and team every time you run 'match' for this
[21:11:06]: Git repository. This might be caused by revoking the certificate on the Dev Portal
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[21:11:08]: To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | xcode_select        | 0           |
| 3    | default_platform    | 0           |
| 4    | cocoapods           | 3           |
| 💥   | match               | 22          |
+------+---------------------+-------------+

[21:11:08]: fastlane finished with errors

[!] To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match
Andys-MacBook-Pro:Mignori andyibanez$ 
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"
xcode_select "/Applications/Xcode-beta.app"
# git_url "git@bitbucket.org:fairese/ios-certificates.git"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # itc_team_id "613506"
    # match(type: "appstore") # more information: https://codesigning.guide
    match(type: "appstore", git_branch: "sergio-andres-ibanez-kautsch", username: "atanacross@gmail.com", app_identifier: ["com.fairese.Mignori"], git_url: "git@bitbucket.org:fairese/ios-certificates.git")
    scan(scheme: "Mignori")
    gym(export_method: "app-store", scheme: "Mignori") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    match(type: "appstore", git_branch: "<REDACTED>", username: "<REDACTED>", app_identifier: ["<REDACTED>"])
    scan(scheme: "<REDACTED>")
    gym(scheme: "<REDACTED>") # Build your app - more options available
    deliver(force: true, submit_for_review: true)
    # frameit
  end

  desc "Development environment"
  lane :dev_env do
    match(force: true, force_for_new_devices: true, type: "development", git_branch: "", username: "", app_identifier: [""])
  end

  desc "Distribution environment"
  lane :dis_env do
    match(type: "appstore", git_branch: "", username: "", app_identifier: [""])
  end

  desc "Frame Screenshots"
  lane :frame do
    frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "" # Developer Portal Team ID" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-08-22**
</details>

**Comment by AndyIbanez** [comment]
I have nuked my certificates again to be sure. I cannot find a solution to this issue.

**Comment by KrauseFx** [comment]
Are you part of multiple teams? Are you admin on that account?

**Comment by AndyIbanez** [comment]
I am indeed part of multiple teams, but I am the creator of the team I'm trying to use match in (so yep, admin). Also worth noting my Fastfile specifies the team I want to run the command in so I don't quite think it's getting confused.

**Comment by AndyIbanez** [comment]
Actually I double checked my fastfile and I'm not specifying the team.

```
    match(force: true, type: "appstore", git_branch: "<REDACTED>", username: "<REDACTED>", app_identifier: ["<REDACTED>"], git_url: "git@bitbucket.org:fairese/ios-certificates.git")
```

So I will try to find a way to do that and see how it goes.

**Comment by AndyIbanez** [comment]
Alright, so I have read the entire match page and noticed that the git_branch is there due to the team name (I set up fastlane a while ago, so I forgot some things), so I'm sure that should be working.

If this helps anyone help me, for whatever reason match is generating thousands of "ineligible" profiles for App Store distribution. The only valid one is a the one for Development. Maybe a bug? No matter how much I run nuke and create my certificates (RIP Beta Testers of other apps), the same thing keeps happening. Here's an screenshot of what I see in the provisioning page of Xcode:

![image](http://imgur.com/a/LktJ5)

**Comment by AndyIbanez** [comment]
@KrauseFx Sorry for pinging you directly, but I believe I am narrowing the problem down and I could use some assistance with this.

So essentially I just ran `fastlane beta --verbose` and `match --verbose` and I noticed these two different outputs:

```
INFO [2017-08-23 20:18:50.12]: 🔓  Decrypted '7YSBMX93YQ.cer'
INFO [2017-08-23 20:18:50.16]: 🔓  Decrypted 'N365A7RF37.cer'
INFO [2017-08-23 20:18:50.20]: 🔓  Decrypted '7YSBMX93YQ.p12'
INFO [2017-08-23 20:18:50.23]: 🔓  Decrypted 'N365A7RF37.p12'
INFO [2017-08-23 20:18:50.27]: 🔓  Decrypted 'AppStore_com.fairese.ios.AnimeSecretary.mobileprovision'
INFO [2017-08-23 20:18:50.31]: 🔓  Decrypted 'AppStore_com.fairese.ios.AnimeSecretary.NewEpisodeNotificationContentExtension.mobileprovision'
INFO [2017-08-23 20:18:50.35]: 🔓  Decrypted 'AppStore_com.fairese.ios.AnimeSecretary.NewEpisodeNotificationServiceExtension.mobileprovision'
INFO [2017-08-23 20:18:50.38]: 🔓  Decrypted 'AppStore_com.fairese.Mignori.mobileprovision'
INFO [2017-08-23 20:18:50.42]: 🔓  Decrypted 'Development_com.fairese.ios.AnimeSecretary.mobileprovision'
INFO [2017-08-23 20:18:50.45]: 🔓  Decrypted 'Development_com.fairese.ios.AnimeSecretary.NewEpisodeNotificationContentExtension.mobileprovision'
INFO [2017-08-23 20:18:50.49]: 🔓  Decrypted 'Development_com.fairese.ios.AnimeSecretary.NewEpisodeNotificationServiceExtension.mobileprovision'
INFO [2017-08-23 20:18:50.49]: 🔓  Successfully decrypted certificates repo


NFO [2017-08-23 20:16:32.23]: 🔓  Decrypted 'ZCXT924J94.cer'
INFO [2017-08-23 20:16:32.27]: 🔓  Decrypted 'ZCXT924J94.p12'
INFO [2017-08-23 20:16:32.30]: 🔓  Decrypted 'Development_com.fairese.Mignori.mobileprovision'
INFO [2017-08-23 20:16:32.30]: 🔓  Successfully decrypted certificates repo
```

The first output is from `fastlane beta` (so the match command in my fastfile) and the second one from `match` alone.

Fastlane complaints that the certificate ```N365A7RF37``` does not exist on the developer portal, but it's on my repo (on the branch of my team). You can also see that the Development and App_Store profiles for the app Mignori (I was hiding the name of the app before, but at this point I can't anymore, lol), are in both different branches.

So my question is, how do I issue `fastlane match nuke` on a different branch than master? I tried doing `fastlane match nuke git_branch MY_URL` but it didn't work (Because of course it thought MY_URL was a release method).

**Comment by mpirri** [comment]
@AndyIbanez I think you should be able to use `fastlane match nuke distribution --git_branch <branch_name>` to clear out that repository. Since `match` doesn't work with .pem files for push, your push certs should be save when you do `match nuke`.

Let me know if this helps! 🚀

**Comment by AndyIbanez** [comment]
Thanks a bunch @mpirri. My fastfile now gets to the pilot step. Although it doesn't succeed, the core issue that has been plaguing me for days now is now fixed.
