### ISSUE TITLE
Hockey owner_id parameter

### ISSUE THREAD

**Issue by batesyuk** [fastlane/fastlane#1011]
Creating this retrospectively as I totally didn't see the contributing.md stuff and had already done the work in Shenzhen.

Anyway I have spoken to Hockey today and they have now added owner_id to their docs for the upload endpoint. As such I have added it to shenzhen and fastlane.

Shenzhen: https://github.com/fastlane/shenzhen/pull/5
Fastlane: https://github.com/fastlane/fastlane/pull/1010

Sorry about that, at least it was only a small change. I will know for next time

**Comment by KrauseFx** [comment]
Thanks, this will be live with the next release :+1:
