### ISSUE TITLE
How to use fastlane submit IAP?

### ISSUE THREAD

**Issue by huanling713** [fastlane/fastlane#10125]
I cannot find the fastlane sub command to submit or edit IAP in iTC.
Can anyone tell me how to submit it?
Thanks

**Comment by mpirri** [comment]
You can work with application IAP using the `spaceship` tool - look at the `in_app_purchases` method in [application.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb) to get the IAP object you can work with. You can learn more about the IAP object in the [iap.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/iap.rb) file that has some examples of how to work with it.

I hope this is helpful, please let us know if you have any other questions we can help with!  🚀

**Comment by huanling713** [comment]
@mpirri Thanks for your reply.
Can you give me a full code example as I am a new rb guy , thanks.

**Comment by ohayon** [comment]
Hey @huanling713 - I think the best way to use this would be to do some digging around to see exactly what would help with your use case. It might just be a bit difficult for us to provide a sample because we don't know exactly the flow you are using. 🐙

**Comment by huanling713** [comment]
It,s OK , use following code.


require 'spaceship'

Spaceship::Tunes.login("huan@xxx.com")
ENV['FASTLANE_ITC_TEAM_ID'] = 'xxx'
Spaceship::Tunes.select_team

# Find a specific app based on the bundle identifier or Apple ID
app = Spaceship::Tunes::Application.find("com.tencent.yan095")

app.in_app_purchases.create!(type: "consumable",
                             versions: {
                                 'de-DE'=>{
                                     name: "Name shown in AppStore",
                                     description: "Description of the In app Purchase"
                                 }
                             },
                             reference_name: "test",
                             product_id: "com.tencent.yan095.iap",
                             cleared_for_sale: true,
                             review_notes: nil,
                             review_screenshot: nil,
                             pricing_intervals: nil,
                             family_id: nil,
                             subscription_free_trial: nil,
                             subscription_duration: nil)
