### ISSUE TITLE
SharedValues::DEPLOY_LINK?

### ISSUE THREAD

**Issue by scottrhoyt** [fastlane/fastlane#1012]
...or `SharedValues::DEPLOY_URL`?

What do you think about standardizing a shared value for deployment actions to output a link to?

I can see this as being useful so that notification/messaging actions can include a link to the build or further information regardless of which of the many deployment options is being used. I'm currently writing a Flowdock notification action and would like to have access to that.

Any thoughts?

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
