### ISSUE TITLE
Supply now requires 0.13.0 of google-api-client, but doesn't enforce this

### ISSUE THREAD

**Issue by tmtrademarked** [fastlane/fastlane#10136]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Supply appears to be broken with the latest release. It looks like https://github.com/fastlane/fastlane/pull/10051 allowed the google-api-client dependency to be dynamic (>= 0.12.0, < 1.0.0) and https://github.com/fastlane/fastlane/pull/10120 changed supply to use APIs from the 0.13.0 version of the gem.

The google-api-client is NOT API stable. Every time they upgrade the minor build version, the API can potentially change. So it is *not* safe to let this dynamically upgrade. I believe the correct fix is to set to requirement for the google-api-client gem to >= 0.13.0, < 0.14.0 to pin the version to 0.13.x releases.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
+------+---------------------------------------------+-------------+
|                         fastlane summary                         |
+------+---------------------------------------------+-------------+
| Step | Action                                      | Time (in s) |
+------+---------------------------------------------+-------------+
| 1    | update_fastlane                             | 0           |
| 2    | Verifying required fastlane version         | 0           |
| 3    | default_platform                            | 0           |
| 4    | Switch to android deploy_alpha_mapping lane | 0           |
| 5    | gradle                                      | 326         |
| 💥   | supply                                      | 0           |
+------+---------------------------------------------+-------------+

[10:44:28]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/supply/lib/supply/client.rb:145:in `listing_for_language': [!] undefined method `get_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007f075a0ce2f8> (NoMethodError)
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:17:in `block in perform_upload'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:13:in `each'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:13:in `perform_upload'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/actions/supply.rb:21:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:81:in `block (2 levels) in parsing_binding'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `load'
	from /opt/circleci/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `<main>'

**Comment by REWMohammed** [comment]
The last update did not solve this for me, I am still having this issue.
I tried both 2.54.1, and the beta version.

```
undefined method `get_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fe52229a6f8>

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 💥   | supply[                                   | 0           |
+------+-------------------------------------+-------------+

fastlane finished with errors

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-08-24**
</details>

**Comment by moga111** [comment]
The last update did not solve this for me, I am still having this issue.
I tried both 2.54.1, and the beta version.

```
undefined method `get_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fe52229a6f8>

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 💥   | supply[                                   | 0           |
+------+-------------------------------------+-------------+

fastlane finished with errors

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-08-24**
</details>

**Comment by moga111** [comment]
The last update did not solve this for me, I am still having this issue.
I tried both 2.54.1, and the beta version.

```
undefined method `get_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fe52229a6f8>

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 💥   | supply[                                   | 0           |
+------+-------------------------------------+-------------+

fastlane finished with errors

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-08-24**
</details>

**Comment by rogerkerse** [comment]
i accidentally created a new issue, but i put some env output there as well https://github.com/fastlane/fastlane/issues/10148

**Comment by mpirri** [comment]
Thanks for the heads up!  We are looking into this now.  🚀

**Comment by tmtrademarked** [comment]
Fixed in 2.54.2! Closing this issue, although there are still a few misnamed methods. I've uploaded https://github.com/fastlane/fastlane/pull/10153 to address the last of these that I'm aware of.

**Comment by mpirri** [comment]
@tmtrademarked Great, thanks for the fixes - do you have any ideas of how we can detect these changed method names going forward? We need more unit tests in the code, but even if we did write tests, we'd probably just mock out all of the methods of the `google-api-client` gem and then we wouldn't know when the method names of the actual gem changed.

**Comment by tmtrademarked** [comment]
Yeah - I've been trying to think of a good way to write a test for this.
I'll give it some more thought to see if there's something I can come up
with.

**Comment by mpirri** [comment]
That would be amazing, @tmtrademarked, thanks so much!
