### ISSUE TITLE
undefined method `get_edit_listing' for Google::Apis::AndroidpublisherV2::AndroidPublisherService

### ISSUE THREAD

**Issue by jaynakus** [fastlane/fastlane#10132]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Cannot upload apk to Google Play
##### Complete output when running fastlane, including the stack trace and command used
[13:57:27]: Preparing to upload for language 'tr-TR'...
+-----------------------------+----------------------------------------------------------------------------------------------------+
|                                                           Lane Context                                                           |
+-----------------------------+----------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM            | android                                                                                            |
| PLATFORM_NAME               | android                                                                                            |
| LANE_NAME                   | android release                                                                                    |
| GRADLE_BUILD_TYPE           | Release                                                                                            |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/mobilnik/builds/630210f7/0/wallet/mixipay/android/app/build/outputs/apk/app-release.apk"] |
| GRADLE_APK_OUTPUT_PATH      | /Users/mobilnik/builds/630210f7/0/wallet/mixipay/android/app/build/outputs/apk/app-release.apk     |
+-----------------------------+----------------------------------------------------------------------------------------------------+
[13:57:28]: undefined method `get_edit_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007f9a24a16970>
Did you mean?  get_apk_listing

> You can use: `--capture_output` as the last commandline argument to get that collected for you
bundler: failed to load command: fastlane (/Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/bin/fastlane)
NoMethodError: [!] undefined method `get_edit_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007f9a24a16970>
Did you mean?  get_apk_listing
Did you mean?  get_apk_listing
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/supply/lib/supply/client.rb:145:in `listing_for_language'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:17:in `block in perform_upload'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:13:in `each'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:13:in `perform_upload'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/actions/supply.rb:21:in `run'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:29:in `block (2 levels) in parsing_binding'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.0/bin/fastlane:20:in `<top (required)>'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/bin/fastlane:22:in `load'
  /Users/mobilnik/builds/630210f7/0/wallet/mixipay/vendor/bundle/ruby/2.4.0/bin/fastlane:22:in `<top (required)>'

### Environment
It is unavailable on ci server 
Using fastlane 2.54.0 (was 2.28.3)
Bundle updated!

**Comment by stoneman1** [comment]
Having same error. They changed the ruby library for google.

**Comment by jaynakus** [comment]
@stoneman1 , these guys are awesome, waiting for the next release then...

**Comment by jaynakus** [comment]
fixed by release 2.54.1
