### ISSUE TITLE
Not able to set FASTLANE_XCODE_LIST_TIMEOUT

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#10131]
I am running the parallel builds on Jenkins using fastlane for iOS.
But the build fails due to the error:

_xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES_ 

I tried the below steps and still the issue persists.

1. In fastlane .env file added the FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=60 
2. In Jenkins before calling Fastlane, added    export FASTLANE_XCODE_LIST_TIMEOUT=60

Even after performing both the above steps, I am not able to override the timeout.

The problem only occurs when I try for parallel builds. It seems both the builds tries to called the showBuildSettings and it times out. Hoping that the increase it timeout will solve the issue.

**Comment by mpirri** [comment]
@santoshshetty2612 A few questions:
Which version of Xcode are you running? If you are running the Xcode 9 beta, make sure you are using beta 6 to workaround a hang in `xcodebuild -showBuildSettings`.
Also, when you change those environment variables do you see the error message change? Just wondering if the values are not actually being set, or aren't being honored by _fastlane_.

**Comment by santoshshetty2612** [comment]
@mpirri I am using Xcode 8.3.3.
There is no change in the error message. Yes the new values don't seem to be honoured by fastlane.

This is my Jenkins call:
export FASTLANE_XCODE_LIST_TIMEOUT=60 
fastlane build admin (running the lane)

And this is how I have set it in .env file for fastlane
FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=60

Both the steps is not having any effect on fastlane.

**Comment by ohayon** [comment]
Hey @santoshshetty2612 - just looking for some clarification here about your use case, when you say `parallel builds` what do you mean exactly?

**Comment by santoshshetty2612** [comment]
Hi @ohayon 

In Jenkins I have created a job to run the iOS Xcode build. 
Now I have requirement to run the same job for multiple countries.  
I run multiple instances of this job which creates its own workspace.

But at some point of time all these jobs might end up calling xcodebuild -showBuildSettings at around the same time. This might be causing the timeout issues.

If I am able to increase this timeout to 60 seconds, I feel this issue of timeout might get resolved. But I am unable to overwrite this value for fastlane.

**Comment by ohayon** [comment]
@santoshshetty2612 - out of curiosity, if you only run one at a time, do you still see the timeout?

**Comment by santoshshetty2612** [comment]
@ohayon 
Till now I haven't observed this issue when I run at a time.

**Comment by ohayon** [comment]
Hmmm. Is there anything you can do in your Jenkins setup to space out the builds by a few seconds so they don't run into each other when running the same commands maybe?

**Comment by santoshshetty2612** [comment]
@ohayon This solution won't work out as the builds can be fired anytime. So builds might end up calling xcodebuild -showBuildSettings at around the same time.

It would be better if fastlane handles this.

**Comment by santoshshetty2612** [comment]
Thanks, the issue has been resolved and now I am able to run multiple builds simultaneously.

I need to set two variables in my fastfile.

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180" 
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
