### ISSUE TITLE
Show team name next to id in deliver error message

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#10134]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I ran deliver while having an incorrect ID in the `Appfile` and I got this error:

    [16:14:24]: Could not set team ID to '123', only found the following available teams: 456, 789

It would be nice if the team name would be next to the IDs like:

    [16:14:24]: Could not set team ID to '123', only found the following available teams: 456 (Team 1), 789 (Team 2)

for easier solving of this.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mpirri** [comment]
This is a really good idea - any chance you might be interested in preparing a pull request to add this? We are always looking for awesome PRs from the _fastlane_ community, and this would be a great change.

Check out [this document](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) for more information on contributing to _fastlane_. 🚀

**Comment by revolter** [comment]
Is there any way to mock the developer account? As I wouldn't want to mess with the work account.

**Comment by ohayon** [comment]
Hey @revolter, you should be able to look at some of the tests in `spaceship/specs` and see if anything makes sense there for mocking out the account. 😄  🐙

**Comment by RishabhTayal** [comment]
Created a PR for this. 👍
