### ISSUE TITLE
Crash on fastlane supply init

### ISSUE THREAD

**Issue by DastanIqbal** [fastlane/fastlane#10147]
var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:133:in `block in listings': [!] undefined method `list_listings' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x00000001733600> (NoMethodError)
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:367:in `call_google_api'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:133:in `listings'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/setup.rb:11:in `perform_download'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/commands_generator.rb:59:in `run'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/supply/lib/supply/commands_generator.rb:12:in `start'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        from /var/lib/gems/2.1.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | debian_based jessie/sid                                  |
| Ruby                        | 2.1.2                                                    |
| Bundler?                    | false                                                    |
| Git                         | git version 2.1.4                                        |
| Installation Source         | /usr/local/bin/fastlane                                  |
| Host                        | Ubuntu 15.04 debian_based jessie/sid (3.19.0-84-generic) |
| Ruby Lib Dir                | /usr/lib                                                 |
| OpenSSL Version             | OpenSSL 1.0.1f 6 Jan 2014                                |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US       | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/home/dastaniqbal/<appName>/fastlane_google_play_android_dev.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "my.package.name" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
| io-console                | 0.4.2        |
</details>

*generated on:* **2017-08-25**
</details>

**Comment by mpirri** [comment]
@DastanIqbal Looks like you are using the `google-api-client` version 0.12.0 - any chance you could do a `gem update` on that gem to get to version 0.13.x? I think it would solve the missing method problem you are seeing.  In the meantime, I will look into why it is that the gem didn't automatically update when you installed the latest version of _fastlane_.

Thanks, please let us know if you have any luck with this!  🚀

**Comment by tmtrademarked** [comment]
Hopefully 2.54.2 solves this by requiring 0.13.1 for that gem.

**Comment by mpirri** [comment]
@tmtrademarked 🤞 that it solves the problem (we are optimistic!). @DastanIqbal please let us know if you are still encountering this problem after updating to the new version of _fastlane_.  Thanks! 🚀

**Comment by DastanIqbal** [comment]
@tmtrademarked  @mpirri thanks  `gem update` worked.  :rocket:
