### ISSUE TITLE
Keychain access while running fastlane on crontab 

### ISSUE THREAD

**Issue by deborahhh** [fastlane/fastlane#1014]
I'm trying to run my fastlane script from crontab, but it seems it can't get the apple developer account password from the keychain. The script runs fine when I run it in the terminal, but when I see the stdout.log from the crontab, it gets stuck at the authentication part. What's the best way to fix this?

**Comment by scottrhoyt** [comment]
I'd say it would be to create a new keychain for the cron job, install your developer .p12 into the new keychain, set it as default, and unlock it. This should all be possible via fastlane actions.

**Comment by deborahhh** [comment]
how do I create a new keychain for the cron job?

**Comment by scottrhoyt** [comment]
Have a look at the [docs](https://github.com/fastlane/fastlane/blob/master/docs/Actions.md) under the building section. You will find all the relevant keychain actions there. These actions will be run by your cron user--ensuring you are creating keychains for their use later in building.

**Comment by deborahhh** [comment]
Hm, I don't know if it will help, since to unlock and all that during runtime I have to provide a password, but the point is to keep these passwords local. But either way, I think it magically worked now, by adding the certificates and passwords to the system keychain. 

But I have a new issue now: https://github.com/fastlane/fastlane/issues/1020 :(

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
