### ISSUE TITLE
[!] undefined method `get_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fbb794797f8> (NoMethodError)

### ISSUE THREAD

**Issue by chandankumar-mob-incedo** [fastlane/fastlane#10145]
I just updated fastlane to version 2.54.1 and getting this issue while supply 

/Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:145:in `listing_for_language': [!] undefined method `get_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007faec12e50a0> (NoMethodError)

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by chandankumar-mob-incedo** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.3                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.47.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  desc "Beta release app. Deploy a new version to the Google Play Store - Beta channel"

     lane :beta do |options|

         gradle(task: "clean")
         gradle(
            task: "assemble",
            build_type: "Release"
          )

          sign_apk(
            apk_path: options[:apk_path],
            keystore_path: options[:keystore_path],
            alias: options[:alias],
            storepass: options[:storepass],
            tsa: "http://timestamp.comodoca.com/rfc316",
          )

          zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")
          gradle(task: "test")

        supply(
           track: options[:track],
           package_name: options[:package_name],
           json_key: options[:json_key_file],
           apk: "#{lane_context[SharedValues::SIGNED_APK_PATH]}"
         )
    end

    desc "Take phone screenshots"
    lane :phones_screenshots do |options|
      screengrab(
      app_package_name: options[:app_package_name],
      device_type: "phone",
      app_apk_path: options[:app_apk_path],
      tests_apk_path: options[:tests_apk_path]
      )
    end

    desc "Take seven inch tablet screenshots"
    lane :seveninchtablet_screenshots do |options|
      screengrab(
      app_package_name: options[:app_package_name],
      device_type: "sevenInch",
      app_apk_path: options[:app_apk_path],
      tests_apk_path: options[:tests_apk_path]
      )
    end

    desc "Take ten inch tablet screenshots"
    lane :teninchtablet_screenshots do |options|
      screengrab(
      app_package_name: options[:app_package_name],
      device_type: "tenInch",
      app_apk_path: options[:app_apk_path],
      tests_apk_path: options[:tests_apk_path]
     )
    end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-08-25**
</details>

**Comment by chandankumar-mob-incedo** [comment]
Fastlane version 2.54.1

**Comment by rogerkerse** [comment]
Same issue with a bit more output https://github.com/fastlane/fastlane/issues/10148

**Comment by vytautasgimbutas** [comment]
Having the same issue.

**Comment by vytautasgimbutas** [comment]
I think this fixes the issue https://github.com/fastlane/fastlane/commit/b6605f0ce6cc263ec4ae58a41f6a3743662a72d6

but they haven't yet released a version.

**Comment by mpirri** [comment]
@vytautasgimbutas You are exactly right - this issue will be resolved by the next _fastlane_ release.

Thanks for your patience with this, folks!  🚀
