### ISSUE TITLE
please don't print your changelogs into my console

### ISSUE THREAD

**Issue by mockturtl** [fastlane/fastlane#10140]
I would prefer a one-line "update available!" notice, and a link.

### New Issue Checklist

- ~~Updated fastlane to the latest version~~
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- ~~I read [docs.fastlane.tools](https://docs.fastlane.tools)~~
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by PetrosIchor** [comment]
Check the docs for more controls/features in fastlane.  https://docs.fastlane.tools/advanced/

To disable update notifications, simply add `FASTLANE_SKIP_UPDATE_CHECK=1` to your environment.

**Comment by mockturtl** [comment]
Thanks!
