### ISSUE TITLE
Deliver 2.54.2 failing on preparing iMessage screenshots with "no implicit conversion of Symbol into Integer" 

### ISSUE THREAD

**Issue by vadique** [fastlane/fastlane#10157]
### Issue Description
Running deliver if an app has iMessage screenshots fails when trying to prepare screenshots from "screenshots/iMessage" folder. (Possibly will fail with appleTV screenshots as well.) This was working before.

Reproduce:
1. run "fastlane deliver init" to download some existing iMessage app with iMessage screenshots 
(or add iMessage/en-US/screenshot.png to your screenshots/)
2. all screenshots are downloaded correctly and placed into "/screenshots/{lang}" and "/screenshots/iMessage/{lang}"
3. run "fastlane deliver" --> fails in collect_screenshots_for_languages in "deliver/lib/deliver/upload_screenshots.rb:77" 
4. delete "iMessage" folder from "screenshots" 
(or comment L92 in upload_screenshots.rb to prevent traversing non-language paths)

> #### Check to see if we need to traverse multiple platforms or just a single platform
>         if language == Loader::APPLE_TV_DIR_NAME || language == Loader::IMESSAGE_DIR_NAME
>           #-->screenshots.concat(collect_screenshots_for_languages(File.join(path, language)))
>           next
>         end

5. run "fastlane deliver" --> success

Note: 
-changing "screenshots_path" from default to custom makes no difference
-"ignore_language_directory_validation" true|false makes no difference

##### Complete output when running fastlane, including the stack trace and command used
fastlane deliver --verbose
INFO [2017-08-25 17:42:01.66]: Successfully loaded '/Users/mcbk/Desktop/fastlane-imessage-test/Deliverfile' 📄

+--------------------------------------+--------------------------------------+
|                    Detected Values from './Deliverfile'                     |
+--------------------------------------+--------------------------------------+
| app_identifier                       | ******************                   |
| username                             | ******************                   |
| screenshots_path                     | screenshots                          |
| metadata_path                        | metadata                             |
| overwrite_screenshots                | true                                 |
+--------------------------------------+--------------------------------------+

INFO [2017-08-25 17:42:01.67]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
INFO [2017-08-25 17:42:01.67]: Login to iTunes Connect
INFO [2017-08-25 17:42:03.72]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.54.2 Summary                            |
+--------------------------------------+--------------------------------------+
| app_identifier                       | ******************                   |
| username                             | ******************                   |
| screenshots_path                     | screenshots                          |
| metadata_path                        | metadata                             |
| ignore_language_directory_validatio  | true                                 |
| n                                    |                                      |
| overwrite_screenshots                | true                                 |
| edit_live                            | false                                |
| platform                             | ios                                  |
| skip_binary_upload                   | false                                |
| skip_screenshots                     | false                                |
| skip_metadata                        | false                                |
| skip_app_version_update              | false                                |
| force                                | false                                |
| submit_for_review                    | false                                |
| automatic_release                    | false                                |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | warn                                 |
+--------------------------------------+--------------------------------------+

/Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/upload_screenshots.rb:77:in `[]': [!] no implicit conversion of Symbol into Integer (TypeError)
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/upload_screenshots.rb:77:in `collect_screenshots_for_languages'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/upload_screenshots.rb:92:in `block in collect_screenshots_for_languages'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/upload_screenshots.rb:87:in `each'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/upload_screenshots.rb:87:in `collect_screenshots_for_languages'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/upload_screenshots.rb:73:in `collect_screenshots'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/runner.rb:95:in `upload_metadata'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/runner.rb:26:in `run'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/commands_generator.rb:173:in `run'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/mcbk/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.2/bin/fastlane:20:in `<top (required)>'
	from /Users/mcbk/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/mcbk/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.1       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-25**
</details>

**Comment by mpirri** [comment]
Good find!  It sure is difficult to imagine how this code would work, given that `collect_screenshots_for_languages` on line 77 of `uplaod_screenshots.rb` is expecting a hash for options, and the method call on line 92 is passing a string! 🤔 

I'll make a pull request to test this shortly - I'll send you a link and maybe you can test it out?  Thanks much!
