### ISSUE TITLE
Snapshot: Snapshot only device in command line

### ISSUE THREAD

**Issue by NewStorm** [fastlane/fastlane#10159]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a little question/feature request:
Can I Snapshot only one or multiple devices which are set as a command line parameter?
Thank you for your help
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mpirri** [comment]
@NewStorm Look at using the `--devices` command line argument to `snapshot` to specify which device you would like to use.

For instance, to just get screenshots on an iPhone 5, you might use:
`fastlane snapshot --devices "iPhone 5"`

To get screenshots on both an iPhone 5 and iPhone 6, use:
`fastlane snapshot --devices "iPhone 5,iPhone 6"`

I hope this is helpful; thanks for contacting us! 🚀
