### ISSUE TITLE
Not generating ipa, just generating archive and done

### ISSUE THREAD

**Issue by tejas-ardeshna** [fastlane/fastlane#10151]
My app contains following things

companion ios app
watch app
watch app extension
ios app Siri extension
watch app Siri extension

All steps work perfectly, but in the gym it just creating archive, not ipa file. 

Log:

Touching iTRAIN.app
INFO [2017-08-25 18:11:53.48]: ▸ Signing /Users/Tejas.Ardeshna/Library/Developer/Xcode/DerivedData/iTRAIN-bsvbchslbhddcgavcziclnxivumj/Build/Intermediates/ArchiveIntermediates/iTRAINWatch/InstallationBuildProductsLocation/Applications/iTRAIN.app
INFO [2017-08-25 18:11:55.21]: ▸ Touching iTRAIN.app.dSYM
INFO [2017-08-25 18:11:57.48]: ▸ Archive Succeeded
DEBUG [2017-08-25 18:11:57.65]: Stored the archive in: /Users/Tejas.Ardeshna/Library/Developer/Xcode/Archives/2017-08-25/iTRAINWatch 2017-08-25 18.04.04.xcarchive
WARN [2017-08-25 18:11:57.66]: No output path received from gym

PS: there is build folder available in the directory. See http://prntscr.com/gcwesc.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "2.32.1"

default_platform :ios
ENV["LANG"] = "en_US.UTF-8"

platform :ios do
   	lane :beta do
	    #increment_build_number
    	#cert(output_path: "./fastlane/certificates")
    	#sigh(output_path: "./fastlane/profiles")
      gym(                                                       # GYM is used to build app
        
        scheme: "iTRAINWatch",                                  # Use your app scheme
        silent: true,
        include_bitcode: true,                                  # Include bit code in bit code
        output_directory: "./fastlane/build"                    # Destination directory. Defaults to current directory.
      )
   	 	deliver(                                                  # DELIVER is used to upload app on itunes connect
          skip_metadata: true,                                # it will skip all meta data to upload on itunes
          force: true, 
          run_precheck_before_submit: false) 
      crashlytics(api_token: '96c68e9c0138cb4916e862697ecd5746657596e6',
             build_secret: '26c18e9bb11b79d4fbf2b036d87c05bdbfef408cb7e58a4f496f2fa1451a1d1f',
                   emails: 'tejas.a@simform.in',
                   groups: nil,
                    notes: 'Distributed with fastlane',    # Check out the changelog_from_git_commits action
            notifications: true)                           # Should this distribution notify your testers via email?
   	end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.yourcardioguru.iMONITORU" # The bundle identifier of your app
apple_id "fitness@thecardioguru.com" # Your Apple email address

team_id "J9S3EC3CQP"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.53.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.6        |
| rubyzip                   | 1.2.0        |
</details>

*generated on:* **2017-08-25**
</details>

**Comment by tejas-ardeshna** [comment]
We are using automatic code signing.

**Comment by ohayon** [comment]
Hey @tejas-ardeshna! Could you show us the full output from your execution? Thanks!

**Comment by tejas-ardeshna** [comment]
Here it is. @ohayon , due to no ipa crashlytics also not working. 

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/Tejas.Ardeshna/Desktop/Simform Work/iMONITORU/Source/iMONITORU/fastlane/Appfile'
- app_identifier: 'com.yourcardioguru.iMONITORU'
- apple_id: 'fitness@thecardioguru.com'
- team_id: 'J9S3EC3CQP'
-------

+------------------+--------------------------------------+
|                 Summary for gym 2.54.1                  |
+------------------+--------------------------------------+
| scheme           | iTRAINWatch                          |
| silent           | true                                 |
| include_bitcode  | true                                 |
| workspace        | ./iTRAIN.xcworkspace                 |
| destination      | generic/platform=iOS                 |
| output_name      | iTRAINWatch                          |
| build_path       | /Users/Tejas.Ardeshna/Library/Devel  |
|                  | oper/Xcode/Archives/2017-08-29       |
| clean            | false                                |
| output_directory | .                                    |
| skip_package_ipa | false                                |
| buildlog_path    | ~/Library/Logs/gym                   |
| xcode_path       | /Applications/Xcode.app              |
+------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -workspace ./iTRAIN.xcworkspace      |                      |
| -scheme iTRAINWatch                  |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/Tejas.Ardeshna/Library/Devel  |                      |
| oper/Xcode/Archives/2017-08-29/iTRA  |                      |
| INWatch\ 2017-08-29\                 |                      |
| 12.37.59.xcarchive                   |                      |
| archive                              |                      |
| | tee                                 |                      |
| /Users/Tejas.Ardeshna/Library/Logs/  |                      |
| gym/iTRAINWatch-iTRAINWatch.log      |                      |
| | xcpretty                            |                      |
+--------------------------------------+----------------------+
Looking for iTunes Connect Team with ID 117278598

+--------------------------------------+------------------------------+
|                       deliver 2.54.1 Summary                        |
+--------------------------------------+------------------------------+
| skip_metadata                        | true                         |
| force                                | true                         |
| run_precheck_before_submit           | false                        |
| screenshots_path                     | ./fastlane/screenshots       |
| metadata_path                        | ./fastlane/metadata          |
| username                             | fitness@thecardioguru.com    |
| app_identifier                       | com.yourcardioguru.iMONITORU |
| edit_live                            | false                        |
| platform                             | ios                          |
| skip_binary_upload                   | false                        |
| skip_screenshots                     | false                        |
| skip_app_version_update              | false                        |
| submit_for_review                    | false                        |
| automatic_release                    | false                        |
| dev_portal_team_id                   | J9S3EC3CQP                   |
| overwrite_screenshots                | false                        |
| precheck_default_rule_level          | warn                         |
| ignore_language_directory_validatio  | false                        |
| n                                    |                              |
+--------------------------------------+------------------------------+


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | gym                 | 823         |
| 4    | deliver             | 12          |
| 💥    | crashlytics         | 0           |
+------+---------------------+-------------+



```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "2.32.1"

default_platform :ios
ENV["LANG"] = "en_US.UTF-8"

platform :ios do
   	lane :beta do
	    #increment_build_number
    	#cert(output_path: "./fastlane/certificates")
    	#sigh(output_path: "./fastlane/profiles")
      gym(                                                       # GYM is used to build app
        
        scheme: "iTRAINWatch",                                  # Use your app scheme
        silent: true,
        include_bitcode: true                                  # Include bit code in bit code
        
      )
   	 	deliver(                                                  # DELIVER is used to upload app on itunes connect
          skip_metadata: true,                                # it will skip all meta data to upload on itunes
          force: true, 
          run_precheck_before_submit: false) 
      crashlytics(api_token: '#########',
             build_secret: '#########',
                   emails: 'tejas.a@simform.in',
                   groups: nil,
                    notes: 'Distributed with fastlane',    # Check out the changelog_from_git_commits action
            notifications: true)                           # Should this distribution notify your testers via email?
   	end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.yourcardioguru.iMONITORU" # The bundle identifier of your app
apple_id "fitness@thecardioguru.com" # Your Apple email address

team_id "J9S3EC3CQP"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.54.1  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.53.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.6        |
| rubyzip                   | 1.2.0        |
| bigdecimal                | 1.2.8        |
| psych                     | 2.0.17       |
</details>


*generated on:* **2017-08-29**
</details>

**Comment by ohayon** [comment]
Hey @tejas-ardeshna - Thanks for sharing that output, but I am not seeing the logs from the `gym` execution, could you maybe try running with `--verbose`? Thanks!

**Comment by tejas-ardeshna** [comment]
@ohayon I have attached gym output file(gym.pdf).
[gym.pdf](https://github.com/fastlane/fastlane/files/1266122/gym.pdf)

**Comment by tejas-ardeshna** [comment]
@ohayon  any update on this?
