### ISSUE TITLE
Wrong documentation of "latest_testflight_build_number" action

### ISSUE THREAD

**Issue by kevin-hirsch** [fastlane/fastlane#10150]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The documentation about the action `` contains a mistake for the return value type. It states that the return value is an Integer:

```
+--------------------------------------------------------------------------+
|               latest_testflight_build_number Return Value                |
+--------------------------------------------------------------------------+
| Integer representation of the latest build number uploaded to TestFlight |
+--------------------------------------------------------------------------+
```

While the return value is actually a String.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.12.6                                        |
| Ruby                        | 2.3.2                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.13.5 (Apple Git-94)              |
| Installation Source         | ~/.rbenv/versions/2.3.2/bin/fastlane           |
| Host                        | Mac OS X 10.12.6 (16G29)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.2/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | ~/Downloads/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 0.8.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.12.2       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.1       |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| curb                      | 0.9.3        |
| badge                     | 0.8.4        |
| fastlane-plugin-badge     | 0.8.2        |
</details>

*generated on:* **2017-08-25**
</details>

**Comment by mpirri** [comment]
@kevin-hirsch Thanks for the heads up on this!  Any chance you might be interested in submitting a patch to fix this? We are always looking for awesome changes submitted by our contributors, and this would be an impactful change to help folks use the `latest_testflight_build_number` action.

Thanks again!  🚀
