### ISSUE TITLE
[gym]Your `export_method` in gym is defined as `:development` which can't be used for `ipa` files for beta or App Store distribution

### ISSUE THREAD

**Issue by MessageDream** [fastlane/fastlane#10169]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

> **Your `export_method` in gym is defined as `:development` 
> which can't be used for `ipa` files for beta or App Store distribution**

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.13.0"

proj_name = "Demo"

default_platform :ios

ENV["MATCH_PASSWORD"] = "*******"

platform :ios do

  before_all do
    ensure_git_status_clean
    cocoapods
    # increment_build_number

    unlock_keychain(path:keychain_name, password: "123")
  end

  lane :build_development do |options|
    branch = options[:branch]
    job = options[:job]
    certificates
    build(
      config:"Debug",
      branch:branch,
      job:job
    )
  end

  lane :build_release do
    branch = options[:branch]
    job = options[:job]
    certificates
    build(
      config:"Release",
      branch:branch,
      job:job
    )
  end
  
  desc "readonly:true 不能创建证书，只能读取"
  lane :certificates do
    match(app_identifier: ["com.xxxx.demo.dev"],
      readonly: true,
      git_url:"git@v.xxxxx.git",
      type:"development",
      team_id:"XXXXXXXX",
      keychain_name:keychain_name,
      keychain_password:"123"
    )
  end

  def keychain_name
    mm=`sw_vers -productVersion | awk -F '.' '{print $2}'`
    if mm.to_i < 12
      "login.keychain"
    else
      "login.keychain-db"
    end
  end

  lane :build do |options|
    config = options[:config]
    branch = options[:branch]
    job = options[:job]
    build_number = get_build_number(xcodeproj: proj_name + ".xcodeproj")
    gym(
      export_method:"development",
      clean: true,
      include_bitcode:false,
      configuration: config,
      output_directory: "../",
      output_name: proj_name + "_" + build_number + "_" + Time.now.strftime("%Y%m%d%H%M%S") + ".ipa"
    )
    sh "./transfer.sh " + branch + " " + job
  end

  # This lane is called, only if the executed lane was successful
  after_all do |lane|
  	 sh "pwd"
  	 sh "rm -f ../../*.ipa"
  	 sh "rm -f ../../*.zip"
  	 sh "git checkout ../" + proj_name
  	 #sh "git fetch -p"
  	 clean_build_artifacts
     build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
  	 reset_git_repo
  	 notification(subtitle: "Finished Building", message: "Fastlane finished `#{lane}` successfully") # Mac OS X Notification
  end

  error do |lane, exception|
	 notification(subtitle: "error", message: "Fastlane `#{lane}` errored") # Mac OS X Notification
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxxx.demo.dev" # The bundle identifier of your app
apple_id "xxxxxxx@163.com" # Your Apple email address

#team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.54.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.45.4       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.1       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
| faraday                   | 0.9.2        |
</details>

*generated on:* **2017-08-28**
</details>

**Comment by ohayon** [comment]
Hey @MessageDream, thanks for reporting the issue, could you share a bit more context about this problem? Thank you!! 🚀

**Comment by MessageDream** [comment]
+---------------+------------------------------+
|              Build environment               |
+---------------+------------------------------+
| xcode_path    | /Applications/Xcode-beta.app |
| gym_version   | 2.55.0                       |
| export_method | development                  |
| sdk           | iPhoneOS11.0.sdk             |
+---------------+------------------------------+

[11:16:55]: ▸     export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/Users/jayden/.rvm/gems/ruby-2.3.1/bin:/Users/jayden/.rvm/gems/ruby-2.3.1@global/bin:/Users/jayden/.rvm/rubies/ruby-2.3.1/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin:/Users/jayden/Documents/GoProjects/bin:/usr/local/go/bin:/Users/jayden/Library/Android/sdk/tools:/Users/jayden/Library/Android/sdk/platform-tools:/Users/jayden/Library/Android/android-ndk:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/maven-3.5.0/bin:/Users/jayden/.rvm/bin"
[11:16:55]: ▸     export PRODUCT_TYPE=com.apple.product-type.application
[11:16:55]: ▸     builtin-validationUtility /Users/jayden/Library/Developer/Xcode/DerivedData/HuaJiaoCamera-hjofohyadbawhhaamdgidqmroozx/Build/Intermediates.noindex/ArchiveIntermediates/HuaJiaoCamera/InstallationBuildProductsLocation/Applications/HuaJiaoCamera.app
[11:16:55]: ▸ ** ARCHIVE SUCCEEDED **
[11:16:55]:
[11:16:55]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[11:16:55]: 📋  For the complete and more detailed error log, check the full log at:
[11:16:55]: 📋  /Users/jayden/Library/Logs/gym/HuaJiaoCamera-HuaJiaoCamera.log
[11:16:55]:
[11:16:55]: Your `export_method` in gym is defined as `:development`
[11:16:55]: which can't be used for `ipa` files for beta or App Store distribution
[11:16:55]: Please make sure to define the correct export methods when calling
[11:16:55]: gym in your Fastfile or from the command line
[11:16:55]:
[11:16:55]:
[11:16:55]: Looks like fastlane ran into a build/archive error with your project
[11:16:55]: It's hard to tell what's causing the error, so we wrote some guides on how
[11:16:55]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[11:16:55]: Before submitting an issue on GitHub, please follow the guide above and make
[11:16:55]: sure your project is set up correctly.
[11:16:55]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[11:16:55]: the full commands printed out in yellow in the above log.
[11:16:55]: Make sure to inspect the output above, as usually you'll find more error information there
[11:16:55]:
[11:16:55]: --------------------------
[11:16:55]: --- Step: notification ---
[11:16:55]: --------------------------
+------------------------------------+--------------------------------------------------------------------------------------+
|                                                       Lane Context                                                        |
+------------------------------------+--------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                  |
| PLATFORM_NAME                      | ios                                                                                  |
| LANE_NAME                          | ios build_development                                                                |
| GIT_REPO_WAS_CLEAN_ON_START        | true                                                                                 |
| SIGH_PROFILE_TYPE                  | development                                                                          |
| MATCH_PROVISIONING_PROFILE_MAPPING | {" com.demo.camera.dev"=>"match Development com.demo.camera"} |
| BUILD_NUMBER                       | 1128                                                                                 |
+------------------------------------+--------------------------------------------------------------------------------------+
[11:16:55]: Error packaging up the application

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | cocoapods                           | 4           |
| 5    | unlock_keychain                     | 0           |
| 6    | Switch to ios certificates lane     | 0           |
| 7    | match                               | 1           |
| 8    | Switch to ios build lane            | 0           |
| 9    | get_build_number                    | 0           |
| 💥   | gym                                 | 139         |
| 11   | notification                        | 0           |
+------+-------------------------------------+-------------+

[11:16:55]: fastlane finished with errors

[!] Error packaging up the application

**Comment by navjotbedi** [comment]
I am also facing the same issue after updating the fastlane to 2.55.0

**Comment by KrauseFx** [comment]
Please share the complete output when running fastlane

**Comment by GuilhermeMachado** [comment]
I was having the same problem, try this: 
```
sudo xcode-select --switch <path to your xcode 9>
```

**Comment by ohayon** [comment]
Thanks for following up with the update @GuilhermeMachado ! 🚀

**Comment by ohayon** [comment]
@MessageDream does this work for you as well?

**Comment by useeless37** [comment]
this works for me as well, to my Xcode 8
`sudo xcode-select --switch <path to your xcode 8>`

thanks @GuilhermeMachado !

**Comment by ohayon** [comment]
Glad to hear you all are working! I am going to close this issue for now, but please feel free to reopen if anything comes up. 🚀

**Comment by nathsociete** [comment]
Same problem : sudo xcode-select --switch /Applications/Xcode.app does not help...
In Xcode i have check code signing manual for the app and the widget/extension with valid certificates and provisionning.
I check that i have all certificates and provisionning on my keychain.
I have in my fastfile :
             ```
 sigh(development:true,
              app_identifier:app_identifier,
              provisioning_name:provisioning_name)
		
  		gym(scheme: scheme,
  	  		export_method: "development",	
      		configuration: "Debug",
      		xcargs: xcargs,
      		clean: true,
      		include_bitcode: false)
```

and the provisioning_name is a Debug one 

i have the same output than the one above 

fastlane | 2.58.0

any help ?

**Comment by zooyf** [comment]
I solve the problem by adding `export_options: { compileBitcode: false}` to gym

https://github.com/fastlane/fastlane/issues/10404

**Comment by nathsociete** [comment]
Do not work for me #zooyf 
Trying also with last fastlane | 2.59.0

/Users/XXX/.rvm/gems/ruby-2.4.0/gems/fastlane-2.59.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] 2017-09-27 13:34:45.378 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18) (FastlaneCore::Interface::FastlaneError)
2017-09-27 13:34:48.248 submit Crashlytics: Unable to package source due to error: Error Domain=CLSIPABuilderErrorDomain Code=-6 "(null)" UserInfo={UnderlyingError=Error Domain=CLSCodeSignerErrorDomain Code=-2 "(null)" UserInfo={arguments=(
    "--sign",
    02987AAC295B51E4C2EE692E5C6DFD4FE8EB116A,
    "--all-architectures",
    "--force",
    "--entitlements",
    "/var/folders/t0/7zbtll7126z6491sh5y0jl_m0000gp/T/com.crashlytics.ipas/BE37B3F5-5C7A-43B3-8554-62FF287200E6/Payload/entitlements.xml",
    "/var/folders/t0/7zbtll7126z6491sh5y0jl_m0000gp/T/com.crashlytics.ipas/BE37B3F5-5C7A-43B3-8554-62FF287200E6/Payload/XXX.app"
), environment={
    "CODESIGN_ALLOCATE" = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate";
}, status=1, stderr=02987AAC295B51E4C2EE692E5C6DFD4FE8EB116A: no identity found
, command=/usr/bin/codesign, stdout=}, SourcePath=/var/folders/t0/7zbtll7126z6491sh5y0jl_m0000gp/T/com.crashlytics.ipas/BE37B3F5-5C7A-43B3-8554-62FF287200E6}
2017-09-27 13:34:48.304 submit Crashlytics: Failed to prepare the binary for release
