### ISSUE TITLE
Same file error

### ISSUE THREAD

**Issue by florianhenonin** [fastlane/fastlane#10166]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I try to generate ipa with fastlane I always get that error : 
(Real app names are replaced)

```
+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | Verifying required    | 0           |
|      | fastlane version      |             |
| 2    | default_platform      | 0           |
| 3    | xcversion             | 1           |
| 4    | clean_build_artifacts | 0           |
| 5    | clear_derived_data    | 8           |
| 💥   | gym                   | 1285        |
+------+-----------------------+-------------+

[10:05:36]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/xxx/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1569:in `block in fu_each_src_dest': [!] same file: /var/folders/kb/3qmqmk_569v9ggc23nnc5btm0000gn/T/gym_output20170828-57245-1owcwhu/xx xx xx - xx.ipa and /var/folders/kb/3qmqmk_569v9ggc23nnc5btm0000gn/T/gym_output20170828-57245-1owcwhu/xx xx xx - xx.ipa (ArgumentError)
```

This is my fastline file :
```
fastlane_version "2.54.2"

default_platform :ios

platform :ios do
    lane :xxx_test do
        xcversion(version: "7.3.1") # Selects Xcode version

        clean_build_artifacts
        clear_derived_data

        gym(scheme: "xx xx xx - xx", workspace: "XXX.xcworkspace", include_bitcode: false, clean: true)
        testflight
    end
end

```

In XCode Organizer, even after this error I got my ipa generated after few minutes...
Manual archive works fine.

Any ideas ?

**Comment by florianhenonin** [comment]
Fastlane env :
`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.2                                      |
| Ruby                        | 2.2.4                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.10.1 (Apple Git-78)            |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane          |
| Host                        | Mac OS X 10.12.2 (16C67)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                   |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                   |
| Is contained                | false                                        |
| Is homebrew                 | true                                         |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode8.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.54.2"

default_platform :ios

platform :ios do
    lane :xxx_test do
        xcversion(version: "7.3.1") # Selects Xcode version
	
	clean_build_artifacts
        clear_derived_data

        gym(scheme: "XXXèXX XXX Xxxxx - XXX", workspace: "ScolarIT.xcworkspace", include_bitcode: false, clean: true)
        testflight(app_identifier: "bla.bla.bla")
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "bla.bla.bla" # The bundle identifier of your app
apple_id "xx@xx.xx" # Your Apple email address

team_id "XXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
</details>


*generated on:* **2017-08-28**
</details>`

**Comment by ohayon** [comment]
Hey @florianhenonin - thanks for submitting the issue, apologies for the issue you are seeing. It looks like we are passing the same source and destination to a copy command. Could you run this with `--verbose` and share the full stack trace that gets printed so we can see a bit more context about whats going on in there? Thank you!! 🚀  🐙
