### ISSUE TITLE
Problem using pem within fastlane?

### ISSUE THREAD

**Issue by tsafrir** [fastlane/fastlane#1016]
I had a problem using fastlane with pem but I didn't see a new version for fastlane along with the new version of pem. Anyway that was solved with simple `bundle update`.

Currently fastlane depends on pem 1.1.0 and spaceship 0.18.0, so using pem within a Fastfile will not work as the fix to recent Apple API changes is in spaceship 0.18.1.

**Comment by KrauseFx** [comment]
Thanks, fixed with https://github.com/fastlane/fastlane/pull/1018
