### ISSUE TITLE
Does 'upload_trailer_preview' method in DUClient still work?

### ISSUE THREAD

**Issue by iOkay** [fastlane/fastlane#10165]
I had searched for existing issues. There is no such a issue about the preview of trailer.
I saw the method 'upload_trailer_preview' in DUClient, is it still working? Or the itc support this  feature or not?

**Comment by lacostej** [comment]
It is supposed to work but not properly integrated in fastlane.

**Comment by KrauseFx** [comment]
It's fixed now https://github.com/fastlane/fastlane/pull/10546 👍
