### ISSUE TITLE
Commit 15215dba843 broke deliver upload_screenshots.rb

### ISSUE THREAD

**Issue by Orgmir** [fastlane/fastlane#10173]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Commit 15215dba843a67259936ed8fcc6ec83a49852cca broke upload_screenshots.rb

I'm running this command:
`bundle exec fastlane deliver --force -i "app.ipa"`

The output is below. Following the error log, line 84 in upload_screenshots.rb expects an options hash (which was edited out in the commit):
``` ruby
   def collect_screenshots(options)
      return [] if options[:skip_screenshots]
      return collect_screenshots_for_languages(options[:screenshots_path])
    end

    def collect_screenshots_for_languages(path)
      screenshots = []
      extensions = '{png,jpg,jpeg}'

      available_languages = Spaceship::Tunes.client.available_languages.each_with_object({}) do |lang, lang_hash|
        lang_hash[lang.downcase] = lang
      end

ERR >>>      ignore_validation = options[:ignore_language_directory_validation]

     (...)

    end
```

Output:
```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NameError: [!] undefined local variable or method `options' for #<Deliver::UploadScreenshots:0x007fe8cf1c05d8>
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/upload_screenshots.rb:84:in `collect_screenshots_for_languages'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/upload_screenshots.rb:73:in `collect_screenshots'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/runner.rb:95:in `upload_metadata'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/runner.rb:26:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/commands_generator.rb:173:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/deliver/lib/deliver/commands_generator.rb:12:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.54.3/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.31.0"

default_platform :ios

lane :setup_env do
  ENV["SIGH_TEAM_ID"] = "REDACTED"
  ENV["FASTLANE_ITC_TEAM_ID"] = "REDACTED"
  ENV['CERT_OUTPUT_PATH'] = "./Certs"
  ENV['SIGH_OUTPUT_PATH'] = "./Certs"
  ENV["SLACK_URL"] = "REDACTED"
  ENV["CRASHLYTICS_API_TOKEN"] = "REDACTED"
  ENV["CRASHLYTICS_BUILD_SECRET"] = "REDACTED"
  ENV["CRASHLYTICS_FRAMEWORK_PATH"] = "./Pods/Crashlytics"
  ENV["INFO_PLIST_PATH"] = ".REDACTED.plist"
end

platform :ios do
  before_all do
    setup_env  
    cocoapods
  end

  desc "Submit a new Staging build to Crashlytics"
  lane :staging do
    #crashlytics ios needs adhoc provision profile to sign the ipa (instead of app store)
    sigh(
      adhoc: true,
      app_identifier: 'REDACTED',
      force: true #renew to add devices
    ) 
    gym(scheme: "REDACTED")
    crashlytics

    git_tags = get_info_plist_value(path: ENV["INFO_PLIST_PATH"], key: "CFBundleShortVersionString")
    message = "Staging version #{git_tags} for iOS has been uploaded to Crashlytics. :shipit:"
    slack(
      message: message,
      channel: "#REDACTED",
      username: "Crashlytics",
    )
  end

  desc "Submit a new Release build to Crashlytics"
  lane :release do
    #crashlytics ios needs adhoc provision profile to sign the ipa (instead of app store)
    sigh(
      adhoc: true,
      app_identifier: 'REDACTED',
      force: true #renew to add devices
    ) 
    gym(scheme: "REDACTED")
    crashlytics(groups: "REDACTED")

    git_tags = get_info_plist_value(path: ENV["INFO_PLIST_PATH"], key: "CFBundleShortVersionString")
    message = "Production version #{git_tags} for iOS has been uploaded to Crashlytics. :shipit:"
    slack(
      message: message,
      channel: "#REDACTED",
      username: "REDACTED",
    )
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    sigh(
      app_identifier: 'REDACTED',
      force: true
    )    
    gym(scheme: "REDACTED")
    crashlytics
    deliver(
      force: true
    )
  end

  desc "Add device to profile"
  lane :add_device do |options|
    setup_env
    register_devices( devices: { options[:device_name] => options[:device_id] } )
    sigh(force: true, development: true)
    sigh(force: true, adhoc: true) 
  end

  after_all do |lane|
    
  end

  error do |lane, exception|
    
  end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app
apple_id "REDACTED" # Your Apple email address

team_id "REDACTED" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-29**
</details>

**Comment by ohayon** [comment]
🚀
