### ISSUE TITLE
[gym] detects profile mapping before applying xcconfig

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#10172]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Overriding `PROVISIONING_PROFILE_SPECIFIER` using a `build.xcconfig` file works during compilation with gym, but fails on the archiving step because gym generates an `exportOptions.plist` file with the provisioning profile set in the the xcproject instead of the actual build settings options.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

`fastlane gym --configuration Release --workspace MyProject.xcworkspace --scheme MyProject --output_name MyProject.0.2.0.8 --output_directory ~/Jenkins/workspace/MyProject-Release/build --buildlog_path ~/Jenkins/workspace/MyProject-Release/build/Logs/gym --derived_data_path ~/Jenkins/workspace/MyProject-Release/build --archive_path ~/Jenkins/workspace/MyProject-Release/build/MyProject.0.2.0.8 --export_method ad-hoc --export_team_id XXXXXXXXXX --xcconfig build.xcconfig --xcargs 'OTHER_CODE_SIGN_FLAGS="--keychain jenkins-MyProject-Release"' --clean true`

```
-- gym log --
Detected provisioning profile mapping: {:"com.company.myproject"=>"match AppStore com.company.myproject"}
(...)

-- build log --
Build settings from configuration file 'build.xcconfig':
    PROVISIONING_PROFILE = $(PROVISIONING_PROFILE_$(WRAPPER_EXTENSION))
    PROVISIONING_PROFILE_app = 1744773a-XXXX-XXXX-XXXX-e9ae542cb136
    PROVISIONING_PROFILE_SPECIFIER = match AdHoc com.company.myproject
(...)
Signing Identity:     "iPhone Distribution: My Name (XXXXXXXXXX)"
Provisioning Profile: "match AdHoc com.company.myproject"
                      (1744773a-XXXX-XXXX-XXXX-e9ae542cb136)
(...)

-- gym log --
Generated plist file with the following values:
19:20:38 [19:18:33]: ▸ -----------------------------------------
19:20:38 [19:18:33]: ▸ {
19:20:38 [19:18:33]: ▸   "provisioningProfiles": {
19:20:38 [19:18:33]: ▸     "com.company.myproject": "match AppStore com.company.myproject"
19:20:38 [19:18:33]: ▸   },
19:20:38 [19:18:33]: ▸   "method": "ad-hoc",
19:20:38 [19:18:33]: ▸   "teamID": "XXXXXXXXXX"
19:20:38 [19:18:33]: ▸ }
19:20:38 [19:18:33]: ▸ -----------------------------------------
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.11.6                                         |
| Ruby                        | 2.3.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.9.3 (Apple Git-75)                |
| Installation Source         | /usr/local/bin/fastlane                         |
| Host                        | Mac OS X 10.11.6 (15G1510)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib              |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-8.1.app/Contents/Developer/ |
| Xcode Version               | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.2       |
| io-console                | 0.4.5        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-08-28**
</details>

**Comment by lkraider** [comment]
Question: can the `provisioningProfiles` export_options be provided on command line invocation?

**Comment by KrauseFx** [comment]
@lkraider no, you can only provide the `provisioningProfiles` hash via either a `Fastfile` (recommended) or a `Gymfile`, both located inside the `fastlane` directory.

**Comment by lkraider** [comment]
Thanks, I'll look into dynamically generating the Gymfile during the build then.

**Comment by pedro380085** [comment]
For me what worked was setting PROVISIONING_PROFILE_SPECIFIER = "" on xcode itself (at project.pbxproj).
