### ISSUE TITLE
PEM force to create new Push certificate even if set --force: false

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#10177]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In previous time, pem will not renew Push certificate if the Certificate has expiry date more than 30 days.  But recently, a month ago, pem forces to create new  Push certificate even if the Push Certificate has been created since few minute.

I already set option ``--force false `` but pem still  forces to create new one.

``` pem(generate_p12: true, p12_password: 'xxxxxx', pem_name: APP_NAME, force: false)```

##### 

Current log, even if I has just created Push notification in few minute before.

14:36:40]: Starting login with user 'jm.developers@abc.com'
[14:36:42]: Successfully logged in
[14:36:43]: [33mCreating a new push certificate for app 'com.abc.abc'.[0m
[14:36:47]: [32mPrivate key: [0m/Users/Shared/Home/iOS_fastlane_Match/workspace/APP.pkey
[14:36:47]: [32mp12 certificate: [0m/Users/Shared/Home/iOS_fastlane_Match/workspace/APP.p12
[14:36:47]: [32mPEM: [0m/Users/Shared/Home/iOS_fastlane_Match/workspace/APP.pem
### Environment

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.5        |
</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

**Comment by ohayon** [comment]
Hey @biolinh, could you try setting the `active_days_limit` parameter to a reasonable number of days? That is supposed to default to 30, but I'm curious if something may be going wrong in there. Thanks! 🚀  🐙

**Comment by biolinh** [comment]
Hi @ohayon. Thank you for your respond.

I try to renew Push Certificate of the app expired in 10 days (Sep 09, 2017)
![screen shot 2017-08-31 at 10 38 56 am](https://user-images.githubusercontent.com/1267094/29905414-bbbccbac-8e38-11e7-8669-731ae0f193a2.png)

with the command:
``` pem --generate_p12  true -p 'xxxxxx' --pem_name  "magento-test" --force  false —active_days_limit 30 ```

**CASE 1:** The first time, it generated a new one

+------------------+--------------+
|      Summary for PEM 1.4.1      |
+------------------+--------------+
| generate_p12     | true         |
| p12_password     | ********     |
| pem_name         | magento-test |
| force            | false        |
| development      | false        |
| save_private_key | true         |
| output_path      | .            |
+------------------+--------------+

[10:31:20]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: linh.nguyen@abc.com
[10:31:26]: Starting login with user 'linh.nguyen@abc.com'
[10:31:29]: Successfully logged in
[10:31:30]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: com.abc.app.magento-test
[10:31:37]: Creating a new push certificate for app 'com.abc.app.magento-test'.
[10:31:39]: Private key: /Users/linh/Documents/magento-test.pkey
[10:31:39]: p12 certificate: /Users/linh/Documents/magento-test.p12
[10:31:39]: PEM: /Users/linh/Documents/magento-test.pem

Then I got the complete new one beside the exited one.
![screen shot 2017-08-31 at 10 44 09 am](https://user-images.githubusercontent.com/1267094/29905562-9e7642f2-8e39-11e7-80b5-d140bb329245.png)

------------------------------
**CASE 2:** Run the command again

``` pem --generate_p12  true -p 'xxxxxx' --pem_name  "magento-test" --force  false —active_days_limit 30 ```

it returns
+------------------+--------------+
|      Summary for PEM 1.4.1      |
+------------------+--------------+
| generate_p12     | true         |
| p12_password     | ********     |
| pem_name         | magento-test |
| development      | false        |
| force            | false        |
| save_private_key | true         |
| output_path      | .            |
+------------------+--------------+

[10:36:52]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: linh.nguyen@abc.com
[10:37:01]: Starting login with user 'linh.nguyen@abc.com'
[10:37:05]: Successfully logged in
[10:37:05]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: com.abc.app.magento-test
[10:37:07]: Creating a new push certificate for app 'com.abc.app.magento-test'.
[10:37:09]: {"responseId"=>"e7831efb-59c4-417f-9733-5963c8f80a1a", "resultCode"=>7460, "resultString"=>"Maximum number of certificates generated", "userString"=>"You already have a current Apple Push Services certificate or a pending certificate request.", "creationTimestamp"=>"2017-08-31T03:37:05Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action", "httpCode"=>200}

[!] You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one

**CASE 3:**  Run the command 2 times. I got the same results as above.

``` pem --generate_p12  true -p 'xxxxxx' --pem_name  "magento-test"  —active_days_limit 30 ```

**CASE 4:** Run the command

``` pem --generate_p12  true -p 'xxxxxx' --pem_name  "magento-test"  ```

i got

+------------------+--------------+
|      Summary for PEM 1.4.1      |
+------------------+--------------+
| generate_p12     | true         |
| p12_password     | ********     |
| pem_name         | magento-test |
| development      | false        |
| force            | false        |
| save_private_key | true         |
| output_path      | .            |
+------------------+--------------+

[10:36:52]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: linh.nguyen@abc.com
[10:37:01]: Starting login with user 'linh.nguyen@abc.com'
[10:37:05]: Successfully logged in
[10:37:05]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: com.abc.app.magento-test
[10:37:07]: Creating a new push certificate for app 'com.abc.app.magento-test'.
[10:37:09]: {"responseId"=>"e7831efb-59c4-417f-9733-5963c8f80a1a", "resultCode"=>7460, "resultString"=>"Maximum number of certificates generated", "userString"=>"You already have a current Apple Push Services certificate or a pending certificate request.", "creationTimestamp"=>"2017-08-31T03:37:05Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action", "httpCode"=>200}

[!] You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one


It SEEMs it try to create a new one.

**Comment by biolinh** [comment]
<h2>**CASE 4:**  </h2>Make a lane, it verified that the expired date more than 30 days and no need to create a new one

> ```
>  lane :test do 
>      pem(generate_p12: true, p12_password: 'xxxxx', pem_name: ENV["APP_NAME"], force: false)
>   end
> 
> ````

I got

[11:41:14]: -----------------
[11:41:14]: --- Step: pem ---
[11:41:14]: -----------------

+-------------------+--------------------------------+
|               Summary for PEM 2.54.4               |
+-------------------+--------------------------------+
| generate_p12      | true                           |
| p12_password      | ********                       |
| pem_name          | magento-test                   |
| force             | false                          |
| development       | false                          |
| active_days_limit | 30                             |
| save_private_key  | true                           |
| app_identifier    | com.abc.app.magento-test |
| username          | linh.nguyen@abc.com      |
| output_path       | .                              |
+-------------------+--------------------------------+

[11:41:14]: Starting login with user 'linh.nguyen@abc.com'
[11:41:17]: Successfully logged in
[11:41:18]: Existing push notification profile for 'com.abc.app.magento-test' is valid for 395 more days.
[11:41:18]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
[11:41:18]: If you still want to create a new one, use the --force option when running PEM.


<h2>BUT in Case 5:</h2>

Make a lane, it verified that the expired date more than 30 days, it created a new one even if  the certificate has just been created.

 

> lane :test do
>   sh "fastlane produce enable_services --push-notification"
>   pem(generate_p12: true, p12_password: 'xxxxx', pem_name: ENV["APP_NAME"], force: false)
>   end

I find the same error i get.

[11:47:18]: --- Step: pem ---
[11:47:18]: -----------------

+-------------------+--------------------------------+
|               Summary for PEM 2.54.4               |
+-------------------+--------------------------------+
| generate_p12      | true                           |
| p12_password      | ********                       |
| pem_name          | magento-test                   |
| force             | false                          |
| development       | false                          |
| active_days_limit | 30                             |
| save_private_key  | true                           |
| app_identifier    | com.abc.app.magento-test |
| username          | linh.nguyen@abc.com      |
| output_path       | .                              |
+-------------------+--------------------------------+

[11:47:18]: Starting login with user 'linh.nguyen@abc.com'
[11:47:20]: Successfully logged in
[11:47:20]: Creating a new push certificate for app 'com.abc.app.magento-test'.
[11:47:24]: Private key: /Users/.../magento-test.pkey
[11:47:24]: p12 certificate: /Users/.../magento-test.p12
[11:47:24]: PEM: /Users/.../magento-test.pem


I find out the error that it I run the command enable the push notification then generate a new push certificate, it will force to renew one

**Comment by ohayon** [comment]
Hmm, I think that this has something to do with the fact that by calling `produce` first, and enabling push notifications, that it is changing the state of the certs on the developer portal. Is there a reason why you are calling produce every time?

**Comment by biolinh** [comment]
@ohayon 

Yes, I create a lane to create a application for first publishing.  and I set a rule if input is 1 then call the createnewapp lane but input isnot 1, it doesn't call it. but my enduser usually forget that.

Beside that, in previously, if they forget that it doesn't force to renew Push certificate.

>...
 if publishing == '1'
      createnewapp
    end 
...

> lane :createnewapp do
      sh "fastlane-credentials add --username FASTLANE_USER --password KEYCHAIN_PASSWORD"
      produce( 
        username: FASTLANE_USER, 
        app_name: APP_NAME,
        team_id: TEAM_ID,
        team_name: TEAM_NAME,
        app_identifier: BUNDLE_ID,
        language: PRODUCE_LANGUAGE ,
        sku: BUNDLE_ID,
        company_name: TEAM_NAME,
        itc_team_id: DELIVER_TEAM_ID,
        skip_itc: 'false'
        )
      sh "fastlane produce enable_services --push-notification"
      pem(generate_p12: true, p12_password: 'xxxxxx', pem_name: APP_NAME)
      sh "fastlane-credentials remove --username $FASTLANE_USER" 
  end
