### ISSUE TITLE
Spaceship frequently throws UnauthorizedAccessError

### ISSUE THREAD

**Issue by edwardmp** [fastlane/fastlane#10181]
I use Spaceship to programatically add external Testflight testers. But frequently I encounter `Spaceship::Client::UnauthorizedAccessError`, seemingly randomly. At one moment, adding a tester works fine, another moment it stops working (without any changes to code/iTunes connect accounts). Whenever Rollbar reports one of this issues, I can't reproduce the issue if I run this code manually through the Rails console. However, once I execute this code from the long running sidekiq process, I can reproduce the issue straight away. If I restart the Sidekiq process, the issue doesn't reappear for a while.

It seems some kind of session is timed out and not refreshed. Possibly related issue: https://github.com/fastlane/boarding/issues/136

##### Complete output when running fastlane, including the stack trace and command used
```
1 File "/app/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.2/spaceship/lib/spaceship/client.rb" line 685 in block in send_request
2 File "/app/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.2/spaceship/lib/spaceship/client.rb" line 520 in with_retry
3 File "/app/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.2/spaceship/lib/spaceship/client.rb" line 679 in send_request
4 File "/app/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.2/spaceship/lib/spaceship/client.rb" line 568 in request
5 File "/app/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.2/spaceship/lib/spaceship/test_flight/client.rb" line 133 in create_app_level_tester
6 File "/app/vendor/bundle/ruby/2.4.0/gems/fastlane-2.54.2/spaceship/lib/spaceship/test_flight/tester.rb" line 47 in create_app_level_tester
7 File "/app/app/jobs/testflight_external_tester_adder_job.rb", line 11 in perform

```

### Environment
See [this](https://gist.github.com/edwardmp/d42b2ecf632e2db9eb823e7a49cbf56c) gist.

The code I use:
```ruby
  spaceship = Spaceship::Tunes.login(Rails.application.secrets.itunes_connect_api[:username], Rails.application.secrets.itunes_connect_api[:password])
    spaceship.select_team

    app = Spaceship::Tunes::Application.find(Rails.application.config.itunes_connect_app_id)
    tester = Spaceship::TestFlight::Tester.create_app_level_tester(app_id: app.apple_id,
                                                                   first_name: customer.first_name,
                                                                   last_name: customer.last_name,
                                                                   email: customer.email)

    tester = Spaceship::Tunes::Tester::External.find_by_app(app.apple_id, customer.email)
    Spaceship::TestFlight::Group.add_tester_to_groups!(tester: tester, app: app, groups: %w[External])

    Rails.logger.info("Added #{customer.email} to TestFlight")
```

**Comment by ohayon** [comment]
Hey @edwardmp - I just have a question that might help clarify something for me... Are you adding testers in a one-off manner? Or are testers being added after an IPA upload or some other longer-running action? Thanks! 🐙

**Comment by edwardmp** [comment]
One-off, that code above is what I literally run in an ActiveJob

**Comment by ohayon** [comment]
Hmmm - thanks for the quick response @edwardmp! Sorry to keep grilling you, but I have one more question... If you run into that 403 and then run it immediately again, do you ever see the error twice in a row? Also, is this happening in CI or on your local machine? I'm not sure I know what an ActiveJob is. Thanks again! 👍

**Comment by edwardmp** [comment]
@ohayon 
Yes, the error will keep reappearing until (seemingly) I kill/restart the master process running this.

This happens on my Heroku dyno.

ActiveJob is just a Rails abstraction for an asynchronous task, not really relevant for this discussion.

**Comment by ohayon** [comment]
Ohhh, interesting! Thats pretty cool that you have this running in Heroku! Aside from this issue, I would love to hear more about that.

Can you share the logs where you are seeing the UnauthorizedAccessError? Our could _should_ be retrying the request a few times, but its possible something is wrong in there.

**Comment by edwardmp** [comment]
@ohayon what kind of logging do you wish to see aside from a stack trace?

Regarding our use case: we currently have an app we wish to test in a relatively small group (not public), but still large enough (few thousand testers) that we do not wish to add people manually to iTunes Connect. We already have all the needed data, that's why every time someone signs up for the pilot of our service I try to add it to TestFlight through Spaceship. Hope we can find out what happens here because currently it fails more often than it works which is not ideal for our process.

**Comment by KrauseFx** [comment]
Very often those error will also happen due to server errors on Apple's side 😢

**Comment by edwardmp** [comment]
@KrauseFx that might explain some of it but not all imho. Often Rollbar would notify me of an `UnauthorizedAccessError`, I would then spin up a new heroku dyno (heroku run rails c) and run this job manually and it would work fine. Does seem this has to do something with some cookie expiring.

**Comment by edwardmp** [comment]
Unfortunately we had to stop using Spaceshipf for this use case since it didn't appear to work in the majority of the cases leading to inconsistency in our process.
