### ISSUE TITLE
import_from_git versioning

### ISSUE THREAD

**Issue by bramseynhaeve** [fastlane/fastlane#10189]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We're using Fastlane at our company for a lot of iOS projects to build and deliver our apps.
To make it all maintainable, we're using a hosted Fastfile that has everything in place to build the apps.
We make use of `import_from_git` to do that. This had lots of benefits, for example: pushing an update to the hosted Fastfile repo had direct impact to all our project. All changes to it have to be compatible with the projects of-course. 

Recently we started working on a new, better version of our hosted Fastfile, but we want to avoid problems after finishing up that release. Once merged, all projects should adapt the new Fastfile immediately. But at our scale, that's not an option. 

So it would be nice for us if we could use some kind of versioning with the import function.

For example:
`import_from_git(url: 'git@example.com:project.git', version:'1.*')`
or  
`import_from_git(url: 'git@example.com:project.git', version:'~> 1.0')`
or
`import_from_git(url: 'git@example.com:project.git', tag:'1.*')`
etc.

I'm aware that we can use git tags, but it's currently not possible allow new versions being used within a specific version range.

Is this something we can add to Fastlane, or are there any other/better ideas to fix this problem?

Thanks

**Comment by ohayon** [comment]
Hey @bramseynhaeve! That is a cool use case, we would definitely be happy to review a PR with a change allowing versioning in the `import_from_git` action! 🚀

**Comment by PetrosIchor** [comment]
An easier solution is to ditch git import.  Add a submodule with the standard import.  Then use submodules to version/branch you fastlane pipelines.
