### ISSUE TITLE
All CLI Commands in a single command?

### ISSUE THREAD

**Issue by isolatedperson** [fastlane/fastlane#10188]
Hi there,

Currently fastlane init works by asking multiple questions like is it iOS project, is code committed etc. What i want is call fastlane init in a single command by passing all the required parameters at once, this will help me automate the process.

Something like that?
fastlane init -no -yes -PATH_TO_JSON -bundleid and so on.

Please advise

**Comment by ohayon** [comment]
Hey @isolatedperson - Currently the `init` command is designed to prompt you for input about your project that _fastlane_ cant figure out on it's own. If you know all of the values you want to have in your setup, I think the best course of action would be to manually create your Fastfile and configure it how ever you would like for your projects. Another option is making a sort of Fastfile template that you could automate copying and filling in placeholders. I hope that's helpful! 🚀  Let us know if you have any questions!

**Comment by isolatedperson** [comment]
I tested it with Android and as for as Android is concerned using Template approach works, ill test with iOs and let you know in case some issue come.

**Comment by ohayon** [comment]
🎉  Awesome! If you don't mind, I am going to close this issue but feel free to continue conversation here and reopen it if necessary! 🚀
