### ISSUE TITLE
Feature request: Gradle test result support for Slack plugin

### ISSUE THREAD

**Issue by astasiak93** [fastlane/fastlane#10192]
Hey,
I discovered Fastlane slack plugin does not support test results from gradle builds - notifications with test results are sent only for scan execution. 
Could you add support for gradle builds?

**Comment by ohayon** [comment]
Hey @astasiak93! Thanks for submitting the feature request. That would be great to have. Is there any chance you would want to submit a PR adding that functionality? We love to see this type of feature work come in from our community! 😄  🐙  🚀 !
