### ISSUE TITLE
Can not upload ipa by fastlane deliver

### ISSUE THREAD

**Issue by huanling713** [fastlane/fastlane#10193]
hi , everybody:

I can,t upload ipa by fastlane deliver while my network is using a proxy only support TCP ,

Has any one get solution for it ?Thanks.

### Issue Description

```
DEBUG [2017-08-30 19:23:34.61]: [Transporter]: INFO: Trying UDP sgr206.apple.com/17.152.249.106:44001 

...
DEBUG [2017-08-30 19:23:35.79]: [Transporter]: INFO: Connected to UDP sgr206.apple.com/17.152.249.106:44001 

DEBUG [2017-08-30 19:23:36.15]: [Transporter]: INFO: Authenticating
DEBUG [2017-08-30 19:23:37.07]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2017-08-30 19:23:37.07]: [Transporter]: INFO: Setting up data streams
DEBUG [2017-08-30 19:23:57.46]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2017-08-30 19:23:58.49]: [Transporter]: DEBUG: An error has occurred during the upload.
DEBUG [2017-08-30 19:23:58.49]: [Transporter]: DEBUG: An exception has occurred: The operation timed out.
DEBUG [2017-08-30 19:23:58.49]: [Transporter]: DEBUG: Transfer error: The operation timed out.
DEBUG [2017-08-30 19:23:58.49]: [Transporter]: DEBUG: Received failed transfer notification; aborting
DEBUG [2017-08-30 19:23:58.49]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2017-08-30 19:23:58.49]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2017-08-30 19:23:58.62]: [Transporter]: INFO: T**he Signiant transport is encountering difficulties with the upload. This may be caused by a firewall or network configuration preventing access.**
DEBUG [2017-08-30 19:23:58.62]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
DEBUG [2017-08-30 19:23:58.63]: [Transporter]: INFO: Using Signiant UDP transport
DEBUG [2017-08-30 19:23:58.63]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
DEBUG [2017-08-30 19:23:58.63]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
DEBUG [2017-08-30 19:23:58.63]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
DEBUG [2017-08-30 19:23:58.63]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2017-08-30 19:23:58.74]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
DEBUG [2017-08-30 19:23:58.74]: [Transporter]: INFO: Processing URL list: mxwan://sgr404.apple.com:44001 

/
DEBUG [2017-08-30 19:23:58.74]: [Transporter]: INFO: Trying UDP sgr404.apple.com/17.172.190.104:44001 

...
DEBUG [2017-08-30 19:23:59.97]: [Transporter]: INFO: Connected to UDP sgr404.apple.com/17.172.190.104:44001 

DEBUG [2017-08-30 19:24:00.45]: [Transporter]: INFO: Authenticating
DEBUG [2017-08-30 19:24:01.66]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2017-08-30 19:24:01.66]: [Transporter]: INFO: Setting up data streams
DEBUG [2017-08-30 19:24:22.16]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2017-08-30 19:24:23.18]: [Transporter]: DEBUG: An error has occurred during the upload.
DEBUG [2017-08-30 19:24:23.18]: [Transporter]: DEBUG: An exception has occurred: The operation timed out.
DEBUG [2017-08-30 19:24:23.18]: [Transporter]: DEBUG: Transfer error: The operation timed out.
DEBUG [2017-08-30 19:24:23.18]: [Transporter]: DEBUG: Received failed transfer notification; aborting
DEBUG [2017-08-30 19:24:23.18]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2017-08-30 19:24:23.18]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
```

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 1.9.2                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.2 (16C68)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | 鉁?|
| LC_ALL   | en_US.UTF-8 | 鉁?|
| LANGUAGE | en_US.UTF-8 | 鉁?|

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.54.2  | 馃毇 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.4       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-30**

**Comment by ohayon** [comment]
Hey @huanling713 apologies for the issues youre seeing. We have some docs around handling proxies. Take a look at https://github.com/fastlane/fastlane/tree/master/deliver#firewall-issues and let us know if you have any more issues! 🚀

**Comment by huanling713** [comment]
@ohayon Thanks for your reply. I use the following command:
fastlane deliver run -i xxx.ipa --skip_metadata --skip_screenshots -x false -u xxx@xxx.com DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV -Dhttp.proxyHost=myproxy_ip -Dhttp.proxyPort=8080"

Then the error info is still exist and not changed. Is there someting missing for config network? Thanks.

**Comment by huanling713** [comment]
@KrauseFx Can you give me a advice?
Thanks.

**Comment by KrauseFx** [comment]
Yah this is a firewall issue, can you try connecting with a VPN or using your iPhone as internet hotspot?

**Comment by huanling713** [comment]
@KrauseFx Thanks，I will consider anther network enviorment.
