### ISSUE TITLE
[!] No ipa file given  | unable to get started with fastlane using Expo

### ISSUE THREAD

**Issue by jpca999** [fastlane/fastlane#10196]
![image](https://user-images.githubusercontent.com/1026325/29873590-cadc15ca-8d61-11e7-97e9-315aa99a98d5.png)

Im new, pls guide. 

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by jpca999** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
</details>


*generated on:* **2017-08-30**
</details>

**Comment by ohayon** [comment]
Hey @jpca999 - This is definitely a weird issue. Could I ask one question: What is Expo?

**Comment by jpca999** [comment]
@ohayon   Expo makes it easy to make React native apps.   
https://expo.io/

**Comment by ohayon** [comment]
Oh cool! Ah I think I see the error there. You need to pass an option to your command rather than just the path. Could you try running `fastlane pilot -i /path/to/ipafile.ipa` ?

**Comment by jpca999** [comment]
it gave me this output  

![image](https://user-images.githubusercontent.com/1026325/29880607-35f098ea-8d76-11e7-8e56-8dc51d95f1cf.png)

**Comment by ohayon** [comment]
Hmmm... have you tried doing this in a `Fastfile`? You could make a lane that does:
```
lane :beta do
  pilot(ipa: "/path/to/ipa")
end
```

And then run `fastlane beta` to execute that lane.

**Comment by jpca999** [comment]
nope, i haven't . @ohayon   

so i created the file   fastlate/Fastfile  
is it Fastfile.rb ?

**Comment by ohayon** [comment]
Ah, my bad @jpca999 - Could you create, in your project directory, a directory called `fastlane` and within that directory, make a file called `Fastfile` with no extension, that should get things working for you hopefully ! 🚀

**Comment by jpca999** [comment]
@ohayon  Wow, It seems like its doing the magic..   How do i change the the code if i have to upload it to the android store ?

**Comment by ohayon** [comment]
Glad to see thats working for you 🎉  🚀 !! If you want to upload to the Play store have a look at our docs for _supply_ here: https://github.com/fastlane/fastlane/blob/master/supply/README.md

**Comment by ohayon** [comment]
I am going to close this issue as it seems like your iOS setup is 💯  now. Please feel free to continue talking about `pilot` here if you'd like, and if you have any questions about supply, feel free to open up a new issue! Thanks again! 😄
