### ISSUE TITLE
Sigh keeps on generating new provisioning profile

### ISSUE THREAD

**Issue by nremond** [fastlane/fastlane#10191]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Everytime `sigh` is executed, it generates a new profile instead of using the current one. 

```
[master] nicolas@~/developments/in-and-win/iaw-mobile/ios: sigh

+-------------------------------------+-------------------------+
|                    Summary for sigh 2.54.3                    |
+-------------------------------------+-------------------------+
| adhoc                               | false                   |
| development                         | false                   |
| skip_install                        | false                   |
| force                               | false                   |
| app_identifier                      | com.in-and-win.inandwin |
| username                            | nicolas@in-and-win.com  |
| team_id                             | N8A7WE9B49              |
| ignore_profiles_with_different_name | false                   |
| skip_fetch_profiles                 | false                   |
| skip_certificate_verification       | false                   |
| platform                            | ios                     |
+-------------------------------------+-------------------------+

[12:54:14]: Starting login with user 'nicolas@in-and-win.com'
[12:54:16]: Successfully logged in
[12:54:16]: Fetching profiles...
[12:54:17]: Verifying certificates...
[12:54:17]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[12:54:19]: Creating new provisioning profile for 'com.in-and-win.inandwin' with name 'com.in-and-win.inandwin AppStore' for 'ios' platform
[12:54:21]: Downloading provisioning profile...
[12:54:22]: Successfully downloaded provisioning profile...
[12:54:22]: Installing provisioning profile...
/Users/nicolas/developments/in-and-win/iaw-mobile/ios/AppStore_com.in-and-win.inandwin.mobileprovision
[master] nicolas@~/developments/in-and-win/iaw-mobile/ios: sigh

+-------------------------------------+-------------------------+
|                    Summary for sigh 2.54.3                    |
+-------------------------------------+-------------------------+
| adhoc                               | false                   |
| development                         | false                   |
| skip_install                        | false                   |
| force                               | false                   |
| app_identifier                      | com.in-and-win.inandwin |
| username                            | nicolas@in-and-win.com  |
| team_id                             | N8A7WE9B49              |
| ignore_profiles_with_different_name | false                   |
| skip_fetch_profiles                 | false                   |
| skip_certificate_verification       | false                   |
| platform                            | ios                     |
+-------------------------------------+-------------------------+

[12:54:56]: Starting login with user 'nicolas@in-and-win.com'
[12:54:59]: Successfully logged in
[12:54:59]: Fetching profiles...
[12:54:59]: Verifying certificates...
[12:54:59]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[12:55:03]: The name 'com.in-and-win.inandwin AppStore' is already taken, using another one.
[12:55:03]: Creating new provisioning profile for 'com.in-and-win.inandwin' with name 'com.in-and-win.inandwin AppStore 1504090503' for 'ios' platform
[12:55:05]: Downloading provisioning profile...
[12:55:07]: Successfully downloaded provisioning profile...
[12:55:07]: Installing provisioning profile...
/Users/nicolas/developments/in-and-win/iaw-mobile/ios/AppStore_com.in-and-win.inandwin.mobileprovision
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.26.0"

default_platform :ios

platform :ios do


  ############################## PRE ##############################

  before_all do
    ensure_git_status_clean
    
    # sh "./scripts/remove_pods.sh"
    # cocoapods
    
    increment_build_number
  end

  ######################### PUBLIC LANES ##########################

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    # Before calling match, we make sure all our devices are registered on the Apple Developer Portal
    register_devices(devices_file: "beta_devices.txt")

    # After registering the new devices, we'll make sure to update the provisioning profile if necessary
    match(git_url: "git@bitbucket.org:in-and-win/iaw-certificates.git",
      type: "adhoc",
      force_for_new_devices: true,
      app_identifier: "com.in-and-win.InAndWin.beta")

    sigh(adhoc: true, force: false)
   
    gym(scheme: "InAndWin", configuration: "AdHoc")
    
    crashlytics(
        api_token: '747b67fdd816e8498266563f1344f674b031e297',
        build_secret: '71daad9e2c7f719ee76b244915ff72d07dc47e510926abe4bd70e40f027beb7b'
        )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(git_url: "git@bitbucket.org:in-and-win/iaw-certificates.git",
      type: "appstore",
      app_identifier: "com.in-and-win.InAndWin")

    # snapshot
    gym(scheme: "InAndWin", configuration: "Store") # Build your app - more options available
    deliver(force: true)

    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.in-and-win.inandwin" # The bundle identifier of your app
apple_id "nicolas@in-and-win.com" # Your Apple email address

team_id "N8A7WE9B49" # Developer Portal Team ID

for_platform :ios do
  for_lane :beta do
    app_identifier 'com.in-and-win.inandwin.beta'
  end
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.4       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-30**
</details>

**Comment by ohayon** [comment]
Hey @nremond, would you mind running this in verbose mode and sharing the output? Might help us see some more context about what is going on. Also, I noticed that you are calling `sigh` directly, could you also share the output of `gem which sigh`? I want to see if you might have an old version of `sigh` that is getting called instead of a newer version that is inside of fastlane. Thanks! 🚀

**Comment by nremond** [comment]
I have this issue with `fastlane beta` and I have been able to reproduce by simply calling `sigh`. The command is calling fastlane though:

```
$which sigh
/Users/nicolas/.fastlane/bin/sigh
```

Here is the verbose output:

```
[master] nicolas@~/developments/in-and-win/iaw-mobile/ios: sigh --verbose
Successfully loaded Appfile at path '/Users/nicolas/developments/in-and-win/iaw-mobile/ios/fastlane/Appfile'
- app_identifier: 'com.in-and-win.inandwin'
- apple_id: 'nicolas@in-and-win.com'
- team_id: 'N8A7WE9B49'
-------

+-------------------------------------+-------------------------+
|                    Summary for sigh 2.54.4                    |
+-------------------------------------+-------------------------+
| adhoc                               | false                   |
| development                         | false                   |
| skip_install                        | false                   |
| force                               | false                   |
| app_identifier                      | com.in-and-win.inandwin |
| username                            | nicolas@in-and-win.com  |
| team_id                             | N8A7WE9B49              |
| ignore_profiles_with_different_name | false                   |
| skip_fetch_profiles                 | false                   |
| skip_certificate_verification       | false                   |
| platform                            | ios                     |
+-------------------------------------+-------------------------+

INFO [2017-08-30 21:43:57.57]: Starting login with user 'nicolas@in-and-win.com'
INFO [2017-08-30 21:43:59.68]: Successfully logged in
INFO [2017-08-30 21:43:59.68]: Fetching profiles...
INFO [2017-08-30 21:44:00.50]: Verifying certificates...
WARN [2017-08-30 21:44:00.51]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
INFO [2017-08-30 21:44:02.89]: $ security list-keychains -d user
INFO [2017-08-30 21:44:02.90]: ▸     "/Users/nicolas/Library/Keychains/login.keychain-db"
INFO [2017-08-30 21:44:02.90]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/nicolas/Library/Keychains/login.keychain-db
INFO [2017-08-30 21:44:02.94]: ▸ keychain: "/Users/nicolas/Library/Keychains/login.keychain-db"
INFO [2017-08-30 21:44:02.94]: ▸ version: 512
INFO [2017-08-30 21:44:02.94]: ▸ class: 0x80001000
INFO [2017-08-30 21:44:02.94]: ▸ attributes:
INFO [2017-08-30 21:44:02.94]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-08-30 21:44:02.94]: ▸     "cenc"<uint32>=0x00000003
INFO [2017-08-30 21:44:02.94]: ▸     "ctyp"<uint32>=0x00000001
INFO [2017-08-30 21:44:02.94]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2017-08-30 21:44:02.94]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2017-08-30 21:44:02.94]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-08-30 21:44:02.94]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2017-08-30 21:44:02.96]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2017-08-30 21:44:02.96]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
ERROR [2017-08-30 21:44:03.92]: The name 'com.in-and-win.inandwin AppStore' is already taken, using another one.
WARN [2017-08-30 21:44:03.92]: Creating new provisioning profile for 'com.in-and-win.inandwin' with name 'com.in-and-win.inandwin AppStore 1504122243' for 'ios' platform
WARN [2017-08-30 21:44:06.41]: Downloading provisioning profile...
INFO [2017-08-30 21:44:09.47]: Successfully downloaded provisioning profile...
INFO [2017-08-30 21:44:09.54]: Installing provisioning profile...
/Users/nicolas/developments/in-and-win/iaw-mobile/ios/AppStore_com.in-and-win.inandwin.mobileprovision
```


Thank you

**Comment by jaleksynas** [comment]
@nremond I have seen this occur if you don't have the proper certificates available or the certificate has expired for the `com.in-and-win.inandwin AppStore` as noted by `No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you`.  

`sigh` then notices that you already have a profile of the "preferred" name and then just makes a new one.  (https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb#L128-L141)

WORKAROUND:: I usually manually remove all the profiles and let sigh just make a new on of the preferred name with the certificate available.

ENHANCEMENT: A nicer behavior may be to search for a valid profile in the list of all profiles for the app_id, once that search is exhausted create! can be called.
