### ISSUE TITLE
"Error parsing provisioning profile" when running fastlane on cron job

### ISSUE THREAD

**Issue by deborahhh** [fastlane/fastlane#1020]
I'm trying to run a cron job with my fastlane actions, but I get this "Error parsing provisioning profile" error after running sigh. I looked into the code, and it seems to me that the cron job can't run the command "security cms -D -i #{path}" from provisioning_profile.rb to parse the provisioning profile. The path to the profile is correct. Is there a way to fix this?

It works fine when I run on the terminal.

**Comment by deborahhh** [comment]
Ok, here's what I found:
I ran security cms from the cronjob, and changed some stuff to make it work
- I need to add some certificates (not sure which ones yet, but I copied my login keychain and it worked) to my System.keychain, to be available to the cron job so it can decode it
- I need to use 'sudo' when running the security command, so I don't get a "security: cert import failed: write permissions error"

but I don't want to add the sudo... anyway I can fix this?

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
