### ISSUE TITLE
"Ran into error while trying to connect to iTunes Connect / Dev Portal: `bundle_id` parameter must not be nil"

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10202]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

From my googling this seems to be an old error that is now back: `Ran into error while trying to connect to iTunes Connect / Dev Portal: `bundle_id` parameter must not be nil` It was talked about multiple times before, but fixes where done every time in the past.

Here is the complete sequence:
```
Jans-MBP:fastlaneTest sujan$ fastlane init
[18:45:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:45:59]: Couldn't automatically detect the platform
[18:45:59]: Is this project an iOS project? (y/n)
y
[18:46:28]: This setup will help you get up and running in no time.
[18:46:28]: fastlane will check what tools you're already using and set up
[18:46:28]: the tool automatically for you. Have fun! 
[18:46:28]: Couldn't automatically detect the project file, please provide a path:

platforms/ios/FastlaneExample.xcodeproj
[18:46:32]: $ xcodebuild clean -showBuildSettings -project platforms/ios/FastlaneExample.xcodeproj
2017-08-30 18:46:35.893 xcodebuild[24417:190930] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-08-30 18:46:35.901 xcodebuild[24417:190930] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[18:46:37]: Your Apple ID (e.g. fastlane@krausefx.com): pi...ki@gmail.com
[18:46:42]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[18:46:42]: Starting login with user 'pi...ski@gmail.com'
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for pio...ski@gmail.com): ********
[18:46:55]: Ran into error while trying to connect to iTunes Connect / Dev Portal: `bundle_id` parameter must not be nil
[18:46:55]: Falling back to manual onboarding
[18:46:55]: `bundle_id` parameter must not be nil
[18:46:55]: An error occurred during the setup process. Falling back to manual setup!
[18:46:55]: App Identifier (com.krausefx.app): 
```

Continuing with the App Identifier everything works as it should, later it can even create the App ID in the developer console.

What is this `bundle_id` the error is talking about?

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1611)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.54.4"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "zo...ne" # The bundle identifier of your app
apple_id "pi....ki@gmail.com" # Your Apple email address

team_id "4Z...X3" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.4  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
</details>

*generated on:* **2017-08-30**
</details>

**Comment by ohayon** [comment]
Hey @janpio would you mind running this in verbose mode to get us some more context around the crash? Thanks!

**Comment by janpio** [comment]
I added `--verbose` to the command I ran:

```
Jans-MBP:fastlaneTest sujan$ fastlane init --verbose
[23:12:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-08-30 23:12:07.32]: Checking if there are any plugins that should be loaded...
WARN [2017-08-30 23:12:07.45]: Couldn't automatically detect the platform
 [2017-08-30 23:12:07.45]: Is this project an iOS project? (y/n)
y
INFO [2017-08-30 23:12:09.04]: This setup will help you get up and running in no time.
INFO [2017-08-30 23:12:09.04]: fastlane will check what tools you're already using and set up
INFO [2017-08-30 23:12:09.04]: the tool automatically for you. Have fun! 
 [2017-08-30 23:12:09.04]: Couldn't automatically detect the project file, please
provide a path: platforms/ios/FastlaneExample.xcodeproj
INFO [2017-08-30 23:12:23.09]: $ xcodebuild clean -showBuildSettings -project platforms/ios/FastlaneExample.xcodeproj
2017-08-30 23:12:23.450 xcodebuild[32793:250788] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-08-30 23:12:23.451 xcodebuild[32793:250788] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
 [2017-08-30 23:12:24.11]: Your Apple ID (e.g. fastlane@krausefx.com): pio...m
WARN [2017-08-30 23:12:33.09]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
INFO [2017-08-30 23:12:33.09]: Starting login with user 'pio...ail.com'
Loading session from '/Users/sujan/.fastlane/spaceship/pi....com/cookie'
INFO [2017-08-30 23:12:37.50]: Ran into error while trying to connect to iTunes Connect / Dev Portal: `bundle_id` parameter must not be nil
INFO [2017-08-30 23:12:37.50]: Falling back to manual onboarding
ERROR [2017-08-30 23:12:37.50]: `bundle_id` parameter must not be nil
ERROR [2017-08-30 23:12:37.50]: An error occurred during the setup process. Falling back to manual setup!
 [2017-08-30 23:12:37.55]: App Identifier (com.krausefx.app): 
```

Doesn't really look like much additional output. Did I miss anything?

**Comment by ohayon** [comment]
Nope, I don't think you missed anything... I took a closer look at the code and it looks like we might have a bug in there where we should be asking for your bundle ID, out of curiosity, could you confirm whether or not when you run ` xcodebuild -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER ` you have a bundle ID in that field? Thanks @janpio !! 🚀

**Comment by janpio** [comment]
I indeed don't seem to have one (iOS project is generated by Cordova and quite outdated, but generally still works):

```
Jans-MBP:ios sujan$ xcodebuild -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER
2017-08-31 16:58:56.941 xcodebuild[37645:310739] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-08-31 16:58:56.943 xcodebuild[37645:310739] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Jans-MBP:ios sujan$ 
```

(Without the `grep` it returns quite a lot of stuff, one of that being a `PRODUCT_NAME`for example)

What exactly *is* this bundle identifier anyway?
(I am not a real iOS developer or even Mac user...)

**Comment by ohayon** [comment]
Hey @janpio - ohh its great to know that you are using Cordova. The bundle identifier is just a unique string that gets used by the App Store to make sure that there are no collisions when installing apps with similar names. For example, I have an app in the app store with the bundle id: `com.thirty-one-parkton.PitaFace`, it's usually in reverse-domain name structure to help keep it unique. 🐙

**Comment by janpio** [comment]
Ok, so `bundle_id` will be `app_identifier` in my `Appfile` and is actually prompted after this failure as "App Identifier". Let me see if this is somewhere else in my Cordova .xcodeproj - I think it should be.

**Comment by janpio** [comment]
`xcodebuild -showBuildSettings` does indeed **not** return my package name at all. 
But Xcode does show it in the "Bundle Identifier" field in "General" and "Info -> Custom iOS Target Properties". 
Seems to come from my `*-Info.plist` where I found an entry:
```
   <key>CFBundleIdentifier</key>
    <string>org.example.name.package.my</string>
```

Is this different in current projects?

**Comment by janpio** [comment]
Ok, I confirmed how this works with a "normal" Xcode project:

```
Jans-MBP:BundleIdTest sujan$ fastlane
[19:48:25]: Seems like launching fastlane takes a while - please run
[19:48:25]: 
[19:48:25]: $ [sudo] gem cleanup
[19:48:25]: 
[19:48:25]: to uninstall outdated gems and make fastlane launch faster
[19:48:25]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[19:48:25]: To get started with a Gemfile, run
[19:48:25]: 
[19:48:25]: $ bundle init
[19:48:25]: $ echo 'gem "fastlane"' >> Gemfile
[19:48:25]: $ bundle install
[19:48:25]: 
[19:48:25]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[19:48:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:48:28]: Could not find fastlane in current directory. Make sure to have
your fastlane configuration files inside a folder called "fastlane". Would you like
to set fastlane up? (y/n)
y
[19:49:26]: Detected iOS/Mac project in current directory...
[19:49:26]: This setup will help you get up and running in no time.
[19:49:26]: fastlane will check what tools you're already using and set up
[19:49:26]: the tool automatically for you. Have fun! 
[19:49:26]: Created new folder './fastlane'.
[19:49:26]: $ xcodebuild clean -showBuildSettings -project ./BundleIdTest.xcodeproj
[19:49:28]: Your Apple ID (e.g. fastlane@krausefx.com): pi...m
[19:50:05]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[19:50:05]: Starting login with user 'pi...m'

+----------------+--------------------------------------+
|                    Detected Values                    |
+----------------+--------------------------------------+
| Apple ID       | pi...m                 |
| App Name       | BundleIdTest                         |
| App Identifier | de.janpiotrowski.BundleIdTest        |
| Project        | /Users/sujan/Documents/BundleIdTest  |
|                | /BundleIdTest.xcodeproj              |
+----------------+--------------------------------------+

[19:50:15]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[19:50:15]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
[19:50:15]: Please confirm the above values (y/n)
y
[19:50:56]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[19:50:56]: Creating the app on iTunes Connect and the Apple Developer Portal
[19:50:56]: $ xcodebuild clean -showBuildSettings -project ./BundleIdTest.xcodeproj

+----------------+-------------------------------+
|           Summary for produce 2.55.0           |
+----------------+-------------------------------+
| app_name       | BundleIdTest                  |
| app_identifier | de.janpiotrowski.BundleIdTest |
| username       | pi...m          |
| sku            | 15...57                    |
| platform       | ios                           |
| language       | English                       |
| skip_itc       | false                         |
| skip_devcenter | false                         |
| team_id        | 4...3                    |
+----------------+-------------------------------+

[19:51:00]: Creating new app 'BundleIdTest' on the Apple Dev Center
[19:51:02]: Created app 69...Y
[19:51:02]: Finished creating new app 'BundleIdTest' on the Dev Center
[19:51:07]: Creating new app 'BundleIdTest' on iTunes Connect
[...]
```

The `PRODUCT_BUNDLE_IDENTIFIER` also exists, so this is why it works:

```
Jans-MBP:BundleIdTest sujan$ xcodebuild -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER
    PRODUCT_BUNDLE_IDENTIFIER = de.janpiotrowski.BundleIdTest
```

So this is an edge case with Cordova projects.

A slightly better workflow would be if Fastlane checked for the `PRODUCT_BUNDLE_IDENTIFIER` earlier and added a simple prompt if it doesn't find it, but then continues as it does for a proper Xcode project.

(As this is with `fastlane init` I can't even write a plugin that just fixes the Cordova Xcode project because Fastfile etc doesn't even exist yet :/)

I will check if the bundle_id is present in some other way in the Cordova iOS project. It has to as Xcode itself shows the bundle_id.

**Comment by janpio** [comment]
Looked up where exactly this PRODUCT_BUNDLE_IDENTIFIER is actually stored:

```
Jans-MBP:BundleIdTest sujan$ grep -rni "de.janpiotrowski" *
BundleIdTest.xcodeproj/project.pbxproj:267:				PRODUCT_BUNDLE_IDENTIFIER = de.janpiotrowski.BundleIdTest;
BundleIdTest.xcodeproj/project.pbxproj:280:				PRODUCT_BUNDLE_IDENTIFIER = de.janpiotrowski.BundleIdTest;
```

which is

```
		6481FA3B1F606C3400DF5FCE /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				DEVELOPMENT_TEAM = 4Z338HBBX3;
				INFOPLIST_FILE = BundleIdTest/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				PRODUCT_BUNDLE_IDENTIFIER = de.janpiotrowski.BundleIdTest;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_VERSION = 3.0;
			};
			name = Debug;
		};
		6481FA3C1F606C3400DF5FCE /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				DEVELOPMENT_TEAM = 4Z338HBBX3;
				INFOPLIST_FILE = BundleIdTest/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				PRODUCT_BUNDLE_IDENTIFIER = de.janpiotrowski.BundleIdTest;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_VERSION = 3.0;
			};
			name = Release;
		};
```

**Comment by janpio** [comment]
So...

To make this work for Cordova projects `fastlane` could read `CFBundleIdentifier` from the `*-Info.plist` file (I know some other code already does similar things) as a fallback before throwing this error. Does this make sense?

**Comment by janpio** [comment]
Some background on the difference between those values:
https://stackoverflow.com/a/33122728/252627
(CFBundleIdentifier is old, PRODUCT_BUNDLE_IDENTIFIER is new and should be used)

**Comment by janpio** [comment]
Nah, want to get this working one day.
