### ISSUE TITLE
Spaceship - IAPList status returns nil when in "developerRemovedFromSale" status

### ISSUE THREAD

**Issue by gylee2011** [fastlane/fastlane#10206]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Here are log from Spaceship Playground
```
disabled_iap = iap.find("REDACTED")
=> <Spaceship::Tunes::IAPList
    application=<Spaceship::Tunes::Application
        apple_id="REDACTED",
        name="REDACTED",
        vendor_id="REDACTED",
        bundle_id="REDACTED",
        last_modified=1498800850000,
        issues_count=0,
        app_icon_preview_url="REDACTED",
        version_sets=[<Spaceship::Tunes::VersionSet
            type="APP",
            application=<Spaceship::Tunes::Application
            #<Object ...>>,
            platform="ios">]>,
    reference_name="REDACTED",
    product_id="REDACTED",
    family_reference_name=nil,
    duration_days=0,
    versions=[{"screenshotUrl"=>"REDACTED", "canSubmit"=>false, "issuesCount"=>0, "itunesConnectStatus"=>"developerRemovedFromSale"}],
    purple_apple_id=["REDACTED"],
    last_modfied_date=1500456859128,
    is_news_subscription=false,
    number_of_codes=0,
    maximum_number_of_codes=100,
    app_maximum_number_of_codes=1000,
    is_editable=false,
    is_required=false,
    can_delete_addon=true>
[5] pry(#<Spaceship::Playground>)> disabled_iap.status
=> nil
```
You can see `"developerRemovedFromSale"` in `versions`. (scroll to the right)

An Apple Developer document on [Working with Your Product's Pricing and Availability](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/WorkingWithYourProductsStatus.html) shows the list of In-app purchase product statuses.

But in [here](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/iap_status.rb), I found that only few of them are declared. "developerRemovedFromSale" status is not declared. I think that's because maybe the rest is not necessary in most cases, or just their actual values are not found yet.

I'm preparing a pull request for this.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.12.3                                                  |
| Ruby                        | 2.4.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.10.1 (Apple Git-78)                        |
| Installation Source         | ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.3 (16D32)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 8.2.1                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ko_KR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs

desc "Runs the unit tests and other verifications for the fastlane repo"
lane :test do |options|
  validate_repo
end

desc "Increment the version number of this gem"
lane :bump do |options|
  ensure_git_branch(branch: "master")
  ensure_git_status_clean

  github_api_token = ENV["FL_GITHUB_RELEASE_API_TOKEN"]
  UI.user_error!("Please provide a GitHub API token using `FL_GITHUB_RELEASE_API_TOKEN`") if github_api_token.to_s.length == 0

  path = "./fastlane/lib/fastlane/version.rb"

  # Verify everything is in a consistent state
  latest_version = current_version
  local_version = version_get_podspec(path: path)
  UI.user_error!("Version on RubyGems doesn't match local repo: #{latest_version} != #{local_version}") if latest_version != local_version

  changelog_text = show_changelog

  bump_type ||= 'minor' if prompt(text: "New feature, method or API?", boolean: true)
  bump_type ||= 'patch'

  slug = "fastlane/fastlane"
  new_version = version_bump_podspec(path: path, bump_type: bump_type)
  sh "git checkout -b 'version-bump-#{new_version}'"
  commit_message = "Version bump to #{new_version}"
  git_commit(path: path,
             message: commit_message)
  push_to_git_remote

  pr_body = ["Auto-generated by fastlane 🤖"]
  pr_body << "**Changes since release '#{latest_version}':**"
  pr_body << changelog_text
  pr_url = create_pull_request(
    api_token: github_api_token,
    repo: slug,
    title: commit_message,
    body: pr_body.join("\n\n")
  )

  if ENV['SLACK_URL']
    slack(
      channel: "action",
      default_payloads: [],
      message: "Version bump: #{pr_url} ✨",
      payload: {}
    )
  end

  # Revert to master branch
  sh "git checkout master"
end

desc "Does everything that's needed for a release"
desc "This includes running tests and verifying the GitHub release"
lane :release do
  slack_train_start(distance: 2,
                       train: "🚀",
           reverse_direction: true,
                        rail: "✨")

  update_fastlane
  slack_train

  # Git verification
  #
  ensure_git_status_clean
  ensure_git_branch(branch: 'master')
  git_pull

  validate_repo

  # Verifying RubyGems version
  #
  require "../fastlane/lib/fastlane/version.rb"
  version = Fastlane::VERSION
  old_version = current_version
  puts "Deploying #{version}"
  if Gem::Version.new(version) <= Gem::Version.new(old_version)
    UI.user_error!("Version number #{version} was already deployed")
  end

  # Then push to git remote
  #
  push_to_git_remote

  # Preparing GitHub Release
  #
  github_release = get_github_release(url: "fastlane/fastlane", version: version)
  if (github_release || {}).fetch('body', '').length == 0
    show_changelog(old_version: old_version)

    title = prompt(text: 'Title: ')
    description = prompt(text: "Please enter a changelog (make sure to rephrase changes to make it easy to understand, and remove non-important changes that don't affect the end-user): ",
                         multi_line_end_keyword: "END")

    github_release = set_github_release(
      repository_name: "fastlane/fastlane",
      name: [version, title].join(" "),
      tag_name: version,
      description: description,
      is_draft: false
    )

    # Actual release of the gem
    #
    sh "gem push ../pkg/fastlane-#{version}.gem"

    release_url = github_release['html_url']

    message = [title, description, release_url].join("\n\n")
    add_fastlane_git_tag(tag: "fastlane/#{version}", message: message)
  end

  # After publishing
  #
  if ENV['SLACK_URL']
    release_notes = github_release['body']
    # markup - turn github references into links
    release_notes.gsub!(/\(#([0-9]+)\)/, '(<https://github.com/fastlane/fastlane/issues/\1|#\1>)')
    slack_message = "Successfully released [fastlane #{version}](#{release_url}) :rocket:"
    slack(
      channel: "releases",
      default_payloads: [],
      message: slack_message,
      payload: {
        "New" => release_notes
      }
    )
    slack(channel: "action", default_payloads: [], message: slack_message)
  end

  clubmate

  puts "You can now tweet:".green
  releases_url = "https://github.com/fastlane/fastlane/releases/tag/#{version}"
  puts "[fastlane] #{github_release['name']} #{releases_url}"

  send_mac_app_ci_reminder

  update_docs
  slack_train
end

desc "Makes sure the tests on https://docs.fastlane.tools still work with the latest version"
lane :verify_docs do
  clone_docs do
    Bundler.with_clean_env do
      puts `sed -i -e "s/activate_bin_path/bin_path/g" $(which bundle)` # workaround for bundler https://github.com/bundler/bundler/issues/4602#issuecomment-233619696
      sh "bundle install"
      sh "bundle exec fastlane test skip_building:true" # skip_building since we don't have a proper python environment set up
    end
  end
end

desc "Generates the actions.md that will get used on https://docs.fastlane.tools"
desc "This will NOT also automatically submit a pull request to fastlane/docs"
desc "This SHOULD only be used for testing changes to the docs"
lane :test_generate_docs do
  ENV['USE_ENHANCE_TEST_DATA'] = "true"
  generate_markdown_docs
  ENV.delete("USE_ENHANCE_TEST_DATA")
end

desc "Update the actions.md on https://docs.fastlane.tools"
desc "This will also automatically submit a pull request to fastlane/docs"
lane :update_docs do
  verify_env_variables

  template_path = File.expand_path("./assets/render_plugin.md.erb")
  clone_docs do
    actions_md_path = generate_markdown_docs

    Bundler.with_clean_env do
      sh "bundle update"
    end

    if `git status --porcelain`.length == 0
      UI.success("No changes in the actions.md ✅")
    else
      # Create a new branch
      sh "git checkout -b 'update-actions-md-#{Time.now.to_i}'"
      plugins_path = "docs/plugins/available-plugins.md"
      plugin_scores(template_path: template_path,
                      output_path: plugins_path)

      Dir.chdir("fastlane") do # this is an assumption of fastlane, that we have to .. when shelling out
        # Commit the changes
        git_commit(path: [actions_md_path, "Gemfile.lock", plugins_path],
                message: "Update actions.md for latest fastlane release 🚀")
        # Push them to the git remote
        push_to_git_remote

        # Submit the pull request
        pr_url = create_pull_request(
          api_token: ENV["FL_GITHUB_RELEASE_API_TOKEN"],
          repo: "fastlane/docs",
          title: "[Bot] Update actions.md for latest fastlane release 🚀",
          body: "Auto-generated by _fastlane_ bot 🤖"
        )
        UI.success("Successfully submitted a pull request to fastlane/docs: #{pr_url} 🚀")
      end
    end
  end
end

def generate_markdown_docs
  require 'fastlane/documentation/markdown_docs_generator'
  actions_md_path = File.expand_path("docs/actions.md")
  Fastlane::MarkdownDocsGenerator.new.generate!(target_path: actions_md_path)

  return actions_md_path
end

def clone_docs
  require 'tmpdir'
  git_url = ENV['FASTLANE_DOCS_GIT_URL'] || "https://github.com/fastlane/docs"

  Dir.mktmpdir("fl_clone") do |tmp_dir|
    Dir.chdir(tmp_dir) do
      sh "git clone #{git_url} --depth=1"
      Dir.chdir("docs") do
        yield
      end
    end
  end
end

error do |lane, exception|
  if ENV['SLACK_URL']
    slack(channel: "testing", message: exception.to_s, success: false)
  end
  slack_train_crash
end

private_lane :send_mac_app_ci_reminder do
  if ENV['FABRIC_SLACK_URL']
    slack(
      slack_url: ENV['FABRIC_SLACK_URL'],
      channel: 'deployment-tools',
      default_payloads: [],
      message: "Please run the Fastlane Mac App Package CI job in TeamCity\n#{ENV['FABRIC_MAC_APP_CI_JOB_URL']}"
    )
  end
end

desc "Verifies all tests pass and the current state of the repo is valid"
private_lane :validate_repo do
  # Verifying that no debug code is in the code base
  #
  ensure_no_debug_code(text: "binding.pry", extension: ".rb", exclude: "playground.rb", exclude_dirs: ["\.bundle"]) # debugging code
  ensure_no_debug_code(text: "# TODO", extension: ".rb", exclude_dirs: ["\.bundle"]) # TODOs
  ensure_no_debug_code(text: "now: ", extension: ".rb", exclude_dirs: ["\.bundle"]) # rspec focus
  ensure_no_debug_code(text: "<<<<<<<", extension: ".rb", exclude_dirs: ["\.bundle"]) # Merge conflict

  # spaceship and credentials_manager don't have access to fastlane_core
  ensure_no_debug_code(text: " UI\\.", path: "spaceship/lib", extension: ".rb", exclude_dirs: ["\.bundle"])
  ensure_no_debug_code(text: " UI\\.", path: "credentials_manager/lib", extension: ".rb", exclude_dirs: ["\.bundle"])

  rubocop

  # Verifying the --help command
  #
  # tools_to_test = Fastlane::TOOLS
  tools_to_test = [:fastlane] # until we have the binaries for all tools included here
  tools_to_test.each do |tool_name|
    next if no_binary.include?(tool_name)
    Dir.chdir("..") do
      binary_path = File.join("bin", tool_name.to_s)
      content = sh("PAGER=cat #{binary_path} --help")
      ["--version", "https://fastlane.tools", tool_name.to_s].each do |current|
        UI.user_error!("--help missing information: '#{current}'") unless content.include?(current)
      end
    end
  end

  Dir.chdir("..") do
    # Install the bundle and the actual gem
    sh "bundle check || bundle install"
    sh "rake install"

    # Run the tests
    #
    sh "bundle exec rake test_all"

    # Verify shell code style
    sh 'find -E . -regex ".*\.(sh|bash)" -not -name "Pods-*" -name ".bundle" -exec shellcheck {} +'
  end

  test_generate_docs
  ensure_code_samples

  # Verify docs are still working
  verify_docs
end

desc "Get the version number of the last release"
private_lane :current_version do
  puts "Checking the latest version on RubyGems"
  download(url: "https://rubygems.org/api/v1/gems/fastlane.json")["version"]
end

desc "All repos that don't have a binary to test"
private_lane :no_binary do
  ['fastlane_core', 'spaceship', 'credentials_manager']
end

desc "Print out the changelog since the last tagged release and open the GitHub page with the changes"
lane :show_changelog do |options|
  old_version = options[:old_version] || current_version

  changes = sh("git log --pretty='* %s via %aN' #{old_version}...HEAD --no-merges ..", log: $verbose).gsub("\n\n", "\n")
  changes.gsub!("[WIP]", "") # sometimes a [WIP] is merged

  github_diff_url = "https://github.com/fastlane/fastlane/compare/#{old_version}...master"
  sh "open #{github_diff_url}"

  puts "Changes since release #{old_version}:\n\n#{changes.cyan}"
  changes # return the text without the modified colors
end

desc "Add a git tag in the fastlane repo for this release"
private_lane :add_fastlane_git_tag do |options|
  `git tag -am #{options[:message].shellescape} #{options[:tag].shellescape}`
  push_git_tags
end

# Run the code samples, yo
private_lane :ensure_code_samples do
  UI.message "<U+1F557>  Verifying all code samples work with the latest fastlane release"
  test_sample_code(path: File.expand_path("docs/Actions.md"))
  UI.success "<U+2705>  All fastlane code samples work as expected"
end

desc "Ensure all the requirement environment variables are provided"
desc "this way the deployment script will fail early (and often)"
private_lane :verify_env_variables do
  ["GITHUB_USER_NAME", "GITHUB_API_TOKEN"].each do |variable|
    next if ENV[variable].to_s.length > 0
    UI.user_error!("Missing ENV variables #{variable}, make sure to provide one for fastlane to be successful")
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.4  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-ruby        | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-clubmate    | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-slack_train | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.1.0        |
| bundler                     | 1.15.3       |
| io-console                  | 0.4.6        |
| rake                        | 11.3.0       |
| CFPropertyList              | 2.3.5        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.5.2        |
| ast                         | 2.3.0        |
| babosa                      | 1.0.2        |
| debug_inspector             | 0.0.3        |
| binding_of_caller           | 0.7.2        |
| builder                     | 3.2.3        |
| byebug                      | 9.1.0        |
| claide                      | 1.0.2        |
| colored2                    | 3.1.2        |
| cork                        | 0.3.0        |
| nap                         | 1.1.0        |
| open4                       | 1.3.4        |
| claide-plugins              | 0.9.2        |
| coderay                     | 1.1.1        |
| colored                     | 1.2          |
| highline                    | 1.7.8        |
| commander-fastlane          | 4.4.5        |
| json                        | 2.1.0        |
| docile                      | 1.1.5        |
| simplecov-html              | 0.10.2       |
| simplecov                   | 0.14.1       |
| tins                        | 1.15.0       |
| term-ansicolor              | 1.6.0        |
| thor                        | 0.19.4       |
| coveralls                   | 0.8.21       |
| safe_yaml                   | 1.0.4        |
| crack                       | 0.4.3        |
| multipart-post              | 2.0.0        |
| faraday                     | 0.13.1       |
| faraday-http-cache          | 1.3.1        |
| git                         | 1.3.0        |
| kramdown                    | 1.14.0       |
| sawyer                      | 0.8.1        |
| octokit                     | 4.7.0        |
| unicode-display_width       | 1.3.0        |
| terminal-table              | 1.8.0        |
| danger                      | 4.3.5        |
| ox                          | 2.6.0        |
| danger-junit                | 0.7.3        |
| declarative                 | 0.0.9        |
| declarative-option          | 0.1.0        |
| diff-lcs                    | 1.3          |
| unf_ext                     | 0.0.7.4      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20170404 |
| dotenv                      | 2.2.1        |
| excon                       | 0.58.0       |
| fakefs                      | 0.8.1        |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.12.2       |
| fastimage                   | 2.1.0        |
| gh_inspector                | 1.0.3        |
| jwt                         | 1.5.6        |
| little-plugger              | 1.1.4        |
| multi_json                  | 1.12.1       |
| logging                     | 2.2.2        |
| memoist                     | 0.16.0       |
| os                          | 0.9.6        |
| signet                      | 0.7.3        |
| googleauth                  | 0.5.3        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2016.0521  |
| mime-types                  | 3.1          |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.1        |
| google-api-client           | 0.13.4       |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.3.0        |
| rubyzip                     | 1.2.1        |
| security                    | 0.1.3        |
| slack-notifier              | 1.5.1        |
| terminal-notifier           | 1.8.0        |
| tty-screen                  | 0.5.0        |
| word_wrap                   | 1.0.0        |
| nanaimo                     | 0.2.3        |
| xcodeproj                   | 1.5.1        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.2.8        |
| xcpretty-travis-formatter   | 0.0.4        |
| fastlane-plugin-clubmate    | 0.1.0        |
| fastlane-plugin-ruby        | 0.1.3        |
| fastlane-plugin-slack_train | 0.2.0        |
| hashdiff                    | 0.3.6        |
| interception                | 0.5          |
| method_source               | 0.8.2        |
| netrc                       | 0.11.0       |
| parallel                    | 1.12.0       |
| parser                      | 2.4.0.0      |
| powerpack                   | 0.1.1        |
| slop                        | 3.6.0        |
| pry                         | 0.10.4       |
| pry-byebug                  | 3.5.0        |
| pry-rescue                  | 1.4.5        |
| pry-stack_explorer          | 0.4.9.2      |
| rack                        | 1.6.8        |
| rack-protection             | 1.5.3        |
| rainbow                     | 2.2.2        |
| rb-readline                 | 0.5.5        |
| rest-client                 | 2.0.2        |
| rspec-support               | 3.5.0        |
| rspec-core                  | 3.5.4        |
| rspec-expectations          | 3.5.0        |
| rspec-mocks                 | 3.5.0        |
| rspec                       | 3.5.0        |
| rspec_junit_formatter       | 0.2.3        |
| ruby-progressbar            | 1.8.1        |
| rubocop                     | 0.49.1       |
| tilt                        | 2.0.8        |
| sinatra                     | 1.4.8        |
| webmock                     | 2.3.2        |
| xcode-install               | 2.2.1        |
| yard                        | 0.8.7.6      |
</details>

*generated on:* **2017-08-31**
</details>

**Comment by luongm** [comment]
Please also add "Developer Action Needed" to the list.
Also, it would be great if IAPStatus does not return nil for any status from Apple that it doesn't recognize. It should return the raw status text from Apple in this case.

**Comment by gylee2011** [comment]
@luongm I am not sure what exactly iTunes Connect sends as a response for `Developer Action Needed` status; it could possibly be `developerActionNeeded`, but I don't know. I haven't encountered such situation since I used Spaceship.

I agree that it would be good and useful if IAPStatus returns raw text instead of nil. However, if we allow IAPStatus to return an arbitrary string, instead of predefined strings, I think codes that use those strings would be broken if Apple changes the strings for some reason.

Btw, I forgot to write `close #10206` in my pull request (#10224) and now I close this issue.

**Comment by luongm** [comment]
I unfortunately did not capture what the status was when one of my IAP was marked like that. Now I don't have an IAP with developer action needed anymore, so I guess I'll update this or create a new issue later when Apple marks one again.
