### ISSUE TITLE
 Operation timed out - connect(2) for "kits-crashlytics-com.s3.amazonaws.com" port 443

### ISSUE THREAD

**Issue by iamsarathi** [fastlane/fastlane#10208]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm getting below warning in one machine whereas in my other machines it successfully builds.

When ever I excutes fastlane it hang for sometime and print this error ony in this machine. Whereas in other machine its not.

### Output

**KR30AFF693:crewmobile-ios 1324$ fastlane beta --capture_output**

/Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Operation timed out - connect(2) for "kits-crashlytics-com.s3.amazonaws.com" port 443 (Errno::ETIMEDOUT)
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:583:in `start'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:478:in `get_response'
	from /Users/1324/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:455:in `get'
	from /Users/1324/.fastlane/bin/bundle_update_checker.rb:5:in `<main>'
..........
...........
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/x3/8xl14w213hj4gnp3yyppftmjmd3pc4/T/gym_config20170830-92413-1y9592h.plist -archivePath '/Users/1324/Library/Developer/Xcode/Archives/2017-08-30/CrewMobile 2017-08-30 14.04.03.xcarchive' -exportPath /var/folders/x3/8xl14w213hj4gnp3yyppftmjmd3pc4/T/gym_output20170830-92413-1aegat6
2017-08-30 14:05:42.028 xcodebuild[93566:1468870] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/x3/8xl14w213hj4gnp3yyppftmjmd3pc4/T/CrewMobile_2017-08-30_14-05-42.028.xcdistributionlogs'.
2017-08-30 14:05:42.275 xcodebuild[93566:1468870] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7f8a93d8e900>: Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}
error: exportArchive: No 'teamID' specified and no team ID found in the archive

Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}

** EXPORT FAILED **

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/1324/crewmobile-ios/fastlane/Appfile'
- apple_id: 'uiconsulting@sabre.com'
-------

+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.54.4                            |
+--------------------------------------+--------------------------------------+
| export_method                        | enterprise                           |
| scheme                               | CrewMobile                           |
| configuration                        | Cert                                 |
| workspace                            | ./CrewMobile.xcworkspace             |
| export_options.provisioningProfiles  | Crew Mobile Dist                     |
| .com.sabre.aspd.crewmobile           |                                      |
| destination                          | generic/platform=iOS                 |
| output_name                          | CrewMobile                           |
| build_path                           | /Users/1324/Library/Developer/  |
|                                      | Xcode/Archives/2017-08-30            |
| clean                                | false                                |
| output_directory                     | .                                    |
| silent                               | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| xcode_path                           | /Applications/Xcode.app              |
+--------------------------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -workspace ./CrewMobile.xcworkspace  |                      |
| -scheme CrewMobile                   |                      |
| -configuration Cert                  |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/1324/Library/Developer/  |                      |
| Xcode/Archives/2017-08-30/CrewMobil  |                      |
| e\ 2017-08-30\ 14.04.03.xcarchive    |                      |
| archive                              |                      |
| | tee                                 |                      |
| /Users/1324/Library/Logs/gym/C  |                      |
| rewMobile-CrewMobile.log             |                      |
| | xcpretty                            |                      |
+--------------------------------------+----------------------+
+--------------------------------------+--------------------------------------+
|                          Generated Package Command                          |
+--------------------------------------+--------------------------------------+
| Option                               | Value                                |
+--------------------------------------+--------------------------------------+
| /usr/bin/xcrun                       |                                      |
| /Users/1324/.fastlane/bin/bund  |                                      |
| le/lib/ruby/gems/2.2.0/gems/fastlan  |                                      |
| e-2.54.4/gym/lib/assets/wrap_xcodeb  |                                      |
| uild/xcbuild-safe.sh -exportArchive  |                                      |
| -exportOptionsPlist                  | /var/folders/x3/8xl14w213hj4gnp3yyp  |
|                                      | pftmjmd3pc4/T/gym_config20170830-92  |
|                                      | 413-1y9592h.plist                    |
| -archivePath                         |                                      |
| /Users/1324/Library/Developer/  |                                      |
| Xcode/Archives/2017-08-30/CrewMobil  |                                      |
| e\ 2017-08-30\ 14.04.03.xcarchive    |                                      |
| -exportPath                          | /var/folders/x3/8xl14w213hj4gnp3yyp  |
|                                      | pftmjmd3pc4/T/gym_output20170830-92  |
|                                      | 413-1aegat6                          |
+--------------------------------------+--------------------------------------+
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/x3/8xl14w213hj4gnp3yyppftmjmd3pc4/T/gym_config20170830-92413-1y9592h.plist -archivePath '/Users/1324/Library/Developer/Xcode/Archives/2017-08-30/CrewMobile 2017-08-30 14.04.03.xcarchive' -exportPath /var/folders/x3/8xl14w213hj4gnp3yyppftmjmd3pc4/T/gym_output20170830-92413-1aegat6
2017-08-30 14:05:42.028 xcodebuild[93566:1468870] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/x3/8xl14w213hj4gnp3yyppftmjmd3pc4/T/CrewMobile_2017-08-30_14-05-42.028.xcdistributionlogs'.
2017-08-30 14:05:42.275 xcodebuild[93566:1468870] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7f8a93d8e900>: Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}
error: exportArchive: No 'teamID' specified and no team ID found in the archive

Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}

** EXPORT FAILED **

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.54.4                  |
| export_method | enterprise              |
| sdk           | iPhoneOS10.2.sdk        |
+---------------+-------------------------+


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | cocoapods           | 4           |
| 💥    | gym                 | 101         |
+------+---------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.4  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2017-08-30**
</details>

**Comment by iamsarathi** [comment]
But I dont know why this is failing only in particular machine.

**Comment by iamsarathi** [comment]
I have also tried `https://docs.fastlane.tools/codesigning/getting-started/#using-xcodes-code-signing-feature` but getting same error

**Comment by ohayon** [comment]
Hmmm - @iamsarathi thanks for submitting the issue! Is it possible that your Xcode project does not have a teamID set in the project settings? Would you mind taking a look at that. It looks like that is why the export to ipa may have failed. 🐙

**Comment by iamsarathi** [comment]
adding `export_team_id: ` in fastlane file worked. Many Thanks @ohayon
