### ISSUE TITLE
Creating Pass Type ID Certificate

### ISSUE THREAD

**Issue by proorlov** [fastlane/fastlane#10200]
Hello!

I have created Pass Type ID and it has successfully created:

```
passbook = Spaceship::Portal.passbook.create!(bundle_id: 'pass.com.my.pb', name: 'Fastlane Passbook')
```

Now I try to create Pass Type ID Certificate:

```
[1] pry(#<Spaceship::Playground>)> csr, pkey = Spaceship.certificate.create_certificate_signing_request
=> [#<OpenSSL::X509::Request:0x007f8885868890>, #<OpenSSL::PKey::RSA:0x007f88858689a8>]

[2] pry(#<Spaceship::Playground>)> Spaceship.certificate.passbook.create!(csr: csr, bundle_id: "pass.com.my.pb")
RuntimeError: Could not find app with bundle id 'pass.com.my.pb'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.4/spaceship/lib/spaceship/portal/certificate.rb:291:in `create!'
```
And it failed. It search for app not for passbook.
What do i wrong and how I should create Pass Type ID Certificate?
Thank you!

##### Complete output when running fastlane

```
mac:Develop user$ fastlane spaceship
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[19:57:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
WARN: Unresolved specs during Gem::Specification.reset:
      terminal-table (< 2.0.0, >= 1.4.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Username: xxx@gmail.com
Logging into to iTunes Connect (xxx@gmail.com)...
Successfully logged in to iTunes Connect

Logging into the Developer Portal (xxx@gmail.com)...
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter
[1] pry(#<Spaceship::Playground>)> 
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.4  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
</details>

*generated on:* **2017-08-30**
</details>

**Comment by ohayon** [comment]
Hey @proorlov, apologies for the issues your seeing. Do you think you could put this into a little script, or Rakefile or Fastfile to execute it so that we can see the stack trace that happens. It would help figure out exactly whats going wrong if we had some more context! 🚀

**Comment by proorlov** [comment]
Hey @ohayon, sure.
[script](https://github.com/fastlane/fastlane/files/1264190/run.txt)

**Comment by ohayon** [comment]
And could you share the full output of running that script?

**Comment by proorlov** [comment]
script with my Apple login & pass:
```
mac:Develop user$ ruby run.rb 
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.4/spaceship/lib/spaceship/portal/certificate.rb:291:in `create!': Could not find app with bundle id 'pass.com.my.pb1' (RuntimeError)
	from run.rb:5:in `<main>'
```

**Comment by ohayon** [comment]
Hmmm. Okay, I was hoping there would be a bit more information printing out haha. So one question for you: that bundle ID `pass.com.my.pb1` is that the bundle ID of the app you are using?

**Comment by proorlov** [comment]
If I understand you correctly - I don't create application for iOS. I create [Wallet Passes](https://developer.apple.com/wallet/). And for creating *.pkpass file I need before register Pass Type Id and then make Pass Type ID Certificate.

And sure, i use `pass.com.my.pb1`:

[creating Pass Type ID using fastlane success](https://user-images.githubusercontent.com/3322730/29882216-c611c026-8dc5-11e7-803c-9c93d927fff6.png)

[need to create certificate](https://user-images.githubusercontent.com/3322730/29882249-dccbb52e-8dc5-11e7-86e1-758f6c5c5271.png)

**Comment by proorlov** [comment]
@ohayon do you understand me and my task?
Is there problem in source code or i do something wrong?
Thank you!

**Comment by ohayon** [comment]
I'm not totally sure I understand the situation, but could you try passing the app's bundle ID? That is what the code is expecting, but there could be an issue with that too..

**Comment by proorlov** [comment]
I don't have app and app's bundle ID. I don't need create iOS app development certificate.
How I should create "Pass Type ID Certificate" using existing "Pass Type ID"?

**Comment by scottire** [comment]
Were you able to get any success with this? Looking to generate Pass Type ID Certificate using fastlane too

**Comment by proorlov** [comment]
No. Looking for solution for automated creating Pass Type ID Certificate.

**Comment by scottire** [comment]
It seems the bundle_id string is just for push profiles.
[Docs](http://www.rubydoc.info/github/fastlane/spaceship/Spaceship/Certificate#create_certificate_signing_request-class_method)
`bundle_id (String) — (optional): The app identifier this certificate is for. This value is only needed if you create a push profile. For normal code signing certificates, you must only pass a certificate signing request.`
It doesn't look like it's possible to create a certificate from a Pass Type ID using Spaceship just yet.

**Comment by ohayon** [comment]
Yeah, I believe @scottire is right here. Apologies for misunderstanding the issue a while back. We do not currently support Pass Type IDs in spaceship at the moment but we would definitely love to review a PR with that addition. Let us know if you would want to submit one! 🐙

**Comment by scottire** [comment]
I was able to get it done with a script but am not comfortable enough with ruby to be confident with a PR.
Here is the code 
```
require 'spaceship'
Spaceship::Portal.login("felix@krausefx.com", "password")
id = "pass.com.fastlane.automated"
passbook = Spaceship::Portal.passbook.create!(bundle_id: id, name: 'Fastlane Passbook')
# passbook = Spaceship::Portal.passbook.find(id)
csr, pkey = Spaceship::Portal.certificate.create_certificate_signing_request
csr = OpenSSL::X509::Request.new(csr) if csr.kind_of?(String)
r = Spaceship::Portal.client.request(:post, "account/ios/certificate/submitCertificateRequest.action", {
    teamId: "XXXXXXXX",
    type: "S5WE21TULA",
    csrContent: csr.to_pem,
    passTypeId: passbook.passbook_id, # optional
    specialIdentifierDisplayId: passbook.passbook_id
  })
Spaceship::Portal.client.parse_response(r, 'certRequest')
```
That generates the Pass Type ID Certificate.

**Comment by proorlov** [comment]
@scottire cool! But i create it using type: "Y3B2F3TYSI" (not S5WE21TULA).

**Comment by scottire** [comment]
Did it work when changing the type, I can't recreate this with my iTunes Connect account?

**Comment by proorlov** [comment]
Don't know. I don't use iTunes Connect account. I use Apple Developer account.

**Comment by scottire** [comment]
Sorry that's what I meant. What happens if you run the above code with a changed `type`?

**Comment by proorlov** [comment]
Error in console that wrong type of certificate.

**Comment by scottire** [comment]
Does it work if you use the one above? S5WE21TULA
I am using it to generate a pass passes that contain an Enhanced Passbook/NFC certificate. 
You can try using Google Developer tools to view the network traffic when manually using https://developer.apple.com/account/ios/certificate/create and when you see submitCertificateRequest.action, view the Form Data and see the params, then edit the request above with those params and type. Sorry I can't be of more help to generate a pass with a default certificate.

**Comment by proorlov** [comment]
@scottire thnx!

**Comment by proorlov** [comment]
Hi @scottire Have you idea how to download *.p12 certificate after creating?

**Comment by kmcrawford** [comment]
I wish PEM supported this. They are very similar functions.
