### ISSUE TITLE
[produce] Define `app_name` in `Appfile`?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10205]
When I run `fastlane produce` with a default `Appfile` it prompts me for the `app_name` and informs me that I could supply it to not be prompted:

```
Jans-MBP:fastlaneTest sujan$ fastlane produce
[19:15:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+----------------------+
|      Summary for produce 2.54.4       |
+----------------+----------------------+
| username       | pi...m |
| app_identifier | z...e  |
| sku            | 15...6           |
| platform       | ios                  |
| language       | English              |
| skip_itc       | false                |
| skip_devcenter | false                |
| team_id        | 4Z...BX3           |
+----------------+----------------------+

[19:15:40]: To not be asked about this value, you can specify it using 'app_name'
[19:15:40]: App Name: 
```

But when I try to set it in `Appfile` I get this error and it can't read any values from there:

```
Jans-MBP:fastlaneTest sujan$ fastlane produce
[19:18:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
undefined method `app_name' for #<CredentialsManager::AppfileConfig:0x007f8ce3a516e0>
[...]
undefined method `app_name' for #<CredentialsManager::AppfileConfig:0x007f8ce22b1328>

+----------------+------------+
| Summary for produce 2.54.4  |
+----------------+------------+
| sku            | 15...86 |
| platform       | ios        |
| language       | English    |
| skip_itc       | false      |
| skip_devcenter | false      |
+----------------+------------+

[19:18:06]: To not be asked about this value, you can specify it using 'username'
[19:18:06]: Your Apple ID Username:
```

Seems this can only be supplied as a command line parameter.

Is there a way to set `app_name` for `fastlane produce` in `Appfile` or another file?

(As I need the app name in my custom lanes as well it would be great to be able to get it with `CredentialsManager::AppfileConfig.try_fetch_value(:app_name)` from `Appfile`)

**fastlane env**

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1611)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.54.4"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "zo...ne" # The bundle identifier of your app
apple_id "pio...com" # Your Apple email address
team_id "4Z...X3" # Developer Portal Team ID

json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "zo...ne" # e.g. com.krausefx.app

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.4  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
</details>

*generated on:* **2017-08-30**
</details>

**Comment by ohayon** [comment]
Hey @janpio could you try adding `app_name "Your App Name"` to your Appfile and see if that works? 🚀

**Comment by janpio** [comment]
Sorry, seems I forgot that part in my initial issue: This is exactly what I did to get the second output with `undefined method `app_name' ...`. I got this when I defined an `app_name` in my `Fastfile`.

**Comment by ohayon** [comment]
Ah, my bad @janpio, I think for now the best way to do this is to put your call to `produce` in a Fastfile and you can pass it to that call like so: 
```
produce(app_name: "Your App Name")
```
Or, alternatively you could pass it on the command line like: `fastlane produce -q "Your App Name"` 🐙

**Comment by janpio** [comment]
Ok.

But you agree this would be a useful feature for `produce` and also other parts to be able to define this in `Appfile`? (Maybe someone *caugh*me?*cough* can cobble this together... [without even knowing ruby])

**Comment by ohayon** [comment]
Hahahaha yes, definitely it should be readable from the Appfile or somewhere else. We will make sure we get that change in at some point soon! 😄

**Comment by janpio** [comment]
Nah @fastlane-bot, I want to get this fixed on day.
