### ISSUE TITLE
Sigh fails with "undefined method `strip' for nil:NilClass" when there are multiple schemes in the project while no scheme is specified in the lane

### ISSUE THREAD

**Issue by marmoy** [fastlane/fastlane#1021]
I experienced this error in a project using cocoapods, which results in a lot of schemes for the project. I did not specify a scheme when setting up fastlane for the project. When the lane is run, the console asks which scheme to use (can't specify that through the console, because I'm running fastlane through jenkins) and then immediately proceeds with a variable dump for sigh, followed by the error message "undefined method `strip' for nil:NilClass". 

It would be great if sigh could recognise that the problem comes from the scheme not having been set, and then tell the user explicitly, rather than using the confusing error message above.

This is for sigh 1.2.1

**Comment by KrauseFx** [comment]
Could you post your configuration files, the complete output and its stack trace?

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
