### ISSUE TITLE
[Question] Android supply automatic release

### ISSUE THREAD

**Issue by vspac** [fastlane/fastlane#10213]
Hi guys,

Can someone confirm that you cannot release an **ANDROID** app using fastlane `supply` but you have to manually click the **Review** button from the desired track? I have looked into the android publisher API and indeed there is no support for this, but I'm thinking maybe you guys found another way to do it.

Also, is there a way to retrieve the app status (Approved, rejected, etc)?

Thanks.

**Comment by janpio** [comment]
As far as I know `supply` only uses Google's Ruby API which, as you said, doesn't support this.
