### ISSUE TITLE
Incorrect error message when updating provisioning profile that does not have a distribution certificate connected to it

### ISSUE THREAD

**Issue by mikkeljuhl** [fastlane/fastlane#10229]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If I have 1 provisioning profile and 2 distribution certificates (1st certificate is created 8AM and 2nd is created 9AM). The provisioning profile is connected to the 1st distribution certificate. If the first certificate is deleted, then the provisioning profile renders invalid. If you then try, using Spaceship, to add a new device to the provisioning profile and update the provisioning profile then Spaceship complains: Exception: Class: RuntimeError Message: 'Please login using `Spaceship::Portal.login('user', 'password')`' Notice that we are logged in however, it seems like we should get another error message.

Perhaps this is because [Spaceship optimistically picks the first available certificate](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/provisioning_profile.rb#L453), which will be the 2nd certificate created.

### Output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

**State of Apple Developer Portal**: 2 Distribution certificates. 1 provisioning profile (connected with the first distribution certificate). 1 unprovisioned device to be registered in the provisioning profile. 

The sequence to reproduce looks something like this (simplified of course):

```ruby 

profileName = "Some Provisioning Profile Name"
new_device = {name: "name", udid: "..."}

@spaceship = Spaceship::Launcher.new
@spaceship.login(username, password)
profile = @spaceship.provisioning_profile.all.detect{ |item| item.name == profileName }
device = @spaceship.device.create!(name: new_device[:name], udid: new_device[:udid])
profile.devices.push(device)
profile.update!
```

#### Stacktrace: 

```
Exception: Class: RuntimeError Message: 'Please login using `Spaceship::Portal.login('user', 'password')`' 
/Users/mikkeljuhl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/spaceship/lib/spaceship/portal/portal_base.rb:8:in `client'
/Users/mikkeljuhl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/spaceship/lib/spaceship/portal/certificate.rb:258:in `all'
/Users/mikkeljuhl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:453:in `update!'
```

**Comment by KrauseFx** [comment]
Do you want to use a launcher? Instead we'd recommend using
```ruby
Spaceship::Portal.login(username, password)
profile = Spaceship.provisioning_profile.all.detect{ |item| item.name == profileName }
```
