### ISSUE TITLE
Install provisioning profile not working

### ISSUE THREAD

**Issue by lumo2707** [fastlane/fastlane#10227]
Hi,

the installation via the fastlane aciton "update_project_provisioning" is not working. 
The profile was not installed before manually. 
How is it possible to install a provisioning profile at a path?

With my implemented gym command i got the following error:
- Code signing is required for product type 'Application' in SDK 'iOS 10.3'

**Comment by KrauseFx** [comment]
We don't recommend using the `update_project_provisioning` action any more, check out our code signing guide linked by the bot 👍

**Comment by grifotv** [comment]
@KrauseFx why should we avoid using `update_project_provisioning`?

I checked the code signing guide and I'm already using `match`, but can't figure out how to update app identifier and project provisioning with Fastlane.

**Comment by ohayon** [comment]
Hey @grifotv, could you provide a bit more information around what you are trying to do, the more context we have the better! 😄 !
