### ISSUE TITLE
An OPTION to change app display name while resigning.

### ISSUE THREAD

**Issue by Dershowitz011** [fastlane/fastlane#10225]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE] Is there a way to change app display name post re-signing? If yes, how? If no, can you please add that feature as an **OPTION ONLY**  in your next release? 
ONLY if we want to change we can. Add this feature to `sigh` off course. Thanks. 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
Sorry that seems very specific and probably not something we want in the fastlane code base for now, however feel free to build a plugin or location for this :)

**Comment by Dershowitz011** [comment]
Try adding the feature of signing the app bundle **(.app)** file at least. That'd be extremely useful. Do oblige. Thanks.
