### ISSUE TITLE
Spaceship ITC service key caching is surprising and undocumented

### ISSUE THREAD

**Issue by untitaker** [fastlane/fastlane#10226]
In https://github.com/fastlane/fastlane/blob/e93b397900bbea5aa626ea2c44b45c172e444d1c/spaceship/lib/spaceship/client.rb#L497-L499, spaceship caches the iTunes Connect service key in a global file. While there may be valid reasons for Spaceship to do this:

* writing to global state like that isn't something you would normally expect from a library
* it isn't documented anywhere as far as I can tell.

Because of those two reasons it took us a long time to figure out why our tests were failing. We use VCR to prevent Spaceship from making any actual network requests, so it may happen that the cassette gets recorded with a valid cache (therefore missing the requests made to fetch the ITC service key) which of course breaks later.

I would recommend the following actions:

* Document that the Spaceship gem has global state that persists across processes.
* Add a method for resetting that global state (i.e. add a method to remove that temporary file) such that we don't have to hardcode that path in our own `spec_helper`.

I am also unsure why such an "aggressive" cache is needed in the first place. Would it be sufficient to cache it in memory, or perhaps even reset it everytime `Spaceship::Tunes.login` is called? That would solve some concurrency problems as a side effect. (https://github.com/fastlane-old/spaceship/pull/207 is related but was reverted by https://github.com/fastlane/fastlane/commit/5df0dc2fe8d3ac3a0acf18c46f3e24eb4bc57db7).

**Comment by untitaker** [comment]
Shouldn't matter for this issue.

**Comment by untitaker** [comment]
Hello @KrauseFx @ohayon if you could give quick feedback on the suggestions above then we can start working on PRs.

**Comment by KrauseFx** [comment]
> Because of those two reasons it took us a long time to figure out why our tests were failing. We use VCR to prevent Spaceship from making any actual network requests, so it may happen that the cassette gets recorded with a valid cache (therefore missing the requests made to fetch the ITC service key) which of course breaks later

Why do you prevent spaceship from making request? 

> Document that the Spaceship gem has global state that persists across processes.

That's not the only thing fastlane caches, we're doing more, including the derived data, session cookies, etc. Or do you mean the fact that it's in `/` instead of `~/Library/Cache`?

> Would it be sufficient to cache it in memory, or perhaps even reset it everytime Spaceship::Tunes.login is called?

it's only needed for the login, the cache wouldn't help if we were to clear it on every login

In general, the API key seems to never change, but we're not allowed to bundle it with fastlane (at least from my understanding), so we download and store it. _spaceship_ shouldn't cache the key if it doesn't get a valid key. If that was the case for your setup, we should fix that instead 👍

**Comment by untitaker** [comment]
>Why do you prevent spaceship from making request?

Only in our tests! We use [vcr](https://relishapp.com/vcr/vcr/) to record all requests spaceship makes once and then replay them. This makes it easier to adjust the tests should a new spaceship version use different APIs (you have to just rerecord the requests).

>That's not the only thing fastlane caches, we're doing more, including the derived data, session cookies, etc. Or do you mean the fact that it's in / instead of ~/Library/Cache?

From my perspective it doesn't matter whether it's in either `/` or `~/Library/Cache`. Either way it is state that I have to clean up if I want my tests to not influence each other. Right now our workaround is to have code similar to https://github.com/fastlane/fastlane/blob/f1abb188eb0b167b8447d6dc34f80f4db090c893/spaceship/spec/spec_helper.rb#L68 in our own codebase, but we really shouldn't have to do this.

>spaceship shouldn't cache the key if it doesn't get a valid key. If that was the case for your setup, we should fix that instead :+1:

No, that's not the case at all.

**Comment by untitaker** [comment]
I forgot to respond to this:

>it's only needed for the login, the cache wouldn't help if we were to clear it on every login

In that case, would you accept a PR that adds a method to spaceship's public API to clear all of those caches?

**Comment by KrauseFx** [comment]
Mh, you're actually the first one to mention this, so it doesn't seem like a big problem for most users. Could you add a feature to delete the file as part of your setup (e.g. in your Fastfile)

**Comment by untitaker** [comment]
We use spaceship as a client library for iTunes connect. We are not involved
with writing the actual app. Therefore no Fastfile exists.

Again, we already delete the file ourselves, that was never the point. The
(aesthetic) issue I have with this is that we have knowledge of Spaceship's
internals (cache paths) in our own codebase which we shouldn't have.

**Comment by untitaker** [comment]
This is not an unintentional bug, but an API wart at least in my opinion... It's up to @KrauseFx re what to do with this.

**Comment by ohayon** [comment]
Hey @untitaker, thanks for following up with this. I think for now, we are going to avoid changing around the way this is currently working. I know that it is not ideal for your tests, I'm just wondering if there is any other workaround that we can come up with to fix this for you. If you are using VCR, is it possible for you to mock out the return values from the cache so that your tests are unaffected by the local cache? 🐙

**Comment by untitaker** [comment]
I was actually only asking for a helper method exposed by spaceship that would allow me to clear the cache.

The idea is to not rely on spaceships internals

On 24 October 2017 19:19:00 GMT+02:00, David Ohayon <notifications@github.com> wrote:
>Hey @untitaker, thanks for following up with this. I think for now, we
>are going to avoid changing around the way this is currently working. I
>know that it is not ideal for your tests, I'm just wondering if there
>is any other workaround that we can come up with to fix this for you.
>If you are using VCR, is it possible for you to mock out the return
>values from the cache so that your tests are unaffected by the local
>cache? 🐙 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/fastlane/fastlane/issues/10226#issuecomment-339065938

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ohayon** [comment]
Ah, yeah, I hear your concern. Is there any chance you would want to submit a PR with the change and we can try to get it in to our next release?

**Comment by untitaker** [comment]
Sure, will do. Can't promise anything this week though.

**Comment by ohayon** [comment]
Sweet. thanks @untitaker - looking forward to seeing your change!

**Comment by untitaker** [comment]
Hey @ohayon, it seems that it's currently not possible to run any tests under Linux. When I try to run `rspec` (or `rspec spaceship`) as described in `YourFirstPR`, I hit a lot of code that will attempt to validate my `xcode` settings. Xcode shouldn't be necessary if I am working on spaceship?

**Comment by ohayon** [comment]
You're right it shouldnt be necessary. Unfortunately at the moment fastlane isnt so great at running on Linux, but if you could provide some stacktraces or output of where it's failing it would be helpful to take a look 😄

**Comment by untitaker** [comment]
Sorry, you're right I should've provided that. Here you go:

```
$ rvm use
Using /home/mau/.rvm/gems/ruby-2.4.1 with gemset fastlane

$ bundle
[...]
Bundle complete! 22 Gemfile dependencies, 119 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ DEBUG=true rspec spaceship
No DRb server is running. Running in local process instead ...
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/home/mau/projects/fastlane/fastlane_core/lib/fastlane_core/helper.rb:138:in ``': No such file or directory - xcode-select (Errno::ENOENT)
	from /home/mau/projects/fastlane/fastlane_core/lib/fastlane_core/helper.rb:138:in `xcode_path'
	from /home/mau/projects/fastlane/spec_helper.rb:15:in `<top (required)>'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `require'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/invocations.rb:23:in `call'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:69:in `run'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/bin/rspec:22:in `load'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/bin/rspec:22:in `<main>'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/bin/ruby_executable_hooks:15:in `eval'
	from /home/mau/.rvm/gems/ruby-2.4.1@fastlane/bin/ruby_executable_hooks:15:in `<main>'
[Coveralls] Outside the CI environment, not sending data.
```

**Comment by ohayon** [comment]
Oh interesting. So this is coming from the spec helper that is looking for Xcode, that is probably something that we could make conditional upon operating system right?

**Comment by untitaker** [comment]
@ohayon Sure, it appears there is already some logic in there to distinguish between Darwin and Linux, but not all helper functions appear to honor it anyway. Not sure if I can help here, I did try to fix the spec issues on Linux but wasn't very successful. I don't really understand how CI works then.
