### ISSUE TITLE
Deliver - fails to deliver

### ISSUE THREAD

**Issue by fishandphil** [fastlane/fastlane#10228]
We used to love using FastLane Deliver and it used to work perfectly. 
Here we init Deliver and then push and it breaks directly. 

We can make it work when skipping the screenshots. However, we really need it to upload our screenshots.. Otherwise there is no point using it. 

Thank you

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Philippes-MacBook-Pro:FastLane philippe$ fastlane deliver
[12:13:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:13:32]: Successfully loaded '/Users/philippe/Dropbox/xxx/AppStore/18 - v2.10/FastLane/Deliverfile' 📄
[12:13:32]: No values defined in './Deliverfile'
[12:13:32]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[12:13:32]: To not be asked about this value, you can specify it using 'username'
[12:13:32]: Your Apple ID Username: xxx@xxx.com
[12:13:38]: Login to iTunes Connect (xxx@xxx.com)
[12:13:41]: Login successful
[12:13:41]: The Bundle Identifier of your App: com.xxx.xxx

+--------------------------------------+----------------------+
|                   deliver 2.55.0 Summary                    |
+--------------------------------------+----------------------+
| username                             | xxx@xxx.com |
| app_identifier                       | com.xxx.xxx    |
| screenshots_path                     | ./screenshots        |
| metadata_path                        | ./metadata           |
| edit_live                            | false                |
| platform                             | ios                  |
| skip_binary_upload                   | false                |
| skip_screenshots                     | false                |
| skip_metadata                        | false                |
| skip_app_version_update              | false                |
| force                                | false                |
| submit_for_review                    | false                |
| automatic_release                    | false                |
| overwrite_screenshots                | false                |
| run_precheck_before_submit           | true                 |
| precheck_default_rule_level          | warn                 |
| ignore_language_directory_validation | false                |
+--------------------------------------+----------------------+

Looking for related GitHub issues on fastlane/fastlane...

➡️  wrong number of arguments (given 1, expected 2) in snapshot runner.rb:200
    https://github.com/fastlane/fastlane/issues/5976 [closed] 8 💬
    24 Apr 2017

➡️  Fix `pilot distribute`
    https://github.com/fastlane/fastlane/pull/9005 [closed] 7 💬
    5 weeks ago

➡️  snapshot: File name of screenshots is appended by a unique ID
    https://github.com/fastlane/fastlane/issues/8339 [closed] 35 💬
    5 weeks ago

and 7 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20(given%201,%20expected%202)&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/upload_screenshots.rb:76:in `collect_screenshots_for_languages': [!] wrong number of arguments (given 1, expected 2) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/upload_screenshots.rb:89:in `block in collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/upload_screenshots.rb:84:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/upload_screenshots.rb:84:in `collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/upload_screenshots.rb:73:in `collect_screenshots'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/runner.rb:95:in `upload_metadata'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/runner.rb:26:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/commands_generator.rb:173:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.55.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 2.0.2        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-09-01**
</details>

**Comment by KrauseFx** [comment]
Awesome, thanks for the report, I just pushed https://github.com/fastlane/fastlane/pull/10287
