### ISSUE TITLE
Duplicate information in Appfile, Deliverfile etc. - Can we get rid of one of them?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10238]
After using `fastlane deliver init` I get a new `Deliverfile` that contains the same `app_identifier` and `username` (there as `apple_id`) that I already have in `Appfile`. 

One comment also says `# Feel free to remove the following line if you use fastlane (which you should)`.

Does this mean I can get rid of this duplicate information?
Can I get rid of this whole file?

**Comment by janpio** [comment]
I tested this for the `Deliverfile` that got created when I ran `fastlane deliver init` with duplicated variables from `Appfile` - I could `fastlane deliver` and also `fastlane deliver init` again (after deleting the previous files).

So my guess is you don't actually need this file if the correct values are also in your Appfile and you don't need any additional configuration options to be active.

**Comment by KrauseFx** [comment]
Yeah, it's a little confusing, you can delete your `Appfile` or `Deliverfile` or keep using them. You can have everything in your `Fastfile` if you want.

**Comment by janpio** [comment]
Ah, even the `Appfile` can go, interesting. 
I actually like the setup with `Appfile` and `Fastfile` - app information and variables in the former, lanes in the latter, so different project can use the same `Fastfile`.

Will this setup work?

**Comment by KrauseFx** [comment]
Yeah they can use the same Fastfile, also check out https://github.com/fastlane/examples
