### ISSUE TITLE
[deliver] "Insufficient privileges" error when Developer role user tries to upload a new-nonexisting app version to ITC (does work when u/led manually through Xcode)

### ISSUE THREAD

**Issue by LiorApp** [fastlane/fastlane#10236]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

* Using fastlane 2.54.0 we are unable to upload an app ipa with a new non-existing version (=create a new app version) with an ITC user with **Developer** Role, we're getting an "insufficient privileges" error from fastlane.
When using the **same** user together with the **same** exact credentials, uploading manually through Xcode succeeded.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

➜  ✗ fastlane deliver --verbose
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[11:29:47]: fastlane detected a Gemfile in the current directory
[11:29:47]: however it seems like you don't use `bundle exec`
[11:29:47]: to launch fastlane faster, please use
[11:29:47]:
[11:29:47]: $ bundle exec fastlane deliver --verbose
[11:29:47]:
[11:29:47]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/X/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/****/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/****/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/****/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/****/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/****/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/azi/Documents/Apps/****/fastlane/Appfile'
-------
INFO [2017-09-01 11:29:49.60]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
WARN [2017-09-01 11:29:49.61]: To not be asked about this value, you can specify it using 'username'
 [2017-09-01 11:29:49.61]: Your Apple ID Username: ******
INFO [2017-09-01 11:29:57.77]: Login to iTunes Connect (*****)
Multiple iTunes Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable
INFO [2017-09-01 11:30:07.91]: Login successful

+-----------------------------+------------------------+
|                deliver 2.54.0 Summary                |
+-----------------------------+------------------------+
| username                    | *     |
| app_identifier              | *   |
| screenshots_path            | ./fastlane/screenshots |
| metadata_path               | ./fastlane/metadata    |
| app_version                 | 4.0.2                  |
| edit_live                   | false                  |
| ipa                         | Zapp-App-Store.ipa     |
| platform                    | ios                    |
| skip_binary_upload          | false                  |
| skip_screenshots            | false                  |
| skip_metadata               | false                  |
| skip_app_version_update     | false                  |
| force                       | false                  |
| submit_for_review           | false                  |
| automatic_release           | false                  |
| overwrite_screenshots       | false                  |
| run_precheck_before_submit  | true                   |
| precheck_default_rule_level | warn                   |
+-----------------------------+------------------------+

INFO [2017-09-01 11:30:09.88]: Making sure the latest version on iTunes Connect matches '4.0.2' from the ipa file...
Potential server error received: 'insufficient privileges'. Retrying after 10 seconds (remaining: 5)...
Potential server error received: 'insufficient privileges'. Retrying after 10 seconds (remaining: 5)...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	insufficient privileges

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09insufficient%20privileges+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

#######################################################################
# fastlane 2.55.0 is available. You are on 2.54.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

2.55.0 Improvements
* Show nice error message for common Xcode 9 code signing issue (#10204) via Felix Krause
* Add support for provisioning profile templates for all fastlane tools (#9912) via Andrei Raifura
* Escape HipChat room name (#10179) via Takeichi Kanzaki Cabrera
* Update data structure for tester exporting (#10207) via David Ohayon
* Clarify question in app_store_build_number action (#10203) via Felix Krause
* make sure not to call map on nil array (#10219) via David Ohayon
* Add new sub pages for all actions and tools (#10209) via Felix Krause

2.54.4 Improvements
- [snapshot] Update docs for concurrent simulator support (#10182) via David Ohayon
- [download_dsyms] Add option to download latest dSYM file  (#10129) via Addison Brickey
- [deliver] Fix screenshot uploads (#10175) via Luis Ramos
- [testfairy] Handle timeouts (#10124) via Joseph Petersen
- Update xcode-install dependency (#10139) via Felix Krause

2.54.3 Improvements
* Rename missing methods from Google API Client
* Fix regression with iMessage & AppleTV screenshots
* Add tests for Google API Client
* Allow slather to support Travis-Pro
* Restrict public_suffix to version 2.0.x

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/spaceship/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectPotentialServerError)
	insufficient privileges
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/spaceship/lib/spaceship/tunes/tunes_client.rb:354:in `block in update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1327:in `with_tunes_retry'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/spaceship/lib/spaceship/tunes/tunes_client.rb:347:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/spaceship/lib/spaceship/tunes/app_version.rb:388:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/spaceship/lib/spaceship/tunes/application.rb:217:in `ensure_version!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/deliver/lib/deliver/runner.rb:80:in `verify_version'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/deliver/lib/deliver/runner.rb:25:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/deliver/lib/deliver/commands_generator.rb:173:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>
### Stack
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |
### System Locale
| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |
### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>
```ruby
require 'dotenv'
Dotenv.load
default_platform :ios
platform :ios do
  lane :test do
    fastlane_require 'dotenv'
    scan(
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      scheme: ENV['PROJECT_NAME'],
      output_directory: "#{ENV['CIRCLE_TEST_REPORTS']}/results.xml",
      device: "iPhone 7",
      code_coverage: true
    )
  end
  lane :dev do
    fastlane_require 'dotenv'
    gym(
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      scheme: ENV['PROJECT_NAME'],
      configuration: "Debug",
      include_bitcode: false,
      output_directory: ENV['CIRCLE_ARTIFACTS'],
      output_name: "#{ENV['PROJECT_NAME']}-Enterprise",
      build_path: ENV['BUILD_PATH'],
      derived_data_path: ENV['BUILD_PATH'],
      export_team_id: ENV['ENTERPRISE_CODE_SIGNING_TEAM_ID'],
      export_method: "enterprise",
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{ENV["ENTERPRISE_PROVISIONING_PROFILE_SPECIFIER"]}' DEBUG_INFORMATION_FORMAT='dwarf-with-dsym'"
    )
    command = "curl -F 'private=false' \
    -F 'status=2' \
    -F 'notify=0' \
    -F 'notes=Debug Version' \
    -F 'ipa=@#{ENV['CIRCLE_ARTIFACTS']}/#{ENV['PROJECT_NAME']}-Enterprise.ipa' \
    -F 'dsym=@#{ENV['CIRCLE_ARTIFACTS']}/#{ENV['PROJECT_NAME']}-Enterprise.app.dSYM.zip' \
    -H 'X-HockeyAppToken:#{ENV['HOCKEY_APP_TOKEN']}' https://rink.hockeyapp.net/api/2/apps/upload"
    sh("#{command}")
  end
  lane :store do
    fastlane_require 'dotenv'
    gym(
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      scheme: ENV['PROJECT_NAME'],
      configuration: "Release",
      include_bitcode: false,
      include_symbols: true,
      output_directory: ENV['CIRCLE_ARTIFACTS'],
      output_name: "#{ENV['PROJECT_NAME']}-Store",
      build_path: ENV['BUILD_PATH'],
      derived_data_path: ENV['BUILD_PATH'],
      export_team_id: ENV['STORE_CODE_SIGNING_TEAM_ID'],
      export_method: "app-store",
      xcargs: "DEVELOPMENT_TEAM='#{ENV["STORE_CODE_SIGNING_TEAM_ID"]}' PROVISIONING_PROFILE_SPECIFIER='#{ENV["STORE_PROVISIONING_PROFILE_SPECIFIER"]}' DEBUG_INFORMATION_FORMAT='dwarf-with-dsym'"
    )
    deliver(
      username: ENV['itunes_connect_user'],
      app: ENV['itunes_app_id'],
      ipa: "#{ENV['PROJECT_NAME']}-Store.ipa",
      team_name: ENV['TEAM_NAME'],
      submit_for_review: false,
      force: true,
      skip_screenshots: true,
      skip_metadata: true
    )
    command = "curl -F 'private=false' \
    -F 'status=2' \
    -F 'notify=0' \
    -F 'notes=Store Version' \
    -F 'ipa=@#{ENV['PROJECT_NAME']}-Store.ipa' \
    -F 'dsym=@#{ENV['PROJECT_NAME']}-Store.ipa.app.dSYM.zip' \
    -H 'X-HockeyAppToken:#{ENV['HOCKEY_APP_TOKEN']}' https://rink.hockeyapp.net/api/2/apps/upload"
    sh("#{command}")
  end
end
```
</details>
<details><summary>`./fastlane/Appfile`</summary>
```ruby
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>
### fastlane gems
| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.54.0  | 🚫 Update available |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| json                      | 2.1.0        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| bundler                   | 1.15.3       |
| unicode-display_width     | 1.3.0        |
</details>
*generated on:* **2017-09-01**
</details>

**Comment by LiorApp** [comment]
I'm afraid it's not a code signing issue, we're using the same credentials on both ways.

**Comment by ChristopherStephan** [comment]
We are experiencing exactly the same problem as described. When changing the role to 'app manager' the ipa file upload to iTunes Connect succeeds.

**Comment by Orgmir** [comment]
I'm experiencing the same issue trying to upload with an account with Developer Role. Maybe iTunes Connect permissions where updated without us noticing?

**Comment by ohayon** [comment]
Hey everyone, I have a feeling that @Orgmir is correct. Can other people confirm that the App Manager role can upload?

**Comment by skullet** [comment]
We are running into the same issue. Cert things haven't changed in a week and this issue showed up toward the end of last week. Build account is Developer not App Manager.

**Comment by matthamil** [comment]
I had the same issue with my iTunes Connect account set as "Developer."

**Comment by EthanChouTW** [comment]
following the mention above.
I was using account 'Developer' and got reject, and change to 'App Manager' then it works

**Comment by NikolayShubenkovProgSchool** [comment]
I have the same issue too (

**Comment by sadiq81** [comment]
I'm experiencing a similar problem #11536
