### ISSUE TITLE
Pilot logins but Transporter fails (-20283) wrong password

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#10232]
So I have this weird issue that I suspect (after reading some posts here) might be connected with special characters in my password, that is "!!" one after another.  Deliver on the other hand seems to work fine.

### Issue Description

DEBUG [2017-09-01 19:15:26.31]: [Transporter]: DBG-X:   parameter Version = 1.9.3
DEBUG [2017-09-01 19:15:26.31]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2017-09-01 19:15:26.31]: [Transporter]: INFO: id = 20170901191526-965
DEBUG [2017-09-01 19:15:26.57]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2017-09-01 19:15:26.57]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20283)
DEBUG [2017-09-01 19:15:26.57]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20283)]
DEBUG [2017-09-01 19:15:26.58]: [Transporter]: DBG-X:   parameter ErrorCode = -20283
DEBUG [2017-09-01 19:15:26.58]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2017-09-01 19:15:26.58]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20283)
### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'dotenv'
Dotenv.load
CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) 

import "../MasterFastfile"

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.****" # The bundle identifier of your app
apple_id *****@me.com" # Your Apple email address
team_id "********"```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.1       |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
</details>


*generated on:* **2017-09-01**
</details>

**Comment by masteranza** [comment]
Solved it! Turns out it was not related to special characters.
When I've modified the method  `load_password_for_transporter` to only use the third method (standard iTC password) then it worked flawlessly! 

So this error seems to be related to `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` which I have setup for a different team (and different apple_id). It would be great to be able to indicate that certain user may not want to use `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.

Also a bit disconcerting is the fact that prior to the mentioned solution, after I've inserted the right account details through console it failed as well.

**Comment by KrauseFx** [comment]
That's super weird, how can we fix this?

**Comment by masteranza** [comment]
@KrauseFx I think that we'd need to determine whether or not it is a two-factor-authentification group first. Because right now the logic goes right this: 1. try two-factor auth 2. try app-specific keychain auth 3. try the regular keychain auth.

I'm also amazed how the solutions to one problem got so many solutions... I'd propose using only keychain for everything including two-factor auth with team_id as a prefix in key name.
The current way in which two-factor auth works is not really elastic enough (and it's also kinda cumbersome to make env variables in bash) to work with many teams.  

Also I don't really understand (and never used) the app-specific keychain auth. Wouldn't it make more sense to do team-specific auth in keychain in general?

**Comment by sharat** [comment]
I think I am facing a similar problem where I had 2FA enabled for my account and specified `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` in the environment variable. Fastlane complains that I need to specify `FASTLANE_PASSWORD` as to continue to login. I have given app specific password as `FASTLANE_PASSWORD` as well and login failed. I think if `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is already, set we should not authenticate using Keychain or `FASTLANE_PASSWORD`.

**Comment by sharat** [comment]
I think I am facing a similar issue.

`load_password_for_transporter` tries to load `TWO_FACTOR_ENV_VARIABLE` (`FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`) before attempting any other method of login. I am not quite sure why I was prompted to enter Apple ID password though  `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is already setup.

In addition, it also requires FASTLANE_PASSWORD to attempt login (if not present in keychain). It should ignore everything else if two factor environment variables are available.

![screen shot 2017-09-10 at 7 16 03 pm](https://user-images.githubusercontent.com/405971/30250789-2a75e78c-965d-11e7-95b7-3f8ea71945d9.png)

**Comment by ohayon** [comment]
Thanks everyone for chiming in here. We have seen issues with the transporter a few times. Is there anyone that would want to submit a PR for this and beat us to the punch? 🚀
