### ISSUE TITLE
[Supply] Remove App from Sale, getting version name, list developer apps

### ISSUE THREAD

**Issue by oskarn97** [fastlane/fastlane#10242]
Hey,

I wanted to check whether the following features are possible with supply but could not find any information about that:
- Suspending / unreleasing an already released app from the Play Store
- Getting the version name (for example v3.2.1, not the APK version code)
- List available apps on an developer account

Thanks!

**Comment by janpio** [comment]
> Suspending / unreleasing an already released app from the Play Store
> List available apps on an developer account

There are not API methods for this:
https://developers.google.com/apis-explorer/#p/androidpublisher/v2/

Same for the non-ruby API description: https://developers.google.com/android-publisher/
