### ISSUE TITLE
Doc Guide update - Snapshot and CI

### ISSUE THREAD

**Issue by thelontx** [fastlane/fastlane#1024]
I am new to Fastlane.  Just setting it up and following: fastlane/docs/Guide.md

In the "Enable Instruments CLI" section, there are 2 pointers to the snapshot repository that do not have a corresponding section defined:
https://github.com/KrauseFx/snapshot#run-in-continuous-integration

I am not sure if there are specific instructions I should follow or if the pointer in the fastlane guide requires updating.

**Comment by KrauseFx** [comment]
Thank you so much for pointing this out. This is not necessary any more with the new UI Testing technology. I'll update the docs accordingly.
