### ISSUE TITLE
gym deletes project if target is same name as enclosing project folder 😵

### ISSUE THREAD

**Issue by taquitos** [fastlane/fastlane#10240]
1. Create new project "DontDeleteMe"
2. call `fastlane gym -p DontDeleteMe/DontDeleteMe.xcodeproj` from folder that contains the `DontDeleteMe` folder (in this case, I created a project in ~/Downloads and I ran _gym_ from $~/Downloads
3. after your default target is built, it kills the "DontDeleteMe" folder.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.12.6                                                  |
| Ruby                        | 2.2.7                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.11.0 (Apple Git-81)                        |
| Installation Source         | ~/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.7/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 8.3.3                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.54.3  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.15.4       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-09-01**
</details>

$ be fastlane gym -p DeleteApp/DeleteApp.xcodeproj --verbose
INFO [2017-09-01 19:43:27.48]: $ xcodebuild -showBuildSettings -project DeleteApp/DeleteApp.xcodeproj
2017-09-01 19:43:27.872 xcodebuild[22821:396061] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/IBUnfuck.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-09-01 19:43:27.872 xcodebuild[22821:396061] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
DEBUG [2017-09-01 19:43:29.52]: Parsing project file '/Users/jliebowitz/Downloads/DeleteApp/DeleteApp.xcodeproj' to find selected provisioning profiles
DEBUG [2017-09-01 19:43:29.52]: Finding provision profiles for 'Release'
DEBUG [2017-09-01 19:43:29.59]: Merging provisioning profile mappings
DEBUG [2017-09-01 19:43:29.59]: -------------------------------------
DEBUG [2017-09-01 19:43:29.59]: Primary provisioning profile mapping:
DEBUG [2017-09-01 19:43:29.59]: {}
DEBUG [2017-09-01 19:43:29.59]: Secondary provisioning profile mapping:
DEBUG [2017-09-01 19:43:29.59]: {}
DEBUG [2017-09-01 19:43:29.59]: Resulting in the following mapping:
DEBUG [2017-09-01 19:43:29.59]: {}
INFO [2017-09-01 19:43:29.59]: $ xcodebuild -list -project DeleteApp/DeleteApp.xcodeproj
2017-09-01 19:43:30.059 xcodebuild[22827:396171] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/IBUnfuck.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-09-01 19:43:30.060 xcodebuild[22827:396171] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs

+------------------+---------------------------------------------------------------+
|                              Summary for gym 2.54.3                              |
+------------------+---------------------------------------------------------------+
| project          | DeleteApp/DeleteApp.xcodeproj                                 |
| scheme           | DeleteApp                                                     |
| destination      | generic/platform=macOS                                        |
| output_name      | App                                                           |
| build_path       | /Users/jliebowitz/Library/Developer/Xcode/Archives/2017-09-01 |
| clean            | false                                                         |
| output_directory | .                                                             |
| silent           | false                                                         |
| skip_package_ipa | false                                                         |
| buildlog_path    | ~/Library/Logs/gym                                            |
| xcode_path       | /Applications/Xcode.app                                       |
+------------------+---------------------------------------------------------------+

+----------------------------------------------------------------------------------+------------------------+
|                                          Generated Build Command                                          |
+----------------------------------------------------------------------------------+------------------------+
| Option                                                                           | Value                  |
+----------------------------------------------------------------------------------+------------------------+
| set -o pipefail &&                                                               |                        |
| xcodebuild                                                                       |                        |
| -scheme DeleteApp                                                                |                        |
| -project DeleteApp/DeleteApp.xcodeproj                                           |                        |
| -destination                                                                     | generic/platform=macOS |
| -archivePath /Users/jliebowitz/Library/Developer/Xcode/Archives/2017-09-01/App\  |                        |
| 2017-09-01\ 19.43.31.xcarchive                                                   |                        |
| archive                                                                          |                        |
| | tee /Users/jliebowitz/Library/Logs/gym/App-DeleteApp.log                       |                        |
| | xcpretty                                                                       |                        |
+----------------------------------------------------------------------------------+------------------------+
INFO [2017-09-01 19:43:31.87]: $ set -o pipefail && xcodebuild -scheme DeleteApp -project DeleteApp/DeleteApp.xcodeproj -destination 'generic/platform=macOS' -archivePath /Users/jliebowitz/Library/Developer/Xcode/Archives/2017-09-01/App\ 2017-09-01\ 19.43.31.xcarchive archive | tee /Users/jliebowitz/Library/Logs/gym/App-DeleteApp.log | xcpretty
INFO [2017-09-01 19:43:32.31]: ▸ 2017-09-01 19:43:32.315 xcodebuild[22833:396296] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/IBUnfuck.xcplugin' not present in DVTPlugInCompatibilityUUIDs
INFO [2017-09-01 19:43:32.31]: ▸ 2017-09-01 19:43:32.315 xcodebuild[22833:396296] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
INFO [2017-09-01 19:43:34.04]: ▸ Building DeleteApp/DeleteApp [Release]
INFO [2017-09-01 19:43:34.04]: ▸ Check Dependencies
INFO [2017-09-01 19:43:34.14]: ▸ Compiling main.swift
INFO [2017-09-01 19:43:34.56]: ▸ Linking DeleteApp
INFO [2017-09-01 19:43:35.45]: ▸ Generating 'DeleteApp.dSYM'
INFO [2017-09-01 19:43:35.81]: ▸ Signing /Users/jliebowitz/Library/Developer/Xcode/DerivedData/DeleteApp-dixmmzhlmeluucezksyucjfywciq/Build/Intermediates/ArchiveIntermediates/DeleteApp/InstallationBuildProductsLocation/usr/local/bin/DeleteApp
INFO [2017-09-01 19:43:35.97]: ▸ Touching DeleteApp.dSYM
INFO [2017-09-01 19:43:36.00]: ▸ Archive Succeeded
DEBUG [2017-09-01 19:43:36.33]: Stored the archive in: /Users/jliebowitz/Library/Developer/Xcode/Archives/2017-09-01/App 2017-09-01 19.43.31.xcarchive
INFO [2017-09-01 19:43:36.34]: Exporting Files:
WARN [2017-09-01 19:43:36.34]: Removing DeleteApp from output directory
INFO [2017-09-01 19:43:36.35]: 	 ▸ DeleteApp

**Comment by KrauseFx** [comment]
Can you please format the issue properly? 😉

**Comment by taquitos** [comment]
Y̶͖̐͑͆̀̾̒͘è̶̟̺͔̮̪̻̖͒̾͒̋͐̆̄̉̓͌̈́͝͠͝a̷̺̘̾̑́̀͐͂̽̆ḩ̷̢̥͎̦̗̯͔̪̳͖̪͚͕̐̓̐̇̕,̴̛̙͉̙͉̱̣̫̭̇̂ ̸̼̦̘̱̿̂̀̒̄͒̒̐͊̀̓̇͂̔i̶͕̯̩͇̓̊̆͂͒̌s̸̡͍̩̼̫̹͎̻͓̣̱̬̳̻̓̋́̏ ̷̫͙͙̠̖͔͖͎͚̗̥̬͓̩̐t̴̨̢̘̺̭̰̹̖̰̖̩̮̗͕̟̃̒̐̉͐̃̎͛̃͐͘̚͠h̸̢̡̨̯͖̜̖̰͂̋̋ͅi̷̡̫̦̯̩̪̼͙͓̥̥͐̓̄̋̾͒͌̇͛̄̚̚͠s̵̨̛̹͓̭͈͓̘͇̙͕̗̝͓̙̐̈́̉̏̏̍ ̸͈̙̫̭̭̤̆̋̊̂ͅb̴̓͆̓͂̔̀͝ͅę̵̰̗̫̰̉̉͗̿́ẗ̵̘͉̙͎̯͙̘̎͑̃́̉͌́̄͌̀̀̅̈́ţ̷̲͇͉̝̤͇̲͎̃e̸͖̪̭̐̅ŗ̶̲̱̬̣̬̤̼̽͛̂̊͂͒̚͜͠?̸̨͕̗͙̤̞̹̳͙̹̺̱̑͋̓͂͌͒͐̓́
