### ISSUE TITLE
Kids Mode with Spaceship

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#10254]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

How i can set Enable for Kid with Spaceship, like in the older version of Delivery?

https://github.com/fastlane-old/deliver/blob/2d40589a90046f980d780f5076f9778fe73cce53/lib/deliver/itunes_connect/itunes_connect_app_rating.rb#L51

**Comment by bolom** [comment]
someone at least can give me the direction to implement this feature?

**Comment by KrauseFx** [comment]
I don't think that's possible right now, sorry. You can implement it as part of spaceship. Check out https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md on how to get started working on _spaceship_ 👍

**Comment by RishabhTayal** [comment]
@KrauseFx any direction on where to start the implementation? I would be happy to contribute.

**Comment by ohayon** [comment]
Hey @RishabhTayal - that link that Felix put above is a great way to get started with the implementation, likely the network call to set the value would be in the Tunes::Client object or somewhere similar. 💯

**Comment by RishabhTayal** [comment]
@ohayon I mean where to start with logic implementation part.

**Comment by ohayon** [comment]
The `Spaceship::Tunes::Client` might be a good place to start looking I believe.
