### ISSUE TITLE
[snapshot] 'iPad Pro (12.9-inch)' screenshot size 1 pixel off when running via iOS11/Xcode9

### ISSUE THREAD

**Issue by dayjer** [fastlane/fastlane#10259]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

When running snapshot with Xcode 9 build tools & the latest Fastlane ver (fastlane 2.55.0) with SnapshotHelperVersion [1.5], using '--ios 11.0', the iPad Pro screenshots are off by 1 pixel. Resulting screenshots are 2048 × 2731 instead of 2048 × 2732.

=======

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.6                                          |
| Ruby                        | 2.4.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.5 (Apple Git-94)                |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane              |
| Host                        | Mac OS X 10.12.6 (16G29)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                     |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-09-06**
</details>

**Comment by KrauseFx** [comment]
That's weird, anything fastlane snapshot can do to fix it? We just take a screenshot from the device using the xcodebuild command line tools

**Comment by dayjer** [comment]
Might go away with xcode 9.0 release, should we just keep this open till then? I'll check next Xcode update if it's resolved.

**Comment by KrauseFx** [comment]
Sounds great :+1:

**Comment by soheil** [comment]
Happening here too, running xcode 9. My iPhone 6 Plus screenshots are 3 pixel taller than what they should be.

**Comment by cfis** [comment]
I am also seeing this on 'iPad Pro (12.9-inch) (2nd generation)' with Xcode 9.  The image on disk generated by snapshot is in fact 2048 by 2731.  Snapshot then decides this is an unsupported size, showing this message:

>Unsupported screen size [2048, 2731]

**Comment by fixpunkt** [comment]
We have the same issue when capturing screenshots using fastlane and XCode 9. However, manually taking the screenshots from the simulator results in screenshots of the correct size, so we suspect there's something wrong with the programmatic screenshotting feature that was added to the simulators shipped with XCode 9.

**Comment by Mikrasya** [comment]
We have the same problem. iPad 10.5, iPad 12.9, iPhone X has incorrect size issues. iPhone 5, iPhone 6, and iPhone 6s sizes are ok.

**Comment by ohayon** [comment]
Hey everyone, could you all just confirm that you are using the most recent version of Xcode that Apple released last week? Just want to make sure that everyone is on the same page here. In doing some testing on my machine, I am seeing that iPad 12.9 inch screenshots are sometimes coming out wrong, but iPhone X is looking perfect to me. Also, some people are saying that iPhone 6/6 Plus are wrong, and others are saying that they are correct, so I just want to make sure we are starting from the same place. Thanks!! 🐙 🚀 📷

**Comment by Mikrasya** [comment]
Hi David. I am using the latest Xcode from App Store and not the beta
version. Also, I am using the latest version of Fastlane. Thank you.

**Comment by kd8ssq** [comment]
I'm also in the same boat as @Mikrasya.  I'm running Xcode 9.0 (9A235) and Fastlane 2.59.0.  Right now I'm unable to upload apps because the screenshots for iPad are 1px off.

**Comment by Mikrasya** [comment]
Hi @ohayon. I've verified that iPhone X and iPad 10.5 sizes are ok. I still have issue with iPad 12.9 inch.

For both iPad 10.5 and iPhone X, I am having another issue: https://github.com/fastlane/fastlane/issues/10259 . That was the reason I reported that I've had issues with those sizes.

**Comment by fixpunkt** [comment]
I'm using the release version of XCode 9 and have the problem with iPad 12.9 inch in landscape (screenshots are 2731 x 2048). iPhone X works fine.

I also have the issue with iPad 10.5 described in #9651, but I suspect this is just the same error message, but shown for a different reason (10.5 maybe not supported yet?), since the pixel counts look correct.

**Comment by soheil** [comment]
@KrauseFx can you fix this plz?

**Comment by ohayon** [comment]
Hey @Mikrasya, I think you linked to this same issue in that comment, is there another issue you are having with iPhone X?

**Comment by Mikrasya** [comment]
Sorry. Here is the other issue: https://github.com/fastlane/fastlane/issues/9651

**Comment by bassrock** [comment]
Getting the same issue as well with Xcode 9.0 and fastlane 2.60.0:  ```Unsupported screen size [1668, 2224] for path './fastlane/screenshots/en-US/iPad Pro (10.5-inch)```

**Comment by pedro380085** [comment]
Some issue happens here.

**Comment by Mikrasya** [comment]
I found this comment while searching for information:

The resolution should be 2731 x 2048, not 2732. 2048 x 2048 = 4,194,304 / 1536 = 2730.66667, it makes no sense for Apple to bump it to 2732. 1 extra line of pixels doesn't do anything for UI. It would make the aspect ratio 683 : 512 instead of a perfect 4 : 3.
https://www.imore.com/ipad-pro-once-again-shown-testing-new-app-analytics

So, wrong pixel issue might be more nuanced.

For the time being, I have manually resized the images from 2731 to 2732 and submitted my app. Thanks.

**Comment by bassrock** [comment]
I do know that Xcode 9 has a lot of simulator issues. One I found is:  https://twitter.com/marcoarment/status/915981380743446529    could the screenshot method being used be related?

**Comment by pdruart** [comment]
Same issue :  Unsupported screen size [2048, 2731] for path './en-US/iPad Pro (12.9-inch)

**Comment by pedro380085** [comment]
Maybe a viable solution would be to automatically compare the sizes and resize if needed?

**Comment by zineer** [comment]
I hacked together a Python script which uses imagemagick to get the height of the images and resize if needed. I call the script from my fastfile using the `sh` action after `snapshot`. If your screenshots are landscape, you'd need to adjust the code as necessary.

https://gist.github.com/zineer/962b682c9dce01542225a9c9ced5359c

**Comment by owurman** [comment]
Has anyone filed a RADAR? If so, what's the number?

**Comment by ohayon** [comment]
Hey Everyone! We are going to look into this issue this week for sure. Just to be totally clear, it seems like this is only happening on iPad Pro devices of both 10.5 and 12.9 sizes. Is does that sound right to everyone?

**Comment by bassrock** [comment]
Yea thats what it was occurring on. Im also looking at todays Xcode 9.0.1. Looks like it fixed all the simulator names and by default the simulators now run iOS 11.0.1 when reset.

**Comment by ohayon** [comment]
Thanks @bassrock, I'll make sure to test it on 9.0.1 😄  🚀

**Comment by ohayon** [comment]
So, I have spent some time trying to reproduce this in Xcode 9.0 on iOS 11.0 simulators and in 9.1 with 11.0.1 simulators and was unable to see the same issue 😞 . Can anyone here share a sample project that causes this to happen? Also, if you all were seeing this in 9.0, would you mind giving it a shot in the new Xcode 9.1? (note: you may need to add `ios_version: '11.0.1` to your snapshot options in your Fastfiles because it looks like there is an issue in `xcodebuild` where doing `xcodebuild -version -sdk` prints out info about 11.0 instead of 11.0.1 and we use that command in _fastlane_ to determine the latest version of iOS simulators on your machine. 

Apologies for the inconveniences! Let us know whats up! 🚀

**Comment by datacosmos** [comment]
I have the same problem with XCode Version 9.0.1 (9A1004), doing fastlane snapshot -i 11.0.1,

[08:31:45]: Framing screenshot './de-DE/iPad Pro (12.9-inch) (2nd generation)-05Login.png'
[08:31:45]: Unsupported screen size [2048, 2731] for path './de-DE/iPad Pro (12.9-inch) (2nd generation)-05Login.png'
[08:31:45]: Framing screenshot './de-DE/iPad Pro (12.9-inch)-01HomeScreen.png'
[08:31:45]: Unsupported screen size [2048, 2731] for path './de-DE/iPad Pro (12.9-inch)-01HomeScreen.png'
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.2.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>


*generated on:* **2017-10-20**
</details>

**Comment by LucasVanDongen** [comment]
This seems to happen when you resize the screen once, for example because the iPhone 8 Plus is too big for a 15" MacBook screen in terms of pixels. You'll never be able to resize it back to 100%. If you don't touch any scaling the simulator should always be fine, but quite unusable for larger devices because they're larger than your screen

**Comment by joncursi** [comment]
I'm still getting this error on the latest XCode 9, ios `11.0.1`. It happens only on iPad Pro 12.9 inch for me

**Comment by jeromediaz** [comment]
Still there with Xcode 9.1 and iOS 11.0

**Comment by bassrock** [comment]
I just dropped the 10.5 inch iPad from my screenshots and it works. The issue may be the screen sizes that iTunes Connect now takes.  https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2

The 10.5 inch isn't even listed.

**Comment by fixpunkt** [comment]
Issue still persists with XCode 9.2 and iOS 11.2. My screenshots for iPad 12.9 inch are still `2731x2048`. I've tried resetting the simulators to no avail.

**Comment by jjochen** [comment]
I have the same issue.
How are the screenshots generated?
`xcrun simctl io booted screenshot screenshot.png` creates a screenshots with correct size.

**Comment by GeorgeNita** [comment]
I've tried today to implement snapshot and frameit in my app and I'm having this issue. The screenshots generated by snapshot for iPhone 7 Plus are 1242x2205 and for iPad 2048x2731. When I'm taking the screenshots manually(CMD+S) they are in correct sizes. I've also checked the temporary screenshots that Xcode UI testing takes and place them in Derived Data folder(they are .jpg and with correct size). As I understood fastlane snapshot takes this screenshots from Derived Data folder?

Using Xcode 9.2/iOS 11,2. Latest version of fastlane and snapshot.

**Comment by jbb1003** [comment]
I'm getting this issue also. I don't think it's fastlane per se. 

XCode 9.2 (9C40b)
iPhone 6 S Simulator 11.2
Optimize Rendering for Window Scale is OFF. 
Show Device Bezels is OFF 
Simulator is set as large as I can get it, which is on a 2560x1440p display occupying almost all of the screen. If I set it any larger, it just resets itself to the max to fit on screen.

The screenshot captured in SnapshotHelper.swift with
            let screenshot = app.windows.firstMatch.screenshot() 

has the wrong size:
```
(lldb) po screenshot.image
<UIImage: 0x6040000b1880> size {735, 414} orientation 0 scale 3.000000

```
Note 736 which is wrong!

And this saves out to disk as 2205x1242, when it should be 2208x1242.


I don't know if this has any significance but the key window presented an odd size too:
(lldb) po app?.windows.firstMatch.frame
```
    t =   255.44s Find the Window
▿ Optional<CGRect>
  ▿ some : (0.574999999999989, 0.0, 734.85, 414.0)
    ▿ origin : (0.574999999999989, 0.0)
      - x : 0.574999999999989
      - y : 0.0
    ▿ size : (734.85, 414.0)
      - width : 734.85
      - height : 414.0

```

However, capturing a screenshot with `xcrun simctl io booted screenshot screenshot.png` generates the correct size image.

This seems to be pointing in the direction of a problem with 3x displays / xcode 9 / UI Test screenshots. I have old installs available so I'll investigate.

**Comment by jbb1003** [comment]
Adding a Launch Screen storyboard appears to fix the issue.

**Comment by GeorgeNita** [comment]
So yes. I've have an app with Launch Images in the old fashion way. After adding a Launch Screen storyboard it fixed the snapshot issue(it messed up with other UI stuff but no problem, it's minor). Thank you very much @jbb1003 !

**Comment by jbb1003** [comment]
See comments above. I believe that this is a generic XCode simulator issue, not a fastlane issue.

**Comment by LucasVanDongen** [comment]
As I couldn't get the iPad Pro 12,9" to scale on my 15" MacBook screen I was searching for a solution to make pixel-perfect snapshots. The magic settings was disabling "Optimize rendering for window scale". I'm not sure if this setting is readable by programs using the Simulator but not having this switched off definitely can cause problems on bigger devices.
