### ISSUE TITLE
After upgrading to macbook sierra rvm is not working as expected

### ISSUE THREAD

**Issue by adath** [fastlane/fastlane#10262]
I am getting the below error after trying to run a ruby script. This used to work fine before I upgraded my OS to sierra. 

/Users/alok/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- os (LoadError)
	from /Users/alok/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from test.rb:2:in `<main>'

Can you please advise on this?

Regards,
Alok

**Comment by adath** [comment]
I am sorry. I am new to git and I am getting the below error for when I try out that command.

-bash: fastlane: command not found

**Comment by janpio** [comment]
So you are not using `fastlane`?

**Comment by adath** [comment]
No, I'm not. Please let me know if I have raised this question in a wrong
queue.

-Alok

**Comment by janpio** [comment]
Yes, this is a Github repository for the `fastlane` tool which can be used to automate things for building mobile apps.

You should probably post your problem in a ruby forum or maybe on StackOverflow.

Please close this issue.

**Comment by KrauseFx** [comment]
Thanks for helping out @janpio 👍
