### ISSUE TITLE
Request: update sign doc

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#1026]
Please, update
https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md

According match:
Should We use `match` instead of `sigh`? Or we have to use both of them?

**Comment by KrauseFx** [comment]
Yeah, great catch, will do that now :+1:

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/commit/47bf0f243303186400977709f45ff683b2c219fc
