### ISSUE TITLE
Feature: showing language for failed deliver (copy of #6948)

### ISSUE THREAD

**Issue by dayjer** [fastlane/fastlane#10277]
It states:

"It would be nice to see the language, which failed. For example in such cases:

[!] The request could not be completed because:
        App Name must not contain control characters (for example, null, new lines, carriage returns, escape, and other invisible characters). App Name must
 not contain control characters (for example, null, new lines, carriage returns, escape, and other invisible characters)."

https://github.com/fastlane/fastlane/issues/6948

Doesn't appear to be the case at present. 

[17:00:40]: Activating languages da, de-DE, el, en-US, es-ES, es-MX, fi, fr-FR, id, it, ja, ko, ms, nl-NL, no, pt-BR, pt-PT, ru, sv, th, tr, vi, zh-Hans, zh-Hant...
[17:00:48]: Uploading metadata to iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...

[!] The request could not be completed because:
	App Name must not contain control characters (for example, null, new lines, carriage returns, escape, and other invisible characters). App Name must not contain control characters (for example, null, new lines, carriage returns, escape, and other invisible characters).

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-09-07**
</details>

**Comment by KrauseFx** [comment]
Uh, I thought that's already the case, can you share the complete output when running this with `--verbose` enabled, so we have the stack trace

**Comment by dayjer** [comment]
Will do when I generate them again in a couple days.

**Comment by dayjer** [comment]
I didn't have any invisible characters handy, but I post some bad ones and got this back.

```
INFO [2017-09-12 16:14:08.71]: Uploading metadata to iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Name can’t contain the following character(s): ⚄, ⚅, ⚆, ⚇, ⎇, ⚈, ⚉, ⏏, ⎗, ⎘, ⌘, ⎙, ⎚, ⌥, ⌦, ♨, ⌨, ♩, ♪, ♫, ⌫, ♬, ♭, ♮, ♯, . App Name can’t be longer than 50 characters. Name can’t contain the following character(s): ⚄, ⚅, ⚆, ⚇, ⎇, ⚈, ⚉, ⏏, ⎗, ⎘, ⌘, ⎙, ⎚, ⌥, ⌦, ♨, ⌨, ♩, ♪, ♫, ⌫, ♬, ♭, ♮, ♯, . App Name can’t be longer than 50 characters.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Name%20can%E2%80%99t%20contain%20the%20following%20character(s):%20%E2%9A%84,%20%E2%9A%85,%20%E2%9A%86,%20%E2%9A%87,%20%E2%8E%87,%20%E2%9A%88,%20%E2%9A%89,%20%E2%8F%8F,%20%E2%8E%97,%20%E2%8E%98,%20%E2%8C%98,%20%E2%8E%99,%20%E2%8E%9A,%20%E2%8C%A5,%20%E2%8C%A6,%20%E2%99%A8,%20%E2%8C%A8,%20%E2%99%A9,%20%E2%99%AA,%20%E2%99%AB,%20%E2%8C%AB,%20%E2%99%AC,%20%E2%99%AD,%20%E2%99%AE,%20%E2%99%AF,%20%EF%A3%BF.%20App%20Name%20can%E2%80%99t%20be%20longer%20than%2050%20characters.%20Name%20can%E2%80%99t%20contain%20the%20following%20character(s):%20%E2%9A%84,%20%E2%9A%85,%20%E2%9A%86,%20%E2%9A%87,%20%E2%8E%87,%20%E2%9A%88,%20%E2%9A%89,%20%E2%8F%8F,%20%E2%8E%97,%20%E2%8E%98,%20%E2%8C%98,%20%E2%8E%99,%20%E2%8E%9A,%20%E2%8C%A5,%20%E2%8C%A6,%20%E2%99%A8,%20%E2%8C%A8,%20%E2%99%A9,%20%E2%99%AA,%20%E2%99%AB,%20%E2%8C%AB,%20%E2%99%AC,%20%E2%99%AD,%20%E2%99%AE,%20%E2%99%AF,%20%EF%A3%BF.%20App%20Name%20can%E2%80%99t%20be%20longer%20than%2050%20characters.+repo:fastlane/fastlane
ERROR [2017-09-12 16:14:16.61]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
/Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/spaceship/lib/spaceship/tunes/tunes_client.rb:176:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	Name can’t contain the following character(s): ⚄, ⚅, ⚆, ⚇, ⎇, ⚈, ⚉, ⏏, ⎗, ⎘, ⌘, ⎙, ⎚, ⌥, ⌦, ♨, ⌨, ♩, ♪, ♫, ⌫, ♬, ♭, ♮, ♯, . App Name can’t be longer than 50 characters. Name can’t contain the following character(s): ⚄, ⚅, ⚆, ⚇, ⎇, ⚈, ⚉, ⏏, ⎗, ⎘, ⌘, ⎙, ⎚, ⌥, ⌦, ♨, ⌨, ♩, ♪, ♫, ⌫, ♬, ♭, ♮, ♯, . App Name can’t be longer than 50 characters.
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/spaceship/lib/spaceship/tunes/tunes_client.rb:208:in `update_app_details!'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/spaceship/lib/spaceship/tunes/app_details.rb:79:in `save!'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/deliver/lib/deliver/upload_metadata.rb:127:in `upload'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/deliver/lib/deliver/runner.rb:108:in `upload_metadata'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/deliver/lib/deliver/runner.rb:26:in `run'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/deliver/lib/deliver/commands_generator.rb:173:in `run'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/jday/.rvm/gems/ruby-2.4.1/gems/fastlane-2.55.0/bin/fastlane:20:in `<top (required)>'
	from /Users/jday/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/jday/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
```

Will that work?
