### ISSUE TITLE
[deliver] html preview doesn't include content from privacy_url.txt 

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10270]
`fastlane deliver init` creates a `privacy_url.txt`. `fastlane deliver` also sets this privacy URL in the iTunes Connect interface for your app. But the HTML preview you can review before uploading the metadata doesn't show the value of this file.

If there is no good reason why this is, the privacy URL should also be output.

**Comment by janpio** [comment]
Let's see if I can figure the code behind this out:

Template for preview lives here: https://github.com/fastlane/fastlane/blob/master/deliver/lib/assets/summary.html.erb
File is rendered here: https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/html_generator.rb#L33-L50
(privacy_url would probably be part of `options` I guess)
HtmlGenerator is called here: https://github.com/fastlane/fastlane/blob/256e6e370685cbbf2ac2072ab9d836c75205fc3b/deliver/lib/deliver/runner.rb#L115
Which is called here: https://github.com/fastlane/fastlane/blob/256e6e370685cbbf2ac2072ab9d836c75205fc3b/deliver/lib/deliver/runner.rb#L59
Following the breadcrumbs I somehow end up here:
https://github.com/fastlane/fastlane/blob/256e6e370685cbbf2ac2072ab9d836c75205fc3b/deliver/lib/deliver/upload_metadata.rb#L11

Which, to me, means that privacy_url should be available similar to marketing_url in the template and should just be output the same way.

Correct? If so, I can submit a PR on this.

**Comment by KrauseFx** [comment]
Ah interesting, so the upload works, but you were surprised that the privacy URL isn't visible on the HTML report? I guess that's because you rarely change your URL, as opposed to screenshots or metadata

**Comment by janpio** [comment]
Yes, I expected the preview to display _all_ metadata so I can check if I filled all the files. Question is how the feature was intended to work...

**Comment by KrauseFx** [comment]
Uh, not sure if we really need all metadata to be honest, but yah, we could easily do that, check out the `deliver/html_generator.rb` file for the implementation 👍

**Comment by KrauseFx** [comment]
Uh yah, in the beginning it was just screenshots & app description + title, and nowadays it does more. I'd be ok with it showing all the metadata it is going to upload :)

**Comment by janpio** [comment]
On my todo.
