### ISSUE TITLE
[supply] init could create required images

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10273]
Seems `icon.png` and `featureGraphic.png` in `fastlane/metadata/android/xx-XX/images/` are actually needed for the app to be published. Wouldn't it make sense to create them as empty 0 byte images when `fastlane supply init` is executed and creates all the empty .txt files locally?

It already tries to download them:
```
[19:02:02]: Downloading icon for en-US...
[19:02:02]: Downloading promoGraphic for en-US...
[19:02:02]: Downloading tvBanner for en-US...
```
but as they of course don't exist on new apps, they just seem to be skipped.

(Caution: If this gets changes, the upload process might have to check for empty/0 byte files and skip those depending on how Play Console API handles empty files)

**Comment by KrauseFx** [comment]
Oh interesting, do you mind submitting a PR for this? :)

**Comment by janpio** [comment]
I can try (after I fix the other PR that I seem to have messed up 😃 )

**Comment by KrauseFx** [comment]
Sounds great 👍 Thanks @janpio

**Comment by janpio** [comment]
On my todo.
