### ISSUE TITLE
[precheck] run before uploading metadata?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10271]
Right now `precheck` is run by `fastlane deliver` only after the metadata is uploaded to the App Store. It would be quite practical to be able to use `precheck` on the local metadata before uploading.

Is this just the way `precheck` is built or could this be done somehow?

**Comment by taquitos** [comment]
_precheck_ is built to pull from the source of truth (ITC). We considered reading metadata locally, but decided that sticking with the source of truth was the best move for the V1. I think it would be a great addition to check all the metadata locally instead of ITC as an option 👍

**Comment by janpio** [comment]
Nah, would be a great feature.
