### ISSUE TITLE
[Scan] Multiple devices produce an empty reports file

### ISSUE THREAD

**Issue by raulriera** [fastlane/fastlane#10276]
When using the new multiple devices options, the reports folder just have an empty reports html and junit. If I just test for one device then the reports are back.

Do we need another argument when using more than one device in the `devices` argument?

## Multiple devices
![screen shot 2017-09-06 at 3 58 05 pm](https://user-images.githubusercontent.com/24159/30131896-6ac4e084-931c-11e7-93c0-21133e7f5ea9.png)

## One device
![screen shot 2017-09-06 at 3 58 11 pm](https://user-images.githubusercontent.com/24159/30131885-634bb4ae-931c-11e7-894d-2af7867dfe2a.png)

Code looks like this

```ruby
project: IOS_PROJECT_PATH,
scheme: "SnapshotTests",
devices: options[:devices], # this line, when using more than one device it fails to give a report
xcargs: "SNAPSHOT_RECORD_MODE=#{options[:record]}",
output_directory: "#{IOS_REPORT_FOLDER}/#{options[:platform]}",
buildlog_path: "#{IOS_REPORT_FOLDER}/#{options[:platform]}",
skip_build: true
```

**Comment by raulriera** [comment]
Possibly just this https://github.com/supermarin/xcpretty/issues/295

**Comment by KrauseFx** [comment]
Yep, should be followed-up on on https://github.com/supermarin/xcpretty/issues/295 👍 Thanks for reporting
