### ISSUE TITLE
Docs confusion: `testflight` vs `pilot`

### ISSUE THREAD

**Issue by clozach** [fastlane/fastlane#10274]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The first sample code given in the docs, both [here](https://github.com/fastlane/fastlane) and [here](https://docs.fastlane.tools) use the `testflight` action, but there is no `testflight` tool listed [here](https://github.com/fastlane/fastlane#fastlane-toolchain) nor [here](https://fastlane.tools). In addition, there seem to be two other methods for uploading builds: `deliver` and `pilot`. This makes it quite daunting trying to figure out the canonically correct way to use fastlane for build uploads.

On a more general note, the onboarding process feels very fragmented. It can feel like a wild goose chase trying to figure out the "right" docs to reference. fastlane.tools links to github, which links right back to fastlane.tools, to docs.fastlane.tools, to various sub-repo README's, and to the code signing guide. But, assuming you don't have plans to massively reorganize the docs with a clearly-delineated tutorial with maybe a section explaining how the project is organized, please take a look at the `testflight`/`pilot` issue described above. :)

**Comment by KrauseFx** [comment]
Hey @clozach, thanks for the feedback, we're well aware of the confusion, and we're working on moving everything to docs.fastlane.tools, e.g. with https://github.com/fastlane/fastlane/pull/10209 👍
