### ISSUE TITLE
Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by Jef-Jkn** [fastlane/fastlane#10279]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After reading all other issues and trying what they dit i still get this error message 'Connection reset by peer - SSL_connect'. I do use Fastlane match development.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
12:39:46]: Fetching certificates and profiles...
[12:40:03]: -----------------------------------------------------------------------
[12:40:03]: Connection reset by peer - SSL_connect
[12:40:03]: 
[12:40:03]: SSL errors can be caused by various components on your local machine.
[12:40:03]: Apple has recently changed their servers to require TLS 1.2, which may
[12:40:03]: not be available to your system installed Ruby (2.0.0)
[12:40:03]: 
[12:40:03]: The best solution is to use the self-contained fastlane version.
[12:40:03]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
[12:40:03]:  - Use Homebrew
[12:40:03]:     - update brew with `brew update`
[12:40:03]:     - install fastlane using:
[12:40:03]:       - `brew cask install fastlane`
[12:40:03]:  - Use One-Click-Installer:
[12:40:03]:     - download fastlane at https://download.fastlane.tools
[12:40:03]:     - extract the archive and double click the `install`
[12:40:03]: -----------------------------------------------------------
[12:40:03]: for more details on ways to install fastlane please refer the documentation:
[12:40:03]: -----------------------------------------------------------
[12:40:03]:         🚀       https://docs.fastlane.tools          🚀   
[12:40:03]: -----------------------------------------------------------
[12:40:03]: 
[12:40:03]: You can also install a new version of Ruby
[12:40:03]: 
[12:40:03]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
[12:40:03]: - If you use system Ruby:
[12:40:03]:   - Run `brew update && brew install ruby`
[12:40:03]: - If you use rbenv with ruby-build:
[12:40:03]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
[12:40:03]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
[12:40:03]: - If you use rvm:
[12:40:03]:   - First run `rvm osx-ssl-certs update all`
[12:40:03]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
[12:40:03]: 
[12:40:03]: If that doesn't fix your issue, please google for the following error message:
[12:40:03]:   'Connection reset by peer - SSL_connect'
[12:40:03]: -----------------------------------------------------------------------

[!] Connection reset by peer - SSL_connect

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F2073)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Booqit") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Booqit") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.planning.booqit" # The bundle identifier of your app
apple_id "jef.jkn@gmail.com" # Your Apple email address

team_id "86GH485AXL" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
</details>

*generated on:* **2017-09-07**
</details>

Looking for related GitHub issues on fastlane/fastlane...

➡️  Pilot reported "invalid byte sequence in US-ASCII" after token expiration
    https://github.com/fastlane/fastlane/issues/9689 [closed] 6 💬
    5 weeks ago

➡️  Invalid byte sequence with invalid strings file
    https://github.com/fastlane/fastlane/issues/7661 [closed] 8 💬
    01 Jun 2017

➡️  invalid byte sequence in UTF-8
    https://github.com/fastlane/fastlane/issues/7850 [closed] 11 💬
    13 Apr 2017

and 23 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
        from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:730:in `format_statement'
        from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:621:in `say'
        from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:261:in `ask'
        from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:109:in `confirm'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane/lib/fastlane/environment_printer.rb:12:in `output'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane/lib/fastlane/commands_generator.rb:233:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

**Comment by KrauseFx** [comment]
```
[12:40:03]: You can also install a new version of Ruby
[12:40:03]:
[12:40:03]: - Make sure OpenSSL is installed with Homebrew: brew update && brew upgrade openssl
[12:40:03]: - If you use system Ruby:
[12:40:03]: - Run brew update && brew install ruby
[12:40:03]: - If you use rbenv with ruby-build:
[12:40:03]: - Run brew update && brew upgrade ruby-build && rbenv install 2.3.1
[12:40:03]: - Run rbenv global 2.3.1 to make it the new global default Ruby version
[12:40:03]: - If you use rvm:
[12:40:03]: - First run rvm osx-ssl-certs update all
[12:40:03]: - Then run rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local
[12:40:03]:
[12:40:03]: If that doesn't fix your issue, please google for the following error message:
[12:40:03]: 'Connection reset by peer - SSL_connect'
```

**Comment by corneliu-serediuc** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'time'
require 'commander'
require 'pathname'

fastlane_version "1.105.0"

# Constants
APPLICAITON_IDENTIFIER = "com.ghuntley.fastlanelecture"
ITUNES_CONNECT_TEAM_ID = "J98S49XE45"
ITUNES_CONNECT_USERNAME = "ghuntley@ghuntley.com"
GOOGLE_PLAY_JSON_KEY = "~/Desktop/google-play-account-secret.json"

desc "Displays the commits between working tree and the last beta/release tag"
lane :changelog do |options|
  tag = options[:tag]

  puts_changelog(tag: last_release)
  puts_changelog(tag: last_beta)

end

desc "Fetches the distribution certificates and provisioning profiles to compile the app for development & distribution"
lane :certificates do

  match(type: "appstore", readonly: true, force: false, app_identifier: APPLICAITON_IDENTIFIER, team_id: ITUNES_CONNECT_TEAM_ID, username: ITUNES_CONNECT_USERNAME)
  match(type: "development", readonly: true, force: false, app_identifier: APPLICAITON_IDENTIFIER, team_id: ITUNES_CONNECT_TEAM_ID, username: ITUNES_CONNECT_USERNAME)

end

desc "Build production and debug build"
lane :build do
  
  changelog
  certificates

  sh("cd ..; ./build.sh")
end


desc "Submit a new version to iTunes Connect and Google Play"
desc ""
desc "If on master; it will do the following: "
desc "- Displays the commits between working tree and the last beta/release tag"
desc "- Fetches distribution certificates and provisioning profiles"
desc "- Upload screenshots + app metadata"
desc "- Build, sign and upload the app release"
desc "- Do a build version bump and push it"
desc "The application will *not* be submitted for review or automatically released"
desc ""
desc "If on develop; it will do the following: "
desc "- Displays the commits between working tree and the last beta/release tag"
desc "- Make sure the profiles are up to date and download the latest one"
desc "- Do a build version bump and push it"
desc "- Build, sign and upload the app for testing"
desc "The application will *not* be submitted for review or automatically released to external testers"
desc ""
lane :deploy do

  puts case git_branch
  when "master", "release"

    # slack(
    #   message: "App Store build incoming",
    #   channel: "#mobile",
    #   default_payloads: [:git_author]
    # )

    build

    tag_release

    deploy_itunesconnect
    deploy_googleplay

    metadata
    screenshots

  when "develop", "beta"
    
    build

    tag_beta

    devices

    deploy_itunesconnect
    deploy_googleplay

  else
    # failure
  end

end

private_lane :deploy_itunesconnect do

  ipa = "./artifacts/apple/release/FastlaneLecture.App.iOS.ipa"

  sigh(
    adhoc: true,
    force: true,
    filename: APPLICAITON_IDENTIFIER + ".mobileprovision",
    app_identifier: APPLICAITON_IDENTIFIER, 
    team_id: ITUNES_CONNECT_TEAM_ID, 
    username: ITUNES_CONNECT_USERNAME
  )

  resign(
    ipa: ipa,
    signing_identity: "iPhone Distribution: Geoffrey Huntley (J98S49XE45)",
  )

  puts case git_branch
  when "master", "release"

    deliver(
      metadata_path: "metadata/itunes-connect",
      force: true,
      ipa: ipa,
      skip_screenshots: true,
      skip_metadata: true,
      automatic_release: false,
      submit_for_review: false,
    )

  when "develop", "beta"
    
    pilot(
      ipa: ipa,
      app_identifier: APPLICAITON_IDENTIFIER,
      username: ITUNES_CONNECT_USERNAME,
      team_id: ITUNES_CONNECT_TEAM_ID,
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )

  else
    # failure
  end

  # slack_message(message: "New version of the app successfully deployed to iTunes Connect! :tada: :tada:", success: true, payload: {})

end

lane :deploy_googleplay do

  apk = "artifacts/android/release/com.ghuntley.fastlanelecture-Signed.apk"
  
  supply(
    json_key: GOOGLE_PLAY_JSON_KEY,
    package_name: APPLICAITON_IDENTIFIER,
    apk: apk,
    track: "beta",
    metadata_path: "metadata/google-play",
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )

  # slack_message(message: "New version of the app successfully deployed to iTunes Connect! :tada: :tada:", success: true, payload: {})

end

desc "Registers developer devices with iTunes Connect"
lane :devices do

  register_devices(devices_file: "./Fastlane/iTunesConnectDevices", username: ITUNES_CONNECT_USERNAME , team_id: ITUNES_CONNECT_TEAM_ID)

end

desc "Upload application metadata to iTunes Connect and Google Play"
lane :metadata do

  metadata_itunesconnect
  metadata_googleplay

end

private_lane :metadata_itunesconnect do

  deliver(
    metadata_path: "metadata/itunes-connect",
    force: true,
    skip_binary_upload: true,
    skip_screenshots: true,
    skip_metadata: false,
    automatic_release: false,
    submit_for_review: false
  )

end

private_lane :metadata_googleplay do

  supply(
    json_key: GOOGLE_PLAY_JSON_KEY,
    package_name: APPLICAITON_IDENTIFIER,
    metadata_path: "metadata/google-play",
    skip_upload_metadata: false,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )

end

desc "Upload application screenshots to iTunes Connect and Google Play"
lane :screenshots do

  screenshots_itunesconnect
  screenshots_googleplay

end

private_lane :screenshots_itunesconnect do

  deliver(
    metadata_path: "metadata/itunes-connect",
    screenshots_path: "metadata/itunes-connect/screenshots",
    force: true,
    skip_binary_upload: true,
    skip_screenshots: false,
    skip_metadata: true,
    automatic_release: false,
    submit_for_review: false
  )

end

private_lane :screenshots_googleplay do

  supply(
    json_key: GOOGLE_PLAY_JSON_KEY,
    package_name: APPLICAITON_IDENTIFIER,
    metadata_path: "metadata/google-play",
    skip_upload_metadata: true,
    skip_upload_images: false,
    skip_upload_screenshots: false
  )

end

private_lane :puts_changelog do |options|
  tag = options[:tag]

  puts compare_url(tag: tag)

  puts changelog_from_git_commits(
    between: [tag, "HEAD"], 
    pretty: "- (%ae) %s",
    match_lightweight_tag: false,
    include_merges: false 
  )

end

desc "Push the build to the beta branch and tag the build"
private_lane :tag_beta do |options|

  tag_name = "betas/#{build_version}"

  sh("git fetch")
  sh("git stash")
  sh("git checkout")
  sh("git pull origin develop")
  sh("git checkout beta")
  sh("git merge develop")
  sh("git stash apply")

  push_to_git_remote(
      local_branch: 'beta', 
      remote_branch: 'beta'
  )

  add_git_tag(tag: tag_name)
  sh("git push origin --tags")

end

desc "Push the build to the release branch and tag the build"
private_lane :tag_release do |options|
  tag_name = "releases/#{build_version}"

  sh("git fetch")
  sh("git stash")
  sh("git checkout")
  sh("git pull origin release")
  sh("git checkout master")
  sh("git merge release")
  sh("git stash apply")

  push_to_git_remote(
      local_branch: 'release',  
      remote_branch: 'release'
  )

  add_git_tag(tag: tag_name)
  sh("git push origin --tags")

end

private_lane :slack_message do |options|
  message = options[:message]
  success = options[:success]
  payload = options[:payload]

  slack(
    message: message,
    channel: "#mobile",
    success: success,
    payload: payload)
end

after_all do |lane|
  ship_it
  notify("Lane #{lane} completed successfully!")
end

error do |lane, exception|
  puts "\n(╯°□°）╯︵ ┻━┻\n".red
  notify("Lane #{lane} failed to complete")
end

# Helper functions
def build_version
  return sh("grep AssemblyInformationalVersion ../src/CommonAssemblyInfo.cs | awk -F '\"' '{print $2}'").strip
end

def last_beta
  return sh("git describe origin/develop --match=\"beta*\" --tags --abbrev=0").strip
end

def last_release
  return sh("git describe origin/master --match=\"release*\" --tags --abbrev=0").strip
end

def compare_url(options={})
  tag = options[:tag]
  head = last_git_commit[:abbreviated_commit_hash]
  
  return "https://github.com/ghuntley/appstore-automation-with-fastlane/compare/#{tag}...#{head}"
end

def ship_it
  rand = Random.rand(0..1)
  if rand == 0
    squirrel
  elsif rand == 1
    boat
  end
end

def squirrel
  puts "
    !!!!
  !!!!!!!!
!!!!!!!!!!!   O_O
!!!  !!!!!!! /@ @\\
      !!!!!! \\ x /
      !!!!!!/ m  !m
       !!!!/ __  |
       !!!!|/  \\__
        !!!\\______\\
  "
end

def boat
  puts "
     .  o ..
     o . o o.o
          ...oo
            __[]__
         __|_o_o_o\__
         \\\"\"\"\"\"\"\"\"\"\"/
          \\. ..  . /
     ^^^^^^^^^^^^^^^^^^^^
  "
end
```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
</details>


*generated on:* **2017-09-08**
</details>
