### ISSUE TITLE
WARNING: CFMachPortSetInvalidationCallBack() called on a CFMachPort with a Mach port

### ISSUE THREAD

**Issue by komarekw** [fastlane/fastlane#10289]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi all,

we are using since more than one year our build pipeline and from beginning the upload to crashlytics did not work if the user isn't logged in at the build server (mac mini). Always we got the error:
```
submit[30292:87464] *** WARNING: CFMachPortSetInvalidationCallBack() called on a CFMachPort with a Mach port (0x5d0b) which does not have any send rights. This is not going to work. Callback function: 0x7fff8e0e90bf 
submit Crashlytics: Unable to find application in Crashlytics. Response code: 0 
submit Crashlytics: Does this app belong to this org?
```
If the user is logged in the upload works fine. We are also using this server as an android build server and for that the crashlytics upload works fine as well.

### Environment
<details><summary>`./fastlane/Appfile`</summary>

```ruby
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ? Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-rocket_chat | 0.1.1   | ? Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| slack-notifier              | 1.5.1        |
| CFPropertyList              | 2.3.5        |
| claide                      | 1.0.2        |
| colored2                    | 3.1.2        |
| nanaimo                     | 0.2.3        |
| xcodeproj                   | 1.5.1        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.2.8        |
| terminal-notifier           | 1.8.0        |
| unicode-display_width       | 1.3.0        |
| terminal-table              | 1.8.0        |
| plist                       | 3.3.0        |
| multipart-post              | 2.0.0        |
| word_wrap                   | 1.0.0        |
| public_suffix               | 2.0.5        |
| tty-screen                  | 0.5.0        |
| babosa                      | 1.0.2        |
| colored                     | 1.2          |
| highline                    | 1.7.8        |
| commander-fastlane          | 4.4.5        |
| unf_ext                     | 0.0.7.4      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20170404 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| fastimage                   | 2.1.0        |
| gh_inspector                | 1.0.3        |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| rubyzip                     | 1.2.1        |
| security                    | 0.1.3        |
| xcpretty-travis-formatter   | 0.0.4        |
| dotenv                      | 2.2.1        |
| bundler                     | 1.15.4       |
| uber                        | 0.1.0        |
| declarative                 | 0.0.9        |
| declarative-option          | 0.1.0        |
| representable               | 3.0.4        |
| mime-types-data             | 3.2016.0521  |
| mime-types                  | 3.1          |
| httpclient                  | 2.8.3        |
| google-api-client           | 0.13.5       |
| json                        | 2.1.0        |
| io-console                  | 0.4.5        |
| excon                       | 0.59.0       |
| faraday                     | 0.13.1       |
| little-plugger              | 1.1.4        |
| logging                     | 2.2.2        |
| jwt                         | 1.5.6        |
| memoist                     | 0.16.0       |
| os                          | 0.9.6        |
| signet                      | 0.7.3        |
| googleauth                  | 0.5.3        |
| faraday_middleware          | 0.12.2       |
| rocket-chat-notifier        | 0.1.0        |
| fastlane-plugin-rocket_chat | 0.1.1        |
</details>

*generated on:* **2017-09-08**
</details>

Had someone of you an similar issue or can support me here?

Thx,
Werner

**Comment by KrauseFx** [comment]
Are you using the right API key for the right org?

**Comment by komarekw** [comment]
Hi,
yes. I checked it several times.  

Thanks,
Werner

**Comment by berliozzz** [comment]
Have you solved this problem?

**Comment by komarekw** [comment]
Hi @berliozzz 

yes I solved the issue. In our case we had the issue, because we are behind a proxy. I've added the proxy crendentials in the crashlytics_helper.rb to the Java command.

Like this one:

`command = ["java"]
command << "-Dhttp.proxyHost=MyproxyHost.com"
command << "-Dhttp.proxyPort=Myproxyport"
command << "-Dhttp.proxyUser=Myproxyuser"
command << "-Dhttp.proxyPassword=Myproxypassword"
command << "-Dhttps.proxyHost=MyproxyHost.com"
command << "-Dhttps.proxyPort=Myproxyport"
command << "-Dhttps.proxyUser=Myproxyuser"
command << "-Dhttps.proxyPassword=Myproxypassword"
command << "-jar #{File.expand_path(params[:crashlytics_path])}"
command << "-androidRes ."`


I hope this will solve your problem as well.

BR,
Werner
