### ISSUE TITLE
Suggestion: Sentry report 

### ISSUE THREAD

**Issue by OlegAnghelov** [fastlane/fastlane#1028]
Hi!

Tried to run a lane with fastlane, and got this:
```
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '20c76181af4398956fa3ceaf96f4aed8'
The crash report has been stored locally '/tmp/sentry_20c76181af4398956fa3ceaf96f4aed8.json'
```

This messages suggests that it's an internal problem, but because I am really new to fastlane, i was sure that it's me who broke smth.
I took a peek into the `sentry.json` file and saw this:
```
  "message": "RuntimeError: \u001b[31mSyntax error in your Fastfile on line 21: Fastfile:21: syntax error, unexpected ':', expecting keyword_end\n    force: true\n          ^\u001b[0m",
```

And this is of course my fault.
But in this situation, where the issue is the nooby-programmer who's misusing fastlane syntax, why it's not showing this error, like "hey, dude, fix the syntax", but "oops, we have a crash, please report"?
Or if it's impossible to detect the "source" of the crash, to at least say "hey, here is the error message, can YOU do smth about it first?"
I hope I made my point clear, and hope this helps :)

Thanks for your great work!

**Comment by KrauseFx** [comment]
Thanks, that's great feedback! I'm actually working on this right now with https://github.com/fastlane/fastlane/pull/1007/files#diff-62449fd0547beb66f9c4a5149ebb1317R52

I'll close this issue for now, as this change will be in one of the next releases. Please feel free to submit more feedback, it's very valuable to improve fastlane :rocket:
