### ISSUE TITLE
fastlane init: both iOS and Android in same project?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10280]
I would very like to be able to type some commands to create a `Fastfile` with lanes for iOS and Android, also having `package_name` and `app_identifier` both created. This would be useful for projects that have both a iOS and Android app like Cordova projects.

Right now you have to choose if this is an iOS application or not on `fastlane init`. When the files already exist you can't call it again as far as I know and have to create some stuff manually.

Is there a way to create the file structure and entries for both iOS and Android in the same project?

**Comment by KrauseFx** [comment]
Sorry, right now you'll have to init per platform, and manually merge those Fastfile's to whatever you want to do with it :)

**Comment by janpio** [comment]
Ok, at least I didn't miss it.

Would you be interested in having enabled/implemented this somehow?

**Comment by KrauseFx** [comment]
Not sure how this could work, how do you know you want to create one for both platforms?

**Comment by janpio** [comment]
Hmm, several ideas:

a) Replace the "Is this project an iOS project?" prompt with a multi selection: 
```
What kind of project is this? 
1) iOS 
2) Android 
3) both
```
(No idea if this concept already exists anywhere in Fastlane though.)

b) Add a parameter that skips the `fastlane is already set up at path` test in setup.rb and allows so the second run to add to the files instead of creating them.

c) New `is_cordova` check in setup.rb that checks for existence of `config.xml` (or other file fingerprints I can think of, maybe also something like what already exists for reactive native) in the directory `fastlane init` is executed.

I like option c) best.

**Comment by KrauseFx** [comment]
Mh, I'd favor on leaving it as is for now, maybe we can have more optimized setups for react native and other cross platform apps, but usually iOS and Android code bases are separated

**Comment by tabrindle** [comment]
Multiplatform setup is perhaps something I think we should look into, given how popular react native and Cordova are and that `fastlane init` definitely does not support this right now. I imagine this change would not be trivial, however if you want to take a stab at it, I'm sure @KrauseFx would appreciate a PR, assuming it does not impact the average user. 

That being said, it is possible to merge them manually, as that's what my team does for all of our hybrid (React Native and Cordova) projects. Given how easy this is, I'm not sure a change to init is worth it. You can see an example of this working [here](https://github.com/fastlane/examples/tree/master/Shop.com).

**Comment by janpio** [comment]
Thanks, I have this working as well (let `init` do the iOS stuff, add Android things manually to the two files) but am currently writing a tutorial on how you, the average user, can do this yourself (instead of just copy/pasting examples you don't really understand) - and there having a "both" option or the Cordova project recognized automatically could really improve the workflow.

If I have the time I will look into `is_cordova` and its implications...

**Comment by janpio** [comment]
Note to myself: Templates for default Fastfiles are here: https://github.com/fastlane/fastlane/tree/51c005ab134b396df73e43403616cbe6adce4c27/fastlane/lib/assets
