### ISSUE TITLE
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD is ignored and requesting FASTLANE_PASSWORD for 2FA enabled accounts in CI environment

### ISSUE THREAD

**Issue by sharat** [fastlane/fastlane#10299]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane ignores `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` and requesting for `FASTLANE_PASSWORD` which eventually ask for 6-digit code in CI environment during `pilot` action.

Expected to process Application Specific Password as the primary authentication mechanism to `pilot`

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.5                                           |
| Ruby                        | 2.3.4                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.11.0 (Apple Git-81)                 |
| Installation Source         | ~/.gem/ruby/2.3.4/bin/fastlane                    |
| Host                        | Mac OS X 10.12.5 (16F73)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.4/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-8.3.3.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                             |

### System Locale

| Error                        |
| ---------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.53.1"

default_platform :ios

platform :ios do


  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    cocoapods
    gym(workspace: "project.xcworkspace",
        scheme: "project",
        configuration: "Release")
    pilot
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| faraday_middleware        | 0.12.2       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| bundler                   | 1.15.4       |
</details>

*generated on:* **2017-09-10**
</details>

**Comment by KrauseFx** [comment]
Could you share the complete output when running _fastlane_?

**Comment by KrauseFx** [comment]
Oh, right, the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` can only be used by the iTunes Transporter, you'll still have to provide the password + the 2 factor SMS code to use iTunes Connect and the Apple Dev Portal

**Comment by sharat** [comment]
@KrauseFx 

See the screenshots attached

My beta lane is simple and default. Just `gym` and `pilot`. It works well in a local machine because my keychain has credentials and app specific password will be automatically taken. In the CI, this is not available. Hence it prompts me for 6 digit code. I tried removing `FASTLANE_USER` and `FASTLANE_PASSWORD` to see if it can work with `PILOT_USER` and `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` but it did not work. What's the best way to handle this in CI environment if 2FA is enabled? Temporarily I created a separate user for CI and added to iTunes Connect to push the build.

```
[08:58:51]: Successfully exported and compressed dSYM file
[08:58:51]: Successfully exported and signed the ipa file:
[08:58:51]: /Users/distiller/project/project.ipa
[08:58:51]: -------------------
[08:58:51]: --- Step: pilot ---
[08:58:51]: -------------------
[08:58:51]: Login to iTunes Connect (myemail@gmail.com)
Two Factor Authentication for account 'myemail@gmail.com' is enabled
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: 
```

**Comment by KrauseFx** [comment]
Yeah, separate user always works great. Check out https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth also 👍

**Comment by getaaron** [comment]
To clarify for future readers, as of early 2019:

- `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is currently only supported for uploading binaries ([see source code](https://github.com/fastlane/fastlane/search?q=FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD&unscoped_q=FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD))
- For other work like changing metadata, generating provisioning profiles, etc., your choices are:
  1. Do it locally with a 2FA-enabled account
  2. Do it on CI with a non-2FA-enabled account that doesn't have _Account Holder_ permission

https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth has more information
