### ISSUE TITLE
show upload progress for hockey app crashlytics

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#10292]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Feature request to show upload progress when uploading files to hockey app or crashlytics. 

Thanks.

**Comment by romk1n** [comment]
Someone ?

**Comment by ohayon** [comment]
Hey @romk1n, thanks for the feature request, is there any chance you would want to submit a PR for this? We would love to review a change with this feature added! Let us know if there is any way we can help! 🚀

**Comment by romk1n** [comment]
I don’t know ruby well enough for this otherwise I would have done it by now. Thanks. 

--

**Comment by ohayon** [comment]
We would be happy to help you work through that! Although I dont believe we have any progress indicators in other actions at the moment, so I'm not sure that there is a good example to follow within fastlane, but if you wanted to try it out here is the file for that https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb

I am going to close this for now and it's marked as a feature request so we will se it when we come back in to see what features the community is wanting. Thanks!! 🐙
