### ISSUE TITLE
Primarily Child-Directed option

### ISSUE THREAD

**Issue by Anthony-SF** [fastlane/fastlane#10295]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Google recently added a required option to select for updating apps. Primarily Child-Directed. We cannot update our apps with Fastlane without setting this option. Is there plans to add this in Fastlane, or if it is already an option can you direct me to the documentation for adding it? I have been searching for a while and All I could find on it was a closed ticket from a year ago saying it is not supported. Thanks

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[!] Google Api Error: noPrimarilyChildDirectedStatus: You are required to indicate if your app is primarily directed towards children in the pricing and distribution section of the Play Console.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | debian_based stretch/sid                                     |
| Ruby                        | 2.3.1                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.7.4                                            |
| Installation Source         | /usr/local/bin/fastlane                                      |
| Host                        | Ubuntu 16.04.2 LTS debian_based stretch/sid (4.4.0-1031-aws) |
| Ruby Lib Dir                | /usr/lib                                                     |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                   |
| Is contained                | false                                                        |
| Is homebrew                 | false                                                        |
| Is installed via Fabric.app | false                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2017-09-08**
</details>

**Comment by andreaskeller** [comment]
I think you only need to check this once in the [Google Play Console](https://play.google.com/apps/publish) under Store presence - Pricing & distribution - Primarily Child-Directed.

**Comment by ohayon** [comment]
Thanks for chiming in @andreaskeller ! @Anthony-SF, let us know if you are still having issues with this based on @andreaskeller's answer! Thanks! 🚀

**Comment by svanzoest** [comment]
I think it would be great if we could have this automated, but I am unclear if these types of options are exposed in the Google Play Publishing API.

**Comment by patrickbussmann** [comment]
I have the same issue.

```
Validating edit
Failed to validate edit, error: googleapi: Error 403: You are required to indicate if your app is primarily directed towards children in the pricing and distribution section of the Play Console., noPrimarilyChildDirectedStatus
```

After update the children option under pricing section - as @andreaskeller said - I was able to deploy 👍 
Thank you.
