### ISSUE TITLE
Spaceship: Add function to post review on an app rating

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#10291]
This is a feature request. It would be nice to have a function in `spaceship` to add a developer response to a user review on an app. In future it will be also nice to have a 'edit response' and 'delete response' features.

I have already completed the implementation for this. Will create PR soon. Really fun to work with `spaceship` development. 👍

**Comment by KrauseFx** [comment]
Hey @RishabhTayal, thanks for the idea and thanks for preparing a PR. We've actually already had a PR for this with https://github.com/fastlane/fastlane/pull/9036 by @hjanuschka and decided not to go ahead with it, as it's going to be abused by developers. I'll close the PR for now, as it's not something we want to have in the fastlane code base for now 👍

**Comment by RishabhTayal** [comment]
😢

**Comment by RishabhTayal** [comment]
@KrauseFx I understand your concern about adding this feature to the `fastlane` code base. However I still want to you this method using `spaceship`. I maintaining a feature branch in my forked repo which contains this feature. Is there a way for me to point my projects `Gemfile` to this feature branch in my forked `fastlane` repo?
