### ISSUE TITLE
gradle command handles some standard Android tasks incorrectly

### ISSUE THREAD

**Issue by y-a-n-n** [fastlane/fastlane#10301]
### New Issue Checklist

- ✅ Updated fastlane to the latest version
- ✅ I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- ✅ I read [docs.fastlane.tools](https://docs.fastlane.tools)
- ✅ I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have an android product with multiple product flavors defined in my build.gradle file.
I am executing tests and creating screenshots via fastlane for each product flavor.
In order to do so, I need to run the standard assembleAndroidTest gradle task for each flavor individually.
In order to do this, my lane has the following code:

`gradle(
			task: "assembleAndroidTest",
			build_type: "Debug",
			flavor: "Flavor1"
		)`

This results in fastlane invoking `gradle assembleAndroidTestFlavor1Debug`, when in fact the correct gradle task is called `assembleFlavor1DebugAndroidTest`. In this case, simply appending the flavor and build type to the end of the gradle task name causes an invalid gradle task to be invoked.

Confusingly, other standard gradle tasks work correctly; i.e. 

`gradle(
			task: "assemble",
			build_type: "Debug",
			flavor: "Flavor1"
		)`

correctly invokes `gradle assembleFlavor1Debug`

The workaround is fairly simple: I just manually construct a string to pass as the `task` argument to the gradle command and leave out the other two arguments. It would be nice, however, if fastlane handled standard android gradle tasks correctly when `build_type` and `flavor` are specified.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

`FAILURE: Build failed with an exception.`
`Task 'assembleAndroidTestFlavor1Debug' not found in root project 'MyApplication'.`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.6                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.3 (Apple Git-91)                |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.6 (16G29)                         |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
</details>

*generated on:* **2017-09-11**
</details>

**Comment by Fosile** [comment]
Since today i discover a similar Problem, last Week everything worked fine.

This is not working anymore:
```
 gradle(task: "clean")

      gradle(
          task: 'assemble',
          build_type: 'release',
          flavor: options[:appName]
      )
```

**Comment by ohayon** [comment]
Thanks for the update @Fosile ! @y-a-n-n could you see if that works for you too? 🐙 🚀

**Comment by y-a-n-n** [comment]
@ohayon: No, that definitely doesn't solve my problem. @Fosile 's problem was not the same as mine. The gradle command works fine for me; the issue is the way that fastlane actually constructs the name of the gradle task from the build_type and flavor parameters.

To reiterate:
There is a standard Android gradle task called `assembleAndroidTest`. 
For each build flavor defined in the build.gradle file, there is a gradle task called `assemble[flavor][build_type]AndroidTest` 
However, when I call `gradle( task: "assembleAndroidTest", build_type: "Debug", flavor: "Flavor1" )` in a lane, fastlane invokes `assembleAndroidTest[flavor][build_type]`, which is not a valid gradle task.

It looks like fastlane just appends the flavor and build type strings on the end of the task name, which is not the correct behaviour for certain standard android tasks.

Again, the workaround is fairly simple, and the solution would probably involve checking for special cases within around line 19 of gradle.rb, as it currently does this:

` gradle_task = [task, flavor, build_type].join`

**Comment by ohayon** [comment]
Ahh, thanks for the clarification @y-a-n-n! Is there any chance you would want to submit a PR to fix this problem on master? That would be 💯 ! 🏎
