### ISSUE TITLE
Call fastlane in ruby

### ISSUE THREAD

**Issue by saitjr** [fastlane/fastlane#10311]
Is there any way to call fastlane in ruby directly?

such as `match`, I have to write like this:

```ruby
Match::Runner.new.run(
  git_url: git_cer_repo,
  type: match_model.type,
  readonly: true,
  verbose: false,
  app_identifier: bundle_id,
  git_branch: match_model.branch,
  team_id: match_model.team_id,
  team_name: match_model.team_name,
  keychain_name: "login.keychain",
  platform: "ios"
)
```

But this method doesn't have any return value, all provision informations is included in ENV. And there is no easy way to call `gym`, so I have to use Fastfile 😭😭😭😭😭:

```ruby
system("fastlane package params")
```

**Comment by KrauseFx** [comment]
You can, but it's not recommended, check out `cli_distributor` in fastlane. Again, I would recommend against it, instead please use multiple lanes, as you can call other lanes from within a lane. Let us know what you want to do, so we can have a better understanding of the use-case :)

**Comment by saitjr** [comment]
Thank you for your reply 😀.

We have a huge workflow:
```
match -> modify project (8 projects at least) -> gym -> match -> resign -> pilot -> upload to our own servers (3 servers at least)
```
And each step may raise an error, and I want to cache these errors at command's entrance, not every fastfile's error lane.

Is there any great idea ?

**Comment by ohayon** [comment]
Hey @saitjr is that something you might be able to do in a `before_each` and/or `after_each` block in a Fastfile? https://docs.fastlane.tools/advanced/ 🚀

**Comment by saitjr** [comment]
I thought about this actually, but this could lead to a large Fastfile. Cause I have to parse project informations before fastlane command not only before lane (such as find dir of .xcodeproj, and copy/paste Fastfile into the dir. After this step, chdir and run fastlane command).

**Comment by ohayon** [comment]
Yeah, I can understand that it is not totally ideal. Maybe its something that you could implement in a [_fastlane_ plugin](https://docs.fastlane.tools/plugins/create-plugin/)?

**Comment by saitjr** [comment]
Wow, that's cool, I'll try it. Thank you very much.

**Comment by Sulfkain** [comment]
@saitjr Maybe you could call other scripts (ruby scripts for ex. ) on that lane, to make Fastfile cleaner.
Even on our project we have splitted the Fastfile on various files.
You just need to use `import 'your path file'`
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#importing-another-fastfile

Hope this helps!

**Comment by saitjr** [comment]
Maybe. I'm not sure about the error catching, cause I want to catch them in one place. But I'll try this solution.  Wait for my good news and thank you very much.
