### ISSUE TITLE
Slather command "source-files" is wrong

### ISSUE THREAD

**Issue by Xcode1994** [fastlane/fastlane#10319]
[Slather/Command.rb](https://github.com/SlatherOrg/slather/blob/master/lib/slather/command/coverage_command.rb)

Line 32
You can see `option ["--source-files"], "SOURCE_FILES", "A Dir.glob compatible pattern used to limit the lookup to specific source files. Ignored in gcov mode.", :multivalued => true`

So the option --source-files is Array not String

But in your source code [lib/fastlane/actions/slather.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slather.rb)

Line 240-243
it means you think the option --source-files is string

hope you guys can fix this problem
thank you

**Comment by ohayon** [comment]
Hey @Xcode1994! Thanks for writing in an identifying the fix. Is there any way you would want to submit a PR with that change? We would love to review it! 🚀

**Comment by Xcode1994** [comment]
@ohayon hahahahahhhh, I am not familiar with Ruby, But I will try to fix it

**Comment by KrauseFx** [comment]
Merged with https://github.com/fastlane/fastlane/pull/10333 :+1: Thanks everyone
