### ISSUE TITLE
YourFirstPR.md: "Test the changes for your application" - How to undo?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10317]
I followed https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md#test-the-changes-for-your-application to use my local Fastlane checkout as the `fastlane` for my test project to confirm a PR I created.

Is it enough to just delete the `Gemfile` to undo this?

**Comment by ohayon** [comment]
Yup! That should work, or if you simply do not run the command with the `bundle exec` prefix.  🌤
