### ISSUE TITLE
Enterprise provisioning profiles no longer included in export options plist

### ISSUE THREAD

**Issue by maxmeyers** [fastlane/fastlane#10325]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We use two separate Developer Teams for different schemes. 

For App Store builds, we have:
com.ifttt.ifttt
com.ifttt.ifttt.share
etc.

For Beta builds, we have:
com.ifttt.beta.ifttt
com.ifttt.beta.ifttt.share

We have the provisioning profiles set correctly in Xcode. This worked fine with fastlane until we upgraded from 2.47 to 2.56. Now we get this when doing a beta build:

```
[13:02:12]: There seems to be a mismatch between your provided `export_method` in gym
[13:02:12]: and the selected provisioning profiles. You passed the following options:
[13:02:12]:   export_method:      enterprise
[13:02:12]:   Bundle identifier:  com.ifttt.ifttt
[13:02:12]:   Profile name:       IFTTT App Store
[13:02:12]:   Profile type:       app-store
[13:02:12]: Make sure to either change the `export_method` passed from your Fastfile or CLI
[13:02:12]: or select the correct provisioning profiles by updating your Xcode project
[13:02:12]: or passing the profiles to use by using match or manually via the `export_options` hash
```

This is the gym command being used:

```
    gym(
      scheme: "IFTTT Beta",
      clean: true,
      export_method: "enterprise"
    )
```

##### Complete output when running fastlane, including the stack trace and command used

It seems like the export options plist that fastlane generates is no lo longer including the beta provisioning profiles.

Here's the output from 2.47:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>enterprise</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.ifttt.beta.ifttt</key>
		<string>IFTTT Beta In House</string>
		<key>com.ifttt.beta.ifttt.notification-service</key>
		<string>IFTTT Notification Service Beta In House</string>
		<key>com.ifttt.beta.ifttt.share</key>
		<string>IFTTT Share Beta In House</string>
		<key>com.ifttt.beta.ifttt.today.buttons</key>
		<string>IFTTT Today Buttons Beta In House</string>
		<key>com.ifttt.beta.ifttt.watchkitapp</key>
		<string>IFTTT Watch Beta In House</string>
		<key>com.ifttt.beta.ifttt.watchkitapp.watchkitextension</key>
		<string>IFTTT Watch Extension Beta In House</string>
		<key>com.ifttt.ifttt</key>
		<string>IFTTT App Store</string>
		<key>com.ifttt.ifttt.notification-service</key>
		<string>IFTTT Notification Service App Store</string>
		<key>com.ifttt.ifttt.share</key>
		<string>IFTTT Share App Store</string>
		<key>com.ifttt.ifttt.todaybuttons</key>
		<string>IFTTT Today Buttons App Store</string>
		<key>com.ifttt.ifttt.watchkitapp</key>
		<string>IFTTT Watch App Store</string>
		<key>com.ifttt.ifttt.watchkitapp.watchkitextension</key>
		<string>IFTTT Watch Extension App Store</string>
	</dict>
</dict>
</plist>
```

And here it is in 2.56:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>enterprise</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.ifttt.ifttt</key>
		<string>IFTTT App Store</string>
		<key>com.ifttt.ifttt.notification-service</key>
		<string>IFTTT Notification Service App Store</string>
		<key>com.ifttt.ifttt.share</key>
		<string>IFTTT Share App Store</string>
		<key>com.ifttt.ifttt.todaybuttons</key>
		<string>IFTTT Today Buttons App Store</string>
		<key>com.ifttt.ifttt.watchkitapp</key>
		<string>IFTTT Watch App Store</string>
		<key>com.ifttt.ifttt.watchkitapp.watchkitextension</key>
		<string>IFTTT Watch Extension App Store</string>
	</dict>
</dict>
</plist>
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-9.app/Contents/Developer/                  |
| Xcode Version               | 9.0                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.19.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.0        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.2       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-09-13**
</details>

**Comment by maxmeyers** [comment]
Thanks @fastlane-bot, but I think this is specific to the changed Fastlane version. When I revert back to 2.47, it works again.

**Comment by maxmeyers** [comment]
Note that a workaround is to specify the provisioning profiles in a `Gymfile`, but it's really much nicer to not have to duplicate the information that's already in the Xcode project.

**Comment by adellibovi** [comment]
I think this is related to #10315

**Comment by ohayon** [comment]
Hmm, apologies for the issues! @maxmeyers, have you tried the most recent version of _fastlane_ with the Xcode 9 GM? Just curious to hear if you are seeing the same issue. Thanks! 🐙

**Comment by maxmeyers** [comment]
Yes, this is with Fastlane 2.56 and Xcode 9 GM.

**Comment by tomasebrennan** [comment]
@maxmeyers We're having a very similar problem. You said a workaround was to specify provisioning profiles in a `Gymfile` however I can't find any examples of how to do this online. Would you mind showing an example?

Cheers

**Comment by thasegaw** [comment]
related issue and comment: https://github.com/fastlane/fastlane/issues/10363#issuecomment-330565507

@maxmeyers 
I think that the default configuration for command line you set in Xcode is appstore's one.
You should specify enterprise's one  in Gym.

**Comment by maxmeyers** [comment]
Adding
`configuration: "BetaEnterprise"`
to the gym command in the `Fastfile` fixed the issue. But that really seems like a workaround, because we specified a theme and the theme specifies a configuration.

**Comment by thasegaw** [comment]
>  the scheme specifies a configuration.

Does it indicate this?

<img width="858" alt="_2017_09_22_8_35" src="https://user-images.githubusercontent.com/8136032/30723283-35a6025a-9f71-11e7-9c3c-4bfeefa9c207.png">

In command-line build, this setting is not used.
You can confirm the value of configuration used by Gym by using following command.
```
$ xcodebuild -showBuildSettings -workspace <project file path> -scheme <scheme> | grep "CONFIGURATION ="
```

Because current Gym cannot use this configuration, I think someone have to send PR as new feature.

**Comment by maxmeyers** [comment]
Okay fair enough. Well, I'm satisfied with using the `configuration` flag!
