### ISSUE TITLE
Deliver fails to upload binary

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#10327]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Upload runs fine if one uses Application Launcher while logged in on the associated account.

Fails silently (aka doesn't do anything) while running on a fastlane script.

This was working fine a couple of versions ago.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `ios upload --env store`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/dev-name/dev/sub-project/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/dev-name/dev/sub-project/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/dev-name/dev/sub-project/fastlane/Appfile'
- apple_id: 'dev-name@example.com'
- team_id: '#TEAMTOKEN#'
- app_identifier: 'com.example.project'
-------
Looking for iTunes Connect Team with ID #TEAMID#

+--------------------------------------+-----------------------------------+
|                          deliver 2.56.0 Summary                          |
+--------------------------------------+-----------------------------------+
| skip_metadata                        | true                              |
| skip_screenshots                     | true                              |
| submit_for_review                    | false                             |
| force                                | true                              |
| run_precheck_before_submit           | false                             |
| username                             | itunes-connect@example.com |
| screenshots_path                     | ./fastlane/screenshots            |
| metadata_path                        | ./fastlane/metadata               |
| app_identifier                       | com.example.project               |
| edit_live                            | false                             |
| platform                             | ios                               |
| skip_binary_upload                   | false                             |
| skip_app_version_update              | false                             |
| automatic_release                    | false                             |
| dev_portal_team_id                   | #TEAMTOKEN#                        |
| overwrite_screenshots                | false                             |
| precheck_default_rule_level          | warn                              |
| ignore_language_directory_validatio  | false                             |
| n                                    |                                   |
+--------------------------------------+-----------------------------------+


+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | deliver          | 5           |
+------+------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

default_platform :ios

platform :ios do

  desc 'Cocoapods'
  lane :pods do
    cocoapods
  end

  desc 'Testing'
  lane :test do
    scan(
        scheme: ENV['SCAN_SCHEME'],
        workspace: ENV['FASTLANE_WORKSPACE'],
        clean: true,
        code_coverage: true,
        configuration: 'Alpha',
        device: 'iPhone 7 Plus',
        xcargs: '-sdk iphonesimulator ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64'
    )
    slather(
        cobertura_xml: true,
        output_directory: 'fastlane/test_output',
        workspace: ENV['FASTLANE_WORKSPACE'],
        proj: ENV['PROJECT_COVERAGE'],
        scheme: ENV['SCAN_SCHEME'],
        verbose: true,
        # ignore:['../../*']
    )
  end

  desc 'Provisioning'
  lane :provision do
    match(
        type: ENV['BUILD_TYPE'],
        team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
        team_name: ENV['TEAM_NAME'],
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
        shallow_clone: false,
        force: true,
        force_for_new_devices: true
    )
  end

  desc 'Building the code'
  lane :Building do
    gym(
        scheme: ENV['SCHEME'],
        export_method: ENV['EXPORT_METHOD'],
        configuration: ENV['CONFIGURATION'],
        output_directory: './build',
        output_name: ENV['OUTPUT_NAME'],
        include_symbols: true,
        include_bitcode: false,
        silent: true
    )
  end

  lane :hockeyapp do
    hockey(
        api_token: ENV['HOCKEY_API_TOKEN'],
        public_identifier: ENV['HOCKEY_APP_ID'],
        ipa: 'build/' + ENV['OUTPUT_NAME'],
        notify: '1',
        status: '2',
        release_type: ENV['RELEASE_TYPE'],
        teams: ENV['TEAM'],
        tags: 'developer,tester',
        strategy: 'replace'
    )
  end

  lane :upload do
    deliver(
        skip_metadata: true,
        skip_screenshots: true,
        submit_for_review: false,
        force: true,
        run_precheck_before_submit: false,
        username: ENV['USERNAME']
    )
  end

  error do |lane, exception|
    puts 'Error: ' + exception.message
  end

end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV['APPLE_ID']        # Your Apple email address
team_id ENV['TEAM_ID']          # Developer Portal Team ID
app_identifier ENV['BUNDLE_ID'] # App Bundle ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| bigdecimal                | 1.3.2        |
| psych                     | 2.2.4        |
</details>

*generated on:* **2017-09-14**
</details>

**Comment by lferro9000** [comment]
The offending line is:
2 | deliver | 5

There is no way the upload to take 5 seconds only. Normally it takes minimal 30 seconds to 1m30s depending on network performance at the time.

Are there any logging that is not captured by fastlane that can be useful to trace this issue?

**Comment by ohayon** [comment]
Hey @lferro9000 could you share the output of the command when you run it using `--verbose` so we can see the whole context? Thanks! 🚀

**Comment by kielgillard** [comment]
We're using Xcode 9 and getting an iTMS uploader error like this:
```
  | Return status of iTunes Transporter was 1: The filename kiosk(9f262739838070af272a2934173f8f246dec8e2311670aea428210e8f4501e5b).ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
  | The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```
However the .ipa is simply named `kiosk.app`.

**Comment by KrauseFx** [comment]
@kielgillard your issue doesn't seem to be related, for some reason the ipa file is being renamed to `kiosk(9f262739838070af272a2934173f8f246dec8e2311670aea428210e8f4501e5b).ipa` instead of just `9f262739838070af272a2934173f8f246dec8e2311670aea428210e8f4501e5b.ipa`, I wonder why this is happening - what version of fastlane are you using, and how did you install it?

**Comment by KrauseFx** [comment]
Yeah, we'd need the `--verbose` output to fix the issue @lferro9000

**Comment by lferro9000** [comment]
The verbose output is very similar, but here it goes:


### Command actually used was: `fastlane  --verbose --capture_output --troubleshoot ios upload --env=Store`


### Captured Output

Command Used: `ios upload --env=Store`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/user/dev/platopus/fastlane/Appfile'
- apple_id: 'user@example.com'
- team_id: '#devteamid#'
- app_identifier: 'com.example.myapp'
-------
Loading session from '/Users/user/.fastlane/spaceship/user@example.com/cookie'
Looking for iTunes Connect Team with ID #itunesteamid#

+--------------------------------------+-----------------------------+
|                       deliver 2.56.0 Summary                       |
+--------------------------------------+-----------------------------+
| skip_metadata                        | true                        |
| skip_screenshots                     | true                        |
| submit_for_review                    | false                       |
| force                                | true                        |
| run_precheck_before_submit           | false                       |
| username                             | user@example.com            |
| screenshots_path                     | ./fastlane/screenshots      |
| metadata_path                        | ./fastlane/metadata         |
| app_identifier                       | com.example.myapp           |
| edit_live                            | false                       |
| platform                             | ios                         |
| skip_binary_upload                   | false                       |
| skip_app_version_update              | false                       |
| automatic_release                    | false                       |
| dev_portal_team_id                   | #devteamid#                 |
| overwrite_screenshots                | false                       |
| precheck_default_rule_level          | warn                        |
| ignore_language_directory_validatio  | false                       |
| n                                    |                             |
+--------------------------------------+-----------------------------+


+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | deliver          | 6           |
+------+------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

default_platform :ios

platform :ios do

  desc 'Cocoapods'
  lane :pods do
    cocoapods
  end

  desc 'Testing'
  lane :test do
    scan(
        scheme: ENV['SCAN_SCHEME'],
        workspace: ENV['FASTLANE_WORKSPACE'],
        clean: true,
        code_coverage: true,
        configuration: 'Alpha',
        device: 'iPhone 7 Plus',
        xcargs: '-sdk iphonesimulator ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64'
    )
    slather(
        cobertura_xml: true,
        output_directory: 'fastlane/test_output',
        workspace: ENV['FASTLANE_WORKSPACE'],
        proj: ENV['PROJECT_COVERAGE'],
        scheme: ENV['SCAN_SCHEME'],
        verbose: true,
        # ignore:['../../*']
    )
  end

  desc 'Provisioning'
  lane :provision do
    match(
        type: ENV['BUILD_TYPE'],
        team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
        team_name: ENV['TEAM_NAME'],
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
        shallow_clone: false,
        force: true,
        force_for_new_devices: true
    )
  end

  desc 'Building the code'
  lane :Building do
    gym(
        scheme: ENV['SCHEME'],
        export_method: ENV['EXPORT_METHOD'],
        configuration: ENV['CONFIGURATION'],
        output_directory: './build',
        output_name: ENV['OUTPUT_NAME'],
        include_symbols: true,
        include_bitcode: false,
        silent: true
    )
  end

  lane :hockeyapp do
    hockey(
        api_token: ENV['HOCKEY_API_TOKEN'],
        public_identifier: ENV['HOCKEY_APP_ID'],
        ipa: 'build/' + ENV['OUTPUT_NAME'],
        notify: '1',
        status: '2',
        release_type: ENV['RELEASE_TYPE'],
        teams: ENV['TEAM'],
        tags: 'developer,tester',
        strategy: 'replace'
    )
  end

  lane :upload do
    deliver(
        skip_metadata: true,
        skip_screenshots: true,
        submit_for_review: false,
        force: true,
        run_precheck_before_submit: false,
        username: ENV['USERNAME']
    )
  end

  error do |lane, exception|
    puts 'Error: ' + exception.message
  end

end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV['APPLE_ID']        # Your Apple email address
team_id ENV['TEAM_ID']          # Developer Portal Team ID
app_identifier ENV['BUNDLE_ID'] # App Bundle ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| bigdecimal                | 1.3.2        |
| psych                     | 2.2.4        |
</details>


*generated on:* **2017-09-18**
</details>

**Comment by lferro9000** [comment]
.env
FASTLANE_SKIP_UPDATE_CHECK=on

.env.default
APPLE_ID=user@example.com #dev portal email

# Developer Portal Team ID
TEAM_ID=#devportalid#
TEAM_NAME=#devportalteamname#
SCHEME=#targetname#
GIT_URL=git@match:matchrepo/match-certificates.git
GIT_BRANCH=#repo-branch-for-team#
FASTLANE_WORKSPACE=MyApp.xcworkspace
TEAM=#itunesteamid#
USERNAME=user@example.com #itunesconnect email
SCAN_SCHEME=#unit-test-base-targetname#
PROJECT_COVERAGE=MyApp.xcodeproj

.env.store
BUNDLE_ID=com.example.MyApp
BUILD_TYPE=appstore
CONFIGURATION=Store
EXPORT_METHOD=app-store
OUTPUT_NAME=MyApp-Store.ipa
RELEASE_TYPE=1
HOCKEY_API_TOKEN=#api-token#
HOCKEY_APP_ID=#app-id#

This are the enviroment configuration (slightly obfuscated naturally).

This setup was working perfectly a couple of versions ago.

Of notice, the fastlane is a symlink to a folder at same level like:

/target1
/target2
/target3
/fastlane -> /target1

This was the only way i could figure out to make fastlane work with different targets which have different teams ids, dev accounts, etc...

**Comment by dtrukr** [comment]
I'm actually seeing exactly the same error. Also using Xcode 9 GM and fastlane 2.57.0. Deliver fails with the following error:
`[22:04:49]: The filename da(79a6c24a88310adf91490fa32eaa7e15dd91ee2d9d8139dfe86ac76320d04eac).ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
`

The IPA file is named just 'da.ipa'. If I look at the generated transporter file, here is how it looks like:
<img width="564" alt="screen shot 2017-09-18 at 22 01 54" src="https://user-images.githubusercontent.com/658322/30562108-9f398590-9cbd-11e7-8df1-a22f8d3bee0c.png">

**Comment by dtrukr** [comment]
I'm not sure if it's relevant, but if I look at ipa_upload_package_builder.rb, there is following code:
` def copy_ipa(ipa_path)
      ipa_file_name = "#{File.basename(ipa_path, '.ipa')}(#{Digest::SHA256.file(ipa_path).hexdigest}).ipa"
`
This actually appends SHA256 digest to the original ipa name and copies it to transporter package. The resulting name of the file will be "ORIGINAL_IPA_NAME(SHA256).ipa". However, looking at transporter out it seems that parentheses are not allowed in the filename:
`[22:04:49]: The filename da(79a6c24a88310adf91490fa32eaa7e15dd91ee2d9d8139dfe86ac76320d04eac).ipa in the package contains an invalid character(s). The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore`

**Comment by pixelmatrix** [comment]
It looks like this PR is what introduced the issue: https://github.com/fastlane/fastlane/commit/d15b3fdbe4b6c39aa2dd3a8d9533a1c4eedaf600

**Comment by vmalyi** [comment]
Downgrading Fastlane to 2.56.0 helps.

**Comment by KrauseFx** [comment]
Thanks for reporting this, this should be fixed with the most recent release, sorry about that

**Comment by fassko** [comment]
Thanks @KrauseFx this did fix the issue!

**Comment by lferro9000** [comment]
Updated to 2.57.1, still same result.
Tried with some older versions with the same result.
My only conclusion is that something fundamental changed that is pervasive between versions (ex. Apple api changes) that is making the upload to fail and that changing versions of fastlane has absolutly no effect.

I will try to do a clean setup from "scratch" without my complicated environment later this week and will keep this issue updated when i've the results.

**Comment by fassko** [comment]
@lferro9000 Hmmm. What is in your gym call?

Mine is just like this:

```
gym(
  workspace: "qminder-tv.xcworkspace",
  scheme: "qminder-tv",
  clean: true
)
```

**Comment by Lutzifer** [comment]
In my case, I was calling fastlane from inside fastlane from inside fastlane. Updating **all** fastlanes to 2.57.1 fixed it.
