### ISSUE TITLE
The request could not be completed because: 	there is no web session to update

### ISSUE THREAD

**Issue by barbaramartina** [fastlane/fastlane#10322]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since today morning we're getting the error "[!] The request could not be completed because:
	there is no web session to update"
And the pilot step is failing the builds. 
Using fast lane 2.56.0. 
Is anybody else experiencing the same problem?

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                              | Version | Update-Status |
| ----------------------------------- | ------- | ------------- |
| fastlane-plugin-wait_xcrun          | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-upload_folder_to_s3 | 0.3.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                 | Version      |
| ----------------------------------- | ------------ |
| did_you_mean                        | 1.0.0        |
| slack-notifier                      | 1.5.1        |
| claide                              | 1.0.2        |
| colored2                            | 3.1.2        |
| nanaimo                             | 0.2.3        |
| xcodeproj                           | 1.5.1        |
| multipart-post                      | 2.0.0        |
| word_wrap                           | 1.0.0        |
| tty-screen                          | 0.5.0        |
| babosa                              | 1.0.2        |
| colored                             | 1.2          |
| highline                            | 1.7.8        |
| commander-fastlane                  | 4.4.5        |
| http-cookie                         | 1.0.3        |
| faraday-cookie_jar                  | 0.0.6        |
| fastimage                           | 2.1.0        |
| mini_magick                         | 4.5.1        |
| security                            | 0.1.3        |
| xcpretty-travis-formatter           | 0.0.4        |
| json                                | 1.8.6        |
| io-console                          | 0.4.5        |
| excon                               | 0.59.0       |
| rubyzip                             | 1.2.1        |
| plist                               | 3.3.0        |
| faraday                             | 0.13.1       |
| jwt                                 | 1.5.6        |
| os                                  | 0.9.6        |
| signet                              | 0.7.3        |
| googleauth                          | 0.5.3        |
| declarative-option                  | 0.1.0        |
| representable                       | 3.0.4        |
| mime-types-data                     | 3.2016.0521  |
| mime-types                          | 3.1          |
| google-api-client                   | 0.13.6       |
| faraday_middleware                  | 0.12.2       |
| unf                                 | 0.1.4        |
| domain_name                         | 0.5.20170404 |
| bundler                             | 1.14.3       |
| terminal-table                      | 1.8.0        |
| unicode-display_width               | 1.3.0        |
| fastlane-plugin-wait_xcrun          | 0.1.1        |
| fastlane-plugin-upload_folder_to_s3 | 0.3.1        |
</details>

*generated on:* **2017-09-13**

**Comment by ohayon** [comment]
Oh no! Thanks for reporting the issue @barbaramartina! We were seeing some outages on Apples end yesterday. Its possible that maybe that was involved. Could you share the output from your command line with us so we can have more context? Thank you!! 🚀

**Comment by barbaramartina** [comment]
hi @ohayon , Im afraid the outages are not the cause since we have run the lane several times & I just did one more time now with the same output. 
Here's the console output I can share, hope this help. We've also signed in again in the new XCode installation (which I read could be a problem for the session issue, but did not help either).

bundle exec fastlane testflight_beta
Couldn't verify that spaceship is up to date
+-------------------------------------+---------+---------------------+
|                            Used plugins                             |
+-------------------------------------+---------+---------------------+
| Plugin                              | Version | Action              |
+-------------------------------------+---------+---------------------+
| fastlane-plugin-wait_xcrun          | 0.1.1   | wait_xcrun          |
| fastlane-plugin-upload_folder_to_s3 | 0.3.1   | upload_folder_to_s3 |
+-------------------------------------+---------+---------------------+

[20:36:17]: -------------------------------------------------
[20:36:17]: --- Step: Verifying required fastlane version ---
[20:36:17]: -------------------------------------------------
[20:36:17]: Your fastlane version 2.56.0 matches the minimum requirement of 1.70.0  ✅
[20:36:17]: ------------------------------
[20:36:17]: --- Step: default_platform ---
[20:36:17]: ------------------------------
[20:36:17]: Driving the lane 'ios testflight_beta' 🚀
[20:36:17]: ----------------------------------------------
[20:36:17]: --- Step: Switch to ios prepare_build lane ---
[20:36:17]: ----------------------------------------------
[20:36:17]: Cruising over to lane 'ios prepare_build' 🚖
[20:36:17]: -------------------------------------
[20:36:17]: --- Step: ensure_git_status_clean ---
[20:36:17]: -------------------------------------
[20:36:17]: $ git status --porcelain
[20:36:18]: Git status is clean, all good! 💪
[20:36:18]: -----------------------
[20:36:18]: --- Step: cocoapods ---
[20:36:18]: -----------------------
[20:36:18]: $ cd 'app' && bundle exec pod install



[20:36:28]: ------------------------------------
[20:36:28]: --- Step: increment_build_number ---
[20:36:28]: ------------------------------------
Current version of project is: 
    1331

[20:36:29]: $ cd /Users/app && agvtool next-version -all && cd -
[20:36:30]: ▸ Setting version of project to:
[20:36:30]: ▸ 1332.
[20:36:30]: ▸ Also setting CFBundleVersion key (assuming it exists)
[20:36:30]: ▸ Updating CFBundleVersion in Info.plist(s)...

[20:36:31]: ---------------------------------
[20:36:31]: --- Step: commit_version_bump ---
[20:36:31]: ---------------------------------
[20:36:31]: $ git rev-parse --show-toplevel
[20:36:31]: $ git diff --name-only HEAD


[20:36:31]: Committed "Build number bump" 💾.
[20:36:31]: --------------------------------
[20:36:31]: --- Step: push_to_git_remote ---
[20:36:31]: --------------------------------


[20:36:35]: -------------------
[20:36:35]: --- Step: match ---
[20:36:35]: -------------------
[20:36:35]: Successfully loaded '/Matchfile' 📄


[20:37:11]: All required keys, certificates and provisioning profiles are installed 🙌
[20:37:11]: Setting Provisioning Profile type to 'app-store'
[20:37:11]: -----------------
[20:37:11]: --- Step: gym ---
[20:37:11]: -----------------
[20:37:11]: $ xcodebuild -list -workspace ./app.xcworkspace
[20:37:17]: $ xcodebuild -showBuildSettings -workspace ./app.xcworkspace -scheme app scheme


[20:43:56]: Successfully exported and compressed dSYM file
[20:43:56]: Successfully exported and signed the ipa file:
[20:43:56]: /Users/barbararodeker/app-ios/app.ipa
[20:43:56]: -------------------------------------------
[20:43:56]: --- Step: upload_symbols_to_crashlytics ---
[20:43:56]: -------------------------------------------


[20:46:24]: Successfully generated zip file at path '/tmp/app 2017-09-14 20.37.28.xcarchive/app 2017-09-14 20.37.28.xcarchive.zip'
[20:46:24]: ---------------------------------
[20:46:24]: --- Step: upload_folder_to_s3 ---
[20:46:24]: ---------------------------------

[20:51:22]: Cruising back to lane 'ios testflight_beta' 🚘
[20:51:22]: -------------------
[20:51:22]: --- Step: pilot ---
[20:51:22]: -------------------
[20:51:22]: Login to iTunes Connect (****)
[20:51:27]: -----------------------------------
[20:51:27]: --- Step: clean_build_artifacts ---
[20:51:27]: -----------------------------------
[20:51:27]: Cleaned up build artifacts 🐙

---+
[20:51:27]: there is no web session to update

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | Verifying required fastlane version  | 0           |
| 2    | default_platform                     | 0           |
| 3    | Switch to ios prepare_build lane     | 0           |
| 4    | ensure_git_status_clean              | 0           |
| 5    | cocoapods                            | 8           |
| 6    | increment_build_number               | 2           |
| 7    | commit_version_bump                  | 0           |
| 8    | push_to_git_remote                   | 3           |
| 9    | match                                | 13          |
| 10   | gym                                  | 518         |
| 11   | upload_symbols_to_crashlytics        | 106         |
| 12   | Switch to ios upload_archive_s3 lane | 0           |
| 13   | zip                                  | 19          |
| 14   | upload_folder_to_s3                  | 332         |
| 💥   | pilot                                | 4           |
| 16   | clean_build_artifacts                | 0           |
+------+--------------------------------------+-------------+

[20:51:27]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  The request could not be completed because: 	there is no web session to update
    https://github.com/fastlane/fastlane/issues/10322 [open] 1 💬
    an hour ago

➡️  fastlane deliver fails when calling from ruby. The request could not be completed because: there is no web session to update 
    https://github.com/fastlane/fastlane/issues/9805 [closed] 2 💬
    20 Jul 2017

➡️  latest_testflight_build_number fails with 'there is no web session to update' error
    https://github.com/fastlane/fastlane/issues/9781 [closed] 3 💬
    17 Jul 2017

and 17 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09there%20is%20no%20web%20session%20to%20update&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	there is no web session to update

**Comment by ohayon** [comment]
Ah! I'm sorry @barbaramartina! I forgot to mention, could you run the command with `--verbose` so that we can see the stack trace as well? Thanks! 🐙

**Comment by barbaramartina** [comment]
@ohayon  no problem, here it goes.


 bundle exec fastlane testflight_beta --verbose
Couldn't verify that spaceship is up to date
DEBUG [2017-09-14 22:14:28.94]: Checking if there are any plugins that should be loaded...
DEBUG [2017-09-14 22:14:28.94]: Loading 'fastlane-plugin-wait_xcrun' plugin
INFO [2017-09-14 22:14:29.02]: gem 'fastlane-plugin-wait_xcrun' is already installed
DEBUG [2017-09-14 22:14:29.02]: Loading 'fastlane-plugin-upload_folder_to_s3' plugin
INFO [2017-09-14 22:14:29.08]: gem 'fastlane-plugin-upload_folder_to_s3' is already installed
+-------------------------------------+---------+---------------------+
|                            Used plugins                             |
+-------------------------------------+---------+---------------------+
| Plugin                              | Version | Action              |
+-------------------------------------+---------+---------------------+
| fastlane-plugin-wait_xcrun          | 0.1.1   | wait_xcrun          |
| fastlane-plugin-upload_folder_to_s3 | 0.3.1   | upload_folder_to_s3 |
+-------------------------------------+---------+---------------------+

INFO [2017-09-14 22:14:29.29]: -------------------------------------------------
INFO [2017-09-14 22:14:29.29]: --- Step: Verifying required fastlane version ---
INFO [2017-09-14 22:14:29.29]: -------------------------------------------------
INFO [2017-09-14 22:14:29.29]: Your fastlane version 2.56.0 matches the minimum requirement of 1.70.0  ✅
INFO [2017-09-14 22:14:29.29]: ------------------------------
INFO [2017-09-14 22:14:29.29]: --- Step: default_platform ---
INFO [2017-09-14 22:14:29.29]: ------------------------------
INFO [2017-09-14 22:14:29.29]: Driving the lane 'ios testflight_beta' 🚀
INFO [2017-09-14 22:14:29.30]: ----------------------------------------------
INFO [2017-09-14 22:14:29.30]: --- Step: Switch to ios prepare_build lane ---
INFO [2017-09-14 22:14:29.30]: ----------------------------------------------
INFO [2017-09-14 22:14:29.30]: Cruising over to lane 'ios prepare_build' 🚖
INFO [2017-09-14 22:14:29.30]: -------------------------------------
INFO [2017-09-14 22:14:29.30]: --- Step: ensure_git_status_clean ---
INFO [2017-09-14 22:14:29.30]: -------------------------------------
INFO [2017-09-14 22:14:29.30]: $ git status --porcelain
INFO [2017-09-14 22:14:29.36]: Git status is clean, all good! 💪
INFO [2017-09-14 22:14:29.36]: -----------------------
INFO [2017-09-14 22:14:29.36]: --- Step: cocoapods ---
INFO [2017-09-14 22:14:29.36]: -----------------------
INFO [2017-09-14 22:14:29.60]: gem 'cocoapods' is already installed
DEBUG [2017-09-14 22:14:29.60]: Taking value for 'podfile' from environment variable 'FL_COCOAPODS_PODFILE'
DEBUG [2017-09-14 22:14:29.60]: Taking value for 'podfile' from environment variable 'FL_COCOAPODS_PODFILE'
DEBUG [2017-09-14 22:14:29.60]: Taking value for 'podfile' from environment variable 'FL_COCOAPODS_PODFILE'

INFO [2017-09-14 22:14:39.42]: ------------------------------------
INFO [2017-09-14 22:14:39.42]: --- Step: increment_build_number ---
INFO [2017-09-14 22:14:39.42]: ------------------------------------
Current version of project app is: 
    1338



INFO [2017-09-14 22:14:41.62]: ---------------------------------
INFO [2017-09-14 22:14:41.62]: --- Step: commit_version_bump ---
INFO [2017-09-14 22:14:41.62]: ---------------------------------
INFO [2017-09-14 22:14:41.62]: $ git rev-parse --show-toplevel
INFO [2017-09-14 22:14:46.26]: -------------------
INFO [2017-09-14 22:14:46.26]: --- Step: match ---
INFO [2017-09-14 22:14:46.26]: -------------------
INFO [2017-09-14 22:14:46.27]: Successfully loaded '/Users/barbararodeker/app-ios/fastlane/Matchfile' 📄

DEBUG [2017-09-14 22:14:46.27]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'
DEBUG [2017-09-14 22:14:46.27]: Taking value for 'team_name' from environment variable 'FASTLANE_TEAM_NAME'


INFO [2017-09-14 22:14:46.27]: Cloning remote git repo...
INFO [2017-09-14 22:14:46.27]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2017-09-14 22:14:46.27]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:app/certs.git' '/var/folders/6l/kw_n4mfd3cqf10mwnz_jh43c0000gn/T/d20170914-84985-p5imm4'

INFO [2017-09-14 22:15:45.85]: $ set -o pipefail && xcodebuild -workspace ./app.xcworkspace -scheme app -destination 'generic/platform=iOS' -archivePath /Users/barbararodeker/Library/Developer/Xcode/Archives/2017-09-14/app\ 2017-09-14\ 22.15.45.xcarchive archive | tee /Users/barbararodeker/Library/Logs/gym/app-app.log | xcpretty

$ /usr/bin/xcrun /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/6l/kw_n4mfd3cqf10mwnz_jh43c0000gn/T/gym_config20170914-84985-lcr6cq.plist' -archivePath /Users/barbararodeker/Library/Developer/Xcode/Archives/2017-09-14/app\ 2017-09-14\ 22.15.45.xcarchive -exportPath '/var/folders/6l/kw_n4mfd3cqf10mwnz_jh43c0000gn/T/gym_output20170914-84985-1lmf1ea' 
INFO [2017-09-14 22:20:57.84]: ▸ rbenv detected, removing env variables
INFO [2017-09-14 22:20:57.85]: ▸ rbenv: no such command `shell'
INFO [2017-09-14 22:20:57.85]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/6l/kw_n4mfd3cqf10mwnz_jh43c0000gn/T/gym_config20170914-84985-lcr6cq.plist -archivePath '/Users/barbararodeker/Library/Developer/Xcode/Archives/2017-09-14/app 2017-09-14 22.15.45.xcarchive' -exportPath /var/folders/6l/kw_n4mfd3cqf10mwnz_jh43c0000gn/T/gym_output20170914-84985-1lmf1ea
INFO [2017-09-14 22:20:58.43]: ▸ 2017-09-14 22:20:58.429 xcodebuild[92702:3228994] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/6l/kw_n4mfd3cqf10mwnz_jh43c0000gn/T/app_2017-09-14_22-20-58.429.xcdistributionlogs'.

INFO [2017-09-14 22:21:46.44]: Successfully exported and compressed dSYM file
INFO [2017-09-14 22:21:46.44]: Successfully exported and signed the ipa file:
INFO [2017-09-14 22:21:46.44]: /Users/barbararodeker/app-ios/app.ipa
INFO [2017-09-14 22:21:46.45]: -------------------------------------------
INFO [2017-09-14 22:21:46.45]: --- Step: upload_symbols_to_crashlytics ---
INFO [2017-09-14 22:21:46.45]: -------------------------------------------
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'binary_path' from environment variable 'FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_BINARY_PATH'
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'binary_path' from environment variable 'FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_BINARY_PATH'
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'binary_path' from environment variable 'FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_BINARY_PATH'
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'api_token' from environment variable 'CRASHLYTICS_API_TOKEN'
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'api_token' from environment variable 'CRASHLYTICS_API_TOKEN'
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'dsym_path' from environment variable 'FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_DSYM_PATH'
DEBUG [2017-09-14 22:21:46.45]: Taking value for 'dsym_path' from environment variable 'FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_DSYM_PATH'
INFO [2017-09-14 22:21:46.45]: Extracting '/Users/barbararodeker/app-ios/app.app.dSYM.zip'...


INFO [2017-09-14 22:23:54.59]: Successfully uploaded dSYM files to Crashlytics 💯
INFO [2017-09-14 22:23:54.59]: --------------------------------------------------
INFO [2017-09-14 22:23:54.59]: --- Step: Switch to ios upload_archive_s3 lane ---
INFO [2017-09-14 22:23:54.59]: --------------------------------------------------
INFO [2017-09-14 22:23:54.59]: Cruising over to lane 'ios upload_archive_s3' 🚖
INFO [2017-09-14 22:23:54.59]: -----------------
INFO [2017-09-14 22:23:54.59]: --- Step: zip ---
INFO [2017-09-14 22:23:54.59]: -----------------
INFO [2017-09-14 22:23:54.59]: Compressing /Users/barbararodeker/Library/Developer/Xcode/Archives/2017-09-14/app 2017-09-14 22.15.45.xcarchive...
INFO [2017-09-14 22:23:54.59]: $ zip -r /tmp/app\ 2017-09-14\ 22.15.45.xcarchive/app\ 2017-09-14\ 22.15.45.xcarchive.zip app\ 2017-09-14\ 22.15.45.xcarchive

INFO [2017-09-14 22:24:12.82]: ---------------------------------
INFO [2017-09-14 22:24:12.82]: --- Step: upload_folder_to_s3 ---
INFO [2017-09-14 22:24:12.82]: ---------------------------------
DEBUG [2017-09-14 22:24:12.90]: The 'aws-sdk' gem is present
DEBUG [2017-09-14 22:24:12.90]: Found the needed `AWS` module in the 'aws-sdk' gem
DEBUG [2017-09-14 22:24:12.90]: Loaded AWS SDK v1.x from the `aws-sdk` gem


INFO [2017-09-14 22:43:20.71]: --- Step: pilot ---
INFO [2017-09-14 22:43:20.71]: -------------------
INFO [2017-09-14 22:43:20.72]: Login to iTunes Connect (itunes@app.de)
INFO [2017-09-14 22:43:25.85]: -----------------------------------
INFO [2017-09-14 22:43:25.85]: --- Step: clean_build_artifacts ---
INFO [2017-09-14 22:43:25.85]: -----------------------------------
DEBUG [2017-09-14 22:43:25.85]: Cleaning up '/Users/barbararodeker/app-ios/app.ipa'
DEBUG [2017-09-14 22:43:25.85]: Cleaning up '/Users/barbararodeker/app-ios/app.app.dSYM.zip'
INFO [2017-09-14 22:43:25.85]: Cleaned up build artifacts 🐙

ERROR [2017-09-14 22:43:25.85]: there is no web session to update
INFO [2017-09-14 22:43:25.85]: Successfully generated documentation at path '/Users/barbararodeker/app-ios/fastlane/README.md'

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | Verifying required fastlane version  | 0           |
| 2    | default_platform                     | 0           |
| 3    | Switch to ios prepare_build lane     | 0           |
| 4    | ensure_git_status_clean              | 0           |
| 5    | cocoapods                            | 10          |
| 6    | increment_build_number               | 2           |
| 7    | commit_version_bump                  | 0           |
| 8    | push_to_git_remote                   | 3           |
| 9    | match                                | 39          |
| 10   | gym                                  | 380         |
| 11   | upload_symbols_to_crashlytics        | 128         |
| 12   | Switch to ios upload_archive_s3 lane | 0           |
| 13   | zip                                  | 18          |
| 14   | upload_folder_to_s3                  | 1147        |
| 💥   | pilot                                | 4           |
| 16   | clean_build_artifacts                | 0           |
+------+--------------------------------------+-------------+

DEBUG [2017-09-14 22:43:25.87]: All plugins are up to date
ERROR [2017-09-14 22:43:25.87]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	there is no web session to update

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09there%20is%20no%20web%20session%20to%20update+repo:fastlane/fastlane
➡️  The request could not be completed because: 	there is no web session to update
    https://github.com/fastlane/fastlane/issues/10322 [open] 3 💬
    an hour ago

➡️  fastlane deliver fails when calling from ruby. The request could not be completed because: there is no web session to update 
    https://github.com/fastlane/fastlane/issues/9805 [closed] 2 💬
    20 Jul 2017

➡️  latest_testflight_build_number fails with 'there is no web session to update' error
    https://github.com/fastlane/fastlane/issues/9781 [closed] 3 💬
    17 Jul 2017

and 17 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09there%20is%20no%20web%20session%20to%20update&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2017-09-14 22:43:27.14]: All plugins are up to date

bundler: failed to load command: fastlane (/Users/barbararodeker/.gem/ruby/2.3.1/bin/fastlane)
Spaceship::TunesClient::ITunesConnectError: [!] The request could not be completed because:
	there is no web session to update
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/tunes/tunes_client.rb:97:in `team_id='
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/tunes/tunes_client.rb:124:in `select_team'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/pilot/lib/pilot/manager.rb:16:in `login'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/pilot/lib/pilot/manager.rb:8:in `start'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/pilot/lib/pilot/build_manager.rb:6:in `upload'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/actions/pilot.rb:16:in `run'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:105:in `block (2 levels) in parsing_binding'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/barbararodeker/.gem/ruby/2.3.1/gems/fastlane-2.56.0/bin/fastlane:20:in `<top (required)>'
  /Users/barbararodeker/.gem/ruby/2.3.1/bin/fastlane:23:in `load'
  /Users/barbararodeker/.gem/ruby/2.3.1/bin/fastlane:23:in `<top (required)>'

**Comment by ohayon** [comment]
Hey @barbaramartina - is there any chance you could share your Gemfile with us? We have seen this issue before and it often has something to do with referencing older versions of our gem which could happen by accident if the Gemfile references our other tools besides fastlane, _or_ if you still have some of those gems installed on your machine. Would you also mind running `gem list pilot` to see if you have a gem called 'pilot' in your gemset?

Thanks! 🐰

**Comment by barbaramartina** [comment]
hey @ohayon  sure, here is the Gem file & the result of the command:

# GemFile
source "https://rubygems.org"
gem 'cocoapods', '1.2.1'
gem 'fastlane', '2.56.0'
gem 'xcode-install'
gem 'spaceship', '1.0.0'
gem 'fastlane-plugin-wait_xcrun', '~> 0.1.1'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)

# Command

 gem list pilot

*** LOCAL GEMS ***

pilot (1.12.1, 1.12.0, 1.11.1, 1.11.0, 1.10.1)

**Comment by ohayon** [comment]
Okay! Great. So, could you try removing the `gem 'spaceship'` line from your Gemfile, and also do a `gem uninstall pilot` on your command line and then give this another shot? 

The reason for this is that a while back we moved from having many gems to just one so that dependency management was easier it looks like this is the culprit, but please let us know if you are still having issues!

**Comment by barbaramartina** [comment]
@ohayon thanks for your help here! and sorry for the delay answering here (some other priorities made their way in the meantime). I've updated to 2.58.0 version of Fastlane & the problem is solved.

**Comment by ohayon** [comment]
Glad to hear you are back up and running @barbaramartina !
