### ISSUE TITLE
[iOS] Alternative Solution to Could not retrieve response as fastlane runs in non-interactive mode 

### ISSUE THREAD

**Issue by isolatedperson** [fastlane/fastlane#10335]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi there,

I'm trying to write a small application so it can setup several itunes applications automatically. If we use manual process, we go project folder , call fastlane init, which detects iOS project and asks for username, we provide username and then it asks for email and so on.

As you can see this would be a great problem if i have to do that for several dozens of apps (as thats my primary job). Thats why i tried to write a program which automatically provide these parameters but im getting following error
crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode

So i have 2 options now, either there is some property which let fastlane work on non-interactive mode.
2- i'll be able to provide all answers to these questions in a single command something like fastlane init username "username_here" password "password here" etc

Please advise which one of them should i use?
In case of 2. where can i get list of parameters?

Thanks

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/interface.rb:119:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:130:in `verify_interactive!'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:103:in `input'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane/lib/fastlane/setup/setup_ios.rb:187:in `ask_for_apple_id'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane/lib/fastlane/setup/setup_ios.rb:28:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane/lib/fastlane/setup/setup.rb:29:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/li
```

**Comment by ohayon** [comment]
Hey @isolatedperson, as of now, the `fastlane init` action is expecting that it will be run in interactive mode so that it can ask the user for relevant values. That being said, I think maybe you could try to make a template Fastfile that you could then write a script to fill in variables in the template as it copies and sets up new projects. Does that make sense at all? Let us know if we can help any further!! 🚀

**Comment by isolatedperson** [comment]
@ohayon thank you for your prompt reply.

I can do template thing as i did for Android, however i have a confusion about it.
As you know that Fastlane has deep support for iOS, including create app in iTunes Connect + Apple Developer, creating certs etc, uploading meta, and finally binary.

So my confusion is does Fastlane create app in itunes DURING asking these questions OR after that Fastlane folder/AppFile is created? because if its AFTER then template can be used.

Please advise

**Comment by ohayon** [comment]
Yeah, so fastlane does create the app in iTC during this whole process. And that is something that you would be missing by using a template. That being said, you could, in the script call `fastlane produce` with the necessary variables so that it will create the app in iTC along the way. 

Happy to help more feel free to ask questions!

**Comment by isolatedperson** [comment]
@ohayon If i understand correctly, then after creating a hand made template fastlane folder, i can later call produce and other commands seperatly to create app in itunes and update meta data etc?
If thats so i think it can be done, ill try and let you know

**Comment by ohayon** [comment]
Yup! You should be able to do that no problem! 🐙
