### ISSUE TITLE
import_from_git failing

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#10331]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`fastlane` failing when using `import_from_git` action. I am passing the `https://github.com/fastlane/fastlane/tree/master/fastlane` as url parameter. Happy to provide more information. The command I am running is just `fastlane` without any lane or action name.

### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/rtayal/Desktop/Personal/ReviewMonitor/fastlane/Appfile'
- app_identifier: 'io.rtayal.ReviewMonitor'
- apple_id: 'contact@appikon.com'
- team_id: 'CEBY93VF85'
-------

Looking for related GitHub issues on fastlane/fastlane...
Search query: Exit status of command 'GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/fastlane/fastlane/tree/master/fastlane' '/var/folders/36/ssh7kx297sz2smr6ll6zmj2wcv760y/T/fl_clone20170914-37710-6kn4zh/fastlane' --depth 1 -n ' was 128 instead of 0.
Cloning into '/var/folders/36/ssh7kx297sz2smr6ll6zmj2wcv760y/T/fl_clone20170914-37710-6kn4zh/fastlane'...
remote: Not Found
fatal: repository 'https://github.com/fastlane/fastlane/tree/master/fastlane/' not found

URL: https://api.github.com/search/issues?q=Exit%20status%20of%20command%20'GIT_TERMINAL_PROMPT=0%20git%20clone%20'https://github.com/fastlane/fastlane/tree/master/fastlane'%20'/var/folders/36/ssh7kx297sz2smr6ll6zmj2wcv760y/T/fl_clone20170914-37710-6kn4zh/fastlane'%20--depth%201%20-n%20'%20was%20128%20instead%20of%200.%0ACloning%20into%20'/var/folders/36/ssh7kx297sz2smr6ll6zmj2wcv760y/T/fl_clone20170914-37710-6kn4zh/fastlane'...%0Aremote:%20Not%20Found%0Afatal:%20repository%20'https://github.com/fastlane/fastlane/tree/master/fastlane/'%20not%20found%0A+repo:fastlane/fastlane


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

  import_from_git(url: 'https://github.com/fastlane/fastlane/tree/master/fastlane')

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # ENV['DEVELOPER_DIR'] = '/Applications/Xcode old/Xcode-beta.app/Contents/Developer'
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "io.rtayal.ReviewMonitor" # The bundle identifier of your app
apple_id "contact@appikon.com" # Your Apple email address

team_id "CEBY93VF85" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| json                      | 2.1.0        |
| excon                     | 0.59.0       |
| openssl                   | 2.0.2        |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| rdoc                      | 5.0.0        |
| addressable               | 2.5.2        |
| multi_json                | 1.12.2       |
| declarative               | 0.0.10       |
| retriable                 | 3.1.1        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-09-14**
</details>

**Comment by ohayon** [comment]
Hey @RishabhTayal, I believe that the URL you are using is not a valid repo URL. Could you try to use `https://github.com/fastlane/fastlane` and see if that works? Thanks! 🐰

**Comment by RishabhTayal** [comment]
This works. Need to change this in the docs. I will update it and create a PR. 👍
