### ISSUE TITLE
[scan] Question: what's the correct way of specifying iOS version in scan?

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/fastlane#10338]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using `scan(device: "iPhone 7 Plus (10.3.1)")`, but using the exact string in Xcode doesn't work. 

<img width="160" alt="screen shot 2017-09-15 at 11 13 29 am" src="https://user-images.githubusercontent.com/685609/30497281-252f8906-9a07-11e7-8b63-b7b396423b67.png">

> [11:01:08]: No simulators found that are equal to the version of specifier (10.3.1) and greater than or equal to the version of deployment target (0)
> [11:01:08]: Ignoring 'iPhone 7 Plus (10.3.1)', couldn’t find matching simulator
> [11:01:08]: Couldn't find any matching simulators for '["iPhone 7 Plus (10.3.1)"]' - falling back to default simulator

```
Available destinations for the "All Tests" scheme:
{ platform:iOS Simulator, id:D392C177-0E5B-45DE-8CDC-D2191F7C4A5D, OS:10.3.1, name:iPad (5th generation) }
{ platform:iOS Simulator, id:05C68794-EE48-400C-A6C1-DCB2B013D291, OS:11.0, name:iPad (5th generation) }
{ platform:iOS Simulator, id:5593F602-45D1-4E73-8D2E-7BE3B7E1C7D3, OS:10.3.1, name:iPad Air }
{ platform:iOS Simulator, id:04455522-D1AB-48F8-90FD-6D00F58A3FCF, OS:11.0, name:iPad Air }
{ platform:iOS Simulator, id:068D1827-7760-4305-9692-ABC57941E49B, OS:10.3.1, name:iPad Air 2 }
{ platform:iOS Simulator, id:1C47CF59-2BD5-4026-AA0F-1CD2D71AE138, OS:11.0, name:iPad Air 2 }
{ platform:iOS Simulator, id:84C66A88-79FB-42B5-8A0D-CC321433975A, OS:10.3.1, name:iPad Pro (9.7 inch) }
{ platform:iOS Simulator, id:BC341610-E3E1-4266-965F-955AE10C34B9, OS:11.0, name:iPad Pro (9.7 inch) }
{ platform:iOS Simulator, id:CDACF185-A9CE-4385-8DE3-7DFD7C9A4FCC, OS:10.3.1, name:iPad Pro (10.5-inch) }
{ platform:iOS Simulator, id:5DC24578-2590-4652-B3DF-32D7A8B7160E, OS:11.0, name:iPad Pro (10.5-inch) }
{ platform:iOS Simulator, id:8B1A9C1C-D9EC-462D-95BB-7F8293B0C4BC, OS:10.3.1, name:iPad Pro (12.9 inch) }
{ platform:iOS Simulator, id:D5B0EB80-B56C-4363-9B33-06AC90178125, OS:11.0, name:iPad Pro (12.9 inch) }
{ platform:iOS Simulator, id:80E08231-F51D-4D9C-9FC1-2E18DFBD2267, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }
{ platform:iOS Simulator, id:1D347D5C-9957-4901-9635-44D3BD0073C5, OS:11.0, name:iPad Pro (12.9-inch) (2nd generation) }
{ platform:iOS Simulator, id:E615A208-2E1B-4F91-AC7E-E0E8C7827E23, OS:10.3.1, name:iPhone 5 }
{ platform:iOS Simulator, id:62A42023-CCF4-4FF0-801B-7FF7F6FE8989, OS:10.3.1, name:iPhone 5s }
{ platform:iOS Simulator, id:A984A9F1-49FF-4218-9883-9C133026754C, OS:11.0, name:iPhone 5s }
{ platform:iOS Simulator, id:CB563767-96CE-4F93-8B74-2B725BFC46FE, OS:10.3.1, name:iPhone 6 }
{ platform:iOS Simulator, id:9BDC3419-3E4E-49E3-87C7-BDB9056D2BF0, OS:11.0, name:iPhone 6 }
{ platform:iOS Simulator, id:11DFA03C-7B26-45D3-81DC-2ABFE9183887, OS:10.3.1, name:iPhone 6 Plus }
{ platform:iOS Simulator, id:FA54D11A-6886-41BF-85EB-DB17EB950810, OS:11.0, name:iPhone 6 Plus }
{ platform:iOS Simulator, id:1527EFA9-0E6D-44C1-A3D6-5EBC75D85A0E, OS:10.3.1, name:iPhone 6s }
{ platform:iOS Simulator, id:9A44B3DA-9B7D-4DC7-AB4C-6AC0BA1BED63, OS:11.0, name:iPhone 6s }
{ platform:iOS Simulator, id:4D44773A-9F91-42A8-AD1F-E5F219FD9131, OS:10.3.1, name:iPhone 6s Plus }
{ platform:iOS Simulator, id:37879ACD-653D-4B50-B8E2-4D7A2D45F7BC, OS:11.0, name:iPhone 6s Plus }
{ platform:iOS Simulator, id:D4D9DB1D-1664-4682-9E89-22B4E336CAE9, OS:10.3.1, name:iPhone 7 }
{ platform:iOS Simulator, id:B1A3829E-AC49-4728-8E03-14334AED431A, OS:11.0, name:iPhone 7 }
{ platform:iOS Simulator, id:9F9A2745-78C3-4577-A74B-FB6243C22090, OS:10.3.1, name:iPhone 7 Plus }
{ platform:iOS Simulator, id:3F0E2DB8-F1EC-412B-93F4-EAC4B4B28A18, OS:11.0, name:iPhone 7 Plus }
{ platform:iOS Simulator, id:34C35DA2-161C-47E8-B98C-EE48E81762D1, OS:11.0, name:iPhone 8 }
{ platform:iOS Simulator, id:0B0E6607-98B7-437F-8DAB-DD14D0DC5D8F, OS:11.0, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:49A4E931-5262-4497-834C-772D640DE559, OS:10.3.1, name:iPhone SE }
{ platform:iOS Simulator, id:DC424D2A-19E3-494A-99A4-1F8A7F6D0FA7, OS:11.0, name:iPhone SE }
{ platform:iOS Simulator, id:ECB5285C-95C2-4AE1-B77F-3794C2FF1518, OS:11.0, name:iPhone X }

Ineligible destinations for the "All Tests" scheme:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.1       |
| json                      | 2.1.0        |
| excon                     | 0.58.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.12.2       |
| bundler                   | 1.13.7       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-09-15**
</details>

**Comment by ohayon** [comment]
Hey @NachoSoto, I could be wrong here, but I don't believe there currently is a way to specify OS version 😞.

**Comment by NachoSoto** [comment]
`xcodebuild` allows specifying a platform like `'platform=iOS Simulator,name=iPhone SE,OS=10.1'`. Are you saying that `scan` doesn't support it (yet)?

**Comment by NachoSoto** [comment]
Oh I could get this to work using `scan -d 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1'`.
Any chance we could get another parameter, parallel to `-a` (device), that helps disambiguate it when there are multiple devices with different iOS versions?

**Comment by KrauseFx** [comment]
@NachoSoto I think using the `destination` parameter, you should have full control, and it should be passed over directly to `xcodebuild`. Is that not the case?

**Comment by NachoSoto** [comment]
Yeah see my last comment, I got it working with `-d`, but see my question:
> Any chance we could get another parameter, parallel to -a (device), that helps disambiguate it when there are multiple devices with different iOS versions?

**Comment by Sulfkain** [comment]
@NachoSoto I have something similar, and what I did was call a bash command to get the correct simulator:
To get an AppleWatch simultaor for ex:
`device = %x(instruments -s | grep '+ Apple Watch' | cut -d "+" -f1 | tail -n1 | xargs)`

Then I do:
```
scan(
      scheme: scheme,
      clean: true,
      devices: [device]
   )
```

I now it's a workaround but maybe usefull for you or other users

**Comment by thedavidharris** [comment]
Also having an issue with this, not really sure how to get it formatted. `iPhone 6s (10.2)` worked in the past, seems like after upgrading Xcode (or something, not really sure) can't do something like `iPhone 6s (10.3.1)` even though that's exactly what's listed under `instruments -s`

**Comment by szweier** [comment]
Seeing the same issue, for the time being I'm just choosing iPhone 7 and leaving the version off. Not ideal but seems to be functional.

**Comment by micnguyen** [comment]
This would be a great addition, to allow specific iOS versions. Currently passing in multiple device destinations does work but messy. I do remembe specifying the device name/iOS version used to work but no more.

**Comment by Buju77** [comment]
yes, we are also seeing this issue. we also used to specify `iPhone 7 (10.3)` but that doesn't work anymore. so are there some kind of proper solution to this already?

**Comment by ohayon** [comment]
Hey @Buju77 did you get a chance to try out this workaround mentioned above?
