### ISSUE TITLE
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

### ISSUE THREAD

**Issue by msand** [fastlane/fastlane#10334]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane pilot upload
[13:06:48]: fastlane detected a Gemfile in the current directory
[13:06:48]: however it seems like you don't use `bundle exec`
[13:06:48]: to launch fastlane faster, please use
[13:06:48]: 
[13:06:48]: $ bundle exec fastlane pilot upload
[13:06:48]: 
[13:06:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:06:50]: Login to iTunes Connect (user@domain.tld)
[13:06:53]: Login successful
[13:06:54]: Ready to upload new build to TestFlight (App: removed)...
[13:06:54]: Going to upload updated app to iTunes Connect
[13:06:54]: This might take a few minutes. Please don't interrupt the script.
[13:10:20]: Transporter transfer failed.
[13:10:20]: 
[13:10:20]: 
[13:10:20]: Return status of iTunes Transporter was 1: 
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

[!] Error uploading ipa file, for more information see above
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.3                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.56.0"

default_platform :ios
ENV["ITC_TEAM_ID"] = "removed"
project "ios/Keventajat.xcodeproj"
scheme "Keventajat"


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    update_project_team(
      path: "ios/Keventajat.xcodeproj",
      teamid: "removed"
    )
    match(type: "appstore") # more information: https://codesigning.guide

    cert
    sigh(force: true)
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "fi.keventajat.mobi" # The bundle identifier of your app
apple_id "user@domain.tld" # Your Apple email address

team_id "removed" # Developer Portal Team ID
itc_team_id "removed"
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_project_codesigning            | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| slack-notifier                                        | 1.5.1        |
| CFPropertyList                                        | 2.3.5        |
| claide                                                | 1.0.2        |
| colored2                                              | 3.1.2        |
| nanaimo                                               | 0.2.3        |
| xcodeproj                                             | 1.5.1        |
| rouge                                                 | 1.11.1       |
| xcpretty                                              | 0.2.6        |
| unicode-display_width                                 | 1.1.3        |
| terminal-table                                        | 1.7.3        |
| multipart-post                                        | 2.0.0        |
| word_wrap                                             | 1.0.0        |
| public_suffix                                         | 2.0.5        |
| tty-screen                                            | 0.5.0        |
| babosa                                                | 1.0.2        |
| colored                                               | 1.2          |
| highline                                              | 1.7.8        |
| commander-fastlane                                    | 4.4.5        |
| unf_ext                                               | 0.0.7.4      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20170404 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| fastimage                                             | 2.1.0        |
| gh_inspector                                          | 1.0.3        |
| json                                                  | 1.8.1        |
| mini_magick                                           | 4.5.1        |
| multi_xml                                             | 0.6.0        |
| rubyzip                                               | 1.2.1        |
| security                                              | 0.1.3        |
| xcpretty-travis-formatter                             | 0.0.4        |
| bundler                                               | 1.14.6       |
| faraday_middleware                                    | 0.11.0.1     |
| declarative                                           | 0.0.10       |
| declarative-option                                    | 0.1.0        |
| representable                                         | 3.0.4        |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| little-plugger                                        | 1.1.4        |
| logging                                               | 2.2.2        |
| jwt                                                   | 1.5.6        |
| os                                                    | 0.9.6        |
| signet                                                | 0.7.3        |
| googleauth                                            | 0.5.1        |
| httpclient                                            | 2.8.3        |
| google-api-client                                     | 0.13.6       |
| excon                                                 | 0.59.0       |
| plist                                                 | 3.3.0        |
| faraday                                               | 0.13.1       |
| fastlane-plugin-update_project_codesigning            | 0.2.0        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0        |
</details>

*generated on:* **2017-09-15**
</details>

**Comment by ohayon** [comment]
Hey @msand are you building your app in Xcode 9 or 8? 🐙

**Comment by kielgillard** [comment]
We're using Xcode 9 and getting an iTMS uploader error like this:
```
  | Return status of iTunes Transporter was 1: The filename kiosk(9f262739838070af272a2934173f8f246dec8e2311670aea428210e8f4501e5b).ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
  | The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```
However the .ipa is simply named `kiosk.app`.

**Comment by KrauseFx** [comment]
@kielgillard your issue doesn't seem to be related, for some reason the ipa file is being renamed to `kiosk(9f262739838070af272a2934173f8f246dec8e2311670aea428210e8f4501e5b).ipa` instead of just `9f262739838070af272a2934173f8f246dec8e2311670aea428210e8f4501e5b.ipa`, I wonder why this is happening - what version of fastlane are you using, and how did you install it?

**Comment by dtrukr** [comment]
@kielgillard This seems to be related to https://github.com/fastlane/fastlane/issues/10327

**Comment by KrauseFx** [comment]
Yeah, seems like you were using the nightly build, that predicated something being broken once we ship, which we shipped yesterday, and broke everything, hehe :)

**Comment by caroaguilar** [comment]
I'm getting this issue too, tried with both Xcode 8.3 and Xcode 9

**Comment by dflourusso** [comment]
Same issue, some solution?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pt_BR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.60.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| awesome_print             | 1.7.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-10-05**
</details>

**Comment by KrauseFx** [comment]
If you're running the most recent fastlane release, then those issues are not related. Please submit a new issue with all the output and information for us to debug
