### ISSUE TITLE
Cron job failed to execute fastlane setup

### ISSUE THREAD

**Issue by deepaksahu-mob-ibtech** [fastlane/fastlane#10336]
I am able to run the fastlane setup via terminal as expected and result success but when i run same setup using crontab it has thrown many errors. 
I tried number of things but still not success

After the below command execution within the fastlane thrown error
**xcodebuild -showBuildSettings -workspace ./AppManager.xcworkspace -scheme** AppManagerUITests

I tried to run cron job using below combination and permutation with complete path of script file

1. execute job using importing #!/bin/bash, #!/bin/sh in script file and also source current_user
2. execute job with sudo su command with current user bash_profile
3. execute job with /bin/bash, /bin/sh, /bin/bash -x, /bin/sh -x in cron job like this
4. execute job by setting all environment variable in script file
	export LANG=en_US.UTF-8
       export LANGUAGE=en_US.UTF-8
       export LC_ALL=en_US.UTF-8

5. run fastlane env work fine as expected in terminal and cron
6. I also try with launchd which is recommended by apple instead of crontab.
7. I also gave all script file to execute permission 

https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html

So cron or launchd its not able to execute the fastlane gem which is installed at root level and have all persmision.

**Comment by deepaksahu-mob-ibtech** [comment]
1. I included **fastlane dev**  in scripts so command return fastlane: command not found 
2. When I added completed path in script **/usr/local/bin/fastlane env** it;s wokring with below error

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.55.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| json                      | 2.1.0        |
| bundler                   | 1.15.4       |
</details>


*generated on:* **2017-09-15**
</details>

**Comment by ohayon** [comment]
Hey @deepaksahu-mob-ibtech, I am not so familiar with running fastlane as a cron job, but could you share some of the output from the job so that we can see some more context? Thank you! 🚀

**Comment by PetrosIchor** [comment]
I'm haven't had much experience either with cron, but this is something I've been looking into to solve some scheduling needs.

https://github.com/javan/whenever

It's a ruby based cron utility.  Being that fastlane is also ruby, I feel like it would bring benefits by sharing the same language/dependencies.  Personally, I try to avoid increasing the requirements for my CI (practicing KISS and DRY if that makes sense)

**Comment by deepaksahu-mob-ibtech** [comment]
We tried different way to execute our script file instead of crontab, because issue not resolved

**Comment by YRafalsky** [comment]
faced same issue.
actually problem's root is keychain. 
Cron runs your process from your user name BUT it uses system keychain. 
Saddest part is that you CANNOT CHANGE default keychain from system to yours. 
Fastlane uses default keychain
So you have 2 options
1) rewrite fastlane to use custom keychain (all of these `security` commands can work with custom keychain)
2) make ssh connection in you cron command and ssh to your machine etc. 

We've choose 2nd way after 2 days of struggle and pain
```
*/5 * * * * ssh  -i ~/.ssh/id_rsa user_name@88.88.88.88 "/bin/bash ~/bash_script_to_run.sh"
```
we did not tried to use 127.0.0.1 address, maybe it could work
