### ISSUE TITLE
docker pull doesn't work?

### ISSUE THREAD

**Issue by robertslowley** [fastlane/fastlane#10344]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
Trying to set up boarding to run in docker on AWS... Please help :-)

> GERTY3000:boarding robhu$ ls -la
> total 0
> drwxr-xr-x   2 robhu  staff   64 18 Sep 09:49 .
> drwxr-xr-x  25 robhu  staff  800 18 Sep 09:49 ..
> GERTY3000:boarding robhu$ docker pull emcniece/docker-boarding
> Using default tag: latest
> Error response from daemon: manifest for emcniece/docker-boarding:latest not found

**Comment by KrauseFx** [comment]
Please submit a separate issue on the fastlane/boarding repo. I haven't used docker myself for boarding, we'd recommend using the one click Heroku deployment button instead 👍
