### ISSUE TITLE
delivery init fails on screenshots download 

### ISSUE THREAD

**Issue by kamleshkatios** [fastlane/fastlane#10349]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane delivery init fails when downloading images. All other meta data is downloaded.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane deliver init -a com.test.app  -u aaaaaa@test.com
[06:26:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[06:26:58]: Login to iTunes Connect (aaaaaa@test.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for aaaaaa@test.com): **********
[06:27:05]: Login successful

+--------------------------------------+------------------------------------+
|                          deliver 2.56.0 Summary                           |
+--------------------------------------+------------------------------------+
| app_identifier                       | com.test.app      
| username                             | aaaaaa@test.com
| run_precheck_before_submit           | false                              |
| screenshots_path                     | ./screenshots                      |
| metadata_path                        | ./metadata                         |
| edit_live                            | false                              |
| platform                             | ios                                |
| skip_binary_upload                   | false                              |
| skip_screenshots                     | false                              |
| skip_metadata                        | false                              |
| skip_app_version_update              | false                              |
| force                                | false                              |
| submit_for_review                    | false                              |
| automatic_release                    | false                              |
| overwrite_screenshots                | false                              |
| precheck_default_rule_level          | warn                               |
| ignore_language_directory_validation | false                              |
+--------------------------------------+------------------------------------+

[06:27:08]: Writing to './metadata/en-US/description.txt'
[06:27:08]: Writing to './metadata/en-US/keywords.txt'
[06:27:08]: Writing to './metadata/en-US/release_notes.txt'
[06:27:08]: Writing to './metadata/en-US/support_url.txt'
[06:27:08]: Writing to './metadata/en-US/marketing_url.txt'
[06:27:08]: Writing to './metadata/en-US/promotional_text.txt'
[06:27:08]: Writing to './metadata/en-US/name.txt'
[06:27:08]: Writing to './metadata/en-US/subtitle.txt'
[06:27:08]: Writing to './metadata/en-US/privacy_url.txt'
[06:27:08]: Writing to './metadata/copyright.txt'
[06:27:08]: Writing to './metadata/primary_category.txt'
[06:27:08]: Writing to './metadata/secondary_category.txt'
[06:27:08]: Writing to './metadata/primary_first_sub_category.txt'
[06:27:08]: Writing to './metadata/primary_second_sub_category.txt'
[06:27:08]: Writing to './metadata/secondary_first_sub_category.txt'
[06:27:08]: Writing to './metadata/secondary_second_sub_category.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/trade_name.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/address_line1.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/city_name.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/state.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/country.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/postal_code.txt'
[06:27:08]: Writing to './metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'
[06:27:08]: Writing to './metadata/review_information/first_name.txt'
[06:27:08]: Writing to './metadata/review_information/last_name.txt'
[06:27:08]: Writing to './metadata/review_information/phone_number.txt'
[06:27:08]: Writing to './metadata/review_information/email_address.txt'
[06:27:08]: Writing to './metadata/review_information/demo_user.txt'
[06:27:08]: Writing to './metadata/review_information/demo_password.txt'
[06:27:08]: Writing to './metadata/review_information/notes.txt'
[06:27:08]: Successfully created new configuration files.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/lib/ruby/2.3.0/open-uri.rb:258:in `open_http': [!] Non-HTTP proxy URI: https://server.proxy.test:port/ (RuntimeError)
	from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/deliver/lib/deliver/setup.rb:100:in `generate_metadata_files'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/deliver/lib/deliver/setup.rb:30:in `generate_deliver_file'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/deliver/lib/deliver/setup.rb:8:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/deliver/lib/deliver/commands_generator.rb:110:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/deliver/lib/deliver/commands_generator.rb:176:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.56.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                       |
| Ruby                        | 2.3.1                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Ubuntu 16.04.3 LTS debian_based stretch/sid (4.4.0-92-generic) |
| Ruby Lib Dir                | /usr/lib                                                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-09-18**
</details>

**Comment by KrauseFx** [comment]
Seems like that's an error with your internet connection, can you try it from a different connection and different Mac, maybe with a VPN?
