### ISSUE TITLE
iPad & iPhone screenshots wrong size on XCode 9

### ISSUE THREAD

**Issue by soheil** [fastlane/fastlane#10342]
My iPhone screenshots >5s are 3 pixels shorter than what they should be and iPad screenshots 1 pixel shorter. I am using the latest version of fastlane and the screenshot helper and XCode 9 GM.

This is related to issue https://github.com/fastlane/fastlane/issues/10259

**Comment by KrauseFx** [comment]
Let's move discussion over to https://github.com/fastlane/fastlane/issues/10259
