### ISSUE TITLE
gym is chosing the wrong provisioning profile and ignoring export_options

### ISSUE THREAD

**Issue by faithfracture** [fastlane/fastlane#10341]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
For whatever reason, Gym is selecting my AppleTV app provisioning profile rather than my iOS profile. This was never a problem before - I just built this two weeks ago with no problem. Furthermore, Gym is ignoring what I pass to export_options. According to [this documentation](https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up), I should be able to do what I'm trying to do. However, you can see in the output that what I am passing to `export_options` is not getting used.

##### Complete output when running fastlane, including the stack trace and command used

```
bundle exec fastlane openeye

// Extraneous output omitted

[17:17:41]: -----------------
[17:17:41]: --- Step: gym ---
[17:17:41]: -----------------
[17:17:41]: $ xcodebuild -list -workspace ./Apex.xcworkspace
[17:17:44]: Couldn't automatically detect the provisioning profile mapping
[17:17:44]: There were multiple profiles for bundle identifier(s): com.pco-inc.OpenEye-Mobile
[17:17:44]: You need to provide an explicit mapping of what provisioning
[17:17:44]: profile to use for each bundle identifier of your app
[17:17:44]: Couldn't automatically detect the provisioning profile mapping
[17:17:44]: There were multiple profiles for bundle identifier(s): com.pco-inc.OpenEye-Mobile
[17:17:44]: You need to provide an explicit mapping of what provisioning
[17:17:44]: profile to use for each bundle identifier of your app
[17:17:45]: Detected provisioning profile mapping: {:"com.pco-inc.OpenEye-Mobile"=>"Apex TV"}

+-------------------------------------------------------------------+----------------------------------------------------------------+
|                                                       Summary for gym 2.56.0                                                       |
+-------------------------------------------------------------------+----------------------------------------------------------------+
| scheme                                                            | OpenEye                                                        |
| clean                                                             | true                                                           |
| include_symbols                                                   | true                                                           |
| include_bitcode                                                   | true                                                           |
| output_name                                                       | OpenEye-1.3.1.1                                                |
| export_method                                                     | app-store                                                      |
| export_options.provisioningProfiles.com.pco-inc.OpenEye-Mobile    | Apex TV                                                        |
| workspace                                                         | ./Apex.xcworkspace                                             |
| destination                                                       | generic/platform=iOS                                           |
| build_path                                                        | /Users/jordanbondo/Library/Developer/Xcode/Archives/2017-09-15 |
| output_directory                                                  | .                                                              |
| silent                                                            | false                                                          |
| skip_package_ipa                                                  | false                                                          |
| buildlog_path                                                     | ~/Library/Logs/gym                                             |
| xcode_path                                                        | /Applications/Xcode.app                                        |
+-------------------------------------------------------------------+----------------------------------------------------------------+

// Everything after this is irrelevant

```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./.fastlane/Fastfile`</summary>

```ruby

def doBuild(options, project, scheme, profile)
  fullVersion = set_build_number(options, project)
  outputFile = scheme
  outputFile += "-pre" unless !options[:beta]
  outputFile += "-#{fullVersion}"

  gym(
    scheme: scheme, 
    clean: true,
    include_symbols: true,
    include_bitcode: true,
    output_name: outputFile,
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "com.pco-inc.OpenEye-Mobile" => "Apex"
      }
    }
  )
  pilot(skip_submission: true, skip_waiting_for_build_processing: true) unless !options[:deploy]
end

desc "Build the OpenEye Mobile iOS app"
lane :openeye do |options|
  ENV["TEAM_ID"] = OpeneyeTeamId
  ENV["APPLE_ID"] = OpeneyeAppleId
  ENV["APP_IDENTIFIER"] = OpeneyeAppId
  if options[:beta]
    ENV["APP_IDENTIFIER"] = OpeneyeAppId + '.beta'
    switch_beta(IosProject, OpeneyeScheme, OpeneyePlist)
  end
  doBuild(options, IosProject, OpeneyeScheme, OpeneyeProfile) unless options[:configOnly]
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0   | ✅ Up-To-Date  |
| fastlane-plugin-badge                                 | 0.8.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.1.2        |
| bundler                                               | 1.15.4       |
| io-console                                            | 0.4.6        |
| CFPropertyList                                        | 2.3.5        |
| public_suffix                                         | 2.0.5        |
| addressable                                           | 2.5.2        |
| babosa                                                | 1.0.2        |
| curb                                                  | 0.9.4        |
| fastimage                                             | 2.1.0        |
| colored                                               | 1.2          |
| highline                                              | 1.7.8        |
| commander-fastlane                                    | 4.4.5        |
| dotenv                                                | 2.2.1        |
| excon                                                 | 0.59.0       |
| multipart-post                                        | 2.0.0        |
| faraday                                               | 0.13.1       |
| unf_ext                                               | 0.0.7.4      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20170404 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| faraday_middleware                                    | 0.12.2       |
| gh_inspector                                          | 1.0.3        |
| jwt                                                   | 1.5.6        |
| little-plugger                                        | 1.1.4        |
| multi_json                                            | 1.12.2       |
| logging                                               | 2.2.2        |
| memoist                                               | 0.16.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.7.3        |
| googleauth                                            | 0.5.3        |
| httpclient                                            | 2.8.3        |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| declarative                                           | 0.0.10       |
| declarative-option                                    | 0.1.0        |
| uber                                                  | 0.1.0        |
| representable                                         | 3.0.4        |
| retriable                                             | 3.1.1        |
| google-api-client                                     | 0.13.6       |
| json                                                  | 2.1.0        |
| mini_magick                                           | 4.5.1        |
| multi_xml                                             | 0.6.0        |
| plist                                                 | 3.3.0        |
| rubyzip                                               | 1.2.1        |
| security                                              | 0.1.3        |
| slack-notifier                                        | 1.5.1        |
| terminal-notifier                                     | 1.8.0        |
| unicode-display_width                                 | 1.3.0        |
| terminal-table                                        | 1.8.0        |
| tty-screen                                            | 0.5.0        |
| word_wrap                                             | 1.0.0        |
| claide                                                | 1.0.2        |
| colored2                                              | 3.1.2        |
| nanaimo                                               | 0.2.3        |
| xcodeproj                                             | 1.5.1        |
| rouge                                                 | 2.0.7        |
| xcpretty                                              | 0.2.8        |
| xcpretty-travis-formatter                             | 0.0.4        |
| badge                                                 | 0.8.5        |
| fastlane-plugin-badge                                 | 0.8.2        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0        |
</details>

*generated on:* **2017-09-15**
</details>

**Comment by faithfracture** [comment]
I managed to find a workable solution.

First, some more info on my project structure:
I have a workspace that has several projects in it. One of the projects is an iOS project and another is a tvOS project. These projects share a significant amount of code and have other dependent projects in the workspace, so it is quite a lot easier to work with them by having them all in the same workspace.

I'm pretty sure the problem here is that both the tvOS and iOS apps share the same application identifier, so Gym is trying to find the appropriate provisioning profile for the one it is building and finding two with the same application id (makes sense). What's not clear is _why_ it is choosing the tvOS provisioning profile _NOW_ when it hasn't done so in the past.

To work around this (and the issue with not actually being able to specify `export_options: {provisioningProfiles: {"bundleId" => "profile"} }` in the gym command in the fast file), I created separate exportOptions.plist files for both the iOS and tvOS projects and pass the appropriate one to gym's `export_options` parameter depending on the target being built. Things seem to be working correctly again after doing that.

**Comment by ryang1428** [comment]
Related issue: https://github.com/fastlane/fastlane/issues/10315

**Comment by nicolasbraun** [comment]
I am working on a fix, will be proposing a PR soon

**Comment by nicolasbraun** [comment]
Note that if using match, match generates a maping so the build works despite the error

**Comment by KrauseFx** [comment]
@nicolasbraun can you send me a quick email (on my profile)? We'd love to help 👍

**Comment by abarnes** [comment]
Any resolution here? I just ran into this issue today

**Comment by hcrub** [comment]
+1

**Comment by lbrownell-gpsw** [comment]
I'm having what I take is this problem as well, and can't get around it.  Was building just fine with Xcode 8.3.3 (and in fact still am; we have a branch of the app that is still on 8.3.3 and it's chugging along without incident -- same build machine, same build job, same fastfile, both always using the latest version of Fastlane).

The app in question has two targets: the app itself, and a widget.  Both need codesigning at export time.

Before gym, I call sigh, no parameters.  It successfully finds the signing bits for the app, but ignores the widget.  Which seems to be fine, as the build works.  I don't see a way to specify more than one target or profile in any case using sigh's parameter set, so I suppose that's a good thing.
```
------------------
--- Step: sigh ---
------------------

+-------------------------------------+---------------------------+
|                     Summary for sigh 2.59.0                     |
+-------------------------------------+---------------------------+
| adhoc                               | false                     |
| development                         | false                     |
| skip_install                        | false                     |
| force                               | false                     |
| app_identifier                      | com.mycompany.studio      |
| username                            | rm@mycompany.com          |
| team_id                             | 9999999999                |
| ignore_profiles_with_different_name | false                     |
| skip_fetch_profiles                 | false                     |
| skip_certificate_verification       | false                     |
| platform                            | ios                       |
+-------------------------------------+---------------------------+

Starting login with user 'rm@mycompany.com'
Successfully logged in
Fetching profiles...
Provisioning Profile 'MyApp AdHoc' is not valid, skipping this one...
Verifying certificates...
Found 1 matching profile(s)
Downloading provisioning profile...
Successfully downloaded provisioning profile...
Installing provisioning profile...
/Users/builder-mobile/bundle-src-develop-MyApp_ios/MyApp_ios/AppStore_com.mycompany.studio.mobileprovision
Setting Provisioning Profile type to 'app-store'
```
Using this gym invocation:
```
gym(
  clean: true,
  project: "./MyApp/MyApp.xcodeproj",
  scheme: options[:scheme],
  archive_path: options[:archive],
  sdk: "iphoneos",
  silent: "true",
  output_name: options[:output],
  output_directory: "..",
  configuration: options[:configuration],
  buildlog_path: '.',
  include_bitcode: "false",
  xcargs: "-allowProvisioningUpdates",
  export_method: options[:method],
  export_team_id: options[:team],
  export_xcargs: "-allowProvisioningUpdates",
  #export_options: ".fastlane/ExportOptions.plist"
  export_options: {
    provisioningProfiles: {
      "com.mycompany.studio.todayextension" => "MyApp Today Widget",
      "com.mycompany.studio" => "MyApp AppStore"
    }
  }
)
```
I get this plist file -- which ignores the provisioning profile options specified above:
```
 ▸ -----------------------------------------
 ▸ {
 ▸   "provisioningProfiles": {
 ▸     "com.mycompany.studio": "MyApp AppStore"
 ▸   },
 ▸   "method": "app-store",
 ▸   "uploadBitcode": false,
 ▸   "teamID": "9999999999"
 ▸ }
 ▸ -----------------------------------------
 ```

Tried this instead, providing an external plist file:
```
gym(
  clean: true,
  project: "./MyApp/MyApp.xcodeproj",
  scheme: options[:scheme],
  archive_path: options[:archive],
  sdk: "iphoneos",
  silent: "true",
  output_name: options[:output],
  output_directory: "..",
  configuration: options[:configuration],
  buildlog_path: '.',
  include_bitcode: "false",
  xcargs: "-allowProvisioningUpdates",
  export_xcargs: "-allowProvisioningUpdates",
  export_options: ".fastlane/ExportOptions.plist"
)
```
The plist file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
	<key>teamID</key>
	<string>9999999999</string>
	<key>uploadBitcode</key>
	<string>false</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.mycompany.studio.todayextension</key>
		<string>Myapp Today Widget</string>
		<key>com.mycompany.studio</key>
		<string>MyApp AppStore</string>
	</dict>
</dict>
</plist>
```

This plist file is also ignored; I get the same plist entries as before.  No error messages either, saying it can't find the plist file or whatever.  Vexing.

For both of the above examples I get this result:
```
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/dr/p326kb990jzfwt92wwhb4t7r0000gn/T/gym_config20170926-7353-1ix604z.plist -archivePath MyApp-AppStore.xcarchive -exportPath /var/folders/dr/p326kb990jzfwt92wwhb4t7r0000gn/T/gym_output20170926-7353-jcgnpm
2017-09-26 13:15:12.582 xcodebuild[9731:5167406] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/dr/p326kb990jzfwt92wwhb4t7r0000gn/T/MyApp_2017-09-26_13-15-12.581.xcdistributionlogs'.
2017-09-26 13:15:15.421 xcodebuild[9731:5167406] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7f8dffe03bb0>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
"Error Domain=IDEProfileLocatorErrorDomain Code=1 \"No profiles for 'com.mycompany.studio.todayextension' were found\" UserInfo={NSLocalizedDescription=No profiles for 'com.mycompany.studio.todayextension' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.mycompany.studio.todayextension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}",
"Error Domain=IDEProfileLocatorErrorDomain Code=1 \"No profiles for 'com.mycompany.studio' were found\" UserInfo={NSLocalizedDescription=No profiles for 'com.mycompany.studio' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.mycompany.studio'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}"
)}
error: exportArchive: No profiles for 'com.mycompany.studio.todayextension' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.mycompany.studio.todayextension' were found" UserInfo={NSLocalizedDescription=No profiles for 'com.mycompany.studio.todayextension' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.mycompany.studio.todayextension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

error: exportArchive: No profiles for 'com.mycompany.studio' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.mycompany.studio' were found" UserInfo={NSLocalizedDescription=No profiles for 'com.mycompany.studio' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.mycompany.studio'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

** EXPORT FAILED **
[13:15:15]: Exit status: 70
```
So, even though the plist options dogmatically provided by Fastlane *does* identify the required app profile, it can't find it.  Didn't expect that.  Not shocked that it couldn't find the widget profile.

Also, the detailed xcode log stops at "** ARCHIVE SUCCEEDED **".  Nothing in there from the export.

Any suggestions greatly appreciated.

**Comment by lbrownell-gpsw** [comment]
Resolved the problem above.  Turned off exporting the IPA in Fastlane and tried to do it manually. The problem was it couldn't authenticate with the account information in Xcode preferences.  Odd, since sigh was able to.  I deleted and re-created the account information, then the manual export worked.  So...tried Fastlane again, and IT worked.

Hopefully that helps someone else.

**Comment by pedro380085** [comment]
+!
