### ISSUE TITLE
App Store Name lookup

### ISSUE THREAD

**Issue by kd8ssq** [fastlane/fastlane#10348]
Question for the group.

Is there a way to do a lookup in the app store to see if an app store name is unique outside of running produce or deliver?  This new app store name character limit of 30 characters is really causing a problem for me and my customers.  Just trying to see if anyone has or knows of a way to do a lookup before running through the entire deployment process.

**Comment by dtrukr** [comment]
You mean you want to get name of one of your apps in iTunes Connect? If yes, you can have something like that in Fastfile:
`
Spaceship::Tunes.login(CredentialsManager::AppfileConfig.try_fetch_value(:apple_id))
app = Spaceship::Tunes::Application.find("com.xxx.xxx")
`

`app.latest_version.languages` will have an array of hashes with localised metadata

**Comment by KrauseFx** [comment]
Awesome, thanks for your help @dtrukr 👍

**Comment by kd8ssq** [comment]
@dtrukr thanks for the response.  I'm looking for a way to query the global list of App Store Apps to find out if a name I want to use is unique.  I would like to find out if the name is already used before running produce or deliver, that way I can go back to my customers and have them come up with a new one.

**Comment by KrauseFx** [comment]
Oh yeah, great question, check out `itunes_search_api.rb`: 

```ruby
FastlaneCore::ItunesSearchApi.fetch_by_identifier("...")
```

for searching for the app identifier, we're using the URL `https://itunes.apple.com/lookup?id=#{id}#{suffix}`. So I'm pretty sure there is also an iTunes API that works based on the app title, just check out the  docs and you'll probably find something 👍 

I'll close this issue for now, as it's not a fastlane question :)
