### ISSUE TITLE
Deliver downloading the wrong type of application

### ISSUE THREAD

**Issue by KatkayApps** [fastlane/fastlane#10340]
I have an app is a solely Apple TV app. I was creating an update for that app but by mistake I have added the update as being an iOS update. This app will never have an iOS update because like I said it is a tvOS app but thanks to the draconian iTunesConnect I was able to add an updated iOS version of an AppleTV app that I will never be able to delete.

Now I have created a new directory on my disk and I am trying to use deliver to grab all data I have there on iTunesConnect about my app.

I type: `fastlane deliver -j appletv`

and deliver downloads the iOS metadata and files that are basically clean.

How do I force it to grab the apple tv stuff?

thanks

**Comment by KatkayApps** [comment]
I have discovered by chance that Apple miraculously allow you to delete the incorrect update I have added. Anyway this issue probably persists for those that truly have an app that from the same entry delivers iOS and tvOS versions.

**Comment by KrauseFx** [comment]
Awesome, glad to hear 👍
