### ISSUE TITLE
Gemfile bundle update failing

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#10355]
I am using `Gemfile` for `fastlane` installation. I am posting the gem to local fastlane repo path. When running `bundle update` I get following error.

```
Bundler could not find compatible versions for gem "mime-types":
  In Gemfile:
    fastlane was resolved to 2.57.0, which depends on
      google-api-client (< 0.14.0, >= 0.13.1) was resolved to 0.13.1, which depends on
        mime-types (~> 3.0)

    rest-client (>= 1.8.0) was resolved to 1.8.0, which depends on
      mime-types (< 3.0, >= 1.16)
```

Here is the `Gemfile`:

<details><summary>Gemfile</summary>

```
source "https://rubygems.org"

gem 'cocoapods', '~> 1.3.1'
gem 'cocoapods-keys'

# gem "fastlane"
gemspec path: File.expand_path("/Users/rtayal/Desktop/Forks/fastlane")
```

</details>

**Comment by KrauseFx** [comment]
Can you `rm Gemfile.lock` and try again?

**Comment by RishabhTayal** [comment]
I tried that. It only fails when I point my Gemfile to local fork.

**Comment by paulryanclark** [comment]
I am seeing this issue as well. My bundle update pushed rest-client back to `1.6.7`

```
rest-client (1.6.7)
      mime-types (>= 1.16)
```
which is incompatible with the `fastlane-plugin-github_job_status`. See https://github.com/justinsinger/fastlane_plugins/issues/5
