### ISSUE TITLE
Server error (Google::Apis::ServerError)

### ISSUE THREAD

**Issue by jkammerer** [fastlane/fastlane#10361]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I get a "Server error" during upload. I tried --skip_upload_metadata and --skip_upload_screenshots, all languages and just one. Every time the same. I even did an init and uploaded the same content without changes.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane supply --json_key XXX.json --package_name com.XXX --skip_upload_apk --skip_upload_images --verbose --skip_upload_metadata

+-------------------------+-------------------------+
|             Summary for supply 2.57.0             |
+-------------------------+-------------------------+
| json_key                | XXX.json |
| package_name            | com.XXX       |
| skip_upload_apk         | true                    |
| skip_upload_images      | true                    |
| skip_upload_metadata    | true                    |
| track                   | production              |
| metadata_path           | ./metadata              |
| skip_upload_screenshots | false                   |
| validate_only           | false                   |
| check_superseded_tracks | false                   |
+-------------------------+-------------------------+

DEBUG [2017-09-19 08:13:30.87]: Fetching a new access token from Google...
INFO [2017-09-19 08:13:31.59]: Preparing to upload for language 'de-DE'...
INFO [2017-09-19 08:13:31.78]: Preparing to upload for language 'en-US'...
INFO [2017-09-19 08:13:31.97]: Uploading all changes to Google Play...

Looking for related GitHub issues on fastlane/fastlane...
Search query: Server error

URL: https://api.github.com/search/issues?q=Server%20error+repo:fastlane/fastlane
➡️  Building fine locally, failing on the Bitrise build server
    https://github.com/fastlane/fastlane/issues/10062 [open] 6 💬
    5 weeks ago

➡️  Error while running scan on Jenkins.
    https://github.com/fastlane/fastlane/issues/9745 [open] 20 💬
    5 days ago

➡️  FastlaneCore::Interface::FastlaneError: [!] Google Api Error: badRequest: Bad Request
    https://github.com/fastlane/fastlane/issues/10022 [open] 17 💬
    5 weeks ago

and 475 more at: https://github.com/fastlane/fastlane/search?q=Server%20error&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:221:in `check_status': [!] Server error (Google::Apis::ServerError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/api_command.rb:118:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:183:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:299:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:101:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:93:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.13.6/generated/google/apis/androidpublisher_v2/service.rb:92:in `commit_edit'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/client.rb:118:in `block in commit_current_edit!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/client.rb:367:in `call_google_api'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/client.rb:118:in `commit_current_edit!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/uploader.rb:36:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.57.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.57.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| excon                     | 0.59.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.12.2       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| bundler                   | 1.15.4       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-09-19**
</details>

**Comment by KrauseFx** [comment]
Did this work before? Have you tried running it on a different Mac?

**Comment by jkammerer** [comment]
It worked before, many times. No, not tried on a different Mac.

**Comment by swl367** [comment]
I'm also getting a similar issue where I'm stuck on 'fetching a new access token from google'
This was working for me in the past week.

**Comment by jkammerer** [comment]
This was related to an issue on Google's side. They confirmed this and fixed the bug. Now it works. Closing ticket.
