### ISSUE TITLE
Xcode 9 GM: Gym auto selects provisioning profile mapping wrong in an Xcode project with multiple configs

### ISSUE THREAD

**Issue by zapjonny** [fastlane/fastlane#10363]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```
Generated plist file with the following values:
/// incorrect mappings ///
```

Basically like https://github.com/fastlane/fastlane/issues/9890 - that issue is still an issue and needs fixing... The process which generates a plist file with provisioning mappings does so but the mappings are incorrect. Basically the profiles always selected the profs selected for DEBUG configs, instead of the expected profs for ADHOC/INHOUSE configs. I think the last few comments on the original issue are close to finding the cause/fix for this.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane version 2.57.1

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Sorry, this output included too many secrets :-P

**Comment by zapjonny** [comment]
> It seems like this issue might be related to code signing 🚫
> 
> Have you seen our new Code Signing Troubleshooting Guide? It will help you resolve the most common code signing issues 👍

Yes and https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up does not work. It ignores that `export_options` setting.

**Comment by ryang1428** [comment]
Related: https://github.com/fastlane/fastlane/issues/10315

**Comment by zapjonny** [comment]
So, I'll try to explain a bit more:

I use a workspace (initially because cocoapods demanded one)

It includes a couple of projects, only of which ones is a real iOS app. (have a few command line tools there in the form of projects too) (I think this should be pretty irrelevant)

Have a couple of schemes. Most are for the iOS app - debug, release, adhoc and appstore schemes. There are schemes for the tools too so they can be easily run, and also a few schemes for tests/uitests.

For the main iOS app, there are four configurations; debug, release, adhoc(>inhouse), appstore

Sometimes Xcode provisioning auto works, but many times, especially when running from fastlane build scripts they wouldn't, so I mostly use manual settings here. I have created stuff like this

<appname>_<environment>_<prov.prof.revisionnumber>
myapp_dev_1
myapp_inhouse_4
myapp_appstore_3

where the provision number is just a manually bumped number whenever I need to recreate that file when a new team member joined, some distribution certificate is renewed or whatever. I don't keep old profiles around to minimize confusion.

And as has been noted in https://github.com/fastlane/fastlane/issues/9890 , it looks like Gym selects Debug profiles for adhoc/inhouse builds. (For me, YMMV, because the error might be a sorting issue in a loop somewhere etc)

**Comment by zapjonny** [comment]
Fun fact: the current problematic lane uses gym setting export_method: enterprise

**Comment by zapjonny** [comment]
I but of summary of the above, I get the feeling that Gym sometimes:

- Selects incorrect bundle id at sign time (not the one that should be related to the scheme>target)
- Maps an incorrect prov profile to an incorrect bundle id, for instance uses a debug profile for a bundle id that belongs to a adhoc/inhouse/enterprise build.

**Comment by zapjonny** [comment]
Also, in line with other ongoing discussions, this setup (specifically including **export_xcargs: '-allowProvisioningUpdates',**) seems to be working well, if I change said target to use automatic provisioning inside Xcode:

gym(scheme: thescheme,
      export_method: theexportmethod, # export_methodが必要がどうかは・・・

      export_options: {
        provisioningProfiles: { 
          "#{app_identifier}" => "#{provisioning_profile_name}",
        }
      },
      
      export_xcargs: '-allowProvisioningUpdates',
      silent: true,
      destination: 'generic/platform=iOS'
    )

With allowProvisioningUpdates in place, I'm not sure I need those export_options. Doing a lot of trial and error here... building takes a fair share of time.

**Comment by thasegaw** [comment]
Hi @zapjonny,

> Basically the profiles always selected the profs selected for DEBUG configs

Which Configuration do you set in default? (Is it Debug?)

<img width="713" alt="xcodeproj" src="https://user-images.githubusercontent.com/8136032/30598418-99ce603a-9d94-11e7-9792-1530ecfe4ba7.png">

If you do not specify Configuration at `gym`, this value will be used.
Therefore I think you should specify correct Configuration like this
```
gym(
  scheme: 'adhoc'
  configuration: 'adhoc'
  .
  .
 )
```

**Comment by zapjonny** [comment]
@thasegaw Ok thanks I will try to specify configuration like that! I kind of assumed that the configuration that is defined in scheme already did that.

**Comment by zapjonny** [comment]
@thasegaw For now it seems that only adding `configuration: 'Adhoc'` to the gym call in the fastfile fixes things for me. I stopped using `export_options`, `export_xcargs`, etc, it works so far.

Thank you very much. I think I will close this for now... until I run into some similar problem later.
