### ISSUE TITLE
Could not find app with app identifier '[Bundle Id]' in your iTunes Connect account ([Team Email Address] - Team: [Team Number])

### ISSUE THREAD

**Issue by skladek** [fastlane/fastlane#10374]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to use appstore to push a build, but I get the error (brackets obscuring personal info): "Could not find app with app identifier '[Bundle Id]' in your iTunes Connect account ([Email Address] - Team: [Team Number])". The email address is associated with multiple teams. The team_id listed on developer.apple.com under the Membership tab is different from the team number in the error and is in a different format (letters and numbers from developer.apple.com, all numbers in the error). How do I get the correct team id to send through the team_id parameter on appstore? On other accounts I am prompted to select a team when it can't find one, on this account, I don't get prompted, instead, the process returns through the error block.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.55.0"

default_platform :ios

platform :ios do
  bundle_id = '[bundle id]'
  itunes_connect_username = '[email address]'
  team_id = '[team id from developer.apple.com]'
  xcode_project_name = '[project name]'
  xcode_scheme = '[scheme name]'
  xcode_workspace_name = '[workspace name]'

  before_all do
    ensure_git_status_clean
  end

  desc "Builds and pushes an .ipa to iTunes Connect. This should be used for TestFlight and App Store releases."
  lane :appstore do |values|
    match(
      app_identifier: bundle_id,
      team_id: team_id,
      type: 'appstore',
      username: itunes_connect_username
    )

    incrementBuildNumber

    gym(
      export_method: 'app-store',
      scheme: xcode_scheme,
      workspace: xcode_workspace_name
    )

    appstore(
      app_identifier: bundle_id,
      skip_screenshots: true,
      team_id: developer_team_id,
      username: itunes_connect_username
    )
  end

  desc "Increments the build number and commits and tags with the build number."
  private_lane :incrementBuildNumber do
    increment_build_number
    build_number = get_build_number(xcodeproj: xcode_project_name)

    commit_version_bump(
      message: "Build #{build_number}",
      xcodeproj: xcode_project_name
    )

    add_git_tag(
      tag: "builds/#{build_number}"
    )

    push_to_git_remote
  end

  desc "Bumps and commits the major version number, for example, 1.0.0 to 2.0.0"
  lane :versionBumpMajor do
    increment_version_number(
      bump_type: "major"
    )

    version_number = get_version_number(xcodeproj: xcode_project_name)

    commit_version_bump(
      message: "Version bump to #{version_number}",
      xcodeproj: xcode_project_name
    )
  end

  desc "Bumps and commits the minor version number, for example, 1.0.0 to 1.1.0"
  lane :versionBumpMinor do
    increment_version_number(
      bump_type: "minor"
    )

    version_number = get_version_number(xcodeproj: xcode_project_name)

    commit_version_bump(
      message: "Version bump to #{version_number}",
      xcodeproj: xcode_project_name
    )
  end

  desc "Bumps and commits the patch version number, for example, 1.0.0 to 1.0.1"
  lane :versionBumpPatch do
    increment_version_number(
      bump_type: "patch"
    )

    version_number = get_version_number(xcodeproj: xcode_project_name)

    commit_version_bump(
      message: "Version bump to #{version_number}",
      xcodeproj: xcode_project_name
    )
  end

  after_all do |lane|
    notification(
      message: "✅ Lane #{lane} finished successfully."
    )
  end


  error do |lane, exception|
    notification(
      message: "❗Lane #{lane} finished with errors. #{exception}"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.cpr.mobile"
itc_team_id "117992606"
apple_id "cprapps@cprmail.org"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.57.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.0.2        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-09-19**
</details>

**Comment by juli1quere** [comment]
It looks like there is a mismatch between your fastlane config and your account. Just to be clear: there are two different team ids (with, possibly 2 different logins): 
- The iTunes Connect team: only numbers (something like 1234567890)
- The Apple Developper team: numbers and letters (like X3RJ6CR66A)

For the `appstore` action, you need to specify the iTunes Connect team ID  in `team_id` (with only numbers). 

To find it, you can use spaceship. Launch the playground with `fastlane spaceship -u [YOUR_ITC_APPLE_ID@domain.tld]` and then, type `Spaceship::Tunes.select_team`. It will display the list of the available ITC team ids attached to your Apple ID.

In your case, maybe you made a typo in the `appstore` action call: `team_id: developer_team_id,`. To ensure that everything is OK, you can check the logs. Just before launching `appstore` action, fastlane reminds you the parameters used to do the action.

Otherwise: be careful, you have a lane (`appstore`) with the same name as an action (`appstore` too). You should, probably, rename your lane :)

**Comment by skladek** [comment]
Thanks!

The spaceship command helped me figure out what was going wrong. There was an Appfile in the project that had the wrong team_id. I'm pretty sure this is what was causing appstore to not prompt me to select a team. Good to have that command for when I need to check the list of accounts in the future.

Also, I changed the lane named appstore. I've been ignoring that warning for long enough :)

Marking this as closed.

**Comment by juli1quere** [comment]
Great news !
