### ISSUE TITLE
Support management of all app capabilities with Spaceship

### ISSUE THREAD

**Issue by alaincaltieri** [fastlane/fastlane#10383]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

👋  Hi everybody!

App Capabilities are elegantly managed by Spaceship in the [app_service module](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/app_service.rb)

I just noticed a few of the supported capabilities are missing, maybe just those that have been added recently. I'll be happy to submit a PR to update the module and add the missing ones, using the Developer Center as the source of truth. I already have all the information needed. 

Would that be fine for you? Has it any chance of getting merged?

Thank you!

**Comment by KrauseFx** [comment]
Yeah, that would be awesome, we always appreciate help. Thanks @alaincaltieri, and welcome to the fastlane community 🚀
