### ISSUE TITLE
Make simulator visible when snapshot runs

### ISSUE THREAD

**Issue by vmalyi** [fastlane/fastlane#10381]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm currently facing with an issue when one of my UI tests works well when started directly in Xcode but has some issues when I use it in **snapshot** for generating screenshots.

I would like to visually debug the issue but the simulator is not shown when running snapshot in Xcode 9. 

Could you please add an option to make simulator visible when snapshot is running?

Thanks in advance!

**Comment by KrauseFx** [comment]
Hey @vmalyi, that's a great idea, yeah. We were thinking, you could debug the issue by using Xcode to run the UI Tests, would that work for you?

**Comment by vmalyi** [comment]
@KrauseFx thanks for the reply! 

I already follow this approach. The problem is that the **tests work when launched in Xcode** and **don't work when launched from snapshot**. 

The problem I'm facing is 100% related to the app under test and tests itself. I just wanted to see what exactly happens when snapshot runs, since I can't reproduce it in Xcode.

PS: I went through options of _xcodebuild_ command and didn't find anything related to enabling the simulator windows.

I will appretiate a solution from you if this feasible from your point of view!

**Comment by haydus** [comment]
I have a similar issue and it seems that when running tests even a warning causes a SIGABORT, where running normally just outputs a warning in the console.
Mine was the new UI thread checker introduced in iOS 11 saying "Checker: UI API called on a background thread".
As a workaround i use snapshot in iOS 10.2

**Comment by carlosefonseca** [comment]
@haydus Disable Main Thread Checker on your scheme. ![](https://dsc.cloud/carlosefonseca/Screen-Shot-2017-09-26-11-33-41-copy-NGFF5.png)

**Comment by haydus** [comment]
Thanks!
@carlosefonseca will that setting affect the way snapshot is running?

**Comment by carlosefonseca** [comment]
@haydus I don't know. I'm still trying to get snapshot running again since upgrading to Xcode9… But that check box was a problem running the tests on Xcode itself.

**Comment by carlosefonseca** [comment]
Snapshot was failing me with generic Error 65 and crashes until I figured out it was still crashing because of the Main Thread Checker… I had to disable the checkbox on the scheme that was being used by xcodebuild, which was not the same as the regular one… It's working now!

**Comment by vmalyi** [comment]
@carlosefonseca thanks for the idea about disabling main thread checker.

**Comment by kd8ssq** [comment]
@carlosefonseca is there a way to programmatically disable the main thread checker that you've seen?

**Comment by carlosefonseca** [comment]
@kd8ssq I you really want to only have it disabled on run, I guess you could change value in the scheme plist before running and reseting after running. Or make a new scheme just for that.

**Comment by kd8ssq** [comment]
Any ideas what the option in the plist is?  I don't see anything changing
in the file when I enable/disable the main thread checker

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gigi-mohemian** [comment]
@vmalyi if you want to see what's going on in the simulator when running UI tests via `snapshot`, simply launch the simulator via e.g. Spotlight while `snapshot` is running your tests. If there is a simulator instance running in the background it will launch this instance in the foreground and you can see what's going on.

Hope this helps.

**Comment by vmalyi** [comment]
@gigi-mohemian thanks!

**Comment by kd8ssq** [comment]
Is there any plan to have snapshot not use a background thread in order to correct the "Error 65" error that @carlosefonseca talked about?

**Comment by williamsjj** [comment]
@gigi-mohemian Running snapshot automatically closes the visible Simulator when its run. 

@KrauseFx Being able to see the simulator would be really helpful trying to debug what's going on right now, since passing in UI Tests doesn't mean it will work with snapshot in my experience.

**Comment by gigi-mohemian** [comment]
@williamsjj that might be true, but you can re-open it so to speak by launching it again _while snapshot is running your tests_. Not a good solution, I agree, but it might be a sensible workaround until there is another way.

**Comment by ohayon** [comment]
Hey everyone - in my experience using xcodebuild to execute UI tests in Xcode 9+ while running in multiple simulators I have not been able to make this happen. I would love to see this happen too!
