### ISSUE TITLE
Build failed when using jenkins, but succeed in terminal

### ISSUE THREAD

**Issue by Daemonson** [fastlane/fastlane#10390]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [Y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [Y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
>I use fastlane to build my iOS project. It works well when executing `fastlane debug` in terminal >but failed when executing the same shell in jenkins. Please help me! Thanks a lot!

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment
<details><summary>✅ fastlane environment ✅</summary>

> ### Stack

> | Key                         | Value                                       |
> | --------------------------- | ------------------------------------------- |
> | OS                          | 10.12.6                                     |
> | Ruby                        | 2.2.4                                       |
> | Bundler?                    | false                                       |
> | Git                         | git version 2.13.5 (Apple Git-94)           |
> | Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
> | Host                        | Mac OS X 10.12.6 (16G29)                    |
> | Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
> | OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
> | Is contained                | false                                       |
> | Is homebrew                 | false                                       |
> | Is installed via Fabric.app | false                                       |
> | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
> | Xcode Version               | 9.0                                         |

> ### System Locale

> | Variable | Value       |   |
> | -------- | ----------- | - |
> | LANG     | zh_CN.UTF-8 | ✅ |
> | LC_ALL   |             |   |
> | LANGUAGE |             |   |

> ### fastlane gems

> | Gem      | Version | Update-Status |
> | -------- | ------- | ------------- |
> | fastlane | 2.58.0  | ✅ Up-To-Date  |

> ### Loaded fastlane plugins:

> | Plugin                | Version | Update-Status |
> | --------------------- | ------- | ------------- |
> | fastlane-plugin-pgyer | 0.2.1   | ✅ Up-To-Date  |

> <details><summary><b>Loaded gems</b></summary>

> | Gem                       | Version      |
> | ------------------------- | ------------ |
> | slack-notifier            | 1.5.1        |
> | rouge                     | 2.0.7        |
> | xcpretty                  | 0.2.8        |
> | terminal-notifier         | 1.8.0        |
> | unicode-display_width     | 1.3.0        |
> | terminal-table            | 1.8.0        |
> | plist                     | 3.1.0        |
> | CFPropertyList            | 2.3.5        |
> | public_suffix             | 2.0.5        |
> | addressable               | 2.5.2        |
> | multipart-post            | 2.0.0        |
> | word_wrap                 | 1.0.0        |
> | tty-screen                | 0.5.0        |
> | babosa                    | 1.0.2        |
> | colored                   | 1.2          |
> | highline                  | 1.7.8        |
> | commander-fastlane        | 4.4.5        |
> | excon                     | 0.59.0       |
> | faraday                   | 0.13.1       |
> | unf_ext                   | 0.0.7.4      |
> | unf                       | 0.1.4        |
> | domain_name               | 0.5.20170404 |
> | http-cookie               | 1.0.3        |
> | faraday-cookie_jar        | 0.0.6        |
> | fastimage                 | 2.1.0        |
> | gh_inspector              | 1.0.3        |
> | mini_magick               | 4.5.1        |
> | multi_json                | 1.12.2       |
> | multi_xml                 | 0.6.0        |
> | rubyzip                   | 1.2.1        |
> | security                  | 0.1.3        |
> | xcpretty-travis-formatter | 0.0.4        |
> | dotenv                    | 2.2.1        |
> | bundler                   | 1.15.4       |
> | faraday_middleware        | 0.12.2       |
> | uber                      | 0.1.0        |
> | declarative               | 0.0.10       |
> | declarative-option        | 0.1.0        |
> | representable             | 3.0.4        |
> | retriable                 | 3.1.1        |
> | mime-types-data           | 3.2016.0521  |
> | mime-types                | 3.1          |
> | little-plugger            | 1.1.4        |
> | logging                   | 2.2.2        |
> | jwt                       | 1.5.6        |
> | memoist                   | 0.16.0       |
> | os                        | 0.9.6        |
> | signet                    | 0.7.3        |
> | googleauth                | 0.5.3        |
> | httpclient                | 2.8.3        |
> | google-api-client         | 0.13.6       |
> | json                      | 2.1.0        |
> | claide                    | 1.0.2        |
> | colored2                  | 3.1.2        |
> | nanaimo                   | 0.2.3        |
> | xcodeproj                 | 1.5.1        |
> | fastlane-plugin-pgyer     | 0.2.1        |
> </details>

> *generated on:* **2017-09-21**
> </details>

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ My OUTPUT ✅</summary>

> [20:23:47]: [31mYour `export_method` in gym is defined as `development`[0m
> [20:23:47]: [31mwhich might cause problems when signing your application[0m
> [20:23:47]: [31mAre you sure want to build and export for development?[0m
> [20:23:47]: [31mPlease make sure to define the correct export methods when calling[0m
> [20:23:47]: [31mgym in your Fastfile or from the command line[0m
> [20:23:47]: 
> [20:23:47]: 
> [20:23:47]: [31mLooks like fastlane ran into a build/archive error with your project[0m
> [20:23:47]: [31mIt's hard to tell what's causing the error, so we wrote some guides on how[0m
> [20:23:47]: [31mto troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/[0m
> [20:23:47]: [31mBefore submitting an issue on GitHub, please follow the guide above and make[0m
> [20:23:47]: [31msure your project is set up correctly.[0m
> [20:23:47]: [31mfastlane uses `xcodebuild` commands to generate your binary, you can see the[0m
> [20:23:47]: [31mthe full commands printed out in yellow in the above log.[0m
> [20:23:47]: [31mMake sure to inspect the output above, as usually you'll find more error information there[0m
> [20:23:47]: 
> +------------------+-----------+
> |         [33mLane Context[0m         |
> +------------------+-----------+
> | DEFAULT_PLATFORM | ios       |
> | PLATFORM_NAME    | ios       |
> | LANE_NAME        | ios debug |
> +------------------+-----------+
> [20:23:47]: [31mError building the application - see the log above[0m

> +------+-------------------------------------+-------------+
> |                     [32mfastlane summary[0m                     |
> +------+-------------------------------------+-------------+
> | Step | Action                              | Time (in s) |
> +------+-------------------------------------+-------------+
> | 1    | Verifying required fastlane version | 0           |
> | 2    | default_platform                    | 0           |
> | 3    | cocoapods                           | 4           |
> | 💥   | [31mgym[0m                                 | 13          |
> +------+-------------------------------------+-------------+

> [20:23:47]: [31mfastlane finished with errors[0m
> [31m
> [!] Error building the application - see the log above[0m
> Build step 'Execute shell' marked build as failure
> Finished: FAILURE

**Comment by Daemonson** [comment]
@fastlane-bot Yes, I have seen the guide. I don't use match and I have defined a mapping of app target to provisioning profile in my Fastfile as the guide described.

**Comment by nicolasbraun** [comment]
Please insert the full output / your fastfile

**Comment by Daemonson** [comment]
@nicolasbraun 

My fastfile
<details><summary>🚫Fastfile🚫</summary>
`# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.58.0”

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :debug do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "xxx",
        workspace: "xxx.xcworkspace",
        export_method: "development",
        include_bitcode: true,
        export_options: {
          provisioningProfiles: { 
            "com.xxx.xxx" => "xxxDevelopment",
            "com.xxx.carpassenger.xxx" => "xxxDevelopment",
            "com.xxx.xxx.xxx" => "xxxDevelopment"
        }
      },
      output_directory: "./build", 
      output_name: "xxx", 
    ) # Build your app - more options available
    pgyer(api_key: "xxxxxxxxxxxxxxxxxx", 
          user_key: "xxxxxxxxxxxxxxxxxx"
    )
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "xxx") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
`

**Comment by nicolasbraun** [comment]
Sorry got caught up in some stuff.
Hard to help with those incomplete logs and format, check the Markdown guide!

Seems you are calling match for appstore in the debug lane but export_method for gym is set todevelopment. Try passing the export_method option to gym with correct value (call `fastlane action gym`for more info. (Usually gym infers it from match but ... who knows).

Otherwise is your local setup and jenkins the same? especially Xcode version

**Comment by Daemonson** [comment]
@nicolasbraun  Thanks a lot. I resolved my problem by checking my Jenkins configuration as your suggestions.
