### ISSUE TITLE
fastlane init 

### ISSUE THREAD

**Issue by anthonyjoeseph** [fastlane/fastlane#10394]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane init can't detect my bundle id. I have one, as you can see here:

![screen shot 2017-09-21 at 6 22 49 pm](https://user-images.githubusercontent.com/3209763/30721507-6282f778-9efa-11e7-91c7-66b0982070a1.png)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.7.0                           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.58.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
</details>

*generated on:* **2017-09-21**
</details>

**Comment by KrauseFx** [comment]
Can you share the output when running `fastlane init` please?

**Comment by anthonyjoeseph** [comment]
$ fastlane init
[08:49:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:49:16]: Detected iOS/Mac project in current directory...
[08:49:16]: This setup will help you get up and running in no time.
[08:49:16]: fastlane will check what tools you're already using and set up
[08:49:16]: the tool automatically for you. Have fun! 
[08:49:16]: $ xcodebuild -showBuildSettings -project ./Broccoli.xcodeproj

[!] Could not detect bundle identifier of your react-native app. Make sure to open the Xcode project and update the bundle identifier in the `General` section of your project settings. Restart `fastlane init` once you're done!

**Comment by anthonyjoeseph** [comment]
According to [this article](https://medium.com/react-native-training/fastlane-for-react-native-ios-android-app-devops-8ca85bee614e), I should have created my react native app with a custom package name: 

> ...create a new React Native app from the command line but make sure you pass in a package name as a param otherwise you’ll hit some pain down the line renaming your package.

`
react-native init AwesomeProject -package=net.applification.awesomeproject
cd AwesomeProject
`

I assume this vaguely refers to the issue I'm having now. However, it's inconvenient for me to change my bundle id, let alone re-initialize my entire project. Is it possible to use my current bundle id?

**Comment by mynameiswillporter** [comment]
I am also currently experiencing an identical issue.

**Comment by puradox** [comment]
I'm also trying to work through the same issue.

**Comment by viperfx** [comment]
Is there any update to this? Just found this issue as I am trying to setup fastlane for the first time.

**Comment by mynameiswillporter** [comment]
@puradox @viperfx By opening the project in XCode and setting a new Bundle Identifier in the General project settings I was able to move past this error.  I still don't have fastlane setup, but I am no longer triggering this error.

**Comment by viperfx** [comment]
The thing is, there is a bundle identifier set. I even removed it and
changed it. All in xcode. However running fastline init still gives that
error.

**Comment by viperfx** [comment]
Just wanted to leave a comment and say I resolved the issue. For me, the issue was that I noticed the fastlane command was using the workspace file rather than xcode project file. So I delete the workspace file and the fastlane init command worked for me.

**Comment by jrryhrtn** [comment]
This seems to be an issue with Xcode 9.  I am have this exact problem, and I am absolutely sure that my bundle id is set under the general tab in Xcode.  I believe in Xcode 9 that  xcodebuild -showBuildSettings -project ./AwesomeProject.xcodeproj does not list the BUNDLE_ID, but if you grep the ./AwesomeProject.xcodeproj it is there:  grep -R BUNDLE *

AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOS";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOS";
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOSTests";
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOSTests";

**Comment by alexdriedger** [comment]
I had the same issue. This solved my problem (and I don't know why).

1. Delete the Bundle Identifier
2. `fastlane init` (it will fail)
3. Add the Bundle Identifier back exactly as it was before deleting it
4. `fastlane init` (it worked this time magically)
