### ISSUE TITLE
Build takes huge time to finish

### ISSUE THREAD

**Issue by aputhotta** [fastlane/fastlane#10391]
[fastlane_output.docx](https://github.com/fastlane/fastlane/files/1321600/fastlane_output.docx)
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi Team,
We have nearly 60 apps getting build overnight, previously its was taking 3 mins to build a single  ipa file but now it takes more than 7 mins to build an ipa file.

Difference between the previous and new build:
Previous Build: Used Xcode 8.3.3
Current Build: Using Xcode 9, and extra line in Fastfile is that I am passing the argument -allowProvisioningUpdates in GYM, it was specified in Xcode 9 Release Notes.

Please help me to figure out if there is a way to reduce the build time. As I build all 60 apps every day and now it is taking double the time it usual takes. Let me know if there are any questions.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output

` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment
Doc Attached
Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by platedbay** [comment]
Going to 👍  this. We've actually been seeing time outs out on CI when archiving. Happens locally too so it's not just the CI service.

**Comment by PetrosIchor** [comment]
I've been scoping out our iOS team's migration to xcode9 the last 2 weeks as well, build time has almost doubled.  It appears to hang the most during the export to IPA.  These are swift projects.  I recall similar issues with xcode8 awhile back, I'm inclined to point the finger at Apple on this one.  At least until I can run some different projects we have through the xcode9 pipeline. 

I realize it's not a solution, just wanted to say your not the only one with a raised eyebrow.

**Comment by platedbay** [comment]
Ya know, I'm not seeing this delay when exporting the same exact build for `app-store`, only when building it for `ad-hoc`. Perhaps something changed there?

**Comment by ChristianTellefsen** [comment]
I am currently getting an 11 minute wait at this step.

[12:02:00]: ▸ [35m-----------------------------------------[0m
[12:02:00]: [36m$ /usr/bin/xcrun /Users/administrator/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.58.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/7f/f_l11s5n4v96v0r6151ftjxc0000gn/T/gym_config20170925-70332-2o94n4.plist' -archivePath /Users/administrator/Library/Developer/Xcode/Archives/2017-09-25/meganumbers\ 2017-09-25\ 11.55.07.xcarchive -exportPath '/var/folders/7f/f_l11s5n4v96v0r6151ftjxc0000gn/T/gym_output20170925-70332-1n0qztj' -allowProvisioningUpdates [0m
[12:13:01]: Compressing 3 dSYM(s)

**Comment by mlequeux** [comment]
Same here, looks like only one core is working when exporting to IPA

**Comment by fabricedeplancke** [comment]
It happens for me too on our CI environment, when exporting for `enterprise`. I also noticed more dSYMs being compressed (I had 15 before the upgrade to Xcode 9 and fastlane 2.59.0, and now I have 93).

```
INFO [2017-09-26 20:39:26.53]: ? + xcodebuild -exportArchive -exportOptionsPlist /var/folders/jc/70y7nvgs2ml9yvlh6v5l2hv80000gn/T/gym_config20170926-22459-o6qmc0.plist -archivePath ./archive.xcarchive -exportPath /var/folders/jc/70y7nvgs2ml9yvlh6v5l2hv80000gn/T/gym_output20170926-22459-19jyo55
INFO [2017-09-26 20:39:28.50]: ? 2017-09-26 20:39:28.503 xcodebuild[25044:296864] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jc/70y7nvgs2ml9yvlh6v5l2hv80000gn/T/TV5Monde Afrique_2017-09-26_20-39-28.502.xcdistributionlogs'.
INFO [2017-09-26 20:46:45.58]: ? Exported archive.xcarchive to: /var/folders/jc/70y7nvgs2ml9yvlh6v5l2hv80000gn/T/gym_output20170926-22459-19jyo55
INFO [2017-09-26 20:46:45.58]: ? ** EXPORT SUCCEEDED **
INFO [2017-09-26 20:46:45.72]: Compressing 93 dSYM(s)
```

**Comment by romk1n** [comment]
same here

**Comment by dbrajkovic** [comment]
+1

**Comment by ryanbaldwin** [comment]
Just to echo - I'm also exporting via Archive. That export alone is taking 8 minutes. The only change is Xcode 8.3.3 to Xcode 9. Our "build and sign" step went from ~2.5 minutes, to an average time of nearly 9 minutes. It's sad because I recently got our checkout & setup step (which uses carthage) down from 2.5 minutes to literally 15 seconds. I was pumped for super fast turnout builds. Then Xcode 9 came and spoiled all the fun with a brutally slow archive. Sad face.

**Comment by Allui** [comment]
see my comment here
#10482

**Comment by tylerjames** [comment]
I'm getting this as well. I have a dedicated machine doing these builds (Mac Mini with Core i5 and 8GB or RAM) and nothing else and at the `-exportArchvive` step the RAM usage for `xcodebuild` shoots up to >10 GB of usage on a machine with only 8 GB

**Comment by ryanbaldwin** [comment]
@allui - thanks for the tip. I’ll give that a whirl tomorrow and see if it improves. Thanks again.

**Comment by sosng** [comment]
Same to me, I use Travis to run fastlane,  It stucks at this step, since there is no output in 10 minutes.

**Comment by JackieQi** [comment]
Same thing here. Xcode 9 with latest fastlane when exporting for adhoc.

**Comment by younke** [comment]
Investigate the plist file that was generated by gym. If `include_symbols` `include_bitcode` options are not listed  even if you passed it,  try including them as export_options. In my case:
```ruby
gym(clean: true,
         scheme: "Scheme",
         output_directory: options[:out_dir] || "./build",
         output_name: options[:out_name] || options[:scheme],
         configuration: options[:configuration] || "Debug",
         export_method: options[:export_method] || "development",
         export_options: {
              uploadBitcode: false,
              uploadSymbols: false,
              compileBitcode: false,
         })
```
If you don't need symbols to be generated that should save you some time

**Comment by ryanbaldwin** [comment]
I've tried both suggestions now and neither worked. I'm still getting build times in the realm of 8-12 minutes. I tried @younke's suggestion and disabled all the `export_options` but it didn't help. Sad panda.

**Comment by ohayon** [comment]
Hey everyone, I'm curious, has anyone tried running `xcodebuild` outside of the context of _fastlane_? I have a suspicion that this because of changes to the `xcodebuild` tools. 🚀

**Comment by platedbay** [comment]
@younke did something similar for us and it's back to a normal export time! We do need to upload symbols but I didn't notice a difference with it true/false. For us it was definitely bitcode that caused the export time to balloon.

```
include_bitcode: false,
export_options: {
    uploadBitcode: false,
    uploadSymbols: true,
    compileBitcode: false
}
```

**Comment by ohayon** [comment]
👍 yeah it is definitely good to know about for people using `gym` just wanted to make sure that it wasn't anything we were doing on our end 😄 ! I am going to close this for now, but feel free to keep conversation going!! Let us know if there is anything we can do to help! 🚀 🐙
