### ISSUE TITLE
Git Last Tag on a shallow clone

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#1039]
I have a question about working with the `git_last_tag` command on a shallow clone.  

I'm using bamboo as my CI server and fastlane.  Bamboo (by default) does a shallow clone which doesn't seem to be pulling tags correctly.  

I follow that up with a `git fetch --tags` which then pulls in the tags.

I've noticed in `git_helper.rb` it looks like the last_tag command is doing `git describe --tags --abbrev=0`

    def self.last_git_tag_name(match_lightweight = true)
      command = ['git describe']
      command << '--tags' if match_lightweight
      command << '--abbrev=0'
      Actions.sh(command.join(' '), log: false).chomp
     rescue
      nil
     end

This doesn't *seem* to be working correctly whereas the command:

    git describe --tags `git rev-list --tags --max-count=1`

does pull the last tag correctly.  Should the code be updated to mirror this behavior?  I guess i'm a little clear what "last_tag" means.

**Comment by mfurtak** [comment]
Hi @jeeftor - thanks for writing this up! :+1: I've reproduced what you've described locally, and will be taking a look at #1040 as a solution. :bug:

**Comment by mfurtak** [comment]
Closing this for now - please reopen if needed! :unlock:
