### ISSUE TITLE
App fails to submit after running deliver

### ISSUE THREAD

**Issue by hksna** [fastlane/fastlane#10393]
### Issue Description

We're trying to submit our app for review through fastlane deliver command through shell. However, submit returns success but in reality, app will be still enabled with "Submit for Review". We need to do it manually by selecting export compliance and add id info uses idfa options.

We're running following command for this:

fastlane deliver --skip_binary_upload --submit_for_review -x false -f true  -b "export_compliance_compliance_required: false" -b "add_id_info_uses_idfa:false"-u <user_id>

##### Complete output when running fastlane, including the stack trace and command used
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[13:25:57]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:25:59]: Login to iTunes Connect (<user_id>)
[13:26:05]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.56.0 Summary                            |
+--------------------------------------+--------------------------------------+
| skip_binary_upload                   | true                                 |
| submit_for_review                    | true                                 |
| run_precheck_before_submit           | false                                |
| force                                | true                                 |
| submission_information               | add_id_info_uses_idfa:false          |
| username                             | <user_id>                       |
| app_identifier                       | com.<pkg_name> |
| screenshots_path                     | ./screenshots                        |
| metadata_path                        | ./metadata                           |
| app_version                          | 1.10                                 |
| edit_live                            | false                                |
| ipa                                  | FastlaneTest.ipa                     |
| platform                             | ios                                  |
| skip_screenshots                     | false                                |
| skip_metadata                        | false                                |
| skip_app_version_update              | false                                |
| automatic_release                    | false                                |
| overwrite_screenshots                | false                                |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validation | false                                |
+--------------------------------------+--------------------------------------+

[13:26:06]: Making sure the latest version on iTunes Connect matches '1.10' from the ipa file...
[13:26:08]: '1.10' is the latest version on iTunes Connect
[13:26:14]: Uploading metadata to iTunes Connect
When you create a new app name or update an existing one, it must now be 30 characters or fewer. Also, you can only update an app’s description when submitting a new version of that app. <a href="https://developer.apple.com/app-store/product-page/" target="_blank">Learn more</a>
[13:26:16]: Successfully uploaded set of metadata to iTunes Connect
[13:26:17]: Starting with the upload of screenshots...
[13:26:17]: Successfully uploaded screenshots to iTunes Connect
[13:26:20]: Selecting the latest build...
[13:26:22]: Selecting build 1.10 (1.18)...
[13:26:24]: Successfully selected build
[13:26:24]: Submitting the app for review...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

#######################################################################
# fastlane 2.58.0 is available. You are on 2.56.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.58.0 Bugfixes and improvements
* Add "fastlane update_fastlane" command to tab autocompletion (#10375) via Omer Faruk Yilmaz
* Print out the languages that are being updated for set_changelog action (#10369) via Felix Krause
* Add in-app purchase scanning support in precheck (#10372) via Joshua Liebowitz
* Revert commits that caused bugs with the package name for transporter (#10376) via Felix Krause

2.57.2 snapshot improvements
* Add missing "Apple TV" device in snapshot report generator devices (see #10365) (#10366) via Julien Quéré
* Allow snapshot to handle multiple tvOS devices (closes #10347) (#10350) via Julien Quéré

2.57.1 Fix regression in match
* Revert "Fix creation of certificate when a keychain is specified. (#10321)" via Felix Krause (this fixes the regression of the last release
* Use underscore instead of parentheses when copying IPA file (#10357) via Dennis Torbichuk
* Fix error in GitHub issue list (#10352) via Rishabh Tayal

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/deliver/lib/deliver/submit_for_review.rb:18:in `submit!': [!] undefined method `each' for "add_id_info_uses_idfa:false":String (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/deliver/lib/deliver/runner.rb:153:in `submit_for_review'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/deliver/lib/deliver/runner.rb:37:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/deliver/lib/deliver/commands_generator.rb:176:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.56.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

### Environment
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[13:28:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:28:43]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.56.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
</details>

*generated on:* **2017-09-21**
</details>

Looking for related GitHub issues on fastlane/fastlane...

➡️  Pilot reported "invalid byte sequence in US-ASCII" after token expiration
    https://github.com/fastlane/fastlane/issues/9689 [closed] 6 💬
    03 Aug 2017

➡️  invalid byte sequence in UTF-8 when using update_info_plist
    https://github.com/fastlane/fastlane/issues/6998 [closed] 11 💬
    2 days ago

➡️  Invalid byte sequence with invalid strings file
    https://github.com/fastlane/fastlane/issues/7661 [closed] 8 💬
    01 Jun 2017

and 24 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.58.0 is available. You are on 2.56.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

2.58.0 Bugfixes and improvements
* Add "fastlane update_fastlane" command to tab autocompletion (#10375) via Omer Faruk Yilmaz
* Print out the languages that are being updated for set_changelog action (#10369) via Felix Krause
* Add in-app purchase scanning support in precheck (#10372) via Joshua Liebowitz
* Revert commits that caused bugs with the package name for transporter (#10376) via Felix Krause

2.57.2 snapshot improvements
* Add missing "Apple TV" device in snapshot report generator devices (see #10365) (#10366) via Julien Quéré
* Allow snapshot to handle multiple tvOS devices (closes #10347) (#10350) via Julien Quéré

2.57.1 Fix regression in match
* Revert "Fix creation of certificate when a keychain is specified. (#10321)" via Felix Krause (this fixes the regression of the last release
* Use underscore instead of parentheses when copying IPA file (#10357) via Dennis Torbichuk
* Fix error in GitHub issue list (#10352) via Rishabh Tayal

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`

**Comment by hksna** [comment]
Any help would be highly appreciated!

**Comment by KrauseFx** [comment]
Sorry, I don't understand the problem, could you describe it a bit more?

**Comment by pomozoff** [comment]
Here is the problem:

```
~ head -1 /usr/local/bin/fastlane
#!/System/Library/Frameworks/Ruby.framework/2.0/Current/usr/bin/ruby
```

There is no that directory in the FS:
```
~ ls -la /System/Library/Frameworks/Ruby.framework
total 0
drwxr-xr-x    5 root  wheel   160 Sep 26 12:15 .
drwxr-xr-x  143 root  wheel  4576 Sep 26 12:15 ..
lrwxr-xr-x    1 root  wheel    26 Sep 26 12:14 Resources -> Versions/Current/Resources
lrwxr-xr-x    1 root  wheel    21 Sep 26 12:14 Ruby -> Versions/Current/Ruby
drwxr-xr-x    4 root  wheel   128 Sep 26 12:15 Versions
~ 
```
