### ISSUE TITLE
fastlane scan unable to do xctestrun

### ISSUE THREAD

**Issue by liaogz82** [fastlane/fastlane#10403]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
+ bundle exec fastlane test
+-------------------------------+---------+-------------------------+
|                           [32mUsed plugins[0m                            |
+-------------------------------+---------+-------------------------+
| Plugin                        | Version | Action                  |
+-------------------------------+---------+-------------------------+
| fastlane-plugin-sentry        | 1.4.0   | sentry_create_release   |
|                               |         | sentry_finalize_release |
|                               |         | sentry_upload_dsym      |
|                               |         | sentry_upload_file      |
|                               |         | sentry_upload_sourcemap |
| fastlane-plugin-mobile_center | 0.1.4   | mobile_center_upload    |
+-------------------------------+---------+-------------------------+

[20:24:02]: -------------------------------------------------
[20:24:02]: --- Step: Verifying required fastlane version ---
[20:24:02]: -------------------------------------------------
[20:24:02]: Your fastlane version 2.47.0 matches the minimum requirement of 2.47.0  ✅
[20:24:02]: ------------------------------
[20:24:02]: --- Step: default_platform ---
[20:24:02]: ------------------------------
[20:24:02]: Driving the lane 'ios test' 🚀
[20:24:02]: --------------------------------
[20:24:02]: --- Step: get_bundle_version ---
[20:24:02]: --------------------------------
fatal: no tag exactly matches 'fda0dddfd756c654082b4964c53e962b217fb19b'
[20:24:02]: ---------------------------------------------
[20:24:02]: --- Step: Switch to ios open_project lane ---
[20:24:02]: ---------------------------------------------
[20:24:02]: Cruising over to lane 'ios open_project' 🚖
[20:24:02]: ------------------------------------------
[20:24:02]: --- Step: open "../jarvis.xcworkspace" ---
[20:24:02]: ------------------------------------------
[20:24:02]: $ open "../jarvis.xcworkspace"
[20:24:02]: Cruising back to lane 'ios test' 🚘
[20:24:03]: -------------------------------------------------------
[20:24:03]: --- Step: Switch to ios run_test_with_coverage lane ---
[20:24:03]: -------------------------------------------------------
[20:24:03]: Cruising over to lane 'ios run_test_with_coverage' 🚖
[20:24:03]: ------------------
[20:24:03]: --- Step: scan ---
[20:24:03]: ------------------
[20:24:03]: Successfully loaded '/Users/jenkins/workspace/jarvis/jarvis-ios/fastlane/Scanfile' 📄

+-----------------------+--------------------+
| Detected Values from './fastlane/Scanfile' |
+-----------------------+--------------------+
| devices               | ["iPhone 7"]       |
| scheme                | jarvis             |
| workspace             | jarvis.xcworkspace |
| code_coverage         | true               |
| output_directory      | ./reports          |
| only_testing          | jarvisTests        |
| slack_only_on_failure | true               |
+-----------------------+--------------------+

[20:24:03]: $ xcodebuild -list -workspace jarvis.xcworkspace
[20:24:03]: $ xcodebuild -showBuildSettings -workspace jarvis.xcworkspace -scheme jarvis
[20:24:05]: Successfully loaded '/Users/jenkins/workspace/jarvis/jarvis-ios/fastlane/Scanfile' 📄
[20:24:05]: No values defined in './fastlane/Scanfile'
[20:24:05]: $ xcodebuild -list -workspace jarvis.xcworkspace
[20:24:06]: $ xcodebuild -showBuildSettings -workspace jarvis.xcworkspace -scheme jarvis

+------------------------+----------------------------------------------------------------------------------------+
|                                             Summary for scan 2.47.0                                             |
+------------------------+----------------------------------------------------------------------------------------+
| xctestrun              | ../DerivedData/Build/Products/jarvis_iphoneos10.3-arm64.xctestrun                      |
| devices                | ["iPhone 7"]                                                                           |
| scheme                 | jarvis                                                                                 |
| workspace              | jarvis.xcworkspace                                                                     |
| code_coverage          | true                                                                                   |
| output_directory       | ./reports                                                                              |
| only_testing           | ["jarvisTests"]                                                                        |
| slack_only_on_failure  | true                                                                                   |
| derived_data_path      | /Users/jenkins/Library/Developer/Xcode/DerivedData/jarvis-bejkaxfemfmswxgvrtdhcfuyeygd |
| clean                  | false                                                                                  |
| skip_build             | false                                                                                  |
| output_types           | html,junit                                                                             |
| buildlog_path          | ~/Library/Logs/scan                                                                    |
| include_simulator_logs | false                                                                                  |
| open_report            | false                                                                                  |
| skip_slack             | false                                                                                  |
| use_clang_report_name  | false                                                                                  |
| fail_build             | true                                                                                   |
| xcode_path             | /Applications/Xcode.app                                                                |
+------------------------+----------------------------------------------------------------------------------------+

[20:24:07]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -destination 'platform=iOS Simulator,id=E2450393-D96F-46B9-93D7-42D34E5E6D57' -derivedDataPath '/Users/jenkins/Library/Developer/Xcode/DerivedData/jarvis-bejkaxfemfmswxgvrtdhcfuyeygd' -enableCodeCoverage YES -xctestrun '../DerivedData/Build/Products/jarvis_iphoneos10.3-arm64.xctestrun
' -only-testing:jarvisTests test-without-building | tee '/Users/jenkins/Library/Logs/scan/jarvis-jarvis.log' | xcpretty --no-color --report html --output '/Users/jenkins/workspace/jarvis/jarvis-ios/reports/report.html' --report junit --output '/Users/jenkins/workspace/jarvis/jarvis-ios/reports/report.junit' --report junit --output '/var/folders/jf/rt1q_d4s56j1x6cvgy63d8380000gs/T/junit_report20170922-65498-99jsqj'
[20:24:07]: ▸ Loading...
[20:24:08]: ▸ xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
[20:24:08]: ▸ Reason: Cannot read test run specification.
xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
Reason: Cannot read test run specification.
[20:24:08]: Exit status: 70

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.47.0"
default_platform :ios

# Project name jarvis-ios
project = "jarvis-ios"

# Source folder is jarvis
source = "jarvis"

# Project and scheme setup. TODO: reduce to only one target / scheme
app_schemes = {
  "alpha" => "jarvis", # QA Scheme
  "beta" => "jarvis",
  "enterprise" => "JarvisAppstore" # Production scheme
}

app_identifiers = {
  "alpha" => "d217a8c2ac6640539807600586b66365",
  "beta"  => "2659945bae85454f9b4ecd9b2085bfc1",
  "enterprise" => ""
}

xcodeproj = source + ".xcodeproj"
xcworkspace = source + ".xcworkspace"
build_directory = "Build/Release-Enterprise-iphoneos"
slack_internal_channel = "jarvis-ios-git"
slack_external_channel = "jarvis-external"

platform :ios do

  desc "runs all the tests"
  lane :test do
    open_project
    run_test_with_coverage
  end

  desc "Release a build, alpha, beta or enterprise"
  lane :build do
    puts "Building on #{lane_context[SharedValues::GET_BUILD_ENVIRONMENT]} environment"
    open_project
    ENV['FL_HOCKEY_PUBLIC_IDENTIFIER'] = app_identifiers[lane_context[SharedValues::GET_BUILD_ENVIRONMENT]]
    update_build_version(environment: lane_context[SharedValues::GET_BUILD_ENVIRONMENT])
    update_display_name(environment: lane_context[SharedValues::GET_BUILD_ENVIRONMENT]) #to add if using lane for app store (if options[:environment] != "enterprise")
    create_binary(environment: lane_context[SharedValues::GET_BUILD_ENVIRONMENT])
  end

  desc "Update cocoapods and carthage dependencies"
  lane :update_dependencies do
    if File.file?("../Podfile")
      cocoapods
    end

    if File.file?("../Cartfile")
      carthage(
        command: "bootstrap",   # One of: build, bootstrap, update, archive. (default: bootstrap)
        use_ssh: false,         # Use SSH for downloading GitHub repositories.
        use_submodules: false,  # Add dependencies as Git submodules.
        use_binaries: false,    # Check out dependency repositories even when prebuilt frameworks exist
        no_build: false,        # When bootstrapping Carthage do not build
        no_skip_current: false, # Don't skip building the current project (only for frameworks)
        verbose: false,         # Print xcodebuild output inline
        platform: "iOS",
        cache_builds: true,
      )
    end
  end

  desc "create appstore build"
  lane :app_store_build do
    gym

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

    pilot(
      app_identifier:"sg.com.singaporepower.spsccm",
      distribute_external: false,
      ipa:"Build/Release-Appstore-iphoneos/JarvisAppstore.ipa",
      skip_waiting_for_build_processing:true,
      skip_submission:true
    )
  end

  desc "reset simulator"
  lane :reset_sim do
    sh "actions/reset_sim.sh"
  end

  desc "Quit Xcode, Simulator and any other related programmes"
  lane :quit_all do
    # ensures that there are only one process remain running
    number_of_fastlane_processes = `ps | grep fastlane | wc -l`.strip
    if number_of_fastlane_processes.to_i <= 3
      sh "osascript -e 'quit app \"Xcode\"'"
      sh "osascript -e 'quit app \"Simulator\"'"
    end
  end

  desc "Upload .ipa file"
  lane :upload_binary do |options|
    message = "New *#{project}* #{lane_context[SharedValues::GET_BUILD_ENVIRONMENT]} version *#{lane_context[SharedValues::GET_BUNDLE_SHORT_VERSION_STRING]}* build is uploaded"
    puts message

    if is_ci
      if is_tryouts
        UI.important 'Skipping hockeyapp upload as the build is run in tryouts.'
        next
      end
      if options[:release_candidate].to_b
        ENV['FL_HOCKEY_TAGS'] = "tester" ## or groups = tester
      end
      hockey( ## may want to change to mobile_center_upload
        ipa: "#{build_directory}/#{source}.ipa",
        notes: generate_release_notes
      )
      slack_channel = lane_context[SharedValues::GET_BUILD_ENVIRONMENT] == "alpha" ? "#{slack_internal_channel}" : "#{slack_external_channel}"
      slack(
        channel: "#{slack_channel}",
        message: "#{message}",
        success: true
      )
    end
  end

  #############################################################################
  ## Private lanes
  #############################################################################

  desc "Open Project File"
  private_lane :open_project do
    sh "open \"../#{xcworkspace}\""
  end

  desc "Run test with coverage (scan & slather)"
  private_lane :run_test_with_coverage do |options|
    if ENV['BRANCH_NAME'] == 'master'
      xctestrun = `find .. -name "*.xctestrun"`
      scan(
        xctestrun: xctestrun
      )
    else
      scan
    end
    slather
  end

  desc "Set up Info.plist on ShortVersionString and BundleVersion"
  private_lane :update_build_version do |options|
    versioning_string = "version string - #{lane_context[SharedValues::GET_BUNDLE_SHORT_VERSION_STRING]}, build number - #{lane_context[SharedValues::GET_BUNDLE_VERSION]}"
    puts versioning_string

    plist_path = options[:environment] == "enterprise" ? "#{source}/jarvis.plist" : "#{source}/Info.plist"
    set_info_plist_value(
      path: "#{plist_path}",
      key: "CFBundleShortVersionString",
      value: "#{lane_context[SharedValues::GET_BUNDLE_SHORT_VERSION_STRING]}"
    )
    set_info_plist_value(
      path: "#{plist_path}",
      key: "CFBundleVersion",
      value: "#{lane_context[SharedValues::GET_BUNDLE_VERSION]}"
    )
  end

  desc "Set up Info.plist for Display Name"
  private_lane :update_display_name do |options|
    display_name = options[:environment] == "alpha" ? "Jarvis-Alpha" : "Jarvis Beta"
    set_info_plist_value(
      path: "#{source}/Info.plist",
      key: "CFBundleDisplayName",
      value: display_name
    )
  end

  desc "Build the Enterprise Signed IPA"
  private_lane :create_binary do |options|
    build_env = options[:environment]
    configuration = build_env == "alpha" ? "Alpha" : "Release"
    export_method = build_env == "enterprise" ? "app-store" : "enterprise"
    gym(
      archive_path: build_directory,
      configuration: "#{configuration}",
      derived_data_path: "./DerivedData",
      export_method: export_method,
      export_options: {
        provisioningProfiles: {
          "sg.com.singaporepower.jarvis-qa-release"=>"Jarvis QA Release",
          "sg.com.singaporepower.jarvis-release"=>"Jarvis Release Distribution"
        }
      },
      include_bitcode: false,
      include_symbols: false,
      output_directory: build_directory,
      scheme:  app_schemes[build_env],
      silent: "true",
      workspace: xcworkspace,
      xcargs: "build-for-testing"
    )
  end

  #############################################################################
  ## Callbacks
  #############################################################################

  before_all do
    if !ENV['BRANCH_NAME'].nil? && ENV['BRANCH_NAME'].match(/(master|release-.*|hotfix-.*)/)
      get_bundle_version
    end
  end

  error do |lane, exception|
    if is_ci
      slack(
        channel: "#{slack_internal_channel}",
        message: "Lane `#{lane}` failed to complete in build <" + ENV['BUILD_URL'] + "|" + ENV['BUILD_ID']+">",
        success: false
      )
      if ENV['BRANCH_NAME'].match(/(master|release-.*|hotfix-.*)/)
        clear_derived_data(derived_data_path: "../DerivedData")
      else
        clear_derived_data
      end
    end
    quit_all
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.47.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-sentry        | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-mobile_center | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.1.0        |
| slack-notifier                | 1.5.1        |
| claide                        | 1.0.2        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.2.3        |
| xcodeproj                     | 1.5.1        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.2.8        |
| terminal-notifier             | 1.8.0        |
| unicode-display_width         | 1.3.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.3.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.5.0        |
| babosa                        | 1.0.2        |
| colored                       | 1.2          |
| highline                      | 1.7.8        |
| commander-fastlane            | 4.4.5        |
| unf_ext                       | 0.0.7.4      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20170404 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| fastimage                     | 2.1.0        |
| gh_inspector                  | 1.0.3        |
| uber                          | 0.1.0        |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.1        |
| mime-types-data               | 3.2016.0521  |
| mime-types                    | 3.1          |
| little-plugger                | 1.1.4        |
| logging                       | 2.2.2        |
| jwt                           | 1.5.6        |
| memoist                       | 0.16.0       |
| os                            | 0.9.6        |
| signet                        | 0.7.3        |
| googleauth                    | 0.5.3        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.12.0       |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| rubyzip                       | 1.2.1        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 0.0.4        |
| dotenv                        | 2.2.1        |
| bundler                       | 1.15.4       |
| json                          | 2.0.2        |
| io-console                    | 0.4.6        |
| excon                         | 0.59.0       |
| openssl                       | 2.0.3        |
| faraday                       | 0.13.1       |
| faraday_middleware            | 0.12.2       |
| fastlane-plugin-sentry        | 1.4.0        |
| fastlane-plugin-mobile_center | 0.1.4        |
</details>

*generated on:* **2017-09-23**
</details>

**Comment by huy-le** [comment]
This one is not code signing issue
