### ISSUE TITLE
Submit build to Beta App Review without uploading new IPA

### ISSUE THREAD

**Issue by dlo** [fastlane/fastlane#10408]
### New Issue Checklist

🔑 

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi folks. I'm reading through the documentation for pilot, and am wondering if there's a way to simply submit an existing build that has already been uploaded. AFAIK, `deliver` already takes care of uploading the build. What I want is a way to just take a build that has been uploaded through `deliver` and submit it to Beta App Review. Is there a way to do this? I've combed through the documentation and am just not finding anything.

Thanks!

**Comment by dlo** [comment]
@fastlane-bot Thanks, but this is a feature request / question, not a bug :) 👍

**Comment by KrauseFx** [comment]
Yeah that's a great idea, for now, you could build that using [spaceship](https://spaceship.airforce), but there is no action or plugin available yet to my knowledge. 

Let me know if you're interested in providing this as a plugin, I'm sure lots of people would find it useful 👍

**Comment by dlo** [comment]
On it. 👍

**Comment by dlo** [comment]
Here's a first take. Comments welcome, I'll submit to the directory after I package it up. :) https://gist.github.com/dlo/062bd03f39449fa11342febc41d45842

**Comment by dlo** [comment]
@KrauseFx Uploaded to RubyGems. Hopefully other people find this useful! 🌮 

https://rubygems.org/gems/fastlane-plugin-submit_to_beta_app_review
