### ISSUE TITLE
Fastlane build fails using CircleCI

### ISSUE THREAD

**Issue by jaumevn** [fastlane/fastlane#10400]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Install `fastlane`and execute a lane returns the following error. Fastlane is isntalled in a `circleci` machine.

`[!] Could not find action, lane or variable 'esc'. Check out the documentation for more details: https://docs.fastlane.tools/actions`
### Output
15:12:18]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-09-22 15:12:20.78]: Checking if there are any plugins that should be loaded...
INFO [2017-09-22 15:12:20.79]: -------------------------------------------------
INFO [2017-09-22 15:12:20.79]: --- Step: Verifying required fastlane version ---
INFO [2017-09-22 15:12:20.79]: -------------------------------------------------
INFO [2017-09-22 15:12:20.79]: Your fastlane version 2.58.0 matches the minimum requirement of 2.56.0  ✅
INFO [2017-09-22 15:12:20.79]: ------------------------------
INFO [2017-09-22 15:12:20.79]: --- Step: default_platform ---
INFO [2017-09-22 15:12:20.79]: ------------------------------
DEBUG [2017-09-22 15:12:20.79]: /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:155:in `trigger_action_by_name'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:12:in `block in parsing_binding'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:114:in `platform'
Fastfile:5:in `parsing_binding'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:54:in `eval'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/bin/fastlane:20:in `<top (required)>'
/home/circleci/.rubies/ruby-2.4.1/bin/fastlane:22:in `load'
/home/circleci/.rubies/ruby-2.4.1/bin/fastlane:22:in `<main>'
WARN [2017-09-22 15:12:21.14]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-09-22 15:12:21.29]: Checking if there are any plugins that should be loaded...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | debian_based 9.1                                       |
| Ruby                        | 2.4.1                                                  |
| Bundler?                    | false                                                  |
| Git                         | git version 2.11.0                                     |
| Installation Source         | ~/.rubies/ruby-2.4.1/bin/fastlane                      |
| Host                        | Debian GNU/Linux 9 debian_based 9.1 (4.4.0-92-generic) |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.1/lib                               |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.56.0"

default_platform :android

platform :android do

  desc "Build all app flavors"
  lane :build_all do
    sh "fastlane build --env fotoku"
  end

  esc "Deploy all app flavors to the Google Play"
  lane :deploy_all do
    sh "fastlane deploy --env fotoku"
  end

  desc "Build the app"
  lane :build do
    gradle(task: "assemble",
            build_type: "Release",
            flavor: ENV['GRADLE_FLAVOR'])
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assemble",
            build_type: "Release",
            flavor: ENV['GRADLE_FLAVOR'])
    supply
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file ENV['JSON_KEY']
package_name ENV['PACKAGE_NAME']

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.58.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-09-22**
</details>
INFO [2017-09-22 15:12:21.29]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
/home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Could not find action, lane or variable 'esc'. Check out the documentation for more details: https://docs.fastlane.tools/actions (FastlaneCore::Interface::FastlaneError)
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:169:in `rescue in trigger_action_by_name'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:155:in `trigger_action_by_name'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:12:in `block in parsing_binding'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:114:in `platform'
	from Fastfile:5:in `parsing_binding'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:54:in `eval'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /home/circleci/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.58.0/bin/fastlane:20:in `<top (required)>'
	from /home/circleci/.rubies/ruby-2.4.1/bin/fastlane:22:in `load'
	from /home/circleci/.rubies/ruby-2.4.1/bin/fastlane:22:in `<main>'

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/home/circleci/code/fastlane/Appfile'
-------
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | debian_based 9.1                                       |
| Ruby                        | 2.4.1                                                  |
| Bundler?                    | false                                                  |
| Git                         | git version 2.11.0                                     |
| Installation Source         | ~/.rubies/ruby-2.4.1/bin/fastlane                      |
| Host                        | Debian GNU/Linux 9 debian_based 9.1 (4.4.0-92-generic) |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.1/lib                               |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |


### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.56.0"

default_platform :android

platform :android do

  desc "Build all app flavors"
  lane :build_all do
    sh "fastlane build --env fotoku"
  end

  esc "Deploy all app flavors to the Google Play"
  lane :deploy_all do
    sh "fastlane deploy --env fotoku"
  end

  desc "Build the app"
  lane :build do
    gradle(task: "assemble",
            build_type: "Release",
            flavor: ENV['GRADLE_FLAVOR'])
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assemble",
            build_type: "Release",
            flavor: ENV['GRADLE_FLAVOR'])
    supply
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file ENV['JSON_KEY']
package_name ENV['PACKAGE_NAME']

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.58.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-09-22**
</details>

```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | debian_based 9.1                                       |
| Ruby                        | 2.4.1                                                  |
| Bundler?                    | false                                                  |
| Git                         | git version 2.11.0                                     |
| Installation Source         | ~/.rubies/ruby-2.4.1/bin/fastlane                      |
| Host                        | Debian GNU/Linux 9 debian_based 9.1 (4.4.0-92-generic) |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.1/lib                               |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |


### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.56.0"

default_platform :android

platform :android do

  desc "Build all app flavors"
  lane :build_all do
    sh "fastlane build --env fotoku"
  end

  esc "Deploy all app flavors to the Google Play"
  lane :deploy_all do
    sh "fastlane deploy --env fotoku"
  end

  desc "Build the app"
  lane :build do
    gradle(task: "assemble",
            build_type: "Release",
            flavor: ENV['GRADLE_FLAVOR'])
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assemble",
            build_type: "Release",
            flavor: ENV['GRADLE_FLAVOR'])
    supply
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file ENV['JSON_KEY']
package_name ENV['PACKAGE_NAME']

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.58.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-09-22**
</details>

**Comment by taquitos** [comment]
Looks like you have a typo in your lanefile, that should be `desc`:
<img width="431" alt="screen shot 2017-09-22 at 10 35 22 am" src="https://user-images.githubusercontent.com/1304821/30756994-ce6b4b34-9f81-11e7-9e14-d8a9b9fbd88f.png">

**Comment by jaumevn** [comment]
You’re right... thanks.
