### ISSUE TITLE
`export_method` in gym is defined as `development` cause problems when signing application

### ISSUE THREAD

**Issue by yangmiemie1116** [fastlane/fastlane#10404]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)

### Issue Description

[15:57:52]: Your `export_method` in gym is defined as `development`
[15:57:52]: which might cause problems when signing your application
[15:57:52]: Are you sure want to build and export for development?
[15:57:52]: Please make sure to define the correct export methods when calling
[15:57:52]: gym in your Fastfile or from the command line
[15:57:52]:
[15:57:52]:
[15:57:52]: Looks like fastlane ran into a build/archive error with your project
[15:57:52]: It's hard to tell what's causing the error, so we wrote some guides on how
[15:57:52]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[15:57:52]: Before submitting an issue on GitHub, please follow the guide above and make
[15:57:52]: sure your project is set up correctly.
[15:57:52]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[15:57:52]: the full commands printed out in yellow in the above log.
[15:57:52]: Make sure to inspect the output above, as usually you'll find more error information there

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.58.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build_no = get_version_number + '.' + Time.new.strftime("%m%d%H%M")
    increment_build_number(build_number: build_no)
    match(type: "development")
    gym(scheme: "Mic",
        workspace: "Mic.xcworkspace",
        configuration: "Debug",
        export_method:"development",
        clean:true,
        output_directory: "./build/",
        output_name: "sdjj"+build_no) # Build your app - more options available
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    build_no = get_version_number + '.' + Time.new.strftime("%m%d%H%M")
    increment_build_number(build_number: build_no)
    match(type: "appstore")
    gym(scheme: "Mic",
        workspace: "Mic.xcworkspace",
        output_directory: "./build/",
        export_method: "app-store",
        clean: true,
        configuration: "Release",
        output_name: "sdjj") # Build your app - more options available
    deliver
  end

  # You can define as many lanes as you want

  after_all do |lane|
   
  end

  error do |lane, exception|
  
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.58.0  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-firim | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.8        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| coderay                   | 1.1.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| escape                    | 0.0.4        |
| excon                     | 0.56.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-firim     | 0.1.0        |
| firim                     | 0.1.4        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.4       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.1        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| method_source             | 0.8.2        |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.3.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| slop                      | 3.6.0        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.2.1        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-09-25**
</details>

**Comment by yangmiemie1116** [comment]
it always works well until update to Xcode 9 and fastlane 2.58.0

**Comment by KrauseFx** [comment]
This is not an error message, but a warning, can you share the complete output, with the actual error? :)

**Comment by Panajev** [comment]
This is what gym provides. Will re run with extra debug info soon:

```
INFO [2017-09-25 19:02:46.17]: ▸ Signing BuildScripts/build/DerivedDataBETA/Build/Intermediates.noindex/ArchiveIntermediates/Project/InstallationBuildProductsLocation/Applications/Project.app
INFO [2017-09-25 19:02:46.83]: ▸ Touching Project.app.dSYM
INFO [2017-09-25 19:02:47.46]: ▸ Archive Succeeded
DEBUG [2017-09-25 19:02:48.46]: Stored the archive in: /Users/goff.marocchi/Library/Developer/Xcode/Archives/2017-09-25/Project 2017-09-25 19.01.00.xcarchive
WARN [2017-09-25 19:02:48.47]: Generated plist file with the following values:
INFO [2017-09-25 19:02:48.47]: ▸ -----------------------------------------
INFO [2017-09-25 19:02:48.47]: ▸ {
INFO [2017-09-25 19:02:48.47]: ▸   "provisioningProfiles": {
INFO [2017-09-25 19:02:48.47]: ▸     "com.gamesys.corp.project": "Project Development"
INFO [2017-09-25 19:02:48.47]: ▸   },
INFO [2017-09-25 19:02:48.47]: ▸   "method": "enterprise"
INFO [2017-09-25 19:02:48.47]: ▸ }
INFO [2017-09-25 19:02:48.47]: ▸ -----------------------------------------
INFO [2017-09-25 19:02:48.47]: This results in the following plist file:
INFO [2017-09-25 19:02:48.47]: ▸ -----------------------------------------
INFO [2017-09-25 19:02:48.47]: ▸ <?xml version="1.0" encoding="UTF-8"?>
INFO [2017-09-25 19:02:48.47]: ▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
INFO [2017-09-25 19:02:48.47]: ▸ <plist version="1.0">
INFO [2017-09-25 19:02:48.47]: ▸ <dict>
INFO [2017-09-25 19:02:48.47]: ▸ 	<key>method</key>
INFO [2017-09-25 19:02:48.47]: ▸ 	<string>enterprise</string>
INFO [2017-09-25 19:02:48.47]: ▸ 	<key>provisioningProfiles</key>
INFO [2017-09-25 19:02:48.47]: ▸ 	<dict>
INFO [2017-09-25 19:02:48.47]: ▸ 		<key>com.gamesys.corp.project</key>
INFO [2017-09-25 19:02:48.47]: ▸ 		<string>Project Development</string>
INFO [2017-09-25 19:02:48.47]: ▸ 	</dict>
INFO [2017-09-25 19:02:48.47]: ▸ </dict>
INFO [2017-09-25 19:02:48.47]: ▸ </plist>
INFO [2017-09-25 19:02:48.47]: ▸ -----------------------------------------
```

**Comment by yangmiemie1116** [comment]
it works well after add `export_options: { compileBitcode: false} ` to gym @KrauseFx , thanks
