### ISSUE TITLE
--export_options is error?

### ISSUE THREAD

**Issue by zhuayi** [fastlane/fastlane#10412]
fastlane gym --workspace ./puhui.xcworkspace --scheme puhui  --clean --configuration release --archive_path ./output//999/10001318.xcarchive --output_directory ./output//999/10001318 --output_name 10001318.ipa --export_team_id ****  --export_options {"provisioningProfiles": {"com.xiaoying.beijing.puhui": "puhui_distribution"}} 

帮我看看这样的语法对不对?

**Comment by KrauseFx** [comment]
Please provide more information about this issue, so we can help you
