### ISSUE TITLE
undefined method `fetch' for nil:NilClass when trying to fetch from ITC with Spaceship

### ISSUE THREAD

**Issue by lucabartoletti** [fastlane/fastlane#10416]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I created this lane in my `Fastfile`:

```
  lane :setup_release_notes do
      Spaceship::Tunes.login
      print "after login\n"
      app = Spaceship::Tunes::Application.find(MY_APP_ID)
      if (app)
        print "app: " + app.name + "\n"
        print "before fetch"
        v = app.edit_version
        if (v) 
          print "v: \n" + v
          release_notes_languages = v.release_notes.languages
          release_notes_languages do |language|
             v.release_notes[language] = "Bug fixes and Speed improvements"
           end      
           v.save!
         else
           print "No edit version available 😔"
         end
       else
           print "Can't find app with id MY_APP_ID 😔"         
       end
  end
```
The problem is that trying to use Spaceship to set the release not for the "edit version" I get the following error:

```
/Users/user/.rvm/gems/ruby-2.3.1/gems/spaceship-1.0.0/lib/spaceship/tunes/app_version.rb:733:in `block in setup_trailers_for': [!] undefined method `fetch' for nil:NilClass (NoMethodError)
```
Once I try to run any command that tries to fetch data from ITC. The error happens at the line
`v = app.edit_version`

The fetch of the app

`app = Spaceship::Tunes::Application.find(MY_APP_ID)`

works cause I can read the name of the app with

`app.name`

### Captured Output

Command Used: `setup_release_notes`
<details><summary>Output/Log</summary>

```

DEBUG [2017-09-26 12:20:55.54]: Checking if there are any plugins that should be loaded...
DEBUG [2017-09-26 12:20:55.54]: Loading 'fastlane-plugin-versioning' plugin
INFO [2017-09-26 12:20:55.60]: gem 'fastlane-plugin-versioning' is already installed
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-versi  | 0.2.5   | get_app_store_version  |
| oning                  |         | _number                |
|                        |         | get_build_number_from  |
|                        |         | _plist                 |
|                        |         | get_info_plist_path    |
|                        |         | get_version_number_fr  |
|                        |         | om_git_branch          |
|                        |         | get_version_number_fr  |
|                        |         | om_plist               |
|                        |         | increment_build_numbe  |
|                        |         | r_in_plist             |
|                        |         | increment_version_num  |
|                        |         | ber_in_plist           |
+------------------------+---------+------------------------+

WARN [2017-09-26 12:20:55.73]: You require a gem, if this is a third party gem, please use `fastlane_require 'spaceship'` to ensure the gem is installed locally
INFO [2017-09-26 12:20:55.73]: -------------------------------------------------
INFO [2017-09-26 12:20:55.73]: --- Step: Verifying required fastlane version ---
INFO [2017-09-26 12:20:55.73]: -------------------------------------------------
INFO [2017-09-26 12:20:55.73]: Your fastlane version 2.59.0 matches the minimum requirement of 2.58.0  ✅
INFO [2017-09-26 12:20:55.74]: ------------------------------
INFO [2017-09-26 12:20:55.74]: --- Step: default_platform ---
INFO [2017-09-26 12:20:55.74]: ------------------------------
INFO [2017-09-26 12:20:55.74]: Driving the lane 'ios setup_release_notes' 🚀
after login
WARN [2017-09-26 12:21:01.05]: Lane Context:
INFO [2017-09-26 12:21:01.05]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios setup_release_notes"}
ERROR [2017-09-26 12:21:01.06]: undefined method `fetch' for nil:NilClass
INFO [2017-09-26 12:21:01.06]: Successfully generated documentation at path '/Users/user/Workspace/project/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
+------+---------------------+-------------+

+------------+--------------+----------------+
|          Plugin updates available          |
+------------+--------------+----------------+
| Plugin     | Your Version | Latest Version |
+------------+--------------+----------------+
| versioning | 0.2.5        | 0.2.8          |
+------------+--------------+----------------+
INFO [2017-09-26 12:21:01.08]: To update all plugins, just run
INFO [2017-09-26 12:21:01.08]: $ fastlane update_plugins

ERROR [2017-09-26 12:21:01.08]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `fetch' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60fetch'%20for%20nil+repo:fastlane/fastlane
➡️  undefined method `details' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/9947 [open] 5 💬
    2 weeks ago

➡️  Unable to fetch build number from TestFlight 
    https://github.com/fastlane/fastlane/issues/9662 [open] 7 💬
    18 hours ago

➡️  undefined method `fetch' for nil:NilClass in spaceship through deliver
    https://github.com/fastlane/fastlane/issues/9373 [closed] 4 💬
    3 weeks ago

and 69 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60fetch%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```
<REDACT FASTFILE>
  
  desc "Prepare the release notes for all languages with the dummy test"
  lane :setup_release_notes do
      Spaceship::Tunes.login
      print "after login\n"
      app = Spaceship::Tunes::Application.find(MY_APP_ID)
      l = app.live_version
      print "live version: " + l.version + "\n"
      print "app status: " + l.app_status + "\n"
      if (app)
        print "app: " + app.name + "\n"
        print "before fetch"
        v = app.edit_version
        if (v) 
          print "v: \n" + v
          release_notes_languages = v.release_notes.languages
          release_notes_languages do |language|
             v.release_notes[language] = "Bug fixes and Speed improvements"
           end      
           v.save!
         else
           print "No edit version available 😔"
         end
       else
           print "Can't find app with id MY_APP_ID 😔"         
       end
  end
  
<REDACT FASTFILE>
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

apple_id "my@email.com" # Your Apple email address

for_lane :rc do
    app_identifier 'com.the_app_identifier'
end

for_lane :daily do
    app_identifier "com.the_app_identifier.daily"
end

team_id "MY_TEAM_ID"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.59.0  | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning | 0.2.5   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| io-console                 | 0.4.5        |
| CFPropertyList             | 2.3.5        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| babosa                     | 1.0.2        |
| bundler                    | 1.15.4       |
| claide                     | 1.0.2        |
| coderay                    | 1.1.2        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| highline                   | 1.7.8        |
| commander                  | 4.4.3        |
| commander-fastlane         | 4.4.5        |
| dotenv                     | 2.2.1        |
| excon                      | 0.59.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.13.1       |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.12.2       |
| fastimage                  | 2.1.0        |
| gh_inspector               | 1.0.3        |
| jwt                        | 1.5.6        |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.12.2       |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.7.3        |
| googleauth                 | 0.5.3        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| google-api-client          | 0.13.6       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.3.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| slack-notifier             | 1.5.1        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.5.0        |
| word_wrap                  | 1.0.0        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| xcpretty-travis-formatter  | 0.0.4        |
| credentials_manager        | 1.0.0        |
| fastlane-plugin-versioning | 0.2.5        |
| method_source              | 0.8.2        |
| openssl                    | 2.0.6        |
| pry                        | 0.11.0       |
| xcode-install              | 2.3.0        |
</details>

*generated on:* **2017-09-26**
</details>

**Comment by KrauseFx** [comment]
I think trailers currently don't work, they broke with the iOS 11 update where people could upload multiple trailers. Is that something you'd be interested looking into and updating?

**Comment by lucabartoletti** [comment]
Hi Felix

I'm not a ruby expert, but I would like to give it a shoot. I'll let you know how it procede

**Comment by KrauseFx** [comment]
Wohooo, awesome 👍 Check out the `.md` files we have in the root of this project, that tell you more about how to use Charles
