### ISSUE TITLE
Google Api Error: multiApkShadowedActiveApk despite check_superseded_tracks

### ISSUE THREAD

**Issue by atom-b** [fastlane/fastlane#10410]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

A build has been deployed to the Google Play beta track. I attempt to publish a new build, with a larger build number, directly to the production track. `check_superseded_tracks` is `true`. I still receive the error `Google Api Error: multiApkShadowedActiveApk: Version 123456789 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.`

Publishing the latest build to the beta track then promoting from beta to production works fine.

```
$ fastlane android publish

[16:38:38]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:38:41]: -----------------------------
[16:38:41]: --- Step: update_fastlane ---
[16:38:41]: -----------------------------
[16:38:41]: Looking for updates for fastlane...
[16:38:47]: Nothing to update
[16:38:47]:
[16:38:47]: Please help us test early releases of fastlane by opting into nightly builds
[16:38:47]: Just replace your `update_fastlane` call with
[16:38:47]:
[16:38:47]: update_fastlane(nightly: true)
[16:38:47]:
[16:38:47]: Nightly builds are reviewed and tested just like the public releases
[16:38:47]:
[16:38:47]: -------------------
[16:38:47]: --- Step: is_ci ---
[16:38:47]: -------------------
[16:38:47]: -------------------------------------------------
[16:38:47]: --- Step: Verifying required fastlane version ---
[16:38:47]: -------------------------------------------------
[16:38:47]: Your fastlane version 2.59.0 matches the minimum requirement of 2.57.0
[16:38:47]: ------------------------------
[16:38:47]: --- Step: default_platform ---
[16:38:47]: ------------------------------
[16:38:47]: Driving the lane 'android publish'
[16:38:47]: --------------------
[16:38:47]: --- Step: supply ---
[16:38:47]: --------------------
+-------------------------+------------------------------------+
|                  Summary for supply 2.59.0                   |
+-------------------------+------------------------------------+
| apk_paths               | ["out/my.apk"]                     |
| skip_upload_metadata    | false                              |
| skip_upload_images      | true                               |
| skip_upload_screenshots | true                               |
| check_superseded_tracks | true                               |
| package_name            | com.some.package.id                |
| track                   | production                         |
| metadata_path           | ./fastlane/metadata/android        |
| json_key                | ../some/path/google.json           |
| skip_upload_apk         | false                              |
| validate_only           | false                              |
+-------------------------+------------------------------------+

[16:38:49]: Preparing to upload for language 'en-US'...
[16:38:49]: Updating changelog for code version '123456789' and language 'en-US'...

<other changelog updates ommitted for brevity...>

[16:39:19]: Updating track 'production'...
[16:39:19]: Checking superseded tracks...
[16:39:20]: Uploading all changes to Google Play...
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | android         |
| LANE_NAME        | android publish |
+------------------+-----------------+
[16:39:24]: Google Api Error: multiApkShadowedActiveApk: Version 123456789 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.
+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | update_fastlane     | 6           |
| 2    | is_ci               | 0           |
| 3    | Verifying required  | 0           |
|      | fastlane version    |             |
| 4    | default_platform    | 0           |
| 💥   | supply              | 36          |
+------+---------------------+-------------+
[16:39:24]: fastlane finished with errors
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.2       |
</details>

*generated on:* **2017-09-25**
</details>

**Comment by jaynakus** [comment]
Same issue using fastlane version 2.61.0

**Comment by corneliu-serediuc** [comment]
Same issue using 2.61.0.

It seems there is no way to push the apk via fastlane if the version number is smaller. You can still do it manually in Google Play -> App Releases -> Manual Upload.

This breaks the Continuous Deployment process and I have not found an alternative yet.
