### ISSUE TITLE
Fastlane init failing at Starting login with user ... prompt following update from 2.55.0 to 2.59.0

### ISSUE THREAD

**Issue by dh256** [fastlane/fastlane#10419]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Following update of fast lane from 2.55.0 to 2.59.0, fastlane init is freezing at the "Starting login with user ..." command after prompting for Apple Id.

##### Complete output when running fastlane, including the stack trace and command used

16:45:32]: Detected iOS/Mac project in current directory...
[16:45:32]: This setup will help you get up and running in no time.
[16:45:32]: fastlane will check what tools you're already using and set up
[16:45:32]: the tool automatically for you. Have fun! 
[16:45:32]: $ xcodebuild -showBuildSettings -project ./FastlaneDemo.xcodeproj
2017-09-26 16:45:33.121 xcodebuild[26984:480011] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FortifyScanningPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[16:45:33]: Your Apple ID (e.g. fastlane@krausefx.com): apple.id@xxxxx.com
[16:45:49]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[16:45:49]: Starting login with user 'apple.id@xxxxx.com

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.6                                           |
| Ruby                        | 2.2.4                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.11.0 (Apple Git-81)                 |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane               |
| Host                        | Mac OS X 10.12.6 (16G29)                          |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                        |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                        |
| Is contained                | true                                              |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-8.3.2.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.5       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.2.1        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-09-26**
</details>

**Comment by KrauseFx** [comment]
That's weird, how long have you left it running? Can you try the same from a different Mac / internet connection?

**Comment by dh256** [comment]
Hi Felix

Left fastlane init running for around 5 minutes, multiple times. Tried it on two different WI-Fi networks and seeing the same issue (unable to test on another Mac). Was definitely working ok with 2.55.0. Issue started to occur immediately following the update to 2.59.0.

**Comment by dh256** [comment]
Also worth noting that other actions that require Apple Id (e.g. fastlane match and fastlane produce) appear to be working normally.

**Comment by dh256** [comment]
Although I have a workaround for this issue (manually create the fastlane folder, Fastfile and Appfile) it would be useful to know how to get fastlane init to work. Still experiencing this issues with Fastlane 2.59.0.

**Comment by vladdaneliuc** [comment]
same here with fastlane 2.61.0 .
INFO [2017-10-11 11:27:51.17]: Starting login with user

Been waiting for 30 minutes but nothing happens. To mention is that the command fastlane spaceship with the same user works in under 2 seconds

**Comment by ToninZhao** [comment]
I got the same problem with enterprise account, fastlane 2.62.0.

**Comment by HelloHolyLi** [comment]
I get stuck at 
Loading session from '/Users/xxx/.fastlane/spaceship/xxxx@gmail.com/cookie'

and after a long while, I get this error:

/Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:382:in `block in inflate_adapter': stack level too deep (SystemStackError)

here is my env:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2017-10-31**
</details>

Does any one have any idea about this?

**Comment by wesleysui** [comment]
same problem with enterprise account, fastlane 2.63.0.

**Comment by ohayon** [comment]
Is this happening for any folks who are not using an enterprise account?

**Comment by drumnation** [comment]
Happening to me. I have an enterprise account.

**Comment by negovrodion** [comment]
The same issue with enterprise account.

**Comment by taquitos** [comment]
I'm taking a look into this.

**Comment by taquitos** [comment]
I'm able to repro the hang, it's been about a minute and a half for me.

**Comment by taquitos** [comment]
Root cause is `https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/detail` is returning a `403` with `{"data":null,"messages":{"warn":null,"error":["insufficient privileges"],"info":null},"statusCode":"ERROR"}`
And then we're going into an exception handling loop.

Once iTunes Connect comes back online, I can continue to debug why this error is happening.

**Comment by taquitos** [comment]
Ok, looks like if you don't have an iTunes Connect account for that AppleID, you'll get this error. 
Can you try to login directly to `itunesconnect.apple.com`

I tried that and I see this, which means the `insufficient privileges` makes sense since `developer.apple.com` and `itunesconnect.apple.com` are 2 separate services requiring 2 separate invitations from your enterprise.

If you see this when you login to iTunes Connect, that means you need your admin to add you to your enterprise iTunes Connect account too: 

<img width="909" alt="screen shot 2017-11-13 at 4 11 02 pm" src="https://user-images.githubusercontent.com/1304821/32756112-4aa0ffb2-c88d-11e7-8f5d-e88f2bec48f3.png">

**Comment by taquitos** [comment]
Alright, so the changes I made in https://github.com/fastlane/fastlane/pull/10899 should break the exception handling looping and surface the api error.

**Comment by omerjanjua** [comment]
@taquitos How can you enrol on an iTunes connect enterprise account?
https://developer.apple.com/support/roles/

```Apple Developer Enterprise Program
Since this program does not include App Store distribution, membership benefits do not include access to iTunes Connect.```

**Comment by taquitos** [comment]
Somebody who is the admin of your `iTunes Connect` team needs to invite you into the organization. Not to be confused with the `Developer Portal` team.
It's always confusing because if you're a developer, you'll need to be invited to two separate Apple web sites, `developer.apple.com`, and `itunesconnect.apple.com`
Usually what we see is former, and company admins forget about the later.

**Comment by omerjanjua** [comment]
I am the Agent for the Enterprise account. What I tried to explain with my earlier message was according to the rules of the Apple Developer Enterprise Program. Since it does not include App Store distribution. You will not be given an iTunes Connect Account. So it's not possible to make a iTunes connect account or register to one. 

Is there a way to bypass this step in `fastlane init` if you do not have an iTunes Connect account?

**Comment by omerjanjua** [comment]
@taquitos I suspect the reason it works for you is that if you use your email which is tied to multiple developer accounts and while running `fastlane init` from the list you choose the enterprise account. That will be valid however that same email might still be registered with iTunes Connect. That doesn't mean it's valid you could've been invited to iTunes connect to that email by the normal team Admin. 

So `test@mail.com` may well be registered with both `developer.apple.com` and `itunesconnect.apple.com` but the invite for `developer.apple.com` could've come from the Enterprise team admin and `itunesconnect.apple.com` invite could've come from a team admin from one of the normal teams. 

To reproduce the issue please make a new Apple ID with a new email. Invite that Apple ID to use `developer.apple.com` from the Enterprise Account admin only. The enterprise admin will not be able to add the new member to `itunesconnect.apple.com` because it does not exist for the enterprise account. 

How can we run `fastlane init` in this scenario? 

Even if I create the `Fastfile` and `Appfile` manually I still have issues running `cert`, `sigh` or `gym`
