### ISSUE TITLE
Feature Request: Reset iOS Summary Rating

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#10422]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### in iTC a new field has been added:

- 'Reset iOS Summary Rating'

- You can reset your app’s summary rating for all territories when you release this version. Keep in mind that once this version is released, you won’t be able to restore the rating. Your app’s existing customer reviews will still appear on the App Store. View Ratings and Reviews

With two options:

- Keep existing rating

- Reset rating when this version is released 

Can this field be added to the fields that can be updated using Fastlane?

Thanks

**Comment by adellibovi** [comment]
@KrauseFx, I would like to work on this issue if it’s something we want to add, which I suppose yes, but please confirm.
Also would you mind to point me out how to approach the PR?
I.e.: do we discuss the naming of parameters ahead or I could go with my suggestions and discuss it in the PR? This would be part of “deliver” right? Thanks 😊

**Comment by KrauseFx** [comment]
Sounds great, thanks you two, [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) is a great starting point and for all `spaceship` related changes, check out https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md 👍

**Comment by adellibovi** [comment]
@KrauseFx pushed the PR 😄 🎉

**Comment by pparmaei** [comment]
@adellibovi cheers!
