### ISSUE TITLE
[build_app] fails: main.jsbundle does not exist / cannot find entry file index.js

### ISSUE THREAD

**Issue by eballeste** [fastlane/fastlane#10426]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane always fails on the **Running script 'Bundle React Native code and images** step. I can manually push the app via the `product > archive` process having successfully setup all of the certificates via `fastlane match init`.

terminal echos: **main.jsbundle does not exist**
digging into the xcodebuild logs: **Cannot find entry file index.js in any of the roots**

index.ios.js is definitely in the root of the folder, i've run `product > clean` from xcode, manually deleted the contents of the DerivedData folder, cleared the cache and wiped out / re-installed the node_modules directory, tried manually building the main.jsbundle into the root of the ios folder and editing the AppDelegates.m file to load said file but still get the same error failing in the same step of the build process.

Appreciate any help and insights anybody might be able to provide. 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.59.0"

default_platform :ios

platform :ios do
 

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number(xcodeproj: "./xxxx.xcodeproj")

    match(
      type: "appstore",
      git_url: "https://github.com/xxxx/xxxx.git"
    ) 
    gym(scheme: "xxxx")
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "xxxx")
    # snapshot
    gym(scheme: "xxxx") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "xxxx" # The bundle identifier of your app
apple_id "xxxx" # Your Apple email address

team_id "xxxx" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-09-26**
</details>

**Comment by raubas** [comment]
Okay, so I've had exactly the same issue - really annoying.

Building through xcode worked but fastlane gym failed (bundling for RN step).

At the end:

```
[10:48:05]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[10:48:05]: 📋  For the complete and more detailed error log, check the full log at:
[10:48:05]: 📋  /Users/[username]/Library/Logs/gym/[App-name].log
```

And looking in the end of that file:

```
Scanning 589 folders for symlinks in /Users/[username]/repos/app/node_modules (5ms)
Scanning 589 folders for symlinks in /Users/[username]/repos/app/node_modules (5ms)
Loading dependency graph, done.
warning: the transform cache was reset.

TypeError /Users/[username]/repos/app/index.ios.js: Duplicate declaration "stripe"
```

And after correcting this, it worked. Not the proudest moment, but hey, I can now deploy a new version to crashlytics..

**Comment by eballeste** [comment]
nice, but unrelated, mine literally says: `Cannot find entry file index.ios.js in any of the roots`, google searches return an assortment of results with no solution

**Comment by christian-smith** [comment]
This happened to me and after looking at the end of the log file ~/Library/Logs/gym/Project.log I noticed the line: Cannot find entry file index.js in any of the roots: ["/Users/user/Projects/reactnative/project"]

But the actual name of the directory on my disk was 'Reactnative/project'.  So I just renamed Reactnative on my disk to reactnative and it's working now.

**Comment by eballeste** [comment]
@christian-smith thank you your feedback! my directory indeed is structured differently! 

the error says `/projects/projectname` while in reality it's `/projects/ProjectName` i tried to test this by changing the directory to all lowercase letters but still got the same `Cannot find entry file index.js in any of the roots` error. I'm pretty sure this is what is going on though since I still can't get it to work correctly. I still have to manually archive and upload to TestFlight via xcode.

**Comment by mehdisam** [comment]
I found it here: 
https://stackoverflow.com/questions/41351739/main-jsbundle-foundation-and-security-missing-in-the-project-causing-error

**Comment by christian-smith** [comment]
I had this fail again and I noticed that in Terminal if I didn't cd into the directory using the exact casing fastlane would fail.  So if your directory is ReactNative make sure to $ cd ReactNative/ios before running fastlane.  For example $ cd reactnative/ios would change the cwd  to all lowercase instead of the proper casing on the directory.  There must be a really picky function call when checking for the existing file on a case insensitive filesystem.

**Comment by eballeste** [comment]
Thank you @christian-smith!! I finally got this to run and it was because more than one of the directories had caps in them.

```
$ pwd
this/is/current/path/to/projectname
```

correct case-sensitive path:
```
$ cd this/is/Current/PATH/to/ProjectName
```
