### ISSUE TITLE
[Discussion] Using Fastlane for more than just iOS / Android Apps

### ISSUE THREAD

**Issue by joncursi** [fastlane/fastlane#10428]
This is more of a discussion than an issue, so feel free to close if this is not the right place.

Fastlane has been saving me so much time in deploying my iOS and Android apps, and it got me thinking... why shouldn't I also be using this for my web apps? Sure, a lot of fastlane actions and plugins are iOS and Android specific, but a slew of them aren't! Such as `sh` to run shell commands, various plugins, `git` hooks, the ability to automate the creation of git tags and releases, changelogs, etc.

Is there any reason not to run web deployments through fastlane as well to automate these tasks? I know this is not necessarily why fastlane was created, but I see an equally underserved market with fully automated web deployments. I'm thinking fastlane can be used to orchestrate all of these generic tasks, and then when it comes to the actual deployment of the web app, run your app-specific command via the `sh` shell action (basically defer at that point to Capistrano for rails projects, or Galaxy for meteor projects, etc.).

@KrauseFx Thoughts?

**Comment by joncursi** [comment]
FWIW, I gave this a test-drive and it seems to be working well. I'm using fastlane as a container to deploy my Meteor web app, as well as my Serverless AWS Lambda functions. I'm using it in the method described above, where I leverage `fastlane` for the generic actions and plugins, and then use the `sh` action to run app-specific deployment commands.

**Comment by janpio** [comment]
@fastlane is deployed and managed using fastlane - so I think you are doing it right ;)

https://github.com/fastlane/fastlane/blob/master/fastlane/Fastfile

Maybe write a blog post about your setup so the bits you posted don't get buried here in this (now closed) issue?
