### ISSUE TITLE
Provided xcconfig is not used for provisioning profile selection

### ISSUE THREAD

**Issue by pkostenko** [fastlane/fastlane#10424]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If xcconfig is provided from the command line, it's not being used during the provisioning profiles search.

##### Complete output when running fastlane, including the stack trace and command used

`fastlane gym --export_method "enterprise" --xcconfig "Config.xcconfig" MyProject.xcproj`

```
DEBUG [2017-09-27 00:27:12.27]: Parsing project file 'MyProject.xcproj' to find selected provisioning profiles
DEBUG [2017-09-27 00:27:12.27]: Finding provision profiles for 'Release'
DEBUG [2017-09-27 00:27:12.63]: Merging provisioning profile mappings
DEBUG [2017-09-27 00:27:12.63]: -------------------------------------
DEBUG [2017-09-27 00:27:12.63]: Primary provisioning profile mapping:
DEBUG [2017-09-27 00:27:12.63]: {}
DEBUG [2017-09-27 00:27:12.63]: Secondary provisioning profile mapping:
DEBUG [2017-09-27 00:27:12.63]: {:"<REDACTED_BUNDLE_ID>"=>"<REDACTED_PROFILE_NAME>"}
DEBUG [2017-09-27 00:27:12.63]: Resulting in the following mapping:
DEBUG [2017-09-27 00:27:12.63]: {:"<REDACTED_BUNDLE_ID>"=>"<REDACTED_PROFILE_NAME>"}
INFO [2017-09-27 00:27:12.63]: Detected provisioning profile mapping: {:"<REDACTED_BUNDLE_ID>"=>"<REDACTED_PROFILE_NAME>"}
```
Where <REDACTED_BUNDLE_ID> and <REDACTED_PROFILE_NAME> are being the ones set in the project and not in the provided xcconfig file.

The contents of the xcconfig:

```
PRODUCT_BUNDLE_IDENTIFIER = <MyBundleId>
PROVISIONING_PROFILE_SPECIFIER = <MyProfileName>
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-09-27**
</details>

**Comment by Panajev** [comment]
This should also explain why gym throws a fit if you use variables in the Xcode project that the xcconfig specified provides. What is even more puzzling though is that by default the project and targets have an Xcode specified .xcconfig matches to them without it needed to be specified through args... but then why should gym fail to resolve them?

**Comment by jdee** [comment]
`gym` only passes the `-xcconfig` parameter to `xcodebuild`. It's not clear why that wouldn't work. Are you able to build using `xcodebuild` with that xcconfig?

**Comment by pkostenko** [comment]
I'm able to build the archive with both `xcodebuild` and `gym`. The issue is on the next signing phase because `gym` tries to find the provisioning profile and certificate by itself using only `xcodeproj`. But `gym` fails to pass xcconfig to it, which results in incorrect values taken from target configuration and placing them in export plist.

**Comment by lkraider** [comment]
Same issue here with `gym 2.73.0`. I am trying to set PROVISIONING_PROFILE_SPECIFIER using xcconfig but gym does not pass that to the profile detection command:

First, detecting from the project directly _(identifiers redacted)_:
```
$ fastlane gym

[16:38:00]: $ xcodebuild -showBuildSettings -workspace ./bmgreact.xcworkspace -scheme bmgreact
[16:38:03]: Detected provisioning profile mapping: {:"xx.com.bmgreactapplid"=>"match AppStore xx.com.bmgreactapplid"}

+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.73.0                            |
+--------------------------------------+--------------------------------------+
| workspace                            | ./bmgreact.xcworkspace               |
| scheme                               | bmgreact                             |
| destination                          | generic/platform=iOS                 |
| export_options.provisioningProfiles  | match AppStore                       |
| .xx.com.bmgreactapplid               | xx.com.bmgreactapplid                |
| output_name                          | bmgreact                             |
| build_path                           | /Users/corp/Library/Developer/Xcode  |
|                                      | /Archives/2018-01-06                 |
| clean                                | false                                |
| output_directory                     | .                                    |
| silent                               | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| skip_profile_detection               | false                                |
| xcode_path                           | /Applications/Xcode-9.1.app          |
+--------------------------------------+--------------------------------------+
```

Now, trying to pass a xcconfig file with the following contents _(identifiers redacted)_:
```
$ cat build.xcconfig
 
PROVISIONING_PROFILE_app = 00000000-0000-0000-0000-000000000000
PROVISIONING_PROFILE = $(PROVISIONING_PROFILE_$(WRAPPER_EXTENSION))
PROVISIONING_PROFILE_SPECIFIER = match AdHoc xx.com.bmgreactapplid

```

```
$ fastlane gym -y build.xcconfig

[16:39:27]: $ xcodebuild -showBuildSettings -workspace ./bmgreact.xcworkspace -scheme bmgreact
[16:39:29]: Detected provisioning profile mapping: {:"xx.com.bmgreactapplid"=>"match AppStore br.com.facilalimentos"}

+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.73.0                            |
+--------------------------------------+--------------------------------------+
| xcconfig                             | build.xcconfig                       |
| workspace                            | ./bmgreact.xcworkspace               |
| scheme                               | bmgreact                             |
| destination                          | generic/platform=iOS                 |
| export_options.provisioningProfiles  | match AppStore                       |
| .xx.com.bmgreactapplid               | xx.com.bmgreactapplid                |
| output_name                          | bmgreact                             |
| build_path                           | /Users/corp/Library/Developer/Xcode  |
|                                      | /Archives/2018-01-06                 |
| clean                                | false                                |
| output_directory                     | .                                    |
| silent                               | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| skip_profile_detection               | false                                |
| xcode_path                           | /Applications/Xcode-9.1.app          |
+--------------------------------------+--------------------------------------+

```

It should be calling instead:
`xcodebuild -showBuildSettings -workspace ./bmgreact.xcworkspace -scheme bmgreact -xcconfig build.xcconfig`

**Comment by hamdullahshah** [comment]
I'm in the same situation, having multiple bundle identifiers for same target using xcconfig. 
Which needed different provisioning profiles.

@lkraider @pkostenko 

Do you guys have any temporary solution for this ?

**Comment by lkraider** [comment]
@hamdullahshah I have a workaround which you may be able to adapt.

Basically, you need to create a plist file containing the profile names you want to use for each bundle id, then pass that as a command line option for gym.

 In my Jenkins build, I use an exec script step with this:
```sh
cat >> 'exportOptions.plist' <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>provisioningProfiles</key>
    <dict>
        <key>${APP_IDENTIFIER}</key>
        <string>${PROFILE_NAME}</string>
    </dict>
</dict>
</plist>
EOF
```
(you may need more key/value entries for projects with multiple bundle ids)

Then call gym like this:
```
fastlane gym --xcconfig "build.xcconfig" --export_options "exportOptions.plist" (...other options)
```


Also, since I don't use Fastlane lanes to drive the build, I get the profile name dynamically from sigh like this:
```
fastlane sigh "${APP_IDENTIFIER}" --skip_install
PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print Name' /dev/stdin <<< $(security cms -D -i *.mobileprovision))
```

**Comment by hamdullahshah** [comment]
@lkraider thanks 👍 will give it a try.

**Comment by chrispcampbell** [comment]
I just ran into a very similar problem where gym's `copy_mac_app` step uses the wrong executable name because it's not taking the provided xcconfig into account when it gathers the project `build_settings` as gym's first step.  I narrowed down the problem and it looks precisely the same as what @lkraider suggested in the comment above:

> It should be calling instead:
```
xcodebuild -showBuildSettings -workspace ./bmgreact.xcworkspace -scheme bmgreact -xcconfig build.xcconfig
```

So I think this issue (and the separate but related one I'm seeing) could be resolved simply by fixing `xcodebuild_parameters` here:
https://github.com/fastlane/fastlane/blob/0c23d5e64f3c193ac013e9383551149ac6e8d88c/fastlane_core/lib/fastlane_core/project.rb#L268

The fix would be to add one more line to take the xcconfig parameter into account if present:
```
      proj << "-xcconfig #{options[:xcconfig].shellescape}" if options[:xcconfig]
```

I'm hoping that someone with more familiarity with fastlane internals could confirm whether this is the correct fix and see about getting it integrated.

**Comment by hamdullahshah** [comment]
[This may not be relevant, but just incase...!!!!]

I fixed my issue, which was really strange.
The issue was that if i select the "xcconfig" in the Xcode and pass the same "config" using "gym" or even to "xcodebuild" the build will fail.

So i had to either pass it using "gym" or use Xcode so i went with the Xcode for now.
<img width="578" alt="screen shot 2018-01-26 at 10 14 13 pm" src="https://user-images.githubusercontent.com/1726321/35461103-b1ebcb14-02e6-11e8-8f0a-dece92dae7b5.png">

**Comment by lkraider** [comment]
I am still relying on the workaround.

**Comment by chrispcampbell** [comment]
I finally got around to submitting a PR.  Not quite the one liner that I described in my earlier comment, but pretty straightforward.

**Comment by lkraider** [comment]
@chrispcampbell awesome, patch looks good to me! (but I have no say whatsoever in the merge :p)

**Comment by joshdholtz** [comment]
@lkraider @chrispcampbell This is merged now so this should be fixed! Happy fastlaning 🚀
