### ISSUE TITLE
Error sending email with Mailgun

### ISSUE THREAD

**Issue by 4brunu** [fastlane/fastlane#1042]
I'm trying to send an email at the end of the lane, but I'm getting this error

    uninitialized constant Fastlane::Actions::MailgunAction::RestClient

I'm not the only one getting this error, and may be related to this commit https://github.com/fastlane/fastlane/commit/a018e060980880a04b142b022247c90cebbfa9d0

Is this commit that's breaking Mailgun integration?

Thanks and congratulations for the great work.

**Comment by micnguyen** [comment]
Hi @4brunu , I was never able to resolve the issue despite installing the rest-client gem.

**Comment by 4brunu** [comment]
Hey @micnguyen, I too have rest-client gem installed but can't send any emails.

@KrauseFx can you revert this commit and add the rest-client has a dependency?

Thanks

**Comment by truth3** [comment]
Looking forward to seeing this merged :+1:

**Comment by KrauseFx** [comment]
The error message should actually show you how to resolve this issue. 
add
```ruby
gem "rest-client"
```

to your `Gemfile` and run `bundle install`. 

Please let me know if that works. If it doesn't, please share your `Gemfile` and your complete output when running `fastlane`

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/1074, thanks everyone :+1:

**Comment by truth3** [comment]
All working well for me with latest release of fastlane (1.50.0)
