### ISSUE TITLE
Rollback action

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#1043]
Hi,

I think we should add an action for rolling back to the previous version of the app.
The need occurred to us today when we found out that the (enterprise, distributed with S3) release was bad, so we had to quickly roll back.

My thought of doing it for enterprise releases: 
 * We should know what the previous version is with [last_git_tag](https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#last_git_tag)).
 * Then we can modify app_version.json and index.html in S3 to point to the previous version.

Since I only got to work with enterprise dist released through S3, I'd like to hear your thoughts, is it useful / possible in other distributions? I guess rolling back in an AppStore release can be just to cancel the submission, or re-releasing the app with previous code-base but a newer version.

Thanks

**Comment by jcampbell05** [comment]
I think rolling back is a complex concept for distributions via the App Store. For my company we may not need t as we try to release so often

**Comment by KrauseFx** [comment]
This really sounds super complex and not possible to implement for actual App Store apps

**Comment by jcampbell05** [comment]
You could perhaps implement this yourself using a script, custom `lane` or a `rake` task. I feel this is out of scope fot fastlane

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
