### ISSUE TITLE
Using environment variables in gym does not work with app dependencies

### ISSUE THREAD

**Issue by aruld** [fastlane/fastlane#10431]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to use environment variables to update provisioning profile. This fails with an error.

```
gym(
      scheme: 'App',
      clean: true,
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile}' DEVELOPMENT_TEAM='#{team_id}'"
    )
```

The gym configuration below works, but the problem with this approach is I have to manually update the XCode profile every time I build an app. I build multiple apps and using the environment variable seems to be the recommended approach. Unfortunately, it does not work with my dependencies.

```
    gym(
      clean: true,
      scheme: "App")
```

Any help would be appreciated. I must be doing something wrong as this seems to fairly straightforward.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

`bundle exec fastlane ios beta build --env app1`

▸ Compiling RCTTouchEvent.m
▸ Compiling RCTProfile.m
▸ Compiling RCTConvert+Transform.m
▸ Compiling RCTComponentData.m
▸ Compiling RCTNavigatorManager.m
▸ Building library libReact.a
▸ Building library libReact.a
▸ Running script 'Include RCTJSCProfiler'
▸ Building RNDeviceInfo/RNDeviceInfo [Release]
▸ Check Dependencies
▸ Compiling DeviceUID.m
▸ Compiling RNDeviceInfo.m
▸ Compiling DeviceUID.m
▸ Compiling RNDeviceInfo.m
▸ Building library libRNDeviceInfo.a
▸ Building library libRNDeviceInfo.a
▸ Copying RNDeviceInfo/RNDeviceInfo.h
▸ Building QBImagePicker/QBImagePicker [Release]
▸ Check Dependencies
** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[08:29:45]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.59.0                  |
| export_method | app-store               |
| sdk           | iPhoneOS10.3.sdk        |
+---------------+-------------------------+

[08:29:45]: ▸ === BUILD TARGET QBImagePicker OF PROJECT QBImagePicker WITH CONFIGURATION Release ===
[08:29:45]: ▸ Check dependencies
[08:29:45]: ▸ QBImagePicker has conflicting provisioning settings. QBImagePicker is automatically signed, but provisioning profile 98ac250d-199c-405e-839a-c85369131866 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.
[08:29:45]: 
[08:29:45]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[08:29:45]: 📋  For the complete and more detailed error log, check the full log at:
[08:29:45]: 📋  /Users/arul/Library/Logs/gym/App-App.log
[08:29:45]: 
[08:29:45]: Looks like fastlane ran into a build/archive error with your project
[08:29:45]: It's hard to tell what's causing the error, so we wrote some guides on how
[08:29:45]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[08:29:45]: Before submitting an issue on GitHub, please follow the guide above and make
[08:29:45]: sure your project is set up correctly.
[08:29:45]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[08:29:45]: the full commands printed out in yellow in the above log.
[08:29:45]: Make sure to inspect the output above, as usually you'll find more error information there
[08:29:45]: 
+------------------------------------+-----------------------------------+
|                              Lane Context                              |
+------------------------------------+-----------------------------------+
| DEFAULT_PLATFORM                   | ios                               |
| ENVIRONMENT                        | app1                        |
| PLATFORM_NAME                      | ios                               |
| LANE_NAME                          | ios beta                          |
| SIGH_PROFILE_TYPE                  | app-store                         |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.apps.app1"=>"match  |
|                                    | AppStore com.apps.app1"}  |
+------------------------------------+-----------------------------------+
[08:29:45]: Error building the application - see the log above

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | Switch to ios          | 0           |
|      | copy_resources lane    |             |
| 4    | bash                   | 0           |
|      | ./../../copy_resource  |             |
|      | s.sh "$SKU"            |             |
| 5    | set_info_plist_value   | 0           |
| 6    | set_info_plist_value   | 0           |
| 7    | Switch to ios          | 0           |
|      | update_identifier      |             |
|      | lane                   |             |
| 8    | update_app_identifier  | 0           |
| 9    | Switch to ios          | 0           |
|      | update_display_name    |             |
|      | lane                   |             |
| 10   | update_info_plist      | 0           |
| 11   | match                  | 3           |
| 💥   | gym                    | 11          |
+------+------------------------+-------------+

[08:29:45]: fastlane finished with errors

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.59.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    match(
      type: "appstore",
      git_url: "points to certs.git"
    )
    app_identifier = ENV['APP_IDENTIFIER']
    team_id = ENV["sigh_#{app_identifier}_appstore_team-id"]
    profile = ENV["sigh_#{app_identifier}_appstore"]
    gym(
      scheme: 'App',
      clean: true,
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile}' DEVELOPMENT_TEAM='#{team_id}'"
    )
    pilot(
        skip_submission: true,
        skip_waiting_for_build_processing: false
    ) # Upload the app to TestFlight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# HELPER FUNCTIONS

def log(message)
    UI.header message
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app
apple_id "user@apple.com" # Your Apple email address

team_id "XXXXXXXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.10.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| fastlane-plugin-appicon   | 0.10.0       |
</details>

*generated on:* **2017-09-27**
</details>

**Comment by aruld** [comment]
The error message is:

`QBImagePicker has conflicting provisioning settings. QBImagePicker is automatically signed, but provisioning profile 98ac250d-199c-405e-839a-c85369131866 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.`

This is a dependency in our app and how do I make it work with my app which uses match for signing and automatic signing is disabled in our project.

**Comment by monolithic-adam** [comment]
My project is suddenly having this error with fastlane 2.59.0 and Xcode 9...

**Comment by JeromeCHA** [comment]
I am still having this issue with fastlane 2.60.1 and Xcode9...

**Comment by klinkert0728** [comment]
That's the fastlane env


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./Fastfile`</summary>

ruby
require 'faraday'
Faraday::Utils.default_params_encoder = Faraday::FlatParamsEncoder

lane :ad_hoc do

  produce(
    username: 'xxxxxx',
    app_identifier: 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing',
    app_name: 'GridTestSolution',
    app_version: '2.29',
    sku: '1510085045',
    language: 'English',
    team_id: 'xxxxx',
    skip_itc: true
  )

  profile_udid = sigh(
    username: 'xxxxxx',
    app_identifier: 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing',
    team_id: 'xxxxx',
    provisioning_name: 'GridTestSolution Provisioning Profile',
    output_path: '/tmp',
    adhoc: true,
    force: true
  )
  ENV["VELOCITY_PROFILE_UDID"] = profile_udid
  ENV["PRODUCT_BUNDLE_IDENTIFIER"] = 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing'
  puts ENV["VELOCITY_PROFILE_UDID"]
  gym(
    workspace: 'Velocity.xcworkspace',
    scheme: 'Velocity',
    configuration: 'Release',
    codesigning_identity: 'iPhone Distribution: Knomatic LLC (xxxxx)',
    clean: true,
    silent: true,
    include_bitcode: false,
    export_options: {
      compileBitcode: false,
      uploadSymbols: false,
      provisioningProfiles: {
        'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing' => "$(VELOCITY_PROFILE_UDID)"
      }
    },
    export_xcargs: "-allowProvisioningUpdates",
    xcargs: 'ENABLE_BITCODE=false',
    export_method: 'ad-hoc'
  )

end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.5        |
</details>


*generated on:* **2017-11-07**
</details>
