### ISSUE TITLE
[spaceship] initialization error

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#10434]
### Issue Description

I am getting `You must implement self.hostname` error when initializing `Spaceship` using the `new` method. The `Fastfile` is simple for better understanding purpose. This error is produced every time, no special case.

### Captured Output

Command Used: `test_lane`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/rtayal/Desktop/test2/fastlane/Appfile'
- team_name: 'appikon software private limited'
-------
Successfully loaded Appfile at path '/Users/rtayal/Desktop/test2/fastlane/Appfile'
- team_name: 'appikon software private limited'
-------

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | update_fastlane     | 5           |
+------+---------------------+-------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: You must implement self.hostname

URL: https://api.github.com/search/issues?q=You%20must%20implement%20self.hostname+repo:fastlane/fastlane
➡️  New instance of Spaceship?
    https://github.com/fastlane/fastlane/issues/3542 [closed] 8 💬
    22 Sep 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.36.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

update_fastlane

platform :ios do

  lane :test_lane do
    client = Spaceship::Client.new
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
team_name "appikon software private limited"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| openssl                   | 2.0.2        |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| bundler                   | 1.15.4       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| rdoc                      | 5.0.0        |
| addressable               | 2.5.2        |
| multi_json                | 1.12.2       |
| declarative               | 0.0.10       |
| retriable                 | 3.1.1        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-09-27**
</details>

**Comment by taquitos** [comment]
Thanks for the report, it looks like what was originally mentioned in https://github.com/fastlane/fastlane/issues/3589
around 

> client1 = Spaceship::Client.new
> client1.login(..)

Won't work because you need to specify a client subclass you want to use:
`Spaceship::PortalClient`, `Spaceship::DUClient`, `Spaceship::TestFlight::Client`, or `Spaceship::TunesClient`. 

You probably want either `Spaceship::PortalClient`: [portal_client.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/portal_client.rb) or `Spaceship::TunesClient`: [tunes_client.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb)

`PortalClient` connects to the developer portal, while `TunesClient` connects to iTunesConnect

**Comment by RishabhTayal** [comment]
@taquitos Awesome that works! 

Here is how to do it:

#### iTunes
```
client = Spaceship::TunesClient.new
client.login("username", "password")
```

#### Dev Portal
```
client = Spaceship::PortalClient.new
client.login("username", "password")
```
