### ISSUE TITLE
Uploading apk using fastlane got exception

### ISSUE THREAD

**Issue by suresh777** [fastlane/fastlane#10445]
I am trying to upload apk using fastlane 

fastlane supply apk  "path"

[!] Google Api Error: cannotUpdateApksOnTrackWithDraftRelease: Cannot update the APK configuration of the track when the track has a draft release. Please use UI to rollout or discard the draft release.

**Comment by suresh777** [comment]
where should i add fastlane env

**Comment by matheusrocha89** [comment]
@suresh777 This happens because you are trying to upload a version of your app to play store (production, beta or alpha) and there is already a version there in Draft (inside production, beta or alpha, depends what of these buckets you are trying to upload)
