### ISSUE TITLE
`app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`

### ISSUE THREAD

**Issue by avi-midtown** [fastlane/fastlane#10447]
### New Issue Checklist

- [V] Updated fastlane to the latest version
- [V] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [V] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [V] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `master`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/avi/Documents/getty/fastlane/Appfile'
- app_identifier: 'com.sidekick.Getty'
- apple_id: 'apple@sidekick.im'
- team_id: '8CBD9DP7Q2'
-------
Looking for iTunes Connect Team with ID 118610643

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | is_ci                  | 0           |
| 4    | get_version_number     | 0           |
| 💥   | app_store_build_numbe  | 5           |
|      | r                      |             |
| 6    | is_ci                  | 0           |
+------+------------------------+-------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `current_build_number' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60current_build_number'%20for%20nil+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.33.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    if is_ci
      ENV["KEYCHAIN_NAME"] = "no_prompt_keychain"
      ENV["KEYCHAIN_PASSWORD"] = "apassword"
      create_keychain(
          name: ENV["KEYCHAIN_NAME"],
          password: ENV["KEYCHAIN_PASSWORD"],
          default_keychain: true,
          unlock: true,
          timeout: 1200,
          add_to_search_list: true
      )
    end
  end

  lane :devices do
    register_devices(devices_file: "./fastlane/devices.txt")
    match(type: "adhoc", force_for_new_devices: true)
  end

  lane :certificates do
    for type in ["development", "adhoc", "appstore"] do
      match(type: type)
    end
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build a Signed Archive, incrementing the build number"
  private_lane :archive do |options|
    configuration = options[:configuration]
    export_method = options[:export_method]

    set_info_plist_value(path: "./Getty/Getty/Info.plist",
                         key: "GIT_COMMIT_HASH",
                         value: last_git_commit[:abbreviated_commit_hash])
    set_info_plist_value(path: "./Getty/Getty/Info.plist",
                         key: "GIT_BRANCH_NAME",
                         value: git_branch)
    ENV["CHANGELOG"] = changelog_from_git_commits(
        pretty: "%ad:  %B%n",
        merge_commit_filtering: "exclude_merges",
        date_format: "short"
    )
    match(
        type: export_method.delete("-"),
        keychain_name: ENV["KEYCHAIN_NAME"],
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    gym(
        scheme: "Getty",
        configuration: configuration,
        export_method: export_method,
        export_xcargs: "IDEBuildOperationMaxNumberOfConcurrentCompileTasks='sysctl -n hw.ncpu'",
        skip_package_ipa: ENV["TRAVIS_PULL_REQUEST"] != "false"
    )
  end

  desc "Sanity Test Build"
  lane :development do
    xcodebuild(
        scheme: "Getty",
        xcargs: "IDEBuildOperationMaxNumberOfConcurrentCompileTasks='sysctl -n hw.ncpu'",
        configuration: "Debug",
        build_settings: {
            "CODE_SIGNING_REQUIRED" => "NO",
            "CODE_SIGN_IDENTITY" => ""
        }
    )
  end

  desc "Submit a new Staging Build to Fabric Crashlytics"
  lane :staging do
    increment_build_number(xcodeproj: "./Getty/Getty.xcodeproj", build_number: last_build_number_from_git_tag + 1)
    archive(
        configuration: "Staging",
        export_method: "ad-hoc"
    )
    crashlytics(
        api_token: get_info_plist_value(path: "./Getty/Getty/Info.plist", key: "Fabric")["APIKey"],
        build_secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        groups: "continuous",
        notes: ENV["CHANGELOG"][0...10000]
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build_number = 1 + latest_testflight_build_number(
        version: get_version_number(xcodeproj: "./Getty/Getty.xcodeproj"),
        initial_build_number: 0,
    )
    increment_build_number(xcodeproj: "./Getty/Getty.xcodeproj", build_number: build_number)
    archive(
        configuration: "Beta",
        export_method: "app-store",
    )
    pilot(
        changelog: ENV["CHANGELOG"][0...4000] # Apple's 4000 character limit
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :master do
    build_number = 1 + app_store_build_number(
        version: get_version_number(xcodeproj: "./Getty/Getty.xcodeproj"),
        initial_build_number: 0,
    )
    increment_build_number(xcodeproj: "./Getty/Getty.xcodeproj", build_number: build_number)
    # match(type: "appstore")
    # snapshot
    archive(
        configuration: "Release",
        export_method: "app-store",
    )
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    if is_ci
      delete_keychain(name: ENV["KEYCHAIN_NAME"])
      if "#{lane}" != "development"
        add_git_tag(prefix: "#{get_version_number(xcodeproj: "./Getty/Getty.xcodeproj")}_")
        push_git_tags
      end
    end

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    if is_ci
      delete_keychain(name: ENV["KEYCHAIN_NAME"])
      slack(
          message: exception.message,
          success: false
      )
    end
  end

  def last_build_number_from_git_tag
    sh('git fetch --tags')
    version = get_version_number(xcodeproj: "./Getty/Getty.xcodeproj")
    tags = `git tag -l builds/#{lane_context[:LANE_NAME].sub(' ', '')}/#{version}_*`.split
    builds = tags.map {|tag| tag.rpartition('/').last.split('_').last.to_i}
    return builds.sort.last.to_i
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.sidekick.Getty" # The bundle identifier of your app
apple_id "apple@sidekick.im" # Your Apple email address

team_id "8CBD9DP7Q2" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 2.0.3        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2017-09-28**
</details>

<details>
<summary>Stacktrace</summary>

/Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:19:in `run': [!] undefined method `current_build_number' for nil:NilClass (NoMethodError)
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:131:in `block (2 levels) in parsing_binding'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /Users/avi/.rvm/gems/ruby-2.2.3/gems/fastlane-2.59.0/bin/fastlane:20:in `<top (required)>'
        from /Users/avi/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
        from /Users/avi/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
        from /Users/avi/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
        from /Users/avi/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
</details>

**Comment by jgcook935** [comment]
I'm referred to this issue when using Match on the latest version (2.65.0). Here's my input and output: 

```

> James-MBP:TrainerRoadWeb James$ fastlane match development --force_for_new_devices
> [08:14:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
> [08:14:21]: Successfully loaded '/Users/admin/TrainerRoadWeb/Matchfile' 📄
> 
> +---------+-------------------------------------------+
> |         Detected Values from './Matchfile'          |
> +---------+-------------------------------------------+
> | git_url | https://github.com/trainerroad/AppleCerts |
> | type    | development                               |
> +---------+-------------------------------------------+
> 
> 
> +-----------------------+-------------------------------------------+
> |                     Summary for match 2.65.0                      |
> +-----------------------+-------------------------------------------+
> | force_for_new_devices | true                                      |
> | type                  | development                               |
> | git_url               | https://github.com/trainerroad/AppleCerts |
> | git_branch            | master                                    |
> | keychain_name         | login.keychain                            |
> | readonly              | false                                     |
> | verbose               | false                                     |
> | force                 | false                                     |
> | skip_confirmation     | false                                     |
> | shallow_clone         | false                                     |
> | clone_branch_directly | false                                     |
> | skip_docs             | false                                     |
> | platform              | ios                                       |
> +-----------------------+-------------------------------------------+
> 
> [08:14:21]: Cloning remote git repo...
> [08:14:21]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
> [08:14:27]: 🔓  Successfully decrypted certificates repo
> [08:14:27]: To not be asked about this value, you can specify it using 'username'
> [08:14:27]: Your Apple ID Username: <username>
> [08:14:32]: Verifying that the certificate and profile are still valid on the Dev Portal...
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> ➡️  Gym Errors Out with: [!] undefined method `each_with_object' for nil:NilClass
>     https://github.com/fastlane/fastlane/issues/10780 [open] 6 💬
>     2 weeks ago
> 
> ➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
>     https://github.com/fastlane/fastlane/issues/10447 [open] 2 💬
>     a week ago
> 
> ➡️  undefined method `to_sym' for nil:NilClass when running gym
>     https://github.com/fastlane/fastlane/issues/10717 [closed] 11 💬
>     3 weeks ago
> 
> and 292 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]%27%20for%20nil&type=Issues&utf8=✓
> 
> 🔗  You can ⌘ + double-click on links to open them directly in your browser.
> /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/provider.rb:8:in `initialize': [!] undefined method `[]' for nil:NilClass (NoMethodError)
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/client.rb:505:in `new'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/client.rb:505:in `fetch_olympus_session'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/client.rb:472:in `send_shared_login_request'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/client.rb:669:in `do_login'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/client.rb:405:in `login'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/client.rb:121:in `login'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/spaceship/lib/spaceship/portal/spaceship.rb:92:in `login'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/match/lib/match/spaceship_ensure.rb:19:in `initialize'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/match/lib/match/runner.rb:22:in `new'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/match/lib/match/runner.rb:22:in `run'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/match/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/match/lib/match/commands_generator.rb:134:in `run'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/match/lib/match/commands_generator.rb:13:in `start'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.65.0/bin/fastlane:20:in `<top (required)>'
> 	from /Users/admin/.rvm/rubies/ruby-2.4.2/bin/fastlane:23:in `load'
> 	from /Users/admin/.rvm/rubies/ruby-2.4.2/bin/fastlane:23:in `<main>'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/bin/ruby_executable_hooks:15:in `eval'
> 	from /Users/admin/.rvm/gems/ruby-2.4.2@global/bin/ruby_executable_hooks:15:in `<main>'

```

Any updates on this?

**Comment by mpirri** [comment]
@jgcook935 This is an issue in _fastlane_, fixed in version 2.66.1 (just shipped!). Give it a try and let us know if you are still seeing issues.  Thanks!  🚴💨

**Comment by jgcook935** [comment]
@mpirri Thanks for the reply :) I was able to get the necessary work done by rolling back to the previous stable release, but I'll make sure our machines are updated to 2.66.1 going forward. Cheers!

**Comment by julestburt** [comment]
Sadly I'm seeing this issue - and am on 2.66.2:

Looking for related GitHub issues on fastlane/fastlane...

➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
    https://github.com/fastlane/fastlane/issues/10447 [open] 5 💬
    7 hours ago

➡️  undefined method `split' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/10977 [closed] 4 💬
    5 hours ago

➡️  undefined method `[]' for nil:NilClass during Match
    https://github.com/fastlane/fastlane/issues/10960 [closed] 19 💬
    6 hours ago

and 253 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60version%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `version' for nil:NilClass
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.2/deliver/lib/deliver/commands_generator.rb:165:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.2/deliver/lib/deliver/commands_generator.rb:176:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.2/deliver/lib/deliver/commands_generator.rb:12:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.2/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'

**Comment by edoardoc** [comment]
just had this while doing

```
fastlane deliver download_metadata


[15:54:28]: Do you want to overwrite existing metadata on path '/Users/eddy/App/fastlane/metadata'? (y/n)
y

Looking for related GitHub issues on fastlane/fastlane...

➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
    https://github.com/fastlane/fastlane/issues/10447 [open] 6 💬
    14 hours ago

➡️  undefined method `split' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/10977 [closed] 4 💬
    20 hours ago

➡️  undefined method `[]' for nil:NilClass during Match
    https://github.com/fastlane/fastlane/issues/10960 [closed] 19 💬
    20 hours ago

and 253 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60version%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/deliver/lib/deliver/commands_generator.rb:165:in `block (2 levels) in run': [!] undefined method `version' for nil:NilClass (NoMethodError)
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/deliver/lib/deliver/commands_generator.rb:176:in `run'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/eddy/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/bin/fastlane:20:in `<top (required)>'
	from /Users/eddy/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/eddy/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by julestburt** [comment]
I forgot to add - like edoardoc I was also executing 'fastlane deliver download_metadata'

**Comment by edoardoc** [comment]
Hi again, 

in my case I was executing download_metadata without having set `app_version "x.y.z"` inside the
Deliverfile, after I did that the problem disappears.
It makes sense that deliver needs to know from which version of your app should download metadata, maybe an easier to read error message would sort it, rather than just showing `[!] undefined method `version' for nil:NilClass`

**Comment by julestburt** [comment]
That's quite helpful to know @edoardoc . I did have mine set - but for this particular app there is no binary uploaded yet and set on iTunes as it's just been created.

I will try the same script on an existing app and report back! Thx

**Comment by julestburt** [comment]
Yes, I can confirm that on older apps where there is an existing (shipped) build on iTunes, this doesn't occur.

So it's only an issue for download_metadata, when there is no matching build for the version number.
