### ISSUE TITLE
Beep when FL is done

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#10467]
Is there a way to enable a short beep when fastlane is done uploading? ;-)

**Comment by milch** [comment]
You can just defer to the shell for that, see [this example](https://stackoverflow.com/a/33526010/1805855) I found on StackOverflow. Shell commands can easily be executed using backticks, so you can do something like this:

```ruby
lane :upload do
    #... perform upload here ...
    `osascript -e "beep"`
end
```

Note that fastlane includes a couple of [built-in ways to notify you](https://docs.fastlane.tools/actions/#notifications) about things. A better way than just to beep might be to use the [notification action](https://docs.fastlane.tools/actions/notification/) which sends a macOS notification complete with sound and everything. So you might wanna do something like this: 

```ruby
lane :upload do
    #... perform upload here ...
   notification(title: "Finished", message: "The build was succesfully uploaded",  sound: "Hero")
end
```

I'm going to close this now, but feel free to continue commenting if you have further questions

**Comment by prolog3001** [comment]
OK, Thanks :)

**Comment by KrauseFx** [comment]
Thanks @milch 👍
