### ISSUE TITLE
How i can reupload the ipa file without build again ?

### ISSUE THREAD

**Issue by mhtranbn** [fastlane/fastlane#10468]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Some time i want reupload file ipa, because it faile when upload.
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by taquitos** [comment]
Check our our docs on _deliver_ https://docs.fastlane.tools/actions/deliver/#deliver
there's an option you can where you define the location of an IPA.
