### ISSUE TITLE
fastlane's gemspec not compatible with cocoapods 1.0 beta

### ISSUE THREAD

**Issue by dpassage** [fastlane/fastlane#1047]
If my Gemfile says this:

```
source "https://rubygems.org"

gem 'cocoapods', '1.0.0.beta.1'
gem 'fastlane', '1.49.0'
```

Then I get the following error from Bundler:

```
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "claide":
  In Gemfile:
    cocoapods (= 1.0.0.beta.1) ruby depends on
      claide (< 2.0, >= 1.0.0.beta.1) ruby

    cocoapods (= 1.0.0.beta.1) ruby depends on
      claide (< 2.0, >= 1.0.0.beta.1) ruby

    fastlane (= 1.49.0) ruby depends on
      xcode-install (~> 1.0.1) ruby depends on
        claide (~> 0.9.1) ruby
```

This looks like it's really a downstream issue with `xcode-install` but it'll need dealing with sooner rather than later...

**Comment by neonichu** [comment]
xcode-install 1.2.5 allows CLAide 1.0.x now, but since neonichu/xcode-install#108 has a deliberate pinned dependency on spaceship 0.15.1 — so this will probably not be solvable in the near term.

**Comment by sirlantis** [comment]
Is making `xcode-install` a weak dependency (not a concept of Bundler sadly) a feasible option for now, since #208 failed?

I did this in https://github.com/sirlantis/fastlane/commit/5a22c942a41885ad87e5d7bb2dc4943ad5c2d7ea

**Comment by KrauseFx** [comment]
Yeah, I'll do that, thanks :+1:

**Comment by dpassage** [comment]
Thanks!
