### ISSUE TITLE
[Feature] Add import_relative

### ISSUE THREAD

**Issue by Otbivnoe** [fastlane/fastlane#10481]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Description
I have a few local repositories that use one general fastfile with import:

```ruby
import "/Users/otbivnoe/Documents/fastlane/Fastfile"
``` 

This imported profile relates to another fastfiles:

```ruby
# Fastfile
import "../RSBMatch.rb"
import "../RSBUpload.rb"
```

#### Problem
So, my problem is that when I call some lane from project directory, I can see the following *path* error:

> Could not find Fastfile at path '/Users/otbivnoe/Documents/fastlane/../RSBMatch.rb'

#### Possible Solution

Is it possible to add something similar to `require_relative` only for `import`?

**Comment by KrauseFx** [comment]
I haven't tried it yet, but I think you can use the Ruby keyword `require_relative` to import the `Fastfile`?

**Comment by Otbivnoe** [comment]
@KrauseFx, yes I tried it - unsuccessfully :(
```ruby
require_relative "../RSBMatch.rb"
require_relative "../RSBUpload.rb"
```

See the `undefined method` errors: 

> [!] undefined method `desc' for main:Object (NoMethodError)

> [!] undefined method `lane' for main:Object
