### ISSUE TITLE
Add Hacktoberfest tag to issues in Fastlane to increase visibility, support open source dev

### ISSUE THREAD

**Issue by loyaltyarm** [fastlane/fastlane#10480]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Add the Hacktoberfest project tag to Fastlane to increase visibility of the project and support open source development! Details at: https://hacktoberfest.digitalocean.com/

##### Complete output when running fastlane, including the stack trace and command used

```
n/a this time!
```

### Environment

```
n/a
```

**Comment by KrauseFx** [comment]
> Server Error

**Comment by KrauseFx** [comment]
😢
