### ISSUE TITLE
[gym] exportArchive much slower with Xcode 9

### ISSUE THREAD

**Issue by ileitch** [fastlane/fastlane#10482]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

gym has become much slower with Xcode 9. The time taken to export an archive has gone from ~1 minute with Xcode 8 to ~12 minutes with Xcode 9. Xcode 9 also seems to be producing _way_ more dSYMs.

Here's some output from Xcode 8:

```
[01:15:43]: $ /usr/bin/xcrun /Users/mac/.gem/gems/fastlane-2.55.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/rd/_y4xzbts3sxcw6h776q0xm440000gn/T/gym_config20170930-18238-vrd0ir.plist' -archivePath /Users/mac/Library/Developer/Xcode/Archives/2017-09-30/MyApp\ 2017-09-30\ 01.06.56.xcarchive -exportPath '/var/folders/rd/_y4xzbts3sxcw6h776q0xm440000gn/T/gym_output20170930-18238-1moz0qt'
[01:16:33]: Compressing 34 dSYM(s)
```

and with Xcode 9:

```
[10:39:18]: $ /usr/bin/xcrun /Users/mac/.gem/gems/fastlane-2.59.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/rd/_y4xzbts3sxcw6h776q0xm440000gn/T/gym_config20171003-38098-hv6ab0.plist' -archivePath /Users/mac/Library/Developer/Xcode/Archives/2017-10-03/MyApp\ 2017-10-03\ 10.31.53.xcarchive -exportPath '/var/folders/rd/_y4xzbts3sxcw6h776q0xm440000gn/T/gym_output20171003-38098-1lx5xm7' 
[10:51:10]: Compressing 149 dSYM(s)
```

The greatly increased number of dSYMs looks like a smoking gun. Anyone else experiencing this?

**Comment by PetrosIchor** [comment]
https://github.com/fastlane/fastlane/issues/10391#issuecomment-332423180

**Comment by Allui** [comment]
Same problem

**Comment by Allui** [comment]
I found this:
>Xcode 9 changed the default configs regarding Bitcode in archive for Development / Ad-Hoc archives.
>
>Xcode 8.3 did not use the Bitcode option during export if the export type is development / ad-hoc, but Xcode 9 does, so if you want to make the archive faster and you don’t need Bitcode you should disable that in the Xcode Archive step.
>
>This only applies for non App Store archives, for app-store type archives Xcode 8.3 did enable Bitcode as well by default, so there should be no (significant) difference on the two stacks."

And make this:
```
 gym(...,
        export_options: 'path to plist',
       ...)
```
in plist:
```
...
<key>uploadBitcode</key>
<false/>
<key>compileBitcode</key>
<false/>
...
```

**Comment by ileitch** [comment]
thanks @Allui, disabling Bitcode fixed it for me 👍

**Comment by tylerjames** [comment]
Can you still submit to App Store if you disable bitcode? Or is this only for doing test builds?

**Comment by Allui** [comment]
@tylerjames 
I use it only for ad-hoc, but
>For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required. If you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode.

[source](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.htmll)

**Comment by tylerjames** [comment]
Strange, I actually had bitcode disabled in my project and it's still slow as hell. It's not really any faster if I let Xcode itself do the build though so I don't think fastlane is to blame.

**Comment by zapjonny** [comment]
FYI I had to do it like this in my Fastfile.

```
includebitcode = false
gym(scheme: thescheme,
      export_method: theexportmethod, # export_methodが必要がどうかは・・・
      include_bitcode: includebitcode,
      configuration: theconfiguration,
      silent: true,
      destination: 'generic/platform=iOS',
      export_options: {
        provisioningProfiles: { 
          app_identifier => provisioning_profile_name,
          compileBitcode: includebitcode,
          uploadBitcode: includebitcode
        }
      }
    )
```

My point is that `include_bitcode` was not enough, I had to specify compileBitcode/uploadBitcode inside of export_options too.
