### ISSUE TITLE
Do not display title of PrintTable colored if disabled via environment variable

### ISSUE THREAD

**Issue by ChristianBecker** [fastlane/fastlane#10498]
I disabled colored output by setting the environment variable `FASTLANE_DISABLE_COLORS` to `1`. Unfortunately, the title of `PrintTable` is still printed in green:

```
+-------------------+-------------------------+
|           [32mSummary for PEM 2.59.0[0m            |
+-------------------+-------------------------+
| team_id           | ***              |
| app_identifier    | de.***.app |
| pem_name          | ***                |
| development       | false                   |
| generate_p12      | true                    |
| active_days_limit | 30                      |
| force             | false                   |
| save_private_key  | true                    |
| username          | fastlane@***.com      |
| p12_password      | ********                |
| output_path       | certs                   |
+-------------------+-------------------------+
```

I believe that the fix is quite simple and should be located somewhere around this line: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/print_table.rb#L34

**Comment by janpio** [comment]
A bit of investigation into the code:

> `FASTLANE_DISABLE_COLORS `

This variable is transformed into the "property" `colors_disabled` in the helper:
https://github.com/fastlane/fastlane/blob/5019acb53fc2adf050b4227c3e3216e365ba36ec/fastlane_core/lib/fastlane_core/helper.rb#L118

That one is mostly used to add `--color` or `--no-color` to generated commands:
https://github.com/fastlane/fastlane/search?utf8=%E2%9C%93&q=colors_disabled&type=

The exception is here where it includes some code:
https://github.com/fastlane/fastlane/blob/ed6ae9ded33f32da768f65318599161675fa3391/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L23

This is the code:
https://github.com/fastlane/fastlane/blob/ed6ae9ded33f32da768f65318599161675fa3391/fastlane_core/lib/fastlane_core/ui/disable_colors.rb
Per the comment this "code overwrites the methods from the colored gem".

Back to the table: 
What is used here is `.green` of colored directly:
https://github.com/fastlane/fastlane/search?utf8=%E2%9C%93&q=.green&type=

This should be overwritten with "nothing" vs. the default "32":
https://github.com/defunkt/colored/blob/master/lib/colored.rb#L21
Which also matches what you posted.

Now the question becomes: 
Why doesn't this work as it should?
What is special here?
Does it disable color everywhere else for you?

**Comment by ChristianBecker** [comment]
@janpio : Thank you for your investigations!

All other output is properly disabled – only the title of the PrintTable is still printed in color.

**Comment by mpirri** [comment]
@ChristianBecker Any interest in taking a stab at fixing this yourself? We are always looking for awesome PRs from the _fastlane_ community and this would be a really useful thing to have fixed. Let us know if you have any questions -- we are happy to help out!  🚀
