### ISSUE TITLE
Gym crashes since updating to 2.60

### ISSUE THREAD

**Issue by OJDee** [fastlane/fastlane#10500]
### New Issue Checklist

- [ ✅] Updated fastlane to the latest version
- [ ✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Gym crashing

/usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:135:in `match': stack level too deep (SystemStackError)
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:135:in `match_variable'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:122:in `resolve_variable_substitution'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:131:in `resolve_variable_substitution'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:87:in `resolve_build_setting'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:128:in `resolve_variable_substitution'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:131:in `resolve_variable_substitution'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:87:in `resolve_build_setting'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:128:in `resolve_variable_substitution'
	 ... 7410 levels...
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.60.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.60.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `load'
	from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.13.5 (Apple Git-94)               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                        |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 9.0                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
#fastlane_version "1.30.1"

default_platform :ios

    # increment_build_number

    gym(scheme: “MyScheme”, export_method: "app-store")

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # snapshot
    # sigh
    deliver(skip_metadata: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    snapshot
    # sigh
    deliver(skip_deploy: true, force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier “BUNDLE_IDENTIFIER HERE”
apple_id “APPLE_ID_HERE”

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.60.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-10-04**
</details>

**Comment by OJDee** [comment]
Have uninstalled fastlane and all associated files, ran fastlane init and setup appidentifier, itunes userid etc.. gym stills crashes with:

/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:135: stack level too deep (SystemStackError)

Is this a system issue or something for fastlane to address..?

**Comment by yapiskan** [comment]
I am getting exact same error. Both in local and Travis CI. None of the other "stack level too deep" issues are similar to this. One was mentioning the issue originated by the match password, but in my case it already passed the match step. Crashes as soon as gym runs.

Please help!

**Comment by taquitos** [comment]
A couple questions:
- Are you just calling `fastlane gym` and it's crashing?
- Also, I see 

Is installed via Fabric.app | true
-- | --

Is that true for you too @yapiskan?
@OJDee are you still using `fastlane` from the `Fabric.app`?

**Comment by OJDee** [comment]
@taquitos yes this was updated via Fabric. Is this no longer recommended?

**Comment by taquitos** [comment]
I just wanted to get a good understanding of how best to repro 😄 
We still support Fabric.app install 👍 
That being said, if you're in a bind, you might want to give installing it via rubygems or brew a try.

**Comment by yapiskan** [comment]
@taquitos it still crashes when i just call `fastlane gym`.
Fastlane wasn't install via Fabric. But Fabric is installed anyways. 

I uninstalled and reinstalled fastlane via rubygems. Now I am on 2.61 and still crashing. I tried installing different rvm versions as well, but no luck.

**Comment by tomaskraina** [comment]
I have this issue too. Any ideas how can I help to resolve it?

**Comment by tomaskraina** [comment]
I'm using Fastlane installed by bundler. As a work around, adding this line to `Gemfile` helps:

```
gem 'xcodeproj', '1.5.1'
```

**Comment by vburojevic** [comment]
Any ideas why reverting to 1.5.1 fixes the issue on some of some projects?
We have multiple iOS projects that use the latest Fastlane with xcodeproj 1.5.3, but it only crashes on one of them on CircleCI.

**Comment by mkalmes** [comment]
I've noticed this problem as well. As described by [tomaskraina](https://github.com/fastlane/fastlane/issues/10500#issuecomment-338161113), using `xcodeproj` v1.5.1 and `fastlane` v2.64.0 as a workaround. [This pull request][https://github.com/CocoaPods/Xcodeproj/pull/515] should fix the issue, but isn't yet integrated in the latest `xcodeproj` version (v1.5.3).

**Comment by joshdholtz** [comment]
Heyyyy 👋 Its been a while but I just wanted to check in to see if that pull request that was mentioned above solved things for everyone 😊
