### ISSUE TITLE
Not able to update Entitlements

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#10507]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

Okay, So now I can set the **_app_group_identifiers_** on the entitlements file. But 
I am not able to change the Keychain Access Groups value. 
There are only two options inside the action **_update_app_group_identifiers_**
**_entitlements_file_** and **_app_group_identifiers_**

How can I change **_Keychain Access Groups_**

**Comment by tringManoj** [comment]
Can someone plz at least take time to give an update.

**Comment by ohayon** [comment]
Hey @tringManoj could you show us how you are executing fastlane? Your command line output and Fastfile would be amazing to help us figure out what's going wrong. Thanks! 🚀

**Comment by tringManoj** [comment]
```
	update_app_group_identifiers(
			entitlements_file: entitle_path,
			app_group_identifiers: ['group.' +baseID]
	)
```

I have the above lines on my lane. It updates correctly but what I need is other than **update_app_group_identifiers
entitlements_file and app_group_identifiers**
I need an action to update the **Keychain Access Groups**
I need to change the Keychain Access Groups in enetilements
