### ISSUE TITLE
frameit has no iPhone X / Xcode 9 support?

### ISSUE THREAD

**Issue by paulshapiro** [fastlane/fastlane#10501]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After getting iPhone X snapshotting to work by letting it use the device type "iPhone2017-C", frameit now appears not to have support for the iPhone X form factor, with the output 

`Unsupported screensize [1125, 2436] for path './en-US/iPhone2017-C-….png`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.60.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-10-04**
</details>

**Comment by cherpake** [comment]
Hi, I would add deliver tool as well.

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 8           |
| 2    | Verifying required     | 0           |
|      | fastlane version       |             |
| 3    | default_platform       | 0           |
| 4    | pod install            | 6           |
| 5    | increment_build_numbe  | 2           |
|      | r                      |             |
| 6    | commit_version_bump    | 0           |
| 7    | gym                    | 124         |
| 💥   | deliver                | 11          |
+------+------------------------+-------------+

[14:43:39]: fastlane finished with errors

[!] Unsupported screen size [1125, 2436] for path './fastlane/screenshots/da/iPhone X-01Media_framed.png'

**Comment by cherpake** [comment]
Made it working with this...

`diff --git a/deliver/lib/deliver/app_screenshot.rb b/deliver/lib/deliver/app_screenshot.rb
index bd96c32..0f13cee 100644
--- a/deliver/lib/deliver/app_screenshot.rb
+++ b/deliver/lib/deliver/app_screenshot.rb
@@ -13,6 +13,8 @@ module Deliver
       IOS_47 = "iOS-4.7-in"
       # iPhone 6 Plus
       IOS_55 = "iOS-5.5-in"
+      # iPhone X
+      IOS_58 = "iOS-5.8-in"
       # iPad
       IOS_IPAD = "iOS-iPad"
       # iPad Pro
@@ -64,6 +66,7 @@ module Deliver
         ScreenSize::IOS_40 => "iphone4",
         ScreenSize::IOS_47 => "iphone6",
         ScreenSize::IOS_55 => "iphone6Plus",
+        ScreenSize::IOS_58 => "iphone58",
         ScreenSize::IOS_IPAD => "ipad",
         ScreenSize::IOS_IPAD_PRO => "ipadPro",
         ScreenSize::IOS_40_MESSAGES => "iphone4",
@@ -85,6 +88,7 @@ module Deliver
         ScreenSize::IOS_40 => "iPhone 5",
         ScreenSize::IOS_47 => "iPhone 6",
         ScreenSize::IOS_55 => "iPhone 6 Plus",
+        ScreenSize::IOS_58 => "iPhone X",
         ScreenSize::IOS_IPAD => "iPad",
         ScreenSize::IOS_IPAD_PRO => "iPad Pro",
         ScreenSize::IOS_40_MESSAGES => "iPhone 5 (iMessage)",
@@ -112,6 +116,10 @@ module Deliver
 
     def self.device_messages
       return {
+        ScreenSize::IOS_58_MESSAGES => [
+          [1125, 2436],
+          [2436, 1125]
+        ],
         ScreenSize::IOS_55_MESSAGES => [
           [1080, 1920],
           [1242, 2208]
@@ -143,6 +151,10 @@ module Deliver
 
     def self.devices
       return {
+        ScreenSize::IOS_58 => [
+          [1125, 2436],
+          [2436, 1125]
+        ],
         ScreenSize::IOS_55 => [
           [1080, 1920],
           [1242, 2208]
diff --git a/spaceship/lib/spaceship/du/du_client.rb b/spaceship/lib/spaceship/du/du_client.rb
index 211ad6e..bc175e4 100644
--- a/spaceship/lib/spaceship/du/du_client.rb
+++ b/spaceship/lib/spaceship/du/du_client.rb
@@ -93,6 +93,7 @@ module Spaceship
         ipadPro:      "MZPFT.SortedJ99ScreenShot",
         iphone6:      "MZPFT.SortedN61ScreenShot",
         iphone6Plus:  "MZPFT.SortedN56ScreenShot",
+        iphone58:     "MZPFT.SortedD22ScreenShot",
         iphone4:      "MZPFT.SortedN41ScreenShot",
         iphone35:     "MZPFT.SortedScreenShot",
         appleTV:      "MZPFT.SortedATVScreenShot",
@@ -107,6 +108,7 @@ module Spaceship
         ipadPro:      "MZPFT.SortedJ99MessagesScreenShot",
         iphone6:      "MZPFT.SortedN61MessagesScreenShot",
         iphone6Plus:  "MZPFT.SortedN56MessagesScreenShot",
+        iphone58:     "MZPFT.SortedD22MessagesScreenShot",
         iphone4:      "MZPFT.SortedN41MessagesScreenShot"
       }
     end
diff --git a/spaceship/lib/spaceship/tunes/device_type.rb b/spaceship/lib/spaceship/tunes/device_type.rb
index a124e49..2a721c1 100644
--- a/spaceship/lib/spaceship/tunes/device_type.rb
+++ b/spaceship/lib/spaceship/tunes/device_type.rb
@@ -1,7 +1,7 @@
 module Spaceship
   module Tunes
     class DeviceType
-      @types = ['iphone4', 'iphone35', 'iphone6', 'iphone6Plus', 'ipad', 'ipadPro', 'watch', 'appleTV', 'desktop']
+        @types = ['iphone4', 'iphone35', 'iphone6', 'iphone6Plus', 'iphone58', 'ipad', 'ipadPro', 'watch', 'appleTV', 'desktop']
       class << self
         attr_accessor :types
 
`

**Comment by ohayon** [comment]
Hey everyone! We pushed out a new release today that can upload iPhone X screenshots with deliver so that should be 💯 now! 

Regarding frameit: you can track this issue here. Due to legal stuff, we are still in a bit of a holding pattern to support iPhone X but hopefully this will get fixed soon! 🚀  🖼 https://github.com/fastlane/fastlane/search?q=frameit+iphone+x&type=Issues&utf8=%E2%9C%93

**Comment by MoOx** [comment]
@ohayon I just got an issue when trying to deliver screenshots https://github.com/fastlane/fastlane/issues/10805#issuecomment-344067466
