### ISSUE TITLE
"Code Sign error: No matching provisioning profiles found" until project is rebuilt in xcode IDE

### ISSUE THREAD

**Issue by owigley** [fastlane/fastlane#1050]
The first time a project is build with fastlane, gym fails with "Code Sign error: No matching provisioning profiles found". The problem persists until you have to built the project once in the xcode IDE.  Would be ideal to avoid this step for users managing remote build machines

crash report ﻿﻿c62b7afc9103f4ade85ab232d243a783

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
