### ISSUE TITLE
update_app_identifier Creates Project File Error - Project won't open after Bundle ID updation

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#10509]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

Xcode Project file error after running the action update_app_identifier.
I have set absolute app to plist and set Bundle ID correctly. 
I have no idea why it happens. 

update_app_group_identifiers & update_info_plist works fine. 

I am using xcode 9

**Comment by tringManoj** [comment]
I just found that If Bundle Identifier is set to _**PRODUCT_BUNDLE_IDENTIFIER**_ in plist **_update_app_identifier_** isn't working. It corrupts the project file. But when Bundle Identifier is to a static ID say com.abc.company and then changing the Bundle ID via **_update_app_identifier_** works fine.

**Comment by tringManoj** [comment]
Can someone plz at least take time to give an update. We are not able to use the bundle ID update actions yet. We are doing it manually on xcode each time to update the Bundle ID and other Info plist values.

**Comment by ohayon** [comment]
Hey @tringManoj - Could you share the output of this command? Also, it would be amazing if you could share a sample project that could help us reproduce this on our end 😄  🚀

**Comment by tringManoj** [comment]
```
lane :update_bundle_id do
	update_app_identifier(
		app_identifier: id,
		plist_path: $plistpath
	)
	update_info_plist(
		plist_path: $plistpath,
		plist.each{|key, value|
			if key == 'GroupingID'
				plist[key] = 'group.'+ baseID
			end
		}
	)
end
```

> I have been using fastlane for Build Automation, Scan, Snapshot, Version and Build Number Update , etc. Everything works fine since 2015. Only thing thats not working yet is update_bundle_id & update_info_plist

Output always shows SUCCESS. Not error on fastlane Run. But when I open the xcode, I could see my projects file is corrupted.

**Comment by ohayon** [comment]
Hmmm... @tringManoj, it looks like you have some custom logic/variables in your lane, is it possible that those are nil or not strings and that could be causing the issue?

**Comment by tringManoj** [comment]
Hi @ohayon . Thanks for taking time to help. All my variables are valid. I even tested with static values. It's updating the values properly for all identifiers but somewhere it's getting messed up in project file. 
As I mentioned earlier..
 If Bundle Identifier is set to PRODUCT_BUNDLE_IDENTIFIER in plist update_app_identifier isn't working. It corrupts the project file. But when Bundle Identifier is set with a static ID say com.abc.company and then changing the Bundle ID via update_app_identifier works fine.

**Comment by ohayon** [comment]
Could you try looking in the corrupted project file to see what value is set for bundle ids? You should be able to run `cat path/to/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER` to see what its getting set to, I would imagine that value is somehow invalid which could be a bug on our side for sure so it would be good to know what you see in there 😄
