### ISSUE TITLE
Feature Request - Delete/renew certificate and profile for a single bundle id

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#10502]
Please reference ticket #8756 for information.

It would be nice to have a command for match to delete/renew certificates on demand. Something like

`fastlane match -a com.bundle.name --delete`
`fastlane match -a com.bundle.name --delete_cert`
`fastlane match -a com.bundle.name --delete_profile`

`fastlane match -a com.bundle.name --renew`
`fastlane match -a com.bundle.name --renew_cert`
`fastlane match -a com.bundle.name --renew_profile`

Or something like that.

I know about the existance of `nuke` but that is not an option when your account has multiple apps.

Also, I just ran into an issue where (who knows why) a new develpment certificate was created, but the provisioning profile was not being updated with that new certificate. So I had to manually delete the profile from the git repo and the dev portal, and run match again. 

Thanks for an awesome tool!

**Comment by jlubeck** [comment]
No need for output since it's a feature request :D

**Comment by jlubeck** [comment]
Nope, feature not there yet

**Comment by jlubeck** [comment]
Nope, feature not there yet

**Comment by jlubeck** [comment]
Nope, latest version of fastlane doesn't have this feature

**Comment by ened** [comment]
This would be most appreciated.

**Comment by okonon** [comment]
@KrauseFx @robertjpayne any way you can shed some lite on this feature? seems pretty critical for reviewing soon to expire certs ahead of time.

**Comment by yakimant** [comment]
Maybe we can reopen that one, instead of creating a duplicate?
