### ISSUE TITLE
Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

### ISSUE THREAD

**Issue by LesykMelnychuk** [fastlane/fastlane#10511]
Hi
Error occurses every time i try to run scan 
Error description:
Signing /Library/Developer/Xcode/DerivedData/Application-ezbuarhxoqmqcvaeagbaiqcruxjm/Build/Products/Debug-iphonesimulator/ApplicationProvider.app/PlugIns/ApplicationProviderTests.xctest
2017-10-05 16:46:02.421 xcodebuild[29207:16188267] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
Test target ApplicationProviderTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
[16:46:04]: Exit status: 65

xcode: XCode 9.0
fastlane 2.60.1
gem --version 2.6.11

fastlane env           

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| bundler                   | 1.14.6       |
</details>

<details>
+------------------------+--------------------------------------------------------------------------------------+
|                                            Summary for scan 2.60.1                                            |
+------------------------+--------------------------------------------------------------------------------------+
| scheme                 | ApplicationProvider                                                                        |
| workspace              | Application.xcworkspace                                                                    |
| clean                  | true                                                                                 |
| devices                | ["iPhone 6"]                                                                         |
| output_directory       | build                                                                                |
| derived_data_path      | /Library/Developer/Xcode/DerivedData/Application-ezbuarhxoqmqcvaeagbaiqc  |
|                        | ruxjm                                                                                |
| skip_build             | false                                                                                |
| output_types           | html,junit                                                                           |
| buildlog_path          | ~/Library/Logs/scan                                                                  |
| include_simulator_logs | false                                                                                |
| open_report            | false                                                                                |
| skip_slack             | false                                                                                |
| slack_only_on_failure  | false                                                                                |
| use_clang_report_name  | false                                                                                |
| fail_build             | true                                                                                 |
| xcode_path             | /Applications/Xcode.app                                                              |
+------------------------+--------------------------------------------------------------------------------------+
</details>

Scan code

  desc "Runs all the tests"
  lane :test do
    targets.each do |scheme_name|
      scan(scheme: scheme_name,
           workspace: current_workspace,
           clean: true,
           devices: ['iPhone 6'],
           output_directory: "build")
    end
  end

**Comment by nicholascross** [comment]
I was getting that issue intermittently.

Specifying the following environmental variable seem to resolve the issue for me.

```
FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 scan
```

**Comment by LesykMelnychuk** [comment]
<code> ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2" </code>
Is already set in <code>before_all</code> lane
