### ISSUE TITLE
No values found in Gymfile when running on CircleCI (works locally)

### ISSUE THREAD

**Issue by lluisgerard** [fastlane/fastlane#10513]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I try to run gym on CircleCI `Gymfile` is not loaded and the build fails later on.

Screenshot from CircleCI:
![screen shot 2017-10-05 at 18 08 15](https://user-images.githubusercontent.com/1152968/31240319-32e19b10-a9f8-11e7-8b8a-195a35a7f277.png)

As you can see on the screenshot above, looks like the `Gymfile` is empty.

I know for sure that `Gymfile` contains information as you can see on the next screenshot (circleci command):
![screen shot 2017-10-05 at 18 06 29](https://user-images.githubusercontent.com/1152968/31240261-f6798836-a9f7-11e7-9a9c-d92e3af0fe62.png)

The same lane works correctly locally with the same fastlane version:
<img width="873" alt="screen shot 2017-10-05 at 18 14 47" src="https://user-images.githubusercontent.com/1152968/31240652-48a7ac22-a9f9-11e7-948a-83dea3ebb518.png">

Fastfile on `deploy_crashlytics` lane:

```
  gym(
    scheme: "FieldMargin",
    export_method: "ad-hoc"
  )
```

Gymfile

```
export_options(
	method: "ad-hoc",
	provisioningProfiles: {
		"com.fielmdargin.notesdev" => "match AdHoc com.fielmdargin.notesdev"
	}
)
```

So far I tried all sorts of things like deleting the file, creating it again and avoiding copy/paste just in case some weird character was causing the issue, but I fail to see why CircleCI is not reading the `Gymfile` file. Any ideas? Thanks!

### Environment

Local

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.6                                      |
| Ruby                        | 2.2.4                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.14.2                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane          |
| Host                        | Mac OS X 10.12.6 (16G29)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                   |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                   |
| Is contained                | false                                        |
| Is homebrew                 | true                                         |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode9.app/Contents/Developer/ |
| Xcode Version               | 9.0                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.60.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-10-05**
</details>

**Comment by KrauseFx** [comment]
Could you try defining something else in your `Gymfile` also, like the `scheme`, instead of defining it in the `Fastfile`? Just to give it a shot?

**Comment by lluisgerard** [comment]
Interesting, CircleCI does read the `scheme` but not the `export_options`.
I added the stack information from both sides because this sounds more like a Ruby issue when parsing the file (just a guess).

**CircleCI:**

```
[09:55:52]: Successfully loaded '/Users/distiller/notes-ios/fastlane/Gymfile' 📄

+---------------------+---------------------+
| Detected Values from './fastlane/Gymfile' |
+---------------------+---------------------+
| scheme              | FieldMargin         |
| export_options      |                     |
+---------------------+---------------------+
```

Stack:
```
### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.6                                       |
| Ruby                        | 2.3.5                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.13.5 (Apple Git-94)             |
| Installation Source         | ~/.gem/ruby/2.3.5/bin/fastlane                |
| Host                        | Mac OS X 10.12.6 (16G29)                      |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.5/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode-9.app/Contents/Developer/ |
| Xcode Version               | 9.0                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |
```


**Locally**:
```
[09:52:40]: Successfully loaded '/Users/lluisgerard/Xcode/apps/notes-ios Xcode 9 GM working frameworks/fastlane/Gymfile' 📄

+----------------+--------------------------------------+
|       Detected Values from './fastlane/Gymfile'       |
+----------------+--------------------------------------+
| scheme         | FieldMargin                          |
| export_options | {:method=>"ad-hoc",                  |
|                | :provisioningProfiles=>{"com.fielmd  |
|                | argin.notesdev"=>"match AdHoc        |
|                | com.fielmdargin.notesdev"}}          |
+----------------+--------------------------------------+
```

```
### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.6                                      |
| Ruby                        | 2.2.4                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.14.2                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane          |
| Host                        | Mac OS X 10.12.6 (16G29)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                   |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                   |
| Is contained                | false                                        |
| Is homebrew                 | true                                         |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode9.app/Contents/Developer/ |
| Xcode Version               | 9.0                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

```

Some context about this issue:
Now I'm trying to figure out how to use the right provisioning profile without using Gymfile so I can solve this asap. To add a little bit of context, we've moved to `match` and  `Xcode 9` recently. Until now I was using my identity to sign on circleci with a `development` cert, it's been working for months (because fastlane is awesome), but we moved to `ad-hoc` after some issues, it seems to me that fastlane gym is trying to build the app with development and then sign it with ad-hoc? that's why I had to specify adhoc profile locally to make it work.

**Comment by lluisgerard** [comment]
I'm closing this issue because I'm having multiple issues at the same time and I'm waiting for a new update. Also I'm not using Gymfile at the moment.
Will reopen when I have more info or try this again.
