### ISSUE TITLE
Syntax issue with export_options

### ISSUE THREAD

**Issue by TimMumsnet** [fastlane/fastlane#10510]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running this lane:
```
  lane :build_adhoc do 

    gym(
      scheme: "Talk",
      configuration: "AdHoc",
      clean: true,
      output_directory:"./fastlane",
      export_xcargs: "-allowProvisioningUpdates",
      export_options(
        method: "ad-hoc",
        provisioningProfiles: { 
          "com.mumsnet.app" => "Talk Ad Hoc" 
        } 
      )
    )
  end
```
I receive this syntax error, referencing the close of `export_options` 
```
[!] Syntax error in your Fastfile on line 30: Fastfile:30: syntax error, unexpected '\n', expecting =>
```

Any ideas what I'm doing wrong?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.6                                       |
| Ruby                        | 2.3.3                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.13.5 (Apple Git-94)             |
| Installation Source         | /usr/local/bin/fastlane                       |
| Host                        | Mac OS X 10.12.6 (16G29)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib              |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode 9.app/Contents/Developer/ |
| Xcode Version               | 9.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby


update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.20"

default_platform :ios

platform :ios do
  before_all do
    xcode_select "/Applications/Xcode.app" # Specifies the Xcode version
  end


  lane :build_adhoc do 

    gym(
      scheme: "Talk",
      configuration: "AdHoc",
      clean: true,
      output_directory:"./fastlane",
      export_xcargs: "-allowProvisioningUpdates",
      export_options(
        method: "ad-hoc",
        provisioningProfiles: { 
          "com.mumsnet.app" => "Talk Ad Hoc" 
        } 
      )
    )
  end


end


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.60.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 1.8.6        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-10-05**
</details>

**Comment by dcrobert** [comment]
idk if it's accurate but if I copy/paste your code above into atom with showInvisibles: true, I see extra space:
        provisioningProfiles: {   <-- I see one here
          "com.mumsnet.app" => "Talk Ad Hoc"  <-- I see one here
        }  <-- I see one here

**Comment by TimMumsnet** [comment]
Thanks @dcrobert - I found the 3x spaces and removed, so it now looks like:
```
  lane :build_adhoc do 

    gym(
      scheme: "Talk",
      configuration: "AdHoc",
      clean: true,
      output_directory:"./fastlane",
      export_xcargs: "-allowProvisioningUpdates",
      export_options(
        method: "ad-hoc",
        provisioningProfiles:{
          "com.mumsnet.app" => "Talk Ad Hoc"
        }
      )<= Issue raised here
    )
  end
```

With the response
```
[!] Syntax error in your Fastfile on line 30: Fastfile:30: syntax error, unexpected '\n', expecting =>
```

Any other ideas?

**Comment by ohayon** [comment]
Hey @TimMumsnet, it looks like you have `export_options` followed by a `(`, i think that should maybe be `export_options: { .... }`. Let us know if that works! 🚀

**Comment by TimMumsnet** [comment]
@ohayon thanks! That appears to have fixed the syntax issue. As it builds, however, the following warning is raised:

```
[09:17:05]: Couldn't automatically detect the provisioning profile mapping
[09:17:05]: There were multiple profiles for bundle identifier(s): com.mumsnet.app
[09:17:05]: You need to provide an explicit mapping of what provisioning
[09:17:05]: profile to use for each bundle identifier of your app
[09:17:05]: Couldn't automatically detect the provisioning profile mapping
[09:17:05]: There were multiple profiles for bundle identifier(s): com.mumsnet.app
[09:17:05]: You need to provide an explicit mapping of what provisioning
[09:17:05]: profile to use for each bundle identifier of your app
[09:17:05]: Couldn't automatically detect the provisioning profile mapping
[09:17:05]: There were multiple profiles for bundle identifier(s): com.mumsnet.app
[09:17:05]: You need to provide an explicit mapping of what provisioning
[09:17:05]: profile to use for each bundle identifier of your app
[09:17:05]: Couldn't automatically detect the provisioning profile mapping
[09:17:05]: There were multiple profiles for bundle identifier(s): com.mumsnet.app
[09:17:05]: You need to provide an explicit mapping of what provisioning
[09:17:05]: profile to use for each bundle identifier of your app
[09:17:05]: Detected provisioning profile mapping: {:"com.mumsnet.app"=>"Talk Ad Hoc", :"Mumsnet.TalkFramework"=>"52b4bb6e-6a5c-49c9-9b8f-2dc7ee553a33"}
```

This is a little confusing though, since after building successfully, the plist file is:
```
[09:10:30]: Generated plist file with the following values:
[09:10:30]: ▸ -----------------------------------------
[09:10:30]: ▸ {
[09:10:30]: ▸   "method": "ad-hoc",
[09:10:30]: ▸   "provisioningProfiles": {
[09:10:30]: ▸     "com.mumsnet.app": "Talk Ad Hoc",
[09:10:30]: ▸     "Mumsnet.TalkFramework": "52b4bb6e-6a5c-49c9-9b8f-2dc7ee553a33"
[09:10:30]: ▸   },
[09:10:30]: ▸   "signingStyle": "manual"
[09:10:30]: ▸ }
[09:10:30]: ▸ -----------------------------------------
```
So the archive succeeds, but the warnings are perplexing 🤔 any ideas?

**Comment by ohayon** [comment]
Hmmm that definitely is a bit strange. Is there any chance you would open up a new issue to talk about that just so that the title of this one can stay relevant to the syntax issue for history purposes? 🚀
