### ISSUE TITLE
fastlane match - unique name for each Development  certificate in the Apple Enterprise Portal

### ISSUE THREAD

**Issue by dh256** [fastlane/fastlane#10524]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

_fastlane match_ is creating a developer certificate in the Apple Enterprise Portal for each branch in the GIT repo that holds certificates (each dev team is given a branch in a single GIT repo). Unfortunately, there is no way to distinguish between the certs in the Portal as they are given the same name (see screenshot).

<img width="897" alt="samecertname" src="https://user-images.githubusercontent.com/21205793/31275939-4bc74d02-aa91-11e7-9a5e-0f51febe2067.png">

Is it possible to get _fastlane match_ to create a unique name for each  certificate, perhaps <BRANCH_NAME> - <APPLE_ID_NAME>? e.g. _Team A - IAS Build_

**Comment by KrauseFx** [comment]
The name is generated by the Apple Dev Portal, and not by fastlane as far as I know - so there is probably no way to customize this 😢
