### ISSUE TITLE
Build Xcode Plugins

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#1052]
In Alcatraz they actually build the plugins, why? So when a plugin is auto-installed the user isn't prompted if they want to load it.

https://github.com/alcatraz/Alcatraz/blob/master/Alcatraz/Installers/ATZPluginInstaller.m

**Comment by KrauseFx** [comment]
Interesting, would love @neonichu's opinion about this. Should `fastlane` build and install the plugins?

**Comment by neonichu** [comment]
Loading into a running Xcode process only affects the use right after installation. On next launch, you'll still get the loading prompt unless you have already accepted it for that bundle ID on that same Xcode version.

**Comment by jcampbell05** [comment]
Any way to by pass that prompt?

**Comment by neonichu** [comment]
You can prefill the defaults, see <http://buegling.com/blog/2015/5/2/xcode-64-plugins-and-you> — but I wouldn't recommend putting it into fastlane, for the same reason Alcatraz doesn't handle this or auto-update UUIDs: it'll only force the Xcode team to add even more hurdles into the process.

**Comment by jcampbell05** [comment]
Okay makes sense :)
