### ISSUE TITLE
Support iMessage Apps Snapshot

### ISSUE THREAD

**Issue by fishcharlie** [fastlane/fastlane#10535]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane Snapshot and Deliver should support taking screenshots for iMessage Applications. In Xcode 9 and iOS 11 Apple added support for performing UI tests on separate applications (such as messages).

	let messageApp = XCUIApplication(bundleIdentifier: "com.apple.MobileSMS")
	messageApp.terminate()
	app.terminate()
	messageApp.launch()
		
	snapshot("6-iMessage-Main")

The code above produces the following error in the SnapshotHelper.swift file.

    let screenshot = app.windows.firstMatch.screenshot() // Element Window cannot request screenshot data because it does not exist

Currently it is also supported where deliver works seamlessly with snapshot. I believe it will require changes to work seamlessly with iMessage App screenshots.

**Comment by adellibovi** [comment]
Hi @fishcharlie, screenshot for iMessage are supported. I believe you should call `setupSnapshot` with the iMessage app, if you want to screenshot that.

**Comment by adellibovi** [comment]
@KrauseFx I have a question about this issue. Calling `setupSnapshot` indeed fixes it but I was think that we could improve the API by enabling the setup to accept more then an single app.
When calling `screenshot`, the helper will pick the running in foreground one.
In my opinion this could avoid doubts, means you just need to setup for all the apps involved in the process and that would work. If you would like to see a PR I would happy to do so.

**Comment by fishcharlie** [comment]
@adellibovi So calling `setupSnapshot` twice on both the main app and iMessage App won't cause problems? Does it matter where I call each?

Also how does this integrate with Deliver? How will Deliver know to submit those screenshots as iMessage App screenshots?

**Comment by fishcharlie** [comment]
@adellibovi Any ideas on this?

**Comment by dataxpress** [comment]
Adding `concurrent_simulators false` to my Snapfile fixed this problem for me.

**Comment by ohayon** [comment]
Ohh good to know that concurrent sims don't work with iMessage screenshots at the moment. Thanks for sharing your fix @dataxpress! 🚀

**Comment by dataxpress** [comment]
Actually I am not using iMessage screenshots at all - just a regular single
target - but my test were failing with the same error until I changed that
flag. I don't know if concurrent sims are supposed to support iMessage or
not so this issue should probably still be open.

**Comment by fishcharlie** [comment]
But how does this integrate with Deliver?

**Comment by JanBrinker** [comment]
I'm getting the same error message from my CI server when running `scan`. It's not an iMessage application, so I'm not sure whether this is actually the issue here. (Running fastlane `2.64.0` and SnapshotHelper `1.7`)

**Comment by dataxpress** [comment]
Does disabling concurrent simulators fix your error?

Sent from my iPhone
________________________________

**Comment by owurman** [comment]
Disabling concurrent simulators fixed it for me. Not an iMessage app.
