### ISSUE TITLE
Support all App Services in Produce

### ISSUE THREAD

**Issue by felix-dumit** [fastlane/fastlane#10532]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

There are some newly added services in spaceship via https://github.com/fastlane/fastlane/pull/10385
That are not available in produce: 
https://github.com/fastlane/fastlane/blob/master/produce/lib/produce/developer_center.rb#L13-L32

Would be nice if they were supported so we can use them in `fastlane produce enable_services`

**Comment by felix-dumit** [comment]
Still would be nice if the feature I described was implemented.

**Comment by mpirri** [comment]
This does seem like a great idea! Any interest in submitting a pull request to add this functionality? We are always looking for awesome PRs from our community to make _fastlane_ even better.

If you are interested and have any questions, we are more than happy to help; just let us know! 🚀

**Comment by felix-dumit** [comment]
I'd be up for doing it, I'm just not sure if it would be as simple as adding those services here: https://github.com/fastlane/fastlane/blob/master/produce/lib/produce/developer_center.rb#L13-L32
Or there are more changes involved.

**Comment by janpio** [comment]
#11159 has been merged and should be included in the next release.
