### ISSUE TITLE
The login credentials for ... seem to be wrong

### ISSUE THREAD

**Issue by jasonhocker** [fastlane/fastlane#10548]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Around 6am eastern today, we had a successful build.  Around 9am eastern today, we have now started to get an error that our username/password is incorrect.  We can build outside fastlane which proves the credentials are correct.

[09:33:02]: Starting login with user 'redacted@gmail.com'
The login credentials for 'redacted@gmail.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios jenkins_build |
+------------------+-------------------+
[09:33:03]: Invalid username and password combination. Used 'redacted@gmail.com' as the username.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Executing command cd /Users/sduser/buildserver/jenkins/workspace/Mobile_iOS/build/redacted/iOS && security unlock-keychain -p redacted ~/Library/Keychains/login.keychain && security show-keychain-info ~/Library/Keychains/login.keychain && fastlane ios jenkins_build ios_build_version:5.2.0.1953 ios_version:5.2.0
Error |
Keychain "/Users/sduser/Library/Keychains/login.keychain" no-timeout
fastlane update available
Please run `brew cask reinstall fastlane`
[09:32:58]: Seems like launching fastlane takes a while - please run
[09:32:58]: 
[09:32:58]: $ [sudo] gem cleanup
[09:32:58]: 
[09:32:58]: to uninstall outdated gems and make fastlane launch faster
[09:32:58]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[09:32:58]: To get started with a Gemfile, run
[09:32:58]: 
[09:32:58]: $ bundle init
[09:32:58]: $ echo 'gem "fastlane"' >> Gemfile
[09:32:58]: $ bundle install
[09:32:58]: 
[09:32:58]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[09:32:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:33:01]: -------------------------------------------------
[09:33:01]: --- Step: Verifying required fastlane version ---
[09:33:01]: -------------------------------------------------
[09:33:01]: Your fastlane version 2.61.0 matches the minimum requirement of 1.14.1  ✅
[09:33:01]: ------------------------------
[09:33:01]: --- Step: default_platform ---
[09:33:01]: ------------------------------
[09:33:01]: Driving the lane 'ios jenkins_build' 🚀
[09:33:01]: ---------------------------------
[09:33:01]: --- Step: mkdir -p ./profiles ---
[09:33:01]: ---------------------------------
[09:33:01]: $ mkdir -p ./profiles
[09:33:01]: -----------------------------------------------
[09:33:01]: --- Step: sed -i '' '/_UDID/d' .env.default ---
[09:33:01]: -----------------------------------------------
[09:33:01]: $ sed -i '' '/_UDID/d' .env.default
[09:33:01]: ------------------
[09:33:01]: --- Step: sigh ---
[09:33:01]: ------------------

+-------------------------------------+-------------------------------------------------------+
|                                   Summary for sigh 2.61.0                                   |
+-------------------------------------+-------------------------------------------------------+
| app_identifier                      | com.redacted.watchkitapp.watchkitextension |
| provisioning_name                   | redacted Watch Extension                           |
| adhoc                               | false                                                 |
| development                         | false                                                 |
| skip_install                        | false                                                 |
| force                               | false                                                 |
| username                            | redacted@gmail.com                        |
| team_id                             | redacted                                            |
| team_name                           | redacted.                                         |
| ignore_profiles_with_different_name | false                                                 |
| skip_fetch_profiles                 | false                                                 |
| skip_certificate_verification       | false                                                 |
| platform                            | ios                                                   |
+-------------------------------------+-------------------------------------------------------+

[09:33:02]: Starting login with user 'redacted@gmail.com'
The login credentials for 'redacted@gmail.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios jenkins_build |
+------------------+-------------------+
[09:33:03]: Invalid username and password combination. Used 'redacted@gmail.com' as the username.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | mkdir -p ./profiles                 | 0           |
| 4    | sed -i '' '/_UDID/d' .env.default   | 0           |
| 💥   | sigh                                | 0           |
+------+-------------------------------------+-------------+

[09:33:03]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.2.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.61.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.1       |
</details>

*generated on:* **2017-10-09**
</details>

**Comment by salabaha** [comment]
I see the same issue on my build machine. The only what is helping is to remove "deliver.*" record from keychain

**Comment by AlexandruSpotMe** [comment]
Started happening intermittently on our builds too. Either there is a problem with iTunes or the dev portal (happens to both), or they changed something.

**Comment by salabaha** [comment]
Looks like fastlane has no access to the keychain therefore can not read/write credentials. I have successfully used "secure" command to unlock keychain. See details here https://github.com/fastlane/fastlane/issues/5634

**Comment by Lutzifer** [comment]
I also have this and can provide logs and testing

**Comment by ilsinszkibal** [comment]
Same issue both with deliver and pilot.
