### ISSUE TITLE
xcode9 Code Signing Error

### ISSUE THREAD

**Issue by Liaojiahao** [fastlane/fastlane#10543]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Xcode8 works, updated to xcode9 get the error.
There is the fastlane logs:
The following build commands failed:
Check dependencies
Check dependencies
Check dependencies
Check dependencies
Check dependencies
Check dependencies
Check dependencies
Check dependencies
(8 failures)
[16:15:44]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.61.0                  |
| export_method | enterprise              |
| sdk           | iPhoneOS11.0.sdk        |
+---------------+-------------------------+

[16:15:44]: ▸ === BUILD TARGET Colours OF PROJECT Pods WITH CONFIGURATION Release ===
[16:15:44]: ▸ Check dependencies
[16:15:44]: ▸ Code Signing Error: Colours does not support provisioning profiles. Colours does not support provisioning profiles, but provisioning profile NO_SIGNING/ has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
[16:15:44]:
[16:15:44]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[16:15:44]: 📋  For the complete and more detailed error log, check the full log at:
[16:15:44]: 📋  /Users/jahov/Library/Logs/gym/creams-creams.log
[16:15:44]:
[16:15:44]: Looks like fastlane ran into a build/archive error with your project
[16:15:44]: It's hard to tell what's causing the error, so we wrote some guides on how
[16:15:44]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[16:15:44]: Before submitting an issue on GitHub, please follow the guide above and make
[16:15:44]: sure your project is set up correctly.
[16:15:44]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[16:15:44]: the full commands printed out in yellow in the above log.
[16:15:44]: Make sure to inspect the output above, as usually you'll find more error information there
[16:15:44]:
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios release |
+------------------+-------------+
[16:15:44]: Error building the application - see the log above

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | cocoapods           | 11          |
| 4    | number_of_commits   | 0           |
| 5    | last_git_tag        | 0           |
| 💥   | gym                 | 10          |
+------+---------------------+-------------+

[16:15:44]: fastlane finished with errors

[!] Error building the application - see the log above

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"
default_platform :ios


## update me in different project
WORKSPACE_NAME = 'creams'
SCHEME_NAME = 'creams'
FIR_TOKEN = '93fe440b0c2371550f57b088ce04a6da'
## end

DEBUG_CONFIGURATION_NAME = 'Debug'
DEBUG_EXPORT_METHOD = 'ad-hoc'
DEBUG_CODESIGNING_IDENTIFIER = 'iPhone Developer: GuoYong Zhou (G66SUHG772)'
DEBUG_PROFILE_PREFIX = 'debug'

RELEASE_CONFIGURATION_NAME = 'Release'
RELEASE_EXPORT_METHOD = 'enterprise'
RELEASE_CODESIGNING_IDENTIFIER = 'iPhone Distribution: Hangzhou Jiangren Network Technology Co., Ltd'
RELEASE_PROFILE_PREFIX = 'release'

PREVIEW_CONFIGURATION_NAME = 'Preview'
PREVIEW_EXPORT_METHOD = 'enterprise'
PREVIEW_CODESIGNING_IDENTIFIER = 'iPhone Distribution: Hangzhou Jiangren Network Technology Co., Ltd'
PREVIEW_PROFILE_PREFIX = 'preview'

DISTRIBUTION_CONFIGURATION_NAME = 'AppStore'
DISTRIBUTION_EXPORT_METHOD = 'app-store'
DISTRIBUTION_CODESIGNING_IDENTIFIER = 'iPhone Distribution: Hangzhou Jiangren Network Technology Co., Ltd.'
DISTRIBUTION_PROFILE_PREFIX = 'distribution'

# 打包
def generate_ipa(typePrefix,codesigningIdentity,exportMethod,configuration,options)   
    build_number = number_of_commits
    version_number = last_git_tag

    gym(
      workspace: "./#{WORKSPACE_NAME}.xcworkspace",
      scheme: SCHEME_NAME,
      clean: true,
      output_directory: './build/',
      output_name: "#{RELEASE_CONFIGURATION_NAME}_#{version_number}_#{build_number}.ipa",
      configuration: configuration,
      codesigning_identity: "#{codesigningIdentity}",
      include_symbols: 'false',
      include_bitcode: 'false',
      archive_path: './build/',
      export_method: "#{exportMethod}"
    )

end

def versionBuildUpdate()
    build_number = number_of_commits
    version_number = last_git_tag
    increment_version_number(
      version_number: "#{version_number}" # Set a specific version number
    )
    increment_build_number(
      build_number: "#{build_number}" # set a specific number
    )
end

def uploadToFir()
    build_number = number_of_commits
    version_number = last_git_tag
    file_name = "#{RELEASE_CONFIGURATION_NAME}_#{version_number}_#{build_number}.ipa"
    sh "pwd"
    sh "fir p ../build/#{file_name} -T #{FIR_TOKEN}"
end

platform :ios do
  before_all do
    cocoapods
  end

  lane :preview do |options| #预览版
    desc "Submit a new preview Build to fir.im"
    generate_ipa(
      PREVIEW_PROFILE_PREFIX,
      PREVIEW_CODESIGNING_IDENTIFIER,
      PREVIEW_EXPORT_METHOD,
      PREVIEW_CONFIGURATION_NAME,
      options
    )
    uploadToFir()
  end

  lane :release do |options| #内测版
    desc "Submit a new Beta Build to fir.im"
    generate_ipa(
      RELEASE_PROFILE_PREFIX,
      RELEASE_CODESIGNING_IDENTIFIER,
      RELEASE_EXPORT_METHOD,
      RELEASE_CONFIGURATION_NAME,
      options
    )
    uploadToFir()
  end

lane :distribution do |options| # appstore
    # match(type: "appstore") # more information: https://codesigning.guide
    # cert(team_id: 'Hangzhou Jiangren Network Technology Co., Ltd.(6K4AKLPNTH)',username:"crafts-man@qq.com")
    # sigh(team_id: 'Hangzhou Jiangren Network Technology Co., Ltd.(6K4AKLPNTH)',username:"crafts-man@qq.com")
    desc "for keychain unlock"
    keychain_entry_builder = CredentialsManager::AccountManager.new(user: "crafts-man@qq.com")
    password_builder = keychain_entry_builder.password
    ENV["USER_PASS"] = "#{password_builder}"
    desc "for pilot(TestFlight)"
    keychain_entry_devid = CredentialsManager::AccountManager.new(user: "crafts-man@qq.com")
    password_devid = keychain_entry_devid.password
    puts "#{password_devid}"
    generate_ipa(
      DISTRIBUTION_PROFILE_PREFIX,
      DISTRIBUTION_CODESIGNING_IDENTIFIER,
      DISTRIBUTION_EXPORT_METHOD,
      DISTRIBUTION_CONFIGURATION_NAME,
      options
    )
    deliver(
      force: true,
      submit_for_review: false
    )
  end

  lane :metrics do
    #scan(scheme: SCHEME_NAME, code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./sonar-reports")
    #slather(cobertura_xml: true, jenkins: true, scheme: SCHEME_NAME, build_directory: "./DerivedData", output_directory: "./sonar-reports", proj: "./creams.xcodeproj")
    sh("cd .. && mkdir sonar-reports && lizard ./ -l swift --xml > ./sonar-reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    #sonar
end
  after_all do |lane|
  end

  error do |lane, exception|
  end
end



```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby


for_lane :release do 
	apple_id "apple-ee@91souban.com"
	app_identifier "com.jiangren.creams" # The bundle identifier of your app
	team_id "JXQ4Q3HT8V"  # Developer Portal Team ID
end

for_lane :preview do 
	apple_id "apple-ee@91souban.com"
	app_identifier "com.jiangren.creams" # The bundle identifier of your app
	team_id "JXQ4Q3HT8V"  # Developer Portal Team ID
end

for_lane :distribution do 
	apple_id "crafts-man@qq.com"
	app_identifier "com.jiangren.creams-appstore" # The bundle identifier of your app
	team_id "6K4AKLPNTH"
	itunes_connect_id "crafts-man@qq.com"
  # Developer Portal Team ID
end


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.61.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-10-09**
</details>

**Comment by Liaojiahao** [comment]
I have tried uninstalling and reinstall but not work , what's wrong with me,can you help me?

**Comment by KrauseFx** [comment]
You seem to have forgotten to attach
```
[16:15:44]: 📋 For the complete and more detailed error log, check the full log at:
[16:15:44]: 📋 /Users/jahov/Library/Logs/gym/creams-creams.log
```

**Comment by Fl0p** [comment]
As i understood xdoce9 comand line tools sometimes it fails with "Automatic" profiles detection.
This is fine workaround for me:
```
    lane :adhoc_build do
        gym(scheme: "AppName", 
            configuration:"AdHoc", 
            export_method: "ad-hoc", 
            output_name: "AppName_AdHoc_"+build_time, 
            output_directory: archives_folder, 
            xcargs: "ARCHIVE=YES", 
            export_options:{ provisioningProfiles: {
                "com.apps.app" => "match AdHoc com.apps.app",
                "com.apps.app.extension" => "match AdHoc com.apps.app.extension"    }
            } )
    end

```

**Comment by feiadan** [comment]
@Liaojiahao 
Have you got it? I have the same problem.
搞定了吗？我也遇到一样的问题。

**Comment by feiadan** [comment]
`User defaults from command line:
    IDEArchivePathOverride = /Volumes/Fuck/oldjenkins/jobs/tubobo_rider_ios/workspace/archive/archive.xcarchive
    IDEDerivedDataPathOverride = /Volumes/Fuck/oldjenkins/jobs/tubobo_rider_ios/workspace/archive

Build settings from command line:
    CODE_SIGN_IDENTITY = iPhone Distribution: Zhejiang Jeepei Technology Co., Ltd. (PV6A5J332N)
    PROVISIONING_PROFILE_SPECIFIER = com.toobob.rider AdHoc

=== BUILD TARGET Alamofire OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: Alamofire does not support provisioning profiles. Alamofire does not support provisioning profiles, but provisioning profile com.toobob.rider AdHoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

=== BUILD TARGET SnapKit OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
Code Signing Error: SnapKit does not support provisioning profiles. SnapKit does not support provisioning profiles, but provisioning profile com.toobob.rider AdHoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

=== BUILD TARGET FMDB OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: FMDB does not support provisioning profiles. FMDB does not support provisioning profiles, but provisioning profile com.toobob.rider AdHoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

=== BUILD TARGET Countly OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
Code Signing Error: Countly does not support provisioning profiles. Countly does not support provisioning profiles, but provisioning profile com.toobob.rider AdHoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

=== BUILD TARGET CryptoSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: CryptoSwift does not support provisioning profiles. CryptoSwift does not support provisioning profiles, but provisioning profile com.toobob.rider AdHoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

=== BUILD TARGET CustomExtension OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: CustomExtension does not support provisioning profiles. CustomExtension does not support provisioning profiles, but provisioning profile com.toobob.rider AdHoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
`

@KrauseFx the log file is like above。
after upgrade to Xcode9，i got this problem!

**Comment by Liaojiahao** [comment]
@feiadan  I resolved it by adding some code to podfile 

`
post_install do |installer| 
installer.pods_project.build_configurations.each do |config|
config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
end
end
`

**Comment by mkismy** [comment]
@Liaojiahao Your solution fixed the problem. Thanks!

**Comment by caoyunxiao** [comment]
to Podfile？

**Comment by robindirksen1** [comment]
@Liaojiahao at the end of the Podfile? or can you show your code?

**Comment by Liaojiahao** [comment]
@robindirksen1 
Yes. At the end of podfile

**Comment by biolinh** [comment]
Hi all,
I got a same title but another error with code signing.

> [33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/JMango360/InstallationBuildProductsLocation/Applications/360.app
> ** ARCHIVE FAILED **
> 
> 
> The following build commands failed:
> CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications360.app
> (1 failure)
> [14:45:32]: [31mExit status: 65[0m
> 
> +---------------+-------------------------+
> |            [32m[33mBuild environment[0m            |
> +---------------+-------------------------+
> | xcode_path    | /Applications/Xcode.app |
> | gym_version   | 2.68.2                  |
> | export_method | app-store               |
> | sdk           | iPhoneOS11.2.sdk        |
> +---------------+-------------------------+
> 
> [14:45:32]: ▸ [35m                      (7fa6ed04-ea94-496c-a4e9-e66be8feccd8)[0m
> [14:45:32]: ▸ [35m    /usr/bin/codesign --force --sign A22EDB7245B8CBB7CB5A2ED61ED7B980873C17E6 --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app[0m
> [14:45:32]: ▸ [35m/Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app: unknown error -1=ffffffffffffffff[0m
> [14:45:32]: ▸ [35mCommand /usr/bin/codesign failed with exit code 1[0m
> [14:45:32]: 
> [14:45:32]: [31m⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error[0m
> [14:45:32]: [33m📋  For the complete and more detailed error log, check the full log at:[0m
> [14:45:32]: [33m📋  /Users/jenkins/Library/Logs/gym/360-360.log[0m
> [14:45:32]: 
> 


Then I run the command again in terminal:
>  /usr/bin/codesign --force --sign A22EDB7245B8CBB7CB5A2ED61ED7B980873C17E6 --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app

it popups a message to require input password to allow add the certificate.

After I run the command, I can build successful. But the problem is that:
1. I must build many apps with corresponding certificate, I unable to import manually like that.
2. If I must do manually it lost the powerful feature of Fastlane. 

my Fastlane file:

>  desc "Deploy a new version to the hockey"
>   lane :upload_hockey do
>     unlock_keychain(path: "login.keychain", password: KEYCHAIN_PASSWORD)
>     sh "fastlane fastlane-credentials add --username '" + ENV["FASTLANE_USER"] +  "' --password '" + KEYCHAIN_PASSWORD + "'" 
>     match(force: false, type: "adhoc" )
>    
>     sh "pod install"
>     sh "sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' '#{ENV["PROJECT_DIR"]}'/360.xcodeproj/project.pbxproj"
>     
>     increment_build_number(build_number: BUILD_NUMBER)
>     xcclean(scheme: "360")
> 
>     PROVISIONING_PROFILE_SPECIFIER='match AdHoc ' + ENV["BUNDLE_IDENTIFIER"]
>     gym(scheme: "360", codesigning_identity: CODE_SIGN_IDENTITY,  workspace: "360.xcworkspace", configuration: "Jenkins", derived_data_path: "./build",
>         xcargs: "DEVELOPMENT_TEAM=" + ENV["TEAM_ID"] +" " "PROVISIONING_PROFILE_SPECIFIER='#{PROVISIONING_PROFILE_SPECIFIER}'"+" " "PRODUCT_BUNDLE_IDENTIFIER=" + BUNDLE_ID
>         )

>     hockey(
>     api_token: 'xxxxxxxxxxxx',
>     ipa: './build/360.ipa'
> )
>     sh "fastlane fastlane-credentials remove --username $FASTLANE_USER"
>   end


[15:30:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:30:17]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.3.2/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2m  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-  | 🚫 |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-12-06**
</details>

**Comment by ptrocki** [comment]
I had the same error on my local machine (I run this using gitlab CI on local mac mini(server)). I resolve this running command on local server and allowing keychain to get this pp.

**Comment by mcm30114** [comment]
The solution above provided by "Liaojiahao" worked like a charm.  it set the "debug" and "release" profile settings to null.  There did not seem to need any settings done to the TARGETS. In the XCWORKSPACE configuration, there should be the project name that was the .xcodeproj file prior to the POD INSTALL, and then the POD project.  It appears that the settings go against the original project settings -- and that seems to address the PROVISIONING_PROFILE_SPECIFIER issue.  

Thanks @Liaojiahao  !!

**Comment by StefanoBiasu** [comment]
A fastlane version of @Liaojiahao  workaround, (to call it from a Fastlane action):

`    project = Xcodeproj::Project.open(pods_project_dir)`
`    configurations = project.objects.select { |obj| obj.isa == 'XCBuildConfiguration'}`
`    configurations.each do |configuration|`
`    configuration.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''`
`    end`

given that _pods_project_dir_ points to **Pods.xcodeproj** file.

**Comment by manish0282** [comment]
@robindirksen1 I had the same issue and your solution worked like charm.

**Comment by daviskoh** [comment]
@Liaojiahao's solution did not work...
