### ISSUE TITLE
Feature Request - Match tool Git Cache

### ISSUE THREAD

**Issue by Fl0p** [fastlane/fastlane#10549]
## Match tool Decrypted unused profiles for every `app_identifier`

```
    ids = ["my.app.bundleid", "my.app.bundleid.exension"]
    match(type: 'adhoc', app_identifier: ids, readonly: true, git_url: git)
```

in this case match would:
```
[]: -------------------
[]: --- Step: match ---
[]: -------------------
...
[]: Cloning remote git repo...
...
INFO []: 🔓  Decrypted 'AdHoc_my.app.other_bundleid'
INFO []: 🔓  Decrypted 'AdHoc_my.app.bundleid'
INFO []: 🔓  Decrypted 'AdHoc_my.app.bundleid.exension'
INFO []: 🔓  Decrypted 'AdHoc_my.app.one_more_unused_id'
...
```

I do not want to waste my time to decrypt 'AdHoc_my.app.otherbundleid' and other redundant ids

## Match tool does not support array for `type:` option

So only workaround is:
```
    types = ["development", "adhoc", "appstore"]
    for type in types do
      match(type: type, app_identifier: ids, readonly: true, git_url: git, clone_branch_directly: true)
    end
```

in this case match tool will clone git 3 times like so:
```
[]: -------------------
[]: --- Step: match ---
[]: -------------------
...
[]: Cloning remote git repo...
...
INFO []: ▸ Cloning into '/var/folders/qb/l9v7ytx575674552...'
...
INFO []: Installing provisioning profile...
...
[]: -------------------
[]: --- Step: match ---
[]: -------------------
...
[]: Cloning remote git repo...
...
INFO []: ▸ Cloning into '/var/folders/qb/l9v353454355325...'
...
INFO []: Installing provisioning profile...
...
[]: -------------------
[]: --- Step: match ---
[]: -------------------
...
[]: Cloning remote git repo...
...
INFO []: ▸ Cloning into '/var/folders/qb/35345523452345...'
...
INFO []: Installing provisioning profile...
...
```

And after every clone match will decrypt all unused profiles and certificates again and again.
Even using `clone_branch_directly` option it took ridiculously long time.

``` fastlane.tools just saved you 16 minutes! 🎉 ```
WTH ? it runs 16 minutes for updating all profiles for 1 app.
How can i use it on my build machine that 

### One more thing

On my build machine i have a lot of projects to build.
And all they have the same git locations for profiles.

So updating profiles for projects take about 100-200 minutes.

### Request оne little change

Сhanging following temp location
```
INFO []: ▸ Cloning into '/var/folders/qb/l92523543534535...'
```
to some predefined location will save my time
...and huge amount of time to other developers.

### Cocoapods 
The Cocoapods gem already have this nice cache here ``` ~/Library/Caches/CocoaPods/...```

**Comment by KrauseFx** [comment]
Sorry, _match_ is not designed for this, as it seems like a one-off task, or do you plan to run it more regularly?

**Comment by Fl0p** [comment]
@fastlane-bot WRONG! 

@KrauseFx 
In a middle+ companies which develop (or support) several apps simultaneously it is normal to regenerate provisioning profiles couple times in a week. (New bundle id for R&D / new test device / new extension for existing app / new developer etc...)

That why it is good idea to keep _match_ in _lane_ for CI on build machines
To keep provisioning profiles up-to-date and valid for all apps and all devices.

And all we need is move git location from _tmp_ to _caches_

It looks so simple and it will save a lot of time.

**Comment by KrauseFx** [comment]
Uh yeah, that's not good, I agree, having an array option for the type would be a great way to improve the speed, however I don't think we currently have the time to work on this. If you feel like it, we'd love to review a pull request adding this functionality 👍 

Thanks for all the suggestions so far 💯
