### ISSUE TITLE
Using fastlane for Swift Framework

### ISSUE THREAD

**Issue by christoff-1992** [fastlane/fastlane#10558]
I was just wondering can we use fastlane for a swift framework/lib without setting up an app identifier etc? 

In this scenario the above is not relevant.

Thanks

**Comment by KrauseFx** [comment]
Yeah, this might work, however you won't be able to use `fastlane init`, but instead have to manually build your `Fastfile` 👍

**Comment by christoff-1992** [comment]
Ah thank you for the quick reply, I have tried this but unfortunately when running Scan it doesn’t register the fastfile existence. Does Scan make any other checks for files before running? Il take a look at the source code in the morning :) hopefully I can get it working Fastlane is awesome!

**Comment by jdee** [comment]
I'm using Fastlane to run native iOS and Android unit tests in an SDK: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/fastlane/Fastfile#L14. This is not Swift, but this might help you.

**Comment by christoff-1992** [comment]
@jdee thanks for the info :) .. not sure why it was complaining for me then, will give it another go 👍

**Comment by christoff-1992** [comment]
Thanks all I can confirm this is working as expected.
