### ISSUE TITLE
Delete apps from iTunes and Developers portal

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#10565]
hello I can't find functional for delete apps from iTunes and Developers portal. If functional exists you can give me example commands

**Comment by taquitos** [comment]
You can use Spaceship to do this sort of thing. Checkout https://github.com/fastlane/fastlane/tree/master/spaceship/docs

specifically: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md#more-cool-things-you-can-do

**Comment by GandjaFuzz** [comment]
big thanks!

**Comment by GandjaFuzz** [comment]
I find how delete from developer portal. but how delete from iTunes connect, in docs not describe this functional
