### ISSUE TITLE
Error code 65 on certain simulators with Xcode 9

### ISSUE THREAD

**Issue by AdrianBinDC** [fastlane/fastlane#10573]
### Issue Description

I get error code 65 when running `snapshot` on certain simulators and a `NSInternalInconsistencyException` is logged. 

According to [this post](https://forums.developer.apple.com/thread/87463) on Apple's developer forums, it occurs with certain simulators.

> The problem occurs offen on simulators: iPhone 5s, iPhone SE, iPad's
> The problem seems to not occur on simulators: iPhone X, iPhone 8, iPhone 8 Plus

By avoiding the iPhone 5s and iPhone SE in my SnapFile, I was able to generate screenshots without generating the error. I suspect the problem is on Apple's end, not Fastlane's, but I wanted to memorialize a solution in case someone else encounters it.

**Comment by taquitos** [comment]
Sigh. Thank you. We retry runs when they fail, so that means it's failing like 3 times in a row ☹️ Did you happen to file a radar for this?

**Comment by AdrianBinDC** [comment]
Not yet. As soon as I commented out the problematic simulators, I did [this](https://www.youtube.com/watch?v=IS7Og1zvdy8) and submitted my app to the store ;) I'll file a radar tomorrow.

**Comment by taquitos** [comment]
Hahahaha, that's the best. I'm keeping my 🤞 it passes review!
