### ISSUE TITLE
Snapshot crashes in SnapshotHelper line #186

### ISSUE THREAD

**Issue by andreaslindahl** [fastlane/fastlane#10576]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Snapshot seems to be really unstable when running XCode 9. UI test that work great when started from within XCode fail when executed via Snapshot. Mostly because various UI elements can't be found. The latest tries have resulted in a crash in SnapshotHelper.swift (version 1.5), line #186: 

Assertion Failure: SnapshotHelper.swift:186: No matches found for Find: Element at index 4 from input {(
    Other, 0x6080003835a0, traits: 8388608,
    Other, 0x6080001953a0, traits: 8388608,
    Other, 0x608000382630, traits: 8389120,
    Other, 0x608000386660, traits: 8388608
)}

These errors seem to be very sporadic, but it's mostly various elements that can't be found when running the test via Snapshot.

Is anyone else experiencing these problems as well?

**Comment by andreaslindahl** [comment]
Interestingly enough, I don't seem to get any crashes if I make sure that the iOS simulators are visible on the screen while snapshot is running...

**Comment by viplord** [comment]
Does your test method runs without errors when your run(without snapshot action) it? .

**Comment by andreaslindahl** [comment]
You mean when I run it manually from XCode? Yes, it runs fine then.

**Comment by alez007** [comment]
Interestingly enough, I'm experiencing the same problem: 

`testExample, No matches found for Find: Element at index 4 from input {(
SnapshotHelper.swift:186
	 Executed 1 test, with 1 failure (0 unexpected) in 55.595 (55.597) seconds`

test passes when I trigger it manually from xcode.

**Comment by HirotoshiKawauchi** [comment]
I also faced the same problem and tests from XCode 9 failed on Neither XCode nor the snapshot command.
I do not yet know how to reproduce this phenomenon
It seems that it crashed at the moment when "self.identifier" was called at line 186 of SnapshotHelper.swift.
Since the version of snapshot I am currently using is v2.61.0, it may be healed because the latest 2.62.0 fix includes the following modifications.
https://github.com/fastlane/fastlane/pull/10541/files

If It's had not healed with this fix I would despair

**Comment by ohayon** [comment]
Hey @andreaslindahl - let us know if the fix that @HirotoshiKawauchi mentioned helps out at all and if not, we can take a deeper look! 🚀

**Comment by andreaslindahl** [comment]
The latest version of SnapshotHelper.swift, together with the latest XCode version, seem to have solved this problem.

**Comment by ohayon** [comment]
🚨 🚀  Thanks for following up! Glad you're back up and running!
