### ISSUE TITLE
In the Playground, how can I get the information back from an app that belongs to another team?

### ISSUE THREAD

**Issue by adrianstrahan** [fastlane/fastlane#10572]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In the Playground, when I check the current team info with:
`Spaceship::Portal.client.team_information`
I get the correct information.

I can also get some information about an app that belongs to that team, using:
`Spaceship::Tunes::Application.find(<my_app_id>)`

However, when I then change the team_id with:
`Spaceship::Portal.client.team_id='<my_other_team_id>'`

and then try to get the information about an app belonging to this new team, all I get back from:
`Spaceship::Tunes::Application.find(<my_other_teams_app_id>)`

is:
`=> nil`

However,
`Spaceship::Portal.client.team_information`

shows the correct information for my other team.

So, how can I get the information back from an app that belongs to another team?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by taquitos** [comment]
When you enter: `Spaceship::Tunes.select_team` does changing the team there work?

**Comment by adrianstrahan** [comment]
Hi, thanks for looking into this.
Yes, it does work.
If I do `Spaceship::Portal.client.team_information` the details that come back are as expected.
