### ISSUE TITLE
Fastlane on Xcode Server for CI

### ISSUE THREAD

**Issue by dalu93** [fastlane/fastlane#1057]
Hello,
I have to say congrats for fastlane, is really an awesome project, but I have some problems integrating it on Xcode Server

I built a perfect `Fastfile` on my machine, but when I run the fastlane command on CI I have multiple errors starting from `fastlane command not found` (solved using `/usr/local/bin/fastlane ...`)

Then I found an error on 

    carthage(
        platform: "iOS"
    )

as `carthage command not found`, so I replaced that code with 

    # Carthage for Xcode Server using /usr/local/bin
    sh "cd .. && /usr/local/bin/carthage bootstrap --platform iOS && cd fastlane"

Passed also this error, now I have another one on `gym` command, related to `xcpretty command not found`

    [11:07:31]: ▸ [35msh: xcpretty: command not found[0m
    [11:07:57]: ▸ [35m** ARCHIVE FAILED **[0m
    [11:07:57]: ▸ [35mThe following build commands failed:[0m
    [11:07:57]: ▸ [35mCheck dependencies[0m
    [11:07:57]: ▸ [35m(1 failure)[0m
    sh: xcpretty: command not found
    ** ARCHIVE FAILED **

    The following build commands failed:
    Check dependencies
    (1 failure)
    [11:07:57]: [31mExit status: 127[0m

I tried also doing 

    sh "export PATH=$PATH:\"usr/local/bin\""

into `before_all` block, but nothing is changing.
Can you please explain me what is wrong? Because I don't think that the best solution is to solve each problem as it occurs. Thank you

**Comment by jcampbell05** [comment]
Firstly which CI are you using ?

**Comment by dalu93** [comment]
@jcampbell05  It's in the title, Xcode Server

**Comment by dalu93** [comment]
It seems that the export during the script doesn't works (I tried to do it and then print the `$PATH` and it is still the same).

I tried logging in as `_xcsbuildd` and then modifying the `.bash_profile`. It doesn't work anyway, but then I added the `source ~/.bash_profile` into fastlane script and it's working as well.
I think that was the problem

**Comment by jcampbell05** [comment]
@dalu93  Ah sorry, my bad. 

Yeah I think I've had issue like that, I think certain CIs don't run under users so certain scripts need to be manually loaded.

**Comment by dalu93** [comment]
Yeah, the problem was related to `$PATH` variable and the missing `usr/local/bin` value into it
