### ISSUE TITLE
in `to_specs': Could not find 'fastlane' (>= 0) among 20 total gem(s)

### ISSUE THREAD

**Issue by shuijinliuxi** [fastlane/fastlane#10574]
### New Issue Checklist

- [√] Updated fastlane to the latest version
- [√] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [√] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [√] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Jenkins run script on macOS in slave agent, the script is follow:

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
cd $WORKSPACE
fastlane env --capture_output
fastlane gym --capture_output
```

But it run error:

```
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
PATH=/Users/michael/.pyenv/plugins/pyenv-virtualenv/shims:/Users/michael/.pyenv/shims:/Users/michael/.pyenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/michael/.rvm/bin:/usr/local/bin:/Users/michael/.rvm/rubies/ruby-2.2.4/bin:~/.rvm/rubies/ruby-2.2.4/lib:/Users/michael/.rvm/rubies/ruby-2.2.4/bin:/Users/michael/.rvm/gems/ruby-2.2.4/bin/

[EnvInject] - Variables injected successfully.
[JenKins] $ /bin/sh -xe /var/folders/4m/jprvhgpx22l6grbzc8k8n1_80000gn/T/hudson2224660881844232806.sh
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ export LANGUAGE=en_US.UTF-8
+ LANGUAGE=en_US.UTF-8
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ cd /Users/michael/Desktop/JenKins
+ fastlane env --capture_output
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 20 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /Users/michael/.rvm/rubies/ruby-2.2.4/bin/fastlane:22:in `<main>'
	from /Users/michael/.rvm/rubies/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michael/.rvm/rubies/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.4 (Apple Git-73)            |
| Installation Source         | ~/.rvm/rubies/ruby-2.2.4/bin/fastlane       |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2i  22 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.61.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday                   | 0.13.1       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.12.2       |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
</details>

*generated on:* **2017-10-12**
</details>

**Comment by taquitos** [comment]
Maybe I don't understand RVM well enough, but it looks like Jenkins is still trying to use parts of system ruby here: `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb`
which would explain why it can't find _fastlane_, since it's installed: `~/.rvm/rubies/ruby-2.2.4/bin/fastlane`

**Comment by artetinho** [comment]
Unfortunately, I came across the issue. Is there any update on this or any suggestion for workaround?

**Comment by artetinho** [comment]
I still can not run the fastlane gym command build in Jenkins job even though is able to do it in slave machine.

```
+ which fastlane
/usr/local/bin/fastlane
+ /usr/local/bin/fastlane env
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 22 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by shuijinliuxi** [comment]
@artetinho 
I add the `Inject environment variables to the build process` in Jenkin, and set the path of rvm in 
 the Properties Content:

```
PATH=$PATH:/usr/local/bin:~/.rvm/bin/rvm
```
