### ISSUE TITLE
[HowTo] Avoid keychain prompt to allow access to the private key

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#10589]
### Issue Description

When using match + gym for the first time the system will ask for authorisation to use the Certificate.
https://i.imgur.com/7oPSD4H.jpg

It is problematic on our CI servers with many slaves and for which developers do not have GUI access.

### Tried but failed

I tried using a temp keychain to store match stuff but I still got the prompt , did you guys found a way to do that?

Fastfile extract
```ruby
  delete_keychain(name: "fastlane_keychain") if File.exist?(File.expand_path("~/Library/Keychains/fastlane_keychain-db"))
  create_keychain(
      name: 'fastlane_keychain',
      password: 'temppassword',
      unlock: true,
      timeout: false
    )
  match(
  ...
    keychain_name: 'fastlane_keychain'
    )
  gym(...)
  delete_keychain(name: 'fastlane_keychain')
```

Nicolas

**Comment by WilliamIzzo83** [comment]
I've got the same problem, this breaks up thing the first time on our building server. Does anyone have a solution?

**Comment by ohayon** [comment]
Hey everyone. I believe you should be able to fix this by using these two options: 

```
FastlaneCore::ConfigItem.new(key: :lock_when_sleeps,
                                       description: 'Lock keychain when the system sleeps',
                                       is_string: false,
                                       default_value: false),
FastlaneCore::ConfigItem.new(key: :lock_after_timeout,
                                       description: 'Lock keychain after timeout interval',
                                       is_string: false,
                                       default_value: false),
```

Let us know if that works for you! 🚀

**Comment by MSavisko** [comment]
@nicolasbraun 
I have the same problem.

Not working for me:
1. Unlock keychain
2. set-key-partition-list for all items in keychain

@ohayon 
changing the state of lock_when_sleeps and lock_after_timeout do not relate to @nicolasbraun question and not helped me.

Any other real suggestion?

**Comment by ohayon** [comment]
Hey @MSavisko, apologies that that wasnt working for you, that solution has helped others in the past and even my own configuration on a personal project 😄 . Could you provide a bit more context for the issue youre having? It would be helpful to see the output of your command when it is failing and the method by which you are calling fastlane. Are you using a Fastfile?

**Comment by nicolasbraun** [comment]
Hi @ohayon  @MSavisko 

Sorry crazy weeks! Took a while to look.
I realised the keychain created in not called `fastlane_keychain` but `fastlane_keychain-db`. 
Changed that in the match options and running some tests, will let you know how it goes.

**Comment by Felipe-Banno** [comment]
Im having the same problems. I tried several variations of "fastlane_keychain" and fastlane_keychain-db" without success.

@nicolasbraun Did you fix the issue? If yes, could you please share you solution?

**Comment by VincentCATILLON** [comment]
If anyone has a solution about it, it will helps.
Trying to implement https://github.com/fastlane/fastlane/issues/10651

**Comment by nicolasbraun** [comment]
Hi sorry for the long time to answer.

First note that adding `-db`as stated in my previous comment does not change anything anymore as this has been fixed now https://github.com/fastlane/fastlane/blob/5019acb53fc2adf050b4227c3e3216e365ba36ec/fastlane_core/lib/fastlane_core/helper.rb#L199

I am having a really hard time debugging this. I have inconsistent results on the several slaves I have on my Jenkins and cannot figure a pattern. So I tried on a new slave machine.

* The keychain is properly created, unlocked.
* The certificate is imported in the keychain
![screen shot 2017-12-14 at 16 18 44](https://user-images.githubusercontent.com/1089363/34001376-1ae6056c-e0f0-11e7-9eed-a663f9bc120d.png)
* Access to the private key are open for `codesign`  and `security`
![screen shot 2017-12-14 at 17 01 04](https://user-images.githubusercontent.com/1089363/34001487-6b667d64-e0f0-11e7-97d6-f49c89baf4dd.png)
* *First Run* Weirdly the prompt asks for the login keychain password (keychain that is empty, and unlocked
<img width="670" alt="screen shot 2017-12-14 at 17 23 39" src="https://user-images.githubusercontent.com/1089363/34002707-9dd6524e-e0f3-11e7-803f-9cdd93f93863.png">

* Even more weird if I enter it and Always allows the build goes on
* On the next runs weirdly it asks for the correct keychain (and access control is not he same)
![screen shot 2017-12-14 at 18 14 44 3](https://user-images.githubusercontent.com/1089363/34007376-ddba32e6-e101-11e7-89cf-bb0760faac3f.png)

The codesign command uses `usr/bin/codesign` which is the one autorized in the screenshot.
It is specificaly authorized to avoid this promp 
https://github.com/fastlane/fastlane/blob/70cf925ac575c903dcf1eda973746f9f181f7b9d/fastlane_core/lib/fastlane_core/keychain_importer.rb#L8

Driving me nuts :)


Also i do not seem to have the issue locally (but only have one setup to test against) so it might be Jenkins related but i do not see how. The user launching the script is the one I am logged with for the screenshots.

I am not familiar with how xcodebuild choose in which keychain to look for the signing certificate. I see that gym does not pass any path/name of keychain maybe we should had the option ? @ohayon do you have any input on that maybe?

Still i don't get why i have a prompt even though my keychain is unlocked.

Something I forgot to mention is that the prompts happens during the
` '[CP] Embed Pods Frameworks'` build phase.

Here are my last lines of logs

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/IntermediateBuildFilesPath/Primitive_iOS.build/Production-iphoneos/Primitive_iOS.build/Script-BDD5F3E9C530D463D230A81C.sh
    cd /Users/slave/Jenkins/workspace/Shaper_iOS
    /bin/sh -c /Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/IntermediateBuildFilesPath/Primitive_iOS.build/Production-iphoneos/Primitive_iOS.build/Script-BDD5F3E9C530D463D230A81C.sh
mkdir -p /Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/BuildProductsPath/Production-iphoneos/Primitive_iOS.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ADDynamicLogLevel.framework" "/Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/InstallationBuildProductsLocation/Applications//Primitive_iOS.app/Frameworks"
building file list ... done
ADDynamicLogLevel.framework/
ADDynamicLogLevel.framework/ADDynamicLogLevel
ADDynamicLogLevel.framework/Info.plist

sent 313437 bytes  received 70 bytes  627014.00 bytes/sec
total size is 313147  speedup is 1.00
Code Signing /Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/InstallationBuildProductsLocation/Applications//Primitive_iOS.app/Frameworks/ADDynamicLogLevel.framework with Identity iPhone Distribution: APPLIDIUM (LL36D6ZV57)
/usr/bin/codesign --force --sign D398B53754539ED9657EB33B19B8F1C153D3AA96  --preserve-metadata=identifier,entitlements '/Users/slave/Library/Developer/Xcode/DerivedData/Primitive_iOS-fmpstfyalbxbsparvoduprhyhnxj/Build/Intermediates.noindex/ArchiveIntermediates/Primitive_iOS/InstallationBuildProductsLocation/Applications//Primitive_iOS.app/Frameworks/ADDynamicLogLevel.framework'
```

Nicolas

**Comment by MSavisko** [comment]
Perhaps on no free time and "Allways allow" workaround, I will check that bug is actual later.

**Comment by saitjr** [comment]
I just resolve this problem last week.

`security set-key-partition-list -S apple-tool:,apple: -s -k $PASS ~/Library/Keychains/login.keychain-db`

**Comment by nicolasbraun** [comment]
Awesome can you explain a bit what this does?

**Comment by jgavris** [comment]
FWIW I haven't seen the codesign dialog using the following

```ruby
def ensure_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  create_keychain(
    name: name,
    password: 'temppassword',
    unlock: true,
    timeout: false
  )
end

...

ensure_temp_keychain 'fastlane_enterprise'
match(
  type: 'enterprise',
  git_branch: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
  readonly: true,
  keychain_name: 'fastlane_enterprise'
)
```

**Comment by saitjr** [comment]
@jgavris Should delete keychain before running match ?

**Comment by jgavris** [comment]
@saitjr  `ensure_temp_keychain` always deletes it first, then creates it. It's just making sure it's 'really temporary'.

**Comment by saitjr** [comment]
Seems the solution of stuck.

**Comment by nicolasbraun** [comment]
Thanks for your help, I made a test run and it seems to work with @jgavris solution 🚀 
I will test it soon on a  fresh new machine
