### ISSUE TITLE
Guys need help fastlane 

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#10581]
Hello all. Need help, tell me please how I can write password for match deliver pem and etc from Fastfile without keychain?

**Comment by taquitos** [comment]
Hey @GandjaFuzz could you describe the setup you're using and what you're trying to accomplish?
In most cases, you should be able to create a temporary keychain: https://docs.fastlane.tools/actions/create_keychain/

**Comment by GandjaFuzz** [comment]
I receive from server login and password for release apps. and me need in cycle setup login and pass for fast lane.

**Comment by GandjaFuzz** [comment]
if I create keychain how I can automatic programmatically add in keychain login with password for fast lane delivery etc
