### ISSUE TITLE
Is there a way to upload what's new on a per-language basis?

### ISSUE THREAD

**Issue by ndyck14** [fastlane/fastlane#10594]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Right now it appears you can only upload a single paragraph for all translations found (set_changelog). Can there be an option to specify per-translation?

**Comment by KrauseFx** [comment]
Yeah, you can use deliver for that, using the `release_notes` value I think, so you can either include that in your `Fastfile`, or using local `txt` files after running `fastlane deliver init` 👎

**Comment by ndyck14** [comment]
Ahh, yes, it looks like that is supported through deliver. It might be worth adding a note on the action set_changelog that you can support multi languages using the metadata approach in deliver.

https://docs.fastlane.tools/actions/set_changelog/#set_changelog

Also it might be worth adding a bit more detail to https://docs.fastlane.tools/getting-started/ios/appstore-deployment/#submitting-your-app. I presume that making changes to the meta data in the repo would be uploaded, although this section doesnt make explicit reference that that's the case.
