### ISSUE TITLE
[Feature-request] add extesnion to all config files in `fastlane` folder

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#1059]
[Feature-request] add `.rb` extension to all files in `faslane` folder in order to support correct syntax highlighting by default.

Now I'm using workaround like this:

    ln -s ./Gymfile ./Gymfile.rb

Another way: to not confuse users with ruby extension - make your own like `Gymfile.fastlane` then everybody can manually setup desired syntax files in favorite text editor.

**Comment by KrauseFx** [comment]
Following the standard pattern, we decided to have it like this, e.g. `Makefile`, `Rakefile`, `Podfile`, `Gemfile`, etc.
