### ISSUE TITLE
Shell Command Not working through Fastfile

### ISSUE THREAD

**Issue by giribabur** [fastlane/fastlane#10606]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to copy file from one folder to another folder using shell commands but we couldn't able to do this operation. Below is the command which we are trying it out. Could you please help me whether I am doing something wrong here.

[INSERT OUTPUT HERE]
sh("cp Sample\ Source\ Directory/Sub\ Directory/GoogleService-Info.plist Sample\ Destination\ Directory")

[INSERT OUTPUT HERE]

[11:59:53]: Exit status of command 'cp ./FireBase\ Config\ Files/Educational\ Networks\ Mobile/GoogleService-Info.plist ./Educational\ Networks\ Mobile' was 1 instead of 0.
cp: ./FireBase Config Files/Educational Networks Mobile/GoogleService-Info.plist: No such file or directory

Thanks,
Giribabu R

**Comment by PetrosIchor** [comment]
Sh in fastlane uses the fastlane/ folder as root.  Change to `cd ../Sample`

**Comment by evfemist** [comment]
yea, in fastlane every action used root folder except `sh` action. I believe this is something that should be fixed. Here is my thoughts:
Pros:
- consistency
- less errors in scripts like `sh "do_something_and_put_to #{ENV['GYM_OUTPUT_DIRECTORY']}"`
- no need to use `cd .. && ` to run from root folder

Cons:
- need to update existing code
- longer line for scripts located in `fastlane` dir
