### ISSUE TITLE
Why it automatically changing my app store's version number?

### ISSUE THREAD

**Issue by jacobjiangwei** [fastlane/fastlane#10605]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I keep asking for this obvious bug.
I was using jenkins job automate can upload tons of build to iTunesConnect while I can manage/decide which version to submit and review.

Here is the situation:

I have 2 version in dev, one is 4.7.0 another is 4.8.0,

After I submit 4.7.0 into waiting for review status, as long as 4.8.0 job triggered and upload to TF build, the 4.7.0 waiting for review changes to 4.8.0 waiting for review in iTunesConnect page, which the build I submit is still 4.7.0

Even apple reviewed passed, the app store page still showing 4.8.0 while build is actually 4.8.0.

How to avoid this happen if all app store jobs using fastlane?

Thanks

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

 fastlane env
[13:02:34]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:02:37]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.61.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.6       |
| json                      | 2.0.2        |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-10-16**
</details>

**Comment by jacobjiangwei** [comment]
12:01:28 INFO [2017-10-16 12:01:28.77]: Making sure the latest version on iTunes Connect matches '4.8.0' from the ipa file...
12:01:45 ITC.apps.devReject.message.and.link.waitingForReview.canReject
12:01:45 INFO [2017-10-16 12:01:45.81]: [32mSuccessfully set the version to '4.8.0'[0m
12:01:49 INFO [2017-10-16 12:01:49.49]: Uploading binary to iTunes Connect
12:01:50 INFO [2017-10-16 12:01:50.41]: [32mWrote XML data to '/tmp/715886894.itmsp'[0m
12:01:50 INFO [2017-10-16 12:01:50.44]: Going to upload updated app to iTunes Connect
12:01:50 INFO [2017-10-16 12:01:50.44]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
12:01:50 DEBUG [2017-10-16 12:01:50.51]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar -m upload -u jacob.jiang@ringcentral.com -p YourPassword -f /tmp/715886894.itmsp -t Signiant -k 100000 2>&1
12:01:53 DEBUG [2017-10-16 12:01:53.10]: [Transporter]: INFO: Transporter is searching for updated software components.
12:01:56 DEBUG [2017-10-16 12:01:56.96]: [Transporter]: INFO: No updates found.
12:01:57 DEBUG [2017-10-16 12:01:57.11]: [Transporter]: INFO: Logging configured successfully.
12:01:57 DEBUG [2017-10-16 12:01:57.11]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
12:01:57 DEBUG [2017-10-16 12:01:57.30]: [Transporter]: DEBUG: Configuration refresh successful.
12:01:57 DEBUG [2017-10-16 12:01:57.30]: [Transporter]: DEBUG: Saving configuration to local path: /Users/jacob/.itmstransporter/Defaults.properties
12:01:57 DEBUG [2017-10-16 12:01:57.30]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.3]
12:01:57 DEBUG [2017-10-16 12:01:57.31]: [Transporter]: INFO: OS identifier: Mac OS X 10.12.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
12:01:57 DEBUG [2017-10-16 12:01:57.31]: [Transporter]: INFO: Memory: [JVM] 868M free, 981M total, 981M max [System] (Physical) 3161M free, 16384M total (Swap) 1641M free, 2048M total
12:01:57 DEBUG [2017-10-16 12:01:57.31]: [Transporter]: INFO: Upload mode selected.
12:01:57 DEBUG [2017-10-16 12:01:57.32]: [Transporter]: INFO: Examining the package at: /tmp/715886894.itmsp
12:01:57 DEBUG [2017-10-16 12:01:57.32]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
12:01:57 DEBUG [2017-10-16 12:01:57.32]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
12:01:57 DEBUG [2017-10-16 12:01:57.32]: [Transporter]: INFO: Gathering the list of valid files from the package ...
12:01:57 DEBUG [2017-10-16 12:01:57.32]: [Transporter]: DEBUG:   69a68113567c023d80ac437fae427ca3.ipa will be verified by Apple's web service to determine if it is a valid file.
12:01:57 DEBUG [2017-10-16 12:01:57.32]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
12:01:57 DEBUG [2017-10-16 12:01:57.33]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
12:01:57 DEBUG [2017-10-16 12:01:57.33]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
12:01:57 DEBUG [2017-10-16 12:01:57.36]: [Transporter]: INFO: Performing authentication of package 715886894.itmsp ...
12:01:57 DEBUG [2017-10-16 12:01:57.36]: [Transporter]: DBG-X: Memory: [JVM] 858M free, 981M total, 981M max [System] (Physical) 3147M free, 16384M total (Swap) 1641M free, 2048M total
12:01:57 DEBUG [2017-10-16 12:01:57.36]: [Transporter]: DBG-X: Memory: [JVM] 858M free, 981M total, 981M max [System] (Physical) 3147M free, 16384M total (Swap) 1641M free, 2048M total
12:01:57 DEBUG [2017-10-16 12:01:57.36]: [Transporter]: DBG-X: Using operation named: authenticateForSession
12:01:57 DEBUG [2017-10-16 12:01:57.37]: [Transporter]: DBG-X: Apple's web service operation input parameters:
12:01:57 DEBUG [2017-10-16 12:01:57.37]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
12:01:57 DEBUG [2017-10-16 12:01:57.37]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter Password = **hidden value**
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2017-10-16T12:01:57+08:00
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.397732318
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jacob.jiang@ringcentral.com -p **hidden value** -f /tmp/715886894.itmsp -t Signiant -k 100000
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter Username = jacob.jiang@ringcentral.com
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter Version = 1.9.3
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
12:01:57 DEBUG [2017-10-16 12:01:57.38]: [Transporter]: INFO: id = 20171016120157-611

**Comment by janpio** [comment]
You didn't tell us what tool or action you are actually talking about.

If you are talking about `deliver`, then this exists:
skip_app_version_update | Don't update app version for submission

**Comment by jacobjiangwei** [comment]
great! That solves my problems. Thanks!

发自我的 iPhone

**Comment by janpio** [comment]
Awesome. Have fun!
