### ISSUE TITLE
Functionality request for google_play_track_version_codes: Get lastest build number

### ISSUE THREAD

**Issue by hinews** [fastlane/fastlane#10602]
Hi, 

I'm using google_play_track_version_codes to get the lastest build number in Google Play to upload the new apk file and resolve this error from 

> Google Api Error: apkUpgradeVersionConflict: APK specifies a version code that has already been used

by this code 
`lane :get_lastest_build_number do
    alpha_build_number =   google_play_track_version_codes(track: "alpha")
    beta_build_number  =   google_play_track_version_codes(track: "beta")
    prod_build_number  =   google_play_track_version_codes(track: "production")
    roll_build_number  =   google_play_track_version_codes(track: "rollout")
    max_build_number   =   [alpha_build_number, beta_build_number, prod_build_number, roll_build_number].max
    open(ENV["BUILD_NUMBER_FILE"], 'w') do |f|
      f << max_build_number[0] + 1
    end
  end         `

It has the main problem: if in some track 'alpha' or 'beta' uploaded apk file and then the track was disabled - google_play_track_version_codes cannot get it's build number and the snippet above doesn't work. 

Could you extend and provide functionality to get the lastest build number of apk file from Artifact Library Place in Google Play Console and feature to write the lastest build number to file, it's needed for Unity projects that use internal build system instead of gradle?

**Comment by hinews** [comment]
The command for ios, is there analog for android?
`increment_build_number(
      build_number: latest_testflight_build_number + 1
    )`

**Comment by JesseScott** [comment]
You can use this plugin:
https://github.com/Jems22/fastlane-plugin-increment_version_code
