### ISSUE TITLE
Found multiple versions of Xcode in '/Applications/'

### ISSUE THREAD

**Issue by SupreeSeekSter** [fastlane/fastlane#10616]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I run fastlane on my local machine without any problem but there is this error while running on the Circleci.

This is my yml file
machine:
  xcode:
    version: 9.0
  environment:
    XCODE_SCHEME: "xxx xxx"
    XCODE_WORKSPACE: "xxx.xcworkspace"
    GYM_CODE_SIGNING_IDENTITY: "xxx"
    GYM_CODE_SIGNING_IDENTITY: "xxx"
    GYM_CODE_SIGNING_IDENTITY: "xxx"
dependencies:
  cache_directories:
    - 'Pods'
    - '~/.cocoapods'
  override:
    # - sudo gem 'cocoapods'
    - sudo gem install cocoapods
    - sudo gem install fastlane
    - brew upgrade carthage
    # - pod repo update
    - pod install:
  cache_directories:
    - "~/.cocoapods"
test:
  override:
    - echo “Deploy staging”
deployment:
  develop_distribution:
    branch: develop
    commands:
      - fastlane beta

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
** ARCHIVE FAILED **
The following build commands failed:
Check dependencies
(1 failure)
[02:27:13]: Exit status: 65
[02:27:13]: 
[02:27:13]: Maybe the error shown is caused by using the wrong version of Xcode
[02:27:13]: Found multiple versions of Xcode in '/Applications/'
[02:27:13]: Make sure you selected the right version for your project
[02:27:13]: This build process was executed using '/Applications/Xcode-9.app'
[02:27:13]: If you want to update your Xcode path, either
[02:27:13]: 
[02:27:13]: - Specify the Xcode version in your Fastfile
[02:27:13]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[02:27:13]: 
[02:27:13]: - Specify an absolute path to your Xcode installation in your Fastfile
[02:27:13]: ▸ xcode_select "/Applications/Xcode8.app"
[02:27:13]: 
[02:27:13]: - Manually update the path using
[02:27:13]: ▸ sudo xcode-select -s /Applications/Xcode.app
[02:27:13]: 
+---------------+---------------------------+
|             Build environment             |
+---------------+---------------------------+
| xcode_path    | /Applications/Xcode-9.app |
| gym_version   | 2.61.0                    |
| export_method | development               |
| sdk           | iPhoneOS11.0.sdk          |
+---------------+---------------------------+
[02:27:13]: ▸ === BUILD TARGET Bolts OF PROJECT Pods WITH CONFIGURATION Release ===
[02:27:13]: ▸ Check dependencies
[02:27:13]: ▸ Code Signing Error: Bolts does not support provisioning profiles. Bolts does not support provisioning profiles, but provisioning profile NO_SIGNING/ has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
[02:27:13]: 
[02:27:13]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[02:27:13]: 📋  For the complete and more detailed error log, check the full log at:
[02:27:13]: 📋  /tmp/circle-artifacts.kvFugD1/gym/Seeker Staging-Seeker Staging.log
[02:27:13]: 
[02:27:13]: Your `export_method` in gym is defined as `development`
[02:27:13]: which might cause problems when signing your application
[02:27:13]: Are you sure want to build and export for development?
[02:27:13]: Please make sure to define the correct export methods when calling
[02:27:13]: gym in your Fastfile or from the command line
[02:27:13]: 
[02:27:13]: 
[02:27:13]: Looks like fastlane ran into a build/archive error with your project
[02:27:13]: It's hard to tell what's causing the error, so we wrote some guides on how
[02:27:13]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[02:27:13]: Before submitting an issue on GitHub, please follow the guide above and make
[02:27:13]: sure your project is set up correctly.
[02:27:13]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[02:27:13]: the full commands printed out in yellow in the above log.
[02:27:13]: Make sure to inspect the output above, as usually you'll find more error information there
[02:27:13]: 
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[02:27:13]: Error building the application - see the log above
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 14          |
| 4    | carthage                            | 84          |
| 5    | register_devices                    | 2           |
| 6    | automatic_code_signing              | 0           |
| 7    | automatic_code_signing              | 0           |
| 💥   | gym                                 | 16          |
+------+-------------------------------------+-------------+
[02:27:13]: fastlane finished with errors
[!] Error building the application - see the log above
fastlane beta returned exit code 1
Action failed: fastlane beta

### Stack
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |
### System Locale
| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |
### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>
```ruby
fastlane_version "2.61.0"
default_platform :ios
platform :ios do
  before_all do
    cocoapods
    carthage
    # ENV['KEYCHAIN_NAME'] = "TempKeychain.keychain"
  end
  desc "Runs all the tests"
  lane :test do
    scan
  end
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :enterprise do
  end
  desc "Build and submit the app on Crashlytics Beta"
    lane :beta do
      register_devices(
          devices_file: './fastlane/Devices.txt'
        )
      disable_automatic_code_signing(path: "xxx.xcodeproj")
      gym(
        workspace: "xxx.xcworkspace",
        scheme: "xxx xxx",
        silent: true,
        clean: true,
        export_method: "development",
        output_directory: "../",
        output_name: "xxx xxx.ipa",
        export_method: "development"
      )
      enable_automatic_code_signing(path: "xxx.xcodeproj")
    crashlytics(
      api_token: "xxx",
      build_secret: "xxx",
      ipa_path: "/Users/attapong/Documents/Work/xxx/xxx/xxx xxx.ipa",
      notes_path: "./fastlane/crashlytics/notes.txt",
      notifications: true # Should this distribution notify your testers via email?
    )
  end
  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "xxx") # Build your app - more options available
    deliver(force: true)
  end
  after_all do |lane|
  end
  error do |lane, exception|
  end
end
```
</details>
<details><summary>`./fastlane/Appfile`</summary>
```ruby
app_identifier "xxx" # The bundle identifier of your app
apple_id "xxx@xxx.com" # Your Apple email address
team_id "xxx" # Developer Portal Team ID
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.61.0  | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
</details>

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by qmskills** [comment]
I have the same problem please help!

**Comment by tspecht** [comment]
Any idea?
