### ISSUE TITLE
 Could not find action, lane or variable 'sign_apk'

### ISSUE THREAD

**Issue by ZalakSA** [fastlane/fastlane#10617]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Could not find action, lane or variable 'sign_apk'. Check out the documentation for more details: https://docs.fastlane.tools/actions

FASTLANE ends with error 

My fast file code is like below:-

```
 lane :prod_release do |options|
    gradle(
      task: "cdvBuildRelease",
      project_dir: project_path
    )
    sign_apk(
      keystore_path: "profiles/faithplay.keystore",
      alias: "faithplay",
      storepass: "faithplayRd9U74",
      tsa: "http://timestamp.comodoca.com/rfc316"
    )
    zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")
    end
```

Please help me to resolve above issue. I am creating build using grunt and Fastlane with ionic
Platform versions are:- Installed platforms:
  android 6.2.3
  ios 4.3.1
  ionic 3.12.0
  cordova 7.1.0

**Comment by mpirri** [comment]
@ZalakSA `sign_apk` is not an officially-supported part of fastlane, but you can try to follow the instructions here to get set up with it: https://github.com/appfoundry/fastlane-android-example/

I hope this is helpful! 🚀
