### ISSUE TITLE
Net::ReadTimeout after successful Hockey upload

### ISSUE THREAD

**Issue by maxmeyers** [fastlane/fastlane#10624]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Starting on October 6th, our nightly build started failing with the following error during the `hockey` phase:

```
INFO [2017-10-17 11:41:58.48]: --------------------
INFO [2017-10-17 11:41:58.48]: --- Step: hockey ---
INFO [2017-10-17 11:41:58.48]: --------------------
INFO [2017-10-17 11:41:58.48]: Starting with file(s) upload to HockeyApp... this could take some time.
WARN [2017-10-17 11:43:03.83]: Lane Context:
INFO [2017-10-17 11:43:03.83]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios nightly", :BUILD_NUMBER=>"760", :IPA_OUTPUT_PATH=>"/Users/jenkins/.jenkins/jobs/GrizzlyiOS-Nightly/workspace/IFTTT.ipa", :DSYM_OUTPUT_PATH=>"/Users/jenkins/.jenkins/jobs/GrizzlyiOS-Nightly/workspace/IFTTT.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/jenkins/Library/Developer/Xcode/Archives/2017-10-17/IFTTT 2017-10-17 11.30.19.xcarchive", :FL_CHANGELOG=>"[redacted]"}
ERROR [2017-10-17 11:43:03.83]: Net::ReadTimeout
```

However, the upload is successful and the build is downloadable from Hockey. But the error causes the whole build to fail, which prevents following actions from occurring.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                              |
| --------------------------- | ---------------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                            |
| Ruby                        | 2.0.0                                                                              |
| Bundler?                    | true                                                                               |
| Git                         | git version 2.13.5 (Apple Git-94)                                                  |
| Installation Source         | ~/.jenkins/jobs/GrizzlyiOS-Nightly/workspace/vendor/bundle/ruby/2.0.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib                     |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                                        |
| Is contained                | false                                                                              |
| Is homebrew                 | false                                                                              |
| Is installed via Fabric.app | false                                                                              |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                        |
| Xcode Version               | 9.0                                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.15.4       |
| rake                      | 12.1.0       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 1.8.6        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| sqlite3                   | 1.3.13       |
</details>

*generated on:* **2017-10-17**
</details>

**Comment by mpirri** [comment]
Interesting error, @maxmeyers . If you manually set a timeout via `timeout` (in seconds) -- maybe set something huge like 3000 seconds? -- do you still see this error? I wonder if maybe the default timeout being used is too short for your application?

Thanks for writing in!  🚀

**Comment by maxmeyers** [comment]
Thanks for the suggestion. I see that a timeout option was added to the Hockey action recently.

I'm now getting the below error. Interestingly, it's taking the same amount of time to occur, 65 seconds.

```[14:24:01]: Error when trying to upload file(s) to HockeyApp: 504 - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: -Tp_RMrKyVzIPg7GBtk6fw6IGDIpA3a_-hK1GMAsvy_JtenXfsbyzw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by mpirri** [comment]
@maxmeyers have a look at [this GitHub issue](https://github.com/fastlane/fastlane/issues/6101) - specifically the very last comment - maybe the `bypass_cdn` option will help you?

Thanks!  🚀

**Comment by maxmeyers** [comment]
Great, that fixed my problem. Thanks for your help.
