### ISSUE TITLE
Using match with app store and enterprise account when App ID / Bundle ID remains the same

### ISSUE THREAD

**Issue by sharkusmarkus** [fastlane/fastlane#10622]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.57.0       |
| openssl                   | 2.0.2        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| bundler                   | 1.15.1       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>

*generated on:* **2017-10-17**
</details>

### Issue Description
Let us say that I have access to an app store developer account, through which apps are published to the app store. I also access to an enterprise account, through which apps are distributed internally.

Let us say I have an app with an App ID / Bundle ID of com.myapp.myapp. This is setup in the app store account. 

I would also want to distribute the app, via the enterprise account using the same App ID / Bundle ID. I know that I cannot create the App ID on the enterprise account as it's unique, and already exists on the app store account. However, I can create a wildcard App ID, and that can be used to generate a provisioning profile and code sign the app without changing the bundle ID.

So what's the problem? Well, I'd quite like to use Match, but it seems that I likely won't be able to do this, as one of the first things I'd need to do after setting up the repo, is to specify an app id for the enterprise setup, and, as I've found with sigh, it's going to fail as it won't be able to find or create the app id on the enterprise account, as it exists in the app store account.

Does anyone have any ideas of how one could get match to work with the setup above, or is it simply the case I'd need to create new App ID's in the enterprise account?

As to why I've not done that already, I believe that there are third party items that are configured with the bundle ID, and it may not be easily possible to add additional bundle ID's to those items.

**Comment by mpirri** [comment]
@sharkusmarkus Unfortunately, I think it will be difficult to get `match` to support this configuration. Using a wildcard app id to allow an app store and enterprise build with the same bundle identifier isn't really recommended by Apple and unfortunately it breaks a lot of the assumptions made by `match`. Your best bet is probably creating new App IDs for the enterprise account.  Sorry I don't have better news!

**Comment by sharkusmarkus** [comment]
Thanks for the reply. I thought I would ask, but did presume that it'd be the case that new ID's would be needed, which should be ok :)
