### ISSUE TITLE
[Regression] Error accessing file after upgrading to 2.62

### ISSUE THREAD

**Issue by Jun711** [fastlane/fastlane#10623]
### New Issue Checklist

- [X] Updated fastlane to the latest version

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[[11:16:41]: Error accessing file, this might be due to fastlane's directory handling
[11:16:41]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details]

**Comment by Jun711** [comment]
It works after I downgraded to fastlane 2.60.0

**Comment by ohayon** [comment]
Hey @Jun711 - would you mind sharing the complete stack trace? You may need to run with `--verbose`. Thanks! 🚀

**Comment by Jun711** [comment]
yea, sure. What about this?

`fastlane --verbose       
[16:48:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-10-17 16:48:28.28]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/Jun/Documents/project1/fastlane/Appfile'
- app_identifier: ''
- apple_id: ''
- team_id: ''
-------

WARN [2017-10-17 16:48:28.68]: Error accessing file, this might be due to fastlane's directory handling
WARN [2017-10-17 16:48:28.68]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:194:in ``': No such file or directory - SW_VERS (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:194:in `operating_system_version'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:71:in `action_launched'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
`

**Comment by datacosmos** [comment]
Hi, 
fasltane 2.62 seems not to be usable under Mac OS (even fastlane env does not work)
it seems that there is a bug in .fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:
sw_vers was in capital letters (SW_VERS) and this mac os command cannot be found, in lower case everything works. 
This code works:
```
190     def operating_system_version
191       os = self.operating_system
192       case os
193       when "macOS"
194         return `**sw_vers** -productVersion`.strip
195       else
196         # Need to test in Windows and Linux... not sure this is enough
197         return Gem::Platform.local.version
198       end
```
HTH,
Martin

**Comment by Jun711** [comment]
@datacosmos Hi, is your mac file system case-sensitive?

**Comment by datacosmos** [comment]
yes - naturally ;)

**Comment by mpirri** [comment]
@Jun711 @datacosmos We have a fix for this that will be shipping in the next version of `fastlane` (maybe tomorrow?).  The change is in PR #10625

Thanks so much for writing in about this.  🚀

**Comment by Jun711** [comment]
it works now
