### ISSUE TITLE
Feature request for hockey

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#1063]
Is there an option to add a %age progress so one can observe the uploading to hockeyapp?

**Comment by ohwutup** [comment]
Hey @nmayafit thanks for the great suggestion. We would definitely be open to merging in a PR with this change, its always great to see feedback about uploads/downloads. Feel free to submit a PR!

**Comment by nmayafit** [comment]
(-:
Don't have the knowledge for developing this. Just suggested for a new feature.
Maybe someone can help here with the dev part.
