### ISSUE TITLE
[Deliver] ["ITC.apps.idfa.errorMessage.agreeoptout"] missing in additional review options?

### ISSUE THREAD

**Issue by minuscorp** [fastlane/fastlane#10632]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using Deliver to upload and submitting into review a build which uses IDFA identifier, it fails with
**Something wrong with your Ad ID information: ["ITC.apps.idfa.errorMessage.agreeoptout"].** because in the formulary is required to fill the agreement as a developer (a checkbox).

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
    [09:18:40]: Selecting build 1.1.7 (232.171018)...
    [09:18:42]: Successfully selected build
    [09:18:42]: Submitting the app for review...
    [09:19:09]: Setting 'add_id_info_tracks_install' to 'true'...
    [09:19:09]: Setting 'export_compliance_uses_encryption' to 'false'...
    [09:19:09]: Setting 'export_compliance_encryption_updated' to 'false'...
    [09:19:09]: Setting 'add_id_info_uses_idfa' to 'true'...
    [09:19:13]: Sending crash report...
    [09:19:13]: The stack trace is sanitized so no personal information is sent.
    [09:19:13]: To see what we are sending, look here: /Users/buddybuild/.fastlane/latest_crash.json
    [09:19:13]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
    [09:19:13]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
    +------------------+----------------+
    |           Lane Context            |
    +------------------+----------------+
    | DEFAULT_PLATFORM | ios            |
    | PLATFORM_NAME    | ios            |
    | LANE_NAME        | ios buddybuild |
    +------------------+----------------+
    [09:19:13]: Something wrong with your Ad ID information: ["ITC.apps.idfa.errorMessage.agreeoptout"].
    [09:19:13]: Sending Crash/Success information. Learn more at https://github.com/fastlane/fastlane#metrics
    [09:19:13]: No personal/sensitive data is sent. Only sharing the following:
    [09:19:13]: {:update_fastlane=>1, :fastlane_version=>1, :default_platform=>1, :last_git_commit=>1, :deliver=>1}
    [09:19:13]: deliver
    [09:19:13]: This information is used to fix failing actions and improve integrations that are often used.
    [09:19:13]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
    +------+---------------------+-------------+
    |             fastlane summary             |
    +------+---------------------+-------------+
    | Step | Action              | Time (in s) |
    +------+---------------------+-------------+
    | 1    | update_fastlane     | 0           |
    | 2    | Verifying required  | 0           |
    |      | fastlane version    |             |
    | 3    | default_platform    | 0           |
    | 4    | last_git_commit     | 0           |
    | 💥   | deliver             | 1572        |
    +------+---------------------+-------------+
    [09:19:13]: fastlane finished with errors
    Looking for related GitHub issues on fastlane/fastlane...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/fastlane/fastlane/issues/new
    Run `fastlane env` to append the fastlane environment to your issue
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.13                                         |
| Ruby                        | 2.0.0                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.14.1                            |
| Installation Source         | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane      |
| Host                        | Mac OS X 10.13 (17A365)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.0.0-p648/lib             |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                     |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode-9.app/Contents/Developer/ |
| Xcode Version               | 9.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"

default_platform :ios

platform :ios do
  before_all do
    ENV["GITHUB_TOKEN"] = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    #cocoapods
    #carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Ebikemotion Dealer") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store, use deploy: 'TEST|RELEASE' in order to further actions."
  lane :release do |options|
    if ["TEST","RELEASE"].include? options[:deploy] 
      begin
        ensure_git_status_clean
      rescue => ex
        UI.important(ex.message)
        UI.important("Commiting changes before releasing...")
        branch = git_branch
        git_commit(
          path: ".",
          message: "[ci skip] See commit changes for info"
        )
        push_to_git_remote(
          remote: "origin",
          local_branch: branch,
          remote_branch: branch
        )
      end
      branch = git_branch
      if options[:deploy] == "RELEASE"
        increment_version_number
      end
      increment_build_number
      build_number = get_build_number
      version = get_info_plist_value(path: "./Ebikemotion\ Dealer/Info.plist", key: "CFBundleShortVersionString")
      changelog = changelog_from_git_commits
      commit_version_bump(
        message: "[#{options[:deploy]}] Version Bump v#{version} (#{build_number})"
      )
      push_to_git_remote(
        remote: "origin",
        local_branch: branch,
        remote_branch: branch
      )
      github_release = set_github_release(
        repository_name: "minuscorp/ebikemotion2dealer",
        api_token: ENV['GITHUB_TOKEN'],
        name: options[:deploy] == "TEST" ? "#{version}.beta.#{build_number}" : version,
        tag_name: options[:deploy] == "TEST" ? "#{version}.beta.#{build_number}" : version,
        description: changelog,
        commitish: branch,
        is_prerelease: options[:deploy] == "TEST"
      )
    elsif
      puts "Use deploy: TEST|RELEASE options in order to run the lane."
    end
  end

  # You can define as many lanes as you want

lane :buddybuild do
  commit = last_git_commit
  if commit[:message].include? "[TEST]"
    pilot(
      username: "XXXXXXXXX",
      app_identifier: "com.ebikemotion.Ebikemotion-Dealer",
      ipa: ENV["BUDDYBUILD_APP_STORE_IPA_PATH"],
      distribute_external: true,
      testers_file_path: "./testers.csv",
      groups: ["Testers"]
    )
  elsif commit[:message].include? "[RELEASE]"
    deliver(
      submit_for_review: true,
      force: true,
      ipa: ENV["BUDDYBUILD_APP_STORE_IPA_PATH"]
    )
  else
    puts "------------------------------"
    puts "No further actions configured:"
    puts commit[:message]
    puts "------------------------------"
  end
end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ebikemotion.Ebikemotion-Dealer" # The bundle identifier of your app
apple_id "XXXXXXXXXX" # Your Apple email address

team_id "XXXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| json                      | 2.1.0        |
| excon                     | 0.59.0       |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.12.2       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
</details>

*generated on:* **2017-10-18**
</details>

**Comment by minuscorp** [comment]
Not sure if I need to answer a bot, but... Not related with code signing 😅

**Comment by mpirri** [comment]
@minuscorp This is very interesting. My suspicion is that there is a piece of metadata (this "optout" checkbox) that `deliver` is not including in submissions for apps that use IDFA.

Interestingly, you might have been getting this error before, but not actually having it reported to you by _fastlane_. We recently changed how `deliver` and `pilot` parse iTunesConnect error codes resulting in far-fewer false-positives on posting to iTC. For instance, previously this particular error would have been reported as success, even though the app might not have appeared on iTC.

So, if you post this app manual (via iTC), is there an "opt-out" checkbox that appears during the process? If so, we'll probably have to find a way to add support for this to `deliver`.

Also, silly question - does iTC just detect that your app uses iDFA, or is there a place in the web portal that you have to indicate that this is the case?

Thanks! 🚀

**Comment by minuscorp** [comment]
You have to select that your application does use IDFA and for what reason (3 different checkboxes that are nowadays already supported by Deliver), and an additional checkbox that confirms that you as a developer accepts the terms of use of the IDFA and that if you select the wrong answer they can reject your binary. After that you can send it to revision. So I think there's a missing option in the additional `submission_information` parameter collection (see [this](https://docs.fastlane.tools/actions/deliver/#submission_information) for more information)

**Comment by mpirri** [comment]
Got it. Thanks for the info - we'll see what we can do to add support for that additional flag.

**Comment by minuscorp** [comment]
If I can contribute on this issue you can give me a clue where to start? I think all the parse is done by Spaceship but I'm not sure. I'm here to help!

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group

**Comment by mpirri** [comment]
Actually, that would be really helpful! Have you ever used Charles Proxy to observe network requests? We have a useful web page (https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md) that talks through how to debug `spaceship` issues like these. Essentially, you will want to look at the network traffic made by a manual submission to iTunesConnect, and then compare that to what `spaceship` is doing, and see what `spaceship` has omitted.

Thanks so much for the offer - please let us know if there is any way we can help!  🚀

**Comment by minuscorp** [comment]
So... After debugging a manual build and an automated one, the only difference between the request body is the following:
```json
"contentRights": {
		"containsThirdPartyContent": {
			"value": false
		},
		"hasRights": {
			"value": true
		}
	},
```

which is just above the `"adIdInfo"` key where the other keys (uses the identifier, tracks installs, and others) are defined.

Those keys are already defined in the `submission_information` additional keys, so I'm going to provide those keys in my next build and see if that's enough to submit for review the build.
Although, if those keys solve the issue, (I think the `"hasRights"` keys should be the problematic) that key must be automatically set if the user uses the IDFA by default. A little change to the file should fix this behavior.

**Comment by mpirri** [comment]
Awesome - great detective work, @minuscorp ! Can't wait to hear what you find. 🚀

**Comment by minuscorp** [comment]
So... This is super weird... Setting those keys does not solve the issue and I cannot find differences between manual uploads and deliver ones...

**Comment by minuscorp** [comment]
So at last... This happened

```
[19:09:43]: Setting 'add_id_info_tracks_install' to 'true'...
[19:09:43]: Setting 'export_compliance_uses_encryption' to 'false'...
[19:09:43]: Setting 'export_compliance_encryption_updated' to 'false'...
[19:09:43]: Setting 'add_id_info_uses_idfa' to 'true'...
[19:09:43]: Setting 'content_rights_contains_third_party_content' to 'false'...
[19:09:43]: Setting 'content_rights_has_rights' to 'true'...
[19:09:43]: Setting 'add_id_info_limits_tracking' to 'true'...
[19:10:15]: Successfully submitted the app for review!
```

**Comment by mpirri** [comment]
@minuscorp Seems reasonable. So what did you change to make it set that value?

**Comment by minuscorp** [comment]
That value was already supported by the Deliver tool in the `submission_information` additional keys, but was not being automatically being set to true whenever the user chooses that his app uses IDFA. In my opinion this `add_id_info_limits_tracking` should not be set by the user, but automatically when `add_id_info_uses_idfa` is set to true.

**Comment by mpirri** [comment]
Sounds good - want to submit a pull request with this change?  😄

**Comment by minuscorp** [comment]
We can follow the discussion in #10653. 😄
