### ISSUE TITLE
Fails to pickup proxy configuration when uploading a build to hockeyapp

### ISSUE THREAD

**Issue by rafael-chavez** [fastlane/fastlane#10638]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fails to upload build to hockeyapp using fastlane hockey module

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
 /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/net/http/response.rb:122:in `error!': [!] 403 "Forbidden" (Faraday::ConnectionFailed)
 	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/net/http/response.rb:131:in `value'
 	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/net/http.rb:925:in `connect'
 	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
 	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/net/http.rb:876:in `start'
 	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/net/http.rb:1407:in `request'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:15:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/request/multipart.rb:15:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:186:in `post'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/actions/hockey.rb:48:in `upload_build'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/actions/hockey.rb:32:in `upload'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/actions/hockey.rb:157:in `run'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:234:in `block in execute_action'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:230:in `chdir'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:230:in `execute_action'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
 	from Fastfile:150:in `block (2 levels) in parsing_binding'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/lane.rb:33:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
 	from /usr/local/bin/fastlane:23:in `load'
 	from /usr/local/bin/fastlane:23:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | 10.12.6                                                |
| Ruby                        | 2.4.2                                                  |
| Bundler?                    | false                                                  |
| Git                         | git version 2.13.5 (Apple Git-94)                      |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane                    |
| Host                        | Mac OS X 10.12.6 (16G29)                               |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                           |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |
| Xcode Path                  | /Applications/Xcode/11.0/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.61.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| openssl                   | 2.0.5        |

**Comment by mpirri** [comment]
Can you send us the command line or Fastfile command you are using to invoke the `hockey` action? Also, can you try running with the `--verbose` flag so that we can see the response from hockey associated with the 403 error? Thanks!
