### ISSUE TITLE
A minor issue with the installer

### ISSUE THREAD

**Issue by adamvandenhovenfm** [fastlane/fastlane#10649]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I was installing fastlane via the script, I ran into all sorts of problems because my home directory had a space in it. Its the fault of my IT dept, and I've corrected it, but you might want to (a) put quotes around all the path components and (b) detect that specific problem and put up message, perhaps pointing people to https://support.apple.com/en-ca/HT201548. 

I had done (a) myself and the update_fastlane step blew up so maybe (b) is all that's needed. Unless you think I'm likely to be the only person ever to encounter this problem.

**Comment by mpirri** [comment]
@adamvandenhovenfm Great find! Any chance you want to submit the changes you made to the script to quote path components as a PR? Would love to see what you did there and maybe we can use that as the basis for getting the `update_fastlane` step working as well? Thanks! 🚀

**Comment by adamvandenhovenfm** [comment]
yeah I can probably do that... its not so hard. The issue I had with `update_fastlane` may be easy or hard, I'm not sure. Trying to flail around to get things working got me trying to update ruby via rbenv, which has the same issue. I raised this issue there too.

**Comment by adamvandenhovenfm** [comment]
I can't find the install script in the repo... at least the search didn't point out anything obvious.

**Comment by ohayon** [comment]
Hey @adamvandenhovenfm - apologies, the script is actually in another repo here: https://github.com/fastlane/packaged-fastlane 🚀
