### ISSUE TITLE
[Regression] Cannot execute fastlane beta

### ISSUE THREAD

**Issue by dvalenzuela** [fastlane/fastlane#10641]
### Issue Description

/Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:44:in `eval': (eval):2: syntax error, unexpected tIDENTIFIER, expecting end-of-input (SyntaxError)
apple_id "[maskedemail@gmail.com]" # Your Apple email address
               ^
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:44:in `block in initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:32:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:32:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:8:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:8:in `try_fetch_value'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:33:in `guess_package_name_from_appfile'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:68:in `guess_package_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:56:in `android_app_identifier'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:16:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:18:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:18:in `context_for_action_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:63:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by KrauseFx** [comment]
You seem to have forgotten to share your Appfile. This seems like there is a syntax error in your Appfile

**Comment by dvalenzuela** [comment]
@KrauseFx  It works well in 2.61.0, but after the update it stopped working.

Below is the App File Content (Keys and Other Elements where Masked)
```
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"
default_platform :ios

platform :ios do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/T04040911/AC79LH/drwcpXl5o5AHpfCB9jvCfhf9"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end
  changeLog     = changelog_from_git_commits
  desc "Submit a new Build to Test Fairy"
  lane :beta do
      # Ensure that your git status is not dirty
      git_pull
      #ensure_git_status_clean
      gym(scheme: "Project",
        project: "Project.xcodeproj",
        export_method: "ad-hoc")
    	testfairy(api_key: "A0987678998765678987656789876")
  end
  after_all do |lane|
    desc "Build URL: #{Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]} "
    version = get_info_plist_value(path: "./Project-Info.plist", key: "CFBundleShortVersionString")
    build = get_info_plist_value(path: "./Project-Info.plist", key: "CFBundleVersion")
    system("./Dropbox.sh #{Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]} '#{version}.#{build}.ipa'")
    slack(
        message: "Successfully deployed binary to Test Fairy #{version}.#{build}",
        success: true,
        payload: {  # Optional, lets you specify any number of your own Slack attachments.
          "Build" => "#{version}.#{build}",
          "Build Date" => Time.new.to_s,
          "Testfairy" =>"https://mycompany.testfairy.com",
          "IPA Download Folder" => "Link"
        },
        default_payloads: [:git_branch, :git_author]
    )
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

**Comment by dvalenzuela** [comment]
Even fastlane env fails

```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:44:in `eval': (eval):2: syntax error, unexpected tIDENTIFIER, expecting end-of-input (SyntaxError)
apple_id "diego.valenzuela@company.com" # Your Apple email address
               ^
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:44:in `block in initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:32:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:32:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:8:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/credentials_manager/lib/credentials_manager/appfile_config.rb:8:in `try_fetch_value'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:33:in `guess_package_name_from_appfile'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:68:in `guess_package_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:56:in `android_app_identifier'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:16:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:18:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:18:in `context_for_action_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:63:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
dMacPro:ios dvalenzuela$

**Comment by mpirri** [comment]
@dvalenzuela Looks like you sent us your `Fastfile` - can you send `Appfile` from the same `./fastlane` directory within your project?  Thanks!

**Comment by dvalenzuela** [comment]
@mpirri 
```
app_identifier com.gocanvas.canvas" # The bundle identifier of your app
apple_id "diego.valenzuela@company.com" # Your Apple email address

team_id "4Y59FUR69Z" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

**Comment by mpirri** [comment]
@dvalenzuela There is a syntax error in your `Appfile` - you are missing an opening quote before your app identifier. This is causing the parsing of the file to fail when it encounters the opening quote on the next line. Add a quote right before `com.gocanvas.canvas` and I suspect everything will be back to :100:!

**Comment by dvalenzuela** [comment]
@mpirri i dont recall modifying that document to begin with, but yeap that fixed the issue... 
Thanks
