### ISSUE TITLE
Snapshot Scan test doesn't give correct results

### ISSUE THREAD

**Issue by durul** [fastlane/fastlane#10658]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I used scan to automate running  Snapshot test for my app by facebookarchive/ios-snapshot-test-case instead of XCTestCase. Without ```fastlane scan``` my Snapshot test methods worked fine, I was getting green checkmark. When I use ```fastlane scan```at the end of scan I got reports with failure.  

<img width="1456" alt="screen shot 2017-10-20 at 12 42 18" src="https://user-images.githubusercontent.com/1297785/31832196-237272d8-b594-11e7-98b5-e7cc8403ec79.png">

```fastlane scan``` can not find images but images are there. 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.0"

default_platform :ios

platform :ios do
  before_all do
  #   cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "Acadia.xcworkspace",
      scheme: "PMIIntegration",
      devices: ["iPhone 7"]
      )
  end

lane :buildVibrentQAApps do
  vibrentIntegration
  vibrentQA
end

lane :buildPMIQAApps do
  pmiIntegration
  pmiQA
end

  lane :vibrentQA do
    certificates(
      appIdentifier: "com.vibrent.Acadia"
    )

    gymBuild(
      buildScheme: "VibrentQA",
      buildConfiguration: "QA"
    )

    slackMsg(
      message: "Successfully uploaded Vibrent QA APP build to crashlytics"
    )
  end

  lane :vibrentIntegration do
    certificates(
      appIdentifier: "com.vibrent.Acadia"
    )

    gymBuild(
      buildScheme: "VibrentIntegration",
      buildConfiguration: "Integration"
    )

    slackMsg(
      message: "Successfully uploaded Vibrent Integration APP build to crashlytics"
    )
  end

desc "Build step to produce an PMI QA build"
  lane :pmiQA do
    certificates(
      appIdentifier: "com.vibrent.PMI"
    )

    gymBuild(
      buildScheme: "PMIQA",
      buildConfiguration: "QA"
    )

    slackMsg(
      message: "Successfully uploaded PMI QA APP build to crashlytics"
    )
  end
  
desc "Build step to produce an Vibrent Integration build"
  lane :pmiIntegration do
    certificates(
      appIdentifier: "com.vibrent.PMI"
    )

    gymBuild(
      buildScheme: "PMIIntegration",
      buildConfiguration: "Integration"
    )

    slackMsg = "Successfully deployed new PMI QAC"
    slack(
      message: slackMsg
    )
  end

  lane :VibrentStaging do
    certificates(
      appIdentifier: "com.vibrent.Acadia"
    )

    gymBuild(
      buildScheme: "VibrentStaging",
      buildConfiguration: "Staging"
    )

    slackMsg = "Successfully deployed new Vibrent Staging"
    slack(
      message: slackMsg
    )
  end

desc "Build step to produce an PMI Integration build"
  lane :VibrentProduction do
    certificatesProduction(
      appIdentifier: "com.vibrent.AcadiaProduction"
    )

    gymBuild(
      buildScheme: "VibrentProduction",
      buildConfiguration: "Production"
    )

    slackMsg(
      message: "Successfully uploaded Acadia Production APP build to crashlytics"
    )
  end

  desc "Build step to produce an PMI Production build"
  lane :pmiProduction do

    gymBuild(
      buildScheme: "PMIProduction",
      buildConfiguration: "ReleasePMIProduction"
    )
  end

  desc "Shortcut, test to upload to crashlytics"
  lane :crashUpload do
    crashlytics(
      api_token: ENV["crash_api_token"],
      build_secret: ENV["crash_build_secret"],
      ipa_path: "./crashlyticsBuilds/Acadia.ipa",
      groups: ["qateam"]
    )
  end

  lane :slackMsg do |options|
    slackMessage = options[:message]

    slack(
        message: slackMessage,
        channel: "#buildbot",
        success: true,
        payload: {  # Optional, lets you specify any number of your own Slack attachments.
          "Build Date" => Time.new.to_s,
          "Built by" => "Bitrise",
        }
      )
  end

  after_all do |lane|

  end
    
  desc "sync certificates"
  lane :certificates do |options|
    appIdentifier = options[:appIdentifier]
    match(
      app_identifier: [appIdentifier], 
      type:"development", 
      git_url: "git@github.com:VibrentHealth/VHCertificates.git",
      readonly: true
    )
  end

  desc "sync certificates Production"
  lane :certificatesProduction do |options|
    appIdentifier = options[:appIdentifier]
    match(
      app_identifier: [appIdentifier], 
      type:"appstore", 
      git_url: "git@github.com:VibrentHealth/VHCertificates.git",
      readonly: true
    )
  end

  lane :gymBuild do |options|
    buildScheme = options[:buildScheme]
    buildConfiguration = options[:buildConfiguration]

    gym(
      workspace: "Acadia.xcworkspace",
      scheme: buildScheme,
      configuration: buildConfiguration,
      silent: true,
      clean: true,
      output_directory: "./crashlyticsBuilds",
      export_method: "development",
      output_name: "Acadia.ipa"
      )

    crashUpload
  end

  lane :PMIProductionBuild do
    ProductionBuild(
      buildScheme: "PMIProduction",
      buildConfiguration: "Production"
    )

    slackMsg(
      message: "Successfully uploaded PMI Production APP build to crashlytics"
    )
  end

  lane :PMIStaging do
    ProductionBuild(
      buildScheme: "PMIStaging",
      buildConfiguration: "Staging",
      profileName: "PMIEnterpriseProfile"
    )
    slackMsg(
      message: "Successfully uploaded PMI Staging APP build to crashlytics"
    )
  end

  lane :VibrentStagingOld do
    ProductionBuild(
      buildScheme: "VibrentStaging",
      buildConfiguration: "Staging"
    )
    slackMsg(
      message: "Successfully uploaded Vibrent Staging APP build to crashlytics"
    )
  end

  lane :AcadiaProductionBuild do
    ProductionBuild(
      buildScheme: "VibrentProduction",
      buildConfiguration: "Production"
    )
    slackMsg(
      message: "Successfully uploaded Vibrent Production APP build to crashlytics"
    )
  end

  lane :ProductionBuild do |options|
    buildScheme = options[:buildScheme]
    buildConfiguration = options[:buildConfiguration]
    profileName = options[:profileName]
    gym(
      workspace: 'Acadia.xcworkspace',
      scheme: buildScheme,
      configuration: buildConfiguration,
      silent: true,
      clean: true,
      output_directory: './crashlyticsBuilds',
      codesigning_identity: 'iPhone Distribution: Vignet Inc',
      export_method: 'enterprise',
      export_team_id: 'S489G82DC6',
      profile_name: profileName,
      profile_type: 'distribution',
      output_name: 'PMI.ipa'
      )

    ProductionCrashUpload()

  end

  lane :ProductionCrashUpload do |options|
    crashlytics(
      api_token: ENV["crash_api_token"],
      build_secret: ENV["crash_build_secret"],
      ipa_path: "./crashlyticsBuilds/PMI.ipa",
      groups: ["qateam"]
    )
  end

  error do |lane, exception|
    slack(
     message: exception.message,
     success: false
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-10-20**
</details>

**Comment by mpirri** [comment]
A quick thought based on the error message that you are getting - is it possible that `recordMode` is not being enabled when the tests are run through `scan`? Where do you set recordMode for these tests? Thanks!

**Comment by durul** [comment]
hello @mpirri recodmode = false. Because I had taken image snapshots with recodmode = true. We need recormode = true  just once. If you do not change UIViewcontroller. Thanks for answer.
