### ISSUE TITLE
How to distribute .apk to Fabric Beta?

### ISSUE THREAD

**Issue by mladenrakonjac** [fastlane/fastlane#10654]
Is there a way to upload .apk to Fabric Beta for Android?

**Comment by mpirri** [comment]
@mladenrakonjac Definitley!  Use the `crashlytics` action, and specify an `apk_path`. More information on the [`crashlytics` action documentation](https://docs.fastlane.tools/actions/crashlytics/) page.

I hope this is helpful! 🚀
