### ISSUE TITLE
Spaceship 2-Step Authentication throws an error

### ISSUE THREAD

**Issue by gapl** [fastlane/fastlane#10668]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Spaceship script `test.rb`

```ruby
#!/usr/bin/env ruby
require "spaceship"
Spaceship::Portal.login("user@email.com", "pass")
```

##### Complete output when running my own script `test.rb`, including the stack trace and command used

```
$ fastlane/test.rb 
Two Step Verification for account 'user@email.com' is enabled
Please select a device to verify your identity
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/two_step_client.rb:35:in `handle_two_step': undefined method `choose' for #<Spaceship::PortalClient:0x007fd485178868> (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/client.rb:473:in `send_shared_login_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/client.rb:660:in `do_login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/client.rb:401:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/client.rb:117:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.62.0/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
	from fastlane/test.rb:5:in `<main>'
```
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

**Comment by ohayon** [comment]
Hey @gapl - we should definitely look into this as it seems like there is an issue here. Just one question for you: is there a particular reason you are using Two Step Verification rather than Two Factor Authentication? 🦌

**Comment by gapl** [comment]
Thanks for looking into it!

The reason we're using Two Step Verification over Two Factor Authentication is that this is a company Apple ID in use only for iTunes Connect. It is not yet used on any device as a logged in iCloud account and thus we can't use any Apple device for iCloud verification. We rely on Apple's SMS verification that is not tied to iCloud usage.
