### ISSUE TITLE
Parameters are ignored

### ISSUE THREAD

**Issue by LesykMelnychuk** [fastlane/fastlane#10667]
Parameter "apple_id" in "testflight" line is ignored
Export_options - provisioningProfiles in "gym" lane is ignored

There are two applications already and bundle identifiers are already set. Don't know why, but fastlane takes one app id all the time, no meter what to set in 'pilot' or 'testflight' lane.
Similar is in gym for provision profiles setting

```
Error message:
<description> Ready to upload new build to TestFlight (App: 1293721839)...
[16:00:26]: Going to upload updated app to iTunes Connect
[16:00:26]: This might take a few minutes. Please don't interrupt the script.
[16:03:59]: [Transporter Error Output]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, '...'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect." </description>
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1033)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"

default_platform :ios

platform :ios do
  auto_generated_commit_prefix = "🤖 Released v"
  itc_team_id = 
  sudo_prefix = "echo #{build_machine_password} | sudo -S "
  current_workspace = 'Main.xcworkspace'
  targets = [###, ###2]

  provider_adHock_name =  ...
  customer_adHock_name =  ...

  provider_bundleId = ...
  customer_bundleId = ...

  itunes_provider_app_id = ...
  itunes_customer_app_id = ...

  app_bundleIds = {
    targets[0] => provider_bundleId,
    targets[1] => customer_bundleId
  }

  itunes_apps_ids = {
    targets[0] => itunes_customer_app_id,
    targets[1] => itunes_provider_app_id
  }
  
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2" # 2 == true, 3 == false -> default
    ENV["FASTLANE_ITC_TEAM_ID"] = itc_team_id

    # sh "npm install -g apollo-codegen"
    # update_fastlane_component
    # update_pods
  end

  desc "Submits a new Beta Build to Apple TestFlight"
  lane :test_flight do
    last_commit_message = Actions.last_git_commit_message

    if not last_commit_message.include? auto_generated_commit_prefix
      # cert
      # sigh
      # reset_simulators
      #test
      #build_number
      export_to_distribute_testers
    end
  end

  desc "General lane for Crashlytics export build"
  lane :crashlitics_export do
    last_commit_message = Actions.last_git_commit_message
    
    if not last_commit_message.include? auto_generated_commit_prefix
      cert
      sigh 
      # reset_simulators
      # test
      build_number
      export_to_crashlytics          
    end
  end

  desc "Close iOS simulators"
  lane :terminate_simulators do
    Action.sh("killall -9 Simulator 2>/dev/null || echo No simulators running")    
  end

  desc "Reset simulators"
  lane :reset_simulators do 
    if Env.reset_simulator?
      puts "Reset simulator: iOS #{CIConfig.full_test_device_name}"
      FastlaneCore::Simulator.reset(name: CIConfig.test_device_name, os_version: CIConfig.test_device)
      terminate_simulators # Kill simulators again (otherwise builds may get stuck)
    end
  end
  
  desc "Pods updating"
  lane :update_pods do
   cocoapods
  end

  desc "Update fastlane"
  lane :update_fastlane_component do
    sh "gem update fastlane"
  end

  desc "Build and distribute to testflight"
  lane :export_to_distribute_testers do
    targets.each do |scheme_name|
      gym(
        scheme: scheme_name, 
        workspace: current_workspace,
        export_method: "app-store"
      )

      testflight(
        distribute_external: true,
        apple_id: itunes_apps_ids[scheme_name],
        app_identifier: app_bundleIds[scheme_name],
        changelog: 'Misc. bug fixes and improvements throughout the app.',
        groups: "..."
      )
    end
  end

  desc "Send archive to crashlitics"
  lane :export_to_crashlytics do
    provider_app_id = ...
    customer_app_id = ...

    app_adhockIds = {
      targets[0] => provider_adHock_name,
      targets[1] => customer_adHock_name
    }

    app_crashlitycs_ids = {
      targets[0] => provider_app_id,
      targets[1] => customer_app_id
    }

    targets.each do |scheme_name|
      gym(
        scheme: scheme_name, 
        workspace: current_workspace, 
        export_method: "ad-hoc", export_options: {
          provisioningProfiles: {
            app_bundleIds[scheme_name] => app_adhockIds[scheme_name]
          }
        }
      )
      hockey(
        api_token: app_crashlitycs_ids[scheme_name]
      )
    end
  end

  desc "Increase build number"
  lane :build_number do
    # targets.each do |scheme_name|
    #   version = get_version_number
    #   build = increment_build_number
    #
    # increment_build_number_in_plist(
    #   build_number: build,
    #   version_number: version,
    #   target: scheme_name
    # )
    # end

    # semantic_version = "v#{version}_#{build}"

    # git_commit(
    #   path: ".",
    #   message: "#{auto_generated_commit_prefix}#{version} (#{build})"
    # )
    # add_git_tag(
    #   tag: semantic_version
    # )
    # push_to_git_remote
  end

  desc "Runs all the tests"
  lane :test do
    targets.each do |scheme_name|
      scan(
        scheme: scheme_name,
        workspace: current_workspace,
        clean: true,
        devices: ['iPhone 6'],
        output_directory: "build"
      )
    end
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.###.###", "com.###2.@@@2" # The bundle identifier of your app
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| bundler                   | 1.14.6       |
</details>

*generated on:* **2017-10-23**
</details>

**Comment by ohayon** [comment]
Hey @LesykMelnychuk - could you provide a bit more context about what's going wrong? In your Fastfile it looks like you have some custom logic that is setting the app ID for the testflight action, is it possible that is not behaving as expected? 🐰

**Comment by LesykMelnychuk** [comment]
Hi @ohayon  "is it possible that is not behaving as expected?" - yep you are right, testflight lane behaviour is unexpected
