### ISSUE TITLE
You are not permitted to add App IDs to this team

### ISSUE THREAD

**Issue by samuelcastro** [fastlane/fastlane#10665]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
 ✘  samuelcastro@Samuels-MacBook-Pro  ~/Projects/Integritas/hippo/client   mobile-environments ± fastlane ios create
[11:16:01]: -------------------------------------------------
[11:16:01]: --- Step: Verifying required fastlane version ---
[11:16:01]: -------------------------------------------------
[11:16:01]: Your fastlane version 2.62.0 matches the minimum requirement of 2.14.2  ✅
[11:16:01]: ------------------------------
[11:16:01]: --- Step: default_platform ---
[11:16:01]: ------------------------------
[11:16:02]: -------------------------------------------------
[11:16:02]: --- Step: Verifying required fastlane version ---
[11:16:02]: -------------------------------------------------
[11:16:02]: Your fastlane version 2.62.0 matches the minimum requirement of 1.68.0  ✅
[11:16:02]: ------------------------------
[11:16:02]: --- Step: default_platform ---
[11:16:02]: ------------------------------
[11:16:02]: Driving the lane 'ios create' 🚀
[11:16:02]: ----------------------------------
[11:16:02]: --- Step: cordova_get_app_name ---
[11:16:02]: ----------------------------------
[11:16:02]: --------------------------------
[11:16:02]: --- Step: cordova_get_app_id ---
[11:16:02]: --------------------------------
[11:16:02]: ---------------------
[11:16:02]: --- Step: produce ---
[11:16:02]: ---------------------

+----------------+-----------------------------+
|          Summary for produce 2.62.0          |
+----------------+-----------------------------+
| username       | MY_APPLE_ID |
| team_id        | TEAM_ID                  |
| itc_team_id    | ITC_TEAM_IC                   |
| app_identifier | APP_IDENTIFIER         |
| app_name       | MY_APP_NAME           |
| sku            | SKU                  |
| platform       | ios                         |
| language       | English                     |
| skip_itc       | false                       |
| skip_devcenter | false                       |
+----------------+-----------------------------+

[11:16:04]: Creating new app 'MY_APP_NAME' on the Apple Dev Center
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios create      |
| CORDOVA_APP_NAME | APP_NAME     |
| CORDOVA_APP_ID   | APP_NAME |
+------------------+-----------------+
[11:16:05]: {"responseId"=>"a5795fe9-8956-42fe-82f3-0430d6b75d30", "resultCode"=>1200, "resultString"=>"You are not permitted to add App IDs to this team.  Please contact one of your team admins, who can add the App ID on your behalf.", "userString"=>"You are not permitted to add App IDs to this team.  Please contact one of your team admins, who can add the App ID on your behalf.", "creationTimestamp"=>"2017-10-22T18:16:04Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/addAppId.action", "httpCode"=>200}

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | Verifying required   | 0           |
|      | fastlane version     |             |
| 2    | default_platform     | 0           |
| 3    | Verifying required   | 0           |
|      | fastlane version     |             |
| 4    | default_platform     | 0           |
| 5    | cordova_get_app_name | 0           |
| 6    | cordova_get_app_id   | 0           |
| 💥   | produce              | 2           |
+------+----------------------+-------------+

[11:16:05]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  You are not permitted to create provisioning profiles for team.
    https://github.com/fastlane/fastlane/issues/8183 [closed] 4 💬
    07 Aug 2017

➡️  [Match] Reusing manually generated certificates and provisioning
    https://github.com/fastlane/fastlane/issues/7133 [closed] 4 💬
    30 Apr 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Apple provided the following error info:
        You are not permitted to add App IDs to this team.  Please contact one of your team admins, who can add the App ID on your behalf.

```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

import "./fastlane-cordova/fastlane/Fastfile"

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
itc_team_id "118621158"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.2        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-10-22**
</details>

**Comment by samuelcastro** [comment]
That's not the case @fastlane-bot, my app is already using `match` with a few targets, I'm just trying to create new one (qa and dev).

**Comment by ohayon** [comment]
Hey @samuelcastro - it looks like your dev center user does not have permissions on the team for app ID creation. Could you confirm that you can do this manually in the web interface?

**Comment by samuelcastro** [comment]
@ohayon I do have permissions, I'm able to create new targets manually through the web interface without any problems.

**Comment by ohayon** [comment]
Interesting.... are you an admin on your team? If not could you let us know how your role is defined in the developer portal? Thanks!! 🚀

**Comment by samuelcastro** [comment]
@ohayon This is my role in the apple dev portal:

*App Manager.* The App Manager role can create apps and submit versions, edit store details, manage TestFlight builds and testers, manage iTunes Connect users and roles, grant users access to apps, and manage TestFlight users.

**Comment by ohayon** [comment]
Hey @samuelcastro, if I recall correctly, App Manager is a role that is specific to iTC rather than the dev portal. I think to create App IDs you need to be an Admin or Agent on the developer portal side of things. I could be mistaken, but could you take a look at what your role is on the dev portal?

**Comment by samuelcastro** [comment]
Good catch @ohayon, that's right, I was looking on iTC, on apple dev portal I'm just a **Member**. I'll request changes and try it again.

Thank you! :)

**Comment by ohayon** [comment]
No problem! Glad we could sort it out! 🚀
