### ISSUE TITLE
Code signing error even when certificate is in keychain

### ISSUE THREAD

**Issue by rishabhtayal** [fastlane/fastlane#1066]
I am getting code signing error. The certificate is valid and stored in local keychain. Not sure what's the issue.

`Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.`

**Comment by KrauseFx** [comment]
Please share information about your setup, in particular configuration files like your `Fastfile`, a screenshot of your Xcode project setting and if you use [match](https://github.com/fastlane/match)

**Comment by rishabhtayal** [comment]
@KrauseFx Here is my Fastfile: https://gist.github.com/rishabhtayal/0a65a42dbf32fcfc701b. Also attached is the screenshot of Xcode project setting.
![screen shot 2016-01-07 at 9 43 09 am](https://cloud.githubusercontent.com/assets/2100166/12174607/32e27f6a-b523-11e5-8a17-01b18fbeeeb5.png)

**Comment by rishabhtayal** [comment]
@KrauseFx Any updates?

**Comment by triage** [comment]
this seems to have happened to us over the weekend, too.

here's our fastfile
```
before_all do |lane, options|
  import_certificate({
    certificate_path: "fastlane/signing/MyCompany-Enterprise.p12",
    certificate_password: "<not our password>",
    keychain_name: "login.keychain"
  })
  cocoapods
end

lane :build do |options|
  #custom action to download a specific provisioning profile
  profile = sigh_download_profile({
    password: options[:password],
    provisioning_name: "My Company Development - Distribution",
  })
  gym(
    scheme: "Development",
    provisioning_profile_path: profile,
    codesigning_identity: "iPhone Distribution: My Company Inc.",
    export_method: "enterprise",
    xcargs: "APP_VERSION=#{options[:version]} BUILD_VERSION=#{options[:build]}",
    output_name: "Development"
  )
  clean_build_artifacts
end
```

**Comment by KrauseFx** [comment]
You both should start using [match](https://github.com/fastlane/match) with the [codesigning.guide](https://codesigning.guide) and also follow the [Xcode instructions](https://github.com/fastlane/match#setup-xcode-project) :+1:

**Comment by triage** [comment]
@KrauseFx we'd love to use Match! ... but we have existing enterprise apps w/ associated certs/profiles, etc.

**Comment by triage** [comment]
for anyone else that arrives here and by chance was building with CircleCI, `keychain_name: "login.keychain"` was working till this weekend for us. Changed to "circle.keychain"` and everything works fine again.

**Comment by rishabhtayal** [comment]
I agree with @triage. For my project its not possible for me to use matc

**Comment by rishabhtayal** [comment]
@KrauseFx @triage I added `codesigning_identity: "iPhone Distribution: My Company Inc.",` to my `Fastfile` and it worked! It now detects the signing certificate from my keychain. May be this issue can be fixed in next fastlane version.

**Comment by rishabhtayal** [comment]
Closing the issue now.

**Comment by flexaddicted** [comment]
@RishabhTayal can you share you Fastfile? In addition, where is your ent certificate located? Mine has been inserted into login.keychain. What I'm missing are the profile path and the export method. The first shoul be optional, as per doc. @KrauseFx any suggestion?

**Comment by flexaddicted** [comment]
Typo: your Fastfile

**Comment by TKBurner** [comment]
Hi @flexaddicted! Can you let me know what command you are using and share the full output of your error message? I definitely want to take a look 👍

**Comment by RishabhTayal** [comment]
@flexaddicted 

``` gym({
      scheme: ENV['SCHEME'],
      export_method: 'enterprise',
      # codesigning_identity: 'iPhone Distribution: *****'
      })
```

**Comment by flexaddicted** [comment]
@RishabhTayal Thanks for sharing. Is there any particular reason you commented out the signing identity?

@TKBurner here the detailed you asked for. Thanks.

- Error (The **enterprise** certificate is correctly installed in the **login.keychain**)

> Code Sign error: No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching "iPhone Distribution: **********" were found.

- Used command (the **ENV** variables are contained into a *.env* file)

```
gym(
        scheme: ENV['XCODE_SCHEME'],
        project: ENV['PROJECT'],
        sdk: ENV['SDK'],
        codesigning_identity: ENV['CODE_SIGN'],
        use_legacy_build_api: true,
        output_directory: ENV['OUTPUT_DIRECTORY'],
        configuration: 'Release'
    )
```

- Xcode configuration

<img width="592" alt="xcode" src="https://cloud.githubusercontent.com/assets/1482350/14800962/8f4afc3a-0b3d-11e6-99cf-29095138ffa9.png">

**NOTE** If I move the enterprise certificate into the **System.keychain** it works correctly. But this is not  what I want. In addition to that, the configuration I set runs correctly into a CI environment.

**Comment by RishabhTayal** [comment]
I believe I have set the code signing identity in Xcode configuration that’s why I did not need it. You may use it though.
