### ISSUE TITLE
Is there any way to change output format?

### ISSUE THREAD

**Issue by blackjid** [fastlane/fastlane#10660]
Hi, 

Is there any way to change the output format of a command?? For example something like this

```
fastlane match appstore --readonly --format json

{
    "certificate": {
        "user_id": "449NF38ND",
        "common_name" : "iPhone Distribution"
        ...
    },
    "profile": {
        "app_identifier": "com.mydomain.myapp",
        "type": "appstore",
        "profile_uuid": "3498ca-cba873e-0cf1f-dad-b34a76c",
        "profile_name": "match AppStore com.mydomain.myapp",
        ....
    }
}
```

**Comment by blackjid** [comment]
hey, thanks nice bot.... I really didn't know where to ask a question like this one. Is not an issue, more a question or feature request..

Is there a better place to ask this?

**Comment by ohayon** [comment]
Hey @blackjid - at the moment there is no other output format from _fastlane_. Having a JSON based output option would be quite sweet though! 🚀
