### ISSUE TITLE
unify export method types

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#10669]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It's very annoying that match takes type as `appstore`, but export method in gym is `app-store` or other way around?  In any case it would be great if you can just unify it so there is no difference. Thanks!

### Environment

Not required

**Comment by ohayon** [comment]
Thanks for the suggestion @romk1n, the fragmentation is definitely not amazing. At this point however, it would require a good amount of change to fix this and make sure that we do not break people's current setups. We defintiely will try to make sure we are consistent moving forward and when changes are made that we can be more future proof with this. 🚀
