### ISSUE TITLE
fastlane Init Error

### ISSUE THREAD

**Issue by sunforcode** [fastlane/fastlane#10679]
```
fastlane init --verbose
fastlane could not check for updates error: execution expired
[16:40:46]: fastlane detected a Gemfile in the current directory
[16:40:46]: however it seems like you don't use `bundle exec`
[16:40:46]: to launch fastlane faster, please use
[16:40:46]: 
[16:40:46]: $ bundle exec fastlane init --verbose
[16:40:46]: 
[16:40:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-10-24 16:40:49.24]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/CharlyZhang/Desktop/replayKitDemo/fastlane/Appfile'
- app_identifier: '517732'
- apple_id: 'com.founder.replayKitDemo'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
INFO [2017-10-24 16:40:49.47]: Detected iOS/Mac project in current directory...
INFO [2017-10-24 16:40:49.47]: This setup will help you get up and running in no time.
INFO [2017-10-24 16:40:49.47]: fastlane will check what tools you're already using and set up
INFO [2017-10-24 16:40:49.48]: the tool automatically for you. Have fun! 
INFO [2017-10-24 16:40:49.48]: $ xcodebuild -showBuildSettings -project ./replayKitDemo.xcodeproj
2017-10-24 16:40:49.835 xcodebuild[1673:436941] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
 [2017-10-24 16:40:57.36]: Your Apple ID (e.g. fastlane@krausefx.com): 363148025@qq.com
WARN [2017-10-24 16:41:35.28]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
INFO [2017-10-24 16:41:35.28]: Starting login with user '363148025@qq.com'
Loading session from '/Users/CharlyZhang/.fastlane/spaceship/363148025@qq.com/cookie'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) JWD48Y236P "Beijing Founder Electronics Co Ltd" (In-House)
2) ML9BS8L9GR "Beijing Founder Electronics Co.,Ltd" (Company/Organization)
2
Loading session from '/Users/CharlyZhang/.fastlane/spaceship/363148025@qq.com/cookie'
/Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:379:in `block in inflate_adapter': stack level too deep (SystemStackError)
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:411:in `call_block'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:402:in `<<'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:102:in `read'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:401:in `read'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:290:in `block in read_body_0'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:261:in `inflater'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	 ... 8723 levels...
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
	from /Users/CharlyZhang/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/CharlyZhang/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

------- help me

**Comment by ohayon** [comment]
Hey @sunforcode - thanks for raising the issue. Would you mind providing a bit of information about whats going on here? It looks like you're having an issue logging in to the dev portal, but a lot of that stack trace seems to be missing. Thanks!! 🚀

**Comment by lsw94315** [comment]
I have  a  same problem,have you solved this problem ?

**Comment by sunforcode** [comment]
CharlyZhangs-Mac-Pro:~ YongjiSun$ cd /Users/CharlyZhang/Desktop/replayKitDemo 
CharlyZhangs-Mac-Pro:replayKitDemo YongjiSun$ fastlane init --verbose env
[15:58:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-10-27 15:58:51.08]: Checking if there are any plugins that should be loaded...
INFO [2017-10-27 15:58:51.33]: Detected iOS/Mac project in current directory...
INFO [2017-10-27 15:58:51.33]: This setup will help you get up and running in no time.
INFO [2017-10-27 15:58:51.33]: fastlane will check what tools you're already using and set up
INFO [2017-10-27 15:58:51.33]: the tool automatically for you. Have fun! 
INFO [2017-10-27 15:58:51.33]: Created new folder './fastlane'.
INFO [2017-10-27 15:58:51.33]: $ xcodebuild -list -workspace ./replayKitDemo.xcworkspace
2017-10-27 15:58:51.872 xcodebuild[80613:1395052] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
INFO [2017-10-27 15:58:52.39]: $ xcodebuild -showBuildSettings -workspace ./replayKitDemo.xcworkspace -scheme replayKitDemo
2017-10-27 15:58:52.649 xcodebuild[80616:1395126] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
 [2017-10-27 15:58:54.19]: Your Apple ID (e.g. fastlane@krausefx.com): 363148025@qq.com
WARN [2017-10-27 15:59:02.29]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
INFO [2017-10-27 15:59:02.29]: Starting login with user '363148025@qq.com'
Loading session from '/Users/CharlyZhang/.fastlane/spaceship/363148025@qq.com/cookie'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) JWD48Y236P "Beijing Founder Electronics Co Ltd" (In-House)
2) ML9BS8L9GR "Beijing Founder Electronics Co.,Ltd" (Company/Organization)
1
Loading session from '/Users/CharlyZhang/.fastlane/spaceship/363148025@qq.com/cookie'

**Comment by jrryhrtn** [comment]
spa-mac-phtd6:ios irhppe$ grep -R BUNDLE *
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOS";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOS";
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOSTests";
AwesomeProject.xcodeproj/project.pbxproj:				BUNDLE_LOADER = "$(TEST_HOST)";
AwesomeProject.xcodeproj/project.pbxproj:				PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.AwesomeProject-tvOSTests";

Where the follow has zero results

xcodebuild -showBuildSettings -project ./AwesomeProject.xcodeproj | grep com.facebook.REACT.AwesomeProject 

fastlane init

[!] Could not detect bundle identifier of your react-native app. Make sure to open the Xcode project and update the bundle identifier in the `General` section of your project settings. Restart `fastlane init` once you're done!
