### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by 666sempron999** [fastlane/fastlane#10672]
Body text

**Comment by ohayon** [comment]
Hey @666sempron999 - Not sure if this issue was posted by mistake, but I am going to close it for now, let us know if you have any problems! 🚀

**Comment by 666sempron999** [comment]
Sorry, I just run example from https://gist.github.com/JeffPaine/3145490 to
get the issues.​


2017-10-23 22:37 GMT+03:00 David Ohayon <notifications@github.com>:
