### ISSUE TITLE
how to read match generated environment variables

### ISSUE THREAD

**Issue by rockneverdies55** [fastlane/fastlane#10671]
I run the `match`  in my build script by itself by passing the necessary env variables to it such as `MATCH_USERNAME=some@xyz.com match` and it successfully runs and sets everything up. It reports that it set **sigh_[app_identifier]_appstore** environment variable at the end. However I can no way read this value (other than manually copy pasting it) within bash script.  

Can someone please guide me on how to go about this?

```bash
  #!/bin/bash
  MATCH_USERNAME=me@me.com match
  # now read the value of generated environment variable: sigh_com.example.app120_appstore 
```

**Comment by ohayon** [comment]
Hey @rockneverdies55, thanks for posting the issue. I'm not totally sure I understand what you are trying to do here, but I think that if you use a Fastfile, you should be able to use any ENV variables that are set after `match` is executed. Sorry if I'm not fully understanding. Let me know if that makes sense or if you have any more context you can share so we can help! 🚀

**Comment by rockneverdies55** [comment]
Thanks for the answer. Can't I invoke `match` by itself in a custom build script written in bash and capture the environment variables set by match? Do I have to use a Fastfile?

Basically after match runs, I need to get provisioning profile uuid from the env variable generated by match and insert it into the cordova build.json file. Then build the project with `cordova build ios --release --device --buildConfig=build.json` to produce the ipa file.

**Comment by ohayon** [comment]
We definitely recommend using a Fastfile rather than a custom script as it will contain all of the context of _fastlane_ actions and allow you to access them.

**Comment by rockneverdies55** [comment]
@ohayon - Can you please at least guide me how to read that env var generated by match in a fastlane lane then?

For example:
```
lane :build_cordova do
  match(username: "me.me@com")
  # match has generated env var called "sigh_com.example.app120_appstore" 
  # read the value of the environment variable and use it in the next line
  sh("PROVISION_UUID=[/*VALUE_OF_ENV_VAR*/] cordova build")
end
```

How could I read and use the env var value on the `sh` line in the above snippet?

**Comment by ohayon** [comment]
Sure! You should be able to do something like 

```
env_var_value = ENV['NAME_OF_ENV_VARIABLE']
sh("PROVISION_UUID=env_var_value cordova build")
```

**Comment by rockneverdies55** [comment]
That worked. Thanks a lot @ohayon
