### ISSUE TITLE
Switched to using Match does not work and broke old fastfile

### ISSUE THREAD

**Issue by Genhain** [fastlane/fastlane#10677]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

So a little background, I am a little green when it comes to fastlane and terminal stuff, The team has two Apps on the store, one connects to the Production server and the other connects to the Staging server, and the Fastfile was bear minimum in setup. As it was pushing the staging App to testflight worked, but attempting to use fastlane to push a new build for release on the production version of the app did not. Then yesterday i tried using `cert` and `sigh` and it did the trick. I then thought id give the Match thing a go. And now as it is Nothing works, even when trying to go back to the old way when at least release the staging version of the app to testflight. I have followed the code signing guide as shown here

<img width="831" alt="screen shot 2017-10-24 at 11 24 43 am" src="https://user-images.githubusercontent.com/2082208/31923907-3b67678a-b8b0-11e7-9e37-4ab098786a9e.png">

The Error that comes out at the end is 

ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.eventxtra.CheckinStaging [Payload/2vanx.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

*Missing code-signing certificate* Excuse my ignorance but i thought match was supposed to handle this? 

One more thing that might exacerbate this issue is the development portal has heaps of certs and provisioning profiles. should i be nuking them with the match command?

At this point i am not sure what to do or how to fix it so that any usage of fastlane works on this project for these two app versions.

<details><summary>Previous fastfile</summary>

    fastlane_version "2.46.1"

    default_platform :ios

    xcversion version: "9.0.1"

    platform :ios do
      before_all do
        # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
        cocoapods
        
      end

      desc "Runs all the tests"
      lane :test do
        scan
      end

      def build_and_distribute_to_crashlytics(scheme)
        # Make sure we don't have any uncommited changes on master and are up to date with the remote
        # ensure_git_status_clean
        # ensure_git_branch(branch: 'master')
        # git_pull
        # push_to_git_remote

        # Ask the user of fastlane to enter a changelog
        changelog = IO.read("../CHANGELOG.md")

        # Increment the version number of your Xcode project
        if scheme == "CheckinStaging"
          # increment_build_number
        end
        # version = increment_version_number(bump_type: "patch")

        # Build and sign your app
        gym(scheme: scheme, export_method: "development")

        # Distribute via Crashlytics
        emails = %w(developer@eventxtra.com
                    apple@eventxtra.com
                    maxwu@eventxtra.com
                    johnchan@eventxtra.com
                    angel@eventxtra.com
                    david@eventxtra.com)

        options = {
          api_token: "6444855d6df7e4e76d6b30cb467c723d934cbce4",
          build_secret: "3bdb16b8b808495353859abf9ddc706de688954a8eed6f70856863ec06c3c3de",
          notes: changelog,
          notifications: true,
          emails: emails.join(', '),
          debug: true
        }
        crashlytics options
      end

      desc "Build and distribute build to Crashlytics (Production server)"
      lane :beta_production do
        build_and_distribute_to_crashlytics("Checkin")
      end

      desc "Build and distribute build to Crashlytics (Staging server)"
      lane :beta_staging do
        build_and_distribute_to_crashlytics("CheckinStaging")
      end

      desc "Build and distribute build to Crashlytics (Demo server)"
      lane :beta_demo do
        build_and_distribute_to_crashlytics("CheckinDemo")
      end

      desc "Take snapshots"
      lane :snapshot do
        snapshot
      end

      desc "Deploy a new version to the App Store"
      lane :appstore do
        # match(type: "appstore")
        # snapshot
        gym(scheme: "Checkin") # Build your app - more options available
        deliver(force: true)
        # frameit
      end

      desc "Deploy a new version to the App Store (Staging)"
      lane :appstore_staging do
        gym(scheme: "CheckinStaging")
        deliver(force: true, app_identifier: 'com.eventxtra.CheckinStaging', skip_metadata: true)
      end

      # You can define as many lanes as you want

      after_all do |lane|
        # This block is called, only if the executed lane was successful

        # slack(
        #   message: "Successfully deployed new App Update."
        # )
      end

      error do |lane, exception|
        # slack(
        #   message: exception.message,
        #   success: false
        # )
      end
    end
</details>

<details><summary>Current Matchfile</summary>
	git_url "git@git.2vanx.com:eventxtra/Check-In-Fastlane-Match.git"

	type "development" # The default type, can be: appstore, adhoc, enterprise or development

	# app_identifier ["tools.fastlane.app", "tools.fastlane.app2"]
	# username "user@fastlane.tools" # Your Apple Developer Portal username

	# For all available options run `fastlane match --help`
	# Remove the # in the beginning of the line to enable the other options
</details>

### Captured Output

Command Used: `ios staging`

Will provide Gist for captured output upon request

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.46.1"

default_platform :ios

xcversion version: "9.0.1"

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  # desc "Submit a new Beta Build to Apple TestFlight"
  # desc "This will also make sure the profile is up to date"
  # lane :beta do
  #   # match(type: "appstore") # more information: https://codesigning.guide
  #   gym(scheme: "Checkin") # Build your app - more options available
  #   pilot
  #
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here (run `fastlane actions`)
  # end
  def build_and_distribute_to_crashlytics(scheme)
    # Make sure we don't have any uncommited changes on master and are up to date with the remote
    # ensure_git_status_clean
    # ensure_git_branch(branch: 'master')
    # git_pull
    # push_to_git_remote

    # Ask the user of fastlane to enter a changelog
    changelog = IO.read("../CHANGELOG.md")

    # Increment the version number of your Xcode project
    if scheme == "CheckinStaging"
      # increment_build_number
    end
    # version = increment_version_number(bump_type: "patch")

    # Build and sign your app
    gym(scheme: scheme, export_method: "development")

    # Distribute via Crashlytics
    emails = %w(developer@eventxtra.com
                apple@eventxtra.com
                maxwu@eventxtra.com
                johnchan@eventxtra.com
                angel@eventxtra.com
                david@eventxtra.com)

    options = {
      api_token: "6444855d6df7e4e76d6b30cb467c723d934cbce4",
      build_secret: "3bdb16b8b808495353859abf9ddc706de688954a8eed6f70856863ec06c3c3de",
      notes: changelog,
      notifications: true,
      emails: emails.join(', '),
      debug: true
    }
    crashlytics options
  end

  desc "Build and distribute build to Crashlytics (Production server)"
  lane :beta_production do
    build_and_distribute_to_crashlytics("Checkin")
  end

  desc "Build and distribute build to Crashlytics (Staging server)"
  lane :beta_staging do
    build_and_distribute_to_crashlytics("CheckinStaging")
  end

  desc "Build and distribute build to Crashlytics (Demo server)"
  lane :beta_demo do
    build_and_distribute_to_crashlytics("CheckinDemo")
  end

  desc "Take snapshots"
  lane :app_snapshots do
    snapshot
  end

  lane :certificates do
    match(app_identifier: ["com.eventxtra.Checkin", "com.eventxtra.CheckinStaging"], readonly: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore",
          git_url: "git@git.2vanx.com:eventxtra/Check-In-Fastlane-Match.git",
          username: "developer@eventxtra.com",
          app_identifier: "com.eventxtra.Checkin")
    gym(scheme: "Checkin") # Build your app - more options available
    deliver(force: true)
  end

  desc "Deploy a new version to the App Store (Staging)"
  lane :appstore_staging do
    match(type: "development",
          git_url: "git@git.2vanx.com:eventxtra/Check-In-Fastlane-Match.git",
          username: "developer@eventxtra.com",
          app_identifier: "com.eventxtra.CheckinStaging",
          readonly: true)
    gym(scheme: "CheckinStaging",
        workspace: "Checkin.xcworkspace",
        export_method: "development")
    testflight
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.eventxtra.Checkin" # The bundle identifier of your app
apple_id "developer@eventxtra.com" # Your Apple email address

team_id "EMSJL2G288"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.59.0       |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| os                        | 0.9.6        |
| googleauth                | 0.6.1        |
| signet                    | 0.8.1        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.12.2       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| bundler                   | 1.15.4       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-10-24**
</details>

**Comment by Genhain** [comment]
## Update
Using the old Fastfile with the exception of changing `deliver` to `testflight` And setting the Signing for both Debug and Release to "match AppStore com.eventxtra.CheckinStaging" caused it to work, which leads me to believe there is something funky with the development provisioning profile and its signed certificate? I also deleted a bunch of old revoked certificates which then caused the "match Development com.eventxtra.CheckinStaging" certificate to no longer have a signing certificate.

Could the development match have been done incorrectly?

I am thoroughly vexed

**Comment by ohayon** [comment]
Hey @Genhain! Thanks for posting the issue and following up. Its pretty hard to diagnose the root cause of issues like this sometimes because it is so dependent on the developer account on Apple's end. That being said, it does sound like something went a bit wonky.

Looking at your Matchfile, it looks like `development` was selected as the type of cert/profile to create, so that is what was being attempted to be used by fastlane when it was building and signing your app, but as the error you shared above is mentioning, if you are uploading to iTunesConnect you need to use an app store cert/profile pair to sign with. Maybe by changing your Matchfile to say `appstore` instead of `development`, it could do the trick?

Let us know if you are still having problems and we will absolutely try to help out! 🚀  🐙

**Comment by Genhain** [comment]
@ohayon Will do, I've just been mired in trying to write a script to do clang-formatting for a 4 year old project and then making it merge nicely, once i have something to release ill give that a shot and update here

**Comment by Genhain** [comment]
@ohayon So i gave changing the Matchfile to `appstore` instead of `development` And it still does not seem to work, But not in the sense of when i try to run fastlane, actually its when im doing the manual code signing. When selecting the `match AppStore`  provisioning Profile its fine, however when i select the Development match provisioning profile it says

Provisioning profile "match Development com.eventxtra.CheckinStaging" doesn't include signing certificate "iPhone Developer: Cheuk Sum Wong (8WM8524S77)".

The thing to note that the team ID 8WM8524S77 is not the team ID on the developer portal, which is quite confusing, im not certain where it got this value from any thoughts?

**Comment by Genhain** [comment]
@ohayon, our developer portal was a mess and i was reluctant to use nuke, but i gave it a what the hell, ill deal with the backlash if any. Nukes both development and distribution and now it matches a correct Development and appstore profile for use.

So in short, as long as you arent running any Adhoc or enterprise releases during a sensitive time for clients. Nuking helps immensly
