### ISSUE TITLE
deliver fails when app is "Waiting for Review"

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#10686]
Reopening issue: https://github.com/fastlane/fastlane/issues/6010 to reinitiate the conversation.

When the app is in "Waiting for review" status on iTunes Connect, `deliver` will fail with error `Problem processing review submission.`. According to the issue #6010 this is an expected behavior. I just want to understand if this is still the case. Is there any other way to reject the version on the iTunes connect and resubmit with `deliver` automatically?

**Comment by minuscorp** [comment]
I'd like to help, can you provide some more information about this issue, maybe you can run in `verbose` the command and add it to the issue. 🚀

**Comment by RishabhTayal** [comment]
@minuscorp Just add `deliver(submit_for_review: true, force: true)` to your lane and run it when the latest version is in "Waiting for Review" status in iTunes Connect.

**Comment by RishabhTayal** [comment]
correct. Maybe there could be a parameter which will reject the current build on iTunes Connect and submit the new one.

**Comment by ohayon** [comment]
Hey folks! I think thats a really great idea @RishabhTayal, it would be nice to have that option. We would definitely take a look at a PR with that added. Let us know if we can help! 🚀

**Comment by minuscorp** [comment]
Reading the stub that produces the error: [this](https://github.com/fastlane/fastlane/blob/master/spaceship/spec/tunes/fixtures/app_submission/complete_failed.json), I'm wondering if the only difference between a successful review and one that doesn't is the `error` key with `null` content... If there's no certain message that Apple uses to really confirm that the review was errored because it's being reviewed... How can we do this?

**Comment by RishabhTayal** [comment]
@ohayon where can I start with the implementation? I know about the YOUR_FIRST_PR.md. I am talking about the technical details about the feature?

**Comment by ohayon** [comment]
Hey @RishabhTayal - I think [this file](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/submit_for_review.rb) would maybe be a good place to start tracing through some of the code. Also, if you're not familiar, you can use [pry](https://github.com/nixme/pry-debugger) to help with debugging and stepping through code too 😄 .

**Comment by RishabhTayal** [comment]
@ohayon I will check that. What's a good way to mock the app store submission while development, since I don't want to keep on submitting a build for dev purpose.

**Comment by ohayon** [comment]
@RishabhTayal I think we have some fixture json files that have mocked responses, you should be able to use WebMock and return those as necessary 👍

**Comment by RishabhTayal** [comment]
@ohayon Could you explain that more? Is there any link/resource I can refer to?

**Comment by RishabhTayal** [comment]
There is an open PR #10722
