### ISSUE TITLE
 xcodebuild -showBuildSettings   Command timed out after 10 seconds 

### ISSUE THREAD

**Issue by hytzxd** [fastlane/fastlane#10680]
<details><summary>✅ fastlane environment ✅</summary>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.62.1  | 💥 Check failed |
*generated on:* **2017-10-24**
</details>

##console output 

 $ xcodebuild -list -workspace  ****.xcworkspace -configuration *****
[18:15:23]: $ xcodebuild -showBuildSettings -workspace  ***** -scheme ***** -configuration ***
[18:15:33]: Command timed out after 10 seconds on try 1 of 4, trying again...
[18:15:43]: Command timed out after 10 seconds on try 2 of 4, trying again...
[18:15:53]: Command timed out after 10 seconds on try 3 of 4, trying again...
[18:16:03]: Command timed out after 10 seconds on try 4 of 4
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beat |
+------------------+----------+
[18:16:03]: xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES

**Comment by hytzxd** [comment]
Thank you  very much. I have solved it by set " FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT= 120";

**Comment by hytzxd** [comment]
Thank you very much.

**Comment by ohayon** [comment]
Glad you got things working @hytzxd !! 🚀
