### ISSUE TITLE
How  do i provide the apk file to upload to the google play store ?

### ISSUE THREAD

**Issue by jpca999** [fastlane/fastlane#10689]
I've read the following document, but Im still not ablel to figure how do i supply the apk file 
for fastlane to deploy the file to the google play store ?

https://docs.fastlane.tools/getting-started/android/release-deployment/#uploading-your-apk

Like in order to deploy the iap file in apple store we provide the location of the file like below. 

![image](https://user-images.githubusercontent.com/1026325/31973766-ae74360a-b8f5-11e7-8e26-0a6babe56473.png)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :beta do
  pilot(ipa: "/Users/jay/Desktop/ios%2F@jay_jpca999%2Frecherry-0bc0f0a6-b14b-11e7-9289-0050568ec4ea-archive.ipa")
  end

lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/Users/jay/Desktop/googlekey.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.recherry.app" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
</details>

*generated on:* **2017-10-24**
</details>

**Comment by ohayon** [comment]
Hey @fastlane/android folks! Any chance you could chime in here? 🐐

**Comment by joshdholtz** [comment]
@jpca999 Make sure to follow the `supply` instructions on getting your google JSON key file - https://docs.fastlane.tools/actions/supply/

```rb
gradle(
  task: 'assemble',
  build_type: 'Release'
)
  
# Using `GRADLE_APK_OUTPUT_PATH` to make sure we are only
# getting one APK (sometimes an debug and release are build)
# This gets the release
apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

# Uploading to Google Play
# These are arguments I usually use
# I upload to the "beta" track so it doesn't get automatically released
supply(
  apk: apk_path,
  package_name: package_name,
  track: "beta",
  skip_upload_metadata: true,
  skip_upload_images: true,
  skip_upload_screenshots: true )
```

**Comment by igorlamos** [comment]
Hi,

```
lane :beta do
  pilot(ipa: "<path_to_the_ipa_file">)
end
```

will upload your IPA file to Apple's TestFlight.

Analogy for Google Play Store (Alpha track) is:
```
lane :alpha do
  supply(
    track: "alpha", // "beta" for Beta, "production" for Production ...
    apk: "<path_to_the_apk_file>"
  )
end
```

Complete documentation for `supply` can be found here:
[https://docs.fastlane.tools/actions/supply/](https://docs.fastlane.tools/actions/supply/)

According to your Screenshot in this Issue, you have:
```
lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end
```

This will only use `gradle` to assemble a Release APK for you. There is no `supply` which tells Fastlane to upload built APK file to Google Play Store. Add `supply` after `gradle`:
```
lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

  supply(
    track: "alpha",
    apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
  )
end
```

`SharedValues::GRADLE_APK_OUTPUT_PATH` will hold the path to the latest APK file built. This is relevant for most projects...

You can find the complete example here:
[https://github.com/igorlamos/udemy-fastlane/blob/master/android/fastlane/Fastfile](https://github.com/igorlamos/udemy-fastlane/blob/master/android/fastlane/Fastfile)

Hope this helps.

**Comment by jpca999** [comment]
@igorlamos 

Heres my updated code. Kindly help me resolve the issue. 


fyi: this is my first time trying to upload apk file to google app store with help of expo and fastlane 

Here are the steps. 

1) I used exp build:android 
2) exp build:status 
go the apk file and put the location in my fastlane/fastlane file. 

![image|690x193](upload://aQDwtd3F6jq0Zldw4bs46DbKahz.png)


so when i tried to upload this file to app store it gave me this error: 

![image|623x500](upload://tHG15n1QFUV09ONRhsRAC6FKB4l.jpg)

![image|690x475](upload://ssst51VQAfwrGaoyzsJNyJetnlz.jpg)

**Comment by igorlamos** [comment]
Hey @jpca999 

look at the last screenshot you posted ... there is an error message, which says:
`"APK specifies a version code that has already been used."`

Now, open the `android/app/build.gradle` file and search for `versionCode`. Everytime you upload a new APK to the Google Play Store, **you have to raise this number**. Look at the documentation here https://developer.android.com/studio/publish/versioning.html and try to find `versionCode`. There is a clear explanation of WHY for `versionCode`.

You can use `increment_version_code` Fastlane plugin to do this automatically. I've explained this in my [Fastlane / Bitrise Course](https://www.udemy.com/automate-your-react-native-releases-with-fastlane-and-bitrise/?couponCode=RNFB_GITHUB).

And some other points:
1. You don't need to use `sudo` with Fastlane ... why are you using it this way? Also the output contains "Get started using a Gemfile for Fastlane ..."
2. I see you're using Expo for your RN app ... and if it's for the first time for you, I understand you have some issues ... if you continue to experience these issues, and if it's possible, you can share your repo (or some part) with me and I'll help you to set it up. I'm glad I can help :)

Let me know.

**Comment by jpca999** [comment]
@igorlamos 

I can't locate this file. 
android/app/build.gradle

here is my project structure.... 

![image](https://user-images.githubusercontent.com/1026325/32806401-61023f1e-c95a-11e7-9bf6-430e2eab8679.png)

**Comment by igorlamos** [comment]
Yes @jpca999 - **it's my fault, sorry** ... I didn't realize it's different in Expo .. you don't have an Android project :-) sorry for that ...

So for you - you have to locate `app.json` file (https://github.com/jpca999/fastlane-test-app/blob/master/app.json).

According to Expo documentation here:
https://docs.expo.io/versions/latest/guides/configuration.html

add `android` section (as well as you have `ios` now) with a child `versionCode` and set a value of `2` now (I assume you have successfully uploaded just the first build with `versionCode` of `1`). **And everytime you prepare new build using Expo, raise this number by `1` (so next time, you will set it to `3`, then `4` and so on)**.

Details can be found in the docs:
https://docs.expo.io/versions/latest/guides/configuration.html#versioncode

I hope this will help.

**Comment by jpca999** [comment]
okay @igorlamos , so this time after I providing and incrementing the version number  I created a new build for android  & I got this error 


![image](https://user-images.githubusercontent.com/1026325/32810719-42ec30ce-c96a-11e7-8fd4-6376934c250e.png)


My app.json file 

{
  "expo": {
    "name": "App",
    "description": "the App",
    "slug": "theApp",
    "privacy": "unlisted",
    "sdkVersion": "21.0.0",
    "version": "1.0.20",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "hideExponentText": true,
    "versionCode": "2",
    "loading": {
      "backgroundImage": "./assets/icons/splash_ink.jpg",
      "splash": {
        "backgroundColor": "#222127",
        "image": {
          "ios": {
            "backgroundImage": "./assets/icons/splash_ink.jpg"
          }
        }
      }
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
          "bundleIdentifier": "com.theAppp.exp",
          "supportsTablet": true
    },
    "android": {
       "package": "org.theAppp.exp",
     }
  }
}

**Comment by igorlamos** [comment]
Wrong placement of `versionCode` in `app.json` ... and the error is the same as before.

Try this:
```json
{
  "expo": {
    "name": "App",
    "description": "the App",
    "slug": "theApp",
    "privacy": "unlisted",
    "sdkVersion": "21.0.0",
    "version": "1.0.20",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "hideExponentText": true,
    "loading": {
      "backgroundImage": "./assets/icons/splash_ink.jpg",
      "splash": {
        "backgroundColor": "#222127",
        "image": {
          "ios": {
            "backgroundImage": "./assets/icons/splash_ink.jpg"
          }
        }
      }
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "bundleIdentifier": "com.theAppp.exp",
      "supportsTablet": true
    },
    "android": {
      "package": "org.theAppp.exp",
      "versionCode": "2"
    }
  }
}
```

**Comment by jpca999** [comment]
@igorlamos   not the same error but another error 

![image](https://user-images.githubusercontent.com/1026325/32836412-b2b8169e-c9d7-11e7-93cc-7e8c7c45964e.png)

**Comment by igorlamos** [comment]
You have to sign the APK with the same key as you've already done with the `versionCode` 1.

Read here:
https://support.google.com/googleplay/android-developer/answer/113476?hl=en

**The updated APK needs to be signed with the same signature as the current version.**

**Comment by jpca999** [comment]
I dont think i have the signatures thing,,,  if i create a new app, would it give me new signatures ?
