### ISSUE TITLE
Warning app_identifier when use multiple targets

### ISSUE THREAD

**Issue by narlei** [fastlane/fastlane#10693]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My app contains multi targets as Whitelabels, then I use ENV[] to setup app_identifier, but in the last fastlane version this warning shows:

_In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value rght after the option name. Make sure to check the docs for more information_

````
fastlane
[15:45:49]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:45:52]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value rght after the option name. Make sure to check the docs for more information
[15:45:52]: In the config file './Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value rght after the option name. Make sure to check the docs for more information
[15:45:52]: -----------------------------
[15:45:52]: --- Step: update_fastlane ---
[15:45:52]: -----------------------------
[15:45:52]: Looking for updates for fastlane...
````
### Environment

**Fastfile:**
````
def find_bundle (bundle_name)
  case bundle_name
  when "SocialBase"
    ENV["BUNDLE"] = "com.socialbase.socialbase"

  when "CREA"
    ENV["BUNDLE"] = "com.socialbase.conecteCREA"

  when "Fazenda"
    ENV["BUNDLE"] = "com.socialbase.redefaz"

  when "Capemisa"
    ENV["BUNDLE"] = "com.socialbase.capemisa"

  when "Portobello"
    ENV["BUNDLE"] = "com.socialbase.redepb"

  when "PortoSeguro"
    ENV["BUNDLE"] = "com.socialbase.redeporto"

  when "Epagri"
    ENV["BUNDLE"] = "com.socialbase.redeepagri"

  when "Senior"
    ENV["BUNDLE"] = "com.socialbase.senior"

  when "Embratur"
    ENV["BUNDLE"] = "com.socialbase.embratur"
  end
end

platform :ios do
  before_all do
    # cocoapods
  end

  desc "Deploy a new version to the App Store"
  lane :deployAll do
    #increment_version_number
    #increment_build_number

    ["Senior", "Embratur", "Epagri", "SocialBase", "Portobello", "Capemisa", "PortoSeguro", "CREA", "Fazenda"].each do |scheme_name|
        ENV["SCHEME"] = scheme_name
        find_bundle(scheme_name)
        gym(
          export_xcargs: "-allowProvisioningUpdates",
          export_options: {
            iCloudContainerEnvironment: 'Production'
          }
        )
        deliver
    end
  end


.....
````

Deriverfile

````
app_identifier ENV["BUNDLE"]# The bundle identifier of your app

....
````

**Comment by ohayon** [comment]
Hey @narlei - would you mind sharing the output of `fastlane env` and some more of the output from your terminal? I have been trying to reproduce this for a bit and am unable to recreate the situation so I would love some more context about how this is happening? Thanks 🚀

**Comment by narlei** [comment]
Hi @ohayon here's my environment. Thank you!


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0.1                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.1"

default_platform :ios

generated_fastfile_id "cb32b268-9d3d-4098-8c97-f7788a07f718"

#method to change the bundle name in fastlane lanes.
def find_bundle (bundle_name)
  case bundle_name
  when "SocialBase"
    ENV["BUNDLE"] = "com.socialbase.socialbase"

  when "CREA"
    ENV["BUNDLE"] = "com.socialbase.conecteCREA"

  when "Fazenda"
    ENV["BUNDLE"] = "com.socialbase.redefaz"

  when "Capemisa"
    ENV["BUNDLE"] = "com.socialbase.capemisa"

  when "Portobello"
    ENV["BUNDLE"] = "com.socialbase.redepb"

  when "PortoSeguro"
    ENV["BUNDLE"] = "com.socialbase.redeporto"

  when "Epagri"
    ENV["BUNDLE"] = "com.socialbase.redeepagri"

  when "Senior"
    ENV["BUNDLE"] = "com.socialbase.senior"

  when "Embratur"
    ENV["BUNDLE"] = "com.socialbase.embratur"
  end
end

platform :ios do
  before_all do
    # cocoapods
  end

  desc "Deploy a new version to the App Store"
  lane :deployAll do
    #increment_version_number
    #increment_build_number

    ["Senior", "Embratur", "Epagri", "SocialBase", "Portobello", "Capemisa", "PortoSeguro", "CREA", "Fazenda"].each do |scheme_name|
        ENV["SCHEME"] = scheme_name
        find_bundle(scheme_name)
        gym(
          export_xcargs: "-allowProvisioningUpdates",
          export_options: {
            iCloudContainerEnvironment: 'Production'
          }
        )
        deliver
    end
  end

  desc "Deploy a new version to BETA Users in SocialBase Staging"
  lane :fabric do

    scheme_name = "SocialBase"
    ENV["SCHEME"] = scheme_name
    find_bundle(scheme_name)

    changelog = File.read("Changelog.txt")
    increment_build_number

    gym(
      scheme: "SocialBase",
      export_xcargs: "-configuration 'Adhoc'",
      export_options: {
         iCloudContainerEnvironment: 'Development'
      },
      export_method: "ad-hoc"
    )

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "50f8b882fa802f838e2f23a6ee949a922eb58a3b",
      build_secret: "3a2d107ce4aaf9dcae237a1f159c082822ee371a66d1e22e3609cf36a4f5d843",
      groups: "Interno",
      notes: changelog
    )
  end

  desc "Increase build version"
  lane :add_version do
    increment_build_number
  end

  # Whitelabels

  desc "Deploy specific whitelabel to AppStore, call: `$ fastlane ios deploy scheme:'WhiteLabel'`"
  lane :deploy do |options|

    scheme_name = options[:scheme]
    ENV["SCHEME"] = scheme_name
    find_bundle(scheme_name)

    gym(
      scheme: options[:scheme],
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        iCloudContainerEnvironment: 'Production'
      }
    )
    deliver
  end

  # You can define as many lanes as you want
  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

app_identifier ENV["BUNDLE"] # The bundle identifier of your app
apple_id "narlei_@hotmail.com" # Your Apple email address

team_id "3G9EBGNG32"  # Developer Portal Team ID
itc_team_id "4027801" # Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-10-26**
</details>

**Comment by ohayon** [comment]
Hey @narlei - this is definitely a bit strange. I am having a hard time reproducing the issue locally. I have two proposals to help you out of this mess though! 🚀 

1. You could try to pass your app ID in to the `deliver` call directly rather than relying on your Deliverfile, and that would just look like: `deliver(app_identifier: find_bundle(scheme_name))` and you would just want to change your `find_bundle` method to return the ID rather than just setting the ENV var.
2. The other option would depend on your familiarity with Ruby, it would be interesting to see if you could put a breakpoint in where that error message gets printed to see exactly what the call stack is that gets you there and then we could move forward from there.

I think option 1 is probably the best/easiest to move forward quickly 😄

**Comment by scurioni** [comment]
Same error here. I have an app with 4 schemes, and only one of the schemes is giving me this issue. Will try to provide more details later.

**Comment by ohayon** [comment]
Hey @scurioni - apologies for this issue, I think the same fix I mentioned above should work for you too... if you pass the `app_identifier:` param to match, and remove it from your Matchfile, it should work 💯 . I think that the config files themselves dont respond so well to dynamically setting values 😄
