### ISSUE TITLE
xcrun in 2.62.1 vs 2.59

### ISSUE THREAD

**Issue by mijo-gracanin** [fastlane/fastlane#10691]
### Issue Description
With fastlane 2.62.1, my builds fail with message:
`xcodebuild: error: The flag -scheme or -xctestrun is required when specifying -derivedDataPath.`
With 2.59 there are no errors.

xcrun in 2.59:
`/usr/bin/xcrun /Users/bserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.59.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/ym/q1t4j38x72vd106y8npc2_y40000gq/T/gym_config20171024-25903-1g33djl.plist' -archivePath build/Napster-CoreTeam.xcarchive -exportPath '/var/folders/ym/q1t4j38x72vd106y8npc2_y40000gq/T/gym_output20171024-25903-1uaj3cn' `

2.62.1:
`/usr/bin/xcrun /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/vd/xrhd3z751kq6zxq02vlfdvgr0000gr/T/gym_config20171024-67531-1tgwn87.plist' -archivePath build/Movistar_Musica-CoreTeam.xcarchive -exportPath '/var/folders/vd/xrhd3z751kq6zxq02vlfdvgr0000gr/T/gym_output20171024-67531-1ipgt09' -derivedDataPath derivedData`

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.8.2                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.59.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

**Comment by ohayon** [comment]
Hey @mijo-gracanin, would you mind sharing a bit more of the output from your terminal so we can have a bit more context to work with?

**Comment by mijo-gracanin** [comment]
Hey @ohayon , here is more output:
<details>
_..cut out some jenkins mumbo jumbo..._

[11:53:50]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:53:53]: You require a gem, if this is a third party gem, please use `fastlane_require 'fileutils'` to ensure the gem is installed locally
[11:53:53]: -------------------------------------------------
[11:53:53]: --- Step: Verifying required fastlane version ---
[11:53:53]: -------------------------------------------------
[11:53:53]: Your fastlane version 2.62.1 matches the minimum requirement of 1.80.0  ✅
[11:53:53]: ------------------------------
[11:53:53]: --- Step: default_platform ---
[11:53:53]: ------------------------------
[11:53:53]: Driving the lane 'ios build' 🚀
[11:53:53]: -------------------
[11:53:53]: --- Step: is_ci ---
[11:53:53]: -------------------
[11:53:53]: -----------------------------
[11:53:53]: --- Step: unlock_keychain ---
[11:53:53]: -----------------------------
[11:53:53]: Unlocking keychain at path: /Users/bserver/Library/Keychains/login.keychain-db
[11:53:54]: --------------------------
[11:53:54]: --- Step: xcode_select ---
[11:53:54]: --------------------------
[11:53:54]: Setting Xcode version to /Applications/Xcode.app for all build steps
_...cut out some Jenkins mumbo jumbo..._
[11:53:56]: build is called with options:
[11:53:56]: {:scheme=>"Rhapsody", :configuration=>"CoreTeam", :platform=>"iphoneos", :build_number=>"", :upload_dsym=>true}
[11:53:56]: get_jenkins_build_number: 2375 (ENV_BUILD_NUM:2375)
[11:53:56]: reset_build_number(): Incrementing version number to 2375
[11:53:56]: ------------------------------------
[11:53:56]: --- Step: increment_build_number ---
[11:53:56]: ------------------------------------
_...cut out some Jenkins mumbo jumbo..._
[11:54:03]: build_binary_iphoneos() starting...
[11:54:03]: --------------------------------
[11:54:03]: --- Step: clear_derived_data ---
[11:54:03]: --------------------------------
[11:54:03]: Derived Data path located at: /Users/bserver/Jenkins/Home/jobs/Continuum_CI_Matrix_Builder/workspace/SCHEME/Rhapsody/derivedData
[11:54:06]: Successfully cleared Derived Data ♻️
[11:54:06]: -----------------
[11:54:06]: --- Step: gym ---
[11:54:06]: -----------------
[11:54:07]: $ xcodebuild -list -workspace ./Rhapsody.xcworkspace -configuration CoreTeam
[11:54:25]: $ xcodebuild -showBuildSettings -workspace ./Rhapsody.xcworkspace -scheme Rhapsody -configuration CoreTeam
[11:55:20]: Couldn't automatically detect the provisioning profile mapping
[11:55:20]: There were multiple profiles for bundle identifier(s): com.rhapsody.iphone.${PRODUCT_NAME:rfc1034identifier}3
[11:55:20]: You need to provide an explicit mapping of what provisioning
[11:55:20]: profile to use for each bundle identifier of your app
[11:55:20]: Couldn't automatically detect the provisioning profile mapping
_..cut out some mumbo jumbo..._
[11:55:20]: Detected provisioning profile mapping: {:"com.rhapsody.iphone.Rhapsody3"=>"Rhapsody3 Ad Hoc", :"com.rhapsody.iphone.Rhapsody3.RhapsodyNotificationServiceExtension"=>"RhapsodyNotificationServiceExtension AdHoc",
_..cut out some mumbo jumbo..._
}

+---------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------+
|                                                                              Summary for gym 2.62.1                                                                              |
+---------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------+
| scheme                                                                                                              | Rhapsody                                                   |
| configuration                                                                                                       | CoreTeam                                                   |
| xcargs                                                                                                              | -derivedDataPath derivedData                               |
| archive_path                                                                                                        | build/Rhapsody-CoreTeam.xcarchive                          |
| include_bitcode                                                                                                     | false                                                      |
| export_method                                                                                                       | ad-hoc                                                     |
| export_options.provisioningProfiles.com.rhapsody.iphone.Rhapsody3                                                   | Rhapsody3 Ad Hoc                                           |
| export_options.provisioningProfiles.com.rhapsody.iphone.Rhapsody3.RhapsodyNotificationServiceExtension              | RhapsodyNotificationServiceExtension AdHoc                 |
| export_options.provisioningProfiles.com.rhapsody.iphone.Rhapsody3.enterprise                                        | Rhapsody Enterprise In House                               |
| export_options.provisioningProfiles.com.rhapsody.iphone.Rhapsody3.enterprise.RhapsodyNotificationServiceExtension   | RhapsodyNotificationServiceExtension In House              |
| export_options.provisioningProfiles.com.rhapsody.iphone.Napster3                                                    | Napster3 AdHoc                                             |
| export_options.provisioningProfiles.com.rhapsody.iphone.Napster3.NapsterNotificationServiceExtension                | NapsterNotificationServiceExtension AdHoc                  |
| export_options.provisioningProfiles.com.rhapsody.iphone.Napster3.enterprise                                         | Napster Enterprise In House                                |
| export_options.provisioningProfiles.com.rhapsody.iphone.Napster3.enterprise.NapsterNotificationServiceExtension     | NapsterNotificationServiceExtension In House               |
| export_options.provisioningProfiles.com.rhapsody.iphone.Vivo-Musica3                                                | VivoMusica3 AdHoc                                          |
| export_options.provisioningProfiles.com.rhapsody.iphone.Vivo-Musica3.VivoNotificationServiceExtension               | VivoNotificationServiceExtension AdHoc                     |
| export_options.provisioningProfiles.com.rhapsody.iphone.Vivo-Musica3.enterprise                                     | Vivo Enterprise In House                                   |
| export_options.provisioningProfiles.com.rhapsody.iphone.Vivo-Musica3.enterprise.VivoNotificationServiceExtension    | VivoNotificationServiceExtension In House                  |
| export_options.provisioningProfiles.com.rhapsody.iphone.aldilifemusik                                               | AldiLifeMusik AdHoc                                        |
| export_options.provisioningProfiles.com.rhapsody.iphone.aldilifemusik.AldiNotificationServiceExtension              | AldiNotificationServiceExtension AdHoc                     |
| export_options.provisioningProfiles.com.rhapsody.iphone.aldilifemusik.enterprise                                    | Aldi Enterprise In House                                   |
| export_options.provisioningProfiles.com.rhapsody.iphone.aldilifemusik.enterprise.AldiNotificationServiceExtension   | AldiNotificationServiceExtension In House                  |
| export_options.provisioningProfiles.com.rhapsody.iphone.hoferlifemusic                                              | HoferLifeMusic AdHoc                                       |
| export_options.provisioningProfiles.com.rhapsody.iphone.hoferlifemusic.HoferNotificationServiceExtension            | HoferNotificationServiceExtension AdHoc                    |
| export_options.provisioningProfiles.com.rhapsody.iphone.hoferlifemusic.enterprise                                   | Hofer Enterprise In House                                  |
| export_options.provisioningProfiles.com.rhapsody.iphone.hoferlifemusic.enterprise.HoferNotificationServiceExtension | HoferNotificationServiceExtension In House                 |
| export_options.provisioningProfiles.com.rhapsody.iphone.movistar                                                    | MovistarMusica AdHoc                                       |
| export_options.provisioningProfiles.com.rhapsody.iphone.movistar.MovistarNotificationServiceExtension               | MovistarNotificationServiceExtension AdHoc                 |
| export_options.provisioningProfiles.com.rhapsody.iphone.movistar.enterprise                                         | Movistar Enterprise In House                               |
| export_options.provisioningProfiles.com.rhapsody.iphone.movistar.enterprise.MovistarNotificationServiceExtension    | MovistarNotificationServiceExtension In House              |
| export_options.provisioningProfiles.com.rhapsody.iphone.${PRODUCT_NAME:rfc1034identifier}3                          | VivoMusica3 AdHoc                                          |
| clean                                                                                                               | true                                                       |
| export_team_id                                                                                                      | 2XLR2SMA94                                                 |
| output_name                                                                                                         | Rhapsody_CoreTeam_iphoneos                                 |
| workspace                                                                                                           | ./Rhapsody.xcworkspace                                     |
| destination                                                                                                         | generic/platform=iOS                                       |
| build_path                                                                                                          | /Users/bserver/Library/Developer/Xcode/Archives/2017-10-24 |
| output_directory                                                                                                    | .                                                          |
| silent                                                                                                              | false                                                      |
| skip_package_ipa                                                                                                    | false                                                      |
| buildlog_path                                                                                                       | ~/Library/Logs/gym                                         |
| skip_profile_detection                                                                                              | false                                                      |
| xcode_path                                                                                                          | /Applications/Xcode.app                                    |
+---------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------+

[11:55:21]: $ set -o pipefail && xcodebuild -workspace ./Rhapsody.xcworkspace -scheme Rhapsody -configuration CoreTeam -destination 'generic/platform=iOS' -archivePath build/Rhapsody-CoreTeam.xcarchive -derivedDataPath derivedData clean archive | tee /Users/bserver/Library/Logs/gym/Napster-Rhapsody.log | xcpretty
_...cut out some mumbo jumbo..._
[12:15:45]: Successfully stored the archive. You can find it in the Xcode Organizer.
[12:15:45]: Generated plist file with the following values:
[12:15:45]: ▸ -----------------------------------------
[12:15:45]: ▸ {
[12:15:45]: ▸   "provisioningProfiles": {
[12:15:45]: ▸     "com.rhapsody.iphone.Rhapsody3": "Rhapsody3 Ad Hoc",
[12:15:45]: ▸     "com.rhapsody.iphone.Rhapsody3.RhapsodyNotificationServiceExtension": "RhapsodyNotificationServiceExtension AdHoc",
_...cut out some irelevant PPs..._
[12:15:45]: ▸   },
[12:15:45]: ▸   "method": "ad-hoc",
[12:15:45]: ▸   "signingStyle": "manual",
[12:15:45]: ▸   "teamID": "2XLR2SMA94"
[12:15:45]: ▸ }
[12:15:45]: ▸ -----------------------------------------
[12:15:45]: $ /usr/bin/xcrun /Library/Ruby/Gems/2.3.0/gems/fastlane-2.62.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/vd/xrhd3z751kq6zxq02vlfdvgr0000gr/T/gym_config20171024-80186-66euqm.plist' -archivePath build/Rhapsody-CoreTeam.xcarchive -exportPath '/var/folders/vd/xrhd3z751kq6zxq02vlfdvgr0000gr/T/gym_output20171024-80186-1u8nma6' -derivedDataPath derivedData 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/vd/xrhd3z751kq6zxq02vlfdvgr0000gr/T/gym_config20171024-80186-66euqm.plist -archivePath build/Rhapsody-CoreTeam.xcarchive -exportPath /var/folders/vd/xrhd3z751kq6zxq02vlfdvgr0000gr/T/gym_output20171024-80186-1u8nma6 -derivedDataPath derivedData
xcodebuild: error: The flag -scheme or -xctestrun is required when specifying -derivedDataPath.
[12:15:46]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.62.1                  |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS11.0.sdk        |
+---------------+-------------------------+

[12:15:46]: ▸     cd /Users/bserver/Jenkins/Home/jobs/Continuum_CI_Matrix_Builder/workspace/SCHEME/Rhapsody
[12:15:46]: ▸     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/local/bin"
[12:15:46]: ▸     /usr/bin/touch -c /Users/bserver/Jenkins/Home/jobs/Continuum_CI_Matrix_Builder/workspace/SCHEME/Rhapsody/derivedData/Build/Intermediates.noindex/ArchiveIntermediates/Rhapsody/BuildProductsPath/CoreTeam-iphoneos/Napster.app.dSYM
[12:15:46]: ▸ ** ARCHIVE SUCCEEDED **
_...cut out some mumbo jumbo..._
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios build |
| BUILD_NUMBER     | 2375      |
+------------------+-----------+
[12:15:46]: Error packaging up the application

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | is_ci                               | 0           |
| 4    | unlock_keychain                     | 0           |
| 5    | xcode_select                        | 0           |
| 6    | increment_build_number              | 6           |
| 7    | clear_derived_data                  | 3           |
| 💥   | gym                                 | 1299        |
+------+-------------------------------------+-------------+

[12:15:46]: fastlane finished with errors

[!] Error packaging up the application
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
Finished: FAILURE
</details>


and here is gym part from fastfile:

```
gym(scheme: scheme,
        configuration: configuration,
        xcargs: '-derivedDataPath ' + derived_data_path(),
        archive_path: "build/#{scheme}-#{configuration}.xcarchive",
        include_bitcode: false,
        export_method: export_method,
        export_options: {
            provisioningProfiles: {
                "com.rhapsody.iphone.Rhapsody3" => rhapsodyPP,
                "com.rhapsody.iphone.Rhapsody3.RhapsodyNotificationServiceExtension" => rhapsodyExtensionPP,
                _...cut out some PPs..._
            }
        },
        clean: true,
        export_team_id: team_id,
        output_name: ipa_name.dup
    )
```

**Comment by ohayon** [comment]
Thanks for sharing that @mijo-gracanin ! One more little question, could you just confirm that these both of those executions on different versions of fastlane were running against the same version of Xcode?

**Comment by mijo-gracanin** [comment]
Yes, both versions were running against the same Xcode version (9.0.1).
