### ISSUE TITLE
Signed APK in Android

### ISSUE THREAD

**Issue by rahul19393** [fastlane/fastlane#10700]
can we make Signed APK in android by using fastlane?

**Comment by ohayon** [comment]
Pinging @fastlane/android, any thoughts on this? I believe this should be possible!

**Comment by joshdholtz** [comment]
@rahul19393 You will have to modify your `build.gradle` file to make a signed APK. Here is a link on how to configure the `release` build type on how to do that - https://developer.android.com/studio/publish/app-signing.html#gradle-sign

After you properly configure you `build.gradle`, your an call something like... 
```rb
gradle(
  task: 'assemble',
  build_type: 'Release'
)
```

**Comment by joshdholtz** [comment]
Closing this for now but let us know if you have any issues with anything! Thanks for fastlaning ❤️

**Comment by rahul19393** [comment]
Thanks for replying but i have an issue,

I have successfully run "fastlane playstore" command for uploading the
android APK on google play store but its not changing the status on google
play console. Its still showing status "Ready to publish".

please find the attachment to see i have run command successfully.



*Thanks & Regards,*
*Rahul pal*
Android Developer | Acumeet Technologies Pvt. Ltd
*Mobile:* (+91) 9650878516
*Mail:* rahul.pal@acumeet.com <soumitra.mishra@acumeet.com>
*Web: *www.acumeet.com

**Comment by joshdholtz** [comment]
@rahul19393 What does your `Fastfile` look like? Do you see the APK version anywhere in Google Play? I can help with any fastlane issues but the Google Play dashboard is not my speciality 😇
