### ISSUE TITLE
Is it possible to check and generate push certificates for multiple bundle identifiers with pem tool? 

### ISSUE THREAD

**Issue by EugeneGoloboyar** [fastlane/fastlane#10701]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have multiple apps (one project, multiple targets per each one).
I want to use pem tool for each app to check push certificates and generate new if needed. 
Is it possible to check for each app's bundle if push certificate is valid (and generate if needed)?
So run one command  - check and generate for each target - bundle id in my case?
Or how to create some script to do this automatically?
Thanks!

**Comment by ohayon** [comment]
Hey @EugeneGoloboyar - yes! This is definitely possible! You should be able to create a Fastfile with multiple calls to `pem` and pass in the different parameters to specify each bundle ID you would wish to check! 🚀  Let us know if we can help any further!!

**Comment by EugeneGoloboyar** [comment]
thanks.
also can I specify smth like this?
So pem file name and folder name will match my Target bundle id?
By omitting '.'?


lane :pushPems do
  # generate pems

  targets_fabric.each do |scheme_name|

    pem -a 'TargetID'  -o 'TargetName.pem' -e 'TargetName' #omitting dots

  end

end

**Comment by EugeneGoloboyar** [comment]
Also as I see generated *.pem doesn't include metadata 
as in the case when I generate *.pem manually

**Comment by ohayon** [comment]
Hey @EugeneGoloboyar check out the docs for how to use `pem` you can pass parameters to it just like a ruby method rather that trying to shell out like that lane you put above. https://docs.fastlane.tools/actions/pem/#pem Let us know if you have any more questions! 🐰

**Comment by EugeneGoloboyar** [comment]
thanks, found output_path and pem_name.
And is it possible to include metada to pem file? 
So *.pem will contain bundle id etc
at least in future?)
