### ISSUE TITLE
Snapshot / Xcode 9 performance hit

### ISSUE THREAD

**Issue by edwinveger** [fastlane/fastlane#10714]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since upgrading to Xcode 9, our snapshots have take a huge time hit. Whereas it took approx. 6 hours to snapshot 400 images (5 screens * 4 devices * 20+ languages), now it takes over 10 hours!
When I look in the terminal, it appears the app is compiled more often than is necessary.
Is this repeated recompilation intended behavior? I thought it might be related to the concurrent simulator setting.

When running the following Snapshot, I can see in the logs that my app is compiled 7 times during this command. That's 2 more than the number of devices I'm snapping on.
```
+----------------------------+--------------------------------------------------------------------+
|                                   Summary for snapshot 2.62.1                                   |
+----------------------------+--------------------------------------------------------------------+
| languages                  | ["th", "vi", "no"]                                                 |
| devices                    | ["iPhone SE", "iPhone 7", "iPhone 7 Plus", "iPhone X", "iPad Air"] |
| scheme                     | Snapshots                                                          |
| workspace                  | ./<redacted>.xcworkspace                                           |
| number_of_retries          | 5                                                                  |
| ios_version                | 11.0.1                                                             |
| clear_previous_screenshots | false                                                              |
| stop_after_first_error     | false                                                              |
| output_directory           | /Users/beheerder/Developer/<redacted>-ios-11/fastlane/screenshots   |
| launch_arguments           | [""]                                                               |
| output_simulator_logs      | false                                                              |
| skip_open_summary          | false                                                              |
| skip_helper_version_check  | false                                                              |
| reinstall_app              | false                                                              |
| erase_simulator            | false                                                              |
| localize_simulator         | false                                                              |
| buildlog_path              | ~/Library/Logs/snapshot                                            |
| clean                      | false                                                              |
| concurrent_simulators      | true                                                               |
| xcode_path                 | /Applications/Xcode.app                                            |
+----------------------------+--------------------------------------------------------------------+
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | nl_NL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.49.0"

default_platform :ios

platform :ios do
  desc "Create framed snapshots using the UI test target."
  lane :snapshots do
    snapshot
    
    # frameit expects the titles for the screenshots in a specific location. This scripts extracts strings and copies them to the correct files.
    sh "php ./screenshots/frameit_get_titles.php"
    
    frameit(silver: true)
  end
  
  desc "Submits all screenshots to the App Store."
  lane :submit_screenshots do
    deliver(skip_screenshots: false, force: true)
  end

  desc "Update CocoaPods and Carthage dependencies."
  lane :dependencies do
    cocoapods
    carthage(platform: "ios")
    carthage(command: "update", dependencies: ["CocoaLumberjack"], platform: "watchOS")
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "<redacted>"

# To select a team for iTunes Connect use
itc_team_id "<redacted>"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| ffi                       | 1.9.18       |
| mustache                  | 0.99.8       |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| redcarpet                 | 3.4.0        |
| rb-fsevent                | 0.10.2       |
| rb-inotify                | 0.9.10       |
| sass-listen               | 4.0.0        |
| sass                      | 3.5.1        |
| jazzy                     | 0.0.14       |
</details>

*generated on:* **2017-10-27**
</details>

**Comment by ohayon** [comment]
Hey @edwinveger - that is definitely not intended, in fact we added support for concurrent simulators a little while back so it should be much faster. Could you share the entire output from your command line so we can see the full context of what's happening?

Thanks! 🚀

**Comment by iliakukharev** [comment]
@edwinveger add `derived_data_path "/Users/beheerder/Developer/<redacted>-ios-11/fastlane/DerivedData"` to your Snapfile and Xcode won't rebuild the app every time. This will help you.

**Comment by edwinveger** [comment]
Thanks for your response! I am running a couple of tests (including adding the derived data path) and will post more information soon.

One thing that _might_ be impacting performance is I'm using the New Build System (Preview). I'm seeing a warning which I discovered is related to this.

> `` ▸ unexpected mutating task ('CodeSign /var/folders/6s/43m3ns7j5p903c89bsd96fcc0000gp/T/snapshot_derived20171031-72865-c4x5vw/Build/Products/Debug-watchsimulator/<red>-Watch.app') with no relation to prior mutator ('Ditto /var/folders/6s/43m3ns7j5p903c89bsd96fcc0000gp/T/snapshot_derived20171031-72865-c4x5vw/Build/Products/Debug-watchsimulator/<red>-Watch.app/<red>-Watch /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator4.0.sdk/Library/Application\ Support/WatchKit/WK') (in target '<red>-Watch')``

I expect this warning to disappear when switching back to the Standard Build System. I'm going to run some comparative tests and I'll inform you about the results.

**Comment by iliakukharev** [comment]
Thanks. Our app build time on my macbook us about 15 mins. So, adding DerivedData path saved me 15 mins * 25 locales, about 6 hours 👍

**Comment by edwinveger** [comment]
I haven't gotten around to the results comparison, but adding `derived_data_path "./fastlane/DerivedData"` to the Snapfile and moving back to the Standard Build System has solved the issue. 
I also added `fastlane/DerivedData` to the .gitignore :)
