### ISSUE TITLE
OCLint configuration file

### ISSUE THREAD

**Issue by TiagoVeloso** [fastlane/fastlane#1071]
I was trying to change more than one rule in the OCLint action.

I was not able to do it within the `Fastfile`.

So I've looked into OCLint and found out that there is the chance to use a `.oclint` file.

I've placed two `.oclint` files, one on my project root, and another on my Fastlane folder.

But when running fast lane on a lane with the `oclint` action, it does not pickup on my `.oclint` file

**Comment by KrauseFx** [comment]
Could you play around with the location of the config file? Maybe put it in the `fastlane` directory of your project.

**Comment by TiagoVeloso** [comment]
I did that.

I've tried in:
`{PROJECT_ROOT}/.oclint`
`{PROJECT_ROOT}/fastlane/.oclint`

Without success.

In the command line OCLint takes an `rc` flag for each rule I want to change. But the action only allows one `rc` flag, It would be nice of the OCLint action could picket on more than one rule configuration.

**Comment by TiagoVeloso** [comment]
I looked at the `OClint` action and found the author.

What do you think @HeEAaD ?

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by masters3d** [comment]
@nschum I saw that implemented this part of OCLint. https://github.com/oclint/oclint/pull/78
I am having a similar issue than this one.  http://stackoverflow.com/questions/38516125/how-to-tell-oclint-to-load-oclint-file-on-traviscl
Do you have any suggestions?
