### ISSUE TITLE
Supporting multiple review screenshot resolutions with in app purchases

### ISSUE THREAD

**Issue by alaincaltieri** [fastlane/fastlane#10713]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
iTunes connect supports multiple screenshot sizes when dealing with review screenshot assets for in app purchases. Spaceship instead requires to use 640x960 resolution (iPhone 4s) which is a bit tedious since the app may not be optimised for that screen resolution and aspect ratio as less and less people use those devices.

It would be nice to have Spaceship support all valid screen resolutions and I'd be happy to do that. I'd need a bit of introduction on how to approach this maybe, since I don't know that much private APIs of iTC. Just pointing out in general how it works and where this call is performed should be enough for getting me started :)

This has been referenced in https://github.com/fastlane/fastlane/issues/9390 and still looks open with the latest fastlane release (tested locally)

What do you think about this?

**Comment by alaincaltieri** [comment]
I actually found my way through, was pretty easy.

Will create a PR soon. I hope this is useful and will find it's way to master 😄

**Comment by earien** [comment]
👍 It would be superuseful... being forced to upload an iphone 4s screenshot is pretty annoying 😄
