### ISSUE TITLE
Deliver error: The application account information was incorrect. (-20207)

### ISSUE THREAD

**Issue by guthook** [fastlane/fastlane#10728]
### New Issue Checklist

- [ √] Updated fastlane to the latest version
- [ √] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ √] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ √] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Deliver fails when trying to upload binary to iTunesConnect, with the following output:

```
[09:28:15]: Uploading binary to iTunes Connect
[09:28:15]: Going to upload updated app to iTunes Connect
[09:28:15]: This might take a few minutes. Please don't interrupt the script.
[09:28:21]: [Transporter Error Output]: The application account information was incorrect. (-20207)
[09:28:21]: Transporter transfer failed.
[09:28:21]: 
[09:28:21]: The application account information was incorrect. (-20207)

```

It's entirely possible this is user error, but as far as I can tell I haven't changed anything about the account in Xcode or Fastlane since the last time I used it successfully, and I don't see any obvious culprits for what application account has the wrong information.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.0-rc1/bin/fastlane   |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0-rc1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.3       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.0.2        |
| openssl                   | 2.0.1        |
</details>

*generated on:* **2017-10-28**
</details>

**Comment by ramnac** [comment]
@guthook - I too faced the same issue, i installed fastlane 2.58.0 and then it worked.

**Comment by robertwijas** [comment]
Thanks @ramnac for the workaround! `2.58.0` worked for me as well.

**Comment by guthook** [comment]
@ramnac Yep, that seems to be working. Thanks much! I'll hope a later version of Fastlane fixes the issue, though :-)

**Comment by eugenpodaru** [comment]
I had the same issue 2 days ago. Tried now with fastlane 2.62.1 and it works. Seems to have been a problem with iTunes Connect

**Comment by ohayon** [comment]
Glad to hear you are all up and running. Would love to hear if the most recent version as of today works for you all. I am going to close this for now as it seems like everyone is working, but let us know if there are more issues! 🚀
