### ISSUE TITLE
[Proposal] Adding self-documenting action name aliases

### ISSUE THREAD

**Issue by mpirri** [fastlane/fastlane#10721]
Back in April, @KrauseFx [proposed](https://github.com/fastlane/fastlane/issues/8806) adding easy-to-remember aliases for _fastlane_ tools. We have decided to revisit this idea, and have written up another proposal for an approach that we could take to make _fastlane_ a bit more approachable for new users. We will soon provide another proposal for steps we can take to get there, and what the tool aliases would be.

Please have a look and let us know if you have any thoughts, ideas, or questions about this proposal.  Thanks!!  🚀 

### Background:

The experience of reading a `Fastfile` for the first time can be confusing and alienating. Here is the top-most example of a `Fastfile` on the [fastlane docs page](http://fastlane.tools/):

```
lane :beta do
  increment_build_number
  gym                       # Build your app
  testflight                # Upload to TestFlight
end

lane :appstore do
  snapshot                  # Generate screenshots for the App Store
  gym                       # Build your app
  deliver                   # Upload the screenshots and the binary to iTunes
  slack                     # Let your team-mates know the new version is live
end
```

To grok this piece of code, a user needs to learn (at least) two things:

* What a `Fastfile` is and what its lanes are all about
* What each of these action names mean (impossible without the comments)

Consider how this might look with more self-documenting core action names:

```
lane :beta do
  increment_build_number
  build                     # Build your app
  testflight                # Upload to TestFlight
end

lane :appstore do
  screenshots               # Generate screenshots for the App Store
  build                     # Build your app
  appstore                  # Upload the screenshots and the binary to iTunes
  slack                     # Let your team-mates know the new version is live
end
```

Even without the comments, it is substantially easier to understand what is going on here.

### Proposal:

Create a set of obvious name aliases for the core tools to improve the new user experience for fastlane and improve the readability of Fastfiles. These aliases will not replace the existing tool names, but act as stand-ins to help people understand the basic concepts of fastlane while deferring until later the requirement that they understand the tool names.

Discussing what the actual name aliases will be is beyond the scope of this document. Consider the existing `pilot`/`testflight` and `deliver`/`appstore` aliases as examples of the style that these new aliases would likely follow.

### Scope:

In order to move quickly and minimize risk, we will create tool aliases and modify only documentation/marketing materials/command output. No namespace changes will be made to the _fastlane_ code base. This will avoid a massive change to the source that could break third party actions, require users to make changes to their `Fastfile`s, and inconvenience contributors by requiring messy pull request rebases.

### Precedents:

Developers are used to the concept of aliasing tools, having one tool call another tool, or tool wrappers. Consider these examples:

* When a user calls `xcodebuild`, `xcodebuild` invokes other tools to complete the build (e.g., `swiftc`, `ditto`, `ibtool`, `dsymutil`). New users of `xcodebuild` can learn what `xcodebuild` is all about without having to worry about what `ditto` is - later they can “level up” their understanding if necessary to see how the tool does what it does.
* File system and command-line aliases are a well-worn concept for software developers - create more logical names for complicated concepts to aid in understandability and readability.

### Advantages to this approach:

* First time _fastlane_ users will not have to struggle with both the complexities of the `Fastfile` and the unusual tool naming scheme right away. This will allow users to be successful more quickly with _fastlane_. Our hypothesis is that this will make it more likely that they will continue to use _fastlane_ past this first interaction.
* `Fastfile`s will become more readable, even for _fastlane_ veterans. We considered making this change to a single core action for quick validation but felt that to realize the full improvement to `Fastfile` readability, it’s necessary to alias all core actions.
* Low effort, low scope, less risk (when compared to a full tool name change).
* Opens the door to more all-emcompassing tool name change efforts later (e.g., changing the tool names in the _fastlane_ source code).
* By leveraging _fastlane_ usage metrics, we can measure adoption of the new names (measure number of users using new names vs. using old names).

### Concerns:

* Without careful messaging, this could actually result in a more confusing _fastlane_ - why does the `build` command reference something called `gym` in it’s output? Why is documentation for `build` command point to something called `gym`? Etc.
* Harder for users to self-diagnose problems - calling `build`, which then crashes, has lots of references to `gym` in the backtrace.
* Confusion around why only core tools have these tool-name aliases.

**Comment by janpio** [comment]
I use fastlane in multi platform projects (Cordova, Ionic), my `Fastfile`s have lanes for both platforms iOS and Android. How would a `build` or `screenshots` action work here?

**Comment by mpirri** [comment]
@janpio While this is not a solved problem, there are several obvious ways to detect the platform that could be used:
* use the `platform` block, if present
* look for the presence of platform-specific tools already in the lane (i.e., keep track of the "last" platform used and assume that platform)
* look at the directory structure and/or config files and make a best guess on that
* look at arguments being passed to the command as a hint
* failing all of the above, throw an error telling the user to add a --ios or --android flag to their `build`/`screenshots` invocation

**Comment by milch** [comment]
I've been a proponent of this idea for so long. The only big issue I see is compatibility with pre-existing Fastfiles. If you throw an error when a `build` lane is declared that's potentially problematic for some users, if you just use the user defined lane instead of the builtin then you increase cognitive load by a lot. 

I'd be more in favour of giving the default actions more verbose, descriptive names to potentially avoid this issue, e.g. `gym` -> `build_ios_app`, `match` -> `sync_apple_developer_profile`, `snapshot` -> `take_ios_screenshots`, `screengrab` -> `take_android_screenshots` and so on, at least for the time being. Less magic is better in this case, best not to do any guesswork or the user could end up with something they didn't want. 

> Without careful messaging, this could actually result in a more confusing fastlane - why does the build command reference something called gym in it’s output? Why is documentation for build command point to something called gym? Etc.

I don't think this would be a huge concern, developers are usually well aware of abstractions built on other pre-existing technologies. Besides, there is an unexpected advantage hidden in this: think about the searchability of `gym failed because...` and `build failed because...`. Apple does this intentionally in some of their frameworks - assign arbitrary names to ordinary functions that could potentially crash so that it is easier to search for them online.

**Comment by mpirri** [comment]
@milch So, we do have a system like this already - you can define a lane `pilot` (for instance), and then when you execute `fastlane pilot` you'll get this warning:
```
[14:45:03]: Lane name 'pilot' should not be used because it is the name of a fastlane tool
[14:45:03]: It is recommended to not use 'pilot' as the name of your lane
```
(but the lane will execute successfully after that)

We could improve this messaging to say something like "`build` is now the name of a `fastlane` tool; it is recommended to no longer use a lane with this name" and maybe even give the user an option such as "you can disable the new actions and this warning by setting the environment variable [...]".

> I'd be more in favour of giving the default actions more verbose, descriptive names to potentially avoid this issue [...]

We discussed the possibility of using more verbose name. One way we found that this fell down was with a tool like `pilot`, which can both upload a binary OR add a tester to TestFlight.

So, `pilot upload` becomes `upload_to_testflight upload`, which is okay (if a bit of a mouthful), but `pilot add` becomes `upload_to_testflight add`, which is confusing and would probably require a second alias to the `pilot` tool.

**Comment by mpirri** [comment]
This proposal has been superseded by the action name changes that were introduced as #10939.  Thanks for your feedback everyone!  🚀
