### ISSUE TITLE
Crash when using "fastlane <lane-name> --env <environment>" in the command line

### ISSUE THREAD

**Issue by francesco-puglisi** [fastlane/fastlane#1072]
This is the following message printed in the terminal.

>Successfully submitted a crash report. If this is a problem with one of the tools specifically,
>please submit an issue on GitHub and attach the following number to it: '1c3bda5c456a6f043e3fde4a9582a32f'
>The crash report has been stored locally '/tmp/sentry_1c3bda5c456a6f043e3fde4a9582a32f.json'"

**Comment by KrauseFx** [comment]
```
RuntimeError: [31mSyntax error in your Fastfile on line 17: Fastfile:17: syntax error, unexpected tLABEL, expecting keyword_end
  xcodebuild() sdk: "iphoneos", configuration: "...
```

Your `Fastfile` is broken, please post it

**Comment by francesco-puglisi** [comment]
Thanks for your reply. I realised that the error report is stored locally. The error message points at this line:
`gym -s ENV["BUILD_SCHEME"]`

**Comment by francesco-puglisi** [comment]
I realised I should have used `gym(scheme: ENV["BUILD_SCHEME"])` instead. Now it works. Sorry, I have never worked with Ruby before. Thanks for maintaining this awesome tool.

**Comment by suchita-sindhi-bs** [comment]
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '79d6abb92fc876eab296f5c9b0d089e7'
The crash report has been stored locally '/tmp/sentry_79d6abb92fc876eab296f5c9b0d089e7.json'

**Comment by vpolouchkine** [comment]
@suchita-sindhi-bs Please open a new issue and post your Fastfile. Thanks!
