### ISSUE TITLE
Unable to create certs for new iOS app taget

### ISSUE THREAD

**Issue by samuelcastro** [fastlane/fastlane#10725]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to update certs for a new set of mobile apps (dev and qa) that I just created with `fastlane ios create`, now I'd like to generate new certs for these envs with: `fastlane ios certs` however I'm getting this message:

```
[16:49:10]: Certificate 'XYZ' (stored in your git repo) is not available on the Developer Portal
[16:49:10]: for the user samuelcastrosilva@gmail.com
[16:49:10]: Make sure to use the same user and team every time you run 'match' for this
[16:49:10]: Git repository. This might be caused by revoking the certificate on the Dev Portal
[16:49:11]: To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match
```

As suggested I'm trying to clean up my certs with `fastlane match nuke development`, but for some reason, after run it I'm getting stuck in this process:

```
[16:50:19]: Cloning remote git repo...
```

Am I missing something? 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

 ✘  samuelcastro@Samuels-MacBook-Pro  ~/Projects/Integritas/hippo/client   mobile-environments  fastlane match nuke development
[16:53:14]: Successfully loaded '/Users/samuelcastro/Projects/Integritas/hippo/client/fastlane/Matchfile' 📄

+-----------------------+--------------------------------------+
|         Detected Values from './fastlane/Matchfile'          |
+-----------------------+--------------------------------------+
| git_url               | git@github.com:MyRepo/project  |
|                       | rts.git                              |
| type                  | development                          |
| app_identifier        | ["com.bundle.id",                  |
|                       | "bundle.id.staging"]           |
| team_id               | TEAM_ID                           |
| username              | samuelcastrosilva@gmail.com          |
| clone_branch_directly | master                               |
+-----------------------+--------------------------------------+

[16:53:14]: Cloning remote git repo...

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

import "./fastlane-cordova/fastlane/Fastfile"

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
itc_team_id "118621158"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.2        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-10-27**
</details>

**Comment by ohayon** [comment]
Hmmm, @samuelcastro can you verify that you can clone that repo to your machine manually? Most of our git commands just shell out to your `git` executable, so everything should be working as expected. Would you mind sharing the output of the command with `--verbose`? Thanks! 🚀

**Comment by samuelcastro** [comment]
@ohayon Yes I'm able to clone the repo manually. And this is the `--verbose` output:

```
INFO [2017-11-02 09:11:30.38]: Cloning remote git repo...
INFO [2017-11-02 09:11:30.38]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:MyRepo/my-repo-certs.git' '/var/folders/xv/5by7xn1d2h1dvmw1c9lb4nn80000gn/T/d20171102-43408-1ah8pis' -b master --single-branch
INFO [2017-11-02 09:11:30.39]: ▸ Cloning into '/var/folders/xv/5by7xn1d2h1dvmw1c9lb4nn80000gn/T/d20171102-43408-1ah8pis'...
```

**Comment by samuelcastro** [comment]
@ohayon Any idea about what might be happening here?
