### ISSUE TITLE
Pass what to test with build - pilot

### ISSUE THREAD

**Issue by tejas-ardeshna** [fastlane/fastlane#10739]
We are release build with Fastlane, It's quite easy and very time-saving. But I have one question, can we pass "What to test" info for a build with a pilot? http://prntscr.com/h3w9vv

**Comment by tejas-ardeshna** [comment]
@allu22 I have skip_waiting_for_build_processing = true, so will changelog works with it?

**Comment by ohayon** [comment]
Yup @tejas-ardeshna it should work just fine!
