### ISSUE TITLE
IOS Relase/Snapshot Fail

### ISSUE THREAD

**Issue by eyalabadi98** [fastlane/fastlane#10733]
Hello! When I run "fastlane snapshot -i 11.0.1" I get an error:

`2017-10-29 16:50:32.108 xcodebuild[1050:9791] Error Domain=IXUserPresentableErrorDomain Code=2 "This app was unable to be installed." UserInfo={NSLocalizedDescription=This app was unable to be installed., NSUnderlyingError=0x7fa8de550d20 {Error Domain=MIInstallerErrorDomain Code=3 "Could not access item to be installed at /Users/eyalabadi/Library/Developer/CoreSimulator/Devices/C96FFEE6-D07C-48D3-9BF3-1D600883C104/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/65200308-D723-48DF-B7B8-6B687FA3BA2B/MG16.app" UserInfo={NSUnderlyingError=0x7fa8ddaca4b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={SourceFileLine=629, NSLocalizedDescription=lstat of /Users/eyalabadi/Library/Developer/CoreSimulator/Devices/C96FFEE6-D07C-48D3-9BF3-1D600883C104/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/65200308-D723-48DF-B7B8-6B687FA3BA2B/MG16.app failed: No such file or directory, FunctionName=-[MIFileManager itemExistsAtURL:error:]}}, LegacyErrorString=PackageInspectionFailed, FunctionName=-[MobileInstallationHelperService stageItemAtURL:completion:], SourceFileLine=379, NSLocalizedDescription=Could not access item to be installed at /Users/eyalabadi/Library/Developer/CoreSimulator/Devices/C96FFEE6-D07C-48D3-9BF3-1D600883C104/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/65200308-D723-48DF-B7B8-6B687FA3BA2B/MG16.app}}}
INFO [2017-10-29 16:50:32.11]: ▸ 2017-10-29 16:50:32.109 xcodebuild[1050:9791] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
INFO [2017-10-29 16:50:32.11]: ▸ 2017-10-29 16:50:32.116 xcodebuild[1050:15756] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fa8dd984940>
INFO [2017-10-29 16:50:35.34]: ▸ 2017-10-29 16:50:35.346 xcodebuild[1050:9791] Error Domain=IXUserPresentableErrorDomain Code=2 "This app was unable to be installed." UserInfo={NSLocalizedDescription=This app was unable to be installed., NSUnderlyingError=0x7fa8ddb4ca00 {Error Domain=MIInstallerErrorDomain Code=3 "Could not access item to be installed at /Users/eyalabadi/Library/Developer/CoreSimulator/Devices/028BC4F9-520F-484E-8A0D-E67AF3F34C67/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/12DEA133-F4DB-4155-8088-A9A4E1B265EA/MG16.app" UserInfo={NSUnderlyingError=0x7fa8ddd22c50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={SourceFileLine=629, NSLocalizedDescription=lstat of /Users/eyalabadi/Library/Developer/CoreSimulator/Devices/028BC4F9-520F-484E-8A0D-E67AF3F34C67/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/12DEA133-F4DB-4155-8088-A9A4E1B265EA/MG16.app failed: No such file or directory, FunctionName=-[MIFileManager itemExistsAtURL:error:]}}, LegacyErrorString=PackageInspectionFailed, FunctionName=-[MobileInstallationHelperService stageItemAtURL:completion:], SourceFileLine=379, NSLocalizedDescription=Could not access item to be installed at /Users/eyalabadi/Library/Developer/CoreSimulator/Devices/028BC4F9-520F-484E-8A0D-E67AF3F34C67/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/12DEA133-F4DB-4155-8088-A9A4E1B265EA/MG16.app}}}
INFO [2017-10-29 16:50:35.34]: ▸ 2017-10-29 16:50:35.346 xcodebuild[1050:9791] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
INFO [2017-10-29 16:50:35.34]: ▸ 2017-10-29 16:50:35.347 xcodebuild[1050:14129] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fa8ddc4f480>
INFO [2017-10-29 16:50:35.35]: ▸ Testing failed:
INFO [2017-10-29 16:50:35.35]: ▸ Test target MG16Tests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
INFO [2017-10-29 16:50:35.35]: ▸ ** TEST FAILED **
`

After this, it gets stuck on signing, and basically freezers my computer

### New Issue Checklist

- [y ] Updated fastlane to the latest version
- [y ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [y ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [y ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Not sure what to put here. I posted my error at the top

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
	match(
	type: “appstore”,
	git_url: “takenout”
	)
	
    gym(
	
	scheme: "MG16”,
	
) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    snapshot
	ios_version '11.0.1'
	version
	match(
	type: “appstore”,
	git_url: “https://abadieyal@bitbucket.org/abadieyal/codesigning.git”
	unlock_keychain
	keychain_password: “abadi”
	)
	match
	unlock_keychain
	keychain_password: “abadi”
	
  	gym
  	
  	pilot
    gym(scheme: "MG16") # Build your app - more options available
    deliver(force: true)

    frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "hidden" # The bundle identifier of your app
apple_id "hidden" # Your Apple email address

team_id "hidden" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| slack-notifier        | 1.5.1        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.2.8        |
| terminal-notifier     | 1.8.0        |
| unicode-display_width | 1.3.0        |
| terminal-table        | 1.8.0        |
| plist                 | 3.3.0        |
| CFPropertyList        | 2.3.5        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.5.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| highline              | 1.7.8        |
| commander-fastlane    | 4.4.5        |
| unf_ext               | 0.0.7.4      |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| dotenv                | 2.2.1        |
| bundler               | 1.15.3       |
| faraday_middleware    | 0.12.2       |
| json                  | 2.1.0        |
| io-console            | 0.4.6        |
| excon                 | 0.59.0       |
| openssl               | 2.0.3        |
| faraday               | 0.13.1       |
| little-plugger        | 1.1.4        |
| logging               | 2.2.2        |
| memoist               | 0.16.0       |
| os                    | 0.9.6        |
| googleauth            | 0.6.1        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| signet                | 0.8.1        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
</details>

*generated on:* **2017-10-29**
</details>

**Comment by ohayon** [comment]
Hey @eyalabadi98 could you share the xcodebuild command that fastlane spits out when it is trying to run your app for snapshot? I'm curious if that command will work for you when you run it manually! 🐙 🚀

**Comment by eyalabadi98** [comment]
I have decided to just upload the builds manually as it was giving me too many troubles :/. ill get back to you on this output
