### ISSUE TITLE
git_commit don't allow to add paths with space

### ISSUE THREAD

**Issue by sp3esu** [fastlane/fastlane#1073]
Hi.

During my build process I'm trying to commit few files and one of them is in "Supporting files" folder.
For command:
```
git_commit(
          path: [
                 SOME_OTHER_FILES_HERE,
        	  "./Extensions/Watch/Extension/Supporting Files/Info.plist",
        	  SOME_OTHER_FILES_HERE
          ],
          message: "Commit message"
)
```
git_commit gives me and error like: 
```
error: pathspec './Extensions/Watch/Extension/Supporting' did not match any file(s) known to git.
error: pathspec 'Files/Info.plist' did not match any file(s) known to git.
```

If I would like to do like this:
```
git_commit(
          path: [
                 SOME_OTHER_FILES_HERE,
        	  "./Extensions/Watch/Extension/Supporting\\ Files/Info.plist",
        	  SOME_OTHER_FILES_HERE
          ],
          message: "Commit message"
)
```
it will give me:
```
git_commit.rb:38:in `block (2 levels) in available_options': Couldn't find file at path './Extensions/Watch/Extension/Supporting\ Files/Info.plist' (RuntimeError)
```

Can you help?

Regards,
Gregor

**Comment by asfalcone** [comment]
@sp3esu I wonder if this would be handled properly if we added `.shellescaped` to [paths](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/git_commit.rb#L11) like we do in [git_helper](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/helper/git_helper.rb#L5)

**Comment by sp3esu** [comment]
I think this can help (but I'm not a Ruby ninja) ;-)
