### ISSUE TITLE
'invalid byte sequence in UTF-8' when using sh .But it worked by using system.

### ISSUE THREAD

**Issue by MooYoo** [fastlane/fastlane#10734]
I searched for issues but found nothing worked for me. 
But It worked when I use 'system' instead of 'sh'.

### Issue Description

`

    desc "Upload dSYM to bugly."
    lane :bugly do
        bundleShortVersion = get_info_plist_value(path: "./xxx/xxx-Info.plist", key: "CFBundleShortVersionString")
	sh("./uploadDSYM.sh " + bundleShortVersion)
    end

`

I run 'fastlane bugly' but got error.
But It worked when I use 'system' instead of 'sh'.

+-----------------------------------+-----------+
|                 Lane Context                  |
+-----------------------------------+-----------+
| DEFAULT_PLATFORM                  | ios       |
| PLATFORM_NAME                     | ios       |
| LANE_NAME                         | ios bugly |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 5.4       |
+-----------------------------------+-----------+
[11:08:00]: invalid byte sequence in UTF-8

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | Verifying required   | 0           |
|      | fastlane version     |             |
| 2    | default_platform     | 0           |
| 3    | get_info_plist_value | 0           |
| 💥   | ./uploadDSYM.sh 5.4  | 5           |
+------+----------------------+-------------+

[11:08:00]: fastlane finished with errors
^C/Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `initialize': Interrupt
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/mooyoo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/crash_reporter/crash_reporter.rb:91:in `send_report'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/crash_reporter/crash_reporter.rb:30:in `report_crash'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:156:in `rescue_unknown_error'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:123:in `rescue in run!'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:126:in `run!'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.62.1/bin/fastlane:20:in `<top (required)>'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mooyoo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

**Comment by ohayon** [comment]
Hey @MooYoo! apologies for the issues you are having. It looks like this could be because your LANG environment variable is set to a Chinese language, could you try prefacing your command with `LANG=en_US.UTF-8` and see if that works? We should support all LANGs so there definitely is an issue but that hopefully will get you working quickly! 🚀
