### ISSUE TITLE
"You passed invalid parameters to 'resign'" when resign

### ISSUE THREAD

**Issue by MooYoo** [fastlane/fastlane#10737]
### Issue Description

Got errors when run 'fastlane resignToAdHoc'.

> [16:41:42]: --- Step: resign ---
[16:41:42]: --------------------
[16:41:42]: Error setting value '{"com.LiMei.MeiJiaLove"=>"~/Library/MobileDevice/Provisioning Profiles/03d99751-3f2c-4aeb-b155-19a1a003da9d.mobileprovision", "com.LiMei.MeiJiaLove.NotificationService"=>"~/Library/MobileDevice/Provisioning Profiles/5aee9fe1-4657-47b5-a3fc-8caf1de543ad.mobileprovision"}' for option 'provisioning_profile'
[16:41:42]: You passed invalid parameters to 'resign'.
[16:41:42]: Check out the error below and available options by running `fastlane action resign`
[16:42:42]: An error occurred while executing the `error` block:
[16:42:42]: no implicit conversion of Symbol into String
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios resignToAdHoc |
+------------------+-------------------+
[16:42:42]: Couldn't find provisiong profile at path '~/Library/MobileDevice/Provisioning Profiles/03d99751-3f2c-4aeb-b155-19a1a003da9d.mobileprovision'
+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | resign              | 0           |
+------+---------------------+-------------+
[16:42:42]: fastlane finished with errors
[!] Couldn't find provisiong profile at path '~/Library/MobileDevice/Provisioning Profiles/03d99751-3f2c-4aeb-b155-19a1a003da9d.mobileprovision'

My Fastfile:
`

    desc "Resign to adHoc."
    lane :resignToAdHoc do
        resign(
            ipa: "./build/tf/xxx.ipa",
            signing_identity: "xxx",
            provisioning_profile: {
                "com.xxx.xxx"=>"~/Library/MobileDevice/Provisioning\ Profiles/03d99751-3f2c-4aeb-b155-19a1a003da9d.mobileprovision",
                "com.xxx.xxx.NotificationService"=>"~/Library/MobileDevice/Provisioning\ Profiles/5aee9fe1-4657-47b5-a3fc-8caf1de543ad.mobileprovision"
            }
        )
    end

`

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.62"
default_platform :ios
build_time = Time.now.strftime('%Y%m%d%H%M%S')
branch_name = ENV["BRANCH_NAME"]
platform :ios do

####before_all######################################################################

    before_all do
        ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    end

####discard_Pull####################################################################

    desc "Reset and git pull."
    lane :discard_pull do
        reset_git_repo(
            force: true,
        )
        git_pull
    end

####set_version#####################################################################

    desc "Set bundle version."
    lane :set_version do
        set_info_plist_value(path: "./Meijiabang/Meijiabang-Info.plist", key: "CFBundleVersion", value: build_time)
    end

####pod_install#####################################################################

    desc "Pod install."
    lane :pod_install do
        cocoapods(repo_update: true)
    end

####matchAppstore###################################################################

    desc "Match App-Store certificates and provisioning profile."
    lane :matchAppstore do
        match(type: "appstore", readonly: true)
    end

####gym_release#####################################################################

    desc "GYM release ipa."
    lane :gym_release do
        gym(
            workspace: "Meijiabang.xcworkspace",
            configuration: "Release",
            scheme: "Meijiabang",
            clean: true,
            output_directory: "./build/tf",
            codesigning_identity: "iPhone Distribution: MooYoo (Guangzhou) Technology Co., Ltd. (RML58CN62D)",
            include_bitcode: false,
            export_options: {
                export_method: "app-store",
                provisioningProfiles: { 
                    "com.LiMei.MeiJiaLove": "match AppStore com.LiMei.MeiJiaLove",
                    "com.LiMei.MeiJiaLove.NotificationService": "match AppStore com.LiMei.MeiJiaLove.NotificationService"
                }
            }
        )
    end

####resignToAdHoc###################################################################

    desc "Resign to adHoc."
    lane :resignToAdHoc do
        resign(
            ipa: "./build/tf/Pods_Meijiabang.ipa",
            signing_identity: "iPhone Distribution: MooYoo (Guangzhou) Technology Co., Ltd. (RML58CN62D)",
            provisioning_profile: {
                "com.LiMei.MeiJiaLove"=>"~/Library/MobileDevice/Provisioning Profiles/",
                "com.LiMei.MeiJiaLove.NotificationService"=>"~/Library/MobileDevice/Provisioning Profiles/"
            }
        )
    end

####tf_ipa##########################################################################

    desc "Deploy ipa to the TestFight"
    lane :tf_ipa do
        testflight(
            ipa: "./build/tf/Pods_Meijiabang.ipa",
            skip_submission: true,
            skip_waiting_for_build_processing: true
        )
    end

####deliver_ipa#####################################################################

    desc "Deploy ipa to the AppStore."
    lane :deliver_ipa do
        deliver(
            ipa: "./build/tf/Pods_Meijiabang.ipa",
            force: true
        )
    end

####push_tag########################################################################

    desc "Push Tag."
    lane :push_tag do
        bundleVersion = get_info_plist_value(path: "./Meijiabang/Meijiabang-Info.plist", key: "CFBundleVersion")
        bundleShortVersion = get_info_plist_value(path: "./Meijiabang/Meijiabang-Info.plist", key: "CFBundleShortVersionString")
        add_git_tag(
            tag: "#{bundleShortVersion}/#{bundleVersion}"
        )
        push_git_tags
    end

####bugly###########################################################################

    desc "Upload dSYM to bugly."
    lane :bugly do
        bundleShortVersion = get_info_plist_value(path: "./Meijiabang/Meijiabang-Info.plist", key: "CFBundleShortVersionString")
	system("./uploadDSYM.sh " + bundleShortVersion)
    end

####sendSuccessToDingding###########################################################

    desc "Send message to 钉钉 when succeed."
    lane :sendSuccessToDingding do
        bundleVersion = get_info_plist_value(path: "./Meijiabang/Meijiabang-Info.plist", key: "CFBundleVersion")
        bundleShortVersion = get_info_plist_value(path: "./Meijiabang/Meijiabang-Info.plist", key: "CFBundleShortVersionString")
	sh("./dingdingSucceed.sh" + " " + bundleShortVersion + " " + bundleVersion)
    end

####tf##############################################################################

    desc "Deploy a new version to the TestFight"
    lane :tf do
	discard_pull()
        set_version()
        pod_install()
        gym_release()
        tf_ipa()
	sendSuccessToDingding()
        push_tag()
    end

####after_all#######################################################################

    after_all do |lane|
    # This block is called, only if the executed lane was successful    
    end

####error###########################################################################

    error do |lane, exception|
	sh("./dingdingFailed.sh " + lane + " " + exception)
    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.LiMei.MeiJiaLove" # The bundle identifier of your app
apple_id "mooyooorg@gmail.com" # Your Apple email address

team_id "RML58CN62D"  # Developer Portal Team ID

itc_team_id "2114361"
itc_team_name "MooYoo (Guangzhou) Technology Co., Ltd."

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| executable-hooks           | 1.3.2        |
| bundler-unload             | 1.0.2        |
| rubygems-bundler           | 1.4.4        |
| bundler                    | 1.15.4       |
| io-console                 | 0.4.5        |
| CFPropertyList             | 2.3.5        |
| i18n                       | 0.8.6        |
| minitest                   | 5.10.3       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.3        |
| activesupport              | 4.2.9        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| cork                       | 0.3.0        |
| nap                        | 1.1.0        |
| open4                      | 1.3.4        |
| claide-plugins             | 0.9.2        |
| fuzzy_match                | 2.0.4        |
| cocoapods-core             | 1.3.1        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.3        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| netrc                      | 0.7.8        |
| cocoapods-trunk            | 1.2.0        |
| cocoapods-try              | 1.1.0        |
| escape                     | 0.0.4        |
| fourflusher                | 2.0.1        |
| gh_inspector               | 1.0.3        |
| molinillo                  | 0.5.7        |
| ruby-macho                 | 1.1.0        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.3        |
| cocoapods                  | 1.3.1        |
| colored                    | 1.2          |
| highline                   | 1.7.8        |
| commander-fastlane         | 4.4.5        |
| multipart-post             | 2.0.0        |
| faraday                    | 0.13.1       |
| faraday-http-cache         | 1.3.1        |
| git                        | 1.3.0        |
| kramdown                   | 1.14.0       |
| sawyer                     | 0.8.1        |
| octokit                    | 4.7.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| danger                     | 5.3.4        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| dotenv                     | 2.2.1        |
| excon                      | 0.59.0       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.12.2       |
| fastimage                  | 2.1.0        |
| jwt                        | 2.1.0        |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.12.2       |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.1        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| google-api-client          | 0.13.6       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.3.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| slack-notifier             | 1.5.1        |
| terminal-notifier          | 1.8.0        |
| tty-screen                 | 0.5.1        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-versioning | 0.3.0        |
| psych                      | 2.2.4        |
</details>

*generated on:* **2017-10-30**
</details>

**Comment by ohayon** [comment]
Hey @MooYoo would you mind running that command with `--verbose` and sharing the output? Would be helpful to see the full stack trace 🚀
