### ISSUE TITLE
Is it possible to add parameter "bundle_id" to upload_symbols_to_crashlytics? 

### ISSUE THREAD

**Issue by EugeneGoloboyar** [fastlane/fastlane#10749]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi, I have multiple-target project. One project - multiple apps.
I want to create a lane for download/upload dsyms.
It should run for each target - each app.
But I cannot specify bundle_id for upload_symbols_to_crashlytics
So currently I download ALL dSYMs in loop for each app and then upload ALL as one action.

Is it possible to upload dSYM for particular bundle_id?

```ruby
lane :refresh_dsyms do

  targets_dsym.each do |scheme_name, bundle_identifier|
    download_dsyms(app_identifier: bundle_identifier, team_id: "XXXXX") # Download dSYM files from iTC
  end

  # good to have bundle_id here as argument to separate upload for each taget 
  upload_symbols_to_crashlytics(api_token: "XXXX") # Upload them to Crashlytics
  clean_build_artifacts # Delete the local dSYM files

  slack(
      message: "#{scheme_name}: dSYM files successfully uploaded to Fabric!",
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Target" => scheme_name,
        "Build Date" => Time.new.to_s
      }
    )


end
```

**Comment by ohayon** [comment]
Hey @EugeneGoloboyar - you should be able to pass a `:dsym_path` option to `upload_symbols_to_crashlytics` and that way you can do them one by one. Let us know if that works for you! 🆙

**Comment by EugeneGoloboyar** [comment]
Thanks, could you also prompt is it possible to create directories automatically?
I want to do smth like this - to create folder for each target scheme_name

sh 'mkdir -pv dSYMs/"{scheme_name}"'

**Comment by ohayon** [comment]
I think the best way at the moment would be to iterate through paths within the directory you are referring to.
