### ISSUE TITLE
User doesn't have enough permission for user_details_data

### ISSUE THREAD

**Issue by SebastianThiebaud** [fastlane/fastlane#10744]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `fastlane init`, after entering my email and password, 2 teams are listed (app store & in house). I select the in house team and get this error:

```
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) ******** "****** Inc" (Company/Organization)
2) ******** "****** Incorporated" (In-House)
2

[!] Insufficient permissions for your Apple ID:
	User ****.****@****.com doesn't have enough permission for the following action: user_details_data
```

I've been searching for a while what `user_details_data` refers to, without success. I'm also using an  admin account.

Thank you.

#### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

#### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

#### fastlane files:

**No Fastfile found**

**No Appfile found**

#### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

#### Loaded fastlane plugins:

**No plugins Loaded**

**Comment by ohayon** [comment]
Hey @SebastianThiebaud - do you happen to know what your role is on iTC?

**Comment by SebastianThiebaud** [comment]
@ohayon I have no role (no account) on iTC since I only want to deal with the In-House team (the one I selected).

**Comment by ohayon** [comment]
Ah, my apologies! That makes sense. Do you know what your role is for the dev portal? Are you an agent or admin?

**Comment by SebastianThiebaud** [comment]
I'm an admin

**Comment by SebastianThiebaud** [comment]
Tested with `2.63.0` too, error is still happening.

I don't know if it's related, but it takes approximately 2 or 3 minutes to see the error message on screen after selecting the team.

**Comment by SebastianThiebaud** [comment]
I also get random errors like: 
```
/Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:379:in `block in inflate_adapter': stack level too deep (SystemStackError)
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:411:in `call_block'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:402:in `<<'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:106:in `read'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:401:in `read'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:290:in `block in read_body_0'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:261:in `inflater'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	 ... 8723 levels...
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.63.0/bin/fastlane:20:in `<top (required)>'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/sebastianthiebaud/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by ohayon** [comment]
Oh interesting. Thanks for that stack trace @SebastianThiebaud. We have seen that issue a bit over the past week or two, I plan on digging in to that today to see what's going on.

In the meantime, you could create your Fastfile manually in order to work around this issue. I'll follow up here with what I find related to to that login issue.

**Comment by SebastianThiebaud** [comment]
Alright, sounds good. Thank you @ohayon

**Comment by gtatgh** [comment]
Same error after `fastlane produce` creates new app with an admin account.

**Comment by jaredballou** [comment]
I'm having a similar issue. We installed Fastlane and set the Bash environment according to the iOS Setup documentation. When running "fastlane init" inside our project, I get to select a scheme, then enter credentials. With my Apple ID, it immediately bails out with this error. I had another person in our team try it, and he was able to select the team ID, and then had a similar error for the same permission. Could this have to do with the fact that we're using non-production teams/keys? The other developer is a member of a production team, I believe our accounts have the same permissions in  Apple Developer Portal.

**Comment by s-hocking** [comment]
I'm having the same issue. I get to enter my Apple ID, then immediately receive the "Insufficient permissions for your Apple ID" error. Don't get the option to enter my password. I'm an agent on an Enterprise team.

**Comment by ScottBuchanan** [comment]
Same issue after running `fastlane init` and entering my Apple ID. I'm on an In-House / Enterprise account with an Agent role. I was prompted to enter my password the first time, but not on subsequent trys.

**Comment by kaqijiang** [comment]
I'm an agent on an Enterprise team. show me doesn't have enough permission for the following action: user_details_data

**Comment by ohayon** [comment]
Hey @kaqijiang this sounds like it might be a different issue. Would you mind sharing the output from your command line when you run the command with `--verbose` so we can have some more context? Thanks! 🚀

**Comment by Kennouf** [comment]
Hey, 

So I'm having the same issue, I am an admin of the team but I don't have a role in iTC, and fastlane init won't pass.

Here is the stack for my error : 

`/Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:679:in `raise_insuffient_permission_error!': [!] Insufficient permissions for your Apple ID: (Spaceship::Client::InsufficientPermissions)
	User <my email> doesn't have enough permission for the following action: user_details_data
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:658:in `detect_most_common_errors_and_raise_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:631:in `parse_response'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:189:in `user_details_data'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:134:in `teams'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/tunes/tunes_client.rb:67:in `select_team'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/setup/setup_ios.rb:228:in `detect_if_app_is_available'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/setup/setup_ios.rb:34:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/setup/setup.rb:29:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.68.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'`

**Comment by taquitos** [comment]
Ugh, yeah,  iTC permissions vs Dev Center permissions are so annoying. Thank you for posting a follow up, this should help others who search for help on this sort of thing 🎉

**Comment by EricZinda** [comment]
I'm having the same issue trying to add a beta user to TestFlight using fastlane pilot add or find or basically anything at this point.  Worked great for the first 24 hours.  I went and removed the cookie in case that was the issue but it didn't work.  Here's the --verbose output (replaced personal information with XXXXXX:

Erics-MBP:fastlane XXXXXXX$ fastlane pilot find XXXXXXX --verbose
[10:53:24]: fastlane detected a Gemfile in the current directory
[10:53:24]: however it seems like you don't use `bundle exec`
[10:53:24]: to launch fastlane faster, please use
[10:53:24]: 
[10:53:25]: $ bundle exec fastlane pilot find XXXXXXX --verbose
[10:53:25]: 
[10:53:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/XXXXXXX/Enlistments/ExospeciesSrc/native/fastlane/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/XXXXXXX/Enlistments/ExospeciesSrc/native/fastlane/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/XXXXXXX/Enlistments/ExospeciesSrc/native/fastlane/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/XXXXXXX/Enlistments/ExospeciesSrc/native/fastlane/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/XXXXXXX/Enlistments/ExospeciesSrc/native/fastlane/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/XXXXXXX/Enlistments/ExospeciesSrc/native/fastlane/fastlane/Appfile'
-------
WARN [2018-03-13 10:53:25.42]: To not be asked about this value, you can specify it using 'username'
 [2018-03-13 10:53:25.42]: Your Apple ID Username: XXXXXXX
INFO [2018-03-13 10:53:31.36]: Login to iTunes Connect (XXXXXXX)
Two Factor Authentication for account 'XXXXXXX' is enabled
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: XXXXXXX
Requesting session...
ERROR [2018-03-13 10:53:55.88]: User XXXXXXX doesn't have enough permission for the following action: user_details_data
/Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!': [!] Some operations failed: User XXXXXXX doesn't have enough permission for the following action: user_details_data (FastlaneCore::Interface::FastlaneError)
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/pilot/lib/pilot/commands_generator.rb:44:in `handle_multiple'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/pilot/lib/pilot/commands_generator.rb:125:in `block (2 levels) in run'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
	from /Users/XXXXXXX/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.85.0/bin/fastlane:20:in `<top (required)>'
	from /Users/XXXXXXX/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/XXXXXXX/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by joshdholtz** [comment]
@SebastianThiebaud Heyyyyy 👋 Were you able to get things figured out with this issue? Asking because its been awhile and iTC stuff has changed a lot of hoping things worked out 😊

**Comment by emilio-martinez** [comment]
This seems to be an issue if the user doesn't have enough permission access in iTunes Connect

**Comment by EricZinda** [comment]
No, it worked fine for me when I use the account directly on ITC to do this.  The account has full permissions to everything and is an admin.

**Comment by EricZinda** [comment]
Nope, this was just a few days ago that it failed.

**Comment by joshdholtz** [comment]
Hey everyone 👋 I was able to duplicate this and this is 100% an issue when _fastlane_ is trying setup for something that uses iTC permissions (like uploading screenshots) when the selected account does not have those permissions. 

This is not something that _fastlane_ can actually solve as its a permissions issue within iTC but we did rework the "init" process a few months ago (you can see in the output below). If a permissions issue occurs, it will redirect users to setting up the `Fastfile` manually.

I **do think** the error should be a little more user friendly / descriptive. I will be working on a way to the permission error be a more helpful on what system the permission is actually looking on.

```
[07:50:23]: --------------------
[07:50:23]: fastlane init failed
[07:50:23]: --------------------
[07:50:23]: ["Insufficient permissions for your Apple ID:", "User josh+test@email doesn't have enough permission for the following action: user_details_data"]
[07:50:23]: Something failed while running `fastlane init`
[07:50:23]: Tried using Apple ID with email 'josh+test@email.com'
[07:50:23]: You can either retry, or fallback to manual setup which will create a basic Fastfile
[07:50:23]: Would you like to fallback to a manual Fastfile? (y/n)
```

**Comment by emilio-martinez** [comment]
@joshdholtz absolutely. A lot of this revolves around not knowing exactly what `user_details_data` is precisely referring to when it comes to iTC. Getting a clearer picture around the permissions fastlane is looking for in iTC would be extremely helpful.

**Comment by joshdholtz** [comment]
@emilio-martinez I will see what we can do 😊

**Comment by tedgonzalez** [comment]
I had this issue when my developer account has some terms and conditions to accept in app store connect.

**Comment by pborbas** [comment]
I had the same error. The cause for me was that I had an admin account on [apple developer site](https://developer.apple.com/account) but not on [appstore connect](https://appstoreconnect.apple.com/). After our agent created an account for me on appstore connect and I logged in and accepted its terms all started to work.
