### ISSUE TITLE
fastlane gym seems to not want to use ad-hoc profile as specified by export-options in CircleCI

### ISSUE THREAD

**Issue by rick-cape** [fastlane/fastlane#10745]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have searched github issues and found many similar problems (#10315, #10341, #10172), but none seem to address the problem I'm having.

I'm using CircleCI, which is where the failure is occurring.  When I run `fastlane` locally it all works fine.  I'm fairly certain this has something to do with the fact that the _AdHoc_ profiles are installed on my local machine, but on the clean CI build, either `sigh` isn't installing them or `gym` isn't picking them up.

First, let me say that I am aware of https://docs.fastlane.tools/codesigning/troubleshooting/ and that I am not currently using `match`.  I eventually want to migrate to it but do not have the ability to at this moment.

I'm using `sigh` to update my _AdHoc_ provisioning profiles, and then build using `gym`.  I have three different targets building three different bundle-ids with three different sets of provisioning profiles: each with an _AdHoc_ and _AppStore_ profile (for a total of 6).  

Notice, `sigh` pulls the right _AdHoc_ Profile, but `gym` does not use it.

I've tried the following things
- adding `export_xcargs -allowProvisioningUpdates`
- adding `export_options.signingStyle` "manual"

<details><summary>CircleCI output, trimmed</summary>

(Please Note: I've redacted parts of this output...either because it is irrelevant or I cannot expose it.  I've replaced our app name with APPNAME and our bundle id with APPBUNDLEID where appropriate...but the rest is actual output.)

```
[]: ------------------
[]: --- Step: sigh ---
[]: ------------------
+-------------------------------------+----------------------------------+
|                        Summary for sigh 2.62.1                         |
+-------------------------------------+----------------------------------+
| adhoc                               | true                             |
| provisioning_name                   | APPNAME Ad-Hoc Profile |
| app_identifier                      | APPBUNDLEID              |
| development                         | false                            |
| skip_install                        | false                            |
| force                               | false                            |
| username                            | USERNAME          |
| team_id                             | TEAM                       |
| ignore_profiles_with_different_name | false                            |
| skip_fetch_profiles                 | false                            |
| skip_certificate_verification       | false                            |
| platform                            | ios                              |
+-------------------------------------+----------------------------------+

[]: Starting login with user 'USERNAME'
[]: Successfully logged in
[]: Fetching profiles...
[]: Verifying certificates...
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[]: Found 1 matching profile(s)
[]: Downloading provisioning profile...
[]: Successfully downloaded provisioning profile...
[]: Installing provisioning profile...
...
[]: Setting Provisioning Profile type to 'ad-hoc'
...
[]: -----------------
[]: --- Step: gym ---
[]: -----------------
[]: $ xcodebuild -list -workspace ...REDACTED
[]: $ xcodebuild -showBuildSettings -workspace ...REDACTED 
[]: Detected provisioning profile mapping: {:"APPBUNDLEID"=>"APPNAME Ad-Hoc Profile"}

+-------------------------------------------------------------+--------------------------------------------------------------+
|                                                   Summary for gym 2.62.1                                                   |
+-------------------------------------------------------------+--------------------------------------------------------------+
| output_directory                                            | /tmp/circle-artifacts.iGItMty/                        |
| output_name                                                 | REDACTED                                         |
| scheme                                                      | SCHEME                                                   |
| export_method                                               | ad-hoc                                                       |
| export_options.provisioningProfiles.APPBUNDLEID     | APPNAME Ad-Hoc Profile                             |
| codesigning_identity                                        | IDENTITY
|
| workspace                                                   | WORKSPACE                                         |
| destination                                                 | generic/platform=iOS                                         |
| build_path                                                  | /Users/distiller/Library/Developer/Xcode/Archives/2017-10-30 |
| clean                                                       | false                                                        |
| silent                                                      | false                                                        |
| skip_package_ipa                                            | false                                                        |
| buildlog_path                                               | /tmp/circle-artifacts.iGItMty/gym                            |
| skip_profile_detection                                      | false                                                        |
| xcode_path                                                  | /Applications/Xcode-9.0.1.app                                |
+-------------------------------------------------------------+--------------------------------------------------------------+

[]: $ set -o pipefail && xcodebuild -workspace <WORKSPACE> -scheme <SCHEME> -destination 'generic/platform=iOS' -archivePath <ARCHIVEPATH> archive CODE_SIGN_IDENTITY=<IDENTITY> | tee /tmp/circle-artifacts.iGItMty/gym/LOGFILE | xcpretty
...
+---------------+-------------------------------+
|               Build environment               |
+---------------+-------------------------------+
| xcode_path    | /Applications/Xcode-9.0.1.app |
| gym_version   | 2.62.1                        |
| export_method | ad-hoc                        |
| sdk           | iPhoneOS11.0.sdk              |
+---------------+-------------------------------+
...
[]: ▸ Check dependencies
[]: ▸ Code Signing Error: No profile for team 'TEAMID' matching 'APPNAME Distribution Profile' found:  Xcode couldn't find any provisioning profiles matching 'TEAMID/APPNAME Distribution Profile'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
[]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
[]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
[]: 
[]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[]: 📋  For the complete and more detailed error log, check the full log at:
[]: 📋  /tmp/circle-artifacts.iGItMty/gym/LOG
[]: 
[]: Looks like fastlane ran into a build/archive error with your project
[]: It's hard to tell what's causing the error, so we wrote some guides on how
[]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[]: Before submitting an issue on GitHub, please follow the guide above and make
[]: sure your project is set up correctly.
[]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[]: the full commands printed out in yellow in the above log.
[]: Make sure to inspect the output above, as usually you'll find more error information there
```
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.6                                           |
| Ruby                        | 2.3.5                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.13.5 (Apple Git-94)                 |
| Installation Source         | ~/.gem/ruby/2.3.5/bin/fastlane                    |
| Host                        | Mac OS X 10.12.6 (16G29)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.5/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-9.0.1.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:
(Note: I've redacted parts of Fastfile...either because it is irrelevant or I cannot expose it)

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.7.0"
default_platform :ios

platform :ios do

...<REDACTED>

  desc "Builds IPA"
  private_lane :buildIPA do |options|
    UI.message "Building IPA, Options: #{options}"

...<REDACTED>

    adhoc = options[:adhoc] || false
    if adhoc then
      export_method = "ad-hoc"
      profile_type = "Ad-Hoc"
    else
      export_method = "app-store"
      profile_type = "Distribution"
    end

    manual_profile = "APPNAME #{profile_type} Profile"
      
    sigh(adhoc: adhoc,
         provisioning_name: manual_profile,
         app_identifier: "APPBUNDLEID")

...<REDACTED>
    
    gym(
      output_directory: options[:output_directory],
      output_name: "APPNAME",
      scheme: "APPSCHEME",
      export_method: export_method,
      codesigning_identity: "REDACTED",
    )

...<REDACTED>

  end

  desc "Builds adhoc IPA"
  lane :adhoc do |options|
    options[:adhoc] = true
    buildIPA(options)
  end

...<REDACTED>

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "APPBUNDLEID" # The bundle identifier of your app
apple_id "USERNAME" # Your Apple email address

team_id "TEAMID"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-10-30**
</details>

**Comment by ryang1428** [comment]
The trick for me was setting `skip_profile_detection: true` along with `signingStyle: "manual"` and explicitly passing my `provisioningProfiles` mapping. I went crazy for several days before realizing I needed all of these set. Godspeed sir, it was not a fun week. I didn't have to do any of this for Xcode8 builds.

```
	gym(
  		workspace: options[:workspaceName],
  		scheme: options[:scheme],
  		output_name: options[:ipaFileName],
		output_directory: "./build",
  		clean: true,
		export_method: options[:exportMethod], 
		export_team_id: "options[:teamId]",
		skip_profile_detection: true,
		export_options:{
			compileBitcode: false,
			signingStyle: "manual",
  			provisioningProfiles:{
				#Anthro
    				"com.anthropologie.iosapp.dev": "Anthro Dev Distribution"
  			}
		}
	)
```

Note the `export_method` I am passing in is `enterprise`

**Comment by rick-cape** [comment]
Thanks @ryang1428 for the suggestion!  Unfortunately, I tried adding all three: `skip_profile_detection: true`, `export_options.signingStyle: "manual"`, and manually specifying `export_options.provisioningProfiles`.  I can provide the output here but sadly it did not help.  `gym` _still_ insists on using the "app store" profiles, not the "ad hoc" ones.  
(Thanks also for sharing the pain...I've been spending days on this and still it doesn't work...)

**Comment by rick-cape** [comment]
Greetings! Any updates on this issue?

**Comment by romk1n** [comment]
i have kind of similar issue i think, i have 2 lanes which can either do ad hoc or App Store for the same bundle, everything use to work fine, but now with latest fast lane it stopped, it complains about that i used option ad hoc but the Xcode Project uses App Store, before was not an issue.

**Comment by amast09** [comment]
I have this same issue except in my case I am using match and I only encounter the error when running an adhoc build in circleci. Any help would be a godsend as I have already spent ~12 hours trying to figure it out. I did try @ryang1428's suggestions short of manually specifying the provisioning profiles (since match should be taking care of this for me) but of course it did not work :( .

**Comment by ohayon** [comment]
Hey folks! Apologies for this issue you all are seeing. I am able to use an ad-hoc profile with the solution that @ryang1428 mentioned in a side project. @amast09, could you share the output you are seeing? Also, it would be nice to see how you have Xcode setup to code sign as well 😄  🐙

**Comment by amast09** [comment]
Okay @ohayon hopefully this should help,

The command I am running with the fastlane file is,

`bundle exec fastlane build build_number:0 match_type:adhoc export_method:ad-hoc ipa_name:ADHOC.ipa`

Here is my fastlane environment (I know my version is behind however I am only 1 patch version behind):
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.12.6                                            |
| Ruby                        | 2.3.5                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.13.5 (Apple Git-94)                  |
| Installation Source         | ~/mobile/ios/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                           |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.5/lib                           |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-9.app/Contents/Developer/      |
| Xcode Version               | 9.0                                                |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.1"
generated_directory = "fastlane/generated"

default_platform :ios

xcversion(version: "9.0")

platform :ios do

  before_all do
  end

  desc "This will generate an ad hoc build to run on any device"
  lane :adhoc do
    match(type: "adhoc", readonly: true)
    gym(
        scheme: "Mobile",
        export_method: "ad-hoc",
        configuration: "Release",
        output_directory: generated_directory,
        build_path: generated_directory,
        derived_data_path: generated_directory,
        buildlog_path: generated_directory
    )
  end

  desc "Build an IPA for the App"
  lane :build do |options|
    setup_circle_ci
    match(type: options[:match_type], readonly: true)
    increment_build_number(build_number: options[:build_number].to_s)
    gym(
        scheme: "Mobile",
        export_method: options[:export_method],
        clean: true,
        skip_profile_detection: true,
        configuration: "Release",
        output_directory: "./",
        output_name: options[:ipa_name],
        build_path: generated_directory,
        derived_data_path: generated_directory,
        buildlog_path: generated_directory
    )
  end

  desc "Push Built IPA to TestFlight"
  lane :push_ipa_to_testflight do |options|
    testflight(
        groups: "BAH",
        skip_submission: true,
        skip_waiting_for_build_processing: true,
        ipa: options[:path_to_ipa]
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
  end

  desc "Increment Patch Version Number"
  lane :increment_patch_version do
    increment_build_number(build_number: 1)
    increment_version_number(bump_type: "patch")
    commit_version_bump(xcodeproj: "./Mobile.xcodeproj", message: "Version Bump [ci skip]")
    push_to_git_remote
  end

  desc "Increment Build Number and Major Version Number"
  lane :increment_build_and_major_version do
    increment_build_number
    increment_version_number(bump_type: "major")
    commit_version_bump(xcodeproj: "./Mobile.xcodeproj")
    push_to_git_remote
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<BUNDLE ID CENSORED>" # The bundle identifier of your app
apple_id "<APPLE EMAIL ADDRESS CENSORED>" # Your Apple email address

team_id "<DEV PORTAL TEAM ID CENSORED>" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.68.1  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.3.1        |
</details>


*generated on:* **2017-12-06**
</details>

<br/>
In Xcode I have the following configuration for the `Mobile` target that is attempting to be built


### Provisioning Profile
> Debug : match Development (bundle id)
> Release : match AppStore (bundle id)

### Provisioning Profile (Deprecated)
> Both : match AdHoc (bundle id)

The reason I added the Provisioning Profile Deprecated property is because that is what circle ci advised, [Setting Up Code Signing for iOS Projects](https://circleci.com/docs/2.0/ios-codesigning/#preparing-your-xcode-project-for-use-with-fastlane-match)

Please let me know if you have any other details that you may need from me.

Any help is GREATLY appreciated

Thanks!

**Comment by ohayon** [comment]
Hey @amast09, we did just make some small changes to how code signing works in the latest release, any chance you could update and give it another shot before diving in deeper? Thanks!

**Comment by amast09** [comment]
Hey @ohayon ,

Unfortunately I am receiving the same error with the upgraded fastlane version. Here is the exact error,

`Code Signing Error: No profile for team '<Team ID>' matching 'match AppStore <App Identifier>'`

Even though I get the following configuration details in the Gym output,

`export_options.provisioningProfiles.<App Identifier> | match AdHoc <App Identifier>`

which makes it seem like the Gym command will be building with the AdHoc provisioning profile.

I have even SSH'ed into the failed CI machine and I am able to see that the correct provisioning profile was installed via `match`.

Thank you for your continued help!

**Comment by ohayon** [comment]
Oh, I just took a closer look at your Fastfile and it looks like you will need to specify the export options parameter. Could you share the entire output from your command line or CI so that we can see the whole context? Thanks! 🚀

**Comment by amast09** [comment]
Here are the CircleCI logs for the AdHoc build in all their glory (with sensitive strings replaced):

[AdHocBuild.log](https://github.com/fastlane/fastlane/files/1536322/AdHocBuild.log)

Again, thanks for your help!

**Comment by rick-cape** [comment]
@ohayon thank you for looking into this!  Just want to note: in the original issue post on Oct 30, I noted that I do _not_ use `match`.  If you notice in the logs, `sigh` pulls the right AdHoc Profile, but `gym` does not use it (see the "CircleCI output, trimmed").  I tried the solution @ryang1428 suggested but it did not work for me.  Do you have any other insights?  Can I help by providing any further information?

**Comment by ohayon** [comment]
Have you all tried specifying your provisioning profile in the `export_options` parameter for gym? That can look something like:

```
gym(
  ...
  export_method: 'adhoc',
  export_options: {
    provisioningProfiles: {
      "<your bundle ID>": "<the name of your provisioning profile>"
    }
  }
)
```

**Comment by amast09** [comment]
Yes, I have attempted that solution. Unfortunately it also did not work.

It is weird because in my case when using match (different from @ohayon who uses cert and sigh) on my local, it works just fine. It is only CircleCI that causes the xcodebuild to attempt to build using the AppStore provisioning profile even though Gym clearly states it is using the adhoc profile and match correctly installed the adhoc provisioning profile.

**Comment by rick-cape** [comment]
@ohayon Yes I have tried that.  I'd also like to reiterate that I saw the exact same problem @amast09 sees: it works on my local machine, but fails in CircleCI (i.e. xcodebuild uses the AppStore profile)

**Comment by getreup** [comment]
I believe we are running into the same issue. Using Gym & Match, xcodebuild is spewing out:

`Code Signing Error: No certificate for team '<TEAM_ID>' matching 'match AppStore <BUNDLE_ID>' found:  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.`

The team ID and the bundle ID are both correct, and the name of the provisioning profile matches match's. The weird thing is that I can run archive from Xcode and it builds and signs correctly with this team ID, bundle ID and provisioning profile. Here is my Gym command:

`fastlane gym --scheme ReUp --clean true --silent false --output_directory ./output/ios/ --output_name  "ipaname".ipa --skip_profile_detection true --export_options "./fastlane/exportOptionsStore.plist" --export_team_id <TEAM_ID> --codesigning_identity "match AppStore <BUNDLE_ID>"`

Is there anything in the above that could be missing? I think the key thing here is that Xcode can archive fine but xcodebuild can't find the certs.

Thanks!

**Comment by getreup** [comment]
Wow.. after days of trying to work through this, I found a solution minutes after posting here ><

I had some redundancy in my command above, since a lot of that info is in the export options plist already. Once I removed that redundancy, everything worked like a charm. I don't think this should be happening, but if anyone else sees this, it may help. I changed this:

`fastlane gym --scheme ReUp --clean true --silent false --output_directory ./output/ios/ --output_name "ipaname".ipa --skip_profile_detection true --export_options "./fastlane/exportOptionsStore.plist" --export_team_id <TEAM_ID> --codesigning_identity "match AppStore <BUNDLE_ID>"`

to this:

`fastlane gym --scheme ReUp --clean true --silent false --output_directory ./output/ios/ --output_name "ipaname".ipa --skip_profile_detection true --export_options "./fastlane/exportOptionsStore.plist"`

Where the export options plist has the team, bundle and provisioning file name.

**Comment by rick-cape** [comment]
@getreup thanks for the message.  Unfortunately, I do not believe this is the same issue.  Again the original issue is using `gym` (without `match`), trying to specify an *ad-hoc* profile (you specified an "AppStore" profile).  For some reason beyond my understanding, the problem only surfaces in CircleCI.

Here is the `gym` command I've tried from my `Fastfile`:
````
    gym(
      output_directory: OUTPUT_DIR,
      output_name: OUTPUT_NAME,
      scheme: APPSCHEME,
      export_method: "ad-hoc",
      export_options: {
        # Tried with and without this, doesn't matter:      compileBitcode: false,
        signingStyle: "manual",
        provisioningProfiles:{ APPBUNDLEID: ADHOC_PROFILE }
      },
      codesigning_identity: "<REDACTED>",
    )
```

And here is 

Note to all: I've had to resort to not using *ad-hoc* profiles, which is a workaround but it is a hardship on our team.  I just tried it again, with the current version of fastlane (*2.68.2*).  Same issue.

**Comment by hborders** [comment]
I just changed from using `PROVISIONING_PROFILE` to `PROVISIONING_PROFILE_SPECIFIER` in my Xcode project. Additionally, I upgraded from Xcode 8.2.3 to Xcode 9.2, and `gym` started failing to automatically detect my provisioning profile settings. I tried using [`ryang1428`'s workaround](https://github.com/fastlane/fastlane/issues/10745#issuecomment-340848177), but I got the following error:
```
[!] Syntax error in your Fastfile on line 68: Fastfile:68: syntax error, unexpected ':', expecting =>
          "<app id>": "<provisioning profile name>",
```

I assume this is because `ryang1428` is running a different `ruby` than me. I'm running:
```
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```
I believe this is the default for `macOS Sierra 10.12.6`.

However, when I fixed the ruby syntax issues, everything worked great! Just for completeness, here is the equivalent of `ryang1428`'s `gym` call within my `Fastfile`:
```
gym(
  		workspace: options[:workspaceName],
  		scheme: options[:scheme],
  		output_name: options[:ipaFileName],
		output_directory: "./build",
  		clean: true,
		export_method: options[:exportMethod], 
		export_team_id: "options[:teamId]",
		skip_profile_detection: true,
		export_options: {
			"compileBitcode" => false,
			"signingStyle" => "manual",
  			"provisioningProfiles" => {
    				"com.myapp.iosapp.dev" => "MyApp Dev Distribution",
  			},
		},
	)
```

**Comment by rick-cape** [comment]
@hborders thanks for the tip!  Unfortunately, changing from the ":" to "=>" syntax in `export_options` did not solve the problem (I have the same issue, where specifying the `export_options` seems to be ignored by CircleCI). I wasn't expecting it to work, because I do see this in the CI logs:

`Detected provisioning profile mapping: {:"com.myapp.iosapp.dev"=>"MyApp Ad-Hoc Profile" ... } `

However, later on after the build completes, I see:
`[14:17:43]: ▸ Code Signing Error: No profile for team '<TEAM>' matching 'MyApp Distribution Profile' found:  Xcode couldn't find any provisioning profiles matching '<TEAM>/MyApp Distribution Profile'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor...`

I just don't understand it.  It is as if `gym` (or `xcodebuild`) is simply ignoring my `export_options` settings.

Any other help out there?  This issue has been plaguing us for months now.. :(

**Comment by rick-cape** [comment]
Any progress on this issue?  Even with the latest Fastlane (2.77.1) I still see this problem in CircleCI.

**Comment by rick-cape** [comment]
Just reproduced this problem in 2.80.0 as well.

**Comment by KrauseFx** [comment]
Sorry for the late response, those kinds of things are almost impossible for us to reproduce unfortunately. You see all the commands _fastlane_ uses printed out as they run. If you can tell us how they should be different, we can of course modify them. 

Or if you know how we can reproduce this on an empty sample project, that would help also. 

Does it work on your machine? If so, it might be a problem related to Circles keychain, you might be able to create a temporary Keychain as part of your _fastlane_ run

**Comment by rick-cape** [comment]
@KrauseFx thanks for the reply.  Yes, one of the confounding things about this is that it works on my local machine 100%.  It only fails in CircleCI.  How would I go about setting up a temporary keychain to test this?

**Comment by kevnm67** [comment]
@rick-cape I had the same issue and finally solved it (after many failed attempts) by installing development, appstore and adhoc certs using match. Here's an example of the lane I'm using:
```
    desc "Fetch all provisioning profiles."
    desc "types: Provisioning profile for match (appstore, development, or adhoc) as an array"
    desc ""
    private_lane :run_match do |options|
      if !options.key?(:types)
        raise "You must provide an array of distribution types for match to fetch provisioning profiles!"
        return
      end

      distribution_methods = options[:types]

      distribution_methods.each do |distribution_method|
        match(
          type: distribution_method,
          force_for_new_devices: true,
          readonly: is_ci?,
        )
      end
    end

    desc "Install all profiles"
    lane :certs do
      run_match(types: ["appstore", "adhoc"])
    end
```

**Comment by rick-cape** [comment]
@kevnm67 Thank you for the suggestion!  I do not have `match` set up at the moment -- for my situation it would be a lot of work.  But if it is the only option I suppose I'll have to go that route.

**Comment by kevnm67** [comment]
@rick-cape Sorry, I missed that in your previous response.  Have you tried installing your developer, appstore and adhoc profiles before running gym for ad-hoc builds?

**Comment by rick-cape** [comment]
@kevnm67 Yes.  `gym` works perfectly fine on my machine, and properly uses the adhoc profile when specified.  However, it fails on CircleCI.  (I realize now that the issue title does not state this, I just fixed that)

As I mentioned above, 
> ... It is as if gym (or xcodebuild) is simply ignoring my export_options settings.

**Comment by kevnm67** [comment]
@rick-cape I had the same exact issue except I'm using match.  

Have you used SSH to debug your builds? If not, rerun using SSH and use the command ```security find-identity -v -p codesigning```. Are your code signing credentials installed?

I'd try something like this (note: setup_circle_ci used in the before all step to prepare a temp. keychain when running in ci env.):

```ruby
  before_all do
    if is_ci?
      setup_circle_ci
    end
  end
  
  lane :build_adhoc
    temp_keychain = ENV["MATCH_KEYCHAIN_NAME"]
    
    get_certificates
    run_sigh(types: ["appstore", "adhoc"])
  
    gym(
      output_directory: OUTPUT_DIR,
      output_name: OUTPUT_NAME,
      scheme: APPSCHEME,
      export_method: "ad-hoc",
      include_bitcode: false,
      include_symbols: true,
      buildlog_path: 'fastlane/logs',
      clean: true,
      export_options: {
        signingStyle: "manual",
        provisioningProfiles:{ APPBUNDLEID: ADHOC_PROFILE }
      },
      codesigning_identity: "<REDACTED>",
    )
  end

  lane :run_sigh 
    sigh(adhoc: false, readonly: is_ci?)
    sigh(adhoc: true, readonly: is_ci?)
  end
```

**Comment by rick-cape** [comment]
Update: on @kevnm67 's suggestion, I checked the code signing creds in CircleCI and they all looked good.  I also added the `setup_circle_ci` suggestion above and still, the signing was failing.

On a lark, I thought I'd remove any profiles registered with CircleCI and add fresh ones from apple developer.  And...what do you know?  It *worked*!  I _thought_ that CircleCI used in the provisioning profiles provided by `sigh` (ideally I'd want Fastlane to manage the profiles, not CircleCI), which were always the right ones coming from Apple.  Was I mistaken about this?

This seems more reason for me to switch to `match` as soon as possible.  Anyway, thank you all for your ideas and help.  I'll close this issue.

**Comment by kevnm67** [comment]
@rick-cape Glad to hear you got it working!  What, if anything, is different with your fastfile?  

It doesn't seem like circle 2.0 uses the uploaded code signing credentials as circle 1.0 did - not positive but I don't see them anywhere in my archive workflow.  Also, [circle 2.0's code signing docs](https://circleci.com/docs/2.0/ios-codesigning/) describe code signing guidelines for iOS or Mac projects using a fastlane match configuration.  "Fastlane Match is one of the Fastlane tools, and it allows for seamless configuration on code signing in both the development environment and on CircleCI".  They make it at least ** seem** like match or fastlane cert & sigh setups are expected/best practice.

**Comment by rick-cape** [comment]
@kevnm67 the only thing I added to my Fastfile is the
```
  before_all do
    if is_ci?
      setup_circle_ci
    end
  end
```
and
```
...
readonly: is_ci?
...
```
in the `sigh` command.

I am definitely motivated to switch to `match`.  Thanks for all your help. 🥇

**Comment by matteocollina** [comment]
This is my beta lane and it works
`
get_provisioning_profile(
		  adhoc: true,
		  force: true
)   
increment_build_number
gym(export_method:"ad-hoc",
	        scheme: "MyScheme",
	        workspace:"MyScheme.xcworkspace",
	        export_xcargs: "-allowProvisioningUpdates"
 )
`
