### ISSUE TITLE
Better error message API

### ISSUE THREAD

**Issue by iShawnWang** [fastlane/fastlane#10748]
### New Issue Checklist

- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

###  :D

Hey guys ~

Is there an api for collect error message, so that I can make better slack notification with the error message instead of the whole long logs.
If the build failed I want to get the short message or the error, such as  `Unauthorized`, `Network failed`, `logIn iTunes connect failed, reason XXXX`. It's even better if there is a `common error list` for what may happen when build.

Now, if the build error occur, I need to login the remote server and search from the log.

**Comment by ohayon** [comment]
Hey @iShawnWang - there isn't an API exactly, but you could put `rescue` blocks in your Fastfile and call to the `slack` action in there to post the message you'd like 🚀
