### ISSUE TITLE
[PEM] Active days limit option is unusable

### ISSUE THREAD

**Issue by vspac** [fastlane/fastlane#10752]
`active_days_limit` option can't be used because it is missing `is_string: false` in config item

https://github.com/fastlane/fastlane/blob/a4704d7a0da18e35a24d858000f66e80c8956ea1/pem/lib/pem/options.rb#L26

Fastlane forces you to pass a `String` but the `verify_block` expects an `Integer`

**Comment by ohayon** [comment]
Hey @vspac - thanks for raising the issue! Any chance you would want to submit a PR with a fix for that? 🎉

**Comment by janpio** [comment]
Resolved via #10763
