### ISSUE TITLE
Show progress for match cloning repo

### ISSUE THREAD

**Issue by NikKovIos** [fastlane/fastlane#10764]
Hello) It' would be very nice if you add a progress notification while match is cloning the existing repo. Like git do.
My repo is 600mb size and it takes near 10 minutes to clone it.

[12:53:57]: Cloning remote git repo...
[12:53:57]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.

Also there is a case when it clones the whole repo, when (i think) shouldn't.  
 Exists: Repo 600mb. No branches for match.
1) Nuked distribution and development certs.
2) match(type: "appstore"). It clones the whole repo.
3) match(type: "development"). It clones whole repo again. `shallow_clone` and `clone_branch_directly` options enabled. Should it do that again?

**Comment by ohayon** [comment]
Hey @NikKovIos, that would be sweet. Is there any chance you would want to submit a PR adding progress UI? We would love to review it! 🚀

**Comment by adellibovi** [comment]
@ohayon maybe we could just add the "--progress" param to the git command? Have ideas on making that as "default" or being optional?

**Comment by ohayon** [comment]
I think I would favor this to be optional if possible.
