### ISSUE TITLE
Fastlane beta update app version for app waiting in review

### ISSUE THREAD

**Issue by devladinci** [fastlane/fastlane#1076]
## Prerequisites 

- `Waiting for review` version in iTunes Connect

## Steps to reproduce

- Bump app version (Product -> General)
- `Fastlane beta`

## Expected result

- New test flight is uploaded.

## Actual result

- New test flight is uploaded.
- Fastlane change app version with version of the new build.

For example if `waiting for review` version is `3.1` and submit test flight version `3.2`. Then `waiting for review` version will become `3.2`

 Always reproducible.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
