### ISSUE TITLE
Match : unable to push the certificate or profiles into git

### ISSUE THREAD

**Issue by kumarkalluri** [fastlane/fastlane#10760]
I am trying out utilize the match feature functionality. So, I am getting below error when i tried out.

Pushing changes to remote git repo...
git: 'credential-foo' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[18:42:56]: Exit status: 128
[18:42:56]: Couldn't commit or push changes back to git...
[18:42:56]: Exit status: 128

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.62.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-11-01**
</details>

**Comment by ohayon** [comment]
Hey @kumarkalluri, could you share the command you are using to run match? Thanks! Also, is this a CI machine?

**Comment by kumarkalluri** [comment]
I am using the command like **fastlane match development** and this is not ci machine , just running on my system command line.

**Comment by ohayon** [comment]
Thanks for the reply @kumarkalluri, could you share the entire output from beginning to end of the execution?

**Comment by kumarkalluri** [comment]
output:


Dhakers-MacBook-Pro:~ kumar$ fastlane match development
[23:04:15]: fastlane detected a Gemfile in the current directory
[23:04:15]: however it seems like you don't use `bundle exec`
[23:04:15]: to launch fastlane faster, please use
[23:04:15]: 
[23:04:15]: $ bundle exec fastlane match development
[23:04:15]: 
[23:04:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-----------------------+----------------+
|        Summary for match 2.62.1        |
+-----------------------+----------------+
| type                  | development    |
| git_branch            | master         |
| keychain_name         | login.keychain |
| readonly              | false          |
| verbose               | false          |
| force                 | false          |
| skip_confirmation     | false          |
| shallow_clone         | false          |
| clone_branch_directly | false          |
| force_for_new_devices | false          |
| skip_docs             | false          |
| platform              | ios            |
+-----------------------+----------------+

[23:04:17]: To not be asked about this value, you can specify it using 'git_url'
[23:04:17]: URL to the git repo containing all the certificates: https://github.com/xyz/xyz-sample.git
[23:04:26]: Cloning remote git repo...
[23:04:26]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[23:04:32]: 🔓  Successfully decrypted certificates repo
[23:04:32]: To not be asked about this value, you can specify it using 'username'
[23:04:32]: Your Apple ID Username: abc@xyz.com
[23:04:43]: Verifying that the certificate and profile are still valid on the Dev Portal...
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) ABCDEFZF “ABC” (Company/Organization)
2) BBB65ddd “ABC LLC" (Company/Organization)
2
[23:05:37]: To not be asked about this value, you can specify it using 'app_identifier'
[23:05:37]: The bundle identifier(s) of your app (comma-separated): com.abc.xyz
[23:05:55]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+--------------------------------------+
|               Summary for cert 2.62.1                |
+---------------+--------------------------------------+
| development   | true                                 |
| force         | true                                 |
| username      | abc@xyz.com            |
| keychain_path | /Users/kumar/Library/Keychains/logi  |
|               | n.keychain-db                        |
| platform      | ios                                  |
+---------------+--------------------------------------+

[23:05:55]: Starting login with user ‘abc@xyz.com'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) TTZYH87XY5 “ABC” (Company/Organization)
2) 6X82G43549 “ABC LLC" (Company/Organization)
2
[23:06:49]: Successfully logged in
[23:07:11]: Successfully generated 8D8R77JSJH which was imported to the local machine.
[23:07:12]: Verifying the certificate is properly installed locally...
[23:07:12]: Successfully installed certificate 8D8R77JSJH

+-------------------------------------+-----------------------------+
|                      Summary for sigh 2.62.1                      |
+-------------------------------------+-----------------------------+
| app_identifier                      | com.abc.xyz |
| username                            | abc@xyz.com   |
| force                               | true                        |
| cert_id                             | 8D8R77JSJH                  |
| provisioning_name                   | match Development           |
|                                     | com.abc.xyz |
| ignore_profiles_with_different_name | true                        |
| platform                            | ios                         |
| development                         | true                        |
| adhoc                               | false                       |
| skip_install                        | false                       |
| skip_fetch_profiles                 | false                       |
| skip_certificate_verification       | false                       |
+-------------------------------------+-----------------------------+

[23:07:17]: Starting login with user ‘abc@xyz.com'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) ABDDDED “ABC” (Company/Organization)
2) 6XYZASFF “ABC LLC" (Company/Organization)
2
[23:08:03]: Successfully logged in
[23:08:03]: Fetching profiles...
[23:08:08]: Verifying certificates...
[23:08:11]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[23:08:34]: The name 'match Development com.abc.xyz’ is already taken, using another one.
[23:08:34]: Creating new provisioning profile for 'com.abc.xyz’ with name 'match Development com.abc.xyz 1509557914' for 'ios' platform
[23:09:03]: Downloading provisioning profile...
[23:09:22]: Successfully downloaded provisioning profile...
[23:09:22]: Installing provisioning profile...
/var/folders/rz/d6k9df8d1qs2j_x0wx462b1h0000gr/T/d20171101-13102-14nfw5q/profiles/development/Development_com.abc.xyz.mobileprovision
[23:09:22]: Installing provisioning profile...
[23:09:30]: 🔒  Successfully encrypted certificates repo
[23:09:30]: Pushing changes to remote git repo...
**git: 'credential-foo' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[23:09:36]: Exit status: 128
[23:09:36]: Couldn't commit or push changes back to git...
[23:09:36]: Exit status: 128**

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | com.abc.xyz            |
|                     |                        |                        |
| Type                |                        | development            |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_com.abc           | 1fe36d36-c9ba-44fa-af  |
|                     | .xyz_developme         | 7a-105e26f921ac        |
|                     | nt                     |                        |
| Profile Name        | sigh_com.abc.          | match Development      |
|                     | .xyz_developme         | com.abc.xyz            |
|                     | nt_profile-name        | makers 1509557914      |
| Profile Path        | sigh_com.abc.          | /Users/kumar/Library/  |
|                     | .xyz_developme         | MobileDevice/Provisio  |
|                     | nt_profile-path        | ning                   |
|                     |                        | Profiles/1fe36d36-c9b  |
|                     |                        | a-44fa-af7a-105e26f92  |
|                     |                        | 1ac.mobileprovision    |
| Development Team ID | sigh_com.abc.          | 6X824567               |
|                     | .xyz._developme        |                        |
|                     | nt_team-id             |                        |
+---------------------+------------------------+------------------------+

[23:09:36]: All required keys, certificates and provisioning profiles are installed 🙌

**Comment by kumarkalluri** [comment]
The issue was fixed. I think it is not asking the username if it is not found. So, it is failed.

I tried to push the other files into that repo, Then it is asking me the username and password and given the credentials and successfully pushed. After that, I tried to run the  **fastlane match development** and it is working as expected. Thank you.

**Comment by ohayon** [comment]
Glad that youre all set @kumarkalluri !! 🚀
