### ISSUE TITLE
Code signing is required for product type 'App Extension' in SDK 'iOS 11.0'

### ISSUE THREAD

**Issue by riyazarnr** [fastlane/fastlane#10767]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

"OneSignalNotificationServiceExtension" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it

My Pod file

target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
post_install do |installer| installer.pods_project.build_configurations.each do |config| config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = '' end end

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by ohayon** [comment]
Hey @riyazarnr I'm not totally sure about that, I would check in with the creators of OneSignal as I'm sure this is something they have seen before 😄

**Comment by agfa555** [comment]
I'm having the same issue, has anyone found a way to solve it?

**Comment by jhochenbaum** [comment]
Joining the chorus... Anyone else able to get OneSignal working with Fastlane?

**Comment by agfa555** [comment]
@jhochenbaum I got it to work.

First of all I had to switch to sigh and cert to match (https://docs.fastlane.tools/actions/match/). It's actually a very good decision if you're on a team. Just follow the instructions to nuke everything and regenerate.

After you generate you can use this in your Fastfile for match:

`match(app_identifier: ['com.yourcompany.yourapp', 'com.yourcompany.yourapp.onesignalextension'],
              type: 'adhoc')`

Make sure you change adhoc to appstore for production builds.

Then you can use this configuration for gym adhoc:

`gym(scheme: 'YourScheme',
            configuration: 'Staging',
            export_method: 'ad-hoc',
            export_xcargs: '-allowProvisioningUpdates',
            export_options: {
                compileBitcode: false,
                uploadSymbols: false
            },
            clean: true,
            include_bitcode: false)`

And this for production:

`gym(scheme: 'YourScheme',
            configuration: 'Release',
            export_method: 'app-store',
            export_xcargs: '-allowProvisioningUpdates',
            clean: true,
            include_bitcode: true)`

Let me know if this works for you.

Cheers.
