### ISSUE TITLE
rspec on other_action returns undefined method `trigger_action_by_name` for nil:NilClass

### ISSUE THREAD

**Issue by svanzoest** [fastlane/fastlane#10769]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I am testing my own fastlane plugin via the provided `bundle exec rake` task, my tests fail with the following:

```
Failures:

  1) Fastlane::Actions::CustomConfigAction#run retrieves app config data
     Failure/Error: other_action.team_id(app.team_id)
     
     NoMethodError:
       undefined method `trigger_action_by_name' for nil:NilClass
     # ./lib/fastlane/plugin/custom_config/actions/custom_config_action.rb:31:in `run'
     # ./spec/custom_config_action_spec.rb:6:in `block (3 levels) in <top (required)>'
```

Looking at the code it looks like it is called via `self.runner` and should be loaded in. This works okay when actually running fastlane, however,  it fails when I run it via the supplied test setup.

I looked at #10675 which seems to look at improving the documentation for this, which is great. 
As I basically look through #4707 and got it all working except for the rspec test above.

I will probably look at just returning the value of my action and call `team_id` from within the `Fastfile` itself, but it would be nicer if this could be more implicit and I would rather not copy all the environment variables and duplicate the `team_id` action within my code.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.6                                           |
| Ruby                        | 2.4.2                                             |
| Bundler?                    | true                                              |
| Git                         | git version 2.11.0 (Apple Git-81)                 |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane              |
| Host                        | Mac OS X 10.12.6 (16G29)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-8.3.3.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.63.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                         | Version | Update-Status  |
| ------------------------------ | ------- | -------------- |
| fastlane-plugin-custom_config | 0.1.0   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                            | Version      |
| ------------------------------ | ------------ |
| did_you_mean                   | 1.1.0        |
| bundler                        | 1.15.4       |
| io-console                     | 0.4.6        |
| json                           | 2.1.0        |
| rake                           | 12.1.0       |
| CFPropertyList                 | 2.3.5        |
| public_suffix                  | 2.0.5        |
| addressable                    | 2.5.2        |
| ast                            | 2.3.0        |
| babosa                         | 1.0.2        |
| claide                         | 1.0.2        |
| coderay                        | 1.1.2        |
| colored                        | 1.2          |
| colored2                       | 3.1.2        |
| highline                       | 1.7.8        |
| commander-fastlane             | 4.4.5        |
| safe_yaml                      | 1.0.4        |
| crack                          | 0.4.3        |
| declarative                    | 0.0.10       |
| declarative-option             | 0.1.0        |
| diff-lcs                       | 1.3          |
| docile                         | 1.1.5        |
| unf_ext                        | 0.0.7.4      |
| unf                            | 0.1.4        |
| domain_name                    | 0.5.20170404 |
| dotenv                         | 2.2.1        |
| excon                          | 0.59.0       |
| multipart-post                 | 2.0.0        |
| faraday                        | 0.13.1       |
| http-cookie                    | 1.0.3        |
| faraday-cookie_jar             | 0.0.6        |
| faraday_middleware             | 0.12.2       |
| fastimage                      | 2.1.0        |
| gh_inspector                   | 1.0.3        |
| jwt                            | 2.1.0        |
| little-plugger                 | 1.1.4        |
| multi_json                     | 1.12.2       |
| logging                        | 2.2.2        |
| memoist                        | 0.16.0       |
| os                             | 0.9.6        |
| signet                         | 0.8.1        |
| googleauth                     | 0.6.1        |
| httpclient                     | 2.8.3        |
| mime-types-data                | 3.2016.0521  |
| mime-types                     | 3.1          |
| uber                           | 0.1.0        |
| representable                  | 3.0.4        |
| retriable                      | 3.1.1        |
| google-api-client              | 0.13.6       |
| mini_magick                    | 4.5.1        |
| multi_xml                      | 0.6.0        |
| plist                          | 3.3.0        |
| rubyzip                        | 1.2.1        |
| security                       | 0.1.3        |
| slack-notifier                 | 1.5.1        |
| terminal-notifier              | 1.8.0        |
| unicode-display_width          | 1.3.0        |
| terminal-table                 | 1.8.0        |
| tty-screen                     | 0.5.1        |
| word_wrap                      | 1.0.0        |
| nanaimo                        | 0.2.3        |
| xcodeproj                      | 1.5.3        |
| rouge                          | 2.0.7        |
| xcpretty                       | 0.2.8        |
| xcpretty-travis-formatter      | 1.0.0        |
| fastlane-plugin-custom_config | 0.1.0        |
| hashdiff                       | 0.3.7        |
| method_source                  | 0.9.0        |
| parallel                       | 1.12.0       |
| parser                         | 2.4.0.0      |
| powerpack                      | 0.1.1        |
| pry                            | 0.11.1       |
| rainbow                        | 2.2.2        |
| rspec-support                  | 3.7.0        |
| rspec-core                     | 3.7.0        |
| rspec-expectations             | 3.7.0        |
| rspec-mocks                    | 3.7.0        |
| rspec                          | 3.7.0        |
| ruby-progressbar               | 1.9.0        |
| rubocop                        | 0.50.0       |
| simplecov-html                 | 0.10.2       |
| simplecov                      | 0.15.1       |
| webmock                        | 3.1.0        |
</details>

*generated on:* **2017-11-01**
</details>

**Comment by svanzoest** [comment]
@jdee it looks like you are using `other_action`, did you run into this issue? If so, how did you solve it?

**Comment by Vivekxk** [comment]
I'm getting this as well, did you manage to fix this @svanzoest ?

**Comment by svanzoest** [comment]
@Vivekxk I did not. I worked around it for now. I'd love to do this correctly though.

**Comment by svanzoest** [comment]
So, my work around is as follows:
```ruby
   results = Fastlane::FastFile.new.parse("lane :test do
       app = custom_config(params)
   end").runner.execute(:test)
```
The above gives `other_action` the right context apparently, which causes my test to pass.

**Comment by jdee** [comment]
@svanzoest @Vivekxk Sorry I missed the @ mention. Too many notifications!

Is this only happening in tests? One thing you might think about doing in unit tests is mocking calls to other_action. This better separates code units anyway. Something like:

```Ruby
other = double :other_action
expect(action).to receive(:other_action) { other }
expect(other).to receive(:team_id).with "ABCDEFG"
```

Or you can do something with fixtures, but either way you're not actually calling the `team_id` action in your tests. There also may be a way to set something in your spec_helper or in your tests that makes `other_action` work in a test environment. I'll post it here if I find something like that.

There is an issue with calling actions from dependent plugins in your plugin: #9917. But it looks like you're only calling the built-in `team_id` action.

**Comment by svanzoest** [comment]
@jdee yes, it works fine outside of tests. So your mock example helps a lot.  I haven't done enough mocking for something like that to come that easily. :)

**Comment by jdee** [comment]
Here's some more involved mocking if you want more examples:

https://github.com/BranchMetrics/branch_io_cli/blob/master/spec/ios_helper_spec.rb#L211
https://github.com/BranchMetrics/branch_io_cli/blob/master/spec/ios_helper_spec.rb#L302

That tests verification of a signed apple-app-site-association file using PKCS7 by mocking not only the HTTP request but also the verification by OpenSSL.

And of course see the RSpec docs: https://relishapp.com/rspec/rspec-mocks/docs
