### ISSUE TITLE
Adding export_options to gym not working

### ISSUE THREAD

**Issue by MartijnSchoemaker** [fastlane/fastlane#10778]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Existing issue #10685 

### Issue Description

Because of issue #10685 I manually changed 'signingStyle' to 'automatic' in the plist and exporting is working correctly then.
So to achieve this via fastlane I added this in my gym command:

```
export_options: {
                signingStyle: "automatic"
        }
```
But when I run fastlane the signingStyle of generated plist is still 'manual'. I don't want this... Did I do anything wrong or is this een issue in fastlane?!

_Sorry I don't past all content of fast file etc because it contains confidential information. Please ask me if you need some specific parts to answer my question._

### Environment
 Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

**Comment by ohayon** [comment]
Hey @MartijnSchoemaker - could you share the xcodebuild command that is generated by fastlane and output to your terminal?

**Comment by MartijnSchoemaker** [comment]
Some parts that are useful I think:

+--------------------------------------+--------------------------------------+
| Summary for gym 2.63.0 |
+--------------------------------------+--------------------------------------+
| workspace | wehkamp.xcworkspace |
| configuration | DebugDistribution |
| scheme | wehkamp |
| silent | true |
| output_name | wehkamp |
| export_team_id | 8V375A94TK |
| export_xcargs | -allowProvisioningUpdates |
| export_options.signingStyle | automatic |
| export_method | ad-hoc |
| destination | generic/platform=iOS |
| build_path | /Users/monitor/Library/Developer/Xc |
| | ode/Archives/2017-11-02 |
| clean | false |
| skip_package_ipa | false |
| buildlog_path | ~/Library/Logs/gym |
| skip_profile_detection | false |
| xcode_path | /Applications/Xcode.app |
+--------------------------------------+--------------------------------------+

[15:21:04]: Generated plist file with the following values:
[15:21:04]: ▸ -----------------------------------------
[15:21:04]: ▸ {
[15:21:04]: ▸ "signingStyle": "manual",
[15:21:04]: ▸ "provisioningProfiles": {
[15:21:04]: ▸ "nl.wehkamp.PDD5388SwipeBetweenPDP": "nl.wehkamp.PDD5388SwipeBetweenPDP AdHoc"
[15:21:04]: ▸ },
[15:21:04]: ▸ "method": "ad-hoc",
[15:21:04]: ▸ "teamID": "8V375A94TK"
[15:21:04]: ▸ }
[15:21:04]: ▸ -----------------------------------------

xcodebuild -exportArchive -exportOptionsPlist /var/folders/w3/pts492bj42359t0w2_kxd91m0000gp/T/gym_config20171102-82214-mogew.plist -archivePath '/Users/monitor/Library/Developer/Xcode/Archives/2017-11-02/wehkamp 2017-11-02 15.04.10.xcarchive' -exportPath /var/folders/w3/pts492bj42359t0w2_kxd91m0000gp/T/gym_output20171102-82214-1dcrlqx -allowProvisioningUpdates

**Comment by MartijnSchoemaker** [comment]
If I manually change gym_config20171102-82214-mogew.plist (signingStyle : 'automatic') and run the xcodebuild command manually, everything works fine...

**Comment by twobitlabs** [comment]
We're running into the same issue. After updating to Xcode 9 builds are failing. Hand editing the plist to set signingStyle to automatic fixes the issue but `gym` ignores `export_options: { signingStyle: "automatic" }` and sets the signingStyle to manual.

**Comment by threat70** [comment]
@MartijnSchoemaker Hi! but as I can see, your provisioning profiles is not empty, so it switches to manual signingStyle and I think it cannot find specified provisioning profile. how you specify this provisioning profiles? try to find it in your Fastfile.

**Comment by MartijnSchoemaker** [comment]
I have this line in my lane:

`    sigh(adhoc: true, force: true, app_identifier: params[:app_identifier])
`

I can try removing this, but apart from that it's still strange:
1. That 'signingStyle: "manual" is now explicitly added to plist. 
2. If you specify I specify in gym that I want to use automatic it simply ignores this.

**Comment by threat70** [comment]
it ignored because have provisioning profiles in export_options, automatic signingStyle will use xcode-managed provisioning profiles. In case where you setup provisioning profile always should used signingStyle as manual.
If you want to use automatic signingStyle, so remove provisioning profiles from export_options.
In your case I don't understand how provisioning profiles appeared in export_options and if it do by Sigh, so it have issue. But you cannot share Fastfile, and maybe you will try to find where provisioning profiles was specified?

maybe has the meaning to don't ignore signingStyle in export_options if it specified by user. it will add flexibility.

**Comment by MartijnSchoemaker** [comment]
It seems te be fixed.
First I removed 'sigh', but then I got an error that app id already exists. This maybe could caused by using 'produce' in my lane. So I also removed this, now it seems to work...:

```
lane :adhoc do |params|
    update_info_plist(plist_path: "wehkamp/Info.plist", display_name: params[:app_name], app_identifier: params[:app_identifier])
    update_info_plist(plist_path: "notificationService/Info.plist", app_identifier: params[:app_identifier] + ".notificationService" )
#             app_name: params[:app_name],
#            skip_itc: true,
#            enable_services: { associated_domains: "on"} )
#    produce(app_identifier: params[:app_identifier] + ".notificationService",
#            app_name: params[:app_name] + "notserv",
#            skip_itc: true,
#            enable_services: { associated_domains: "on"} )
...
#sigh(adhoc: true, force: true, app_identifier: params[:app_identifier] )

   enable_automatic_code_signing(path: "wehkamp.xcodeproj")
    gym(
        workspace: "wehkamp.xcworkspace",
        configuration: "DebugDistribution",
        scheme: "wehkamp",
        silent: true,
        output_directory: params[:output_directory],
        output_name: "wehkamp.ipa",
        export_team_id: "",
        export_xcargs: "-allowProvisioningUpdates"
    )
end
```

**Comment by MartijnSchoemaker** [comment]
I doesn't work the second time running this... :( 
Because it added the app id and prov profiles the first time running the script. I get now this error message:
` "An App ID with Identifier 'nl.wehkamp.Adventskalender' is not available. Please enter a different string."`

**Comment by threat70** [comment]
maybe problem in `export_team_id: "",`? why you should use this?

**Comment by MartijnSchoemaker** [comment]
@threat70 sorry I did it for obfuscation but that doesn't make any sense because you can find the teamId also on other places. I added it again, so its now as it really is.

**Comment by threat70** [comment]
@MartijnSchoemaker You build it on CI or local machine? have you tried to build through Xcode?

**Comment by MartijnSchoemaker** [comment]
It's on CI machine, but calling fastlane locally doesn't work neither. Build in Xcode just works. The fastlane build always worked before update 3.62.0 (see #10685)... 

Problem has to do with changing the app name and identifier and creating prov files for this with fastlane.

**Comment by MartijnSchoemaker** [comment]
OMG by changing the fast file as is now as mentioned in previous comment I get now this generated plist:
```
[09:01:29]: Generated plist file with the following values:
[09:01:29]: ▸ -----------------------------------------
[09:01:29]: ▸ {
[09:01:29]: ▸   "method": "app-store",
[09:01:29]: ▸   "teamID": "8V375A94TK"
[09:01:29]: ▸ }
[09:01:29]: ▸ -----------------------------------------
```
That does even make any less sense... 'app-store' why?!

**Comment by threat70** [comment]
I noticed that you have no provisioning profile for NotificationService module, check it on developer.apple.com portal.

**Comment by MartijnSchoemaker** [comment]
No, I tried adding this manually, but also not succeeded.
But I don't want to do manually. I just want that everything is handled automatic, like it did before update 2.62.1. What should I do to achieve this? I

**Comment by MartijnSchoemaker** [comment]
I'm now trying to do everything manually. The profile for notification service is created now, but get this error:
` Provisioning profile "nl.wehkamp.*.notificationService AdHoc" doesn't match the entitlements file's value for the application-identifier entitlement.`

I have not this in fast file:
```
produce(app_identifier: params[:app_identifier] + ".notificationService",
            app_name: params[:app_name] + "notserv",
            skip_itc: true,
            enable_services: {
                push_notification: "off"
            }
    )
```

All capabilities for this target are set to 'off':
<img width="995" alt="screen shot 2017-11-03 at 10 57 59" src="https://user-images.githubusercontent.com/2683569/32368557-5bc3fb64-c086-11e7-874e-99f1dd669143.png">

**Comment by lanebrain** [comment]
I have been having this issue since 2.62.1 was released.  I have pinned to version 2.62.0 for now to be able to build for App Store.  I have tried to force automatic, but no matter where I do this (Gymfile, or as params to gym in the fast file) - it always goes to manual.

[11:12:42]: ▸ Archive Succeeded
[11:12:42]: Generated plist file with the following values:
[11:12:42]: ▸ -----------------------------------------
[11:12:42]: ▸ {
[11:12:42]: ▸   "signingStyle": "manual",
[11:12:42]: ▸   "method": "app-store",
[11:12:42]: ▸   "uploadSymbols": true,
[11:12:42]: ▸   "uploadBitcode": true
[11:12:42]: ▸ }
[11:12:42]: ▸ -----------------------------------------


This the archive will fail - because of trying to manual sign and my extensions start complaining about prov profiles.

**Comment by twobitlabs** [comment]
Pinning to 2.62.0 in the Gemfile resolves the issue, however, I've also found that doing anything with `sigh` in the fastfile causes the signingStyle to resort to manual. We had calls to `sigh repair` and `sigh` in one of our fastfiles and that was causing the signingStyle to switch to "manual". Removing all calls to `sigh` seemed to fix the issues.

**Comment by lanebrain** [comment]
Interesting!  I just commented sigh out of my lane for submitting a build to apple, upgraded to latest Fastlane to give it a go, and can confirm that it works!

Generated plist file with the following values:
[14:21:12]: ▸ -----------------------------------------
[14:21:12]: ▸ {
[14:21:12]: ▸   "method": "app-store",
[14:21:12]: ▸   "uploadSymbols": true,
[14:21:12]: ▸   "uploadBitcode": true
[14:21:12]: ▸ }

**Comment by joshdholtz** [comment]
Heyyyyyyy 👋 Adding this to my list to look into if this is still an issue 😊

**Comment by trackvia-ios** [comment]
@joshdholtz  FYI still experiencing this against `'fastlane', '2.85.0'`.

- `development` archiving and submission to Crashlytics working correctly with gym:

**Gym call:**

```ruby
gym(
    scheme: scheme,
    archive_path: "./#{scheme}",
    output_name: scheme,
    configuration: "Debug",
    export_method: "development",
    export_options: {
      provisioningProfiles: {
          "com.xvia.TrackVia-Develop": "match Development *",
          "com.xvia.TrackVia-Develop.watchkitapp": "match Development com.xvia.TrackVia-Develop.watchkitapp",
          "com.xvia.TrackVia-Develop.watchkitapp.watchkitextension": "match Development com.xvia.TrackVia-Develop.watchkitapp.watchkitextension"
    }
  }
)
```

**Console log:**

```
[11:44:20]: Generated plist file with the following values:
[11:44:20]: ▸ -----------------------------------------
[11:44:20]: ▸ {
[11:44:20]: ▸   "provisioningProfiles": {
[11:44:20]: ▸     "com.xvia.TrackVia-Develop": "match Development *",
[11:44:20]: ▸     "com.xvia.TrackVia-Develop.watchkitapp": "match Development com.xvia.TrackVia-Develop.watchkitapp",
[11:44:20]: ▸     "com.xvia.TrackVia-Develop.watchkitapp.watchkitextension": "match Development com.xvia.TrackVia-Develop.watchkitapp.watchkitextension",
[11:44:20]: ▸     "*": "match Development *"
[11:44:20]: ▸   },
[11:44:20]: ▸   "method": "development",
[11:44:20]: ▸   "signingStyle": "manual"
[11:44:20]: ▸ }
[11:44:20]: ▸ -----------------------------------------
```

- `ad-hoc` archiving fails due to provisioning with gym:

```ruby
gym(
    scheme: scheme,
    archive_path: "./#{scheme}",
    output_name: scheme,
    configuration: "Adhoc",
    export_method: "ad-hoc",
    export_options: {
      method: "ad-hoc",
      signingStyle: "automatic",
      provisioningProfiles:   {
        "com.xvia.TrackVia-Beta": "match AdHoc *",
        "com.xvia.TrackVia-Beta.watchkitapp": "match AdHoc com.xvia.TrackVia-Beta.watchkitapp",
        "com.xvia.TrackVia-Beta.watchkitapp.watchkitextension": "match AdHoc com.xvia.TrackVia-Beta.watchkitapp.watchkitextension"
      }
  }
)
```

**Console log:**

```
[12:41:59]: Generated plist file with the following values:
[12:41:59]: ▸ -----------------------------------------
[12:41:59]: ▸ {
[12:41:59]: ▸   "method": "ad-hoc",
[12:41:59]: ▸   "signingStyle": "manual",
[12:41:59]: ▸   "provisioningProfiles": {
[12:41:59]: ▸     "com.xvia.TrackVia-Beta": "match AdHoc *",
[12:41:59]: ▸     "com.xvia.TrackVia-Beta.watchkitapp": "match AdHoc com.xvia.TrackVia-Beta.watchkitapp",
[12:41:59]: ▸     "com.xvia.TrackVia-Beta.watchkitapp.watchkitextension": "match AdHoc com.xvia.TrackVia-Beta.watchkitapp.watchkitextension",
[12:41:59]: ▸     "*": "match AdHoc *",
[12:41:59]: ▸     "com.xvia.TrackVia-Develop.watchkitapp": "match AdHoc com.xvia.TrackVia-Develop.watchkitapp",
[12:41:59]: ▸     "com.xvia.TrackVia-Develop.watchkitapp.watchkitextension": "match AdHoc com.xvia.TrackVia-Develop.watchkitapp.watchkitextension"
[12:41:59]: ▸   }
[12:41:59]: ▸ }
[12:41:59]: ▸ -----------------------------------------
```

Also not sure why my develop profiles get returned in the adhoc case since I'm not explicitly specifying them?

Happy to provide more insight, frustrated we haven't had much luck doing AdHoc or AppStore archives with Fastlane for quite a few months!

**Comment by trackvia-ios** [comment]
Upgrading to Fastlane `2.88.0` resulted in some more promising logs, but still resulted in the same error state :(

**Comment by joshdholtz** [comment]
@trackvia-ios Can you try removing `method: "ad-hoc",` from your `export_options`?

**Comment by Matsepura** [comment]
Same issue since 2.62.0 + versions =(

**Comment by trackvia-ios** [comment]
@joshdholtz @KrauseFx  I've removed `export_method` from all places and still seeing the exact same results. Seems to be adding `ad-hoc` automatically:

```
[15:44:54]: Generated plist file with the following values:
[15:44:54]: ▸ -----------------------------------------
[15:44:54]: ▸ {
[15:44:54]: ▸   "signingStyle": "manual",
[15:44:54]: ▸   "provisioningProfiles": {
[15:44:54]: ▸     "com.XXX.App-Beta": "match AdHoc *",
[15:44:54]: ▸     "com.XXX.App-Beta.watchkitapp": "match AdHoc com.XXX.App-Beta.watchkitapp",
[15:44:54]: ▸     "com.XXX.App-Beta.watchkitapp.watchkitextension": "match AdHoc com.XXX.App-Beta.watchkitapp.watchkitextension",
[15:44:54]: ▸     "*": "match AdHoc *",
[15:44:54]: ▸     "com.XXX.App-Develop.watchkitapp": "match AdHoc com.XXX.App-Develop.watchkitapp",
[15:44:54]: ▸     "com.XXX.App-Develop.watchkitapp.watchkitextension": "match AdHoc com.XXX.App-Develop.watchkitapp.watchkitextension"
[15:44:54]: ▸   },
[15:44:54]: ▸   "method": "ad-hoc"
[15:44:54]: ▸ }

```

It seems undesired for it to be adding my **Develop** provisioning profiles in with my Beta profiles, perhaps that's what's causing error? I'm ONLY specifying beta options in my export_options mapping.

Also to note, I'm NOT using an export options plist, but the `export_options` hash option.

Let me know if I can provide anymore insight @Matsepura @joshdholtz

**Comment by trackvia-ios** [comment]
It seems even if I completely remove everything from my Gymfile, and strip Gym to the following:

```
gym(
    scheme: scheme,
    archive_path: "./#{scheme}",
    output_name: scheme,
    configuration: configuration)
```

I see more red error output regarding:

```
[09:53:11]: There seems to be a mismatch between your provided `export_method` in gym
[09:53:11]: and the selected provisioning profiles. You passed the following options:
```

But it's still using the same generated plist file...

I'm going to try creating a static plist file and load that to see if it doesn't auto-set the "method"

**Comment by trackvia-ios** [comment]
Doing some digging, it appears the `package_command_generator_xcode7` is always setting the `export_method`:

```ruby

```

I set `method` to an empty string in my exportOptions, but it seems no matter what I do, it still gets method `ad-hoc`, everytime.

Any other suggestions as to what to try?

**Comment by joshdholtz** [comment]
@trackvia-ios Are you running either `match` or `sigh` before you call `gym`?

**Comment by trackvia-ios** [comment]
Thanks for getting back, @joshdholtz  and yes, just for reference we have had all of our deployments working in the past for Development, Ad Hoc, and App Store using Fastlane previously.

```ruby
match(git_branch: "master", 
team_id: "REDACTED", 
team_name: "REDACTED", 
type: "adhoc", 
app_identifier: "com.xvia.TrackVia-Beta.watchkitapp", 
readonly: readonly, 
force_for_new_devices: true, 
keychain_name: keychain_name, 
keychain_password: keychain_password)
```

Is type `adhoc` here causing problem?

**Comment by trackvia-ios** [comment]
I think this line:

`Actions.lane_context[SharedValues::SIGH_PROFILE_TYPE] = profile_type`

inside `sync_code_signing.rb` is the one that's automatically assigning type "ad-hoc" based on the match provisioning?

**Comment by joshdholtz** [comment]
@trackvia-ios Can I ask why you are trying to do `export_method: "development"` with `adhoc` profiles? 🙃

**Comment by trackvia-ios** [comment]
@joshdholtz sorry for the delay. I'm not intending to do `export_method: "development"` with `adhoc` profiles. I was just demonstrating to you that I am able to archive no problem my Debug, development target via gym, but every time I switch to `ad-hoc` and/or `Release`, the automatic provisioning profiles that are selected are incorrect, and I cannot pass my own `export_options` plist because it seems to always be overridden regardless of what I provide (explicit map in Ruby or plist).

Any suggestions would be great. I've tried to follow the latest Xcode 9 codesigning guidelines on Fastlane docs but still must be missing one final piece.

Thanks!
