### ISSUE TITLE
Snapshot for iOS and tvOS

### ISSUE THREAD

**Issue by deepaksahu-mob-ibtech** [fastlane/fastlane#10775]
How can I manage app for iOS and tvOS on same project,  I am trying to capture screenshot for iOS and tvOS.

**iOS**
#A list of devices you want to take the screenshots from
 devices([
    "iPhone 8 Plus",
   "iPhone 7",
   "iPhone 5",
   "iPad Pro (12.9-inch)",
    "iPad Pro (9.7-inch)"
 ])

How do i update on runtime device list in Snapfile to capture screenshot for each platform.

**tvOS**

#A list of devices you want to take the screenshots from
 devices([
   "Apple TV 4K"
 ])

**Comment by ohayon** [comment]
Hey @deepaksahu-mob-ibtech have you tried just putting "AppleTV 4K" in the bigger list of iOS devices? Do your targets have different bundle ids?
