### ISSUE TITLE
Call "sub action" from Fastfile

### ISSUE THREAD

**Issue by vikeri** [fastlane/fastlane#10779]
How can I call a "sub action" from my Fastfile? 

I want to call  `fastlane pilot distribute` but from within my Fastfile. I managed to import the class using `require "pilot"` and then run `Pilot::BuildManager.new...` but then I had to define all my options again. I would like to have my already predefined options sourced from Fastlane.

**Comment by ohayon** [comment]
Hey @vikeri, you should be able to do that with a Fastfile like this:

```
lane :upload_to_testflight do
  pilot(<any params you need>)
end
```

And then you can execute it with `fastlane upload_to_testflight` on your command line.

Let us know if that works fr yu!

**Comment by vikeri** [comment]
@ohayon Then I'm only calling the main fastlane pilot task (`fastlane pilot`), I want to call the _sub task_: `distribute`. That I call from the command line like this `fastlane pilot distribute`.

**Comment by ohayon** [comment]
Ah, got it. So you can you use the Fastfile that I mentioned above and make the pilot call look like this: `pilot(distribute_external: true)`

**Comment by vikeri** [comment]
@ohayon Ok, but how do I run for example `pilot builds`?

**Comment by ohayon** [comment]
That can be done by using another option that you can pass to `pilot`. Have a look at https://docs.fastlane.tools/actions/pilot/#pilot to see all the different options you have. Let us know if you have any more questions! 🚀

**Comment by vikeri** [comment]
How? I have looked at the docs and none of the parameters are `build`?

**Comment by ohayon** [comment]
Ah, my apologies, for something like that, the best thing to do would be to call into the library directly. If you have a look at the code for that action here https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/commands_generator.rb#L76 you can see how it works to implement some similar code in your Fastfile.

**Comment by vikeri** [comment]
I managed to import the class using `require "pilot"` and then run `Pilot::BuildManager.new...` but then I had to define all my options again. I would like to have my already predefined options sourced from Fastlane

**Comment by sharat** [comment]
@vikeri @ohayon I am also looking for a solution for a similar problem. In my case I am trying to list all the builds uploaded using fastlane pilot builds. What's the elegant way to recreate existing options from fastlane core?

**Comment by yxztj** [comment]
Same question here. From command line I can call "fastlane pilot distribute -g xxx", but in Fastfile it's required to provide the path of ipa file while I'm trying to distribute a previously uploaded build.

**Comment by vikeri** [comment]
There has been no solution to this yet, I'm on the latest version of fastlane

**Comment by taquitos** [comment]
As you probably found, pilot `BuildManager` has a `.config` attribute on it which gets populated when actions are run. 

I don't think you can access the instance of `BuildManager` that is created when pilot runs, but if you could, you would be able to grab the config and use it again.

This isn't really something we support, but maybe you can use `FastlaneCore::Configuration` to load configuration, then you'd be able to access `.config_file_options` with all the values.

**Comment by xster** [comment]
use case: you don't want to give your CI bot write permissions to your repo so when you deploy a new version, you want to check `fastlane pilot builds` first to check existing builds to +1 the build number to avoid version collisions when pushing to TestFlight.
