### ISSUE TITLE
gym export failing with "Bundle only contains bitcode-marker" error

### ISSUE THREAD

**Issue by dpassage** [fastlane/fastlane#10788]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I attempt to build and export my app in `development` mode using `gym`, the `xcodebuild -exportArchive` fails with the following error:

```
2017-11-02 12:54:51.394 xcodebuild[36302:1333431] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7fb583caac00>: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in opus.framework/opus:
error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.iiO/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in opus.framework/opus:
error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.iiO/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)

}
```

Doing the archive and export directly in Xcode succeeds without error.

My gym command is: `gym(export_method: "development", export_options: { combileBitcode: false, uploadBitcode: false }, scheme: "XXX")
`

For the main app and the rest of the project, `ENABLE_BITCODE` is set to `No`. However, the framework above is a pre-compiled binary which evidently includes bitcode.

##### Complete output when running fastlane, including the stack trace and command used

<details><summary>output<summary>

```
INFO [2017-11-02 13:02:19.65]: ▸ Archive Succeeded
DEBUG [2017-11-02 13:02:19.91]: Stored the archive in: /Users/davidp/Library/Developer/Xcode/Archives/2017-11-02/XXX 2017-11-02 12.58.07.xcarchive
WARN [2017-11-02 13:02:19.91]: Generated plist file with the following values:
INFO [2017-11-02 13:02:19.91]: ▸ -----------------------------------------
INFO [2017-11-02 13:02:19.91]: ▸ {
INFO [2017-11-02 13:02:19.91]: ▸   "combileBitcode": false,
INFO [2017-11-02 13:02:19.91]: ▸   "uploadBitcode": false,
INFO [2017-11-02 13:02:19.91]: ▸   "provisioningProfiles": {
INFO [2017-11-02 13:02:19.91]: ▸     "com.xxx.XXX": "match Development com.xxx.XXX",
INFO [2017-11-02 13:02:19.91]: ▸     "com.xxx.XXXUITests": "match Development com.xxx.XXXUITests",
INFO [2017-11-02 13:02:19.91]: ▸     "com.xxx.$(PRODUCT_NAME:rfc1034identifier)": "match AdHoc com.xxx.XXX"
INFO [2017-11-02 13:02:19.91]: ▸   },
INFO [2017-11-02 13:02:19.91]: ▸   "method": "development",
INFO [2017-11-02 13:02:19.91]: ▸   "signingStyle": "manual"
INFO [2017-11-02 13:02:19.91]: ▸ }
INFO [2017-11-02 13:02:19.91]: ▸ -----------------------------------------
INFO [2017-11-02 13:02:19.91]: This results in the following plist file:
INFO [2017-11-02 13:02:19.91]: ▸ -----------------------------------------
INFO [2017-11-02 13:02:19.91]: ▸ <?xml version="1.0" encoding="UTF-8"?>
INFO [2017-11-02 13:02:19.91]: ▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
INFO [2017-11-02 13:02:19.91]: ▸ <plist version="1.0">
INFO [2017-11-02 13:02:19.91]: ▸ <dict>
INFO [2017-11-02 13:02:19.91]: ▸ 	<key>combileBitcode</key>
INFO [2017-11-02 13:02:19.91]: ▸ 	<false/>
INFO [2017-11-02 13:02:19.91]: ▸ 	<key>method</key>
INFO [2017-11-02 13:02:19.91]: ▸ 	<string>development</string>
INFO [2017-11-02 13:02:19.91]: ▸ 	<key>provisioningProfiles</key>
INFO [2017-11-02 13:02:19.91]: ▸ 	<dict>
INFO [2017-11-02 13:02:19.91]: ▸ 		<key>com.xxx.$(PRODUCT_NAME:rfc1034identifier)</key>
INFO [2017-11-02 13:02:19.91]: ▸ 		<string>match AdHoc com.xxx.XXX</string>
INFO [2017-11-02 13:02:19.91]: ▸ 		<key>com.xxx.XXX</key>
INFO [2017-11-02 13:02:19.91]: ▸ 		<string>match Development com.xxx.XXX</string>
INFO [2017-11-02 13:02:19.91]: ▸ 		<key>com.xxx.XXXUITests</key>
INFO [2017-11-02 13:02:19.91]: ▸ 		<string>match Development com.xxx.XXXUITests</string>
INFO [2017-11-02 13:02:19.91]: ▸ 	</dict>
INFO [2017-11-02 13:02:19.91]: ▸ 	<key>signingStyle</key>
INFO [2017-11-02 13:02:19.91]: ▸ 	<string>manual</string>
INFO [2017-11-02 13:02:19.91]: ▸ 	<key>uploadBitcode</key>
INFO [2017-11-02 13:02:19.91]: ▸ 	<false/>
INFO [2017-11-02 13:02:19.91]: ▸ </dict>
INFO [2017-11-02 13:02:19.91]: ▸ </plist>
INFO [2017-11-02 13:02:19.91]: ▸ -----------------------------------------
+--------------------------------------+--------------------------------------+
|                          Generated Package Command                          |
+--------------------------------------+--------------------------------------+
| Option                               | Value                                |
+--------------------------------------+--------------------------------------+
| /usr/bin/xcrun                       |                                      |
| /Users/davidp/ios-client/xcode9/Nav  |                                      |
| dyClient-iOS/vendor/bundle/ruby/2.4  |                                      |
| .0/gems/fastlane-2.63.0/gym/lib/ass  |                                      |
| ets/wrap_xcodebuild/xcbuild-safe.sh  |                                      |
| -exportArchive                       |                                      |
| -exportOptionsPlist                  | /var/folders/_z/vxkm582x22l475ckgwt  |
|                                      | g79tm0000gn/T/gym_config20171102-39  |
|                                      | 194-if11gz.plist                     |
| -archivePath                         |                                      |
| /Users/davidp/Library/Developer/Xco  |                                      |
| de/Archives/2017-11-02/XXX\  |                                      |
| 2017-11-02\ 12.58.07.xcarchive       |                                      |
| -exportPath                          | /var/folders/_z/vxkm582x22l475ckgwt  |
|                                      | g79tm0000gn/T/gym_output20171102-39  |
|                                      | 194-r6ngru                           |
+--------------------------------------+--------------------------------------+
INFO [2017-11-02 13:02:19.92]: $ /usr/bin/xcrun /Users/davidp/ios-client/xcode9/XXX-iOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.63.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/gym_config20171102-39194-if11gz.plist' -archivePath /Users/davidp/Library/Developer/Xcode/Archives/2017-11-02/XXX\ 2017-11-02\ 12.58.07.xcarchive -exportPath '/var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/gym_output20171102-39194-r6ngru' 
INFO [2017-11-02 13:02:19.94]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/gym_config20171102-39194-if11gz.plist -archivePath '/Users/davidp/Library/Developer/Xcode/Archives/2017-11-02/XXX 2017-11-02 12.58.07.xcarchive' -exportPath /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/gym_output20171102-39194-r6ngru
INFO [2017-11-02 13:02:20.67]: ▸ 2017-11-02 13:02:20.670 xcodebuild[49096:1377799] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XXX_2017-11-02_13-02-20.670.xcdistributionlogs'.
INFO [2017-11-02 13:02:51.52]: ▸ 2017-11-02 13:02:51.525 xcodebuild[49096:1377799] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f9c002c1990>: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in opus.framework/opus:
INFO [2017-11-02 13:02:51.52]: ▸ error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.39f/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)
INFO [2017-11-02 13:02:51.52]: ▸ " UserInfo={NSLocalizedDescription=Failed to verify bitcode in opus.framework/opus:
INFO [2017-11-02 13:02:51.52]: ▸ error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.39f/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)
INFO [2017-11-02 13:02:51.52]: ▸ }
INFO [2017-11-02 13:02:51.52]: ▸ error: exportArchive: Failed to verify bitcode in opus.framework/opus:
INFO [2017-11-02 13:02:51.52]: ▸ error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.39f/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)
INFO [2017-11-02 13:02:51.52]: ▸ Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in opus.framework/opus:
INFO [2017-11-02 13:02:51.52]: ▸ error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.39f/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)
INFO [2017-11-02 13:02:51.52]: ▸ " UserInfo={NSLocalizedDescription=Failed to verify bitcode in opus.framework/opus:
INFO [2017-11-02 13:02:51.52]: ▸ error: Bundle only contains bitcode-marker /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/XcodeDistPipeline.39f/Root/Payload/XXX.app/Frameworks/opus.framework/opus (armv7)
INFO [2017-11-02 13:02:51.52]: ▸ }
INFO [2017-11-02 13:02:51.52]: ▸ ** EXPORT FAILED **
```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                     |
| --------------------------- | ------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                   |
| Ruby                        | 2.4.1                                                                     |
| Bundler?                    | true                                                                      |
| Git                         | git version 2.14.1                                                        |
| Installation Source         | ~/ios-client/xcode9/XXX-iOS/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib                                        |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                                               |
| Is contained                | false                                                                     |
| Is homebrew                 | false                                                                     |
| Is installed via Fabric.app | false                                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                               |
| Xcode Version               | 9.1                                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# xxx iOS Client Build Script

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.63.0"

default_platform :ios
require_relative './add_missing_devices'
require_relative './spaceship_helpers'

platform :ios do
  before_all do
    APP_BUILD_NUMBER = "#{ENV['BUILD_NUMBER']}"
    # ENV['XCODE_XCCONFIG_FILE'] = "#{ENV['PWD']}/fastlane/no_bitcode.xcconfig"
  end

  # This allows us to bypass setting/retrieving cocoapods keys from the Keychain.
  # When invoked, it will prompt for CocoapodsSecretsVaultPassword
  # which is used to decrypt the cocoapods-secrets.yml file. Once correct value is provided,
  # it will be saved in the login Keychain for future use.
  desc "Add cocoapods keys as environment variables"
  lane :setup_cocoapods_keys_env do
      require_relative "./setup_cocoapods_keys_env"
  end

  desc "Error-resilient cocoapods update"
  lane :update_cocoapods do
    setup_cocoapods_keys_env
    begin
      cocoapods
    rescue
      cocoapods(repo_update: true)
    end
    # sh "git status"
    # sh "git diff"
    # ensure_git_status_clean
  end

  desc "Add new devices from devicesToAdd.txt"
  lane :register_new_devices do
    register_devices(
      # format of this file is UDID\tDEVICENAME
      devices_file: "./devicesToAdd.txt"
    )
  end

  desc "Pull Request build & test"
  lane :pull_request do 
    update_cocoapods
    increment_build_number build_number: APP_BUILD_NUMBER
    sh "cd .. && ./download-here-library.sh"
    match_development
    # scan(scheme: "XXX",
    #      workspace: "XXX.xcworkspace",
    #      output_types: "junit",
    #      output_directory: "test-report",
    #      buildlog_path: "build_logs")
    gym(export_method: "development", export_options: { combileBitcode: false, uploadBitcode: false }, scheme: "XXX")
  end

  desc 'Match development - forces nuke + update if new devices present'
  lane :match_development do
    begin
      HockeyAppDevices.add_missing_devices
      if SpaceshipHelpers.development_profile_needs_update?
        SpaceshipHelpers.delete_development_profiles
        match(type: "development", app_identifier: ["com.xxx.XXX", "com.xxx.XXXUITests"], force: true)
      else
        raise "no update needed"
      end
    rescue
      match(type: "development", app_identifier: ["com.xxx.XXX", "com.xxx.XXXUITests"], readonly: true)            
    end
  end

end

# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxx.XXX" # The bundle identifier of your app
# apple_id "sohail@xxx.com" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.63.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.0        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| oroku_saki                | 1.1.1        |
| ansible-vault             | 0.2.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| cocoapods                 | 1.3.1        |
| dotenv                    | 2.2.1        |
| osx_keychain              | 1.0.1        |
| cocoapods-keys            | 2.0.0        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| httparty                  | 0.15.6       |
| psych                     | 2.2.4        |
</details>

*generated on:* **2017-11-02**
</details>

**Comment by dpassage** [comment]
More detail:

* With Xcode 8.3, the export succeeds correctly.
* With Xcode 9.0, `xcodebuild` crashes with a segmentation fault.

**Comment by ohayon** [comment]
Hey @dpassage - does this execute successfully when you use Xcode directly?

**Comment by dpassage** [comment]
Yes, it does.

**Comment by dpassage** [comment]
More fun; it appears that the library being complained about contains no `__LLVM` segment, meaning that there isn't any bitcode in it, not even the bitcode marker.

For reference, it comes from here: https://github.com/chrisballinger/Opus-iOS

**Comment by dpassage** [comment]
And now here's the exciting part: while the source binary framework embedded in the Cocoapod does _not_ have an `__LLVM` segment, the file which `xcodebuild` is complaining about does. Smells like it may not be `fastlane`'s fault after all.
