### ISSUE TITLE
[pilot] submitting build with no `ITSAppUsesNonExemptEncryption` incorrectly claims `Successfully distributed build to Internal testers`

### ISSUE THREAD

**Issue by marco-piccolino** [fastlane/fastlane#10784]
When I run `fastlane pilot` (fastlane 2.63.0) on an iOS app whose `Info.plist` does not contain `ITSAppUsesNonExemptEncryption`, I get the following output:

`Successfully distributed build to Internal testers`

whereas Apple requires to input the value of `ITSAppUsesNonExemptEncryption` from iTunesConnect's UI before making the build available to internal testers.

**Comment by ohayon** [comment]
Hmmm, could you please share the output from your terminal when you run this command with `--verbose`? Also would be helpful to see the output of `fastlane env`. Thanks! 🚀
