### ISSUE TITLE
Where can i set the environment variables?

### ISSUE THREAD

**Issue by esbenr** [fastlane/fastlane#10781]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Get get an error when trying to upload successful build using `pilot`.
I know I'm missing the password for my iTunesConnect account and that it can be set using environment variables.

My question is: Where can i set the environment variables?

Found great help in the Credentials Manager, but still no help on where.

I would really like to set the variables in my shell script in the Jenkins job. But I'm having trouble finding out how the syntax should be.

<img width="462" alt="screen shot 2017-11-02 at 16 02 44" src="https://user-images.githubusercontent.com/560120/32333117-5bfa4d94-bfe7-11e7-9d31-674c3f92474a.png">

We're doing some custom stuff in setup.sh before initiating our pipeline via a rake script.
Would it be possible to set the environment variable as in the screenshot - before initiating our build?
How is the syntax supposed to be here?

##### Complete output when running fastlane, including the stack trace and command used

`[15:44:23]: Login to iTunes Connect (secretemail)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager`

**Comment by ohayon** [comment]
Hey @esbenr - the best way to handle this is to allow your credentials to be store in the keychain of the Jenkins machine. If you would like to use environment variables instead, you could use something like https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin to setup Jenkins to store environment variables. One other option would be to preface your `rake` command like so: `FASTLANE_PASSWORD="password" rake create_release_ipa` *OR* you could also just put `export` in front of that first line of your command, which would look like: `export FASTLANE_PASSWORD="password`. Let us know if that helps! 🚀

**Comment by esbenr** [comment]
I made it work with export FASTLANE_PASSWORD="password". What tricked me was that I had spaces around the equal sign. Thanks.
