### ISSUE TITLE
TestFlight- there is no web session to update error

### ISSUE THREAD

**Issue by ninaa0718** [fastlane/fastlane#10782]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when running "fastlane TestFlight upload" I get the following error:
there is no web session to update
It was working earlier

### Environment

[| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.6                                      |
| Ruby                        | 2.4.1                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.15.0                           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane          |
| Host                        | Mac OS X 10.12.6 (16G29)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/xcode8.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.62.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 1.15.4       |
| io-console            | 0.4.6        |
| slack-notifier        | 1.5.1        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.2.8        |
| terminal-notifier     | 1.8.0        |
| terminal-table        | 1.8.0        |
| plist                 | 3.3.0        |
| CFPropertyList        | 2.3.5        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| highline              | 1.7.8        |
| commander-fastlane    | 4.4.5        |
| unf_ext               | 0.0.7.4      |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| dotenv                | 2.2.1        |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| json                  | 2.1.0        |
| excon                 | 0.59.0       |
| openssl               | 2.0.3        |
| tty-screen            | 0.5.1        |
| faraday               | 0.13.1       |
| little-plugger        | 1.1.4        |
| logging               | 2.2.2        |
| os                    | 0.9.6        |
| googleauth            | 0.6.1        |
| signet                | 0.8.1        |
| faraday_middleware    | 0.12.2       |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
| unicode-display_width | 1.3.0        |
</details>

**Comment by ohayon** [comment]
Hey @ninaa0718 - could you send the output from your command line? Sometimes Apple's APIs throw this error intermittently, hopefully it will resolve on it's own, otherwise, having the full output would be helpful 🐙

**Comment by ninaa0718** [comment]
I am seeing same error while running output from command line "your request cannot be completed
-no web session to update"
