### ISSUE TITLE
FR: Omit fastlane installation instructions from autogenerated fastlane docs

### ISSUE THREAD

**Issue by ILI4S** [fastlane/fastlane#10785]
The fact that fastlane is able to autogenerate documentation for lanes is brilliant. However, installation instructions vary from team to team. For example, we use bundler. 

In general, some projects are known to maintain their own installation instructions for their repository's dependencies, which can make the generated instructions very misleading for developers that are still being onboarded. 

I'd like to contribute a PR to specify fastlane NOT include installation instructions at the top of the generated `README.md`.

**Comment by ohayon** [comment]
Hey @ILI4S - I totally understand this can be confusing, but we do think its helpful for a lot of our users. Do you think that we could just change the text to say something like "Common installation instructions, your team may use a different method" or something to that end?

**Comment by ILI4S** [comment]
@ohayon thanks for your response

I completely agree it’s helpful for many users. I meant my feature request as an opt-in setting for fastlane.

Your suggestion is valid, too. What about placing the instructions below the lane documentation?
