### ISSUE TITLE
storing json_key file

### ISSUE THREAD

**Issue by MaxToyberman** [fastlane/fastlane#10798]
### Issue Description

According to the Docs in my Appfile I need to add json_key_file file path locally.
I don't think that it is a good practice to upload my private key to GitHub. 
What are the best practices working with this file . (Maybe encrypt and upload it ?)

**Comment by MaxToyberman** [comment]
@joshdholtz Thanks ! , what about encrypting the file ? like we do here with iOS certificates

**Comment by joshdholtz** [comment]
@MaxToyberman There is a plugin available that I think might be what you are looking for? https://github.com/hjanuschka/fastlane-plugin-cryptex
