### ISSUE TITLE
download_dsyms action for tvos platform

### ISSUE THREAD

**Issue by fassko** [fastlane/fastlane#10794]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

**download_dsyms** right now only supports **ios** platform. Would be great to add also this action for **tvos** platform.

P.S. I'm will try to solve this myself as I need it. :)

**Comment by fassko** [comment]
It turns out that it does support tvos, just it should be named as **appletvos**.

Anyone knows how Supported platforms is generated in docs? https://docs.fastlane.tools/actions/download_dsyms/#download_dsyms

**Comment by milch** [comment]
The docs are generated here: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/ActionDetails.md.erb#L22

As you can see the docs are created by calling the `is_supported?` method on the action. It seems that the `download_dsyms` action does support `appletvos`: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/download_dsyms.rb#L198
