### ISSUE TITLE
Expose new Swift toolchain flag for Xcode 7.3

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#1079]
In the new `xcodebuild` we will be able to specify which version of swift we wish to use. This is just a note to add support for it, once Xcode 7.3 is released.

**Comment by KrauseFx** [comment]
What would you like? A new action for setting it?

**Comment by jcampbell05** [comment]
@KrauseFx On reflection this issue would be better for `gym`. We should add an extra flag for gym which will pass the toolchain of swift to use, (Unless Gym just accepts the same flags that xcodebuild does).

We should expose this new flag to the `gym` action.

**Comment by KrauseFx** [comment]
Sounds like a great idea. Do you have the know-how to do that? :rocket:

**Comment by jcampbell05** [comment]
@KrauseFx  Should be straight forward, I'll give it a go :)

**Comment by jcampbell05** [comment]
@KrauseFx Sorry, I let this slip and since xcode 7.3 is released we should defiantly implement this.

**Comment by KrauseFx** [comment]
Oh yeah :sparkles:

**Comment by nafu** [comment]
@KrauseFx 

Could you check the PR https://github.com/fastlane/fastlane/pull/5864?
I think this can solve this issue.

**Comment by TKBurner** [comment]
@nafu Thanks so much for the work there! Glad to see it got merged 👍 👍 💯
