### ISSUE TITLE
Snapshot: Add timeout for tests

### ISSUE THREAD

**Issue by IchHabRecht** [fastlane/fastlane#10791]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Du to my hardware limitation I have sometimes the problem that the app under test doesn't get started in the simulator of Xcode 9. Running the tests is currently impossible because those ghost tests might block snapshot for hours. It would be really great to be able to define some timeout limits, either per test and/or for the run of the whole test case.

**Comment by ohayon** [comment]
Hey @IchHabRecht - could you elaborate a bit more on what the restriction is and what you mean by "ghost tests"? Just want to make sure we fully understand the issue before working on a solution 😄

**Comment by IchHabRecht** [comment]
Hi @ohayon,

With "ghost tests" I mean the start of the application under test. If you start the UI tests, first the test application is started and afterwards your real app is started multiple times (in case you have more than one test function in your test suite). Sometimes those app start fails on my system and the test process runs forever without any notification.

**Comment by IchHabRecht** [comment]
I bought a new Mac and now I'm unable to reproduce failing tests :-) Closing this ticket for now.
