### ISSUE TITLE
 [!] Unauthorized (Google::Apis::AuthorizationError)

### ISSUE THREAD

**Issue by mrkd** [fastlane/fastlane#10795]
I am getting this Unauthorized error when running supply on a second Android app.

It works fine on my first app - but is error out on the second one.

I am using the same json-key for both. 

### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

/Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:212:in `check_status': [!] Unauthorized (Google::Apis::AuthorizationError)
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/api_command.rb:118:in `check_status'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:183:in `process_response'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:299:in `execute_once'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:101:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:93:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.13.6/generated/google/apis/androidpublisher_v2/service.rb:210:in `insert_edit'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/client.rb:92:in `block in begin_edit'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/client.rb:367:in `call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/client.rb:92:in `begin_edit'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.63.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.1                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.1 (17B48)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.63.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(task: "assembleRelease")
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    supply(apk: apk_path, track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "secrets/<json file name redacted" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "<package name redacted>" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.63.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.0        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-11-03**
</details>

**Comment by mrkd** [comment]
This was a permission issue on my end. Closing.

**Comment by manyasone** [comment]
I am facing a similar issue - could you tell me, how you solved it?

**Comment by KrauseFx** [comment]
This seems like it's not a fastlane issue, make sure your permissions are correct, and also [search for the error string](https://www.google.at/search?q=Unauthorized+(Google::Apis::AuthorizationError)+&gws_rd=cr&dcr=0&ei=WjI6Wt_IN8jSwQLTvaTYBw) 👍

**Comment by hrushie** [comment]
@mrkd Can you please let me know what permissions you have to give? Thanks

**Comment by thao33** [comment]
@mrkd Could you tell me how you solved it? I am now facing a similar issue

**Comment by albinekb** [comment]
I have the same issue, how did you fix it?

**Comment by hrushie** [comment]
So apparently u need to have full account privileges.

**Comment by mrkd** [comment]
@hrushie Yes - that was the issue. I had access only set to the first app. I changed that to give it access to all apps and it worked for me.
