### ISSUE TITLE
Ask for text message during authenticating 2FA

### ISSUE THREAD

**Issue by fxfactorial** [fastlane/fastlane#10790]
When running `fastlane spaceauth -u some_name@foo.com`, you get prompted for a 6 digit token. However that token doesn't often come for me or is just delayed. On the web interface with apple when prompted, you can ask them to force send the token to your phone number. Is there a `fastlane spaceauth` exposure of that option as well?

**Comment by ohayon** [comment]
Hey @fxfactorial - that option is not available in fastlane currently, I think the best workaround if youre not getting the message would be to go to the web and force a new code to be sent from Apple as you mentioned. Let us know if thats helpful! 🚀
