### ISSUE TITLE
ios: app_identifier not forwarded from Appfile to Fastfile

### ISSUE THREAD

**Issue by mkozjak** [fastlane/fastlane#10803]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [*] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [*] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

For some reason, `fastlane beta` is not getting app_identifier when getting to gym.
I get an error: `Code Signing Error: Bundle identifier is missing. Leti doesn't have a bundle identifier for the Release build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor...`

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

DEBUG [2017-11-05 22:54:25.98]: Checking if there are any plugins that should be loaded...
INFO [2017-11-05 22:54:26.03]: -------------------------------------------------
INFO [2017-11-05 22:54:26.03]: --- Step: Verifying required fastlane version ---
INFO [2017-11-05 22:54:26.03]: -------------------------------------------------
INFO [2017-11-05 22:54:26.03]: Your fastlane version 2.28.7 matches the minimum requirement of 2.28.7  ✅
INFO [2017-11-05 22:54:26.03]: ------------------------------
INFO [2017-11-05 22:54:26.03]: --- Step: default_platform ---
INFO [2017-11-05 22:54:26.03]: ------------------------------
INFO [2017-11-05 22:54:26.03]: Driving the lane 'ios beta' 🚀
INFO [2017-11-05 22:54:26.04]: -----------------
INFO [2017-11-05 22:54:26.04]: --- Step: gym ---
INFO [2017-11-05 22:54:26.04]: -----------------
INFO [2017-11-05 22:54:26.69]: $ xcodebuild -list -project ./Leti.xcodeproj -configuration Release
INFO [2017-11-05 22:54:28.62]: $ xcodebuild -showBuildSettings -scheme Leti -project ./Leti.xcodeproj -configuration Release

+----------------------+--------------------------------------+
|                   Summary for gym 2.28.7                    |
+----------------------+--------------------------------------+
| export_method        | app-store                            |
| configuration        | Release                              |
| project              | ./Leti.xcodeproj                     |
| scheme               | Leti                                 |
| destination          | generic/platform=iOS                 |
| output_name          | Leti                                 |
| build_path           | /Users/mkozjak/Library/Developer/Xc  |
|                      | ode/Archives/2017-11-05              |
| clean                | false                                |
| output_directory     | .                                    |
| silent               | false                                |
| skip_package_ipa     | false                                |
| use_legacy_build_api | false                                |
| buildlog_path        | ~/Library/Logs/gym                   |
| xcode_path           | /Applications/Xcode.app              |
+----------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -scheme Leti                         |                      |
| -project ./Leti.xcodeproj            |                      |
| -configuration Release               |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/mkozjak/Library/Developer/Xc  |                      |
| ode/Archives/2017-11-05/Leti\        |                      |
| 2017-11-05\ 22.54.30.xcarchive       |                      |
| archive                              |                      |
| | tee                                |                      |
| /Users/mkozjak/Library/Logs/gym/Let  |                      |
| i-Leti.log                           |                      |
| | xcpretty                           |                      |
+--------------------------------------+----------------------+
INFO [2017-11-05 22:54:30.43]: $ set -o pipefail && xcodebuild -scheme Leti -project ./Leti.xcodeproj -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/mkozjak/Library/Developer/Xcode/Archives/2017-11-05/Leti\ 2017-11-05\ 22.54.30.xcarchive archive | tee /Users/mkozjak/Library/Logs/gym/Leti-Leti.log | xcpretty
INFO [2017-11-05 22:54:30.77]: ▸ 2017-11-05 22:54:30.775 xcodebuild[9259:20383894] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Vicious.xcplugin' not present in DVTPlugInCompatibilityUUIDs
INFO [2017-11-05 22:54:31.38]: ▸ Aggregate Leti/Qt Preprocess [Release]
INFO [2017-11-05 22:54:31.42]: ▸ Check Dependencies
INFO [2017-11-05 22:54:31.42]: ▸ Running script 'Qt Qmake'
INFO [2017-11-05 22:54:31.60]: ▸ Running script 'Qt Preprocessors'
INFO [2017-11-05 22:54:31.71]: ▸ Building Leti/Leti [Release]
INFO [2017-11-05 22:54:31.71]: ▸ Check Dependencies
INFO [2017-11-05 22:54:31.72]: ▸ ** ARCHIVE FAILED **
INFO [2017-11-05 22:54:31.72]: ▸ The following build commands failed:
INFO [2017-11-05 22:54:31.72]: ▸ Check dependencies
INFO [2017-11-05 22:54:31.72]: ▸ (1 failure)
2017-11-05 22:54:30.775 xcodebuild[9259:20383894] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Vicious.xcplugin' not present in DVTPlugInCompatibilityUUIDs
▸ Aggregate Leti/Qt Preprocess [Release]
▸ Check Dependencies
▸ Running script 'Qt Qmake'
▸ Running script 'Qt Preprocessors'
▸ Building Leti/Leti [Release]
▸ Check Dependencies
** ARCHIVE FAILED **


The following build commands failed:
Check dependencies
(1 failure)
ERROR [2017-11-05 22:54:31.75]: Exit status: 65
WARN [2017-11-05 22:54:31.75]: 📋  For a more detailed error log, check the full log at:
WARN [2017-11-05 22:54:31.75]: 📋  /Users/mkozjak/Library/Logs/gym/Leti-Leti.log

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.28.7                  |
| sdk         | iPhoneOS11.0.sdk        |
+-------------+-------------------------+

WARN [2017-11-05 22:54:31.78]: Lane Context:
INFO [2017-11-05 22:54:31.78]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2017-11-05 22:54:31.78]: Error building the application - see the log above
INFO [2017-11-05 22:54:31.79]: Successfully generated documentation at path '/opt/dev/github.com/qaap/leti/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | gym                 | 5           |
+------+---------------------+-------------+

ERROR [2017-11-05 22:54:31.80]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    # scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
      export_method: "app-store",
      configuration: "Release"
    )

    # pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "my.identifi.er" # The bundle identifier of your app
apple_id "my.id@apple.com" # Your Apple email address

team_id "TEAM_ID" # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.7  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2017-11-05**
</details>

**Comment by mkozjak** [comment]
If I manually insert an identifier in Info.plist, then it works. Seems like it's ignoring Appfile altogether. Am I doing anything wrong?

**Comment by joshdholtz** [comment]
@mkozjak The `Apple` will not *insert* an app identifier into your Xcode project and/or plist. The `app_identifier` is used to communicate with the iOS Developer Center and iTunesConnect APIs to make sure that the proper app information is uploaded/download. You *should* be putting your app identifier into the `Info.plist` so your fix is the correct thing to do 👍
