### ISSUE TITLE
pilot `Could not receive latest API key from iTunes Connect, this might be a server issue.`

### ISSUE THREAD

**Issue by esbenr** [fastlane/fastlane#10808]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to use ´pilot´to upload to iTunes Connect, I get the following error.
Found another issue around same topic, but it was locked so it is not possible to elaborate on that.

I suspect that this is caused by us having strict firewall rules on out CI.
What host names should I whitelist in order for gelt uploadting to testflight to work?

Kind regards,
Esben

##### Complete output when running fastlane, including the stack trace and command used
[09:40:11]: Login to iTunes Connect (dbaselenium1@gmail.com)
Operation timed out - SSL_connect
Operation timed out - SSL_connect
Operation timed out - SSL_connect
Operation timed out - SSL_connect
Operation timed out - SSL_connect
+--------------------+------------------------------------------------------------------------------------------------+
|                                                    [33mLane Context[0m                                                     |
+--------------------+------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                            |
| PLATFORM_NAME      | ios                                                                                            |
| LANE_NAME          | ios create_release_ipa                                                                         |
| BUILD_NUMBER       | 26                                                                                             |
| IPA_OUTPUT_PATH    | /Volumes/Data/Slave/workspace/DBA-Next-Release-Upload/Scripts/output/ipa.root/dba.ipa          |
| DSYM_OUTPUT_PATH   | /Volumes/Data/Slave/workspace/DBA-Next-Release-Upload/Scripts/output/ipa.root/dba.app.dSYM.zip |
| XCODEBUILD_ARCHIVE | /Users/jenkins/Library/Developer/Xcode/Archives/2017-11-06/dba 2017-11-06 09.29.42.xcarchive   |
+--------------------+------------------------------------------------------------------------------------------------+
[10:53:13]: [31mCould not receive latest API key from iTunes Connect, this might be a server issue.[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcode_select                        | 0           |
| 4    | increment_build_number              | 6           |
| 5    | gym                                 | 629         |
| 6    | upload_symbols_to_crashlytics       | 15          |
| 💥   | [31mpilot[0m                               | 4380        |
+------+-------------------------------------+-------------+

[10:53:13]: [31mfastlane finished with errors[0m

### Environment

Ruby: 2.3.1
OpenSSL: 1.0.2j

**Comment by KrauseFx** [comment]
Could you give it a try on a Mac without a strict firewall, e.g. on an iPhone hotspot?
