### ISSUE TITLE
Version code not updating on fabric

### ISSUE THREAD

**Issue by dheerajsinghanktech** [fastlane/fastlane#10806]
Hello,

After updating android studio to 3.0 and build gradle classpath to 'com.android.tools.build:gradle:3.0.0', Version code always remain same 1.0(1) for every build, While  the correct Versioncode is showing on running app

Thanks

**Comment by nirukk52** [comment]
I also ran into same issue.. It seems that after the update android studio 3.0 has changed the location of the apk
Now it is in app--> release--> .apk

So, you must be actually uploading the same apk again.

**Comment by dheerajsinghanktech** [comment]
Right apk is uploading on Fabric beta, Download same apk from beta app showing correct version code and all changes inside app

**Comment by joshdholtz** [comment]
@dheerajsinghanktech I am not _super_ familiar with crashlytics but what do you mean by `Version code always remain same 1.0(1)`? Do you mean that its not showing the correct name/version in the crashlytics web dashboard?

**Comment by dheerajsinghanktech** [comment]
@joshdholtz Yes its not showing the correct version code in the crashlytics web dashboard. For example in my current build version name is 1.0 and version code is 100, but its showing 1.0(1) in crashlytics dashboard. This was perfect before upgrading to android studio 3.0 and gradle to latest version.

Thanks

**Comment by joshdholtz** [comment]
@dheerajsinghanktech This sounds like it would be an issue with Android Studio and/or the output paths that `gradle` task is outputting (assuming you are using `gradle`). The `crashlytics` action simply uploads from an APK path context that `gradle` creates.

To debug this issue myself, I would personally try commenting out `crashlytics` and printing out `Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]` and `Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATHS]` to see the APKs that `gradle` is outputting and that `crashlytics` would be intaking to make sure its actually outputting the correct APK and then manually upload that APK to crashlytics to make (bypassing the action) to make sure that that works as expected.

**Comment by cpetzel** [comment]
I am seeing this problem as well.

**Comment by cpetzel** [comment]
I fixed this by removing the ```manifestPath``` in the crashlytics config of my build gradle. 

```
crashlytics {
    enableNdk true
    //manifestPath 'src/main/AndroidManifest.xml' //REMOVE ME
}
```

This was causing crashlytics to always use the old manifest file which doesn't have the version_code and version_name in it. Gradle slaps those in as a build artifact in ``app/build/intermediates/manifests/...```

So by removing this line from our config, crashlytics will then use the correctly generated manifest from gradle tasks .
