### ISSUE TITLE
FASTLANE_SESSION not working for two factor security

### ISSUE THREAD

**Issue by jliebrand** [fastlane/fastlane#10802]
I can't get my CircleCI to build using fastlane; or rather any time it needs to talk to the portal it fails because of the two factor security. I've created a token (a couple of times now) and added it as the FASTLANE_SESSION env var. I've also echo'd that variable out to double check circle ci didn't do any string substitution on it, and it is fine.

But every time it gets near doing anything with itunes connect (match, or cert, or anything really), it fails with the following error:
```
[10:47:27]: Starting login with user 'foobar@my-app.com'
Two Factor Authentication for account 'foobar@my-app.com' is enabled
Your session cookie has been expired.
Please enter the 6 digit code: 
```

One thing I did notice, after reading through all other related issues, is that the token spaceauth created for me does not have expiry field set. Instead it has max_age set. The example tokens I've seen posted in other issues seem to have expiry set, not max_age. Could that be related? Also, I appear to get two cookies printed out, not just one. Although I tried deleting the second but that didn't do anything either
```
Pass the following via the FASTLANE_SESSION environment variable:
---\n- !ruby/object:HTTP::Cookie\n  name: DES5ffc13031df8f1ee5275a7fa86e3310f3\n  value: HSARMTKNSRVTWFla9ob2eyS0YRC3pWRJLweYSC4+wiPIy8TkUDDJy9VLx/9jhWBGqzLBARWc0c0JZb46OjE7iD4eeJ/GROnaNXqoSIjEsmusUEbxS/atPsPmCfrqTrmb4nJbBoKxoCH7sPY=SRVT\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 2592000\n  created_at: 2017-10-25 18:25:18.837741000 +01:00\n  accessed_at: 2017-11-05 18:54:58.762727000 +00:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ1bjJXTlA2VEktcG9pRnotcnVYbkxRIn0.cdkERul-_F_3YWrGlIZFiz0XMui0vqsgaLYWr3WzZAE\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2017-11-05 18:55:01.459120000 +00:00\n  accessed_at: *1\n
```

Here's the output from env:
```
[10:47:23]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 10.12.6                                             |
| Ruby                        | 2.3.5                                               |
| Bundler?                    | true                                                |
| Git                         | git version 2.13.6 (Apple Git-96)                   |
| Installation Source         | ~/MyApp/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                            |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.5/lib                            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                         |
| Is contained                | false                                               |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode-9.1.app/Contents/Developer/     |
| Xcode Version               | 9.1                                                 |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.63.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "MyApp")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number(build_number: ENV['CIRCLE_BUILD_NUM'])
    # match(type: "appstore")
    cert
    sigh
    gym(scheme: "MyApp") # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.my-app.app" # The bundle identifier of your app
apple_id "foobar@my-app.com" # Your Apple email address

team_id "BJN4K6YKG7" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.63.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2017-11-05**
</details>
```

**Comment by KrauseFx** [comment]
Hey @jliebrand, thanks for submitting this issue. There can be various reasons for this, one of them is that the session is region specific, so if Circle has their servers in the US, and you're based somewhere else, this might cause issues. The simplest solution is to create a separate account that has access to the apps you want to control, don't enable 2 step there, but have a long-randomly generated password instead, and use that for fastlane also. This way you can control where this account has access to.

**Comment by jliebrand** [comment]
Thanks for the reply @KrauseFx , but i'm not sure that will work for us. We have a business account with Apple, which does not allow us to turn off 2 factor auth. And the point of the biz account is to distribute the apps under that account specifically.

**Comment by abuturla** [comment]
@KrauseFx Can you clarify the following:

> don't enable 2 step there, but have a long-randomly generated password instead, and use that for fastlane also. This way you can control where this account has access to.

Will Fastlane work if 2 factor auth is enabled? What do you mean by **control where this account has access to**?

**Comment by meiyussk** [comment]
I am setting up fastlane for a new project on a brand new machine so I do have the latest fastlane and this issue just happened to me: 
Going to upload updated app to iTunes Connect
[23:37:13]: Your account has 2 step verification enabled
[23:37:13]: Please go to https://appleid.apple.com/account/manage
[23:37:13]: and generate an application specific password for
[23:37:13]: the iTunes Transporter, which is used to upload builds
[23:37:13]: To set the application specific password on a CI machine using
[23:37:13]: an environment variable, you can set the
[23:37:13]: FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD variable
