### ISSUE TITLE
Crashlytics missing DSYMs for enterprise release ..

### ISSUE THREAD

**Issue by tarunn1** [fastlane/fastlane#10810]
I am trying to upload all DSYMs files while creating .ipa file for Enterprise release not for ITunes release ..  I am able to upload all my file manually and when I did that it's works fine but still showing missing DSYMs .. and also when I created new .ipa file again Fabric is not showing crash reports ..

can any one help me how to upload DSYMs file automatically for every build and when creating .ipa files ...  if i have to write script please let me know where do i have to..

**Comment by joshdholtz** [comment]
@tarunn1 Do you have `DEBUG_INFORMATION_FORMAT` set to `dwarf-with-dsym` in your build settings for your enterprise configuration?

**Comment by raghvendra** [comment]
I had same issue, after disabling bitcode it worked.
