### ISSUE TITLE
Firebase analytics not work after build by fastlane on itunesconnect

### ISSUE THREAD

**Issue by haidang1904** [fastlane/fastlane#10824]
I’m using firebase to tracking analytics on my iOS apps. My apps developed by xcode 9 and swift 3-4.0. When we run build on emulator or run derect on idevice. On the firebase console > stream view > we will see our devices testing are online on map view. But after submit build to itunesconnect, firebase analytics is not work.

**Comment by joshdholtz** [comment]
@haidang1904 Does this still happen if you make a build via Xcode directly and upload to iTunesConnect without fastlane?

**Comment by haidang1904** [comment]
@joshdholtz if I build via xcode directly and upload to iTunesconnect. firebase analytics working normaly. I found this issues many times ago. I alway update latest version of fastlane just hope fastlane fix this issues. recently, when i have thousands downloads app per days. I saw some my app on firebase anaylytics alway is 0 download. after update build without fastlane and direct xcode build. firebase report working again. I also test on some devices & apps build. the issues resutls same above. 
so, if anyone have found issues like me. please join this

**Comment by joshdholtz** [comment]
@haidang1904 This is _most likely_ a configuration issue either with how you are calling `gym` and/or within your Xcode config/target/build settings. If you are able to show me what your `Fastfile` looks like and how you are integrating and instantiating the firebase analytics framework I can try to help diagnose it.

`fastlane` shouldn't just disable / not-initialize a framework on its own so my gut feeling is an environment / configuration variable is just not properly getting set when building with `gym` 🙃
