### ISSUE TITLE
New tty-screen release available 

### ISSUE THREAD

**Issue by piotrmurach** [fastlane/fastlane#10820]
Hi there,

Just wanted to let you know that I've released [tty-screen v0.6.2](https://rubygems.org/gems/tty-screen) which among many things, provides few more checks for terminal size on Unix like systems. I have thoroughly tested the library on Windows, Mac OS and Debian. In your case, the API stays the same so all you need to do is bump the version up and all should work just fine.

I'm happy to submit PR if you need me to?

**Comment by KrauseFx** [comment]
Hey @piotrmurach, that's awesome, thanks for letting us know. Yeah, a PR would be welcome 👍

**Comment by piotrmurach** [comment]
@KrauseFx submitted

**Comment by piotrmurach** [comment]
@KrauseFx @joshdholtz Any chance on merging my PR? It fixes important issues and improves terminal size detection. Pretty please 🙏
