### ISSUE TITLE
Feature: Restart simulator if test hangs

### ISSUE THREAD

**Issue by nickolas-pohilets** [fastlane/fastlane#10822]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We are using `scan` for running UI tests in Jenkins. Sometimes, when the SUT crashes, test execution just hangs until the entire job is killed by Jenkins due to timeout. That's is pretty inconvenient, as this loses all the information about the test results.

There is a known workaround for this: shutting down the device makes test manager proceed to the next test and continue execution.

This leads to the following idea: insert a new command in the `xcodebuild` -> `tee` -> `xcpretty` pipeline. That command should listen to its input and shutdown the device if no input is coming for a specified amount of time.

I can implement this and submit a PR, but I wanted to discuss the idea with the community first. So, any feedback is more than welcomed.

**Comment by KrauseFx** [comment]
Hey @nickolas-pohilets, really sorry for the delay here, we must have missed your proposal. Is this still an issue, and is this still something you're interested in preparing a PR for? Also, what's the best way for me to reproduce the issue?

**Comment by nickolas-pohilets** [comment]
For our project, I solved this by calling xcodebuild directly, without scan(). To reproduce the issue, you can run `scan()` for UI tests with SUT doing NSAssert(NO).

I wrote a simple C program that copies data from stdin to stdout, while monitoring activity of stdin in a background thread. It takes two arguments - a timeout in seconds (180), and a command to execute (`xcrun simctl shutdown DEVICE_ID`). If stdin is blocked for the specified amount of seconds then the command is executed. Shutting down device make test runner continue to the next test and boot device again. Reliability of this workaround is questionable, but for now, it solves the problem.

I'm hardly an expert in Ruby, but few tips from the community and some googling I probably can make a PR.

I need to update code of the `scan()` command and somehow ship that command with Fastlane. Not sure what would be the best way to do later. Shall I ship it as C code and compile when installing, or ship as a binary, or re-write in Ruby?

**Comment by getaaron** [comment]
I think you should be able to write that in Ruby. Would be nice to avoid introducing additional languages if possible.

Will this rerun the test that didn’t finish?

**Comment by nickolas-pohilets** [comment]
No, test manager will move to the next test.
