### ISSUE TITLE
Creating TestFlight groups using Pilot or Spaceship

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#10829]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Is it possible to create a new group in TestFlight using either Fastlane or Spaceship? When you create a new app on iTunes Connect, there are no default external groups (there are no groups at all). Therefore, you are not able to add any external testers for the specific app.  When I use the following Fastlane command for a newly created app:
`fastlane pilot add emailaddress -a "BundleID" -g "GroupName"` (with or without the group flag)
I get the following error:
There are no groups available matching the name passed to the ':groups' option.

I have looked through the documents and the source code, and I can't seem to find anything? Is this possible? Or do you always need to create new groups using iTC?

**Comment by mooshee** [comment]
I have a similar issue when importing.  I imagine its the same issue underneath.  When trying to import a list of testers using the `pilot import -c testers.csv`, every user that belongs to a group that does not currently exist in ITC spits out an error message, such as `Could not add user@email.com to app: App Name`.  If I go into ITC and manually create the groups, it works fine.

**Comment by pparmaei** [comment]
This is still an issue, no support for this feature has been added with the latest fastlane version

**Comment by kevinm90** [comment]
Any news on that? Or any ideas how this can be worked around, e.g. via spaceship?

**Comment by KrauseFx** [comment]
Yeah, that works fine with _spaceship_

```ruby
   context '.create!' do
      it 'returns an existing group with the same name' do
        group = Spaceship::TestFlight::Group.create!(app_id: 'app-id', group_name: 'Group 1')
        expect(group.name).to eq('Group 1')
        expect(group.id).to eq(1)
        expect(group).to be_instance_of(Spaceship::TestFlight::Group)
      end

      it 'creates the group for correct parameters' do
        group = Spaceship::TestFlight::Group.create!(app_id: 'app-id', group_name: 'group-name')
        expect(group.name).to eq('group-name')
        expect(group.id).to eq(3)
        expect(group).to be_instance_of(Spaceship::TestFlight::Group)
      end
    end

    context '.default_external_group' do
      it 'returns the default external group' do
        group = Spaceship::TestFlight::Group.default_external_group(app_id: 'app-id')
        expect(group).to be_instance_of(Spaceship::TestFlight::Group)
        expect(group.id).to eq(1)
      end
    end

    context '.filter_groups' do
      it 'applies block and returns filtered groups' do
        groups = Spaceship::TestFlight::Group.filter_groups(app_id: 'app-id') { |group| group.name == 'Group 1' }
        expect(groups).to be_instance_of(Array)
        expect(groups.size).to eq(1)
        expect(groups.first.id).to eq(1)
      end
    end
```

**Comment by pparmaei** [comment]
Thank you @KrauseFx  
That worked, I do know how we missed this when we were searching earlier.
Also thank you for all the work with Fastlane generally!
