### ISSUE TITLE
When uploading to s3 app versionbuild are not recognized

### ISSUE THREAD

**Issue by jaroslavas** [fastlane/fastlane#1083]
I have several targets/app versions. And one of them uploads perfectly (`deploy_web`), while other has problems with getting version (`deploy_web_staging`). 
After upload I get a folder named `vFile Doesn't Exist, Will Create:_bFile Doesn't Exist, Will Create:` uploaded and inside there is a file `FileDoesn'tExist,WillCreate:.plist`. Looks like there is a problem with getting apps version/build number.

Fastfile:

```
desc "Upload release version to our distribution website"
  lane :deploy_web do
    gym(
        scheme: "MyApp",
        use_legacy_build_api: true
    ) 
    s3(
      access_key: ENV['S3_ACCESS_KEY'],               
      secret_access_key: ENV['S3_SECRET_ACCESS_KEY'], 
      bucket: "my_bucket",       
      html_template_path: "fastlane/getapp-template.html"
    )
    clean_build_artifacts
  end

desc "Upload release version to our distribution website"
  lane :deploy_web_staging do
    gym(
        scheme: "MyApp Staging",
        use_legacy_build_api: true
    ) 
    s3(
      access_key: ENV['S3_ACCESS_KEY'],               
      secret_access_key: ENV['S3_SECRET_ACCESS_KEY'], 
      bucket: "mybucket/staging",       
      html_template_path: "fastlane/getapp-template.html"
    )
    clean_build_artifacts
  end
```

**Comment by vpolouchkine** [comment]
Can you share your version and the full log please?

**Comment by KrauseFx** [comment]
Could you try the most recent release from a few minutes ago?

**Comment by jaroslavas** [comment]
OK. after update I got a crash :)
Here is the number: b03a30196d511820bc47ebcb4b2cc494
I think now you have all the logs you need?

**Comment by jaroslavas** [comment]
Sorry, that was a crash because of the bug #780. After fixing that, I've tried to re-upload and now I get two folders on my s3: one with plist file and named correctly (`v1.0_b50`) and the second with ipa and dsym files but named incorrectly (`vFile Doesn't Exist, Will Create:_bFile Doesn't Exist, Will Create:`).
Should I send you the log from console or are there some logs saved automatically into files?

**Comment by vpolouchkine** [comment]
The log from the console. 👍

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
