### ISSUE TITLE
Docs regarding react-native setup

### ISSUE THREAD

**Issue by kaelumania** [fastlane/fastlane#10834]
I found this useful [Article](https://carloscuesta.me/blog/shipping-react-native-apps-with-fastlane/) to setup fastlane with react-native. I liked the idea to have one `Fastfile` for both platforms, but `fastlane init` guides to having separate `Fastfile`/Fastlane setups for each platform.

I would like to see a best practice established and hopefully documented in the official docs. That way, one could rely on one setup style and be sure it will be supported by fastlane in future releases.

**Comment by KrauseFx** [comment]
Yeah, agreed, having react native docs would be awesome. Unfortunately I don't have any React Native experience, so I'm not in a position where I'd feel comfortable defining those best practices

**Comment by janpio** [comment]
Hey @kaelumania, do you have experience with React Native? 
If yes, could you maybe create an example repository `react-native-fastlane` that follows the suggestions of this article and what you yourself learned about using fastlane? That would be a good start to jump start any documentation  effort.
