### ISSUE TITLE
Add missing UI docs

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#10835]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

The `UI` docs were removed by https://github.com/fastlane/fastlane/commit/2eb22ef562e5d2fcf088a765d97c0e49f83dd7d5 but not added to docs.fastlane.com.

**Comment by joshdholtz** [comment]
@revolter Created a PR for this https://github.com/fastlane/docs/pull/447
