### ISSUE TITLE
Pilot stuck on login

### ISSUE THREAD

**Issue by NateZ7** [fastlane/fastlane#10832]
I currently use fastlane for build, export ipa and deploy.
I'm stuck with the pilot as I want to upload to Testflight.

Everytime I run my lane, It get stuck on login, mostly on username, sometimes on password.

Output :
bash-3.2$ fastlane upl --verbose
[10:17:05]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-11-08 10:17:07.36]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
INFO [2017-11-08 10:17:07.64]: -------------------------------------------------
INFO [2017-11-08 10:17:07.64]: --- Step: Verifying required fastlane version ---
INFO [2017-11-08 10:17:07.64]: -------------------------------------------------
INFO [2017-11-08 10:17:07.64]: Your fastlane version 2.64.0 matches the minimum requirement of 1.109.0  ✅
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
INFO [2017-11-08 10:17:07.68]: ------------------------------
INFO [2017-11-08 10:17:07.68]: --- Step: default_platform ---
INFO [2017-11-08 10:17:07.68]: ------------------------------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
INFO [2017-11-08 10:17:07.69]: Driving the lane 'upl' 🚀
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
INFO [2017-11-08 10:17:07.74]: -------------------
INFO [2017-11-08 10:17:07.74]: --- Step: pilot ---
INFO [2017-11-08 10:17:07.74]: -------------------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/fastlane/Appfile'
-------
WARN [2017-11-08 10:17:07.76]: To not be asked about this value, you can specify it using 'username'
 [2017-11-08 10:17:07.76]: Your Apple ID Username: nativ@globekeeper.com
INFO [2017-11-08 10:17:12.54]: Login to iTunes Connect (nativ@globekeeper.com)

Fastlane env -

bash-3.2$ fastlane env
[10:19:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:19:57]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "f16787cd-62f5-4639-b016-43d833fc960c"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    scheme: "GlobeKeeper",
    export_method: "ad-hoc",
    export_xcargs: "-allowProvisioningUpdates",
    export_options:{
     provisioningProfiles: {
       "com.globekeeper.app" => "JenkinsAdHoc",
       "com.globekeeper.app.ShareExtension" => "JenkinsAdHocShared",
       "com.globekeeper.app.Widget" => "JenkinsAdHocWidget"
     }
   }
)

	end

lane :inst do
   install_on_device(
      device_id: "1b1c7237658ed2cd48b1ce579c1a2b115ba12012",
      ipa: "./GlobeKeeper.ipa"
  )

  # upload to Testflight
  # pilot(skip_waiting_for_build_processing: true)
 	
	end

lane :upl do
   pilot(skip_waiting_for_build_processing: true)

	end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-11-08**
</details>
[10:19:59]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.

Any help will be appreciated, thanks !

**Comment by NateZ7** [comment]
@fastlane-bot I dont think its related to code signing.

**Comment by NateZ7** [comment]
@fastlane-bot  OK I found the issue, I didn't have permissions for itunesconnect /:

Now im facing some other issues with the Pilot command.

Logs -

bash-3.2$ fastlane upl
[08:56:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:56:34]: -------------------------------------------------
[08:56:34]: --- Step: Verifying required fastlane version ---
[08:56:34]: -------------------------------------------------
[08:56:34]: Your fastlane version 2.64.0 matches the minimum requirement of 1.109.0  ✅
[08:56:34]: ------------------------------
[08:56:34]: --- Step: default_platform ---
[08:56:34]: ------------------------------
[08:56:34]: Driving the lane 'upl' 🚀
[08:56:34]: -------------------
[08:56:34]: --- Step: pilot ---
[08:56:34]: -------------------
[08:56:34]: Login to iTunes Connect (nativ@globekeeper.com)
[08:56:41]: Login successful
[08:56:42]: Ready to upload new build to TestFlight (App: 959396988)...
[08:56:42]: Going to upload updated app to iTunes Connect
[08:56:42]: This might take a few minutes. Please don't interrupt the script.
[08:57:03]: [Transporter Error Output]: description length:2656195
[08:58:19]: [Transporter Error Output]: ERROR ITMS-90432: "Invalid Swift Support. The file GlobeKeeper.app/Frameworks/NNLibraries.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."
[08:58:19]: [Transporter Error Output]: ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'GlobeKeeper.app/Frameworks/NNLibraries.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
[08:58:19]: [Transporter Error Output]: ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (226) that’s lower than the latest build number (228) that’s been submitted for the app version '1.93'."
[08:58:19]: [Transporter Error Output]: ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.93' is closed for new build submissions"
[08:58:19]: [Transporter Error Output]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.93] in the Info.plist file must contain a higher version than that of the previously approved version [1.93]."
[08:58:19]: Transporter transfer failed.
[08:58:19]: 
[08:58:19]: description length:2656195
ERROR ITMS-90432: "Invalid Swift Support. The file GlobeKeeper.app/Frameworks/NNLibraries.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'GlobeKeeper.app/Frameworks/NNLibraries.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (226) that’s lower than the latest build number (228) that’s been submitted for the app version '1.93'."
ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.93' is closed for new build submissions"
ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.93] in the Info.plist file must contain a higher version than that of the previously approved version [1.93]."
[08:58:19]: [iTMSTransporter] [2017-11-09 08:58:19 IST] <main>  INFO: Done performing authentication.

[08:58:19]: [iTMSTransporter] 

[08:58:19]: [iTMSTransporter] 

[08:58:19]: [iTMSTransporter] 

[08:58:19]: [iTMSTransporter] Package Summary:

[08:58:19]: [iTMSTransporter]  

[08:58:19]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[08:58:19]: [iTMSTransporter] 	/var/folders/27/xff25j752dl623vsvpwlql5r00008b/T/d20171109-25618-hm4c6q/959396988.itmsp - Error Messages:

[08:58:19]: [iTMSTransporter] 		description length:2656195

[08:58:19]: [iTMSTransporter] 		ERROR ITMS-90432: "Invalid Swift Support. The file GlobeKeeper.app/Frameworks/NNLibraries.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."

[08:58:19]: [iTMSTransporter] 		ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'GlobeKeeper.app/Frameworks/NNLibraries.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

[08:58:19]: [iTMSTransporter] 		ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (226) that’s lower than the latest build number (228) that’s been submitted for the app version '1.93'."

[08:58:19]: [iTMSTransporter] 		ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.93' is closed for new build submissions"

[08:58:19]: [iTMSTransporter] 		ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.93] in the Info.plist file must contain a higher version than that of the previously approved version [1.93]."

[08:58:19]: [iTMSTransporter] [2017-11-09 08:58:19 IST] <main> DBG-X: Returning 1

[08:58:19]: iTunes Transporter output above ^
[08:58:19]: description length:2656195
ERROR ITMS-90432: "Invalid Swift Support. The file GlobeKeeper.app/Frameworks/NNLibraries.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'GlobeKeeper.app/Frameworks/NNLibraries.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (226) that’s lower than the latest build number (228) that’s been submitted for the app version '1.93'."
ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.93' is closed for new build submissions"
ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.93] in the Info.plist file must contain a higher version than that of the previously approved version [1.93]."
\nERROR ITMS-90432: "Invalid Swift Support. The file GlobeKeeper.app/Frameworks/NNLibraries.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) versi\nERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'GlobeKeeper.app/Frameworks/NNLibraries.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bu\nERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.93] in the Info.plist file must contain a higher version than that of the previously approved version [1.93]."r the app version '1.93'."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+-----+
|      Lane Context      |
+------------------+-----+
| DEFAULT_PLATFORM | ios |
| PLATFORM_NAME    |     |
| LANE_NAME        | upl |
+------------------+-----+
[08:58:21]: Error uploading ipa file, for more information see above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | pilot                               | 104         |
+------+-------------------------------------+-------------+

[08:58:21]: fastlane finished with errors

[!] Error uploading ipa file, for more information see above





Will appreciate any help ! thanks !

**Comment by minuscorp** [comment]
Hello, in the logs you provide y can see several errors that are related with your project itself, you'd have the same errors if you try to upload the build manually. Check your build environment 🚀. I'll close this, feel free to open a new issue if you are having issues with fastlane!
