### ISSUE TITLE
Fix incorrect 2.64.0 release notes

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#10836]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

The [`2.64.0` release notes](https://github.com/fastlane/fastlane/releases/tag/2.64.0) have duplicated

> Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta

and missing

> Allow in app purchases check to be disabled via deliver (#10758) via Iulian Onofrei

**Comment by joshdholtz** [comment]
@revolter Sorry about that! Just fixed it 😊 Thanks for letting us know and for your contribution on #10758 ❤️
