### ISSUE TITLE
fastlane new version changes obscures error

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#10844]
Is that possible to move showing new versions information on fastlane up rather then bottom? since if you have an error it simply too hard to go up and find it, i would rather see a last message about my job status than new versions of fastlane ?

**Comment by joshdholtz** [comment]
@romk1n There is not a way to move it to the beginning right now but you can disable it by set an environment variable like this `FASTLANE_SKIP_UPDATE_CHECK=1` - https://docs.fastlane.tools/advanced/#skip-update-check-when-launching-fastlane

**Comment by joshdholtz** [comment]
@romk1n You can also use `FASTLANE_HIDE_CHANGELOG` to hide more information (which does clean the output response size a bit too)
