### ISSUE TITLE
fastlane capable of revoking push certificates? 

### ISSUE THREAD

**Issue by fxfactorial** [fastlane/fastlane#10848]
I am on `fastlane 2.64.0`, getting 

```
[!] You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one
```

And I know how to fix by revoking on website, but wondering, can fastlane revoke those certs programmatically or through CLI?

**Comment by joshdholtz** [comment]
@fxfactorial There is no way to remove non-expired push certs right now. I'm pretty sure `pem` can only renew expired ones (right now) 🙃
