### ISSUE TITLE
Not able to export ipa on xcode 9.1

### ISSUE THREAD

**Issue by klinkert0728** [fastlane/fastlane#10843]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) 

### Captured Output

Command Used: `ad_hoc`
<details><summary>Output/Log</summary>

```


+----------------+--------------------------------------+
|              Summary for produce 2.64.0               |
+----------------+--------------------------------------+
| username       | xxxxxx@xxxx.com             |
| app_identifier | com.knomatic.velocity.00000000.dev.  |
|                | CustomForm.3f0f5f03.Testing          |
| app_name       | GridTestSolution                     |
| app_version    | 2.29                                 |
| sku            | 1510085045                           |
| language       | English                              |
| team_id        | xxxxxxx                           |
| skip_itc       | true                                 |
| platform       | ios                                  |
| skip_devcenter | false                                |
+----------------+--------------------------------------+


+-------------------------------------+--------------------------------------+
|                          Summary for sigh 2.64.0                           |
+-------------------------------------+--------------------------------------+
| username                            | xxxxxx@xxxx.com             |
| app_identifier                      | com.knomatic.velocity.00000000.dev.  |
|                                     | CustomForm.3f0f5f03.Testing          |
| team_id                             | xxxxxxx                           |
| provisioning_name                   | GridTestSolution Provisioning        |
|                                     | Profile                              |
| adhoc                               | true                                 |
| force                               | true                                 |
| development                         | false                                |
| skip_install                        | false                                |
| ignore_profiles_with_different_name | false                                |
| skip_fetch_profiles                 | false                                |
| skip_certificate_verification       | false                                |
| platform                            | ios                                  |
| readonly                            | false                                |
+-------------------------------------+--------------------------------------+

/tmp/AdHoc_com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing.mobileprovision

+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.64.0                            |
+--------------------------------------+--------------------------------------+
| workspace                            | Velocity.xcworkspace                 |
| scheme                               | Velocity                             |
| configuration                        | Release                              |
| codesigning_identity                 | iPhone Distribution: Knomatic LLC    |
|                                      | (xxxxxxx)                         |
| clean                                | true                                 |
| silent                               | true                                 |
| include_bitcode                      | false                                |
| export_xcargs                        | -allowProvisioningUpdates            |
| xcargs                               | ENABLE_BITCODE=false                 |
| export_method                        | ad-hoc                               |
| export_options.provisioningProfiles  | VELOCITY_PROFILE_UDID                |
| .com.knomatic.velocity.00000000.dev  |                                      |
| .CustomForm.3f0f5f03.Testing         |                                      |
| destination                          | generic/platform=iOS                 |
| output_name                          | Velocity                             |
| build_path                           | /Users/danielklinkerthoufer/Library  |
|                                      | /Developer/Xcode/Archives/2017-11-0  |
|                                      | 8                                    |
| output_directory                     | .                                    |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| skip_profile_detection               | false                                |
| xcode_path                           | /Applications/Xcode.app              |
+--------------------------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -workspace Velocity.xcworkspace      |                      |
| -scheme Velocity                     |                      |
| -configuration Release               |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/danielklinkerthoufer/Library  |                      |
| /Developer/Xcode/Archives/2017-11-0  |                      |
| 8/Velocity\ 2017-11-08\              |                      |
| 13.54.11.xcarchive                   |                      |
| ENABLE_BITCODE=false                 |                      |
| clean                                |                      |
| archive                              |                      |
| CODE_SIGN_IDENTITY=iPhone\           |                      |
| Distribution:\ Knomatic\ LLC\        |                      |
| \(xxxxxxx\)                       |                      |
| | tee                                |                      |
| /Users/danielklinkerthoufer/Library  |                      |
| /Logs/gym/Velocity-Velocity.log      |                      |
| | xcpretty                           |                      |
+--------------------------------------+----------------------+
+--------------------------------------+--------------------------------------+
|                          Generated Package Command                          |
+--------------------------------------+--------------------------------------+
| Option                               | Value                                |
+--------------------------------------+--------------------------------------+
| /usr/bin/xcrun                       |                                      |
| /usr/local/lib/ruby/gems/2.4.0/gems  |                                      |
| /fastlane-2.64.0/gym/lib/assets/wra  |                                      |
| p_xcodebuild/xcbuild-safe.sh         |                                      |
| -exportArchive                       |                                      |
| -exportOptionsPlist                  | /var/folders/tr/hg1s4x_s78l2lflcj9m  |
|                                      | qwmjc0000gn/T/gym_config20171108-76  |
|                                      | 513-196s30f.plist                    |
| -archivePath                         |                                      |
| /Users/danielklinkerthoufer/Library  |                                      |
| /Developer/Xcode/Archives/2017-11-0  |                                      |
| 8/Velocity\ 2017-11-08\              |                                      |
| 13.54.11.xcarchive                   |                                      |
| -exportPath                          | /var/folders/tr/hg1s4x_s78l2lflcj9m  |
|                                      | qwmjc0000gn/T/gym_output20171108-76  |
|                                      | 513-121km8t                          |
| -allowProvisioningUpdates            |                                      |
| ENABLE_BITCODE=false                 |                                      |
+--------------------------------------+--------------------------------------+
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/tr/hg1s4x_s78l2lflcj9mqwmjc0000gn/T/gym_config20171108-76513-196s30f.plist -archivePath '/Users/danielklinkerthoufer/Library/Developer/Xcode/Archives/2017-11-08/Velocity 2017-11-08 13.54.11.xcarchive' -exportPath /var/folders/tr/hg1s4x_s78l2lflcj9mqwmjc0000gn/T/gym_output20171108-76513-121km8t -allowProvisioningUpdates ENABLE_BITCODE=false
2017-11-08 13:59:09.035 xcodebuild[78078:1432589] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/tr/hg1s4x_s78l2lflcj9mqwmjc0000gn/T/Velocity_2017-11-08_13-59-09.034.xcdistributionlogs'.
2017-11-08 13:59:11.032 xcodebuild[78078:1432589] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7f8e236bbd80>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
"Error Domain=IDEProfileLocatorErrorDomain Code=4 \"No \"iOS Ad Hoc\" profiles for team 'Knomatic LLC' matching 'VELOCITY_PROFILE_UDID' are installed.\" UserInfo={NSLocalizedDescription=No \"iOS Ad Hoc\" profiles for team 'Knomatic LLC' matching 'VELOCITY_PROFILE_UDID' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}"
)}
error: exportArchive: No "iOS Ad Hoc" profiles for team 'Knomatic LLC' matching 'VELOCITY_PROFILE_UDID' are installed.

Error Domain=IDEProfileLocatorErrorDomain Code=4 "No "iOS Ad Hoc" profiles for team 'Knomatic LLC' matching 'VELOCITY_PROFILE_UDID' are installed." UserInfo={NSLocalizedDescription=No "iOS Ad Hoc" profiles for team 'Knomatic LLC' matching 'VELOCITY_PROFILE_UDID' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}

** EXPORT FAILED **

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.64.0                  |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS11.1.sdk        |
+---------------+-------------------------+


+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 1    | produce | 3           |
| 2    | sigh    | 19          |
| 💥   | gym     | 304         |
+------+---------+-------------+



```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'faraday'
Faraday::Utils.default_params_encoder = Faraday::FlatParamsEncoder

lane :ad_hoc do

  produce(
    username: 'xxxxxx@xxxx.com',
    app_identifier: 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing',
    app_name: 'GridTestSolution',
    app_version: '2.29',
    sku: '1510085045',
    language: 'English',
    team_id: 'xxxxxxx',
    skip_itc: true
  )

  profile_udid = sigh(
    username: 'xxxxxx@xxxx.com',
    app_identifier: 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing',
    team_id: 'xxxxxxx',
    provisioning_name: 'GridTestSolution Provisioning Profile',
    output_path: '/tmp',
    adhoc: true,
    force: true
  )
  ENV["VELOCITY_PROFILE_UDID"] = profile_udid
  ENV["PRODUCT_BUNDLE_IDENTIFIER"] = 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing'
  puts ENV["VELOCITY_PROFILE_UDID"]
  
  gym(
    workspace: 'Velocity.xcworkspace',
    scheme: 'Velocity',
    configuration: 'Release',
    codesigning_identity: 'iPhone Distribution: Knomatic LLC (xxxxxxx)',
    clean: true,
    silent: true,
    include_bitcode: false,
    export_xcargs: "-allowProvisioningUpdates",
    xcargs: 'ENABLE_BITCODE=false',
    export_method: 'ad-hoc'
  )

  pem(
      app_identifier: 'com.knomatic.velocity.00000000.dev.CustomForm.3f0f5f03.Testing',
      username: 'xxxxxx@xxxx.com',
      generate_p12: true,
      pem_name: '3f0f5f03-201f-43bc-915f-ebb6e13177c2_Testing',
      development:false
  )

 crashlytics(
     api_token: ‘xxxxxxxx’,
     build_secret: ‘xxxxxxxxxx’,
     notifications:true
  )

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.5        |
| bigdecimal                | 1.3.0        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-11-08**
</details>

it  works great on xcode 8.3.3 not sure what am i missing

thank you in advance for any help

**Comment by klinkert0728** [comment]
yes i've seen the  Code Signing Troubleshooting Guide and still not luck

**Comment by joshdholtz** [comment]
@klinkert0728 Setting `ENV["VELOCITY_PROFILE_UDID"] = profile_udid` in your `Fastfile` does not create an environment variable for Xcode to see.

```sh
| export_method                        | ad-hoc                               |
| export_options.provisioningProfiles  | VELOCITY_PROFILE_UDID                |
| .com.knomatic.velocity.00000000.dev  |                                      |
| .CustomForm.3f0f5f03.Testing     
```

You can see here that the the output of `gym` does not show `VELOCITY_PROFILE_UDID` being evaluated. Setting `ENV` inside of your `Fastfile` only sets that inside of Ruby where `gym` ends up being a shelled out command to `xcodebuild` so those environment variables do not get shared.

Xcode and `gym` are smart enough (most of the time) to automatically figure out which provisioning profile to use so I would remove the `VELOCITY_PROFILE_UDID` from your build settings and getting the app building/signing properly in Xcode and then call `sigh` and `gym`.

**Comment by klinkert0728** [comment]
hey @joshdholtz  thank you very much for your help, i've been using this configuration with the env variable since 2 years ago, and on xcode 8.3.3 works fine. so is xcode 8.3.3 automatically figure out which provisioning profile to use and xcode 9 does not.
<img width="1010" alt="screen shot 2017-11-09 at 11 05 14" src="https://user-images.githubusercontent.com/6820828/32615561-16073e94-c53e-11e7-8d4f-55f61359ffa4.png">

 btw i found this in the fastlane documentation i know is deprecated but still works on xcode 8.3.3 just like i said, so that's not working in xcode 9

**Comment by joshdholtz** [comment]
@klinkert0728 Where in the fastlane documentation id you find this? Can you link me to this? 🙃

The best approach for signing in Xcode 9 is to use the export options like this - https://docs.fastlane.tools/actions/gym/#export-options. This solves the issue of xcode selecting the wrong profile and `gym` will automatically create this for you correctly most of the time but you can still specify it yourself.

**Comment by klinkert0728** [comment]
@joshdholtz  sure here's the link https://docs.fastlane.tools/codesigning/xcode-project/#set-using-environment-variable
i already tried that approach to define the provisioning profile mapping on the export-options in gym but still not luck.

**Comment by joshdholtz** [comment]
@klinkert0728 That approach should work with standard (and most) Xcode setups so there might be something else in your setup that is messing with things 🤔 Xcode 9 did make a big shift in code signing so it was a little work for all of us to change our implementations to work with it. After tweaking things, your should start seeing the  "generated plist" in the `gym` output showing a correct mapping for bundle id to provisioning profile name 💪

**Comment by klinkert0728** [comment]
@joshdholtz i see the generated plist with the gym since the archive succeeded, if i run fastlane with xcode 8.3.3 selected i have the same plist as with xcode 9 both have the provisional profile dictionary with the correct bundle id and the env variable VELOCITY_PROFILE_UDID,  but with xcode 9 i have a new key called  signingStyle: "manual", not sure if that related. thanks man really appreciate you taking time to try to fix this. i'll keep trying

**Comment by joshdholtz** [comment]
@klinkert0728 Not a problem at all! Code signing will always be tricky. It still get tripped over it sometimes 😇  But I got faith in you. You got this! 💪

**Comment by shubhSaxena** [comment]
@joshdholtz i am facing same issue on xcode 9.0.1, i am able to archive and export build using xcode but on running following command to generate and export build, it fails to export but successfully archives it.

`fastlane gym build --workspace "projectDirectory" --scheme "SchemeName" --codesigning_identity "SigningCerti" --buildlog_path "BuildLogPath" --output_directory "BuildPath" --output_name "Name" --clean --verbose  --export_method ad-hoc --destination "generic/platform=appletvos"`

Here is the build env:
`+---------------+-------------------------+
|            [32m[33mBuild environment[0m            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.64.0                  |
| export_method | ad-hoc                  |
| sdk           | AppleTVOS11.0.sdk       |
+---------------+-------------------------+`

Here is the output log:
`
Error Domain=IDEProvisioningErrorDomain Code=9 ""SchemeNameShelf.appex" requires a provisioning profile with the App Groups feature." UserInfo={NSLocalizedDescription="SchemeNameShelf.appex" requires a provisioning profile with the App Groups feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

error: exportArchive: "SchemeName.app" requires a provisioning profile with the App Groups feature.

Error Domain=IDEProvisioningErrorDomain Code=9 ""SchemeName.app" requires a provisioning profile with the App Groups feature." UserInfo={NSLocalizedDescription="SchemeName.app" requires a provisioning profile with the App Groups feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

** EXPORT FAILED **`

It shows error for provisioning profile with App Groups feature but it is already present in the profile. Using xcode with this same provisioning profile, build can be archived and exported but not through fastlane.

**Comment by ecoopnet** [comment]
+1. 
I have same problem.
