### ISSUE TITLE
[snapshot] support for built-for-testing, test-without-building

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#10849]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Snapshot compiles the the app for each device.
It's just so slow and wasteful.

This has previously been looked into but doesn't seem to have been actioned for snapshot?

https://github.com/fastlane/fastlane/pull/7131

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.6                                       |
| Ruby                        | 2.4.1                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.10.1                            |
| Installation Source         | /usr/local/bin/fastlane                       |
| Host                        | Mac OS X 10.12.6 (16G29)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode91.app/Contents/Developer/ |
| Xcode Version               | 9.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.3       |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-11-08**
</details>

**Comment by Jules2010** [comment]
@hjanuschka any thoughts?

**Comment by Jules2010** [comment]
@KrauseFx This would really speed up the process which for me take a few hours :(

I know this was added to scan, but even building once would be a big improvement.

**Comment by janpio** [comment]
To be honest I am not really sure what you need from reading this issue. Could you edit it to include all relevant information. Same for your "this was added to scan" comment, could you provide a link to the PR or changelog for context?

From what I _did_ understand I agree that this would be useful. But so someone can pick this up, the issue has to be simple and clear to understand.

**Comment by evgeny-sureev** [comment]
I am making snapshots without rebuilding for each iteration with this script:

```
    scan(
      scheme: "DemoApp Snapshots",
      derived_data_path: "my_derived_data",
      build_for_testing: true,
      configuration: "Debug",
      devices: ["iPhone 6", "iPhone 6 Plus", "iPhone SE", "iPad Pro (9.7-inch)", "iPad Pro (12.9-inch)", "iPhone X"]
    )
    capture_ios_screenshots(
      scheme: "DemoApp Snapshots",
      test_without_building: true,
      derived_data_path: "my_derived_data",
      devices: ["iPhone 6", "iPhone 6 Plus", "iPhone SE", "iPad Pro (9.7-inch)", "iPad Pro (12.9-inch)", "iPhone X"]
    )
```
