### ISSUE TITLE
Could not receive latest API key from iTunes Connect, this might be a server issue.

### ISSUE THREAD

**Issue by feargswalsh92** [fastlane/fastlane#10842]
I'm following [this](https://medium.com/react-native-training/fastlane-for-react-native-ios-android-app-devops-8ca85bee614e) guide to integrate Fastlane into React Native, when I get to the match setup though things get hairy. Do I need to set up distribution and development profiles within itunes connect or can I do it through itunes connect?

```
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring nokogiri-1.8.0 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.0
/Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'slack-notifier' (< 2.0.0, >= 1.3) among 136 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/feargalwalsh/.rvm/gems/ruby-2.2.3:/Users/feargalwalsh/.rvm/gems/ruby-2.2.3@global', execute `gem env` for more information
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /Users/feargalwalsh/.rvm/gems/ruby-2.2.3/bin/fastlane:22:in `<main>'
	from /Users/feargalwalsh/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/feargalwalsh/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

```

```
[14:09:46]: Seems like launching fastlane takes a while - please run
[14:09:46]: 
[14:09:46]: $ [sudo] gem cleanup
[14:09:46]: 
[14:09:46]: to uninstall outdated gems and make fastlane launch faster
[14:09:46]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[14:09:46]: To get started with a Gemfile, run
[14:09:46]: 
[14:09:46]: $ bundle init
[14:09:46]: $ echo 'gem "fastlane"' >> Gemfile
[14:09:46]: $ bundle install
[14:09:46]: 
[14:09:46]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[14:09:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-----------------------+----------------+
|        Summary for match 2.64.0        |
+-----------------------+----------------+
| type                  | appstore       |
| git_branch            | master         |
| keychain_name         | login.keychain |
| readonly              | false          |
| verbose               | false          |
| force                 | false          |
| skip_confirmation     | false          |
| shallow_clone         | false          |
| clone_branch_directly | false          |
| force_for_new_devices | false          |
| skip_docs             | false          |
| platform              | ios            |
+-----------------------+----------------+

[14:09:50]: To not be asked about this value, you can specify it using 'git_url'
[14:09:50]: URL to the git repo containing all the certificates: https://github.com/rozalado/match
[14:10:04]: Cloning remote git repo...
[14:10:04]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:10:05]: 🔓  Successfully decrypted certificates repo
[14:10:05]: To not be asked about this value, you can specify it using 'username'
[14:10:05]: Your Apple ID Username: feargswalsh@gmail.com
[14:10:16]: Verifying that the certificate and profile are still valid on the Dev Portal...
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Looking for related GitHub issues on fastlane/fastlane...

➡️  Unable to connect to itunes connect - Environment issue
    https://github.com/fastlane/fastlane/issues/9109 [closed] 5 💬
    6 weeks ago

➡️  Confusion about setting SSL Options
    https://github.com/fastlane/fastlane/issues/10261 [closed] 3 💬
    a week ago

➡️  Jenkins/Deliver: Operation timed out - connect(2)
    https://github.com/fastlane/fastlane/issues/6862 [closed] 2 💬
    02 Feb 2017

and 1 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Could%20not%20receive%20latest%20API%20key%20from%20iTunes%20Connect,%20this%20might%20be%20a%20server%20issue.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Could not receive latest API key from iTunes Connect, this might be a server issue.
```

**Comment by feargswalsh92** [comment]
@fastlane-bot  Yes I did 
fastlane env
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring nokogiri-1.8.0 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.0
/Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'slack-notifier' (< 2.0.0, >= 1.3) among 136 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/feargalwalsh/.rvm/gems/ruby-2.2.3:/Users/feargalwalsh/.rvm/gems/ruby-2.2.3@global', execute `gem env` for more information
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /Users/feargalwalsh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /Users/feargalwalsh/.rvm/gems/ruby-2.2.3/bin/fastlane:22:in `<main>'
	from /Users/feargalwalsh/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/feargalwalsh/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by joshdholtz** [comment]
@feargswalsh92 It doesn't look like you have `fastlane` properly installed. It looks like some Ruby gems aren't properly built and it appears that you may not have `openssl` properly installed. There are docs here for installing `fastlane` properly (and in different ways) - https://docs.fastlane.tools/#choose-your-installation-method

`fastlane env` should be outputting some nice debug information that pastes nicely into the Github issue with system and fastlane information. I would try following the `fastlane` installation from the docs and then following that guide on how to interact with React Native.

Happy fastlaning! 🚀

**Comment by KrauseFx** [comment]
Also, this section might be helpful :) https://docs.fastlane.tools/faqs/#im-getting-an-ssl-error

**Comment by feargswalsh92** [comment]
Internet points for one and all!

**Comment by feargswalsh92** [comment]
@joshdholtz I uninstalled fastlane and started following the steps in the docs as regards setting up fastlane. I ran 
`gem pristine ffi --version 1.9.18 `
and 
`gem pristine nokogiri --version 1.8.0 ` 
 to get rid of those errors but the slack notifier one is persisting.

**Comment by joshdholtz** [comment]
@feargswalsh92 Doing `gem install fastlane` should automaticaly have installed the `slack-notifier` dependency for you 🤔 Did you try running `gem install slack-notifier` and if so, what happened?

**Comment by feargswalsh92** [comment]
Thanks that worked, running into further issues down the line but I've got the bit between my teeth now!

**Comment by joshdholtz** [comment]
@feargswalsh92 Glad to hear! Going to close this for now. Happy fastlaning! 🚀
