### ISSUE TITLE
One more question today :)

### ISSUE THREAD

**Issue by iDevPro** [fastlane/fastlane#10857]
This is not a problem, but rather a question:
- How can I use this tool to catch the moment of page turning in UIPageViewController in the screen shot?

**Comment by joshdholtz** [comment]
@iDevPro This question is not _really_ a fastlane question - fastlane just handles taking the screenshots. This is somethign that you can probably find better answers for on stackoverflow or just by experimenting yourself. You can probably put execute the screenshot after a certain amount of time after the animation starts or listen for an animation callback maybe but this is out of the realm of fastlane 🙃

Happy screenshotting and fastlaning! 🚀
