### ISSUE TITLE
Export IPA ad-hoc works, app-store doesn't

### ISSUE THREAD

**Issue by NateZ7** [fastlane/fastlane#10855]
Hi, I'm able to export an IPA using ad-hoc, but app-store not working...
I can't figure it out. Insights will be appreciated.
I need the above in order  to upload to testflight.

Output -

[16:18:22]: Generated plist file with the following values:
[16:18:22]: ▸ -----------------------------------------
[16:18:22]: ▸ {
[16:18:22]: ▸   "provisioningProfiles": {
[16:18:22]: ▸     "com.globekeeper.app": "com.globekeeper.app AppStore",
[16:18:22]: ▸     "com.globekeeper.app.ShareExtension": "JenkinsAppStoreShare",
[16:18:22]: ▸     "com.globekeeper.app.Widget": "JenkinsAppStoreWidget"
[16:18:22]: ▸   },
[16:18:22]: ▸   "compileBitcode": false,
[16:18:22]: ▸   "method": "app-store",
[16:18:22]: ▸   "signingStyle": "manual"
[16:18:22]: ▸ }
[16:18:22]: ▸ -----------------------------------------
[16:18:22]: $ /usr/bin/xcrun /Library/Ruby/Gems/2.3.0/gems/fastlane-2.64.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/27/xff25j752dl623vsvpwlql5r00008b/T/gym_config20171109-52853-y1m2tz.plist' -archivePath /Users/Shared/Jenkins/Library/Developer/Xcode/Archives/2017-11-09/GlobeKeeper\ 2017-11-09\ 16.11.39.xcarchive -exportPath '/var/folders/27/xff25j752dl623vsvpwlql5r00008b/T/gym_output20171109-52853-19x886n' -allowProvisioningUpdates 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/27/xff25j752dl623vsvpwlql5r00008b/T/gym_config20171109-52853-y1m2tz.plist -archivePath '/Users/Shared/Jenkins/Library/Developer/Xcode/Archives/2017-11-09/GlobeKeeper 2017-11-09 16.11.39.xcarchive' -exportPath /var/folders/27/xff25j752dl623vsvpwlql5r00008b/T/gym_output20171109-52853-19x886n -allowProvisioningUpdates
2017-11-09 16:18:23.619 xcodebuild[55577:993755] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/27/xff25j752dl623vsvpwlql5r00008b/T/GlobeKeeper_2017-11-09_16-18-23.617.xcdistributionlogs'.
2017-11-09 16:18:24.697 xcodebuild[55577:993755] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-13233/DVTFoundation/DeveloperStructure/DVTPlatformFamily.m:192
Details:  Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0x72613c21" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}
Object:   <NSBundle>
Method:   +dvt_platformFamilyForBundleAtPath:error:
Thread:   <NSThread: 0x7fd2eec078d0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2017-11-09 16:18:25.961 xcodebuild[55577:993755] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-13233/DVTFoundation/DeveloperStructure/DVTPlatformFamily.m:192
Details:  Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0x72613c21" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}
Object:   <NSBundle>
Method:   +dvt_platformFamilyForBundleAtPath:error:
Thread:   <NSThread: 0x7fd2eec078d0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2017-11-09 16:18:25.966 xcodebuild[55577:993755] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-13233/DVTFoundation/DeveloperStructure/DVTPlatformFamily.m:192
Details:  Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0x72613c21" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}
Object:   <NSBundle>
Method:   +dvt_platformFamilyForBundleAtPath:error:
Thread:   <NSThread: 0x7fd2eec078d0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2017-11-09 16:18:25.969 xcodebuild[55577:993755] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-13233/DVTFoundation/DeveloperStructure/DVTPlatformFamily.m:192
Details:  Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0x72613c21" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}
Object:   <NSBundle>
Method:   +dvt_platformFamilyForBundleAtPath:error:
Thread:   <NSThread: 0x7fd2eec078d0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.64.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: 55577 Segmentation fault: 11  xcodebuild "$@"
[16:18:32]: Exit status: 139

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.64.0                  |
| export_method | app-store               |
| sdk           | iPhoneOS11.0.sdk        |
+---------------+-------------------------+

[16:18:32]: ▸     cd /Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper
[16:18:32]: ▸     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/nativbarak/Library/Android/sdk/tools:/Users/nativbarak/Library/Android/sdk/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
[16:18:32]: ▸     /usr/bin/touch -c /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/GlobeKeeper-chrfuyjxlhbhqbgzkoamwjlbthsf/Build/Intermediates.noindex/ArchiveIntermediates/GlobeKeeper/BuildProductsPath/Release-iphoneos/GlobeKeeper.app.dSYM
[16:18:32]: ▸ ** ARCHIVE SUCCEEDED **
[16:18:32]: 
[16:18:32]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[16:18:32]: 📋  For the complete and more detailed error log, check the full log at:
[16:18:32]: 📋  /Users/Shared/Jenkins/Library/Logs/gym/GlobeKeeper-GlobeKeeper.log
[16:18:32]: 
[16:18:32]: Looks like fastlane ran into a build/archive error with your project
[16:18:32]: It's hard to tell what's causing the error, so we wrote some guides on how
[16:18:32]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[16:18:32]: Before submitting an issue on GitHub, please follow the guide above and make
[16:18:32]: sure your project is set up correctly.
[16:18:32]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[16:18:32]: the full commands printed out in yellow in the above log.
[16:18:32]: Make sure to inspect the output above, as usually you'll find more error information there
[16:18:32]: 
+--------------------+-------------------------------------------------------------------------------------------------------------------+
|                                                              Lane Context                                                              |
+--------------------+-------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                                               |
| PLATFORM_NAME      |                                                                                                                   |
| LANE_NAME          | betastore                                                                                                         |
| SIGH_PROFILE_PATH  | /Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/AppStore_com.globekeeper.app.mobileprovision     |
| SIGH_PROFILE_PATHS | ["/Users/Shared/Jenkins/.jenkins/workspace/iOSBuildJob/GlobeKeeper/AppStore_com.globekeeper.app.mobileprovision"] |
| SIGH_UDID          | 8005f8bd-9af3-4400-9fda-0cfdd317643c                                                                              |
| SIGH_UUID          | 8005f8bd-9af3-4400-9fda-0cfdd317643c                                                                              |
| SIGH_NAME          | com.globekeeper.app AppStore                                                                                      |
| SIGH_PROFILE_TYPE  | app-store                                                                                                         |
+--------------------+-------------------------------------------------------------------------------------------------------------------+
[16:18:32]: Error packaging up the application

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | sigh                                | 77          |
| 💥   | gym                                 | 417         |
+------+-------------------------------------+-------------+

[16:18:32]: fastlane finished with errors

[!] Error packaging up the application

env -

[16:23:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:23:03]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "f16787cd-62f5-4639-b016-43d833fc960c"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    scheme: "GlobeKeeper",
    export_method: "ad-hoc",
    export_xcargs: "-allowProvisioningUpdates",
    export_options:{
     provisioningProfiles: {
       "com.globekeeper.app" => "JenkinsAdHoc",
       "com.globekeeper.app.ShareExtension" => "JenkinsAdHocShared",
       "com.globekeeper.app.Widget" => "JenkinsAdHocWidget"
     }
   }
)


	end


lane :betastore do
  # build your iOS app
   gym(
    scheme: "GlobeKeeper",
    export_method: "app-store",
    export_xcargs: "-allowProvisioningUpdates",   
    export_options:{
     provisioningProfiles: {
       "com.globekeeper.app" => "JenkinsAppStore",
       "com.globekeeper.app.ShareExtension" => "JenkinsAppStoreShare",
       "com.globekeeper.app.Widget" => "JenkinsAppStoreWidget"
     }
   }
)


        end

lane :inst do
   install_on_device(
      device_id: "1b1c7237658ed2cd48b1ce579c1a2b115ba12012",
      ipa: "./GlobeKeeper.ipa"
  )

  # upload to Testflight
  # pilot(skip_waiting_for_build_processing: true)
 	
	end

lane :upl do
   pilot(
     skip_waiting_for_build_processing: true,
     username: "nativ@globekeeper.com",
     distribute_external: false
    )

	end

lane :tsfl do
   testflight(skip_submission: true)

end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-11-09**

**Comment by NateZ7** [comment]
@fastlane-bot  cant see any reference for that, plus I have the correct provisioning profiles. same as ad-hoc, which works.

**Comment by joshdholtz** [comment]
@NateZ7 Have you tried creating an app store build via xcode directly? The output you pasted above shows this..

```sh
2017-11-09 16:18:25.961 xcodebuild[55577:993755] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-13233/DVTFoundation/DeveloperStructure/DVTPlatformFamily.m:192
Details: Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0
```

which makes it seem like it is a build error with your release configuration. It is hard to tell from my end if this what else could be wrong but this looks like it could be the culprit 🤔
