### ISSUE TITLE
Supply stays forever on "Preparing apk at path..."

### ISSUE THREAD

**Issue by caipivara** [fastlane/fastlane#10864]
My setup:

- fastlane `2.64.0`

```
supply(track: 'alpha',
  apk: "app/build/outputs/apk/app-release.apk",
  json_key: "fastlane/my-setup.json",
  skip_upload_metadata: true, # Dont upload this things at the moment
  skip_upload_images: true,
  skip_upload_screenshots: true)
```
After I run `fastlane deploy_produciton --verbose` logs stay forever at:

```
INFO [2017-11-09 13:54:56.58]: Preparing apk at path 'app/build/outputs/apk/app-release.apk' for upload...
```

can I do more to get more logs from fastlane?

**Comment by caipivara** [comment]
Looks like this happens when you have a proxy in between

**Comment by joshdholtz** [comment]
@caipivara So do things work for you when you remove the proxy?

**Comment by caipivara** [comment]
@joshdholtz yeah.
It will be cool some message or maybe a warning on the readme saying this.
