### ISSUE TITLE
scan - result_bundle  is it a path or a boolean?

### ISSUE THREAD

**Issue by jaleksynas** [fastlane/fastlane#10865]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The option `result_bundle` describes itself as a path:
https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb#L167-L172

The test seems to indicate that the `result_bundle` option is a boolean:
https://github.com/fastlane/fastlane/blob/master/scan/spec/test_command_generator_spec.rb#L256

And the Code agrees:
https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/test_command_generator.rb#L37
https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/test_command_generator.rb#L142

**Would a PR to fix the description or properly consume the option as a path be preferred?**

##### Complete output when running fastlane, including the stack trace and command used

```
...
scan(scheme: "UnitTests", skip_slack: !Helper.is_ci?, result_bundle: "ResultsFolder/Results")
...
```
Results in the command...

`set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme UnitTests -project ./My.xcodeproj -destination 'platform=iOS Simulator,id=FBA6543D-AF8D-44C8-B9A7-A2E0E88F800E' -derivedDataPath './derivedData' -resultBundlePath './fastlane/test_output/UnitTests.test_result' build test | tee './build/logs/scan/UnitTests-UnitTests.log' | xcpretty  --report html --output './fastlane/test_output/report.html' --report junit --output './fastlane/test_output/report.junit' --report junit --output '/var/folders/f3/3v3hhpqs3x7435tz9ggg73740000gn/T/junit_report20171109-32551-1uxhge3'`

**Comment by joshdholtz** [comment]
@Jakadam We love accepting PRs 😊  Feel free to tackle this issue yourself!

**Comment by joshdholtz** [comment]
@jaleksynas I think the test is wrong. It seems like the test isn't _really_ using that "boolean" value since I think it should clearly be a path. I think that https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb#L170 is also probably wrong and should be set to `true`

**Comment by jaleksynas** [comment]
@joshdholtz Ok, I'll make a PR that makes the option function _as a path_ and fix the tests.

**Comment by Statusgman** [comment]
I have this issue in fastlane scan 2.93.0
This parameter is still interpreted like a bool value instead of actual path

**Comment by jaleksynas** [comment]
@joshdholtz Thanks for repairing this and making it consistently used across `scan` and `gym` 🥇
