### ISSUE TITLE
"FASTLANE_SNAPSHOT" equivalent for screengrab

### ISSUE THREAD

**Issue by dustinrwh** [fastlane/fastlane#10863]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running snapshot for iOS, a user default with the key "FASTLANE_SNAPSHOT" is added to the app environment. This way I can add code to show mock data in the app while generating screenshots.

According to the docs, there is a way to add arguments which are accessible to the test, but doesn't mention anything about app source code.

What is the best way to detect Screengrab is running? Is it better to create a custom debug configuration/build?

Thanks for all the work being done on fastlane. Love it!

**Comment by joshdholtz** [comment]
@dustinrwh  I have never tried this myself but in `screengrab` I believe you add the dependency like this...

```
androidTestCompile 'tools.fastlane:screengrab:x.x.x'
```

which I think means that the class `Screengrab` is only available during a test run so I THINK you might be able to check if that class exists? I don't know if this is fully what you want because that class might ALSO be available while running normal tests so you MAY also try toggling a static boolean in your tests manually if you are doing `screengrab` stuff? Hopefully something like this works for you

**Comment by dustinrwh** [comment]
Thanks for the suggestion @joshdholtz. I'll check it out real quick.

**Comment by dustinrwh** [comment]
Just tried this out and it doesn't work. I think the reason is because screengrab code is only included the androidTest.apk, not the debug.apk.

I think I'll try adding a new build type or product flavor.

**Comment by joshdholtz** [comment]
@dustinrwh Oh yeaaaahhh, you right you right. Totes forgot about that. Please report back with any findings 😇

**Comment by dustinrwh** [comment]
I found out that only one build variant can be tested so a new build variant isn't going to work (unless you want to new build type to be the testable build)

http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Testing

Product Flavor should be fine. Onto that now :)

**Comment by joshdholtz** [comment]
Thanks for the update! 🙌

**Comment by dustinrwh** [comment]
Got it working!

Here's what I did for everyone's benefit....

Add two product flavors to the app-level build.gradle file:
```
android {
...
    flavorDimensions "mode"
    productFlavors {
        screengrab {
            dimension "mode"
        }
        regular {
            dimension "mode"
        }
    }
...
}
```

Check for the existence of that flavor (i.e screengrab) in code as follows in order to use mock data or customize data for screenshots:
```
if (BuildConfig.FLAVOR == "screengrab") {
    mainActivity.title = "screengrab rocks"
} else {
    mainActivity.title = "Normal Title"
}
```

When running screengrab, do the following to build the flavor you want as well as the test apk. Note that you use "assemble<Flavor_name>" where the flavor name is capitalized. 
```
./gradlew assembleScreengrab assembleAndroidTest
```

Run screengrab:
```
fastlane screengrab
```
screengrab will ask you to select the debug and test apps (which you can then add to your Screengrabfile to skip this step later). 

The debug apk should be somewhere like this: 
`app/build/outputs/apk/screengrab/debug/app-screengrab-debug.apk`

The test apk should be somewhere like this: 
`app/build/outputs/apk/androidTest/screengrab/debug/app-screengrab-debug-androidTest.apk`

Sit back and enjoy your new screenshots!

**Comment by joshdholtz** [comment]
@dustinrwh This is amazing! Cool if I add this to our screengrab docs? Or if you want to PR into the docs this would be cool too 😊 This is a great thing for other people to know 🙌

**Comment by dustinrwh** [comment]
Docs would be a great place for it. I'll go ahead PR into the docs. Thanks for the help 👍
