### ISSUE TITLE
The App Name you entered has already been used

### ISSUE THREAD

**Issue by subbu-nama** [fastlane/fastlane#10869]
I am getting "The App Name you entered has already been used" if I'm resubmitting an update to an existing app. If I change the name in name.txt with the reference of https://github.com/fastlane/fastlane/issues/1580, my appname is getting changed in itunesconnect. How can I run fastlane multiple times for same app?.

Your help would be highly appreciated. Thanks.

**Comment by subbu-nama** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.7.4 (Apple Git-66)            |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 7.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.1.1"

actions_path './actions'

bundle_install

lane :iosprod do
produce( 
app_name:ENV["APPNAME”])
pem(
pem_name:ENV["APNS_FILE_NAME"],
output_path:ENV["APNS_OUTPUT_PATH"],
generate_p12:true,
p12_password:ENV["PEM_P12_PASS"]
)
aipushupload(
p12:"./"+ENV["APNS_FILE_NAME"]+".p12"
)
set_info_plist_value(
path: "./platforms/ios/" + ENV["APPNAME"] + "/" + ENV["APPNAME"] + "-Info.plist",
key: "UIRequiredDeviceCapabilities",
value: [“telephony”]
)

match(
force_for_new_devices:true,
type:"appstore"
)
ENV["FASTLANE_XCODE_LIST_TIMEOUT"]="100"
recreate_schemes(project:ENV['XCODEPROJFILE'])
gym(export_method:"app-store")
deliver(
ipa:lane_context[SharedValues::IPA_OUTPUT_PATH],
force: true,
price_tier: 0,
app_rating_config_path: ‘fastlane/metadata/ratings_config.json’,
#submit_for_review: true,
#submission_information: {
# "add_id_info_uses_idfa": false,
# "content_rights_contains_third_party_content": false,
# "export_compliance_uses_encryption": false
#},
automatic_release: true
)

#hockey(
#    api_token: ENV['HOCKEYAPP_TOKEN'],
#    public_identifier: "#{lane_context[SharedValues::HOCKEY_PRODUCE_NEW_PUBLIC_IDENTFIER]}",
#    notes: ENV['notes'],
#    notes_type: "1"
#  )
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "xx.xxxxxx.DynamicData" # The bundle identifier of your app
apple_id "xxxxxx@gmail.com" # Your Apple email address

team_id "xxxxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.62.1  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-11-10**
</details>

**Comment by minuscorp** [comment]
Hi! Can you explain a bit more what are you trying to do or what do you expect to fastlane to do?
