### ISSUE TITLE
Scan shouldn't detech project if we specify test_without_build & xctestrun path

### ISSUE THREAD

**Issue by huy-le** [fastlane/fastlane#10868]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

For `scan` below, we shouldn't call `FastlaneCore::Project.detect_projects(config)` in side `https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/detect_values.rb` if we input `xctestrun` & `derived_data_path`.

```ruby
desc "Run the tests"
  lane :test do |options|
  scan(
    devices: ["iPhone 7"],
    test_without_building: true,
    xctestrun: "build/DerivedData-Test/Build/Products/UIStubTests_iphonesimulator11.0-x86_64.xctestrun"
  )
end
```

Because `xcodebuild` allow you to run test without a project. You just need to specific derived data and xctestrun file.

For example, this command run successfully

```bash
xcodebuild test-without-building -xctestrun 'build/DerivedData-Test/Build/Products/UIStubTests_iphonesimulator11.0-x86_64.xctestrun' -destination 'platform=iOS Simulator,name=iPhone 7' -only-testing:UIStubTests
```

### Benefit

Allow us to run the tests without project folder.

### Proposal

Not detect project file if we have `xctestrun` path.

**Comment by huy-le** [comment]
@fastlane-bot no need `fastlane env` for this issue.

**Comment by janpio** [comment]
Hey @huy-le, sorry this got ignored so long. Would you be up to create a PR for this?

**Comment by huy-le** [comment]
Hey @janpio, I'd like to do that and actually I've read the code. The reason I didn't do is that I'm not familiar with Ruby language and completely don't understand the deployment cycle of this project. I don't know where I should start to kick-off and build. And how can I ensure that my changes does not affect other parts in this project. Base on that reason, I temporarily include the .xcproj file to bypass the validation.

Do you have any document for contributor? I could have a look at my free time to try kick-off my knowledge about this project.

**Comment by janpio** [comment]
Sure! Best start is here: https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md and https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md. This will explain how to check out locally, set it up so fastlane uses your local copy, how to test your changes and submit it as a PR that our CI can check. If you have any questions, just @ mention me again in the issue.
