### ISSUE TITLE
Generate more idomatic screenshots.html file when using screengrab

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#10878]
I'd like the `screenshots.html` file to be consistent so that if you check it into your versioning control system you won't have that much difference with the file itself if you run screengrab in the future.

Also, there are a bunch of unnecessary whitespaces and new lines that could be optimized away to make the Html file more readable. Indentation could also be improved in some places.

Happy to contribute if this is something you want.

**Comment by vanniktech** [comment]
Nope. Does not.

**Comment by KrauseFx** [comment]
Sorry for the late reply 🎄  Yeah, this sounds like a great area to get started contributing, check out https://github.com/fastlane/fastlane/blob/master/screengrab/lib/screengrab/page.html.erb, which is where the HTML page gets generated 👍 

Let me know if you need any help getting started

**Comment by vanniktech** [comment]
Thanks for the starter points. I've not forgotten about this and will try to tackle it in the next week.

**Comment by vanniktech** [comment]
What's the easiest way to verify my changes are working as I expect them too?

**Comment by taquitos** [comment]
In a project where you use fastlane, if you aren't using bundler check this out: [Using bundler with fastlane](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile), 

After you set that up, you can then point the `fastlane` gem to the local directory holding your changes, here's what mine looks like: `gem "fastlane", path: "~/dev/fastlane"`

**Comment by vanniktech** [comment]
That's quite fascinating how easy it is to do that. Thanks for the info.

**Comment by vanniktech** [comment]
Thanks to you @taquitos and @KrauseFx I created my PR. Sorry it took a bit longer.

**Comment by taquitos** [comment]
No problem @vanniktech, thank you for taking the time to contribute!

**Comment by vanniktech** [comment]
This has been fixed by #11811

**Comment by KrauseFx** [comment]
Thanks again 👍
