### ISSUE TITLE
Record a video of the simulator during scan

### ISSUE THREAD

**Issue by asalom** [fastlane/fastlane#10875]
Hi,

Is have question and an idea for an addition to scan. Since Xcode 9 it is possible to record videos from the simulator via the command line
```
xcrun simctl io booted recordVideo {name}.{format}
```
and then save them with `CTRL+C` or
```
killall -SIGINT simctl
```

**The idea:** It would be cool to see this in scan someday. It could be pretty useful for UI tests especially when executed in CI systems.

**The question:** Is there any way with fastlane to know when the simulator has been launched?

**Comment by joshdholtz** [comment]
@asalom I don't think there has been any talk about adding this to `scan` but there is a PR that is under development for adding video recording to `snapshot` which _I think_ would solve what you are kind of looking to do - https://github.com/fastlane/fastlane/pull/10121

**Comment by asalom** [comment]
It would be great to add it to scan too. I've been playing around myself with video recording and I hit a hardware limitation on Travis CI https://github.com/travis-ci/travis-ci/issues/8765
