### ISSUE TITLE
Metadata folder with flavors

### ISSUE THREAD

**Issue by tobiasKaminsky** [fastlane/fastlane#10874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
currently supply init is generating fastlane/metadata/android/$locale
Fdroid is using the metadata scheme to directly use the descriptions in their store.
As our app will have two different flavors (e.g. stable / dev), we want to have two different descriptions.
I did not find a scheme for supporting flavors, something like
fastlane/metadata/android/$flavor/$locale/
would be sufficient?

**Comment by joshdholtz** [comment]
@tobiasKaminsky `supply` has a `metadata_path` parameter that you _should_ be able to specify different flavors of metapaths. Have you tried that? 🤔

**Comment by tobiasKaminsky** [comment]
No, I do not use fastlane, but only the metadata schema for fdroid. 
So I wanted to ask if there as a schema with flavors so that I can then adopt fdroid to it.

If I can specify via metadata_path the location, then I would propose this:
no flavors: /fastlane/metadata/android/$locale (as it is now)
flavors: /src/$flavor/fastlane/metadata/android/$locale

This way the generated folder structure is the same, but it is either in "/" (root) or within a specific flavor (src/$flavor).

**Comment by ppamorim** [comment]
Has this issue been fixed? I need this feature working too. Thanks.

**Comment by tobiasKaminsky** [comment]
In fdroid there is now src/$flavour/metadata/fastlane/android/$locale supported.

**Comment by tobiasKaminsky** [comment]
well...still not included in fastlane, but there are now workarounds.

**Comment by joshdholtz** [comment]
@tobiasKaminsky Sorry about not being able to include this in fastlane! There are a lot of our things on our priority list and we have not seen a lot of demand for `fdroid`. We would be happy to look at PR for this if you would like to make one or feel free to also make a custom plugin 😊 

Going to close this for now since you did find a workaround. Happy fastlaning 🚀

**Comment by J-Jamet** [comment]
> In fdroid there is now src/$flavour/metadata/fastlane/android/$locale supported.


@tobiasKaminsky how do you know that it works with a flavor folder, i do not see anything in the doc?

**Comment by tobiasKaminsky** [comment]
@J-Jamet I know it, because I created a merge request for this in fdroid ;-)
You are right that this is not yet documented...
