### ISSUE TITLE
How to sign android apks?

### ISSUE THREAD

**Issue by raiffeisennet** [fastlane/fastlane#10873]
Is it possible to sign the apk with fastlane?

**Comment by raiffeisennet** [comment]
i added signingConfigs for the release build type, but fastlane is always trying to upload the *-unsigned.apk

How can i setup fastlane to upload the signed .apk file for the beta lane?

**Comment by joshdholtz** [comment]
@raiffeisennet This sometimes happens to me so you UI do something like this..

```rb
gradle(task: 'assemble', build_type: 'Release')

# This gets the signed APK
# You could do a "puts" after this to make sure
apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

# Pass the signed APK into supply 
supply(
  apk: apk_path,
  package_name: package_name,
  track: "beta",
  skip_upload_metadata: true,
  skip_upload_images: true,
  skip_upload_screenshots: true
)
```

Another solution would also be to change your gradle file to not build an unsigned APK.

Happy fastlaning! 🚀
