### ISSUE TITLE
SPM action

### ISSUE THREAD

**Issue by fjcaetano** [fastlane/fastlane#10877]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hey guys, first of all, thanks for Fastlane. It's an awesome tool and it saves us developer so much time, there's really no way to thank you enough for it.

I know there's a lot of documentation saying you're not accepting any new actions, and I understand there's already a lot of them, but this one I really have to ask, because it's something that may get wider adoption with time.

## Do you think there's room for a Swift Package Manager action?

First of all, I think it'd be interesting if the Fastlane community, or at least, their representatives, could take a stand on SPM. Whether or not should we push it forward and support it. Swift 4 has just been released and there's still no iOS/tvOS/watchOS support for it yet, so I understand this may be a nuisance at this moment.

P.S. I'm sorry for the fastlane-bot warnings this issue will have because, it's not really an issue, but a proposal.

**Comment by fjcaetano** [comment]
My I be bold enough and propose a voting with 👍 or 👎 on this?

**Comment by KrauseFx** [comment]
Sorry for not coming back earlier. We're happy to review a PR for this, it seems like this would be a useful action to be built-in :)

**Comment by fjcaetano** [comment]
@KrauseFx no problem. It's not a big deal if it seems there won't be much use for it, or if you think there are already too many actions.

I'll start working on it then, if you think there's room for it. I thought of a few commands for it:

- *build*: to build the swift project.
- *test*: to run tests target.
- *clean*: to clean the project before building.
- *reset*: to wipe the cache/build folder.
- *update*: to update dependencies.

It'd be great to have some input in this. I'll get started with these commands nonetheless.

**Comment by KrauseFx** [comment]
I haven't used SPM myself, so I can't say too much about the specifics here. Maybe someone with more experience wants to chime in?

**Comment by orta** [comment]
Those are basically all the commands I use in SPM when working on Danger Swift
