### ISSUE TITLE
Using own created cert to create provisioning profile 

### ISSUE THREAD

**Issue by fxfactorial** [fastlane/fastlane#10889]
I made my own cert with Apple by making my own `.key` file, `csr` and apple gave me the `.cer`. Now I want to make a provisioning profile but running `sigh` with

```
fastlane sigh --skip_install -u some_email@gmail.com -b SOME_TEAM_ID -a com.hyegar.sd-mobile --force --output_path /some/where -q thing.mobileprovision
```

But I get
```
[!] Could not find a matching code signing identity for type 'AppStore'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide.If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert
```

And I think this is because the `.cer` file was never installed into keychain. 

Is there a way to get sigh to produce the provisioning profile given that the `.cer` was made manually? 

I looked through `fastlane action sigh` for guidance but didn't see a relevant argument.

**Comment by taquitos** [comment]
Unfortunately that's not supported. Is there any reason why you can't regenerate the cert using _sigh_? I just use _match_ for all the things and don't worry anymore 😄
