### ISSUE TITLE
Fastlane init tries to add a cocoa pod as an app to iTunes Connect #8923

### ISSUE THREAD

**Issue by bigbangvn** [fastlane/fastlane#10881]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

fastlane init
[17:04:57]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:04:59]: Detected iOS/Mac project in current directory...
[17:04:59]: This setup will help you get up and running in no time.
[17:04:59]: fastlane will check what tools you're already using and set up
[17:04:59]: the tool automatically for you. Have fun! 
[17:04:59]: $ xcodebuild -list -workspace ./MyProject.xcworkspace
[17:05:00]: $ xcodebuild -showBuildSettings -workspace ./MyProject.xcworkspace -scheme Pods-MyTarget
[17:05:02]: Your Apple ID (e.g. fastlane@krausefx.com):bang@gmail.com	
[17:25:10]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[17:25:10]: Starting login with user 'bang@gmail.com'

+----------------+--------------------------------------+
|                    Detected Values                    |
+----------------+--------------------------------------+
| Apple ID       | bang@gmail.com                 |
| App Name       | Pods_MyProject                           |
| App Identifier | org.cocoapods.Pods-MyProject             |
| Workspace      | /Volumes/Bang_Macbook/MyProject/MyProject.xcworkspace        |
+----------------+--------------------------------------+

[17:25:19]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[17:25:19]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
[17:25:19]: Please confirm the above values (y/n)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-11-12**
</details>

**Comment by bigbangvn** [comment]
I found the different between xcodebuild version:

xcodebuild -list -workspace ./MyProject.xcworkspace
Information about workspace "MyProject":
    Schemes:
        Pods-MyProject
        Realm
        RealmSwift
        MyProject

It seems that fastlane always chose the first scheme, so sometime it's wrong scheme as in this example, It should be MyProject not Pods-MyProject.
But I don't know where to fix the script of fastlane :)

**Comment by getaaron** [comment]
@bigbangvn If you select `n` you can manually select the scheme

If you want to improve the logic that selects the default scheme, it's here:

https://github.com/fastlane/fastlane/blob/98bbc59648f209838e28023e029ee966d592d020/fastlane/lib/fastlane/setup/setup_ios.rb#L268-L278

`manually` is `true` if you select `n` at the *Please confirm the above values* prompt.
