### ISSUE TITLE
Error while creating iTunesConnect app with Finnish lang as primary

### ISSUE THREAD

**Issue by nepome** [fastlane/fastlane#10880]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Unexpected error while creating iTunes Connect app with Finnish as primary language.
Problem exists only with Finnish language, all other works fine (fastlane is waiting for app to be available for creationg after registering at Developer Center and sucessfully create iTunes Connect app).

`{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unexpected Error"]}, "statusCode"=>"ERROR"}`

### Captured Output

Command Used: `sign appstore:true`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/***/fastlane/Appfile'
- apple_id: '***'
- app_identifier: '***'
-------
+-----------------------------------+--------------------------+
|                  Summary for produce 2.64.0                  |
+-----------------------------------+--------------------------+
| username                          | *** |
| app_identifier                    | ***             |
| app_name                          | ***             |
| skip_itc                          | false                    |
| language                          | Finnish                  |
| app_version                       | 1.0                      |
| sku                               | ***             |
| enable_services.push_notification | off                      |
| platform                          | ios                      |
| skip_devcenter                    | false                    |
+-----------------------------------+--------------------------+

Looking for iTunes Connect Team with ID ***

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | Switch to appid lane | 0           |
| 💥   | produce              | 28          |
| 3    | Switch to appid lane | 0           |
| 💥   | produce              | 20          |
| 5    | slack                | 2           |
+------+----------------------+-------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: `{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unexpected Error"]}, "statusCode"=>"ERROR"}`

URL: https://api.github.com/search/issues?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22info%22=%3Enil,%20%22error%22=%3E[%22Unexpected%20Error%22]%7D,%20%22statusCode%22=%3E%22ERROR%22%7D+repo:fastlane/fastlane
➡️  Unable to upload to itunes connect using deliver
    https://github.com/fastlane/fastlane/issues/9942 [closed] 33 💬
    5 weeks ago

➡️  spaceship - Get only 'live' apps from itc
    https://github.com/fastlane/fastlane/issues/10310 [closed] 14 💬
    15 Sep 2017

➡️  Deliver fails with "Unexpected Error" after uploading package to iTunes Connect
    https://github.com/fastlane/fastlane/issues/6455 [closed] 51 💬
    23 Jan 2017

and 11 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22info%22=%3Enil,%20%22error%22=%3E[%22Unexpected%20Error%22]%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>Top lines of stacktrace errors</summary>

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:599:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unexpected Error"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/tunes/tunes_client.rb:303:in `create_application!'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/tunes/application.rb:82:in `create!'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/produce/lib/produce/itunes_connect.rb:24:in `create_new_app'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/produce/lib/produce/itunes_connect.rb:12:in `run'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/produce/lib/produce/manager.rb:8:in `start_producing'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/fastlane/lib/fastlane/actions/produce.rb:17:in `block in run'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/fastlane/lib/fastlane/actions/produce.rb:15:in `chdir'
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.0/fastlane/lib/fastlane/actions/produce.rb:15:in `run'
```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.6 (Apple Git-96)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
ENV['PRIMARY_LANG'] = 'Finnish'
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

lane :appid do |options|
	produce(
	    username: ENV['username'],
	    app_identifier: ENV['bundle_identifier'],
	    app_name: ENV['project_name'],
  		skip_itc: options[:itc] ? false : true,
  		language: ENV['PRIMARY_LANG'],
  		app_version: "1.0",
  		sku: ENV['sku'],
  		enable_services: {
	           push_notification: "off"
	        }  
	)
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "***"
app_identifier "***"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.3       |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| psych                     | 2.0.0        |
</details>

*generated on:* **2017-11-11**
</details>

**Comment by taquitos** [comment]
I just tried repro'ing with a new app using your Fastfile and it worked for me.

<img width="519" alt="screen shot 2017-11-14 at 10 44 10 am" src="https://user-images.githubusercontent.com/1304821/32798228-eacc04a0-c928-11e7-8bc4-ef1d0ce5b353.png">


Could you add `fastlane [lane] --verbose` and try again, then post the complete output (not just the error)?

**Comment by nepome** [comment]
@taquitos thank you for your response, but the deal is only regarding iTC app creating. You're doing DevCenter creating with iTC skipped, but the problem I faced is only with creating app at iTunesConnect after successful creation in DevCenter.

Here the log is (not the first run, so already exists in DevCenter).

<details><summary>fastlane appid --verbose</summary>

```

[21:57:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-11-15 21:57:13.88]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/***/fastlane/Appfile'
- apple_id: '***@gmail.com'
- app_identifier: 'why.not.finnish.hm'
-------
INFO [2017-11-15 21:57:13.98]: Driving the lane 'appid' 🚀
INFO [2017-11-15 21:57:14.00]: ---------------------
INFO [2017-11-15 21:57:14.00]: --- Step: produce ---
INFO [2017-11-15 21:57:14.00]: ---------------------

+-----------------------------------+--------------------------+
|                  Summary for produce 2.64.1                  |
+-----------------------------------+--------------------------+
| username                          | ***@gmail.com |
| app_identifier                    | why.not.finnish.hm       |
| app_name                          | FinnishWorthToBeOk   |
| skip_itc                          | **false**                    |
| language                          | Finnish                  |
| app_version                       | 1.0                      |
| sku                               | vecelilozibj             |
| enable_services.push_notification | off                      |
| platform                          | ios                      |
| skip_devcenter                    | false                    |
+-----------------------------------+--------------------------+

INFO [2017-11-15 21:57:24.37]: [DevCenter] App 'FinnishWorthToBeOk' already exists, nothing to do on the Dev Center
Looking for iTunes Connect Team with ID ***
INFO [2017-11-15 21:57:35.52]: Creating new app 'FinnishWorthToBeOk' on iTunes Connect
INFO [2017-11-15 21:57:41.13]: -------------------
INFO [2017-11-15 21:57:41.13]: --- Step: slack ---
INFO [2017-11-15 21:57:41.13]: -------------------
DEBUG [2017-11-15 21:57:41.15]: Taking value for 'slack_url' from environment variable 'SLACK_URL'
^CWARN [2017-11-15 21:57:42.16]: Lane Context:
INFO [2017-11-15 21:57:42.16]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"appid"}

```

</details>


I paid attention to `PLATFORM_NAME=>nil` which is strange for me. Can this cause the problem? I mean I don't have to specify the platform manually but I face the same problem even when I add `platform: "ios"` to `produce`

<details><summary>Traceback</summary>

```

/Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/client.rb:599:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/tunes_client.rb:303:in `create_application!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/application.rb:82:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/produce/lib/produce/itunes_connect.rb:24:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/produce/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/produce/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/produce.rb:17:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/produce.rb:15:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/produce.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:50:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.64.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

</details>

**Comment by dbyzero** [comment]
I got the same issue here with the last fastlane version. I log req et resp for app creation (I hide sensible informations with `*******` : 

Request : 
`{"sectionErrorKeys"=>[],
 "sectionInfoKeys"=>[],
 "sectionWarningKeys"=>[],
 "value"=>nil,
 "companyName"=>
  {"value"=>"*******",
   "isEditable"=>false,
   "isRequired"=>false,
   "errorKeys"=>nil},
 "versionString"=>nil,
 "appRegInfo"=>nil,
 "bundleIds"=>
  {"*******"=>
    "********",
   "*"=>"Xcode iOS Wildcard App ID - *"},
 "enabledPlatformsForCreation"=>{:value=>["ios"]},
 "name"=>{:value=>"Matkaopas"},
 "primaryLanguage"=>{:value=>"Finnish"},
 "primaryLocaleCode"=>{:value=>"fin"},
 "bundleId"=>{:value=>"*******"},
 "bundleIdSuffix"=>{:value=>""},
 "vendorId"=>{:value=>"*******"},
 "initialPlatform"=>"ios",
 "adamId"=>nil,
 "iTunesConnectUsers"=>
  {"grantedAllUsers"=>true, "grantedUsers"=>[], "availableUsers"=>[]}}
"{\"sectionErrorKeys\":[],\"sectionInfoKeys\":[],\"sectionWarningKeys\":[],\"value\":null,\"companyName\":{\"value\":\"*******\",\"isEditable\":false,\"isRequired\":false,\"errorKeys\":null},\"versionString\":null,\"appRegInfo\":null,\"bundleIds\":{\"*******\":\"*******\",\"*\":\"Xcode iOS Wildcard App ID - *\"},\"enabledPlatformsForCreation\":{\"value\":[\"ios\"]},\"name\":{\"value\":\"*******\"},\"primaryLanguage\":{\"value\":\"Finnish\"},\"primaryLocaleCode\":{\"value\":\"fin\"},\"bundleId\":{\"value\":\"*******\"},\"bundleIdSuffix\":{\"value\":\"\"},\"vendorId\":{\"value\":\"*******\"},\"initialPlatform\":\"ios\",\"adamId\":null,\"iTunesConnectUsers\":{\"grantedAllUsers\":true,\"grantedUsers\":[],\"availableUsers\":[]}}`

Response : 
`#<Faraday::Response:0x007fd17d692a48
 @env=
  #<struct Faraday::Env
   method=:post,
   body=
    {"data"=>nil,
     "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil},
     "statusCode"=>"ERROR"},
   url=
    #<URI::HTTPS https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/create/v2>,
   request=
    #<struct Faraday::RequestOptions
     params_encoder=nil,
     proxy=nil,
     bind=nil,
     timeout=300,
     open_timeout=300,
     boundary=nil,
     oauth=nil>,
   request_headers=
    {"User-Agent"=>"Spaceship 2.83.0",
     "Content-Type"=>"application/json",
     "Cookie"=>
      "acn01=k+mUP1Ytogs1raL6REF3qJMCFxjey+vslibCEC95zloADC2sMdmp8Q==; dqsid=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJrR2g3c1ZPM0tNS2lSdzhwZTRqRjVRIn0.nANpKWMvSHFh8K5b_HwP-JNmP8iGL_FlzCX71xBTRFI; dslang=US-EN; itcdq=1; itctx=eyJleCI6IjIwMTgtMi0yNyAyMjozNToyNyIsImNwIjoxMDI5NDgwNCwiZHMiOjQzMjQ3MTc5NX0|9bhurvijrnhn3h90vhmnubq3nb|DSsb8XlcD29Fy1EAezU6ea1n1Ko; myacinfo=DAWTKNV2e9e4375bca10ce167c5a4e375fdcaca9679a7a0c76dc1b9b03e12a149458347c9ff40c1b8bcba3e01a485376f4005facf4c9d2fcb5f01217b1638bc7582afacff64a6ee522dedf8bdbe688d32409ed202f83ca6d4209ed26af747d413be6dcc3a00f7be371f3087bedf5d68f99a81ceae40172fd27d9798f3d6ba29d7a006ed20238ea1cccdf4e64389e68c05c39861183e233f7f89d4a90f059fe360afbd9d9c767032966278e8fbd526c1a6145b5ee1187d4a9f729b6dfbb1ebcec1b76bee0a96239789a2a2dcaf0bfb83cb82c19bf6cf1adb2e7cb9a6d55e98af293e6f7daf522ee6abf49340b857982ea60c20348976f2a9abf9d01305103cafade84840e64626630363862663461356337633339383932626365333733343132343333386235353131646162MVRYV2; site=USA; woinst=5605; wosid=IWoFwAHjkHforzaKsze76g"},
   ssl=
    #<struct Faraday::SSLOptions
     verify=true,
     ca_file=nil,
     ca_path=nil,
     verify_mode=nil,
     cert_store=nil,
     client_cert=nil,
     client_key=nil,
     certificate=nil,
     private_key=nil,
     verify_depth=nil,
     version=nil>,
   parallel_manager=nil,
   params=nil,
   response=#<Faraday::Response:0x007fd17d692a48 ...>,
   response_headers=
    {"server"=>"daiquiri/2.0.0",
     "content-type"=>"application/json; charset=utf-8;",
     "content-length"=>"105",
     "x-apple-jingle-correlation-key"=>"NWC5MLZTANFZCVM2PZJ2CY4P",
     "x-apple-application-site"=>"MR22",
     "apple-originating-system"=>"MZLabel",
     "strict-transport-security"=>"max-age=31536000; includeSubDomains",
     "x-frame-options"=>"SAMEORIGIN",
     "apple-tk"=>"false",
     "apple-seq"=>"0.0",
     "apple-timing-app"=>"123 ms",
     "cache-control"=>
      "private, no-cache, must-revalidate, max-age=0, no-store",
     "expires"=>"Thu, 01-Jan-1970 00:00:00 GMT",
     "x-apple-application-instance"=>"5605",
     "pragma"=>"no-cache",
     "x-webobjects-loadaverage"=>"119",
     "x-apple-request-uuid"=>"6d85d62f-3303-4b91-559a-7e53a1638f",
     "x-daiquiri-instance"=>
      "daiquiri-internal:10100601:mr22p00it-ztbu06131901:9822:18C27, daiquiri-external:10100001:mr22p00it-ztbu06054001:9122:18C27",
     "date"=>"Tue, 27 Feb 2018 15:15:51 GMT",
     "connection"=>"close",
     "set-cookie"=>
      "dqsid=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJrR2g3c1ZPM0tNS2lSdzhwZTRqRjVRIn0.nANpKWMvSHFh8K5b_HwP-JNmP8iGL_FlzCX71xBTRFI; Max-Age=1800; Expires=Tue, 27 Feb 2018 15:45:51 GMT; Path=/; Secure; HTTPOnly"},
   status=500,
   reason_phrase="Internal Server Error">,
 @on_complete_callbacks=[]>`

Changing bundleid or app name get same issue.

**But set language to English fix issues...**

**Comment by max-ott** [comment]
@dbyzero Having the same problem, what do you mean with:
> But set language to English fix the issue...

**Comment by dbyzero** [comment]
I try to build it with primary language set to "Finnish" and I have the error above.

I did a test by setting primary language to "English" and the error vanished...

So there is an

**Comment by dbyzero** [comment]
Or it's may be not related to language, I change app name and bundle id for my English test.

I think the app name is in a strange state in iTunes Connect. Indeed we cannot create the app but it not appear in my customer iTunes Account. I'll ask my customer to change his app name..
