### ISSUE TITLE
Can fast lane provide the key that was used to create the .cer file?

### ISSUE THREAD

**Issue by fxfactorial** [fastlane/fastlane#10888]
I am using `fastlane cert` and it dumps a `.cer` file into a directory that I ask, but that directory doesn't contain the corresponding `.key` file. Is there a way to have `fastlane cert` also dump the `.key` file it used?

**Comment by taquitos** [comment]
I think `cert` provides the following files:
```
<id>.cer                
<id>.certSigningRequest 
<id>.p12                
```

how does the `.p12` differ from the `.key` file you mention? Maybe that's the same thing?

**Comment by fxfactorial** [comment]
hmm, for me, `cert` only provided the .cer file.
