### ISSUE TITLE
Multiplatform best practice?

### ISSUE THREAD

**Issue by BasThomas** [fastlane/fastlane#10891]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am interested in setting up Fastlane for both an iOS & Android app, and after not really finding that much in the docs, I was wondering if some people with experience here have some best practices to share.

I was thinking of creating a separate `fastlane` repository that would house the main Fastfile, including both lanes for Android and iOS. This comes with the issue that actions would be performed in that repo instead of the app repo (eg. [`ensure_git_status_clean`](https://docs.fastlane.tools/actions/ensure_git_status_clean/#ensure_git_status_clean)).

In the examples there is [Shop.com's Fastfile](https://github.com/fastlane/examples/blob/master/Shop.com/Fastfile) where they same to use [`chdir`](https://github.com/fastlane/examples/blob/master/Shop.com/Fastfile#L106) to execute commands in the correct directory. Would that be the way to go?

Let me know if there are better ways, improvements and/or if there is interest in improving this setup, just like at some point the [`fastlane init`](https://github.com/fastlane/fastlane/issues/10280) might be decoupled from the platforms.

Thanks 👍

**Comment by BasThomas** [comment]
Is there anyone with an opinion / feedback / experience regarding a multiplatform / agnostic setup with Fastlane? :)

**Comment by janpio** [comment]
I have experience using fastlane with Cordova, which produces iOS and Android apps from the same base code. The native projects live in `platforms/ios` and `platforms/android`, so I just supply these paths (or the files in them, `.xcodeproj` or similar) to the actions that need to work on the native projects. Fastlane config lives in `fastlane` as usual.

You have the added "problem" that your native projects are probably not in the same repo, so you have to find a way to change that. 
One way could be to add an gitignored `platforms` folder and have checkouts of your two projects in there. 
I am pretty sure there are other ways that form a better "connection" between the repos.
