### ISSUE TITLE
Questions: Fastlane file management

### ISSUE THREAD

**Issue by akac** [fastlane/fastlane#10905]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This is more of a question than an issue. I'm learning fast lane, so I've been Googling, StackOverflowing, and searching through this issues list. I have a few things I'm trying to find better ways to do in fast lane:

1. How do I get a temp folder? I need to do some work in a tmp folder that I don't want to clutter up my repo folder with. I probably can do a sh("") and do some command there to get a temp folder, but  maybe there is a better way? Just asking.

2. One of our lanes needs to check for a folder to exist (build folder with built-final framework) before it can continue for deployment. What is the best way to check for a folder existence?

**Comment by akac** [comment]
Well…not sure if fastlane env is really required here, but…okay.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.6                                      |
| Ruby                        | 2.4.2                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.11.0 (Apple Git-81)            |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:
removed due to private info

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.6        |
</details>


*generated on:* **2017-11-15**
</details>

**Comment by taquitos** [comment]
_fastlane_ is built in Ruby, and your Fastfile is just a Ruby script, so you have the full power of Ruby there 🎉 

So, depending on what you're trying to accomplish, if you want to create a temp folder, I think you want to use: http://ruby-doc.org/stdlib-2.0.0/libdoc/tmpdir/rdoc/Dir.html#method-c-tmpdir

Same with checking for a folder existence, you can use standard ruby for that: `File.directory?(directory)`

**Comment by akac** [comment]
Ah - I had thought that maybe it was Ruby…but I honestly wasn't sure. That does simplify a lot. Perfect. I'll use ruby for that!
