### ISSUE TITLE
Update fastlane problem

### ISSUE THREAD

**Issue by kszuba** [fastlane/fastlane#10906]
### New Issue Checklist

- [X] !!! Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I get this message about update fastlane, but I have already the newest version of fastlane. I tried to reinstall, uninstall and install from different sources:
https://docs.fastlane.tools/getting-started/ios/setup/#choose-your-installation-method
and nothing solves the problem.

I'm using RBENV (rbenv 1.1.0) and I'm using Ruby 2.4.0, but I didn't have that problem before.

```
[12:48:56]: Your './XXX/Snapshot/SnapshotHelper.swift' is outdated, please run `fastlane snapshot update`
[12:48:56]: to update your Helper file

[!] Please update your Snapshot Helper file using `fastlane snapshot update`

#######################################################################
# fastlane 2.64.1 is available. You are on 2.63.0.
# You should use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

2.64.1 Improved build processing waiting
* Wait for uploaded ipa to be processed instead of any build (#10766) via Alvar Hansen
* Add -D system properties to gradle (#10883) via Santi Aguilera
* [Spaceship] Support all review screenshot resolutions - iOS In App Purchases (#10716) via Alain Caltieri
* upgraded xcodeproj version to handle variable substitution on bundle id (#10853) via Alessandro Calzavara
* Snapshot - loosen device name checking from start_with? to include? (#10840) via Josh Holtz
* Update frameit spelling (#10814) via Felix Krause
* Fix broken links (#10816) via Iulian Onofrei
* prevent nil crasher in associated_groups (#10823) via jcarroll-mediafly
* Nil check to avoid crash when language is not activated (#10821) via Javier Agüera Cazorla
* center-aspect-fill background image (instead of previous resize ignoring aspect ratio distorting textured images) (#10815) via Ferran Poveda

2.64.0 iPhone X support and more
* Support App Preview for iPhone X (#10799) via Fumiya Nakamura
* Add auto_release_date option to deliver (#10768) via Joshua Liebowitz
* Support for iPhone X in frameit (#10533) via Alfredo Delli Bovi
* Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta
* Commit version bump enhancements (#9483) via Jimmy Dee
* [Deliver] Fix uses idfa limits tracking (#10715) via Jorge
* Allow snapshots on older iOS versions when no specified/latest found (see #10211) (#10755) via Ely Alvarado
* In two-stage Hockey action, do not set the status to 2 (downloadable) until after the app is uploaded (#10706) via Steve Rubin
* Fix colon styling in SnapshotHelper (#10736) via Sampsa Kuronen
* Fixes image reference in pilot's README. (#10804) via Péter Krassay
* Fixed instruction for update plugin (#10809) via Rishabh Tayal
* Fix mismatched <th> tags in docs_generator (#10797) via David Vanoni
* Allow in app purchases check to be disabled via deliver (#10758) via Iulian Onofrei
* Remove redundant let declaration for a discardable result (#10762) via Sampsa Kuronen
* Update AppfileTemplate (#10759) via Aaron Brager
* Added is_string: false to active_days_limit config entry (#10763) via vspac
* issue template fix (#10673) via Rishabh Tayal

Please update using `fastlane update_fastlane`
```

I'm checked version and:
```
XXX$ fastlane --version
fastlane installation at path:
/Users/XXX/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.64.1/bin/fastlane
-----------------------------
fastlane 2.64.1

```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.1                           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.6        |
</details>

*generated on:* **2017-11-15**
</details>

**Comment by taquitos** [comment]
Do you have the Fabric mac app installed too? If you have: `/usr/local/lib/fastlane_lib` that might be why it thinks you have a different version. If you have `/usr/local/lib/` in your `$PATH` I wonder if it might detect it.

**Comment by getaaron** [comment]
Does `fastlane --version` show different results than `bundle exec fastlane --version`?

**Comment by kszuba** [comment]
@taquitos 
I don't have `fastlane_lib` in `/usr/local/lib/` path.
```
X:~ X$ echo $PATH
/Users/X/.rbenv/shims:/Users/X/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
```

@getaaron :
```
X:~ X$ fastlane --version
fastlane installation at path:
/Users/X/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.64.1/bin/fastlane
-----------------------------
fastlane 2.64.1
```

```
X:~ X$ bundle exec fastlane --version
Could not locate Gemfile or .bundle/ directory
```
