### ISSUE TITLE
Locating signing assets failed - XCode 9.1 - no automatically signing 

### ISSUE THREAD

**Issue by kuzdu** [fastlane/fastlane#10909]
### New Issue Checklist

- [✅ ] Updated fastlane to the latest version
- [✅ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since macOS High Sierra and XCode 9.1 (9B55) I got the following error: 

`xcodebuild[96613:1891372] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7ff18b039eb0>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
"Error Domain=IDEProfileQualificationErrorDomain Code=8 \"Provisioning profile \"com...IOS AppStore\" doesn't match the entitlements file's value for the application-identifier entitlement.\" UserInfo={IDEProfileQualificationError_Profile=<DTDKProvisioningProfile 0x7ff18b305200: UUID: 6c74d5cc-6b04-45f3-8bf0-8e0a8d272372, name: com....AppStore, team: Team (XXX), platform: iOS>, NSLocalizedDescription=Provisioning profile \"com...AppStore\" doesn't match the entitlements file's value for the application-identifier entitlement.}"
)}`

Now I googled around and found already similar issues like [https://github.com/fastlane/fastlane/issues/10251](https://github.com/fastlane/fastlane/issues/10251).

But no solution work for me. 

When I archive manually with XCode everything works fine. 
I'm confused about this output: 
`{
  "provisioningProfiles": {
   "com....IOS": "com...IOS AppStore"
    },
    "method": "app-store",
    "signingStyle": "manual"
   }`
I'm confused because in XCode my `signingStyle` is set to `automatically`. How can I manipulate that? 

I tried `enable_automatic_code_signing(path: "myProj.xcodeproj")` but that doesn't change anything.

My definition of awesome would be that XCode/Fastlane do the procedure automatically. Since XCode 9 there is a dialog: "App needs to be re-signed for App Store distribution. Choose [...]" 
[ ] Automatically manage signing 
OR
[ ] Manually manage signing

How can I tell fastlane that fastlane should use automatically manage singing? 

Thanks for help

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.4.0"

default_platform :ios

platform :ios do
  before_all do
    #team_name ENV['FASTLANE_ITC_TEAM_NAME'] #not ITC PROVIDER
    #team_id ENV['FASTLANE_ITC_TEAM_ID'] #not ITC PROVIDER
  end

  desc "Runs all the tests"
  lane :test do

  end


  desc "Submit a new Beta Build to Apple TestFlight"
  lane :uploadipa do
    pilot(itc_provider: ENV['MEMBER_DEVELOPMENT_TEAM'])
  end

  desc "This will also make sure the profile is up to date"
  lane :beta do
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do

    cert
    sigh(force:true)
    gym(clean: true, scheme: "myScheme", workspace: "myScheme.xcworkspace",export_method: "app-store", export_xcargs: "-allowProvisioningUpdates")

  end

  # You can define as many lanes as you want

  after_all do |lane|


  end



  error do |lane, exception|

  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.myApp"
apple_id "myAppleId"
team_id 'myTeamId'

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-11-15**
</details>

**Comment by taquitos** [comment]
Hey @kuzdu, I think this should be addressed in the code signing guide linked above :+1:, let us know if it doesn’t make sense after you check it out!

**Comment by kuzdu** [comment]
It wasn't a code signing.

It's confusing. For fastlane n `Targets` -> `Build Settings` -> `Product Bundle Identifier` the `Prodcut Bundle Identifier` must be the same like the `Targets` ->  `General` -> `Bundle Identifier`

Manual archiving and uploading works like expected.  [This post helped me](https://stackoverflow.com/questions/39631530/upgrade-testing-for-ios-application-identifier-entitlement-does-not-match)

So I'm now sensitized  for this fact. It's solved for me. But maybe fastlane should check this?

**Comment by taquitos** [comment]
Oh, nice find. That's a good point, maybe it is something fastlane could do better.
