### ISSUE TITLE
change plist: add/remove specific url types (CFBundleURLTypes)

### ISSUE THREAD

**Issue by Mactub07** [fastlane/fastlane#10901]
hi, want to answer : is there a way to change <CFBundleURLTypes array> inside plist, need to dinamically change array.item with dev/prod data

think of a situation 
I should replace "URL_EXAMPLE1" on "URL_EXAMPLE2"
<"dict">
	<"key">CFBundleTypeRole<"/key">
	<"string">Editor<"/string">
	<"key">CFBundleURLName<"/key">
	<"string"><"/string">
	<"key">CFBundleURLSchemes<"/key">
	<"array">
		<"string">URL_EXAMPLE1<"/string">
	<"/array">
<"/dict">

**Comment by Mactub07** [comment]
for time being I found solution to change url types with using ruby script directly 
so : what we need 
- find some string inside urlTypes to trigger line which we need to replace directly inside of Plist (<string-trigger>)
- then override value in Plist (<newValue>)
- setup plist_location_path which define location inside project your plist.file which you want to change

script may be like that 
        file_data = File.read(plist_location_path)
        file_data.gsub!(/<string-trigger>\.[^<]+/, <newValue>)

        File.open(plist_location, 'w+') {|f| f.puts file_data }

**Comment by taquitos** [comment]
I wonder if `set_info_plist_value` action could help here too: https://docs.fastlane.tools/actions/set_info_plist_value/#set_info_plist_value

**Comment by Mactub07** [comment]
Yes, I use this action when we have simple key/value, but how can we make change array of urltypes, which not specified by key/subkey

**Comment by taquitos** [comment]
Ahh, good question, yeah, I think you can read the plist into a hash, edit that, and then write it back out, similarly to how we do it in that action: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/set_info_plist_value.rb#L12

**Comment by Mactub07** [comment]
Do you mean this one 
 path = File.expand_path(params[:path])
          plist = Plist.parse_xml(path) ?

So, we have our Plist and we can modify one, but in url types we can make mistake while edit specific url-type (I have a few ones) , because actually we don't know how many urlTypes we will have

**Comment by taquitos** [comment]
Yeah, that's the one. With that parsing code, you should be able to iterate through all the elements and add/remove as you see fit. 
Another option:
Create two Info.Plist files and switch between which one you want to use by renaming them:
`Prod.plist` `Dev.plist` and then `if dev then cp "Dev.plist" Info.plist` sort of thing there.

**Comment by Mactub07** [comment]
Create two plists is good solution, but I have 2 targets (in future there will be more), and support 4 plists , then 6, etc will be hard, but anyway will keep in mind your approach;)
