### ISSUE TITLE
[Deliver] Release to beta testers

### ISSUE THREAD

**Issue by Lascorbe** [fastlane/fastlane#10904]
Hi there!

First, thanks for Fastlane, it's amazing and the huge amount of work you all put here it's outstanding. THANK YOU! ❤️ 

Now, I was looking to a way of sending my IPAs™️ to the App Store, submitting them to the review process AND sending them to the beta testers (internal and externals). And I've hit with:
- It's hard to know which one to use (I mean: Pilot, Deliver or TestFlight?), because looks like Pilot it's a "mix" of Deliver and TestFlight, but missing some features. After some search, I suppose the ones we all must use are Deliver and TestFlight (right?). If that's the case, I can make a PR trying to specify that on the docs :)
- Then, let's say I want to send the IPA to the App Store, submit it to the review process (with some custom `submission_information` parameters), and also send the same version to the beta testers. Is there some way of doing this, or do I have to upload the binary twice (first with TestFlight, then with Deliver)?

Thanks!
🍻

**Comment by taquitos** [comment]
> Pilot, Deliver or TestFlight
_testflight_ is just an alias for _pilot_ 😃 
I think you can do this:
first, you can use `testflight` to upload and then distribute. Then you can use `deliver(submit_for_review: true, ipa: nil)` to submit to review. Specifically setting`ipa: nil` because I see in the docs, that deliver can submit without uploading: (https://docs.fastlane.tools/actions/deliver/#ipa) if you don't pass in an ipa (I think the default is to find an ipa and upload that, so you have to set it to `nil`)

**Comment by Lascorbe** [comment]
Ah! Good to know, I'll try that, thanks @taquitos!

**Comment by alexito4** [comment]
Hi, I'm doing also this and it works pretty well.
But you may want to run deliver immediately after pilot to create the new version in iTunes Connect. Otherwise the build is there but there is no version created.

This is what I do on my release lane:
```
        pilot( # testflight
            groups: ["QA"]
        )
        deliver(
            skip_app_version_update: false, # Create the new version  
            # Skip   
            force: true,       
            skip_screenshots: true,
            skip_metadata: true,
            skip_binary_upload: true            
        )
```

**Comment by Lascorbe** [comment]
@alexito4 Thanks! I suppose using `skip_binary_upload` instead of `ipa: nil` is the same?

**Comment by alexito4** [comment]
@Lascorbe I haven't taken a look at the implementation but I can confirm that it doesn't upload the ipa 2 times. 
And from the [docs](https://docs.fastlane.tools/actions/deliver/):

> skip_binary_upload | Skip uploading an ipa or pkg to iTunes Connect

Should be fine 💯
