### ISSUE TITLE
Spaceship API Suggestion

### ISSUE THREAD

**Issue by jarnaiz** [fastlane/fastlane#10916]
This is not a issue, is a question:

Im using Spaceship to build an API rest. Works great but the problem is with the login API: ```Spaceship.login(username, password)``` when two factors authentication is enabled.

The problem is the code call the method ```ask``` https://github.com/fastlane/fastlane/blob/c9152e6bf2407739a4db3ceaf61f88ec46a1d778/spaceship/lib/spaceship/two_step_client.rb#L63 and I dont have any callback or something to handle this behaviour in a programatically way. 

```ruby 
Spaceship.on_two_steps_authentication{ return 123131 }
Spaceship.login(user, pass)
```

So I can do something like that:

GET /api/login must return a token
POST /api/login/token?securityCode=124131

I think the spaceship api have the intention to be an API: a DSL to works with Apple or I am wrong?

Thanks!

**Comment by taquitos** [comment]
If you're looking to use spaceship with multiple accounts, you're going to run into trouble really quickly. The session management code isn't really built to handle multiple logins and multiple sessions.
If you only use 1 single account, and that account has 2FA, you can use the tips here:
https://github.com/fastlane/fastlane/tree/master/spaceship#support-for-ci-machines

People use spaceship on CI all the time with 2FA, you just have to save a session and reload it 👍
