### ISSUE TITLE
Code Signing problem

### ISSUE THREAD

**Issue by royberris** [fastlane/fastlane#10919]
### New Issue Checklist

- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [X] Updated fastlane to the latest version
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am getting a signing error and I don't know what to do.. After hours of searching, reinstalling certificates and everything. It still won't work. This error is also not listed on: https://docs.fastlane.tools/codesigning/common-issues/
Does anyone know a solution?

##### Complete output when running fastlane, including the stack trace and command used

The following build commands failed:
Check dependencies
(1 failure)
[15:58:30]: Exit status: 65
[15:58:30]: 
[15:58:30]: Maybe the error shown is caused by using the wrong version of Xcode
[15:58:30]: Found multiple versions of Xcode in '/Applications/'
[15:58:30]: Make sure you selected the right version for your project
[15:58:30]: This build process was executed using '/Applications/Xcode.app'
[15:58:30]: If you want to update your Xcode path, either
[15:58:30]: 
[15:58:30]: - Specify the Xcode version in your Fastfile
[15:58:30]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[15:58:30]: 
[15:58:30]: - Specify an absolute path to your Xcode installation in your Fastfile
[15:58:30]: ▸ xcode_select "/Applications/Xcode8.app"
[15:58:30]: 
[15:58:30]: - Manually update the path using
[15:58:30]: ▸ sudo xcode-select -s /Applications/Xcode.app
[15:58:30]: 

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.64.1                  |
| export_method | app-store               |
| sdk           | iPhoneOS11.1.sdk        |
+---------------+-------------------------+

[15:58:30]: ▸ === BUILD TARGET X OF PROJECT X WITH CONFIGURATION Release ===
[15:58:30]: ▸ Check dependencies
[15:58:30]: ▸ Code Signing Error: Provisioning profile "X" doesn't include signing certificate "Y".
[15:58:30]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.1'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.1"

default_platform :ios

platform :ios do
  before_all do

    cocoapods
    
  end

  lane :store do
    cert
    sigh
    pem
    # build your iOS app
    gym(
      scheme: "x",
      workspace: "x",
      export_method: "app-store",
      clean: true,
      include_bitcode: true
    )
    #appstore
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "x" # The bundle identifier of your app
apple_id "x" # Your Apple email address

team_id "x" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.10       |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.3.1        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| concurrent-ruby           | 1.0.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.9.1        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.4        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-11-16**
</details>

**Comment by melakamc** [comment]
Facing the same issue.

Even if I have defined the `export_options.provisioningProfiles` to match the app ids with provisioning profiles, it always picks one provisioning profile and tries to sign with it.

**Comment by melakamc** [comment]
Right now im bypassing this by setting the provisioning profile manually using `update_project_provisioning` action

**Comment by royberris** [comment]
After 3 full days of searching... It seemed the certificate from my company was not completely right. After deleting every certificate under login I got the right certificate. In Xcode I also had the wrong profision profile. I had selected "Project Name" but I needed "Project Name Appstore <number>". Hope this will point anyone in the right direction.
