### ISSUE TITLE
Pilot action with groups

### ISSUE THREAD

**Issue by Blackjacx** [fastlane/fastlane#10915]
Hey there, 

would it be possible to add an example on https://docs.fastlane.tools/actions/pilot/ that uses groups? Currently that does not associate a new build to multiple groups when deploying to Testflight and maybe I am doing sth wrong when specifying the groups. So an example would be helpful.

**Comment by Blackjacx** [comment]
Here you go :-)

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.2                          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Fastlane Documentation:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
#
# Fastlane actions: 
# https://docs.fastlane.tools/actions/
#
# Bitrise with fastlane example:
# https://github.com/bitrise-samples/fastlane/blob/master/BitriseFastlaneSample/fastlane/Fastfile
#
# AUTHENTICATION
# https://docs.fastlane.tools/best-practices/continuous-integration/
# https://github.com/fastlane/fastlane/tree/master/spaceship
#
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
#
#
# This file was created by the help of https://gist.github.com/ulhas/e8e529d08849b8cda947
#
#
# NOTE: To use faslane first do:
#           gem install bundler && bundle install
#
#       and then run:
#           bundle exec fastlane release product_name:Gasoline version:"1.0.0" github_account:"blackjacx"
#           bundle exec fastlane test product_name:Gasoline
#
# Configure the following environment variables for your project 
# on your CI and in fastlane/.env:
#
# ENV["GITHUB_TOKEN"] = "..."
# ENV["SLACK_URL"] = "..."
# ENV["BITRISE_DEPLOY_DIR"] = "..."
# ENV['CRASHLYTICS_API_TOKEN'] = "..."
# ENV['CRASHLYTICS_BUILD_SECRET'] = "..."
# ENV['FASTLANE_USER'] = "..."
# ENV['FASTLANE_PASSWORD'] = "..."
# ENV['FASTLANE_DONT_STORE_PASSWORD'] = "..."



# TODO: deploy to TestFlight, Crashlytics, Hockey, ... & move away from Bitrise



# This is the minimum version number required. 
# Update this, if you use features of a newer version.
fastlane_version "2.55.0"

default_platform :ios


platform :ios do

  before_all do
    cocoapods(use_bundle_exec: true, repo_update: true)
  end

  after_all do
    # This is called, only if the executed lane was successful
    slack(success: true, message: "*Successfully Built App 🎉*")
  end

  error do |lane, exception|
    # This block is called, only if the executed lane failed
    slack(success: false, message: "*#{lane} failed with #{exception.message}*")
  end

  ##############################################################################
  # Playground Lane
  ##############################################################################

  lane :playground do |options|
  end

  ##############################################################################
  # Release Lane
  ##############################################################################

  desc "Releases a new product version"
  lane :release do |options|

    possible_tester_groups = ["appstore", "beta", "nightly"]
    tester_groups = "#{options[:tester_groups]}"

    raise "No product_name provided!".red unless options[:product_name]
    raise "No build provided!".red unless options[:build]
    raise "No github_account provided!".red unless options[:github_account]
    raise "No tester groups provided! Provide at least one of the following as ruby array: #{possible_tester_groups}".red if options[:tester_groups].empty?
    
    product_name = options[:product_name]
    build = options[:build]
    github_account = options[:github_account]
    project = "#{product_name}.xcodeproj"
    workspace = "#{product_name}.xcworkspace"
    version = get_version_number(xcodeproj: "#{project}", target: "#{product_name}")
    deploy_dir = ENV["BITRISE_DEPLOY_DIR"]
    ipa_name = "#{product_name}.ipa"
    ipa_path = "#{deploy_dir}/#{product_name}.ipa"
    dsym_path = "#{deploy_dir}/#{product_name}.app.dSYM.zip"
    run_danger = options[:run_danger]
    tester_whatsnew = File.read("./metadata/whatsnew.txt")
    export_options_plist = "./fastlane/ExportOptions.plist"

    test(product_name: product_name, run_danger: run_danger)

    # Increments CFBundleVersion by one and sets CFBundleShortVersionString
    increment_version_number(version_number: version)
    increment_build_number(build_number: build)

    # read changelog
    changelog = read_changelog(
      section_identifier: "[#{version}]",
      excluded_markdown_elements: []
    )

    changelog_no_md = changelog
        .gsub(/\* \[(.+): /, '* ')
        .gsub(/ - (.+)\./, '')
        .gsub(/###/, '')
        .strip

    gym(
      workspace: workspace, 
      scheme: product_name,
      buildlog_path: deploy_dir,
      output_directory: deploy_dir,
      output_name: ipa_name,
      export_options: export_options_plist,
      include_bitcode: true,
      include_symbols: true,
      clean: true
    )

    set_github_release(
      repository_name: "#{github_account}/#{product_name}",
      api_token: ENV["GITHUB_TOKEN"],
      name: version,
      tag_name: version,
      description: (changelog || "No changelog provided"),
      commitish: "master"
    )
    
    crashlytics(
      crashlytics_path: "./Pods/Crashlytics/iOS/Crashlytics.framework",
      groups: tester_groups,
      notes: changelog_no_md,
      notifications: false
    )

    pilot(
      changelog: changelog_no_md,
      ipa: "#{ipa_path}",
      groups: tester_groups,
      distribute_external: true
    )

    refresh_dsyms

    sh("ls -la #{deploy_dir}")
    puts tester_groups
  end

  ##############################################################################
  # Test Lane
  ##############################################################################

  desc "Runs tests optionally with danger"
  lane :test do |options|

    raise "No product_name provided!".red unless options[:product_name]

    product_name = options[:product_name]
    run_danger = options[:run_danger]

    # Easily run tests of your iOS app using scan
    scan(
      workspace: "#{product_name}.xcworkspace",
      scheme: product_name,
      clean: true,
      devices: ["iPhone 8"],
      skip_build: false,
      output_types: "html",
      skip_slack: true,
      output_directory: ENV["BITRISE_DEPLOY_DIR"]
    )

    # Runs danger for the project
    if run_danger
      danger(
        use_bundle_exec: true,
        github_api_token: ENV["GITHUB_TOKEN"],
        verbose: true
      )
    end
  end

  ##############################################################################
  # Manually Refreshing Crashlytics dSYM's
  ##############################################################################

  lane :refresh_dsyms do
    # This needs to be done after uploading a new app to ITC since Apple 
    # recompiles the apps from bitcode hich results in new dSYM's.
    # NOTE: upload_symbols_to_crashlytics relies in the installed Fabric.app
    # https://github.com/fastlane/fastlane/issues/10255
    # https://krausefx.com/blog/download-dsym-symbolication-files-from-itunes-connect-for-bitcode-ios-apps
    # https://docs.fabric.io/apple/crashlytics/missing-dsyms.html#upload-symbols-script
    user = ENV["FASTLANE_USER"]
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    
    download_dsyms(username: user, app_identifier: app_id, version: "latest")
    upload_symbols_to_crashlytics
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ioki.passenger" # The bundle identifier of your app

team_id "P4LECE5B35" # Developer Portal Team ID
itc_team_id "118614410" # ID identifying the team Deutsche Bahn AG

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.8.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| rake                      | 12.3.0       |
| CFPropertyList            | 2.3.5        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.15.0       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.5.5        |
| danger-plugin-api         | 1.0.0        |
| danger-changelog          | 0.2.1        |
| danger-commit_lint        | 0.0.6        |
| thor                      | 0.20.0       |
| danger-swiftlint          | 0.11.0       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-changelog | 0.8.0        |
</details>


*generated on:* **2017-11-17**
</details>

**Comment by taquitos** [comment]
Great idea! Improving docs is definitely something we want to do

**Comment by Blackjacx** [comment]
By the way can you help me and tell me how to pass multiple groups to pilot? So I cannot find infos regarding the exact syntax.

**Comment by taquitos** [comment]
Right now, you can't do that 😞  iTunes Connect just had some major changes to the TestFlight API including build trains, and tester groups, so we're still working through that.

**Comment by Blackjacx** [comment]
Ah alright that might be the issue. Thank you!

**Comment by taquitos** [comment]
Ok, we just released 2.66.0 🎉

**Comment by Blackjacx** [comment]
Which one is the relevant issue for this ticket?

* Replace all Tunes::Tester based APIs with TestFlight endpoints (#10959) via Joshua Liebowitz
* Fix for not properly listing out a found tester (#10964) via Joshua Liebowitz
* spaceship fixes for build trains (#10963) via Felix Krause
* Fix download dysms to be compatible with new testflight endpoints (#10961) via David Ohayon
* Fix app_store_build_number command (#10947) via Dave Anderson
* Allow the user to select their scheme during fastlane init (#10955) via Manu Wallner
* Change to upgrade tty-screen dependency in ref to issue #10820 (#10866) via Piotr Murach

**Comment by revolter** [comment]
@Blackjacx, I think you're looking for #10959 but I'm not 100% sure.

**Comment by mpirri** [comment]
@Blackjacx Yeah, #10959, but also #10964 and #10963 as well. We've put out quite a few PRs to get all of this working again!  Thanks for your patience with this! 🚀

**Comment by taquitos** [comment]
Yeah, thanks for your patience here @Blackjacx, when we get slammed with huge Apple API changes it can be... _fun_ to get everything up and running again 🎈

**Comment by Blackjacx** [comment]
Wow wow wow thank you very much for the feedback! But to come back to my original question: could you provide some examples how to specify multiple groups to the pilot action when used inside the Fastfile?

**Comment by taquitos** [comment]
The primary way you set groups is using the friendly name like:
```
pilot(
  ...
  group: ['Group Name1', 'Group Name 2'],
  distribute_external: true,
  ...
)
```
That seems to work for associating testers as well as distributing to specific groups. If it doesn't work, let us know!

Also, there is some language around `distribute_external`
I don't know that it works as expected in this brand new API world, but a quick grok through the code suggests that if you have testers in an external tester group right now, you'll still need that.

**Comment by Blackjacx** [comment]
I will try that out with our next release. Thank you very much :)

**Comment by Blackjacx** [comment]
OK, I can confirm that this works!

**Comment by KrauseFx** [comment]
Awesome, thanks @Blackjacx 👍
