### ISSUE TITLE
Unable to export test users using pilot

### ISSUE THREAD

**Issue by wuftymerguftyguff** [fastlane/fastlane#10918]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Unable to export test users with pilot

##### Complete output when running fastlane, including the stack trace and command used
fastlane pilot export --username xxx@yyy.com
[14:57:12]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:57:14]: Login to iTunes Connect (xxx@yyy.com)
[14:57:19]: Login successful

Looking for related GitHub issues on fastlane/fastlane...

➡️  [!] no implicit conversion of nil into String (TypeError) in Hockey acktion
    https://github.com/fastlane/fastlane/issues/9622 [closed] 7 💬
    25 Sep 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/client.rb:599:in `parse_response': [!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::Client::UnexpectedResponse)
<String>There is no route for the path 'users/pre/ext'.</String>

	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1181:in `testers'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/tester.rb:83:in `all'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/pilot/lib/pilot/tester_exporter.rb:17:in `export_testers'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/pilot/lib/pilot/commands_generator.rb:141:in `block (2 levels) in run'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/bin/fastlane:20:in `<top (required)>'
	from /Users/jeffa/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/jeffa/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.1                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.13.3                              |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane             |
| Host                        | Mac OS X 10.13.1 (17B48)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | true                                            |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.1.app/Contents/Developer/ |
| Xcode Version               | 9.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>


*generated on:* **2017-11-16**
</details>


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.1                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.13.3                              |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane             |
| Host                        | Mac OS X 10.13.1 (17B48)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | true                                            |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.1.app/Contents/Developer/ |
| Xcode Version               | 9.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-11-16**
</details>

**Comment by taquitos** [comment]
Apple just updated TestFlight APIs for some new features, which are awesome, but that means we need to update fastlane. Hopefully we'll have this resolved soon 👍

**Comment by vspac** [comment]
Hi @taquitos, does Apple provide some TestFlight  API doc? I googled for it but no luck :(

**Comment by taquitos** [comment]
@vspac they don't provide an API. Here's how we figure out API changes: https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md#debugging-and-patching-spaceship-issues

**Comment by mpirri** [comment]
@wuftymerguftyguff We have shipped a version of _fastlane_ that should fix this issue (version 2.66.2). Can you give this a try and see if it fixes your issue? Thanks!  🚀

**Comment by wuftymerguftyguff** [comment]
Hi,

Different error, but still failing:

```
fastlane pilot export --username xxx@yyy.com
[22:03:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[22:03:26]: Login to iTunes Connect (xxx@yyy.com)
[22:03:30]: Login successful

Looking for related GitHub issues on fastlane/fastlane...

➡️  latest_testflight_build_number return incorrect build number & crash when live_version parameter is true
    https://github.com/fastlane/fastlane/issues/10923 [closed] 15 💬
    2 hours ago

➡️  When requesting to remove a user output states 'tester_id' is required
    https://github.com/fastlane/fastlane/issues/10006 [closed] 8 💬
    6 weeks ago

➡️  Build disappears from TestFlight after uploading via pilot and processing
    https://github.com/fastlane/fastlane/issues/10001 [closed] 4 💬
    6 weeks ago

and 14 more at: https://github.com/fastlane/fastlane/search?q=%60app_id%27%20is%20a%20required%20parameter&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/test_flight/client.rb:292:in `block in assert_required_params': [!] `app_id' is a required parameter (NameError)
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/test_flight/client.rb:290:in `each'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/test_flight/client.rb:290:in `assert_required_params'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/test_flight/client.rb:146:in `testers_for_app'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/test_flight/tester.rb:79:in `all'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/pilot/lib/pilot/tester_exporter.rb:18:in `export_testers'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/pilot/lib/pilot/commands_generator.rb:142:in `block (2 levels) in run'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/pilot/lib/pilot/commands_generator.rb:160:in `run'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/jeffa/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.2/bin/fastlane:20:in `<top (required)>'
	from /Users/jeffa/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/jeffa/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by taquitos** [comment]
@wuftymerguftyguff the first line on that stack trace has `'app_id' is a required parameter`
Unfortunately, the API that used to query for every tester doesn't exist. You'll have to pass in the `app_id`

**Comment by wuftymerguftyguff** [comment]
@taquitos Okay, this is no problem to add, but FYI this used to work

**Comment by bpham711** [comment]
@taquitos how do you pass the app_id? Can you provide an example command line?
