### ISSUE TITLE
Frameit: Need to turn device to left in landscape mode

### ISSUE THREAD

**Issue by IchHabRecht** [fastlane/fastlane#10928]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I need to turn the iPhones (especially iPhone X) to left in landscape mode instead to right. Your example screens are showing exactly the mode I need but I can't find any option to set correct orientation. Is there anything I can do?

**Comment by IchHabRecht** [comment]
Any suggestion how to solve this issue? Any plans to be able to add configuration for rotation?

**Comment by milch** [comment]
Hi @IchHabRecht! Can you post your Xcode UI test code that you are using to take the screenshots please?

**Comment by IchHabRecht** [comment]
Hi @milch,

Not sure what my test is need for, but here you go

```
func testDetailView() {
        let app = XCUIApplication()
        
        for themeValue in Theme.allValues {
            XCUIDevice.shared.orientation = .portrait
            
            changeTheme(to: themeValue)
            
            let table = app.tables.firstMatch
            let lastCell = table.cells.allElementsBoundByIndex[table.cells.count - 1]
            
            swipeToLastCell(table: table)
            
            lastCell.tap()
            
            snapshot("02 Detail " + themeValue.capitalized + " Portrait", waitForLoadingIndicator: false)
            
            swipeToLastCell(table: app.tables.allElementsBoundByIndex[app.tables.count - 1])
            
            snapshot("02 Detail " + themeValue.capitalized + " Portrait2", waitForLoadingIndicator: false)
            
            if app.navigationBars.count == 1 {
                goBack()
            }
            
            XCUIDevice.shared.orientation = .landscapeLeft
            
            swipeToLastCell(table: table)
            
            lastCell.tap()
            
            snapshot("02 Detail " + themeValue.capitalized + " Landscape", waitForLoadingIndicator: false)
            
            swipeToLastCell(table: app.tables.allElementsBoundByIndex[app.tables.count - 1])
            
            snapshot("02 Detail " + themeValue.capitalized + " Landscape2", waitForLoadingIndicator: false)
            
            if app.navigationBars.count == 1 {
                goBack()
            }
        }
    }
```

**Comment by milch** [comment]
Thank you! I did some investigating, I think it *should* work but it seems to require you to name your screenshots with a "landscapeleft" suffix. So you'd need to change your snapshot lines to:

```swift 
snapshot("02 Detail " + themeValue.capitalized + " landscapeleft", waitForLoadingIndicator: false)
// later...
snapshot("02 Detail " + themeValue.capitalized + " 2landscapeleft", waitForLoadingIndicator: false)
```

I'll do some more investigating. We should definitely add a parameter of some sort for this or at the very least document this properly. 

What do you think how this should be configured? A hash mapping from filename to screenshot orientation? A simple flag saying whether landscape orientation should be landscape left or right?

**Comment by milch** [comment]
Thank you! I did some investigating, I think it *should* work but it seems to require you to name your screenshots with a "landscapeleft" suffix. So you'd need to change your snapshot lines to:

```swift 
snapshot("02 Detail " + themeValue.capitalized + " landscapeleft", waitForLoadingIndicator: false)
// later...
snapshot("02 Detail " + themeValue.capitalized + " 2landscapeleft", waitForLoadingIndicator: false)
```

I'll do some more investigating. We should definitely add a parameter of some sort for this or at the very least document this properly. 

What do you think how this should be configured? A hash mapping from filename to screenshot orientation? A simple flag saying whether landscape orientation should be landscape left or right?

**Comment by IchHabRecht** [comment]
Hi @milch,

Thank you for your investigation already. Will try to rename the files manually first and re-start frameit.

According to the parameter question: for me personally both possibilities would fit perfectly. Also getting the rotation direction from filename seems to be more comfortable. So it would be possible to have a test that turns the device in both directions and the frames would fit automatically.

**Comment by IchHabRecht** [comment]
Unfortunately renaming to landscapeleft doesn't work to enforce the correct frame rotation.

**Comment by milch** [comment]
Sorry about that, it seems I misjudged what the code did. 

In any case, I submitted a PR #11161 that enables this. I made it so that by default files ending in `force_landscapeleft` and `force_landscaperight` will be forced to that orientation. 

If you don't want to wait until this is released, you can try my branch by using a `Gemfile`. Create a `Gemfile` in your project directory: 

```ruby
gem "fastlane", github: "milch/fastlane", branch: "feature/frameit-landscape-orientation"
```

Make sure to install bundler if you don't have it already. Then, in your command line, run `bundle install` and you will be able to run frameit/fastlane by using `bundle exec`: 

```bash
bundle exec fastlane frameit
```

To get back to a regular release version of fastlane you can simply remove the `Gemfile`, or remove the `github` and `branch` parameters from the `Gemfile` I presented above to read:

```ruby
gem "fastlane"
```

If you removed the `Gemfile` simply remove the `bundle exec` from your fastlane commands. Otherwise you can re-run `bundle install` after you've made the above edits.

Let me know if you have any questions!

**Comment by IchHabRecht** [comment]
Hi @milch,

Thank you for the patch and even more for that perfect description how to include your branch. I even was able to provide an own function to turn left on "landscapeleft" prefix only :-D

**Comment by milch** [comment]
Perfect, thanks for testing. I will close this issue now since my branch seems to fix everything. Let me know if you run into any more issues!
