### ISSUE TITLE
[Question] How do I release an iOS build that was set not to auto release but has been approved?

### ISSUE THREAD

**Issue by CliffCawley** [fastlane/fastlane#10926]
### Question

I couldn't find this in the docs anywhere so I'm sorry if I'm asking this in the wrong place !

I've got an iOS build that I successfully uploaded and released for review with fastlane deliver.

I set automatic_release to false as I need to control when it's released after it's been reviewed.

`fastlane deliver submit_build --username zzz@yyy.com --app_identifier com.myco.myapp --submit_for_review true --automatic_release false --skip_metadata false --force true --skip_binary_upload true`

The build has now been approved by Apple and is Pending developer release.  How do I now tell it to release with fastlane?

On Android I just use `fastlane supply --package_name com.myco.myapp --track alpha --track_promote_to production` 

How do I do this for iOS?

**Comment by CliffCawley** [comment]
I don't think the fastlane env will help here :)

**Comment by CliffCawley** [comment]
Anyone?

**Comment by CliffCawley** [comment]
Anyone except the bot able to respond?

**Comment by KrauseFx** [comment]
Sorry for the late response @CliffCawley, somehow missed the notification on this one. There is no built-in action to do that currently. You could build that using [spaceship](https://spaceship.airforce), but none of the fastlane tools can release an existing build for now. Instead what you can do is to submit a new build and set the `automatic_release` flag to `true`. Let me know if that helps

**Comment by CliffCawley** [comment]
Ah no worries, thanks for the info :)
