### ISSUE TITLE
Couldn't decrypt the repo, please make sure you enter the right password! - running match

### ISSUE THREAD

**Issue by mberthos** [fastlane/fastlane#10931]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running command for generate and management certified : 
- fastlane match development

Require a password for encrypt/decrypt, but this password not exists, i tried all passwords, but not success.

##### Complete output when running fastlane, including the stack trace and command used
INFO [2017-11-17 05:32:16.88]: Cloning remote git repo...
INFO [2017-11-17 05:32:16.88]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2017-11-17 05:32:16.88]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@bitbucket.org:tecsinapse/ios-certificates.git' '/var/folders/jw/tmzdrc590w7f2m3tsg5v5hb00000gp/T/d20171117-30393-1xhuu4d'
INFO [2017-11-17 05:32:16.89]: ▸ Cloning into '/var/folders/jw/tmzdrc590w7f2m3tsg5v5hb00000gp/T/d20171117-30393-1xhuu4d'...
INFO [2017-11-17 05:32:17.17]: ▸ remote: Counting objects: 12, done.
INFO [2017-11-17 05:32:17.17]: ▸ remote: Compressing objects: 100% (11/11), done.
INFO [2017-11-17 05:32:17.17]: ▸ remote: Total 12 (delta 0), reused 0 (delta 0)
INFO [2017-11-17 05:32:17.17]: ▸ Receiving objects: 100% (12/12), 7.55 KiB | 0 bytes/s, done.
INFO [2017-11-17 05:32:17.18]: ▸ Checking connectivity... done.
WARN [2017-11-17 05:32:17.22]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2017-11-17 05:32:17.22]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2017-11-17 05:32:17.22]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2017-11-17 05:32:17.22]: Passphrase for Git Repo: *******
 [2017-11-17 05:32:21.44]: Type passphrase again: *******
security: SecKeychainAddInternetPassword <NULL>: User interaction is not allowed.
error reading input file
ERROR [2017-11-17 05:32:25.40]: Couldn't decrypt the repo, please make sure you enter the right password!
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.3 (Apple Git-75)            |
| Installation Source         | /usr/local/rvm/gems/ruby-2.3.1/bin/fastlane |
| Host                        | Mac OS X 10.11.6 (15G1611)                  |
| Ruby Lib Dir                | /usr/local/rvm/rubies/ruby-2.3.1/lib        |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| excon                     | 0.59.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| faraday_middleware        | 0.12.2       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-11-17**

**Comment by fhperuchi** [comment]
I have the same issue here. I tried to run inside Mac OS X El Captain via terminal and I tried to run it via SSH session too.

I unlocked the keychain before I run the command **fastlane match development --verbose** and it did not make effect:
security unlock-keychain -p `cat ~/.file_with_your_password` ~/Library/Keychains/login.keychain

I would appreciate any help.
Thanks.

**Comment by ssmlee04** [comment]
I think this is the solution. #10851

**Comment by steven-luu** [comment]
I hit this issue today.  

In my case, it was due to me storing other unencrypted keys in a different folder within the repo. See closed issue https://github.com/fastlane/fastlane/issues/8796

**Comment by mberthos** [comment]
I will try to do it....and i will let you know if solve for me too. Thanks.

**Comment by svanzoest** [comment]
You can use `fastlane match init` to set the password or via env `MATCH_PASSWORD`. This is an additional password used to encrypt the files in the repo, this is not your git or apple password.

**Comment by mberthos** [comment]
Hello, i will tried to create a new clean repo and export the password for MATCH_PASSWORD, but return a new error, this error i never see, it is new for me .
[!] Could not install WWDR certificate

####################################################################
TEMP-AUTO-DU-EL12-71:certificates jenkins$ export MATCH_PASSWORD=testpasswd
TEMP-AUTO-DU-EL12-71:certificates jenkins$ fastlane match development
[10:10:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:10:06]: Successfully loaded '/Users/jenkins/.fastlane/certificates/Matchfile' 📄

+----------------+-----------------------------------------------+
|               Detected Values from './Matchfile'               |
+----------------+-----------------------------------------------+
| git_url        | git@bitbucket.org:tecsinapse/certificates.git |
| type           | development                                   |
| app_identifier | ["com.homolog.Cavadinha"]                     |
| username       | applestore@tecsinapse.com.br                  |
+----------------+-----------------------------------------------+


+-----------------------+-----------------------------------------------+
|                       Summary for match 2.66.2                        |
+-----------------------+-----------------------------------------------+
| type                  | development                                   |
| git_url               | git@bitbucket.org:tecsinapse/certificates.git |
| git_branch            | master                                        |
| app_identifier        | ["com.homolog.Cavadinha"]                     |
| username              | applestore@tecsinapse.com.br                  |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| verbose               | false                                         |
| force                 | false                                         |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| clone_branch_directly | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
| platform              | ios                                           |
+-----------------------+-----------------------------------------------+

[10:10:06]: Cloning remote git repo...
[10:10:06]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:10:10]: 🔓  Successfully decrypted certificates repo
[10:10:10]: Verifying that the certificate and profile are still valid on the Dev Portal...
[10:10:13]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+-------------------------------------------------+
|                     Summary for cert 2.66.2                     |
+---------------+-------------------------------------------------+
| development   | true                                            |
| force         | true                                            |
| username      | applestore@tecsinapse.com.br                    |
| keychain_path | /Users/jenkins/Library/Keychains/login.keychain |
| platform      | ios                                             |
+---------------+-------------------------------------------------+

[10:10:13]: Starting login with user 'applestore@tecsinapse.com.br'
[10:10:14]: Successfully logged in
[10:10:16]: Successfully generated F33Y25JB57 which was imported to the local machine.
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0   2319      0 --:--:-- --:--:-- --:--:--  2323
security: SecKeychainItemImport: UNIX[Invalid argument]

[!] Could not install WWDR certificate

**Comment by steven-luu** [comment]
I didn't know `fastlane match init` would _encrypt the files in the repo_ at will.  That's kind of neat.

To clarify my previous post, I moved my **non-match** related certs out of the 'match managed' git repo.  This made sense to me since match hit: `error reading input file`, and my certs were unencrypted.

As a first step, could you take a look in the repo and see if you can find any **non-match** managed certs? The **match** certs are named like this `9K2A52KX36.cer`

**Comment by ohayon** [comment]
Hey folks, _match_ should take care of moving the cert into the repo and the encryption all for you. We don't recommend manually putting things into the repo you are using for match as it can cause this sort of problem. It seems like people are back up and running so I am going to close this issue, but please feel free to continue conversation if things are still going wrong and we can reopen it if necessary! Thanks!

**Comment by joshdholtz** [comment]
@mberthos Were you able to figure this out? This definitely looks like you don't have proper access to your keychain with `security: SecKeychainAddInternetPassword : User interaction is not allowed.` which can happen if you are running this over SSH
