### ISSUE TITLE
SecKeychainItemImport: The specified keychain is not a valid keychain file.

### ISSUE THREAD

**Issue by GarryGaGarry** [fastlane/fastlane#10932]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Captured Output
+---------+-------------------------------------------------+
|        Detected Values from './fastlane/Matchfile'        |
+---------+-------------------------------------------------+
| git_url | git@github.com:******/******-ios-sertificate  |
|         | .git                                            |
| type    | development                                     |
+---------+-------------------------------------------------+

+-----------------------+-------------------------------------------------+
|                        Summary for match 2.64.1                         |
+-----------------------+-------------------------------------------------+
| app_identifier        | ["com.******.********"]                         |
| readonly              | true                                            |
| git_url               | git@github.com:******/*******-ios-sertificate  |
|                       | .git                                            |
| type                  | development                                     |
| git_branch            | master                                          |
| username              | sem*********@gmail.com                          |
| keychain_name         | login.keychain                                  |
| team_id               | 2Y2B*******                                      |
| team_name             | LLC Topface                                     |
| verbose               | false                                           |
| force                 | false                                           |
| skip_confirmation     | false                                           |
| shallow_clone         | false                                           |
| clone_branch_directly | false                                           |
| force_for_new_devices | false                                           |
| skip_docs             | false                                           |
| platform              | ios                                             |
+-----------------------+-------------------------------------------------+

[14:45:44]: Cloning remote git repo...
[14:45:44]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:45:46]: 🔓  Successfully decrypted certificates repo
[14:45:46]: Installing certificate...
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0   3617      0 --:--:-- --:--:-- --:--:--  3612
security: SecKeychainItemImport: The specified keychain is not a valid keychain file.
[14:45:48]: --------------------------
[14:45:48]: --- Step: notification ---
[14:45:48]: --------------------------
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios calabash_test |
+------------------+-------------------+
[14:45:48]: Could not install WWDR certificate

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 💥   | match                        | 2           |
| 4    | notification                 | 0           |
+------+------------------------------+-------------+

[14:45:48]: fastlane finished with errors

[!] Could not install WWDR certificate

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| addressable               | 2.5.2        |
| tty-screen                | 0.5.1        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| json                      | 1.8.6        |
| multi_json                | 1.12.2       |
| xcpretty-travis-formatter | 1.0.0        |
| declarative               | 0.0.10       |
| retriable                 | 3.1.1        |
| jwt                       | 2.1.0        |
| signet                    | 0.8.1        |
| os                        | 0.9.6        |
| memoist                   | 0.16.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| googleauth                | 0.6.1        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-11-17**

**Comment by Athosone** [comment]
I got exactly the same issue,
create_keychain does not seems to create the keychain at the path specified in the parameter "path"...
Any idea on it ?

**Comment by ifiokjr** [comment]
I'm having the same issue. I setup fastlane on a particular machine and am testing on another machine to ensure it works consistently and this is cropping up. 

```
security: SecKeychainItemImport: The specified keychain could not be found.
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios develop |
+------------------+-------------+
[17:28:33]: Could not install WWDR certificate

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | match               | 7           |
+------+---------------------+-------------+

[17:28:33]: fastlane finished with errors

[!] Could not install WWDR certificate
```


Here's my fastlane env output. 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.66.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods # TODO: Add pod support
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :develop do
    match(type: "development") # more information: https://codesigning.guide
    gym(
      scheme: "mainapp",
      export_method: "development",
      configuration: "Debug"
    )

    # Uncomment to install on a connected device
    install_on_device(
      ipa: "./mainapp.ipa"
    )

  end


  desc "Register a new device to use for testing builds"
  lane :add_device do
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(
      devices: device_hash
    )
    refresh_profiles
  end

  desc "A helper lane for refreshing provisioning profiles."
  lane :refresh_profiles do
    match(
      force_for_new_devices: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "adhoc")
    gym(
      scheme: "mainapp",
      export_method: "ad-hoc",
      configuration: "Release"
    )

    # Currently the following command will fail
    # pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
  end


  after_all do |lane|
    # TODO: Obtain slack details
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # TODO: Obtain slack details
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<APP_BUNDLE>" # App bundle identifier
apple_id "<VALID_ID>i" # Apple email address

team_id "<TEAM_ID>" # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>


*generated on:* **2017-11-26**
</details>

**Comment by ifiokjr** [comment]
I've managed to resolve the issue. 

I followed the instructions outlined here. 

https://github.com/fastlane/fastlane/issues/6993#issuecomment-281650521

All I had to do was drag my login keychain to the top of the list in the left-hand pane. Very trivial.
