### ISSUE TITLE
`bundle exec fastlane` => 0 (cancel) outputs broken advice

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10936]
Running `bundle exec fastlane` outputs a list of the available lanes. If you decide not to continue and select `0` to cancel, it outputs somewhat broken advice:

```
...
| 0      | cancel                        | No selection, exit fastlane!             |
+--------+-------------------------------+------------------------------------------+
[15:52:18]: Which number would you like run?
0

[!] Run `fastlane` the next time you need to build, test or release your app 🚀
```

That last line should probably not be output when selecting `0` to cancel.

**Comment by revolter** [comment]
Was it like this from start?

**Comment by janpio** [comment]
No idea, used the number selection thing (instead of specifying the lane by name) for the first time today.

**Comment by milch** [comment]
From [the code](https://github.com/fastlane/fastlane/blob/6b8718fe3e418979c49cc2d0d4f3cce2fc7c42f4/fastlane/lib/fastlane/lane_manager.rb#L171) this seems like it is intentional

**Comment by revolter** [comment]
@milch, Indeed, but it is rather odd. Because it's saying to run `fastlane` the next time, but then the same message shows up if you input the same option (`0`). Wouldn't

    Run `fastlane <lane_name>` the next time you need to build, test or release your app 🚀

sound better? Or it could cause confusion?

**Comment by milch** [comment]
Hmm, well if you run `fastlane` the next time and don't cancel, it'll tell you the right command to run at that point. Maybe one could add `Run `fastlane lanes` to find out which commands are supported` to the end of that sentence to make it more explicit what you can do?
