### ISSUE TITLE
fastlane init attempts to create an app for framework in workspaces

### ISSUE THREAD

**Issue by GRiMe2D** [fastlane/fastlane#10952]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Project Structure
```
xcodeworkspace
├ moneyapp-ios (App)
├ privateframework-ios (Dynamic Framework)
└ ReactiveObjC-iOS (Dynamic framework)
```

`fastlane init` tries to register apps for frameworks in iTunesConnect and Apple Developer. Unable to skip. 

##### Complete output when running fastlane, including the stack trace and command used
```[16:23:47]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:23:50]: Detected iOS/Mac project in current directory...
[16:23:50]: This setup will help you get up and running in no time.
[16:23:50]: fastlane will check what tools you're already using and set up
[16:23:50]: the tool automatically for you. Have fun! 
[16:23:50]: Created new folder './fastlane'.
[16:23:50]: $ xcodebuild -list -workspace ./moneyapp.xcworkspace
[16:23:52]: $ xcodebuild -showBuildSettings -workspace ./moneyapp.xcworkspace -scheme ReactiveObjC-iOS
[16:23:54]: Your Apple ID (e.g. fastlane@krausefx.com):
```

**Comment by janpio** [comment]
Could you please update your issue with output that shows the problem you are reporting?

**Comment by GRiMe2D** [comment]
```
$ fastlane init
[17:39:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:39:45]: Detected iOS/Mac project in current directory...
[17:39:45]: This setup will help you get up and running in no time.
[17:39:45]: fastlane will check what tools you're already using and set up
[17:39:45]: the tool automatically for you. Have fun! 
[17:39:45]: $ xcodebuild -list -workspace ./moneyapp.xcworkspace
[17:39:47]: $ xcodebuild -showBuildSettings -workspace ./moneyapp.xcworkspace -scheme ReactiveObjC-iOS
[17:39:49]: Your Apple ID (e.g. fastlane@krausefx.com): <<<private_email>>>@gmail.com    
[17:40:06]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[17:40:06]: Starting login with user '<<<private_email>>>@gmail.com'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) 82AG5W5ZL9 "<company_1> Ltd." (Company/Organization)
2) TVZPUPLA8S "<company_2> OOO" (Company/Organization)
2
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "1095995"

or

  itc_team_name "<company_1> Ltd."

1) "<company_1> Ltd." (1095995)
2) "<company_2>" (117877032)
3) "Shakhzod Ikromov" (118065365)
2

+----------------+--------------------------------------+
|                    Detected Values                    |
+----------------+--------------------------------------+
| Apple ID       | <<<private_email>>>@gmail.com        |
| App Name       | ReactiveObjC                         |
| App Identifier | org.reactivecocoa.ReactiveObjC       |
| Workspace      | /Users/grime2d/Documents/Repositori  |
|                | es/aabbccdouble/moneyapp/moneyapp.x  |
|                | cworkspace                           |
+----------------+--------------------------------------+

[17:40:38]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[17:40:38]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
[17:40:38]: Please confirm the above values (y/n)
n
[17:40:46]: Falling back to manual onboarding
[17:40:46]: App Identifier (com.krausefx.app): ^C
Cancelled... use --verbose to show the stack trace```

**Comment by milch** [comment]
If I'm understanding this correctly, your issue is that when you run `fastlane init` it uses produce to automatically create the app on iTunes Connect and on the Apple Developer portal, right? In that case I would just advise you to configure fastlane manually. You can easily do this by creating a `fastlane` directory in your project and then creating a `Fastfile` and an `Appfile` in there.

You can use the files that `fastlane init` uses as templates: 

- `Appfile`: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/AppfileTemplate
- `Fastfile`: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/DefaultFastfileTemplate

**Comment by GRiMe2D** [comment]
The issue is `fast lane init` automatically creates an app with identifier for dynamic framework.

**Comment by janpio** [comment]
So this is wrong and should not happen in your opinion:

```
+----------------+--------------------------------------+
|                    Detected Values                    |
+----------------+--------------------------------------+
...
| App Name       | ReactiveObjC                         |
| App Identifier | org.reactivecocoa.ReactiveObjC       |
...
+----------------+--------------------------------------+
```

Correct?

**Comment by GRiMe2D** [comment]
Yes. As you can see here, there multiple schemes in project, and libraries are built from sources (they are patched).

`fastlane init` should at least ask which one to use as "target" app for building and publishing it to TestFlight, iTunesConnect and etc.
![screen shot 2017-11-20 at 5 58 57 pm](https://user-images.githubusercontent.com/6705445/33024693-d6fca49a-ce1c-11e7-8901-744c04ae0612.png)

**Comment by milch** [comment]
Unfortunately for Xcode workspaces fastlane can't easily detect which is the right scheme that the user wants to build, and asking the user might be problematic because CocoaPods integrates lots of schemes into the project. 

As a workaround, you can manually reorder the schemes in the list: just drag your "moneyapp" scheme to the top. If it is the first scheme in the list, fastlane should auto-select it instead of the other ones

**Comment by GRiMe2D** [comment]
Thank you, it worked. Maybe we need document this somewhere?

Btw, issue can be closed

**Comment by milch** [comment]
@GRiMe2D Thank you, I'll close this issue now! 

I've also opened a [PR](https://github.com/fastlane/fastlane/pull/10955) that will default to choosing a scheme that matches your project name (as that is the default when you create a new project in Xcode) and will ask you for the scheme otherwise
