### ISSUE TITLE
Proposal for new action lizard

### ISSUE THREAD

**Issue by liaogz82** [fastlane/fastlane#10950]
I propose to the fastlane community to add in a new action lizard for code complexity analysis.

Reasons are:

1) Sonar uses lizard quite extensively but have to use `sh("cd .. && lizard ./[SOURCE_FOLDER] -l swift --xml > ./reports/lizard-report.xml")`. Refer to [here](https://github.com/Backelite/sonar-swift/blob/develop/docs/sonarqube-fastlane.md#using-with-fastlane-)

2) lizard has wide support in the community

3) there are no action in fastlane that does code complexity analysis. the closest I see is swiftlint, but swiftlint is more of a code convention enforcer.

I have the customized action ready for lizard. Once the admins are ok, I can fork out fastlane and add in my action for review.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by milch** [comment]
As far as I know there is no standardised process for creating new actions at the moment, see the docs here: https://docs.fastlane.tools/plugins/create-plugin/#submitting-the-action-to-the-fastlane-main-repo

I would suggest that you create a fastlane plugin, which are supported as first-class citizens within fastlane. Adding them is very easy and they even have [their own page](https://docs.fastlane.tools/plugins/available-plugins/) in the docs. Once you've published your plugin, this will make it easier for the developers and the community of fastlane to decide wether your action fulfils all three criteria from the link above:

* Generally usable for a big majority of developers (e.g. basic interactions with git)
* Solve pain points for mobile app developers (iOS and Android)
* have an easy to read documentation and great test coverage

If it does, a decision can be made wether to include it in fastlane permanently as an action or not.

**Comment by liaogz82** [comment]
ok thanks
