### ISSUE TITLE
[!] undefined method `fetch' for #<String:0x007fb9844e32d0> (NoMethodError)

### ISSUE THREAD

**Issue by wenjuan82** [fastlane/fastlane#10967]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to submit app build to AppStore review with "fastlane deliver" command. The fastlane version is 2.64.1. Following error is occurred.
##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2017-11-17 15:28:13.67]: Login to iTunes Connect (lijinsuo@didichuxing.com)
Looking for iTunes Connect Team with ID 1439882
INFO [2017-11-17 15:29:35.66]: Login successful

+----------------------------------------------------+-------------------------------------+
 |                                  deliver 2.64.1 Summary                                  |
+----------------------------------------------------+-------------------------------------+
| team_id                                            | ----                             |
| team_name                                          | ---. |
| username                                           | ---            |
| app_identifier                                     | ----     |
| submit_for_review                                  | true                                |
| skip_screenshots                                   | true                                |
| force                                              | true                                |
| skip_binary_upload                                 | true                                |
| skip_metadata                                      | true                                |
| run_precheck_before_submit                         | false                               |
| submission_information.add_id_info_uses_idfa       | true                                |
| submission_information.add_id_info_serves_ads      | false                               |
| submission_information.add_id_info_tracks_install  | true                                |
| submission_information.add_id_info_tracks_action   | true                                |
| submission_information.add_id_info_limits_tracking | true                                |
| screenshots_path                                   | ./screenshots                       |
| metadata_path                                      | ./metadata                          |
| edit_live                                          | false                               |
| platform                                           | ios                                 |
| skip_app_version_update                            | false                               |
| automatic_release                                  | false                               |
| overwrite_screenshots                              | false                               |
| precheck_default_rule_level                        | warn                                |
 | ignore_language_directory_validation               | false                               |
| precheck_include_in_app_purchases                  | true                                |
+----------------------------------------------------+-------------------------------------+

INFO [2017-11-17 15:29:41.09]: Selecting the latest build...
 INFO [2017-11-17 15:29:44.26]: Selecting build 5.0.24 (5.0.24.1711171200)...
INFO [2017-11-17 15:29:47.35]: Successfully selected build
INFO [2017-11-17 15:29:47.35]: Submitting the app for review...
INFO [2017-11-17 15:30:23.69]: Setting 'add_id_info_uses_idfa' to 'true'...
INFO [2017-11-17 15:30:23.69]: Setting 'add_id_info_serves_ads' to 'false'...
INFO [2017-11-17 15:30:23.69]: Setting 'add_id_info_tracks_install' to 'true'...
INFO [2017-11-17 15:30:23.69]: Setting 'add_id_info_tracks_action' to 'true'...
INFO [2017-11-17 15:30:23.69]: Setting 'add_id_info_limits_tracking' to 'true'...
/Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/tunes_client.rb:990:in `send_app_submission': [!] undefined method `fetch' for #<String:0x007fb9844e32d0> (NoMethodError)
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/app_submission.rb:144:in `complete!'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/deliver/lib/deliver/submit_for_review.rb:25:in `submit!'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/deliver/lib/deliver/runner.rb:154:in `submit_for_review'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/deliver/lib/deliver/runner.rb:36:in `run'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
	from /Users/didi/.rvm/gems/ruby-2.2.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/didi/.rvm/gems/ruby-2.2.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/didi/.rvm/gems/ruby-2.2.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/didi/.rvm/gems/ruby-2.2.5/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/didi/.rvm/gems/ruby-2.2.5/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/deliver/lib/deliver/commands_generator.rb:176:in `run'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/didi/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/bin/fastlane:20:in `<top (required)>'
	from /Users/didi/fastlane-downloads/fastlane-2.64.1/fastlane:23:in `load'
	from /Users/didi/fastlane-downloads/fastlane-2.64.1/fastlane:23:in `<main>'
	from /Users/didi/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/didi/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'

```

### Environment

[09:27:06]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:27:09]: Generating fastlane environment output, this might take a few seconds...
<details><summary>astlane environment summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.11.6                                       |
| Ruby                        | 2.2.5                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.8.4 (Apple Git-73)              |
| Installation Source         | ~/fastlane-downloads/fastlane-2.64.1/fastlane |
| Host                        | Mac OS X 10.11.6 (15G31)                      |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.5/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                     |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version               | 8.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.64.1  | pdate available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 1.16.0       |
| slack-notifier        | 1.5.1        |
| CFPropertyList        | 2.3.5        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.2.8        |
| terminal-notifier     | 1.8.0        |
| unicode-display_width | 1.3.0        |
| terminal-table        | 1.8.0        |
| plist                 | 3.3.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| highline              | 1.7.8        |
| commander-fastlane    | 4.4.5        |
| unf_ext               | 0.0.7.4      |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| gh_inspector          | 1.0.3        |
| json                  | 1.8.1        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| dotenv                | 2.2.1        |
| faraday_middleware    | 0.12.2       |
| uber                  | 0.1.0        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| retriable             | 3.1.1        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| excon                 | 0.59.0       |
| tty-screen            | 0.5.1        |
| faraday               | 0.13.1       |
</details>

**Comment by wenjuan82** [comment]
I have upgrade fastlane into 2.66.0. But have the same issue

**Comment by swarchen** [comment]
Try to update your fastlane to [2.66.1](https://github.com/fastlane/fastlane/releases/tag/2.66.1)?

**Comment by lazyjean** [comment]
I meet the save issue

/Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1005:in `send_app_submission': [!] undefined method `fetch' for #<String:0x007fa51a674cf8> (NoMethodError)
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/tunes/app_submission.rb:145:in `complete!'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/deliver/lib/deliver/submit_for_review.rb:27:in `submit!'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/deliver/lib/deliver/runner.rb:168:in `submit_for_review'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:26:in `block (2 levels) in parsing_binding'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/liuzhen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.80.0/bin/fastlane:20:in `<top (required)>'
	from /Users/liuzhen/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/liuzhen/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by szweier** [comment]
I just ran into this issue on 2.84.0

**Comment by joshdholtz** [comment]
Adding to my list to look into ^

**Comment by szweier** [comment]
@joshdholtz thanks for looking into it. FWIW I just reran my deploy and it worked fine.

**Comment by joshdholtz** [comment]
@szweier Waiiittt, it worked one now?! But didn't work a few hours ago?

**Comment by szweier** [comment]
Correct, I ran it once and it failed, decided to give it another shot since it had worked during last weeks deploy. When I did it all worked just fine. This was nothing more than a half an hour gap between attempts and I changed nothing.

**Comment by joshdholtz** [comment]
@szweier Uhhhh... do you remember what state your app was In in iTC when this error happened? Maybe the response back from Apple was different than we expect for whatever state it is 🤔

**Comment by szweier** [comment]
@joshdholtz on the first attempt there was a version that was available in the store and nothing more. When I ran deploy it made the build, uploaded it to itc, did its polling to find the build, after finding the build it attempted to update settings (this is all typical of every release by the way) and thats where it failed. At that point I read through this issue and decided to go back and run the attempt a second time, from the beginning. The difference, however, was that new version pending submission was on ITC at this point. It ran through the same flow, build, upload, poll, update settings. Only this time it went through without fail.

**Comment by ricperrott** [comment]
Just wanted to chime in and say that I have just run into this exact error as well when attempting to use deliver to submit an existing build for review
