### ISSUE TITLE
fastlane pilot export fails.

### ISSUE THREAD

**Issue by runloop** [fastlane/fastlane#10971]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running the latest fastlane update I now get an error when running the following command. This has been working perfectly for a long time:

`fastlane pilot export -a com.my.app_id -c ~/Documents/export.csv`

	Looking for related GitHub issues on fastlane/fastlane...

	Found no similar issues. To create a new issue, please visit:
	https://github.com/fastlane/fastlane/issues/new
	Run `fastlane env` to append the fastlane environment to your issue
	/Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/spaceship/lib/spaceship/test_flight/tester.rb:70:in `pretty_install_date': [!] undefined local variable or method `latest_installed_date' for #<Spaceship::TestFlight::Tester:0x007f95f6b24f88> (NameError)
	Did you mean?  latest_install_date
	               latest_install_date=
	               latest_install_info
	Did you mean?  latest_install_date
	               latest_install_date=
	               latest_install_info
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/tester_exporter.rb:30:in `block (2 levels) in export_testers'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/tester_exporter.rb:26:in `each'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/tester_exporter.rb:26:in `block in export_testers'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/csv.rb:1299:in `open'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/tester_exporter.rb:23:in `export_testers'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/commands_generator.rb:142:in `block (2 levels) in run'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/commands_generator.rb:160:in `run'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/pilot/lib/pilot/commands_generator.rb:12:in `start'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.0/bin/fastlane:20:in `<top (required)>'
		from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.4       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| openssl                   | 2.0.2        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>


*generated on:* **2017-11-21**
</details>


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.4       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| openssl                   | 2.0.2        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-11-21**
</details>

**Comment by mpirri** [comment]
Thanks for the report, @runloop - Apple made a bunch of changes to TestFlight recently and we've been working to get everything up and running again. We will revisit `pilot export` and see what is going on here.

Thanks so much for the report!  🚀

**Comment by taquitos** [comment]
Sorry about that, https://github.com/fastlane/fastlane/pull/10974

**Comment by runloop** [comment]
Updated to fastlane 2.66.1 and now get the following error:

	Found no similar issues. To create a new issue, please visit:
	https://github.com/fastlane/fastlane/issues/new
	Run `fastlane env` to append the fastlane environment to your issue
	/Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/spaceship/lib/spaceship/test_flight/tester.rb:72:in `pretty_install_date': [!] undefined method `/' for "1440087732446":String (NoMethodError)
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/tester_exporter.rb:30:in `block (2 levels) in export_testers'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/tester_exporter.rb:26:in `each'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/tester_exporter.rb:26:in `block in export_testers'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/csv.rb:1299:in `open'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/tester_exporter.rb:23:in `export_testers'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/commands_generator.rb:142:in `block (2 levels) in run'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/commands_generator.rb:160:in `run'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/pilot/lib/pilot/commands_generator.rb:12:in `start'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
		from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/bin/fastlane:20:in `<top (required)>'
		from /usr/local/bin/fastlane:22:in `load'
		from /usr/local/bin/fastlane:22:in `<main>'

**Comment by taquitos** [comment]
Ahh, I see what I missed. Turns out I didn't have a tester who had installed the app on my test account.
