### ISSUE TITLE
Fastlane SIGH ArgumentError: [!] wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by egr-ext** [fastlane/fastlane#10970]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After upgrading from Fastlane 2.53.1 to 2.66.0, I have an error with SIGH command : 
bundler: failed to load command: fastlane (/ xxxxx /label/macosx-4/.gem/ruby/2.1.0/bin/fastlane)
ArgumentError: [!] wrong number of arguments (1 for 0)

It is 4 hours I am trying anything possible ...

##### Complete output when running fastlane, including the stack trace and command used

Due to confidentially issue, I can not output the full trace

### Environment

| Key                         | Value                                                                                          |
| --------------------------- | ---------------------------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                                        |
| Ruby                        | 2.1.0                                                                                          |
| Bundler?                    | true                                                                                           |
| Git                         | git version 2.13.5 (Apple Git-94)                                                              |
| Installation Source         | xxxx /macosx-4/.gem/ruby/2.1.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G1111)                                                                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.1.0/lib                                                                    |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                                                                    |
| Is contained                | false                                                                                          |
| Is homebrew                 | false                                                                                          |
| Is installed via Fabric.app | false                                                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                    |
| Xcode Version               | 9.0.1                                                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.0  | ✅ Up-To-Date  |
| gym      | 2.0.0   | ✅ Up-To-Date  |
| sigh     | 2.0.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.16.0       |
| CFPropertyList            | 2.3.5        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| cocoapods                 | 1.1.1        |
| dotenv                    | 2.2.1        |
| osx_keychain              | 1.0.1        |
| cocoapods-keys            | 1.7.0        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.2        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.4.3        |
</details>

**Comment by milch** [comment]
@egr-ext Sorry that you're having troubles getting fastlane running. Can you share what command you used and which parameters?

**Comment by egr-ext** [comment]
I execute:
$ fastlane sigh

I also used by setting bundleId and so on.
$ fastlane sigh -a com.xxxx.xxxx -u xx@xx.xx etc....

My last investigation shows that a fresh install of Fastlane (without Rbenv nor gem) gives a SIGH version of 2.66.0 so I investigate in this direction.

**Comment by egr-ext** [comment]
Issue found, my sigh version was locked to an old version
