### ISSUE TITLE
Operation not supported on socket @ rb_ioctl

### ISSUE THREAD

**Issue by lgauthier** [fastlane/fastlane#10983]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm running into an issue only when running fastlane on our CI server. I've traced the issue back to an update to tty-screen #10820 , so let me know if you think I should post an issue there instead. It seems like the issue stems from the fact that there is no terminal window when running via our CI. I can log in on that same machine and run fastlane from the GUI terminal without any issue. This issue is only present in fastlane 2.66.0 which includes the version bump for tty-screen.

##### Complete output when running fastlane, including the stack trace and command used

```
bundler: failed to load command: fastlane (/Users/Shared/Jenkins/.rbenv/versions/2.4.2/bin/fastlane)
Errno::EOPNOTSUPP: [31m[!] Operation not supported on socket @ rb_ioctl - <STDERR>[0m
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.2/lib/tty/screen.rb:170:in `ioctl'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.2/lib/tty/screen.rb:170:in `ioctl?'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.2/lib/tty/screen.rb:162:in `size_from_ioctl'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.2/lib/tty/screen.rb:42:in `size'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.2/lib/tty/screen.rb:54:in `width'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:80:in `header'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/actions_helper.rb:49:in `execute_action'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:1:in `parsing_binding'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:54:in `eval'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.66.1/bin/fastlane:20:in `<top (required)>'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/bin/fastlane:23:in `load'
  /Users/Shared/Jenkins/.rbenv/versions/2.4.2/bin/fastlane:23:in `<top (required)>'
Bash failed with error: /bin/bash failed with return code: 1
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2m  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '1.105.3'

default_platform :ios

platform :ios do
  before_all do |lane, options|
    
    if lane != :increment_project_build_number
      clear_derived_data
      cocoapods
    end
  end
  
  desc 'Runs tests and creates a slather code coverage report.'
  lane :test do
    scan
    slather(scheme: 'MyApp', proj: 'MyApp.xcodeproj', workspace: 'MyApp.xcworkspace', html: true, use_bundle_exec: true)
    slather(scheme: 'MyApp', proj: 'MyApp.xcodeproj', workspace: 'MyApp.xcworkspace', cobertura_xml: true, use_bundle_exec: true)
  end
  
  desc 'Runs tests, creates a slather code coverage report, and deploys to TestFlight as long as "[skip_deploy_beta]" is not found in the commit message.'
  lane :test_and_deploy_beta do
    test
    integration_tests
    deploy_beta
  end
  
  desc 'Increments the build number to one greater than the current highest build number found in TestFlight.'
  lane :increment_project_build_number do
    increment_build_number(build_number: latest_testflight_build_number(live: false) + 1)
  end
  
  desc 'Submit a beta to TestFlight. If "[skip_deploy_beta]" is found in the latest commit message, then this lane does nothing.'
  lane :deploy_beta do
    if Actions.last_git_commit_message.include? '[skip_deploy_beta]'
      puts 'Skipping deployment since "[skip_deploy_beta]" was found in the last commit message.'
    else
      increment_project_build_number
      add_git_tag
      gym(scheme: 'MyApp', workspace: 'MyApp.xcworkspace', configuration: 'Release App Store')
      pilot(distribute_external: false, skip_waiting_for_build_processing: true)
    end
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier 'com.team.MyApp'
apple_id 'user@MyApp.com'
team_id 'XXXXXXXX'

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.0       |
| CFPropertyList            | 2.3.5        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.2        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.4.3        |
</details>

*generated on:* **2017-11-21**
</details>

**Comment by mpirri** [comment]
@piotrmurach - calling upon your `tty-screen` expertise. Do you think this is an issue in `tty-screen` or related to how _fastlane_ is using it?  Thanks!  🚀

**Comment by piotrmurach** [comment]
@mpirri This is defo issue with `tty-screen` or more specifically `ioctl` call that its trying to make. It's strange since it is a standard in many Unix like systems but then again as @lgauthier has described this may be due to the fact that the fastlane command is executed as non-login & non-interactive shell which may be a very stripped down version of terminal without access to any common Unix functions.

In my experience, getting terminal size is super hard on CI environments as they provide virtually no terminal info in which case quite often the detection falls back to default terminal size set by `tty-screen`. 

I will take a look and see what I can do to prevent this issue and release asap.

@lgauthier If you have time to repost on `tty-screen` issue tracker that would be sweet but don't worry if you can't.

**Comment by marekchen** [comment]
I have meet the same error.
Please fix it.
Thank you all very much.

**Comment by piotrmurach** [comment]
@lgauthier @mpirri I've released `v0.6.3` that should fix this issue. Could you please try to run fastlane with the latest `tty-screen`?

**Comment by ajfigueroa** [comment]
I've experienced the same issue and it looks like updating `tty-screen` did the trick.
Thanks @piotrmurach

**Comment by piotrmurach** [comment]
@lgauthier @mpirri I think the issue is resolved and can be closed?

**Comment by lgauthier** [comment]
@piotrmurach Yes, I can confirm that this is fixed. Thanks!

I also went ahead and reported the issue in tty-screen as well so it's documented there: piotrmurach/tty-screen#5
