### ISSUE TITLE
fastlane pilot list doesn't return all testers

### ISSUE THREAD

**Issue by thomasjoulin** [fastlane/fastlane#10990]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running

```
fastlane pilot list -a my.app.id -u my@username.com
```

I get 80 testers returned, when I have around 10,000 testers. `fastlane pilot export` has the same issue

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

// redacted, let me know if it's relevant

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                   | Version | Update-Status |
| ---------------------------------------- | ------- | ------------- |
| fastlane-plugin-clean_testflight_testers | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                      | Version      |
| ---------------------------------------- | ------------ |
| did_you_mean                             | 1.1.2        |
| executable-hooks                         | 1.3.2        |
| bundler-unload                           | 1.0.2        |
| rubygems-bundler                         | 1.4.4        |
| bundler                                  | 1.15.3       |
| io-console                               | 0.4.6        |
| CFPropertyList                           | 2.3.5        |
| i18n                                     | 0.8.6        |
| minitest                                 | 5.10.3       |
| thread_safe                              | 0.3.6        |
| tzinfo                                   | 1.2.3        |
| activesupport                            | 4.2.9        |
| public_suffix                            | 2.0.5        |
| addressable                              | 2.5.2        |
| babosa                                   | 1.0.2        |
| claide                                   | 1.0.2        |
| fuzzy_match                              | 2.0.4        |
| nap                                      | 1.1.0        |
| cocoapods-core                           | 1.3.1        |
| cocoapods-deintegrate                    | 1.0.1        |
| cocoapods-downloader                     | 1.1.3        |
| cocoapods-plugins                        | 1.0.0        |
| cocoapods-search                         | 1.0.0        |
| cocoapods-stats                          | 1.0.0        |
| netrc                                    | 0.7.8        |
| cocoapods-trunk                          | 1.2.0        |
| cocoapods-try                            | 1.1.0        |
| colored2                                 | 3.1.2        |
| escape                                   | 0.0.4        |
| fourflusher                              | 2.0.1        |
| gh_inspector                             | 1.0.3        |
| molinillo                                | 0.5.7        |
| ruby-macho                               | 1.1.0        |
| nanaimo                                  | 0.2.3        |
| xcodeproj                                | 1.5.3        |
| cocoapods                                | 1.3.1        |
| colored                                  | 1.2          |
| highline                                 | 1.7.8        |
| commander                                | 4.4.3        |
| commander-fastlane                       | 4.4.5        |
| mime-types-data                          | 3.2016.0521  |
| mime-types                               | 3.1          |
| rest-client                              | 1.6.7        |
| crowdin-api                              | 0.4.0        |
| gli                                      | 2.16.1       |
| rubyzip                                  | 1.2.1        |
| crowdin-cli                              | 0.5.5        |
| declarative                              | 0.0.10       |
| declarative-option                       | 0.1.0        |
| unf_ext                                  | 0.0.7.4      |
| unf                                      | 0.1.4        |
| domain_name                              | 0.5.20170404 |
| dotenv                                   | 2.2.1        |
| excon                                    | 0.59.0       |
| multipart-post                           | 2.0.0        |
| faraday                                  | 0.13.1       |
| http-cookie                              | 1.0.3        |
| faraday-cookie_jar                       | 0.0.6        |
| faraday_middleware                       | 0.12.2       |
| fastimage                                | 2.1.0        |
| jwt                                      | 2.1.0        |
| little-plugger                           | 1.1.4        |
| multi_json                               | 1.12.2       |
| logging                                  | 2.2.2        |
| memoist                                  | 0.16.0       |
| os                                       | 0.9.6        |
| signet                                   | 0.8.1        |
| googleauth                               | 0.6.2        |
| httpclient                               | 2.8.3        |
| uber                                     | 0.1.0        |
| representable                            | 3.0.4        |
| retriable                                | 3.1.1        |
| google-api-client                        | 0.13.6       |
| json                                     | 2.1.0        |
| mini_magick                              | 4.5.1        |
| multi_xml                                | 0.6.0        |
| plist                                    | 3.3.0        |
| security                                 | 0.1.3        |
| slack-notifier                           | 1.5.1        |
| terminal-notifier                        | 1.8.0        |
| unicode-display_width                    | 1.3.0        |
| terminal-table                           | 1.8.0        |
| tty-screen                               | 0.6.2        |
| word_wrap                                | 1.0.0        |
| rouge                                    | 2.0.7        |
| xcpretty                                 | 0.2.8        |
| xcpretty-travis-formatter                | 1.0.0        |
| fastlane-plugin-clean_testflight_testers | 0.1.1        |
| houston                                  | 2.2.4        |
| xcov                                     | 1.3.0        |
</details>

*generated on:* **2017-11-22**
</details>

**Comment by wuftymerguftyguff** [comment]
Very similar issue here.

I am getting 71 out of a list of about 200 testers.

**Comment by milch** [comment]
Hi @thomasjoulin & @wuftymerguftyguff, sorry you're running into issues with this! Apple recently changed the API out from under us and it seems we didn't quite get the new implementation right. I've just sent out a PR @ #11013 that should hopefully fix your issues!

**Comment by runloop** [comment]
What's happening with this? My entire beta signup system has been broken since the recent iTC changes.

**Comment by janpio** [comment]
@runloop We appreciate any help, so if you could apply this to your fastlane locally (workflow here: https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) and test if it fixes your problem and comment so in the PR this would really help us. Thanks!

**Comment by milch** [comment]
Hi all, I just merged my proposed fix. It is not released yet, although my understanding is the core team is working on a release soon. 

Let me know if you still experience issues with this after the fix is released
