### ISSUE TITLE
pem certificate for Java servers

### ISSUE THREAD

**Issue by imodeveloper** [fastlane/fastlane#10995]
### Issue Description

I am using [pem](https://docs.fastlane.tools/actions/pem/#pem) to generate certificates for push notifications, and all is fine when I'm testing certificates with [Knuff](https://github.com/KnuffApp/Knuff),  [Pusher](https://github.com/noodlewerk/NWPusher) or [pushtry](https://pushtry.com) but when I we put it on Java server with [java-apns](https://github.com/notnoop/java-apns) we can't send notifications. 

I found this [article](http://findnerd.com/list/view/Creating--p12-for-apns-with-server-side-in-Java/4469/)  where is described the issue

> Generally in iOS apps server side is coded in PHP and to integrate APNS we can create .pem file by following this [RayWenderlich](http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1) tutorial.
> But we might face difficulty in receiving remote notification on device when server side coding is done in Java. This is because the private key p12 file doesn't work with Java. We should use following OpenSSL commands to generate another p12 file from the private key and the .cer download from Apple. This new file is actually the correct one to be used with Java.
> 
> aps_dev.cer -> downloaded from Apple developer
> private_key.p12 -> private key
> 
> openssl x509 -in aps_dev.cer -inform DER -out aps_dev.pem -outform PEM
> openssl pkcs12 -nocerts -in private_key.p12 -out private_key.pem
> openssl pkcs12 -export -inkey private_key.pem -in aps_dev.pem -out aps_dev_java.p12
> 
> Finally we should use aps_dev_java.p12 at server end for sending notifications.

So, maybe will be good Idea to add this possibility direct to [pem](https://docs.fastlane.tools/actions/pem/#pem) action, to be able to export for Java servers.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.19.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-11-22**
</details>

**Comment by janpio** [comment]
That sounds like a pretty good candidate for a fastlane plugin! 

That way the actual logic could be implemented and tested without any commitment needed from the core contributors, and if it turns out to be super popular and used very often it can still be integrated to the core `pem` action.

You can read more about creating a plugin here: https://docs.fastlane.tools/plugins/create-plugin/
