### ISSUE TITLE
reinstall_app not working as intended

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#11008]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

While running Automation App and it's corresponding test app is created and test app is being tested. reinstall_app just reinstalls the app not the test app. So there is no use in reinstalling the app.

So using snapshot and setting the reinstall_app to true, just reinstalls the app but the Test App is not reinstalled. This

**Comment by milch** [comment]
Hi @tringManoj! What do you mean by test app? Are you talking about the UI test bundle? As far as I know the UI test bundle should not be installed on your device anyway, and should be run directly from your mac. 

In any case, you should be able to adjust which app gets uninstalled by `snapshot` by using the `app_identifier` parameter. See the description here: 

```
app_identifier: The bundle identifier of the app to uninstall (only needed when enabling reinstall_app)
```

**Comment by tringManoj** [comment]
Hi @milch. Thanks for trying to help me. 
When we run the UIAutomation from xCode. App appropriate to the target is created, also a test app is created along side.  reinstall_app just reinstalls the app but not the test app. Problem here is userdefaults are still active because the test app is never reinstalled. This messes up the work.

**Comment by milch** [comment]
In that case, have you tried setting the `app_identifier` to the bundle identifier of this test app? I believe during normal operation there should only be one app and not two, so it is likely that the wrong one is just automatically detected here by fastlane

**Comment by tringManoj** [comment]
That seems to be because of the bundle identifier. Thanks for your help @milch
