### ISSUE TITLE
download_dsyms unable to find the latest build and symbol files

### ISSUE THREAD

**Issue by sharat** [fastlane/fastlane#11006]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

- Download_dsyms can't find the latest version of the app on iTunes Connect. 
- Explicitly passing version via environment variables `DOWNLOAD_DSYMS_VERSION` and `DOWNLOAD_DSYMS_BUILD_NUMBER` did not help to resolve the issue.

### Lane Details
```ruby
desc "Refresh Dsyms"
  lane :refresh_dsyms do
    download_dsyms(app_identifier: ENV["APP_ID_PROD"])                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end
```

### Output
```
$ bundle exec fastlane refresh_dsyms
[11:01:13]: -------------------------------------------------
[11:01:13]: --- Step: Verifying required fastlane version ---
[11:01:13]: -------------------------------------------------
[11:01:13]: Your fastlane version 2.66.2 matches the minimum requirement of 2.66.0  ✅
[11:01:13]: ------------------------------
[11:01:13]: --- Step: default_platform ---
[11:01:13]: ------------------------------
[11:01:13]: Driving the lane 'ios refresh_dsyms' 🚀
[11:01:13]: ----------------------------
[11:01:13]: --- Step: download_dsyms ---
[11:01:13]: ----------------------------
[11:01:13]: Login to iTunes Connect (my@email.com)
[11:01:18]: Login successful
[11:01:19]: Looking for dSYM files for com.mycompany.app v1.1 (1)
[11:01:27]: No dSYM URL for 1 (1.1)
[11:01:27]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet
[11:01:27]: -------------------------------------------
[11:01:27]: --- Step: upload_symbols_to_crashlytics ---
[11:01:27]: -------------------------------------------
[11:01:27]: Using 4 threads for Crashlytics dSYM upload 🏎
[11:01:27]: Extracting '/Users/user/github/projects/my-project/com.mycompany.app-1.0-3.dSYM.zip'...
[11:01:27]: $ unzip -qo /Users/user/github/projects/my-project/com.mycompany.app-1.0-3.dSYM.zip

[11:01:47]: Successfully uploaded dSYM files to Crashlytics 💯
[11:01:47]: -----------------------------------
[11:01:47]: --- Step: clean_build_artifacts ---
[11:01:47]: -----------------------------------
[11:01:47]: Cleaned up build artifacts 🐙

```

### Relevant Environment Variables
I have passed the build and version number explicitly as the fastlane unable to find the dSYMS for latest build.

```
CRASHLYTICS_API_TOKEN=crashlytics_token
FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_DSYM_WORKER_THREADS=4
DOWNLOAD_DSYMS_VERSION=1.1
DOWNLOAD_DSYMS_BUILD_NUMBER=1
```

</details>

![screen shot 2017-11-23 at 11 04 22 am](https://user-images.githubusercontent.com/405971/33160167-f4fdf1ea-d03f-11e7-93c5-f044384a2d46.png)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.6        |
</details>

*generated on:* **2017-11-23**
</details>

**Comment by teanet** [comment]
It is working on version 2.64.0, but on 2.66.0 it's not =(

**Comment by igor-makarov** [comment]
I think what broke it is the required platform flag that was introduced to Spaceship recently.

**Comment by jced-artem** [comment]
I also have this problem on 2.66.2.
Tried to provide platform but result the same.

**Comment by igor-makarov** [comment]
PR [#11030](https://github.com/fastlane/fastlane/pull/11030) fixes this.

**Comment by KrauseFx** [comment]
Thanks everyone, and sorry for the late response. Can you confirm that this works again with the most recent release?

**Comment by alphatroya** [comment]
Confirm, it works fine on 2.67.0
