### ISSUE TITLE
Clarification of differences between the two Spaceship APIs for creating apps 

### ISSUE THREAD

**Issue by fxfactorial** [fastlane/fastlane#11012]
Hi, 

This is probably me not understanding Apple's model well enough but what is the difference between 

```
Spaceship::Portal.app.create!
```

and 
```
Spaceship::Tunes::Application.create
```

Looking for something more substantial an explanation than 'one is iTunes connect and other is portal'. 

Thank you

**Comment by milch** [comment]
That's really the only difference. Apple has two websites online, https://itunesconnect.apple.com and https://developer.apple.com. On iTunes Connect, you manage the App Store side of things, metadata, screenshots and so on. On the Developer Portal you manage development things like signing certificates, provisioning profiles, etc. They are used for different things, and to interact with your app on that platform it has to exist there first.

**Comment by fxfactorial** [comment]
@milch got it! Thank you so much!
