### ISSUE TITLE
CodeSign fails in Jenkins/SSH while using Match

### ISSUE THREAD

**Issue by ngreeney** [fastlane/fastlane#11015]
I am running into an issue with xcode 9 and Jenkins running fastlane. The lane I am running looks like this: 

  lane :hockeyDev do
    setup_jenkins(
      force: true
    )
    cocoapods()
    match(
      force: true,
      git_branch: '--------',
      type: 'enterprise',
      team_id: '--------',
      app_identifier: ['--------', '--------.today', '--------.watchkitapp', '--------.watchkitapp.watchkitextension'],
      username: '--------'
    )
    gym(
      clean: true,
      workspace: "--------.xcworkspace",
      scheme: "--------",
      configuration: "-------- - Release",
      output_name: "--------.ipa"
    )
    hockey(...lots of stuff it never reaches...)
  end

This works when I run it locally or when I run it from screen share. From both SSH and Jenkins it gives me an error when reaching the CodeSign step of archiving. I also run export FASTLANE_PASSWORD="------" to get past entering passwords for Match at this point. This is the error I get:

** ARCHIVE FAILED **
The following build commands failed:
CodeSign derivedData/Build/Intermediates.noindex/ArchiveIntermediates/PV\ Dev/IntermediateBuildFilesPath/UninstalledProducts/watchos/PowerView\ -\ Watch\ Extension.appex
(1 failure)

### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

fastlane hockeyDev OUTPUT:
https://gist.github.com/ngreeney/c581dcca34f562df82f2cb78aa34e2b8

### Environment
Fastlane Env:
https://gist.github.com/ngreeney/b424d6ad673c59b3a104faf7a1c3db41

**Comment by ngreeney** [comment]
env and output are included in two gists

**Comment by ngreeney** [comment]
This seems to be due to not using the login.keychain when I ssh into the box where as Jenkins through fastlane is trying to use login.keychain. Trying to set a different keychain always give me an error saying it can't find the keychain though. 

Any thoughts anyone? 

I have tried to follow this issue but it has not helped: https://github.com/fastlane/fastlane/issues/5649

I am running High Sierra but the issue was happening on Sierra as well.

**Comment by arodus** [comment]
Not really a solution for your problem but I also had problems with codesigning and jenkins in the past. A few weeks ago I started using a temporary keychain (```create_keychain```) and everything is working like a charm since then.

**Comment by ngreeney** [comment]
I'll give that a shot. Thanks!

**Comment by ngreeney** [comment]
Unfortunately did not work but I'll keep digging.

**Comment by ohayon** [comment]
Hey @ngreeney, have you gotten a chance to take a look at [these docs](https://docs.fastlane.tools/best-practices/continuous-integration/#jenkins-integration)? They have some useful tips for Jenkins + fastlane. Let us know if that's helpful at all! 🚀

**Comment by ngreeney** [comment]
Yes I have. And the more I play with this, I think that is the problem. Going to try and remove the setup_jenkins action and see if I can get further. Or play around with the setup_jenkins options some more.

Basically my thinking is that setup_jenkins is trying to do a lot of default thinks like using the login.keychain and/or the Jenkins plugin for signing and I don't use either of those since I have a separate keychain and the plugin on Jenkins does not work with Match.

**Comment by Ruenzuo** [comment]
@ngreeney that is probably related to the keychain not being unlocked on SSH sessions and Jenkins non-interactive mode. Have you tried unlocking the keychain before?

```
security default-keychain -s '/Users/YOUR_USER/Library/Keychains/login.keychain'
security -v unlock-keychain -p ${KEYCHAIN_PASSWORD} '/Users/bldadmin/Library/Keychains/login.keychain'
```

You can use credentials binding on Jenkins to set `KEYCHAIN_PASSWORD` environment variable with your user's password.

**Comment by ngreeney** [comment]
I was able to resolve this by unlocking the keychain as @Ruenzuo  mentioned. I also went through fully wiping out my keychain and starting over as well though. In any case this is resolved. Thanks for the help.
