### ISSUE TITLE
Gym: No such file or directory: 'Kingfisher'

### ISSUE THREAD

**Issue by royberris** [fastlane/fastlane#11010]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Gym failed because it can't find Kingfisher. It does compile it in a previous stage in gym, and there is a folder inside the Pods folder called "Kingfisher". This is weird, because I just moved the fastlane files to another branch in my repository, checked if everything was OK but then this error shows up, this is not happening in the other branch

##### Complete output when running fastlane, including the stack trace and command used

▸ Building Pods/Kingfisher [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling Kingfisher-dummy.m
▸ Compiling Kingfisher_vers.c
▸ Compiling Kingfisher-dummy.m
▸ Compiling Kingfisher_vers.c
▸ Linking Kingfisher
▸ Linking Kingfisher
▸ Generating 'Kingfisher.framework.dSYM'
▸ Copying Kingfisher-umbrella.h
▸ Copying Kingfisher.h
▸ Touching Kingfisher.framework
// More things and then at the end:
▸ Compiling ModuleApp-iOS_vers.c
▸ Compiling ModuleApp-iOS_vers.c
▸ Linking ModuleApp-iOS

❌  clang: error: no such file or directory: 'Kingfisher'

▸ Linking ModuleApp-iOS

❌  clang: error: no such file or directory: 'Kingfisher'

** ARCHIVE FAILED **

The following build commands failed:
Ld /Users/user/Library/Developer/Xcode/DerivedData/ModuleApp-iOS-fhfgmzaawccjskfdrjcfzvwoprqk/Build/Intermediates.noindex/ArchiveIntermediates/ModuleApp-iOS/IntermediateBuildFilesPath/ModuleApp-iOS.build/Release-iphoneos/ModuleApp-iOS.build/Objects-normal/armv7/ModuleApp-iOS normal armv7
Ld /Users/user/Library/Developer/Xcode/DerivedData/ModuleApp-iOS-fhfgmzaawccjskfdrjcfzvwoprqk/Build/Intermediates.noindex/ArchiveIntermediates/ModuleApp-iOS/IntermediateBuildFilesPath/ModuleApp-iOS.build/Release-iphoneos/ModuleApp-iOS.build/Objects-normal/arm64/ModuleApp-iOS normal arm64
(2 failures)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.1"

default_platform :ios

platform :ios do

  lane :firstlane do |options|
    # gym part of the fastfile
    gym(
      scheme: "ModuleApp-iOS",
      workspace: "ModuleApp-iOS.xcworkspace",
      export_method: "app-store",
      clean: true,
      include_bitcode: true,
      output_name: "#{appname}.ipa"
    )

      end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.10.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.10       |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.3.1        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| concurrent-ruby           | 1.0.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| escape                    | 0.0.4        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-appicon   | 0.10.0       |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.9.1        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.3.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| rest-client               | 2.0.2        |
| retriable                 | 3.1.1        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.6.2        |
| tzinfo                    | 1.2.4        |
| uber                      | 0.1.0        |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.3.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-11-23**
</details>

**Comment by milch** [comment]
On that branch, can you do a regular build in Xcode?

**Comment by royberris** [comment]
@milch didn't try that, and it couldn't. I've fixed it, this had nothing to do with fastlane.

For people also having a similar problem: https://stackoverflow.com/questions/31264763/apple-mach-o-linker-error-no-such-file-or-directory-swifty-json
I had a -framework to many. So it looked like -framework -framework "Kingfisher"

**Comment by milch** [comment]
Alright, no problem. Glad you managed to fix it!
