### ISSUE TITLE
Pilot doesn't get all the testers from testflight because sort order is different

### ISSUE THREAD

**Issue by diegopeinador** [fastlane/fastlane#11011]
Initial call:
https://github.com/fastlane/fastlane/blob/38274ab1f76140c4910bf148c3c2a9d251134b8d/spaceship/lib/spaceship/test_flight/client.rb#L150

Each page:
https://github.com/fastlane/fastlane/blob/38274ab1f76140c4910bf148c3c2a9d251134b8d/spaceship/lib/spaceship/test_flight/client.rb#L158

If you want to do pagination you need to keep the same sort fields so you get new data in each call, you may get duplicated otherwise (and end the loop too soon).

**Comment by milch** [comment]
Hi @diegopeinador, thanks for your help and good catch! I'll submit a PR soon

**Comment by KrauseFx** [comment]
Thanks @milch ❤️
