### ISSUE TITLE
Fastlane match: creates a signing certificate for each Apple Id/Git branch combination

### ISSUE THREAD

**Issue by dh256** [fastlane/fastlane#11018]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane match creates a signing certificate for each combination of Apple Id/Git branch. As an Apple Id can only have two signing certificates, this restricts us to having two branches in the Git repo that holds certificates/provisioning profiles. 

Although, can get around this by creating additional Apple Ids (one per Git branch) is it possible for fastlane match to only create a signing certificate for each unique Apple Id rather than Apple Id/Branch combination. 

This would allow me to use a single Apple Id and create a separate branch in Git repo for each product/team.

**Comment by svanzoest** [comment]
The reason it does this is that each team_id/apple id combo has its own organization per branch. Why would you want a separate branch when the team_id/appleid combo is the same?

**Comment by dh256** [comment]
Hi svanzoest. A separate Git branch in the certificates repo for each (Xcode) project, perhaps? Not a deal breaker by any means, just wondering if it was an option to support both scenarios.

**Comment by svanzoest** [comment]
@dh256 I see. I do not think that is currently supported as it wouldn't know if the certificate already exists in read-only mode.

**Comment by joshdholtz** [comment]
@dh256 I believe @svanzoest latest response is correct so I'm going to close this issue for now 🙃
