### ISSUE TITLE
[Regression] Setting env var directly bypasses verify block

### ISSUE THREAD

**Issue by jesiegel1** [fastlane/fastlane#11017]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In our `Fastfile`, we define `ENV["GYM_OUTPUT_NAME"] = "my_build.ipa"` to globally set the output name for all of our calls to `gym`.  This value was added to our `Fastfile` about 9 months ago and worked fine when cutting builds. 

Then recently, while trying to cut a build using Xcode 9, I was running into code signing issues during the export step - after reading through existing issues and the changelog, I found the Xcode 9 changes and promptly updated fastlane (I was using an outdated version) - problem solved.

However, while the code signing error went away when I tried cutting a new build after the update, a new error appeared during our upload to hockey step - I kept hitting https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb#L179 because hockey was returning a `415: Unsupported Media Type`.  After some digging, I finally realized that our build was being exported with the name `my_build.ipa.ipa` and was surprised, since I had seen in the source that the `.ipa` extension was handled in order to prevent this very thing from happening when naming the build.

It seems like the proc handling the `GYM_OUTPUT_NAME ` validation (which removes the `.ipa` extension if present - https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/options.rb#L65) was being bypassed when setting `ENV["GYM_OUTPUT_NAME"]` directly.  Instead of setting the env var, I explicitly provided a value for `output_name` in our call to `gym`, and uploading the build to hockey succeeded without error.

I'm presuming this is a regression because setting `GYM_OUTPUT_NAME` directly has been fine for us in the past.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.66.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| faraday                   | 0.12.1       |
| coderay                   | 1.1.1        |
| slop                      | 3.6.0        |
| method_source             | 0.8.2        |
| pry                       | 0.10.4       |
</details>

*generated on:* **2017-11-23**
</details>

**Comment by KrauseFx** [comment]
There was change with this recently, can you check if it works now?

**Comment by jesiegel1** [comment]
@KrauseFx sorry, "close issue" and "comment" buttons are too close to each other on mobile - i'll give it a go tomorrow and verify if the issue has been resolved

**Comment by joshdholtz** [comment]
@jesiegel1 Were you able to see if this was resolved?
