### ISSUE TITLE
[question] Upload build notes/metadata

### ISSUE THREAD

**Issue by danielphillips** [fastlane/fastlane#11025]
Hello, 

My current CI/CD setup is that I'm distributing a build to iTC on every integration with my develop branch. With the team size I have we have approx. 15 or so integrations per day.
What's nice is testflight is continuously receiving updates to our app and QA are happy to have the latest build available on all test devices.
Sometimes when a regression occurs, it can be tricky to pin down which integration introduced the problem.

Does fastlane/the iTunes connect APIs support uploading any metadata which can be used to for instance insert the git sha of the HEAD of the branch which was used to create the build. I'm thinking this would show up in testflight and be a great help.

Not sure if this kind of API exists.
Thanks.

**Comment by danielphillips** [comment]
Not applicable thank you Mr fastlane-bot.

**Comment by ricperrott** [comment]
Does your app have an "About?" area where the version number is shown? What we do for our app is make that tappable and swap out the version number with the git sha when tapped. This way testers can always relay which build they are on.

**Comment by joshdholtz** [comment]
@danielphillips There isn't anything built in for this but using something like @ricperrott's suggestion is what I would recommend as well 😊
