### ISSUE TITLE
Error while using import_certificate

### ISSUE THREAD

**Issue by flexaddicted** [fastlane/fastlane#1102]
Hello! I'm using fastlane in order to import a certificate into the keychain.

I am using the following actions (ENV are created in a .env file)

    def import_certificates
        create_keychain(
            name: ENV["KEYCHAIN_NAME"],
            default_keychain: true,
            unlock: true,
            password: ENV["KEYCHAIN_PASSWORD"]
        )
        import_certificate(
            certificate_path: ENV['CERTIFICATE_P12'],
            certificate_password: ENV['CERT_PASSWORD'],
            keychain_name: ENV['KEYCHAIN_NAME']
        )
        import_certificate(
            certificate_path: ENV['CERTIFICATE_CER'],
            keychain_name: ENV['KEYCHAIN_NAME']
        )
    end

I always end up with the following error.

> [16:01:33]: ------------------------------
> [16:01:33]: --- Step: default_platform ---
> [16:01:33]: ------------------------------
> [16:01:33]: Driving the lane 'ios beta' 🚀
> [16:01:33]: -----------------------------
> [16:01:33]: --- Step: create_keychain ---
> [16:01:33]: -----------------------------
> [16:01:33]: --------------------
> [16:01:33]: --- Step: notify ---
> [16:01:33]: --------------------
> [16:01:33]: It's recommended to use the new 'notification' method instead of 'notify'
> [16:01:34]: Variable Dump:
> [16:01:34]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios canary"}
> [16:01:34]: Exit status of command 'security import certificates/Certificates.p12 -k ~/Library/Keychains/circleci.keychain -P CertificatePassword -T /usr/bin/codesign -T /usr/bin/security' was 1 instead of 0.

Using the command within the terminal, it works correctly? Any clue?

Thanks

**Comment by KrauseFx** [comment]
What was the issue?

**Comment by flexaddicted** [comment]
@KrauseFx I did not specify the password for the keychain. On CircleCI I created a new keychain and now it works. Maybe there something missing on CircleCI documentation.

Thanks.
