### ISSUE TITLE
Ability to update fastlane to a specific version rather than latest

### ISSUE THREAD

**Issue by dh256** [fastlane/fastlane#11031]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In some (corporate) environments only specific versions of software are approved for use. This causes issues with software that utilises auto update features (e.g. _update-fastlane_).

It would be very useful to have an additional parameter on the _fastlane update-fastlane_ command that allowed you to stipulate a specific version to update to e.g:

`fastlane update-fastlane 2.64.1 `

would update current version of fastlane to 2.64.1 regardless of whether this was the most recent version.

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by sharat** [comment]
Have you tried [setting up Fastlane with Bundler](https://docs.fastlane.tools/getting-started/ios/setup/) with [version constraints ](http://guides.rubygems.org/patterns/#pessimistic-version-constraint)?

**Comment by joshdholtz** [comment]
Closing this since @sharat comment above is the preferred way of doing this 😊
