### ISSUE TITLE
`xcversion`: Are these comments swapped?

### ISSUE THREAD

**Issue by coltrey** [fastlane/fastlane#11039]
Are the comments on these two lines swapped?

https://github.com/fastlane/fastlane/blob/3dc3fd85ee91377812437df3bae03d130697f913/fastlane/lib/fastlane/actions/xcversion.rb#L45
https://github.com/fastlane/fastlane/blob/3dc3fd85ee91377812437df3bae03d130697f913/fastlane/lib/fastlane/actions/xcversion.rb#L46

**Comment by janpio** [comment]
From the param description on https://docs.fastlane.tools/actions/xcversion/:

> The version of Xcode to select specified as a Gem::Version requirement string (e.g. '~> 7.1.0')

Googling for "Gem::Version" brings me to http://ruby-doc.org/stdlib-2.0.0/libdoc/rubygems/rdoc/Gem/Version.html

> `gem 'stack', '~> 0.1'`
> [...] was introduced in version 0.1.0, so that version or anything later is fine, as long as the version stays below version 1.0 where incompatibilities are introduced.

From which I conclude:

- `xcversion(version: "8.1")` = Exactly 8.1 (or 8.1.0)
- `xcversion(version: "~> 8.1.0")` = Anything that doesn't make `.1` change to `.2`, so `8.1.x`

So my guess would be: No, comments are correct. 
But documentation could be improved a bit to make this more obvious how specifying versions work.

**Comment by coltrey** [comment]
Got it.  Thank you.
