### ISSUE TITLE
Cannot find any documentation on fastlane_require

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/fastlane#11042]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I cannot find any documentation on fastlane_require. Is there any?

**Comment by janpio** [comment]
This is all I could find:
https://github.com/fastlane/fastlane/blob/4c5ddd5b320ae30bedeeca0a0c2b29bda6d1f5df/fastlane/lib/fastlane/fast_file.rb#L30

Also of course the actual code:
https://github.com/fastlane/fastlane/blob/60bac7e4a2a6c1e19d1cd20eb83201e7d0cb9e48/fastlane/lib/fastlane/fastlane_require.rb

What exactly are you looking for?

**Comment by GoodMirek** [comment]
@janpio, thanks for your response. I knew about the function `fastlane_require` from reading others' Fastfile's, but I am wondering how a new user can find this function (action).
Is it considered action or not?
If there is no doc, is it acceptable to add it to Advanced.md? Or elsewhere?
If yes, I will be happy to submit a PR.

**Comment by janpio** [comment]
Good question - I don't know if this _should_ be used or not, sorry.

**Comment by joshdholtz** [comment]
I found it by the UI spitting it out when it was first introduced 😊 But I do like the idea of putting this in the "Advanced" section of docs. I will create a PR over there and reference this issue 💪 Thanks for bringing this up!

**Comment by janpio** [comment]
For future readers of this: 
https://docs.fastlane.tools/advanced/Fastfile/#using-fastlane_require
