### ISSUE TITLE
`fastlane deliver download_metadata` crash: NoMethodError: [!] undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by julestburt** [fastlane/fastlane#11046]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Previously had no issues running `bundle exec fastlane deliver download_metadata`, but recently this has started to crash - if the version # in deliver file doesn't match the iTunes release #.

Our team builds out the iTunes page 1.0 with description etc...or alternatively updates some meta data on iTunes. Then we download any existing metadata during build process - before adding other meta such as release notes, copyright etc. 

Now this fails as we don't specify which version on iTunes to download - I assume deliver used to grab the latest if version number didn't match?

Any help would be appreciated...

NB. I am using bundle exec fastlane deliver download_metadata in a bash script...in and around setting up the app for building / submitting.

```
[16:22:56]: Successfully loaded '/Users/jules/Desktop/xxxx/OurProject/our-master/fastlane/Deliverfile' 📄

+------------------------+-------------------------------------------------------------------------------------------------------------------+
|                                               Detected Values from './fastlane/Deliverfile'                                                |
+------------------------+-------------------------------------------------------------------------------------------------------------------+
| overwrite_screenshots  | false                                                                                                             |
| skip_screenshots       | true                                                                                                              |
| skip_metadata          | false                                                                                                             |
| force                  | true                                                                                                              |
| app_identifier         | net.xxx.yyy                                                                                       |
| app_version            | 3.6.1                                                                                                             |
| username               | jules@                                                                                              |
| app_review_information | {:first_name=>"Jules", :last_name=>"xxx", :phone_number=>"xxx",                                       |
|                        | :email_address=>"jules@yyyy", :demo_user=>"xxxx", :demo_password=>"xxxx"} |
| app_rating_config_path | ./fastlane/Rating.json                                                                                            |
| automatic_release      | false                                                                                                             |
| submit_for_review      | true                                                                                                              |
| price_tier             | 0                                                                                                                 |
| submission_information | {:content_rights_contains_third_party_content=>false, :export_compliance_uses_encryption=>false}                  |
+------------------------+-------------------------------------------------------------------------------------------------------------------+

[16:22:56]: Login to iTunes Connect (jules@xxx)
[16:23:00]: Login successful

+--------------------------------------------------------------------+-----------------------------+
|                                      deliver 2.67.0 Summary                                      |
+--------------------------------------------------------------------+-----------------------------+
| screenshots_path                                                   | ./fastlane/screenshots      |
| metadata_path                                                      | ./fastlane/metadata         |
| username                                                           | jules@xxx         |
| app_identifier                                                     | net.xxx  |
| edit_live                                                          | false                       |
| platform                                                           | ios                         |
| skip_binary_upload                                                 | false                       |
| skip_screenshots                                                   | true                        |
| app_version                                                        | 3.6.1                       |
| skip_metadata                                                      | false                       |
| skip_app_version_update                                            | false                       |
| force                                                              | true                        |
| submit_for_review                                                  | true                        |
| automatic_release                                                  | false                       |
| price_tier                                                         | 0                           |
| app_rating_config_path                                             | ./fastlane/Rating.json      |
| submission_information.content_rights_contains_third_party_content | false                       |
| submission_information.export_compliance_uses_encryption           | false                       |
| dev_portal_team_id                                                 | xxxxxxxxxx                  |
| overwrite_screenshots                                              | false                       |
| run_precheck_before_submit                                         | true                        |
| precheck_default_rule_level                                        | warn                        |
| app_review_information.first_name                                  | Jules                       |
| app_review_information.last_name                                   | yyyy                        |
| app_review_information.phone_number                                | yyyy             |
| app_review_information.email_address                               | jules@yyy    |
| app_review_information.demo_user                                   | yyyy|
| app_review_information.demo_password                               | ********                    |
| ignore_language_directory_validation                               | false                       |
| precheck_include_in_app_purchases                                  | true                        |
+--------------------------------------------------------------------+-----------------------------+


Looking for related GitHub issues on fastlane/fastlane...

➡️  Type Checking error: got 'Fixnum' for attribute 'fileEncoding' and undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11016 [open] 1 💬
    5 days ago

➡️  fastlane deliver download_metadata crash: bundler: failed to load command: fastlane (/usr/local/bin/fastlane) NoMethodError: [!] undefined method `version' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11046 [open] 0 💬
    a minute ago

➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
    https://github.com/fastlane/fastlane/issues/10447 [open] 11 💬
    5 days ago

and 256 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60version%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `version' for nil:NilClass
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/deliver/lib/deliver/commands_generator.rb:165:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/deliver/lib/deliver/commands_generator.rb:176:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/cli_tools_distributor.rb:67:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

##### Complete output when running fastlane, including the stack trace and command used

<!-- Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.1                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.13.6 (Apple Git-96)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.1 (17B48)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
end

desc "Submit a new Beta Build to Apple TestFlight"
lane :beta do

  disable_automatic_code_signing(path: "Our App.xcodeproj")

    match(type: "appstore",
        git_full_name: '',
        git_user_email: 'jules@')

    udid = sigh(output_path: "./provisions")
    ENV["PROJECT_UDID"] = udid


    # setting SWIFT COMPILE FLAGS
    app_ident = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    if "#{app_ident}" == "net.xxx.yyy"
      xcatargs = "-DCATALUFA"
    end


    puts "Building with Our Pro scheme"
    gym(scheme: "OurPro", export_method: "app-store",
    clean: true,
    xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{udid}' OTHER_SWIFT_FLAGS='#{xcatargs}'")

    # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)


  desc "This is to build the develop branch with Catalufa Profile"
  lane :develop do
    disable_automatic_code_signing(path: "Our Pro App.xcodeproj")
    project = Xcodeproj::Project.open('../Our Pro App.xcodeproj')
    project.targets.each do |target|
      target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_STYLE'] = "Manual"
    end
  end
  project.save

    match(type: "appstore",
        git_full_name: 'xxxx',
        git_user_email: 'jules@')
   
udid = ENV["PROJECT_UDID"]
udid = sigh(output_path: "./provisions")
ENV["PROJECT_UDID"] = udid

#increment_build_number
    version = ENV["VERSION_NUMBER"]
    venueid = ENV["VENUE_ID"]

# setting SWIFT COMPILE FLAGS
  app_ident = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  if "#{app_ident}" == "net.xxxx.zzzz"
    xcatargs = "-DCATALUFA"
  end

    puts "version: '#{version}'"
    buildNumber = latest_testflight_build_number(version: version) + 1
    puts "build #'#{buildNumber}'"
    increment_build_number(
        build_number: buildNumber
    )

    gym(scheme: "Catalufa Profile",
        export_method: "app-store",
        clean: true,
        xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{udid}', OTHER_SWIFT_FLAGS='#{xcatargs}'")

    pilot(skip_waiting_for_build_processing: true)

end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Pro scheme") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

desc "Deploy testflight version to the App Store"
lane :submit do
    deliver(force: true,
    metadata_path: "./fastlane/metadata")
# frameit
end

desc "Download metadata to local ./fastlane/metadata"
lane :get_meta do
deliver(download_metadata: true,
metadata_path: "./fastlane/metadata")
# frameit
end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    enable_automatic_code_signing(path: "Our App.xcodeproj")

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )

    enable_automatic_code_signing(path: "Our App.xcodeproj")

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "net.xxx.yyy" # The bundle identifier of your app
apple_id "jules@" # Your Apple email address


team_id "zzzzzzzzz"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.67.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| method_source             | 0.9.0        |
| pry                       | 0.11.3       |
</details>

*generated on:* **2017-11-28**
</details>

**Comment by janpio** [comment]
Can you run that lane with `--verbose` added at the end? Does it give you more/other output?

**Comment by julestburt** [comment]
It's not a lane - I'm just running in bash script...but no, it didn't give any more output?

**Comment by janpio** [comment]
Got it.

**Comment by julestburt** [comment]
this doesn't solve my issue - but it's interesting. If I run that same deliver command in a lane it runs fine and you get the usual...

[23:12:35]: Making sure the latest version on iTunes Connect matches '3.6.1' from the ipa file...
[23:12:37]: Successfully set the version to '3.6.1'
...

but not when it's run from bundle exec fastlane deliver. The  deliver 2.66.2 Summary is identical between the bash / lane runs...so settings are identical, but environment isn't?

**Comment by janpio** [comment]
I took a look at the code:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/commands_generator.rb#L161-L168

It can't access `version` because `v` seems to be nil/empty/undefined here:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/commands_generator.rb#L165

That code only gets executed when a `app_version` is supplied:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/commands_generator.rb#L163
which you did.

Before it set `v` to a `latest_version`. If the supplied version is not identical with the version of `v`, it replaces it with a `live_version`:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/commands_generator.rb#L164
My guess is this happens and this live_version doesn't exist - which causes the crash when accessing its version to check if this is now the matching one to the one you supplied.

Question is: Why? 
Where do `latest_version` and `live_version` come from?
Do you have any idea what the "latest" and "live" could refer to and what it could be in your case?

**Comment by janpio** [comment]
> 23:12:35]: Making sure the latest version on iTunes Connect matches '3.6.1' from the ipa file...
> [23:12:37]: Successfully set the version to '3.6.1'

Is this additional output you are only getting when running it in a lane? 
Can you please post the _complete_ output you get when running it in the lane?

**Comment by julestburt** [comment]
Hi @janpio 

I will post a little later again. I realized the use of Deliver (and expected working output) in my lane specifically...was delivering an existing build on TestFlight for submission - but obviously it worked in that context. I will add a download_metadata to a lane later today - to see specifics of what occurs, good or bad with that.

Thx.

**Comment by julestburt** [comment]
Actually - seems I cannot execute 'download_metadata' using deliver in a lane, as that isn't an option I can pass.

@janpio You're right about latest_version and live_version. I think I read that Apples response changed some of these key names, so may need updating? Although as I said when I use deliver in a lane (to submit) then it has no trouble downloading existing metadata before it uploads. However I think deliver is setting this current version on iTunes before it downloads existing (and now matching current build) metadata.

Hope that makes sense?

**Comment by janpio** [comment]
> Actually - seems I cannot execute 'download_metadata' using deliver in a lane, as that isn't an option I can pass.

You are right, I created #11153 about this issue.

> You're right about latest_version and live_version. I think I read that Apple's JSON response changed some of these key names, so may need updating in deliver scripts?

Possible, no idea.

> Although as I said when I use deliver in a lane (to submit) then it has no trouble downloading existing metadata before it uploads. However I think deliver is setting this current version on iTunes (and now therefore matching current build #) before it downloads existing metadata.

What do you mean by "downloading ... before it uploads"? From reading the documentation, I don't think `deliver` should download anything when uploading data. Or what am I missing?

**Comment by palusik86** [comment]
Same here :/
