### ISSUE TITLE
[match] Support Custom Entitlements - Apple Pay Pass Suppression

### ISSUE THREAD

**Issue by lukewakeford** [fastlane/fastlane#11049]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

We have 8 Instances of a white labeled app on the appstore, the next version will be supporting apple pay pass suppression, this is a custom entitlement that can only be added to the provisioning profile.

Our current fastlane flow uses match to provision all our apps during CI. Going forward I will need to use a work around to manually create my provisioning profiles at least once per year and then encrypt them and upload them to our provisioning repos as mentioned here: #4548

Would it be possible to add a flag to match to allow custom entitlement support?

Thanks.

**Comment by janpio** [comment]
Can you provide a bit more information on how this works? Code or command example, link to documentation etc.

**Comment by lukewakeford** [comment]
Apple pay pass suppression is a 'custom entitlement' - unlike application services that are attached to the App ID, These custom entitlements are added to the provisioning profile.

I'm using Fastlane for provisioning new Apps and it can add App Services really nicely on App ID Creation, heres a log of this happening successfully:

`[11:47:02]: Successfully logged in
[11:47:03]: [DevCenter] App found 'XXXXX'
[11:47:03]: Enabling services
[11:47:03]: 	App Groups
[11:47:04]: 	Apple Pay
[11:47:06]: Done! Enabled 2 services.`

As mentioned before, I use match to create my certs and profiles but there isn't currently an easy way to configure custom entitlements during this process (the current work around is to manually create your profiles and if you want to use match, encrypt the manually generated profiles and upload them to your provisioning repo).

**Id like to be able to add custom entitlements to provisioning profiles using fastlane.**

Hope that makes sense, let me know if you need more info, I may be able to provide a screenshot of the custom entitlement part of the provisioning portal.

**Comment by janpio** [comment]
That would be nice, basically everything that tells a developer what manual steps would have to be implemented. Do you have an idea how this could work with `match`? (Params, values, workflow, ...)

**Comment by lukewakeford** [comment]
So the steps in order to manually create a new profile and include the custom entitlements are as follows.

- On the apple developer portal navigate to Certificates, Identifiers and Profiles.
- Assuming we already have an App Id and relevant certificates setup and we just want to create a new profile.
- Click on Provisioning Profiles > All > + (plus button to add a new profile)
- Select the profile type e.g. App Store > Click Continue
- Select the relevant App Id for this profile > Click Continue
- Select the Certificate to include in this profile > Click Continue
- Now if Apple have added any custom entitlements to your team ID you will see this 'additional entitlements' step

![Additional Entitlements](https://d26dzxoao6i3hh.cloudfront.net/items/0o3b2E3i3s1I0g0q2Z3z/Screen%20Shot%202017-12-04%20at%2012.17.21.png?v=b5efc32a)

- The final step after selecting the entitlement is to name the profile and finish/download.

Profiles can also be edited to add the custom entitlement and re-generate from the edit flow in the profiles list.

I currently do a lot of my setup for the Match command using environment variables so perhaps a custom entitlements parameter would be a nice way of doing it. Here is an example of my match setup.

```
    match(
      type: ENV['MATCH_TYPE'],
      git_url: ENV['PROVISIONING_REPO'],
      username: ENV['PRODUCE_USERNAME'],
      app_identifier: ENV['APP_IDENTIFIERS'].split(', '),
      readonly: ENV['MATCH_READONLY'],
      team_id: ENV['CERT_TEAM_ID'],
      keychain_name: "xxxx",
      keychain_password: "xxxx",
      force_for_new_devices: true,
      shallow_clone: true
    )
```

**Comment by janpio** [comment]
Ok, thanks for this walk-through.

For reference, lots of entitlements documentation lives here: https://developer.apple.com/library/content/technotes/tn2415/_index.html

Am I correct in assuming that [this here in the yellow box](https://developer.apple.com/documentation/networkextension/nehotspothelper) is another custom entitlement?

If you use https://developer.apple.com/library/content/technotes/tn2415/_index.html#//apple_ref/doc/uid/DTS40016427-CH1-PROFILESENTITLEMENTS on your provisining profile, how does the relevant part for your entitlement look like?

Do you think an implementation should just let you set a list of key value pairs (e.g. `com.apple.developer.passkit.pass-presentation-suppression: true`) as a `custom_entitlements` param or do you think this should work some other way?

**Comment by lukewakeford** [comment]
I've not used the NEHotspotHelper, but it looks like a similar kind of entitlement yes.
That security command is nice! - heres what it looks like inside a distribution profile

```
<key>Entitlements</key>
	<dict>
		...
		<key>com.apple.developer.passkit.pass-presentation-suppression</key>
		<true/>
	</dict>
```

I'm not sure how many of these custom entitlements exist, I guess if the bundle id's are known for all of them you could have a list and allow nice friendly params like

`apple_pay_pass_supression: true`

But if not then as you described with an Array for entering all required custom entitlements by bundle id could work.

Thanks for your help with this :thumbsup:

**Comment by janpio** [comment]
> I've not used the NEHotspotHelper, but it looks like a similar kind of entitlement yes.

Thanks, now I have 2 examples I can work with ;)

Actually 3 as I found another one:
https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/ApplePayandPassKitEntitlements/ApplePayandPassKitEntitlements.html#//apple_ref/doc/uid/TP40011195-CH7-SW4

To recap:
* `com.apple.developer.passkit.pass-presentation-suppression` = Suppressing the Display of Apple Pay Passes
* `com.apple.developer.payment-pass-provisioning` = Enabling In-App Provisioning of Payment Cards
* `com.apple.developer.networking.HotspotHelper` = Register an app as a Hotspot Helper

(I created a [StackOverflow question](https://stackoverflow.com/questions/47639714/what-kind-of-custom-entitlements-do-exist) to ask if someone has a complete list - lets hope it doesn't get closed. Upvotes probably help *`hint)

> That security command is nice!

You can't imagine how happy I am Apple's docs are getting better and you can actually foind stuff like that (although not much better to link, those URLs and anchors are still monsters 👹 )

> heres what it looks like inside a distribution profile

Thanks, make sense - so 100% like normal entitlements.

So battle plan would be to find out 

1. how `match` creates provisioning profiles (probably using some other tool), 
2. where and how exactly the entitlements are defined and how this can be changed, 
3. where and how a new param can be added that can supply the necessary array of key-value pairs or strings (as only value seems to be `true`),
4. write the code for all that and submit it as a PR.

Problem right now: How would I actually test this? Just compare provisioning profiles? My account of course doesn't have access to these custom entitlements, so I guess trying to install such an app would fail :/

----

Might using an "entitlements file" be an alternative solution for your problem maybe?
https://developer.apple.com/library/content/technotes/tn2415/_index.html#//apple_ref/doc/uid/DTS40016427-CH1-ENTITLEMENTSFILE

**Comment by lukewakeford** [comment]
Hint taken.

1. Yeah I think Match uses [sigh](https://docs.fastlane.tools/actions/sigh/) to do provisioning, guessing sigh uses something else under the bonnet that exposes the dev portals API.

I guess the test will be wether or not the profile is successfully created on the dev portal, I'd be happy to run some tests with the apple pay suppression entitlement if we manage to get somewhere with this.

**Comment by janpio** [comment]
What is you "entry point"/call to `match` you are using right now in your lane that would then have to produce a profile with the entitlements?

**Comment by lukewakeford** [comment]
Here's my Fastfile atm. (I've xxx'd out some bits)

```
fastlane_version "1.92.0"

default_platform :ios

platform :ios do

  before_all do |lane, options|
    cocoapods(
      podfile: ENV['PODFILE_LOCATION']
    )
    unlock_keychain(
        path: "xxx",
        password: "xxx"
    )
    register_devices(
      devices_file: "xxx.txt",
      team_id: ENV['CERT_TEAM_ID'],
      username: ENV['PRODUCE_USERNAME']
    )
    match(
      type: ENV['MATCH_TYPE'],
      git_url: ENV['PROVISIONING_REPO'],
      username: ENV['PRODUCE_USERNAME'],
      app_identifier: ENV['APP_IDENTIFIERS'].split(', '),
      readonly: ENV['MATCH_READONLY'],
      team_id: ENV['CERT_TEAM_ID'],
      keychain_name: "xxx",
      keychain_password: "xxx",
      force_for_new_devices: true,
      shallow_clone: true
    )
  end

  desc "Dev Build"
  lane :Dev do
    gym(
      workspace: "../"+ENV['WORKSPACE_NAME'], 
      scheme: ENV['SCHEME_NAME'],
      export_method: ENV['EXPORT_METHOD'],
      export_team_id: ENV['CERT_TEAM_ID'],
      output_name: "build",
      export_options: ENV['EXPORT_PLIST_LOCATION']
    )
  end

  desc "Beta Build"
  lane :Beta do
    gym(
      workspace: "../"+ENV['WORKSPACE_NAME'], 
      scheme: ENV['SCHEME_NAME'],
      export_method: ENV['EXPORT_METHOD'],
      export_team_id: ENV['CERT_TEAM_ID'],
      output_name: "build",
      export_options: ENV['EXPORT_PLIST_LOCATION']
    )
    crashlytics(
      crashlytics_path: ENV['PODFILE_LOCATION']+"/Pods/Crashlytics", 
      api_token: ENV['CRASHLYTICS_TOKEN'], 
      build_secret: ENV['CRASHLYTICS_SECRET'],
      groups: ["xxx"]
    )
  end

  desc "Release Build"
  lane :Release do
    gym(
      clean: true,
      workspace: "../"+ENV['WORKSPACE_NAME'], 
      scheme: ENV['SCHEME_NAME'],
      export_method: ENV['EXPORT_METHOD'],
      export_team_id: ENV['CERT_TEAM_ID'],
      output_name: "build"
    )
    pilot(
      ipa:lane_context[SharedValues::IPA_OUTPUT_PATH],
      username: ENV['PRODUCE_USERNAME'],
      skip_waiting_for_build_processing:true,
      team_id: ENV['ITC_TEAM_ID']
    )
  end

  error do |lane, exception|

  end

end
```

**Comment by janpio** [comment]
Some notes for myself:
* App Services in `produce` = https://github.com/fastlane/fastlane/blob/27aa175503e172c4045ad90f78b8feeba94fe531/produce/lib/produce/service.rb#L19:17
* How do normal provisioning profiles include these? How does `match` learn about it?

**Comment by lukewakeford** [comment]
@janpio I just had a really obvious thought/question..

What if.. **Instead** of trying to pass the entitlement in to the profile creation, I create the profile as usual without the custom entitlement then enter the provisioning portal and add the entitlement to the match generated profile.

**Can** I then force Match to download that modified profile and run in read only?

I think this would solve my issue.

**Comment by janpio** [comment]
Please try, that sounds like a very nice workaround which we then would only have to document a bit.

**Comment by lukewakeford** [comment]
I think the problem with this approach is that `--readonly` means that match only pulls down from the git repo instead of also checking the dev portal.

I need it to pull down from dev portal and store in git repo but **NOT** generate any profiles.

**Comment by lukewakeford** [comment]
@janpio I think this should technically be possibly already by using `--readonly` and `--force` flags in match.

I'm going to raise this as a separate issue. and reference this.

**Comment by lukewakeford** [comment]
@janpio looks like someone already fixed this but it's called templates?
 - https://github.com/fastlane/fastlane/pull/9912

**Comment by janpio** [comment]
Oh wow! 

Does it work for you as expected?

**Comment by lukewakeford** [comment]
Yup it works!

**Comment by janpio** [comment]
Awesome!

Now I'm happy I didn't get to it, as I really would not have connected the dots here.

Left some comments on the PR - thanks for directly creating one.

**Comment by lukewakeford** [comment]
Happy to close as created a PR that improves the documentation on this feature: https://github.com/fastlane/fastlane/pull/11548
