### ISSUE TITLE
Error when running a sh

### ISSUE THREAD

**Issue by marcelofb** [fastlane/fastlane#11041]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when running a sh to install a dependency, the task breaks with the error "invalid byte sequence in UTF-8"

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/prisma/Desktop/Applications/todo-pago-phonegap/fastlane/Appfile'
- package_name: 'com.prisma.todopago'
-------
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#Version minima
fastlane_version "2.66.2"

#Plataforma por defecto
default_platform :android

#Acciones de Android
platform :android do
  desc "Compilación para Android"
  lane :release do |options|
    #Valor recibido por parametro (ejemplo)
    #UI.success options[:un_valor]
    #match(type: "appstore")
    app_android_key = 'keystore_mobile'

    #Configuracion global de cordova para mantener las versiones exactas de plugins (deprecado)
    #sh("cd .. && cordova config set save-exact true")

    #Se instalan dependencias
    dependencies()

    
  end

  lane :prueba do |options|
  UI.message('prueba OK')
  end
end

platform :ios do
  lane :iOSbuild do
    #Se setea el ambiente de Desarrollo
    sh("cd .. && gulp config-dev && gulp package")
  
    #Se compila
    gym(
      export_options: {
        "provisioningProfiles": {
          "com.prisma.todopago": "Todo Pago PEI - STORE"
        },
        "method": "app-store",
        "teamID": "P4ZJVVE6CR"
      },
        "output_directory": "/Users/todopago/desarrollo/todo-pago-phonegap/platforms/ios",
        "output_name": "p2p v"+ENV["VERSION_NUMBER"]+" desa.ipa"
    )

    #Se setea el ambiente de Certificacion
    sh("cd .. && gulp config-cert && gulp package")
  
    #Se compila
    gym(
      export_options: {
        "provisioningProfiles": {
          "com.prisma.todopago": "Todo Pago PEI - STORE"
        },
        "method": "app-store",
        "teamID": "P4ZJVVE6CR"
      },
        "output_directory": "/Users/todopago/desarrollo/todo-pago-phonegap/platforms/ios",
        "output_name": "p2p v"+ENV["VERSION_NUMBER"]+" cert.ipa"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.prisma.todopago" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-11-28**
</details>
Successfully loaded Appfile at path '/Users/prisma/Desktop/Applications/todo-pago-phonegap/fastlane/Appfile'
- package_name: 'com.prisma.todopago'
-------

```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#Version minima
fastlane_version "2.66.2"

#Plataforma por defecto
default_platform :android

#Acciones de Android
platform :android do
  desc "Compilación para Android"
  lane :release do |options|
    #Valor recibido por parametro (ejemplo)
    #UI.success options[:un_valor]
    #match(type: "appstore")
    app_android_key = 'keystore_mobile'

    #Configuracion global de cordova para mantener las versiones exactas de plugins (deprecado)
    #sh("cd .. && cordova config set save-exact true")

    #Se instalan dependencias
    dependencies()

    
  end

  lane :prueba do |options|
  UI.message('prueba OK')
  end
end

platform :ios do
  lane :iOSbuild do
    #Se setea el ambiente de Desarrollo
    sh("cd .. && gulp config-dev && gulp package")
  
    #Se compila
    gym(
      export_options: {
        "provisioningProfiles": {
          "com.prisma.todopago": "Todo Pago PEI - STORE"
        },
        "method": "app-store",
        "teamID": "P4ZJVVE6CR"
      },
        "output_directory": "/Users/todopago/desarrollo/todo-pago-phonegap/platforms/ios",
        "output_name": "p2p v"+ENV["VERSION_NUMBER"]+" desa.ipa"
    )

    #Se setea el ambiente de Certificacion
    sh("cd .. && gulp config-cert && gulp package")
  
    #Se compila
    gym(
      export_options: {
        "provisioningProfiles": {
          "com.prisma.todopago": "Todo Pago PEI - STORE"
        },
        "method": "app-store",
        "teamID": "P4ZJVVE6CR"
      },
        "output_directory": "/Users/todopago/desarrollo/todo-pago-phonegap/platforms/ios",
        "output_name": "p2p v"+ENV["VERSION_NUMBER"]+" cert.ipa"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.prisma.todopago" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-11-28**
</details>

**Comment by janpio** [comment]
The environment info you posted is duplicated but the actual output showing the failure is missing :/
What lane are you executing and what `sh` invocation exactly is causing the crash?

**Comment by marcelofb** [comment]
@janpio I use a custom lane called dependencies() which execute "npm install cordova-plugin-card-io". if I execute the instruction from the terminal it doesn't break.

**Comment by janpio** [comment]
Could you please post the output you get when running that lane, including the error output?
Also post the actual action please.

**Comment by joshdholtz** [comment]
There has been no response for a few months heres closing. Feel free to comment with your output if you want us to reopen and look into 😊
