### ISSUE TITLE
Add groups to pilot distribute_build without disabling demo account

### ISSUE THREAD

**Issue by dantman** [fastlane/fastlane#11056]
In pilot's `distribute_build` when `groups` or `distribute_external` are set then`uploaded_build.beta_review_info.demo_account_required` is set to `false`.

https://github.com/fastlane/fastlane/blob/680420d25f96c255a3e9e3d7fdbc9a1f59088e88/pilot/lib/pilot/build_manager.rb#L135-L170

Is this necessary? I'd like to automatically add the build to our list of internal testers but a demo account is still required for Apple, there is no sign up page in this business app.

**Comment by dantman** [comment]
The code in question has not changed.

**Comment by taquitos** [comment]
@dantman is the only problem that it automatically sets it to `false`?

**Comment by dantman** [comment]
Yes, that overrides the TestFlight settings. So if your app requires a demo account to login, then simply trying to make fastlane add a build to a group of testers would disable the demo login that Apple needs to test the app and authorize it for those testers.

**Comment by taquitos** [comment]
Ohh, that makes sense, thanks for the clarification!
