### ISSUE TITLE
testfairy - custom API url for upload

### ISSUE THREAD

**Issue by marianpolek** [fastlane/fastlane#11057]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

Hi all, 

i am just requesting new feature. custom upload URL (API server url) for testfairy action. Because some of us have private cloud instance, dont know if it's new feature but some companies does have it. 
Thank you

should be like, default one, original, and some custom with params[:api_url] or something like this. ofcourse as a optional parameter

### Environment

fastlane/fastlane/lib/fastlane/actions/testfairy.rb

now, there is hardcoded "https://upload.testfairy.com"

![screenshot 2017-12-03 16 59 41](https://user-images.githubusercontent.com/4357071/33527212-e06778ae-d84c-11e7-9797-dac1168f457e.png)
![screenshot 2017-12-03 17 02 10](https://user-images.githubusercontent.com/4357071/33527213-e0807c64-d84c-11e7-873a-9efb8aa3db61.png)

**Comment by janpio** [comment]
`testfairy` normally uses `ipa` to define the path of the file to be uploaded. 
How does this relate to "custom icloud instance"?
Or do you mean the API endpoint - do you have your own API server? Can you provide some documentation on that?

**Comment by marianpolek** [comment]
Yes i mean api endpoint. Yes we have own api server. Dont have documentation, just requested to make that url not hardcoded. Just make ist as parameter, optional parameter. So default will be original testfairy server like it is now

**Comment by marianpolek** [comment]
Now, there is a https://upload.testfairy.com

**Comment by janpio** [comment]
Can anyone have such a custom server? where can I read about that?

**Comment by marianpolek** [comment]
You can read about that on testfairy.com. It’s on topic about security. Private cloud. 
But i think tou are going to out of topic :) so back to my request :)

**Comment by janpio** [comment]
I am not going to google that myself. Please get the link and post it here if you want me to look at it.

**Comment by marianpolek** [comment]
https://testfairy.com ---- scroll down to part "SECURE PRIVATE CLOUD" .... should i past here a screenshot ? hm. you don't believe me ? :/   
i am just requested feature, if somebody will do it, okay, if not , okay.. 

thank you

**Comment by joshdholtz** [comment]
@marianpolek Would you still like this feature? If yes... would you be able to use a branch to test out my change since I don't have access to a private testfairy instance?

**Comment by marianpolek** [comment]
Hi @joshdholtz 
Yes i will test it on monday at the work

**Comment by joshdholtz** [comment]
@marianpolek Perfect! Opening up because should be straight forward to implement, I just can't test 😊 Stay tuned for a branch URL when I get around to this 👍

**Comment by joshdholtz** [comment]
@marianpolek I was able to get my hands on a private cloud thingy, tested it, and created a PR ^
