### ISSUE TITLE
Manually pointing the xcode_path variable for build

### ISSUE THREAD

**Issue by girishnair12345** [fastlane/fastlane#11051]
How can I manually set the xcode_path variable?
I did check [this commit ] (https://github.com/fastlane/fastlane/commit/ed6e7f493c5a5c7dcee1ac4ceb8e455587d0cd68).

I don't want to set the **ENV['DEVELOPER_DIR'] = /Applications/Xcode2.app** but set it in fastfile or app file that fastlane generates

The problem that I am facing is that one of the projects is built using old Xcode 8.3 and another project is built using 9.1

I need to set the  _xcode_path /Applications/Xcode2.app_  so that the build uses a specified version using project-level settings

**Comment by girishnair12345** [comment]
yes I have, please check it

**Comment by janpio** [comment]
You mistyped the command.

**Comment by girishnair12345** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "2.56.0"

default_platform :ios

platform :ios do

	desc "Development Build"
	lane :dev do
		begin
			cert(development:true)
		rescue => ex
			UI.error(ex)
		end
		
		begin
			sigh(development:true)
		rescue => ex
			UI.error(ex)
		end

		begin
			sh "sigh download_all"
		rescue => ex
			UI.error(ex)
		end

	   	gym(scheme: "SCHEME_NAME", export_method:"development", clean:true, export_options:{provisioningProfiles:{}}, configuration:"Debug") 
	end

	desc "Release Build"
	lane :release do
		begin
			cert(development:false)
		rescue => ex
			UI.error(ex)
		end

		begin
			sigh(development:false)
		rescue => ex
			UI.error(ex)
		end

		begin
			sh "sigh download_all"
		rescue => ex
			UI.error(ex)
		end

	   	gym(scheme: "SCHEME_NAME", export_method:"enterprise", clean:true, export_options:{provisioningProfiles:{}}, configuration:"Release") 
	end

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "BUNDLE_ID" # The bundle identifier of your app
apple_id "EMAIL_ID" # Your Apple email address

team_id "TEAM_ID" # Developer Portal Team ID


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.56.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-11-30**
</details>

**Comment by girishnair12345** [comment]
Its done by adding this to our Fastfile

xcode_select "/Applications/Xcode_9_2.app"
