### ISSUE TITLE
[gradle] Android - Gradle build with dynamic applicationId?

### ISSUE THREAD

**Issue by royberris** [fastlane/fastlane#11069]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

How would I run gradle with a custom application ID every time? In iOS it is possible, now I need to implement this on the Android side, but I'm kind of stuck. And I know about the flavours, but we are talking about building over 100 apps with a different applicationId, and I am not looking forward to putting over 100 flavours into gradle.

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by janpio** [comment]
I would look into `properties` and see how I can use that in the Gradle script to set the app id.

**Comment by royberris** [comment]
@janpio I know how to set the "applicationId" dynamic now, but you have the problem where the package itself needs to be 'renamed'. If I set the applicationId to "com.foo.bar" but the actual folder and package's in the Java files are "com.bar.foo" it won't work. I need a compile my app, so that the store sees it as a different app even tho it might use the same package in the code. Is this possible?

**Comment by janpio** [comment]
Isn't this exactly what `gradle` is for? I am sure there are actions or plugins that can edit a file or rename a folder - if not `sh` is available.

**Comment by joshdholtz** [comment]
@royberris This is something a little custom but this is something you could do with different build flavors in gradle (which isn't a fastlane thing) but you can also do something like...

```rb
sh "find #{path}/app/src -name '*.java' -type f -exec sed -i '' 's/#{package_name}/#{new_package_name}/' {} \\;"
          sh "find #{path}/app/src -name 'AndroidManifest.xml' -type f -exec sed -i '' 's/#{package_name}/#{new_package_name}/' {} \\;"
          sh "find #{path}/app -name 'build.gradle' -type f -exec sed -i '' 's/#{package_name}/#{new_package_name}/' {} \\;"
```

It's a little gross but it will work 😊 If this doesn't work I would recommend creating your own fastlane plugin since your use case sounds pretty specific 💪
