### ISSUE TITLE
can we stop the execution at point when "the name xyz is already taken, creating new one"

### ISSUE THREAD

**Issue by kumarkalluri** [fastlane/fastlane#11072]
- Sigh with config.
          
Issue is : 
       Actually, provision profile(xyz) is taking from the config file. So, in the above case if that named provision profile(xyz) already created and associated with other certificates. Sigh is looking the for the provisioning profile(xyz) and if it exists, creating the profile with name appending(xyz 1150345) with the timestamp, but my scheme is looking for the xyz profile and then build fails.
  So, I want to stop the execution when the provisioning profile is already taken and throw the customized message to user.

**Comment by joshdholtz** [comment]
@kumarkalluri Thanks for the feature suggestion! We have a long list of things to work on so if you are willing to create a PR for this that would be great 😊
