### ISSUE TITLE
Cannot upload binary if version doesn't exist

### ISSUE THREAD

**Issue by olejnjak** [fastlane/fastlane#11079]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi, 

I have a problem with `deliver`. In my case I have an app that has one version on iTunes Connect (1.0) and its state is *Ready for sale*. I want to upload an update (version 1.0.1) but that version doesn't exist yet. My role on iTC is **developer** so I am only allowed to upload new builds. When I try to run `deliver` with arguments `--skip-screenshots` and `--skip-metadata`, I end up with error
```
User jakub.olejnik@ackee.cz (Team ID <team_id>) doesn't have enough permission for the following action: create_version
```

Well then I looked more in the documentation and tried adding parameter `--skip_app_version_update` and I ended up with error 
```
Could not find a version to edit for app '<app_name>'
```

Okay then I've added `--force` parameter and the result was the same.
```
Could not find a version to edit for app '<app_name>'
```

There must be some problem with `deliver` because later when I tried to upload binary using **Application Loader** it uploaded successfully.

##### Complete output when running fastlane, including the stack trace and command used

Deliver call
```
+--------------------------------------+----------------------------------------------------+
|                                  deliver 2.68.0 Summary                                   |
+--------------------------------------+----------------------------------------------------+
| skip_screenshots                     | true                                               |
| skip_metadata                        | true                                               |
| skip_app_version_update              | true                                               |
| force                                | true                                               |
| ipa                                  | /Users/olejnjak/Ackee/carolina/outputs/App.ipa.ipa |
| username                             | jakub.olejnik@ackee.cz                             |
| app_identifier                       | <app_id>                                           |
| screenshots_path                     | ./fastlane/screenshots                             |
| metadata_path                        | ./fastlane/metadata                                |
| app_version                          | 1.0.1                                              |
| edit_live                            | false                                              |
| platform                             | ios                                                |
| skip_binary_upload                   | false                                              |
| submit_for_review                    | false                                              |
| automatic_release                    | false                                              |
| overwrite_screenshots                | false                                              |
| run_precheck_before_submit           | true                                               |
| precheck_default_rule_level          | warn                                               |
| ignore_language_directory_validation | false                                              |
| precheck_include_in_app_purchases    | true                                               |
+--------------------------------------+----------------------------------------------------+
```
Result
```
Could not find a version to edit for app '<app_name>'
```
### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
##################################### SETTINGS #####################################

inhouse_apple_id = 'unicorn@ackee.cz'
connect_team_id = "xxx"

####################################################################################

ENV["ACK_BACKTOBASICS"] = "1"
ENV["FASTFILE_DIR"] = File.expand_path(File.dirname(__FILE__))
ENV["ACK_PREPROCESS_HEADER"] = "../Environment/environment_preprocess.h"

#import "../../fastlane/fastlane/Fastfile"
import(download_from_git(url: 'git@gitlab.ack.ee:Ackee/fastlane.git', use_cache: is_xcode ))


ENV["GYM_USE_LEGACY_BUILD_API"] = nil
xcversion version: "~> 9.0"

  desc "Downloads provisioning for all environments"
  lane :provisioning do |options|
    environment = options[:environment]

    if environment && !(is_environment(environment: environment))
      raise "Unknown environment #{environment}"
    end

    if !environment || environment == "Development"
      provisioning_match(configuration: "Debug",
                        type: "development",
                        app_identifier: app_identifier("Development"),
                        username: inhouse_apple_id,
                        team_id: team_id("Development"),
                        readonly: true)
    end

    if !environment || environment == "Stage"
      provisioning_match(configuration: "AdHoc",
                        type: "enterprise",
                        app_identifier: app_identifier("Stage"),
                        username: inhouse_apple_id,
                        team_id: team_id("Stage"),
                        readonly: true)
    end

    if !environment || environment == "Production"
      provisioning_match(configuration: "AppStore",
                        type: "appstore",
                        app_identifier: app_identifier("Production"),
                        git_url: ENV["ACK_PRODUCTION_MATCH_GIT"],
                        team_id: team_id("Production"),
                        readonly: true)

      #Use sigh only for client accounts (on our account you would use match)
      # provisioning_sigh(configuration: "AppStore",
      #                   username: production_apple_id,
      #                   team_id: team_id("Production"),
      #                   app_identifier: app_identifier("Production"))
    end

  end

  desc "Submit new **beta** build to Hockey app"
  lane :beta do

    environment = "Stage"

    #Download provisioning if on CI, locally can be run by the user
    if is_ci then
        provisioning(environment: environment)
    else
        UI.message("Running locally, not running :provisioning lane, if needed run manually")
    end

    #Setup environments, app identifier and app name
    set_environment(environment: environment)

    #Setup badge for beta
    begin
        badge(shield: "#{get_version_number}-#{number_of_commits}-blue", dark: false, shield_no_resize: true)
    rescue
        UI.error("Unable to add badges to app icon")
        # Put badge back to original
        sh "git checkout -- ../Resources/Images.xcassets/"
    end

    begin
      gym(
          scheme: environment,
          configuration: "AdHoc",
          clean: false
  		)
    ensure
      # Put badge back to original
      sh "git checkout -- ../Resources/Images.xcassets/"
    end

    if !is_ci
        hockey_identifier = get_environment_plist_value(key: "hockey_identifier", environment: environment)

        hockey(
              public_identifier: hockey_identifier,
              notify: '0'
        )
    end
  end


  desc "Deploy new version to the App Store (and also hockey app)"
  lane :appstore do |options|

      environment = "Production"

      #Setup environments, app identifier and app name
      set_environment(environment: environment)

      # if !options[:skip_snapshot]
      #   snapshot
      # end

      provisioning(environment:environment)

      gym(
  		  scheme: environment,
        configuration: "AppStore",
  		  clean: true
  		)

        deliver(
                skip_screenshots: true,
                skip_metadata: true,
                skip_app_version_update: true,
                force: true
            )
  end



  desc "Switches environment and sets app_name and app_identifier in plist"
  lane :set_environment do |options|
      if is_xcode
          UI.message "Xcode run script phase"
      end

      environment = options[:environment]

      if !is_environment(environment: environment)
          raise "Unknown environment #{environment}"
      end

      display_name = app_name(environment)
      app_identifier =  app_identifier(environment)

      UI.message "Setting environment for #{environment}"

      # Change environment plist
      replace_environment_plist(environment: environment)

      # Change GoogleService-Info.plist
      replace_google_plist(environment: environment)

      fb_dict = get_environment_plist_value(key: "facebook", environment: environment)
      fb_app_name = fb_dict["app_name"]
      fb_app_id = fb_dict["app_id"]
      fb_app_scheme = fb_dict["app_scheme"]
      fb_app_suffix = fb_dict["app_suffix"]

      environment_dict = {
          "ACK_BUILD_NUMBER" => number_of_commits,
          "FB_APP_NAME" => fb_app_name,
          "FB_URL_SCHEME" => fb_app_scheme,
          "FB_APP_ID" => fb_app_id,
          "FB_URL_SUFFIX" => fb_app_suffix
      }

      generate_preprocess_header(values: environment_dict)
  end

  override_lane :localization do  |options|
      UI.message "Downloading localized strings from Google Doc"
      sh "cd ..; " + ENV["FASTFILE_DIR"] + "/utils/localization.sh " + ENV["FASTFILE_DIR"] + "/utils" + "; cd -"
  end

  desc "Install pods"
  lane :pods do |options|
      pod_install
  end

#end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.0.0        |
| slack-notifier        | 1.5.1        |
| claide                | 1.0.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.2        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| highline              | 1.7.8        |
| commander-fastlane    | 4.4.5        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| mini_magick           | 4.5.1        |
| security              | 0.1.3        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| google-api-client     | 0.13.6       |
| json                  | 2.1.0        |
| io-console            | 0.4.5        |
| excon                 | 0.59.0       |
| rubyzip               | 1.2.1        |
| plist                 | 3.3.0        |
| faraday               | 0.13.1       |
| os                    | 0.9.6        |
| googleauth            | 0.6.1        |
| signet                | 0.8.1        |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| faraday_middleware    | 0.12.2       |
| colored2              | 3.1.2        |
| bundler               | 1.16.0       |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
</details>

*generated on:* **2017-11-30**
</details>

**Comment by janpio** [comment]
>  I want to upload an update (version 1.0.1) but that version doesn't exist yet. My role on iTC is developer so I am only allowed to upload new builds.

> ... doesn't have enough permission for the following action: create_version

Here is the description of what a "Developer" can do:
https://help.apple.com/itunes-connect/developer/#/dev82a173c41

> Upload binaries to iTunes Connect.

As I understand that, "creating a version" and "uploading a binary" are two different things. 
Former creates the version that contains metadata, screenshots and builds, the latter becomes a build for a specific version that has to be created first. Correct?
If you log in, can you actually create a new version in iTunes Connect?

Where did the app you uploaded with Application Loader end up? New version or with the old one? Or somewhere else?

(Might very well be that `deliver` always trys to create a version if the specified one doesn' exist yet. Let's look into that after you reply.)

**Comment by olejnjak** [comment]
The issue is definitely in `deliver`, the build ended up under version 1.0.1 which existed only under Testflight builds. Right now I can't create a screenshot as the build is already submited to the store...

**Comment by janpio** [comment]
> the build ended up under version 1.0.1 which existed only under Testflight builds.

Wait, didn't uploading it with Application Loader do something that was not expected then? I understood you that you wanted to create a new version on the normal app and supply a build to it (so you can also add screenshots), correct?

**Comment by olejnjak** [comment]
Nope, I consider the behaviour of Application Loader correct. As we know the version of app in iTC doesn't have to correspond with app version in app's bundle so there is no real connection between them. So I don't see any reason why `deliver` should restrict such uploads.

**Comment by janpio** [comment]
Ok, let me try to recap:

You have only version 1.0.0 on iTC.
You locally build a 1.0.1.
You want to upload that 1.0.1.

If you use `deliver` you get the error that you can't create a new version (which is true, as your are only "Develper").
If you use Application Loader, it is uploaded into 1.0.1 under Testflight.

All correct?

For upload to Testflight there is a specific action: https://docs.fastlane.tools/actions/testflight/

Did you use your `appstore` lane that was included in your first post?
The `deliver Summar` you included is from that run?
My question (not really for you, more to the code) is: Where did it get the app_version that is output in the summary?

Can you please run the initial lane with `--verbose` and post the complete output as the issue template suggested?
Can you try to set a `app_version = 1.0.0` in your `deliver` call and see what happens?

> Also uploading screenshots doesn't make sense as developer role doesn't have permission to do that.

Why did you bring it upin the post before then?

>  Right now I can't create a screenshot as the build is already submited to the store...

**Comment by olejnjak** [comment]
Hah, cool, didn't notice that there's special *Testflight* action as we've been misusing `deliver` as historically we all had higher permission on iTC. Consider this resolved, I'll report back if using Testflight action doesn't work.

**Comment by olejnjak** [comment]
Yep, `testflight` action nailed it. There's just one inconvenience that the action reports error even in case when no errors occur.

```
[14:56:18]: ------------------------
[14:56:18]: --- Step: testflight ---
[14:56:18]: ------------------------
[14:57:40]: Login to iTunes Connect (<apple_id>)
[14:57:48]: Login successful
[14:57:49]: Ready to upload new build to TestFlight (App: <app_id>)...
[14:57:50]: Going to upload updated app to iTunes Connect
[14:57:50]: This might take a few minutes. Please don't interrupt the script.
[14:58:17]: [Transporter Error Output]: description length:5597673
[15:00:33]: iTunes Transporter successfully finished its job
[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:28 CET] <main> DBG-X: Apple's web service operation return value:

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:28 CET] <main> DBG-X:   parameter Success = true

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:33 CET] <main> DBG-X: Unlocking token at path /Users/olejnjak/.itmstransporter/UploadTokens/Jakub-Macbook.local_7NM382XQ7C_1315972574.itmsp.token

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:33 CET] <main> DBG-X: Releasing token file lock

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:33 CET] <main> DBG-X: Removing token at path /Users/olejnjak/.itmstransporter/UploadTokens/Jakub-Macbook.local_7NM382XQ7C_1315972574.itmsp.token

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:33 CET] <main>  INFO: Done performing uploadDone notification to Apple.

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:33 CET] <main>  INFO: The package: /var/folders/5g/dxznwg850518m5fx369sfmsc0000gn/T/d20171208-89886-1hlh7ws/1315972574.itmsp has been successfully uploaded.

[15:00:33]: [iTMSTransporter] 

[15:00:33]: [iTMSTransporter] 

[15:00:33]: [iTMSTransporter] 

[15:00:33]: [iTMSTransporter] Package Summary:

[15:00:33]: [iTMSTransporter]  

[15:00:33]: [iTMSTransporter] 1 packages were uploaded successfully:

[15:00:33]: [iTMSTransporter] 	/var/folders/5g/dxznwg850518m5fx369sfmsc0000gn/T/d20171208-89886-1hlh7ws/1315972574.itmsp

[15:00:33]: [iTMSTransporter] [2017-12-08 15:00:33 CET] <main> DBG-X: Returning 0

[15:00:33]: iTunes Transporter output above ^
[15:00:33]: description length:5597673
[15:00:33]: Although errors occurred during execution of iTMSTransporter, it returned success status.
[15:00:33]: ---------------------------------------------------------------------------------------------------------------
[15:00:33]: --- Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online. ---
[15:00:33]: ---------------------------------------------------------------------------------------------------------------
[15:00:33]: Successfully uploaded the new binary to iTunes Connect
[15:00:33]: Skip waiting for build processing
[15:00:33]: This means that no changelog will be set and no build will be distributed to testers
```

This output is produced using fastlane 2.68.0. After that I updated to 2.68.2.

I will try to keep this on my mind when submitting next build and will create new issue if this still remains in the latest version.

**Comment by janpio** [comment]
Thanks, an additional issue would be the way to go if this persists.
