### ISSUE TITLE
bundler: failed to load command: fastlane (/usr/local/bin/fastlane) NoMethodError: [!] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Megatron1000** [fastlane/fastlane#11071]
### New Issue Checklist

- [ ✔️] Updated fastlane to the latest version
- [ ✔️] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✔️ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✔️ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane is failing to launch

##### Complete output when running fastlane, including the stack trace and command used

C360572:myHomeIOS mark.bridges$ bundle exec fastlane build_distribute config:develop color_icon:false --verbose
DEBUG [2017-11-30 10:49:11.55]: Checking if there are any plugins that should be loaded...
DEBUG [2017-11-30 10:49:11.55]: Loading 'fastlane-plugin-unzip' plugin
INFO [2017-11-30 10:49:11.61]: gem 'fastlane-plugin-unzip' is already installed
+-----------------------+---------+--------+
|               Used plugins               |
+-----------------------+---------+--------+
| Plugin                | Version | Action |
+-----------------------+---------+--------+
| fastlane-plugin-unzip | 1.0.1   | unzip  |
+-----------------------+---------+--------+

Successfully loaded Appfile at path '/Users/mark.bridges/Documents/myHomeIOS/fastlane/Appfile'
- app_identifier: 'com.thirstysea'
- apple_id: 'uday.pandey@bgch.co.uk'
- team_id: '6WX233N4N3'
-------
DEBUG [2017-11-30 10:49:11.81]: Using config: develop
DEBUG [2017-11-30 10:49:11.81]: Using color_icon: false
INFO [2017-11-30 10:49:11.84]: -------------------------------------------------
INFO [2017-11-30 10:49:11.84]: --- Step: Verifying required fastlane version ---
INFO [2017-11-30 10:49:11.84]: -------------------------------------------------
INFO [2017-11-30 10:49:11.84]: Your fastlane version 2.67.0 matches the minimum requirement of 2.39.0  ✅

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60[]'%20for%20nil+repo:fastlane/fastlane
➡️  Type Checking error: got 'Fixnum' for attribute 'fileEncoding' and undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11016 [open] 1 💬
    a week ago

➡️  `fastlane deliver download_metadata` crash: NoMethodError: [!] undefined method `version' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11046 [open] 7 💬
    11 hours ago

➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
    https://github.com/fastlane/fastlane/issues/10447 [open] 11 💬
    a week ago

and 299 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2017-11-30 10:49:13.52]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `[]' for nil:NilClass
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/fast_file.rb:57:in `rescue in block in parse'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/fast_file.rb:47:in `block in parse'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.67.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
C360572:myHomeIOS mark.bridges$ whereis ruby
/usr/bin/ruby
C360572:myHomeIOS mark.bridges$ ruby  -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
C360572:myHomeIOS mark.bridges$ rbenv ruby-build
rbenv: no such command `ruby-build'
C360572:myHomeIOS mark.bridges$ whereis ruby
/usr/bin/ruby
C360572:myHomeIOS mark.bridges$ usr/local/bin bundle exec fastlane build_distribute config:develop color_icon:false --verbose
-bash: usr/local/bin: No such file or directory
C360572:myHomeIOS mark.bridges$ /usr/local/bin bundle exec fastlane build_distribute config:develop color_icon:false --verbose
-bash: /usr/local/bin: is a directory

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.1                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.6 (Apple Git-96)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.1 (17B1003)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.39.0"
#require 'pry'
#binding.pry
require_relative 'config'
fastlane_require 'shellwords'

default_platform :ios

platform :ios do

  before_all do |lane, options|

  end

  before_each do |lane, options|

  end


  ###### Lanes #########

  desc "Hive build command"
  lane :build_distribute do |user_input|

    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "60"
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"

    # Get config
    (bconfig, bname) = build_config(user_input)
    if bconfig.nil? then
      UI.error("Provided config is invalid: #{bconfig}")
      return
    end
    UI.success("Selected config: #{bname}")

    # Get environments to build
    head, *tail = *environments(bconfig)
    UI.success("Building for #{head}, then #{tail} will be signed")

    # Building options
    app_version = get_version_number
    options = build_options(head, bconfig, user_input, app_version, bname)
    FastlaneCore::PrintTable.print_values(config: options, title: "Build Config")

    # Changing Icon Color
    if options[:color_icon] then
      UI.message("Changing icon color")
      sh("find ../Hive/Images.xcassets/AppIcon.appiconset -name '*.png' -print0 | xargs -0 -n1 ../scripts/appicon/change_dominant_color.sh '#{options[:icon_color]}'")
      sh("find ../Hive\\ Watch/Assets.xcassets/AppIcon.appiconset -name '*.png' -print0 | xargs -0 -n1 ../scripts/appicon/change_dominant_color.sh '#{options[:icon_color]}'")
    end

    # Update Plist
    update_plist(options)

    # Setup keychain
    if ENV['CI'] then
      setup_keychain
    end

    # Disable code signing
    disable_automatic_code_signing

    # Define product name
    product_name = "Hive"

    # Build
    build_internal(options)
    options[:ipa_path] = "build/#{product_name}.ipa"

    # Distribute first binary
    distribute(options)

    if !tail.empty? then
      unzip(file: "build/#{product_name}.ipa", destination_path: "build/Hive_extracted")

      tail.each { |e|
        # Create folder for env builds
        sh("mkdir -p ../build/#{e}")
        ipa_path = "build/#{e}/#{product_name}.ipa"

        # Get options
        UI.message("Creating options for environment: #{e}")
        e_options = build_options(e, bconfig, user_input, app_version, bname)
        e_options[:main_app_info_plist] = "./build/Hive_extracted/Payload/#{product_name}.app/Info.plist"
        e_options[:watch_extension_app_info_plist] = "./build/Hive_extracted/Payload/#{product_name}.app/Watch/Hive Watch.app/PlugIns/Hive Watch Extension.appex/Info.plist"
        e_options[:watch_app_info_plist] = "./build/Hive_extracted/Payload/#{product_name}.app/Watch/Hive Watch.app/Info.plist"
        e_options[:watch_app_info_plists] = [e_options[:watch_app_info_plist], e_options[:watch_extension_app_info_plist]]

        FastlaneCore::PrintTable.print_values(config: e_options, title: "Build Config")

        # Icon color
        if options[:color_icon] then
          UI.message("Changing icon color")
          sh("find ../build/Hive_extracted/Payload/ -name 'AppIcon*' -print0 | xargs -0 -n1 ../scripts/appicon/change_dominant_color.sh '#{e_options[:icon_color]}'")
          sh("find ../build/Hive_extracted/Payload/Watch/Hive\\ Watch/ -name 'AppIcon*' -print0 | xargs -0 -n1 ../scripts/appicon/change_dominant_color.sh '#{e_options[:icon_color]}'")
        end

        # Convert app info plist to xml
        plists = e_options[:watch_app_info_plists]
        plists << e_options[:main_app_info_plist]
        plists.each do |plist|
          sh("plutil -convert xml1 .#{plist.shellescape}")
        end

        # Update info.plist
        update_plist(e_options)
        update_bundle_ids(e_options)

        # Convert Info.plist to binary
        plists.each do |plist|
          sh("plutil -convert binary1 .#{plist.shellescape}")
        end

        # Zip IPA
        zip(path:"build/Hive_extracted/Payload", output_path: ipa_path)
        sh("mv ../#{ipa_path}.zip ../#{ipa_path}")

        # Resign
        certificates(e_options)
        resign(
          ipa: ipa_path,
          signing_identity: "iPhone Distribution: Centrica Connected Home LTD",
          provisioning_profile: e_options["provisioning_profile_paths"],
          display_name: e_options[:app_name],
          bundle_id: e_options[:bundle_identifier]
        )

        # Distribute
        e_options[:ipa_path] = ipa_path
        distribute(e_options)
      }
    end
  end

  lane :setup_keychain do
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASS"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
  end

  desc "Hive run unit tests command"
  lane :unit_test do |options|
    scan(
        clean: true,
        scheme: "Hive",
        devices: ["iPhone 7", "iPad Air"]
    )
  end


  lane :certificates do |options|
    ids = app_ids(options[:bundle_identifier], app_ids_extensions(options))
    type = options[:match_type]
    match(app_identifier: ids, type: type, team_id: options[:team_id], keychain_name: ENV["KEYCHAIN_NAME"], keychain_password: ENV["KEYCHAIN_PASS"])
    options["provisioning_profile_paths"] = Hash.new
    ids.zip(app_ids_extensions(options)).each { |id,ext|
      key = ["last_sigh_provisioning_profile", ext.gsub(".", "_"), type].reject(&:empty?).join("_")
      path_key = "#{key}_profile_path"
      ENV[key] = ENV[["sigh", id, type, "profile-name"].join("_")]
      ENV[path_key] = ENV[["sigh", id, type, "profile-path"].join("_")]
      UI.success("Set " + ENV[key] + " to " + key )
      options["provisioning_profile_paths"][id] = ENV[path_key]
    }
  end


  ########## Info.plist ########

  private_lane :update_bundle_ids do |options|
    set_info_plist_value(key: "CFBundleIdentifier", value:options[:main_app_bundle_id], path: options[:main_app_info_plist])
    if options[:watch]
      set_info_plist_value(key: "CFBundleIdentifier", value:options[:watch_app_bundle_id], path: options[:watch_app_info_plist])
      set_info_plist_value(key: "WKCompanionAppBundleIdentifier", value:options[:bundle_identifier], path: options[:watch_app_info_plist])
      set_info_plist_value(key: "CFBundleIdentifier", value:options[:watch_ext_app_bundle_id], path: options[:watch_extension_app_info_plist])
      extension_attributes = {
        "WKAppBundleIdentifier" => options[:watch_app_bundle_id]
      }
      set_info_plist_value(key: "NSExtension", subkey: "NSExtensionAttributes", value:extension_attributes, path: options[:watch_extension_app_info_plist])
    end
  end

  private_lane :update_plist do |options|

    options[:watch_app_info_plists].each { |plist|
      set_info_plist_value(key: "CFBundleShortVersionString", value: options[:app_long_version], path: plist)
    }
    set_info_plist_value(key:"CFBundleShortVersionString",    value:options[:app_long_version], path:options[:main_app_info_plist])

    set_info_plist_value(key:"CFBundleDisplayName",           value:options[:app_name],         path:options[:main_app_info_plist])

    # Current Used Values
    set_info_plist_value(key:"HVServerURL",                   value:options[:v6_server_url],                    path:options[:main_app_info_plist])
    set_info_plist_value(key:"HVServeroAuthURL",              value:options[:v6_server_oauth_url],              path:options[:main_app_info_plist])
    set_info_plist_value(key:"HVNonProxyServerURL",           value:options[:v6_non_proxy_server_url],          path:options[:main_app_info_plist])
    set_info_plist_value(key:"HVNonProxyServerUSURL",         value:options[:v6_non_proxy_server_us_url],       path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCServerURL",                  value:options[:v5_server_url],                    path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCWeatherURL",                 value:options[:weather_url],                      path:options[:main_app_info_plist])
    set_info_plist_value(key:"HVV6USServerURL",               value:options[:v6_us_server_url],                 path:options[:main_app_info_plist])
    set_info_plist_value(key:"HVReplaceHubURL",               value:options[:replace_hub_url],                  path:options[:main_app_info_plist])

    # Proposed Values
    set_info_plist_value(key:"RHCV6ServerURL",                value:options[:v6_server_url],    path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCV6USServerURL",              value:options[:v6_us_server_url], path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCV5ServerURL",                value:options[:v5_server_url],    path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCWeatherURL",                 value:options[:weather_url],      path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCBeekeeperURL",               value:options[:beekeeper_url],    path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCUSBeekeeperURL",             value:options[:beekeeper_us_url], path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCHiveLiveSubscribeURL",       value:options[:hivelive_url],     path:options[:main_app_info_plist])

    set_info_plist_value(key:"RHCCommitID",                   value:options[:commit_id],        path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCShortCommitID",              value:options[:short_commit_id],  path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCBuildTimestamp",             value:options[:build_timestamp],  path:options[:main_app_info_plist])
    set_info_plist_value(key:"RHCPushNotificationAppName",    value:options[:pushnotifications_app_name],  path:options[:main_app_info_plist])

    set_info_plist_value(key:"HVCamPlatformURL",              value:options[:hivecam_platform_url],    path:options[:main_app_info_plist])
    set_info_plist_value(key:"HVCamPlatformUSURL",            value:options[:hivecam_us_platform_url],    path:options[:main_app_info_plist])

  end

  ########## Building ##########

  private_lane :build_internal  do |options|

    xcarg_options = []

    # Added these xcargs to get Xcode 8 manual provisioning working as automatic provisoning just keeps failing miserably on the build server.
    # There's probably a better way of doing this but wasted too much time already with provisioning...

    xcarg_options << "PARENT_APP_BUNDLE_IDENTIFIER='#{options[:bundle_identifier]}'" if options[:bundle_identifier]

    xcargs_arguments = xcarg_options.any? ? xcarg_options.join(" ") : ""

    # Useful when you want to try building with a different (i.e. non-default) version of Xcode (i.e. you can use a version for a specific build by passing in "xcode_version:'X.X'" to the command line)
    if options[:xcode_version]
        xcversion(version: options[:xcode_version])
    end

    certificates(options)

    gym(
        xcargs:                 xcargs_arguments,

        # Clean before build
        clean:                  true,

        workspace:              "Hive.xcworkspace",
        scheme:                 "Hive",
        configuration:          options[:configuration],

        output_directory:       "build",

        # Set this to true if you want to see the raw xcodebuild output (otherwise it is stored in a separate file). Can be useful when you need more verbose info.
        disable_xcpretty:       options[:disable_xcpretty],

        # Export method and team required for Xcode 8 provisioning
        export_method:          options[:export_method],
        export_team_id:         options[:team_id],
    )

  end

  ###### Distribution ###

  private_lane :distribute do |options|
    UI.message("Distributing app saved at: #{options[:ipa_path]}")
    begin
      if options[:upload_to_crashlytics]
          crashlytics(
              crashlytics_path:             "./Pods/Crashlytics",
              notes:                        "Please note this app is currently in development and not all of the functionality and features are live. We are continuing to update periodically, so keep downloading the latest version onto your smartphone.",
              groups:                       options[:crashlytics_group_aliases],
              debug:                        true,

              api_token:                    "e6b31c01a44c5028dbb203ac5e364c82f6e977cf",
              build_secret:                 "228d9378d5cbffab8219e51207c632b9b0f1320236acdbd918e7c03a52095967",
              ipa_path:                     options[:ipa_path]
          )
      end
    rescue => ex
      UI.error(ex)
    end
  end

  after_each do |lane, options|

  end

  after_all do |lane, options|

  end

  error do |lane, exception, options|
    UI.error "error: Missing attributes ..."
  end

  def usage (options, missing_attribute)
    UI.user_error!("Missing attributes ... : #{missing_attribute}")
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The bundle identifier of your app
# app_identifier "uk.co.britishgas.hive" 
# app_identifier "com.centrica.trial.hive" 
app_identifier "com.thirstysea" 

# Your Apple email address
apple_id "uday.pandey@bgch.co.uk" 

# Developer Portal Team ID
team_id "6WX233N4N3"  

# British Gas 
# https://developer.apple.com/account/#/overview/6WX233N4N3
# Centrica Plc
# https://developer.apple.com/account/#/overview/6QYB9GU99H
# team_id "6WX233N4N3"  
# team_id "6QYB9GU99H"  

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.67.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-unzip | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| highline                  | 1.7.10       |
| io-console                | 0.4.5        |
| tty-screen                | 0.6.3        |
| fastlane-plugin-unzip     | 1.0.1        |
</details>

*generated on:* **2017-11-30**
</details>

**Comment by Megatron1000** [comment]
This turned out to be missing commas in the config.rb file

**Comment by kylebrowning** [comment]
Im getting this as well. Which config.rb file?

**Comment by KrauseFx** [comment]
@kylebrowning Please submit a new issue and share your configuration files, thanks 👍

**Comment by fishercraigj** [comment]
@kylebrowning @KrauseFx - Where was this fixed?  Running into the same issue.

**Comment by kylebrowning** [comment]
I had a bad character in my fastlane file.
