### ISSUE TITLE
push_to_git_remote triggers another CI build

### ISSUE THREAD

**Issue by mikewdeasy** [fastlane/fastlane#1107]
Has anyone had an issue where they version bump, commit, and then push to git remote in their fastfile where it then causes github to send a webhook off and trigger another build?

I'm using Bamboo, it can pull the github repo or subscribe to a webhook.

**Comment by KrauseFx** [comment]
Yeah, if you configured your CI to run on every commits, this will end up in an endless loop I guess. What are you trying to achieve?

**Comment by mikewdeasy** [comment]
Basically just trying to have CI fire when we merge a feature branch into our sprint branch and then deploy to hockey.  I'll attach my Fastfile so you can see what's going on.  I might just cut out the version bump since it's not that big of a deal for betas.  I can include it on deploying our app store version and then just make app store fire manually.


[Fastfile.txt](https://github.com/fastlane/fastlane/files/92070/Fastfile.txt)

**Comment by jeeftor** [comment]
In bamboo when you define a repo- in the advanced settings is a regex to ignore commits

![screen shot 2016-01-18 at 4 19 57 pm](https://cloud.githubusercontent.com/assets/6491743/12403079/5742fe68-bdff-11e5-9bff-4c8e2fb463fb.png)

That regex tells it to ignore commits that match the message

**Comment by jeeftor** [comment]
I just typed up some notes and submitted to the documentation in #1132

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
