### ISSUE TITLE
Run multiple schemes in scan?

### ISSUE THREAD

**Issue by Drwalcore** [fastlane/fastlane#11081]
### New Issue Checklist

- [ ✔️] Updated fastlane to the latest version
- [ ✔️] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✔️ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✔️ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Is it possible to run two schemes in "scan" lane? Like with **device** and **devices**
For example instead of:
```ruby
scan(
 workspace: "ExampleWorkspace.xcworkspace",
 scheme: "SchemeA"
)
    
scan(
 workspace: "ExampleWorkspace.xcworkspace",
 scheme: "SchemeB"
)
```

I'd like to see that option

```ruby
scan(
  workspace: "Example.xcworkspace",
  schemes: ["SchemeA", "Scheme B"]
 )
```
I know that's won't affect building speed, but It could prevent code duplication :)

**Comment by ohayon** [comment]
Hey @Drwalcore, thanks for opening the issue! We currently do not support this functionality in _scan_. We would love to review a PR with this added if you want to take a crack at adding this ability? I am going to close this issue for now as a feature request, but feel free to continue discussion here or ask more questions and we can reopen it if necessary! 🚀
