### ISSUE TITLE
[sigh] --use_app_entitlements flag with in-app-purchases/ApplePay entitlement

### ISSUE THREAD

**Issue by Travolter** [fastlane/fastlane#11085]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to use fastlane sigh to resign a small Apple pay demo app for testing purposes. When using the `--use_app_entitlements` flag, the resulting IPA crashes when trying to use the apple pay button. The issue seems to be related to permissions/entitlements. When I compare the entitlements from the original binary and the resigned one, I notce the `in-app-purchases` key with the corresponding merchant value is missing.

This issue does not occur when not using the `--use_app_entitlements` flag. 

From my limiting understanding the blacklist that is provided in the `resign.sh` script removes this entitlement with the `--use_app_entitlement` flag. But there seems to be no real explanation as to why. The only thing I could find is a link to a buck issue regarding acceptance by the apple store. But to me it seems that this entitlement should still be in there for the app to run.

### Fastlane env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.60.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-12-01**
</details>

**Comment by ohayon** [comment]
Hey @Travolter, apologies for the issue youre having. Is it possible you could share the way that you are calling fastlane, whether thats directly from your command line or via a Fastfile? Thanks! 🚀

**Comment by Travolter** [comment]
I am running `fastlane sigh resign` from the command line (with and without the `--use_app_entitlement` flag).

**Comment by ohayon** [comment]
Could you share the output when you run in with `--verbose`?

**Comment by Travolter** [comment]
```
~/workspace/entitlements_tests » fastlane sigh resign --verbose ApplePayDemo.ipa                                                                                                                                                                                                                                                                      travolter@Mac-Andre
[09:44:18]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

 [2017-12-05 09:44:21.47]: Signing Identity: 09EB7A0048DE98E993A35F30409280709972688C
 [2017-12-05 09:44:24.91]: Path to provisioning file: /Users/travolter/Apple_pay_demo.mobileprovision
/Users/travolter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/sigh/lib/assets/resign.sh ApplePayDemo.ipa 09EB7A0048DE98E993A35F30409280709972688C -p /Users/travolter/Apple_pay_demo.mobileprovision       -v   ApplePayDemo.ipa
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
Print: Entry, ":CFBundleDisplayName", Does Not Exist
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
_floatsignTemp/Payload/PayDemo.app: replacing existing signature
_floatsignTemp/Payload/PayDemo.app: signed app bundle with Mach-O universal (armv7 arm64) [com.company.applepaydemo]
rm: _floatsignTemp/old-embedded-profile.plist: No such file or directory
Specified provisioning profile: '/Users/travolter/Apple_pay_demo.mobileprovision'
Original file: 'ApplePayDemo.ipa'
Certificate: '09EB7A0048DE98E993A35F30409280709972688C'
Output file name: 'ApplePayDemo.ipa'
Current bundle identifier is: 'com.company.applepaydemo'
New bundle identifier will be: 'com.company.applepaydemo'
Validating the new provisioning profile: /Users/travolter/Apple_pay_demo.mobileprovision
Profile app identifier prefix is 'ELFQ2L747V'
Profile team identifier is 'ELFQ2L747V'
Fixing nested app and extension references
Extracting entitlements from provisioning profile
Resigning application using certificate: '09EB7A0048DE98E993A35F30409280709972688C'
and entitlements from provisioning profile: /Users/travolter/Apple_pay_demo.mobileprovision
Repackaging as ApplePayDemo.ipa
Process complete
INFO [2017-12-05 09:45:16.16]: Successfully signed ApplePayDemo.ipa!
```

```
~/workspace/entitlements_tests » fastlane sigh resign --use_app_entitlements --verbose ApplePayDemo.ipa                                                                                                                                                                                                                                               travolter@Mac-Andre
[09:47:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

 [2017-12-05 09:47:06.78]: Signing Identity: 09EB7A0048DE98E993A35F30409280709972688C
 [2017-12-05 09:47:10.57]: Path to provisioning file: /Users/travolter/Apple_pay_demo.mobileprovision
/Users/travolter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/sigh/lib/assets/resign.sh ApplePayDemo.ipa 09EB7A0048DE98E993A35F30409280709972688C -p /Users/travolter/Apple_pay_demo.mobileprovision      --use-app-entitlements -v   ApplePayDemo.ipa
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
Print: Entry, ":CFBundleDisplayName", Does Not Exist
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
Executable=/Users/travolter/workspace/entitlemtens_tests/_floatsignTemp/Payload/PayDemo.app/PayDemo
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
_floatsignTemp/Payload/PayDemo.app: replacing existing signature
_floatsignTemp/Payload/PayDemo.app: signed app bundle with Mach-O universal (armv7 arm64) [com.company.applepaydemo]
Specified provisioning profile: '/Users/travolter/Apple_pay_demo.mobileprovision'
Original file: 'ApplePayDemo.ipa'
Certificate: '09EB7A0048DE98E993A35F30409280709972688C'
Output file name: 'ApplePayDemo.ipa'
Extract app entitlements: YES
Current bundle identifier is: 'com.company.applepaydemo'
New bundle identifier will be: 'com.company.applepaydemo'
Validating the new provisioning profile: /Users/travolter/Apple_pay_demo.mobileprovision
Profile app identifier prefix is 'ELFQ2L747V'
Profile team identifier is 'ELFQ2L747V'
Fixing nested app and extension references
Extracting entitlements from provisioning profile
Extracting entitlements from the app

App entitlements for _floatsignTemp/Payload/PayDemo.app:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>ELFQ2L747V.com.company.applepaydemo</string>
	<key>beta-reports-active</key>
	<true/>
	<key>com.apple.developer.in-app-payments</key>
	<array>
		<string>merchant.com.company</string>
	</array>
	<key>com.apple.developer.team-identifier</key>
	<string>ELFQ2L747V</string>
	<key>get-task-allow</key>
	<false/>
</dict>
</plist>
Patching profile entitlements with values from app entitlements
No value for 'com.apple.developer.associated-domains'
No value for 'com.apple.developer.healthkit'
No value for 'com.apple.developer.homekit'
No value for 'com.apple.developer.icloud-container-identifiers'
No value for 'com.apple.developer.icloud-services'
App entitlements value for key 'com.apple.developer.in-app-payments':
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>merchant.com.company</string>
</array>
</plist>
No value for 'com.apple.developer.networking.vpn.api'
No value for 'com.apple.developer.ubiquity-container-identifiers'
No value for 'com.apple.developer.ubiquity-kvstore-identifier'
No value for 'com.apple.external-accessory.wireless-configuration'
No value for 'com.apple.security.application-groups'
No value for 'inter-app-audio'
No value for 'keychain-access-groups'
Replacing old bundle ID 'com.company.applepaydemo' with new bundle ID 'com.company.applepaydemo' in patched entitlements
Removing blacklisted keys from patched profile
Removing blacklisted key: com.apple.developer.icloud-container-development-container-identifiers
Removing blacklisted key: com.apple.developer.icloud-container-environment
Removing blacklisted key: com.apple.developer.icloud-container-identifiers
Removing blacklisted key: com.apple.developer.icloud-services
Removing blacklisted key: com.apple.developer.restricted-resource-mode
Removing blacklisted key: com.apple.developer.ubiquity-container-identifiers
Removing blacklisted key: com.apple.developer.ubiquity-kvstore-identifier
Removing blacklisted key: inter-app-audio
Removing blacklisted key: com.apple.developer.homekit
Removing blacklisted key: com.apple.developer.healthkit
Removing blacklisted key: com.apple.developer.in-app-payments
Removing blacklisted key: com.apple.developer.maps
Removing blacklisted key: com.apple.external-accessory.wireless-configuration
Resigning application using certificate: '09EB7A0048DE98E993A35F30409280709972688C'
and patched entitlements:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>ELFQ2L747V.com.company.applepaydemo</string>
	<key>com.apple.developer.team-identifier</key>
	<string>ELFQ2L747V</string>
	<key>get-task-allow</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string>ELFQ2L747V.*</string>
	</array>
</dict>
</plist>
Repackaging as ApplePayDemo.ipa
Process complete
INFO [2017-12-05 09:47:20.68]: Successfully signed ApplePayDemo.ipa!
```

**Comment by Travolter** [comment]
Are there any updates on this issue?

**Comment by kapfab** [comment]
We also unfortunately noticed a few days ago that `use_app_entitlements` seems completely broken as soon as you use it for apps with some advanced capabilities.
I think there has been too much copy/paste of misunderstood code between the buck project and fastlane regarding blacklisted keys when merging entitlements.

As nobody seems to consider several recent issues and questions raised on this part of Fastlane, we forked it and are currently making the changes to make it actually work for much more use cases.
This is not easy to test (many capabilities with different ways of working on Apple side), so that might take a few days before it‘s almost ready.
And we won't be able to test all configurations with TestFlight, so we'll be happy if someone can give it a try before we make a PR…

**Comment by Travolter** [comment]
@kapfab I have looked at your fork and the commit you made (https://github.com/kapfab/fastlane/commit/1c74ae9293d4797eedda8a28db58fe78af584fbb). 

I have used this change on my Apple pay sample and it has fixed the issue.

How did you come to making this change? Do you have any more info as to why the blacklist is needed and why it needed to move?

**Comment by kapfab** [comment]
I've just made additional changes (https://github.com/kapfab/fastlane/commit/d49a2173012bb9f6c3d01c2baaafea0299dcf8c2) that should make everything safer for all types of capabilities, you'd better use it instead (though all this still needs to be tested and re-tested).
These changes make that entitlements from the app take precedence over the ones from the provisioning profiles (which seems to be a good idea at this point, we'll see if it still is after a few more tests).

For the story, the `use_app_entitlements` option merges provisioning entitlements with app entitlements (from its previous code signing) to generate a new entitlements file for re-signing.
This blacklist is actually needed because some entitlements included in provisioning profiles must not go to the final app entitlements to be used for resigning the app (Apple rules…).

The fact is that this blacklist actions were made after the merge of PP + App entitlements, and some keys in this list (but not all) seem to have been put in it as "should not be taken from the PP (but from the App Entitlements instead)". But they were actually completely removed as merge with App Entitlements was done beforehand.

But there are other cases where a key was historically present in this blacklist and got deleted for no clear reason some time ago, leading to apps getting additional (and invalid) entitlements from the provisioning profiles.

**Comment by janpio** [comment]
Nice work @kapfab. I assume we can expect a pull request with these changes in the near future to integrate these changes back into fastlane?

**Comment by kapfab** [comment]
Absolutely, though I can not guarantee this can be achieved before holiday season.
We really want to test these changes on real apps of ours to make sure this won't do more harm than good…

**Comment by kapfab** [comment]
After a few adaptations, our internal tests seem conclusive.
It's now time for the rest of the world to make sure PR #11346 makes `resign` work as they expect!

**Comment by Travolter** [comment]
Fixed here: https://github.com/fastlane/fastlane/pull/11346
