### ISSUE TITLE
appledoc action creates a Docset even when create_docset is set to false

### ISSUE THREAD

**Issue by s-hocking** [fastlane/fastlane#11083]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running an appledoc action, a Docset is always created (and the create_html parameter is ignored) even when passing the parameter `create_docset: false`. 

I think the easiest way to fix this is to have the appledoc action pass the parameter `--no-create-docset` when the `create_docset` option is set to false.

There is an easy workaround: add the following to your appledoc() command in your Fastfile:

```
options: "--no-create-docset"
```

##### Complete output when running fastlane, including the stack trace and command used

```
shocking@MacBook-Pro ~/Documents/SandboxApps/iOS/TestFramework 
$ fastlane test_appledocs --capture_output
[14:37:50]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-12-01 14:37:53.44]: Checking if there are any plugins that should be loaded...
INFO [2017-12-01 14:37:53.74]: Driving the lane 'test_appledocs' 🚀
INFO [2017-12-01 14:37:53.78]: ----------------------
INFO [2017-12-01 14:37:53.78]: --- Step: appledoc ---
INFO [2017-12-01 14:37:53.78]: ----------------------
INFO [2017-12-01 14:37:53.78]: Install using `brew install homebrew/boneyard/appledoc`
INFO [2017-12-01 14:37:53.79]: Generating documentation.
DEBUG [2017-12-01 14:37:53.79]: appledoc --output "./apple_docs" --project-name "Test Framework" --project-version "1.0" --project-company "Test Company" --company-id "com.testcompany" --create-html --exit-threshold "2" "TestFramework/TestFramework.h"
INFO [2017-12-01 14:37:53.79]: $ appledoc --output "./apple_docs" --project-name "Test Framework" --project-version "1.0" --project-company "Test Company" --company-id "com.testcompany" --create-html --exit-threshold "2" "TestFramework/TestFramework.h"
INFO [2017-12-01 14:37:54.27]: ▸ appledoc version: 2.2.1 (build 1334)
INFO [2017-12-01 14:37:54.27]: ▸ Generation step 4/4 failed: GBDocSetInstallGenerator failed generating output, aborting!
INFO [2017-12-01 14:37:54.27]: ▸ Documentation set was installed, but couldn't reload documentation within Xcode.
INFO [2017-12-01 14:37:54.27]: ▸ Expected end of line but found identifier.
INFO [2017-12-01 14:37:54.27]: Successfully generated documentation at path '/Users/shocking/Documents/SandboxApps/iOS/TestFramework/fastlane/README.md'
INFO [2017-12-01 14:37:54.28]: fastlane.tools finished successfully 🎉
WARN [2017-12-01 14:37:54.28]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-12-01 14:37:54.61]: Checking if there are any plugins that should be loaded...
```

### Captured Output

Command Used: `test_appledocs`
<details><summary>Output/Log</summary>

```


+------+----------+-------------+
|       fastlane summary        |
+------+----------+-------------+
| Step | Action   | Time (in s) |
+------+----------+-------------+
| 1    | appledoc | 0           |
+------+----------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
desc "Make appledocs for public headers only"
lane :test_appledocs do |options|
    appledoc(
        input: "TestFramework/TestFramework.h", 
        output: "./apple_docs",
        project_name: "Test Framework",
        project_version: "1.0",
        project_company: "Test Company",
        company_id: "com.testcompany",
        create_html: true,
        create_docset: false,
        install_docset: false
      )
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
</details>

*generated on:* **2017-12-01**
</details>

**Comment by janpio** [comment]
`create_docset` is default `false`:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/appledoc.rb#L143
This indicates to me that by default this wasn't applied by default when running `appledoc` in the past. 
Did `appledoc` (the underlying tool) change its behaviour?

**Comment by s-hocking** [comment]
The underlying `appledoc` tool hasn't been updated since 2015. Reading the issues raised against the project it seems like this is a [known issue](https://github.com/tomaz/appledoc/issues/574).

**Comment by janpio** [comment]
Okay, so it would actually make sense to change the fastlane action to also use this workaround to achieve the functionality that was originally expected, correct?

@alexmx seems to have done all the work back then to add this action. Do you want to have a look at this?

**Comment by s-hocking** [comment]
Yep, I think that sounds like a good approach. I think the fastlane action should quietly do the workaround, at least until the Appledoc tool is fixed.

I'm happy to have a look at it!

**Comment by alexmx** [comment]
@s-hocking Thanks for taking a look! 

Interesting to see that people still use `appledoc` considering that it is not really maintained by the author.

**Comment by s-hocking** [comment]
Reading the [`appledoc` documentation again](https://github.com/tomaz/appledoc/wiki/appledoc-docs-examples-advanced#create-html-only), it seems like the current behaviour is intended:

>By adding --no-create-docset you instruct appledoc to create HTML and then quit. Using this command line, you'll find HTML files in ~/help/html. This option is useful if you don't need documentation set or want to use external tools for generating it.

With this in mind, I'm just going to add the `--no-create-docset` as an available parameter to the fastlane appledoc action.
