### ISSUE TITLE
Keep TouchID Settings for each Snapshot run

### ISSUE THREAD

**Issue by micnguyen** [fastlane/fastlane#11082]
### New Issue Checklist

- [✔️ ] Updated fastlane to the latest version
- [✔️ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✔️ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✔️ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I run unit tests that rely on the device's biometrics enrolment settings. In the simulator, if I enrol with Touch ID and then run Snapshot, it seems to remove the Touch ID enrolment settings. The tests fail and if I boot up the simulator from XCode, the enrolment switch flag in the Hardware menu is off. I would like it to retain my Touch ID enrolment settings in lieu of not being able to set it via command line as mentioned here: https://github.com/fastlane/fastlane/issues/2491 I can't see any flags that are resetting the simulator anywhere. 

##### Complete output when running fastlane, including the stack trace and command used

* Not needed. Shows tests that fail because of lack of touch id enrolment. *

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.12.6                                                  |
| Ruby                        | 2.3.4                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.13.6 (Apple Git-96)                        |
| Installation Source         | ~/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G1036)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.4/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 9.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
platform :ios do

  before_all do |lane, options|
    cocoapods(
      use_bundle_exec: true
    )
    ENV['CI_BUILD_NUMBER'] = options[:build_number]
    ENV['IPA_FULL_FILE']= "XXXX" + "_" + get_version_number + "b" + ENV['CI_BUILD_NUMBER'] + ".ipa"
  end

  desc "Builds Develop App & Uploads to Hockey"
  lane :build_upload_develop do |options|

    increment_build_number(
      build_number: ENV['CI_BUILD_NUMBER']
    )
    cert(
      development: true,
      username: 'XXX',
      team_id: ENV['DID_APPLE_DEV_TEAM_ID'],
    )

    sigh(
      force: true,
      development: true,
      username: 'XXX',
      team_id: ENV['DID_APPLE_DEV_TEAM_ID'],
      app_identifier: ENV['DEV_BUNDLE_ID']
    )

    build_develop
    upload_hockey_dev
  end

  desc "Builds Develop App & Uploads to Hockey RC Equivalent App"
  lane :build_upload_rc do |options|

    increment_build_number(
      build_number: ENV['CI_BUILD_NUMBER']
    )
    cert(
      development: true,
      team_id: ENV['DID_APPLE_DEV_TEAM_ID'],
      username: 'XXXX'
    )

    sigh(
      team_id: ENV['DID_APPLE_DEV_TEAM_ID'],
      force: true,
      development: true,
      username: 'XXXX',
      app_identifier: ENV['DEV_BUNDLE_ID']
    )

    build_develop
    upload_hockey_rc
  end

  desc "Builds Prod App & Uploads to iTunesConnect Testflight"
  lane :build_upload_prod do |options|

    # enables uploads behind AP firewall
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

    increment_build_number(
      build_number: ENV['CI_BUILD_NUMBER']
    )

    cert(
      username: 'XXXX',
      team_id: ENV['DID_APPLE_DEV_TEAM_ID']
    )

    sigh(
      username: 'XXXX',
      app_identifier: ENV['PROD_BUNDLE_ID'],
      team_id: ENV['DID_APPLE_DEV_TEAM_ID']
    )

    build_prod
    testflight(
      username: 'XXXX',
      team_id: ENV['DID_ITC_TEAM_ID'],
      app_identifier: ENV['PROD_BUNDLE_ID'],
      ipa: 'build_artefacts/' + ENV['IPA_FULL_FILE'],
      skip_waiting_for_build_processing: true
    )
  end

  desc "Runs unit tests"
  lane :unit_tests do |options|
    scan(
      scheme: ENV['DEV_SCHEME'],
      clean: true,
      code_coverage: true,
      output_types: "html",
      output_directory: "build_artefacts/unit_tests",
      slack_url: ENV['SLACK_URL'],
      slack_message: "Unit Test Results for branch: " + git_branch + " on pipeline: #" + ENV['CI_BUILD_NUMBER'] + " author: " + last_git_commit[:author] + " message: " + last_git_commit[:message],
      slack_only_on_failure: true,
      destination: 'id=0c9eca83c15da8f48e4d1002f47ef38d205473f9' # Run on attached iPhone SE to CI Box
    )
  end

  desc "Quick snapshot of UI tests (UI Snapshot + xcpretty Test Results)"
  lane :ui_tests_quick do
    snapshot(
      scheme: "XXXX",
      devices: ["iPhone 7"],
      output_directory: "build_artefacts/ui_tests",
      xcpretty_args: '--report html --output build_artefacts/ui_tests/test_report.html -t',
      clear_previous_screenshots: true,
      output_simulator_logs: true,
      languages: ["en-AU"],
      number_of_retries: 0,
      # stop_after_first_error: true
      # reinstall_app: true,
      # erase_simulator: true,
      # configuration: "Debug"
    )
  end

  desc "Builds the develop scheme"
  lane :build_develop do |options|
    gym(
      scheme: ENV['DEV_SCHEME'],
      export_method: "development",
      clean: true,
      output_directory: "build_artefacts/",
      output_name: ENV['IPA_FULL_FILE'],
      configuration: "Debug"
    )
  end

  desc "Builds the Prod App with the proper signing"
  lane :build_prod do |options|
    gym(
      scheme: ENV['PROD_SCHEME'],
      export_method: "app-store",
      clean: true,
      output_directory: "build_artefacts/",
      output_name: ENV['IPA_FULL_FILE'],
      configuration: "Release",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          ENV['PROD_BUNDLE_ID'] => ENV['PROD_PROVISIONING_PROFILE'],
        }
      }
    )
  end

  private_lane :upload_hockey_dev do
    upload_hockey(
      ipa: ENV['IPA_FULL_FILE'],
      api_token: ENV['HOCKEY_DEV_API_TOKEN'],
      app_identifier: ENV['HOCKEY_DEV_APP_ID'],
      release_notes: last_git_commit[:message]
    )
  end

  private_lane :upload_hockey_rc do
    upload_hockey(
      ipa: ENV['IPA_FULL_FILE'],
      api_token: ENV['HOCKEY_RC_API_TOKEN'],
      app_identifier: ENV['HOCKEY_RC_APP_ID'],
      release_notes: last_git_commit[:message]
    )
  end

  private_lane :upload_hockey do |options|
    hockey(
      api_token: options[:api_token],
      public_identifier: options[:app_identifer],
      notes: options[:release_notes],
      ipa: "build_artefacts/" + ENV['IPA_FULL_FILE'],
      notify: '0' # Don't send out an email on each upload
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.63.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

**Comment by janpio** [comment]
Does this setting survive the simulator being restarted?

**Comment by joshdholtz** [comment]
@micnguyen Heyyyy 👋 So yeah, this is not **super** possible right now (in a nice clean way) since the "Touch ID" -> "Enroll" option does get reset whenever a simulator gets restarted.

## Solution 1 (might be a little sketch)
`appium` does do allow for this kind of functionality but it looks like this might be done using AppleScript (based on the documentation they have) - https://appium.readthedocs.io/en/stable/en/commands/device/simulator/toggle-touch-id-enrollment/
You might be able to make use fo this or roll your own AppleScript to do the same thing.

## Solution 2 (probably the cleanest)
I would personally write some mock Touch ID logic to execute while testing/snapshotting. Its the least hacky and most stable. I know its not ideal but it should work 🙃
