### ISSUE TITLE
Having two Screengrabfile s?

### ISSUE THREAD

**Issue by Macarse** [fastlane/fastlane#11091]
### New Issue Checklist

- [✔️ ] Updated fastlane to the latest version
- [✔️ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✔️ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✔️ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am using a `Screengrabfile` to run play store screenshots.
Now I would like to use a second `Screengrabfile` to get screenshots for something else.

I couldn't find a way to specify the `Screengrabfile` to use. is that possible?

**Comment by janpio** [comment]
How are you running the command?

**Comment by Macarse** [comment]
@janpio `fastlane screengrab` for the store screenshots.
I was hoping to find something like: `fastlane screengrab -i Screengrabfile`

**Comment by janpio** [comment]
This sounds like a usecase for a `Fastfile` - and you just define two lanes (e.g. `playstore` and `other`) that both execute `screengrab` internally and supply the content of your `Screengrabfile` as parameters. Then run `fastlane playstore` and `fastlane other` to execute them.

Can you post the content of your current `Screengrabfile`?

**Comment by Macarse** [comment]
mmm can you show me an example of how to do that?
My playstore `screengrabfile` is:

```
clear_previous_screenshots true

app_package_name 'com.xxx'
use_tests_in_packages ['com.xx.screenshots.playstore']

app_apk_path 'production-debug.apk'
tests_apk_path 'production-debug-androidTest.apk'

locales ['cs-CZ', 'da-DK', 'de-DE', 'en-US', 'es-ES', 'fi-FI', 'fr-FR', 'it-IT', 'nl-NL', 'no-NO', 'pl-PL', 'pt-PT', 'sv-SE',	'zh-CN']

test_instrumentation_runner 'com.xxx.EspressoTestRunner'
```

**Comment by janpio** [comment]
See here for an example lane:
https://docs.fastlane.tools/actions/screengrab/#3-examples
https://docs.fastlane.tools/getting-started/android/screenshots/#use-in-fastfile
(Confusing right now because of a migration: The "action" `screengrab` is also called `capture_android_screenshots` because of a recent rename (to simplify the naming))

Setup of _fastlane_ is here:
https://docs.fastlane.tools/getting-started/android/setup/

A random finished `Fastfile` looks like this:
https://github.com/fastlane/examples/blob/master/Shop.com/Fastfile

Less difficult than it sounds.

**Comment by Macarse** [comment]
I will give it a try. Thanks!

**Comment by Macarse** [comment]
@janpio your recommendation worked great.

I ended up using: 
```
desc "Take screenshots for translations"
  lane :translations_screenshots do
    screengrab(...)
```

`capture_android_screenshots` gave me an error

**Comment by janpio** [comment]
Nice :)

Oh, could you report that error as a new issue? `screengrab` and that one should be identical. If they are not, something is going wrong that should be fixed. Thanks.

**Comment by Macarse** [comment]
it just says `Could not find action, lane or variable 'capture_android_screenshots'. Check out the documentation for more details: https://docs.fastlane.tools/actions`

I am running: `fastlane version 2.28.3`

**Comment by janpio** [comment]
Oh, that was added in the current 2.68.0 - all good then.
You should upgrade, painless but useful ;)
