### ISSUE TITLE
fastline-init is crashing after trying to set up deliver

### ISSUE THREAD

**Issue by andrewsardone** [fastlane/fastlane#1109]
On a new project, I am running `fastlane init`, and immediately after the 'deliver` set up fastlane crashes.

Per the instructions, I am attaching the crash report number: `ba908018bae85e302554ff1ac853f264`

Please let me know if there's any more information I can provide – thanks!

**Comment by KrauseFx** [comment]
Could you update `spaceship` using `gem update spaceship` or `bundle update` if you use `bundler` and try again? I pushed a fix a few hours ago :+1:

**Comment by andrewsardone** [comment]
![giphy](https://cloud.githubusercontent.com/assets/14554/12352723/bbde15b6-bb56-11e5-893c-51929d3e4052.gif)

Awesome! I ran `bundle update`, grabbed `spaceship (0.19.1)`, and `fastlane init` completed! Thanks so much!

I have been following the fastlane tools for some time, but haven't used them on a real project. I'm hoping to change that today!

**Comment by KrauseFx** [comment]
Awesome, enjoy @andrewsardone and let us know how it goes! :+1:

**Comment by KrauseFx** [comment]
I hope you can soon :rocket: :rocket: :rocket:
