### ISSUE TITLE
rename "zip" to "compress" and use ditto for efficient packaging

### ISSUE THREAD

**Issue by DivineDominion** [fastlane/fastlane#11095]
(Formerly "Support other compression algorithms in zip command")

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using the `fastlane zip` action for my macOS app bundle, I noticed the resulting zip was about 26 MB, compared to the 14 MB Finder's "Compress" command produces. Since the archives is used for beta deployment, I tried to reduce the file size and figured out that Finder really uses something like this:

    ditto -c -k --sequesterRsrc --keepParent AppBundle.app/ AppBundle.zip

Since no new actions are accepted, I was wondering if I should do something at all, and if so, what. The `ditto` command seems to produce files that are not supported by every publisher or platform, so people will want to keep using the regular Zip algorithm. At least other Mac developers who do most deployment on their own, though, could want to shave off some bytes. 

Here's the plan I came up with and which I'd like to discuss, if there's interest in this:

- rename `zip` to `compress` and leave an alias
- add options to the `compress` action to choose a different compression algorithm (one of `[:zip, :ditto]`, but could possibly be extended for `:bzip` and similar to support `tar.bz` compression)

Will gladly create a PR if fastlane maintainers and the community think this is a worthwile change.

**Comment by janpio** [comment]
That sounds like a pretty good candidate for a fastlane plugin!

That way the actual logic could be implemented and tested without any commitment needed from the core contributors, and if it turns out to be super popular and used very often it can maybe still be integrated to the core action further down the line.

You can read more about creating a plugin here: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by milch** [comment]
What about just adding the option to use ditto to the zip action? It still produces a zip archive, so it's not a misnomer. 

If you want maximum space saving you could go the route of writing a plugin though, but at that point you don't need to rely on zip at all. IIRC 7zip offers the absolute best compression ratio, so you might as well write a plugin for 7zip

**Comment by janpio** [comment]
Right, as it still produces a valid "zip" file nothing speaks against adding a `method: ditto` param that defaults to `zip` if unset.

**Comment by DivineDominion** [comment]
Whoops, didn't notice the edit @janpio -- will make the change and propose a PR. Renaming "zip" to "compress" is probably not that hot, right? :)

**Comment by milch** [comment]
That's actually not a bad idea I would say. Rename to compress, and add a `zip` alias that would set  `method` parameter to `:zip`. I like it
