### ISSUE TITLE
Getting error when trying to upload a mac build to HockeyApp:  "Is a directory @ io_fread" 

### ISSUE THREAD

**Issue by Palleas** [fastlane/fastlane#1110]
Hi, 

I have a simple mac application that I'm trying to upload to HockeyApp for updates. Here is my 
`FastFile`: 
```ruby
fastlane_version "1.50.0"

default_platform :mac

platform :mac do
  before_all do
    carthage
  end

  lane :beta do
    increment_version_number(:bump_type => "minor")
    gym(:scheme => "Editor")
    hockey(:api_token => "...")
  end
end
```

I'm getting an error which has the number "f755167b4d3819a9f2dfb56fadbc8dc4":

    FATAL [2016-01-14 22:01:38.59]: Is a directory @ io_fread - /Users/Romain/Projects/Editor/Editor.app

Am I doing something wrong? I tried manually zipping the file and setting the `:ipa` param but I'm getting
the same error.

Thanks!

**Comment by vpolouchkine** [comment]
Yeah, for Mac apps you need to zip the .app file. What did you set the :ipa parameter when after you zipped?

**Comment by Palleas** [comment]
This is the code I use when I zip manually: 

```ruby
    increment_version_number(:bump_type => "minor")
    gym(:scheme => "Editor")

    app_path = ENV[SharedValues::IPA_OUTPUT_PATH.to_s]
    dir = File.dirname(ENV[SharedValues::IPA_OUTPUT_PATH.to_s])
    app_filename = File.basename(app_path)
    zip_path = dir + "/" + File.basename(app_path, ".app") + ".zip"
    Actions.sh("pushd #{dir} && zip -r #{zip_path} #{app_filename}/* && popd")
    hockey(:api_token => "5fcef81dbdfd44f7a9fde49c16f5fe3a", :ipa => zip_path)
```

The zip is valid, if I unzip it manually, my Editor.app is here and I can launch it.

**Comment by vpolouchkine** [comment]
Can you try removing ".zip" from zip_path?

**Comment by Palleas** [comment]
Getting the same error. Is there a way to have the full stack trace to see where the issue comes from?

**Comment by alickbass** [comment]
I also get this error

**Comment by TKBurner** [comment]
@alickbass Thanks for reaching out. Can you give me your fastfile? And the full output when you run the affected lane?

Thanks!

**Comment by alickbass** [comment]
So I found the reason for that. If you run `gym` and then run `hockey` on mac platform, you have to specify both `:ipa` and `dsym:` as as far I understood, `gym` sets `:DSYM_OUTPUT_PATH` and it is used by `hockey`.

**Comment by TKBurner** [comment]
@alickbass Thanks for letting me know. I'm glad to hear you are up and running. I'm going to have the team take a look at the central issue and have them think about making these required. I am going to close out this support issue for housekeeping purposes. Feel free to ping if you run into this problem again.

Thank!
