### ISSUE TITLE
No JAR signatures

### ISSUE THREAD

**Issue by sathish-ajira** [fastlane/fastlane#11111]
While uploading apk to playstore using `fastlane beta`, It shows following error. 
` [!] Google Api Error: apkInvalidSignature: APK signature is invalid or does not exist. Error from apksigner: ERROR: JAR_SIG_NO_SIGNATURES: No JAR signatures `
  My app gradle file

` signingConfigs {
 config {
            keyAlias 'key0'
            keyPassword 'S@thish22'
            storeFile file('/Users/sathish/Sathish/Android/androidKeystore.jks')
            storePassword 'S@thish22'
        }
    }`

**Comment by ohayon** [comment]
Hey @fastlane/android folks, do any of you have some knowledge around this? 🐙

**Comment by RishabhTayal** [comment]
I am getting the same error when signing with `Release` `build_type`.

**Comment by RishabhTayal** [comment]
I just added `gradle(task: 'clean')` before my `gradle` command in the lane and now it works! Here is the complete lane.

```
desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code
    gradle(task: 'clean')
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "keystore",
        "android.injected.signing.store.password" => "password",
        "android.injected.signing.key.alias" => "alias",
        "android.injected.signing.key.password" => "password",
        })
    upload_to_play_store(json_key: 'play-store.json', track: 'beta')
  end
```

**Comment by janpio** [comment]
Just a note for future readers: A more probable reason is that your app is not signed at all or you are not correctly signing the file. Check StackOverflow for your exact error message.
