### ISSUE TITLE
undefined method `each' for #<Enumerable::Enumerator:0x007f9c8b6d87b8>

### ISSUE THREAD

**Issue by Wojcik** [fastlane/fastlane#11114]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
### Issue Description
Trying to iterate over objects in an amazon bucket

```
bucket = s3.bucket('bucket_name')

objects = bucket.objects

return objects.select do |icon| 
    ((params[:app_release_time] <=> icon.last_modified) == -1) && icon.key.start_with?('production') && icon.key.include?('appLogo')
end
```

Code works when running it in bash directly just in rb file like `ruby test.rb`

```
$ which ruby
/usr/local/bin/ruby
$ whereis ruby
/usr/bin/ruby
$ /usr/local/bin/ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

And it fails when it placed in a Fastlane action with next error

##### Complete output when running fastlane, including the stack trace and command used

<details><summary>✅Stack trace ✅</summary>
### Stack
/usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.11.0/lib/aws-sdk-core/resources/collection.rb:56:in `each': [!] undefined method `each' for #<Enumerable::Enumerator:0x007f9c8b6d87b8> (NoMethodError)
	from /Users/Aaaa/Projects/project/fastlane/actions/amazon_get_app_icons.rb:21:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from FastlaneContainerApp:201:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.68.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
<\details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:
**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                     | Version      |
| --------------------------------------- | ------------ |
| did_you_mean                            | 1.0.2        |
| slack-notifier                          | 1.5.1        |
| CFPropertyList                          | 2.3.5        |
| claide                                  | 1.0.2        |
| colored2                                | 3.1.2        |
| nanaimo                                 | 0.2.3        |
| xcodeproj                               | 1.5.3        |
| rouge                                   | 2.0.7        |
| xcpretty                                | 0.2.8        |
| terminal-notifier                       | 1.8.0        |
| plist                                   | 3.3.0        |
| addressable                             | 2.5.2        |
| multipart-post                          | 2.0.0        |
| word_wrap                               | 1.0.0        |
| public_suffix                           | 2.0.5        |
| tty-screen                              | 0.6.3        |
| babosa                                  | 1.0.2        |
| colored                                 | 1.2          |
| highline                                | 1.7.10       |
| commander-fastlane                      | 4.4.5        |
| excon                                   | 0.59.0       |
| faraday                                 | 0.13.1       |
| unf_ext                                 | 0.0.7.4      |
| unf                                     | 0.1.4        |
| domain_name                             | 0.5.20170404 |
| http-cookie                             | 1.0.3        |
| faraday-cookie_jar                      | 0.0.6        |
| fastimage                               | 2.1.0        |
| gh_inspector                            | 1.0.3        |
| mini_magick                             | 4.5.1        |
| multi_json                              | 1.12.2       |
| multi_xml                               | 0.6.0        |
| security                                | 0.1.3        |
| xcpretty-travis-formatter               | 1.0.0        |
| dotenv                                  | 2.2.1        |
| bundler                                 | 1.16.0       |
| faraday_middleware                      | 0.12.2       |
| declarative                             | 0.0.10       |
| declarative-option                      | 0.1.0        |
| representable                           | 3.0.4        |
| mime-types-data                         | 3.2016.0521  |
| mime-types                              | 3.1          |
| little-plugger                          | 1.1.4        |
| logging                                 | 2.2.2        |
| jwt                                     | 2.1.0        |
| memoist                                 | 0.16.0       |
| os                                      | 0.9.6        |
| signet                                  | 0.8.1        |
| googleauth                              | 0.6.2        |
| httpclient                              | 2.8.3        |
| google-api-client                       | 0.13.6       |
| json                                    | 2.1.0        |
| io-console                              | 0.4.6        |
| rubyzip                                 | 1.2.1        |
| unicode-display_width                   | 1.3.0        |
| terminal-table                          | 1.8.0        |
| jmespath                                | 1.3.1        |
| aws-partitions                          | 1.44.0       |
| aws-sigv4                               | 1.0.2        |
| aws-sdk-core                            | 3.11.0       |
| aws-sdk-acm                             | 1.2.0        |
| aws-sdk-apigateway                      | 1.7.0        |
| aws-sdk-alexaforbusiness                | 1.0.0        |
| aws-sdk-appstream                       | 1.2.0        |
| aws-sdk-appsync                         | 1.0.0        |
| aws-sdk-applicationautoscaling          | 1.6.0        |
| aws-sdk-applicationdiscoveryservice     | 1.0.0        |
| aws-sdk-athena                          | 1.0.0        |
| aws-sdk-autoscaling                     | 1.4.0        |
| aws-sdk-batch                           | 1.3.0        |
| aws-sdk-budgets                         | 1.3.0        |
| aws-sdk-cloud9                          | 1.0.0        |
| aws-sdk-clouddirectory                  | 1.0.0        |
| aws-sdk-cloudformation                  | 1.3.0        |
| aws-sdk-cloudfront                      | 1.1.0        |
| aws-sdk-cloudhsm                        | 1.3.0        |
| aws-sdk-cloudhsmv2                      | 1.1.0        |
| aws-sdk-cloudsearch                     | 1.0.0        |
| aws-sdk-cloudsearchdomain               | 1.0.0        |
| aws-sdk-cloudtrail                      | 1.0.0        |
| aws-sdk-cloudwatch                      | 1.2.0        |
| aws-sdk-cloudwatchevents                | 1.1.0        |
| aws-sdk-cloudwatchlogs                  | 1.2.0        |
| aws-sdk-codebuild                       | 1.4.0        |
| aws-sdk-codecommit                      | 1.2.0        |
| aws-sdk-codedeploy                      | 1.1.0        |
| aws-sdk-codepipeline                    | 1.1.0        |
| aws-sdk-codestar                        | 1.1.0        |
| aws-sdk-cognitoidentity                 | 1.0.0        |
| aws-sdk-cognitoidentityprovider         | 1.1.0        |
| aws-sdk-cognitosync                     | 1.0.0        |
| aws-sdk-comprehend                      | 1.0.0        |
| aws-sdk-configservice                   | 1.4.0        |
| aws-sdk-costexplorer                    | 1.0.0        |
| aws-sdk-costandusagereportservice       | 1.0.0        |
| aws-sdk-dax                             | 1.0.0        |
| aws-sdk-datapipeline                    | 1.0.0        |
| aws-sdk-databasemigrationservice        | 1.3.0        |
| aws-sdk-devicefarm                      | 1.2.0        |
| aws-sdk-directconnect                   | 1.1.0        |
| aws-sdk-directoryservice                | 1.0.0        |
| aws-sdk-dynamodb                        | 1.3.0        |
| aws-sdk-dynamodbstreams                 | 1.0.0        |
| aws-sdk-ec2                             | 1.21.0       |
| aws-sdk-ecr                             | 1.2.0        |
| aws-sdk-ecs                             | 1.6.0        |
| aws-sdk-efs                             | 1.0.0        |
| aws-sdk-emr                             | 1.1.0        |
| aws-sdk-elasticache                     | 1.3.0        |
| aws-sdk-elasticbeanstalk                | 1.2.0        |
| aws-sdk-elasticloadbalancing            | 1.1.0        |
| aws-sdk-elasticloadbalancingv2          | 1.6.0        |
| aws-sdk-elastictranscoder               | 1.0.0        |
| aws-sdk-elasticsearchservice            | 1.2.0        |
| aws-sdk-firehose                        | 1.1.0        |
| aws-sdk-gamelift                        | 1.1.0        |
| aws-sdk-glacier                         | 1.5.0        |
| aws-sdk-glue                            | 1.2.0        |
| aws-sdk-greengrass                      | 1.2.0        |
| aws-sdk-guardduty                       | 1.0.0        |
| aws-sdk-health                          | 1.0.0        |
| aws-sdk-iam                             | 1.3.0        |
| aws-sigv2                               | 1.0.1        |
| aws-sdk-importexport                    | 1.0.0        |
| aws-sdk-inspector                       | 1.1.0        |
| aws-sdk-iot                             | 1.1.0        |
| aws-sdk-iotdataplane                    | 1.0.0        |
| aws-sdk-iotjobsdataplane                | 1.0.0        |
| aws-sdk-kms                             | 1.3.0        |
| aws-sdk-kinesis                         | 1.1.0        |
| aws-sdk-kinesisanalytics                | 1.1.0        |
| aws-sdk-kinesisvideo                    | 1.0.0        |
| aws-sdk-kinesisvideoarchivedmedia       | 1.0.0        |
| aws-sdk-kinesisvideomedia               | 1.0.0        |
| aws-sdk-lambda                          | 1.2.0        |
| aws-sdk-lambdapreview                   | 1.0.0        |
| aws-sdk-lex                             | 1.2.0        |
| aws-sdk-lexmodelbuildingservice         | 1.2.0        |
| aws-sdk-lightsail                       | 1.3.0        |
| aws-sdk-mq                              | 1.0.0        |
| aws-sdk-mturk                           | 1.1.0        |
| aws-sdk-machinelearning                 | 1.0.0        |
| aws-sdk-marketplacecommerceanalytics    | 1.0.0        |
| aws-sdk-marketplaceentitlementservice   | 1.0.0        |
| aws-sdk-marketplacemetering             | 1.0.0        |
| aws-sdk-mediaconvert                    | 1.0.0        |
| aws-sdk-medialive                       | 1.0.0        |
| aws-sdk-mediapackage                    | 1.0.0        |
| aws-sdk-mediastore                      | 1.0.0        |
| aws-sdk-mediastoredata                  | 1.0.0        |
| aws-sdk-migrationhub                    | 1.0.0        |
| aws-sdk-mobile                          | 1.0.0        |
| aws-sdk-opsworks                        | 1.1.0        |
| aws-sdk-opsworkscm                      | 1.2.0        |
| aws-sdk-organizations                   | 1.7.0        |
| aws-sdk-pinpoint                        | 1.2.0        |
| aws-sdk-polly                           | 1.4.0        |
| aws-sdk-pricing                         | 1.0.0        |
| aws-sdk-rds                             | 1.8.0        |
| aws-sdk-redshift                        | 1.1.0        |
| aws-sdk-rekognition                     | 1.2.0        |
| aws-sdk-resourcegroups                  | 1.0.0        |
| aws-sdk-resourcegroupstaggingapi        | 1.0.0        |
| aws-sdk-route53                         | 1.5.0        |
| aws-sdk-route53domains                  | 1.1.0        |
| aws-sdk-s3                              | 1.8.0        |
| aws-sdk-ses                             | 1.4.0        |
| aws-sdk-sms                             | 1.0.0        |
| aws-sdk-sns                             | 1.1.0        |
| aws-sdk-sqs                             | 1.3.0        |
| aws-sdk-ssm                             | 1.5.0        |
| aws-sdk-swf                             | 1.0.0        |
| aws-sdk-sagemaker                       | 1.1.0        |
| aws-sdk-sagemakerruntime                | 1.0.0        |
| aws-sdk-serverlessapplicationrepository | 1.0.0        |
| aws-sdk-servicecatalog                  | 1.1.0        |
| aws-sdk-shield                          | 1.1.0        |
| aws-sdk-simpledb                        | 1.0.0        |
| aws-sdk-snowball                        | 1.1.0        |
| aws-sdk-states                          | 1.2.0        |
| aws-sdk-storagegateway                  | 1.2.0        |
| aws-sdk-support                         | 1.0.0        |
| aws-sdk-translate                       | 1.0.0        |
| aws-sdk-waf                             | 1.3.0        |
| aws-sdk-wafregional                     | 1.3.0        |
| aws-sdk-workdocs                        | 1.1.0        |
| aws-sdk-workspaces                      | 1.0.0        |
| aws-sdk-xray                            | 1.1.0        |
| aws-sdk-resources                       | 3.8.0        |
| aws-sdk                                 | 3.0.1        |
| mini_portile2                           | 2.3.0        |
| nokogiri                                | 1.8.1        |
</details>
*generated on:* **2017-12-05**
</details>

**Comment by ohayon** [comment]
Hey @Wojcik, apologies for the issue youre having. This is pretty interesting. 

My first thought is: is there any chance that when you are running fastlane you are unsetting or overwriting your AWS credential environment variables? You could check this out by just adding a `puts `env`` in your Fastfile. 🐙

**Comment by Wojcik** [comment]
I beleive that it's not connected to credentials because I'm getting objects from amazon buket and can access bucket properties etc. But as soon as I try to enumerate Aws::S3::ObjectSummary::Collection entity fastlane crashes here
/Users/Ap/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-3.11.0/lib/aws-sdk-core/resources/collection.rb:56:in `each': [!] undefined method `each' for #<Enumerable::Enumerator:0x007fc3fcf83a50> even though there is a such method in collection.rb 
`      # @return [Enumerator<Band>]
      def each(&block)
        enum = Enumerator.new do |y|
          batch_enum.each do |batch|
            batch.each do |band|
              y.yield(band)
            end
          end
        end
        enum.each(&block) if block
        enum
      end`

**Comment by Wojcik** [comment]
This is strange
        objects = bucket.objects
        puts objects.class => Aws::S3::ObjectSummary::Collection (which is right)
        puts objects.each.class => Enumerable::Enumerator (also correct)
        puts objects.each.methods.sort => (! != !~ <=> == === =~ __id__ __send__ agree ask choose class clone dclone define_singleton_method display dup enum_for eql? equal? extend freeze frozen? gem get_binding hash inspect instance_eval instance_exec instance_of? instance_variable_defined? instance_variable_get instance_variable_set instance_variables is_a? itself kind_of? method methods nil? object_id or_ask private_methods protected_methods psych_to_yaml public_method public_methods public_send remove_instance_variable respond_to? say send singleton_class singleton_method singleton_methods taint tainted? tap to_enum to_json to_s to_yaml to_yaml_properties trust untaint untrust untrusted?) And this looks wrong

**Comment by ohayon** [comment]
Hey @Wojcik, this is pretty strange. And just to confirm here, you have fastlane installed via rubygems? What happens if you run similar code to test `each` in an `irb` session in the same directory from which you are executing fastlane?

**Comment by Wojcik** [comment]
Hey @ohayon . Yes, fastlane installed via rubygems, today I tried to reinstall fastlane in rvm environment - same error.

Results from irb session
<details>
2.4.1 :002 > require 'aws-sdk'
 => true
2.4.1 :003 > s3 = Aws::S3::Resource.new(access_key_id:'*****', secret_access_key: '******', region:'eu-central-1')
 => #<Aws::S3::Resource:0x007f90753df790 @client=#<Aws::S3::Client>>
2.4.1 :004 > bucket = s3.bucket(*****')
 => #<Aws::S3::Bucket:0x007f9075c528f0 @name="*****", @data=nil, @client=#<Aws::S3::Client>>
2.4.1 :005 > objects = bucket.objects
 => #<Aws::S3::ObjectSummary::Collection:0x007f9075c49ae8 @batches=#<Enumerator: #<Enumerator::Generator:0x007f9075c49b60>:each>, @limit=nil, @size=nil>
2.4.1 :006 > puts objects.each.methods.sort
!
!=
!~
<=>
==
===
=~
__id__
__send__
all?
any?
chunk
chunk_while
class
clone
collect
collect_concat
count
cycle
dclone
define_singleton_method
detect
display
drop
drop_while
dup
each
each_cons
each_entry
each_slice
each_with_index
each_with_object
entries
enum_for
eql?
equal?
extend
feed
find
find_all
find_index
first
flat_map
freeze
frozen?
grep
grep_v
group_by
hash
include?
inject
inspect
instance_eval
instance_exec
instance_of?
instance_variable_defined?
instance_variable_get
instance_variable_set
instance_variables
is_a?
itself
kind_of?
lazy
map
max
max_by
member?
method
methods
min
min_by
minmax
minmax_by
next
next_values
nil?
none?
object_id
one?
partition
peek
peek_values
private_methods
protected_methods
public_method
public_methods
public_send
reduce
reject
remove_instance_variable
respond_to?
reverse_each
rewind
select
send
singleton_class
singleton_method
singleton_methods
size
slice_after
slice_before
slice_when
sort
sort_by
sum
taint
tainted?
take
take_while
tap
to_a
to_enum
to_h
to_json
to_s
to_set
trust
uniq
untaint
untrust
untrusted?
with_index
with_object
zip
</details>
So in irb it has all methods

**Comment by jdee** [comment]
@Wojcik Here's a question: It works with `irb`. Are you using a Gemfile, and if so, does it work with `bundle console`? Can you try the same thing there? I wonder if it could be a dependency issue, where you're picking up a dependency from RubyGems that isn't in your bundle. It looks like somehow the Enumerable module isn't mixed into the Aws::S3::ObjectSummary::Collection class.

**Comment by kevinj** [comment]
I had this same problem and ended up finding an empty class definition for `Enumerator` here: https://github.com/ckruse/CFPropertyList/blob/master/lib/cfpropertylist/rbCFPropertyList.rb#L91-L95. After removing that, I can enumerate my s3 bucket again.

**Comment by jdee** [comment]
@kevinj Interesting. There were some changes around CFPropertyList in 2.69.0 and 2.69.1. Do you have this problem with those versions?

**Comment by jdee** [comment]
And if you're using >= 2.69.0, you can also try adding `require "fastlane_core/core_ext/cfpropertylist"` in your code. That extension fixes some conflicts between CFPropertyList and plist.
