### ISSUE TITLE
Define action within lane

### ISSUE THREAD

**Issue by royberris** [fastlane/fastlane#11110]
I am fairly new to ruby, and I would like to define an action within my Fastfile (or lane) and execute this action within that lane. How do I do this? I've tried to define inside my lane and at the top of the Fastfile. but this didn't work.

**Comment by ohayon** [comment]
Hey @royberris! Thats a great question, would it be possible to tell us a bit more about your use case so that we can give you some good advice? Depending on what you want to achieve there could be a few options for you. 🚀
