### ISSUE TITLE
UTF-8 is set yet download_dsyms fails.

### ISSUE THREAD

**Issue by dirkoswanepoel** [fastlane/fastlane#11119]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

download_dsyms fails with UTF-8 exception when it is set.

##### Complete output when running fastlane, including the stack trace and command used

Command Used: `ios refresh_dsyms`
<details><summary>Output/Log</summary>

```

DEBUG [2017-12-06 09:45:16.09]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '*** REMOVED ***/fastlane/Appfile'
- app_identifier: '*** REMOVED ***'
- apple_id: '*** REMOVED ***'
- team_id: '*** REMOVED ***'
- itc_team_id: '*** REMOVED ***'
-------
INFO [2017-12-06 09:45:16.30]: -------------------------------------------------
INFO [2017-12-06 09:45:16.30]: --- Step: Verifying required fastlane version ---
INFO [2017-12-06 09:45:16.30]: -------------------------------------------------
INFO [2017-12-06 09:45:16.30]: Your fastlane version 2.68.2 matches the minimum requirement of 2.64.1  ✅
INFO [2017-12-06 09:45:16.33]: ------------------------------
INFO [2017-12-06 09:45:16.33]: --- Step: default_platform ---
INFO [2017-12-06 09:45:16.33]: ------------------------------
INFO [2017-12-06 09:45:16.33]: Driving the lane 'ios refresh_dsyms' 🚀
INFO [2017-12-06 09:45:16.36]: ----------------------------
INFO [2017-12-06 09:45:16.36]: --- Step: download_dsyms ---
INFO [2017-12-06 09:45:16.36]: ----------------------------
INFO [2017-12-06 09:45:16.36]: Login to iTunes Connect (*** REMOVED ***)
Loading session from '*** REMOVED ***/.fastlane/spaceship/*** REMOVED ***/cookie'
Looking for iTunes Connect Team with ID *** REMOVED ***
INFO [2017-12-06 09:45:20.01]: Login successful
INFO [2017-12-06 09:45:21.28]: Looking for dSYM files for *** REMOVED *** v3.0
WARN [2017-12-06 09:45:30.16]: Lane Context:
INFO [2017-12-06 09:45:30.16]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios refresh_dsyms"}
ERROR [2017-12-06 09:45:30.16]: "\x8B" from ASCII-8BIT to UTF-8
INFO [2017-12-06 09:45:30.17]: Successfully generated documentation at path '*** REMOVED ***/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | download_dsyms                      | 12          |
+------+-------------------------------------+-------------+

ERROR [2017-12-06 09:45:30.17]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: "\x8B" from ASCII-8BIT to UTF-8

URL: https://api.github.com/search/issues?q=%22%5Cx8B%22%20from%20ASCII-8BIT%20to%20UTF-8+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.1"

default_platform :ios

platform :ios do
  lane :refresh_dsyms do
    download_dsyms(version: "3.0")
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "*** REMOVED ***" # The bundle identifier of your app
apple_id "*** REMOVED ***" # Your Apple email address

team_id "*** REMOVED ***" # Developer Portal Team ID

itc_team_id "*** REMOVED ***"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.4.4        |
</details>

*generated on:* **2017-12-06**
</details>

**Comment by ohayon** [comment]
Hey @dirkoswanepoel apologies for this issue you're seeing! Could you share the output of the commend when you run it with `--verbose`? Thanks!

**Comment by dirkoswanepoel** [comment]
Hi @ohayon I'm not sure what verbose should add. I did a --capture_output and it seems it already does verbose. Which is what I logged above.

Below is the stacktrace at the end of it all:
`bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Encoding::UndefinedConversionError: [!] "\x8B" from ASCII-8BIT to UTF-8
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:91:in `write'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:91:in `write_dsym'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:69:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:54:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:54:in `block in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:50:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/download_dsyms.rb:50:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:23:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'`

**Comment by ohayon** [comment]
Hey @dirkoswanepoel - this is definitely strange. Im curious are you pretty familiar with Ruby? Would you be comfortable helping debug this a bit? I would love to stick a breakpoint (`binding.pry`) or print out some values in that method to see what exactly is the state of the world at runtime.

**Comment by fruitcoder** [comment]
I also get an error. This is the verbose output:

```
DEBUG [2017-12-23 10:40:22.31]: [310635]: sending {"payload":{"status":"failure","failure_information":["Encoding::UndefinedConversionError:", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:97:in `write'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:97:in `write_dsym'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:74:in `block (2 levels) in run'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:59:in `each'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:59:in `block in run'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:55:in `each'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/download_dsyms.rb:55:in `run'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:227:in `chdir'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:227:in `execute_action'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:72:in `run'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:41:in `execute'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:115:in `execute_command'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:110:in `process_command'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:56:in `block in receive_and_process_commands'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:40:in `loop'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:40:in `receive_and_process_commands'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:89:in `listen'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/server/socket_server.rb:29:in `start'", "/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/swift_lane_manager.rb:194:in `block in start_socket_thread'"]}}
DEBUG [2017-12-23 10:40:22.31]: [312037]: received done signal, shutting down
```

**Comment by emes** [comment]
Encoding::UndefinedConversionError: [!] "\xF7" from ASCII-8BIT to UTF-8
