### ISSUE TITLE
Is there a tool to verify against private api use? 

### ISSUE THREAD

**Issue by danielCarlosCE** [fastlane/fastlane#11123]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by ohayon** [comment]
Hey @danielCarlosCE, thats a great question! We do not currently support checking for private APIs but that would be a great addition to our precheck tool. Would you want to try submitting a PR with that addition? I think the community would love it! 🚀
