### ISSUE TITLE
No "bash profile instructions" output on install with homebrew-bundle

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11127]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Normally during `brew cask install fastlane` you get output like this:

```
...
==> Couldn't detect shell config file (bash - ~/.bash_profile)
==> Please add the following line to your bash profile:
==> 
==> export PATH="$HOME/.fastlane/bin:$PATH"
...
```

But if you use https://github.com/Homebrew/homebrew-bundle, this output is swallowed. Any workaround for this? How do other tools handle this?

**Comment by ohayon** [comment]
This seems like more of an issue with homebrew-bundle (which I had never heard of until now 😄  ) than fastlane no?

**Comment by janpio** [comment]
They are fine with swallowing whatever output there is. 
Problem is, that _fastlane_ then just doesn't work at all.

**Comment by janpio** [comment]
I had created an issue at homebrew-bundle about this problem:

>> homebrew-bundle swallowing all output is certainly normally useful, but what about cases like this?
> This is either-or, unfortunatley.. brew bundle --verbose may print what you desire and if it doesn't: we'd welcome a PR to do so.

https://github.com/Homebrew/homebrew-bundle/issues/310

`--verbose` does indeed print the instructions. Nothing `fastlane` can do about it directly.

Some `brew` packages have a "Caveats" block output:

```
Virtuals-Mac:~ foo$ brew reinstall nvm
==> Reinstalling nvm 
==> Downloading https://github.com/creationix/nvm/archive/v0.33.6.tar.gz
Already downloaded: /Users/foo/Library/Caches/Homebrew/nvm-0.33.6.tar.gz
==> Caveats
Please note that upstream has asked us to make explicit managing
nvm via Homebrew is unsupported by them and you should check any
problems against the standard nvm install method prior to reporting.

You should create NVM's working directory if it doesn't exist:

  mkdir ~/.nvm

Add the following to ~/.bash_profile or your desired shell
configuration file:

  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

You can set $NVM_DIR to any location, but leaving it unchanged from
/usr/local/opt/nvm will destroy any nvm-installed Node installations
upon upgrade/reinstall.

Type `nvm help` for further information.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/nvm/0.33.6: 7 files, 134.9KB, built in 4 seconds
Virtuals-Mac:~ foo$ 
```

This is output for all installations via `brew`.

Am I correct in my understanding that this is not useful as _sometimes_ fastlane can take care of all the steps by itself and only if it fails you get the ouput I posted in my original post?
