### ISSUE TITLE
Issue with `keychain-access-groups` when resigning with `use_app_entitlements` option

### ISSUE THREAD

**Issue by kapfab** [fastlane/fastlane#11125]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using `use_app_entitlements` option in `resign` with an app without any specific `keychain-access-groups` capability set, the `keychain-access-groups` key from the provisioning profile gets re-injected into the patched entitlements, with an incorrect value (as this key in provisioning profiles is always populated with `TEAMID.*` or `OLDPREFIX.*`, AFAIK), instead of no entry at all.

The impact is that the "corrupted" resigned application will now by default create keychain entries on the wrong access group (`TEAMID.*` or `OLDPREFIX.*`) instead of the default access group (based on the `application-identifier`).
Note that this "corrupted" application will still be able to access the existing `application-identifier`-based entries, which can lead to many Fastlane users having this issue without being aware of it.

Removing this incorrect key from the entitlements in the next version of the app will make the keychain items created on the wrong access group not accessible anymore.
Of course, the longer an app lives with this problem, the more keychains items will get lost with the fix, the more users will get upset remembering and re-typing their credentials…

### Environment

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### My two cents

Adding `keychain-access-groups` to the blacklisted keys added by PR #7916 could do the trick to avoid this behaviour, but these forbidden keys are removed after the PP+App merge and not before (and always removing `keychain-access-groups` would be an issue for apps with specific access groups set).

Couldn't we move this blacklist code before the PP+App merge? I can't see why an IPA to be resigned would contain forbidden entitlements, I think invalid entitlements can only come from the PP…

Any thoughts, @mgrebenets and other `resign` wizards?

**Comment by kapfab** [comment]
If someone wants to share his thoughts about PR #11346…

**Comment by mgrebenets** [comment]
@kapfab 

This sounds like it may be related to https://github.com/fastlane/fastlane/issues/8307

**Comment by kapfab** [comment]
Definitely.

**Comment by kapfab** [comment]
Will be fixed by PR #11346, can be closed.
