### ISSUE TITLE
After using command "I signed it!" in a PR, the googlebot will respond to every (edited) comment when the CLA is not OK.

### ISSUE THREAD

**Issue by funnel20** [fastlane/fastlane#11122]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

See PR #11096 where at [this comment](https://github.com/fastlane/fastlane/pull/11096#issuecomment-349579321) I wrote the command: `I signed it!`

googlebot responded with an issue, which is fine:

> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for the commit author(s). If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA (login here to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and have the pull request author **add another comment and the bot will run again**.

Here is the issue:
Instead of what it says in the last sentence, the googlebot responds to EVERY new comment, or an edit of an comment.
While it should stay silent, until `I signed it!` is written again. 

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by janpio** [comment]
Although I am also irritated by its behaviour, isn't what you describe exactly what it tells you it will be doing?

> ... have the pull request author add another comment and the bot will run again

It runs again for each additional comment interaction on the thread of the PR author (probably can't or intentionally does not differentiate between new comment and edited comment).

**Comment by funnel20** [comment]
You're right.
I read "**the** comment" (referring to `I signed it!`) instead of "**another** comment", because I assumed that someone was able to make a sensible requirement and the implementation was just erroneous.

However, reality seems worse as the requirement is the problem.
So my suggestion would be to change that to:

> In order to pass this check, please resolve this problem and add a comment with "I signed it!" and the bot will run again.

**Comment by janpio** [comment]
Personally, I agree that @googlebot is quite chatty and annoying in this case, see your PR :/

I will close this issue, as this is only indirectly related to _fastlane_ itself.

But @alexsinger, can you make sure this feedback gets forwarded to the correct team? There doesn't seem to be a repo with issues for @googlebot where this could get reported. Thanks.

**Comment by funnel20** [comment]
@janpio and @alexsinger Thanks for transferring this to the correct team.
