### ISSUE TITLE
Multiple iOS versions

### ISSUE THREAD

**Issue by allysonsaberg** [fastlane/fastlane#11133]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello! The iOS app i've been using snapshot for currently needs to be tested on screen sizes from 3.5" -> 12.9". This means that we need to do testing specifically on the iphone 4s (3.5 inch screen), which only supports up to ios 9. For this reason, we cannot run all devices/languages at once since the rest of them are on ios 11 and the 4s simulator is stuck on ios 9. We would like to ideally run what we can (ie the rest of the simulators) on ios 11, and have the 4s default to its highest supported ios(9). Is there any way to specify a SECOND ios version in the snapfile for the 4S only so that we may run all simulators at once?
##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by ohayon** [comment]
Hey @allysonsaberg - apologies for the issue youre having. We are not currently supporting snapshot for iPhone 4s as iTunesConnect no longer requires that size screenshot. See https://github.com/fastlane/fastlane/issues/10211 for some more history. Let us know if you have any more questions! 🚀

**Comment by IchHabRecht** [comment]
I'm able to run tests on multiple iOS versions by not defining any version in my configuration. I set up a 7 and 7 Plus simulator with iOS 10.0 and all other devices with 11.2. All simulators are found and used perfectly fine. Maybe this helps you as well.

**Comment by joshdholtz** [comment]
Closing this issue now as iTunesConnect is a little more flexible with screenshot sizes now 😊
