### ISSUE TITLE
[Plugin] Running CLI command in `sh` cuts off output 

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11132]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a plugin https://github.com/ionic-zone/fastlane-plugin-ionic that runs a CLI command (`ionic cordova prepare android --debug --device --prod`). 

In some special case (fresh checkout, `npm i` not run yet) the command normally has this output:

```
Virtuals-Mac:ionic-fastlane foo$ ionic cordova prepare android --debug --device --prod

? Looks like a fresh checkout! No ./node_modules directory found. Would you like
 to install project dependencies? (Y/n) 
```

But when run inside the plugin with `sh` (https://github.com/ionic-zone/fastlane-plugin-ionic/blob/master/lib/fastlane/plugin/ionic/actions/ionic_action.rb#L91) the output gets cut off:

```
...
[12:04:25]: -------------------
[12:04:25]: --- Step: ionic ---
[12:04:25]: -------------------
[12:04:25]: $ ionic cordova prepare android --debug --device --prod

[12:04:26]: ▸ ? Looks like a fresh checkout! No ./node_modules directory found. Would you like

```

Any idea what could be causing this?
Is it the fact that this text is a prompt? [1]
Or is the linebreak there somehow the culprit?

[1] (that can not be answered right there anyway, but that is secondary for the cut off problem)

**Comment by joshdholtz** [comment]
@janpio Did you ever get a chance to look into this? 🙃

**Comment by janpio** [comment]
Never did as the plugin was not popular enough and the problem is kind of an edge case @joshdholtz Still a honest problem with `sh` of course.

**Comment by joshdholtz** [comment]
Have you seen this issue with any other commands? I have totally seen other node stuff be buggy in `sh` before too 😔
