### ISSUE TITLE
fastlane crashes with strange error message when run without ever starting Xcode before causing misconfigured `xcode-select`

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11130]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I managed to screw up my `xcode-select` configuration somehow:

1. Setup new Mac
2. Install Xcode
3. Install _fastlane_ 
4. Run `fastlane`
5. See this:

```
Virtuals-Mac:~ foo$ fastlane
[09:45:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
sh: /Library/Developer/CommandLineTools//usr/bin/xcodebuild: No such file or directory
[09:45:46]: undefined method `split' for nil:NilClass
sh: /Library/Developer/CommandLineTools//usr/bin/xcodebuild: No such file or directory
[09:45:47]: undefined method `split' for nil:NilClass

[!] Error detecting currently used Xcode installation, please ensure that you have Xcode installed and set it using `sudo xcode-select -s [path]`
```

My thoughts:
- I have Xcode installed.
- I have no idea what this `sudo xcode-select ...` command is for. Why should this be necessary?

Further investigation:
1. Start Xcode
2. Accept licence agreements
3. Wait for "Installing Components" to finish
4. See "Welcome to Xode"
5. Try again
6. See same error

Futher:

7. 
```
Virtuals-Mac:~ foo$ xcode-select -p  
/Library/Developer/CommandLineTools
```
Huh!?
8. 
```
Virtuals-Mac:~ foo$ sudo xcode-select --reset  
Password:  
```
```
Virtuals-Mac:~ foo$ xcode-select -p  
/Applications/Xcode.app/Contents/Developer
```
Better.
9. 
``` 
Virtuals-Mac:~ foo$ fastlane  
[10:11:35]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile  
[10:11:39]: Could not find fastlane in current directory. Make sure to have  
your fastlane configuration files inside a folder called "fastlane". Would you like  
to set fastlane up? (y/n)  
n  
Virtuals-Mac:~ foo$
```
Fixed.

Am I correct in my assumption this was caused by running `fastlane` on the command line before ever starting Xcode?
Could or should this case be better handled in _fastlane_?

**Comment by janpio** [comment]
7 other issues about that same path: https://github.com/fastlane/fastlane/issues?utf8=%E2%9C%93&q=%22%2FLibrary%2FDeveloper%2FCommandLineTools%2F%2Fusr%2Fbin%2Fxcodebuild%22

We could probably add some code checking for `/Library/Developer/CommandLineTools//usr/bin/xcodebuild` and output an appropriate error message.

**Comment by KrauseFx** [comment]
Oh wow, nice catch. That looks like something worth investigating - is that something you're gonna take a closer look at?

**Comment by janpio** [comment]
Yes. I think I know how this happens, see my initial post. Will just have to go through the other issues.
