### ISSUE TITLE
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:124:in `block in keys_to_symbols': 

### ISSUE THREAD

**Issue by bsyg** [fastlane/fastlane#11138]
```
[32m#######################################################################[0m
[32m# fastlane 2.68.2 is available. You are on 2.67.0.[0m
[32m# You should use the latest version.[0m
[32m# Please update using `sudo gem install fastlane`.[0m
[32m#######################################################################[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:124:in `block in keys_to_symbols': [31m[!] undefined method `to_sym' for true:TrueClass[0m (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:123:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:123:in `each_with_object'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:123:in `keys_to_symbols'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:140:in `read_export_options'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:161:in `config_content'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:20:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/runner.rb:107:in `package_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/manager.rb:14:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/gym/lib/gym/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/fastlane/lib/fastlane/cli_tools_distributor.rb:67:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.67.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'<!-- Thanks for helping _fastlane_! Before you submit your issue, please make sure to check the following boxes by putting an x in the [ ] (do: [x], don't: [x ], [ x], [✔️]) -->
```

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by ohayon** [comment]
Hey @bsyg could you provide some more context about how this crash is happening? Thanks! 🚀

**Comment by bsyg** [comment]
hello, when I run fastlane env, the output as follows:
➜  ~ fastlane env
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fastimage (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/du/utilities.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/tunes/tunes.rb:38:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/spaceship/lib/spaceship.rb:12:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/setup/setup_ios.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/setup/setup.rb:57:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/fastlane/lib/fastlane.rb:11:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by bsyg** [comment]
when I put back /Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb from the trash, execute the `fast lane env`in the terminal and the output as follows:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>


*generated on:* **2017-12-11**
</details>

**Comment by taquitos** [comment]
It looks like a key "true" is being set, and that's causing issues. I have a PR up to fix that first problem you reported. I don't know if it will fix your issue though, since the problem you highlighted shows "true" as being passed as a key, and that's weird.
If you can add your fastfile and the full output from the tool, that will help us diagnose this further.

**Comment by bsyg** [comment]
Hello,taquitos
Our build script has used about two years, so it does not have  fast file. The process  probably is parameters configuration and then running the command `fastlane gym --project ./ProjectRelayout/LetvMobileClient/LetvMobileClient.xcodeproj --configuration Debug --export_options exportPlist.plist --archive_path ./LetvIphoneClient --output_name LetvIphoneClient --clean`. The output information is in the attachment:
[outputinfo.log.zip](https://github.com/fastlane/fastlane/files/1550115/outputinfo.log.zip)

**Comment by bsyg** [comment]
hi,
I find this issue is still existed now. which version of fastlane is fixed?
