### ISSUE TITLE
[Feature] Allow uploading an attachment as part of App Review Information

### ISSUE THREAD

**Issue by alenia** [fastlane/fastlane#11136]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane's Deliver does not support adding an attachment to the app review information, but itunesconnect allows a user to add an attachment as part of app review information (e.g. a zipfile with more relevant screenshots for IAP). It would be nice to be able to have `metadata/review_information/attachment.zip` upload the attachment to the appropriate spot given that itunesconnect supports this.

**Comment by ohayon** [comment]
Hey @alenia, this definitely would be a cool feature to add. Is there any chance you would want to submit a PR for that? 🚀
