### ISSUE TITLE
Unhandled exception when gradle exit status is 1.

### ISSUE THREAD

**Issue by alexrs** [fastlane/fastlane#11131]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

In [`GradleAction#run`](https://github.com/fastlane/fastlane/blob/0d3a86512780512db5523c145fd1f5b6020d4528/fastlane/lib/fastlane/actions/gradle.rb#L50), when executing a gradle action, the `run` function is supposed to return the result of the command, but when the exit status of the command is a failure (1), an exception is thrown and the result is never returned.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>
 
### Stack
 
| Key                         | Value                                                 |
| --------------------------- | ----------------------------------------------------- |
| OS                          | debian_based stretch/sid                              |
| Ruby                        | 2.4.2                                                 |
| Bundler?                    | true                                                  |
| Git                         | git version 2.7.4                                     |
| Installation Source         | /tmp/bundle/ruby/2.4.0/bin/fastlane                   |
| Host                        | Ubuntu 16.04.3 LTS debian_based stretch/sid (4.4.64+) |
| Ruby Lib Dir                | /usr/lib                                              |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                            |
| Is contained                | false                                                 |
| Is homebrew                 | false                                                 |
| Is installed via Fabric.app | false                                                 |
 
### System Locale
 
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |
 
### fastlane files:
 
<details><summary>`./fastlane/Fastfile`</summary>
 
```ruby
ANDROID_PROJECT_PATH = File.expand_path('../..', __FILE__)
FIREBASE_CONFIG_FILE = ".buildkite/firebase-config.yml"
 
platform :android do
  desc "Upload code coverage to codecov.io"
  private_lane :codecov do
    UI.message("Uploading code coverage results to codecov.io")
    Fastlane::Actions.sh("bash -c 'bash <(curl -s https://codecov.io/bash)'")
  end
 
  desc "Run Danger"
  private_lane :run_danger do
    begin
      Fastlane::Actions.sh("cd .. && bundle exec danger")
    rescue => e
      # Don't fail CI because of Danger
      UI.message("Danger did not run successfully")
    end
  end
end
 
FIREBASE_LIBRARY_APK = 'FirebaseTestApplication/build/outputs/apk/debug/FirebaseTestApplication-debug.apk'
 
import "Emulator.fastfile"
import "MerchantSDK.fastfile"
import "Polaris.fastfile"
import "Lint.fastfile"
import "Shopify.fastfile"
import "Hockey.fastfile"
import "Foundation.fastfile"
import "PolarisSample.fastfile"
import "Release.fastfile"
import "ShopifyAutomation.fastfile"
import "MerchantLogin.fastfile"
import "Timeline.fastfile"
import "Uploadify.fastfile"
require_relative 'release_helpers.rb'
require_relative 'version.rb'
```
</details>
 
**No Appfile found**
 
### fastlane gems
 
| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.66.2  | 🚫 Update available |
 
### Loaded fastlane plugins:
 
| Plugin                                        | Version | Update-Status  |
| --------------------------------------------- | ------- | -------------- |
| fastlane-plugin-common_actions                | 0.1.0   | 💥 Check failed |
| fastlane-plugin-download_github_release_asset | 1.0.0   | ✅ Up-To-Date   |
 
<details><summary><b>Loaded gems</b></summary>
 
| Gem                                           | Version      |
| --------------------------------------------- | ------------ |
| io-console                                    | 0.4.6        |
| CFPropertyList                                | 2.3.5        |
| public_suffix                                 | 2.0.5        |
| addressable                                   | 2.5.2        |
| android_emulator                              | 0.1.4        |
| babosa                                        | 1.0.2        |
| multipart-post                                | 2.0.0        |
| faraday                                       | 0.13.1       |
| sawyer                                        | 0.8.1        |
| buildkit                                      | 1.2.0        |
| bundler                                       | 1.15.4       |
| claide                                        | 1.0.2        |
| colored2                                      | 3.1.2        |
| cork                                          | 0.3.0        |
| nap                                           | 1.1.0        |
| open4                                         | 1.3.4        |
| claide-plugins                                | 0.9.2        |
| colored                                       | 1.2          |
| colorize                                      | 0.8.1        |
| highline                                      | 1.7.8        |
| commander-fastlane                            | 4.4.5        |
| faraday-http-cache                            | 1.3.1        |
| git                                           | 1.3.0        |
| kramdown                                      | 1.15.0       |
| no_proxy_fix                                  | 0.1.2        |
| octokit                                       | 4.7.0        |
| unicode-display_width                         | 1.3.0        |
| terminal-table                                | 1.8.0        |
| danger                                        | 5.5.5        |
| danger-plugin-api                             | 1.0.0        |
| danger-todoist                                | 1.2.3        |
| declarative                                   | 0.0.10       |
| declarative-option                            | 0.1.0        |
| unf_ext                                       | 0.0.7.4      |
| unf                                           | 0.1.4        |
| domain_name                                   | 0.5.20170404 |
| dotenv                                        | 2.2.1        |
| excon                                         | 0.59.0       |
| http-cookie                                   | 1.0.3        |
| faraday-cookie_jar                            | 0.0.6        |
| faraday_middleware                            | 0.12.2       |
| fastimage                                     | 2.1.0        |
| gh_inspector                                  | 1.0.3        |
| jwt                                           | 2.1.0        |
| little-plugger                                | 1.1.4        |
| multi_json                                    | 1.12.2       |
| logging                                       | 2.2.2        |
| memoist                                       | 0.16.0       |
| os                                            | 0.9.6        |
| signet                                        | 0.8.1        |
| googleauth                                    | 0.6.2        |
| httpclient                                    | 2.8.3        |
| mime-types-data                               | 3.2016.0521  |
| mime-types                                    | 3.1          |
| uber                                          | 0.1.0        |
| representable                                 | 3.0.4        |
| retriable                                     | 3.1.1        |
| google-api-client                             | 0.13.6       |
| json                                          | 1.8.6        |
| mini_magick                                   | 4.5.1        |
| multi_xml                                     | 0.6.0        |
| plist                                         | 3.3.0        |
| rubyzip                                       | 1.2.1        |
| security                                      | 0.1.3        |
| slack-notifier                                | 1.5.1        |
| terminal-notifier                             | 1.8.0        |
| tty-screen                                    | 0.6.2        |
| word_wrap                                     | 1.0.0        |
| nanaimo                                       | 0.2.3        |
| xcodeproj                                     | 1.5.3        |
| rouge                                         | 2.0.7        |
| xcpretty                                      | 0.2.8        |
| xcpretty-travis-formatter                     | 1.0.0        |
| fastlane-plugin-common_actions                | 0.1.0        |
| fastlane-plugin-download_github_release_asset | 1.0.0        |
| graphql_schema                                | 0.1.6        |
| graphql_java_gen                              | 0.1.0        |
| mini_portile2                                 | 2.3.0        |
| nokogiri                                      | 1.8.1        |
| ox                                            | 2.8.2        |
</details>
 
*generated on:* **2017-12-06**
</details>

**Comment by ohayon** [comment]
Hey @alexrs, could you share the output from your command line so we can see whats going on? 🚀

**Comment by alexrs** [comment]
Hey, here is an example to reproduce the issue:

```RUBY
# ... some code here
passed = Actions::GradleAction.run(task: task, project_dir: params[:android_project_path],
                                            serial: '', print_command: true, print_command_output: true,
                                            flags: params[:flags])
# ... some more code here
```
If the gradle command is `gradlew :Polaris:checkstyle :Polaris:lintRelease`, and for any reason my code contains lint errors, and gradle returns 1, the code below the `Actions::GradleAction.run` is never executed. 
If I print the exception thrown, it's `exception: Exit status of command '/app/gradlew :Polaris:checkstyle :Polaris:lintRelease -p /app --build-cache' was 1 instead of 0.`. When catching this exception, the code below the `Actions::GradleAction.run` call is executed, although it makes fastlane to finish successfully, which in this case is not true.

**Comment by hjanuschka** [comment]
@alexrs  the underlying issue is that the gradle.run does not support the `error_callback` block that is used in `sh_helper.rb` - there for it just bails out with `shell_error!("msg")` throwing the "generic" `FastlaneShellError`  without any further information.



the change itself, would be a bit more work.
however maybe one of the following paths solves your issue, and gets you rolling again


# catch n match

Catch the exception and regex-match  on the  output message

# split

split your tasks so that the linting task (which may be flaky) is called in a seperate call to `gradle()` - then you can simply catch n ignore it.


overall i think its correct that fastlane fails as the gradle task fails, that your specific task is a `can-break` task, is not a real issue that fastlane can solve itself.
however i agree that the exception should be a bit more useful.

**Comment by alexrs** [comment]
👋 @hjanuschka Thanks for the answer! Your suggestions may work. I'll try them.
Anyway, IMHO, the real problem here is that I expected `GradleAction#run` to return the exit status of the command (or whether it has been successful or not), so I can decide how I want to handle that failure.
