### ISSUE TITLE
How to run appium tests on an Android emulator?

### ISSUE THREAD

**Issue by QianPb** [fastlane/fastlane#11137]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to integrate my appium end-to-end tests (running on Android emulator) with fastlane. I find that there is an Action `Appium` which is described as "Run UI test by Appium with RSpec". I tried to use this Action, and I have successfully invoked appium. However, I don't how to invoke my test files to run. I was asked to provide `spec_path`, but I don't know what exactly it is.

My test file is written with javascript, location is (project/__tests__/appium.android.js). Usually, I just run `npm test` in terminal to invoke them.

What I need to do is: `run test files on Android Emulator`

##### Complete output when running fastlane, including the stack trace and command used

This is my Fastfile
```
fastlane_version "2.68.2"

default_platform :android

platform :android do

  desc "Build apk"
  lane :beta do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  end

  desc "Run end to end tests on Appium"
  lane :test do
  appium(
  )
  end

end
```

This is the running result of `test` lane

QiandeMacBook-Pro:android qian$ bundle exec fastlane test
[12:52:27]: -------------------------------------------------
[12:52:27]: --- Step: Verifying required fastlane version ---
[12:52:27]: -------------------------------------------------
[12:52:27]: Your fastlane version 2.68.2 matches the minimum requirement of 2.68.2  ✅
[12:52:27]: ------------------------------
[12:52:27]: --- Step: default_platform ---
[12:52:27]: ------------------------------
[12:52:27]: Driving the lane 'android test' 🚀
[12:52:27]: --------------------
[12:52:27]: --- Step: appium ---
[12:52:27]: --------------------

+----------------------+---------+
|   Summary for Appium Action    |
+----------------------+---------+
| invoke_appium_server | true    |
| host                 | 0.0.0.0 |
| port                 | 4723    |
+----------------------+---------+

[12:52:27]: Appium executable detected: /usr/local/bin/appium
[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[12:52:32]: To not be asked about this value, you can specify it using 'spec_path'
[12:52:32]: Path to Appium spec directory: 
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.2"

default_platform :android

platform :android do
  before_all do
    #ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Build an apk"
  lane :beta do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Run end to end tests on Appium"
  lane :test do
  appium(
      #spec_path: "test"
  )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "com.tbsx3.customer.android" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| awesome_print             | 1.8.0        |
| json                      | 2.1.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.1        |
| ffi                       | 1.9.18       |
| childprocess              | 0.8.0        |
| rubyzip                   | 1.2.1        |
| selenium-webdriver        | 3.8.0        |
| tomlrb                    | 1.2.6        |
| appium_lib                | 9.7.5        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| diff-lcs                  | 1.3          |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| rspec-support             | 3.7.0        |
| rspec-core                | 3.7.0        |
| rspec-expectations        | 3.7.0        |
| rspec-mocks               | 3.7.0        |
| rspec                     | 3.7.0        |
</details>

*generated on:* **2017-12-07**
</details>

**Comment by ohayon** [comment]
ping @fastlane/android

**Comment by anthonyjoeseph** [comment]
This fastlane action runs spec tests written in ruby.

https://stackoverflow.com/questions/42735676/what-is-spec-path-for-fastlane-action-appium

 To use this action, you would have to re-write your node tests in ruby rspec.

**Comment by joshdholtz** [comment]
@anthonyjoeseph Thanks for answering this! You the MVP 🥇 Going to close this since implementing tests writing in javascript is probably not high on the list unless somebody would like to create a PR for this eventually 🙃

**Comment by aleenadavy90** [comment]
Hi, is there a fastlane action to run tests written in java and maven.

**Comment by joshdholtz** [comment]
@aleenadavy90 Hello 👋 Are you referring to `appium` tests? Or standard Android testing framework?

**Comment by aleenadavy90** [comment]
@joshdholtz I was referring to appium tests on iOS simulator
I have it working locally now. Thanks!

```
desc "Run Appium Test using simulators"
  private_lane :run_appium do
    xcodebuild(
      scheme: "XXXX",
      build: true,
      sdk: "iphonesimulator11.2",
      derivedDataPath: "build",
      xcargs: {
        ONLY_ACTIVE_ARCH: "NO"
      }
    )
    run_maven_tests
  end

  desc "Run maven tests"
  private_lane :run_maven_tests do 

  Dir.chdir("..") do
    sh "cd appium-selenium"
    sh "cd appium-selenium/XXXX && mvn clean test"
    end
  end
```
It does fail when I run it with Circle CI.
