### ISSUE TITLE
Match certificates unrecognized

### ISSUE THREAD

**Issue by gorbat-o** [fastlane/fastlane#11142]
### New Issue Checklist
- [✔️] Updated fastlane to the latest version
- [✔️] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✔️] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✔️] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello guys,

I have a problem with match,
When i'm trying to open in my keychain the p12 that it created, it gives me an error like this :(
<img width="717" alt="screen shot 2017-12-07 at 12 26 19" src="https://user-images.githubusercontent.com/7542553/33713096-2abf5bd8-db4a-11e7-8896-bcf5cce8d271.png">

the problem is, i'm using Bitrise, and when i put my p12 in it, it fails too.
My password is good, i tried a couple time with erasing all my certificates in my keychain, and all certificates and provisioning in the apple dev center,

I created my certificates with "fastlane match development"

Thanks for forthcoming helps,

<3 

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

There are some empty or modified, it is normal, it was sensitive informations

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.68.0"
default_platform :ios

platform :ios do
  lane :devices do
    register_devices(
      devices_file: "fastlane/devices.txt",
      username: ""
    )
  end

  desc "Use Match to generate certificates"
  lane :certificates do
    match(type: "appstore", readonly: true)
    match(type: "development", readonly: true)
    match(type: "adhoc", readonly: true)
  end

  desc "Create ipa and upload to tf"
  lane :testflight do
    `rm -rf ./Build; rm -rf ./Archive*`
    match(type: "appstore", readonly: true)
    cocoapods(clean: true, podfile: "./Podfile")
    gym(
      scheme: "Yoopies",
      export_method: "app-store",
      archive_path: "./Archive",
      output_directory: "Build",
      output_name: "Yoopies.ipa",
      export_xcargs: "-allowProvisioningUpdates",
      clean: true,
      silent: true
    )
    pilot(
      username: "ios@yoopies.com",
      app_identifier: "com.yoopies.iOSApps.Yoopies",
      team_id: "",
      ipa: "./Build/Yoopies.ipa",
      testers_file_path: "testers.csv",
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
    upload_symbols_to_crashlytics(
      dsym_path: "./Archive.xcarchive/dSYMs/Yoopies.app.dSYM",
      api_token: '',
    )
    clean_build_artifacts
    slack(
      slack_url: "",
      message: "Testflight released",
      channel: "#ios-ci",
      success: true
    )
  end

  desc "Create automatically a beta for Crashlytics"
  lane :beta do
    `rm -rf ./Build; rm -rf ./Archive`
    match(type: "adhoc", readonly: true)
    cocoapods(clean: true, podfile: "./Podfile")
    gym(
      scheme: "Yoopies-adhoc",
      export_method: "ad-hoc",
      output_directory: "Build",
      output_name: "Yoopies.ipa",
      export_xcargs: "-allowProvisioningUpdates"
    )
    crashlytics(
      api_token: '',
      build_secret: '',
      groups: "Testers",
      notifications: true,
      ipa_path: "./Build/Yoopies.ipa"
    )
    clean_build_artifacts
    slack(
      slack_url: "",
      message: "Beta released",
      channel: "#ios-ci",
      success: true
    )
  end

  error do |lane, exception|
    slack(
      slack_url: "",
      message: exception.message,
      success: false
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-12-07**
</details>

**Comment by ohayon** [comment]
Hey @gorbat-o - could you share the output from your command line when you run fastlane?

**Comment by gorbat-o** [comment]
Hey @ohayon ,
The lane certificates that i created works.
It's in the environment, it's just when i'm trying to use the p12 which was created in the repo containing the certficates, it fails to import in the keychain, or be used in Bitrise directly,

I kinda overpass this by going directly to developer.apple.com and download the certificates manually, and now it works with bitrise
