### ISSUE TITLE
Can't upload new version to HockeyApp with Fastlane

### ISSUE THREAD

**Issue by afraidiot** [fastlane/fastlane#11156]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I am in China
Every time I try to upload a new version to HockeyApp with fastlane, it always telling me that there is a network error
Does anyone has any solution?

```
[11:40:07]: [32mSuccessfully exported and compressed dSYM file[0m
[11:40:07]: [32mSuccessfully exported and signed the ipa file:[0m
[11:40:07]: /Users/jenkins/.jenkins/workspace/xxxx/output/xxxx.ipa
[11:40:07]: Cruising back to lane 'ios development' 🚘
[11:40:07]: [32m---------------------------------------[0m
[11:40:07]: [32m--- Step: Switch to ios deploy lane ---[0m
[11:40:07]: [32m---------------------------------------[0m
[11:40:07]: Cruising over to lane 'ios deploy' 🚖
[11:40:07]: [32m----------------------------------------[0m
[11:40:07]: [32m--- Step: changelog_from_git_commits ---[0m
[11:40:07]: [32m----------------------------------------[0m
[11:40:07]: [32mCollecting Git commits between  and HEAD[0m

[11:40:07]: [32m--------------------[0m
[11:40:07]: [32m--- Step: hockey ---[0m
[11:40:07]: [32m--------------------[0m
[11:40:07]: [32mStarting with file(s) upload to HockeyApp... this could take some time.[0m
+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                   [33mLane Context[0m                                                                                   |
+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                                                                                         |
| PLATFORM_NAME      | ios                                                                                                                                                         |
| LANE_NAME          | ios development                                                                                                                                             |
| BUILD_NUMBER       | 1920.20171129112423                                                                                                                                         |
| IPA_OUTPUT_PATH    | /Users/jenkins/.jenkins/workspace/xxxx/output/xxxx.ipa                           |
| DSYM_OUTPUT_PATH   | /Users/jenkins/.jenkins/workspace/xxxx/output/x.app.dxxxSYM.zip                  |
| XCODEBUILD_ARCHIVE | /Users/jenkins/.jenkins/workspace/xxxx/output/xxxx.xcarchive |
| FL_CHANGELOG       |                                                                                                                                                             |
+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
[11:43:11]: [31mNet::ReadTimeout[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_crash_reporting             | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | setup_jenkins                       | 0           |
| 5    | add_badge                           | 2           |
| 6    | Switch to ios build lane            | 0           |
| 7    | number_of_commits                   | 0           |
| 8    | increment_build_number              | 1           |
| 9    | gym                                 | 941         |
| 10   | Switch to ios deploy lane           | 0           |
| 11   | changelog_from_git_commits          | 0           |
| 💥   | [31mhockey[0m                              | 184         |
+------+-------------------------------------+-------------+

[11:43:11]: [31mfastlane finished with errors[0m

```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.4        |
| fastimage                 | 2.1.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.8.5        |
| fastlane-plugin-badge     | 1.0.0        |
</details>

**Comment by ohayon** [comment]
Hey @afraidiot, sorry about this issue, would you mind running this command again with `--verbose` so we can see a bit more context? Thanks! 🚀

**Comment by afraidiot** [comment]
@ohayon Following is new log with additional information of command with `--verbose`
```
Successfully exported and compressed dSYM file
INFO [2017-12-10 22:03:35.90]: Successfully exported and signed the ipa file:
INFO [2017-12-10 22:03:35.90]: /Users/afraidiot/Projects/audi-onetouch-ios/myAudi.ipa
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
INFO [2017-12-10 22:03:35.91]: Cruising back to lane 'ios development' 🚘
INFO [2017-12-10 22:03:35.91]: ---------------------------------------
INFO [2017-12-10 22:03:35.91]: --- Step: Switch to ios deploy lane ---
INFO [2017-12-10 22:03:35.91]: ---------------------------------------
INFO [2017-12-10 22:03:35.91]: Cruising over to lane 'ios deploy' 🚖
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
INFO [2017-12-10 22:03:35.94]: ----------------------------------------
INFO [2017-12-10 22:03:35.94]: --- Step: changelog_from_git_commits ---
INFO [2017-12-10 22:03:35.94]: ----------------------------------------
DEBUG [2017-12-10 22:03:36.00]: Found the last Git tag: 
INFO [2017-12-10 22:03:36.00]: Collecting Git commits between  and HEAD



Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
INFO [2017-12-10 22:03:36.04]: --------------------
INFO [2017-12-10 22:03:36.04]: --- Step: hockey ---
INFO [2017-12-10 22:03:36.04]: --------------------
INFO [2017-12-10 22:03:36.04]: Starting with file(s) upload to HockeyApp... this could take some time.
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
WARN [2017-12-10 22:12:38.36]: Lane Context:
INFO [2017-12-10 22:12:38.36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios development", :BUILD_NUMBER=>"1975.20171210215122", :IPA_OUTPUT_PATH=>"/Users/afraidiot/Projects/audi-onetouch-ios/myAudi.ipa", :DSYM_OUTPUT_PATH=>"/Users/afraidiot/Projects/audi-onetouch-ios/myAudi.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/afraidiot/Library/Developer/Xcode/Archives/2017-12-10/myAudi 2017-12-10 21.51.26.xcarchive", :FL_CHANGELOG=>nil}
ERROR [2017-12-10 22:12:38.36]: Net::ReadTimeout
INFO [2017-12-10 22:12:38.36]: Successfully generated documentation at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | opt_out_crash_reporti  | 0           |
|      | ng                     |             |
| 2    | Verifying required     | 0           |
|      | fastlane version       |             |
| 3    | default_platform       | 0           |
| 4    | setup_jenkins          | 0           |
| 5    | add_badge              | 0           |
| 6    | Switch to ios build    | 0           |
|      | lane                   |             |
| 7    | number_of_commits      | 0           |
| 8    | increment_build_numbe  | 0           |
|      | r                      |             |
| 9    | gym                    | 732         |
| 10   | Switch to ios deploy   | 0           |
|      | lane                   |             |
| 11   | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 💥   | hockey                 | 542         |
+------+------------------------+-------------+

DEBUG [2017-12-10 22:12:38.37]: All plugins are up to date
ERROR [2017-12-10 22:12:38.37]: fastlane finished with errors
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
-------
Successfully loaded Appfile at path '/Users/afraidiot/Projects/audi-onetouch-ios/fastlane/Appfile'
- app_identifier: 'cn.audi.onetouch'
```

**Comment by taquitos** [comment]
@afraidiot, it looks like the `hockey` action is timing out, you can set a timeout using `timeout:` param, I'd suggest setting that absurdly high, like 1hr or more.

**Comment by afraidiot** [comment]
@taquitos Oh, it really works, thanks
