### ISSUE TITLE
Fastlane canot automatically sign the app in High Sierra (10.13.1) 

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#11155]
### New Issue Checklist

- [x] I have been tried with the laster version 2.68. and version 2.64.1
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Branding a new app for the fist time in High Sierr, Fastlane cannot sigh the app.
##### Complete output when running fastlane, including the stack trace and command used

```
[[33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/JMango360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/JMango360/InstallationBuildProductsLocation/Applications/JMango360.app
** ARCHIVE FAILED **


[33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app
** ARCHIVE FAILED **


The following build commands failed:
CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app
(1 failure)
[10:46:51]: [31mExit status: 65[0m

+---------------+------------------------------------+
|                 [32m[33mBuild environment[0m                  |
+---------------+------------------------------------+
| xcode_path    | /Users/jenkins/Documents/Xcode.app |
| gym_version   | 2.64.1                             |
| export_method | app-store                          |
| sdk           | iPhoneOS11.2.sdk                   |
+---------------+------------------------------------+

[10:46:51]: ▸ [35m                      (123456-123456-45 123456-123456-aa15-68)[0m**
[10:46:51]: ▸ [35m    /usr/bin/codesign --force --sign 1234qwertyui1234567nbvcf --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app[0m
[10:46:51]: ▸ [35m/Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app: unknown error -1=ffffffffffffffff[0m
[10:46:51]: ▸ [35mCommand /usr/bin/codesign failed with exit code 1[0m]

```

Then, I run the command in terminal:
```
/usr/bin/codesign --force --sign 1234qwertyui1234567nbvcf --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app
```

###  and it popup a box to ask for access the certificate in keychain, I input the password to always allow it. After that, we can brand the app successfully.

After that, Fastlane can sign the app and build the app successfully. 
This only happens for the first time app is built.

This error not happened in previous OS. 
### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                     |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.13.1                                   |
| Ruby                        | 2.3.3                                     |
| Bundler?                    | false                                     |
| Git                         | git version 2.14.3 (Apple Git-98)         |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane      |
| Host                        | Mac OS X 10.13.1 (17B1003)                |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib               |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016               |
| Is contained                | false                                     |
| Is homebrew                 | false                                     |
| Is installed via Fabric.app | false                                     |
| Xcode Path                  | ~/Documents/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.64.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-12-08**
</details>

**Comment by ohayon** [comment]
Could you share the command that you are using to execute fastlane? Thanks! 🚀

**Comment by biolinh** [comment]
hi @ohayon 

this is my fastlane:

```
desc "Deploy a new version to the App Store using Match"
  lane :appstore_match do
    unlock_keychain(path: "login.keychain", password: KEYCHAIN_PASSWORD)

    sh "fastlane fastlane-credentials add --username '" + FASTLANE_USER +  "' --password '" + KEYCHAIN_PASSWORD + "'" 
    #set_google_info_plist_value
    match(type: "appstore")
    increment_build_number(build_number: BUILD_NUMBER)
    xcclean(scheme: "360")

    # clear jmango pods
    sh "pod install"
    sh "sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' '#{ENV["PROJECT_DIR"]}'/360.xcodeproj/project.pbxproj"
     sh "/usr/libexec/PlistBuddy -c 'Set :Preview  YES' ../360/Info.plist"
    #set_info_plist_value(path: '360/Info.plist', key: 'Preview', value: "YES")
 
    gym(scheme: "360", codesigning_identity: CODE_SIGN_IDENTITY, 
        xcargs: "DEVELOPMENT_TEAM=" + ENV["TEAM_ID"] +" " "PROVISIONING_PROFILE_SPECIFIER='" + ENV['sigh_' + ENV['BUNDLE_IDENTIFIER'] + '_appstore_profile-name'] +"'" +" " "PRODUCT_BUNDLE_IDENTIFIER=" + ENV["BUNDLE_IDENTIFIER"]) 
    upload_ipa
    #sh "fastlane pem renew"  
    sh "fastlane fastlane-credentials remove --username $FASTLANE_USER"

  end
```
Please note that: it worked before but after I update my OS into high Sierra, it cannot sign the app for first time without manually allow access key in my keychain
![2017-12-09_20-44-28](https://user-images.githubusercontent.com/1267094/33796171-dc07280c-dd21-11e7-83df-c3ac7d961a4f.png)

**Comment by biolinh** [comment]
follow the link https://stackoverflow.com/a/40039594/1920536 and it works
