### ISSUE TITLE
Match certificates become ineligible when having multiple bundle identifers

### ISSUE THREAD

**Issue by ippo012** [fastlane/fastlane#11154]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have multiple bundle identifers in the same project.
It is the next three.
- com.example
- com.example.develop
- com.example.staging

I created a provisioning profile using Match in each environment.

```bash
fastlane match appstore -a com.example
fastlane match development -a com.example.develop
fastlane match development -a com.example.staging
```

When trying to reference the created provisioning profile from xcode,
The provisioning profile other than appstore becomes ineligible.

<img width="734" alt="sample" src="https://user-images.githubusercontent.com/9071515/33749324-76e9ffd8-dc10-11e7-960e-cb48a329b4f6.png">

Even if you import directly from `~/Library/MobileDevice/Provisioning Profile`, the following error is displayed.

<img width="734" alt="sample2" src="https://user-images.githubusercontent.com/9071515/33749665-55754022-dc12-11e7-9ee8-136acc997d23.png">

I do not know why, so please let me know.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.rbenv/versions/2.3/bin/fastlane          |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.5/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

before_all do
  # https://github.com/fastlane/fastlane/issues/8475
  ENV['FASTLANE_HIDE_CHANGELOG'] = '1'
end

after_all do |lane|
end

error do |lane, exception|
end

platform :ios do
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.0.0        |
| slack-notifier        | 1.5.1        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.2.8        |
| terminal-notifier     | 1.8.0        |
| unicode-display_width | 1.3.0        |
| terminal-table        | 1.8.0        |
| plist                 | 3.3.0        |
| CFPropertyList        | 2.3.5        |
| public_suffix         | 2.0.5        |
| addressable           | 2.5.2        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| tty-screen            | 0.6.3        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.5        |
| excon                 | 0.59.0       |
| faraday               | 0.13.1       |
| unf_ext               | 0.0.7.4      |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_json            | 1.12.2       |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| dotenv                | 2.2.1        |
| bundler               | 1.14.6       |
| faraday_middleware    | 0.12.2       |
| uber                  | 0.1.0        |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| retriable             | 3.1.1        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| io-console            | 0.4.5        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
</details>

*generated on:* **2017-12-08**
</details>

**Comment by ohayon** [comment]
Hey @ippo012 - apologies for the issue. I've seen this same thing before. Have you tried just selecting that app store profile even though it says ineligible? That has worked for me int he past 🐙

**Comment by ippo012** [comment]
Thanks, @ohayon ! 
The cause was that the Product Bundle Identifer was wrong.
I corrected it and it worked fine.
