### ISSUE TITLE
Use cases/support for fastlane working with hashicorp vault for code-signing

### ISSUE THREAD

**Issue by jjmiv** [fastlane/fastlane#11150]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I was wondering if there are any use cases for fastlane with using hashicorp vault to code-signing with android and ios.

**Comment by joshdholtz** [comment]
@jjmiv There isn't anything built in to fastlane for HashiCorp but feel free to build a plugin for HashiCorp if you'd like 😊 https://docs.fastlane.tools/plugins/create-plugin/
