### ISSUE TITLE
Pricing info creation_date or tier_name is not included.

### ISSUE THREAD

**Issue by ahmgeek** [fastlane/fastlane#11169]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The `pricing_info` returns the corresponding prices as needed, and `pricing_intervals` returns the intervals also as needed.
In case of prices change for IAP recurring subscription, you get something like: 
```
pricing_intervals.select { |c| c[:country] == "AT" }
=> [{:tier=>80,
  :begin_date=>nil,
  :end_date=>"2017-06-14",
  :grandfathered=>{"value"=>"CURRENT_GF", "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil},
  :country=>"AT"},
 {:tier=>90,
  :begin_date=>"2017-06-14",
  :end_date=>nil,
  :grandfathered=>{"value"=>"FUTURE_NONE", "isEditable"=>false, "isRequired"=>false, "errorKeys"=>nil},
  :country=>"AT"}]
```
and for `pricing_info`:
```
pricing_info.select { |d| d.country_code == "AT" }
=> [<Spaceship::Tunes::IAPSubscriptionPricingInfo
	country_code="AT",
	currency_symbol="€",
	currency_code="EUR",
	wholesale_price=29.16,
	wholesale_price2=35.41,
	retail_price=49.99,
	f_retail_price="49,99 €",
	f_wholesale_price="29,16 €",
	f_wholesale_price2="35,41 €">,
 <Spaceship::Tunes::IAPSubscriptionPricingInfo
	country_code="AT",
	currency_symbol="€",
	currency_code="EUR",
	wholesale_price=34.99,
	wholesale_price2=42.49,
	retail_price=59.99,
	f_retail_price="59,99 €",
	f_wholesale_price="34,99 €",
	f_wholesale_price2="42,49 €">]
```
the issue here it's a bit not direct to know for pricing_info which one is he latest change so you can start using it.
Is there a direct way to get this piece of info?
Is it reliable or doable to add the tier_name to the pricing_info object or the date for this price?

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2@money/bin/fastlane   |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.62.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| diff-lcs                  | 1.3          |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| method_source             | 0.9.0        |
| pry                       | 0.11.2       |
| rspec-support             | 3.7.0        |
| rspec-core                | 3.7.0        |
| rspec-expectations        | 3.7.0        |
| rspec-mocks               | 3.7.0        |
| rspec                     | 3.7.0        |
</details>

*generated on:* **2017-12-11**
</details>

**Comment by taquitos** [comment]
Not super familiar here, but it looks like each tier has `begin_date`,  `end_date`, and `tier`
And you want to match that to a specific `IAPSubscriptionPricingInfo` right?

We don't have an easy of doing that right now, but you could go up one level to the `IAPSubscriptionPricingTier` object that holds the `IAPSubscriptionPricingInfo`. That object has `tier_name` too, so I think your only option right now is to filter the `IAPSubscriptionPricingInfo` from there 😞

**Comment by ahmgeek** [comment]
Thanks @taquitos for the heads up,
If this is the case, and since one of our ex-colleagues(@klappradla 😘) worked on the (retrieving of _Auto-Renewable Subscriptions_ ) #9121 #9180

We can send a Pull Request (**Some time ~soon~**)  😅  to make the mapping easier, 
or to append some tier details for the `pricing_info` method?

**Comment by taquitos** [comment]
@ahmgeek I'm not opposed to a PR :) Let us know what direction you think you'll go in. I think ideally, we'd have a call somewhere that would be "lastest pricing info for country code" or something to that extent. We're not fans of duplicating data from parent objects into child objects. But totally open to talk about what fits your needs 👍

**Comment by ahmgeek** [comment]
Sorry for the delay, will propose something here and we can discuss it further later. I am currently trying to patching #11189 first before Christmas, so it's a bit busy days 😢
