### ISSUE TITLE
undefined method `build_settings' for nil:NilClass Error

### ISSUE THREAD

**Issue by jackdem** [fastlane/fastlane#11168]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I am using the versioning plugin with fastlane, i get an error when it runs that ends my script:

```
[10:23:51]: -------------------------------------------
[10:23:51]: --- Step: get_version_number_from_plist ---
[10:23:51]: -------------------------------------------
+------------------+------------------------------+
|                  Lane Context                   |
+------------------+------------------------------+
| DEFAULT_PLATFORM | ios                          |
| PLATFORM_NAME    | ios                          |
| LANE_NAME        | ios distribute_to_testflight |
+------------------+------------------------------+
[10:23:52]: undefined method `build_settings' for nil:NilClass

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | Verifying required fastlane   | 0           |
|      | version                       |             |
| 2    | default_platform              | 0           |
| 3    | cocoapods                     | 3           |
| 💥   | get_version_number_from_plis  | 0           |
|      | t                             |             |
+------+-------------------------------+-------------+

[10:23:52]: fastlane finished with errors
```

Here is the fastfile:
```

platform :ios do

  before_all do
    cocoapods
  end

  lane :distribute_to_testflight do |options|
    ["Target1", "Target2", "Target3"].each do |scheme_name|

    scheme = scheme_name

    version = get_version_number_from_plist(xcodeproj: "projectTitle.xcodeproj", target: scheme, build_configuration_name: 'Release')

    current_build_number = latest_testflight_build_number(version: version)

    increment_build_number(
      build_number: current_build_number + 1
    )
    testflight_build = current_build_number + 1

      gym(
        scheme: scheme,
        export_method: "app-store",
        configuration: "Release",)

      pilot(
          skip_submission: false,
          distribute_external: false,
          skip_waiting_for_build_processing: true)

    end
end
```
Any idea what im doing wrong? i want to loop the targets and version them then upload them

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.1                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.1 (17B1003)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| slack-notifier             | 1.5.1        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.3.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.6.3        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.5        |
| excon                      | 0.59.0       |
| faraday                    | 0.13.1       |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| fastimage                  | 2.1.0        |
| gh_inspector               | 1.0.3        |
| mini_magick                | 4.5.1        |
| multi_json                 | 1.12.2       |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| dotenv                     | 2.2.1        |
| bundler                    | 1.16.0       |
| faraday_middleware         | 0.12.2       |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| little-plugger             | 1.1.4        |
| logging                    | 2.2.2        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.2        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.13.6       |
| json                       | 2.1.0        |
| io-console                 | 0.4.5        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.3        |
| fastlane-plugin-versioning | 0.3.3        |
</details>

*generated on:* **2017-12-11**
</details>

**Comment by jdee** [comment]
The `increment_build_number` action is a wrapper around `agvtool`. If you're using AGV versioning, you shouldn't use the `versioning` plugin. If you're not using AGV, you should not use the built-in `increment_build_number`, `increment_version_number`, `get_build_number` or `get_version_number` actions (described here https://docs.fastlane.tools/actions/#project). The crash you're getting is coming from `versioning`, though I'm not sure why.

**Comment by jackdem** [comment]
thanks, i used the plugin because i dont seem to be able to handle the various targets in my project with the default fastlane actions which dont take scheme params, is there a way i can achieve that so i dont need to use the plugin and can get around this error?

**Comment by jdee** [comment]
It sounds like you want different targets to have different version numbers and build numbers. This is legitimate, but incompatible with Apple Generic Versioning. If you're not familiar with AGV, here's an explanation: https://developer.apple.com/library/content/qa/qa1827/_index.html.

The `increment_build_number` and `increment_version_number` actions just call `agvtool next-version` and `agvtool next-marketing-version`, so they will do just what that Apple tech note says and set all targets to have the same version.

I think the `versioning` plugin can probably do just what you want. I'm not very familiar with it. You might get more help if you open an issue in that repo. But I think the exception is being raised here: https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/master/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb#L39. That means the target is nil, which probably means it's not finding the target by name in the project. That could mean the target name is misspelled or something. But it looks like you're calling the action right.

Instead of `increment_build_number` (the `agvtool` wrapper) you probably want to call [`increment_build_number_in_plist`](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning#increment_build_number_in_plist) from the `versioning` plugin.

**Comment by jackdem** [comment]
Im happy for the targets to have the same version and build, they will all always increment together, ill try and debug the versioning issue as you have said, but having no luck so far!

**Comment by jdee** [comment]
I think AGV might be what you really want, using built-in actions instead of the versioning plugin. You _may_ also have to add a `CURRENT_PROJECT_VERSION` setting to your project (at the project level) for `agvtool`. The `CURRENT_PROJECT_VERSION` needs to be the same as the build number (`CFBundleVersion`) in all of your Info.plist files. It may be that `agvtool` doesn't need this, but sometimes it complains.

<img width="1132" alt="screen shot 2017-12-12 at 6 18 05 am" src="https://user-images.githubusercontent.com/121951/33889219-4f26f59a-df04-11e7-8150-93a21606a2ee.png">


```Ruby
platform :ios do

  before_all do
    cocoapods
  end

  lane :distribute_to_testflight do |options|
    #
    # --- Update the build number for all targets
    #
    version = get_version_number(xcodeproj: "projectTitle.xcodeproj")
    current_build_number = latest_testflight_build_number(version: version)
    testflight_build = current_build_number + 1
    increment_build_number(
      xcodeproj: "projectTitle.xcodeproj"
      build_number: testflight_build
    )

    #
    # --- Now build each target/scheme
    #
    ["Target1", "Target2", "Target3"].each do |scheme_name|
      scheme = scheme_name

      gym(
        scheme: scheme,
        export_method: "app-store",
        configuration: "Release")

      pilot(
          skip_submission: false,
          distribute_external: false,
          skip_waiting_for_build_processing: true)
    end
end
```

But I also think instead of 7 lines of code, you can just do this:

```Ruby
    #
    # --- Update the build number for all targets
    #
    increment_build_number xcodeproj: "projectTitle.xcodeproj"

    #
    # --- Now build each target/scheme
    #
    ...
```
