### ISSUE TITLE
765: unexpected token at 'Bad Request' when calling to provisioningProfile.update!

### ISSUE THREAD

**Issue by pbeast** [fastlane/fastlane#11162]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The following code crashes with

> /Users/pbeast/.gems/gems/json-2.1.0/lib/json/common.rb:156:in 'parse': **765: unexpected token at 'Bad Request'** (Faraday::ParsingError)
	from /Users/pbeast/.gems/gems/json-2.1.0/lib/json/common.rb:156:in 'parse'
	from /Users/pbeast/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in 'block in <class:ParseJson>'
	from /Users/pbeast/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in 'parse'
	from /Users/pbeast/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in 'process_response'
	from /Users/pbeast/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in 'block in call'
	from /Users/pbeast/.gems/gems/faraday-0.13.1/lib/faraday/response.rb:61:in 'on_complete'
	from /Users/pbeast/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in 'call'
	from /Users/pbeast/.gems/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in 'build_response'
	from /Users/pbeast/.gems/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in vrun_request'
	from /Users/pbeast/.gems/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in 'post'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:724:in 'block in send_request'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:559:in 'with_retry'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:723:in 'send_request'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:611:in 'request'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/portal_client.rb:672:in 'repair_provisioning_profile!'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:459:in 'block in update!'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:559:in 'with_retry'
	from /Users/pbeast/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:458:in 'update!'
	from ./fastlane/sample.rb:49:in '<main>'

The code below is cut-out from the much longer script. By fail-and-retry, I found that **issue was introduced with fastlane v2.67.0** (v2.66.2 works fine)

```
#!/usr/bin/env ruby

require 'spaceship'

spaceship = Spaceship::Portal.login("xxx")
puts "Logged-in to Dev Portal".green
spaceship.team_id = 'xxx'

all_profiles = Spaceship::Portal.provisioning_profile.development.all

profiles = all_profiles.find_all do |profile|
  profile.app.bundle_id == "com.xxx.xxx"
end

if !profiles.nil? && profiles.size > 0
  if profiles.size > 1
    UI.important("Multiple profiles found: #{profiles.size}. Deleting all to avoid inconsistency")
    profiles.each { |p|
      #deleteLocalProvisioningProfile(p.uuid)
      p.delete!
    }
  else
    profile = profiles.first

    puts "Found provisioning profile '#{profile.name}' for app: #{profile.app.name}"

    profileName = "xxx Development"
    puts "Making sure profile name is '#{profileName}'"

    profile.name = profileName

    if !profile.valid? || !profile.certificate_valid?
      puts "Profile is broken. Will be fixed..."
    end

    puts "Updating profile devices".green
    profile.devices = Spaceship::Portal.device.all

    certificates = Spaceship::Portal.certificate.development.all

    puts "Assigning code signing certificates:".green
    certificates.each { |c|
      puts "	#{c.owner_name}(#{c.name})"
    }

    profile.certificates = certificates

    puts "Updating profile at development portal".green
    profile.update!

    #deleteLocalProvisioningProfile(profile.uuid)
  end
end
```

**Comment by taquitos** [comment]
Hey @pbeast, could you run fastlane with `--verbose`, and attach your complete output from the tool as well? That should help us diagnose this stuff.

**Comment by pbeast** [comment]
Hi,

That particular script isn't a part of any lane but executed as a standalone piece of code.
If that will help, I can create a sample lane with the same code. Will that help?

Regards,
Pavel Yankelevich

**Comment by taquitos** [comment]
Yeah, and if you could gather all the output with the `--verbose` flag that would be really helpful. It looks like you might be getting a bad server response from Apple.

**Comment by pbeast** [comment]
Below the output with --verbose flag:
DEBUG [2017-12-12 15:41:14.93]: Checking if there are any plugins that should be loaded...
DEBUG [2017-12-12 15:41:15.08]: Using scheme: xxx
INFO [2017-12-12 15:41:15.12]: -------------------------------------------------
INFO [2017-12-12 15:41:15.12]: --- Step: Verifying required fastlane version ---
INFO [2017-12-12 15:41:15.12]: -------------------------------------------------
INFO [2017-12-12 15:41:15.12]: Your fastlane version 2.68.2 matches the minimum requirement of 1.94.1  ✅
INFO [2017-12-12 15:41:15.15]: gem 'spaceship' is already installed
INFO [2017-12-12 15:41:15.20]: gem 'deliver' is already installed
INFO [2017-12-12 15:41:15.25]: gem 'deliver/app_screenshot' is already installed
INFO [2017-12-12 15:41:15.29]: gem 'fileutils' is already installed
INFO [2017-12-12 15:41:15.32]: gem 'json' is already installed
INFO [2017-12-12 15:41:15.35]: gem 'openssl' is already installed
INFO [2017-12-12 15:41:15.38]: gem 'terminal-table' is already installed
INFO [2017-12-12 15:41:15.40]: gem 'xcodeproj' is already installed
INFO [2017-12-12 15:41:15.47]: gem 'chunky_png' is already installed
INFO [2017-12-12 15:41:15.54]: gem 'date' is already installed
INFO [2017-12-12 15:41:15.78]: Driving the lane 'updateProfile' 🚀
INFO [2017-12-12 15:41:15.80]: ---------------------------
INFO [2017-12-12 15:41:15.80]: --- Step: shell command ---
INFO [2017-12-12 15:41:15.80]: ---------------------------
WARN [2017-12-12 15:41:15.83]: Following apps are known: ["xxx"]
INFO [2017-12-12 15:41:15.83]: -------------------------------------
INFO [2017-12-12 15:41:15.83]: --- Updating provisioning profile ---
INFO [2017-12-12 15:41:15.83]: -------------------------------------
INFO [2017-12-12 15:41:16.49]: Found bundle identifier: com.xxx.xxx
Loading session from '/Users/xxx/.fastlane/spaceship/xx@xx.xx/cookie'
INFO [2017-12-12 15:41:17.83]: Logged-in to Dev Portal
WARN [2017-12-12 15:41:19.05]: Found provisioning profile 'xxx Development' for app: xxx
INFO [2017-12-12 15:41:19.05]: Making sure profile name is 'xxx Development'
INFO [2017-12-12 15:41:20.96]: Updating profile devices
INFO [2017-12-12 15:41:22.84]: Assigning code signing certificates:
INFO [2017-12-12 15:41:22.84]: 	xxx xxx(iOS Development)
INFO [2017-12-12 15:41:22.84]: 	yyyy yyyy(iOS Development)
INFO [2017-12-12 15:41:22.87]: Updating profile at development portal
INFO [2017-12-12 15:42:54.60]: -----------------------------------
INFO [2017-12-12 15:42:54.60]: --- Step: clean_build_artifacts ---
INFO [2017-12-12 15:42:54.60]: -----------------------------------
INFO [2017-12-12 15:42:54.60]: Cleaned up build artifacts 🐙
INFO [2017-12-12 15:42:54.63]:

+-------------------------+-------------------+
|                 Actions Log                 |
+-------------------------+-------------------+
| Action                  | Result            |
+-------------------------+-------------------+
| Found bundle identifier | com.xxxx.xxxxxxxx |
+-------------------------+-------------------+
INFO [2017-12-12 15:42:54.75]: -------------------
INFO [2017-12-12 15:42:54.75]: --- Step: slack ---
INFO [2017-12-12 15:42:54.75]: -------------------
INFO [2017-12-12 15:42:55.48]: Successfully sent Slack notification
WARN [2017-12-12 15:42:55.48]: Lane Context:
INFO [2017-12-12 15:42:55.48]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"updateProfile", "noreports"=>false}
ERROR [2017-12-12 15:42:55.48]: 765: unexpected token at 'Bad Request'
INFO [2017-12-12 15:42:55.49]: Successfully generated documentation at path '/Volumes/Macintosh HD 2/Work/xxxx/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | shell command                       | 0           |
| 3    | clean_build_artifacts               | 0           |
| 4    | slack                               | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-12-12 15:42:55.49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: 765: unexpected token at 'Bad Request'

URL: https://api.github.com/search/issues?q=765:%20unexpected%20token%20at%20'Bad%20Request'+repo:fastlane/fastlane
➡️  765: unexpected token at 'Bad Request' when calling to provisioningProfile.update!
    https://github.com/fastlane/fastlane/issues/11162 [open] 5 💬
    15 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/xxx/.gems/bin/fastlane)
Faraday::ParsingError: [!] 765: unexpected token at 'Bad Request'
  /Users/xxx/.gems/gems/json-2.1.0/lib/json/common.rb:156:in 'parse'
  /Users/xxx/.gems/gems/json-2.1.0/lib/json/common.rb:156:in 'parse'
  /Users/xxx/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in 'block in <class:ParseJson>'
  /Users/xxx/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in 'parse'
  /Users/xxx/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in 'process_response'
  /Users/xxx/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in 'block in call'
  /Users/xxx/.gems/gems/faraday-0.13.1/lib/faraday/response.rb:61:in 'on_complete'
  /Users/xxx/.gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in 'call'
  /Users/xxx/.gems/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in 'build_response'
  /Users/xxx/.gems/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in 'run_request'
  /Users/xxx/.gems/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in 'post'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:724:in 'block in send_request'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:559:in 'with_retry'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:723:in 'send_request'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:611:in 'request'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/portal_client.rb:672:in 'repair_provisioning_profile!'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:459:in 'block in update!'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:559:in 'with_retry'
  /Users/xxx/.gems/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:458:in 'update!'
  Fastfile:1622:in 'block in parsing_binding'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane.rb:33:in 'call'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:49:in 'block in execute'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in 'chdir'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in 'execute'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane_manager.rb:54:in 'cruise_lane'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/command_line_handler.rb:30:in 'handle'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:104:in 'block (2 levels) in run'
  /Users/xxx/.gems/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in 'call'
  /Users/xxx/.gems/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in 'run'
  /Users/xxx/.gems/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in 'run_active_command'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in 'run!'
  /Users/xxx/.gems/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in 'run!'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:304:in 'run'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:42:in 'start'
  /Users/xxx/.gems/gems/fastlane-2.68.2/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in 'take_off'
  /Users/xxx/.gems/gems/fastlane-2.68.2/bin/fastlane:20:in '<top (required)>'
  /Users/xxx/.gems/bin/fastlane:23:in 'load'
  /Users/xxx/.gems/bin/fastlane:23:in '<top (required)>'

**Comment by pbeast** [comment]
Guys, any updates?

**Comment by taquitos** [comment]
I'm having a difficult time reproducing this with my own account. Any chance you could you run this script and capture the request and response that is being made? I think that would point us in the right direction. There must be some piece of data that the server doesn't like.

**Comment by pbeast** [comment]
The call to `profile.update!` leads to the following requests sequence: `https://developer.apple.com/services-account/QH65B2/account/ios/certificate/listCertRequests.action` followed by 25 identical calls to `https://developer.apple.com/services-account/QH65B2/account/ios/profile/regenProvisioningProfile.action`: (I masked potentially sensitive information with `????`)

**Request:**
`POST /services-account/QH65B2/account/ios/profile/regenProvisioningProfile.action HTTP/1.1`
`User-Agent: Spaceship 2.71.0`
`Content-Type: application/x-www-form-urlencoded`
`Cookie: DSESSIONID=????; acn01=????; dslang=US-EN; itcdq=0; itctx=????|????; myacinfo=????; site=USA`
`Accept-Encoding: gzip, deflate`
`Accept: */*`
`Connection: close`
`Host: developer.apple.com`
`Content-Length: 1039`

`appIdId=????&certificateIds=????&deviceIds=????&deviceIds=????&deviceIds=782XFC22KD&deviceIds=????&distributionType=limited&provisioningProfileId=????&provisioningProfileName=????&teamId=????`

**Response:**
`HTTP/1.1 421 421`
`Date: Wed, 27 Dec 2017 12:44:52 GMT`
`Content-Type: application/json`
`DSESSIONID: ????`
`Set-Cookie: DSESSIONID=????;Path=/;Domain=developer.apple.com;Secure;HttpOnly`
`Expires: Thu, 01 Jan 1970 00:00:00 GMT`
`csrf: ????`
`csrf_ts: ????`
`X-Frame-Options: DENY`
`Strict-Transport-Security: max-age=1500000`
`Cache-Control: no-store, no-cache, must-revalidate`
`X-Content-Type-Options: nosniff`
`Pragma: no-cache`
`X-XSS-Protection: 1; mode=block`
`Server: ATS/7.1.1`
`X-Frame-Options: SAMEORIGIN`
`Age: 0`
`Connection: close`
`Via: https/1.1 uklon5-edge-bx-017.ts.apple.com (ApacheTrafficServer/7.1.1)`
`CDNUUID: 0201849d-d877-44eb-a125-6ef9c576eec1--1144456225`
`X-Cache: miss`
`Content-Length: 11`

`Bad Request`

**Comment by KrauseFx** [comment]
Can you try adding a `profile.reload` before you run `profile.update!`?

**Comment by pbeast** [comment]
`Fastfile:1622:in 'block in parsing_binding': [!] undefined method 'reload' for #<Spaceship::Portal::ProvisioningProfile::Development:0x00007f917fb5b978> (NoMethodError)`

fastlane version: 2.71.0

**Comment by pbeast** [comment]
Guys, the issue is still there :-)
The problem could be fixed by rolling back the following piece of code:
`@csrf_cache ||= {}` to `@csrf_cache || {}` (Introduced in 'Ensure CSRF tokens are cached #10720')

I understand that cancels the CSRF tokens caching idea, but looks like, tokens are being updated by server more frequent than you thought.

**Comment by KrauseFx** [comment]
Hey @pbeast, sorry it's not something we can investigate on our side unfortunately, since it doesn't seem to affect any of the _fastlane_ tools, but only in certain ways _spaceship_ is used. However feel free to prepare a PR and we're happy to review & merge it. I'd not like to see a revert of the PR, but instead a fix of the actual problem that's cause the request to fail.

**Comment by KrauseFx** [comment]
> So, probably the easiest fix is to force the token update by always calling PortalClient::fetch_csrf_token_for_provisioning at the beginning of PortalClient::repair_provisioning_profile!, regardless to cache state

Sounds like a great approach to me :) Wanna submit a PR for it? 👍

**Comment by pbeast** [comment]
Will do

Regards,
Pavel Yankelevich

**Comment by KrauseFx** [comment]
Thanks @pbeast  ❤️ 🚀
