### ISSUE TITLE
Promoting build from beta/alpha to production with rollout goes wrong

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#11170]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I wrote a script that promotes a build from beta to production, you can set the rollout ratio and as expected it would send the beta build to production as an staged release.
But the command send it to 100%...

### Souce code

Code used to push the beta build to production:

```ruby

selectedPackageName = "com.my.app"
metadataPath = "...."
rollout = 0.1

supply(
  track: "beta",
  track_promote_to: "production",
  rollout: "#{rollout}",
  package_name: selectedPackageName,
  metadata_path: "./fastlane#{metadataPath}",
  skip_upload_apk: true,
  skip_upload_metadata: true,
  skip_upload_images: true,
  skip_upload_screenshots: true)
```

Code used to send the build to beta:

```ruby

selectedPackageName = "com.my.app"
apkPath = "..."
mapping="..."
metadataPath = "...."

supply(
  track: 'beta', 
  package_name: selectedPackageName,
  apk: apkPath,
  mapping: mapping,
  metadata_path: "./fastlane#{metadataPath}")
```

Log:

![bug](https://user-images.githubusercontent.com/5521682/33842469-87bb114c-de92-11e7-849a-41304e33a6da.png)

I don't know if I did something wrong or this is a expected behaviour. 
And yes, our app has been released to 100%. Luckly the staged release wasn't critical.

Thanks!

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| CFPropertyList             | 2.3.5        |
| activesupport              | 4.2.10       |
| addressable                | 2.5.2        |
| babosa                     | 1.0.2        |
| bigdecimal                 | 1.2.6        |
| bundler                    | 1.14.6       |
| claide                     | 1.0.2        |
| cocoapods                  | 1.3.1        |
| cocoapods-core             | 1.3.1        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.3        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| cocoapods-trunk            | 1.3.0        |
| cocoapods-try              | 1.1.0        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| commander-fastlane         | 4.4.5        |
| concurrent-ruby            | 1.0.5        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| domain_name                | 0.5.20170404 |
| dotenv                     | 2.2.1        |
| escape                     | 0.0.4        |
| excon                      | 0.59.0       |
| faraday                    | 0.13.1       |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.11.0.1     |
| fastimage                  | 2.1.0        |
| fastlane-plugin-versioning | 0.3.0        |
| fourflusher                | 2.0.1        |
| fuzzy_match                | 2.0.4        |
| gh_inspector               | 1.0.3        |
| google-api-client          | 0.13.6       |
| googleauth                 | 0.5.1        |
| highline                   | 1.7.8        |
| http-cookie                | 1.0.3        |
| httpclient                 | 2.8.3        |
| hurley                     | 0.2          |
| i18n                       | 0.8.6        |
| io-console                 | 0.4.3        |
| json                       | 1.8.1        |
| jwt                        | 2.1.0        |
| jwt                        | 1.5.6        |
| libxml-ruby                | 3.0.0        |
| little-plugger             | 1.1.4        |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| mime-types                 | 3.1          |
| mime-types-data            | 3.2016.0521  |
| mini_magick                | 4.5.1        |
| minitest                   | 5.4.3        |
| molinillo                  | 0.5.7        |
| multi_json                 | 1.12.2       |
| multi_xml                  | 0.6.0        |
| multipart-post             | 2.0.0        |
| nanaimo                    | 0.2.3        |
| nap                        | 1.1.0        |
| netrc                      | 0.11.0       |
| nokogiri                   | 1.5.6        |
| os                         | 0.9.6        |
| plist                      | 3.3.0        |
| power_assert               | 0.2.2        |
| psych                      | 2.0.8        |
| public_suffix              | 2.0.5        |
| rake                       | 10.4.2       |
| rdoc                       | 4.2.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| rouge                      | 2.0.7        |
| rouge                      | 1.11.1       |
| ruby-macho                 | 1.1.0        |
| rubygems-update            | 2.5.2        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| signet                     | 0.7.3        |
| slack-notifier             | 1.5.1        |
| sqlite3                    | 1.3.13       |
| terminal-notifier          | 1.8.0        |
| terminal-table             | 1.7.3        |
| test-unit                  | 3.0.8        |
| thread_safe                | 0.3.6        |
| tty-screen                 | 0.6.3        |
| tzinfo                     | 1.2.3        |
| uber                       | 0.1.0        |
| unf                        | 0.1.4        |
| unf_ext                    | 0.0.7.4      |
| unicode-display_width      | 1.3.0        |
| unicode-display_width      | 1.1.3        |
| word_wrap                  | 1.0.0        |
| xcodeproj                  | 1.5.2        |
| xcpretty                   | 0.2.6        |
| xcpretty-travis-formatter  | 0.0.4        |
</details>

*generated on:* **2017-12-11**
</details>

**Comment by lacostej** [comment]
I haven't used this feature, but it looks like the percentage is used when using the `rollout` track

https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L26

It seems to be confirmed here:

https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L156-L165

where the non rollout tracks are getting 100%.
