### ISSUE TITLE
Why is there Pilot and TestFlight actions

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#1118]
It appears `Pilot` and `TestFlight` actions mostly do the same things, especially because the documentation for deliver says "Use `Pilot`" and then the next action is `TestFlight`

**Comment by vpolouchkine** [comment]
TestFlight is actually just an alias for Pilot.

**Comment by KrauseFx** [comment]
Thanks @vpolouchkine :+1:

**Comment by KrauseFx** [comment]
Oh, we should actually improve the documentation for that
