### ISSUE TITLE
Allow posting developer responses

### ISSUE THREAD

**Issue by jayrhynas** [fastlane/fastlane#11187]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I propose adding new methods to Spaceship to allow posting developer responses to app reviews.

I have tried searching for existing issues regarding this feature, and I haven't found anything, although it is hard to effectively search for the terms "developer, response, review" without many false positives. I apologize if this issue has already been discussed.

I looked into the request when posting responses and they seem to take this format:

#### Creating a response:
Request:

    POST ra/apps/#{app_id}/platforms/#{platform}/reviews/#{review_id}/responses
    {
      "responseText": "#{response_text}",
      "reviewId": "#{review_id}"
    }

Response (success):

    201 Created
    {
      "data": null,
      "messages": {
        "warn": null,
        "info": ["Successfully created new response"],
        "error": null
      },
      "statusCode": "SUCCESS"
    }

#### Editing a response:
Request:

    PUT ra/apps/#{app_id}/platforms/#{platform}/reviews/#{review_id}/responses/#{response_id}
    {
      "responseText": "#{response_text}"
    }

Response (success):

    200 OK
    {
      "data": {
        "responseText": "<response text>",
        "reviewId": 0
      },
      "messages": {
        "warn": null,
        "info": ["Successfully updated"],
        "error": null
      },
      "statusCode": "SUCCESS"
    }

> *Note: the* ```responseId``` *will change after updating, and therefore should be re-fetched via the review*

I can try to take a stab at creating a PR for this myself, although I'm not sure exactly where to get started with adding a new method to Spaceship.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.5        |
</details>

*generated on:* **2017-12-12**
</details>

**Comment by taquitos** [comment]
@jayrhynas, that would be amazing! We have some information on how to use common tools for debugging Spaceship issues: (https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md)
but we don't really have a guide for how to modify Spaceship beyond this: https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md

Most of the classes are really well documented and have comments, but if you find yourself stuck, feel free to reach out to us! 

I would start here: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb
I would also consider adding a method on `client.rb` and calling that from the app. Kinda like this (found in application.rb):

```
      # set the price tier. This method doesn't require `save` to be called
      def update_price_tier!(price_tier)
        client.update_price_tier!(self.apple_id, price_tier)
      end
```

**Comment by jayrhynas** [comment]
I have started work on this but haven't had time to finish it; needing to test it on a live app slows things down too. I don't believe anyone else has implemented this, and so the issue should not be closed yet

**Comment by KrauseFx** [comment]
Hey peeps, actually we will not allow this feature as part of _fastlane_, as it will be abused by developers for things Apple didn't want the developer responses to use for.

We had an open PR we didn't merge also https://github.com/fastlane/fastlane/pull/9036

Developers would use it to automatically "spam" responses with generic responses, and I'm sure Apple wouldn't be happy about it. With _fastlane_ we're trying to help with your app deployment and app management, everything in the best interests of Apple I'd say. 

For now, I'm gonna close this PR, thanks for the idea, and discussion here 👍
