### ISSUE TITLE
Pass app identifier to match function in Fastfile

### ISSUE THREAD

**Issue by eman6576** [fastlane/fastlane#11197]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
 When calling `match` in a Fastfile, the parameter type for `app_identifier` has changed to `Array`. I tried passing in something like this `Array[fabric_bundle_identifier]`, but I still get `'app_identifier' value must be a Array! Found String instead.`. What is the correct value to pass to the parameter?

### Captured Output

Command Used: `update_test_devices`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/emanuel/Desktop/SilverLogic/Bitbucket/iOS/baseapp-ios-v2/fastlane/Appfile'
- app_identifier: 'com.silverlogic.BaseAppV2'
- apple_id: 'apple@tsl.io'
- team_id: '4SB3F2S2K3'
-------

+----------------+----------------------------------------------------------------------------------------+
|                               Detected Values from './fastlane/Matchfile'                               |
+----------------+----------------------------------------------------------------------------------------+
| git_url        | ssh://git@bitbucket.org/silverlogic/baseapp-ios-provisioning-profiles-certificates.git |
| app_identifier | com.silverlogic.BaseAppV2                                                              |
| username       | apple@tsl.io                                                                           |
+----------------+----------------------------------------------------------------------------------------+


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | register_devices                    | 3           |
| 💥   | match                               | 0           |
| 5    | slack                               | 0           |
+------+-------------------------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.2"

default_platform :ios

platform :ios do

  # Called before requested lane runs
  before_all do
    ENV["SLACK_URL"] = ENV["SLACK_HOOK"]
  end

  # Avaliable Lanes
  desc "Deploy Staging Build To Fabric"
  lane :fabric do

    # Install dependencies
    cocoapods

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    application_scheme = ENV["APPLICATION_SCHEME_NAME"]
    fabric_developer_email = ENV["FABRIC_DEVELOPER_EMAIL"]
    fabric_developer_team_id = ENV["FABRIC_DEVELOPER_TEAM_ID"]
    fabric_bundle_identifier = ENV["FABRIC_BUNDLE_IDENTIFIER"]
    fabric_api_token = ENV["FABRIC_API_TOKEN"]
    fabric_build_secret = ENV["FABRIC_BUILD_SECRET"]

    # Create the application on Apple Developer Portal
    produce(username: fabric_developer_email,
            app_identifier: fabric_bundle_identifier,
            app_name: application_name,
            team_id: fabric_developer_team_id,
            skip_itc: true)

    # Load provisioning profiles and certificates
    match(app_identifier: fabric_bundle_identifier,
          username: fabric_developer_email,
          readonly: true,
          type: "adhoc")

    # Disable automatic code signing
    disable_automatic_code_signing(path: "BaseAppV2.xcodeproj")

    # Auto increment build number
    increment_build_number

    # Generate archive
    specifier = "sigh_#{fabric_bundle_identifier}_adhoc"
    provisioning_profile_specifier = ENV[specifier]
    gym(scheme: application_scheme,
        export_method: "ad-hoc",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER=#{provisioning_profile_specifier}")

    # Get release notes
    release_notes = sh "cd .. && ./get_latest_release_notes.sh"

    # Upload to Fabric
    crashlytics(api_token: fabric_api_token,
                build_secret: fabric_build_secret,
                notes: release_notes,
                groups: ["fav","loki","sparkle", ENV["FABRIC_CLIENT_GROUP_ALIAS"]])

  end

  desc "Deploy Production Build To iTunes Connect"
  lane :itunes_connect do

     # Install dependencies
     cocoapods

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    application_scheme = ENV["APPLICATION_SCHEME_NAME"]
    appstore_developer_email = ENV["APPSTORE_DEVELOPER_EMAIL"]
    appstore_developer_team_id = ENV["APPSTORE_DEVELOPER_TEAM_ID"]
    appstore_bundle_identifier = ENV["APPSTORE_BUNDLE_IDENTIFIER"]

    # Create the application on iTunes Connect and Apple Developer Portal
    produce(username: appstore_developer_email,
            app_identifier: appstore_bundle_identifier,
            app_name: application_name,
            team_id: appstore_developer_team_id)

    # Load provisioning profiles and certificates
    production_branch = "#{application_name}-production"
    match(git_branch: production_branch,
          app_identifier: appstore_bundle_identifier,
          username: appstore_developer_email,
          readonly: true,
          type: "appstore")

    # Disable automatic code signing
    disable_automatic_code_signing(path: "BaseAppV2.xcodeproj")
    
    # Auto increment build number
    increment_build_number

    # Generate screenshots
    # UITest will need to change for screenshots the client wants
    snapshot(scheme: "BaseAppV2UITests")

    # Generate archive
    specifier = "sigh_#{appstore_bundle_identifier}_appstore"
    provisioning_profile_specifier = ENV[specifier]
    gym(scheme: application_scheme,
        export_method: "app-store",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER=#{provisioning_profile_specifier}")

    # Send to iTunes Connect and submit for review
    deliver(username: appstore_developer_email,
            app_identifier: appstore_bundle_identifier,
            submit_for_review: false)

  end

  desc "Update current provisioning profile with test devices"
  lane :update_test_devices do

    # Read in values set from .env file
    fabric_developer_email = ENV["FABRIC_DEVELOPER_EMAIL"]
    fabric_bundle_identifier = ENV["FABRIC_BUNDLE_IDENTIFIER"]

    # Register devices for the provisiong profile to use
    register_devices(devices_file: "fastlane/devices.txt")

    # Update the provisioning profile
    # Value `app_identifier` will change for Silverlogic development
    identifiers = Array[fabric_bundle_identifier]
    puts "#{identifiers}"
    match(app_identifier: "#{identifiers}",
          username: fabric_developer_email,
          force_for_new_devices: true,
          type: "adhoc")
  end

  desc "Generate adhoc provisioning profile for Fabric builds"
  lane :generate_fabric_profile do

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    fabric_developer_email = ENV["FABRIC_DEVELOPER_EMAIL"]
    fabric_developer_team_id = ENV["FABRIC_DEVELOPER_TEAM_ID"]
    fabric_bundle_identifier = ENV["FABRIC_BUNDLE_IDENTIFIER"]

    # Create the application on Apple Developer Portal
    produce(username: fabric_developer_email,
            app_identifier: fabric_bundle_identifier,
            app_name: application_name,
            team_id: fabric_developer_team_id,
            skip_itc: true)

    # Create provisioning profiles and certificates
    match(app_identifier: fabric_bundle_identifier,
          username: fabric_developer_email,
          type: "adhoc")

  end

  desc "Generate appstore provisioning profile for AppStore builds"
  lane :generate_appstore_profile do

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    appstore_developer_email = ENV["APPSTORE_DEVELOPER_EMAIL"]
    appstore_developer_team_id = ENV["APPSTORE_DEVELOPER_TEAM_ID"]
    appstore_bundle_identifier = ENV["APPSTORE_BUNDLE_IDENTIFIER"]

    # Create the application on iTunes Connect and Apple Developer Portal
    produce(username: appstore_developer_email,
            app_identifier: appstore_bundle_identifier,
            app_name: application_name,
            team_id: appstore_developer_team_id)

    # Generate provisioning profiles and certificates
    production_branch = "#{application_name}-production"
    match(git_branch: production_branch,
          app_identifier: appstore_bundle_identifier,
          username: appstore_developer_email,
          type: "appstore")
  end

  # Called if requested lane runs successfully
  after_all do |lane|
    if lane == :fabric
      slack(message: "Successfully deployed to Fabric! 🎉")
    elsif lane == :update_test_devices
      slack(message: "Successfully updated provisiong profile with test devices! 🎉")
    elsif lane == :itunes_connect
      slack(message: "Successfully deployed to iTunes Connect! 🎉")
    elsif lane == :generate_fabric_profile
      slack(message: "Successfully generated provisioning profile for Fabric! 🎉")
    else
      slack(message: "Successfully generated provisioning profile for AppStore! 🎉")
    end
  end

  # Called if requested lane failed
  error do |lane, exception|
    slack(message: exception.message, success: false)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.silverlogic.BaseAppV2" # The bundle identifier of your app
apple_id "apple@tsl.io" # Your Apple email address

team_id "4SB3F2S2K3"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.69.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| excon                     | 0.57.0       |
| bigdecimal                | 1.2.8        |
| psych                     | 2.0.17       |
</details>

*generated on:* **2017-12-12**
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.2"

default_platform :ios

platform :ios do

  # Called before requested lane runs
  before_all do
    ENV["SLACK_URL"] = ENV["SLACK_HOOK"]
  end

  # Avaliable Lanes
  desc "Deploy Staging Build To Fabric"
  lane :fabric do

    # Install dependencies
    cocoapods

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    application_scheme = ENV["APPLICATION_SCHEME_NAME"]
    fabric_developer_email = ENV["FABRIC_DEVELOPER_EMAIL"]
    fabric_developer_team_id = ENV["FABRIC_DEVELOPER_TEAM_ID"]
    fabric_bundle_identifier = ENV["FABRIC_BUNDLE_IDENTIFIER"]
    fabric_api_token = ENV["FABRIC_API_TOKEN"]
    fabric_build_secret = ENV["FABRIC_BUILD_SECRET"]

    # Create the application on Apple Developer Portal
    produce(username: fabric_developer_email,
            app_identifier: fabric_bundle_identifier,
            app_name: application_name,
            team_id: fabric_developer_team_id,
            skip_itc: true)

    # Load provisioning profiles and certificates
    match(app_identifier: fabric_bundle_identifier,
          username: fabric_developer_email,
          readonly: true,
          type: "adhoc")

    # Disable automatic code signing
    disable_automatic_code_signing(path: "BaseAppV2.xcodeproj")

    # Auto increment build number
    increment_build_number

    # Generate archive
    specifier = "sigh_#{fabric_bundle_identifier}_adhoc"
    provisioning_profile_specifier = ENV[specifier]
    gym(scheme: application_scheme,
        export_method: "ad-hoc",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER=#{provisioning_profile_specifier}")

    # Get release notes
    release_notes = sh "cd .. && ./get_latest_release_notes.sh"

    # Upload to Fabric
    crashlytics(api_token: fabric_api_token,
                build_secret: fabric_build_secret,
                notes: release_notes,
                groups: ["fav","loki","sparkle", ENV["FABRIC_CLIENT_GROUP_ALIAS"]])

  end

  desc "Deploy Production Build To iTunes Connect"
  lane :itunes_connect do

     # Install dependencies
     cocoapods

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    application_scheme = ENV["APPLICATION_SCHEME_NAME"]
    appstore_developer_email = ENV["APPSTORE_DEVELOPER_EMAIL"]
    appstore_developer_team_id = ENV["APPSTORE_DEVELOPER_TEAM_ID"]
    appstore_bundle_identifier = ENV["APPSTORE_BUNDLE_IDENTIFIER"]

    # Create the application on iTunes Connect and Apple Developer Portal
    produce(username: appstore_developer_email,
            app_identifier: appstore_bundle_identifier,
            app_name: application_name,
            team_id: appstore_developer_team_id)

    # Load provisioning profiles and certificates
    production_branch = "#{application_name}-production"
    match(git_branch: production_branch,
          app_identifier: appstore_bundle_identifier,
          username: appstore_developer_email,
          readonly: true,
          type: "appstore")

    # Disable automatic code signing
    disable_automatic_code_signing(path: "BaseAppV2.xcodeproj")
    
    # Auto increment build number
    increment_build_number

    # Generate screenshots
    # UITest will need to change for screenshots the client wants
    snapshot(scheme: "BaseAppV2UITests")

    # Generate archive
    specifier = "sigh_#{appstore_bundle_identifier}_appstore"
    provisioning_profile_specifier = ENV[specifier]
    gym(scheme: application_scheme,
        export_method: "app-store",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER=#{provisioning_profile_specifier}")

    # Send to iTunes Connect and submit for review
    deliver(username: appstore_developer_email,
            app_identifier: appstore_bundle_identifier,
            submit_for_review: false)

  end

  desc "Update current provisioning profile with test devices"
  lane :update_test_devices do

    # Read in values set from .env file
    fabric_developer_email = ENV["FABRIC_DEVELOPER_EMAIL"]
    fabric_bundle_identifier = ENV["FABRIC_BUNDLE_IDENTIFIER"]

    # Register devices for the provisiong profile to use
    register_devices(devices_file: "fastlane/devices.txt")

    # Update the provisioning profile
    # Value `app_identifier` will change for Silverlogic development
    identifiers = Array[fabric_bundle_identifier]
    puts "#{identifiers}"
    match(app_identifier: "#{identifiers}",
          username: fabric_developer_email,
          force_for_new_devices: true,
          type: "adhoc")
  end

  desc "Generate adhoc provisioning profile for Fabric builds"
  lane :generate_fabric_profile do

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    fabric_developer_email = ENV["FABRIC_DEVELOPER_EMAIL"]
    fabric_developer_team_id = ENV["FABRIC_DEVELOPER_TEAM_ID"]
    fabric_bundle_identifier = ENV["FABRIC_BUNDLE_IDENTIFIER"]

    # Create the application on Apple Developer Portal
    produce(username: fabric_developer_email,
            app_identifier: fabric_bundle_identifier,
            app_name: application_name,
            team_id: fabric_developer_team_id,
            skip_itc: true)

    # Create provisioning profiles and certificates
    match(app_identifier: fabric_bundle_identifier,
          username: fabric_developer_email,
          type: "adhoc")

  end

  desc "Generate appstore provisioning profile for AppStore builds"
  lane :generate_appstore_profile do

    # Read in values set from .env file
    application_name = ENV["APPLICATION_NAME"]
    appstore_developer_email = ENV["APPSTORE_DEVELOPER_EMAIL"]
    appstore_developer_team_id = ENV["APPSTORE_DEVELOPER_TEAM_ID"]
    appstore_bundle_identifier = ENV["APPSTORE_BUNDLE_IDENTIFIER"]

    # Create the application on iTunes Connect and Apple Developer Portal
    produce(username: appstore_developer_email,
            app_identifier: appstore_bundle_identifier,
            app_name: application_name,
            team_id: appstore_developer_team_id)

    # Generate provisioning profiles and certificates
    production_branch = "#{application_name}-production"
    match(git_branch: production_branch,
          app_identifier: appstore_bundle_identifier,
          username: appstore_developer_email,
          type: "appstore")
  end

  # Called if requested lane runs successfully
  after_all do |lane|
    if lane == :fabric
      slack(message: "Successfully deployed to Fabric! 🎉")
    elsif lane == :update_test_devices
      slack(message: "Successfully updated provisiong profile with test devices! 🎉")
    elsif lane == :itunes_connect
      slack(message: "Successfully deployed to iTunes Connect! 🎉")
    elsif lane == :generate_fabric_profile
      slack(message: "Successfully generated provisioning profile for Fabric! 🎉")
    else
      slack(message: "Successfully generated provisioning profile for AppStore! 🎉")
    end
  end

  # Called if requested lane failed
  error do |lane, exception|
    slack(message: exception.message, success: false)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.silverlogic.BaseAppV2" # The bundle identifier of your app
apple_id "apple@tsl.io" # Your Apple email address

team_id "4SB3F2S2K3"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.69.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| excon                     | 0.57.0       |
</details>

*generated on:* **2017-12-12**
</details>

**Comment by robertjpayne** [comment]
Same issue here!

**Comment by joeldrotleff** [comment]
If you change your code from:
`match(app_identifier: "co.myapp", readonly: true, type: "development")`

to:
`match(app_identifier: ["co.myapp"], readonly: true, type: "development")`

that seems to fix the issue

**Comment by robertjpayne** [comment]
@joeldrotleff did you actually try that? I tried that and still no luck on my end.

**Comment by eman6576** [comment]
@joeldrotleff That does not work for me

**Comment by sketch34** [comment]
Same problem here. I've tried this in the `Matchfile` with the same error message. 

```app_identifier ["com.my.App"]```

This is the same format as generated by `fastlane match init`. Result:

`[!] 'app_identifier' value must be a Array! Found String instead.`

**Comment by jordanebelanger** [comment]
Having the same issue here.

**Comment by mrjman** [comment]
Hit the same error here.

Updating the Matchfile to `app_identifier ["com.my.app"]` did seem to fix the issue. However I then ran into another error `[!] undefined method 'to_plist' for Gym::PackageCommandGeneratorXcode7:Class`

Dropped back to 2.68 and all errors are gone.

If you need to drop back on circle CI you can use:
```
dependencies:
  pre:
    - sudo gem install fastlane -v '~> 2.68.0'
```

**Comment by timothystewart6** [comment]
thanks @mrjman!  Rolling back to `2.68.2` fixed it for me

**Comment by robindirksen1** [comment]
To install specific version of fastlane run:

```
gem uninstall fastlane --all --executables
gem install fastlane --version 2.18.3 --no-document
```

And make sure `update_fastlane` isset to false.

@mrjman thanks it worked after downgrading.

**Comment by gcmleon** [comment]
Same issue here, I wanted to run `fastlane match nuke development` but it fails due to this error. I tried changing the app_identifier to ["com.my.app"] on the Matchfile and the Appfile but it didn't work.

**Comment by bimusiek** [comment]
Same here, the only way is to downgrade. 👎

**Comment by taquitos** [comment]
Sorry, about to roll out a fix for this

**Comment by taquitos** [comment]
`2.69.2` is released with a fix for this issue. You should be able to go back to using either a `String` or `Array`

**Comment by bimusiek** [comment]
`2.69.2` works 👍

**Comment by taquitos** [comment]
So sorry about that, thank you for confirming 🎈:goat:

**Comment by bimusiek** [comment]
I just wonder after looking at your commit, why `["identifier"]` did not work. 😎  I changed all strings to arrays in `Fastfile`.

**Comment by taquitos** [comment]
I'm wondering the same thing, it should work. That being said, the ability to pass in an array was written a long time ago, and maybe that code path hasn't been flexed in a while since I think like 99.9% of the use cases are for a `String`

It's something we'll be looking into because Swift fastfile support passes an `Array` sooo it better work!

**Comment by eman6576** [comment]
@taquitos The fix works. 🎉

**Comment by timothystewart6** [comment]
Thanks!  This was closed by https://github.com/fastlane/fastlane/pull/11212
