### ISSUE TITLE
Remove html from Match README

### ISSUE THREAD

**Issue by krazik** [fastlane/fastlane#11196]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Bitbucket doesn't support HTML in markdown so the table in the fastline match readme doesn't render.  Ideally switch to native markdown.

##### Complete output when running fastlane, including the stack trace and command used
![image](https://user-images.githubusercontent.com/1224164/33910316-2e010312-df43-11e7-96f7-18127256468c.png)

### Environment
Bitbucket

**Comment by krazik** [comment]
fastlane creates a readme in the fastlane directory with html in it.
it also creates one in the match repository.  see:
 https://github.com/fastlane/fastlane/blob/master/match/lib/assets/READMETemplate.md

so these are my repo's not the fastlane ones. my company has chosen to use bitbucket.  so the file that is committed isn't visible.  you can see in my screen shot.

let me know if unclear still.
thanks!
-Rylan

**Comment by janpio** [comment]
Ah, now it's clearer what you mean - and I can actually reproduce this as my certificate repo also lives on Bitbucket ;)

Do you want to take a shot at modifying the template file? You can even do it directly on Github, it will create a fork automatically when you edit the file. Then send a PR and refer to this issue in the description. Thanks!

**Comment by krazik** [comment]
sure I'll pr it.

**Comment by krazik** [comment]
done, closing this for the pr.
