### ISSUE TITLE
Migration of Ruby fastlane to Swift fastlane (rb_file_s_stat)

### ISSUE THREAD

**Issue by steprescott** [fastlane/fastlane#11203]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x]  I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Attempting to migrate over from the ruby fastlane to use the swift beta fastlane. When following the steps below it results in:
```
Ran into error while trying to connect to iTunes Connect / Dev Portal: No such file or directory @ rb_file_s_stat
```

Some suggestions from other issues say simply delete any apps on iTunes connect or use alternative details but as this is a migration I can not simply nuke iTunes connect or use different details.

### Steps taken

- I deleted the `fastlane/` directory
- ran `fastlane init swift`
- Fell back to manual setup
- Entered all the details
- Said no to deliver
 
<details><summary>Console output</summary>

```
[10:28:42]: Created new file './fastlane/Appfile.swift'. Edit it to manage your preferred app metadata information.
[10:28:42]: Do you want to setup 'deliver', which is used to upload app screenshots, app metadata and app updates to the App Store? This requires the app to be in the App Store already (y/n)
n
[10:28:45]: Optional: The scheme name of your app (If you don't need one, just hit Enter): XXX
[10:28:49]: 'snapshot' not enabled.
[10:28:49]: 'cocoapods' not enabled.
[10:28:49]: 'carthage' enabled.
[10:28:49]: Created new file './fastlane/Fastfile.swift'. Edit it to manage your own deployment lanes.
[10:28:49]: Error occurred with the setup program! Reverting changes now!
[10:28:49]: Moving './fastlane/screenshots' to 'screenshots'
[10:28:49]: Moving './fastlane/metadata' to 'metadata'
[10:28:49]: Deleting the 'fastlane' folder

[10:28:49]: Error accessing file, this might be due to fastlane's directory handling
[10:28:49]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

~/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1225:in `stat': No such file or directory @ rb_file_s_stat - ~/.rvm/gems/ruby-2.4.2@ios-dev/gems/fastlane-2.69.0/fastlane/swift/. (Errno::ENOENT)
```
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.13.2                                            |
| Ruby                        | 2.4.2                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.14.3 (Apple Git-98)                  |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2@ios-dev/bin/fastlane |
| Host                        | Mac OS X 10.13.2 (17C88)                           |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                       |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                         |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version               | 9.2                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.69.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2017-12-13**
</details>

**Comment by hartbit** [comment]
Same here.

**Comment by javialgaba** [comment]
This issue is still open even after updating to fastlane 2.69.1

**Comment by taquitos** [comment]
Taking a look at this

**Comment by PorterHoskins** [comment]
Same issue

**Comment by PorterHoskins** [comment]
I ran into an error at the same point but it was a little different. I'm on 2.69.2:

```
Ran into error while trying to connect to iTunes Connect / Dev Portal: unknown file type
```

Console Output:
```
[09:52:07]: Created new file './fastlane/Fastfile.swift'. Edit it to manage your own deployment lanes.
[09:52:07]: Ran into error while trying to connect to iTunes Connect / Dev Portal: unknown file type: ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.69.2/fastlane/swift/.
[09:52:07]: Falling back to manual onboarding
[09:52:07]: unknown file type: ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.69.2/fastlane/swift/.
[09:52:07]: An error occurred during the setup process. Falling back to manual setup!
```

**Comment by KrauseFx** [comment]
I actually ran into the same problem on my other Mac last night - I changed the installation method and it worked. Are you using a `Gemfile`? If not, could you give it a try (https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile) and see if that solves the problem, when running _fastlane_ using `bundle exec fastlane ...`

**Comment by slashmo** [comment]
@KrauseFx I ran it with `bundle exec` but I got the exact same error message again.
> Ran into error while trying to connect to iTunes Connect / Dev Portal: No such file or directory @ rb_file_s_stat - /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.2/fastlane/swift/

**Comment by jdee** [comment]
The `fastlane/swift` folder is not part of the gem, and @KrauseFx is probably working from a local repo. PR incoming...

**Comment by taquitos** [comment]
> The fastlane/swift folder is not part of the gem, and @KrauseFx is probably working from a local repo. PR incoming...

^ you nailed it, @taquitos was working from a local repo 🤦‍♂️
