### ISSUE TITLE
Gym fails with verbose logging

### ISSUE THREAD

**Issue by farkasseb** [fastlane/fastlane#11204]
### Gym fails with verbose logging

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
As I was running `bundle exec fastlane gym --verbose` I got the following error.

```
Undefined method `to_plist' for Gym::PackageCommandGeneratorXcode7:Class
```

<details><summary>Error output</summary>

```
NoMethodError: [!] undefined method `to_plist' for Gym::PackageCommandGeneratorXcode7:Class
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:188:in `config_content'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:20:in `generate'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/generators/package_command_generator.rb:16:in `generate'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/runner.rb:107:in `package_app'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/runner.rb:20:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/manager.rb:14:in `work'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/commands_generator.rb:72:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/gym/lib/gym/commands_generator.rb:12:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/fastlane/lib/fastlane/cli_tools_distributor.rb:67:in `take_off'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.69.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<top (required)>'
```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.69.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2017-12-13**
</details>

**Comment by GandjaFuzz** [comment]
have this problem too

**Comment by adebree** [comment]
Having this problem after upgrading to 2.69.0. Removed --verbose from the invocation to workaround this issue.
