### ISSUE TITLE
Action for cocoapods repos refresh

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#1121]
It would be great to add a new action (or add a parameter to `cocoapods`) to run pods repos refresh manually. Sometimes [`pod install` takes forever](http://stackoverflow.com/questions/23755974/cocoapods-pod-install-takes-forever). I run into that issue on a Travis-CI instance, pod install took ~5 minutes. This could be cured by calling this 3 commands:
```shell
pod repo remove master
pod setup
pod install --no-repo-update
```
This 3 commands took less than 2 minutes, wich is really a fantastic improvement!

**Comment by KrauseFx** [comment]
Sure, just use
```ruby
cocoapods(repo_update: false)
```

**Comment by Sega-Zero** [comment]
But it's for last command only. it would be much more handy if I could use something like 
```ruby
cocoapods(repo_refresh: true, repo_update: false)
```
instead of
```ruby
sh "pod repo remove master"
sh "pod setup"
cocoapods(repo_update: false)
```

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
