### ISSUE TITLE
unknown file type

### ISSUE THREAD

**Issue by Bheem-singh-26** [fastlane/fastlane#11232]
I have install fastlane using:   brew cask install fastlane

but i am getting error which log i have pasted below when doing : fastlane init swift

[14:14:17]: 'snapshot' not enabled.
[14:14:17]: 'cocoapods' enabled.
[14:14:17]: 'carthage' not enabled.
[14:14:17]: Created new file './fastlane/Fastfile.swift'. Edit it to manage your own deployment lanes.
[14:14:17]: Ran into error while trying to connect to iTunes Connect / Dev Portal: unknown file type: /Users/bheemsingh/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.69.2/fastlane/swift/.
[14:14:17]: Falling back to manual onboarding
[14:14:17]: unknown file type: /Users/bheemsingh/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.69.2/fastlane/swift/.
[14:14:17]: An error occurred during the setup process. Falling back to manual setup!
[14:14:17]: App Identifier (com.krausefx.app): com.tikkle.tikkle
[14:14:38]: Created new file './fastlane/Appfile.swift'. Edit it to manage your preferred app metadata information.
[14:14:38]: Do you want to setup 'deliver', which is used to upload app
screenshots, app metadata and app updates to the App Store? This requires the app to
be in the App Store already (y/n)
y
[14:14:40]: Loading up 'deliver', this might take a few seconds
[14:14:40]: Login to iTunes Connect (shashankpachore@gmail.com)
[14:14:44]: Login successful

**Comment by Bheem-singh-26** [comment]
Bheems-MacBook-Pro:tickle-ios bheemsingh$ fastlane env
[14:33:08]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.69.2  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.6.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-12-15**
</details>
[14:33:10]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[14:33:10]: 🙄  Wow, that's a lot of markdown text... should fastlane put it
into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[14:33:25]: Successfully copied markdown into your clipboard 🎨
[14:33:25]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.69.3 is available. You are on 2.69.2.
# You should use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################

2.69.3 Hotfix for Swift files missing from gem
* Version bump to 2.69.3 (#11227) via Joshua Liebowitz
* #11203 Add fastlane/swift to gem (#11226) via Jimmy Dee
* Workaround for missing/delayed file after `system("openssl ...")` (#11182) via Jan Piotrowski
* Improve GitHub Issue and Pull Request templates (#11214) via Iulian Onofrei

Please update using `fastlane update_fastlane`

**Comment by taquitos** [comment]
@Bheem-singh-26 thank you for the report, we _just_ fixed this issue and released a new version of fastlane (2.69.3) give that a shot.
