### ISSUE TITLE
import_from_git is not importing the correct version

### ISSUE THREAD

**Issue by NiklasWebnuts** [fastlane/fastlane#11252]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I've created a private repository called `fastlane-lanes`, which contains a bunch of lanes that I intent to use across multiple projects. However, when i try to specify which version to use using (e.g. `~> 1.0.0`), it seems that versions are sorted alphabetically, rather than by number, i.e. versions are sorted like this:

* `1.0.0`
* `1.0.1`
* `1.0.10` ⬅️  ⚠️
* `1.0.11` ⬅️  ⚠️
* `1.0.2`
* `1.0.3`
* `1.0.4`
* `1.0.5`
* `1.0.6`
* `1.0.7`
* `1.0.8`
* `1.0.9`

This causes the "newest" release to be `1.0.9` rather than `1.0.11`. I do not know if this is the case for minor and major, since I did not test this. But i suspect that it works the same. I'm importing the lanes like this:

```
import_from_git(
    url: "git@github.com:my-org/fastlane-lanes.git",
    version: "~> 1.0.0"
)
```

### Captured Output

Command Used: `install`
<details><summary>Output/Log</summary>

```

DEBUG [2017-12-18 16:10:07.72]: Checking if there are any plugins that should be loaded...
DEBUG [2017-12-18 16:10:07.72]: Loading 'fastlane-plugin-upgrade_super_old_xcode_project' plugin
INFO [2017-12-18 16:10:07.77]: gem 'fastlane-plugin-upgrade_super_old_xcode_project' is already installed
DEBUG [2017-12-18 16:10:07.78]: Loading 'fastlane-plugin-ftp' plugin
INFO [2017-12-18 16:10:07.83]: gem 'fastlane-plugin-ftp' is already installed
+-------------------------------------------------+---------+---------------------------------+
|                                        Used plugins                                         |
+-------------------------------------------------+---------+---------------------------------+
| Plugin                                          | Version | Action                          |
+-------------------------------------------------+---------+---------------------------------+
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2   | upgrade_super_old_xcode_project |
| fastlane-plugin-ftp                             | 0.1.3   | ftp                             |
+-------------------------------------------------+---------+---------------------------------+

Successfully loaded Appfile at path '/Users/niklas/Documents/git/my-project/fastlane/Appfile'
- app_identifier: 'com.example.myapp'
- apple_id: 'me@my-org.com'
- team_id: 'my-teamid'
-------
INFO [2017-12-18 16:10:08.02]: -------------------------------------------------
INFO [2017-12-18 16:10:08.02]: --- Step: Verifying required fastlane version ---
INFO [2017-12-18 16:10:08.02]: -------------------------------------------------
INFO [2017-12-18 16:10:08.02]: Your fastlane version 2.70.0 matches the minimum requirement of 2.64.0  ✅
INFO [2017-12-18 16:10:08.05]: ------------------------------
INFO [2017-12-18 16:10:08.05]: --- Step: default_platform ---
INFO [2017-12-18 16:10:08.05]: ------------------------------
INFO [2017-12-18 16:10:08.05]: -----------------------------
INFO [2017-12-18 16:10:08.05]: --- Step: import_from_git ---
INFO [2017-12-18 16:10:08.05]: -----------------------------
INFO [2017-12-18 16:10:08.08]: Cloning remote git repo...
INFO [2017-12-18 16:10:08.08]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:my-org/fastlane-lanes.git' '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' --depth 1 -n 
INFO [2017-12-18 16:10:08.09]: ▸ Cloning into '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git'...
INFO [2017-12-18 16:10:13.07]: Fetching remote git tags...
INFO [2017-12-18 16:10:13.07]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && GIT_TERMINAL_PROMPT=0 git fetch --all --tags -q
INFO [2017-12-18 16:10:14.98]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && git tag -l
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.0
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.10
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.11
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.2
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.3
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.6
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.7
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.8
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.9
INFO [2017-12-18 16:10:14.99]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && git checkout 1.0.9 'fastlane/Fastfile'
INFO [2017-12-18 16:10:15.01]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && git checkout 1.0.9 'fastlane/actions'
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/build_ember.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/build_ios.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/correct_ember_project.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/correct_xcode_project.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/generate_changelog.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/livereload_client.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/livereload_server.rb'.
INFO [2017-12-18 16:10:16.51]: -------------------------------------------------
INFO [2017-12-18 16:10:16.51]: --- Step: Verifying required fastlane version ---
INFO [2017-12-18 16:10:16.51]: -------------------------------------------------
INFO [2017-12-18 16:10:16.51]: Your fastlane version 2.70.0 matches the minimum requirement of 2.64.0  ✅
INFO [2017-12-18 16:10:16.54]: ------------------------------
INFO [2017-12-18 16:10:16.54]: --- Step: default_platform ---
INFO [2017-12-18 16:10:16.54]: ------------------------------
INFO [2017-12-18 16:10:16.71]: Driving the lane 'ios install' 🚀
INFO [2017-12-18 16:10:16.74]: -------------------------------
INFO [2017-12-18 16:10:16.74]: --- Step: install_on_device ---
INFO [2017-12-18 16:10:16.74]: -------------------------------
INFO [2017-12-18 16:10:16.74]: $ ios-deploy --bundle /Users/niklas/Documents/git/my-project/fastlane/../.tmp/app.ipa
INFO [2017-12-18 16:10:16.76]: ▸ [....] Waiting for iOS device to be connected
INFO [2017-12-18 16:10:16.77]: ▸ [....] Using 3218dc86753d7d632d4bf5fa8e150e7373a1f75c (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'My iPhone'.
INFO [2017-12-18 16:10:16.77]: ▸ ------ Install phase ------
INFO [2017-12-18 16:10:16.77]: ▸ [  0%] Found 3218dc86753d7d632d4bf5fa8e150e7373a1f75c (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'My iPhone' connected through USB, beginning install
INFO [2017-12-18 16:10:17.02]: ▸ [  5%] Copying META-INF/ to device
INFO [2017-12-18 16:10:17.02]: ▸ [  5%] Copying META-INF/com.apple.ZipMetadata.plist to device
INFO [2017-12-18 16:10:17.02]: ▸ [  5%] Copying Payload/ to device
··· (I've excluded the rest of the build due to privacy issues) ···
INFO [2017-12-18 16:10:17.80]: ▸ [ 52%] CreatingStagingDirectory
INFO [2017-12-18 16:10:17.80]: ▸ [ 57%] ExtractingPackage
INFO [2017-12-18 16:10:17.80]: ▸ [ 60%] InspectingPackage
INFO [2017-12-18 16:10:17.82]: ▸ [ 60%] TakingInstallLock
INFO [2017-12-18 16:10:17.84]: ▸ [ 65%] PreflightingApplication
INFO [2017-12-18 16:10:17.85]: ▸ [ 65%] InstallingEmbeddedProfile
INFO [2017-12-18 16:10:17.86]: ▸ [ 70%] VerifyingApplication
INFO [2017-12-18 16:10:19.52]: ▸ [ 75%] CreatingContainer
INFO [2017-12-18 16:10:19.53]: ▸ [ 80%] InstallingApplication
INFO [2017-12-18 16:10:19.56]: ▸ [ 85%] PostflightingApplication
INFO [2017-12-18 16:10:19.56]: ▸ [ 90%] SandboxingApplication
INFO [2017-12-18 16:10:19.61]: ▸ [ 95%] GeneratingApplicationMap
INFO [2017-12-18 16:10:19.74]: ▸ [100%] Installed package /Users/niklas/Documents/git/my-project/fastlane/../.tmp/app.ipa
INFO [2017-12-18 16:10:19.74]: Deployed /Users/niklas/Documents/git/my-project/fastlane/../.tmp/app.ipa to device!
INFO [2017-12-18 16:10:19.74]: Successfully generated documentation at path '/Users/niklas/Documents/git/my-project/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | Verifying required fastlane version | 0           |
| 4    | default_platform                    | 0           |
| 5    | import_from_git                     | 8           |
| 6    | install_on_device                   | 3           |
+------+-------------------------------------+-------------+

DEBUG [2017-12-18 16:10:19.75]: All plugins are up to date
INFO [2017-12-18 16:10:19.75]: fastlane.tools finished successfully 🎉
DEBUG [2017-12-18 16:10:19.75]: All plugins are up to date


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.64.0"

default_platform :ios

import_from_git(
    url: "git@github.com:my-org/fastlane-lanes.git",
    version: "~> 1.0.0"
)

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.example.myapp" # The bundle identifier of your app
apple_id "me@my-org.com" # Your Apple email address

team_id "my-teamid" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                          | Version | Update-Status |
| ----------------------------------------------- | ------- | ------------- |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2   | ✅ Up-To-Date  |
| fastlane-plugin-ftp                             | 0.1.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                             | Version      |
| ----------------------------------------------- | ------------ |
| did_you_mean                                    | 1.1.0        |
| executable-hooks                                | 1.3.2        |
| bundler-unload                                  | 1.0.2        |
| rubygems-bundler                                | 1.4.4        |
| bundler                                         | 1.16.0       |
| io-console                                      | 0.4.6        |
| CFPropertyList                                  | 2.3.6        |
| public_suffix                                   | 2.0.5        |
| addressable                                     | 2.5.2        |
| babosa                                          | 1.0.2        |
| claide                                          | 1.0.2        |
| colored                                         | 1.2          |
| colored2                                        | 3.1.2        |
| highline                                        | 1.7.10       |
| commander-fastlane                              | 4.4.5        |
| commonjs                                        | 0.2.7        |
| declarative                                     | 0.0.10       |
| declarative-option                              | 0.1.0        |
| unf_ext                                         | 0.0.7.4      |
| unf                                             | 0.1.4        |
| domain_name                                     | 0.5.20170404 |
| dotenv                                          | 2.2.1        |
| excon                                           | 0.60.0       |
| multipart-post                                  | 2.0.0        |
| faraday                                         | 0.13.1       |
| http-cookie                                     | 1.0.3        |
| faraday-cookie_jar                              | 0.0.6        |
| faraday_middleware                              | 0.12.2       |
| fastimage                                       | 2.1.0        |
| gh_inspector                                    | 1.0.3        |
| jwt                                             | 2.1.0        |
| little-plugger                                  | 1.1.4        |
| multi_json                                      | 1.12.2       |
| logging                                         | 2.2.2        |
| memoist                                         | 0.16.0       |
| os                                              | 0.9.6        |
| signet                                          | 0.8.1        |
| googleauth                                      | 0.6.2        |
| httpclient                                      | 2.8.3        |
| mime-types-data                                 | 3.2016.0521  |
| mime-types                                      | 3.1          |
| uber                                            | 0.1.0        |
| representable                                   | 3.0.4        |
| retriable                                       | 3.1.1        |
| google-api-client                               | 0.13.6       |
| json                                            | 2.1.0        |
| mini_magick                                     | 4.5.1        |
| multi_xml                                       | 0.6.0        |
| plist                                           | 3.4.0        |
| rubyzip                                         | 1.2.1        |
| security                                        | 0.1.3        |
| slack-notifier                                  | 1.5.1        |
| terminal-notifier                               | 1.8.0        |
| unicode-display_width                           | 1.3.0        |
| terminal-table                                  | 1.8.0        |
| tty-screen                                      | 0.6.3        |
| word_wrap                                       | 1.0.0        |
| nanaimo                                         | 0.2.3        |
| xcodeproj                                       | 1.5.4        |
| rouge                                           | 2.0.7        |
| xcpretty                                        | 0.2.8        |
| xcpretty-travis-formatter                       | 1.0.0        |
| fastlane-plugin-ftp                             | 0.1.3        |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2        |
| libv8                                           | 3.16.14.19   |
| mini_portile2                                   | 2.3.0        |
| nokogiri                                        | 1.8.1        |
| ref                                             | 2.0.0        |
| therubyracer                                    | 0.12.3       |
</details>

*generated on:* **2017-12-18**
</details>

**Comment by KrauseFx** [comment]
Ah, nice catch, this seems like it's a bug in the way we parse those version numbers. It seems like the `checkout_param_twiddle_wakka` method in `fast_file.rb` does some custom parsing of the version number instead of using `Gem::Version.new`
