### ISSUE TITLE
[Regression] Crashlytics plugin "No such file or directory" when looking for Java path

### ISSUE THREAD

**Issue by fechy** [fastlane/fastlane#11255]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Changes introduced in #10861 have introduced a typo on the java path, leading to the following error.

##### Complete output when running fastlane, including the stack trace and command used
```
[20:07:41]: sh: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java}: No such file or directory
```
### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane(nightly: true)

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

default_platform :android

import "actions/Android"
import "actions/IOS"

desc "Prepares the environment for assembling a release"
lane :prepare_release do
    # Set release notes
    gradle(
        task: "releaseNotes",
        flags: '-a --no-rebuild --console=plain'
    )

    # Set the build numbers to IOS
    gradle(
        task: "setBuildNumbers",
        flags: '-a --no-rebuild --console=plain'
    )

    # Clean the environment
    gradle(
        task: "clean",
        flags: '-a --no-rebuild --console=plain'
    )
end

desc "Creates a new release branch"
lane :new_release do
    # Make sure we have all committed and pushed
    ensure_git_status_clean

    # Ask for the tag
    tag = prompt( text: "Enter tag name (i.e v0.0.0-build-0): ");
    if git_tag_exists(tag: tag)
      UI.message("Given tag already exist. Try a new one")
    else
        # Add the new tag
        add_git_tag(
            tag: tag
        )

        # Push
        push_git_tags

        # Create a new branch for the release
        sh("git checkout -b release/" + tag);
    end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "client_secret_970540180847-f7iutb9bk8bmms3gsnl0gts8abptt5ud.apps.googleusercontent.com.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.kingmonkey.machaca" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.10.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| highline                  | 1.7.10       |
| CFPropertyList            | 2.3.6        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastlane-plugin-appicon   | 0.10.0       |
</details>

*generated on:* **2017-12-18**
</details>

**Comment by KrauseFx** [comment]
Thanks for the report, caused by https://github.com/fastlane/fastlane/pull/10861, will push a fix 👍

**Comment by KrauseFx** [comment]
Awesome, thanks for the report, pushed https://github.com/fastlane/fastlane/pull/11257

**Comment by comm1x** [comment]
Error still exist in 2.70.1

**Comment by janpio** [comment]
@comm1x, please post the complete output and environment information when you are getting this error. Thank you.

**Comment by KrauseFx** [comment]
@comm1x also please share your Java environment variables

**Comment by comm1x** [comment]
@KrauseFx sorry for long answer.

```
$ env | grep JAVA
JAVA_HOME=/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/
```

This is my JAVA_HOME and there is a space in the path. I think this relates to the problem. 
I have the latest version of fastlane - 2.80.0, and my output looks like this:
![](https://simplecat.tk/shots/shot-20180209-204601.png)

I think the spaces in path is not escaping.

**Comment by comm1x** [comment]
I've not found out how to print all env-log like in first post.

**Comment by comm1x** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.109.0"
generated_fastfile_id "fa3ea32a-16de-4c61-8a1e-78a298ca99df"
default_platform :android

lane :beta do
  # Do not create fastlane/README.md
  skip_docs

  # build release
  gradle(task: "whitelabel:assembleRelease")

  # upload to crashlytics
  crashlytics(
    api_token: "...",
    build_secret: "...",
    emails: "..."
  )
end
```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| highline                  | 1.7.10       |
| excon                     | 0.60.0       |
| CFPropertyList            | 2.3.6        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| faraday                   | 0.14.0       |
| fastimage                 | 2.1.1        |
</details>


*generated on:* **2018-02-09**
</details>

**Comment by taquitos** [comment]
@comm1x could you update your variable to:
`JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/"`
as a work around for now?

**Comment by comm1x** [comment]
@taquitos Unfortunately, it is not working. I tried many variants, also with `export` and this is not helps.

**Comment by comm1x** [comment]
This bullshit bug still exists. I cant make CD because fastlane cant use JAVA_HOME with space.
Please fix it. It was working fine up to.. 2.68 maybe, and at 2.71-2.72 it broke.

**Comment by taquitos** [comment]
Yeah, sorry for the delay, we'll take a look. Thank you for pinging this issue.

**Comment by comm1x** [comment]
@taquitos Oh, many thanks, in 2.84 it has been successfully fixed, thank you!

**Comment by taquitos** [comment]
@comm1x that is fantastic to hear! Sorry it caused you trouble for this long 😞
