### ISSUE TITLE
Unable to Upload Builds to Testflight from CircleCI, 2 Factor Auth Error

### ISSUE THREAD

**Issue by amast09** [fastlane/fastlane#11256]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
About 2 weeks ago uploading builds to Testflight worked like a charm. However, for the past week I have not been able authenticate to iTunesConnect using the generated FASTLANE_SESSION environment variable. I have followed the following guide for setting up Testflight build uploads, [https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth).

I have tried generating the session on a CircleCI machine to circumvent any geo awareness of the cookie session that I saw referenced in other issues.

I have even attempted to debug Fastlane's request that is made to authenticate using the Fastlane Session Cookie Environment variable. It seems like the request ignores the environment variable that has the session cookie in it,

fastlane/spaceship/lib/spaceship/client.rb:489
`puts req.inspect`
```
#<struct Faraday::Request method=:post, path="https://idmsa.apple.com/appleauth/auth/signin", params={}, headers={"User-Agent"=>"Spaceship 2.70.0", "Content-Type"=>"application/json", "X-Requested-With"=>"XMLHttpRequest", "X-Apple-Widget-Key"=>"e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42", "Accept"=>"application/json, text/javascript"}, body="{\"accountName\":\"##@######.com\",\"password\":\"*******\",\"rememberMe\":true}", options=#<Faraday::RequestOptions timeout=300, open_timeout=300>>
``` 

Lastly I have attempted to create a brand new app-specific-password as well as session to see if it would somehow fix my issues, however this did not work either.

##### Complete output when running fastlane, including the stack trace and command used

bundle exec fastlane ios push_ipa_to_testflight --capture_output path_to_ipa:/Users/distiller/project/DEV.ipa
Please enter the 6 digit code: ^C

### Captured Output

Command Used: `ios push_ipa_to_testflight path_to_ipa:/Users/distiller/project/DEV.ipa`
<details><summary>Output/Log</summary>

```

DEBUG [2017-12-18 11:02:22.64]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/distiller/project/fastlane/Appfile'
- app_identifier: '<app-identifier>'
- apple_id: '<apple-id__email>'
- team_id: '<team-id>'
- package_name: '<app-identifier>'
-------
DEBUG [2017-12-18 11:02:22.84]: Using path_to_ipa: /Users/distiller/project/DEV.ipa
INFO [2017-12-18 11:02:22.88]: -------------------------------------------------
INFO [2017-12-18 11:02:22.88]: --- Step: Verifying required fastlane version ---
INFO [2017-12-18 11:02:22.88]: -------------------------------------------------
INFO [2017-12-18 11:02:22.88]: Your fastlane version 2.70.0 matches the minimum requirement of 2.68.2  ✅
INFO [2017-12-18 11:02:22.88]: Driving the lane 'ios push_ipa_to_testflight' 🚀
INFO [2017-12-18 11:02:22.91]: ------------------------
INFO [2017-12-18 11:02:22.91]: --- Step: testflight ---
INFO [2017-12-18 11:02:22.91]: ------------------------
INFO [2017-12-18 11:02:22.92]: Login to iTunes Connect (<apple-id__email>)
Loading session from '/Users/distiller/.fastlane/spaceship/<apple-id__email>/cookie'
Loading session from environment variable
Two Factor Authentication for account '<apple-id__email>' is enabled
Your session cookie has been expired.
WARN [2017-12-18 11:02:26.79]: Lane Context:
INFO [2017-12-18 11:02:26.79]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios push_ipa_to_testflight"}
INFO [2017-12-18 11:02:26.79]: Successfully generated documentation at path '/Users/distiller/project/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | testflight                          | 3           |
+------+-------------------------------------+-------------+

ERROR [2017-12-18 11:02:26.79]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.4.2                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.13.5 (Apple Git-94)               |
| Installation Source         | ~/project/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                        |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.2/lib                        |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.app/Contents/Developer/   |
| Xcode Version               | 9.0                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "2.68.2"
generated_directory = "fastlane/generated"
ios_project_location = "ios/Mobile.xcodeproj"
get_app_version_sh = "cat ../package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'"

def get_version_code(semver_string)
  semver_numbers = semver_string.split(".").map { |s| s.to_i }
  return (semver_numbers[0] * 100000) + (semver_numbers[1] * 1000) + semver_numbers[2]
end

platform :ios do

  desc "Build an AdHoc IPA for the App"
  lane :adhoc do
    match(
      type: "adhoc",
      readonly: true
    )
    gym(
      scheme: "Mobile",
      project: ios_project_location,
      export_method: "ad-hoc",
      configuration: "Debug",
      output_directory: "./",
      output_name: "ADHOC.ipa",
      build_path: generated_directory,
      derived_data_path: generated_directory,
      buildlog_path: generated_directory
    )
  end

  desc "Build an IPA for the App"
  lane :build do |options|
    setup_circle_ci
    match(
      type: options[:match_type],
      readonly: true
    )
    increment_build_number(
      build_number: options[:build_number].to_s,
      xcodeproj: ios_project_location
    )
    version_number = sh(get_app_version_sh)
    increment_version_number(
        xcodeproj: ios_project_location,
        version_number: version_number
    )
    gym(
      scheme: "Mobile",
      project: ios_project_location,
      export_method: options[:export_method],
      clean: true,
      skip_profile_detection: true,
      configuration: "Release",
      output_directory: "./",
      output_name: options[:ipa_name],
      build_path: generated_directory,
      derived_data_path: generated_directory,
      buildlog_path: generated_directory
    )
  end

  desc "Push Built IPA to TestFlight"
  lane :push_ipa_to_testflight do |options|
    testflight(
        groups: "BAH",
        skip_submission: true,
        skip_waiting_for_build_processing: true,
        ipa: options[:path_to_ipa]
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
  end

end

platform :android do

  desc "Build an APK for the App"
  lane :build do |options|
    version_number = sh(get_app_version_sh)
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android",
      flavor: options[:flavor],
      print_command: false,
      properties: {
        "VERSION_NAME" => version_number,
        "VERSION_CODE" => get_version_code(version_number),
        "RELEASE_STORE_FILE" => options[:store_file],
        "RELEASE_STORE_PASSWORD" => options[:store_password],
        "RELEASE_KEY_ALIAS" => options[:key_alias],
        "RELEASE_KEY_PASSWORD" => options[:key_password]
      }
    )
  end

  desc "Deploy a new version to the Google Play Store Alpha track"
  lane :push_apk_to_google_play do |options|
    supply(
      apk: options[:path_to_apk],
      json_key_data: options[:google_play_json_key],
      package_name: options[:package_name],
      track: "alpha"
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS Specific App Details
app_identifier "<app-identifier>" # The bundle identifier of your app
apple_id "<apple-id__email>" # Your Apple email address
team_id "<team-id>" # Developer Portal Team ID

# Android Specific App Details
package_name "<app-identifier>" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| method_source             | 0.9.0        |
| pry                       | 0.11.3       |
</details>

*generated on:* **2017-12-18**
</details>

Any help would be MASSIVELY appreciated. I have spent ~45hours trying to figure out why it is not working.

Thank you!

**Comment by KrauseFx** [comment]
Thanks for the report - those things are always tricky to debug for us, as it can have many reasons. One thing we noticed is that a session is specific to a region, meaning if Circle hosts their machines in the US, and you're based somewhere else, this might be the issue.

What I can also recommend as a workaround is to create a separate Apple ID without 2FA but a long, randomly generated password, with limited permissions and use that for CI only

**Comment by amast09** [comment]
@KrauseFx 

Both CircleCI as well as our local machines are in the United States.

Will a separate Apple ID without 2FA be able to upload builds to Testflight?

Thanks!

**Comment by KrauseFx** [comment]
Yeah it will work 👍 As long as the separate Apple ID has access to the app you want to upload

**Comment by amast09** [comment]
@KrauseFx 

How do I pass in the password of the CI user for [upload_to_testflight](https://docs.fastlane.tools/actions/upload_to_testflight/) to work?

Is it a separate environment variable?

Thanks for all your help!

**Comment by KrauseFx** [comment]
Yeah, it's `FASTLANE_PASSWORD` you can use 👍 it's described over here https://docs.fastlane.tools/best-practices/continuous-integration/#environment-variables-to-set

**Comment by amast09** [comment]
@KrauseFx doesn't look like there is mention of `FASTLANE_PASSWORD` in that link, not sure if docs need updated?

Attempting to run CI now with our System Apple ID user represented with,

`FASTLANE_USER`

`FASTLANE_PASSWORD`

**Comment by amast09** [comment]
YESSSS IT WORKED!!! 🎉 🎉 🎉 

Thank you for your support / help!

Not sure if you would want to update some of the CI documentation?

[https://docs.fastlane.tools/best-practices/continuous-integration/](https://docs.fastlane.tools/best-practices/continuous-integration/)

Has the following verbiage,

> If you want to upload builds to TestFlight/iTunes Connect from your CI machine, you need to generate an application specific password:
>1. Visit appleid.apple.com/account/manage
>2. Generate a new application specific password
>3. Provide the application specific password using the environment variable `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`

Which I interpreted as, "the only way to use TestFlight in a CI environment is to use 2FA and an application specific password"

Also feel free to close this issue unless you wanted to look more into the iTunes Connect session issue.

Thanks again!

**Comment by KrauseFx** [comment]
Glad to hear you got things running. That's a great idea, I submitted a PR adding this to the docs page https://github.com/fastlane/docs/pull/504, let me know what you think 👍
