### ISSUE TITLE
Adapt to "aggregate target" in Xcode

### ISSUE THREAD

**Issue by tossense** [fastlane/fastlane#1125]
Aggregate target doesn't have 'product_type' method, check this method's existence before call it.

I've created a PR https://github.com/fastlane/fastlane/pull/1124, but it failed in CI Test. I don't understand the CI's error message, so this issue is submitted.

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/1124, thanks :+1: This will be in the next release
