### ISSUE TITLE
Return a string from getBuildNumber func? 

### ISSUE THREAD

**Issue by altyus** [fastlane/fastlane#11266]
https://github.com/fastlane/fastlane/blob/3aaababca9498872e3fd631a379a5b766a08f1ed/fastlane/swift/Fastlane.swift#L1396

Wouldn't you want this to return the build number?

**Comment by taquitos** [comment]
🤦‍♂️ thank you.

We use code generation that depends on a few things, and it looks like I missed adding a `return_type` to that action.

Fixing that right now

**Comment by KrauseFx** [comment]
Beautiful, this will be part of the next release, thanks @altyus 👍

**Comment by acegreen** [comment]
How about getVersionNumber()?

**Comment by taquitos** [comment]
@acegreen you want the world, don't you 😜
PR incoming

**Comment by acegreen** [comment]
@taquitos I changed it on my end, was going to do a PR. No rush, if you don't get to it, I'll do it

**Comment by taquitos** [comment]
@acegreen thanks, the fix just got merged. Let me know if you find anything else, I had a feeling a few of these might slip through.

**Comment by acegreen** [comment]
@taquitos I see a bunch of get....() methods that have no return in that file. I would return String for all of them

**Comment by taquitos** [comment]
That's a great point. One thing that prevented me from doing that is some of those only store a file somewhere, or they save an object in the lane context for later use. Maybe in those cases we could return a path, or update the action to return the value too.

**Comment by acegreen** [comment]
Ah true, just to keep it simple for now, maybe for the obvious ones return String. And in the future, more use-cases it will be clear what to do with the exceptions you mentioned

On a side note, I noticed fast lane swift doesn't have a deploy_to_fabric equivalent, I thought it would be something like uploadToFabric(...)
