### ISSUE TITLE
Fastlane Swift only runs the first action in a lane

### ISSUE THREAD

**Issue by colincameron** [fastlane/fastlane#11276]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I've installed Fastlane.Swift as per the docs, but when trying to run `fastlane beta`, only the first action is executed. At first, only the `cocoapods()` action is executed (output below). When I comment out `cocoapods()` in `beforeAll()`, only the `buildApp()` action is executed.

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane beta
[11:18:36]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:18:37]: FastlaneSwiftRunner project is up-to-date
[11:18:37]: $ xcodebuild -list -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[11:18:38]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[11:18:39]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/colin/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[11:18:43]: Waiting for 5 seconds for a connection from FastlaneRunner
[11:18:43]: $ ./fastlane/FastlaneRunner lane beta > /dev/null
[11:18:43]: Client connected
[11:18:43]: -----------------------
[11:18:43]: --- Step: cocoapods ---
[11:18:43]: -----------------------
[11:18:43]: Installing Ruby gem 'cocoapods'...
Fetching: concurrent-ruby-1.0.5.gem (100%)
Fetching: i18n-0.9.1.gem (100%)
Fetching: thread_safe-0.3.6.gem (100%)
Fetching: tzinfo-1.2.4.gem (100%)
Fetching: activesupport-4.2.10.gem (100%)
Fetching: nap-1.1.0.gem (100%)
Fetching: fuzzy_match-2.0.4.gem (100%)
Fetching: cocoapods-core-1.3.1.gem (100%)
Fetching: cocoapods-deintegrate-1.0.1.gem (100%)
Fetching: cocoapods-downloader-1.1.3.gem (100%)
Fetching: cocoapods-plugins-1.0.0.gem (100%)
Fetching: cocoapods-search-1.0.0.gem (100%)
Fetching: cocoapods-stats-1.0.0.gem (100%)
Fetching: netrc-0.11.0.gem (100%)
Fetching: cocoapods-trunk-1.3.0.gem (100%)
Fetching: cocoapods-try-1.1.0.gem (100%)
Fetching: molinillo-0.5.7.gem (100%)
Fetching: escape-0.0.4.gem (100%)
Fetching: fourflusher-2.0.1.gem (100%)
Fetching: ruby-macho-1.1.0.gem (100%)
Fetching: cocoapods-1.3.1.gem (100%)
[11:18:54]: Successfully installed 'cocoapods'
[11:18:54]: $ pod install
[11:18:59]: ▸ Analyzing dependencies
[11:18:59]: ▸ Downloading dependencies
[11:18:59]: ▸ Using 1PasswordExtension (1.8)
[11:18:59]: ▸ Using ACSimpleKeychain (0.3)
[11:18:59]: ▸ Using AEXML (4.0.2)
[11:18:59]: ▸ Using Alamofire (4.4.0)
[11:18:59]: ▸ Using CLImageEditor (0.1.4)
[11:18:59]: ▸ Using Crashlytics (3.7.0)
[11:18:59]: ▸ Installing DraggableCollectionView 0.1 (was 0.1)
[11:18:59]: ▸ Using Fabric (1.6.7)
[11:18:59]: ▸ Using KYDrawerController (2.0.1)
[11:18:59]: ▸ Using MBProgressHUD (0.9.2)
[11:18:59]: ▸ Using UIActionSheet+Blocks (0.9)
[11:18:59]: ▸ Using UIAlertView+Blocks (0.9)
[11:18:59]: ▸ Using iRate (1.11.4)
[11:18:59]: ▸ Generating Pods project
[11:18:59]: ▸ Integrating client project
[11:19:03]: ▸ Sending stats
[11:19:03]: ▸ Pod installation complete! There are 13 dependencies from the Podfile and 13 total pods installed.

+------+-----------+-------------+
|        fastlane summary        |
+------+-----------+-------------+
| Step | Action    | Time (in s) |
+------+-----------+-------------+
| 1    | cocoapods | 19          |
+------+-----------+-------------+

[11:19:04]: fastlane.tools finished successfully 🎉

```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// Customize this file, documentation can be found here:
// https://docs.fastlane.tools/
// All available actions: https://docs.fastlane.tools/actions
// can also be listed using the `fastlane actions` command

// Change the syntax highlighting to Swift
// All lines starting with // are ignored when running `fastlane`

// If you want to automatically update fastlane if a new version is available:
// updateFastlane()

import Foundation

class Fastfile: LaneFile {
    // This is the minimum version number required.
    // Update this, if you use features of a newer version
    var fastlaneVersion: String { return "2.70.0" }

    func beforeAll() {
        // environmentVariables["SLACK_URL"] = "https://hooks.slack.com/services/..."
        // cocoapods()
        // carthage()
    }

    func testLane() {
        desc("Runs all the tests")
        runTests()
    }

    func betaLane() {
        desc("Submit a new Beta Build to Apple TestFlight. This will also make sure the profile is up to date")

        // syncCodeSigning(gitUrl: "gitUrl", appIdentifier: [appIdentifier], username: appleID)
        // buildApp(scheme: "PowerMusic") // more options available
        uploadToTestflight(username: appleID)
        // You can also use other beta testing services here (run `fastlane actions`)
    }

    func releaseLane() {
        desc("Deploy a new version to the App Store")

        // syncCodeSigning(gitUrl: "gitUrl", type: "appstore", appIdentifier: [appIdentifier], username: appleID)
        captureScreenshots()
        buildApp(scheme: "PowerMusic") // more options available
        uploadToAppStore(username: appleID, app: appIdentifier, force: true)
        // frameScreenshots()
    }

    // You can define as many lanes as you want

    func afterAll(currentLane: String) {
        // This block is called, only if the executed lane was successful
        // slack(
        //     message: "Successfully deployed new App Update.",
        //     slackUrl: "slackURL"
        // )
    }

    func onError(currentLane: String, errorInfo: String) {
        // slack(
        //     message: errorInfo,
        //     slackUrl: "slackUrl",
        //     success: false
        // )
    }

    // All available actions: https://docs.fastlane.tools/actions

    // fastlane reports which actions are used. No personal data is recorded.
    // Learn more at https://github.com/fastlane/fastlane/#metrics
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2017-12-19**
</details>

**Comment by clehew** [comment]
I'm seeing this issue as well.  I don't think it's a code signing issue, the app build works fine if it's the first action.

**Comment by colincameron** [comment]
Yes I've managed to build and upload to TestFlight by running multiple times, commenting out one action each time.

**Comment by taquitos** [comment]
Taking a look at this

**Comment by taquitos** [comment]
does this reproduce for you if your lane is just:
```
        sh(command: "echo \"test 1\"")
        sh(command: "echo \"test 2\"")
        sh(command: "echo \"test 3\"")
```
?

Also, could you pass in `--verbose` when you run the command and post that output?

**Comment by colincameron** [comment]
Ok so that gives the same issue - only the first action is run.

See output:

```
fastlane beta --verbose
[20:40:10]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-12-20 20:40:11.54]: Checking if there are any plugins that should be loaded...
DEBUG [2017-12-20 20:40:11.78]: Checking for new user-provided tool configuration files
INFO [2017-12-20 20:40:11.95]: FastlaneSwiftRunner project is up-to-date
INFO [2017-12-20 20:40:11.97]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2017-12-20 20:40:12.21]: $ ./fastlane/FastlaneRunner lane beta logMode verbose > /dev/null
INFO [2017-12-20 20:40:12.24]: Client connected
DEBUG [2017-12-20 20:40:12.24]: [247367]: received command:{"commandID" : "","methodName" : "sh","args" : [{"name":"command","value":"echo \"test 1\""},{"name":"log","value":true}]}
INFO [2017-12-20 20:40:12.26]: ---------------------------
INFO [2017-12-20 20:40:12.26]: --- Step: echo "test 1" ---
INFO [2017-12-20 20:40:12.26]: ---------------------------
INFO [2017-12-20 20:40:12.26]: $ echo "test 1"
INFO [2017-12-20 20:40:12.26]: ▸ test 1
DEBUG [2017-12-20 20:40:12.26]: [268547]: sending {"payload":{"status":"failure","failure_information":["JSON::GeneratorError:", "/Users/colin/.fastlane/bin/bundle/lib/ruby/2.2.0/json/common.rb:223:in `generate'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/2.2.0/json/common.rb:223:in `generate'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:177:in `process_value_as_string'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:157:in `prepare_object'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:121:in `execute_command'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:110:in `process_command'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:56:in `block in receive_and_process_commands'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:40:in `loop'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:40:in `receive_and_process_commands'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:89:in `listen'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/server/socket_server.rb:29:in `start'", "/Users/colin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/swift_lane_manager.rb:194:in `block in start_socket_thread'"]}}
DEBUG [2017-12-20 20:40:12.27]: [270249]: received done signal, shutting down

+------+---------------+-------------+
|          fastlane summary          |
+------+---------------+-------------+
| Step | Action        | Time (in s) |
+------+---------------+-------------+
| 1    | echo "test 1" | 0           |
+------+---------------+-------------+

INFO [2017-12-20 20:40:13.29]: fastlane.tools finished successfully 🎉
```

**Comment by taquitos** [comment]
Thank you, that is super helpful @colincameron

**Comment by taquitos** [comment]
Ok, I was able to repro, looks like when you don't use `bundler` sometimes the `json` library that is used is the built-in json library, instead of the json library that is defined in the gemspec.
I have a PR on the way that will work with both.

**Comment by taquitos** [comment]
Ok, so I would suggest using `bundler` with a gemfile, we have some instructions for that
https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

**Comment by colincameron** [comment]
Thanks for the quick solution. I can confirm that using bundler with a gemfile fixes this.

**Comment by mlabraca** [comment]
Also worked for me. Thanks!

**Comment by taquitos** [comment]
Thank you for confirming!

**Comment by KrauseFx** [comment]
Yessss @taquitos 🚀 ❤️
