### ISSUE TITLE
How to export for both AppStore (Testflight) and Adhoc from same configuration

### ISSUE THREAD

**Issue by garyhooper** [fastlane/fastlane#11272]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

How do I sign my iOS app twice, once for AppStore (for TestFlight) and once for AdHoc (for Beta by Crashlytics), from the same Xcode configuration?  Do I need to build the app twice, or can I just sign it a second time?

Also, my Xcode configuration manually specifies the AppStore provisioning file for signing.  How do I override this in fastlane to use the AdHoc profile on the second signing?

**Comment by KrauseFx** [comment]
You could use the https://docs.fastlane.tools/actions/resign action, however it does come with some difficulties sometimes, so I'd recommend building the app twice.

**Comment by PetrosIchor** [comment]
To echo krausfx, I would say build it twice.  From my experience, it's the easiest, most stable way I've found.

**Comment by romk1n** [comment]
is there is away to use with Match ?

**Comment by xwartz** [comment]
Are there any updates?

**Comment by taquitos** [comment]
@xwartz what kind of update were you hoping for? It seems like building the app twice, once for adhoc and once for app store is the best path forward.

If you're wondering about using match, it should be as easy as just calling match 2 times, once for app store, and once for adhoc.

**Comment by PetrosIchor** [comment]
Agreed.  Make 2 lanes, one for each.  Then a third that drives both.  Call what you need when you need it.

**Comment by xwartz** [comment]
@taquitos  Thanks, it works for me.
