### ISSUE TITLE
fastlane frameit - wrong image output settings

### ISSUE THREAD

**Issue by Justinemmerich** [fastlane/fastlane#11273]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

frameit output the wrong format and has either transparency or alpha in it, iTunes Connect denied the upload.   

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.1                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.1 (17B1003)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode_8.3.3.app/Contents/Developer/              |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.69.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sync_code_signing(type: "appstore") # more information: https://codesigning.guide
    build_app(scheme: "DZIDE")
    upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Capture screenshots"
    lane :screenshots do
    capture_screenshots
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app # more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "it.dzide.user-app" # The bundle identifier of your app
apple_id "s.kleier@get-tyme.com" # Your Apple email address

team_id "Y2CWHTLMGQ" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.70.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2017-12-19**
</details>

**Comment by Justinemmerich** [comment]
This has nothing to do with code signing

**Comment by KrauseFx** [comment]
Could you share some more information, ideally some samples images, so that we can reproduce the issue?

**Comment by Justinemmerich** [comment]
I had some previously made screenshots created with the native xcode simulator and wanted them to be automatically framed by frameit. When I tried to upload them manually, iTunesConnect declared that the Screen Specifications are not right and has transparency in it.

For Example: 
5.8 Inch Display output was 1295 × 2590 but has to be 1125 x 2436 for portrait.
5.5 Inch Display output was 1446 × 2950 but has to be 1242 x 2208 for portrait.
(See http://help.apple.com/itunes-connect/developer/#/devd274dd925) 

this may have been caused because my initial shots had 1242 × 2208 before framing. 

I don't know if this will be fixed or maybe bypassed during the fastlane upload, but it would be definitely great if the user could use a single tool from the fastlane toolbox on its own.

**Comment by janpio** [comment]
So you give `frameit` a file of 1125 x 2436 and it outputs a file 1295 × 2590, and input 1242 x 2208 = output 1446 × 2950?

**Comment by Justinemmerich** [comment]
Yes, Right! So the output is not matching the Apple guideline

**Comment by janpio** [comment]
Yep, afaik the screenshots being framed should be zoomed out / made smaller so the file dimensions stay identical.

What command exactly are you running? Can you share one of these files?

**Comment by Justinemmerich** [comment]
![image](https://user-images.githubusercontent.com/10778265/34257718-4b00a016-e65b-11e7-9ef5-610377253020.png)

These are some example. I put the init dimensions as a title, check the framed dimensions they are changed.

**Comment by Justinemmerich** [comment]
![5 5 inch - 1242 x 2208_framed](https://user-images.githubusercontent.com/10778265/34257811-c0d3d4e8-e65b-11e7-8df3-3b36bd6db326.png)
![5 5 inch - 1242 x 2208](https://user-images.githubusercontent.com/10778265/34257812-c0f259a4-e65b-11e7-974c-79bb6eff3891.png)
![5 8 inch - 1125 x 2436_framed](https://user-images.githubusercontent.com/10778265/34257813-c10c8c2a-e65b-11e7-87e8-613116d7f516.png)
![5 8 inch - 1125 x 2436](https://user-images.githubusercontent.com/10778265/34257814-c1329046-e65b-11e7-98f3-9fb8002308e2.png)

**Comment by Justinemmerich** [comment]
These are some example. I put the init dimensions as a title, check the framed dimensions they are changed.

**Comment by Justinemmerich** [comment]
terminal command: fastlane frameit (in screenshot directory)

**Comment by janpio** [comment]
https://docs.fastlane.tools/actions/frameit/#usage

> When using frameit without titles on top, the screenshots will have the full resolution, which means they can't be uploaded to the App Store directly. They are supposed to be used for websites, print media and emails. Check out the section below to use the screenshots for the App Store.

So I think this might actually be expected behaviour.

To get App Store screenshots you probably could add a white background with 0 padding and not text? Not sure, but that is what I would try.

**Comment by Justinemmerich** [comment]
even with a Framefile.json this is not working. I got the same dimension output as described above.

Framefile.json:
`{
  "device_frame_version": "latest",
  "default": {
    "show_complete_frame": false,
    "stack_title": false,
    "background": "./background.jpg",
    "padding": 0
  },
  "data": []
}
`

**Comment by janpio** [comment]
Ok, but you agree that the docs indicate that without Framefile you are getting what is documented?

Now on to the framefile: Can you test with padding and some text?

**Comment by Justinemmerich** [comment]
I don't want to padding or text. This is still a Bug, because Images can not be used directly after for example`fastlane frameit silver`

**Comment by Justinemmerich** [comment]
<img width="802" alt="bildschirmfoto 2018-01-16 um 14 32 30" src="https://user-images.githubusercontent.com/10778265/34991589-7aaffaf4-faca-11e7-86ae-3528f6dd00c0.png">

**Comment by Justinemmerich** [comment]
<img width="635" alt="bildschirmfoto 2018-01-16 um 14 35 36" src="https://user-images.githubusercontent.com/10778265/34991626-9735839c-faca-11e7-8ea9-c725a48b5a88.png">

**Comment by janpio** [comment]
Why is this a bug when the docs tell you:

> When using frameit without titles on top, the screenshots will have the full resolution, which means they can't be uploaded to the App Store directly. They are supposed to be used for websites, print media and emails. Check out the section below to use the screenshots for the App Store.

docs.fastlane.tools/actions/frameit/#usage

You of course could say that you want it to work otherwise or an option to work it this way.

> I don't want to padding or text.

Yes, but I don't want to replicate all this although I don't have a problem and just want to help you. So please add some padding and text to confirm that it works the way it should if those are present. Then we have a baseline.
