### ISSUE TITLE
[Ubuntu] Build `xar` dependency into `.deb` file that can installed via `apt-get`

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11280]
#11242 adds an Ubuntu testing environment for fastlane.

One of the dependencies of fastlane, `xar`, is always available on macOS - but not on Ubuntu. Unfortunately there are also no ready made packages to install, so we have to build from source directly:

```
      - run:
          name: Install additional dependency xar
          command: |
            cd /tmp
            mkdir download
            cd download
            wget https://github.com/downloads/mackyle/xar/xar-1.6.1.tar.gz
            tar -xzf xar-1.6.1.tar.gz
            cd xar-1.6.1
            ./autogen.sh --noconfigure
            ./configure
            make
            sudo make install
```

This works, but of course is a bit unnecessary (and ugly).

@lacostej suggested in https://github.com/fastlane/fastlane/pull/11242/files#r157786751 to "provide a pre-built binary to avoid having to do that every time and maybe host it here: https://launchpad.net/ubuntu/+ppas" which makes total sense.

Unfortunately this is a bit more involved than I hoped, so I extracted this into this separate issue.

As replies to @lacostej's comment I already posted the following snippets in that comment thread:

> Fascinating, there are actually 4 sources for ready built xars there I didn't find googling before: https://launchpad.net/ubuntu/+ppas?name_filter=xar
> Unfortunately none of them are v1.6.1, so I will see if I can build this myself.

> https://launchpad.net/ubuntu/+ppas links to https://help.launchpad.net/Packaging/PPA links to https://help.launchpad.net/Packaging/PPA/Uploading links to https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage links to http://packaging.ubuntu.com/html/ links to http://packaging.ubuntu.com/html/packaging-new-software.html - and is a bit complicated.

**Comment by jdee** [comment]
The simplest solution to @lacostej's concern could be just to cache xar after it's installed. Then you won't be running `wget` each time. I've done that sort of thing in other Circle projects with good results.

I like the idea of publishing the package, but if that proves too involved, I think you could probably also just make a new repo like `fastlane/ci-tools` and then run your `wget` command in that repo and push. In CI you can clone/sync/cache that repo. That might not be a huge improvement over caching the `wget` in the first place, but then if you have other needs like this, you could add dependencies/tools for each platform in that repo, which would make that approach a bit more scalable.

**Comment by jdee** [comment]
@janpio https://circleci.com/docs/2.0/caching/

**Comment by janpio** [comment]
Thanks @jdee, seems I am almost accidentally already doing that at https://github.com/fastlane/fastlane/blob/3830c51f153875ec0b7350af359709e32616cfab/.circleci/config.yml#L56-L82 - which tells me that the `xar` installation should not be inside these two cache commands, correct?

How exactly does one "cache xar after it's installed"? Caching the downloaded file I would understand, but what is needed to cache the installed tool?
