### ISSUE TITLE
Passing an environment variable to a shell script from Fastlane

### ISSUE THREAD

**Issue by flexaddicted** [fastlane/fastlane#1128]
I need to execute a shell script from fastlane. I am using the following command.

    sh "./myscript.sh ENV['ENCRYPTION_P12']"

The goal is to pass to `myscript` file a environment variable defined in the `.env` file.
Could you suggest me the right way to do it?

**Comment by KrauseFx** [comment]
Closed with https://stackoverflow.com/questions/34855316/passing-an-environment-variable-to-a-shell-script-from-fastlane
