### ISSUE TITLE
Support for iOS Today Widget Extension?

### ISSUE THREAD

**Issue by tangzzz-fan** [fastlane/fastlane#11295]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]
My app has a extension for Widget, before add the today target on my project, I used fastlane gym succeed, and today I still used it, it worked, but I cannot found today extension of my application. Fastlane worked without no error output.

After failed,  I tried to specified my appfile with different appid in different target(cause today extension needs different target) 
I will paste my appfile and fastfile configuration blow
#### here is appfile configuration

for_platform :ios do
  team_id 'WT44JA8H45' # for all iOS related things
  for_lane :release_to_pgyer do
    app_identifier 'com.company.property'
  end
  for_lane :release_to_pgyer_widget do
    app_identifier 'com.company.property.widgetToday'
  end
end

#### here is my fastfile configuration
    gym(
      scheme: "findproperty",
      output_name: ipaName,
      output_directory: "./fastlane/build/Pgy",
      configuration: "Release",
      export_method: "ad-hoc",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.centaline.findproperty" => "ShCentalineFindHouse_AdHoc",
          "com.centaline.findproperty.widgetToday" => "ShCentalineFindHouseToday_AdHoc"
        }
      }
    )

Maybe a guideline of how to archive with today extension of iOS is suitable, cause I cannot find enough doc to solve this myself. thanks a lot

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.1"

default_platform :ios

def updateProjectBuildNumber
 
  currentTime = Time.new.strftime("%Y%m%d")
  build = get_build_number()
  if build.include?"#{currentTime}."
  # => 为当天版本 计算迭代版本号
  lastStr = build[build.length-2..build.length-1]

  lastNum = lastStr.to_i
  lastNum = lastNum + 1
  lastStr = lastNum.to_s
    if lastNum < 10
      lastStr = lastStr.insert(0,"0")
  end
  build = "#{currentTime}.#{lastStr}"
  else
  # => 非当天版本 build 号重置
    build = "#{currentTime}.01"
end
puts("*************| 更新build #{build} |*************")
# => 更改项目 build 号
increment_build_number(
  build_number: "#{build}"
)
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "findproperty") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot

    # 1 拉取 git 和 pod(检查私有库)

    # 2 更新版本号

    # 3 git 提交, 拉取, 推送

    git_pull
    updateProjectBuildNumber
    git_commit(path: '.', message: "Update build number to itunesconnect")
    git_pull
    git_push(branch: "Jenkins")

    currentTime = Time.new.strftime("%Y-%m-%d-%H-%M")
    ipaName = "FindProperty-#{currentTime}.ipa"
    puts "打包并上传到 app-store"
    gym(
      scheme: "findproperty",
      output_name: ipaName,
      output_directory: "./fastlane/build/App-Store",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.centaline.findproperty" => "ShCentalineFindHouse_Dis"
        }
      }
    )    
    deliver(force: true)
    # frameit
  end

  desc "Deploy a app to testflight"
  lane :release_to_testflight do

    # 1 拉取 git 和 pod(检查私有库)

    # 2 更新版本号

    # 3 git 提交, 拉取, 推送

    git_pull
    updateProjectBuildNumber
    git_commit(path: '.', message: "Update build number to itunesconnect")
    git_pull
    git_push(branch: "Jenkins")

    currentTime = Time.new.strftime("%Y-%m-%d-%H-%M")
    ipaName = "FindProperty-#{currentTime}.ipa"
    puts "打包并上传到test"

    gym(
      scheme: "findproperty",
      output_name: ipaName,
      output_directory: "./fastlane/build/Pgy",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.centaline.findproperty" => "ShCentalineFindHouse_Dis"
        }
      }
    )

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

    pilot

  end
  # You can define as many lanes as you want

  desc "Deploy a app to 蒲公英"
  lane :release_to_pgyer do
    # 1 拉取 git 和 pod(检查私有库)

    # 2 更新版本号

    # 3 git 提交, 拉取, 推送

    git_pull
    updateProjectBuildNumber
    git_commit(path: '.', message: "Update build number to pgyer")
    git_pull
    git_push(branch: "Jenkins")

    currentTime = Time.new.strftime("%Y-%m-%d-%H-%M")
    ipaName = "FindProperty-#{currentTime}.ipa"
    puts "打包并上传到蒲公英"
    # 版本号自增
    gym(
      scheme: "findproperty",
      output_name: ipaName,
      output_directory: "./fastlane/build/Pgy",
      configuration: "Release",
      export_method: "ad-hoc",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.centaline.findproperty" => "ShCentalineFindHouse_AdHoc",
          "com.centaline.findproperty.widgetToday" => "ShCentalineFindHouseToday_AdHoc"
        }
      }
    )

    pgyer(api_key: "a3caff155177c60f2a71a6259bd3bd1e", user_key: "4be20c41a529d11fe539bd56c9e425c0")

  end

  

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.centaline.findproperty" # The bundle identifier of your app

apple_id "bobin@centaline.com.cn" # Your Apple email address

team_id "WT44JA8HJ5" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile
for_platform :ios do
  team_id 'WT44JA8HJ5' # for all iOS related things
  for_lane :release_to_pgyer do
    app_identifier 'com.centaline.findproperty'
  end
  for_lane :release_to_pgyer_widget do
    app_identifier 'com.centaline.findproperty.widgetToday'
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| chunky_png                | 1.3.8        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-pgyer     | 0.2.1        |
| rest-client               | 2.0.2        |
| rqrcode                   | 0.10.1       |
| ruby_android              | 0.7.7        |
| thor                      | 0.20.0       |
| fir-cli                   | 1.6.3        |
</details>

*generated on:* **2017-12-20**
</details>

**Comment by KrauseFx** [comment]
Sorry I'm a little unsure what you're asking. Can you share more information about your setup, the complete output when running _fastlane_ and the error message?

**Comment by tangzzz-fan** [comment]
I want to know how to archive app what has a today widget extension. I think maybe I don't know how to config my fastfile. 
here is part output info when running fastlane 
[19:38:32]: [35m[33m▸[0m [39;1mTouching[0m findproperty.app[0m
[19:38:33]: [35m[33m▸[0m [39;1mRunning script[0m '[CP] Copy Pods Resources'[0m
[19:38:34]: [35m[33m▸[0m [39;1mSigning[0m /Users/Paranora/Library/Developer/Xcode/DerivedData/findproperty-fqjymaiteatylvbylezregwjfqwm/Build/Intermediates.noindex/ArchiveIntermediates/findproperty/InstallationBuildProductsLocation/Applications/findproperty.app[0m
[19:38:42]: [35m[33m▸[0m [39;1mTouching[0m findproperty.app.dSYM[0m
[19:38:47]: [35m[33m▸[0m [39;1mArchive[0m Succeeded[0m
[19:38:49]: [33mGenerated plist file with the following values:[0m
[19:38:49]: ▸ [35m-----------------------------------------[0m
[19:38:49]: ▸ [35m{[0m
[19:38:49]: ▸ [35m  "compileBitcode": false,[0m
[19:38:49]: ▸ [35m  "provisioningProfiles": {[0m
[19:38:49]: ▸ [35m    "com.centaline.findproperty": "ShCentalineFindHouse_AdHoc"[0m
[19:38:49]: ▸ [35m  },[0m
[19:38:49]: ▸ [35m  "method": "ad-hoc",[0m
[19:38:49]: ▸ [35m  "signingStyle": "manual"[0m
[19:38:49]: ▸ [35m}[0m
[19:38:49]: ▸ [35m-----------------------------------------[0m
[19:38:49]: [36m$ /usr/bin/xcrun /Users/Paranora/.rvm/gems/ruby-2.3.0/gems/fastlane-2.70.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/_g/qk6z01652kgg8d0pmn3fsrv00000gp/T/gym_config20171220-551-1k89jm5.plist' -archivePath /Users/Paranora/Library/Developer/Xcode/Archives/2017-12-20/FindProperty-2017-12-20-19-31\ 2017-12-20\ 19.31.40.xcarchive -exportPath '/var/folders/_g/qk6z01652kgg8d0pmn3fsrv00000gp/T/gym_output20171220-551-1pusthp' [0m
[19:39:21]: Compressing 18 dSYM(s)
--------
I put my identifier for today extension in fastfile like this: 
gym(
      scheme: "findproperty",
      output_name: ipaName,
      output_directory: "./fastlane/build/Pgy",
      configuration: "Release",
      export_method: "ad-hoc",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.centaline.findproperty" => "ShCentalineFindHouse_AdHoc",
          "com.centaline.findproperty.widgetToday" => "ShCentalineFindHouseToday_AdHoc"
        }
      }
    )
----------
Here is done infomation 
[19:39:26]: [32mSuccessfully exported and compressed dSYM file[0m
[19:39:26]: [32mSuccessfully exported and signed the ipa file:[0m
[19:39:26]: /Users/Paranora/Jenkins/workspace/Release_PGY_TestDev/Project/fastlane/build/Pgy/FindProperty-2017-12-20-19-31.ipa

Maybe the key is how to archive a app with a today widget. thanks a lot

**Comment by KrauseFx** [comment]
```
[19:39:26]: �[32mSuccessfully exported and compressed dSYM file�[0m
[19:39:26]: �[32mSuccessfully exported and signed the ipa file:�[0m
[19:39:26]: /Users/Paranora/Jenkins/workspace/Release_PGY_TestDev/Project/fastlane/build/Pgy/FindProperty-2017-12-20-19-31.ipa
```

Looks successful to me, could you tell us more about what the error is?

**Comment by tangzzz-fan** [comment]
my app has a today widget extension. but cannot found it in my app, which is archived by fastlane.
so, i want to know whether need other configuration for app including today extension. thanks.

**Comment by getaaron** [comment]
@tangzzz-fan Did you figure it out? I think you need to include it in your target specification.

**Comment by tangzzz-fan** [comment]
Today. I tried again, I found it appeared in my app, I didn't change any configuration.(Specified different provision file for each identifier) Further, I wanna know how to include it in my target specification.can you share with me?
