### ISSUE TITLE
Failed to register devices in devices.txt

### ISSUE THREAD

**Issue by Hapeki** [fastlane/fastlane#11294]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `register_devices` after adding new devices in `devices.txt` results in the following error message: **Please provide a file according to the Apple Sample UDID file (https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip).** 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.1  | ✅ Up-To-Date  |

*generated on:* **2017-12-20**
</details>

**Comment by Hapeki** [comment]
The fix is to edit the devices.txt from another texteditor **(not from within Xcode)**. I got it working by using **Sublime Text** and setting a single tab between the UDID and device name. I tried TextEdit but this also resulted in a non working devices.txt file.

More info: It turns out that Xcode editor translates the tab between the UDID and device name into 4 spaces - resulting in a broken devices.txt file.

**Comment by janpio** [comment]
Awesome you figured it out.

Not much _fastlane_ can do about that, right?
