### ISSUE TITLE
Set Development Team for specific Target

### ISSUE THREAD

**Issue by mbaldassarri** [fastlane/fastlane#11292]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I created a Notification Service Extension target for managing notifications with images. 
In my XCode project I have different app targets each one with different Development Team set. 
When building and launching a specific app target the compiler asks me to change the Development Team and the Bundle Identifier for the Notification Service Extension target, that's because embedded binaries have to be signed with the same certificate as the parent app. I want to automate this so I used fastlane to set the proper bundle id, but I can't figure out how to change the Development Team for that specific embedded target.

**Comment by KrauseFx** [comment]
Does the [update_app_identifier](https://docs.fastlane.tools/actions/update_app_identifier/) action do what you need?

**Comment by mbaldassarri** [comment]
Hello @KrauseFx ! Thanks for your fast reply.
Actually I was able to change the app identifier, what I can't do is to change the Development Team for the embedded target (Notification Service Extension). 
I can do this by going to the embedded target general settings in XCode and manually switching the Team to the parent target team.

![image](https://user-images.githubusercontent.com/7142465/34202031-d5879d56-e576-11e7-9c17-5e788b5919b5.png)

**Comment by KrauseFx** [comment]
[update_project_team](https://docs.fastlane.tools/actions/update_project_team/) maybe? You can find a full list of actions over here https://docs.fastlane.tools/actions/, also check out the available plugins on the docs page

**Comment by mbaldassarri** [comment]
This is a good plugin but it is not exactly what I need, because it changes the entire project team. I need to change a specific target development team only. 
Only this way the Service Extension can work, because it has to have the same dev team set up as the parent one.
I checked out the whole actions page and googled it but didn't find anything useful for my purpose.

**Comment by KrauseFx** [comment]
You can check out the implementation of it [over here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/update_project_team.rb). Since _fastlane_ can't do this specific thing right now, you can submit a PR adding the functionality to this action, or you can build & publish a fastlane plugin 👍
