### ISSUE TITLE
Could not find a matching code signing identity for Spaceship::Portal::ProvisioningProfile::AppStore

### ISSUE THREAD

**Issue by joshbedo** [fastlane/fastlane#1129]
Keep getting this error and i'm unsure how to solve it. I have a cert installed on my login/system keychain. I set Provisioning Profile to * and the app id etc. seem to be connecting. I was wondering if anyone can tell me what im missing?

![](http://i.imgur.com/Skpkxic.jpg)

**Comment by joshbedo** [comment]
So i got further and now it can't find the app id. I definitely have a `com.roomthat.app` id
![](http://i.imgur.com/dMYNC6O.jpg)

**Comment by KrauseFx** [comment]
Since it failed on the `pilot` step, can you check if your app is created on iTunes Connect?

**Comment by joshbedo** [comment]
Hehe So that was exactly my problem, I didn't have the app registered on iTunes Connect :)

**Comment by KrauseFx** [comment]
:+1:
