### ISSUE TITLE
[Ubuntu/CircleCI] Create Docker container with our dependencies

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11302]
Quoting @DanToml in [this PR comment](https://github.com/fastlane/fastlane/pull/11242/files#r158092394):

> We should build a docker container that includes these (based on the circleci/ruby:2.3 container)

"these" refers to:
* `sudo apt-get install shellcheck`
* #11280, `xar`
* probably #11268, `iTMSTransporter`

**Comment by milch** [comment]
I have some experience with Docker, I can do that 👍🏼

**Comment by janpio** [comment]
Wow, that would be awesome. 

#11242 is merged, so you should be able to edit the `circle.yml` and see results of using the Docker container on Circle CI directly.
