### ISSUE TITLE
match don`t work in a new machine 

### ISSUE THREAD

**Issue by zhenMZ** [fastlane/fastlane#11309]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I try to use match in a new machine, but it dont work.
I ensure i have access to repo, i cant use ssh clone repo.it even do not let me enter password of match repo.
![5d72dda6-6287-4f5b-bfbb-74105b2bd04e](https://user-images.githubusercontent.com/15841784/34238381-3c99e132-e63c-11e7-9daa-a940646c5d8a.png)

it always still in here!help~

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Fastfile 
# Copyright@2017 Abyss

fastlane_version "2.69.2"
default_platform :ios

platform :ios do

	before_all do
	end

	import_from_git(
		url: 'https://github.com/RogerAbyss/fastlane.git', 
		branch: '0.0.3',
		path: 'fastlane/IOSAppFastfile'
	  )
	  
	after_all do
	end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# APP 配置
apple_id "3228233658@qq.com"

for_lane :test do
	app_identifier "com.zgxl.test001"
end

for_lane :beta do
	app_identifier "com.zgxl.test002"
end

for_lane :release do
	app_identifier "com.zgxl.app"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.70.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| slack-notifier        | 1.5.1        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.2.8        |
| terminal-notifier     | 1.8.0        |
| unicode-display_width | 1.3.0        |
| terminal-table        | 1.8.0        |
| public_suffix         | 2.0.5        |
| addressable           | 2.5.2        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| tty-screen            | 0.6.3        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.5        |
| faraday               | 0.13.1       |
| unf_ext               | 0.0.7.4      |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_json            | 1.12.2       |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| dotenv                | 2.2.1        |
| bundler               | 1.15.4       |
| faraday_middleware    | 0.12.2       |
| uber                  | 0.1.0        |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| retriable             | 3.1.1        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| io-console            | 0.4.6        |
| excon                 | 0.60.0       |
| openssl               | 2.0.5        |
| CFPropertyList        | 2.3.6        |
| mini_portile2         | 2.3.0        |
| nokogiri              | 1.8.1        |
| plist                 | 3.4.0        |
| fastimage             | 2.1.1        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.4        |
</details>

*generated on:* **2017-12-21**
</details>

**Comment by janpio** [comment]
Your screenshot doesn't include any error message or problem. What is going wrong?
