### ISSUE TITLE
Mute fastlane output keeping lane's output.

### ISSUE THREAD

**Issue by ignazioc** [fastlane/fastlane#11311]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
As user of `fastlane` I would like to be able to suppress the fastlane's output but still be able to see the output of the lanes.
In particularly is already possible to use `FASTLANE_SKIP_UPDATE_CHECK`  and `FASTLANE_HIDE_TIMESTAMP` to limit the verbosity of the output, but there is no way to disable:

* The `fastlane summary` table
* The `fastlane version verification`
* The `Step: header`

My suggestion is to add new ENV variables to also disable those parts of the output.
I would like to create the PR but, as suggested [here](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) I'm creating this issue in advance.

##### Complete output when running fastlane, including the stack trace and command used
Not relevant

### Environment

Not relevant

**Comment by KrauseFx** [comment]
Interesting - thanks for filing an issue first. What's the reason you feel strongly to want to hide those?

From my side, I'm ok with adding those env variables, but I'm not 100% sure yet I understand why it's necessary.

**Comment by ignazioc** [comment]
Thanks @KrauseFx .
Mostly for human readability of the output of some lanes. 
I have few lanes with short output that's somehow lost between the standard output of `fastlane`

**Comment by KrauseFx** [comment]
Sounds good, yah feel free to submit a PR with the new option 👍 Thanks for your contribution
