### ISSUE TITLE
Upload to Fabric doesn't work since 2.70.2. How to downgrade to 2.70.1?

### ISSUE THREAD

**Issue by EugeneGoloboyar** [fastlane/fastlane#11310]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Upload to Crashlytics doesn't work anymore. 
Yesterday I used fastlane v 2.70.1 and it definitely worked - as I tested both deployment to Fabric and to Testflight - after migration to Xcode 9.2 to check everythihg. 
And everything was ok. 
 
Please give me some instructions for downgrade to the previous version 2.70.1 which definitely works.
Thanks.

But today fastlane updated to 2.70.2 and I cannot upload anymore. 
with --verbose I got the following output:

[
2017-12-21 08:13:35.242 submit Crashlytics: Added Release Notes Successfully 200
2017-12-21 08:13:36.631 submit Crashlytics: Added Testers/Groups Successfully 200
2017-12-21 08:15:51.904 submit Crashlytics: Unable to submit build. Response code: 0
2017-12-21 08:15:51.968 submit Crashlytics: Failed to upload binary

	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/helper/sh_helper.rb:73:in `call'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/helper/sh_helper.rb:73:in `sh_control_output'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:150:in `block (2 levels) in parsing_binding'
	from Fastfile:136:in `each'
	from Fastfile:136:in `block in parsing_binding'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/evgenij/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.2/bin/fastlane:20:in `<top (required)>'
	from /Users/evgenij/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/evgenij/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
]

### Environment
[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.13.2                                      |
| Ruby                        | 2.2.4                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.8.1                            |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane          |
| Host                        | Mac OS X 10.13.2 (17C88)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                   |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                   |
| Is contained                | true                                         |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode9.app/Contents/Developer/ |
| Xcode Version               | 9.2                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:


# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.22.0"

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer


```

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.6.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-12-21**
</details>]

P.S.
It it could help I got this while updating
[07:38:19]: Looking for updates for fastlane...
[07:38:31]: Updating fastlane from 2.70.1 to 2.70.2... 🚀
(eval):101: warning: character class has ']' without escape
(eval):106: warning: else without rescue is useless
(eval):110: warning: else without rescue is useless
(eval):116: warning: else without rescue is useless
(eval):119: warning: else without rescue is useless
(eval):103: warning: else without rescue is useless
(eval):108: warning: else without rescue is useless
(eval):115: warning: else without rescue is useless
(eval):119: warning: else without rescue is useless

**Comment by EugeneGoloboyar** [comment]
Think it can be closed. Issue is supposed to be related to the bad connection.
Because now managed to upload.
Is it possible to improve error logging about this?)

**Comment by palusik86** [comment]
Same problem here, `crashlytics` action is completed with success, but build is not visible in Fabric, I'm on 2.6.4, Will try to update and check once again.

**Comment by fechy** [comment]
Same here since 2.75.1
Getting:
````
[15:19:27]: fastlane finished with errors

[!] 2018-01-12 15:18:41.031 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2018-01-12 15:18:53.498 submit Crashlytics: Added Release Notes Successfully 200
2018-01-12 15:18:54.115 submit Crashlytics: Added Testers/Groups Successfully 200
2018-01-12 15:19:26.935 submit Crashlytics: Unable to submit build. Response code: 0
2018-01-12 15:19:27.056 submit Crashlytics: Failed to upload binary
````

**Comment by krin-san** [comment]
Just had the same issue on 2.64.1. Issue gone after updating to 2.80.0. Could be coincidence _(build host connected via Wi-Fi)_ but could also be a reason.

**Comment by joshdholtz** [comment]
Going to close this for now since this seems like it was a wifi connection issue. The fabric uploading is mostly a pass-thru to the crashlytics tools so if this keeps happening this might be an issue deeper than fasltane 🙃 

Happy fastlaning 🚀

**Comment by palusik86** [comment]
Ye, apparently it still don't work for me, but manually upload with Fabric does work/.
