### ISSUE TITLE
SystemStackError (stack level too deep):

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#11323]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
 in rails environement.  gem 'rails', '5.1.4', when I have tried to create to complate an app submission. I have got SystemStackError (stack level too deep):

it's this to_json  here
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L985
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/base.rb#L66

who crashed rails.
my crash logs

https://gist.github.com/bolom/95c9ce228fd14a8cf2f2524261e718ec

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13.2                              |
| Ruby                        | 2.4.1                                |
| Bundler?                    | true                                 |
| Git                         | git version 2.14.3 (Apple Git-98)    |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane  |
| Host                        | Mac OS X 10.13.2 (17C88)             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib         |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| rake                      | 12.2.1       |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 5.1.4        |
| builder                   | 3.2.3        |
| erubi                     | 1.7.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.1        |
| rails-dom-testing         | 2.0.3        |
| crass                     | 1.0.3        |
| loofah                    | 2.1.1        |
| rails-html-sanitizer      | 1.0.3        |
| actionview                | 5.1.4        |
| rack                      | 2.0.3        |
| rack-test                 | 0.7.0        |
| actionpack                | 5.1.4        |
| nio4r                     | 2.1.0        |
| websocket-extensions      | 0.1.3        |
| websocket-driver          | 0.6.5        |
| actioncable               | 5.1.4        |
| globalid                  | 0.4.1        |
| activejob                 | 5.1.4        |
| mini_mime                 | 1.0.0        |
| mail                      | 2.7.0        |
| actionmailer              | 5.1.4        |
| activemodel               | 5.1.4        |
| arel                      | 8.0.0        |
| activerecord              | 5.1.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| airbrake-ruby             | 2.6.0        |
| airbrake                  | 7.1.0        |
| highline                  | 1.7.10       |
| commander                 | 4.4.3        |
| analytics-ruby            | 2.2.2        |
| encryptor                 | 3.0.0        |
| attr_encrypted            | 3.0.3        |
| execjs                    | 2.7.0        |
| autoprefixer-rails        | 7.1.6        |
| aws-sigv4                 | 1.0.2        |
| jmespath                  | 1.3.1        |
| aws-sdk-core              | 2.10.82      |
| aws-sdk-resources         | 2.10.82      |
| aws-sdk                   | 2.10.82      |
| babosa                    | 1.0.2        |
| bcrypt                    | 3.1.11       |
| benchmark-ips             | 2.7.2        |
| bindex                    | 0.5.0        |
| byebug                    | 9.1.0        |
| xpath                     | 2.1.0        |
| capybara                  | 2.16.0       |
| capybara-email            | 2.5.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| carrierwave               | 1.2.1        |
| excon                     | 0.60.0       |
| formatador                | 0.2.5        |
| fog-core                  | 1.45.0       |
| multi_json                | 1.12.2       |
| fog-json                  | 1.0.2        |
| ipaddress                 | 0.8.3        |
| xml-simple                | 1.1.5        |
| fog-aliyun                | 0.2.0        |
| fog-xml                   | 0.1.3        |
| fog-atmos                 | 0.1.0        |
| fog-aws                   | 1.4.1        |
| inflecto                  | 0.0.2        |
| fog-brightbox             | 0.14.0       |
| fog-cloudatcost           | 0.1.2        |
| fog-digitalocean          | 0.3.0        |
| fog-dnsimple              | 1.0.0        |
| fog-dynect                | 0.0.3        |
| fog-ecloud                | 0.3.0        |
| fog-google                | 0.1.0        |
| fog-internet-archive      | 0.0.1        |
| fog-joyent                | 0.0.1        |
| fog-local                 | 0.4.0        |
| fog-openstack             | 0.1.22       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| netrc                     | 0.11.0       |
| rest-client               | 2.0.2        |
| rbovirt                   | 0.1.4        |
| fog-ovirt                 | 0.1.1        |
| fog-powerdns              | 0.1.1        |
| fog-profitbricks          | 4.0.0        |
| fog-rackspace             | 0.1.5        |
| fog-radosgw               | 0.0.5        |
| fog-riakcs                | 0.1.0        |
| fog-sakuracloud           | 1.7.5        |
| fog-serverlove            | 0.1.2        |
| fog-softlayer             | 1.1.4        |
| fog-storm_on_demand       | 0.1.1        |
| fog-terremark             | 0.1.0        |
| fission                   | 0.5.0        |
| fog-vmfusion              | 0.1.0        |
| fog-voxel                 | 0.1.0        |
| json                      | 2.1.0        |
| trollop                   | 2.1.2        |
| rbvmomi                   | 1.11.3       |
| fog-vsphere               | 1.13.1       |
| fog-xenserver             | 0.3.0        |
| fog                       | 1.42.0       |
| uuidtools                 | 2.1.5        |
| carrierwave_direct        | 0.0.15       |
| ffi                       | 1.9.18       |
| childprocess              | 0.8.0        |
| choice                    | 0.2.0        |
| claide                    | 1.0.2        |
| method_source             | 0.9.0        |
| thor                      | 0.20.0       |
| railties                  | 5.1.4        |
| jquery-rails              | 4.3.1        |
| regexp_parser             | 0.4.7        |
| js_regex                  | 2.1.0        |
| sprockets                 | 3.7.1        |
| sprockets-rails           | 3.2.1        |
| rails                     | 5.1.4        |
| client_side_validations   | 10.0.2       |
| climate_control           | 0.2.0        |
| cliver                    | 0.3.2        |
| clockwork                 | 2.0.2        |
| cocaine                   | 0.5.8        |
| coderay                   | 1.1.2        |
| coffee-script-source      | 1.12.2       |
| coffee-script             | 2.4.1        |
| coffee-rails              | 4.2.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| i18n_data                 | 0.8.0        |
| money                     | 6.10.0       |
| sixarm_ruby_unaccent      | 1.2.0        |
| unicode_utils             | 1.4.0        |
| countries                 | 2.1.2        |
| css_parser                | 1.6.0        |
| database_cleaner          | 1.6.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| get_process_mem           | 0.2.1        |
| heapy                     | 0.1.3        |
| memory_profiler           | 0.9.8        |
| derailed_benchmarks       | 1.3.2        |
| derailed                  | 0.1.0        |
| orm_adapter               | 0.5.0        |
| responders                | 2.4.0        |
| warden                    | 1.2.7        |
| devise                    | 4.3.0        |
| devise_invitable          | 1.7.2        |
| docile                    | 1.1.5        |
| dotenv                    | 2.2.1        |
| dotenv-rails              | 2.2.1        |
| et-orbi                   | 1.0.8        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| flamegraph                | 0.9.5        |
| font-awesome-rails        | 4.7.0.2      |
| hashie                    | 3.5.6        |
| hiredis                   | 0.6.1        |
| immigrant                 | 0.3.6        |
| jbuilder                  | 2.7.0        |
| rb-fsevent                | 0.10.2       |
| rb-inotify                | 0.9.10       |
| sass-listen               | 4.0.0        |
| sass                      | 3.5.3        |
| jquery-fileupload-rails   | 0.4.7        |
| turbolinks-source         | 5.0.3        |
| turbolinks                | 5.0.1        |
| jquery-turbolinks         | 2.1.0        |
| ruby_dep                  | 1.5.0        |
| listen                    | 3.1.5        |
| mimemagic                 | 0.3.2        |
| mono_logger               | 1.1.0        |
| mustermann                | 1.0.1        |
| oauth2                    | 1.4.0        |
| omniauth                  | 1.7.1        |
| omniauth-oauth2           | 1.3.1        |
| omniauth-github           | 1.1.2        |
| omniauth-google-oauth2    | 0.5.2        |
| omniauth-slack            | 2.3.0        |
| paperclip                 | 5.1.0        |
| paperclip-meta            | 3.0.0        |
| pg                        | 0.21.0       |
| poltergeist               | 1.16.0       |
| pry                       | 0.11.3       |
| puma                      | 3.10.0       |
| puma_worker_killer        | 0.1.0        |
| pundit                    | 1.1.0        |
| rack-cors                 | 1.0.2        |
| rack-protection           | 2.0.0        |
| rack-throttle             | 0.5.0        |
| rails-assets-tether       | 1.4.1        |
| ruby-graphviz             | 1.2.3        |
| rails-erd                 | 1.5.2        |
| redis                     | 3.3.5        |
| redis-namespace           | 1.6.0        |
| redis-throttle            | 0.0.1        |
| tilt                      | 2.0.8        |
| sinatra                   | 2.0.0        |
| vegas                     | 0.1.11       |
| resque                    | 1.27.4       |
| resque-pool               | 0.6.0        |
| rufus-scheduler           | 3.4.2        |
| resque-scheduler          | 4.3.0        |
| resque_mailer             | 2.4.3        |
| roadie                    | 3.2.2        |
| roadie-rails              | 1.2.1        |
| roo                       | 2.7.1        |
| sass-rails                | 5.0.6        |
| s3_direct_upload          | 0.1.7        |
| sauce_whisk               | 0.1.0        |
| selenium-webdriver        | 3.7.0        |
| simple_segment            | 0.2.1        |
| simplecov-html            | 0.10.2       |
| simplecov                 | 0.15.1       |
| smarter_csv               | 1.1.5        |
| spring                    | 2.0.2        |
| spring-watcher-listen     | 2.0.1        |
| stackprof                 | 0.2.10       |
| stripe                    | 3.8.0        |
| sucker_punch              | 2.0.4        |
| to_words                  | 1.1.1        |
| uglifier                  | 3.2.0        |
| web-console               | 3.5.1        |
| whacamole                 | 1.2.0        |
| wicked_pdf                | 1.1.0        |
| wkhtmltopdf-binary        | 0.12.3.1     |
| wkhtmltopdf-heroku        | 2.12.4.0     |
</details>

*generated on:* **2017-12-22**
</details>

**Comment by milch** [comment]
It seems like you have a second JSON gem installed (`fog-json`), is it possible that is causing the issue by interfering with the regular JSON gem? 

Another thing is that it seems you haven't set up your locale settings correctly. Check out the docs here: https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

Also the crash log you posted seems to be a system crash log, if that is the only thing you get it might be related to a bug in your ruby version (or a native library that you are using) rather than fastlane

**Comment by bolom** [comment]
> It seems like you have a second JSON gem installed (fog-json), is it possible that is causing the issue by interfering with the regular JSON gem?

I have remove it. I have got same error. :(

**Comment by bolom** [comment]
I have created an new project with the basic gem and fastlane.

I have got the same error. My only solution so far is to call an external ruby script in Rails with the same code :(

**Comment by bolom** [comment]
This issue is not fixed

**Comment by taquitos** [comment]
When you run fastlane, can you add `--verbose` to the end of the call, and then paste in your entire console output?

**Comment by bolom** [comment]
mmm. I can do that with SpaceShip? At the moment what I am doing it's something really dirty. I am calling in my rails controller this script. otherwise it's to working

```
require 'spaceship'
login = ARGV[0]
password = ARGV[1]
apple_id = ARGV[2]
team_id = ARGV[3]

export_compliance_encryption_updated = ARGV[4]
content_rights_contains_third_party_content = (ARGV[5] == "true")
content_rights_has_rights = (ARGV[6] == "true")
add_id_info_uses_idfa = (ARGV[7] == "true")

Spaceship::Tunes.login(login, password)
Spaceship::Tunes.client.team_id = team_id
app = Spaceship::Tunes::Application.find(apple_id)

  begin
  submission = app.create_submission
  submission.export_compliance_encryption_updated =  export_compliance_encryption_updated
  if submission.export_compliance_encryption_updated  == true
      submission.export_compliance_is_exempt = true
  end

  submission.content_rights_contains_third_party_content = content_rights_contains_third_party_content
  submission.content_rights_has_rights = content_rights_has_rights

  submission.add_id_info_uses_idfa = add_id_info_uses_idfa
  if submission.add_id_info_uses_idfa == true
    submission.add_id_info_serves_ads = true
    submission.add_id_info_tracks_action = true
    submission.add_id_info_tracks_install = true
    submission.add_id_info_limits_tracking = true
  end
  # Finalize app submission
    submission.complete!
    puts "true"
  rescue  => e
    puts e.message
  end
```
