### ISSUE TITLE
Can scan use the same ui tests used in snapshot and capture autolayout runtime errors?

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#11337]
This isn’t a bug, but an implementation question.

I use snapshot with a uitest, which has the screenshot function calls.

I’d like to reuse this ui test to capture any autolayout runtime issues.

Is this possible, if so can someone provide me with some guidance and sample configuration?

Thanks.

**Comment by KrauseFx** [comment]
It depends on if your tests cover those issues, fastlane itself just runs tests using Xcode
