### ISSUE TITLE
It looks like travis is messed up

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#1133]
I submitted 2 PR's that are failing and couldn't figure out why.  So i just did the following:

    git clone https://github.com/fastlane/fastlane.git ftl
    cd ftl
    bundle install
    bundle exec fastlane test

And its not passing - so that says to me the master branch is broken.  

> Exit status of command 'rubocop -D' was 1 instead of 0.

**Comment by KrauseFx** [comment]
Yeah, `rubocop` had an update which changes all kinds of code style rules and therefore fails...

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
