### ISSUE TITLE
Speed up Circle CI builds

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11335]
This is an issue to collect ideas how to speed up the builds on Circle CI. Right now it takes 10/5 minutes on macOS/Ubuntu to run a build, which is not bad but could still be much better.

**Comment by janpio** [comment]
@milch started work on this with https://github.com/fastlane/fastlane/pull/11334 where he enabled the rubocop cache which saved ~40 seconds.

**Comment by milch** [comment]
I had some more ideas: 

- It seems around ~1 min is taken up by checking the docs repo. That step is not using the gem cache, so it is (needlessly) re-done and gems are re-installed. If the same cache would be used there, or even a separate cache could be used, we'd be able to save that time. 
- On macOS a lot of the time is taken up by things like homebrew updating. Maybe that can be cached or avoided somehow as well.

**Comment by milch** [comment]
Obviously the most time is taken up by RSpec, at least on Ubuntu. Looking at CPU usage of RSpec on my laptop it seems like it's not parallelized at all, so that should be another way to speed it up.

**Comment by milch** [comment]
Did some quick smoke testing using the [`parallel_tests`](https://github.com/grosser/parallel_tests) gem, on my laptop I get a pretty big speedup: 137 seconds for parallel_tests vs. 321 seconds without. Seems like a worthwhile thing to explore

**Comment by janpio** [comment]
If analysis of the timings in the one **big** test step tells us that several of the sub-steps take a considerable amount of time, it might be worth splitting this into multiple steps - that might be parallelized on Circle CI itself:
https://circleci.com/docs/2.0/parallelism-faster-jobs/
https://circleci.com/docs/2.0/sample-config/#sample-configuration-with-parallel-jobs
(We are already using this for running macOS and Ubuntu at the same time)

**Comment by janpio** [comment]
Running tests on newer machines is usually faster. Circle CI has an option to choose the Ubuntu version: https://circleci.com/gh/fastlane/fastlane/edit#build-environment But I am not sure if this affects our container at all with the way it is setup right now.

**Comment by milch** [comment]
Ah, good point. I think the rubocop step only has to be done once, same with checking the docs repo, so both could be done separately from the macOS/Ubuntu tests. 

Also yeah, I believe when running docker containers that setting doesn't do anything

**Comment by janpio** [comment]
We could run rubocop on Docker, then only start the tests on Docker and macOS.
One could think about running the docs testing stuff while the tests are still running (but we would have to split those out in their own step for that).

**Comment by milch** [comment]
I'd split rubocop, docs verification both into separate steps, and then have only the tests run on Docker and macOS. It's cleaner that way, plus `rubocop` is gonna slow down a bit once my missing require checker is merged in

**Comment by milch** [comment]
One more idea just came to me, for macOS: We're running `brew install` which automatically updates the Homebrew repo. This takes a looooong time so we should try to cache the `/usr/local/Homebrew` folder to save ~1min

**Comment by milch** [comment]
I just discovered [`test-queue`](https://github.com/tmm1/test-queue) which seems to work better than `parallel-test`. Similar speedups there as well
