### ISSUE TITLE
Suggestion for docs

### ISSUE THREAD

**Issue by Stas-Buzunko** [fastlane/fastlane#11342]
Maybe it's obvious for other people, but I've been fighting with proxyError for 4 hours.

https://docs.fastlane.tools/actions/deliver/#http-proxy

1) I'm a new mac user and it took me a lot of time to find out how to open xcode's contents
2) When I found net.properties I switched java.net.useSystemProxies to true, that didn't help
3) It took me some time to guess I needed to use 443 port

My suggestion is to add
a) a note how to find xcode's contents
b) specify port 443 in example (in case it's the same for everyone)
c) whether proxyHost is required

Feel free to close this in case you don't find it useful.

**Comment by KrauseFx** [comment]
Sounds like a great idea, would you mind submitting a pull request to add the information that's currently missing? https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/deliver.md 👍
