### ISSUE TITLE
Not working for cocoapods project.

### ISSUE THREAD

**Issue by bdavid68** [fastlane/fastlane#11345]
I am going to use Fastlane for my React Native project.
Everything was working perfectly. But after I update the project to cocoapods project, it's not working.
Here is my log.

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.3/lib/xcodeproj/plist.rb:17:in `read_from_path': [!] [!] The plist file at path `/Volumes/Work/ReactNative/RNApp/ios/RNApp.xcworkspace/project.pbxproj` doesn't exist. (Xcodeproj::Informative)

	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:200:in `initialize_from_file'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:102:in `open'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/automatic_code_signing.rb:10:in `run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:11:in `block (2 levels) in parsing_binding'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:287:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:287:in `execute_flow_block'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.70.3/bin/fastlane:20:in `<top (required)>'
	from /Users/admin/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/admin/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

I'd appreciate any help!

**Comment by KrauseFx** [comment]
You seem to have forgotten to share your `fastlane env` output, in particular the `Fastfile`. It seems like you're using the `automatic_code_signing` action, and passed no path, or an invalid path.
