### ISSUE TITLE
Call 'fastlane' fail when in bash scrip

### ISSUE THREAD

**Issue by allen8300** [fastlane/fastlane#11349]
I'm working with AppleScript, it's calling my bash script:
![screen shot 2017-12-27 at 4 41 25 pm](https://user-images.githubusercontent.com/1751906/34376059-d0754008-eb24-11e7-9c3d-c1755adb2951.png)

And here is my bash script: 
![screen shot 2017-12-27 at 4 31 03 pm](https://user-images.githubusercontent.com/1751906/34375801-5f313d76-eb23-11e7-87c5-857ace5abcc5.png)

But I got error:
![screen shot 2017-12-27 at 4 31 48 pm](https://user-images.githubusercontent.com/1751906/34375815-784baa08-eb23-11e7-8361-964154f482e8.png)

In fact, everything is working well if I call fastlane directly from Mac Terminal, or run my bash script directly from Mac Terminal.
Only fails when applescript calls my bash script.

**Comment by allen8300** [comment]
@fastlane-bot 
Thanks so much man, I updated my question.

**Comment by KrauseFx** [comment]
Seems like Apple script doesn't access your shell environment. You can try the following

1. Run this in the terminal manually `which fastlane`
1. Copy the full path and use that in your Apple script

**Comment by Panajev** [comment]
Try this:

```bash
#!/bin/bash --login
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#Debug checks...
rvm list
fastlane --version
[... rest of the original script]
```

Depending on how your shell is setup, this may do the trick.

if that fails too try to use bash --login to invoke your shell script from AppleScript.

**Comment by allen8300** [comment]
@KrauseFx @Panajev 
Yes, it works, I did it like this:
#fastlane env
export PATH="/Users/XXX/.rbenv/versions/2.4.3/bin:$PATH"
Thanks so much, man.

**Comment by KrauseFx** [comment]
Awesome 👍
