### ISSUE TITLE
While using sign_apk.rb I am facing /.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn': [!] wrong first argument

### ISSUE THREAD

**Issue by chandankumar-mob-incedo** [fastlane/fastlane#11343]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

While using sign_apk.rb I am facing /.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn': [!] wrong first argument (ArgumentError)

         sign_apk(
            apk_path: options[:apk_path],
            keystore_path: options[:keystore_path],
            alias: options[:alias],
            storepass: options[:storepass],
            tsa: "http://timestamp.comodoca.com/rfc316",
          )

##### Complete output when running fastlane, including the stack trace and command used

.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn': [!] wrong first argument (ArgumentError)
	from /Users/macmini/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /Users/macmini/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:190:in `popen2e'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/helper/sh_helper.rb:49:in `sh_control_output'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/macmini/fastlane/android/AndroidAppCMS/fastlane/actions/sign_apk.rb:30:in `run'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/macmini/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.70.3/bin/fastlane:20:in `<top (required)>'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/bin/fastlane:23:in `load'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/bin/fastlane:23:in `<main>'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/macmini/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-12-26**
</details>

**Comment by chandankumar-mob-incedo** [comment]
@KrauseFx Please give your input on this issue.

**Comment by KrauseFx** [comment]
Mh, seems like `sign_apk` isn't a fastlane action, but a third party action or plugin? If so, make sure to reach out to the original author

**Comment by chandankumar-mob-incedo** [comment]
@KrauseFx Yes correct. It's a third party plugin. I will check with the original author. Thanks for your response.

**Comment by ima747** [comment]
I am seeing the same behavior as well after updating to 2.71.1. Will investigate the custom action. @chandankumar-mob-incedo please update if you find anything and of course I will do the same.

**Comment by sharplet** [comment]
I also had this issue with a custom action in my project, and the ultimate cause was a change to the `Fastlane::Actions#sh` signature: https://github.com/fastlane/fastlane/commit/bb42e90bfc84bb64f1bb77470d4b558c5e47a773#diff-1199e480ea97c3165a58c7afdc48f00d.

Basically, you now need to pass a variadic argument list to `sh`, rather than an array. This is consistent with Ruby's various process launching methods, but was a breaking change for custom actions.

I think this is likely the problem line: https://github.com/appfoundry/fastlane-android-example/blob/796aae03baf7f03e6be5f7340480a2f29e9c2e5d/fastlane%20actions/sign_apk.rb#L30

**Comment by ima747** [comment]
Changing line 30 linked by @sharplet above to 

Fastlane::Actions.sh(sign_cmd.join(" "))

Appears to fix it for me.

I had to make similar modifications to the zipalign action I'm also using. Search for Fastlane::Actions.sh and modify the array args to join with spaces and it should be good. I dropped the log: true/false values everywhere since it's now a couple different log args and default is verbose and that's what I want anyway.

**Comment by sharplet** [comment]
I'd recommend `*sign_cmd` rather than `sign_cmd.join(" ")`, as that will handle escaping correctly.

**Comment by hjanuschka** [comment]
@jdee, @KrauseFx  i wonder if we can support both `variadic`  and `array` arguments, as this seems to break plugins. ?

**Comment by KrauseFx** [comment]
@hjanuschka did we break this, or is this just an extra way we'd support?

**Comment by ima747** [comment]
@sharplet I tried that first but it didn't work for no reason I could figure out (my Ruby skills are virtually non existant). Maybe I'll assume fat fingers and give it another try.

@KrauseFx It was definitely a change in Fastlane. My build process has been working fine with these custom actions for at least 5 months, just updated Fastlane today after the holidays and boom. It looks like the sh action currently supports variadic and string, but dropped support for array, would be nice to support all 3 for compatibility assuming it didn't muck anything up (again, no ruby skills here, don't know what's best practice).

**Comment by hjanuschka** [comment]
@KrauseFx yes i think we broke it, https://github.com/fastlane/fastlane/commit/bb42e90bfc84bb64f1bb77470d4b558c5e47a773#diff-1199e480ea97c3165a58c7afdc48f00dL30  - removed the `kind_of?(Array)` stuff, not sure how to fix it right now with the `*`.

**Comment by jdee** [comment]
I guess I broke that. Apologies. It's hard to support both forms without ditching something. Supporting an array would prevent this kind of usage: https://github.com/fastlane/fastlane/blob/master/fastlane/spec/helper/sh_helper_spec.rb#L49. I don't know if that's something Fastlane really needs to support, but one of the benefits of this approach is that it removes code and just allows you to do anything that, say, `system` supports. In order to support this syntax, custom code will have to be added and tested. (And there were no unit tests before for any of this, e.g. for array arguments.)

Also, the variadic style has a performance impact in that it does not use a shell at all. It simply calls fork and exec and passes the `command` array directly to `Kernel#exec`. You avoid an extra, unnecessary process.

For now, if anyone is using an array argument, I'd recommend that you just pass `*command`, etc. I don't mind submitting PRs to any plugins that need it.

But if there's a need to support passing arrays, we could. It's just that this makes Fastlane's `sh` method unique and unlike every other related method, including Rake's `sh` and `Kernel#system`. So it has to be documented and explained why this method alone behaves unlike everything else.

The current behavior of `sh` is documented here: https://docs.fastlane.tools/advanced/#using-the-sh-method

**Comment by jdee** [comment]
#11393 will address this issue, but after taking a closer look, I'm concerned about this usage. Nevertheless, it has to be fixed for now.

**Comment by jdee** [comment]
Apologies again for the trouble. This is fixed in the master branch. You can try it out with a Gemfile by adding `gem "fastlane", git: "https://github.com/fastlane/fastlane"` to your Gemfile and running `bundle install`. I'm sure it won't be long until it's released.
