### ISSUE TITLE
How to help match choose provisioning profiles automatically?

### ISSUE THREAD

**Issue by andrey-lisovskiy** [fastlane/fastlane#11355]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi,

I have one project with a multiple targets in it, and want to integrate **fastlane** to automate build/deploy progress. Currently I have made one more target called **Universal**, and just updating bundleId/product name in it. For managing certificated/provisioning profiles I have set up **match**. How to help match choose provisioning profiles automatically? 

##### Complete output when running fastlane, including the stack trace and command used

❌  Code Signing Error: "Universal" requires a provisioning profile. Select a provisioning profile for the "Production" build configuration in the project editor.

** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[19:03:32]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.71.0                  |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS11.2.sdk        |
+---------------+-------------------------+

[19:03:32]: ▸ Check dependencies
[19:03:32]: ▸ Code Signing Error: "Universal" requires a provisioning profile. Select a provisioning profile for the "Production" build configuration in the project editor.
[19:03:32]: ▸ Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'xxxx/Universal-Info.plist'.
[19:03:32]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
[19:03:32]: 
[19:03:32]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[19:03:32]: 📋  For the complete and more detailed error log, check the full log at:
[19:03:32]: 📋  xxxx/Library/Logs/gym/Universal-Universal.log
[19:03:32]: 
[19:03:32]: Looks like fastlane ran into a build/archive error with your project
[19:03:32]: It's hard to tell what's causing the error, so we wrote some guides on how
[19:03:32]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[19:03:32]: Before submitting an issue on GitHub, please follow the guide above and make
[19:03:32]: sure your project is set up correctly.
[19:03:32]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[19:03:32]: the full commands printed out in yellow in the above log.
[19:03:32]: Make sure to inspect the output above, as usually you'll find more error information there
[19:03:32]: 
+------------------------------------+------------------------------------+
|                              Lane Context                               |
+------------------------------------+------------------------------------+
| DEFAULT_PLATFORM                   | ios                                |
| PLATFORM_NAME                      | ios                                |
| LANE_NAME                          | ios build                          |
| SIGH_PROFILE_TYPE                  | ad-hoc                             |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"xxxx"=>"match  |
|                                    | AdHoc xxxx
"}     |
+------------------------------------+------------------------------------+
[19:03:32]: Error building the application - see the log above

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | default_platform      | 0           |
| 2    | update_app_identifier | 0           |
| 3    | update_info_plist     | 0           |
| 4    | update_info_plist     | 0           |
| 5    | match                 | 13          |
| 💥   | gym                   | 31          |
+------+-----------------------+-------------+

[19:03:32]: fastlane finished with errors

[!] Error building the application - see the log above

### Environment

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
platform :ios do
   lane :build do |options|
      update_app_identifier(xcodeproj: "xxx.xcodeproj", plist_path: "xxx/Universal-Info.plist", app_identifier: "XXXX")
      update_info_plist(xcodeproj: "xxx.xcodeproj", plist_path: "xxx/Universal-Info.plist", display_name: "XXXX")
      update_info_plist(xcodeproj: "xxx.xcodeproj", plist_path: "xxx/Universal-Info.plist", block: lambda { |plist|
         urlScheme = plist["CFBundleURLTypes"].find{|scheme| scheme["CFBundleURLName"] == "xxxxx"}
         urlScheme[:CFBundleURLSchemes] = ["xxxx"] })
    match(app_identifier: 'xxxxx', type: 'adhoc')
    gym(
      workspace: 'xxx.xcworkspace',
      scheme: 'Universal',
      clean: 'true',
      silent: 'true',
      export_xcargs: 'PRODUCT_BUNDLE_IDENTIFIER=XXXX',
      export_method: options[:method] || 'ad-hoc', # Available options: app-store, ad-hoc, package, enterprise, development, developer-id
    )
   end

   lane :certificates do
      match(app_identifier: 'xxxx', readonly: true)
   end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "xxxxxx"
team_id "xxxxxx"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.71.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                | Version | Update-Status |
| ------------------------------------- | ------- | ------------- |
| fastlane-plugin-get_product_bundle_id | 0.1.2   | ✅ Up-To-Date  |
| fastlane-plugin-get_product_bundle_id | 0.1.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| slack-notifier                        | 1.5.1        |
| CFPropertyList                        | 2.3.6        |
| claide                                | 1.0.2        |
| colored2                              | 3.1.2        |
| nanaimo                               | 0.2.3        |
| xcodeproj                             | 1.5.4        |
| rouge                                 | 1.11.1       |
| xcpretty                              | 0.2.6        |
| terminal-notifier                     | 1.8.0        |
| unicode-display_width                 | 1.1.3        |
| terminal-table                        | 1.7.3        |
| plist                                 | 3.4.0        |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.5.2        |
| multipart-post                        | 2.0.0        |
| word_wrap                             | 1.0.0        |
| tty-screen                            | 0.6.3        |
| babosa                                | 1.0.2        |
| colored                               | 1.2          |
| highline                              | 1.7.10       |
| commander-fastlane                    | 4.4.5        |
| excon                                 | 0.60.0       |
| faraday                               | 0.13.1       |
| unf_ext                               | 0.0.7.4      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20170404 |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| fastimage                             | 2.1.1        |
| gh_inspector                          | 1.0.3        |
| json                                  | 1.8.1        |
| mini_magick                           | 4.5.1        |
| multi_json                            | 1.12.2       |
| multi_xml                             | 0.6.0        |
| rubyzip                               | 1.2.1        |
| security                              | 0.1.3        |
| xcpretty-travis-formatter             | 0.0.4        |
| dotenv                                | 2.2.1        |
| bundler                               | 1.14.6       |
| faraday_middleware                    | 0.11.0.1     |
| uber                                  | 0.1.0        |
| declarative                           | 0.0.10       |
| declarative-option                    | 0.1.0        |
| representable                         | 3.0.4        |
| retriable                             | 3.1.1        |
| mime-types-data                       | 3.2016.0521  |
| mime-types                            | 3.1          |
| little-plugger                        | 1.1.4        |
| logging                               | 2.2.2        |
| jwt                                   | 1.5.6        |
| memoist                               | 0.16.0       |
| os                                    | 0.9.6        |
| signet                                | 0.7.3        |
| googleauth                            | 0.5.1        |
| httpclient                            | 2.8.3        |
| google-api-client                     | 0.13.6       |
| libxml-ruby                           | 3.0.0        |
| fastlane-plugin-get_product_bundle_id | 0.1.2        |
</details>

*generated on:* **2017-12-27**
</details>

![- -2017-12-27- -19 06 48](https://user-images.githubusercontent.com/7079771/34388172-dd625b00-eb3a-11e7-9ed9-af184398b3e4.png)
![- -2017-12-27- -19 07 06](https://user-images.githubusercontent.com/7079771/34388175-dd7fde96-eb3a-11e7-998b-276c27122a10.png)

**Comment by andrey-lisovskiy** [comment]
Was able to do this by adding following to fastlane.

```
gym(
      xcargs: {
          :PROVISIONING_PROFILE_SPECIFIER => 'match AppStore com.dev.Fastlane-test'
      }
)
```

**Comment by andrey-lisovskiy** [comment]
Still searching solution to choose provisioning profile automatically on Jenkins.

**Comment by KrauseFx** [comment]
The [Xcode guide](https://docs.fastlane.tools/codesigning/xcode-project/) didn't help? It covers that..

**Comment by andrey-lisovskiy** [comment]
@KrauseFx Hi, the app has one Universal target and bundle id is changing by _update_app_identifier, update_info_plist_ each time.  How can I set provisioning profiles automatically, without choosing manually _match Appstore Foo_?

**Comment by KrauseFx** [comment]
Check out the available actions https://docs.fastlane.tools/actions/#code-signing

Looks like https://docs.fastlane.tools/actions/update_project_provisioning/ might help?

**Comment by andrey-lisovskiy** [comment]
Sorry, how can I found path for provisioning profile on Jenkins?

**Comment by andrey-lisovskiy** [comment]
So, as I understand:
I should download provisioning using `get_provisioning_profile`
Provide path to provisioning profile in `update_project_provisioning`
Right?

**Comment by andrey-lisovskiy** [comment]
Was able to do this with above.

**Comment by KrauseFx** [comment]
Awesome, glad to hear 👍 Have fun @andrey-lisovskiy, and welcome to the fastlane community
