### ISSUE TITLE
Match Certificates

### ISSUE THREAD

**Issue by chshapiro** [fastlane/fastlane#11357]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
What happens when a certificate on the Apple Dev Portal? Will running `match` create a new one?

**Comment by pav1790** [comment]
https://github.com/fastlane/fastlane/blob/master/match/lib/match/spaceship_ensure.rb#L40 

**_I believe_** this would get called everytime. It checks if the certificate exists. If not, it will error out.

**Comment by KrauseFx** [comment]
You mean when you revoke an existing one? Yah, _match_ will help you resolve it, or even resolve it for you 👍
