### ISSUE TITLE
Update Xcode Code Signing

### ISSUE THREAD

**Issue by jaumevn** [fastlane/fastlane#11354]
### Issue Description
I have a white-label app project on iOS that needs to use different provisioning files and certificates for specific environments. I've successfully integrated `match` with a git repo and different branches per each project, it creates the new certificates and provisioning if needed, otherwise fastlane download and install them.

The issue I have is that when fastlane is compiling with `gym` seems that the project settings hasn't been updated after `match` action has run without errors. The `gym` action throws the following error:

```
Code Signing Error: No profile for team 'XXX' matching 'YYY' found:  Xcode couldn't find any provisioning profiles matching 'XXX/YYY'
```
Where `XXX` is the team id, `YYY` the name of the provisioning file. The issue is that those values are not the new ones downloaded and installed by `match` action, they are the old ones that are set by default by our Xcode project.

Is there anything I should do in order to update the Xcode settings? If run fastlane using the default environment settings, the `match` action downloads and install cert and provisioning files as well, and the `gym` action runs without any issues.

**Comment by KrauseFx** [comment]
The code signing guide above should yield the answers you're looking for
