### ISSUE TITLE
There is no route for the path 'apps/App_ID/pricing' error

### ISSUE THREAD

**Issue by willbt** [fastlane/fastlane#11368]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

/Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/spaceship/lib/spaceship/client.rb:642:in `parse_response': [!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::Client::UnexpectedResponse)
<String>There is no route for the path 'apps/1326756760/pricing'.</String>

	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/spaceship/lib/spaceship/tunes/tunes_client.rb:538:in `price_tier'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/spaceship/lib/spaceship/tunes/application.rb:234:in `price_tier'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/deliver/lib/deliver/upload_price_tier.rb:11:in `upload'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/deliver/lib/deliver/runner.rb:111:in `upload_metadata'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/deliver/lib/deliver/runner.rb:25:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:68:in `block (2 levels) in parsing_binding'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.71.0/bin/fastlane:20:in `<top (required)>'
	from /Users/distiller/.gem/ruby/2.3.5/bin/fastlane:22:in `load'
	from /Users/distiller/.gem/ruby/2.3.5/bin/fastlane:22:in `<main>'

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.6                                           |
| Ruby                        | 2.3.5                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.13.5 (Apple Git-94)                 |
| Installation Source         | ~/.gem/ruby/2.3.5/bin/fastlane                    |
| Host                        | Mac OS X 10.12.6 (16G29)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.5/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-9.0.1.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.49.0"

default_platform :ios

build_version = ENV["CIRCLE_TAG"] || ENV["CIRCLE_BUILD_NUM"] || "0" 

identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

increment_build_number(
  build_number: build_version, # specify specific build number (optional, omitting it increments by one)
  xcodeproj: "ProjectName.xcodeproj" # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
)

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  #desc "Runs all the tests"
  #lane :test do
  #  scan
  #end


  desc "Test version"
  lane :test do
    gym(scheme: "ProjectNameTest", export_method: "ad-hoc", workspace:"ProjectName.xcworkspace", export_options: {
      provisioningProfiles: { "com.ProjectName.cem.members.app.test": "ProjectName_CEM_members_TEST_AdHoc_13_11_17" }
    }) 
  end

  desc "QA version"
  lane :qa do
    gym(scheme: "ProjectNameQa", export_method: "ad-hoc", workspace:"ProjectName.xcworkspace", export_options: {
      provisioningProfiles: { "com.ProjectName.cem.members.app.qa": "ProjectName_CEM_members_QA_AdHoc_13_11_17" }
    }) 
  end
  
  desc "Staging version"
  lane :staging do
    gym(scheme: "ProjectNameStaging", export_method: "enterprise", workspace:"ProjectName.xcworkspace", export_options: {
      provisioningProfiles: { "com.ProjectName.cem.members.app.staging": "ProjectName_CEM_members_STAGING_enterprise_9_11_17" }
    }) 
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "ProjectNameProd", export_method: "app-store", workspace:"ProjectName.xcworkspace", export_options: {
      provisioningProfiles: { "com.ProjectName.cem.members.app": "ProjectName_CEM_members_PROD_AppStore_23_12_17" }
    }) 
    deliver(force: true, submit_for_review: false)
    # frameit
  end
  lane :local do
    gym(scheme: "ProjectName", export_method: "ad-hoc", workspace:"ProjectName.xcworkspace") # Build your app - more options available
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ProjectName.cem.members.app"
apple_id "it@ProjectName.com"
team_id "7W87XC744Y"

for_platform :ios do
  for_lane :test do
    app_identifier "com.ProjectName.cem.members.app.test"
  end
  for_lane :qa do
    app_identifier "com.ProjectName.cem.members.app.qa"
  end
  for_lane :staging do
    app_identifier "com.ProjectName.cem.members.app.staging"
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.71.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

[INSERT OUTPUT HERE]

**Comment by pav1790** [comment]
@willbt Check out the conversation here : https://github.com/fastlane/fastlane/pull/11314
