### ISSUE TITLE
undefined method for Spaceship::TestFlight::Tester

### ISSUE THREAD

**Issue by miixell** [fastlane/fastlane#11366]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello! 
So I'm trying to find and then remove external test users in Testflight. 

First, I tried the command that is stated in the docs: `fastlane pilot find testuser@email.com -u myemail@email.com` -- but got the error: ***[!] Some operations failed: `app_id' is a required parameter*** 

Then I added the 'app_id' parameter: 
`fastlane pilot find -e testuser@email.com -u myemail@email.com -a bundle.app.id --verbose`

However, I got the error that is pasted below. 

```
`Loading session from '/Users/******/.fastlane/spaceship/myemail@*******.com/cookie'
Looking for iTunes Connect Team with ID *********
INFO [2017-12-28 16:03:51.30]: Login successful
INFO [2017-12-28 16:04:00.41]: Found existing tester ********@**.com
ERROR [2017-12-28 16:04:00.41]:` undefined method `latest_build' for #<Spaceship::TestFlight::Tester:0xhexadecimalnumber>`
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] `Some operations failed: undefined method `latest_build' for #`<Spaceship::TestFlight::Tester:0xhexadecimalnumber> (FastlaneCore::Interface::FastlaneError)`
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/pilot/lib/pilot/commands_generator.rb:119:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/pilot/lib/pilot/commands_generator.rb:160:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/fastlane/lib/fastlane/cli_tools_distributor.rb:67:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.71.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
`
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.6 (Apple Git-96)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.71.0  | ✅ Up-To-Date  |

**Comment by lsblakk** [comment]
I'm having this issue as well - and it does look like fastlane env has been included by the OP
