### ISSUE TITLE
Specifying 'release notes' when metadata is in a custom folder

### ISSUE THREAD

**Issue by gerbil802** [fastlane/fastlane#11367]
Hi,

Is there a way to use Deliver with a custom metadata folder, yet specify the _release notes_ in a  parameter? The reason I'm asking is because I don't want to edit the `release_notes.txt` file for each localization.

In other words, is it possible to specify default release notes when there are localizations in the metadata folder?

**Comment by KrauseFx** [comment]
Yes, passing the value via a parameter as part of the `Fastfile` will do the trick :)

**Comment by gerbil802** [comment]
Thanks @KrauseFx. The default value didn't trigger for me and I realized that I have release_notes.txt in the localization and Deliver preferred _it_ over default in the parameters. That part was confusing at first :-)
