### ISSUE TITLE
Fastlane match keeps recreating the provisioning profile

### ISSUE THREAD

**Issue by buscarini** [fastlane/fastlane#11396]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane keeps recreating the provisioning profile for an inhouse app every time it runs. I checked an older thread about this, but I'm not sure if it's due to the same thing, and that seems to be fixed. I also tried debugging, but the only thing I found is that match runs sigh with force=true, and then the profile is recreated. I think it would be good to add in the sigh/match output information about why the profile is being recreated. This looks strange:

> [12:23:50]: Found 1 matching profile(s)
> [12:23:50]: Recreating the profile

##### Complete output when running fastlane, including the stack trace and command used

$ fastlane match appstore -r [git_url] -a [app_id] -u [user_id]

[⠋] 🚀 /Users/josanchez/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/tty-screen-0.6.3/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
/Users/josanchez/.rvm/gems/ruby-2.3.1@global/gems/tty-screen-0.6.3/lib/tty/version.rb:3: warning: previous definition of VERSION was here
[✔] 🚀 
[12:22:39]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-----------------------+------------------------------------------------------------+
|                              Summary for match 2.72.0                              |
+-----------------------+------------------------------------------------------------+
| git_url               | [REDACTED]                                                 |
| app_identifier        | [REDACTED]                                                 |
| username              | [REDACTED]	                                                |
| type                  | appstore                                                   |
| git_branch            | master                                                     |
| keychain_name         | login.keychain                                             |
| readonly              | false                                                      |
| verbose               | false                                                      |
| force                 | false                                                      |
| skip_confirmation     | false                                                      |
| shallow_clone         | false                                                      |
| clone_branch_directly | false                                                      |
| force_for_new_devices | false                                                      |
| skip_docs             | false                                                      |
| platform              | ios                                                        |
+-----------------------+------------------------------------------------------------+

[12:22:39]: Cloning remote git repo...
[12:22:39]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:23:31]: 🔓  Successfully decrypted certificates repo
[12:23:32]: Verifying that the certificate and profile are still valid on the Dev Portal...
[12:23:35]: Installing certificate...

+-------------------+---------------------------------------------+
|                      Installed Certificate                      |
+-------------------+---------------------------------------------+
| User ID           | [REDACTED]                                  |
| Common Name       | iPhone Distribution: [REDACTED]             |
| Organisation Unit | [REDACTED]                                  |
| Organisation      | [REDACTED]                                  |
| Country           | US                                          |
| Start Datetime    | Mar 17 08:21:01 2016 GMT                    |
| End Datetime      | Mar 17 08:21:01 2019 GMT                    |
+-------------------+---------------------------------------------+

+-------------------------------------+--------------------------------+
|                       Summary for sigh 2.72.0                        |
+-------------------------------------+--------------------------------+
| app_identifier                      | [REDACTED]                     |
| username                            | [REDACTED]                     |
| force                               | true                           |
| cert_id                             | [REDACTED]                     |
| provisioning_name                   | [REDACTED]                     |
| ignore_profiles_with_different_name | true                           |
| platform                            | ios                            |
| adhoc                               | false                          |
| development                         | false                          |
| skip_install                        | false                          |
| skip_fetch_profiles                 | false                          |
| skip_certificate_verification       | false                          |
| readonly                            | false                          |
+-------------------------------------+--------------------------------+

[12:23:42]: Starting login with user '[REDACTED]'
[12:23:44]: Successfully logged in
[12:23:44]: Fetching profiles...
[12:23:45]: Verifying certificates...
[12:23:50]: Found 1 matching profile(s)
[12:23:50]: Recreating the profile
[12:23:54]: Creating new provisioning profile for '[REDACTED]' with name '[REDACTED]' for 'ios' platform
[12:23:55]: Downloading provisioning profile...
[12:23:56]: Successfully downloaded provisioning profile...
[12:23:56]: Installing provisioning profile...
/var/folders/bk/0fgz68ts39753prpgsbd0q200000gn/T/d20180103-69559-1h9wtlr/profiles/appstore/InHouse_com.[REDACTED].mobileprovision
[12:23:56]: Installing provisioning profile...
[12:23:58]: 🔒  Successfully encrypted certificates repo
[12:23:58]: Pushing changes to remote git repo...

+---------------------+------------------------------------------+---------------------------------------------------------------+
|                                                 Installed Provisioning Profile                                                 |
+---------------------+------------------------------------------+---------------------------------------------------------------+
| Parameter           | Environment Variable                     | Value                                                         |
+---------------------+------------------------------------------+---------------------------------------------------------------+
| App Identifier      |                                          | [REDACTED]                                                    |
| Type                |                                          | appstore                                                      |
| Platform            |                                          | ios                                                           |
| Profile UUID        | [REDACTED]                               | [REDACTED]                                                    |
| Profile Name        | [REDACTED]                               | match AppStore [REDACTED]                                     |
| Profile Path        | [REDACTED]                               | /Users/josanchez/Library/MobileDevice/Provisioning            |
|                     |                                          | Profiles/[REDACTED].mobileprovision                           |
| Development Team ID | sigh_com.ssm.zeder_appstore_team-id      | [REDACTED]                                                    |
+---------------------+------------------------------------------+---------------------------------------------------------------+

[12:24:01]: All required keys, certificates and provisioning profiles are installed 🙌

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.

fastlane_version "1.11.0"

default_platform :ios

platform :ios do
  
  before_all do
        
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    #cocoapods

    # increment_build_number

    # ipa({
    #   scheme: ""
    # })

    #xctool # run the tests of your app
  end


  
  ## 
  ## Create in App Store
  ## 

  desc "Create in app store"
  lane :create do
    produce(
      username: File.read("Config/apple_id.txt"), 
      app_identifier: File.read("Config/app_identifier.txt"), 
      app_name: File.read("Config/name.txt"),
      company_name: File.read("Config/company_name.txt"),
      language: "English",
      app_version: File.read("metadata/currentVersion.txt"),
      sku: File.read("Config/app_identifier.txt")
    )

  end


  ## 
  ## Create Enterprise
  ## 
  desc "Create for enterprise"
  lane :createEnterprise do
    produce(
      username: File.read("Config/Enterprise/apple_id.txt"), 
      app_identifier: File.read("Config/Enterprise/app_identifier.txt"), 
      app_name: File.read("Config/name.txt"),
      language: "English",
      app_version: File.read("metadata/currentVersion.txt"),
      sku: File.read("Config/Enterprise/app_identifier.txt")
    )

  end
 

  ##
  ## Generate Certs & Push & Profiles
  ##
  
  lane :certsPushProfiles do

  	push_dev
  	push_prod
  	match_adhoc

  end


  ##
  ## Match for all certificates
  ##

  lane :certificates do

    match_appstore
    match_development
    match_adhoc

  end

  lane :match_appstore do
    match(
        type: "appstore",
        force: false,
        git_url: File.read("Config/certs_repo_url.txt"),
        app_identifier: File.read("Config/app_identifier.txt"),
        username: File.read("Config/apple_id.txt")
      )
  end

   lane :match_development do
    register_devices(devices_file: "fastlane/Config/devices.txt") 
    match(
      git_url: File.read("Config/certs_repo_url.txt"),
      force: false,
      app_identifier: File.read("Config/app_identifier.txt"),
      type: "development",
      username: File.read("Config/apple_id.txt")
    )
  end

  lane :match_adhoc do
    match(
      git_url: File.read("Config/certs_repo_url.txt"),
      force: false,
      app_identifier: File.read("Config/app_identifier.txt"),
      type: "adhoc",
      username: File.read("Config/apple_id.txt")
    )
  end



  ##
  ## Match for enterprise certificates
  ##

  lane :match_enterprise do

  	match_enterprise_dev
  	match_enterprise_release

  end


  ##
  ## Match for enterprise dev
  ##

  lane :match_enterprise_dev do

  	match(
  		git_url: File.read("Config/Enterprise/certs_repo_url.txt"),
  		app_identifier: File.read("Config/Enterprise/app_identifier.txt"),
  		type: "development",
  		username: File.read("Config/Enterprise/apple_id.txt"),
      force_for_new_devices: false
  	)

  end


  ##
  ## Match for enterprise release
  ##

  lane :match_enterprise_release do

  	match(
  		git_url: File.read("Config/Enterprise/certs_repo_url.txt"),
  		app_identifier: File.read("Config/Enterprise/app_identifier.txt"),
  		type: "appstore",
  		username: File.read("Config/Enterprise/apple_id.txt"),
      force: false,
      force_for_new_devices: false
  	)

  end


  ##
  ## Push DEV-Enterprise
  ##


  desc "Generate Dev certs"
  lane :push_dev_enterprise do
    
    pem(development: true,
        generate_p12: true,
        save_private_key: true,
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    match_enterprise_dev

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]


  end


  ##
  ## Push PROD-Enterprise
  ##


  desc "Generate Dev certs"
  lane :push_prod_enterprise do
    
    pem(development: false,
        generate_p12: true,
        save_private_key: true,
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    match_enterprise_release

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]


  end


  ##
  ## Push DEV
  ##


  desc "Generate Dev certs"
  lane :push_dev do
    
    pem(development: true,
        generate_p12: true,
        save_private_key: true,
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    match_development

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]


  end



  ## 
  ## Push PROD
  ## 

  desc "Generate Prod Push certs"
  lane :push_prod do
    
    pem(generate_p12: true,
        save_private_key: true,
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    match_appstore

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

  end


  ## 
  ## Push DEMO
  ## 

  desc "Generate Demo Push certs"
  lane :push_demo do
    
    pem(generate_p12: true,
        save_private_key: true,
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    certificates

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]


  end


  ##
  ## Build IPA
  ##

  desc "Build app"
  lane :build_app do

    gym(
      workspace: "../Code/" + File.read("./Config/workspace.txt") + ".xcworkspace",
      scheme: File.read("Config/scheme.txt"),
      # xcargs: "CODE_SIGN_IDENTITY='...' PROVISIONING_PROFILE='#{ENV["PROFILE_UDID"]}'",
      configuration: "Release",
      clean: true,
      silent: true
    )

  end


  ## 
  ## Test App
  ## 

  desc "Test app"
  lane :test_app do
    xctool :test,["-workspace", "../Code/" + File.read("./Config/workspace.txt") + ".xcworkspace",
            "-scheme", File.read("Config/scheme.txt"),
            "-configuration","Release",
            "-sdk","iphoneos"].join(" ")
  end


  ## 
  ## Test
  ## 

  desc "Runs all the tests"
  lane :test do
    cocoapods
    build_app
    test_app
  end
  
  
  ## 
  ## Screenshots
  ## 

  desc "Takes screenshots for configured devices/languages"
  lane :screenshots do

    snapshot

  end
  
  
  ## 
  ## Update App Store Metadata
  ## 

  desc "Update App Store metadata"
  lane :metadata do

    deliver(force: true,
        skip_screenshots: false,
        skip_metadata: false)

  end


  ## 
  ## Upload ipa
  ## 

  desc "Deploy a new version to the App Store"
  lane :uploadIpa do

      push_prod
 
      build_app
             
      deliver(force: true,
        skip_screenshots: true,
        skip_metadata: true)
    
  end


  ## 
  ## Deploy to App Store & Beta ITC
  ## 

  desc "Deploy a new version to the App Store"
  lane :deploy do

      push_prod
 
      build_app
             
      deliver(force: true)

  end



  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(message: "The lane " + lane + " completed successfully")
  end


  error do |lane, exception|
    # slack(message: exception.message,
    #       success: false)
  end

end


# More information:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id File.read("Config/apple_id.txt")
app_identifier File.read("Config/app_identifier.txt")

for_lane :push_dev_enterprise do
	apple_id File.read("Config/Enterprise/apple_id.txt")
	app_identifier File.read("Config/Enterprise/app_identifier.txt")
end

for_lane :push_prod_enterprise do
	apple_id File.read("Config/Enterprise/apple_id.txt")
	app_identifier File.read("Config/Enterprise/app_identifier.txt")
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.72.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.4        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.5        |
| bundler                   | 1.15.4       |
</details>

*generated on:* **2018-01-03**
</details>

**Comment by KrauseFx** [comment]
```
+-------------------------------------+--------------------------------+
| Summary for sigh 2.72.0 |
+-------------------------------------+--------------------------------+
| app_identifier | [REDACTED] |
| username | [REDACTED] |
| force | true |
```
interesting, the `force` parameter is true for your _sigh_ call. I wonder why that is, it shouldn't be the case. Can you look through the environment variables you set and see if there is something there?

**Comment by KrauseFx** [comment]
It looks like the provisioning profile isn't stored in your git repo, can you confirm that that's the case?

**Comment by buscarini** [comment]
It seems to be there, inside profiles/appstore/InHouse_[REDACTED].mobileprovision

**Comment by pvinis** [comment]
this is happening to me too. i have the profile in the repo, and match recreates every time.

**Comment by joshdholtz** [comment]
I have seen this myself on a project and I did something to fix it but I don't remember what it was right now 😔 I will try to see if I can remember what I did 🤔

**Comment by thunky-monk** [comment]
Could it possibly be related to having a non-iOS device registered, like an Apple TV? If you have X devices registered including Y non-iOS devices. The iOS provisioning profiles will include X - Y devices. Thus, the "device count" could be interpreted as changed?

**Comment by spandanabatchu** [comment]
Im having the same issue. I can confirm that the provisioning profile exists in my repo. But it says :
Found 1 matching profile(s)
Recreating the profile
While it does that, it doesnt use the cert that in my match repo. It picks a different cert that's on the dev portal.

**Comment by joshdholtz** [comment]
@spandanabatchu Do you have `force` set to `true`? `match` currently uses "newest" cert to make a profile (I'm hoping to change this soon). Best bet is to expire that cert and recreate it within match or import it into `match` manually 😬
