### ISSUE TITLE
Would you accept a PR to add sigh option install a provisioning profile from the local filesystem?

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#11408]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run my `fastlane` lanes, I want to ensure that my provisioning profiles are up to date, but I keep my provisioning profiles committed into git, so I don't want to have to depend on Apple's Developer Center being up to be able to install the latest provisioning profile. Right now, [I install the local profiles](https://stackoverflow.com/a/48083698/9636) similarly to [the way you do it](https://github.com/fastlane/fastlane/blob/eb0d3fe3979184f28cb501dc2d313b5a160bd7ef/sigh/lib/sigh/local_manage.rb#L15), but ideally, I would just use `sigh` because `sigh` is more likely to be up to date if something changes.

Would you accept a PR that ads a `--local-install` option that takes a file path to a local provisioning profile to install?

**Comment by hjanuschka** [comment]
@hborders ✋ 

not 100% sure about the PR, for me it sounds like you are looking for a tool to manager provisioning profiles. take a look at _match_  https://docs.fastlane.tools/actions/match/#easily-sync-your-certificates-and-profiles-across-your-team-using-git

it stores prov.profs and certs secure and encrypted in a git repo.


let me know if that helps you.

**Comment by hborders** [comment]
Thanks for your prompt response! I'm aware of `match`, but my team already has a standardized secrets database in which we store all company-wide secrets, including our private keys, so I can't use `match` for this purpose. I'm simply trying to avoid having a dependency on the Apple Developer Center with every build since the Apple Developer Center sometimes goes down. Most of the time, we simply generate local builds, and never have to hit an external network, so I'd very much like to continue that use case.
