### ISSUE TITLE
How to upload .pem file to git

### ISSUE THREAD

**Issue by andrey-lisovskiy** [fastlane/fastlane#11403]
Hi! I need to upload _.pem_ file to specific git url. How it can be done using **fastlane**?

**Comment by KrauseFx** [comment]
Nothing built-into fastlane for now, but you can easily use your own Ruby or shell scripts from within fastlane that do that 👍

**Comment by andrey-lisovskiy** [comment]
Thanks for response! 
Could you please navigate me to some example? 
I am not familiar with ruby (yet).

**Comment by KrauseFx** [comment]
You can use shell scripts (or any other language) by shelling out in fastlane using

```ruby
sh("./myShellScript.sh")
```
as part of your `lane` 👍
