### ISSUE TITLE
Match can't push certificate changes to remote repo

### ISSUE THREAD

**Issue by jordanpwood** [fastlane/fastlane#11406]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to setup `match` for the first time for an existing iOS project.  When I ran `bundle exec fastlane match development` the first time, or after a `bundle exec fastlane match nuke development`, then I get the attached output.  I just created the GitHub certificate repo and can push changes to the README file using normal `git` commands.  I have verified that the certificate repo only contains the README file, not any certificates. 

I have not yet updated my Fastfile to use match, since I have not gotten that far yet!

##### Complete output when running fastlane, including the stack trace and command used

$ bundle exec fastlane match development
[✔] 🚀 
[12:02:24]: Successfully loaded '/Users/woodj/Third_Iron/browzine_ios_app/fastlane/Matchfile' 📄

+----------+---------------------------------------------------+
|         Detected Values from './fastlane/Matchfile'          |
+----------+---------------------------------------------------+
| git_url  | https://github.com/thirdiron/ios_certificates.git |
| type     | development                                       |
| username | ios-dev@thirdiron.com                             |
+----------+---------------------------------------------------+

+-----------------------+---------------------------------------------------+
|                         Summary for match 2.72.0                          |
+-----------------------+---------------------------------------------------+
| type                  | development                                       |
| git_url               | https://github.com/thirdiron/ios_certificates.git |
| git_branch            | master                                            |
| app_identifier        | ["com.thirdiron.browzine"]                        |
| username              | ios-dev@thirdiron.com                             |
| keychain_name         | login.keychain                                    |
| readonly              | false                                             |
| team_id               | 6SFE9N8FZ4                                        |
| verbose               | false                                             |
| force                 | false                                             |
| skip_confirmation     | false                                             |
| shallow_clone         | false                                             |
| clone_branch_directly | false                                             |
| force_for_new_devices | false                                             |
| skip_docs             | false                                             |
| platform              | ios                                               |
+-----------------------+---------------------------------------------------+

[12:02:24]: Cloning remote git repo...
[12:02:24]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:02:24]: Migrating to new match...
[12:02:24]: Cloning remote git repo...
[12:02:24]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:02:25]: 🔓  Successfully decrypted certificates repo
keychain: "/Users/woodj/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_https://github.com/thirdiron/ios_certificates.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303130333138303134315A00  "20180103180141Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303130333138303134315A00  "20180103180141Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_https://github.com/thirdiron/ios_certificates.git"
    "type"<uint32>=<NULL>
password has been deleted.
[12:02:25]: Verifying that the certificate and profile are still valid on the Dev Portal...
[12:02:27]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+--------------------------------------------------+
|                     Summary for cert 2.72.0                      |
+---------------+--------------------------------------------------+
| development   | true                                             |
| force         | true                                             |
| username      | ios-dev@thirdiron.com                            |
| team_id       | 6SFE9N8FZ4                                       |
| keychain_path | /Users/woodj/Library/Keychains/login.keychain-db |
| platform      | ios                                              |
+---------------+--------------------------------------------------+

[12:02:27]: Starting login with user 'ios-dev@thirdiron.com'
[12:02:29]: Successfully logged in
[12:02:31]: Successfully generated 636YLNUEBD which was imported to the local machine.
[12:02:35]: Verifying the certificate is properly installed locally...
[12:02:35]: Successfully installed certificate 636YLNUEBD

+-------------------------------------+------------------------------------------+
|                            Summary for sigh 2.72.0                             |
+-------------------------------------+------------------------------------------+
| app_identifier                      | com.thirdiron.browzine                   |
| username                            | ios-dev@thirdiron.com                    |
| force                               | true                                     |
| cert_id                             | 636YLNUEBD                               |
| provisioning_name                   | match Development com.thirdiron.browzine |
| ignore_profiles_with_different_name | true                                     |
| team_id                             | 6SFE9N8FZ4                               |
| platform                            | ios                                      |
| development                         | true                                     |
| adhoc                               | false                                    |
| skip_install                        | false                                    |
| skip_fetch_profiles                 | false                                    |
| skip_certificate_verification       | false                                    |
| readonly                            | false                                    |
+-------------------------------------+------------------------------------------+

[12:02:35]: Starting login with user 'ios-dev@thirdiron.com'
[12:02:37]: Successfully logged in
[12:02:37]: Fetching profiles...
[12:02:38]: Verifying certificates...
[12:02:38]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[12:02:40]: Creating new provisioning profile for 'com.thirdiron.browzine' with name 'match Development com.thirdiron.browzine' for 'ios' platform
[12:02:41]: Downloading provisioning profile...
[12:02:41]: Successfully downloaded provisioning profile...
[12:02:42]: Installing provisioning profile...
/var/folders/d5/ntx8rq7n05j1_0z1hbk7y09c0000gp/T/d20180103-2944-1mco2pw/profiles/development/Development_com.thirdiron.browzine.mobileprovision
[12:02:42]: Installing provisioning profile...
[12:02:42]: 🔒  Successfully encrypted certificates repo
[12:02:42]: Pushing changes to remote git repo...
The following paths are ignored by one of your .gitignore files:
certs/development/636YLNUEBD.cer
Use -f if you really want to add them.
[12:02:42]: Exit status: 1
[12:02:42]: Couldn't commit or push changes back to git...
[12:02:42]: Exit status: 1

+---------------------+------------------------------------------------------+-------------------------------------------------------+
|                                                   Installed Provisioning Profile                                                   |
+---------------------+------------------------------------------------------+-------------------------------------------------------+
| Parameter           | Environment Variable                                 | Value                                                 |
+---------------------+------------------------------------------------------+-------------------------------------------------------+
| App Identifier      |                                                      | com.thirdiron.browzine                                |
| Type                |                                                      | development                                           |
| Platform            |                                                      | ios                                                   |
| Profile UUID        | sigh_com.thirdiron.browzine_development              | f33c7f5c-89e3-4d08-825c-7c62f7656f80                  |
| Profile Name        | sigh_com.thirdiron.browzine_development_profile-name | match Development com.thirdiron.browzine              |
| Profile Path        | sigh_com.thirdiron.browzine_development_profile-path | /Users/woodj/Library/MobileDevice/Provisioning        |
|                     |                                                      | Profiles/f33c7f5c-89e3-4d08-825c-7c62f7656f80.mobile  |
|                     |                                                      | provision                                             |
| Development Team ID | sigh_com.thirdiron.browzine_development_team-id      | 6SFE9N8FZ4                                            |
+---------------------+------------------------------------------------------+-------------------------------------------------------+

[12:02:42]: All required keys, certificates and provisioning profiles are installed 🙌

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = <REDACTED>
    ENV["CRASHLYTICS_API_TOKEN"] = <REDACTED>
    ENV["CRASHLYTICS_BUILD_SECRET"] = <REDACTED>
  end

  # NOTE: As of Xcode 7.3, running tests using scan makes Xcode unable to find all Swift tests in the project.
  #desc "Runs all the tests"
  #lane :test do
  #  scan(scheme: "BrowZine",
  #    skip_slack: true)
  #end

  desc "Send the current build to Crashlytics -- Use this to build a non-release test version from your local machine"
  lane :crash do
    #update_info_plist(
    #  plist_path: "browzine/browzine-info.plist",
    #  display_name: "Browzine-AdHoc"
    #)
    build_ad_hoc
    crashlytics
  end

  desc "Build the develop branch -- Use this to build develop from your local machine"
  lane :develop do
    build_ad_hoc
    crashlytics(
      groups: ["internal-testers"]
    )
    slack(
      message: "There's a new develop version available in Crashlytics!"
    )
  end

  desc "Submit a new Release Build to TestFlight -- Use this to build a release candidate from your local machine"
  lane :release do
    build_release
    test_flight_upload_for_release
    slack(
      message: "There will soon be a new release candidate available in TestFlight"
    )
  end

  desc "Submit a new Test Build to TestFlight -- Use this to make a test build from your local machine"
  lane :test do
    build_release
    test_flight_upload
    slack(
      message: "There will soon be a new test build available in TestFlight"
    )
  end

  desc "Build the master branch"
  lane :master do
    build_release
    test_flight_upload_for_release
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  lane :bump do
    version = get_version_number(target:"browzine")
    increment_build_number({
      build_number: latest_testflight_build_number(version:get_version_number(target:"browzine")) + 1
    })
  end

  lane :name_by_branch do
    build_value = "#{get_build_number}-#{git_branch}"
    set_info_plist_value(path: "browzine/browzine-info.plist", key: 'CFBundleVersion', value: build_value)
  end

  lane :build_release do
    cocoapods
    bump
    cert
    sigh
    gym(scheme: "BrowZine", clean:true)
  end

  lane :build_ad_hoc do
    cocoapods
    bump
    cert
    sigh(adhoc: true)    
    name_by_branch
    gym(scheme: "BrowZine", export_method: "ad-hoc", clean:true)
  end

  desc "Upload to TestFlight"
  lane :test_flight_upload_for_release do
    ensure_git_branch(   
      branch: "(master|release\\S+|hotfix\\S+)"    
    )        
    testflight(skip_waiting_for_build_processing: true, beta_app_description: "Release candidate")
    upload_symbols_to_crashlytics
  end

  desc "Upload to TestFlight"
  lane :test_flight_upload do
    testflight(skip_waiting_for_build_processing: true, beta_app_description: "Test build, not for release")
    upload_symbols_to_crashlytics
  end

  desc "Upload symbols to Crashlytics"
  lane :crash_upload do
    upload_symbols_to_crashlytics
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.thirdiron.browzine" # The bundle identifier of your app
apple_id "jordan@thirdiron.com" # Your Apple email address

team_id "6SFE9N8FZ4"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.72.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.11.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-01-03**
</details>

**Comment by hjanuschka** [comment]
check your `.gitignore` file according to the log you have something like `./cert/*` in it, which results in ignoring the certs.

**Comment by jordanpwood** [comment]
I would think that the `.gitignore` in question would be generated by `match` in the local certificates repo (just a theory). My certificate repo has no `.gitignore` in it.  My project `.gitignore` file has `certificates/`, but no reference to `cert/*`.

**Comment by hjanuschka** [comment]
after `match` fails. can you check the temp folder where it cloned the current repo into?
and have a look if there is a .gitignore? - very strange behaviour.

**Comment by jordanpwood** [comment]
Is the temp folder you mean `/var/folders/d5/ntx8rq7n05j1_0z1hbk7y09c0000gp/T/d20180103-2944-1mco2pw/` from the above output?  That directory is gone after match finishes running.  Is there a way for me to keep that from being cleaned up, or is there a different place I should be looking?

Thanks!

**Comment by dbeltram** [comment]
If it helps, make sure you have the writing access to the GitHub repository.
