### ISSUE TITLE
[Pilot] Localized "Beta app description" and "What to test"

### ISSUE THREAD

**Issue by tbaranes** [fastlane/fastlane#11421]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Duplicate of #9621 which has been auto-closed.
While there's the possibility to localise app's description, releases notes... we can't do it for TestFlight data. That's would be a great addition!

**Comment by minuscorp** [comment]
Hi! Do you think this something you can implement in a PR? We'll be glad to review it 🚀

**Comment by tbaranes** [comment]
If I get time to do it, I will definitely look into it, but that won't be that soon, so if anyone want to take care of this, don't wait for me!
