### ISSUE TITLE
Spaceship::Tunes::AppVersion.current_build_number is incorrect

### ISSUE THREAD

**Issue by ambientlight** [fastlane/fastlane#11420]
AppVersion `current_build_number` doesn't return the latest submitted build.
Specifically it takes the very first candidate build for edit version and candidate builds are not upload-time sorted (it turns out).

https://github.com/fastlane/fastlane/blob/7171725879ab8d4e78d501fbc663d0e59a0490eb/spaceship/lib/spaceship/tunes/app_version.rb#L315-L323

probably something like:
```ruby
def current_build_number 
   if self.is_live? 
     build_version 
   else 
     if candidate_builds.length > 0 
       candidate_builds.sort_by(&:upload_date).last.build_version
     end 
   end 
 end 
```

**Comment by ppamorim** [comment]
What number is this returning? Here is always zero.

**Comment by KrauseFx** [comment]
Ah nice catch, would you mind submitting a PR for this and testing if the new code works?

**Comment by ambientlight** [comment]
@ppamorim here you mean for your version?. I use `app.latest_version` which would use `candidate_builds` when there is no app-store submitted build in this version.

@KrauseFx 
sure. We actually use it in a custom action that retrieves the build_num from itunesconnect.

**Comment by KrauseFx** [comment]
Awesome, thanks 👍 Keep me posted, and let me know if you need any help
