### ISSUE TITLE
[frameit] Android support

### ISSUE THREAD

**Issue by Gp2mv3** [fastlane/fastlane#11429]
Why is Android not supported by Frameit ? 
I saw issue #9974 which is now closed but there is no clear answer...

Thanks a lot for your work guys !

**Comment by janpio** [comment]
#9974 is not closed, but several people are talking about maybe creating a PR to add this functionality. Until now nobody did, so there is no support for Android in `frameit` yet.

**Comment by Caspain** [comment]
I will take a shot at it. Any advice upfront first?

**Comment by janpio** [comment]
Have fun and just ask questions here if anything pops up! You can also create a PR with `[WIP]` in the title quite early to get feedback from CI and maybe some other contributors.
