### ISSUE TITLE
Test multiple Ruby versions on CI

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11428]
It would make sense to test multiple ruby versions in CI, starting with 2.0 up to current versions people might use.

Research:
- AppVeyor/Windows: https://mattbrictson.com/how-to-test-ruby-windows
- Circle CI: https://jtway.co/run-tests-against-multiple-ruby-versions-on-circleci-60e1e523e245

**Comment by minuscorp** [comment]
I think adding to the current circle CI configuration to test on multiple Ruby versions is a nice idea. Sometimes we receive PRs that add new functionality and is hard to know which operator or function was added in which Ruby version so I'm totally agreeing on this 😁
