### ISSUE TITLE
'build_id' is a required parameter on download_dsyms process

### ISSUE THREAD

**Issue by chikitin** [fastlane/fastlane#11435]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | Switch to ios provision lane        | 0           |
| 4    | produce                             | 6           |
| 5    | cert                                | 2           |
| 6    | sigh                                | 5           |
| 7    | Switch to ios build lane            | 0           |
| 8    | increment_build_number              | 0           |
| 9    | gym                                 | 320         |
| 10   | crashlytics                         | 214         |
| 11   | Switch to ios upload lane           | 0           |
| 12   | deliver                             | 402         |
| 13   | Switch to ios refresh_dsyms lane    | 0           |
| 💥   | download_dsyms                      | 7           |
+------+-------------------------------------+-------------+

[21:02:56]: fastlane finished with errors

When download_dsyms process it finished with errors: 'build_id' is a required parameter

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.38.1"

default_platform :ios

platform :ios do

  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    produce(
      app_name: '',
      language: 'English',
      app_version: '1.0.3',
      sku: 'x'
    )
    cert
    sigh(force: false)
  end

  desc "Creating a code signing certificate and provisioning profile for development"
  lane :provision_dev do
    produce(
      app_name: 'x',
      language: 'English',
      app_version: '1.0',
      sku: 'x'
    )
    cert
    sigh(development: true)
  end

  desc "Create ipa"
  lane :build do
    increment_build_number
    gym(scheme: "x")
    crashlytics(
      api_token: "fd4057e695fb90ba80d7e6b114a67470c42d0a0c",
      build_secret: "8edda5a6e2a7bab28ca035f7a171550a1a5f93f07c2ed241e363c83b7000a2b6"
    )
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

  desc "Refresh Dsyms"
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  desc "Provision, build and upload to App Store"
  lane :do_everything do
    provision
    build
    upload
    refresh_dsyms
  end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "x" # The bundle identifier of your app
apple_id "x" # Your Apple email address

team_id "" # Developer Portal Team ID
itc_team_id ""

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.72.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2018-01-04**
</details>

**Comment by chikitin** [comment]
I don't think so, my app was uploaded, but when trying to download and upload my dsyms files, it crashes. 

desc "Refresh Dsyms"
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

**Comment by hunhejj** [comment]
Same error here. Any solution?

**Comment by taquitos** [comment]
When running fastlane, could you add the `--verbose` option to the end of the command and then paste the contents? That should help us debug this is issue

**Comment by hunhejj** [comment]
This is the stack:
```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/client.rb:308:in `block in assert_required_params': [!] `build_id' is a required parameter (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/client.rb:306:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/client.rb:306:in `assert_required_params'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/client.rb:47:in `get_build'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/build.rb:100:in `find'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/build.rb:131:in `reload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/download_dsyms.rb:66:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/download_dsyms.rb:59:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/download_dsyms.rb:59:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/download_dsyms.rb:55:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/download_dsyms.rb:55:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:120:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by CRivlaldo** [comment]
Enabling of await of build processing worked for me.

`upload_to_testflight(skip_waiting_for_build_processing:false)`

Before the waiting was **true**.

**Comment by hunhejj** [comment]
I don't explicitly upload to testflight, but use `deliver` instead. I couldn't find any similar option for that one. However my guess is also some asynchronicity.

**Comment by mohammdsss1** [comment]
Same here

**Comment by treinberger** [comment]
+1

**Comment by tkoshida** [comment]
Inserting `sleep(8*60)` before `download_dsyms` worked for me.
Just waiting for iTC to process build.
