### ISSUE TITLE
[Swift] Documentation for how to start developing on the Swift project

### ISSUE THREAD

**Issue by kimdv** [fastlane/fastlane#11431]
🔑
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It would be awesome to have a description inside `fastlane/ToolsAndDebugging.md` with some guides to how debug and test the swift project 😄

**Comment by minuscorp** [comment]
Is this something you'd like to implement in a PR? 😁
