### ISSUE TITLE
765: Unexpected token at 'Bad Request' when calling to provisioningProfile.delete!

### ISSUE THREAD

**Issue by cfis** [fastlane/fastlane#11434]
Fastlane 2.72.0
This is likely related to #11162

Basic code:

profile = ::Spaceship::Portal.provisioning_profile.find_by_bundle_id(bundle_id: app.app_id).first
if profile.status == 'Invalid'
  profile.delete!
end

The root cause is Spaceship::PortalClient#provisioning_profiles_via_xcode_api

Line 590 in portal_client_id.rb:

      csrf_cache[Spaceship::ProvisioningProfile] = self.csrf_tokens

The problem is that the api response does not include and csrf_tokens, so self.csrf_tokens is an empty hash.  But since empty is not checked, then:

    def delete_provisioning_profile!(profile_id, mac: false)
      ensure_csrf(Spaceship::ProvisioningProfile) do
        fetch_csrf_token_for_provisioning
      end

The call the ensure_csrf checks for nil but not an empty hash:

    def ensure_csrf(klass)
      if csrf_cache[klass]
        self.csrf_tokens = csrf_cache[klass]
        return
      end

Thus the request is made with no tokens and you get a bad request.

This error just started happening for me recently.  I suspect the difference is the Apple account id I am using is now associated with multiple teams.  Previously it was not, and Fastlane was working (version 268).   Alternatively, maybe the  provisioning_profiles_via_xcode_api api no longer returns csfr tokens?

My quick fix is change:

      csrf_cache[Spaceship::ProvisioningProfile] = self.csrf_tokens

To:

      csrf_cache[Spaceship::ProvisioningProfile] = self.csrf_tokens unless self.csrf_tokens.empty?

**Comment by fullsailor** [comment]
I encountered this problem as well. It does seem like the Xcode API used in `PortalClient#provisioning_profiles_via_xcode_api` does not return csrf tokens, so the empty hash incorrectly bypasses the check in `ensure_csrf`.
