### ISSUE TITLE
Loading Indicator and Jenkins

### ISSUE THREAD

**Issue by carlosefonseca** [fastlane/fastlane#11441]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Recently (#11378) Deliver was updated with loading indicators for some tasks but this kind of stuff sucks when running on Jenkins (see the image). Could a`is_ci?` check be added to not animate this indicators on CI systems?

![](https://dsc.cloud/carlosefonseca/Screen-Shot-2018-01-05-15-46-14-LFqeM.png)

**Comment by fxfactorial** [comment]
This is exactly what I was talking about in my comments on the PR that introduced this feature originally.

**Comment by carlosefonseca** [comment]
Yeah, I saw the PR but missed the Issue and the discussion. I'm gonna close this one. See #11416.
