### ISSUE TITLE
Spaceship - Tunes Client - Cannot create user with apps

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#11444]
Hello,

I cannot seem to create new user with only few apps. I am using Spaceship library directly.

**Works:** Can create user with empty "apps" array. User gets access to "All Apps"

**Does not work:** When specifying few apps in "apps" array, it doesn't work. I have tried passing just an array of strings. Also obtained a proper "application" object, and tried passing it to the array, no dice. 

This is my code, 
```ruby
client = Spaceship::Tunes.client
all_apps = Spaceship::Tunes::Application.all # /fastlane/spaceship/lib/spaceship/tunes/application.rb
user_apps = []
["app name1", "app name 2"].each do |app|
  user_apps << all_apps.select { |a| a.name.casecmp(app) == 0 }
end

# Just app names.
client.create_member!(firstname: "abc", lastname: "def", email_address: "abc@def.com", roles: ["finance", "appmanager"], apps: ["app name1", "app name2"])

# "app" objects in array.
client.create_member!(firstname: "abc", lastname: "def", email_address: "abc@def.com", roles: ["finance", "appmanager"], apps: user_apps)

# Error
# Spaceship::TunesClient::ITunesConnectError: Posted data is not valid.
# from /Users/<user>/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.64.1/spaceship/lib/spaceship/tunes/tunes_client.rb:213:in `handle_itc_response'
```

I am not sure what mistake I am doing. Please help!

**Comment by scorpion35** [comment]
[fastlane-env.txt](https://github.com/fastlane/fastlane/files/1607895/fastlane-env.txt)

**Comment by scorpion35** [comment]
Anyone? Help, please!

@KrauseFx @taquitos Sorry to mention you guys directly, I am just hoping someone would help me. Many thanks in advance!

**Comment by taquitos** [comment]
Taking a look 🎈

**Comment by scorpion35** [comment]
@taquitos Thank you!!

**Comment by taquitos** [comment]
Ok, did some inspection here, you need a list of "AdamIds", which we call apple_id 🤕 

Here's some code that worked for me:

```ruby
client = Spaceship::Tunes.client
all_apps = Spaceship::Tunes::Application.all 
app_names_lower = ["App 1 Name", "App 2 Name"].map{ |name| name.downcase }.to_set
app_ids = all_apps.select{ |app| app_names_lower.include?(app.name.downcase) }.map{ |app| app.apple_id }
# Just app ids.
client.create_member!(firstname: "abc", lastname: "def", email_address: "abc@def.com", roles: ["finance", "appmanager"], apps: app_ids) if app_ids.length > 0
```

**Comment by taquitos** [comment]
I'm going to update that method so it's more obvious what should happen.

**Comment by scorpion35** [comment]
@taquitos Thank you for taking a look! Much appreciated!!

Unfortunately it didnt' work out for me :(

This is what I've tried, 
```ruby
# app_ids as array of strings - didn't work
client.create_member!(firstname: "abc", lastname: "def", email_address: "abc@def.com", roles: ["finance", "appmanager"], apps: ["12345", "54321"])

# app_ids as array of int's - didn't work
client.create_member!(firstname: "abc", lastname: "def", email_address: "abc@def.com", roles: ["finance", "appmanager"], apps: [12345, 54321])
```

![image](https://user-images.githubusercontent.com/18679225/35014001-30cd29ee-fadd-11e7-8636-c41d6ab00c42.png)

What was the data type of `app_ids` in the example that worked for you?

**Comment by taquitos** [comment]
`app_ids` is an `Array` of `String` for me

**Comment by taquitos** [comment]
Oh, the other thing, when I tried your first example, it created a tester, but I had to go delete them manually.

**Comment by taquitos** [comment]
Oh yeah, you're right, I didn't notice that, it's giving the user access to all apps 😞
