### ISSUE TITLE
Spaceship returning wrong testers

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#11453]
I am trying to get testers for a specific app using `bundle_id`.

Here is how I am trying to get:

```  
  client = Spaceship::TunesClient.new
  client.login(username, password)
  client.team_id = 123456

  apps = client.applications.find(bundle_id)
  testers = Spaceship::TestFlight::Tester.all(app_id: apps.first['adamId'])
```
This return testers for some other app; Not for the app specified by `bundle_id`. Am I doing it wrong?

**Comment by scorpion35** [comment]
@RishabhTayal The below works for me all the time, 

```ruby
apps = Spaceship::Tunes::Application.all
dot = apps.select { |a| a.name.casecmp("your app name") == 0 };
Spaceship::TestFlight::Tester::all(app_id: 123456)
```

**Comment by RishabhTayal** [comment]
@scorpion35 how did you login in spaceship? What happens if there are multiple teams?

**Comment by scorpion35** [comment]
@RishabhTayal Updated the code above.

**Comment by RishabhTayal** [comment]
@scorpion35 `select_team` is not supposed be used on CI system or sever? It requires user input.

**Comment by scorpion35** [comment]
@RishabhTayal Updated code above.
