### ISSUE TITLE
`fastlane match nuke` doesn't support enterprise accounts

### ISSUE THREAD

**Issue by vburojevic** [fastlane/fastlane#11463]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I didn't see anywhere in the docs that match doesn't support nuking of enterprise accounts, so this surprised me when I ran the command to nuke development certs and profiles on our Enterprise account. Is it possible to force this somehow? Or is this feature planned to be implemented in the future?

##### Complete output when running fastlane, including the stack trace and command used

`fastlane match nuke` doesn't support enterprise accounts

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

*generated on:* **2018-01-07**
</details>

**Comment by KrauseFx** [comment]
In case someone finds this issue, discussion happened on Twitter https://twitter.com/vburojevic/status/949941658644250624

**Comment by vburojevic** [comment]
I've decided to use UI confirmation instead of global env var.
I think this a better way to handle this, but let me know if this is not ok for you, I can adjust it to use the env var.

PR reference: #11522

**Comment by vburojevic** [comment]
PR merged!
