### ISSUE TITLE
[actions]: Ability to access / paste from clipboard

### ISSUE THREAD

**Issue by joncursi** [fastlane/fastlane#11462]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Within my `Fastfile`, I'm trying to paste the contents of my clipboard into a variable for usage in my script. I see there is a `clipboard` action for copying contents into the clipboard, but how does one do the reverse - extract **from** the clipboard?

The reason I need this is that one of the third-party CLI services that I invoke within my deploy script generates a unique URL and puts it on the clipboard, and I need access to that value in the remainder of my deploy script.

Thanks!

**Comment by joncursi** [comment]
To help clarify:

```ruby
    sh("npm run deploy:to:zeit:now") # puts a unique URL on the system clipboard
    slack(
      message: "Successfully deployed a new update to #{INSERT_CLIPBOARD_URL_HERE}", # need access to the clipboard value here
    )
```

**Comment by KrauseFx** [comment]
Hey @joncursi,
Great idea.

We recently introduced the new [fastlane plugin system](https://docs.fastlane.tools/plugins/create-plugin/) that allows you to distribute and maintain your own plugins, and still be exposed to `fastlane` users. 
We'd love this new action to be a `fastlane` plugin so people who want to use it, can easily add it to their project.
Please let us know how the integration goes, and if you need any help getting up and running 🚀
