### ISSUE TITLE
[Regression] method `app_id' not defined in Spaceship::TestFlight::Build (NameError)

### ISSUE THREAD

**Issue by michaelgmcd** [fastlane/fastlane#11481]
In versions 2.74.* I get the following error:
spaceship/lib/spaceship/base.rb:137:in `remove_method': method `app_id' not defined in Spaceship::TestFlight::Build (NameError)

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running any fastlane command, I get the following error, claiming that `method `app_id' not defined in Spaceship::TestFlight::Build (NameError)`

Note that I am not able to include information other than a screenshot due to the fact that every fastlane command throws this same error.

##### Complete output when running fastlane, including the stack trace and command used
![screen shot 2018-01-08 at 3 44 48 pm](https://user-images.githubusercontent.com/8161781/34691548-e876ad08-f48a-11e7-95ae-da2b9857e2f8.png)

**Comment by taquitos** [comment]
I'm trying to repro this now

**Comment by taquitos** [comment]
@michaelgmcd I can't repro on my setup, maybe you can try:
`rvm cleanup all` and followed by 
`rvm all-gemsets do gem cleanup`
this might be caused by stale gems.

**Comment by michaelgmcd** [comment]
Interesting. After running your commands, I still get the error. This has occurred on two mac machines and after installing in an ubuntu docker image.

**Comment by taquitos** [comment]
@michaelgmcd could you provide some simple docker setup instructions on how I can repro this? I'm a docker newb.

**Comment by itruf** [comment]
Same problem right now 👎 

MBP-Ivan-2:client itruf$ fastlane env
[⠋] 🚀 /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/tty-screen-0.6.3/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
/Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/tty-screen-0.6.3/lib/tty/version.rb:3: warning: previous definition of VERSION was here
[⠹] 🚀 /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:137:in `remove_method': method `app_id' not defined in Spaceship::TestFlight::Build (NameError)
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:137:in `block in attr_mapping'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:134:in `each'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:134:in `attr_mapping'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:62:in `<class:Build>'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:11:in `<module:TestFlight>'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:10:in `<module:Spaceship>'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:9:in `<top (required)>'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.74.1/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `<top (required)>'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/fastlane_core/lib/fastlane_core.rb:30:in `require_relative'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/fastlane_core/lib/fastlane_core.rb:30:in `<top (required)>'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/itruf/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/fastlane/lib/fastlane/cli_tools_distributor.rb:33:in `take_off'
	from /Users/itruf/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.74.1/bin/fastlane:20:in `<top (required)>'
	from /Users/itruf/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/itruf/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/itruf/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/itruf/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by taquitos** [comment]
@itruf have you tried cleaning all your gems? There were some big changes around how files are required last release, so if there is any cruft laying around, it could interfere.

**Comment by itruf** [comment]
@taquitos tried:` rvm cleanup all `and followed by
`rvm all-gemsets do gem cleanup`

**Comment by KrauseFx** [comment]
And can you confirm that this is happening only with the most recent release and it worked before? I could imagine it might be related to the change of how we require files (cc @milch) as I don't think we've changed any code in _spaceship_

**Comment by zenrobin** [comment]
seeing this as well with latest. I tried the rvm cleanup and it didn't help.  It all started when I did a sudo gem fastlane update to 2.74.1.

**Comment by zenrobin** [comment]
sudo gem install fastlane -v 2.71.1      and then  sudo gem uninstall fastlane  and pick 2.74.1  and I'm back up and running.

**Comment by KrauseFx** [comment]
I just pushed a PR that hopefully fixes the problem, gonna do a hotfix release with this change today: https://github.com/fastlane/fastlane/pull/11493

**Comment by snatchev** [comment]
I am at a loss of how a method returned by `public_instance_method` can also be undefined when attempted to be removed. I suppose anything is possible with ruby tho. I think @KrauseFx's PR takes a safe approach to what is attempted. 👍

**Comment by snatchev** [comment]
It does not appear that `app_id` was defined with an `attr_accessor` before it was mapped in this particular instance in `build.rd`. If that is the case, then we do not need to "replace" the method with the call to `remove_method`.

**Comment by itruf** [comment]
Thanks @KrauseFx! Good job, it works.

**Comment by KrauseFx** [comment]
Glad to hear, thanks 👍
