### ISSUE TITLE
slack action broken

### ISSUE THREAD

**Issue by hjanuschka** [fastlane/fastlane#1148]
i believe this commit https://github.com/fastlane/fastlane/commit/ce0b80e95dca9cfae4f7d02f7e10a48d1d33bd86#diff-ab1a6cace4c393dec2706737b2fbf18a

breaks the slack action

```bash
{
  "event_id": "7b005a4f8156e774d76bacbc109d05af",
  "message": "RuntimeError: \u001b[31mDo not let descriptions end with a '.', since it's used for user inputs as well\u001b[0m",
  "timestamp": "2016-01-19T08:37:24",
  "time_spent": null,
  "level": 40,
  "project": null,
  "platform": "ruby",
  "logger": "",
  "culprit": "fastlane_core/configuration/config_item.rb in initialize at line 25",

```

@KrauseFx  i think this one is urgent

**Comment by asfalcone** [comment]
Thanks for reporting. I believe https://github.com/fastlane/fastlane/pull/1146 address this. @hjanuschka could you confirm?

**Comment by hjanuschka** [comment]
yes i think this fixes it!

Von meinem iPhone gesendet

**Comment by hjanuschka** [comment]
ok confirmed to be fixed - on current master!
