### ISSUE TITLE
Use specific SSH keys

### ISSUE THREAD

**Issue by aloifolia** [fastlane/fastlane#1149]
I am using Fastlane on a Jenkins machine. The code is shared via Bitbucket. Now, in order to have access to the code on Bitbucket at Jenkins I added a Git deployment key. Thus, Jenkins can now access the code via its SSH key pair. However, the push does not work, since the deployment key only as read access rights. Since I do not want to register a separate Bitbucket account only for Jenkins, I thought it would be nice to add my own SSH key pair to the Jenkins machine which would result in: 
- id_rsa
- id_rsa.pub
- bastians_id_rsa 
- bastians_id_rsa.pub

However, how would I tell fastlane to use these alternative SSH credentials for git instead of the default ones?

**Comment by custompods** [comment]
The simplest solution is to start an ```ssh-agent``` and to add the private key(s) with ```ssh-add``` before calling ```fastlane```; or before calling the ```git``` action within ```fastlane``` :

```shell
chmod 600 /path/to/id_rsa
chmod 600 /path/to/bastians_id_rsa
eval $(ssh-agent -s)
ssh-add /path/to/id_rsa
ssh-add /path/to/bastians_id_rsa
```

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
