### ISSUE TITLE
Error installing on device app_store version

### ISSUE THREAD

**Issue by NateZ7** [fastlane/fastlane#11492]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After building a iOS ipa using app_store method I can't install on device

That's the error im getting -
[2018-01-09 15:19:01.709 ios-deploy[51315:4409617] [ !! ] Error 0xe8008016: The executable was signed with invalid entitlements. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)](url)

Checked my p.p and all valid.

### Environment
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

this is how I build my IPA -

```
lane :buildappstore do
build_app(
     workspace: "./appname.xcworkspace",
    scheme: "schemename",
    export_method: "app-store",
    export_xcargs: "allowProvisioningUpdates",
    export_options: {
      provisioningProfiles: {
        "com.appname.app" => "JenkinsAppStore",
        "com.appname.app.Widget" => "JenkinsAppStoreWidget",
        "com.appname.app.ShareExtension" => "JenkinsAppStoreShare"
      }
    }
  )
end
```

**Comment by NateZ7** [comment]
@fastlane-bot  It's full of sensitive info. I hope I can get an answer as it is right now. Thanks !

**Comment by KrauseFx** [comment]
Yah, that's the idea of App Store builds, you can't run them on devices. They have to be submitted to Apple for review

**Comment by NateZ7** [comment]
@KrauseFx  Thank you for the answer. I changed my jenkins flow accordingly. Closing
