### ISSUE TITLE
[screengrab] Adding Falcon as a ScreenshotStrategy

### ISSUE THREAD

**Issue by Macarse** [fastlane/fastlane#11497]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have been using fastlane+screengrab to take screenshots from my android app. I have been using `UiAutomatorScreenshotStrategy` and some of my screenshot tests are flaky. Some screenshots are taken before the whole ui is ready even though I am using Espresso onView and checks.

I haven't dig into how UiAutomator takes the screenshot but there is a race condition somewhere. Adding a small delay before taking the screenshots fixes all my issues.

While looking for other libraries to take screenshots I found https://github.com/jraska/Falcon
Falcon is a 400 lines dependency which takes screenshots in the main thread.

I am looking forward to add Falcon as a screengrab dependency and create a `ScreenshotStrategy`.

Would that be ok?

**Comment by Macarse** [comment]
ping?

**Comment by janpio** [comment]
Sounds like a great idea!

I also had to add delays to get my screenshots working but assumed it was my apps fault.

Looking forward to review a PR.

**Comment by Macarse** [comment]
@fastlane-bot updating doesn't solve the issue.
