### ISSUE TITLE
undefined method `login' for Spaceship::Tunes:Module

### ISSUE THREAD

**Issue by HarriesChen** [fastlane/fastlane#11495]
```
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/pilot/lib/pilot/manager.rb:22:in `login': [!] undefined method `login' for Spaceship::Tunes:Module (NoMethodError)
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/pilot/lib/pilot/manager.rb:15:in `start'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/pilot/lib/pilot/build_manager.rb:12:in `upload'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/fastlane/lib/fastlane/cli_tools_distributor.rb:86:in `take_off'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/gems/fastlane-2.75.0/bin/fastlane:20:in `<top (required)>'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/chenhao/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.59.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: 'GoWokClient',export_xcargs: '-allowProvisioningUpdates') # Build your app - more options available
    pilot(
      skip_waiting_for_build_processing: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.gowokgo.client" # The bundle identifier of your app
apple_id "hao@gowokgo.com" # Your Apple email address

team_id "6JDF54ADA9" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| faraday                   | 0.13.1       |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-01-09**
</details>
  
```

**Comment by Eeyore741** [comment]
+

**Comment by HarriesChen** [comment]
I can upload IPA using pilot 20mins ago. but When I update fastlane to the most new, got an error while uploading IPA

**Comment by Eeyore741** [comment]
Same here after update from 2.74.1 to 2.75.0.

**Comment by HarriesChen** [comment]
can I back to 2.74.1 ?

**Comment by andrey-lisovskiy** [comment]
same

**Comment by kurtheiligmann** [comment]
I see this when trying to download metadata also.

**Comment by rygood** [comment]
Same here after updating. :(

**Comment by rygood** [comment]
@HarriesChen you can go back by [installing a specific version of a gem. ](https://stackoverflow.com/questions/17026441/how-to-install-a-specific-version-of-a-ruby-gem)

**Comment by KrauseFx** [comment]
Ugh, so sorry to hear that. We'll try to resolve this ASAP

**Comment by KrauseFx** [comment]
I can reproduce, working on a fix now 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/11499, we hope to have a fix out within about 20 minutes 👍

**Comment by KrauseFx** [comment]
Just shipped the new release, thanks everybody for helping out. Please update and let us know if that fixes the issue 👍

**Comment by kurtheiligmann** [comment]
So far so good Thanks for the quick response!

**Comment by Eeyore741** [comment]
Works like a charm
