### ISSUE TITLE
Where is stderr?

### ISSUE THREAD

**Issue by strano666** [fastlane/fastlane#11498]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
With previous version of fastlane, i used to redirect `stderr` into a log file, via classical `2>`.
In the last version (2.75) stderr output is composed by the rocket animation.

Where can i find the `stderr`?

##### Complete output when running fastlane, including the stack trace and command used
```
$ fastlane produce app_name FB -u XXX@XXX.XX -a XX.XXXX.FB -i -q FB 2> log

[16:33:06]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+--------------------------+
|        Summary for produce 2.75.0         |
+----------------+--------------------------+
| username       | XXX@XXX.XX |
| app_identifier | XX.XXXX.FB      |
| skip_itc       | true                     |
| app_name       | FB                       |
| sku            | XXXXX              |
| platform       | ios                      |
| language       | English                  |
| skip_devcenter | false                    |
+----------------+--------------------------+

[16:33:09]: Creating new app 'FB' on the Apple Dev Center
[16:33:11]: Created app XXXXXX
[16:33:11]: Finished creating new app 'FB' on the Dev Center
```
The `log` file results in
`
[1G[⠋] 🚀 [1G[⠙] 🚀 [1G[⠹] 🚀 [1G[⠸] 🚀 [1G[⠼] 🚀 [1G[⠴] 🚀 [1G[⠦] 🚀 [1G[⠧] 🚀 [1G[⠇] 🚀 [1G[⠏] 🚀 [1G[⠋] 🚀 [1G[✔] 🚀 `

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | it_IT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.2        |
| slack-notifier        | 1.5.1        |
| CFPropertyList        | 2.3.5        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.2.8        |
| terminal-notifier     | 1.8.0        |
| terminal-table        | 1.8.0        |
| plist                 | 3.3.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.4        |
| tty-cursor            | 0.5.0        |
| tty-spinner           | 0.7.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| highline              | 1.7.8        |
| commander-fastlane    | 4.4.5        |
| unf_ext               | 0.0.7.4      |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| dotenv                | 2.2.1        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.4       |
| openssl               | 2.0.6        |
| io-console            | 0.4.6        |
| excon                 | 0.59.0       |
| faraday               | 0.13.1       |
| faraday_middleware    | 0.12.2       |
| little-plugger        | 1.1.4        |
| logging               | 2.2.2        |
| os                    | 0.9.6        |
| googleauth            | 0.6.2        |
| signet                | 0.8.1        |
| json                  | 2.1.0        |
| bundler               | 1.16.0       |
| unicode-display_width | 1.3.0        |
</details>

*generated on:* **2018-01-09**
</details>

**Comment by KrauseFx** [comment]
I don't think we changed anything. Does this have something to do with the loading indicator you think? Can you try setting the `FASTLANE_DISABLE_ANIMATION` variable to hide the loading indicator?

**Comment by strano666** [comment]
Yep. The problem was there!
With
`export FASTLANE_DISABLE_ANIMATION=1`
`stderr` is captured correctly.

**Comment by KrauseFx** [comment]
That's sub-optimal, I'm gonna look into this

**Comment by KrauseFx** [comment]
https://github.com/piotrmurach/tty-spinner/issues/28

**Comment by piotrmurach** [comment]
@strano666 Could you please update the tty-spinner either by running `gem install tty-spinner -v 0.8.0` or if you're using bundler `bundle update tty-spinner`? Any redirects, whether `stdin` or `stderr` should be clear of any spinner output and work as expected. Please let me know if this fixes your issue?

**Comment by strano666** [comment]
@piotrmurach updating tty-spinner everything works!

**Comment by piotrmurach** [comment]
@strano666 Great! I do appreciate that fastlane uses tty-spinner for its functionality and I can improve it to work even better.
