### ISSUE TITLE
deliver init bombing on some apps

### ISSUE THREAD

**Issue by mgamber** [fastlane/fastlane#1150]
Not all apps, but certain apps are causing "deliver init" to blow up and not grab the data on iTC. Here is an example, certain bits of data have been changed to protect privacy:

mymac:test tester$ deliver init -u username -e "Team Name Here" -f -a "com.myapp.app123"
[12:03:16]: Login to iTunes Connect (username)
[12:03:19]: Login successful

+-------------------+-----------------------------------------+
|                    deliver 1.7.0 Summary                    |
+-------------------+-----------------------------------------+
| username          | username               |
| app_identifier    | com.myapp.app123 |
| metadata_path     | ./metadata                              |
| screenshots_path  | ./screenshots                           |
| skip_screenshots  | false                                   |
| skip_metadata     | false                                   |
| force             | true                                    |
| submit_for_review | false                                   |
| automatic_release | false                                   |
| team_name         | Team Name Here                 |
+-------------------+-----------------------------------------+

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.0/lib/spaceship/tunes/application.rb:103:in `live_version': undefined method `count' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.0/lib/spaceship/tunes/application.rb:121:in `latest_version'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/lib/deliver/setup.rb:29:in `generate_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/lib/deliver/setup.rb:14:in `create_based_on_identifier'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/lib/deliver/setup.rb:5:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/lib/deliver/commands_generator.rb:65:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/lib/deliver/commands_generator.rb:107:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.7.0/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'

Everything had been working, as far as I could tell, perfectly until this morning sometime. And as I mentioned above, some apps still download from iTC just fine. Any ideas?

Thanks!

**Comment by KrauseFx** [comment]
Could you update spaceship using `sudo gem update spaceship` and see if that fixes the problem?

**Comment by mgamber** [comment]
Oh snap! I never realized spaceship was an updatable module, I always saw the updates come down the deliver and such. Just took your suggestion and it appears to be back to normal. I'll add it to my update script, thanks a bunch!

**Comment by KrauseFx** [comment]
Oh yeah, we need to push out a new fastlane release, to update the spaceship dependency :+1:
