### ISSUE TITLE
Deprecate pre-mono-gem releases

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#11508]
Pre mono gem times, @milch helped with a lot of the migration. We still have people being confused about this: https://twitter.com/julianjuko/status/950643214641332224

Would love to solve this once and for all. 

A few approaches I was thinking about: 
1) Write a script that yanks all the versions of all the individual gems
2) Push a new release for all those old gems, that replaces the code base with `Hey pls use fastlane kthxbye`

It's been a year now, and the old versions just won't work anymore

e.g. https://rubygems.org/gems/cert

**Comment by KrauseFx** [comment]
Maybe yanking might not be a good idea, as it would remotely break `bundle update`. Seems like it's better to just replace the code with a big `raise`

**Comment by milch** [comment]
How about this timeline: 

- Update all gems to show an error message at the beginning and end. Set a date when the gems will turn non-functional (e.g. +1 month from now)
- On that date, replace the executable with `raise "Please use fastlane instead, this will be removed on x date"` (e.g. +1 month again)
- Yank the gems at that time
