### ISSUE TITLE
Add internal tester

### ISSUE THREAD

**Issue by andrey-lisovskiy** [fastlane/fastlane#11513]
Hi, I have new app and want to add **_internal_** testers to it.
Tried:
_fastlane pilot add -e XXXX -u XXXX -a XXXX --distribute_external=false_

but **fastlane** keeps throwing an error:

_You must provide 1 or more groups (with the `:groups` option)_

How can I achieve this?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
platform :ios do
    lane :update_app do
        update_app_identifier(xcodeproj: "XXXX.xcodeproj", plist_path: "XXXX/Universal-Info.plist")
        update_info_plist(xcodeproj: "XXXX.xcodeproj", plist_path: "XXXX/Universal-Info.plist", display_name: "XXXX")
        update_info_plist(xcodeproj: "XXXX.xcodeproj", plist_path: "XXXX/Universal-Info.plist", block: lambda { |plist|
        urlScheme = plist["CFBundleURLTypes"].find{|scheme| scheme["CFBundleURLName"] == "co.XXXX"}
        urlScheme[:CFBundleURLSchemes] = ["XXXX"];
        plist[:CFBundleShortVersionString] = "3.0.15";
        plist[:CFBundleVersion] = "8" })
    end

    lane :build do
        update_app
        produce(skip_itc: "false", # Skip the creation of the app on iTunes Connect
                username: "XXXX",
                app_name: "XXXX",
                language: "English",
                app_version: "3.0.15",
                sku: "XXXX",
                team_name: "XXXX",
                enable_services: {
                    push_notification: "on",
                })
        pem(force: "false")
        match(type: "appstore")
        get_certificates
        get_provisioning_profile
        update_project_provisioning(xcodeproj: "XXXX.xcodeproj",
                                    profile: "./AppStore_XXXX.mobileprovision",
                                    target_filter: ".*Universal.*",
                                    build_configuration: "AppStore")
        gym(workspace: "XXXX.xcworkspace",
            scheme: "Universal",
            clean: true,
            silent: true,
            output_name: "XXXX",
            xcargs: {
                :PROVISIONING_PROFILE_SPECIFIER => "match AppStore com.dev.XXXX"
            },
            export_method: "app-store")
        sh "cd .. && fastlane pilot import"
        pilot(skip_submission: true, skip_waiting_for_build_processing: false, distribute_external: false)
    end

    lane :reset_git do
        reset_git_repo(force: true) 
    end

    lane :piloting do
        sh "cd .. && fastlane pilot import"
        pilot(skip_submission: true, 
        	skip_waiting_for_build_processing: false, 
        	distribute_external: true, 
        	beta_app_feedback_email: "email@example.org",
        	distribute_external: false,
        	beta_app_description: "QA Version app - For external testing") 
    end

    before_all do
    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXXX"
apple_id "XXXX"
team_id "XXXX"
itc_team_id "XXXX"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                | Version | Update-Status |
| ------------------------------------- | ------- | ------------- |
| fastlane-plugin-get_product_bundle_id | 0.1.2   | ✅ Up-To-Date  |
| fastlane-plugin-get_product_bundle_id | 0.1.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| slack-notifier                        | 1.5.1        |
| CFPropertyList                        | 2.3.6        |
| claide                                | 1.0.2        |
| colored2                              | 3.1.2        |
| nanaimo                               | 0.2.3        |
| xcodeproj                             | 1.5.4        |
| rouge                                 | 1.11.1       |
| xcpretty                              | 0.2.6        |
| terminal-notifier                     | 1.8.0        |
| unicode-display_width                 | 1.1.3        |
| terminal-table                        | 1.7.3        |
| plist                                 | 3.4.0        |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.5.2        |
| multipart-post                        | 2.0.0        |
| word_wrap                             | 1.0.0        |
| tty-screen                            | 0.6.3        |
| tty-cursor                            | 0.5.0        |
| tty-spinner                           | 0.7.0        |
| babosa                                | 1.0.2        |
| colored                               | 1.2          |
| highline                              | 1.7.10       |
| commander-fastlane                    | 4.4.5        |
| excon                                 | 0.60.0       |
| faraday                               | 0.13.1       |
| unf_ext                               | 0.0.7.4      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20170404 |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| fastimage                             | 2.1.1        |
| gh_inspector                          | 1.0.3        |
| json                                  | 1.8.1        |
| mini_magick                           | 4.5.1        |
| multi_json                            | 1.12.2       |
| multi_xml                             | 0.6.0        |
| rubyzip                               | 1.2.1        |
| security                              | 0.1.3        |
| xcpretty-travis-formatter             | 0.0.4        |
| dotenv                                | 2.2.1        |
| bundler                               | 1.14.6       |
| faraday_middleware                    | 0.11.0.1     |
| uber                                  | 0.1.0        |
| declarative                           | 0.0.10       |
| declarative-option                    | 0.1.0        |
| representable                         | 3.0.4        |
| retriable                             | 3.1.1        |
| mime-types-data                       | 3.2016.0521  |
| mime-types                            | 3.1          |
| little-plugger                        | 1.1.4        |
| logging                               | 2.2.2        |
| jwt                                   | 1.5.6        |
| memoist                               | 0.16.0       |
| os                                    | 0.9.6        |
| signet                                | 0.7.3        |
| googleauth                            | 0.5.1        |
| httpclient                            | 2.8.3        |
| google-api-client                     | 0.13.6       |
| libxml-ruby                           | 3.0.0        |
| fastlane-plugin-get_product_bundle_id | 0.1.2        |
</details>

*generated on:* **2018-01-10**
</details>

**Comment by andrey-lisovskiy** [comment]
@KrauseFx is it possible at all?

**Comment by scorpion35** [comment]
@andrey-lisovskiy Not sure with fastlane, but you can do it with Spaceship. Check my answer here - https://github.com/fastlane/fastlane/issues/11453. 

If you want to add new user, using Spaceship,
```ruby
Spaceship::TestFlight::Tester::create_app_level_tester(app_id: 1235553, first_name: "foo", last_name: "bar", email: "foo.bar@foobar.com")
```

**Comment by andrey-lisovskiy** [comment]
@scorpion35 Thanks for response, but this adds **external** user, not **internal** (iTunes Connect user).

**Comment by scorpion35** [comment]
@andrey-lisovskiy Fixed the code above! Hopefully it works for you.

`Spaceship::TestFlight::Tester::crea**` -> `Spaceship::TestFlight::Tester::Internal::crea***`

**Comment by andrey-lisovskiy** [comment]
@scorpion35 I am receiving error: `uninitialized constant Spaceship::TestFlight::Tester::Internal`

**Comment by Alarson93** [comment]
Any updates on this? I would also like to add internal testers via my Fastlane script.
