### ISSUE TITLE
Swift: Using getProvisioningProfile with adhoc = true creates conflict

### ISSUE THREAD

**Issue by fwal** [fastlane/fastlane#11519]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using `getProvisioningProfile` with `adhoc: true` doesn't work.
Tried adding `development: false` as well but didn't help

##### Complete output when running fastlane, including the stack trace and command used

[✔] 🚀
[15:08:31]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[15:08:31]: FastlaneSwiftRunner project is up-to-date
[15:08:31]: $ xcodebuild -list -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:08:32]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:08:33]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /.../Logs/gym/App-FastlaneRunner.log | xcpretty
[15:08:37]: $ ./fastlane/FastlaneRunner lane foo > /dev/null
[15:08:37]: --------------------------------------
[15:08:37]: --- Step: get_provisioning_profile ---
[15:08:37]: --------------------------------------
[15:08:37]: Error resolving conflict between options: 'adhoc' and 'development'
[15:08:37]: You passed invalid parameters to 'get_provisioning_profile'.
[15:08:37]: Check out the error below and available options by running `fastlane action get_provisioning_profile`
[15:08:38]: You can't enable both :development and :adhoc

+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 💥   | get_provisioning_profile | 0           |
+------+--------------------------+-------------+

[15:08:38]: fastlane finished with errors

[!] You can't enable both :development and :adhoc

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// Customize this file, documentation can be found here:
// https://docs.fastlane.tools/
// All available actions: https://docs.fastlane.tools/actions
// can also be listed using the `fastlane actions` command
import Foundation

class Fastfile: LaneFile {
    let fastlaneVersion = "2.73.0"
    
    func afterAll() {
        cleanBuildArtifacts()
    }

    func fooLane() {
        getProvisioningProfile(
            adhoc: true,
            development: false,
            force: true,
            appIdentifier: appIdentifier,
            username: appleID,
            provisioningName: "App Ad Hoc"
        )
    }

}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.12.5       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.11.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.16.2       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.5.6        |
| danger-plugin-api         | 1.0.0        |
| danger-xcode_summary      | 0.4.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.0       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| ffi                       | 1.9.18       |
| mustache                  | 0.99.8       |
| redcarpet                 | 3.4.0        |
| rb-fsevent                | 0.10.2       |
| rb-inotify                | 0.9.10       |
| sass-listen               | 4.0.0        |
| sass                      | 3.5.5        |
| sqlite3                   | 1.3.13       |
| liferaft                  | 0.0.6        |
| xcinvoke                  | 0.3.0        |
| jazzy                     | 0.9.1        |
| xcode-install             | 2.3.1        |
| xcpretty-json-formatter   | 0.1.0        |
</details>

*generated on:* **2018-01-10**
</details>

**Comment by antonino-u** [comment]
I have the same issue, not sure why this is happening.

**Comment by ianalbertruelala** [comment]
I rewrote how the args array is built in `Fastlane.getProvisioningProfile` and it fixed the issue for me. Basically, I'm only inserting RubyCommand.Arguments for non-default arguments.

```
    var args: [RubyCommand.Argument] = [
        RubyCommand.Argument(name: "app_identifier", value: appIdentifier),
        RubyCommand.Argument(name: "username", value: username),
        RubyCommand.Argument(name: "output_path", value: outputPath),
        RubyCommand.Argument(name: "platform", value: platform),
    ]
    if adhoc { args.append(RubyCommand.Argument(name: "adhoc", value: adhoc)) }
    if development { args.append(RubyCommand.Argument(name: "development", value: development)) }
    if skipInstall { args.append(RubyCommand.Argument(name: "skip_install", value: skipInstall)) }
    if force { args.append(RubyCommand.Argument(name: "force", value: force)) }
    ...
    let command = RubyCommand(commandID: "", methodName: "get_provisioning_profile", className: nil, args: args)
```
