### ISSUE TITLE
Invoke Snapshot ReportsGenerator without XCode Project

### ISSUE THREAD

**Issue by akamud** [fastlane/fastlane#11527]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I understand `Snapshot` uses XCode UI Tests at the moment, but I'm not writing my tests with this (using Xamarin UITest atm), so I generated my screenshots myself and put them in the `./screenshots` folder, and now I would like to just call the `ReportGenerator` to generate a nice HTML with the screenshots, just so I don't have to rewrite all of this templating code and HTML.

I searched on GitHub and found a recommendation to do something like this:

```ruby
    Dir.chdir("..") do
        require 'snapshot'

        Snapshot::ReportsGenerator.new.generate
    end
```

the problem was that the config was null, so I added this just before calling `generate`:

```ruby
Snapshot.config = FastlaneCore::Configuration.create(Snapshot::Options.available_options, {})
```

I then hit a restriction:

```
[16:42:49]: Couldn't automatically detect the project file, please provide a path:
```

which doesn't make sense in a Xamarin environment, all the tests are in a `.csproj`.

I'm not a Ruby programmer, so I would like to understand my possibilites:
* Am I doing this the right way?
* Is there any way to force not having a `.xcodeproj`? Didn't look like it was possible from looking at [this](https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/detect_values.rb#L17).
* Would it be possible to make this not required or have another way of just generating the reports considering the screenshots are there?

##### Output:
```
[16:42:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:42:48]: You require a gem, if this is a third party gem, please use `fastlane_require 'snapshot'` to ensure the gem is installed locally
[16:42:49]: ----------------------------------------
[16:42:49]: --- Step: Verifying fastlane version ---
[16:42:49]: ----------------------------------------
[16:42:49]: Your fastlane version 2.75.1 matches the minimum requirement of 2.75.1  ✅
[16:42:49]: Driving the lane 'dev' 🚀
[16:42:49]: Successfully loaded '/Users/mahmoud/Documents/Repositorios/MyApp/fastlane/Snapfile' 📄

+------------------+---------------------------+
|      Detected Values from './Snapfile'       |
+------------------+---------------------------+
| devices          | ["iPhone SE", "iPhone 6"] |
| languages        | ["en-US"]                 |
| output_directory | ./screenshots             |
+------------------+---------------------------+

[16:42:49]: Couldn't automatically detect the project file, please provide a path:
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.75.1"
 
lane :dev do
    Dir.chdir("..") do
        require 'snapshot'

        Snapshot.config = FastlaneCore::Configuration.create(Snapshot::Options.available_options, {})
        Snapshot::ReportsGenerator.new.generate
    end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-10**
</details>

**Comment by akamud** [comment]
Any word on this?

**Comment by taquitos** [comment]
Yeah, unfortunately we don't support Xamarin. 
Xamarin has done some work to integrate fastlane into their IDE, but I don't think they've done anything for snapshot to work there. 

It would be amazing to have support for Xamarin, but unfortunately we'll have to wait for them to build a plugin to support it.

**Comment by akamud** [comment]
I understand that part, in fact, in this scenario Xamarin is not really relevant, it could be anything else that is not a XCode UI project.

What I'm trying to validate is if there is a way to bypass the XCode project requirement somehow, because from my very basic understanding of Ruby, I couldn't find it.

**Comment by akamud** [comment]
So? Feedback on this?

**Comment by KrauseFx** [comment]
Sorry, but for now we do require an Xcode project. If you find a way to get it to work, that's great, and feel free to also submit a PR to the docs or fastlane code base to explain how it works, but we as the core team can't spend time on building support for this right now. Again, sorry, I know it's not the answer you're looking for...

**Comment by akamud** [comment]
Thanks for the feedback, for now, just knowing that XCode is needed is enough for non-Ruby developers like me.
