### ISSUE TITLE
Output to console when using Fastfile.swift

### ISSUE THREAD

**Issue by onevcat** [fastlane/fastlane#11537]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In Ruby version, we could use [`puts` action](https://docs.fastlane.tools/actions/puts/) to send some text to console. However, this action is not mapped to Swift yet. Is there a way to print some log when using Fastlane Swift version?

(I tried Swift `print` method. However, it seems that the text is eaten by xcpretty so the log does not show in my terminal.)

Thanks!

**Comment by taquitos** [comment]
Great suggestion! The reason why this action hasn't been added to `Fastlane.swift` is because the `PutsAction` has no `def self.available_options` options. 
If you were to add an option, say `message` option, then print that out if it was passed in, this action would get auto-generated in `Fastlane.swift`

**Comment by antonino-u** [comment]
So is there a solution to printing things out? This totally stops me from moving to swift :( (I've tried using the Logger to no avail.

**Comment by taquitos** [comment]
@thii has a PR up: https://github.com/fastlane/fastlane/pull/11625
and that will do it once they address the review comment 🚀

**Comment by joshdholtz** [comment]
This should be fixed now as that PR was merged 😊
