### ISSUE TITLE
Updating to last version breaks Enumerable

### ISSUE THREAD

**Issue by ahmgeek** [fastlane/fastlane#11539]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Updating to the last version breaks the specs and parts of the code **`jRuby` implementation only** with this error:
```
      NameError:
        uninitialized constant Enumerable::Enumerator::Lazy
```

the code is not that important, but here's how it's going
```RUBY
collection.find(criteria.to_h).limit(options.fetch(:limit, 0)).lazy.map do |doc|
  # stuff
end
```

On jruby,  `CFPropertyList`, in the gem dependencies seems to break enumerable.
I forked `CFPropertyList` [CHECK THIS PLEASE](https://github.com/ahmgeek/CFPropertyList/commit/fd3b3d70bedbec2bb29a2c62bee0cb9985ea43cc#diff-b16f6a0127971a7fd3aaed3ae7b87272L91)
and removed the code from in the PR, and it ran smoothly.
 
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | UNKNOWN                                         |
| Ruby                        | 2.3.3                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.13.1                              |
| Installation Source         | ~/.rvm/gems/jruby-9.1.10.0@project/bin/fastlane |
| Host                        | Unknown  ()                                     |
| Ruby Lib Dir                | ~/.rvm/rubies/jruby-9.1.10.0/lib                |
| OpenSSL Version             | JRuby-OpenSSL 0.9.20                            |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.75.1  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                            | Version      |
| ------------------------------ | ------------ |
| did_you_mean                   | 1.0.1        |
| executable-hooks               | 1.3.2        |
| bundler-unload                 | 1.0.2        |
| rubygems-bundler               | 1.4.4        |
| bundler                        | 1.16.1       |
| rake                           | 12.2.1       |
| CFPropertyList                 | 2.3.6        |
| i18n                           | 0.8.6        |
| minitest                       | 5.11.1       |
| thread_safe                    | 0.3.6        |
| tzinfo                         | 1.2.4        |
| activesupport                  | 4.2.8        |
| builder                        | 3.2.3        |
| erubis                         | 2.7.0        |
| nokogiri                       | 1.8.1        |
| rails-deprecated_sanitizer     | 1.0.3        |
| rails-dom-testing              | 1.0.9        |
| crass                          | 1.0.3        |
| loofah                         | 2.1.1        |
| rails-html-sanitizer           | 1.0.3        |
| actionview                     | 4.2.8        |
| rack                           | 1.6.8        |
| rack-test                      | 0.6.3        |
| actionpack                     | 4.2.8        |
| globalid                       | 0.4.1        |
| activejob                      | 4.2.8        |
| mini_mime                      | 1.0.0        |
| mail                           | 2.7.0        |
| actionmailer                   | 4.2.8        |
| activemodel                    | 4.2.8        |
| arel                           | 6.0.4        |
| activerecord                   | 4.2.8        |
| activerecord-jdbc-adapter      | 1.3.23       |
| jdbc-mysql                     | 5.1.42       |
| activerecord-jdbcmysql-adapter | 1.3.23       |
| public_suffix                  | 2.0.5        |
| addressable                    | 2.5.1        |
| thor                           | 0.19.4       |
| approvals                      | 0.0.22       |
| ast                            | 2.3.0        |
| babosa                         | 1.0.2        |
| backports                      | 3.8.0        |
| bson                           | 4.2.2        |
| bundler-audit                  | 0.5.0        |
| highline                       | 1.7.8        |
| net-ssh                        | 4.1.0        |
| net-scp                        | 1.2.1        |
| net-sftp                       | 2.1.2        |
| net-ssh-gateway                | 2.0.0        |
| capistrano                     | 2.15.9       |
| capistrano-ext                 | 1.2.1        |
| claide                         | 1.0.2        |
| coderay                        | 1.1.1        |
| colored                        | 1.2          |
| colored2                       | 3.1.2        |
| commander-fastlane             | 4.4.5        |
| concurrent-ruby                | 1.0.5        |
| hashie                         | 3.5.5        |
| confstruct                     | 1.0.2        |
| connection_pool                | 2.2.1        |
| i18n_data                      | 0.7.0        |
| money                          | 6.9.0        |
| sixarm_ruby_unaccent           | 1.1.2        |
| unicode_utils                  | 1.4.0        |
| countries                      | 2.0.8        |
| safe_yaml                      | 1.0.4        |
| crack                          | 0.4.3        |
| data_transfer_object           | 1.1.0        |
| declarative                    | 0.0.10       |
| declarative-option             | 0.1.0        |
| diff-lcs                       | 1.3          |
| unf                            | 0.1.4        |
| domain_name                    | 0.5.20170404 |
| dotenv                         | 2.2.1        |
| dry-configurable               | 0.7.0        |
| dry-container                  | 0.6.0        |
| dry-core                       | 0.3.3        |
| dry-equalizer                  | 0.2.0        |
| dry-initializer                | 2.3.0        |
| dry-logic                      | 0.4.1        |
| inflecto                       | 0.0.2        |
| dry-types                      | 0.11.1       |
| ice_nine                       | 0.11.2       |
| dry-struct                     | 0.3.1        |
| dry-validation                 | 0.11.0       |
| error_handler                  | 0.2.0        |
| excon                          | 0.60.0       |
| factory_bot                    | 4.8.2        |
| multipart-post                 | 2.0.0        |
| faraday                        | 0.13.1       |
| http-cookie                    | 1.0.3        |
| faraday-cookie_jar             | 0.0.6        |
| faraday_middleware             | 0.12.2       |
| fastercsv                      | 1.5.5        |
| fastimage                      | 2.1.1        |
| gh_inspector                   | 1.0.3        |
| jwt                            | 2.1.0        |
| little-plugger                 | 1.1.4        |
| multi_json                     | 1.12.1       |
| logging                        | 2.2.2        |
| memoist                        | 0.16.0       |
| os                             | 0.9.6        |
| signet                         | 0.8.1        |
| googleauth                     | 0.6.2        |
| httpclient                     | 2.8.3        |
| mime-types-data                | 3.2016.0521  |
| mime-types                     | 3.1          |
| uber                           | 0.1.0        |
| representable                  | 3.0.4        |
| retriable                      | 3.1.1        |
| google-api-client              | 0.13.6       |
| json                           | 2.1.0        |
| mini_magick                    | 4.5.1        |
| multi_xml                      | 0.6.0        |
| plist                          | 3.4.0        |
| rubyzip                        | 1.2.1        |
| security                       | 0.1.3        |
| slack-notifier                 | 1.5.1        |
| terminal-notifier              | 1.8.0        |
| unicode-display_width          | 1.3.0        |
| terminal-table                 | 1.8.0        |
| tty-screen                     | 0.6.4        |
| tty-cursor                     | 0.5.0        |
| tty-spinner                    | 0.8.0        |
| word_wrap                      | 1.0.0        |
| nanaimo                        | 0.2.3        |
| xcodeproj                      | 1.5.4        |
| rouge                          | 2.0.7        |
| xcpretty                       | 0.2.8        |
| xcpretty-travis-formatter      | 1.0.0        |
| ffi                            | 1.9.18       |
| rspec-support                  | 3.6.0        |
| rspec-core                     | 3.6.0        |
| ruby-progressbar               | 1.9.0        |
| fuubar                         | 2.2.0        |
| gem_config                     | 0.3.1        |
| gherkin                        | 4.1.3        |
| hashdiff                       | 0.3.4        |
| health_monitor                 | 0.6.0        |
| jrjackson                      | 0.4.2        |
| jruby-rack                     | 1.1.20       |
| jsonapi-parser                 | 0.1.1        |
| jsonapi-deserializable         | 0.1.1        |
| jsonapi-renderer               | 0.1.3        |
| jsonapi-serializable           | 0.2.1        |
| jsonapi-rb                     | 0.2.1        |
| march_hare                     | 2.22.0       |
| maxminddb                      | 0.1.13       |
| msgpack                        | 1.0.3        |
| receptacle                     | 0.3.1        |
| messages                       | 4.2.4        |
| method_source                  | 0.8.2        |
| mongo                          | 2.4.3        |
| net-http-persistent            | 2.9.4        |
| newrelic_rpm                   | 4.7.1.340    |
| notifier                       | 1.0.8        |
| parallel                       | 1.12.0       |
| parser                         | 2.4.0.0      |
| powerpack                      | 0.1.1        |
| slop                           | 3.6.0        |
| spoon                          | 0.0.6        |
| pry                            | 0.10.4       |
| rack-protection                | 1.5.3        |
| racksh                         | 1.0.0        |
| rainbow                        | 2.2.2        |
| redis                          | 3.3.3        |
| redis-namespace                | 1.5.3        |
| slyphon-log4j                  | 1.2.15       |
| slyphon-zookeeper_jar          | 3.3.5        |
| zookeeper                      | 1.4.11       |
| zk                             | 1.9.6        |
| repository-lock                | 3.0.0        |
| rspec-expectations             | 3.6.0        |
| rspec-mocks                    | 3.6.0        |
| rspec                          | 3.6.0        |
| sidekiq                        | 5.0.4        |
| rspec-sidekiq                  | 3.0.3        |
| rvm-capistrano                 | 1.5.6        |
| rt_deploy                      | 1.16.0       |
| rubocop                        | 0.51.0       |
| rt_rubocop_defaults            | 1.0.0        |
| rubocop-rspec                  | 1.19.0       |
| rubocop_runner                 | 2.0.0        |
| sequel                         | 4.48.0       |
| service                        | 0.2.0        |
| sidekiq-pro                    | 3.5.1        |
| sidekiq-ent                    | 1.6.0        |
| tilt                           | 1.4.1        |
| sinatra                        | 1.4.5        |
| sinatra-advanced-routes        | 0.5.3        |
| sinatra-contrib                | 1.4.7        |
| sinatra-param                  | 1.4.0        |
| vcr                            | 3.0.3        |
| tidyvcr                        | 0.1.2        |
| timecop                        | 0.8.1        |
| transaction_flow               | 0.6.0        |
| trinidad_jars                  | 1.4.2        |
| trinidad                       | 1.4.6        |
| trinidad_init_services         | 1.3.1        |
| turnip                         | 3.0.0        |
| webmock                        | 3.0.1        |
</details>

</details>

**Comment by janpio** [comment]
What OS are you working on?
Did this work before?
If so, what changed besides updating fastlane? 
Anything local?
Do you know what changed inside fastlane? Dependencies or code?

**Comment by ahmgeek** [comment]
Hey @janpio, here's the steps:

from inside on the project  `bundle update fastlane --conservative`
then `git diff --unified=0`

<details><summary>Click to toggle contents of `diff`</summary>

```
diff --git a/Gemfile.lock b/Gemfile.lock
index a752616..fe7aa2e 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -29 +29 @@ GEM
-    CFPropertyList (2.3.5)
+    CFPropertyList (2.3.6)
@@ -119 +119 @@ GEM
-    declarative (0.0.9)
+    declarative (0.0.10)
@@ -163 +163 @@ GEM
-    excon (0.57.1)
+    excon (0.60.0)
@@ -171 +171 @@ GEM
-    faraday_middleware (0.11.0.1)
+    faraday_middleware (0.12.2)
@@ -174,2 +174,2 @@ GEM
-    fastimage (2.1.0)
-    fastlane (2.48.0)
+    fastimage (2.1.1)
+    fastlane (2.75.1)
@@ -189 +189 @@ GEM
-      google-api-client (>= 0.12.0, < 0.13.0)
+      google-api-client (>= 0.13.1, < 0.14.0)
@@ -196,0 +197 @@ GEM
+      public_suffix (~> 2.0.0)
@@ -202 +203,2 @@ GEM
-      tty-screen (~> 0.5.0)
+      tty-screen (>= 0.6.3, < 1.0.0)
+      tty-spinner (>= 0.7.0, < 1.0.0)
@@ -204 +206 @@ GEM
-      xcodeproj (>= 1.4.4, < 2.0.0)
+      xcodeproj (>= 1.5.2, < 2.0.0)
@@ -217 +219 @@ GEM
-    google-api-client (0.12.0)
+    google-api-client (0.13.6)
@@ -224 +226 @@ GEM
-    googleauth (0.5.3)
+    googleauth (0.6.2)
@@ -226 +228 @@ GEM
-      jwt (~> 1.4)
+      jwt (>= 1.4, < 3.0)
@@ -257 +259 @@ GEM
-    jwt (1.5.6)
+    jwt (2.1.0)
@@ -319 +321 @@ GEM
-    plist (3.3.0)
+    plist (3.4.0)
@@ -369 +371 @@ GEM
-    retriable (3.0.2)
+    retriable (3.1.1)
@@ -421 +423 @@ GEM
-    signet (0.7.3)
+    signet (0.8.1)
@@ -424 +426 @@ GEM
-      jwt (~> 1.5)
+      jwt (>= 1.5, < 3.0)
@@ -467 +469,4 @@ GEM
-    tty-screen (0.5.0)
+    tty-cursor (0.5.0)
+    tty-screen (0.6.4)
+    tty-spinner (0.8.0)
+      tty-cursor (>= 0.5.0)
@@ -486 +491 @@ GEM
-    xcodeproj (1.5.1)
+    xcodeproj (1.5.4)
@@ -493 +498 @@ GEM
-    xcpretty-travis-formatter (0.0.4)
+    xcpretty-travis-formatter (1.0.0)

```
</details>
then `rspec` and the error in my issue pops up.


> What OS are you working on?
-  you can find details in the issue env but here's it too
```
System Software Overview:
  System Version:	macOS 10.13.2 (17C88)  High Seirra
  Kernel Version:	Darwin 17.3.0
```
That failed on my co-worker linux/ubuntu/jRuby machine too.

> Did this work before?
I tried to `bundle update` with `--major` before but really I don't know which version exactly it breaks.

> If so, what changed besides updating fastlane?
I added above the `diff`

> Anything local?
`jRuby` ? I am not sure what you mean by this.

> Do you know what changed inside fastlane? Dependencies or code?
well, that's a high jump in versions:
```
-    fastlane (2.48.0)

+    fastlane (2.75.1)
```
so lot's of changes..

**Comment by janpio** [comment]
> you can find details in the issue env but here's it too

Nah, there it says "UNKNOWN" ;)

>> Anything local?
> jRuby ? I am not sure what you mean by this.

Yes, if you also changed something in your environment.

My current understanding is that newer fastlane uses a newer dependency that doesn't work on your jRuby environment, agree?

**Comment by ahmgeek** [comment]
ok, maybe my issue was a bit vague, so does fastlane works as expected with jRuby, can you please
just try to bundle install and run tests with jRuby?
bundle install has issued with gems which doesn't work with jRuby.
and I am not sure if tests will pass too.

**Comment by ahmgeek** [comment]
@janpio @KrauseFx any updates about this 😭  ?

**Comment by janpio** [comment]
Fastlane is not tested with jRuby, so no idea. (Also: I personally don't know anything about it)
