### ISSUE TITLE
Code signing error due to automatic signing

### ISSUE THREAD

**Issue by reshadf** [fastlane/fastlane#11543]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when the CI runs the fastlane beta lane it comes up with the following error:

```
[14:28:34]: ▸ === BUILD TARGET appTargetName OF PROJECT ProjectName WITH CONFIGURATION Release ===
[14:28:34]: ▸ Check dependencies
[14:28:34]: ▸ Code Signing Error: No profiles for 'com.app.name' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.app.name'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[14:28:34]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
```

However, I already do pass that argument along. This is my whole lane

```
lane :beta do
  match(type: "appstore")

  # build your iOS app
  gym(
    scheme: "SchemeName",
    export_method: "app-store",
    clean: true,
    export_xcargs: "-allowProvisioningUpdates"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end
```

**Comment by saeros** [comment]
Same here (see #11514)

**Comment by westrada** [comment]
You have to use the parameter `xcargs` instead of `export_xcargs`. But for CI server is better having the code manual signing because using `-allowProvisioningUpdates` requires a developer account to have been added in Xcode's Accounts preference pane and it doesn't work when you run in a CI server.
If you use XCode 9 you have to choose a provisioning profile for each target https://docs.fastlane.tools/codesigning/xcode-project/

**Comment by saeros** [comment]
Hello @westrada, as there been a breaking change lately in Xcode or fastlane regarding this? Because I've been using Xcode 9 since it was out and never had to to do this. It only started failing about a 10 days ago.

**Comment by reshadf** [comment]
Well then is this a breaking change or something because it first always worked and then we had to add export_xcargs and now suddenly its xcargs would be nice to see some info if breaking changes like these happen.

**Comment by westrada** [comment]
I really don’t know because I started using Fastlane + Xcode9 recently. For Xcode 8 it was working fine previously. Does it work fine for you now? If not, you can add error details here if there’s something that I can help you

**Comment by joshdholtz** [comment]
@reshadf Heyyyy 👋  Were you able to figure out this issue on your end?

**Comment by reshadf** [comment]
I ended up using Match because the codesigning stuff made me go crazy @joshdholtz

**Comment by joshdholtz** [comment]
@reshadf Cool cool, glad you got it working! And sorry about slow response. Will be improving on that 😊
