### ISSUE TITLE
Get latest `all_build_train_numbers`

### ISSUE THREAD

**Issue by pablog** [fastlane/fastlane#11544]
I have a script that fetches the latest version number uploaded to Itunes Connect.

It does this (only the relevant lines of the script):

```
Spaceship::Tunes.login
app = Spaceship::Tunes::Application.find(params[:bundle_id])
app.all_build_train_numbers.max
```

This has a big problem, which is that [`all_build_train_numbers`](http://www.rubydoc.info/gems/spaceship/0.31.1/Spaceship%2FTunes%2FApplication:all_build_train_numbers) is just an array of strings, so `max` considers `1.1.9` to be higher than `1.1.10`.

To fix that I ended up doing:

```
app.all_build_train_numbers
    .map{ |v| v.split(".").map{ |i| i.to_i } }        # ["1.2.1", "1.2.2"] => [[1,2,1], [1,2,2]]
    .max.join(".")        # Comparator of arrays checks values from left to right
```

Which doesn't look like a clean workaround. Also, I'd like this to support [semver](https://semver.org/).

I'd like to know if there's a proper way to do this using provided features by fastlane, and also any other suggestion for this.

**Comment by milch** [comment]
@pablog If you do `require 'rubygems/version'` you can wrap it in `Gem::Version`: 

![screen shot 2018-01-13 at 13 23 22](https://user-images.githubusercontent.com/279407/34906036-029b7118-f865-11e7-93f0-55ab624b73bc.png)

`fastlane` also has a thin wrapper around `Gem::Version` with `FastlaneCore::TagVersion`. You can use that instead if you `require 'fastlane_core/tag_version'`

**Comment by pablog** [comment]
Perfect @milch this is very useful! I'll do that!
