### ISSUE TITLE
register_devices documentation links to an unsafe website

### ISSUE THREAD

**Issue by zilppuri** [fastlane/fastlane#11540]
The documentation for register_devices (https://docs.fastlane.tools/actions/register_devices/) points to an website: https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip

However, this websites certificate has been expired.

Is there are reason for not providing an example a standard UDID export .txt file syntax within the documentation without linking to external sources?

**Comment by janpio** [comment]
Seems this is/was an official site from Apple, which is also available under the "safe" URL: http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip

I kind of assume that this isn't part of the documentation as the system fastlane is using for that (generate it from the action code itself automatically) is not very well equipped to handle such situations.

I create a PR to at least use that http only link that doesn't generate a warning.

**Comment by KrauseFx** [comment]
Thanks everyone 👍
