### ISSUE TITLE
[proposal] Create a Gemfile for the user when running `fastlane init`

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#11546]
Users using system Ruby without a `Gemfile` cause a lot of our incoming support tickets.

@milch has some good opinions (some would even say the best opinions)

Currently we support the following installation methods (the % is the number of executions done by each installation method)

### Using a `Gemfile` (49%)

Currently we classify this as a more advanced setup, and don't recommend this out of the box

### `gem install fastlane` (30%)

This doesn't use a proper dependency manager, causing lots of setups to break

### `brew cask install fastlane` (17%)

This is great, however requires `homebrew` to be installed, which not all iOS developers have

### `download.fastlane.tools` (5%)

This is basically `homebrew`, but without homebrew, and a few extra manual steps

### Using the Fabric Mac app (0.1%)

This is used by less than 0.1% of the user base

## Main proposal

The idea is to simplify the installation methods and make it easier for the user. As during onboarding most people will run `fastlane init`, the proposal is to also create a `Gemfile` for the user, so they can check it into version control together with the `Fastfile`.

This requires a few things:
1) During `fastlane init`, check if a `Gemfile` already exists, if not create one, if yes, append `fastlane` to it and verify `rubygems.org` is the defined source
2) `fastlane update_fastlane` should use `bundle update fastlane` (which I think it might already do)
3) Automatically run `Bundler.load` (or similar) on _fastlane_ if there is a `Gemfile`

## Secondary proposal

Secondly, we should think about dropping support for hardly used installation methods in the future. In particular, the Fabric Mac app, and `download.fastlane.tools`. Both use basically the `homebrew` zip file, so it's not a big deal to maintain. But at least we probably don't want to mention them in the docs. We're gonna leave it around for a bit, and see if they cause problems in the future.

`gem install fastlane` is "supported" by default, but we're just not gonna mention it in the docs

**Comment by milch** [comment]
> 1. During fastlane init, check if a Gemfile already exists, if not create one, if yes, append fastlane to it and verify rubygems.org is the defined source

We can do it during init, we can also do it any time fastlane is run when `!Helper.contained? && !Helper.bundler? && !FastlaneCore::FastlaneFolder.path.nil?` (or deMorgan'd `!(Helper.contained? || Helper.bundler? || FastlaneCore::FastlaneFolder.path.nil?)`) as an interactive step, i.e. before anything else is done: `fastlane is recommended to be run *only* with Bundler as dependency manager, which requires a Gemfile. Do you want fastlane to create one for you now? (yes/no)`. Disable only with some ENV var, e.g. `FL_DISABLE_BUNDLER_CHECK`.

**Comment by milch** [comment]
> Secondly, we should think about dropping support for hardly used installation methods. In particular, the Fabric Mac app, and download.fastlane.tools. Both use basically the homebrew zip file, so it's not a big deal to maintain. But at least we probably don't want to mention them in the docs.

I'm in favour of that

**Comment by taquitos** [comment]
Yeah, totally in favor of trimming out the hard-to-support methods of installation. I think if we start to get more support issue around these methods, we should plan on deprecating and removing. As is, if we aren't actively seeing issues, I'm in favor of keeping them around. The idea being, if we do start seeing more issues, we can prioritize dropping them and migrating people.

**Comment by janpio** [comment]
Thanks @taquitos. They only mention gem install and the app on their site though, right?
https://guides.cocoapods.org/using/getting-started.html#installation
https://guides.cocoapods.org/using/troubleshooting#installing-cocoapods

They don't have the `Gemfile` problem we have?

**Comment by taquitos** [comment]
Yeah, they only mention those bethods on their site, but you can still install it from `homebrew` I'm not sure if they have the gemfile problem, but I've certainly had issues in the past that were ruby-related.

**Comment by KrauseFx** [comment]
As @milch said though, CocoaPods doesn't have any dependencies

**Comment by taquitos** [comment]
Ugh, I guess it is causing support issues: https://github.com/fastlane/fastlane/issues/11573

**Comment by KrauseFx** [comment]
Related docs https://github.com/fastlane/fastlane/issues/11586
