### ISSUE TITLE
Can't access app.build_train

### ISSUE THREAD

**Issue by DuglsYoung** [fastlane/fastlane#11553]
I'm using fastlane 2.75.1 and trying to follow the train example at https://github.com/fastlane/fastlane/blob/master/spaceship/docs/iTunesConnect.md

I'm just using spaceship, no fastfile.  app.all_build_train_numbers returns a list of builds but app.build_trainss[version] doesn't return anything useful. What am I doing wrong?

require 'spaceship'
Spaceship::Tunes.login(login, password)
app = Spaceship::Tunes::Application.find('com.linkedin.MPSampleApp')
=> <Spaceship::Tunes::Application 
	apple_id="809006384", 
	name="MP Sample App", 
	...
irb(main):068:0> app.all_build_train_numbers
=> ["2.8.8", "2.8.9", "2.8.14", "2.8.6", "2.8.16", "2.8.20", "2.8.21", "2.8.11", "2.8.12", "2.8.17", "2.8.19"]
irb(main):069:0> train = app.build_trains["2.8.21"]
(Object doesn't support #inspect)
=> 
irb(main):070:0> train.version_string
NoMethodError: undefined method `version_string' for #<Array:0x007f91ce2389c8>
	from (irb):70
	from /usr/bin/irb:12:in `<main>'

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | ~/.gem/ruby/2.0.0/bin/fastlane                                 |
| Host                        | Mac OS X 10.12.6 (16G1114)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| libxml-ruby               | 2.6.0        |
</details>

*generated on:* **2018-01-12**
</details>

**Comment by milch** [comment]
Hmm, it seems the documentation is wrong there. I believe when you do `build_trains[<version>]` it returns an array with all the builds in the version, at least according to the tests: https://github.com/fastlane/fastlane/blob/master/spaceship/spec/test_flight/build_trains_spec.rb#L44
