### ISSUE TITLE
[question] forcefully fail fastlane

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#11550]
I am using `xcodebuild` to run the tests in my lane.

`sh("xcodebuild test -workspace ./../MyWorkspace.xcworkspace -scheme MyScheme -sdk iphonesimulator  -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty")`

Even though if the unit test fails the fastlane lane returns successfully. I am expecting the lane to fail when the unit test fails with above command. How can we do that?

**Comment by KrauseFx** [comment]
It should fail. But either way, you should use [run_tests](https://docs.fastlane.tools/actions/run_tests/)

**Comment by RishabhTayal** [comment]
I have been having issues with scan for my project and it's really hard to find the issue so I decided to use xcodebuild.

It doesn't fail lane when xcodebuild fails.

**Comment by RishabhTayal** [comment]
Will share output here.

**Comment by hjanuschka** [comment]
have you tried removing the `|xcpretty`  and see if it fails then? maybe xcpretty is messing up the exit code.
because as @KrauseFx  mentioned  `sh`  ususually fails/exists if the command fails.

**Comment by RishabhTayal** [comment]
@hjanuschka Removing the `| xcpretty` from the command is failing the lane. Is there a way to fail lane and use `| xcpretty` as well?

**Comment by RishabhTayal** [comment]
Found more info on [`xcpretty`](https://github.com/supermarin/xcpretty#usage). 

using `sh("set -o pipefail && xcodebuild test -workspace ./../PersonalShopper.xcworkspace -scheme PSClient -sdk iphonesimulator  -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty")` works.
