### ISSUE TITLE
Service account actor - deprecated

### ISSUE THREAD

**Issue by MoMannn** [fastlane/fastlane#11565]
In the supply docs there is a mistake. https://docs.fastlane.tools/actions/supply/ 
Step 6: Click Select a role and choose Project > Service Account Actor 
The service account actor cannot be selected as it is deprecated https://cloud.google.com/iam/docs/service-accounts

The Service Account Actor role
This role has been deprecated. If you need to run operations as the service account, use the Service Account User role. To effectively provide the same permissions as Service Account Actor, you should also grant Service Account Token Creator.

**Comment by janpio** [comment]
Thanks for the note!

Did you try it with a "Service Account User" role account and did everything work? Or does it also take the "Service Account Token Creator"`role?

**Comment by MoMannn** [comment]
I just checked both. I was able to do all the other steps and get the supply. But I cannot say if this effects any other aspects since I just started using fastlane.

**Comment by pburtchaell** [comment]
I also had this issue and chatted with Google Support to verify. Here's what they said: 

> Thank you for waiting. I apologize, we currently do not have a role for "service account Actor." We only have Administrator, Release manager, Product lead, Finance, Customer service, and Read only as predefined roles. 
> If you are needing to give a authorized user different permissions you will need to do a custom role.

**Comment by pburtchaell** [comment]
I created a PR for this at https://github.com/fastlane/docs/pull/530!

**Comment by KrauseFx** [comment]
Thanks for your help @pburtchaell 👍

**Comment by qhartman** [comment]
The page at https://docs.fastlane.tools/actions/supply/ still refers to the actor role.
