### ISSUE TITLE
Fastlane snapshot requires simulator names to include the device type 

### ISSUE THREAD

**Issue by skagedal** [fastlane/fastlane#11563]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run `fastlane snapshot`, I get the error "[!] All devices provided to snapshot should run the same operating system". The devices I give in the Snapfile are all newly created and do all run iOS 11.2.

I found the issue while I was writing this issue. As you see below, the devices I created for use with Snapshot (this approach worked well last time I was using Fastlane, pre-Xcode 9) are named "snapshot-7-Plus". However, Fastlane looks for words like "iphone" and "ipad" in the device name; renaming them solved the problem.

Fastlane should be able to figure out the operating system in a better way. Next best thing would be to give a better error message. "Couldn't figure out the operating system for `snapshot-7-Plus`, please give it a name that includes iPhone", perhaps. 

##### Complete output when running fastlane, including the stack trace and command used
```
➜  ScreenshottedApp fastlane snapshot
[✔] 🚀
[10:49:15]: Successfully loaded '/Users/simon/Documents/Code/ScreenshottedApp/Snapfile' 📄

+----------------------------+-----------------------------------+
|               Detected Values from './Snapfile'                |
+----------------------------+-----------------------------------+
| devices                    | ["snapshot-7-Plus", "snapshot-X"] |
| languages                  | ["en-US"]                         |
| scheme                     | Snapshot                          |
| output_directory           | ./screenshots                     |
| clear_previous_screenshots | true                              |
+----------------------------+-----------------------------------+

[10:49:15]: $ xcodebuild -list -project ./ScreenshottedApp.xcodeproj
[10:49:16]: $ xcodebuild -showBuildSettings -scheme Snapshot -project ./ScreenshottedApp.xcodeproj

+----------------------------+--------------------------------------+
|                    Summary for snapshot 2.75.1                    |
+----------------------------+--------------------------------------+
| project                    | ./ScreenshottedApp.xcodeproj         |
| output_directory           | /Users/simon/Documents/Code/Screens  |
|                            | hottedApp/screenshots                |
| devices                    | ["snapshot-7-Plus", "snapshot-X"]    |
| languages                  | ["en-US"]                            |
| launch_arguments           | [""]                                 |
| output_simulator_logs      | false                                |
| skip_open_summary          | false                                |
| skip_helper_version_check  | false                                |
| clear_previous_screenshots | true                                 |
| reinstall_app              | false                                |
| erase_simulator            | false                                |
| localize_simulator         | false                                |
| buildlog_path              | ~/Library/Logs/snapshot              |
| clean                      | false                                |
| scheme                     | Snapshot                             |
| number_of_retries          | 1                                    |
| stop_after_first_error     | false                                |
| concurrent_simulators      | true                                 |
| xcode_path                 | /Applications/Xcode/Xcode-9.2.app    |
+----------------------------+--------------------------------------+

[10:49:18]: Clearing previously generated screenshots
[10:49:18]: Building and running project - this might take some time...
[10:49:19]: Patching simulators '/Users/simon/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%

[!] All devices provided to snapshot should run the same operating system
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                 |
| --------------------------- | ----------------------------------------------------- |
| OS                          | 10.12.6                                               |
| Ruby                        | 2.2.4                                                 |
| Bundler?                    | false                                                 |
| Git                         | git version 2.14.3 (Apple Git-98)                     |
| Installation Source         | ~/.fastlane/bin/fastlane_lib/bundle/bin/fastlane      |
| Host                        | Mac OS X 10.12.6 (16G1114)                            |
| Ruby Lib Dir                | ~/.fastlane/bin/fastlane_lib/bundle/lib               |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                            |
| Is contained                | true                                                  |
| Is homebrew                 | false                                                 |
| Is installed via Fabric.app | false                                                 |
| Xcode Path                  | /Applications/Xcode/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.4       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.3        |
| tty-spinner               | 0.7.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-01-15**
</details>

**Comment by brunomunizaf** [comment]
a
