### ISSUE TITLE
Can't pass environment variable to get/set_info_plist_value

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#1156]
(fastlane 1.51)
With environment variables set as:
`INFO_PLIST_PATH = File.expand_path './SmartNews/SmartNews-Info.plist'`
`PROJECT_FILE_PATH = File.expand_path '../SmartNews.xcodeproj'`

Used in commands as:
`update_project_team(path: "#{PROJECT_FILE_PATH}", teamid: "#{TEAM_ID_ENTERPRISE}")`
`set_info_plist_value(path: "#{INFO_PLIST_PATH}", key: "CFBundleVersion", value: "#{build_version}")`

update_project_team will accept its environment path variable, but set_info_plist_value complains that `Couldn't find plist file at path '#{INFO_PLIST_PATH}'`

Replacing the variable with the string works:
`set_info_plist_value(path: "./SmartNews/SmartNews-Info.plist", key: "CFBundleVersion", value: "#{build_version}")`

**Comment by atroutt** [comment]
Why not just use ```set_info_plist_value(path: INFO_PLIST_PATH, key: "CFBundleVersion", value: "#{build_version}")``` it's already a string, right?

**Comment by ChristopherDrum** [comment]
@atroutt I'm a total Ruby noob and didn't notice that as an option. You are correct, passing it just as you suggested works fine, but I don't understand why the two different commands handle the same syntax differently.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
