### ISSUE TITLE
Obstacles building fastlane on ubuntu/linux

### ISSUE THREAD

**Issue by henningBunk** [fastlane/fastlane#11579]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi!
It took me a while to get fastlane to run on ubuntu. I was getting build errors on a clean ubuntu installation with an up to date `ruby-dev` installation.

I found a fix [here](https://github.com/ffi/ffi/issues/286#issuecomment-267675030). It looks as follows:

`$ apt-get install build-essential dh-autoreconf)`

After executing it, I could install fastlane. Is there a dependency to one of this two packages or even both? If yes, a hint on the docs would be very helpful for newbies like me :-)

Cheers!

**Comment by lacostej** [comment]
It would have been nice to know the exact error you got before installing the 2 packages. You don't happen to have it somewhere? Maybe in your browser history? :)

**Comment by henningBunk** [comment]
Ah sorry you are right of course.

The error messages were similar on three ubuntu installations but not exactly the same. Yesterday I installed fastlane on two of these successfully with the command above without saving the previous error messages. 

I reproduced the error on the third machine which I haven't touched yesterday. Here is the output:

https://gist.github.com/henningBunk/808166fb9558f7049e8f957b8fe9a6c5

After installing `build-essential` I could install fastlane successfully. `dh-autoreconf` wasn't neccessary. Interesting is, that I couldn't reproduce the error by removing all gems and then remove the two installed apt-get packages and install fastlane again. I am guessing that build-essential comes with dependencies which are crucial. The following packages were installed:

> The following NEW packages will be installed:
>   build-essential dpkg-dev fakeroot g++ g++-7 gcc gcc-7 libalgorithm-diff-perl libalgorithm-diff-xs-perl
>   libalgorithm-merge-perl libasan4 libatomic1 libc-dev-bin libc6-dev libcilkrts5 libfakeroot libgcc-7-dev libitm1
>   liblsan0 libmpx2 libquadmath0 libstdc++-7-dev libtsan0 libubsan0 linux-libc-dev make manpages-dev
> 0 upgraded, 27 newly installed, 0 to remove and 5 not upgraded.

**Comment by milch** [comment]
Hmm, the issue is that native extensions with ruby always need to be built on the machine they are being installed on, so you need a working compiler and build-environment. The `build-essential` package is only necessary to install/update some of the fastlane dependencies. fastlane itself doesn't have any native extensions. This is a known pain point in the ruby community, and some gems are very well known to cause such installation failures because of that. 

Our fastlane installation instructions right now are geared towards macOS users, but we should probably add installation instructions for other platforms as well

**Comment by henningBunk** [comment]
Thank you for your answer. I understand the problem and hopefully this issue is sufficient for any ruby AND fastlane newcomer like me.
