### ISSUE TITLE
undefined local variable or method `method_to_use'

### ISSUE THREAD

**Issue by shubham-gupta-bs** [fastlane/fastlane#11584]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/setup/setup_ios.rb:422:in `finish_up': [!] undefined local variable or method `method_to_use' for #<Fastlane::SetupIos:0x007fcb9b95c7e8> (NameError)
Did you mean?  methods
##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.13                                             |
| Ruby                        | 2.3.1                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.10.1 (Apple Git-78)                 |
| Installation Source         | /usr/local/bin/fastlane                           |
| Host                        | Mac OS X 10.13 (17A405)                           |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                        |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode_8.2.1.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.76.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2018-01-16**
</details>

**Comment by taquitos** [comment]
@shubham-gupta-bs are you able to see if the latest fastlane fixes this issue for you?

**Comment by shubham-gupta-bs** [comment]
This issue is coming in latest fastlane .

**Comment by juliusgonawan** [comment]
i also have the same problem

**Comment by MaikoHermans** [comment]
for me it gives
`undefined local variable or method `notifier' for #<Scan::SlackPoster:0x007fcc15971588>`

**Comment by spaquet** [comment]
Same here. Fastlan 2.76.0

**Comment by ppamorim** [comment]
Happened here too: https://gist.github.com/ppamorim/51d4831c8c58cab830e997a411c79759
