### ISSUE TITLE
Update hipchat action to support other colours, not just red and green

### ISSUE THREAD

**Issue by digitaliceltd** [fastlane/fastlane#1158]
It would be great if we could pass a color, directly to the hipchat action. If set, it overrides the success / fail logic at present.

Happy to make a pull request if happy to integrate.

Cheers
Matt

**Comment by KrauseFx** [comment]
Yeah, if you provide a pull request, we're more than happy to review and merge this feature :+1:

**Comment by digitaliceltd** [comment]
@KrauseFx I have submitted pull request #1160 for this. Hope this helps.

**Comment by KrauseFx** [comment]
That's great, thanks. Fixed with https://github.com/fastlane/fastlane/pull/1160
