### ISSUE TITLE
Error when creating fastfile in Fabric App

### ISSUE THREAD

**Issue by zuil7** [fastlane/fastlane#11599]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Error when creating fastfile in fabric app. Please see attachment

<img width="319" alt="screen shot 2018-01-17 at 5 26 43 pm" src="https://user-images.githubusercontent.com/1681118/35035294-dc404742-fbab-11e7-8c08-0197e7d72374.png">

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.1                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.1 (17B1003)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | ~/Xcode 9.2/Xcode.app/Contents/Developer/                      |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.76.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
</details>

*generated on:* **2018-01-17**
</details>

**Comment by taquitos** [comment]
@zuil7 could you try on-boarding using the install + setup guide here https://docs.fastlane.tools/getting-started/ios/setup/ and letting us know if that works for you?

**Comment by ajhenri** [comment]
+1

Fabric Mac OS app doesn't seem to work nicely with Fastlane.

**Comment by taquitos** [comment]
@ajhenri have you tried this yet: https://github.com/fastlane/fastlane/issues/11599#issuecomment-358386078 ?

**Comment by ajhenri** [comment]
@taquitos My goal was to get some beta build emails sent with Fabric/Crashlytics to QA testers and this is currently not possible to do via the Fabric app.

I ran `fastlane init` and went through the steps. After that I ran `fastlane beta` after setting up the fastfile with the Crashlytics code in https://docs.fastlane.tools/getting-started/ios/beta-deployment/... 

Had a whole lot of provisioning profile errors and was spinning my wheels for a while.

I ended up with the following in my Fastfile:

```
platform :ios do
  desc "Push a new beta build to Crashlytics"
  lane :beta do
    increment_build_number(xcodeproj: "ExampleAppName.xcodeproj")
    build_app(
		scheme: "ExampleAppName",
		export_method: "development"
	)
	crashlytics(api_token: "${API_TOKEN}",
				build_secret: "${BUILD_SECRET}")
  end
end
```

Including that export_method was essential. This worked and my project is now uploaded in Crashlytics.

**Comment by taquitos** [comment]
@ajhenri what caused you to spin your wheels the most? Is there something we could document better, or do automatically?

So glad to hear the set up worked for you!

**Comment by ajhenri** [comment]
@taquitos Hmmm... It could just be me, since I'm a bit rusty with mobile app deployment. 
I guess it would be nice to see the `export method` option being mentioned in https://docs.fastlane.tools/getting-started/ios/beta-deployment/. When running `fastlane beta`, it seems that fastlane defaults to using iOS Distribution provisioning profiles if export_method is not set to 'development'.

**Comment by taquitos** [comment]
@ajhenri thank you, I'm going to open an issue on our docs repo to address this.
