### ISSUE TITLE
Fastfile before_all block runs before each lane.

### ISSUE THREAD

**Issue by dtrenz** [fastlane/fastlane#116]
`before_all` block should run before all lanes, not before each lane.

**Comment by KrauseFx** [comment]
Are you referring to https://github.com/KrauseFx/fastlane/blob/master/Advanced.md#run-multiple-lanes

> Keep in mind the `before_all` and `after_all` block will be executed for each of the lanes.

You think this should be changed? Why?

I think it makes sense, just imaging having 2 different beta testing services. You will probably want to increase the build number for both, which might be done in the `before_all` block.

**Comment by dtrenz** [comment]
I think this could be confusing if you are used to using most testing frameworks (i.e. rspec or Kiwi) where `before :all` is run once, and `before :each` is run before every step/test. 

I would recommend changing it to `before_each` and maybe adding a `before_all` block that executes only once. I would also considering doing the same with `after_all` for consistency/symmetry. 

As an example, I would want use `before_all` to install cocoapods or select an xcode version to use for lanes.

**Comment by joshdholtz** [comment]
I agree with the `before :all` and `before :each` :+1:

**Comment by KrauseFx** [comment]
How about switching to also offering `before :all` and `before :each` and still supporting the old `before_all` (with the same behaviour as it's now)

**Comment by KrauseFx** [comment]
And update the documentation to only make use of the new syntax.

**Comment by dtrenz** [comment]
:+1:

**Comment by Spencevail** [comment]
Any update on this issue? I'm looking to do a build of my app in both our staging and production configurations in a single command and more importantly in a single commit. I have daily builds of our staging app being run, but I'd like to be able to use that same lane but also include a production lane at the same time. Is there still even support for running multiple lanes in one action? 

**To sum up what I'm trying to do:**

When I run
```
fastlane ios staging
```
1. Increments the build number.
2. Builds the staging configuration of the app
3. Delivers to HockeyApp and TestFlight.
4. Commits, tags, and pushes updates to the remote repo.

When I run
```
fastlane ios production
```
1. Increments the build number.
2. Builds both the staging **AND** production configurations.
3. Delivers both apps to HockeyApp and TestFlight (different app identifiers / configurations in each service for both apps).
4. Commits, tags, and pushes updates to remote repo.


Is there an easy way to do this without copy / pasting the staging lane details or creating a bunch of different lanes that just do parts of this? I feel like I might have missed something here...

**Comment by KrauseFx** [comment]
@Spencevail There are multiple ways to solve this.

1. You can add methods to your `Fastfile` as seen in [this example](https://github.com/fastlane/examples/blob/master/MindNode/Fastfile#L4-L48).
2. You can call `fastlane` multiple times like this: `fastlane ios && fastlane production`

Does that answer your question?

**Comment by asfalcone** [comment]
Going to close this issue since it solves the original problem and has been open a while without comment.

**Comment by arunks** [comment]
Hey guys can we get an update on the before :all implementation? Not a big fan of calling the same lane multiple times before running a build lane.

**Comment by KrauseFx** [comment]
@arunks we already have that, just use

```ruby
before_all do
  gym
end
```

**Comment by arunks** [comment]
@KrauseFx  before_all runs before each lane. This becomes an issue if I am trying to call multiple lanes in my build job.

**Comment by TKBurner** [comment]
@arunks Thanks for following up. This is an interesting idea. We'll look into it :+1:

**Comment by jules2689** [comment]
If anyone is looking for `before_each` or `after_each` blocks - it was just merged here: https://github.com/fastlane/fastlane/pull/4264
