### ISSUE TITLE
`fastlane init` thinks there is an iOS project inside my Android project

### ISSUE THREAD

**Issue by Rahulrsannidhi** [fastlane/fastlane#11606]
It looks like there is no iOS project in the current directory, though we did find one in a sub-directory is getting an error while trying to init fast lane with android project directory.

**Comment by janpio** [comment]
What is your project structure?
What commands exactly did you run?
Please also do what @fastlane-bot indicated.

**Comment by Datrio** [comment]
Hey, I'm having the exact same issue. Here is the output of `fastlane env`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.1                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.14.3 (Apple Git-98)               |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane             |
| Host                        | Mac OS X 10.13.1 (17B45a)                       |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | true                                            |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Volumes/External/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2018-01-22**
</details>

**Comment by KrauseFx** [comment]
@Datrio we'll need some more info, as asked for by @janpio, thanks 👍

**Comment by Datrio** [comment]
I have all the necessary gradle files in the root of the project and Android Studio recognises it out of the box. The only command I run is `fastlane init`.

And there are no Xcode projects in any subdirectory AFAIK.

I just updated to fastlane 2.78.0, but the same issue happens.

**Comment by janpio** [comment]
Can you please post the whole output you are getting?

**Comment by Datrio** [comment]
Sure, there you go :). I'm trying this on a Linux box now, will probably report back soon.

```
Dariuszs-MacBook-Air:project-Android dsiedlec$ fastlane init
[17:12:13]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
[17:12:13]: Please `cd` into the directory of the intended Xcode project you wish to use.

[!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again
```

**Comment by janpio** [comment]
Ok, that is basic ;)

Can you run the same command with `--verbose` added at the end?

**Comment by Datrio** [comment]
```
Dariuszs-MacBook-Air:Chris-Android dsiedlec$ fastlane init --verbose
DEBUG [2018-01-23 09:17:47.64]: Checking if there are any plugins that should be loaded...
ERROR [2018-01-23 09:17:50.61]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
ERROR [2018-01-23 09:17:50.61]: Please `cd` into the directory of the intended Xcode project you wish to use.
~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!': [!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again (FastlaneCore::Interface::FastlaneError)
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/ui.rb:16:in `method_missing'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/setup/setup.rb:89:in `start'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:127:in `block (2 levels) in run'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
  from ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
  from ~/.fastlane/bin/bundle/bin/fastlane:22:in `load'
  from ~/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by janpio** [comment]
Thanks - but meh, no useful output.

Let me investigate:

The error message is here:
https://github.com/fastlane/fastlane/blob/403ca43d8842f66d451d67489788dac3f9d43586/fastlane/lib/fastlane/setup/setup.rb#L87

This is the `else` inside an `if ios_projects.count > 0`. `ios_projects` is `ios_projects = Dir["**/*.xcodeproj"] + Dir["**/*.xcworkspace"]`. 

Can you check if there is a file with ending `.xcodeproj` or `.xcworkspace` in there somewhere?

If not, this code is probably not doing what it should and has to be debugged locally by someone.

How exactly did you create your Android project?
Does it also happen with a virgin new Android project created with a current Android Studio?

**Comment by ikesyo** [comment]
It seems that if fastlane is installed by bundler, there is `fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj`. That should be the cause.
