### ISSUE TITLE
Calling an Action (Gradle) from custom Action: default parameter not found

### ISSUE THREAD

**Issue by bmoliveira** [fastlane/fastlane#11608]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to create an Action for Android, that is just a sequence of gradle commands. In my action I'm running `Actions::GradleAction.run(task: "clean")` directly, but I'm getting an exception on some nil value that is suposed to have a default value of ".", when  an action is called this way the default values are not provided?

Thanks in advance

##### Complete output when running fastlane, including the stack trace and command used

/Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/actions/gradle.rb:29:in `join': [!] no implicit conversion of nil into String (TypeError)
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/actions/gradle.rb:29:in `run'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/bundler/gems/fastlane-plugin-deploy_module_bintray-38217e14bbcc/fastlane-plugin-deploy_module_bintray/lib/fastlane/plugin/deploy_module_bintray/actions/deploy_module_bintray_action.rb:12:in `run'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/fastlane/lib/fastlane/cli_tools_distributor.rb:94:in `take_off'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/gems/fastlane-2.76.1/bin/fastlane:20:in `<top (required)>'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/brunooliveira/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.68.2"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy all libs to bintray"
  lane :deploy do
    #This is the one that crashes
    deploy_module_bintray(module_name: "button-countdown", should_clean: true)
    #This is was the method i was using
    #release_module(module: "button-countdown-rx")
  end

  private_lane :release_module do |options|
    module_name = options[:module]
    UI.message "Deploying module: #{module_name} to bintray"
    gradle(task: "clean")
    gradle(task: ":#{module_name}:install")
    gradle(task: ":#{module_name}:bintrayUpload")
    UI.message "Module uploaded: #{module_name} to bintray, go to bintray to upload to JCenter."
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.76.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                | Version | Update-Status      |
| ------------------------------------- | ------- | ------------------ |
| fastlane-plugin-deploy_module_bintray | 0.4.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| did_you_mean                          | 1.0.0        |
| executable-hooks                      | 1.3.2        |
| bundler-unload                        | 1.0.2        |
| rubygems-bundler                      | 1.4.4        |
| bundler                               | 1.16.0       |
| io-console                            | 0.4.5        |
| rake                                  | 12.3.0       |
| CFPropertyList                        | 2.3.6        |
| concurrent-ruby                       | 1.0.5        |
| i18n                                  | 0.9.1        |
| minitest                              | 5.11.1       |
| thread_safe                           | 0.3.6        |
| tzinfo                                | 1.2.4        |
| activesupport                         | 5.1.4        |
| builder                               | 3.2.3        |
| erubi                                 | 1.7.0        |
| mini_portile2                         | 2.3.0        |
| nokogiri                              | 1.8.1        |
| rails-dom-testing                     | 2.0.3        |
| crass                                 | 1.0.3        |
| loofah                                | 2.1.1        |
| rails-html-sanitizer                  | 1.0.3        |
| actionview                            | 5.1.4        |
| rack                                  | 2.0.3        |
| rack-test                             | 0.8.2        |
| actionpack                            | 5.1.4        |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.5.2        |
| babosa                                | 1.0.2        |
| claide                                | 1.0.2        |
| colored                               | 1.2          |
| colored2                              | 3.1.2        |
| highline                              | 1.7.10       |
| commander-fastlane                    | 4.4.5        |
| declarative                           | 0.0.10       |
| declarative-option                    | 0.1.0        |
| unf_ext                               | 0.0.7.4      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20170404 |
| dotenv                                | 2.2.1        |
| method_source                         | 0.9.0        |
| thor                                  | 0.20.0       |
| railties                              | 5.1.4        |
| dotenv-rails                          | 2.2.1        |
| excon                                 | 0.60.0       |
| multipart-post                        | 2.0.0        |
| faraday                               | 0.13.1       |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| faraday_middleware                    | 0.12.2       |
| fastimage                             | 2.1.1        |
| gh_inspector                          | 1.0.3        |
| jwt                                   | 2.1.0        |
| little-plugger                        | 1.1.4        |
| multi_json                            | 1.13.1       |
| logging                               | 2.2.2        |
| memoist                               | 0.16.0       |
| os                                    | 0.9.6        |
| signet                                | 0.8.1        |
| googleauth                            | 0.6.2        |
| httpclient                            | 2.8.3        |
| mime-types-data                       | 3.2016.0521  |
| mime-types                            | 3.1          |
| uber                                  | 0.1.0        |
| representable                         | 3.0.4        |
| retriable                             | 3.1.1        |
| google-api-client                     | 0.13.6       |
| json                                  | 2.1.0        |
| mini_magick                           | 4.5.1        |
| multi_xml                             | 0.6.0        |
| plist                                 | 3.4.0        |
| rubyzip                               | 1.2.1        |
| security                              | 0.1.3        |
| slack-notifier                        | 2.3.2        |
| terminal-notifier                     | 1.8.0        |
| unicode-display_width                 | 1.3.0        |
| terminal-table                        | 1.8.0        |
| tty-screen                            | 0.6.4        |
| tty-cursor                            | 0.5.0        |
| tty-spinner                           | 0.8.0        |
| word_wrap                             | 1.0.0        |
| nanaimo                               | 0.2.3        |
| xcodeproj                             | 1.5.4        |
| rouge                                 | 2.0.7        |
| xcpretty                              | 0.2.8        |
| xcpretty-travis-formatter             | 1.0.0        |
| fastlane-plugin-deploy_module_bintray | 0.4.0        |
</details>

*generated on:* **2018-01-18**

**Comment by taquitos** [comment]
Great question, when you run the action directly, the defaults aren't used. You'll need to manually create a configuration, like this:
```
options = FastlaneCore::Configuration.create(Actions::GradleAction.available_options, { task: "clean" })
Actions::GradleAction.run(options)
```

**Comment by bmoliveira** [comment]
Oh, I see, I didn't see that way of calling an Action, sorry. I guess this is a no Issue then?

**Comment by taquitos** [comment]
It works as expected 👍 
You can check out the various action spec files to see more examples of calling the actions manually 😄

**Comment by bmoliveira** [comment]
I'll do that for sure! But with your solution is working perfectly, thanks a lot.
