### ISSUE TITLE
Docs: update Google credentials setup docs

### ISSUE THREAD

**Issue by xster** [fastlane/fastlane#11619]
The current docs say `7. Click Select a role and choose Project > Service Account Actor` though in https://console.developers.google.com/iam-admin/serviceaccounts, service account roles' `Project` has Owner, Editor, Viewer, Browser and `Service Accounts` has Service Account Admin, Key Admin, Token Creator, User. 

None match the role in the documentation anymore.

**Comment by xster** [comment]
Seems like the role is deprecated
https://cloud.google.com/iam/docs/service-accounts#the_service_account_actor_role

**Comment by janpio** [comment]
Thanks for reporting this, I think this is duplicate to https://github.com/fastlane/fastlane/issues/11565 from a few days ago.
