### ISSUE TITLE
IPA not coherently use between gym and deliver

### ISSUE THREAD

**Issue by QuentinArnault** [fastlane/fastlane#1162]
Hi,

**Steps**
1. Run deploy lane with fastlane for one application (one specific scheme of my workspace)
`fastlane deploy --env gopili`

Everything goes well, a gopili.ipa is generated in the workspace folder

2. Run deploy lane with fastlane for another application
`fastlane deploy --env kelbillet`

**Expected result**
IPA generated by gym should be used by deliver action.

**Observed result**
Gym works well, but deliver do not use ipa generated with gym, but ipa generated by previous `fastlane deploy`command (aka gopili.ipa)

**Information**
 - fastlane 1.52.0
 - Xcode 7.2 (7C68)
 - OS X El Capitan 10.11.2

[fastlane_deploy.log.zip](https://github.com/fastlane/fastlane/files/98483/fastlane_deploy.log.zip)

[fastlane_conf.zip](https://github.com/fastlane/fastlane/files/98484/fastlane_conf.zip)

<img width="660" alt="capture_d ecran_2016-01-21_a_01_46_58" src="https://cloud.githubusercontent.com/assets/1578026/12468232/f9c5d992-bfe1-11e5-9aba-adff09965908.png">

**Comment by KrauseFx** [comment]
That's weird, could you add `debug` right after running `gym` and post the results here? This will print out the lane environment

**Comment by QuentinArnault** [comment]
Debug logs:

```[12:40:03]: -------------------
[12:40:03]: --- Step: debug ---
[12:40:03]: -------------------
Lane Context
{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"kelbillet", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy", :IPA_OUTPUT_PATH=>"/Users/qarnault/Desktop/bug_hunt/kelbillet.ipa", :DSYM_OUTPUT_PATH=>"/Users/qarnault/Desktop/bug_hunt/kelbillet.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/qarnault/Library/Developer/Xcode/Archives/2016-01-21/kelbillet 2016-01-21 12.38.29.xcarchive"}
[12:40:03]: ---------------------
[12:40:03]: --- Step: deliver ---
[12:40:03]: ---------------------
[12:40:03]: Login to iTunes Connect (quentin@kelbillet.com)
[12:40:07]: Login successful

+-------------------+-------------------------+
|            deliver 1.8.0 Summary            |
+-------------------+-------------------------+
| username          | quentin@kelbillet.com   |
| app_identifier    | com.kelbillet.kelbillet |
| ipa               | gopili.ipa              |
| metadata_path     | ./fastlane/metadata     |
| screenshots_path  | ./fastlane/screenshots  |
| skip_screenshots  | false                   |
| app_version       | 1.9                     |
| skip_metadata     | false                   |
| force             | false                   |
| submit_for_review | true                    |
| automatic_release | false                   |
+-------------------+-------------------------+```

**Comment by KrauseFx** [comment]
Alright, this is caused since it detects an ipa file in the current directory, the priorities are wrong in this one, I'll work on a fix :+1:

**Comment by QuentinArnault** [comment]
Thanks.
