### ISSUE TITLE
Why couldn't I use 'gets.chomp()' before upload my ipa to pgyServer ?

### ISSUE THREAD

**Issue by CoderHRXu** [fastlane/fastlane#11622]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I need use a fastlane plugin called 'pgyer' to upload my app to server.My custom lane is like this 

```ruby
lane: pack_and_upload  do |options|
         .........
          gym(
			scheme: scheme,
			export_method: "ad-hoc",
			silent:true,
			output_directory:outputDirectory,
			output_name:ipaName,
			archive_path:outputDirectory,
			export_xcargs: "-allowProvisioningUpdates",
			# Bundle identifier:  app_identifier,
		 	# Profile name:       "match AdHoc #{app_identifier}",
			# Profile type:       "ad-hoc",
			export_options: {
				provisioningProfiles: {
					app_identifier => "match AdHoc #{app_identifier}"
				}
			}

		)
	print "What's update in this build? 请输入本次更新内容：\n"
	description = gets.chomp()
	pgyer(api_key: "xxx", user_key: "xxxx",update_description: description)
end
```
Everytime when I use this lane, after gym action finished ,the process always goes directly. So I cannot input any word. Finally, fastlane will throw an error and My app cannot be uploaded successfully.

What makes me confused is that my workmate use the same lane , he can build and upload successfully. 

When I modify my lane like this
 ```  
        #print "What's update in this build? 请输入本次更新内容：\n"
	#description = gets.chomp()  
        pgyer(api_key: "xxx", user_key: "xxxx")
```
my fastlane can go successfully.

So, why couldn't I use 'gets.chomp()'??

##### Complete output when running fastlane, including the stack trace and command used

```ruby 
......
[16:26:25]: Successfully exported and compressed dSYM file
[16:26:25]: Successfully exported and signed the ipa file:
[16:26:25]: /Users/haoran/Desktop/xx/xxx/xxxx/fastlane/build/test/xxxx-TEST.ipa
What's update in this build? 请输入本次更新内容：
[16:26:25]: --------------------------
[16:26:25]: --- Step: notification ---
[16:26:25]: --------------------------
.......
No such file or directory @ rb_sysopen - test (in red color)
.....
fastlane finished with errors

```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
    import_from_git(url: 'http://gitlab.xxxx.cn/iOS-Team/fastlane.git')

    lane :xxxtest do |options|
        
            print "what's update in this build?请输入本次更新内容：\n"
            # description = gets.chomp()
            description = gets
            puts "更新内容为#{description}"
        
    end
    

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.8.5        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-pgyer     | 0.2.1        |
</details>

*generated on:* **2018-01-19**
</details>

**Comment by taquitos** [comment]
I'm not totally sure why that wouldn't work, but you can use the `prompt` action:
```
description = prompt(text: "What's update in this build? 请输入本次更新内容: ")
```
And that should work

**Comment by CoderHRXu** [comment]
@taquitos  Thankyou for your answer, I have tried the ```prompt``` action, and it works. 
I found the ```changelog_from_git_commits``` action can also achieve my goals. 
```

 description = changelog_from_git_commits(
                          date_format: "short",
                          commits_count: "1",
                        )
 
```
Just like this, fastlane can get the lateast git commit changelog as update description.

**Comment by taquitos** [comment]
That's awesome, I'm so glad it all worked out for you!
