### ISSUE TITLE
Fabric: Can't generate Fastfile: "invalid option: --crashlytics_path" (Regression)

### ISSUE THREAD

**Issue by ZubenkoIlya** [fastlane/fastlane#11620]
I tried to generate fastfile, but I'm constantly getting this error:

![image](https://user-images.githubusercontent.com/19538740/35127977-0a22a486-fcbd-11e7-819f-13e8dfe859dc.png)

I have no idea why this error occurs.

My config:
Fabric 2.6.17
Fastlane 2.77.1
XCode 9.2, Swift 4.
macOS X Sierra 10.12.6

UPD: fastlane env
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.14.3 (Apple Git-98)               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                        |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.74.1"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    build_app(scheme: 'HomeAdvisor', export_method: 'development')

    emails = values[:test_email] ? values[:test_email] : ['zubenkoilya1993@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'a30a2cf1098cff107868c168a1d2412e3d4af78c',
             build_secret: '0cbe318d3247750f289cd39d6686a8785068c0bdf55a29f7021a7cb936a9b15c',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-19**
</details>

!!!
UPD 2. Solution:

Uninstall fastline(2.77.1) and install fastline previous version(2.69.2).

**Comment by Stan-Ost** [comment]
I have exactly the same issue. Looks like you have previous installation of Fastlane without using Fabric app.

**Comment by ZubenkoIlya** [comment]
I did uninstall fastline and install fastline version 2.69.2(was 2.77.1) and error went missing. 

Developers, correct your new version.

**Comment by mohammedelsammak** [comment]
I have same same issue with 2.77.1..will try to install 2.69.2 and recheck

**Comment by JanOwiesniak** [comment]
Running into the same issue with `fastlane-2.77.1`, so i downgraded fastlane to `fastlane-2.69.2`.
I can not finish the `fastlane beta` setup process because the fabric app forces me to update fastlane to the newest version. Any tips on this?

![fastlane_beta](https://user-images.githubusercontent.com/213214/35154161-66454a2c-fd29-11e7-84dd-be8e317e28b8.png)

**Comment by megatolya** [comment]
I found workaround for me. Install fastlane from cli
https://docs.fastlane.tools/getting-started/ios/setup/#getting-started-with-fastlane-for-ios

**Comment by KrauseFx** [comment]
Hey everyone, sorry it seems like something currently doesn't work with the Beta onboarding, could you migrate to our recommended way of installing and using _fastlane_? Check out the guide over here https://github.com/fastlane/fastlane/issues/11586. 

To then generate a Fastfile, you `bundle exec fastlane init`, select the manual mode, and get started with Beta onboarding according to https://docs.fastlane.tools/getting-started/ios/beta-deployment/, in particular the Crashlytics section 👍 

Let me know if that helps

**Comment by hardikamal** [comment]
@everyone How do I downgrade? Even I am facing the same issue.

**Comment by JanOwiesniak** [comment]
@hardikamal 

```bash
$ gem uninstall fastlane
$ gem install fastlane -v '<VERSION_NUMBER>'
```

**Comment by KrauseFx** [comment]
@JanOwiesniak Could you tell us a bit more about what kind of error/message you get? I'd recommend running your app at least once in your iOS simulator/device, and then maybe uploading one build to Beta manually, and then using _fastlane_ from then on. Let me know if that works for you 👍

**Comment by spaquet** [comment]
@KrauseFx Did what you are recommending doing. It's working when the app is uploaded using an archive and manual approach from Fabric, but still fails to initiate fastlane.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.4                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.16.1                              |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.13.4 (17E139j)                      |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 9.2                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2018-01-25**
</details>

**Comment by KrauseFx** [comment]
Could you share the output and error message also, with the stack trace?

**Comment by spaquet** [comment]
Here what I have in the UI:
![image](https://user-images.githubusercontent.com/176050/35416074-b1e98a62-01dc-11e8-887a-dbb06dbfdc5c.png)

**Comment by KrauseFx** [comment]
Yep, please follow the instructions from over there 👍 https://github.com/fastlane/fastlane/issues/11620#issuecomment-359024591

**Comment by spaquet** [comment]
Does work, but does that mean that the configuration must be done manually and not from the Fabric app?

**Comment by KrauseFx** [comment]
That's right, please follow our official docs on https://docs.fastlane.tools/getting-started/ios/beta-deployment/

**Comment by ahmadalfy** [comment]
This is happening on the lastest version of fastlane 2.93.1
