### ISSUE TITLE
nuke development [!] undefined method `strftime' for nil:NilClass

### ISSUE THREAD

**Issue by OliverZiegler** [fastlane/fastlane#11630]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

fastlane match nuke development

[... some things omitted ... ]

[18:20:02]: Fetching certificates and profiles...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Support for App-Specific Password or something.
    https://github.com/fastlane/fastlane/issues/6095 [closed] 27 💬
    04 Jul 2017

➡️  make_changelog_from_jenkins failing on Jenkins on line 12
    https://github.com/fastlane/fastlane/issues/8476 [closed] 2 💬
    08 Jun 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/nuke.rb:106:in `block in print_tables': [!] undefined method `strftime' for nil:NilClass (NoMethodError)
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/nuke.rb:106:in `collect'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/nuke.rb:106:in `print_tables'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/nuke.rb:37:in `run'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/commands_generator.rb:139:in `block (3 levels) in run'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/commands_generator.rb:146:in `run'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/match/lib/match/commands_generator.rb:19:in `start'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
        from /Users/Oli/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.77.1/bin/fastlane:20:in `<top (required)>'
        from /Users/Oli/.fastlane/bin/bundle/bin/fastlane:22:in `load'
        from /Users/Oli/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-19**
</details>

**Comment by lacostej** [comment]
@taquitos there are other path where we make the assumption that a certificate has an expiration.
Same for profiles.

Have we reviewed those? What are those cases that cause expiration to be `nil`

See just below
```
lacostej@2015MBP ~/Code/OSS/fastlane (master) git grep "\.expires"
cert/lib/cert/runner.rb:        certificate.expires < Time.now.utc
match/lib/match/nuke.rb:          cert_expiration = cert.expires.nil? ? "Unknown" : cert.expires.strftime("%Y-%m-%d")
match/lib/match/nuke.rb:          [p.name, p.id, status, p.type, p.expires.strftime("%Y-%m-%d")]
pem/lib/pem/manager.rb:          remaining_days = (existing_certificate.expires - Time.now) / 60 / 60 / 24
pem/lib/pem/manager.rb:        certificate.all.sort { |x, y| y.expires <=> x.expires }
sigh/lib/sigh/runner.rb:          str = ["\t- Name:", c.owner_name, "- ID:", c.id + " - Expires", c.expires.strftime("%d/%m/%Y")].join(" ")
spaceship/spec/portal/certificate_spec.rb:      expect(cert.expires.class).to eq(Time)
spaceship/spec/portal/certificate_spec.rb:      expect(cert.expires.to_s).to eq('2015-11-25 22:45:50 UTC')
spaceship/spec/portal/certificate_spec.rb:      expect(push.expires.to_s).to eq('2016-04-01 21:24:00 UTC')
spaceship/spec/portal/certificate_spec.rb:    expect(cert.expires.to_s).to eq('2015-11-25 22:45:50 UTC')
spaceship/spec/portal/invite_spec.rb:    expect(invited.expires).to eq(Time.at(expires / 1000))
spaceship/spec/portal/invite_spec.rb:    expect(invited.expires).to eq(Time.at(expires / 1000))
spaceship/spec/provisioning_profile_spec.rb:      expect(profile.expires.class).to eq(Time)
spaceship/spec/provisioning_profile_spec.rb:      expect(profile.expires.to_s).to eq('2016-02-10 00:00:00 UTC')
```

**Comment by taquitos** [comment]
I haven't reviewed them, that's a great point, we should. 
I dug in a tiny bit and didn't get any answers around why expiration would be `nil`. In the case I was looking at, it didn't have an impact on anything (no calculations being done with dates, just printing info).

I think it would be really helpful to look into, I just need to find some time (unlikely 😢 right now).
Is that something you'd have time to look into?

**Comment by taquitos** [comment]
(@lacostej ^)
