### ISSUE TITLE
upload_to_play_store failing for promoting track

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#11632]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`upload_to_play_store` action is failing if we try to just promote the beta track to production. I am using following command in my lane. The build is already uploaded to beta track. I am trying to promote it to production.

```
  desc "Promote beta track to production"
  lane :promote_to_prod_track do
    upload_to_play_store(
      track_promote_to: 'production', 
      json_key: 'play-store.json',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: 'beta'
      )
  end
```

##### Complete output when running fastlane, including the stack trace and command used

The `--capture_output` option just returns the lane without any error.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
min_fastlane_version("2.70.1")

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics(api_token: "apitoken", build_secret: "buildsecret")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    new_version = increment_version_code
    gradle(task: 'clean')
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "keystore",
        "android.injected.signing.store.password" => "password",
        "android.injected.signing.key.alias" => "alias",
        "android.injected.signing.key.password" => "password",
        })
    upload_to_play_store(json_key: 'play-store.json', track: 'beta')
    do_git(commit_message: 'Uploaded to play store by fastlane. 🚀', version: new_version)
  end

  desc "Promote beta track to production"
  lane :promote_to_prod_track do
    upload_to_play_store(
      track_promote_to: 'production', 
      json_key: 'play-store.json',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: 'beta'
      )
  end

  desc "Git commit command"
  private_lane :do_git do |options|
    if options[:commit_message] == nil 
      commit_message = prompt(text: "Enter Commit message", boolean: false)
    else
      commit_message = options[:commit_message]
    end
    git_commit ({
      path: ".",
      message: commit_message
    })
    push_to_git_remote
    add_git_tag(tag: options[:version].to_s)
    push_git_tags
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "com.krausefx.app"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.70.3  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| CFPropertyList                         | 2.3.6        |
| activesupport                          | 4.2.8        |
| addressable                            | 2.5.2        |
| ast                                    | 2.3.0        |
| babosa                                 | 1.0.2        |
| bigdecimal                             | 1.2.6        |
| bundler                                | 1.14.6       |
| claide                                 | 1.0.2        |
| claide-plugins                         | 0.9.2        |
| clamp                                  | 0.6.5        |
| cocoapods                              | 1.2.1        |
| cocoapods-core                         | 1.2.1        |
| cocoapods-deintegrate                  | 1.0.1        |
| cocoapods-downloader                   | 1.1.3        |
| cocoapods-plugins                      | 1.0.0        |
| cocoapods-search                       | 1.0.0        |
| cocoapods-stats                        | 1.0.0        |
| cocoapods-trunk                        | 1.3.0        |
| cocoapods-trunk                        | 1.2.0        |
| cocoapods-try                          | 1.1.0        |
| coderay                                | 1.1.2        |
| colored                                | 1.2          |
| colored2                               | 3.1.2        |
| colorize                               | 0.8.1        |
| commander-fastlane                     | 4.4.5        |
| concurrent-ruby                        | 1.0.5        |
| cork                                   | 0.3.0        |
| danger                                 | 5.3.4        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| diff-lcs                               | 1.3          |
| docile                                 | 1.1.5        |
| domain_name                            | 0.5.20170404 |
| dotenv                                 | 2.2.1        |
| escape                                 | 0.0.4        |
| excon                                  | 0.60.0       |
| excon                                  | 0.59.0       |
| faraday                                | 0.13.1       |
| faraday-cookie_jar                     | 0.0.6        |
| faraday-http-cache                     | 1.3.1        |
| faraday_middleware                     | 0.11.0.1     |
| fastimage                              | 2.1.1        |
| fastimage                              | 2.1.0        |
| fastlane-plugin-android_versioning     | 0.2.2        |
| fastlane-plugin-changelog              | 0.9.0        |
| fastlane-plugin-changelog              | 0.7.0        |
| fastlane-plugin-clubmate               | 0.1.0        |
| fastlane-plugin-hours                  | 0.3.2        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-ruby                   | 0.1.3        |
| fastlane-plugin-sharethemeal           | 0.1.9        |
| fastlane-plugin-slack_train            | 0.2.0        |
| fastlane-plugin-synx                   | 0.1.3        |
| fourflusher                            | 2.0.1        |
| fuzzy_match                            | 2.0.4        |
| gh_inspector                           | 1.0.3        |
| git                                    | 1.3.0        |
| google-api-client                      | 0.13.5       |
| googleauth                             | 0.5.1        |
| highline                               | 1.7.10       |
| http-cookie                            | 1.0.3        |
| httpclient                             | 2.8.3        |
| hurley                                 | 0.2          |
| i18n                                   | 0.9.1        |
| i18n                                   | 0.8.1        |
| io-console                             | 0.4.3        |
| json                                   | 1.8.1        |
| jwt                                    | 2.1.0        |
| jwt                                    | 1.5.6        |
| kramdown                               | 1.16.2       |
| kramdown                               | 1.13.2       |
| libxml-ruby                            | 3.0.0        |
| little-plugger                         | 1.1.4        |
| logging                                | 2.2.2        |
| memoist                                | 0.16.0       |
| method_source                          | 0.9.0        |
| mime-types                             | 3.1          |
| mime-types-data                        | 3.2016.0521  |
| mini_magick                            | 4.5.1        |
| mini_portile2                          | 2.2.0        |
| minitest                               | 5.10.3       |
| minitest                               | 5.4.3        |
| molinillo                              | 0.5.7        |
| multi_json                             | 1.12.2       |
| multi_xml                              | 0.6.0        |
| multipart-post                         | 2.0.0        |
| mustermann                             | 1.0.1        |
| nanaimo                                | 0.2.3        |
| nap                                    | 1.1.0        |
| netrc                                  | 0.11.0       |
| netrc                                  | 0.7.8        |
| no_proxy_fix                           | 0.1.2        |
| nokogiri                               | 1.5.6        |
| octokit                                | 4.7.0        |
| open4                                  | 1.3.4        |
| os                                     | 0.9.6        |
| parallel                               | 1.12.1       |
| parallel                               | 1.12.0       |
| parser                                 | 2.4.0.2      |
| parser                                 | 2.4.0.0      |
| plist                                  | 3.4.0        |
| plist                                  | 3.3.0        |
| power_assert                           | 0.2.2        |
| powerpack                              | 0.1.1        |
| psych                                  | 2.0.8        |
| public_suffix                          | 2.0.5        |
| rack                                   | 2.0.3        |
| rainbow                                | 2.2.2        |
| rake                                   | 12.3.0       |
| rake                                   | 12.0.0       |
| rake                                   | 10.4.2       |
| rdoc                                   | 4.2.0        |
| representable                          | 3.0.4        |
| rest-client                            | 2.0.2        |
| retriable                              | 3.1.1        |
| rouge                                  | 2.0.7        |
| rouge                                  | 1.11.1       |
| rspec-support                          | 3.5.0        |
| ruby-macho                             | 1.1.0        |
| ruby-progressbar                       | 1.9.0        |
| ruby-progressbar                       | 1.8.3        |
| rubygems-update                        | 2.5.2        |
| rubyzip                                | 1.2.1        |
| sawyer                                 | 0.8.1        |
| security                               | 0.1.3        |
| signet                                 | 0.7.3        |
| simplecov-html                         | 0.10.2       |
| slack-notifier                         | 1.5.1        |
| sqlite3                                | 1.3.13       |
| stm_api                                | 0.1.7        |
| synx                                   | 0.2.1        |
| terminal-notifier                      | 1.8.0        |
| terminal-table                         | 1.8.0        |
| terminal-table                         | 1.7.3        |
| test-unit                              | 3.0.8        |
| thread_safe                            | 0.3.6        |
| tilt                                   | 2.0.8        |
| tty-cursor                             | 0.5.0        |
| tty-screen                             | 0.6.4        |
| tty-screen                             | 0.6.3        |
| tzinfo                                 | 1.2.4        |
| tzinfo                                 | 1.2.3        |
| uber                                   | 0.1.0        |
| unf                                    | 0.1.4        |
| unf_ext                                | 0.0.7.4      |
| unicode-display_width                  | 1.3.0        |
| unicode-display_width                  | 1.1.3        |
| word_wrap                              | 1.0.0        |
| xcodeproj                              | 1.5.4        |
| xcodeproj                              | 1.5.3        |
| xcpretty                               | 0.2.6        |
| xcpretty-travis-formatter              | 0.0.4        |
</details>

*generated on:* **2018-01-19**
</details>

**Comment by lacostej** [comment]
Have you tried enabling debug? Set the DEBUG environment variable to something before running your command. This should at least show more information about the requests made.

**Comment by RishabhTayal** [comment]
@lacostej Here are the logs after setting `DEBUG` environment variable.

<details><summary>Debug log</summary>

```
D, [2018-01-21T18:39:43.299833 #83516] DEBUG -- : Sending HTTP post https://www.googleapis.com/androidpublisher/v2/applications/com.rtayal.itunesconnect/edits?
D, [2018-01-21T18:39:45.985621 #83516] DEBUG -- : 200
D, [2018-01-21T18:39:45.986036 #83516] DEBUG -- : #<HTTP::Message:0x007f83e2618308 @http_header=#<HTTP::Message::Headers:0x007f83e26182e0 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3fc1f130c97c URI:https://www.googleapis.com/androidpublisher/v2/applications/com.rtayal.itunesconnect/edits?>, @request_query=nil, @request_absolute_uri=nil, @status_code=200, @reason_phrase="OK", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Cache-Control", "no-cache, no-store, max-age=0, must-revalidate"], ["Pragma", "no-cache"], ["Expires", "Mon, 01 Jan 1990 00:00:00 GMT"], ["Date", "Mon, 22 Jan 2018 00:39:45 GMT"], ["ETag", "\"Bm7uKGaqKCKpsOGLEJDfQT5cCYo/FA6RYubUQ553A0jllzijnSQB0NI\""], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["X-Content-Type-Options", "nosniff"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], ["Server", "GSE"], ["Alt-Svc", "hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x007f83e25f8d78>, issuer=#<OpenSSL::X509::Name:0x007f83e25f8d50>, serial=#<OpenSSL::BN:0x007f83e25f8d28>, not_before=2018-01-10 09:50:08 UTC, not_after=2018-04-04 09:40:00 UTC>, @http_body=#<HTTP::Message::Body:0x007f83e2618268 @body="{\n \"id\": \"02147681483006311871\",\n \"expiryTimeSeconds\": \"1516588785\"\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
D, [2018-01-21T18:39:45.986695 #83516] DEBUG -- : Success - #<Google::Apis::AndroidpublisherV2::AppEdit:0x007f83e25f8558
 @expiry_time_seconds="1516588785",
 @id="02147681483006311871">

+------------------+-------------------------------+
|                   Lane Context                   |
+------------------+-------------------------------+
| DEFAULT_PLATFORM | android                       |
| PLATFORM_NAME    | android                       |
| LANE_NAME        | android promote_to_prod_track |
+------------------+-------------------------------+
[18:39:46]: No local metadata found, make sure to run `fastlane supply init` to setup supply

```
</details>

**Comment by joshdholtz** [comment]
@RishabhTayal Were you able to get this solved?

**Comment by joshdholtz** [comment]
@RishabhTayal Looks like it is a bug right here - https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L8

Its expecting metadata, apk path, or apk paths (which make sense for most things but not working when just trying to promote a track. I will look into fixing this 👌

**Comment by RishabhTayal** [comment]
@joshdholtz Awesome! Thanks.
