### ISSUE TITLE
Unsupported screen size [2286, 3168] for path '../Screenshots/snip_framed.png'

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#11638]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've setup the following lane

```
  lane :justupload do
    frame_screenshots(white: true, path: '../screenshots/STT_V1')
    upload_to_app_store(screenshots_path: '../screenshots/STT_V1')
  end
```

This is my snapfile

```
 devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPad Pro (12.9-inch)",
 ])

languages([
  "en-US",
])

scheme "myapp"
output_directory "../screenshots/STT_V1"
workspace "./mpapp.xcworkspace"
concurrent_simulators true
```
When running `fastlane justupload` I receive the following error.

[09:37:20]: fastlane finished with errors

[!] Unsupported screen size [2286, 3168] for path '../Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-0Results_framed.png'

##### Complete output when running fastlane, including the stack trace and command used

[✔] 🚀 
[09:35:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:35:56]: ----------------------------------------
[09:35:56]: --- Step: Verifying fastlane version ---
[09:35:56]: ----------------------------------------
[09:35:56]: Your fastlane version 2.77.1 matches the minimum requirement of 2.71.1  ✅
[09:35:56]: ------------------------------
[09:35:56]: --- Step: default_platform ---
[09:35:56]: ------------------------------
[09:35:56]: Driving the lane 'ios justupload' 🚀
[09:35:56]: -----------------------
[09:35:56]: --- Step: cocoapods ---
[09:35:56]: -----------------------
[09:35:56]: $ pod install
[09:35:58]: ▸ Analyzing dependencies
[09:35:58]: ▸ Downloading dependencies
snip
[09:35:58]: ▸ Generating Pods project
[09:35:58]: ▸ Integrating client project
[09:36:00]: ▸ Sending stats
[09:36:00]: ▸ Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
[09:36:00]: -------------------------------
[09:36:00]: --- Step: frame_screenshots ---
[09:36:00]: -------------------------------
[09:36:00]: Framing screenshots at path ../screenshots/STT_V1 (via frameit)
[09:36:00]: Using device frames version 'latest'
[09:36:00]: Framing screenshot './en-US/iPad Pro (12.9-inch)-0Results.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:08]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-0Results_framed.png'
[09:36:08]: Framing screenshot './en-US/iPad Pro (12.9-inch)-1Test.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:16]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-1Test_framed.png'
[09:36:16]: Framing screenshot './en-US/iPad Pro (12.9-inch)-2Learn.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:23]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-2Learn_framed.png'
[09:36:23]: Framing screenshot './en-US/iPad Pro (12.9-inch)-3Main.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:31]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-3Main_framed.png'
[09:36:31]: Framing screenshot './en-US/iPad Pro (12.9-inch)-4Cho0se.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:39]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-4Cho0se_framed.png'
[09:36:39]: Framing screenshot './en-US/iPhone 6 Plus-0Results.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:44]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6 Plus-0Results_framed.png'
[09:36:44]: Framing screenshot './en-US/iPhone 6 Plus-1Test.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:49]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6 Plus-1Test_framed.png'
[09:36:49]: Framing screenshot './en-US/iPhone 6 Plus-2Learn.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:36:55]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6 Plus-2Learn_framed.png'
[09:36:55]: Framing screenshot './en-US/iPhone 6 Plus-3Main.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:00]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6 Plus-3Main_framed.png'
[09:37:00]: Framing screenshot './en-US/iPhone 6 Plus-4Cho0se.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:05]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6 Plus-4Cho0se_framed.png'
[09:37:05]: Framing screenshot './en-US/iPhone 6-0Results.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:07]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6-0Results_framed.png'
[09:37:07]: Framing screenshot './en-US/iPhone 6-1Test.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:09]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6-1Test_framed.png'
[09:37:09]: Framing screenshot './en-US/iPhone 6-2Learn.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:11]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6-2Learn_framed.png'
[09:37:11]: Framing screenshot './en-US/iPhone 6-3Main.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:13]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6-3Main_framed.png'
[09:37:13]: Framing screenshot './en-US/iPhone 6-4Cho0se.png'
Forced orientation: 
Forced orientation: 
Forced orientation: 
Forced orientation: 
[09:37:16]: Added frame: '/Users/jm/Dropbox/Code_ObjC/Screenshots/STT_V1/en-US/iPhone 6-4Cho0se_framed.png'
[09:37:16]: ---------------------------------
[09:37:16]: --- Step: upload_to_app_store ---
[09:37:16]: ---------------------------------
[09:37:16]: Successfully loaded '/Users/jm/Dropbox/Code_ObjC/MyApp/fastlane/Deliverfile' 📄

+--------------------+--------------------------+
| Detected Values from './fastlane/Deliverfile' |
+--------------------+--------------------------+
| app_identifier     | snip |
| username           | snip  |
+--------------------+--------------------------+

[09:37:16]: Login to iTunes Connect (snip)
[09:37:18]: Login successful

+--------------------------------------+--------------------------+
|                     deliver 2.77.1 Summary                      |
+--------------------------------------+--------------------------+
| screenshots_path                     | ../screenshots/STT_V1    |
| metadata_path                        | ./fastlane/metadata      |
| username                             | snip |
| app_identifier                       | snip |
| edit_live                            | false                    |
| platform                             | ios                      |
| skip_binary_upload                   | false                    |
| skip_screenshots                     | false                    |
| skip_metadata                        | false                    |
| skip_app_version_update              | false                    |
| force                                | false                    |
| submit_for_review                    | false                    |
| automatic_release                    | false                    |
| phased_release                       | false                    |
| dev_portal_team_id                   | snip               |
| overwrite_screenshots                | false                    |
| run_precheck_before_submit           | true                     |
| precheck_default_rule_level          | warn                     |
| ignore_language_directory_validation | false                    |
| precheck_include_in_app_purchases    | true                     |
+--------------------------------------+--------------------------+

[09:37:20]: Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃
[09:37:20]: 🏃 Skipping screenshot file: ../Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-0Results.png
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios justupload |
+------------------+----------------+
[09:37:20]: Unsupported screen size [2286, 3168] for path '../Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-0Results_framed.png'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | cocoapods                  | 3           |
| 4    | frame_screenshots          | 75          |
| 💥   | upload_to_app_store        | 4           |
+------+----------------------------+-------------+

[09:37:20]: fastlane finished with errors

[!] Unsupported screen size [2286, 3168] for path '../Screenshots/STT_V1/en-US/iPad Pro (12.9-inch)-0Results_framed.png'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.6                                       |
| Ruby                        | 2.4.1                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.10.1                            |
| Installation Source         | /usr/local/bin/fastlane                       |
| Host                        | Mac OS X 10.12.6 (16G1114)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode92.app/Contents/Developer/ |
| Xcode Version               | 9.2                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.71.1")

default_platform(:ios)

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # cocoapods
  end

  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true, path: '../screenshots/STT_V1')
    upload_to_app_store
  end

  lane :justupload do
    frame_screenshots(white: true, path: '../screenshots/STT_V1')
    upload_to_app_store(screenshots_path: '../screenshots/STT_V1')
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sync_code_signing(type: "appstore") # more information: https://codesigning.guide
    build_app(scheme: "MyApp") # more options available
    upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "MyApp") # more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "snip" # The bundle identifier of your app
apple_id "snip" # Your Apple email address

team_id "snip" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.3       |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2018-01-20**
</details>

**Comment by Jules2010** [comment]
I don’t believe that’s the case other images are ok

**Comment by Jules2010** [comment]
Ahhh https://github.com/fastlane/fastlane/issues/7432

A better error would be nice :(

**Comment by joshdholtz** [comment]
Linking for historical purposes.= https://docs.fastlane.tools/actions/frameit/#usage
>When using frameit without titles on top, the screenshots will have the full resolution, which means they can't be uploaded to the App Store directly. They are supposed to be used for websites, print media and emails. Check out the section below to use the screenshots for the App Store.

**Comment by Jules2010** [comment]
This isn’t fixed though.

**Comment by joshdholtz** [comment]
@Jules2010 My bad! I thought your link to the other issue was saying that solved it for you.

**Comment by joshdholtz** [comment]
@Jules2010 Are you thinking we display an error in the console like the following?

>When using frameit without titles on top, the screenshots will have the full resolution, which means they can't be uploaded to the App Store directly. They are supposed to be used for websites, print media and emails. Check out the section below to use the screenshots for the App Store.

**Comment by Jules2010** [comment]
I don’t provide these for any other screen shots are they all provide the correct size. 

I think I was mistaken when I mention 7432
