### ISSUE TITLE
First time fastlane setup "uninitialized constant Fastlane::VERSION" 

### ISSUE THREAD

**Issue by BlakeMccartin** [fastlane/fastlane#11633]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm new to fastlane and ruby, and I've gone through the setup process but both `fastlane init` and `fastlane --version` are failing with the similar output errors. It's complaining that VERSION is not set. I'm new to Ruby, but I see in the fastlane bin file that only `fastlane/cli_tools_distributor` is required, not `fastlane/version`. Is there somewhere else the other modules are required?

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane init
[⠹] 🚀 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:101:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:101:in `take_off'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/bin/fastlane:23:in `<main>'
```

```
fastlane --version
fastlane installation at path:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/bin/fastlane
-----------------------------
[⠋] 🚀 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:101:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:101:in `take_off'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/bin/fastlane:23:in `<main>'
```

### Environment
OS: Windows 10
Ruby version: `ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]`
gem version: 2.6.14
Fastlane version: 2.77.1

```
fastlane env
[⠋] 🚀 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:101:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:101:in `take_off'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/bin/fastlane:23:in `<main>'
```

Any help getting started would be appreciated. Thanks!

**Comment by senoaw** [comment]
any update?

**Comment by senoaw** [comment]
@janpio , yeah I have encountered the same issue as mention by BlakeMccartin. I try so many ways but still come the same problem as above. Thank you very much for your info.

**Comment by janpio** [comment]
As I wrote, fastlane is not supported on Windows yet. I am working on getting it to work, but this work is in a pretty early stage.

**Comment by senoaw** [comment]
@janpio Noted, Thank you :)

**Comment by joshdholtz** [comment]
Going to close this issue for now since fastlane isn't 100% supported on Windows yet 😇
