### ISSUE TITLE
No option to output the results in JSON

### ISSUE THREAD

**Issue by Fudge0952** [fastlane/fastlane#11643]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane pilot list > ~/Desktop/output.txt
>>>>
[19:31:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:31:58]: Login to iTunes Connect (~~~~@~~~~.~~~~)
[19:32:02]: Login successful
+--------------+-------------+-----------------------------------+-----------------------------------+
|                                          All Testers (52)                                          |
+--------------+-------------+-----------------------------------+-----------------------------------+
| First        | Last        | Email                             | Groups                            |
+--------------+-------------+-----------------------------------+-----------------------------------+
| First name   | Last name   | email@address.com.                | ITC.apps.tf.labels.CustomGroup1   |
+--------------+-------------+-----------------------------------+-----------------------------------+
```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C205)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   | en_AU.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
Removed...
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "**ID**" # The bundle identifier of your app
apple_id "**EMAIL**" # Your Apple email address

team_id "**TEAM ID**"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-01-21**
</details>

I've tried poking around the documentation and the files themselves but I haven't been able to locate a way to output the results of a fastlane action as another format such as JSON. The reason this is crucial for me is that I'm trying to create an automation script in which a user enters their details, I verify that the user is valid. Next, I want to verify that the user doesn't already exist in the list of iTunes Connect beta users and if they don't, then I want to add them.

Using the fastlane action pilot as a guide, I was able to manually get the url's required to do this manually and successfully return a list of users using Apple's undocumented API. However, I would rather use fastlane, as it is actively supported and would be quicker (and have more resources than 1 individual) to respond to API changes as Apple is very good at doing.

Does Fastlane already have this support or is it easy enough to create a custom action with this support? I'm not very knowledgeable with Ruby so my poking around was quite limited to random search queries.

**Comment by KrauseFx** [comment]
There is no support for it right now, sorry. You can however export things as CSV as far as I know, and then write a script to convert it over to JSON

**Comment by Fudge0952** [comment]
CSV to JSON is definitely an option. I didn't even know that existed. Thanks @KrauseFx 

For others who stumble across this issue and don't know how to export your testers using this command worked for me:

`pilot export -c ~/Desktop/export.csv`

This command assumes that you are in the current working directory of your project and you have already configured a Appfile, Fastfile, etc.

**Comment by KrauseFx** [comment]
Thanks, glad to hear 👍
