### ISSUE TITLE
Can we create Ad-hoc and Development Certificates Using Fastlane ?

### ISSUE THREAD

**Issue by bhawin-bigstep** [fastlane/fastlane#11649]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by bhawin-bigstep** [comment]
The question is about fastlane functionality , it doesn’t matter what the environment is

**Comment by joshdholtz** [comment]
@bhawin-bigstep Yes, you can create `Development` and `Distribution` certs using fastlane 👌
