### ISSUE TITLE
upload_trailer fails, if you provide no preview_image. simple solution available

### ISSUE THREAD

**Issue by DigitalNerdism** [fastlane/fastlane#11658]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi, 

I am trying to automate the upload of my preview videos for different devices and resolutions. I have written my own upload_action (I am not a ruby expert) but the spaceship upload_trailer! method failed, if you don't pass a preview image. 

The problem is the utility method **portrait?** which has the video_preview_path parameter but this file doesn't exist at this point. I have changed that to trailer_path (from the preview video) and all things seems to working well:

`
   new_trailer = {
            "value" => {
              "videoAssetToken" => trailer_data["responses"][0]["token"],
              "descriptionXML" => trailer_data["responses"][0]["descriptionDoc"],
              "contentType" => upload_file.content_type,
              "sortPosition" => sort_order,
              "size" => video_preview_data["length"],
              "width" => video_preview_data["width"],
              "height" => video_preview_data["height"],
              "checksum" => video_preview_data["md5"],
              "pictureAssetToken" => video_preview_data["token"],
              "previewFrameTimeCode" => ts.to_s,
              "isPortrait" => Utilities.portrait?(trailer_path)  # <== my fix.
              #              "isPortrait" => Utilities.portrait?(video_preview_path)
            }

`
##### Complete output when running fastlane, including the stack trace and command used

Uploading English trailer iphone6Plus for de-DE...
INFO [2018-01-23 08:31:50.58]: -------------------
INFO [2018-01-23 08:31:50.58]: --- Step: slack ---
INFO [2018-01-23 08:31:50.58]: -------------------
INFO [2018-01-23 08:31:51.22]: Successfully sent Slack notification
WARN [2018-01-23 08:31:51.23]: Lane Context:
INFO [2018-01-23 08:31:51.23]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload_previews"}
ERROR [2018-01-23 08:31:51.23]: undefined method `[]' for nil:NilClass
INFO [2018-01-23 08:31:51.23]: Successfully generated documentation at path '/Users/andreclaassen/Projects/yourday/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | opt_out_usage              | 0           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 💥   | upload_trailers            | 127         |
| 5    | slack                      | 0           |
+------+----------------------------+-------------+

ERROR [2018-01-23 08:31:51.25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60[]'%20for%20nil+repo:fastlane/fastlane
➡️  nuke development [!] undefined method `strftime' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11630 [open] 3 💬
    2 days ago

➡️  undefined method `build_settings' for nil:NilClass Error
    https://github.com/fastlane/fastlane/issues/11168 [open] 5 💬
    6 weeks ago

➡️  Type Checking error: got 'Fixnum' for attribute 'fileEncoding' and undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11016 [open] 2 💬
    a week ago

and 319 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/spaceship/lib/spaceship/du/utilities.rb:36:in `portrait?': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/spaceship/lib/spaceship/tunes/app_version.rb:595:in `upload_trailer!'
	from /Users/andreclaassen/Projects/yourday/fastlane/actions/upload_trailers.rb:62:in `block (2 levels) in run'
	from /Users/andreclaassen/Projects/yourday/fastlane/actions/upload_trailers.rb:60:in `each'
	from /Users/andreclaassen/Projects/yourday/fastlane/actions/upload_trailers.rb:60:in `block in run'
	from /Users/andreclaassen/Projects/yourday/fastlane/actions/upload_trailers.rb:45:in `each'
	from /Users/andreclaassen/Projects/yourday/fastlane/actions/upload_trailers.rb:45:in `run'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:63:in `block (2 levels) in parsing_binding'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/andreclaassen/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

### Environment

 Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

    desc "upload trailers to iTunes Connect"
    lane :upload_previews do
      puts "Starting uploadTrailers Lane"
          upload_trailers(app_identifier: "com.andreclaassen.YourDay")
    end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby



# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.3       |
| io-console                | 0.4.5        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.2       |
| coderay                   | 1.1.2        |
| method_source             | 0.9.0        |
| pry                       | 0.11.3       |
</details>

*generated on:* **2018-01-23**
</details>
[08:48:35]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[08:48:35]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)

[INSERT OUTPUT HERE]

**Comment by Chaosspeeder** [comment]
fastlane env is available.
