### ISSUE TITLE
Fastlane 2.78 Error `Gemfile`: unterminated string meets end of file.

### ISSUE THREAD

**Issue by bmwertman** [fastlane/fastlane#11655]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to use beta distribution through the Fabric desktop application. Ran into same issue as @ZubenkoIlya in [issue #11620 Fabric: Can't generate Fastfile: "invalid option: --crashlytics_path" (Regression)](https://github.com/fastlane/fastlane/issues/11620). Uninstalled all fastlane versions via `sudo gem uninstall fastlane` and tried to install at v2.69.2. Version 2.69.2 did not get installed instead got v2.78.0. Running v2.78.0 produces an error relating to the `eval` command on line 10 of my Gemfile as follows;

```
Unknown fastlane error: /Users/Brad/Documents/apparent/Gemfile:10:in `eval':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: unterminated string meets end of file. Bundler cannot continue.

 #  from /Users/Brad/Documents/apparent/Gemfile:10
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
 #  -------------------------------------------
  from /Users/Brad/Documents/apparent/Gemfile:10:in `eval_gemfile'
  from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/dsl.rb:47:in `instance_eval'
  from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/dsl.rb:47:in `eval_gemfile'
  from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/dsl.rb:12:in `evaluate'
  from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:57:in `available_gems'
  from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:64:in `available_plugins'
  from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:279:in `load_plugins'
  from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:39:in `start'
  from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
  from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
  from /usr/local/bin/fastlane:23:in `load'
  from /usr/local/bin/fastlane:23:in `<main>'
```
Unable to run `fastlane` or `fastlane env` without also receiving the above error.

**Comment by KrauseFx** [comment]
Can you share both your `Gemfile`, and your `Pluginfile`?

**Comment by bmwertman** [comment]
Pluginfile contains;
```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-branding'
gem 'fastlane-plugin-cordova'
gem 'fastlane-plugin-ftp
```
Gemfile contains;
```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
```

**Comment by janpio** [comment]
Your `Pluginfile` is missing a `'` in the last line.

**Comment by bmwertman** [comment]
OK, that was that was the cause of that issue. Now I get `Unknown fastlane error: invalid option: --crashlytics_path` which is the original issue I was trying to fix which is the same as [issue #11620 Fabric: Can't generate Fastfile: "invalid option: --crashlytics_path" (Regression)](https://github.com/fastlane/fastlane/issues/11620)

**Comment by KrauseFx** [comment]
Awesome to hear 👍

**Comment by bmwertman** [comment]
@KrauseFx 👍  Thanks for the fast support! Do you have any idea about when issue #11620 may be fixed?
