### ISSUE TITLE
Issue uploading to to Crashlytics all of a sudden.

### ISSUE THREAD

**Issue by gmoalvarez** [fastlane/fastlane#11668]
I have been using fastlane together with Crashlytics without issue for a long time now, but all of a sudden, the Staging version of our build stopped working. I have a QA version of the app that works just fine with almost the same configuration. I am at my wits end trying to figure out what is happening here and can use some help. I could find no log file that describes what is happening with this error but even manually archiving from Xcode and uploading with the Fabric app leads me nowhere. I tried deleting the app from Fabric and bringing it back but that was unsuccessful as well.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying fastlane     | 0           |
|      | version                |             |
| 2    | default_platform       | 0           |
| 3    | Switch to ios          | 0           |
|      | cert_staging lane      |             |
| 4    | match                  | 12          |
| 5    | Switch to ios          | 0           |
|      | build_staging lane     |             |
| 6    | gym                    | 258         |
| 7    | upload_symbols_to_bug  | 0           |
|      | see                    |             |
| 8    | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 💥   | crashlytics            | 6           |
+------+------------------------+-------------+

[19:29:09]: fastlane finished with errors

[!] 2018-01-22 19:29:02.329 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2018-01-22 19:29:08.357 submit Crashlytics: Unable to add release notes. Response code: 500
2018-01-22 19:29:08.358 submit Crashlytics: Failed to add notes to the release

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.18.3"

default_platform :ios

before_all do  
 ENV["SLACK_URL"] = "***"
 ENV["BUGSEE_APP_TOKEN_DEV"] = "***"
 ENV["BUGSEE_APP_TOKEN_QA"] = "***"
 ENV["BUGSEE_APP_TOKEN_STAGING"] = "***"
end

platform :ios do

  lane :cert_staging do |values|
    match(app_identifier: ***',
      username: '***', 
      type: 'adhoc',
      git_url: 'https://bitbucket.org/teamesub/certificates.git',
      force_for_new_devices: true,
      'readonly': true
     )
  end

  lane :build_staging do |values|
  	gym(
      workspace: "shasta.iOS.xcworkspace",
      scheme: 'Staging',
      silent: true,
      configuration: 'Release',
      export_method: 'ad-hoc',
      codesigning_identity: 'iPhone Distribution: eSUB Inc. (49E9T84QH3)',
      skip_profile_detection: true,
      output_name: 'Time Staging',
      export_options: {
        provisioningProfiles: {
          "com.esub.time-staging": "match AdHoc com.esub.time-staging"
        },
        compileBitcode: false,
        installerSigningCertificate: 'iPhone Distribution: eSUB Inc. (49E9T84QH3)',
        signingCertificate: 'iPhone Distribution: eSUB Inc. (49E9T84QH3)',
        signingStyle: 'manual',
        method: 'ad-hoc',
        teamID: '49E9T84QH3',
      }
    )
  end

  lane :staging do |values|

    cert_staging

    build_staging
    
    upload_to_testflight
    
    upload_symbols_to_bugsee( app_token: ENV["BUGSEE_APP_TOKEN_STAGING"] )  

    emails = values[:test_email] ? values[:test_email] : [
      ...***...
    ]

    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    notes = changelog_from_git_commits(
      commits_count: 20,
      pretty: "- (%ae) %s",
      merge_commit_filtering: 'exclude_merges'
    )

    crashlytics(
      api_token: '***',
      build_secret: '***',
      emails: emails,
      groups: groups,
      notes: notes,
      ipa_path: './Time Staging.ipa',
      notifications: true
    ) 

  end

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-bugsee | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| CFPropertyList                         | 2.3.5        |
| addressable                            | 2.5.2        |
| babosa                                 | 1.0.2        |
| bigdecimal                             | 1.2.6        |
| bundler                                | 1.14.6       |
| claide                                 | 1.0.2        |
| colored                                | 1.2          |
| colored2                               | 3.1.2        |
| commander-fastlane                     | 4.4.5        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| domain_name                            | 0.5.20170404 |
| dotenv                                 | 2.2.1        |
| excon                                  | 0.59.0       |
| faraday                                | 0.13.1       |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.11.0.1     |
| fastimage                              | 2.1.0        |
| fastlane-plugin-bugsee                 | 1.0.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| gh_inspector                           | 1.0.3        |
| google-api-client                      | 0.13.5       |
| googleauth                             | 0.5.1        |
| highline                               | 1.7.8        |
| http-cookie                            | 1.0.3        |
| httpclient                             | 2.8.3        |
| hurley                                 | 0.2          |
| io-console                             | 0.4.3        |
| json                                   | 1.8.1        |
| jwt                                    | 1.5.6        |
| libxml-ruby                            | 3.0.0        |
| little-plugger                         | 1.1.4        |
| logging                                | 2.2.2        |
| memoist                                | 0.16.0       |
| mime-types                             | 3.1          |
| mime-types-data                        | 3.2016.0521  |
| mini_magick                            | 4.5.1        |
| minitest                               | 5.4.3        |
| multi_json                             | 1.12.2       |
| multi_xml                              | 0.6.0        |
| multipart-post                         | 2.0.0        |
| nanaimo                                | 0.2.3        |
| nokogiri                               | 1.5.6        |
| os                                     | 0.9.6        |
| plist                                  | 3.3.0        |
| power_assert                           | 0.2.2        |
| psych                                  | 2.0.8        |
| public_suffix                          | 2.0.5        |
| rake                                   | 10.4.2       |
| rdoc                                   | 4.2.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.1        |
| rouge                                  | 2.0.7        |
| rouge                                  | 1.11.1       |
| rubygems-update                        | 2.5.2        |
| rubyzip                                | 1.2.1        |
| security                               | 0.1.3        |
| signet                                 | 0.7.3        |
| slack-notifier                         | 2.3.2        |
| slack-notifier                         | 1.5.1        |
| sqlite3                                | 1.3.13       |
| terminal-notifier                      | 1.8.0        |
| terminal-table                         | 1.7.3        |
| test-unit                              | 3.0.8        |
| tty-cursor                             | 0.5.0        |
| tty-screen                             | 0.6.4        |
| tty-spinner                            | 0.8.0        |
| uber                                   | 0.1.0        |
| unf                                    | 0.1.4        |
| unf_ext                                | 0.0.7.4      |
| unicode-display_width                  | 1.3.0        |
| unicode-display_width                  | 1.1.3        |
| word_wrap                              | 1.0.0        |
| xcodeproj                              | 1.5.3        |
| xcov                                   | 1.3.0        |
| xcpretty                               | 0.2.6        |
| xcpretty-travis-formatter              | 0.0.4        |
</details>

*generated on:* **2018-01-22**
</details>

**Comment by gmoalvarez** [comment]
I was able to contact Crashlytics support and they resolved the issue on their backend. Not sure what was broken but... it is fixed! I am back in business!

**Comment by KrauseFx** [comment]
Glad to hear :+1:
