### ISSUE TITLE
match doesn't renew the signing certificate automatically after the certificate expires

### ISSUE THREAD

**Issue by ISCHI** [fastlane/fastlane#11663]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
An expired signing certificate is automatically removed from the Apple Developer Center. After the expiring date match breaks with the following error:
```
[13:08:23]: Certificate 'xyz' (stored in your git repo) is not available on the Developer Portal  
[13:08:23]: for the user xyz  
[13:08:23]: Make sure to use the same user and team every time you run 'match' for this  
[13:08:23]: Git repository. This might be caused by revoking the certificate on the Dev Portal
```

I used fastlane with version 2.77.1.

### Expected Behaviour
match automatically recreates signing certificates if they don't exist and regenerates corresponding provisioning profiles etc. This includes certificate expiration and deletion/revoke in the development center.

**Comment by KrauseFx** [comment]
Do you remember, did this work in the past for you, or did no certificate expire before?

**Comment by ISCHI** [comment]
This is the first expiring certificate since we are using match.

**Comment by danilobuerger** [comment]
Same issue, using `--force` doesn't seem to work, had to resort to nuke :(

**Comment by alexmaslov** [comment]
Same issue. expiring certificates don't get renewed, but remain in the match repo until manually removed.

**Comment by robmaceachern** [comment]
This is still an issue for me on Fastlane 2.94.0

**Comment by joshdholtz** [comment]
Will add this to my list of things to look into 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mbuchetics** [comment]
We just experienced this issue as well.

**Comment by mbuchetics** [comment]
This is not fixed, this is still happening. What activity do you want, @fastlane-bot ??

**Comment by garylai** [comment]
Instead of just select the last cert in the directory: https://github.com/fastlane/fastlane/blob/master/match/lib/match/runner.rb#L106
maybe it can loop through the certs and select the first one that is not expired? And if it cannot find one then generate a new cert?

**Comment by peterromfeldhk** [comment]
we just got a email that our cert will expire in 30 days, i looked but there is no documentation for cert renewal using match. i guess the workaround would be to a `nuke` if it doesn't renew/recreate it

**Comment by ngreeney** [comment]
Running into the same issue here. Might resort to killing out repo and trying to get match to start over with a clean slate.

**Comment by eimantas** [comment]
We just hit this same issue. We're considering the `nuke` option as the response doesn't look like happening in the nearest future and we can't wait with the release train.

**Comment by mbuchetics** [comment]
This is still a major issue and we just ran into it again ... certificate expired but it's not getting renewed.

**Comment by ngreeney** [comment]
@eimantas and @mbuchetics - Still an issue for me as well but my work around for it was to manually delete the certificate on developer.apple.com and then deleted the repo that Match was using. Then made sure all the Match commands had the Force which recreated the cert as well as new provisioning profiles to match the cert.

Would be nice if this was done by Match rather than needing to get into a clean slate for this to work though.

**Comment by Felipe-Banno** [comment]
We are also having this issue. Any plans to fix it?
