### ISSUE TITLE
Can not set development team directly using update_project_provisioning in XCode 8 project

### ISSUE THREAD

**Issue by wischweh** [fastlane/fastlane#11667]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

update_team seems to have no effect.

I am trying to build, sign & deploy an cordova (6.5.0) project using fastlane. However i am having issues signing the app because i can not set the development team using update_team. It reports a success though but before and after the run the team is not set in XCode.

In XCode it looks like this (before and after)
```
XCode -> NDR SH -> General 
Signing (Debug)
Provisoning Profile [match Development de.ndr.app.ndrsh]
Team None
Signing Certificate None

Status (!) Signing for "NDR SH" requires a development team

Signing (Release)
Provisoning Profile [None]
Team None
Signing Certificate None
```

My XCode-Project is in old format generated by Cordova, but was already successfully was transformed to XCode 8 Format using upgrade_super_old_xcode_project. 

Here is my lane:
```
 team_id = "7W67UV9JF4" # Developer Portal Team ID
  lane :team do
      update_project_team(teamid: team_id)
  end
```
##### Complete output when running fastlane, including the stack trace and command used

fastlane could not check for updates error: 407 "authenticationrequired"
[17:39:24]: fastlane detected a Gemfile in the current directory
[17:39:24]: however it seems like you don't use `bundle exec`
[17:39:24]: to launch fastlane faster, please use
[17:39:24]: 
[17:39:24]: $ bundle exec fastlane team --capture_output
[17:39:24]: 
[17:39:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-01-23 17:39:24.75]: Checking if there are any plugins that should be loaded...
DEBUG [2018-01-23 17:39:24.81]: Loading 'fastlane-plugin-upgrade_super_old_xcode_project' plugin
INFO [2018-01-23 17:39:24.81]: gem 'fastlane-plugin-upgrade_super_old_xcode_project' is already installed
INFO [2018-01-23 17:39:25.12]: ------------------------------
INFO [2018-01-23 17:39:25.12]: --- Step: default_platform ---
INFO [2018-01-23 17:39:25.12]: ------------------------------
INFO [2018-01-23 17:39:25.12]: Driving the lane 'ios team' 🚀
INFO [2018-01-23 17:39:25.14]: ---------------------------------
INFO [2018-01-23 17:39:25.14]: --- Step: update_project_team ---
INFO [2018-01-23 17:39:25.14]: ---------------------------------
INFO [2018-01-23 17:39:25.14]: Updating development team (7W67UV9JF4) for the given project 'NDR SH.xcodeproj/project.pbxproj'
INFO [2018-01-23 17:39:25.14]: Successfully updated project settings to use Developer Team ID '7W67UV9JF4'
INFO [2018-01-23 17:39:25.14]: Successfully generated documentation at path '/Users/wischwehj/workspace/app-baukasten-sh/platforms/ios/fastlane/README.md'
INFO [2018-01-23 17:39:25.15]: fastlane.tools finished successfully 🎉

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

app_identifier = "de.ndr.app.ndrsh"
xcode_path = "NDR SH.xcodeproj"

team_id = "7W67UV9JF4" # Developer Portal Team ID
profile_uuid = "e1feaa38-be42-4ebf-8f94-bdb76b0edea1"
signing_id = "iPhone Developer: ios-apps OSC (PTG4K5V3VE)"

platform :ios do

  lane :fixCordova do
      upgrade_super_old_xcode_project(
        path: xcode_path,
        team_id: team_id
        )
  end

  lane :upgrade_xcode do
    upgrade_super_old_xcode_project(
            path: xcode_path,
            team_id: team_id
            )
  end;

  lane :profile_development do
    match(type: "development")
    profile_development_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_development_profile-path'])
    update_project_provisioning(
      build_configuration: "Debug",
      profile: profile_development_path
    )

  end

  lane :gymit do
    gym(
    scheme: "NDR SH",
    codesigning_identity: signing_id,
    xcargs: "PROVISIONING_PROFILE_SPECIFIER='match AppSto de.ndr.app.ndrsh'"
    )
  end

  lane :profile_appstore do
    match(type: "appstore")
    profile_appstore_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path'])
    update_project_provisioning(
    build_configuration: "Release",
    profile: profile_appstore_path)
  end

  lane :team do
      update_project_team(teamid: team_id)
  end

  lane :enable do
    enable_automatic_code_signing(
            path: xcode_path,
            team_id: team_id
          )
  end

  lane :disable do
    match(type: "appstore", readonly: true)
    profile_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path'])
    sign_id = ENV['sigh_de.ndr.app.ndrsh_appstore']
    disable_automatic_code_signing(
            path: xcode_path,
            team_id: team_id,
            # code_sign_identity: "iPhone Distribution",
            code_sign_identity: signing_id,
            profile_uuid: sign_id
          )
  end

  lane :signing do
    match(type: "appstore", readonly: true)
    profile_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path'])
    sign_id = ENV['sigh_de.ndr.app.ndrsh_appstore']
    update_project_code_signing(
      path: xcode_path,
      uuid: sign_id
    )

  end

  lane :xcode_developmentteam do
      match(type: "development", readonly: true)
      profile_development_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_development_profile-path'])
      profile_development_name = ENV['sigh_de.ndr.app.ndrsh_development_profile-name']
      sign_development_name =    ENV['sigh_de.ndr.app.ndrsh_development_profile-name']
      xcodebuild(
        scheme: "NDR SH",
        build_settings: {
          "CODE_SIGN_IDENTITY" => sign_development_name,
          "PROVISIONING_PROFILE" => profile_development_name,
          "DEVELOPMENT_TEAM" => profile_development_path
        }
      )
    end

  lane :build do
    match(type: "appstore", readonly: true)
    profile_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path'])
    profile_name = ENV['sigh_de.ndr.app.ndrsh_appstore_profile-name']
    sign_name = ENV['sigh_de.ndr.app.ndrsh_appstore_profile-name']
    xcodebuild(
      scheme: "NDR SH",
      build_settings: {
        "CODE_SIGN_IDENTITY" => sign_name,
        "PROVISIONING_PROFILE" => profile_name,
        "DEVELOPMENT_TEAM" => team_id
      }
    )
  end

  lane :build2 do
  gym(
      export_method: 'app-store',
      scheme: 'NDR SH',
      export_team_id: team_id
  )
  end


  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    match(readonly: true)
    provisioning_path = ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path']
    # .mobileprovision outside of this folder seem to cause problems, so we copy them here
    # sh("rm .mobileprovision")
    profile_path = File.expand_path(ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path'])
    # sh("cp \"" + profile_path  + "\" ../fastlanebuild.mobileprovision")
    disable_automatic_code_signing(
            path: xcode_path,
            team_id: team_id
          )
    update_project_team(teamid: team_id)
    update_project_provisioning(profile: profile_path)
    gym
    upload_to_testflight
  end

  lane :betaDeprecated do
      # add actions here: https://docs.fastlane.tools/actions
      match(readonly: true)
      update_project_team(teamid: "7W67UV9JF4")
      provisioning_path = ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path']
      # sh("cp provisioning_path .mobileprovision")
      # update_project_provisioning(profile: ".mobileprovision")
      update_project_code_signing(
        path: xcode_path,
        uuid: profile_uuid
      )
      gym
    end

    lane :keys do
      match(readonly: true)
      sh("echo app_identifier: "+app_identifier)
      sh("echo team_id: "+team_id)


      sh("echo profile_uuid: "+profile_uuid)
      sh("echo xcode_path: "+xcode_path)
      sh("echo sigh_de.ndr.app.ndrsh_appstore_profile-path: "+ENV['sigh_de.ndr.app.ndrsh_appstore_profile-path'])
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "[[APP_IDENTIFIER]]" # The bundle identifier of your app
# apple_id "[[APPLE_ID]]" # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.76.1  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                          | Version | Update-Status  |
| ----------------------------------------------- | ------- | -------------- |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                             | Version      |
| ----------------------------------------------- | ------------ |
| slack-notifier                                  | 2.3.2        |
| claide                                          | 1.0.2        |
| colored2                                        | 3.1.2        |
| nanaimo                                         | 0.2.3        |
| xcodeproj                                       | 1.5.4        |
| rouge                                           | 1.11.1       |
| xcpretty                                        | 0.2.6        |
| unicode-display_width                           | 1.1.3        |
| terminal-table                                  | 1.7.3        |
| multipart-post                                  | 2.0.0        |
| word_wrap                                       | 1.0.0        |
| public_suffix                                   | 2.0.5        |
| tty-screen                                      | 0.6.4        |
| tty-cursor                                      | 0.5.0        |
| tty-spinner                                     | 0.8.0        |
| babosa                                          | 1.0.2        |
| colored                                         | 1.2          |
| commander-fastlane                              | 4.4.5        |
| unf_ext                                         | 0.0.7.4      |
| unf                                             | 0.1.4        |
| domain_name                                     | 0.5.20170404 |
| http-cookie                                     | 1.0.3        |
| faraday-cookie_jar                              | 0.0.6        |
| gh_inspector                                    | 1.0.3        |
| json                                            | 1.8.1        |
| mini_magick                                     | 4.5.1        |
| multi_xml                                       | 0.6.0        |
| rubyzip                                         | 1.2.1        |
| security                                        | 0.1.3        |
| xcpretty-travis-formatter                       | 0.0.4        |
| bundler                                         | 1.14.6       |
| faraday_middleware                              | 0.11.0.1     |
| declarative                                     | 0.0.10       |
| declarative-option                              | 0.1.0        |
| representable                                   | 3.0.4        |
| mime-types-data                                 | 3.2016.0521  |
| mime-types                                      | 3.1          |
| little-plugger                                  | 1.1.4        |
| logging                                         | 2.2.2        |
| jwt                                             | 1.5.6        |
| os                                              | 0.9.6        |
| signet                                          | 0.7.3        |
| googleauth                                      | 0.5.1        |
| httpclient                                      | 2.8.3        |
| google-api-client                               | 0.13.6       |
| highline                                        | 1.7.10       |
| excon                                           | 0.60.0       |
| CFPropertyList                                  | 2.3.6        |
| libxml-ruby                                     | 3.0.0        |
| plist                                           | 3.4.0        |
| faraday                                         | 0.13.1       |
| fastimage                                       | 2.1.1        |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2        |
</details>

*generated on:* **2018-01-23**
</details>

**Comment by punksta** [comment]
Had a same problem.
this action should help https://docs.fastlane.tools/actions/automatic_code_signing/ with this fix https://github.com/fastlane/fastlane/pull/11852
