### ISSUE TITLE
Get ios/mac builds 

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [fastlane/fastlane#11666]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am using Fastlane to get builds from the iTunesConnect and  found a difference in its behavior.
```
version = app.latest_version.version 
trains = app.build_trains
```
I found that `build_trains ` is not empty only for application which has build in the TestFlight. If you didn't upload any builds to the TestFlight but have a build in the Activity - you will receive empty array. How can I get builds from the "Activity"? 
This question is also actual to macOS builds because we don't have an opportunity to use TestFlight with osx builds.

Link to find builds should be like this:  https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/{application_id}/activity/ios/builds

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.77.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| faraday                   | 0.14.0       |
| json                      | 2.1.0        |
| rubyzip                   | 1.2.1        |
| bundler                   | 1.16.1       |
| openssl                   | 2.1.0        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2018-01-23**
</details>

**Comment by mykyta-bondarenko-gl** [comment]
![image](https://user-images.githubusercontent.com/32954580/35287092-449f9758-006a-11e8-96a7-46c500ae6575.png)
It's what I mean when writing "Activity" and "Testflight" tabs.

**Comment by KrauseFx** [comment]
I actually don't know, it might not be possible with spaceship right now. You could [inspect the network traffic](https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md) and see if this is implemented if you want :)

**Comment by mykyta-bondarenko-gl** [comment]
@KrauseFx I undastand you, thanks. 
Am I right that it's not possible to get macOS application too? 
As you know we can't use TestFlight for mac applications. So I can get only latest version from the `Activity` tab via `latest_version` but can't get `build_trains` (because this functianality works only with TestFlight)

**Comment by mykyta-bondarenko-gl** [comment]
Can someone explain me how does it work? I have am application. It contains next tabs
1. TestFlight
   - version 4.76 build 1.68
2. Activity
   - version 4.76 build 1.68
   - version 1.0 build 1.0 and 1.1
   - version 13.0 build 1.0

`latest_version` returns 1.0
`builds` returns array with 1 element. It's version 4.76 build 1.68 
`build_trains` returns a dictionary - [ 4.76, [4.68] ]

@KrauseFx Can you give me a hit with this? 
Thank you!

**Comment by joshdholtz** [comment]
@mykyta-bondarenko-gl Heyyyy 👋 Were you able to figure things out?

**Comment by mykyta-bondarenko-gl** [comment]
@joshdholtz Hi. I went in a few another way.
Now I use two properties:
- `build_trains`
- `candidate_builds`
In the second case I sorted and groupped them and get the latest one. This cases cover all that I need.

**Comment by joshdholtz** [comment]
Perfect! Glad you got it solved. Happy fastlaning 🚀
