### ISSUE TITLE
Detected values through init command are incorrect and no obvious work around is present

### ISSUE THREAD

**Issue by pundegreen** [fastlane/fastlane#1167]
In the last version (1.52.0) version, when I run `fastlane init`, the `Detected Values` are incorrect. It also suggests that it will create the incorrectly found project automatically in the Apple Developer portal. When hitting `n` for `Please confirm the above value`, setup terminates. I realize the project I am dealing with might have a weird setup but there should be a way to manually enter values, like in the previous versions. As is, I am unable to set it up using `fastlane init` command.

**Comment by AngeloGiurano** [comment]
I have the same issue here, it detects Bolts as my App Name and doesn't detect any App Identifier, when obviously my app is on iTunesConnect and I use TestFlight with success every time.

**Comment by Athosone** [comment]
Same here.... can't manage to make it work

**Comment by AngeloGiurano** [comment]
@Athosone I've downgraded to 1.51.0 and you can insert App ID and App Name manually and it worked

**Comment by Athosone** [comment]
Yeah did it too it solved the bug

**Comment by pundegreen** [comment]
yea, had to revert to `1.51.0` version too - def. need an option to manually manage values!

**Comment by jxbambrick** [comment]
I've had some luck on this front. I opened the log file and noticed that I was getting an error: fastlane/setup/setup_ios.rb: ln:110. I replaced self.app_identifier with my bundle identifier and was able to get past the problem. Editing the project files probably isn't the solution your looking for nor would I advise it. One other solution that I found was to change the bundle identifier in xcode then clean and build. When I ran fastlane init a second time,  the app identifier was correctly populated.

**Comment by ohwutup** [comment]
hi everyone! i will be making a change in the next couple of days to add back in the manual onboarding if you don't like the selected values that are chosen for you! in the mean time, you should be able to use the most recent version of fastlane and just manually create your Fastfile and optionally, any fastlane files and fastlane directory.

**Comment by lijie94** [comment]
@jxbambrick is right. Changing the bundle id and doing a clean and build works.

**Comment by ohwutup** [comment]
hi everyone! just released a fix for this, if you answer no to the values fastlane detects, you will be routed through the manual onboarding! https://github.com/fastlane/fastlane/releases/tag/1.54.0

going to close this for now, feel free to open new issues if they come up! thank you all for your patience!

**Comment by biolinh** [comment]
Hi, I have just updated fastlane  to 1.55.0, it means that the error fixed but I still get the error:
fastlane-1.55.0/lib/fastlane/setup/setup_ios.rb:154:in `gsub!': [!] no implicit conversion of nil into String (TypeError)

I clean up the project and try three times to run fastlane init but it is no luck, the error still show.

**Comment by KrauseFx** [comment]
@biolinh can you share the complete output when running `fastlane init`, including the values you entered.

**Comment by benkane** [comment]
With version 1.55.0, the App Identifier wasn't detected for me. I'm guessing this is because "App Name" was detected as "Pods" instead of my App Name, so it probably grabbed the wrong target. I was able to enter a value for "App Identifier", but not "App Name", which worries me. I don't know what the desired behavior actually is. It's possible that it's normal to see Pods for a Detected Value. I'm guessing it's not though, since it offered to create the app in ITC even though it already exists.

**Comment by biolinh** [comment]
@ohwutup Here is full output:
# fastlane init
[17:32:50]: Detected iOS/Mac project in current directory...
[17:32:50]: This setup will help you get up and running in no time.
[17:32:50]: fastlane will check what tools you're already using and set up
[17:32:50]: the tool automatically for you. Have fun!
[17:32:50]: Created new folder './fastlane'.
[17:32:50]: xcrun xcodebuild -list -workspace './myproject.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com): linh.nguyen@mydomain
[17:33:05]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[17:33:05]: Starting login with user 'linh.nguyen@mydomain'

+----------------+----------------------------------------------------------------------------+
|                                       Detected Values                                       |
+----------------+----------------------------------------------------------------------------+
| Apple ID       | linh.nguyen@mydomain                                                    |
| App Name       | myproject                                                                 |
| App Identifier |                                                                            |
| Workspace      | path_to_my_projects.xcworkspace |
+----------------+----------------------------------------------------------------------------+

[17:33:15]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[17:33:15]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
y
[17:33:17]: Error occurred with the setup program! Reverting changes now!
[17:33:17]: Deleting the 'fastlane' folder
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
[17:33:22]: undefined method `message' for nil:NilClass
/Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/lib/fastlane/setup/setup_ios.rb:154:in `gsub!': [!] no implicit conversion of nil into String (TypeError)
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/lib/fastlane/setup/setup_ios.rb:154:in `generate_appfile'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/lib/fastlane/setup/setup_ios.rb:50:in `default_setup'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/lib/fastlane/setup/setup_ios.rb:33:in `run'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/bin/fastlane:150:in `run'
	from /Users/linh/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.55.0/bin/fastlane:156:in `<top (required)>'
	from /Users/linh/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/linh/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/linh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/linh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ohwutup** [comment]
hey @biolinh, it looks like fastlane is not detecting an `app_identifier` for your project so that is likely the issue here. if you answer `n` instead of `y` when it asks to confirm the values, you will have a chance to manually enter the `app_identifier`. let me know how that goes!

**Comment by KrauseFx** [comment]
@biolinh Could you also update fastlane core using `sudo gem update fastlane_core`?

**Comment by biolinh** [comment]
@ohwutup: thank you for your quick response. Just did as you said, answer n and It run ok. Because my Bundle ID is specified in workspace so I only choose y. 

@KrauseFx: after I did as ohwutup said, I got the notify about new tag version 1.56.0 and I have just updated it.

**Comment by ohwutup** [comment]
great! let us know if you have any more issues @biolinh !
