### ISSUE TITLE
[Scan] Is possible to stop all tests when first UITest fails?

### ISSUE THREAD

**Issue by brduca** [fastlane/fastlane#11672]
### Issue Description

Basically what I need is to stop the UITests when the first one fails. I'm using Jenkins with Fastlane Scan. (It's not a Bug)

I have the option to continue after failure disabled (but it only prevents this specific test to continue):

```
override func setUp() {
...        
    continueAfterFailure = false
...
}
```
My scan file contains the option to "fail_build" true.
But it keeps running even when the first on fails.
Is it even possible using a Scanfile or another option, I couldn't find it on scan docs? 

Thanks in advance.

**Comment by KrauseFx** [comment]
Does the `stop_after_first_error` option do what you want?

**Comment by brduca** [comment]
I really can't see that on the scan file options. Does it exists?

**Comment by taquitos** [comment]
Ahhh for `scan`, no, right now we just have it for `snapshot` 😞

**Comment by brduca** [comment]
Ok, thanks anyway.
