### ISSUE TITLE
Spaceship Access to build_trains errors out when switching users

### ISSUE THREAD

**Issue by kylemellander** [fastlane/fastlane#11686]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have a fastlane script that manages multiple builds of an app that spans multiple itunes accounts.  We need to use spaceship to check the builds and versions across all the apps to make sure that they are in sync.  We run a check using spaceship, in which we fetch the build_trains and versions as well as the live versions.  When running this on the first run through it works fine, and with any subsequent requests that are using the same username/password.  When we switch username and password for another account, it breaks, returning a 500 error.

To reach this error, I run:

```
    Spaceship::Tunes.login(my_username, my_password)
    Spaceship::Tunes.select_team
    version1 = Spaceship::Tunes::Application.find(my_app_id)
    version1.build_trains
    Spaceship::Tunes.login(my_other_username, my_other_password)
    Spaceship::Tunes.select_team
    version2 = Spaceship::Tunes::Application.find(my_other_app_id)
    version2.build_trains
```

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/kylemellander/.fastlane/bin/bundle/lib/ruby/2.2.0/json/common.rb:155:in `parse': [!] 776: unexpected token at '<!DOCTYPE html><html lang="en"> (Faraday::ParsingError)
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="http://www.apple.com/legal/internet-services/itunes/us/terms.html">Terms of Service</a></li><li><a href="http://www.apple.com/legal/privacy">Privacy Policy</a></li><li><a href="http:$
/www.apple.com/support/">Contact Us</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/2.2.0/json/common.rb:155:in `parse'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:50:in `call'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:50:in `parse'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.2/lib/faraday/response.rb:61:in `on_complete'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/client.rb:684:in `block in send_request'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/client.rb:519:in `with_retry'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/client.rb:683:in `send_request'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/client.rb:571:in `request'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/test_flight/client.rb:29:in `get_build_trains'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/test_flight/build_trains.rb:16:in `all'
        from /Users/kylemellander/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/spaceship/lib/spaceship/tunes/application.rb:276:in `build_trains'
        from utils/versioning.rb:180:in `serialize_itunes_version'
        from utils/versioning.rb:193:in `set_itunes_version'
        from utils/versioning.rb:147:in `block (2 levels) in load_itunes_versions'
        from utils/versioning.rb:145:in `each'
        from utils/versioning.rb:145:in `block in load_itunes_versions'
        from utils/versioning.rb:144:in `each'
        from utils/versioning.rb:144:in `load_itunes_versions'
        from utils/versioning.rb:109:in `itunes_versions'
        from utils/versioning.rb:116:in `latest_build_number'
        from utils/versioning.rb:15:in `increment_build'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.77.0'

fastlane_require 'security'
fastlane_require 'shellwords'
fastlane_require 'yaml'
fastlane_require 'spaceship'

lane :check_builds do |_|
    Spaceship::Tunes.login(my_username, my_password)
    Spaceship::Tunes.select_team
    version1 = Spaceship::Tunes::Application.find(my_app_id)
    version1.build_trains
    Spaceship::Tunes.login(my_other_username, my_other_password)
    Spaceship::Tunes.select_team
    version2 = Spaceship::Tunes::Application.find(my_other_app_id)
    version2.build_trains
end

# personal information containing username/password/app_ids are removed for obscurity
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier 'OBSCURE' # The bundle identifier of your app
apple_id 'OBSCURED'

team_id "OBSCURED" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| escape                    | 0.0.4        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-cordova   | 0.2.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.6        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| method_source             | 0.9.0        |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.3.0        |
| power_assert              | 0.2.2        |
| pry                       | 0.11.3       |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| sh                        | 0.0.2        |
| signet                    | 0.7.3        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-spinner               | 0.8.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.1.0        |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.3.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.2.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-01-24**
</details>

**Comment by joshdholtz** [comment]
@kylemellander This should be fixed now with #11970 (in 2.85.0). It tested your example above it and it worked perfectly 👌
