### ISSUE TITLE
iTMSTransporter Upload iMessage Screenshots

### ISSUE THREAD

**Issue by fishandphil** [fastlane/fastlane#11681]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

How are you dealing with iMessage Screenshot when uploading wit iTMSTransporter in upload mode. 
How do you format the screenshots in the XML.
 
It doesn't seem to be documented in neither:
 
https://help.apple.com/itc/transporteruserguide/
http://help.apple.com/itc/appsspec/
 
We found that FastLane is using the following "display_target" (https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/app_screenshot.rb)
 
iOS-3.5-in-messages
iOS-4-in-messages
iOS-4.7-in-messages
..
 
Such as:
 
<software_screenshot display_target="iOS-5.5-in-messages" position="1">
  <size>851668</size>
  <file_name>en-US_iMessage_iPhone_6Plus_01.jpg</file_name>
  <checksum type="md5">89f5e1ccb71a25c9f0b57b63270c0961</checksum>
</software_screenshot>
 
However, we try the following error when doing using the Verify mode of iTMSTransporter:
 
ERROR ITMS-3000: "Line 646 column 80: value of attribute "display_target" is invalid; must be equal to "Mac", "appletvos", "iOS-3.5-in", "iOS-4-in", "iOS-4.7-in", "iOS-5.5-in", "iOS-5.8-in", "iOS-Apple-Watch", "iOS-iPad", "iOS-iPad-Pro" or "iOS-iPad-Pro-10.5-in" at XPath /package/software/software_metadata/versions/version/locales/locale[22]/software_screenshots/software_screenshot[5]"
 
Any clue?
We used to be using FastLane Deliver for our product which contains an iMessage App. However, FastLane stopped working in upload mode a while back. We already posted an issue which was unsolved. This is why we are now starting to look directly into iTMSTransporter.. Maybe you got the issue too?

**Comment by KrauseFx** [comment]
We upload iMessage screenshots using _spaceship_, check out the code here: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/du/du_client.rb#L60

**Comment by KrauseFx** [comment]
So we don't use iTunes Transporter for metadata, just for binaries

**Comment by fishandphil** [comment]
Ah thank you. I thought you used the iTMSTransporter. 

Does that mean you are using this ITC API ? : https://github.com/fastlane/itc-api-docs 

I wished iTMSTransporter supported iMessage Screenshot. Shame! 
Thank you for the information

**Comment by JustinJiaDev** [comment]
Yes spaceship is used. I believe the ITC doc didn’t include iMessge screenshots APIs. When I was implementing that feature I spent quick some time figuring out the Apple API, but I was lazy and didn’t send a pull request to update the doc. You should check the source code instead of the ITC doc.

**Comment by KrauseFx** [comment]
We're using https://spaceship.airfoce 👍

**Comment by KrauseFx** [comment]
Yep, check out the spaceship source code, it includes all of that
