### ISSUE TITLE
Non-macOS platform support (Windows + Linux)

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11687]
We are actively working on 🐧 Linux and 🖥️ Windows support for parts of _fastlane_. Many tools and actions of fastlane can theoretically also work on these platforms. Some underlying software like Xcode or iTunes Transporter was originally made and only available for macOS, but [Linux and Windows versions now seem to be available](https://github.com/fastlane/fastlane/issues/11687#issuecomment-595990307). 

While we can't give a timeline or ETA, we are seeing good progress and want to start to connect to interested people. Please comment on this issue to indicate your interest and we will publish here when we have something to test.

If you have a need for Windows or Linux support for specific tool or action, please let us know as well so we can prioritize the implementation and testing.

**Comment by AlexZezekalo** [comment]
Cool! Awaiting for ubuntu 16.04

**Comment by ozmaat** [comment]
Look forward for Windows support....

**Comment by feinstruktur** [comment]
Would it be possible to package fastlane as a docker image? That way it could presumably easily integrated into various build pipelines (GitLab, BitBucket).

Happy to try and help - is there a good place to start and have a look around?

**Comment by janpio** [comment]
Uh, I have 0 experience with Docker - but sounds interesting. Best create a new issue "Package fastlane as docker image" and keep a log of your investigation. First thing I would do is to find other CLI tools that are delivered as a docker image and find out how they did it.

**Comment by gnolmon** [comment]
Look forward for Windows support.... :D thanks you

**Comment by simonbuchan** [comment]
We've run fastlane on gitlab's docker, it's pretty trivial to add, e.g. `RUN apt-get-install -y ruby && gem install fastlane -NV` to a Dockerfile - the real problem is having the android SDK with the right packages installed for your app.

**Comment by KellyHannemann** [comment]
I look forward to Windows support. Would like to use fastlane with xamarin for android and ios, anyone who has tried this?

**Comment by Purus** [comment]
+1 for Windows Support.

**Comment by hjanuschka** [comment]
@feinstruktur in fact i am using fastlane running inside a docker - (with socket mount) to build docker containers 👍 


```
FROM ruby:2.4-stretch

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

RUN mkdir ~/.ssh/
RUN ssh-keyscan -t rsa gitlab.krone.at >> ~/.ssh/known_hosts

RUN export LANG=en_US.UTF-8
RUN LANGUAGE=en_US.UTF-8
RUN LC_ALL=en_US.UTF-8
RUN gem install fastlane gitlab fastlane-plugin-docker semantic rest-client sentry-api

# ADD Docker itself
RUN apt-get update
RUN apt-get install -y \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
      $(lsb_release -cs) \
         stable"

RUN apt-get update
RUN apt-get install -y docker-ce
```



inside the `fastlane_runner` docker i use https://github.com/milch/fastlane-plugin-docker to build another docker container. (❤️ ci worker running in docker, running fastlane in docker, building docker containers, docker inception 🚀 )

**Comment by silwar** [comment]
Looking forward to Ubuntu 16.04 support.

**Comment by Buraburaite** [comment]
Windows, Ubuntu 16.04, Docker... All are good ideas, I use all of them but would prioritize Windows. Thanks fastlane!

**Comment by 24PaH** [comment]
Looking forward for Linux support 🐧

**Comment by danpe** [comment]
Any linux support?

**Comment by girishghoda** [comment]
Any news for a window?

**Comment by Aravindios** [comment]
Cool! Awaiting for linux.

**Comment by rogerdavis198** [comment]
Centos or any Linux system,  mind u any images out there for Mac and install it that way as a virtual machine ?

**Comment by i-need-to-tell-you-something** [comment]
+1 Linux

**Comment by appleajay** [comment]
Please update support for Linux.

**Comment by yvolk** [comment]
@janpio Reading this thread I've got an impression that actually there is no visible progress in Windows/Linux support since January, when this thread (issue) was created :-( 
As explained in https://github.com/fastlane/fastlane/issues/11579#issuecomment-358632536 using Ruby as an underlying language/framework is a cause of this pain. And if so, the only real way forward would be to re-implement Fastlane on a platform/language with better OS support?!
Did Fastlane team consider that option?!

**Comment by janpio** [comment]
There is progress, just nothing that would justify updating here (at least not just yet). All changes on Fastlane are already fully tested on both Linux and Windows, but it is not ready enough yet.

Fastlane will not be reimplemented in another language, it is a few ten thousands lines of ruby code after all, but of course feel free to create a new project with the same goals as Fastlane if you want.

**Comment by janpio** [comment]
There is still progress being made here, several PRs were recently merged or are waiting to be merged to further improve on Windows support.

**Comment by phillipleblanc** [comment]
Transporter is supported on Windows & Linux, according to this link: https://help.apple.com/itc/transporteruserguide/#/itc0d5b535bf
Does that mean that we could one day use fastlane to upload to App Store without requiring macOS?

**Comment by raveesh-me** [comment]
> Does that mean that we could one day use FastLane to upload to App Store without requiring macOS?

We still need Xcode to build the app which will never run on other platforms

I used Fastlane with flutter recently for continuous delivery to clients for internal testing. This helps save so much time and allows for so much faster feedback cycles! I have fallen in love with your work. This is awesome.

Just hope I could run the same thing on my Linux machine on which I do most of the coding. +1 for Linux support. Waiting eagerly!!

**Comment by janpio** [comment]
Same as for Windows, you can already do _most_ of the things on Linux. (Exceptions are everything that requires Xcode - and the stuff I couldn't fix yet). Let me know if something does not work that you would like to have working and I will look into it @raveesh-me!

**Comment by raveesh-me** [comment]
Se here are the installation steps for anyone stumbling here trying to figure out how to do this on Ubuntu 18.04:

### Install ruby and ruby-dev headers
```
sudo apt install ruby ruby-dev
```

### Install fastlane 
```
sudo gem install fastlane -NV
```

From there do the normal Fastlane Setup:
https://docs.fastlane.tools/getting-started/android/setup/

**Comment by MIna-Maher** [comment]
Hi I have a big problem when i install fastlane using this command 
#gem install fastlane -NV
I got this problem 
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::SafeYAML
Iam using gem version 2
and ruby version 2

**Comment by janpio** [comment]
@MIna-Maher Please create a new issue for this and include all the information the bug issue template asks for - then we will be able to help you. If this is on Windows or Linux, please mention me directly with @janpio so I get a notification. Thanks!

**Comment by RomuloVHSYS** [comment]
> Same as for Windows, you can already do _most_ of the things on Linux. (Exceptions are everything that requires Xcode - and the stuff I couldn't fix yet). Let me know if something does not work that you would like to have working and I will look into it @raveesh-me!

@janpio here you quote "everything that requires Xcode - and the stuff I couldn't fix yet", is there a chance to fastlane do an implementation to install xcode command line tools on linux or maybe theres a way to dribble that?

**Comment by janpio** [comment]
None that I know of. Xcode and its command line tools are macOS only - and you also don't want to mess with Apple here, or they can just remove/delete your app.

(I am personally working on a workaround for that on the side, but that's not directly related to fastlane)

**Comment by TPXP** [comment]
Hello, and thank you very much for your work, it is very helpful!

I'm trying to upload an IPA to Testflight, and it looks like it's not working properly. Here are the logs:
```
$ fastlane pilot upload --username "$FASTLANE_APPLE_LOGIN" --ipa "myapp.ipa"
[11:58:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:58:48]: Sending anonymous analytics information
[11:58:48]: Learn more at https://docs.fastlane.tools/#metrics
[11:58:48]: No personal or sensitive data is sent.
[11:58:48]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[11:58:48]: Login to App Store Connect (****@example.com)
[11:58:52]: Login successful
[11:58:52]: Ready to upload new build to TestFlight (App: 1453045438)...
[11:58:53]: Going to upload updated app to App Store Connect
[11:58:53]: This might take a few minutes. Please don't interrupt the script.

[11:58:53]: Error accessing file, this might be due to fastlane's directory handling
[11:58:53]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/usr/local/lib/ruby/2.6.0/fileutils.rb:128:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:293:in `execute'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:387:in `upload'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	from /usr/local/bundle/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bundle/bin/fastlane:23:in `load'
	from /usr/local/bundle/bin/fastlane:23:in `<main>'
```

This is running under Gitlab-CI on a Linux host. Is `pilot` expecting some Xcode dependency? It would help a lot if we could upload builds directly from our Linux CI!

**Comment by janpio** [comment]
Can you create a new issue for this @TPXP? I can look into this and offer a workaround probably. Thanks.

**Comment by TPXP** [comment]
@janpio Wow, didn't expect such a quick reply, thanks <3
I'm opening a new issue right now 😄

**Comment by RomuloVHSYS** [comment]
@janpio Where can i get updated about that "workaround"? I'm curious about that, and i'm looking for the better solution to implement a CI to iOS projects, but without a macOS server.

**Comment by janpio** [comment]
@RomuloVHSYS The issue @TPXP created and linked to: https://github.com/fastlane/fastlane/issues/14256

**Comment by RomuloVHSYS** [comment]
Thanks for your reply

**Comment by ash-and** [comment]
Ubuntu 16.04/18.04 would be really healpful

**Comment by bizire** [comment]
Looking for Windows version of Fastlane for working with Google Play to upload app and metadata.

**Comment by janpio** [comment]
You found it. All the Google Play stuff should work. If you can't get it working, create a new issue with your specific problem and I will try to help.

**Comment by geordanex** [comment]
Any news for a Windows?

**Comment by lilili87222** [comment]
appuploader.net   for windows

**Comment by janpio** [comment]
As written above: Install Ruby (https://rubyinstaller.org/) and just use it as you usually would on macOS. If you encounter any problems, open an issue. But big parts should be usable out of the box (exception: Everything that has to do with Xcode which does not work on Windows).

**Comment by TheIronMarx** [comment]
Crossing my fingers for Supply on Linux!

**Comment by janpio** [comment]
@TheIronMarx That should work pretty well. As said before: If specific stuff doesn't work, please create a new issue and report the problem.

**Comment by nenio-traduko** [comment]
Can't wait for Ubuntu support.

**Comment by raveesh-me** [comment]
> Se here are the installation steps for anyone stumbling here trying to figure out how to do this on Ubuntu 18.04:
> 
> ### Install ruby and ruby-dev headers
> ```
> sudo apt install ruby ruby-dev
> ```
> ### Set environment language variables
> #### Add these lines to the top of `~/.profile`
> ```
> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> ```
> #### Check that you didn't break the environment and restart
> run `source ~/.profile` in the terminal. If no output, you are safe. Otherwise, check for what you broke in the .profile file 
> 
> ### Install fastlane
> ```
> sudo gem install fastlane -NV
> ```
> From there do the normal Fastlane Setup:
> https://docs.fastlane.tools/getting-started/android/setup/

@nenio-traduko @TheIronMarx

**Comment by mareklowy** [comment]
Hey, I have tried following the install instructions on Fedora 29, but installation fails with following output: 
```
    Building native extensions. This could take a while...
    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
    /usr/bin/ruby -r ./siteconf20190327-12548-b9qtga.rb extconf.rb
    checking for -lstdc++... no
    creating Makefile
    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
    make "DESTDIR=" clean
    rm -f 
    rm -f unf_ext.so  *.o  *.bak mkmf.log .*.time
    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
    make "DESTDIR="
    g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall - 
    Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS 
    fexceptions  -
    fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 - 
    specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack- 
    clash-protection -fcf-protection -m64 -o unf.o -c unf.cc
    make: g++: Command not found
    make: *** [Makefile:211: unf.o] Error 127
    ERROR:  Error installing fastlane:
    ERROR: Failed to build gem native extension.
    Building has failed. See above output for more information on the failure.
    make failed, exit code 2
    Gem files will remain installed in /usr/local/share/gems/gems/unf_ext-0.0.7.5 for inspection.
    Results logged to /usr/local/lib64/gems/ruby/unf_ext-0.0.7.5/gem_make.out
```
I have installed gcc, make, ruby, ruby-devel, but something seems to be missing and I can-t figure out what. I have also added language variables into my profile file. 
I have noticed the log stating "checking for -lstdc++... no", however I don't knwo where to get it.
Thank you for your help.

**Comment by janpio** [comment]
Best create a new issue where we can discuss the details @mareklowy without notifying 31 people with each comment ;) Also please include a link to the exact "install instructions" you are following so there is not need to guess. Thanks.

**Comment by nickyrabit** [comment]
windows 10

**Comment by mareklowy** [comment]
Hey guys,
So I have managed to fix the error I was getting while trying to install fastlane on Fedora 29.

> Hey, I have tried following the install instructions on Fedora 29:
> 
> > Se here are the installation steps for anyone stumbling here trying to figure out how to do this on Ubuntu 18.04:
> > ### Install ruby and ruby-dev headers
> > ```
> > sudo apt install ruby ruby-dev
> > ```
> > ### Set environment language variables
> > #### Add these lines to the top of `~/.profile`
> > ```
> > export LC_ALL=en_US.UTF-8
> > export LANG=en_US.UTF-8
> > ```
> > #### Check that you didn't break the environment and restart
> > run `source ~/.profile` in the terminal. If no output, you are safe. Otherwise, check for what you broke in the .profile file
> > ### Install fastlane
> > ```
> > sudo gem install fastlane -NV
> > ```
> > From there do the normal Fastlane Setup:
> > https://docs.fastlane.tools/getting-started/android/setup/
> 
> However when I tried running the `sudo gem install fastlane -NV` I get folling error log:
> 
> ```
>     Building native extensions. This could take a while...
>     current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
>     /usr/bin/ruby -r ./siteconf20190327-12548-b9qtga.rb extconf.rb
>     checking for -lstdc++... no
>     creating Makefile
>     current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
>     make "DESTDIR=" clean
>     rm -f 
>     rm -f unf_ext.so  *.o  *.bak mkmf.log .*.time
>     current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
>     make "DESTDIR="
>     g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall - 
>     Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS 
>     fexceptions  -
>     fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 - 
>     specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack- 
>     clash-protection -fcf-protection -m64 -o unf.o -c unf.cc
>     make: g++: Command not found
>     make: *** [Makefile:211: unf.o] Error 127
>     ERROR:  Error installing fastlane:
>     ERROR: Failed to build gem native extension.
>     Building has failed. See above output for more information on the failure.
>     make failed, exit code 2
>     Gem files will remain installed in /usr/local/share/gems/gems/unf_ext-0.0.7.5 for inspection.
>     Results logged to /usr/local/lib64/gems/ruby/unf_ext-0.0.7.5/gem_make.out
> ```
> I have installed gcc, make, ruby, ruby-devel, but something seems to be missing and I can-t figure out what. I have also added language variables into my profile file.
> I have noticed the log stating "checking for -lstdc++... no", however I don't know where to get it.

First thing that was causing problem was missing lstdc++.
This I have managed to install using `sudo yum install libstdc++-static`. 
After doing so, I had one more persisting error, which was missing g++. 
This package is called differently in Fedora. Solution to this was `sudo dnf install gcc-c++`

I hope this will help to anybody who encounters this issue.

**Comment by mhienx95** [comment]
I can use it "fastlane init" but when to use "fastlane supply" error


[16:30:10]: WARNING: fastlane requires your locale to be set to UTF-8. To learn
more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environ
ment-variables
'cat' is not recognized as an internal or external command,
operable program or batch file.
[16:30:11]: Could not find service account json file at path 

[!] Invalid default value for json_key, doesn't match verify_block
[16:30:11]: WARNING: fastlane requires your locale to be set to UTF-8. To learn
more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environ
ment-variables

I user fastlane in window 7

**Comment by janpio** [comment]
Can you create a new issue about this @mhienx95? The solution will be to use a command line that comes with Linux like tools lik `cat` - I sometimes forget that I have those installed. Git bash or Cmder should do the trick. (I wonder if we can do something more here...)

**Comment by mikewillems** [comment]
This is so helpful, thanks so much for your work! Any word on whether work on Linux / Windows support is still planned following the Google / Firebase acquisition?

**Comment by janpio** [comment]
As I am in no way connected to Google or Firebase, but just a community member as most the other contributors here, this has no influence on what we do. We are still fixing Windows and Linux specific problems when they are reported.

**Comment by yuridiniz** [comment]
> Se here are the installation steps for anyone stumbling here trying to figure out how to do this on Ubuntu 18.04:
> 
> ### Install ruby and ruby-dev headers
> ```
> sudo apt install ruby ruby-dev
> ```
> 
> ### Set environment language variables
> #### Add these lines to the top of `~/.profile`
> ```
> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> ```
> 
> #### Check that you didn't break the environment and restart
> run `source ~/.profile` in the terminal. If no output, you are safe. Otherwise, check for what you broke in the .profile file 
> 
> ### Install fastlane
> ```
> sudo gem install fastlane -NV
> ```
> 
> From there do the normal Fastlane Setup:
> https://docs.fastlane.tools/getting-started/android/setup/

I also needed the following units:

sudo apt-get install libc6-dev
sudo apt-get install g++

**Comment by lichuanxiao** [comment]
+1 for Windows and linux Support.

**Comment by janpio** [comment]
Not much progress in the last time because of lack of time unfortunately :/ 
Anyone (or anyone's company) wants to sponsor my time on this? Contact me at piotrowski@gmail.com

**Comment by YWaller** [comment]
Windows 10 support requested!

**Comment by giacomocerquone** [comment]
@janpio you could open a patreon or something like it, or propose this to formidablelabs that i know are very active on oss.
Let me tweet this for you

**Comment by janpio** [comment]
Not the route I prefer here, but thanks @giacomocerquone. There might be a solution soon-ish - I will keep you all posted here. Until then: Please open bug issues if something _doesn't_ work so I have a nice TODO list when I can start working on it.

**Comment by mortenholmgaard** [comment]
It is possible to run Fastlane as it is on Windows 10. (with a few quirks)
Find a [full guide to set Fastlane up on Windows here][1] including a powershell setup script to do all the needed setup to be running Fastlane on Windows!
Find the [powershell script here][1].

  [1]: https://blog.vertica.dk/2019/08/15/automated-android-deployment-with-fastlane-on-windows/
  [2]: https://gist.github.com/mortenholmgaard/493572893b1e75da54633e9cc52b881c

**Comment by ghasemikasra39** [comment]
Linux support requested

**Comment by yihuang** [comment]
``sigh`` and ``match`` use ``security``, is there fast replacements for them on Linux?

**Comment by janpio** [comment]
No, the macOS only software is the big problem here @yihuang which we will probably not be able to replace that simple.

**Comment by yihuang** [comment]
@janpio It seems they only dependent on ``security`` and ``PlistBuddy``. ``PlistBuddy`` is easy to replace, maybe the ``https://github.com/ryu2/isign`` project can be used to replace ``security``?

**Comment by janpio** [comment]
Thanks, that's an interesting link. I will try to remember that when I have more time to look into non-macOS support (which will be soon 🥇)

**Comment by mthole** [comment]
Just chiming in here to say "me too!". Specifically, I'm looking for Linux support for the upload-to-TestFlight portion of fastlane. (I know that requires some iTMSTransporter shenanigans.)

For anyone curious, I'm looking to enable a workflow where anyone on my team makes a commit to master, CI runs tests and builds + signs an .ipa, then uploads that .ipa to Apple for release on TestFlight. As you may know the "upload to TestFlight" task can take foooorever, especially if you want to set metadata on the build (e.g. based on the commit message). That's not tenable on an expensive-per-minute macOS CI node, but would be reasonable on a cheap docker node.

**Comment by janpio** [comment]
ping @fastlane-bot - still open

**Comment by yihuang** [comment]
Actually, I've implemented parts of developer APIs in python and using my fork of `isign <https://github.com/yihuang/isign>`_ to resign apps, with success.

**Comment by janpio** [comment]
Interesting, I will look into this when the time comes. Definitely might be a workaround for _some_ of the iOS only things.

**Comment by mieliespoor** [comment]
Interested in using Fastlane to do Android builds on Linux (CentOS).

**Comment by janpio** [comment]
That should already work @mieliespoor - feel free to try and open new issues for the stuff that does _not_ work.

**Comment by alexcroox** [comment]
Am I right in reading this that currently you cannot automate iOS builds as part of a CI/CD pipeline as these tend to run with linux based dockers?

**Comment by janpio** [comment]
No, you just need a CI system that uses macOS based machines as most CI providers offer.

**Comment by ptgamr** [comment]
@janpio based on your comment, am I correct to understand that Fastlane now can build Android in a linux machine?

Is there any guide available for it? The setup guide: https://docs.fastlane.tools/getting-started/android/setup/ is still tied with Mac.

**Comment by janpio** [comment]
Besides the absolutely first command, which is not required, everything should work on Linux on the page you linked to @ptgamr

**Comment by giacomocerquone** [comment]
@janpio quoting on: "That should already work @mieliespoor - feel free to try and open new issues for the stuff that does not work." relative to android builds on linux.
If it's true, can we specify this on [this page](https://docs.fastlane.tools/)?

Regarding to the ios builds in linux, I see literally no point in that... it's really well known that ios builds and app store uploads need an osx machine.
Glad to see that you're even trying to support it, but that should really be a "wishing" feature.

**Comment by eman1986** [comment]
I too would like to see this available on windows. I am the only mobile dev currently and we only have 1 mac but if others on the team had a way to use fast lane on their windows computers, that'd be amazing.

**Comment by pnlinh-it** [comment]
> That should already work @mieliespoor - feel free to try and open new issues for the stuff that does _not_ work.

Does this already contains signing with keystore and upload to google play?

**Comment by ozbek** [comment]
> Does this already contains signing with keystore and upload to google play?

That's part of your Android build script (usually, `app/build.gradle`).

**Comment by iXunlong** [comment]
Sorry, my English is very poor. This is translated by translation software.
When I first used the command "Fastlane sigh -- ad hoc -- force" in CentOS, it succeeded and generated a valid mobileprovision certificate. 

But I failed when I used the command again. I don't know why, but I guess there is still a possibility of successful implementation. In Linux, we don't need to install the certificate, just let it be generated and then downloaded to the local.
I hope it helps.

**Comment by cbfranca** [comment]
Any update ?

**Comment by janpio** [comment]
No, otherwise it would have been posted here.

**Comment by tal987** [comment]
So fastlane is not working on linux or windows to run iOS app? only Mac OS?

**Comment by janpio** [comment]
Yes, as the documentation and this issue says _fastlane_ is only fully supported on macOS. Support for Linux and Windows is growing, but limited and should not be considered stable.

**Comment by yh414209726** [comment]
我在windows下下载了fastlane 能成功运行，但无法登录，是否因为这个仅支持 mac OS？

**Comment by janpio** [comment]
Create a new issue please @yh414209726 and describe what "can not login" means for you - maybe we can help you fix this.

**Comment by Tyler-V** [comment]
Happy 2020! Here for the  🖥️ Windows support.

**Comment by janpio** [comment]
This might probably not happen in the way we/I initially hoped. It becomes harder and harder to find an actual working version of iTMSTransporter for Windows, and if you read and agreed to the TOS of Apple you then probably can not even use it. Same probably applies for the Linux part - there is just no good way to properly upload stuff to Apple if you are not using macOS to run the software on.

I did not give up yet, but my hopes and ambitions are a lot smaller now. (E.g. just make the rest, that does not user iTMSTransporter work on these operating systems properly and make sure that everything that does use it, is properly hidden/disabled)

**Comment by buptwsg** [comment]
@janpio 
If I just want to use fastlane to access apple developer portal, does it support Linux?
Thanks.

**Comment by janpio** [comment]
Yes, the things that are done via APIs work just fine on all operating systems. If not, please open an issue.

**Comment by SebaRossi94** [comment]
+1 on windows development, at least for the android part of the project! Keep the good work!

**Comment by mortenholmgaard** [comment]
@SebaRossi94 
**Fastlane on windows for Android is working just fine** - please see my comment earlier:
https://github.com/fastlane/fastlane/issues/11687#issuecomment-521896065

**Comment by liamnichols** [comment]
I know that uploading the binary uses transporter, which doesn't sound like its gonna ever be available on linux but in theory can the build watcher run on linux? The one that waits until the build finishes processing? Does that use the App Store Connect API directly? 

Our Jenkins job to submit our apps is currently executing a single lane that runs for a couple of hours since processing always seems to take foreverrrrrrrr...

I've recently been looking at Jenkins Pipelines to try and make some of our processes more efficient... I'm wondering if I could split the 'wait to finish processing' stage out and run it on a linux node since we have less Mac Mini's in our setup and they could be doing better things (like running UI tests) for the period where we wait for Apple to do their thing 😅

**Comment by janpio** [comment]
Yes, that sounds like it should work. Not sure how to split the information out though. Next step is to actually look at the code that the watcher runs and confirm.

**Comment by janpio** [comment]
Ohhhh, take a look at this:

https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#aria-apd28806d5ebc904

iTMSTransporter 2.0 is available and downloadable for Windows and Linux. Thanks @Ashton-W for posting this at https://github.com/fastlane/fastlane/issues/16131#issuecomment-595973303 <3

**Comment by wp44** [comment]
> Ohhhh, take a look at this:
> 
> https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#aria-apd28806d5ebc904
> 
> iTMSTransporter 2.0 is available and downloadable for Windows and Linux. Thanks @Ashton-W for posting this at [#16131 (comment)](https://github.com/fastlane/fastlane/issues/16131#issuecomment-595973303) <3
> 
> The .exe again is just a zipped folder, and included are a lot of .jar files.

Is it possible now set delivery plugin from fastlane on windows or linux maschine?

**Comment by janpio** [comment]
> Is it possible now set fastlane delivery plugin on windows or linux maschine?

I am not sure what you are asking.

The link I posted can be used to investigate how everything works, and then potentially adapt fastlane to work on Linux and Windows. But considerable work and testing is required here to implement that and make sure it actually works.

**Comment by Ashton-W** [comment]
I think most of pilot could be made to work on windows and linux.
I’m using iTMSTransporter on Linux to upload an iOS app built on macOS. The rest of pilot is APIs I believe so should work on any platform.

**Comment by wp44** [comment]
I would like to create a central place in the cloud to veryfy apps internaly. The idea is to run it on Pivotal Cloud with Spring Boot. The app should collect ipa, metadata, and screenshots and then, after internal approval process push that all to apple app review. Deliver plugin is exactly what I'm looking for. The only obsticle is lack of mac maschine :) Thank you both for answer :) I really appreciate it!

**Comment by xxw898** [comment]
Can run on Windows, Linux or Mac systems， If you do not have a Mac, you can easily upload IPA
https://github.com/xxw898/Application-Loader-Windows/wiki/Application-Loader-Windows-version

**Comment by childnode** [comment]
@janpio perhaps you would like to give up an update sum in your first issue statement?

**Comment by janpio** [comment]
Done: https://github.com/fastlane/fastlane/issues/11687#issue-291362572

**Comment by tommycloud** [comment]
Yes! Looking forward to the **windows** support! especially the snapshots generate and upload.

**Comment by wp44** [comment]
@Ashton-W Can you describe how you did it?
I installed iTMSTransporter 2.0.0 from: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__linux/bin/ 

I set environmental variable FASTLANE_ITUNES_TRANSPORTER_PATH pointing to iTMSTransporter and receive an error:

-Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.

The same as in this macOS thread:
https://github.com/fastlane/fastlane/issues/15323

**Comment by golfiti** [comment]
Can I build (gym) iOS app in Ubuntu ?

**Comment by taltrui** [comment]
Hi @golfiti! I'm not part of Fastlane but use it daily.

You can't build an iOS app in any platform that's not MacOS primarily because in order to build an iOS app you'll need (among other things) XCode, which is only available on MacOS.

**Comment by golfiti** [comment]
> Hi @golfiti! I'm not part of Fastlane but use it daily.
> 
> You can't build an iOS app in any platform that's not MacOS because in order to build an iOS app you'll need (among other things) XCode, which is only available on MacOS.

@taltrui Thank you

**Comment by zhlynn** [comment]
https://github.com/zhlynn/zsign

**Comment by rogerluan** [comment]
Reopened by mistake 🙇 there's ongoing work on the docs for platform compatibility. Follow the issue here: https://github.com/fastlane/fastlane/issues/11859
