### ISSUE TITLE
How should I give which directory to look to gcovr action

### ISSUE THREAD

**Issue by manuyavuz** [fastlane/fastlane#1168]
Hi,

I'm trying to use gcovr action but can't figure out how I am supposed to give the directory path to look for .gcda files.

This is the command that I want gcovr action to run:

```
gcovr -r .. ~/Library/Developer/Xcode/DerivedData/MyProject-afooxihhktmqdrfkuvqoejyacuzs/Build/Intermediates/Pods.build/Debug-iphonesimulator/MyProject.build/Objects-normal/i386 --xml
```

I can give `-r` and `--xml` options using the following:

```ruby
gcovr(
      root: "..",
      xml: true, 
)
```

But I couldn't figure out how I can give the build path which has no option prefix.

Thanks for the help.

**Comment by vpolouchkine** [comment]
If you run `$ fastlane action gcovr` it will print out all the possible arguments that you can pass. I believe `object_directory` is the one you're looking for.

**Comment by manuyavuz** [comment]
I've tried that first but there was an issue about that option related to gcovr version 3.2. I've made it work after a few more trials.

Closing. Thanks for the feedback!
