### ISSUE TITLE
fastlane-plugin-firim error

### ISSUE THREAD

**Issue by gongyucheng** [fastlane/fastlane#11682]
/usr/local/lib/ruby/gems/2.3.0/gems/firim-0.1.4/lib/firim/runner.rb:77:in `upload_binary_and_icon': [!] undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by janpio** [comment]
You should probably report this in the repo of `fastlane-plugin-firim` at https://github.com/whlsxl/firim/issues
