### ISSUE TITLE
How to set DELIVER_WHAT_TO_TEST for the deliver command 

### ISSUE THREAD

**Issue by jahanvijani** [fastlane/fastlane#11697]
I am using Bitrise to deploy iOS build to TestFlight.  How to add “What to Test” (test notes) in iOS Testflight build. I am not using fast lane in my project but Bitrise is having 1 step named "Deploy to iTunes Connect / TestFlight (with Deliver)" which is using deliver command to deploy build.

Can you help me how to set DELIVER_WHAT_TO_TEST in Bitrise. Is there any official document for this env variable. 

Thanks in advance.

**Comment by KrauseFx** [comment]
`DELIVER_WHAT_TO_TEST` isn't a variable we support with _fastlane_. It seems like we currently only support the following parameters as part of pilot: https://docs.fastlane.tools/actions/pilot/#parameters, you might be interested in `changelog`, `beta_app_description`, `beta_app_feedback_email`. It seems like the what to test value can't be set by _fastlane_ currently 😢

**Comment by jbelkins** [comment]
Whatever you put in the `changelog` field during a Pilot upload gets put into the "What to Test" field for that build, provided you also use the `wait_for_uploaded_build: true` option (apparently the "What to Test" notes can't be entered until the build finishes processing.)

**Comment by jahanvijani** [comment]
Actually I am using fastlane through Bitrise only. And they are using deliver command only. Is there any way to do with deliver command?

**Comment by jahanvijani** [comment]
Thanks everyone for the reply.

**Comment by joshdholtz** [comment]
Closing this as it seems like the question was answered 😊 Happy fastlaning 🚀
