### ISSUE TITLE
How to set path to info.plist for different targets?

### ISSUE THREAD

**Issue by gleutar** [fastlane/fastlane#11692]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi, I have several targets in my workspace and am using it to deploy several different apps (with different app bundle identifiers). How can I make fastlane use a different info.plist instead of the default one? Whatever I do, it always uses the default one even though I've specified another plist in my target.

**Comment by KrauseFx** [comment]
Maybe you could try using multiple schemes, and passing the `scheme` as part of your _gym_ call?

**Comment by gleutar** [comment]
Hi @KrauseFx ! Thanks for your answer. I'm using scheme in my GYM call like this "gym(scheme: "MyScheme")" but fastlane seems to always use the info.plist instead of the MyScheme-info.plist. I have also specified the other plist in my scheme. Fastlane finishes without errors. The upload to Itunes is completed and then Apple sends me this:
"**Attempting to Change Bundle Identifier** - Once a version of your application has been made available for sale on the store, you must use the same bundle identifier (as specified via the key CFBundleIdentifier in the bundle's Info.plist file)..."

**Comment by KrauseFx** [comment]
You can see the `xcodebuild` command _fastlane_ uses in the output. That's all _fastlane_ does really :)

**Comment by gleutar** [comment]
@KrauseFx  Maybe the problem is not the build of the fastlane but the attempt to upload it to itunes. Do I have to set something up for fastlane so that it knows that I'm building AppB instead of AppA and that it should upload the binary to AppB instead of the usual AppA?

**Comment by gleutar** [comment]
Hi @KrauseFx. I found the error. I forgot to add the app identifier in the Appfile.
I've added this:
for_lane : beta do
	app_identifier 'com.wargog.me'
end

and it works fine now. You can close the issue. Thanks a lot.

**Comment by KrauseFx** [comment]
Glad to hear :)
