### ISSUE TITLE
xcpretty_formatter in gym not working

### ISSUE THREAD

**Issue by zebroc** [fastlane/fastlane#11694]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I wanted to use xcpretty-json-formatter from our Fastfile.

Their doc says to use xcpretty -f `xcpretty-json-formatter`, i.e. run the program and then take that output as the actual formatter.

I can't put backticks in the Fastfile without getting an error: Assuming it checks for special characters.

My workaround is putting the output of running xcpretty-json-formatter in the Fastfile.

TBH: Not really sure what the best way to go about this is, all the solutions that come to mind seem pretty whacky. Just wanted to leave this here for awareness and maybe someone else stumbles on it too.

**Comment by KrauseFx** [comment]
Could you tell us a bit more, and ideally share your Fastfile? If you use tools like _gym_ or _scan_ this should all happen automatically for you

**Comment by joshdholtz** [comment]
Going to close this for now since no response 😊 Feel free to comment back about this issue!
