### ISSUE TITLE
Screengrab locale not changing 

### ISSUE THREAD

**Issue by kirshanluhana** [fastlane/fastlane#11696]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
ScreenGrab does not change app local: We were enjoying fastlane screengrab for screenshot. Recently we upgraded our app with in-app local support where device-local gets device language or one can set on his / her choice. 
Now when we are trying to take screenshots, it is taking screenshots all in one language but changing system local. 

I want to know: is screengrab restart app after system local change or how it changes local to understand fix issue.  

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[16:22:27]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[16:22:27]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                               |
| --------------------------- | ------------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                            |
| Ruby                        | 2.3.1                                                               |
| Bundler?                    | false                                                               |
| Git                         | git version 2.7.4                                                   |
| Installation Source         | /usr/local/bin/fastlane                                             |
| Host                        | Linux Mint 18.3 Sylvia debian_based stretch/sid (4.10.0-38-generic) |
| Ruby Lib Dir                | /usr/lib                                                            |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                          |
| Is contained                | false                                                               |
| Is homebrew                 | false                                                               |
| Is installed via Fabric.app | false                                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US       | 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| nanaimo                   | 0.2.3        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 2.3.6        |
| xcodeproj                 | 1.5.4        |
| plist                     | 3.4.0        |
| tty-screen                | 0.6.4        |
| highline                  | 1.7.10       |
| excon                     | 0.60.0       |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
</details>

*generated on:* **2018-01-25**
</details>
[16:22:27]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[16:22:27]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

**Comment by taquitos** [comment]
Ok, so we erase the simulator before the runs, and then we set the preferences before re-launching the sims. 
Here's how we erase:
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb#L45-L65

You can see how we set the device's preferences here: 
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb#L106-L118

Ultimately, we update:
`plist_path = "#{ENV['HOME']}/Library/Developer/CoreSimulator/Devices/#{device_udid}/data/Library/Preferences/.GlobalPreferences.plist"`

To set the preferences.

**Comment by kirshanluhana** [comment]
Hi
Thanks for details.
1- Is snapshot and screengrab have same logic /workflow?
2- Please tell me: is application shutdown and restart for new language code or not?
