### ISSUE TITLE
Upload of Android app fails with uninitialized constant Fastlane::FastFile::Upload (NameError)

### ISSUE THREAD

**Issue by dral3x** [fastlane/fastlane#11705]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running the deploy lane, fastlane crashes executing `upload_to_play_store` action.
Every single time.

##### Complete output when running fastlane, including the stack trace and command used

 ~  Projects  bnpcard-android  upgrades  ✎  $  fastlane deploy
[✔] 🚀
[08:41:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:41:05]: ----------------------------------------
[08:41:05]: --- Step: Verifying fastlane version ---
[08:41:05]: ----------------------------------------
[08:41:05]: Your fastlane version 2.78.0 matches the minimum requirement of 2.76.1  ✅
[08:41:05]: ------------------------------
[08:41:05]: --- Step: default_platform ---
[08:41:05]: ------------------------------
[08:41:05]: Driving the lane 'android deploy' 🚀
[08:41:05]: Which version do you want to deploy?
1. Production
2. Test
?  2
[08:41:11]: Deploying Test version...
[08:41:11]: ------------------------------------------------
[08:41:11]: --- Step: Switch to android deploy_test lane ---
[08:41:11]: ------------------------------------------------
[08:41:11]: Cruising over to lane 'android deploy_test' 🚖
[08:41:11]: -----------------------------
[08:41:11]: --- Step: get_app_version ---
[08:41:11]: -----------------------------
[08:41:11]: Reading ./app/build.gradle
[08:41:11]: Current app version is: 68
[08:41:11]: --------------------------------
[08:41:11]: --- Step: validate_changelog ---
[08:41:11]: --------------------------------
[08:41:11]: Checking file: ./fastlane/metadata-test/it-IT/changelogs/68.txt
[08:41:11]: Chars counter: 295
[08:41:11]: --------------------------------
[08:41:11]: --- Changelog for version 68 ---
[08:41:11]: --------------------------------
[08:41:11]: [removed]
[08:41:11]: Is it correct? (y/n)
y
[08:41:13]: --------------------
[08:41:13]: --- Step: gradle ---
[08:41:13]: --------------------
[08:41:13]: $ /Users/alex/Projects/bnpcard-android/gradlew assembleDevRelease -p .
[08:41:13]: ▸ Parallel execution is an incubating feature.
[08:41:14]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
[08:41:14]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
[08:41:14]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
[08:41:14]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
[08:41:14]: ▸ :app:preBuild UP-TO-DATE
[08:41:14]: ▸ :app:extractProguardFiles UP-TO-DATE
[08:41:14]: ▸ :app:preDevReleaseBuild UP-TO-DATE
[08:41:14]: ▸ :app:compileDevReleaseAidl UP-TO-DATE
[08:41:14]: ▸ :app:compileDevReleaseRenderscript UP-TO-DATE
[08:41:14]: ▸ :app:checkDevReleaseManifest UP-TO-DATE
[08:41:14]: ▸ :app:generateDevReleaseBuildConfig UP-TO-DATE
[08:41:14]: ▸ :app:prepareLintJar UP-TO-DATE
[08:41:14]: ▸ :app:mergeDevReleaseShaders UP-TO-DATE
[08:41:14]: ▸ :app:compileDevReleaseShaders UP-TO-DATE
[08:41:14]: ▸ :app:generateDevReleaseAssets UP-TO-DATE
[08:41:14]: ▸ :app:mergeDevReleaseAssets UP-TO-DATE
[08:41:14]: ▸ :app:createDevReleaseCompatibleScreenManifests UP-TO-DATE
[08:41:14]: ▸ :app:processDevReleaseManifest UP-TO-DATE
[08:41:14]: ▸ :app:fabricGenerateResourcesDevRelease
[08:41:14]: ▸ :app:generateDevReleaseResValues UP-TO-DATE
[08:41:14]: ▸ :app:generateDevReleaseResources UP-TO-DATE
[08:41:14]: ▸ :app:mergeDevReleaseResources
[08:41:14]: ▸ :app:splitsDiscoveryTaskDevRelease UP-TO-DATE
[08:41:15]: ▸ :app:processDevReleaseResources
[08:41:15]: ▸ :app:generateDevReleaseSources
[08:41:15]: ▸ :app:javaPreCompileDevRelease UP-TO-DATE
[08:41:15]: ▸ :app:compileDevReleaseJavaWithJavac UP-TO-DATE
[08:41:15]: ▸ :app:compileDevReleaseNdk NO-SOURCE
[08:41:15]: ▸ :app:compileDevReleaseSources UP-TO-DATE
[08:41:15]: ▸ :app:processDevReleaseJavaRes NO-SOURCE
[08:41:15]: ▸ :app:transformResourcesWithMergeJavaResForDevRelease UP-TO-DATE
[08:41:16]: ▸ :app:transformClassesAndResourcesWithProguardForDevRelease UP-TO-DATE
[08:41:16]: ▸ :app:crashlyticsStoreDeobsDevRelease
[08:41:19]: ▸ :app:crashlyticsUploadDeobsDevRelease
[08:41:27]: ▸ :app:lintVitalDevRelease
[08:41:27]: ▸ :app:transformClassesWithDexForDevRelease UP-TO-DATE
[08:41:27]: ▸ :app:mergeDevReleaseJniLibFolders UP-TO-DATE
[08:41:27]: ▸ :app:transformNativeLibsWithMergeJniLibsForDevRelease UP-TO-DATE
[08:41:27]: ▸ :app:transformNativeLibsWithStripDebugSymbolForDevRelease UP-TO-DATE
[08:41:27]: ▸ :app:validateSigningDevRelease
[08:41:29]: ▸ :app:packageDevRelease
[08:41:29]: ▸ :app:assembleDevRelease
[08:41:29]: ▸ BUILD SUCCESSFUL in 15s
[08:41:29]: ▸ 30 actionable tasks: 8 executed, 22 up-to-date
+-----------------------------+--------------------------------------------------------------------+
|                                           Lane Context                                           |
+-----------------------------+--------------------------------------------------------------------+
| DEFAULT_PLATFORM            | android                                                            |
| PLATFORM_NAME               | android                                                            |
| LANE_NAME                   | android deploy                                                     |
| VERSION_CODE                | 68                                                                 |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/alex/Projects/bnpcard-android/app/build/outputs/apk/dev/  |
|                             | release/app-dev-release.apk",                                      |
|                             | "/Users/alex/Projects/bnpcard-android/app/build/outputs/apk/dev/d  |
|                             | ebug/app-dev-debug.apk"]                                           |
| GRADLE_APK_OUTPUT_PATH      | /Users/alex/Projects/bnpcard-android/app/build/outputs/apk/dev/re  |
|                             | lease/app-dev-release.apk                                          |
+-----------------------------+--------------------------------------------------------------------+
[08:41:29]: uninitialized constant Fastlane::FastFile::Upload
Did you mean?  UploadIO

+------+------------------------------------+-------------+
|                    fastlane summary                     |
+------+------------------------------------+-------------+
| Step | Action                             | Time (in s) |
+------+------------------------------------+-------------+
| 1    | Verifying fastlane version         | 0           |
| 2    | default_platform                   | 0           |
| 3    | Switch to android deploy_test lane | 0           |
| 4    | get_app_version                    | 0           |
| 5    | validate_changelog                 | 0           |
| 6    | gradle                             | 16          |
+------+------------------------------------+-------------+

[08:41:29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Fastfile:119:in `block (2 levels) in parsing_binding': [!] uninitialized constant Fastlane::FastFile::Upload (NameError)
Did you mean?  UploadIO
Did you mean?  UploadIO
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.76.1")

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version of the app"
  lane :deploy do

    flavor = UI.select("Which version do you want to deploy? ", ["Production", "Test"])

    UI.success("Deploying #{flavor} version...")

    case flavor
      when "Production"
        deploy_prod

      when "Test"
        deploy_test

      else
        UI.warning "I've no idea what to do!"
    end

  end

  desc "Deploy a new public version to the Google Play"
  lane :deploy_prod do

    metadata_path = "./fastlane/metadata-prod"

    app_version = get_app_version(
      gradle_file_path: "./app/build.gradle"
      )

    # Ensure changelog is valid and up-to-date    

    UI.header "Changelog for version #{app_version} - Italian"

    changelog_it_file = "#{metadata_path}/it-IT/changelogs/#{app_version}.txt"
    validate_changelog(
      file_path: changelog_it_file
      )

    UI.message(File.read(changelog_it_file))
    unless UI.confirm("Is IT changelog correct?")
      UI.user_error!("Please update file #{changelog_it_file} and run lane again.")
    end

    UI.header "Changelog for version #{app_version} - English"

    changelog_en_file = "#{metadata_path}/en-US/changelogs/#{app_version}.txt"
    validate_changelog(
      file_path: changelog_en_file
      )

    UI.message(File.read(changelog_en_file))
    unless UI.confirm("Is EN changelog correct?")
      UI.user_error!("Please update file #{changelog_en_file} and run lane again.")
    end

    # Build
    gradle(task: "assembleProdRelease")

    # Upload
    upload_to_play_store(
      package_name: "[removed]",
      track: "production",
      rollout: "1.0",
      metadata_path: metadata_path,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
      )

  end

  desc "Deploy a new test version to the Google Play"
  lane :deploy_test do

    app_version = get_app_version(
      gradle_file_path: "./app/build.gradle"
      )
    changelog_file = "./fastlane/metadata-test/it-IT/changelogs/#{app_version}.txt"

    # Validate changelog 
    validate_changelog(
      file_path: changelog_file
      )

    # Ensure changelog is up-to-date
    UI.header "Changelog for version #{app_version}"
    UI.message(File.read(changelog_file.gsub("fastlane/", "")))
    unless UI.confirm("Is it correct?")
      UI.user_error!("Please update file #{changelog_file} and run lane again.")
    end

    # Build
    gradle(task: "assembleDevRelease")

    Upload
    upload_to_play_store(
      package_name: "[removed]",
      track: "alpha",
      rollout: "1.0",
      metadata_path: "./fastlane/metadata-test",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
      )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "[removed]" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.7.0.1      |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-01-26**
</details>

**Comment by lacostej** [comment]
Missing comment sign in your `Fastfile`
````
   Upload
    upload_to_play_store(
````

should be

````
   # Upload
    upload_to_play_store(
````

**Comment by dral3x** [comment]
That's so stupid on my side.
Thank you so much @lacostej
