### ISSUE TITLE
Hardcoded log-file paths lead to permission errors when embedding ruby gems in macOS app

### ISSUE THREAD

**Issue by sn3ek** [fastlane/fastlane#11708]
I'm building an macOS App which embedds ruby gems. When I now execute Spaceship it tries to create a log-file within the /tmp folder. This causes some issues. 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/logger.rb:711:in `initialize': Operation not permitted @ rb_sysopen - /tmp/spaceship1516966386_1152.log (Errno::EPERM)
```

I found an example code snipped which indicates that the Logger Class is initialized by a hard-coded tmp path. This should be configurable by an environment variable, e.g. `TMP_DIR=/tmp`.

Code snipped:
https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/spaceship/lib/spaceship/client.rb#L241

I try to come up with an pull request. But if there is someone which can resolve this issue faster, I'm open to it :)

Thanks
Lars

**Comment by sn3ek** [comment]
Workaround for me:
Using the environment variable `VERBOSE=1` which redirects the output to STDOUT.

**Comment by KrauseFx** [comment]
Ah alright 👍 If you have the time for a PR, I'm happy to review it

**Comment by sn3ek** [comment]
I'm on it.
