### ISSUE TITLE
Fastlane swift commit version bump unexpected uncommitted changes

### ISSUE THREAD

**Issue by acegreen** [fastlane/fastlane#11709]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

![screen shot 2018-01-26 at 10 13 23 am](https://user-images.githubusercontent.com/10794609/35446110-b8afafde-0281-11e8-8696-fde7bd201050.png)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// Customize this file, documentation can be found here:
// https://docs.fastlane.tools/
// All available actions: https://docs.fastlane.tools/actions
// can also be listed using the `fastlane actions` command

// Change the syntax highlighting to Swift
// All lines starting with // are ignored when running `fastlane`

// If you want to automatically update fastlane if a new version is available:
// updateFastlane()

import Foundation

class Fastfile: LaneFile {
    // This is the minimum version number required.
    // Update this, if you use features of a newer version
    var fastlaneVersion: String { return "2.78.0" }
    var xcodeproj: String { return "OMRecordApp/OMRecordApp.xcodeproj" }

    func beforeAll() {
        // environmentVariables["SLACK_URL"] = "https://hooks.slack.com/services/..."
        // cocoapods()
        // carthage()
        
        updateFastlane()
    }

    func testLane() {
        desc("Runs all the tests")
        runTests()
    }

    func betaLane() {
        desc("Submit a new Beta Build to Apple TestFlight. This will also make sure the profile is up to date")

        // syncCodeSigning(gitUrl: "gitUrl", appIdentifier: [appIdentifier], username: appleID)
        buildApp(scheme: "Alamofire") // more options available
        uploadToTestflight(username: appleID)
        // You can also use other beta testing services here (run `fastlane actions`)
    }

    func releaseLane() {
        desc("Deploy a new version to the App Store")

        // syncCodeSigning(gitUrl: "gitUrl", type: "appstore", appIdentifier: [appIdentifier], username: appleID)
        captureScreenshots()
        buildApp(scheme: "Alamofire") // more options available
        uploadToAppStore(username: appleID, app: appIdentifier, force: true)
        // frameScreenshots()
    }
    
    func prepareNextVersionLane() {
        desc("Prepare next version")
        
        let currentVersion = getVersionNumber(xcodeproj: xcodeproj)
        let nextVersion = prompt(text: "version now: \(currentVersion), next version? (like '2.4.0' not 'v2.4.0'))")
        
        let nextSnapshotVersion = nextVersion + "-SNAPSHOT"
        incrementVersionNumber(bumpType: "major", versionNumber: nextSnapshotVersion, xcodeproj: xcodeproj)
        incrementBuildNumber(buildNumber: "1", xcodeproj: xcodeproj)
        
        commitVersionBump(message: "[fastlane][prepare-next-version] Version set to #{next_snapshot_version} with build number set to 1", xcodeproj: xcodeproj)
        pushToGitRemote()
    }
    
    func bumpBuildNumberLane() {
        desc("Bump build number")
        
        incrementBuildNumber(buildNumber: nil, xcodeproj: xcodeproj)
        commitVersionBump(message: "[fastlane][bump-build-number] Build number set to \(getBuildNumber(xcodeproj: xcodeproj))", xcodeproj: xcodeproj)
        pushToGitRemote()
    }
    
    func tagCurrentVersionLane() {
        desc("Tag version current version (will be removing '-SNAPSHOT'")
        
        let currentVersion = getVersionNumber(xcodeproj: xcodeproj)
        let versionToTag = String(currentVersion.split(separator: "-").first!)
        incrementVersionNumber(bumpType: "patch", versionNumber: versionToTag, xcodeproj: xcodeproj)
        
        commitVersionBump(message: "[fastlane][tag-version] Version set to \(versionToTag) for release", xcodeproj: xcodeproj)
        addGitTag(tag: "v\(versionToTag)", buildNumber: getBuildNumber(xcodeproj: xcodeproj))
        
        pushToGitRemote()
        pushGitTags()
    }
    
    func bumpAndTagLane() {
        desc("Bump and Tag")
        
        let currentVersion = getVersionNumber()
        let nextVersion = prompt(text: "version now: \(currentVersion), next version? (like '2.4.0' not 'v2.4.0'))")
        
        incrementVersionNumber(bumpType: "major", versionNumber: nextVersion, xcodeproj: xcodeproj)
        incrementBuildNumber(buildNumber: nil, xcodeproj: xcodeproj)
        
        commitVersionBump(message: "Version bump with Fastlane to \(nextVersion)", xcodeproj: xcodeproj)
        addGitTag(tag: "v\(nextVersion)", buildNumber: getBuildNumber(xcodeproj: xcodeproj))
    }
    
    func buildAndDeployToFabricLane() {
        desc("Build & Deploy to Fabric")
        
        let notes = prompt(text: "release notes?")
        
        bumpBuildNumberLane()
        
        let projectVersion = getVersionNumber(xcodeproj: xcodeproj)
        let qaVersion = "\(projectVersion)-qa"
        
        incrementVersionNumber(bumpType: "qa", versionNumber: qaVersion, xcodeproj: xcodeproj)
        
        buildApp(scheme: "WomensHealthProjectApp", configuration: "QA")
        crashlytics(apiToken: "c25b0e87f2722bcf99aabfe96ebee2ff7fead4a0",
                    buildSecret: "3a8061ebe748faceeb8818267dd5f0a079e0769831d96dcbc4e373c6f7f715a5",
                    notes: notes)
        
        uploadSymbolsToCrashlytics()
        
        cleanBuildArtifacts()
    }
    
    func bumpPodspecVersionLane() {
        bumpAndTagLane()
        bumpPodspecVersionLane()
        
        podLibLint()
        podPush(repo: "https://github.com/CocoaPods/Specs.git,https://github.com/OMsignal/CocoaPodsSpecs.git", allowWarnings: "true")
    }

    // You can define as many lanes as you want

    func afterAll(currentLane: String) {
        // This block is called, only if the executed lane was successful
        // slack(
        //     message: "Successfully deployed new App Update.",
        //     slackUrl: "slackURL"
        // )
    }

    func onError(currentLane: String, errorInfo: String) {
        // slack(
        //     message: errorInfo,
        //     slackUrl: "slackUrl",
        //     success: false
        // )
    }

    // All available actions: https://docs.fastlane.tools/actions

    // fastlane reports which actions are used. No personal data is recorded.
    // Learn more at https://github.com/fastlane/fastlane/#metrics
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.2       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.2        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.60.0       |
| CFPropertyList            | 2.3.6        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2018-01-26**
</details>

**Comment by KrauseFx** [comment]
For now, I think you could use the `force` flag to `true` to ignore the list of expected changes.

**Comment by acegreen** [comment]
@KrauseFx some additional info. A project where my .xcodeproj is in the root directory does NOT experience this unexpected error.
