### ISSUE TITLE
Can't install fastlane due to dependency error with fastlane_core

### ISSUE THREAD

**Issue by tommyle** [fastlane/fastlane#1170]
When I try to install fastlane with:
sudo gem install fastlane

I get this error:
ERROR: Could not find a valid gem 'fastlane_core' (< 1.0.0.0, >= 0.35.1) in any repository
ERROR: Possible alternatives: fastlane_core

My version of ruby is 2.0.0p654
Gem version: 2.5.1

If i do gem list I have fastlane_core 0.35.0 installed.

My source is: https://rubygems.rog/

**Comment by tommyle** [comment]
The issue is caused by the the dependencies for deliver v 1.8.1
To fix this issue I installed an older version of deliver v 1.8.0

**Comment by KrauseFx** [comment]
Sorry for the troubles, I pushed a new release and it should be working now :+1:
