### ISSUE TITLE
Add a update_project_to_sign_with_sigh action

### ISSUE THREAD

**Issue by xster** [fastlane/fastlane#11704]
A follow up to #3906

Sounds like the argument there is to not automatically imply modifications to the xcode project in sigh or in gym which are reasonable. 

But it would be nice to add a convenience bundler action to do whatever combination of update_project_team/update_project_provisioning/automatic_code_signing/wtv necessary to get gym to build and code sign exactly with the provisioning profile sigh just acquired. 

The user explicitly accepts all consequences of leaving the git state dirty etc etc (and likely don't matter if they're doing this on CI systems that gets wiped seconds later).

**Comment by taquitos** [comment]
I feel like this would be a good plugin. Have you had a chance to check out how to build a plugin yet?  [Create your own plugin](https://docs.fastlane.tools/plugins/create-plugin/#create-your-own-plugin)
