### ISSUE TITLE
last_testflight_build_number always assumes the build number is an int, truncates real value

### ISSUE THREAD

**Issue by marcpalmer** [fastlane/fastlane#11712]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```
$ fastlane --verbose stock_app_store_submit
[✔] 🚀 
[15:41:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path 'XXXXX'
- apple_id: 'XXXXX'
- team_name: 'XXXXX'
- app_identifier: 'XXXXX'
-------
DEBUG [2018-01-26 15:41:26.46]: Checking if there are any plugins that should be loaded...
INFO [2018-01-26 15:41:26.65]: ----------------------------------------
INFO [2018-01-26 15:41:26.65]: --- Step: Verifying fastlane version ---
INFO [2018-01-26 15:41:26.65]: ----------------------------------------
INFO [2018-01-26 15:41:26.65]: Your fastlane version 2.78.0 matches the minimum requirement of 2.73.0  ✅
INFO [2018-01-26 15:41:26.68]: ------------------------------
INFO [2018-01-26 15:41:26.68]: --- Step: default_platform ---
INFO [2018-01-26 15:41:26.68]: ------------------------------
INFO [2018-01-26 15:41:26.68]: Driving the lane 'ios stock_app_store_submit' 🚀
INFO [2018-01-26 15:41:26.68]: --------------------------------------
INFO [2018-01-26 15:41:26.68]: --- Step: mkdir -p ./fastlane_logs ---
INFO [2018-01-26 15:41:26.68]: --------------------------------------
INFO [2018-01-26 15:41:26.68]: $ mkdir -p ./fastlane_logs
INFO [2018-01-26 15:41:26.69]: ------------------------------------------------------
INFO [2018-01-26 15:41:26.69]: --- Step: Switch to ios get_marketing_version lane ---
INFO [2018-01-26 15:41:26.69]: ------------------------------------------------------
INFO [2018-01-26 15:41:26.69]: Cruising over to lane 'ios get_marketing_version' 🚖
INFO [2018-01-26 15:41:26.77]: gem 'Xcodeproj' is already installed
INFO [2018-01-26 15:41:26.77]: Cruising back to lane 'ios stock_app_store_submit' 🚘
INFO [2018-01-26 15:41:26.77]: We are about to submit to the App Store. This is serious. The release are are submitting for review is 1.1.28.
INFO [2018-01-26 15:41:26.81]: --------------------------------------------
INFO [2018-01-26 15:41:26.81]: --- Step: latest_testflight_build_number ---
INFO [2018-01-26 15:41:26.81]: --------------------------------------------
INFO [2018-01-26 15:41:26.87]: Login to iTunes Connect (XXXXX)
Loading session from 'XXXXX'
Looking for iTunes Connect Team with ID XXXXX
INFO [2018-01-26 15:41:28.88]: Login successful
INFO [2018-01-26 15:41:29.45]: Fetching the latest build number for version 1.1.28
INFO [2018-01-26 15:41:31.11]: Latest upload for version 1.1.28 is build: 180124
INFO [2018-01-26 15:41:31.11]: The build number we are using is 180124
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.4.2                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.5.0                               |
| Installation Source         | /usr/local/bin/fastlane                         |
| Host                        | Mac OS X 10.12.6 (16G29)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.1.app/Contents/Developer/ |
| Xcode Version               | 9.1                                             |

</details>

We are using build numbers of the form 99999.99999 based on dates, but builds like this in TestFlight return truncated int values for the version e.g. "99999".

This has shown up what appears to be a bug in the implementation of `AppStoreBuildNumberAction`. The code always coerces the version string to int in order to do the sorting.

Build versions are not exclusively ints, although some people use them like this. Amusingly if you look at the Apple docs for CFBundleVersion it actually expects three part versions...

The offending code is:

https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/fastlane/lib/fastlane/actions/app_store_build_number.rb#L43

I would like to suggest this is changed to not attempt to sort the values - presumably Apple supplies them sorted because you cannot reliably sort multi-part build numbers especially as CFBundleVersion permits alphanumerics.

**Comment by marcpalmer** [comment]
FYI, this works for us:

```
            build_nr = app.all_builds_for_train(train: version_number, platform: platform).map(&:build_version).first
```

**Comment by minuscorp** [comment]
A PR covering this change might be super useful, as you noted @marcpalmer, from Apple docs:

> The build version number should be a string comprised of three non-negative, period-separated integers with the first integer being greater than zero—for example, 3.1.2. The string should only contain numeric (0-9) and period (.) characters. Leading zeros are truncated from each integer and will be ignored (that is, 1.02.3 is equivalent to 1.2.3).

So Apple interprets that build version kind of follows the conventions applied to semver.

**Comment by joshdholtz** [comment]
@marcpalmer Got a PR out for a fix for ya ^
