### ISSUE TITLE
ERROR:  Could not find a valid gem 'fastlane_core' (< 1.0.0, >= 0.35.1) in any repository

### ISSUE THREAD

**Issue by rndcmo** [fastlane/fastlane#1171]
sudo gem install fastlane --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
HEAD http://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=fastlane
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=fastlane
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=addressable,cert,credentials_manager,deliver,fastlane_core,frameit,gym,krausefx-shenzhen,match,pem,pilot,plist,produce,scan,sigh,slack-notifier,snapshot,spaceship,supply,terminal-notifier,terminal-table,xcode-install,xcodeproj,xcpretty
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=addressable,cert,credentials_manager,deliver,fastlane_core,frameit,gym,krausefx-shenzhen,match,pem,pilot,plist,produce,scan,sigh,slack-notifier,snapshot,spaceship,supply,terminal-notifier,terminal-table,xcode-install,xcodeproj,xcpretty
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=activesupport,claide,colored
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=activesupport,claide,colored
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=i18n,json,minitest,thread_safe,tzinfo
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=i18n,json,minitest,thread_safe,tzinfo
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=babosa,commander,dotenv,excon,faraday,faraday_middleware,google-api-client,highline,multi_json,net-sftp,rubyzip,security,sentry-raven
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=babosa,commander,dotenv,excon,faraday,faraday_middleware,google-api-client,highline,multi_json,net-sftp,rubyzip,security,sentry-raven
200 OK
ERROR:  Could not find a valid gem 'fastlane_core' (< 1.0.0, >= 0.35.1) in any repository
GET https://api.rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
304 Not Modified
GET http://api.rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET http://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
304 Not Modified
ERROR:  Possible alternatives: fastlane_core

**Comment by KrauseFx** [comment]
Sorry for the troubles, I pushed a new release and it should be working now :+1:

**Comment by rndcmo** [comment]
Thanks for the quick turnaround.  Super cool.
