### ISSUE TITLE
Find the currently published version number on App Store

### ISSUE THREAD

**Issue by jvnike** [fastlane/fastlane#11716]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is more of a general question, I have been searching and can't seem to find an answer. 
I have setup the lane to successfully retrieve the live AppStore Build Number, but can Spaceship return the live AppStore Version number and | or the latest 'pending release' version number?

I would like to be able to capture the live version or pending release version into a variable.

Reference for latest build number that was solved:
https://github.com/fastlane/fastlane/issues/6770

Thanks!

**Comment by minuscorp** [comment]
Hi! I got this issue some months ago and I go this snippet working in my `Fastfile`, keep in mind that there's a dependency with `Versionomy` so make sure you have installed it in order to successfully run.

Also, I appreciate some credit on this 🚀 
```ruby
require 'versionomy'

def __highest_app_version_number(username, bundle_id)
  puts "fetching highest version on iTunes Connect..."

  Spaceship::Tunes.login(username)
  app = Spaceship::Tunes::Application.find(bundle_id)

  liveVersion = nil

  if app.live_version
    liveVersion = Versionomy.parse(app.live_version.version)
  end

  if app.edit_version && liveVersion.nil?
    editVersion = Versionomy.parse(app.edit_version.version)
    return liveVersion, editVersion
  else
    return liveVersion, nil
  end
ensure
  puts "Live Version: #{liveVersion}\tEdit Version: #{editVersion}"
end
```

Explaining it, `liveVersion` is the latest *on sale* version available (if any) for the app and `editVersion` is the latest *on preparation* version available, again, if any.

**Comment by jvnike** [comment]
Hello. minuscorp, thank for the info. For some reason, when I try to use Versionomy I get an error "undefined methodversion' for nil:NilClass"`, as noted in https://github.com/fastlane/fastlane/issues/8878

But, this was very helpful, I have come up with the following lane that is solving my problem. We have Jenkins jobs designed for business owners to manage the App Store Assets via Deliver. The Download job will pull the latest screenshots and metadata, generate a preview report, and zip up the files. For clarity, I need the job to indicate if the version in ITC is live or pending. Using this modified lane solves the issue. You will see I save the return of the either the live or edit version to a file (I use this file to get values for other app related items):

lane :check_for_edit_version do
    require 'spaceship'
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("com.nike.niketrainingclub")
    version = app.edit_version
    if version
    latest_app_version = version.raw_data["version"]
    # latest_prod_build_nr = app_info.raw_data["preReleaseBuild"]["buildVersion"]
    File.open('itc_edit_app_info.txt', 'w') do |fo|
      fo.puts "#{version}"
    end
    File.open('current_itc_version.txt', 'w') do |fo|
      fo.puts "#{latest_app_version}"
    end
    puts "Latest edit version: #{latest_app_version}"
  else
    puts "No edit version available"
    version = app.live_version
    latest_app_version = version.raw_data["version"]
    File.open('itc_live_app_info.txt', 'w') do |fo|
      fo.puts "#{version}"
    end
    File.open('current_itc_version.txt', 'w') do |fo|
      fo.puts "#{latest_app_version}"
    end
    puts "Latest live version: #{latest_app_version}"
  end
end
