### ISSUE TITLE
Demo Account in pilot

### ISSUE THREAD

**Issue by joaopedrok** [fastlane/fastlane#11713]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After update Xcode to version 9.2 and fastlane to version 2.78.0 im getting this error when i try do use pilot to distribuite to external testers

 {"code"=>"Enter a demo account user name, or deselect \"A demo account is required to use all the features of the app.\"", "description"=>"Failed to submit build for review."}`

I have searched all over the internet and i know what is this about but I don’t know how to solve it.

I don’t even know how to send this demouser and demopassword to pilot if my app does use an account.

Does anyone know anything about it?

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pt_BR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**Comment by alakoring** [comment]
This also seems like #11713

**Comment by joaopedrok** [comment]
@alakoring this is number of my issue.

@cpk1 witch version of fastlane has this modification? Becaseu i have tried all of the last versions with no success.

**Comment by alakoring** [comment]
Oops, I meant #11665 …

**Comment by KrauseFx** [comment]
Thanks everyone, working on the release right now 👍 https://github.com/fastlane/fastlane/pull/11760

**Comment by joshdholtz** [comment]
Should be fixed with now with #11760 😊 Happy fastlaning 🚀
