### ISSUE TITLE
Using Pilot without supplying or uploading an IPA file

### ISSUE THREAD

**Issue by jbelkins** [fastlane/fastlane#11719]
Reviewing the "pilot" action's docs & source code, it appears that there is not a way to add/change test metadata (i.e. changelog, etc.) for a TestFlight build without (1) supplying "pilot" with an .IPA file and (2) actually uploading the app.

I'd like to change the metadata for an existing build that has completed processing.  Is there a way to do that using Pilot without rebuilding and re-uploading (which causes an upload failure because the version already exists?)

**Comment by taquitos** [comment]
Unfortunately, Pilot doesn't support that, but you could use [Spaceship](https://github.com/fastlane/fastlane/tree/master/spaceship) to accomplish it

**Comment by jbelkins** [comment]
Thanks, I'll look at using Spaceship directly.

Alternatively, let me know if you'd like to support this as a feature in pilot and I can try to get a PR together (basically take parameters to identify the build rather than pick them out of the IPA, then perform the required metadata operations without uploading a new version first)
