### ISSUE TITLE
Need to launch Fastlane with sudo when publish to PlayStore

### ISSUE THREAD

**Issue by aguillard** [fastlane/fastlane#11726]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since several version of Fastlane, in need to execute fastlane with sudo when I want to publish to PlayStore, otherwise, I get an error when supply. Execute Fastlane with sudo works, but, I create many trouble on my project after, so, isn't a good solution.

##### Complete output when running fastlane, including the stack trace and command used

[16:14:43]: fastlane finished with errors
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- googleauth (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/supply/lib/supply/client.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/supply/lib/supply.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:37:in `available_options'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:237:in `block (2 levels) in execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:119:in `block (2 levels) in parsing_binding'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                  |
| Ruby                        | 2.3.3                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.14.1                                        |
| Installation Source         | /usr/local/bin/fastlane                                   |
| Host                        | Ubuntu 17.10 debian_based stretch/sid (4.13.0-32-generic) |
| Ruby Lib Dir                | /usr/lib                                                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**Comment by taquitos** [comment]
Ohh, I would totally use something like `rbenv` [Using rbenv with fastlane](https://docs.fastlane.tools/best-practices/continuous-integration/#ruby-environment)

That should help out because it will install all the gems in a local folder with your current permissions.

**Comment by joshdholtz** [comment]
@aguillard This is definitely one of the drawbacks to using a system Ruby. Using `rbenv` like @taquitos mentioned is usually a good idea. I personally use [chruby](https://github.com/postmodern/chruby) and [ruby-install](https://github.com/postmodern/ruby-install). Happy fastlaning 🚀
