### ISSUE TITLE
cannotUpdateApksOnTrackWithDraftRelease: Cannot update the APK configuration of the track when the track has a draft release. Please use UI to rollout or discard the draft release.

### ISSUE THREAD

**Issue by hszeto** [fastlane/fastlane#11735]
I'm trying out Fastlane deployment to Google Play Store. If followed the doc and instructions... I got the following error:

    Google Api Error: cannotUpdateApksOnTrackWithDraftRelease: 
    Cannot update the APK configuration of the track when the track has a draft release.
    Please use UI to rollout or discard the draft release.

I have a React Native app and I followed the instructions on RN's doc... and were successfully deployed to the Play Store. 

A couple days later, I tried Fastlane to deploy some styling changes... I can't get it to work. I have to manually drag and drop the release apk in the console.

What is causing the error?

**Comment by hszeto** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.2.2                           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store(
      track: 'rollout',
      rollout: '0.5'
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./Google-Play-Android-Developer-f1ad60884a8f.json" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "com.sicsnackrn" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.79.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.1        |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| bundler                   | 1.16.0       |
</details>


*generated on:* **2018-01-30**
</details>

**Comment by joshdholtz** [comment]
@hszeto Heeyyy 👋 I ran into this same error today while I was actually trying to look into #9363 😕 I'm thinking this _may_ be an error in the `google-api-client` gem. I created a sample script outside of fastlane using just the `google-api-client` provided sample code and I still got this error.

However, after I manually submitted a build through the Google Play web dashboard, I was able to submit build again. Were you able to submit builds again via fastlane after you manually submitted them through Google Play?

**Comment by joshdholtz** [comment]
Created on issue on `google-api-client` to see if we can diagnose this problem any further - https://github.com/google/google-api-ruby-client/issues/655

**Comment by nthegedus** [comment]
Same issue here.

I've tried to upload manually and it worked fine.

Any idea if it's a bug?

Here's the error:

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | gradle           | 3           |
| 3    | gradle           | 621         |
| 💥   | supply           | 28          |
+------+------------------+-------------+

[19:32:12]: fastlane finished with errors

[!] Google Api Error: cannotUpdateApksOnTrackWithDraftRelease: Cannot update the APK configuration of the track when the trackhas a draft release. Please use UI to rollout or discard the draft release.
