### ISSUE TITLE
Testfairy action fails randomly in jenkins

### ISSUE THREAD

**Issue by farshadtx** [fastlane/fastlane#11740]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm getting random failures on Testfairy action (possibly timeout) that started last month. The error I'm getting back from logs is: 

> undefined method `key?' for "":String

I just update fastlane to the latest version and now failures are 90%. can anyone point this error to any open issue or is this by any chance regression issue?

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[14:06:02]: Cruising back to lane 'ios build_and_release' 🚘
[14:06:02]: ----------------------------------------
[14:06:02]: --- Step: Switch to ios release lane ---
[14:06:02]: ----------------------------------------
[14:06:02]: Cruising over to lane 'ios release' 🚖
[14:06:02]: -----------------------
[14:06:02]: --- Step: testfairy ---
[14:06:02]: -----------------------
[14:06:02]: Starting with ipa upload to TestFairy...
+------------------------------------+---------------------------------------------------------------------------------------------------+
|                                                              Lane Context                                                              |
+------------------------------------+---------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                               |
| PLATFORM_NAME                      | ios                                                                                               |
| LANE_NAME                          | ios ci                                                                                            |
| VERSION_NUMBER                     | 4.0.0-qa                                                                                          |
| SIGH_PROFILE_TYPE                  | ad-hoc                                                                                            |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"*********"}          |
| BUILD_NUMBER                       | 1868                                                                                              |
| IPA_OUTPUT_PATH                    | /Users/ *********/build/workspace/******************_QA.ipa                                       |
| DSYM_OUTPUT_PATH                   | /Users/ *********/build/workspace/******************_QA.app.dSYM.zip                              |
| XCODEBUILD_ARCHIVE                 | /Users/ *********/Library/Developer/Xcode/Archives/2018-01-30/**_QA 2018-01-30 14.02.01.xcarchive |
| TESTFAIRY_BUILD_URL                | https://app.testfairy.com/projects/*********/builds/***************                               |
+------------------------------------+---------------------------------------------------------------------------------------------------+
[14:06:47]: undefined method `key?' for "":String

+------+----------------------------------------------+-------------+
|                         fastlane summary                          |
+------+----------------------------------------------+-------------+
| Step | Action                                       | Time (in s) |
+------+----------------------------------------------+-------------+
| 1    | Verifying fastlane version                   | 0           |
| 2    | default_platform                             | 0           |
| 3    | Switch to ios build_and_release lane         | 0           |
| 4    | get_version_number                           | 1           |
| 5    | Switch to ios download_signing_identity lane | 0           |
| 6    | match                                        | 13          |
| 7    | match                                        | 7           |
| 8    | Switch to ios build lane                     | 0           |
| 9    | increment_version_number                     | 1           |
| 10   | increment_build_number                       | 1           |
| 11   | gym                                          | 272         |
| 12   | Switch to ios release lane                   | 0           |
| 13   | testfairy                                    | 40          |
| 14   | Switch to ios build lane                     | 0           |
| 15   | increment_version_number                     | 1           |
| 16   | increment_build_number                       | 1           |
| 17   | gym                                          | 184         |
| 18   | Switch to ios release lane                   | 0           |
| 19   | testfairy                                    | 43          |
| 20   | Switch to ios build lane                     | 0           |
| 21   | increment_version_number                     | 1           |
| 22   | increment_build_number                       | 1           |
| 23   | gym                                          | 243         |
| 24   | Switch to ios release lane                   | 0           |
| 💥   | testfairy                                    | 43          |
+------+----------------------------------------------+-------------+

[14:06:47]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [!] undefined method `fetch' for #<String:0x007fb9844e32d0> (NoMethodError)
    https://github.com/fastlane/fastlane/issues/10967 [open] 3 💬
    2 weeks ago

➡️  Type Checking error: got 'Fixnum' for attribute 'fileEncoding' and undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11016 [open] 2 💬
    2 weeks ago

➡️  Scan completion issue: undefined method `username=' for Slack::Notifier
    https://github.com/fastlane/fastlane/issues/11590 [closed] 6 💬
    2 weeks ago

and 46 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60key?%27%20for%20%22%22:String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/actions/testfairy.rb:110:in `parse_response': [!] undefined method `key?' for "":String (NoMethodError)
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/actions/testfairy.rb:97:in `run'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:165:in `block (2 levels) in parsing_binding'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:93:in `block (3 levels) in parsing_binding'
	from Fastfile:91:in `each'
	from Fastfile:91:in `block (2 levels) in parsing_binding'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:80:in `block (2 levels) in parsing_binding'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/ *********/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.79.0/bin/fastlane:20:in `<top (required)>'
	from /Users/ *********/.rbenv/versions/2.4.0/bin/fastlane:22:in `load'
	from /Users/ *********/.rbenv/versions/2.4.0/bin/fastlane:22:in `<main>'
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require_relative 'support/system'
require_relative 'support/provisioning_profiles'

# This is the minimum version number required.
fastlane_version '2.10.0'
default_platform :ios

platform :ios do
    desc 'Run CI sequence'
    lane :ci do |options|
        puts options
        build_and_release(options)
    end

    desc 'Distribute the app to TestFairy'
    lane :build_and_release do |options|
        release_notes = options[:release_notes] || raise('Error: Must specify release notes')
        build_number = options[:build_number] || ENV['BUILD_NUMBER'] || raise('No build number specified')
        version_number = get_version_number

        download_signing_identity

        ['Production', 'Demo', 'QA', 'Development'].each do |environment|
            build(build_number: build_number, environment: environment, version_number: version_number)
            release(build_number: build_number, environment: environment, release_notes: release_notes)
        end

        build_production_testflight(version_number: version_number, build_number: build_number)
    end

    desc 'Build production for testflight'
    lane :build_production_testflight do |options|
        version_number = options[:version_number] || raise('No version number specified')
        build_number = options[:build_number] || raise('No build number specified')
        increment_version_number(version_number: version_number)
        increment_build_number(build_number: build_number)

        match(type: 'appstore', readonly: true)

        productionIpaFile = " *********_Production.ipa"
        gym(scheme: "Production", clean: true, output_name: productionIpaFile)

        productionBuildDir = "/Users/*********/build/production/#{build_number}"
        Dir.mkdir(productionBuildDir)
        puts "Our directory is #{Dir.pwd}"
        FileUtils.mv("../#{productionIpaFile}", productionBuildDir)
    end

    #####################
    ### Private Lanes ###
    #####################

    private_lane :download_signing_identity do
        ProvisioningProfiles.delete_local

        match(type: 'development', readonly: true)
        match(type: 'adhoc', readonly: true)
    end

    private_lane :build do |options|
        version_number = options[:version_number]
        build_number = options[:build_number]
        environment = options[:environment]

        updated_version_number = version_number + '-' + environment.downcase
        increment_version_number(version_number: updated_version_number)
        increment_build_number(build_number: build_number)

        gym(scheme: "#{environment}",
            clean: true,
            output_name: " *********_#{environment}.ipa",
            include_bitcode: false,
            export_options: {
                compileBitcode: false,
                uploadSymbols: true,
                uploadBitcode: false
            })
    end

    private_lane :release do |options|
        build_number = options[:build_number]
        environment = options[:environment]
        release_notes = options[:release_notes]
        
        distribution_group = "*********-#{environment.downcase}"
        testfairy_comment = "Environment: #{environment}\nBuild: #{build_number}\nDistribution Group: #{distribution_group}\nRelease Notes:\n#{release_notes}"
        testfairy(api_key: '*********', comment: testfairy_comment, testers_groups: [distribution_group], notify: 'on')
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "*********" # The bundle identifier of your app
apple_id "*********" # Your Apple email address
team_id "*********"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.79.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| slack-notifier        | 2.3.2        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.4        |
| tty-cursor            | 0.5.0        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.5        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| openssl               | 2.0.2        |
| highline              | 1.7.10       |
| io-console            | 0.4.6        |
| excon                 | 0.60.0       |
| CFPropertyList        | 2.3.6        |
| mini_portile2         | 2.1.0        |
| nokogiri              | 1.6.8.1      |
| plist                 | 3.4.0        |
| faraday               | 0.14.0       |
| faraday_middleware    | 0.12.2       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| os                    | 0.9.6        |
| googleauth            | 0.6.2        |
| signet                | 0.8.1        |
| fastimage             | 2.1.1        |
| json                  | 2.1.0        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.4        |
| bundler               | 1.16.1       |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
</details>

*generated on:* **2018-01-30**
</details></pre>
</details>

**Comment by farshadtx** [comment]
Any update on this issue, I added verbose flag to the runner and it is timeout error but the build goes out. Is there any global timeout parameter we can change and fix this?

**Comment by KrauseFx** [comment]
It looks like it's an issue with testfairy - can you run testfairy directly without fastlane with no issues/

**Comment by farshadtx** [comment]
@KrauseFx 

Yes, I tried it multiple times and it looks working individually. You are right it looks like Testfairy issue and somehow they delay, but we may be able to set the timeout on this action (down to Faraday) to be able to prevent this failure.

**Comment by KrauseFx** [comment]
If you want to, feel free to submit a PR for this, however unfortunately we can't invest time in working around bugs of a third party library

**Comment by farshadtx** [comment]
I'm working with one of Testfairy's support agent to figure out why is this happening first. If it's something we can control in action level sure I will make a PR.

**Comment by KrauseFx** [comment]
Awesome, thanks 👍

**Comment by joshdholtz** [comment]
@farshadtx Heyyyy 👋 Were you able to figure this out with Testfairy's support?

**Comment by farshadtx** [comment]
@joshdholtz Yes, they said it was a bug on their end and fixed it. I haven't had that failure for about a month.
