### ISSUE TITLE
Find total time saved by fastlane

### ISSUE THREAD

**Issue by tejas-ardeshna** [fastlane/fastlane#11748]
After each execution Fastlane tools shows a number of minutes saved by it, But can I find total mins of all execution (lifetime) saved by Fastlane.

**Comment by taquitos** [comment]
Are you trying to find total minutes saved over the lifetime of your project? If that's the case, we don't record that 😞 
You could probably build a plugin though that persists that information somewhere 🎉  https://docs.fastlane.tools/plugins/create-plugin/#create-your-own-plugin

**Comment by marcpalmer** [comment]
I would actually say this existing feature should be removed or changed. Fastlane hasn't saved me that time, it has just run for that time. These are completely different things.
