### ISSUE TITLE
match could not create another development certificate right after match init

### ISSUE THREAD

**Issue by flashspys** [fastlane/fastlane#11745]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have a problem with match. Right after `match init`it fails with the message:
> Could not create another Development certificate, reached the maximum number of available Development certificates.

But that is not right as we can create new dev certificates in the developer portal manually. The match repo is still empty.
The output of `fastlane match development`:

<details>
  <pre> > fastlane match development --verbose       
[⠙] 🚀 /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/user_interaction.rb:334: warning: constant ::Data is deprecated
[✔] 🚀 
Successfully loaded Appfile at path '/xxx/fastlane/Appfile'
- app_identifier: 'de.xxx'
- apple_id: 'xxx'
- team_id: 'xxx'
- itc_team_id: 'xxx'
-------
INFO [2018-01-31 11:35:48.24]: Successfully loaded 'xxx/fastlane/Matchfile' 📄

+----------------+-------------------------------------------------------------------+
|                    Detected Values from './fastlane/Matchfile'                     |
+----------------+-------------------------------------------------------------------+
| git_url        | git@xxx:xxx/match.git |
| type           | development                                                       |
| app_identifier | xxx
| username       | xxx                                |
+----------------+-------------------------------------------------------------------+

+-----------------------+-------------------------------------------------------------------+
|                                 Summary for match 2.79.0                                  |
+-----------------------+-------------------------------------------------------------------+
| verbose               | true                                                              |
| type                  | development                                                       |
| git_url               | git@xxx:xxx/match.git |
| git_branch            | master                                                            |
| app_identifier        | ["de.xxx"]                          |
| username              | developer@xxx                                |
| keychain_name         | login.keychain                                                    |
| readonly              | false                                                             |
| team_id               | xxx                                                        |
| force                 | false                                                             |
| skip_confirmation     | false                                                             |
| shallow_clone         | false                                                             |
| clone_branch_directly | false                                                             |
| force_for_new_devices | false                                                             |
| skip_docs             | false                                                             |
| platform              | ios                                                               |
+-----------------------+-------------------------------------------------------------------+

INFO [2018-01-31 11:35:48.26]: Cloning remote git repo...
INFO [2018-01-31 11:35:48.26]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-01-31 11:35:48.26]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@xxx:xxx/match.git' '/var/folders/j8/6ck2pfn94rl411_pz074gsf80000gn/T/d20180131-12387-27n9gg'
INFO [2018-01-31 11:35:48.28]: ▸ Cloning into '/var/folders/j8/6ck2pfn94rl411_pz074gsf80000gn/T/d20180131-12387-27n9gg'...
INFO [2018-01-31 11:35:48.80]: ▸ warning: You appear to have cloned an empty repository.
INFO [2018-01-31 11:35:48.84]: 🔓  Successfully decrypted certificates repo
INFO [2018-01-31 11:35:48.88]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2018-01-31 11:35:52.03]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+--------------------------------------------------+
|                     Summary for cert 2.79.0                      |
+---------------+--------------------------------------------------+
| development   | true                                             |
| force         | true                                             |
| username      | developer@xxx               |
| team_id       | X6AUNVT82L                                       |
| keychain_path | /Users/xxx/Library/Keychains/login.keychain-db |
| platform      | ios                                              |
+---------------+--------------------------------------------------+

INFO [2018-01-31 11:35:52.04]: Starting login with user 'developer@xxx'
INFO [2018-01-31 11:35:54.27]: Successfully logged in

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not create another Development certificate, reached the maximum number of available Development certificates.

URL: https://api.github.com/search/issues?q=Could%20not%20create%20another%20Development%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Development%20certificates.+repo:fastlane/fastlane
➡️  Match can't find certificate in repo if run again.
    https://github.com/fastlane/fastlane/issues/10489 [open] 28 💬
    3 days ago

➡️  Match profiles become ineligible when having multiple projects
    https://github.com/fastlane/fastlane/issues/11101 [open] 11 💬
    2 weeks ago

➡️  Match "Couldn't find a valid code signing identity in the git repo for development"
    https://github.com/fastlane/fastlane/issues/10512 [closed] 6 💬
    3 days ago

and 23 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20create%20another%20Development%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Development%20certificates.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Could not create another Development certificate, reached the maximum number of available Development certificates.
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/fastlane_core/lib/fastlane_core/ui/ui.rb:16:in `method_missing'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/cert/lib/cert/runner.rb:158:in `rescue in create_certificate'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/cert/lib/cert/runner.rb:153:in `create_certificate'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/cert/lib/cert/runner.rb:44:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/cert/lib/cert/runner.rb:13:in `launch'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/match/lib/match/generator.rb:25:in `generate_certificate'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/match/lib/match/runner.rb:100:in `fetch_certificate'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/match/lib/match/runner.rb:57:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/match/lib/match/commands_generator.rb:61:in `block (3 levels) in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/match/lib/match/commands_generator.rb:146:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/match/lib/match/commands_generator.rb:19:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.79.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.69.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sync_code_signing(type: "appstore") # more information: https://codesigning.guide
    build_app(scheme: "xxx") # more options available
    upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "xxx") # more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "de.xxx" # The bundle identifier of your app
apple_id "developer@xxx" # Your Apple email address

team_id "xxx" # Developer Portal Team ID
itc_team_id "xxx"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.79.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-01-31**
</details></pre>
</details>

**Comment by taquitos** [comment]
I can't reproduce this problem, maybe you should clear our your development certs (there should only be 2, at most)
And then try match again.
That usually works for me.

Another possibility is that you might be using different accounts, or selecting the wrong team somehow.

**Comment by flashspys** [comment]
`fastlane match nuke` fixed everything. Thank you.
