### ISSUE TITLE
Fastlane 2.79.0: 'include_symbols' value must be either `true` or `false`! Found String instead.

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#11746]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I update fastlane to lastest version, I got the error:

` 'include_symbols'  value must be either `true` or `false`! Found String instead.`

<details>
17:34:25]: [32m-----------------[0m
[17:34:25]: [32m--- Step: gym ---[0m
[17:34:25]: [32m-----------------[0m
[17:34:25]: [32mSuccessfully loaded '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-Hotfix/workspace/fastlane/Gymfile' 📄[0m

+----------------------+----------------------------------------------------------+
|                    Detected Values from './fastlane/Gymfile'                    |
+----------------------+----------------------------------------------------------+
| output_directory     | ./build/                                                 |
| output_name          |                                                |
| include_symbols      | false                                                    |
| include_bitcode      | false                                                    |
| codesigning_identity | iPhone Distribution: Operations B.V. () |
| xcargs               | PROVISIONING_PROFILE_SPECIFIER=''                        |
| configuration        | Fastlane                                                 |
+----------------------+----------------------------------------------------------+
+------------------------------------+--------------------------------------------------------------------+
|                                              [33mLane Context[0m                                               |
+------------------------------------+--------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                |
| PLATFORM_NAME                      | ios                                                                |
| LANE_NAME                          | ios upload_hockey                                                  |
| SIGH_PROFILE_TYPE                  | ad-hoc                                                             |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"au.com.360"=>"match AdHoc au.com.360"} |
| BUILD_NUMBER                       | 641                                                                |
| XCODEBUILD_DERIVED_DATA_PATH       |                                                                    |
+------------------------------------+--------------------------------------------------------------------+
[17:34:27]: [31m'include_symbols' value must be either `true` or `false`! Found String instead.[0m
[17:34:27]: [31mfastlane finished with errors[0m
[31m
[!] 'include_symbols' value must be either `true` or `false`! Found String instead.[0m
</details>

### **Note:**  I back to version 2.70.2, I got the error:
`'app_identifier' value must be a Array! Found String instead`
<details>
`[17:42:59]: [32m--- Step: match ---[0m
[17:42:59]: [32m-------------------[0m
[17:43:00]: [32mSuccessfully loaded '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-Hotfix/workspace/fastlane/Matchfile' 📄[0m

+-----------------------+----------------------------------------------------------------+
|                      Detected Values from './fastlane/Matchfile'                       |
+-----------------------+----------------------------------------------------------------+
| git_url               | git@abc.xyz/Match.git |
| type                  | appstore                                                       |
| force_for_new_devices | true                                                           |
| team_name             | Operations B.V.                                         |
| username              | developers@360.com                                       |
| app_identifier        | au.com.360                                        |
| skip_docs             | true                                                           |
| git_branch            | 360_Preview                                              |
+-----------------------+----------------------------------------------------------------+

[17:43:02]: [31m'app_identifier' value must be a Array! Found String instead`
</details>
- I back to version 2.64.1. it ok.

### Environment
<details>
 <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.64.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-01-31**
</details>
</details>

**Comment by taquitos** [comment]
Hey @biolinh could add `--verbose` to the command you are running and then post the entire output (using `2.79.0`)? 

> 'app_identifier' value must be a Array! Found String instead
was fixed in a later version 🎉

**Comment by biolinh** [comment]
Fastlane --verbose
Note that: i use transfer value to environment variable when build app.
<detail>
Jenkinss-Mac-mini:workspace jenkins$ fastlane --verbose
[✔] 🚀
[10:07:53]: fastlane detected a Gemfile in the current directory
[10:07:53]: however it seems like you don't use `bundle exec`
[10:07:53]: to launch fastlane faster, please use
[10:07:53]:
[10:07:53]: $ bundle exec fastlane --verbose
[10:07:53]:
[10:07:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
WARN [2018-02-01 10:07:53.04]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:53.04]: In the config file './fastlane/Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
INFO [2018-02-01 10:07:53.37]: Successfully loaded custom action '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/actions/app_name.rb'.
INFO [2018-02-01 10:07:53.37]: Successfully loaded custom action '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/actions/build_number_icon.rb'.
INFO [2018-02-01 10:07:53.37]: Successfully loaded custom action '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/actions/color_icon.rb'.
INFO [2018-02-01 10:07:53.37]: Successfully loaded custom action '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/actions/propertylint.rb'.
DEBUG [2018-02-01 10:07:53.37]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.57]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.57]: In the config file './fastlane/Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.61]: You have require'd a gem, if this is a third party gem, please use `fastlane_require 'dotenv'` to ensure the gem is installed locally.
INFO [2018-02-01 10:07:54.66]: gem 'dotenv' is already installed
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.67]: In the config file './Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.67]: In the config file './Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
INFO [2018-02-01 10:07:54.71]: ----------------------------------------
INFO [2018-02-01 10:07:54.71]: --- Step: Verifying fastlane version ---
INFO [2018-02-01 10:07:54.71]: ----------------------------------------
INFO [2018-02-01 10:07:54.71]: Your fastlane version 2.79.0 matches the minimum requirement of 1.89.0  ✅
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.71]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.72]: In the config file './fastlane/Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.72]: In the config file './Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.72]: In the config file './Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
INFO [2018-02-01 10:07:54.75]: ------------------------------
INFO [2018-02-01 10:07:54.75]: --- Step: default_platform ---
INFO [2018-02-01 10:07:54.75]: ------------------------------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.76]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.76]: In the config file './fastlane/Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.76]: In the config file './Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.76]: In the config file './Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/jobs/RX-360-Fastlane-QA/workspace/fastlane/Appfile'
-------
WARN [2018-02-01 10:07:54.79]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
WARN [2018-02-01 10:07:54.79]: In the config file './fastlane/Matchfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
INFO [2018-02-01 10:07:54.80]: Welcome to fastlane! Here's what your app is setup to do:
+--------+--------------------------+----------------------------------+
|                        Available lanes to run                        |
+--------+--------------------------+----------------------------------+
| Number | Lane Name                | Description                      |
+--------+--------------------------+----------------------------------+
| 1      | ios UITest               | Runs all the testcase            |
| 2      | ios createnewapp         | Create new iOS apps on iTunes    |
|        |                          | Connect and Dev Portal for the   |
|        |                          | firtst time                      |
| 3      | ios appleprovision       | Creating a code signing          |
|        |                          | certificate and Apple            |
|        |                          | provisionning profile            |
| 4      | ios adhocprovision       |                                  |
| 5      | ios beta                 | Submit a new Beta Build to       |
|        |                          | Apple TestFlight This will also  |
|        |                          | make sure the profile is up to   |
|        |                          | date                             |
| 6      | ios upload_ipa           | Upload iPA to Apple Store        |
| 7      | ios upload_appstore      | Deploy a new version to the App  |
|        |                          | Store                            |
| 8      | ios appstore_match       | Deploy a new version to the App  |
|        |                          | Store using Match                |
| 9      | ios upload_hockey        | Deploy a new version to the      |
|        |                          | hockey                           |
| 10     | ios BrandedApp_QA_hockey | Deploy a new version to the      |
|        |                          | hockey                           |
| 11     | ios generate_appicon     |                                  |
| 12     | ios test                 |                                  |
| 0      | cancel                   | No selection, exit fastlane!     |
+--------+--------------------------+----------------------------------+
 [2018-02-01 10:07:54.81]: Which number would you like run?
</detail>
Fastlane env:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.79.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2018-02-01**
</details>

**Comment by KrauseFx** [comment]
It seems like the formatting broke when posting somehow. Also it seems like the error might be related to a custom local action?
