### ISSUE TITLE
Mute Siri say command

### ISSUE THREAD

**Issue by lolgear** [fastlane/fastlane#11750]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I use Siri say command to notify about possible errors or mistakes that I've made in release distribution ( oh, CI ).

However, I would like to define local_say function which could check fast lane option "mute_siri" or something to mute Siri.

Is it possible to do via fast lane tools?

Thanks!

My possible solution:

```ruby
def say_or_write(message)
    if ENV["SIRI_ALLOWED"]
       say message
    else
       puts message
    end
end
```

**Comment by PetrosIchor** [comment]
I don't believe there is, but you could write it much shorter with a ternary operator instead of defining a method. 

`ENV['SIRI_ALLOWED'].eql?(true) ? say(message) : UI.message(message)`

**Comment by lolgear** [comment]
@PetrosIchor do you know where say command is defined?

**Comment by lolgear** [comment]
Not good name, functionality could be inserted into UI as `say_or_write` or just `say`.

```ruby
  class Voice
    class << self
      def say(messages)      
        if ENV["SIRI_VOICE"] == "1"
          # not sure where it is defined.
          Fastlane::Actions::SayAction.run messages
        else
          write messages
        end
      end
      def write(messages)
        UI.message messages
      end
    end
  end
```

**Comment by lolgear** [comment]
Bot is ok, please, anybody, take attention to this issue as feature request, thanks!

@KrauseFx, Could this integration of Siri and UI message be done in recent (future?) releases?
