### ISSUE TITLE
Check for changelog on externally distributed pilot builds

### ISSUE THREAD

**Issue by getaaron** [fastlane/fastlane#11753]
Distributing a TestFlight build to external testers will fail if a changelog is not specified.

Currently this fails after the lengthy build processing process like so:

```
[13:09:26]: Successfully finished processing the build 1.0 - 11
[13:09:26]: Distributing new build to testers: 1.0 - 11
[13:09:28]: Sending crash report...
[13:09:28]: The stack trace is sanitized so no personal information is sent.

[…snip…]

[13:09:28]: {"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."}
```

We could check for this condition in the `upload` method:

https://github.com/fastlane/fastlane/blob/30bb1c4514a59c4ca2af4107b086e56408ece7c6/pilot/lib/pilot/build_manager.rb#L11-L53

e.g. if `options[:changelog]` is empty and `options[:distribute_external] == 'External'` then show a helpful `UI.user_error!` without making the user wait 20 minutes.

A side enhancement that could be done alongside this work is to load `changelog` from a metadata file, like [how _deliver_'s `UploadMetadata` class does it](https://github.com/fastlane/fastlane/blob/30bb1c4514a59c4ca2af4107b086e56408ece7c6/deliver/lib/deliver/upload_metadata.rb) (search for 'loader'). This would be helpful for CI tools that don't support parameterized builds (like CircleCI).

**Comment by RishabhTayal** [comment]
@getaaron Should add this check for `deliver` action as well?
