### ISSUE TITLE
Can't update via Mac App from 2.78.0

### ISSUE THREAD

**Issue by realpb** [fastlane/fastlane#11754]
I'm usually able to update from within the Mac App but today I'm stuck in a 2.78 loop.
1. I uninstall via App (fastlane tab)
2. I check for previous versions via Terminal (it returns: No previous installation found. Now installing fastlane via the Fabric Mac app 🚀)
3. Install completes. 
4. It still says 2.78 (and not 2.79) and I get the error message below when trying to Distribute Beta Builds. 

Thanks in advance for any help you can give.

(BTW, other things I have tried: sudo gem update fastlane & sudo gem cleanup )

Unknown fastlane error: 
[32m#######################################################################[0m
[32m# fastlane 2.79.0 is available. You are on 2.78.0.[0m
[32m# You should use the latest version.[0m
[32m# Please update using `the Fabric app. Launch the app and navigate to the fastlane tab to get the most recent version.`.[0m
[32m#######################################################################[0m

[fastlane-env-output.txt](https://github.com/fastlane/fastlane/files/1683987/fastlane-env-output.txt)

**Comment by realpb** [comment]
Sorry, I added the env info (attached as a text file) to my original post.

**Comment by KrauseFx** [comment]
Hey @realpb, thanks for submitting the issue. We recently published a guide on how to migrate to the recommended way of installing _fastlane_ https://github.com/fastlane/fastlane/issues/11586

Let me know if that helps 👍

**Comment by realpb** [comment]
Update: I uninstalled Fastlane via Fabric Mac app, then deleted Fabric. 
I installed Fastlane using command line tools. Success. 2.79
Then I downloaded Fabric Mac App again, and clicked on the Fastlane tab and it says "upgrade to 2.78" LOL.
<img width="313" alt="screen shot 2018-02-01 at 8 50 33 am" src="https://user-images.githubusercontent.com/1487466/35687940-482b85fc-072d-11e8-9061-64d59998732c.png">

Update: Then I rebooted and Fabric prompted me to reinstall (although it was already installed) and then after I went through the screens (in the Fabric Mac App) it changed to Fastlane 2.79 installed. 

BUT... I'm still unable to select a scheme when trying to distribute a build.

I'll take a look at the doc you just posted. Thank you.

**Comment by realpb** [comment]
Thanks @KrauseFx - I followed the instructions but I was getting a "Error parsing Xcode file" error. I reinstalled Xcode but same result.

<img width="576" alt="fastlane-xcode-error" src="https://user-images.githubusercontent.com/1487466/35691716-76ca51a0-0736-11e8-9c66-5b50a9f20f00.png">

But I tried to fix the Xcode-select path:
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

and that worked.  (meaning that I can now select a Scheme to distribute via Fabric app)

But then... I got this error.
One thing after another :/

<img width="323" alt="screen shot 2018-02-01 at 10 16 56 am" src="https://user-images.githubusercontent.com/1487466/35692683-37b5325c-0739-11e8-924f-a62ba7073a45.png">

Any ideas about this last error message?
Thanks.

**Comment by KrauseFx** [comment]
That doesn't seem to be related to the installation method though, it has something to do with your Xcode project

**Comment by realpb** [comment]
@KrauseFx You're right - after I relied on your documentation #11586 it installed well (after may local hiccup).
But what about the final screen shot I sent? 
Unknown Fastlane error: invalid option: --crashlytics_path
Was wondering if you had any thoughts about that. 
Thanks,
Paul

**Comment by joshdholtz** [comment]
@realpb Heyyy 👋 Were you able to get this solved? If not, what command were you trying to use with `--crashlytics_path`?
