### ISSUE TITLE
Disallow build_app as a lane name

### ISSUE THREAD

**Issue by buscarini** [fastlane/fastlane#11769]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I had a lane named build_app, which worked fine with older versions of fastlane, as far as I can remember. Now if I use the lane directly it works ok, but if the lane is used from another one, fastlane interprets that I'm using the build_app action and later it complains that it can't find the project path, the scheme, etc. I was very confused by this, and it took me a long time to figure out the name clashing.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.

fastlane_version "1.11.0"

default_platform :ios

platform :ios do
  
  before_all do
        
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    #cocoapods

    # increment_build_number

    # ipa({
    #   scheme: ""
    # })

    #xctool # run the tests of your app
  end


  
  ## 
  ## Create in App Store
  ## 

  desc "Create in app store"
  lane :create do
    produce(
      username: File.read("Config/apple_id.txt"), 
      app_identifier: File.read("Config/app_identifier.txt"), 
      app_name: File.read("Config/name.txt"),
      language: "English",
      app_version: File.read("metadata/currentVersion.txt"),
      sku: File.read("Config/app_identifier.txt")
    )

  end
 

  ##
  ## Match for all certificates
  ##

  lane :certificates do

    match_appstore
    match_development
    match_adhoc

  end

  lane :match_appstore do
    match(
        type: "appstore",
        git_url: File.read("Config/certs_repo_url.txt"),
        app_identifier: File.read("Config/app_identifier.txt"),
        username: File.read("Config/apple_id.txt")
      )
  end

   lane :match_development do
    register_devices(devices_file: "fastlane/Config/devices.txt") 
    match(
      git_url: File.read("Config/certs_repo_url.txt"),
      app_identifier: File.read("Config/app_identifier.txt"),
      type: "development",
      username: File.read("Config/apple_id.txt")
    )
  end

  lane :match_adhoc do
    match(
      git_url: File.read("Config/certs_repo_url.txt"),
      app_identifier: File.read("Config/app_identifier.txt"),
      type: "adhoc",
      username: File.read("Config/apple_id.txt")
    )
  end



  ##
  ## Match for enterprise certificates
  ##

  lane :match_enterprise do

  	match_enterprise_dev
  	match_enterprise_release

  end


  ##
  ## Match for enterprise dev
  ##

  lane :match_enterprise_dev do

    register_devices(devices_file: "fastlane/Config/devices.txt")

  	match(
  		git_url: File.read("Config/Enterprise/certs_repo_url.txt"),
  		app_identifier: "*", # File.read("Config/Enterprise/app_identifier.txt"),
  		type: "development",
  		username: File.read("Config/Enterprise/apple_id.txt"),
      force: true
  	)

  end


  ##
  ## Match for enterprise release
  ##

  lane :match_enterprise_release do

  	match(
  		git_url: File.read("Config/Enterprise/certs_repo_url.txt"),
  		app_identifier: File.read("Config/Enterprise/app_identifier.txt"),
  		type: "appstore",
  		username: File.read("Config/Enterprise/apple_id.txt")
  	)

  end


  ##
  ## Push DEV
  ##


  desc "Generate Dev certs. Accepts force option with force:true"
  lane :push_dev do |options|
    
    pem(development: true,
        generate_p12: true,
        save_private_key: true,
        force: options[:force],
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    # match_development

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]


  end



  ## 
  ## Push PROD
  ## 

  desc "Generate Prod Push certs. Accepts force option with force:true"
  lane :push_prod do |options|
    
    pem(generate_p12: true,
        save_private_key: true,
        force: options[:force],
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    match_appstore

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

  end


  ## 
  ## Push DEMO
  ## 

  desc "Generate Demo Push certs. Accepts force option with force:true"
  lane :push_demo do |options|
    
    pem(generate_p12: true,
        save_private_key: true,
        force: options[:force],
        p12_password: File.read("Config/push_password.txt"),
        new_profile: Proc.new do |profile_path|
          puts "------ New .p12 generated ------" + profile_path.yellow
          end)

    # certificates

    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]


  end


  ##
  ## Build IPA
  ##

  desc "Build app"
  lane :build_the_app do

    gym(
      workspace: "../Code/" + File.read("./Config/workspace.txt") + ".xcworkspace",
      scheme: File.read("Config/scheme.txt"),
      # xcargs: "CODE_SIGN_IDENTITY='...' PROVISIONING_PROFILE='#{ENV["PROFILE_UDID"]}'",
      configuration: "Release",
      clean: true,
      silent: true
    )

  end


  ## 
  ## Test App
  ## 

  desc "Test app"
  lane :test_app do
    xctool :test,["-workspace", "../Code/" + File.read("./Config/workspace.txt") + ".xcworkspace",
            "-scheme", File.read("Config/scheme.txt"),
            "-configuration","Release",
            "-sdk","iphoneos"].join(" ")
  end


  ## 
  ## Test
  ## 

  desc "Runs all the tests"
  lane :test do
    cocoapods
    build_the_app
    test_app
  end
  
  
  ## 
  ## Screenshots
  ## 

  desc "Takes screenshots for configured devices/languages"
  lane :screenshots do

    snapshot

  end
  
  
  ## 
  ## Update App Store Metadata
  ## 

  desc "Update App Store metadata"
  lane :metadata do

    deliver(skip_screenshots: true)

  end


  ## 
  ## Upload ipa
  ## 

  desc "Deploy a new version to the App Store"
  lane :uploadIpa do

      push_prod
 
      build_the_app
             
      deliver(force: true,
        skip_screenshots: true,
        skip_metadata: true)
    
  end


  ## 
  ## Deploy to App Store & Beta ITC
  ## 

  desc "Deploy a new version to the App Store"
  lane :deploy do

      push_prod
 
      build_the_app
             
      deliver(force: true)

  end



  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(message: "The lane " + lane + " completed successfully")
  end


  error do |lane, exception|
    # slack(message: exception.message,
    #       success: false)
  end

end


# More information:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id File.read("Config/apple_id.txt")
app_identifier File.read("Config/app_identifier.txt")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.5        |
| slack-notifier            | 2.3.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| CFPropertyList            | 2.3.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.4        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
</details>

*generated on:* **2018-02-02**
</details></pre>
</details>

**Comment by KrauseFx** [comment]
I'm pretty sure _fastlane_ should show a warning if you have a lane called after an action. Are you sure that's not the case?

**Comment by getaaron** [comment]
We check for this and emit a warning here:

https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/fastlane/lib/fastlane/lane.rb#L43-L58

There are three levels of warning:

- blacklist gets the `UI.user_error!` treatment
- grey list gets `UI.error`
- actions gets `UI.important`

We might want to consider switching these all to `user_error!` on some upcoming major release. It will break existing implementations but I think in the long run would reduce confusion.

A less severe improvement would be to ask if the user wants to continue if in interactive mode. This would avoid breaking CI pipelines at least.

**Comment by buscarini** [comment]
I agree with switching to an error. I work at a consulting company, we have a lot of projects and in all of them we are using build_app as a lane name. I haven't noticed this warning until now that you mention it. It's just one line that is very easy to miss when you have lots of output from Xcode.

**Comment by KrauseFx** [comment]
Agreed that it would be nice, but we can't do that, as it would break setups that already use the names at this point, and also it would potentially break setups every time we add a new action to fastlane

**Comment by KrauseFx** [comment]
I'm gonna take a look at this as part of https://github.com/fastlane/fastlane/issues/11785
