### ISSUE TITLE
No value found for 'username' CircleCI

### ISSUE THREAD

**Issue by jwilson85** [fastlane/fastlane#11762]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Im getting ***No value found for 'username'*** even though my appfile has a value for apple_id.
Im trying the cert and sigh method explained here: https://docs.fastlane.tools/codesigning/getting-started/ 
You can see that in my fast file

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
#!/bin/bash -eo pipefail
fastlane ent
^D^D/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[16:38:55]: fastlane detected a Gemfile in the current directory
[16:38:55]: however it seems like you don't use `bundle exec`
[16:38:55]: to launch fastlane faster, please use
[16:38:55]: 
[16:38:55]: $ bundle exec fastlane ent
[16:38:55]: 
[16:38:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebdcd7968>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebdced3a8>
[16:38:59]: -------------------------------------------------
[16:38:59]: --- Step: Verifying required fastlane version ---
[16:38:59]: -------------------------------------------------
[16:38:59]: Your fastlane version 2.59.0 matches the minimum requirement of 2.29.0  ✅
[16:38:59]: ------------------------------
[16:38:59]: --- Step: default_platform ---
[16:38:59]: ------------------------------
[16:38:59]: Driving the lane 'ios ent' 🚀
[16:38:59]: ------------------------------------
[16:38:59]: --- Step: increment_build_number ---
[16:38:59]: ------------------------------------
Current version of project iOS-Core is: 
    1

/Users/distiller/project
[16:39:02]: $ cd /Users/distiller/project && agvtool next-version -all && cd -
[16:39:02]: ▸ Setting version of project iOS-Core to:
[16:39:02]: ▸ 2.
[16:39:02]: ▸ Also setting CFBundleVersion key (assuming it exists)
[16:39:02]: ▸ Updating CFBundleVersion in Info.plist(s)...
[16:39:02]: ▸ $(SRCROOT)/iOS-Core/client/Info.plist
[16:39:02]: ▸ Cannot find "$(SRCROOT)/iOS-Core/client/Info.plist"
[16:39:02]: ▸ Updated CFBundleVersion in "iOS-Core.xcodeproj/../PlaygroundFramework/Info.plist" to 2
[16:39:02]: ▸ Updated CFBundleVersion in "iOS-Core.xcodeproj/../iOS-CoreTests/Info.plist" to 2
[16:39:02]: ▸ Updated CFBundleVersion in "iOS-Core.xcodeproj/../iOS-CoreUITests/Info.plist" to 2
[16:39:02]: ▸ /Users/distiller/project
[16:39:03]: ------------------
[16:39:03]: --- Step: cert ---
[16:39:03]: ------------------
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfbf3b30>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfbfaa98>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfc02d10>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfc0a538>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfc126c0>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfc1b978>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfc23b28>
undefined method `fastlane_password' for #<CredentialsManager::AppfileConfig:0x007ffebfc2bd00>

+---------------+------------------------------------------------------+
|                       Summary for cert 2.59.0                        |
+---------------+------------------------------------------------------+
| development   | false                                                |
| force         | false                                                |
| keychain_path | /Users/distiller/Library/Keychains/login.keychain-db |
| platform      | ios                                                  |
+---------------+------------------------------------------------------+

[16:39:03]: Sending crash report...
[16:39:03]: The stack trace is sanitized so no personal information is sent.
[16:39:03]: To see what we are sending, look here: /Users/distiller/.fastlane/latest_crash.json
[16:39:03]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[16:39:03]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
[16:39:04]: ---------------------
[16:39:04]: --- Step: hipchat ---
[16:39:04]: ---------------------
+------------------+---------+
|        Lane Context        |
+------------------+---------+
| DEFAULT_PLATFORM | ios     |
| PLATFORM_NAME    | ios     |
| LANE_NAME        | ios ent |
| BUILD_NUMBER     | 2       |
+------------------+---------+
[16:39:04]: No value found for 'username'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 4           |
| 💥   | cert                                | 0           |
| 5    | hipchat                             | 0           |
+------+-------------------------------------+-------------+

[16:39:04]: fastlane finished with errors

[!] No value found for 'username'

#######################################################################
# fastlane 2.79.0 is available. You are on 2.59.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.79.0 Improvements
* Change update message color from green to default terminal color (#11698) via Felix Krause
* [Fastlane.swift] Support printing out console log from Swift (#11625) via Thi
* Read files as UTF8 or binary explicitly (#11678) via Jan Piotrowski
* Fix plugin search only returns plugins which have search query as (#11639) via Thi
* [frameit] Fix vertical padding and spacing between keyword and multi-line title when using the stacked title option (issue #11646) (#11661) via funnel20
* [frameit] prevent too large multi line text (issue #11585) (#11624) via funnel20
* Remove default value for initial_build_number (#11730) via Joshua Liebowitz
* Fix duplicate loading of Gymfile if there is only one Gymfile (#11718) via Thi
* Fix usage of FastlanePty.spawn() (#11688) via Robin Kunde
* Update podspec CocoaPods version regex to work with new `swift_version` in CocoaPods 1.4.0 (#11702) via Felix Krause
* Instructions on how to run specific unit test or unit test group (#11685) via Jan Piotrowski
* Disable pager explicitly for * git_branch_pager (#11689) via Robin Kunde
* Don't check for executable files on Windows (#11679) via Jan Piotrowski
* Fallback for PTY (#11671) via Jan Piotrowski
* better cross platform tests (#11677) via Jan Piotrowski
* Replace hard coded test paths (e.g. /tmp) (#11427) via Jan Piotrowski
* Parallelize CI (#11456) via Jan Piotrowski

2.78.0 Improvements
* Download screenshots: add `use_live_version` option (#11640) via Andrea Cipriani
*  Swift Runner Upgrader always finds something to upgrade (#11635) via Joshua Liebowitz
* Missing cert expiration in nuke causes crash (#11631) via Joshua Liebowitz
* Do not show step text for environment_variable action. (#11626) via Thi
* sort candidate_builds by upload_date (#11602) via Taras Vozniuk
* Appaloosa action - Enforce API_KEY on private signed form (#11545) via Benoit Tigeot
* Fix `fastlane init` crash when having no iOS or Android project (#11621) via Felix Krause

2.77.1 Fix for crash when things go wrong while using fastlane.swift
* Missing variable fix for socket_server (#11616) via Joshua Liebowitz
* Version bump to 2.77.1 (#11617) via Joshua Liebowitz

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
Exited with code 1
</pre>
</details>

### Environment

<details>
  <pre>
# Enerprise Distribution Account

app_identifier "com.axxx.lyon-beta" # The bundle identifier of your app
apple_id "mobile@xxxxxx.com" # Your Apple email address
team_id "E65xxxxx" # Developer Portal Team ID

# App Store Production Account

  for_lane :release do
    app_identifier 'com.xxxx.lyon' # The bundle identifier of your app
    apple_id 'mobile-accounts@axxxx.com' # Your Apple email address
    team_id 'MZEHxxxxx' # Developer Portal Team ID
  end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
</pre>
</details>

I also have FASTLANE_PASSWORD set in the circleCI env varibles that allowed me to get to this point. I feel like im so close and I just need to get over this hump. 

**also here is my fastFile so you can see what im trying to do it's messy currently but im running the ent lane**

<details>
<pre>

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.29.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["HIPCHAT_API_TOKEN"] = "0021438866bda6526b53da70db5391"
    # cocoapods
  end

  #Create a provisioning profile
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: 'com.activewebsite.lyon',
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end

  #end provisioning 

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build Enterprise IPA"
  lane :ent do
    increment_build_number
    cert           # invokes cert
    sigh   # invokes sigh
    gym(scheme: "iOS-Core")
    hipchat(
        version: "1",
        channel: "3838648",
        message: "A new version of Lyon is available on the FTP." # "Mobile Build Room"
      )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    sigh(
      adhoc: false # otherwise sigh will produce an ad-hoc profile
    )
    gym(scheme: "iOS-Core") # Build your app - more options available
    sh "./upload.sh"
    hipchat(
      version: "1",
      channel: "3838648",
      message: "A new version of Lyon is available on the FTP." # "Mobile Build Room"
    )
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    sigh(
      adhoc: false # otherwise sigh will produce an ad-hoc profile
    )
    snapshot
    gym(scheme: "iOS-Core") # Build your app - more options available
    deliver(force: true)
        hipchat(
      version: "1",
      channel: "3838648",
      message: "A new version of Lyon has been uploaded to iTunes Connect." # "Mobile Build Room"
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|
    hipchat(
      version: "1",
      channel: "3838648",
      custom_color: "red",
      message: "Lyon build failed." # "Mobile Build Room"
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

</pre>
</details>

**Comment by KrauseFx** [comment]
Hey @jwilson85, thanks for the report. I see you have a Gemfile, but you're not using `bundle exec`, can you try using `bundle exec fastlane ...`? 
Also, can you run `bundle update` to update your dependencies, followed by `gem cleanup` to remove old gems?
Additionally, please run `[sudo] gem uninstall credentials_manager fastlane_core` and see if that helps also.

Thanks

**Comment by jwilson85** [comment]
So in the fastlane folder I have a Gymfile is that the same thing?

**Comment by KrauseFx** [comment]
The `Gymfile` is only used for building your app, so you can leave that as is

**Comment by jwilson85** [comment]
I dont see this gemfile I do have hidden files set to visible.

**Comment by jwilson85** [comment]
Better question would i tell circleCI to do bundle exec fastlane? my current circleCI config looks like this 
<details>
<pre>
# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.0"

    steps:
      - checkout:
          post:
            - git submodule sync
            - git submodule update --init


      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install


      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane ent 
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: iOS-Core

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

</pre>
</details>

**Comment by KrauseFx** [comment]
`command: fastlane ent`
replace with
`bundle exec command: fastlane ent`

**Comment by jwilson85** [comment]
maybe a mistype 
Build-agent version 0.0.4666-05dad47 (2018-01-25T18:14:33+0000)
Configuration errors: 1 error occurred:

* In step 3 (run): No command given

**Comment by jwilson85** [comment]
I think i got it 
I did command: bundle exec fastlane ent2

**Comment by jwilson85** [comment]
Hey, thank you guys for your help! I was able to run into a different roadblock after this. XD

**Comment by getaaron** [comment]
@jwilson85 Glad to hear you got it working!
