### ISSUE TITLE
Fastlane match with mulitple apps

### ISSUE THREAD

**Issue by mastermind247** [fastlane/fastlane#11766]
I have developer account with multiple apps. I am using fastlane match to generate certs and profile. Now using match it creates new certs. Check below code how I generate it.

```
lane :GenerateCerts do
match(app_identifier: "dev", type: "development")
match(app_identifier: "stage", type: "development")
match(app_identifier: "stage", type: "appstore")
end
```

I already have crossed the limit on developer account to generate new iOS Distribution certs so I am not able to generate a new one. But I guess that certificate on dev portal can be used for generating profiles.

So, How can I use the certificate already there in portal to generate profiles?

Also, I need to manually set the profiles in Xcode for different configurations. Which command could be helpful to configure certificates in Xcode generated by match, cert, sigh?

What is the best practice for following case when I have single developer account for multiple apps?

Creating different git repo for different apps for fastlane match

Single repo for all apps.

For now I am using first one. If you have any better suggestions please help.

https://stackoverflow.com/questions/48576134/fastlane-match-with-mulitple-apps

**Comment by getaaron** [comment]
I [answered this on SO](https://stackoverflow.com/a/48591262/1445366) so I'm going to close this issue and keep the discussion over there
