### ISSUE TITLE
Can spaceship revoke certs programmatically? 

### ISSUE THREAD

**Issue by fxfactorial** [fastlane/fastlane#11776]
Looking through https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md and wondering since I don't see it, does Spaceship expose APIs to revoke Apple certificates and provisioning profile?

**Comment by DeveloperBen** [comment]
Yes, there is a way to do that.
Please use
```
# Finding all certificates of the app! 
certificates = Spaceship.certificate.all.find_all {|cert| cert.owner_id == 'com.myBundleId.app'} 

# Choose a certificate from certificates array that we want to revoke (lets say the first one)
c = certificates[0]

# Revoking certificate
c.revoke!
```

Next time maybe use a quick google search. This was the first result [4395](https://github.com/fastlane/fastlane/issues/4395) which answers your question.

**Comment by fxfactorial** [comment]
Thanks! My bad about searching. I don’t see yet a corresponding way for the provisioning profile

**Comment by fxfactorial** [comment]
@DeveloperBen  Do you happen to know a way to also outright revoke a provisioning profile?

**Comment by DeveloperBen** [comment]
Sorry, I don't

**Comment by fxfactorial** [comment]
Found it!: FWIW: Provisioning profile objects have `delete!` method.

**Comment by DeveloperBen** [comment]
Great to know! I had to do it manually until now
