### ISSUE TITLE
How do I specify a specific UI Test method in my snapshot configuration?

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#11773]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

How do I specify a specific UI Test method in my snapshot configuration?

I was previously advised by @milch not use the ui test scheme, instead use the main app scheme, otherwise I'd setup another scheme for my other new ui test method. https://github.com/fastlane/fastlane/issues/10969#issuecomment-346828859

**Comment by joshdholtz** [comment]
@Jules2010 Heyyy 👋 Were you able to figure this out?

**Comment by jeromediaz** [comment]
I have had to do something like that and what I finished doing wasn't to try launching only a specific test, but using launch arguments at the start of each test to exit it if it is not the targeted test
