### ISSUE TITLE
Fastlane fails with Error: building/testing the application

### ISSUE THREAD

**Issue by arunaousula9421** [fastlane/fastlane#11789]
Hi All, I have setup fastlane for running my XCUITests, which worked as expected until last week. Some how from past week it is failing with above error.

Here's my configuration details:

```desc "Runs all the UI tests"
  lane :UITests do |options|
    scheme_to_test = "Scehem_Name"

    scan_options = {
      scheme: scheme_to_test,
      clean: true,
      output_directory: '../artifacts/tests',
      output_files: 'report.xml'
    }

    begin
      retry_count ||=0
      scan(scan_options)
    rescue => e
      UI.important("failure noted: #{e}")
      report_filepath = File.absolute_path('../artifacts/tests/report.xml')
      unless File.exist?(report_filepath)
        raise e
      end
      if (retry_count += 1) < 3
        setup_fragile_tests_for_rescan(
          project_path: File.absolute_path('../app.xcodeproj'),
          scheme: scheme_to_test,
          report_filepath: report_filepath
        )
        clear_derived_data
        reset_simulator_contents if retry_count > 0
        retry
      end
    end
  end
````

Here's the logs what it returns
```[11:24:47]: ------------------
[11:24:47]: --- Step: scan ---
[11:24:47]: ------------------
[11:24:47]: $ xcodebuild -list -workspace ./app.xcworkspace
2018-02-06 11:24:48.449 xcodebuild[27400:2138878]  DTDeviceKit: deviceType from a5d1d4a6e8558ac7f5df08dbdf2b7969d0c9d022 was NULL
[11:24:48]: $ xcodebuild -showBuildSettings -workspace ./app.xcworkspace -scheme UITests
[11:24:51]: Found simulator "iPhone 5s (11.2)"
[11:24:51]: $ xcodebuild -list -workspace ./app.xcworkspace
2018-02-06 11:24:52.499 xcodebuild[27420:2139197]  DTDeviceKit: deviceType from a5d1d4a6e8558ac7f5df08dbdf2b7969d0c9d022 was NULL
[11:24:52]: $ xcodebuild -showBuildSettings -workspace ./app.xcworkspace -scheme UITests
2018-02-06 11:24:53.793 xcodebuild[27423:2139283]  DTDeviceKit: deviceType from a5d1d4a6e8558ac7f5df08dbdf2b7969d0c9d022 was NULL
[11:24:55]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[11:25:01]: Found simulator "iPhone 5s (11.2)"

+------------------------+--------------------------------------------------------------------+
|                                   Summary for scan 2.80.0                                   |
+------------------------+--------------------------------------------------------------------+
| scheme                 | UITests                                                        |
| clean                  | true                                                               |
| output_directory       | ../artifacts/tests                                                 |
| output_files           | report.xml                                                         |
| workspace              | ./app.xcworkspace                                                 |
| derived_data_path      | /Users/arun/Library/Developer/Xcode/DerivedData/app-eemzpzapcmva  |
|                        | xlalzceqygbhqqzd                                                   |
| skip_build             | false                                                              |
| output_types           | html,junit                                                         |
| buildlog_path          | ~/Library/Logs/scan                                                |
| include_simulator_logs | false                                                              |
| open_report            | false                                                              |
| skip_slack             | false                                                              |
| slack_only_on_failure  | false                                                              |
| use_clang_report_name  | false                                                              |
| fail_build             | true                                                               |
| xcode_path             | /Applications/Xcode.app                                            |
+------------------------+--------------------------------------------------------------------+

[11:25:01]: WARNING: output_types and output_files do not have the same number of items. Default values will be substituted as needed.
[11:25:01]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./app.xcworkspace -scheme UITests -destination 'platform=iOS Simulator,id=C81DCE4B-CA00-4B58-ABD4-5BE310E5010F' -derivedDataPath '/Users/arun/Library/Developer/Xcode/DerivedData/app-eemzpzapcmvaxlalzceqygbhqqzd' clean build test | tee '/Users/arun/Library/Logs/scan/app.ie-UItests.log' | xcpretty  --report html --output '/Users/arun/Projects/artifacts/tests/report.xml' --report junit --output '/Users/arun/Projects/artifacts/tests/report.junit' --report junit --output '/var/folders/tl/gntx2cg1083bzhvgs08sfdpw0000gq/T/junit_report20180206-27378-ek8zem'
[11:25:01]: ▸ Loading...
can't get Master/Slave device
[11:25:01]: failure noted: Error building/testing the application - see the log above
+----------------------------+--------------------------------------------------------------------+
|                                          Lane Context                                           |
+----------------------------+--------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                |
| PLATFORM_NAME              | ios                                                                |
| LANE_NAME                  | ios UITests                                                        |
| SCAN_DERIVED_DATA_PATH     | /Users/arun/Library/Developer/Xcode/DerivedData/app-eemzpzapcmva  |
|                            | xlalzceqygbhqqzd                                                   |
| SCAN_GENERATED_PLIST_FILES | []                                                                 |
| SCAN_GENERATED_PLIST_FILE  |                                                                    |
+----------------------------+--------------------------------------------------------------------+
[11:25:01]: Error building/testing the application - see the log above

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | cocoapods                  | 3           |
| 💥   | scan                       | 13          |
+------+----------------------------+-------------+

[11:25:01]: fastlane finished with errors

[!] Error building/testing the application - see the log above```

Any help in why it started failing??

**Comment by arunaousula9421** [comment]
fastlane env

```<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.1.10                                      |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.1.10/bin/fastlane        |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.1.10/lib               |
| OpenSSL Version             | OpenSSL 1.0.2m  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

    desc "Submit a new Beta Build to Crashlytics"
    desc "Build the Beta app and Submit the build to Crashlytics"
    lane :beta do

      gym(
          scheme: "Daft.ie",
          configuration: "Beta",
          archive_path: "./build/daft_beta.xcarchive",
          output_directory: "./build",
          export_method: "ad-hoc",
          clean: true
       )
     scan(
         workspace: "Daft.xcworkspace",
         scheme: "Daft.ie",
         device: "iPhone 7 Plus",
         clean: true
      )
    crashlytics(
        crashlytics_path:"./Pods/Crashlytics/",
        api_token: "16d8061598eb5d06a2ac69a3621537beba88de42",
        build_secret: "edebe376485cdd09fe7d4eaa78f926b24da6904587718e147fc9a1d7e93f4c41",
        ipa_path: "./build/Daft.Beta.ipa",
        groups: ["daft-beta"],
        notifications: "true"
      )     
  end 


  desc "Runs all the UI tests"
  lane :UITests do |options|
    scheme_to_test = "DaftUITests"

    scan_options = {
      scheme: scheme_to_test,
      clean: true,
      output_directory: '../artifacts/tests',
      output_files: 'report.xml'
    }

    begin
      retry_count ||=0
      scan(scan_options)
    rescue => e
      UI.important("failure noted: #{e}")
      report_filepath = File.absolute_path('../artifacts/tests/report.xml')
      unless File.exist?(report_filepath)
        raise e
      end
      if (retry_count += 1) < 3
        setup_fragile_tests_for_rescan(
          project_path: File.absolute_path('../Daft/Daft.xcodeproj'),
          scheme: scheme_to_test,
          report_filepath: report_filepath
        )
        clear_derived_data
        reset_simulator_contents if retry_count > 0
        retry
      end
    end
  end



  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Daft.ie") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "arun@daft.ie" # The bundle identifier of your app
apple_id "arun@daft.ie" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                         | Version | Update-Status |
| ---------------------------------------------- | ------- | ------------- |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                            | Version      |
| ---------------------------------------------- | ------------ |
| executable-hooks                               | 1.3.2        |
| bundler-unload                                 | 1.0.2        |
| rubygems-bundler                               | 1.4.4        |
| bundler                                        | 1.16.0       |
| CFPropertyList                                 | 2.3.6        |
| concurrent-ruby                                | 1.0.5        |
| i18n                                           | 0.9.1        |
| minitest                                       | 5.10.3       |
| thread_safe                                    | 0.3.6        |
| tzinfo                                         | 1.2.4        |
| activesupport                                  | 4.2.10       |
| public_suffix                                  | 2.0.5        |
| addressable                                    | 2.5.2        |
| atomos                                         | 0.1.2        |
| babosa                                         | 1.0.2        |
| claide                                         | 1.0.2        |
| fuzzy_match                                    | 2.0.4        |
| nap                                            | 1.1.0        |
| cocoapods-core                                 | 1.3.1        |
| cocoapods-deintegrate                          | 1.0.1        |
| cocoapods-downloader                           | 1.1.3        |
| cocoapods-plugins                              | 1.0.0        |
| cocoapods-search                               | 1.0.0        |
| cocoapods-stats                                | 1.0.0        |
| netrc                                          | 0.11.0       |
| cocoapods-trunk                                | 1.3.0        |
| cocoapods-try                                  | 1.1.0        |
| colored2                                       | 3.1.2        |
| escape                                         | 0.0.4        |
| fourflusher                                    | 2.0.1        |
| gh_inspector                                   | 1.1.1        |
| molinillo                                      | 0.5.7        |
| ruby-macho                                     | 1.1.0        |
| nanaimo                                        | 0.2.3        |
| xcodeproj                                      | 1.5.6        |
| cocoapods                                      | 1.3.1        |
| colored                                        | 1.2          |
| highline                                       | 1.7.10       |
| commander-fastlane                             | 4.4.5        |
| declarative                                    | 0.0.10       |
| declarative-option                             | 0.1.0        |
| unf_ext                                        | 0.0.7.5      |
| unf                                            | 0.1.4        |
| domain_name                                    | 0.5.20170404 |
| dotenv                                         | 2.2.1        |
| excon                                          | 0.60.0       |
| multipart-post                                 | 2.0.0        |
| faraday                                        | 0.14.0       |
| http-cookie                                    | 1.0.3        |
| faraday-cookie_jar                             | 0.0.6        |
| faraday_middleware                             | 0.12.2       |
| fastimage                                      | 2.1.1        |
| jwt                                            | 2.1.0        |
| little-plugger                                 | 1.1.4        |
| multi_json                                     | 1.13.1       |
| logging                                        | 2.2.2        |
| memoist                                        | 0.16.0       |
| os                                             | 0.9.6        |
| signet                                         | 0.8.1        |
| googleauth                                     | 0.6.2        |
| httpclient                                     | 2.8.3        |
| mime-types-data                                | 3.2016.0521  |
| mime-types                                     | 3.1          |
| uber                                           | 0.1.0        |
| representable                                  | 3.0.4        |
| retriable                                      | 3.1.1        |
| google-api-client                              | 0.13.6       |
| json                                           | 2.1.0        |
| mini_magick                                    | 4.5.1        |
| multi_xml                                      | 0.6.0        |
| plist                                          | 3.4.0        |
| rubyzip                                        | 1.2.1        |
| security                                       | 0.1.3        |
| slack-notifier                                 | 2.3.2        |
| terminal-notifier                              | 1.8.0        |
| unicode-display_width                          | 1.3.0        |
| terminal-table                                 | 1.8.0        |
| tty-screen                                     | 0.6.4        |
| tty-cursor                                     | 0.5.0        |
| tty-spinner                                    | 0.8.0        |
| word_wrap                                      | 1.0.0        |
| rouge                                          | 2.0.7        |
| xcpretty                                       | 0.2.8        |
| xcpretty-travis-formatter                      | 1.0.0        |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.0        |
</details>


*generated on:* **2018-02-06**
</details>```

**Comment by useeless37** [comment]
I have similar issue

> [12:43:25]: $ xcodebuild -list -workspace ./Ride.xcworkspace
> [12:43:28]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
> [12:43:34]: Command timed out after 6 seconds on try 2 of 4, trying again with a 12 second timeout...
> 2018-02-10 12:43:35.121 xcodebuild[22318:362079]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> 2018-02-10 12:43:36.779 xcodebuild[22319:362193]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> 2018-02-10 12:43:44.623 xcodebuild[22326:362337]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> [12:43:46]: Command timed out after 12 seconds on try 3 of 4, trying again with a 24 second timeout...
> 2018-02-10 12:43:58.869 xcodebuild[22338:362691]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> [12:44:04]: $ xcodebuild -showBuildSettings -workspace ./Ride.xcworkspace -scheme RideAustinTest
> [12:44:07]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
> 2018-02-10 12:44:12.472 xcodebuild[22368:363065]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> [12:44:13]: Command timed out after 6 seconds on try 2 of 4, trying again with a 12 second timeout...
> 2018-02-10 12:44:25.157 xcodebuild[22382:363212]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> [12:44:25]: Command timed out after 12 seconds on try 3 of 4, trying again with a 24 second timeout...
> 2018-02-10 12:44:38.113 xcodebuild[22421:363545]  DTDeviceKit: deviceType from 15c22d0d745a3912fad8946d42495bdafe758771 was NULL
> [12:44:49]: Command timed out after 24 seconds on try 4 of 4
> +------------------+--------+
> |       Lane Context        |
> +------------------+--------+
> | DEFAULT_PLATFORM | ios    |
> | PLATFORM_NAME    | ios    |
> | LANE_NAME        | ios qa |
> | BUILD_NUMBER     | 597    |
> | VERSION_NUMBER   | 4.5.0b |
> +------------------+--------+
> [12:44:49]: xcodebuild -showBuildSettings timed out after 4 retries with a base timeout of 3. You can override the base timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES

what I did is to downgrade cocoapods from 1.4 to 1.3.1, and its working fine.

**Comment by taquitos** [comment]
It seems like there might be an issue with your simulators: `DTDeviceKit: deviceType from a5d1d4a6e8558ac7f5df08dbdf2b7969d0c9d022 was NULL`

Maybe you can try resetting your simulators: `fastlane snapshot reset_simulators`
And see if that helps?

**Comment by yapiskan** [comment]
@taquitos i have the same problem. resetting simulators didn't help.

**Comment by joshdholtz** [comment]
This seems to be an issue outside of fastlane 🤔 The output shows `Can't get Master/Slave` which I believe is a system level error which involves spawning a new process. We had an similar issue (https://github.com/fastlane/fastlane/issues/8258) that was solved by restarting 😕
