### ISSUE TITLE
fastlane stop working - `require': unable to find a version of 'xcodeproj' to activate

### ISSUE THREAD

**Issue by YissacharB** [fastlane/fastlane#11782]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
some why since last update I can't use fastlane, even when I'm trying to run `fastlane env` I  also get the same error: `require': unable to find a version of 'xcodeproj' to activate`

<details>
  <pre> Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'xcodeproj' to activate (Gem::LoadError)
	from /Users/myUser/.rvm/gems/ruby-2.3.1/gems/fastlane-2.80.0/fastlane/lib/fastlane/setup/crashlytics_project_parser.rb:1:in `<top (required)>'
	from /Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/gems/fastlane-2.80.0/fastlane/lib/fastlane/setup/setup.rb:354:in `<top (required)>'
	from /Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/gems/fastlane-2.80.0/fastlane/lib/fastlane.rb:11:in `<top (required)>'
	from /Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/myUser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/gems/fastlane-2.80.0/fastlane/lib/fastlane/cli_tools_distributor.rb:37:in `take_off'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/gems/fastlane-2.80.0/bin/fastlane:20:in `<top (required)>'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/myUser/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>it is not running, 
fastlane: 2.80.0
os:10.13.3
ruby: 2.3.1
git: 2.6.0
Xcode: 9.1

what else do you need?
</pre>
</details>

**Comment by YissacharB** [comment]
@fastlane-bot This is the problem, I can't run fastlane.
I tried to unistall and install, didn't help.
I tried gem update.

**Comment by kvasdopil** [comment]
You may have several versions of `xcodeproj` installed. Uninstall the old one with `gem uninstall`.

**Comment by YissacharB** [comment]
I installed ruby 2.3.3 - and reinstall fastlane, it fixed the problem.

**Comment by revolter** [comment]
I got this problem because I forgot to run with `bundle exec` at the beginning.
