### ISSUE TITLE
Importing provisioning profiles from file

### ISSUE THREAD

**Issue by akashivskyy** [fastlane/fastlane#11788]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi! I have a need for an action that would import a `.mobileprovision` file from a folder in my repository to `~/Library/MobileDevice/Provisioning Profiles`.

Is there a fastlane action that does that (I cound't find such options in any of the code signing actions) or should I do this manually using `cp`?

**Comment by akashivskyy** [comment]
@fastlane-bot Nope and nope! 😅

**Comment by taquitos** [comment]
I think the `copy_artifacts` action will work for you
Check out the example code:
```
'copy_artifacts(
            target_path: "artifacts",
            artifacts: ["*.cer", "*.mobileprovision", "*.ipa", "*.dSYM.zip", "path/to/file.txt", "another/path/*.extension"]
          )
```

You can provide paths to the files, and a target directory.

**Comment by akashivskyy** [comment]
@taquitos That did the trick, but it's semantically incorrect (these are not artifats). I believe there should be an action for importing `.mobileprovision` files to `~/Library/MobileDevice/Provisioning Profiles` just like `import_certificate` imports `.p12` to Keychain.

**Comment by taquitos** [comment]
Yeah, I agree, while it works, it could lead to confusion.

**Comment by akashivskyy** [comment]
I used Joshua's solution for now which is satisfactory enough. Maybe I'll take advantage of Fastlane's amazing contribution culture and open a PR with an action that meets the need described in this issue. I'm closing the issue for now.

**Comment by janpio** [comment]
Hey @akashivskyy, I just searched for a similar action and found this "old" issue. I would love if such an action would exist, even if it would "only" be a pretty shallow one.

For documentation, this is what I ended up with:
```
  require 'fileutils'
  path = File.expand_path("~") + "/Library/MobileDevice/Provisioning Profiles/"
  unless File.directory?(path)
    FileUtils.mkdir_p(path)
  end
  FileUtils.cp('../foo/367f12b1-4765-4d71-86be-e69ac68885b1.mobileprovision', path)
```
The `367f12b1-4765-4d71-86be-e69ac68885b1` is extracted from the original provisioning profile itself that had a different name, so automating that as well would be a great feature for the action.

**Comment by akashivskyy** [comment]
Yeah, I ended up doing a very similar thing:

```rb
copy_artifacts(
  artifacts: [".fastlane/certificates/foo.mobileprovision"],
  target_path: File.expand_path("~/Library/MobileDevice/Provisioning Profiles")
)
```

@janpio Are you suggesting adding an action (let's say `import_profiles`) for simply copying `*.mobileprovision` to `~/Library/MobileDevice/Provisioning Profiles`?

**Comment by janpio** [comment]
Yes, I think that is a common enough usecase to add - don't you think? Of course we did find a solution on our own, but we had to learn about the path where profiles end up to be able to. Skipping that could be nice for new users.

Do you want to give it a shot?

**Comment by akashivskyy** [comment]
Sure. 😉 I'll call it `import_profile` so that it's analogous to `import_certificate`. Will open a PR in a couple of days.

**Comment by janpio** [comment]
There is actually a issue open where we are talking to add an alias `import_into_keychain` as `import_certificate` is only semi correct ;) Maybe `install_profile`? It doesn't end up in the keychain, but in the correct location to be picked up by Xcode etc.

**Comment by humbass** [comment]
@akashivskyy ,

 I have the same request "import_certificate" as you.  

Have you been solved it ?

**Comment by humbass** [comment]
Maybe I should use "update_project_provisioning" ? 


Action | Description | Supported Platforms
-- | -- | --
update_project_provisioning | Update projects code signing settings from your provisioning profile | ios, mac

**Comment by humbass** [comment]
Maybe I should use "update_project_provisioning" ? 


Action | Description | Supported Platforms
-- | -- | --
update_project_provisioning | Update projects code signing settings from your provisioning profile | ios, mac

**Comment by SofteqDG** [comment]
@akashivskyy, @janpio 
I like the idea about new action to install provisioning profile. I've looked through the code and find that we can use `FastlaneCore::ProvisioningProfile.install(#path_to_provisioning_profile)` to install provisioning profile. 

There is a possible implementation of such plugin:
```ruby
require 'shellwords'

module Fastlane
  module Actions
    class InstallProvisioningProfileAction < Action
      def self.run(params)
        provisioning_profile_path = params[:provisioning_profile_path]
        FastlaneCore::ProvisioningProfile.install(provisioning_profile_path)
      end

      def self.description
        "Install provisioning profile from inputfile"
      end

      def self.details
        "Install provisioning profile from inputfile for current user"
      end

      def self.authors
        ["SofteqDG"]
      end

      def self.category
        :code_signing
      end

      def self.is_supported?(platform)
        [:ios, :mac].include?(platform)
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :provisioning_profile_path,
                                  env_name: "FL_INSTALL_PROVISIONING_PROFILE_PATH",
                               description: "Path to provisioning profile",
                                  optional: false,
                                      type: String)
        ]
      end

      def self.return_value
        "The absolute path to the installed provisioning profile"
      end

      def self.example_code
        [
          'install_provisioning_profile(provisioning_profile_path: "profiles/profile.mobileprovision")',
        ]
      end
    end
  end
end
```

I'm not sure that it will work cos i'm not good at ruby.
What do you think about it? Will it work?

**Comment by akashivskyy** [comment]
@SofteqDG Feel free to submit this as a PR, there are no objections from my side. 😉 Just a little bit of guilt since I said that I would open a PR "in a couple of days", which unfortunately I didn't manage to do.

**Comment by SofteqDG** [comment]
@akashivskyy,
Looks like i can't submit this as a PR because contributing guide states that new actions will not be accepted at the moment :(

**Comment by janpio** [comment]
@SofteqDG Don't worry about that, I think the team will have no objections on this one as it is clearly useful in fastlane context and pretty lean, and basically just a wrapper around existing code.
