### ISSUE TITLE
Required ruby version

### ISSUE THREAD

**Issue by caipivara** [fastlane/fastlane#11784]
I want to run it on Debian 32 bits but I dont see what's the required min ruby version to run this.
I instaled `rbenv` but put on `/opt/rbenv` since I want it to be shared between users.

Im trying with ruby #`2.4.0` but with no success.

Im trying with http://download.fastlane.tools/ but it looks like it's just for 64 bits.

Getting a security error:

```
$ ruby fastlane env
ruby: no -x allowed while running setgid (SecurityError)
```

**Comment by minuscorp** [comment]
If I'm not wrong, `fastlane` depends on Ruby 2.0.0 as its minimum requirement.

**Comment by caipivara** [comment]
@minuscorp and it runs on 32 bit systems?

**Comment by minuscorp** [comment]
Yeah! For sure, look for it using apt-get, you'll have to look for the 2.0.0 version tough
