### ISSUE TITLE
Code signing with HealthKit

### ISSUE THREAD

**Issue by kay-is** [fastlane/fastlane#11783]
### Issue Description

I use match for code signing.

When I activated the HealthKit capabilities, fastlane fails with the following error:

Provisioning profile "match AdHoc com.my-domain.mobile-app" doesn't support the HealthKit capability.

When I disable the capability everything works again, but I need it.

##### Complete output when running fastlane, including the stack trace and command used

I tried to run `fastlane beta` 

<details>
  <pre>
INFO [2018-02-05 16:24:27.15]: ▸ ** ARCHIVE FAILED **
INFO [2018-02-05 16:24:27.15]: ▸ The following build commands failed:
INFO [2018-02-05 16:24:27.15]: ▸ Check dependencies
INFO [2018-02-05 16:24:27.15]: ▸ (1 failure)
ERROR [2018-02-05 16:24:27.20]: Exit status: 65
INFO [2018-02-05 16:24:27.30]: ▸ Check dependencies
INFO [2018-02-05 16:24:27.30]: ▸ Code Signing Error: Provisioning profile "match AdHoc com.company.mobile-app" doesn't support the HealthKit capability.
INFO [2018-02-05 16:24:27.30]: ▸ Code Signing Error: Provisioning profile "match AdHoc com.company.mobile-app" doesn't include the com.apple.developer.healthkit entitlement.
INFO [2018-02-05 16:24:27.30]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
</pre>
</details>

### Environment
<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.2                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build a new beta version"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    
    register_devices(
      devices: {
        ...
      }
    )
    
    match(type: "adhoc", force_for_new_devices: true) # more information: https://codesigning.guide
    
    gym(
      scheme: "xxxx",
      clean: true,
      silent: true,
      output_directory: "../build/beta/"
    ) 

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    # snapshot
    gym(
      scheme: "xxxx",
      clean: true,
      silent: true,
      output_directory: "../build/release/"
    ) # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.mobile-app" # The bundle identifier of your app
apple_id "developer@company.com" # Your Apple email address

team_id "XXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-02-05**
</details></pre>
</details>

**Comment by kay-is** [comment]
The code signing guide mentiones that capabilities can be cause of a problem, but doesn't provide a solution :(

**Comment by KrauseFx** [comment]
Sorry, I won't be able to help with this, as I've never worked with HealthKit myself 😢

**Comment by minuscorp** [comment]
So I have several applications that use HealthKit being signed with `match` without any issue. I encourage you to dig into the build logs to see if that's the only issue in the build. If it is the only build failure reason, I'd try to `nuke` 💥  that certificates and generate them again. Make sure to properly clean `~/Library/MobileDevice/Provisioning Profiles` directory, it contains **all** your profiles, so make sure you don't delete anything else that might be used by another targets or projects!

**Comment by kay-is** [comment]
Thanks for the help @minuscorp 

Tried nuking and deleting local provisioning profiles. Still get this error:
<pre>
INFO [2018-02-06 15:08:16.26]: ▸ ** ARCHIVE FAILED **
INFO [2018-02-06 15:08:16.26]: ▸ The following build commands failed:
INFO [2018-02-06 15:08:16.26]: ▸ Check dependencies
INFO [2018-02-06 15:08:16.26]: ▸ (1 failure)
ERROR [2018-02-06 15:08:16.32]: Exit status: 65
INFO [2018-02-06 15:08:16.43]: ▸ Check dependencies
INFO [2018-02-06 15:08:16.43]: ▸ Code Signing Error: Provisioning profile "match AdHoc com.company.mobile-app" doesn't support the HealthKit capability.
INFO [2018-02-06 15:08:16.43]: ▸ Code Signing Error: Provisioning profile "match AdHoc com.company.mobile-app" doesn't include the com.apple.developer.healthkit entitlement.
INFO [2018-02-06 15:08:16.43]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
</pre>

Do I have to take any manual steps here?

Add something to the `Fastfile`?

Change something in the Apple Developer Account?

Xcode has added the entitlement file, but maybe this isn't enough?

**Comment by minuscorp** [comment]
I'd use `match` using `appstore` instead of `adhoc` profile. I just make sure that xcode is really compiling the application in first place, before even trying to use `fastlane`.

**Comment by kay-is** [comment]
Ah okay.

What is the difference between `adhoc` and `appstore`?

**Comment by minuscorp** [comment]
So the main difference is that applications signed with `adhoc` provisioning profile will only be able to be installed on a number of devices. `appstore` signs the application in a way that can be submitted either through TestFlight or AppStore.

**Comment by kay-is** [comment]
Ah, so I have to use TestFlight for distribution of test-builds?

Got a new error by switching to `appstore`

<pre>
ERROR [2018-02-06 16:17:12.65]: Exit status: 65
INFO [2018-02-06 16:17:12.81]: ▸ === BUILD TARGET myapp OF PROJECT myapp WITH CONFIGURATION Release ===
INFO [2018-02-06 16:17:12.81]: ▸ Check dependencies
INFO [2018-02-06 16:17:12.81]: ▸ Code Signing Error: No profile for team 'XXXXXXXXXX' matching 'match AdHoc com.company.mobile-app' found:  Xcode couldn't find any provisioning profiles matching 'XXXXXXXXXX/match AdHoc com.company.mobile-app'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
INFO [2018-02-06 16:17:12.81]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
</pre>

Shouldn't match create and add these things automatically?

**Comment by kay-is** [comment]
Ah, the Apple Developer portal says, I don't have these capabilities.

Just Game Center, In-App Purchase and Push Notifications.

I don't even use Game Center stuff and it seems like I can't change anything in there...

**Comment by minuscorp** [comment]
So... @kay-is, if you want to distribute your app to beta testers without manually having to add your testers UUIDs, regenerate your provisioning profile and re-signing your application each time you add a new device, you should definitely use TestFlight...

About your output, it seems that something is being messed up with your project signing configuration, you should always have the following mapping (assuming that you use TestFlight):

- Debug Configuration -> match development com.XXXX.YYYY

- Release Configuration -> match appstore com.XXXX.YYYY

Also, for your portal to register those capabilities, make sure that in your project -> Capabilities is actually selected HealtKit. If it is already selected please make sure you unselect it and select it again and make new certificates that reflects the changes made in your developer portal.

**Comment by kay-is** [comment]
Thanks for the help.

Got it running without Fastlane, I had to let Xcode manage the certificates.

Not pretty, but for now I can upload to itunes connect again :/
