### ISSUE TITLE
Tool renaming caused issues for some setups

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#11785]
Reported by @steipete:

It seems like the name conflicts with tool aliases with lane names are not handled the right way, it's something we have to fix for sure, as this is not the way this was designed. We always favor lanes over actions, but it seems like that's not the case for aliases is my first assumption.

Related https://github.com/fastlane/fastlane/issues/11769

**Comment by KrauseFx** [comment]
Alright, I tried the following `Fastfile`

```ruby
lane :build_app do
  puts "my lane"
end

lane :yolo do
  build_app
end
```

and can confirm, that it uses the `build_app` action, and not the `build_app` lane, meaning with the aliases we basically broke some setups (ugh.... sorry)

We're making this right! We did however have a warning as part of the output every time you run _fastlane_:

```
[18:11:04]: Lane name 'gym' should not be used because it is the name of a fastlane tool
[18:11:04]: It is recommended to not use 'gym' as the name of your lane
```
or for `build_app` it was
```
[18:12:15]: Name of the lane 'build_app' is already taken by the action named 'build_app'
```

Besides fixing the priority, I'm also gonna update the warnings to be even more visible 👍

**Comment by steipete** [comment]
Thanks for making this more obvious! ❤️
