### ISSUE TITLE
Building Xamarin projects with Fastlane

### ISSUE THREAD

**Issue by luigifilannino** [fastlane/fastlane#11797]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi team,
I need to build Xamarin.Forms projects which contains a core, a .Droid and a .iOS components. Can you tell me please if xamarin_build plugin (https://github.com/punksta/fastlane-plugin-xamarin_build) or souyuz plugin (https://github.com/voydz/souyuz/tree/master/fastlane-plugin-souyuz) can be used for my goal? Do you have any Fastfile samples to understand how can I structure my lanes to build and sign .ipa and .apk apps with specific certificates/provisioning profiles/keystores. 

The souyuz plugin seems to be useful for Xamarin iOS apps, but I don't find anything to build Xamarin Android apps...  

Thank you in advance!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
https://github.com/voydz/souyuz says

> Fastlane build plugin for building Xamarin.iOS and Xamarin.Android applications

You should probably ask in their repo for an example `Fastfile`.
