### ISSUE TITLE
Use new Basic App Metadata XML for updating of AppStore metadata

### ISSUE THREAD

**Issue by koenpunt** [fastlane/fastlane#11792]
Apple recently released a new API for updating metadata in ITC: https://itunespartner.apple.com/en/apps/news/7437625

This provides native support for updating app title, description, and also previews and screenshots.

More on the format here: http://help.apple.com/itc/appsspec/#/itc6e4198248

I'm going to setup Snapshot for a project soon, and while at it I will take a stab at using this instead of the methods available with Spaceship's DUClient.

But maybe someone else with more knowhow of the Spaceship internals, has the time to implement this properly before I even get to it? 🙃

--- 

**Edit:** Now that I re-read Apple's news item, I think this XML delivery has been available for longer, and they just released it for App Previews too. So now I'm wondering, was this XML delivery ever considered, but not proven useful, or was this option not known by the developers? (no shame on that, I also just found out about it now)

**Comment by janpio** [comment]
Without knowing the details of any of this: Is this maybe iTMSTransporter?

**Comment by koenpunt** [comment]
I think this is still relevant..

**Comment by joshdholtz** [comment]
@koenpunt I'm curious about @janpio's question above as well. Is this different than what we are already using iTMSTransporter for?

**Comment by joshdholtz** [comment]
@koenpunt Ahhhhhh, I see now 😊 This is would be a pretty large change **but** probably _could_ be a good one since official and documented like you said. I will take a look at and weigh things out 😇 Thanks for linking this!

**Comment by KrauseFx** [comment]
So if I'm not mistaken, https://help.apple.com/itc/appsspec/#/itc6e4198248 is just describing the format of the iTunes Transporter. We consciously stopped using transporter for app metadata & screenshots, as lots of companies faced issues when they had firewalls or proxies setup. So if this is using the transporter, I see no reason for now to make a switch. If it's something else, it might be worth investigating

**Comment by koenpunt** [comment]
@KrauseFx thanks for chiming in; did Fastlane previously used the ITMSTransporter program? Or did just using those api endpoints cause issues already?
Because the above mentioned endpoints can be used without the ITMSTransporter

**Comment by KrauseFx** [comment]
We used `ITMSTransporter` in the past, but many users had issues with it, due to firewalls and proxies
