### ISSUE TITLE
Frameit: Option to not fall back on available color

### ISSUE THREAD

**Issue by saschagordner** [fastlane/fastlane#11795]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently frameit falls back on available device colors, if there is a color defined which is not available for a model (e.g. rose-gold for iPhone X).
There should be an option to prevent this from happening.

I currently have the case where I iterate over an array of defined colors and then create framed screenshots for each iPhone size and move them to another folder which is named after the respective color.
It would come in really handy to disable fallback and just skip unavailable color/ device combinations, because as of now I end up with e.g. white iPhone X framed screenshots in the "rose-gold" subdirectory.
Sure, I can do a mapping locally, but I think an option to disable the fallback might make sense for other cases as well.

What do you think?

### Environment

<details><summary> fastlane environment </summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.4.0                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.7.2                               |
| Installation Source         | ~/.gems/bin/fastlane                            |
| Host                        | Mac OS X 10.12.6 (16G29)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |
</details>

**Comment by janpio** [comment]
What it the usecase for getting framed screenshots with all device frame colors?

I am reading why we are falling back at all instead of giving an error message...

**Comment by saschagordner** [comment]
We want to automatically create framed screenshots of the app for our marketing department, so they can easily pick the screens they want for their purposes like newsletters, mails, ...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
