### ISSUE TITLE
Unexpected results deploying to Android Store using "supply" with "check_superseded_tracks: true"

### ISSUE THREAD

**Issue by kingbin** [fastlane/fastlane#11803]
### New Issue Checklist

- :white_check_mark: Updated fastlane to the latest version
- :white_check_mark: I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- :white_check_mark: I read [docs.fastlane.tools](https://docs.fastlane.tools)
- :white_check_mark: I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### I believe the desired result should be to remove builds in a lower task priority (Production->Beta->Alpha) and then by the version code. This could be my misunderstanding of the flag but the examples I have found all refer to a publish to the beta track dealing with the alpha track versioning.

<details><summary>✅ FastFile Specific Lane ✅</summary>

```ruby

  desc "Deploy beta to the Google Play Store"
  lane :beta do
    ENV["ENVFILE"] = '.env.staging'
    gradle(
      task: 'assemble',
      build_type: 'release',
      project_dir: "android/"
    )
    supply(
      package_name: "com.something.cool",
      track: 'beta',
      check_superseded_tracks: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

```
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.2/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.2/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# fastlane_version "2.3.1"

...
  desc "Deploy beta to the Google Play Store"
  lane :beta do
    ENV["ENVFILE"] = '.env.staging'
    gradle(
      task: 'assemble',
      build_type: 'release',
      project_dir: "android/"
    )
    supply(
      package_name: "com.something.cool",
      track: 'beta',
      check_superseded_tracks: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
...



```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-wait_xcrun         | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-android_versioning | 0.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.0.0        |
| executable-hooks                   | 1.3.2        |
| bundler-unload                     | 1.0.2        |
| rubygems-bundler                   | 1.4.4        |
| bundler                            | 1.16.1       |
| io-console                         | 0.4.5        |
| CFPropertyList                     | 2.3.6        |
| public_suffix                      | 2.0.5        |
| addressable                        | 2.5.2        |
| atomos                             | 0.1.2        |
| babosa                             | 1.0.2        |
| curb                               | 0.9.4        |
| fastimage                          | 2.1.1        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.5        |
| dotenv                             | 2.2.1        |
| excon                              | 0.60.0       |
| multipart-post                     | 2.0.0        |
| faraday                            | 0.14.0       |
| unf_ext                            | 0.0.7.5      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20170404 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday_middleware                 | 0.12.2       |
| gh_inspector                       | 1.1.1        |
| jwt                                | 2.1.0        |
| little-plugger                     | 1.1.4        |
| multi_json                         | 1.13.1       |
| logging                            | 2.2.2        |
| memoist                            | 0.16.0       |
| os                                 | 0.9.6        |
| signet                             | 0.8.1        |
| googleauth                         | 0.6.2        |
| httpclient                         | 2.8.3        |
| mime-types-data                    | 3.2016.0521  |
| mime-types                         | 3.1          |
| declarative                        | 0.0.10       |
| declarative-option                 | 0.1.0        |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.1        |
| google-api-client                  | 0.13.6       |
| json                               | 2.1.0        |
| mini_magick                        | 4.5.1        |
| multi_xml                          | 0.6.0        |
| plist                              | 3.4.0        |
| rubyzip                            | 1.2.1        |
| security                           | 0.1.3        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 1.8.0        |
| unicode-display_width              | 1.3.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.6.4        |
| tty-cursor                         | 0.5.0        |
| tty-spinner                        | 0.8.0        |
| word_wrap                          | 1.0.0        |
| claide                             | 1.0.2        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.2.3        |
| xcodeproj                          | 1.5.6        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.2.8        |
| xcpretty-travis-formatter          | 1.0.0        |
| badge                              | 0.8.7        |
| fastlane-plugin-android_versioning | 0.3.0        |
| fastlane-plugin-wait_xcrun         | 0.1.1        |
| watchbuild                         | 0.2.0        |
| xcode-install                      | 2.3.1        |
</details>

*generated on:* **2018-02-08**
</details>

**Comment by olivierg13** [comment]
Hey folks,

Same issue for me, while trying to rollout (5%) a new APK, the `check_superseded_tracks` method wants to remove Production apks.
I see two ways to improve this method:
- Like @kingbin said, if possible, the superseded method could check by priority.
Actually l175 of `uploader.rb`, tracks are already defined this way: `tracks = ["production", "rollout", "beta", "alpha"]`. Then the iteration occurs on all tracks l178 `tracks.each_index`.
- Also another improvement I would see is to check for APK targets (if the APK targets an older API version, it should not be deleted because not superseded by the new APK).

I could try to do a PR, but my Ruby is rusty 😆 
I'll try something if no-one more experienced answers on this thread 😄 

Thank you in advance. 

Olivier

**Comment by joshdholtz** [comment]
Will look into this 👍
