### ISSUE TITLE
Requesting for a Tagalog Translation

### ISSUE THREAD

**Issue by ergiegonzaga** [fastlane/fastlane#11805]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[]</pre>
</details>

**Comment by janpio** [comment]
Hi @ergiegonzaga. What exactly is your issue or question?

**Comment by taquitos** [comment]
Oh, right now fastlane isn't set up for localization 😞

**Comment by ergiegonzaga** [comment]
Hi sir,
Does it mean sir that your project does need a tagalog translations or
translations to any language sir?

**Comment by taquitos** [comment]
Unfortunately, fastlane isn't localized at all. We don't have any localization support. It would be great if we did, because we'd certainly take translations.
