### ISSUE TITLE
Support wild character * in screenshot lane app_apk_path

### ISSUE THREAD

**Issue by cavega** [fastlane/fastlane#11808]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Currently, if the Android APK specified in _app_apk_path_ (inside the **lane :screenshots do** block) contains a wild character (*) fastlane errors out with the the error message 
```
[!] Could not find APK file at path...
``` 

My project's build.gradle is configured so that the built apk's filename includes the app's current versionName.

Example:
```
app_apk_path: "<path_to_apk/app_filename-123456.apk",
```

I understand this might be a long shot but....is there a way, or, would it be possible for Fastlane to support a file path containing wild-character, as shown below, such that fastlane is able to execute the lane? 
```
app_apk_path: "<path_to_apk/app_filename-*.apk",
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
fastlane android screenshots
[✔] 🚀
[17:56:55]: ----------------------------------------
[17:56:55]: --- Step: Verifying fastlane version ---
[17:56:55]: ----------------------------------------
[17:56:55]: Your fastlane version 2.80.0 matches the minimum requirement of 1.110.0  ✅
[17:56:55]: ------------------------------
[17:56:55]: --- Step: default_platform ---
[17:56:55]: ------------------------------
[17:56:55]: Driving the lane 'android screenshots' 🚀
[17:56:55]: ------------------------
[17:56:55]: --- Step: screengrab ---
[17:56:55]: ------------------------
[17:56:55]: Error setting value '<path_to_apk>/debug/app_filename-debug-*.apk' for option 'app_apk_path'
[17:56:55]: You passed invalid parameters to 'screengrab'.
[17:56:55]: Check out the error below and available options by running `fastlane action screengrab`
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | android             |
| PLATFORM_NAME    | android             |
| LANE_NAME        | android screenshots |
+------------------+---------------------+
[17:56:55]: Could not find APK file at path '<path_to_apk>/debug/app_filename-debug-*.apk'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | screengrab                 | 0           |
+------+----------------------------+-------------+

[17:56:55]: fastlane finished with errors

[!] Could not find APK file at path '<path_to_apk>/debug/app_filename-debug-*.apk'
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| nanaimo                   | 0.2.3        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 2.3.6        |
| atomos                    | 0.1.2        |
| xcodeproj                 | 1.5.6        |
| unf_ext                   | 0.0.7.5      |
| gh_inspector              | 1.1.2        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.1        |
</details>

*generated on:* **2018-02-08**
</details>

**Comment by joshdholtz** [comment]
@cavega This isn't something that we would probably build into fastlane but you could do something like this...
```rb
lane :something do
    gradle(
      task: 'assemble assembleAndroidTest'
    )

    apk_path = Dir.glob("../**/app_filename-*.apk").first
    # Call UI.user_error if apk_path doesn't exist
end
```

Happy fastlaning 🚀

**Comment by cavega** [comment]
@joshdholtz Thanks for the feedback. We'll try that. 👍
