### ISSUE TITLE
Fastlane not setting the proper provisioning profile

### ISSUE THREAD

**Issue by jwaldrip** [fastlane/fastlane#11806]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=54815541)](https://www.bountysource.com/issues/54815541-fastlane-not-setting-the-proper-provisioning-profile?utm_source=54815541&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Match is not managing my provisioning profiles. I have separate app identifiers for each lane, but it is not setting the matching provisioning profile during the build process and therefore failing the build with:

```
INFO [2018-02-08 12:34:11.52]: ▸ ❌  Code Signing Error: "assessmentmobile" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
INFO [2018-02-08 12:34:11.58]: ▸ ** ARCHIVE FAILED **
INFO [2018-02-08 12:34:11.58]: ▸ The following build commands failed:
INFO [2018-02-08 12:34:11.58]: ▸ Check dependencies
INFO [2018-02-08 12:34:11.58]: ▸ (1 failure)
ERROR [2018-02-08 12:34:11.60]: Exit status: 65
INFO [2018-02-08 12:34:11.67]: ▸ === BUILD TARGET assessmentmobile OF PROJECT assessmentmobile WITH CONFIGURATION Release ===
INFO [2018-02-08 12:34:11.67]: ▸ Check dependencies
INFO [2018-02-08 12:34:11.67]: ▸ Code Signing Error: "assessmentmobile" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
INFO [2018-02-08 12:34:11.67]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
INFO [2018-02-08 12:34:11.67]:
ERROR [2018-02-08 12:34:11.67]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2018-02-08 12:34:11.67]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2018-02-08 12:34:11.67]: 📋  /Users/jwaldrip/Library/Logs/gym/assessmentmobile-CT-Assess Staging.log
INFO [2018-02-08 12:34:11.67]:
ERROR [2018-02-08 12:34:11.67]: Looks like fastlane ran into a build/archive error with your project
ERROR [2018-02-08 12:34:11.67]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2018-02-08 12:34:11.67]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2018-02-08 12:34:11.67]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2018-02-08 12:34:11.67]: sure your project is set up correctly.
ERROR [2018-02-08 12:34:11.67]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2018-02-08 12:34:11.67]: the full commands printed out in yellow in the above log.
ERROR [2018-02-08 12:34:11.67]: Make sure to inspect the output above, as usually you'll find more error information there
```

##### Complete output when running fastlane, including the stack trace and command used

https://gist.github.com/jwaldrip/d59dfa4b38f78de9fe5a7ecbf29c7ba2

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.gem/ruby/2.3.1/bin/fastlane              |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.1/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

if ENV["CI"]
  setup_travis
  ENV["MATCH_READONLY"] = false.to_s
end

IOS_PROJECT = "./ios/assessmentmobile.xcodeproj"
APP_IDENTIFIER = "com.commercialtribe.assessment-mobile"
APP_NAME = "CT Assess"
ENV['ENVFILE'] = ".env.production"

before_all do
  ensure_git_status_clean
end

after_all do
  reset_git_repo skip_clean: true
end

error do
  reset_git_repo skip_clean: true
end

private_lane :label_icons do |top: nil, bottom: nil|
  command = "label-icons"
  command << " --top=\"#{top}\"" if top
  command << " --bottom=\"#{bottom}\"" if bottom
  yarn command: command
end

platform :ios do
  private_lane :compile_app do |channel: nil, **options|
    # Set up some vars
    app_name = APP_NAME
    app_identifier = APP_IDENTIFIER
    version_number = get_version_number xcodeproj: IOS_PROJECT
    build_number = ENV["TRAVIS_BUILD_NUMBER"] || raise("Missing TRAVIS_BUILD_NUMBER")
    increment_build_number xcodeproj: IOS_PROJECT, build_number: build_number

    # If a channel is specfied, update the project to reflect it
    if channel
      app_name = app_name + " (#{channel})"
      app_identifier = "com.commercialtribe.assessment-mobile.#{channel}"
      update_info_plist(
        xcodeproj: IOS_PROJECT,
        plist_path: "assessmentmobile/Info.plist",
        app_identifier: app_identifier,
      )
      label_icons top: channel, bottom: "v#{version_number}b#{build_number}"
    end

    # Ensure the app is created on iTunes Connect
    produce(
      app_identifier: app_identifier,
      app_name: app_name,
      language: 'English',
      app_version: version_number,
    )

    # Sync the code signing
    sync_code_signing(
      type: "appstore",
      app_identifier: app_identifier,
      git_url: "git@github.com:CommercialTribe/assessment-certificates.git"
    )

    # Build the app
    build_ios_app(
      **options,
      project: IOS_PROJECT
    )

    # Return the app id
    app_identifier
  end

  desc "Push a new alpha build to TestFlight"
  lane :alpha do
    ENV['ENVFILE'] = ".env.staging"
    compile_app(channel: "alpha", scheme: "CT-Assess Staging")
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_identifier = compile_app(channel: "beta", scheme: "CT-Assess Prod")
    upload_to_testflight(
      app_identifier: app_identifier
    )
  end

  desc "Release a version to the app store"
  lane :release do
    raise "Can only release from travis tag" unless (version_number = ENV['TRAVIS_TAG'])
    commit_version_bump xcodeproj: IOS_PROJECT, version_number: version_number
    compile_app scheme: "CT-Assess Prod"
    deliver(force: true, submit_for_review: true, automatic_release: true)
  end
end

platform  :android do
  desc "Push a new alpha build to the play store"
  lane :alpha do
    version_code = ENV["TRAVIS_BUILD_NUMBER"] || raise("Missing TRAVIS_BUILD_NUMBER")
    increment_version_code version_code: version_code
    ENV['ENVFILE'] = ".env.staging"
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android',
      print_command: false,
      properties: {
          "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
          "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_ALIAS"],
          "android.injected.signing.key.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        }
    )
    upload_to_play_store(track: 'alpha')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.commercialtribe.assessment-mobile" # The bundle identifier of your app
apple_id "engineering@commercialtribe.com" # Your Apple email address

itc_team_id "117943466" # iTunes Connect Team ID
team_id "9AZS5LT7UB" # Developer Portal Team ID

package_name "com.commercialtribe.assessment.mobile" # Android Package Name
json_key_file "/tmp/google_play.json" # Google Play Service Account Credentials

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-yarn                   | 1.0     | ✅ Up-To-Date  |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.0.0        |
| slack-notifier                         | 2.3.2        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.6.4        |
| tty-cursor                             | 0.5.0        |
| tty-spinner                            | 0.8.0        |
| babosa                                 | 1.0.2        |
| colored                                | 1.2          |
| commander-fastlane                     | 4.4.5        |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| security                               | 0.1.3        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| mime-types-data                        | 3.2016.0521  |
| mime-types                             | 3.1          |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.13.6       |
| highline                               | 1.7.10       |
| io-console                             | 0.4.5        |
| excon                                  | 0.60.0       |
| rubyzip                                | 1.2.1        |
| CFPropertyList                         | 2.3.6        |
| mini_portile2                          | 2.2.0        |
| nokogiri                               | 1.8.0        |
| plist                                  | 3.4.0        |
| faraday                                | 0.14.0       |
| os                                     | 0.9.6        |
| googleauth                             | 0.6.2        |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20170404 |
| faraday_middleware                     | 0.12.2       |
| signet                                 | 0.8.1        |
| fastimage                              | 2.1.1        |
| json                                   | 2.1.0        |
| atomos                                 | 0.1.2        |
| claide                                 | 1.0.2        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.3        |
| xcodeproj                              | 1.5.6        |
| bundler                                | 1.14.6       |
| terminal-table                         | 1.8.0        |
| unicode-display_width                  | 1.3.0        |
| fastlane-plugin-yarn                   | 1.0          |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2018-02-08**
</details>

**Comment by jwaldrip** [comment]
@fastlane-bot your right, but the troubleshooting guide isn't very helpful in this regard.

**Comment by jwaldrip** [comment]
This has been the most frustrating day in a long time wrestling with this issue. It looks like the export options are not being generated. Is this a known issue, or am I wrong and are they actually being generated? If so where are they generated to and how can I confirm?

**Comment by taquitos** [comment]
Yeah, this is a huge pain. 
Have you done this yet: 
- Open project in Xcode (9)
- Archive the project
- Once archived, export the generated .xcarchive file to an IPA file
  - During this process Xcode will should put an `exportOptionsPlist` file next to the generated IPA file that has the configuration it used. 
- You can take this file and edit it to fit your needs.

**Comment by wade0317** [comment]
I think you could have a look at my [fastlane lane](https://github.com/fastlane/fastlane/issues/11801).

**Comment by wade0317** [comment]
This work for me , as follow:

        lane :release do

            disable_automatic_code_signing(path: "test.xcodeproj",
              team_id: "Y737MXXXXXX"
            )

            match(
              git_url: "https://git.coding.net/XXXXXXXX.git",
              app_identifier: "com.xxxxxxxx.test",
              type: "appstore"
            )

            update_project_provisioning(
              xcodeproj: "test.xcodeproj",
              target_filter: "test",
              profile:ENV["sigh_com.xxxxxxxx.test_appstore_profile-path"],
              build_configuration: "Release"
            )

            gym(
              workspace: "test.xcworkspace",
              scheme:"test",
              configuration: "Release",
              clean: true,
              export_method: "app-store",
              output_directory:"./build/",
              export_options: {
                method: "app-store",
                provisioningProfiles: { 
                  "com.xxxxxxxx.test" => ENV["sigh_com.xxxxxxxx.test_appstore_profile-name"]
                }
              },
              codesigning_identity:"iPhone Distribution: XXXXXX Common Name(XXXXXX)",
              output_name: "test_prod.ipa"
            )

            upload_symbols_to_crashlytics(
              dsym_path: "./build/test_prod.app.dSYM.zip",
              api_token: "ac2a264f7834a17a7d54ad806130ae1f23ad7c77"
            )
            
        end

**Comment by jwaldrip** [comment]
Well @wade0317 that did it! Be sure to claim the bounty at the top of this issue.
