### ISSUE TITLE
[match] How can make certificate for ApplePay base on CSR?

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#11809]
How can make certificate for ApplePayfor merchant base on CSR through fastlane?
Please help me

**Comment by taquitos** [comment]
Have you had a chance to check out the docs yet? I think something like: https://docs.fastlane.tools/actions/produce/#creating-apple-pay-merchants-and-associating-them-with-an-app-id might help.

**Comment by GandjaFuzz** [comment]
@taquitos yes I read this. 
But for merchant need upload CSR request and in answer receive CERT for payment system. 
this is functional not isset.

**Comment by GandjaFuzz** [comment]
I about this functional 
![2018-02-12_01-08-55](https://user-images.githubusercontent.com/14003794/36079169-5d2a64a2-0f91-11e8-8452-5982a551e616.png)

**Comment by GandjaFuzz** [comment]
For example in arg for produce set csr path and generated cert save in same dir
or
set csr data how string and get cert in ENV variable

**Comment by GandjaFuzz** [comment]
@taquitos you can help?

**Comment by taquitos** [comment]
@GandjaFuzz sorry, it's not supported right now in fastlane 😞 We don't have plans to add that feature right now since demand is very low and our current workload is very high. If you want to build it out we'd be happy to review your PR though 🚀

**Comment by GandjaFuzz** [comment]
😞😞😞😞😞😞😞😞😞😞

**Comment by Aaryahi** [comment]
@taquitos i have this problem too

**Comment by anniyanniyanniy** [comment]
@taquitos i have this problem too

**Comment by anniyanniyanniy** [comment]
+1

**Comment by oksiiii2909** [comment]
+1

**Comment by RishabhTayal** [comment]
@joshdholtz Any suggestions on I can start with the implementation for this?

**Comment by joshdholtz** [comment]
@RishabhTayal I actually have never done anything with Apple Pay so I don't really have any suggestions besides inspect the requests in browser and/or with Charles Proxy 😉

**Comment by RishabhTayal** [comment]
@joshdholtz I meant how and where in `fastlane` would I generate the certificates? something similar to `match` or `sigh`?

**Comment by joshdholtz** [comment]
@RishabhTayal Ohhhhhhhhhh lol... I would actually think maybe a brand new action? `pem` does something similar but for push certificates so I would create a new action for this I think

**Comment by GandjaFuzz** [comment]
I think for example need use so
in fastfile
```//add new
pay (
	username: USER,
	csr: REQUEST, //path or data from csr
	merchant: merchant.com.example.app,
)

ENV['APPLE_PAY_CERTIFICATE_ID']
ENV['APPLE_PAY_CERTIFICATE'] //maybe base64 or paste in file

//download
pay (
	username: USER,
	merchant: merchant.com.example.app,
	certificate_id: id
)

ENV['APPLE_PAY_CERTIFICATE_ID']
ENV['APPLE_PAY_CERTIFICATE'] //maybe base64 or paste in file

//revoke
pay (
	username: USER,
	merchant: merchant.com.example.app,
	certificate_id: id,
	revoke: true
)```

**Comment by RishabhTayal** [comment]
Can we reopen this issue? I have a working PR in progress. @joshdholtz @taquitos ?

**Comment by GandjaFuzz** [comment]
hello, when it is will released?

**Comment by GandjaFuzz** [comment]
I review commit action for apple_pay_cert. 
need add configuration with custom certificate signing request

**Comment by RishabhTayal** [comment]
@joshdholtz any plan on merging the PR?

**Comment by janpio** [comment]
PR #12466 is waiting for reviews and merge.

**Comment by GandjaFuzz** [comment]
I see this pr, it is not correct, need can set path to custom csr, but this don’t have this functional.

**Comment by janpio** [comment]
@RishabhTayal Any comment on what @GandjaFuzz wrote?

**Comment by kornerr** [comment]
LOL @fastlane-bot

**Comment by kornerr** [comment]
So, is this ready or not?
