### ISSUE TITLE
Indirect dependency from PortalClient instance to Portal.client class method

### ISSUE THREAD

**Issue by sergiocampama** [fastlane/fastlane#11816]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/portal_client.rb#L755

Many methods in PortalClient appear to call ensure_csrf() which in turn calls klass.all. For example, in the create_app!, ensure_csrf is called with the App module. This in turns calls App.all, which calls the Portal.client.apps method. This assumes that the client where we're calling create_app! from is the same as the Portal.client. Because of this, standalone usage of PortalClient is not possible.

My current workaround for this issue is to monkey patch ensure_csrf to do nothing, which seems to work, and this makes me wonder if ensure_csrf is needed at all.

```
module Spaceship
  class PortalClient
    def ensure_csrf(klass)
    end
  end
end

```

**Comment by sergiocampama** [comment]
This is an architectural issue, more than a running issue

**Comment by KrauseFx** [comment]
Sorry about that, those kinds of changes are risky, as very often they'd break something else. If the workaround works for you, let's keep it like this for now?

**Comment by sergiocampama** [comment]
This is not blocking us, but hopefully it will get taken looked at at some point :)

**Comment by sergiocampama** [comment]
still open
