### ISSUE TITLE
I want to add a time variable in output_directory, but I do not know how to add it.

### ISSUE THREAD

**Issue by codergelly** [fastlane/fastlane#11818]
I want to add a time variable in output_directory, but I do not know how to add it.I read all the documents, there is no explanation. Have this function?

**Comment by KrauseFx** [comment]
What is the `output_directory` you refer to? Part of a built-in action?

**Comment by codergelly** [comment]
Yes, in the build_app action

**Comment by KrauseFx** [comment]
You didn't share your `fastlane env` output, so I can only guess here, that you have a `Fastfile`. If you do, use the following:
```ruby
build_app(output_directory: "#{Time.now.to_i}_build/")
```
which will use `"1518445001_build/"` as a output directory 👍

**Comment by joshdholtz** [comment]
Closing this for now as there hasn't been any response and @KrauseFx answer is 💯
