### ISSUE TITLE
Bad Request Error while using spaceship to add device to a provision profile

### ISSUE THREAD

**Issue by ankitr432** [fastlane/fastlane#11815]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to write some ruby code using the spaceship ruby library, to add an already registered device to my provision profile. My ruby code is - 

    require "spaceship"

    Spaceship::Portal.login('username', 'password')

    Spaceship::Portal.client.team_id = "<teamId>"
   
    profile = Spaceship::Portal.provisioning_profile.development.find_by_bundle_id(bundle_id: "com.domain.app").first
     
    # at this point i can fetch and display the provision profile 
    #using puts profile.inspect
    
    #also i can verify that the device exists by using
    #Spaceship::Portal.device.find_by_udid("<registered-device-udid>").inspect

    profile.devices.push(Spaceship::Portal.device.find_by_udid("<registered-device-udid>"))

    profile.update!

returns the following error
      
    /usr/local/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse': 765: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:734:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:569:in `with_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:733:in `send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:621:in `request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/portal_client.rb:672:in `repair_provisioning_profile!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:459:in `block in update!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:569:in `with_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:458:in `update!'
	from register.rb:38:in `<main>'    

I have tried some variations such as 

    profile.devices = Spaceship::Portal.device.all

but they return the same error

I run the ruby code as 

    ruby register.rb

Can you please help me fixing this error?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/usr/local/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse': 765: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:734:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:569:in `with_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:733:in `send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:621:in `request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/portal_client.rb:672:in `repair_provisioning_profile!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:459:in `block in update!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:569:in `with_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:458:in `update!'
	from register.rb:38:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.68.2  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.5        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
</details>

*generated on:* **2018-02-09**
</details></pre>

**Comment by ankitr432** [comment]
Hi everyone, 

This looks like a very basic piece of code. Does anyone have any clue as to what could be causing this error? Any pointers would be appreciated :)

Thanks

**Comment by KrauseFx** [comment]
It might be worth inspecting the network traffic and looking of what's wrong. I could imagine the devices are causing the issues with the `.push` command. Maybe it doesn't expect an array of devices or something? I'm not sure, but once you investigated the network traffic you should know what's going wrong https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md

**Comment by joshdholtz** [comment]
@ankitr432 Hey 👋 Were you able to get this working?
