### ISSUE TITLE
Feature Proposal: formally define lane parameters (similar to actions/plugins)

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#11824]
Similarly to how actions and plugins can define their available options with...
```rb
def self.available_options
  [
    FastlaneCore::ConfigItem.new(key: :apk,
                                 env_name: "",
                                 description: ".apk file for the build ",
                                 optional: true,
                                 default_value: Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH])
  ]
end
```

... I would like to propose a solution to give lanes a similar ability.

## Currently
Current lanes can accept parameters through a standard hash.
Example CLI: `fastlane deploy submit:false build_number:24`
```rb
lane :submit do |options|
  build_number = options[:build_number]
  if options[:submit]
    # Do something with
  end
end
```

### Pros
- No setup
- Standard Ruby hash (no new classes to understand)

### Cons
- Parameters aren't documented
- Parameter types aren't checked or defaulted
- Parameters can't be marked as required
  - And can't provide a CLI input if are required but not supplied 

## Proposed Example
I would like to include a `lane_options` configuration (or something like this) to give lanes optional structure and documentation around their parameters.
```rb
lane :submit do |options|
  build_number = options[:build_number]
  if options[:submit]
    # Do something with
  end
end
lane_options :submit do 
  [
    OptionItem.new(key: :build_number,
      description: "",
      optional: false
    )
  ]
end
```

This `lane_options` would be used in the following ways:
- Verify proper parameters being passed into lanes when executed
  - Allow for CLI inputs if required
- Show documentation when running `fastlanes lanes`
- Show documentation in generated fastlane markdown file
-  Allow for UI to be generated individually for lane parameters in https://github.com/fastlane/ci
  - Proposed solution for CI - https://github.com/fastlane/ci/issues/125

**Comment by milch** [comment]
In principle I think this is good, however, I'd drop the `OptionItem.new` from the Array and instead use a `Hash` directly

**Comment by getaaron** [comment]
I think it might be confusing if we don’t use the existing `OptionItem` class. @milch can you show an example of your proposed API?

**Comment by milch** [comment]
The existing class is `FastlaneCore::ConfigItem`, so I was assuming this `OptionItem` was going to be something new. Additionally, the `ConfigItem` is mostly used internally as noted by @joshdholtz and not by people writing their `Fastfile`. I'm not saying not to use a class like that at all, but instead simplifying the API from this:

```ruby
lane_options :submit do 
  [
    OptionItem.new(key: :build_number,
      description: "",
      optional: false
    )
  ]
end
```

to this:

```ruby
lane_options :submit do 
  [
    {
      key: :build_number,
      description: "",
      optional: false
    }
  ]
end
```

**Comment by joshdholtz** [comment]
@milch I totally did not mean to "refuse" a class type. I figured it be a new one and definitely did not check if that name was already being used 🙃 

But I think I disagree with the hash 😉 We used to use a hash for action options and that turned into a mess since you can literally put anything in a hash. Making the options a class allows us to have clear documentation around that class and what it can all do along with encapsulating any logic in the class.

**Comment by milch** [comment]
That documentation can still exist, but I think it'd be easier to use for the user. The implementation of `lane_options` could look something like this 

```ruby
def lane_options(name)
  option_array = yield
  option_array.map! { |o| OptionItem.new(**o) } 
  # ... and so on 
end
```

Which would yield functionally identical diagnostics for the user while reducing noise in the `Fastfile`. 

Personally I know that every time I write a custom action (which is infrequent) I have to look up the exact class and module to use for the `available_options` call (i.e. `FastlaneCore::ConfigItem`). The things I do remember are the attributes `key`, `description`, `default_value`, `optional`, since those are the ones that are actually important

**Comment by joshdholtz** [comment]
Hmmm... I can see that working 🤔 And I GUESSSSSSS plugin are more developer facing so its nice to have classes where this is more user facing so its easier to do hashes

@milch Why are you so smart?

**Comment by milch** [comment]
lol the only reason I'm even suggesting it is because I can't remember the classnames. Being smart's got nothing to do with it 😉

**Comment by revolter** [comment]
Stupid question, could it also convert the value so `options[:name]` receives the required type (e.g. bool, int, array) automatically?

**Comment by revolter** [comment]
We really need this ❤️

**Comment by revolter** [comment]
Bot, please, stahp 😢

**Comment by milch** [comment]
Josh the rebel
