### ISSUE TITLE
Languages not accepted, but do match valid options

### ISSUE THREAD

**Issue by rckoenes** [fastlane/fastlane#11826]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We are summitind a lot of VPP apps with different languages from one project. 
and for this we use the `languages` on `upload_to_app_store`.

It works if we set the languages in the fastlane file, but not when we load them via .env deil

loading via an .envfile will giving the following error:

```
fastlane finished with errors

[!] The following languages are invalid and cannot be activated: ["nl-NL", "en-US", "fr-FR"]

Valid languages are: ["en-CA", "fr-CA", "en-US", "es-MX", "en-GB", "de-DE", "fr-FR", "nl-NL", "el", "tr", "da", "fi", "it", "no", "pt-PT", "ru", "es-ES", "sv", "en-AU", "zh-Hans", "zh-Hant", "id", "ja", "ko", "ms", "th", "vi", "pt-BR"]
```

The flowing is .nev file for this app:

```
DLV_BUNDLE_ID="com.AppName.client"
DLV_LANGUAGE=["nl-NL", "en-US", "fr-FR"]

GYM_SCHEME="Client app name"
```

But the languages given are in the valid array!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

private_lane :run_carthage do |options|
  # Install carthage libaries

  if options[:mode] == 'update'
	  carthage(
		command: "update",       # One of: build, bootstrap, update, archive. (default: bootstrap)
		use_submodules: false,      # Add dependencies as Git submodules.
		use_binaries: true,         # Check out dependency repositories even when prebuilt frameworks exist
		no_build: false,            # When bootstrapping Carthage do not build
		no_skip_current: false,     # Don't skip building the current project (only for frameworks)
		verbose: false,             # Print xcodebuild output inline
		platform: "iOS",            # Define which platform to build for (one of 'all', 'Mac', 'iOS', 'watchOS', 'tvOS', or comma-separated values of the formers except for 'all')
		configuration: "Release",   # Build configuration to use when building
		cache_builds: false,        # By default Carthage will rebuild a dependency regardless of whether its the same resolved version as before.
	  )
  end
  if options[:mode] == 'bootstrap'
	  carthage(
		command: "bootstrap",       # One of: build, bootstrap, update, archive. (default: bootstrap)
		use_submodules: false,      # Add dependencies as Git submodules.
		use_binaries: true,         # Check out dependency repositories even when prebuilt frameworks exist
		no_build: false,            # When bootstrapping Carthage do not build
		no_skip_current: false,     # Don't skip building the current project (only for frameworks)
		verbose: false,             # Print xcodebuild output inline
		platform: "iOS",            # Define which platform to build for (one of 'all', 'Mac', 'iOS', watchOS', 'tvOS', or comma-separated values of the formers except for 'all')
		configuration: "Release",   # Build configuration to use when building
		cache_builds: false,        # By default Carthage will rebuild a dependency regardless of whether its the same resolved version as before.
	  )
  end
end


private_lane :deploy_app_store do |options|


  # Build  the app
  gym(
	clean: true,
	scheme: options[:scheme], 
	include_bitcode: true, 
	include_symbols: true
  )


  if options[:submit_for_review]

	# Upload and submit it for review.
	upload_to_app_store(
	  force: true,
	  submit_for_review: true,
	  skip_screenshots: true,
	  automatic_release: true,
	  skip_metadata: false,
	  username: ENV['DLV_ITUNESCONNECT_USERNAME'],
	  app_identifier: ENV['DLV_BUNDLE_ID'],
	  ignore_language_directory_validation: true,
	  languages: ENV['DLV_LANGUAGE'],
	)
  else 
	pilot(
	  skip_waiting_for_build_processing: true
	)

  end

end

platform :ios do

  before_all do
	# Clear an build data
	clear_derived_data

	xcode_select "/Applications/Xcode.app"
  end

  after_all do 
	clean_build_artifacts
	notification(
	  subtitle: "Watch here!",
	  message: "Fastlane has finished",
	  sound: "default"
	)
  end

  # General lanes

  desc "Create new iOS app"
  lane :create_app do
	project = './Whitelabels.xcodeproj'
	version_number = get_version_number(
	  xcodeproj: project
	)

	if ENV['ITUNES_NAME'].length > 0
		app_name = ENV['ITUNES_NAME']
	else
	   app_name = ENV['GYM_SCHEME']
	end

	produce(
	   app_identifier: ENV['DLV_BUNDLE_ID'],
	   app_name: app_name,
	   app_version: version_number,
	   sku: ENV['DLV_BUNDLE_ID'],
	   enable_services: {
		 data_protection: "complete",
		 push_notification: "on"
	   }
	)
  end 

  desc "Increment build version"
  lane :bump_version do
	# ensure_git_status_clean

	project = './Whitelabels.xcodeproj'

	increment_build_number(
	  xcodeproj: project,
	)

	build_number = get_build_number(
	  xcodeproj: project
	)

	commit_message = "Version bumped to " + build_number
	commit_version_bump(
	  xcodeproj: project,
	  include: ["Targets/*.plist"],
	  message: commit_message
	) 

	add_git_tag(
	  tag: build_number
	)
	push_git_tags
	push_to_git_remote

  end

  desc "Build and submit to Apple, upload to crashyltics."
  lane :deploy do
	#run_carthage(mode: 'bootstrap')
	deploy_app_store(
	  submit_for_review: true,
	  schema: ENV['GYM_SCHEME']
	)
  end

  desc "Build and deploy to TestFlight, upload to crashyltics."
  lane :deploy_release_candidate do
	run_carthage(mode: 'bootstrap')
	deploy_app_store(
	  submit_for_review: false
	)
  end

  desc "Build one app and push to Fabric (needs environment)"
  lane :build_beta do |options|
	clear_derived_data

	gym(
	  clean: true,
	  scheme: options[:scheme], 
	  include_bitcode: true, 
	  include_symbols: true,
	  export_method: "ad-hoc"
	)

	# Upload to fabric and inform the user group
	crashlytics(
	  api_token: ENV['CRASHLYTICS_TOKEN'], 
	  build_secret: ENV['CRASHLYTICS_SECRET'],
	  groups: ENV['CRASHLYTICS_GROUP']
	)

	clean_build_artifacts
  end

  desc "Deploy AppName to Fabric"
  lane :AppName_to_Fabric do
	  run_carthage(mode:'bootstrap')
	  build_beta(scheme: "AppName")
  end

 
  desc "Update the Urban Airship configuration"
  lane :update_urban_airship do
	 production_key = ENV['URBANAIRSHIP_PRODKEY']
	 production_app_secret = ENV['URBANAIRSHIP_PROD_APP_SECRET']
	 if production_key && production_app_secret
	  update_urban_airship_configuration(
		plist_path: "./Targets/#{ENV['GYM_SCHEME']}/AirshipConfig.plist",
		production_app_key: production_key,
		production_app_secret: production_app_secret
	  )
	 end
  end

  desc "Runs all the unit tests"
  lane :unit_test do
	scan(scheme: "Tests")
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "nl.AppName.iphone" # The bundle identifier of your app
apple_id "mobile-development@AppName.nl" # Your Apple email address

team_id "<snip>"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.3        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-02-13**
</details>

**Comment by janpio** [comment]
Did I see that right that it is returning the error message for _all_ your languages?

**Comment by rckoenes** [comment]
Yes, but when if past the language array directly in the `fastfile` it works, but not from the `.env` file.

**Comment by janpio** [comment]
So this works:

```
upload_to_app_store(
   ...
   languages: ["nl-NL", "en-US", "fr-FR"],
   )
```

buts this doesn't:

```
upload_to_app_store(
   ...
   languages: ENV['DLV_LANGUAGE'],
)
```

Correct?

Then I think your error message is actually that, the on language `["nl-NL", "en-US", "fr-FR"]` (one string) can not be activated - meaning that the ENV variable can not handle a list/array/hash (at least in the way you tried). Does that make sense?

**Comment by rckoenes** [comment]
Yes that is correct, that seems to be my conclusion as well.
Declaring the array in the ENV does not seem to work.

**Comment by rckoenes** [comment]
Ok I've got a solution:

##ENV file##
DLV_LANGUAGE= "en-US,nl-NL,fr-FR"

## fastfile ##
languages: ENV['DLV_LANGUAGE'].split(",")

**Comment by janpio** [comment]
I think this is more an issue with ENV variables in general - it is a key value store. If you want to turn that into a data structure, you have to do so yourself as you did with the `split`.

Let's see if someone suggest a better solution. Otherwise it might be worth adding this to the ENV part of the docs as a common usage scenario.

**Comment by taquitos** [comment]
@janpio @rckoenes yeah, that's the best solution. You can't store anything other than strings in ENV vars
So most of the ENV vars fastlane supports can actually be a string with comma separators, or an actual ruby array.
