### ISSUE TITLE
Fail to distribute app to external testers with pilot

### ISSUE THREAD

**Issue by alexs555** [fastlane/fastlane#11828]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>ios-build  /usr/local/bin/fastlane pilot distribute -a **** -u ***  --app-platform ios --changelog "text" --distribute_external true --wait_for_uploaded_build true --groups "**"
[✔] 🚀 
[16:18:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:18:07]: Login to iTunes Connect (***)
[16:18:10]: Login successful
[16:19:30]: Successfully set the changelog for build
[16:19:30]: Distributing new build to testers: 2.0 

Looking for related GitHub issues on fastlane/fastlane...

➡️  Waiting for iTunes Connect to finish processing the new build 
    https://github.com/fastlane/fastlane/issues/9664 [closed] 16 💬
    29 Nov 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/client.rb:290:in `handle_response': [!] {"code"=>"ITC.response.error.INVALID_REQUEST", "description"=>"Failed to submit build for review."} (Spaceship::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/spaceship/lib/spaceship/test_flight/build.rb:204:in `submit_for_testflight_review!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/pilot/lib/pilot/build_manager.rb:149:in `distribute_build'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/pilot/lib/pilot/build_manager.rb:88:in `distribute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/pilot/lib/pilot/commands_generator.rb:78:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre>fastlane env
[✔] 🚀 
[17:31:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:31:44]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.2       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
</details></pre>
</details>

Hello!
Found this issue while trying to distribute binary to external testers with 'pilot distribute' .
It was successfully uploaded with fastlane deliver and is shown in itunesconnect (it is available for internal testers) but as for external testres - it has "yellow" status "approved" (which is even not mentioned in official apple docs - https://help.apple.com/itunes-connect/developer/#/dev18557d60e)
Also it is possible to promote it manualy.

Actually, it seems to be old error - https://github.com/fastlane/fastlane/issues/5123
 <center><h1>504 Gateway Time-out</h1></center>

<img width="862" alt="2018-02-14 18 24 31" src="https://user-images.githubusercontent.com/3940001/36212386-dee1123c-11b4-11e8-8d9b-b51169d5a1af.png">

**Comment by m-conklin** [comment]
I'm getting this also. But alternating with {"code"=>"ITC.response.error.OPERATION_FAILED", "description"=>"Failed to submit build for review."}
Which is probably a different manifestation of the same error.

**Comment by minuscorp** [comment]
So for the app to be released to external testers is mandatory to provide a changelog into the build using pilot it in the iTunes connect platform. Can you check that?

**Comment by alexs555** [comment]
@minuscorp What do you mean?

> /usr/local/bin/fastlane pilot distribute -a **** -u ***  --app-platform ios --changelog "text" --distribute_external true --wait_for_uploaded_build true --groups "**"

changelog is provided actually, moreover in Itunesconnect i can see this changelog in "what to test" section, but, nevertheless, app was not provided toe xternal testers

**Comment by m-conklin** [comment]
I'm also including the changelog, and it is showing up on iTunes Connect. It uploads that first then attempts to distribute to external testers and fails.

**Comment by alexs555** [comment]
@m-conklin can you please check the state of your build in itunes connect? also "approved" like mine? or smth other?

**Comment by m-conklin** [comment]
They go to approved for me too.

**Comment by alexs555** [comment]
I think Spaceship fails to create a right request for this(unexpected) state

 

> /spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review

**Comment by m-conklin** [comment]
Agreed. I'm getting the same.

**Comment by beefon** [comment]
Getting EXACTLY the same issue. Some weird Approved yellow state, unable to distribute to external testers via fast lane. I can add test group myself from iTC web UI and that is all I have to do to move it to the green state. Fastlane fails to do that for some reason.

**Comment by minuscorp** [comment]
Hi, so for us to track this bug it would be great if you can provide the actual request and response that are being made in the issue your raise. I recommend you to read [this](https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md#debugging-and-patching-spaceship-issues) to get information about how to debug the `Spaceship` requests being made.

**Comment by alexs555** [comment]
I sniffed traffic and notices that build state "approved" is not supported in fastlane and when a build has this state it tries to send it to review, and fails with 504.
My pr fixes this

**Comment by bhorwood** [comment]
This still appears to be happening after the https://github.com/fastlane/fastlane/pull/11849 release.

**Comment by michellehalliwell** [comment]
I'm also still seeing this issue with version 2.83.0
`/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.83.0/spaceship/lib/spaceship/test_flight/client.rb:289:in `handle_response': [!]  (Spaceship::UnexpectedResponse)`

**Comment by minuscorp** [comment]
Let's try to debug the request that is being made and the response to see where the issue is. Can you do it @michellehalliwell @bhorwood ?

**Comment by ergunkocak** [comment]
I'm also seeing this issue with version 2.84.0

`bundler: failed to load command: fastlane (/Users/jenkins/.gem/ruby/2.5.0/bin/fastlane)
Spaceship::UnexpectedResponse: ?[31m[!] {"code"=>"ITC.response.error.OPERATION_FAILED", "description"=>"Failed to submit build for review."}?[0m
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/spaceship/lib/spaceship/test_flight/client.rb:292:in `handle_response'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/spaceship/lib/spaceship/test_flight/build.rb:212:in `submit_for_testflight_review!'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/pilot/lib/pilot/build_manager.rb:163:in `distribute_build'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/pilot/lib/pilot/build_manager.rb:102:in `distribute'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/pilot/lib/pilot/build_manager.rb:60:in `upload'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:111:in `block (2 levels) in parsing_binding'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:61:in `block (2 levels) in parsing_binding'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/jenkins/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/jenkins/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/jenkins/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jenkins/.gem/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
  /Users/jenkins/.gem/ruby/2.5.0/gems/fastlane-2.84.0/bin/fastlane:20:in `<top (required)>'
  /Users/jenkins/.gem/ruby/2.5.0/bin/fastlane:23:in `load'
  /Users/jenkins/.gem/ruby/2.5.0/bin/fastlane:23:in `<top (required)>'`

**Comment by joshdholtz** [comment]
I don't know if this helps or not but I actually get the `Failed to submit build for review.` error when using the iTC website (without fastlane) when trying to distribute to external testers. Been happening to me since January/February. I have to retry about 4 or 5 times before it happens. This probably makes things more confusing. So I don't know if this means its more of an iTC issue??? 😖

**Comment by jeffmcfadden** [comment]
Same, in 2.89.0

```
bundler: failed to load command: fastlane ([...]bin/fastlane)
Spaceship::UnexpectedResponse: [!] {"code"=>"ITC.response.error.OPERATION_FAILED", "description"=>"Failed to submit build for review."}
  [...]gems/fastlane-2.89.0/spaceship/lib/spaceship/test_flight/client.rb:299:in `handle_response'
  [...]gems/fastlane-2.89.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
  [...]gems/fastlane-2.89.0/spaceship/lib/spaceship/test_flight/build.rb:212:in `submit_for_testflight_review!'
  [...]gems/fastlane-2.89.0/pilot/lib/pilot/build_manager.rb:159:in `distribute_build'
  [...]gems/fastlane-2.89.0/pilot/lib/pilot/build_manager.rb:98:in `distribute'
  [...]gems/fastlane-2.89.0/pilot/lib/pilot/build_manager.rb:60:in `upload'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  [...]gems/fastlane-2.89.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:20:in `block (2 levels) in parsing_binding'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  [...]commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  [...]commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  [...]commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  [...]fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  [...]commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  [...]fastlane-2.89.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
  [...]fastlane-2.89.0/bin/fastlane:20:in `<top (required)>'
  [...]bin/fastlane:23:in `load'
  [...]bin/fastlane:23:in `<top (required)>'```

**Comment by jeffmcfadden** [comment]
Update: Today Fastlane works fine, no changes made. This error seems to be coming from iTC itself, and not because Fastlane is doing something wrong, so far as I can tell now.
