### ISSUE TITLE
Builds uploaded with pilot and distributed with the groups option are not submitted for review.

### ISSUE THREAD

**Issue by thibaudrobelain** [fastlane/fastlane#11825]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<pre>04:09:59 [04:09:59]: Build doesn't show up in the build list anymore, waiting for it to appear again
04:10:30 [04:10:30]: Successfully finished processing the build *redacted*
04:10:30 [04:10:30]: Distributing new build to testers: *redacted*
04:10:31 [04:10:31]: Successfully distributed build to Internal testers 🚀</pre>

Builds we upload with fastlane with the intent to distribute to a "Nightly Testers" group don't seem to be submitted for review. When logging into iTC, the builds appear as waiting for review. However, the logging seems to indicate that the distribute_build method is hit, which would normally indicate that the build would be submitted for review.

### Environment

Using a Gemfile with fastlane 2.80.0

Lane that uploads to TestFlight is the following:
```private_lane :upload_to_testflight do |options|
  ipa_path = *redacted*
  pilot(
    ipa: ipa_path,
    distribute_external: false,
    skip_waiting_for_build_processing: options[:skip_waiting_for_build_processing], <- false
    wait_for_uploaded_build: true,
    changelog: "Bug fixes",
    beta_app_description: "Nightly Build",
    beta_app_feedback_email: "redacted@redacted.com",
    groups: ["Nightly Testers"])
```

I'm wondering what's the best way to debug this? Should I open up a PR that adds some more logging around this part of the code? Has anyone had this issue on 2.80.0?

**Comment by joshdholtz** [comment]
Will look into 👌

**Comment by thibaudrobelain** [comment]
Thanks @joshdholtz. There's an update on my end, it seems like we're hitting some some form of #11828. The first build of a new app version is submitted for review correctly and then subsequent builds only manage to get into the "Approved" state before getting a 504 and making fastlane fail.

**Comment by thibaudrobelain** [comment]
I'll close this in favor of #11828
