### ISSUE TITLE
More `rubocop` cops to ensure cross platform compatibility

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11827]
Yesterday @milch suggested to add more cops for `rubocop` that make sure it is harder to accidentally cause problems on platforms besides macOS when working on _fastlane_ - even before CI fails. Much faster feedback loop, and so more probable to actually be used and not frustrate developers.

In the past he already created a check for `fork` usage as this is problematic: https://github.com/fastlane/fastlane/pull/11502

So I created this issue to have a place where to collect ideas for other things to check for.

**Comment by janpio** [comment]
One obvious thing I could think of were paths (https://github.com/fastlane/fastlane/pull/11427/files):

- Usage of `/tmp` in paths instead of `Dir.mktmpdir` or `Dir.tmpdir`.
- Usage of `~` instead of `Dir.home`.

(I did a _lot_ of PRs for Linux/Ubuntu and Windows support in the last two months, so I will go through them step by step and see if anything else pops up as a "pattern" that one could check for.)

**Comment by KrauseFx** [comment]
Would it be enough to have something like this? https://github.com/fastlane/fastlane/blob/master/fastlane/Fastfile#L24-L27

**Comment by janpio** [comment]
That would indeed be an option as well. Maybe add an alias for that method. 
Advantage of rubocop would be that it can directly give suggestion on how to solve it.
