### ISSUE TITLE
Cannot build project using gym

### ISSUE THREAD

**Issue by olejnjak** [fastlane/fastlane#11830]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello, I am unable to build my project using gym it always fails on touching dsyms. The raw touch command is successful when I run it manually from terminal. 

Also archive and export from xcode works, just using gym it fails. Any idea please?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>▸ Touching Mervis.app
▸ Signing /Users/olejnjak/Library/Developer/Xcode/DerivedData/Mervis-cxleutduaujtdsaexyxzidkgzxbg/Build/Intermediates.noindex/ArchiveIntermediates/Stage/InstallationBuildProductsLocation/Applications/Mervis.app
▸ Touching Mervis.app.dSYM
** ARCHIVE FAILED **
[16:42:52]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.80.0                  |
| export_method | enterprise              |
| sdk           | iPhoneOS11.2.sdk        |
+---------------+-------------------------+

[16:42:52]: ▸ Touch /Users/olejnjak/Library/Developer/Xcode/DerivedData/Mervis-cxleutduaujtdsaexyxzidkgzxbg/Build/Intermediates.noindex/ArchiveIntermediates/Stage/BuildProductsPath/AdHoc-iphoneos/Mervis.app.dSYM
[16:42:52]: ▸     cd /Users/olejnjak/Desktop/ios-merge-request-builder
[16:42:52]: ▸     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
[16:42:52]: ▸     /usr/bin/touch -c /Users/olejnjak/Library/Developer/Xcode/DerivedData/Mervis-cxleutduaujtdsaexyxzidkgzxbg/Build/Intermediates.noindex/ArchiveIntermediates/Stage/BuildProductsPath/AdHoc-iphoneos/Mervis.app.dSYM</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby


##################################### SETTINGS #####################################

inhouse_apple_id = 'unicorn@ackee.cz'
production_apple_id = 'unicorn@ackee.cz'
connect_team_id = "631675"
production_team_id = "A36K97VQWC"

####################################################################################

ENV["ACK_BACKTOBASICS"] = "1"

import(download_from_git(url: 'git@gitlab.ack.ee:Ackee/fastlane.git', use_cache: is_xcode ))

if !is_xcode then
xcversion(version: "~> 9.0")
end
ENV["GYM_USE_LEGACY_BUILD_API"] = nil

  desc "Downloads provisioning for all environments"
  lane :provisioning do |options|
    environment = options[:environment]

    if environment && !(is_environment(environment: environment))
      raise "Unknown environment #{environment}"
    end

    if !environment || environment == "Development"
      provisioning_match(configuration: "Debug",
                        type: "development",
                        app_identifier: app_identifier("Development"),
                        username: inhouse_apple_id,
                        team_id: team_id("Development"),
                        readonly: true)
    end

    if !environment || environment == "Stage"
      provisioning_match(configuration: "AdHoc",
                        type: "enterprise",
                        app_identifier: app_identifier("Stage"),
                        username: inhouse_apple_id,
                        team_id: team_id("Stage"),
                        readonly: true)
    end

    if !environment || environment == "Production"
      provisioning_match(configuration: "AppStore",
                        type: "appstore",
                        app_identifier: app_identifier("Production"),
                        username: production_apple_id,
                        git_url: ENV["ACK_PRODUCTION_MATCH_GIT"],
                        team_id: production_team_id,
                        readonly: false)

      #Use sigh only for client accounts (on our account you would use match)
      # provisioning_sigh(configuration: "AppStore",
      #                   username: production_apple_id,
      #                   team_id: team_id("Production"),
      #                   app_identifier: app_identifier("Production"))
    end

  end

  desc "Submit new **beta** build to Hockey app"
  lane :beta do

    environment = "Stage"

    #Build number
  	build_number = number_of_commits
		set_build_number(build_number: build_number)

    #Download provisioning
    provisioning(environment: environment)

    #Setup environments, app identifier and app name
    set_environment(environment: environment)

    #Setup badge for beta
    #badge(shield: "#{get_version_number}-#{number_of_commits}-blue", dark: true, shield_no_resize: true)

    begin
      gym(
      	  scheme: environment,
  		  configuration: "AdHoc",
  		  export_method: "enterprise",
          clean: true

  		)
    ensure
      # Put badge back to original
      sh "git checkout -- ../Resources/Images.xcassets/"
    end

    if !is_ci
        hockey_identifier = get_nested_environment_plist_value(key: "hockey.identifier", environment: "Development")

        # hockey(
        #       public_identifier: hockey_identifier,
        #       notify: '0'
        # )
    end
  end


  desc "Deploy new version to the App Store (and also hockey app)"
  lane :appstore do |options|

      environment = "Production"

      version = get_version_number
      #ensure_appstore_version(app_identifier: app_identifier(environment), version: version, build_number: number_of_commits, team_id: connect_team_id)


    	build_number = number_of_commits
  		set_build_number(build_number: build_number)

      #Setup environments, app identifier and app name
      set_environment(environment: environment)


      provisioning(environment:environment)

      gym(
  		  scheme: environment,
        configuration: "AppStore",
  		  clean: true
  		)

      deliver(
          team_id: connect_team_id,
          force: is_ci,
          skip_screenshots: true,
          skip_metadata: true
      )
  end

  desc "Switches environment and sets app_name and app_identifier in plist"
  lane :set_environment do |options|
      if is_xcode
          UI.message "Xcode run script phase"
      end

      environment = options[:environment]

      if !is_environment(environment: environment)
          raise "Unknown environment #{environment}"
      end

      display_name = app_name(environment)
      app_identifier =  app_identifier(environment)

      UI.message "Setting environment for #{environment}"

      # Change environment plist
      replace_environment_plist(environment: environment)
      replace_google_plist(environment: environment)

      environment_dict = {
          "ACK_BUILD_NUMBER" => number_of_commits,
      }

      generate_preprocess_header(values: environment_dict)
  end

  desc "Install pods"
	lane :pods do |options|
	    pod_install
	end

  desc "Generate SwiftGen enums"
  override_lane :swiftgen do |options|
      generated_dir = File.expand_path(ENV["ACK_GENERATED_ITEMS_DIR"], FastlaneCore::FastlaneFolder.path)
      swiftgen_binary = File.expand_path("../Pods/SwiftGen/bin/swiftgen", FastlaneCore::FastlaneFolder.path)

      images_file = File.expand_path("Images.swift", generated_dir)
      assets_file = File.expand_path(ENV["ACK_IMAGES_PATH"], FastlaneCore::FastlaneFolder.path)
      localized_file = File.expand_path("LocalizedStrings.swift", generated_dir)
      localizable_file = File.expand_path(ENV["ACK_LOCALIZABLE_PATH"], FastlaneCore::FastlaneFolder.path)
      template_file = File.expand_path("../SwiftGen/strings.stencil", FastlaneCore::FastlaneFolder.path)

      sh "#{swiftgen_binary} images -t swift3 --output '#{images_file}' '#{assets_file}'"
      sh "#{swiftgen_binary} strings -p #{template_file} --enumName Localizable --output '#{localized_file}' '#{localizable_file}'"
  end


#end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| nanaimo                   | 0.2.3        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.2        |
| xcodeproj                 | 1.5.6        |
| tty-screen                | 0.6.4        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.1        |
| multi_json                | 1.13.1       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-02-13**
</details></pre>
</details>

**Comment by ugenlik** [comment]
What's your fastfile look like?

**Comment by minuscorp** [comment]
Are you sure you have manually selected in your xcode project targets to use the match generated certs? If you use the raw command without being selected those certs it will work because it'll use the xcode managed certs.

**Comment by olejnjak** [comment]
Yes I am, certs selected in project are generated by match but right now I am pursuing different issue which is not fastlane related and might have caused this, closing for now, will report back if this persists.
