### ISSUE TITLE
fastlane installation issue

### ISSUE THREAD

**Issue by vikashth1** [fastlane/fastlane#11846]
Hello,

I am new on platform and tried to install fastlane from root access but getting an error.

ERROR:  Error installing fastlane:
	jwt requires Ruby version >= 2.1.

I have already updated the jwt from website but still getting same issue, Can you please help me with understanding the process.

Having Mac Os Sierra 10.12

Waiting for your positive response.

**Comment by vikashth1** [comment]
Sorry but can you please tell me how to enable fastlane env because there is nothing explained about this.

**Comment by bhawin-bigstep** [comment]
Its the ruby version that you have to update.
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

This is my ruby version and fastlane installed like a charm

**Comment by vikashth1** [comment]
I already updated the ruby 2.7.5 Released trough terminal but still the same.

**Comment by joshdholtz** [comment]
@vikashth1 Can you run `ruby --version` and paste what the output is? It should be >= 2.1
