### ISSUE TITLE
Use CFBundleShortVersionString in add_git_tag

### ISSUE THREAD

**Issue by timcamber** [fastlane/fastlane#1184]
Is it possible to use CFBundleShortVersionString (e.g. "1.0.2") in [`add_git_tag`](https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#add_git_tag)? If not, I'd like to request this feature!

**Comment by KrauseFx** [comment]
You can pass any value, so you should be able to do something like this

```ruby
increment_version_number(...)

add_git_tag(
  tag: lane_context[SharedValues::VERSION_NUMBER]
)
```

**Comment by timcamber** [comment]
great, thanks!
