### ISSUE TITLE
Release app using fast lane (change status from "Pending Developer Release" to released

### ISSUE THREAD

**Issue by dessmith** [fastlane/fastlane#11842]
Hi,

I've been using Fastlane to _release_ my apps, by that I mean changing the status of an app from "Pending Developer Release" to released, so instead of having someone log into ITC and click the "Release this Version" button we just use fastlane (we release multiple apps at the same time)

I've done this by adding the code made by @hjanuschka https://github.com/fastlane/fastlane/issues/3481#issuecomment-264856531 this has been faultless until recently when things started to fail.

First I had an issue where  ```Spaceship::Tunes.login``` was undefined, to resolve this I added `require 'spaceship'` to the top of my fastfile. Then I got a ```undefined method `edit_version' for nil:NilClass``` error message

I'm assuming that some update has changed edit_version to version_sets, however I can't find much documentation on Spaceship, and I'm no ruby coder, so it's quicker if I post this here and ask for help.

Thanks

**Comment by dessmith** [comment]
My fastlane env is 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.1/bin/fastlane       |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
# If you want to automatically update fastlane if a new version is available:
# update_fastlane
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.48.0"
default_platform :ios
require 'Spaceship'

platform :ios do

  #------------------------- Crashlytics -------------------------#

  desc "This will create a new build and upload it to Crashlytics"
  desc "Provisioning Profiles for the application will be fetched and installed"
  desc "This will also create an iPA named in the path ./Archive/Archive.ipa"
  lane :fabric do
    cocoapods
    sigh(
      app_identifier: ENV['appBundleID'],
      team_id: ENV['ENTERPRISE_TEAM_ID'],
      cert_id: "WY969TXR45",
      skip_certificate_verification: true
    )
    gym(
      scheme: ENV['targetScheme'],
      workspace: "TMNews.xcworkspace",
      output_directory: ENV['targetDirectory'],
      export_method: "enterprise",
      output_name: "Archive",
      export_xcargs: "-allowProvisioningUpdates"
    )
    crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      ipa_path: ENV['targetDirectory'] + "/Archive.ipa",
      groups: "devs",
      notes_path: ENV['releaseNotesPath']
    )
    post_to_slack(scheme: ENV['targetScheme'], destination: "Fabric :airplane:")

  end

  #------------------------- Apple TestFlight -------------------------#

  desc "Builds and uploads a new Beta Build to Apple TestFlight"
  desc "Provisioning Profiles for the application will be fetched and installed"

  lane :testFlight do
    cocoapods
    sigh(
      app_identifier: ENV['appBundleID'],
      team_id: ENV['APPSTORE_TEAM_ID'],
      skip_certificate_verification: true,
      cert_id: "D2RVY5675H",
      force: true
    )
    gym(
      scheme: ENV['targetScheme'],
      workspace: "TMNews.xcworkspace", #Shoudl be the
      output_directory: ENV['targetDirectory'],
      export_method: "app-store",
      output_name: "Archive",
      export_xcargs: "-allowProvisioningUpdates"
    )
    pilot(
      ipa: ENV['targetDirectory'] + "/Archive.ipa",
      skip_waiting_for_build_processing: true
    )
    post_to_slack(scheme: ENV['targetScheme'], destination: "Apple TestFlight :rocket:")

  end

  #--------------------------- App Store Review -------------------------#

  desc "Submits an already uploaded binary for review on the App Store"
  desc "Allows the addition of release notes, to be added to the build"
  lane :submitForReview do
    # match(type: "appstore")
    # snapshot
    deliver(
      app_identifier: ENV['appBundleID'],
      submission_information: {
        add_id_info_uses_idfa: true,
        add_id_info_serves_ads: true,
        add_id_info_tracks_install: false,
        add_id_info_tracks_action: false,
        add_id_info_limits_tracking: true
      },
      team_id: ENV['APPSTORE_TEAM_ID'],
      app_version: ENV['App_Version_Number'],
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_metadata: false,
      submit_for_review: true,
      automatic_release: false,
      force: true,
      run_precheck_before_submit: true
    )

    slack(
      message: ":rocket: *#{ENV['Publication']} #{get_version_number(xcodeproj: "TMNews.xcodeproj")}* has been submitted for review with :appleinc: :sleuth_or_spy:",
      default_payloads: []
    )
  end

  desc "Clicks the 'Release This Version' on iTunes connect, for a given application id"
  lane :release do
    Spaceship::Tunes.login(ENV['DELIVER_USERNAME'])
    app = Spaceship::Tunes::Application.find(ENV['appBundleID'])
    version = app.edit_version
    version.release! # hits the "Release button"

    slack(
      message: ":rocket: *#{ENV['Publication']} #{get_version_number(xcodeproj: "TMNews.xcodeproj")}* is now *Live* on the App Store :rocket:",
      default_payloads: []
    )
  end

  ############################# UTIL ##############################

  private_lane :post_to_slack do |options|
    scheme      = options[:scheme]
    version     = get_version_number(xcodeproj: "TMNews.xcodeproj")
    destination = options[:destination]

    slack(
      message: "*#{ENV['Publication']} #{version} (Job Number #{ENV['CustomBundleName']})* has been submitted to *#{destination}*",
      default_payloads: [:git_branch, :last_git_commit_hash]
    )

  end

  ############################# POST ##############################

  # You can define as many lanes as you want
  # after_all do |lane|
  #   # This block is called, only if the executed lane was successful

  # end
  error do |lane, exception|
    slack(
      message: "*#{ENV['Publication']}* (Job Number #{ENV['CustomBundleName']}) failed, because #{exception.message}",
      success: false,
      default_payloads: [:git_branch, :last_git_commit_hash]
    )
  end

end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions
# fastlane reports which actions are used. No personal data is recorded.

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.81.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2018-02-14**
</details>

**Comment by minuscorp** [comment]
So `Spaceship::Tunes.login('user', 'password')` definitely exists, after that you should be able to get things moving in your application, for example: `app = Spaceship::Tunes::Application.find("your.bundle.id")`
