### ISSUE TITLE
Couldn't decrypt the repo, please make sure you enter the right password!

### ISSUE THREAD

**Issue by jwilson85** [fastlane/fastlane#11853]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

So Weather I encrypt the cirts or not. Was hoping there was even an or not. I just get the password loop. with the error: Couldn't decrypt the repo, please make sure you enter the right password!
I am checking out the branch correctly. And the cirts have their own repo. Which was what the other users who posted this error had troubles with. So I can't find any information as to why my password is not working. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
BOOJ0000197:BAMBOO-LT-JOB1 mobile$ fastlane enterprise --verbose
[11:01:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-02-15 11:01:57.38]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
INFO [2018-02-15 11:01:58.83]: ----------------------------------------
INFO [2018-02-15 11:01:58.83]: --- Step: Verifying fastlane version ---
INFO [2018-02-15 11:01:58.83]: ----------------------------------------
INFO [2018-02-15 11:01:58.83]: Your fastlane version 2.81.0 matches the minimum requirement of 2.29.0  ✅
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
INFO [2018-02-15 11:01:58.89]: ------------------------------
INFO [2018-02-15 11:01:58.89]: --- Step: default_platform ---
INFO [2018-02-15 11:01:58.89]: ------------------------------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
-------
INFO [2018-02-15 11:01:58.89]: Driving the lane 'ios enterprise' 🚀
INFO [2018-02-15 11:01:58.90]: -----------------------------------------------------
INFO [2018-02-15 11:01:58.90]: Step: git rev-parse --short HEAD 2> /dev/null | sed 's/(.*)//'
INFO [2018-02-15 11:01:58.90]: -----------------------------------------------------
INFO [2018-02-15 11:01:58.90]: $ git rev-parse --short HEAD 2> /dev/null | sed 's/(.*)//'
INFO [2018-02-15 11:01:59.02]: ▸ 2b750ed6
Successfully loaded Appfile at path '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Appfile'
- app_identifier: 'com.activewebsite.lyon-beta'
- apple_id: 'mobile@activewebsite.com'
- team_id: 'E65YP8XL5R'
-------
INFO [2018-02-15 11:01:59.07]: ------------------------------------
INFO [2018-02-15 11:01:59.07]: --- Step: increment_build_number ---
INFO [2018-02-15 11:01:59.07]: ------------------------------------
Current version of project iOS-Core is: 
    31

/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1
INFO [2018-02-15 11:01:59.61]: $ cd /Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1 && agvtool next-version -all && cd -
INFO [2018-02-15 11:02:00.08]: ▸ Setting version of project iOS-Core to:
INFO [2018-02-15 11:02:00.08]: ▸ 32.
INFO [2018-02-15 11:02:00.14]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2018-02-15 11:02:00.22]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2018-02-15 11:02:00.26]: ▸ $(SRCROOT)/iOS-Core/client/Info-beta.plist
INFO [2018-02-15 11:02:00.27]: ▸ Cannot find "$(SRCROOT)/iOS-Core/client/Info-beta.plist"
INFO [2018-02-15 11:02:00.28]: ▸ $(SRCROOT)/iOS-Core/client/Info.plist
INFO [2018-02-15 11:02:00.28]: ▸ Cannot find "$(SRCROOT)/iOS-Core/client/Info.plist"
INFO [2018-02-15 11:02:00.34]: ▸ Updated CFBundleVersion in "iOS-Core.xcodeproj/../PlaygroundFramework/Info.plist" to 32
INFO [2018-02-15 11:02:00.37]: ▸ Updated CFBundleVersion in "iOS-Core.xcodeproj/../iOS-CoreTests/Info.plist" to 32
INFO [2018-02-15 11:02:00.39]: ▸ Updated CFBundleVersion in "iOS-Core.xcodeproj/../iOS-CoreUITests/Info.plist" to 32
INFO [2018-02-15 11:02:00.40]: ▸ /Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1
INFO [2018-02-15 11:02:00.88]: -------------------
INFO [2018-02-15 11:02:00.88]: --- Step: match ---
INFO [2018-02-15 11:02:00.88]: -------------------
INFO [2018-02-15 11:02:01.11]: Successfully loaded '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-LT-JOB1/fastlane/Matchfile' 📄

+-----------------------+--------------------------------------+
|         Detected Values from './fastlane/Matchfile'          |
+-----------------------+--------------------------------------+
| git_url               | git@github.com:ActiveWebsite/code_s  |
|                       | igning.git                           |
| git_branch            | Lyon                                 |
| clone_branch_directly | true                                 |
| type                  | enterprise                           |
| app_identifier        | ["com.activewebsite.lyon-beta"]      |
| username              | mobile@activewebsite.com             |
+-----------------------+--------------------------------------+

+-----------------------+--------------------------------------+
|                   Summary for match 2.81.0                   |
+-----------------------+--------------------------------------+
| git_url               | git@github.com:ActiveWebsite/code_s  |
|                       | igning.git                           |
| git_branch            | Lyon                                 |
| type                  | enterprise                           |
| app_identifier        | ["com.activewebsite.lyon-beta"]      |
| username              | mobile@activewebsite.com             |
| keychain_name         | login.keychain                       |
| keychain_password     | ********                             |
| readonly              | false                                |
| team_id               | E65YP8XL5R                           |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | true                                 |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

INFO [2018-02-15 11:02:01.15]: Cloning remote git repo...
INFO [2018-02-15 11:02:01.15]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:ActiveWebsite/code_signing.git' '/var/folders/8z/wmp1g63j0sn3c02b05wdc1mm0000gp/T/d20180215-21792-1vaprh9' -b Lyon --single-branch
INFO [2018-02-15 11:02:01.18]: ▸ Cloning into '/var/folders/8z/wmp1g63j0sn3c02b05wdc1mm0000gp/T/d20180215-21792-1vaprh9'...
INFO [2018-02-15 11:02:03.59]: ▸ remote: Counting objects: 35, done.
INFO [2018-02-15 11:02:03.63]: ▸ remote: Compressing objects: 100% (29/29), done.
INFO [2018-02-15 11:02:03.73]: ▸ remote: Total 35 (delta 8), reused 26 (delta 4), pack-reused 0
INFO [2018-02-15 11:02:03.73]: ▸ Receiving objects: 100% (35/35), 66.87 KiB | 769.00 KiB/s, done.
INFO [2018-02-15 11:02:03.73]: ▸ Resolving deltas: 100% (8/8), done.
INFO [2018-02-15 11:02:03.88]: $ git --no-pager branch --list origin/Lyon --no-color -r
INFO [2018-02-15 11:02:03.90]: ▸ origin/Lyon
INFO [2018-02-15 11:02:03.90]: Checking out branch Lyon...
INFO [2018-02-15 11:02:03.90]: $ git checkout Lyon
INFO [2018-02-15 11:02:03.91]: ▸ Already on 'Lyon'
INFO [2018-02-15 11:02:03.91]: ▸ Your branch is up-to-date with 'origin/Lyon'.
WARN [2018-02-15 11:02:03.92]: Migrating to new match...
WARN [2018-02-15 11:02:03.99]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-02-15 11:02:03.99]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-02-15 11:02:03.99]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-02-15 11:02:03.99]: Passphrase for Git Repo: 
 [2018-02-15 11:03:09.63]: Type passphrase again: 
INFO [2018-02-15 11:03:10.41]: Cloning remote git repo...
INFO [2018-02-15 11:03:10.41]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-02-15 11:03:10.41]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:ActiveWebsite/code_signing.git' '/var/folders/8z/wmp1g63j0sn3c02b05wdc1mm0000gp/T/d20180215-21792-1vwkzmz'
INFO [2018-02-15 11:03:10.43]: ▸ Cloning into '/var/folders/8z/wmp1g63j0sn3c02b05wdc1mm0000gp/T/d20180215-21792-1vwkzmz'...
INFO [2018-02-15 11:03:14.28]: ▸ remote: Counting objects: 58, done.
INFO [2018-02-15 11:03:14.32]: ▸ remote: Compressing objects: 100% (46/46), done.
INFO [2018-02-15 11:03:14.47]: ▸ remote: Total 58 (delta 11), reused 47 (delta 5), pack-reused 0
INFO [2018-02-15 11:03:14.47]: ▸ Receiving objects: 100% (58/58), 91.61 KiB | 621.00 KiB/s, done.
INFO [2018-02-15 11:03:14.48]: ▸ Resolving deltas: 100% (11/11), done.
INFO [2018-02-15 11:03:14.59]: $ git --no-pager branch --list origin/Lyon --no-color -r
INFO [2018-02-15 11:03:14.61]: ▸ origin/Lyon
INFO [2018-02-15 11:03:14.61]: Checking out branch Lyon...
INFO [2018-02-15 11:03:14.61]: $ git checkout Lyon
INFO [2018-02-15 11:03:14.63]: ▸ Branch Lyon set up to track remote branch Lyon from origin.
INFO [2018-02-15 11:03:14.63]: ▸ Switched to a new branch 'Lyon'
ERROR [2018-02-15 11:03:14.63]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/mobile/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:ActiveWebsite/code_signing.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303231353138303331305A00  "20180215180310Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303231353138303331305A00  "20180215180310Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:ActiveWebsite/code_signing.git"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2018-02-15 11:03:14.77]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-02-15 11:03:14.77]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-02-15 11:03:14.77]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-02-15 11:03:14.77]: Passphrase for Git Repo: 

</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.29.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["HIPCHAT_API_TOKEN"] = "XXXXXXXXX"
    #ENV["MATCH_PASSWORD"] = "XXXXXXXXXXX"
    ENV["GIT_CHECKOUT"] = sh("git rev-parse --short HEAD 2> /dev/null | sed 's/\(.*\)/\1/'")
    # cocoapods
  end


  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build Enterprise IPA"
  lane :enterprise do
    increment_build_number
    match()
    gym(workspace: "./iOS-Core.xcworkspace", scheme: "iOS-Core-beta", export_method: "enterprise", clean: true, export_xcargs: "-allowProvisioningUpdates")
    sh "./upload.sh"
    hipchat(
        version: "1",
        channel: "3838648",
        message: "A new version of Lyon is available on the FTP - @#{ENV['GIT_CHECKOUT']}" # "Mobile Build Room"
      )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    sigh(
      adhoc: false # otherwise sigh will produce an ad-hoc profile
    )
    gym(scheme: "iOS-Core-beta") # Build your app - more options available
    sh "./upload.sh"
    hipchat(
      version: "1",
      channel: "3838648",
      message: "A new version of Lyon is available on the FTP." # "Mobile Build Room"
    )
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    sigh(
      adhoc: false # otherwise sigh will produce an ad-hoc profile
    )
    snapshot
    gym(scheme: "iOS-Core") # Build your app - more options available
    deliver(force: true)
        hipchat(
      version: "1",
      channel: "3838648",
      message: "A new version of Lyon has been uploaded to iTunes Connect." # "Mobile Build Room"
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|
    hipchat(
      version: "1",
      channel: "3838648",
      custom_color: "red",
      message: "Lyon build failed - @#{ENV['GIT_CHECKOUT']}" # "Mobile Build Room"
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Enerprise Distribution Account
for_lane :enterprise do
	app_identifier "com.activewebsite.lyon-beta" # The bundle identifier of your app
	apple_id "mobile@activewebsite.com" # Your Apple email address
	team_id "E65YP8XL5R" # Developer Portal Team ID
end	
# App Store Production Account

  for_lane :release do
    app_identifier 'com.activewebsite.lyon' # The bundle identifier of your app
    apple_id 'mobile-accounts@activewebsite.com' # Your Apple email address
    team_id 'MZEH9D559Y' # Developer Portal Team ID
  end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.81.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-02-15**
</details>

</pre>
</details>

**Comment by emes** [comment]
If you need a quick fix :-)

gem "fastlane", '2.80.0'

**Comment by jwilson85** [comment]
So is this a bug introduced into .81?

**Comment by jwilson85** [comment]
Also 
Jeremys-MacBook-Pro-2:~ jeremywilson$ gem "fastlane", '2.80.0'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command fastlane,
Jeremys-MacBook-Pro-2:~ jeremywilson$

**Comment by daneov** [comment]
@jwilson85 `gem uninstall fastlane -v 2.81.0` and `gem install fastlane -v 2.80.0`.
If you have multiple versions, run it by: `fastlane _2.80.0_ <command>`

@emes is referring to a Gemfile :smile:

**Comment by jwilson85** [comment]
Do the files have to be encrypted? In the tutorial, it says that's optional.

**Comment by jwilson85** [comment]
Ok well without them being encrypted I'm still getting the password loop on 2.80.0

**Comment by jwilson85** [comment]
So what fixed it for me was.
I had followed the tutoril here : https://codesigning.guide/
It said to down load from the store and upload to my private git repo with the optional openssl 

So when I used fastlane nuke. It did that process for me. Now I am out of the password loop. It may have nothing to do with 80 or 81

**Comment by Cyberbeni** [comment]
@jwilson85 what is your `openssl version`?

**Comment by emes** [comment]
@Cyberbeni: LibreSSL 2.2.7, which I guess what comes with MacOS 10.13

**Comment by daneov** [comment]
Same here: 
<details><summary>ℹ️ fastlane environment </summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.14.3                                             |
| Installation Source         | ./bin/fastlane                                                 |
| Host                        | Mac OS X 10.13.3 (17D47)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

**Comment by emes** [comment]
@Cyberbeni

Just adding this to be more complete:

$ openssl version
LibreSSL 2.2.7

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.13.4                                                  |
| Ruby                        | 2.4.2                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.14.3 (Apple Git-98)                        |
| Installation Source         | ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.13.4 (17E160e)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 9.2                                                      |
