### ISSUE TITLE
Fastlane Swift + CVS

### ISSUE THREAD

**Issue by daneov** [fastlane/fastlane#11854]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm switching to Swift Fastlane, and have migrated most of my lanes so far.
However, I'm now a bit at a loss about what to do with the fastlane/swift folder.
Since Fastfile.swift and other relevant files reside under `fastlane/`, I feel like the other parts in `fastlane/swift` should be auto-generated at any time, but am looking for either a reason it shouldn't, or how to achieve this, since I think that part doesn't belong in my git history.

Could anyone point me in the right direction?

**Comment by joshdholtz** [comment]
@daneov Heyy 👋 The `fastlane/swift` folder is a copy of the Swift buildings (that are generated specifically for that version of fastlane). These Swift bindings are what allows you to write your `Fastfile.swift` but have it actually call the core of fastlane (which is written in Ruby). You shouldn't need to do anything with the content that are in the `fastlane/swift` directory - these are just needed for fastlane to do its thing 💪
