### ISSUE TITLE
create_keychain: lock_after_timeout doesn't work

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#11850]
```lock_after_timeout: false``` doesn't work until ```timeout: false``` is set.

```security set-keychain-settings -t 300 ~/Library/Keychains/fastlane.keychain-db```
is setting lock after timeout.

Workaround:
```timeout: false``` make
```security set-keychain-settings ~/Library/Keychains/fastlane.keychain-db```
to run, which doesn't lock keychain after timeout.

**Comment by joshdholtz** [comment]
@yakimant Hey 👋 `timeout` defaults to `300` so I think the actual solution here would be to not include `lock_after_timeout` at all and only include `timeout: false`.
```rb
create_keychain(
  name: "test-fastlane-keychain",
  password: "",
  timeout: false
)
```
There is shouldn't be a reason to specify `lock_after_timeout` if you are saying `timeout` is false 😇

Happy fastlaning 🚀
