### ISSUE TITLE
`match` doesn't re-create provisioning profiles when git repo is out of sync

### ISSUE THREAD

**Issue by ldiqual** [fastlane/fastlane#11866]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

TL;DR: if provisioning profiles on git are out of sync, match fails with no fallback.

We've been facing an issue regarding provisioning profile syncing between the Apple Dev Center and the match git repo. Here is what happens on our CI:

 1. Match finds an expired provisioning profile `A` on the dev center and creates a new provisioning profile `B`
 3. Match pushes the new provisioning profile `B` to the git repo. This times out for reasons that are out of match's control (bad network, slow CI, things like that). Now git has the old provisioning profile `A` and the Dev Center has the new one `B`.
 4. In a later run, match sees the old profile `A` on git and tries to find it on the Dev Center. However it is nowhere to be found because it was replaced earlier with `B`. Match exits with the following error:

```
[18:28:12]: Installing provisioning profile...
[18:28:13]: Provisioning profile 'A' is not available on the Developer Portal
[18:28:13]: for the user ios-dev@takescoop.com
[18:28:13]: Make sure to use the same user and team every time you run 'match' for this
[18:28:13]: Git repository. This might be caused by deleting the provisioning profile on the Dev Portal
```

This happens here: https://github.com/fastlane/fastlane/blob/master/match/lib/match/spaceship_ensure.rb#L61-L67

This means that if at any time match cannot push changes to github, you need to nuke your repo. In some cases – like for enterprise certificates – it is not supported out of the box so we have to manually remove files from git. Even if the nuke worked automatically it would invalidate certificates for apps that are already deployed internally (enterprise certs). Finally, even if nuking was ok, we'd still have to run the command manually and that's a no-no from the CI side.

I believe that match should have a better way to handle this scenario because anything that involves networks will fail eventually and there needs to be a proper fallback.

### Proposed fix

I believe a good way to handle this would be to create a new provisioning profile `C` if `A` is not found on the Dev Center, then sync it with github. Much like when match [detects an invalid profile](https://github.com/fastlane/fastlane/blob/master/match/lib/match/spaceship_ensure.rb#L73-L75).

I don't believe there are downsides to this, let me know if I'm missing anything. I'm happy to open a PR about this, would just love to have confirmation that this is the right way to go.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>N/A</pre>
</details>

### Environment

<details>
  <pre>N/A</pre>
</details>

**Comment by janpio** [comment]
Hey @ldiqual, did I understand correctly that you propose to change the default behaviour of `match` to automatically create a certificate the one being tried to use is not found? 

Could you maybe share how you are using `match` in your `Fastfile` for some context?

**Comment by ldiqual** [comment]
@janpio Thanks for following up on this!

My proposal is for `match` to automatically create a new *provisioning profile* (not certificates) when one being tried to use is not found. I think creating a new cert would be too risky especially in the case enterprise certs. My argument is that syncing with git can fail in many ways, which forces people to use `nuke` while there could be better fallbacks.

Here's how we use match in this case:

```
# ScoopQA
# No development cert because of https://github.com/fastlane/fastlane/issues/11038
["enterprise"].each { |type|
  match(
    type: type,
    team_id: "REDACTED",
    team_name: "Scoop Technologies, Inc",
    app_identifier: "REDACTED",
    git_branch: "enterprise"
  )
}
```

Matchfile:

```
force_for_new_devices true
git_url "REDACTED"
username "ios-dev@takescoop.com"
```

**Comment by triplef** [comment]
+1

We’ve run into this a couple times too. Alternatively (or additionally), a way to nuke/delete just provisioning profiles (all or specific ones) but not the certificates could also help in this case.
