### ISSUE TITLE
Can Fastlane verify assets and copy without uploading to ITC?

### ISSUE THREAD

**Issue by jvnike** [fastlane/fastlane#11865]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Apple supports validating and ITC Package before uploading assets with verify mode:
https://help.apple.com/itc/transporteruserguide/#/apdATD1E1222-D1E1A1303-D1E1222A1126

Is it possible to use Deliver to perform verification without uploading to ITC?

**Comment by janpio** [comment]
I don't see any option that would indicate such a feature for `deliver`: https://docs.fastlane.tools/actions/deliver/

By the way, I am not sure if `deliver` is actually using iTMSTransporter in the background. If it does, this should be quite simple to implement. If it does not, this will be quite a bit harder. Do you want to investigate in the code a bit?

**Comment by jvnike** [comment]
Hi @janpio, thanks for the tip. It does look like it is usin iTMSTransporter, when looking: fastlane_core/lib/fastlane_core/itunes_transporter.rb

The current value in itunes_transporter.rb: -m upload, but also allows -m verify to verify an .itmsp package. I'll keep looking into this further.

**Comment by janpio** [comment]
Yeah, we definitely _do_ have an interface for iTMSTransporter, you should look into what `deliver` actually uses under the hood. If this is it, it shouldn't be too hard to add e.g. a param to `deliver` that then influences what is called on the transporter.

**Comment by cpk1** [comment]
From what I can see Deliver uses spaceship to access iTC to upload images (and all the other store data) directly to iTC.
It doesn't look like there is anything currently to generate an xml that includes anything other than the *.ipa data in order to upload the *.ipa to iTC
I think there could be value in allowing the option to use iTMSTransporter to upload screenshots instead of accessing iTC directly which I feel is less likely to fail as often as uploading one by one to iTC. This is something I definitely would be interested in spending time looking at if the team has an interest in growing what it supports with iTMSTransporter.

**Comment by janpio** [comment]
(Pinged some people that might know more)

**Comment by KrauseFx** [comment]
_fastlane_ actually used to use the iTunes Transporter for all the metadata, including screenshots, however it caused a ton of problems for many of our users. For example, the iTunes Transporter caused issues on setups with firewalls, VPNs and proxies. We decided to re-implement everything using the iTunes Connect API, and things have been much more stable recently. There are currently no plans on going back to the transporter. We use the transporter just for the binary, as there is no other way.

**Comment by cpk1** [comment]
Thanks for the context, completely understandable with the iTMSTransporter woes!
Although it looks to use the same network requirements, in the future altool might be worth considering as a simpler alternative to iTMSTransporter that wont auto-update like Transporter does.

**Comment by janpio** [comment]
#2166 might be relevant ;)

**Comment by jvnike** [comment]
@KrauseFx @janpio @cpk1 thank you for your input. I am looking for a way to allow non developers access to manage and validate the screens and metadata without having to upload to a staged release in ITC. But what we have put together is a big step forward - the deliver download Jenkins jobs provide all copy and assets to each team in that nice structured format. Nice work to everyone who has contributed.

Once each team updates metadata and screens, they run the validate | upload Deliver job.

For Goole, I use Supply to pull down copy, and BitBucket to pull down the screens. The team makes the required updates and validates (thank you for the validate only flag!). 

When we do finally run the Google |  Supply upload job, upon success, we push the screens back to BitBucket, so the next download job contains the new accurate set.

Another option we have is to write our own validation steps to check screens and character counts, but then you wind up maintaining test that can drift from what Apple provides.
