### ISSUE TITLE
Gym fails by Code Signing Error: No profile for team 'xxxx' matching

### ISSUE THREAD

**Issue by jp928** [fastlane/fastlane#11864]
### Issue Description

Code Signing Error: No profile for team 'xxxx' matching

<details>
  <pre>Code Signing Error: No profile for team 'xxxx' matching</pre>
</details>

**Comment by janpio** [comment]
Hi @jp928, you should provide a bit more context. Does the profile actually exist? What is the `Fastfile` and lane that is throwing that error? Did you read what @fastlane-bot posted?

**Comment by uncleRX** [comment]
楼主解决了么?

**Comment by joshdholtz** [comment]
Closing this since there hasn't been any response 😊
