### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish which is my native language. I could translate any text whenever it is a thousand words or more I could translate the contributing documents, code_of_conduct, core_contributor and readme

### ISSUE THREAD

**Issue by LuigiBaute** [fastlane/fastlane#11871]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by minuscorp** [comment]
First of all, thank you for your collaboration offer. I'm not into adding localized versions of the documentation into the main repo, as it'd mean more maintenance and relying on translators to get all documents updated to the latest version. What do you guys think @janpio @revolter ?

**Comment by revolter** [comment]
Yeah, the biggest problem would be to keep them in sync, and I don't have too much knowledge of localizing documentations.

**Comment by minuscorp** [comment]
I think I'm going to close this for now. We appreciate the offer but the cons of doing this are too high to invest time on documentation translation. Thank you very much! 🚀
