### ISSUE TITLE
A way to access Appfile values from Fastfile?

### ISSUE THREAD

**Issue by zats** [fastlane/fastlane#1187]
Hi, I specify various team ids and bundle ids for different lanes in my Appfile (this is the way we handle different environments for the same app so we can run them side by side without overriding each other)

```
for_platform :ios do
	team_id 'xxxx'
	apple_id 'xxx@xxx.xx'

	for_lane :dev do
		app_identifier 'xxx.xx.xx'
	end

	for_lane :int do
		app_identifier 'zzz.zz.zz'
	end

	for_lane :appstore do
		team_id 'yyy.yy.yy'
		apple_id 'yay@yyy.yy'
		app_identifier 'www.ww.ww'
	end
end
```

In the Fastfile I'd like to access `team_id` to be able to specify it in various actions:
`gym(export_team_id:, codesigning_identity:)`, `resign(signing_identity:)` etc

I couldn't find it anywhere in documentation. Is there a public way to access those?

Thanks!

**Comment by KrauseFx** [comment]
Yeah, you can use

```ruby
CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
...
```

Where should this be added to the docs? `Advanced.md`?

**Comment by zats** [comment]
Great that's exactly what I'm looking for! 
I'd add it to `Appfile` maybe and link to it from `Advanced`? or vice versa…
Thanks!

**Comment by KrauseFx** [comment]
Very good idea, thanks @zats :+1:

**Comment by besi** [comment]
@KrauseFx Is it necessary to specify `team_id` and `apple_id` in the Fastfile? I do have it in my `Appfile` but when I run `fastlane beta` I still have to enter the apple_id three times. Plus I get asked for the bundle identifier which I ironically copy from the `Appfile` and paste it into the console.

**Comment by KrauseFx** [comment]
@besi Please submit a separate issue with your full Fastfile and Appfile.

**Comment by besi** [comment]
Sure thing #1201
