### ISSUE TITLE
Help incrementing version number

### ISSUE THREAD

**Issue by bmwertman** [fastlane/fastlane#11876]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is more of a question or perhaps an issue with the docs. I'm trying to set my fastfile up using the`increment_version_number` and `increment_build_number` actions.

`increment_build_number` is working as expected. But `increment_build_number` actually seemed to decrement the build number in a couple of instances and has failed to increment it at all. 

Based on the code below can someone confirm how `version_number` and `bump_type` should be passed to the key in the command line? Is it always expecting a string value whether passing `minor` or `0.3.0`? I think this may be the root of my problem. 

```
    if options[:bump_type]
      increment_version_number(
        version_number: options[:version_number],
        bump_type: options[:bump_type],
        xcodeproj: ios_project_path
      )
    end

    if options[:build_number]
      increment_build_number(
        build_number: options[:build_number],
        xcodeproj: ios_project_path
      )
    else
      increment_build_number(
        xcodeproj: ios_project_path
      )
    end
```

**Comment by minuscorp** [comment]
If you stablish a `:version_number` you're then overriding the `bump_type:` parameter, as it is the responsible of bumping the current version number to the next version number following the `semver` pattern.

**Comment by bmwertman** [comment]
I just updated the above code to this;

```
if options[:bump_type]
      increment_version_number(
        bump_type: options[:bump_type],
        xcodeproj: ios_project_path
      )
    elsif options[:version_number]
      increment_version_number(
        version_number: options[:version_number],
        xcodeproj: ios_project_path
      )
    end

    if options[:build_number]
      increment_build_number(
        build_number: options[:build_number],
        xcodeproj: ios_project_path
      )
    else
      increment_build_number(
        xcodeproj: ios_project_path
      )
    end
```

Now I'm seeing this error;

```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'cd /Users/Brad/Documents/apparent/platforms/ios && agvtool new-marketing-version ' was 2 instead of 0.
The new-marketing-version command requires a single argument to specify the new version.

agvtool - Apple-generic versioning tool for Xcode projects
  usage:
    agvtool help
    agvtool what-version | vers [-terse]
    agvtool [-noscm | -usecvs | -usesvn] next-version | bump [-all]
    agvtool [-noscm | -usecvs | -usesvn] new-version [-all] <versNum>
    agvtool [-noscm | -usecvs | -usesvn] tag [-force | -F] [-noupdatecheck | -Q] [-baseurlfortag]
    agvtool what-marketing-version | mvers [-terse | -terse1]
    agvtool [-noscm | -usecvs | -usesvn] new-marketing-version <versString>
```

**Comment by minuscorp** [comment]
Take a look [here](https://developer.apple.com/library/content/qa/qa1827/_index.html)

**Comment by bmwertman** [comment]
I actually gave that a look. My issue was fixed through a combination of breaking `version_number` and `bump_type` out into the `if` `elsif` condition and me passing the variable in the command line as `fastlane ios beta version_number:'0.3.0'` instead of `fastlane ios beta version_number: '0.3.0' with a space.
