### ISSUE TITLE
Spaceship in a thread-safe manner with Tunes Client

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#11884]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since we migrate to sidekiq, who is multi-thread. I am wondering how to use Spaceship Library in a threadSave for Tunes Clients

**Comment by bolom** [comment]
What is the equivalent of for Tunes?

`   Spaceship::Portal::App.set_client(client).all`

**Comment by taquitos** [comment]
Spaceship isn't currently thread-safe  😞 
It would be a large undertaking to make it so.

**Comment by bolom** [comment]
Ok :(
