### ISSUE TITLE
Automatically renew Enterprise Certificates and Provisioning Profiles

### ISSUE THREAD

**Issue by n1mda** [fastlane/fastlane#11886]
I distribute Enterprise applications and use match to manage code signing.
I would like a way to automatically renew both certificates and provisioning profiles to ensure that they never expire (which causes any distributed applications to stop working)

How can this be done, without nuking any existing valid certificate / profile?

**Comment by n1mda** [comment]
I'd be very interested to hear how someone else has solved this. Doesn't anyone else use enterprise distribution?

**Comment by joshdholtz** [comment]
@n1mda This can't be done without nuking. Only two distribution certs are allowed to be active at once and they will expire (you can't just renew them). You will have to nuke them at some point when they expire and create new ones. Provisioning profile can automatically get regenerated with `match` and `sigh` but we aren't so lucky with certs.

**Comment by joshdholtz** [comment]
BTW, I do a lot of enterprise distribution. I usually just end up nuking every year or so (whenever my certs expire) and recreate them 🙃

**Comment by n1mda** [comment]
@joshdholtz thank you for the response. But doesn’t nuking the certs mean that installed applications will stop working?

**Comment by joshdholtz** [comment]
@n1mda That is correct. The apps would have stopped working already though if the certs have expired. But I create a new cert and push new apps out before the the old cert expired so there is an overlap in certs and no downtime for my users 😊
