### ISSUE TITLE
Undefined method `in_app_purchases' for nil:NilClass

### ISSUE THREAD

**Issue by Cerebelus** [fastlane/fastlane#11883]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I have a problem with the part that is creating the IAP on iOS. Yesterday was working fine but now is getting errors. 

My implementation in Fastfile:
```
desc "Advanced: Create IAP Remove Ads."
lane :advanced_create_iap do
  fastlane_require ("spaceship")
  Spaceship::Tunes.login(nil, nil)
  app = Spaceship::Application.find(ENV["APP_BUNDLE_ID"])
  app.in_app_purchases.create!(
  type: Spaceship::Tunes::IAPType::NON_CONSUMABLE, 
  versions: {
    'en-US': {
      name: "NO ADS",
      description: "Remove the ads forever!"
    }
  },
  reference_name: "#{ENV['APP_BUNDLE_ID']}.removeads",
  product_id: "#{ENV['APP_BUNDLE_ID']}.removeads",
  cleared_for_sale: true,
  review_notes: " ",
  review_screenshot: "./iap_image.png", 
  pricing_intervals: 
    [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: 1
      }
    ] 
)
  end

```

<details>
  <pre>21:16:31]: --- Step: Verifying fastlane version ---
[21:16:31]: ----------------------------------------
[21:16:31]: Your fastlane version 2.81.0 matches the minimum requirement of 2.9.0  ✅
[21:16:31]: ------------------------------
[21:16:31]: --- Step: default_platform ---
[21:16:31]: ------------------------------
[21:16:31]: Driving the lane 'ios advanced_create_iap' 🚀
[21:16:34]: --------------------------
[21:16:34]: --- Step: notification ---
[21:16:34]: --------------------------
+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios advanced_create_iap |
+------------------+-------------------------+
[21:16:35]: undefined method `in_app_purchases' for nil:NilClass

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | notification               | 0           |
+------+----------------------------+-------------+

[21:16:35]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `in_app_purchases' for nil:NilClass
  Fastfile:133:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.81.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by minuscorp** [comment]
Hi! It seems that your app is not being found by `spaceship`, can you debug that the login is actually being performed and, if so, the bundle is present in your ITC portal?

**Comment by LUJYM** [comment]
@Cerebelus do u solve this problem? I have the same problem~~~

**Comment by Cerebelus** [comment]
Hello! No I didn't solved it. I suspect that is has something to do with my ruby/fastlane. If run 'which ruby' and 'which fastlane' I get '/usr/local/bin/ruby' and '/usr/local/bin/fastlane' instead of the RVM. Somehow I messed up the ruby/fastlane and I can't change back to RVM(I get some errors of some sort, I don't remember what was exactly).

**Comment by ming-chu** [comment]
I guess somethings wrong for action last_git_commit[.....], 
it works after I remove related actions in Fastfile
