### ISSUE TITLE
[question] Action to update xcconfig file

### ISSUE THREAD

**Issue by sovcharenko** [fastlane/fastlane#11892]
Hi,

Is there an action to update xcconfig file and change value of a specific key?

**Comment by sovcharenko** [comment]
I don't think there is.

Does it make sense to you to add such action to fastlane? i.e

update_xcconfig(file: 'Release.xcconfig', settings: {
  SETTING: 'value'
})

Use case: 
For those who manage their build settings via external xcconfig files it will be a handy tool.

**Comment by minuscorp** [comment]
So I think you can use an already well tested gem (which is included in _fastlane_) called [XCodeProj](https://github.com/CocoaPods/Xcodeproj)

**Comment by sovcharenko** [comment]
Sure, there are multiple ways of doing that. XCodeProj, simple text replace etc.

But Fastfile would be a bit cleaner if there was an action for that.

**Comment by minuscorp** [comment]
What API could _fastlane_ provide that `XCodeProj` doesn't?

**Comment by sovcharenko** [comment]
In terms of features, probably none. Well, except that this API could preserve formatting. But for me this doesn't look very important.

The point is that with XCodeProj it'll be 3 or 4 lines of code. Instead of simple one line action.

It's like [backup_file](https://docs.fastlane.tools/actions/backup_file/) and [restore_file](https://docs.fastlane.tools/actions/restore_file/) they do simple things but make Fastfile easy to read, compact and show the intent.

**Comment by minuscorp** [comment]
I think that could be nice to wrap in a plugin, as for now we're not accepting new actions 😄

**Comment by sovcharenko** [comment]
Sure, thanks. I'll do a plugin then.

**Comment by sovcharenko** [comment]
https://github.com/sovcharenko/fastlane-plugin-xcconfig
