### ISSUE TITLE
Is there anyway to modify fastfile dynamically ?

### ISSUE THREAD

**Issue by Mohab1** [fastlane/fastlane#1189]
I'm using Crashlytics and Slack integrations with Fastlane to automate builds, Is there anyway to modify fastfile to change messages in these action everytime I trigger build ?

**Comment by KrauseFx** [comment]
Sure, what do you want to change for example? The `Fastfile` is a Ruby file so you can run anything you want :+1:

**Comment by Remyoman** [comment]
@KrauseFx I have similar requests. For Crashlytics it would be nice to retrieve the list of email-adresses and the release notes from perhaps a file or aggregated from git commit messages. Having little experience in Ruby, how would one go about this?

**Comment by KrauseFx** [comment]
@Remyoman sorry, I'm not sure I understand, could you clarify on why and how you want to do this?

**Comment by Remyoman** [comment]
@KrauseFx To send out a Crashlytics build, email-addresses are usually provided with or without release notes. Would it be possible to retrieve these from a file and make them available to the Crashlytics fastlane action?

For example: I send out a new build to 3 users and I have their email-addresses in a file, besides that I also have some release notes in a file. I would like to pass the email-addresses and release notes to the Crashlytics action so I don;t have to perform this manually from Fabric.
Would I need a script or action that extracts the information into an ENV variable or does this require a sh script?

**Comment by Mohab1** [comment]
@KrauseFx @Remyoman  that's exactly what I mean my problem is that fastlane resides on server and everything is automated so I want a way developers can attach their release notes to crashlytics and slack without having to touch fastfile or expose it.
I'm thinking of text file attached to project directory and read its contents everytime I run fastlane embed release notes.

**Comment by vpolouchkine** [comment]
The `crashlytics` action can take a `notes_path` argument to points to the release notes.
