### ISSUE TITLE
Cannot get groups for multiple apps in same Spaceship session

### ISSUE THREAD

**Issue by chrisva** [fastlane/fastlane#11905]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm running commands directly in `Spaceship` to fetch the group for each app_id we have in `iTunes Connect`. We have 44 apps now and we do login once first:

`Spaceship::Tunes.login`

Then for each `app_identifier` in iTunes Connect we do the following commands to fetch groups:

- `app = Spaceship::Tunes::Application.find(app_identifier)`
- `external_group = Spaceship::TestFlight::Group.all(app_id: app.apple_id)`

The output from this call is fine for the 1st app:

```
[<Spaceship::TestFlight::Group
        id="5f486262-bb82-43ab-afb3-5838e85e029a",
        name="ITC.apps.tf.labels.internalTesters",
        is_default_external_group=false,
        is_internal_group=true,
        provider_id=369xxx,
        is_active=true,
        created="2017-05-28T02:05:28.266+0000",
        app_id=11xxxxxxxx>, <Spaceship::TestFlight::Group
        id="b413ffa1-77cd-47d2-9413-2bc1ccexxxxx",
        name="ITC.apps.tf.labels.CustomGroup1",
        is_default_external_group=true,
        is_internal_group=false,
        provider_id=369783,
        is_active=true,
        created="2017-05-28T02:05:28.273+0000",
        app_id=11xxxxxxxx>]
```

But when we do this again with a new app_identifier:

- `app = Spaceship::Tunes::Application.find(app_identifier2)`
- `external_group = Spaceship::TestFlight::Group.all(app_id: app.apple_id)`

*We get the exact same result.*

Looking at the source code for [test_flight/client.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/client.rb#L95), I can see that the function `get_groups(app_id: nil)` for getting groups does the following`return @cached_groups if @cached_groups`. And I cannot see any way to reset the cache. 

How can I get around this or reset the cache so I can get groups for more than one app in a Test Flight session?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>Too much sensitive data to share... </pre>
</details>

**Comment by taquitos** [comment]
No workaround, let me see if I can fix this real quick.

**Comment by chrisva** [comment]
Wonderful @taquitos! This fix is really helpful. Thank you. What is the frequency of fastlane releases?

**Comment by taquitos** [comment]
Generally one or two releases per week. We have a nightly gem you can use too if you'd like: https://docs.fastlane.tools/actions/update_fastlane/#parameters

**Comment by chrisva** [comment]
Wonderful. Thanks.
