### ISSUE TITLE
Incrementing and committing build version bump for target without .xcodeproj file?

### ISSUE THREAD

**Issue by IljaDaderko** [fastlane/fastlane#11904]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a project with 2 targets and one xcodde project file i.e. `myProj.xcodeproj` I created separate folder for my dev target that includes its own info.plist and am now having issues with following fastlane commands `increment_build_number` and `commit_version_bump`

It increments and commits just originaj info.plist under `myProj.xcodeproj` and I can't figure out a way to enable this for my dev info plist.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Not Needed</pre>
</details>

### Environment

<details>
  <pre>Not Needed</pre>
</details>

**Comment by taquitos** [comment]
unfortunately this action just calls out to `agvtool` which has it's own set of rules on how it will work: https://developer.apple.com/library/content/qa/qa1827/_index.html

**Comment by IljaDaderko** [comment]
Thank you for pointing in that direction, I'll look around to see if I can perhaps make one target inherit this field from another somehow
