### ISSUE TITLE
Troublesome dependency into a singleton client from model class initializer

### ISSUE THREAD

**Issue by sergiocampama** [fastlane/fastlane#11901]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Any model class (i.e. `Spaceship::Portal::App`) ultimately subclasses `Spaceship::Base`. The initializer for this base class references a [singleton client](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/base.rb#L228) object, which makes this using standalone client objects more cumbersome to use, by requesting to login just to initialize an instance of the object.

Paired with the fact that the PortalClient APIs use Portal:: model objects as inputs (but return hashes instead of instances of those classes) ensures that the singleton client must always be initialized and logged in, unless complete mocks of the model classes are used.

**Comment by sergiocampama** [comment]
Not a problem with running fastlane

**Comment by taquitos** [comment]
@sergiocampama yeah, singletons are not ideal here. We'd love to be able to refactor this stuff, but it feels like we'd need to really take our time with that. I agree with you though.

**Comment by sergiocampama** [comment]
still open
