### ISSUE TITLE
[Regression] ErbalT now requires 2 params

### ISSUE THREAD

**Issue by ctaintor** [fastlane/fastlane#11917]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

With #11144, `Fastlane:: ErbalT` now requires two params where it used to require one previously. The 2nd parameter should have a default. There is at least [one plugin](https://github.com/joshdholtz/fastlane-plugin-s3/blob/master/lib/fastlane/plugin/aws_s3/helper/aws_s3_helper.rb#L29) that breaks due to this change.

##### Complete output when running fastlane, including the stack trace and command used
```
/.../.rvm/gems/ruby-2.4.1/gems/fastlane-2.82.0/fastlane/lib/fastlane/erb_template_helper.rb:21:in `initialize': [!] wrong number of arguments (given 1, expected 2) (ArgumentError)
	from /.../.rvm/gems/ruby-2.4.1/bundler/gems/fastlane-plugin-s3-a85f598f1ab4/lib/fastlane/plugin/aws_s3/helper/aws_s3_helper.rb:29:in `new'
```

### Environment

**Comment by minuscorp** [comment]
Thank you @ctaintor for raising this so quickly! Already have a PR on this and I hope it'll get released as soon as possible.

**Comment by janpio** [comment]
And reviewed and merged. Thanks for the report @ctaintor, thanks for the PR @minuscorp. I think we can expect a release on Monday containing this change.
