### ISSUE TITLE
[Regression] upload_symbols_to_crashlytics Unable to find value for key GOOGLE_APP_ID in plist

### ISSUE THREAD

**Issue by johndelong** [fastlane/fastlane#11910]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Upon upgrading fastlane to 2.81.0 from 2.80.0, uploading dsym files fail with the following error:
`Shell command exited with exit status 13 instead of 0.`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>➜  ios git:(master) ✗ bundle exec fastlane refresh_dsyms --verbose
[✔] 🚀
Successfully loaded Appfile at path '/Users/johndelong/example/ios/fastlane/Appfile'
- app_identifier: 'com.example.app'
- apple_id: 'user@examlple.com'
-------
DEBUG [2018-02-23 11:08:00.55]: Checking if there are any plugins that should be loaded...
INFO [2018-02-23 11:08:00.91]: ---------------------------
INFO [2018-02-23 11:08:00.91]: --- Step: opt_out_usage ---
INFO [2018-02-23 11:08:00.91]: ---------------------------
INFO [2018-02-23 11:08:00.91]: Disabled upload of used actions
INFO [2018-02-23 11:08:00.95]: ------------------------------
INFO [2018-02-23 11:08:00.95]: --- Step: default_platform ---
INFO [2018-02-23 11:08:00.95]: ------------------------------
ERROR [2018-02-23 11:08:00.95]: ------------------------------------------------
ERROR [2018-02-23 11:08:00.95]: Name of the lane 'appstore' is already taken by the action named 'appstore'
ERROR [2018-02-23 11:08:00.95]: ------------------------------------------------
INFO [2018-02-23 11:08:00.95]: Driving the lane 'ios refresh_dsyms' 🚀
INFO [2018-02-23 11:08:00.99]: Skipping cocoapods repo update
INFO [2018-02-23 11:08:01.03]: ----------------------------
INFO [2018-02-23 11:08:01.03]: --- Step: download_dsyms ---
INFO [2018-02-23 11:08:01.03]: ----------------------------
INFO [2018-02-23 11:08:01.13]: Login to iTunes Connect (user@examlple.com)
Loading session from '/Users/johndelong/.fastlane/spaceship/user@examlple.com/cookie'
Looking for iTunes Connect Team with ID 685980
INFO [2018-02-23 11:08:03.93]: Login successful
INFO [2018-02-23 11:08:04.42]: Looking for dSYM files for com.example.app
DEBUG [2018-02-23 11:08:05.99]: Found train: 3.0.0, comparing to supplied version:
DEBUG [2018-02-23 11:08:06.87]: Found build version: 28, comparing to supplied build_number:
DEBUG [2018-02-23 11:08:06.88]: Build_version: 28 matches , grabbing dsym_url
DEBUG [2018-02-23 11:08:07.99]: dsym_url: http://iosapps.itunes.apple.com/apple-assets-us-std-000001/Purple118/v4/23/a8/5e/23a85e4c-f081-7a43-4788-6c74c4b56954/appDsyms.zip?accessKey=1519596487_384981703607010810_ScWIyBj13oLBqDlfsAB%2FzWyLQcr6vYYTyqQsl1CTU0P48zQKG7W2cfS%2FCMI7Ucf1UP5ao9rp1SeMTUzt21lbECiLmmIYMqVcA29yD0U3ncvpYYuo73BIp2Wwhs8odSmRZfU57tSBY7qFeWPb9TgV0QdwyrfYPRX0%2B2jZ4zSqFW457OLQ0h0PhWn3mixI
INFO [2018-02-23 11:08:08.45]: 🔑  Successfully downloaded dSYM file for 3.0.0 - 28 to 'com.example.app-3.0.0-28.dSYM.zip'
INFO [2018-02-23 11:08:08.49]: -------------------------------------------
INFO [2018-02-23 11:08:08.49]: --- Step: upload_symbols_to_crashlytics ---
INFO [2018-02-23 11:08:08.49]: -------------------------------------------
DEBUG [2018-02-23 11:08:08.55]: found an APIKey in ./exampleApp/Info.plist
ERROR [2018-02-23 11:08:08.55]: invalid byte sequence in UTF-8
ERROR [2018-02-23 11:08:08.58]: invalid byte sequence in UTF-8
INFO [2018-02-23 11:08:08.59]: Extracting '/Users/johndelong/example/ios/com.example.app-3.0.0-28.dSYM.zip'...
INFO [2018-02-23 11:08:08.59]: $ unzip -qo /Users/johndelong/example/ios/com.example.app-3.0.0-28.dSYM.zip
INFO [2018-02-23 11:08:08.73]: Uploading '2DDBFD5B-E14A-3C30-A5C4-F29FC033BD64.dSYM'...
DEBUG [2018-02-23 11:08:08.73]: upload_dsym using command: /Users/johndelong/example/ios/Pods/Fabric/upload-symbols -a dac9a807282526ab574099acd0e38cfd17b95dba -gsp /Users/johndelong/example/ios/exampleApp/Configuration/GoogleService-Info.plist -p ios /private/var/folders/gb/j686zk7d3nz7pyqnbjjldkfm0000gn/T/d20180223-6454-1sy3psl/2DDBFD5B-E14A-3C30-A5C4-F29FC033BD64.dSYM
ERROR [2018-02-23 11:08:08.80]: Shell command exited with exit status 13 instead of 0.</pre>
</details>

Executing the failing command from above provides the following error:
```
➜  ios git:(master) ✗ /Users/johndelong/example/ios/Pods/Fabric/upload-symbols -a dac9a807282526ab574099acd0e38cfd17b95dba -gsp /Users/johndelong/example/ios/exampleApp/Configuration/GoogleService-Info.plist -p ios /private/var/folders/gb/j686zk7d3nz7pyqnbjjldkfm0000gn/T/d20180223-6454-1sy3psl/2DDBFD5B-E14A-3C30-A5C4-F29FC033BD64.dSYM
error: Unable to find value for key GOOGLE_APP_ID in plist at path Optional("/Users/johndelong/example/ios/exampleApp/Configuration/GoogleService-Info.plist")
```

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13.3                                          |
| Ruby                        | 2.3.2                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.14.3 (Apple Git-98)                |
| Installation Source         | /usr/local/var/rbenv/versions/2.3.2/bin/fastlane |
| Host                        | Mac OS X 10.13.3 (17D47)                         |
| Ruby Lib Dir                | /usr/local/var/rbenv/versions/2.3.2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 9.2                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage

#update_fastlane

default_platform :ios

platform :ios do
    before_all do |lane|
        cocoapods(repo_update: false)
    end

    desc "Upload dSYM files to Crashlytics"
    lane :refresh_dsyms do
        download_dsyms
        upload_symbols_to_crashlytics(
           api_token: ENV['CRASHLYTICS_API_KEY']
        )
        clean_build_artifacts
    end

    after_all do |lane|
        # This block is called, only if the executed lane was successful
    end

    error do |lane, exception|
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.example.app"
apple_id "user@examlple.com"

for_lane :adhoc do
    app_identifier "com.example.app.debug"
end

for_lane :beta do
    app_identifier "com.example.app.beta"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.82.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.4.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.2        |
| molinillo                 | 0.6.4        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| cocoapods                 | 1.4.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-02-23**
</details></pre>
</details>

**Comment by taquitos** [comment]
Does it still work in 2.80.0?
I'm trying to track down whether Fabric made a change in their recent SDK to `upload_dsyms` because I don't recall anything changing in fastlane around this.

**Comment by johndelong** [comment]
Yes, I tried it this morning on 2.80.0 and it uploaded no problem. Both 2.81.0 and 2.82.0 do not work for me.

**Comment by taquitos** [comment]
Sadness. Thank you for the report 👍

**Comment by johndelong** [comment]
I have a hunch this is where the problem is coming from: https://github.com/fastlane/fastlane/commit/55428591ad1df48bb87e498ef80695bbf865040b

Looks like previously the `-gsp` argument was not supplied. And because our `GoogleService-Info.plist` structure looks like this, I bet the script cannot find the `GOOGLE_APP_ID` key in the dictionary.

![image](https://user-images.githubusercontent.com/4023203/36615458-541d4da4-18ae-11e8-8e54-c4d55f323cb2.png)

Does that seem possible?

**Comment by taquitos** [comment]
Yeah, so maybe `upload_dsyms` loads your `GoogleService-Info.plist` but only looks at the root.

**Comment by johndelong** [comment]
Yeah, that makes sense. So maybe this is a non-issue after all. We may just need to separate out configurations into separate `GoogleService-Info.plist` files. You can close this issue if you feel it is outside of fastlane's scope.

**Comment by taquitos** [comment]
Yup, just chatted with somebody from Crashlytics, that's exactly what you'll need to do 🚀
