### ISSUE TITLE
Code Signing Error: No profile for team 'xx' matching 'xx' found

### ISSUE THREAD

**Issue by HarrisHan** [fastlane/fastlane#11916]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./.fastlane/Fastfile`</summary>

```ruby
fastlane_require "uri"


d = DateTime.now
df = d.strftime("%Y_%m_%d_%H_%M_%S")

folder_name = ""
if ENV["IPA_TYPE"] == "01"
   folder_name = "/01测试包/"
   ENV["METHOD"] = "ad-hoc"
elsif ENV["IPA_TYPE"] == "02"
   folder_name = "/02预发布包/"
   ENV["METHOD"] = "ad-hoc"
elsif ENV["IPA_TYPE"] == "03"
   folder_name = "/03生产包/"
   ENV["METHOD"] = "app-store"
elsif ENV["IPA_TYPE"] == "04"
   folder_name = "/04企业版包/"
   ENV["METHOD"] = "enterprise"
   ENV["SIGH_PROFILE_ENTERPRISE"]="1"
end

version_folder = ENV["VERSION_FOLDER"]

svn_absolute_path = "/Users/kidswant/var/jenkins/var/jenkins/workspace/build/" + version_folder
file_name   = ENV["SCHEME"] + "_" + df.to_s

# SVN
ENV["SVN_DIR"]   = svn_absolute_path
ENV["OUT_DIR"]   = svn_absolute_path + folder_name + file_name
ENV["OUT_NAME"]  = file_name

ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"

# BUGLY
ENV["FL_UPLOAD_DSYM_TO_BUGLY_FILE_NAME"] = file_name + ".app.dSYM.zip"
ENV["FL_UPLOAD_DSYM_TO_BUGLY_FILE"] = svn_absolute_path + folder_name + file_name + "/" + file_name + ".app.dSYM.zip"


fastlane_version "2.60.1"

default_platform :ios

platform :ios do

  before_all do

  end

  lane :fire do

      unless Dir.exists?(ENV["SVN_DIR"])
        repo_path = URI.escape(ENV["REPO_PATH"])
        sh "svn mkdir #{repo_path} -m 'mkdir'"
        sh "svn checkout #{repo_path} #{ENV["SVN_DIR"]}"
      end
      clear_derived_data
      cert
      unless ENV["IPA_TYPE"] != "03"
        sigh(
          force: true,
          filename: "#{ENV["METHOD"]}_#{ENV["SCHEME"]}" + ".mobileprovision")
      else
        sigh(
         adhoc: true,
         force: true,
         filename: "#{ENV["METHOD"]}_#{ENV["SCHEME"]}" + ".mobileprovision")
      end
    gym
  end

  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    # gym(scheme: "HaiziwangTemai") # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    sh "bash ./svn_commit.sh"

    upload_dsym_to_bugly(
       app_key: $FL_UPLOAD_DSYM_TO_BUGLY_APP_KEY,
        app_id: $FL_UPLOAD_DSYM_TO_BUGLY_APP_ID,
     bundle_id: $FL_UPLOAD_DSYM_TO_BUGLY_BUNDLE_ID,
       version: $FL_UPLOAD_DSYM_TO_BUGLY_VERSION,
     file_name: $FL_UPLOAD_DSYM_TO_BUGLY_FILE_NAME,
          file: $FL_UPLOAD_DSYM_TO_BUGLY_FILE
    )
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    # publish_to_firim(
    #  file:  $FL_PUBLISH_TO_FIRIM_IPA_FILE,
    #  token: $FIR_IM_TOKEN
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

```
</details>

<details><summary>`./.fastlane/Appfile`</summary>

```ruby
app_identifier ENV["BUNDLE_ID"] # The bundle identifier of your app
apple_id ENV["APPLE_ID"]  # Your Apple email address
team_id ENV["TEAM_ID"]  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.60.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-02-24**
</details>

**Comment by HarrisHan** [comment]
![image](https://user-images.githubusercontent.com/15394437/36632056-2aa19c50-19bc-11e8-8482-8eccd7ad483b.png)

I don't want to choose the right profile manually and want to  make the xcode to find the profile automatically, How can I do that?

**Comment by CoderHRXu** [comment]
你这是provising profile不正确啊，要么手动从开发者网站创建下载安装，要么你用fastlane的match，来自动匹配。

**Comment by HarrisHan** [comment]
@CoderHRXu 谢谢你的回复，我目前用的cert 和 sigh来维护证书和描述文件，确保他们的可靠性，gym 里面profile map 我刚开始认为他会去找这个描述文件，后来发现并不是，我尝试过用xcargs 指定PROVISIONING_PROFILE_SPECIFIER 和TEAM 却还是不能达到自动匹配的目的，所以说只能match了？

**Comment by CoderHRXu** [comment]
@HarrisHan 1.首先你的pp文件（provising profile）要是正确的，而且在工程里面指定好。 2.gym里面profile map就是为了给fastlane去找对应bundleid的pp文件，是会主动找的。这个键值对value就是pp文件的文件名。 经过我个人使用总结来看，建议使用match来自动生成pp文件，确保正确性。

**Comment by HarrisHan** [comment]
@CoderHRXu 我打算后面试试match,其实我的一个疑问就是如果工程里面不指定好pp文件，fastlane如何寻找正确的pp文件并使用它来签名，gym的profile map 做不到，match还没试过

**Comment by CoderHRXu** [comment]
@HarrisHan就算你不制定好pp文件， fastlane还是会通过gym的profile map来找，就会搜你电脑的~/Library/MobileDevice/Provisioning Profiles 这个文件夹里面，如果匹配到就会使用。

**Comment by HarrisHan** [comment]
@CoderHRXu 我还真测试过。。结果也是令我失望的，我把pp文件(确保其实正确的)，也确保其在~/Library/MobileDevice/Provisioning Profiles是存在的。gym的profile map也指定了。。依然不会自动去使用，当然当时测试的场景可能是Xcode 指定了一个错误的profile，None测试也不行

**Comment by uncleRX** [comment]
遇到同样的问题～ 请问最后匹配上 profile 没？ 我的文件在本地是存在的，指定文件依旧匹配不上

**Comment by HarrisHan** [comment]
@uncleRX 暂时手动指定
