### ISSUE TITLE
error

### ISSUE THREAD

**Issue by renzifeng** [fastlane/fastlane#11928]
ERROR [2018-02-26 09:42:35.62]: fastlane finished with errors
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane_core/lib/fastlane_core/ui/interface.rb:155:in `build_failure!': [!] Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane_core/lib/fastlane_core/ui/ui.rb:16:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/gym/lib/gym/runner.rb:121:in `block in package_app'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane_core/lib/fastlane_core/command_executor.rb:93:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/gym/lib/gym/runner.rb:117:in `package_app'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/gym/lib/gym/runner.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/gym/lib/gym/manager.rb:19:in `work'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/actions/build_ios_app.rb:64:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:230:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:230:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:11:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.82.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by KrauseFx** [comment]
Please share the complete output
