### ISSUE TITLE
Issue with fastlane after re-installing CocaoPods

### ISSUE THREAD

**Issue by jpghelfi** [fastlane/fastlane#11934]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If a run in  root
<details>
  <pre>fastlane -v
Could not find proper version of fastlane (2.81.0) in any of the sources
Run `bundle install` to install missing gems.</pre>
</details>

I did 'bundle install' and here is the output
<details>
  <pre>An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.</details></pre>

so, i did 'gem install json -v '1.8.3' and the output is

<details>
  <pre>
➜  TTCheck git:(development) ✗ gem install json -v '1.8.3'
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2/gems/json-1.8.3/ext/json/ext/generator
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/bin/ruby -r ./siteconf20180226-48193-187g9we.rb extconf.rb
creating Makefile

current directory: /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {
                        ^
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2151:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2324:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2209:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2175:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2170:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2166:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2151:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2324:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2209:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2175:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2171:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2166:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2151:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2324:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2209:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2176:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2170:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2166:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2151:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2324:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2209:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2175:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2170:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2166:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2151:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2324:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2209:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2175:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2170:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2166:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2151:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2324:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2209:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2175:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2170:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:2166:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings and 2 errors generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2/gems/json-1.8.3 for inspection.
Results logged to /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2/extensions/x86_64-darwin-16/2.4.0/json-1.8.3/gem_make.out
</details>
  </pre>

but if I run in my xcode proyect, where I had fastlane previously installed

<details>
  <pre>fastlane -v
fastlane installation at path:
/Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.83.0/bin/fastlane
-----------------------------
[⠋] 🚀 /Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
/Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: previous definition of VERSION was here
[⠦] 🚀 /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.83.0/spaceship/lib/spaceship/test_flight/build.rb:89: warning: already initialized constant Spaceship::TestFlight::Build::BUILD_STATES
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.83.0/spaceship/lib/spaceship/test_flight/build.rb:89: warning: previous definition of BUILD_STATES was here
[✔] 🚀 
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.83.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: already initialized constant CredentialsManager::AccountManager::DEFAULT_PREFIX
/Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.83.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: previous definition of DEFAULT_PREFIX was here
fastlane 2.83.0</pre>
</details>

### Environment

<details>
  <pre>[⠋] 🚀 /Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
/Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: previous definition of VERSION was here
[⠦] 🚀 /Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.83.0/spaceship/lib/spaceship/test_flight/build.rb:89: warning: already initialized constant Spaceship::TestFlight::Build::BUILD_STATES
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.83.0/spaceship/lib/spaceship/test_flight/build.rb:89: warning: previous definition of BUILD_STATES was here
[✔] 🚀 
[21:15:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
/Users/juanpabloghelfi/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.83.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: already initialized constant CredentialsManager::AccountManager::DEFAULT_PREFIX
/Users/juanpabloghelfi/.rvm/gems/ruby-2.4.2@global/gems/fastlane-2.83.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: previous definition of DEFAULT_PREFIX was here
[21:15:46]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.6                                       |
| Ruby                        | 2.4.2                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.14.3 (Apple Git-98)             |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                      |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                  |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                    |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode92.app/Contents/Developer/ |
| Xcode Version               | 9.2                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.83.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.5        |
| CFPropertyList            | 2.3.6        |
</details>

*generated on:* **2018-02-26**
</details>
[21:15:46]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[21:15:46]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)</pre>
</details>

I dont´t get what happened. This was fucked when I tried to 'pod install' something... and uninstalled ruby and installed it again.

**Comment by jpghelfi** [comment]
reinstalled everything and worked!

**Comment by KrauseFx** [comment]
Glad to hear 👍

**Comment by jpghelfi** [comment]
sorry to reopen this issue.. but where I can propose new functionalities to fastlane. Is there a forum o something like similar ? thanks

**Comment by KrauseFx** [comment]
GitHub issues are fine :)

**Comment by KrauseFx** [comment]
A new one please

**Comment by jpghelfi** [comment]
thanks! https://github.com/fastlane/fastlane/issues/11954
