### ISSUE TITLE
Running Fastlane from Xcode's run script phase

### ISSUE THREAD

**Issue by AnandKumar9** [fastlane/fastlane#11943]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Ok, so a [previously reported issue](https://github.com/fastlane/fastlane/issues/9029) is pretty similar to this one, except that I am running Xcode locally instead of through a build server. I have got Fastlane installed, can run a lane belonging to my Xcode project from command line but if I try to run it by including it in a run-phase script and doing a Cmd+R (i.e. Run) on Xcode, it fails with below error message.
`fastlane: command not found`

This is what the run-phase script  looks like - 
```
export PATH="/Users/myusername/.rvm/gems/ruby-2.4.1/bin/fastlane"
fastlane custom_lane
```

Doing a `which fastlane` does give the same path I inserted above.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.79.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| tty-screen                | 0.6.4        |
| openssl                   | 2.0.3        |
| excon                     | 0.60.0       |
| CFPropertyList            | 2.3.6        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| plist                     | 3.4.0        |
| faraday                   | 0.14.0       |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
</details>

*generated on:* **2018-02-27**
</details></pre>
</details>

**Comment by Cyberbeni** [comment]
Try `sh -c "fastlane custom_lane"`

**Comment by joshdholtz** [comment]
@AnandKumar9 Your PATH is pointing directly at the executable but I think it needs to point to the `bin ` directory. Can you try something like... 
```
export PATH="/Users/myusername/.rvm/gems/ruby-2.4.1/bin:$PATH"
```

**Comment by Cyberbeni** [comment]
Just use the full path to the executable then instead of adding it to PATH and then only using the name.
`~/.rvm/gems/ruby-2.4.1/bin/fastlane custom_lane`
