### ISSUE TITLE
Regression: upload_symbols_to_crashlytics doesn't work anymore without specifying the api key

### ISSUE THREAD

**Issue by mbalex** [fastlane/fastlane#11948]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

A change to upload_symbols_to_crashlytics (see [here](https://github.com/fastlane/fastlane/commit/55428591ad1df48bb87e498ef80695bbf865040b#diff-2eec78d70c41940712d3172fc80d1898R13) ) makes it need an api key. Before that change upload_symbols_to_crashlytics was working fine without supplying such an api key.

Also the doc example still shows the usage without supplying the api key.

Error message:
<pre>[14:43:36]: Either Fabric API key or path to Firebase Crashlytics GoogleService-Info.plist must be given.</pre>

**Comment by janpio** [comment]
Hey @mbalex, I added "Regression" to the title of this issue so it gets the proper attention as it broke something that worked before.

Also, @jonasrottmann do you mabye want to take a look as your commit seems to have added that new requirement?

**Comment by mbalex** [comment]
I take this bug report back, it works after our weekly gem update and mac reboot.
