### ISSUE TITLE
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics

### ISSUE THREAD

**Issue by kas84** [fastlane/fastlane#11957]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am getting this error since yesterday after Apple's scheduled maintenance.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[12:41:45]: Going to upload updated app to iTunes Connect
[12:41:45]: This might take a few minutes. Please don't interrupt the script.
[12:44:40]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[12:44:40]: Transporter transfer failed.
[12:44:40]: 
[12:44:40]: Could not start delivery: all transports failed diagnostics
[12:44:41]: [iTMSTransporter] [2018-03-01 12:44:40 CET] <Automatic reconnector> DEBUG: Transfer warning: Scheduling automatic restart in 1 minute

[12:44:41]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$2.run(TransferEngine.java:593)

[12:44:41]: [iTMSTransporter] 

[12:44:41]: [iTMSTransporter] [2018-03-01 12:44:40 CET] <Automatic reconnector> DEBUG: Received failed transfer notification; aborting

[12:44:41]: [iTMSTransporter] [2018-03-01 12:44:40 CET] <Automatic reconnector>  INFO: Scheduling automatic restart in 1 minute

[12:44:41]: [iTMSTransporter] [2018-03-01 12:44:40 CET] <main> ERROR: Could not start delivery: all transports failed diagnostics

[12:44:41]: [iTMSTransporter] 

[12:44:41]: [iTMSTransporter] 

[12:44:41]: [iTMSTransporter] 

[12:44:41]: [iTMSTransporter] Package Summary:

[12:44:41]: [iTMSTransporter]  

[12:44:41]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[12:44:41]: [iTMSTransporter] 	/var/folders/x1/cw1_hqvx1vj8b2jzhwfj204m0000gn/T/d20180301-2088-13udshd/1171144340.itmsp - Error Messages:

[12:44:41]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics

[12:44:41]: [iTMSTransporter] [2018-03-01 12:44:40 CET] <main> DBG-X: Returning 1

[12:44:41]: iTunes Transporter output above ^
[12:44:41]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.2"

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    before_all do
      update_fastlane()
    end
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(git_url:"git@bitbucket.org:zoiber/ios_certs.git", type: "appstore") # more information: https://codesigning.guide
    #gym --verbose # Build your app - more options available
    #cert
    sigh


    # not needed anymore since we increase the build number with a cordova hook
    #increment_build_number(xcodeproj: 'platforms/ios/Tramitapp.xcodeproj')
    gym(
      scheme: "TramitApp",
      clean: true,
      include_bitcode: false,
      #use_legacy_build_api: false,
      output_directory: "./",
      workspace:'./platforms/ios/TramitApp.xcworkspace',
      output_name: "TramitApp.ipa",
      #xcargs: "ARCHIVE=YES", # Used to tell the Fabric run script to upload dSYM file
      export_xcargs:"-allowProvisioningUpdates"
    )
    pilot(
      skip_waiting_for_build_processing:true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    deliver(
      skip_screenshots:true
    )

    gym(
      scheme: "TramitApp",
      clean: true,
      include_bitcode: false,
      use_legacy_build_api: false,
      output_directory: "./",
      workspace:'./platforms/ios/TramitApp.xcworkspace',
      output_name: "TramitApp.ipa",
      export_method: "app-store",
      #xcargs: "ARCHIVE=YES",
      export_xcargs:"-allowProvisioningUpdates" # Used to tell the Fabric run script to upload dSYM file
    )
    appstore
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform:android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    @project_path = File.expand_path('../../platforms/android', __FILE__).shellescape
    @fastlane_path = File.expand_path('../../fastlane', __FILE__).shellescape

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Playstore"

  lane :beta do
    gradle(
      gradle_path: "#{@project_path}/gradlew",
      project_dir: "#{@project_path}",
      task: 'assemble',
      build_type: 'Release'
    )

    supply(
      json_key:"#{@fastlane_path}/android_developer_api.json",
      package_name:"com.tramitapp.employee",
      apk_paths:["#{@project_path}/build/outputs/apk/release/android-release.apk"],
      track: 'beta'
    )
  end

  # You can define as many lanes as you want

  lane :playstore do

    gradle(
      gradle_path: "#{@project_path}/gradlew",
      project_dir: "#{@project_path}",
      task: 'assemble',
      build_type: 'Release'
    )

    supply(
      json_key:"#{@fastlane_path}/android_developer_api.json",
      package_name:"com.tramitapp.employee",
      apk_paths:["#{@project_path}/build/outputs/apk/release/android-release.apk"]
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.tramitapp.employee" # The bundle identifier of your app
apple_id "manuel.santillan@tramitapp.com" # Your Apple email address

team_id "99G27EM9A7"  # Developer Portal Team ID
json_key_file "./android_developer_api.json"
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.83.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 2.3.2        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.3        |
| tty-screen                | 0.6.2        |
| tty-screen                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| tty-spinner               | 0.7.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.2        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-03-01**
</details></pre>
</details>

**Comment by kas84** [comment]
Fixed it with:

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

in my Fastfile

**Comment by singletondejan** [comment]
Thanks @kas84 !

**Comment by hlian** [comment]
@kas84 thanks! how the heck did you figure that out?

**Comment by KrauseFx** [comment]
Moving all further discussion to https://github.com/fastlane/fastlane/issues/11958
