### ISSUE TITLE
[enhancement] Read path to derived data folder from xcode settings in clear_derived_data action

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#11951]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Right now, action code [defaults](https://github.com/fastlane/fastlane/blob/d0998ae7acd3e8ed165186d55547a9d7e69abefd/fastlane/lib/fastlane/actions/clear_derived_data.rb#L28) to `~/Library/Developer/Xcode/DerivedData`.
It would be great, if it could check if a custom path specified in xcode settings (`~/Library/Preferences/com.apple.dt.Xcode.plist`, key `IDECustomDerivedDataLocation`) and, if any, default to it instead.
I know there is a `derived_data_path` key I can specify manually, but hey, it's fastlane, right?

**Comment by KrauseFx** [comment]
Great idea, _fastlane_ already does that for the `custom_archive_path` with https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/detect_values.rb#L53, so it should be rather easy to add for `derived_data_path` 👍

**Comment by Sega-Zero** [comment]
@KrauseFx any ETA on this?
