### ISSUE TITLE
I get the error "Shell command exited with exit status 48 instead of 0" when running beta lane for iOS application.

### ISSUE THREAD

**Issue by nabhak25** [fastlane/fastlane#11956]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
Shell command exited with exit status 48 instead of 0 error occurs when running create_keychain() method.

The shell returns error code and no description. Hence I am unable to understand what is the issue.

Please help.

Command used and output:
bundle exec fastlane beta
[✔] 🚀 
[17:40:01]: -----------------------------
[17:40:01]: --- Step: update_fastlane ---
[17:40:01]: -----------------------------
[17:40:01]: Looking for updates for fastlane...
[17:40:06]: Updating fastlane from 2.83.0 to nightly build 2.84.0.beta.20180301050048... (last official release 2.83.0) 🚀
[17:40:45]: Finished updating fastlane
[17:40:45]: Cleaning up old versions...
[17:40:45]: Thanks for using fastlane's nightly builds! This makes it easier for everyone to detect regressions earlier.
[17:40:45]: Please submit an issue on GitHub if anything behaves differently than it should 🍪
[17:40:45]: fastlane.tools successfully updated! I will now restart myself... 😴
[✔] 🚀 
[17:40:46]: -----------------------------
[17:40:46]: --- Step: update_fastlane ---
[17:40:46]: -----------------------------
[17:40:46]: ------------------------------
[17:40:46]: --- Step: default_platform ---
[17:40:46]: ------------------------------
[17:40:46]: Driving the lane 'ios beta' 🚀
[17:40:46]: ------------------------------
[17:40:46]: --- Step: get_certificates ---
[17:40:46]: ------------------------------

+---------------+-------------------------------------------------+
|                     Summary for cert 2.83.0                     |
+---------------+-------------------------------------------------+
| development   | false                                           |
| force         | false                                           |
| username      | user@example.com                       |
| team_id       |  team_id                                   |
| keychain_path | keychain_path |
| platform      | ios                                             |
+---------------+-------------------------------------------------+

[17:40:47]: Starting login with user 'user@example.com'
[17:40:53]: Successfully logged in
[17:40:59]: Found the certificate XXX (iOS Distribution) which is installed on the local machine. Using this one.
[17:40:59]: Verifying the certificate is properly installed locally...
[17:40:59]: Successfully installed certificate XXX
[17:40:59]: Use signing certificate 'XXX' from now on!
[17:40:59]: --------------------------------------
[17:40:59]: --- Step: get_provisioning_profile ---
[17:40:59]: --------------------------------------

+-------------------------------------+---------------------------------+
|                        Summary for sigh 2.83.0                        |
+-------------------------------------+---------------------------------+
| adhoc                               | false                           |
| development                         | false                           |
| skip_install                        | false                           |
| force                               | false                           |
| app_identifier                      | com.example.app |
| username                            | user@example.com       |
| team_id                             | team_id                      |
| ignore_profiles_with_different_name | false                           |
| cert_id                             | XXX                     |
| skip_fetch_profiles                 | false                           |
| skip_certificate_verification       | false                           |
| platform                            | ios                             |
| readonly                            | false                           |
+-------------------------------------+---------------------------------+

[17:40:59]: Starting login with user 'user@example.com'
[17:41:04]: Successfully logged in
[17:41:04]: Fetching profiles...
[17:41:06]: Provisioning Profile XXX is not valid, skipping this one...
[17:41:06]: Provisioning Profile XXX  is not valid, skipping this one...
[17:41:06]: Provisioning Profile XXX is not valid, skipping this one...
[17:41:06]: Provisioning Profile XXX is not valid, skipping this one...
[17:41:06]: Provisioning Profile XXXis not valid, skipping this one...
[17:41:06]: Provisioning Profile XXX is not valid, skipping this one...
[17:41:06]: Provisioning Profile XXX is not valid, skipping this one...
[17:41:06]: Provisioning Profile XXX is not valid, skipping this one...
[17:41:09]: Verifying certificates...
[17:41:13]: Found 2 matching profile(s)
[17:41:13]: Downloading provisioning profile...
[17:41:14]: Successfully downloaded provisioning profile...
[17:41:14]: Installing provisioning profile...
.../..../mobileprovision
[17:41:14]: Setting Provisioning Profile type to 'app-store'
[17:41:14]: -----------------------------
[17:41:14]: --- Step: create_keychain ---
[17:41:14]: -----------------------------
+---------------------+--------------------------------------------------------+
|                                 Lane Context                                 |
+---------------------+--------------------------------------------------------+
| DEFAULT_PLATFORM    | ios                                                    |
| PLATFORM_NAME       | ios                                                    |
| LANE_NAME           | ios beta                                               |
| CERT_FILE_PATH      | .../.../XXX.cer                                             |
| CERT_CERTIFICATE_ID | XXX                                             |
| SIGH_PROFILE_PATH   | .../..../mobileprovision   |
| SIGH_PROFILE_PATHS  | [".../..../mobileprovision  |
|                     | "]                                                     |
| SIGH_UDID           | UUID                  |
| SIGH_UUID           | UUID                 |
| SIGH_NAME           | match XXX         |
| SIGH_PROFILE_TYPE   | app-store                                              |
+---------------------+--------------------------------------------------------+
[17:41:16]: **Shell command exited with exit status 48 instead of 0.**

+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 1    | update_fastlane          | 0           |
| 2    | default_platform         | 0           |
| 3    | get_certificates         | 12          |
| 4    | get_provisioning_profile | 15          |
| 💥   | create_keychain          | 0           |
+------+--------------------------+-------------+

[17:41:16]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Colour codes included in slack message
    https://github.com/fastlane/fastlane/issues/48 [closed] 5 💬
    22 Sep 2016

➡️  upload_symbols_to_crashlytics is reporting success, but Fabric is reporting missing dSYMs
    https://github.com/fastlane/fastlane/issues/8053 [open] 21 💬
    2 weeks ago

➡️  Jenkins Fastlane Match - Code Signing Error: Signing certificate is invalid. Signing certificate "xxx", serial number "xxx is not valid for code signing. It may have been revoked or expired.
    https://github.com/fastlane/fastlane/issues/11855 [open] 6 💬
    2 weeks ago

and 15 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%2048%20instead%20of%200.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `shell_error!': [!] Shell command exited with exit status 48 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane_core/lib/fastlane_core/ui/ui.rb:16:in `method_missing'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/actions/create_keychain.rb:25:in `run'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:53:in `import_certificates'
	from Fastfile:25:in `block (2 levels) in parsing_binding'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/test/.rvm/gems/ruby-2.4.1/gems/fastlane-2.83.0/bin/fastlane:20:in `<top (required)>'
	from /Users/test/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/test/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane(nightly: true)

default_platform(:ios)

platform :ios do

before_all do
    ENV['KEYCHAIN_NAME'] = "abc.keychain"
    ENV['KEYCHAIN_PASSWORD'] = "password"
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    import_certificates
    sync_code_signing(type: "appstore")
    build_app(project: "example.xcodeproj", scheme: "example")
    upload_to_testflight
  end
  
  desc "Version number of IPA"
  lane :print do
    get_version_number(
    xcodeproj: "example.xcodeproj", scheme: "example"
    )
  end
  
  desc "Upload app to iTunes Connect"
  lane :release do
    #get_certificates
    #get_provisioning_profile
    get_push_certificate
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(project: "example.xcodeproj", scheme: "example")
    #upload_to_app_store                  # upload your app to iTunes Connect
    deliver(
        automatic_release: false            # deafult is false; however for safety purposes
    )
  end
  
  def import_certificates

    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: false,
      unlock: true,
      timeout: 6400,
      #lock_when_sleeps: false,
      password: ENV["KEYCHAIN_PASSWORD"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/Certificates.p12",
      certificate_password: ENV['CERT_PASSWORD'],
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/XXX.cer",
      keychain_name: ENV["KEYCHAIN_NAME"]
    )
  end
  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "app_identifier" # The bundle identifier of your app
apple_id "user@example.com" # Your Apple email address

itc_team_id "12345" # iTunes Connect Team ID
team_id "XXX" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.83.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-03-01**
</details>
</pre>
</details>

**Comment by janpio** [comment]
Could you please run the same lane again with `--verbose` added at the end and post the output again? Thanks.

**Comment by nabhak25** [comment]
Ran it with --verbose. The output is same.

**Comment by mamaz** [comment]
In my case, there's a keychain with the same name with the keychain that wants to be created.
deleting the keychain in ~/Library/Keychain helps.

**Comment by nabhak25** [comment]
Hi ,

Seems like the error is resolved. I have kept the beta lane as simple as shown below with no extra importing of certificates and it works now. Thank you for all the help!

**Code snippet:**

desc "Push Beta to Testflight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(project: "abc.xcodeproj", scheme: "abc")
    upload_to_testflight
  end
