### ISSUE TITLE
Spaceship Logout Method?

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#11955]
I am wondering how to force Spaceship to reconnect/logout, in this scenario we use the same apple id but with a wrong password we are able to get the info.

```
Spaceship::Tunes.login(username, GOOD_PASSWORD)
client_tunes.teams.size ( OK)

Spaceship::Tunes.login(username, wRONG_PASSWORD)
client_tunes.teams.size ( OK)
```

**Comment by KrauseFx** [comment]
Sorry, there is nothing built in for this

**Comment by bolom** [comment]
Ok :(

Le jeu. 1 mars 2018 à 17:13, Felix Krause <notifications@github.com> a
écrit :

**Comment by KrauseFx** [comment]
I'll close this issue for now 👍
