### ISSUE TITLE
Spaceship find_by_bundle_id ArgumentError: [!] wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by miguelsierrac** [fastlane/fastlane#11963]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Just install Fastlane 2.83.0, and I'm getting an ArgumentError: [!] wrong number of arguments (1 for 0) with find_by_bundle_id method from Spaceship.

##### Complete output when running fastlane, including the stack trace and command used

Code:
`array_profiles = Spaceship.provisioning_profile.InHouse.find_by_bundle_id(bundle_id)`

Output:
<details>/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.83.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:365:in `find_by_bundle_id': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from test.rb:91:in `<main>'</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.83.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| json                      | 2.0.2        |
</details>

*generated on:* **2018-03-01**
</details>

**Comment by lpenaflor** [comment]
I ran into the same error using match, but it seemed that I had the sigh gem 2.0.1 which is not the same version that ships with Fastlane. I removed the sigh gem and upgraded to Fastlane 2.85.0 and it works.

**Comment by miguelsierrac** [comment]
Hi @lpenaflor , thank you very much for your response. I tried updating to Fastlane 2.85.0 and removing a gem from an earlier version of Spaceship (1.0.0) that I had installed, but it still does not work. On the other hand with a version 2.8.0 of Fastlane works great. I still do not know what I'm doing wrong.

**Comment by joshdholtz** [comment]
@miguelsierrac This will do it for you!
```rb
Spaceship.login('your@email.com')
Spaceship::client.team_id = 'your-team-id'
array_profiles = Spaceship::ProvisioningProfile::InHouse.find_by_bundle_id(bundle_id: "a.b.c.")
puts "hey: #{array_profiles}"
```

Happy fastlaning 🚀
