### ISSUE TITLE
Can't provide export_compliance options to upload_to_testflight

### ISSUE THREAD

**Issue by christaggart** [fastlane/fastlane#11967]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When uploading a CI build for testing to testflight, our builds are getting stuck in "Export Compliance Required" land, and require a manual approval in iTunes Connect, even though nothing has changed since the last build. It doesn't seem like ```upload_to_testflight``` accepts any of the submission_information properties like 'export_compliance_uses_encryption' or 'export_compliance_encryption_updated' that one would include in ```deliver```. 

* Is there a way for to pass this down so that testflight builds require manual approval every time? This is purely for a beta build to internal testflight testers. 

Here's a snippet from our Fastfile:

```
 lane :beta do
    increment_build_number(build_number: ENV['CIRCLE_BUILD_NUM'], xcodeproj: "myapp.xcodeproj")
    match(type: "appstore")
    gym(workspace: "myapp.xcworkspace", scheme: "myapp", export_method: "app-store" )
    upload_to_testflight
    slack(message: "App successfully uploaded to Testflight!", channel: "#ios")
    app_identifier "com.myco.myapp-beta"
 end
```

**Comment by pparmaei** [comment]
Not too sure about using Fastfile directly, but you can do this with spaceship, see sample code below:
`build = Spaceship::TestFlight::Build.latest(app_id: appID, platform: "ios")
build.export_compliance.uses_encryption = false
build.export_compliance.encryption_updated = false
build.submit_for_testflight_review!`

I am actually trying to figure out if you can deal with the next layer of questions after you answer yes to encryption_updated with spaceship/Fastlane

**Comment by pparmaei** [comment]
@mpirri Hey Mark, I see that you commented on [Issue-9788](https://github.com/fastlane/fastlane/issues/9788) regarding something similar. I have a follow up question, on Spaceship when I look at a build object
`build = Spaceship::TestFlight::Build.latest(app_id: appID, platform: "ios")`
I see 
`export_compliance=<Spaceship::TestFlight::ExportCompliance 
		uses_encryption=nil, 
		encryption_updated=nil>,
`
Is there a way to be able to answer the more detailed questions regarding encryption, after you answer yes to uses_encryption and encryption_updated? Does such a capability to answer the follow up questions exist through Spaceship?

**Comment by joshdholtz** [comment]
@christaggart This should probably be a setting in `deliver` but cou can also set the `ITSAppUsesNonExemptEncryption` setting in your Info.plist to completely bypass that question - https://stackoverflow.com/questions/35739361/itsappusesnonexemptencryption-export-compliance-while-internal-testing

**Comment by RishabhTayal** [comment]
@joshdholtz I can take this one. How about we call the `update_info_plist` action inside `deliver` to update this setting in the Info.plist?

**Comment by christaggart** [comment]
Adding ITSAppUsesNonExemptEncryption seemed to have resolved it for us, but the deliver setting would definitely be a nice addition.

**Comment by joshdholtz** [comment]
@RishabhTayal We don't want to update anything in the user's project from `deliver` and we also want to keep `deliver` standalone from any actions 🙃 

@christaggart Glad this solved it for you! 😊 Happy fastlaning 🚀
