### ISSUE TITLE
[Supply] Proguard mapping file is not uploaded

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#11979]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When exeucting `fastlane supply` everything gets uploaded correctly except for the mapping file.

This is my configuration file:

```
package_name 'com.vanniktech.chessclock'
track 'rollout'
rollout '0.5'
json_key 'fastlane.json'
apk 'app/build/outputs/apk/release/app-1.2.4-release.apk'
mapping 'app/build/outputs/mapping/release/mapping.txt'
```

The mapping file is also recognized from fastlane:

```
[14:55:39]: Successfully loaded '/Users/nik/tmp/chess-clock/Supplyfile' 📄

+--------------+-----------------------------------------------------+
|                Detected Values from './Supplyfile'                 |
+--------------+-----------------------------------------------------+
| package_name | com.vanniktech.chessclock                           |
| track        | rollout                                             |
| rollout      | 0.5                                                 |
| json_key     | fastlane.json                                       |
| apk          | app/build/outputs/apk/release/app-1.2.4-release.apk |
| mapping      | app/build/outputs/mapping/release/mapping.txt       |
+--------------+-----------------------------------------------------+


+-------------------------+-----------------------------------------------------+
|                           Summary for supply 2.84.0                           |
+-------------------------+-----------------------------------------------------+
| package_name            | com.vanniktech.chessclock                           |
| track                   | rollout                                             |
| rollout                 | 0.5                                                 |
| metadata_path           | ./fastlane/metadata/android                         |
| json_key                | fastlane.json                                       |
| apk                     | app/build/outputs/apk/release/app-1.2.4-release.apk |
| skip_upload_apk         | false                                               |
| skip_upload_metadata    | false                                               |
| skip_upload_images      | false                                               |
| skip_upload_screenshots | false                                               |
| validate_only           | false                                               |
| mapping                 | app/build/outputs/mapping/release/mapping.txt       |
| check_superseded_tracks | false                                               |
+-------------------------+-----------------------------------------------------+
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.16.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.84.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| tty-screen                | 0.6.4        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| faraday                   | 0.14.0       |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
</details>

*generated on:* **2018-03-03**
</details>

**Comment by dvdrlee** [comment]
Could it be the same as the issue mentioned here? https://github.com/fastlane/fastlane/issues/11888

**Comment by vanniktech** [comment]
Yes I'll close. Sorry for the dupe.
