### ISSUE TITLE
Appfile is not being called when I call the main lane.

### ISSUE THREAD

**Issue by joquerod** [fastlane/fastlane#11972]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Appfile is not being called when I call the main lane.
I uninstalled Fastlane, including all versions installed on my computer. Then I cleaned up the gems, then reinstalled the latest fastlane version. Doing this fixed the problem, only the first time I called the main lane. The second time I called the main lane, I got the same problem.

##### Complete output when running fastlane, including the stack trace and command used
--capture output is only printing:
[✔] 🚀 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.2@omnibus/bin/fastlane |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.2/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

Not provided

</details>

<details><summary>`./fastlane/Appfile`</summary>

Not provided

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.84.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| json                      | 1.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| highline                  | 1.7.10       |
| commander                 | 4.4.3        |
| git                       | 1.3.0        |
| launchy                   | 2.4.3        |
| atlassian-stash           | 0.1.9        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| certified                 | 1.0.0        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.4.0.beta.2 |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.2        |
| molinillo                 | 0.6.4        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| cocoapods                 | 1.4.0.beta.2 |
| cocoapods-check           | 1.0.1        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.1        |
| xcode-install             | 2.3.1        |
</details>


*generated on:* **2018-03-02**
</details>

**Comment by joquerod** [comment]
lane example:

  desc "Build Release Build"
  lane :release do |options|
    cocoapods(repo_update: false)
    #This is the only thing my main lane is doing. I disabled other tasks just to debug this issue.
  end

**Comment by KrauseFx** [comment]
Interestingly the `Appfile` wasn't posted on that issue also. Is it inside of the `fastlane` folder? Can you share a screenshot of your whole directory structure?

**Comment by joquerod** [comment]
This is a simplified version of the Appfile, I'm just setting an ENV Variable.

Appfile example:
`
for_platform :ios do
  apple_id 'user@email.com'
  team_id 'myteamtest'

  for_lane :release do
    ENV['MY_VAR'] = 'myValue'
  end
end
`

And as part of the main lane, I'm trying to retrieve the value:
`
desc "Build Release Build"
platform :ios do

  lane :release do |options|
    puts("#{ENV['MY_VAR']}")
    #The above line prints an empty string
    cocoapods(repo_update: false)
    #This is the only thing my main lane is doing. I disabled other tasks just to debug this issue.
  end

end
`

**Comment by joquerod** [comment]
I did not include the original Fastfile and Appfile, but the requirement we have is very simple. Our build machine with Jenkins started to fail, and we didn't do any change, it just started to happen for no reason. Then I found the settings we have in the Appfile are being ignored completely. I'll add the directory structure for Fastlane

**Comment by joquerod** [comment]
![screen shot 2018-03-02 at 4 08 18 pm](https://user-images.githubusercontent.com/15059291/36921910-0592fee6-1e34-11e8-9e19-70b8b5a3f947.png)

**Comment by joquerod** [comment]
Just updated the code styling with Markdown, please review.

**Comment by joquerod** [comment]
In the meantime, I'm planning to move the Appfile configuration to .env files. Those work fine.

**Comment by joshdholtz** [comment]
@joquerod Heyyyyy 👋 So the `Appfile` doesn't actually execute `for_platform` or `for_lane` until an action in that lane and platform is executed that needs to use the `Appfile`

So, if you would call `produce` instead of `cocoapods`, your environment variable would have been set. But using `.env` files is probably the better approach anyway 💪 🙃

**Comment by joquerod** [comment]
It makes sense... I already move it to the .env files. Thank you!
