### ISSUE TITLE
help with simple code

### ISSUE THREAD

**Issue by Maheralmizany** [fastlane/fastlane#11976]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello i'm php and swift developer and i do not understand the basics of Ruby
sorry but please i want a simple code for ruby or shell (bash) 
The code i want to do is simple:

 1. sign in by email and password 
 2. register udid to developer account
 3. download a profile with select all of device

 
###
**Please Help me i want it :(**

**Comment by Maheralmizany** [comment]
I prefer spaceship for using fastLane

**Comment by Baumchen** [comment]
For iOS there's `match` (https://docs.fastlane.tools/actions/match/).
If it's fine for you to create a new certificate you can setup new certificates with `match` (e.g. `fastlane match -a XXX.YYY.ZZZ development`, where `XXX.YYY.ZZZ` is your bundle identifier) and then in your Fastfile you can use 
```
register_devices(
  devices: {
    "Name Device 1" => "UDID-DEVICE-1",
    "Name Device 2" => "UDID-DEVICE-2"
  },
  readonly: true
)
    
match(
  app_identifier: "XXX.YYY.ZZZ",
  type: "development",
  force_for_new_devices: true
)
```

You'd need to setup Fastlane first, then Match.

Disclaimer: I'm not an expert on this topic, just following my experiences from the last couple of days. Just follow the link https://docs.fastlane.tools/actions/match, there's plenty of documentation on this.

**Comment by Maheralmizany** [comment]
thank you .. but for now i want run in php script how ?
shell_exec or exec and how

**Comment by Baumchen** [comment]
Well, you could try executing commands from within php (http://be2.php.net/manual/en/function.exec.php). But I'm not sure if that makes sense at all.
Why exactly do you want to use Fastlane with php?

**Comment by Maheralmizany** [comment]
i want use spaceship with php for : 
1. get udid from database
2. add to apple developer account 
3. download profile with select all device 
4. resign ipa file 
Thank you very much

**Comment by Baumchen** [comment]
Well yes, you said that. But why would you want to use PHP in any of those steps?

If you want to use fastlane, there's `fastlane init` (https://docs.fastlane.tools) and `match init` (https://docs.fastlane.tools/actions/match). That should get you started.

Additionally there's action `register_devices` which allows you to pass a `devices_file` (potentially created by some PHP function that does the database request from step `1`; use `fastlane action register_devices` for more information). The `devices_file` has to have the format one of these: https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip .

For resigning there's action `resign` (`fastlane action resign` for more information; https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/resign.rb). 

Combining these steps sounds like it's all you need.
