### ISSUE TITLE
Support for macOS on Action match

### ISSUE THREAD

**Issue by Baumchen** [fastlane/fastlane#11980]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'd like to reopen the discussion on adding support for macOS of action `match`.
There's a pull request here: https://github.com/fastlane/fastlane/pull/9333 that seems to handle almost everything already, but was closed due to some "undisclosed Slack communication".

It would still be great to have `match` for handling certificates and provisioning profiles. Right now:
- `cert` seems to be missing support for macOS Installer certificates.
- `sigh` seems to be missing support for macOS completely.

Can you elaborate on the reasons why the existing PR (https://github.com/fastlane/fastlane/pull/9333) has been closed? Which issues need to be fixed (some are stated, but there's no comment on show stoppers)?

Thanks for any response.

**Comment by joshdholtz** [comment]
@Baumchen Thanks for bringing this back up! I _believe_ that issue was closed at the time because the goal was to focus fastlane on mobile. Some time has past and there has been some changes in goals/focus since then so this is definitely something that I'd be okay with reviving 🙃 

I've recently been able to dedicate more time to fastlane so I will move this to my list of new features to look into 💪

**Comment by lacostej** [comment]
I have a PR waiting to be revived taht supports this.

**Comment by lacostej** [comment]
See #9333

**Comment by Baumchen** [comment]
Yep, @lacostej , I referenced that PR in the description already. Thanks for your work!

@joshdholtz, thanks for looking into it ..
There's also PR #11978 which adds support for registering Mac devices.

**Comment by tbaranes** [comment]
What's the status here? Is ont of the PRs gonna be merged? It would be great to have match for macOS as well!

**Comment by sgara** [comment]
Hi guys,
Now that [CircleCI 2.0 only supports match for codesigning](https://circleci.com/docs/2.0/ios-codesigning/), I'd also love to see match working for macOS projects!
@lacostej can we do something to make that happen?

**Comment by joshdholtz** [comment]
@tbaranes @sgara Hoping to get around to this soon! I have a PR that allows `gym` to actually package Mac apps again (https://github.com/fastlane/fastlane/pull/12195) so jumping into this would totally benefit `gym` and go along with my current train of though 🙃

**Comment by joshdholtz** [comment]
Good to know 👌 I'm not a macOS app professions yet so I don't fully know all the ins and outs but really wanna get this working 💪

Side note: if anybody here would like to test my `gym` PR for building macOS apps that would be 💯 (https://github.com/fastlane/fastlane/pull/12195)

**Comment by fnlctrl** [comment]
Any updates?

**Comment by jefflovejapan** [comment]
Is there any update on this? What can we do to help get one of these merged and supported?

**Comment by subdigital** [comment]
Also want to chime in here. I just started carving out some time to get match supported on a macOS project and then ran into some issues which led me here. I'm not familiar w/ what's left, but @joshdholtz let me know if there's anything I can do to help.
