### ISSUE TITLE
diawi plugin update works for android but not for ios

### ISSUE THREAD

**Issue by nigam214** [fastlane/fastlane#11987]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane shows plugin update available on my both ios and android project. when i run update plugins command for android project, it updates the plugin but it doesn't update the same plugin on ios project:

<details>
<pre>
+--------+--------------+----------------+
|        Plugin updates available        |
+--------+--------------+----------------+
| Plugin | Your Version | Latest Version |
+--------+--------------+----------------+
| diawi  | 0.1.3        | 1.1.0          |
+--------+--------------+----------------+
[15:35:51]: To update all plugins, just run
[15:35:51]: $ bundle exec fastlane update_plugins
</pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used
<details>
<pre>
dev proj-ios $ bundle exec fastlane update_plugins --capture_output
[✔] 🚀 
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using CFPropertyList 2.3.6
...
Using fastlane 2.84.0
...
Using fastlane-plugin-diawi 0.1.3
Bundler attempted to update fastlane-plugin-diawi but its version stayed the same
Bundle updated!
Successfully updated plugins
dev proj-ios $ cd ../proj-android/
dev proj-android $ bundle exec fastlane update_plugins --capture_output
[✔] 🚀 
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using CFPropertyList 2.3.6
...
Using fastlane 2.84.0
...
Using fastlane-plugin-diawi 1.1.0
Bundler attempted to update fastlane-plugin-diawi but its version stayed the same
Bundle updated!
Successfully updated plugins
dev proj-android $ 
</pre>
</details>

### Environment

<details>
  <pre>
dev proj-android $ bundle exec fastlane env --capture_output
[✔] 🚀 
dev proj-android $ cd ../proj-ios/
dev proj-ios $ bundle exec fastlane env --capture_output
[✔] 🚀 
dev proj-ios $ 
  </pre>
</details>

**Comment by joshdholtz** [comment]
@nigam214 Do your `Gemfile` and `Gemfile.lock` look the exact same for both of your projects? It seems like your iOS projects may have a different `Gemfile` or `Gemfile.lock` which has older dependencies which is stopping `diawi` from updating.

I would suggest running `bundle update fast lane` or `bundle update` for your iOS project to make sure all dependencies are update to their latest. Hopefully this does it 😇

**Comment by nigam214** [comment]
found the issue. iOS Gemfile has cocoapods which require older version of netrc (= 0.7.8). Android doesn't have cocoapods and new version of fastlane-plugin-diawi requires newer version of netrc (~> 0.8)

### iOS Gemfile.lock
<pre>
GEM                                                                                                  
  remote: https://rubygems.org/                                                                      
  specs:                                                                                             
    cocoapods (1.3.1)
      cocoapods-trunk (>= 1.2.0, < 2.0)                                                              
    cocoapods-trunk (1.2.0)                                                                          
      netrc (= 0.7.8)                                                                                
    netrc (0.7.8)
                                                                                                     
PLATFORMS                                                                                            
  ruby                                                                                               
                                                                                                     
DEPENDENCIES                                                                                         
  cocoapods                                                                                          
  fastlane
  fastlane-plugin-diawi                                                                              

BUNDLED WITH                                                                                         
   1.16.1
</pre>


### Android Gemfile.lock
<pre>
GEM
  remote: https://rubygems.org/
  specs:
    fastlane-plugin-diawi (1.1.0)
      rest-client (>= 2.0.0)
    rest-client (2.0.2)
      netrc (~> 0.8)
    netrc (0.11.0)

PLATFORMS
  ruby

DEPENDENCIES
  fastlane
  fastlane-plugin-diawi

BUNDLED WITH
   1.16.1
</pre>

hopefully cocoapods lib will also get updates soon...
