### ISSUE TITLE
Docs should list the file structure for uploading info

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#11988]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I can't find anywhere in the docs where it shows what files I should use to upload info (in deliver).

For example in my case - I didn't have promotional_text.txt file as I had an old fastlane setup from before that existed.
Telling me that fastlane will 'automatically set up the right files' isn't helpful if you have already got a working installation.

having a definitive list of allowed/expected files would be great (I don't think my image is 100% correct)

![image](https://user-images.githubusercontent.com/586910/36971150-c88eafc8-2062-11e8-9149-68f50f7e1ed8.png)

**Comment by joshdholtz** [comment]
@ConfusedVorlon Thanks for bringing this to our attention! I created a PR in the docs repo to improve this - https://github.com/fastlane/docs/pull/553

Feel free to let me know your thoughts and comments there 😊

**Comment by ConfusedVorlon** [comment]
thanks for getting on this so quickly.
one suggestion - wherever the docs end up, you should add a link from https://docs.fastlane.tools/getting-started/ios/setup/

(assuming this doesn't get a sidebar entry of it's own)
