### ISSUE TITLE
Scan: escape HTML characters

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#11981]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using `scan` with a test that errors out with a message that has HTML characters like `<` or `>` incorrectly generates the report file.

The error `expected to equal <ComparisonAlmostEqual>, got <ComparisonEqual>` gets generated like `expected to equal , got `.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@revolter Are you going to work on this one? 😇

**Comment by revolter** [comment]
I might, as I'm also planning 2 changes to `scan` in the near future.

**Comment by revolter** [comment]
As soon as I have something I'll open a WIP PR as I might need some help (never used `scan` before).
