### ISSUE TITLE
[Spaceship] Create review with progressive rollout

### ISSUE THREAD

**Issue by martofeld** [fastlane/fastlane#11992]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I’m trying to create a review for an app using Spaceship. We use progressive rollout from Apple and when creating the submission by hand we have to select the corresponding option. Can this be done with Spaceship, and if so, how?

**Comment by joshdholtz** [comment]
@martofeld This is the thing you are looking for, right? (see image below)

![screen shot 2018-03-05 at 2 16 38 pm](https://user-images.githubusercontent.com/401294/36997972-053d7120-2081-11e8-8a2b-1a10b949df74.png)

If so, `deliver` has a parameter called `phased_release ` - https://docs.fastlane.tools/actions/deliver/#parameters

If you are you using `spaceship` directly, you can try using the `toggle_phased_release` method - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_version.rb#L206-L210

**Comment by martofeld** [comment]
@joshdholtz That is what I was looking for.

After a closer look I found the method `toggle_phased_release` you mentioned. It would be great if it could be documented under the "Submit an app for review" section of the documentation. Also, it would be awesome if the submission class had said method to allow modifications over a single object.

Thanks for the answer. I will now close the issue
