### ISSUE TITLE
INSTRUMENTATION_FAILED error when running screengrab.

### ISSUE THREAD

**Issue by shailesh2208** [fastlane/fastlane#11990]
New Issue Checklist

    [✔] Updated fastlane to the latest version
    [✔] I have read the Contribution Guidelines

Issue Description

I'm using fastlane  on my Linux environment  to build my android app, and fastlane screen grab to take snapshots in an instrumentation test. 
The application successfully running on emulator as well as on device but when we follow the steps to take screen shots we are getting the  INSTRUMENTATION_FAILED error .

Also we follow
[#8217](https://github.com/fastlane/fastlane/issues/8217)
[#9510](https://github.com/fastlane/fastlane/issues/9510)

Complete output when running fastlane to take screen shots as below 
`

root@fusioni:~# fastlane screengrab
[✔] 🚀 
[17:53:40]: fastlane detected a Gemfile in the current directory
[17:53:40]: however it seems like you don't use `bundle exec`
[17:53:40]: to launch fastlane faster, please use
[17:53:40]: 
[17:53:40]: $ bundle exec fastlane screengrab
[17:53:40]: 
[17:53:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:53:40]: Successfully loaded '/home/fusioni/fastlane/Screengrabfile' 📄

+----------------------------+-----------------------------+
|     Detected Values from './fastlane/Screengrabfile'     |
+----------------------------+-----------------------------+
| locales                    | ["en-US", "fr-FR", "it-IT"] |
| clear_previous_screenshots | true                        |
+----------------------------+-----------------------------+

[17:53:40]: The `aapt` command could not be found on your PATH
[17:53:40]: Please ensure that the Android SDK is installed and you have the build tools downloaded and present on your PATH

+-----------------------------+--------------------------------------+
|                   Summary for screengrab 2.84.0                    |
+-----------------------------+--------------------------------------+
| tests_package_name          | com.example.fusioni.fastlanetest.te  |
|                             | st                                   |
| locales                     | ["en-US", "fr-FR", "it-IT"]          |
| clear_previous_screenshots  | true                                 |
| output_directory            | fastlane/metadata/android            |
| skip_open_summary           | true                                 |
| app_package_name            | com.example.fusioni.fastlanetest     |
| test_instrumentation_runner | android.support.test.runner.Android  |
|                             | JUnitRunner                          |
| ending_locale               | en-US                                |
| device_type                 | phone                                |
| exit_on_test_failure        | true                                 |
| reinstall_app               | false                                |
+-----------------------------+--------------------------------------+

[17:53:40]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[17:53:40]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[17:53:40]: Clearing phoneScreenshots within fastlane/metadata/android
[17:53:40]: $ adb devices -l
[17:53:40]: ▸ List of devices attached
[17:53:40]: ▸ emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[17:53:40]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[17:53:40]: ▸ /sdcard
[17:53:40]: Cleaning screenshots on device
ls: /sdcard/com.example.fusioni.fastlanetest/screengrab: No such file or directory
[17:53:40]: Exit status: 1
ls: /data/data/com.example.fusioni.fastlanetest/app_screengrab: Permission denied
[17:53:40]: Exit status: 1
[17:53:40]: To not be asked about this value, you can specify it using 'app_apk_path'
[17:53:40]: Select your debug app APK
1. Downloads/FastlaneTest/app/build/outputs/apk/debug/app-debug.apk
2.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_1.apk
3.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_8.apk
4.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_9.apk
5.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_3.apk
6.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_7.apk
7.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_5.apk
8.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_6.apk
9.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_2.apk
10.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_0.apk
11.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_4.apk
12.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/dep/dependen
cies.apk
?  1
[17:55:02]: To not be asked about this value, you can specify it using 'tests_apk_path'
[17:55:02]: Select your debug tests APK
1. Downloads/FastlaneTest/app/build/outputs/apk/debug/app-debug.apk
2.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_1.apk
3.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_8.apk
4.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_9.apk
5.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_3.apk
6.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_7.apk
7.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_5.apk
8.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_6.apk
9.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_2.apk
10.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_0.apk
11.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/slices/slice
_4.apk
12.
Downloads/FastlaneTest/app/build/intermediates/split-apk/debug/dep/dependen
cies.apk
?  1
[17:55:05]: The `aapt` command could not be found on your system, so your app APK could not be validated
[17:55:05]: Installing app APK
[17:55:05]: $ adb -s emulator-5554 install -r Downloads/FastlaneTest/app/build/outputs/apk/debug/app-debug.apk
[17:55:05]: ▸ Success
[17:55:05]: Installing tests APK
[17:55:05]: $ adb -s emulator-5554 install -r Downloads/FastlaneTest/app/build/outputs/apk/debug/app-debug.apk
[17:55:06]: ▸ Success
[17:55:06]: Granting the permission necessary to change locales on the device
[17:55:06]: $ adb -s emulator-5554 shell pm grant com.example.fusioni.fastlanetest android.permission.CHANGE_CONFIGURATION
[17:55:06]: $ adb -s emulator-5554 shell getprop ro.build.version.sdk
[17:55:06]: ▸ 25
[17:55:06]: Granting the permissions necessary to access device external storage
[17:55:06]: $ adb -s emulator-5554 shell pm grant com.example.fusioni.fastlanetest android.permission.WRITE_EXTERNAL_STORAGE
[17:55:06]: $ adb -s emulator-5554 shell pm grant com.example.fusioni.fastlanetest android.permission.READ_EXTERNAL_STORAGE
[17:55:07]: Running tests for locale: en-US
[17:55:07]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
com.example.fusioni.fastlanetest.test/android.support.test.runner.AndroidJUnitRunner
[17:55:07]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.fusioni.fastlanetest.test/android.support.test.runner.AndroidJUnitRunner
[17:55:07]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:890)
[17:55:07]: ▸ at com.android.commands.am.Am.onRun(Am.java:400)
[17:55:07]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
[17:55:07]: ▸ at com.android.commands.am.Am.main(Am.java:121)
[17:55:07]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[17:55:07]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
[17:55:07]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[17:55:07]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.example.fusioni.fastlanetest.test/android.support.test.runner.AndroidJUnitRunner}
[17:55:07]: ▸ INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.fusioni.fastlanetest.test/android.support.test.runner.AndroidJUnitRunner
at com.android.commands.am.Am.runInstrument(Am.java:890)
at com.android.commands.am.Am.onRun(Am.java:400)
at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
at com.android.commands.am.Am.main(Am.java:121)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.example.fusioni.fastlanetest.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1
[17:55:07]: Exit status: 1

[!] Exit status: 1

`

``

**Comment by joshdholtz** [comment]
@shailesh2208 Hey! 👋 Its a little bit hard to debug on my end with that information but it appears this _may_ be an issue with your test APK not installing on your device/emulator. `screengrab` needs both the main app APK and the test app APK (which has the `screengrab` code) in order to run. This error makes it looks like your test APK might be be built properly with your gradle file or might not be selected properly with `screengrab` to be installed - `Unable to find instrumentation info for: ComponentInfo{com.example.fusioni.fastlanetest.test`

Can you test if your test APK was actually installed? Here is a stackoverflow post on how to do that - https://stackoverflow.com/a/23394559

**Comment by shailesh2208** [comment]
Sorry! I am unable to verify that my application listed there with the given command
 "adb shell pm list instrumentation". 
If I am using
"adb shell "pm list packages"|cut -f 2 -d ":""
Its displaying my application . 
so I can say that my application is already installed in emulator/device

**Comment by shailesh2208** [comment]
@fastlane-bot Hey! 
when we are using "fastlane env" 
we are getting the output as below 
please suggest what we have to do and what is going wrong actually?


[15:51:15]: $ bundle exec fastlane env
[15:51:15]: 
[15:51:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:51:15]: Generating fastlane environment output, this might take a few seconds...

[15:51:15]: Error accessing file, this might be due to fastlane's directory handling
[15:51:15]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/environment_printer.rb:214:in ``': No such file or directory - git (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/environment_printer.rb:214:in `print_system_environment'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/environment_printer.rb:24:in `get'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:267:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.84.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by joshdholtz** [comment]
@shailesh2208 Heyyyyy! The problem is definitely you are installing the same app as your "debug apk" and your "test apk"

Below is your output:
```sh
[17:55:05]: $ adb -s emulator-5554 install -r Downloads/FastlaneTest/app/build/outputs/apk/debug/app-debug.apk
[17:55:05]: ▸ Success
[17:55:05]: Installing tests APK
[17:55:05]: $ adb -s emulator-5554 install -r Downloads/FastlaneTest/app/build/outputs/apk/debug/app-debug.apk
```

Below is my output from one of my working examples:
```sh
[07:45:32]: Select your debug app APK
1. app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
2. app/build/outputs/apk/release/app-release-unsigned.apk
3. app/build/outputs/apk/debug/app-debug.apk
?  3
[07:45:41]: To not be asked about this value, you can specify it using 'tests_apk_path'
[07:45:41]: Select your debug tests APK
1. app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
2. app/build/outputs/apk/release/app-release-unsigned.apk
3. app/build/outputs/apk/debug/app-debug.apk
?  1
[07:45:43]: Validating app APK
[07:45:43]: $ /usr/local/share/android-sdk/build-tools/27.0.3/aapt dump permissions app/build/outputs/apk/debug/app-debug.apk
[07:45:43]: ▸ package: example.screengrab.fastlane.tools.fastlanescreengrabexample
[07:45:43]: Installing app APK
[07:45:43]: $ adb -s emulator-5554 install -r app/build/outputs/apk/debug/app-debug.apk
[07:45:45]: ▸ Success
[07:45:45]: Installing tests APK
[07:45:45]: $ adb -s emulator-5554 install -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[07:45:46]: ▸ Success
```

You can see that the APK listed under `Installing app APK` and `Installing tests APK` are different (which is what you want). 

Below is an example of what I sometimes do in my `Fastfile`...
```rb
platform :android do
  lane :test do
    gradle(
      task: 'assemble assembleAndroidTest'
    )

    apk_path = Dir.glob("../**/*-debug.apk").first
    test_apk_path = Dir.glob("../**/*-debug-androidTest.apk").first

    screengrab(
      app_package_name: 'example.screengrab.fastlane.tools.fastlanescreengrabexample',
      app_apk_path: File.absolute_path(apk_path),
      tests_apk_path:  File.absolute_path(test_apk_path)
    )
  end
end
```

Hopefully this does it for you 💪

**Comment by shailesh2208** [comment]
@fastlane-bot We are unable to generate app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
what should I do?
Thanks

**Comment by joshdholtz** [comment]
@shailesh2208 Are you running both the `assemble` and `assembleAndroidTest` gradle tasks?

**Comment by shailesh2208** [comment]
@joshdholtz  yes we are running both.

**Comment by joshdholtz** [comment]
@shailesh2208 That is super weird 😔 It sounds like it could be a configuration issue with how your Android test or gradle file. I would suggest trying to create a basic sample project using screengrab docs (this is what I did this morning to help replicate what you were seeing) - https://docs.fastlane.tools/actions/screengrab/#ui-tests

**Comment by shailesh2208** [comment]
@joshdholtz we already created three basic sample project. but as you suggested i will again create a new sample project and soon will get back to you.
Thanks

**Comment by shailesh2208** [comment]
@joshdholtz  again we created a sample project but same issue occur (unable to find the debug test APK)

**Comment by joshdholtz** [comment]
@shailesh2208 So your `android/build/outputs/apk` directory doesn't have an `androidTest` directory in it with a `app-debug-androidTest.apk` in it like mine does? This is what also needs to get installed with `snapshot`
<img width="823" alt="screen shot 2018-03-16 at 8 54 10 pm" src="https://user-images.githubusercontent.com/401294/37550496-375c45d0-295c-11e8-8e35-09f8a734ada1.png">

**Comment by taman123** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.1 (Apple Git-101)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E199)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "assembleDemo")
    say "Assemble completed"
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Users/user/Documents/fastlanekey/peacenepalpersonal.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.peacenepal.jyotilife") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>


*generated on:* **2018-04-04**
</details>


I am facing same issue as above. Has anyone fixed this issue?
