### ISSUE TITLE
Pilot output: `Build doesn't show up in the build list anymore, waiting for it to appear again`

### ISSUE THREAD

**Issue by hazzaldo** [fastlane/fastlane#11999]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi, 
Currently I'm trying to run the Test Flight lane, which looks like this in the fastfile:
<details>
<pre>desc "Submits a new Beta Build to Apple TestFlight"
	lane :beta_testflight do
    	adhoc_cert
    	store_cert
    	increment_build_number
    	gym(configuration: "Debug", clean: true, export_method: "ad-hoc")
    	pilot(app_identifier: "com.XXXX.XXXXX")
  	end</pre>
</details>

When I invoke the lane using the command - `fastlane beta_testflight --capture_output` .  I get this output (I only get this when I add the `--capture_output` part), which probably doesn't help much (and not really sure how to resolve this bit so it shows the expected output):

<details>
  <pre>[[✔] 🚀 
security: SecKeychainItemImport: The specified item already exists in the keychain.
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
security: SecKeychainItemImport: The specified item already exists in the keychain.
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
Current version of project mZone Poker is: 
    7

/Users/harethnaji/Downloads/mZone
2018-03-06 11:02:08.354 xcodebuild[83059:2624755]  DTDeviceKit: deviceType from e7de9ef16f1950f76fb1198b4f991b1d213157c2 was NULL]</pre>
</details>

Running the command `fastlane beta_testflight`, it's supposed to upload a build to Test Flight, which it doesn't quite succeed to do in the end. I'll try to be as brief as possible on the output (just showing the final outcome messages for each step e.g. successful or error):

<details>
<pre>
 ------------------------------
[11:18:48]: --- Step: default_platform ---
[11:18:48]: ------------------------------
[11:18:48]: Driving the lane 'ios beta_testflight' 🚀
[11:18:48]: -------------------------------------------
[11:18:48]: --- Step: Switch to ios adhoc_cert lane ---
[11:18:48]: ------------------------------------------- 
All required keys, certificates and provisioning profiles are installed 🙌
 -------------------------------------------
[11:18:56]: --- Step: Switch to ios store_cert lane ---
[11:18:56]: -------------------------------------------
All required keys, certificates and provisioning profiles are installed 🙌
------------------------------------
[11:19:03]: --- Step: increment_build_number ---
[11:19:03]: ------------------------------------
[11:21:39]: -----------------
[11:19:05]: --- Step: gym ---
[11:19:05]: -----------------
Successfully exported and signed the ipa file:
-------------------
[11:21:39]: --- Step: pilot ---
[11:21:39]: -------------------
Ready to upload new build to TestFlight (App: xxxxxxxxxx)...
iTunes Transporter successfully finished its job
[12:07:29]: ---------------------------------------------------------------------------------------------------------------
[12:07:29]: --- Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online. ---
[12:07:29]: ---------------------------------------------------------------------------------------------------------------
[12:07:29]: Successfully uploaded the new binary to iTunes Connect
[12:07:29]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[12:07:32]: Waiting for iTunes Connect to finish processing the new build (1.0 - 9)
[12:08:03]: Waiting for iTunes Connect to finish processing the new build (1.0 - 9)
[12:08:34]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:09:05]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:09:36]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:10:18]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:10:49]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:11:19]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:11:50]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:12:21]: Build doesn't show up in the build list anymore, waiting for it to appear again
[12:12:52]: Build doesn't show up in the build list anymore, waiting for it to appear again
</pre>
</details>

The output line below continues to output infinitely: 
```
Build doesn't show up in the build list anymore, waiting for it to appear again
```
I'm not really sure what this means. I have looked at previous similar issues. One was resolved apparently by a new release of Fastlane. This was back in April 2017. I'm on the latest version of Fastlane and this issue is happening. 
Can someone assist on this please. 

Many thanks in advance. 

### Environment

<details>
  <pre>[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |
 </pre>
</details>

<details><summary>`./fastlane/Appfile`</summary>

*generated on:* **2018-03-06**
</details>]</pre>
</details>

**Comment by joshdholtz** [comment]
@hazzaldo Heyyyy 👋  So I've seen this happen to me when my app has errors after iTunesConnect tries to process the app. I would look in your email to see if you received a message from iTunesConnect showing if there were any errors.

The email should look something like the following:
![screen shot 2018-03-06 at 8 23 33 am](https://user-images.githubusercontent.com/401294/37037342-b448faa4-2117-11e8-824c-50c32fe3edfd.png)

**Comment by hazzaldo** [comment]
@joshdholtz , thank you for the response and help. Yes you're right, I got an email from Apple. I don't know how I missed that email. :P  
It suggested to correct the following:
```
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

Though you are not required to fix the following issues, we wanted to make you aware of them:

Missing App Store Icon - iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ for more information.

Missing beta entitlement - Your app does not include the beta-reports-active entitlement. If you intend to distribute this build via TestFlight for beta testing, please re-build this app with an App Store Distribution provisioning profile. Do not use ad-hoc profiles.
```
For `Missing App Store Icon` I have added an image 1024x1024 to fill in that resolution requirement

For `Missing beta entitlement` I changed the Signing  provisional profile (Release) from `Ad-hoc` to `AppStore`.

And as for `Invalid Swift Support`, I found a Fastlane previous issue, where solution suggests: `if i use appstore to gym. there is no issue.it is contain the SwiftSupport folder
but it failed in development and ad-hoc`. So I have changed my gym function to not include `configuration: "Debug", or Ad-hoc export method`. So my gym looks like this now: `gym(clean: true)`. 
The same issue errors appeared for a while, but eventually as you can see from the screenshot below it completed successfully: 
![fastlane](https://user-images.githubusercontent.com/16270718/37045818-b527f58c-215e-11e8-8564-76f45dc1d0eb.png)


And I received an email from Apple this time confirming that the build has been pushed successfully to Test Flight ready for testing.

Also the builds appeared in iTunes connect.

So, even though it's working, and thank you so much for your help, I'm still not sure why the `Build doesn't show up in the build list anymore, waiting for it to appear again` message still appears at least a few times, before the success message appears. If anyone knows please feel free to share it here, so that future developers can benefit from the answer. 

Many thanks again for your help @joshdholtz

**Comment by joshdholtz** [comment]
@hazzaldo Glad you got your issues worked out! iTunesConnect is a funny thing that we have very little control over 😔 I have had that same showing, hiding, and showing later experience with the actual web iTC dashboard (which is why I think we have the text saying "Build doesn't show up in the build list anymore..."). It maybe because Apple is hiding it for some reason and will show it later but it may also be because of an error 🤔 

We could maybe add some text in there to say "If this continues, check your email for processing issues" or something like that????

**Comment by hazzaldo** [comment]
@joshdholtz ye I think that's a good idea. Every time I managed to solve an error quickly in Fastlane, it was because Fastlane gave me a big hint or told me what I needed to do to solve the issue (in the output). As you can see from this issue, without a helpful suggestion to solve the issue, the error itself doesn't tell you much, otherwise. I guess if you get email notifications via your smartphone or desktop notifications then you can see the email from Apple, but otherwise if the email can be missed. 
Thanks again 👍

**Comment by Nov1kov** [comment]
I'm still the same bug. And I didn't receive mail from apple.

**Comment by Aravindios** [comment]
Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues) 

how to solve this.

**Comment by tedgonzalez** [comment]
I had to manually send the testflight build for review, then pilot has Successfully finished processing the build
