### ISSUE TITLE
patch file to change provisional profile from dev to adhoc is throwing errors in Fastlane output

### ISSUE THREAD

**Issue by hazzaldo** [fastlane/fastlane#12001]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Currently I have a `beta_testflight` lane, which looks like this:
```
desc "Submits a new Beta Build to Apple TestFlight"
	lane :beta_testflight do
    	# cocoapods
    	adhoc_cert
    	store_cert
    	increment_build_number
    	sh "cd .. && git apply adhoc.patch"
    	gym(clean: true)
    	pilot(app_identifier: "com.xxxx.xxxxxxxxxxxxxxxxxxxxxxx")
    	sh "cd .. && git apply -R adhoc.patch"
  	end
```
When I invoke the lane, the `sh "cd .. && git apply adhoc.patch"` part is not working (throwing errors). This part is basically meant to switch the provisional profile from `development` to `adhoc` for you so you don't have to go into xcode general settings and do it manually. This is so to enable `gym` to create the correct build for testing (using the correct (adhoc) profile). This line/command is basically applying a patch file, which I created, which contains the Git diff text created as a result of switching from `development` to `adhoc` provisional profile in xcode. Hence it's applied automatically and you don't have to change the provisional profile manually. 

Here's the output I get in Fastlane:
<details>
  <pre>[[17:04:08]: --------------------------------------------
[17:04:08]: --- Step: cd .. && git apply adhoc.patch ---
[17:04:08]: --------------------------------------------
[17:04:08]: $ cd .. && git apply adhoc.patch
[17:04:08]: ▸ error: corrupt patch at line 24
[17:04:08]: An error occurred while executing the `error` block:
[17:04:08]: undefined method `error_info' for #<FastlaneCore::Interface::FastlaneShellError:0x007fde8518c020>
+------------------------------------+---------------------------------------------------------------+
|                                            Lane Context                                            |
+------------------------------------+---------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                           |
| PLATFORM_NAME                      | ios                                                           |
| LANE_NAME                          | ios beta_testflight                                           |
| SIGH_PROFILE_TYPE                  | app-store                                                     |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.xxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx"=>"match AppStore  |
|                                    | com.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx"}                    |
| BUILD_NUMBER                       | 23                                                            |
+------------------------------------+---------------------------------------------------------------+
[17:04:08]: Exit status of command 'cd .. && git apply adhoc.patch' was 128 instead of 0.
error: corrupt patch at line 24
+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 1    | default_platform               | 0           |
| 2    | Switch to ios adhoc_cert lane  | 0           |
| 3    | match                          | 5           |
| 4    | Switch to ios store_cert lane  | 0           |
| 5    | match                          | 6           |
| 6    | increment_build_number         | 1           |
| 💥   | cd .. && git apply adhoc.patch | 0           |
+------+--------------------------------+-------------+

[17:04:08]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...

➡️  Adds more options to the `slack` command
    https://github.com/fastlane/fastlane/pull/128 [closed] 3 💬
    04 Feb 2017

➡️  Added hipchat messaging support
    https://github.com/fastlane/fastlane/pull/24 [closed] 6 💬
    04 Feb 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/harethnaji/.rvm/gems/ruby-2.4.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `shell_error!': [!] Exit status of command 'cd .. && git apply adhoc.patch' was 128 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
error: corrupt patch at line 24
]</pre>
</details>

And this is the content of the patch file (the file name is `adhoc.patch`:
```
diff --git a/mZone Poker.xcodeproj/project.pbxproj b/mZone Poker.xcodeproj/project.pbxproj
index b350605..15ed78a 100644
--- a/mZone Poker.xcodeproj/project.pbxproj     
+++ b/mZone Poker.xcodeproj/project.pbxproj     
@@ -452,7 +452,7 @@
                        buildSettings = {
                                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
                                CODE_SIGN_IDENTITY = "iPhone Distribution";
-                               "CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
+                               "CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Distribution";
                                CODE_SIGN_STYLE = Manual;
                                CURRENT_PROJECT_VERSION = 21;
                                DEVELOPMENT_TEAM = xxxxxxxx;
@@ -465,8 +465,8 @@
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                                PRODUCT_BUNDLE_IDENTIFIER = "com.xxxxxxxxxxxxxxxxxxxxx";
                                PRODUCT_NAME = "$(TARGET_NAME)";
-                               PROVISIONING_PROFILE = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
-                               PROVISIONING_PROFILE_SPECIFIER = "match Development com.xxxxxxxxxxxxxxxxxxxxxxx";
+                               PROVISIONING_PROFILE = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
+                               PROVISIONING_PROFILE_SPECIFIER = "match AdHoc com.xxxxxxxxxxxxxxxxxxxxxx";
                                SWIFT_VERSION = 4.0;
                                VERSIONING_SYSTEM = "Apple Generic";
                        };
```

By the way, I picked up on this approach from a developer called `Jag Cesar` from his video tutorial fastfile demo: https://www.youtube.com/watch?v=fxLgEtk-ALA&t=639s (skip to 09:20 in the video for this particular part), if it's of any help.  

### Environment

<details>
  <pre>[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |
]</pre>
</details>

**Comment by joshdholtz** [comment]
@hazzaldo Does `git apply adhoc.patch` work when run by itself outside of fastlane in the CLI? It looks like the git command is returning an error because of an invalid patch `Exit status of command 'cd .. && git apply adhoc.patch' was 128 instead of 0.
error: corrupt patch at line 24`

I have no idea if this will work but maybe try...
```rb
Bundler.with_clean_env do
  sh "cd.. && git apply adhoc.patch"
end
```

If this doesn't work I don't think we can offer much help here since this is a pretty custom setup where it looks like the git patch you are applying is causing the issue - not anything fastlane related 😇  But hopefully we can get this working for you!

**Comment by hazzaldo** [comment]
Hi @joshdholtz , thanks for the response and suggestion :)  
So the `corrupt patch at line 24` is no longer showing when I added `\ No newline at end of file` at the end of the patch file. However, now when I run `git apply adhoc.patch` I get a different output error: 
```
error: mZone Poker.xcodeproj/project.pbxproj     : No such file or directory
```
When I navigated to that directory, the file does exist. So I don't know why it's saying `no such file or directory`!!!
![project_pbxproj directory](https://user-images.githubusercontent.com/16270718/37092505-189f471e-2204-11e8-8f3a-253fc138d09a.png)

**Comment by joshdholtz** [comment]
@hazzaldo It sounds like something is still wonky with the patch and where (the directory) the command is being execute from? The space in the file name might be an issue? I don't think I can be too much help since this is more of a custom implementation than something built and supported by fastlane 🙃

**Comment by hazzaldo** [comment]
No problem. Thanks for your suggestions in any case :)

**Comment by joshdholtz** [comment]
Anytime! Have fun fastlaning 🚀
