### ISSUE TITLE
Xamarin automatic release ios and android

### ISSUE THREAD

**Issue by KellyHannemann** [fastlane/fastlane#12007]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Is there a way to use fastlane to automatically release to android and ios using a xamarin cross platform project?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@KellyHannemann Hello 👋  There is currently no support for Xamarin for building apps in fastlane. Some people have developed custom implementations that have worked for them but we don't have anything built in yet. We would gladly take a pull request for Xamarin support if anybody is willing to make it though 😇
