### ISSUE TITLE
Problem to upload android app to crashlytics

### ISSUE THREAD

**Issue by luiszacheu** [fastlane/fastlane#12005]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I don't understand the cause of this error:

Did start a few days ago ago. A another thing I set up was the fastlane to iOS
Someone have one explanation for this?

WARN - Crashlytics had a problem uploading the deobs file. Please check network connectivity and try again.
[11:05:00]: ▸ javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No X509TrustManager implementation available

<details>
  <pre>[11:05:05]: Shell command exited with exit status 1 instead of 0.
+-----------------------------+-----------------------------------------------------------------+
|                                         Lane Context                                          |
+-----------------------------+-----------------------------------------------------------------+
| DEFAULT_PLATFORM            | android                                                         |
| PLATFORM_NAME               | android                                                         |
| LANE_NAME                   | android demo                                                    |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/luiszacheu/AndroidDeveloper/workspaceAndroidStudio/qp  |
|                             | roretail-android/app/build/outputs/apk/app-demo-release.apk",   |
|                             | "/Users/luiszacheu/AndroidDeveloper/workspaceAndroidStudio/qpr  |
|                             | oretail-android/app/build/outputs/apk/app-demo-debug.apk"]      |
| GRADLE_APK_OUTPUT_PATH      | /Users/luiszacheu/AndroidDeveloper/workspaceAndroidStudio/qpro  |
|                             | retail-android/app/build/outputs/apk/app-demo-release.apk       |
+-----------------------------+-----------------------------------------------------------------+
[11:05:07]:  WARN - Crashlytics had a problem uploading the distribution.
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No X509TrustManager implementation available
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)</pre>
</details>

**Comment by joshdholtz** [comment]
@luiszacheu So uploading your android app to crashlytics was working until a few days ago? Did anything else change on your system since then? Like Java versions? SSL? Proxies?

I'm not a huge expert at this kind of stuff but it seems like there is something between fastlane and crashlytics API that is causing this 😬

**Comment by joshdholtz** [comment]
@luiszacheu I just built an Android app and successfully uploaded it to crashlytics successfully on my side. It looks to be a configuration issue or something on your machine. Are you able to try to run your fastlane setup on a different machine to see if it works there?

**Comment by luiszacheu** [comment]
@joshdholtz Yes I did try in my personal machine and works successfully, I don't remember if I updated my java versions, but I install some certificates to iOS distribution and make a any setup my environment for this. Thank you. I go search how fix this :(

**Comment by luiszacheu** [comment]
@joshdholtz the problem occurs after I run this command: `osx-ssl-certs update all`
 When I run this on failed machine `rvm osx-ssl-certs status` show me this `Certificates for /usr/local/etc/openssl/cert.pem: Up to date.`
I sucess machine show me this : `Certificates for /usr/local/etc/openssl/cert.pem: Old.`

You have any idea about this?
