### ISSUE TITLE
cannot deploy to crashlytics

### ISSUE THREAD

**Issue by nikeshakya** [fastlane/fastlane#12003]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
 Hey, 
I am using 
crashlytics(api_token: "token",
              build_secret: "secret",
              groups:["alias"],
              notes: last_git_commit[:message],
              crashlytics_path: "./Pods/Crashlytics",
              notifications: notifications)
command to deploy build to crashlytics 
after successful build using gym 
but 
It is throwing error saying 
submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18) (FastlaneCore::Interface::FastlaneError)
2018-03-07 14:42:36.044 submit Crashlytics: Unable to inflate IPA to temporary path: Error Domain=CLSFileSystemUtilsErrorDomain Code=-1 "(null)"

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.84.0"
default_platform(:ios)

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "slackURL"

  end

  desc "Gets current version number"
  lane :version do
    get_version_number
  end

  desc "Bumps version. Type: patch"
  lane :version_patch do
    increment_version_number(bump_type: "patch")
  end

  desc "Bumps version. Type: minor"
  lane :version_minor do
    increment_version_number(bump_type: "minor")
  end

  desc "Bumps version. Type: major"
  lane :version_major do
    increment_version_number(bump_type: "major")
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :getProfiles do
    # Get the latest provisionnig profiles from the Dev Portal and
    get_certificates(
      development: false,
      username: "email"
    )
    udid = sigh(app_identifier: "appID.*",
                output_path: "/tmp",
                skip_certificate_verification: false,
                adhoc: true)
    ENV["WATCHKIT_EXTENSIONS_UDID"] = udid

    udid = sigh(app_identifier: "appID.*",
                output_path: "/tmp",
                skip_certificate_verification: false,
                adhoc: true)
    ENV["WATCHKIT_APP_UDID"] = udid

    udid = sigh(app_identifier: "appID",
                output_path: "/tmp",
                skip_certificate_verification: false,
                readonly: true,
                adhoc: true)
    ENV["PROJECT_UDID"] = udid
  end


  desc "Submit a new Beta Build to Apple CrashLytics"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    notifications = true
    if options[:notifications] != nil
      notifications = options[:notifications]
    end
    # get_certificates # invokes cert
    # get_provisioning_profile(
    #   adhoc: true,
    #   readonly: true
    # ) #invokes sigh
    getProfiles
    cocoapods
    gym(
      export_method: "ad-hoc",
      export_options: {
        iCloudContainerEnvironment: 'Production',
        compileBitcode: false
      },
      scheme: "Artup"
    )
    deployToFabric

  end

  desc "Deploys the build to crashlytics"
  lane :deployToFabric do |options|
    notifications = true
    if options[:notifications] != nil
      notifications = options[:notifications]
    end
    crashlytics(api_token: "token",
              build_secret: "secret",
              groups:["alias"],
              notes: last_git_commit[:message],
              crashlytics_path: "./Pods/Crashlytics",
              notifications: notifications)
    notifySlack
  end

  # desc "Deploy a new version to the App Store"
  # lane :appstore do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

  lane :notifySlack do
    slack(message: "@channel New build available",
      channel: "#git-ios",
      payload: {
      "Build Date" => Time.new.to_s,
      "Branch" => git_branch,
      "Version" => get_version_number
    })
  end

  desc "Push a new release build to the App Store"
  lane :appstore_release do
    build_app(workspace: "Artup.xcworkspace", scheme: "Artup")
    upload_to_app_store
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("appID") # The bundle identifier of your app
apple_id("email") # Your Apple email address

itc_team_id "team_itc_id" # iTunes Connect Team ID
team_id "team_id" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.84.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
</details>

*generated on:* **2018-03-07**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@nikeshakya Do you have any more output available? Like where the IPA was originally located or what temporary path it tried to inflate? Your `Fastfile` looks like it should be okay so can't tell too much right now without some more info 🙃

**Comment by nikeshakya** [comment]
@joshdholtz ipa is located in same directory where fastfile is located..
I used this about 1 2 months ago....it was working fine 
but now it is giving me this error.

**Comment by joshdholtz** [comment]
@nikeshakya Weird 🤔 This appears to be an issue from within the Crashyltics side of things - `Crashlytics.framework/submit 1.3.5`. I don't know a ton about Crashlytics works on the inside but it looks like this may be a crashlytics issue?

**Comment by nikeshakya** [comment]
@joshdholtz any suggested solution for this ?

**Comment by joshdholtz** [comment]
@nikeshakya Are there any upgrades for Crashlytics available? Its either an issue with the IPA not getting created properly, some permissions of some sort where the temporary path is, or something within Crashlytics. Is your hard drive full??? Maybe that's why I can't inflate the IPA? 🤔

**Comment by nikeshakya** [comment]
it is not hard drive issue..
and I have latest crashlytics 
I also tried creating IPA from xcode and then upload it via fastlane but still same error

**Comment by joshdholtz** [comment]
@nikeshakya Are you able to try uploading the IPA with crashlytics directly? (I don't know how this is done, TBH). But that would help us diagnose if its a fastlane issue or a crashlytics issue 😇

**Comment by nikeshakya** [comment]
yeah
uploading directly crashlytics is what I have been doing..
now I want it to be automated with fastlane 
but its causing error @joshdholtz

**Comment by joshdholtz** [comment]
@nikeshakya Thanks for looking into! That is very odd. Are you able to provide me with a full output so I can see any more stacktrace info? (if there is anymore)

**Comment by joshdholtz** [comment]
@nikeshakya Can you also set the `debug` option in the `crashlytics` action to `true` for me? 😁

**Comment by nikeshakya** [comment]
@joshdholtz will update you today 
gonna try update gem files

**Comment by nikeshakya** [comment]
@joshdholtz it uploaded successfully after updating gem files 
will close issue for now and update you when I encounter similar problem again
thanks

**Comment by shrawan2015** [comment]
Your fastlane version 2.85.0 matches the minimum requirement of 2.85.0  ✅


[05:59:31]: Successfully exported and compressed dSYM file
[05:59:31]: Successfully exported and signed the ipa file:
[05:59:31]: /Users/distiller/AppIOS/Beta.ipa
[05:59:31]: -------------------------
[05:59:31]: --- Step: crashlytics ---
[05:59:31]: -------------------------
[05:59:31]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[05:59:45]: Build successfully uploaded to Crashlytics Beta 🌷
[05:59:45]: Visit https://fabric.io/_/beta to add release notes and notify testers.
[05:59:45]: -------------------
[05:59:45]: --- Step: slack ---
[05:59:45]: -------------------
[05:59:46]: Successfully sent Slack notification

Still I am not getting new build

**I have updated gem,fastlane**

At last i am getting error 
WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

Still app is not uploaded to fabric. Anything that need to be considered.

**Comment by joshdholtz** [comment]
@shrawan2015 Your issue is a fabric's side - I saw this myself when trying to debug this issue. It took a good amount of time for my app to show up in fabric. I don't exactly know what happens but if fastlane says that it successfully uploaded then there isn't anything more I can help with 😇

Sorry for you pain! I know how this goes 😢 It eventually showed up for me (don't know why/how)
