### ISSUE TITLE
Frameit titles shown as question marks when "Whites" used as key

### ISSUE THREAD

**Issue by stonehouse** [fastlane/fastlane#12009]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is a pretty weird issue, I just wanted to check whether it's a known issue before I get together more information. When I use Frameit, the title text is shown as "?????" only for Japanese and Russian screenshots that have the key "Whites". If I change the name of the screenshots and key to something else, then the result is fine. All other languages are fine even if the key is "Whites" (English, French, Italian, German, Portuguese). The only difference between the failing language and the working ones is that they use different fonts, Russian and Japanese each use their own fonts.

I'm happy to make a repo to reproduce it, I just wanted to check whether there is a known issue with using "White" as a key.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Only thing I can think of: There is a way to specify the color of the frames to be used when framing the screenshots - maybe this includes "white" and somehow (but how!?) messes with the strings?
