### ISSUE TITLE
error with devices text file option of register_devices

### ISSUE THREAD

**Issue by hazzaldo** [fastlane/fastlane#12006]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying the `register_devices(devices_file: "./devices.txt")` functionality to register devices before recreating the Adhoc provisional profile. 

```
desc "Submits a new Beta Build to Apple TestFlight"
	lane :beta_crashlytic do
    	# cocoapods
    	register_devices(devices_file: "./devices.txt")
```

I get the following output error:
```
Please provide a file according to the Apple Sample UDID file (https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip)
```
One problem with that suggestion is, the `Multiple-Upload-Samples.zip` is no longer accessible:

<img width="895" alt="txt file not accessible" src="https://user-images.githubusercontent.com/16270718/37108901-7442ccf4-2230-11e8-8c07-054e8c41b478.png">

This is the content of the `devices.txt` file:
```
Device ID   Device Name
e7de9ef16f1950f76fb1198b4f991b1d213157c2	Hareth's iPhone
```
I know there was another similar issue reported before, but I tried the suggested solution `a tab and a space between the id and the name!` and it didn't work for me. Presumably meaning press tab once and a space once between the uuid and the device name. 

<img width="793" alt="solution" src="https://user-images.githubusercontent.com/16270718/37109197-20c9d634-2231-11e8-9dc9-c32061eb3f4f.png">

Any help would be really appreciated.
### Environment

<details>
  <pre>[### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |]</pre>
</details>

**Comment by joshdholtz** [comment]
@hazzaldo Do you have a tab between "Device ID" and "Device Name"? Your file contents shows a tab between the `e7de9ef16f1950f76fb1198b4f991b1d213157c2 ` and `Hareth's iPhone` but not between the `Device ID` and `Device Name`

**Comment by hazzaldo** [comment]
Good call @joshdholtz :)  yep that was the issue. It's working now. Fastlane community must be keeping you on overtime shift :D  as this is my third issue I've raised on Fastlane that you ended up answering in quick succession. Many thanks @joshdholtz  :) 👍

**Comment by G1King** [comment]
I am a direct copy of the multiple-device-upload-ios. TXT, and then modify the device name and ID. 😆
