### ISSUE TITLE
 EXPORT FAILED  Exit status: 70 

### ISSUE THREAD

**Issue by G1King** [fastlane/fastlane#12017]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
<details><summary>`./fastlane/Appfile`</summary>

```ruby



# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-pgyer     | 0.2.1        |
</details>

*generated on:* **2018-03-09**
</details>
Error log: 
----------------------------------------------------------------
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/8g/p5vxk53d6pnc6jn7zkjk8k9r0000gn/T/gym_config20180309-32487-a01ytz.plist -archivePath '/Users/Sunshinking/Library/Developer/Xcode/Archives/2018-03-09/SPIC-TutorialSystem 2018-03-09 12.44.41.xcarchive' -exportPath /var/folders/8g/p5vxk53d6pnc6jn7zkjk8k9r0000gn/T/gym_output20180309-32487-y65091
2018-03-09 12:55:00.541 xcodebuild[37502:266566] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/8g/p5vxk53d6pnc6jn7zkjk8k9r0000gn/T/SPIC-TutorialSystem_2018-03-09_12-55-00.532.xcdistributionlogs'.
2018-03-09 12:55:00.956 xcodebuild[37502:266566] [MT] IDEDistribution: Step failed: <IDEDistributionOptionsStep: 0x7f9de092f6f0>: Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided}
error: exportArchive: exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided}

** EXPORT FAILED **
[12:55:00]: Exit status: 70
----------------------------------------------------------------
When I used iCloud, I used the script to package，Would be an error！！！！

**Comment by joshdholtz** [comment]
@G1King Your error appears to be something with the value you are setting for `iCloudContainerEnvironment `

Your output shows the following error. What do you have it set as? It needs to be either "Development" or "Production".
```sh
exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided
```

**Comment by G1King** [comment]
@joshdholtz  thank you for your reply! 
this is my ExportOptions  . i set iCloudContainerEnvironment,But it's still wrong.
![image](https://user-images.githubusercontent.com/21077737/37237369-3a1d0354-244d-11e8-9eb6-7df7ecdedd72.png)

**Comment by G1King** [comment]
@joshdholtz thank you for your reply。I set iCloudContainerEnvironment value.but it's still wrong.
this is my exportOptionsPlist
![image](https://user-images.githubusercontent.com/21077737/37237398-9e0700ae-244d-11e8-952b-a8d4fd50b028.png)

**Comment by joshdholtz** [comment]
@G1King Does your project build properly in Xcode? Have you tried setting `gym` to something like...
```rb
gym(
  export_options: {iCloudContainerEnvironment: 'Development']} # or 'Production'
) 
```

**Comment by G1King** [comment]
@joshdholtz     thank you very much .Solve problems successfully！！
