### ISSUE TITLE
Fastlane formatted output is not working properly in CloudBees Jenkins CI even after using ANSI plugin

### ISSUE THREAD

**Issue by dineshkrishna** [fastlane/fastlane#12010]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### The fastlane formatted output is not working properly in CloudBees Jenkins CI even after using ANSI plugin and the environment variables needed to set the console log format. Every character is separated by a bunch of asterisks in the log and it makes totally unusable. I am pasting the actual text and the corrupted text for reference. There is no issue with the fastlane build. I have attached the smaller failed log instead of the full success log.

Corrupted console log in CloudBees Jenkins:
****[****i****O****S****_************/****b****i****n****/****s****h**** ****-****x****e**** ****/****v****a****r****/****f****o****l****d****e****r****s****/****6****f****/****s****s****q****b****w****p****p****j****5****9****5****3****h****w****h****7****g****3****v****5****x****b****x****r****0****0****0****0****g****p****/****T****/****j****e****n****k****i****n****s****4****5****8****0****9****9****0****6****8****5****2****1****5****2****0****1****9****1****0****.****s****h****
********[****E****n****v****I****n****j****e****c****t****]**** ****-**** ****I****n****j****e****c****t****i****n****g**** ****e****n****v****i****r****o****n****m****e****n****t**** ****v****a****r****i****a****b****l****e****s**** ****f****r****o****m**** ****a**** ****b****u****i****l****d**** ****s****t****e****p****.****
********[****E****n****v****I****n****j****e****c****t****]**** ****-**** ****I****n****j****e****c****t****i****n****g**** ****a****s**** ****e****n****v****i****r****o****n****m****e****n****t**** ****v****a****r****i****a****b****l****e****s**** ****t****h****e**** ****p****r****o****p****e****r****t****i****e****s**** ****f****i****l****e**** ****p****a****t****h**** ****'****e****n****v****.****p****r****o****p****e****r****t****i****e****s****'****
********[****E****n****v****I****n****j****e****c****t****]**** ****-**** ****V****a****r****i****a****b****l****e****s**** ****i****n****j****e****c****t****e****d**** ****s****u****c****c****e****s****s****f****u****l****l****y****.****
********[****i****O****S****_******$**** ****/****b****i****n****/****s****h**** ****-****x****e**** ****/****v****a****r****/****f****o****l****d****e****r****s****/****6****f****/****s****s****q****b****w****p****p****j****5****9****5****3****h****w****h****7****g****3****v****5****x****b****x****r****0****0****0****0****g****p****/****T****/****j****e****n****k****i****n****s****1****9****1****3****8****8****7****5****5****1****9****4****5****6****4****3****1****7****4****.****s****h****
********+**** ****e****x****p****o****r****t**** ****T****E****R****M****=****x****t****e****r****m****-****2****5****6****c****o****l****o****r****
********+**** ****T****E****R****M****=****x****t****e****r****m****-****2****5****6****c****o****l****o****r****
********+**** ****e****x****p****o****r****t**** ****L****A****N****G****=****e****n****_****U****S****.****U****T****F****-****8****
********+**** ****L****A****N****G****=****e****n****_****U****S****.****U****T****F****-****8****
********+**** ****e****x****p****o****r****t**** ****L****A****N****G****U****A****G****E****=****e****n****_****U****S****.****U****T****F****-****8****
********+**** ****L****A****N****G****U****A****G****E****=****e****n****_****U****S****.****U****T****F****-****8****
********+**** ****e****x****p****o****r****t**** ****L****C****_****A****L****L****=****e****n****_****U****S****.****U****T****F****-****8****
********+**** ****L****C****_****A****L****L****=****e****n****_****U****S****.****U****T****F****-****8****
********+**** ****c****d**** ****/****U****s****e****r****s****/********/****c****l****o****u****d****b****e****e****s****_****j****e****n****k****i****n****s****/****w****o****r****k****s****p****a****c****e****/****N****a****t****i****v****e****M****o****b****i****l****e****A****p****p****s****/****I****P****H****N****-****6****9****8****5****3****0****/****i****O****S****_*******/****c****o****d****e****
********/****v****a****r****/****f****o****l****d****e****r****s****/****6****f****/****s****s****q****b****w****p****p****j****5****9****5****3****h****w****h****7****g****3****v****5****x****b****x****r****0****0****0****0****g****p****/****T****/****j****e****n****k****i****n****s****1****9****1****3****8****8****7****5****5****1****9****4****5****6****4****3****1****7****4****.****s****h****:**** ****l****i****n****e**** ****1****0****:**** ****c****d****:**** ****/****U****s****e****r****s****/********/****c****l****o****u****d****b****e****e****s****_****j****e****n****k****i****n****s****/****w****o****r****k****s****p****a****c****e****/****N****a****t****i****v****e****M****o****b****i****l****e****A****p****p****s****/****I****P****H****N****-****6****9****8****5****3****0****/****i****O****S****_*******/****c****o****d****e****:**** ****N****o**** ****s****u****c****h**** ****f****i****l****e**** ****o****r**** ****d****i****r****e****c****t****o****r****y****
********B****u****i****l****d**** ****s****t****e****p**** ****'****E****x****e****c****u****t****e**** ****s****h****e****l****l****'**** ****m****a****r****k****e****d**** ****b****u****i****l****d**** ****a****s**** ****f****a****i****l****u****r****e****
********S****S****H****:**** ****C****u****r****r****e****n****t**** ****b****u****i****l****d**** ****r****e****s****u****l****t**** ****i****s**** ****[****F****A****I****L****U****R****E****]****,**** ****n****o****t**** ****g****o****i****n****g**** ****t****o**** ****r****u****n****.****
********E****m****a****i****l**** ****w****a****s**** ****t****r****i****g****g****e****r****e****d**** ****f****o****r****:**** ****F****a****i****l****u****r****e**** ****-**** ****A****n****y****
********S****e****n****d****i****n****g**** ****e****m****a****i****l**** ****f****o****r**** ****t****r****i****g****g****e****r****:**** ****F****a****i****l****u****r****e**** ****-**** ****A****n****y****
********A****n**** ****a****t****t****e****m****p****t**** ****t****o**** ****s****e****n****d**** ****a****n**** ****e****-****m****a****i****l**** ****t****o**** ****e****m****p****t****y**** ****l****i****s****t**** ****o****f**** ****r****e****c****i****p****i****e****n****t****s****,**** ****i****g****n****o****r****e****d****.****
********F****i****n****i****s****h****e****d****:**** ****F****A****I****L****U****R****E****

Actual log after removing the asterisks by 'find and replace'

[iOS_CompanyX_Labs] $ /bin/sh -xe /var/folders/6f/ssqbwppj5953hwh7g3v5xbxr0000gp/T/jenkins4580990685215201910.sh
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path 'env.properties'
[EnvInject] - Variables injected successfully.
[iOS_CompanyX_Labs] $ /bin/sh -xe /var/folders/6f/ssqbwppj5953hwh7g3v5xbxr0000gp/T/jenkins1913887551945643174.sh
+ export TERM=xterm-256color
+ TERM=xterm-256color
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ export LANGUAGE=en_US.UTF-8
+ LANGUAGE=en_US.UTF-8
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ cd /Users//cloudbees_jenkins/workspace/NativeMobileApps/IPHN-****/iOS_CompanyX_Labs/code
/var/folders/6f/ssqbwppj5953hwh7g3v5xbxr0000gp/T/jenkins1913887551945643174.sh: line 10: cd: /Users//cloudbees_jenkins/workspace/NativeMobileApps/IPHN-****/iOS_CompanyX_Labs/code: No such file or directory
Build step 'Execute shell' marked build as failure
SSH: Current build result is [FAILURE], not going to run.
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE

What's the issue thats causing the log to get corrupt like this in cloud bees jenkins? Please let us know if anyone had faced an issue like this before?

Thanks, 
Dinesh

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.59.0"

default_platform :ios

#built_ipa_path '../build/'


platform :ios do
before_all do
ENV["SLACK_URL"] = "https://hooks.slack.com/services/****/@@@@@“
# cocoapods

end


# This is for daily builds using adhoc profile and adhoc scheme
lane :jenkins_test do

    # POSSIBLE GYM CONFIGURATION TYPES:
    # Debug, Testing, Adhoc, AppStore?, etc

    ios_app_filename = ENV["TEST_FILENAME"]

#   match(
#       app_identifier: "com.CompanyX.mobile.home",
#       type:"adhoc"
#   )

    ios_build_number = ENV["BUILD_NUMBER"]

    increment_build_number(
        build_number: ios_build_number
    )


    gym(
        scheme: "CompanyX-Adhoc",
        export_method: "ad-hoc",
        configuration: "Adhoc",
        output_name: "#{ios_app_filename}.ipa",
        clean: "true",
        export_options: {
            method: "ad-hoc",
            teamID: "****",
            compileBi****se,
            uploadSymbols: true,
            provisioningProfiles: {
                "com.CompanyX.mobile.home" => "CompanyXHome_Adhoc",
            },
            manifest: {
                appURL: "https://***.test.cloud.CompanyX.com/files/#{ios_app_filename}.ipa",
                displayImageURL: "https://**.test.cloud.CompanyX.com/files/app_icon.png",
                fullSizeImageURL: "https://****.test.cloud.CompanyX.com/files/app_icon_full.png",
                title: "CompanyX"
            }
        }
    )


#   # Code to fix space in manifest plist if any in the file
#   replace="CompanyX"
#   filename = ENV["WORKSPACE"] + "/build/manifest.plist"
#   outdata = File.read(filename).gsub(/CompanyX Dev/, "#{replace}")

#   File.open(filename, 'w') do |out|
#       out << outdata
#   end

    Dir.chdir(ENV["WORKSPACE"] + "/build/") do
        File.rename("manifest.plist", "#{ios_app_filename}.plist")
    end

    swiftlint(
        mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
        output_file: "swiftlintResult.html", # The path of the output file (optional)
        config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
        ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )



end



lane :jenkins_appstore do

# match(type: "appstore")
# snapshot
# gym(scheme: "CompanyX",
# clean: "true") # Build your app - more options available

ios_build_number = ENV["BUILD_NUMBER"]
deliver_ipa_path = ENV["DELIVER_IPA_PATH"]
ios_app_filename = ENV["APPSTORE_FILENAME"]
ios_app_version = ENV["APP_VERSION"]
workspace_path = ENV["WORKSPACE"]


#p deliver_ipa_path # to display the variable value use p or puts
#p ios_app_filename
built_ipa_path = workspace_path + deliver_ipa_path + ios_app_filename + ".ipa"
#p built_ipa_path
sh("echo #{built_ipa_path}")

increment_build_number(
    build_number: ios_build_number
)


gym(
scheme: "CompanyX",
export_method: "app-store",
configuration: "Release",
output_name: "#{ios_app_filename}.ipa",
clean: "true",
export_options: {
method: "app-store",
teamID: "****",
compileBitcode: true,****bols: true,
provisioningProfiles: {
"com.CompanyX.mobile.home" => "CompanyXHome_AppStore",
},
manifest: {
appURL: “*****.ipa",
displayImageURL: "*****icon.png",
fullSizeImageURL: "*****icon_full.png",
title: "CompanyX"
}
}
)







desc "Runs all the tests"
lane :test do
scan
end



desc "Submit a new Beta Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :beta do
# match(type: "appstore") # more information: https://codesigning.guide
gym(scheme: "CompanyX",
    clean: "true",
    export_options: {
        method: "app-store",
        provisioningProfiles: {
            "com.CompanyX.mobile.home" => "CompanyXHome_AppStore_Distribution"
        }
    }
) # Build your app - more options available
pilot

# sh "your_script.sh"
# You can also use other beta testing services here (run `fastlane actions`)
end



# You can define as many lanes as you want



after_all do |lane|
# This block is called, only if the executed lane was successful
build_number = ENV["BUILD_NUMBER"]
   slack(
        message: "Fastlane build:#{build_number} Successful"
    )
end

error do |lane, exception|
 slack(
   message: exception.message,
   success: false
 )
end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.CompanyX.mobile.home" # The bundle identifier of your app
apple_id “*****-*****@CompanyX.com" # Your Apple email address

team_id “*******” # Developer Portal Team ID****IVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
ENV["DELIVER_SUBMIT_FOR_REVIEW"] = "false"
ENV["DELIVER_IPA_PATH"] = "/build/" #Use the path where the appstore ready ipa file is residing
ENV["DELIVER_SUBMIT_FOR_REVIEW"] = "false"
#ENV["IOS_APP_FILENAME"] = “***.ipa" # Comment if using direct gym build
#ENV["IOS_APP_VERSION"] = "4.2.0"



# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.84.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-03-07**
</details></pre>
</details>

**Comment by dineshkrishna** [comment]
I havent had much support from CloudBees on this. We dont know whats causing this issue. I dont know how to proceed further :(

**Comment by joshdholtz** [comment]
@dineshkrishna Sorry to here you aren't getting any support from CloudBees 😔 I have never seen anything like this and I can't seem to find anyway to produce this on my end to look into a fix

**Comment by dineshkrishna** [comment]
We got it resolved finally, from manual trouble shooting. One secret text Binding plug-in entry was causing this issue which no one could have related the corrupted log to. Anyway, Thank you.

**Comment by joshdholtz** [comment]
Woot! Glad to hear 😊 Happy fastlaning 🚀
