### ISSUE TITLE
Snapshot fails all UI tests when app has background processing.

### ISSUE THREAD

**Issue by wuftymerguftyguff** [fastlane/fastlane#12019]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My app has an embedded web server.  This runs as a background task.
When I run my screen shotting test cases from Xcode they all work fine.

When I run snapshot using fastlane snapshot I get the error below.

If I comment out the start of the background web server, then fast lane snapshot works fine.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
ERROR [2018-03-09 15:31:40.33]: iPhone 7 Plus: ; iPad Pro (12.9-inch): Failed to terminate com.redacted.redacted:63490 after 60.0s; state is still `Running Background` (3) (/Users/redacted/Documents/stuff/redacted/ScreenshotBuilder/ScreenshotBuilder.swift:58); iPhone 7 Plus: Failed to terminate com.redacted.redacted:64155 after 60.0s; state is still `Running Background` (3) (/Users/redacted/Documents/stuff/redacted/ScreenshotBuilder/ScreenshotBuilder.swift:58), Failed to terminate com.redacted.redacted:64155 after 60.0s; state is still `Running Background` (3) (/Users/redacted/Documents/stuff/redacted/ScreenshotBuilder/ScreenshotBuilder.swift:58), Failed to terminate com.redacted.redacted:64155 after 60.0s; state is still `Running Background` (3) (/Users/redacted/Documents/stuff/redacted/ScreenshotBuilder/ScreenshotBuilder.swift:58)
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.3                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.47.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    #carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    changelog = prompt(
  text: "Changelog: ",
  multi_line_end_keyword: "END"
)
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "sqrl-ponly") # Build your app - more options available
    pilot(distribute_external: true, 
        changelog: changelog
    ) 

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "sqrl-ponly") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.redacted" # The bundle identifier of your app
apple_id "redacted@gmail.com" # Your Apple email address

team_id "redacted" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-03-09**
</details></pre>
</details>

**Comment by janpio** [comment]
When does this error occur - before, during or after taking the screenshots?

**Comment by wuftymerguftyguff** [comment]
The screenshots seem to get taken, the files in the output dir certainly get updated.

However every single test is failed, so the individual files never get processed and screenshots.html never gets updated.

I get the error once per test.

I guess the process under test is polled to see when it is complete? As mine has background threads it does not appear to be complete inside the 60 second timeout.

**Comment by janpio** [comment]
That is what I would guess as well. Not really an idea how to fix that though :/

**Comment by joshdholtz** [comment]
@wuftymerguftyguff Are you able to provide a code example of the embedded web server so we can try and reproduce? There seem to be a few issues with snapshot and background processing and having a nice background example might help 🙃

**Comment by wuftymerguftyguff** [comment]
OK, I'll try to pull a minimal project together that has the issue.

**Comment by wuftymerguftyguff** [comment]
In fact..

The demo project for iOS here would probably be the best place to start.

https://github.com/swisspol/GCDWebServer
