### ISSUE TITLE
Please help me. How to modify project.pbxproj file？I didn't find the action.

### ISSUE THREAD

**Issue by YTFDoing** [fastlane/fastlane#12018]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@YTFDoing What are you looking todo? A to of Xcode Project modification is one with https://github.com/CocoaPods/Xcodeproj
