### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by hulinhu521** [fastlane/fastlane#12011]
After set  fastlane init:

INFO [2018-03-08 11:42:52.96]: -----------------------------
INFO [2018-03-08 11:42:52.96]: --- Welcome to fastlane 🚀 ---
INFO [2018-03-08 11:42:52.96]: -----------------------------
INFO [2018-03-08 11:42:52.96]: fastlane can help you with all kinds of automation for your mobile app
INFO [2018-03-08 11:42:52.96]: We recommend automating one task first, and then gradually automating more over time
WARN [2018-03-08 11:42:52.96]: What would you like to use fastlane for?
ERROR [2018-03-08 11:42:52.99]: Unable to send the crash report.
ERROR [2018-03-08 11:42:52.99]: Please open an issue on GitHub if you need help!

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/11802 [open] 4 💬
    4 weeks ago

➡️  FR : Improve non interactive mode for latest_testflight_build_number
    https://github.com/fastlane/fastlane/issues/10772 [open] 5 💬
    2 weeks ago

➡️  fastlane cert --output_path doesn't generate p12 file
    https://github.com/fastlane/fastlane/issues/11009 [open] 14 💬
    5 weeks ago

and 25 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/hulinhu/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Users/hulinhu/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:140:in `verify_interactive!'
	from /Users/hulinhu/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:123:in `select'
	from /Users/hulinhu/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/fastlane/lib/fastlane/setup/setup_ios.rb:44:in `setup_ios'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/fastlane/lib/fastlane/setup/setup.rb:104:in `start'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:127:in `block (2 levels) in run'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/hulinhu/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.84.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/hulinhu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.84.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

**Comment by hulinhu521** [comment]
what should I do for this issue ?? thanks.

**Comment by joshdholtz** [comment]
@hulinhu521 What terminal program are you running this in? Are you using the standard OSX "Terminal" app?

**Comment by jushiyuan** [comment]
@joshdholtz Hi,I face the same issue,I am using the standard OSX "Terminal" app.

**Comment by KrauseFx** [comment]
> `Could not retrieve response as fastlane runs fastlane.ci and can't ask for additional inputs during its run`

This just means you forgot to provide some information to the fastlane run. In this case you get `What would you like to use fastlane?`, meaning you'd have the lane selection here. You have to provide a lane when running fastlane

**Comment by gaofengtan** [comment]
Has the problem been solved?

**Comment by KrauseFx** [comment]
It isn't a problem, the error message describes how to solve it exactly 👍

**Comment by Dev-Crea** [comment]
I'm resolved my problem with disable ENV variables configured in my .zshrc.

TRAVIS and CI varaible it's defined and create conflit with fastlane process.

I created an alias:
```linux
alias fastlane='unset TRAVIS CI && fastlane '
```
A good idea it's write this ENV variable in fastlane env command for diagnostic ?

**Comment by gaofengtan** [comment]
Have you solved the problem?
