### ISSUE TITLE
P12 file created by match cannot be installed on another computer manually or usable by other tools (MS AppCenter)

### ISSUE THREAD

**Issue by gokulraja** [fastlane/fastlane#12029]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Unable to use the mobile provisioning file, p12 file combination on ms appcenter. Get the password is wrong error.
on Mac when I double-click and try to install the p12 from the certs folder it asks for a password, the password which I used the passphrase  for the repo but it doesn't seem to be the valid password.
Please advice on how to get the p12 password.

When I generate the p12 from keychain using the export option the p12 generated and the mobile provisioning file are not linked properly "Invalid .mobileprovision" is the error message.

I was successful in using fast lane to deploy to TestFlight. Thank You for the wonderful toolset.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Hf.xcodeproj")
    build_app(scheme: "hf")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("org.hfm") # The bundle identifier of your app
apple_id("aaa@aaa.com") # Your Apple email address

itc_team_id "1123456713" # iTunes Connect Team ID
team_id "AD912345ME" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-03-11**
</details></pre>
</details>

**Comment by gokulraja** [comment]
I have checked the Code Signing Troubleshooting Guide. But the issue I am facing doesn't have the required solution.
To simplify my initial question : Without using match how can I reuse the p12 file on another machine. If we get an answer for this question. I think the issue will get resolved. Thanks !!

**Comment by joshdholtz** [comment]
@gokulraja Your `Fastfile` doesn't show

**Comment by joshdholtz** [comment]
@gokulraja Your `Fastfile doesn't show how you are generating your certifications. Are you using `cert` to create them? If so, have you tried using a blank password?

**Comment by gokulraja** [comment]
@joshdholtz I created the certificate using fastlane match development command.

**Comment by joshdholtz** [comment]
@gokulraja Have you tried trying this same MS AppCenter approach by creating a certificate and mobile provisioning profile manually and seeing if that works? I regularly export my certificates from my keychain and don't see any problems like this 🤔

**Comment by gokulraja** [comment]
Hi @joshdholtz 
Finally the issue the fixed. So the current workflow is use match to generate the certs and provisioning profiles.
Generate the p12 file from keychain
Goto apple developer account download the provisioning file and upload to app center.
By doing so I was able to get it working.
It would be nice if we have an option in fastlane where it generates decerypted p12 and provisioning profile that we can use for external entities like appcenter and delete them manually.
Thank You !!

**Comment by joshdholtz** [comment]
@gokulraja Glad you got it solved! You can definitely use `match` to download and decrypt the repo and pull from there. The contents are just AES-256 encrypted with your `match` password so you should have full ability to do that 😊 

But happy to see you figured it out! Happy fastlaning 🚀

**Comment by gokulraja** [comment]
@joshdholtz this is one of the best tools out there. Are you on gitter or slack to discuss a couple of small items which will help the process

**Comment by joshdholtz** [comment]
@gokulraja Glad you like it! And thanks for using it 🙃 Feel free to create an issue with a `[Discussion]` or `[Proposal]` in the name and we can have the conversation here and allow anybody else to throw in any ideas or thoughts 💪
