### ISSUE TITLE
Match decrypt failure-then-success password loop

### ISSUE THREAD

**Issue by WoodyWoodsta** [fastlane/fastlane#12025]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This issue has almost definitely been reported before, however, all proposed fixes have not resolved the issue and so I thought that I could perhaps have a different problem but with the same results.

Due to client and company policy, there is no way for fastlane match to create its own Distribution Certificate and Provisioning Profiles. The only way to use match is to create the match repo from scratch and encrypt certificates and profiles ourselves. I've done so but I have managed to get the below password loop error. I know that I have encrypted the certificates correctly, because it seems as though match is able to decrypt the certificates at least once during the loop pattern, and I've also manually cloned, decrypted and installed the certificates without an issue.

FWIW, using the `MATCH_PASSWORD` env variable also does not work.

Secondly: I wouldn't mind knowing why fastlane match checks out the desired branch, and then tries to clone the repo again, specifically checking out the master branch? I've tried pushing certs and profiles to multiple other branches (for multiple targets) and at some point, fastlane match will try to pull from/push to the master branch, and of course be met with errors. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
bundle exec fastlane ios deploy --env=stage --verbose
[✔] 🚀
DEBUG [2018-03-09 17:30:31.15]: Checking if there are any plugins that should be loaded...
DEBUG [2018-03-09 17:30:31.16]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2018-03-09 17:30:31.16]: gem 'fastlane-plugin-appcenter' is already installed
+---------------------------+---------+------------------+
|                      Used plugins                      |
+---------------------------+---------+------------------+
| Plugin                    | Version | Action           |
+---------------------------+---------+------------------+
| fastlane-plugin-appcenter | 0.1.7   | appcenter_upload |
+---------------------------+---------+------------------+

INFO [2018-03-09 17:30:31.43]: gem 'dotenv' is already installed
INFO [2018-03-09 17:30:31.44]: Loading from './fastlane/.env.stage'
INFO [2018-03-09 17:30:31.44]: Driving the lane 'ios deploy' 🚀

Loading Environment File: stage

INFO [2018-03-09 17:30:31.45]: --------------------------------------
INFO [2018-03-09 17:30:31.45]: --- Step: Switch to ios setup lane ---
INFO [2018-03-09 17:30:31.45]: --------------------------------------
INFO [2018-03-09 17:30:31.45]: Cruising over to lane 'ios setup' 🚖
INFO [2018-03-09 17:30:31.45]: -------------------
INFO [2018-03-09 17:30:31.45]: --- Step: match ---
INFO [2018-03-09 17:30:31.45]: -------------------
Successfully loaded Appfile at path 'xxx/fastlane/Appfile'
- app_identifier: 'com.xxx.xxx.stage'
- apple_id: 'xxx@xxx.com'
- team_id: 'xxx'
- itc_team_name: 'xxxx'
-------

+-----------------------+---------------------------------------------------------------+
|                               Summary for match 2.85.0                                |
+-----------------------+---------------------------------------------------------------+
| type                  | appstore                                                      |
| app_identifier        | ["com.xxx.xxx.stage"]                                    |
| git_url               | git@github.com:xxx/xxx.git |
| readonly              | true                                                          |
| clone_branch_directly | true                                                          |
| git_branch            | master                                                        |
| username              | xxx@xxx.com                                       |
| keychain_name         | login.keychain                                                |
| team_id               | xxx                                                    |
| verbose               | false                                                         |
| force                 | false                                                         |
| skip_confirmation     | false                                                         |
| shallow_clone         | false                                                         |
| force_for_new_devices | false                                                         |
| skip_docs             | false                                                         |
| platform              | ios                                                           |
+-----------------------+---------------------------------------------------------------+

INFO [2018-03-09 17:30:31.55]: Cloning remote git repo...
INFO [2018-03-09 17:30:31.55]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:xxx/xxx.git' '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-4tlkj6' -b master --single-branch
INFO [2018-03-09 17:30:31.57]: ▸ Cloning into '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-4tlkj6'...
INFO [2018-03-09 17:30:32.84]: ▸ remote: Counting objects: 129, done.
INFO [2018-03-09 17:30:32.84]: ▸ remote: Compressing objects: 100% (2/2), done.
INFO [2018-03-09 17:30:33.18]: ▸ remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 127
INFO [2018-03-09 17:30:33.19]: ▸ Receiving objects: 100% (129/129), 153.18 KiB | 580.00 KiB/s, done.
INFO [2018-03-09 17:30:33.19]: ▸ Resolving deltas: 100% (4/4), done.
WARN [2018-03-09 17:30:33.29]: Migrating to new match...
WARN [2018-03-09 17:30:33.35]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-03-09 17:30:33.35]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-03-09 17:30:33.35]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-03-09 17:30:33.35]: Passphrase for Git Repo: ****************
 [2018-03-09 17:30:48.14]: Type passphrase again: ****************
INFO [2018-03-09 17:30:49.08]: Cloning remote git repo...
INFO [2018-03-09 17:30:49.08]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-03-09 17:30:49.08]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:xxx/xxx.git' '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-tczodq'
INFO [2018-03-09 17:30:49.09]: ▸ Cloning into '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-tczodq'...
INFO [2018-03-09 17:30:50.22]: ▸ remote: Counting objects: 162, done.
INFO [2018-03-09 17:30:50.48]: ▸ remote: Total 162 (delta 0), reused 0 (delta 0), pack-reused 162
INFO [2018-03-09 17:30:50.48]: ▸ Receiving objects: 100% (162/162), 196.31 KiB | 752.00 KiB/s, done.
INFO [2018-03-09 17:30:50.48]: ▸ Resolving deltas: 100% (7/7), done.
ERROR [2018-03-09 17:30:50.59]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/xxx/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:xxx/xxx.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303330393137333034395A00  "20180309173049Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303330393137333034395A00  "20180309173049Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:xxx/xxx.git"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2018-03-09 17:30:50.69]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-03-09 17:30:50.69]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-03-09 17:30:50.69]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-03-09 17:30:50.69]: Passphrase for Git Repo: ****************
 [2018-03-09 17:30:59.60]: Type passphrase again: ****************
INFO [2018-03-09 17:31:00.84]: 🔓  Decrypted 'xxx.cer'
INFO [2018-03-09 17:31:00.88]: 🔓  Decrypted 'xxx.p12'
INFO [2018-03-09 17:31:00.94]: 🔓  Decrypted 'AppStore_com.xxx.xxx.mobileprovision'
INFO [2018-03-09 17:31:00.94]: 🔓  Successfully decrypted certificates repo
keychain: "/Users/xxx/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:xxx/xxx.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303330393137333130305A00  "20180309173100Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303330393137333130305A00  "20180309173100Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:xxx/xxx.git"
    "type"<uint32>=<NULL>
password has been deleted.
INFO [2018-03-09 17:31:01.14]: 🔒  Encrypted 'xxx.cer'
INFO [2018-03-09 17:31:01.19]: 🔒  Encrypted 'xxx.p12'
INFO [2018-03-09 17:31:01.25]: 🔒  Encrypted 'AppStore_com.xxx.xxx.mobileprovision'
INFO [2018-03-09 17:31:01.25]: 🔒  Successfully encrypted certificates repo
INFO [2018-03-09 17:31:01.25]: Pushing changes to remote git repo...
INFO [2018-03-09 17:31:01.25]: $ git add -A
INFO [2018-03-09 17:31:01.26]: $ git commit -m \[fastlane\]\ Changed\ passphrase
INFO [2018-03-09 17:31:01.29]: ▸ [master 208de0e] [fastlane] Changed passphrase
INFO [2018-03-09 17:31:01.29]: ▸ 3 files changed, 244 insertions(+), 229 deletions(-)
INFO [2018-03-09 17:31:01.29]: ▸ rewrite certs/distribution/xxx.cer (100%)
INFO [2018-03-09 17:31:01.29]: ▸ rewrite certs/distribution/xxx.p12 (100%)
INFO [2018-03-09 17:31:01.29]: ▸ rewrite profiles/appstore/AppStore_com.xxx.xxx.mobileprovision (100%)
INFO [2018-03-09 17:31:01.29]: $ GIT_TERMINAL_PROMPT=0 git push origin master
INFO [2018-03-09 17:31:04.59]: ▸ Counting objects: 9, done.
INFO [2018-03-09 17:31:04.59]: ▸ Delta compression using up to 8 threads.
INFO [2018-03-09 17:31:04.59]: ▸ Compressing objects: 100% (7/7), done.
INFO [2018-03-09 17:31:04.59]: ▸ Writing objects: 100% (9/9), 11.63 KiB | 11.63 MiB/s, done.
INFO [2018-03-09 17:31:04.59]: ▸ Total 9 (delta 0), reused 0 (delta 0)
INFO [2018-03-09 17:31:06.83]: ▸ To github.com:xxx/xxx.git
INFO [2018-03-09 17:31:06.83]: ▸ 3067ea4..208de0e  master -> master
INFO [2018-03-09 17:31:06.85]: Cloning remote git repo...
INFO [2018-03-09 17:31:06.85]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-03-09 17:31:06.85]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:xxx/xxx.git' '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-drevpd'
INFO [2018-03-09 17:31:06.87]: ▸ Cloning into '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-drevpd'...
INFO [2018-03-09 17:31:08.17]: ▸ remote: Counting objects: 171, done.
INFO [2018-03-09 17:31:08.17]: ▸ remote: Compressing objects: 100% (7/7), done.
INFO [2018-03-09 17:31:08.48]: ▸ remote: Total 171 (delta 0), reused 9 (delta 0), pack-reused 162
INFO [2018-03-09 17:31:08.48]: ▸ Receiving objects: 100% (171/171), 207.90 KiB | 872.00 KiB/s, done.
INFO [2018-03-09 17:31:08.48]: ▸ Resolving deltas: 100% (7/7), done.
WARN [2018-03-09 17:31:08.59]: Migrating to new match...
INFO [2018-03-09 17:31:08.66]: Cloning remote git repo...
INFO [2018-03-09 17:31:08.66]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-03-09 17:31:08.66]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:xxx/xxx.git' '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-1gvp9mq'
INFO [2018-03-09 17:31:08.67]: ▸ Cloning into '/var/folders/z4/5jgh06rd66l7x84p2870hrnc0000gn/T/d20180309-80188-1gvp9mq'...
INFO [2018-03-09 17:31:09.89]: ▸ remote: Counting objects: 171, done.
INFO [2018-03-09 17:31:09.89]: ▸ remote: Compressing objects: 100% (7/7), done.
INFO [2018-03-09 17:31:10.21]: ▸ remote: Total 171 (delta 0), reused 9 (delta 0), pack-reused 162
INFO [2018-03-09 17:31:10.21]: ▸ Receiving objects: 100% (171/171), 207.90 KiB | 831.00 KiB/s, done.
INFO [2018-03-09 17:31:10.21]: ▸ Resolving deltas: 100% (7/7), done.
ERROR [2018-03-09 17:31:10.33]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/xxx/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:xxx/xxx.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303330393137333130315A00  "20180309173101Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303330393137333130315A00  "20180309173101Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:xxx/xxx.git"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2018-03-09 17:31:10.44]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-03-09 17:31:10.44]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-03-09 17:31:10.44]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-03-09 17:31:10.44]: Passphrase for Git Repo:</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.16.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |
</pre>
</details>

**Comment by WoodyWoodsta** [comment]
Managed to resolve the issue! The problem was that I did not place a `match_version.txt` file in the root of the repo, and this caused the tool to get into some sort of a loop.

Perhaps this could be a bit safer?

**Comment by joshdholtz** [comment]
Glad you figured it out! 😊
