### ISSUE TITLE
Missing password for user, and running in non-interactive shell

### ISSUE THREAD

**Issue by klinkert0728** [fastlane/fastlane#12023]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

<details>
  <pre>[09:19:54]: [32mDriving the lane 'ad_hoc' 🚀[0m
[09:19:54]: [32m---------------------[0m
[09:19:54]: [32m--- Step: produce ---[0m
[09:19:54]: [32m---------------------[0m

+----------------+--------------------------------------+
|              [32mSummary for produce 2.85.0[0m               |
+----------------+--------------------------------------+
| username       |             |
| app_identifier |.00000000.beta  |
|                | .CustomForm.e1628dba.Testing         |
| app_name       | Test UID                             |
| app_version    | 1.00                                 |
| sku            | 1520615976                           |
| language       | English                              |
| team_id        | XXXXXXXX                           |
| skip_itc       | true                                 |
| platform       | ios                                  |
| skip_devcenter | false                                |
+----------------+--------------------------------------+

[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
[32mSee more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
[32m-------------------------------------------------------------------------------------[0m
+---------------+--------+
|      [33mLane Context[0m      |
+---------------+--------+
| PLATFORM_NAME |        |
| LANE_NAME     | ad_hoc |
+---------------+--------+
[09:19:54]: [31mMissing password for user, and running in non-interactive shell[0m

+------+---------+-------------+
|       [32mfastlane summary[0m       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 💥   | [31mproduce[0m | 0           |
+------+---------+-------------+
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D47)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-03-09**
</details>
</pre>
</details>

**Comment by klinkert0728** [comment]
I already have the password stored in the keychain it works if I run the code manually

**Comment by joshdholtz** [comment]
@klinkert0728 Does your password by any chance have a `\` in it? It maybe related to this issue - https://github.com/fastlane/fastlane/issues/10746

**Comment by klinkert0728** [comment]
@joshdholtz  hey thanks for your reply. No the password does not contain \ . however i was able to fix the issue by moving the password to the system keychain along with the certificate, and then i move it back to the login keychain. and it works perfect.
