### ISSUE TITLE
Is it possible to update System Capabilities to add associated domains (for multiple target app)?

### ISSUE THREAD

**Issue by EugeneGoloboyar** [fastlane/fastlane#12038]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I wonder is it possible to update xproj* file ('SystemCapabilities') to add specific associated domains for different target?

I need to add smth like this  
1 Add to the proj file "SystemCapabilities" => {"com.apple.SafariKeychain" => {"enabled" => 1}}}
(for each target)
2 Update app entitlements (I can update entitlement file but without step 1 it doesn't work)

I didn't find some reliable way to update this. 

Thanks if you find some time to help with this.

**Comment by joshdholtz** [comment]
@EugeneGoloboyar You could do something custom like this with `xcodeproj` - https://github.com/fastlane/fastlane/issues/6544#issuecomment-262220946

Its also on stackoverflow too - https://stackoverflow.com/questions/40673116/ionic-cordova-how-to-add-push-capability-with-fastlane-or-xcodebuild/40741297#40741297

Closing this for now but lemme know if you have any other questions/issues! Happy fastlaning 🚀
