### ISSUE TITLE
Adding last_git_commit to Fastlane Swift

### ISSUE THREAD

**Issue by monolithic-adam** [fastlane/fastlane#12043]
Hey guys, love fastlane and don't know what I would do without it.

Recently I have been trying to convert our current fastlane setup into Swift and I ran across a missing command that I would like to add `last_git_commit` to `Fastlane.swift`

Let me know what you think!

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to add the command last_git_commit that is missing from Fastlane swift.

```
@discardableResult func lastGitCommit() -> [String : String] {
    let command = RubyCommand(commandID: "", methodName: "last_git_commit", className: nil, args: [])
    return parseDictionary(fromString: runner.executeCommand(command))
}
```

**Comment by joshdholtz** [comment]
@monolithic-adam Heyyy 👋 Only the main fastlane tools are currently supported by Swift (like `deliver`, `scan`, `snapshot`, `match`, `produce`, etc). I will update the docs to make that more clear 😊

**Comment by joshdholtz** [comment]
@monolithic-adam I think we found the issue! I will look into 😊
