### ISSUE TITLE
ios upload to fabric beta fail

### ISSUE THREAD

**Issue by adsl99801** [fastlane/fastlane#12044]
2018-03-13 16:25:58.609 xcodebuild[83056:8372622] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path
'/var/folders/xs/f4xsj2d53mz4jljhvccfhkrc0000gn/T/Reader2_2018-03-13_16-25-58.607.xcdistributionlogs'.
2018-03-13 16:25:59.588 xcodebuild[83056:8372622] [MT] IDEDistribution: Step failed: <IDEDistributionOptionsStep: 0x7fac40a71220>: Error Domain=IDEFo$
ndationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was
provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, $
ut no value was provided}
error: exportArchive: exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was prov$
ded

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production$
, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Develop$
ent, Production}, but no value was provided}

** EXPORT FAILED **
[16:25:59]: Exit status: 70

https://imgur.com/a/mgdw4

```
my fastlane file is 

https://fabric.io/features/distribution
```

upload to testfight is okay but fail to fabric

**Comment by G1King** [comment]
I have the same problem as you. when i use  iCloudKit @adsl99801

**Comment by damboscolo** [comment]
I have the same problem!

**Comment by joshdholtz** [comment]
@adsl99801 You are using a different target/scheem to upload to fabric, right? Is there anything different you are doing between you App Store (TestFlight) build and your adhoc (fabric) build?

Can you try adding this to gym/build_app to see if this helps?
```
gym(
  export_options: {iCloudContainerEnvironment: 'Development']} # or 'Production'
) 
```

**Comment by G1King** [comment]
@joshdholtz success solved my problem.  Thank you very much

**Comment by adsl99801** [comment]
Thanks!
Problem solved.
```
  build_app(
    scheme: "Project",
    export_method: "ad-hoc",
    export_options: {iCloudContainerEnvironment: 'Production'} 
  )
```
