### ISSUE TITLE
Frameit: Order of fonts in Framefile.json causes title to appear as ?????

### ISSUE THREAD

**Issue by mtrezza** [fastlane/fastlane#12042]
Referencing locked issue #https://github.com/fastlane/fastlane/issues/4606

## Observed Behavior
My `Framefile.json` has 4 fonts in the `Root > default > title > fonts` array.

If the Arabic font for language `ar` is **after** the latin font for languages `pt,...`, frameit tries to display the Arabic text with the latin font. This results in only question marks appearing, because the latin font has no Arabic letters.

If the Arabic font is **before** the latin font, it works fine. The same goes for other non-latin fonts like Thai and Korean.

## Expected behavior

The order of the fonts in the array shouldn't matter and the proper font for the supported language should be chosen.

## File

This is the working version, until the first font for `ar` is moved after the font for `pt,...`.
 
```
{
  "device_frame_version" : "latest",
  "default" : {
    "title" : {
      "fonts" : [
        {
          "font" : "./fonts/<...>.ttf",
          "supported" : [
            "ar"
          ]
        },
        {
          "font" : "./fonts/<...>.ttc",
          "supported" : [
            "zh-Hans",
            "zh-Hant",
            "ja"
          ]
        },
        {
          "font" : "./fonts/<...>.ttc",
          "supported" : [
            "pt",
            "it",
            "fr",
            "es",
            "en",
            "de",
            "vi",
            "tr"
          ]
        },
        {
          "font" : "./fonts/<...>.ttc",
          "supported" : [
            "ko"
          ]
        },
        {
          "font" : "./fonts/<...>.ttf",
          "supported" : [
            "th"
          ]
        }
      ]
    },
    "background" : "./background.png",
    "stack_title" : true,
    "title_below_image" : false,
    "show_complete_frame" : false,
    "font_scale_factor" : 0.15,
    "interline_spacing" : 30,
    "padding" : "30x80"
  },
  "data" : [
    {
      "filter" : "01",
      "keyword" : {
        "color" : "#d21559"
      }
    },
    {
      "filter" : "02",
      "keyword" : {
        "color" : "#feb909"
      }
    },
    {
      "filter" : "03",
      "keyword" : {
        "color" : "#aa4dbc"
      }
    },
    {
      "filter" : "04",
      "keyword" : {
        "color" : "#31bb48"
      }
    }
  ]
}
```

**Comment by mtrezza** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Fastlane-Screenshots")
    frame_screenshots(silver: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.myteam.MyApp") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2018-03-14**
</details>

**Comment by joshdholtz** [comment]
@mtrezza Are you able to send me your font files somehow? I would like to look into this one but do not have those specific font's you are having issues with 😊

**Comment by mtrezza** [comment]
@joshdholtz I can't send you the files but the fonts are:
ar: Bahij Myriad Arabic Bold
pt,..: Helvetica Neu
