### ISSUE TITLE
Percentage values (in prices) do work for some product pages but not for others

### ISSUE THREAD

**Issue by charl201** [fastlane/fastlane#12045]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<Hi everyone  i have an issue with my fastlane theme Could you help me please 
in fastlane theme, with shopify, my Percentage values (in prices) do work for some product pages but not for others
![fastlane issue](https://user-images.githubusercontent.com/37332802/37339618-8ac3890c-26bb-11e8-87cd-e0b7d8b369a1.png)>
</Do you have an idea ?>

**Comment by joshdholtz** [comment]
@charl201 Heyyy 👋 I think you have the wrong spot. This _fastlane_ is for the developer automation tool - not a theme 😊
