### ISSUE TITLE
Failure to run scan via bundle exec

### ISSUE THREAD

**Issue by paymand** [fastlane/fastlane#12056]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Greetings!

When I run `bundle exec fastlane action sigh` I get no error and a list of actions supported for `sigh`.
For `scan` however when I run `bundle exec fastlane action scan` I get an error which you can see below.

Good to know that it happens only when running with `bundle`, so if I run `fastlane action scan` I get no errors.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>$ bundle exec fastlane action scan
[✔] 🚀
[16:52:27]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
+-----------------------+---------+-----------+
|                Used plugins                 |
+-----------------------+---------+-----------+
| Plugin                | Version | Action    |
+-----------------------+---------+-----------+
| fastlane-plugin-badge | 1.0.0   | add_badge |
+-----------------------+---------+-----------+

Loading documentation for scan:

+-------------------------------------------------------------+
|                            scan                             |
+-------------------------------------------------------------+
| Alias for the `run_tests` action                            |
|                                                             |
| More information: https://docs.fastlane.tools/actions/scan/ |
|                                                             |
| Created by KrauseFx                                         |
+-------------------------------------------------------------+

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NameError: [!] uninitialized constant Scan::Options
Did you mean?  OptionParser
Did you mean?  OptionParser
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/actions/run_tests.rb:55:in `available_options'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/documentation/actions_list.rb:127:in `print_options'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/documentation/actions_list.rb:60:in `show_details'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/documentation/actions_list.rb:6:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/commands_generator.rb:243:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.85.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'</pre>
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests on one site"
  lane :test_unit do |options|
    # Safety check
    #ensure_git_status_clean 

    scheme = ENV['SCHEME_UNIT_TESTS']
    output_name = "unit_report.xml"
    scan(
      scheme: scheme,
      output_types: "junit",
      output_files: output_name,
      skip_slack: true
      )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
itc_team_id "xxx" # iTunes Connect Team ID
team_id "xxx" # Developer Portal Team ID
app_identifier "cxxx" # Generic App Identifier 
apple_id "xxx"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.1        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
| curb                      | 0.9.4        |
| badge                     | 0.8.7        |
| fastlane-plugin-badge     | 1.0.0        |
</details>

*generated on:* **2018-03-14**

**Comment by paymand** [comment]
@KrauseFx : I think I know what the problem is. You see I have `gem 'scan'` in my Pluginsfile and for some reason (tm) bundle installs version `0.0.1` which doesn't even seem to exist! base on what I see here: https://rubygems.org/gems/scan
So the only workaround for me is to specify the version number `gem 'scan', '1.0.0'` and then it all works. Don't know why we need to do that though.

**Comment by paymand** [comment]
Looks like there's a dependency conflict with between fastlane 2.85.0 and scan 1.0.0.
So they don't agree on the version of `slack-notifier`.
fastlane needs `slack-notifier < 3.0.0, >= 2.0.0` while scan needs `slack-notifier ~> 1.3`.

**Comment by paymand** [comment]
I have downgraded to 2.75.0 as a workaround for now.

**Comment by joshdholtz** [comment]
@paymand The `scan` gem is actually no longer needed anymore. `scan` is built inside of the `fastlane` gem now. Can you try removing `scan` from your Gemfile? That should solve the problem for you. 😊

**Comment by paymand** [comment]
Works like a charm! thanks :) Closing this issue.
