### ISSUE TITLE
'scan' should not run the 'build' action by default

### ISSUE THREAD

**Issue by kballard** [fastlane/fastlane#12050]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The default behavior of the `scan` action is to run `xcodebuild [options] build test`. The problem here is if the scheme specifies a different configuration for Run vs Test, this ends up building the project twice, once with the Run configuration and then again with the Test configuration.

I can't think of any reason why it should run the `build` action at all. The `test` action already builds what's necessary, so all this does is slow down the scan. If I want to do a debug build first, I should be using a separate action for that. As it is, the current behavior is surprising and penalizes anyone who uses the default configuration.

Reading through the code I noticed there's a config flag to skip the `build` action. So obviously someone realized the `build` was pointless, but they didn't go far enough. The config flag should be inverted so it only inserts `build` if explicitly instructed to. Since it looks like the config flags have default values, this could be accomplished simply by switching the default value of `:skip_build` to `true`.

**Comment by kballard** [comment]
Sorry bot, this issue doesn't need `fastlane env`, I double-checked the source already to confirm the issue.

**Comment by getaaron** [comment]
Hey @kballard, thanks for the issue. From memory, I think you’re right that the default build action is technically pointless in isolation but I think some people may rely on this behavior. So if we switch the default value of `skip_build`, we may want to think about failing in a helpful way later.

**Comment by joshdholtz** [comment]
I agree ^ Switching the default value of `skip_build` seems a little bit risky right now as it doesn't seem like its breaking things for a lot of people in its current implementation but switching it might cause a lot of breakage. I super appreciated you bringing this to our attention as I was not aware of this 😊 

I think I'm going to close this issue for now as this isn't something that is worth changing right now but we will definitely take a look at flipping this parameter in the future if it cause issues with what you raise above 👍

**Comment by getaaron** [comment]
I have a suggested solution for this; reopening
