### ISSUE TITLE
Error handling - method error_info not working

### ISSUE THREAD

**Issue by MobilityEngineer** [fastlane/fastlane#12069]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Anyone else getting the error that "undefined method error_info" See ouput details?

``` Ruby
error do |lane, exception|
	slack(
		slack_url: "XXXXXXX",
		message: exception.to_s,
		success: false,
		channel: "#random",
		payload:{
			"output" => exception.error_info.to_s
			}
		)
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[12:37:30]: An error occurred while executing the `error` block:
[12:37:30]: undefined method `error_info' for #FastlaneCore::Interface::FastlaneBuildFailure:0x007f86e9cb5418</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@MobilityEngineer Hey! So `exception.error_info.to_s` will only be a thing when an error occurs from a `UI.crash!` or `UI.user_error`. It looks like that your error that is being raised might be coming from something like `raise "Error"` and `error_info` doesn't exist on a Ruby `RuntimeError`. 

I will take this as an opportunity to fix the documentation around this and/or making sure that `error_info` always exists even for `raise "Error"` since this can lead to some confusion.

For now, do...
```rb
"output" => exception.to_s
```

**Comment by Scrat94** [comment]
@joshdholtz Hey! Thanks for the info. So there is currently no way to get the complete error message out of the console? e.g. I have intentionally added a typo error and all I get is "Error building the application - see the log above" (exception.to_s)
Is there any way to get a more detailed message, which I can share on e.g. Slack?
Much thanks in advance

**Comment by cpk1** [comment]
See this issue too: https://github.com/fastlane/fastlane/issues/11902#issuecomment-368125104 I've spent some time taking a look but unfortunately haven't got much further than understanding how the error reporting works.
From what I can see (for what I'm trying to address) the main issue is slack is picking up the error message here: https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L40
It looks like we could simply pass on for example the output from transporter when it fails (the see above that is mentioned) if here https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L102 we also returned all the errors printed out by transporter and added that to the pilot error message.

My focus has obviously been on getting useful errors from Pilot and it looks like you are having a problem with a different tool, so what I've been looking at doing might be too specific to Pilot if this is something that happens a lot in other Fastlane tools as well.

**Comment by joshdholtz** [comment]
@Scrat94 The object being passed into the block is a standard Ruby "error" object so you should be able to get relevant information from that. You can get the stacktrace like this...

```rb
error do |lane, exception|
  puts "something happened: #{exception.to_s}"
  puts "stacktrace: #{exception.backtrace}"
end
```

What else are you looking to do?

**Comment by MobilityEngineer** [comment]
@joshdholtz I give you an example. I intentionally did a typo error. The error message in the jenkins console log looks like this: 

**Expected Error message**
<details>
<pre>
> Cleaning testci/testci [Release]
> Check Dependencies
> Clean Succeeded
> Building testci/testci [Release]
> Check Dependencies

[x] /Users/Shared/Jenkins/Home/workspace/ios-test-build-pipeline/testci/ViewController.swift:22:5: expected declaration

h
    ^


** ARCHIVE FAILED **


The following build commands failed:
CompileSwift normal armv7
CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(2 failures)
[12:37:30]: Exit status: 65
</pre>
</details>

The message: "`/Users/Shared/Jenkins/Home/workspace/ios-test-build-pipeline/testci/ViewController.swift:22:5: expected declaration` " -> This one  I would expect as the exception message, so its directly clear for the develoepr whats wrong. 


Instead I get a meaningless Message such as:

**Actual Error message with exception.to_s**
<details>
<pre>
[12:37:30]: Error building the application - see the log above
</pre>
</details>

**Comment by joshdholtz** [comment]
@MobilityEngineer That is output coming directly from the `xcodebuild` tool which cannot be nicely formatted into a Ruby exception with stacktrace

**Comment by MobilityEngineer** [comment]
@joshdholtz okay thanks for clarification. I think then its the best way to just link to the console output in Jenkins...

Nevertheless it would be so great if we could have a meaningful error message.

**Comment by joshdholtz** [comment]
@MobilityEngineer Being able to parse the `xcodebuild` output for exactly the most meaningful message is easier said than done 🙃 The output has thousands of lines of code and really could be anything. We have some higher priority things to fix but if you would like to take a stab at this and submit a PR with what you are expecting to show, we would be happy to accept up 👍

**Comment by MobilityEngineer** [comment]
@joshdholtz yea I got that point. My original question was more related to the issue #6292 - so I thought there would be already a way to receive detailed error messages..

**Comment by joshdholtz** [comment]
@MobilityEngineer Yeah, I don't think we put the `xcodebuild` output in that error that gets raised because it would be hundred or thousands of lines long. You may have to do something a little more custom to get that working.
