### ISSUE TITLE
[question] - update_info_plist update multiple keys

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#12072]
Is there a way to update multiple keys in Info.plist using `update_info_plist`?

Currently I can update a key using the following code:
```
update_info_plist(
      plist_path: plist_path,
      block: lambda { |plist|
               plist[:key_name1] = key_value1
             }
    )
```

However we can not update multiple keys in the `block` like this:
```
update_info_plist(
      plist_path: plist_path,
      block: lambda { |plist|
               plist[:key_name1] = key_value1
               plist[:key_name2] = key_value2
             }
    )
```

I have to resort to calling `update_info_plist` twice. first time for updating `key_name1`, second time for updating `key_name2`.

**Comment by joshdholtz** [comment]
There is not but feel free to implement this if you'd like 😊

**Comment by RishabhTayal** [comment]
@joshdholtz I just tried setting two key values with one command and it worked for me this time 🤷‍♂️. Not sure what happened before. Looks like it IS supported by the action. Going to close this issue for now.
