### ISSUE TITLE
Spaceship's Client can't make a "create" request until after a "get" request

### ISSUE THREAD

**Issue by sergiocampama** [fastlane/fastlane#12070]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Spaceship's client will fail to make a "create" request (like `PortalClient#create_app!` method) until after executing a "get" request (like `PortalClient#teams`). After checking the difference in the failure or success requests using Charles proxy, a request like `teams` configures the `Csrf` and `Csrf_ts` headers. Without these, "create" requests will fail to succeed.

It would simplify things if after doing `login`, the client would test it's connectivity with a simple request like `teams`, which would also configure the required `Csrf` for future requests.

Workaround for now is to directly call `teams` after `login`.

**Comment by joshdholtz** [comment]
@sergiocampama Is this only an error really when calling the spaceship API directly? Word another way - are actions that use spaceship probably okay since they all _should_ prompt for team? 🤔

**Comment by sergiocampama** [comment]
Yes, this is when using the client objects directly. Please refer to the other 2 issues I have opened on using the portal client directly:

#11901 and #11816

**Comment by joshdholtz** [comment]
Thanks for linking those! This is definitely something I saw that needed improving too when exploring through the codebase this past weekend too 💡

**Comment by sergiocampama** [comment]
still open
