### ISSUE TITLE
fastlane-plugin-badge: Can't search for app icons if they are not in sub folder

### ISSUE THREAD

**Issue by ngouass** [fastlane/fastlane#12074]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
- [x] Using fastlane **2.85.0**
- [x] Using fastlane-plugin-badge **1.0.0**

Based on the documentation of the [badge package](https://github.com/HazAT/badge) - *Usage section*,

 I understood that **fastlane-plugin-badge**:

> It will search all subfolders for your asset catalog app icon set and add the badge to the icons.

that will work with the following folder tree:
![capture d ecran 2018-03-17 a 02 04 23](https://user-images.githubusercontent.com/17073855/37550057-8e5dc180-2987-11e8-87d5-77532a620451.png)

But not with this one:
![capture d ecran 2018-03-17 a 02 07 05](https://user-images.githubusercontent.com/17073855/37550083-e9698a46-2987-11e8-855d-0bf4e92071f0.png)
(I choose to use this folder structure is order to be able to isolate iOS and Android Fastfile)

I was wondering if there were a way to specify the root path for the search like it were possible to do with the **[deprecated]** - fastlane action [*badge*](https://docs.fastlane.tools/actions/badge/).

My goal:
![capture d ecran 2018-03-17 a 02 11 15](https://user-images.githubusercontent.com/17073855/37550131-81c03f42-2988-11e8-9d3e-367f7eecdd0c.png)

**Comment by ngouass** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.5.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.85.0"

default_platform :ios

# iOS platform
platform :ios do

  desc "Add badge to app icon"
  lane :add_badge_to_icon do
    add_badge(
      dark: true,
      path: '~/test/ios/',
      glob: "/**/*.appiconset/*.{png,PNG}"
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "${appIdentifier}" # The bundle identifier of your app
apple_id "${dev_id}" # Your Apple email address
team_id "[[DEV_PORTAL_TEAM_ID]]" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.12.0  | ✅ Up-To-Date  |
| fastlane-plugin-badge   | 1.0.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.4        |
| fastimage                 | 2.1.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.2.1        |
| excon                     | 0.61.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.8.7        |
| fastlane-plugin-appicon   | 0.12.0       |
| fastlane-plugin-badge     | 1.0.0        |
</details>


*generated on:* **2018-03-17**
</details>

**Comment by nicolasbraun** [comment]
@ngouass  
The code behind the plugin as an option for that 
https://github.com/HazAT/badge/blob/4c6f17c89120c855871ed1a89384d31694b4bfc1/lib/badge/options.rb#L61
did you try it ?

**Comment by ngouass** [comment]
@nicolasbraun 
I tried that option and it didn't work.

```
  desc "Add badge to app icon"
  lane :add_badge_to_icon do
    add_badge(
      dark: true,
      glob: "~/test/ios/test/Images.xcassets/AppIcon.appiconset/*.{png,PNG}"
    )
  end
```

**Comment by joshdholtz** [comment]
@ngouass I would create an issue over at https://github.com/HazAT/fastlane-plugin-badge 😊 There isn't anything we can do directly since this is a third-party plugin. Hopefully creating an issue over there will help you out!
