### ISSUE TITLE
Is it possiable for fastlane to auto download all crash logs and dsym them?

### ISSUE THREAD

**Issue by rcmpayne** [fastlane/fastlane#12089]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currenlty with Xcode -> Organizer, you have to select each version of your app for it to download the crash data. Can fastlane automate this so i can 1) script it to auto download all crash data for all versions as they exist and 2) be able to dsym them after using fastlane refresh_dsyms?

**Comment by joshdholtz** [comment]
@rcmpayne We do not currently have this feature in fastlane. Just curious (since I don't use those very heavily) but how would you be planning to view/use the logs after downloading them with fastlane? 😊
