### ISSUE TITLE
Difference between app_apk_path and tests_apk_path

### ISSUE THREAD

**Issue by mueller-ma** [fastlane/fastlane#12082]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
From the docs:

app_apk_path | The path to the APK for the app under test 
-- | -- 
tests_apk_path | The path to the APK for the the tests bundle 

Which apk do I have to use for those two arguments? Can I use the same apk for both?

**Comment by joshdholtz** [comment]
@mueller-ma Heyyy! I'm assuming you are talking about 'screengrab` or `android_capture_screenshot` here? These cannot be the same. `app_apk_path` is for your main app code (this is the APK that would get uploaded to Google Play). `tests_apk_path` is a separate APK that is generated with your JUnit tests in it that control your screenshooting. See my two images below on how my example generates two APKs. 

<img width="1402" alt="screen shot 2018-03-21 at 1 55 01 pm" src="https://user-images.githubusercontent.com/401294/37731198-79cc66b4-2d0f-11e8-9939-c30a11167f5f.png">
<img width="1414" alt="screen shot 2018-03-21 at 1 54 56 pm" src="https://user-images.githubusercontent.com/401294/37731199-79dc199c-2d0f-11e8-9ed6-7864426098ed.png">

**Comment by mueller-ma** [comment]
Thanks for your answer. Why does screengrab need both apks? If I run `./gradlew assembleAndroidTest`, I have an apk with the "normal" code plus the Android tests code, don't I?

**Comment by joshdholtz** [comment]
@mueller-ma One APK is your actually code. The other is essentially a "runner" that runs through your app (main APK) with tests (secondary APK). Its just how android works 🙃

**Comment by mueller-ma** [comment]
Thanks. Can you add those information to the docs? And remove one "the" in "The path to the APK for the the tests bundle"
