### ISSUE TITLE
upload_symbols_to_crashlytics action fails on unzip errors

### ISSUE THREAD

**Issue by Istered** [fastlane/fastlane#12081]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

For some of my projects with bitcode support iTunes Connect provides archived dSYMs which cannot be unzipped properly, at least it seems like that. Every time `upload_symbols_to_crashlytics` tries to invoke `unzip` command it fails with `invalid byte sequence in UTF-8` error message, but, in fact, some of the dSYMs were actually unzipped. However, since `unzip` returns an error code instead of 0 `sh` action throws an error, so none of those successfully unzipped dSYMs are going to be uploaded.

I've ran some tests in terminal with `unzip -qo` and manually downloaded dSYMs, just to make sure this is not the problem of `download_dsyms` or any other part of Fastlane.

So, my question is: could we add some kind of `fail_on_unzip_errors` parameter which will be set to `true` by default to `upload_symbols_to_crashlytics` action and wrap `Actions.sh("unzip -qo #{current_path.shellescape}")` with `begin/rescue` block?
Something like this:
```ruby
begin
  Actions.sh("unzip -qo #{current_path.shellescape}")
rescue => ex
  UI.user_error!(ex.to_s) if params[:fail_on_unzip_errors]
end
```

Maybe there is a better way to workaround the problem I have, but It would be better if `upload_symbols_to_crashlytics ` could handle such situations by itself. Thanks in advance!

<details>
  <pre>
INFO [2018-03-18 13:34:19.95]: --------------------------------------------------
INFO [2018-03-18 13:34:19.95]: --- Step: custom_upload_symbols_to_crashlytics ---
INFO [2018-03-18 13:34:19.95]: --------------------------------------------------
INFO [2018-03-18 13:34:19.96]: Extracting '/Users/usrname/Projects/project/project.dSYM.zip'...
INFO [2018-03-18 13:34:19.96]: $ unzip -qo /Users/usrname/Projects/project/project.dSYM.zip
ERROR [2018-03-18 13:34:20.01]: invalid byte sequence in UTF-8
 </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/lib/ruby/gems/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| rake                      | 12.3.0       |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| json-schema               | 2.8.0        |
</details>

*generated on:* **2018-03-18**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@Istered Hey 👋 Just wanted to clarify from your description but you manually downloaded dSYMs from iTC and tried to manually unzip them and that was failing for you too, right?

**Comment by Istered** [comment]
Hi @joshdholtz. Yep, I tried to manually download dSYMs and then unzip them using `unzip -qo` command in the terminal to make sure I'll get the same result as for `upload_symbols_to_crashlytics`. Just to clarify, it wasn't failing, not completely, at least. In fact, it did extract most of the dSYMs, but since it had some errors during extraction `unzip` produced an error code. As expected, that code was processed as an error by Fastlane.

I understand that it's intended to raise an exception if `Action.sh` fails, but at the same time, I wish I could proceed with uploading with successfully unzipped dSYMs.

**Comment by joshdholtz** [comment]
@Istered This may be weird but would you be able to let me use your dSYM zip so that I can debug this and fix it (at least the failing zip file) 😊 This shouldn't be happening. Totes okay if you don't feel comfortable (I can try to generate a failing one myself). But if you don't mind, can you email it to the email on my GitHub profile?

**Comment by Istered** [comment]
@joshdholtz Sure :)

**Comment by joshdholtz** [comment]
@Istered Got the email!! Will look into this today/tomorrow 🙃

**Comment by Istered** [comment]
@fastlane-bot Tried with the latest fastlane, but still have this issue.

**Comment by Istered** [comment]
Hi @joshdholtz! Any update on this issue?

**Comment by joshdholtz** [comment]
Heyyyy! This is on my list still 😊 Hoping to get to it this week. Thanks for the ping ❤️

**Comment by joshdholtz** [comment]
@Istered Heyyy, I just got around to testing this and everything seemed to work with that zip file of dSYMs that you sent me 🤔 I'm curious if the `invalid byte sequence in UTF-8` error was happening with the path that gets passed into the `unzip` call? Does your path have any non-`UTF-8` characters in it?

Also, can you try setting the environment variables for `LC_ALL ` and `LANGUAGE ` to `en_US.UTF-8` to see if that helps?

**Comment by Istered** [comment]
Also, I found this thread https://discussions.apple.com/thread/8209482. Might be related to this issue somehow
