### ISSUE TITLE
Unable to delete groups in Testflight via spaceship

### ISSUE THREAD

**Issue by kkw4** [fastlane/fastlane#12094]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently spaceship testflight is able to create new groups which we can then add testers to. Groups can be setup for different sets of users who will be testing the app on testflight. However, we have seen that overtime, the number of groups can grow and rather than performing manual group deletion via the iTunes connect UI (error prone and tedious), there should be functionality in spaceship which should allow us to delete groups which are no longer needed. This would allow further automation and would create huge savings.

We are unable to find the testflight group deletion methods in spaceship.
This is something that we can contribute. I'll submit a PR for this.

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-ruby        | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-clubmate    | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-slack_train | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| bundler                     | 1.16.1       |
| io-console                  | 0.4.5        |
| psych                       | 2.1.0        |
| rake                        | 11.3.0       |
| CFPropertyList              | 2.3.6        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.5.2        |
| ast                         | 2.4.0        |
| atomos                      | 0.1.2        |
| babosa                      | 1.0.2        |
| debug_inspector             | 0.0.3        |
| binding_of_caller           | 0.8.0        |
| builder                     | 3.2.3        |
| byebug                      | 10.0.0       |
| claide                      | 1.0.2        |
| colored2                    | 3.1.2        |
| cork                        | 0.3.0        |
| nap                         | 1.1.0        |
| open4                       | 1.3.4        |
| claide-plugins              | 0.9.2        |
| coderay                     | 1.1.2        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| json                        | 2.1.0        |
| docile                      | 1.1.5        |
| simplecov-html              | 0.10.2       |
| simplecov                   | 0.14.1       |
| tins                        | 1.16.3       |
| term-ansicolor              | 1.6.0        |
| thor                        | 0.19.4       |
| coveralls                   | 0.8.21       |
| safe_yaml                   | 1.0.4        |
| crack                       | 0.4.3        |
| multipart-post              | 2.0.0        |
| faraday                     | 0.14.0       |
| faraday-http-cache          | 1.3.1        |
| git                         | 1.3.0        |
| kramdown                    | 1.16.2       |
| sawyer                      | 0.8.1        |
| octokit                     | 4.8.0        |
| unicode-display_width       | 1.3.0        |
| terminal-table              | 1.8.0        |
| danger                      | 4.3.5        |
| ox                          | 2.9.0        |
| danger-junit                | 0.7.4        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| diff-lcs                    | 1.3          |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20170404 |
| dotenv                      | 2.2.1        |
| excon                       | 0.61.0       |
| fakefs                      | 0.8.1        |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.12.2       |
| fastimage                   | 2.1.1        |
| gh_inspector                | 1.1.3        |
| jwt                         | 2.1.0        |
| little-plugger              | 1.1.4        |
| multi_json                  | 1.13.1       |
| logging                     | 2.2.2        |
| memoist                     | 0.16.0       |
| os                          | 0.9.6        |
| signet                      | 0.8.1        |
| googleauth                  | 0.6.2        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2016.0521  |
| mime-types                  | 3.1          |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.1        |
| google-api-client           | 0.13.6       |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.4.0        |
| rubyzip                     | 1.2.1        |
| security                    | 0.1.3        |
| naturally                   | 2.1.0        |
| simctl                      | 1.6.2        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 1.8.0        |
| tty-screen                  | 0.6.4        |
| tty-cursor                  | 0.5.0        |
| tty-spinner                 | 0.8.0        |
| word_wrap                   | 1.0.0        |
| nanaimo                     | 0.2.3        |
| xcodeproj                   | 1.5.6        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.2.8        |
| xcpretty-travis-formatter   | 1.0.0        |
| fastlane-plugin-clubmate    | 0.1.0        |
| fastlane-plugin-ruby        | 0.1.3        |
| fastlane-plugin-slack_train | 0.2.0        |
| hashdiff                    | 0.3.7        |
| interception                | 0.5          |
| method_source               | 0.9.0        |
| netrc                       | 0.11.0       |
| parallel                    | 1.12.1       |
| parser                      | 2.5.0.4      |
| powerpack                   | 0.1.1        |
| pry                         | 0.11.3       |
| pry-byebug                  | 3.6.0        |
| pry-rescue                  | 1.4.5        |
| pry-stack_explorer          | 0.4.9.2      |
| rack                        | 1.6.9        |
| rack-protection             | 1.5.5        |
| rainbow                     | 2.2.2        |
| rb-readline                 | 0.5.5        |
| rest-client                 | 2.0.2        |
| rspec-support               | 3.5.0        |
| rspec-core                  | 3.5.4        |
| rspec-expectations          | 3.5.0        |
| rspec-mocks                 | 3.5.0        |
| rspec                       | 3.5.0        |
| rspec_junit_formatter       | 0.2.3        |
| ruby-progressbar            | 1.9.0        |
| rubocop                     | 0.49.1       |
| rubocop-require_tools       | 0.1.2        |
| tilt                        | 2.0.8        |
| sinatra                     | 1.4.8        |
| webmock                     | 2.3.2        |
| xcode-install               | 2.3.1        |
| yard                        | 0.9.12       |
</details>

**Comment by pparmaei** [comment]
+1. This would be a great feature
