### ISSUE TITLE
fastlane download_dsyms Unknown method 'train_number'

### ISSUE THREAD

**Issue by zhengjianing** [fastlane/fastlane#12101]
fastlane_version "2.86.0"

action: download_dsyms(version: "1.0.0") 

### Issue Description

******version_set=nil>, comparing to supplied version: 3.0.3
ERROR [2018-03-20 15:02:02.68]: Unknown method 'train_number'
WARN [2018-03-20 15:02:02.68]: Lane Context:
INFO [2018-03-20 15:02:02.68]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios refresh_dsyms"}
ERROR [2018-03-20 15:02:02.68]: To call another action from an action use `other_action.train_number` instead

**Comment by joshdholtz** [comment]
This was fixed in `2.86.1` 😊
