### ISSUE TITLE
Xcov fails due to invalid 'xcconfig' argument

### ISSUE THREAD

**Issue by ndonald2** [fastlane/fastlane#12103]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I recently updated to the latest version of fastlane and my test command broke, failing on the `xcov` step. I also updated `xcov` to the latest in hopes that it would fix the issue, but to no avail. It's complaining about an extra invalid `xcconfig` argument, but I am providing no such argument. I suspect it may be related to #12067 but it's a bit beyond me.

Full output below as requested, with sensitive info redacted, but here is the relevant output:

```
[11:04:38]: ------------------
[11:04:38]: --- Step: xcov ---
[11:04:38]: ------------------

+-----------------------------+--------------------------------------------------+
|                             Summary for xcov 1.3.3                             |
+-----------------------------+--------------------------------------------------+
| workspace                   | betterup.xcworkspace                             |
| scheme                      | betterup-prod                                    |
| output_directory            | xcov_output                                      |
| skip_slack                  | true                                             |
| include_targets             | betterup.app,BUAPI.framework,Utilities.framework |
| html_report                 | true                                             |
| markdown_report             | false                                            |
| json_report                 | false                                            |
| minimum_coverage_percentage | 0                                                |
| slack_username              | xcov                                             |
| slack_message               | Your *xcov* coverage report                      |
| ignore_file_path            | ./fastlane/.xcovignore                           |
| include_test_targets        | false                                            |
| only_project_targets        | false                                            |
+-----------------------------+--------------------------------------------------+

+----------------------------+------------------------------------------------------------------------------------------------------+
|                                                           Lane Context                                                            |
+----------------------------+------------------------------------------------------------------------------------------------------+
| VERSION_NUMBER             | 3.19.0                                                                                               |
| PLATFORM_NAME              |                                                                                                      |
| LANE_NAME                  | test                                                                                                 |
| SCAN_DERIVED_DATA_PATH     | /Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx                |
| SCAN_GENERATED_PLIST_FILES | ["/Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx/Logs/Test/9  |
|                            | 062A64B-814F-4AA3-83D8-904C160563D3_TestSummaries.plist"]                                            |
| SCAN_GENERATED_PLIST_FILE  | /Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx/Logs/Test/906  |
|                            | 2A64B-814F-4AA3-83D8-904C160563D3_TestSummaries.plist                                                |
+----------------------------+------------------------------------------------------------------------------------------------------+
[11:04:39]: Could not find option 'xcconfig' in the list of available options: workspace, project, scheme, configuration, source_directory, derived_data_path, output_directory, html_report, markdown_report, json_report, minimum_coverage_percentage, slack_url, slack_channel, skip_slack, slack_username, slack_message, ignore_file_path, include_test_targets, exclude_targets, include_targets, only_project_targets, coveralls_service_name, coveralls_service_job_id, coveralls_repo_token

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | get_version_number    | 0           |
| 2    | clean_build_artifacts | 0           |
| 3    | setup_circle_ci       | 0           |
| 4    | scan                  | 49          |
| 💥   | xcov                  | 0           |
+------+-----------------------+-------------+

[11:04:39]: fastlane finished with errors

[!] Could not find option 'xcconfig' in the list of available options: workspace, project, scheme, configuration, source_directory, derived_data_path, output_directory, html_report, markdown_report, json_report, minimum_coverage_percentage, slack_url, slack_channel, skip_slack, slack_username, slack_message, ignore_file_path, include_test_targets, exclude_targets, include_targets, only_project_targets, coveralls_service_name, coveralls_service_job_id, coveralls_repo_token
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
+-------------------------------------------------------+---------+---------------------------------------+
|                                              Used plugins                                               |
+-------------------------------------------------------+---------+---------------------------------------+
| Plugin                                                | Version | Action                                |
+-------------------------------------------------------+---------+---------------------------------------+
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.1   | get_unprovisioned_devices_from_hockey |
| fastlane-plugin-badge                                 | 1.0.0   | add_badge                             |
+-------------------------------------------------------+---------+---------------------------------------+

[11:03:49]: --------------------------------
[11:03:49]: --- Step: get_version_number ---
[11:03:49]: --------------------------------
[11:03:49]: Driving the lane 'test' 🚀
[11:03:49]: -----------------------------------
[11:03:49]: --- Step: clean_build_artifacts ---
[11:03:49]: -----------------------------------
[11:03:49]: Cleaned up build artifacts 🐙
[11:03:49]: -----------------------------
[11:03:49]: --- Step: setup_circle_ci ---
[11:03:49]: -----------------------------
[11:03:49]: Not running on CI, skipping `setup_circle_ci`
[11:03:49]: ------------------
[11:03:49]: --- Step: scan ---
[11:03:49]: ------------------
[11:03:49]: Successfully loaded '/Users/nick/Developer/betterup-ios/fastlane/Scanfile' 📄

+------------------------+-------------------+
| Detected Values from './fastlane/Scanfile' |
+------------------------+-------------------+
| scheme                 | betterup-prod     |
| device                 | iPhone 8          |
| open_report            | false             |
| skip_slack             | true              |
| output_types           | html,junit        |
| include_simulator_logs | false             |
+------------------------+-------------------+

[11:03:49]: $ xcodebuild -showBuildSettings -workspace ./betterup.xcworkspace -scheme betterup-prod
[11:03:52]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[11:03:56]: Successfully loaded '/Users/nick/Developer/betterup-ios/fastlane/Scanfile' 📄

+------------------------+-------------------+
| Detected Values from './fastlane/Scanfile' |
+------------------------+-------------------+
| scheme                 | betterup-prod     |
| device                 | iPhone 8          |
| open_report            | false             |
| skip_slack             | true              |
| output_types           | html,junit        |
| include_simulator_logs | false             |
+------------------------+-------------------+

[11:03:56]: $ xcodebuild -showBuildSettings -workspace ./betterup.xcworkspace -scheme betterup-prod
[11:03:59]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...

+------------------------+---------------------------------------------------------------------------------------+
|                                            Summary for scan 2.86.0                                             |
+------------------------+---------------------------------------------------------------------------------------+
| xcargs                 | CI=                                                                                   |
| clean                  | false                                                                                 |
| workspace              | ./betterup.xcworkspace                                                                |
| derived_data_path      | /Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx |
| device                 | iPhone 8                                                                              |
| scheme                 | betterup-prod                                                                         |
| skip_build             | false                                                                                 |
| output_directory       | ./fastlane/test_output                                                                |
| output_types           | html,junit                                                                            |
| buildlog_path          | ~/Library/Logs/scan                                                                   |
| include_simulator_logs | false                                                                                 |
| open_report            | false                                                                                 |
| skip_slack             | true                                                                                  |
| slack_only_on_failure  | false                                                                                 |
| use_clang_report_name  | false                                                                                 |
| fail_build             | true                                                                                  |
| xcode_path             | /Applications/Xcode9.2/Xcode.app                                                      |
+------------------------+---------------------------------------------------------------------------------------+

[11:04:02]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./betterup.xcworkspace -scheme betterup-prod -destination 'platform=iOS Simulator,id=31BF0269-3177-48CA-A53C-621AA077B53A' -derivedDataPath '/Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx' CI= build test | tee '/Users/nick/Library/Logs/scan/betterup-betterup-prod.log' | xcpretty  --report html --output '/Users/nick/Developer/betterup-ios/fastlane/test_output/report.html' --report junit --output '/Users/nick/Developer/betterup-ios/fastlane/test_output/report.junit' --report junit --output '/var/folders/s_/mf_hdvsx5g718vr0ngksv44r0000gn/T/junit_report20180320-50857-1hm3tpy'

... lots of build and test output redacted here ...

+--------------------+-----+
|       Test Results       |
+--------------------+-----+
| Number of tests    | 760 |
| Number of failures | 0   |
+--------------------+-----+

[11:04:38]: ------------------
[11:04:38]: --- Step: xcov ---
[11:04:38]: ------------------

+-----------------------------+--------------------------------------------------+
|                             Summary for xcov 1.3.3                             |
+-----------------------------+--------------------------------------------------+
| workspace                   | betterup.xcworkspace                             |
| scheme                      | betterup-prod                                    |
| output_directory            | xcov_output                                      |
| skip_slack                  | true                                             |
| include_targets             | betterup.app,BUAPI.framework,Utilities.framework |
| html_report                 | true                                             |
| markdown_report             | false                                            |
| json_report                 | false                                            |
| minimum_coverage_percentage | 0                                                |
| slack_username              | xcov                                             |
| slack_message               | Your *xcov* coverage report                      |
| ignore_file_path            | ./fastlane/.xcovignore                           |
| include_test_targets        | false                                            |
| only_project_targets        | false                                            |
+-----------------------------+--------------------------------------------------+

+----------------------------+------------------------------------------------------------------------------------------------------+
|                                                           Lane Context                                                            |
+----------------------------+------------------------------------------------------------------------------------------------------+
| VERSION_NUMBER             | 3.19.0                                                                                               |
| PLATFORM_NAME              |                                                                                                      |
| LANE_NAME                  | test                                                                                                 |
| SCAN_DERIVED_DATA_PATH     | /Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx                |
| SCAN_GENERATED_PLIST_FILES | ["/Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx/Logs/Test/9  |
|                            | 062A64B-814F-4AA3-83D8-904C160563D3_TestSummaries.plist"]                                            |
| SCAN_GENERATED_PLIST_FILE  | /Users/nick/Library/Developer/Xcode/DerivedData/betterup-hfuebyfhccmkupajsoyduchwtxzx/Logs/Test/906  |
|                            | 2A64B-814F-4AA3-83D8-904C160563D3_TestSummaries.plist                                                |
+----------------------------+------------------------------------------------------------------------------------------------------+
[11:04:39]: Could not find option 'xcconfig' in the list of available options: workspace, project, scheme, configuration, source_directory, derived_data_path, output_directory, html_report, markdown_report, json_report, minimum_coverage_percentage, slack_url, slack_channel, skip_slack, slack_username, slack_message, ignore_file_path, include_test_targets, exclude_targets, include_targets, only_project_targets, coveralls_service_name, coveralls_service_job_id, coveralls_repo_token

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | get_version_number    | 0           |
| 2    | clean_build_artifacts | 0           |
| 3    | setup_circle_ci       | 0           |
| 4    | scan                  | 49          |
| 💥   | xcov                  | 0           |
+------+-----------------------+-------------+

[11:04:39]: fastlane finished with errors

[!] Could not find option 'xcconfig' in the list of available options: workspace, project, scheme, configuration, source_directory, derived_data_path, output_directory, html_report, markdown_report, json_report, minimum_coverage_percentage, slack_url, slack_channel, skip_slack, slack_username, slack_message, ignore_file_path, include_test_targets, exclude_targets, include_targets, only_project_targets, coveralls_service_name, coveralls_service_job_id, coveralls_repo_token
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.13.3                                              |
| Ruby                        | 2.4.2                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.16.2                                   |
| Installation Source         | bin/fastlane                                         |
| Host                        | Mac OS X 10.13.3 (17D102)                            |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode9.2/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>Relevant portion of `./fastlane/Fastfile`</summary>

```ruby
desc """
  Runs tests and gathers code coverage
  Skip code coverage using `skip_coverage:true`
"""
lane :test do |options|
  # only clean first if running in CI
  scan(xcargs: "CI=#{CI}", clean: CI)
  if not options[:skip_coverage] ||= false
    included_targets = [
      'betterup.app',
      'BUAPI.framework',
      'Utilities.framework'
    ]
    xcov(
      workspace: WORKSPACE_PATH,
      scheme: "betterup-prod",
      output_directory: "xcov_output",
      skip_slack: true,
      include_targets: included_targets.join(',')
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier 'co.betterup.betterup'
apple_id ENV['APPLE_ID']
team_name 'REDACTED'
team_id 'REDACTED'
```

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-badge                                 | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.1.0        |
| bundler                                               | 1.16.0       |
| io-console                                            | 0.4.6        |
| CFPropertyList                                        | 2.3.6        |
| concurrent-ruby                                       | 1.0.5        |
| i18n                                                  | 0.9.3        |
| minitest                                              | 5.11.3       |
| thread_safe                                           | 0.3.6        |
| tzinfo                                                | 1.2.4        |
| activesupport                                         | 4.2.10       |
| public_suffix                                         | 2.0.5        |
| addressable                                           | 2.5.2        |
| atomos                                                | 0.1.2        |
| babosa                                                | 1.0.2        |
| curb                                                  | 0.9.4        |
| fastimage                                             | 2.1.1        |
| colored                                               | 1.2          |
| highline                                              | 1.7.10       |
| commander-fastlane                                    | 4.4.6        |
| dotenv                                                | 2.2.1        |
| excon                                                 | 0.61.0       |
| multipart-post                                        | 2.0.0        |
| faraday                                               | 0.14.0       |
| unf_ext                                               | 0.0.7.5      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20170404 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| faraday_middleware                                    | 0.12.2       |
| gh_inspector                                          | 1.1.3        |
| jwt                                                   | 2.1.0        |
| little-plugger                                        | 1.1.4        |
| multi_json                                            | 1.13.1       |
| logging                                               | 2.2.2        |
| memoist                                               | 0.16.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.8.1        |
| googleauth                                            | 0.6.2        |
| httpclient                                            | 2.8.3        |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| declarative                                           | 0.0.10       |
| declarative-option                                    | 0.1.0        |
| uber                                                  | 0.1.0        |
| representable                                         | 3.0.4        |
| retriable                                             | 3.1.1        |
| google-api-client                                     | 0.13.6       |
| json                                                  | 2.1.0        |
| mini_magick                                           | 4.5.1        |
| multi_xml                                             | 0.6.0        |
| plist                                                 | 3.4.0        |
| rubyzip                                               | 1.2.1        |
| security                                              | 0.1.3        |
| naturally                                             | 2.1.0        |
| simctl                                                | 1.6.2        |
| slack-notifier                                        | 2.3.2        |
| terminal-notifier                                     | 1.8.0        |
| unicode-display_width                                 | 1.3.0        |
| terminal-table                                        | 1.8.0        |
| tty-screen                                            | 0.6.4        |
| tty-cursor                                            | 0.5.0        |
| tty-spinner                                           | 0.8.0        |
| word_wrap                                             | 1.0.0        |
| claide                                                | 1.0.2        |
| colored2                                              | 3.1.2        |
| nanaimo                                               | 0.2.3        |
| xcodeproj                                             | 1.5.6        |
| rouge                                                 | 2.0.7        |
| xcpretty                                              | 0.2.8        |
| xcpretty-travis-formatter                             | 1.0.0        |
| badge                                                 | 0.8.7        |
| fuzzy_match                                           | 2.0.4        |
| nap                                                   | 1.1.0        |
| cocoapods-core                                        | 1.4.0        |
| cocoapods-deintegrate                                 | 1.0.2        |
| cocoapods-downloader                                  | 1.1.3        |
| cocoapods-plugins                                     | 1.0.0        |
| cocoapods-search                                      | 1.0.0        |
| cocoapods-stats                                       | 1.0.0        |
| netrc                                                 | 0.11.0       |
| cocoapods-trunk                                       | 1.3.0        |
| cocoapods-try                                         | 1.1.0        |
| escape                                                | 0.0.4        |
| fourflusher                                           | 2.0.1        |
| molinillo                                             | 0.6.4        |
| ruby-macho                                            | 1.1.0        |
| cocoapods                                             | 1.4.0        |
| fastlane-plugin-badge                                 | 1.0.0        |
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.1        |
| sawyer                                                | 0.8.1        |
| octokit                                               | 4.8.0        |
| xcov                                                  | 1.3.3        |
</details>

*generated on:* **2018-03-20**
</details>

**Comment by joshdholtz** [comment]
Hello! The xcodeproj issues just got merged (https://github.com/fastlane/fastlane/pull/12147) so this should be fixed in next release 🙃

**Comment by joshdholtz** [comment]
Actually, let me verify one more thing quick 😊

**Comment by joshdholtz** [comment]
@ndonald2 Actually, can you try updating to xcov gem to  `1.3.5`? This should fix it for you now 💪

**Comment by ndonald2** [comment]
Yep that did it! Thanks! 👍
