### ISSUE TITLE
Could not set changelog: `build_id` is a required parameter

### ISSUE THREAD

**Issue by nikitaame** [fastlane/fastlane#12110]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running fastlane to try to distribute our builds to external testers via TestFlight using:

`  options = {
    username: "username",
    distribute_external: true,
    groups: external_groups,
    beta_app_feedback_email: "email",
    changelog: "Build #{version_name} is now ready for testing.",
    app_identifier: app_identifier,
    app_platform: "ios"
  }
  Pilot::BuildManager.new.distribute(options)`

This has been working just fine until just recently we have been receiving the error message:

> Could not set changelog: `build_id` is a required parameter

Seeing in the log that before that (which I know many have seen as a common problem with incorrectly using pilot):

> Successfully set the beta_app_feedback_email and/or beta_app_description

I don't see any sort of `build_id` parameter btw from your docs: https://docs.fastlane.tools/actions/set_changelog/

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>
### Stack
| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 10.13.3                                                   |
| Ruby                        | 2.5.0                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.15.1                                        |
| Installation Source         | /usr/local/bin/fastlane                                   |
| Host                        | Mac OS X 10.13.3 (17D102)                                 |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Applications/Xcodes/latest/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                                       |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |
### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>
```ruby
# Customize this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
# This is the minimum version number required.
# Update this, if you use features of a newer version
import '../../Common/fastlane/Fastfile'
ENV['CONFIG'] = "../../___/fastlane/config.yaml"
fastlane_version "1.85.0"
default_platform :ios
```
</details>
**No Appfile found**
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.2  | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| ipaddr                    | 1.2.0        |
</details>
  </pre>
</details>

**Comment by nikitaame** [comment]
Updated with `fastlane env`

**Comment by joshdholtz** [comment]
@nikitaame Thanks for the great description! I think this `build_id` is actually deep down within fastlane and iTC may have changed up an API call on us. I've seen an issue like this before it was because there is no `build_id` while the app is processing. Just from your description, it looks like we may need to wait until the build is done processing before setting the change log but I will look into more to see what is going on. 🤔

**Comment by nikitaame** [comment]
Really appreciate you looking into this! I'll keep an eye out on our CI and see if this is happening again but it seems like we've been lucky over the weekend. Will keep you posted.

**Comment by joshdholtz** [comment]
@nikitaame Heyyy 👋 Are you still experiencing this issue? I tried for a while today and I could not replicate 😔
