### ISSUE TITLE
[Regression] get_version_number target parameter become required, but documented as optional 

### ISSUE THREAD

**Issue by vladislav-m** [fastlane/fastlane#12119]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have ios project with **single target** and trying to get its version number with `get_version_number` call without parameters. It was working fine for long time, but failed yesterday after update fastlane to 2.86.1.

Fastlane asked me to enter target after running 'get_version_number', though it working on travis in non-interactive mode. After reviewing latest releases change logs I found [this](https://github.com/fastlane/fastlane/pull/12037) pull request, that probably caused this regression. And in confirmation of my guess, after I downgraded fastlane to 2.85.0 `get_version_number` started to work as expected again.

<details>
  <pre>[19:29:53]: --------------------------------
[19:29:53]: --- Step: get_version_number ---
[19:29:53]: --------------------------------
[19:29:53]: What target would you like to use?
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios auto |
+------------------+----------+
[19:29:53]: Could not retrieve response as fastlane runs in non-interactive mode
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | git_branch                                                    | 0           |
| 3    | create_keychain                                               | 0           |
| 4    | sed -i '' "s#\(Pods\.framework in Frameworks \*/ = {isa = PBX | 0           |
| 5    | Switch to ios deploy lane                                     | 0           |
| 6    | update_app_identifier                                         | 0           |
| 7    | update_project_team                                           | 0           |
| 8    | Switch to ios build lane                                      | 0           |
| 💥   | get_version_number                                            | 0           |
+------+---------------------------------------------------------------+-------------+
[19:29:53]: fastlane finished with errors
🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:138:in `verify_interactive!'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:121:in `select'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/actions/get_version_number.rb:40:in `get_target!'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/actions/get_version_number.rb:13:in `run'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:137:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:151:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
	from /Users/travis/build/Fooder/iOS-Fooder-Restaraunt/vendor/bundle/ruby/2.4.0/gems/fastlane-2.86.1/bin/fastlane:20:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
The command "./build.sh" exited with 1.</pre>
</details>

probably related to issue #12115 , not sure, because it have too few details.

**Comment by joshdholtz** [comment]
@vladislav-m Look at this right away for you!

**Comment by WildStudio** [comment]
What's the solution if there's more than one target?

**Comment by joshdholtz** [comment]
@WildStudio 
```rb
get_version_number(
  target: "your-target-name"
)
```
