### ISSUE TITLE
What target would you like to use?

### ISSUE THREAD

**Issue by josercc** [fastlane/fastlane#12115]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.1                           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
def test_key
  set_info_plist_value(key:"branch_key", value:"xxxx", path: "./GearBest/Info.plist")
  set_info_plist_value(key:"TRACKING_ID", value:"xxxxx", path: "./GearBest/Others/GoogleService-Info.plist")
end

def kive_key
  set_info_plist_value(key:"branch_key", value:"xxxxx", path: "./GearBest/Info.plist")
  set_info_plist_value(key:"TRACKING_ID", value:"xxxx", path: "./GearBest/Others/GoogleService-Info.plist")
end

def archiveipa(configuration)
  time = Time.new
  version = get_version_number(xcodeproj: "GearBest.xcodeproj")
  app_identifier = "com.gb.gearbestTest"
  if configuration == 'Debug_Test' or configuration == 'Release_Test'
    app_identifier = "com.gb.gearbestTest"
  else
    app_identifier = "com.globalegrow.gearbest"
  end
  build_number_int = Time.new.to_i
  build_name = version + "." + build_number_int.to_s
  set_info_plist_value(key:"CFBundleVersion", value:build_name, path: "./GearBest/Info.plist")
  set_info_plist_value(key:"CFBundleIdentifier", value:app_identifier, path: "./GearBest/Info.plist")
  output_directory = "/Applications/MAMP/htdocs/ipa/"

  configuration_fun = 'Debug'

  #enterprise
  name = configuration
  export_method = 'ad-hoc'
  if configuration == 'Release'
    configuration_fun = configuration
    name = 'Release'
    export_method = 'ad-hoc'
  end

  if configuration == 'Debug_Test'
    configuration_fun = 'Debug'
    export_method = 'enterprise'
    name = 'Debug'
  end

  if configuration == 'Release_Test'
    configuration_fun = 'Release'
    export_method = 'enterprise'
    name = 'Release'
  end

  if configuration == 'appstore'
    configuration_fun = 'Release'
    export_method = 'app-store'
    name = 'AppStore'
  end

  output_name = "GearBest_" + name + "_" + version + "_" + build_number_int.to_s

  puts export_method
  puts configuration_fun
  puts output_directory
  puts output_name
  if configuration == 'Debug_Test' or configuration == 'Release_Test'
    gym(scheme: 'GearBest',
        export_method: export_method,
        configuration: configuration_fun,
        output_directory: output_directory,
        output_name:output_name,
        clean:true,
        export_xcargs: "-allowProvisioningUpdates",
        export_options: {
          provisioningProfiles: {
            app_identifier => "GB_TEST_TEST"
          }
        }
      )
  else
    gym(scheme: 'GearBest',
        export_method: export_method,
        configuration: configuration_fun,
        output_directory: output_directory,
        output_name:output_name,
        clean:true,
      )
  end
end

lane :test_key_configuration do |values|
  test_key
end

lane :live_key_configuration do |values|
  kive_key
end

lane :beta do |values|
  test_key
  archiveipa "Debug"
end

lane :applive do |values|
  kive_key
  archiveipa "Release"
end

lane :beta_test do |values|
  test_key
  archiveipa "Debug_Test"
end

lane :applive_test do |values|
  kive_key
  archiveipa "Release_Test"
end

lane :store do |values|
  kive_key
  archiveipa "appstore"
end

lane :updateBuildNumber do |values|
  build_number_int = Time.new.to_i
  build_name = version + "." + build_number_int.to_s
  set_info_plist_value(key:"CFBundleVersion", value:build_name, path: "./GearBest/Info.plist")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "[[APP_IDENTIFIER]]" # The bundle identifier of your app
# apple_id "[[APPLE_ID]]" # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.1        |
| signet                    | 0.8.1        |
| json                      | 2.1.0        |
| bundler                   | 1.16.1       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2018-03-21**
</details>

**Comment by josercc** [comment]
It seems that the problem has not yet been completely resolved.
When there are two targets in my project, for example creating a project will automatically bring the two targets of test and UI test so there are three targets.
This will prompt me to choose the target, it blocks the automation of the script.
When I delete only one, it will not be prompted again.
The target we choose to package is set in the gym method

**Comment by joshdholtz** [comment]
@josercc Just a little follow up but `gym` does not pass the `target` to `get_version_number` so you will need to specify the target explicitly 😊

**Comment by josercc** [comment]
@joshdholtz Thanks
