### ISSUE TITLE
[supply] Add support for internal test

### ISSUE THREAD

**Issue by nekator** [fastlane/fastlane#12117]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Google introduced internal test as a new way to distribute apks to testers.
So I tried to setup supply to upload my apk to intern test track, but supply doesn't allow track which are not in [this](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L184) array.

Maybe it is enough to expand the array and add the right track name?

I couldn't find the correct track name in the [google developer api docs](https://developers.google.com/android-publisher/api-ref/edits/tracks) , but the docs was last updated on 15 February 2018.

It would be great if someone could find a way to bring internal testing support to supply :)

**Comment by janpio** [comment]
> I could find the correct track name in the google developer api docs ,

Where? I see only exactly what fastlane has in its code :/

Is there an announcement post or something about that change from Google?

**Comment by nekator** [comment]
@janpio Ups. Sorry for the typo. I couldn't find it. So im not 100% sure whether it is possible.

sources: https://support.google.com/googleplay/android-developer/answer/3131213#internal_test
             https://android-developers.googleblog.com/2018/03/our-big-bet-on-mobile-games-at-game.html

**Comment by joebandenburg** [comment]
https://support.google.com/googleplay/android-developer/answer/3131213

> What's the difference between an alpha, beta, and internal test?
> * **Internal test**: You should create an internal test if you want to quickly distribute your app for internal testing and quality assurance checks.
> * **Alpha**: You should create a closed alpha release to test pre-release versions of your app with a larger set of testers. Once you've tested with a smaller group of employees or trusted users, you can expand your test to an open beta release.
>   * *Note*: As of March 2018, you can no longer create open alpha tests. You'll retain access to any existing open alpha tests that are already in progress.
> * **Beta**: You should create a beta release after you've created an alpha release. Your beta release can include a wider range of users for testing, before your app goes live in production.

**Comment by AlexKorovyansky** [comment]
+1. 

`Internal test` has several advantages comparing with Alpha, for example, it doesn't take into distribution limits.

Our development team is based in Russia, but app distribution is the US only, so we're actively using internal test releases to avoid Alpha limits and expect fastlane to support that. Let me know if I can help somehow.

**Comment by joshdholtz** [comment]
PR created for this ^
