### ISSUE TITLE
frameit: Why do the localised .strings file need to be in UTF-16 BE as the code converts them to UTF-8?

### ISSUE THREAD

**Issue by funnel20** [fastlane/fastlane#12127]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The frameit docu at https://docs.fastlane.tools/actions/frameit/ shows:

> Note: These .strings files MUST be utf-16 encoded (UTF-16 BE with BOM). They also must begin with an empty line. If you are having trouble see issue #1740

However, the first thing that Class _strings_parser.rb_ does is converting the file to UTF-8 encoding:
https://github.com/fastlane/fastlane/blob/48ad2fae84e10c3c89402b702f8dd6bdc2f71660/frameit/lib/frameit/strings_parser.rb#L12-L13

We've got a struggle to maintain UTF-16 BE encoding for these .strings files in Xcode over commits.
Often it falls back to some format (WINDOWS-1252 according to [uchardet](https://github.com/BYVoid/uchardet) ) that destroys special characters in locales, like French.
We don't have this problem with the app specific locale .strings files, because they all have default UTF-8 encoding.

So what is the reason these frameit specific .strings files should have UTF-16 BE encoding?
What is needed to support UTF-8 encoding?

**Comment by funnel20** [comment]
@joshdholtz Thanks for this excellent fix.

One action still remains, updating of the frameit docu as it stil refers to UTF-16 BE:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/frame_screenshots.md#strings-files

**Comment by joshdholtz** [comment]
Ah, good call! Will update 👍
