### ISSUE TITLE
Please provide your Apple Developer Program account credentials

### ISSUE THREAD

**Issue by jeremyspatrick** [fastlane/fastlane#12129]
We have been using fastlane with Jenkins for over a year now with no issues. Today fastlane is not able to access the keychain from Jenkins. I have verified that the correct credentials are in the keychain.  The credentials are added via the keychain manager.

If I run the same command manually without Jenkins this works. We have built several apps with this setup so I am not sure what is going on. 

Jenkins is installed as the root user and i'm unlocking the keychains

security default-keychain -s /var/****/Library/Keychains/login.keychain-db
security unlock-keychain -p **** /var/****/Library/Keychains/login.keychain-db
security set-keychain-settings -t 3600 -l /var/****/Library/Keychains/login.keychain-db

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[13:56:17]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
invalid option: --capture_output
****** produce *******
fastlane produce create -a xxxxxxxxxx -u xxxxxxxxxx -b xxxxxxxxxx -q xxxxxxxxxx -i
[13:56:22]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m

+----------------+---------------------------------------+
|               [32mSummary for produce 2.86.2[0m               |
+----------------+---------------------------------------+
| app_identifier | xxxxxxxxxx |
| username       | xxxxxxxxxx                |
| team_id        | xxxxxxxxxx                            |
| app_name       | xxxxxxxxxx                          |
| skip_itc       | true                                  |
| sku            | xxxxxxxxxx                            |
| platform       | ios                                   |
| language       | English                               |
| skip_devcenter | false                                 |
+----------------+---------------------------------------+

[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
[32mSee more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
[32m-------------------------------------------------------------------------------------[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/credentials_manager/lib/credentials_manager/account_manager.rb:131:in `ask_for_login': [31m[!] Missing password for user csi0271@myebanking.net, and running in non-interactive shell[0m (RuntimeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/credentials_manager/lib/credentials_manager/account_manager.rb:52:in `password'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/client.rb:348:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/client.rb:71:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/portal/spaceship.rb:95:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/produce/lib/produce/developer_center.rb:126:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/produce/lib/produce/developer_center.rb:41:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/produce/lib/produce/manager.rb:11:in `start_producing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/produce/lib/produce/commands_generator.rb:39:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/produce/lib/produce/commands_generator.rb:182:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/produce/lib/produce/commands_generator.rb:16:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/fastlane/lib/fastlane/cli_tools_distributor.rb:99:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.86.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.5        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2018-03-21**
</details></pre>
</details>

**Comment by jeremyspatrick** [comment]
I was able to able to get around this by using the system keychain instead of the login keychain but it appears doing so is causing this issue

https://github.com/fastlane/fastlane/issues/11714

**Comment by joshdholtz** [comment]
@jeremyspatrick Hey 👋 Do you know what happened to make this stop working? Was it a fastlane update? Or a jenkins update? Or an OS update?

**Comment by jeremyspatrick** [comment]
I am not sure what caused this but I was able to get this to work by going back to the login keychain and making sure my jenkins was running as the correct user by adding the username to the LaunchAgent/LaunchDaemons

        <key>UserName</key>
        <string>jenkins</string>
        <key>SessionCreate</key>
        <true />

https://stackoverflow.com/questions/6827874/missing-certificates-and-keys-in-the-keychain-while-using-jenkins-hudson-as-cont/7433167
