### ISSUE TITLE
Fastlane docs not available on RubyDoc

### ISSUE THREAD

**Issue by fjcaetano** [fastlane/fastlane#12139]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

RubyDoc is not indexing Fastlane files as can be verified here: http://www.rubydoc.info/gems/fastlane/2.86.2

This seems to be a somewhat recent issue since version 1.56.0 used to be indexed: http://www.rubydoc.info/gems/fastlane/1.56.0

I can't pinpoint what caused this issue, but I find really helpful relying on the classes documentation when developing an action, plugin, or even customizing the Fastfile.

Anyway, thank you for Fastlane! Please, feel free to ask for anything.

**Comment by nafu** [comment]
We've released some of the updates for the yardoc at [2.87.0](https://github.com/fastlane/fastlane/releases/tag/2.87.0) but we still need one more action to work it on rubydoc.info.

I've created https://github.com/fastlane/fastlane/pull/12156 to solve it. This should be enough for closing this 💪

**Comment by nafu** [comment]
@fjcaetano Thanks for reporting. This is fixed on _fastlane_ 2.88.0 👍 

http://www.rubydoc.info/gems/fastlane/2.88.0

![image](https://user-images.githubusercontent.com/932290/38003071-c5b407d8-3270-11e8-8ae0-5f993f3e96e1.png)

**Comment by fjcaetano** [comment]
Awesome! Kudos! 🎉
