### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by flohei** [fastlane/fastlane#1213]
I'm trying to set up fastlane for one of my old projects. I have already used snapshot a while back. When I run `fastlane init`, I get the following error message right after entering the password for my Apple ID:

> Error occurred with the setup program! Reverting changes now!

The corresponding error report id is `aea98e66c7a27576b2255b29dad1e297`.

Any idea what's going wrong there?

Thank you!

**Comment by rpmobile** [comment]
Me as well. Entering correct credentials is causing that same error.  In the keychain I see this account:

deliver.<my itunes developer email id>

with the correct password stored.  But fastlane init still fails.

**Comment by ohwutup** [comment]
hey @flohei and @rpmobile, a fix for this is in the works and should be merged later today or tomorrow most likely, sorry for the issues! in the mean time, you can definitely get set up by manually creating your Fastfile and/or other relevant files.

**Comment by ObjColumnist** [comment]
Is there any documentation for manually creating the files?

**Comment by ohwutup** [comment]
Hi all! Just pushed a fix for this here: https://github.com/fastlane/fastlane/releases/tag/1.54.0 If you answer "n" to the values that fastlane determines for you, you will be routed through manual onboarding and it will ask you if you want to do the iTC/dev portal actions, respond no to those and you should be all set!

Going to close this, but please feel free to open new issues as they arise!

**Comment by rpmobile** [comment]
Got the latest, but its still failing for me.  I see a more verbose output now:

```
[13:10:25]: Error occurred with the setup program! Reverting changes now!
[13:10:25]: Deleting the 'fastlane' folder
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'bed729e26a3575ff40c36242f24a4c7c'
The crash report has been stored locally '/tmp/sentry_bed729e26a3575ff40c36242f24a4c7c.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.3/lib/spaceship/client.rb:268:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)

```

I have verified that I am using the correct apple id / pass.
