### ISSUE TITLE
Upload to Crashlytics plugin has no way to disable Firebase plist upload

### ISSUE THREAD

**Issue by JoeSzymanski** [fastlane/fastlane#12132]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Recently, UploadSymbolsToCrashlyticsAction was updated to support the relatively new feature of uploading symbols to Fabric using a GoogleServices plist file (#11798). While this is listed as an optional setting, if there is a GoogleServices.plist file anywhere in the directory structure, the action will now attempt to upload using the plist.
Unfortunately, this causes problems in multi-organization scenarios for Fabric. Firebase doesn't currently support having different configurations within the same app (to support things like enterprise versions or internal versions), so there is only one plist file. At the same time, uploading to Fabric with the plist overrides any value used for the Fabric App ID.
What this results in is that the dSYM files can be uploaded to the wrong Fabric Organization, which will result in crashes being unable to be symbolicated.

This action should be update to truly make the GoogleServices plist optional and not pull it in automatically if found.

We have created a workaround by replicating the previous version of the UploadSymbolsToCrashlyticsAction as a local action and using the local action instead of the real action, but we would prefer using the official action, if possible.

**Comment by joshdholtz** [comment]
@JoeSzymanski Created a PR for ya ^

**Comment by JoeSzymanski** [comment]
+1. Thanks!
