### ISSUE TITLE
Match uses wrong team ID if it's defined in Matchfile and Fastfile

### ISSUE THREAD

**Issue by rs-georg** [fastlane/fastlane#12146]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It seems that properties defined by sync_code_signing (aka match) in a Fastfile do not overwrite properties defined in the Matchfile. According to the logs match detects the Matchfile and correctly merges it with the Fastfile giving the properties of the Fastfile precedence. However, when actually executing match the team ID defined in the Matchfile is used. If I comment out the team ID in the Matchfile everything works as expected.
Might be related to #9298

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[12:19:31]: [32m---------------------------[0m
[12:19:31]: [32m--- Step: opt_out_usage ---[0m
[12:19:31]: [32m---------------------------[0m
[12:19:31]: Disabled upload of used actions
[12:19:31]: [32m------------------------------[0m
[12:19:31]: [32m--- Step: default_platform ---[0m
[12:19:31]: [32m------------------------------[0m
[12:19:31]: [32mDriving the lane 'ios setup' 🚀[0m
[12:19:31]: [32m-----------------------[0m
[12:19:31]: [32m--- Step: xcversion ---[0m
[12:19:31]: [32m-----------------------[0m
[12:19:32]: Setting Xcode version to /Applications/Xcode_9.2.app for all build steps
[12:19:32]: [32m-----------------------------[0m
[12:19:32]: [32m--- Step: create_keychain ---[0m
[12:19:32]: [32m-----------------------------[0m
[12:19:32]: [36m$ security list-keychains -d user[0m
[REDACTED]
[12:19:32]: [32m-------------------------------[0m
[12:19:32]: [32m--- Step: sync_code_signing ---[0m
[12:19:32]: [32m-------------------------------[0m
INFO [2018-03-23 12:19:32.79]: [32mSuccessfully loaded '[redacted] fastlane/Matchfile' 📄[0m

+----------------+-----------------------------------------------+
|          Detected Values from './fastlane/Matchfile'           |
+----------------+-----------------------------------------------+
| git_url        | [REDACTED]                                    |
|                |                                               |
| team_id        | CLE3CR44ZG                                    |
| app_identifier | ["com.example.foo"]                           |
|                |                                               |
|                |                                               |
|                |                                               |
| username       | [REDACTED]                                    |
| keychain_name  | foo.keychain                                  |
+----------------+-----------------------------------------------+

+-----------------------+-----------------------------------------------+
|                       [32mSummary for match 2.86.2[0m                 |
+-----------------------+-----------------------------------------------+
| type                  | enterprise                                    |
| git_branch            | enterprise                                    |
| team_id               | X5CCK6Q4J6                                    |
| team_name             | [REDACTED]                                    |
| username              | [REDACTED]                                    |
| verbose               | true                                          |
| app_identifier        | ["com.example.enterprise.foo"]                |
|                       |                                               |
|                       |                                               |
|                       |                                               |
|                       |                                               |
| readonly              | false                                         |
| git_url               | [REDACTED]                                    |
|                       |                                               |
| keychain_name         | foo.keychain                                  |
| force                 | false                                         |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| clone_branch_directly | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
| platform              | ios                                           |
+-----------------------+-----------------------------------------------+

INFO [2018-03-23 12:19:32.81]: Cloning remote git repo...
INFO [2018-03-23 12:19:32.81]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-03-23 12:19:32.81]: [36m$ GIT_TERMINAL_PROMPT=0 git clone '[REDACTED]' '/var/folders/p6/pmppjydx72lb8y85f737qjtc00011z/T/d20180323-15710-1dfbzzt'[0m
INFO [2018-03-23 12:19:32.82]: ▸ [35mCloning into '/var/folders/p6/pmppjydx72lb8y85f737qjtc00011z/T/d20180323-15710-1dfbzzt'...[0m
INFO [2018-03-23 12:19:33.66]: ▸ [35mremote: Counting objects: 382, done.[K[0m
INFO [2018-03-23 12:19:33.82]: ▸ [35mremote: Compressing objects: 100% (340/340), done.[K[0m
INFO [2018-03-23 12:19:34.17]: ▸ [35mremote: Total 382 (delta 61), reused 205 (delta 29)[K[0m
INFO [2018-03-23 12:19:34.18]: ▸ [35mReceiving objects: 100% (382/382), 1.26 MiB | 0 bytes/s, done.[0m
INFO [2018-03-23 12:19:34.19]: ▸ [35mResolving deltas: 100% (61/61), done.[0m
INFO [2018-03-23 12:19:34.28]: [36m$ git --no-pager branch --list [REDACTED] --no-color -r[0m
INFO [2018-03-23 12:19:34.29]: Checking out branch enterprise...
INFO [2018-03-23 12:19:34.29]: [36m$ git checkout --orphan enterprise[0m
INFO [2018-03-23 12:19:34.31]: ▸ [35mSwitched to a new branch 'enterprise'[0m
INFO [2018-03-23 12:19:34.31]: [36m$ git reset --hard[0m
INFO [2018-03-23 12:19:34.32]: [32m🔓  Successfully decrypted certificates repo[0m
INFO [2018-03-23 12:19:34.37]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2018-03-23 12:19:37.29]: [32m-----------------------------[0m
INFO [2018-03-23 12:19:37.29]: [32m--- Step: delete_keychain ---[0m
INFO [2018-03-23 12:19:37.29]: [32m-----------------------------[0m
WARN [2018-03-23 12:19:37.32]: [33m[33mLane Context:[0m
INFO [2018-03-23 12:19:37.32]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios setup"}
ERROR [2018-03-23 12:19:37.32]: [31mYou defined the profile type 'enterprise', but your Apple account doesn't support In-House profiles[0m
INFO [2018-03-23 12:19:37.32]: [32mSuccessfully generated documentation at path 'fastlane/README.md'[0m

+------+-------------------+-------------+
|            [32mfastlane summary[0m            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | opt_out_usage     | 0           |
| 2    | default_platform  | 0           |
| 3    | xcversion         | 0           |
| 4    | create_keychain   | 0           |
| 💥   | [31msync_code_signing[0m | 4           |
| 6    | delete_keychain   | 0           |
+------+-------------------+-------------+

ERROR [2018-03-23 12:19:37.33]: [31mfastlane finished with errors[0m
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.5.0                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.10.0                              |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane            |
| Host                        | Mac OS X 10.12.6 (16G1212)                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode_9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
#

opt_out_usage

default_platform(:ios)

platform :ios do

	before_all do |lane|
		xcversion(version: "9.2")

		create_keychain(
  		name: ENV["KEYCHAIN_NAME"],
  		password: rand(36**42).to_s(36),
  		default_keychain: false,
  		unlock: true,
  		lock_when_sleeps: false,
  		lock_after_timeout: false,
  		add_to_search_list: true,
  		timeout: false
		)
	end

	after_all do |lane|
		delete_keychain(name: ENV["KEYCHAIN_NAME"])
	end

	error do |lane, exception, options|
  	delete_keychain(name: ENV["KEYCHAIN_NAME"])
	end

  desc "Setup local development."
  desc "This will do the following: "
  desc "- Install certificates and profiles"
  lane :setup do
    sync_code_signing(
      type: "enterprise",
      git_branch: "enterprise",
      team_id: "X5CCK6Q4J6",
      team_name: "[REDACTED]",
      username: "[REDACTED]",
      verbose: true,
      app_identifier: ["com.example.enterprise.foo"],
      readonly: false
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier("com.example.foo")
apple_id("[REDACTED]")

```
</details>

<details><summary>`./fastlane/Matchfile`</summary>

```ruby
# For all available options run `fastlane match --help`

git_url("[REDACTED]")

team_id("CLE3CR44ZG")
app_identifier(["com.example.foo"])
username("[REDACTED]")
keychain_name(ENV["KEYCHAIN_NAME"])

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 5.1.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 0.6.5        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.61.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| slather                   | 2.4.5        |
| xcode-install             | 2.3.1        |
</details>

*generated on:* **2018-03-23**
</details>
</pre>
</details>

**Comment by joshdholtz** [comment]
@rs-georg Got a PR made for your issue ^

**Comment by rs-georg** [comment]
Cool, thanks!
