### ISSUE TITLE
[Match] Check OpenSSL version on attempt to decrypt certificates repo

### ISSUE THREAD

**Issue by RenGate** [fastlane/fastlane#12149]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is rather suggestion, than an issue. Can match be updated to store the OpenSSL version that was used during certificates encryption in something like a .openssl-version file in the repo and show warning on attempt to decrypt certificates with different OpenSSL version?
Right now if there is a mismatch between OpenSSL versions used to encrypt and decrypt files, an "Incorrect password" error will be shown even if password is correct, which is very misleading. I've experienced such situation during attempt to decrypt the repo, which was encrypted with LibreSSL 2.2.7, with OpenSSL 1.1.0e.
If such check will be integrated, it will eliminate issues like https://github.com/fastlane/fastlane/issues/7127. Thanks.

**Comment by joshdholtz** [comment]
@RenGate This is a great suggestion! Are you able to give this change a try yourself? If not, I can add this to my queue of things to work on 🙃

**Comment by RenGate** [comment]
Unfortunately, my knowledge of Ruby is very limited 🙁, otherwise I would send a pull request instead of opening issue.
