### ISSUE TITLE
Could not find lane

### ISSUE THREAD

**Issue by AndriyGo** [fastlane/fastlane#12141]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to call fastlane from a python script. When I do so, I encounter an error `Could not find lane 'ios GLXCDUUpload'. Available lanes: screenshots, uploadMetadata, grandUpdate, GLXCDUUpload, GLXCDUSubmit, refresh_dsyms`.

In my Python script I am using the following code to call fastlane:
```
with cd(project["pathToGit"] + "fastlane"):
            print(GLXCDUBash.call(("pwd").split(" ")))
            GLXCDUBash.call(("fastlane GLXCDUUpload --env glxcdu").split(" "))
```

The `cd` part comes from [this answer](https://stackoverflow.com/questions/431684/how-do-i-cd-in-python/13197763#13197763) on how to change the current path in python. `GLXCDUBash` is my wrapper around bash commands and it is not a source of the problem as I have used it in many places. `pwd` prints correct path. In fact, if I `cd` into that directory in terminal and run `fastlane GLXCDUUpload --env glxcdu` everything is working. However, if I call it from Python, I get the error described above.

Could anyone tell me what might be causing this error?

P.S. `fastlane env` produces the same output if run from Python and after `cd` into fastlane folder.

### Update 1

The output I see from my Python script is identical to calling `fastlane ios GLXCDUUpload --env glxcdu` in terminal. That way I also encounter an error. The question is why the `ios` bit is added?

#### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[07:56:18]: ------------------------------
[07:56:18]: --- Step: default_platform ---
[07:56:18]: ------------------------------
[07:56:18]: Loading from './.env.glxcdu'
+------------------+--------+
|       Lane Context        |
+------------------+--------+
| DEFAULT_PLATFORM | ios    |
| ENVIRONMENT      | glxcdu |
+------------------+--------+
[07:56:18]: Could not find lane 'ios GLXCDUUpload'. Available lanes: screenshots, uploadMetadata, grandUpdate, GLXCDUUpload, GLXCDUSubmit, refresh_dsyms

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[07:56:18]: fastlane finished with errors

[!] Could not find lane 'ios GLXCDUUpload'. Available lanes: screenshots, uploadMetadata, grandUpdate, GLXCDUUpload, GLXCDUSubmit, refresh_dsyms</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

before_all do
 	update_fastlane(
 		nightly: false
 	)
end

lane :screenshots do
	SCHEMES = ENV["SCHEMES"].split(",")
	APP_IDS = ENV["APP_IDS"].split(",")
	SCHEMES.each_with_index {|scheme_name, index|
	ENV["SCHEME"] = scheme_name
	ENV["APP_ID"] = APP_IDS[index]
	snapshot({skip_open_summary:true,
		output_directory: "../Screenshots/#{ENV["SCHEME"]}",
		clear_previous_screenshots:true,
		reinstall_app:true,
		stop_after_first_error:true,
		app_identifier: "#{ENV["APP_ID"]}"})
		slack ({
			slack_url: "XXXXXXXXXXX",
			success:true,
			message: "Screenshots created for #{ENV["SCHEME"]}",
			default_payloads: [:lane, :test_result]
		})
	}
end

lane :uploadMetadata do
	SCHEMES = ENV["SCHEMES"].split(",")
	APP_IDS = ENV["APP_IDS"].split("|")
	NOTES = ENV["RELEASE_NOTES"].split("|")
	ADS = ENV["SERVE_ADS"].split(",")
	SCHEMES.each_with_index {|scheme_name, index|
		ENV["SCHEME"] = scheme_name
		IDS = APP_IDS[index].split(",")
		ENV["APP_ID"] = IDS[0]
		ENV["RELEASE_NOTE"] = NOTES[index]
		ENV["SERVES_ADS"] = ADS[index]
		deliver(
			submit_for_review:false,
			skip_binary_upload:true
		)
	}
end

lane :grandUpdate do
  increment_build_number
  SCHEMES = ENV["SCHEMES"].split(",")
  APP_IDS = ENV["APP_IDS"].split("|")
  NOTES = ENV["RELEASE_NOTES"].split("|")
  ADS = ENV["SERVE_ADS"].split(",")
  SCHEMES.each_with_index {|scheme_name, index|
 	ENV["SCHEME"] = scheme_name
	IDS = APP_IDS[index].split(",")
	ENV["APP_ID"] = IDS[0]
	ENV["RELEASE_NOTE"] = NOTES[index]
	IDS.each_with_index {|id, index|
		match(app_identifier: "#{id}", type: "appstore")
	}
        ENV["SERVES_ADS"] = ADS[index]
	gym(configuration: "Release", scheme:ENV["SCHEME"])
	deliver(submit_for_review:false)
  }
  SCHEMES.each_with_index {|scheme_name, index|
	ENV["SCHEME"] = scheme_name
	IDS = APP_IDS[index].split(",")
	ENV["APP_ID"] = IDS[0]
        ENV["SERVES_ADS"] = ADS[index]
	ENV["RELEASE_NOTE"] = NOTES[index]
	deliver(skip_binary_upload:true)
	slack ({
		slack_url: "XXXXXXXX",
		success:true,
		message: "Update for #{ENV["SCHEME"]} successfully submitted for review",
		default_payloads: [:lane, :test_result]
  	})
  }
end

lane :GLXCDUUpload do
  increment_build_number
  SCHEMES = ENV["SCHEMES"].split(",")
  APP_IDS = ENV["APP_IDS"].split("|")
  NOTES = ENV["RELEASE_NOTES"].split("|")
  ADS = ENV["SERVE_ADS"].split(",")
  SCHEMES.each_with_index {|scheme_name, index|
 	ENV["SCHEME"] = scheme_name
	IDS = APP_IDS[index].split(",")
	ENV["APP_ID"] = IDS[0]
	ENV["RELEASE_NOTE"] = NOTES[index]
	IDS.each_with_index {|id, index|
		match(app_identifier: "#{id}", type: "appstore")
	}
        ENV["SERVES_ADS"] = ADS[index]
	gym(configuration: "Release", scheme:ENV["SCHEME"])
	deliver(submit_for_review:false)
  }
  SCHEMES.each_with_index {|scheme_name, index|
	ENV["SCHEME"] = scheme_name
	IDS = APP_IDS[index].split(",")
	ENV["APP_ID"] = IDS[0]
        ENV["SERVES_ADS"] = ADS[index]
	ENV["RELEASE_NOTE"] = NOTES[index]
	deliver(skip_binary_upload:true)
  }
end

lane :GLXCDUSubmit do
  increment_build_number
  SCHEMES = ENV["SCHEMES"].split(",")
  APP_IDS = ENV["APP_IDS"].split("|")
  NOTES = ENV["RELEASE_NOTES"].split("|")
  ADS = ENV["SERVE_ADS"].split(",")
  SCHEMES.each_with_index {|scheme_name, index|
	ENV["SCHEME"] = scheme_name
	IDS = APP_IDS[index].split(",")
	ENV["APP_ID"] = IDS[0]
        ENV["SERVES_ADS"] = ADS[index]
	ENV["RELEASE_NOTE"] = NOTES[index]
	deliver(skip_binary_upload:true)
  }
end

# error block is executed when an error occurs
error do |lane, exception|
	slack(
		slack_url: "XXXXX",
		# message with short human friendly message
		message: exception.to_s, 
		success: false, 
		# Output containing extended log output
		payload: { "Output" => exception.error_info.to_s } 
	)
end

lane :refresh_dsyms do
	SCHEMES = ENV["SCHEMES"].split(",")
	APP_IDS = ENV["APP_IDS"].split("|")
	ADS = ENV["SERVE_ADS"].split(",")
	SCHEMES.each_with_index {|scheme_name, index|
		ENV["SCHEME"] = scheme_name
		IDS = APP_IDS[index].split(",")
		ENV["APP_ID"] = IDS[0]
		ENV["SERVES_ADS"] = ADS[index]
		download_dsyms(
			app_identifier: "#{ENV["APP_ID"]}", 
			version: "latest"
		)
	}
	upload_symbols_to_crashlytics(
		api_token: "XXXXXX"
		)
	clean_build_artifacts
	slack ({
		slack_url: "XXXXXX",
		success:true,
		message: "All dSYMS were refreshed!",
		default_payloads: [:lane, :test_result]
  	})
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
apple_id "XXXXX@gmail.com"
app_identifier "#{ENV["APP_ID"]}"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.86.2  | ✅ Up-To-Date       |
| fastlane | 2.85.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.6        |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.2        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| dotenv                    | 2.2.0        |
| excon                     | 0.60.0       |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.1        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| gh_inspector              | 1.1.2        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.10       |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.13.1       |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| naturally                 | 2.1.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.4.0        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.2        |
| slack-notifier            | 2.3.2        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-screen                | 0.6.3        |
| tty-screen                | 0.6.2        |
| tty-screen                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| tty-spinner               | 0.7.0        |
| uber                      | 0.1.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.3.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-03-23**
</details>

**Comment by joshdholtz** [comment]
@AndriyGo The `ios` is getting injected from `default_platform :ios` in the top of your `Fastfile`. If you remove that your python script should start working?

**Comment by AndriyGo** [comment]
@joshdholtz thanks, either this or wrapping everything in `platform :ios do` works. However, I do not still understand why `ios` is injected only when I run it from the script? It doesn't get injected if I call `fastlane` from a folder.

I think this is important because even though I fixed those errors, I now have an error in `deliver`. It does not set the release notes even though it detects them. The output is the same when called from my script or from a folder. However, from the script, it does not work...

**Comment by AndriyGo** [comment]
@joshdholtz actually I found one difference in `deliver`. I have the following entries there:
```
screenshots_path "./fastlane/#{ENV["SCHEME"]}/screenshots"
metadata_path "./fastlane/#{ENV["SCHEME"]}/metadata/"
```

I am not currently uploading metadata or screenshots. Calling `deliver` from terminal creates the following empty folders structure:
```
|metadata
---default
---en-US
|screenshots
---default
---en-US
```

From the script it does not create the language subfolders, even though in the output it clearly states that it detected default and en-US as languages.

**Comment by AndriyGo** [comment]
@joshdholtz actually I was wrong. There is nothing wrong with the script. The problem with deliver was originating from a missing language folder. I have opened a new issue for this as I think it is a bug. #12163
