### ISSUE TITLE
Element Window cannot request screenshot data because it has an empty frame SnapshotHelper.swift:164

### ISSUE THREAD

**Issue by sirdharma** [fastlane/fastlane#12140]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to set up Snapshot and have followed the Snapshot installation steps.

I have a single UI test that's pretty straightforward:

```
class XxxUITests: XCTestCase {
        
    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    func testOnboarding() {
        let app = XCUIApplication()

        let getStartedButton = app.buttons["signin.button.get started"]
        let nextButton = app.buttons["signin.button.next"]
        let joinButton = app.buttons["signin.button.join"]

        XCTAssert(getStartedButton.exists)
        snapshot("01Onboarding")
        getStartedButton.tap()

        XCTAssert(nextButton.exists)
        snapshot("02Onboarding")
        nextButton.tap()

        XCTAssert(nextButton.exists)
        snapshot("03Onboarding")
        nextButton.tap()

        XCTAssert(joinButton.exists)
        snapshot("04Onboarding")
    }
    
}
```

- The tests run fine when I comment out the calls to `snapshot()`.
- The tests run fine when I leave the calls to `snapshot()` but comment out the call to `setupSnapshot()` (I get a warning in the console that says to call `setupSnapshot`, as is expected).
- I get the following error `Element Window cannot request screenshot data because it has an empty frame SnapshotHelper.swift:164` when I run the tests otherwise (with Xcode or with `fastlane snapshot`).

My `Snapfile` is as follows:

```
devices([
  "iPhone SE",
])
clear_previous_screenshots(true)
concurrent_simulators(false)
```

Any hint towards the right direction would be much appreciated. Thank you!

##### Complete output when running fastlane, including the stack trace and command used

`fastlane snapshot --capture_output` returns an error

<details>
  <pre>invalid option: --capture_output</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.asdf/installs/ruby/2.4.2/bin/fastlane    |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/2.4.2/lib             |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :ios

CRASHLYTICS_API_TOKEN = "xxx"
CRASHLYTICS_BUILD_SECRET = "xxx"
SLACK_URL = "https://hooks.slack.com/services/xxx/xxx/xxx"

platform :ios do
  before_all do
    setup_circle_ci
  end
end

lane :test do
  cocoapods

  run_tests(
    scheme: "Dev Local",
  )
end

lane :register_new_devices do
  register_devices(
    devices_file: "devices.txt",
  )
end

lane :alpha do
  cocoapods

  increment_build_number

  get_provisioning_profile(
    adhoc: true,
    force: true,
    app_identifier: "com.xxx.xxx-alpha",
  )

  build_ios_app(
    scheme: "Alpha",
    export_method: "ad-hoc",
  )

  crashlytics(
    api_token: CRASHLYTICS_API_TOKEN,
    build_secret: CRASHLYTICS_BUILD_SECRET,
    groups: "xxx-team, alpha-testers",
  )

  slack(
    slack_url: SLACK_URL,
  )
end

lane :beta do
  cocoapods

  increment_build_number

  get_provisioning_profile(
    adhoc: true,
    force: true,
    app_identifier: "com.xxx.xxx-dev",
  )

  build_ios_app(
    scheme: "Beta",
    export_method: "ad-hoc",
  )

  crashlytics(
    api_token: CRASHLYTICS_API_TOKEN,
    build_secret: CRASHLYTICS_BUILD_SECRET,
    groups: "***-team, insiders",
  )

  slack(
    slack_url: SLACK_URL,
  )
end

lane :build do
  cocoapods

  xcodebuild(
    workspace: 'xxx.xcworkspace',
    scheme: 'Dev Local',
    clean: true,
    build: true,
    destination: 'generic/platform=iOS',
    build_settings: {
    'CODE_SIGNING_REQUIRED' => 'NO',
    'CODE_SIGN_IDENTITY' => '',
    }
  )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.61.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-03-22**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@sirdharma Heyyy 👋 Your `setup()` function looks to be missing `XCUIApplication().launch()` at the end. I'm not sure if that will fix this but this is what my `setup()` looks like 🙃 

```swift
override func setUp() {
    super.setUp()
    
    let app = XCUIApplication()
    setupSnapshot(app)
    app.launch()
  
    continueAfterFailure = false

    XCUIApplication().launch()
}
```

**Comment by sirdharma** [comment]
@joshdholtz Thank you for your reply! My `setup()` has `app.launch()` though:

```
    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()
    }
```

It looks to me like your `setup()` is launching the app twice, or am I mistaken?

For reference, this is exactly what the Snaphost's example does: https://github.com/fastlane/fastlane/blob/d996750c186f66c885d20421729814b20257a50f/snapshot/example/ExampleUITests/ExampleUITests.swift#L14-L20

**Comment by joshdholtz** [comment]
Oops, my bad! And yeah, I guess mine is doing it twice 🤔 How is mine working....

**Comment by joshdholtz** [comment]
Can you try calling this code directly from within your tests and see what happens?
```swift
let screenshot = app.windows.firstMatch.screenshot()
```

This is the line that is failing on your you and maybe your app doesn't have any windows for some reason? 🤔 But maybe inspect/print stuff out and see if you can get to `app`, `app.windows` and `app.windows.firstMatch` manually. 

Lemme know if that doesn't make sense 🙃

**Comment by sirdharma** [comment]
@joshdholtz It does make sense. Those steps were actually the first I took when I stumbled upon this error but it didn't help.

Somehow when `screenshot()` is being called, whichever `window` was matched has an empty frame. The `Snapshot` code doesn't ensure that this is the case, so my best guess is this is some sort of race condition. I am just surprised not more people struggle with that error.

**Comment by sirdharma** [comment]
Solved by https://github.com/fastlane/fastlane/commit/721f102695521f47f3c6b2a140961a40e32746d7. 

Thank you all!
