### ISSUE TITLE
Gym not honoring "BuildSystemType" in project/workspace settings. 

### ISSUE THREAD

**Issue by SeanRobinson159** [fastlane/fastlane#12155]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Gym does not honor the `BuildSystemType` that is in the project file. 

I want Gym to use Xcode's "New Build System" for faster building.

Looking at the documentation for fastlane / gym I couldn't see anywhere where I could provide additional flags to the `xcodebuild` command either. 

Is it possible to use Xcode's new build system with Gym?

**Comment by joshdholtz** [comment]
@SeanRobinson159 TIL about "New Build System" 🙃 You should be able to do... 
```rb
gym(
  xcargs: "-UseNewBuildSystem=YES"
)
```

**Comment by SeanRobinson159** [comment]
That did work.
It would be a nice feature to add to fastlane to honor the project file setting for the build system though.

**Comment by joshdholtz** [comment]
@SeanRobinson159 This probably won't get added as an option to fastlane since Xcode will most likely end up using the new system transparently in a new version which would make the change not necessary 🙃 But thanks for bringing this issue up so that others can find a solution 🙌
