### ISSUE TITLE
Match fails when run by Bamboo but not terminal

### ISSUE THREAD

**Issue by jwilson85** [fastlane/fastlane#12152]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I installed bamboo on a mac so we can do local CI builds. When I run fastlane from the folder that was checked out by bamboo. Everything is rosy! However if bamboo runs it. Match fails. No clue whats wrong here or what is different about how bamboo does it. Also FYI I tried but using command and the fastlane plugin for bamboo. Makes no difference.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
simple	23-Mar-2018 12:25:32	Build Mobile - ios-Enterprise - Default Job #10 (BAMBOO-IOS-JOB1-10) started building on agent Default Agent
simple	23-Mar-2018 12:25:32	
simple	23-Mar-2018 12:25:32	Build working directory is /Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-IOS-JOB1
simple	23-Mar-2018 12:25:32	Executing build Mobile - ios-Enterprise - Default Job #10 (BAMBOO-IOS-JOB1-10)
simple	23-Mar-2018 12:25:32	Starting task 'Checkout Default Repository' of type 'com.atlassian.bamboo.plugins.vcs:task.vcs.checkout'
simple	23-Mar-2018 12:25:32	Checking out into /Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-IOS-JOB1
simple	23-Mar-2018 12:25:32	Updating source code to revision: 9824f479ed794ff05c5b300edaea490e6b6aa520
simple	23-Mar-2018 12:25:32	Fetching 'refs/heads/development' from 'https://bitbucket.org/boojgit/enterprise'.
simple	23-Mar-2018 12:25:33	Checking out revision 9824f479ed794ff05c5b300edaea490e6b6aa520.
simple	23-Mar-2018 12:25:34	Already on 'development'
simple	23-Mar-2018 12:25:34	Your branch is up-to-date with 'origin/development'.
simple	23-Mar-2018 12:25:34	Updated source code to revision: 9824f479ed794ff05c5b300edaea490e6b6aa520
simple	23-Mar-2018 12:25:34	Finished task 'Checkout Default Repository' with result: Success
simple	23-Mar-2018 12:25:34	Running pre-build action: VCS Version Collector
simple	23-Mar-2018 12:25:34	Skipping execution of task 'fastlane enterprise' as it is disabled
simple	23-Mar-2018 12:25:34	Starting task 'fastlane pluging' of type 'com.atlassian.bamboo.plugins.xcode.bamboo-xcode-plugin:fastlaneTaskType'
error	23-Mar-2018 12:25:35	/Users/mobile/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
error	23-Mar-2018 12:25:35	/Users/mobile/.rvm/gems/ruby-2.4.1@global/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: previous definition of VERSION was here
build	23-Mar-2018 12:25:37	[12:25:37]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m----------------------------------------[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m--- Step: Verifying fastlane version ---[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m----------------------------------------[0m
build	23-Mar-2018 12:25:39	[12:25:39]: Your fastlane version 2.86.2 matches the minimum requirement of 2.29.0  ✅
build	23-Mar-2018 12:25:39	[12:25:39]: [32m------------------------------[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m--- Step: default_platform ---[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m------------------------------[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32mLoading from './fastlane/.env.lyon'[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32mDriving the lane 'ios enterprise' 🚀[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m--------------------------------------------------------------------[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32mStep: git rev-parse --short HEAD 2> /dev/null | sed 's/(.*)//'[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [32m--------------------------------------------------------------------[0m
build	23-Mar-2018 12:25:39	[12:25:39]: [36m$ git rev-parse --short HEAD 2> /dev/null | sed 's/(.*)//'[0m
build	23-Mar-2018 12:25:40	[12:25:40]: ▸ [35m9824f47[0m
build	23-Mar-2018 12:25:40	[12:25:40]: target name Lyon-beta bundle com.activewebsite.lyon-beta
build	23-Mar-2018 12:25:40	[12:25:40]: [32m-------------------[0m
build	23-Mar-2018 12:25:40	[12:25:40]: [32m--- Step: match ---[0m
build	23-Mar-2018 12:25:40	[12:25:40]: [32m-------------------[0m
build	23-Mar-2018 12:25:40	[12:25:40]: [32mSuccessfully loaded '/Users/mobile/Bamboo/xml-data/build-dir/BAMBOO-IOS-JOB1/fastlane/Matchfile' 📄[0m
build	23-Mar-2018 12:25:40	
build	23-Mar-2018 12:25:40	+------------+--------------------------------------+
build	23-Mar-2018 12:25:40	|    Detected Values from './fastlane/Matchfile'    |
build	23-Mar-2018 12:25:40	+------------+--------------------------------------+
build	23-Mar-2018 12:25:40	| git_url    | git@bitbucket.org:boojgit/certifica  |
build	23-Mar-2018 12:25:40	|            | tes.git                              |
build	23-Mar-2018 12:25:40	| git_branch | master                               |
build	23-Mar-2018 12:25:40	| type       | enterprise                           |
build	23-Mar-2018 12:25:40	| username   | mobile@activewebsite.com             |
build	23-Mar-2018 12:25:40	+------------+--------------------------------------+
build	23-Mar-2018 12:25:40	
build	23-Mar-2018 12:25:40	
build	23-Mar-2018 12:25:40	+-----------------------+--------------------------------------+
build	23-Mar-2018 12:25:40	|                   [32mSummary for match 2.86.2[0m                   |
build	23-Mar-2018 12:25:40	+-----------------------+--------------------------------------+
build	23-Mar-2018 12:25:40	| app_identifier        | ["com.activewebsite.lyon-beta"]      |
build	23-Mar-2018 12:25:40	| git_url               | git@bitbucket.org:boojgit/certifica  |
build	23-Mar-2018 12:25:40	|                       | tes.git                              |
build	23-Mar-2018 12:25:40	| git_branch            | master                               |
build	23-Mar-2018 12:25:40	| type                  | enterprise                           |
build	23-Mar-2018 12:25:40	| username              | mobile@activewebsite.com             |
build	23-Mar-2018 12:25:40	| keychain_name         | login.keychain                       |
build	23-Mar-2018 12:25:40	| keychain_password     | ********                             |
build	23-Mar-2018 12:25:40	| readonly              | false                                |
build	23-Mar-2018 12:25:40	| team_id               | E65YP8XL5R                           |
build	23-Mar-2018 12:25:40	| verbose               | false                                |
build	23-Mar-2018 12:25:40	| force                 | false                                |
build	23-Mar-2018 12:25:40	| skip_confirmation     | false                                |
build	23-Mar-2018 12:25:40	| shallow_clone         | false                                |
build	23-Mar-2018 12:25:40	| clone_branch_directly | false                                |
build	23-Mar-2018 12:25:40	| force_for_new_devices | false                                |
build	23-Mar-2018 12:25:40	| skip_docs             | false                                |
build	23-Mar-2018 12:25:40	| platform              | ios                                  |
build	23-Mar-2018 12:25:40	+-----------------------+--------------------------------------+
build	23-Mar-2018 12:25:40	
build	23-Mar-2018 12:25:40	[12:25:40]: Cloning remote git repo...
build	23-Mar-2018 12:25:40	[12:25:40]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
build	23-Mar-2018 12:25:42	[12:25:42]: [32m🔓  Successfully decrypted certificates repo[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [33mYou can also run `fastlane match` in readonly mode to not require any access to the[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [33mDeveloper Portal. This way you only share the keys and credentials[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [36m$ fastlane match --readonly[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [33mMore information https://docs.fastlane.tools/actions/match/#access-control[0m
build	23-Mar-2018 12:25:42	[12:25:42]: Verifying that the certificate and profile are still valid on the Dev Portal...
build	23-Mar-2018 12:25:42	[32m-------------------------------------------------------------------------------------[0m
build	23-Mar-2018 12:25:42	[32mPlease provide your Apple Developer Program account credentials[0m
build	23-Mar-2018 12:25:42	[32mThe login information you enter will be stored in your macOS Keychain[0m
build	23-Mar-2018 12:25:42	[32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
build	23-Mar-2018 12:25:42	[32mSee more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
build	23-Mar-2018 12:25:42	[32m-------------------------------------------------------------------------------------[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [32m---------------------[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [32m--- Step: hipchat ---[0m
build	23-Mar-2018 12:25:42	[12:25:42]: [32m---------------------[0m
build	23-Mar-2018 12:25:42	+------------------+----------------+
build	23-Mar-2018 12:25:42	|           [33mLane Context[0m            |
build	23-Mar-2018 12:25:42	+------------------+----------------+
build	23-Mar-2018 12:25:42	| DEFAULT_PLATFORM | ios            |
build	23-Mar-2018 12:25:42	| ENVIRONMENT      | lyon           |
build	23-Mar-2018 12:25:42	| PLATFORM_NAME    | ios            |
build	23-Mar-2018 12:25:42	| LANE_NAME        | ios enterprise |
build	23-Mar-2018 12:25:42	+------------------+----------------+
build	23-Mar-2018 12:25:42	[12:25:42]: [31mMissing password for user mobile@activewebsite.com, and running in non-interactive shell[0m
build	23-Mar-2018 12:25:42	
build	23-Mar-2018 12:25:42	+------+------------------------+-------------+
build	23-Mar-2018 12:25:42	|              [32mfastlane summary[0m               |
build	23-Mar-2018 12:25:42	+------+------------------------+-------------+
build	23-Mar-2018 12:25:42	| Step | Action                 | Time (in s) |
build	23-Mar-2018 12:25:42	+------+------------------------+-------------+
build	23-Mar-2018 12:25:42	| 1    | Verifying fastlane     | 0           |
build	23-Mar-2018 12:25:42	|      | version                |             |
build	23-Mar-2018 12:25:42	| 2    | default_platform       | 0           |
build	23-Mar-2018 12:25:42	| 3    | git rev-parse --short  | 0           |
build	23-Mar-2018 12:25:42	|      | HEAD 2> /dev/null |    |             |
build	23-Mar-2018 12:25:42	|      | sed 's/(.*)//'        |             |
build	23-Mar-2018 12:25:42	| 💥   | [31mmatch[0m                  | 2           |
build	23-Mar-2018 12:25:42	| 5    | hipchat                | 0           |
build	23-Mar-2018 12:25:42	+------+------------------------+-------------+
build	23-Mar-2018 12:25:42	
build	23-Mar-2018 12:25:42	[12:25:42]: [31mfastlane finished with errors[0m
build	23-Mar-2018 12:25:43	
build	23-Mar-2018 12:25:43	Looking for related GitHub issues on fastlane/fastlane...
build	23-Mar-2018 12:25:43	
build	23-Mar-2018 12:25:43	Found no similar issues. To create a new issue, please visit:
build	23-Mar-2018 12:25:43	https://github.com/fastlane/fastlane/issues/new
build	23-Mar-2018 12:25:43	Run `fastlane env` to append the fastlane environment to your issue
error	23-Mar-2018 12:25:43	/Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/credentials_manager/lib/credentials_manager/account_manager.rb:131:in `ask_for_login': [31m[!] Missing password for user mobile@activewebsite.com, and running in non-interactive shell[0m (RuntimeError)
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/credentials_manager/lib/credentials_manager/account_manager.rb:52:in `password'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/spaceship/lib/spaceship/client.rb:348:in `login'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/spaceship/lib/spaceship/client.rb:71:in `login'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/spaceship/lib/spaceship/portal/spaceship.rb:95:in `login'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/match/lib/match/spaceship_ensure.rb:22:in `initialize'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/match/lib/match/runner.rb:33:in `new'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/match/lib/match/runner.rb:33:in `run'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:231:in `chdir'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
error	23-Mar-2018 12:25:43		from Fastfile:39:in `block (2 levels) in parsing_binding'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/lane.rb:33:in `call'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/gems/fastlane-2.86.2/bin/fastlane:20:in `<top (required)>'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
error	23-Mar-2018 12:25:43		from /Users/mobile/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
simple	23-Mar-2018 12:25:43	Failing task since return code of [/Users/mobile/Downloads/atlassian-bamboo-6.3.1/temp/epb9084636930285549639.sh enterprise --env lyon] was 1 while expected 0
simple	23-Mar-2018 12:25:43	Finished task 'fastlane pluging' with result: Failed
simple	23-Mar-2018 12:25:43	Running post build plugin 'NCover Results Collector'
simple	23-Mar-2018 12:25:43	Running post build plugin 'Artifact Copier'
simple	23-Mar-2018 12:25:43	Running post build plugin 'npm Cache Cleanup'
simple	23-Mar-2018 12:25:43	Running post build plugin 'Clover Results Collector'
simple	23-Mar-2018 12:25:43	Running post build plugin 'Docker Container Cleanup'
simple	23-Mar-2018 12:25:43	Finalising the build...
simple	23-Mar-2018 12:25:43	Stopping timer.
simple	23-Mar-2018 12:25:43	Build BAMBOO-IOS-JOB1-10 completed.
simple	23-Mar-2018 12:25:43	Running on server: post build plugin 'NCover Results Collector'
simple	23-Mar-2018 12:25:43	Running on server: post build plugin 'Build Hanging Detection Configuration'
simple	23-Mar-2018 12:25:43	Running on server: post build plugin 'Clover Delta Calculator'
simple	23-Mar-2018 12:25:43	Running on server: post build plugin 'Maven Dependencies Postprocessor'
simple	23-Mar-2018 12:25:43	All post build plugins have finished
simple	23-Mar-2018 12:25:43	Generating build results summary...
simple	23-Mar-2018 12:25:43	Saving build results to disk...
simple	23-Mar-2018 12:25:43	Logging substituted variables...
simple	23-Mar-2018 12:25:43	Indexing build results...
simple	23-Mar-2018 12:25:43	Finished building BAMBOO-IOS-JOB1-10.
</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.29.0"

default_platform :ios



platform :ios do
  before_all do
    ENV["HIPCHAT_API_TOKEN"] = "XXXXXXXXXX"
    ENV["MATCH_PASSWORD"] = "XXXXXXX"
    ENV["GIT_CHECKOUT"] = sh("git rev-parse --short HEAD 2> /dev/null | sed 's/\(.*\)/\1/'")
    # cocoapods
  end


  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build Enterprise IPA"
  lane :enterprise do |target|
    puts "target name #{ENV["ENV_SCHEME"]} bundle #{ENV["ENV_APP_ID"]}"
    #increment_build_number
    match(app_identifier: ENV["ENV_APP_ID"])
    gym(workspace: "./iOS-Core.xcworkspace", scheme: ENV["ENV_SCHEME"], export_method: "enterprise", clean: true, export_xcargs: "-allowProvisioningUpdates")

    sh("./upload.sh #{ENV["UPLOAD_FOLDER"]} #{ENV["ENV_BUILD_DIR"]}")
    hipchat(
        version: "1",
        channel: "3838648",
        message: "A new version of Lyon is available on the FTP - @#{ENV['GIT_CHECKOUT']}" # "Mobile Build Room"
      )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    sigh(
      adhoc: false # otherwise sigh will produce an ad-hoc profile
    )
    snapshot
    gym(scheme: "iOS-Core") # Build your app - more options available
    deliver(force: true)
        hipchat(
      version: "1",
      channel: "3838648",
      message: "A new version of WKRE has been uploaded to iTunes Connect." # "Mobile Build Room"
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|
    hipchat(
      version: "1",
      channel: "3838648",
      custom_color: "red",
      message: "WKRE build failed - @#{ENV['GIT_CHECKOUT']}" # "Mobile Build Room"
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Enerprise Distribution Account
for_lane :enterprise do
#	app_identifier "xxxxxxxxxx" # The bundle identifier of your app
	apple_id "xxxxx@xxxxxxxx" # Your Apple email address
	team_id "XXXXXXXXX" # Developer Portal Team ID
end	
# App Store Production Account

  for_lane :release do
    app_identifier 'xxxxxxxxxx' # The bundle identifier of your app
    apple_id 'xxxxxxxxxx@xxxxxxxx' # Your Apple email address
    team_id 'XXXXXXXXX' # Developer Portal Team ID
  end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.86.2  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2018-03-23**
</details></pre>
</details>

**Comment by jwilson85** [comment]
Not sure it is a code sing issue due to the fact it works when run via terminal.

**Comment by joshdholtz** [comment]
@jwilson85 It _might_ be a code sign issue 😬 Is bamboo running as a different user with different permissions? Does `security find-identity -p codesigning` return the same results when run as your use and when run in bamboo?

We have some actions for setting up CI's so you might have to do something similar to this `setup_jenkins` action - https://docs.fastlane.tools/actions/setup_jenkins/#setup_jenkins

**Comment by jwilson85** [comment]
ya they both look the same to me. 
code```

27-Mar-2018 11:24:31 | Policy: Code Signing
-- | --
27-Mar-2018 11:24:31 | Matching identities
27-Mar-2018 11:24:31 | 1) 1B46EE31E4ABFAABFA5FE7DD3BE68BAE2B3260C0 "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 2) 310D5913ADE3A23147B7D503C2EC081821F54DD6 "iPhone Developer: Tyler Olmsted (AXP4KCHDF4)" (CSSMERR_TP_CERT_REVOKED)
27-Mar-2018 11:24:31 | 3) 18909DF2A284FF23884B3BF17D5D25F4EAA41599 "iPhone Developer: mobile@activewebsite.com (XU4JD8EQ38)"
27-Mar-2018 11:24:31 | 4) E916184F40F9A41E7E7D57227CCAC6713F6894E6 "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 5) FD48F876804D2F62071698BBEC1D4BC44466E2DE "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 6) D8AD64D15F97A276407C8EB6F91B663B3CBE77C3 "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 6 identities found
27-Mar-2018 11:24:31 |  
27-Mar-2018 11:24:31 | Valid identities only
27-Mar-2018 11:24:31 | 1) 1B46EE31E4ABFAABFA5FE7DD3BE68BAE2B3260C0 "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 2) 310D5913ADE3A23147B7D503C2EC081821F54DD6 "iPhone Developer: Tyler Olmsted (AXP4KCHDF4)" (CSSMERR_TP_CERT_REVOKED)
27-Mar-2018 11:24:31 | 3) 18909DF2A284FF23884B3BF17D5D25F4EAA41599 "iPhone Developer: mobile@activewebsite.com (XU4JD8EQ38)"
27-Mar-2018 11:24:31 | 4) E916184F40F9A41E7E7D57227CCAC6713F6894E6 "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 5) FD48F876804D2F62071698BBEC1D4BC44466E2DE "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 6) D8AD64D15F97A276407C8EB6F91B663B3CBE77C3 "iPhone Distribution: Active Website LLC"
27-Mar-2018 11:24:31 | 6 valid identities found

```

code```
  Matching identities
  1) 1B46EE31E4ABFAABFA5FE7DD3BE68BAE2B3260C0 "iPhone Distribution: Active Website LLC"
  2) 310D5913ADE3A23147B7D503C2EC081821F54DD6 "iPhone Developer: Tyler Olmsted (AXP4KCHDF4)" (CSSMERR_TP_CERT_REVOKED)
  3) 18909DF2A284FF23884B3BF17D5D25F4EAA41599 "iPhone Developer: mobile@activewebsite.com (XU4JD8EQ38)"
  4) E916184F40F9A41E7E7D57227CCAC6713F6894E6 "iPhone Distribution: Active Website LLC"
  5) FD48F876804D2F62071698BBEC1D4BC44466E2DE "iPhone Distribution: Active Website LLC"
  6) D8AD64D15F97A276407C8EB6F91B663B3CBE77C3 "iPhone Distribution: Active Website LLC"
     6 identities found

  Valid identities only
  1) 1B46EE31E4ABFAABFA5FE7DD3BE68BAE2B3260C0 "iPhone Distribution: Active Website LLC"
  2) 310D5913ADE3A23147B7D503C2EC081821F54DD6 "iPhone Developer: Tyler Olmsted (AXP4KCHDF4)" (CSSMERR_TP_CERT_REVOKED)
  3) 18909DF2A284FF23884B3BF17D5D25F4EAA41599 "iPhone Developer: mobile@activewebsite.com (XU4JD8EQ38)"
  4) E916184F40F9A41E7E7D57227CCAC6713F6894E6 "iPhone Distribution: Active Website LLC"
  5) FD48F876804D2F62071698BBEC1D4BC44466E2DE "iPhone Distribution: Active Website LLC"
  6) D8AD64D15F97A276407C8EB6F91B663B3CBE77C3 "iPhone Distribution: Active Website LLC"
     6 valid identities found
```

**Comment by jwilson85** [comment]
So in the logs, it looks like it was looking for FASTLANE_PASSWORD. I added that ENV with the same password I was using for MATCH_PASSWORD. And bamboo was then able to build. I have no idea why it worked in Terminal and not bamboo. Whatever it works now but that is very weird.
