### ISSUE TITLE
Can I use fastlane for android archive on Windows now?

### ISSUE THREAD

**Issue by HarrisHan** [fastlane/fastlane#12158]
Can I use fastlane for android archive on Windows now?

**Comment by janpio** [comment]
Theoretically - https://github.com/fastlane/fastlane/issues/11687 is far enough that you might be able to install _fastlane_ on Windows and run a few actions. Archiving Android stuff on Windows might be one of those - which one exactly are you looking at?

**Comment by HarrisHan** [comment]
@janpio Thx
