### ISSUE TITLE
iTunes Connect Team Selection doesn't work

### ISSUE THREAD

**Issue by Swolebrain** [fastlane/fastlane#12160]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running fastlane init, fastlane correctly detects that my itunes connect account is tied to two teams (my personal one and my employer). I select my employer's team and it disregards my choice and selects my own team ID. It correctly selects the itc_team_id but uses my personal team for the team_id value in the appfile. I'm posting this again because I've noticed several people have this issue and you guys close it without resolving it. In addition, it's for some reason super difficult to figure out the iTunes Connect Team ID for a team you do not own.

##### Complete output when running fastlane, including the stack trace and command used

Command was `fastlane init`. Here is the relevant bit of output:

<details>
  <pre>
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
1) "Prakash Hosalli" (118977159)
2) "Victor Moreno" (118546770)
1
[07:59:34]: ✅  Logging in with your Apple ID was successful
[07:59:34]: Checking if the app 'ai.akila.health' exists in your Apple Developer Portal...
[07:59:35]: It looks like the app 'ai.akila.health' isn't available on the Apple Developer Portal
[07:59:35]: for the team ID 'MEB3******' on Apple ID 'marjvic@gmail.com'
[07:59:35]: Do you want fastlane to create the App ID for you on the Apple Developer Portal? (y/n)
  </pre>
</details>

MEB3****** is my personal team id. Even though I clearly selected 1 (Prakash team) fastlane looked through my own dev portal.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "akila.xcodeproj")
    build_app(workspace: "akila.xcworkspace", scheme: "akila")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("ai.akila.health") # The bundle identifier of your app
apple_id("marjvic@gmail.com") # Your Apple email address

itc_team_id("118977159") # iTunes Connect Team ID
team_id("MEB344YGTK") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| tty-screen                | 0.6.4        |
| io-console                | 0.4.5        |
| excon                     | 0.61.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.4.0        |
| faraday                   | 0.14.0       |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-03-24**
</details></pre>
</details>

*Please do not merely delete/lock this issue based on some minutia about the contribution guidelines.* Many people are clearly having issues with this. Although fastlane is an awesome tool and I've been using pilot for years, it would be *super helpful* if you could add documentation about how to find the correct values (in particular itc_team_id) to configure your appfile manually. I basically had to delete my fastlane folder and re-run fastlane init to be able to see my employer's itc_team_id (I'm hoping it's right) and make sure my Appfile was right.

**Comment by joshdholtz** [comment]
@Swolebrain 

1) Sorry about your previous issues getting ignored 💔 The amount of issues that can come in at times is overwhelming. We do our best but sometimes things get lost, skipped over, or diagnosed improperly. 

2) I am looking into this 👀

**Comment by joshdholtz** [comment]
@Swolebrain One follow up questions... Do you have multiple iOS Developer teams? Or just multiple iTunesConnect team? In other words, did you get this question asked to you?
```sh
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
```

**Comment by Swolebrain** [comment]
Hey, thanks for the response! 

I never got that question asked. I do not own the other ios developer team, they just added me on itunes connect. I was able to build several times with xcode and manually upload to testflight before.

I ended up figuring out a solution and getting everything to work by following your optional advice (marked as optional under the documentation for match) to simply have an itunes account that everyone shares. This seems like a viable solution, everything is working great. The only minor hiccup I experienced was that fastlane wouldn't pick up the build number from xcode, it would reset it to whatever it thought the build was. However since I only had 5 prior builds I just had to run fastlane beta 6 times before it worked. 

I'm super happy that everything is working.

**Comment by joshdholtz** [comment]
@Swolebrain Glad you got things working! Creating an account only for fastlane to use is definitely the easiest option 😊 Going to close this issue for now but feel free to comment back here or open another issue if something pops back up 

Happy fastlaning 🚀
