### ISSUE TITLE
 invalid byte sequence in US-ASCII (ArgumentError) Jenkins CI with Fastlane

### ISSUE THREAD

**Issue by vizllx** [fastlane/fastlane#12164]
# Archiving always fails , while building from Jenkins using fastlane #

**_Using the following version -_** 

Fastlane version 2.87.0

Gem version 2.3.0

**_Checked my locale configured properly in  bash shell:-_**

`jenkins$ locale

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
`
**_Already added environment variables in ~/.profile , .bash_profile & .bashrc_**

**Here is the log I am getting in Jenkins :-** 

```
/Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:429:in `===': invalid byte sequence in US-ASCII (ArgumentError)
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:429:in `update_test_state'
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:304:in `parse'
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/printer.rb:19:in `pretty_print'
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/bin/xcpretty:84:in `block in <top (required)>'
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/bin/xcpretty:83:in `each_line'
from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/bin/xcpretty:83:in `<top (required)>'
from /usr/local/bin/xcpretty:23:in `load'
from /usr/local/bin/xcpretty:23:in `<main>'
** ARCHIVE FAILED **


The following build commands failed:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/XYZApp-dbbcprewyxrzlaentthzpdpsjtwf/Build/Intermediates.noindex/ArchiveIntermediates/i XYZApp-ID/IntermediateBuildFilesPath/xyzApp.build/Release-iphoneos/XYZApp-ID.build/Script-D0AD36D9D9320DDEB397BE82.sh
(1 failure)
[19:30:58]: [31mExit status: 1[0m
[19:30:58]: [31mYour shell environment is not correctly configured[0m
[19:30:58]: [31mInstead of UTF-8 your shell uses US-ASCII[0m
[19:30:58]: [31mPlease add the following to your '~/.bashrc':[0m
[19:30:58]: 
[19:30:58]: [31m       export LANG=en_US.UTF-8[0m
[19:30:58]: [31m       export LANGUAGE=en_US.UTF-8[0m
[19:30:58]: [31m       export LC_ALL=en_US.UTF-8[0m
[19:30:58]: 
[19:30:58]: [31mYou'll have to restart your shell session after updating the file.[0m
[19:30:58]: [31mIf you are using zshell or another shell, make sure to edit the correct bash file.
```

### What is the solution to this ?

**_Attached Fastlane Environment Report_** 

`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D47)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Developed by  xyzssddd - Software Engineer -company
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
#generated_fastfile_id "6128fbda-b691-4479-ac13-aada4f84534d"

default_platform :ios
puts "Upload to Fabric as per scheme name 1. iOSxyz 2. iOSxyz-TH 3.iOSxyz-ID"
# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
fastlane_require 'dotenv'
lane :uploadToFabric  do
  # build your iOS app
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"

  desc "Increment version number"
      xcodeproj = "./iOSxyz.xcodeproj"
        target = ENV['SCHEME']
      version = get_build_number_from_plist(
        xcodeproj: xcodeproj,
        target: target,
      )
      version_array = version.split(".").map(&:to_i)
      #version_array[0] = version_array[0] + 1
      #version_array[1] = version_array[1] = 0
      #version_array[1] = version_array[2] = 0
      version_array[4] = version_array[4] + 1
      next_version_number = version_array.join(".")
      puts next_version_number
      puts "Using build number: #{version}"
      increment_build_number_in_plist(
       build_number: next_version_number,
       target: ENV['SCHEME']
     )
      #increment_version_number_in_plist(
      #  version_number: next_version_number,
      #  xcodeproj: "./iOSxyz.xcodeproj",
      #  target:ENV['SCHEME']
      #  )

   

  gym(
    scheme: ENV['SCHEME'],  #{}"iOSxyz-TH",
    export_method:"ad-hoc",         #"app-store",   #"ad-hoc",
    export_xcargs: "-allowProvisioningUpdates",
    #disable_xcpretty:true,

    include_bitcode: false,
     export_options: {
 		    uploadBitcode: false,
        uploadSymbols:true,
        compileBitcode: false,
          provisioningProfiles: {
            ENV['BUNDLE_IDENTIFIER'] => ENV['PROVISION_NAME_ADHOC'] #ENV['PROVISION_NAME_APPSTORE']
          },
            "signingStyle": "manual"
          }

     )
  # upload to Beta by Crashlytics
  crashlytics(
    api_token: ENV['API_TOKEN'],
    build_secret:ENV['BUILD_SECRET'],
    groups: "companyInternalQA"
  )
  desc "Send notification in HipChat"
    hipchat(
        api_token: “hh”,
        version: "2",
       message: " Hi, iOS-xyz Testers, a new build of #{ENV['APP_NAME']}-Build-#{next_version_number} is available  in Fabric, kindly check the mail from Fabric to download the latest app. Thanks :)  @here ",
       message_format: "html",
       custom_color: "red",
       channel:ENV['HIPCHAT_GROUP_NAME'],
        notify_room: true,
        success: true
      )

    upload_symbols_to_crashlytics # Upload them to Crashlytics
    clean_build_artifacts # Delete the local dSYM files

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.xyzcountry" # The bundle identifier of your app
apple_id "appledev@company.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| slack-notifier             | 2.3.2        |
| atomos                     | 0.1.2        |
| CFPropertyList             | 3.0.0        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.4        |
| xcodeproj                  | 1.5.7        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.4.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.6.4        |
| tty-cursor                 | 0.5.0        |
| tty-spinner                | 0.8.0        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| excon                      | 0.61.0       |
| faraday                    | 0.14.0       |
| unf_ext                    | 0.0.7.5      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| fastimage                  | 2.1.1        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.5.1        |
| multi_json                 | 1.13.1       |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| dotenv                     | 2.2.1        |
| bundler                    | 1.16.1       |
| faraday_middleware         | 0.12.2       |
| naturally                  | 2.1.0        |
| simctl                     | 1.6.2        |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| little-plugger             | 1.1.4        |
| logging                    | 2.2.2        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.2        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.13.6       |
| json                       | 2.1.0        |
| io-console                 | 0.4.5        |
| libxml-ruby                | 2.9.0        |
| fastlane-plugin-versioning | 0.3.4        |
</details>

*generated on:* **2018-03-25**
</details>`

**Comment by vizllx** [comment]
I don't think it is a  code signing issue.

**Comment by joshdholtz** [comment]
@vizllx Is this error happening within `gym`? If so, it looks like you tried setting `disable_xcpretty: sure`. Did this not fix it at all?

**Comment by joshdholtz** [comment]
@vizllx Also, did you try setting all the locale environment variables from **within** your Jenkins job? Maybe Jenkins isn't picking up your bashrc and whatnot? Can you also try setting them at the top of your `Fastfile`?

**Comment by vizllx** [comment]
Well, I will be closing this issue as I solved it by adding "LC_ALL=en_US.UTF-8" in the Execute Shell option of Jenkin's job, just before calling the fastlane action. Thanks @joshdholtz for your reply.

**Comment by joshdholtz** [comment]
@vizllx Woot, glad you got it! Looks like Jenkin's doesn't inherit stuff from .bashrc (and similar) 🙃 Happy fastlaning 🚀
