### ISSUE TITLE
Deliver does not correctly process release notes

### ISSUE THREAD

**Issue by AndriyGo** [fastlane/fastlane#12163]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am unable to submit an app for review because `deliver` does not set release notes specified for a default language.

I was able to identify the issue for this. In my deliverfile I am specifying the path to metadata at `./fastlane/appTarget/metadata`. As I am not modifying any metadata those are left empty. And this causes an error. As soon as I add an empty `en-US` folder deliver identifies this language and correctly sets the value for its release notes to the one specified for the `default` language in my deliverfile.

Is this not a bug? :) I'd assume that when we set something for the `default` language deliver would set these values for all languages on iTunesConnect regardless of whether we have those language folders. Especially, given that the release notes are not supplied via those folders. They are feeded to deliver through the deliverfile.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[09:20:10]: ------------------------------
[09:20:10]: --- Step: default_platform ---
[09:20:10]: ------------------------------
[09:20:10]: Loading from './fastlane/.env.glxcdu'
[09:20:10]: Driving the lane 'ios GLXCDUSubmit' 🚀
[09:20:10]: ---------------------
[09:20:10]: --- Step: deliver ---
[09:20:10]: ---------------------
[09:20:11]: Successfully loaded '/GLXCDU/Apple/theory_test/repository/fastlane/Deliverfile' 📄

+------------------------+--------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+------------------------+--------------------------------------+
| app_identifier         | xxxxxxxsxxxxxxxxxxxxxxxxxxxxxxxxxx   |
| username               | xxxxxxxxxxxxxxxxxxxx                 |
| submit_for_review      | true                                 |
| skip_screenshots       | true                                 |
| skip_metadata          | false                                |
| force                  | true                                 |
| screenshots_path       | ./fastlane/HazardPerception/screens  |
|                        | hots                                 |
| metadata_path          | ./fastlane/HazardPerception/metadat  |
|                        | a/                                   |
| app_review_information | {:first_name=>"Andriy",              |
|                        | :last_name=>"Gordiychuk",            |
|                        | :phone_number=>"xxxxxxxxxxxxx",      |
|                        | :email_address=>"xxxxxxxxxxxxxxxxxx  |
|                        | ", :demo_user=>"",                   |
|                        | :demo_password=>"", :notes=>""}      |
| submission_information | {:add_id_info_limits_tracking=>true  |
|                        | , :add_id_info_serves_ads=>nil,      |
|                        | :add_id_info_tracks_action=>false,   |
|                        | :add_id_info_tracks_install=>true,   |
|                        | :add_id_info_uses_idfa=>true,        |
|                        | :content_rights_has_rights=>true,    |
|                        | :content_rights_contains_third_part  |
|                        | y_content=>true,                     |
|                        | :export_compliance_platform=>"ios",  |
|                        | :export_compliance_compliance_requi  |
|                        | red=>false,                          |
|                        | :export_compliance_encryption_updat  |
|                        | ed=>false,                           |
|                        | :export_compliance_app_type=>nil,    |
|                        | :export_compliance_is_exempt=>true,  |
|                        | :export_compliance_uses_encryption=  |
|                        | >false,                              |
|                        | :export_compliance_contains_third_p  |
|                        | arty_cryptography=>false,            |
|                        | :export_compliance_contains_proprie  |
|                        | tary_cryptography=>false,            |
|                        | :export_compliance_available_on_fre  |
|                        | nch_store=>true}                     |
| automatic_release      | true                                 |
| app_rating_config_path | ./fastlane/zeroRatingConfig.json     |
| release_notes          | {"default"=>"- Latest 2018 Official  |
|                        | DVSA revision materials.\n\nIf you   |
|                        | enjoy our app, please take a moment  |
|                        | to rate it on the App Store!"}       |
+------------------------+--------------------------------------+

[09:20:11]: Login to iTunes Connect (xxx)
[09:20:14]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.87.0 Summary                            |
+--------------------------------------+--------------------------------------+
| app_version                          | 10.2.2                               |
| skip_binary_upload                   | true                                 |
| release_notes.default                | - Latest 2018 Official DVSA          |
|                                      | revision materials.  If you enjoy    |
|                                      | our app, please take a moment to     |
|                                      | rate it on the App Store!            |
| username                             | xxxxxxxxxxxxxxxxxxxx                 |
| app_identifier                       | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   |
| edit_live                            | false                                |
| platform                             | ios                                  |
| metadata_path                        | ./fastlane/xxxxxxxxxxxxxxxx/metadat  |
|                                      | a/                                   |
| screenshots_path                     | ./fastlane/xxxxxxxxxxxxxxxx/screens  |
|                                      | hots                                 |
| use_live_version                     | false                                |
| skip_screenshots                     | true                                 |
| skip_metadata                        | false                                |
| skip_app_version_update              | false                                |
| force                                | true                                 |
| submit_for_review                    | true                                 |
| reject_if_possible                   | false                                |
| automatic_release                    | true                                 |
| phased_release                       | false                                |
| app_rating_config_path               | ./fastlane/zeroRatingConfig.json     |
| submission_information.add_id_info_  | true                                 |
| limits_tracking                      |                                      |
| submission_information.add_id_info_  | false                                |
| tracks_action                        |                                      |
| submission_information.add_id_info_  | true                                 |
| tracks_install                       |                                      |
| submission_information.add_id_info_  | true                                 |
| uses_idfa                            |                                      |
| submission_information.content_righ  | true                                 |
| ts_has_rights                        |                                      |
| submission_information.content_righ  | true                                 |
| ts_contains_third_party_content      |                                      |
| submission_information.export_compl  | ios                                  |
| iance_platform                       |                                      |
| submission_information.export_compl  | false                                |
| iance_compliance_required            |                                      |
| submission_information.export_compl  | false                                |
| iance_encryption_updated             |                                      |
| submission_information.export_compl  | true                                 |
| iance_is_exempt                      |                                      |
| submission_information.export_compl  | false                                |
| iance_uses_encryption                |                                      |
| submission_information.export_compl  | false                                |
| iance_contains_third_party_cryptogr  |                                      |
| aphy                                 |                                      |
| submission_information.export_compl  | false                                |
| iance_contains_proprietary_cryptogr  |                                      |
| aphy                                 |                                      |
| submission_information.export_compl  | true                                 |
| iance_available_on_french_store      |                                      |
| overwrite_screenshots                | false                                |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | warn                                 |
| app_review_information.first_name    | Andriy                               |
| app_review_information.last_name     | Gordiychuk                           |
| app_review_information.phone_number  | xxxxxxxxxxxxx                        |
| app_review_information.email_addres  | xxxxxxxxxxxxxxxxxx                   |
| s                                    |                                      |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+

[09:20:15]: Making sure the latest version on iTunes Connect matches '10.2.2' from the ipa file...
[09:20:17]: '10.2.2' is the latest version on iTunes Connect
[09:20:20]: Detected languages: ["default"]
[09:20:25]: Setting the app's age rating...
[09:20:28]: Successfully uploaded set of metadata to iTunes Connect
[09:20:30]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[09:20:30]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+------------------------------------+
|                  Summary for precheck 2.87.0                  |
+--------------------------+------------------------------------+
| default_rule_level       | warn                               |
| include_in_app_purchases | true                               |
| app_identifier           | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
| username                 | xxxxxxxxxxxxxxxxxxxx               |
+--------------------------+------------------------------------+

[09:20:30]: Checking app for precheck rule violations
[09:20:38]: Reading in-app purchases. If you have a lot, this might take a while
[09:20:38]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[09:20:45]: Done reading in-app purchases
[09:20:46]: ✅  Passed: No negative  sentiment
[09:20:46]: ✅  Passed: No placeholder text
[09:20:46]: ✅  Passed: No mentioning  competitors
[09:20:46]: ✅  Passed: No future functionality promises
[09:20:46]: ✅  Passed: No words indicating test content
[09:20:46]: ✅  Passed: No curse words
[09:20:46]: ✅  Passed: No words indicating your IAP is free
[09:20:46]: ✅  Passed: Incorrect, or missing copyright date
[09:20:48]: ✅  Passed: No broken urls
[09:20:48]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[09:20:51]: Selecting the latest build...
[09:20:54]: Selecting build 10.2.2 (208)...
[09:20:56]: Successfully selected build
[09:20:56]: Submitting the app for review...
[09:21:02]: An error occurred while executing the `error` block:
[09:21:02]: undefined method `error_info' for #<Spaceship::Tunes::Error:0x007fe9c45d0a38>
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| ENVIRONMENT      | glxcdu           |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios GLXCDUSubmit |
+------------------+------------------+
[09:21:02]: [en-US]: You must detail what's new in this version in English (U.S.). There are one or more errors on the page.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | deliver          | 51          |
+------+------------------+-------------+

[09:21:02]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
	[en-US]: You must detail what's new in this version in English (U.S.). There are one or more errors on the page.</pre>
</details>

**Comment by joshdholtz** [comment]
@AndriyGo 
>I'd assume that when we set something for the default language deliver would set these values for all languages on iTunesConnect regardless of whether we have those language folders. 

^ This assumption is correct **only if** if you have more than one language "enabled" on iTunesConnect. I'm not sure what your current setup is on iTunesConnect but if you only have "English" enabled then the default will only update "English". You will have to enable other languages for the the default to apply to them.

**Comment by AndriyGo** [comment]
@joshdholtz I do have only one language, en-US, and "default" is not being applied to it. Anyway, this is not a huge concern as I can always programmatically check to see if I have the right language folder. It is just a bit inconvenient :)

**Comment by joshdholtz** [comment]
Ummm... I will need to look into this more 🙃

**Comment by ConfusedVorlon** [comment]
I'm seeing the same thing. I have en-US enabled and am setting release notes in my deliverfile

```
release_notes({
  'default' => 'Updated for the iPhone X'
})
```

fwiw - this used to work fine.

for bonus interest - I wrote the code for 'default' language...
