### ISSUE TITLE
Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild

### ISSUE THREAD

**Issue by salqadri** [fastlane/fastlane#12165]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am a first-time fastlane user and am not able to follow the instructions successfully to add fastlane to an existing Swift app. I have XCode 9.2, and when I run the step fastline init, I get an error that it is not able to find xcodebuild. It seems it is trying to look for xcodebuild at:
/Library/Developer/CommandLineTools//usr/bin/xcodebuild

But when I do which xcodebuild, my xcode is installed at /usr/bin/xcodebuild.

Is this a bug in fastlane?

##### Complete output when running fastlane, including the stack trace and command used
[✔] 🚀 
DEBUG [2018-03-25 16:57:11.66]: Checking if there are any plugins that should be loaded...
DEBUG [2018-03-25 16:57:11.75]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
[✔] Looking for iOS and Android projects in current directory...
INFO [2018-03-25 16:57:11.78]: Detected an iOS/macOS project in the current directory: 'Foo.xcworkspace'
INFO [2018-03-25 16:57:11.92]: -----------------------------
INFO [2018-03-25 16:57:11.92]: --- Welcome to fastlane 🚀 ---
INFO [2018-03-25 16:57:11.92]: -----------------------------
INFO [2018-03-25 16:57:11.92]: fastlane can help you with all kinds of automation for your mobile app
INFO [2018-03-25 16:57:11.92]: We recommend automating one task first, and then gradually automating more over time
WARN [2018-03-25 16:57:11.92]: What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
?  2
INFO [2018-03-25 16:57:24.07]: -----------------------------------------------------------
INFO [2018-03-25 16:57:24.07]: --- Setting up fastlane for iOS TestFlight distribution ---
INFO [2018-03-25 16:57:24.07]: -----------------------------------------------------------
INFO [2018-03-25 16:57:24.07]: Parsing your local Xcode project to find the available schemes and the app identifier
DEBUG [2018-03-25 16:57:24.13]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
ERROR [2018-03-25 16:57:24.13]: --------------------
ERROR [2018-03-25 16:57:24.14]: fastlane init failed
ERROR [2018-03-25 16:57:24.14]: --------------------
DEBUG [2018-03-25 16:57:24.14]: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/helper.rb:166:in `xcode_at_least?'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/project.rb:329:in `build_xcodebuild_showbuildsettings_command'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/project.rb:350:in `build_settings'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/project.rb:387:in `default_build_settings'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/project.rb:203:in `default_app_identifier'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/setup/setup_ios.rb:281:in `find_and_setup_xcode_project'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/setup/setup_ios.rb:82:in `ios_testflight'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/setup/setup_ios.rb:48:in `setup_ios'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/setup/setup.rb:108:in `start'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.87.0/bin/fastlane:20:in `<top (required)>'
/usr/local/bin/fastlane:22:in `load'
/usr/local/bin/fastlane:22:in `<main>'
ERROR [2018-03-25 16:57:24.14]: Unable to locate Xcode. Please make sure to have Xcode installed on your machine
WARN [2018-03-25 16:57:24.14]: Something failed while running `fastlane init`
WARN [2018-03-25 16:57:24.14]: Tried using Apple ID with email ''
WARN [2018-03-25 16:57:24.14]: You can either retry, or fallback to manual setup which will create a basic Fastfile
 [2018-03-25 16:57:24.14]: Would you like to fallback to a manual Fastfile? (y/n)

**Comment by saitjr** [comment]
try this: `xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by salqadri** [comment]
I got:
xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/Developer'

Digging into it, it seemed I had my Xcode.app file in the downloads directory. After copying it over to the Applications folder, it worked again. Closing.

Thanks!
