### ISSUE TITLE
Fastlane upload to crashlytics fails with error fetching remote file

### ISSUE THREAD

**Issue by BeliliFahem** [fastlane/fastlane#12161]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ fastlane android_release_upload_beta
[12:59:31]: fastlane detected a Gemfile in the current directory
[12:59:31]: however it seems like you don't use `bundle exec`
[12:59:31]: to launch fastlane faster, please use
[12:59:31]:
[12:59:31]: $ bundle exec fastlane android_release_upload_beta
[12:59:31]:
[12:59:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-----------------------+---------+--------+
|               Used plugins               |
+-----------------------+---------+--------+
| Plugin                | Version | Action |
+-----------------------+---------+--------+
| fastlane-plugin-ionic | 0.0.4   | ionic  |
+-----------------------+---------+--------+

[12:59:34]: Driving the lane 'android_release_upload_beta' 🚀
[12:59:34]: -------------------------
[12:59:34]: --- Step: crashlytics ---
[12:59:34]: -------------------------
[12:59:34]: Downloading Crashlytics Support Library - this might take a minute...
[12:59:37]: $ unzip 'C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip' -d 'C:/Users/user_xxx/Library/CrashlyticsAndroid'
[12:59:37]: ▸ Archive:  C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip
[12:59:37]: ▸ warning [C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip]:  30829 extra bytes at beginning or within zipfile
[12:59:37]: ▸ (attempting to process anyway)
[12:59:37]: ▸ file #1:  bad zipfile offset (local header sig):  30829
[12:59:37]: ▸ (attempting to re-compensate)
[12:59:37]: ▸ inflating: C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics_build.xml
[12:59:37]: ▸ error:  invalid compressed data to inflate
[12:59:37]: ▸ bad CRC 00000000  (should be 313e1340)
[12:59:37]: ▸ file #2:  bad zipfile offset (local header sig):  839
[12:59:37]: ▸ (attempting to re-compensate)
[12:59:37]: ▸ file #2:  bad zipfile offset (local header sig):  839
[12:59:37]: ▸ file #3:  bad zipfile offset (local header sig):  34909
+---------------+-----------------------------+
|                Lane Context                 |
+---------------+-----------------------------+
| PLATFORM_NAME |                             |
| LANE_NAME     | android_release_upload_beta |
+---------------+-----------------------------+
[12:59:37]: Error fetching remote file: Exit status of command 'unzip 'C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip' -d 'C:/Users/user_xxx/Library/CrashlyticsAndroid'' was 2 instead of 0.
Archive:  C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip
warning [C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip]:  30829 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  30829
  (attempting to re-compensate)
  inflating: C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics_build.xml
  error:  invalid compressed data to inflate
 bad CRC 00000000  (should be 313e1340)
file #2:  bad zipfile offset (local header sig):  839
  (attempting to re-compensate)
file #2:  bad zipfile offset (local header sig):  839
file #3:  bad zipfile offset (local header sig):  34909

+------+-------------+-------------+
|         fastlane summary         |
+------+-------------+-------------+
| Step | Action      | Time (in s) |
+------+-------------+-------------+
| 💥   | crashlytics | 3           |
+------+-------------+-------------+

[12:59:37]: fastlane finished with errors

[!] Error fetching remote file: Exit status of command 'unzip 'C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip' -d 'C:/Users/user_xxx/Library/CrashlyticsAndroid'' was 2 instead of 0.
Archive:  C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip
warning [C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip]:  30829 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  30829
  (attempting to re-compensate)
  inflating: C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics_build.xml
  error:  invalid compressed data to inflate
 bad CRC 00000000  (should be 313e1340)
file #2:  bad zipfile offset (local header sig):  839
  (attempting to re-compensate)
file #2:  bad zipfile offset (local header sig):  839
file #3:  bad zipfile offset (local header sig):  34909
</pre>
</details>

### Environment

<details>
  <pre>
   [13:37:30]: fastlane detected a Gemfile in the current directory
[13:37:30]: however it seems like you don't use `bundle exec`
[13:37:30]: to launch fastlane faster, please use
[13:37:30]:
[13:37:30]: $ bundle exec fastlane env
[13:37:30]:
[13:37:30]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:37:32]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                          |
| --------------------------- | ------------------------------ |
| OS                          | UNKNOWN                        |
| Ruby                        | 2.4.3                          |
| Bundler?                    | false                          |
| Git                         | git version 2.15.1.windows.2   |
| Installation Source         | C:/dev/Ruby24-x64/bin/fastlane |
| Host                        | Unknown  ()                    |
| Ruby Lib Dir                | C:/dev/Ruby24-x64/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017     |
| Is contained                | false                          |
| Is homebrew                 | false                          |
| Is installed via Fabric.app | false                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test do
  puts "Hello Mr Belili"
end

desc "Build android Debug"
lane :build_debug do
  ionic(
    platform: 'android',
    prod: false,
    release: false
  )
end


desc "Build Release"
lane :android_release_build do
  ionic(
    platform: 'android',
    prod: true,
    release: true,

    keystore_path: 'certificates-and-keys/android/android-key.keystore',
    keystore_password: 'xxxxxxxxxx',
    keystore_alias: 'android-release-xxx-keystore',
    key_password: 'xxxxxxxxxxx'
  )
end

desc "upload to Beta by Crashlytics"
lane :android_release_upload_beta do
  crashlytics(
    apk_path: "platforms/android/app/build/outputs/apk/release/app-release.apk",
    api_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    build_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    emails: "aaaaaa@email.com"
  )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-ionic | 0.0.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.61.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.5        |
| io-console                | 0.4.6        |
| fastlane-plugin-ionic     | 0.0.4        |
</details>

*generated on:* **2018-03-24**
 </pre>
</details>

**Comment by joshdholtz** [comment]
@BeliliFahem Hey! It looks like you are trying to use fastlane on Windows? If this is the case, fastlane isn't officially supported on Windows yet 🙃 
```
[!] Error fetching remote file: Exit status of command 'unzip 'C:/Users/user_xxx/Library/CrashlyticsAndroid/crashlytics-devtools.zip' -d 'C:/Users/user_xxx/Library/CrashlyticsAndroid'' was 2 instead of 0.
```
