### ISSUE TITLE
the action cocoapods issue

### ISSUE THREAD

**Issue by stevepaks** [fastlane/fastlane#1216]
I think cocoapods action is not working properly.

I wrote Fastfile as below.

...
platform: ios do
    before_all do
        cocoapods
    end
    ...

but latest libraries are not used.
ex) iOSNoob (0.8.2) (latest 0.8.5)

I could use the latest one after updating the cocoapods repos in person.

any problem?

**Comment by stevepaks** [comment]
anyone know about this issue?

**Comment by KrauseFx** [comment]
Please share your complete Fastfile and complete output when running `fastlane`

**Comment by stevepaks** [comment]
thank you for your reploy.
below is the Fastfile.

#Fastfile
fastlane_version "1.39.0"
default_platform :ios
platform :ios do
  before_all do
    cocoapods
  end

  lane :build do |options|
    # sigh
    increment_build_number(build_number: options[:build_number])
    gym(scheme: "Lineage",
        clean: true,
        output_directory: "./ipa-dir/",
        output_name: "Lineage.ipa",
        xcargs: "TARGET=Lineage PROVISIONING_PROFILE="
    ) # Build your app - more options available
    
  end
end


and below is the output agains running fastlane


fastlane ios build build_number:14
[35m[13:56:36]: [0m[33mUsing build_number: 14[0m
[37m[13:56:36]: [0m[32m-------------------------------------------------[0m
[37m[13:56:36]: [0m[32m--- [0m[32mStep: Verifying required fastlane version[0m[32m ---[0m
[37m[13:56:36]: [0m[32m-------------------------------------------------[0m
[37m[13:56:36]: [0mfastlane version valid
[37m[13:56:36]: [0m[32m------------------------------[0m
[37m[13:56:36]: [0m[32m--- [0m[32mStep: default_platform[0m[32m ---[0m
[37m[13:56:36]: [0m[32m------------------------------[0m
[37m[13:56:36]: [0m[32mDriving the lane 'ios build' 🚀[0m
[37m[13:56:36]: [0m[32m-----------------------[0m
[37m[13:56:36]: [0m[32m--- [0m[32mStep: cocoapods[0m[32m ---[0m
[37m[13:56:36]: [0m[32m-----------------------[0m
[37m[13:56:36]: [0m[SHELL COMMAND]: [33mpod install[0m
[37m[13:56:39]: [0m[SHELL]: Updating local specs repositories
[37m[13:56:57]: [0m[SHELL]: 
[37m[13:56:57]: [0m[SHELL]: CocoaPods 1.0.0.beta.2 is available.
[37m[13:56:57]: [0m[SHELL]: To update use: `gem install cocoapods --pre`
[37m[13:56:57]: [0m[SHELL]: [!] This is a test version we'd love you to try.
[37m[13:56:57]: [0m[SHELL]: 
[37m[13:56:57]: [0m[SHELL]: For more information see http://blog.cocoapods.org
[37m[13:56:57]: [0m[SHELL]: and the CHANGELOG for this version http://git.io/BaH8pQ.
[37m[13:56:57]: [0m[SHELL]: 
[37m[13:56:59]: [0m[SHELL]: Analyzing dependencies
[37m[13:57:05]: [0m[SHELL]: Downloading dependencies
[37m[13:57:05]: [0m[SHELL]: Using AFNetworking (2.5.4)
[37m[13:57:05]: [0m[SHELL]: Using Crashlytics (3.3.4)
[37m[13:57:05]: [0m[SHELL]: Using DTCoreText (1.6.17)
[37m[13:57:05]: [0m[SHELL]: Using DTFoundation (1.7.9)
[37m[13:57:05]: [0m[SHELL]: Using FXNotifications (1.0.2)
[37m[13:57:05]: [0m[SHELL]: Using Fabric (1.5.5)
[37m[13:57:05]: [0m[SHELL]: Using GoogleAnalytics (3.13.0)
[37m[13:57:05]: [0m[SHELL]: Using JSCustomBadge (1.0.1)
[37m[13:57:05]: [0m[SHELL]: Using MBProgressHUD (0.9.2)
[37m[13:57:05]: [0m[SHELL]: Using MFSideMenu (0.5.5)
[37m[13:57:05]: [0m[SHELL]: Using MTAnimation (1.2.2)
[37m[13:57:05]: [0m[SHELL]: Using NCMessangerShareKit (0.2.5)
[37m[13:57:05]: [0m[SHELL]: Using SDWebImage (3.7.5)
[37m[13:57:05]: [0m[SHELL]: Using Toast (2.4)
[37m[13:57:05]: [0m[SHELL]: Using UIAlertView+Blocks (0.8.1)
[37m[13:57:05]: [0m[SHELL]: Using iOSNexus (0.4.0)
[37m[14:10:51]: [0m[SHELL]: Using iOSNoob (0.8.2)
[37m[13:57:05]: [0m[SHELL]: Generating Pods project
[37m[13:57:12]: [0m[SHELL]: Integrating client project
[37m[13:57:12]: [0m[SHELL]: Sending stats
[37m[13:57:12]: [0m[SHELL]: Pod installation complete! There are 16 dependencies from the Podfile and 17 total pods installed.
...


The remains output is about building project.
As you can see, the version of iOSNoob is 0.8.2
So I executed the command(pod update) updating local pod repository.
After that fastlane was doing well updating library.

**Comment by KrauseFx** [comment]
It runs `pod install`, and not `pod update`. Replace `cocoapods` with `sh "pod update"` or `sh "cd .. && pod update"` to get this result.

**Comment by stevepaks** [comment]
thank you for your prompt reply.
second one among the commands is well done.

**Comment by KrauseFx** [comment]
Yeah :+1:
