### ISSUE TITLE
[Screengrab] "No screenshots were detected" while screenshots are getting succefully created and copied

### ISSUE THREAD

**Issue by henningBunk** [fastlane/fastlane#12169]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since I switched the api level of the emulator I am using from 23 to 27 I've got some problems.

Screengrab is creating all the screenshots I want but has an error when retreiving them from the device.  The screenshots do get copied from the device to the computer but still, there is an error due to permissions and the error message 'No screenshots were detected' is thrown.

The screenshots are in the folder `fastlane/en-US/images/phoneScreenshots`. In the screengrabfile I set the output folder to `fastlane/screengrab` so would expect them to be in `fastlane/screengrab/en-US/images/phoneScreenshots` as they were with an emulator on api 23.

I think the reason for screengrab to think the screenshots were unsuccesful is the missing permission to read from `/data/data/...`. But I don't know how I can give screengrab this permission.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> (...)
[13:45:13]: ▸ OK (7 tests)
[13:45:13]: Pulling captured screenshots from the device
[13:45:13]: $ adb -s emulator-5554 pull /sdcard/my.app/screengrab /var/folders/0l/mvk3rshn3wb_lv10mc33kx7c0000gp/T/d20180326-17009-58757h
ls: /data/data/my.app/app_screengrab: Permission denied
[13:45:15]: Exit status: 1
[13:45:16]: Screenshots copied to fastlane/en-US/images/phoneScreenshots
[13:45:16]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌</pre>
</details>

### Environment

<details>
  <pre>[14:04:58]: Generating fastlane environment output, this might t                                                                                                                                                ake a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.13.3|
| Ruby                        | 2.5.0                                                                                                                                                                                       |
| Bundler?                    | false                                                                                                                                                                                       |
| Git                         | git version 2.16.3                                                                                                                                                                          |
| Installation Source         | /usr/local/bin/fastlane                                                                                                                                                                     |
| Host                        | Mac OS X 10.13.3 (17D102)                                                                                                                                                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/l                                                                                                                                                ib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                                                                                                                                                  |
| Is contained                | false                                                                                                                                                                                       |
| Is homebrew                 | false                                                                                                                                                                                       |
| Is installed via Fabric.app | false                                                                                                                                                                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents                                                                                                                                                /Developer/ |
| Xcode Version               | 9.2                                                                                                                                                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 3.0.0        |
| excon                     | 0.61.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| gh_inspector              | 1.1.3        |
| multi_json                | 1.13.1       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-03-26**
</pre>
</details>

**Comment by henningBunk** [comment]
As a side effect: The html file with an overview of all the screenshots isn't getting created.

**Comment by joshdholtz** [comment]
@henningBunk It sounds like your new device might not have been created properly. Did you try anything suggested here by rooting the emulator? https://stackoverflow.com/questions/7399028/android-adb-permission-denied

**Comment by henningBunk** [comment]
I checked and you are right, the emulator wasn't rooted. So I tried the following:

1. Start the emulator
2. type `adb root`
3. start fastlane screengrab

Now instead of  
`ls: /data/data/my.app/app_screengrab: Permission denied`  
I am getting  
`ls: /data/data/my.app/app_screengrab: No such file or directory`

When I check manually the directory `/data/data/my.app/app_screenrab` doesn't exist while the screenshots can be found succesfully in `/sdcard/my.app/screengrab/en-US/images/phoneScreenshots/`

**Comment by henningBunk** [comment]
Does somebody has an idea how to fix the `no such file or directory` error? Or can hint me to the source of the problem. Thanks!
