### ISSUE TITLE
updating plist value to empty dict

### ISSUE THREAD

**Issue by anwarhamr** [fastlane/fastlane#12175]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### I'm trying to set the value for my plist value NSAppTransportSecurity/NSExceptionDomains
I have looked at the `set_info_plist_value` and `update_info_plist` but nothing is telling me how to use this with a dict value.

I have the following in my lane:
`set_info_plist_value(path: "./aura_react_native/Info.plist", key: "NSAppTransportSecurity", subkey: "NSExceptionDomains", value: "<dict/>")` 
but when it runs it does the following in my plist value
```	
        <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<string>&lt;dict/&gt;</string>
	</dict>
```
whereas I need it to be 
```	
        <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict/>
	</dict>
```
Can anyone please point me in the right direction?

**Comment by joshdholtz** [comment]
@anwarhamr Something like this should do it for you...
```rb
lane :plist do
  set_info_plist_value(
    path: 'Test/Info.plist',
    key: 'NSAppTransportSecurity',
    value: { 'NSExceptionDomains' => {
        'example1.com' => {
          'NSExceptionAllowsInsecureHTTPLoads' => true
        },
        'example2.com' => {
          'NSExceptionAllowsInsecureHTTPLoads' => true
        }
      }
    }
  )
end
```

**Comment by anwarhamr** [comment]
That did it!  thank you @joshdholtz
