### ISSUE TITLE
"NFC Tag Reading" can not be enabled with CLI of "fastlane produce enable_services".

### ISSUE THREAD

**Issue by kazuhidet** [fastlane/fastlane#12179]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I wanted to use the "NFC Tag Reading" function on the iPhone, but since it was not in "fastlane produce enable_services".

##### Complete output when running fastlane, including the stack trace and command used
macpro: jenkins$ fastlane produce disable_services --nfc-tag-reading --username xxxx@xxxx.xx --team_id XXXXXX --app_identifier xxxx.xxxx.xxxx
[✔] 🚀
[14:29:14]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
invalid option: --nfc-tag-reading

<details>
  <pre>No output.</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /opt/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | /opt/local/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.1       |
| io-console                | 0.4.5        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
</details>

*generated on:* **2018-03-27**
</details></pre>
</details>

**Comment by kazuhidet** [comment]
The reason is that someone forgets to change "produce/lib/produce/commands_generator.rb".

--- a/produce/lib/produce/commands_generator.rb
+++ b/produce/lib/produce/commands_generator.rb
@@ -60,6 +60,7 @@ module Produce
         c.option('--push-notification', 'Enable Push notification (only enables the service, does not configure certificates)')
         c.option('--sirikit', 'Enable SiriKit')
         c.option('--vpn-conf', 'Enable VPN Configuration')
+        c.option('--nfc-tag-reading', 'Enable NFC Tag Reading')

         FastlaneCore::CommanderGenerator.new.generate(Produce::Options.available_options, command: c)

@@ -93,6 +94,7 @@ module Produce
         c.option('--push-notification', 'Disable Push notifications')
         c.option('--sirikit', 'Disable SiriKit')
         c.option('--vpn-conf', 'Disable VPN Configuration')
+        c.option('--nfc-tag-reading', 'Disable NFC Tag Reading')

         FastlaneCore::CommanderGenerator.new.generate(Produce::Options.available_options, command: c)

Also, the description of "--hotspot", "--multipath" and "--nfc-tag-reading" is missing in "fastlane/lib/fastlane/actions/docs/create_app_online.md".

**Comment by joshdholtz** [comment]
Fixed in `2.89.0`
