### ISSUE TITLE
[Supply] SendTimeoutError: execution expired

### ISSUE THREAD

**Issue by damienherve** [fastlane/fastlane#12173]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to upload my apk using supply.
The problem is the SendTimeout is not set and defaults to 120 seconds (which is insufficient in my case)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[12:15:06]: Preparing apk at path 'app/build/outputs/apk/prod/release/app-prod-release.apk' for upload...
D, [2018-03-26T12:15:06.344942 #5004] DEBUG -- : Sending upload start command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?
D, [2018-03-26T12:15:06.437000 #5004] DEBUG -- : Upload status active
D, [2018-03-26T12:15:06.437086 #5004] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:17:09.040847 #5004] DEBUG -- : Error - #<HTTPClient::SendTimeoutError: execution expired>

D, [2018-03-26T12:17:09.843691 #5004] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:17:10.096983 #5004] DEBUG -- : Upload status active
D, [2018-03-26T12:17:10.097083 #5004] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:19:10.817966 #5004] DEBUG -- : Error - #<HTTPClient::SendTimeoutError: execution expired>

D, [2018-03-26T12:19:13.639062 #5004] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:19:13.851417 #5004] DEBUG -- : Upload status active
D, [2018-03-26T12:19:13.851491 #5004] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:21:13.999300 #5004] DEBUG -- : Error - #<HTTPClient::SendTimeoutError: execution expired>

D, [2018-03-26T12:21:18.699165 #5004] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:21:18.873708 #5004] DEBUG -- : Upload status active
D, [2018-03-26T12:21:18.873789 #5004] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:23:19.199522 #5004] DEBUG -- : Error - #<HTTPClient::SendTimeoutError: execution expired>

D, [2018-03-26T12:23:28.681518 #5004] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:23:28.933913 #5004] DEBUG -- : Upload status active
D, [2018-03-26T12:23:28.933994 #5004] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:25:29.470393 #5004] DEBUG -- : Error - #<HTTPClient::SendTimeoutError: execution expired>

D, [2018-03-26T12:25:43.964227 #5004] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:25:44.091235 #5004] DEBUG -- : Upload status active
D, [2018-03-26T12:25:44.091315 #5004] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/apks?upload_id=AEnB2UqsPYVu1hGafud2hkD1zVtIs29qIBBlHrLxrqTIJ1f8LDgTm4e-gwP9svluiXEvMc-NsvFneauJSKKA3xo5vh96qqsyfg&upload_protocol=resumable
D, [2018-03-26T12:26:13.110400 #5004] DEBUG -- : Upload status final
D, [2018-03-26T12:26:13.110970 #5004] DEBUG -- : Success - #<Google::Apis::AndroidpublisherV2::Apk:0x00007fbfc979e358
 @binary=
  #<Google::Apis::AndroidpublisherV2::ApkBinary:0x00007fbfc979c670
   @sha1="3bc3c9dd96b53047d29f96188fa9277af747add1",
   @sha256="23166d22598ab0e3ff50f72a37a83b47b8d1838a8dbd7a6089a6c47c8d012a03">,
 @version_code=7382>

[12:26:13]: Updating track 'beta'...
D, [2018-03-26T12:26:13.111909 #5004] DEBUG -- : Sending HTTP put https://www.googleapis.com/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/tracks/beta?
D, [2018-03-26T12:26:13.587493 #5004] DEBUG -- : 200
D, [2018-03-26T12:26:13.587726 #5004] DEBUG -- : #<HTTP::Message:0x00007fbfc97d7798 @http_header=#<HTTP::Message::Headers:0x00007fbfc97d7770 @http_version="1.1", @body_size=0, @chunked=false, @request_method="PUT", @request_uri=#<Addressable::URI:0x3fdfe4e1a470 URI:https://www.googleapis.com/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073/tracks/beta?>, @request_query=nil, @request_absolute_uri=nil, @status_code=200, @reason_phrase="OK", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Cache-Control", "no-cache, no-store, max-age=0, must-revalidate"], ["Pragma", "no-cache"], ["Expires", "Mon, 01 Jan 1990 00:00:00 GMT"], ["Date", "Mon, 26 Mar 2018 10:26:13 GMT"], ["ETag", "\"DkUKIRIeTDI6nbvWGVHylIeETI4/grUNLSO5CxjCQDXwUWbDbAPMX-M\""], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["X-Content-Type-Options", "nosniff"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], ["Server", "GSE"], ["Alt-Svc", "hq=\":443\"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=\":443\"; ma=2592000; v=\"42,41,39,35\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=*.googleapis.com,O=Google Inc,L=Mountain View,ST=California,C=US>, issuer=#<OpenSSL::X509::Name CN=Google Internet Authority G3,O=Google Trust Services,C=US>, serial=#<OpenSSL::BN:0x00007fbfc9cabb48>, not_before=2018-03-13 18:57:10 UTC, not_after=2018-06-05 18:17:00 UTC>, @http_body=#<HTTP::Message::Body:0x00007fbfc97d76f8 @body="{\n \"track\": \"beta\",\n \"versionCodes\": [\n  7382\n ]\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
D, [2018-03-26T12:26:13.588096 #5004] DEBUG -- : Success - #<Google::Apis::AndroidpublisherV2::Track:0x00007fbfc9caa590
 @track="beta",
 @version_codes=[7382]>

[12:26:13]: Uploading all changes to Google Play...
D, [2018-03-26T12:26:13.588545 #5004] DEBUG -- : Sending HTTP post https://www.googleapis.com/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073:commit?
D, [2018-03-26T12:26:17.465545 #5004] DEBUG -- : 200
D, [2018-03-26T12:26:17.465812 #5004] DEBUG -- : #<HTTP::Message:0x00007fbfc96fd020 @http_header=#<HTTP::Message::Headers:0x00007fbfc96fcff8 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3fdfe4b7f120 URI:https://www.googleapis.com/androidpublisher/v2/applications/com.gmf.android/edits/01203631387240767073:commit?>, @request_query=nil, @request_absolute_uri=nil, @status_code=200, @reason_phrase="OK", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Cache-Control", "no-cache, no-store, max-age=0, must-revalidate"], ["Pragma", "no-cache"], ["Expires", "Mon, 01 Jan 1990 00:00:00 GMT"], ["Date", "Mon, 26 Mar 2018 10:26:17 GMT"], ["ETag", "\"DkUKIRIeTDI6nbvWGVHylIeETI4/VUzhr5IiFDuf53mhdDDaRKlsMsY\""], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["X-Content-Type-Options", "nosniff"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], ["Server", "GSE"], ["Alt-Svc", "hq=\":443\"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=\":443\"; ma=2592000; v=\"42,41,39,35\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=*.googleapis.com,O=Google Inc,L=Mountain View,ST=California,C=US>, issuer=#<OpenSSL::X509::Name CN=Google Internet Authority G3,O=Google Trust Services,C=US>, serial=#<OpenSSL::BN:0x00007fbfcc822920>, not_before=2018-03-13 18:57:10 UTC, not_after=2018-06-05 18:17:00 UTC>, @http_body=#<HTTP::Message::Body:0x00007fbfc96fcf30 @body="{\n \"id\": \"01203631387240767073\",\n \"expiryTimeSeconds\": \"1522066505\"\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
D, [2018-03-26T12:26:17.466125 #5004] DEBUG -- : Success - #<Google::Apis::AndroidpublisherV2::AppEdit:0x00007fbfcc821de0
 @expiry_time_seconds="1522066505",
 @id="01203631387240767073">

[12:26:17]: [32mSuccessfully finished the upload to Google Play</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | fr_FR.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| CFPropertyList            | 3.0.0        |
| highline                  | 1.7.10       |
| excon                     | 0.61.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| retriable                 | 3.1.1        |
| jwt                       | 2.1.0        |
| signet                    | 0.8.1        |
| os                        | 0.9.6        |
| memoist                   | 0.16.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| googleauth                | 0.6.2        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-03-26**
</details></pre>
</details>

### Solution

Set the send_timeout_sec option in supply/lib/supply/client.rb:
```
Google::Apis::ClientOptions.default.application_name = "fastlane - supply"
Google::Apis::ClientOptions.default.application_version = Fastlane::VERSION
Google::Apis::ClientOptions.default.read_timeout_sec = 300
Google::Apis::ClientOptions.default.open_timeout_sec = 300
Google::Apis::ClientOptions.default.send_timeout_sec = 300
Google::Apis::RequestOptions.default.retries = 5
```

or give an environment variable in supply to set it manually, something like SUPPLY_SEND_TIMEOUT

**Comment by rahulmodu** [comment]
i am getting this error in latest version of fastlane ,but i was install 2.66.1 version of fastlane then its worked in 2.66.1. 



[16:09:27]: [31mexecution expired[0m

+------+---------------------+-------------+
|             [32mfastlane summary[0m             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | default_platform    | 0           |
| 3    | gradle              | 31          |
| 💥   | [31msupply[0m              | 61          |
+------+---------------------+-------------+

[16:09:27]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33m[Supply] SendTimeoutError: execution expired[0m
    https://github.com/fastlane/fastlane/issues/12173 [[31mopen[0m] 0 💬
    a week ago

➡️  [33mOBB upload times out (TransmissionError: execution expired)[0m
    https://github.com/fastlane/fastlane/issues/9573 [[32mclosed[0m] 3 💬
    30 Oct 2017

➡️  [33min initialize: execution expired (Faraday::ConnectionFailed)[0m
    https://github.com/fastlane/fastlane/issues/9197 [[32mclosed[0m] 11 💬
    22 Aug 2017

and 21 more at: https://github.com/fastlane/fastlane/search?q=execution%20expired&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': [31m[!] execution expired[0m (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
	from /Library/Ruby/Gems/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:967:in `fetch_access_token'
	from /Library/Ruby/Gems/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token!'
	from /Library/Ruby/Gems/2.3.0/gems/googleauth-0.6.2/lib/googleauth/signet.rb:69:in `fetch_access_token!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/supply/lib/supply/client.rb:63:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/supply/lib/supply/client.rb:36:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/supply/lib/supply/client.rb:36:in `make_from_config'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/supply/lib/supply/uploader.rb:221:in `client'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:34:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by alexnivanov** [comment]
Same here with fastlane-2.93.1 :(
