### ISSUE TITLE
`mkdir': [!] Permission denied @ dir_s_mkdir - fastlane/metadata (Errno::EACCES)

### ISSUE THREAD

**Issue by shailesh2208** [fastlane/fastlane#12180]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have run the command Fastlane supply init and found the permission issue . How can I resolved it
##### Complete output when running fastlane, including the stack trace and command used

  fusioni@fusioni:~$ fastlane supply init
[✔] 🚀 

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
```
/usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': # **# [!] Permission denied @ dir_s_mkdir - fastlane/metadata (Errno::EACCES)**
	from /usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
	from /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
	from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
	from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
	from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
	from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/setup.rb:30:in `store_metadata'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/setup.rb:12:in `block in perform_download'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/setup.rb:11:in `each'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/setup.rb:11:in `perform_download'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/cli_tools_distributor.rb:99:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.87.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
</details>

### Environment

<details>

<details>
  <pre>Fastlane</pre>
</details>

**Comment by joshdholtz** [comment]
@shailesh2208 This appears to be a permissions issue with your local setup. Are you running `fastlane supply init` as a user that has valid permission to make a directory in the local where you are running this? You can test this by running something like `mkdir -p dir1/dir2` which will make a directory called `dir1` with another directory in it called `dir2`
