### ISSUE TITLE
[!] Google Api Error: multiApkShadowedActiveApk: Version 1 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.

### ISSUE THREAD

**Issue by shailesh2208** [fastlane/fastlane#12181]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I found this issue when I have run the command fastlane supply --apk path_to_apk

[!] Google Api Error: multiApkShadowedActiveApk: Version 1 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.

 [15:40:32]: fastlane detected a Gemfile in the current directory
[15:40:32]: however it seems like you don't use `bundle exec`
[15:40:32]: to launch fastlane faster, please use
[15:40:32]: 
[15:40:32]: $ bundle exec fastlane supply --apk /home/fusioni/Downloads/TestFastlaneApp2/app/release/app-release.apk
[15:40:32]: 
[15:40:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------+--------------------------------------+
|                   Summary for supply 2.87.0                    |
+-------------------------+--------------------------------------+
| apk                     | /home/fusioni/Downloads/TestFastlan  |
|                         | eApp2/app/release/app-release.apk    |
| package_name            | mytestapp.test.com.testfastlaneapp   |
| track                   | production                           |
| metadata_path           | ./fastlane/metadata/android          |
| json_key                | /home/fusioni/Downloads/jsonService  |
|                         | .json                                |
| skip_upload_apk         | false                                |
| skip_upload_metadata    | false                                |
| skip_upload_images      | false                                |
| skip_upload_screenshots | false                                |
| validate_only           | false                                |
| check_superseded_tracks | false                                |
+-------------------------+--------------------------------------+

[15:40:34]: Preparing to upload for language 'en-US'...
[15:40:35]: Uploading image file ./fastlane/metadata/android/en-US/images/icon.png...
[15:40:39]: Updating changelog for code version '1' and language 'en-US'...
[15:40:40]: Preparing apk at path '/home/fusioni/Downloads/TestFastlaneApp2/app/release/app-release.apk' for upload...
[15:40:44]: Updating track 'production'...
[15:40:45]: Uploading all changes to Google Play...

[!] Google Api Error: multiApkShadowedActiveApk: Version 1 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.

##### Complete output when running fastlane, including the stack trace and command used

<details>
 
<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

</details>

**Comment by shailesh2208** [comment]
yes, I have APK with the version code 2 and version name 1.1
And one thing I reminds to you that its an beta version that I am trying to update.

**Comment by joshdholtz** [comment]
Did you try setting `check_superseded_tracks: true`?

**Comment by shailesh2208** [comment]
@joshdholtz  yes I have added it . Still have the same issue

**Comment by joshdholtz** [comment]
@shailesh2208 Can you try running these for me and send me the output so I can have some more information to try to replicate your scenario?
```rb
google_play_track_version_codes(
  package_name: 'your.package.name',
  json_key: 'your_key.json',
  track: 'production'
)
google_play_track_version_codes(
  package_name: 'your.package.name',
  json_key: 'your_key.json',
  track: 'beta'
)
google_play_track_version_codes(
  package_name: 'your.package.name',
  json_key: 'your_key.json',
  track: 'alpha'
)
```
