### ISSUE TITLE
Can't build on Jenkins server, how i can fix on this problem ? "Build step 'Execute shell' marked build as failure"

### ISSUE THREAD

**Issue by uthens** [fastlane/fastlane#1218]
Started by user anonymous
Building in workspace /Users/Shared/Jenkins/Home/jobs/iCPSStock/workspace
Updating http://xxx@xxx/svn/icps/stock/tags/3.5.6/iOS at revision '2016-01-27T11:56:25.393 +0700'
At revision 3267
[workspace] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/hudson4929987696912794951.sh
+ fastlane iOS build_for_test_xcodebuild
/Users/Shared/Jenkins/tmp/hudson4929987696912794951.sh: line 2: fastlane: command not found
Build step 'Execute shell' marked build as failure
[OS X] restore keychains as defined in global configuration
[workspace] $ /usr/bin/security list-keychains -s
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /Users/Shared/Jenkins/Home/jobs/iCPSStock/workspace/coverage_reports to /Users/Shared/Jenkins/Home/jobs/iCPSStock/builds/657/htmlreports/HTML_Report
Finished: FAILURE

I tested on my lans on terminal is worked and build succeeded, But don't work when i integrate on Jenkins server build to have the program.

#TESTED
  desc "Build and prepare deployment"
  lane :build_for_test_xcodebuild do
     xcodebuild sdk: "iphoneos", configuration: "release"
  end

**Comment by mandrizzle** [comment]
You probably need to set a environment variable in Jenkins to the location fastlane was installed.

Go to `{jenkins_url}/configure`, scroll down to environment variables, and add:
path: `PATH`
value: `$PATH:/Users/Shared/Jenkins/.gem/ruby/2.0.0/bin` 

You might have to mess around with the value depending on where gem installed fastlane

**Comment by uthens** [comment]
Thank you @mandrizzle but still don't fix you have other solution ? 

I used SVN and i checked on folder: 
/Users/Shared/Jenkins/
    +Home
    +Library
    +tmp
    .bash_history << hidden file
    .subversion << hidden folder 
          - config 
          - README.txt
          - server

I don't see ruby version on those folders

"$PATH:/Users/Shared/Jenkins/.gem/ruby/{your_ruby_version}/bin:/Library/Ruby/Gems/{your_ruby_version}/bin"

**Comment by mandrizzle** [comment]
@uthens try running `gem environment` and look under `GEM PATHS`

**Comment by uthens** [comment]
@mandrizzle, Thanks you again,
1) i try gem environment under fast lane folder and i found 

  - GEM PATHS:
     - /Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
     - /Users/uthen/.gem/ruby/2.1.0

2) I tried input on Execute shell textbook on {jenkins_url}/configure, save and build now, still found the same error.
"$PATH:/Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bin:/Library/Ruby/Gems/2.0.0/bin
"
3) I should be additional some plugin on Jenkins or not ?

**Comment by uthens** [comment]
@ thiagolioy
Do you have any suggestion on this ? 
I try follow step on your same on youtube : https://www.youtube.com/watch?v=i-Fr5L5u1Gs
but still same error exceptions.

**Comment by thiagolioy** [comment]
Could you share your fastfile and error stack please ..

 This video is a little old i dont think that it still applies without adaptation 
To today's version of fastlane .

**Comment by thiagolioy** [comment]
Also check this 
https://github.com/fastlane/examples/blob/master/README.md

A repo with several fastlane examples from different projects with different requirements

**Comment by thiagolioy** [comment]
First, you have to make sure that you can run your ruby gems from jenkins .. Maybe you have to import your ruby/gems to the jenkins script build phase context . There lots of related errors on google try to look for running ruby gem from jenkins kind of thing ..

**Comment by uthens** [comment]
My lane it's worked under terminal, but don't work if integrate on Jenkins server.

I used : build_for_test_Jenkins 
===================================

# Define the minimal fastlane version
fastlane_version "1.53.0"

# Use the iOS platform as default
default_platform :ios
platform :ios do

  before_all do    ENV["SLACK_URL"] = "https://hooks.slack.com/services/xxxxxxxxx"
    # cocoapods
  end

  desc "Testing on Jenkins server"
  lane :build_for_test_Jenkins do
    cert
    sigh(force: true)
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end

**Comment by uthens** [comment]
build result on terminal: 

fastlane build_for_test_Jenkins 

[17:11:00]: Setting Provisioning Profile type to 'app-store'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cert                                | 10          |
| 4    | sigh                                | 13          |
+------+-------------------------------------+-------------+

[17:11:00]: fastlane.tools finished successfully 🎉

**Comment by uthens** [comment]
@thiagolioy you have web example (step by step) for setup Fastlane + Jenkins ? 

Note: I just download installer file from https://jenkins-ci.org and setup on my mac.

Thanks you

**Comment by thiagolioy** [comment]
Your problem is running gems inside jenkins build .. Differences on the environment are producing this . Try to first make sure you can run gems from jenkins build than you will have no problems with fastlane ... 

Actually this is not a fastlane issue . It is a problem with your jenkins configuration . 

In my video on youtube i've started jenkins from the cmd line , so once it loads it has access to the same paths and vars that my command line does I dont know if you are starting it from a daemon or other way .. 

But again i would search for that before anything else ..

**Comment by uthens** [comment]
Ok, Thanks you for your explained i will try to setup jenkins on command line again and update status soon.
