### ISSUE TITLE
Can't run xctestrun file with scan when created with gym

### ISSUE THREAD

**Issue by dehlen** [fastlane/fastlane#12184]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.3                                         |
| Ruby                        | 2.3.1                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.14.3 (Apple Git-98)               |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane            |
| Host                        | Mac OS X 10.13.3 (17D102)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
  lane :build_with_unit_tests do
    build_lane(
      scheme: "Test",
      configuration: "Debug"
    )
    run_unit_tests
  end

  lane :build_with_unit_and_ui_tests do
    build_lane(
      scheme: "Test",
      configuration: "Debug"
    )
    run_unit_tests
    run_ui_tests
  end

  private_lane :run_unit_tests do |options|
    scan_lane(scheme: "Test", only_testing: 'TestTests')
  end

  private_lane :run_ui_tests do |options|
    scan_lane(scheme: "Test", only_testing: 'TestUITests')
  end

  private_lane :build_lane do |options|
    scheme = options[:scheme]
    configuration = options[:configuration]
    gym(
      scheme: scheme,
      configuration: configuration,
      project: "Test.xcodeproj",
      clean: true,
      include_bitcode: false,
      derived_data_path: "build",
      export_method: "development",
      xcargs: "build-for-testing"
    )
  end

  private_lane :scan_lane do |options|
    scheme = options[:scheme]
    only_testing = options[:only_testing] || []
    scan(
      xctestrun: "build/Build/Products/Test_iphonesimulator11.2-x86_64.xctestrun",
      only_testing: only_testing,
      derived_data_path: "build"
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-03-27**
</details>

I am referring to #8376. I want to build the application via gym and then reuse the build to run unit/uitests for my application. As stated in this issue: #8376 this should be possible by giving gym the `build-for-testing` option via `xcargs`. However when running it like this gym will create an xcarchive in which the .app file is located. When running scan with the created `xctestrun` after this the .app file can not be found because scan is searching for the app in `Build/Products/Debug-(iphoneos/iphonesimulator)/AppName.app`.

Is there any way to use gym to build a valid xctestrun file ? I got it working by replacing gym with xcodebuild because xcodebuild action will run xcodebuild build and not xcodebuild archive. Any help would be much appreciated :).

Btw. I could not append the output of `--capture_output` because it does not print any thing for me. I tried with `bundle exec fastlane ios build_with_unit_and_ui_tests --capture_output.`

**Comment by getaaron** [comment]
@hjanuschka Do you have time to look at this issue? IIRC you have gotten this working before

**Comment by hjanuschka** [comment]
@getaaron , i give it a try 👍 , @dehlen have you tried setting derrived_data path to the same value, in gym and scan? -> https://github.com/fastlane/fastlane/issues/8376#issuecomment-282754603

**Comment by dehlen** [comment]
Yes you can see that in the attaches Fastfile. Both paths are set to „build“.

Thanks for helping out :)

**Comment by dehlen** [comment]
You can test it out by creating a new Single View iOS App called Test with a UnitTest and UITest target. Then the provided Fastfile can be used attached to this issue. You can see that the scan lane will fail because when trying to run the xctestrun file it will search for Test.app in Build/Products/Debug-iphone*/Test.app bit the app is created by gym in Library/.../28-03-2018Test.xcarchive/.../Test.app.

**Comment by dehlen** [comment]
@hjanuschka any other ideas for me ?

**Comment by joshdholtz** [comment]
@dehlen This is way out of my realm but have you tried setting `skip_archive` and/or `skip_build_archive` to `true`?

**Comment by hjanuschka** [comment]
@dehlen ok i tried the test app and your fastfile.


problem is the PR's for adding "native" support for - build-for-testing to gym have been reverted/not-accepted.   https://github.com/fastlane/fastlane/pull/7131



taken the sample from here:
https://github.com/hjanuschka/fastlane-plugin-aws_device_farm
using `xcodebuild` itself, you can achieve what you want.

changing your `gym` call to:

```ruby
    xcodebuild(
        scheme: scheme,
        destination: 'generic/platform=iOS',
        configuration: configuration,
        derivedDataPath: 'build',
        xcargs: "clean build-for-testing"

      )
```

produces the correct xctestrun file.


here is your original fastfile, adopted:


<details>
 <summary>Fastfile</summary>
default_platform :ios

platform :ios do
  lane :build_with_unit_tests do
    build_lane(
      scheme: "Test",
      configuration: "Debug"
    )
    run_unit_tests
  end

  lane :build_with_unit_and_ui_tests do
    build_lane(
      scheme: "Test",
      configuration: "Debug"
    )
    run_unit_tests
    run_ui_tests
  end

  lane :run_unit_tests do |options|
    scan_lane(scheme: "Test", only_testing: 'TestTests')
  end

  lane :run_ui_tests do |options|
    scan_lane(scheme: "Test", only_testing: 'TestUITests')
  end

  private_lane :build_lane do |options|
    scheme = options[:scheme]
    configuration = options[:configuration]
    xcodebuild(
        scheme: scheme,
        destination: 'generic/platform=iOS',
        configuration: configuration,
        derivedDataPath: 'build',
        xcargs: "ENABLE_BITCODE=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build-for-testing"
      )
  end

  lane :scan_lane do |options|
    scheme = options[:scheme]
    only_testing = options[:only_testing] || []
    scan(
      xctestrun: "build/Build/Products/Test_iphoneos11.3-armv7k.xctestrun",
      only_testing: only_testing,
      derived_data_path: "build"
    )
  end
end
</details>

changes:
  - private lanes made public (just for testing)
  - gym replaced with xcodebuild (thats the trick)
  - path adopted for current ios sdk

**Comment by dehlen** [comment]
Thanks, thats what I meant when I wrote 

> I got it working by replacing gym with xcodebuild because xcodebuild action will run xcodebuild build and not xcodebuild archive.

However the problem still persists that my current gym command will produce a valid ipa which is signed by match. How can I replicate this behaviour with xcodebuild ? To me it looks like xcodebuild with run `xcodebuild build` but gym runs` xcodebuild archive`. The example I posted above uses exportMethode development which was only for testing purposes. My gym command which I'd like to replicate with xcodebuild in order to also build-for-testing looks like this:

`gym(
      clean: true,
      scheme: "MyScheme",
      output_directory: output_dir,
      configuration: configuration,
      derived_data_path: "build",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: { 
          "de.some.bundle" => "match AdHoc de.some.bundle"
        },
        compileBitcode: false
      }
    )`
