### ISSUE TITLE
Skip two factor authentication

### ISSUE THREAD

**Issue by atitovdev** [fastlane/fastlane#12194]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi, I use many client accounts and sometimes there 2FA is enabled. My build process running on Jenkins. Is there any easy steps to skip actions like sigh/pilot/deliver if 2FA is enabled?

**Comment by joshdholtz** [comment]
@atitovdev Your best option is to have your client create a new account that **only** fastlane will use. This is one of that best approaches so that your client doesn't need to share their credentials and so that you don't have to use 2FA
