### ISSUE TITLE
Disable pilot action fancy output

### ISSUE THREAD

**Issue by atitovdev** [fastlane/fastlane#12203]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi, how to disable fancy rocket output on pilot action? I need it because on Jenkins it looks like 
`[⠙] � 
[⠹] �
[⠸] �
[⠼] �
... /same 20 times/ ...
[⠏] �
[⠋] �
[⠙] �
[✔] � `
 and each one on next line.

**Comment by joshdholtz** [comment]
@atitovdev Can you try setting an environment variable for`FASTLANE_DISABLE_ANIMATION=true` to see if that does it for you?

**Comment by atitovdev** [comment]
@joshdholtz Thanks! Works like a charm!
