### ISSUE TITLE
[Question] Does fastlane have automatic license agreement implemented?

### ISSUE THREAD

**Issue by mofneko** [fastlane/fastlane#12208]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to automate some iOS product applications by fastlane.
This time we are investigating how much maintenance cost will occur in long term operation.
I wonder the possibility that an irregular occurrence of an iTunes Connect license update may cause an error and stop the build phase.
For example, in the following PR, https://github.com/fastlane/fastlane/commit/82db9eda3da1bc56503431c5a5a1c97048331559
It looks just like displaying an error, but in fact does the function to automatically accept license agreement on fastlane or ignore the error and continue processing?

**Comment by joshdholtz** [comment]
@mofneko fastlane does not have automatic license agreement implemented as this would probably cause some legal issues 😊 fastlane will just stop whatever it is doing until the license agreement is manually read and accepted

**Comment by mofneko** [comment]
Thank you for your reply. I understood the gist of the implementation.
