### ISSUE TITLE
How to use fastlane to submit xcarchive files to the App Store?

### ISSUE THREAD

**Issue by Apocryphon** [fastlane/fastlane#12204]
My usual workflow is to create an Archive in Xcode, then Upload to App Store via Organizer. Looks like `deliver` uploads ipa files to the App Store. Is there anything different involved in submitting an ipa, as opposed to submitting an xcarchive file? Would it make sense to use the `xcarchive` action instead of `deliver`?

**Comment by joshdholtz** [comment]
@Apocryphon `deliver` will only upload an `.ipa` to the App Store. I _think_ the App Store only accepts IPA 🙃 Organizer takes the `xcarchive` and creates a `.ipa` for it and uploads it to the App Store
