### ISSUE TITLE
fastlane match does add iOS distribution certificate to the Debug/development provisioning profile

### ISSUE THREAD

**Issue by alexanderritola** [fastlane/fastlane#12202]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Our development team is having an issue where our Debug provisioning profile does not include the iOS distribution certificate. Instead it uses the iOS Developer certificate. All developers are signed in using the same iOS developer account and all developers are using match to manage certificates and profiles. Is this how match works by design? We need to make sure we're using the same certificate for Debug and Release so iOS Universal linking will work for development and production.

**Comment by saitjr** [comment]
Generate .cert and .p12, push to git repo. When you run match in local, pull from git repo. So it is same certificate for each team member.

**Comment by alexanderritola** [comment]
@saitjr thanks for the response! I'm not sure how to do that... I can't seem to explicitly tell match to use a specific certificate for a specific provisioning profile. Currently I'm generating certificates like this....

```
   lane :regenerate_certificates do
    match(
      app_identifier: "[redacted]",
      type: "development",
      force: true
    )
    match(
      app_identifier: "[redacted]",
      type: "adhoc",
      force: true
    )
    match(
      app_identifier: "[redacted]",
      type: "appstore",
      force: true
    )
  end
```

And developers are retrieving them on their local machines like this...

```
  lane :certificates do
    match(
      app_identifier: "[redacted]",
      type: "development",
      readonly: true
    )
    match(
      app_identifier: "[redacted]",
      type: "adhoc",
      readonly: true
    )
    match(
      app_identifier: "[redacted]",
      type: "appstore",
      readonly: true
    )
  end
```

It seems like what I'd want to would look something like this...

```
   lane :regenerate_certificates do
    match(
      app_identifier: "[redacted]",
      certificate_id: "XYXYXYX",
      type: "development",
      force: true
    )
    match(
      app_identifier: "[redacted]",
      certificate_id: "XYXYXYX",
      type: "adhoc",
      force: true
    )
    match(
      app_identifier: "[redacted]",
      certificate_id: "XYXYXYX",
      type: "appstore",
      force: true
    )
  end
```

**Comment by joshdholtz** [comment]
@alexanderritola `match` does not have the ability to select a certain certificate. Any `development` profiles in `match` will be made with the the user's "Development Certificate". Only `adhoc` and `appstore` will get made with a "Distribution Certificate"

**Comment by alexanderritola** [comment]
Thanks @joshdholtz !
