### ISSUE TITLE
Fastlane not setting provisioning profiles correctly in *.xcodeproj

### ISSUE THREAD

**Issue by lblast** [fastlane/fastlane#12200]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello. I am building Unity projects through Jenkins, and attempting to sign fastlane. The problem I keep having is related to codesigning - it seems that the settings from my Gymfile/Fastfile/Matchfile are not able to actually change the XCode profiles.

I have read a lot of different forum posts related to this topic as well as documentation, so I believe I have done everything correctly. I have attached my Gym/Fast/Match files as well (privacy modified).

If I am on my build machine and I have manually set the .xcodeproj to have signing profiles running fastlane dev will work. However, if they are blank, fastlane dev will not set them even though I have explicitly set them. This follows the advice here: http://puu.sh/zSflp/a882092f90.png

I have also tried just using fastlane match -> fastlane gym with the same result (The gym file was configured differently than provided).

I have ran fastlane match nuke development.
I have verified the login.keychain is unlocked and everything has access to the certs.
I have verified that if the .xcodeproj has the settings manually set it will work, but if not set, it will fail.
I set several environment variables related to fastlane: MATCH_PASSWORD, FASTLANE_PASSWORD, WORKSPACE_XCODE (for my Gymfile).

My frustration comes from the following:

1. All required keys, certificates and provisioning profiles are installed (fastlane match output)
2. Detected provisioning profile mapping: {"com.."=>"match Development com..********"} (fastlane dev output)
3. [BCEROR]Code Signing Error: "Unity-iPhone" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor. (fastlane dev output)

The reason I cannot have them manually set is the Unity build process seems to clear the signing identities. Any help with this matter is greatly appreciated, thank you!

##### Complete output when running fastlane, including the stack trace and command used

The result of fastlane match:
<details>
  <pre>[16:08:33]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[16:08:34]: [32mSuccessfully loaded '/Users/ghc/jenkins_node/workspace/Unity-Arcade/Fastlane/Matchfile' 📄[0m

+----------------+--------------------------------------------------+
|            Detected Values from './Fastlane/Matchfile'            |
+----------------+--------------------------------------------------+
| git_url        | git@bitbucket.org:****** /ios-code-signing.git |
| type           | development                                      |
| app_identifier | ["com.********.************"]                  |
| username       | dev-ops@********inc.com                        |
+----------------+--------------------------------------------------+

+-----------------------+--------------------------------------------------+
|                         [32mSummary for match 2.88.0[0m                         |
+-----------------------+--------------------------------------------------+
| git_url               | git@bitbucket.org:******/ios-code-signing.git |
| git_branch            | master                                           |
| type                  | development                                      |
| app_identifier        | ["com.********.************"]                  |
| username              | dev-ops@********inc.com                        |
| keychain_name         | login.keychain                                   |
| readonly              | false                                            |
| verbose               | false                                            |
| force                 | false                                            |
| skip_confirmation     | false                                            |
| shallow_clone         | false                                            |
| clone_branch_directly | false                                            |
| force_for_new_devices | false                                            |
| skip_docs             | false                                            |
| platform              | ios                                              |
+-----------------------+--------------------------------------------------+

[16:08:34]: Cloning remote git repo...
[16:08:34]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:08:36]: [32m🔓  Successfully decrypted certificates repo[0m
[16:08:36]: Verifying that the certificate and profile are still valid on the Dev Portal...
[16:08:37]: Installing certificate...

+-------------------+-----------------------------------------------+
|                       [32mInstalled Certificate[0m                       |
+-------------------+-----------------------------------------------+
| User ID           | ******                                    |
| Common Name       | iPhone Developer: ****** Inc (******) |
| Organisation Unit | ******                                    |
| Organisation      | ****** Limited                            |
| Country           | US                                            |
| Start Datetime    | 2018-03-29 21:01:51 UTC                       |
| End Datetime      | 2019-03-29 21:01:51 UTC                       |
+-------------------+-----------------------------------------------+

[16:08:38]: Installing provisioning profile...

+---------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
|                                                                                [32mInstalled Provisioning Profile[0m                                                                                |
+---------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                                      | Value                                                                                                      |
+---------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                           | com.********.******                                                                                |
| Type                |                                                           | development                                                                                                |
| Platform            |                                                           | ios                                                                                                        |
| Profile UUID        | sigh_com.********.******_development              | ******-******-******-******-******                                                                       |
| Profile Name        | sigh_com.********.******_development_profile-name | match Development com.********.******                                                              |
| Profile Path        | sigh_com.********.******_development_profile-path | /Users/ghc/Library/MobileDevice/Provisioning Profiles/******************.mobileprovision |
| Development Team ID | sigh_com.********.******_development_team-id      | ******                                                                                                 |
+---------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------+

[16:08:39]: [32m[32mAll required keys, certificates and provisioning profiles are installed 🙌[0m</pre>
</details>

The result of fastlane dev:
<details>
  <pre>[16:20:23]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[16:20:24]: [32mDriving the lane 'dev' 🚀[0m
[16:20:24]: [32m-----------------------[0m
[16:20:24]: [32m--- Step: build_app ---[0m
[16:20:24]: [32m-----------------------[0m
[16:20:24]: [32mSuccessfully loaded '/Users/ghc/jenkins_node/workspace/Unity-************/Fastlane/Gymfile' 📄[0m

+------------------------+-------------------------------------------------------------+
|                      Detected Values from './Fastlane/Gymfile'                       |
+------------------------+-------------------------------------------------------------+
| project                | ../XCode/Unity-iPhone.xcodeproj                             |
| scheme                 | Unity-iPhone                                                |
| include_bitcode        | false                                                       |
| clean                  | true                                                        |
| silent                 | false                                                       |
| skip_profile_detection | true                                                        |
| export_xcargs          | -allowProvisioningUpdates                                   |
| output_directory       | ../XCode/build/                                             |
| output_name            | #1002439 - 18.4.1.1002439-update/BSA-2054-a70ef7ec-QA (iOS) |
+------------------------+-------------------------------------------------------------+

[16:20:24]: [36m$ xcodebuild -showBuildSettings -scheme Unity-iPhone -project ../XCode/Unity-iPhone.xcodeproj -configuration Debug[0m
2018-03-29 16:20:25.738 xcodebuild[9436:1423604] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[16:20:27]: Detected provisioning profile mapping: {"com.********.************"=>"match Development com.********.************"}
`<PBXGroup name=`Supporting Files` UUID=`5623C57917FDCB0800090B9E`>` attempted to initialize an object with an unknown UUID. `5623C57B17FDCB0900090B9E` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
`<PBXBuildFile UUID=`5623C57D17FDCB0900090B9E`>` attempted to initialize an object with an unknown UUID. `5623C57B17FDCB0900090B9E` for attribute: `file_ref`. This can be the result of a merge and  the unknown UUID is being discarded.
`<PBXNativeTarget name=`Unity-iPhone Tests` UUID=`5623C57217FDCB0800090B9E`>` attempted to initialize an object with an unknown UUID. `5623C58217FDCB0900090B9E` for attribute: `dependencies`. This can be the result of a merge and  the unknown UUID is being discarded.

+-----------------------------------------------------------------+-------------------------------------------------------------+
|                                                    [32mSummary for gym 2.88.0[0m                                                     |
+-----------------------------------------------------------------+-------------------------------------------------------------+
| export_method                                                   | development                                                 |
| export_options.provisioningProfiles.com.********.************ | match Development com.********.************               |
| configuration                                                   | Debug                                                       |
| destination                                                     | generic/platform=iOS                                        |
| build_path                                                      | /Users/ghc/Library/Developer/Xcode/Archives/2018-03-29      |
| project                                                         | ../XCode/Unity-iPhone.xcodeproj                             |
| scheme                                                          | Unity-iPhone                                                |
| clean                                                           | true                                                        |
| output_directory                                                | ../XCode/build/                                             |
| output_name                                                     | #1002439 - 18.4.1.1002439-update_BSA-2054-a70ef7ec-QA (iOS) |
| silent                                                          | false                                                       |
| skip_package_ipa                                                | false                                                       |
| include_bitcode                                                 | false                                                       |
| export_xcargs                                                   | -allowProvisioningUpdates                                   |
| buildlog_path                                                   | ~/Library/Logs/gym                                          |
| skip_profile_detection                                          | true                                                        |
| xcode_path                                                      | /Applications/Xcode.app                                     |
+-----------------------------------------------------------------+-------------------------------------------------------------+

[16:20:27]: [36m$ set -o pipefail && xcodebuild -scheme Unity-iPhone -project ../XCode/Unity-iPhone.xcodeproj -configuration Debug -destination 'generic/platform=iOS' -archivePath /Users/ghc/Library/Developer/Xcode/Archives/2018-03-29/\#1002439\ -\ 18.4.1.1002439-update_BSA-2054-a70ef7ec-QA\ \(iOS\)\ 2018-03-29\ 16.20.27.xcarchive clean archive | tee /Users/ghc/Library/Logs/gym/************-Unity-iPhone.log | xcpretty[0m
[16:20:28]: ▸ [35m2018-03-29 16:20:28.459 xcodebuild[9453:1423683] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs[0m
[16:20:29]: [35m[33m▸[0m [39;1mCleaning[0m Unity-iPhone/Unity-iPhone [Debug][0m
[16:20:29]: [35m[33m▸[0m [39;1mCheck Dependencies[0m
[16:20:33]: ▸ [35m[31m❌  [BCEROR]Code Signing Error: "Unity-iPhone" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor.[0m
[16:20:33]: [35m[33m▸[0m [39;1mClean[0m Succeeded[0m
[16:20:33]: [35m[33m▸[0m [39;1mBuilding[0m Unity-iPhone/Unity-iPhone [Debug][0m
[16:20:33]: [35m[33m▸[0m [39;1mCheck Dependencies[0m
[16:20:36]: ▸ [35m[31m❌  Code Signing Error: "Unity-iPhone" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor.[0m
[16:20:36]: ▸ [35m** ARCHIVE FAILED **[0m
[16:20:36]: ▸ [35mThe following build commands failed:[0m
[16:20:36]: ▸ [35mCheck dependencies[0m
[16:20:36]: ▸ [35m(1 failure)[0m
2018-03-29 16:20:28.459 xcodebuild[9453:1423683] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[33m▸[0m [39;1mCleaning[0m Unity-iPhone/Unity-iPhone [Debug]
[33m▸[0m [39;1mCheck Dependencies[0m

[31m❌  [BCEROR]Code Signing Error: "Unity-iPhone" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor.[0m

[33m▸[0m [39;1mClean[0m Succeeded
[33m▸[0m [39;1mBuilding[0m Unity-iPhone/Unity-iPhone [Debug]
[33m▸[0m [39;1mCheck Dependencies[0m

[31m❌  Code Signing Error: "Unity-iPhone" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor.[0m</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Environment specific build settings

lane :dev do
  build_app(
    export_method: "development",
    export_options: {
      provisioningProfiles: { 
        "com.###.###" => "match Development com.###.###",
      }
    }
    configuration: "Debug"
  )
end

lane :adhoc do
  build_app(
    export_method: "ad-hoc",
    export_options: {
      provisioningProfiles: { 
        "com.###.###" => "match AdHoc com.###.###",
      }
    }
    configuration: "Debug"
  )
end

lane :release do
  build_app(
    export_method: "app-store",
    export_options: {
      provisioningProfiles: { 
        "com.###.###" => "match AppStore com.###.###",
      }
    }
    configuration: "Release",
    include_symbols: true
  )
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.88.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| openssl                   | 2.0.2        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.61.0       |
| rubyzip                   | 1.2.1        |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.1        |
| plist                     | 3.4.0        |
| faraday                   | 0.14.0       |
| fastimage                 | 2.1.1        |
| json                      | 2.1.0        |
| bundler                   | 1.16.1       |
</details>

*generated on:* **2018-03-29**
</details></pre>
</details>

Attached files:
Gymfile, Fastfile, Matchfile

[Fastlane.zip](https://github.com/fastlane/fastlane/files/1862245/Fastlane.zip)

**Comment by ReggaePanda** [comment]
have same issue

**Comment by joshdholtz** [comment]
I have never used Unity myself so I don't know what weird stuff goes on but you can always try to run this plugin - https://github.com/faithfracture/update_provisioning_profile_specifier

```rb
update_provisioning_profile_specifier(
      new_specifier: "com.your.unity-project",
      configuration: 'Release'
    )
```

Happy fastlaning 🚀

**Comment by lblast** [comment]
I did try several methods mainly:
- Setting export_options with provisioningProfiles (specifying the certificate to use)
- Setting the codesigning_identity to match the keychain

I have mainly been building these with Debug configuration.

**Comment by joshdholtz** [comment]
@lblast My bad! `update_provisioning_profile_specifier` is a plugin that you need to install 😊 https://github.com/faithfracture/update_provisioning_profile_specifier

**Comment by lblast** [comment]
I believe I had version 1.3.0 installed.

**Comment by joshdholtz** [comment]
@lblast You will need to run `fastlane add_plugin update_provisioning_profile_specifier` and then modify your `Fastfile` to look something like...
```rb
lane :build do
  update_provisioning_profile_specifier(
    new_specifier: 'TestApp App Store',
    configuration: 'Release'
  )
  gym
end
```

**Comment by lblast** [comment]
It seems that the plugin has a bug (or I'm using it incorrectly?).

I tried several versions of my fastfile:

`lane :dev do
  update_provisioning_profile_specifier(
    new_specifier: 'match Development com.###.###',
    configuration: 'Debug'
  )
  gym
end`

`lane :dev do
  update_provisioning_profile_specifier
end`

Sorry I don't know how to format the code block nicely like you...

Both of these gave me the error:
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-plugin-update_provisioning_profile_specifier-1.3.0/lib/fastlane/plugin/update_provisioning_profile_specifier/actions/update_provisioning_profile_specifier_action.rb:13:in `join': [!] no implicit conversion of nil into String (TypeError)
    from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-plugin-update_provisioning_profile_specifier-1.3.0/lib/fastlane/plugin/update_provisioning_profile_specifier/actions/update_provisioning_profile_specifier_action.rb:13:in `run'

http://puu.sh/A0lmw/9262eb4e88.jpg

**Comment by lblast** [comment]
After some additional work I think the plugin is working as intended.

When building I get the following:

+-----------------------+--------------------------------------------------+
|                         [32mSummary for match 2.89.0[0m                         |
+-----------------------+--------------------------------------------------+
| git_url               | git@bitbucket.org:###/ios-code-signing.git |
| git_branch            | master                                           |
| type                  | development                                      |
| app_identifier        | ["com.********.###"]                  |
| username              | dev-ops@********inc.com                        |
| keychain_name         | login.keychain                                   |
| readonly              | false                                            |
| verbose               | false                                            |
| force                 | false                                            |
| skip_confirmation     | false                                            |
| shallow_clone         | false                                            |
| clone_branch_directly | false                                            |
| force_for_new_devices | false                                            |
| skip_docs             | false                                            |
| platform              | ios                                              |
+-----------------------+--------------------------------------------------+


+-------------------+-----------------------------------------------+
|                       [32mInstalled Certificate[0m                       |
+-------------------+-----------------------------------------------+
| User ID           | G3B8W6MUG4                                    |
| Common Name       | iPhone Developer: ### Inc (###) |
| Organisation Unit | ###                                    |
| Organisation      | ###                            |
| Country           | US                                            |
| Start Datetime    | 2018-03-29 21:01:51 UTC                       |
| End Datetime      | 2019-03-29 21:01:51 UTC                       |
+-------------------+-----------------------------------------------+


+---------------------+-----------+----------------------------------------------+
|            [32mInstalled Provisioning Profile[0m 
+---------------------+------------------------------------------------------+

(Output suppressed) 

Resulting in:
All required keys, certificates and provisioning profiles are installed


Then the build starts:

+-------------------------------------------------------+---------+---------------------------------------+
|                                              [32mUsed plugins[0m                                               |
+-------------------------------------------------------+---------+---------------------------------------+
| Plugin                                                | Version | Action                                |
+-------------------------------------------------------+---------+---------------------------------------+
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0   | update_provisioning_profile_specifier |
+-------------------------------------------------------+---------+---------------------------------------+

Successfully updated project settings in '../XCode/Unity-iPhone.xcodeproj'


+----------------------+-------------------------------------------------------------+
|                     Detected Values from './Fastlane/Gymfile'                      |
+----------------------+-------------------------------------------------------------+
| project              | ../XCode/Unity-iPhone.xcodeproj                             |
| scheme               | Unity-iPhone                                                |
| include_bitcode      | false                                                       |
| clean                | true                                                        |
| silent               | false                                                       |
| export_team_id       | ###                                       |
| codesigning_identity | iPhone Developer: ### Inc (###)               |
| export_xcargs        | -allowProvisioningUpdates                                   |
| output_directory     | ../XCode/build/                                             |
| output_name          | #1002580 - 18.4.1.1002580-update/BSA-2054-0132c966-QA (iOS) |
+----------------------+-------------------------------------------------------------+


+-----------------------------------------------------------------+-------------------------------------------------------------+
|                                                    [32mSummary for gym 2.89.0[0m                                                     |
+-----------------------------------------------------------------+-------------------------------------------------------------+
| export_method                                                   | development                                                 |
| export_team_id                                                  | ### Limited                                          |
| export_options.provisioningProfiles.com.********.###| match Development com.********.###|
| export_options.teamID                                           | ###Limited                                          |
| export_options.installerSigningCertificate                      | iPhone Developer: ###Inc (###)               |
| configuration                                                   | Debug                                                       |
| destination                                                     | generic/platform=iOS                                        |
| build_path                                                      | /Users/ghc/Library/Developer/Xcode/Archives/2018-04-11      |
| project                                                         | ../XCode/Unity-iPhone.xcodeproj                             |
| scheme                                                          | Unity-iPhone                                                |
| clean                                                           | true                                                        |
| output_directory                                                | ../XCode/build/                                             |
| output_name                                                     | #1002580 - 18.4.1.1002580-update_BSA-2054-0132c966-QA (iOS) |
| silent                                                          | false                                                       |
| codesigning_identity                                            | iPhone Developer: ### Inc (###)               |
| skip_package_ipa                                                | false                                                       |
| include_bitcode                                                 | false                                                       |
| export_xcargs                                                   | -allowProvisioningUpdates                                   |
| buildlog_path                                                   | ~/Library/Logs/gym                                          |
| skip_profile_detection                                          | false                                                       |
| xcode_path                                                      | /Applications/Xcode.app                                     |
+-----------------------------------------------------------------+-------------------------------------------------------------+

[12:03:54]: Archive  Succeeded 
[12:03:54]: Generated plist file with the following values 
[12:03:54]:   "provisioningProfiles":
[12:03:54]:     "com.********.###": "match Development com.********.###"
[12:03:54]:   },
[12:03:54]:   "teamID": "### Limited",
[12:03:54]:   "installerSigningCertificate": "iPhone Developer: ### Inc (###)",
[12:03:54]:   "method": "development",
[12:03:54]:   "signingStyle": "manual"
[12:03:54]: -----------------------------------------


So everything looks like it is set up correctly, but then I get the build error:

error: exportArchive: No "iOS App Development" profiles for team '### Limited' matching 'match Development com.********.###' are installed.

Error Domain=IDEProfileLocatorErrorDomain Code=4 "No "iOS App Development" profiles for team '###Limited' matching 'match Development com.********.###' are installed." UserInfo={NSLocalizedDescription=No "iOS App Development" profiles for team '### Limited' matching 'match Development com.********.###' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}

** EXPORT FAILED **
[12:03:56]: Exit status: 70

I have attached my current Fast/Gym files.


[Fastfile.zip](https://github.com/fastlane/fastlane/files/1900358/Fastfile.zip)

Thanks for help resolving this issue.

**Comment by lblast** [comment]
Any ideas?

**Comment by joshdholtz** [comment]
@lblast So it looks like using the plugin set your profile to the profile name that you wanted correctly but it doesn't look like that profile is installed. So from what I can tell, it looks like you either most likely...

1) Didn't type the correct profile name into `update_provisioning_profile_specifier`
or
2) Didn't install the profile through `match`, `sigh`, or manually

Hopefully this helps 🙃

**Comment by lblast** [comment]
I updated fastlane but the issue has not yet been resolved. I'll spend some time working on this again to verify.
