### ISSUE TITLE
archived-expanded-entitlements is removed in Xcode9.3

### ISSUE THREAD

**Issue by saitjr** [fastlane/fastlane#12209]
I find that archived-expanded-entitlements.xcent file has been removed in Xcode9.3. And I don't know why Xcode9.3 do this.
And the resign module still export archived-expanded-entitlements.xcent from entitlements, should it remove just like Xcode9.3 do?

This issue is just a suggestion, close it if you think it is unnecessary.

**Comment by saitjr** [comment]
Emmm...............The env


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.13.4                                        |
| Ruby                        | 2.5.0                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.13.6 (Apple Git-96)              |
| Installation Source         | /usr/local/bin/fastlane                        |
| Host                        | Mac OS X 10.13.4 (17E199)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib             |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                     |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode9.1.app/Contents/Developer/ |
| Xcode Version               | 9.1                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.87.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| excon                     | 0.61.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| multi_json                | 1.13.1       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>


*generated on:* **2018-04-03**
</details>

**Comment by joshdholtz** [comment]
@saitjr Does including the `archived-expanded-entitlements.xcent` breaking anything at all now for you with the resign? Or is it just extra / not necessary?

**Comment by saitjr** [comment]
It doesn't break anything, just not necessary from now on. I don't know why Xcode9.3 remove it.

**Comment by yakimant** [comment]
There is an Apple thred, fyi:
https://forums.developer.apple.com/thread/99923

**Comment by saitjr** [comment]
@yakimant Thanks, for now I use:

```
/usr/bin/codesign -d --entitlements :<output path> <binary path>
```

**Comment by yakimant** [comment]
@saitjr, yes. xcent file is redundant.

**Comment by limXInfi** [comment]
@saitjr yes, but you can not checkt entitlements at runtime this way...

**Comment by joshdholtz** [comment]
Below are references to archived-expanded-entitlements.xcent in `resign.sh`. The hard part about this is that this will still need to be backwards compatible with Xcode 9.2 and older (if we wanted to make this change)
- https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L615
- https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L822
- https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L831

I don't know if removing these in necessarily required (unless it breaks things) right now 🤔
