### ISSUE TITLE
Submitting an approved testflight app with spaceship

### ISSUE THREAD

**Issue by DuglsYoung** [fastlane/fastlane#12214]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using spaceship to submit an app to testflight. Basically, finding the build to submit and doing:

build.submit_for_testflight_review!

Works for submitting the app for testflight review. However, after apple reviews, it seems I still have to manually select the build to be released on itunesconnect, so I must be missing something.

Looking at pilot, it seems that after submit_for_testflight_review, it adds the default external test group.
Question: is that sufficient to have the app released to testers once apple approves? Or is there something else that needs to be done?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | ~/.gem/ruby/2.3.0/bin/fastlane                                 |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.88.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-04-02**
</details></pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by DuglsYoung** [comment]
Yes, I understand the different tracks here. We are not using a fastfile. We're using fastlane integrated with our own build/deployment backends (at LinkedIn), so other than using deliver with cmd-line options to upload, we're using spaceship for everything. In this case, I'm submitting the build for testflight, and it's being submitted for testflight review. But once apple approves it, we still have to log into itunesconnect and click a few buttons to select the build for release, even tho we already selected it for review and was approved. I'm looking for why that is needed, we want everything automated. Non-testflight is all working nicely, completely automated and integrated with our in-house build/deployment system. So I'm just trying to close this hole for testflight.

**Comment by joshdholtz** [comment]
@DuglsYoung Got it got it, sorry about that. I misunderstood. I don't remember the exact steps that happen after a build gets reviewed and approved for beta but I will send a build through so I can figure what we can do to help you out 👍

**Comment by DuglsYoung** [comment]
Thanks, appreciate any suggestions. For product releases, I just use app.edit_version.release! But I don't see any equivalent for testflight.

**Comment by DuglsYoung** [comment]
The extra step of setting the test group seems to have done the trick. So I basically do:

build.test_info.whats_new = "bug fixes, etc"

build.submit_for_testflight_review!

default_group = Spaceship::TestFlight::Group.default_external_group(app_id: build.app_id)

unless default_group.nil?
  build.add_group!(default_group)
end
