### ISSUE TITLE
Working with flavor using fastlane

### ISSUE THREAD

**Issue by shailesh2208** [fastlane/fastlane#12227]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane screengrab shows all the apk for all flavor I need just show the apk with selected flavor. I want specific flavor would be selected then I can get the screenshots of that flavor 

##### Complete output when running fastlane, including the stack trace and command used
[11:19:56]: Select your debug app APK
1.
app/build/outputs/apk/androidTest/flavorTest2/debug/app-flavorTest2-debug-a
ndroidTest.apk
2.
app/build/outputs/apk/androidTest/flavorTest1/debug/app-flavorTest1-debug-a
ndroidTest.apk
3. app/build/outputs/apk/flavorTest2/release/app-flavorTest2-release.apk
4. app/build/outputs/apk/flavorTest2/debug/app-flavorTest2-debug.apk
5. app/build/outputs/apk/flavorTest1/release/app-flavorTest1-release.apk
6. app/build/outputs/apk/flavorTest1/debug/app-flavorTest1-debug.apk
7. app/release/app-release.apk

<details>
  [10:41:14]: fastlane detected a Gemfile in the current directory
[10:41:14]: however it seems like you don't use `bundle exec`
[10:41:14]: to launch fastlane faster, please use
[10:41:14]: 
[10:41:14]: $ bundle exec fastlane env
[10:41:14]: 
[10:41:14]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:41:15]: Generating fastlane environment output, this might take a few seconds...

[10:41:15]: Error accessing file, this might be due to fastlane's directory handling
[10:41:15]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

#######################################################################
# fastlane 2.89.0 is available. You are on 2.88.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.89.0 Improvements
* [action] Make sure get_version_number targets respond to test_target_type? (#12212) via Josh Holtz
* [action] Make enable_automatic_code_signing for all configurations (#12187) via Nicolas Braun
* [produce]Use correct spelling of icloud service in product/service.rb (#12134) via Jakub Knejzlík
* [action] Add Support for Registering Mac Devices on Apple Developer Portal (#11978) via Baumchen
* [spaceship] Spaceship delete testflight groups (#12111) via Kenneth Wong
* [produce] Enable set 'NFC Tag Reading' at 'fastlane produce' cli. (#12179) (#12201) via Kazuhide Takahashi
* [frameit] frameit documentation describes all parameters from the Framefile (#11662) via funnel20
* [supply] Clarify difference between SUPPLY_JSON_KEY and SUPPLY_JSON_KEY_DATA via Aaron Brager
* [action] added custom api_url option to testfairy (#12153) via Josh Holtz

Please update using `sudo gem install fastlane`
/var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:214:in ``': No such file or directory - git (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:214:in `print_system_environment'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:24:in `get'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/commands_generator.rb:263:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

</details>

### Environment

<details>
Android Fastlane
</details>

**Comment by joshdholtz** [comment]
@shailesh2208 You can use `Dir.glob` to find the APK that you want with something like this...

```rb
:snaps do
  gradle(
    task: 'assemble assembleAndroidTest'
  )

  apk_path = Dir.glob("../**/flavorTest2/*-debug.apk").first
  test_apk_path = Dir.glob("../**/flavorTest2/*-debug-androidTest.apk").first

  screengrab(
    app_apk_path: File.absolute_path(apk_path),
    tests_apk_path:  File.absolute_path(test_apk_path)
  )
end
```
