### ISSUE TITLE
app_store_build_number should return version number too

### ISSUE THREAD

**Issue by kballard** [fastlane/fastlane#12221]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The `app_store_build_number` action has an output variable for the build number, but it would also be great if it had an output variable for the version number. This wouldn't be useful when you pass a version number to the action, but it would be useful when using `live: true`.

The context here is I'd like to have a lane that creates a git tag for the current live version (we already have a way to go from build number -> commit), and this obviously requires knowing what the version number is. The idea is we'd run this after publishing a new version.

**Comment by kballard** [comment]
@joshdholtz Is that label supposed to suggest to me, the issue author, that I should try doing this? Or is it just a cute way of saying "this is easy"?

**Comment by joshdholtz** [comment]
@kballard Could mean both 🙃 We are always happy to accept PRs if this is something you want to try but also a good way for other to find a task that has low complexity

**Comment by joshdholtz** [comment]
@RishabhTayal 
- rename `AppStoreBuildNumberAction` to `AppStoreInfo` have it return all the things
- create `AppStoreBuildNumberAction` which just grabs the build number (for backwards compatibility)
- no need to create `AppStoreVersionNumberAction` cause people can just use `AppStoreInfo`

**Comment by RishabhTayal** [comment]
@fastlane-bot there is an existing open PR for this.

**Comment by RishabhTayal** [comment]
@joshdholtz Can you please review the PR https://github.com/fastlane/fastlane/pull/12286

**Comment by kballard** [comment]
The relevant PR is still open.
