### ISSUE TITLE
upload_to_play_store metadata release track

### ISSUE THREAD

**Issue by eygraber** [fastlane/fastlane#12226]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to be able to upload metadata for changelogs based on the track ([as described here](https://github.com/Triple-T/gradle-play-publisher#play-store-metadata)). Is just setting `track` and `metadata_path` enough, or is this not supported? Can the filename be used to differentiate like the linked project above? It would be much easier than having to separate multiple metadata directories.

### Environment

<details>
  <pre>
    <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                        |
| Ruby                        | 2.3.1                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.7.4                                               |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 16.04.4 LTS debian_based stretch/sid (4.13.0-37-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                      |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US       | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.88.0"

default_platform :android

platform :android do
  Dir['lanes/*.rb'].each { |file| import(file) }

  before_all do
    setup_environment_variables
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.88.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                               | Version | Update-Status  |
| ------------------------------------ | ------- | -------------- |
| fastlane-plugin-changelog_generator  | 0.2.1   | ✅ Up-To-Date   |
| fastlane-plugin-git_tags             | 0.1.1   | ✅ Up-To-Date   |
| fastlane-plugin-google_cloud_storage | 0.1.1   | ✅ Up-To-Date   |
| fastlane-plugin-scarif               | 0.1.4   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                  | Version      |
| ------------------------------------ | ------------ |
| io-console                           | 0.4.5        |
| CFPropertyList                       | 3.0.0        |
| public_suffix                        | 2.0.5        |
| addressable                          | 2.5.2        |
| atomos                               | 0.1.2        |
| thread_safe                          | 0.3.6        |
| descendants_tracker                  | 0.0.4        |
| ice_nine                             | 0.11.2       |
| axiom-types                          | 0.1.1        |
| babosa                               | 1.0.2        |
| bundler                              | 1.16.1       |
| claide                               | 1.0.2        |
| colored2                             | 3.1.2        |
| cork                                 | 0.3.0        |
| nap                                  | 1.1.0        |
| open4                                | 1.3.4        |
| claide-plugins                       | 0.9.2        |
| coderay                              | 1.1.2        |
| coercible                            | 1.0.0        |
| colored                              | 1.2          |
| highline                             | 1.7.10       |
| commander-fastlane                   | 4.4.6        |
| multipart-post                       | 2.0.0        |
| faraday                              | 0.14.0       |
| faraday-http-cache                   | 1.3.1        |
| git                                  | 1.3.0        |
| kramdown                             | 1.16.2       |
| no_proxy_fix                         | 0.1.2        |
| sawyer                               | 0.8.1        |
| octokit                              | 4.8.0        |
| unicode-display_width                | 1.3.0        |
| terminal-table                       | 1.8.0        |
| danger                               | 5.5.11       |
| danger-plugin-api                    | 1.0.0        |
| excon                                | 0.62.0       |
| danger-jumpspeeder                   | 0.1.0        |
| declarative                          | 0.0.10       |
| declarative-option                   | 0.1.0        |
| digest-crc                           | 0.4.1        |
| unf_ext                              | 0.0.7.5      |
| unf                                  | 0.1.4        |
| domain_name                          | 0.5.20170404 |
| dotenv                               | 2.2.1        |
| ejson                                | 1.1.0        |
| equalizer                            | 0.0.11       |
| http-cookie                          | 1.0.3        |
| faraday-cookie_jar                   | 0.0.6        |
| faraday_middleware                   | 0.12.2       |
| fastimage                            | 2.1.1        |
| gh_inspector                         | 1.1.3        |
| jwt                                  | 2.1.0        |
| little-plugger                       | 1.1.4        |
| multi_json                           | 1.13.1       |
| logging                              | 2.2.2        |
| memoist                              | 0.16.0       |
| os                                   | 0.9.6        |
| signet                               | 0.8.1        |
| googleauth                           | 0.6.2        |
| httpclient                           | 2.8.3        |
| mime-types-data                      | 3.2016.0521  |
| mime-types                           | 3.1          |
| uber                                 | 0.1.0        |
| representable                        | 3.0.4        |
| retriable                            | 3.1.1        |
| google-api-client                    | 0.13.6       |
| json                                 | 2.1.0        |
| mini_magick                          | 4.5.1        |
| multi_xml                            | 0.6.0        |
| plist                                | 3.4.0        |
| rubyzip                              | 1.2.1        |
| security                             | 0.1.3        |
| naturally                            | 2.1.0        |
| simctl                               | 1.6.3        |
| slack-notifier                       | 2.3.2        |
| terminal-notifier                    | 1.8.0        |
| tty-screen                           | 0.6.4        |
| tty-cursor                           | 0.5.0        |
| tty-spinner                          | 0.8.0        |
| word_wrap                            | 1.0.0        |
| nanaimo                              | 0.2.4        |
| xcodeproj                            | 1.5.7        |
| rouge                                | 2.0.7        |
| xcpretty                             | 0.2.8        |
| xcpretty-travis-formatter            | 1.0.0        |
| fastlane-plugin-changelog_generator  | 0.2.1        |
| fastlane-plugin-git_tags             | 0.1.1        |
| google-cloud-env                     | 1.0.1        |
| google-cloud-core                    | 1.2.0        |
| google-cloud-storage                 | 1.5.0        |
| fastlane-plugin-google_cloud_storage | 0.1.1        |
| fastlane-plugin-scarif               | 0.1.4        |
| method_source                        | 0.8.2        |
| mimemagic                            | 0.3.2        |
| slop                                 | 3.6.0        |
| pry                                  | 0.10.4       |
| pry-nav                              | 0.2.4        |
| virtus                               | 1.0.5        |
| tracker_api                          | 1.8.0        |
</details>

*generated on:* **2018-04-04**
</details>

</pre>
</details>

**Comment by joshdholtz** [comment]
@eygraber You can totes do this 👌 My example is probably a little bit explicit with all the options I used but this worked for me by following https://docs.fastlane.tools/actions/supply/#changelogs-whats-new:
```rb
lane :meta do
  supply(
    package_name: 'example.screengrab.fastlane.tools.fastlanescreengrabexample',
    track: 'production',
    skip_upload_apk: true,
    skip_upload_metadata: false,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    json_key: './fastlane/google_play2.json',
  )
end
```

**Comment by eygraber** [comment]
@joshdholtz thanks. 

And if `track` was `beta` then the listing would only be updated for my users in the beta, and users in the `production` track wouldn't see the new listing information?

**Comment by joshdholtz** [comment]
@eygraber That is correct 👌
