### ISSUE TITLE
RuntimeError: Unsupported workspace file reference type `self` (running fastlane ios beta)

### ISSUE THREAD

**Issue by ivmos** [fastlane/fastlane#12233]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm getting [!] Unsupported workspace file reference type `self` (RuntimeError) when running fastlane ios beta.

Thanks in advance,

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace/file_reference.rb:81:in `absolute_path': [!] Unsupported workspace file reference type `self` (RuntimeError)
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace.rb:195:in `block in load_schemes'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace.rb:194:in `each'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace.rb:194:in `load_schemes'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace.rb:85:in `from_s'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/project.rb:106:in `workspace'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/project.rb:120:in `schemes'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/project.rb:133:in `select_scheme'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/gym/lib/gym/detect_values.rb:102:in `detect_scheme'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/gym/lib/gym/detect_values.rb:29:in `set_additional_default_values'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/gym/lib/gym/module.rb:15:in `config='
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/gym/lib/gym/manager.rb:8:in `work'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/build_ios_app.rb:64:in `run'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
        from Fastfile:30:in `block (2 levels) in parsing_binding'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
        from /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.89.0/bin/fastlane:20:in `<top (required)>'
        from /Users/ivmos/.fastlane/bin/bundle/bin/fastlane:22:in `load'
        from /Users/ivmos/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.9.0"
default_platform :ios

# we will call some node scripts which are written in ES6 (see below)
nodeExec = '../node_modules/.bin/babel-node'

# load in config generated in the pre-build step (see above)
file = File.read('../appConfig.json')
appConfig = JSON.parse(file)

# iOS
platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # fetch previously generated certificates, but don't generate new ones if none already exist
    match(type: "appstore", readonly: true)
    # ensure we're on the "master" git branch
    ensure_git_branch(branch: "master")
    # set the app build number from our previously generated config
    increment_build_number(
      xcodeproj: "./ios/FooMobileApp.xcodeproj",
      build_number: appConfig["buildNumber"]
    )
    # set the app version from our previously generated config
    increment_version_number(
      xcodeproj: "./ios/FooMobileApp.xcodeproj",
      version_number: appConfig["appVersion"]
    )
    # build the app for app store export
    gym(
      clean: true,
      export_method: 'app-store',
      workspace: "./ios/FooMobileApp.xcodeproj/project.xcworkspace",
      scheme: "FooMobileApp",
      output_directory: "./build-tools/deploy/data"
    )
    # upload to TestFlight and notify testers
    testflight(
      skip_submission: true
    )
  end
end

# Android
platform :android do
  desc "Submit a new Beta Build to TestFairy"
  lane :beta do
    # ensure we're on the "master" git branch
    ensure_git_branch(branch: "master")
    # build the app in release mode
    gradle(
      project_dir: "./android",
      task: "assemble",
      flavor: "",
      build_type: "Release",
      properties: {
        'versionCode' => appConfig["buildNumber"],
        'versionName' => appConfig["appVersion"]
      }
    )
   # Upload to TestFairy
   testfairy(
     api_key: 'XXXXXX',
     ipa: './android/app/build/outputs/apk/app-release.apk',
     comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
   )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXXXX" # The bundle identifier of your app
apple_id "XXXX" # Your Apple email address
team_id "XXXXX"  # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-04-04**
</details></pre>
</details>

**Comment by ivmos** [comment]
I did this as workaround but no idea why I need it...

```
+++ /Users/ivmos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/workspace/file_reference.rb	2018-04-05 11:54:43.000000000 +0200
@@ -69,6 +69,8 @@
       def absolute_path(workspace_dir_path)
         workspace_dir_path = workspace_dir_path.to_s
         case type
+        when 'self'
+          File.expand_path(File.join(workspace_dir_path, path))
         when 'group'
           File.expand_path(File.join(workspace_dir_path, path))
         when 'container'
```

**Comment by joshdholtz** [comment]
@ivmos This is super weird... "self" is not a type of option available 🤔 Does your dropdown look different than mine?

![screen shot 2018-04-10 at 8 52 21 am](https://user-images.githubusercontent.com/401294/38561007-8a4ec8d2-3c9c-11e8-942c-4192a1beb7db.png)

**Comment by owurman** [comment]
I have the same issue after updating.

It's unclear from the error which file it's having an issue with, but the target I'm running on has the files as Relative to Group.

**Comment by Gi0rgi0s** [comment]
bump

**Comment by Gi0rgi0s** [comment]
Has there been any progress on this? thanks

**Comment by jmillan** [comment]
Same its happening here.

**Comment by jmillan** [comment]
Worked with @ivmos workaround: https://github.com/fastlane/fastlane/issues/12233#issuecomment-378884704

**Comment by owurman** [comment]
This was not fixed. It got no attention then was auto-closed, but it's still broken in 2.102.0.

**Comment by calkinssean** [comment]
I'm having a similar issue when trying to generate screenshots. I get `Unsupported workspace file reference type `SDK`` on every attempt. This lane has worked just fine in the past but no longer works with any of the old applications or my new ones.




| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
</details>

**Comment by LizCira** [comment]
Hi all, as detailed here, this is an issue with the dependency Gem Xcodeproj being unable to parse embedded xcode workspaces. I submitted a fix here, fingers crossed that causes these issues to go away as well once it's accepted and Gem version is updated https://github.com/CocoaPods/Xcodeproj/pull/606
