### ISSUE TITLE
How we can increase the version code in android apk using fastlane

### ISSUE THREAD

**Issue by shailesh2208** [fastlane/fastlane#12231]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to know that any method for android release apk that increase the version code as increment_build_number in the IOS platform. 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  [10:41:14]: fastlane detected a Gemfile in the current directory
[10:41:14]: however it seems like you don't use `bundle exec`
[10:41:14]: to launch fastlane faster, please use
[10:41:14]: 
[10:41:14]: $ bundle exec fastlane env
[10:41:14]: 
[10:41:14]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:41:15]: Generating fastlane environment output, this might take a few seconds...

[10:41:15]: Error accessing file, this might be due to fastlane's directory handling
[10:41:15]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

# fastlane 2.89.0 is available. You are on 2.88.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.

2.89.0 Improvements
* [action] Make sure get_version_number targets respond to test_target_type? (#12212) via Josh Holtz
* [action] Make enable_automatic_code_signing for all configurations (#12187) via Nicolas Braun
* [produce]Use correct spelling of icloud service in product/service.rb (#12134) via Jakub Knejzlík
* [action] Add Support for Registering Mac Devices on Apple Developer Portal (#11978) via Baumchen
* [spaceship] Spaceship delete testflight groups (#12111) via Kenneth Wong
* [produce] Enable set 'NFC Tag Reading' at 'fastlane produce' cli. (#12179) (#12201) via Kazuhide Takahashi
* [frameit] frameit documentation describes all parameters from the Framefile (#11662) via funnel20
* [supply] Clarify difference between SUPPLY_JSON_KEY and SUPPLY_JSON_KEY_DATA via Aaron Brager
* [action] added custom api_url option to testfairy (#12153) via Josh Holtz

Please update using `sudo gem install fastlane`
/var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:214:in ``': No such file or directory - git (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:214:in `print_system_environment'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:24:in `get'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/commands_generator.rb:263:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.88.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

</details>

### Environment

<details>
  <pre>Fastlane</pre>
</details>

**Comment by JesseScott** [comment]
Check out the various plugins from this user --> https://github.com/Jems22

**Comment by joshdholtz** [comment]
@JesseScott Thanks for that comment! Going to close this issue for now since that is the accept answer and any issue with those plugins should be handled on those repositories 😊 Happy fastlaning 🚀
