### ISSUE TITLE
Unable to upvote a comment on github issue

### ISSUE THREAD

**Issue by gauravagarwalr** [fastlane/fastlane#12246]
Hi,

I was wondering if it would be possible to restrict a issue but be able to allow for voting emojis to comments?

I really think the last comment on this issue needs to be up voted, as it has solved my issue:
https://github.com/fastlane/fastlane/issues/6866 .

I can't do that since the "@fastlane-bot fastlane-bot locked and limited conversation to collaborators on 22 Jun 2017"

I wasn't sure how to reach out to the collaborators to bring us this issue, so I am adding it here. Please feel free to delete it if you find it irrelevant.

Bringing attention to comments is important in threads like the above where a lot of people have added their comments. Some things are not easy to spot or obvious.

**Comment by joshdholtz** [comment]
@gauravagarwalr Not sure why that got lock but I unlocked it for you to upvote it 👍
