### ISSUE TITLE
could not locate gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by codesinghanoop** [fastlane/fastlane#12248]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I use fastlane command in the post build script and the post build script is of appcenter.

The script is : - bundle exec fastlane ios appcenterPost password:$PASSWORD user:$USER ipa:$APPCENTER_OUTPUT_DIRECTORY/projectname.ipa

it gives me error :-  could not locate gemfile or .bundle/ directory

**Comment by RishabhTayal** [comment]
@codesinghanoop Do you have a `Gemfile` in your project folder? If you are not using `Gemfile` you should run without `bundle exec`.

**Comment by codesinghanoop** [comment]
@RishabhTayal i removed bundle exec and it works great. Please can you tell me the reason behind this ?

**Comment by RishabhTayal** [comment]
Awesome. You could use fastlane as a bundled gem i.e. using `Gemfile`. If you use `Gemfile` you would be using `bundle exec` command. More info here in the [docs](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile)
