### ISSUE TITLE
Avoid creating fastlane/README.md

### ISSUE THREAD

**Issue by squarefrog** [fastlane/fastlane#1225]
Is there an option to not create the fastlane README file?

**Comment by iWaiterDeveloper** [comment]
I've also faced this issue. We have our Readme.md in fastlane folder with tutorial how to upload app.

**Comment by Wojcik** [comment]
We also have our README.md in the fastlane folder and it's replaced each time. It's very annoying.

**Comment by KrauseFx** [comment]
Yeah, you just add
```ruby
skip_docs
```
to your `Fastfile` :+1:
