### ISSUE TITLE
Reuse existing 

### ISSUE THREAD

**Issue by elviin** [fastlane/fastlane#12250]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

A client who is also an owner of a apple developer team is using the Distribution certificate for other clients. I can not just nuke the existing Distribution Certificates. There are already 3 certificates, that is the possible maximum number.

How can I instruct **match** to use a specific Distribution certificate that already exists in the Apple developer portal?

Why does match create a new certificate and do not reuse an existing one (that we could define via an argument)?

There is a closed issue https://github.com/fastlane/fastlane/issues/8873

But the only solution described there is to nuke the existing certificate.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>...
Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not create another Distribution certificate, reached the maximum number of available Distribution certificates.

URL: https://api.github.com/search/issues?q=Could%20not%20create%20another%20Distribution%20certificate%2C%20reached%20the%20maximum%20number%20of%20available%20Distribution%20certificates.+repo:fastlane/fastlane
➡️  Match can't find certificate in repo if run again.
    https://github.com/fastlane/fastlane/issues/10489 [closed] 31 💬
    4 days ago

➡️  [match] Ignoring file when decrypting certificates repo 
    https://github.com/fastlane/fastlane/issues/9400 [closed] 5 💬
    07 Sep 2017

➡️  How can I use 'match' to upload my existing distribution cert/key instead of creating a new one on portal?
    https://github.com/fastlane/fastlane/issues/8873 [closed] 3 💬
    11 Sep 2017

and 16 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20create%20another%20Distribution%20certificate%2C%20reached%20the%20maximum%20number%20of%20available%20Distribution%20certificates.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!': [!] Could not create another Distribution certificate, reached the maximum number of available Distribution certificates. (FastlaneCore::Interface::FastlaneError)
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/cert/lib/cert/runner.rb:158:in `rescue in create_certificate'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/cert/lib/cert/runner.rb:153:in `create_certificate'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/cert/lib/cert/runner.rb:44:in `run'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/cert/lib/cert/runner.rb:13:in `launch'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/match/lib/match/generator.rb:25:in `generate_certificate'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/match/lib/match/runner.rb:100:in `fetch_certificate'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/match/lib/match/runner.rb:57:in `run'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/match/lib/match/commands_generator.rb:61:in `block (3 levels) in run'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/match/lib/match/commands_generator.rb:146:in `run'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/match/lib/match/commands_generator.rb:19:in `start'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/fastlane/lib/fastlane/cli_tools_distributor.rb:99:in `take_off'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/bin/fastlane:20:in `<top (required)>'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/vladimirslavik/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'</pre>
</details>

### Environment

<details>
  <pre>### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| oauth                     | 0.5.4        |
| jira-ruby                 | 1.5.0        |
</details>

</pre>
</details>

**Comment by joshdholtz** [comment]
@elviin So, `match` will reuse a certificate if its installed (public and private key) on the local machine (as the private key isn't stored by Apple). If the private key isn't installed, it will attempt to create a new one because otherwise it wouldn't be able to sign. (This may be known to you but just dropping this here for others).

That being said, `match` was initially designed for a full team to use (and everyone to use) for this reason. The quick solution would be to get your client's other developers to all use `match` to keep things in sync (but this is probably easier said than done). I do understand your problem as I have also faced it myself so I will add this to my list of things to look into 😬

**Comment by vasvf** [comment]
There will be good to have build-in initializer to export all existing certificates to git repo.

The steps are, for example, described here:
https://medium.com/@jonathancardoso/using-fastlane-match-with-existing-certificates-without-revoking-them-a325be69dac6

Fastlane could just fetch all certificates using Spaceship to get their cert_ids, then extract all identities existing in keychain according to fetched list and then push everything to repo.

I suppose it to be run once on a build node/developer mac/etc, and then everyone else could just use `fastlane match` to install all this certificates in a simple and easy way.

**Comment by HIIgor** [comment]
I wrote an action to reuse the reusable certificates on the git repo
https://github.com/HIIgor/match_certs_migration
