### ISSUE TITLE
Packaging NodeJS and Java Application?

### ISSUE THREAD

**Issue by dotku** [fastlane/fastlane#12253]
I'm not sure if it is a proper space to discuss this question, but dose NodeJS support java app wrapper? I want to run Java application inside a node app, eg I do have a Java App called JA.jre. I have a NodeJS Electron App called NEA, I want NEA to have full access on JA (access function, memory and ect, is it possible?)

**Comment by joshdholtz** [comment]
@dotku Heyyy 👋 I think this is the wrong place for this 😊 I don't think your question has much intersection with fastlane as we are a building/automation tool for iOS, Android, and macOS apps
