### ISSUE TITLE
fastlane skipped exporting ipa file after archiving succeeded

### ISSUE THREAD

**Issue by artetinho** [fastlane/fastlane#12254]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane command used:

```
fastlane gym --workspace xxx.xcworkspace \
--scheme ${SCHEME} \
--sdk 'iphoneos' \
--configuration Release \
--destination generic/platform=iOS \
--output_directory ${BUILD_RELEASE_FOLDER} \
--output_name ${APP_NAME}-Release-${BUILD_NUMBER}.ipa \
--codesigning_identity "$SIGNING_CERTIFICATE" \
--xcargs "PROVISIONING_PROFILE_SPECIFIER='${TARGET_PROVISIONING_PROFILE_SPECIFIER}'" \
--verbose \
--buildlog_path "${WORKSPACE}" \
--export_options "${WORKSPACE}/export_options.plist" \
--export_method "app-store"

Details:
+------------------------+-----------------------------------------------------------------------------------------+
|                                              [32mSummary for gym 2.89.0[0m                                              |
+------------------------+-----------------------------------------------------------------------------------------+
| workspace              | xxx.xcworkspace                                                                      |
| scheme                 | XScheme                                                                                  |
| sdk                    | iphoneos                                                                                |
| configuration          | Release                                                                                 |
| destination            | generic/platform=iOS                                                                    |
| output_directory       | /Users/xxx/Jenkins/workspace/xxx/Release_Appstore/buildRelease         |
| output_name            | xxx-Release-2706                                                                     |
| codesigning_identity   | iPhone Distribution: xxx, Inc. (xxx)                                          |
| xcargs                 | PROVISIONING_PROFILE_SPECIFIER='xxx/xxx Q App Store'                          |
| buildlog_path          | /Users/xxx/Jenkins/workspace/xxx/Release_Appstore                      |
| export_options         | /Users/xxx/Jenkins/workspace/xxx/Release_Appstore/export_options.plist |
| export_method          | app-store                                                                               |
| build_path             | /Users/xxx/Library/Developer/Xcode/Archives/2018-04-07                               |
| clean                  | false                                                                                   |
| silent                 | false                                                                                   |
| skip_package_ipa       | false                                                                                   |
| skip_profile_detection | false                                                                                   |
| xcode_path             | /Applications/Xcode.app                                                                 |
+------------------------+-----------------------------------------------------------------------------------------+
```

After archive succeeded, it skipped exporting ipa file. Everything was OK when I use "enterprise" for export_method.
LOGS:

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>INFO [2018-04-07 09:08:53.31]: [35m[33m▸[0m [39;1mTouching[0m xxx.app[0m
INFO [2018-04-07 09:08:57.61]: [35m[33m▸[0m [39;1mSigning[0m /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-agmucgrifenkmdgjfbeweelgpavd/Build/Intermediates.noindex/ArchiveIntermediates/xxx/InstallationBuildProductsLocation/Applications/xxx.app[0m
INFO [2018-04-07 09:08:59.21]: [35m[33m▸[0m [39;1mTouching[0m xxx.app.dSYM[0m
INFO [2018-04-07 09:09:01.93]: [35m[33m▸[0m [39;1mArchive[0m Succeeded[0m
DEBUG [2018-04-07 09:09:02.20]: Stored the archive in: /Users/xxx/Library/Developer/Xcode/Archives/2018-04-07/xxx-Release-2706 2018-04-07 08.56.42.xcarchive
INFO [2018-04-07 09:09:02.23]: Compressing 62 dSYM(s)
INFO [2018-04-07 09:09:02.23]: [36m$ cd '/Users/xxx/Library/Developer/Xcode/Archives/2018-04-07/xxx-Release-2706 2018-04-07 08.56.42.xcarchive/dSYMs' && zip -r '/Users/xxx/Jenkins/workspace/xxx/iOS_xxx_Release_Appstore/buildRelease/xxx-Release-2706.app.dSYM.zip' *.dSYM[0m
....
....
....
INFO [2018-04-07 09:09:13.75]: [32mSuccessfully exported and compressed dSYM file[0m
INFO [2018-04-07 09:09:14.27]: [32mSuccessfully exported the .app file:[0m
INFO [2018-04-07 09:09:14.27]: /Users/xxx/Jenkins/workspace/xxx/iOS_xxx_Release_Appstore/buildRelease/xxx.app</pre>
</details>

### Environment

<details>
  <pre>| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@artetinho Are you able to paste your entire output from your command here so I have some more information to go on? 😊 Thanks!

**Comment by artetinho** [comment]
Oh, there was an incorrect configuration for the release config that used macOS for base SDK instead of ios, it led to the issue I mentioned above.
I'll close the issue ticket as invalid. Thanks everyone for look over.
