### ISSUE TITLE
Generate .ipa using jenkins and fastlane

### ISSUE THREAD

**Issue by GiritharanHubbell** [fastlane/fastlane#12262]
Hi i am trying to generate .ipa using Fastlane and Jenkins.
In Fastlane i can able to generate ipa in terminal.
But i could not able to run fastlane in Jenkins Command Shell.
I tried almost all tutorial like this (https://medium.com/@cherrmann.com/continuous-integration-and-delivery-for-ios-with-jenkins-and-fastlane-part-1-3b17f1901a73).
But still i could not able to solve.Please help me.

Thanks in Advance!

**Comment by saitjr** [comment]
Could you paste the logs?

**Comment by GiritharanHubbell** [comment]
Started by user xxx
Building in workspace /Users/Shared/Jenkins/Home/workspace/Git Practice
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/xxx/Jenkins-Test.git # timeout=10
Fetching upstream changes from https://github.com/xxx/Jenkins-Test.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/xxx/Jenkins-Test.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 1dfd4e11b2e176550ea5f6e6033975ded81790d8 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1dfd4e11b2e176550ea5f6e6033975ded81790d8
Commit message: "changes made with spaces"
 > git rev-list --no-walk 1dfd4e11b2e176550ea5f6e6033975ded81790d8 # timeout=10
Capturing environment variables produced by 'rvm use .'

$ bash -c export
$ bash -c "test -f ~/.rvm/scripts/rvm"
$ bash -c "test -f ~/.rvm/scripts/rvm"
[Git Practice] $ bash -c " source ~/.rvm/scripts/rvm && rvm use --install --create . && export > rvm.env"
Could not determine which Ruby to use; . should contain .rvmrc or .versions.conf or .ruby-version or .rbfu-version or .rbenv-version, or an appropriate line in Gemfile.
Run `rvm help` to see usage information
ERROR: Failed to setup RVM environment
Finished: FAILURE

**Comment by saitjr** [comment]
You should solve the ruby version in Jenkins.

**Comment by joshdholtz** [comment]
@GiritharanHubbell This is not a fastlane issue and a configuration issue (as of right now based upon your output). Your Jenkins script could not determine which Ruby version to use which means it wasn't able to touch fastlane. Please look into on how to first solve by finding your Ruby version while running Jenkins 😊
