### ISSUE TITLE
How to disable dSYM?

### ISSUE THREAD

**Issue by ThatBulgarian** [fastlane/fastlane#12267]
Hi, 
Fastlane is crashing when touching the dSYM file and since I'm not using that, I just want to know how I can turn it off in code(not through the xcode ui)?

**Comment by ThatBulgarian** [comment]
preferably it would be through one command line instead of needing a fastfile

**Comment by joshdholtz** [comment]
@ThatBulgarian You can change your build settings to just be "DWARF" 🙃 
![screen shot 2018-04-10 at 9 35 47 am](https://user-images.githubusercontent.com/401294/38563464-92e5ac12-3ca2-11e8-8bc2-795250efe611.png)

**Comment by ThatBulgarian** [comment]
I feel like you just read the title and not the comments I put. Anyways, I found out how myself.
