### ISSUE TITLE
How to code sign and use multiple configurations for snapshot

### ISSUE THREAD

**Issue by fabiogomezdiaz** [fastlane/fastlane#12261]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
https://github.com/KrauseFx/krausefx.com/blob/master/_posts/2015-06-18-run-xcode-7-ui-tests-from-the-command-line.md

Hi there, I the above article about uitests and snapshot and thought it was great. However, I am having some issues making it work when using multiple configurations. It asks me to select a provisioning profile for each configuration, but none of the existing provisioning profiles I am using are listed.

I was following some of the guidelines listed in the articles below to use multiple configurations for different environments (App Store, Beta, and Debug), which has worked great for me. Using fastlane is a breeze with multiple configurations as well.

https://medium.com/@danielgalasko/run-multiple-versions-of-your-app-on-the-same-device-using-xcode-configurations-1fd3a220c608
https://medium.com/@danielgalasko/change-your-api-endpoint-environment-using-xcode-configurations-in-swift-c1ad2722200e
This is my first time working with Cocoa Touch UI Testing Bundle, which I plan to use for some UI tests as well for using snapshot and frameit to automate screenshots. Since documentation for UI Testing Bundle with multiple configurations is scarce, I would appreciate if you have any resources you can point me towards to get this going.

Thanks

**Comment by joshdholtz** [comment]
@fabiogomezdiaz Can you send a screenshot or put the output here for what you mean by...
>It asks me to select a provisioning profile for each configuration, but none of the existing provisioning profiles I am using are listed.

I'm not exactly sure what you are seeing with this but if you can show me I may be able to help out more 😊
