### ISSUE TITLE
match decrypted cert p12 file password does not work

### ISSUE THREAD

**Issue by hammadzz** [fastlane/fastlane#12260]
I followed how to decrypt certs and provisioning profiles from the repo:
`openssl aes-256-cbc -k "<password>" -in "<fileYouWantToDecryptPath>" -out "<decryptedFilePath>" -a -d`

But I am unable to use the p12 file after decrypting as the password does not work on it. I checked that I have the correct password from KeyChain. I am trying to use this certificate in a CI environment outside of fastlane (AppCenter.ms)

I have spent more than an hour trying to figure this out. Couldn't find any information in the documentation, just another issue stating the password for the p12 file is the same as the password used to encrypt the certs and provisioning profile.

**Comment by hammadzz** [comment]
Looks like the decrypted p12 file is corrupt, fails when trying to convert it to pem

`openssl pkcs12 -in 28S6549VX7.p12 -out certificate.pem -nodes`

gets errors
```
error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong
error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested
```

**Comment by joshdholtz** [comment]
@hammadzz Heyyy 👋 It looks like you were able to get this working, correct?

**Comment by hammadzz** [comment]
@joshdholtz yes. Perhaps this needs to be added to the documentation as the current documentation although is correct is overly simple and misleading. It should be clear the p12 file is the private key only .

**Comment by joshdholtz** [comment]
@hammadzz Do you want to take a stab at updating the documentation with what you want to be there? 🙃 This is the file that needs to be changed - https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/sync_code_signing.md

**Comment by acecilia** [comment]
Hi:
Couldnt avoid to chip in. I am using [this](https://github.com/michaelhenry/fastlane-match-certificates-boilerplate/blob/master/encryptor.sh) to manually create the match repo, which is including the .p12 file obtained from the keychain (cert+key) and encrypting it straight away (without extracting the key to a .pem file). This is working for me: cert and key are added to the keychain and gym can codesign successfully.

I also tried extracting the key to a .pem file and then encrypting it as follows:

```
openssl pkcs12 -nocerts -nodes -out key.pem -in certAndKey.p12
openssl aes-256-cbc -k "password" -in key.pem -out encryptedKey.p12 -a
```

But this does not import the key into the keychain (only the cert), so gym fails to codesign.

So, with the behaviour that I am experiencing, I am not sure of what is going on, and if @hammadzz is right when he says that only the key is included in the .p12.

Can somebody bring some light on this issue? Why, when encrypting a .pem file containing the key we also rename it to .p12?

**Comment by hammadzz** [comment]
@acecilia its not necessary that a p12 file will have both the cert and private key. In this case it definitely only has the private key. I believe there are github issues on manually setting up match repo that reflect the same.

**Comment by acecilia** [comment]
@hammadzz from your comments I get that, as you say, the p12 can contain the key only without the cert (and also explained [here](http://macoscope.com/blog/simplify-your-life-with-fastlane-match/#migration)). But as far as I tested (a lot) I can not make it work.

I can not find the code where match extracts the key form the p12(cert+key) file. Do you know where to find it?

**Comment by ayoubkhayatti** [comment]
I'll add this because it might be helpful for someone.

After decrypting repo i got two files in the distribution folder. A .cer file and a .p12 file.

To be able to use .p12 in app center you'll have to first get a .pem out of the .cer.
Then combine .p12 and .pem file to generate a new .p12 file that can be used in app center.

note that i'm setting an empty password using `--passout` argument.

`
openssl x509 -inform der -in 2UTZJB12N6.cer -out cert.pem
openssl pkcs12 -export -out cert.p12 -inkey 2UTZJB12N6.p12 -in cert.pem -passout pass:
`

The posted object for creating a build config will look like the following:
`
{
  "badgeIsEnabled": true,
  "environmentVariables": [
    {
      "name": "USERNAME",
      "value": "-",
      "isSecret": tue
    }
  ],
  "id": 87,
  "testsEnabled": false,
  "toolsets": {
    "buildscripts": {
      "app.xcodeproj/project.xcworkspace": {
        "postBuild": "appcenter-post-build.sh",
        "postClone": "appcenter-post-clone.sh",
        "preBuild": "appcenter-pre-build.sh"
      },
      "app.xcworkspace": {
        "postBuild": "appcenter-post-build.sh",
        "postClone": "appcenter-post-clone.sh",
        "preBuild": "appcenter-pre-build.sh"
      }
    },
    "xcode": {
      "archiveConfiguration": "Release",
      "certificateFilename": "cert.p12",
      "certificatePassword": "",
      "certificateUploadId": "86f20d7e-901f-4926-bf07-7ab3799a0000",
      "podfilePath": "Podfile",
      "projectOrWorkspacePath": "App.xcworkspace",
      "provisioningProfileFilename": "AppStore_com.app.mobileprovision",
      "provisioningProfileUploadId": "43ccae85-4299-4bb0-b850-17820c50004",
      "scheme": "App",
      "targetToArchive": "E8C089611FFE96D001234567",
      "xcodeProjectSha": "https://.../project.pbxproj",
      "xcodeVersion": "9.4.1"
    }
  },
  "trigger": "continuous"
}
`

**Comment by zaro0508** [comment]
@acecilia I was having the exact same problem, fastlane not importing the key into the keychain.  I believe that is due to an incompatibility with LibreSSL and match.  Take a look at issue  https://github.com/fastlane/fastlane/issues/13242
