### ISSUE TITLE
What is a lane?

### ISSUE THREAD

**Issue by kdbertel** [fastlane/fastlane#12269]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I would like to know what a `lane` is, and what the ruby DSL for a `lane` is, along with the `desc` command and other commands that can possibly be run around a `lane` that I'm not aware of.

Furthermore, what are the differences between a `lane`, a `private_lane`, and a standard Ruby function?

I have scoured the docs for an explanation of what a `lane` is or how to use `desc` to no avail. I think this is a large oversight in the documentation.

##### Complete output when running fastlane, including the stack trace and command used

N/A

### Environment

N/A

**Comment by Ruenzuo** [comment]
Have you seen https://docs.fastlane.tools/advanced/? I agree, the definition of Lane is somewhat missing, or I can't find it either.

**Comment by kdbertel** [comment]
I read through that, and at best I could learn that a `private_lane` was a `lane` that you couldn't call from the command line. And some other incidental details about a `lane`, but no good, clear definition or API for it.

I originally discovered this when I went to look up what `desc` was and how its API worked, and my first reaction was to go look up `lane` since I figured it would be mentioned or even part of the `lane` API, and couldn't find anything.

**Comment by joshdholtz** [comment]
@kdbertel `desc` is just a way for you to "describe" your lane. Its not required at all 😊 

A `lane` is real similar to a `Rakefile`'s `task` if that helps at all - http://jacobswanner.com/development/2013/rake-file-tasks/

**Comment by kdbertel** [comment]
@joshdholtz Can I do multi-line `desc`s? If so, how? How does variable interpolation work when the `desc` strings are grabbed for output by `fastlane list`?

It would be helpful if the documentation included information that discussed the similarity of a `lane` to a `task`, instead of it being buried in a Github issue. (Along with a link to what a `task` is, for people who don't know `rake` trying to come in and understand how to write a `Fastfile`)

**Comment by joshdholtz** [comment]
@kdbertel The `Fastfile` is simple a ruby file so interpolation works how any other ruby file would...
```rb
desc "OMG, this lanes description has"
desc "the time in it #{Date.today}"
lane :hey do
  # Your lane info goes here
end
```

We probably won't do a link to `rake` and what a `task` is since those aren't used at all within fastlane (I was just using that as an example incase you were familiar with `rake`). But can you create an issue over at https://github.com/fastlane/docs with what you want to see for lane documentation?

**Comment by kdbertel** [comment]
Good call. I didn't realize there was a different issues set over there. I'll get it migrated over.
