### ISSUE TITLE
[deliver] fails when age_rating is set

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#12271]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running `deliver` for the first time we can specify the `age_rating ` in the option and it will work as long as the age rating is not set on the iTunes connect portal. However if the age rating is already set on the portal and if we specify the `age_rating ` option in the `deliver` it will fail the action.

Is there a way to skip this option based on the values set on the portal? I would like to NOT fail the action even though it's not able to set the age rating. Is there a way we can check if age rating field is able to change and if it is then we specify the option in `deliver`?

**Comment by joshdholtz** [comment]
@RishabhTayal Do you have a code example of this? I can't find anything in the project that matches `age_rating` so I'm not exactly sure how to help right now 😊

**Comment by RishabhTayal** [comment]
@joshdholtz The age rating can be set through the `app_rating_config_path` option. I am sorry if I misrepresented the problem. Now that I read the description it sounds confusing. 

Actually you can set the app rating of the app using the `app_rating_config_path` option. However you can only set this option the very first time. After the app rating is set on iTunes connect, this option will throw an error because iTunes Connect would not take the rating config again. `deliver` should probably be silent the second time instead of throwing an error.

```
    upload_to_app_store(
      username: username,
      app_identifier: bundle_identifier,
      force: true,
      submit_for_review: true,
      app_rating_config_path: './fastlane/ratings_config.json',
      price_tier: 0,
      reject_if_possible: true
    )
```

<details><summary>ratings_config.json</summary>

```
{
  "CARTOON_FANTASY_VIOLENCE": 0,
  "REALISTIC_VIOLENCE": 0,
  "PROLONGED_GRAPHIC_SADISTIC_REALISTIC_VIOLENCE": 0,
  "PROFANITY_CRUDE_HUMOR": 0,
  "MATURE_SUGGESTIVE": 0,
  "HORROR": 0,
  "MEDICAL_TREATMENT_INFO": 0,
  "ALCOHOL_TOBACCO_DRUGS": 0,
  "GAMBLING": 0,
  "SEXUAL_CONTENT_NUDITY": 0,
  "GRAPHIC_SEXUAL_CONTENT_NUDITY": 0,
  "UNRESTRICTED_WEB_ACCESS": 0,
  "GAMBLING_CONTESTS": 0
}
```
</details>

**Comment by RishabhTayal** [comment]
@joshdholtz I figured out what the issue was. The issue is not with the `app_rating_config_path`. I was sending wrong value for the `metadata/trade_representative_contact_information/country.txt` file. This requires a valid country name.

Closing this now.
