### ISSUE TITLE
Pass args to swift lanes from command line

### ISSUE THREAD

**Issue by doruvil** [fastlane/fastlane#12277]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In order to pass arguments to a swift lane I found the following:
Issue: https://github.com/fastlane/fastlane/issues/11747
Issue: https://github.com/fastlane/fastlane/issues/11370
PR: https://github.com/fastlane/fastlane/pull/11401

I have discovered that the usage is different from what is described in the issue.
For example:

Declaring lane as:
~~~~
func hockeyLane(client: String, env: String) { 
      // things to be done by the lane
}
~~~~
will not be detected  as a lane.

the format which is working is:
~~~~
func hockeyAppLane(withOptions options:[String: String]?) {
     // things to be done by the lane
}
~~~~

and running the lane from command line would need:
`bundle exec fastlane hockeyApp environment:Staging buildnumber:100`
for example.

Nevertheless, it is needed to be updated the contents of:
*LaneFileProtocol* because the message:
`[!] Could not find lane 'demoLane'. Available lanes: first, thirdLaneWithOpti, fourthLaneWithOpti, hockeyAppLaneWithOpti`
can be better formated in order to provide quick feedback with the available lanes.

I have detailed my test scenarios here:
https://medium.com/@doruvil/fatlane-continous-integration-swift-version-b8851f1f38b6

##### Complete output when running fastlane, including the stack trace and command used
~~~~
user-vilceanud:FastlaneSwift dumitruvilceanu$ bundle exec fastlane demoLane
[✔] 🚀 
[15:37:18]: loading manifest: /Users/dumitruvilceanu/.gem/gems/fastlane-2.89.0/fastlane/swift/upgrade_manifest.json
[15:37:18]: FastlaneSwiftRunner project is up-to-date
[15:37:18]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:37:19]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/dumitruvilceanu/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[15:37:23]: $ ./fastlane/FastlaneRunner lane demoLane > /dev/null
[15:37:23]: [!] Could not find lane 'demoLane'. Available lanes: first, thirdLaneWithOpti, fourthLaneWithOpti, hockeyAppLaneWithOpti
~~~~

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@doruvil This _should_ be fixed now by https://github.com/fastlane/fastlane/pull/12382

**Comment by doruvil** [comment]
@joshdholtz sorry for the delayed reply.
There are some changes needed.
For the following Fastfile.swift:
https://github.com/doruvil/FastlaneSwift/blob/testing-fastlane-swift-limits/FastlaneSwift/fastlane/Fastfile.swift

The feedback provided in case of wrong lane signature is different from the result of
`fastlane lanes` action:

**Comment by doruvil** [comment]
![screen shot 2018-06-11 at 14 55 00](https://user-images.githubusercontent.com/4958872/41232923-1ff2f694-6d88-11e8-92e2-0119ceb6ed2d.png)

**Comment by doruvil** [comment]
![screen shot 2018-06-11 at 14 55 16](https://user-images.githubusercontent.com/4958872/41232928-2550cca6-6d88-11e8-93c6-e2934e0e2f59.png)

**Comment by doruvil** [comment]
I have tested of course using the latest version of fastlane: 2.97.0
