### ISSUE TITLE
Command `addvideo` deprecated. Use `addmedia` instead.

### ISSUE THREAD

**Issue by onato** [fastlane/fastlane#12289]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The `add_video` Snapshot setting produces the following command.

`xcrun simctl addphoto F03917FD-9D7F-48A8-948F-D730EB88027D MyVideo.mp4`

Running this with Xcode 9.3 produced the following error.

`Warning: addphoto is deprecated, use addmedia instead
An error was encountered processing the command (domain=NSCocoaErrorDomain, code=-1):
The operation couldn’t be completed. (Cocoa error -1.)`

The error message is not very descriptive, but given the warning I tried using `addmedia` instead. This fixed the problem for me. Looking at the responsible method https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb#L68-L83 it appears that the `media_type` parameter can be removed if we switch to `xcrun simctl addmedia`.

If backwards compatibility is not an issue I'd be happy to submit a PR.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane snapshot
[✔] 🚀
[10:07:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:07:53]: Successfully loaded '/Users/stephen/Documents/Code/Intellum/exceed-ios/fastlane/Snapfile' 📄

+-----------------------+---------------------------+
|    Detected Values from './fastlane/Snapfile'     |
+-----------------------+---------------------------+
| devices               | ["iPhone X"]              |
| languages             | ["en-US"]                 |
| scheme                | UITests                   |
| output_directory      | ./screenshots             |
| reinstall_app         | true                      |
| concurrent_simulators | true                      |
| add_videos            | ["../test-data/Hops.mp4"] |
+-----------------------+---------------------------+

[10:07:54]: $ xcodebuild -showBuildSettings -workspace ./ExceedLMS.xcworkspace -scheme UITests

+----------------------------+---------------------------------------------------------------+
|                                Summary for snapshot 2.91.0                                 |
+----------------------------+---------------------------------------------------------------+
| workspace                  | ./ExceedLMS.xcworkspace                                       |
| output_directory           | /Users/stephen/Documents/Code/Intellum/exceed-ios/screenshots |
| devices                    | ["iPhone X"]                                                  |
| languages                  | ["en-US"]                                                     |
| launch_arguments           | [""]                                                          |
| output_simulator_logs      | false                                                         |
| skip_open_summary          | false                                                         |
| skip_helper_version_check  | false                                                         |
| clear_previous_screenshots | false                                                         |
| reinstall_app              | true                                                          |
| erase_simulator            | false                                                         |
| localize_simulator         | false                                                         |
| app_identifier             | com.intellum.ExceedLMS                                        |
| add_videos                 | ["../test-data/Hops.mp4"]                                     |
| buildlog_path              | ~/Library/Logs/snapshot                                       |
| clean                      | false                                                         |
| scheme                     | UITests                                                       |
| number_of_retries          | 1                                                             |
| stop_after_first_error     | false                                                         |
| concurrent_simulators      | true                                                          |
| xcode_path                 | /Applications/Xcode.app                                       |
+----------------------------+---------------------------------------------------------------+

[10:07:57]: Building and running project - this might take some time...
[10:07:58]: Patching simulators '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[10:08:04]: Launch Simulator iPhone X
[10:08:04]: $ xcrun instruments -w CDE40CCA-D179-46AC-90E0-D56756FA67F8 &> /dev/null
[10:08:07]: Uninstall application com.intellum.ExceedLMS
[10:08:07]: $ xcrun simctl uninstall CDE40CCA-D179-46AC-90E0-D56756FA67F8 com.intellum.ExceedLMS &> /dev/null
[10:08:13]: Launch Simulator iPhone X
[10:08:13]: $ xcrun instruments -w CDE40CCA-D179-46AC-90E0-D56756FA67F8 &> /dev/null
[10:08:15]: Adding '../test-data/Hops.mp4'
[10:08:15]: $ xcrun simctl addvideo CDE40CCA-D179-46AC-90E0-D56756FA67F8 ../test-data/Hops.mp4 &> /dev/null
[10:08:16]: Running snapshot on: iPhone X
[10:08:16]: $ set -o pipefail && xcodebuild -workspace ./ExceedLMS.xcworkspace -scheme UITests -derivedDataPath '/var/folders/x1/1794tkfs2fsbz0xvb84jnym00000gn/T/snapshot_derived20180414-85842-siu9rs' -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' FASTLANE_SNAPSHOT=YES build test | tee /Users/stephen/Library/Logs/snapshot/ExceedLMS-UITests.log | xcpretty</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.2                           |
| Installation Source         | ~/.gem/ruby/2.3.3/bin/fastlane              |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.3/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_NZ.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end
  
  
  desc "Deploy a new version to the App Store"
  lane :release do

    inc
    gym(scheme: "Tribe Social", 
        configuration: "Release", 
        export_method: "app-store",
        export_options: {
          provisioningProfiles: { 
            "com.intellum.tribe" => "match AppStore com.intellum.tribe"
          }
        }
    )
    upload_release 
    staging
  end

  desc "Upload the release build"
  lane :upload_release do

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    deliver(force: true, 
            release_notes: changelog_from_git_commits, 
            app_identifier: "com.intellum.tribe", 
            skip_metadata: true,
            skip_screenshots: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :staging do

    #inc
    gym(scheme: "Tribe Social", 
        configuration: "Staging", 
        export_method: "app-store",
        export_options: {
          provisioningProfiles: { 
            "com.intellum.tribe" => "match AppStore com.intellum.tribe.staging"
          }
        }

    )

    upload_staging
  end

  desc "Upload the staging build"
  lane :upload_staging do

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    deliver(force: true, 
            release_notes: changelog_from_git_commits, 
            app_identifier: "com.intellum.tribe.staging", 
            skip_metadata: true,
            skip_screenshots: true
    )
  end

  lane :profiles do
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe")
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe.ShareExtension")
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe.NotificationExtension")
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe.NotificationContent", 
          clone_branch_directly: true,
          shallow_clone: true,
          verbose: true
    )

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "adhoc",
          #app_identifier: "com.intellum.tribe")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "adhoc",
          #app_identifier: "com.intellum.tribe.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "adhoc",
          #app_identifier: "com.intellum.tribe.NotificationExtension")
       

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging.NotificationExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging.NotificationContent")

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging.NotificationExtension")

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging.NotificationExtension")

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug.NotificationExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug.NotificationContent", 
          #clone_branch_directly: true,
          #shallow_clone: true,
          #verbose: true
    #)

  end

  desc "Increment the build number"
  lane :inc do
    increment_build_number(
      xcodeproj: 'TribeSocial/Tribe.xcodeproj',
      build_number: "#{get_build_number(xcodeproj: 'TribeSocial/Tribe.xcodeproj').to_i + 1}"
    )
  end

  desc "Download DSYM files from iTunesConnect and upload them to Crashlytics"
  lane :dsyms do
    download_dsyms(version: "latest")                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics                      # Upload them to Crashlytics
    clean_build_artifacts                              # Delete the local dSYM files
  end
  
  desc "Generate an HTML file containing all of the screenshots"
  lane :gen_report do
    Dir.chdir("..") do
      require 'snapshot/reports_generator'
      Snapshot.config[:output_directory] = "screenshots"
      Snapshot::ReportsGenerator.new.generate
    end
  end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.intellum.tribe" # The bundle identifier of your app
apple_id "swilliams@intellum.com" # Your Apple email address

team_id "JYANFLU7NT"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.91.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.3        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.8        |
| io-console                | 0.4.5        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.2.1        |
| CFPropertyList            | 2.3.4        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| bundler                   | 1.15.0       |
</details>

*generated on:* **2018-04-14**
</details></pre>
</details>

**Comment by onato** [comment]
Bump

**Comment by joshdholtz** [comment]
@onato Thanks for the find! Backwards compatibility is something that we definitely need to maintain. Would you still be comfortable making this PR? If not, I can totally do it 😊

**Comment by joshdholtz** [comment]
@onato Created a PR for this ^
