### ISSUE TITLE
[Question] About fastlane deliver

### ISSUE THREAD

**Issue by mofneko** [fastlane/fastlane#12282]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have some questions about fastlane deliver

· About auto_release_date
Is it necessary to set automatic_release to ture when using this parameter?
What should the type of this parameter be given?
The date set by this parameter is the same specification as that of iTC, and is it set as the time of the time zone to which the stores of world countries belong?
Is this parameter an epoch millisecond?

**Comment by mofneko** [comment]
The following questions self-solved
"Is it necessary to set automatic_release to ture when using this parameter?
"
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb#L140

if you do not mind
Please tell me what parameters are required to submit the application to the store review using delivery immediately after creating plain app in iTunes Connect
In that case, automatic release is not a condition

**Comment by mofneko** [comment]
@joshdholtz I appreciate your reply.
I looked into some actions. Strangely, although DeliverFile has parameters called metadata path and appicon path, even if it is not mentioned, it will be automatically affected when the target file is placed under the fastlane directory.
It is amazing. Do you have other files that behave like this? I expected ScreenShot to do it, but it did not work.

**Comment by joshdholtz** [comment]
@mofneko A lot of the tools have things similar like that. 

### Some samples
- _snapshot_ has `Snapfile` https://docs.fastlane.tools/actions/snapshot/#snapfile
- _match_ has `Matchfile`
- `Appfile` is used by many fastlane things - https://docs.fastlane.tools/advanced/#appfile

**Comment by mofneko** [comment]
@joshdholtz Thank you very much.
However, the details of my question are to visit the file which loads automatically even if you do not mention the path in GymFile such as .txt file placed under metadata rather than the configuration file (eg GymFile) specific to fastlane It was.

**Comment by mofneko** [comment]
I am interested in reflecting on iTC when executing the fastlane deliver command by placing the file called AppIcon.jpg in the fastlane directory.

**Comment by mofneko** [comment]
I'm sorry my question was not in the correct format.

For example, DeliverFile has an option to describe a directory storing information such as metadata_path, screenshot_path, app_icon.
However, if metadata information is stored in the directory fastlane / metadata, it will be loaded at deliver time without description.

**Comment by mofneko** [comment]
I'm sorry my question was not in the correct format.

For example, DeliverFile has an option to describe a directory storing information such as metadata_path, screenshot_path, app_icon.
However, if metadata information is stored in the directory fastlane / metadata, it will be loaded at deliver time without description.
