### ISSUE TITLE
Fastlane Snapshot is try to read the devices.plist of a simulator that does not exist 

### ISSUE THREAD

**Issue by morlombakop** [fastlane/fastlane#12284]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When i try the capture screenshot, i have an iO error.
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/CFPropertyList-3.0.0/lib/cfpropertylist/rbCFPropertyList.rb:333:in `load': [!] File /Users/lrcdmobile/Library/Developer/CoreSimulator/Devices/036CEF0D-9208-4B8B-88CE-B406CB91DAAE/device.plist not readable!

I have check the the devices 036CEF0D-9208-4B8B-88CE-B406CB91DAAE does not exist.

This is my Snapfile 

```
# A list of devices you want to take the screenshots from
devices([
  "iPhone 8 Plus",
  "iPad Pro (9.7-inch)"
])

languages([
  "en-GB"
])
ios_version "11.2"

# The name of the scheme which contains the UI Tests
# scheme "lrclassdirect"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

[19:37:10]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                |
| --------------------------- | -------------------------------------------------------------------- |
| OS                          | 10.12.6                                                              |
| Ruby                        | 2.2.4                                                                |
| Bundler?                    | false                                                                |
| Git                         | git version 2.14.1                                                   |
| Installation Source         | /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G1212)                                           |
| Ruby Lib Dir                | /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                           |
| Is contained                | true                                                                 |
| Is homebrew                 | false                                                                |
| Is installed via Fabric.app | false                                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                          |
| Xcode Version               | 9.2                                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("lr.classdirect.ios") # The bundle identifier of your app
apple_id("mobileapps@lr.org") # Your Apple email address
team_name("Lloyd's Register group services limited")

itc_team_id("118525567") # iTunes Connect Team ID
team_id("EY892TPJDX") # Developer Portal Team ID


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 3.0.0        |
| CFPropertyList            | 2.3.6        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.62.0       |
| excon                     | 0.60.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.10       |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.4        |
| naturally                 | 2.1.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.4.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.3        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.1.0        |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.3.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.7        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@morlombakop Can you paste your whole console output in here for me? 😊 Thanks!
