### ISSUE TITLE
Fastlane init not getting correct Schema name for workspace 

### ISSUE THREAD

**Issue by ggallotti** [fastlane/fastlane#12288]
### Issue Description

Fastlane is not getting the correct Scheme name from my Workspace. 
(Used to work before)

xcodebuild: error: The workspace named "Betting_UI_InZone_AppQuiniela" does not contain a scheme named "Betting_UI_InZone_AppQuiniela".

My Schema Name is: AppQuiniela

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>GonzaMacBook:Betting_UI_InZone_AppQuiniela ggallotti$ fastlane init
[✔] 🚀 
[✔] Looking for iOS and Android projects in current directory...
[00:21:18]: Detected an iOS/macOS project in the current directory: 'Betting_UI_InZone_AppQuiniela.xcworkspace'
[00:21:18]: -----------------------------
[00:21:18]: --- Welcome to fastlane 🚀 ---
[00:21:18]: -----------------------------
[00:21:18]: fastlane can help you with all kinds of automation for your mobile app
[00:21:18]: We recommend automating one task first, and then gradually automating more over time
[00:21:18]: What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
?  2
[00:21:21]: -----------------------------------------------------------
[00:21:21]: --- Setting up fastlane for iOS TestFlight distribution ---
[00:21:21]: -----------------------------------------------------------
[00:21:21]: Parsing your local Xcode project to find the available schemes and the app identifier
[00:21:21]: $ xcodebuild -showBuildSettings -workspace Betting_UI_InZone_AppQuiniela.xcworkspace -scheme Betting_UI_InZone_AppQuiniela
xcodebuild: error: The workspace named "Betting_UI_InZone_AppQuiniela" does not contain a scheme named "Betting_UI_InZone_AppQuiniela". The "-list" option can be used to find the names of the schemes in the workspace.
[00:21:22]: Could not read build settings. Make sure that the scheme "Betting_UI_InZone_AppQuiniela" is configured for running by going to Product → Scheme → Edit Scheme…, selecting the "Build" section, checking the "Run" checkbox and closing the scheme window.
[00:21:22]: Bundle identifier of your app: 

xcodebuild -showBuildSettings -workspace Betting_UI_InZone_AppQuiniela.xcworkspace -list
Information about workspace "Betting_UI_InZone_AppQuiniela":
    Schemes:
        AppQuiniela
        Bolts
        FBSDKCoreKit
        FBSDKLoginKit
        FBSDKShareKit
        Pods-AppQuiniela
        Pods-OneSignalNotificationServiceExtension
        QBImagePickerController
        QBImagePickerController-QBImagePicker

</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D47)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.89.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@ggallotti Can you take a screenshot of the "Edit Scheme..." modal from Xcode so we can see what all schemas should be available? Your console output show the "AppQuiniela" scheme. Is this the scheme that you actually want?
