### ISSUE TITLE
update_availability is not working. Apple has changed mandatory fields.

### ISSUE THREAD

**Issue by Wojcik** [fastlane/fastlane#12283]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Getting ** ~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/tunes_client.rb:227:in `handle_itc_response': Your app must be marked as cleared for pre-order to modify available date. (Spaceship::Tunes::Error)** while trying to change available countries.

Code
```ruby
	app = Spaceship::Tunes::Application.find(bundle_id)

	availability = app.availability
	availability.include_future_territories = true
	availability = Spaceship::Tunes::Availability.from_territories(["FR", "DK", "GB", "IE", "UA", "SE", "DE", "AT"])
	app.update_availability!(availability)
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/tunes_client.rb:227:in `handle_itc_response': Your app must be marked as cleared for pre-order to modify available date. (Spaceship::Tunes::Error)
[12:36:16]: ▸ from ~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/tunes_client.rb:611:in `update_availability!'
[12:36:16]: ▸ from ~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/application.rb:261:in `update_availability!'
[12:36:16]: ▸ from usefull_scripts/submit_to_review.rb:31:in `<main>'
[12:36:16]: Exit status of command 'ruby usefull_scripts/submit_to_review.rb com.xxx.xxx' was 1 instead of 0.
[12:35:45]: Login to iTunes Connect (iwaiterdeveloper@gmail.com)
~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/tunes_client.rb:227:in `handle_itc_response': Your app must be marked as cleared for pre-order to modify available date. (Spaceship::Tunes::Error)
	from ~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/tunes_client.rb:611:in `update_availability!'
	from ~/.rvm/gems/ruby-2.4.1/gems/fastlane-2.89.0/spaceship/lib/spaceship/tunes/application.rb:261:in `update_availability!'
	from usefull_scripts/submit_to_review.rb:31:in `<main>'</pre>
</details>

Apple added `"preOrder"=>{"clearedForPreOrder"=>{"value"=>false, "isEditable"=>false, "isRequired"=>false, "errorKeys"=>nil}` to "ra/apps/#{app_id}/pricing/intervals" so I fixed this error by adding 
`data["preOrder"] = {"clearedForPreOrder"=>{"value"=>false, "isEditable"=>false, "isRequired"=>false, "errorKeys"=>nil}}` to update_availability! method of TunesClient but it's good to have it updated in fastlane. Thanks.

**Comment by joshdholtz** [comment]
@Wojcik This is good to know! I will add "pre-order" a thing 😊 Thanks for finding this ❤️

**Comment by joshdholtz** [comment]
@Wojcik I _think_ the actual solution here is to call `data.delete("preOrder")`

The data object contains...
```json
"preOrder":{
  "clearedForPreOrder":{
    "value":false,
    "isEditable":false,
    "isRequired":false,
    "errorKeys":null
  },
  "appAvailableDate":{
    "value":"2013-06-18",
    "isEditable":false,
    "isRequired":false,
    "errorKeys":null
  },
  "preOrderAvailableDate":null
},
```

so it was trying to reset the `appAvailableDate` (which is why you were getting that error). Instead of overwriting this value completely, I'm going to change this up to delete the `preOrder` key completely so that it won't get updated to anything

**Comment by damoncoo** [comment]
@joshdholtz how did you add pre-order data? I am not quite familiar with the usage

**Comment by joshdholtz** [comment]
PR has been made ^ 😊
