### ISSUE TITLE
 character content of element "file_name" invalid; must be a string matching the regular expression "[^/: ]

### ISSUE THREAD

**Issue by YissacharB** [fastlane/fastlane#12294]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have an app with an Hebrew name.
It worked fine before now when im trying to use deliver i'm getting this error:

[Transporter Error Output]: ERROR ITMS-3000: "Line 7 column 111: character content of element "file_name" invalid; must be a string matching the regular expression "[^/: ]+" at XPath /package/software_assets/asset/data_file/file_name"

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[20:56:31]: [31mERROR ITMS-3000: "Line 7 column 111: character content of element "file_name" invalid; must be a string matching the regular expression "[^/: ]+" at XPath /package/software_assets/asset/data_file/file_name"
ERROR ITMS-3000: "Package "com.*.*" failed schema validation."
Return status of iTunes Transporter was 1: ERROR ITMS-3000: "Line 7 column 111: character content of element "file_name" invalid; must be a string matching the regular expression "[^/: ]+" at XPath /package/software_assets/asset/data_file/file_name"

ERROR ITMS-3000: "Package "com.*.*" failed schema validation."</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.6.0                           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | ~/Downloads/Xcode 2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.90.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| excon                     | 0.62.0       |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-04-12**
</details></pre>
</details>

**Comment by aric87** [comment]
Same issue with an app name with a space in it. Looks to be the same issue as this https://github.com/fastlane/fastlane/issues/10373

**Comment by CavalcanteLeo** [comment]
It's happen to me to after o upgraded to 2.9, I will downgrade too

**Comment by YissacharB** [comment]
Mine has space too, and it seems that ia not the character in Hebrew but the space.

**Comment by emilkarl** [comment]
Same here

**Comment by CavalcanteLeo** [comment]
I've downgraded to 2.9.0 and now it's working again

**Comment by owurman** [comment]
I had to downgrade to 2.81.0 to get around this.

**Comment by emilkarl** [comment]
I went down to `2.89.0` and it works fine!

**Comment by cmartin81** [comment]
Same issue her also...

**Comment by lukaskukacka** [comment]
Same issue here with `fastlane-2.91.0`

**Comment by AndyDunn** [comment]
Is there an easy work around for this using a config parameter of Fastfile? I'd rather not have to change anything in Xcode.

**Comment by joshdholtz** [comment]
Looking into this right now!

**Comment by joshdholtz** [comment]
Hey everyone! Sorry about this issue. This should be fixed now in `2.92.0` 😊 

As a side note: please feel free to put the word "regression" in the title if something like this happens again. The issue will pop out a little bit more to the team and get fixed right away 🙃
