### ISSUE TITLE
Crashlytics cannot handle relative directories for IPA path

### ISSUE THREAD

**Issue by Apocryphon** [fastlane/fastlane#12295]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

All of my app builds are to a specific directory `~/my_builds/archive/MyApp-X.Y.Z./`, with X.Y.Z. being the build number. `gym` is able to create that ipa file flawlessly. However, when I attempt to submit it with crashlytics, it fails. In my lane is:

```
crashlytics(	api_token: sh("echo $api_key"),
          		build_secret: sh("echo $api_secret"),
          		ipa_path: my_build_dir + "/MyApp.ipa"
          	  )

```

`my_build_dir = "~/my_builds/archive/MyApp-" + version`

`my_build_dir` is the local variable in my Fastfile. You can see Crashlytics fail to find it below, even though the file exists. Could it be because Crashlytics does not interpret the `~` as the user home directory?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ fastlane qa --verbose --capture_output
[✔] 🚀 
[17:11:40]: fastlane detected a Gemfile in the current directory
[17:11:40]: however it seems like you don't use `bundle exec`
[17:11:40]: to launch fastlane faster, please use
[17:11:40]: 
[17:11:40]: $ bundle exec fastlane qa --verbose --capture_output
[17:11:40]: 
[17:11:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-04-12 17:11:41.00]: Checking if there are any plugins that should be loaded...
INFO [2018-04-12 17:11:41.18]: ------------------------------
INFO [2018-04-12 17:11:41.18]: --- Step: default_platform ---
INFO [2018-04-12 17:11:41.18]: ------------------------------
INFO [2018-04-12 17:11:41.18]: Driving the lane 'ios fabric' 🚀
INFO [2018-04-12 17:11:41.18]: ----------------------------------
INFO [2018-04-12 17:11:41.18]: --- Step: get_info_plist_value ---
INFO [2018-04-12 17:11:41.18]: ----------------------------------
INFO [2018-04-12 17:11:41.18]: ----------------------------------
INFO [2018-04-12 17:11:41.18]: --- Step: get_info_plist_value ---
INFO [2018-04-12 17:11:41.18]: ----------------------------------
INFO [2018-04-12 17:11:41.21]: --- Step: crashlytics ---
INFO [2018-04-12 17:11:41.21]: -------------------------
ERROR [2018-04-12 17:11:41.21]: Error setting value '~/my_builds/archive/MyApp-1.0.1/MyApp.ipa' for option 'ipa_path'
ERROR [2018-04-12 17:11:41.21]: You passed invalid parameters to 'crashlytics'.
ERROR [2018-04-12 17:11:41.21]: Check out the error below and available options by running `fastlane action crashlytics`
WARN [2018-04-12 17:11:41.21]: Lane Context:
INFO [2018-04-12 17:11:41.21]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios fabric", :GET_INFO_PLIST_VALUE_CUSTOM_VALUE=>"1.0.1"}
ERROR [2018-04-12 17:11:41.21]: Couldn't find ipa file at path '~/my_builds/archive/MyApp-1.0.1/MyApp.ipa'
INFO [2018-04-12 17:11:41.21]: Successfully generated documentation at path '...'
ERROR [2018-04-12 17:11:41.23]: fastlane finished with errors</pre>
</details>

### Environment

<details>
  <pre>| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.3                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E199)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.90.0  | ✅ Up-To-Date  |
</pre>
</details>

**Comment by Apocryphon** [comment]
When I replace the tilde with my home directory path, `crashlytics` is satisfied, but then it fails thusly:

```
[!] 2018-04-12 17:30:48.251 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2018-04-12 17:30:48.257 submit Crashlytics: Companion to the Crashlytics Mac App for submitting iOS builds for Beta Testing.
     Usage: 
        submit  API_KEY BUILD_SECRET        default options for upload after archive, with ipa path in environment 
         additional options:
         -help                          display this message
         -ipaPath           [path to IPA]
         -emails            [tester email address],[email]
         -groupAliases      [group build server alias],[group]
         -notesPath         [release notes]
         -notifications     YES|NO
         -debug             YES|NO
sh: line 1: $api_secret : command not found
sh: line 2: -ipaPath: command not found
```
Where `$api_secret` in the error page is the string of my actual API key, the result of `sh("echo $api_secret")`. So is it even possible for to invoke environmental variables in Crashlytics when passing in the key and secret?

**Comment by jshier** [comment]
You should access the environment variables directly using `ENV["name"]`. Better yet, export them using the names the `crashlytics` action expects (`CRASHLYTICS_API_TOKEN` and `CRASHLYTICS_BUILD_SECRET`) and it will pick them up automatically.

**Comment by joshdholtz** [comment]
@Apocryphon Using `~` will sometimes cause errors. In that case, I sometimes call `File.absolute_path('~/something/something')` to get the absolute path to pass to things.

And @jshier is right, you should use `ENV['name']` to access environment variables. You could also make use of `.env` files to store your environment variables - https://docs.fastlane.tools/advanced/#environment-variables
