### ISSUE TITLE
Could not find `fastlane`

### ISSUE THREAD

**Issue by ashishpatill** [fastlane/fastlane#12297]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello i am trying fastlane for first time.

I am getting :- "fastlane init -bash: fastlane: command not found".
I have tried every step as mentioned in your docs. Please update the docs to make it more generic for all developers. My view is not only experienced ones need automation, less experienced ones too. I am an iOS dev and newbee to terminal commands or with whole command world without any interface. Please guide me how to fix this issue.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>
****

**Comment by ashishpatill** [comment]
updated with issue checklist

**Comment by revolter** [comment]
Does https://github.com/fastlane/fastlane/issues/729 help you?

**Comment by revolter** [comment]
Also, it would be easier to help you if you would describe the issue in the description instead of the title 😅

**Comment by DanToml** [comment]
Updated the title/issue for readability.

**Comment by DanToml** [comment]
@ashishpatill Hey, to be able to help you here, we need some more information:

- How did you install fastlane?
- What is the output of `echo $PATH`
- What is the output of `which ruby`
- What is the output of `which fastlane`
- What is the output of `gem list`

Thanks!
