### ISSUE TITLE
[Feature] Provide changelog based on recent commits

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#123]
`fastlane` should somehow detect all commits done, since the last build of the current lane and put all the commit messages into one string variable. This should then be provided using the lane context.

**Comment by bassrock** [comment]
:+1: Another add on for this would be to pass the info to the TestFlight "What To Test"

**Comment by KrauseFx** [comment]
Absolutely, this sounds pretty amazing :+1:

**Comment by coreyfloyd** [comment]
Started working on this in my Fastfile before I attempted to make a full blown action out of it. My solution depends on Jenkins… but was pretty straightforward (added a dependency for "git" to stay in ruby - but you could just execute a shell script)

```
def generate_git_commit_log
  g = Git.open(ENV['PWD'], :log => Logger.new(STDOUT))
  change_log = g.log.between(ENV['LAST_SUCCESS_REV']).map {|commit| commit.message}.join('\n')
  ENV['GIT_COMMIT_LOG'] = 'Commit Log:\n\n' + change_log
end
```

Honestly though, I wanted to do better than just dump the commit messages before I submitted a patch… I want to parse the commit messages for the issue numbers and pull in the issue descriptions. But that means building an action that works with at least one specific issue tracker (probably should be Github). Of course my day job has me stuck in Phabricator - so thats probably what I will work on first.

**Comment by KrauseFx** [comment]
@coreyfloyd I found 2 things that might help:

- [SSBuild's git changelog code for Jenkins](https://github.com/splinesoft/SSBuild/blob/master/SSBuild.sh#L236)
- [tj's git library to generate a changelog](https://github.com/tj/git-extras/wiki/Commands#git-changelog)

I honestly don't think fetching URL's content should be part of this action. 

It would be great to just append all commit messages since either the last Jenkins run or the last git tag.

What do you think?

**Comment by coreyfloyd** [comment]
@KrauseFx SSBuild's changeling code is essentially the same as what I posted above (just bash instead of ruby). If you think that would be useful to others, I could wrap it up into an action.

As far as whether Fastlane should connect to outside URLs to obtain change log information… I've put together automated change logs a few times and it usually evolves from git commit logs to testers wanting/needing the ticket information. Because whoever is testing the app (I'm talking internally) needs to map to the ticket to do their job (Releasing code to external beta testers has different needs).

So maybe for this action we can keep it simple - just the commit log messages?

I'll still be working on an action to grab our ticket information for Phabricator - we need that for internally for our project.

**Comment by KrauseFx** [comment]
Yes, just the commit logs would be great :+1:

**Comment by eytanbiala** [comment]
Having the option to use either the last Jenkins run or the last git tag would be nice!

**Comment by bgerstle** [comment]
The current approach we're taking at Wikipedia is to grab either the `GIT_PREVIOUS_SUCCESSFUL_COMMIT` env var (from Jenkins Git plugin) or 5 revisions ago (`HEAD^^^^^`).  You can see the code on our [GitHub mirror](https://github.com/wikimedia/apps-ios-wikipedia/blob/master/fastlane/lib/utils.rb#L46), in `fastlane/lib/utils.rb#generate_git_commit_log`.

However, we've been having problems with getting the notes into TestFlight. Nothing we've tried populates the "What To Test" field in iTC. Neither the `changelog` DSL method in the DeliverFile nor setting `ENV['DELIVER_WHAT_TO_TEST'] = ...`.

**Comment by bgerstle** [comment]
Sorry to hijack the thread, I can create a separate issue, but figured it was relevant.

**Comment by KrauseFx** [comment]
@bgerstle Thanks for sharing your solution on how you get the git commit logs. Really interesting, this could be a great new `fastlane` action :+1: 

For not filling in the changelog: The `changelog` option in the `Deliverfile` sets the changelog of the app on iTunes Connect (seen in the App Store), while `DELIVER_WHAT_TO_TEST` should pre-fill the change log for the TestFlight build. 

If it's not working, please create a separate issue, so we can take a closer look :+1:

**Comment by parkej60** [comment]
I would love to see this feature be agnostic to the build server being used. We currently use TeamCity instead of Jenkins. :+1:

**Comment by bgerstle** [comment]
here's how I'm thinking the API could look:

``` ruby
git_changelog(
  from: '012345', # or FL_GIT_CHANGELOG_FROM, defaults to HEAD^^^^^
  to: '012346', # or FL_GIT_CHANGELOG_TO, defaults to HEAD
) { |commit| "- #{commit.message.lines.first.chomp} # optional line formatter, default shown here
```

From this, it could be possible to add convenience wrappers for Jenkins, etc. like so:

``` ruby
jenkins_git_changelog :last_successful { |c| ... } # use Jenkins/GitPlugin env vars under the hood
# and for TC, etc...
```

**Comment by KrauseFx** [comment]
@bgerstle what's the main use cases?

I think it's 

> Git changelog since the last deploy/beta build (usually from a git tag)

Therefore specifying a git commit sha is probably not very useful except for the Jenkins case you mentioned. We probably have to support both tags and specific commits.

What do you think?

**Comment by bgerstle** [comment]
@KrauseFx a ref can be a SHA, tag, branch, etc., so any of these should be supported. The tricky bit is figuring out which ref to get the commits from, depending on the CI environment.

**Comment by KrauseFx** [comment]
That sounds like a good plan. There is a command to get the latest tag: http://stackoverflow.com/a/7261049/445598

```
git describe --abbrev=0 --tags
```

I think we can use that as a default value, as from my perspective this will be the top use case.

**Comment by bgerstle** [comment]
@KrauseFx sounds good. does anyone else want to weigh in on the default value for the git ref to grab commits from when generating a changelog?

**Comment by dhagerty9009** [comment]
Maybe look at how [this](https://github.com/skywinder/github-changelog-generator) gem is doing it? Only issue is this gem seems to only work with GitHub.

**Comment by JaviSoto** [comment]
This is now possible with `changelog_from_git_commits`: https://github.com/fastlane/fastlane/pull/964 🎉
