### ISSUE TITLE
What is the best build automatic tool for integatge with fastlane script ? (bettween Jenkins & OSX server)

### ISSUE THREAD

**Issue by uthens** [fastlane/fastlane#1230]
I will decide for setup the build server for my lane script on fastlane, do you have any suggestion on this ? 
now i have 2 choice.
1) Jenkins OR 2) OSX server

Reference : 
https://honzadvorsky.com/articles/2015-08-04-xcs_tutorials_1_getting_started/
http://youandthegang.com/2015/continuous-integration-delivery-with-jenkins/
http://blog.zuehlke.com/en/continuous-integration-for-mobile-apps-with-fastlane-and-jenkins/

Please suggestion with me.

**Comment by KrauseFx** [comment]
You can choose, in general Jenkins gives you much more control, while Xcode server is better looking and easier to use. Also, maybe @czechboy0 wants to jump in here.

**Comment by czechboy0** [comment]
I'm not objective, because I've worked with Xcode Server deeply for over a year and I was able to get it to work with everything I needed (see my tutorials for lots of reading on this). I like how XCS is integrated with Xcode, adopting new features quickly, whereas I've see Jenkins plug-ins take ages to get updated. 

I'd suggest you try the simpler tool first - Xcode Server and if it doesn't let you do something you definitely need, switch to Jenkins.

**Comment by jsslai** [comment]
I'm not sure if this is a right place, but I've been following @czechboy0 article: https://honzadvorsky.com/articles/2015-09-14-15-00-xcode_server_hacks_3_install_cli_tools_for_xcsbuildd/

I've installed fastlane with Homebrew. If I follow tutorial steps and then run `fastlane beta` I'll get:

`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 13 total gem(s) (Gem::LoadError)`

What is wrong?

**Comment by czechboy0** [comment]
Do you run it when logged in as `_xcsbuildd` user or as a Xcode Bot prebuild script? In the first case, make sure to log in with `sudo su - _xcsbuildd` (that dash in the middle is important). In the second, make sure to have the `source ~/.profile` call before calling out to fastlane.

(Also, I'm assuming you installed fastlane properly?)

**Comment by jsslai** [comment]
I've tried both. From the bot with following script: 

```
source ~/.profile
fastlane beta
```

From terminal:

```
sudo su - _xcsbuildd 
fastlane beta
```

I've installed fastlane from Homebrew (as a default user, not logged in with _xcsbuildd): `brew install fastlane`. Then I followed the steps in the article:

```
\curl -sSL https://get.rvm.io | bash -s stable
source ~/.profile
rvm autolibs read-only
rvm install ruby
```

**Comment by uthens** [comment]
Thanks you all, i will try again on next week :) :+1:
