### ISSUE TITLE
 [Transporter Error Output]: The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s)

### ISSUE THREAD

**Issue by invoodoo** [fastlane/fastlane#12302]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After latest update of fastlane it started to give this error. I did build just before update it was everything ok.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[10:38:17]: Login successful
[10:38:18]: Ready to upload new build to TestFlight (App: 850306139)...
[10:38:19]: Going to upload updated app to iTunes Connect
[10:38:19]: This might take a few minutes. Please don't interrupt the script.
[10:38:24]: [Transporter Error Output]: The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
[10:38:24]: Transporter transfer failed.
[10:38:24]: 
[10:38:24]: The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
[10:38:25]: [iTMSTransporter] [2018-04-13 10:38:24 PDT] <main> DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[pkg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}

[10:38:25]: [iTMSTransporter] [2018-04-13 10:38:24 PDT] <main> DBG-X:   parameter ErrorMessage = The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscor

[10:38:25]: [iTMSTransporter]  (1102)

[10:38:25]: [iTMSTransporter] [2018-04-13 10:38:24 PDT] <main> DBG-X:   parameter Success = false

[10:38:25]: [iTMSTransporter] [2018-04-13 10:38:24 PDT] <main> ERROR: The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore

[10:38:25]: [iTMSTransporter] [2018-04-13 10:38:24 PDT] <main> DBG-X: The error code is: 1102

[10:38:25]: [iTMSTransporter] 

[10:38:25]: [iTMSTransporter] 

[10:38:25]: [iTMSTransporter] 

[10:38:25]: [iTMSTransporter] Package Summary:

[10:38:25]: [iTMSTransporter]  

[10:38:25]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[10:38:25]: [iTMSTransporter] 	/var/folders/2c/wppz345x689bg23pc9gjb7cr0000gp/T/d20180413-79692-13cjmw1/850306139.itmsp - Error Messages:

[10:38:25]: [iTMSTransporter] 		The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore

[10:38:25]: [iTMSTransporter] [2018-04-13 10:38:24 PDT] <main> DBG-X: Returning 1

[10:38:25]: iTunes Transporter output above ^
[10:38:25]: The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
Return status of iTunes Transporter was 1: The filename .ipa_0bd16aa42f3bc516f51b0b7c4136697e2398c40e0b46cf16acbeb98321b8ba5f.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.13.4                                                 |
| Ruby                        | 2.2.4                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.15.1 (Apple Git-101)                      |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E199)                               |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                              |
| Is contained                | true                                                    |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Development/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

require 'spaceship'
require_relative '/Users/InVooDoo/Library/Mobile Documents/com~apple~CloudDocs/iWork/Misc/actions'

$apple_id = "evgeniy.lebed@gmail.com"
$git_branch = "master"
$team_id = "EHTMEM7E2H"
$itc_team_id = "2106312"

$bundle_ids = ["com.fancyinteractive.converter"]
$info_plists = ["Properties/Info.plist"]
$schemes = ["FancyUnits"]

$bundle_id = $bundle_ids[0]

$types = [""]

$project_path = "FancyUnits.xcodeproj"
$app_name = "FancyUnits"

$signing_identity = "iPhone Distribution: Ievgenii Lebid (EHTMEM7E2H)"

before_all do |lane, options|
    ENV["APP_IDENTIFIER"] = $bundle_id
end

platform :ios do
    lane :tf do |options|
        build(options)
    end

    lane :dsyms do |options|
        upload_dsyms(options)
    end

    lane :ver do |options|
        update_codesign_version
    end
end

after_all do |lane, options|
    clean_build_artifacts

    is_git_check = options[:check]

    if is_git_check
       reset_git_repo(force: true)
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id "evgeniy.lebed@gmail.com" # Your Apple email address

itc_team_id "2106312" # iTunes Connect Team ID
team_id "EHTMEM7E2H" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.91.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| emoji_regex               | 0.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-act       | 1.1.1        |
| fastlane-plugin-appicon   | 0.7.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.1.2        |
| google-api-client         | 0.13.1       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.6        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.4        |
| nap                       | 1.1.0        |
| naturally                 | 2.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.3.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.3        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.3        |
| tty-spinner               | 0.8.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.1.0        |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.3.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.7        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-04-13**
</details></pre>
</details>

**Comment by invoodoo** [comment]
Everything is ok, double checked. The problem with IPA name, after last update it with incorrect symbol in the name.

**Comment by invoodoo** [comment]
@joshdholtz just checked, still the same issue. 2.92.1 version of the fastlane

**Comment by joshdholtz** [comment]
@invoodoo What does your `PRODUCT_NAME` value look like in your Xcode project's build settings?

**Comment by invoodoo** [comment]
http://drops.invoodoo.com/ru37c9 "Free"

**Comment by joshdholtz** [comment]
@invoodoo I see where in the code that could fix this but I'm confused on how this is happening for you 🤔 I'm going to make a PR for this that will be available in a few days in `2.93.0`

**Comment by invoodoo** [comment]
@joshdholtz thanks, let me know if I can help you somehow.

**Comment by joshdholtz** [comment]
@invoodoo Can you try changing your `Gemfile` to the following to see if this works for you?
```rb
gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'joshdholtz-remove-basename-from-itc-uploaded-ipa'
```

**Comment by joshdholtz** [comment]
@invoodoo Ah sorry, I was assuming you had a `Gemfile` already. If you did have a `Gemfile`, you will need to run `bundle install` or `bundle update` before running `bundle exec fastlane <your lane>`.  Did you have a `Gemfile` already?

If not, you will need to also run `gem install bundler` before running `bundle install` or `bundle update`.

Don't worry if its too much trouble 🙃

**Comment by invoodoo** [comment]
@joshdholtz I have a gemfile, forgot about bundle install/update. I have done steps. And now it works.

**Comment by invoodoo** [comment]
@joshdholtz why it started to ask me select 

--------------------------------
[20:43:31]: --- Step: get_version_number ---
[20:43:31]: --------------------------------
What target would you like to use?
1. Free
2. Paid

**Comment by joshdholtz** [comment]
@invoodoo What version were you upgrading from? We also had to recently make a change `get_version_number` to make things more stable going forward. We were using `agvtool` which had sketch output and recently replaced it with using the `xcodeproj`. More info can be seen here - https://github.com/fastlane/fastlane/issues/12177#issuecomment-376912765

The answer though is to do something like...
```rb
get_version_number(
  target: 'Free' # or 'Paid'
)
```

**Comment by invoodoo** [comment]
@joshdholtz thanks for explanation.

**Comment by joshdholtz** [comment]
@invoodoo Not a problem! The way `get_version_number` behaved before was technically wrong so wanted to fix it going forward 😇 But were you able to get my new branch pulled down? Is that working for you now?

**Comment by invoodoo** [comment]
pilot works now very well ;)

**Comment by joshdholtz** [comment]
@invoodoo Woot woot! This PR will go out sometime later this week with the next release. Thanks for working on this with me 😊

**Comment by invoodoo** [comment]
@joshdholtz  sure, fastlane is awesome it is always a pleasure to help make it even better :)
