### ISSUE TITLE
RVM detected, forcing to use system ruby Now using system ruby

### ISSUE THREAD

**Issue by TargetNoBug** [fastlane/fastlane#12305]
[17:52:31]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[17:52:31]: 📋  For the complete and more detailed error log, check the full log at:
[17:52:31]: 📋  /Users/yuweiliu/Library/Logs/gym/XIDIAN-XIDIAN.log
[17:52:31]: 
[17:52:31]: Looks like fastlane ran into a build/archive error with your project
[17:52:31]: It's hard to tell what's causing the error, so we wrote some guides on how
[17:52:31]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[17:52:31]: Before submitting an issue on GitHub, please follow the guide above and make
[17:52:31]: sure your project is set up correctly.
[17:52:31]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[17:52:31]: the full commands printed out in yellow in the above log.
[17:52:31]: Make sure to inspect the output above, as usually you'll find more error information there
[17:52:31]: 
[17:52:31]: Looks like no provisioning profile mapping was provided
[17:52:31]: Please check the complete output, in particular the very top
[17:52:31]: and see if you can find more information. You can also run fastlane
[17:52:31]: with the `--verbose` flag.
[17:52:31]: Alternatively you can provide the provisioning profile mapping manually
[17:52:31]: https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios release |
+------------------+-------------+
[17:52:31]: Error packaging up the application

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | build_app        | 303         |
+------+------------------+-------------+

[17:52:31]: fastlane finished with errors

[!] Error packaging up the application

**Comment by TargetNoBug** [comment]
gem source is https://gems.ruby-china.org/ that is correct  in china

**Comment by TargetNoBug** [comment]
Exit status: 70

**Comment by wanyakun** [comment]
+ 1

**Comment by wanyakun** [comment]
In my jenkins some jobs are ok, and some jobs have the error: RVM detected, forcing to use system ruby.....

**Comment by TargetNoBug** [comment]
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.91.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.3        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| json                      | 2.1.0        |
</details>

 @joshdholtz

**Comment by TargetNoBug** [comment]
@wanyakun many error in here whose commit is similar to yours

**Comment by joshdholtz** [comment]
@TargetNoBug Thanks for the env! Can you also paste all the output from the fastlane command that you were running so that I have some more information to go on?

**Comment by Wojcik** [comment]
Hey, having the same issue when trying to build from microsoft vsts server. There was no such error before migration to rvm. How can I help to find out what's wrong?

**Comment by TargetNoBug** [comment]
I find thatMy app with the full certificate is perfectly complete when fastlane is packaged 




At 2018-04-18 23:59:49, "Ant" <notifications@github.com> wrote:


Hey, having the same issue when trying to build from microsoft vsts server. There was no such error before migration to rvm. How can I help to find out what's wrong?
