### ISSUE TITLE
lane_context does not have :hash_with_strings return type so laneContext() in Swift doesn't work

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#12303]
This is not documented and may or may not be broken 🙃

**Comment by doruvil** [comment]
My fastlane env:
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

**Comment by joshdholtz** [comment]
@doruvil Are you able to send me what your `Fastfile.swift` looks like? I want to try and duplicate your situation

**Comment by doruvil** [comment]
@joshdholtz 
I have simplified the Fastfile.swift
as much as possible in order to help you detect the problem. 
[Fastfile.swift.zip](https://github.com/fastlane/fastlane/files/1937810/Fastfile.swift.zip)Please replace the:
- HockeyApp API Token
- keychain password
- project name
- Xcode scheme
- bundle id -> provisioning profile matching
