### ISSUE TITLE
Latest Testflight build number not parsed into Int...

### ISSUE THREAD

**Issue by samwarfield** [fastlane/fastlane#12319]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using the Swift tool
The latest Testflight build number feature doesn't parse the number.
Looks like the quotes are messing it up...

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[13:04:44]: fastlane detected a Gemfile in the current directory
[13:04:44]: however it seems like you don't use `bundle exec`
[13:04:44]: to launch fastlane faster, please use
[13:04:44]: 
[13:04:44]: $ bundle exec fastlane dev --capture_output
[13:04:44]: 
[13:04:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-04-16 13:04:45.00]: Checking if there are any plugins that should be loaded...
INFO [2018-04-16 13:04:45.33]: loading manifest: /Users/../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.91.0/fastlane/swift/upgrade_manifest.json
DEBUG [2018-04-16 13:04:45.42]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2018-04-16 13:04:45.42]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.13/0.9.13
DEBUG [2018-04-16 13:04:45.42]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.3/0.9.3
DEBUG [2018-04-16 13:04:45.42]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-04-16 13:04:45.42]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-04-16 13:04:45.42]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-04-16 13:04:45.42]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-04-16 13:04:45.42]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-04-16 13:04:45.43]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.3/0.9.3
DEBUG [2018-04-16 13:04:45.43]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-04-16 13:04:45.43]: Checking for new user-provided tool configuration files
INFO [2018-04-16 13:04:45.46]: FastlaneSwiftRunner project is up-to-date
DEBUG [2018-04-16 13:04:45.46]: Found changes to user's Fastfile.swift, setting re-build runner flag
DEBUG [2018-04-16 13:04:45.46]: Building FastlaneSwiftRunner
INFO [2018-04-16 13:04:45.52]: $ xcodebuild -showBuildSettings -scheme FastlaneSwiftRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
DEBUG [2018-04-16 13:04:46.58]: Parsing project file '/Users/../Development/iOSRepos/TASL/Attain/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj' to find selected provisioning profiles
DEBUG [2018-04-16 13:04:46.58]: Finding provision profiles for 'Release'
DEBUG [2018-04-16 13:04:46.60]: Merging provisioning profile mappings
DEBUG [2018-04-16 13:04:46.60]: -------------------------------------
DEBUG [2018-04-16 13:04:46.60]: Primary provisioning profile mapping:
DEBUG [2018-04-16 13:04:46.60]: {}
DEBUG [2018-04-16 13:04:46.60]: Secondary provisioning profile mapping:
DEBUG [2018-04-16 13:04:46.60]: {}
DEBUG [2018-04-16 13:04:46.60]: Resulting in the following mapping:
DEBUG [2018-04-16 13:04:46.60]: {}
INFO [2018-04-16 13:04:46.71]: $ set -o pipefail && xcodebuild -scheme FastlaneSwiftRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/../Library/Logs/gym/App-FastlaneSwiftRunner.log | xcpretty
INFO [2018-04-16 13:04:47.35]: ▸ Building FastlaneSwiftRunner/FastlaneRunner [Debug]
INFO [2018-04-16 13:04:47.35]: ▸ Check Dependencies
INFO [2018-04-16 13:04:47.42]: ▸ Compiling Fastfile.swift
INFO [2018-04-16 13:04:48.00]: ▸ Linking FastlaneRunner
INFO [2018-04-16 13:04:49.06]: ▸ Running script 'Run Script'
INFO [2018-04-16 13:04:49.09]: ▸ Signing /Users/../Library/Developer/Xcode/DerivedData/FastlaneSwiftRunner-aqhkrbjohpiswfehceltbjbcbhdc/Build/Products/Debug/FastlaneRunner
INFO [2018-04-16 13:04:49.20]: ▸ Build Succeeded
DEBUG [2018-04-16 13:04:49.23]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2018-04-16 13:04:49.48]: $ ./fastlane/FastlaneRunner lane dev logMode verbose > /dev/null
DEBUG [2018-04-16 13:04:49.51]: Client connected
DEBUG [2018-04-16 13:04:49.51]: received command:#<Fastlane::ActionCommand:0x007ff69a15c7d0 @method_name="latest_testflight_build_number", @class_name=nil, @command_id="", @args=[named argument: live, value: false, type: , named argument: app_identifier, value: ***, type: , named argument: username, value: ***, type: , named argument: platform, value: ios, type: , named argument: initial_build_number, value: 1, type: , named argument: team_id, value: ***, type: ]>
INFO [2018-04-16 13:04:49.52]: --------------------------------------------
INFO [2018-04-16 13:04:49.52]: --- Step: latest_testflight_build_number ---
INFO [2018-04-16 13:04:49.52]: --------------------------------------------
INFO [2018-04-16 13:04:49.67]: Login to iTunes Connect (***)
INFO [2018-04-16 13:04:53.10]: Login successful
INFO [2018-04-16 13:05:06.37]: Fetching the latest build number for version 1.0
INFO [2018-04-16 13:05:14.75]: Latest upload for version 1.0 is build: 139
DEBUG [2018-04-16 13:05:14.75]: sending {"payload":{"status":"ready_for_next","return_object":"\"139\"","closure_argument_value":""}}
DEBUG [2018-04-16 13:05:14.75]: received command:#<Fastlane::ActionCommand:0x007ff69a09d970 @method_name="println", @class_name=nil, @command_id="", @args=[named argument: message, value: New build number: 1, type: ]>
INFO [2018-04-16 13:05:14.75]: New build number: 1
DEBUG [2018-04-16 13:05:14.75]: return_value_type is nil value: 
DEBUG [2018-04-16 13:05:14.75]: sending {"payload":{"status":"ready_for_next","return_object":"","closure_argument_value":""}}
DEBUG [2018-04-16 13:05:14.76]: received done signal shutting down
INFO [2018-04-16 13:05:14.78]: fastlane.tools finished successfully 🎉
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile { 
	func devLane() {
        desc("Push a new development build to TestFlight")
        let testflightBuildNumber = latestTestflightBuildNumber(live: false,
                                                                appIdentifier: "com.tasl.attain-development",
                                                                username: appleID,
                                                                teamId: itcTeam)
        let newBuildNumber = testflightBuildNumber + 1
        println(message: "New build number: \(newBuildNumber)")
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.91.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-04-16**
</details>
</pre>
</details>

**Comment by joshdholtz** [comment]
@samwarfield Will look into for you!
