### ISSUE TITLE
Can't upload to play store using internal track

### ISSUE THREAD

**Issue by alexmngn** [fastlane/fastlane#12317]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to use the `internal` track of the method `upload_to_play_store` as per documentation:

> The track of the application to use: production, beta, alpha, internal, rollout
> https://docs.fastlane.tools/actions/upload_to_play_store/

However when I use this track, I get the following error:
```
Error setting value 'internal' for option 'track'
You passed invalid parameters to 'upload_to_play_store'.
Check out the error below and available options by running `fastlane action upload_to_play_store`
```

When I run `fastlane action upload_to_play_store` it also output I can use the `internal` track.

This is how I run the method:

```
    upload_to_play_store(
      json_key: "#{Dir.pwd}/json_key.json",
      track: "internal",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
```

Looks like a bug to me.

### Environment

Linux + Docker

**Comment by joshdholtz** [comment]
@alexmngn I just successfully upload to "internal" track with `2.92.1` 🤔

What version of _fastlane_ are you running? Can you run `fastlane env` and paste the response here? Can you also paste your whole console to output as well if you don't mind so I can see a stacktrace?

**Comment by alexmngn** [comment]
Found out there were 2 versions of fastlane with 2 ruby, a clean up and an upgrade and everything works
