### ISSUE TITLE
HardwareKeyboardFix.patch no-longer work with Xcode 9.3

### ISSUE THREAD

**Issue by onato** [fastlane/fastlane#12325]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The "Connect Hardware Keyboard" setting has changed. It is can no-longer be set with `defaults write com.apple.iphonesimulator ConnectHardwareKeyboard…` which breaks [Fixes::HardwareKeyboardFix.patch](https://github.com/fastlane/fastlane/blob/fc5e26692b7bb4ab9522b7f058c0cd7d230737d1/snapshot/lib/snapshot/fixes/hardware_keyboard_fix.rb#L12). According to a [stackoverflow answer](https://stackoverflow.com/a/47820883/215748) it now looks more like `Set :DevicePreferences:$UDID:ConnectHardwareKeyboard 
false`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane run_snapshot --capture_output
[✔] 🚀
[16:00:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-04-17 16:00:33.46]: Checking if there are any plugins that should be loaded...
INFO [2018-04-17 16:00:33.66]: ----------------------------------------
INFO [2018-04-17 16:00:33.66]: --- Step: Verifying fastlane version ---
INFO [2018-04-17 16:00:33.66]: ----------------------------------------
INFO [2018-04-17 16:00:33.66]: Your fastlane version 2.92.0 matches the minimum requirement of 2.12.0  ✅
INFO [2018-04-17 16:00:33.66]: ------------------------------
INFO [2018-04-17 16:00:33.66]: --- Step: default_platform ---
INFO [2018-04-17 16:00:33.66]: ------------------------------
INFO [2018-04-17 16:00:33.67]: Driving the lane 'ios run_snapshot' 🚀
INFO [2018-04-17 16:00:33.67]: ----------------------
INFO [2018-04-17 16:00:33.67]: --- Step: snapshot ---
INFO [2018-04-17 16:00:33.67]: ----------------------
INFO [2018-04-17 16:00:34.45]: Successfully loaded '/Users/stephen/Documents/Code/Intellum/tribe-ios/fastlane/Snapfile' 📄
DEBUG [2018-04-17 16:00:34.46]: Fetching available simulator devices
INFO [2018-04-17 16:00:34.88]: $ xcodebuild -showBuildSettings -workspace ./Tribe.xcworkspace -scheme TribeUITests
--- xcodebuild: WARNING: Unable to open project file '/Users/stephen/Documents/Code/Intellum/tribe-ios/Playground.playground' in workspace './Tribe.xcworkspace'.
WARN [2018-04-17 16:00:37.88]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
--- xcodebuild: WARNING: Unable to open project file '/Users/stephen/Documents/Code/Intellum/tribe-ios/Playground.playground' in workspace './Tribe.xcworkspace'.
DEBUG [2018-04-17 16:00:40.59]: Fetching available simulator devices
DEBUG [2018-04-17 16:00:40.87]: Found 45 simulators.
DEBUG [2018-04-17 16:00:40.87]: Fetching available simulator devices
DEBUG [2018-04-17 16:00:41.15]: Checking that helper files contain SnapshotHelperVersion [1.10]
WARN [2018-04-17 16:00:41.38]: Clearing previously generated screenshots
INFO [2018-04-17 16:00:41.38]: Building and running project - this might take some time...
DEBUG [2018-04-17 16:00:41.39]: Fetching available simulator devices
INFO [2018-04-17 16:00:42.12]: Patching simulators '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
DEBUG [2018-04-17 16:00:42.12]: Fetching available simulator devices
INFO [2018-04-17 16:00:42.41]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-4s' '1.0'
INFO [2018-04-17 16:00:42.57]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-5' '1.0'
INFO [2018-04-17 16:00:42.70]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-5s' '1.0'
INFO [2018-04-17 16:00:42.82]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6' '1.0'
INFO [2018-04-17 16:00:42.94]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus' '1.0'
INFO [2018-04-17 16:00:43.06]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6s' '1.0'
INFO [2018-04-17 16:00:43.17]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus' '1.0'
INFO [2018-04-17 16:00:43.29]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-2' '1.0'
INFO [2018-04-17 16:00:43.41]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Retina' '1.0'
INFO [2018-04-17 16:00:43.53]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Air' '1.0'
INFO [2018-04-17 16:00:43.64]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Air-2' '1.0'
INFO [2018-04-17 16:00:43.76]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-5' '1.0'
INFO [2018-04-17 16:00:43.88]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-5s' '1.0'
INFO [2018-04-17 16:00:44.00]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6' '1.0'
INFO [2018-04-17 16:00:44.12]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus' '1.0'
INFO [2018-04-17 16:00:44.24]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6s' '1.0'
INFO [2018-04-17 16:00:44.35]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus' '1.0'
INFO [2018-04-17 16:00:44.47]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-7' '1.0'
INFO [2018-04-17 16:00:44.58]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus' '1.0'
INFO [2018-04-17 16:00:44.70]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-SE' '1.0'
INFO [2018-04-17 16:00:44.81]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Air' '1.0'
INFO [2018-04-17 16:00:44.93]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Air-2' '1.0'
INFO [2018-04-17 16:00:45.05]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-(5th-generation)' '1.0'
INFO [2018-04-17 16:00:45.16]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(9.7-inch)' '1.0'
INFO [2018-04-17 16:00:45.28]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(12.9-inch)' '1.0'
INFO [2018-04-17 16:00:45.39]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(12.9-inch)-(2nd-generation)' '1.0'
INFO [2018-04-17 16:00:45.51]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(10.5-inch)' '1.0'
INFO [2018-04-17 16:00:45.63]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-5s' '1.0'
INFO [2018-04-17 16:00:45.75]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6' '1.0'
INFO [2018-04-17 16:00:45.87]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus' '1.0'
INFO [2018-04-17 16:00:45.98]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6s' '1.0'
INFO [2018-04-17 16:00:46.11]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus' '1.0'
INFO [2018-04-17 16:00:46.22]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-7' '1.0'
INFO [2018-04-17 16:00:46.34]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus' '1.0'
INFO [2018-04-17 16:00:46.46]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-8' '1.0'
INFO [2018-04-17 16:00:46.57]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus' '1.0'
INFO [2018-04-17 16:00:46.69]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-SE' '1.0'
INFO [2018-04-17 16:00:46.81]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-X' '1.0'
INFO [2018-04-17 16:00:46.94]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Air' '1.0'
INFO [2018-04-17 16:00:47.05]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Air-2' '1.0'
INFO [2018-04-17 16:00:47.17]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-(5th-generation)' '1.0'
INFO [2018-04-17 16:00:47.28]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(9.7-inch)' '1.0'
INFO [2018-04-17 16:00:47.39]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(12.9-inch)' '1.0'
INFO [2018-04-17 16:00:47.51]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(12.9-inch)-(2nd-generation)' '1.0'
INFO [2018-04-17 16:00:47.62]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro-(10.5-inch)' '1.0'
INFO [2018-04-17 16:00:47.75]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-TV' '1.0'
INFO [2018-04-17 16:00:47.87]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K' '1.0'
INFO [2018-04-17 16:00:47.99]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-(at-1080p)' '1.0'
INFO [2018-04-17 16:00:48.11]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-Watch---38mm' '1.0'
INFO [2018-04-17 16:00:48.24]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-Watch---42mm' '1.0'
INFO [2018-04-17 16:00:48.35]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2---38mm' '1.0'
INFO [2018-04-17 16:00:48.48]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2---42mm' '1.0'
INFO [2018-04-17 16:00:48.59]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3---38mm' '1.0'
INFO [2018-04-17 16:00:48.70]: $ defaults write '/Users/stephen/Library/Preferences/com.apple.iphonesimulator.plist' 'SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3---42mm' '1.0'
DEBUG [2018-04-17 16:00:48.82]: Patching simulator to work with secure text fields
INFO [2018-04-17 16:00:48.82]: $ defaults write com.apple.iphonesimulator ConnectHardwareKeyboard 0
DEBUG [2018-04-17 16:00:48.93]: Erasing iPhone SE...
DEBUG [2018-04-17 16:00:48.93]: Fetching available simulator devices
WARN [2018-04-17 16:00:49.21]: Erasing iPhone SE...
DEBUG [2018-04-17 16:00:50.35]: Adding videos to iPhone SE...
DEBUG [2018-04-17 16:00:50.35]: Fetching available simulator devices
INFO [2018-04-17 16:00:50.63]: Launch Simulator iPhone SE
INFO [2018-04-17 16:00:50.63]: $ xcrun instruments -w F03917FD-9D7F-48A8-948F-D730EB88027D &> /dev/null
INFO [2018-04-17 16:00:53.60]: Adding '../test-data/Hops.mp4'
INFO [2018-04-17 16:00:53.60]: $ xcrun simctl addvideo F03917FD-9D7F-48A8-948F-D730EB88027D ../test-data/Hops.mp4 &> /dev/null
DEBUG [2018-04-17 16:01:02.44]: Fetching available simulator devices
WARN [2018-04-17 16:01:02.83]: Running snapshot on: iPhone SE
INFO [2018-04-17 16:01:02.83]: $ set -o pipefail && xcodebuild -workspace ./Tribe.xcworkspace -scheme TribeUITests -derivedDataPath '/var/folders/x1/1794tkfs2fsbz0xvb84jnym00000gn/T/snapshot_derived20180417-27538-1s2cw5h' -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.3' FASTLANE_SNAPSHOT=YES build test | tee /Users/stephen/Library/Logs/snapshot/Tribe\ Social-TribeUITests.log | xcpretty
INFO [2018-04-17 16:01:02.83]: ▸ Loading...
INFO [2018-04-17 16:01:05.02]: ▸ --- xcodebuild: WARNING: Unable to open project file '/Users/stephen/Documents/Code/Intellum/tribe-ios/Playground.playground' in workspace './Tribe.xcworkspace'.
INFO [2018-04-17 16:01:10.33]: ▸ Building Pods/FormatterKit [Debug]
INFO [2018-04-17 16:01:10.33]: ▸ Check Dependencies
INFO [2018-04-17 16:01:10.49]: ▸ Processing Info.plist
INFO [2018-04-17 16:01:10.61]: ▸ Compiling TTTColorFormatter.m
…
INFO [2018-04-17 16:14:04.27]: Generating HTML Report
INFO [2018-04-17 16:14:04.29]: Successfully created HTML file with an overview of all the screenshots: '/Users/stephen/Documents/Code/Intellum/tribe-ios/screenshots/screenshots.html'
INFO [2018-04-17 16:14:09.73]: Successfully generated documentation at path '/Users/stephen/Documents/Code/Intellum/tribe-ios/fastlane/README.md'
INFO [2018-04-17 16:14:09.75]: fastlane.tools just saved you 14 minutes! 🎉
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.2                           |
| Installation Source         | ~/.gem/ruby/2.3.3/bin/fastlane              |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.3/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_NZ.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end
  
  
  desc "Deploy a new version to the App Store"
  lane :run_snapshot do
    snapshot
  end
  desc "Deploy a new version to the App Store"
  lane :release do

    inc
    gym(scheme: "Tribe Social", 
        configuration: "Release", 
        export_method: "app-store",
        export_options: {
          provisioningProfiles: { 
            "com.intellum.tribe" => "match AppStore com.intellum.tribe"
          }
        }
    )
    upload_release 
    staging
  end

  desc "Upload the release build"
  lane :upload_release do

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    deliver(force: true, 
            release_notes: changelog_from_git_commits, 
            app_identifier: "com.intellum.tribe", 
            skip_metadata: true,
            skip_screenshots: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :staging do

    #inc
    gym(scheme: "Tribe Social", 
        configuration: "Staging", 
        export_method: "app-store",
        export_options: {
          provisioningProfiles: { 
            "com.intellum.tribe" => "match AppStore com.intellum.tribe.staging"
          }
        }

    )

    upload_staging
  end

  desc "Upload the staging build"
  lane :upload_staging do

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    deliver(force: true, 
            release_notes: changelog_from_git_commits, 
            app_identifier: "com.intellum.tribe.staging", 
            skip_metadata: true,
            skip_screenshots: true
    )
  end

  lane :profiles do
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe")
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe.ShareExtension")
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe.NotificationExtension")
    match(git_url: "https://github.com/intellum/certificates",
          type: "appstore",
          app_identifier: "com.intellum.tribe.NotificationContent", 
          clone_branch_directly: true,
          shallow_clone: true,
          verbose: true
    )

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "adhoc",
          #app_identifier: "com.intellum.tribe")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "adhoc",
          #app_identifier: "com.intellum.tribe.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "adhoc",
          #app_identifier: "com.intellum.tribe.NotificationExtension")
       

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging.NotificationExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "appstore",
          #app_identifier: "com.intellum.tribe.staging.NotificationContent")

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging.NotificationExtension")

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.staging.NotificationExtension")

    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug.ShareExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug.NotificationExtension")
    #match(git_url: "https://github.com/intellum/certificates",
          #type: "development",
          #app_identifier: "com.intellum.tribe.debug.NotificationContent", 
          #clone_branch_directly: true,
          #shallow_clone: true,
          #verbose: true
    #)

  end

  desc "Increment the build number"
  lane :inc do
    increment_build_number(
      xcodeproj: 'TribeSocial/Tribe.xcodeproj',
      build_number: "#{get_build_number(xcodeproj: 'TribeSocial/Tribe.xcodeproj').to_i + 1}"
    )
  end

  desc "Download DSYM files from iTunesConnect and upload them to Crashlytics"
  lane :dsyms do
    download_dsyms(version: "latest")                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics                      # Upload them to Crashlytics
    clean_build_artifacts                              # Delete the local dSYM files
  end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.intellum.tribe" # The bundle identifier of your app
apple_id "swilliams@intellum.com" # Your Apple email address

team_id "JYANFLU7NT"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.3        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.8        |
| io-console                | 0.4.5        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.2.1        |
| CFPropertyList            | 2.3.4        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| bundler                   | 1.15.0       |
</details>

*generated on:* **2018-04-17**
</details></pre>
</details>

**Comment by onato** [comment]
Still not working.

**Comment by onato** [comment]
This is still an issue.

**Comment by ppamorim** [comment]
Is this fixed?
