### ISSUE TITLE
Fastlane fails with "duplicated argument name"

### ISSUE THREAD

**Issue by cpk1** [fastlane/fastlane#12322]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I use Fastlane with Ruby 2.0.0 (the Ruby shipped with Mac OS Sierra)
Starting with 2.90.0 I am getting the following for a few files:

"SyntaxError: /Users/github/fastlane/spaceship/lib/spaceship/portal/ui/select_team.rb:50: duplicated argument name
...ct_team(team_id: team_id = nil, team_name: team_name = nil)"

I think this is failing because there were some changes to how Ruby handles keyword arguments in both 2.0.0 and 2.1.X, to check this I've confirmed that I don't get this error on 2.1.1 and 2.4.1.
I tried to find somewhere in the docs that stated a min ruby version that is supported, however I only saw a brief mention here (https://docs.fastlane.tools/best-practices/continuous-integration/#ruby-environment) that says the Ruby that comes with the Mac OS is OK, however there is no min Mac OS defined that I could find, this is an important distinction as I believe High Sierra ships with 2.3.3, so if the min OSX is High Sierra this is not a bug and just the docs need to be updated to better describe the minimum requirements.

Going through and changing all instances of method definitions that had "team_id: team_id = nil, team_name: team_name = nil" to "team_id: nil, team_name: nil" resolves this for me, and appears to work in the limited testing I've done so far, however I'm not sure if there was some needed behavior by using "team_id: team_id = nil, team_name: team_name = nil".

##### Complete output when running fastlane, including the stack trace and command used

<details>
SyntaxError: /Users/github/fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb:62: duplicated argument name
...ct_team(team_id: team_id = nil, team_name: team_name = nil)
...                               ^
/Users/github/fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb:62: duplicated argument name
  /Users/github/fastlane/spaceship/lib/spaceship/test_flight/base.rb:2:in `require_relative'
  /Users/github/fastlane/spaceship/lib/spaceship/test_flight/base.rb:2:in `<top (required)>'
  /Users/github/fastlane/spaceship/lib/spaceship/test_flight/build.rb:3:in `require_relative'
  /Users/github/fastlane/spaceship/lib/spaceship/test_flight/build.rb:3:in `<top (required)>'
  /Users/github/fastlane/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `require'
  /Users/github/fastlane/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `<top (required)>'
  /Users/github/fastlane/fastlane_core/lib/fastlane_core.rb:29:in `require_relative'
  /Users/github/fastlane/fastlane_core/lib/fastlane_core.rb:29:in `<top (required)>'
  /Users/github/fastlane/fastlane/lib/fastlane.rb:1:in `require'
  /Users/github/fastlane/fastlane/lib/fastlane.rb:1:in `<top (required)>'
  /Users/github/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:37:in `require'
  /Users/github/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:37:in `take_off'
  /Users/github/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/github/zynga/UniversalFastlane/vendor/bundle/ruby/2.0.0/bin/fastlane:23:in `load'
  /Users/github/zynga/UniversalFastlane/vendor/bundle/ruby/2.0.0/bin/fastlane:23:in `<top (required)>'
</details>

### Environment

<details>
  ### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.0.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane    |
| Host                        | Mac OS X 10.12.6 (16G1314)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.0.0-p648/lib           |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

</details>

**Comment by joshdholtz** [comment]
@cpk1 Thanks for the report! Will look into 👀
