### ISSUE TITLE
download_dsyms fails when there are builds that were marked as invalidBinary

### ISSUE THREAD

**Issue by tristandl** [fastlane/fastlane#12332]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have some invalid binaries in iTunes Connect which is preventing me from downloading them, which causes fastlane to fail, which is failing builds in CI. However, the other dSYMs are downloaded successfully, and that's all that is required.

To workaround this, I'll have to delete the builds that are invalid, and the it should be ok, but it would be preferable if Fastlane didn't fail when it encounters an invalid binary. There maybe other cases where we get the `ITC.response.error.BUILD_NOT_FOUND` exception but it is a real problem, so it might need to look at the processing_state and ignore just `invalidBinary`

We tried working around this using the version or build number flags to specify just the build we uploaded, but iTunes doesn't seem to have it available immediately (despite us waiting for processing to complete during the upload step). That's a separate issue though I imagine.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[10:17:36]: ------------------------------
[10:17:36]: --- Step: default_platform ---
[10:17:36]: ------------------------------
[10:17:36]: Driving the lane 'ios test_dsyms' 🚀
[10:17:36]: ----------------------------
[10:17:36]: --- Step: download_dsyms ---
[10:17:36]: ----------------------------
[10:17:36]: Login to iTunes Connect (XXXX@XXXXX)
[10:17:39]: Login successful
[10:17:39]: Looking for dSYM files for XXXXXXXXXXXX
[10:17:43]: 🔑  Successfully downloaded dSYM file for 1.0 - 70 to 'XXXXXXXXXXXX-1.0-70.dSYM.zip'
[10:17:45]: 🔑  Successfully downloaded dSYM file for 1.0 - 77 to 'XXXXXXXXXXXX-1.0-77.dSYM.zip'
[10:17:51]: 🔑  Successfully downloaded dSYM file for 1.0 - 101 to 'XXXXXXXXXXXX-1.0-101.dSYM.zip'
[10:17:53]: 🔑  Successfully downloaded dSYM file for 1.0 - 66 to 'XXXXXXXXXXXX-1.0-66.dSYM.zip'
[10:17:55]: 🔑  Successfully downloaded dSYM file for 1.0 - 68 to 'XXXXXXXXXXXX-1.0-68.dSYM.zip'
[10:17:58]: 🔑  Successfully downloaded dSYM file for 1.0 - 91 to 'XXXXXXXXXXXX-1.0-91.dSYM.zip'
[10:17:59]: 🔑  Successfully downloaded dSYM file for 1.0 - 76 to 'XXXXXXXXXXXX-1.0-76.dSYM.zip'
[10:18:01]: 🔑  Successfully downloaded dSYM file for 1.0 - 47 to 'XXXXXXXXXXXX-1.0-47.dSYM.zip'
[10:18:01]: Error accessing dSYM file for build

<Spaceship::Tunes::Build 
	apple_id="XXXXXX", 
	build_train=nil, 
	id=29539244, 
	valid=nil, 
	build_version="38", 
	train_version="1.0", 
	processing=true, 
	processing_state="invalidBinary", 
	upload_date=1523448158000, 
	icon_url="https://is3-ssl.mzstatic.com/image/thumb/Newsstand128/v4/66/10/fe/6610fef0-a064-70cc-b2cc-629b2d698361/Icon-76@2x.png.png/150x150bb-80.png", 
	app_name="XXXXXXX", 
	platform="ios", 
	internal_expiry_date=0, 
	external_expiry_date=0, 
	watch_kit_enabled=nil, 
	ready_to_install=nil, 
	install_count=nil, 
	internal_install_count=nil, 
	external_install_count=nil, 
	session_count=nil, 
	crash_count=nil>

Exception: Unexpected Error
[10:18:01]: No dSYM URL for 38 (1.0)
[10:18:03]: 🔑  Successfully downloaded dSYM file for 1.0 - 50 to 'XXXXXXXXXXXX-1.0-50.dSYM.zip'
[10:18:24]: 🔑  Successfully downloaded dSYM file for 1.0 - 43 to 'XXXXXXXXXXXX-1.0-43.dSYM.zip'
[10:18:26]: 🔑  Successfully downloaded dSYM file for 1.0 - 53 to 'XXXXXXXXXXXX-1.0-53.dSYM.zip'
[10:18:28]: 🔑  Successfully downloaded dSYM file for 1.0 - 59 to 'XXXXXXXXXXXX-1.0-59.dSYM.zip'
[10:18:29]: 🔑  Successfully downloaded dSYM file for 1.0 - 83 to 'XXXXXXXXXXXX-1.0-83.dSYM.zip'
[10:18:30]: Error accessing dSYM file for build

<Spaceship::Tunes::Build 
	apple_id="XXXXX", 
	build_train=nil, 
	id=0, 
	valid=nil, 
	build_version="33", 
	train_version="1.0", 
	processing=true, 
	processing_state="invalidBinary", 
	upload_date=1523433807000, 
	icon_url=nil, 
	app_name=nil, 
	platform="ios", 
	internal_expiry_date=0, 
	external_expiry_date=0, 
	watch_kit_enabled=nil, 
	ready_to_install=nil, 
	install_count=nil, 
	internal_install_count=nil, 
	external_install_count=nil, 
	session_count=nil, 
	crash_count=nil>

Exception: ITC.response.error.BUILD_NOT_FOUND
[10:18:30]: No dSYM URL for 33 (1.0)
[10:18:30]: Error accessing dSYM file for build

<Spaceship::Tunes::Build 
	apple_id="XXXXX", 
	build_train=nil, 
	id=0, 
	valid=nil, 
	build_version="36", 
	train_version="1.0", 
	processing=true, 
	processing_state="invalidBinary", 
	upload_date=1523438683000, 
	icon_url=nil, 
	app_name=nil, 
	platform="ios", 
	internal_expiry_date=0, 
	external_expiry_date=0, 
	watch_kit_enabled=nil, 
	ready_to_install=nil, 
	install_count=nil, 
	internal_install_count=nil, 
	external_install_count=nil, 
	session_count=nil, 
	crash_count=nil>

Exception: ITC.response.error.BUILD_NOT_FOUND
[10:18:30]: No dSYM URL for 36 (1.0)
[10:18:31]: Error accessing dSYM file for build

<Spaceship::Tunes::Build 
	apple_id="XXXXX", 
	build_train=nil, 
	id=0, 
	valid=nil, 
	build_version="35", 
	train_version="1.0", 
	processing=true, 
	processing_state="invalidBinary", 
	upload_date=1523434512000, 
	icon_url=nil, 
	app_name=nil, 
	platform="ios", 
	internal_expiry_date=0, 
	external_expiry_date=0, 
	watch_kit_enabled=nil, 
	ready_to_install=nil, 
	install_count=nil, 
	internal_install_count=nil, 
	external_install_count=nil, 
	session_count=nil, 
	crash_count=nil>

Exception: ITC.response.error.BUILD_NOT_FOUND
[10:18:31]: No dSYM URL for 35 (1.0)

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | download_dsyms   | 54          |
+------+------------------+-------------+

[10:18:31]: fastlane.tools finished successfully 🎉</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.4                                         |
| Ruby                        | 2.4.2                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.10.1                              |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane             |
| Host                        | Mac OS X 10.13.4 (17E199)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
  before_all do
    if ENV["CIRCLECI"].to_s == "true"
      setup_circle_ci
    end
  end
 
  lane :test_dsyms do
    download_dsyms
  end 
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS
app_identifier "XXXXXXXXXXXX"  	# The bundle identifier
apple_id "XXXXXX"            # iTunes Connect user name
team_id "XXXXXX"                    # The Team ID as displayed in the Member Center - Login and click MEMBERSHIP in the sidebar
itc_team_id "XXXXXX"           # itc_team_id can ONLY BE FOUND when CircleCI fails to login to iTunes Connect the first time

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clubhouse_ruby            | 0.4.0        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| cocoapods                 | 1.5.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.2        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-04-18**
</details></pre>
</details>

**Comment by tristandl** [comment]
oh, and --capture_output didn't work - not sure why (I got no output), so i copied and pasted the output manually. hope that's ok

**Comment by joshdholtz** [comment]
@tristandl Heyyyyy 👋 So good news is you did download some dSYMs 😊 Bad news is there isn't anything we can do about those `Error accessing dSYM file for build` because they builds were invalid binaries. We print those out for you so we know you we tried but couldn't do it 🙃

**Comment by tristandl** [comment]
sorry, my bad - I thought these errors were killing my build, but it was actually the next step where i had a problem with my crashlytics key not being read from the info.plist correctly 😬

at least i learnt a bit about fastlane today! looks great!

**Comment by joshdholtz** [comment]
@tristandl Not a problem! It is a little be spooky at first - I am not afraid to admit that 😇 Happy fastlaning 🚀
