### ISSUE TITLE
Some usages of list-keychains clobber the list of keychains

### ISSUE THREAD

**Issue by macdoum1** [fastlane/fastlane#12337]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

[Resign](https://github.com/fastlane/fastlane/blob/5ad02db331fc58b47b05b3e95a455ebb4c41c708/sigh/lib/assets/resign.sh#L296) and [replace_keychain_in_search_list](https://github.com/fastlane/fastlane/blob/7a87b8ad761dc739be941611721e7616e2b66824/fastlane/lib/fastlane/actions/unlock_keychain.rb#L47) call `security list-keychains -s KEYCHAIN` which removes all keychains from the list of keychains except the keychain passed as a parameter.

[add_keychain_to_search_list](https://github.com/fastlane/fastlane/blob/7a87b8ad761dc739be941611721e7616e2b66824/fastlane/lib/fastlane/actions/unlock_keychain.rb#L34-L40) correctly appends the keychain passed as parameter onto the existing list of keychains.

This was causing some issues with our deployment machines since we have some keychains that need to stick around outside of fastlane

**Comment by joshdholtz** [comment]
@macdoum1 This is an interesting find 🤔 I will volunteer my keychains as tribute to duplicate and fix this issue

**Comment by macdoum1** [comment]
@joshdholtz here is an example of the behavior on macOS 10.12.6
```
mmacdougall: Desktop
$ security list-keychains
    "/Users/mmacdougall/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
mmacdougall: Desktop
$ security create-keychain
keychain to create: newkeychain
password for new keychain:
retype password for new keychain:
mmacdougall: Desktop
$ security list-keychains
    "/Users/mmacdougall/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
mmacdougall: Desktop
$ security list-keychains -s newkeychain
mmacdougall: Desktop
$ security list-keychains
    "/Users/mmacdougall/Library/Keychains/newkeychain-db"
    "/Library/Keychains/System.keychain"
```

As you can see my `/Users/mmacdougall/Library/Keychains/login.keychain-db` keychain gets clobber. It appears that the system keychain is immune to this behavior
