### ISSUE TITLE
Create OS X .pkg file with "gym" for "deliver"

### ISSUE THREAD

**Issue by mkeiser** [fastlane/fastlane#1234]
So I saw that deliver recent learned to upload .pkg files to the Mac App Store. But is there currently a way to produce a .pkg file with gym, or do we have to use xcodebuild for this?

**Comment by KrauseFx** [comment]
Yeah, that should work with `gym`

**Comment by mkeiser** [comment]
But how so? When doing

`gym(scheme: "scheme", clean: true, output_directory: dir, export_method: "package")`

I only see the .app and dSYM.zip files in the output directory.

Also, a casual look at the file gym/lib/gym/runner.rb seems to confirm that the "package" step is skipped for mac apps (please excuse me if I'm interpreting this wrong):

```
      if Gym.project.ios? || Gym.project.tvos?
        package_app
        fix_package
        compress_and_move_dsym
        move_ipa
      elsif Gym.project.mac?
        compress_and_move_dsym
        move_mac_app
      end

```

**Comment by vpolouchkine** [comment]
Are you still running into this? Happy to look into it.

**Comment by mkeiser** [comment]
Yes I do, I just tried with the latest version of fasten/gym.

	+----------------------+--------------------------+
	|              Summary for gym 1.6.1              |
	+----------------------+--------------------------+
	| workspace            | ./skilRoute.xcworkspace  |
	| scheme               | playerOSX                |
	| clean                | true                     |
	| output_directory     | fastlane/ipas/playerOSX/ |
	| output_name          | playerOSX                |
	| silent               | false                    |
	| use_legacy_build_api | false                    |
	| export_method        | package                  |
	| buildlog_path        | ~/Library/Logs/gym       |
	| destination          | generic/platform=OS X    |
	+----------------------+--------------------------+

It results in an .app file and a .dSYM.zip file in the output_directory. I was expecting a .pkg file.

**Comment by ohwutup** [comment]
Hey @mkeiser would you mind sharing the entire output from your terminal? It should be printing out the `xcodebuild` command that it is using under the hood.

**Comment by mkeiser** [comment]
Attached:
[fastlaneBuildOutput.txt](https://github.com/fastlane/fastlane/files/148921/fastlaneBuildOutput.txt)

**Comment by vpolouchkine** [comment]
@mkeiser Are you still running into this?

**Comment by mkeiser** [comment]
Yes. Does that mean it works for other people?

**Comment by TKBurner** [comment]
Thanks @mkeiser! I'm going to look into this a little bit more and follow up with you 👍

**Comment by nerd0geek1** [comment]
@mkeiser 
No, I tried to generate .pkg file with gym 1.6.2, but it won't generate.
I also try to solve this problem with you!

**Comment by nerd0geek1** [comment]
I wrote some code as below and confirmed that works fine.
I'll refactor it and submit pull request within 2days.

```
if Gym.project.ios? || Gym.project.tvos?
  package_app
  fix_package
  compress_and_move_dsym
  move_ipa
elsif Gym.project.mac?
  compress_and_move_dsym
  app_path = copy_mac_app.shellescape
  if Gym.config[:export_method] == "package"
    make_pkg_command = "productbuild --component #{app_path} /Applications Foo.pkg"
    system make_pkg_command
  end
end
```

Thanks @mkeiser !!

**Comment by KrauseFx** [comment]
Awesome, thanks @nerd0geek1 👍
