### ISSUE TITLE
Scan/run_tests will succeed if build fails

### ISSUE THREAD

**Issue by mbogh** [fastlane/fastlane#12343]
🔑 

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We are using `danger` and the `danger-junit` plugin to report test result back to the Pull Request as comments. So I set up the following in our `Fastfile`:
```
desc 'Run all the enabled tests'
lane :test do |options|
  run_tests(
    scheme: "Some Project",
    device: 'iPhone 8',
    code_coverage: true,
    fail_build: false
  )
end
```

Everything was perfect until someone broke the tests so they could no longer compile but Fastlane kept ending in `fastlane.tools finished successfully 🎉`.

If I change `fail_build` to `true` then the CI job will fail on compile errors but there will be nothing for `danger` to report on if a test fail since it will also fail the CI job.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
DEBUG [2018-04-19 20:37:45.07]: Checking if there are any plugins that should be loaded...
DEBUG [2018-04-19 20:37:45.07]: Loading 'fastlane-plugin-update_project_codesigning' plugin
INFO [2018-04-19 20:37:45.07]: gem 'fastlane-plugin-update_project_codesigning' is already installed
DEBUG [2018-04-19 20:37:45.08]: Loading 'fastlane-plugin-tpa' plugin
INFO [2018-04-19 20:37:45.08]: gem 'fastlane-plugin-tpa' is already installed
DEBUG [2018-04-19 20:37:45.08]: Loading 'fastlane-plugin-prepare_build_resources' plugin
INFO [2018-04-19 20:37:45.08]: gem 'fastlane-plugin-prepare_build_resources' is already installed
DEBUG [2018-04-19 20:37:45.09]: Loading 'fastlane-plugin-versioning' plugin
INFO [2018-04-19 20:37:45.09]: gem 'fastlane-plugin-versioning' is already installed
INFO [2018-04-19 20:37:45.26]: ---------------------------
INFO [2018-04-19 20:37:45.26]: --- Step: opt_out_usage ---
INFO [2018-04-19 20:37:45.26]: ---------------------------
INFO [2018-04-19 20:37:45.26]: Disabled upload of used actions
INFO [2018-04-19 20:37:45.26]: Driving the lane 'test' 🚀
INFO [2018-04-19 20:37:45.26]: -----------------------
INFO [2018-04-19 20:37:45.26]: --- Step: xcversion ---
INFO [2018-04-19 20:37:45.26]: -----------------------
INFO [2018-04-19 20:37:45.26]: gem 'xcode-install' is already installed
DEBUG [2018-04-19 20:37:45.99]: Found Xcode version 9.3 at /Applications/Xcode-9.3.app satisfying requirement 9.3
INFO [2018-04-19 20:37:45.99]: Setting Xcode version to /Applications/Xcode-9.3.app for all build steps
INFO [2018-04-19 20:37:45.99]: -----------------------
INFO [2018-04-19 20:37:45.99]: --- Step: run_tests ---
INFO [2018-04-19 20:37:45.99]: -----------------------
INFO [2018-04-19 20:37:46.16]: $ xcodebuild -showBuildSettings -scheme Some\ Project -project ./SomeProject.xcodeproj
...
INFO [2018-04-19 20:41:23.93]: ▸ Testing failed:
INFO [2018-04-19 20:41:23.93]: ▸ Use of undeclared type 'X'
INFO [2018-04-19 20:41:23.93]: ▸ Use of undeclared type 'Y'
INFO [2018-04-19 20:41:23.93]: ▸ Use of undeclared type 'Z'
INFO [2018-04-19 20:41:23.93]: ▸ Use of undeclared type 'A'
INFO [2018-04-19 20:41:23.93]: ▸ Use of undeclared type 'A'
INFO [2018-04-19 20:41:23.93]: ▸ Use of undeclared type 'A'
INFO [2018-04-19 20:41:23.93]: ▸ Use of unresolved identifier 'X'
INFO [2018-04-19 20:41:23.93]: ▸ Use of unresolved identifier 'X'
INFO [2018-04-19 20:41:23.93]: ▸ Use of unresolved identifier 'X'
INFO [2018-04-19 20:41:23.93]: ▸ Use of unresolved identifier 'X'
INFO [2018-04-19 20:41:24.11]: ▸ ** TEST FAILED **
INFO [2018-04-19 20:41:24.11]: ▸ The following build commands failed:
INFO [2018-04-19 20:41:24.11]: ▸ CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
INFO [2018-04-19 20:41:24.12]: ▸ CompileSwift normal x86_64 /Users/.../Tests/XTests.swift
INFO [2018-04-19 20:41:24.12]: ▸ CompileSwift normal x86_64 /Users/.../Tests/B.swift
INFO [2018-04-19 20:41:24.12]: ▸ (3 failures)
...
ERROR [2018-04-19 20:41:28.19]: Exit status: 65
INFO [2018-04-19 20:41:28.41]: Successfully generated documentation at path '/Users/.../fastlane/README.md'
DEBUG [2018-04-19 20:41:28.43]: All plugins are up to date
INFO [2018-04-19 20:41:28.43]: fastlane.tools finished successfully 🎉
DEBUG [2018-04-19 20:41:28.43]: All plugins are up to date
  </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.4                                         |
| Ruby                        | 2.3.0                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.15.1 (Apple Git-101)              |
| Installation Source         | ~/.rvm/gems/ruby-head/bin/fastlane              |
| Host                        | Mac OS X 10.13.4 (17E199)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-head/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2d 9 Jul 2015                       |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.3.app/Contents/Developer/ |
| Xcode Version               | 9.3                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-tpa                        | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-prepare_build_resources    | 1.0.4   | ✅ Up-To-Date  |
| fastlane-plugin-versioning                 | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| executable-hooks                           | 1.3.2        |
| bundler-unload                             | 1.0.2        |
| rubygems-bundler                           | 1.4.4        |
| bundler                                    | 1.16.0       |
| io-console                                 | 0.4.6        |
| rake                                       | 12.3.1       |
| CFPropertyList                             | 3.0.0        |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.2        |
| atomos                                     | 0.1.2        |
| babosa                                     | 1.0.2        |
| curb                                       | 0.9.4        |
| fastimage                                  | 2.1.1        |
| colored                                    | 1.2          |
| highline                                   | 1.7.10       |
| commander-fastlane                         | 4.4.6        |
| dotenv                                     | 2.2.2        |
| emoji_regex                                | 0.1.1        |
| excon                                      | 0.62.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.15.0       |
| unf_ext                                    | 0.0.7.5      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20180417 |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.12.2       |
| gh_inspector                               | 1.1.3        |
| jwt                                        | 2.1.0        |
| little-plugger                             | 1.1.4        |
| multi_json                                 | 1.13.1       |
| logging                                    | 2.2.2        |
| memoist                                    | 0.16.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.8.1        |
| googleauth                                 | 0.6.2        |
| httpclient                                 | 2.8.3        |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| declarative                                | 0.0.10       |
| declarative-option                         | 0.1.0        |
| uber                                       | 0.1.0        |
| representable                              | 3.0.4        |
| retriable                                  | 3.1.1        |
| google-api-client                          | 0.13.6       |
| json                                       | 2.1.0        |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.4.0        |
| rubyzip                                    | 1.2.1        |
| security                                   | 0.1.3        |
| naturally                                  | 2.1.0        |
| simctl                                     | 1.6.4        |
| slack-notifier                             | 2.3.2        |
| terminal-notifier                          | 1.8.0        |
| unicode-display_width                      | 1.3.2        |
| terminal-table                             | 1.8.0        |
| tty-screen                                 | 0.6.4        |
| tty-cursor                                 | 0.5.0        |
| tty-spinner                                | 0.8.0        |
| word_wrap                                  | 1.0.0        |
| claide                                     | 1.0.2        |
| colored2                                   | 3.1.2        |
| nanaimo                                    | 0.2.5        |
| xcodeproj                                  | 1.5.7        |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.2.8        |
| xcpretty-travis-formatter                  | 1.0.0        |
| badge                                      | 0.9.1        |
| cork                                       | 0.3.0        |
| nap                                        | 1.1.0        |
| open4                                      | 1.3.4        |
| claide-plugins                             | 0.9.2        |
| faraday-http-cache                         | 1.3.1        |
| git                                        | 1.3.0        |
| kramdown                                   | 1.16.2       |
| no_proxy_fix                               | 0.1.2        |
| sawyer                                     | 0.8.1        |
| octokit                                    | 4.8.0        |
| danger                                     | 5.5.12       |
| httparty                                   | 0.16.2       |
| gitlab                                     | 4.3.0        |
| danger-gitlab                              | 6.0.0        |
| ox                                         | 2.9.2        |
| danger-junit                               | 0.7.4        |
| thor                                       | 0.20.0       |
| danger-swiftlint                           | 0.10.1       |
| fastlane-plugin-prepare_build_resources    | 1.0.4        |
| fastlane-plugin-tpa                        | 1.1.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| fastlane-plugin-versioning                 | 0.3.4        |
| xcode-install                              | 2.3.1        |
</details>

*generated on:* **2018-04-19**
</details>
  </pre>
</details>

**Comment by mbogh** [comment]
Sad to disappoint you @fastlane-bot but it is not 😀

**Comment by joshdholtz** [comment]
@mbogh I think this is because you have `fail_build: false`. If you set this to `true` (or remove it), things should be 👌 for you

**Comment by mbogh** [comment]
@joshdholtz if I do `fail_build: true` then the build fails if the test fail.

|                     | State  | On build errors | On test failures |
| ----------- | ------ | --------------- | --------------- |
| `fail_build` | `true` | 🔴 | 🔴 |
| `fail_build` | `false` | 💚 | 💚 |
| Wish           |              | 🔴 | 💚 |

**Comment by joshdholtz** [comment]
@mbogh Ohhhhhh, I totally see now 👀 Sorry about that! 🙃 I will look into 💪

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mbogh** [comment]
No problem at all, might also be an odd request 🙃 
Let me know if there is anything I can do to help. I am unsure how to add this without breaking existing setups.

**Comment by mbogh** [comment]
@joshdholtz any progress on this or maybe you can give me a pointer towards how to best solve this.

**Comment by joshdholtz** [comment]
@mbogh Hey sorry! I remember starting to look into this but then I think I got sidetracked 😔 But I got a solution now. Can you test this PR out for me? 😊 #12916

**Comment by mbogh** [comment]
@joshdholtz thanks a lot, looking forward to get this into our project so I can delete my nasty workaround 💯
