### ISSUE TITLE
/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.92.1/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)

### ISSUE THREAD

**Issue by nrazvan87** [fastlane/fastlane#12340]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

[10:26:20]: Set output directory path to: "/Users/user/git/app-ios/output".
[10:26:20]: Set derived data path to: "/Users/user/git/app-ios/derivedData".
[10:26:20]: --------------------------------------
[10:26:20]: --- Step: Switch to ios certs lane ---
[10:26:20]: --------------------------------------
[10:26:20]: Cruising over to lane 'ios certs' 🚖
[10:26:20]: -------------------
[10:26:20]: --- Step: match ---
[10:26:20]: -------------------
[10:26:20]: Successfully loaded '/Users/user/git/app-ios/fastlane/Matchfile' 📄

+----------------+--------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+----------------+--------------------------------------+
| git_url        | git@addr:app/app-ios-cer  |
|                | tificates.git                        |
| type           | development                          |
| app_identifier | *,com.app.app,com.app.app.acc      |
| team_id        | team-id                           |
| username       | mobile@app.com                   |
+----------------+--------------------------------------+

+-----------------------+--------------------------------------+
|                   Summary for match 2.92.1                   |
+-----------------------+--------------------------------------+
| type                  | development                          |
| app_identifier        | [".acc"]                             |
| readonly              | true                                 |
| git_url               | git@addr:app/app-ios-cer  |
|                       | tificates.git                        |
| git_branch            | master                               |
| username              | mobile@app.com                   |
| keychain_name         | login.keychain                       |
| team_id               | team-id                           |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

[10:26:20]: Cloning remote git repo...
[10:26:20]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:26:23]: 🔓  Successfully decrypted certificates repo
[10:26:23]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now
[10:26:23]: -------------------
[10:26:23]: --- Step: is_ci ---
[10:26:23]: -------------------
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| ENVIRONMENT      | eu,acc,local |
| PLATFORM_NAME    | ios          |
| LANE_NAME        | ios qa       |
+------------------+--------------+
[10:26:23]: No code signing identity found and can not create a new one because you enabled `readonly`

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying fastlane     | 0           |
|      | version                |             |
| 2    | xcversion              | 0           |
| 3    | default_platform       | 0           |
| 4    | Switch to ios build    | 0           |
|      | lane                   |             |
| 5    | clean_build_artifacts  | 0           |
| 6    | clear_derived_data     | 0           |
| 7    | Switch to ios setup    | 0           |
|      | lane                   |             |
| 8    | Switch to ios get_env  | 0           |
|      | lane                   |             |
| 9    | is_ci                  | 0           |
| 10   | setup_jenkins          | 0           |
| 11   | Switch to ios certs    | 0           |
|      | lane                   |             |
| 💥   | match                  | 2           |
| 13   | is_ci                  | 0           |
+------+------------------------+-------------+

[10:26:23]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Match "[!] No code signing identity found and can not create a new one because you enabled `readonly`"
    https://github.com/fastlane/fastlane/issues/8810 [closed] 13 💬
    09 Jul 2017

➡️  bitrise code signing problem (local working)
    https://github.com/fastlane/fastlane/issues/9095 [closed] 5 💬
    25 Sep 2017

➡️  Enterprise profile - No code signing identity found and can not create a new one because you enabled `readonly`
    https://github.com/fastlane/fastlane/issues/7822 [closed] 5 💬
    17 Apr 2017

and 12 more at: https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
**/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.92.1/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)**

---------

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.92.1"
xcversion version: "~> 9.3"
#ensure_git_status_clean
#ensure_xcode_version(version: "~> 8.3")

default_platform :ios

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2018-04-19**
</details>

### Environment

<!-- Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option, please remove this block as it is already included there. -->

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@nrazvan87 `match` wasn't able to install a code sign identity for the app identifier that you specified (with whatever was stored in your _match_ repo) so it wanted to create a new code sign identify for you (in the iOS Developer Portal) but could not because you have `read_only: true` on

I would suggest either:
1) Make sure you are specifying the correct app identifier (and other info) for the code signing identity that you want installed on this machine
2) Set `read_only: false` so a new code sign identity can be created

**Comment by nrazvan87** [comment]
Thanks @joshdholtz
