### ISSUE TITLE
[iTMSTransporter error] The filename {product_name}_fb5d9d0d3763874019285b6a3261ea84e77f598be9bb109d9f718fe15edddd8b.ipa in the package contains an invalid character(s).

### ISSUE THREAD

**Issue by JienLee** [fastlane/fastlane#12356]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
I used fastlane 2.92.1 version, when running with circleCI, it doesn't upload .ipa file.
```
- DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS : -t DAV
- FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT : 1
```
That setting is not woking.
Please some advice to me, How to fix it?

<details><summary><b>Error Message </b></summary>
  <pre>[iTMSTransporter] [2018-04-23 00:38:29 PDT] <main> ERROR: The filename {product_name}_fb5d9d0d3763874019285b6a3261ea84e77f598be9bb109d9f718fe15edddd8b.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore

[00:38:29]: [iTMSTransporter] [2018-04-23 00:38:29 PDT] <main> DBG-X: The error code is: 1102</pre>
</details>

**circleCI**
settings -> Environment Variables 
```
- DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS : -t DAV
- FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT : 1
```

Fastfile
```
lane :beta do
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
...
increment_build_number
match(
      type: "appstore",
      readonly: true
    )
...
gym(
      export_method: "app-store",
      workspace: "{target}.xcworkspace",
      scheme: "{target}",
      clean: true,
      include_bitcode: false,
      export_xcargs: "-allowProvisioningUpdates",
      skip_profile_detection: false
    )
...
pilot(
      username: "developer mail",
      app_identifier: "app identifier",
      apple_id: "apple id",
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
end
```

.env
```
...
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1
...
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
</details>

<details><summary>`./fastlane/Appfile`</summary>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| CFPropertyList                             | 2.3.6        |
| activesupport                              | 4.2.10       |
| addressable                                | 2.5.2        |
| atomos                                     | 0.1.2        |
| babosa                                     | 1.0.2        |
| bigdecimal                                 | 1.2.6        |
| bundler                                    | 1.14.6       |
| claide                                     | 1.0.2        |
| cocoapods                                  | 1.3.1        |
| cocoapods-core                             | 1.3.1        |
| cocoapods-deintegrate                      | 1.0.1        |
| cocoapods-downloader                       | 1.1.3        |
| cocoapods-plugins                          | 1.0.0        |
| cocoapods-search                           | 1.0.0        |
| cocoapods-stats                            | 1.0.0        |
| cocoapods-trunk                            | 1.3.0        |
| cocoapods-try                              | 1.1.0        |
| colored                                    | 1.2          |
| colored2                                   | 3.1.2        |
| commander-fastlane                         | 4.4.6        |
| concurrent-ruby                            | 1.0.5        |
| declarative                                | 0.0.10       |
| declarative-option                         | 0.1.0        |
| domain_name                                | 0.5.20170404 |
| dotenv                                     | 2.2.1        |
| emoji_regex                                | 0.1.1        |
| escape                                     | 0.0.4        |
| excon                                      | 0.60.0       |
| faraday                                    | 0.13.1       |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0.1     |
| fastimage                                  | 2.1.1        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| fourflusher                                | 2.0.1        |
| fuzzy_match                                | 2.0.4        |
| gh_inspector                               | 1.1.2        |
| google-api-client                          | 0.13.6       |
| googleauth                                 | 0.5.1        |
| highline                                   | 1.7.10       |
| http-cookie                                | 1.0.3        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| i18n                                       | 0.9.1        |
| io-console                                 | 0.4.3        |
| json                                       | 1.8.1        |
| jwt                                        | 2.1.0        |
| jwt                                        | 1.5.6        |
| libxml-ruby                                | 3.0.0        |
| little-plugger                             | 1.1.4        |
| logging                                    | 2.2.2        |
| memoist                                    | 0.16.0       |
| mime-types                                 | 3.1          |
| mime-types-data                            | 3.2016.0521  |
| mini_magick                                | 4.5.1        |
| minitest                                   | 5.10.3       |
| molinillo                                  | 0.5.7        |
| multi_json                                 | 1.12.2       |
| multi_xml                                  | 0.6.0        |
| multipart-post                             | 2.0.0        |
| nanaimo                                    | 0.2.5        |
| nap                                        | 1.1.0        |
| naturally                                  | 2.1.0        |
| netrc                                      | 0.11.0       |
| nokogiri                                   | 1.5.6        |
| os                                         | 0.9.6        |
| plist                                      | 3.4.0        |
| power_assert                               | 0.2.2        |
| psych                                      | 2.0.8        |
| public_suffix                              | 2.0.5        |
| rake                                       | 10.4.2       |
| rdoc                                       | 4.2.0        |
| representable                              | 3.0.4        |
| retriable                                  | 3.1.1        |
| rouge                                      | 2.0.7        |
| rouge                                      | 1.11.1       |
| ruby-macho                                 | 1.1.0        |
| rubygems-update                            | 2.5.2        |
| rubyzip                                    | 1.2.1        |
| security                                   | 0.1.3        |
| signet                                     | 0.7.3        |
| simctl                                     | 1.6.4        |
| slack-notifier                             | 2.3.2        |
| sqlite3                                    | 1.3.13       |
| terminal-notifier                          | 1.8.0        |
| terminal-table                             | 1.7.3        |
| test-unit                                  | 3.0.8        |
| thread_safe                                | 0.3.6        |
| tty-cursor                                 | 0.5.0        |
| tty-screen                                 | 0.6.3        |
| tty-spinner                                | 0.8.0        |
| tzinfo                                     | 1.2.4        |
| uber                                       | 0.1.0        |
| unf                                        | 0.1.4        |
| unf_ext                                    | 0.0.7.4      |
| unicode-display_width                      | 1.3.0        |
| unicode-display_width                      | 1.1.3        |
| word_wrap                                  | 1.0.0        |
| xcodeproj                                  | 1.5.7        |
| xcpretty                                   | 0.2.6        |
| xcpretty-travis-formatter                  | 0.0.4        |
</details>

*generated on:* **2018-04-23**
</details>

**Comment by mvandervelden** [comment]
I encounter a similar issue with pilot today. The error message is:
`Return status of iTunes Transporter was 1: The filename .ipa_5538e9f0bd5ed2254d8adef3a465c7bd2b9530b1cd21b2dab75d13db6be0f3ac.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore`
I was first running it on Fastlane 2.91.0, then on 2.29.1, both failed.

Fastfile:
```ruby
  lane :deploy_appstore do |options|
    if options[:bump]
        version_bump_project(bump_type:options[:bump])
    end
    if git_branch == "release"
        upload_meta_data
        match(type: "appstore", readonly: true, app_identifier:["xxx"])
        gym(scheme: "xxx",
            configuration: "Appstore",
            export_method:"app-store",
            output_directory: ENV["CIRCLE_ARTIFACTS"],
            output_name: "#{ENV["APP_NAME_EXT"]}.ipa",
            buildlog_path: ENV["CIRCLE_ARTIFACTS"],
            clean: true,
            silent: true
        )
        pilot(username: "xxx",
              skip_submission: "true",
              apple_id: "xxx",
              distribute_external: "false",
              skip_waiting_for_build_processing: "true"
        )
    end
  end

lane :upload_meta_data do |options|
    if options[:version]
        current_version = options[:version]
    else
        current_version = get_version_number(target: "xxx")
    end

    skip_screenshots = true
    if options[:skip_screenshots] == false
        skip_screenshots = false
    end

    deliver(username: "xxx",
            app_identifier: "xxx",
            app_version: current_version,
            skip_screenshots: skip_screenshots,
            skip_binary_upload: true,
            force: true
    )
  end

  lane :version_bump_project do |options|
    # Set build number to current date and time
    build_number = Time.new.strftime("%Y.%m.%d.%H.%M")
    ENV["BUILD_NUMBER"] = build_number
    increment_build_number(build_number: build_number)
    # Set version number conforming the bump type
    if options[:bump_type]
      cw_version_bump(bump_type: options[:bump_type])
    end
  end
```

pilot output on CircleCI:
```
[10:04:21]: -------------------
[10:04:21]: --- Step: pilot ---
[10:04:21]: -------------------
[10:04:21]: Login to iTunes Connect (xxx)
[10:04:24]: Login successful
[10:04:27]: Ready to upload new build to TestFlight (App: 926272969)...
[10:04:29]: Going to upload updated app to iTunes Connect
[10:04:29]: This might take a few minutes. Please don't interrupt the script.

[10:04:54]: Transporter transfer failed.
[10:04:54]: 

[10:04:54]: [iTMSTransporter] [2018-04-23 10:04:54 PDT] <main> DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[pkg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}


[10:04:54]: [iTMSTransporter] [2018-04-23 10:04:54 PDT] <main> DBG-X:   parameter ErrorMessage = The filename .ipa_5538e9f0bd5ed2254d8adef3a465c7bd2b9530b1cd21b2dab75d13db6be0f3ac.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscor


[10:04:54]: [iTMSTransporter]  (1102)


[10:04:54]: [iTMSTransporter] [2018-04-23 10:04:54 PDT] <main> DBG-X:   parameter Success = false


[10:04:54]: [iTMSTransporter] [2018-04-23 10:04:54 PDT] <main> ERROR: The filename .ipa_5538e9f0bd5ed2254d8adef3a465c7bd2b9530b1cd21b2dab75d13db6be0f3ac.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore


[10:04:54]: [iTMSTransporter] [2018-04-23 10:04:54 PDT] <main> DBG-X: The error code is: 1102


[10:04:54]: [iTMSTransporter] 


[10:04:54]: [iTMSTransporter] 


[10:04:54]: [iTMSTransporter] 


[10:04:54]: [iTMSTransporter] Package Summary:


[10:04:54]: [iTMSTransporter]  


[10:04:54]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:


[10:04:54]: [iTMSTransporter] 	/var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/d20180423-13371-l998eu/926272969.itmsp - Error Messages:


[10:04:54]: [iTMSTransporter] 		The filename .ipa_5538e9f0bd5ed2254d8adef3a465c7bd2b9530b1cd21b2dab75d13db6be0f3ac.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore


[10:04:54]: [iTMSTransporter] [2018-04-23 10:04:54 PDT] <main> DBG-X: Returning 1


[10:04:54]: iTunes Transporter output above ^
[10:04:54]: The filename .ipa_5538e9f0bd5ed2254d8adef3a465c7bd2b9530b1cd21b2dab75d13db6be0f3ac.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore

Return status of iTunes Transporter was 1: The filename .ipa_5538e9f0bd5ed2254d8adef3a465c7bd2b9530b1cd21b2dab75d13db6be0f3ac.ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore

The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  Lane Context                                                                                   |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                                                        |
| PLATFORM_NAME                      | ios                                                                                                                                        |
| LANE_NAME                          | ios deploy_appstore                                                                                                                        |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/distiller/Library/Keychains/login.keychain-db"                                                                                     |
| VERSION_NUMBER                     | 3.36                                                                                                                                       |
| SIGH_PROFILE_TYPE                  | app-store                                                                                                                                  |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"xxx"=>"match AppStore xxx", "xxx"=>"match AppStore xxx"} |
| IPA_OUTPUT_PATH                    | /Users/distiller/project/.ipa                                                                                                              |
| DSYM_OUTPUT_PATH                   | /Users/distiller/project/.app.dSYM.zip                                                                                                     |
| XCODEBUILD_ARCHIVE                 | /Users/distiller/Library/Developer/Xcode/Archives/2018-04-23/ 2018-04-23 09.53.16.xcarchive                                                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
[10:04:54]: Error uploading ipa file, for more information see above
```

**Comment by JienLee** [comment]
@fastlane-bot No that's not code signing issue. Because 'gym' running is success.
When 'pilot' run it shows the iTMSTransporter error.

**Comment by JienLee** [comment]
Today build the 2.93.0 pilot is success. (on CircleCI). So I close this issue.
