### ISSUE TITLE
Three stages Upload

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12369]
I want to use three stages. At first Just build, then test without build then just archive and upload testflight. But now, every stage build the code again. I want to use first build to test and upload.

My codes:

For Build
```rb
clear_derived_data
xcodebuild(
  workspace: "ios/XYZ.xcworkspace",
  scheme: "XYZ",
  build: true,
  configuration: 'Development',
  destination: "platform=iOS Simulator,name=iPhone 8"
)
```

For Test 
```rb
scan(
  workspace: "ios/XYZ.xcworkspace",
  scheme: "XYZ",
  configuration: "Development"
)
```

For Upload
```rb
build_ios_app(
  workspace: "ios/XYZ.xcworkspace",
  scheme: "XYZ"
)
upload_to_testflight(
  beta_app_description: "Batur test",
  beta_app_feedback_email: "info@XYZ.com",
  skip_submission: true
)
```

**Comment by joshdholtz** [comment]
@baturorkun Hey 👋 I don't think that you will be able to make the first build work for both your test **and** upload (unless I am mistaken) as you usually need you upload as `configuration: 'Release'` using `upload_test_testflight`

So right now (based upon your code), your app is going to build 3 times. The easiest thing would be to drop the `xcodebuild` and just use `scan` and `build_ios_app` (which will build twice) but `scan` will build using `configuration: 'Development'` where `build_ios_app` will build using `configuration: 'Release'`

**Comment by baturorkun** [comment]
hi joshdholtz
i want to build and produce derived data, then use derived data for testing.

**Comment by baturorkun** [comment]
What's wrong below?

Build:

  clear_derived_data
  xcodebuild(
      		workspace: "ios/XYZ.xcworkspace",
      		scheme: "XYZ",
          build: true,
          #configuration: 'Development',
      		destination: "platform=iOS Simulator,name=iPhone 8",
          derivedDataPath: "/Users/batur/Library/Developer/Xcode/DerivedData/batur1"
       )

Test

 scan(
     workspace: "ios/XYZ.xcworkspace",
     scheme: "XYZ",
     test_without_building: true,
     derived_data_path: "/Users/batur/Library/Developer/Xcode/DerivedData/batur1",
     destination: "platform=iOS Simulator,name=iPhone 8"
   )

**Comment by baturorkun** [comment]
i did it like this.

BUILD:

  clear_derived_data
    xcodebuild(
      	 workspace: "ios/XYZ.xcworkspace",
      	 scheme: "XYZ",
          clean: true,
          configuration: 'Debug',
      	  destination: "platform=iOS Simulator,name=iPhone 8",
          device: "iPhone 8",
          derivedDataPath: "/Users/batur,/Library/Developer/Xcode/DerivedData/batur",
          xcargs: "build-for-testing"
    )


TEST:

scan(
     workspace: "ios/XYZ.xcworkspace",
     scheme: "XYZ",
     test_without_building: true,
     skip_build: true,
     configuration: 'Debug',
     derived_data_path: "/Users/batur/Library/Developer/Xcode/DerivedData/batur",
     device:"iPhone 8",
     #clean: true
   )

UPLOAD:

 increment_build_number(
        xcodeproj: "ios/XYZ.xcodeproj",
        build_number: build_number
      )

     build_ios_app(
  		 workspace: "ios/XYZ.xcworkspace",
                 scheme: "XYZ"
  	 )

     version =  get_version_number(xcodeproj: "ios/XYZ.xcodeproj")
     changelog = getChangeLogs(version)

  upload_to_testflight(
       changelog: changelog,
       beta_app_description: "Minor bug fixes and improvements",
       beta_app_feedback_email: "batur@domain",
       #skip_submission: true
       skip_waiting_for_build_processing: false
     )
