### ISSUE TITLE
Automate Tweet For Fastlane Releases

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#1236]
Now we have the tweet action there is no excuse not to ;)
https://github.com/fastlane/fastlane/blob/master/fastlane/Fastfile#L101

**Comment by KrauseFx** [comment]
Yeah :rocket:

**Comment by bgannin** [comment]
Where should the access details live? Where might I find the applicable values for the account to use? Thanks!

**Comment by TKBurner** [comment]
Hi @bgannin! Great to hear from you. Are you considering a PR for this? Thanks!

**Comment by KrauseFx** [comment]
There already is a `twitter` action, however we decided not to auto-tweet, since we usually attach screenshots to the tweets.

**Comment by bgannin** [comment]
👍 Thanks for the update.
