### ISSUE TITLE
Spaceship auto release date value is not reflected in iTunes Connect

### ISSUE THREAD

**Issue by kkw4** [fastlane/fastlane#12366]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When looking at this previous issue (https://github.com/fastlane/fastlane/pull/7151), it looks like there is currently functionality in spaceship to perform an auto release after a specific date. This seems to be set via the auto_release_date field in AppVersion.

When performing the following commands and after waiting for some time, we see that there are no changes in iTunes Connect. Specifically, we navigate to the specific App, click on the App which is in "Prepare for Submission" state, and look at the "Automatically release this version after App Review, no earlier than" entry.

The commands we run in fastlane spaceship are:

app = Spaceship::Tunes::Application.find("x.x.x")
v = app.edit_version
v.auto_release_date = 1527829200
v.save!

Note that the app bundle identifier is replaces with "x.x.x" for anonymity.

Afterwards, we run "v.auto_release_date" and I see this:
pry(#<Spaceship::Playground>)> v.auto_release_date
=> 1527829200

Note that 1527829200 corresponds to:
GMT: Friday, 1 June 2018 05:00:00
This is a timestamp in the future.

However, there are no updates in iTunes Connect. Is this a known issue or should the date be set via a different way?

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.1/bin/fastlane       |
| Host                        | Mac OS X 10.12.2 (16C68)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-04-23**
</details>

**Comment by joshdholtz** [comment]
@kkw4 It looks like you are doing it correctly but I will look into 👌

**Comment by kkw4** [comment]
@joshdholtz Did you manage to find out more information on this issue? Thanks!

**Comment by joshdholtz** [comment]
Will look into more tomorrow morning for you! 😊

**Comment by joshdholtz** [comment]
@kkw4 Just realized your `auto_release_date` needs to be in milliseconds 🙃 So `1527829200 * 1000` should do the trick for ya 💪

**Comment by kkw4** [comment]
@joshdholtz Thanks for looking into this. I tried your suggestion of multiplying the unix date by 1000, but it still doesn't seem to update the date in iTunesConnect. This is after waiting for about 2 hours after running the save! command. Could you take a further look?

**Comment by kkw4** [comment]
@joshdholtz Just following up, are there any updates on this? Were you able to test this on your side as well? We're still seeing the same issue. Thanks

**Comment by joshdholtz** [comment]
@kkw4 The was able to replicate your issue and my solution I posted above solved it for me 😬  I don't have any updates since this "work on my machine" 😔
