### ISSUE TITLE
command not found fastlane after installing integrated in both Xcode bots and Jenkins

### ISSUE THREAD

**Issue by hemanthmpkumar** [fastlane/fastlane#1237]
Steps:

1. sudo gem install fastlane --verbose
...
2. After Successfully installed fastlane cd MyAppFolder/
3. fastlane init
lane :build do
    Gym
  end
4. fastlane build (Works fine in the local)
5. git commit -a -m "pushing to git"
6. In Jenkins, added build step as execute shell script
    "fastlane build"
7. Build now

[IOSSample3] $ /bin/sh -xe /var/folders/yx/8mys4k3s5836q0mdjc3l9_yw0000gq/T/hudson982340983277737459.sh
+ fastlane
/var/folders/yx/8mys4k3s5836q0mdjc3l9_yw0000gq/T/hudson982340983277737459.sh: line 3: fastlane: command not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE

Am I doing something wrong?

**Comment by vpolouchkine** [comment]
Did you checkout https://github.com/fastlane/fastlane/blob/master/docs/Jenkins.md?

**Comment by btawfic** [comment]
It's because Jenkins can't see your PATH variable. You can just use the full path to your fastlane install
`/usr/local/bin/fastlane build`

**Comment by TKBurner** [comment]
@hemanthmpkumar Can you verify this is fixed? Closing this issue until we get an update :+1:

**Comment by hemanthmpkumar** [comment]
@btawfic Thanks for the updates , i will check it and let you know . :), Thanks @TKBurner
