### ISSUE TITLE
Could not find action, lane or variable 'folder'

### ISSUE THREAD

**Issue by Dharmarajm** [fastlane/fastlane#12380]
I'm getting the below error. I don't know what i'm missing in fastlane file.

+---------------------+------------------------------------------------------------------------------------+
11:04:09 |                                               [33mLane Context[0m                                               |
11:04:09 +---------------------+------------------------------------------------------------------------------------+
11:04:09 | PLATFORM_NAME       | ios                                                                                |
11:04:09 | LANE_NAME           | ios build                                                                          |
11:04:09 | PRODUCE_APPLE_ID    |                                                                                    |
11:04:09 | CERT_FILE_PATH      | /Users/altius-mac/workspace/MobCom-ios/V7N4K52VEP.cer                              |
11:04:09 | CERT_CERTIFICATE_ID | V7N4K52VEP                                                                         |
11:04:09 | SIGH_PROFILE_PATH   | /Users/altius-mac/workspace/MobCom-ios/AdHoc_com.mob.alti.mobileprovision     |
11:04:09 | SIGH_PROFILE_PATHS  | ["/Users/altius-mac/workspace/MobCom-ios/AdHoc_com.mob.alti.mobileprovision"] |
11:04:09 | SIGH_UDID           | b61fdbdf-2cb6-4a1e-a9a1-06bc5e7ed089                                               |
11:04:09 | SIGH_UUID           | b61fdbdf-2cb6-4a1e-a9a1-06bc5e7ed089                                               |
11:04:09 | SIGH_NAME           | Mobc                                                                         |
11:04:09 | SIGH_PROFILE_TYPE   | ad-hoc                                                                             |
11:04:09 +---------------------+------------------------------------------------------------------------------------+
11:04:09 [11:04:09]: [31mCould not find action, lane or variable 'folder'. Check out the documentation for more details: https://docs.fastlane.tools/actions[0m
11:04:09 
11:04:09 +------+-----------------------------------+-------------+
11:04:09 |                    [32mfastlane summary[0m                    |
11:04:09 +------+-----------------------------------+-------------+
11:04:09 | Step | Action                            | Time (in s) |
11:04:09 +------+-----------------------------------+-------------+
11:04:09 | 1    | produce                           | 7           |
11:04:09 | 2    | cert                              | 10          |
11:04:09 | 3    | get_provisioning_profile          | 11          |
11:04:09 | 4    | (cd .. && ionic platform add ios) | 71          |
11:04:09 +------+-----------------------------------+-------------+
11:04:09 
11:04:09 [11:04:09]: [31mfastlane finished with errors[0m
11:04:09 [31m
11:04:09 [!] Could not find action, lane or variable 'folder'. Check out the documentation for more details: https://docs.fastlane.tools/actions[0m

I'm integrating fastlane in ionic project. I didn't get the PRODUCE_APPLE_ID  field in lane context. If someone figure it out what is an issue, that is helpful to me.

**Comment by hjanuschka** [comment]
can you share your fastfile.

or as mentioned in the issue template:

> you can use: `--capture_output` as the last commandline argument to get that collected for you -->
> The output of `--capture_output` could contain sensitive data such as application ids, certificate ids, > or email addreses, Please make sure you double check the output and replace anything sensitive you > don't wish to submit in the issue


you can manually redact sensitive data, but it helps alot to troubelshoot the issue

**Comment by Dharmarajm** [comment]
Sorry for rising this error. Actually I forgot to hash the line in fastlane file.

Thanks for your comments hjanuschka.
