### ISSUE TITLE
Handle lane errors in Swift

### ISSUE THREAD

**Issue by haritowa** [fastlane/fastlane#12381]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello, I am new to fastlane swift, is there any way to handle errors, occurred during Fastfile.swift lane invocation?

I found method `func onError(currentLane: String, errorInfo: String)`, but it seems, that method is not invoked for errors.

**Comment by joshdholtz** [comment]
@haritowa That is a good question! I have been making some improvements to swift lately but I have not come across this yet so I will look into this for you! 🙃

**Comment by haritowa** [comment]
@joshdholtz Throws lanes will be the best choice, I guess. Maybe I'll investigate it later, unfortunately, there is no chance for me to do any side work for now ¯\_(ツ)_/¯

**Comment by ruffnecktsk** [comment]
Any updates?
