### ISSUE TITLE
changelog_from_git_commits

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12397]
i want to write commit logs to WHAT TO TEXT while uploading testflight, then i saw "changelog_from_git_commits action, but there is no PATH parameter. My Fastlane directory and git repo are different paths.

**Comment by joshdholtz** [comment]
@baturorkun `changelog_from_git_commits` assumes your fastlane is within your git repo 🙃 If you are comfortable trying to make this change yourself we would love a PR... otherwise I will add this to my list of things to add 😉

**Comment by baturorkun** [comment]
hi joshdholtz
actually, it is important parameter, because i have 2 project (ios and android)
i set the fastlane directory to top of these projects folder. so i use one fastlane directory for 2 projects.
:)

**Comment by RishabhTayal** [comment]
started a PR for this #12429
