### ISSUE TITLE
increment_build_number not reading complete build number

### ISSUE THREAD

**Issue by ahmad2smile** [fastlane/fastlane#12398]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

latest_testflight_build_number asked for manual input for choosing the build number. Which I provided the value of `20` but increment_build_number read it somehow wrong and set my new build number to `2`.

##### Complete output when running fastlane, including the stack trace and command used

```
Login successful
You have to specify a new version number, as there are multiple to choose from
20
Fetching the latest build number for version 20
Could not find a build on iTC. Using supplied 'initial_build_number' option
Latest upload for version 20 is build: 1
------------------------------------
--- Step: increment_build_number ---
------------------------------------
Current version of project Epicor is: 
    20

/Users/a_050313/Documents/dev/scheduling
$ cd /Users/a_050313/Documents/dev/scheduling/ios && agvtool new-version -all 2 && cd -
▸ Setting version of project Epicor to:
▸ 2.
▸ Also setting CFBundleVersion key (assuming it exists)
▸ Updating CFBundleVersion in Info.plist(s)...
▸ Updated CFBundleVersion in "Epicor.xcodeproj/../Epicor-tvOS/Info.plist" to 2
▸ Updated CFBundleVersion in "Epicor.xcodeproj/../Epicor-tvOSTests/Info.plist" to 2
▸ Updated CFBundleVersion in "Epicor.xcodeproj/../Epicor/Info.plist" to 2
▸ Updated CFBundleVersion in "Epicor.xcodeproj/../EpicorUITests/Info.plist" to 2
```

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.92.1  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-tunes                                 | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-commit_android_version_bump           | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-increment_version_code                | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-get_version_code                      | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-install_provisioning_profiles         | 0.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-remove_provisioning_profile           | 1.0.3   | ✅ Up-To-Date  |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0   | ✅ Up-To-Date  |</pre>
</details>

**Comment by joshdholtz** [comment]
@ahmad2smile This is very strange 🤔 Will look into to see if I can replicate

**Comment by joshdholtz** [comment]
@ahmad2smile I can't see what your `Fastfile` is or what your whole output was but are you passing up `:version` in the action options?

1. It seems like it couldn't find your version on iTunesConnect / TestFlight so it prompted you for the "version number".
2. It looks like you entered a "build number" for the prompt instead of a "version number"
3. It couldn't find a "version number" of 20 so it used the `:initial_build_number` of `1` (which got returned by this action)
4. That `1` got passed into `increment_build_number` which got incremented to `2`

So it looks like this may have been caused by an error by entering a "build number" instead of a "version number" when prompted?

**Comment by ahmad2smile** [comment]
I see. There were some issues with previous builds on Testflight so versions got mixed up.

```build number for version 20```

I didn't pay attention to this. My apologies.  Just 1 thing though. On Testflight we got '2.0.0' and '1.3.0'. In future scenario would I enter just 2 or the whole '2.0.0'.

Really appreciate you response. Thanks.

**Comment by joshdholtz** [comment]
@ahmad2smile You would enter `2.0.0`. That _should_ work but I cannot verify 100% since I don't have access to your account 😉 Happy fastlaning 🚀

**Comment by ahmad2smile** [comment]
Yes, That solution was right. I had 2 different version setup on itunes and I had to select the right one. This is solved and was problem on my end.
