### ISSUE TITLE
can't load cocapods-1.2.1/bin/pod (have 1.5.1 installed)

### ISSUE THREAD

**Issue by invoodoo** [fastlane/fastlane#12405]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using fastlane started to get message:

xit status of command 'pod install' was 1 instead of 0.
/Users/InVooDoo/.fastlane/bin/bundle/bin/pod:22:in `load': cannot load such file -- /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.1/bin/pod (LoadError)
	from /Users/InVooDoo/.fastlane/bin/bundle/bin/pod:22:in `<main>'

And I see that fastlane try to use 1.2.1, how to set use 1.5.1 or just latest I have?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.13.4                                                 |
| Ruby                        | 2.2.4                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.15.1 (Apple Git-101)                      |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E202)                               |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                              |
| Is contained                | true                                                    |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Development/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

require_relative '/Users/InVooDoo/Library/Mobile Documents/com~apple~CloudDocs/iWork/Misc/actions'

$apple_id = "evgeniy.lebed@gmail.com"
$git_branch = "master"
$team_id = "EHTMEM7E2H"
$itc_team_id = "2106312"

$bundle_ids = ["biz.keyd.globeconvert", "com.globefamilyapps.globeconvert"]
$info_plists = ["Properties/Free-Info.plist", "Properties/Paid-Info.plist"]
$schemes = ["GlobeConvert Free", "GlobeConvert Paid"]

$bundle_id = $bundle_ids[0]

$types = ["free", "paid"]

$project_path = "GlobeUnits.xcodeproj"
$app_name = "GlobeConvert"

$signing_identity = "iPhone Distribution: Ievgenii Lebid (EHTMEM7E2H)"

before_all do |lane, options|
    ENV["APP_IDENTIFIER"] = $bundle_id
end

platform :ios do
    lane :tf do |options|
        build(options)
    end

    lane :dsyms do |options|
        upload_dsyms(options)
    end

    lane :ver do |options|
        update_codesign_version
    end
end

after_all do |lane, options|
    clean_build_artifacts

    is_git_check = options[:check]

    if is_git_check
       reset_git_repo(force: true)
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id "evgeniy.lebed@gmail.com" # Your Apple email address

team_id "EHTMEM7E2H" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.93.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin              | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane-plugin-act | 1.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| emoji_regex               | 0.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-act       | 1.1.1        |
| fastlane-plugin-appicon   | 0.7.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.1.2        |
| google-api-client         | 0.13.1       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.6        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.4        |
| nap                       | 1.1.0        |
| naturally                 | 2.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.3.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.3        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.3        |
| tty-spinner               | 0.8.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.1.0        |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.3.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.7        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-04-28**
</details></pre>
</details>

**Comment by minuscorp** [comment]
It seems that the lock of your bundle of using a Cocoapods version 1.2.1, you either update the dependency in your bundle or delete it to force fastlane to use the system one

**Comment by invoodoo** [comment]
@minuscorp I'm not using bundle for most of the projects and all the time using it. I have checked fastlane it has 1.2.1 gemspec. Don't know how to change it so far. In the system cocoapods 1.5.0 only now.

**Comment by minuscorp** [comment]
You have defined in your `Gemfile` the CocoaPods dependency with that version, but it seems that is not installed, you should try to `bundle install` and `bundle update`

**Comment by joshdholtz** [comment]
@invoodoo Were you able to solve this? 😊

**Comment by invoodoo** [comment]
I have reinstalled all wig sudo and wothout and it seems like it works now. :-)
