### ISSUE TITLE
pilot import CSV library wrong number of arguments

### ISSUE THREAD

**Issue by dbroudy** [fastlane/fastlane#12403]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
pilot's test_importer seems to call the CSV foreach method with an extra argument ("r" for readonly only open)

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>$ bundle exec fastlane pilot import -c fastlane/testflight-test.csv -a com.topya.soccer.test 
[✔] 🚀 
[12:06:21]: Login to iTunes Connect (dbroudy@3aspen.com)
[12:06:23]: Login successful

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Regression] ErbalT now requires 2 params
    https://github.com/fastlane/fastlane/issues/11917 [closed] 2 💬
    a day ago

➡️  Show plugin actions on the plugin page
    https://github.com/fastlane/fastlane/pull/11117 [closed] 3 💬
    21 Feb 2018

➡️  wrong number of arguments (given 1, expected 2) in snapshot runner.rb:200
    https://github.com/fastlane/fastlane/issues/5976 [closed] 8 💬
    24 Apr 2017

and 10 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20%28given%202%2C%20expected%201%29&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.5.0/bin/fastlane)
ArgumentError: [!] wrong number of arguments (given 2, expected 1)
  /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/csv.rb:1139:in `foreach'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/pilot/lib/pilot/tester_importer.rb:20:in `import_testers'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/pilot/lib/pilot/commands_generator.rb:160:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.93.1/bin/fastlane:20:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.5.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | /usr/local/lib/ruby/gems/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs

fastlane_require 'securerandom'

# update_fastlane
fastlane_version "2.0.0"
xcversion(version: "~> 9.3.0")

default_platform :ios

def get_app_list(apps)
  default_apps = ["Soccer", "Lacrosse", "Volleyball", "Active", "Martial Arts", "Yoga"] #, "Cricket"]

  if !apps then
    return default_apps
  end

  app_list = apps.split(/ *, */)
  return app_list || default_apps
end

def get_env_name()
  return case git_branch
    when 'build/test'
      'test'
    when 'build/demo'
      'demo'
    when 'build/prod'
      'release'
    else
      prompt(text: 'Unknown environment, use environment: ')
    end
end

def get_app_id(env_name, base_name)
  case env_name
    when 'release'
      case base_name.downcase
        when 'soccer'
          app_id = "com.soccersphere.mysoccermoves"
        else
          app_id = "com.topya.#{base_name.downcase.delete(' ')}"
      end
      app_name = "TopYa! #{base_name}"
    else
      app_id = "com.topya.#{base_name.downcase.delete(' ')}.#{env_name}"
      app_name = "#{base_name} - #{env_name.capitalize}"
  end
  return app_id, app_name
end

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Update data from iTunes Connect"
  lane :pull do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])
    ENV["DELIVER_FORCE_OVERWRITE"] = "1"

    app_list.each do |app_name|
      base_name = app_name.downcase.delete(' ')
      app_id, full_name = get_app_id(env_name, base_name)
      system("fastlane deliver download_screenshots -a #{app_id} -w #{base_name}/screenshots")
      system("fastlane deliver download_metadata -a #{app_id} -m #{base_name}/metadata")
    end
  end
  
  desc "Update data in iTunes Connect"
  lane :push do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])

    app_list.each do |app_name|
      base_name = app_name.downcase.delete(' ')
      app_id, full_name = get_app_id(env_name, base_name)
      deliver(
        app_identifier: app_id,
        screenshots_path: "fastlane/#{base_name.downcase}/screenshots",
        metadata_path: "fastlane/#{base_name.downcase}/metadata",
        skip_binary_upload: true,
        submit_for_review: false,
        run_precheck_before_submit: false,
        force: true)
    end
  end
  
  desc "New Version in iTunes Connect"
  lane :newversion do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])
    app_version = options[:version]

    app_list.each do |app_name|
      base_name = app_name.downcase.delete(' ')
      app_id, full_name = get_app_id(env_name, base_name)
      deliver(
        app_identifier: app_id,
        app_version: app_version,
        skip_binary_upload: true,
        skip_metadata: true,
        skip_screenshots: true,
        submit_for_review: false,
        run_precheck_before_submit: false,
        force: true)
    end
  end

  desc "Submit App for Review"
  lane :submit do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])

    app_list.each do |app_name|
      base_name = app_name.downcase.delete(' ')
      app_id, full_name = get_app_id(env_name, base_name)
      case env_name
        when 'release'
          deliver(
            app_identifier: app_id,
            skip_binary_upload: true,
            skip_metadata: true,
            skip_screenshots: true,
            submit_for_review: true,
            automatic_release: true,
            force: true)
        else
          pilot(
            app_identifier: app_id,
            skip_binary_upload: true,
            distribute_external: true)
      end
    end
  end
  
  desc "Create new App in iTunes Connect"
  lane :new do |options|
    env_name = (options[:env] || get_env_name()).downcase

    app_id, app_name = get_app_id(env_name, options[:name])

    produce(
      app_identifier: app_id,
      app_name: app_name,
      app_version: '1.0',
      sku: SecureRandom.uuid,
      language: "English",
    )

  end

  desc "Submit a new Build"
  lane :build do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])
    use_hockey = false 

    build_number = 10000 + number_of_commits
    increment_build_number(
      build_number: build_number,
      xcodeproj: "TopYa.xcodeproj"
    )
    disable_automatic_code_signing(path: "TopYa.xcodeproj")
    cocoapods(
      repo_update: true,
    )

    app_list.each do |app_name|
      app_id, = get_app_id(env_name, app_name)
      scheme_name = "#{app_name} - #{env_name.capitalize}"

      match(
        app_identifier: app_id,
        type: "appstore",
        readonly: true
      )
      gym(
        clean: true,
        scheme: scheme_name,
        silent: false,
        codesigning_identity: "iPhone Distribution: TalentKode Sports LLC",
        output_directory: "fastlane/build")
      if use_hockey
        hockey(release_type: env_name)
      else
        pilot(skip_waiting_for_build_processing: true)
      end
    end

    enable_automatic_code_signing(path: "TopYa.xcodeproj")

    slack(
      channel: "#deployments",
      message: if use_hockey then
          "iOS #{env_name.capitalize} builds available in HockeyApp"
        else
          "iOS #{env_name.capitalize} builds available in Test Flight"
        end,
      attachment_properties: {
        "fields": [
          {
            "title": "Build",
            "value": build_number,
            "short": true
          },
          {
            "title": "Apps",
            "value": app_list.join("\n"),
            "short": true
          }
        ]
      })
  end

  desc "Update dSYMs"
  lane :refresh_dsyms do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])
    sym_env = case env_name when "release" then "Prod" else env_name.capitalize end

    app_list.each do |app_name|
      app_id, = get_app_id(env_name, app_name)

      download_dsyms(app_identifier: app_id)
      upload_symbols_to_crashlytics(gsp_path: "TopYa/GoogleService-Info-#{app_name.delete(' ')}#{sym_env}.plist")
      clean_build_artifacts
      lane_context[SharedValues::DSYM_PATHS] = []
    end
  end

  desc "Create Deliver commit"
  lane :deliverlog do
    changelog = changelog_from_git_commits(
      between: [ "origin/#{git_branch()}", "MERGE_HEAD"],
      merge_commit_filtering: 'include_merges')

    tracker_ids = {}
    changelog.scan(/\[(finishes|finished)? *(#\d+)\]/im) do |state, tracker_id|
      if state
        tracker_ids[tracker_id] = state #|| "Finished"
      end
    end 
    message = "\n"
    tracker_ids.each do |id, state|
      message << "[Delivers #{id}]\n"
    end
    puts(message)
  end

  desc "Add tester to applications"
  lane :addtester do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])

    app_list.each do |app_name|
      app_id, app_name = get_app_id(env_name, app_name)
      if options[:testers]
        testers = options[:testers].split(/ *, */)
        testers.each do |tester|
          system("fastlane pilot add #{tester} -a #{app_id}")
        end
      else
        tester_file = "fastlane/testflight-#{env_name.downcase}.csv"
        system("fastlane pilot import -c #{tester_file} -a #{app_id}")
      end
    end
  end

  desc "Update match and push certificates and profiles"
  lane :updatecerts do |options|
    env_name = (options[:env] || get_env_name()).downcase
    app_list = get_app_list(options[:apps])

    app_list.each do |app_name|
      app_id, = get_app_id(env_name, app_name)

      pem(
        development: true,
        app_identifier: app_id, 
        output_path: "fastlane/itunes/push"
      )
      pem(
        development: false,
        app_identifier: app_id, 
        output_path: "fastlane/itunes/push"
      )

      match(app_identifier: app_id, type: "development")
      match(app_identifier: app_id, type: "appstore")
    end
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
team_id "V67XXXXXXX"  # Developer Portal Team ID
itc_team_id "58XXXXX"



```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.93.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| cocoapods                 | 1.5.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.3.1        |
</details>

*generated on:* **2018-04-27**
</details>

**Comment by dbroudy** [comment]
This looks like a really simple fix and I was going submit a PR, but then I ran into #12402 trying to run the unit tests.

**Comment by joshdholtz** [comment]
@dbroudy Are you able to try with Ruby `2.4` or lower? It looks like the CSV module may have changed in Ruby `2.5`

**Comment by joshdholtz** [comment]
- Ruby 2.4
  - `foreach(path, options = Hash.new, &block)`
    - ^ looks same for 2.4 and below
  - https://ruby-doc.org/stdlib-2.4.0/libdoc/csv/rdoc/CSV.html#method-c-foreach
- Ruby 2.5
  - `foreach(path, **options, &block)`
  - https://ruby-doc.org/stdlib-2.5.0/libdoc/csv/rdoc/CSV.html#method-c-foreach

**Comment by dbroudy** [comment]
Yeah, that resolves my issue. Thanks Josh!

**Comment by spesic** [comment]
I'm still experiencing this with Ruby 2.5 and fastlane 2.94.0... Was there a PR for this?

**Comment by joshdholtz** [comment]
@spesic Not yet but will look into next week 👌 I will reopen this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
