### ISSUE TITLE
Prompts inconsistently require pressing 'Enter'

### ISSUE THREAD

**Issue by diakonos** [fastlane/fastlane#12412]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Some prompts require you to enter input and then press 'Enter', and others just require you to enter 'y' or 'n' and will continue without you pressing 'Enter'. This caused me some confusion when running `fastlane init` today because it was the first time using fastlane on this machine, so I needed to go through the full setup process. I had to enter my Apple ID (type it and press 'Enter'), then select my iTunes Connect team (enter the team number and press 'Enter'), but when it detected that the app did not exist in the Developer Portal or iTunes Connect, it asked me whether I wanted to create them. I typed 'y' and pressed 'Enter', but it kept failing because it would read that 'Enter' as my response to the prompt for the App Name. So, it would keep trying to create an app with an empty name.

I think it'd probably be more consistent to require an 'Enter' after all prompts.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>MacBook-Pro-2:ios justin$ fastlane init
...output
[14:35:49]: Checking if the app 'com.xxxxxx.xxxxxx' exists in your Apple Developer Portal...
[14:35:50]: It looks like the app 'com.xxxxxx.xxxxxx' isn't available on the Apple Developer Portal
[14:35:50]: for the team ID 'xxxxxx' on Apple ID 'xxxxxx@gmail.com'
[14:35:50]: Do you want fastlane to create the App ID for you on the Apple Developer Portal? (y/n)
y

+----------------+--------------------------+
|        Summary for produce 2.93.1         |
+----------------+--------------------------+
| username       | xxxxxx@gmail.com        |
| team_id        | xxxxxx               |
| itc_team_id    | xxxxxx                   |
| platform       | ios                      |
| app_identifier | com.xxxxxx.xxxxxx |
| skip_itc       | true                     |
| sku            | xxxxxx               |
| language       | English                  |
| skip_devcenter | false                    |
+----------------+--------------------------+

[14:35:55]: App Name: [14:35:55]: Creating new app '' on the Apple Dev Center
[14:35:56]: ["Apple provided the following error info:", "There were errors in the data supplied. Please correct and re-submit.", "No value was provided for the parameter 'appIdName'."]
[14:35:56]: It looks like something went wrong when we tried to create your app on the Apple Developer Portal
[14:35:56]: Would you like to try again (y)? If you enter (n), fastlane will fall back to the manual setup (y/n)
...output</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "xxxxxx.xcodeproj")
    build_app(scheme: "xxxxxx")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("BUNDLE_ID") # The bundle identifier of your app
apple_id("APPLE_ID") # Your Apple email address

itc_team_id("ITC_TEAM_ID") # iTunes Connect Team ID
team_id("DEV_TEAM_ID") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.93.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.1        |
</details>

*generated on:* **2018-04-30**
</details>

**Comment by joshdholtz** [comment]
@diakonos Heyyy 👋 Thanks for feedback! I can totally see where you are coming from here. We definitely like to have things consistent and _fastlane_ can have a lot of user interaction and we like to make it as easy to use for everyone 😊  

TBH, at first I was gunna be like "I think things are fine" but the more I thought about it the more I think this has actually happened to me 🤔 

The fix _would_ be to remove the `true` parameter on this line - https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L134

I'm a bit hesitant to make this change (even though easy) as this changes **a lot** of behavior (since a lot of tools use this) for a lot of people. It definitely isn't a change that could "break" things but it does offer a different user experience. Imma let this one simmer in my mind for a bit 💭

**Comment by diakonos** [comment]
Totally understand the concern! It's actually somewhat odd, because I've used fastlane on and off for years and don't remember noticing this. I don't think I've ever gone through this exact scenario where I was setting up fastlane before the app had been created in iTunes Connect yet, but I imagine I must've run across the y/n questions at some point. Pressing 'Enter' afterwards doesn't always have this effect though, depending on if there is another prompt and what it is.

I can definitely see this going both ways, since I guess there is a small speed / convenience benefit for y/n questions if you don't have to press 'Enter', as well as not wanting to impact everyone.

Thanks for taking the time to consider the suggestion!
