### ISSUE TITLE
xcodebuild action with $(inherited) build_setting runs bash subcommand

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#12418]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Adding a `build_setting` with `$(inherted)` runs a bash subcommand with `inherited` instead of emitting a literal `$(inherited)` string.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

For privacy reasons, I can't include the full `fastlane env` output, but here are my installed gems:

<details>
  <pre>
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.93.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| slack-notifier            | 2.3.2       |
| atomos                    | 0.1.2       |
| CFPropertyList            | 2.3.3       |
| claide                    | 1.0.2       |
| colored2                  | 3.1.2       |
| nanaimo                   | 0.2.5       |
| xcodeproj                 | 1.5.7       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| plist                     | 3.1.0       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| public_suffix             | 2.0.4       |
| tty-screen                | 0.6.4       |
| tty-cursor                | 0.5.0       |
| tty-spinner               | 0.8.0       |
| babosa                    | 1.0.2       |
| colored                   | 1.2         |
| highline                  | 1.7.8       |
| commander-fastlane        | 4.4.6       |
| excon                     | 0.45.4      |
| unf_ext                   | 0.0.7.1     |
| unf                       | 0.1.4       |
| domain_name               | 0.5.25      |
| http-cookie               | 1.0.2       |
| faraday-cookie_jar        | 0.0.6       |
| fastimage                 | 2.1.0       |
| gh_inspector              | 1.1.2       |
| mini_magick               | 4.5.1       |
| multi_json                | 1.11.2      |
| multi_xml                 | 0.5.5       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| bundler                   | 1.12.5      |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| naturally                 | 2.1.0       |
| simctl                    | 1.6.4       |
| uber                      | 0.0.15      |
| declarative               | 0.0.9       |
| declarative-option        | 0.1.0       |
| representable             | 3.0.4       |
| retriable                 | 2.1.0       |
| addressable               | 2.5.1       |
| mime-types-data           | 3.2016.0221 |
| mime-types                | 3.0         |
| little-plugger            | 1.1.4       |
| logging                   | 2.0.0       |
| jwt                       | 1.5.2       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.2       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.3       |
| google-api-client         | 0.13.6      |
| emoji_regex               | 0.1.1       |
| libxml-ruby               | 2.6.0       |
| json                      | 1.8.3       |
</details></pre></details>

And here is the error in question:
```
[17:23:33]: ------------------------
[17:23:33]: --- Step: xcodebuild ---
[17:23:33]: ------------------------
[17:23:33]: For a more detailed xcodebuild log open ./fastlane/logs/xcodebuild//xcodebuild.log
[17:23:33]: $ set -o pipefail && xcodebuild build GCC_PREPROCESSOR_DEFINITIONS="$(inherited) FOO=1" -configuration "Release" -destination "platform=iOS Simulator,OS=latest,name=iPhone 6s Plus" -scheme "FooKit" -workspace "Foo.xcworkspace" -sdk iphonesimulator | tee './fastlane/logs/xcodebuild//xcodebuild.log' | xcpretty --no-utf --simple
[17:23:33]: ▸ sh: inherited: command not found
```

**Comment by joshdholtz** [comment]
@hborders Can you paste a copy of your `Fastfile` so I can see a bit more and try to replicate it? 😊

**Comment by hborders** [comment]
Sorry, I can't post the actual `Fastfile`, but here's a relevant anonymized lane.
```
  desc "Build Foo"
  lane :build_foo do
    xcodebuild(
      build: true,
      buildlog_path: "./fastlane/logs/xcodebuild/",
      build_settings: {
        # fastlane wraps these settings in double-quotes, rather than single-quotes.
        # Thus, bash will attempt to process $(inherited) as a command substitution, which produces:
        # > -bash: inherited: command not found
        # We inject a backslash in front of $ to prevent this.
        # fastlane issue: https://github.com/fastlane/fastlane/issues/12418
        'GCC_PREPROCESSOR_DEFINITIONS'                      => '\\$(inherited) NDEBUG=1',
      },
      configuration: "Release",
      destination: "platform=iOS Simulator,OS=latest,name=iPhone 6s Plus",
      output_style: :basic,
      scheme: "Foo",
      workspace: "Foo.xcworkspace",
      xcargs: "-sdk iphonesimulator",
    )
  end
```
