### ISSUE TITLE
Have no swift Document

### ISSUE THREAD

**Issue by YTF-CD** [fastlane/fastlane#12434]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.3.5                           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    func betaLane() {
        desc("Submit a new Beta Build to Apple TestFlight. This will also make sure the profile is up to date")
        
        syncCodeSigning(gitUrl: "URL/for/your/git/repo", appIdentifier: [appIdentifier], username: appleID)
        // Build your app - more options available
        buildIosApp(scheme: "SchemeName")
        uploadToTestflight(username: appleID)
        // You can also use other beta testing services here (run `fastlane actions`)
    }}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.94.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| nanaimo                   | 0.2.5        |
| unicode-display_width     | 1.3.2        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| dotenv                    | 2.4.0        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-05-02**
</details>

################After run "fastlane init swift" and A mistake has occurred.###################################
open': [!] [Xcodeproj] Unable to open `/Users/iamdzz/Desktop/Demo/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` because it doesn't exist. (RuntimeError)

**Comment by joshdholtz** [comment]
@YTF-CD Do you happen have the full output from when you ran this that you can share? That would provide us with more information to help you with 😊

**Comment by alfazeeweb** [comment]
I have the same issue:
Following are the logs:

Chanchals-MacBook-Pro:cartuneios chanchalraj$ fastlane beta
[✔] 🚀 
[02:47:29]: fastlane detected a Gemfile in the current directory
[02:47:29]: however it seems like you don't use `bundle exec`
[02:47:29]: to launch fastlane faster, please use
[02:47:29]: 
[02:47:29]: $ bundle exec fastlane beta
[02:47:29]: 
[02:47:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[02:47:30]: loading manifest: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/swift/upgrade_manifest.json
[02:47:30]: [Xcodeproj] Unable to open `/Users/chanchalraj/cartuneios/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` because it doesn't exist.
[02:47:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:100:in `open': [!] [Xcodeproj] Unable to open `/Users/chanchalraj/cartuneios/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` because it doesn't exist. (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:38:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/swift_lane_manager.rb:258:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/swift_lane_manager.rb:258:in `ensure_runner_up_to_date_fastlane!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/swift_lane_manager.rb:32:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by Jaydeepvadalia** [comment]
Getting same problem
