### ISSUE TITLE
deliver download_screenshots weird naming

### ISSUE THREAD

**Issue by pvinis** [fastlane/fastlane#12438]
why are the names like `1_iphone6_1`? why do we need the sordOrder twice?
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/download_screenshots.rb#L19

**Comment by pvinis** [comment]
it's not needed fastlane-bot. thanks though :)

**Comment by pvinis** [comment]
an answer would be nice. unless Boone knows and we can simplify?

**Comment by pvinis** [comment]
maybe I can do a pr to make it simpler.

**Comment by janpio** [comment]
This actually looks a bit like a bug. Before a rewrite 3 years ago, it looked like this:
https://github.com/fastlane/fastlane/blob/6023cf252e487c8836ca06fb854f0cd2f99464ee/lib/deliver/download_screenshots.rb#L18

Which was then changed to this:
https://github.com/fastlane/fastlane/blob/7319398ccd84e34e70d3a964f211244251946743/deliver/lib/deliver/download_screenshots.rb#L19-L21
in this commit: https://github.com/fastlane/fastlane/commit/181df092e92f5719613fbaa26d940941e9e55af6

Probably the new ITC mentioned in the commit message didn't include a useful original_file_name any more (Do you maybe remember @KrauseFx?) and while changing that, the sort order snuck in twice.

I think it would be great if you could create a PR @pvinis.

**Comment by janpio** [comment]
`File.basename` also doesn't return the extension, as the code implies - it return everything behind the last folder separator (`/`) which causes strange filenames like this:

`1_iphone6Plus_1.ftl_403370b4ce0bf506dd2a492c323b4386_08e7e94336e2a3494e12589e0facdcd3.png`

**Comment by janpio** [comment]
These super strange filenames when downloading seem to be from a specific era, recent screenshots have their nice filenames again like `3_ipadPro_3.iPad Pro (12.9-inch)-2-details.png`.
