### ISSUE TITLE
Snapshot hangs and workaround

### ISSUE THREAD

**Issue by StuSchwartz** [fastlane/fastlane#12435]
I was having issues of Snapshot hanging for me. I saw a few issues also referring to this as well from back in 2016. 

I am still seeing this hang in 2018, but I was able to get past this and wanted to pass on what I observed.

At first I thought it was concurrent_simulators being true, so I disabled that and it still hung. 

Since I was doing multiple languages I then enabled localize_simulator and the hanging stopped.

I then tried reenabling concurrent_simulators and there was still no hanging.

I have not seen any hanging since then

So looks like the hang has something to do with localize_simulator being disabled.

**Comment by lolgear** [comment]
@StuSchwartz 
Do you really need snapshots in Xcode 9?

**Comment by StuSchwartz** [comment]
Why wouldn't you need screenshots in Xcode 9?

**Comment by lolgear** [comment]
@StuSchwartz 

Xcode 9 has native screenshots, just use them instead.

**Comment by StuSchwartz** [comment]
I was not looking to take a single snapshot I was running capture_screenshots to capture all my screenshots, then run frameit.

**Comment by lolgear** [comment]
@StuSchwartz 

[What's New in Testing, session 409, WWDC 2017](https://developer.apple.com/videos/play/wwdc2017/409/)

Look at 30:00
