### ISSUE TITLE
Clarification on `match nuke`

### ISSUE THREAD

**Issue by startupthekid** [fastlane/fastlane#12446]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I work on an enterprise signed application that is also distributed via Fabric using an adhoc distribution certificate. I'm in the process of moving all signing over to use match and I had a question about running the `nuke` commands. Running `fastlane match nuke development` was straightforward and easy; I was able to clear everything out without any trouble. The next step is to run `fastlane match nuke distribution` to clear out the adhoc certificates used to distribute to fabric but _*NOT*_ the enterprise certificate. 

When I run `fastlane match nuke distribution`:

```
[12:21:53]: ---
[12:21:53]: ⚠️ Warning: This seems to be an Enterprise account!
[12:21:53]: By nuking your account's distribution, all your apps deployed via ad-hoc will stop working!
[12:21:53]: ---
[12:21:53]: Do you really want to nuke your Enterprise account? (y/n)
n

[!] Enterprise account nuke cancelled
```

The verbiage here is a bit confusing; am I nuking my entire Enterprise account or just the adhoc certificates that are using only for beta deployment? I can also run `fastlane match nuke enterprise` which I'm assuming gets rid of distribution certs only for enterprise but seeing as this is a very destructive action, I wanted to double check.

My questions are:
- does running `fastlane match nuke distribution` only clear out adhoc certs?
- how does this affect push notification certificates?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.3.6                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.rbenv/versions/2.3.6/bin/fastlane        |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.6/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("doordash.DoorDashDriverApp")
apple_id("admin@doordash.com")
team_id("E4W8JP9HX2")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.94.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| excon                     | 0.61.0       |
</details>

*generated on:* **2018-05-03**
</details>

**Comment by RishabhTayal** [comment]
@startupthekid if I am not mistaken, `fastlane match nuke distribution` should remove your ad-hoc and appstore profiles. If you want to clear the enterprise certificates and profiles you should use `fastlane match nuke enterprise`. 

`match nuke` doesn't clears out the push notification certificates. It's only for signing certificate and provisioning profiles.

Refer to [the nuke docs](https://docs.fastlane.tools/actions/sync_code_signing/#nuke) for more details.

**Comment by joshdholtz** [comment]
@startupthekid You have a great question here! `match` works a bit weird for adhoc enterprise and you may be another weird message after you say "yes" to the above 😊

1) `fastlane match nuke distribution` will clear out adhoc certs and profiles
2) This won't affect push notifications at all 👌 Push notifications are handle completely separately
3) After you would say "yes" to the above (and as long as you have didn't set `skip_confirmation: true`), you will get another confirmation of all the certs and profiles that will be nuked 💣 That way you can verify its not doing anything that you don't want it to do 😊

Happy nuking! 💥

**Comment by startupthekid** [comment]
That is super helpful! Thank you @joshdholtz and @RishabhTayal, that's exactly what I was looking for.
