### ISSUE TITLE
Fastlane swift functions don't return values

### ISSUE THREAD

**Issue by arnaudWasappli** [fastlane/fastlane#12445]
Hello, hope someone can help me.
I am using Fastlane with swift, but sometime function don't send me the supposed return value.

**Example**: 
latestTestflightBuildNumber should return an Integer.
The function seems to work but the return value is always 0.
Please see attachments

![buildnumberfunction](https://user-images.githubusercontent.com/7737273/39596789-80e22148-4ee1-11e8-84ef-7997ff9cd11d.png)
<img width="456" alt="buildnumberlogs" src="https://user-images.githubusercontent.com/7737273/39596794-845b1640-4ee1-11e8-9aa8-b88293510820.png">

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[14:36:27]: loading manifest: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/swift/upgrade_manifest.json
[14:36:27]: FastlaneSwiftRunner project is up-to-date
[14:36:27]: Successfully loaded '/Users/lala/Desktop/Projects/lala/fastlane/Gymfile' 📄

+---------------------+---------------------+
| Detected Values from './fastlane/Gymfile' |
+---------------------+---------------------+
| output_directory    | ./                  |
+---------------------+---------------------+

[14:36:27]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[14:36:28]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/alays/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[14:36:30]: $ ./fastlane/FastlaneRunner lane downloadCurrentDsym > /dev/null
[14:36:30]: --------------------------------------------
[14:36:30]: --- Step: latest_testflight_build_number ---
[14:36:30]: --------------------------------------------
[14:36:30]: Login to iTunes Connect (lala@help.com)
[14:36:32]: Login successful
[14:36:33]: Fetching the latest build number for version 2.15
[14:36:34]: Latest upload for version 2.15 is build: 129
[14:36:34]: build found 0 !!

+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 1    | latest_testflight_build_number | 3           |
+------+--------------------------------+-------------+

[14:36:34]: fastlane.tools finished successfully 🎉</pre>
</details>

### Environment

  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E199)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    
    func beforeAll() {
    }
    
    //////////////////////////////////////////
    // MARK: - // Build environment version //
    //////////////////////////////////////////
    
    //Build a version for DEV and send new build in Fabric
    func devLane() {
        desc("Send new version of LesPAC app in Dev")
        promptIncrementBuildVersion()
        
        let environment: Environment = .DEV
        
        let changelog: String = askChangeLog(for: environment)
        
        gym(scheme: environment.scheme, configuration: "Debug", silent: true, exportMethod: environment.exportMethod)
        
        uploadToCrashlytics(with: changelog, mode: environment.crashlyticsMode)
    }
    
    //Build a version for QA and send new build in Fabric
    func qaLane() {
        desc("Send new version of LesPAC app in QA")
        promptIncrementBuildVersion()
        
        let environment: Environment = .QA
        
        let changelog: String = askChangeLog(for: environment)
        
        gym(scheme: environment.scheme, configuration: "Release-QA", exportMethod: environment.exportMethod)
        
        uploadToCrashlytics(with: changelog, mode: environment.crashlyticsMode)
    }
    
    //Build a version for UserAcceptanceTest
    func uatLane() {
        desc("Send new version of LesPAC app in UserAcceptanceTest")
        promptIncrementBuildVersion()
        
        let environment: Environment = .UAT
        gym(scheme: environment.scheme, configuration: "Debug-UAT", exportMethod: environment.exportMethod)
    }
    
    //Build a version for PreProd
    func ppLane() {
        desc("Send new version of LesPAC app in PreProd")
        promptIncrementBuildVersion()
        
        let environment: Environment = .PP
        gym(scheme: environment.scheme, configuration: "Debug-PP", exportMethod: environment.exportMethod)
    }
    
    //Build a version for Production and send new build to TestFlight
    func prodLane() {
        desc("Send new version of LesPAC app in Production")
        promptIncrementBuildVersion()
        
        let environment: Environment = .PROD
        gym(scheme: environment.scheme, configuration: "Release", exportMethod: environment.exportMethod)
        
        uploadToTestFlight()
    }
    
    ///////////////////////////////////////
    // MARK: - // Increment build number //
    ///////////////////////////////////////
    
    func incrementLane() {
        promptIncrementBuildVersion()
    }
    
    ////////////////////////////
    // MARK: - // Upload dSYM //
    ////////////////////////////
    
    //Download dSYM from iTunesConnect and the upload to Fabric
    func dsymLane() { //Shortcut function for uploadDSymToFabricLane
        uploadDSymToFabricLane()
    }
    
    func uploadDSymToFabricLane() {
        uploadDSymToFabric()
    }
    
    //Upload local dsym to Fabric (with a local path of a dSYM or a dSYM.zip)
    func localdsymLane() { //Shortcut function for uploadLocalDSymToFabricLane
        uploadLocalDSymToFabricLane()
    }
    
    func uploadLocalDSymToFabricLane() {
        let dsymPath = prompt(text: "Enter the path of the DSYM you want to upload?")
        uploadDSymToFabric(dsymPath: dsymPath)
    }
    
    //Download dSYM from iTunesConnect
    func downloadDsymLane() {
        downloadDsym()
    }
    
    func getCurrentBuildNumberLane() {
        let buildNumber = latestTestflightBuildNumber(appIdentifier: Configuration.appIdentifier,
                                                      username: Configuration.username,
                                                      teamId: Configuration.teamID)
        println(message: "build found \(buildNumber) !!")
        //        downloadDsyms(username: Configuration.username, appIdentifier: Configuration.appIdentifier, teamName: Configuration.teamName, buildNumber: "\(buildNumber)", outputDirectory: Constants.dsymFolder)
    }
}

//MARK: Private helper methods
extension Fastfile {
    
    private func promptIncrementBuildVersion() {
        let incrementAutomatic = prompt(text: "Do you want to increment build version automatically? (y/n)")
        var buildVersion: String?
        if incrementAutomatic == "true" || incrementAutomatic == "y" || incrementAutomatic == "1" || incrementAutomatic == "yes" {
            if let bNumber = Int(getBuildNumber()) {
                buildVersion = "\(bNumber + 1)"
            }
        } else {
            buildVersion = prompt(text: "Write build version:")
        }
        let buildNumber = incrementBuildNumber(buildNumber: buildVersion != nil ? buildVersion! : nil)
        println(message: "✅ new build version: \(buildNumber) ✅")
    }
    
    private func askChangeLog(for environment: Environment) -> String {
        let userChangeLog: String = prompt(text: "Changelog: ", multiLineEndKeyword: "END")
        return environment.headerChangeLog + userChangeLog
    }
    
    private func uploadToCrashlytics(with notes: String, mode: CrashlyticsMode = .test, testGroups: [UserTestGroup] = [.DEV, .QA]) {
        
        assert(testGroups.count > 0, "Please use at least one test group")
        let groups: String = testGroups.map({ $0.rawValue }).joined(separator: ",")
        
        crashlytics(apiToken: mode.apiToken,
                    buildSecret: mode.secret,
                    notes: notes,
                    groups: groups,
                    notifications: true)
    }
    
    private func uploadToTestFlight() {
        //TODO: implement uploadToTestFlight
        uploadToTestflight(username: Configuration.username, appIdentifier: Configuration.appIdentifier, appleId: Configuration.appleID, teamId: Configuration.teamID, teamName: Configuration.teamName)
    }
    
    private func uploadDSymToFabric(dsymPath: String? = nil) {
        var path: String = ""
        if let dsymPath = dsymPath {
            path = dsymPath
        } else {
            let build = downloadDsym()
            path = "\(Constants.dsymFolder)/\(Configuration.appIdentifier)\(build.buildName).dSYM.zip"
        }
        uploadSymbolsToCrashlytics(dsymPath: path, apiToken: CrashlyticsMode.prod.apiToken)
        cleanBuildArtifacts()
    }
    
    @discardableResult private func downloadDsym() -> Build {
        var build: Build = Build()
        
        let version = prompt(text: "Which build version do you want to download dSYM? (ex: \(build.version))")
        if !version.isEmpty {
            build.version = version
        }
        let buildNumber = prompt(text: "Which build number do you want? (ex: \(build.number))")
        if !buildNumber.isEmpty {
            build.number = buildNumber
        }
        
        latestTestflightBuildNumber(appIdentifier: Configuration.appIdentifier, username: Configuration.username)
        downloadDsyms(username: Configuration.username, appIdentifier: Configuration.appIdentifier, teamName: Configuration.teamName, version: build.version, buildNumber: build.number, outputDirectory: Constants.dsymFolder)
        
        return build
    }
}

extension Fastfile {
    struct Constants {
        static let dsymFolder: String = "fastlane/.dsyms"
    }
}

struct Build {
    var version: String
    var number: String
    
    init() {
        version = getVersionNumber()
        number = getBuildNumber()
    }
    
    var buildName: String {
        return "-\(version)-\(number)"
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.94.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-05-03**
</details>
</pre>

**Comment by arnaudWasappli** [comment]
Sorry bot, don't know why no one seems interested by my issue

**Comment by iozz** [comment]
I have the same problem with other functions such as `prompt()`, I can't get the return value either...
