### ISSUE TITLE
[Regression] fastlane pilot list broken 

### ISSUE THREAD

**Issue by vorti2** [fastlane/fastlane#12441]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### If I run the command 
```
bundle exec fastlane pilot list -u <Apple ID> -a <app identifier>
```
the output is:
```
[15:31:20]: Login to iTunes Connect (<Apple ID>)
[15:31:23]: Login successful

[!] Couldn't find app with '<Apple ID>'
```
Otherwise I can handle the app with the app identifier `<app identifier>` via fastlane.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.94.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-05-03**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@vorti2 What version did this last work for you?

**Comment by joshdholtz** [comment]
@vorti2 This works for me 🙃 Can you run `bundle exec fastlane pilot list -u <Apple ID> -a <app identifier> --verbose` and paste the output?

**Comment by vorti2** [comment]
I mean in one of the previous versions 😉, but I am not sure 

Here is the output: 

```
> bundle exec fastlane pilot list -u <Apple ID> -a <app identifier> --verbose
Successfully loaded Appfile at path '<App path>/fastlane/Appfile'
- itc_team_id: '<ITC team ID>'
- team_id: ''
-------
Successfully loaded Appfile at path '<App path>/fastlane/Appfile'
- itc_team_id: '<ITC team ID>'
- team_id: '<team ID>'
-------
Successfully loaded Appfile at path '<App path>/fastlane/Appfile'
- itc_team_id: '<ITC team ID>'
- team_id: '<team ID>'
-------
Successfully loaded Appfile at path '<App path>/fastlane/Appfile'
- itc_team_id: '<ITC team ID>'
- team_id: '<team ID>'
-------
Successfully loaded Appfile at path '<App path>/fastlane/Appfile'
- itc_team_id: '<ITC team ID>'
- team_id: '<team ID>'
-------
Successfully loaded Appfile at path '<App path>/fastlane/Appfile'
- itc_team_id: '<ITC team ID>'
- team_id: '<team ID>'
-------
INFO [2018-05-03 15:48:55.28]: Login to iTunes Connect (<Apple ID>)
Loading session from '<User Path>/.fastlane/spaceship/appledev@v-software.de/cookie'
Looking for iTunes Connect Team with ID <ITC team ID>
INFO [2018-05-03 15:48:59.18]: Login successful
<User Path>.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!': [!] Couldn't find app with '<Apple ID>' (FastlaneCore::Interface::FastlaneError)
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/pilot/lib/pilot/tester_manager.rb:163:in `list_testers_by_app'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/pilot/lib/pilot/tester_manager.rb:92:in `list_testers'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/pilot/lib/pilot/commands_generator.rb:114:in `block (2 levels) in run'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from<User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from <User Path>o/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from <User Path>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.94.0/bin/fastlane:20:in `<top (required)>'
	from <User Path>/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from <User Path>/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by vorti2** [comment]
Or should I delete the cookie?

**Comment by joshdholtz** [comment]
@vorti2 What login method are you using? Are you using 2FA?

**Comment by joshdholtz** [comment]
But yeah, I would suggest either 1) Deleting the cookie / password in keychain 2) Try temporarily renaming `Appfile` to make sure settings in there aren't doing anything weird with this pilot command

**Comment by joshdholtz** [comment]
@vorti2 What role do you have on the iTunesConnect team?

**Comment by gyant-travis** [comment]
I am `Admin` on this iTunesConnect team.

**Comment by vorti2** [comment]
I am `Admin` on this iTunesConnect team.

**Comment by joshdholtz** [comment]
@vorti2 This is _really_ strange 🤔 The `list` command totally works for me on `2.94.0` and I am also `Admin` on my account.

Does the `Looking for iTunes Connect Team with ID <ITC team ID>` display the same team id for your `builds` and `list` command? I don't know why they wouldn't but just another thing to look into since I can't be on your computer to debug this 😉

**Comment by vorti2** [comment]
team id is the same ... 

I have executed  the `fastlane pilot builds` command with the `--verbose` parameter and the line 
```
DEBUG [2018-05-03 17:12:06.66]: App identifier (<app identifier>)
```
seems to be the "baddie". Should not that also exist in the command `fastlane pilot list ...`?

**Comment by joshdholtz** [comment]
@vorti2 Question! The `[!] Couldn't find app with '<Apple ID>'` output you originally had. Was this the "bundle identifier" that you passed in? Or was this the "app ID" that iTunesConnect gives your app? I _THINK_ I may have a hunch
