### ISSUE TITLE
can not open fastlane doc

### ISSUE THREAD

**Issue by EvilWizarder** [fastlane/fastlane#12447]
can not open fastlane doc recently https://docs.fastlane.tools

**Comment by joshdholtz** [comment]
@EvilWizarder Can you provide any more information? What kind of browser? What OS? Are you behind some kind of firewall that could be blocking it? Also, this issue should be created at https://github.com/fastlane/docs so I'm going to close this here 😊 Feel free to open one over there if you can't get it to load still
