### ISSUE TITLE
Update_price_tier is not working anymore

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#12444]
When I have tried to change the price,  Spaceship throw an error related to pre-order feature

```
7] pry(#<Spaceship::Playground>)> availability.cleared_for_preorder
=> false
[38] pry(#<Spaceship::Playground>)> app = Spaceship::Tunes::Application.find("io.transporterapp.deep.test1")
=> <Spaceship::Tunes::Application 
	apple_id="1242385799", 
	name="App Keyword Finder Tool", 
	vendor_id="io.transporterapp.deep.test1", 
	bundle_id="io.transporterapp.deep.test1", 
	last_modified=1525366680000, 
	issues_count=0, 
	app_icon_preview_url="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/dd/ea/f2/ddeaf2c2-6059-b00d-f1fb-ee9f3077fb2f/AppIcon-1x_U007emarketing-85-220-0-5.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
[39] pry(#<Spaceship::Playground>)> app.update_price_tier!(3)
```

Error

```
Spaceship::Tunes::Error: Your app must be marked as cleared for pre-order to modify available date.
from /Users/bolo/.rvm/gems/ruby-2.5.0/bundler/gems/fastlane-960b4e82261b/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response'

```

**Comment by bolom** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13.4                              |
| Ruby                        | 2.5.0                                |
| Bundler?                    | true                                 |
| Git                         | git version 2.15.1 (Apple Git-101)   |
| Installation Source         | ~/.rvm/gems/ruby-2.5.0/bin/fastlane  |
| Host                        | Mac OS X 10.13.4 (17E199)            |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.0/lib         |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.94.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version         |
| ------------------------- | --------------- |
| did_you_mean              | 1.2.0           |
| executable-hooks          | 1.4.2           |
| bundler-unload            | 1.0.2           |
| rubygems-bundler          | 1.4.4           |
| bundler                   | 1.16.1          |
| fileutils                 | 1.0.2           |
| rake                      | 12.3.1          |
| CFPropertyList            | 2.3.6           |
| concurrent-ruby           | 1.0.5           |
| i18n                      | 1.0.1           |
| minitest                  | 5.10.1          |
| thread_safe               | 0.3.6           |
| tzinfo                    | 1.2.5           |
| activesupport             | 5.2.0           |
| builder                   | 3.2.3           |
| erubi                     | 1.7.1           |
| mini_portile2             | 2.3.0           |
| nokogiri                  | 1.8.2           |
| rails-dom-testing         | 2.0.3           |
| crass                     | 1.0.4           |
| loofah                    | 2.2.2           |
| rails-html-sanitizer      | 1.0.4           |
| actionview                | 5.2.0           |
| rack                      | 2.0.5           |
| rack-test                 | 1.0.0           |
| actionpack                | 5.2.0           |
| nio4r                     | 2.3.1           |
| websocket-extensions      | 0.1.3           |
| websocket-driver          | 0.7.0           |
| actioncable               | 5.2.0           |
| globalid                  | 0.4.1           |
| activejob                 | 5.2.0           |
| mini_mime                 | 1.0.0           |
| mail                      | 2.7.0           |
| actionmailer              | 5.2.0           |
| activemodel               | 5.2.0           |
| arel                      | 9.0.0           |
| activerecord              | 5.2.0           |
| mimemagic                 | 0.3.2           |
| marcel                    | 0.3.2           |
| activestorage             | 5.2.0           |
| public_suffix             | 2.0.5           |
| addressable               | 2.5.2           |
| airbrake-ruby             | 2.10.0          |
| airbrake                  | 7.3.0           |
| highline                  | 1.7.10          |
| commander                 | 4.4.4           |
| analytics-ruby            | 2.2.5           |
| atomos                    | 0.1.2           |
| encryptor                 | 3.0.0           |
| attr_encrypted            | 3.1.0           |
| execjs                    | 2.7.0           |
| autoprefixer-rails        | 8.4.1           |
| aws-sigv4                 | 1.0.2           |
| jmespath                  | 1.4.0           |
| aws-sdk-core              | 2.11.42         |
| aws-sdk-resources         | 2.11.42         |
| aws-sdk                   | 2.11.42         |
| babosa                    | 1.0.2           |
| bcrypt                    | 3.1.11          |
| benchmark-ips             | 2.7.2           |
| bindex                    | 0.5.0           |
| byebug                    | 10.0.2          |
| xpath                     | 3.0.0           |
| capybara                  | 3.0.3           |
| capybara-email            | 3.0.1           |
| mime-types-data           | 3.2016.0521     |
| mime-types                | 3.1             |
| carrierwave               | 1.2.2           |
| excon                     | 0.62.0          |
| formatador                | 0.2.5           |
| fog-core                  | 1.45.0          |
| multi_json                | 1.13.1          |
| fog-json                  | 1.0.2           |
| ipaddress                 | 0.8.3           |
| xml-simple                | 1.1.5           |
| fog-aliyun                | 0.2.1           |
| fog-xml                   | 0.1.3           |
| fog-atmos                 | 0.1.0           |
| fog-aws                   | 2.0.1           |
| inflecto                  | 0.0.2           |
| fog-brightbox             | 0.14.0          |
| fog-cloudatcost           | 0.1.2           |
| fog-digitalocean          | 0.3.0           |
| fog-dnsimple              | 1.0.0           |
| fog-dynect                | 0.0.3           |
| fog-ecloud                | 0.3.0           |
| fog-google                | 0.1.0           |
| fog-internet-archive      | 0.0.1           |
| fog-joyent                | 0.0.1           |
| fog-local                 | 0.5.0           |
| fog-openstack             | 0.1.25          |
| json                      | 2.1.0           |
| ovirt-engine-sdk          | 4.2.4           |
| unf_ext                   | 0.0.7.5         |
| unf                       | 0.1.4           |
| domain_name               | 0.5.20180417    |
| http-cookie               | 1.0.3           |
| netrc                     | 0.11.0          |
| rest-client               | 2.0.2           |
| rbovirt                   | 0.1.5           |
| fog-ovirt                 | 1.0.3           |
| fog-powerdns              | 0.1.1           |
| fog-profitbricks          | 4.1.1           |
| fog-rackspace             | 0.1.5           |
| fog-radosgw               | 0.0.5           |
| fog-riakcs                | 0.1.0           |
| fog-sakuracloud           | 1.7.5           |
| fog-serverlove            | 0.1.2           |
| fog-softlayer             | 1.1.4           |
| fog-storm_on_demand       | 0.1.1           |
| fog-terremark             | 0.1.0           |
| fission                   | 0.5.0           |
| fog-vmfusion              | 0.1.0           |
| fog-voxel                 | 0.1.0           |
| trollop                   | 2.1.2           |
| rbvmomi                   | 1.12.0          |
| fog-vsphere               | 2.1.1           |
| fog-xenserver             | 0.3.0           |
| fog                       | 2.0.0           |
| uuidtools                 | 2.1.5           |
| carrierwave_direct        | 0.0.15          |
| ffi                       | 1.9.23          |
| childprocess              | 0.9.0           |
| choice                    | 0.2.0           |
| claide                    | 1.0.2           |
| method_source             | 0.9.0           |
| thor                      | 0.20.0          |
| railties                  | 5.2.0           |
| jquery-rails              | 4.3.3           |
| regexp_parser             | 0.5.0           |
| js_regex                  | 2.2.1           |
| sprockets                 | 3.7.1           |
| sprockets-rails           | 3.2.1           |
| rails                     | 5.2.0           |
| client_side_validations   | 11.1.2          |
| climate_control           | 0.2.0           |
| cliver                    | 0.3.2           |
| clockwork                 | 2.0.3           |
| coderay                   | 1.1.2           |
| coffee-script-source      | 1.12.2          |
| coffee-script             | 2.4.1           |
| coffee-rails              | 4.2.2           |
| colored                   | 1.2             |
| colored2                  | 3.1.2           |
| commander-fastlane        | 4.4.6           |
| connection_pool           | 2.2.1           |
| i18n_data                 | 0.8.0           |
| money                     | 6.11.2          |
| sixarm_ruby_unaccent      | 1.2.0           |
| unicode_utils             | 1.4.0           |
| countries                 | 2.1.4           |
| css_parser                | 1.6.0           |
| database_cleaner          | 1.7.0           |
| declarative               | 0.0.10          |
| declarative-option        | 0.1.0           |
| get_process_mem           | 0.2.1           |
| heapy                     | 0.1.3           |
| memory_profiler           | 0.9.10          |
| derailed_benchmarks       | 1.3.4           |
| derailed                  | 0.1.0           |
| orm_adapter               | 0.5.0           |
| responders                | 2.4.0           |
| warden                    | 1.2.7           |
| devise                    | 4.4.3           |
| devise_invitable          | 1.7.4           |
| docile                    | 1.3.0           |
| dotenv                    | 2.4.0           |
| dotenv-rails              | 2.4.0           |
| emoji_regex               | 0.1.1           |
| multipart-post            | 2.0.0           |
| faraday                   | 0.12.2          |
| faraday-cookie_jar        | 0.0.6           |
| faraday_middleware        | 0.12.2          |
| fastimage                 | 2.1.3           |
| gh_inspector              | 1.1.3           |
| jwt                       | 1.5.6           |
| little-plugger            | 1.1.4           |
| logging                   | 2.2.2           |
| memoist                   | 0.16.0          |
| os                        | 0.9.6           |
| signet                    | 0.8.1           |
| googleauth                | 0.6.2           |
| httpclient                | 2.8.3           |
| uber                      | 0.1.0           |
| representable             | 3.0.4           |
| retriable                 | 3.1.1           |
| google-api-client         | 0.13.6          |
| mini_magick               | 4.5.1           |
| multi_xml                 | 0.6.0           |
| plist                     | 3.4.0           |
| rubyzip                   | 1.2.1           |
| security                  | 0.1.3           |
| naturally                 | 2.1.0           |
| simctl                    | 1.6.4           |
| slack-notifier            | 2.3.2           |
| terminal-notifier         | 1.8.0           |
| unicode-display_width     | 1.3.2           |
| terminal-table            | 1.8.0           |
| tty-screen                | 0.6.4           |
| tty-cursor                | 0.5.0           |
| tty-spinner               | 0.8.0           |
| word_wrap                 | 1.0.0           |
| nanaimo                   | 0.2.5           |
| xcodeproj                 | 1.5.7           |
| rouge                     | 2.0.7           |
| xcpretty                  | 0.2.8           |
| xcpretty-travis-formatter | 1.0.0           |
| flamegraph                | 0.9.5           |
| font-awesome-rails        | 4.7.0.4         |
| gli                       | 2.17.1          |
| hashie                    | 3.5.7           |
| hiredis                   | 0.6.1           |
| immigrant                 | 0.3.6           |
| jbuilder                  | 2.7.0           |
| rb-fsevent                | 0.10.3          |
| rb-inotify                | 0.9.10          |
| sass-listen               | 4.0.0           |
| sass                      | 3.5.6           |
| jquery-fileupload-rails   | 0.4.7           |
| turbolinks-source         | 5.1.0           |
| turbolinks                | 5.1.1           |
| jquery-turbolinks         | 2.1.0           |
| ruby_dep                  | 1.5.0           |
| listen                    | 3.1.5           |
| mustermann                | 1.0.2           |
| oauth2                    | 1.4.0           |
| omniauth                  | 1.8.1           |
| omniauth-oauth2           | 1.3.1           |
| omniauth-github           | 1.1.2           |
| omniauth-google-oauth2    | 0.5.2           |
| omniauth-slack            | 2.3.0           |
| terrapin                  | 0.6.0           |
| paperclip                 | 6.0.0           |
| pg                        | 0.21.0          |
| poltergeist               | 1.18.0          |
| pry                       | 0.11.3          |
| puma                      | 3.11.4          |
| puma_worker_killer        | 0.1.0           |
| pundit                    | 1.1.0           |
| rack-cors                 | 1.0.2           |
| rack-mini-profiler        | 1.0.0           |
| rack-protection           | 2.0.1           |
| rack-proxy                | 0.6.4           |
| rack-throttle             | 0.5.0           |
| rails-assets-tether       | 1.4.3           |
| ruby-graphviz             | 1.2.3           |
| rails-erd                 | 1.5.2           |
| redis                     | 3.3.5           |
| redis-namespace           | 1.6.0           |
| redis-classy              | 2.4.1           |
| redis-mutex               | 4.0.1           |
| redis-throttle            | 0.0.1           |
| roadie                    | 3.3.0           |
| roadie-rails              | 1.3.0           |
| roo                       | 2.7.1           |
| tilt                      | 2.0.8           |
| sass-rails                | 5.0.7           |
| s3_direct_upload          | 0.1.7           |
| sauce_whisk               | 0.1.0           |
| selenium-webdriver        | 3.11.0          |
| sidekiq                   | 5.1.3           |
| sidekiq-unique-jobs       | 5.0.10          |
| simple_segment            | 0.3.0           |
| simplecov-html            | 0.10.2          |
| simplecov                 | 0.16.1          |
| sinatra                   | 2.0.1           |
| slack-ruby-client         | 0.11.1          |
| smarter_csv               | 1.2.3           |
| spring                    | 2.0.2           |
| spring-watcher-listen     | 2.0.1           |
| stackprof                 | 0.2.11          |
| stripe                    | 3.13.0          |
| sucker_punch              | 2.0.4           |
| to_words                  | 1.1.1           |
| web-console               | 3.6.2           |
| webpacker                 | 4.0.0.pre.pre.2 |
| whacamole                 | 1.2.0           |
| wicked_pdf                | 1.1.0           |
| wkhtmltopdf-binary        | 0.12.3.1        |
| wkhtmltopdf-heroku        | 2.12.4.0        |
</details>


*generated on:* **2018-05-04**
</details>

**Comment by joshdholtz** [comment]
@bolom I put a fix out for this! Can you test this to see if this fixes the issue for you? 😊 

## To Test This Change
Add the following to your Gemfile and then run `bundle install`
```rb
gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'joshdholtz-spaceship-delete-preOrder-update-price-tier'
```

**Comment by joshdholtz** [comment]
@bolom Glad to hear! Happy fastlaning 🚀
