### ISSUE TITLE
Check if VoIP certificate already exists

### ISSUE THREAD

**Issue by andrey-lisovskiy** [fastlane/fastlane#12463]
How can I check if VoIP certificate already created?

Foк certificate creation I am using next lane:

lane :make_voip_cert do
        output_path = ".."
        p12_password = "31415926"
        Spaceship.login("#{ENV['APPLE_ID']}")
        Spaceship.client.select_team
        csr, pkey = Spaceship::Certificate.create_certificate_signing_request
        cert = Spaceship::Certificate::VoipPush.create!(csr:csr,bundle_id:"co.synergetica.Synergy.develop")
        x509_certificate = cert.download
        certificate_type = "voippush"
        filename_base = "#{ENV['PEM_FILE_PREFIX']}_VoIP_XXX"
        p12_cert_path = File.join(output_path, "#{filename_base}.p12")
        p12 = OpenSSL::PKCS12.create(p12_password, certificate_type, pkey, x509_certificate)
        File.write(p12_cert_path, p12.to_der)
        x509_cert_path = File.join(output_path, "#{filename_base}.pem")
        File.write(x509_cert_path, x509_certificate.to_pem + pkey.to_pem)
    end

**Comment by heartofagoof** [comment]
First of all, I like the 8 digits of Pi password. :)

You can run through all distribution certificates and see if there are any that match the type. Something like this should work. 

```
Spaceship::Portal.login("","")
Spaceship::Portal.select_team
certs = Spaceship::Portal::Certificate::VoipPush.all()
if certs.length > 0
  voip_first = certs.first
end
```

Alternatively, you can store the certificate id somewhere and use that to retrieve the certificate - if you need it.

**Comment by andrey-lisovskiy** [comment]
Thanks a lot! One more question, how can I find specific certificate by name?

**Comment by andrey-lisovskiy** [comment]
Done with 
```
cert = Spaceship::Portal::Certificate::VoipPush.all().find do |certificate| certificate.owner_name == "app_bundle_id" end
        if cert.nil?
            ...
        end
```
