### ISSUE TITLE
SlackAction does not show message when attachment text exists.

### ISSUE THREAD

**Issue by lolgear** [fastlane/fastlane#12468]
It seems that slack API changed and message was renamed into text.

Try:

[Slack API](https://api.slack.com/docs/messages/builder)

```json
{
    "text": "I am a test message http://slack.com",
    "attachments": [
        {
            "text": "And here’s an attachment!"
        }
    ]
}
```

I send use it as:

```ruby
  def growl_to_team(options)
    slack(
      message: options[:message],
      default_payloads: [],
      attachment_properties: {
          text: options[:text]
      },
      use_webhook_configured_username_and_icon: true,
      success: options[:success] || true
      )
  end
```

There is no message, only attachment_properties[:text] in slack channel.

**Comment by lolgear** [comment]
Hm, it seems that fastlane ignore text in SlackAction:

```ruby
          results = notifier.ping('', link_names: link_names, icon_url: icon_url, attachments: [slack_attachment])
```

**Comment by joshdholtz** [comment]
@lolgear Made a PR for this ^

**Comment by lolgear** [comment]
@joshdholtz 
One notice about PR.

Why did this option have name 'pretext' instead of 'text'?
This option should mimic slack API, right?

**Comment by joshdholtz** [comment]
@lolgear This option is called `pretext` in the Slack API 😊 

https://github.com/fastlane/fastlane/pull/12472/files#diff-b1bdb034f6cb7f5c61224beb38e76fa9R192

**Comment by lolgear** [comment]
@joshdholz 

No, it does not. 

Please, check link to Slack API in first post. Text in outer json is not in attachment box in preview. Instead, it is appeared first “where you put pretext”.

**Comment by joshdholtz** [comment]
@lolgear Is this the end result you are looking for?

![screen shot 2018-05-08 at 7 29 04 am](https://user-images.githubusercontent.com/401294/39770412-94de65d6-52b4-11e8-9d69-95b46849fe90.png)

**Comment by lolgear** [comment]
@joshdholtz 
yes

**Comment by joshdholtz** [comment]
@lolgear Then this can be accomplished through `pretext` in my PR which is a legit Slack API property  😊 

https://api.slack.com/docs/message-attachments
![screen shot 2018-05-10 at 6 35 44 am](https://user-images.githubusercontent.com/401294/39867816-665d814c-541c-11e8-9d9a-1c05b823f805.png)
![screen shot 2018-05-10 at 6 35 12 am](https://user-images.githubusercontent.com/401294/39867796-52f3d8c2-541c-11e8-8213-e4d101463b7e.png)

**Comment by lolgear** [comment]
@joshdholtz 
I see.
We talk about different names (meanings?) of this property.
I talk about formal API field ( **text** ) and you talk about the intention of this field ( they call it **pretext** as on screen ).

However, I think that formal API field will be convenient for developers cause they could try it in Slack Web API Console.

I a bit confused when I can't find field **message** in slack api web console.
That is why I have opened this issue cause I don't understand words or do not (can not) see them on fastlane page.

I believe that all drivers ( or adapters ) should mimic formal APIs ( exceptions are C-APIs with bsdc_w narrow names ).

**Comment by joshdholtz** [comment]
@lolgear This action does not mimic the API directly. `message` is a custom parameter created in this action that adds the value of `message` into the first line of the attachment (which is why you are not finding it in the slack docs). 

I do not feel comfortable removing `message` because it serves it purposes and it would also break a lot of existing implemenationats that are already using this 🙃 

I could add a new parameter called `text` (which I think would also solve what you are looking for) but this "text" and "message" are too similar and I think would cause confusion 😖 

So I think the **best** solution would either to create a new parameter called `pretext` (or maybe `premessage`) that does what I showed/explained above 💯

**Comment by lolgear** [comment]
@joshdholtz 
Yes, I think about it. 
Some features are nice like "use profile picture from web", I don't even think about it, just put true.
But here I struggle with misunderstanding of what is going on.

Could you also add additional information for `message` parameter ( or even emphasize it by **bold**/_italic_/**_color_** ) that describes special purpose of it? ( It is not a parameter for Slack, it is parameter for Fastlane to use it in Slack ).

For example, you could add another possibility for user to choose between Slack API and Fastlane API here.
Suppose, that there is a key `:take_it_literally (slackally) => true` and it's value equals true.
Thus, I could assure myself that all parameters are delivered directly to Slack instead of custom Fastlane logic.

This ability could be implemented by using ( ah, the only way to use inheritance correctly ) inheritance. Choose between some `Strategy` classes or even `SlackAction` classes.

By the way,
Thanks for self-assigning #11750
