### ISSUE TITLE
Testflight does not send notification to users, sometimes.

### ISSUE THREAD

**Issue by csv8674xn** [fastlane/fastlane#12476]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After released to testflight, sometimes users do not get notifications. I am using fastlane 2.87.0, which works fine. However, sometimes when I submit a build to testflight, and release it, users do not get notification. This happened on last week, while yesterday I submitted another build it actually notified users. Please note that there's nothing changed on how I used fastlane between these two submissions. And neither of these two builds outputs errors. 

I wonder if there's a field in Apple's API that you specify whether to send out notification. I do not see an option to specify explicitly in fastlane for testflight though. I attached how I use fastlane(spaceship) in the detail section.
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
if use_build.beta_review_info.demo_account_name.nil?
  use_build.beta_review_info.demo_account_required = false
end

use_build.test_info.whats_new = whats_new
use_build.submit_for_testflight_review!

default_group = Spaceship::TestFlight::Group.default_external_group(app_id: use_build.app_id)
unless default_group.nil?
  use_build.add_group!(default_group)
end
</pre>
</details>

### Environment

<details>
</details>

**Comment by cjo666** [comment]
Were you able to find a solution to this?  We've been experiencing the same issue and we are on fastlane 2.96.1.  There seems to be about a 70% chance that Apple will not send the notifications.  Also, if I login to Itunes Connect and go to the Testflight tab it will immediately send the notifications.

**Comment by exevil** [comment]
@csv8674xn, @cjo666: Any solutions, guys?

**Comment by csv8674xn** [comment]
Honestly, we haven't figured it out. It does seem to have a glitch from time to time. But the success rate is more than 60% I would say.
