### ISSUE TITLE
Support uploading Android app bundles

### ISSUE THREAD

**Issue by eygraber** [fastlane/fastlane#12478]
[Android app bundles](https://developer.android.com/guide/app-bundle/build) were announced today at Google IO.

One of the sessions mentioned that the publisher API will have support for this. 

It would be cool if an option was added to `upload_to_play_store` to support this.

**Comment by eygraber** [comment]
This is a feature request ☝️

**Comment by joshdholtz** [comment]
@eygraber Thanks for the feature request! I started to implement `.aab` support today but looks like we are held back by https://github.com/google/google-api-ruby-client until `.aab` support is added there 🙃 We will get this updated as soon as we can 💪

**Comment by vanniktech** [comment]
Is there an issue on their repo to watch?

**Comment by joshdholtz** [comment]
@vanniktech Its up now and should have this out today 💪 I've been out sick so haven't been able to get to it as quickly as I would have liked 😝
