### ISSUE TITLE
Add option to `cert` to only download certificates

### ISSUE THREAD

**Issue by ben-lings-tessella** [fastlane/fastlane#12486]
#### Motivation Behind Feature

We have our CI build set up so that the private key the code signing certificates is installed on each machine. When the certificate expires, we use the same private key to create a new certificate signing request to get a new certificate. We would like to be able to automate downloading the new certificates as part of our Fastlane build. 

#### Feature Description

The `cert` action almost handles this - with the exception that if the certificate has expired, it creates a new private key and new certificate. I'd like to be able to pass an option to the `cert` action  (e.g. `readonly` - similar to `sigh`)  to make it fail the build if the certificate has expired.

The current behaviour isn't workable because the signing key is shared between multiple 3rd party suppliers who deploy to the company's App Store account. Distributing this new private key is non-trivial.

Any new behaviour would only happen if the option were specified, so this wouldn't impact any existing users.

#### Alternatives or Workarounds

Current workaround is to manually copy the certificates to the build machines and to update the certificate ID specified as a parameter to the `sigh` action.

**Comment by ben-lings-tessella** [comment]
`fastlane env` isn't relevant to this (it's a feature request). I'm aware of the code signing troubleshooting guide, but this doesn't fit with the way we are using Fastlane

**Comment by ben-lings-tessella** [comment]
This issue isn't yet resolved

**Comment by ben-lings-tessella** [comment]
This issue isn't yet resolved

**Comment by ben-lings-tessella** [comment]
This issue isn't yet resolved

**Comment by janpio** [comment]
Some research on this:

The logic that would have to be changed:
https://github.com/fastlane/fastlane/blob/477acfccd2af9b849846f1de2d3e5af64cd168ed/cert/lib/cert/runner.rb#L36-L48

New options to be created here:
https://github.com/fastlane/fastlane/blob/master/cert/lib/cert/options.rb

modelled after
https://github.com/fastlane/fastlane/blob/477acfccd2af9b849846f1de2d3e5af64cd168ed/sigh/lib/sigh/options.rb#L133-L142

**Comment by ben-lings-tessella** [comment]
> > When the certificate expires, we use the same private key to create a new certificate signing request to get a new certificate.
> How are you doing this? Fastlane actions?
This is a manual step - because it involves coordinating with third parties

> > The cert action almost handles this - with the exception that if the certificate has expired, it creates a new private key and new certificate.
> What exactly do you need - it to a) create a new certificate using the same private key that you supply to the action or b) only to fail if a new certificate would be created as the old one is expired?

`b` - I want to be in control of when new certificates are created and when we switch to a new one. For enterprise apps, I need to know when they are going to expire because it means rolling out new versions of apps.

> > with the exception that if the certificate has expired
> Are you sure cert is checking if a certificate is expired? I couldn't the code that does this to be honest.

I think `find_existing_cert` (called on line 38 of `runner.rb`) will return `nil` if the certificate is invalid.

**Comment by janpio** [comment]
yay side effects :) :/

Ok, that should definitely be documented here, but actually makes this viable. Similar to `match` and `sigh`, `cert` could get a `readonly` param.

Do you want to create the PR yourself? Shouldn't be too hard to throw something together.
