### ISSUE TITLE
Fatslane Match for different branches in same project

### ISSUE THREAD

**Issue by Martin-MacDonald** [fastlane/fastlane#12481]
I am just new to fastlane and have been tasked with deploying an application that is far from the norm.

We have a Master branch and off of that branch we have several release/ branches. Each of these release/ branches is a different setup for specific clients. Our initial setup had us using fastlane and match from the one apple developer account - which was fine.

However Apple have now required each of the separate setups/apps for clients to be under their own developer accounts. Thus we are now in a position where we have one project but will be required to run different fastlane and match setups from different branches.

Is this possible from the same project? Do we need a match repo for each branch? Or are we going to be able to use fastlane at all for this setup?

**Comment by salmanasiddiqui** [comment]
`match` supports multiple teams
https://docs.fastlane.tools/actions/match/#important-use-one-git-branch-per-team
