### ISSUE TITLE
Using Deliverfile

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12485]
hi
i could not use Deliverfile. I just need upload release notes. I uploaded it by metadata. But is it possible to write just release notes by Deliverfile
 
 deliver(
      app_version: version,
      precheck_include_in_app_purchases: false,
      submit_for_review: false,
      automatic_release: false,
      skip_metadata: true,
      release_notes: true,
      force: true,
      ignore_language_directory_validation: true,
      skip_screenshots: true,
      skip_binary_upload: true   
    )

My Deliverfile:
----------------
release_notes({
  'default' => 'Minor bug fixes and improvements',
  'tr-TR' => 'Hatalar giderildi ve performans iyilestirmeleri yapildi.'
})

**Comment by RishabhTayal** [comment]
@baturorkun Try the following.

```
 deliver(
    app_version: version,
    app_identifier: 'com.example.identifier',
    precheck_include_in_app_purchases: false,
    submit_for_review: false,
    automatic_release: false,
    force: true,
    ignore_language_directory_validation: true,
    skip_screenshots: true,
    skip_binary_upload: true
  )
```

Remove the `skip_metadata: true` and `release_notes: true`. Specifying `skip_metadata` as `true` will skip updating `release_notes` as well. Also, `release_notes` is required to be a hash instead of boolean. That hash is picked up from your `Deliverfile`.

**Comment by baturorkun** [comment]
hi rishabhtayal

After running like this, i got this error

[10:01:47]: Making sure the latest version on iTunes Connect matches '1.114' from the ipa file...
[10:01:49]: '1.114' is the latest version on iTunes Connect
[10:01:51]: Detected languages: ["default", "en-US", "tr-TR"]
[⠦] Activating languages en-US, tr-TR... Potential server error received: 'There are one or more errors on the page.'. Retrying after 10 seconds (remaining: 5)...
[⠦] Activating languages en-US, tr-TR... Potential server error received: 'There are one or more errors on the page.'. Retrying after 10 seconds (remaining: 5)...
[⠏] Activating languages en-US, tr-TR... [10:02:21]: There are one or more errors on the page.

**Comment by RishabhTayal** [comment]
Have you specified `languages['en-US', 'tr-TR']` in your `Deliverfile`?

could you run `fastlane` with `--verbose` option?

**Comment by RishabhTayal** [comment]
@baturorkun The error you are receiving seems like is because the metadata you are submitting is not valid. Can you try putting the same data manually on iTunes Connect and see if all the data is valid.
