### ISSUE TITLE
Upgrading to 2.95 breaks changelog_from_git_commits

### ISSUE THREAD

**Issue by keeshux** [fastlane/fastlane#12497]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.95.0`
- Last working version: `2.94.0`

### Regression Description

Simply put, fails with:

    TypeError: [!] no implicit conversion of nil into String

Looks related to #10358 but it's not happening in `match`, I'm invoking `changelog_from_git_commits`.

##### Complete output when running fastlane, including the stack trace and command used

I can't share the full output for privacy, but if this is not enough I can share more snippets on request.

<details>
  <pre>
TypeError: [!] no implicit conversion of nil into String
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb:32:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb:32:in `run'
</pre>
</details>

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

</pre>
</details>

**Comment by joshdholtz** [comment]
@keeshux Looking into!

**Comment by RishabhTayal** [comment]
@keeshux Could you provide the options you are using with `changelog_from_git_commits` action?

**Comment by keeshux** [comment]
Could this be related? Seems recent enough: https://github.com/fastlane/fastlane/commit/f50df628d7a2af8cb91c31024ec8111482cbf4db

**Comment by keeshux** [comment]
@RishabhTayal I've just found your entry in the changelog:
```
[action] add path option for changelog from git commits (#12429) via Rishabh Tayal
```
so yeah this definitely was introduced by https://github.com/fastlane/fastlane/pull/12429

**Comment by RishabhTayal** [comment]
Yeah I will take a look at it.

**Comment by RishabhTayal** [comment]
@keeshux I just checked and the value for `path` is coming as `nil` even though we have specified the `default_value`. Same is the case with a couple of other options. Not sure why the value is coming as `nil`. Will keep digging further. Thanks for the info.

**Comment by RishabhTayal** [comment]
For now you can provide the `path` option. Will fix this issue soon.

**Comment by keeshux** [comment]
Sure, thanks, I'm digging the code too and I'm now quite sure that #12429 is not the root cause.

More info. Running the action with `fastlane run` from the shell gives no issue, whereas failure happens when I run it within my custom action (`Fastlane::Actions::ChangelogFromGitCommitsAction.run`).

**Comment by RishabhTayal** [comment]
@keeshux That's very interesting. To add to your point, I think that's how all the actions work. If you call the action using `Fastlane::Actions::SomeAction.run()` it won't pick up the `default_value`. You would need to specify them manually. I remember having this issue with some other lane as well. 

I think it's safe to close the PR as this bug is invalid. @joshdholtz @revolter Please verify and close the issue.

**Comment by revolter** [comment]
In which case would you need to call an action like that, instead of `changelog_from_git_commits(...)`?

**Comment by keeshux** [comment]
@RishabhTayal I disagree for two reasons:

- This has worked until 2.94
- There are other options that I'm not passing as they have defaults (e.g. `ancestry_path`)

@revolter it's part of a plugin I wrote to make the action easy to share in more projects. Of course this can be rewritten as a lane, but AFAIK plugins are made of actions. I don't think we have enough data to close this issue.

**Comment by revolter** [comment]
@keeshux, `Fastlane::Actions::ChangelogFromGitCommitsAction.run(...)` goes directly to:

https://github.com/fastlane/fastlane/blob/c01816e5cc3fe279ef0593f28a19edc2fd3c3cae/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L8

with the parameters that you pass, so when it gets to:

https://github.com/fastlane/fastlane/blob/c01816e5cc3fe279ef0593f28a19edc2fd3c3cae/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L32

it crashes.

**Comment by revolter** [comment]
@keeshux, The default values are not used at all, they're `nil`. It might not crash because they're ignored or something, depending on the usage, but in this case it crashes when it's `nil`.

**Comment by keeshux** [comment]
@revolter yeah I know, it didn't crash because the parameter didn't exist before the `path` addition. Other default values don't crash only because e.g. booleans fail more gracefully/silently than strings/objects. Makes sense.

**Comment by revolter** [comment]
Yup. I say we should make sure it doesn't crash regardless how it's called, and then maybe figure out a way to go through the config items if possible, or mention it in the docs.

**Comment by keeshux** [comment]
Cool, even though I think I read somewhere in the doc about overall differences between lane and raw invocation, like @RishabhTayal mentioned. Still, the assumption that they behave the same may be legitimate, especially for plugins. I'll close this issue anyway and possibly create a specific issue if none exists.

Thank you!

**Comment by revolter** [comment]
@keeshux Did you try the `FastlaneCore::Configuration.create` approach?

**Comment by keeshux** [comment]
Not really, I'll let you know. I'll have to rewrite those `run()` bits with this caveat in mind, as the plugin as is may break very unexpectedly.
