### ISSUE TITLE
Simulator visibility during snapshot

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#12493]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Why I am not able to see the emulator while `snapshot` is running? if I start the lane with the simulator opened, it closes.
#### Question Description

Sometimes I want to do some configuration, control the device while the automation is running or simply see it, but I can't since the simulator is not visible anymore. What I can do to solve this? Is this a expected behaviour?
My UI tests/automation are working fine, the compilation is super fast compared to fastlane, just fastlane is not dealing correct with the process to build and run the test. Probably there is something wrong... You can check my config here: https://github.com/fastlane/fastlane/issues/12480
This last version of `fastlane` is very unstable, I am wasting more than a day just to solve a issue on a single action. It's driving me crazy.

Probably related to https://github.com/fastlane/fastlane/issues/10381

Edit 1:

I was able to find one sign of what is happening, I am running the `snapshot` inside a foreach, like this:

```ruby
  SCREENSHOTS_ARRAY.each_with_index do |screenshotScheme, index|
    ENV["SCREENSHOT_SCHEME"] = screenshotScheme
    ENV["APP_IDENTIFIER"] = POSSIBLE_IDENTIFIER_ARRAY[index]
    ENV["SCHEME"] = POSSIBLE_SCHEME_ARRAY[index]
    ENV["SCHEME_NICKNAME"] = POSSIBLE_SCHEME_NICKNAME_ARRAY[index]
    snapshot(
        workspace: "MyApp.xcworkspace",
        scheme: ENV["SCREENSHOT_SCHEME"],
        derived_data_path: "/Users/me/Library/Developer/Xcode",
        output_simulator_logs: false,
        skip_open_summary: true,
        erase_simulator: false,
        clear_previous_screenshots: true,
        test_without_building: false,
        reinstall_app: false,
        concurrent_simulators: false,
        stop_after_first_error: false)
  end
```
After removing it from the interaction, the simulator started to appear. Is `snapshot` locking the thread? This can be the problem.

Edit 2:

The error `unable to spawn process (Resource temporarily unavailable)` still happening, even just running a single `snapshot` action.

**Comment by ppamorim** [comment]
Any idea?

**Comment by sushant40** [comment]
The docs DO say...

> Note: While running snapshot with Xcode 9, the simulators will not be visibly spawned. So, while you wont see the simulators running your tests, they will, in fact, be taking your screenshots.


however, I'd like to override that and show the simulator when i am developing!!

**Comment by ppamorim** [comment]
@sushant40 It does show if you test just one application. Strange no?

**Comment by sushant40** [comment]
I get no output. I got some screenshots that I need to use the home screen/springboard for but I cant - I think because the simulator is not visible

**Comment by molind** [comment]
I've managed to get the image from simulator by recording screen. :)

example:
`xcrun simctl io "iPhone 5s" recordVideo --type=mp4 test.mp4`
or
`xcrun simctl io booted recordVideo --type=mp4 test.mp4`

**Comment by mmysliwiec** [comment]
It's a big issue for me since headless simulator is ignoring geolocation setup and my screenshots show different location than I want. Check my feature request https://github.com/fastlane/fastlane/issues/12682 describing the issue and solution.

**Comment by sushant40** [comment]
Can we add a fix for this to the next release? Alternatively the screen recording function could also be part of fastlane.

**Comment by ppamorim** [comment]
@fastlane-bot It wasn't.

**Comment by Teglgaard** [comment]
It does not help to update. Does someone know where this code is being run then i can check if I can fix it.

**Comment by tmaly1980** [comment]
It looks like the simulator won't open if the app is already installed. But if you provide "reinstall_app: true" to snapshot, it will always open the simulator and uninstall the app before installing it.
