### ISSUE TITLE
How to change android applicationId dynamically?

### ISSUE THREAD

**Issue by daraujofs** [fastlane/fastlane#12503]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Change applicationId dynamically using env files

#### Question Description
I need to export the same app with different applicationIds. I tried to set the gradle property, but has no effect, the app is always generated with same package (defined in gradle file). This is my gradle action:
```
gradle(
        task: "assemble",
        build_type: "Release",
        print_command: false,
        properties: {
            "applicationId" => ENV["APPLICATION_ID"],
            "android.injected.signing.store.file" => "#{ENV["ANDROID_KEYSTORE_KEYSTORE_NAME"]}",
            "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_ALIAS_NAME"],
            "android.injected.signing.key.password" => ENV["ANDROID_KEYSTORE_KEY_PASSWORD"],
        }
    )
```

I found a question similar to mine but the solution to change the applicationId (only in gradle file) isn't there.

**Comment by joshdholtz** [comment]
@daraujofs Have you tried this plugin yet? 😊 https://github.com/MaximusMcCann/fastlane-plugin-android_change_app_name
