### ISSUE TITLE
Is full Xcode required to run fastlane for IOS projects?

### ISSUE THREAD

**Issue by skathayat** [fastlane/fastlane#12502]
According to the fastlane documentation on IOS setup, the following command should be enough
`xcode-select --install`

Meaning that no need to install full Xcode.

However,  when I run fastlane on iOS project, it says the following error,
`xcode-select: error: tool 'agvtool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

So, the question is, Xcode is  required to run fastlane for IOS projects? xcode command line tools are not enough?

**Comment by joshdholtz** [comment]
@skathayat Xcode command lines tools are needed for fastlane to run as it uses the Xcode command line tools to communicate with Xcode. So yes, you will need full Xcode to build iOS projects 😊
