### ISSUE TITLE
"fastlane snapshot" not reading my Snapfile

### ISSUE THREAD

**Issue by FromDerik** [fastlane/fastlane#12510]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I setup fastlane with "fastlane init swift" and followed the steps to automate screenshots. Fast-forward to having my UITests setup and everything, running "fastlane snapshot" does not read my Snapfile and uses the default Snapfile, but it runs the tests and generates the screenshots fine. Also, running "fastlane screenshotsLane" also does not read my Snapfile, but this fails.

This is my Snapfile:

    class Snapshotfile: SnapshotfileProtocol {

    // A list of devices you want to take the screenshots from
    var devices: [String] { return [
        "iPhone 6",
        "iPhone 6 Plus",
        "iPhone 5",
        "iPhone X"
        ]
    }

    // locales not supported in Swift yet
    var languages: [String] { return [
        "en-US",
        "de-DE",
        "it-IT"
        ]
    }

    // The name of the scheme which contains the UI Tests
    var scheme: String? { return "MarcosManagementUITests" }

    // Where should the resulting screenshots be stored?
    var outputDirectory: String { return "./screenshots" }

    // Clear all previously generated screenshots before creating new ones
    var clearPreviousScreenshots: Bool { return true }

    // Choose which project/workspace to use
    var project: String? { return "./MarcosManagement.xcodeproj" }
    // var workspace: String? { return "./Project.xcworkspace" }

    // Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
    // var launchArguments: [String] { return ["-favColor red"] }

    // For more information about all available options run
    // fastlane snapshot --help
}

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
Deriks-iMac:MarcosManagement derik$ fastlane screenshotsLane
[✔] 🚀 
[07:30:34]: fastlane detected a Gemfile in the current directory
[07:30:34]: however it seems like you don't use `bundle exec`
[07:30:34]: to launch fastlane faster, please use
[07:30:34]: 
[07:30:34]: $ bundle exec fastlane screenshotsLane
[07:30:34]: 
[07:30:34]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[07:30:34]: loading manifest: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/swift/upgrade_manifest.json
[07:30:35]: FastlaneSwiftRunner project is up-to-date
[07:30:35]: $ ./fastlane/FastlaneRunner lane screenshotsLane > /dev/null
[07:30:35]: ---------------------------------
[07:30:35]: --- Step: capture_screenshots ---
[07:30:35]: ---------------------------------
[07:30:36]: $ xcodebuild -showBuildSettings -scheme MarcosManagementUITests -project ./MarcosManagement.xcodeproj

+----------------------------+--------------------------------------+
|                    Summary for snapshot 2.95.0                    |
+----------------------------+--------------------------------------+
| languages                  | ["en-US"]                            |
| launch_arguments           | []                                   |
| output_directory           | /Users/derik/Documents/Xcode/Marcos  |
|                            | Management/screenshots               |
| output_simulator_logs      | false                                |
| skip_open_summary          | false                                |
| skip_helper_version_check  | false                                |
| clear_previous_screenshots | false                                |
| reinstall_app              | false                                |
| erase_simulator            | false                                |
| localize_simulator         | false                                |
| buildlog_path              | ~/Library/Logs/snapshot              |
| clean                      | false                                |
| scheme                     | MarcosManagementUITests              |
| number_of_retries          | 1                                    |
| stop_after_first_error     | false                                |
| concurrent_simulators      | true                                 |
| project                    | ./MarcosManagement.xcodeproj         |
| devices                    | ["iPhone 7", "iPhone 7 Plus",        |
|                            | "iPhone 8", "iPhone 8 Plus",         |
|                            | "iPhone X", "iPad (5th               |
|                            | generation)", "iPad Pro              |
|                            | (9.7-inch)", "iPad Pro               |
|                            | (12.9-inch)", "iPad Pro              |
|                            | (10.5-inch)"]                        |
| xcode_path                 | /Applications/Xcode.app              |
+----------------------------+--------------------------------------+

[07:30:39]: Building and running project - this might take some time...

+-----------------------+
|   snapshot results    |
+-----------------------+
| Device                |
+-----------------------+
| iPhone 7              |
| iPhone 7 Plus         |
| iPhone 8              |
| iPhone 8 Plus         |
| iPhone X              |
| iPad (5th generation) |
| iPad Pro (9.7-inch)   |
| iPad Pro (12.9-inch)  |
| iPad Pro (10.5-inch)  |
+-----------------------+

[07:30:39]: Generating HTML Report
[07:30:39]: No such file or directory @ rb_sysopen - /Users/derik/Documents/Xcode/MarcosManagement/screenshots/screenshots.html

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 💥   | capture_screenshots | 3           |
+------+---------------------+-------------+

[07:30:39]: fastlane finished with errors

[07:30:39]: Error accessing file, this might be due to fastlane's directory handling
[07:30:39]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/snapshot/lib/snapshot/reports_generator.rb:35:in `write': No such file or directory @ rb_sysopen - /Users/derik/Documents/Xcode/MarcosManagement/screenshots/screenshots.html (Errno::ENOENT)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/snapshot/lib/snapshot/reports_generator.rb:35:in `generate'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/snapshot/lib/snapshot/runner.rb:56:in `work'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/capture_ios_screenshots.rb:14:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:73:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:42:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:179:in `execute_action_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:174:in `process_action_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:121:in `handle_action_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:84:in `parse_and_execute_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:60:in `block in receive_and_process_commands'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:47:in `loop'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:47:in `receive_and_process_commands'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:156:in `listen'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/server/socket_server.rb:36:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/swift_lane_manager.rb:226:in `block in start_socket_thread'
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.1 (Apple Git-101)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    func screenshotsLane() {
    desc("Generate new localized screenshots")
        captureScreenshots(scheme: "MarcosManagementUITests")
//        uploadToAppStore(username: "DerikMalcolm@gmail.com", app: "com.fromderik.MarcosManagement", skipBinaryUpload: true, skipMetadata: true)
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.95.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                   |    Version      |
| ------------------------- | ------------ |
| did_you_mean                    | 1.0.0        |
| slack-notifier                | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.8        |
| faraday                   | 0.15.1       |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-05-12**
</details>
</pre>
</details>

**Comment by SebastianBoldt** [comment]
I got the same problem and did not found a solution so far. I think it has something todo with the fact that we are both using the swift beta. I also discovered that the same applies to match or pilot. They will also ignore App & Fastfile.
