### ISSUE TITLE
Prompted for Apple ID Security Questions

### ISSUE THREAD

**Issue by benwalpole** [fastlane/fastlane#12515]
### Question Subject
Spaceship

#### Question Description

I'm trying to use the Fastlane (via VSTS) to deploy a build of an app to TestFlight but something is failing at the authentication stage.

It seems to be related to the fact that iTunes is challenging for answers to the security questions for the account.

I'm not sure how to resolve this, Is this an issue with the account I'm trying to use?

`/Users/vsts/.gem-cache/gems/fastlane-2.93.1/spaceship/lib/spaceship/two_step_client.rb:45:in` `handle_two_step:` [!] Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>134,` `"question"=>"Where` did you go the first time you flew on a plane?", "number"=>1,` `"userDefined"=>false},` {"id"=>136, "question"=>"What is your dream job?", "number"=>2,` `"userDefined"=>false}]},` "crResetEnabled"=>false,` `"resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"}` (RuntimeError)`

**Comment by benwalpole** [comment]
I'm not actually running fastlane directly, its being used by a VSTS extension, so I don't think I can get the output `fastlane env`. I'm just looking to get some guidance on what would cause Apple to challenge for security questions during authentication.

**Comment by heartofagoof** [comment]
Do you have 2FA enabled on fastlane?

**Comment by benwalpole** [comment]
No I don't, I think that might be the problem, the VSTS docs don't make it clear that its required: https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth

**Comment by joshdholtz** [comment]
@benwalpole One of the suggest approaches when working with a CI system is to create a separate developer account specifically for fastlane to run with that doesn't have 2 factor or 2 step auth. I don't know what your account is setup as (😉) but I would suggest maybe creating a new developer account specifically for fasltane and give that a try 🙃
