### ISSUE TITLE
Snapshot on XCode7 objc: pb on filename orientation

### ISSUE THREAD

**Issue by fvisticot** [fastlane/fastlane#1251]
Screenshots are corrects but file name is  './screenshots/fr-FR/iPhone6-01BeaconsScreen    t =    17.78s     Set device orientation to Unknown.png'

How to set orientation in objc test code instead of this Unknown filename ?

**Comment by fvisticot** [comment]
With Snapshot 1.6.0 

I'm using objc class for SnapshotHelper found here: https://gist.github.com/vovkasm

Can you please help me to fix this pb ?

Traces:
 	 Executed 3 tests, with 0 failures (0 unexpected) in 70.664 (70.667) seconds
[22:36:33]: ▸ 
[22:36:33]: Collecting screenshots...
[22:36:33]: Found 7 screenshots...
[22:36:33]: Copying 'screenshots/fr-FR/iPhone4s-01LoginScreen    t =     7.12s     Set device orientation to Unknown.png'...
[22:36:33]: Copying 'screenshots/fr-FR/iPhone4s-02ConnectionScreen    t =     9.07s     Set device orientation to Unknown.png'...
[22:36:33]: Copying 'screenshots/fr-FR/iPhone4s-05BeaconsScreen    t =    21.64s     Set device orientation to Unknown.png'...

**Comment by fvisticot** [comment]
any update ? still blocked :(

**Comment by ohwutup** [comment]
hey @fvisticot, thanks for raising this issue! i think it would be best if @vovkasm could chime in here and help debug this, but i can definitely help walk you through using fastlane's swift version of this file even though you are using objc for your testing. that would at least help get rid of the variable of the third party code. let me know if you have trouble trying that out! :smile:

**Comment by vovkasm** [comment]
I will need to do screenshots in near days, so will update objc helper to latest swift version. And will try to fix this, of course ;-) Thanks!

**Comment by ohwutup** [comment]
thanks @vovkasm !

**Comment by fvisticot** [comment]
Please do not close the issue, the issue is not fixed yet

**Comment by ohwutup** [comment]
@fvisticot i'm going to close this again, and it would be best if we could track work on the gist here: https://gist.github.com/vovkasm/9620d9105d0869d1debb
