### ISSUE TITLE
Multiple flavour single project push to different application to playstore (Android)

### ISSUE THREAD

**Issue by taman123** [fastlane/fastlane#12529]
#### Motivation Behind Feature
If application has two version like (Paid and free) if we ship them to play store making different application. I think this is frequent case.

#### Feature Description
If application has two version like (Paid and free) if we ship them to play store making different application. I think this is frequent case.

#### Alternatives or Workarounds
Now the alternative work around may be making them separate project and building separately and publishing them to play store

**Comment by taman123** [comment]
My question is not regarding any issue. I am just asking about some features either fastlane has or you are planning to ship soon.

At the time of fastlane init we have to provide package name, but in my case i have single project but multiple package generated with multiple flavour. 

Now the question is there any features to add multiple packages in single project. Now at the time of fastlane init we can provide only one package name and fast lane supply init will pull that specific single application. But in my case there are multiple application with single project file.

**Comment by joshdholtz** [comment]
@taman123 Heyyy 👋 I'm a little confused by how you explained your setup but if you are able to make different builds with your gradle process, you should totally be able to use the `gradle` action to call your different flavors and APKs multiple times using supply 🙃
