### ISSUE TITLE
Using export_method as "development" for Appstore build.

### ISSUE THREAD

**Issue by jelangba-ford** [fastlane/fastlane#12522]
Hello,

I was trying to export the archive(generating ipa) for the AppStore distribution, I have the AppStore profile , but the problem is that the Appstore profile is created using developer profile, so when I use export_method as "app-store", fastlane complains that "Distribution Profile not found" however I can successfully export using "development" in export_method.
My question is , will there be any problem if I use export_method as "development", instead of "app-store" for Appstore build, or is there a work around for this problem?

Thanks in advance.

### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by jelangba-ford** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.26.1"

default_platform :ios

#ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do

before_all do


#  sh("export http_proxy=proxyvipecc.nb.ford.com:83")
#   sh("export https_proxy=proxyvipecc.nb.ford.com:83")

end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

gym(
       scheme: "TestFastlane",
       configuration: "Release",
       export_method: "development",
       skip_build_archive: false,
       output_directory: "./build",
       build_path: "./build",
       disable_xcpretty: true,
      #  xcargs: "PROVISIONING_PROFILE_SPECIFIER='Ford Pass Europe-DEV'"
      #  export_options: {
      #    provisioningProfiles: {
      #      "com.ford.fordpasseu" => "Ford Pass Europe-DEV"
      #      } 
      #     }

)

build_number = latest_hockeyapp_version_number(
	    api_token: "2d3264e0eee94e1fbb31d3f5a5b1b4db",
	    app_name: "Upload Archive testing"
  )
  increment_build_number(
        build_number: build_number + 1,
        xcodeproj: "TestFastlane/TestFastlane.xcodeproj"
	)

# upload to HockeyApp
  hockey(
     api_token: "2d3264e0eee94e1fbb31d3f5a5b1b4db",
     public_identifier: "3368c958f60a457194946ef9314f6faf",
#     dsym: "../TestFastlane/build/TestFastlane.dsym.zip",
#     bundle_version: "1",
#     #bundle_short_version: "1",
#     notes_type: "1",
#     status: "2",
#     notify: "2",
#     #create_update: true,
#     upload_dsym_only: true
 )
    after_all do
        #Call the script to push to hockeyapp
        # sh("./hockey.sh")
    end

  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ford.TestingApp" # The bundle identifier of your app
apple_id "ccdevops@ford.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.59.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2018-05-16**
</details>

**Comment by joshdholtz** [comment]
@jelangba-ford Building for the app-store will require that the "provisioning profile" mapping get set (which based upon your `Fastfile`, it looks like you had commented out). You will either want to uncomment that out and make sure things are set correctly there or use the preferred method of calling `match` or `sigh` before calling `gym`. `match` and `sigh` will both create the proper proper provisioning profile mapping for you that _should_ help you build and distribute your app properly 😊
