### ISSUE TITLE
[Frameit] Maintain same font size in all framed screenshots

### ISSUE THREAD

**Issue by vrao423** [fastlane/fastlane#12520]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about?
frameit
Is this a question about documentation?
No
Is this a question about a third party plugin? (If so, please go to the plugin repository first)
No

#### Question Description
Is it possible to maintain the same font size for all frames generated by frameit?

Here is my Framefile.json
```
{
    "device_frame_version": "latest",
    "default": {
        "background": "iPhone_6_7_8_plus_bg.jpg",
        "padding": 60,
        "title": {            
            "fonts": [
                {
                    "font": "../../Shutterstock/DINNextW1G-Regular.ttf",
                    "supported": ["en", "de", "es", "pt"]
                },
                {
                    "font": "../../Fonts/NotoSansCJKkr-Regular.otf",
                    "supported": ["ko"]
                },
                {
                    "font": "../../Fonts/NotoSansCJKjp-Regular.otf",
                    "supported": ["ja"]
                }
            ]
        }
    },
    "data": [
    ]    
}
```

Here is my title.string file:
```
"Discovery" = "Search and discover";

"MediaDetails" = "Save and Share";

"Collections" = "Start your project on mobile";

"Search" = "Search";

"Downloads" = "Download images";
```

Here are the two screenshots generated:
![iphone 6 plus-01mediadetails_framed](https://user-images.githubusercontent.com/675111/40020791-03a33448-5791-11e8-9ad4-982bad7be087.png)
![iphone 6 plus-03userimagecollections_framed](https://user-images.githubusercontent.com/675111/40020796-060e4bd2-5791-11e8-8c50-0d31f36fa83c.png)

The same font size is required as it might be jarring for users scrolling horizontally in the App Store. The example images have the same font, so I must not be understanding something.

**Comment by RishabhTayal** [comment]
@vrao423 Have you tried using `font_scale_factor` in your `Framefile.json`?

Something like this:

```
{
  "default": {
    "title": {
      "color": "#ffffff"
    },
    "background": "./Frameit-background.png",
    "padding": "3%",
    "font_scale_factor": 0.05
  },
   "data": [
    {
      "filter" : "iPad"
      "font_scale_factor": 0.035
    }
  ]
}
```

**Comment by vrao423** [comment]
@RishabhTayal so I will have to set `font_scale_factor` for each screenshot?

**Comment by RishabhTayal** [comment]
I believe so. @joshdholtz Correct me if I am wrong.
