### ISSUE TITLE
The login credentials for '***@***.com' seem to be wrong

### ISSUE THREAD

**Issue by daviskoh** [fastlane/fastlane#12528]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I assume you mean the Github password, but to be safe I have also tried my Apple Developer account as well with no luck. I have also tried using the `FASTLANE_PASSWORD` env var to set the password as well. 

The passwords used are in fact correct. I have tried both manually entering and copy-pasting. The passwords used were used to login to my accounts before and after running `fastlane match` to verify that they were valid.

##### Complete output when running fastlane, including the stack trace and command used

`$ bundle exec fastlane match appstore` also tried `$ fastlane exec match appstore` (does not seem to be issue w/ bundler)

```
[22:56:58]: Successfully loaded '***/fastlane/Matchfile' 📄

+----------------+---------------------------------------------------------------+
|                  Detected Values from './fastlane/Matchfile'                   |
+----------------+---------------------------------------------------------------+
| git_url        | ***-certificates.git       |
| app_identifier | ["com.***.***", "com.***.***",  |
|                | "com.***.***"]                                |
| username       | ***@***.com                                           |
+----------------+---------------------------------------------------------------+


+-----------------------+---------------------------------------------------------------+
|                               Summary for match 2.95.0                                |
+-----------------------+---------------------------------------------------------------+
| type                  | appstore                                                      |
| git_url               | ***-certificates.git       |
| git_branch            | master                                                        |
| app_identifier        | ["com.***.***", "com.***.***",  |
|                       | "com.***.***"]                                |
| username              | ***@***.com                                           |
| keychain_name         | login.keychain                                                |
| readonly              | false                                                         |
| verbose               | false                                                         |
| force                 | false                                                         |
| skip_confirmation     | false                                                         |
| shallow_clone         | false                                                         |
| clone_branch_directly | false                                                         |
| force_for_new_devices | false                                                         |
| skip_docs             | false                                                         |
| platform              | ios                                                           |
+-----------------------+---------------------------------------------------------------+

[22:56:58]: Cloning remote git repo...
[22:56:58]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[22:56:59]: 🔓  Successfully decrypted certificates repo
[22:56:59]: Verifying that the certificate and profile are still valid on the Dev Portal...
The login credentials for '***@***.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
[22:56:59]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[22:56:59]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[22:56:59]: to just install the certificates and profiles without accessing the Dev Portal.
[22:56:59]: To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
	Invalid username and password combination. Used '***@***.com' as the username.
```

<details>
  <pre>invalid option: --capture_output</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.95.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  # ENV['BITRISE_SOURCE_DIR'] = /Users/vagrant/git

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "***",
      devices: ["iPhone 8"],
      configuration: "Debug",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Debug.xcconfig"
    )
  end

  desc "Submit a new ALPHA Build to Apple TestFlight"
  lane :alpha do
    ENV["AWS_COGNITO_USER_POOL_SECRET"] = ENV["AWS_COGNITO_USER_POOL_SECRET_alpha"]
    ENV["GOOGLE_PLACES_AUTOCOMPLETE_KEY"] = ENV["GOOGLE_PLACES_AUTOCOMPLETE_KEY_alpha"]

    match(
      app_identifier: "com.***.***",
      type: "appstore",
      readonly: true
    )

    gym(
      scheme: "***",
      configuration: "Alpha",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Alpha.xcconfig"
    )
    scan(
      scheme: "***",
      devices: ["iPhone 8"],
      skip_build: true,
      configuration: "Alpha",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Alpha.xcconfig"
    )

    # increment_build_number
    # upload_to_testflight
    # match(type: "appstore") # more information: https://codesigning.guide
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Submit a new BETA Build to Apple TestFlight"
  lane :beta do
    # ENV["AWS_COGNITO_USER_POOL_SECRET"] = ENV["AWS_COGNITO_USER_POOL_SECRET_beta"]

    #increment_build_number
    #gym(scheme: "***", xcconfig: "Alpha.xcconfig")
    #upload_to_testflight
    # match(type: "appstore") # more information: https://codesigning.guide
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    #gym(scheme: "***") # Build your app - more options available
    #deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "***@***" # Your Apple email address

for_lane :local do
  team_id "***" # Developer Portal Team ID
  app_identifier 'com.***.***'
end

for_lane :dev do
  team_id "***" # Developer Portal Team ID
  app_identifier 'com.***.***'
end

for_lane :alpha do
  team_id "***" # Developer Portal Team ID
  app_identifier 'com.***.***'
end


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.95.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.2        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |

</details>

*generated on:* **2018-05-15**

**Comment by daviskoh** [comment]
Yes I've look at your guide. It's not very helpful as it just says to use the tools I am already using like `match`. As described above, I am unable to use the `match` command to do any kind of write operation as it results in the error above.

**Comment by joshdholtz** [comment]
@daviskoh Sorry to hear your having issues 😔 

>I assume you mean the Github password, but to be safe I have also tried my Apple Developer account as well with no luck

The match username should be your iOS Developer Portal email address and password.

The _match_ code for match is currently working for me (been using it this morning) so it appears its either a configuration issue in your project or something weird going on with your machine 🤔 

```rb
The login credentials for '***@***.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
```

Its hard to know _exactly_ how to help without using your setup directly but can you try removing the password from the environment variable so the command makes you enter it manually? (Maybe its pulling the wrong value from somewhere?) Also, just wanted to verify... is that blurred out email that correct one for your iOS Developer account?

**Comment by daviskoh** [comment]
As stated above, I have already tried entering the password manually.

The email is blurred out.

**Comment by daviskoh** [comment]
deciding to nuke my whole setup and start from scratch. seeing other issues, but ill close this for now
