### ISSUE TITLE
setup_jenkins 

### ISSUE THREAD

**Issue by skathayat** [fastlane/fastlane#12521]
Why does it deletes other KeyChain such as Login?

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by skathayat** [comment]
@fastlane-bot there is not output of fastlane env! It just deletes login keychain that we can see on keychain access app

**Comment by joshdholtz** [comment]
@skathayat It shouldn't be deleting the login keychain. Can you provide what parameters you are passing to `setup_jenkins`, if any?

**Comment by skathayat** [comment]
@joshdholtz I have tried without any parameters, and it deletes login keychain. The name of my keychain is different from `login`.
