### ISSUE TITLE
Match generating profile with a different certificate

### ISSUE THREAD

**Issue by kdaker** [fastlane/fastlane#12537]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Match generating profile with a different certificate

#### Question Description
When generating a development cert with match, it seems to be using a different certificate from what xcode is reporting. 

this is the cert output from `match development`:

```
+-------------------+---------------------------------------------+
|                      Installed Certificate                      |
+-------------------+---------------------------------------------+
| User ID           | xxxxxxxxxx                                  |
| Common Name       | iPhone Developer: Kareem Daker (SKT9X66B85) |
| Organisation Unit | xxxxxxxxxx                                  |
| Organisation      |  -------------------------                  |
| Country           | US                                          |
| Start Datetime    | 2017-12-04 22:54:50 UTC                     |
| End Datetime      | 2018-12-04 22:54:50 UTC                     |
+-------------------+---------------------------------------------+
```

However xcode is not showing the signing certificate and displays the wrong ID `6A4JXPAZ5T`:
![cert_issue](https://user-images.githubusercontent.com/905997/40143726-0f4a3540-5911-11e8-954f-c66df9b9d634.png)

I have both the certs and private keys for `SKT9X66B85` and `6A4JXPAZ5T` in my keychain.

**Comment by joshdholtz** [comment]
@kdaker Heyyyy 👋 Which team id are you actually looking to use? `SKT9X66B85` or `6A4JXPAZ5T `?

## If `SKT9X66B85 `
It looks like you need to change the team in the "Build Settings" to be the one associated with `SKT9X66B85`

## If `6A4JXPAZ5T`
It looks like you should be specifying a team id of `6A4JXPAZ5T` when running `fastlane match development`

Let me know if neither of these points you in the right direction 😊

**Comment by kdaker** [comment]
Thanks @joshdholtz! In addition to that I had to delete the development certificate generated by xcode, but it works now.
