### ISSUE TITLE
IOS How to change bundle_id

### ISSUE THREAD

**Issue by PaulDevelter** [fastlane/fastlane#12534]
Wondering if anyone can help. this is my scenario
1. I receive a compiled binary, lets say **newapp.ipa**
2. This has been signed with a cert from a 3rd party company and has the  bundle id **com.thirdpcompany.name**

I need to resign the app with my companys distribution cert - This I can do without issue.
BUT
I do not know how to change the bundle id so that it matches the app we have registered in the apple dev pages and therefore in the provisioning profle, for example, to **com.mycompany.appname**

I cannot recompile the binary. I do not have access to the code, all I have is a .IPA file.  

How do I do this?

Thanks!

**Comment by truth3** [comment]
Hi @PaulDevelter i can try to lend you a hand as I have been down this path a few times as the third party sending apps to our businesss parters. 

Unless you have a super strict policy the easiest thing to do is ask the third party to use your certs to publish for you. If it helps I can even share a lane configuration that build using local resources if you won’t let them be part of your dev team.

**Comment by salmanasiddiqui** [comment]
Hey @PaulDevelter ,
https://docs.fastlane.tools/actions/resign/
the above action supports `bundle_id` parameter which should do what you need.
