### ISSUE TITLE
Does not received notification for latest build in the Testflight

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#12532]
In my case, notification not receiving for the latest build. For new builds, I am receiving the notification with the previous build number.

Kindly clarify

**Comment by joshdholtz** [comment]
@nihp Can you please provide a little bit more info? What tools are you using? What does your `Fastfile` look like? What command are you running? And what kind of "notification" are you expecting?

**Comment by nihp** [comment]
@joshdholtz  Here is my Fastfile
```
# Uncomment the line if you want fastlane to automatically update itself
--
  |   |   | # update_fastlane
  |   |   |  
  |   |   | default_platform(:ios)
  |   |   |  
  |   |   | platform :ios do
  |   |   | desc "Push a new beta build to TestFlight"
  |   |   | lane :beta do
  |   |   | increment_build_number(xcodeproj: "MyApp.xcodeproj")
  |   |   | build_app(scheme: "MyApp")
  |   |   | upload_to_testflight
  |   |   | end
  |   |   | end
```
