### ISSUE TITLE
Pilot submitted to AppStore

### ISSUE THREAD

**Issue by joquerod** [fastlane/fastlane#1253]
Hello good day.
We use a CI system to build and deliver distribution builds.
For the last couple of months I've been using pilot to submit a build to testers.
I just noticed that a couple of weeks ago, the records show that pilot submitted a build to the appstore. I'm not 100% sure yet, I still need to review this with QA and the team, but using the timestamp as a reference, there is a 2 minutes difference between the build submission using pilot, and when the build became ready for sale, (according to itunes connect). 
Do you think this is possible?

**Notes:**
- First time it happens.
- Jenkins job has not changed all this time, same script:
- We submitted two builds with the same jenkins job, one was submitted to the appstore, the second it didn't, it's available for testers only.

**Script:**
export DELIVER_USER=user1
export DELIVER_PASSWORD=pass1
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" pilot upload --ipa file1.ipa

export DELIVER_USER=user2
export DELIVER_PASSWORD=pass2
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" pilot upload --ipa file2.ipa

**Comment by vpolouchkine** [comment]
Are you still hitting this?

**Comment by joquerod** [comment]
There is a chance that someone did a mistake and enabled an option in itunes connect to submit a build to the appstore right away. Is that possible? I'm not the itunes connect admin, and we know (the team) that was not intended.
At this point I'm still not sure, the build is in the appstore, and I will double check this next time we have a build for testflight.
Thanks for checking this. I will update this issue next time.

**Comment by vpolouchkine** [comment]
Sounds good, I will close this for now.
