### ISSUE TITLE
[Supply] Support Android custom closed tracks

### ISSUE THREAD

**Issue by authuser** [fastlane/fastlane#12541]
### Feature Request

Allow supply track parameter to be a custom name corresponding to a user-defined closed track on the google play store.

#### Motivation Behind Feature

At this years google IO, google changed all `beta` tracks to be open betas by default. This is problematic for anyone who wants to do a closed beta. To provide this functionality, google now allows multiple closed tracks that can have custom names. Fastlane doesn't seem to support custom tracks, since supply fails with `track must be one of 'production', 'beta', 'alpha'...` etc. This is very problematic for anyone requiring more than one closed track (e.g. a closed alpha and beta). 

Previously it was possible to set `beta` tracks to be closed betas, so having closed beta and alpha tracks was easily achievable with Fastlane. However now that beta tracks are open by default, you need a custom closed track to recreate that functionality, and this is not currently possible with Fastlane (supply).

#### Feature Description

Supply allow upload apk to custom closed track.

#### Alternatives or Workarounds

Workaround currently is to upload apks manually to the custom closed track.

**Comment by joshdholtz** [comment]
@authuser Hey, this is actually implemented in the latest master (https://github.com/fastlane/fastlane/pull/12487). This will get pushed out in the next release 😊
