### ISSUE TITLE
Manually pass provisioning profile and signing identity in lane without opening project in xcode

### ISSUE THREAD

**Issue by shrus672** [fastlane/fastlane#12548]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by RishabhTayal** [comment]
Can you try:

```
update_project_provisioning(
      profile: ENV["sigh_#{app_identifier}_appstore_profile-path"],
      target_filter: 'App'
      )

gym(
      scheme: 'App',
      export_team_id: 'xxxxxxx',
      export_options: {
        provisioningProfiles: {
          app_identifier => ENV["sigh_#{app_identifier}_appstore_profile-name"]
        }
      }
    )
```

`update_project_provisioning` will update your Xcode project setting and set the given provisioning profile. While `gym` will use the provided profile for given `app_identifer`.

**Comment by NikhileshTiwari** [comment]
Will it work with export_method = "development"

**Comment by RishabhTayal** [comment]
I don't think you can use `development` profile to archive and generate ipa.
