### ISSUE TITLE
Couldn't decrypt the repo, please make sure you enter the right password!

### ISSUE THREAD

**Issue by patreu22** [fastlane/fastlane#12554]
### Issue Description

Running `fastlane match init --verbose` doesn't throw an error, but also does not ask for setting a password.
Running `fastlane match` or `fastlane appstore` now asks for a password but I'm not able to enter one. It throws the output you can see in the following.
I know, there are a couple of issues related to that error, but nothing helped me to solve it :(

##### Complete output when running fastlane, including the stack trace and command used

```
MBPro: Patrick$ bundle exec fastlane match init --verbose
[✔] 🚀 
WARN [2018-05-18 20:33:57.00]: Please create a new, private git repository
WARN [2018-05-18 20:33:57.00]: to store the certificates and profiles there
 [2018-05-18 20:33:57.00]: URL of the Git Repo: https://github.com/USER/APP-provisioning-profiles
INFO [2018-05-18 20:34:08.89]: Successfully created './fastlane/Matchfile'. You can open the file using a code editor.
WARN [2018-05-18 20:34:08.89]: You can now run `fastlane match development`, `fastlane match adhoc`, `fastlane match enterprise` and `fastlane match appstore`
INFO [2018-05-18 20:34:08.89]: On the first run for each environment it will create the provisioning profiles and
INFO [2018-05-18 20:34:08.89]: certificates for you. From then on, it will automatically import the existing profiles.
INFO [2018-05-18 20:34:08.89]: For more information visit https://docs.fastlane.tools/actions/match/
<!-- The output of `--capture_output` could contain sensitive data such as application ids, certificate ids, or email addreses, Please make sure you double check the output and replace anything sensitive you don't wish to submit in the issue -->
```

```
MBPro:skeleton Patrick$ bundle exec fastlane match --verbose
[✔] 🚀 
Successfully loaded Appfile at path '/Users/.../fastlane/Appfile'
- app_identifier: 'app.identifier'
-------
Successfully loaded Appfile at path '/Users/.../fastlane/Appfile'
- app_identifier: 'app.identifier'
-------
Successfully loaded Appfile at path '/Users/.../fastlane/Appfile'
- app_identifier: 'app.identifier'
-------
Successfully loaded Appfile at path '/Users/.../fastlane/Appfile'
- app_identifier: 'app.identifier'
-------
Successfully loaded Appfile at path '/Users/.../fastlane/Appfile'
- app_identifier: 'app.identifier'
-------
development
INFO [2018-05-18 20:35:40.63]: Successfully loaded '/Users/.../fastlane/Matchfile' 📄

+---------+----------------------------------------------------------+
|            Detected Values from './fastlane/Matchfile'             |
+---------+----------------------------------------------------------+
| git_url | https://github.com/USER/APP-provisioning-profi  |
|         | les                                                      |
| type    | development                                              |
+---------+----------------------------------------------------------+


+-----------------------+----------------------------------------------------------+
|                             Summary for match 2.95.0                             |
+-----------------------+----------------------------------------------------------+
| verbose               | true                                                     |
| git_url               | https://github.com/USER/APP-provisioning-profi  |
|                       | les                                                      |
| git_branch            | master                                                   |
| type                  | development                                              |
| app_identifier        | ["APP.identifier"]                               |
| keychain_name         | login.keychain                                           |
| readonly              | false                                                    |
| force                 | false                                                    |
| skip_confirmation     | false                                                    |
| shallow_clone         | false                                                    |
| clone_branch_directly | false                                                    |
| force_for_new_devices | false                                                    |
| skip_docs             | false                                                    |
| platform              | ios                                                      |
+-----------------------+----------------------------------------------------------+

INFO [2018-05-18 20:35:40.64]: Cloning remote git repo...
INFO [2018-05-18 20:35:40.64]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-05-18 20:35:40.64]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/USER/APP-provisioning-profiles' '/var/folders/bs/7lc_4jvd59zcyz8pc5bf2y4r0000gn/T/d20180518-12753-1hj79xw'
INFO [2018-05-18 20:35:40.66]: ▸ Cloning into '/var/folders/bs/7lc_4jvd59zcyz8pc5bf2y4r0000gn/T/d20180518-12753-1hj79xw'...
INFO [2018-05-18 20:35:41.76]: ▸ remote: Counting objects: 3, done.
INFO [2018-05-18 20:35:41.76]: ▸ remote: Compressing objects: 100% (3/3), done.
INFO [2018-05-18 20:35:41.88]: ▸ remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
INFO [2018-05-18 20:35:41.89]: ▸ Unpacking objects: 100% (3/3), done.
WARN [2018-05-18 20:35:41.98]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-05-18 20:35:41.98]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-05-18 20:35:41.98]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-05-18 20:35:41.98]: Passphrase for Git Repo: ****
 [2018-05-18 20:35:56.47]: Type passphrase again: ****
ERROR [2018-05-18 20:35:58.59]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/USER/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_https://github.com/USER/APP-provisioning-profiles"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303531383138333535385A00  "20180518183558Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303531383138333535385A00  "20180518183558Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_https://github.com/USER/APP-provisioning-profiles"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2018-05-18 20:35:58.71]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-05-18 20:35:58.71]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-05-18 20:35:58.71]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-05-18 20:35:58.71]: Passphrase for Git Repo: 
```

### Environment

<details>
  <pre>### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("app.identifier") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.95.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |c
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.8        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

</pre>
</details>

**Comment by rraina** [comment]
Having the same issue here --> running into a cycle.

Fastlane version: 2.95
Openssl: Libre 2.2.7

**Comment by patreu22** [comment]
Ah, good thing to mention, for me it's:
```
$ openssl version -a
OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by patreu22** [comment]
Nobody with a hint? :(

**Comment by mbuchetics** [comment]
We just experienced the same issue.

**Comment by mbuchetics** [comment]
Still an issue, go away @fastlane-bot

**Comment by DmitrijKotsur** [comment]
Have the same issue too.
