### ISSUE TITLE
[Testflight] UnexpectedResponse "You can’t submit a build for testing if another build is already in review. Wait until your other build has been reviewed, and resubmit this build."

### ISSUE THREAD

**Issue by ulfgebhardt** [fastlane/fastlane#12551]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If there is the same VersionCode (e.g. 1.2.3) already pushed to testflight and still in testing, fastlane fails with an UnexpectedResponse Error, even tho the build number is different.

Please catch this and make it an option to ignore!

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[12:31:55]: Successfully finished processing the build 0.7.7 - 100881
[12:31:59]: Successfully set the changelog for build
[12:31:59]: Distributing new build to testers: 0.7.7 - 100881
+------------------------------------+---------------------------------------------------------------------------------------------------------+
|                                                                 Lane Context                                                                 |
+------------------------------------+---------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                     |
| PRODUCE_APPLE_ID                   | 1341311162                                                                                              |
| PLATFORM_NAME                      | ios                                                                                                     |
| LANE_NAME                          | ios alpha                                                                                               |
| BUILD_NUMBER                       | 100881                                                                                                  |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/travis/Library/Keychains/login.keychain-db"                                                     |
| SIGH_PROFILE_TYPE                  | app-store                                                                                               |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"de.democracy-deutschland.clientapp.alpha"=>"match AppStore de.democracy-deutschland.clientapp.alpha"} |
| IPA_OUTPUT_PATH                    | /Users/travis/build/demokratie-live/democracy-development/client/ios/democracyclient.ipa                |
| DSYM_OUTPUT_PATH                   | /Users/travis/build/demokratie-live/democracy-development/client/ios/democracyclient.app.dSYM.zip       |
| XCODEBUILD_ARCHIVE                 | /Users/travis/Library/Developer/Xcode/Archives/2018-05-18/democracyclient 2018-05-18 12.12.22.xcarchive |
+------------------------------------+---------------------------------------------------------------------------------------------------------+
[12:32:00]: {"code"=>"You can’t submit a build for testing if another build is already in review. Wait until your other build has been reviewed, and resubmit this build.", "description"=>"Failed to submit build for review."}
+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | produce                | 5           |
| 3    | increment_build_number | 3           |
| 4    | automatic_code_signing | 0           |
| 5    | setup_travis           | 0           |
| 6    | sync_code_signing      | 2           |
| 7    | build_app              | 668         |
| 💥   | upload_to_testflight   | 526         |
+------+------------------------+-------------+
[12:32:00]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {"code"=>"You can’t submit a build for testing if another build is already in review. Wait until your other build has been reviewed, and resubmit this build.", "description"=>"Failed to submit build for review."}
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/spaceship/lib/spaceship/test_flight/client.rb:299:in `handle_response'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/spaceship/lib/spaceship/test_flight/build.rb:212:in `submit_for_testflight_review!'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/pilot/lib/pilot/build_manager.rb:173:in `distribute_build'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/pilot/lib/pilot/build_manager.rb:99:in `distribute'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:65:in `block (2 levels) in parsing_binding'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
  /Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `load'
  /Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `<top (required)>'
The command "DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios alpha" exited with 1.
  </pre>
</details>

### Environment

https://travis-ci.org/demokratie-live/democracy-development/jobs/380659794

### HowToTest

- Push App to Testflight with a specific Version Code (e.g. 1.2.3)
- Push the same Version with a new Build Number immediately(<= 6h) after the first Push.
- ...
- Profit

**Comment by ulfgebhardt** [comment]
@RishabhTayal make an option to ignore this specific error

-> a more general approch would be to make an option to ignore definable errors

**Comment by RishabhTayal** [comment]
@ulfgebhardt I don't think it's a good idea to ignore that error. Maybe we could add a new option to reject the previous build from app review and then resubmit this new version.

**Comment by RishabhTayal** [comment]
@joshdholtz can you pitch in?

**Comment by ulfgebhardt** [comment]
@RishabhTayal Getting the old build out and the new in would be awesome - prefere that option <3

**Comment by RishabhTayal** [comment]
I will look into it.

**Comment by RishabhTayal** [comment]
@ulfgebhardt I have a WIP PR for this. #12565

**Comment by RishabhTayal** [comment]
@ulfgebhardt Could you point your `Gemfile` to my branch and help me test it.

**Comment by ReggaePanda** [comment]
@RishabhTayal thank u very much for your pr, we will try it 😃 

```
    upload_to_testflight(
      …
      reject_previously_submitted_build: true
    )
```
is this configuration correct?

**Comment by RishabhTayal** [comment]
@ReggaePanda Yes that is correct. 👍

**Comment by ulfgebhardt** [comment]
https://cdn.discordapp.com/attachments/385901951881052161/451462859814207498/Bildschirmfoto_2018-05-30_um_21.11.37.png

Confirming that this works.

Great job @RishabhTayal

**Comment by RishabhTayal** [comment]
🕺 woot woot
