### ISSUE TITLE
Exit status: 70 even though Archive Succeeds

### ISSUE THREAD

**Issue by daviskoh** [fastlane/fastlane#12557]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Tried solutions from and looked at the following issues to name a few:

https://github.com/fastlane/fastlane/issues/10543
https://github.com/fastlane/fastlane/issues/11514
https://github.com/fastlane/fastlane/issues/10522
https://github.com/fastlane/fastlane/issues/10483
https://github.com/fastlane/fastlane/issues/10616
https://github.com/fastlane/fastlane/issues/10449

### Issue Description

**NOTE**: sensitive data has been redacted w/ `***`

Running

```
BITRISE_SOURCE_DIR="." MATCH_PASSWORD="***" FASTLANE_PASSWORD="***" bundle exec fastlane fuck --verbose
```

which results in:

```
** EXPORT FAILED **
ERROR [2018-05-19 00:59:29.13]: Exit status: 70
```

even though

```
** ARCHIVE SUCCEEDED **
```

##### Complete output when running fastlane, including the stack trace and command used

Unfortunately, when I run the above command w/ the `--capture_output` flag, the process just hangs and terminates w/o any errors

<details>
  <pre>security: SecKeychainItemImport: The specified item already exists in the keychain.
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
2018-05-19 01:07:49.782 xcodebuild[63309:11339147] [MT] PluginLoading: Required plug-in compatibility UUID EE23884D-A5C0-4163-94CF-DBBF3A5ED8D6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-05-19 01:07:49.783 xcodebuild[63309:11339147] [MT] PluginLoading: Required plug-in compatibility UUID EE23884D-A5C0-4163-94CF-DBBF3A5ED8D6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-05-19 01:07:49.783 xcodebuild[63309:11339147] [MT] PluginLoading: Required plug-in compatibility UUID EE23884D-A5C0-4163-94CF-DBBF3A5ED8D6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-05-19 01:07:49.784 xcodebuild[63309:11339147] [MT] PluginLoading: Required plug-in compatibility UUID EE23884D-A5C0-4163-94CF-DBBF3A5ED8D6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-05-19 01:07:49.937 xcodebuild[63309:11339147] WARNING: Failed to load plugin at path: "/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signing blocked mmap() of '/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2'
	/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2, NSDebugDescription=dlopen_preflight(/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signing blocked mmap() of '/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2'
	/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1, NSBundlePath=/Users/daviskoh/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin, NSLocalizedDescription=The bundle “XVim2” couldn’t be loaded because it is damaged or missing necessary resources.}</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.95.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  # ENV['BITRISE_SOURCE_DIR'] = /Users/vagrant/git

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "***",
      devices: ["iPhone 8"],
      configuration: "Debug",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Debug.xcconfig"
    )
  end

  lane :fuck do
    match(
      app_identifier: "com.***.***",
      type: "adhoc",
      readonly: true
    )

    gym(
      scheme: "***",
      clean: true,
      output_directory: "#{ENV['BITRISE_SOURCE_DIR']}/build",
      output_name: "***-***.ipa",
      configuration: "Alpha",
      export_method: "ad-hoc",
      xcargs: "ARCHIVE=YES",
      export_options: {
        method: "ad-hoc",
        thinning: "<thin-for-all-variants>",
        provisioningProfiles: {
          "com.***.***": "match AdHoc com.***.***"
        },
        method: "ad-hoc",
        signingStyle: "manual"
      },
      # export_xcargs: "-allowProvisioningUpdates",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Alpha.xcconfig"
    )
  end

  desc "Submit a new ALPHA Build to Apple TestFlight"
  lane :alpha do
    ENV["AWS_COGNITO_USER_POOL_SECRET"] = ENV["AWS_COGNITO_USER_POOL_SECRET_alpha"]
    ENV["GOOGLE_PLACES_AUTOCOMPLETE_KEY"] = ENV["GOOGLE_PLACES_AUTOCOMPLETE_KEY_alpha"]

    match(
      app_identifier: "com.***.***",
      type: "ad-hoc",
      readonly: true
    )

    gym(
      scheme: "***",
      configuration: "Alpha",
      export_method: "ad-hoc",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Alpha.xcconfig"
    )

    scan(
      scheme: "***",
      devices: ["iPhone 8"],
      skip_build: true,
      configuration: "Alpha",
      xcconfig: "#{ENV['BITRISE_SOURCE_DIR']}/Config/Alpha.xcconfig"
    )

    # increment_build_number
    # upload_to_testflight
    # match(type: "appstore") # more information: https://codesigning.guide
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Submit a new BETA Build to Apple TestFlight"
  lane :beta do
    # ENV["AWS_COGNITO_USER_POOL_SECRET"] = ENV["AWS_COGNITO_USER_POOL_SECRET_beta"]

    #increment_build_number
    #gym(scheme: "***", xcconfig: "Alpha.xcconfig")
    #upload_to_testflight
    # match(type: "appstore") # more information: https://codesigning.guide
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    #gym(scheme: "***") # Build your app - more options available
    #deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "***@***.com" # Your Apple email address

for_lane :local do
  team_id "***" # Developer Portal Team ID
  app_identifier 'com.***.***'
end

for_lane :dev do
  team_id "***" # Developer Portal Team ID
  app_identifier 'com.***.***'
end

for_lane :alpha do
  team_id "***" # Developer Portal Team ID
  app_identifier 'com.***.***'
end


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.95.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.2        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.2        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| synx                      | 0.2.1        |
</details>

*generated on:* **2018-05-19**
</details></pre>
</details>

**Comment by daviskoh** [comment]
Yes I've seen it

**Comment by daviskoh** [comment]
Is there any update on this? Archive and export work fine in Xcode

**Comment by daviskoh** [comment]
I keep getting these

```
error: exportArchive: DateTimePicker.framework does not support provisioning profiles.

Error Domain=IDEProvisioningErrorDomain Code=10 "DateTimePicker.framework does not support provisioning profiles." UserInfo={NSLocalizedDescription=DateTimePicker.framework does not support provisioning profiles., NSLocalizedRecoverySuggestion=DateTimePicker.framework does not support provisioning profiles, but provisioning profile match AdHoc com.***.*** has been manually specified. Remove this item from the "provisioningProfiles" dictionary in your Export Options property list.}
```

but dont know why. I dont think its a Cocoapods issue as ive already tried every possible variation of adding

```
config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
```

in the Podfile

ex: 

```
installer.pods_project.build_configurations.each do |config|
    config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
  end
```

another ex

```
target.build_configurations.each do |config|
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
```

**Comment by daviskoh** [comment]
any updates on this? this issue is becoming stale

**Comment by romk1n** [comment]
have kind of the same issue

**Comment by iOSleep** [comment]
same to me
