### ISSUE TITLE
xcversion action fails when spotlight indexing is disabled

### ISSUE THREAD

**Issue by marcomorain** [fastlane/fastlane#12556]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running the following on CircleCI on a macOS container with `Xcode 9.3 Build 9E145` installed, the `xcversion` action fails to detect that the current version of xcode satisfies the requirement. The following `Fastfile` fails:

```ruby
default_platform(:ios)

platform :ios do
  lane :custom_lane do
    xcversion(version: "9.3.0")
  end
end
```

Config:

```yaml
version: 2
jobs:
  build:
    macos:
      xcode: 9.3.0
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec fastlane custom_lane --capture_output
```

Example: https://circleci.com/gh/marcomorain/python/229

The reason for this is that we disable spotlight indexing on the build images in an attempt to prevent the disk IO from interfering with builds.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
bundle exec fastlane custom_lane --capture_output
^D^D[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [⠦] 🚀 [⠧] 🚀 [✔] 🚀 
[12:54:52]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
DEBUG [2018-05-18 12:54:52.44]: Checking if there are any plugins that should be loaded...
INFO [2018-05-18 12:54:52.65]: ------------------------------
INFO [2018-05-18 12:54:52.65]: --- Step: default_platform ---
INFO [2018-05-18 12:54:52.65]: ------------------------------
INFO [2018-05-18 12:54:52.65]: Driving the lane 'ios custom_lane' 🚀
INFO [2018-05-18 12:54:52.65]: -----------------------
INFO [2018-05-18 12:54:52.65]: --- Step: xcversion ---
INFO [2018-05-18 12:54:52.65]: -----------------------
INFO [2018-05-18 12:54:52.65]: gem 'xcode-install' is already installed
WARN [2018-05-18 12:54:52.90]: Lane Context:
INFO [2018-05-18 12:54:52.90]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios custom_lane"}
ERROR [2018-05-18 12:54:52.90]: Cannot find an installed Xcode satisfying '9.3.0'
INFO [2018-05-18 12:54:52.90]: Successfully generated documentation at path '/Users/distiller/project/fastlane/README.md'
ERROR [2018-05-18 12:54:52.93]: fastlane finished with errors
ERROR [2018-05-18 12:54:52.93]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
Exited with code 1
</pre>
</details>

### Suggested Fix

The `xcversion` action could run `xcodebuild -version` as quick check to see if the currently selected xcode satisfies the requirements, before trying to enumerate the installed xcodes using Spotlight.

**Comment by marcomorain** [comment]
Still an issue 👍

**Comment by joshdholtz** [comment]
@marcomorain Heyyyyy, how's it going?! Long time no talk 😊 So... I'm unsure exactly where this issue should be solved 🤔 I don't wan to sidestep what https://github.com/KrauseFx/xcode-install actually does since the `xcversion` action pretty much directly calls this code but also what you are saying does make sense as a quick check...

The thing with `xcodebuild -version` is that it return the following which we need to have some weirdness in searching for that version number...
```sh
Xcode 9.4
Build version 9F1027a
```

Maybe instead... we add another if/else around here to use Ruby's `Dir["some/path/stuff"]` in here to find the Xcode versions with pure Ruby? https://github.com/KrauseFx/xcode-install/blob/master/lib/xcode/install.rb#L394

**Comment by marcomorain** [comment]
Hi @joshdholtz 

Yeah, I'm not sure where, architecturally, the best place to check is.

As a user, the situation is as follows:

- I have Xcode 9.4 installed, and it is selected with `xcode-select` as the default version run with `xcodebuild`.
- I ask `Fastlane` to ensure that Xcode 9.4 is installed before building.
- Then when I build, Fastlane produces an error telling me that Xcode 9.4 is not installed.

I would personally put some code into the `xcode_version` action to check if current version . of Xcode satisfies the requirements before deferring to `xcode-install`, to isolate the use of `xcode-install` in the common case.

**Comment by pykaso** [comment]
Any progress with this issue?

**Comment by AdamBCo** [comment]
If you are looking for a solution, please run the following command in your travis file:

<code>sudo mdutil -i on /<code>
