### ISSUE TITLE
Could not find action make_changelog_from_jenkins.

### ISSUE THREAD

**Issue by WinterKirk** [fastlane/fastlane#1256]
Hi, trying to use the new action "make_changelog_from_jenkins" and am getting the following error:

> [!] Could not find action or lane 'make_changelog_from_jenkins'. Check out the README for more details: https://github.com/fastlane/fastlane

Lane only contains "make_changelog_from_jenkins" and nothing else. Using Fastlane version 1.55.0 on Yosemite. Thanks!

**Comment by KrauseFx** [comment]
Sorry, this action is not live yet, will be available with the next release, which will happen today :+1:

**Comment by KrauseFx** [comment]
It's live now :rocket:
