### ISSUE TITLE
Build IPA with fastlane using jenkins 

### ISSUE THREAD

**Issue by NikhileshTiwari** [fastlane/fastlane#12567]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Is xcode installation  required for build IPA file using fastlane jenkin combintion ?

#### Question Description
I am trying to build a react native app through fastlane on jenkins. I am using below script

_export PATH="$PATH:/usr/local/bin"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
pwd
cd ../../../../../../
cd /this/is/path/to/ios/folder
pwd
security unlock-keychain -p "/Users/usernamefolder/Library/Keychains/login.keychain"
fastlane gym --export_method "development" --scheme “ProjectSchemeName”_

Source I am taking from git repo with all fastlane related folder and fastfile checked in.

I am getting below error in logs

_Started by user XXXXXXX
Building in workspace /Users/XXXXX/.jenkins/workspace/ProjectName
[Scheme Name] $ /bin/sh -xe /var/folders/cd/rdydx7910k1dccpgnks84n5mxt3j95/T/jenkins3957881768527977509.sh
+ export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ pwd
/Users/xxxxx/.jenkins/workspace/SchemeName
+ cd ../../../../../../
+ cd /proejct/location/projectname/ios
+ pwd
/actual/projectrootfolder/projectname/ios
+ security unlock-keychain -p /Users/xxxxx/Library/Keychains/login.keychain
+ fastlane gym --export_method development --scheme SchemeName
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.1/lib/fastimage.rb:68: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[01:37:23]: [33mfastlane detected a Gemfile in the current directory[0m
[01:37:24]: [33mhowever it seems like you don't use `bundle exec`[0m
[01:37:24]: [33mto launch fastlane faster, please use[0m
[01:37:24]: 
[01:37:24]: [36m$ bundle exec fastlane gym --export_method development --scheme SchemeName [0m
[01:37:24]: 
[01:37:24]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[31m
[!] Unable to locate Xcode. Please make sure to have Xcode installed on your machine[0m
Build step 'Execute shell' marked build as failure
Finished: FAILURE_

**Comment by RishabhTayal** [comment]
@NikhileshTiwari As mentioned in the error output, Xcode **is required** to compile the code. It's not only a `fastlane gym` requirement, it's a basic requirement for compiling the code through any tool.

**Comment by sprabhuanand** [comment]
Yes, it is.
