### ISSUE TITLE
Support Android App Bundle [Supply]

### ISSUE THREAD

**Issue by Sparow199** [fastlane/fastlane#12569]
### Feature Request
Add support for [Android App Bundles](https://developer.android.com/platform/technology/app-bundle/).
#### Motivation Behind Feature
Google added new upload format for publishing Android applications on Play store.

#### Feature Description
- Android App Bundle uses [Android Publisher v3](https://developers.google.com/android-publisher/api-ref/edits/bundles/upload).

- Maximum `.aab` file size is 100Mo (May change in the future).

#### Alternatives or Workarounds
Upload Android App Bundles with Google Play console instead of using Fastlane.

**Comment by bernaferrari** [comment]
How is this different from #12568?

**Comment by Sparow199** [comment]
Hello @bernaferrari, the two issues was  opened in the same date. Android app bundle support was released on Supply. It's time to close my issue.
