### ISSUE TITLE
Full list of possible Appfile values?

### ISSUE THREAD

**Issue by forgot** [fastlane/fastlane#1257]
The Appfile documentation lists eight possible values. 

```Ruby
app_identifier "net.sunapps.1" # The bundle identifier of your app
apple_id "felix@krausefx.com" # Your Apple email address

team_name "Felix Krause" # Developer Portal Team Name
team_id "Q2CBPJ58CA" # Developer Portal Team ID
apple_dev_portal_id "portal@company.com"  # Developer Portal Account

itc_team_name "Company Name" # # iTunes Connect Team Name
itc_team_id "18742801" # iTunes Connect Team ID
itunes_connect_id "tunes@company.com"     # iTunes Connect Account
```

Are there any other values that can be added to the Appfile?

I have a rather complicated setup, and I'm trying to keep from repeating myself as much as possible.

**Comment by KrauseFx** [comment]
That looks about right, check out the source file for a full list https://github.com/fastlane/credentials_manager/blob/master/lib/credentials_manager/appfile_config.rb#L61-L107 :+1:

**Comment by forgot** [comment]
Thank you for pointing me to that!
