### ISSUE TITLE
Beta App Review Notes upload_to_testflight distribute_external

### ISSUE THREAD

**Issue by MarkAMcCorkle** [fastlane/fastlane#12573]
### Feature Request
Include Beta App Review Information -> Review Notes in upload_to_testflight
#### Motivation Behind Feature

Required for Beta App Review Team
#### Feature Description

When using the `distribute_external` flag for `upload_to_testflight` there isn't an option to include Release Notes for the Beta App Review Team. I don't want to include the review notes in the Beta App Description area as this is different information than what our beta testers need to see. 

#### Alternatives or Workarounds

Manually add them using iTunes Connect gui. 

Not that I am aware of.

**Comment by RishabhTayal** [comment]
@MarkAMcCorkle I believe this already exists in `upload_to_testflight` action. You can use the `changelog` option. More [docs here](https://docs.fastlane.tools/actions/testflight/#parameters)

**Comment by MarkAMcCorkle** [comment]
@RishabhTayal From my testing, the `changelog` gets applied to the **What's New** portion of **Test Details** for beta testers to see what to test for that specific build. I am referring to the **Beta App Review Information** section under the **Test Information** tab. I can't say this is a top priority since once you set it for an app it does tend to persist across versions although if we want to fully automate app creation thru delivery, this field would be needed. Every other field I need is in there except that one from what I can tell. Using the `notes` field works fine for the **App Review Notes** but this request is specific to the **Beta App Review Information**.
