### ISSUE TITLE
[!] The request could not be completed because: {"authType"=>"sa"}

### ISSUE THREAD

**Issue by danivegamx** [fastlane/fastlane#12577]
### Question Checklist

- [ ✅ ] Updated fastlane to the latest version
- [ ✅ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ✅ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Running fastlane for an adhoc distribution is not working. Error below.

#### Question Description

When I run via `bundle exec fastlane beta` I got this:

[!] The request could not be completed because: {"authType"=>"sa"} aa=5A52AF019EF22EE5C2D8BBA8AADA6E4F; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=57NJeJgkumOF6rAbV4AvInJhJaP4TxVrExywB7p+W1pyLjWuY0gBrxkAECrx0bG3+w==; Max-Age=31536000; Expires=Tue, 21-May-2019 22:41:58 GMT; Domain=apple.com; Path=/; Secure; HttpOnly

This is my configuraiton file:

```

default_platform(:ios)

lane :beta do
    get_certificates
    get_provisioning_profile(
        username: ENV['APPLE_TEAM_DEV_ID'],
        adhoc: true,
        filename: "AdHoc_com.company.mobileprovision",
        app_identifier: "com.company"
    )
    get_info_plist_path(
        build_configuration_name: "staging",
        target: "staging"
    )
    increment_version_number_in_plist(
        target: "staging",
        bump_type: "patch"
    )
    gym(
        scheme: "staging",
        export_method: "ad-hoc",
        export_xcargs: "-allowProvisioningUpdates"
    )
    aws_s3(
        access_key: ENV['S3_ACCESS_KEY'],
        secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
        bucket: "bucket-name",
        region: "region",
        ipa: "appname.ipa",
        app_directory: "beta"
    )
end
```

Any idea?

**Comment by AaronSofaer** [comment]
I'm also getting this when I run `match`, after it decrypts the certs repo and then goes to check the validity of the certs with Apple. Thought it was on my end!

**Comment by cpetzel** [comment]
This is currently failing for us too with `cert`

**Comment by iosdevben** [comment]
Me too!

**Comment by joshdholtz** [comment]
Hello, everyone! We are looking into this 💪 👀

**Comment by danivegamx** [comment]
Awesome, thanks a lot

**Comment by kirushi** [comment]
@joshdholtz that's great to hear :D

**Comment by lalitb** [comment]
Got same error. This helped me - login to appleid.apple.com  website using the same apple credentials you are using in AppCenter. After login, accept/continue any Privacy information displayed, and then try using fastlane again.

    On Tuesday, May 22, 2018, 4:40:37 AM GMT+5:30, Dani Vega <notifications@github.com> wrote:  
 
 
Awesome, thanks a lot

**Comment by getaaron** [comment]
If you login to itunesconnect.apple.com with your Apple ID, you should see this new privacy prompt:

<img width="763" alt="screen shot 2018-05-21 at 7 09 39 pm" src="https://user-images.githubusercontent.com/789577/40334432-c9fa8624-5d2b-11e8-9eb3-72ee404dfb55.png">

Once you select "continue", does this resolve your issue?

**Comment by sungjin0213** [comment]
That resolved the issue for me for fastlane pem. Thanks!

**Comment by kirushi** [comment]
Confirmed that this fixes the issue for me too!

**Comment by danivegamx** [comment]
Solved, but I had to change to another Apple ID because the one I was using wasn't eligible for iTunes connect (whut?) Thanks

**Comment by joshdholtz** [comment]
@danivegamx Going to keep this open for now for visibility and until I make a code fix for a prettier error 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stevemoser** [comment]
Hmm, the above fix didn't work for me 😭

**Comment by joshdholtz** [comment]
@stevemoser Gotta ask this but did you accept it under **all** your iTunesConnect accounts that you use? 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bencmorrison** [comment]
Am I understanding this correctly? In order for this to work, the account we are using for match has to also be on iTC?

**Comment by pangers** [comment]
When I went to the iTunes Connect site, I was already logged in automatically. I had to sign out and sign back in to get the prompt.

**Comment by joshdholtz** [comment]
Going to appleid.apple.com as @getaaron suggested also shows the same privacy step 💪 

<img width="1043" alt="screen shot 2018-05-21 at 7 42 56 pm" src="https://user-images.githubusercontent.com/401294/40336458-4e90d958-5d2f-11e8-9904-6b19f6d2a489.png">

**Comment by enso123456** [comment]
Thanks @getaaron

**Comment by bencmorrison** [comment]
Thanks @getaaron, it appears to be working for me as well!

**Comment by mmarvick** [comment]
Also getting this for `{"authType"=>"hsa"}` -- the same solution worked (including this comment for Google-ability).

**Comment by nevil** [comment]
I went to itunes connect and try to login with our robot account.
Clicked Continue and got the below. But the account could then be used by fastlane again...

<img width="744" alt="itc" src="https://user-images.githubusercontent.com/36905/40338337-82417e4e-5daf-11e8-8fc7-61ec441fb3fe.png">

**Comment by joshdholtz** [comment]
@nevil Try going to https://appleid.apple.com and trying this 😊

**Comment by joshdholtz** [comment]
@mmarvick I have not seen `hsa` yet! Is this account configured any different? I have no idea how but just curious how `hsa` showed up 😇

**Comment by nevil** [comment]
@joshdholtz No need to do that. fastlane can login after accepting the privacy information even thought the account is not enabled for iTunes Connect.

**Comment by mmarvick** [comment]
@joshdholtz great question! I'm not sure. Here's a comment elsewhere in the project. Maybe it's because I have 2FA on the account?

https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/spaceship/lib/spaceship/two_step_client.rb#L160

**Comment by joshdholtz** [comment]
@mmarvick Ahhh, that could do! That's for finding that 😊 I've included `hsa` is my fix pretty error fix 👌

**Comment by joshdholtz** [comment]
This will be released in `2.96.0` which _should_ be going out later tonight or tomorrow AM 💪

**Comment by korvan** [comment]
@joshdholtz The same issue appears for "non-sa" authType. Add it please to your pretty fix as well :) 
 `send_shared_login_request': [!] The request could not be completed because: (Spaceship::Tunes::Error) {"authType"=>"non-sa"}

**Comment by joshdholtz** [comment]
@korvan Interesting! Didn't know `non-sa` was a type 😊 Will fix!

**Comment by atreat** [comment]
I'm also getting this with the response
```
Spaceship::Tunes::Error: {"authType"=>"hsa2"}
```

I also have 2FA setup on the account

@joshdholtz I don't know if you want to update the tidbit in #12578 to support that as well.

**Comment by joshdholtz** [comment]
@atreat lol, how many account types are there?! 🙉  I will add this as well. Thanks for letting me know ❤️

**Comment by LamourBt** [comment]
if you didn't see the privacy screen, log out and log back into iTunesConnect, it shall appear :)

**Comment by nneuberger1** [comment]
Is anyone seeing the issue still using an enterprise apple account?   We are seeing this after logging into itunesconnect.apple.com

"Your Apple ID isn't enabled for iTunes Connect."

**Comment by stevemoser** [comment]
@joshdholtz I had to accept it twice. I logged in, accepted. Logged out, logged in, accepted again, and it finally worked. I guess the first time didn't take.

**Comment by nneuberger1** [comment]
@joshdholtz  No that didn't help my issue.  I've signed in several times after that even and don't see the privacy popup any longer.  We're running our builds via bamboo and fastlane on a build server and have tried several things like restarting the Mac, but not much luck yet. For safety, we escalated to Apple to see if it may have anything to do with Enterprise accounts.

Any other ideas?

I'm trying to sign in to Apple via Xcode Preferences on our build server in hopes that will pass the issue as it may be possibly cached locally.

**Comment by nneuberger1** [comment]
If it helps the original error this morning, prior to fastlane update, we saw this in the logs.


[!] The request could not be completed because:
22-May-2018 08:33:10 | {"authType"=>"sa"}

But I don't necessarily know what "sa" is...

In some cases, I've seen while debugging these issues I may get a prompt to "sign in" on our build box during a build.

**Comment by joshdholtz** [comment]
@nneuberger1 What action/tool is this error happening on? I'm trying to reproduce this error on my side with my enterprise account

**Comment by nneuberger1** [comment]
@joshdholtz sorry false alarm.  I accepted the ToS in Apple with our global Enterprise account and NOT the one we we're using in our AppFile

`apple_id "email@domainname.com" # Your Apple email address`

After accepting the ToS for that account, our build worked fine.  Sorry for the false alarm.  And thank you all for your help.

**Comment by ryancarlson** [comment]
@joshdholtz not sure if you got the answer to this question:

> @stevemoser Gotta ask this but did you accept it under all your iTunesConnect accounts that you use? 🙃

but I accepted for just our "CI builder" account and that got me past this issue. I'm 100% positive that not everyone in our organization has accepted, yet.

**Comment by robmaceachern** [comment]
@joshdholtz thanks for getting the [PR](https://github.com/fastlane/fastlane/pull/12578) done so quickly!

One minor enhancement would be to include the username in the error message to make it clear which account has the prompt. e.g. "Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) _with {username}_ to acknowledge the statement."

I was being dumb and was logging in/out of my development Apple ID trying to accept the prompt instead of the CI account before it finally clicked 😭💡😃✅

**Comment by lalitb** [comment]
@joshdholtz can we handle 2fa accounts same way. As of now, we get below exception for 2fa account which haven't accepted privacy:
```
/usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:478:in `send_shared_login_request': {"authType"=>"hsa2"} (Spaceship::Tunes::Error)
aa=A2027CD2C3CCF256D7FF5C6F6D1CF238; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=wyKBpX2oJTI/U8OrntnIQWWbb/3X7sGb8f2pABDZYcZo+RE=; Max-Age=31536000; Expires=Thu, 23-May-2019 05:17:34 GMT; Domain=apple.com; Path=/; Secure; HttpOnly
	from /usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/portal/portal_client.rb:27:in `send_login_request'
	from /usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:662:in `do_login'
	from /usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:363:in `login'
	from /usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:71:in `login'
	from /usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from /usr/local/rvm/gems/ruby-2.4.2/gems/fastlane-2.96.0/spaceship/lib/spaceship/portal/spaceship.rb:98:in `login'
	from /tmp/a.rb:3:in `<main>'
```

**Comment by joshdholtz** [comment]
@lalitb `non-sa` and `hsa2` should be in `2.96.1` 😊

**Comment by brad** [comment]
:+1: 2.96.1 does indeed display a much friendlier error, however the recommended solution does not fix the problem for me. The privacy statement appears every time I login no matter how many times I accept it.
1. Login
2. Answer security questions
3. Select "Continue" on the privacy prompt
4. Logout
5. Go to step 1

I have repeated this 4 times with the login used by fastlane. Just me?

**Comment by brad** [comment]
Tried on a different network and this time it took. The network it didn't work on was my AT&T Mobley hotspot. I occasionally encounter weird quirks like this on that network ([here's](https://forums.att.com/t5/Data-Messaging-Features-Internet/Public-IP-for-my-Mac-connected-via-iPhone-7-Plus-personal/td-p/5388709) another one), so it's not entirely surprising. Sorry for the noise, but hopefully it helps somebody else as well.

**Comment by inturbidus** [comment]
Good to see other CLT devs here @stevemoser

**Comment by jamesgmorgan** [comment]
I had to logout and login again to see the notice but acknowledged it and everything works again.  Way not to do GDPR, Apple :-/

**Comment by garyhooper** [comment]
I continue to get an error: "Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement".

I have logged into both (and developer.apple.com) multiple times from different networks. No statement is presented to acknowledge, yet fastlane produces the error above.

**Comment by inturbidus** [comment]
I had to switch browsers from Chrome to Safari. Logout and log back in to ITC.

**Comment by garyhooper** [comment]
I tried that, different browser on a different computer. Still no joy.

**Comment by getaaron** [comment]
@garyhooper are you logging in with the same Apple ID specified in `fastlane/Appfile`? A few users with your issue have been logging in with a personal account while fastlane is configured to use a machine account.

**Comment by garyhooper** [comment]
Yes, I have verified that they are the same.

**Comment by garyhooper** [comment]
Sill not working. I am running under Jenkins...is anyone else?  More detail under #12675.

**Comment by coneman** [comment]
Login to https://appstoreconnect.apple.com/ instead of https://itunesconnect.apple.com to accept the privacy statement.

**Comment by garyhooper** [comment]
fastlane is still failing.

When logging in to https://appstoreconnect.apple.com/, no privacy statement acceptance was presented; it went straight to the dashboard.

**Comment by mrh-is** [comment]
I just solved this by checking all three of:
1. [appleid.apple.com](https://appleid.apple.com/)
    - I had to log into a device with the Apple ID in question before I could log into Apple ID in the browser, heads up
2. [developer.apple.com](https://developer.apple.com/)
3. [appstoreconnect.apple.com](https://appstoreconnect.apple.com/)

**Comment by garyhooper** [comment]
I have logged into each of https://appleid.apple.com, https://developer.apple.com, https://itunesconnect.apple.com, and https://appstoreconnect.apple.com from multiple browsers (including Safari) and from multiple (mac) computers.  No privacy acceptance is required (completed several days ago), yet `fastlane certs` still fails.

@mrh-is, can you clarify what you mean by "I had to log into a device with the Apple ID in question before I could log into Apple ID in the browser, heads up"?

**Comment by mrh-is** [comment]
@garyhooper I wan't able to log into [appleid.apple.com](https://appleid.apple.com/) until I had already logged into an iOS device with that Apple ID.

**Comment by garyhooper** [comment]
on an iOS device, i have logged into both itunesconnect app and website, plus app store.  for all i logged out and back in again.  still fails.

**Comment by getaaron** [comment]
I think @mrh-is meant sign in via Settings - iCloud on iOS or something. But I doubt that will fix anything.

At this point the only two things I can think of are:

1. logging the exact HTTP response headers & body in case there’s some info there. You could try running the Ruby commands via IRB, or making a curl request 

2. Logging into https://iforgot.apple.com/ and going through the account unlock flow mentioned in https://support.apple.com/en-us/HT204106. However if your account were locked I’d expect bigger problems

**Comment by garyhooper** [comment]
RESOLVED. All members associated with the team must accept that privacy statement, regardless of which user's account is used to get the certificates.

**Comment by inturbidus** [comment]
So glad. No more notifications for this issue! Hahaha.

**Comment by getaaron** [comment]
@garyhooper I’m pretty sure that’s not it since there are definitely people on my team who haven’t accepted it, but glad to hear you got it working. Maybe you have something overriding the account specified in the Appfile?

**Comment by garyhooper** [comment]
I don’t see anything overriding the Appfile. I have 4 emails associated with the team. 2 had accepted, including the appfile id. Accepting the other two resulted in success.
