### ISSUE TITLE
Fastlane Swift: What is the proper syntax to specify  iTunes Connect Team ID, or the Team Name in your fastlane/Appfile?

### ISSUE THREAD

**Issue by benrudhart** [fastlane/fastlane#12586]
Question Subject
I am using Fastlane swift (beta). The Appfile got created automatically. with the required variables for Teamid/ itcTeamId

When building my betalane I still get notified that there are several teams and I have to choose on.

Question:
what is the proper syntax/ name of the variables I should use in the Appfile in order to specify the identifiers?

**Comment by ipedro** [comment]
Here's an example from the docs:

```ruby
app_identifier "net.sunapps.1"
apple_id "felix@krausefx.com"
team_id "Q2CBPJ58CC"

for_platform :ios do
  team_id '123' # for all iOS related things
  for_lane :test do
    app_identifier 'com.app.test'
  end
end
```

You can set your globals, and then override them on whichever lanes make sense to you. Hope that helps, you can check more examples here.

https://docs.fastlane.tools/advanced/#appfile

**Comment by benrudhart** [comment]
Thank you but I already saw this documentation and it didn't help. I'm working with Fastlane swift. I do have a `/fastlane/Appfile.swift` wich states all the following identifiers. But inside the `/fastlane/swift/Appfile.swift` (which states that it is autogenerated) all variables are empty:
```
// the autogenerated code
var appIdentifier: String { return "" } 
var appleID: String { return "" }
var teamID: String { return "" }
var itcTeam: String? { return nil }
```

Hence I'm wondering how the `fastlane/Appfile.swift` has to look, in order to make this work. The documentation doesn't contain any information on the swift file (yet)/ I haven't been able to find it.
