### ISSUE TITLE
Support Android on testfairy action

### ISSUE THREAD

**Issue by Dor3nz** [fastlane/fastlane#12589]
#### Motivation Behind Feature
I would like to automate my test build uploads to TestFairy for both iOS and Android, for what I've read in the documentation it is only possible for iOS at the moment.

#### Feature Description
Support build uploading to TestFairy for Android, I have already seen the feature requested here: https://github.com/fastlane/fastlane/issues/4111 (I opened a new issue because I am unable to reply to that one as it got closed for inactivity)

```
testfairy(
  api_key: "...",
  apk: "./apk_file.apk",
  comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
)
```

#### Alternatives or Workarounds
I am unsure if there are any alternatives existing, any help on the topic would be greatly appreciated.

**Comment by joshdholtz** [comment]
@Dor3nz Its poorly named but if you pass the APK path into the `ipa` option it actually works 😉  I will update the action and docs to say this 🙃

**Comment by Dor3nz** [comment]
Oh! Alright, thank you!
