### ISSUE TITLE
fastlane spaceauth - Could not login to iTunes Connect

### ISSUE THREAD

**Issue by koekaverna** [fastlane/fastlane#12583]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have error "Could not login to iTunes Connect" on command `fastlane spaceauth -u my@mail.here`.
It's not two factor auth. It worked before. No changes has made on software, when error is happen i up to date all software but it still did not work

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀
[12:36:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Logging into to iTunes Connect (my@mail.here)...
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for my@mail.here): *************
Could not login to iTunes Connect
Please check your credentials and try again.
This could be an issue with iTunes Connect,
Please try unsetting the FASTLANE_SESSION environment variable
and re-run `fastlane spaceauth`

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane init fails while connecting to iTunes
    https://github.com/fastlane/fastlane/issues/9134 [closed] 4 💬
    25 Sep 2017

➡️  Two factor authentication fails iTunes Connect login
    https://github.com/fastlane/fastlane/issues/9261 [closed] 8 💬
    22 Jun 2017

➡️  Unable to run fastlane spaceauth using crontab
    https://github.com/fastlane/fastlane/issues/10430 [closed] 3 💬
    19 Jan 2018

and 26 more at: https://github.com/fastlane/fastlane/search?q=Problem%20connecting%20to%20iTunes%20Connect&type=Issues&utf8=✓

/var/lib/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/spaceauth_runner.rb:27:in `rescue in run': [!] Problem connecting to iTunes Connec                                            t (RuntimeError)
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/spaceauth_runner.rb:16:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/commands_generator.rb:42:in `block (2 levels) in run'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/commands_generator.rb:48:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/commands_generator.rb:14:in `start'
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
        from /var/lib/gems/2.3.0/gems/fastlane-2.96.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀
[12:46:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:46:19]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                        |
| Ruby                        | 2.3.1                                                           |
| Bundler?                    | false                                                           |
| Git                         | git version 2.7.4                                               |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 16.04.4 LTS debian_based stretch/sid (4.4.0-124-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                      |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-05-22**
</details>
</pre>
</details>

**Comment by joshdholtz** [comment]
@koekaverna This is weird if this has worked before 🤔 Can you try / have your tried this yet? - https://github.com/fastlane/fastlane/issues/12577#issuecomment-390811299

I'm curious if this is related to that

**Comment by lefloh** [comment]
Had the same problem and it was related. Thanks @joshdholtz

**Comment by koekaverna** [comment]
Yes this fix problem, thank you!
