### ISSUE TITLE
fastlane deliver error

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#12581]
The deliver feature of fastlane seems broker from yesterday.
I am getting the following error when calling deliver. It seems the login authentication is failing on Apple end.

Login to iTunes Connect ...

Looking for related GitHub issues on fastlane/fastlane...

[31m
[!] The request could not be completed because:
	{"authType"=>"sa"}
aa=174F427F8E181B5DBE53F58H9A2957E5; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=naA0kRIhuLMKGb+Y7oIAl17H7pWbiHNBHDrAIC8fD0FSKAAQJmGidnBM; Max-Age=31536000; Expires=Wed, 22-May-2019 05:56:37 GMT; Domain=apple.com; Path=/; Secure; HttpOnly[0m

**Comment by soranoba** [comment]
https://github.com/fastlane/fastlane/issues/12577
Is this same issue?

**Comment by santoshshetty2612** [comment]
@soranoba Thanks a lot. It seems the same issue.
I have logged into iTunes and have accepted the popup and fired new builds. Hopefully it should work now as it has worked for others.

I am closing this issue.
