### ISSUE TITLE
Fastlane cert (Match) stuck at "Successfully logged in"

### ISSUE THREAD

**Issue by cortnum** [fastlane/fastlane#12588]
Hi,

I've been using fastlane and match for quite some time now, first off thanks for some amazing tools!

However, I am trying to change the fastlane setup, seeing as our customer finally got their own ITC account. Which means we need to setup match with this new team. I have setup a clean git repo, changed bundle identifiers and everything seems to be in order. However, when I try to create the new certificates (fastlane match development/appstore) there is a problem, and I cannot seems to figure out what goes wrong. The certificate is created in the developer portal, and when I enable verbose logging I can see it also says "1 key imported", however, this is where the process stalls indefinitely.

I have attached the console output with verbose logging enabled. Any help would be appreciated!

Thanks :) 
[output.txt](https://github.com/fastlane/fastlane/files/2026394/output.txt)

**Comment by joshdholtz** [comment]
@cortnum That is a weird spot to stop 🤔 Do you know if it ended up putting the cert in your keychain?

**Comment by cortnum** [comment]
@joshdholtz It does not seems like it, I just tried again and it is not in the keychain no.

**Comment by tim-doapp** [comment]
We've seen similar hangs of Fastlane over the last few days.  Seems to hang right after the login on different tool calls.  For instance, in the log below - it hung after "Certificate HBP4DTF5X5 (iOS Distribution) can't be found on your local computer" for about 15-20 minutes.  Before finally moving on.  Some hangs are longer than that.  This is a build machine that has not been touched in weeks that has all of a sudden experienced these hangs.  Starting to suspect Apple apis.

`2018-05-22 13:57:55,938 DEBUG [13:57:55]: Starting login with user 'itunes-connect-mobile@newscycle.com'

2018-05-22 13:57:58,911 DEBUG [13:57:58]: Successfully logged in

2018-05-22 14:03:04,032 DEBUG [14:03:04]: Certificate HBP4DTF5X5 (iOS Distribution) can't be found on your local computer

2018-05-22 14:08:08,625 DEBUG [14:08:08]: Found the certificate 97VC863V25 (iOS Distribution) which is installed on the local machine. Using this one.`

**Comment by markusboesch** [comment]
We currently experience some possibly related issue. `match` keeps hanging at

> Verifying that the certificate and profile are still valid on the Dev Portal...

Sometimes it keeps working after about 20 minutes. Usually, this process takes only very few seconds, so it actually makes me wonder what's causing this.

I'm also suspecting Apple's servers, but `developer.apple.com` is responding as fast as usual.

**Comment by cortnum** [comment]
Thanks everyone for the response. Letting it hang for 30+ minutes seemed to do the trick. And then updating to fastlane 2.96.1 fixed the hang time 🙌

**Comment by joshdholtz** [comment]
Glad you got it solved! 😊
