### ISSUE TITLE
 Couldn't find app 

### ISSUE THREAD

**Issue by Aravindios** [fastlane/fastlane#12599]
#### Alternatives or Workarounds

 Couldn't find app 'xxxxxxxxxxx' on the account of 'yxyxyxx@gmail.com' on iTunes Connect

**Comment by joshdholtz** [comment]
@Aravindios Doesn't look like this is a feature request but more of a configuration issue.
1) Are you logging in with the correct account?
2) Does your account have the proper iTunesConnect role to do what you are doing? Usually need admin or technical role
3) Did you enter the correct bundle identifier?
