### ISSUE TITLE
Getting "SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A" error with match

### ISSUE THREAD

**Issue by WedgeSparda** [fastlane/fastlane#12598]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since this morning I'm getting this error when executing `match` or `match nuke` in fastlane.

`SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
fastlane match nuke development -a "MY-APP-ID"

+----------------+--------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+----------------+--------------------------------------+
| git_url        | REDACTED  |
| git_branch     | mi-gelatina                          |
| app_identifier | ["MY-APP-ID"]            |
+----------------+--------------------------------------+

[11:59:50]: Cloning remote git repo...
[11:59:50]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:00:01]: Checking out branch mi-gelatina...
[12:00:01]: 🔓  Successfully decrypted certificates repo

+-----------------------+--------------------------------------+
|                Summary for match nuke 2.96.1                 |
+-----------------------+--------------------------------------+
| git_url               | REDACTED  |
| git_branch            | mi-gelatina                          |
| type                  | development                          |
| username              | REDACTED                     |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| team_id               | REDACTED                           |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

[12:00:01]: Fetching certificates and profiles...

[12:00:11]: -----------------------------------------------------------------------
[12:00:11]: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
[12:00:11]: 
[12:00:11]: SSL errors can be caused by various components on your local machine.
[12:00:11]: 
[12:00:11]: The best solution is to use the self-contained fastlane version.
[12:00:11]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
[12:00:11]:  - Use Homebrew
[12:00:11]:     - update brew with `brew update`
[12:00:11]:     - install fastlane using:
[12:00:11]:       - `brew cask install fastlane`
[12:00:11]:  - Use One-Click-Installer:
[12:00:11]:     - download fastlane at https://download.fastlane.tools
[12:00:11]:     - extract the archive and double click the `install`
[12:00:11]: -----------------------------------------------------------
[12:00:11]: for more details on ways to install fastlane please refer the documentation:
[12:00:11]: -----------------------------------------------------------
[12:00:11]:         🚀       https://docs.fastlane.tools          🚀   
[12:00:11]: -----------------------------------------------------------
[12:00:11]: 
[12:00:11]: You can also install a new version of Ruby
[12:00:11]: 
[12:00:11]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
[12:00:11]: - If you use system Ruby:
[12:00:11]:   - Run `brew update && brew install ruby`
[12:00:11]: - If you use rbenv with ruby-build:
[12:00:11]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
[12:00:11]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
[12:00:11]: - If you use rvm:
[12:00:11]:   - First run `rvm osx-ssl-certs update all`
[12:00:11]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
[12:00:11]: 
[12:00:11]: If that doesn't fix your issue, please google for the following error message:
[12:00:11]:   'SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A'
[12:00:11]: -----------------------------------------------------------------------

[!] SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
</pre>
</details>

I tried all suggestions on the stacktrace with no luck.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.4                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.15.1 (Apple Git-101)              |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane             |
| Host                        | Mac OS X 10.13.4 (17E202)                       |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | true                                            |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.3.app/Contents/Developer/ |
| Xcode Version               | 9.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.68.0"
default_platform(:ios)

platform :ios do

  build_number = ""
  version_number = ""
  vtag = ""

  before_all do
    ENV["CRASHLYTICS_API_TOKEN"] = "REDACTED"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "REDACTED"
  end

  desc "Sync development certificates and provision profiles"
  lane :development_certificates do
    match(type: "development",
      force: true)
  end

  desc "Sync appstore certificates and provision profiles"
  lane :appstore_certificates do
    match(type: "appstore")
  end

  desc "Submit a new Developer Beta to Crashlytics"
  lane :send_crashlytics do
    cocoapods
    increment_build_number
    development_certificates

    build_app(scheme: "Mi Gelatina", 
        export_method: "development")

    upload_symbols_to_crashlytics
    crashlytics(
        api_token: ENV["CRASHLYTICS_API_TOKEN"],
        build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
        groups: ["mi-gelatina"],
        notifications: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :send_testflight do
    
    cocoapods
    increment_build_number
    appstore_certificates

    build_app(scheme: "Mi Gelatina")

    upload_symbols_to_crashlytics
    upload_to_testflight

  end

  desc "Build with jenkins and submit a new Staging Build to Crashlytics "
  lane :jenkins_staging_crashlytics do

    #cocoapods
    increment_build_number(
 	    build_number: ENV["BUILD_NUMBER"]
	  )
    development_certificates
    build_app(scheme: "Mi Gelatina",
              export_method: "development")

    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      groups: ["mi-gelatina"],
      notifications: true)	
   
  end

  desc "Build with jenkins and submit a new Beta Build to Apple TestFlight"
  lane :jenkins_testflight do
  
    jenkins_testflight_output_version_number
   
    cocoapods
    
    appstore_certificates 
    build_app(scheme: "Mi Gelatina")
    upload_symbols_to_crashlytics
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true)
    
    add_git_tag(tag: vtag)
    push_git_tags 
    #pass back to jenkins the build name	
    ENV['BUILD_DISPLAY_NAME'] = vtag

  end

  desc "Output current version and build number to version.txt"
  lane :jenkins_testflight_output_version_number do 
  
    version_number = get_info_plist_value(
      path: "Source/Info.plist", 
      key: "CFBundleShortVersionString")	
    

    build_number = increment_build_number(
 	 build_number: ENV["BUILD_NUMBER"]
	)
  
    vtag = "v#{version_number}(#{build_number})"
        
  	File.open("../version.txt", 'w') do |file|
      file.write vtag
    end
  end 
end



```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#app_identifier "MY-APP-ID" 
apple_id "REDACTED"
team_id "REDACTED"
itc_team_id "REDACTED"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.21.2       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.5        |
| naturally                 | 2.1.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.9        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-05-23**
</details>

**Comment by WedgeSparda** [comment]
Getting a SSL error on XCode too when trying to create a new provision profile.

**Comment by warrendeleon** [comment]
I'm getting the same issue too. Is there any ETA?

**Comment by jackcolley** [comment]
Setting 'readonly: true' has been working for us so we can continue to use existing provisioning profiles

**Comment by darrenbrooke** [comment]
I'm using `sigh` and had exactly the same problem.  Setting `readonly: true` seemed to work around it.

**Comment by WedgeSparda** [comment]
I just tried again and is working 👍

**Comment by dmarjanovic** [comment]
@WedgeSparda, have you changed anything in your configuration to fix it, maybe upgraded Ruby? Which Ruby version are you using?
