### ISSUE TITLE
Show summary in minutes

### ISSUE THREAD

**Issue by philipengberg** [fastlane/fastlane#1259]
It would a bit easier to grasp how much time is spent, if the summary could show the duration in minutes for tasks that take longer than 60 seconds to finish, like `gym`, `pilot`, and `watchbuild`.

So that this:

<img width="581" alt="screen shot 2016-02-02 at 07 51 55" src="https://cloud.githubusercontent.com/assets/1840093/12741991/e1ac790c-c981-11e5-805f-2de01b5c1244.png">

Would become either this:

<img width="585" alt="screen shot 2016-02-02 at 07 50 03" src="https://cloud.githubusercontent.com/assets/1840093/12741972/b8cce65c-c981-11e5-929b-f893db594a17.png">

or this:

<img width="586" alt="screen shot 2016-02-02 at 07 49 35" src="https://cloud.githubusercontent.com/assets/1840093/12741977/c44b5ac2-c981-11e5-802f-bfc97c70ab51.png">

**Comment by KrauseFx** [comment]
Thanks for the feedback, however I don't like the design and messaging of the alternatives.

**Comment by philipengberg** [comment]
Alright. how about something like this?

```
+----------+
| 3s       |
| 52s      |
| 1m 3s    |
| 52m 5s   |
| 54s      |
+----------+
```

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it.

**Comment by philipengberg** [comment]
I still think it's a relevant improvement though!

**Comment by KrauseFx** [comment]
I'm not 100% sold to be honest
