### ISSUE TITLE
Error in Uploading Android apk to Google play store Using Fastlane

### ISSUE THREAD

**Issue by selvakumar1994** [fastlane/fastlane#12596]
I installed the fastlane and updated the FastFile according to the steps provided https://docs.fastlane.tools/getting-started/android/setup and i completed the setup. and then uploaded my first apk on the google play console. while executing the command below it gives an error

command: fastlane supply --apk path/to/app.apk
error: "ProjectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console".

**Comment by joshdholtz** [comment]
@selvakumar1994 This error happens when this step is not done properly - https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials

**Comment by selvakumar1994** [comment]
@joshdholtz  It is passible to  UPLOAD  android apk file to google play store (Beta or Production) release Using Fastlane tool.
