### ISSUE TITLE
Upload/Download progress

### ISSUE THREAD

**Issue by jyounus** [fastlane/fastlane#12593]
#### Motivation Behind Feature
I'm currently at a coffee shop trying to upload a beta build to testflight (behind a VPN). The internet connection itself seems to be relatively decent. However I'm currently uploading the IPA file for at least 60 mins now. 

It would be super helpful to know how much it has already uploaded, so that I know if it's worth it to wait or if I should cancel, go home and restart the upload again.

#### Feature Description
Just a pretty standard progress status would be perfect. Could be a fancy one (using an existing open source lib available on the internet) or just simple text which would tell me x% has been uploaded (we know the IPA filesize and I'm guessing we should be able to somehow get how many bytes have already been uploaded?). Maybe even show the current upload speed with it, if possible.

#### Alternatives or Workarounds
I cancel the upload even though it's maybe only 2 mins before finishing but I wouldn't know and would have to restart the whole thing once I get home. :(

**Comment by joshdholtz** [comment]
@jyounus Can you trying running with `--verbose` on the end of your fastlane CLI command? `--verbose` should show you the upload progress to iTunesConnect

Also, I highly recommend a whole milk honey latte if you want to try something new next time you are at a coffee shop ☕️ An almond milk honey latte is also pretty 👌 🙃

**Comment by jyounus** [comment]
@joshdholtz that worked and is exactly what I was after, thanks!

Will give both of them a try next time I go! :D
