### ISSUE TITLE
Allow two instances of FastlaneRunner running at same time in Swift

### ISSUE THREAD

**Issue by josesm82** [fastlane/fastlane#12604]
#### Motivation Behind Feature
I'd like to have the possibility of run several instances of FastlaneRunner al same time to allow Jenkins to run concurrent builds. Right now, when I have one instance of fastlane running, the next one gets this error: 
fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
After dig a little bit, I found this error is being generated because it tries to open a socket in port 2000 which is being used by the other instance

#### Feature Description
Fastlane is listening to FastlaneRunner on port 2000, on the FastlaneSwiftRunner code you can change this port easily but on the ruby side there is no option to set this port as parameter. This value is set on socket_server.rb when the server starts. Id could be great to have the option to set this port as parameter so we can choose a different port to listen and avoid this issue. 

#### Alternatives or Workarounds
I'm not allowing Jenkins to have concurrent buils 

fastlane env output:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.15.1 (Apple Git-101)                             |
| Installation Source         | /Library/Ruby/Gems/2.3.0/bin/fastlane                          |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    
    func productionLane() {
        cocoapods(clean: true)
        clearDerivedData()
        incrementBuildNumber()
        incrementVersionNumber()
        let version_number = getVersionNumber()
        let build_number = getBuildNumber()
        buildApp(scheme: "Stuart")
    }
    
    
    func testLane() {
        cocoapods(clean: true)
        scan(devices: ["iPhone X"], scheme: "Stuart Beta", outputTypes: "junit", failBuild: true)
    }
    
    func betaLane() {
        cocoapods(clean: true)
        let build_number = getBuildNumber()
        let name = "stuart-\(build_number).ipa"
        let options = ["compileBitcode": false, "uploadBitcode": false]
        buildApp(scheme: "Stuart Beta", clean: true, outputName: name, silent: true, includeBitcode: false, exportMethod: "development", exportOptions: options)
    }
    
    func dailyBuildLane() {
        createipa("git", "rev-list", "HEAD", "--count", "--since=1.day")
    }
    
    func RCBuildLane() {
        createipa("git", "log", "origin/master..origin/develop", "--no-merges", "--oneline", "|", "cut", "-d", "' '", "-f2-")
    }
    
    func customLane(options: [String: Any] = [:]) {
        guard let notes = options["releaseNotes"] as? String else { return }
        cocoapods(clean: true)
        incrementBuildNumber()
        let options = ["compileBitcode": false, "uploadBitcode": false]
        let version_number = getVersionNumber()
        let build_number = getBuildNumber()
        let name = "stuart-\(build_number).ipa"
        buildApp(scheme: "Stuart Beta", clean: true, outputName: name, silent: true, includeBitcode: false, exportMethod: "development", exportOptions: options)
    }
    
    private func createipa(_ values: String...) {
        cocoapods(clean: true)
        guard let n = Int(shell(values).trimmingCharacters(in: CharacterSet.newlines)) else { return }
        incrementBuildNumber()
        let changeLog = changelogFromGitCommits(commitsCount: n, pretty: "- %s")
        let options = ["compileBitcode": false, "uploadBitcode": false]
        let version_number = getVersionNumber()
        let build_number = getBuildNumber()
        let name = "stuart-\(build_number).ipa"
        buildApp(scheme: "Stuart Beta", clean: true, outputName: name, silent: true, includeBitcode: false, exportMethod: "development", exportOptions: options)
  
    }
    
    @discardableResult func shell(_ args: [String]) -> String {
        let task = Process()
        let pipe = Pipe()
        task.launchPath = "/usr/bin/env"
        task.arguments = args
        task.standardOutput = pipe
        task.launch()
        task.waitUntilExit()
        
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: String.Encoding.utf8) ?? ""
    }
    
   
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.96.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.2        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-05-24**
</details>

**Comment by joshdholtz** [comment]
@josesm82 This is an interesting use case! I can see this making sense and being needed 😊
