### ISSUE TITLE
Unable to upload ipa files to crashlytics

### ISSUE THREAD

**Issue by phaniteja** [fastlane/fastlane#12602]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

**We have built a fastlane docker image for Crashlytics beta distribution of iOS ipa files. We receive a [!] /Crashlytics.framework/submit: 1: /Crashlytics.framework/submit: Syntax error: Unterminated quoted string (FastlaneCore::Interface::FastlaneError) error when when we try to upload the ipa files to Crashlytics.**

Error log can be found below:
```
root@af054fe4e300:/fastlaneiOS# fastlane deploy --verbose
[✔] 🚀 
[14:48:38]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-05-23 14:48:38.19]: Checking if there are any plugins that should be loaded...
INFO [2018-05-23 14:48:38.21]: ----------------------------------------
INFO [2018-05-23 14:48:38.21]: --- Step: Verifying fastlane version ---
INFO [2018-05-23 14:48:38.21]: ----------------------------------------
INFO [2018-05-23 14:48:38.21]: Your fastlane version 2.96.1 matches the minimum requirement of 2.96.1  ✅
INFO [2018-05-23 14:48:38.21]: ------------------------------
INFO [2018-05-23 14:48:38.21]: --- Step: default_platform ---
INFO [2018-05-23 14:48:38.21]: ------------------------------
INFO [2018-05-23 14:48:38.22]: Driving the lane 'deploy' 🚀
INFO [2018-05-23 14:48:38.22]: -----------------------------------
INFO [2018-05-23 14:48:38.22]: --- Step: Switch to lane_0 lane ---
INFO [2018-05-23 14:48:38.22]: -----------------------------------
INFO [2018-05-23 14:48:38.22]: Cruising over to lane 'lane_0' 🚖
INFO [2018-05-23 14:48:38.23]: -------------------------
INFO [2018-05-23 14:48:38.23]: --- Step: crashlytics ---
INFO [2018-05-23 14:48:38.23]: -------------------------
INFO [2018-05-23 14:48:38.24]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2018-05-23 14:48:38.24]: /Crashlytics.framework/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath 'iPhone.ipa' -groupAliases 'aaa' -notifications YES -debug NO
ERROR [2018-05-23 14:48:38.25]: Shell command exited with exit status 2 instead of 0.
WARN [2018-05-23 14:48:38.25]: Lane Context:
INFO [2018-05-23 14:48:38.25]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"deploy"}
ERROR [2018-05-23 14:48:38.26]: /Crashlytics.framework/submit: 1: /Crashlytics.framework/submit: Syntax error: Unterminated quoted string

INFO [2018-05-23 14:48:38.26]: Successfully generated documentation at path '/fastlaneiOS/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | Switch to lane_0 lane      | 0           |
| 💥   | crashlytics                | 0           |
+------+----------------------------+-------------+

ERROR [2018-05-23 14:48:38.29]: fastlane finished with errors
/usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] /Crashlytics.framework/submit: 1: /Crashlytics.framework/submit: Syntax error: Unterminated quoted string (FastlaneCore::Interface::FastlaneError)

	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:10:in `block in parsing_binding'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:6:in `block in parsing_binding'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Also I recieve the following error when I try to upload the ipa file via commandline**
root@af054fe4e300:/fastlaneiOS# Crashlytics.framework/submit aaa bbb -ipaPath iPhone.ipa -notifications YES
bash: Crashlytics.framework/submit: cannot execute binary file: Exec format error

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>root@af054fe4e300:/fastlaneiOS# fastlane deploy --capture_output --verbose
[✔] 🚀 
[14:44:49]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-05-23 14:44:49.29]: Checking if there are any plugins that should be loaded...
INFO [2018-05-23 14:44:49.31]: ----------------------------------------
INFO [2018-05-23 14:44:49.31]: --- Step: Verifying fastlane version ---
INFO [2018-05-23 14:44:49.31]: ----------------------------------------
INFO [2018-05-23 14:44:49.31]: Your fastlane version 2.96.1 matches the minimum requirement of 2.96.1  ✅
INFO [2018-05-23 14:44:49.31]: ------------------------------
INFO [2018-05-23 14:44:49.31]: --- Step: default_platform ---
INFO [2018-05-23 14:44:49.31]: ------------------------------
INFO [2018-05-23 14:44:49.32]: Driving the lane 'deploy' 🚀
INFO [2018-05-23 14:44:49.33]: -----------------------------------
INFO [2018-05-23 14:44:49.33]: --- Step: Switch to lane_0 lane ---
INFO [2018-05-23 14:44:49.33]: -----------------------------------
INFO [2018-05-23 14:44:49.33]: Cruising over to lane 'lane_0' 🚖
INFO [2018-05-23 14:44:49.33]: -------------------------
INFO [2018-05-23 14:44:49.33]: --- Step: crashlytics ---
INFO [2018-05-23 14:44:49.33]: -------------------------
INFO [2018-05-23 14:44:49.34]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2018-05-23 14:44:49.34]: /Crashlytics.framework/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath 'iPhone.ipa' -groupAliases 'aaa' -notifications YES -debug NO
ERROR [2018-05-23 14:44:49.35]: Shell command exited with exit status 2 instead of 0.
WARN [2018-05-23 14:44:49.35]: Lane Context:
INFO [2018-05-23 14:44:49.35]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"deploy"}
ERROR [2018-05-23 14:44:49.35]: /Crashlytics.framework/submit: 1: /Crashlytics.framework/submit: Syntax error: Unterminated quoted string

INFO [2018-05-23 14:44:49.36]: Successfully generated documentation at path '/fastlaneiOS/fastlane/README.md'
ERROR [2018-05-23 14:44:49.38]: fastlane finished with errors
</pre>
</details>

### Environment

<details>
  <pre>root@af054fe4e300:/fastlaneiOS# fastlane env
[✔] 🚀 
[14:46:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:46:13]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | debian_based 8.7                                           |
| Ruby                        | 2.4.1                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.1.4                                          |
| Installation Source         | /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane                |
| Host                        | Debian GNU/Linux 8 debian_based 8.7 (4.9.87-linuxkit-aufs) |
| Ruby Lib Dir                | /usr/local/rvm/rubies/ruby-2.4.1/lib                       |
| OpenSSL Version             | OpenSSL 1.0.1t  3 May 2016                                 |
| Is contained                | false                                                      |
| Is homebrew                 | false                                                      |
| Is installed via Fabric.app | false                                                      |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.96.1"
default_platform :ios
desc "Deploy ipa Files"
lane :deploy do
desc "Deploy ipas"
lane_0
lane_1
end
lane :lane_0 do
crashlytics(
            crashlytics_path:"/Crashlytics.framework",
            api_token: "abc",
            build_secret: "def",
            notifications: true,
            groups: "aaa",
            ipa_path:"iPhone.ipa"
            )
end
lane :lane_1 do
crashlytics(
            crashlytics_path:"Crashlytics.framework",
            api_token: "abc",
            build_secret: "def",
            notifications: true,
            groups: "aaa",
            ipa_path:"iPad.ipa"
            )
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.1       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2018-05-23**
</details>
[14:46:14]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[14:46:14]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
</pre>
</details>

**Comment by joshdholtz** [comment]
@phaniteja If you also receive this same error when running crashlytics via command line directly, this is more than likely an issue with your crashlytics configuration in your environment or a crashlytics issue and not a fastlane issue 🙃 

If you can get crashlytics to manually upload outside of fastlane, it should work in fastlane 😊 

Can you also try running your fastlane command with `--verbose` and past the whole output so I can see some more output?

**Comment by phaniteja** [comment]
@joshdholtz Thanks for the reply. The fastlane command with --verbose is already pasted in the issue description. Could you please have a look?

Also, could you please help us to know whether crashlytics upload of ipa (iOS) files works on a linux machine?

**Comment by joshdholtz** [comment]
@phaniteja Ah, sorry about that! I expected some more logs to show that I didn't see in there 🤔 

And oh, is your output from a linux machine???

**Comment by joshdholtz** [comment]
@phaniteja There is a good chance that you might not be able to upload an IPA to Crashlytics from Linux using the Crashlytics framework 🤔 fastlane is doing its job here by calling the Crashlyics framework to upload the IPA so I think this is a thing you might want to talk to Crashlyics about and see how they support running from a Linux machine 😬
