### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhangdongpo** [fastlane/fastlane#12609]
Building native extensions. This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.5.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/usr/local/opt/ruby/bin/ruby -r ./siteconf20180524-10246-xs9ghf.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.5.1/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:541:in `try_link0'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:559:in `try_link'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:777:in `try_func'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:1004:in `block in have_library'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:947:in `block in checking_for'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:946:in `checking_for'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:999:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.5.0/gems/unf_ext-0.0.7.5 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0/unf_ext-0.0.7.5/gem_make.out

**Comment by Kirow** [comment]
I have same issue when installed via brew (when installed via gem - bundle update never ends).
mkmf.log says that stdio.h not found
I've fixed this error, in my case settings file had 
```
CONFIG["CFLAGS"] = "-mmacosx-version-min=10.10 -isysroot /Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe"`, no idea why there was `Xcode-7.3.1.app
```
 but that is not related to my system, because I never had xCode 7.3.1 here...

anyway, another error appeared then - 
`ld: library not found for -lruby-static`, seems like mess with pathes...

I expected this setup to be one click, but wasted whole day and did not make it work w/o errors...

I will report more details later, after I cleanup all the mess I did while trying to make it work correctly.

**Comment by Kirow** [comment]
## Installation
### Step1 - command line tools:
```
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
### Step2 - fastlane install:
```
brew cask install fastlane
```
### Step3 - environment (using zsh terminal, so modified `~/.zshrc` file):
```
export PATH="$HOME/.fastlane/bin:$PATH"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2018-05-24**
</details>

### Step4 - fastlane init:
```
fastlane init
```
**Q:** What would you like to use fastlane for?
**A:** 1. Automate screenshots
**Q:** Enable automatic upload of localized screenshots to iTunes
Connect?
**A:** No

finally same error...
```
An error occurred while installing unf_ext (0.0.7.5), and Bundler
cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.5'` succeeds before bundling.
[12:30:41]: Exit status: 5
[12:30:41]: Something went wrong when running `bundle update` for you
[12:30:41]: Please take a look at your Gemfile at path `Gemfile`
[12:30:41]: and make sure you can run `bundle update` on your machine.
[12:30:41]: --------------------------------------------------------
[12:30:41]: --- ✅  Successfully generated fastlane configuration ---
[12:30:41]: --------------------------------------------------------
```
mkmf.log:
```
"/usr/bin/clang -o conftest -I/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/x86_64-darwin15 -I/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/backward -I/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0 -I. -I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe conftest.c  -L. -L/Users/kirow/.fastlane/bin/bundle/lib -L. -L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib -fstack-protector     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]
In file included from conftest.c:1:
In file included from /Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

obviously:
```
clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]
```
related to 
```
In file included from /Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
```

so opening config file at `/Users/kirow/.fastlane/bin/bundle/lib/ruby/2.2.0/x86_64-darwin15/rbconfig.rb`, there we can see:
```
CONFIG["configure_args"] = " '--prefix' '/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/bundle' '--enable-load-relative' '--disable-shared' '--with-static-linked-ext' '--disable-install-doc' '--without-ext=,dbm,gdbm,sdbm,dl/win32,fiddle/win32,tk/tkutil,tk,win32ole,-test-/win32/dln,-test-/win32/fd_setsize,-test-/win32/dln/empty' 'CC=/usr/bin/clang' 'CFLAGS=-mmacosx-version-min=10.10 -isysroot /Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' 'LDFLAGS=-L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib' 'CPPFLAGS=-I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/include' 'CXX=/usr/bin/clang++'"
CONFIG["CFLAGS"] = "-mmacosx-version-min=10.10 -isysroot /Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe"
```
**this is definitely wrong** - `/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk`
changed to - `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`
`/Users/crashlytics/buildAgent/work/2484be8b71880c21/...` seems wrong too, but no idea what its purpose, so I did not modified/removed this

re-run `fastlane init`

mkmf.log:
```
"/usr/bin/clang -o conftest -I/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/x86_64-darwin15 -I/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/backward -I/Users/kirow/.fastlane/bin/bundle/include/ruby-2.2.0 -I. -I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -pipe conftest.c  -L. -L/Users/kirow/.fastlane/bin/bundle/lib -L. -L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib -fstack-protector     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
ld: warning: directory not found for option '-L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib'
ld: library not found for -lruby-static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

And for now I'm stuck here...

**Comment by Kirow** [comment]
installed via `sudo gem install fastlane -NV`
and init with sudo - `sudo fastlane init`, works as expected

if `fastlane init` - ` $ bundle update` stays on screen forever, no errors, just stuck

**Comment by joshdholtz** [comment]
@zhangdongpo It looks like you may be missing the developer tools based upon this line in your output: `The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first.`

Looks ike @Kirow mentioned this in a comment but have you run: `xcode-select --install`?

**Comment by joshdholtz** [comment]
@Kirow Are you using the system version of Ruby? The system version of Ruby usually forces you to use `sudo` to install a gem but you shouldn't need to use `sudo` to run `fastlane init`.

Can you run `fastlane init --verbose` and paste the output? I'm curious what it is getting stuck on 🤔

**Comment by Kirow** [comment]
> Looks ike @Kirow mentioned this in a comment but have you run: xcode-select --install?

when installed via `brew cask` it doesn't help, because it tired to use wrong SDK path, and even if it changed manually - issue with missing ruby-static appeared and I don't know where it is located... 
also `fastlane env` says that ruby version 2.2.4, but '.fastlane/bin/bundle/lib/ruby' had only `2.2.0`
I think that installation via homebrew not working at all...

> Are you using the system version of Ruby?

not sure what I am using. `ruby -v` says `ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]`

> Can you run fastlane init --verbose and paste the output?

when I launched it second time it worked w/o issue, probably because all dependencies were already installed with sudo.

So I removed some installed gems and reinstall fastlane...and it worked anyway...
Is there is a way to remove fastlane with all dependencies?

**Comment by joshdholtz** [comment]
@Kirow Two questions for you:
1) Did you have a `Gemfile` in the directory where you initially ran `fastlane init`?
2) Are things fully working for you now?

**Comment by Kirow** [comment]
1. Yes, I do. It was created automatically:
```
source "https://rubygems.org"

gem "fastlane"
```
2. no errors during `fastlane init`, but not fully working for me. 
`sudo fastlane screenshots`
```
No such file or directory @ rb_sysopen - /Users/kirow/Library/Developer/CoreSimulator/Devices/85FEC9CC-CDCB-42C6-B679-39325A8A931D/data/Library/Preferences/.GlobalPreferences.plist
```
there is no such folder - 85FEC9CC-CDCB-42C6-B679-39325A8A931D

Anyway I don't think this issue is related...

**Comment by Kirow** [comment]
> Can you run fastlane init --verbose and paste the output?

ok, I removed all dependencies manually...

```
INFO [2018-05-24 16:32:45.24]: ▸ Fetching json 2.1.0
INFO [2018-05-24 16:32:45.59]: ▸ Your user account isn't allowed to install to the system RubyGems.
INFO [2018-05-24 16:32:45.59]: ▸ You can cancel this installation and run:
INFO [2018-05-24 16:32:45.59]: ▸ bundle install --path vendor/bundle
INFO [2018-05-24 16:32:45.59]: ▸ to install the gems into ./vendor/bundle/, or you can enter your password
INFO [2018-05-24 16:32:45.59]: ▸ and install the bundled gems to RubyGems using sudo.
```

**Comment by joshdholtz** [comment]
@Kirow So the preferred way to install fastlane is through a `Gemfile` (instead of `gem install fastlane`)

I THINK what was going on is that...
1) You installed fastlane directly into Ruby with `sudo gem install fastlane`
2) You had a `Gemfile` that also had fastlane there (which is why things may have gone 💥 cause it may have had some conflicting stuff going on)
3) You may have had an update fastlane action in your `Fastfile` which was trying to update using bundler (`Gemfile`) but since you installed it via `sudo gem install fastlane` that it was also getting confused

So I THINK if you would do `sudo gem uninstall fastlane` and then run `bundle install` things _may_ have worked? 🤔 😇

**Comment by Kirow** [comment]
`bundle install` failed with same problem, but at least it is visible by default.

```
Fetching json 2.1.0


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:
```
input password....and:
```
Fetching fastlane 2.96.1
Installing fastlane 2.96.1
Gem::FilePermissionError: You don't have write permissions for the
/var/folders/9f/jg5vh8hn7rn20z6j14tgfbgc0000gn/T/bundler20180524-19162-yefdgsfastlane-2.96.1/bin
directory.
An error occurred while installing fastlane (2.96.1), and Bundler cannot
continue.
Make sure that `gem install fastlane -v '2.96.1' --source 'https://rubygems.org/'` succeeds
before bundling.
```
so I ended with `sudo bundle install`, but it says - 
```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will
break this application for all non-root users on this
```

that make me sad :(
