### ISSUE TITLE
Auto update/link of latest build in the Prepare for Submission via deliver

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#12601]
Hi,

Currently I have automated build setup for iOS and the build is uploaded to iTunes for Testers to test via fastlane deliver.

**Once the final build is generated, I manually select the latest build in the Prepare for submission section.**
Then marketing team makes the desired changes in the release notes, etc. and submits the build for Review.

I can not use the submit_for_review option in deliver as apart from selecting the latest build it will also submit the app for Review which I want to avoid. 

After every build, when I push it to iTunes via deliver, I just want to link it in the Prepare for Submission so that marketing team after modifying the release notes can directly submit for Review without the need of me to link the app version manually.

**Comment by joshdholtz** [comment]
@santoshshetty2612 You can actually do the today 😊 

```rb
fastlane_require 'spaceship'

    Spaceship::Tunes.login("your@email.com")
    app = Spaceship::Tunes::Application.find("your.bundle.id")
    version = app.edit_version
    latest_build = version
      .candidate_builds
      .sort_by(&:upload_date)
      .last
    version.select_build(latest_build)
    version.save!
```

You should be able to put this after your call to `deliver` or `pilot` or whatever you are using and this should select the latest build 💪

**Comment by santoshshetty2612** [comment]
Thanks @joshdholtz Its amazing that Spaceship don't need to wait for the processing to complete on iTunes before we ask it to link the build.
I will give this a try. Thanks again.

**Comment by santoshshetty2612** [comment]
Hi @joshdholtz 

I created a lane 

lane :linkLatestBuildInitunes do
			appId="#{ENV["APP_ID"]}"
			iTunesUser="#{ENV["ITUNESCONNECT_USER"]}"
			Spaceship::Tunes.login(iTunesUser)
			app = Spaceship::Tunes::Application.find(appId)
			version = app.edit_version
			latest_build = version
			.candidate_builds
				.sort_by(&:upload_date)
				.last
			version.select_build(latest_build)
			version.save!
end

and at top of my fast file I added  require 'spaceship'

Now When I run this lane, I am getting the error:

iTunes Connect temporary error received: 'There was an error saving changes. Please try again later or <a href='http://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa/jumpTo?page=contactUs&contactfaq=errorhelp'>contact App Store Developer Support</a>.'. Retrying after 60 seconds
