### ISSUE TITLE
How do you use the console logging from Swift?

### ISSUE THREAD

**Issue by simonbromberg** [fastlane/fastlane#12600]
In #11625 support for Swift console printing was added. But the documentation and the commits in that PR don't explain how to actually use this. I tried putting `print` in my Fastfile.swift but it doesn't seem to do anything.

**Comment by simonbromberg** [comment]
Oh; isn't `println` deprecated?

**Comment by 93cantero** [comment]
It is a custom function created by fastlane that executes the `println` ruby command.
It is not the Swift print function, but it does the job.

**Comment by joshdholtz** [comment]
@simonbromberg @simonbromberg Good call! Closing in favor of this issue in the docs repo ^ 😊
