### ISSUE TITLE
Can't add tools.fastlane:screengrab

### ISSUE THREAD

**Issue by YamiDaisuke** [fastlane/fastlane#12608]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Screengrab

#### Question Description

I'm following the instructions in the screen grab documentation but adding 

`androidTestCompile('tools.fastlane:screengrab')`

or 

`androidTestCompile('tools.fastlane:screengrab:1.2.0')`

Fails with:

Error:Failed to resolve: tools.fastlane:screengrab:

I have added both mavenCentral and jcentral repositories:

```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}
```

**Comment by joshdholtz** [comment]
@YamiDaisuke Hmmm, this is what my`build.gradle` looks like and it works for me 🤔  Can you try something like this?

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0-alpha14'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by YamiDaisuke** [comment]
Hello! thanks for the reply, I was able to make it work but I needed to add excludes for android support library there was a conflict 'cause I was using a different version of the support library for my project


```
androidTestImplementation('tools.fastlane:screengrab:1.2.0'){
        exclude group: 'com.android.support', module: '*'
    }

    androidTestImplementation('com.android.support.test:runner:1.0.2') {
        exclude group: 'com.android.support', module: '*'
    }
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.2') {
        exclude group: 'com.android.support', module: '*'
    }
```
