### ISSUE TITLE
upload_to_play_store retaining old versions

### ISSUE THREAD

**Issue by stevmachine** [fastlane/fastlane#12617]
### Feature Request
Upload to play store retaining old versions.

### Motivation Behind Feature
I'm using [**supply**](https://docs.fastlane.tools/actions/supply/) to deploy a bundle of multiple APKs to play store and this work like a charm. But, apparently, there is no option to retains old versions yet, so the process always deprecates the old bundle/single APK that had been published before.

The last is ok for my alpha track because I'm constantly updating versions for 21+ and 24+. But for production, I need to retain a version for 16+ for a time without add new updates. So, I need to create a manual release that also includes the "almost deprecated" version every time and my idea is to do all the process in an automatic way. 

![screen shot 2018-05-22 at 5 28 48 pm 1](https://user-images.githubusercontent.com/17983441/40525807-cd77c1e8-6025-11e8-8815-da06edc9b18e.png)

 
![edit 1 1](https://user-images.githubusercontent.com/17983441/40526105-8a7cf1d6-6027-11e8-894c-c48e79d897a1.png)

So, pretty please, can you add this functionality?. 

### Feature Description

Probably, we are going to need this command **[google_play_track_version_codes](https://docs.fastlane.tools/actions/google_play_track_version_codes/#google_play_track_version_codes)** and that way we can indicate which old versions we want to retain.

Something like:

```
upload_to_play_store(
          track: 'alpha',
          apk_paths: [ options[:apk_paths] ],
          retain_old_versions: [ '1010']
)
```

**Comment by stvmachine** [comment]
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                          | Version | Update-Status |
| ----------------------------------------------- | ------- | ------------- |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                             | Version      |
| ----------------------------------------------- | ------------ |
| did_you_mean                                    | 1.2.0        |
| bundler                                         | 1.16.1       |
| fileutils                                       | 1.0.2        |
| CFPropertyList                                  | 3.0.0        |
| public_suffix                                   | 2.0.5        |
| addressable                                     | 2.5.2        |
| atomos                                          | 0.1.2        |
| babosa                                          | 1.0.2        |
| claide                                          | 1.0.2        |
| colored                                         | 1.2          |
| colored2                                        | 3.1.2        |
| highline                                        | 1.7.10       |
| commander-fastlane                              | 4.4.6        |
| declarative                                     | 0.0.10       |
| declarative-option                              | 0.1.0        |
| unf_ext                                         | 0.0.7.5      |
| unf                                             | 0.1.4        |
| domain_name                                     | 0.5.20180417 |
| dotenv                                          | 2.4.0        |
| emoji_regex                                     | 0.1.1        |
| excon                                           | 0.62.0       |
| multipart-post                                  | 2.0.0        |
| faraday                                         | 0.15.2       |
| http-cookie                                     | 1.0.3        |
| faraday-cookie_jar                              | 0.0.6        |
| faraday_middleware                              | 0.12.2       |
| fastimage                                       | 2.1.3        |
| gh_inspector                                    | 1.1.3        |
| jwt                                             | 2.1.0        |
| little-plugger                                  | 1.1.4        |
| multi_json                                      | 1.13.1       |
| logging                                         | 2.2.2        |
| memoist                                         | 0.16.0       |
| os                                              | 0.9.6        |
| signet                                          | 0.8.1        |
| googleauth                                      | 0.6.2        |
| httpclient                                      | 2.8.3        |
| mime-types-data                                 | 3.2016.0521  |
| mime-types                                      | 3.1          |
| uber                                            | 0.1.0        |
| representable                                   | 3.0.4        |
| retriable                                       | 3.1.1        |
| google-api-client                               | 0.21.2       |
| json                                            | 2.1.0        |
| mini_magick                                     | 4.5.1        |
| multi_xml                                       | 0.6.0        |
| plist                                           | 3.4.0        |
| rubyzip                                         | 1.2.1        |
| security                                        | 0.1.3        |
| naturally                                       | 2.1.0        |
| simctl                                          | 1.6.4        |
| slack-notifier                                  | 2.3.2        |
| terminal-notifier                               | 1.8.0        |
| unicode-display_width                           | 1.3.3        |
| terminal-table                                  | 1.8.0        |
| tty-screen                                      | 0.6.4        |
| tty-cursor                                      | 0.5.0        |
| tty-spinner                                     | 0.8.0        |
| word_wrap                                       | 1.0.0        |
| nanaimo                                         | 0.2.5        |
| xcodeproj                                       | 1.5.9        |
| rouge                                           | 2.0.7        |
| xcpretty                                        | 0.2.8        |
| xcpretty-travis-formatter                       | 1.0.0        |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2        |
</details>
