### ISSUE TITLE
 How to control devices list for each project?

### ISSUE THREAD

**Issue by KinGwaL** [fastlane/fastlane#12612]
### Question Checklist

- [O] Updated fastlane to the latest version
- [O] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [O] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [O] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
In my developer portal, there have full devices list for different company using (e.g, A.ipa for A company, B.ipa for B company)

Is there have any functions/methods to control the devices list for different project ? 
(A.project = 1,2,3 persons)
(B.project = 4,5,6 persons)

Thanks!

**Comment by joshdholtz** [comment]
@KinGwaL Do you mean when making provisioning profiles with `sigh` or `match`?

**Comment by KinGwaL** [comment]
@joshdholtz No, i have used `match` to make provisioning profiles, but i'm try to control the devices list for each provisioning profiles because of company policy.. every time i generate the provisioning profiles via `match`, it will automatically add all devices for ad hoc profiles but that's not i want

For example, my devices list in developer portal: 
Alan
John
Bob
Jason

What i want is that:
A_project.mobileprovision (Alan, John)
B_project.mobileprovision (John, Bob)
C_project.mobileprovision (Alan, Bob, Jason)

**Comment by KinGwaL** [comment]
Is there a function like `register_devices` that can read devices file so i can control which applications a tester can install? 
I know there have third party like Hockeyapp can limit the installation of different user by control user account/group, but it cannot limit the installation using UDID.

**Comment by joshdholtz** [comment]
@KinGwaL There is not a way to do that with fastlane right now 😔 This has been a requested feature so I can look into this when I get time 😊

**Comment by KinGwaL** [comment]
@joshdholtz  look forward to hearing your good news!🍾️
