### ISSUE TITLE
Fastlane beta shows "Couldn't decrypt the repo, please make sure you enter the right password"

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#12613]
I can't able to run the "fastlane beta", because it shows the error "Couldn't decrypt the repo, please make sure you enter the right password!".

Enter the passphrase that should be used to encrypt/decrypt your certificates
 This passphrase is specific per repository and will be stored in your local keychain
Make sure to remember the password, as you'll need it when you run match on a different machine
Passphrase for Git Repo: ***************
Type passphrase again: ***************
Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Library/Keychains/login.keychain-db"

**Comment by joshdholtz** [comment]
@nihp Did you use the exact same password for when you create the _match_ repo?  Please see other issues that are similar to this one - https://github.com/fastlane/fastlane/issues?q=is%3Aissue+Couldn%27t+decrypt+the+repo%2C+please+make+sure+you+enter+the+right+password+is%3Aclosed

**Comment by nihp** [comment]
@joshdholtz 
My exact issue is in this thread
 https://github.com/fastlane/fastlane/issues/10931

Kindly reopen this, it get auto closed

Here I have a decrypted file, I have given correct password only. Is there is any way to disable the password which I was given earlier

```
Enter the passphrase that should be used to encrypt/decrypt your certificates
 This passphrase is specific per repository and will be stored in your local keychain
 Make sure to remember the password, as you'll need it when you run match on a different machine
 Passphrase for Git Repo: ***************
 Type passphrase again: ***************
: 🔓  Decrypted 'HDDJNHHFDFDN32.cer'
 Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Library/Keychains/login.keychain-db"
```

**Comment by joshdholtz** [comment]
@nihp So you are running this over ssh?

**Comment by nihp** [comment]
I am running with my git repo

**Comment by nihp** [comment]
Any way to change the password

**Comment by joshdholtz** [comment]
@nihp There is not a built in way to change the password. Your best bet to change the password would just be to just delete everything in this repo or to create a new repo. Do you not remember the password you used when creating the match repo?

**Comment by nihp** [comment]
I remember the password, but when I giving the password it not accepting that password

**Comment by joshdholtz** [comment]
@nihp _match_ is working for me right now 🤔 Can you maybe try creating a brand new repository (just as a test) and see if things work with that?

**Comment by mbuchetics** [comment]
We just experienced the same issue. Match keeps asking for a password and even though it's the correct one, it does not get accepted.

**Comment by astrokin** [comment]
the same issue

**Comment by DmitrijKotsur** [comment]
the same issue

**Comment by SolorzanoJose** [comment]
Same issue, goodjob fastlane bot

**Comment by dsrees** [comment]
I ran `bundle exec fastlane match nuke development` which unlocked my Keychain, decrypted the repo and cleared out all dev certificates. And then 30 seconds later I ran `bundle exec fastlane match nuke distribution` and it failed, deleting the password from the keychain

```
[✔] 🚀 
[13:32:52]: Successfully loaded '/Users/proj/fastlane/Matchfile' 📄

+----------------+----------------------------------------------+
|          Detected Values from './fastlane/Matchfile'          |
+----------------+----------------------------------------------+
| git_url        | git@github.com:company/certificates.git |
| type           | development                                  |
| app_identifier | com.example.appid       |
| username       | dev@example.com                   |
+----------------+----------------------------------------------+

[13:32:52]: Cloning remote git repo...
[13:32:52]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[13:32:53]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/me/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:Company/certificates.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303130343135353231395A00  "20180104155219Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303130343135353231395A00  "20180104155219Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:Company/certificates.git"
    "type"<uint32>=<NULL>
password has been deleted.
[13:32:53]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[13:32:53]: This passphrase is specific per repository and will be stored in your local keychain
[13:32:53]: Make sure to remember the password, as you'll need it when you run match on a different machine
[13:32:53]: Passphrase for Git Repo: 

```

Running version 2.107.0

**Comment by dsrees** [comment]
Deleting the git repo and creating a new one with the same name seemed to work, allowing me to reset the password for the repo.

**Comment by levantAJ** [comment]
Same issue here, any help from team, pls?

**Comment by rkuncewicz** [comment]
This happens to us now when we try to nuke a particular lane, and we are forced to nuke everything, clean the repo and create everything again.

**Comment by geraldeersteling** [comment]
Same issues here as well, after setting a password it just fails to decrypt it.

**Comment by madsonic** [comment]
seems to have been solved in `2.116.0`

**Comment by trinadhkoya9** [comment]
It was not closed yet, still producing the same error

**Comment by riyanpratama** [comment]
still getting this error

**Comment by rdewolff** [comment]
Have you tried using the ENV variable `MATCH_PASSWORD` ?

**Comment by ls-kelsey-regan** [comment]
I'm getting the same thing. Tried both inputting the password manually and through env var MATCH_PASSWORD.

**Comment by rdewolff** [comment]
How do you set the ENV variable? I noticed that setting it in the Fastfile did NOT work. But on the command line it did!

**Comment by nihp** [comment]
I am also experiencing the same problem. 

My distribution certificate has expired. So I have regenerated the same certificate by editing from UI in developer account. Now it is eligible to distribute my app. But I am facing an error as 

`❌  error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "924775HDGD" with a private key was found. (in target 'My App')`

Note: So I deleted the older Match file and generated a new Match File by running **fastlane match init**. But the password gets mismatched and I can't not able to encrypt the certificate in my repo.

Kindly provide any suggestion to upload my build as soon as possible

**Comment by nihp** [comment]
I have fixed the above mentioned error by the following 

Unchecked "Automatically manage signing".

```
1. Select "Provisioning profile" in "Signing (Release)" section.

2. No signing certificate error will be show.

3. Then below the error has a "Manage Certificates" button. click the button.
4. This window will come. Click the + sign and click "iOS Distribution". xcode will create the private key for your distribution certificate and error will be gone.
```

Refer answer from the stackoverflow

https://stackoverflow.com/questions/45050902/no-signing-certificate-ios-distribution-found

**Comment by agordeev** [comment]
I'm getting the same problem as OP. Entering the correct password produces 

```
bad decrypt
Couldn't decrypt the repo, please make sure you enter the right password!
password has been deleted
```

**Comment by udayasri** [comment]
Any one got this working ? fastlane keep asking me for Passphrase for the git repo, even though I have entered the correct password

**Comment by rdewolff** [comment]
The only workaround I know is using the ENV variable when running the script. For example, run it like: 

```
MATCH_PASSWORD=myp4ssw0rd fastlane ios
```

**Comment by udayasri** [comment]
I was super stupid that I have added two different team certificates & profiles in the same directory. When use them in different branches match worked perfectly

**Comment by hmgibson23** [comment]
I am still experiencing this issue on CircleCI

**Comment by kuka** [comment]
@hmgibson23 have you figured it out?

**Comment by hmgibson23** [comment]
Yeah. It was because the original certs were on my local machine. Deleted those, regenerated and it worked. Misleading error though...

**Comment by yoshimoto8** [comment]
same issue

**Comment by trinadhkoya9** [comment]
I am using fastlane 2.129.0 , the issue remains same .Any workaround to fix this out without changing repository and doing the same shit again and again

**Comment by nihp** [comment]
Did you tried with the exact password which you already used

**Comment by trinadhkoya9** [comment]
Yes I did

Thanks & Regards TRINADH KOYA Work Hard.Have fun.Make History
