### ISSUE TITLE
warning: conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#12625]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

in snapshot action 
```
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:` warning: conflicting chdir during another chdir block
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/snapshot/lib/snapshot/detect_values.rb:21: warning: conflicting chdir during another chdir block
```

```
            snapshot({
            	devices: [
            		device
            	],
            	languages: [
            		language
            	],
            	output_directory: FASTLANE_SCREENSHOT_PATH + "/" + device,
            	clear_previous_screenshots: true,
            	skip_open_summary: true,
            	scheme: FASTLANE_SCHEME,
            	workspace: APP_WORKSPACE_PATH,
            	erase_simulator: true,
            	concurrent_simulators: false
            })
```

all work good in previous versions

**Comment by joshdholtz** [comment]
@GandjaFuzz I am not able to reproduce this on my end at all 😢

1) Does this happen for you every time you run this?
2) Do thing still "work" but a warning is just showing? Or does this make things break?
3) Can you add `--verbose` to your command you are using to run this and paste the entire output here?
4) Can you run `fastlane env` and paste that here as well?

Thanks!!
