### ISSUE TITLE
How to stop build when fastlane run building?

### ISSUE THREAD

**Issue by Bijiabo** [fastlane/fastlane#12624]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### What tool/action do you have a question about? 
fastlane build
#### Is this a question about documentation?
no
#### Is this a question about a third party plugin? (If so, please go to the plugin repository first) 
no
#### Question Description

I wrote a command line tool to do Xcode project build and package by run fastlane build command. But in some scene, it need to stop build immediately. I try to kill shell child process. But the fastlane and xcodebuild is still running.

Is there are any ways to shut down the build action by run command? Now I use `killall xcodebuild` to stop it, but it is only work after the process is on the second step(step one is change the plist content).

Thanks.

**Comment by joshdholtz** [comment]
@Bijiabo How are you running this? If you are running something like `fastlane <lane>` then doing a CONTROL+C should kill everything for you. Are you running this a different way if this isn't working for you?

**Comment by Bijiabo** [comment]
@joshdholtz I wrote a script in Node.js to run shell command, not type command in command line. My target is building a automatic workflow to change project content and build the project into .ipa and .apk file. 

In this scene, if the workflow run the `fast lane <lane>`, need to stop it when the program receive a stop message. So, need a clear way to realize it.

Thanks.

**Comment by joshdholtz** [comment]
@Bijiabo This might not be the best place to get a solution for this answer if you are wrapping a fastlane call in a custom Node.js script 😔 _fastlane_ processes do properly get interrupted/killed if CONTROL+C is called so I would suggested maybe asking this question about a Node.js specific forum or IRC channel
