### ISSUE TITLE
upload_to_testflight cannot update What to test when skip_waiting_for_build_processing is set to true

### ISSUE THREAD

**Issue by sprabhuanand** [fastlane/fastlane#12621]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I set the attribute skip_waiting_for_build_processing in fastlane file, it is not updating the what to test in the testflight. But at the same time, when i remove this flag it updates the what to test box. 

upload_to_testflight(changelog: notes, skip_waiting_for_build_processing: true )

And am running this over jenkins. 

```
##### Complete output when running fastlane, including the stack trace and command used
[23:02:57]: ESC[32m----------------------------------ESC[0m
[23:02:57]: ESC[32m--- Step: upload_to_testflight ---ESC[0m
[23:02:57]: ESC[32m----------------------------------ESC[0m
[23:02:57]: Login to iTunes Connect (devops@mindstronghealth.com)
[23:03:01]: Login successful
[23:03:02]: ESC[32mReady to upload new build to TestFlight (App: xxxxxxxxxx )...ESC[0m
[23:03:06]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[23:03:06]: Going to upload updated app to iTunes Connect
[23:03:06]: ESC[32mThis might take a few minutes. Please don't interrupt the script.ESC[0m
[23:04:45]: ESC[32miTunes Transporter successfully finished its jobESC[0m
[23:04:45]: ESC[32m--------------------------------------------------------------------ESC[0m
[23:04:45]: ESC[32mSuccessfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.ESC[0m
[23:04:45]: ESC[32m--------------------------------------------------------------------ESC[0m
[23:04:45]: ESC[32mSuccessfully uploaded the new binary to iTunes ConnectESC[0m
[23:04:45]: ESC[33mSkip waiting for build processingESC[0m
[23:04:45]: ESC[33mThis means that no changelog will be set and no build will be distributed to testersESC[0m
[23:04:45]: ESC[32m--------------------------------ESC[0m
[23:04:45]: ESC[32m--- Step: push_to_git_remote ---ESC[0m
[23:04:45]: ESC[32m--------------------------------ESC[0m
```

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment
<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.16.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
</details>
</pre>
</details>

**Comment by joshdholtz** [comment]
@sprabhuanand Sorry about the issue but thanks for the detail ❤️ I think I've seen a report of this before but I didn't know that this was caused by `skip_waiting_for_build_processing`. I will look into this 💪

**Comment by sprabhuanand** [comment]
Thanks @joshdholtz , looking forward for the fix.

**Comment by sprabhuanand** [comment]
Well, i'm waiting to hear on this issue. Not sure what am supposed to do :(

**Comment by Jauzee** [comment]
I'm facing the same issue. Also found these issues: #1463 #10074 

`skip_waiting_for_build_processing` was implemented here #4812 to resolve the issue, because `skip_submission` flag would cause ignoring the changelog.

**Comment by sprabhuanand** [comment]
I think, this bug not start to contribute this issue as well. 

`12:15:59 ERROR [2018-08-13 12:15:59.71]: [31mCould not set changelog: 765: unexpected token at '<!DOCTYPE html><html lang="en">
12:15:59 <head>
12:15:59 <title></title>
12:15:59 <link rel="stylesheet" href="/styles/main.css">
12:15:59 <style type='text/css'>
12:15:59     /*include ../../dist/styles/main.css*/
12:15:59 </style>
12:15:59 </head>
12:15:59 
12:15:59 <body><div id="wrapper" class="j42">
12:15:59 <h2>Internal Server Error</h2></div>
12:15:59 
12:15:59 <div class="footer">
12:15:59     <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
12:15:59     <ul><li><a href="http://www.apple.com/legal/internet-services/itunes/us/terms.html">Terms of Service</a></li><li><a href="http://www.apple.com/legal/privacy">Privacy Policy</a></li><li><a href="http://www.apple.com/support/">Contact Us</a></li></ul>
12:15:59 </div>
12:15:59 
12:15:59 
12:15:59 <script type='text/javascript'>(function() {
12:15:59     var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
12:15:59     document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
12:15:59     var yearEl = document.getElementById('year');
12:15:59     if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
12:15:59 })();
12:15:59 </script>
12:15:59 
12:15:59 </body>
12:15:59 </html>'[0m`

**Comment by jontelang** [comment]
Is the issue here that App Store Connect cannot change 'What to test' before processing completes? Regardless, I'd love for this to work together as well.

**Comment by alombard** [comment]
Is there an update on this by chance?  I'm facing an issue where deploy time is capped in Azure Devops so setting the "what to test" and not waiting for the build to process would be preferable if this is possible (ITC can take way more than 30 minutes in my experience so this becomes an issue unfortunately).
