### ISSUE TITLE
upload_to_app_store not able to activate languages

### ISSUE THREAD

**Issue by salmanasiddiqui** [fastlane/fastlane#12622]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to upload metadata + screenshot in `en-US` and `fr-FR`. The failure comes when fastlane tries to activate languages. The app on itunesconnect currently has `en-US`, `en-CA` and `fr-CA` activated. I have used this Fastfile to upload metadata for other apps and it worked fine; on itunesconnect it activated only the given languages while deactivating rest. Not sure what's going on, all I know is after trying to activate language; fastlane uploads the `rating.json`, and then it again activates language and start uploading screenshots. But for this app, it fails on first try to activate languages.

The metadata and screenshots are in `fastlane/metadata` and `fastlane/screenshots` directory. The screenshots are valid, I have tested by uploading them manually.

I will appreciate if anyone can share alternate way to activate language on itunesconnect using spaceship.

##### Complete output when running fastlane, including the stack trace and command used

This I copied from `reports.xml`..  not sure how `capture_output` works neither found docs
<details>
  <pre>/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/actions_helper.rb:48:in `execute_action'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'&#10;Fastfile:108:in `block in parsing_binding'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane.rb:33:in `call'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `execute'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:332:in `run'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.96.1/bin/fastlane:20:in `&lt;top (required)&gt;'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/bin/fastlane:23:in `load'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/bin/fastlane:23:in `&lt;top (required)&gt;'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in &lt;top (required)&gt;'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `&lt;top (required)&gt;'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/bin/bundle:23:in `load'&#10;/Users/salmansiddiqui/.rbenv/versions/2.4.2/bin/bundle:23:in `&lt;main&gt;'&#10;&#10;In order to save your changes, all 5.5&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&amp;quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space.</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'spaceship'

DEFAULT_LOCALES = %w[en-US fr-FR].freeze

lane :publish_ipa_file do |options|
  upload_to_app_store(
    username: USERNAME,
    team_name: ios_tunes_team_name,
    dev_portal_team_id: ios_portal_team_id,
    app_identifier: IOS_APP_ID,
    skip_binary_upload: true,
    platform: 'ios',
    languages: DEFAULT_LOCALES,
    app_rating_config_path: 'fastlane/rating.json',
    price_tier: 0,
    reject_if_possible: true,
    automatic_release: true,
    force: true
  )
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.13.0  | ✅ Up-To-Date  |
| fastlane-plugin-brew    | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.13.0       |
| fastlane-plugin-brew      | 0.1.1        |
| rest-client               | 2.0.2        |
</details>

*generated on:* **2018-05-26**
</details></pre>
</details>

**Comment by salmanasiddiqui** [comment]
After looking into spaceship codebase, I found [`create_languages`](https://github.com/fastlane/fastlane/blob/7011471ca3bd6a27f863ee35fdeed8b67b52901e/spaceship/lib/spaceship/tunes/app_version.rb#L305) function.. so I tried the following in `bundle console`:

```ruby
require 'spaceship'
ss = Spaceship::Tunes.login(username, password)
ss.select_team #selected my team
app = Spaceship::Tunes::Application.find(app_identifier)
v = app.edit_version
v.create_languages('fr-FR')
v.save!
```
The above resulted in the same error I get when using `upload_to_app_store` action

😢

**Comment by joshdholtz** [comment]
@salmanasiddiqui Heyyyy 👋 So I was able to run the exact code you posted above and it work 💯 for me 😬 Which I guess is good news and bad news. Good news because things work but bad news is that it makes it hard to debug your situation now.

Your error above says `In order to save your changes, all 5.5&quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7&quot; displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7&quot; displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 5.5&quot; displays must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7&quot; displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space.` which makes it sound like that you _might_ have some "bad" images already uploaded to your app.

Are you able to add `fr-FR` to your app via the iTunesConnect website directly? That might be the first place I would look to debug this. If that doesn't work I would maybe clear all the screenshots and then try to add a language.

Sorry for not being able to help more but I can't duplicate your issue on my end 😢

**Comment by salmanasiddiqui** [comment]
🙁 it was working for me aswell till May 24th, but not anymore.

I am able to add `fr-FR` to my apps via iTunesConnect website directly. Screenshot/metadata is all valid otherwise apple wouldn't let me upload it for already activated languages right? Something is wrong while activating/deactivating languages, but I am not really able to figure out what.

Also, before May 25th, for some apps which had `en-US, en-CA and fr-CA` locales activated, I updated metadata and changed locales to `en-US and fr-FR` using my lane `publish_ipa_file`. Now I have modified my `Fastfile` and changed the `DEFAULT_LOCALES` to `en-US, en-CA, fr-CA`. Running `publish_ipa_file` for the schools which were updated by my lane before May 25th now fails with the same error.

**Comment by joshdholtz** [comment]
@salmanasiddiqui Do things work for you if you try downgrading to _fastlane_ `2.95.0`?

**Comment by salmanasiddiqui** [comment]
@joshdholtz I am not sure at all but this might be related https://github.com/fastlane/fastlane/pull/11555

As I have given up on modifying languages and currently just went with what was activated by default, I will need some time to reproduce the issue as the above PR suggest.
