### ISSUE TITLE
Spaceship::Tunes::Error: ITC.apps.universal.pricing.intervalsCreatingMissingError

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#12628]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have tried to upload the availability

```
[4] pry(#<Spaceship::Playground>)> availability = Spaceship::Tunes::Availability.from_territories([])
=> #<Spaceship::Tunes::Availability:0x3fef2b556360>
[5] pry(#<Spaceship::Playground>)> app.update_availability!(availability)
Spaceship::Tunes::Error: ITC.apps.universal.pricing.intervalsCreatingMissingError
from /Users/bolo/.rvm/gems/ruby-2.5.0/bundler/gems/fastlane-90b924c030e6/spaceship/lib/spaceship/tunes/tunes_client.rb:228:in `handle_itc_response'
[6] pry(#<Spaceship::Playground>)> 
```

I have got this error Spaceship::Tunes::Error: ITC.apps.universal.pricing.intervalsCreatingMissingError

**Comment by aliofye** [comment]
@bolom can you tell us why you closed this issue and whether you found the solution to this problem?

**Comment by bolom** [comment]
In my case it was an error in my code

Le mar. 3 juil. 2018 à 16:56, Felipe Oliveira <notifications@github.com> a
écrit :

**Comment by gholias** [comment]
@bolom Could you please share what was the error?
This is my code
```
# update territories
      require "spaceship"
      Spaceship::Tunes.login()
      app = Spaceship::Application.find("com.myapp.myid")      
      availability = Spaceship::Tunes::Availability.from_territories(["US", "CA"])            
      availability = app.update_availability!(availability)
```
