### ISSUE TITLE
New Action : For uploading app to BrowserStack

### ISSUE THREAD

**Issue by raghuhit** [fastlane/fastlane#12627]
#### Motivation Behind Feature

This action will let users to upload their app to BrowserStack, and after that they can run manual or automated tests on that app. 
BrowserStack is a cloud-based platform for testing mobile apps and websites on real devices. It is used by more than 25000 developers across the globe; including freelancers, small teams, as well as large enterprises.
BrowserStack also offers free access to open source community through its Open Source Program. Till date, 1000+ open source projects have used BrowserStack, including jQuery, AngularJS, Zurb Foundation, Video.js.

#### Feature Description

1. **Feature detail**: 
- The action will upload apk and ipa files to BrowserStack for performing manual and automated tests on the uploaded app. 
- In case of automated testing, the action will set the value of uploaded app's id in an environment variable "BROWSERSTACK_APP_ID" as well as in the SharedValues with the same variable name, which can be used in next steps for running tests.

2. **Code Examples**: Sample Fastlane step for uploading app to browserstack : 

> upload_to_browserstack(
            browserstack_username: ENV["BROWSERSTACK_USERNAME"],
            browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
            file_path: "absolute_path_to_apk_or_ipa_file",
            project_type: "AUTOMATE" # available options MANUAL and AUTOMATE, default is AUTOMATE
           )

3. Output of running this action will be something like : 

> Uploading app to BrowserStack...
[16:11:29]: Successfully uploaded app /absolute_path_to_apk_or_ipa_file to BrowserStack with app_url : uploaded_app_id
[16:11:29]: Setting Environment variable BROWSERSTACK_APP_ID = uploaded_app_id

4. Since this is a completely different action, it will not have any impact on existing fastlane functionalities. Hence it will not break anything for existing users.

#### Alternatives or Workarounds
1. There is no current alternative present in fastlane actions for doing this.

**Comment by joshdholtz** [comment]
@raghuhit Heyyyy 👋 Thanks for the detailed feature request! I really appreciate the time and effort put into it ❤️ 

However, we are currently not accepting any new actions directly into fastlane that involve integration into third party services at this moment. Most third party integrations like this should be created as plugins (https://docs.fastlane.tools/plugins/create-plugin/) that are available for fastlane users to add into their project. It would be ideal for BrowserStack to maintain this fastlane plugin themselves that may not be a thing that they would like to support themselves. There are a quite a few community support plugins like this so I think this would be best place for this

So my suggestion here would be to either see if BrowserStack is interested in creating/supporting a fastlane plugin for this, creating this your own, or finding someone else to make this 😊 

Thanks again for all the detail in your feature request! Happy fastlaning 🚀

**Comment by raghuhit** [comment]
@joshdholtz  I really appreciate the quick response. 

However, I want to emphasize on how it can add value to current beta action list. While the current list solves the problem of app distribution in beta, it lacks actions that helps developers test on multiple devices. 

It is a problem faced by majority of Android & iOS developers in small to large organisations and solves a critical aspect of app development. Requesting you to re-evaluate this.

**Comment by joshdholtz** [comment]
@raghuhit I completely understand how important an action of this can be to a user 😊 We have things similar in the repo right now (`hockey`, `crashlytics`, etc), these are in here mainly for legacy support right now. _fastlane_ used to accept all actions but it ended up making maintenance/support on the core maintainers much more difficult/time consuming since all of these third party services needed to be learned and tested (which ends up involving creating an account in each of these services to test). 

Having a third party service integration like this is much better suited to be maintained by someone who is a export/regular at using this service - (which is why I recommended that this would be ideal if BrowserStack themselves would maintain a _fastlane_ plugin). Plugins are still searchable through our docs so its not like they are lost or disconnected from our fastlane ecosystem but it is easier to maintain and update a third party service independently than coupling it into fastlane directly.

**Comment by raghuhit** [comment]
@joshdholtz , thanks for your response, I will create a plugin for that.

**Comment by raghuhit** [comment]
@joshdholtz I have created the fastlane plugin for browserstack at https://github.com/browserstack/browserstack-fastlane-plugin as discussed, and published it too.
Can you tell me, what should I do so that it would appear at https://docs.fastlane.tools/plugins/available-plugins/

**Comment by joshdholtz** [comment]
@raghuhit This is fantastic! Thanks for making this plugin 🙌  I actually have a need for this soon so looking forward to using it. And its up on the docs now! New plugins don't appear until we rebuild the docs (cause static stuff) 😉
