### ISSUE TITLE
upload_to_app_store should have a flag to not wait for build processing

### ISSUE THREAD

**Issue by salmanasiddiqui** [fastlane/fastlane#12649]
#### Motivation Behind Feature

I am automating our ios delivery process, we have around 200 apps to build and submit. I used sidekiq for concurrency and have divided the process into 3 workers.

1.  BuildAppWorker (this executes a lane which calls `gym` action and generates ipa)
2. UploadAppWorker (this executes a lane which calls `upload_to_app_store` action and uploads ipa + metadata + screenshot + rating + price tier)
3. SubmitAppWorker (this executes a lane which calls `upload_to_app_store` action and just submits the uploaded build for review)

The problem arises on step3, as `upload_to_app_store` waits for apple build processing to complete and that results in sidekiq worker to stay in progress.
By adding a flag like `wait_for_build_processing` (defaults to `true`), then it will make this action `upload_to_app_store` much more efficient for automation. Atleast I will just set that flag as `false` for my use case and things will work perfectly.

#### Feature Description

There should be a `wait_for_build_processing` flag in `upload_to_app_store` action, which should default to `true` for backward compatibility. This flag should do nothing if `submit_for_review` is `false`. If `submit_for_review` is `true` then this flag should decide if fastlane should wait for apple to complete the build processing or not.

This should not break anything for existing users.

#### Alternatives or Workarounds

I am currently implementing it, and it will be similar to [submit_for_review.rb](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/submit_for_review.rb)

I think only the [select_build](https://github.com/fastlane/fastlane/blob/c2ce640997b0aa7b6e5550c7b93d144dd5372a90/deliver/lib/deliver/submit_for_review.rb#L32) function should be modified, where it calls the `wait_for_build` we just need to ensure if flag is true, incase its false, then we should call `find_build` if the build is found then proceed, else fail.

**Comment by joshdholtz** [comment]
@salmanasiddiqui Heyyy 👋 Quick question on your feature request. If `wait_for_build_processing: false` and `submit_for_review: true` and the build is not yet processed, are you expecting the action to fail?

**Comment by salmanasiddiqui** [comment]
Yes, I am expecting it to fail.

**Comment by joshdholtz** [comment]
@salmanasiddiqui Cool cool, just wanted to make sure.  I will think about this one 🤔 I'm not sure if this should be built directly into `upload_to_app_store` since this seems kind of niche but this should also be possible for you to do with _spaceship_ directly. I will look into both options and let you know what is best here. If its the _spaceship_ option, I will give you example code that can do what you are looking for so you can put this into a custom lane or custom action of your own 👌

**Comment by salmanasiddiqui** [comment]
oh yes this can be done with `spaceship` and I know how I can do that, will do it once I get rid of other blockers i keep getting 😓  (you probably know as you have commented on other issues of mine)..

I was just thinking that it should be part of fastlane too, also I too think it should be a separate action than `upload_to_app_store`. And there should just be a comment in the documentation of `upload_to_app_store` | `submit_for_review` parameter, that

> this will submit the app for review after waiting for it to be processed by apple, but it does not work 100% of the time. As sometimes builds take time to be visible on apple (and it won't return the recently uploaded build), while other times builds just stuck in processing and requires us to upload build with new build number.

**Comment by joshdholtz** [comment]
@salmanasiddiqui We are trying to limit the addition of actions right now as its more of us to maintain but it _does_ seem like this would be a better fit for an action 🤔 I will throw that into my thinking session as well of where this best fits 👍
