### ISSUE TITLE
[match] improve educational experience when initializing and using match

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#12641]
#### Motivation Behind Feature
- To provide a clearer understanding and educate new users to _match_ on how certificates are handled to prevent less confusion and issues and create more productivity for all 🎊 

#### Feature Description/Tasks
- [ ] Give users a consent style prompt so they can acknowledge they know (or will learn how) _match_ works
  - Rough idea: a “consent” style yes/no in the match init process might saying “match cannot use any existing certs that are in the ios dev portal. match will have to create new certs to use. view match doc(link) to learn more. continue?”
  - Also make sure that prompt for _match_ password clearly states to the user that this password **is not** their Apple password
- [ ] Improve documentation on _match_ will integrate/behave with existing projects/certificates
  - Highlight important key aspects with fancy pants CSS
  - Inform users existing certs will **probably** need to be revoked to make things run the smoothest
  - Inform users that _match_ (but really _sigh_) uses the latest cert in the iOS Dev Portal to create new provisioning profiles
  - Inform and highlight users that the _match_ password **is not** their Apple password (its something completely separate)

#### Alternatives or Workarounds
- Learning by mistakes
- Searching through existing issues to answer questions
- Creating new issues to get questions answered

**Comment by taquitos** [comment]
Yeah, I would also maybe even make a call out to that their private key is the problem here, and then link them to our documentation that talks about how that private key actually works at https://codesigning.guide

**Comment by getaaron** [comment]
Why not allow them to import the private keys if they already have them in their keychain?

I run into this a lot for work - I’m hired to write an app, the company already has 6 apps and both App Store certs are in use, so I have to take the existing key and manually create a match repo

**Comment by getaaron** [comment]
😈

**Comment by joshdholtz** [comment]
Linking to a thing about importing keys that @KrauseFx wrote years ago - https://github.com/fastlane/fastlane/pull/9752#issuecomment-320373291
