### ISSUE TITLE
sign download_all crash

### ISSUE THREAD

**Issue by kevinlevelex** [fastlane/fastlane#12643]
### Issue Description
When running bundle exec fastlane sigh download_all --verbose --download_xcode_profiles we are seeing a crash downloading provision profiles.   It appears that it has to do with a default keychain, but the crash does not appear on a fresh reboot.  Unclear what is missing or changing

Issue started recently ~4/25/2018

##### Complete output when running fastlane, including the stack trace and command used

```
+ bundle exec fastlane sigh download_all --verbose --download_xcode_profiles
[33mSuccessfully loaded Appfile at path '/Users/buildbot/.jenkins/workspace/Client Projects/Airway_Baxter_Suprane_iOS/BuildTools/fastlane/Appfile'[0m
- [36mapple_id[0m: '[32mREDACTED@email.com[0m'
- [36mitunes_connect_id[0m: '[32mREDACTED@email.com[0m'
- [36mteam_id[0m: '[32mREDACTED_TEAM_ID[0m'
-------
INFO [2018-05-29 12:20:45.81]: Starting login with user 'REDACTED@email.com'
INFO [2018-05-29 12:20:48.82]: Successfully logged in
INFO [2018-05-29 12:20:50.40]: Downloading profile 'Pulm EX Development'...
ERROR [2018-05-29 12:20:50.89]: [31mFailure to decode ./Development_d6b39736-08f9-485c-8db2-5fa90d34eed7_com.levelex.pulm.mobileprovision. Exit: 1: security: cert import failed: A default keychain could not be found.
security: problem decoding
[0m
```

### Environment
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| json                      | 2.1.0        |
</details>

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by kevinlevelex** [comment]
It appears that UE4 may be interfering with something fastlane is depending on.

Reboot OSX Machine
Build using fastlane on OSX machine = Success 
Remote build UE4 project on OSX machine
Build using fastlane on OSX machine = security crash

**Comment by joshdholtz** [comment]
@kevinlevelex I can't tell from this but if this is being down from an SSH session, keychains are usually not accessibly. But it does look like something is removing your default keychain from your keychain path.

Does `security list-keychains` list `login.keychain-db` before your UE4 build and but after?
