### ISSUE TITLE
How do I disable the changelog spam from the command line?

### ISSUE THREAD

**Issue by EdwardDrapkin** [fastlane/fastlane#12647]
We're not pacing Fastlane's latest release cycle because it's difficult, and Fastlane takes over stdout with its changelog.

Is there anyway to turn off this super-obnoxious behavior?  This is the sort of thing that makes users want to find alternatives that are less pushy and obnoxious and understand the enterprise release cycle isn't always the bleeding edge.

**Comment by joshdholtz** [comment]
I think this is what you are looking for 😊 https://docs.fastlane.tools/advanced/#hide-changelog-information-at-the-end-of-running-fastlane
