### ISSUE TITLE
New Action Request: itc_team_name

### ISSUE THREAD

**Issue by kumichou** [fastlane/fastlane#12644]
#### Motivation Behind Request
Fastlane has a built-in team_name action that internally sets the environment variables FASTLANE_TEAM_NAME and PRODUCE_TEAM_NAME. These can then be used instead of hard-coding a team_id (or setting FASTLANE_TEAM_ID) in a project when interacting with Produce, Deliver, and Match.

There doesn't appear to be an iTunes Connect equivalent of the `team_name` action. This can be very useful for projects that may be built and deployed for different teams so Appfile configuration would be restrictive.

#### Feature Description
Usage would be `itc_team_name("Krause Fx")` which would then set the FASTLANE_ITC_TEAM_NAME and PRODUCE_ITC_TEAM_NAME environment variables to the value **Krause Fx** following the same pattern set forth in the `team_name` action.

#### Alternatives or Workarounds
Manually set FASTLANE_ITC_TEAM_NAME and PRODUCE_ITC_TEAM_NAME in Fastfile (or externally in environment).

I would be more than happy to submit a PR for this 😁

**Comment by joshdholtz** [comment]
@kumichou We are limiting the addition of new actions but I think maybe we could add two options onto the existing `team_name` action? We could add `dev_portal` (defaults to `true`) and `itc` (defaults to `false`). Thoughts? I would totally be down for accepting this PR if you would like to do this 🤗

**Comment by kumichou** [comment]
@joshdholtz Fair enough. Since this is more about overriding settings outside of the Appfile/Matchfile/etc, would something like this work:

`team_name(team: 'Company X')` is the current logic, not setting iTC related env vars
`team_name(team: 'Company X', itc: true)` would be current logic and also set iTC env vars
`team_name(team: 'Company X', dev_portal: false, itc: true)` would skip current logic but set iTC env vars

Is this what you mean?

**Comment by joshdholtz** [comment]
@kumichou That is exactly what I mean 😊 That looks 💯 to me!

**Comment by kumichou** [comment]
@joshdholtz OK, so had to handle some other stuff before coming back to this. So, with the announcement of the updated API for App Connect, does this make any sense to do this? I'm all for contributing the solution but don't want to submit it if the new API will be available and supported in say 2 months or some other short time frame. Thoughts?

**Comment by kumichou** [comment]
OK, so I will get on putting this together ASAP 😅

**Comment by kumichou** [comment]
Easy @fastlane-bot , I'm in the middle of the code change. Give me a few more days to complete and update folks here.

**Comment by janpio** [comment]
Your reply "granted" you another 30 days before @fastlane-bot will try to be helpful again @kumichou :)

**Comment by svanzoest** [comment]
This is somewhat related to #10796 as you need the provider Id as well.
