### ISSUE TITLE
Increment version/build number for specific target

### ISSUE THREAD

**Issue by gpbl** [fastlane/fastlane#1264]
👋 

Is there a way to use `increment_version_number` and `increment_build_number` only for specific targets? I have multiple targets following a different version numbering...

Thanks!

**Comment by sprobst** [comment]
I had the same problem today!
Check if `agvtool next-version -all` works in your terminal. My problem was, the tool could not find the Info.plist file for one target. When I updated the path for the .plist file in Xcode's Project, updating the build number worked.

**Comment by gpbl** [comment]
:smile: I'm looking for a way to bump specific targets. `agvtool` affects the version number for *all* the targets so I guess the fastlane actions are just a wrapper over it. 

What I do now is to go in Xcode and change manually the version number: I wonder if this could be automatised by fast lane somehow...

**Comment by sprobst** [comment]
From what I've seen in the code, they are indeed just a wrapper. I.e. if the `agvtool` can't bump specific targets, so can't fastlane.
However, you could try implement the desired behavior in pure Ruby: Read the .plist file, update the correct value and write the file back. Then build your target.

**Comment by ohwutup** [comment]
this is a great topic. i have actually run into this same issue in the past also. and also been plagued by not using Apple Generic Versioning. that being said, i think we will likely keep using `agvtool` for now as it is what apple recommends, but using plistbuddy for a shell script or just parsing the file with ruby is definitely a good option and I'm sure people would love to see a generic solution for that! feel free to submit a custom action that can do this on a target-by-target basis! :100:

**Comment by tomassliz** [comment]
So what is the result of this issue? If we have multiple targets in the project, we should not use Apple Generic Versioning? It's easy to accomplish similar behaviour with `update_info_plist` so maybe new wrapped action would make sense here.

**Comment by gpbl** [comment]
I think the suggestion by @ohwutup is that we should make a script by ourselves :)
