### ISSUE TITLE
Pilot should check that groups is set at start of process if distribute_externally requested

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#12642]
### Feature Request

Pilot should inform you that 
`'You must specify at least one group using the `:groups` option to distribute externally'`
Before building, uploading and waiting for the build to process
(currently it builds, uploads, waits for processing, then spits out an error)

#### Motivation Behind Feature

The build / upload / wait process can take a long time (mine was just 30mins).
The error could easily have been presented at the start

#### Feature Description

If distribute_external == true, then check that groups = #some plausible value# before running

Currently, Pilot would upload the build - then error. This would error before uploading.
If some user was relying on the upload and ignoring the error, then this could break for them - but they really shouldn't be ignoring errors...

#### Alternatives or Workarounds

know what is required up front
better documentation?

n/a

**Comment by joshdholtz** [comment]
@ConfusedVorlon Thanks for this request 😊 I agree with this 👌
