### ISSUE TITLE
Test target JustDeployUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

### ISSUE THREAD

**Issue by aravind1os** [fastlane/fastlane#12656]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@aravind1os Going to close this issue since the standard issue template was not used with all the requested information. Please open another issue following the issue template and I will be able to look into further 😊
