### ISSUE TITLE
Add create Play Store listing for Android to supply

### ISSUE THREAD

**Issue by jmarkoff** [fastlane/fastlane#12655]
### Feature Request
Add create option to the supply action to facilitate creating Play Store listings.

I work with large enterprises that have to migrate apps to Managed Google Play. Some of these enterprises have 100+ internal applications and this process is quite painful to do this manually. I would love to steer them towards fastlane.

#### Motivation Behind Feature
Adding "create play store listings" would be extremely helpful for developers with large amounts of applications. It also helps automate cross platform. This feature exists for iOS and it's holding back enterprises I work with on adopting the other great features of fastlane/supply. This would be a significant enhancement so fastlane can be used for the whole automation flow.

More information on how to do this with the Play API
https://developers.google.com/android-publisher/#publishing

Example of the code in Java - https://github.com/googlesamples/android-play-publisher-api/blob/master/v3/java/src/com/google/play/developerapi/samples/UpdateListing.java (See the create listing as part of the Google client libraries).

#### Feature Description
Add feature similar to create from the produce (https://docs.fastlane.tools/actions/produce/) action.

fastlane supply create

Options for create: (Some ideas but not limited to)
  -p, --package_name STRING Package name (e.g. com.android.app) (SUPPLY_PACKAGE_NAME)
  -l, --language STRING Title (e.g. for example, "de-AT" for Austrian German) (SUPPLY_LANGUAGE)
  -t, --title STRING Title (SUPPLY_TITLE)
  -s, --short_description STRING Short App Description (SUPPLY_SHORT_DESCRIPTION)
  -d, --full_description STRING Full App Description (SUPPLY_FULL_DESCRIPTION)
  -v, --video STRING Video URL (SUPPLY_VIDEO)

Found a listing of supported keys under class Listing [here](https://github.com/google/google-api-ruby-client/blob/f1edceed1881dc2773b679789014b14cfc746fb7/generated/google/apis/androidpublisher_v2/classes.rb).

This will not break any functionality. There are also no drawbacks.

#### Alternatives or Workarounds
The workaround is to use the Play REST API directly which is pretty rough for one missing feature.

**Comment by joshdholtz** [comment]
@jmarkoff 👀 ... _pushes everything off desk_... Investigating now 💪

**Comment by joshdholtz** [comment]
@jmarkoff Heyyyy 👋 I tried giving this a go but I kept running into `Google::Apis::ClientError: [!] applicationNotFound: No application was found for the given package name.` when trying to create the edit. The Java example you linked looks like it is creating the insert in a similar way. It only sets the package name and nothing else. Both of these routes also do a `POST` to `<package_name>/edits`. I'm not sure if I'm missing something when creating the edit to tell the Google Service API that "Hey, I'm creating a new app" or if the Ruby client is doing something wrong 🤔

Would you be help me figure out what is going on here? 🙏 It looks like what I'm doing below should "just work" based upon the Java example.

### Use
```ruby
# Using Google::Apis::AndroidpublisherV2
android_publisher.insert_edit(package_name)
```

Insert method - https://github.com/google/google-api-ruby-client/blob/02b88ae098d41aebe40f5c062e1246d8d5db2558/generated/google/apis/androidpublisher_v2/service.rb#L166-L201

### Full Response

```bash
Google::Apis::ClientError: [!] applicationNotFound: No application was found for the given package name.
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:218:in `check_status'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/api_command.rb:116:in `check_status'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:183:in `process_response'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:299:in `execute_once'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
  /Users/josh/.gem/ruby/2.3.7/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
  /Users/josh/.gem/ruby/2.3.7/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
  /Users/josh/.gem/ruby/2.3.7/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:101:in `block in execute'
  /Users/josh/.gem/ruby/2.3.7/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
  /Users/josh/.gem/ruby/2.3.7/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
  /Users/josh/.gem/ruby/2.3.7/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:93:in `execute'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
  /Users/josh/.gem/ruby/2.3.7/gems/google-api-client-0.21.2/generated/google/apis/androidpublisher_v2/service.rb:200:in `insert_edit'
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/client.rb:92:in `begin_edit'
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/uploader.rb:6:in `perform_upload'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:39:in `block (2 levels) in parsing_binding'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/josh/Projects/fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/josh/Projects/fastlane/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/josh/.gem/ruby/2.3.7/bin/fastlane:22:in `load'
  /Users/josh/.gem/ruby/2.3.7/bin/fastlane:22:in `<top (required)>'
```
