### ISSUE TITLE
Fastlane IOS Universal Links / Associated domains

### ISSUE THREAD

**Issue by zyhou** [fastlane/fastlane#12658]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Description

We are using fastlane in Travis with fastlane-plugin-cordova to deploy Android and IOS apps. All deliveries works well and we are happy about fastlane/match.

Some links can open automatically our apps but he doesn't work on IOS when we using fastlane. He work well in Android. When we deploy manually IOS (with XCode), universal links works.

I don't understand where the problem comes from.

Delivery Summary
![selection_001](https://user-images.githubusercontent.com/2212144/40773438-278deaf8-64c3-11e8-85f4-9830c104598d.png)

Deliver summary
![image](https://user-images.githubusercontent.com/2212144/40773681-edc8519a-64c3-11e8-83cb-8b2e74c01993.png)

**Comment by joshdholtz** [comment]
@zyhou Heyyy 👋 I can't give a lot of help with the information that are able to provide but it sounds like maybe your fastlane setup isn't building with the proper set of entitlements? 🤔 I would probably start look around there by comparing the build output by fastlane has the same set of entitlements as the build output by Xcode

**Comment by chapayGhub** [comment]
Have the same issue

**Comment by chapayGhub** [comment]
@zyhou Did you find solution for this issue?

this is my lane
```
    lane :beta do |values|  
        #puts Dir.pwd    

        #build constants
        buildType = "beta"

        # increment_build_number    

        derivedDataDir = "tmp.fastlane/derived.data"
        resultBuildDir = "tmp.fastlane/build/beta"        

        tcPrefixName = values[:ipa_prefix] ? values[:ipa_prefix] : "none_tc_build"
        ipaVersion = get_version_number(xcodeproj: "xxxxx.xcodeproj", target: "xxxxx")
        ipaBuild = get_build_number(xcodeproj: "xxxxx.xcodeproj")

        ipaName="#{tcPrefixName}_xxxxx_ios_#{buildType}_v#{ipaVersion}.#{ipaBuild}.ipa"

        defaultXcodeIpa = "#{resultBuildDir}/xxxxx.ipa"
        resultIpa = "#{resultBuildDir}/#{ipaName}"

        # #clear previous build info
        clear_derived_data(derived_data_path: derivedDataDir)

        # #install pods with versions from Podfile.lock 
        cocoapods(repo_update: true)

        #get credential for build signin
        match( 
            type: "adhoc",
            app_identifier: "com.xxxxx.ios.xxxxx",
            readonly: true
        )

        #build ios ipa
        gym( 
             workspace: "xxxxx.xcworkspace",
             scheme: 'xxxxx',
             clean: true,
             derived_data_path: derivedDataDir,
             output_directory: resultBuildDir,                         
             export_options: {
                  signingStyle: "automatic",
                  uploadBitcode: false,
                  uploadSymbols: false,
                  compileBitcode: false,                  
             }
            )

        #clear previous build info
        clear_derived_data(derived_data_path: derivedDataDir)

        #hide precommit hook, it breaks down git_commit command from this script
        precommit_hook = "../Scripts/git/pre-commit"
        precommit_hook_hided = "#{precommit_hook}.hided"
        
        if File.exist?(precommit_hook)
          File.rename(precommit_hook, precommit_hook_hided)
        end

        begin
          git_commit(
              path: [
                  "CommonApp/Info.plist", 
                  "xxxxx.xcodeproj/project.pbxproj", 
                  "xxxxx/Info.plist", 
                  "NetworkApp/Info.plist", 
                  "PersistantApp/Info.plist"
                  ], 
              message: "Version Bump")
                  
          push_to_git_remote
        ensure
          #return git precommit hook
          if File.exist?(precommit_hook_hided)
            File.rename(precommit_hook_hided, precommit_hook)          
          end
        end

    end
```

@joshdholtz  No any problems with permissions ((( May by you know somebody who can help us with this issue?
