### ISSUE TITLE
Fastlane pilot - TestFlight upload gets stuck randomly

### ISSUE THREAD

**Issue by ItsNoHax** [fastlane/fastlane#12650]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Our Jenkins CI build runs fastlane to upload new app versions to Testflight. Unfortunately sometimes the builds get stuck at uploading. No error or anything, they just keep on going. I figured it probably is a firewall issue but even with -t DAV option it is still happening. Any idea what we are doing wrong?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[DEBUG [2018-05-29 17:31:13.07]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2018-05-29 17:31:13.08]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2018-05-29 17:31:13.22]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2018-05-29 17:31:13.22]: [Transporter]: DEBUG: Saving configuration to local path: /Users/jenkins/.itmstransporter/Defaults.properties
DEBUG [2018-05-29 17:31:13.22]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.8]
DEBUG [2018-05-29 17:31:13.22]: [Transporter]: INFO: OS identifier: Mac OS X 10.13.4 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-05-29 17:31:13.22]: [Transporter]: INFO: Memory: [JVM] 797M free, 981M total, 981M max [System] (Physical) 29005M free, 32768M total (Swap) 834M free, 3072M total
DEBUG [2018-05-29 17:31:13.23]: [Transporter]: INFO: Upload mode selected.
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: INFO: Examining the package at: /var/folders/gg/4ntqwgjn1gn1yrkhb22tqbjc0000gp/T/d20180529-73327-gsw9ux/1176066221.itmsp
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: DEBUG:   df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2018-05-29 17:31:13.24]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2018-05-29 17:31:13.26]: [Transporter]: INFO: Performing authentication of package 1176066221.itmsp ...
DEBUG [2018-05-29 17:31:13.26]: [Transporter]: DBG-X: Memory: [JVM] 787M free, 981M total, 981M max [System] (Physical) 28993M free, 32768M total (Swap) 834M free, 3072M total
DEBUG [2018-05-29 17:31:13.26]: [Transporter]: DBG-X: Memory: [JVM] 787M free, 981M total, 981M max [System] (Physical) 28993M free, 32768M total (Swap) 834M free, 3072M total
DEBUG [2018-05-29 17:31:13.26]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.4 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-05-29T17:31:13+02:00
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.316295786
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u HIDDEN -p **hidden value** -f /var/folders/gg/4ntqwgjn1gn1yrkhb22tqbjc0000gp/T/d20180529-73327-gsw9ux/1176066221.itmsp -t DAV -t Signiant -k 100000
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter Username = HIDDEN
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-05-29 17:31:13.27]: [Transporter]: INFO: id = 20180529173113-174
DEBUG [2018-05-29 17:31:13.97]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter TxHeaders = {dc=mr26p00it-contdelivery022}
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter SessionId = CM2oDBIQ4jQAHjcEQbmoR0/h3i0uUw==
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X: Deflated 484 bytes to 424
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X: Using operation named: validateMetadata
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter Files = [df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa, metadata.xml]
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter MetadataChecksum = 6084ad90ab55bee4fb8a404ff2b55bc6
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.4 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter PackageName = 1176066221.itmsp
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter PackageSize = 13661893
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-05-29T17:31:13+02:00
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u HIDDEN -p **hidden value** -f /var/folders/gg/4ntqwgjn1gn1yrkhb22tqbjc0000gp/T/d20180529-73327-gsw9ux/1176066221.itmsp -t DAV -t Signiant -k 100000
DEBUG [2018-05-29 17:31:13.98]: [Transporter]: DBG-X:   parameter Username = HIDDEN
DEBUG [2018-05-29 17:31:13.99]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-05-29 17:31:13.99]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-05-29 17:31:13.99]: [Transporter]: INFO: id = 20180529173113-056
DEBUG [2018-05-29 17:31:15.73]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-05-29 17:31:15.73]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa]
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa, ShouldDescribeAsset=true, UTI=com.apple.ipa}]
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter CPUToken = de09beb5-ec83-42a5-a3d2-ff9cfdfed93d/1527607877300
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter Checksums = {df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa=42ccac97b9e286a443b8baf538faad15}
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter FileSizes = {df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa=13661409}
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter ProviderNameForToken = AA59X2J6VY
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa].  These are the files that will be uploaded.
DEBUG [2018-05-29 17:31:15.74]: [Transporter]: INFO: Starting media analysis of assets
DEBUG [2018-05-29 17:31:16.06]: [Transporter]: DEBUG: Handling asset: filename=df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa,uti=com.apple.ipa,role=source,describe=true
DEBUG [2018-05-29 17:31:16.06]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.25
DEBUG [2018-05-29 17:31:16.06]: [Transporter]: DEBUG: Using path: /var/folders/gg/4ntqwgjn1gn1yrkhb22tqbjc0000gp/T/d20180529-73327-gsw9ux/1176066221.itmsp/df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa
DEBUG [2018-05-29 17:31:23.25]: [Transporter]: DBG-X: description length:0
DEBUG [2018-05-29 17:31:23.25]: [Transporter]: DBG-X: Asset description: 
DEBUG [2018-05-29 17:31:23.25]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@6548bb7d
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X: Deflated 629 bytes to 382
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: INFO: Asset media analysis has completed
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X: Memory: [JVM] 897M free, 981M total, 981M max [System] (Physical) 28646M free, 32768M total (Swap) 1388M free, 2048M total
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.4 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-05-29T17:31:23+02:00
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u HIDDEN -p **hidden value** -f /var/folders/gg/4ntqwgjn1gn1yrkhb22tqbjc0000gp/T/d20180529-73327-gsw9ux/1176066221.itmsp -t DAV -t Signiant -k 100000
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter Username = HIDDEN
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-05-29 17:31:23.35]: [Transporter]: INFO: id = 20180529173123-274
DEBUG [2018-05-29 17:31:33.86]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-05-29 17:31:33.86]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
DEBUG [2018-05-29 17:31:33.86]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
DEBUG [2018-05-29 17:31:33.86]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-05-29 17:31:34.47]: [Transporter]: DBG-X: WebDAV status: 401
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DEBUG: Using token file path /Users/jenkins/.itmstransporter/UploadTokens/Steffens-iMac.office.base.nl_AA59X2J6VY_1176066221.itmsp.token
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DEBUG: Set token: de09beb5-ec83-42a5-a3d2-ff9cfdfed93d/1527607877300
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X: Memory: [JVM] 897M free, 981M total, 981M max [System] (Physical) 28643M free, 32768M total (Swap) 1388M free, 2048M total
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X: Deflated 484 bytes to 424
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X: Using operation named: validateAssets
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter CPUToken = de09beb5-ec83-42a5-a3d2-ff9cfdfed93d/1527607877300
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter Files = [df2aee9d99aedcce8f019930334acc93d904c5507c2759cb850df32f3c9e7a95.ipa, metadata.xml]
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter MetadataChecksum = 6084ad90ab55bee4fb8a404ff2b55bc6
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.4 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter PackageName = 1176066221.itmsp
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter PackageSize = 13661893
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-05-29T17:31:34+02:00
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter StreamingInfoList = [com.apple.transporter.streaming.StreamableFile@56781d96]
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter Transport = DAV
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u HIDDEN -p **hidden value** -f /var/folders/gg/4ntqwgjn1gn1yrkhb22tqbjc0000gp/T/d20180529-73327-gsw9ux/1176066221.itmsp -t DAV -t Signiant -k 100000
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter Username = HIDDEN
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-05-29 17:31:34.48]: [Transporter]: INFO: id = 20180529173134-429]</pre>
</details>

### Environment

<details>
  <pre>[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-05-30**
</details>]</pre>
</details>

**Comment by ItsNoHax** [comment]
@joshdholtz Don't think so, this has been happening for months. Problem is the build doesn't timeout or anything so get's really annoying.

**Comment by joshdholtz** [comment]
@ItsNoHax Huh... I see it very seldom and just running it again "fixes" it for me. Your output ends with a request sent to apple but no response (other requests end with `Apple's web service operation return value:`). It seems like the response is getting lost somewhere either on Apple's side (and there is no timeout) or an error in _transporter_ itself.

After a build gets stuck on your CI, does restarting the job usually work? (I'm not saying this is the proper fix. I'm just curious if that works for you)

**Comment by ItsNoHax** [comment]
@joshdholtz Yeah but the next build is a gamble too. I've had to retry up to 4 times before.

**Comment by joshdholtz** [comment]
@ItsNoHax That does sound super frustrating 😔 Do you have these same issues if you make a build on a dev machine? (Not on a CI)

**Comment by ItsNoHax** [comment]
@joshdholtz I will have to get back to you tomorrow about that. I don't develop on our mac and I got a couple issues to finish today.

**Comment by joshdholtz** [comment]
@ItsNoHax No probs! Just mentioned me when you have an answer 🙃

**Comment by stonedauwg** [comment]
Sounds similar to #12060 which we are experiencing as well

**Comment by theFluterr** [comment]
Also experiencing this issue with my Jenkins setup, the fastlane process was stuck there for around 8 hours. Hope it gets resolved, since it is just impossible to do pilot.

**Comment by petterikamppuririchie** [comment]
We're seeing pilot uploads getting stuck as well.

`fastlane pilot upload --skip_submission` is stuck.

I believe something happens when going to the new App Store Connect web site and accessing the TestFlight tab. That immediately triggers push notifications for new TestFlight build being available and pilot upload task proceeds forward.

Pilot upload succeeds, but it can't properly enable the build for TestFlight.

So it seems there is a change on Apple's side, and something needs to be done on the web site, which pilot doesn't yet know how to do.

**Comment by ItsNoHax** [comment]
Not sure if latest FastLane version fixed this, last couple builds have worked perfectly and I even get the feeling that they have sped up the uploading process. Will report back.
