### ISSUE TITLE
 Unable to locate Xcode. Please make sure to have Xcode installed on your machine

### ISSUE THREAD

**Issue by VarunRaj94** [fastlane/fastlane#12662]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@VarunRaj94 You need to select a version of Xcode for Xcode Command Line Tools to use. This can be done two ways:
- CLI -`$: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`
- Xcode - https://github.com/fastlane/fastlane/issues/12263#issuecomment-379959724
