### ISSUE TITLE
 no such module 'FBSDKLoginKit'

### ISSUE THREAD

**Issue by aravind1os** [fastlane/fastlane#12664]
![screen shot 2018-05-31 at 8 15 56 pm](https://user-images.githubusercontent.com/39641155/40789650-8cee88ec-6510-11e8-8c7d-4ee363363bfd.png)
![screen shot 2018-05-31 at 8 15 50 pm](https://user-images.githubusercontent.com/39641155/40789671-99894556-6510-11e8-9f58-264c521b2191.png)

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by RishabhTayal** [comment]
@aravind1os This doesn't seem like a fastlane issue. Are you able to compile your project manually through Xcode?
