### ISSUE TITLE
Consistent Invalid Builds in iTunes Connect

### ISSUE THREAD

**Issue by cmds4410** [fastlane/fastlane#1266]
Every one of my builds submitted with fastlane is getting "This build is invalid." in iTunes connect, despite no error messages during the fastlane execution: `Successfully uploaded package to iTunesConnect. It might take a few minutes until it's visible online.` I am not given any error code, nor has Apple emailed me about any issues. 

When I archive and submit using Xcode, I get no errors (see builds 52 and 58). 

<img width="744" alt="itunes connect error" src="https://cloud.githubusercontent.com/assets/721387/12761054/5e904996-c99e-11e5-84ee-b1805044d91c.png">

Here's my lane:
```
  lane :beta do
    increment_build_number
    gym(scheme: "Production", use_legacy_build_api: true, include_bitcode: true) 
    pilot

    slack(
      message: "Successfully deployed new TestFlight Build!"
    )

  end
```

I am on:
OS X 10.11.3
Xcode 7.2
fastlane 1.56.0
gym 1.4.0
pilot 1.2.1
cocoapods 0.39.0

Related SO post: http://stackoverflow.com/questions/34901766/this-build-is-invalid-on-https-itunesconnect-apple-com

Thanks!

**Comment by i2amsam** [comment]
@cmds4410 from the SO post it looks like Apple may have sent more information about that error to your developer account's email, did that ever happen?  Was this working correctly before and then regressed?

**Comment by cmds4410** [comment]
@i2amsam Unfortunately I've received communication from Apple regarding this issue. It was definitely working fine before.

**Comment by ohwutup** [comment]
hey @cmds4410 i've never seen this issue before so its a little wild to me, but before i dig in further, my initial thought is to ask if your Xcode builds also have bit code enabled?

**Comment by cmds4410** [comment]
Thanks @ohwutup, I'm currently trying to fix it as well. Yep, bitcode is enabled.

**Comment by cmds4410** [comment]
Btw the only other info I've been able to find form Apple has been from the TestFlight screen: 
![screen shot 2016-02-10 at 4 01 53 pm](https://cloud.githubusercontent.com/assets/721387/12966044/b792d9b0-d00f-11e5-8933-c1dc56295381.png)

The top one was submitted with Xcode, all the others with fastlane

**Comment by i2amsam** [comment]
@cmds4410 could you post the output of `xcode-select -p`?  I wonder if the commandline tool is using a beta version of xcode.

**Comment by cmds4410** [comment]
@i2amsam Interesting, I hadn't even considered that possibility! I think it looks fine though: `/Applications/Xcode.app/Contents/Developer`

**Comment by cmds4410** [comment]
I could try re-installing Xcode and the command line tools just to be safe

**Comment by ohwutup** [comment]
Hey @cmds4410! Apologies for the lag time here, have you tried this again recently? Are you still having the same issue?

**Comment by cmds4410** [comment]
@ohwutup yep, still having the same issue 😕

**Comment by cmds4410** [comment]
Turns out we had some email issues, and Apple actually did contact us. We're having the "Invalid Swift Support" errors, which looks like it's related to Cocoapods. Sorry about the confusion on my end! Closing this as it is a duplicate of https://github.com/fastlane/fastlane/issues/1860

**Comment by i2amsam** [comment]
:+1: Thanks for the follow up @cmds4410
