### ISSUE TITLE
Frameit - Specify device frame in Framefile.json

### ISSUE THREAD

**Issue by mpdifran** [fastlane/fastlane#12676]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Frameit - Device frame in Framefile.json

#### Question Description
I need to frame one screenshot in a white iOS device, and another in a black iOS device. Currently, I'm framing both screenshots in white, using the first one, then manually editing my Fastfile like so to generate the black one:

    frame_screenshots#(white: true)

This is preventing me from automating my screenshot uploads. Would it be possible to add the device frame colour to the `Framefile.json` like so (or is it currently possible?):

    "data": [
    {
      "filter": "Red",
      "background": "../backgrounds/Red_Background.png",
      "title": {
        "text": "Red"
      },
      "frame": "Black" # Black iOS device
    },
    {
      "filter": "Blue",
      "background": "../backgrounds/Blue_Background.png",
      "title": {
        "text": "Blue"
      },
      "frame": "White" # White iOS device
    }]

**Comment by mpdifran** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :screenshotsAppStore do
	capture_screenshots(skip_open_summary: true)
	frame_screenshots(white: true)
	upload_to_app_store
end

lane :screenshots do
  capture_screenshots(skip_open_summary: true)
  frame_screenshots(white: true)
end

lane :screenshotsdark do
  capture_screenshots(skip_open_summary: true)
  frame_screenshots
end

lane :deliverMetadata do
  upload_to_app_store(skip_screenshots: true)
end

lane :framelight do
  frame_screenshots(white: true)
end

lane :framegold do
  frame_screenshots(gold: true)
end

lane :framedark do
  frame_screenshots
end
```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>


*generated on:* **2018-06-04**
</details>

**Comment by mpdifran** [comment]
The problem is not fixed in the latest version of `fastlane`. I have a pull request open to fix it however.

**Comment by mpdifran** [comment]
The problem is not fixed in the latest version of `fastlane`. I have a pull request open to fix it however.

**Comment by mpdifran** [comment]
There is a PR open for this issue, just waiting on an approval. Please keep this issue open!

**Comment by mpdifran** [comment]
Issue can be closed, as the PR was just merged.

**Comment by janpio** [comment]
I created https://github.com/fastlane/fastlane/pull/14170 to document this functionality. Could you please check if I got it right @mpdifran? Thanks.
