### ISSUE TITLE
Broken installation of fastlane

### ISSUE THREAD

**Issue by jonas-andersson-stratsys** [fastlane/fastlane#1267]
Hi,

I'm quite new to ruby, gems and such but got fastlane installed and setup quite nicely. I then ran into this issue for deliver:

https://github.com/fastlane/deliver/issues/349

I tried to update to the lastest version of fastlane but then ran into this issue:

https://github.com/fastlane/fastlane/issues/567

> ERROR:  While executing gem ... (Errno::EPERM)
>     Operation not permitted - /usr/bin/sigh
> 

I tried the 

```
gem update -n /usr/local/bin fastlane
gem update -n /usr/local/bin sigh
gem update -n /usr/local/bin deliver
```

without success. These only led me to this error:

Unable to activate deliver-1.9.0, because plist-3.2.0 conflicts with plist (~> 3.1.0 ...

I also tried 

```
sudo su
sudo gem install fastlane --verbose
exit
```

Without success. After that I tried to install bundler, a new ruby version and do cleanups and reinstalls. No success. Now everything seems to be in a bad state and trying to install fastlane with the normal command 

` install fastlane --verbose`

leads to 

> You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

Same command with sudo gives:

> /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.6.0/lib/snapshot/version.rb
> ERROR:  While executing gem ... (TypeError)
>     no implicit conversion of nil into String

What to do??

**Comment by xfreebird** [comment]
@jonas-andersson-stratsys How about using [rbenv](http://rbenv.org) or [rvm](https://rvm.io) ?

**Comment by jonas-andersson-stratsys** [comment]
Thanks. Yes, got it working finally using rvm. 

These where the commands I used in total to restore my fastlane installation:

```
brew install gnupg gnupg2
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable --ruby
source /Users/xxx/.rvm/scripts/rvm
gem install fastlane --verbose
xcode-select --install
gem cleanup
gem update -p
rvm reinstall ruby-2.2.3 --with-openssl-dir=/usr/local
gem install fastlane --verbose
```

It also seemed to fix the original problem I had :)

**Comment by i2amsam** [comment]
@jonas-andersson-stratsys thanks for the steps! Since you've got it working now I'm going to close this but please re-open if there is another part I missed.

**Comment by youdy3000** [comment]
@jonas-andersson-stratsys You are the man.  Thanks.  I had exactly the same problem with Fastlane / Snapshot and El Capitan. 

For other people, when you read Jonas' instruction, xxx == your username on the mac.

source /Users/**xxx**/.rvm/scripts/rvm
