### ISSUE TITLE
Continue to get error: I continue to get an error: "Need to acknowledge to Apple's Apple ID and Privacy statement."

### ISSUE THREAD

**Issue by garyhooper** [fastlane/fastlane#12675]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Even though I have accepted the privacy statement, I continue to see the error: "Need to acknowledge to Apple's Apple ID and Privacy statement."

I have logged into appleid.apple.com, itunesconnect.apple.com, and developer.apple.com multiple times from different networks. No statement is presented to acknowledge, yet fastlane continues to produce the error above.

Note that I am running this under Jenkins.  I had logged in several times to the itunesconnect account from various machines. The privacy acceptance was only required once. However, when I logged in as the Jenkins user and accessed itunesconnect again with the same appleid, the privacy acknowledgement was required again (once).  A clue?

Related to #12577?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[12:00:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

DEBUG [2018-06-05 12:00:41.23]: Checking if there are any plugins that should be loaded...
INFO [2018-06-05 12:00:41.33]: ----------------------------------------
INFO [2018-06-05 12:00:41.33]: --- Step: Verifying fastlane version ---
INFO [2018-06-05 12:00:41.33]: ----------------------------------------
INFO [2018-06-05 12:00:41.33]: Your fastlane version 2.97.0 matches the minimum requirement of 2.68.2  ✅
INFO [2018-06-05 12:00:41.33]: ------------------------------
INFO [2018-06-05 12:00:41.33]: --- Step: default_platform ---
INFO [2018-06-05 12:00:41.33]: ------------------------------
INFO [2018-06-05 12:00:41.33]: Driving the lane 'ios getCerts' 🚀
INFO [2018-06-05 12:00:41.33]: --------------------------------------
INFO [2018-06-05 12:00:41.33]: --- Step: Switch to ios certs lane ---
INFO [2018-06-05 12:00:41.33]: --------------------------------------
INFO [2018-06-05 12:00:41.33]: Cruising over to lane 'ios certs' 🚖
INFO [2018-06-05 12:00:41.33]: -------------------
INFO [2018-06-05 12:00:41.33]: --- Step: match ---
INFO [2018-06-05 12:00:41.33]: -------------------
INFO [2018-06-05 12:00:41.40]: Cloning remote git repo...
INFO [2018-06-05 12:00:41.40]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-06-05 12:00:41.40]: $ GIT_TERMINAL_PROMPT=0 git clone 'ssh://git@bitbucket.org/kinghooper/codesigning.git' '/var/folders/hl/jb5p0pr92z7_3_xk5d0dz59r000086/T/d20180605-16579-1cvhjz6'
INFO [2018-06-05 12:00:41.41]: ▸ Cloning into '/var/folders/hl/jb5p0pr92z7_3_xk5d0dz59r000086/T/d20180605-16579-1cvhjz6'...
INFO [2018-06-05 12:00:43.08]: ▸ remote: Counting objects: 78, done.
INFO [2018-06-05 12:00:43.46]: ▸ remote: Compressing objects: 100% (69/69), done.
INFO [2018-06-05 12:00:43.70]: ▸ remote: Total 78 (delta 15), reused 0 (delta 0)
INFO [2018-06-05 12:00:43.70]: ▸ Receiving objects: 100% (78/78), 208.67 KiB | 1.12 MiB/s, done.
INFO [2018-06-05 12:00:43.70]: ▸ Resolving deltas: 100% (15/15), done.
INFO [2018-06-05 12:00:43.75]: 🔓  Decrypted 'U4ZU78KQF2.cer'
INFO [2018-06-05 12:00:43.80]: 🔓  Decrypted 'U4ZU78KQF2.p12'
INFO [2018-06-05 12:00:43.84]: 🔓  Decrypted 'AdHoc_com.domain.xxx-beta.mobileprovision'
INFO [2018-06-05 12:00:43.88]: 🔓  Decrypted 'AdHoc_com.domain.xxx-dev.mobileprovision'
INFO [2018-06-05 12:00:43.92]: 🔓  Decrypted 'AdHoc_com.domain.xxx.mobileprovision'
INFO [2018-06-05 12:00:43.96]: 🔓  Decrypted 'AppStore_com.domain.xxx-beta.mobileprovision'
INFO [2018-06-05 12:00:44.00]: 🔓  Decrypted 'AppStore_com.domain.xxx-dev.mobileprovision'
INFO [2018-06-05 12:00:44.04]: 🔓  Decrypted 'AppStore_com.domain.xxx.mobileprovision'
INFO [2018-06-05 12:00:44.04]: 🔓  Successfully decrypted certificates repo
INFO [2018-06-05 12:00:44.08]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2018-06-05 12:00:44.39]: Lane Context:
INFO [2018-06-05 12:00:44.39]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios getCerts"}
ERROR [2018-06-05 12:00:44.39]: Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement.
INFO [2018-06-05 12:00:44.39]: Successfully generated documentation at path '/Users/Shared/Jenkins/Home/workspace/GlucoZone-iOS/fastlane/README.md'
ERROR [2018-06-05 12:00:44.40]: fastlane finished with errors
</pre>
</details>

**Comment by getaaron** [comment]
I’m totally stumped on this one. What happens if you run the lane locally? Can you try running it with the `--verbose` flag and see if anything interesting prints?

**Comment by garyhooper** [comment]
It fails in every scenario that I try: (1) as a regular user from cmd line; (2) as Jenkins user from cmd line; (3) from Jenkins triggrered build. To check acceptance of privacy statement, I am logging in to itunesconnect from the same machine using the apple_id in my fastlane/Appfile; it displays its normal dashboard.

Verbose output:
<details>
  <pre>ERROR [2018-06-05 15:08:55.12]: fastlane finished with errors
Traceback (most recent call last):
	41: from /usr/local/bin/fastlane:23:in `<main>'
	40: from /usr/local/bin/fastlane:23:in `load'
	39: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/bin/fastlane:20:in `<top (required)>'
	38: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	37: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	36: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	35: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	34: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	33: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	23: from Fastfile:209:in `block (2 levels) in parsing_binding'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	18: from Fastfile:191:in `block (2 levels) in parsing_binding'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/runner.rb:33:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/runner.rb:33:in `new'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/spaceship_ensure.rb:22:in `initialize'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/portal/spaceship.rb:98:in `login'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/client.rb:70:in `login'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/client.rb:362:in `login'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/client.rb:655:in `do_login'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/portal/portal_client.rb:27:in `send_login_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/spaceship/lib/spaceship/client.rb:472:in `send_shared_login_request': [!] The request could not be completed because: (Spaceship::AppleIDAndPrivacyAcknowledgementNeeded)
	Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement.</pre>
</details>

**Comment by garyhooper** [comment]
RESOLVED. All members associated with the team must accept that privacy statement, regardless of which user's account is used to get the certificates.

**Comment by RishabhTayal** [comment]
I am getting this error with one of my Apple developer account. I checked developer.apple.com, appstoreconnect.apple.com, appleid.apple.com. There is no privacy statement popup shown there. I can successfully login on all three sites.

**Comment by garyhooper** [comment]
Whether it was the cause or not, fastlane started working again for me when all members associated with the team had logged in and accepted the privacy statement.

**Comment by RishabhTayal** [comment]
@garyhooper I only have one person in the team.

**Comment by Krumelur** [comment]
Same here. I am the only person and nothing in the portal.
