### ISSUE TITLE
export fails when trying to sign with different bundle id

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#12671]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We need to sign an app with different bundle id for hockey app distribution for enterprise. The default in the project for Relese builds is appstore. Enterprise versions is used for testing and early beta distribution.

I have the following lane 
```
lane :production_hockeyapp do

    # ensure_git_branch(branch: "master")

    scheme = "***REDACTED***"
    output_name = "***REDACTED***-hockeyapp-production.ipa"

    app_id = "com.***REDACTED***"
    signing_profile = "match InHouse #{app_id}"
    distribution_profile = "iPhone Distribution: *Redacted*"
    team_id = "***REDACTED***"

    match(type: "enterprise", app_identifier: app_id, readonly: true, git_branch: match_branch, team_id: team_id)
    gym(
      scheme: scheme,
      workspace: workspace_file,
      configuration: default_configuration,
      output_name: output_name,
      include_bitcode: false,
      include_symbols: true,
      export_method: "enterprise",
      xcargs: {
          :PRODUCT_BUNDLE_IDENTIFIER => app_id, 
          :PROVISIONING_PROFILE_SPECIFIER => signing_profile,
          :DEVELOPMENT_TEAM => team_id
      },
      export_options: {
        provisioningProfiles: {
          app_id => distribution_profile
        },
      }
    )

    push_to_hockey_app(ipa: "#{output_directory}/#{output_name}", api_token: hockey_api_token)
    
  end
```

However the export fails when archive successes and still tries to use appstore for some reason, can you please help how to resolve the issue?

```
[13:28:11]: ▸ Archive Succeeded
[13:28:11]: Generated plist file with the following values:
[13:28:11]: ▸ -----------------------------------------
[13:28:11]: ▸ {
[13:28:11]: ▸   "provisioningProfiles": {
[13:28:11]: ▸     "com.***REDACTED***": "match InHouse ***REDACTED***",
[13:28:11]: ▸     "com.***REDACTED***": "match AppStore ***REDACTED***"
[13:28:11]: ▸   },
[13:28:11]: ▸   "method": "enterprise",
[13:28:11]: ▸   "signingStyle": "manual"
[13:28:11]: ▸ }
[13:28:11]: ▸ -----------------------------------------
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[13:28:11]: ▸ Archive Succeeded
[13:28:11]: Generated plist file with the following values:
[13:28:11]: ▸ -----------------------------------------
[13:28:11]: ▸ {
[13:28:11]: ▸   "provisioningProfiles": {
[13:28:11]: ▸     "com***READACTED****": "match InHouse com***READACTED****",
[13:28:11]: ▸     "com***REDACTED": "match AppStore com***REDACTED"
[13:28:11]: ▸   },
[13:28:11]: ▸   "method": "enterprise",
[13:28:11]: ▸   "signingStyle": "manual"
[13:28:11]: ▸ }
[13:28:11]: ▸ -----------------------------------------
[13:28:11]: $ /usr/bin/xcrun /Users/romk1n/.rvm/gems/ruby-2.4.1/gems/fastlane-2.96.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/pw/vqd3f_w557bgld1lvvv4x4300000gn/T/gym_config20180601-9129-yh92le.plist' -archivePath /Users/romk1n/Library/Developer/Xcode/Archives/2018-06-01/app-hockeyapp-production\ 2018-06-01\ 13.25.33.xcarchive -exportPath '/var/folders/pw/vqd3f_w557bgld1lvvv4x4300000gn/T/gym_output20180601-9129-17ss1ui' PRODUCT_BUNDLE_IDENTIFIER=com***READACTED**** PROVISIONING_PROFILE_SPECIFIER=match\ InHouse\ com***READACTED**** DEVELOPMENT_TEAM=**REDACTED**
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/pw/vqd3f_w557bgld1lvvv4x4300000gn/T/gym_config20180601-9129-yh92le.plist -archivePath '/Users/romk1n/Library/Developer/Xcode/Archives/2018-06-01/app-hockeyapp-production 2018-06-01 13.25.33.xcarchive' -exportPath /var/folders/pw/vqd3f_w557bgld1lvvv4x4300000gn/T/gym_output20180601-9129-17ss1ui PRODUCT_BUNDLE_IDENTIFIER=com***READACTED**** 'PROVISIONING_PROFILE_SPECIFIER=match InHouse com***READACTED****' DEVELOPMENT_TEAM=**REDACTED**
2018-06-01 13:28:12.750 xcodebuild[13557:2251641] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/pw/vqd3f_w557bgld1lvvv4x4300000gn/T/app_2018-06-01_13-28-12.749.xcdistributionlogs'.
2018-06-01 13:28:13.749 xcodebuild[13557:2251641] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7febdcbd9c10>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
"Error Domain=IDEProvisioningErrorDomain Code=10 \"SwiftyJSON.framework does not support provisioning profiles.\" UserInfo={NSLocalizedDescription=SwiftyJSON.framework does not support provisioning profiles., NSLocalizedRecoverySuggestion=SwiftyJSON.framework does not support provisioning profiles, but provisioning profile match InHouse com***READACTED**** has been manually specified. Remove this item from the \"provisioningProfiles\" dictionary in your Export Options property list.}"
)}
error: exportArchive: SwiftyJSON.framework does not support provisioning profiles.

Error Domain=IDEProvisioningErrorDomain Code=10 "SwiftyJSON.framework does not support provisioning profiles." UserInfo={NSLocalizedDescription=SwiftyJSON.framework does not support provisioning profiles., NSLocalizedRecoverySuggestion=SwiftyJSON.framework does not support provisioning profiles, but provisioning profile match InHouse com***READACTED**** has been manually specified. Remove this item from the "provisioningProfiles" dictionary in your Export Options property list.}

** EXPORT FAILED **
[13:28:13]: Exit status: 70</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| addressable               | 2.5.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.3        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| faraday                   | 0.15.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-06-01**
</details></pre>
</details>

**Comment by bguidolim** [comment]
Hi @romk1n 

When you need to switch between Appstore <-> Enterprise, you should change the bundle id of your app.

The best practice is create a new app target and scheme, so you can deal with it easily. But if you need to use the same target, so you'll need to create a combination for your specific case using these actions.

 - [update_app_identifier](https://docs.fastlane.tools/actions/update_app_identifier/)
 - [set_info_plist_value](https://docs.fastlane.tools/actions/set_info_plist_value/)
 - [update_app_group_identifiers](https://docs.fastlane.tools/actions/update_app_group_identifiers/)
 - [update_project_team](https://docs.fastlane.tools/actions/update_project_team/)
 - [disable_automatic_code_signing](https://docs.fastlane.tools/actions/automatic_code_signing/)
