### ISSUE TITLE
`match` failing due to Apple 302 errors

### ISSUE THREAD

**Issue by EdwardDrapkin** [fastlane/fastlane#12683]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Apple 302 error is preventing me from signing packages

##### Complete output when running fastlane, including the stack trace and command used
```
 📒133 🍺 fastlane match adhoc
[✔] 🚀
[13:51:08]: fastlane detected a Gemfile in the current directory
[13:51:08]: however it seems like you don't use `bundle exec`
[13:51:08]: to launch fastlane faster, please use
[13:51:08]:
[13:51:08]: $ bundle exec fastlane match adhoc
[13:51:08]:
[13:51:08]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

jason.ma@flexshopper.com
[13:51:09]: Successfully loaded '/Users/edwarddrapkin/projects/flex-mobile-head/ios/fastlane/Matchfile' 📄

+----------------+--------------------------------------------------------------------------+
|                        Detected Values from './fastlane/Matchfile'                        |
+----------------+--------------------------------------------------------------------------+
| git_url        | X  |
| app_identifier | X                                     |
| username       | X                                          |
+----------------+--------------------------------------------------------------------------+


+-----------------------+--------------------------------------------------------------------------+
|                                     Summary for match 2.97.0                                     |
+-----------------------+--------------------------------------------------------------------------+
| type                  | adhoc                                                                    |
| git_url               | X |
| git_branch            | master                                                                   |
| app_identifier        | X                                              |
| username              | X                                                |
| keychain_name         | login.keychain                                                           |
| readonly              | false                                                                    |
| verbose               | false                                                                    |
| force                 | false                                                                    |
| skip_confirmation     | false                                                                    |
| shallow_clone         | false                                                                    |
| clone_branch_directly | false                                                                    |
| force_for_new_devices | false                                                                    |
| skip_docs             | false                                                                    |
| platform              | ios                                                                      |
+-----------------------+--------------------------------------------------------------------------+

[13:51:09]: Cloning remote git repo...
[13:51:09]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[13:51:12]: 🔓  Successfully decrypted certificates repo
[13:51:12]: Verifying that the certificate and profile are still valid on the Dev Portal...

Looking for related GitHub issues on fastlane/fastlane...

➡️  HipChat Action URI
    https://github.com/fastlane/fastlane/issues/302 [closed] 2 💬
    22 Sep 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Apple 302 detected - this might be temporary server error, check https://developer.apple.com/system-status/ to see if there is a known downtime

```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  desc "Deploying to beta env(Fabric Beta)..."

  desc "Increment patch version number"
  lane :bump_version_patch do
    # Bump version and commit
    ensure_git_status_clean
    increment_build_number
    commit_version_bump(
      message: "iOS Version Bump",
      xcodeproj: "XXX"
    )
  end

  desc "Increment minor version number"
  lane :bump_version_minor do
    increment_version_number(
      bump_type: "minor"
    )
  end

  desc "Increment major version number"
  lane :bump_version_major do
    increment_version_number(
      bump_type: "major"
    )
  end

  desc "Set version number to version_number, argument 'version_number' required"
  lane :bump_version_number do |options|
    increment_version_number(
      version_number: options[:version_number]
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  
  lane :tiresBeta do
    begin
      build_and_push_tires_to_beta()
    rescue => exception
      on_error(exception)
    end
  end

  lane :beta do
    begin
      build_and_push_to_beta()
    rescue => exception
      on_error(exception)
    end
  end
end

def build_and_push_tires_to_beta
  match(type: "adhoc", app_identifier: 'XXX.Tires', verbose: true)

  build_app(
    scheme: "XXXTires",
    output_directory: "./build",
    archive_path: "./archives"
  )

  crashlytics(
    api_token: ENV['CRASHLYTICS_API_TOKEN'],
    build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
    groups: ENV['FABRIC_TESTERS_GROUP_IOS'],
    notes: 'XXX ios beta build released',
    notifications: true
  )

  build_number = get_build_number

  slack(
    message: "XXX new build submitted(iOS)",
    slack_url: ENV['SLACK_CHANNEL_URL'],
    payload: {  # Optional, lets you specify any number of your own Slack attachments.
      "Build Date" => Time.new.to_s,
    },
    default_payloads: [:last_git_commit_hash, :test_result], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
          # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit_message`, `last_git_commit_hash`.
    attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      fields: [
        {
          title: "Build Number: ",
          value: build_number,
        },
        {
          title: "Test groups: ",
          value: ENV['FABRIC_TESTERS_GROUP_IOS'],
        }
      ]
    }
  )
end

def build_and_push_to_beta
  match(type: "adhoc", app_identifier: 'XXXX', verbose: true)

  build_app(
    scheme: "XXX",
    output_directory: "./build",
    archive_path: "./archives"
  )

  crashlytics(
    api_token: ENV['CRASHLYTICS_API_TOKEN'],
    build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
    groups: ENV['FABRIC_TESTERS_GROUP_IOS'],
    notes: 'FlexMobile ios beta build released',
    notifications: true
  )

  build_number = get_build_number

  slack(
    message: "FlexShopper new build submitted(iOS)",
    slack_url: ENV['SLACK_CHANNEL_URL'],
    payload: {  # Optional, lets you specify any number of your own Slack attachments.
      "Build Date" => Time.new.to_s,
    },
    default_payloads: [:last_git_commit_hash, :test_result], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
          # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit_message`, `last_git_commit_hash`.
    attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      fields: [
        {
          title: "Build Number: ",
          value: build_number,
        },
        {
          title: "Test groups: ",
          value: ENV['FABRIC_TESTERS_GROUP_IOS'],
        }
      ]
    }
  )
end

def on_error(exception)
  build_number = get_build_number

  slack(
    message: "XXX new build(iOS) failed with exception : #{exception}",
    success: false,
    slack_url: ENV['SLACK_CHANNEL_URL'],
    payload: {  # Optional, lets you specify any number of your own Slack attachments.
      "Build Date" => Time.new.to_s,
    },
    default_payloads: [:last_git_commit_hash, :test_result], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
          # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit_message`, `last_git_commit_hash`.
    attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      fields: [
        {
          title: "Build Number: ",
          value: build_number,
        },
        {
          title: "Test groups: ",
          value: ENV['FABRIC_TESTERS_GROUP_IOS'],
        }
      ]
    }
  )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "[[APP_IDENTIFIER]]" # The bundle identifier of your app
# apple_id "[[APPLE_ID]]" # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| bundler                   | 1.16.1       |
</details>

*generated on:* **2018-06-04**
</details>

PS `--capture_output` or `--capture-output` are invalid flags so your ticket template should probably be updated.

**Comment by shkn-not-strrd** [comment]
Having this issue as well. Apple's status page showing 
"Certificates, Identifiers & Profiles - Maintenance In Progress"
so hopefully if it's on their end it will be wrapped shortly.

**Comment by mstralka** [comment]
I think this is happening because WWDC is going on right now and they probably disabled this system temporarily.

**Comment by shkn-not-strrd** [comment]
Issue has resolved itself for me, seems it was indeed all Apple.

**Comment by EdwardDrapkin** [comment]
Back to working for me again... does seem to have been on apple's end, so I guess the maintenance page was slow to update with their downtime.  

Can the error message for this specific case be changed to something more friendly?

Old: "Apple 302 detected - this might be temporary server error, check https://developer.apple.com/system-status/ to see if there is a known downtime"

Suggested: 'Invalid response (302) from the Apple certificate server.  If your project has built successfully before, this is probably not a problem with FastLane or your project.  Please check https://developer.apple.com/system-status/ to see if there is a known issue under "Certificates, Identifiers & Profiles."  Note that the status page may take a while to reflect downtime.'
