### ISSUE TITLE
ERROR ITMS-90129: "The bundle uses a bundle name or display name that is already taken

### ISSUE THREAD

**Issue by Aravindios** [fastlane/fastlane#12680]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> iTunes Transporter output above ^
[18:02:44]: ERROR ITMS-90129: "The bundle uses a bundle name or display name that is already taken."
Return status of iTunes Transporter was 1: ERROR ITMS-90129: "The bundle uses a bundle name or display name that is already taken."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.</pre>
</details>

### Environment

<details>
  <pre> ERROR ITMS-90129: "The bundle uses a bundle name or display name that is already taken."
Return status of iTunes Transporter was 1: ERROR ITMS-90129: "The bundle uses a bundle name or display name that is already taken."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure</pre>
</details>

**Comment by RishabhTayal** [comment]
@Aravindios This error is thrown by Apple iTunes Connect. The app name you are trying to use is already taken by someone else. You need to choose another app name that is not already taken. This is not a fastlane issue.
