### ISSUE TITLE
[snapshot] Add parameter to not use headless simulator

### ISSUE THREAD

**Issue by mmysliwiec** [fastlane/fastlane#12682]
#### Motivation Behind Feature
Xcode 9 introduced headless mode for UI testing. It's used by default when no simulator is running. But Snapshot is killing simulator by default to fix some issues (https://github.com/fastlane/fastlane/issues/2533). Unfortunately, this will always use headless simulator while taking screenshots. It's an issue in rare circumstances when headless simulator behaves differently than UI simulator. One blocker for me is when screenshot relly on geolocation. The headless simulator ignores settings for location (Debug->Location->Custom Location). This is a huge problem because all screenshots with maps show my country silhouette instead of my simulated location.

#### Feature Description
New Snapshot configuration parameter should be added (e.g. "headless") with the default value of true. Default parameter would kill simulator as it is now so no changes for current scenarios. When set to false it should reopen simulator with 'open "/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"' equivalent after applying all fixes.

#### Alternatives or Workarounds
One workaround is to manually launch simulator after Snapshot is killing it. Then the headless mode is off and Snapshot is launching UI test on the opened simulator. The geolocation is configured properly then. The problem is when we have more than one device inside devices list. The simulator is killed before each device is picked to make screenshots. So I could manually monitor the situation and relaunch the simulator each time Snapshot kills it but it's useless for automating the process.

**Comment by Leeds-eBooks** [comment]
This is still an issue. Is it impossible to fix, or just not high priority?

**Comment by mmysliwiec** [comment]
It's still an issue for me and anyone who want to make screenshots with specific geo-location showing user position on the map. I guess it's not high priority enough 😢.

**Comment by Leeds-eBooks** [comment]
My use case is different, but it's the same cause – I'm using React Native, and it appears that nothing renders in a headless simulator, so all of my "tests" (which snapshot uses to take screenshots) fail.

**Comment by Leeds-eBooks** [comment]
A **very** hacky workaround I've just used is to set a trigger in iTerm2 that alerts me to open the simulator manually whenever the fastlane output shows the test is about to run...!

**Comment by m-ruhl** [comment]
We have the same issue: Our UI-Tests and Snapshot-Tests require a geo-location to function properly..

These workarounds would only work local, not on a CI environment

**Comment by janpio** [comment]
Hey @mmysliwiec and @m-ruhl, so your issue is that setting geo location with headless simulators does not work? Adding an option to not use headless simulators would solve that problem?

And @Leeds-eBooks, could you please open a new issue for your actual problem so it can be properly debugged? But your solution would also be to not use a headless simulator?

I think we are absolutely open for a PR for the `snapshot`/`capture_ios_screenshots` action. Does anyone of you know how one can control if a headless or "normal" simulator is used?

For reference to anyone who wants to tackle this:
Simulators are launched here: https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
Command used to start simulators are generated here: https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/test_command_generator.rb

**Comment by m-ruhl** [comment]
@janpio Yes it does not work with a headless simulator.
How can you start the simulator from cmd-line not headless, so I can verify it?

**Comment by mmysliwiec** [comment]
@janpio If there is Simulator.app opened before running tests then execution of those tests will be visible within the simulator (no headless). When there is no simulator launched then all tests will use headless mode. The issue with `snapshot` is that it's always killing Simulator.app before making screenshots for a given device due to fixing some issues with resolution. Because of this running `snapshot` in no-headless mode is not possible.

**Comment by janpio** [comment]
For reference:
https://github.com/fastlane/fastlane/blob/514a8c782fc465fbb1397fac64d4886d5e2181c6/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb#L49-L52
