### ISSUE TITLE
projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.

### ISSUE THREAD

**Issue by R4ein** [fastlane/fastlane#12698]
### New Issue Checklist

- [x] Updated fastlane to the latest version: 2.97.0
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

https://github.com/fastlane/fastlane/issues/12596 — Problem is not solved
https://github.com/fastlane/fastlane/issues/5283 — Problem is not solved

### Issue Description

Hello,

I am trying to setup CI process for automated APK builds. However, I am facing an issue that might be related to Google Play Developer Publishing API. The problem shows up when I try to upload new APK to Google Play using Fastlane instruments, or even `fastlane supply init`. 

```
/var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/api_command.rb:109:in `check_status': projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.
```

Problem also occurs regardless of whether I pre-create application project in Google Play Developer account, or not.

I did everything according to https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials , got my JSON file, and I'm getting the error above every time I'm trying to use my JSON key with Fastlane. I already tried to re-create Service Account, amd tried to give it 'Owner' permissions just to exclude permissions issue. Also, yes, my project is linked with Google Play Developer Account, it is listed in 'API Access' as 'Connected', and also Service Account is listed below is active. I have also checked JSON file, its project id equals to what I see in Google Developer console. I did even create a separate Google Play Developer account and payed $25 fee just to check if there's a problem with my Google account or I am limited to use API.

So, basically, my project from Google API _is_ linked to Google Play Developer Console, but, for some unknown reason, Fastlane thinks that there's no connection, and API and my Developer account are not linked.

Any ideas what did I do wrong? Or might that not be related to Fastlane, but to Google API and its access?

How can I check that JSON file used with Fastlane is correct and I'm able to access API with it?

Also, I am running my build container inside Docker 1.13.1, and Kubernetes cluster 1.9.6. I tried to build it on host VPS, without using Docker, faced the same issue.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre># fastlane supply init

[⠙] 🚀 /var/lib/gems/2.1.0/gems/fastimage-2.1.3/lib/fastimage.rb:68: warning: already initialized constant URI::DEFAULT_PARSER
/usr/lib/ruby/2.1.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[✔] 🚀
[09:57:27]: To not be asked about this value, you can specify it using 'package_name'
[09:57:27]: The package name of the application to use: com.ci-test

Looking for related GitHub issues on fastlane/fastlane...

➡️  Error in Uploading Android apk to Google play store Using Fastlane
    https://github.com/fastlane/fastlane/issues/12596 [open] 3 💬
    5 days ago

➡️  projectNotLinked Issue
    https://github.com/fastlane/fastlane/issues/5283 [closed] 6 💬
    06 Dec 2016

/var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/api_command.rb:109:in `check_status': [!] projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console. (Google::Apis::ProjectNotLinkedError)
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:183:in `process_response'
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:299:in `execute_once'
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
        from /var/lib/gems/2.1.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
        from /var/lib/gems/2.1.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
        from /var/lib/gems/2.1.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:101:in `block in execute'
        from /var/lib/gems/2.1.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
        from /var/lib/gems/2.1.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
        from /var/lib/gems/2.1.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/http_command.rb:93:in `execute'
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
        from /var/lib/gems/2.1.0/gems/google-api-client-0.21.2/generated/google/apis/androidpublisher_v2/service.rb:200:in `insert_edit'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/client.rb:92:in `block in begin_edit'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/client.rb:387:in `call_google_api'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/client.rb:92:in `begin_edit'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/setup.rb:9:in `perform_download'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/commands_generator.rb:59:in `run'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/supply/lib/supply/commands_generator.rb:12:in `start'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
        from /var/lib/gems/2.1.0/gems/fastlane-2.97.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | debian_based 8.10                                        |
| Ruby                        | 2.1.5                                                    |
| Bundler?                    | false                                                    |
| Git                         | git version 2.1.4                                        |
| Installation Source         | /usr/local/bin/fastlane                                  |
| Host                        | Debian GNU/Linux 8 debian_based 8.10 (4.13.0-43-generic) |
| Ruby Lib Dir                | /usr/lib                                                 |
| OpenSSL Version             | OpenSSL 1.0.1t  3 May 2016                               |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play beta track"
  lane :beta do
    gradle(task: "assembleRelease")
    upload_to_play_store(track: 'beta')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play prod track"
  lane :production do
    gradle(task: "assembleRelease")
    upload_to_play_store(track: 'production')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/usr/src/app/android/gpad.json")
#package_name("com.ci-test")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.2        |
| unf                       | 0.2.0.beta2  |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-06-06**</pre>
</details>

**Comment by DanielCasadoCrisalix** [comment]
I have exactly the same Issue here!..

**Comment by evaleirasclapps** [comment]
I have exactly the same issue here!

**Comment by joshdholtz** [comment]
Does your Google Play dashboard show stuff like this?

## API access
![screen shot 2018-07-03 at 8 36 41 am](https://user-images.githubusercontent.com/401294/42223088-88f153be-7e9c-11e8-863f-c2ace5e79397.png)

## Users & permissions
![screen shot 2018-07-03 at 8 38 40 am](https://user-images.githubusercontent.com/401294/42223089-89055738-7e9c-11e8-97cb-f9c2487ea893.png)

**Comment by Zhuinden** [comment]
@joshdholtz where did you even find those menus?

**Comment by aBuder** [comment]
I habe also these issue

**Comment by nokite** [comment]
I also have this issue. It started happening after they updated the Google API console (might be coincidence).
It might be a problem on Google's side, not Fastlane's, though.

**Comment by VietUngIT** [comment]
I have exactly the same issue here!and i'm using test inapp purchase

**Comment by VietUngIT** [comment]
I have exactly the same issue. but i have resolved . [request]: - you must link project Google Play Developer Console before you create inapp purchase

**Comment by aBuder** [comment]
I also fixed the problem. I created an ne key.json on google developer console and also set new access in google pay store and it works :-)

**Comment by rahul70422** [comment]
I have exactly the same issue. I have tried each and everything but not able to resolve this issue. can anyone please help me to resolve this issue?

**Comment by ahmadmssm** [comment]
@rahul70422 + 1

**Comment by RyanHow** [comment]
+1

**Comment by janpio** [comment]
@rahul70422 @ahmadmssm No. Also this is very off topic for this issue here. Please create new issues for unrelated problems or questions. Thanks.

**Comment by vinothpsv** [comment]
am able to connect with the Google server https://vinothpsv.blogspot.com/2018/11/gplay-billing-subscription-with-real.html

**Comment by Maxwell2022** [comment]
Same issue here, I followed every single steps and double check everything. Still have this error message showing up :/
