### ISSUE TITLE
Any way to extract tests results without looking at the generated reports ?

### ISSUE THREAD

**Issue by srikanth-vm** [fastlane/fastlane#12694]
We are not using slack and I was looking for a cleaner way to post test results and code coverage to our chat. 

```
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 1 |
| Number of failures | 0 |
+--------------------+---+
```

Is there any way to fetch output as above to post them else where ?

**Comment by getaaron** [comment]
The `run_tests` (aka `scan`) action has an `output_directory` param for reports. See also the other params beginning with `output_` to configure the type of report you want. https://docs.fastlane.tools/actions/scan/

Once you have the report file you can upload it somewhere depending on your CI software support or what you have available locally. For example on CircleCI you can use the `store-test-results` step to upload a report file.

**Comment by srikanth-vm** [comment]
Hey @getaaron ! thanks for looking at this. As of now I have configured to spit out HTML reports, but I was looking for a way to get just that summary out so that I could ping on our chat rooms. I have put it a workaround by reading files, but thought that there might be a better way to do. Any ideas ?
