### ISSUE TITLE
Upload Dsym to hockey

### ISSUE THREAD

**Issue by sprabhuanand** [fastlane/fastlane#12695]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to upload the dsym file to hockey but am getting this error message

[09:55:53]: Error when trying to upload file(s) to HockeyApp: 404 - {"errors"=>{"app"=>["not found"]}}

Here is my config that am using
    hockey(api_token: "abcdefghijklmnopqrstuvwxyz",
    notes: notes,
    notes_type: "1",
    upload_dsym_only: true,
    public_identifier: "123456789", (app_id from the itunes url and also used bundle id)
    dsym: "ABC.app.dSYM.zip",
    dsa_signature: "",
    commit_sha: commit_sha)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

[09:55:49]: Successfully exported and compressed dSYM file
[09:55:49]: Successfully exported and signed the ipa file:
[09:55:49]: /Users/Shared/Jenkins/Home/workspace/ios-build/ABC.ipa
[09:55:49]: --------------------
[09:55:49]: --- Step: hockey ---
[09:55:49]: --------------------
[09:55:49]: Starting with dSYM upload to HockeyApp... this could take some time.
+--------------------+--------------------------------------+
|                       Lane Context                        |
+--------------------+--------------------------------------+
| DEFAULT_PLATFORM   | ios                                  |
| PLATFORM_NAME      | ios                                  |
| LANE_NAME          | ios beta                             |
| VERSION_NUMBER     | 2.11                                 |
| BUILD_NUMBER       | 125                                  |
+--------------------+--------------------------------------+
[09:55:53]: Error when trying to upload file(s) to HockeyApp: 404 - {"errors"=>{"app"=>["not found"]}}

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 0           |
| 2    | default_platform       | 0           |
| 3    | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 4    | cd ../;git log         | 0           |
|      | --pretty=format:'%s    |             |
|      | %h' | grep -i          |             |
|      | '^version bu           |             |
| 5    | git rev-parse HEAD     | 0           |
| 6    | increment_build_numbe  | 1           |
|      | r                      |             |
| 7    | gym                    | 225         |
| 💥   | hockey                 | 3           |
+------+------------------------+-------------+

[09:55:53]: fastlane finished with errors
</pre>
</details>

### Environment
<details>
  <pre>
MacPros-Mac-Pro:tmp jenkins$ fastlane env
[✔] 🚀
[12:12:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:12:44]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.16.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.96.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-06-05**
</pre>
</details>

**Comment by andrew-nemtsev** [comment]
The same issue with fastalne 2.100.1 and hockey:

`Starting with dSYM upload to HockeyApp... this could take some time.
/Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error when trying to upload file(s) to HockeyApp: 404 -   (FastlaneCore::Interface::FastlaneError)
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/hockey.rb:180:in `run'
..........`

Observed for dSYM uploading started by this command from terminal:
fastlane run hockey api_token:"12345DEADBEEF" dsym:"./Application.app.dSYM.zip" public_identifier:"com.domain.applicatoin" upload_dsym_only:true status:1 --verbose

**Comment by m1entus** [comment]
Same issue for 2.100.1 and hockey:

    FastlaneCore::Interface::FastlaneError: [31m[!] Error when trying to upload file(s) to HockeyApp: 404 -  [0m
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/hockey.rb:180:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'

**Comment by WiesnerPeti** [comment]
@sprabhuanand @m1entus Have you checked if the user that generated the Hockey App API Token has access to the app you want to upload the ipa/dsym for? The backtrace was misleading for me, it showed error on the Fastlane error logging method like it had not be required in hockey.rb. The actual error is that HockeyApp API Token does not have access to the app.

**Comment by andrew-nemtsev** [comment]
@WiesnerPeti  the same API token works fine - checked with cli
