### ISSUE TITLE
Fastlane Pilot stucks on '... dosent show up in build list'

### ISSUE THREAD

**Issue by d4ex** [fastlane/fastlane#12704]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have the following problem:
- Our build stucks on **'Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)'**
- I recieve a mail from apple that the build processing was successful
- **_If i go to the apple store connect website and click on "Testflight" to show my iOS builds the "Build dosen't show up..." Message goes immediately a way and fastlane recognize that the build is already processed._** and my jenkins task finish successful.

This behavior is reproducible

**Comment by tonyzp** [comment]
I meet this issue too !

**Comment by goingreen** [comment]
+1

**Comment by stonedauwg** [comment]
+1

**Comment by taisukeh** [comment]
+1

**Comment by insanity13** [comment]
+1

**Comment by lexd5** [comment]
+1

**Comment by Kazinaki** [comment]
+1

**Comment by saragulov** [comment]
+1

**Comment by Demmy27** [comment]
+1

**Comment by DavidWiesner** [comment]
+1
When I manually login into https://appstoreconnect.apple.com and navigate to the app and than to "TestFlight" the app will be distributed and fastlane immediately will stop waiting and finish the build

**Comment by garyjohnson** [comment]
@DavidWiesner I'm seeing the same issue. My TestFlights builds started getting stuck and a visit to the "TestFlight" tab in the app on App Store Connect will immediately trigger the app release.

**Comment by paladocy** [comment]
+1
I'm experiencing the same issue. Visiting TestFlight seems to immediately release the version to testers.

**Comment by thijsonline** [comment]
+1
Another workaround to trigger the app release is to execute `fastlane pilot builds`

**Comment by thorstenschiffer** [comment]
Same problem here, I get an email that the processing is done but pilot is stuck

**Comment by timoa** [comment]
+1

**Comment by viamatt** [comment]
+1

**Comment by vincentkjj** [comment]
+1

**Comment by cooksimo** [comment]
This is happening for me too, and today logging in didn't fix it either. It triggered TestFlight to distribute the build but fastlane still thinks the build is missing

**Comment by FouadAstitou** [comment]
+1

**Comment by Jerrot** [comment]
+1
visiting the TestFlight tab on Appstore Connect triggered the build to re-appear for fastlane.

**Comment by joshdholtz** [comment]
Will look into 👀

**Comment by mhemmings** [comment]
I'm seeing this happen too, _however_ I have seen it happen in the past with builds manually (i.e via Xcode not fastlane) uploaded to iTunes, so points at some madness happening inside iTunes?
