### ISSUE TITLE
for_lane in AppFile does not work for sub-lanes

### ISSUE THREAD

**Issue by eskerber** [fastlane/fastlane#1270]
If I have a lane:

```ruby
lane :mainline do
   # stuff
   store
   # stuff
end

private_lane :store do
  CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) 
end
```

And my Appfile reads:

```ruby
app_identifier "com.foo.Bar"

for_lane :store do
  app_identifier "com.fizz.Buzz"
end
```

Then the credentials manager will return `com.foo.Bar` instead of `com.fizz.Buzz`. It seems as though for_lane will only apply to the top-most lane.

Is this intentional? We have lanes that build for enterprise + app store, so the hard work is done by sublanes so :point_up: would be really awesome to have work.

Thanks!

**Comment by KrauseFx** [comment]
Yah, that's by design, the `Appfile` is loaded at the point when you trigger a lane, so the lane you actually trigger (`mainline` in your case) is chosen. Should the documentation be more clear? I'm more than happy to merge a PR improving this :+1:
