### ISSUE TITLE
gym ignores Dir.chdir

### ISSUE THREAD

**Issue by the4thfloor** [fastlane/fastlane#12707]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I change the working directory with `Dir.chdir` but `gym` can't find the workspace file :-(
After `Dir.chdir` I added `sh("pwd")` and it prints the right directory path like:
```
[11:46:54]: $ pwd
[11:46:54]: ▸ /Users/ralphbergmann/development/flutter/foo/store
```
But `gym` fails with:
```
[11:47:38]: Workspace file not found at path '/Users/ralphbergmann/development/flutter/foo/ios/Runner.xcworkspace'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.1 (Apple Git-101)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.33.0"


platform :flutter do


    lane :alphaBuild do

        # Return the number of commits in current git branch
        build_number = number_of_commits()


        Dir.chdir "../core" do
            sh("pwd")
            sh("flutter", "packages", "get")
            sh("flutter", "clean")
        end

        Dir.chdir "../store" do

            sh("pwd")
            sh("flutter", "packages", "get")
            sh("flutter", "clean")
            sh("flutter", "build", "ios", "--release", "--no-codesign", "--build-number=#{build_number}")

            # Easily sync your certificates and profiles across your team using git
            match(
                type: "enterprise",
                team_id: "foobar",
                git_branch: "foobar",
                app_identifier: "foobar"
            )

            # Easily build and sign your app using gym
            gym(
                workspace: "ios/Runner.xcworkspace",
                scheme: "Jenkins",
                silent: true,
                clean: true,
                configuration: "Release",
                export_method: 'enterprise'
            )

        end

    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "bergmann@foobar.com" # Your Apple email address

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.6        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-06-07**
</details>

**Comment by the4thfloor** [comment]
It looks the `apk` option of the `hockey` command ignores `Dir.chdir` too. 

`hockey` fails with:
```
[12:04:27]: Couldn't find apk file at path 'build/app/outputs/apk/app.apk'
```

**Comment by johnknapprs** [comment]
https://docs.fastlane.tools/advanced/#directory-behavior
