### ISSUE TITLE
app_store_build_number

### ISSUE THREAD

**Issue by invoodoo** [fastlane/fastlane#12714]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When it is an initial build and not app in AppStore yet, command: app_store_build_number(version: app_version, live: true) throw an error **undefined method `current_build_number' for nil:NilClass**

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:32:in `get_build_number': [!] undefined method `current_build_number' for nil:NilClass (NoMethodError)
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:11:in `run'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from /Users/InVooDoo/Library/Mobile Documents/com~apple~CloudDocs/iWork/Misc/actions.rb:133:in `build_number'
	from /Users/InVooDoo/Library/Mobile Documents/com~apple~CloudDocs/iWork/Misc/actions.rb:121:in `update_version'
	from Fastfile:55:in `block (2 levels) in parsing_binding'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/InVooDoo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/bin/fastlane:20:in `<top (required)>'
	from /Users/InVooDoo/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/InVooDoo/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.13.5                                                 |
| Ruby                        | 2.2.4                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.15.1 (Apple Git-101)                      |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                     |
| Host                        | Mac OS X 10.13.5 (17F77)                                |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Development/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

require 'spaceship'
require_relative '/Users/InVooDoo/Library/Mobile Documents/com~apple~CloudDocs/iWork/Misc/actions'

$apple_id = ""
$git_branch = "master"
$team_id = "D3U5A76CF4"
$itc_team_id = "119123964"

$bundle_ids = ["com.pmc.app", "com.pmc.app.staging", "com.pmc.testing"]
$info_plists = ["PMC/Production.plist", "PMC/Staging.plist", "PMC/Testing.plist"]
$schemes = ["Production", "Staging", "Testing"]
$targets = $schemes

$bundle_id = $bundle_ids[0]

$types = ["prod", "staging", "testing"]

$project_path = "PMC.xcodeproj"
$app_name = "PMC"

$signing_identity = ""

before_all do |lane, options|
    ENV["APP_IDENTIFIER"] = $bundle_id
end

platform :ios do
    lane :tf do |options|
        clean = options[:clean]
        server = options[:server]

        if server == "production"
            idx = 0
        elsif server == "staging"
            idx = 1
        else
            idx = 2
        end

        puts "-----------------------------------------"
        puts "-----  Scheme: #{$schemes[idx]}"
        puts "-----------------------------------------"

        if (clean.nil?) || (clean)
#            reset_git_repo(force: true)
        end

        ensure_git_branch(branch: $git_branch)

        git_pull

        cocoapods
        update_version

        ENV["APP_IDENTIFIER"] = $bundle_ids[idx]

        make_build($schemes[idx], $info_plists[idx], $types[idx])
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.pmc.app") # The bundle identifier of your app
apple_id("") # Your Apple email address

itc_team_id("119123964") # iTunes Connect Team ID
team_id("D3U5A76CF4") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| simctl                    | 1.6.4        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.3        |
</details>

*generated on:* **2018-06-07**
</details></pre>
</details>

**Comment by invoodoo** [comment]
it is related to newly created version and usage of app_store_build_number funciton

**Comment by joshdholtz** [comment]
@invoodoo I will fix the code to handle this more gracefully but it looks like this is happening because there is no "live" version of the app that you are looking for 🤔 I am able to replicate with an app that is in iTunesConnect (I guess now App Store Connect) that hasn't officially be approved and released yet. Can you verify the state of approval of your app with me?

**Comment by invoodoo** [comment]
Awesome if it could give a nil or something else so I can manager situation and still make a build.

I fetch version and build number from AppStore and checking live or edit version. And if there is no live it crashes :(

**Comment by joshdholtz** [comment]
@invoodoo You could do something like `app_store_build_number() rescue nil` to stop it from crashing 😊
