### ISSUE TITLE
Couldn't find any new signed apk files.

### ISSUE THREAD

**Issue by Abgaryan** [fastlane/fastlane#12728]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
Going to close this issue since no issue information, `fastlane env`, or _fastlane_ output was provided. Please open another issue with all requested information and I will be happy to look into 😊
