### ISSUE TITLE
Fastfile: gym and pilot

### ISSUE THREAD

**Issue by carlosefonseca** [fastlane/fastlane#1272]
I'm having a bit of a trouble with Fastfile. I have this issue that if I run a lane like
```
appid='com.example.xyz'
gym(scheme: "Some scheme")
pilot(app_identifier:appid)
```
and there's another ipa `abc.ipa` on the folder, pilot seems to load that other file and not the file `gym` created. This seems weird, I though `gym` set the path to the generated ipa to some var and `pilot` would pick that up and use that.

I think this might be solved by doing something like

```
appid='com.example.xyz'
ipa = gym(scheme: "Some scheme")
pilot(app_identifier:appid, ipa:ipa)
```
but seems like it shouldn't be needed. Also, deleting the other `ipa` file seems to work too.

When pilot runs, it doesn't print out the path to the `ipa` file in use, and neither does iTunesTransporter, but looking into the `.itms` package I saw a different `ipa`, and iTunesConnect complained with 

`ERROR ITMS-90054: "This bundle is invalid. The bundle identifier cannot be changed from the previous version. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect.`

I'll try to figure this out better soon…

**Comment by ohwutup** [comment]
Thanks for the issue @carlosefonseca, if this is still an issue for you, would you mind opening a new one in the `pilot` repo here: https://github.com/fastlane/pilot.

I'm going to close this comment for now and we can track work over there.

Thanks!
