### ISSUE TITLE
Can't decrypt fastlane match repository using an Enterprise account

### ISSUE THREAD

**Issue by nneuberger1** [fastlane/fastlane#12722]
We're having issues with decrypting the fastlane match repository due to unexpected issues.  We're in a lost password state BUT we're using the Apple Enterprise option (not a standard account).  When running our builds we have the following error (via Bamboo CI) usage:

We we're using keychain usage.

Here are some of the errors:
"Couldn't decrypt the repo, please make sure you enter the right password!"

and:

[11:45:57]: Invalid password passed via 'MATCH_PASSWORD'

If it's easier to do something 'nuke' like I will do it. BUT the last thing I want to do is do any nuke option and deleting our current Production Enterprise Certificates on our app store.

What is the recommend approach to dealing with this?

Can I just delete my internal git repository and run an init and fastlane match / gym will just pull everything down again from the our apple enterprise account from their website?

I remember some mention of the type 'enterprise' option where the nuke option.  I believe so Production Certificates we're never expired in the app store.

I'm looking for all options to ensure our certificates are good and we can build again using fastlane OR the option on the table could be just removing fastlane and/or the match process.

### Environment

+-----------------------+---------------------------------------------------------------+
|                               Summary for match 2.96.0                                \|
| +-----------------------+---------------------------------------------------------------+
| \| type                  \| enterprise                                                    \|
| \| git_url               \| ssh://git@stash.asdf.com:7999/myrepo/fastlanematch.git        \|
| \| git_branch            \| master                                                        \|
| \| app_identifier        \| ["com.asdf"]                                                  \|
| \| username              \| email@asdf.com                                                \|
| \| keychain_name         \| login.keychain                                                \|
| \| readonly              \| false                                                         \|
| \| team_id               \| 123456789                                                     \|
| \| verbose               \| false                                                         \|
| \| force                 \| false                                                         \|
| \| skip_confirmation     \| false                                                         \|
| \| shallow_clone         \| false                                                         \|
| \| clone_branch_directly \| false                                                         \|
| \| force_for_new_devices \| false                                                         \|
| \| skip_docs             \| false                                                         \|
| \| platform              \| ios                                                           \|
| +-----------------------+---------------------------------------------------------------+

**Comment by nneuberger1** [comment]
My initial thought is to just init a brand new repository and new password and allow fastlane to pull everything down again, but I don't know exactly what it will do during the process.

**Comment by nneuberger1** [comment]
Here's another error occuring on our build boxes that we think may help triage the issue.

'password has been deleted.'

Here's the full output just running a simple command:  "fastlane match development"

[11:35:04]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[11:35:04]: This passphrase is specific per repository and will be stored in your local keychain
[11:35:04]: Make sure to remember the password, as you'll need it when you run match on a different machine
[11:35:04]: Passphrase for Git Repo: **********
[11:35:28]: Type passphrase again: **********
[11:35:29]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/bamboo/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_ssh://git@stash.asdf.com:7999/asdf/fastlanematch.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303630383136333532395A00  "20180608163529Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303630383136333532395A00  "20180608163529Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_ssh://git@stash.asdf.com:7999/asdf/fastlanematch.git"
    "type"<uint32>=<NULL>
password has been deleted.

**Comment by nneuberger1** [comment]
Bump.  Any ideas on this?   Is it just as simple as creating a new git repository locally "init"? and then allowing fastlane to recreate it?

I'm really needing some expert guidance I may just need to not use fastlane, OR at least the gym aspect of it.

if it helps here's some of the Fastfile configuration:

`
fastlane_version "2.51.0"

xcversion(version: "~> 8.3.0") # Selects the latest installed version from the 8.3.x set

default_platform :ios


desc "Deploy a new version to the App Store"
  lane :release do
    incrementBuildVersion()

    match(type: "enterprise")
    gym(scheme: "Kiosk")

    # deliver(force: true)
    # frameit
  end
`

**Comment by joshdholtz** [comment]
@nneuberger1 Heyyy 👋 How long ago was your _match_ repo created? And what version of open ssl do you have installed? Open ssl changed their default algorithm from MD5 to SHA256 when bumping from 1.0 to 1.1. fastlane _should_ handle this for you (see https://github.com/fastlane/fastlane/blob/master/match/lib/match/encrypt.rb#L84-L130) but maybe there is an issue going on with that 🤔 

If you could let me know the answers to the above I will be able to look into further ✊

**Comment by nneuberger1** [comment]
@joshdholtz I created the original repository Aug 1, 2017 and has been updated via fastlane through May 28, 2018.

If it helps, a developer accidentally changed one of the "match" provisioning profiles via the Developer Portal and broke things because of that.

**Comment by joshdholtz** [comment]
@nneuberger1 Ah okay, so it most likely sounds like its _not_ an issue with the OpenSSL 👌 

If an developer accidentally delete changed one of the match provisioning profiles it shouldn't have caused a "couldn't decrypt repo" error unless that file was manually committed back to the repo in an unencrypted state. 

I wouldn't suggest using fastlane's "nuke" option as it also 💣s the certificates (which I am assuming you don't want to revoke because it will stop all apps from working that were made with that certificate). If this is the case, I would suggest manually deleting the profiles from the match git repo (as fastlane can re-pull those down) but just make sure to keep those certificates.

If the currently issue cert that was signed with the apps doesn't matter to you for some reason, its probably alright to run nuke 😊 

Hope this helps!
