### ISSUE TITLE
upload_to_play_store(track: 'beta') sent APK to production

### ISSUE THREAD

**Issue by nthegedus** [fastlane/fastlane#12733]
Here is my lane, that I'm using:
  <pre>lane :betaStore do
    bump_version_code
    gradle(task: 'clean', project_dir: "./") 
    gradle(
      task: "assemble",
      build_type: "Release",
      flavor: "prod",
      system_properties: {
        "ENVFILE": ".env.prod"
      },
      project_dir: "./"
    )
    upload_to_play_store(track: 'beta')
  end</pre>

It used to work very well until last month, because I've tried today and it has sent the APK to production instead of Beta.

Does any one can figure out what happened?

**Comment by joshdholtz** [comment]
@nthegedus This is really strange 🤔 My `track: 'beta'` does straight to the Beta track like it should. Can you please provide `fastlane env` and output of you terminal (using `--verbose`) like the issue template suggests so I have more information to go? 😊
