### ISSUE TITLE
Add callback before waiting for done uploading, but waiting for processing

### ISSUE THREAD

**Issue by KjellConnelly** [fastlane/fastlane#12738]
### Feature Request
I haven't used gotten around to uploading to app store yet, and am still focusing on uploading to Testflight, but this feature could work for both: Add a callback so that once a build has been created and uploaded to the appropriate server, we can run some custom code of our own.

#### Motivation Behind Feature
I have a pipeline where I have 6 different apps that all share code. So when I want to submit updates for all these apps, I want to do it as streamlined as possible. This means that as soon as one has been built and submitted, I want to be able to start building the next app. Sure, I could disable waiting. But I do want the app to be distributed to testers for Testflight (and whatever happens when uploading to the App Store). Personally, I would have a new bash script run... open a new tab, start building the next one, etc...

#### Feature Description
I believe that changes would need to be made in: ```fastlane/pilot/lib/pilot/build_manager.rb```
I don't know Ruby, but in pseudocode it would look something like:
```
UI.success("Successfully uploaded the new binary to iTunes Connect")
if [:config.onSuccessfulUpload]
    onSuccessfulUpload()
end
```
There shouldn't be any drawbacks as this just opens up a new option for others. By default, ```onSuccessfulUpload``` would be undefined or null or whatever a blank value is.

#### Alternatives or Workarounds
The alternative I know of is to just write a script that has to wait for iTunes to finish processing and for Fastlane to distribute before starting the next build. Though this would work, it isn't as time efficient.

I do not know if there are other ways around this, but I do not see any parameters for upload_to_testflight that indicate an alternative.

#### fastlane env output (changed my team_id and apple_id to PRIVATE):
```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.107.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

# fastlane kjelltest --env Diary
  desc "Kjell's Test"
  lane :kjelltest do
    puts "Hello"
    puts ENV['ENV_SCHEME'] + " " + ENV['ENV_BUNDLE_IDENTIFIER']
  end

  desc "Create screenshots test"
  lane :kjelltest2 do
    fastlane frameit
    puts "Success"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  #this is the script I am working on from scratch.
  # fastlane beta2 --env Diary
  lane :beta2 do
    build_app(
      scheme: ENV['ENV_SCHEME'],
      export_xcargs: "-allowProvisioningUpdates"
    )
    #increment_build_number()
    increment_build_number_in_plist(scheme: ENV['ENV_SCHEME'])
    upload_to_testflight
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Diary") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Diary") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier ENV['ENV_BUNDLE_IDENTIFIER'] # The bundle identifier of your app
apple_id "PRIVATE" # Your Apple email address

team_id "PRIVATE"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.94.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.1.0        |
| slack-notifier             | 2.3.2        |
| atomos                     | 0.1.2        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.5        |
| xcodeproj                  | 1.5.7        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| terminal-notifier          | 1.8.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.4.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.6.4        |
| tty-cursor                 | 0.5.0        |
| tty-spinner                | 0.8.0        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| mini_magick                | 4.5.1        |
| multi_json                 | 1.13.1       |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| bundler                    | 1.16.1       |
| faraday_middleware         | 0.12.2       |
| naturally                  | 2.1.0        |
| simctl                     | 1.6.4        |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| little-plugger             | 1.1.4        |
| logging                    | 2.2.2        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.2        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.13.6       |
| emoji_regex                | 0.1.1        |
| openssl                    | 2.0.5        |
| io-console                 | 0.4.6        |
| excon                      | 0.62.0       |
| CFPropertyList             | 3.0.0        |
| faraday                    | 0.15.0       |
| unf_ext                    | 0.0.7.5      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| fastimage                  | 2.1.3        |
| json                       | 2.1.0        |
| dotenv                     | 2.4.0        |
| fastlane-plugin-versioning | 0.3.4        |
</details>

*generated on:* **2018-06-13**
</details>
```

**Comment by joshdholtz** [comment]
@KjellConnelly Thanks for using the feature request template! ❤️ I totally get your reasoning for having a callback. 

Are you talking about adding a callback after:
1) the app is uploaded?
or
2) after the app is uploaded and successfully processed?

My biggest concern with either of these approaches is that fastlane runs thing synchronously and waits for all actions to finish before starting the next and it seems like this feature request would throw the "waiting for upload" onto a background process to wait for it to complete to submit.

This means that if all the end of the fastlane run would also need to "wait" or all these uploads and/or processing which makes the code implementation more complex than just adding callback and calling it when its done. fastlane would need to be aware of the new forks/processes that are created (outside of the `deliver` action`) and then wait for all of those to be done before this completely exiting out of the main (parent) fastlane process itself.

Am I reading into this correctly? 🙃
