### ISSUE TITLE
Add support for new iTunes Connect API to fetch release app build number and version.

### ISSUE THREAD

**Issue by lolgear** [fastlane/fastlane#12747]
Hi!

I would like to fetch build number metadata and version metadata for latest iOS released app to put version tag in git.

I can not be sure that version that I put in test flight "as release" will be release version in case of beta-testers or any other circumstances.

I could make a daemon which will run fetch of iTunes connect every day or just run this phase of release validation on each build.

If I fetch new released version ( version 2.0.1 ), I would like to stop and ask user to input another version or increase its part.
If I don't find this released version in git, I would like to add it to git as version tag.

**Comment by joshdholtz** [comment]
@lolgear Heyyy 👋 If you could please use one of the four provided issue templates from now on (there is one for "Feature Request") that would be 💯 This makes it easier for us maintainers to parse information about the feature request.

What you are looking to do can be done with `Spaceship` directly...
```rb
lane :the_live do
  fastlane_require 'spaceship'
  Spaceship::Tunes.login('josh+dev@rokkincat.com')
  Spaceship::Tunes.select_team(team_id: '3Q54H69ZVN')

  app = Spaceship::Tunes::Application.find('com.goodnightcar.GoodNightCar')
  live_version = app.live_version
  puts "version: #{live_version.version}"
  puts "build number: #{live_version.build_version}"
end
```
