### ISSUE TITLE
Switch environment when switching lanes

### ISSUE THREAD

**Issue by donald-m-ritter** [fastlane/fastlane#12744]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about? Switching Lanes
Is this a question about documentation? Yes
Is this a question about a third party plugin? No

#### Question Description
When switching lanes, is there a way to also change the environment?  Example:

```ruby
desc 'Tests the library'
lane :test do
    scan
end

desc 'Tests the library for iOS, watchOS, tvOS, and macOS'
lane :pullrequest do
  UI.important 'Verifying iOS'
  test --env ios

  UI.important 'Verifying watchOS'
  test --env watchos

  UI.important 'Verifying tvOS'
  test --env tvos

  UI.important 'Verifying macOS'
  test --env macos
end
```

**Comment by joshdholtz** [comment]
@donald-m-ritter Heyyyy 👋 I might need a little more clarification on your question. By "switching environments", are you talking about passing arguments to your `test` lane to test different schemes/targets?

If so, you could do something like...
```rb
desc 'Tests the library'
lane :test do |options|
    scan(scheme: options[:scheme])
end

desc 'Tests the library for iOS, watchOS, tvOS, and macOS'
lane :pullrequest do
  UI.important 'Verifying iOS'
  test(scheme: 'test-ios')

  UI.important 'Verifying watchOS'
  test(scheme: 'test-watchos')

  UI.important 'Verifying tvOS'
  test(scheme: 'test-tvos')

  UI.important 'Verifying macOS'
  test(scheme: 'test-macos')
end
```

This solution above though requires your Xcode project to have schemes call `test-ios`, `test-watchos`, `test-tvos`, and `test-macos` that do those specific tests.

Lemme know if this is not what you were looking for 😊

**Comment by donald-m-ritter** [comment]
I eventually figured it out by using `Dotenv.overload '.env.macos'`.

```ruby
desc 'Tests the library'
lane :test do
    scan
end

desc 'Tests the library for iOS, watchOS, tvOS, and macOS'
lane :pullrequest do
  UI.important 'Verifying macOS'
  Dotenv.overload '.env.macos'
  lane_context[SharedValues::ENVIRONMENT] = 'macos'
  test

  UI.important 'Verifying iOS'
  Dotenv.overload '.env.ios'
  lane_context[SharedValues::ENVIRONMENT] = 'ios'
  test

  UI.important 'Verifying tvOS'
  Dotenv.overload '.env.tvos'
  lane_context[SharedValues::ENVIRONMENT] = 'tvos'
  test

  UI.important 'Verifying watchOS'
  Dotenv.overload '.env.watchos'
  lane_context[SharedValues::ENVIRONMENT] = 'watchos'
  test
end
```
