### ISSUE TITLE
[React-Native] - Fastlane screenshots, recorder throw "Timestamped Event Matching Error..."

### ISSUE THREAD

**Issue by MayeuldP** [fastlane/fastlane#12748]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Question about setting up the wanted screenshots with `fastlane screenshots `

#### Question Description

Alright, I was setting up my project with fastlane in order to generate screenshots for the release on the store. When I tried to update the `textExample()` function in `[...]UITest.swift` using the `Recorder`, my simulator launched well, but when I clicked on any buttons, I got this error =>
 `Timestamped Event Matching Error: Failed to find matching element`
I found many peoples with this issue but who weren't doing a react native project.
Do you have any ideas about how to resolve it ? 

My Fastfile : 

```
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(project: "project.xcodeproj", scheme: "projectUITests")
  end
end
```

**Comment by joshdholtz** [comment]
@MayeuldP Heyyy 👋 This sounds like its not related to your `Fastfile` but instead related to your UI tests. It sounds like you are trying to specific an element by name/key in your UI tests (that control the screenshots) and the element you are specifying by name/key doesn't exist - either because its not on screen or its not configured properly. 

I think that is all that I am able to help you since I cannot do much debugging on your UI tests 😔

**Comment by MayeuldP** [comment]
@joshdholtz Hello, thank for your help, indeed, it worked for few components by adding `testID="identifier"` as props. 
However. for others elements, even if there's a testID props, I got this as a return, `app.otherElements.matching(random stuff)` instead of `app.buttons["indetifier']` for example, so then, running `fastlane screenshot` doesnt work, and display that `No matches found for Find:`... Do I do something wrong with the testID ? 

By the way, every time I run `fastlane screenshots` the app build every time again which is taking a long time, I tried to add `derived_data_path : ./fastlane/DerivedDataPath` and `test_without_building true` but didnt work.

**Comment by MayeuldP** [comment]
@joshdholtz Yeah indeed I succeed to make it works, concerning `derived_data_path` and `test_without_building`. 
Concerning ReactNative, I think, it's hard to make it work properly with fastlane. Do you guys plan to integrate fastlane for react-Native ?
Else, do you suggest or know, any tools for generate all the screenshots for a react-native app for itunes connect ? 

Thanks for your help.

**Comment by joshdholtz** [comment]
@MayeuldP We do try to support whatever our users are using and it seems like either RN is gaining popularity 😊 I would like to add more docs for RN and possibly some better onboarding in tools and such but there is also a fine line on how to manage our resources 🙃 

That being said, I would love to hear all your pain points when integrating fastlane in RN 🙏 I have an RN app that I maintain but I have fastlane working but I probably have a different view on fastlane 😇 

Is your main issue on just taking screenshots with RN? Or were there some other gotchas that you found?

**Comment by MayeuldP** [comment]
Would be so cool indeed. 
Yeah I was planing to use fastlane only for the screenshots. Well, actually, since there's no documentation for RN on fastlane, I needed to go search for informations here and there on internet. There's several tutorials about how managing release and automatic deployments, but never about the screenshots, since UI tests on Xcode for RN Project is not well supported. 
I succeed to manage fews components with the `testID` props which is supported by xcode. But nor for all of them on my RN project.

I think, it's more a question for react-native to better manage `testID` and UI Tests on xcode, than fastlane to adapt himself.

**Comment by joshdholtz** [comment]
@MayeuldP I created an issue in doc for me to take a look at later - https://github.com/fastlane/docs/issues/626

And thanks again for the feedback! Cool if I close this issue for now since it seems like this issue is solved now? 😊

**Comment by MayeuldP** [comment]
Thank you, nice,
yeah it's fine.

**Comment by RobertSasak** [comment]
@MayeuldP Would you mind to share how you have solved the issue with *testID* for most of your components? I keep getting *Timestamped Event Matching Error: Failed to find matching element* error.

**Comment by MayeuldP** [comment]
Hi @RobertSasak sorry for the late answer, so basically, few react native's components got this props => [testID](https://facebook.github.io/react-native/docs/view#testid) which allow you to do UITesting. 
It's done like this for example :
```
 <MyButton
            testID="doLogin"
            onPress={() => doSomeStuff()}
            color="primary">
            {I18n.t("Sign in")}
</MyButton>
```
Then in your testFile on xcode for example, just do like this for the UITest sequence => 
```
let app = XCUIApplication()
app.buttons["doLogin"].tap()
snapshot("TakeScreenshot")
```
However the `testID` props doesn't work for every component. 
Concerning react-navigation and navIcon on the tabBar for example, they added it in a recent release [here](https://github.com/react-navigation/react-navigation/releases/tag/2.2.0)

**Comment by RobertSasak** [comment]
Thank you for your reply. From my experience *testID* does not work on most of the element. I managed to successfully used it only on `<Text>` element. I hope that more and more libraries will support *testID* out of the box.

If anybody out there is also trying to use *testID* for taking screenshots with *fastlane*. I end up creating a custom component which works as "remote control". Remote control is placed in the middle of the screen and has opacity of 0.00001. In my UI test I tap on invisible `<Text>` node which then update redux state to desire state and then I take a screenshot.
```js
class Remote extends Component {

    handleState1Press = () =>
        this.props.setState(state1)

    handleState2Press = () =>
        this.props.setState(state2)

    render = () => {
        const {
            invisible,
            enabled,
        } = this.props
        return enabled && (
            <View style={[styles.wrapper, invisible ? styles.invisible : null]}>
                <Text
                    onPress={this.handleState1Press}
                    testID="State1"
                >
                    State1
                </Text>
                <Text
                    onPress={this.handleState2Press}
                    testID="State2"
                >
                    State2
                </Text>
        )
    }
}

Remote.defaultProps = {
    enabled: true,
    invisible: true,
    setState: () => { },
}

Remote.propTypes = {
    enabled: PropType.bool,
    invisible: PropType.bool,
    setState: PropType.func,
}

export default connect(null, {
    setState,
})(Remote)
```
And my *UITest.swift* looks like this.
```swift
    func testExample() {
        let app = XCUIApplication()
        app.staticTexts["State1"].tap()
        sleep(3)
        snapshot("01")
        app.staticTexts["State2"].tap()
        sleep(3)
        snapshot("02")
   }
```

**Comment by MayeuldP** [comment]
@RobertSasak yeah did the same tricks when I wasn't able to find the testID. Works well too :)

**Comment by TechGuyVN** [comment]
can anybody explain @RobertSasak  example, i can't apply it for my project :)

**Comment by RobertSasak** [comment]
@TechGuyVN Can you please be more specific about what do you not understand?
