### ISSUE TITLE
Add support to read file version at specific commit

### ISSUE THREAD

**Issue by lolgear** [fastlane/fastlane#12749]
It would be nice to have an ability to read file content in git history.

E.g. I would like to read file at specific commit:

```
git show commit:./Info.plist
```

Especially, I would like to read it with native functions like `get_info_plist_by_key()` or similar.

**Comment by joshdholtz** [comment]
@lolgear Heyyyy 👋 We currently are trying to limit the number of actions that are included into _fastlane_ itself. I would suggest that you either:
1. just run this with `sh("git show commit:./Info.plist")`
2. create your own custom action for this in your project
3. make this a plugin (if you would like to maintain this yourself and let other people to install this as well)

If there is bigger demand for this we can re-evaluate adding this as an action built into _fastlane_ but for now there are other multiple solutions that can be used to do this 👌

**Comment by lolgear** [comment]
@joshdholtz 
It seems that "this" approach ( by directly using git ) is broken in case of complex projects.
Git folder structure  doesn't directly mapped into project structure.

Also, reading 'whole" file is not ok, because I need to process it later to retrieve specific info from it. ( Like version number ).

Fastlane has only ( as far as I know ) one plist method that reads key from existing plist file, not a file in memory or plist-formatted-dictionary.

So, only one possibility to reuse this method - Tempfile.
