### ISSUE TITLE
`read_from_path': cannot load such file -- nanaimo

### ISSUE THREAD

**Issue by jaroslavas** [fastlane/fastlane#12757]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

On `gym` and `commit_version_bump` commands I get this error:

```
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/plist.rb:23:in `read_from_path': cannot load such file -- nanaimo (LoadError)
```

Solution in #6281 (reinstalling only one version of `nanaimo`) doesn't help.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane increment_build
[11:30:34]: fastlane detected a Gemfile in the current directory
[11:30:34]: however it seems like you don't use `bundle exec`
[11:30:34]: to launch fastlane faster, please use
[11:30:34]: 
[11:30:34]: $ bundle exec fastlane increment_build
[11:30:34]: 
[11:30:34]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[11:30:36]: ------------------------------
[11:30:36]: --- Step: default_platform ---
[11:30:36]: ------------------------------
[11:30:36]: Driving the lane 'ios increment_build' 🚀
[11:30:36]: ------------------------------------
[11:30:36]: --- Step: increment_build_number ---
[11:30:36]: ------------------------------------
Current version of project projectname is: 
    5

/Users/username/Projects/projectname/projectname-ios
[11:30:36]: $ cd /Users/username/Projects/projectname/projectname-ios && agvtool next-version -all && cd -
[11:30:36]: ▸ Setting version of project projectname to:
[11:30:36]: ▸ 6.
[11:30:37]: ▸ Also setting CFBundleVersion key (assuming it exists)
[11:30:37]: ▸ Updating CFBundleVersion in Info.plist(s)...
[11:30:37]: ▸ Updated CFBundleVersion in "projectname.xcodeproj/../projectname/Info.plist" to 6
[11:30:37]: ▸ /Users/username/Projects/projectname/projectname-ios
[11:30:37]: ---------------------------------
[11:30:37]: --- Step: commit_version_bump ---
[11:30:37]: ---------------------------------
[11:30:37]: $ git rev-parse --show-toplevel
[11:30:37]: ▸ /Users/username/Projects/projectname/projectname-ios
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | ios                 |
| PLATFORM_NAME    | ios                 |
| LANE_NAME        | ios increment_build |
| BUILD_NUMBER     | 6                   |
+------------------+---------------------+

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_numbe  | 1           |
|      | r                      |             |
| 3    | commit_version_bump    | 0           |
+------+------------------------+-------------+

[11:30:37]: fastlane finished with errors
/Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/plist.rb:23:in `read_from_path': cannot load such file -- nanaimo (LoadError)
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:201:in `initialize_from_file'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:103:in `open'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/commit_version_bump.rb:60:in `run'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/username/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.97.0/bin/fastlane:20:in `<top (required)>'
	from /Users/username/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/username/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  test_identifiers = ["com.projectname.test"]
  stage_identifiers = []
  live_identifiers = []#"com.projectname.live"]
  
  
  
  ## ****************************** VERSIONING ******************************
  
  desc "Move to next build number"
  lane :increment_build do
      increment_build_number
      commit_version_bump
  end
  
  desc "Move to next patch version number (1.1.X)"
  lane :increment_version_patch do
      increment_version_number(bump_type: "patch" )
      commit_version_bump
  end
  
  desc "Move to next minor version number (1.X.0)"
  lane :increment_version_minor do
      increment_version_number(bump_type: "minor" )
      commit_version_bump
  end
  
  ## ****************************** CERTIFICATES ******************************
  
  desc "Download all certificates from apple"
  lane :match_certificates do
      identifiers = test_identifiers + live_identifiers + stage_identifiers
      match(app_identifier: identifiers, readonly: false, force_for_new_devices:true, force:true, type: "development")
      match(app_identifier: identifiers, readonly: false, force_for_new_devices:true, type: "adhoc")
      match(app_identifier: identifiers, readonly: false, type: "appstore")
  end
  
  ## ******************************  TESTFLIGHT  ******************************
  
  desc "Submit a new Test Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight_test do
      match(app_identifier: test_identifiers, readonly: false, type: "appstore")
      gym(scheme: "TEST projectname")
      pilot
  end
  
  desc "Submit a new Test Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight_live do
      match(app_identifier: test_identifiers, readonly: false, type: "appstore")
      gym(scheme: "projectname")
      pilot
  end
  
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| simctl                    | 1.6.3        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| tty-screen                | 0.6.4        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.3        |
</details>

*generated on:* **2018-06-15**
</details>

**Comment by mikkoj** [comment]
Same here. Noticed the issue after XCode updated to 9.4.1.

**Comment by joshdholtz** [comment]
@mikkoj Are you also using `brew` to install _fastlane_?

@jaroslavas This looks to be an issue with using `brew` to install _fastlane_ and the how which gem dependencies are installed. Based upon your issue, it doesn't look like the `nanaimo` gem is properly installed (or installed in a way which `xcodeproj` (a gem that fastlane uses) can't find the `nanaimo` gem)

Can you try running `gem which nanaimo` and let me know if this finds anything?

An installation through `brew` can get a bit wonky with local Ruby versions and gems so the most stable way to install _fastlane_ to make sure all dependency versions are properly used is to install via _bundler_ with a `Gemfile` - https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

**Comment by mikkoj** [comment]
@joshdholtz Thanks for the clarifications. I now got it working running with `bundle exec fastlane ...`

For me `gem which nanaimo` returns:
`/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.5/lib/nanaimo.rb`

It's possible the wrong version of nanaimo is picked up using only `fastlane`. I'll try to reinstall fastlane without `brew` (cannot recall if installed it with `brew` initially)

**Comment by joshdholtz** [comment]
@mikkoj Glad you got it working with `bundle exec` 🙌  If you were running it without that before then Ruby may have been just picking up the `nanaimo` gem from who knows where 🙃 

`bundle exec` is always the safest way to run things so that you know **exactly** what the dependencies that _fastlane_ is running with (defined by the `Gemfile` and which then can be seen in the `Gemfile.lock`)

**Comment by jaroslavas** [comment]
OK, I had `fastlane` installed into `~/.fastlane`, not sure how it was done. Deleting it and installing via bundle did the trick. Thanks!
