### ISSUE TITLE
Name of the lane 'testflight' is already taken by the action named 'testflight'

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#12753]
Omg I just updated from some ancient fastlane to the latest and it says `Name of the lane 'testflight' is already taken by the action named 'testflight'` and goes into recursion if I run such lane. How can I fix this. Do I have to rename my actions? 🆘

**Comment by shardulsrivastava** [comment]
@pronebird can you paste your fastfile here??

**Comment by pronebird** [comment]
@shardulsrivastava it's quite large, but offending lanes share the same name as action, i.e:

```
desc "Generate NSManagedObject subclasses from CoreData Model."
  lane :mogenerator do
    mogenerator
end
```

`mogenerator` is also an action.

**Comment by joshdholtz** [comment]
@pronebird You do have to rename your lanes so they don't match actions 😇 Having lanes and actions have same names causes confusion on what is _actually_ getting called since they can both get called the same way.
