### ISSUE TITLE
set_build_number_repository cannot update path containing $(SRCROOT)

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#12759]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@pronebird Going to close this issue since no issue information, `fastlane env`, or _fastlane_ output was provided. Please open another issue with all requested information and I will be happy to look into 😊
