### ISSUE TITLE
Is this a good approach for project with various targets?

### ISSUE THREAD

**Issue by tharak** [fastlane/fastlane#12765]
Hello, I started to use fastlane in my company and I'm not sure if this is the best approach for our scenario.
We have three white label apps that have more then 30 clients where every client is a target, some clients have their own itunes account (team_id and itc are different).
New versions of the apps are sent according to client requests (We don't update all the apps at the same time).
Right know I'm implementing this for our project with more targets and the plan is to copy the fastfile to the other projects and it will magically work.
After some days trying to make fastlane work for all target I came up with this solution:
Every target has its own environment file (.env.xxxx).

**.env.target**:
```
APPLE_ID_USER=***
GIT_HUB_USER=***
WORKSPACE=Project.xcworkspace
MATCH_GIT_URL=https://github.com/***
MATCH_PASSWORD=***

#team dependent
TEAM_ID=ABCDE
FASTLANE_ITC_TEAM_ID=123456789
GIT_BRANCH="company" #Use one git branch per team https://docs.fastlane.tools/actions/match/

#target dependent
BUNDLE_ID=com.company.target
GYM_SCHEME=Target

PLIST_PATH="Project/Customer/#{ENV['GYM_SCHEME']}/Supporting Files/#{ENV['GYM_SCHEME']}-info.plist"
```
For every team I have a lane that makes match. And one lane that runs all of them, so when we have a new mac that needs the certificates we run it. 

**team_lane**:
```
  lane :team1 do
    bundle_id_list = [ 
      #product1
      "com.company.product1.client1",
      "com.company.product1.client2",
      "com.company.product1.client3",
      #product2
      "com.company.product2.client1",
      "com.company.product2.client2",
      "com.company.product2.client3"
    ]
    certificates_git_branch = "client"
    team_id = "ACBD"
    sync_code_signing(git_branch: certificates_git_branch, team_id: team_id, app_identifier: bundle_id_list, type: "appstore", readonly: true)
    sync_code_signing(git_branch: certificates_git_branch, team_id: team_id, app_identifier: bundle_id_list, type: "development", readonly: true)
  end
```

to upload to testfligth I did this lane
**beta lane**
```
  lane :beta do
    sync_code_signing(type: "appstore",
        app_identifier: ENV['BUNDLE_ID'],
        git_url: ENV['MATCH_URL'],
        git_branch: ENV['GIT_BRANCH'],
        readonly: true
    )
    increment_build_number(build_number: latest_testflight_build_number + 1)
    build_ios_app(suppress_xcode_output: true, disable_xcpretty: true, export_method: "app-store",
      export_options: {
            method: "app-store",
            signingStyle: "automatic"
        }
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
    hipchat(api_token: "***",
      message: "upload_to_testflight #{ENV['BUNDLE_ID']}",
      message_format: "html",
      channel: "fastlane",
      success: true,
      version: "1",
      notify_room: true
    )
  end
```

At some point I had to add this to the Appfile because, I guess, some actions where not reading from the env:
**Appfile**
```
app_identifier ENV['BUNDLE_ID'] # The bundle identifier of your app
apple_id ENV['APPLE_ID_USER'] # your Apple ID user
```
Matchfile, Gymfile, etc are empty or do not exist. I was going to do the same as in Appfile but I was not sure which variable should go on which files.

Any thoughts on this approach?

**Comment by joshdholtz** [comment]
@tharak Heyyy, using `.env.target` is a pattern that I follow as well!  I usually do this for different environments (dev, staging, production) but essentially same concept 👌

- You could also add `FASTLANE_USER` so you don't need to see `apple_id` in your `Appfile`
- You could also try setting `PRODUCE_APP_IDENTIFIER` so you don't need to set `app_identifier` in your `Appfile` 

💪

**Comment by tharak** [comment]
@joshdholtz where did you get this PRODUCE_APP_IDENTIFIER? I searched in the docs but could not find it.
Is there a list of all the possible environment variables?

**Comment by joshdholtz** [comment]
@tharak You can see environment variables by executing `fastlane action <action_name>` in the CLI 😊 

![screen shot 2018-06-19 at 7 44 24 am](https://user-images.githubusercontent.com/401294/41598010-9ef392de-7394-11e8-9296-e3942cef6518.png)
