### ISSUE TITLE
Plugin pitch: generate build secrets as part of build

### ISSUE THREAD

**Issue by amlcurran** [fastlane/fastlane#12766]
#### Motivation Behind Feature
We've recently built a new application using fastlane as our build process. There are keys for various SDKs that need to be kept out of the repo for security, and are supplied by the CI environment. Currently, getting these into a iOS app is not trivial and would be a nice (optional) addition to the build system. We have built a custom "plugin" as part of our fastlane build, but would like to make this more widely available.

Our company currently has a similar [plugin available](https://github.com/novoda/gradle-build-properties-plugin) for Android Gradle builds.

#### Feature Description
This plugin would:
- Be able to generate a file with secrets, supporting input from the environment (`ENV`).
- Generate a Swift file, to utilise type-safety, with a configurable filename (different outputs e.g. plist would be considered)
- Fail fast in the case a required secret is missing

I will be implementing this throughout this week. If it sounds like an idea that suits fastlane as a whole, I'll make a PR back to fastlane. If not, we'll keep it on one of our own repos :) 

#### Alternatives or Workarounds
- Our current solution essentially implements this functionality, but is specific to our current project.
- A similar project exists for Cocoapods, [cocoapods-keys](https://github.com/orta/cocoapods-keys), but we do not feel that this is functionality that should be implemented by a dependency manager, rather a build system.

**Comment by amlcurran** [comment]
@joshdholtz hey! This is part of it, however our use case is to _then_ generate a Swift file containing those keys so they can be accessed in code. For example given we have an `ENV` containing `apiKey` and `crashlyticsKey`, it would generate a file:

```swift
struct BuildConfig {
  static let apiKey = "<secret key here>"
  static let crashlyticsKey = "<crashlytics secret key here>"
}
```

This way, we can access those values in the app, and we also get a compile error when the file is missing.

We also have some cleverness as we need different keys for different stages but I'm not sure I'd round to implementing that!

**Comment by joshdholtz** [comment]
@amlcurran Ahhhh, I see I see! You are looking for these secret for your iOS app too (not just for your fastlane implementation). I would probably suggest that this get created as a third-party plugin (and not as a _fastlane_ action) as we are currently limiting the amount of new actions that we are allowing to get merged into _fastlane_ 😊 

Create your own plugin doc - https://docs.fastlane.tools/plugins/create-plugin/

**Comment by amlcurran** [comment]
@joshdholtz yup exactly! 

Perhaps I misunderstood then, are plugins not part of the fastlane project themselves, but separate repos?

**Comment by joshdholtz** [comment]
@amlcurran Correct correct!

`actions` are built into _fastlane_ directly and `plugins` are similar to actions but as external gems/repos 👍

**Comment by amlcurran** [comment]
@joshdholtz cool thanks! Then I'll implement this plugin and will close this issue. Thanks for your help :)
