### ISSUE TITLE
Changelog between two release tags

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#12762]
#### Motivation Behind Feature

Hi,

When deploying I usually already have a tag in place, so I'd expect `changelog_from_git_commits` to collect the changelog between two most recent release tags, but instead it goes between `head` and the last tag. Which works great for beta builds where the tag is not in place yet, but doesn't for release deployments.

There is also only one built-in action that allows to collect the last tag only. It would be ace to have the facility to grab two most recent tags (perhaps with glob filter, i.e `release/*`).

#### Alternatives or Workarounds
Using Git directly:
```
most_recent_tags = sh("git tag | grep 'release/' | sort -r | head -2").split("\n")
commit_history = changelog_from_git_commits(
  between: most_recent_tags,
  merge_commit_filtering: 'exclude_merges'
)
```

**Comment by joshdholtz** [comment]
@pronebird I _think_ this already works as expected 🙃 

I ran `fastlane run changelog_from_git_commits between: "2.95.0,2.94.0"` on the _fastlane_ repo and it looks like it returned only the commits between `2.95.0` tag and `2.94.0` tag for me 🤔

**Comment by pronebird** [comment]
@joshdholtz try running `changelog_from_git_commits()`.

**Comment by joshdholtz** [comment]
@pronebird `fastlane run changelog_from_git_commits` is the same thing as calling `changelog_from_git_commits` from the CLI instead of `Fastfile` - it passes the same info and runs the same code 😊 

What parameters are you passing to `changelog_from_git_commits`?

**Comment by pronebird** [comment]
@joshdholtz Pretty cool, I didn't know that!  👏 

I think you misunderstood my feature request though. Basically I have two scenarios when I use the changelog.

1. Shipping TestFlight builds
In this scenario running `changelog_from_git_commits` without parameters is fine since it picks up everything between `HEAD:last_git_tag`. I don't usually tag TestFlight builds so that works fine.

2. Shipping AppStore builds
In this scenario I usually tag the release manually, then run fastlane to ship the build to AppStore. The thing is in order to obtain the changelog between releases I actually need to know what tag was before and now. This is of course can be solved by running, i.e `git ` command directly but seems a little inconvenient.

```ruby
most_recent_tags = sh("git tag | grep 'release/' | sort -r | head -2").split("\n")
commit_history = changelog_from_git_commits(
  between: most_recent_tags
)
```

**Comment by joshdholtz** [comment]
@pronebird Ohhhh, I totally misunderstood your question 🙃 I thought you were saying that we needed to implement `changelog_from_git_commits` to work with two tags 😝 

I _think_ your approach is probably the recommended for now. I feel like opening up an option for two most recent tags might open up requests for more options for other types of custom configurations which makes maintenance/debugging on this action harder 😇

**Comment by pronebird** [comment]
I see. Just trying to give the feedback after using Fastlane in my rudimental flow. Really nothing fancy in my scripts. Felt like certain things were harder than they should be. 👍

**Comment by joshdholtz** [comment]
@pronebird I 100% appreciate the feedback! I definitely understand how not having an option for "latest two tags" can make things harder but we need to walk the fine line between having options that make things most flexible/extensible and not having too many options that makes things more confusing for users and harder for maintainers 😊 

Being able to compose a the ability you need for your workflow with only two actions (`sh` and `changelog_from_git_commits`) still seems like a pretty solid alternative, IMO 🙃
