### ISSUE TITLE
Upload to testflight fails constantly 

### ISSUE THREAD

**Issue by Kollerb04** [fastlane/fastlane#12767]
Using fastlane  2.93.1 xcode 9.4 and upload_to_testflight(), Fastlane upload fails for both:
DAV:
`unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
An error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
\nAn error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
\nCould not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.`

non-DAV:
`Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.`

I'd be happy to provide a certificate if this is a proxy related error but what where?

**Comment by joshdholtz** [comment]
@Kollerb04 I have never seen this error message before 😱 

1) Are you able to successfully upload an IPA manually using Xcode or Application Loader?
2) What were the versions of fastlane and Xcode the last time this worked?
3) Did the network you are on change any security setting (or something) that could effect?
4) Does uploading work if you are outside of the network that uploading failed on?

**Comment by Kollerb04** [comment]
@joshdholtz 
1.I guess yes
2.9.3 and fastlane 2.93.1
3.I'm afraid yes
4. Actually DAV upload worked on the outside nework, yes. 

So where do I supply the ssl certificate for this?

**Comment by joshdholtz** [comment]
@Kollerb04 There isn't a place to supply an SSL certificate. I don't know anything about your network setup or if you are within a company network but sounds like to me like your network admins could potentially be blocking something here if this used to work and still works outside of the network 😬 The best bet is to probably talk to them to open stuff up to get things resolved.
