### ISSUE TITLE
Fastlane build with Manual Certs and Profiles

### ISSUE THREAD

**Issue by mschary932** [fastlane/fastlane#12760]
### Question Checklist

- [Yes ] Updated fastlane to the latest version
- [Yes ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ Yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ Yes] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Is there a way to use manually created certs and profiles directly in Fastfile?

#### Question Description
Is there a way to use manually created certs and profiles directly in Fastlane without access to Apple account and GitHub repo.  I have local certificate and profile, and I want to install on specific folder and share these profile path and cert name and cert path to Xcode gym build. Can I get fastfile samples for this flow to establish? I am a newbie to the fastlane and I looked at docs and forums to see if there is a way to install on dynamic path and use that in gym configuration, but dint find any reference. Specifically installing profile on a dynamic path, not on default location '~/Library/MobileDevice/Provisioning Profile'.

Glad if someone can help me here.

**Comment by PAlkisP** [comment]
Is there a reason you aren't using fastlane/Match?

**Comment by mschary932** [comment]
Yes. I know Match can do this stuff for automatic certs and profile setups. Basically, I want to achieve two workflows - one with Match, where I can share apple account and git repo details and it's creating certs and profiles one the fly. Successfully I am able to get this done. Now, I am looking to extend this for second flow, if user can share existing certs that he might installed local dev boxes to re-use it in fastlane. This is for various reasons like some intended people might not have full fledge access to apple account or git repos.  When sometimes Cert limit crossed in developer/enterprise accounts, he can simply re-use existing ones.

**Comment by joshdholtz** [comment]
@mschary932 _fastlane_ can 100% use manually created certs and profiles. You will need to manually set the provisioning profile mapping like...
```rb
lane :build do
  gym(
    export_options: {
      method: "app-store"
      provisionProfiles: {
        "com.your.bundle.id": "your provisioning profile name"
      }
    }
  )
end
```

^ This is what `match` and `sigh` set for your automatically but you can do this yourself

**Comment by mschary932** [comment]
Thanks @joshdholtz for the update.

But How do I set the profile path to explicit location for the fastlane to pick, I don't want to copy it to "~/Library/MobileDevice/Provisioning Profile/" path.

**Comment by joshdholtz** [comment]
@mschary932 You don't need to give the path. With `provisioningProfiles` keys above, you just need to specify the name of the profile where the name matches what is in the iOS Developer Portal.

If you _do_ want to use the profile path (which isn't the recommend solution these days), you could use this action - https://docs.fastlane.tools/actions/update_project_provisioning/

**Comment by mschary932** [comment]
thanks again @joshdholtz.

So if 'update_project_provisionin'g is not the recommended solution, then how to manually specify my p12 cert and profile details to fastlane. Like I mentioned, I am not going to have GitHub access to store these assets and also I am not going to have apple account to get or create certs on-fly. I guess Match and Sigh both serve these two options. But to meet my requirement, I may not use them.

I am thinking to use _import_certificate_ with _certificate_path_ to install p12 cert in Mac. _Profile_path_ in _update_project_provisioning_ to mention about the profile path. Not sure if this correct way to get this done.


any inputs from your end?

**Comment by joshdholtz** [comment]
@mschary932 My recommend solution (without using `match` or `sigh`) is still the solution I commented here - https://github.com/fastlane/fastlane/issues/12760#issuecomment-398042007 😊 

As long as:
1) The certificate is installed on your machine
2) The profile is installed on your machine
3) And you manually specify the profile mapping in `gym`

It _should_ build 👌

**Comment by mschary932** [comment]
thanks. When you say 'The profile is installed on your machine', I dont want to place (or install) .mobileprovision file under '~/Library/MobileDevice/Provisioning Profile'. I will place in some random location, and want to pass that file path to fastfile. possible?

**Comment by joshdholtz** [comment]
@mschary932 Should be possible with https://docs.fastlane.tools/actions/update_project_provisioning/. One of the parameters is `profile` which in the doc says `profile`

**Comment by joshdholtz** [comment]
@mschary932 Glad you were able to make this work! Going to close this issue for now but feel free to mention me here or open another issue if you have any other questions/issues 😊
