### ISSUE TITLE
Fastlane build with WatchOS app integration

### ISSUE THREAD

**Issue by mschary932** [fastlane/fastlane#12761]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How do I build an App with WatchOS2 extension. 

#### Question Description

I have working fastlane file where I was able to build for a single app. Now I want to extend this for apps which I have WatchOS entensions.

```
platform :ios do
  before_all do
    ENV['MATCH_KEYCHAIN_NAME'] = "KC_#{ENV['GYM_OUTPUT_NAME']}_#{ENV['BUILD_NUMBER']}"
    ENV['MATCH_KEYCHAIN_PASSWORD'] = "xxxx"
    @derivedDataPath = "#{ENV['PROJECT_WORKSPACE']}/DerivedData"
    @buildArchivePath  = "#{ENV['PROJECT_WORKSPACE']}/Archive"
    @buildlogPath = "#{ENV['PROJECT_WORKSPACE']}/Logs/gym"
    
    create_keychain(name: ENV["MATCH_KEYCHAIN_NAME"], password: ENV["MATCH_KEYCHAIN_PASSWORD"], unlock: true, timeout: false)
    sh("security list-keychains -d user")
    sh("security set-keychain-settings #{ENV["MATCH_KEYCHAIN_NAME"]}")
    
    automatic_code_signing(path: ENV["FL_PROJECT_SIGNING_PROJECT_PATH"])
    update_info_plist(xcodeproj: ENV["FL_PROJECT_SIGNING_PROJECT_PATH"], plist_path: 'Info.plist')
    match(force_for_new_devices: true)
    
    ENV['GYM_XCARGS'] = "DEVELOPMENT_TEAM=#{ENV["sigh_#{ENV['MATCH_APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}_team-id"]} PROVISIONING_PROFILE_SPECIFIER=#{ENV["sigh_#{ENV['MATCH_APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}"]} OTHER_CODE_SIGN_FLAGS=\"--keychain #{ENV['MATCH_KEYCHAIN_NAME']}\""
  end

  desc "Build and sign (Release)"
  lane ios_release do
    gym(scheme: 'Release', export_method: ENV["MATCH_TYPE"], clean:true, disable_xcpretty: true, derived_data_path: @derivedDataPath, build_path: @buildArchivePath, buildlog_path: @buildlogPath)
  end
```

I simply changes in existing code with below line after going through couple of forums. But I am getting an exceptions, where it is not able to set proper profile for the watchOS target.  I guess something I am missing to set the profile.

Code Signing Error: Provisioning profile "match Development com.x.y" has app ID "com.x.y", which does not match the bundle ID "com.x.y.watchkitapp".
Code Signing Error: Provisioning profile "match Development com.x.y" has app ID "com.x.y", which does not match the bundle ID "com.x.y.watchkitapp.extension".
```
    app_identifiers = [
        "#{ENV['MATCH_APP_IDENTIFIER']}",
        "#{ENV['MATCH_APP_IDENTIFIER']}.watchkitapp",
        "#{ENV['MATCH_APP_IDENTIFIER']}.watchkitapp.watchkitextension"
      ]
    
    match(app_identifier: app_identifiers, force_for_new_devices: true)
`

I also tried defining profile export in gym configure, but no luck.

export_options: {
 `
provisioningProfiles: {
           "#{ENV['MATCH_APP_IDENTIFIER']}" => "match #{ENV['MATCH_TYPE']} #{ENV['MATCH_APP_IDENTIFIER']}",
           "#{ENV['MATCH_APP_IDENTIFIER']}.watchkitapp" => "match #{ENV['MATCH_TYPE']} #{ENV['MATCH_APP_IDENTIFIER']}.watchkitapp",
           "#{ENV['MATCH_APP_IDENTIFIER']}.watchkitapp.watchkitextension" => "match #{ENV['MATCH_TYPE']} #{ENV['MATCH_APP_IDENTIFIER']}.watchkitapp.watchkitextension"
         }
        },
```

Could someone give me insight on this issue, or tell mw to get it worked for multiple targets with different app-id and profile?

**Comment by mschary932** [comment]
It looks like, we dont have provision to set different profiles for different targets? Though I created certificates for multiple identifiers using match and defined provisioningProfiles map hash, Fastlane still considering same app-id profile across all targets.

Is there a way to set this or did I miss any configuration?

**Comment by mschary932** [comment]
any inputs please?

**Comment by joshdholtz** [comment]
@mschary932 You can explicitly pass multiple app identifiers into `match` and then match will automatically create a `export_options.provisioningProfiles` mapping so that you don't have to.

Example:
```rb
lane :build do
  match(
    app_identifier: [
      "com.myapp",
      "com.myapp.watch",
      "com.myapp.today"
    ],
    force_for_new_devices: true
  )
  gym(scheme: 'Release')
end
```

**Comment by mschary932** [comment]
@joshdholtz,

Do I need to remove PROVISIONING_PROFILE_SPECIFIER in  ENV['GYM_XCARGS'] in my above code to get this worked? When I use this specifier it is not figuring watchkit target profiles.  It stop referring main app profile.

If I remove this, its prompting to mention profile map using export options. I even added this hash map, still getting some exception like signing identity  not found for each of the target.

Something issue with gym_xcargs setting that I am using?

**Comment by mschary932** [comment]
Once I added with below fastlane script, I am getting exception like - '  Code Signing Error: "KWatchOS2 Extension" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.'

KWatchOs2 is my watch extension target.

`match(app_identifier: [ "com.myapp", "com.myapp.watchkitapp", "com.myapp.watchkitapp.watchkitextension"], force_for_new_devices: true)

   gym(scheme: 'Release', configuration: "Debug", export_method: ENV["MATCH_TYPE"],
                xcargs: "DEVELOPMENT_TEAM=#{ENV["sigh_#{ENV['MATCH_APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}_team-id"]} OTHER_CODE_SIGN_FLAGS=\"--keychain #{ENV['MATCH_KEYCHAIN_NAME']}\"")
`

I was unable to get further to this level without adding xcargs to gym. But still I am facing issue with provision profile for extensions, looks like it is not auto setting profiles for each these watch targets, even though we defined app-identifiers in match.

**Comment by joshdholtz** [comment]
@mschary932 Can you paste your whole output for me here?

**Comment by mschary932** [comment]
@joshdholtz ,

**Here is my code snippet:**

`
platform :ios do
  before_all do
	create_keychain(name: ENV["MATCH_KEYCHAIN_NAME"], password: ENV["MATCH_KEYCHAIN_PASSWORD"], unlock: true, timeout: false)
    sh("security list-keychains -d user")
    sh("security set-keychain-settings #{ENV["MATCH_KEYCHAIN_NAME"]}")

    automatic_code_signing(path: ENV["FL_PROJECT_SIGNING_PROJECT_PATH"])
    update_info_plist(xcodeproj: ENV["FL_PROJECT_SIGNING_PROJECT_PATH"], plist_path: 'Info.plist')

    match(app_identifier: [ "com.myapp.afdemo", "com.myapp.afdemo.watchkitapp", "com.myapp.afdemo.watchkitapp.watchkitextension"], force_for_new_devices: true)

  end

  desc "Build and sign (Release)"
  lane :kony_ios_build do
    ENV['GYM_XCARGS'] = "DEVELOPMENT_TEAM=#{ENV["sigh_#{ENV['MATCH_APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}_team-id"]} OTHER_CODE_SIGN_FLAGS=\"--keychain #{ENV['MATCH_KEYCHAIN_NAME']}\""

    gym(scheme: 'KRelease', configuration: "Release", export_method: ENV["MATCH_TYPE"], disable_xcpretty: true)
  end
end`


**Error Output:**

Code Signing Error: 
"KWatchOS2 Extension" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
"KWatchOS2" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
"KRelease" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.


I attempted to manually set profiles for each of these targets with below lines of code, able to generate the app successfully. I am not sure if this need to be manually set for each and every target. 

`	update_project_provisioning(
          xcodeproj: ENV["FL_PROJECT_SIGNING_PROJECT_PATH"],
          target_filter: "KWatchOS2 Extension$",
          profile: ENV['sigh_com.myapp.afdemo.watchkitapp.watchkitextension_development_profile-path']
        )
        update_project_provisioning(
          xcodeproj: ENV["FL_PROJECT_SIGNING_PROJECT_PATH"],
          target_filter: "KWatchOS2$",
          profile: ENV['sigh_com.myapp.afdemo.watchkitapp_development_profile-path']
        )
        update_project_provisioning(
          target_filter: "KRelease$",
          profile: ENV['sigh_com.myapp.afdemo_development_profile-path']
        )`


I have other query as well, is there a way to pull bundle identifiers list from xcode project, that way I cannot hard-code these app-identifiers.

**Comment by joshdholtz** [comment]
@mschary932 So just to confirm, you were able to successfully build an IPA by using `update_project_provisioning`?

**Comment by mschary932** [comment]
yes @joshdholtz. I am able to successfully build it. But I am not sure if this is correct way?

To make this script more reliable, I want to make those app-identifers list and target_filters also to be  retrieved programatically.  Do you think it is possible to get that to level?  Because, today it is watchkit app, I know target name and it;s bundle identifier.  If I want to add any other new extensions, again I need to hard code these values, right? so, problems.

**Comment by joshdholtz** [comment]
@mschary932 One thing you _might_ be able to do to prevent these errors:
```
Code Signing Error:
"KWatchOS2 Extension" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
"KWatchOS2" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
"KRelease" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
```
... is to set "Don't Code Sign" for your `Release` config. I think these errors are coming from the "build" part of `gym` and not the "signing" part. If you tell your `Release` config to not code sign, it should make it through that ***and then** it will use the the `provisioningProfile` mapping that `match` generates... hopefully 😇 

Sorry about all the different solutions I'm coming up with! There are always multiple solutions with fastlane and its hard to give exact solutions when I don't have the project in the screen infront of me 😉

**Comment by mschary932** [comment]
hey @joshdholtz,

Sorry I given different error output. Following is the exception I see with the actual code that I shared above.

Code Signing Error: Provisioning profile "match Development com.myapp.afdemo" has app ID "com.myapp.afdemo", which does not match the bundle ID "com.myapp.afdemo.watchkitapp.watchkitextension".
Code Signing Error: Provisioning profile "match Development com.myapp.afdemo" doesn't match the entitlements file's value for the application-identifier entitlement.

It is not referring same profile of main-app across watchkit app-id. In the console, I could see profiles are installed properly for all required app-ids and its able to show proper mapping. 


All required keys, certificates and provisioning profiles are installed 🙌
12:01:46 [12:01:45]: Setting Provisioning Profile type to 'development'
12:01:46 [12:01:45]: -----------------
12:01:46 [12:01:45]: --- Step: gym ---
12:01:46 [12:01:45]: -----------------
12:01:46 [12:01:45]: $ xcodebuild -showBuildSettings -scheme KRelease -project ./VMAppWithKonylib.xcodeproj -configuration Release
12:01:49 [12:01:48]: Detected provisioning profile mapping: {:"com.myapp.afdemo"=>"match Development com.myapp.afdemo", :"com.myapp.afdemo.watchkitapp"=>"match Development com.myapp.afdemo.watchkitapp", :"com.myapp.afdemo.watchkitapp.watchkitextension"=>"match Development com.myapp.afdemo.watchkitapp.watchkitextension"}
