### ISSUE TITLE
Register Launch Screen in project

### ISSUE THREAD

**Issue by Dictory** [fastlane/fastlane#12777]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Launch Screen

#### Question Description
Hello. Can i register Launch Screen in `.pbxproj` programmatically?

**Comment by joshdholtz** [comment]
@Dictory There is not a built in fastlane action to do this but you might be able to do something more custom if you use the `xcodeproj` gem - https://github.com/CocoaPods/Xcodeproj

**Comment by Dictory** [comment]
@joshdholtz ok thanks for answer
