### ISSUE TITLE
Fastlane builds and submits app inspite of error

### ISSUE THREAD

**Issue by sprabhuanand** [fastlane/fastlane#12778]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I have a weird behavior. When building/compiling the application, there is a failure and fastlane exits with code 65 and have this message in the log
"Fastlane finished with error".

But shortly after 2-3 mins, the build continues and overwrites the logs and finish uploading the app and we are getting a test-flight. 
#### Question Description
1. Why fastlane continues to build when there is a failure ? Looks like something been started parallely

I'm using gym to build it
    gym(
        workspace: "abcd.xcworkspace",
      scheme: scheme,
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )

Fastlane env below
================
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.16.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.96.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| json                      | 2.1.0        |

First Error
=========
INFO [2018-06-19 21:20:26.52]: [32mSuccessfully generated documentation at path '/Users/Shared/Jenkins/Home/workspace/ios-build/fastlane/README.md'[0m

+------+------------------------+-------------+
|              [32mfastlane summary[0m               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 0           |
| 2    | default_platform       | 0           |
| 3    | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 4    | cd ../;git log         | 0           |
|      | --pretty=format:'%s    |             |
|      | %h' | grep -i          |             |
|      | '^version bu           |             |
| 5    | git rev-parse HEAD     | 0           |
| 6    | latest_testflight_bui  | 21          |
|      | ld_number              |             |
| 7    | increment_build_numbe  | 0           |
|      | r                      |             |
| 💥   | [31mgym[0m                    | 61          |
+------+------------------------+-------------+

ERROR [2018-06-19 21:20:26.54]: [31mfastlane finished with errors[0m

**Comment by sprabhuanand** [comment]
it fails well before that, did not reach code-signing part

**Comment by shardulsrivastava** [comment]
@sprabhuanand  can you paste your entire log, to see the error clearly??

**Comment by joshdholtz** [comment]
@sprabhuanand Can you also post your `Fastfile` as well as what @shardulsrivastava is requesting?

**Comment by sprabhuanand** [comment]
Its a compiling issue, so it fails there. 

⚠️  /Users/Shared/Jenkins/Home/workspace/ios-build/mindstrongtasks/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:65:93: lambda capture 'callId' is not used [-Wunused-lambda-capture]

dispatch_block_t block = [weakBridge, weakModuleData, methodId, params=std::move(params), callId] {
                                                                                     ^


▸ Compiling RCTTouchEvent.m
▸ Compiling RCTProfile.m
▸ Compiling RCTComponentData.m
▸ Compiling RCTNavigatorManager.m
▸ Compiling RCTModalManager.m
▸ Compiling RCTUIUtils.m
▸ Building library libReact.a
▸ Building library libReact.a
▸ Running script 'Include RCTJSCProfiler'

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't stat input file: /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a (No such file or directory)



❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: file: /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a is not writable (No such file or directory)


** ARCHIVE FAILED **


The following build commands failed:
Strip /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a
(1 failure)
ERROR [2018-06-19 21:20:26.44]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.96.1                  |
| export_method | app-store               |
| sdk           | iPhoneOS11.4.sdk        |
+---------------+-------------------------+

INFO [2018-06-19 21:20:26.51]: ▸     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
INFO [2018-06-19 21:20:26.51]: ▸     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++14 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wnewline-eof -Wno-c++11-extensions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -fembed-bitcode -I/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/React.build/Release-iphoneos/yoga.build/yoga.hmap -I/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/BuildProductsPath/Release-iphoneos/include -I/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/React.build/Release-iphoneos/yoga.build/DerivedSources/armv7 -I/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/React.build/Release-iphoneos/yoga.build/DerivedSources -Wextra -Wall -Wno-semicolon-before-method-body -F/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/BuildProductsPath/Release-iphoneos -MMD -MT dependencies -MF /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/React.build/Release-iphoneos/yoga.build/Objects-normal/armv7/Yoga.d --serialize-diagnostics /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/React.build/Release-iphoneos/yoga.build/Objects-normal/armv7/Yoga.dia -c /Users/Shared/Jenkins/Home/workspace/ios-build/mindstrongtasks/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp -o /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/React.build/Release-iphoneos/yoga.build/Objects-normal/armv7/Yoga.o
INFO [2018-06-19 21:20:26.51]: ▸ error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't stat input file: /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a (No such file or directory)
INFO [2018-06-19 21:20:26.52]: ▸ error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: file: /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Mindstrong-dkgdiichsonksffhoggmlypzivfi/Build/Intermediates.noindex/ArchiveIntermediates/Mindstrong/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a is not writable (No such file or directory)
INFO [2018-06-19 21:20:26.52]: ▸ Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip failed with exit code 1
INFO [2018-06-19 21:20:26.52]:
ERROR [2018-06-19 21:20:26.52]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2018-06-19 21:20:26.52]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2018-06-19 21:20:26.52]: 📋  /Users/Shared/Jenkins/Library/Logs/gym/Mindstrong-Mindstrong.log
INFO [2018-06-19 21:20:26.52]:
ERROR [2018-06-19 21:20:26.52]: Looks like fastlane ran into a build/archive error with your project
ERROR [2018-06-19 21:20:26.52]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2018-06-19 21:20:26.52]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2018-06-19 21:20:26.52]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2018-06-19 21:20:26.52]: sure your project is set up correctly.
ERROR [2018-06-19 21:20:26.52]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2018-06-19 21:20:26.52]: the full commands printed out in yellow in the above log.
ERROR [2018-06-19 21:20:26.52]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2018-06-19 21:20:26.52]:
WARN [2018-06-19 21:20:26.52]: Lane Context:
INFO [2018-06-19 21:20:26.52]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :VERSION_NUMBER=>"2.11", :BUILD_NUMBER=>"178", :FL_CHANGELOG=>"Merge pull request #366 from MindStrongHealth/bug/HEALTH-1344\nHEALTH-1344\nMerge branch 'bug/HEALTH-1344' of github.com:MindStrongHealth/ios-keyboard into bug/HEALTH-1344\nMerge pull request #365 from MindStrongHealth/bug/HEALTH-1344\nBug/health-1344\nMerge pull request #364 from MindStrongHealth/bug/HEALTH-1566\nHEALTH-1566: record key down time in one central place\nMerge pull request #360 from MindStrongHealth/HEALTH-1474-1\nChart series should run flat in the end if empty points", :LATEST_BUILD_NUMBER=>177, :LATEST_TESTFLIGHT_BUILD_NUMBER=>177}
ERROR [2018-06-19 21:20:26.52]: Error building the application - see the log above
INFO [2018-06-19 21:20:26.52]: Successfully generated documentation at path '/Users/Shared/Jenkins/Home/workspace/ios-build/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 0           |
| 2    | default_platform       | 0           |
| 3    | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 4    | cd ../;git log         | 0           |
|      | --pretty=format:'%s    |             |
|      | %h' | grep -i          |             |
|      | '^version bu           |             |
| 5    | git rev-parse HEAD     | 0           |
| 6    | latest_testflight_bui  | 21          |
|      | ld_number              |             |
| 7    | increment_build_numbe  | 0           |
|      | r                      |             |
| 💥   | gym                    | 61          |
+------+------------------------+-------------+

Here is what happens:

It fails with this error and then it proceeds to building again. The log files gets over written during the course of building.

**Comment by joshdholtz** [comment]
@sprabhuanand I don't think just having this portion of your output will allow me to help you out at all. In order to get a better understanding of what is going on it would be best to have the whole output (from start to finish) and what your complete `Fastfile` looks like. 

_fastlane_ won't execute anything after an action (like `gym`) fails so there is no way that **IF** you are calling `deliver` after `gym` (which I don't know if you are) that any sort of app upload would happen.

It does look like you are Jenkins so I'm guessing this may be a configuration issue within your Jenkins setup? Hard to know since I don't have full information to go on 🙃
