### ISSUE TITLE
deliver puts the Preview.html file in the root project folder rather than in the fastlane folder. 

### ISSUE THREAD

**Issue by simonbromberg** [fastlane/fastlane#12772]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I just noticed that `deliver` puts the Preview.html file in the root project folder rather than in the "fastlane" folder. By default, fastlane put this in my .gitignore when I ran init:

    # deliver temporary files
    fastlane/Preview.html

But since it puts the Preview.html file in the root folder, it is showing up as a change in git. Plus it's better to put it in the fastlane folder for organization purposes.

##### Complete output when running fastlane, including the stack trace and command used
Not applicable

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["GET_PRODUCT_BUNDLE_ID_PROJECT_PATH"] = "DashMD.xcodeproj"

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight (use fastlane beta --env development for dev app)"
  lane :beta do |options|
    app_target = ENV["APP_TARGET"]
    app_scheme = ENV["APP_SCHEME"]

    version = prompt(
      text: "Type in desired version (currently " + get_version_number(target: app_target) + "):",
    )

    changelog = prompt(
      text: "Paste in changelog:",
      multi_line_end_keyword: "END"
    )

    distribute = prompt(
      text: "Distribute to external testers?",
      boolean: true
    )

    increment_version_number_in_plist(version_number: version, target: app_target)

    testflight_build_number = latest_testflight_build_number(version: get_version_number(target: app_target))
    increment_build_number(build_number: testflight_build_number + 1)

    if !options[:skip_build]
      build_app(workspace: "DashMD.xcworkspace", scheme: app_scheme)
    end

    upload_to_testflight(app_identifier: ENV["APP_IDENTIFIER"], changelog: changelog, distribute_external: distribute)
  end

  desc "Push a new release build to App Store Connect (update release notes in metadata)"
  lane :release do |options|
    app_target = ENV["APP_TARGET"]
    app_scheme = ENV["APP_SCHEME"]

    version = prompt(
      text: "Type in desired version (currently " + get_version_number(target: app_target) + "):",
    )

    should_review = prompt(
      text: "Should the build be submitted for review?",
      boolean: true
    )

    increment_version_number_in_plist(version_number: version, target: app_target)

    testflight_build_number = latest_testflight_build_number(version: get_version_number(target: app_target))
    increment_build_number(build_number: testflight_build_number + 1)

    if !options[:skip_build]
      build_app(workspace: "DashMD.xcworkspace", scheme: app_scheme)
    end

    deliver(submit_for_review: should_review)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id ENV["DASHMD_APPLE_ID"] # Your Apple ID
# Add export DASHMD_APPLE_ID="USERNAME@dashmd.co" (replacing USERNAME) to your ~/.bash_profile
# to load your Apple ID into your local bash profile

itc_team_id("118296251") # iTunes Connect Team ID
team_id("V8B22HRKPX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.98.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.1.0        |
| executable-hooks           | 1.3.2        |
| bundler-unload             | 1.0.2        |
| rubygems-bundler           | 1.4.4        |
| bundler                    | 1.16.2       |
| io-console                 | 0.4.6        |
| CFPropertyList             | 3.0.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| atomos                     | 0.1.2        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| unf_ext                    | 0.0.7.5      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| dotenv                     | 2.4.0        |
| emoji_regex                | 0.1.1        |
| excon                      | 0.62.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.15.2       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.12.2       |
| fastimage                  | 2.1.3        |
| gh_inspector               | 1.1.3        |
| jwt                        | 2.1.0        |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.13.1       |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.2        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.21.2       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.4.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.4        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.4.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.6.4        |
| tty-cursor                 | 0.5.0        |
| tty-spinner                | 0.8.0        |
| word_wrap                  | 1.0.0        |
| nanaimo                    | 0.2.5        |
| xcodeproj                  | 1.5.9        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-versioning | 0.3.4        |
</details>

*generated on:* **2018-06-19**
</details>

**Comment by ericmarkmartin** [comment]
+1

**Comment by joshdholtz** [comment]
@simonbromberg PR created for this ^

**Comment by sameeragrawal** [comment]
Need to reopen the issue to track the problem reported by @hons82
