### ISSUE TITLE
Upload symbol to crashlytics action uploads the first dSYM file it finds.

### ISSUE THREAD

**Issue by nishantdesai** [fastlane/fastlane#12774]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using the `upload_symbols_to_crashlytics` without the path for the dSYM specified, if there are a number of dSYM (app, embedded frameworks) present in the default location, it selects the first dSYM and uploads it to crashlytics.
It should be uploading all the dSYM generated to crashlytics. 

Also, If I'm not wrong, while using the `hockey` action to upload dSYM and IPA, it uploads all the dSYMs generated during the build.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.96.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| rake                      | 12.3.1       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.4        |
| fastimage                 | 2.1.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.3        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.9.1        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.16.2       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.9.0        |
| danger                    | 5.5.13       |
| thor                      | 0.20.0       |
| danger-swiftlint          | 0.17.0       |
</details>

*generated on:* **2018-06-20**
</details>

**Comment by joshdholtz** [comment]
@nishantdesai `upload_symbols_to_crashlytics`is definitely supposed to upload multiple dsym files which can be seen here - https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb#L17-L37

Can you verify that you have all the paths that you are expecting in your `Actions.lane_context[SharedValues::DSYM_PATHS]`?

**Comment by nishantdesai** [comment]
Oh right it already has that ability. The way I was using it was that I wasn't supplying any `dsym_path` parameter since the dsym files were already in the default location.

>Can you verify that you have all the paths that you are expecting in your Actions.lane_context[SharedValues::DSYM_PATHS]?

Also, I'm not sure that how can I verify this.

**Comment by joshdholtz** [comment]
@nishantdesai Are you using the `download_dsyms` action? This action sets the `DSYM_PATHS` context automatically for you. If you are, just put the following line before your call to `upload_symbols_to_crashlytics` to see what the value is. It should be an array of paths.

```rb
puts "dsym paths: #{Actions.lane_context[SharedValues::DSYM_PATHS]}"
```

And if you aren't supplying any `dsym_path` to it, it will default from the `Actions.lane_context[SharedValues::DSYM_PATHS]` as well as... https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb#L147
- `ENV[SharedValues::DSYM_OUTPUT_PATH.to_s]`
- `(Dir["./**/*.dSYM"] + Dir["./**/*.dSYM.zip"]).sort_by { |f| File.mtime(f) }.last`

If nothing is getting automatically passed into it, you may have to do it manually. I don't know your setup so I can't give much more help other than that 🙃 But if you give it a `dSYM.zip` (which contains many dSYM files), you should be good 👍

**Comment by nishantdesai** [comment]
@joshdholtz, Thank you! Eended up using `download_dsyms` action so everything is working as expected. Although, I still have a doubt.
> And if you aren't supplying any dsym_path to it, it will default from the Actions.lane_context[SharedValues::DSYM_PATHS]

I have a bunch of frameworks integrated so a few dSYM files are generated. https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb#L147 <- I think this is unable to find anything from the context so it's just picking up the first dSYM file it finds (no dSYM.zip is available) and just uploads that.
In my case, the first dSYM found is of a framework.

If you want to reproduce have multiple dSYM in the default location and use the upload action without passing in the path or the context.

**Comment by joshdholtz** [comment]
@nishantdesai I _think_ that make sense since the action options is named singular `dsym_path` but that doesn't make things for easy for if you do have a multiple dSYM that you need to upload.  I think I will change this up because it is a bit confusing 🤔
