### ISSUE TITLE
scan log output not showing warnings or analyser issues

### ISSUE THREAD

**Issue by alexito4** [fastlane/fastlane#12780]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
`scan` log output not showing warnings or analyser issues

#### Question Description

While using scan to run tests in the CI on every PR the log file generated doesn't contain the warnings.

```  
 scan(
             scheme: ...,
             devices: ...,
             formatter: "xcpretty-json-formatter",
             output_types: "html,junit,json-compilation-database"
        )
```

After running that, checking the Xcode generated .log file and the part where it builds the scheme it just says "** BUILD SUCCEEDED **" with not data of the compilation of every single file. That means that https://github.com/marcelofabri/xcpretty-json-formatter doesn't have access to that date so the output JSON it only contains the summary of the tests.
When building that same scheme from Xcode warnings and analyser issues show up as expected. 

**Expected behaviour:**

Running `scan` should output warnings and analyser issues so other tools can use that. 

**The end goal:**

My end goal is to use https://github.com/danger/danger to fail a PR if warnings are introduced. The plan is to use scan with xcpretty-json-formatter so then I can read the JSON from danger and show the results in the PR. 
If somebody has a better idea on how to accomplish this I'm all 👂:D

**Comment by joshdholtz** [comment]
@alexito4 Heyyyyy 👋 

You _should_ be able to show warnings with _xcpretty_ by specifying a custom formatter - https://github.com/supermarin/xcpretty/blob/master/lib/xcpretty/formatters/formatter.rb

```rb
# Fastfile
lane :test do
  scan(
    formatter: "./fastlane/custom_formatter.rb"
  )
end
```

```rb
# customer_formatter.rb
class JoshCityFormatter < XCPretty::Simple

  # other method overrides go here

  def format_warning(message)
    "###customer_formatter[warning] '#{message}'"
  end
end
```

I _think_ you should be able to use Danger to look for this message format then ^ 😊

**Comment by alexito4** [comment]
Thanks @joshdholtz . Sorry for not coming back to this until now, I was on holidays and just now had time to look into it again.

I finally found what the issue was. When I was running `scan` locally on my machine to test the integration with danger, the incremental compilation was being used so it was just running the tests. Because no file was compiled no warnings were output and thus `xcpretty-json-formatter` was not reporting anything. 

So the issue is solved, was totally an oversight on my part. 😅

---

Now, before I found that that was the issue I tried many things and found some issues, I will write them here for posterity.

You pointed me to an interesting solution, using a custom formatter, I looked into that but I’ve run into some problems. The issue is that if I specify a ruby file as the formatter fastlane keeps throwing errors at me like if the ruby file was wrong (but the file I was using was fine as it was copied from another project. I have the feeling that is because it was being run with "sh ...." so ruby wasn't being used. I didn't investigate further.

What made me ditch this is that everything seemed to point that xcpretty-json-formatter was already gathering the warnings. https://github.com/marcelofabri/xcpretty-json-formatter/blob/master/lib/json_formatter.rb#L34

To discard issues with scan I wanted to run gym with the json formatter.

Then I found an interesting issue:

gym doesn’t work when you use ""xcpretty-json-formatter”” you need to point directly to the .rb file of the gem. 
```
gym(
 # xcpretty_formatter: "xcpretty-json-formatter"  THIS DOESN'T WORK
 xcpretty_formatter: "...rvm/gems/ruby-2.3.3/gems/xcpretty-json-formatter-0.1.0/lib/json_formatter.rb" # THIS WORKS
)
```
Instead scan works just by specifying the gem name. (and in fact it doesn't seem to work when a file is given, as explained above)
```
scan(
 formatter: "xcpretty-json-formatter"
)
```

When running gym I was seeing the correct warnings in the JSON, after a bit I realised that it was due to the incremental compilation. With that JSON there is easy to report the warnings with danger. In case somebody is interested this is what do:

```
# Build Status
file = "./build/reports/errors.json"
json = JSON.parse(File.open(file, 'r').read)

warnings_count = (json["warnings"] + json["ld_warnings"] + json["compile_warnings"])
.map { |w| w["file_path"] }
.compact
.select { |p| p.include? "l" } # this is to ignore warnings from Pods, to workaround a Cocoapods issue.
.count

if warnings_count > 0
warnings_string = warnings_count == 1 ? "warning" : "warnings"
fail("Please fix **#{warnings_count}** #{warnings_string} ⚠️")
end
```

----

I'm closing the issue as it was just a mistake on my part. 
Thanks for the help. 👍
