### ISSUE TITLE
Waiting iTunes Connect processing for build got 504

### ISSUE THREAD

**Issue by foxsofter** [fastlane/fastlane#12785]
/Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/spaceship/lib/spaceship/client.rb:597:in `parse_response': [31m[!] <html>
 (Spaceship::UnexpectedResponse)
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
[0m

<details>
  <pre>/Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/spaceship/lib/spaceship/client.rb:597:in `parse_response': [31m[!] <html>
 (Spaceship::UnexpectedResponse)
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
[0m
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/spaceship/lib/spaceship/tunes/tunes_client.rb:384:in `app_version'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/spaceship/lib/spaceship/tunes/app_version.rb:282:in `find'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/spaceship/lib/spaceship/tunes/application.rb:125:in `edit_version'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/spaceship/lib/spaceship/tunes/application.rb:131:in `latest_version'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/submit_for_review.rb:60:in `block in wait_for_build'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/submit_for_review.rb:59:in `loop'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/submit_for_review.rb:59:in `wait_for_build'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/submit_for_review.rb:44:in `select_build'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/runner.rb:172:in `submit_for_review'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:124:in `block (2 levels) in parsing_binding'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/foxsofter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.98.0/bin/fastlane:20:in `<top (required)>'
	from /Users/foxsofter/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
	from /Users/foxsofter/.rbenv/versions/2.3.3/bin/fastlane:22:in `<main>'
Build step 'Execute shell' marked build as failure
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.0                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

update_fastlane

default_platform(:ios)

platform :ios do

    desc "Archive ipa package for test"
    lane :beta_development do
        # add actions here: https://docs.fastlane.tools/actions
        sh "git checkout ."
        sh "git checkout develop"
        sh "git pull"
        increment_build_number
        gym(
            scheme: "YHYProject",
            workspace: "YHYProject.xcworkspace",
            clean: true,                        # 清空上次打包信息
            export_method: "development",       # app-store, ad-hoc, package, enterprise, development, developer-id
            configuration: "Debug",             # Debug or Release
            output_directory: "build/beta/",
            output_name: "yhy.ipa"
        )
        enable_automatic_code_signing(path: "YHYProject.xcodeproj")
    end

    desc "Archive ipa package for test and upload to pgyer"
    lane :beta_pgyer do beta_development
        # add actions here: https://docs.fastlane.tools/actions
        pgyer(api_key: "43956ec6f8a23a4acc6a95b8e3a3a7c9", user_key: "223959aa7c1b40619b606d2c33163dd4")

        version = get_version_number(xcodeproj: "YHYProject.xcodeproj")
        build_number = get_build_number(xcodeproj: "YHYProject.xcodeproj")
        tag_string = "pgyer_" + version + "_" + build_number

        git_add(path: ".")
        git_commit(path: ".", message: tag_string)
        sh "git push"
        add_git_tag(tag: tag_string)
        sh "git push origin --tags"
        
        clean_build_artifacts
        clear_derived_data
    end

    desc "Archive ipa package for prod"
    lane :prod_development do
        # add actions here: https://docs.fastlane.tools/actions
        sh "git fetch"
        sh "git checkout develop"
        sh "git pull"
        increment_build_number
        gym(
            scheme: "YHYProject",
            workspace: "YHYProject.xcworkspace",
            clean: true,                        # 清空上次打包信息
            export_method: "development",       # app-store, ad-hoc, package, enterprise, development, developer-id
            configuration: "Release",           # Debug or Release
            output_directory: "build/prod/",
            output_name: "yhy.ipa"
        )
        enable_automatic_code_signing(path: "YHYProject.xcodeproj")
    end

    desc "Archive ipa package for test and upload to fir"
    lane :prod_fir do prod_development
        # add actions here: https://docs.fastlane.tools/actions
        firim(firim_api_token: "dc12423b31a9e310ee4b4fccbf7f882b")

        version = get_version_number(xcodeproj: "YHYProject.xcodeproj")
        build_number = get_build_number(xcodeproj: "YHYProject.xcodeproj")
        tag_string = "fir_" + version + "_" + build_number
     
        git_add(path: ".")
        git_commit(path: ".", message: tag_string)
        sh "git push"
        add_git_tag(tag: tag_string)
        sh "git push origin --tags"
        
        clean_build_artifacts
        clear_derived_data
    end

    desc "Archive ipa package for appstore"
    lane :prod_appstore do
        # add actions here: https://docs.fastlane.tools/actions

        sh "git fetch"
        sh "git checkout develop"
        sh "git pull"
        increment_build_number
        gym(
            scheme: "YHYProject",
            workspace: "YHYProject.xcworkspace",
            clean: true,                                # 清空上次打包信息
            export_method: "app-store",                 # app-store, ad-hoc, package, enterprise, development, developer-id
            export_xcargs: "-allowProvisioningUpdates",
            configuration: "Release",                   # Debug or Release
            output_directory: "build/appstore/",
            output_name: "yhy.ipa"
        )
        enable_automatic_code_signing(path: "YHYProject.xcodeproj")
    end

    desc "Archive ipa package for test and upload to appstore"
    lane :itunes do prod_appstore
        # add actions here: https://docs.fastlane.tools/actions
        version = get_version_number(xcodeproj: "YHYProject.xcodeproj")
        build_number = get_build_number(xcodeproj: "YHYProject.xcodeproj")

        deliver(force: true, ipa:"./build/appstore/yhy.ipa")
  
        tag_string = "appstore_" + version + "_" + build_number
  
        git_add(path: ".")
        git_commit(path: ".", message: tag_string)
        sh "git push"
        add_git_tag(tag: tag_string)
        sh "git push origin --tags"
  
        clean_build_artifacts
        clear_derived_data
        
    end

    desc "Archive ipa package for testflight"
    lane :beta_appstore do
        # add actions here: https://docs.fastlane.tools/actions
        sh "git fetch"
        sh "git checkout develop"
        sh "git pull"          
        increment_build_number
        gym(
            scheme: "YHYProject",
            workspace: "YHYProject.xcworkspace",
            clean: true,                                # 清空上次打包信息
            export_method: "app-store",                 # app-store, ad-hoc, package, enterprise, development, developer-id
            export_xcargs: "-allowProvisioningUpdates",
            configuration: "Debug",                   # Debug or Release
            output_directory: "build/testflight/",
            output_name: "yhy.ipa"
        )
        enable_automatic_code_signing(path: "YHYProject.xcodeproj")
    end

    desc "Archive ipa package for test and upload to testflight"
    lane :beta_testflight do beta_appstore
        # add actions here: https://docs.fastlane.tools/actions
        pilot

        version = get_version_number(xcodeproj: "YHYProject.xcodeproj")
        build_number = get_build_number(xcodeproj: "YHYProject.xcodeproj")
        tag_string = "testflight_" + version + "_" + build_number

        git_add(path: ".")
        git_commit(path: ".", message: tag_string)
        sh "git push"
        add_git_tag(tag: tag_string)
        sh "git push origin --tags"
        
        clean_build_artifacts
        clear_derived_data

    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

apple_id "appledeveloper@quncaotech.com" 
app_identifier "com.quncaotech.lark.participator"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.98.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-firim | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| faraday_middleware        | 0.12.2       |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| faraday                   | 0.15.2       |
| json                      | 2.1.0        |
| bundler                   | 1.16.2       |
| unicode-display_width     | 1.3.3        |
| fastlane-plugin-pgyer     | 0.2.1        |
| fastlane-plugin-firim     | 0.2.0        |
</details>

*generated on:* **2018-06-22**
</details></pre>
</details>

**Comment by wanyakun** [comment]
got the same error

**Comment by wanyakun** [comment]
@foxsofter how to fixed it?

**Comment by saitjr** [comment]
got the same error
