### ISSUE TITLE
fastlane running lane from my own web page

### ISSUE THREAD

**Issue by SSamanta** [fastlane/fastlane#1278]
Guys,

You have done a great job!. It's really awesome.
I would like to develop my own web page where my project manager will have access that page from Internet. The page will display different lanes which is in Fastfile like "beta" , "appstore". 

So when manager will go to the page and will click on "beta" it will run beta lane of fastlane. Currently Developer have to run it on his own Mac terminal. I would like to be controlled from any webpage.

Are there any setups or tools?

**Comment by KrauseFx** [comment]
Sure that works, you just need your own CI machine or Mac in the cloud to host fastlane and trigger the lane using any kind of hook

**Comment by Wojcik** [comment]
Maybe this can help http://stackoverflow.com/questions/20433552/how-do-i-run-a-ruby-script-from-a-webpage second result from the google btw

**Comment by SSamanta** [comment]
@KrauseFx Thanks..closing it..
