### ISSUE TITLE
Could Not Determine Installed IOS SDK

### ISSUE THREAD

**Issue by OlyRice** [fastlane/fastlane#12784]
** Sorry just spotted that I should have used a template for this question **

Hi
Just installed a fresh version of Fastlane on my Mac and Xcode 9.4 to take screenshots and after following the guide I get the following error message.

> [!] Could not determine installed iOS SDK version. Try running the _xcodebuild_ command manually to ensure it works.

Automatic init failed and after a few attempts I decided to opt for a manual file to see if that would work but I am still getting the same error. I have installed Xcode Tools and checked for updates, none are needed. 

> /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Could not determine installed iOS SDK version. Try running the _xcodebuild_ command manually to ensure it works. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/latest_os_version.rb:26:in `version_for_os'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/latest_os_version.rb:13:in `version'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/latest_os_version.rb:8:in `ios_version'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/dependency_checker.rb:32:in `check_xcode_select'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/dependency_checker.rb:11:in `check_dependencies'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/module.rb:39:in `<module:Snapshot>'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/module.rb:6:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/runner.rb:8:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot/runner.rb:8:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot.rb:1:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/snapshot/lib/snapshot.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/cli_tools_distributor.rb:81:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.98.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
Olivers-iMac:Printly oliverrice$ 

Builds are normal when testing on IPhone and simulator so Im a bit stuck.

Any ideas?

Thanks

**Comment by bartekhugo** [comment]
Do you have set your Command line tools pointing to current version?

**Comment by shardulsrivastava** [comment]
@OlyRice can you run `fastlane env` and provide the output. It will helpful to understand the issue here.

**Comment by joshdholtz** [comment]
@OlyRice It sounds like you may need to run `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

The output you are getting is coming from _fastlane_ executing `xcodebuild -version -sdk` and trying to parse that to get all the info it needs for what version of iOS and things you have installed. _fastlane_ isn't able to successfully execute that command so it sounds like that you don't have an Xcode version selected for `xcodebuild` to run things with. Running the `xcode-select` command above should do the trick for you 👌
