### ISSUE TITLE
Invalid Build number.

### ISSUE THREAD

**Issue by sarunw** [fastlane/fastlane#1279]
Today I got this error.

`
Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (25) that’s lower than the latest build number (291) that’s been submitted for the app version '1.0.0'.
`

Which state that build number is lower than the one on iTunesconnect, but I didn't change fastfile or circle.yml recently. Any one got this problem recently?

I have no clue where this 25 build number coming from, In my info.plist it was 143 and I have build phase run script that update it and it used to work.

*Here is my fastfile*

```
platform :ios do
  before_all do
    cocoapods
    ENV['KEYCHAIN_NAME'] = "TempKeychain.keychain"
    # increment_build_number
    # set_info_plist_value(path: "./MY_PROJECT_NAME/Info.plist", key: "CFBundleVersion", value: "99") I have try this but it won't set build number to 99
    # xctool # run the tests of your app
  end
 
  desc "Submit a new Beta Build for client"
  lane :production do
    # snapshot
    import_certificates
    sigh
    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    gym(scheme: "MY_PROJECT_NAME") # Build your app - more options available
    pilot(skip_submission: true)
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

 
end
```

**Comment by mfurtak** [comment]
Hi @sarunw - is it possible that your CFBundleVersion has been modified for some targets but not all of them? `sigh` and `pilot` shouldn't be involved in changing this value. :+1:

**Comment by KrauseFx** [comment]
Could you share the complete output when running fastlane? This might be due to a wrong path for the Info.plist.

**Comment by sarunw** [comment]
Sorry :( my bad. It turn out to be circleci behavior https://discuss.circleci.com/t/git-rev-list-head-count-gives-strange-results-on-circleci-server/654

My script use that git rev as a build number.
