### ISSUE TITLE
Can we build iOS project in Jenkins by using docker in fastlane.

### ISSUE THREAD

**Issue by Aravindios** [fastlane/fastlane#12791]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
  docker inside  Jenkins can we use fast lane code to build iOS project 
[ no,
 yes]

#### Question Description
 I want to build iOS project in Jenkins by using docker in fastlane code if it's possible can any one help.
thank you.....

**Comment by joshdholtz** [comment]
@Aravindios fastlane will only be able to build an iOS app in an macOS environment. So if you docker container is using macOS then you should be able to do that. I don't know how much more I am able since this sounds like a pretty specific use case 😊

**Comment by shardulsrivastava** [comment]
@Aravindios we also explored the possibilities of this. but stopped since it was not worth the effort.

If you want to explore on this, you may want to look at this 

https://github.com/jkingyens/docker4xcode

It implements a REST API to simulate a docker server.
