### ISSUE TITLE
Unable to capture screenshot

### ISSUE THREAD

**Issue by ViktorBylbas** [fastlane/fastlane#12804]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

java.lang.RuntimeException: Unable to capture screenshot.

#### Question Description

I get exception after start test:

> Running tests
> 
> $ adb shell am instrument -w -r   -e debug false -e class 'com.test.helloworld.app.MainActivityTest' com.test.helloworld.app.test/android.support.test.runner.AndroidJUnitRunner
> Client not ready yet..
> Started running tests
> 
> java.lang.RuntimeException: Unable to capture screenshot.
> at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
> at tools.fastlane.screengrab.FalconScreenshotStrategy.takeScreenshot(FalconScreenshotStrategy.java:24)
> at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
> at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
> at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
> at com.test.helloworld.app.MainActivityTest.testTakeScreenshot(MainActivityTest.java:41)
> at java.lang.reflect.Method.invoke(Native Method)
> at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
> at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
> at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:32)
> at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> at org.junit.runners.Suite.runChild(Suite.java:128)
> at org.junit.runners.Suite.runChild(Suite.java:27)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
> at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
> at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
> at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1962)
> Caused by: java.io.IOException: Unable to get a screenshot storage directory
> at tools.fastlane.screengrab.FileWritingScreenshotCallback.getFilesDirectory(FileWritingScreenshotCallback.java:81)
> at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:39)
> ... 37 more
> 
> Tests ran to completion.

My tests:

    @RunWith(JUnit4.class)
     public class MainActivityTest {
        @ClassRule
         public static final LocaleTestRule localeTestRule = new LocaleTestRule();

        @Rule
         public ActivityTestRule<MainActivity> activityRule = new ActivityTestRule<>(MainActivity.class);

        @Test
        public void testTakeScreenshot() {
             Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
            Screengrab.screenshot("Main");
        }
    }

What is the problem?

**Comment by anh1979** [comment]
I am also encountering this - I am just writing the test class in Android Studio using FalconScreenshotStrategy) and when I call
`Screengrab.screenshot("main_menu");`
it crashes, telling me "Unable to get a screenshot storage directory". I am using "Pixel" as emulator.
Also in the stack trace I find:
"Failed to initialize directory: /storage/emulated/0/our.package.name/screengrab/en-US/images/screenshots
              java.io.IOException: Unable to create output dir: /storage/emulated/0/our.package.name"

Any hints about this?

**Comment by anh1979** [comment]
Perhaps related to this issue: [https://github.com/fastlane/fastlane/issues/8727](url)

**Comment by ppamorim** [comment]
Any solution on this?

**Comment by anh1979** [comment]
By the way I managed to get it working using another device (Nexus instead of Pixel as far as I remember). I don't know what the real problem was, maybe configuration details...
