### ISSUE TITLE
Is there an option to pass parameters from bash into error lane?

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#1280]

**Comment by KrauseFx** [comment]
Have you tried
```ruby
error do |lane, ex, options|
  puts options[:something]
end
```
```sh
fastlane lane something:my_value
```

**Comment by nmayafit** [comment]
Yes.
This is what I did:

In Jenkins I have shell script:
echo "user name is ${BUILD_USER}"
fastlane test_hockeyapp username:${BUILD_USER}

The result in jenkins console:
+ echo 'user name is anonymous'
user name is anonymous
+ fastlane test_hockeyapp username:anonymous

My Fastfile lane:
error do |lane, exception, **options**|
  	Helper.log.info 'Moving to Error lane'.red
  	version     = get_version_number(xcodeproj: "xxxx.xcodeproj")
    slack(
       	slack_url: ENV['SLACK_URL'],
       	message: "*Error* in `iOS` deployment *#{version}* in lane *#{lane}* with message: *#{exception.message}* :hankey:",
       	channel: "#xxxx",  # Optional, by default will post to the default channel configured for the POST URL.
       	success: false,
       	payload: {            # Optional, lets you specify any number of your own Slack attachments.
    		'Build Date' => Time.new.to_s,
    		'Built by' => '**options[:username]**',
  		},
  		default_payloads: [:lane, :test_result, :git_branch],
	 )
	 reset_git_repo
  end

The result in Slack:
New `iOS` ​*1.6.3(TE3134)*​ running `xxxx Test` has been submitted to ​*Hockeyapp*​  :rocket:
Build Date
----------------
2016-02-09 10:08:10 +0200

Built by
----------------
**options[:username]**

Lane
----------------
ios test_hockeyapp

Result
----------------
Success

Git Branch
----------------
origin/xxxx

**Comment by nmayafit** [comment]
Also its not working in regular lanes also.

**Comment by nmayafit** [comment]
ok, I found the error.
Had to move the apostrophes from the 'Built by' => 'options[:username]', So now its like:
'Built by' => options[:username]

**Comment by i2amsam** [comment]
@nmayafit great!  Glad you figured it out!  I'm going to close this issue, feel free to re-open if there is something I missed.
