### ISSUE TITLE
Export archive takes more than 1 hour

### ISSUE THREAD

**Issue by marian19** [fastlane/fastlane#12819]
### Issue Description
Export archive takes more than 1 hour 
Xcode 9.2

cert
  sigh(force: true)
build_app(
  scheme: "###",
    workspace: "###.xcworkspace",
    output_directory: "./fastlane/Archives",
    silent: true,
      clean: true,
      export_method: "enterprise",
include_bitcode: false,
    export_options: {
      method: "enterprise",
      compileBitcode: false,
uploadBitcode: false,
    uploadSymbols: true
    }
  )

### Environment

<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | 10.13.4                                                      |
| Ruby                        | 2.2.4                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.14.3 (Apple Git-98)                            |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                          |
| Host                        | Mac OS X 10.13.4 (17E199)                                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                                   |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                   |
| Is contained                | true                                                         |
| Is homebrew                 | false                                                        |
| Is installed via Fabric.app | false                                                        |
| Xcode Path                  | /Volumes/External/Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.98.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.10       |
| addressable               | 2.5.1        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.5.3        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| concurrent-ruby           | 1.0.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 0.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.21.2       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.9.5        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.6.5        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.5        |
| nap                       | 1.1.0        |
| naturally                 | 2.1.0        |
| netrc                     | 0.11.0       |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| ruby-macho                | 1.2.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-spinner               | 0.8.0        |
| tzinfo                    | 1.2.5        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-06-29**
</details>
</details>

**Comment by shardulsrivastava** [comment]
@marian19 it will be helful if you paste the logs as well, it will help us to understand the problem.

I also faced an issue somewhat similar to yours but in my case it got stuck forever.

Once work around will be to try to use xcodebuild and xcexport actions 
```
lane :beta do
 xcodebuild(
  archive: true,
  archive_path: "blueprint.xcarchive",
  scheme: "blueprint",
  workspace: "blueprint.xcworkspace"
  )
  xcexport(
  archive_path: "blueprint.xcarchive",
  export_options_plist: "exportOptions.plist",
  export_path: "."
  )
```

**Comment by marian19** [comment]
what's the exportOptions.plist?

**Comment by marian19** [comment]
what's the exportOptions.plist?
