### ISSUE TITLE
Using fastlane with an app that uses a notification extension

### ISSUE THREAD

**Issue by yusuftor** [fastlane/fastlane#12826]
I am using fastlane to build and send my app to testflight. This worked until I added a Notification Extension. Now it always gives me the error:

> Error Domain=IDEProvisioningErrorDomain Code=9 ""OneSignalNotificationServiceExtension.appex" requires a provisioning profile with the App Groups feature." UserInfo={NSLocalizedDescription="OneSignalNotificationServiceExtension.appex" requires a provisioning profile with the App Groups feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

Everything is supposed to be handled automatically on Xcode, and my fastfile looks like this:

```
default_platform(:ios)

platform :ios do
  before_all do
    increment_build_number
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(workspace: "MyApp.xcworkspace", scheme: "MyApp (Production)")
    pilot(skip_waiting_for_build_processing: true)
  end
end
```

My bundle identifier for my app is like com.myapp.ios and my bundle identifier for my notification service is like com.myapp.ios.notificationservice.

I've tried creating multiple provisioning profiles for the different bundle identifiers manually, but fastlane only selects one. How can I fix this?

**Comment by RishabhTayal** [comment]
@yusuftor I think you need to specify the provisioning profile mapping to `build_app` like this.

```
gym(
      scheme: 'MyApp (Production)',
      export_options: {
        provisioningProfiles: {
          "com.myapp.ios" => ENV["sigh_com.myapp.ios_appstore_profile-name"],
          "com.myapp.ios.notificationservice" => ENV["sigh_com.myapp.ios.notificationservice.NotificationServiceExtension_appstore_profile-name"]
        }
      }
    )
```

**Comment by slorber** [comment]
Hi,

I have the exact same problem with a ReactNative app and OneSignal,  not sure how to sign that extension with fastlane.

> error: exportArchive: "OneSignalNotificationServiceExtension.appex" requires a provisioning profile.

I'm trying to use Match to create the provisioning profile but without success so far

```
    match(
        app_identifier: ["com.x.mobile","com.x.mobile.OneSignalNotificationServiceExtension"],
        type: "appstore",
    )
```

> [!] Couldn't find bundle identifier 'com.x.mobile.OneSignalNotificationServiceExtension' for the user 'tech@x.in'

**Comment by yusuftor** [comment]
@RishabhTayal was right, I managed to get it working by using the following:

```
build_app(workspace: "MyApp.xcworkspace", 
	scheme: "MyApp (Production)", 
	export_method: "app-store",
    	export_options: {
     		provisioningProfiles: { 
        		"com.MyApp.ios" => "com.MyApp.ios AppStore 1900397498",
        		"com.MyApp.ios.OneSignalNotificationServiceExtension" => "My App Notification Extension Provisioning Profile"
      		}
    	})
```

Just make sure you manually create the provisioning profile for your extension online. Hope this helps

**Comment by slorber** [comment]
@yusuftor good for you. I'm managing certs with match and just found a solution that seems to work so far, based on https://github.com/fastlane/fastlane/issues/8563

```
  desc "Prepare the iOS app for dev or build"
  lane :prepare do
    produce(
        app_identifier: "com.x.mobile.OneSignalNotificationServiceExtension",
        app_name: "x OneSignalNotificationServiceExtension",
        skip_itc: true
    )
    match(
        app_identifier: ["com.x.mobile","com.x.mobile.OneSignalNotificationServiceExtension"],
        type: "development",
    )
    match(
        app_identifier: ["com.x.mobile","com.x.mobile.OneSignalNotificationServiceExtension"],
        type: "appstore",
    )
    cocoapods
  end
```

Hope this will be helpful
