### ISSUE TITLE
"Release Version" functionality

### ISSUE THREAD

**Issue by gerbil802** [fastlane/fastlane#12827]
### Feature Request

Hi,
I'm interested in the ability to release a version with fastlane. i.e. when a version is submitted, reviewed and approved I'd like a lane that simply releases the app to the App Store.

#### Motivation Behind Feature
This allows to automate timely releases regardless to whenever they were submitted. 

#### Feature Description
I would think deliver is the tool for this, however it may be focused on _submitting_. 
Whatever command this would be - it should release a reviewed version, unless there isn't a version available for release. Can't see drawbacks.

#### Alternatives or Workarounds
Right now it's only going into iTunesConnect website or app.

**Comment by RishabhTayal** [comment]
@gerbil802 `spaceship` already has the implementation for this.

https://github.com/fastlane/fastlane/blob/442f151d9180a19f9d79caa4d5872166d12d122e/spaceship/lib/spaceship/tunes/app_version.rb#L623-L623

**Comment by gerbil802** [comment]
Thank you!
