### ISSUE TITLE
Make Match use existing certificate or add the ability to specify a certificate to user 

### ISSUE THREAD

**Issue by tundsD53** [fastlane/fastlane#12838]
#### Motivation Behind Feature

When creating a new project using the match action a new certificate is generated every time, it would be useful/handy if the match action was smart enough to pick up the fact that a certificate exists rather than creating a new distribution or development certificate which will invalidate provisioning profiles.

#### Alternatives or Workarounds

An alternative would be to add a parameter where you can specify a certificate that already exists otherwise fastlane will create a new one.

**Comment by tigran-stdev** [comment]
Due to this limitation, we can't have more than 3 apps with the same dev accounts as per Apple limitations you can have up to 3 distribution certificates for Individual accounts.

Could you please suggest any workaround for now until we can have this feature?

Thanks.

**Comment by HIIgor** [comment]
@tigran-stdev  @tundsD53 I don't know if this tool will solve your problem perfectly.

https://github.com/HIIgor/match_certs_migration

**Comment by tundsD53** [comment]
@Hllgor looks good, but in your notice you mention about how we have to work with your project structure within our match repo. Doesn’t this work with the default repo structure that the match action provides?

**Comment by HIIgor** [comment]
@tundsD53  The default branch is generated by match. I manually modified his directory structure and deleted his certs directory and provisions directory

**Comment by HIIgor** [comment]
@tundsD53  yes, it can do the thing. I just updated the code, now you can have a try. It will not change any existing repo or branch.

**Comment by tundsD53** [comment]
@HIIgor I'll give it a go and and open an issue if i find anything, good work though mate. This plugin will be super handy.
