### ISSUE TITLE
Fastlane gym does not use provisioning profile set by match

### ISSUE THREAD

**Issue by JCMais** [fastlane/fastlane#12849]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to use fastlane to create an adhoc version of one of our apps from CI, but currently I'm having the following error:

`Code Signing Error: No profile for team '<REDACTED>' matching 'match AppStore <REDACTED>' found:  Xcode couldn't find any provisioning profiles matching '<REDACTED>/match AppStore <REDACTED>'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor`

The thing is, I'm using:
```
    match(type: "adhoc", readonly: true)
    gym(export_method: "ad-hoc")
```

If I understood the docs correctly, gym will use the provisioning profile set by match. However it does not seems to be the case (in reality it does uses, more on this later on).

I'm using the same target for now to create the adhoc `.ipa`, and the project, by default, is set to use the AppStore provisioning profile manually on Xcode, but I thought match would change to the adhoc one automatically, and so I would not need to have this installed.

I've tried many solutions, including the following:
```
    match(type: "adhoc", readonly: true)
    gym(
      export_method: "ad-hoc",
      export_options: {
        method: "ad-hoc",
        signingStyle: "manual",
        provisioningProfiles: {
          "<appid>": "match AdHoc <appid>"
        }
      }
```

But none worked.

**Interesting points:**

1. If I have all provisioning profiles installed, it does work.
2. I've used ProvisionQL to verify which provisioning profile was used to sign the ipa, and it **was** the adhoc one, so it's seems wrong to give an error on missing AppStore one.

###### Related Issues
https://github.com/fastlane/fastlane/issues/10745
https://github.com/fastlane/fastlane/issues/4694
https://github.com/fastlane/fastlane/issues/10458

##### Complete output when running fastlane, including the stack trace and command used
I could not get this using the `--capture_output` flag because of the following error:
> security: SecKeychainItemImport: The specified item already exists in the keychain.
> security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.

So here is the full log: https://gist.github.com/JCMais/1da6d961559719f82168710878caac00

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.6        |
| fastimage                 | 2.1.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.9.1        |
| fastlane-plugin-badge     | 1.1.0        |
| semantic                  | 1.6.1        |
</details>

*generated on:* **2018-07-04**
</details>

**Comment by joshavant** [comment]
I'm experiencing the same problem. The only solution I could find was explicitly calling `match` to trigger the installation of the same identity + provisioning profile assigned for that Build Configuration in the `.xcodeproj` (even if you're configuring Fastlane to build in a way that would not require that profile) AND explicitly specifying the provisioning profile it's expected to use (based on Match auto-configuration) as an `export_option`.

So, in my case, my `.xcodeproj` is configured to build a Build Configuration named `Production` with a `development`-type provisioning profile. However, a lane built the following way would fail, exactly as described in the OP:
```
match(
    app_identifier: "com.foo.bar",
    type: "appstore",
    readonly: true
)

gym(
    workspace: @WORKSPACE_PATH,
    scheme: "Foo",
    configuration: "Production",
    export_method: "app-store"
)
```

I also tried nearly every combination of explicitly specifying all codesigning options, as described [here](https://github.com/fastlane/fastlane/issues/10745#issuecomment-340848177).


Finally, I got it working, but only when I added an additional `match` call that would explicitly trigger loading the identity + profile used in the `.xcodeproj` by the Build Configuration I'm building AND explicitly specifying the desired provisioning profile to use in `export_options`. It looks like this:
```
match(
    app_identifier: "com.foo.bar",
    type: "appstore",
    readonly: true
)

match(
    app_identifier: "com.foo.bar",
    type: "development",
    readonly: true
)

gym(
    workspace: @WORKSPACE_PATH,
    scheme: "Foo",
    configuration: "Production",
    export_method: "app-store",
    export_options: {
        provisioningProfiles: { 
            "com.foo.bar" => "match AppStore com.foo.bar"
        }
    }
)
```

This is using Fastlane 2.99.0 and the host environment was Bitrise VMs (with their auto-codesigning  phase remove.. my workflow was just Activate SSH, Clone, fastlane).

From an outside perspective, my guess is whatever is handling the codesigning at the end of a build is implicitly expecting the identity + profiles configured in the `.xcodeproj` for that Build Configuration to be available and is failing early if they're missing, despite being otherwise validly configured to build in a different configuration that should not depend on those. (Part of me wonders if `xcodebuild` is responsible for the failure, because it's trying to autodetect something that it shouldn't need to be looking for.)

Hope that helps!

**Comment by AliSoftware** [comment]
There are two code signing phases when you archive a build (using Xcode or gym): the code signing identity used when building (in Xcode that's what set in the build settings of your target) and the one used when exporting the archive (the one you select in the export dialog from the organizer when exporting the archive via Xcode manually)

What we do in our Fastfiles is set both to the same value when invoking gym. We override the build settings using xcargs and use there the same signing as the one we set in export_options:

```
match(
    app_identifier: "com.foo.bar",
    type: "appstore",
    readonly: true
)

settings_to_override = {
  :BUNDLE_IDENTIFIER => "com.foo.bar",
  :PROVISIONING_PROFILE_SPECIFIER => "match AppStore com.foo.bar",
  :DEVELOPMENT_TEAM => …
}

gym(
    workspace: @WORKSPACE_PATH,
    scheme: "Foo",
    configuration: "Production",
    xcargs: settings_to_override,
    export_method: "app-store",
    export_options: {
        provisioningProfiles: { 
            "com.foo.bar" => "match AppStore com.foo.bar"
        }
    }
)
```
Typed live on my phone, might contain typos, it's just the idea there, but HTH.

**Comment by joshavant** [comment]
You're incredible for typing that from your phone!

Thanks for the tips, @AliSoftware. I will give this a shot!

**Comment by crabman448** [comment]
@AliSoftware Thank you! `settings_to_override` helped me a lot 👍
