### ISSUE TITLE
Creating app IDs as a Member

### ISSUE THREAD

**Issue by pardeike** [fastlane/fastlane#12848]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have an enterprise account at Apple and recently, I was downgraded from Admin to Member. Today I tried to verify why my script does not work anymore and got an error from `fastlane produce`:

```
andreas@pardeike.net:~ andreas@pardeike.net$ fastlane produce create --verbose -i -u "andreas@pardeike.net" -a "net.pardeike.lab.testing234" -q "Testing234"
[✔] 🚀 
[16:19:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+-----------------------------+
|          Summary for produce 2.99.0          |
+----------------+-----------------------------+
| skip_itc       | true                        |
| username       | andreas@pardeike.net |
| app_identifier | net.pardeike.lab.testing234 |
| app_name       | Testing234                  |
| sku            | 1530713962                  |
| platform       | ios                         |
| language       | English                     |
| skip_devcenter | false                       |
+----------------+-----------------------------+

Loading session from '/Users/ap/.fastlane/spaceship/andreas@pardeike.net/cookie'
INFO [2018-07-04 16:19:26.28]: Creating new app 'Testing234' on the Apple Dev Center

Looking for related GitHub issues on fastlane/fastlane...
Search query: Apple provided the following error info:
	You are not permitted to add App IDs to this team.  Please contact one of your team admins, who can add the App ID on your behalf.

URL: https://api.github.com/search/issues?q=Apple%20provided%20the%20following%20error%20info%3A%0A%09You%20are%20not%20permitted%20to%20add%20App%20IDs%20to%20this%20team.%20%20Please%20contact%20one%20of%20your%20team%20admins%2C%20who%20can%20add%20the%20App%20ID%20on%20your%20behalf.+repo:fastlane/fastlane
➡️  You are not permitted to add App IDs to this team
    https://github.com/fastlane/fastlane/issues/10665 [closed] 9 💬
    24 Dec 2017

➡️  You are not permitted to create provisioning profiles for team.
    https://github.com/fastlane/fastlane/issues/8183 [closed] 4 💬
    07 Aug 2017

➡️  [Match] Reusing manually generated certificates and provisioning 
    https://github.com/fastlane/fastlane/issues/7133 [closed] 4 💬
    30 Apr 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/spaceship/lib/spaceship/client.rb:602:in `parse_response': [!] Apple provided the following error info: (Spaceship::UnexpectedResponse)
	You are not permitted to add App IDs to this team.  Please contact one of your team admins, who can add the App ID on your behalf.
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/spaceship/lib/spaceship/portal/portal_client.rb:207:in `create_app!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/spaceship/lib/spaceship/portal/app.rb:97:in `create!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/produce/lib/produce/developer_center.rb:57:in `create_new_app'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/produce/lib/produce/developer_center.rb:44:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/produce/lib/produce/manager.rb:11:in `start_producing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/produce/lib/produce/commands_generator.rb:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/produce/lib/produce/commands_generator.rb:194:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/produce/lib/produce/commands_generator.rb:16:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

so I went to Xcode and created a new app for `net.pardeike.lab.testing123` successfully:

<img src="http://i65.tinypic.com/dfiw43.jpg"/>

Then I ran the fastlane command again for that ID and got this output:

```
ap:~ ap$ fastlane --verbose produce create -i -u "andreas@pardeike.net" -a "net.pardeike.lab.testing123" -q "Testing123"
[✔] 🚀 
[16:18:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-07-04 16:18:53.65]: Checking if there are any plugins that should be loaded...
invalid option: -i
ap:~ ap$ fastlane produce create --verbose -i -u "andreas@pardeike.net" -a "net.pardeike.lab.testing123" -q "Testing123"
[✔] 🚀 
[16:19:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+-----------------------------+
|          Summary for produce 2.99.0          |
+----------------+-----------------------------+
| skip_itc       | true                        |
| username       | andreas@pardeike.net |
| app_identifier | net.pardeike.lab.testing123 |
| app_name       | Testing123                  |
| sku            | 1530713943                  |
| platform       | ios                         |
| language       | English                     |
| skip_devcenter | false                       |
+----------------+-----------------------------+

Loading session from '/Users/ap/.fastlane/spaceship/andreas@pardeike.net/cookie'
INFO [2018-07-04 16:19:08.31]: [DevCenter] App 'net.pardeike.lab.testing123' already exists, nothing to do on the Dev Center
```

So my question: if Xcode can successfully create an app ID, why can't fastlane do it? We are not going to allow users to be Admin because of the capabilities and the access to the distribution certificate that that role has.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G54a)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 9.4                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-07-04**
</details>

**Comment by johnknapprs** [comment]
I believe Xcode might be creating a developer wildcard ID.  Check the developer portal that the appId exists.

**Comment by pardeike** [comment]
This is from the portal (sorry, iPhone):
<img src=“http://i64.tinypic.com/2zfjpz5.png”/>
