### ISSUE TITLE
Ignore test failures

### ISSUE THREAD

**Issue by lyptt** [fastlane/fastlane#1284]
I've noticed that UI tests in Xcode 7 are incredibly unreliable, often getting random capture failures and the like.

Is it possible to add an option to treat UI test failures as warnings and continue the build? I'd like to know about the failures, but I don't want to have to choose between having UI tests and being able to actually deploy my app.

**Comment by KrauseFx** [comment]
Thanks for letting us know, I just pushed a new release implementing this change: https://github.com/fastlane/snapshot/releases/tag/1.7.0 :rocket: Please update and let me know how you like it :+1:

**Comment by KrauseFx** [comment]
Does that work for you?
