### ISSUE TITLE
Asynchronous wait failed: Exceeded timeout of 30 seconds, with unfulfilled expectations: "Expect predicate `exists == 1` for object "Email or phone" TextField".

### ISSUE THREAD

**Issue by MohamedRasool786** [fastlane/fastlane#12844]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[All tests
Test Suite JustDeployUITests.xctest started
JustDeployUITests
✗ testExample, Asynchronous wait failed: Exceeded timeout of 30 seconds, with unfulfilled expectations: "Expect predicate `exists == 1` for object "Email or phone" TextField".

JustDeployUITests.JustDeployUITests
testExample, Asynchronous wait failed: Exceeded timeout of 30 seconds, with unfulfilled expectations: "Expect predicate `exists == 1` for object "Email or phone" TextField".
JustDeployUITests.swift:38

	 Executed 1 test, with 1 failure (0 unexpected) in 53.283 (53.324) seconds
]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by RishabhTayal** [comment]
@MohamedRasool786 Are you able to run the tests successfully through Xcode i.e without using `scan`?

**Comment by MohamedRasool786** [comment]
@RishabhTayal 
Thanks for your reply.

Yes I can run the tests successfully through Xcode, But it fails on fastlane scan. I don't know why?

**Comment by gearnshaw** [comment]
I'm having a similar issue. Asynchronous tests are failing when I run scan, but working fine in Xcode. These are tests that were previously passing with fastlane. Every time I run, a single test fails (the same one). If I remove that test, a different test fails consistently. And so on.

After more digging, I realised I updated to Fastlane 2.97.0. When I roll back to 2.85.0, it works.

Let me know if there's any more information I can provide to help.

**Comment by MohamedRasool786** [comment]
@gearnshaw 
I will try let u know. 

Thanks.

**Comment by gearnshaw** [comment]
Actually I don't think it is as simple as downgrading to 2.85.0, as I'm getting intermittent failures in that version as well now. _Something_ has changed, as my test suite was stable running in both fastlane and Xcode previously. I'll keep investigating and update if I find anything.
