### ISSUE TITLE
How to set minimum deployment target?

### ISSUE THREAD

**Issue by Diwei-Chen** [fastlane/fastlane#12859]
Hi there,

Could I please ask how to set the minimum deployment target(eg 10.0) to a xcode project?

Thanks,

**Comment by johnknapprs** [comment]
It can be done in the Xcode gui or by modifying your project files.

**Comment by Diwei-Chen** [comment]
@johnboiles Thanks for your reply.

Could this be done in a fastlane script, eg action?

Can you please specify which project files I need to change? Sorry, I am a bit new to xcode project.

**Comment by Diwei-Chen** [comment]
@johnknapprs Ah, I see. Is it all we need to do is write some scripts to modify this file `PROJECT_xcodeproj/project.pbxproj`?
