### ISSUE TITLE
Why is produce always enabling APN when creating a new App ID?

### ISSUE THREAD

**Issue by VolkerSchiewe** [fastlane/fastlane#12853]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
example command: `fastlane produce -u 'development@incapptic.com' -a 'com.example.fastlane' -q 'Fastlane' --verbose`

![image](https://user-images.githubusercontent.com/23318693/42322091-6e56d6d0-805b-11e8-9ece-94404ed46c3f.png)

#### Question Description
I would expect that non of these entitlements is enabled. But in my case especially the APN is problematic.

**Comment by joshdholtz** [comment]
@VolkerSchiewe Heyyyy 👋 I don't thing "Game Center" and "In-App Purchase" are able to get disabled. They get defaulted to on even if created through the iOS Developer Center without having an option to get turned off. I did find that we were setting "Push Notifications" to on so I will fix that up 👌 Thanks for finding that!

**Comment by VolkerSchiewe** [comment]
Your right, `Game Center` and `In-App Purchase` are probably some kind of default, and it looks like it is not even possible to disable them. But `Push Notifications` is not set by default if I create the App in the Developer Portal. 
I would appreciate if you find a fix for that 👍

**Comment by joshdholtz** [comment]
@VolkerSchiewe In the mean time you can run `fastlane produce disable_services --push-notification -u 'email@email.com -a 'com.yourbundle'` after creating your app 👍
