### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)     You don't have write permissions for the /usr/bin directory.

### ISSUE THREAD

**Issue by ShenJieSuzhou** [fastlane/fastlane#12857]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

When I Install fastlane using command 'sudo gem install fastlane -NV', It shows the following log: 
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.

What should I do to continue my installation？

**Comment by ShenJieSuzhou** [comment]
This is caused by using the default ruby version of the MAC OS system. We can solve the problem by installing a self-managed ruby version via 'rvm'.

**Comment by volodymyrslipak** [comment]
I have the same problem, don't have any idea how to solve it
