### ISSUE TITLE
Fastlane supply instant app support

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#12865]
Instant apps are bundled as a `zip` file. I'd like to be able to upload them to the Play Store too. Currently only `apk` and `aab` are supported and I can't seem to find a way to upload my instant app zip through supply.

**Comment by vanniktech** [comment]
Ideally this would be as easy as `instant_apps 'build/outputs/apk/release/instant-app-1.3.8-release.zip'` It needs to be uploaded after the APK / Android Bundle and can take the same rollout and stage value as APK / AAB.

**Comment by vanniktech** [comment]
This is a feature request hence this is still valid.

**Comment by vanniktech** [comment]
Still an issue

**Comment by vanniktech** [comment]
Still an issue.

**Comment by renatopeterman** [comment]
any news on this?

**Comment by janpio** [comment]
No.

Can someone of you "design" what exactly this feature would look like? What parameters are needed where? Does it use the same User Interface in the Play Console as the "normal" app upload does?

**Comment by renatopeterman** [comment]
Maybe something like @vanniktech proposed would work fine:

```
supply(instant_app_zip: 'build/outputs/apk/release/instant-app-release.zip')
```

The feature would probably depend on the issue below, right? I don't see anything about instantapps in the api reference.

https://github.com/googleapis/google-api-ruby-client/issues/703

**Comment by janpio** [comment]
Yes, we would need an API to use for this. Seems @vanniktech's issue over there was rerouted to the Google team supplying the underlying API :/

**Comment by vanniktech** [comment]
Appreciate that you're jumping in @janpio

**Comment by vanniktech** [comment]
Still an issue.

**Comment by vanniktech** [comment]
Nope.

**Comment by RishabhTayal** [comment]
I can help with this feature. @janpio any directions?

**Comment by janpio** [comment]
The problem seems to be a missing API, see https://github.com/fastlane/fastlane/issues/12865#issuecomment-443196397 With no API, no way to upload the data.

**Comment by RishabhTayal** [comment]
As suggested by @janpio, there are three different requests that are sent to the APIs, we can maybe look into that

1: supply normal app
2: web UI normal app
3: web UI instant app

**Comment by janpio** [comment]
It would help to have all 3 requests (URL, headers, body) to understand how they are similar or different - maybe we can force the API to do what we want.

**Comment by vanniktech** [comment]
It still is.

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/issues/14573 might be relevant here, as v3 of the API changed a bit and brought it more into sync with the web UI again.

**Comment by vanniktech** [comment]
It still is.

**Comment by kherink** [comment]
this would be very useful - is it still blocked by lack of api?

**Comment by janpio** [comment]
As far as I know, yes - at least for the API client version fastlane is using. (There is a newer version fastlane will have to migrate to this year I think, but I haven't checked if this functionality is present there.)

**Comment by vanniktech** [comment]
Yup still an issue.

**Comment by vanniktech** [comment]
Still an issue.

**Comment by vanniktech** [comment]
Still an issue.

**Comment by thanakij** [comment]
Hi @vanniktech,

I believe currently there are only two main formats for uploading to Google Play: (1) `apk` or (2) `aab`.
Both _Typical Release_ and _Instant App Release_ are relying on these two formats.
My thought on this is that the zip is just for an alias (ie, you can rename .apk or .aab to .zip).

Perhaps, a more interesting question to ask is what is the correct value of **track** parameter we should send to Google Play API so it ends up in _Instant App Release_.

Besides "alpha", "beta" and "production" for _Typical Release_, I tried to inspect the requests and responses between my browser and web UI of Play Developer Console.
How about "instantDev", "instantAlpha" and "instantProd"?

So could you verify this for us by changing the value for **track** parameter in your Supply?
Let us know if this work then.
