### ISSUE TITLE
pilot fails with ERROR ITMS-90161: "Invalid Provisioning Profile.

### ISSUE THREAD

**Issue by BObereder** [fastlane/fastlane#1286]
Building works fine but when I upload it with pilot I get the following: 
[!] Error uploading ipa file, more information see above (RuntimeError)

`Return status of iTunes Transporter was 1: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.stylight.Stylight [Payload/MyApp.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."`

This is the lane in the fast file:
 
    lane :beta do
    # Set team id
    team_id 'XXX'

    # Make sure provisioning profiles are up to date
    sigh(output_path: "./fastlane/certificates")

    # build
    gym(scheme: "MyScheme",
      output_directory: "./fastlane/builds/",
      output_name: "App #{Time.now.strftime("%d.%m.%Y")}.ipa",
      clean: true,
      include_symbols: true,
      include_bitcode: true,
      use_legacy_build_api: true
    )

    # Submit to TestFlight
    pilot
    end

**Comment by kumaro** [comment]
I am experiencing this too. I verified the IPA codesigning and provisioning profile. Everything is fine and the upload is working fine from XCode but it is failing from pilot. Any fix ?

**Comment by KrauseFx** [comment]
It looks like the export step doesn't use the correct provisioning profile. Make sure to follow the [Code Signing Guide](https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md) that describes on how to update your Xcode project to use the correct profile with its matching code signing identity.
Let me know how that works for you :+1:

**Comment by BObereder** [comment]
You were totally right for some reason the release provisioning profile in the project settings got set to development.
Setting it to release solved the problem, everything is back to normal now ;)
Thanks for pointing me in the right direction and sry for blaming fastlane for this.
Keep up the awesome work!

**Comment by KrauseFx** [comment]
Yeah :+1:

**Comment by KrauseFx** [comment]
Glad we could help you :rocket:
