### ISSUE TITLE
Missing action Crashlytics with notes

### ISSUE THREAD

**Issue by Thiryn** [fastlane/fastlane#12875]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm looking to upload my changelog with my beta deployment, but when I add the `notes: File.read("../CHANGELOG.md")` in the crashlytics call, I get an error
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$> fastlane deploy_fabric --verbose                                                                                     
[✔] 🚀
[15:25:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

DEBUG [2018-07-10 15:25:54.23]: Checking if there are any plugins that should be loaded...

INFO [2018-07-10 15:25:54.58]: ----------------------------------------
INFO [2018-07-10 15:25:54.58]: --- Step: Verifying fastlane version ---
INFO [2018-07-10 15:25:54.58]: ----------------------------------------
INFO [2018-07-10 15:25:54.58]: Your fastlane version 2.99.0 matches the minimum requirement of 2.68.0  ✅
INFO [2018-07-10 15:25:54.58]: ------------------------------
INFO [2018-07-10 15:25:54.58]: --- Step: default_platform ---
INFO [2018-07-10 15:25:54.58]: ------------------------------
INFO [2018-07-10 15:25:54.58]: Driving the lane 'ios deploy_fabric' 🚀
INFO [2018-07-10 15:25:54.58]: -------------------------
INFO [2018-07-10 15:25:54.58]: --- Step: crashlytics ---
INFO [2018-07-10 15:25:54.58]: -------------------------
INFO [2018-07-10 15:25:54.88]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2018-07-10 15:25:54.88]: ./Frameworks/Crashlytics.framework/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath './app.ipa' -notesPath '/var/folders/f9/33ntg5xj38n_5xrdj7rc7bqh0000gq/T/changelog20180710-32829-dt1tma' -notifications YES -debug NO
ERROR [2018-07-10 15:26:02.17]: Shell command exited with exit status  instead of 0.
WARN [2018-07-10 15:26:02.18]: Lane Context:
INFO [2018-07-10 15:26:02.18]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy_fabric"}
ERROR [2018-07-10 15:26:02.18]: 2018-07-10 15:25:54.899 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)

INFO [2018-07-10 15:26:02.18]: Successfully generated documentation at path '/path/to/app/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | crashlytics                | 7           |
+------+----------------------------+-------------+

ERROR [2018-07-10 15:26:02.18]: fastlane finished with errors
Traceback (most recent call last):
	30: from /usr/local/bin/fastlane:23:in `<main>'
	29: from /usr/local/bin/fastlane:23:in `load'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/bin/fastlane:20:in `<top (required)>'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:38:in `block (2 levels) in parsing_binding'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.99.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] 2018-07-10 15:25:54.899 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18) (FastlaneCore::Interface::FastlaneError)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.7.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-07-10**
</details></pre>
</details>

**Comment by apwelsh** [comment]
My verbose output:

NFO [2018-07-11 22:28:34.25]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2018-07-11 22:28:34.25]: ./Pods/Crashlytics/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath '/Users/apwelsh/Documents/PeerRate/PeerRate/PeerRate.ipa' -emails 'valerie@welshhome.org,armand@welshhome.org,jbailey1987@icloud.com,welshclaudine@gmail.com' -notesPath '/var/folders/v3/x0c3d0dj34g1tq9m2bl9k4ww0000gn/T/changelog20180711-76146-1tsx4vx' -notifications YES -debug NO
ERROR [2018-07-11 22:28:53.20]: Shell command exited with exit status  instead of 0.
WARN [2018-07-11 22:28:53.20]: Lane Context:
INFO [2018-07-11 22:28:53.20]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/apwelsh/Documents/PeerRate/PeerRate/PeerRate.ipa", :DSYM_OUTPUT_PATH=>"/Users/apwelsh/Documents/PeerRate/PeerRate/PeerRate.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/apwelsh/Library/Developer/Xcode/Archives/2018-07-11/PeerRate 2018-07-11 22.21.31.xcarchive"}
ERROR [2018-07-11 22:28:53.20]: 2018-07-11 22:28:34.272 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)

INFO [2018-07-11 22:28:53.20]: Successfully generated documentation at path '/Users/apwelsh/Documents/PeerRate/PeerRate/fastlane/README.md'

**Comment by Thiryn** [comment]
Hi! It looks like its the same error as me. Do you care to share your Fastfile?
About the comment you made about this distribution model (I guess you talk about fastlane) I am using it for quite a while now and all I can say is that it is saving me a lot of time, same distribution platform for android and iOS, interface with any deployment system (stores, Fabric, testflight...) certificate management for the whole team... Its quite handy tbh!
Its the first bug I encounter in a year.

**Comment by Thiryn** [comment]
I just renamed the issue, It seems like the File.read is working properly, but my problem is coming when the `crashlytics` action is called with the `note` or `note_path` parameter

**Comment by Thiryn** [comment]
Was wrong on my error. Multiple issues are already reporting this, see #12820 and #12888

**Comment by joshdholtz** [comment]
Just wanted to comment the solution here to make it easier but this was due to a bad binary shipped in Crashlytics `3.10.3` and `3.10.4`. Upgrading to Crashlytics `3.10.5` will solve the notes issue and upgrading to _fastlane_ `2.99.1` will also making Crashlytics a bit more stable by selecting the correct binary in the Crashlytics pod 😊

**Comment by apwelsh** [comment]
Thanks for all the follow-ups.  It seemed like when fastlane was distributed through fabric, errors like this didnt happen.  It could be coincidental, but it seemed like the fabric distribution model included some levels of regression testing that caught these types of critical failure errors before they got rolled out to the users.  I dont think this nee bundle based approach of managing the fastlane updates has much in the way in integration testing to ensure critical regression bugs like this are caught earlier on in the process.  
But, it is possible that i am just seeing things wrong, and my judgement is clouded by my distaste of this nee distribution model.

I will update both and see if my issues are solved.
