### ISSUE TITLE
gym is not exporting ipa after successful archive for Watchapp build

### ISSUE THREAD

**Issue by mschary932** [fastlane/fastlane#12879]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I used gym command to build the watch app after setting up project with proper provisioning profiles and identifiers. Able to see ARCHIVE SUCCEEDED message on gym output and there are errors failures from verbose log, but it is not able to export the packaged app (ipa) post the archival completion. it is not generating any export plist file.

18:27:33 [18:27:32]: ▸ export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/home/Jenkins/tools/fastlane/bundle/bin:/usr/bin:/bin:/usr/sbin:/sbin"
18:27:33 [18:27:32]: ▸ /usr/bin/touch -c /home/Jenkins/buildslave/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/KWatchOS2\ -\ Debug/BuildProductsPath/Debug-iphoneos/Debugger-PSECU.app.dSYM
18:27:34 [18:27:34]: ▸ ** ARCHIVE SUCCEEDED **
18:27:35 [18:27:34]: No output path received from gym

Command I used:

ENV['GYM_XCARGS'] = "DEVELOPMENT_TEAM=#{ENV["sigh_#{ENV['MATCH_APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}_team-id"]} OTHER_CODE_SIGN_FLAGS=\"--keychain #{ENV['MATCH_KEYCHAIN_NAME']}\""
gym(scheme: KDebug, configuration: 'Debug', export_method: ENV["EXPORT_METHOD"], output_directory: "./buildmsc", disable_xcpretty: true, derived_data_path: @derivedDataPath, build_path: @buildArchivePath, buildlog_path: @buildlogPath)

I also passed export_options with signingStyle: "manual" to gym command, but no luck. There are profile issues or any invalid archive issues that I observed in gym output file.

Let me know if anyone encountered such issue? I still not able to understand the error about No output path received from gym though I set output_directory.

**Comment by exevil** [comment]
Hey!

Perhaps I'm experiencing the similar issue. Do you have any solution?
