### ISSUE TITLE
Keep getting "Rate limit has been exceeded for: testflight|default|APPLE_CONNECT:"

### ISSUE THREAD

**Issue by hareeshsarma** [fastlane/fastlane#12889]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane Pilot

No

No
#### Question Description

I am getting the following exception when trying to use Fastlane in multi threading environment. Currently I am using 4 threads to login and upload data into TestFlight.

I couldn't find any official documentation for the Apple ITunesConnect account on how many parallel logins are supported.

Also, Could you please let us know what's the max rate supported by Fastlane to add/remove users into TestFlight.

**Comment by hareeshsarma** [comment]
Did anyone else face this issue?

**Comment by elviin** [comment]
Please follow this issue 
https://github.com/fastlane/fastlane/issues/12845

**Comment by hareeshsarma** [comment]
I see that there is no concrete solution in the issue. People are facing the same issue and are giving some sleep time between requests. Can you please point to the solution you recommending?

**Comment by elviin** [comment]
@hareeshsarma actually it is quite annoying issue. I had to serialise the workflow from CricleCI, that means the time to deliver has increased as the upload can not be done in parallel.  **Please report the issue to Apple developer portal.** They are not able to recognise that the issue is on their side.

**Comment by hareeshsarma** [comment]
Thanks @elviin . I think we have to wait for official ITunesConnect API which is announced in WWDC 2018 of Apple.

**Comment by hareeshsarma** [comment]
Hi @elviin 

Could you please help me understand whats the bulk upload feature on Fastlane? 

Based on the code I see that we are still doing sequential upload by reading from csv. But does it login once or it logins every time you upload a user?

Thanks,
Hareesh

**Comment by hareeshsarma** [comment]
@KrauseFx Could you please recommend the best way to bulk upload users into Testflight. As of now i am trying to process one user email at a time, but it seems there is no recommended TPS for that.

**Comment by elviin** [comment]
@hareeshsarma  I run fastlane in the CirclecCI environment. That is, the builds for each app configuration are running in a dedicated CircleCI job. I can define dependencies among the jobs. It can run multiple jobs in parallel. But if there was a dedicated action in the fastlane for the bulk upload, then  I will give it a try.
