### ISSUE TITLE
set and get github_release actions hard coded to public github

### ISSUE THREAD

**Issue by jaleksynas** [fastlane/fastlane#1288]
Users of github enterprise cannot use these nifty actions.

**Comment by KrauseFx** [comment]
Should be fairly easy to add an option to those actions: https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/get_github_release.rb#L14 :+1:

**Comment by KrauseFx** [comment]
Thanks again for your contribution @jaleksynas :+1:
