### ISSUE TITLE
Can I upload 1 or 2 screenshots that have changed, but not the whole bunch of screenshots? 

### ISSUE THREAD

**Issue by SQ1E** [fastlane/fastlane#12882]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Fastlane Deliver

#### Question Description
I have a task to upload screenshots that have changed, without uploading screenshots for 20 languages and for different devices. What is the right way to do that? Is it possible? 

I have screenshots uploaded on App Store Connect. And I need to upload new screenshots only for language en-US, but I'm not going to change screenshots for another activated languages. How should I do that with Fastlane Deliver?

Will you give me an advice?

**Comment by janpio** [comment]
Have you tried renaming the `screenshots` directory you currently have, then only re-create the folder structure for the screenshots you want to upload and then use `fastlane deliver` to generate a the preview?
