### ISSUE TITLE
Crashlytics action failing starting with fastlane 2.99.1

### ISSUE THREAD

**Issue by tomaskraina** [fastlane/fastlane#12894]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.99.1`]
- Last working version: [e.g. `2.98.0`]

### Regression Description

`crashlytics` action started failing with the following message:

```
sh: Pods/Crashlytics: is a directory
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Toms-MacBook-Pro-15:GoOut tomkraina$ bundle exec fastlane upload_to_crashlytics
[✔] 🚀 
[14:41:30]: ----------------------------------------
[14:41:30]: --- Step: Verifying fastlane version ---
[14:41:30]: ----------------------------------------
[14:41:30]: Your fastlane version 2.99.1 matches the minimum requirement of 1.66.0  ✅
[14:41:30]: ------------------------------------------------
[14:41:30]: Name of the lane 'testflight' is already taken by the action named 'testflight'
[14:41:30]: ------------------------------------------------
[14:41:30]: Driving the lane 'upload_to_crashlytics' 🚀
[14:41:30]: -------------------------
[14:41:30]: --- Step: crashlytics ---
[14:41:30]: -------------------------
[14:41:30]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[14:41:30]: Shell command exited with exit status 126 instead of 0.
+---------------+-----------------------+
|             Lane Context              |
+---------------+-----------------------+
| PLATFORM_NAME |                       |
| LANE_NAME     | upload_to_crashlytics |
+---------------+-----------------------+
[14:41:30]: sh: Pods/Crashlytics: is a directory

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 💥   | crashlytics                | 0           |
+------+----------------------------+-------------+

[14:41:30]: fastlane finished with errors

[!] sh: Pods/Crashlytics: is a directory
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.3.1                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.14.3 (Apple Git-98)               |
| Installation Source         | ~/.gems/bin/fastlane                            |
| Host                        | Mac OS X 10.12.6 (16G1510)                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.66.0"

  lane :upload_to_crashlytics do 
    crashlytics(
      groups: 'only-me'
    )
  end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXXXX" # The bundle identifier of your app
apple_id ENV["FASTLANE_USER"] || "xxxxx@xxxxx.xxx" # Your Apple email address

team_id "XXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.3        |
| cocoapods-wholemodule     | 0.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| houston                   | 2.2.4        |
| sqlite3                   | 1.3.13       |
| xcode-install             | 2.4.1        |
</details>

*generated on:* **2018-07-12**
</details>
</pre>
</details>

**Comment by tomaskraina** [comment]
Probably caused by https://github.com/fastlane/fastlane/pull/12876?

**Comment by joshdholtz** [comment]
@tomaskraina Can you run `bundle exec fastlane upload_to_crashlytics` with the `--verbose` flag on the end? `bundle exec fastlane upload_to_crashlytics --verbose`

**Comment by tomaskraina** [comment]
Sure:

```
Toms-MacBook-Pro-15:GoOut tomkraina$ bundle exec fastlane upload_to_crashlytics --verbose
[✔] 🚀 
DEBUG [2018-07-12 15:08:36.68]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/tomkraina/Developer/GoOut.cz/GoOut/fastlane/Appfile'
- app_identifier: 'net.goout.GoOut'
- apple_id: 'xxxx@xxxx.xxx'
- team_id: 'XXXXXX'
-------
INFO [2018-07-12 15:08:36.90]: ----------------------------------------
INFO [2018-07-12 15:08:36.90]: --- Step: Verifying fastlane version ---
INFO [2018-07-12 15:08:36.90]: ----------------------------------------
INFO [2018-07-12 15:08:36.90]: Your fastlane version 2.99.1 matches the minimum requirement of 1.66.0  ✅
INFO [2018-07-12 15:08:36.90]: Driving the lane 'upload_to_crashlytics' 🚀
INFO [2018-07-12 15:08:36.90]: -------------------------
INFO [2018-07-12 15:08:36.90]: --- Step: crashlytics ---
INFO [2018-07-12 15:08:36.90]: -------------------------
INFO [2018-07-12 15:08:36.91]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2018-07-12 15:08:36.91]: Pods/Crashlytics [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath 'GoOut.ipa' -groupAliases 'only-me' -notifications YES -debug NO
ERROR [2018-07-12 15:08:36.91]: Shell command exited with exit status 126 instead of 0.
WARN [2018-07-12 15:08:36.91]: Lane Context:
INFO [2018-07-12 15:08:36.91]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"upload_to_crashlytics"}
ERROR [2018-07-12 15:08:36.91]: sh: Pods/Crashlytics: is a directory

INFO [2018-07-12 15:08:36.91]: Successfully generated documentation at path '/Users/tomkraina/Developer/GoOut.cz/GoOut/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 💥   | crashlytics                | 0           |
+------+----------------------------+-------------+

ERROR [2018-07-12 15:08:36.92]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/tomkraina/.gems/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] sh: Pods/Crashlytics: is a directory

  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:47:in `block in parsing_binding'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/tomkraina/.gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/tomkraina/.gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/tomkraina/.gems/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/tomkraina/.gems/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/tomkraina/.gems/gems/fastlane-2.99.1/bin/fastlane:20:in `<top (required)>'
  /Users/tomkraina/.gems/bin/fastlane:23:in `load'
  /Users/tomkraina/.gems/bin/fastlane:23:in `<top (required)>'
```

**Comment by joshdholtz** [comment]
@tomaskraina Do you happen to have the `CRASHLYTICS_FRAMEWORK_PATH` environment variable set anywhere? https://github.com/fastlane/fastlane/pull/12876 looks for all the paths with the `submit` binary so its kinda add that its trying to execute `Pods/Crashlytics` instead of `./Pods/Crashlytics/submit`

**Comment by tomaskraina** [comment]
Yes, I do actually:

```
Toms-MacBook-Pro-15:GoOut tomkraina$ cat fastlane/.env 
CRASHLYTICS_FRAMEWORK_PATH="Pods/Crashlytics"
...
```

**Comment by tomaskraina** [comment]
Deleting the line with `CRASHLYTICS_FRAMEWORK_PATH` makes it work all right. So I guess that this env var is not needed anymore?

**Comment by joshdholtz** [comment]
@tomaskraina Ah woot, glad that worked for you! I have a PR I'm finishing up to validate that the proper path is executing and I'll throw in a fix for this specifically ^ Sorry about that issue 😊 _fastlane_ is smarter in how in how it finds the `submit` binary on its own in `2.99.1` but didn't validate user input if the path was set explicitly

**Comment by tomaskraina** [comment]
Perfect. Thanks for your help, @joshdholtz  :)
