### ISSUE TITLE
dsym_url missing for some builds

### ISSUE THREAD

**Issue by keith** [fastlane/fastlane#12895]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When attempting to download dsyms with a custom fastlane script, the `dsym_url` property for some builds is `nil`, even though on the iTunes Connect UI, there is a dsym URL for the build.

For example from the repl:

```ruby
[9] pry(main)> builds.map { |x| "#{x.build_version} #{x.dsym_url}" }
=> ["5.37.0.38211407 http://iosapps.itunes.apple.com/...",
 "5.37.0.38153002 http://iosapps.itunes.apple.com/...",
 "5.37.0.38125078 http://iosapps.itunes.apple.com/...",
 "5.37.0.38066651 http://iosapps.itunes.apple.com/...",
 "5.37.0.38037944 ",
 "5.37.0.37983678 ",
 "5.37.0.37954221 ",
 "5.37.0.37896377 ",
 "5.37.0.37875930 ",
 "5.37.0.37868778 ",
 "5.37.0.37807454 ",
 "5.37.0.37778640 ",
 "5.37.0.37720982 ",
 "5.37.0.37692644 ",
 "5.37.0.37634635 ",
 "5.37.0.37606303 "]
```

But on iTC:

![image](https://user-images.githubusercontent.com/283886/42643000-f31652c8-85ac-11e8-9709-afe3cb819b52.png)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.gem/ruby/2.3.3/bin/fastlane              |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.3/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
<snip>

  all_apps = Spaceship::Tunes::Application.all
  all_apps.each do |app|
    app.all_build_train_numbers.each do |train|
      builds = app.all_builds_for_train(train: train)
      builds.each do |build|
        download_url = build.dsym_url
        # download_url is nil

<snip>

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-07-12**
</details>

**Comment by joshdholtz** [comment]
@keith Heyyyy 👋 That is strange... I will look into this for you!

**Comment by keith** [comment]
Did you discover anything here @joshdholtz ?

**Comment by keith** [comment]
Likely still a problem. I can upgrade and try again..


--
Keith Smiley

**Comment by keith** [comment]
This appears to still be an issue in 2.104.0. I _believe_ I've been able to work around this by accessing the `build` ahead of time. Is it possible this causes a side effect that forces the loading of the URL? I'm still debugging but printing the build ahead of time might have fixed it.
