### ISSUE TITLE
Customize HTML generated by Fastlane Snapshot

### ISSUE THREAD

**Issue by JeanAzzopardi** [fastlane/fastlane#12892]
#### Motivation Behind Feature

It would be very handy to customise the HTML generated by Fastlane Snapshot. This would effectively allow us to generate customised reports, apply custom CSS, etc.

#### Feature Description
Specify a custom `page.html.erb` as an option in the `Snapfile`.

Only drawback I can think of is that this can break fastlane snapshot in an update if e.g. the bindings change, however, this can be specified in the documentation.

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/pull/15349 implements this.

**Comment by rogerluan** [comment]
Closing this stale PR as https://github.com/fastlane/fastlane/pull/15349 got merged and released a long time ago 😊
