### ISSUE TITLE
Smart quotes change 1.55 to 1.57 breaks Deliverfile

### ISSUE THREAD

**Issue by RocketPop** [fastlane/fastlane#1289]
I just updated fastlane from 1.55 to 1.57 and now I get this error I have never seen before:

```
[11:25:56]: ---------------------
[11:25:56]: --- Step: deliver ---
[11:25:56]: ---------------------
[11:25:56]: Your Deliverfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice. 
```

Sanitizing these quotes out completely breaks my Deliverfile because I have smart quotes inside my app descriptions to do stuff like: 
```
description( "en-US" => "“Best app ever!” - A. Customer")
```

> “Best app ever!” - A. Customer
 
I wasn't getting this behavior earlier this week but that quote sanitizer code in fast_file.rb seems to be pretty old (Sept '15?) - any ideas what could be causing this now? I don't think smart quotes should be scrubbed out. I'll try rolling back versions as soon as I figure out how to do that :)

**Comment by KrauseFx** [comment]
Interesting! I'd recommend not storing the actual metadata (e.g. description) in your `Deliverfile`, instead put it into the `metadata` folder which is created by `deliver` for you :+1:

**Comment by RocketPop** [comment]
We generate a Deliverfile "on-the-fly" during our build process. It's more of a build artifact for us. We used to write our data out to all the various metadata files but maintaining all those little files was bothersome. I guess I'll revert to that if I must - but I'll look around a bit more first. Thanks!

**Comment by RocketPop** [comment]
I have "fixed" this by using Ruby alternate quotes in our tool that creates the Deliverfile like this:

```description( "en-US" => %q^“Best app ever!” - A. Customer^)```

This ends up with standard quotes in our description rather than the original smart quotes - but it works. After working on this - I really think that fastlane should not be "helping me" by modifying any input / Deliverfile with smart quotes. However, since that's an opinion and not a Pull Request - I'll move on for now :smiley:  Thanks!

**Comment by KrauseFx** [comment]
Awesome, thanks @RocketPop :+1:
