### ISSUE TITLE
[!] sh: ./Pods/Crashlytics/: is a directory 

### ISSUE THREAD

**Issue by Shhamara** [fastlane/fastlane#12902]
### Issue Description
final output crash

##### Complete output when running fastlane, including the stack trace and command used
16:08:38 [16:08:28]: ----------------------------------------------
16:08:38 [16:08:28]: --- Step: Switch to crashlyticsUpload lane ---
16:08:38 [16:08:28]: ----------------------------------------------
16:08:38 [16:08:28]: Cruising over to lane 'crashlyticsUpload' 🚖
16:08:38 [16:08:28]: -------------------------
16:08:38 [16:08:28]: --- Step: crashlytics ---
16:08:38 [16:08:28]: -------------------------
16:08:38 [16:08:28]: Uploading the build to Crashlytics Beta. Time for some ☕️.
16:08:38 [16:08:28]: Shell command exited with exit status 126 instead of 0.
16:08:38 +--------------------+-------------------------------------------------------------------------------------------------------+
16:08:38 |                                                        Lane Context                                                        |
16:08:38 +--------------------+-------------------------------------------------------------------------------------------------------+
16:08:38 | PLATFORM_NAME      |                                                                                                       |
16:08:38 | LANE_NAME          | stageBuildToCrashlytics                                                                               |
16:08:38 | BUILD_NUMBER       | 48420                                                                                                 |
16:08:38 | IPA_OUTPUT_PATH    | /Users/jenkins/workspace/uc-ios-release/United cloud.ipa                                              |
16:08:38 | XCODEBUILD_ARCHIVE | /Users/jenkins/Library/Developer/Xcode/Archives/2018-07-13/United cloud 2018-07-13 15.50.20.xcarchive |
16:08:38 +--------------------+-------------------------------------------------------------------------------------------------------+
16:08:38 [16:08:28]: sh: ./Pods/Crashlytics/: is a directory
16:08:38 
16:08:38 
16:08:38 +------+----------------------------------+-------------+
16:08:38 |                   fastlane summary                    |
16:08:38 +------+----------------------------------+-------------+
16:08:38 | Step | Action                           | Time (in s) |
16:08:38 +------+----------------------------------+-------------+
16:08:38 | 1    | Verifying fastlane version       | 0           |
16:08:38 | 2    | increment_build_number           | 1           |
16:08:38 | 3    | gym                              | 1099        |
16:08:38 | 4    | Switch to crashlyticsUpload lane | 0           |
16:08:38 | 💥   | crashlytics                      | 0           |
16:08:38 +------+----------------------------------+-------------+
16:08:38 
16:08:38 [16:08:28]: fastlane finished with errors
16:08:38 
16:08:38 [!] sh: ./Pods/Crashlytics/: is a directory
16:08:38 

Any clue, what can cause this issue??

**Comment by joshdholtz** [comment]
@Shhamara Can you paste the output from `fastlane env` so we can help you out more? ^

Also, if you are using _fastlane_ `2.99` or `2.99.1`, this might be able to be solved with https://github.com/fastlane/fastlane/issues/12894#issuecomment-404509099

**Comment by Shhamara** [comment]
@joshdholtz  Yes, #12894 helped me to solve my problem. Thank you. 
crashlytics_path in my project was wrong.

**Comment by webvizitor** [comment]
Determining the path in `fastlane env` directly to Crashlytics framework like this:
`CRASHLYTICS_FRAMEWORK_PATH="./Pods/Crashlytics/Crashlytics.framework"`
works well in my case
