### ISSUE TITLE
Google Api Error: Invalid Request in upload_to_play_store - Fastlane 2.99.1

### ISSUE THREAD

**Issue by eygraber** [fastlane/fastlane#12900]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I changed `upload_to_play_store` to use aab instead of apk. Now it fails (output below).

##### Complete output when running fastlane, including the stack trace and command used

```
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+

|                                                                 Summary for supply 2.99.1                                                                  |

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+

| package_name            | com.myapp                                                                                                                        |

| track                   | internal                                                                                                                         |

| json_key                | **** |

| aab                     | app/build/outputs/bundle/prodRelease/app.aab                                                                                     |

| mapping                 | app/build/outputs/mapping/prod/release/mapping.txt                                                                               |

| skip_upload_metadata    | true                                                                                                                             |

| skip_upload_images      | true                                                                                                                             |

| skip_upload_screenshots | true                                                                                                                             |

| metadata_path           | ./fastlane/metadata/android                                                                                                      |

| skip_upload_apk         | false                                                                                                                            |

| skip_upload_aab         | false                                                                                                                            |

| validate_only           | false                                                                                                                            |

| check_superseded_tracks | false                                                                                                                            |

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+



DEBUG [2018-07-13 01:43:59.21]: Fetching a new access token from Google...

INFO [2018-07-13 01:44:01.54]: Preparing to upload for language 'en-US'...

WARN [2018-07-13 01:44:01.67]: Lane Context:

INFO [2018-07-13 01:44:01.67]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android upload_to_play_store_for_release_type", :COMMITS_SINCE_TAG_RESULT=>8}

ERROR [2018-07-13 01:44:01.67]: Google Api Error: Invalid request

INFO [2018-07-13 01:44:01.67]: Successfully generated documentation at path '/Users/developer/.jenkins/workspace/myapp@2/fastlane/README.md'



+------+----------------------------------------+-------------+

|                      fastlane summary                       |

+------+----------------------------------------+-------------+

| Step | Action                                 | Time (in s) |

+------+----------------------------------------+-------------+

| 1    | Verifying fastlane version             | 0           |

| 2    | default_platform                       | 0           |

| 3    | setup_environment_variables            | 0           |

| 4    | Switch to android most_recent_tag lane | 0           |

| 5    | git_tags                               | 2           |

| 6    | commits_since_tag                      | 0           |

| 7    | touched_files_since_tag                | 0           |

| 💥   | upload_to_play_store                   | 2           |

+------+----------------------------------------+-------------+



DEBUG [2018-07-13 01:44:01.68]: All plugins are up to date

ERROR [2018-07-13 01:44:01.68]: fastlane finished with errors

DEBUG [2018-07-13 01:44:01.68]: All plugins are up to date

bundler: failed to load command: fastlane (/Users/developer/.rbenv/versions/2.3.7/bin/fastlane)

FastlaneCore::Interface::FastlaneError: [!] Google Api Error: Invalid request

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/client.rb:390:in `rescue in call_google_api'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/client.rb:387:in `call_google_api'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/client.rb:228:in `upload_mapping'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:136:in `block in upload_binaries'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:134:in `each'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:134:in `upload_binaries'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:26:in `perform_upload'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'

  lanes/releases.rb:43:in `block in parsing_binding'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `execute'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/bin/fastlane:20:in `<top (required)>'

  /Users/developer/.rbenv/versions/2.3.7/bin/fastlane:22:in `load'

  /Users/developer/.rbenv/versions/2.3.7/bin/fastlane:22:in `<top (required)>'

script returned exit code 1
```

**Comment by eygraber** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rbenv/versions/2.2.2/bin/fastlane        |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.88.0"

default_platform :android

platform :android do
  Dir['lanes/*.rb'].each { |file| import(file) }

  before_all do
    setup_environment_variables
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                              | Version | Update-Status  |
| ----------------------------------- | ------- | -------------- |
| fastlane-plugin-changelog_generator | 0.2.1   | ✅ Up-To-Date   |
| fastlane-plugin-git_tags            | 0.1.1   | ✅ Up-To-Date   |
| fastlane-plugin-scarif              | 0.1.4   | 💥 Check failed |


<details><summary><b>Loaded gems</b></summary>

| Gem                                 | Version      |
| ----------------------------------- | ------------ |
| bundler                             | 1.16.2       |
| CFPropertyList                      | 3.0.0        |
| public_suffix                       | 2.0.5        |
| addressable                         | 2.5.2        |
| atomos                              | 0.1.2        |
| thread_safe                         | 0.3.6        |
| descendants_tracker                 | 0.0.4        |
| ice_nine                            | 0.11.2       |
| axiom-types                         | 0.1.1        |
| babosa                              | 1.0.2        |
| claide                              | 1.0.2        |
| colored2                            | 3.1.2        |
| cork                                | 0.3.0        |
| nap                                 | 1.1.0        |
| open4                               | 1.3.4        |
| claide-plugins                      | 0.9.2        |
| coderay                             | 1.1.2        |
| coercible                           | 1.0.0        |
| colored                             | 1.2          |
| highline                            | 1.7.10       |
| commander-fastlane                  | 4.4.6        |
| multipart-post                      | 2.0.0        |
| faraday                             | 0.15.2       |
| faraday-http-cache                  | 1.3.1        |
| git                                 | 1.4.0        |
| kramdown                            | 1.17.0       |
| no_proxy_fix                        | 0.1.2        |
| sawyer                              | 0.8.1        |
| octokit                             | 4.9.0        |
| unicode-display_width               | 1.4.0        |
| terminal-table                      | 1.8.0        |
| danger                              | 5.6.2        |
| danger-plugin-api                   | 1.0.0        |
| excon                               | 0.62.0       |
| danger-jumpspeeder                  | 0.1.0        |
| declarative                         | 0.0.10       |
| declarative-option                  | 0.1.0        |
| unf_ext                             | 0.0.7.5      |
| unf                                 | 0.1.4        |
| domain_name                         | 0.5.20180417 |
| dotenv                              | 2.5.0        |
| ejson                               | 1.1.0        |
| emoji_regex                         | 0.1.1        |
| equalizer                           | 0.0.11       |
| http-cookie                         | 1.0.3        |
| faraday-cookie_jar                  | 0.0.6        |
| faraday_middleware                  | 0.12.2       |
| fastimage                           | 2.1.3        |
| gh_inspector                        | 1.1.3        |
| jwt                                 | 2.1.0        |
| little-plugger                      | 1.1.4        |
| multi_json                          | 1.13.1       |
| logging                             | 2.2.2        |
| memoist                             | 0.16.0       |
| os                                  | 0.9.6        |
| signet                              | 0.8.1        |
| googleauth                          | 0.6.2        |
| httpclient                          | 2.8.3        |
| mime-types-data                     | 3.2016.0521  |
| mime-types                          | 3.1          |
| uber                                | 0.1.0        |
| representable                       | 3.0.4        |
| retriable                           | 3.1.2        |
| google-api-client                   | 0.21.2       |
| json                                | 2.1.0        |
| mini_magick                         | 4.5.1        |
| multi_xml                           | 0.6.0        |
| plist                               | 3.4.0        |
| rubyzip                             | 1.2.1        |
| security                            | 0.1.3        |
| naturally                           | 2.2.0        |
| simctl                              | 1.6.5        |
| slack-notifier                      | 2.3.2        |
| terminal-notifier                   | 1.8.0        |
| tty-screen                          | 0.6.4        |
| tty-cursor                          | 0.5.0        |
| tty-spinner                         | 0.8.0        |
| word_wrap                           | 1.0.0        |
| nanaimo                             | 0.2.6        |
| xcodeproj                           | 1.5.9        |
| rouge                               | 2.0.7        |
| xcpretty                            | 0.2.8        |
| xcpretty-travis-formatter           | 1.0.0        |
| fastlane-plugin-changelog_generator | 0.2.1        |
| fastlane-plugin-git_tags            | 0.1.1        |
| fastlane-plugin-scarif              | 0.1.4        |
| method_source                       | 0.8.2        |
| mimemagic                           | 0.3.2        |
| slop                                | 3.6.0        |
| pry                                 | 0.10.4       |
| pry-nav                             | 0.2.4        |
| virtus                              | 1.0.5        |
| tracker_api                         | 1.9.0        |
</details>


*generated on:* **2018-07-13**
</details>

**Comment by eygraber** [comment]
It seems like the issue was specifying a `mapping` key when uploading a bundle. Removing it makes the upload work. Apparently the mapping file is included with the bundle.

**Comment by chibatching** [comment]
https://github.com/fastlane/fastlane/pull/12856 will fix this :smile:
