### ISSUE TITLE
`Unsupported directory name(s)` when using a fonts directory (reopened)

### ISSUE THREAD

**Issue by piohhmy** [fastlane/fastlane#12903]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Reopening #12375 as it looks like it was auto-closed. 

_Question: Is opening a new issue referencing the closed issue the best way to reopen an issue? Or is there a way to ask for the issue to be reopened directly?_

##### Complete output when running fastlane, including the stack trace and command used

See #12375 

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

See #12375

**Comment by piohhmy** [comment]
@joshdholtz @revolter @KrauseFx  I'd love to start contributing to fastlane with some PRs.  Could you take a look at this issue (and the embedded question) and give a green light for me to go ahead?

**Comment by janpio** [comment]
I re-opened the other issue.
