### ISSUE TITLE
gym should support incremental builds (aka clean: false)

### ISSUE THREAD

**Issue by pvinis** [fastlane/fastlane#12914]
#### Motivation Behind Feature
it will make builds much faster, in the cases where we want it to be fast.

#### Feature Description
pretty self explanatory. if i have clean: false, gym should build by using the previous derived data for faster builds.

#### Alternatives or Workarounds
-

**Comment by pvinis** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                              |
| --------------------------- | ------------------------------------------------------------------ |
| OS                          | 10.13.5                                                            |
| Ruby                        | 2.4.3                                                              |
| Bundler?                    | true                                                               |
| Git                         | git version 2.18.0                                                 |
| Installation Source         | ~/Source/mycujoo/player-ios/bundler-vendor/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.13.5 (17F77)                                           |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.3/lib                                           |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                         |
| Is contained                | false                                                              |
| Is homebrew                 | false                                                              |
| Is installed via Fabric.app | false                                                              |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                        |
| Xcode Version               | 9.4.1                                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs # dont generate readme

def setup_ci 
  if is_ci?
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
    )
  end
end

default_platform(:ios)

platform :ios do
  desc "Create all needed profiles"
  lane :profiles_fix do
    register_devices(devices_file: "./fastlane/devices.txt")

    match(app_identifier: "tv.mycujoo.player",          type: "appstore")
    match(app_identifier: "tv.mycujoo.player",          type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player",          type: "development", force_for_new_devices: true)

    match(app_identifier: "tv.mycujoo.player.internal", type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player.internal", type: "development", force_for_new_devices: true)

    match(app_identifier: "tv.mycujoo.player.beta",     type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player.beta",     type: "development", force_for_new_devices: true)

    match(app_identifier: "tv.mycujoo.player.dev",      type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player.dev",      type: "development", force_for_new_devices: true)
  end

  desc "Build a new Internal build"
  lane :build_internal do
    setup_ci
    match(app_identifier: "tv.mycujoo.player.internal", type: "adhoc", readonly: true)
    gym(
      workspace: "mycujoo-player-ios.xcworkspace",
      scheme: "mycujoo-player-ios Internal Release",
      clean: false,
      output_directory: "builds",
      output_name: "MycujooPlayer-Internal.ipa",
      # include_symbols: true,
      derived_data_path: "builds/dd-internal",
verbose: true,
disable_xcpretty: true,
      buildlog_path: "builds",
    )
  end

  desc "Build a new Appstore build"
  lane :build_appstore do
    setup_ci
    match(app_identifier: "tv.mycujoo.player", type: "appstore", readonly: true)
    gym(
      workspace: "mycujoo-player-ios.xcworkspace",
      scheme: "mycujoo-player-ios Appstore Release",
      output_directory: "builds",
      output_name: "MycujooPlayer-Appstore.ipa",
      # include_symbols: true,
      derived_data_path: "builds/dd-appstore",
      buildlog_path: "builds",
    )
  end

  desc "Upload Internal symbols to Sentry"
  lane :upload_symbols_internal do
    sentry_upload_dsym( 
      auth_token: "e31d792f358b4a01bd5e15fd42ff8ea4f63e1ec7cb0e4c89ade85a839778ab12",
      org_slug: "mycujoo-w3",
      project_slug: "player",
      dsym_path: "./builds/MycujooPlayer-Internal.app.dSYM.zip",
    )
  end

  desc "Upload Appstore symbols to Sentry"
  lane :upload_symbols_appstore do
    sentry_upload_dsym( 
      auth_token: "e31d792f358b4a01bd5e15fd42ff8ea4f63e1ec7cb0e4c89ade85a839778ab12",
      org_slug: "mycujoo-w3",
      project_slug: "player",
      dsym_path: "./builds/MycujooPlayer-Appstore.app.dSYM.zip",
    )
  end

  desc "Upload Internal build to Crashlytics Beta"
  lane :upload_internal_crashlytics do
    setup_ci
    match(app_identifier: "tv.mycujoo.player.internal", type: "adhoc", readonly: true)
    crashlytics(
      # crashlytics_path: "./ios/Vendor/Fabric/Crashlytics.framework/",
      api_token: "999192c9cbfac5d7403248cf12526f67b34c887b",
      build_secret: "1b47b24f1163342dc82743874fc46e5e30ce506e7ebe75ae583eeeeeac5dec2b",
      ipa_path: "./builds/MycujooPlayer-Internal.ipa",
      # notes: changelog,
      groups: ["ios-player-internal"],
      notifications: true,
    )
  end

  desc "Bumps build number"
  lane :bump_build_number do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-build-number " + force
    new_build_number = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^BUILD_NUMBER = (\d+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump build to #{new_build_number}\""
    add_git_tag(tag: "build/#{new_build_number}")
  end

  desc "Bumps version full"
  lane :bump_version_full do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-full " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Bumps version major"
  lane :bump_version_major do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-major " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Bumps version minor"
  lane :bump_version_minor do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-minor " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Bumps version patch"
  lane :bump_version_patch do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-patch " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Adds a tag with the current version, appending rc-<number>"
  lane :tag_with_version do
    version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    final_tag_string = ""
    (1..100).each do |n|
      tag_string = "version/#{version_string}-rc#{n}"
      if !git_tag_exists(tag: tag_string)
        final_tag_string = tag_string
        break
      end
    end
    if final_tag_string != ""
      add_git_tag(tag: final_tag_string)
    end
  end

  desc "Create app manifest"
  lane :create_app_manifest do
    erb(
      template: "./fastlane/app-manifest.plist.erb",
      destination: "./builds/app-manifest.plist",
      placeholders: {
        :bundle_identifier => "tv.mycujoo.player.internal",
        :build_number => 24,
        :name => "mycujoo intrnl",
        :icon_url => "https://a1.files.diawi.com/app-icon/c7zCYsGPV6Hpo0DghCcr.png",
        :ipa_url => "https://a1.files.diawi.com/app-file/c7zCYsGPV6Hpo0DghCcr.ipa",
      },
    )
  end

  desc "Create app install html"
  lane :create_app_install do
    erb(
      template: "./fastlane/app-install.html.erb",
      destination: "./builds/app-install.html",
      placeholders: {
        :plist_url => "https://api.diawi.com/app-manifest/c7zCYsGPV6Hpo0DghCcr.plist",
      },
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "[[APP_IDENTIFIER]]" # The bundle identifier of your app
apple_id "ios-dev@mycujoo.tv"
team_id "57ZCK5ERE3"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.5.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.3        |
| cocoapods-check           | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.5.0        |
</details>


*generated on:* **2018-07-18**
</details>

**Comment by pvinis** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                              |
| --------------------------- | ------------------------------------------------------------------ |
| OS                          | 10.13.5                                                            |
| Ruby                        | 2.4.3                                                              |
| Bundler?                    | true                                                               |
| Git                         | git version 2.18.0                                                 |
| Installation Source         | ~/Source/mycujoo/player-ios/bundler-vendor/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.13.5 (17F77)                                           |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.3/lib                                           |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                         |
| Is contained                | false                                                              |
| Is homebrew                 | false                                                              |
| Is installed via Fabric.app | false                                                              |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                        |
| Xcode Version               | 9.4.1                                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs # dont generate readme

def setup_ci 
  if is_ci?
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
    )
  end
end

default_platform(:ios)

platform :ios do
  desc "Create all needed profiles"
  lane :profiles_fix do
    register_devices(devices_file: "./fastlane/devices.txt")

    match(app_identifier: "tv.mycujoo.player",          type: "appstore")
    match(app_identifier: "tv.mycujoo.player",          type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player",          type: "development", force_for_new_devices: true)

    match(app_identifier: "tv.mycujoo.player.internal", type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player.internal", type: "development", force_for_new_devices: true)

    match(app_identifier: "tv.mycujoo.player.beta",     type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player.beta",     type: "development", force_for_new_devices: true)

    match(app_identifier: "tv.mycujoo.player.dev",      type: "adhoc",       force_for_new_devices: true)
    match(app_identifier: "tv.mycujoo.player.dev",      type: "development", force_for_new_devices: true)
  end

  desc "Build a new Internal build"
  lane :build_internal do
    setup_ci
    match(app_identifier: "tv.mycujoo.player.internal", type: "adhoc", readonly: true)
    gym(
      workspace: "mycujoo-player-ios.xcworkspace",
      scheme: "mycujoo-player-ios Internal Release",
      clean: false,
      output_directory: "builds",
      output_name: "MycujooPlayer-Internal.ipa",
      # include_symbols: true,
      derived_data_path: "builds/dd-internal",
verbose: true,
disable_xcpretty: true,
      buildlog_path: "builds",
    )
  end

  desc "Build a new Appstore build"
  lane :build_appstore do
    setup_ci
    match(app_identifier: "tv.mycujoo.player", type: "appstore", readonly: true)
    gym(
      workspace: "mycujoo-player-ios.xcworkspace",
      scheme: "mycujoo-player-ios Appstore Release",
      output_directory: "builds",
      output_name: "MycujooPlayer-Appstore.ipa",
      # include_symbols: true,
      derived_data_path: "builds/dd-appstore",
      buildlog_path: "builds",
    )
  end

  desc "Upload Internal symbols to Sentry"
  lane :upload_symbols_internal do
    sentry_upload_dsym( 
      auth_token: "efas78ab12",
      org_slug: "mycujoo-w3",
      project_slug: "player",
      dsym_path: "./builds/MycujooPlayer-Internal.app.dSYM.zip",
    )
  end

  desc "Upload Appstore symbols to Sentry"
  lane :upload_symbols_appstore do
    sentry_upload_dsym( 
      auth_token: "e31d792f3fdasf2",
      org_slug: "mycujoo-w3",
      project_slug: "player",
      dsym_path: "./builds/MycujooPlayer-Appstore.app.dSYM.zip",
    )
  end

  desc "Upload Internal build to Crashlytics Beta"
  lane :upload_internal_crashlytics do
    setup_ci
    match(app_identifier: "tv.mycujoo.player.internal", type: "adhoc", readonly: true)
    crashlytics(
      # crashlytics_path: "./ios/Vendor/Fabric/Crashlytics.framework/",
      api_token: "99919asdf6f67b34c887b",
      build_secret: "1b47b24f11asdfffda3fb",
      ipa_path: "./builds/MycujooPlayer-Internal.ipa",
      # notes: changelog,
      groups: ["ios-player-internal"],
      notifications: true,
    )
  end

  desc "Bumps build number"
  lane :bump_build_number do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-build-number " + force
    new_build_number = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^BUILD_NUMBER = (\d+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump build to #{new_build_number}\""
    add_git_tag(tag: "build/#{new_build_number}")
  end

  desc "Bumps version full"
  lane :bump_version_full do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-full " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Bumps version major"
  lane :bump_version_major do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-major " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Bumps version minor"
  lane :bump_version_minor do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-minor " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Bumps version patch"
  lane :bump_version_patch do |opts|
    force = opts[:force]
    force = '' if force == nil
    sh "cd .. && ./scripts/.increment-version-string-patch " + force
    new_version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    sh "cd .. && git add mycujoo-player-ios/Configs/Shared.xcconfig"
    sh "cd .. && git commit -m \"bump version to #{new_version_string}\""
  end

  desc "Adds a tag with the current version, appending rc-<number>"
  lane :tag_with_version do
    version_string = File.read("../mycujoo-player-ios/Configs/Shared.xcconfig").match(/^VERSION_STRING = ([\d\.]+)$/)[1]
    final_tag_string = ""
    (1..100).each do |n|
      tag_string = "version/#{version_string}-rc#{n}"
      if !git_tag_exists(tag: tag_string)
        final_tag_string = tag_string
        break
      end
    end
    if final_tag_string != ""
      add_git_tag(tag: final_tag_string)
    end
  end

  desc "Create app manifest"
  lane :create_app_manifest do
    erb(
      template: "./fastlane/app-manifest.plist.erb",
      destination: "./builds/app-manifest.plist",
      placeholders: {
        :bundle_identifier => "tv.mycujoo.player.internal",
        :build_number => 24,
        :name => "mycujoo intrnl",
        :icon_url => "https://a1.files.diawi.com/app-icon/c7zCYsGasdfghCcr.png",
        :ipa_url => "https://a1.files.diawi.com/app-file/c7zCYa0DghCcr.ipa",
      },
    )
  end

  desc "Create app install html"
  lane :create_app_install do
    erb(
      template: "./fastlane/app-install.html.erb",
      destination: "./builds/app-install.html",
      placeholders: {
        :plist_url => "https://api.diawi.com/app-manifest/c7zCasdfhCcr.plist",
      },
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "[[APP_IDENTIFIER]]" # The bundle identifier of your app
apple_id "isadfv@masdfo.tv"
team_id "asdf"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.5.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.3        |
| cocoapods-check           | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.5.0        |
</details>


*generated on:* **2018-07-18**
</details>

**Comment by ravitripathi** [comment]
Please reopen this as its a valid request.
