### ISSUE TITLE
Gym fail when using with match

### ISSUE THREAD

**Issue by annpt1** [fastlane/fastlane#12913]
### Question Checklist
My plan is to let fastlane match certs and profiles before build a development version for team, upload to hockey all developers can do testing.

It will work if I run match first then run lane to export on hockey like this flow: 
Step 1: fastlane match development
Step 2: fastlane ios beta scheme: "xxx"
Like this it will export smoothly and upload to hockey.

fastfile as below
fastfine
> lane :beta do |options|
>     gym(
>       scheme: options[:scheme],
>       export_method: "development"
>     )
>     hockey(
>      api_token: "xxx",
>      notify: "0",
>      ipa: "./xxx.ipa",
>      dsym: "./xxx.app.dSYM.zip"
>     )
>   end

but if I add match and gym and hockey into 1 lane, it will stuck at gym with error. 

> lane :beta do |options|
>     **match(type: "development")**
>     gym(
>       scheme: options[:scheme],
>       export_method: "development"
>     )
>     hockey(
>      api_token: "xxx",
>      notify: "0",
>      ipa: "./xxx.ipa",
>      dsym: "./xxx.app.dSYM.zip"
>     )
>   end

I notice there is a different on generated plist file.
If running seperate match then gym&hockey the plist file will be like this.

> [18:24:54]: Generated plist file with the following values:
> [18:24:54]: ▸ -----------------------------------------
> [18:24:54]: ▸ {
> [18:24:54]: ▸   "method": "development"
> [18:24:54]: ▸ }
> [18:24:54]: ▸ -----------------------------------------
> 

but if I run all together in 1 lane

> [14:50:28]: ▸ -----------------------------------------
> [14:50:28]: ▸ {
> [14:50:28]: ▸   "provisioningProfiles": {
> [14:50:28]: ▸     "com.xxx.xxx": "iOS Team Provisioning Profile: com.xxx.xxx",
> [14:50:28]: ▸     "com.xxx.xxx.xxx-Today": "iOS Team Provisioning Profile: com.xxx.xxx.xxx-Today"
> [14:50:28]: ▸   },
> [14:50:28]: ▸   "method": "development",
> [14:50:28]: ▸   "signingStyle": "manual"
> [14:50:28]: ▸ }
> [14:50:28]: ▸ -----------------------------------------
> 

Stuck with error
`Provisioning profile "iOS Team Provisioning Profile: com.xxx.xxx" is Xcode managed, but signing settings require a manually managed profile.}`

> +---------------+-------------------------+
> |            Build environment            |
> +---------------+-------------------------+
> | xcode_path    | /Applications/Xcode.app |
> | gym_version   | 2.99.1                  |
> | export_method | development             |
> | sdk           | iPhoneOS11.4.sdk        |
> +---------------+-------------------------+

Anyone know how to config fastfile properly in my case?

**Comment by debeltranc** [comment]
From what I can tell your Xcode project has automatic code signing enabled, take a look at [this](https://docs.fastlane.tools/codesigning/getting-started/#automatic-manual-signing), also I don't know if you have done this already but match needs a git repository to manage all the certificates [(check this for reference)](https://docs.fastlane.tools/actions/match/#setup)
