### ISSUE TITLE
Snapshot always rebuild my project when snapshot each kind of simulator devices

### ISSUE THREAD

**Issue by TechGuyVN** [fastlane/fastlane#12929]
#### Motivation Behind Feature
Help react-native project and the others can get snapshot faster 

#### Feature Description

Because im using react-native, each time i run snapshot comand, in each simulator device, fastlane auto re-build project, and it take to long to screenshot get done. ( About over 15 minutes).
I need a action can install file .app already build and run on simulator to screenshot instead of re-build project to snapshot.

**Comment by janpio** [comment]
`test_without_building` exists as a parameter for the action: https://docs.fastlane.tools/actions/capture_ios_screenshots/#parameters Have you tried using that?
