### ISSUE TITLE
return value or set env variable

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12921]
hi all
i want to get version number so i need to return value from Fastlane. So i tried to set ENV var.

 version =  get_version_number(xcodeproj: "ios/me.xcodeproj")
 UI.error("Version : " +  version)
 ENV['IOS_VERSION'] = version
 sh("export IOS_VERSION='"+version+"'")

Both tries were failed. Icould not get IOS_VERSION variable.  I could write to the file and read again. But is there any good solution.?

thanks

**Comment by johnknapprs** [comment]
ENV is a ruby environment variable, it's not set in the shell.  One way to to that would be this:

`sh("export IOS_VERSION=#{version}'")`

**Comment by baturorkun** [comment]
hi johnknapprs
i tried this one.

#!/bin/bash
fastlane ios test
echo $IOS_VERSION   --> NULL

i ran Fastlane command in shell and i used   sh("export IOS_VERSION=#{version}")    in fastlane. But i could not get value.
