### ISSUE TITLE
Running 'fastlane test' - 77e2717c1dff8bf43b0d332d662b9a0d

### ISSUE THREAD

**Issue by nagra** [fastlane/fastlane#1292]
Hey guys,

When running 'fastlane test' command, it got to a point before crashing. It then asked me to create an issue with the following key: '77e2717c1dff8bf43b0d332d662b9a0d'.

Thanks,
Kam

**Comment by KrauseFx** [comment]
Please share the complete output when running `fastlane`. It seems like you have a build error.

**Comment by KrauseFx** [comment]
It's not really a crash, but a failing build/test

**Comment by mfurtak** [comment]
Hi @nagra - I'm going to close this issue for now. Please reopen it as needed! :+1:
