### ISSUE TITLE
[MATCH] Get dynamic configuration with enterprise / appstore.

### ISSUE THREAD

**Issue by VPecquerie** [fastlane/fastlane#12923]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi, we have an issue with fastlane and appstore / enterprise build on a react application.
I just walk around a lot of issue searching answer to my issue without success.

We have two apple licenses one developper and one enterprise.
As I understood, enterprise can't build app-store package.

Tried to used this : https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning
Without success.

Certs for development and distribution are well imported on the repository.
Profiles for appstore and development are existing both in repository and apple developer portal.

Also tried to add those steps in beta lane :
<details>
  <pre>
  update_project_team(
    path: "./ios/#{ENV['PROJECT_NAME']}.xcodeproj",
    teamid: ENV['DEVELOPER_TEAM_ID']
  )
  update_project_codesigning(
    path: "./ios/#{ENV['PROJECT_NAME']}.xcodeproj",
    use_automatic_signing: true,
    team_id: ENV['DEVELOPER_TEAM_ID']
  )
  </pre>
</details>

The goal is to have two lane : one for appstore which publish app to testflight for the moment and one enterprise which build an enterprise IPA.
For the moment I'm focused on the app-store part.

Here is the **.env** file  : (sensible data has been replaced ;) )

<details>
  <pre>
    PROJECT_NAME=CIHelloWorld
    APPSTORE_BUNDLE_ID=XXXXXXX.appstore
    ENTERPRISE_BUNDLE_ID=XXXXXX.entreprise
    GIT_REMOTE_URL=ssh://git@XXXXXX:YYYY/XXXXXX/XXXXXX.git

    # You should not modify those lines...
    DEVELOPER_TEAM_LOGIN=XXX.YYY@XXXX.YYYY
    DEVELOPER_TEAM_ID=YYYYYYYYYYY

    ENTERPRISE_TEAM_LOGIN=XXX.ZZZ@XXXX.YYYY
    ENTERPRISE_TEAM_ID=XXXXXXXXXX
  </pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[10:12:54]: fastlane detected a Gemfile in the current directory
[10:12:54]: however it seems like you don't use `bundle exec`
[10:12:54]: to launch fastlane faster, please use
[10:12:54]:
[10:12:54]: $ bundle exec fastlane ios beta
[10:12:54]:
[10:12:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+--------------------------------------------+---------+----------------------------+
|                                   Used plugins                                    |
+--------------------------------------------+---------+----------------------------+
| Plugin                                     | Version | Action                     |
+--------------------------------------------+---------+----------------------------+
| fastlane-plugin-update_project_codesigning | 0.2.0   | update_project_codesigning |
+--------------------------------------------+---------+----------------------------+

[10:12:55]: -----------------------------
[10:12:55]: --- Step: update_fastlane ---
[10:12:55]: -----------------------------
[10:12:55]: Looking for updates for fastlane...
[10:12:55]: It seems that your Gem directory is not writable by your current user.
[10:12:55]: fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
[10:12:55]: If you still want to use this action, please read the documentation on how to set this up:
[10:12:55]: https://docs.fastlane.tools/actions/#update_fastlane
[10:12:55]: Driving the lane 'ios beta' 🚀
[10:12:55]: --------------------------------------------
[10:12:55]: --- Step: Switch to ios match_store lane ---
[10:12:55]: --------------------------------------------
[10:12:55]: Cruising over to lane 'ios match_store' 🚖
[10:12:55]: -------------------
[10:12:55]: --- Step: match ---
[10:12:55]: -------------------
ssh://git@XXXXXX:YYYY/XXXXXX/XXXXXX.git
[10:12:55]: Successfully loaded '/Users/vpecquerie/projects/pro/ReactHelloWorld/fastlane/Matchfile' 📄

+---------+-----------------------------------------------------------------------+
|                   Detected Values from './fastlane/Matchfile'                   |
+---------+-----------------------------------------------------------------------+
| git_url | ssh://git@XXXXXX:YYYY/XXXXXX/XXXXXX.git |
+---------+-----------------------------------------------------------------------+

+-----------------------+-----------------------------------------------------------------------+
|                                   Summary for match 2.99.1                                    |
+-----------------------+-----------------------------------------------------------------------+
| git_url               | ssh://git@XXXXXX:YYYY/XXXXXX/XXXXXX.git |
| type                  | appstore                                                              |
| username              | xxxx.yyyyy@xxxxx.xxx                                                  |
| team_id               | XXXXXXXXXX                                                            |
| app_identifier         | ["XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore"]                              |
| shallow_clone         | false                                                                 |
| readonly              | true                                                                  |
| git_branch            | master                                                                |
| keychain_name         | login.keychain                                                        |
| verbose               | false                                                                 |
| force                 | false                                                                 |
| skip_confirmation     | false                                                                 |
| clone_branch_directly | false                                                                 |
| force_for_new_devices | false                                                                 |
| skip_docs             | false                                                                 |
| platform              | ios                                                                   |
+-----------------------+-----------------------------------------------------------------------+

[10:12:55]: Cloning remote git repo...
[10:12:55]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:12:56]: 🔓  Successfully decrypted certificates repo
[10:12:56]: Installing certificate...

+-------------------+------------------------------------------------------------------------------------------+
|                                            Installed Certificate                                             |
+-------------------+------------------------------------------------------------------------------------------+
| User ID           | XXXXXXX                                                                                  |
| Common Name       | iPhone Distribution: XXXXXXX (XXXXXXX)                                                   |
| Organisation Unit | XXXXXXX                                                                                  |
| Organisation      | XXXXXXX                                                                                  |
| Country           | US                                                                                       |
| Start Datetime    | 2018-07-18 06:35:56 UTC                                                                  |
| End Datetime      | 2019-07-18 06:35:56 UTC                                                                  |
+-------------------+------------------------------------------------------------------------------------------+

[10:12:57]: Installing provisioning profile...

+---------------------+----------------------------------------------------------------+------------------------------------------------------------+
|                                                            Installed Provisioning Profile                                                          |
+---------------------+-----------------------------------------------------------------+-----------------------------------------------------------+
| Parameter           | Environment Variable                                            | Value                                                     |
+---------------------+-----------------------------------------------------------------+-----------------------------------------------------------+
| App Identifier       |                                                                 | XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore                      |
| Type                |                                                                 | appstore                                                  |
| Platform            |                                                                 | ios                                                       |
| Profile UUID         | sigh_XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore                       | e9a5e538-a304-4f2a-8cd9-070d07402a90                      |
| Profile Name         | sigh_XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore_profile-name           | match AppStore XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore       |
| Profile Path         | sigh_XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore_profile-path           | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision |
| Development Team ID | sigh_XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore_team-id               | XXXXXXXXXX                                                |
+---------------------+-----------------------------------------------------------------+-----------------------------------------------------------+

[10:12:57]: All required keys, certificates and provisioning profiles are installed 🙌
[10:12:57]: Setting Provisioning Profile type to 'app-store'
[10:12:57]: Cruising back to lane 'ios beta' 🚘
[10:12:57]: ------------------------------------
[10:12:57]: --- Step: automatic_code_signing ---
[10:12:57]: ------------------------------------

+-----------------------+--------------------------------------+
|              Summary for Automatic Codesigning               |
+-----------------------+--------------------------------------+
| path                  | ./ios/CIHelloWorld.xcodeproj         |
| use_automatic_signing | true                                 |
| team_id               | XXXXXXXXXX                           |
| bundle_identifier      | XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore |
+-----------------------+--------------------------------------+

[10:12:57]: Updating the Automatic Codesigning flag to enabled for the given project '/Users/vpecquerie/projects/pro/ReactHelloWorld/ios/CIHelloWorld.xcodeproj/project.pbxproj'
[10:12:57]: Set Team id to: A45FYGHS6V for target: CIHelloWorldTests
[10:12:57]: Set Bundle identifier to: XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore for target: CIHelloWorldTests
[10:12:57]: Set Team id to: A45FYGHS6V for target: CIHelloWorld-tvOS
[10:12:57]: Set Bundle identifier to: XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore for target: CIHelloWorld-tvOS
[10:12:57]: Set Team id to: A45FYGHS6V for target: CIHelloWorld-tvOSTests
[10:12:57]: Set Bundle identifier to: XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore for target: CIHelloWorld-tvOSTests
[10:12:57]: Successfully updated project settings to use Code Sign Style = 'Automatic'
[10:12:57]: Modified Targets:
[10:12:57]: 	 * CIHelloWorldTests
[10:12:57]: 	 * CIHelloWorld-tvOS
[10:12:57]: 	 * CIHelloWorld-tvOSTests
[10:12:57]: -----------------
[10:12:57]: --- Step: gym ---
[10:12:57]: -----------------
[10:12:57]: $ xcodebuild -showBuildSettings -scheme CIHelloWorld -project ./ios/CIHelloWorld.xcodeproj
+------------------------------------+-------------------------------------------------------------------------------------------------+
|                                                             Lane Context                                                             |
+------------------------------------+-------------------------------------------------------------------------------------------------+
| PLATFORM_NAME                      | ios                                                                                             |
| LANE_NAME                          | ios beta                                                                                        |
| SIGH_PROFILE_TYPE                  | app-store                                                                                       |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"XXXXXXXXXXXXXXXXXXXXXXXXXX.appstore "=>"match AppStore XXXXXXXXXXXXXXXXXXXXXXXXXX.appstore "} |
+------------------------------------+-------------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------+---------------------------------------------------------------+
|                                                          Summary for gym 2.99.1                                                          |
+--------------------------------------------------------------------------+---------------------------------------------------------------+
| project                                                                  | ./ios/CIHelloWorld.xcodeproj                                  |
| scheme                                                                   | CIHelloWorld                                                  |
| export_method                                                            | app-store                                                     |
| export_options.provisioningProfiles.XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore  | match AppStore XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore            |
| destination                                                              | generic/platform=iOS                                          |
| output_name                                                              | CIHelloWorld                                                  |
| build_path                                                               | /Users/vpecquerie/Library/Developer/Xcode/Archives/2018-07-18 |
| clean                                                                    | false                                                         |
| output_directory                                                         | .                                                             |
| silent                                                                   | false                                                         |
| skip_package_ipa                                                         | false                                                         |
| result_bundle                                                            | false                                                         |
| buildlog_path                                                            | ~/Library/Logs/gym                                            |
| skip_profile_detection                                                   | false                                                         |
| xcode_path                                                               | /Applications/Xcode.app                                       |
+--------------------------------------------------------------------------+---------------------------------------------------------------+

[10:24:59]: $ set -o pipefail && xcodebuild -scheme CIHelloWorld -project ./ios/CIHelloWorld.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/vpecquerie/Library/Developer/Xcode/Archives/2018-07-18/CIHelloWorld\ 2018-07-18\ 10.24.59.xcarchive archive | tee /Users/vpecquerie/Library/Logs/gym/CIHelloWorld-CIHelloWorld.log | xcpretty

[10:25:07]: ▸ Check Dependencies
[10:25:07]: ▸ Compiling raw_logging.cc
[10:25:08]: ▸ Compiling StringBase.cpp
[10:25:09]: ▸ ⚠️  /Users/vpecquerie/projects/pro/ReactHelloWorld/node_modules/react-native/React/../third-party/folly-2016.09.26.00/folly/String.h:623:11: parameter 'len' not found in the function declaration [-Wdocumentation]
[10:25:09]: ▸ * @param len Length of str, in bytes
[10:25:09]: ▸        ^
[10:25:09]: ▸ Compiling Conv.cpp
[10:25:10]: ▸ Compiling signalhandler.cc
[10:25:10]: ▸ ⚠️  /Users/vpecquerie/projects/pro/ReactHelloWorld/node_modules/react-native/third-party/glog-0.3.4/src/signalhandler.cc:74:19: unused parameter 'ucontext_in_void' [-Wunused-parameter]
[10:25:10]: ▸ void* GetPC(void* ucontext_in_void) {
[10:25:10]: ▸           ^~~
[10:25:10]: ▸ Compiling dynamic.cpp
[10:25:11]: ▸ ⚠️  

[... A VERY LONG XCODE BUILD ...]

** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[10:27:04]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.99.1                  |
| export_method | app-store               |
| sdk           | iPhoneOS11.4.sdk        |
+---------------+-------------------------+

[10:27:04]: ▸ === BUILD TARGET CIHelloWorld OF PROJECT CIHelloWorld WITH CONFIGURATION Release ===
[10:27:04]: ▸ Check dependencies
[10:27:04]: ▸ Code Signing Error: Signing for "CIHelloWorld" requires a development team. Select a development team in the project editor.
[10:27:04]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'
[10:27:04]:
[10:27:04]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[10:27:04]: 📋  For the complete and more detailed error log, check the full log at:
[10:27:04]: 📋  /Users/vpecquerie/Library/Logs/gym/CIHelloWorld-CIHelloWorld.log
[10:27:04]:
[10:27:04]: Looks like fastlane ran into a build/archive error with your project
[10:27:04]: It's hard to tell what's causing the error, so we wrote some guides on how
[10:27:04]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[10:27:04]: Before submitting an issue on GitHub, please follow the guide above and make
[10:27:04]: sure your project is set up correctly.
[10:27:04]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[10:27:04]: the full commands printed out in yellow in the above log.
[10:27:04]: Make sure to inspect the output above, as usually you'll find more error information there
[10:27:04]:
+------------------------------------+-------------------------------------------------------------------------------------------------+
|                                                             Lane Context                                                             |
+------------------------------------+-------------------------------------------------------------------------------------------------+
| PLATFORM_NAME                      | ios                                                                                             |
| LANE_NAME                          | ios beta                                                                                        |
| SIGH_PROFILE_TYPE                  | app-store                                                                                       |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore "=>"match AppStore XXXXXXXXXXXXXXXXXXXXXXXXXXX.appstore "} |
+------------------------------------+-------------------------------------------------------------------------------------------------+
[10:27:04]: Error building the application - see the log above

+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 1    | update_fastlane                | 0           |
| 2    | Switch to ios match_store lane | 0           |
| 3    | match                          | 2           |
| 4    | automatic_code_signing         | 0           |
| 💥   | gym                            | 127         |
+------+--------------------------------+-------------+

[10:27:05]: fastlane finished with errors

[!] Error building the application - see the log above

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.5                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.5 (17F77)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | fr_FR.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane

platform :ios do

  private_lane :match_store do |options|
    match(
      git_url: ENV['GIT_REMOTE_URL'],
      type: 'appstore',
      username: ENV['DEVELOPER_TEAM_LOGIN'],
      team_id: ENV['DEVELOPER_TEAM_ID'],
      team_name: ENV['DEVELOPER_TEAM_NAME'],
      app_identifier: ENV['APPSTORE_BUNDLE_ID'],
      shallow_clone: false,
      readonly: true
    )
  end

  private_lane :match_inhouse do |options|
    match(
      git_url: ENV['GIT_REMOTE_URL'],
      type: 'enterprise',
      username: ENV['ENTERPRISE_TEAM_LOGIN'],
      team_id: ENV['ENTERPRISE_TEAM_ID'],
      team_name: ENV['ENTERPRISE_TEAM_NAME'],
      app_identifier: ENV['ENTERPRISE_BUNDLE_ID'],
      shallow_clone: false,
      readonly: true
    )
  end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do 
    match_store

    automatic_code_signing(
      path: "./ios/#{ENV['PROJECT_NAME']}.xcodeproj",
      use_automatic_signing: true,
      team_id: ENV['DEVELOPER_TEAM_ID'],
      bundle_identifier: ENV['APPSTORE_BUNDLE_ID']
    )
    gym(project: "./ios/#{ENV['PROJECT_NAME']}.xcodeproj",
        scheme: ENV['PROJECT_NAME']
    ) 
    pilot
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
for_platform :ios do

  app_identifier ENV['APPSTORE_BUNDLE_ID']
  apple_id ENV['DEVELOPER_TEAM_LOGIN']
  team_id ENV['DEVELOPER_TEAM_ID']

  for_lane :enterprise do
    app_identifier ENV['ENTERPRISE_BUNDLE_ID']
    apple_id ENV['ENTERPRISE_TEAM_LOGIN']
    team_id ENV['ENTERPRISE_TEAM_ID']
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| did_you_mean                               | 1.0.0        |
| slack-notifier                             | 2.3.2        |
| atomos                                     | 0.1.2        |
| CFPropertyList                             | 3.0.0        |
| claide                                     | 1.0.2        |
| colored2                                   | 3.1.2        |
| nanaimo                                    | 0.2.6        |
| xcodeproj                                  | 1.5.9        |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.2.8        |
| terminal-notifier                          | 1.8.0        |
| unicode-display_width                      | 1.4.0        |
| terminal-table                             | 1.8.0        |
| plist                                      | 3.4.0        |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.2        |
| multipart-post                             | 2.0.0        |
| word_wrap                                  | 1.0.0        |
| tty-spinner                                | 0.8.0        |
| babosa                                     | 1.0.2        |
| colored                                    | 1.2          |
| highline                                   | 1.7.10       |
| commander-fastlane                         | 4.4.6        |
| excon                                      | 0.62.0       |
| faraday                                    | 0.15.2       |
| unf_ext                                    | 0.0.7.5      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20180417 |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| fastimage                                  | 2.1.3        |
| gh_inspector                               | 1.1.3        |
| mini_magick                                | 4.5.1        |
| multi_json                                 | 1.13.1       |
| multi_xml                                  | 0.6.0        |
| rubyzip                                    | 1.2.1        |
| security                                   | 0.1.3        |
| xcpretty-travis-formatter                  | 1.0.0        |
| bundler                                    | 1.16.2       |
| faraday_middleware                         | 0.12.2       |
| naturally                                  | 2.2.0        |
| simctl                                     | 1.6.5        |
| uber                                       | 0.1.0        |
| declarative                                | 0.0.10       |
| declarative-option                         | 0.1.0        |
| representable                              | 3.0.4        |
| retriable                                  | 3.1.2        |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| little-plugger                             | 1.1.4        |
| logging                                    | 2.2.2        |
| jwt                                        | 2.1.0        |
| memoist                                    | 0.16.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.8.1        |
| googleauth                                 | 0.6.2        |
| httpclient                                 | 2.8.3        |
| google-api-client                          | 0.21.2       |
| emoji_regex                                | 0.1.1        |
| tty-cursor                                 | 0.6.0        |
| tty-screen                                 | 0.6.5        |
| json                                       | 2.1.0        |
| io-console                                 | 0.4.5        |
| libxml-ruby                                | 2.9.0        |
| dotenv                                     | 2.5.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
</details>

*generated on:* **2018-07-18**
</details>

**Comment by VPecquerie** [comment]
[CIHelloWorld-CIHelloWorld.log](https://github.com/fastlane/fastlane/files/2205026/CIHelloWorld-CIHelloWorld.log)

**Comment by VPecquerie** [comment]
Tried to used this : https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning

**Comment by VPecquerie** [comment]
Certs for development and distribution are well imported on the repository.
Profiles for appstore and development are existing both in repository and apple developer portal.

**Comment by VPecquerie** [comment]
Also tried to ass those steps in beta lane : 

  ```
    update_project_team(
      path: "./ios/#{ENV['PROJECT_NAME']}.xcodeproj",
      teamid: ENV['DEVELOPER_TEAM_ID']
    )
    update_project_codesigning(
      path: "./ios/#{ENV['PROJECT_NAME']}.xcodeproj",
      use_automatic_signing: true,
      team_id: ENV['DEVELOPER_TEAM_ID']
    )
   ```

**Comment by VPecquerie** [comment]
The goal is to have two lane : one for appstore which publish app to testflight for the moment and one enterprise which build an enterprise IPA.

**Comment by VPecquerie** [comment]
For the moment I'm focused on the app-store part.

**Comment by mickael76** [comment]
Hi, same error message : "Code Signing Error: Code signing is required for product type" 
:-(
