### ISSUE TITLE
undefined method when running frameit

### ISSUE THREAD

**Issue by donnellyk** [fastlane/fastlane#12934]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running `fastlane frameit --verbose`, if I try to include a title and keyword with the image, I get a ruby error `undefined method *' for nil:NilClass` when there is an image name matches a filter. If I remove the filter, all images are framed (without background/text) successfully. The complete `--verbose` output as been included in Details below.

Framefile.json
```
{
  "device_frame_version": "latest",
  "default": {
    "background": "./screenshot_photos/background.jpg"
  },
  "data": [
    {
      "filter": "Explore",
      "keyword": {
        "color": "#d21559",
        "text": "Bar"
      },
      "title": {
        "text": "Foo"
      }
    }
  ]
}
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$[fastlane frameit --verbose
[✔] 🚀 
[15:49:09]: fastlane detected a Gemfile in the current directory
[15:49:09]: however it seems like you don't use `bundle exec`
[15:49:09]: to launch fastlane faster, please use
[15:49:09]: 
[15:49:09]: $ bundle exec fastlane frameit --verbose
[15:49:09]: 
[15:49:09]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path REMOVED
-------
DEBUG [2018-07-19 15:49:10.33]: Parsing config file './screenshots/Framefile.json'
INFO [2018-07-19 15:49:10.33]: Using device frames version 'latest'
[⠋] Framing screenshot './screenshots/en-US/iPhone X-Explore.png' DEBUG [2018-07-19 15:49:10.71]: Looking for Apple iPhone X Space Gray and found 1 template(s)
DEBUG [2018-07-19 15:49:10.71]: Looking for Apple iPhone X Space Gray and found 1 template(s)
[⠧] Framing screenshot './screenshots/en-US/iPhone X-Explore.png' DEBUG [2018-07-19 15:49:11.45]: Parsing config file '/Users/foo/git/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/en-US/iPhone X-Explore.png' ERROR [2018-07-19 15:49:13.88]: undefined method `*' for nil:NilClass
ERROR [2018-07-19 15:49:13.88]: Backtrace:
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/editor.rb:180:in `scale_padding'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/editor.rb:171:in `vertical_frame_padding'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/editor.rb:122:in `complex_framing'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/editor.rb:33:in `frame!'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/screenshot.rb:125:in `frame!'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/runner.rb:42:in `block in run'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/runner.rb:28:in `each'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/runner.rb:28:in `run'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/commands_generator.rb:43:in `block (2 levels) in run'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/commands_generator.rb:103:in `run'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/frameit/lib/frameit/commands_generator.rb:19:in `start'
	/Users/foo/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.100.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	/Users/foo/.rvm/gems/ruby-2.5.1@global/gems/fastlane-2.100.0/bin/fastlane:20:in `<top (required)>'
	/usr/local/bin/fastlane:23:in `load'
	/usr/local/bin/fastlane:23:in `<main>'
	/Users/foo/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:24:in `eval'
	/Users/foo/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:24:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.2       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-07-19**
</details></pre>
</details>

**Comment by donnellyk** [comment]
Add `padding` seems to do the trick. Is that a required param in the json file?

**Comment by kasyanov-ms** [comment]
Spent two hours searching for the solution. Maybe it should be added to the documentation?
