### ISSUE TITLE
fastlane slow

### ISSUE THREAD

**Issue by sjoerdvdvis** [fastlane/fastlane#1293]
Since I updated my fastlane toolset using "sudo gem update", it takes literally minutes before fastlane starts the lane... Anyone else experiencing this issue?

**Comment by KrauseFx** [comment]
Can you run `gem cleanup`

**Comment by sjoerdvdvis** [comment]
This helped a lot, thanks Felix!

**Comment by i2amsam** [comment]
Great! :+1:
