### ISSUE TITLE
when fastlane upload app to AppStore for new account it requires sms?

### ISSUE THREAD

**Issue by dariyaprokopovych** [fastlane/fastlane#12937]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by heartofagoof** [comment]
Are you talking about two factor authentication? If so, https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

**Comment by joshdholtz** [comment]
That is what it sounds like ^ 

@dariyaprokopovych The best approach is to use a separate account for fastlane related things that has two factor auth if you can (as it makes everything easier to use and you can revoke that account at anytime)
