### ISSUE TITLE
How to make fastlane use http proxy?

### ISSUE THREAD

**Issue by an0** [fastlane/fastlane#12935]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm seeing ssl errors:
>SSL_connect returned=1 errno=0 state=error: certificate verify failed

I've read others ssl issues and also https://docs.fastlane.tools/faqs/#im-getting-an-ssl-error.

I'm behind an enterprise firewall and need to setup http proxy environment variables `ALL_PROXY` and `http_proxy` for other cli tools(like `brew`) to work. However `fastlane` doesn't work. Does it use different proxy envs?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>### Captured Output

Command Used: `init swift`
<details><summary>Output/Log</summary>

```

DEBUG [2018-07-19 16:47:59.50]: Checking if there are any plugins that should be loaded...
INFO [2018-07-19 16:47:59.60]: Detected iOS/Mac project in current directory...
INFO [2018-07-19 16:47:59.60]: This setup will help you get up and running in no time.
INFO [2018-07-19 16:47:59.60]: fastlane will check what tools you're already using and set up
INFO [2018-07-19 16:47:59.60]: the tool automatically for you. Have fun! 
INFO [2018-07-19 16:47:59.60]: $ xcodebuild -list -workspace ./App.xcworkspace
INFO [2018-07-19 16:48:00.68]: $ xcodebuild -showBuildSettings -workspace ./App.xcworkspace -scheme Alamofire
WARN [2018-07-19 16:48:01.89]: Your Apple ID (e.g. fastlane@krausefx.com): 

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
ERROR [2018-07-19 16:48:02.11]: Error finding relevant GitHub issues: SSL_connect returned=1 errno=0 state=error: certificate verify failed


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2018-07-19**
</details></pre>
</details>

**Comment by janpio** [comment]
Hey @an0, are you seeing the error anywhere else besides the Github error search?
Can you run the same command with `--verbose` please?
Did you try upgrading openssl as the FAQ indicate?

**Comment by revolter** [comment]
This might be an issue with https://github.com/orta/gh_inspector.

**Comment by pajapro** [comment]
Hi @an0 have you found a way to how to make fastlane use proxy envs? I am facing the same SSL issue now, when using `sigh` on corporate network

**Comment by an0** [comment]
@pajapro no, I'm still tolerating it.
