### ISSUE TITLE
ios deploy on ready

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12948]
hi all

i am using this command :

upload_to_testflight(
       changelog: changelog,
       beta_app_description: "Develop Test",
       beta_app_feedback_email: "batur@xxx.com",
       skip_waiting_for_build_processing: false
     )

My app can be on the test flight. But i want to send my app to review. i don't want to connect iTunes and do it manually.
thanks

**Comment by debeltranc** [comment]
If I understand correctly what you want is not to send your build to TestFlight _per se_ but send a new version to review? if that's the case, you shouldn't use `upload_to_testflight`. use [Deliver](https://docs.fastlane.tools/actions/deliver/) instead.

**Comment by debeltranc** [comment]
@baturorkun If you specify `submit_for_review: true` within `Deliver`, What will happen is that the artifact you generated Will be uploaded to TestFlight and then attached to the version to be submitted to review (upon Apple's build review process). However, if `submit_for_review: false` is specified, The build will be uploaded to TestFlight and (IIRC) you will have to select it manually afterwards when you decide to submit it to Store Review.

**Comment by baturorkun** [comment]
There is another two commands: upload_to_testflight and pilot 
Normally  i use upload_to_testflight to upload test flight.

 upload_to_testflight(
       changelog: changelog,
       beta_app_description: "Minor bug fixes and improvements",
       beta_app_feedback_email: "batu@me",
       skip_waiting_for_build_processing: false
     )

Can i use like that:

 deliver (
       submit_for_review: false,
       changelog: changelog,
       beta_app_description: "Minor bug fixes and improvements",
       beta_app_feedback_email: "batu@me",
       skip_waiting_for_build_processing: false
     )

Then if i want to deliver production, it is enough to change  "submit_for_review: true " ?

**Comment by debeltranc** [comment]
Keep in mind that `upload_to_testflight` and `pilot` are the same action.

`deliver` , on the other side, doesn't manage that kind of information because its purpose is to upload to the App Store, the only interaction with TestFlight is the upload of a build. However, `deliver` manages metadata [(check this out!)](https://docs.fastlane.tools/actions/deliver/#tips).
