### ISSUE TITLE
which simulators are used?

### ISSUE THREAD

**Issue by tofutim** [fastlane/fastlane#12942]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
fastlane snapshot simulators

#### Question Description
I have an app that requires some setup. I've gone ahead and setup all the simulators on XCode and want to make snapshots with fastlane, but somehow, it seems that it is always running new simulators with no data. Is there I can get fastlane to run the XCode version? Or is it always a new simulator?

**Comment by joshdholtz** [comment]
@tofutim Heyyyy 👋 Your best bet (if you are trying to specify specific iOS versions in simulators) is to name them with the OS version that you are going after. So name it something like "iPhone 6 - 11.4" or "iPhone 6 - 10.1" and then in your `Fastfile` do something like...

```rb
snapshot(
  devices: ["iPhone 6 - 11.4", "iPhone 6 - 10.1"]
)
```

**Comment by ppamorim** [comment]
@joshdholtz This is not working.

**Comment by joshdholtz** [comment]
@ppamorim That was my bad, I totally though you could specify by simulator name but I guess not 🤔 I'm looking into fixing this right now

**Comment by joshdholtz** [comment]
@ppamorim It worked for me 🤔 

## Step 1: Create simulator with unique name
![screen shot 2018-08-02 at 8 30 39 am](https://user-images.githubusercontent.com/401294/43589843-3123b644-9635-11e8-85ed-2af1e021e678.png)

## Step 2: Find it to make sure that exists
![screen shot 2018-08-02 at 8 30 47 am](https://user-images.githubusercontent.com/401294/43589856-3656e7c6-9635-11e8-8a05-6c391c70d242.png)

## Step 3: Update the name in `Fastfile` (or in your command line command)
![screen shot 2018-08-02 at 9 21 20 am](https://user-images.githubusercontent.com/401294/43589952-74cae4bc-9635-11e8-8976-9740fa3c71e3.png)

## Step 4: Verify in logs is calling the correct simulator
![screen shot 2018-08-02 at 9 07 55 am](https://user-images.githubusercontent.com/401294/43589878-40734470-9635-11e8-9f75-a25a7d389b7d.png)
