### ISSUE TITLE
[snapshot] Add parameter to generate Snapshot reports with columns and rows reversed

### ISSUE THREAD

**Issue by BJap** [fastlane/fastlane#12949]
#### Motivation Behind Feature
The reason behind this is that during review, most displays are widescreen, and it really helps to have all of the first snapshot in all languages side by side to swipe left and right. Then it’s possible to move down to the next row for the second snapshot, etc. A big display is used for reviews also so it’s mounted in widescreen orientation.

The gain is this would allow more of the same snapshot on the display at once, organized together. This is standard for the review process to do one screen at at time in a group setting.

#### Feature Description
There is a `reports_generator.rb` that is run at the end of snapshot tests, and can also be called on its own. This by default will generate rows, one for each language, and columns, one for each snapshot.

The desire is to provide an argument or capability to reverse this. Each column would be each language, and, each row would be the same snapshot. Row 1 would be all the snapshot 1's, row 2 would be all the snapshot 2's, etc.

The default would of course still be left to the current report generation paradigm so as to not break existing usage.

#### Alternatives or Workarounds
None that I am aware of other than to hard code an HTML or write a separate script.

**Comment by BJap** [comment]
@joshdholtz I'd love to test this out wow! How would I switch my local version to this version? Is there a direction set somewhere I can follow?

**Comment by joshdholtz** [comment]
@BJap Assuming you are using a `Gemfile`, you can change your `Gemfile` to...
```
gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'joshdholtz-snapshot-rows-by-screenshot'
```
and then run `bundle install`

To verify its switched properly, you can run `fastlane action snapshot` and look at the available options for `html_summary_format`

Hopefully that does it for you 💪 🙃

**Comment by joshdholtz** [comment]
@BJap Yessssss, gald it worked! I will make the code prettier now and also make it work for _snapshot_ (incase you need this for Android as well)

**Comment by BJap** [comment]
@joshdholtz I am excited to see the progress on this. Did you need any more runs to test it out? I could show my Android team but I am unsure if we are using snapshot.
