### ISSUE TITLE
Crashlytics not sending emails to test group

### ISSUE THREAD

**Issue by ctews** [fastlane/fastlane#1294]
Hey guys,

I just setup a fresh fastlane setup today. Just to give some kudos, this thing is a real nice beast!

Now coming to my problem. Everything works fine apart from Crashlytics email notifications. Here is the snippet from my Fastfile:

```
    # Crashlytics config
    crashlytics(api_token:"xxx",
                build_secret:"xxx",
                notes:changelog,
                groups:['internal-tester'],
                notifications: true)
```

Neither `notifications:true` nor `notifications:"YES"` is working to send out emails :( Any error on my side?
Thx in advance!

**Comment by i2amsam** [comment]
@ctews could you PM me the name of the app & build version?  I'll take a look, the configuration looks good at first glance.

**Comment by i2amsam** [comment]
@ctews could you also add the `debug: true` option to the configuration and run with --verbose and add the output?

**Comment by ctews** [comment]
Thank you for the fast reply @i2amsam! It was just my stupid mistake, hadn't setup `cert` & `sigh` correctly so the UDID of the device wasn't included in the bundle. Got it working now! :)

So the parameter of `crashlytics` is working fine!
