### ISSUE TITLE
How It's Work For In-app-purchase in ios Using fastlane?

### ISSUE THREAD

**Issue by Devloperios** [fastlane/fastlane#12946]
i Dont know How It's Work For In-app-purchase in Ios.

If possible To share your Example code or Any Extra Suggestion ?

i Alreay Created App in Ios . And Adding Automatically In-app-purchase Using fastlane in app.

please suggest me Best Solution. How Can it's Work ?

**Comment by debeltranc** [comment]
As far as I know In-App purchases are not supported within _deliver_. What I have done in the past is to manage those using Spaceship, which has a feature that supports IAP's #7834

**Comment by joshdholtz** [comment]
@Devloperios What @debeltranc is correct. There is not "action" for managing in-app purchases because of their complexity. You will have to write custom Ruby using Spaceship. Below is an example of mine that you can use as a model for your own implementation 😊 

```ruby
lane :create_iap_nonconsume do
  fastlane_require 'spaceship'
  Spaceship::Tunes.login("your@email.com")
  app = Spaceship::Tunes::Application.find("com.your.bundle.id")
 
  app.in_app_purchases.create!(
  type: Spaceship::Tunes::IAPType::NON_CONSUMABLE,
  versions: {
    "en-US" => {
      name: "Nonconsume1",
      description: "This is the nonconsum 1 description"
    }
  },
  reference_name: "non_consume_1",
  product_id: "com.your.bundle.id.nonconsume1",
  cleared_for_sale: true,
  review_notes: "A note for a reviewer",
  review_screenshot: "test_nonconsume1.png",
  pricing_intervals:
    [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: 1
      }
    ]
  )
end
```
