### ISSUE TITLE
fastlane init does not succeed maybe because UI.current is not defined

### ISSUE THREAD

**Issue by nmatsuo63** [fastlane/fastlane#12944]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane init does not succeed. "It says Helper.log is deprecated. Use `UI` class instead
[!] Unknown method 'current', "

Could you please help my fastlane life?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>myPCname:firefox-ios matsuMac$ fastlane init
[12:38:26]: ----------------------------------------
[12:38:26]: --- Step: Verifying fastlane version ---
[12:38:26]: ----------------------------------------
[12:38:26]: Your fastlane version 2.100.1 matches the minimum requirement of 1.39.0  ✅
[12:38:26]: ------------------------------
[12:38:26]: --- Step: default_platform ---
[12:38:26]: ------------------------------
[12:38:26]: --------------------------------
[12:38:26]: --- Step: import_build_tools ---
[12:38:26]: --------------------------------
[12:38:26]: Helper.log is deprecated. Use `UI` class instead

[!] Unknown method 'current', supported [:error, :important, :success, :message, :deprecated, :command, :command_output, :verbose, :header, :content_error, :interactive?, :input, :confirm, :select, :password, :crash!, :user_error!, :shell_error!, :build_failure!, :test_failure!, :abort_with_message!, :not_implemented]
myPCname:firefox-ios matsuMac$ ls</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/. 

fastlane_version "1.39.0"

default_platform :ios


import_build_tools(
  url: 'git@github.com:mozilla/firefox-ios-build-tools.git',
  clone_folder: "../build-tools",
)

#move all the build tools to the right places
clone_folder = "../../build-tools"
sh("rsync -a #{clone_folder}/scripts ../")
sh("rsync -a #{clone_folder}/fastlane/Appfile Appfile")
sh("rsync -a #{clone_folder}/fastlane/Snapfile Snapfile")
sh("rsync -a #{clone_folder}/fastlane/SnapshotHelper.swift SnapshotHelper.swift")
sh("rsync -a #{clone_folder}/fastlane/scripts .")
sh("rsync -a #{clone_folder}/fastlane/frames .")
sh("rsync -a #{clone_folder}/fastlane/templates .")

#import the fastfile
import "#{clone_folder}/fastlane/BaseFastfile"

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-07-22**
</details></pre>
</details>

**Comment by johnwongapi** [comment]
import_build_tools is a custom action.

**Comment by joshdholtz** [comment]
@nmatsuo63 Were you able to solve this by looking into your custom action `import_build_tools` like @johnwongapi mentioned? This seems to be more a configuration/customization issue on your end than an issue within fastlane 🙃 Lemme know if you need any more help debugging anything.
