### ISSUE TITLE
Description related length issue

### ISSUE THREAD

**Issue by Mirant123** [fastlane/fastlane#12958]
![screen shot 2018-07-24 at 6 28 28 pm](https://user-images.githubusercontent.com/8058130/43139485-785c72ca-8f6f-11e8-9e3b-189cff9e762b.png)

**Comment by joshdholtz** [comment]
@Mirant123 Heyyy 👋 
1) Can you run this with `--verbose` on the end and paste the whole output here?
2) When was the last time the upload worked? 
3) Did you update anything (fastlane, xcode, etc) since the last time this worked?
