### ISSUE TITLE
Spaceship fails to throw an error when run with `bundle exec`

### ISSUE THREAD

**Issue by alexblack** [fastlane/fastlane#12951]
```
Alexs-MacBook-Air:is-spaceship alex$ bundle exec ruby test.rb
Couldn't verify that spaceship is up to date
Starting...
<Spaceship::Tunes::SandboxTester
	email="sandbox@test.com",
	first_name="Steve",
	last_name="Brule",
	country="US">
```

Here is the result I **expected**:

```
`create_sandbox_tester!': That email address is already associated with an existing Apple ID. (Spaceship::Tunes::Error)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.99.1/spaceship/lib/spaceship/tunes/sandbox_tester.rb:46:in `create!'
	from test.rb:7:in `<main>'

```

Here is `test.rb`

```
require 'spaceship'

puts 'Starting...'

Spaceship::Tunes.login('email@domain.com')

result = Spaceship::Tunes::SandboxTester.create!(
  email: 'sandbox@test.com', # required
  password: 'Passwordtest1', # required. Must contain >=8 characters, >=1 uppercase, >=1 lowercase, >=1 numeric.
  country: 'US', # optional, defaults to 'US'
  first_name: 'Steve', # optional, defaults to 'Test'
  last_name: 'Brule', # optional, defaults to 'Test'
)

puts result
```

and my `Gemfile`

```
source 'https://rubygems.org'

ruby '2.3.3'

gem 'spaceship'
```

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.5                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.5 (17F77)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-07-23**
</details>
</pre>
</details>

**Comment by joshdholtz** [comment]
@alexblack Heyyy 👋 First of all, thanks for providing a sample test script 🙌 

I ran the above and I'm pretty sure I got the result that you expected 🤔 
```sh
➜  test-ios git:(master) ✗ bundle exec ruby test.rb
Starting...
/Users/josh/Projects/fastlane/fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb:1288:in `create_sandbox_tester!': That email address is already associated with an existing Apple ID. (Spaceship::Tunes::Error)
        from /Users/josh/Projects/fastlane/fastlane/spaceship/lib/spaceship/tunes/sandbox_tester.rb:46:in `create!'
        from test.rb:7:in `<main>'
```

This is what you were expecting to see on your machine, right?

**Comment by alexblack** [comment]
Hey Josh, yes that is what I expected to see.  I repro'd this issue on both
my Mac laptops, and Heroku.

However, I've also seen it work as expected.  Simply running the script
with Ruby works for me, but running it with bundle exec repros the problem.

I did a lot of investigating, checking gem versions, trying bundle options,
reading about bundle exec .

No luck.

**Comment by alexblack** [comment]
hey @joshdholtz thx again for looking at this.  You can see the actual (unexpected) result above, here it is again:

```
Alexs-MacBook-Air:is-spaceship alex$ bundle exec ruby test.rb
Couldn't verify that spaceship is up to date
Starting...
<Spaceship::Tunes::SandboxTester
	email="sandbox@test.com",
	first_name="Steve",
	last_name="Brule",
	country="US">
```

Yes I tried using begin/rescue, it doesn't catch an error.    If login fails, then I get the expected result on the command line: an error occurs, and the operation fails.

**Comment by joshdholtz** [comment]
@alexblack I totally can't replicate what you are seeing on your end 😔 My call is always throwing an exception. I've tried:
- With `bundle exec` on version of Ruby installed via `ruby-install`/`chruby`
- Without `bundle exec` on version of Ruby installed via `ruby-install`/`chruby`
- With `bundle exec` on system version of Ruby
- Without `bundle exec` on system version of Ruby

Is there something outside of this script that could be causing this?

One thing I did notice that your environment does show `Bundler? | false`. If you are using `bundle exec` you should have a `Gemfile` with `gem "fastlane"` in it. I'm not sure if `Bundler? | false` is reporting wrong or if you don't have a have a `Gemfile` with `gem "fastlane"` in it but that is the only thing I can really think of that would be causing this weird behavior 🤔

**Comment by alexblack** [comment]
Thanks for your help here.  I ended up looking at the source and just
implementing it myself.
