### ISSUE TITLE
[snapshot] Add number of screenshots to snapshot report

### ISSUE THREAD

**Issue by BJap** [fastlane/fastlane#12950]
#### Motivation Behind Feature
At a quick glance, one can see how many screenshots there are to review for localization. This also enables accurate estimates for quotes when reviews are contracted out to third party companies.

#### Feature Description
This would involve counting the screenshots generated and putting a number next to each locale heading for the number of screenshots.

#### Alternatives or Workarounds
Leave the general report and dig into each folder to 'cmd+a' and see how many files are present.

**Comment by jspargo** [comment]
Hi @BJap - are you still interested in this feature? I might be able to get a PR up for this if you (or anyone else) would still like it. Are you thinking that the count would be per locale or a total per device? 

I'm thinking this would either be displayed in the fastlane output like:
**Per locale:**
![image](https://user-images.githubusercontent.com/6527450/46494870-dba4b480-c80b-11e8-8e8a-a57ce6234437.png)

or
**Per device only:**
![image](https://user-images.githubusercontent.com/6527450/46494769-95e7ec00-c80b-11e8-95c2-7857bb89e8e1.png)

**Comment by BJap** [comment]
@jspargo I am more inclined to think that verbosity is better here, especially for debugging and development. Of course that could also be a default with an ‘off’ switch.
