### ISSUE TITLE
commit_version_bump fails to commit test/framework bundle plists, also fails when running from subdirectory of git repo

### ISSUE THREAD

**Issue by MrAlek** [fastlane/fastlane#1295]
So, I got two problems with `commit_version_bump` running on Fastlane v1.57.0. Below is the troubled lane as defined in my fastfile. My setup consists of a shared workspace with a project for an iOS app containing the app target + unit tests, UI tests & separate framework for IBDesignables.

Also, the workspace together with fastfiles, etc is located in a subfolder within the git repository, akin to a "mono repo".

``` ruby
  desc "Submit a new preview build to Crashlytics"
  lane :preview do
    ensure_git_status_clean

    xcodeproj = './DooerApp/Dooer.xcodeproj'

    build_number = increment_build_number(
        xcodeproj: xcodeproj
    )

    sigh(app_identifier: "com.dooer.summify.preview", adhoc: true)
    gym(scheme: "Summify", configuration: "Preview")

    crashlytics(notifications: false)
    clean_build_artifacts

    commit_version_bump(
        message: "Bumped version",
        xcodeproj: xcodeproj,
        force: true,
    )
    push_to_git_remote

  end
```

I launch fastlane with `cd dooer && fastlane preview` from the root catalog of the code repository.

#### Issues

1. When running fastlane from within a subfolder in a git repository the command `git ls-files --other --exclude-standard` which is run from `commit_version_bump.rb` returns just about every file in the repository. This makes the commit command fail since it finds "unexpected changes" in all files.

2. If I set `force: true` on `commit_version_bump`, only the app target's info.plist seems to be found and the other plists that are changed by `agvtool` aren't committed.

Currently, I work around this by committing manually with  `git commit -am` but it would be very nice if I didn't have to.

Otherwise, Fastlane works great and has significantly simplified our CI-flow. Thanks a lot :)

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
