### ISSUE TITLE
release to all users for ios

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12968]
hi

how to implement "release to all users" button on itunes?

**Comment by joshdholtz** [comment]
@baturorkun Heyy 👋 Can you please add a more detail description for your question?

**Comment by baturorkun** [comment]
hi
i am talking about "auto_release_date". i can set a date on this field. but i want to press a button to autorelease. Normally there is the button on itunes. is it possible?

**Comment by joshdholtz** [comment]
@baturorkun Ah, so it sounds like you are talking about about when you set an app to "manual release" and then have to go in to App Store Connect dashboard to finally press that "Release" button, right? 

If so, are you asking "how to set an up for manual release?" or "when my app is approved, is there a way for me to manually release the app like the button in App Store Connect?" 😊

**Comment by baturorkun** [comment]
hi
yes. i am talking about Release to All Users" button after approved app by apple.
is there any function  to do it?
