### ISSUE TITLE
Could not upload binary to App Store Connect.

### ISSUE THREAD

**Issue by Mirant123** [fastlane/fastlane#12961]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[14:27:12]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[14:27:13]: Transporter transfer failed.
[14:27:13]: 
[14:27:13]: Could not start delivery: all transports failed diagnostics
[14:27:13]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine.access$1200(TransferEngine.java:149)

[14:27:13]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$8.run(TransferEngine.java:4060)

[14:27:13]: [iTMSTransporter] 

[14:27:13]: [iTMSTransporter] [2018-07-25 14:27:12 IST] <Transport Protocol> DEBUG: Received failed transfer notification; aborting

[14:27:13]: [iTMSTransporter] [2018-07-25 14:27:12 IST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED

[14:27:13]: [iTMSTransporter] [2018-07-25 14:27:12 IST] <main> ERROR: Could not start delivery: all transports failed diagnostics

[14:27:13]: [iTMSTransporter] 

[14:27:13]: [iTMSTransporter] 

[14:27:13]: [iTMSTransporter] 

[14:27:13]: [iTMSTransporter] Package Summary:

[14:27:13]: [iTMSTransporter]  

[14:27:13]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[14:27:13]: [iTMSTransporter] 	/tmp/1416459147.itmsp - Error Messages:

[14:27:13]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics

[14:27:13]: [iTMSTransporter] [2018-07-25 14:27:13 IST] <main> DBG-X: Returning 1

[14:27:13]: iTunes Transporter output above ^
[14:27:13]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| DEFAULT_PLATFORM | ios        |
| PLATFORM_NAME    | ios        |
| LANE_NAME        | ios upload |
+------------------+------------+
[14:27:13]: Could not upload binary to App Store Connect. Check out the error above

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | deliver          | 357         |
+------+------------------+-------------+

[14:27:13]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  "Could not find any available candidate builds on iTunes Connect to submit" when uploading and submitting a new binary
    https://github.com/fastlane/fastlane/issues/10411 [open] 22 💬
    a week ago

➡️  各位好，我在使用fastlane上传ipa包时出现了这个错误一直解决不了
    https://github.com/fastlane/fastlane/issues/12143 [closed] 6 💬
    3 weeks ago

➡️  Make upload_to_testflight FastlaneCore::Interface::FastlaneError messages useful
    https://github.com/fastlane/fastlane/issues/11902 [closed] 14 💬
    a week ago

and 60 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20upload%20binary%20to%20App%20Store%20Connect.%20Check%20out%20the%20error%20above&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Could not upload binary to App Store Connect. Check out the error above</pre>
</details>

### Environment

<details>
  <pre>[14:27:54]: fastlane detected a Gemfile in the current directory
[14:27:54]: however it seems like you don't use `bundle exec`
[14:27:54]: to launch fastlane faster, please use
[14:27:54]: 
[14:27:54]: $ bundle exec fastlane env
[14:27:54]: 
[14:27:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:27:56]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3                                             |
| Installation Source         | /usr/local/bin/Fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | 🚫 |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # 1
  desc "Creating a code signing certificate and provisioning profile"

  # 2
  lane :provision do
    # 3
    produce(
      app_name: 'FastlaneDemo',
      language: 'English',
      app_version: '1.0',
      sku: '1532414911'
    )
    # 4
     cert
    # 5
    sigh(force: false)
  end

  desc "Beta Deployment"
  lane :beta do
    gym(scheme: "FastlaneDemo")
  end



  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Create ipa"
  lane :build do
    1
    gym
  end

  desc "Upload to App Store and submit for review"
  lane :upload do
    deliver(
      submit_for_review: true
    )
  end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end
 
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.multidots.FastlaneDemoMirant543") # The bundle identifier of your app
apple_id("iphone@multidots.in") # Your Apple email address

itc_team_id("22535800") # App Store Connect Team ID
team_id("A73X7T2VMV") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.9        |
</details>

*generated on:* **2018-07-25**
</details>
[14:27:57]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[14:27:57]: 🙄  Wow, that's a lot of markdown text... should fastlane put it
into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[14:27:58]: Successfully copied markdown into your clipboard 🎨
[14:27:58]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅</pre>
</details>

**Comment by joshdholtz** [comment]
@Mirant123 Are you behind some sort of company firewall? It seems like this is a local configuration or network configuration that might be blocking iTunesTransporter from talking App Store Connect properly?

Have you tried this? https://docs.fastlane.tools/actions/deliver/#http-proxy
