### ISSUE TITLE
Couldn't find an existing certificate with cert, but certificate exists on local machine

### ISSUE THREAD

**Issue by ApoorvKhatreja** [fastlane/fastlane#12970]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

On trying to use local codesigning with `cert` and `sigh`, `cert` is unable to find the distribution certificate from the local keychain, and instead tries to generate a new certificate. I am using `cert` instead of `match` because I would not like to revoke my current certificate. I already tried with the default cert configuration, and also tried by manually specifying the path to the keychain in the `Fastfile`. Here's a screenshot of my Keychain Access that shows that the "login" keychain indeed has both developer and distribution certificates installed, and I also upload to TestFlight/App Store Connect regularly from this machine, so certificates are definitely in place.

I am also using `bundler`, not sure if that changes the behavior of `cert` in any way.

![screen_shot_2018-07-26_at_15_12_56](https://user-images.githubusercontent.com/143720/43283385-bb6798a6-90e6-11e8-921e-239ea76bf1db.png)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle exec fastlane beta
[✔] 🚀
[15:04:31]: ------------------------------
[15:04:31]: --- Step: default_platform ---
[15:04:31]: ------------------------------
[15:04:31]: Driving the lane 'ios beta' 🚀
[15:04:31]: ------------------------------
[15:04:31]: --- Step: get_certificates ---
[15:04:31]: ------------------------------

+---------------+------------------------------------+
|              Summary for cert 2.100.1              |
+---------------+------------------------------------+
| keychain_path | ~/Library/Keychains/login.keychain |
| development   | false                              |
| force         | false                              |
| username      | apoorv@myapp.com               |
| team_id       | REDACTED                         |
| platform      | ios                                |
+---------------+------------------------------------+

[15:04:31]: Starting login with user 'apoorv@myapp.com'
[15:04:32]: Successfully logged in
[15:04:33]: Couldn't find an existing certificate... creating a new one
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[15:04:34]: You do not have permission to create this certificate. Only Team Admins can create Distribution certificates
 🔍 See https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html for more information.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | get_certificates | 2           |
+------+------------------+-------------+

[15:04:34]: fastlane finished with errors

[!] You do not have permission to create this certificate. Only Team Admins can create Distribution certificates
 🔍 See https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html for more information.]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates(keychain_path: "~/Library/Keychains/login.keychain")
    get_provisioning_profile   # invokes sigh
    build_app(workspace: "MyApp.xcworkspace", 
    scheme: "MyApp",
    export_method: "app-store",
    export_options: {
          provisioningProfiles: { 
            "com.MyApp.MyAppName" => "Distribution"
          }
        }
      )
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.MyApp.MyAppName") # The bundle identifier of your app
apple_id("apoorv@myapp.com") # Your Apple email address

itc_team_id("MYAPPSTORETEAMID") # App Store Connect Team ID
team_id("MYTEAMID") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.100.1 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.1.0        |
| bundler                       | 1.16.3       |
| io-console                    | 0.4.6        |
| CFPropertyList                | 3.0.0        |
| concurrent-ruby               | 1.0.5        |
| i18n                          | 0.9.5        |
| minitest                      | 5.11.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.5        |
| activesupport                 | 4.2.10       |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.5.2        |
| atomos                        | 0.1.2        |
| babosa                        | 1.0.2        |
| claide                        | 1.0.2        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| cocoapods-core                | 1.3.1        |
| cocoapods-deintegrate         | 1.0.2        |
| cocoapods-downloader          | 1.2.1        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.0.0        |
| netrc                         | 0.11.0       |
| cocoapods-trunk               | 1.3.0        |
| cocoapods-try                 | 1.1.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.0.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.5.7        |
| ruby-macho                    | 1.2.0        |
| nanaimo                       | 0.2.6        |
| xcodeproj                     | 1.5.9        |
| cocoapods                     | 1.3.1        |
| cocoapods-prune-localizations | 0.3.1        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.10       |
| declarative-option            | 0.1.0        |
| unf_ext                       | 0.0.7.5      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20180417 |
| dotenv                        | 2.5.0        |
| emoji_regex                   | 0.1.1        |
| excon                         | 0.62.0       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.15.2       |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.12.2       |
| fastimage                     | 2.1.3        |
| jwt                           | 2.1.0        |
| little-plugger                | 1.1.4        |
| multi_json                    | 1.13.1       |
| logging                       | 2.2.2        |
| memoist                       | 0.16.0       |
| os                            | 0.9.6        |
| signet                        | 0.8.1        |
| googleauth                    | 0.6.2        |
| httpclient                    | 2.8.3        |
| mime-types-data               | 3.2016.0521  |
| mime-types                    | 3.1          |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.21.2       |
| json                          | 2.1.0        |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.4.0        |
| rubyzip                       | 1.2.1        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.5        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 1.8.0        |
| unicode-display_width         | 1.4.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.6.5        |
| tty-cursor                    | 0.6.0        |
| tty-spinner                   | 0.8.0        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.2.8        |
| xcpretty-travis-formatter     | 1.0.0        |
</details>

*generated on:* **2018-07-26**
</details></pre>
</details>

(I've redacted sensitive info about my app)

**Comment by ApoorvKhatreja** [comment]
@fastlane-bot It is a code-signing issue, and I have an update! `cert` apparently is unable to find a locally installed certificate if I'm not an admin on the Apple Developer portal. Once I changed my status to "Admin", cert was able to find my local certificate:

```
[16:50:49]: Starting login with user 'apoorv@myapp.com'
[16:50:50]: Successfully logged in
[16:50:51]: Found the certificate REDACTED (iOS Distribution) which is installed on the local machine. Using this one.
[16:50:51]: Verifying the certificate is properly installed locally...
[16:50:51]: Successfully installed certificate REDACTED
[16:50:51]: Use signing certificate 'REDACTED' from now on!
```

When I went back to the developer portal and demoted my role to "Member" from "Admin", I started getting the same error again:

```
[17:04:31]: Starting login with user 'apoorv@myapp.com'

[17:04:32]: Successfully logged in

[17:04:33]: Couldn't find an existing certificate... creating a new one

+------------------+----------+

|        Lane Context         |

+------------------+----------+

| DEFAULT_PLATFORM | ios      |

| PLATFORM_NAME    | ios      |

| LANE_NAME        | ios beta |

+------------------+----------+

[17:04:34]: You do not have permission to create this certificate. Only Team Admins can create Distribution certificates

🔍 See https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html for more information.


+------+------------------+-------------+

|           fastlane summary            |

+------+------------------+-------------+

| Step | Action           | Time (in s) |

+------+------------------+-------------+

| 1    | default_platform | 0           |

| 💥   | get_certificates | 2           |

+------+------------------+-------------+


[17:04:34]: fastlane finished with errors


[!] You do not have permission to create this certificate. Only Team Admins can create Distribution certificates

🔍 See https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html for more information.]
```

**Comment by joshdholtz** [comment]
@ApoorvKhatreja `cert` has to go query all distribution certificates and download the public key from the dev portal to determine if it is already installed. In order to download the public key from the dev portal, a user must be as admin as members are not allowed to download distribution certs (see my image below which is taken from an account of mine that is a member). There is no way to `cert` to know if its already installed without fully being an admin.

![screen shot 2018-07-31 at 7 01 24 am](https://user-images.githubusercontent.com/401294/43458607-6bdf17ca-9490-11e8-96e8-f12f4cf44f2c.png)

### Possible solutions
1) Give your _fastlane_ setup an admin user to use to do these operations
2) Revoke your cert and let _match_ create a new cert
3) Manually add your cert into your _match_ repo - https://docs.fastlane.tools/advanced/#manually-manage-the-fastlane-match-repo

Hope this helps 😊
