### ISSUE TITLE
Support virtual target lanes (cruising over to a different lane should affect which lane to read from Scanfile)

### ISSUE THREAD

**Issue by willemfrishert** [fastlane/fastlane#12978]
#### Motivation Behind Feature
I am working on a consolidated fastlane file which contains different lanes. The fastlane files importing this fastlane file will need to create the matching Scanfile with identical lane names to ensure the right scheme within the xcworkspace is tested. 

What I would like is to be able to provide my fellow developers with a virtual target lane to invoke all other lanes which would invoke `scan` individually. Once `scan` is invoked, the last lane of invocation should determine which lane to read from Scanfile.

#### Feature Description
- When cruising over to another lane, the `FASTLANE_LANE_NAME` variable does not reflect the lane update.
- What I would like to suggest to have an additional option to specify the current lane when invoking `scan`. It would also allow the code that creates the `ConfigurationFile` object to do injection and avoid `ConfigurationFile` from knowing about global environment variables.
Note: the current `ConfigurationFile` class (see `fastlane/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb`) is using the `FASTLANE_LANE_NAME` directly which is the environment variable set on the first invocation of the fastlane file.

**Example code**
An example of my Scanfile and Fastfile

*fastlane/Scanfile*
```
for_platform :ios do
  workspace 'HelloWorld.xcworkspace'

  for_lane :test_framework do
    scheme 'Framework'
    output_directory './output_framework'
  end

  for_lane :test_app do
    scheme 'App'
    output_directory './output_app'
  end

  devices ['iPhone X']
end
```

*fastlane/Fastfile*
```
min_fastlane_version('2.100.1')

default_platform(:ios)

platform :ios do
  before_all do
    # ...
  end

  desc 'Runs all the framework tests'
  lane :test_framework do |options|
    scan(scheme: options[:scheme])
  end

  desc 'Runs all the example app tests'
  lane :test_app do |options|
    scan(scheme: options[:scheme])
  end

  desc 'Runs all the tests'
  lane :test do
    test_framework
    test_app
  end

  after_all do
    rocket
  end
end
```

**Invocation**
- `fastlane test`

**What happens?**
1. `ENV["FASTLANE_LANE_NAME"]` is set to `test` after invocation;
2. The `test`-lane immediate cruises over to `test_framework`;
3. The `test_framework` invokes scan with potential options;
4. When the Scanfile is checking `per_lane`, the lane `test` is looked for instead of `test_framework and fastlane will fail not being able to find the correct parameters to invoke `xcodebuild`.

Note: Step 2 to 4 also applies to `test_app`

**Would it affect others?**
- No, if the option to specify the current invocation lane is not set, the ConfigurationFile class should fall back to `ENV["FASTLANE_LANE_NAME"]` variable.

#### Alternatives or Workarounds

Currently as a workaround, I end up temporarily updating the `FASTLANE_LANE_NAME` to ensure the ConfigurationFile picks up the lane change. I use the code that is used to test fastlane.
```
  desc 'Runs all the tests'
  lane :test do
    # include all test lanes
    test_lanes = %w[test_app test_framework]

    # for each test lane,
    # change the lane environment and
    # invoke that specific lane
    test_lanes.each do |test_lane|
      with_env_values('FASTLANE_LANE_NAME' => test_lane) do
        send(test_lane, {})
      end
    end
  end
```

**Comment by willemfrishert** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.13.6                                              |
| Ruby                        | 2.5.1                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.14.2                                   |
| Installation Source         | ~/Code/Example/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.13.6 (17G65)                             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 9.2                                                  |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
min_fastlane_version('2.100.1')

default_platform(:ios)

platform :ios do
  before_all do
    # ...
  end

  desc 'Runs all the framework tests'
  lane :test_framework do |options|
    scan(scheme: options[:scheme])
  end

  desc 'Runs all the example app tests'
  lane :test_app do |options|
    scan(scheme: options[:scheme])
  end

  desc 'Runs all the tests'
  lane :test do
    # include all test lanes
    test_lanes = %w[test_app test_framework]

    # for each test lane,
    # change the lane environment and
    # invoke that specific lane
    test_lanes.each do |test_lane|
      with_env_values('FASTLANE_LANE_NAME' => test_lane) do
        send(test_lane, {})
      end
    end
  end

  after_all do
    rocket
  end
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.3       |
| rake                      | 12.3.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| ffi                       | 1.9.23       |
| mustache                  | 0.99.8       |
| open4                     | 1.3.4        |
| redcarpet                 | 3.4.0        |
| rb-fsevent                | 0.10.3       |
| rb-inotify                | 0.9.10       |
| sass-listen               | 4.0.0        |
| sass                      | 3.5.6        |
| sqlite3                   | 1.3.13       |
| liferaft                  | 0.0.6        |
| xcinvoke                  | 0.3.0        |
| jazzy                     | 0.9.2        |
| parallel                  | 1.12.1       |
| parser                    | 2.5.1.0      |
| powerpack                 | 0.1.1        |
| rainbow                   | 3.0.0        |
| ruby-progressbar          | 1.9.0        |
| rubocop                   | 0.55.0       |
| xcode-install             | 2.3.1        |
</details>


*generated on:* **2018-07-29**
</details>

**Comment by willemfrishert** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.13.6                                              |
| Ruby                        | 2.5.1                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.14.2                                   |
| Installation Source         | ~/Code/Example/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.13.6 (17G65)                             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 9.2                                                  |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
fastlane_require 'dotenv'

# Easily opt-out of metrics collection by adding opt_out_usage at the top of
# your Fastfile or by setting the environment variable FASTLANE_OPT_OUT_USAGE
# opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

min_fastlane_version('2.100.1')

default_platform(:ios)

# Use .env.buildconfig to store build configuration settings
# credentials should be stored in .env, .env.default or .env.secret
build_configuration_file = '.env.buildconfig'

platform :ios do # rubocop:disable Metrics/BlockLength
  before_all do
    # ...
  end

  desc 'Set or update environment variables temporarily using a block notation'
  def with_env_values(hash, &block)
    with_global_key_values(ENV, hash, &block)
  end

  def with_global_key_values(global_store, hash)
    old_vals = global_store.select { |key, _value| hash.include?(key) }
    hash.each do |key, _value|
      global_store[key] = hash[key]
    end
    yield
  ensure
    hash.each do |key, _value|
      global_store.delete(key) unless old_vals.include?(key)
      global_store[key] = old_vals[key]
    end
  end

  desc 'Runs all the framework tests'
  lane :test_framework do |options|
    scan(scheme: options[:scheme])
  end

  desc 'Runs all the example app tests'
  lane :test_app do |options|
    scan(scheme: options[:scheme])
  end

  desc 'Runs all the tests'
  lane :test do
    # include all test lanes
    test_lanes = %w[test_app test_framework]

    # for each test lane,
    # change the lane environment and
    # invoke that specific lane
    test_lanes.each do |test_lane|
      with_env_values('FASTLANE_LANE_NAME' => test_lane) do
        send(test_lane, {})
      end
    end
  end

  after_all do
    rocket
  end
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.3       |
| rake                      | 12.3.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| ffi                       | 1.9.23       |
| mustache                  | 0.99.8       |
| open4                     | 1.3.4        |
| redcarpet                 | 3.4.0        |
| rb-fsevent                | 0.10.3       |
| rb-inotify                | 0.9.10       |
| sass-listen               | 4.0.0        |
| sass                      | 3.5.6        |
| sqlite3                   | 1.3.13       |
| liferaft                  | 0.0.6        |
| xcinvoke                  | 0.3.0        |
| jazzy                     | 0.9.2        |
| parallel                  | 1.12.1       |
| parser                    | 2.5.1.0      |
| powerpack                 | 0.1.1        |
| rainbow                   | 3.0.0        |
| ruby-progressbar          | 1.9.0        |
| rubocop                   | 0.55.0       |
| xcode-install             | 2.3.1        |
</details>


*generated on:* **2018-07-29**
</details>

**Comment by willemfrishert** [comment]
@joshdholtz, I noticed you labelled this as a feature request as part of a triage. I was hoping this labelling would be a hint to the fastlane-bot that the issue is valid and would be ignored for automatic cleanup.

Is there a place (backlog?) where these feature requests are kept as to avoid them from being closed automatically by the fastlane-bot?

**Comment by willemfrishert** [comment]
No worries @fastlane-bot. This feature request is still alive 👍

**Comment by KrauseFx** [comment]
Hey @willemfrishert, this does sound like a pretty specific, advanced use-case, we most likely won't have the time to actually build it. I see you found a workaround, is that one working well enough for you?
