### ISSUE TITLE
Update pem to download APNS p8 files

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#12971]
### Feature Request

I would like to be able to generate and download the APNS p8 files (and the Key ID)

#### Motivation Behind Feature

 I am automating the generation of certs, bundle ids, profiles, and push notifications for one of the teams in my company. I want to make it easy for this team who finds the process of creating these files confusing and onerous. I have almost everything done by using `fastlane` commands, except for the generation of the p8 file and the Key ID (for an idea of what I am talking about: https://stackoverflow.com/a/44733012/71877).

#### Feature Description

I would like options added to `pem` that would download the file, probably named `AuthKey_KEYID.p8` to a destination of my choice.

#### Alternatives or Workarounds

I am not sure what I can do yet. Maybe there is some other way that I am not aware of.

**Comment by lyndsey-ferguson** [comment]
@joshdholtz here is the issue. It would be amazing if you could do something for this. 🎉

**Comment by johnwongapi** [comment]
Hi @lyndsey-ferguson, you can create an APNS p8 file with spaceship. see #9256

**Comment by lyndsey-ferguson** [comment]
[Sweet](
https://github.com/fastlane/fastlane/issues/9256#issuecomment-318471833)

**Comment by joshdholtz** [comment]
@johnwongapi Woah! Thanks for linking that 😱 I didn't even know. I think I would still like to add this to `pem` to move it to its own action but that is pretty cool 🙃

**Comment by lyndsey-ferguson** [comment]
I would expect that if the feature is added to `pem`, this Issue would be closed. Using `spaceship` does allow us to get the `p8` file.
