### ISSUE TITLE
Passing through fastlane command line options to actions

### ISSUE THREAD

**Issue by chris-fuller** [fastlane/fastlane#1297]
How do you pass through `fastlane` command line options to actions?

For example, how would you specify the `device` on the command line for `scan`?

These do not work:

`$ fastlane test device:"iPhone 6s"`
`$ fastlane test "device:iPhone 6s"`
`$ fastlane test device="iPhone 6s"`
`$ fastlane test --device "iPhone 6s"`

Thanks in advance.

**Comment by KrauseFx** [comment]
Can you share your test lane? You'll need to pass parameters like this: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#passing-parameters and then pass the device to the `scan` action

**Comment by chris-fuller** [comment]
Hi - Thanks Felix! Yes, sure, it's just the basics right now:

```
desc "Runs all the tests"
lane :test do
  scan(scheme: "Scheme")
end
```

Based on your comment, I changed to this (and it works):

```
desc "Runs all the tests"
lane :test do |options|
  scan(scheme: "Scheme", device: options[:device])
end
```

So that's awesome!

But what about a general way to do this for all options? Meaning without having to pass them through this way in code. It would be nice to be able to pass action specific options when running fastlane, no? Am I missing something?

Thanks

**Comment by KrauseFx** [comment]
@chris-fuller that's the way to do it, looks good! :+1:

**Comment by KrauseFx** [comment]
Interesting, so `fastlane` should try to automatically apply the given parameters to the actions if the name matches? I wonder if that causes troubles if there are actions with the same parameter name, but different meaning..

**Comment by chris-fuller** [comment]
Thanks @KrauseFx! Appreciate it.

Yes, I suppose that was my thinking. I do not know enough about Fastlane to know if this is possible or problematic. It just seemed like being able to passthrough options from the command line was useful to me. I will accept the fact that this is by design, if that's the case.

Thanks again.

**Comment by chris-fuller** [comment]
_revising issue title to be more apropos for this conversation_

**Comment by KrauseFx** [comment]
I'll mark this issue as a feature for now, it's a good idea, however it might result in a some side effects.

**Comment by chris-fuller** [comment]
Agreed. What about an advanced CLI that accepts 'namespaced' params? Something like:

`$ fastlane test scan:key:value`

Just a thought. No idea if this makes sense or not.

**Comment by KrauseFx** [comment]
I'll close this issue for now, as we're not actively working on it :+1:

**Comment by Bogidon** [comment]
@KrauseFx this link is broken: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#passing-parameters

What's the proper syntax for passing through a parameter?

**Comment by Bogidon** [comment]
Ah never mind, I got it:
`fastlane test device:"iPhone 6s"`

**Comment by KrauseFx** [comment]
👍

**Comment by cepages** [comment]
Fixed link: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#passing-parameters

**Comment by tsheaff** [comment]
I like @chris-fuller 's proposal of namespaced options without having to add the manual `options` passing in code.  For example `fastlane mylane deliver:skip_screenshots:true` or more generally `fastlane <lane> <action>:<options>:<value>`

I could be wrong, but it seems like this avoids any ambiguity in terms of passing the right options/value pairs to the right actions. For example if there's not `deliver` action in the lane `mylane` it does nothing, and likewise if there is no `skip_screenshots` options in the deliver action, it also does nothing.
