### ISSUE TITLE
Include % of iOS phased rollout in the Spaceship's app status response

### ISSUE THREAD

**Issue by rockmobile** [fastlane/fastlane#12973]
### Feature Request
Include % of iOS phased rollout in the Spaceship's app status response

#### Motivation Behind Feature
We would like to notify the teams on the status of our phased rollout as that is critical to asses the adoption perentage. We were able to get the app status but not the rollout %. It would be fantastic to have that included.

#### Feature Description
Today get app status via Spaceship only provides if the app status like ready for sale, wait for review etc but it would be nice to know the % of phased of phased release when the app is already in 'ready for sale' status.

#### Alternatives or Workarounds
Alternate work around is to run a cron job to update the status every 24 hours after the initial phased release was done for next 7 days but again its not ideal as someone needs to kill the cron process if we halt the rollout.

**Comment by joshdholtz** [comment]
@rockmobile Thanks for the feature request! Is this `% of iOS phased rollout` currently available on the App Store Connect dashboard somewhere? If it is we can probably get it. It not then I'm not sure where we could be able to get that from 😬

**Comment by rockmobile** [comment]
Unfortunately, AppStore Connect dashboard doesn't show the % of phased rollout either. I have created a feature request to Apple as well.

**Comment by joshdholtz** [comment]
@rockmobile I don't think we are able to show this then since that information isn't available to us 😔 Let me know if/when that information is available on the App Store Connect dashboard and we will work on getting that connect up to _fastlane_ for you 💪
