### ISSUE TITLE
Get app status from Google PlayStore

### ISSUE THREAD

**Issue by rockmobile** [fastlane/fastlane#12974]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Get app status from Google PlayStore (similar to Spaceship)

#### Question Description
Is there something similar to "Spaceship" for Google PlayStore to get app status and rollout percentage?

**Comment by joshdholtz** [comment]
@rockmobile `supply` (the tool the communicates with Google PlayStore) uses methods from https://github.com/google/google-api-ruby-client/blob/ef45bf244353e338897ebb01e797b6573b332ed1/generated/google/apis/androidpublisher_v2/service.rb. I have no idea of this rollout percentage is something that given to us in any of the requests that the `google-api-ruby-client` provides us. Is this information readily available on the Google PlayStore dashboard?

We currently do not make this `Supply::Client` available as an API for use like _spaceship_. I'm not opposed to it but it would take some re-architecting 🤔

**Comment by rockmobile** [comment]
Hi @joshdholtz Thanks for looking at my ticket. Publisher APIs just let's us publish the app, content etc to PlayStore and we can build our app notifications logic around it. We are manually doing the releases today due to the complex release process. I was just hoping to fetch the current status from Playstore and notify the teams.

Yes, the release version, rollout status is available in the PlayStore dashboard:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/41701421/43477007-ed8c09a4-94ae-11e8-9bd7-4ed5296e7687.png">

**Comment by joshdholtz** [comment]
@rockmobile Ah thanks for showing this! I actually don't use the rollout feature myself so I wasn't sure what all information get's shown 😊 I took a quick look again through the link I posted above to the client that we use to communicate with Google play and I'm not 100% certain there is an API call that will get us this information.

I can add this to my list of things to look up to but its pretty large right now and other things usually jump up in priority 🙃 If you would like to take a stab and seeing if that information is possible for us to get that would be 💯 👌

**Comment by rockmobile** [comment]
Sounds good. Thanks @joshdholtz I will spend some time this week to see if I can get this from Google Play.
