### ISSUE TITLE
fastlane match <anything> failing authentication with Apple Developer

### ISSUE THREAD

**Issue by whatch** [fastlane/fastlane#12972]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane match ...` failing authentication with Apple developer portal

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bill@wkhatch-mbp ~/Code/stratosphere/phonegapApp/Atmosphere/platforms/ios $ bundle exec fastlane match development `--capture_output`
bash: --capture_output: command not found
[✔] 🚀 
[16:58:06]: Successfully loaded '/Users/bill/Code/stratosphere/phonegapApp/Atmosphere/platforms/ios/fastlane/Matchfile' 📄

+-----------------------+------------------------------------------------------------------------+
|                          Detected Values from './fastlane/Matchfile'                           |
+-----------------------+------------------------------------------------------------------------+
| git_url               | https://iosdev-atmosphereiot@github.com/atmosphereiot/fastlane-ios.git |
| type                  | development                                                            |
| app_identifier        | com.atmosphere.atmosphereiot                                           |
| username              | ios-dev@atmosphereiot.com                                              |
| shallow_clone         | true                                                                   |
| force_for_new_devices | true                                                                   |
+-----------------------+------------------------------------------------------------------------+

+-----------------------+------------------------------------------------------------------------+
|                                   Summary for match 2.100.1                                    |
+-----------------------+------------------------------------------------------------------------+
| type                  | development                                                            |
| git_url               | https://iosdev-atmosphereiot@github.com/somecompany/fastlane-ios.git |
| git_branch            | master                                                                 |
| app_identifier        | ["com.atmosphere.atmosphereiot"]                                       |
| username              | ios-dev@atmosphereiot.com                                              |
| keychain_name         | login.keychain                                                         |
| readonly              | false                                                                  |
| team_id               | redacted                                                             |
| verbose               | false                                                                  |
| force                 | false                                                                  |
| skip_confirmation     | false                                                                  |
| shallow_clone         | true                                                                   |
| clone_branch_directly | false                                                                  |
| force_for_new_devices | true                                                                   |
| skip_docs             | false                                                                  |
| platform              | ios                                                                    |
+-----------------------+------------------------------------------------------------------------+

[16:58:06]: Cloning remote git repo...
[16:58:06]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:58:07]: 🔓  Successfully decrypted certificates repo
[16:58:07]: Verifying that the certificate and profile are still valid on the Dev Portal...
The login credentials for 'ios-dev@atmosphereiot.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
[16:58:07]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[16:58:07]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[16:58:07]: to just install the certificates and profiles without accessing the Dev Portal.
[16:58:07]: To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
        Invalid username and password combination. Used 'ios-dev@atmosphereiot.com' as the username.</pre>
</details>

I've set FASTLANE_PASSWORD env variable, and MATCH_PASSWORD (which you should absolutely indicate needs to be the same as your apple dev login password, somewhere) and confirmed access to the developer portal by manually logging in, using the same username and password combination. I've found a few other closed issues that are identical to this one, so, I'm thinking the problem still exists, although none of them provided a solution.

**Comment by whatch** [comment]
I excluded the specific output per the docs, as it's already included when you include the --capture_output flag

**Comment by joshdholtz** [comment]
@whatch Heyyyy 👋 

>I've set FASTLANE_PASSWORD env variable, and MATCH_PASSWORD (which you should absolutely indicate needs to be the same as your apple dev login password, somewhere)

`MATCH_PASSWORD` actually does _not_ need to be the same as your Apple dev login password. The `MATCH_PASSWORD` is only used to 256 AES encrypt and decrypt the contents of your _match_ repository. The `MATCH_PASSWORD` is never used to login into any Apple service's as that is what `FASTLANE_PASSWORD` is used or.

>fastlane match <anything> failing authentication with Apple Developer
 
^ This sounds like an issue with either using wrong Apple email and password combination or trying to access the wrong development team. I just tested out my _match_ setup and its working and authing the Apple services so this sounds like it is most likely a configuration issue 😊

**Comment by whatch** [comment]
@joshdholtz thanks for the reply.

I confused the two passwords, MATCH_ and FASTLANE_ It does appear that the MATCH password is also used to authenticate against github, using https://<matchuser>@github... format for the repo address. I'd like to use the git/ssh protocol, but baby steps into getting this working in circleci. And then FASTLANE_PASSWORD is what I'm successfully using for apple dev. It seems as though it used a previous version of that password that was in my keychain, and doing some additional digging, I found more info about managing credentials with fastlane that clarified a lot of things. I'm now able to provision certs using match, and onto finishing the circleci integration. Thanks again!
