### ISSUE TITLE
don't update README.md

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#1298]
Whenever i run `sudo gem update fastlane` it updates our repo `readme.md` to the default one. Would it be possible to skip overriding readme if that's already exists ?

**Comment by i2amsam** [comment]
@romk1n Hmm, that sounds odd.  Could you put the output of `sudo gem update fastlane --verbose`
?  I'm not sure why that would change a readme.md.  Where is the readme which is being modified?

**Comment by KrauseFx** [comment]
This doesn't happen when updating, but when you run fastlane. You can add the [skip_docs](https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#skip_docs) action to your `Fastfile` to stop this :+1:

**Comment by romk1n** [comment]
thanks you @KrauseFx !

**Comment by cepages** [comment]
This is the right link to [skip_docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#skip_docs) :)

**Comment by mfurtak** [comment]
Thanks @cepages - I've updated Felix's link to match yours, since it changed during the monorepo migration :+1:
