### ISSUE TITLE
access keychain problem

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12992]
When i login to ssh  from remote machine, archive does not run. 

** ARCHIVE FAILED **

The following build commands failed:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/batur/Library/Developer/Xcode/DerivedData/TEST.me-fdcjhspnujwocydxoemczolxjqry/Build/Intermediates.noindex/ArchiveIntermediates/TEST.me/IntermediateBuildFilesPath/TEST.me.build/Release-iphoneos/TEST.me.build/Script-5D56CD1B1CB17387F4D2AFCF.sh
(1 failure)
[13:33:45]: Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.100.1                 |
| sdk         | iPhoneOS11.4.sdk        |
+-------------+-------------------------+

[13:33:45]: ▸ total size is 3486413  speedup is 1.00
[13:33:45]: ▸ Code Signing /Users/batur/Library/Developer/Xcode/DerivedData/TEST.me-fdcjhspnujwocydxoemczolxjqry/Build/Intermediates.noindex/ArchiveIntermediates/TEST.me/InstallationBuildProductsLocation/Applications//TEST.app/Frameworks/AFNetworking.framework with Identity iPhone Developer: Batur Orkun (3CRRLC7B32)
[13:33:45]: ▸ /usr/bin/codesign --force --sign 87BB867A4CA34351A50D64EFD1E66DAA467C11D3 --keychain=/Users/batur/Library/Keychains/login.keychain --preserve-metadata=identifier,entitlements '/Users/batur/Library/Developer/Xcode/DerivedData/TEST.me-fdcjhspnujwocydxoemczolxjqry/Build/Intermediates.noindex/ArchiveIntermediates/TEST.me/InstallationBuildProductsLocation/Applications//TEST.app/Frameworks/AFNetworking.framework'
[13:33:45]: ▸ /Users/batur/Library/Developer/Xcode/DerivedData/TEST.me-fdcjhspnujwocydxoemczolxjqry/Build/Intermediates.noindex/ArchiveIntermediates/TEST.me/InstallationBuildProductsLocation/Applications//TEST.app/Frameworks/AFNetworking.framework: errSecInternalComponent
[13:33:45]: ▸ Command /bin/sh failed with exit code 1

```

    unlock_keychain(
         path: "/Users/batur/Library/Keychains/login.keychain",
         password: "*******",
         #set_default: true
    )
    sh "security unlock-keychain -p ******* /Users/batur/Library/Keychains/login.keychain"

    build_ios_app(
          workspace: "ios/me.xcworkspace",
          scheme: "me",
          configuration: "Release",
          xcargs: "OTHER_CODE_SIGN_FLAGS=--keychain=\"/Users/batur/Library/Keychains/login.keychain\""
     )
```

**Comment by JAManfredi** [comment]
are you running this on jenkins? 

I ran into the same issue, I was using setup_jenkins, but apparently its not unlocking the keychain... I added :     
```
unlock_keychain(
      path: "login.keychain",
      password: ENV['LOGIN_KEYCHAIN_PASSWORD']
    )
```

and now it works.... talk about frustrating...

**Comment by baturorkun** [comment]
hi JAManfredi 
i am not using jenkins. i wrote my CI by using just fastlane.
if i run my bash script in terminal, everything works fine. but if i run it in cronjob or remote shell, i have an error about ARCHIVING. i thought it was a restriction on keychain and certificates. so i tried cert and sigh but could not solve this problem. At last, i decided to use AppleScript. i open a new terminal and run it on this terminal.

```
#!/usr/bin/env bash

osascript -e 'tell app "Terminal"
do script "/Users/batur/run.sh ios deploy"
end tell'
```

**Comment by joshdholtz** [comment]
@baturorkun You may want to look at this stackoverflow issue. This is less of a _fastlane_ issue but more of a security issue with keychain, mac, and ssh - https://apple.stackexchange.com/a/250572

Your keychain isn't automatically unlocked when using an ssh session so there is some configuring you would need to do if you do want to get this to work properly.

It looks like you figured out a solution but I still wanted to drop this information in here 😊 Going to close this since you found a workaround and since I posted another solution.

Happy fastlaning! 🚀

**Comment by Boojs** [comment]
> are you running this on jenkins?
> 
> I ran into the same issue, I was using setup_jenkins (which worked), but apparently its not unlocking the keychain now?? ... I added :
> 
> ```
> unlock_keychain(
>       path: "login.keychain",
>       password: ENV['LOGIN_KEYCHAIN_PASSWORD']
>     )
> ```
> and now it works.... talk about frustrating...

Wow wow wow..... very frustrating, spent days on this and a quick change. I originally told it the passowrd, and its supposed to default to the login keychain. But in my instance the keychain needed to be called `login.keychain-db`
