### ISSUE TITLE
Apple forcing two factor authentication

### ISSUE THREAD

**Issue by awgeorge** [fastlane/fastlane#12996]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Just a note to say that as of today, it would appear apple is forcing 2 factor authentication, so these details we become more prevalent: https://github.com/fastlane/fastlane/tree/master/spaceship#app-store-connect-api

<img width="782" alt="screen shot 2018-07-31 at 18 45 31" src="https://user-images.githubusercontent.com/1777444/43477653-ad3de15c-94f3-11e8-9325-02f1ec6948b8.png">

[Two-factor authentication](https://support.apple.com/en-us/HT204915)
[Using app-specific passwords](https://support.apple.com/en-us/HT204397)

**Comment by yakimant** [comment]
@awgeorge, I created a new dev account with the dev program recently.
I used a phone to overcome this requirement and logged out afterwards.

Now it's basically 2step with SMS, although still called 2factor in AppleID setting.
And it's not possible to switch it off anymore.
