### ISSUE TITLE
google_play_track_version_codes broken in 2.101.0

### ISSUE THREAD

**Issue by jcharr1** [fastlane/fastlane#13013]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [2.101.0]
- Last working version: [2.100.1]

### Regression Description

google_play_track_version_codes now fails with "Could not find option 'timeout' in the list of available options: package_name, track, key, issuer, json_key, json_key_data, root_url." Works fine in 2.100.1.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane beta --capture_output                   
[✔] 🚀 
[08:24:21]: fastlane detected a Gemfile in the current directory
[08:24:21]: however it seems like you don't use `bundle exec`
[08:24:21]: to launch fastlane faster, please use
[08:24:21]: 
[08:24:21]: $ bundle exec fastlane beta --capture_output
[08:24:21]: 
[08:24:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-08-01 08:24:21.29]: Checking if there are any plugins that should be loaded...
INFO [2018-08-01 08:24:21.67]: -----------------------------
INFO [2018-08-01 08:24:21.67]: --- Step: import_from_git ---
INFO [2018-08-01 08:24:21.67]: -----------------------------
INFO [2018-08-01 08:24:21.67]: Cloning remote git repo...
INFO [2018-08-01 08:24:21.67]: $ GIT_TERMINAL_PROMPT=0 git clone [REDACTED] '/var/folders/dk/z57xpvj52nx4wdtb5zzw_q7c0000gr/T/fl_clone20180801-5689-16xnv3c/[REDACTED]' --depth 1 -n 
INFO [2018-08-01 08:24:21.69]: ▸ Cloning into '/var/folders/dk/z57xpvj52nx4wdtb5zzw_q7c0000gr/T/fl_clone20180801-5689-16xnv3c/[REDACTED]...
INFO [2018-08-01 08:24:23.64]: $ cd '/var/folders/dk/z57xpvj52nx4wdtb5zzw_q7c0000gr/T/fl_clone20180801-5689-16xnv3c/[REDACTED]' && git checkout HEAD 'fastlane/Fastfile-android'
INFO [2018-08-01 08:24:23.66]: $ cd '/var/folders/dk/z57xpvj52nx4wdtb5zzw_q7c0000gr/T/fl_clone20180801-5689-16xnv3c/[REDACTED]' && git checkout HEAD 'fastlane/actions'
INFO [2018-08-01 08:24:23.68]: ▸ error: pathspec 'fastlane/actions' did not match any file(s) known to git.
INFO [2018-08-01 08:24:23.68]: ------------------------------
INFO [2018-08-01 08:24:23.68]: --- Step: default_platform ---
INFO [2018-08-01 08:24:23.68]: ------------------------------
INFO [2018-08-01 08:24:23.69]: Driving the lane 'android beta' 🚀
INFO [2018-08-01 08:24:23.69]: ----------------------
INFO [2018-08-01 08:24:23.69]: --- Step: hostname ---
INFO [2018-08-01 08:24:23.69]: ----------------------
INFO [2018-08-01 08:24:23.69]: $ hostname
INFO [2018-08-01 08:24:23.70]: ▸ [REDACTED]
INFO [2018-08-01 08:24:23.70]: -------------------
INFO [2018-08-01 08:24:23.70]: --- Step: slack ---
INFO [2018-08-01 08:24:23.70]: -------------------
INFO [2018-08-01 08:24:24.11]: Successfully sent Slack notification
INFO [2018-08-01 08:24:24.11]: ---------------------------------------------
INFO [2018-08-01 08:24:24.11]: --- Step: google_play_track_version_codes ---
INFO [2018-08-01 08:24:24.11]: ---------------------------------------------
DEBUG [2018-08-01 08:24:24.60]: Fetching a new access token from Google...
INFO [2018-08-01 08:24:24.90]: -------------------
INFO [2018-08-01 08:24:24.90]: --- Step: slack ---
INFO [2018-08-01 08:24:24.90]: -------------------
INFO [2018-08-01 08:24:25.36]: Successfully sent Slack notification
WARN [2018-08-01 08:24:25.36]: Lane Context:
INFO [2018-08-01 08:24:25.36]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android beta"}
ERROR [2018-08-01 08:24:25.36]: Could not find option 'timeout' in the list of available options: package_name, track, key, issuer, json_key, json_key_data, root_url
INFO [2018-08-01 08:24:25.37]: Successfully generated documentation at path '[REDACTED]/fastlane/README.md'
ERROR [2018-08-01 08:24:25.38]: fastlane finished with errors
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14 (18A347e)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# set the correct slack url and then let the shared Fastfile do the rest
ENV["SLACK_URL"] = [REDACTED]
import_from_git(url: [REDACTED],
               path: 'fastlane/Fastfile-android')


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name "[REDACTED]"

json_key_file "./fastlane/fastlane-supply-authenticator.json"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| bundler                   | 1.16.3       |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.8.1        |
| os                        | 0.9.6        |
| memoist                   | 0.16.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| googleauth                | 0.6.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.4       |
| openssl                   | 2.1.1        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.4        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-08-01**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@jcharr1 Looking into! 👀

**Comment by jcharr1** [comment]
And here's the relevant chunk of my imported Fastfile

```ruby
internal_version_codes = google_play_track_version_codes(track: "internal")
production_version_codes = google_play_track_version_codes(track: "production")
google_play_version_code = -1
if internal_version_codes.length < 1 || internal_version_codes[0] < production_version_codes[0]
	google_play_version_code = production_version_codes[0]
else
	google_play_version_code = internal_version_codes[0]	
end
```

**Comment by joshdholtz** [comment]
@jcharr1 I was just about to release `2.101.1` for another supply fix but I cancelled it to get this out with that version as well 😊
