### ISSUE TITLE
fastlane hanges after logging in 

### ISSUE THREAD

**Issue by jwilson85** [fastlane/fastlane#13016]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

running fastlane match enterprise --verbose 
hangs 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>+-------------------+---------------------------------------------------+
|                       Summary for cert 2.101.1                        |
+-------------------+---------------------------------------------------+
| development       | false                                             |
| force             | true                                              |
| username          | mobile@activewebsite.com                          |
| keychain_path     | /Users/mobile/Library/Keychains/login.keychain-db |
| keychain_password | ********                                          |
| platform          | ios                                               |
+-------------------+---------------------------------------------------+

INFO [2018-08-01 17:03:29.37]: Starting login with user 'mobile@activewebsite.com'
INFO [2018-08-01 17:03:31.06]: Successfully logged in
INFO [2018-08-01 17:03:32.21]: $ security import /var/folders/8z/wmp1g63j0sn3c02b05wdc1mm0000gp/T/d20180801-40482-wupnp3/certs/enterprise/S4GBG84363.p12 -k '/Users/mobile/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.29.0"

default_platform :ios



platform :ios do
  before_all do
    ENV["HIPCHAT_API_TOKEN"] = "0021438866bda6526b53da70db5391"
    ENV["MATCH_PASSWORD"] = "XXXXXXXXX"
    ENV["FASTLANE_PASSWORD"] = "XXXXXXXXXX"
    ENV["GIT_CHECKOUT"] = sh("git rev-parse --short HEAD 2> /dev/null | sed 's/\(.*\)/\1/'")
    # cocoapods
  end


  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build Enterprise IPA"
  lane :enterprise do |target|
    puts "target name #{ENV["ENV_SCHEME"]} bundle #{ENV["ENV_APP_ID"]}"
    #increment_build_number
    match(app_identifier: ENV["ENV_APP_ID"])
    gym(workspace: "./iOS-Core.xcworkspace", scheme: ENV["ENV_SCHEME"], export_method: "enterprise", clean: true, export_xcargs: "-allowProvisioningUpdates")

    sh("./upload.sh #{ENV["UPLOAD_FOLDER"]} #{ENV["ENV_BUILD_DIR"]}")
    hipchat(
        version: "1",
        channel: "3838648",
        message: "A new version of #{ENV["ENV_SCHEME"]} is available on the FTP - @#{ENV['GIT_CHECKOUT']}" # "Mobile Build Room"
      )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    sigh(
      adhoc: false # otherwise sigh will produce an ad-hoc profile
    )
    snapshot
    gym(scheme: "iOS-Core") # Build your app - more options available
    deliver(force: true)
        hipchat(
      version: "1",
      channel: "3838648",
      message: "A new version of WKRE has been uploaded to iTunes Connect." # "Mobile Build Room"
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|
    hipchat(
      version: "1",
      channel: "3838648",
      custom_color: "red",
      message: "WKRE build failed - @#{ENV['GIT_CHECKOUT']}" # "Mobile Build Room"
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Enerprise Distribution Account
for_lane :enterprise do
#	app_identifier "com.activewebsite.wkre-beta" # The bundle identifier of your app
	apple_id "mobile@activewebsite.com" # Your Apple email address
	team_id "E65YP8XL5R" # Developer Portal Team ID
end	

for_lane :bootstrap do
	apple_id "mobile@activewebsite.com" # Your Apple email address
	team_id "E65YP8XL5R" # Developer Portal Team ID
end
# App Store Production Account

  for_lane :release do
    app_identifier 'com.activewebsite.wkre' # The bundle identifier of your app
    apple_id 'mobile-accounts@activewebsite.com' # Your Apple email address
    team_id 'MZEH9D559Y' # Developer Portal Team ID
  end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2018-08-01**
</details></pre>
</details>

**Comment by jwilson85** [comment]
Is there a slack channel?

**Comment by joshdholtz** [comment]
@jwilson85 This is a very strange spot for it to hang? How long have your left it go? Also, does doing a restart help this at all? I'm not sure if a restart would help at all but if could help maybe if its a weird keychain thing?

If you want to try some other things, I would maybe try creating another keychain and specify that with cert to see if that fixes it. Maybe its an issue with your login keychain 🤔

**Comment by jwilson85** [comment]
So as it turns out the keychain was locking up when I tried to remove keys from it. I tried that cuz of something I came across on the web. Anyways I rest the keychain a few times actually. And then everything started working.
