### ISSUE TITLE
Show fastlane failures *after* the update notice

### ISSUE THREAD

**Issue by mmarvick** [fastlane/fastlane#13029]
#### Motivation Behind Feature
When there's an update for fastlane, that can take up 20+ lines of the terminal window. It's also the last thing shown before fastlane executes, and ends with green text.

Any fastlane build failures are shown before that. But when looking at the console window at a glance, it can look like the build succeeded, since the last line is green. Especially if your terminal window is only at a height of about 25 lines, the failures will all be "above the fold", so the window just looks green and good.

#### Feature Description
- Show a 'fastlane failed' message in red text *after* showing the fastlane update suggestion message

#### Alternatives or Workarounds
None that I know of!

#### Demonstration of current behavior

<img width="652" alt="screen shot 2018-08-03 at 5 43 36 pm" src="https://user-images.githubusercontent.com/3861298/43670791-033c61c0-9745-11e8-84ee-88f14ad28f64.png">

**Comment by joshdholtz** [comment]
@mmarvick Heyy 👋 Thanks for the feedback! I do agree that the changelog can get a little crazy big sometimes so I would recommend setting the environment variable to hide the chanelog - `FASTLANE_HIDE_CHANGELOG=1` (https://docs.fastlane.tools/advanced/#hide-changelog-information-at-the-end-of-running-fastlane)

I think we would like to keep the way it is for now (as updating to the lastest _fastlane_ is also important as things change a lot) but this should help you out with putting higher priority on seeing any _fastlane_ errors that occur 😊
