### ISSUE TITLE
/Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:27:in `binary_path': [!] Missing xctest binary:

### ISSUE THREAD

**Issue by homebizjunk** [fastlane/fastlane#13028]
I executed the following lane. Just when it is about to start the test, I got the following error and saying /Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:27:in `binary_path': [!] Missing xctest binary:'   Please help me out in resolving this issue.  Thank you in advance!

 fastlane buildBVT

[14:10:22]: ▸ Test build Succeeded
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 0 |
| Number of failures | 0 |
+--------------------+---+

+----------------------------+----------------+
|                Lane Context                 |
+----------------------------+----------------+
| DEFAULT_PLATFORM           | mac            |
| PLATFORM_NAME              | mac            |
| LANE_NAME                  | mac buildBVT   |
| SCAN_DERIVED_DATA_PATH     | ../DerivedData |
| SCAN_GENERATED_PLIST_FILES | []             |
| SCAN_GENERATED_PLIST_FILE  |                |
+----------------------------+----------------+

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | opt_out_usage    | 0           |
| 2    | default_platform | 0           |
| 💥   | multi_scan       | 37          |
+------+------------------+-------------+

[14:10:22]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:27:in `binary_path': [!] Missing xctest binary: '../DerivedData/Build/Products/Release/...DesktopUITests-Runner.app/Contents/PlugIns/...DesktopUITests.xctest/...DesktopUITests' (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:36:in `objc_tests'
	from /Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:68:in `tests'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:15:in `block in xctestrun_tests'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:14:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:14:in `xctestrun_tests'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:7:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:58:in `testables_tests'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:54:in `scan_testable'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:41:in `block in scan'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:40:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:40:in `scan'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:23:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:327:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

====================
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.5                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.5 (17F70a)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane
#update_fastlane
# This is the minimum version number required.
# Update this, if you use features of a newer version
#fastlane_version "1.105.1"
opt_out_usage

default_platform :mac

platform :mac do
before_all do
# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
end

desc "Build ShareFile Drive Mapper Project and run BVT test"
lane :buildBVT do |options|
    scheme_to_test = "SFMDriveMapperBVT"
    multi_scan(
        workspace:"../CitrixFiles.xcworkspace",
        scheme: scheme_to_test,
        configuration:"Release",
        code_coverage: true,
        derived_data_path: "../DerivedData",
        output_types: "html,junit,json-compilation-database",
        output_directory: "../build/reports/UI_test",
        try_count: 5,
        buildlog_path: "../build/logs/xcodebuild"
    )
end

# You can define as many lanes as you want

after_all do |lane|
# This block is called, only if the executed lane was successful

# slack(
#   message: "Successfully deployed new App Update."
# )
end

error do |lane, exception|
# slack(
#   message: exception.message,
#   success: false
# )
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.desktop.widget" # The bundle identifier of your app
apple_id "kanth@gmail.com" # Your Apple email address

team_id "XXXXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.5.3   | ✅ Up-To-Date  |
| fastlane-plugin-test_center | 3.5.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| slack-notifier              | 2.3.2        |
| atomos                      | 0.1.2        |
| claide                      | 1.0.2        |
| colored2                    | 3.1.2        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.5.9        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.2.8        |
| addressable                 | 2.5.2        |
| multipart-post              | 2.0.0        |
| word_wrap                   | 1.0.0        |
| public_suffix               | 2.0.5        |
| tty-screen                  | 0.6.5        |
| tty-cursor                  | 0.6.0        |
| tty-spinner                 | 0.8.0        |
| babosa                      | 1.0.2        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| excon                       | 0.62.0       |
| faraday                     | 0.15.2       |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20180417 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| fastimage                   | 2.1.3        |
| gh_inspector                | 1.1.3        |
| mini_magick                 | 4.5.1        |
| multi_json                  | 1.13.1       |
| multi_xml                   | 0.6.0        |
| rubyzip                     | 1.2.1        |
| security                    | 0.1.3        |
| xcpretty-travis-formatter   | 1.0.0        |
| dotenv                      | 2.5.0        |
| bundler                     | 1.16.3       |
| faraday_middleware          | 0.12.2       |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.5        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| representable               | 3.0.4        |
| mime-types-data             | 3.2016.0521  |
| mime-types                  | 3.1          |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| os                          | 1.0.0        |
| signet                      | 0.8.1        |
| googleauth                  | 0.6.3        |
| httpclient                  | 2.8.3        |
| google-api-client           | 0.23.4       |
| emoji_regex                 | 0.1.1        |
| json                        | 2.1.0        |
| io-console                  | 0.4.5        |
| CFPropertyList              | 3.0.0        |
| libxml-ruby                 | 2.9.0        |
| plist                       | 3.4.0        |
| unicode-display_width       | 1.4.0        |
| terminal-table              | 1.8.0        |
| xctest_list                 | 1.1.3        |
| fastlane-plugin-test_center | 3.5.3        |
</details>

*generated on:* **2018-08-03**
</details>

**Comment by joshdholtz** [comment]
@homebizjunk Heyyy 👋 I think you actually want to file this issue under https://github.com/lyndsey-ferguson/fastlane-plugin-test_center. This is an error with using the `xctest_list` gem which _fastlane_ itself does not use but your `multi_scan` plugin does. I'm going to close this for now since this is an issue with a third party plugin 🙃
