### ISSUE TITLE
Test code my fork for Spaceship changes

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#13032]
Hello,

I have forked and made some changes to Spaceship code (in my local Fastlane repo). I want to test them now, but not sure how to test it. Tried looking at help documentation, but not seem successful. I have tried `bundle install --system`, but didn't seem to have worked. 

I want to call Spaceship functions from another repo. Uninstalled Fastlane gem using `gem uninstall fastlane` and trying to install Fastlane (system-wide) from my fork. Can anyone point me in the right direction, please?

Any help is greatly appreciated!

**Comment by joshdholtz** [comment]
@scorpion35 Hello again 😊 The best option here is to point `Gemfile` for your project that you are using _fastlane_ in where your fork/cloned repo is.

## Local Directory
```rb
source "https://rubygems.org"

gem "fastlane", :path => "../fastlane"
```

## Remote branch
```rb
source "https://rubygems.org"

gem 'fastlane', :git => 'https://github.com/scorpion35/fastlane.git', :branch => 'your-branch-name'
```

**Comment by scorpion35** [comment]
Awesome :) 👍 Cannot believe it's this simple. It worked like a gem (see what I did there :D)

```
gem 'fastlane', :require => 'spaceship', :path => '<my fork/branch path>'
```

Thank you very much for your help!!
