### ISSUE TITLE
'SCAN_GENERATED_PLIST_FILE ' lane context is nil with Xcode 10 Beta 5

### ISSUE THREAD

**Issue by taisukeh** [fastlane/fastlane#13034]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The `run_test` action does not generate `SCAN_GENERATED_PLIST_FILE` lane context with Xcode 10 Beta 5. Then, [trainer](https://github.com/KrauseFx/trainer) plugin does not work.

Fastfile
```
    run_tests(scheme: scheme, code_coverage: true, fail_build: false)

    puts "== Run Test Lane Contexts =="
    p lane_context[Actions::SharedValues::SCAN_GENERATED_PLIST_FILES]
    p lane_context[Actions::SharedValues::SCAN_GENERATED_PLIST_FILE]
```

will produce...

Xcode 10 Beta 5:

```
== Run Test Lane Contexts ==
[]
nil
```

Xcode 9.4.1

```
 == Run Test Lane Contexts
["/Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpaxnpohmrdaamsu/Logs/Test/AE86324F-E4AD-4D57-BBE8-81917015C34D_TestSummaries.plist"]
"/Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpaxnpohmrdaamsu/Logs/Test/AE86324F-E4AD-4D57-BBE8-81917015C34D_TestSummaries.plist"
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

+--------------------------------+---------+------------------------------------------------+
|                                       Used plugins                                        |
+--------------------------------+---------+------------------------------------------------+
| Plugin                         | Version | Action                                         |
+--------------------------------+---------+------------------------------------------------+
| fastlane-plugin-carthage_cache | 0.1.1   | carthage_cache_install carthage_cache_publish  |
|                                |         | carthage_cache_exist                           |
| fastlane-plugin-trainer        | 0.4.0   | trainer                                        |
+--------------------------------+---------+------------------------------------------------+

[15:21:52]: Driving the lane 'ios test' 🚀
[15:21:52]: -----------------------
[15:21:52]: --- Step: run_tests ---
[15:21:52]: -----------------------
[15:21:52]: $ xcodebuild -showBuildSettings -scheme sample_calc_v2 -project ./sample_calc_v2.xcodeproj
[15:21:54]: Found simulator "iPhone 5s (12.0)"
[15:21:54]: $ xcodebuild -showBuildSettings -scheme sample_calc_v2 -project ./sample_calc_v2.xcodeproj
[15:21:56]: Found simulator "iPhone 5s (12.0)"

+----------------------------+---------------------------------------------------------------------------------------+
|                                              Summary for scan 2.101.1                                              |
+----------------------------+---------------------------------------------------------------------------------------+
| scheme                     | sample_calc_v2                                                                     |
| code_coverage              | true                                                                                  |
| fail_build                 | false                                                                                 |
| project                    | ./sample_calc_v2.xcodeproj                                                         |
| derived_data_path          | /Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpax  |
|                            | npohmrdaamsu                                                                          |
| clean                      | false                                                                                 |
| skip_build                 | false                                                                                 |
| output_directory           | ./fastlane/test_output                                                                |
| output_types               | html,junit                                                                            |
| buildlog_path              | ~/Library/Logs/scan                                                                   |
| include_simulator_logs     | false                                                                                 |
| disable_concurrent_testing | false                                                                                 |
| should_zip_build_products  | false                                                                                 |
| result_bundle              | false                                                                                 |
| open_report                | false                                                                                 |
| skip_slack                 | false                                                                                 |
| slack_only_on_failure      | false                                                                                 |
| use_clang_report_name      | false                                                                                 |
| xcode_path                 | /Applications/Xcode-beta.app                                                          |
+----------------------------+---------------------------------------------------------------------------------------+

[15:21:56]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme sample_calc_v2 -project ./sample_calc_v2.xcodeproj -destination 'platform=iOS Simulator,id=D99E500A-3806-4A9B-9775-7220073114DD' -derivedDataPath '/Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpaxnpohmrdaamsu' -enableCodeCoverage YES build test | tee '/Users/tahori/Library/Logs/scan/sample_calc_v2-sample_calc_v2.log' | xcpretty --no-color --report html --output '/Users/tahori/workspace/iOSSample/fastlane/test_output/report.html' --report junit --output '/Users/tahori/workspace/iOSSample/fastlane/test_output/report.junit' --report junit --output '/var/folders/c5/gy7b1r9d36n_msknf1w4ygvw0000gp/T/junit_report20180806-93683-19in60j'
[15:21:56]: ▸ Loading...
[15:21:58]: ▸ Linking sample_calc_v2
[15:22:00]: ▸ Build Succeeded
[15:22:00]: ▸ Linking sample_calc_v2
[15:22:01]: ▸ Linking sample_calc_v2Tests
[15:22:02]: ▸ 2018-08-06 15:22:02.821 xcodebuild[93749:3310799]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[15:22:02]: ▸ /Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpaxnpohmrdaamsu/Logs/Test/Run-sample_calc_v2-2018.08.06_15-21-58-+0900.xcresult/2_Test/Diagnostics/sample_calc_v2Tests-414D9714-40FE-4397-9E84-2D7A933451D6/sample_calc_v2Tests-E2CBDACB-75FA-46FF-9693-2AC4C97F1735/Session-sample_calc_v2Tests-2018-08-06_152202-b1hpwY.log
[15:22:02]: ▸ 2018-08-06 15:22:02.822 xcodebuild[93749:3310787] [MT] IDETestOperationsObserverDebug: (920EB75C-4ECE-4D6E-B504-4247EA2302E3) Beginning test session sample_calc_v2Tests-920EB75C-4ECE-4D6E-B504-4247EA2302E3 at 2018-08-06 15:22:02.822 with Xcode 10L221o on target <DVTiPhoneSimulator: 0x7ff28de12900> {
[15:22:02]: ▸ SimDevice: iPhone 5s (D99E500A-3806-4A9B-9775-7220073114DD, iOS 12.0, Shutdown)
[15:22:02]: ▸ } (12.0 (16A5339e))
[15:22:16]: ▸ All tests
[15:22:16]: ▸ Test Suite sample_calc_v2Tests.xctest started
[15:22:16]: ▸ sample_calc_v2Tests
[15:22:16]: ▸ ✓ testExample (0.001 seconds)
[15:22:16]: ▸ ◷ testPerformanceExample measured (0.000 seconds)
[15:22:16]: ▸ ✓ testPerformanceExample (0.444 seconds)
[15:22:16]: ▸ Executed 2 tests, with 0 failures (0 unexpected) in 0.445 (0.449) seconds
[15:22:17]: ▸ 2018-08-06 15:22:17.013 xcodebuild[93749:3310844]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[15:22:17]: ▸ /Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpaxnpohmrdaamsu/Logs/Test/Run-sample_calc_v2-2018.08.06_15-21-58-+0900.xcresult/2_Test/Diagnostics/sample_calc_v2UITests-1639DB04-A861-4FC5-B412-942530304E39/sample_calc_v2UITests-77171B20-247F-430C-A2A7-240100A42A12/Session-sample_calc_v2UITests-2018-08-06_152217-XKsdsw.log
[15:22:17]: ▸ 2018-08-06 15:22:17.014 xcodebuild[93749:3310787] [MT] IDETestOperationsObserverDebug: (54254D2A-914B-4065-94A8-EDF687FA3381) Beginning test session sample_calc_v2UITests-54254D2A-914B-4065-94A8-EDF687FA3381 at 2018-08-06 15:22:17.014 with Xcode 10L221o on target <DVTiPhoneSimulator: 0x7ff28de12900> {
[15:22:17]: ▸ SimDevice: iPhone 5s (D99E500A-3806-4A9B-9775-7220073114DD, iOS 12.0, Booted)
[15:22:17]: ▸ } (12.0 (16A5339e))
[15:22:21]: ▸ All tests
[15:22:21]: ▸ Test Suite sample_calc_v2UITests.xctest started
[15:22:21]: ▸ sample_calc_v2UITests
[15:22:32]: ▸ ✓ testExample (11.323 seconds)
[15:22:32]: ▸ Executed 1 test, with 0 failures (0 unexpected) in 11.323 (11.326) seconds
[15:22:32]: ▸ 2018-08-06 15:22:32.744 xcodebuild[93749:3310787] [MT] IDETestOperationsObserverDebug: 29.939 elapsed -- Testing started completed.
[15:22:32]: ▸ 2018-08-06 15:22:32.744 xcodebuild[93749:3310787] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[15:22:32]: ▸ 2018-08-06 15:22:32.744 xcodebuild[93749:3310787] [MT] IDETestOperationsObserverDebug: 29.939 sec, +29.939 sec -- end
[15:22:33]: ▸ Test Succeeded
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 3 |
| Number of failures | 0 |
+--------------------+---+

[15:22:39]: == Run Test Lane Contexts
[]
nil
[15:22:39]: ---------------------
[15:22:39]: --- Step: slather ---
[15:22:39]: ---------------------
[15:22:39]: $ slather coverage --scheme sample_calc_v2 sample_calc_v2.xcodeproj
[15:22:40]: ▸ Slathering...
[15:22:44]: ▸ sample_calc_v2/AppDelegate.swift: 7 of 21 lines (33.33%)
[15:22:44]: ▸ sample_calc_v2/FirstViewController.swift: 4 of 9 lines (44.44%)
[15:22:44]: ▸ sample_calc_v2/SecondViewController.swift: 4 of 8 lines (50.00%)
[15:22:44]: ▸ Tested 15/38 statements
[15:22:44]: ▸ Test Coverage: 39.47%
[15:22:44]: ▸ Slathered
[15:22:44]: ---------------------
[15:22:44]: --- Step: trainer ---
[15:22:44]: ---------------------

+-------------+-------------+
| Summary for trainer 0.7.0 |
+-------------+-------------+
| path        | .           |
| extension   | .xml        |
+-------------+-------------+

+----------------------------+---------------------------------------------------------------------------------------+
|                                                    Lane Context                                                    |
+----------------------------+---------------------------------------------------------------------------------------+
| PLATFORM_NAME              | ios                                                                                   |
| LANE_NAME                  | ios test                                                                              |
| SCAN_DERIVED_DATA_PATH     | /Users/tahori/Library/Developer/Xcode/DerivedData/sample_calc_v2-azembgmojnserpax  |
|                            | npohmrdaamsu                                                                          |
| SCAN_GENERATED_PLIST_FILES | []                                                                                    |
| SCAN_GENERATED_PLIST_FILE  |                                                                                       |
+----------------------------+---------------------------------------------------------------------------------------+
[15:22:45]: No test result files found in directory '.', make sure the file name ends with 'TestSummaries.plist'

+------+-----------+-------------+
|        fastlane summary        |
+------+-----------+-------------+
| Step | Action    | Time (in s) |
+------+-----------+-------------+
| 1    | run_tests | 46          |
| 2    | slather   | 5           |
| 💥   | trainer   | 0           |
+------+-----------+-------------+

[15:22:45]: fastlane finished with errors

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                       |
| --------------------------- | ----------------------------------------------------------- |
| OS                          | 10.13.6                                                     |
| Ruby                        | 2.5.0                                                       |
| Bundler?                    | true                                                        |
| Git                         | git version 2.16.1                                          |
| Installation Source         | ~/workspace/iOSSample/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.13.6 (17G65)                                    |
| Ruby Lib Dir                | ~/.anyenv/envs/rbenv/versions/2.5.0/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                  |
| Is contained                | false                                                       |
| Is homebrew                 | false                                                       |
| Is installed via Fabric.app | false                                                       |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/            |
| Xcode Version               | 10.0                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
if ENV['Screwdriver']
  fastlane_require 'approduce/sd'
  import_shared_fastfile(:ios)
end

platform :ios do
  scheme = 'approduce_calc_v2'
  proj = 'approduce_calc_v2.xcodeproj'

  before_all do
    xcode_select ENV['XCODE_9_2'] if ENV['SCREWDRIVER']
   
    # Dragonの向き先は .env.default で設定している
    # dragon_carthage_cache(carthage_params: { platform: 'iOS', use_binaries: false })
  end

  desc "Build app for InHouse"
  lane :build do
    add_badge(custom: ENV['APPRODUCE_BADGE_DEV_LIGHT'])

    build_app(
      scheme: scheme,
      export_team_id: ENV['YAHOO_JAPAN_ADEP_TEAMID'],
      export_method: 'enterprise'
    )

    upload_to_approduce
  end

  desc "Build sim app"
  lane :build_sim do
    build_sim_app(
      scheme: scheme,
    )

    upload_to_approduce
  end

  desc "Run unit test"
  lane :test do
    run_tests(scheme: scheme, code_coverage: true, fail_build: false)

    puts "== Run Test Lane Contexts"
    p lane_context[Actions::SharedValues::SCAN_GENERATED_PLIST_FILES]
    p lane_context[Actions::SharedValues::SCAN_GENERATED_PLIST_FILE]

    slather(scheme: scheme, proj: proj)
    trainer
  end

  desc "Run UI test"
  lane :uitest do
    capture_screenshots(scheme: scheme, skip_helper_version_check: true)
  end

  after_all do |lane, options|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception, options|
    # This block will get executed when an error occurs
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                         | Version | Update-Status |
| ------------------------------ | ------- | ------------- |
| fastlane-plugin-carthage_cache | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-trainer        | 0.4.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                            | Version      |
| ------------------------------ | ------------ |
| did_you_mean                   | 1.2.0        |
| bundler                        | 1.16.1       |
| CFPropertyList                 | 2.3.6        |
| concurrent-ruby                | 1.0.5        |
| i18n                           | 1.0.1        |
| minitest                       | 5.11.3       |
| thread_safe                    | 0.3.6        |
| tzinfo                         | 1.2.5        |
| activesupport                  | 5.2.0        |
| public_suffix                  | 2.0.5        |
| addressable                    | 2.5.2        |
| atomos                         | 0.1.2        |
| aws-sigv4                      | 1.0.2        |
| jmespath                       | 1.4.0        |
| aws-sdk-core                   | 2.11.64      |
| aws-sdk-resources              | 2.11.64      |
| aws-sdk                        | 2.11.64      |
| babosa                         | 1.0.2        |
| highline                       | 1.7.10       |
| commander                      | 4.4.5        |
| carthage_cache                 | 0.9.1        |
| claide                         | 1.0.2        |
| clamp                          | 0.6.5        |
| colored                        | 1.2          |
| colored2                       | 3.1.2        |
| commander-fastlane             | 4.4.6        |
| declarative                    | 0.0.10       |
| declarative-option             | 0.1.0        |
| unf_ext                        | 0.0.7.5      |
| unf                            | 0.1.4        |
| domain_name                    | 0.5.20180417 |
| dotenv                         | 2.5.0        |
| emoji_regex                    | 0.1.1        |
| excon                          | 0.62.0       |
| multipart-post                 | 2.0.0        |
| faraday                        | 0.15.2       |
| http-cookie                    | 1.0.3        |
| faraday-cookie_jar             | 0.0.6        |
| faraday_middleware             | 0.12.2       |
| fastimage                      | 2.1.3        |
| gh_inspector                   | 1.1.3        |
| jwt                            | 2.1.0        |
| memoist                        | 0.16.0       |
| multi_json                     | 1.13.1       |
| os                             | 1.0.0        |
| signet                         | 0.8.1        |
| googleauth                     | 0.6.3        |
| httpclient                     | 2.8.3        |
| mime-types-data                | 3.2016.0521  |
| mime-types                     | 3.1          |
| uber                           | 0.1.0        |
| representable                  | 3.0.4        |
| retriable                      | 3.1.2        |
| google-api-client              | 0.23.4       |
| json                           | 2.1.0        |
| mini_magick                    | 4.5.1        |
| multi_xml                      | 0.6.0        |
| plist                          | 3.4.0        |
| rubyzip                        | 1.2.1        |
| security                       | 0.1.3        |
| naturally                      | 2.2.0        |
| simctl                         | 1.6.5        |
| slack-notifier                 | 2.3.2        |
| terminal-notifier              | 1.8.0        |
| unicode-display_width          | 1.4.0        |
| terminal-table                 | 1.8.0        |
| tty-screen                     | 0.6.5        |
| tty-cursor                     | 0.6.0        |
| tty-spinner                    | 0.8.0        |
| word_wrap                      | 1.0.0        |
| nanaimo                        | 0.2.6        |
| xcodeproj                      | 1.5.9        |
| rouge                          | 2.0.7        |
| xcpretty                       | 0.2.8        |
| xcpretty-travis-formatter      | 1.0.0        |
| fastlane-plugin-carthage_cache | 0.1.1        |
| trainer                        | 0.7.0        |
| fastlane-plugin-trainer        | 0.4.0        |
| mini_portile2                  | 2.3.0        |
| nokogiri                       | 1.8.4        |
| slather                        | 2.4.6        |
</details>

*generated on:* **2018-08-06**
</details>

**Comment by joshdholtz** [comment]
@taisukeh Thanks for reporting this! I'm installing Xcode 10 Beta so that I can take a look at this

**Comment by SlaunchaMan** [comment]
This seems to be the same issue as in [trainer](https://github.com/KrauseFx/trainer/pull/21); Xcode 10 uses a new path. The plist path is currently determined thusly:
`Dir["#{derived_data_path}/**/Logs/Test/*TestSummaries.plist"]`
