### ISSUE TITLE
nexus_upload action requires specific nexus mount path

### ISSUE THREAD

**Issue by chrisgibbs** [fastlane/fastlane#1303]
The `nexus_upload` action constructs the upload URL with a hard coded mount path for nexus at `/nexus`:
`
"#{params[:endpoint].shellescape}/nexus/service/local/artifact/maven/content"
`
I believe the `/nexus` mount path is default when installing it but not required. So Nexus could be mounted at `/` as it is in my case.

I'd propose that the `endpoint` parameter require the path to Nexus as well. Allowing somebody to specify `https://host`, `https://host/nexus`, or `https://host:port/whatever/path/they/like`.

**Comment by mfurtak** [comment]
Fixed in #1325 - nice work!
