### ISSUE TITLE
Cannot sign the app with extension

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#13036]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have an extension with push provisioning and Fastlane is not able to sign it properly:

> Error Domain=IDEProvisioningErrorDomain Code=9 ""NotificationService.appex" requires a provisioning profile with the Push Notifications feature." UserInfo={NSLocalizedDescription="NotificationService.appex" requires a provisioning profile with the Push Notifications feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

Xcodebuild suggest that there is a bug in generated plist, which does not include all of the targets in `provisioningProfiles` section. Any way to fix this? it's been a while, I remember this issue date to years in past.

That's my Fastfile
```
opt_out_usage
fastlane_version "1.109.0"
skip_docs
default_platform :ios

lane :beta do
  get_certificates
  get_provisioning_profile
  build_app
  upload_to_testflight(skip_waiting_for_build_processing: true)
end
```

##### Workaround

Using `sigh` directly works. Really confusing there are so many new actions now that do the same thing but are less flexible.

```
cert
sigh(app_identifier: "com.developer.app")
sigh(app_identifier: "com.developer.app.ext")
gym
pilot(distribute_external: false, skip_waiting_for_build_processing: true)
```

**Comment by joshdholtz** [comment]
@pronebird There are no plans right now. We don't want to be too invasive and start pulling out IDs that are wrong. Example of this is if projects have multiple targets for different style builds. We could easily just scan through all the info.plist files but some of those IDs that we find might actually be ones that the end user doesn't want to do. So it is safest from everyone's perspective for us to just grab the primary ID based off of the target/configuration if we can find it. 😊

**Comment by pronebird** [comment]
@joshdholtz but the target itself bundles extensions with it, it makes no sense to not include the IDs for extensions because it's likely to cause a code signing issue that I face. Either way I think documentation lacks some explanation.

**Comment by joshdholtz** [comment]
@pronebird I appreciate your feedback 😊 I don't use extensions very often so if you would like to create a pull request into the docs or a pull request to make these changes into _match_, _cert_, or _sigh_ that would be totes okay 🙌  We, the maintainers, make as many fixes and improvements to _fastlane_ as we can but there are so many things that we can't always keep up. If you would like to create that PR to get things into _fastlane_ faster and the way you see if I would love to review it ❤️
