### ISSUE TITLE
Fails to generate snapshots

### ISSUE THREAD

**Issue by seanmcneil** [fastlane/fastlane#13031]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fails to generate snapshots.

Updated folder permissions to 777:
drwxrwxrwx  10 user  staff    320 Jul 13 15:04 screenshots

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>fastlane snapshot
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir': [!] Permission denied @ dir_s_mkdir - /screenshots (Errno::EACCES)</pre>
</details>

### Environment
<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.18.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "MyApp.xcworkspace", scheme: "MyApp")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end

  lane :release do
  build_app(scheme: "MyApp")
  end

  lane :uploadscreenshots do
    upload_to_app_store
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("com.abc.MyApp") # The bundle identifier of your app
apple_id("me@email.com") # Your Apple email address

itc_team_id("MyConnectID") # iTunes Connect Team ID
team_id("MyTeamID") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.2       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.4.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.9        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| signet                    | 0.8.1        |
| googleauth                | 0.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| unicode-display_width     | 1.4.0        |
</details>

*generated on:* **2018-08-04**
</details></pre>
</details>

**Comment by seanmcneil** [comment]
Was able to resolve this by re-installing fastlane for the affected project.

**Comment by joshdholtz** [comment]
@seanmcneil Glad you got it solved! Happy fastlaning 🚀
