### ISSUE TITLE
Is it possible to set versions per configuration basis?

### ISSUE THREAD

**Issue by jontelang** [fastlane/fastlane#13035]
In our app, we set the version manually for Release/Debug configurations. For example:

![screen shot 2018-08-06 at 4 32 11 pm](https://user-images.githubusercontent.com/899947/43709155-4eddf636-9996-11e8-9e2e-2803c2e4a631.png)

I'm wondering if there is some way to do this with Fastlane. I see that [get_version_number](https://docs.fastlane.tools/actions/get_version_number/) has the option to return it, however the [increment_version_number](https://docs.fastlane.tools/actions/increment_version_number/) does not. Is there a reason for this?

**Comment by jontelang** [comment]
I see. Thanks for the reply, and the suggestion.

**Comment by joshdholtz** [comment]
@jontelang Not a problem! This is now on my list of things to change... when I get time 😉
