### ISSUE TITLE
nexus_upload action does not respect the verbose parameter

### ISSUE THREAD

**Issue by chrisgibbs** [fastlane/fastlane#1304]
The `nexus_upload` action forces no log output, regardless of the value passed to the `verbose` parameter:

`Fastlane::Actions.sh(command.join(' '), log: false)`

I'd propose modifying the action to use the `verbose` parameter's value when executing the script action:

`Fastlane::Actions.sh(command.join(' '), log: params[:verbose])`

**Comment by mfurtak** [comment]
Fixed in #1325 - nice work!
