### ISSUE TITLE
Certificate Encryption/Decryption failing

### ISSUE THREAD

**Issue by asingh12541** [fastlane/fastlane#13049]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
1) I am trying to code sign a dmg using fastlane and following the documentation : https://medium.com/sixt-labs-techblog/continuous-integration-and-delivery-at-sixt-91ca215670a0

2) I have a git repo in the following format
/
--.cert
--.p12
--.certSigningRequest
--AppStore_com.xxx.xxxxx.mobileprovision

3) After entering the pass phrases in cli it's showing me the following error: `Couldn't decrypt the repo, please make sure you enter the right password!`

4) Does the gir repo needs to be in a specific structure or the certificates need to be already encrypted or whats the expected behaviour

##### Complete output when running fastlane, including the stack trace and command used
bundle exec fastlane certificates refresh_certficates:true --troubleshoot --verbose
[✔] 🚀 
[15:55:32]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
ERROR [2018-08-07 15:55:32.78]: ---
ERROR [2018-08-07 15:55:32.78]: Are you sure you want to enable '--troubleshoot'?
ERROR [2018-08-07 15:55:32.78]: All commmands will run in full unfiltered output mode.
ERROR [2018-08-07 15:55:32.78]: Sensitive data, like passwords, could be printed to the log.
ERROR [2018-08-07 15:55:32.78]: ---
 [2018-08-07 15:55:32.78]: Do you really want to enable --troubleshoot (y/n)
y
DEBUG [2018-08-07 15:55:35.17]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/ankitsingh/Documents/GitHub/try-it-now/fastlane/Appfile'
- team_id: 'xxxxx'
- apple_id: 'xxxxx@xxxx.com'
-------
DEBUG [2018-08-07 15:55:35.39]: Using refresh_certficates: true
INFO [2018-08-07 15:55:35.40]: Driving the lane 'certificates' 🚀
INFO [2018-08-07 15:55:35.40]: -------------------
INFO [2018-08-07 15:55:35.40]: --- Step: match ---
INFO [2018-08-07 15:55:35.40]: -------------------
INFO [2018-08-07 15:55:35.70]: Successfully loaded '/Users/xxxxxx/Documents/GitHub/xx-xxx-xxx/fastlane/Matchfile' 📄

+----------------+-----------------------------------------------+
|          Detected Values from './fastlane/Matchfile'           |
+----------------+-----------------------------------------------+
| git_url        | https://github.com/xxxxxx/certificates |
| type           | development                                   |
| app_identifier | ["com.xxxx.xxxxx"]                     |
| username       | xxxx@xxxxx.com                             |
+----------------+-----------------------------------------------+

+-----------------------+-----------------------------------------------+
|                       Summary for match 2.101.1                       |
+-----------------------+-----------------------------------------------+
| git_branch            | master                                        |
| app_identifier        | ["com.xxx.xxxxxx"]                     |
| team_id               | xxxxxxxxxx                                    |
| type                  | development                                   |
| readonly              | true                                          |
| verbose               | true                                          |
| force_for_new_devices | true                                          |
| force                 | true                                          |
| clone_branch_directly | true                                          |
| git_url               | https://github.com/xxxxx/certificates |
| username              | xxx@xxxx.xxx                             |
| keychain_name         | xxx.xxxx                                |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| skip_docs             | false                                         |
| platform              | ios                                           |
+-----------------------+-----------------------------------------------+

INFO [2018-08-07 15:55:35.71]: Cloning remote git repo...
INFO [2018-08-07 15:55:35.71]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/xxx/certificates' '/var/folders/wv/lrln055s5q58y9bbqzvr8s2m0000gn/T/d20180807-58296-nlhe35' -b master --single-branch
INFO [2018-08-07 15:55:35.72]: ▸ Cloning into '/var/folders/wv/lrln055s5q58y9bbqzvr8s2m0000gn/T/d20180807-58296-nlhe35'...
INFO [2018-08-07 15:55:37.91]: ▸ remote: Counting objects: 9, done.
INFO [2018-08-07 15:55:37.91]: ▸ remote: Compressing objects: 100% (9/9), done.
INFO [2018-08-07 15:55:37.93]: ▸ remote: Total 9 (delta 1), reused 8 (delta 0), pack-reused 0
INFO [2018-08-07 15:55:37.96]: ▸ Unpacking objects: 100% (9/9), done.
WARN [2018-08-07 15:55:38.03]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-08-07 15:55:38.04]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-08-07 15:55:38.04]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-08-07 15:55:38.04]: Passphrase for Git Repo: *********
 [2018-08-07 15:55:44.63]: Type passphrase again: *********
ERROR [2018-08-07 15:55:48.71]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/xxxxxx/Library/Keychains/xxx.xxxx-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_https://github.com/xxxx/certificates"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303830373130323534385A00  "20180807102548Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303830373130323534385A00  "20180807102548Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_https://github.com/xxxxx/certificates"
    "type"<uint32>=<NULL>
password has been deleted.

**Comment by joshdholtz** [comment]
@asingh12541 Heyyy 👋  I got a few questions for you here 😊 

1) You explained your repo format in your description. Did you manually put these files here or did you let _match_ do that? Given an empty repo, _match_ will commit the encrypted files in there for you. _match_ has a specific format that it looks for so if you manually put files in there that may be this issue. If you also manually encrypted them and put them in the repo yourself, they cold be encryped with the wrong algorithm and/or wrong hash that isn't allowing match to successfully decrypt.
2) If you are letting _match_ commit these files, make sure you **are not** using your Apple password. _match_ has its own password (that yous set) that you should be using that is not the same as your Apple password

**Comment by asingh12541** [comment]
@joshdholtz thanks! it worked!

Reason: I was putting the files manually in git repo.

Thanks
