### ISSUE TITLE
Can i generate release notes in a lane where i use deliver ?

### ISSUE THREAD

**Issue by donnib** [fastlane/fastlane#13047]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

I have following :
```
lane :flight do
  deliver(
    metadata_path: ENV["METADATA_PATH"],
    screenshots_path: ENV["SCREENSHOTS_PATH"],
    skip_binary_upload: true,
    skip_screenshots: false,
    skip_metadata: false,
    submit_for_review: false,
    username: ENV["ITUNES_CONNECT_USERNAME"],
    team_id: ENV["ITUNES_CONNECT_TEAM_ID"],
    app_icon: ENV["APPICON"],
    force: true
  )
```
Where can i issue `changelog_from_git_commits` ?

**Comment by joshdholtz** [comment]
@donnib Heyyy 👋 If you run `fastlane action deliver` or go look in https://docs.fastlane.tools/actions/deliver/#parameters you will see there is a `release_notes` option you can use 😊 

<img width="849" alt="screen shot 2018-08-07 at 8 17 27 am" src="https://user-images.githubusercontent.com/401294/43778098-69530770-9a1a-11e8-8726-09950dc9082a.png">

<img width="1078" alt="screen shot 2018-08-07 at 8 18 14 am" src="https://user-images.githubusercontent.com/401294/43778113-740d8b4a-9a1a-11e8-80c1-62c02fa494b6.png">

Happy fastlaning 🚀
