### ISSUE TITLE
FastlaneShellError 

### ISSUE THREAD

**Issue by mohamedhamada1** [fastlane/fastlane#13041]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>s warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
:app:preBuild UP-TO-DATE
:discreteSeekBar:preBuild UP-TO-DATE
:discreteSeekBar:preDebugBuild UP-TO-DATE
:discreteSeekBar:checkDebugManifest UP-TO-DATE
:discreteSeekBar:processDebugManifest UP-TO-DATE
:iap:preBuild UP-TO-DATE
:iap:preDebugBuild UP-TO-DATE
:iap:checkDebugManifest UP-TO-DATE
:iap:processDebugManifest UP-TO-DATE
:remote-logger:preBuild UP-TO-DATE
:remote-logger:preDebugBuild UP-TO-DATE
:remote-logger:checkDebugManifest UP-TO-DATE
:remote-logger:processDebugManifest UP-TO-DATE
:app:preReleaseCandidateDebugBuild UP-TO-DATE
:discreteSeekBar:compileDebugAidl UP-TO-DATE
:iap:compileDebugAidl UP-TO-DATE
:remote-logger:compileDebugAidl UP-TO-DATE
:app:compileReleaseCandidateDebugAidl UP-TO-DATE
:discreteSeekBar:packageDebugRenderscript NO-SOURCE
:iap:packageDebugRenderscript NO-SOURCE
:remote-logger:packageDebugRenderscript NO-SOURCE
:app:compileReleaseCandidateDebugRenderscript UP-TO-DATE
:app:mergeReleaseCandidateDebugShaders UP-TO-DATE
:app:compileReleaseCandidateDebugShaders UP-TO-DATE
:app:generateReleaseCandidateDebugAssets UP-TO-DATE
:discreteSeekBar:mergeDebugShaders UP-TO-DATE
:discreteSeekBar:compileDebugShaders UP-TO-DATE
:discreteSeekBar:generateDebugAssets UP-TO-DATE
:discreteSeekBar:packageDebugAssets UP-TO-DATE
:iap:mergeDebugShaders UP-TO-DATE
:iap:compileDebugShaders UP-TO-DATE
:iap:generateDebugAssets UP-TO-DATE
:iap:packageDebugAssets UP-TO-DATE
:remote-logger:mergeDebugShaders UP-TO-DATE
:remote-logger:compileDebugShaders UP-TO-DATE
:remote-logger:generateDebugAssets UP-TO-DATE
:remote-logger:packageDebugAssets UP-TO-DATE
:app:mergeReleaseCandidateDebugAssets UP-TO-DATE
:app:processReleaseCandidateDebugGoogleServices
Parsing json file: /Users/shaaban_m/rockettv-android/app/src/releaseCandidate/google-services.json
:app:checkReleaseCandidateDebugManifest UP-TO-DATE
:app:createReleaseCandidateDebugCompatibleScreenManifests
:app:mainApkListPersistenceReleaseCandidateDebug
:app:processReleaseCandidateDebugManifest
/Users/shaaban_m/rockettv-android/app/src/releaseCandidate/AndroidManifest.xml:5:5-9:19 Warning:
        application@android:icon was tagged at AndroidManifest.xml:5 to replace other declarations but no other declaration present
:app:fabricGenerateResourcesReleaseCandidateDebug
:app:generateReleaseCandidateDebugResValues UP-TO-DATE
:app:generateReleaseCandidateDebugResources UP-TO-DATE
:discreteSeekBar:compileDebugRenderscript UP-TO-DATE
:discreteSeekBar:generateDebugResValues UP-TO-DATE
:discreteSeekBar:generateDebugResources UP-TO-DATE
:discreteSeekBar:packageDebugResources UP-TO-DATE
:iap:compileDebugRenderscript UP-TO-DATE
:iap:generateDebugResValues UP-TO-DATE
:iap:generateDebugResources UP-TO-DATE
:iap:packageDebugResources UP-TO-DATE
:remote-logger:compileDebugRenderscript UP-TO-DATE
:remote-logger:generateDebugResValues UP-TO-DATE
:remote-logger:generateDebugResources UP-TO-DATE
:remote-logger:packageDebugResources UP-TO-DATE
:app:mergeReleaseCandidateDebugResources
:app:transformDataBindingBaseClassLogWithDataBindingMergeGenClassesForReleaseCandidateDebug UP-TO-DATE
:app:dataBindingGenBaseClassesReleaseCandidateDebug UP-TO-DATE
:app:generateReleaseCandidateDebugBuildConfig
:app:prepareLintJar UP-TO-DATE
:app:splitsDiscoveryTaskReleaseCandidateDebug UP-TO-DATE
:discreteSeekBar:platformAttrExtractor UP-TO-DATE
:discreteSeekBar:generateDebugRFile UP-TO-DATE
:iap:platformAttrExtractor UP-TO-DATE
:iap:generateDebugRFile UP-TO-DATE
:remote-logger:platformAttrExtractor UP-TO-DATE
:remote-logger:generateDebugRFile UP-TO-DATE
:app:processReleaseCandidateDebugResources
:app:generateReleaseCandidateDebugSources
:discreteSeekBar:generateDebugBuildConfig UP-TO-DATE
:discreteSeekBar:prepareLintJar UP-TO-DATE
:discreteSeekBar:generateDebugSources UP-TO-DATE
:discreteSeekBar:javaPreCompileDebug UP-TO-DATE
:discreteSeekBar:compileDebugJavaWithJavac UP-TO-DATE
:discreteSeekBar:processDebugJavaRes NO-SOURCE
:discreteSeekBar:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:iap:generateDebugBuildConfig UP-TO-DATE
:iap:prepareLintJar UP-TO-DATE
:iap:generateDebugSources UP-TO-DATE
:iap:javaPreCompileDebug UP-TO-DATE
:iap:compileDebugJavaWithJavac UP-TO-DATE
:iap:processDebugJavaRes NO-SOURCE
:iap:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:remote-logger:generateDebugBuildConfig UP-TO-DATE
:remote-logger:prepareLintJar UP-TO-DATE
:remote-logger:generateDebugSources UP-TO-DATE
:transport-agent:compileJava UP-TO-DATE
:transport-agent:processResources NO-SOURCE
:transport-agent:classes UP-TO-DATE
:transport-agent:jar UP-TO-DATE
:remote-logger:javaPreCompileDebug UP-TO-DATE
:remote-logger:compileDebugJavaWithJavac UP-TO-DATE
:remote-logger:processDebugJavaRes NO-SOURCE
:remote-logger:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:dataBindingExportBuildInfoReleaseCandidateDebug
:app:javaPreCompileReleaseCandidateDebug UP-TO-DATE
:app:transformDataBindingWithDataBindingMergeArtifactsForReleaseCandidateDebug UP-TO-DATE
:app:compileReleaseCandidateDebugJavaWithJavacerror: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: android.databinding.annotationprocessor.ProcessDataBinding Unable to get public no-arg constructor
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseCandidateDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
74 actionable tasks: 10 executed, 64 up-to-date

        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/gradle.rb:52:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        from Fastfile:22:in `block in parsing_binding'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13.5                              |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.15.2 (Apple Git-101.1) |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.13.5 (17F77)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | false                                |
| Is homebrew                 | true                                 |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.101.1"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "cb45f459-f6cb-42d7-900b-0e54684688a6"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do

  # call the below lane to increase version number
  bump_version_code

  # build the release variant
  gradle(task: 'assemble', build_type: 'Debug', flavor: 'releaseCandidate')

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "7d2bbad541d2694c100ccc5c5fa8de4c8fa8d753",
    build_secret: "9507494e79cb05d8923c7c39185cca5392f9a58962cc682697aaea588156e19f",
    groups: "rocket-qa-android",
    notifications: true,
    debug: true
  )

  #Commit after version increased
  git_commit(path: "./app/build.gradle", message: "Increase Version")

  # This will add an annotated git tag to the current branch
  #add_git_tag(
  #    grouping: "fastlane-beta",
  #    prefix: get_version_number(),
  #    build_number: " (" + build_number + ")"
  #)

  # Push the created git tag
   push_to_git_remote

end

lane :jawwyHomeStaging do

  # call the below lane to increase version number
  bump_version_code

  # build the release variant
  gradle(task: 'assemble', build_type: 'Debug', flavor: 'jawwyHomeStaging')

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "7d2bbad541d2694c100ccc5c5fa8de4c8fa8d753",
    build_secret: "9507494e79cb05d8923c7c39185cca5392f9a58962cc682697aaea588156e19f",
    groups: "rocket-qa-android",
    notifications: true,
    debug: true
  )

  #Commit after version increased
  git_commit(path: "./app/build.gradle", message: "Increase Version")

  # This will add an annotated git tag to the current branch
  #add_git_tag(
  #    grouping: "fastlane-beta",
  #    prefix: get_version_number(),
  #    build_number: " (" + build_number + ")"
  #)

  # Push the created git tag
   push_to_git_remote

end

lane :betaProd do
    # Create production builds
    gradle(task: 'assemble', build_type: 'Release', flavor: 'production')

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "7d2bbad541d2694c100ccc5c5fa8de4c8fa8d753",
      build_secret: "9507494e79cb05d8923c7c39185cca5392f9a58962cc682697aaea588156e19f",
      groups: "rocket-qa-android",
      notifications: false,
      debug: false
    )
end

lane :jawwyHomeProduction do
    # Create production builds
    gradle(task: 'assemble', build_type: 'Release', flavor: 'jawwyHomeProduction')

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "7d2bbad541d2694c100ccc5c5fa8de4c8fa8d753",
      build_secret: "9507494e79cb05d8923c7c39185cca5392f9a58962cc682697aaea588156e19f",
      groups: "rocket-qa-android",
      notifications: false,
      debug: false
    )
end


lane :bump_version_code do
  path = '../app/build.gradle'
  re = /versionCode\s+(\d+)/
  buildNumberExp = /def\srcBuildNumber\s=\s(\d+)/

  s = File.read(path)
  versionCode = s[re, 1].to_i
  s[re, 1] = (versionCode + 1).to_s

  puts("------------------------------")
  puts("Increasing version code from (#{versionCode}) to (#{versionCode + 1})")

  buildNumber = s[buildNumberExp, 1].to_i
  s[buildNumberExp, 1] = (buildNumber + 1).to_s

  puts("Increasing build number from (b#{buildNumber}) to (b#{buildNumber + 1})")
  puts("------------------------------")

  f = File.new(path, 'w')
  f.write(s)
  f.close
end

lane :get_version_name_lane do
  versionName = get_version_name
  puts("Current Version name is #{versionName}")

end

def get_version_name
  path = '../app/build.gradle'
  verNameExp = /def\scurrentVName(.+)/

  s = File.read(path)

  versionNameLine = s[verNameExp]
  versionName = versionNameLine[/\d(.+)\d/]
  return versionName
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-08-06**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
Going to close this issue since no description of issue was submitted. Please open another issue with all requested information and I will be happy to look into 😊
