### ISSUE TITLE
Spaceship::TestFlight::Group.create!(app_id, group_name) does not accept arguments

### ISSUE THREAD

**Issue by adrianokerbermenvia** [fastlane/fastlane#13044]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I couldn't create test groups in TestFlight via Spaceship.

I couldn't find any documentation about group creation for testing although the class Spaceship::TestFlight::Group seems to be the entry point for this task.

This question is about the Spaceship itself.

#### Question Description

I tried to create a test group for our app but the `Group.create` method always fails.
The codes we based us on were the Spaceship's source itself https://github.com/fastlane/fastlane/tree/edb089929a9c1a7b7db7ac806ffa93cb6ab0da5b/spaceship/lib/spaceship/test_flight

Below are our test codes for calling Group creation.
CODE:
`group = Spaceship::TestFlight::Group.create!(app_id, group_name)`
ERROR:
`ArgumentError: [!] wrong number of arguments (given 2, expected 0)
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/test_flight/group.rb:27:in `create!'`

CODE:
`group = Spaceship::TestFlight::Group.create(app_id, group_name)`
ERROR:
`NoMethodError: [!] undefined method `create' for Spaceship::TestFlight::Group:Class
Did you mean?  create!
Did you mean?  create!
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/base.rb:186:in `method_missing'`

Any insight about how to create groups, or even if its possible?

**Comment by joshdholtz** [comment]
@adrianokerbermenvia Heyyy 👋 This method actually uses keyword arguments so you will want something like...
```rb
group = Spaceship::TestFlight::Group.create!(app_id: app_id, group_name: group_name)
```

This should do it for you 😊

**Comment by adrianokerbermenvia** [comment]
Your example @joshdholtz worked flawless. Thank you!

**Comment by joshdholtz** [comment]
@adrianokerbermenvia Glad it worked for you! Happy fastlaning! 🚀
