### ISSUE TITLE
Snapshot: "Could not find option 'xcconfig' in the list of available options"

### ISSUE THREAD

**Issue by blastum** [fastlane/fastlane#13046]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to get started with Snapshot. I've successfully done the snapshot init, but when I try to run fastlane snapshot and select a target, I get

Building and running project - this might take some time...
[17:57:42]: snapshot run 1 of 64
[17:57:42]: Patching '/Users/james/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
[17:57:46]: Could not find option 'xcconfig' in the list of available options: workspace, project, devices, languages, launch_arguments, output_directory, ios_version, skip_open_summary, clear_previous_screenshots, reinstall_app, erase_simulator, localize_simulator, app_identifier, add_photos, add_videos, buildlog_path, clean, configuration, xcpretty_args, sdk, scheme, number_of_retries, stop_after_first_error, derived_data_path
[17:57:46]: Tests failed, re-trying 1 out of 2 times

Last time I tried to get this to work (before giving up), I think it worked in 1.48.0 and failed in 1.49.0 or so, but I am not able to get those to work for different reasons now.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>~/git/xxx: fastlane snapshot
[✔] 🚀
[17:57:39]: Successfully loaded '/Users/xxx/git/xxx/fastlane/Snapfile' 📄

+-----------+----------------------------------------------+
|        Detected Values from './fastlane/Snapfile'        |
+-----------+----------------------------------------------+
| languages | ["en-US", "de-DE", "it-IT", ["pt", "pt_BR"]] |
+-----------+----------------------------------------------+

[17:57:39]: Successfully loaded '/Users/james/git/gss-app/fastlane/Snapfile' 📄

+-----------+----------------------------------------------+
|        Detected Values from './fastlane/Snapfile'        |
+-----------+----------------------------------------------+
| languages | ["en-US", "de-DE", "it-IT", ["pt", "pt_BR"]] |
+-----------+----------------------------------------------+

Select Scheme:
1. xxx
2. yyy
?  1

+----------------------------+------------------------------------------------------------------------------------------+
|                                              Summary for snapshot 2.0.0                                               |
+----------------------------+------------------------------------------------------------------------------------------+
| workspace                  | ./xxx.xcworkspace                                                           |
| scheme                     | UITests-Live                                                                             |
| devices                    | ["iPhone 6", "iPhone 6 Plus", "iPhone 7", "iPhone 7 Plus", "iPhone 8", "iPhone 8 Plus",  |
|                            | "iPhone SE", "iPhone X", "Simulator", "iPad Air", "iPad (5th generation)", "iPad Pro     |
|                            | (9.7-inch)", "iPad Pro (12.9-inch)", "iPad Pro (12.9-inch) (2nd generation)", "iPad Pro  |
|                            | (10.5-inch)", "iPad (6th generation)"]                                                   |
| output_directory           | /Users/xxx/git/xxx/fastlane/screenshots                                            |
| languages                  | ["en-US", "de-DE", "it-IT", ["pt", "pt_BR"]]                                             |
| launch_arguments           | [""]                                                                                     |
| skip_open_summary          | false                                                                                    |
| clear_previous_screenshots | false                                                                                    |
| reinstall_app              | false                                                                                    |
| erase_simulator            | false                                                                                    |
| localize_simulator         | false                                                                                    |
| buildlog_path              | ~/Library/Logs/snapshot                                                                  |
| clean                      | false                                                                                    |
| number_of_retries          | 1                                                                                        |
| stop_after_first_error     | false                                                                                    |
| xcode_path                 | /Applications/Xcode.app                                                                  |
+----------------------------+------------------------------------------------------------------------------------------+

[17:57:42]: Building and running project - this might take some time...
[17:57:42]: snapshot run 1 of 64
[17:57:42]: Patching '/Users/xxx/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
[17:57:46]: Could not find option 'xcconfig' in the list of available options: workspace, project, devices, languages, launch_arguments, output_directory, ios_version, skip_open_summary, clear_previous_screenshots, reinstall_app, erase_simulator, localize_simulator, app_identifier, add_photos, add_videos, buildlog_path, clean, configuration, xcpretty_args, sdk, scheme, number_of_retries, stop_after_first_error, derived_data_path
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

[redacted, it's a mess]

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |
| snapshot | 2.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.16.3       |
| rake                      | 12.3.1       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.6        |
| fastimage                 | 2.1.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.4        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.9.1        |
| build-environment         | 1.1.4        |
| build-files               | 1.3.0        |
| process-group             | 1.1.0        |
| rainbow                   | 2.2.2        |
| build-graph               | 1.0.6        |
| build-makefile            | 1.0.1        |
| process-pipeline          | 1.0.1        |
| graphviz                  | 1.0.0        |
| build                     | 1.1.1        |
| io-console                | 0.4.6        |
| xcov                      | 1.4.3        |
</details>

*generated on:* **2018-08-06**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@blastum Heyyy 👋 This is really weird because `xcconfig` totes an option and was added in version `2.86.0` (https://github.com/fastlane/fastlane/pull/12067/files). Your `fastlane env` shows that you have `2.101.1` but it doesn't seem like `2.101.1` is being used when you are calling _fastlane_ because your output has `Summary for snapshot 2.0.0` when it really should say `Summary for snapshot 2.101.1`. So things should work once you figure out why _fastlane_ 2.101.1 isn't being run 😊
