### ISSUE TITLE
[Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)

### ISSUE THREAD

**Issue by TomVanDerSpek** [fastlane/fastlane#13053]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When uploading a build with fastlane pilot using GitLab CI, Transporter throws an error. As you can see in the output, fastlane successfully logs into App Store Connect with account_1. But when it starts uploading with Transporter, it uses the credentials of a totally different account_2. 

We have multiple project with different accounts. Strangely enough, uploading a build of a project for account_2 works fine. The error only occurs when uploading builds of a project for account_1. 

- I looked at similar other issues like the issue some users face when the password contains certain characters. 
- None of the accounts has 2FA
- We have search if there is any environmental value set that contains account_2's username, but no luck there. 
- Credentials are added to the keychain and they are correct.
- When I run fastlane pilot upload directly from our build server, the build is uploaded without errors.
- Only when I run fastlane pilot upload via our GitLab CI, I get the above specified error. 

It used to work fine, but  a couple of months ago this issue suddenly appeared. We have been looking for a solution since but unfortunately without any luck. If there is any additional info or info missing, please let me know. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ fastlane pilot upload --ipa build/ApplicationPROD.ipa --username account_1@itunesconnect.com --skip_submission true --skip_waiting_for_build_processing true --team_id ABCDEFGHIJ --verbose
[16:01:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2018-08-07 16:01:28.93]: Login to App Store Connect (account_1@itunesconnect.com)
Loading session from '/Users/arnold/.fastlane/spaceship/account_1@itunesconnect.com/cookie'
Looking for App Store Connect Team with ID 877382
INFO [2018-08-07 16:01:30.68]: Login successful
DEBUG [2018-08-07 16:01:30.81]: App identifier (my.application.com)
INFO [2018-08-07 16:01:31.43]: Ready to upload new build to TestFlight (App: 496189385)...
DEBUG [2018-08-07 16:01:31.43]: App Platform (ios)
INFO [2018-08-07 16:01:36.34]: Wrote XML data to '/var/folders/q0/cqtn3m_x2hvgt4kr28sy5wvc0000gn/T/d20180807-32101-23mrbt/496189385.itmsp'
INFO [2018-08-07 16:01:36.43]: Going to upload updated app to App Store Connect
INFO [2018-08-07 16:01:36.43]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2018-08-07 16:01:36.58]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar -m upload -u account_1@itunesconnect.com -p YourPassword -f /var/folders/q0/cqtn3m_x2hvgt4kr28sy5wvc0000gn/T/d20180807-32101-23mrbt/496189385.itmsp -t Signiant -k 100000 2>&1
DEBUG [2018-08-07 16:01:40.44]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
DEBUG [2018-08-07 16:01:40.59]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2018-08-07 16:01:40.59]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2018-08-07 16:01:40.74]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2018-08-07 16:01:40.74]: [Transporter]: DEBUG: Saving configuration to local path: /Users/arnold/.itmstransporter/Defaults.properties
DEBUG [2018-08-07 16:01:40.74]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.8]
DEBUG [2018-08-07 16:01:40.74]: [Transporter]: INFO: OS identifier: Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-08-07 16:01:40.74]: [Transporter]: INFO: Memory: [JVM] 812M free, 981M total, 981M max [System] (Physical) 2052M free, 8192M total (Swap) 1030M free, 2048M total
DEBUG [2018-08-07 16:01:40.75]: [Transporter]: INFO: Upload mode selected.
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: INFO: Examining the package at: /var/folders/q0/cqtn3m_x2hvgt4kr28sy5wvc0000gn/T/d20180807-32101-23mrbt/496189385.itmsp
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: DEBUG:   d890396a906e7aa20a18f0f1f38c2c80u4a00aa451b47b6c413a2f48fad1a319.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2018-08-07 16:01:40.76]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2018-08-07 16:01:40.79]: [Transporter]: INFO: Performing authentication of package 496189385.itmsp ...
DEBUG [2018-08-07 16:01:40.79]: [Transporter]: DBG-X: Memory: [JVM] 802M free, 981M total, 981M max [System] (Physical) 2039M free, 8192M total (Swap) 1030M free, 2048M total
DEBUG [2018-08-07 16:01:40.79]: [Transporter]: DBG-X: Memory: [JVM] 802M free, 981M total, 981M max [System] (Physical) 2039M free, 8192M total (Swap) 1030M free, 2048M total
DEBUG [2018-08-07 16:01:40.79]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-08-07T16:01:40+02:00
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.345765502
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u account_1@itunesconnect.com -p **hidden value** -f /var/folders/q0/cqtn3m_x2hvgt4kr28sy5wvc0000gn/T/d20180807-32101-23mrbt/496189385.itmsp -t Signiant -k 100000
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter Username = account_1@itunesconnect.com
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-08-07 16:01:40.80]: [Transporter]: INFO: id = 20180807160140-806
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2018-08-07 16:01:41.36]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)

The login credentials for 'account_2@itunesconnect.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
ERROR [2018-08-07 16:01:41.36]: Please run this tool again to apply the new password
DEBUG [2018-08-07 16:01:41.36]: [Transporter]: DBG-X: The error code is: -20101
ERROR [2018-08-07 16:01:41.50]: Transporter transfer failed.
WARN [2018-08-07 16:01:41.50]: 
ERROR [2018-08-07 16:01:41.50]: Your Apple ID or password was entered incorrectly. (-20101)

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> DBG-X:   parameter EnableJWTForAllCalls = false

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> DBG-X:   parameter ErrorCode = -20101

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> DBG-X:   parameter Success = false

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> ERROR: Your Apple ID or password was entered incorrectly. (-20101)

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> DBG-X: The error code is: -20101

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] 

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] 

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] 

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] Package Summary:

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter]  

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] 	/var/folders/q0/cqtn3m_x2hvgt4kr28sy5wvc0000gn/T/d20180807-32101-23mrbt/496189385.itmsp - Error Messages:

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] 		Your Apple ID or password was entered incorrectly. (-20101)

WARN [2018-08-07 16:01:41.54]: [iTMSTransporter] [2018-08-07 16:01:41 CEST] <main> DBG-X: Returning 1

INFO [2018-08-07 16:01:41.54]: iTunes Transporter output above ^
ERROR [2018-08-07 16:01:41.54]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/pilot/lib/pilot/build_manager.rb:41:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
ERROR: Job failed: exit status 1</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.5                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.5 (17F77)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-08-07**
</details></pre>
</details>

**Comment by TomVanDerSpek** [comment]
Any help would be appreciated

**Comment by TomVanDerSpek** [comment]
Any help would be appreciated

**Comment by TomVanDerSpek** [comment]
Any help would be appreciated

**Comment by TomVanDerSpek** [comment]
Any help would be appreciated

**Comment by jpghelfi** [comment]
Solved! delete the keychain password, and now it works.
