### ISSUE TITLE
pilot documentation update

### ISSUE THREAD

**Issue by Ambersunshine33** [fastlane/fastlane#13057]
Hello,
Just had a long battle of trial and error with distributing tests to users. The goal was to upload the app to company-beta testers only (external). groups: is defined as "Associate tester to one group or more by group name / group", but perhaps you can add "/distribute to a specific group" - to eliminate confusion.

```
pilot(
  ...
  groups: ["Group Name1", "Group Name 2"],
  distribute_external: true,
  ...
)
That seems to work for associating testers as well as distributing to specific groups.
```

**Comment by janpio** [comment]
Are you talking about the 3rd last entry in the params table on https://docs.fastlane.tools/actions/pilot/?
What exactly should it say in your opinion?

The source for that documentation is this file: https://github.com/fastlane/fastlane/blob/da49421a75942411f2f164a8ed4f8f32acd94d46/pilot/lib/pilot/options.rb#L182 You could submit a PR yourself if you want to.
