### ISSUE TITLE
Sigh producing invalid iOS provisioning profile

### ISSUE THREAD

**Issue by igorkulman** [fastlane/fastlane#13067]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[09:30:07]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[09:30:09]: Creating new provisioning profile for 'com.teamwire.messenger' with name 'com.teamwire.messenger AdHoc' for 'ios' platform
[09:30:10]: Downloading provisioning profile...
[09:30:10]: Successfully downloaded provisioning profile...
...
error: exportArchive: Provisioning profile "com.teamwire.messenger.NotificationServiceExtension AdHoc 1533799814" doesn't support the group.com.teamwire.messenger App Group.
</pre>
</details>

### Environment

<details>
  <pre>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.2        |
| xcodeproj                 | 1.5.9        |
| unicode-display_width     | 1.4.0        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| dotenv                    | 2.5.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| curb                      | 0.9.6        |
| badge                     | 0.9.1        |
| fastlane-plugin-badge     | 1.1.0        |
</details>

*generated on:* **2018-08-09**
</details></pre>
</details>

     
     
I have an iOS app with an extension. My build starts with download provisioning profiles

````
  cert
  
  identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  extension_identifier = identifier + ".NotificationServiceExtension"

  sigh(
    adhoc: true,
    app_identifier: identifier
    )

  sigh(
    adhoc: true,
    app_identifier: extension_identifier
    )
````

The problems started when I added an App Group to both the app and the app extension. Since then, every time Fastlane produces new iOS provisioning profiles the build fails with

````
error: exportArchive: Provisioning profile "X.NotificationServiceExtension AdHoc 1533799814" doesn't support the group.X App Group.
````

I need to go to the dev portal where I see the newly created provisioning profile as invalid and recreate it (Edit + Generate).

My guess is that when the new provisioning profiles are produced they are maybe produced without the App Group? 

But the App Group is associated with both the app id and the extension id in the dev portal. Also when creating a new provisioning profile in the dev portal there is no need to do anything to ensure the App Group is included.

I found `fastlane produce associate_group -a com.krausefx.app group.krausefx` but this seems to just associate an app id with an app group and my app ids are already associated with the app group.

**Comment by YuriiTrach** [comment]
Same problem on my side. Fastlane version 2.104.0
Signing script
`def update_signs (adHoc = false)
    cert(team_name: team_name,
      team_id: team_id)
    sigh(app_identifier: app_identifier,
      team_name: team_name,
      team_id: team_id,
      adhoc: adHoc)
    sigh(app_identifier: extension_identifier,
      team_name: team_name,
      team_id: team_id,
      adhoc: adHoc)
  end`
