### ISSUE TITLE
[GYM] Using xcpretty custom formatter expects for a path instead of an executable.

### ISSUE THREAD

**Issue by minuscorp** [fastlane/fastlane#13075]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Setting the  `xcpretty_formatter` to a custom one (i.e. [xcpretty-json-formatter](https://github.com/marcelofabri/xcpretty-json-formatter)) does not pass the argument validation because of:
https://github.com/fastlane/fastlane/blob/b21e4af381b5267fb5d1fff2a07be41c966c95d5/gym/lib/gym/options.rb#L224-L226

**Comment by minuscorp** [comment]
Also, I have noticed the following in the parameter used by `scan` which is supposed to work:
```
/Users/minuscorp/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable xcpretty-json-formatter for gem xcpretty-json-formatter. xcpretty-json-formatter is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```
The gem is in the bundle, in the rbenv and in the system ruby. Indeed `xcpretty-json-formatter` is not an executable, is a `.rb` file which generates the JSON file.

**Comment by gobetti** [comment]
+1
`gym(xcpretty_formatter: "xcpretty-travis-formatter")` outputs "Formatter file not found", whereas `gym(xcpretty_formatter: "/usr/local/bin/xcpretty-travis-formatter")` works fine

**Comment by minuscorp** [comment]
@joshdholtz want me to take it a look into this?

**Comment by minuscorp** [comment]
bump!

**Comment by janpio** [comment]
(Let's give @minuscorp some time dear @fastlane-bot)

**Comment by lucasff** [comment]
bad bot

**Comment by minuscorp** [comment]
If someone is open to open a PR about this It'd be great, as I'm unable to make it right now 😢

**Comment by janpio** [comment]
plonk

**Comment by minuscorp** [comment]
auto-ping

**Comment by joshdholtz** [comment]
Bad bot! Reopening 😊
