### ISSUE TITLE
Cartfile not found in custom directory (using chdir before carthage action)

### ISSUE THREAD

**Issue by v-ivanyshyn** [fastlane/fastlane#13071]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've met error `"The file “Cartfile” couldn’t be opened because there is no such file."` in `carthage` action with specifying custom directory before it with `Dir.chdir`.

In my project I store Carthage files in `[ROOT_DIR]/External/Frameworks/`. So, I use this flow to run `carthage` action:

```
  lane :update_carthage do
    Dir.chdir("../External/Frameworks/") do
      carthage(
        ...
      )
    end
  end
```

It fails with error:
`Failed to read file or folder at /Users/user/Projects/MyProject-ios/External/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file."`. And strange thing here is that the path is broken (`/Frameworks` missed). Actually `Dir.chdir` works correctly, so the problems is with `carthage` action. Looks like a bug in `carthage` action.

##### Complete output when running fastlane, including the stack trace and command used
/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'carthage update --no-use-binaries --no-build --platform iOS' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Failed to read file or folder at /Users/user/Projects/MyProject-ios/External/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/user/Projects/MyProject-ios/External/Cartfile, NSUnderlyingError=0x7fae5ec61200 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/carthage.rb:34:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:105:in `block (3 levels) in parsing_binding'
	from Fastfile:100:in `chdir'
	from Fastfile:100:in `block (2 levels) in parsing_binding'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by nicksl1986** [comment]
Why don't i succeed with updating the carthage ?
I created a cart file, put it in the root directory of my project, but still there's an error, which looks like that : 
Failed to read file or folder at /Users/nickslobodsky/Documents/Swift/Tabbed/Tabbed/Tabbed/Watson/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/nickslobodsky/Documents/Swift/Tabbed/Tabbed/Tabbed/Watson/Cartfile, NSUnderlyingError=0x7f947145ec00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
