### ISSUE TITLE
Docs for setting up android are out of date

### ISSUE THREAD

**Issue by imdadahad** [fastlane/fastlane#13082]
https://docs.fastlane.tools/getting-started/android/setup/ seem out of date.

Specifically the section 'Collect your Google credentials' is no longer accurate as they now seemed to be managed through GCP.

**Comment by janpio** [comment]
Hmm, just tried the process, and it pretty much worked like documented:

- I had to skip "3. Click the Create New Project button".
- In "10. Click Create to close the dialog" the button was nor labeled "SAVE".

What discrepancies are you seeing? Where does it go wrong?

(If you have your Google interfaces in another language, add `&hl=en` to the URL to switch to English)

**Comment by imdadahad** [comment]
Ignore me, I misread the steps in between in creating the service account. I was confused when moving between the Google Play Console and the Google Developer Console. I've just tried again and it works fine 😀

**Comment by janpio** [comment]
Great. 

I took this as an inspiration to improve the instructions a bit:
https://github.com/fastlane/docs/blob/1b7746efd159dbf4d0a01bc3c71b7d85643c42b6/docs/getting-started/android/setup.md#collect-your-google-credentials

PR is https://github.com/fastlane/docs/pull/673
