### ISSUE TITLE
[Feature Request] Expire previous TestFlight builds

### ISSUE THREAD

**Issue by fiznool** [fastlane/fastlane#13080]
### Feature Request

As per #9361, it would be nice to have an option to expire previous builds when submitting a new build to TestFlight.

#### Motivation Behind Feature

Oftentimes, when distributing a new build, you want to ensure that testers don't continue to test an older build. Currently you have to log into iTunes Connect manually to perform this action after TestFlight has submitted the build.

#### Feature Description

Perhaps a new parameter to the `upload_to_testflight` action?

Maybe:

``` rb
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app
    upload_to_testflight(
      expire_previous_builds: true
    )
  end
end
```

#### Alternatives or Workarounds

You have to sign in to iTunes Connect to expire older builds.

I'm not aware of any existing plugins.

**Comment by fiznool** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "xxx.xcodeproj")
    build_app(
      scheme: "xxx",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "xxx" => "xxx"
        }
      }
    )
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxx") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bundler                   | 1.15.4       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.4        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2018-08-10**
</details>

**Comment by fiznool** [comment]
Pretty sure this hasn’t been fixed

**Comment by hawkrives** [comment]
This has not been fixed (it's still a feature request)

**Comment by hawkrives** [comment]
This has not been fixed (it's still a feature request)

**Comment by yanivshaked** [comment]
+1, This is a great idea for a new feature

**Comment by hawkrives** [comment]
This has not been fixed (it's still a feature request)

**Comment by yanivshaked** [comment]
+1 Supporting this feature request

**Comment by hawkrives** [comment]
This has not been fixed (it's still a feature request)

**Comment by max-ott** [comment]
Just checked the `spaceship` code and it definitely should be possible to do add this support directly to `pilot`. (Haven't tried it myself though).

Reference: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/build.rb#L226

**Comment by hawkrives** [comment]
Nope. Still a feature request.

**Comment by hawkrives** [comment]
This remains an unbuilt feature request.

**Comment by hawkrives** [comment]
This remains an unbuilt feature request.

**Comment by tvongeldern** [comment]
Would be such a helpful feature 👏

**Comment by hawkrives** [comment]
This remains an open feature request.

**Comment by hawkrives** [comment]
This remains an open feature request.

**Comment by emreberge** [comment]
+1 on this request

**Comment by yanivshaked** [comment]
This is still a wanted feature request..

**Comment by yanivshaked** [comment]
This remains a required feature...

**Comment by hawkrives** [comment]
This remains an open feature request.

**Comment by richardtop** [comment]
Great feature request, also interested in having support for this.

**Comment by lemonkey** [comment]
FYI I tried writing a helper script for this that leveraged fastlane spacehip and while spacehip does have the capability to expire testflight builds (see https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/build.rb#L223),  currently isn't exposing the necessary internal testflight build ID anymore it looks like with the latest appstoreconnect APIs.

**Comment by richardtop** [comment]
!

**Comment by Steven0351** [comment]
PR #16332 addresses this. Should not be closed until that PR is merged
