### ISSUE TITLE
deliver returned unexpected response

### ISSUE THREAD

**Issue by reshadf** [fastlane/fastlane#13094]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

deliver returned the following error upon releasing:

```
.rvm/gems/ruby-2.4.1/gems/fastlane-2.101.1/spaceship/lib/spaceship/client.rb:602:in `parse_response': [!]  (Spaceship::UnexpectedResponse)
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1></h1>

    <h3>Bad Gateway</h3>
    <p>Correlation Key: OXRDTW3AMHFGBXQ7ITHB6J7I</p>
</div>
</body>
</html>
```

the following did't happen: The build didn't get attached to the release and it wasn't submitted for review. everything did get uploaded fine though.

**Comment by EugeneGoloboyar** [comment]
I have the same issue after several successful submissions today 
(I have multitarget app).
Can it be that this is related to Apple doing smth on their servers?

**Comment by wuftymerguftyguff** [comment]
i have the same issue

**Comment by johanblomgren** [comment]
We're seeing the same issue.

**Comment by StokkurHuni** [comment]
Same issue

**Comment by aastlind** [comment]
https://appstoreconnect.apple.com has been really unreliable today also, probably related?

**Comment by rockneverdies55** [comment]
I'm getting the same error as well.

**Comment by StokkurHuni** [comment]
Just got a build through just this instant.
