### ISSUE TITLE
Action: exportIPA of xcarchive

### ISSUE THREAD

**Issue by mrgrauel** [fastlane/fastlane#1309]
It would be nice to have an exportIPA action. With an output variable `IPA_PATH`

```ruby
exportIPA(
  :xcarchive_path: 'path',
  :output_path: 'path'
)
```

**Comment by lacostej** [comment]
The next gym version will support an option called `skip_build_archive` so you can probably reuse gym for that.

**Comment by vpolouchkine** [comment]
@mrgrauel Did you get a chance to try `skip_build_archive`?
