### ISSUE TITLE
reinstall_app should skip if the app is not installed

### ISSUE THREAD

**Issue by osrl** [fastlane/fastlane#13097]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using screengrab, I use reinstall_app parameter. If the app is not installed, this parameter makes screengrab fail (`ava.lang.IllegalArgumentException: Unknown package: com.foo.bar`). It should skip the uninstall part if the app is not installed.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[00:05:18]: -----------------------------------------
[00:05:18]: --- Step: capture_android_screenshots ---
[00:05:18]: -----------------------------------------
[00:05:18]: Successfully loaded '/Users/osrl/Documents/web_apps/emiliano/fastlane/Screengrabfile' 📄

+----------------------------+--------------------------------------+
|         Detected Values from './fastlane/Screengrabfile'          |
+----------------------------+--------------------------------------+
| app_apk_path               | platforms/android/app/build/outputs  |
|                            | /apk/debug/app-debug.apk             |
| tests_apk_path             | platforms/android/app/build/outputs  |
|                            | /apk/androidTest/debug/app-debug-an  |
|                            | droidTest.apk                        |
| locales                    | ["en-US"]                            |
| reinstall_app              | true                                 |
| clear_previous_screenshots | true                                 |
+----------------------------+--------------------------------------+

[00:05:18]: The `aapt` command could not be found relative to your provided ANDROID_HOME at /Users/osrl/Library/Android/sdk
[00:05:18]: Please ensure that the Android SDK is installed and you have the build tools downloaded

+-----------------------------+--------------------------------------+
|                   Summary for screengrab 2.101.1                   |
+-----------------------------+--------------------------------------+
| tests_package_name          | com.ls.canadadegomezadeo.test        |
| android_home                | /Users/osrl/Library/Android/sdk      |
| locales                     | ["en-US"]                            |
| clear_previous_screenshots  | true                                 |
| output_directory            | fastlane/metadata/android            |
| skip_open_summary           | false                                |
| app_package_name            | com.ls.canadadegomezadeo             |
| test_instrumentation_runner | android.support.test.runner.Android  |
|                             | JUnitRunner                          |
| ending_locale               | en-US                                |
| app_apk_path                | platforms/android/app/build/outputs  |
|                             | /apk/debug/app-debug.apk             |
| tests_apk_path              | platforms/android/app/build/outputs  |
|                             | /apk/androidTest/debug/app-debug-an  |
|                             | droidTest.apk                        |
| device_type                 | phone                                |
| exit_on_test_failure        | true                                 |
| reinstall_app               | true                                 |
+-----------------------------+--------------------------------------+

[00:05:19]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[00:05:19]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[00:05:19]: Clearing phoneScreenshots within fastlane/metadata/android
[00:05:19]: $ /Users/osrl/Library/Android/sdk/platform-tools/adb devices -l
[00:05:19]: ▸ List of devices attached
[00:05:19]: ▸ emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[00:05:19]: $ /Users/osrl/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[00:05:19]: ▸ /sdcard
[00:05:19]: Cleaning screenshots on device
ls: /sdcard/com.ls.canadadegomezadeo/screengrab: No such file or directory
[00:05:19]: Exit status: 1
ls: /data/data/com.ls.canadadegomezadeo/app_screengrab: No such file or directory
[00:05:19]: Exit status: 1
[00:05:19]: The `aapt` command could not be found on your system, so your app APK could not be validated
[00:05:19]: Uninstalling app APK
[00:05:19]: $ /Users/osrl/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.ls.canadadegomezadeo
[00:05:19]: ▸ Exception occurred while executing:
[00:05:19]: ▸ java.lang.IllegalArgumentException: Unknown package: com.ls.canadadegomezadeo
[00:05:19]: ▸ at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
[00:05:19]: ▸ at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21418)
[00:05:19]: ▸ at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18492)
[00:05:19]: ▸ at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
[00:05:19]: ▸ at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
[00:05:19]: ▸ at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
[00:05:19]: ▸ at android.os.ShellCommand.exec(ShellCommand.java:96)
[00:05:19]: ▸ at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21717)
[00:05:19]: ▸ at android.os.Binder.shellCommand(Binder.java:573)
[00:05:19]: ▸ at android.os.Binder.onTransact(Binder.java:473)
[00:05:19]: ▸ at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2644)
[00:05:19]: ▸ at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3485)
[00:05:19]: ▸ at android.os.Binder.execTransact(Binder.java:674)

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.ls.canadadegomezadeo
at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21418)
at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18492)
at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
at android.os.ShellCommand.exec(ShellCommand.java:96)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21717)
at android.os.Binder.shellCommand(Binder.java:573)
at android.os.Binder.onTransact(Binder.java:473)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2644)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3485)
at android.os.Binder.execTransact(Binder.java:674)
[00:05:19]: Exit status: 255
+-----------------------------+--------------------------------------+
|                            Lane Context                            |
+-----------------------------+--------------------------------------+
| PLATFORM_NAME               | android                              |
| LANE_NAME                   | android screens                      |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/osrl/Documents/web_apps/em  |
|                             | iliano/platforms/android/app/build/  |
|                             | outputs/apk/androidTest/debug/app-d  |
|                             | ebug-androidTest.apk",               |
|                             | "/Users/osrl/Documents/web_apps/emi  |
|                             | liano/platforms/android/app/build/o  |
|                             | utputs/apk/debug/app-debug.apk",     |
|                             | "/Users/osrl/Documents/web_apps/emi  |
|                             | liano/platforms/android/CordovaLib/  |
|                             | build/outputs/apk/androidTest/debug  |
|                             | /CordovaLib-debug-androidTest.apk"]  |
| GRADLE_ALL_AAB_OUTPUT_PATHS | []                                   |
| GRADLE_APK_OUTPUT_PATH      | /Users/osrl/Documents/web_apps/emil  |
|                             | iano/platforms/android/app/build/ou  |
|                             | tputs/apk/androidTest/debug/app-deb  |
|                             | ug-androidTest.apk                   |
+-----------------------------+--------------------------------------+
[00:05:19]: Exit status: 255

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | cordova                | 50          |
| 2    | Switch to android      | 0           |
|      | copy_files lane        |             |
| 3    | copy_artifacts         | 0           |
| 4    | copy_artifacts         | 0           |
| 5    | copy_artifacts         | 0           |
| 6    | copy_artifacts         | 0           |
| 7    | gradle                 | 58          |
| 💥   | capture_android_scree  | 1           |
|      | nshots                 |             |
+------+------------------------+-------------+

[00:05:19]: fastlane finished with errors

[!] Exit status: 255</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1408)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV['JAVA_HOME'] = '/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/' 
ENV['ANDROID_HOME'] = '/Users/osrl/Library/Android/sdk'
ENV['CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL'] = 'http://services.gradle.org/distributions/gradle-4.4-all.zip'

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

platform :android do

  desc "Deploy android app on play store"
  lane :deploy do

    cordova(
      platform: 'android',
      # keystore_path: './prod.keystore',
      # keystore_alias: 'prod',
      # keystore_password: 'password'
    )

    # supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
    puts 'apk path:' + ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH']
  end

  private_lane :copy_files do
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)

    original_file = 'files/MainActivityTest.java.original'
    new_file = original_file.sub(".original", "")

    File.open(new_file, 'w') do |fo|
      fo.puts "package #{package_name};"
      File.foreach(original_file) do |li|
        fo.puts li
      end
    end

    copy_artifacts(
      artifacts: 'fastlane/files/local.properties',
      target_path: 'platforms/android'
    )

    copy_artifacts(
      artifacts: 'fastlane/files/build-extras.gradle',
      target_path: 'platforms/android/app'
    )

    copy_artifacts(
      artifacts: 'fastlane/files/AndroidManifest.xml',
      target_path: 'platforms/android/app/src/androidTest'
    )

    package_path = package_name.gsub('.', '/')

    copy_artifacts(
      artifacts: 'fastlane/files/MainActivityTest.java',
      target_path: "platforms/android/app/src/androidTest/java/#{package_path}"
    )
  end

  lane :screens do
    puts ENV['ANDROID_HOME']
    cordova(
      platform: 'android',
      release: false,
      device: false
    )

    copy_files

    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    
    UI.message "Looking for #{package_name} in device"
    packages = sh "adb shell pm list packages #{package_name}"

    # puts packages.length

    # puts packages.match(/#{package_name}$/)

    if packages.match(/#{package_name}$/)
      UI.important "Uninstalling #{package_name}"
      sh "adb uninstall #{package_name}" 
    else 
      UI.message "#{package_name} not found in device, will be installed"
    end

    gradle(
      task: "assembleDebug assembleAndroidTest",
      project_dir: "platforms/android"
    )

    capture_android_screenshots
    # # supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
    # puts 'apk path:' + ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH']
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address

package_name('com.ls.canadadegomezadeo')


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-cordova | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| simctl                    | 1.6.4        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.3        |
| fastlane-plugin-cordova   | 1.0.1        |
</details>

*generated on:* **2018-08-14**
</details></pre>
</details>

**Comment by janpio** [comment]
This used to work before, now doesn't with newer Android versions.

Issue is already tracked at https://github.com/fastlane/fastlane/issues/9825, where there was also a suggestion how to fix it - but nobody created a PR yet.
