### ISSUE TITLE
modify_services ends up with error

### ISSUE THREAD

**Issue by prinstonjim** [fastlane/fastlane#13090]
#10007 
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to set Push notification ON at capabilities using modify_services, that results in weird error
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/modify_services.rb:40:in `attr_accessor': [!] invalid attribute name `' (NameError)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/modify_services.rb:40:in `attr_accessor': [!] invalid attribute name `' (NameError)
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D47)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "20"

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight or store"
  lane :beta do

modify_services(
username:ENV['APPLEID'],
  app_identifier: ENV['BUNDLE_ID'],
  team_id: ENV['TEAMID'],
  services:{
  push_notification: 'on'
  }
)
#comment: Get/create certificate.
# get_certificates(
#   team_id: ENV['TEAMID'],
#   username: ENV['APPLEID']
# )

#comment:Code To sign automatically.  
  automatic_code_signing(
  path: "./mystudio.xcodeproj",
  use_automatic_signing: true,
  team_id: ENV['TEAMID'],
  targets: ENV['SCHEME'],
  bundle_identifier: ENV['BUNDLE_ID'],
)

#comment:GYM command builds the app.
# gym({
#         workspace: ENV['WORKSPACE'],
# #       configuration: ENV['CONFIG'],
#         scheme: ENV['SCHEME'],
# 		xcargs: "-allowProvisioningUpdates",
# 		export_method: "app-store",
# 		export_team_id: ENV['TEAMID'],
# 		silent: true,
# 		clean: true
#       })
      
#comment:Upload app to testflight - beta testing.
     # upload_to_testflight(
#      dev_portal_team_id:ENV['TEAMID'],
#      team_id:ENV['ITCTEAMID'],
#      app_identifier:ENV['BUNDLE_ID'],
#      skip_waiting_for_build_processing: true,
#      skip_submission: true)
     
#comment:To submit app to store
# upload_to_app_store(
# 		dev_portal_team_id:ENV['TEAMID'],
#      	team_id:ENV['ITCTEAMID'],
#       app_identifier:ENV['BUNDLE_ID'],
#       skip_metadata: false,
#       skip_screenshots: true,
#       force: true,
#       submit_for_review: true,
#       automatic_release: true,
#       run_precheck_before_submit: false,
#       release_notes: {'default' => "New functionalities added.", 'en-US' => "New functionalities added to management system." }      
#       )
   end

desc "Add device only for new account"
lane :adddevice do 
register_devices(devices: {
    "** Mac C04s iPhone" => "4BF51A4A60EB85D848AF7********"
  })
end

desc "Update version number & build number of all apps"
lane :incversion do  
increment_version_number(
  version_number: "1.10.0" # Set a specific version number
)
 increment_build_number(
  build_number: "2" 
)
end
  
  
  
  # env for Mystudio account
  
  
   desc "Deploy all env to"
lane :deploy_all do
  begin
sh "fastlane beta --env mys*****"
rescue => ex
   UI.error("TGS error handled: #{ex}!")
 end
  begin
sh "fastlane beta --env blue******"
rescue => ex
   UI.error("TGS error handled: #{ex}!")
 end
  


end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV['BUNDLE_ID']) # The bundle identifier of your app
# apple_id("****@gmail.com") # Your Apple email address
# 
# itc_team_id("***") # iTunes Connect Team ID
# team_id("****") # Developer Portal Team ID

apple_id(ENV['APPLEID']) # Your Apple email address

itc_team_id(ENV['ITCTEAMID']) # iTunes Connect Team ID
team_id(ENV['TEAMID']) # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-08-11**
</details>
</pre>
</details>

**Comment by prinstonjim** [comment]
Error still exists. Any update on this?

**Comment by johnknapprs** [comment]
The `modify_services` action is essentially a shortcut to some Produce features.   Recent updates to Produce included 2 new service targets `wallet` and `private_vpn`.  

It appears that `modify_services` was not updated to include these new services so it's crashing when you try to use it. 

I've opened a PR to add those services in and get it working again.  Hopefully it'll get approved and rollout soon. : ) 

https://github.com/fastlane/fastlane/pull/13415
