### ISSUE TITLE
Is there a way to setup snapshot from a lane or shell command

### ISSUE THREAD

**Issue by osrl** [fastlane/fastlane#13101]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I need to setup snapshot every time for clone cordova apps. Is there a way to setup snapshot from a lane (or shell command)?

#### Question Description

I've successfully setup screengrab for android from a lane. Copy some files to androidTest folder, copy an extra build.gradle file and bingo. I need to do the same for snapshot but I'm not sure if there is a way to add UI Test target, or Add the SnapshotHelper.swift to that UI Test target, or Add a new Xcode scheme for the newly created UITest target.

**Comment by janpio** [comment]
This might help with both iOS and Android:
https://github.com/ionic-zone/fastlane-plugin-cordova_screenshots

(Can you share what exactly you did for Andorid via an issue on that repository? I would really be interested to see if you did manually what the plugin is doing right now)

**Comment by osrl** [comment]
> I don't have the local.properties, what do you use it for?

It's content shows the the Android sdk path => `sdk.dir=/Users/osrl/Library/Android/sdk` It's needed by gradle. How do you set sdk path?

> I also don't have an AppManifest.xml in /app/src/androidTest I think.

It was related to #12770

**Comment by janpio** [comment]
>> I don't have the local.properties, what do you use it for?
> 
> It's content shows the the Android sdk path => sdk.dir=/Users/osrl/Library/Android/sdk It's needed by gradle. How do you set sdk path?

Oh, you are right. I do have that file, but Cordova/Android Studio created that by themselves. I should probably check if that is a thing that has to be created manually in some cases.

>> I also don't have an AppManifest.xml in /app/src/androidTest I think.
>
> It was related to #12770

Interesting, works for me without them as the test apk gets it via `androidTest`.

**Comment by osrl** [comment]
> > > I also don't have an AppManifest.xml in /app/src/androidTest I think.
> > 
> > It was related to #12770 
> 
> Interesting, works for me without them as the test apk gets it via androidTest.

Maybe I did something wrong.

By the way, it's not related but, do you know a better way of writing ui tests for iOS besides that clicking coordinates? Clicking `div`'s without text is impossible in cordova. The app's accessibility is bad and I couldn't find a better way.

**Comment by janpio** [comment]
Nope, that's actually where I stalled with the plugin as well - otherwise there would be a writeup on it on ionic.zone/fastlane already. But writing those tests is hard. Will have to dedicate a day or two only for this problem soon to find some solution that works reliably (or at least more so) :/
