### ISSUE TITLE
Importing Appfile / Matchfile from file/git

### ISSUE THREAD

**Issue by MrLotU** [fastlane/fastlane#13100]
### Feature Request
Importing Appfile / Matchfile from file/git

#### Motivation Behind Feature
I recently discovered the `import_from_git` action for Fastfiles which allows you to import a Fastfile from github. This is great because it allows you to store all your Fastlane logic in one place if you have shared logic. If you're also using a shared Appfile / Matchfile however, you still need to have those files in 2 places.

#### Feature Description
Add an action to put in the Fastfile that can load said files from a local path or a git URL to avoid having to duplicate these files.

As far as I can see this will not have any drawbacks or consequences for any current Fastlane setup.

##### Example:
Having this implemented, you could create a setup like this without having to have an Appfile along with this Fastfile
Fastfile: 
```ruby
import_from_git(url: "https://github.com/username/fastlaneRepo")
import_appfile_from_git(url: "https://github.com/username/fastlaneRepo")
```

#### Alternatives or Workarounds
Currently I have duplicate Appfiles and Matchfiles both in my repo where I import the Fastfile from and in the repo where I import my Fastfile to. This works but IMO it's never a good thing to have duplicate files.

I did some googling around and couldn't find anything else related to this.

**Comment by janpio** [comment]
From my understanding of how fastlane works, this might not be as easy as it seems. 
Configuration files are also used when calling the command line tools of fastlane like `fastlane supply init` or `fastlane deliver` - there the `Fastfile` is not involved at all, which means there is no way to call this action (or a lane using it). This might lead to confusion for users.

**Comment by MrLotU** [comment]
Hi, I didn't think of those since I never used the command line tools. But IMO this wouldn't stand in the way of being able to load the data from the Appfile/Matchfile from an external location. Especially for setups where usage of the commandline tools are not required.

**Comment by MrLotU** [comment]
Don't know how this works with feature requests, but haven't heard anything about this getting implemented so I guess it should stay open?

**Comment by awgeorge** [comment]
I need this too - in fact I would extend it to the `metadata` folder as well. Perhaps to maintain backwards compatibility and keep @janpio happy, we could have a new `includes` key. Which takes and array of file/folder paths?

**Comment by awgeorge** [comment]
After reading the source code - it would similar just allowing `path` to be a folder, currently it defaults to `fastlane/Fastfile` but if we were allowed to pass just `fastlane/` this would be the most logical. It will also be backwards compatible - just need to modify the import function to allow folders: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/fast_file.rb#L275

**Comment by awgeorge** [comment]
At a very minimum Pluginfile needs to be copied across.

**Comment by janpio** [comment]
So a new `import_configuration` that allows you to import a folder that can contain `Fastfile`, `Appfile` etc?

**Comment by MrLotU** [comment]
Something along those lines, yeah, but preferably a way that also allows you to import that folder from git/online
