### ISSUE TITLE
Add create private app Play Store listing for Android to supply

### ISSUE THREAD

**Issue by jmarkoff** [fastlane/fastlane#13122]
Previous bug, we were not able to figure out the correct APIs to call. I have built sample code (see below) to do this. https://github.com/fastlane/fastlane/issues/12655 for reference.

### Feature Request
Add create private app option to the supply action to facilitate creating Play Store listings for Managed Play.

I work with large enterprises that have to migrate apps to Managed Google Play. Some of these enterprises have 100+ internal applications and this process is quite painful to do this manually. I would love to steer them towards fastlane.

#### Motivation Behind Feature
Adding "create private play store listings" would be extremely helpful for developers with large amounts of applications for Managed Google Play (formally Play for Work). 

It also helps automate cross platform. This feature exists for iOS and it's holding back enterprises I work with on adopting the other great features of fastlane/supply. This would be a significant enhancement so fastlane can be used for the whole automation flow.

#### Feature Description
Add feature similar to create from the produce (https://docs.fastlane.tools/actions/produce/) action.

There is a one time call that needs top made to Managed Play to enable private apps which returns a developer account identifier. It's OK if that needs to be done outside of fastlane, although would be cool if it could help. :)

`fastlane supply enable_private_apps`

Guide here: https://developers.google.com/android/work/play/custom-app-api/get-started
I have an account you can use for testing if that helps and can explain this part if needed.

Implementation:

Make sure to create an IAM role in the Google Cloud console for your enterprise and insert that into the **service_account** query param below.

Example OAuth call: 
https://play.google.com/apps/publish/delegatePrivateApp?service_account=ACCOUNT@PROJECT-ID.iam.gserviceaccount.com&continueUrl=https://foo.bar/oauthredirectfastlane

The returning call will contain a developerAccount string that is a number to denote your account. You will need this to create private apps in the API.

`fastlane supply create_private`

Options for create: (Some ideas but not limited to)
-l, --language_code STRING Title (e.g. for example, "en_us for English", "de-AT" for Austrian German) (SUPPLY_LANGUAGE_CODE)
-t, --title STRING Title (SUPPLY_TITLE)
-d, --developerAccount STRING Title (SUPPLY_DEVELOPER_ACCOUNT) The developer account identifier returned from enabling private apps. 
-v, --apk STRING APK Path (SUPPLY_APK) This should be a release build with V1 and V2 signatures for release.

Found a listing of supported keys under class Listing here.

This will not break any functionality. There are also no drawbacks.

#### Alternatives or Workarounds
The workaround is to use the Play REST API directly which is pretty rough for one missing feature.

Example code in Ruby to do this:

```
require "google/apis/playcustomapp_v1"

# Auth Info
KEYFILE = 'KEYFILE_FROM_SERVICEACCOUNT.json' # PATH TO JSON KEYFILE
DEVELOPER_ACCOUNT = "DEV ACCOUNT ID FROM ONE TIME OAUTH" # DEVELOPER ACCOUNT ID

# App Info
APK_PATH = "app-release.apk" # PATH TO SIGNED APK WITH V1+V2 SIGNATURES
APP_TITLE = "APP TITLE FOR"
LANGUAGE_CODE = "EN_US"

scope='https://www.googleapis.com/auth/androidpublisher'
credentials = JSON.parse(File.open(KEYFILE, 'rb').read)
authorization = Signet::OAuth2::Client.new(
    :token_credential_uri => 'https://oauth2.googleapis.com/token',
    :audience => 'https://oauth2.googleapis.com/token',
    :scope => scope,
    :issuer => credentials['client_id'],
    :signing_key => OpenSSL::PKey::RSA.new(credentials['private_key'], nil),
)
authorization.fetch_access_token!
custom_app = Google::Apis::PlaycustomappV1::CustomApp.new title: APP_TITLE, language_code: LANGUAGE_CODE
play_custom_apps = Google::Apis::PlaycustomappV1::PlaycustomappService.new
play_custom_apps.authorization = authorization

returned = play_custom_apps.create_account_custom_app(
  DEVELOPER_ACCOUNT,
  custom_app,
  upload_source: APK_PATH,
) do |created_app, error|
  unless error.nil?
    puts "Error: #{error}"
  else
    puts "Success: #{created_app}."
  end
end

```

**Comment by janpio** [comment]
Did I understand correctly that this issue contains 2 separate feature requests:

1. Enable private apps (via "Managed Google Play")
2. Create Android apps in Google Play Console

If so, could you please split one of both out into its own issue and make sure both issues only contain the relevant information?

Adding an Android equivalent to `produce` would be really nice for _fastlane_, I'm looking forward to have a look at your code again when the issue is clearly defined (tbh right now it is to confusing for me).

**Comment by jmarkoff** [comment]
Thanks for the response. In order to add private app creation to managed play, you need to enable it. This is really one feature request that has potentially 2 command line options, but this could be separated into one.

@joshdholtz and I worked together on the original version of this issue but we had no luck on which API to use. @joshdholtz Does this help? Do you need more information? :)

The original feature request is here. #12655

**Comment by janpio** [comment]
Ok, so this `produce`-like action you suggest will only work for private apps, not for _normal_ Google Play Console apps?

**Comment by jmarkoff** [comment]
Yes for private apps.

**Comment by janpio** [comment]
Ok, now I understood the scope.

New additions to fastlane tend to _always_ have a standalone action, next to their eventual command line implementation via one of the tools (`supply` in this case`) Some input on the action name: As `produce` is also available as an action `create_app_online` and `supply` has an action `upload_to_play_store`, one could combine those naming patterns to `create_app_on_managed_play_store` (mouthful, but exact).

**Comment by jmarkoff** [comment]
Makes sense, thanks for the clarification.

**Comment by jmarkoff** [comment]
@joshdholtz - Is this something you could implement? I can support the effort and make sure you have what you need to get it done.

CC: @taquitos

**Comment by janpio** [comment]
I could take a shot at it, but as a plugin - not an addition to `supply`. 
Does the code sample you posted above work? Was it used successfully?

Some notes for my later self:
https://developers.google.com/android/work/play/custom-app-api/publish
https://developers.google.com/api-client-library/ruby/apis/playcustomapp/v1
https://github.com/fastlane/fastlane/blob/4f73da3f0e217deeacfba2c3f4d1192ed680a62d/supply/lib/supply/client.rb
https://docs.fastlane.tools/actions/supply/#parameters

**Comment by jmarkoff** [comment]
Sure that works, that would be much appreciated!

**Comment by janpio** [comment]
This is now available as a plugin at https://github.com/janpio/fastlane-plugin-managed_google_play
