### ISSUE TITLE
Uploading metadata to iTunes Connect error: source sequence is illegal/malformed utf-8 

### ISSUE THREAD

**Issue by SEnglishSMP** [fastlane/fastlane#13125]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm getting an error while running `fastlane deliver`

    /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/base.rb:66:in to_json': [!] source sequence is illegal/malformed utf-8 (JSON::GeneratorError)

This was reported before in #11961, but that issue was auto-closed for inactivity, apparently never being fixed.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[00:57:16]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[00:57:17]: Sending anonymous analytics information
[00:57:17]: Learn more at https://docs.fastlane.tools/#metrics
[00:57:17]: No personal or sensitive data is sent.
[00:57:17]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[00:57:17]: Login to App Store Connect (***)
[00:57:22]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.101.1 Summary                           |
+--------------------------------------+--------------------------------------+
| force                                | true                                 |
| username                             | ***                    |
| app_identifier                       | x                  |
| ipa                                  | x                  |
| skip_binary_upload                   | true                                 |
| metadata_path                        | /Users/vsts/agent/2.136.1/work/r1/a  |
|                                      | /_iOS                                |
|                                      | release/drop/AppStore/metadata       |
| skip_screenshots                     | true                                 |
| submit_for_review                    | true                                 |
| screenshots_path                     | ./screenshots                        |
| app_version                          | x                            |
| edit_live                            | false                                |
| platform                             | ios                                  |
| use_live_version                     | false                                |
| skip_metadata                        | false                                |
| skip_app_version_update              | false                                |
| reject_if_possible                   | false                                |
| automatic_release                    | false                                |
| phased_release                       | false                                |
| overwrite_screenshots                | false                                |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+

[00:57:23]: Making sure the latest version on App Store Connect matches 'x' from the ipa file...
[00:57:27]: Successfully set the version to 'x'
[00:57:27]: Loading '/Users/vsts/agent/2.136.1/work/r1/a/_iOS release/drop/AppStore/metadata/en-US/description.txt'...
[00:57:27]: Loading '/Users/vsts/agent/2.136.1/work/r1/a/_iOS release/drop/AppStore/metadata/en-US/release_notes.txt'...
[00:57:27]: Loading '/Users/vsts/agent/2.136.1/work/r1/a/_iOS release/drop/AppStore/metadata/en-US/support_url.txt'...
[00:57:27]: Loading '/Users/vsts/agent/2.136.1/work/r1/a/_iOS release/drop/AppStore/metadata/copyright.txt'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Uploading metadata to iTunes Connect error: source sequence is illegal/malformed utf-8
    https://github.com/fastlane/fastlane/issues/11961 [closed] 3 💬
    08 Jun 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/base.rb:66:in `to_json': [!] source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/base.rb:66:in `to_json'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/tunes/tunes_client.rb:421:in `block (2 levels) in update_app_version!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:384:in `block in run_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:398:in `block in build_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request.rb:26:in `block in create'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `tap'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `create'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:394:in `build_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:379:in `run_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/client.rb:694:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/client.rb:529:in `with_retry'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/client.rb:693:in `send_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/client.rb:581:in `request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/tunes/tunes_client.rb:419:in `block in update_app_version!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1422:in `with_tunes_retry'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/tunes/tunes_client.rb:418:in `update_app_version!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/spaceship/lib/spaceship/tunes/app_version.rb:403:in `save!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/deliver/lib/deliver/upload_metadata.rb:130:in `upload'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/deliver/lib/deliver/runner.rb:120:in `upload_metadata'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/deliver/lib/deliver/runner.rb:38:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

We're using a Visual Studio Team Services hosted build server.  I can't run `fastlane env`, but this is what Microsoft says is installed on the current machine image.

<details>
  <pre>
-- Installation software information ---------

ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Python 2.7.10
Python 3.7.0
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
Node.js v6.14.3
NPM 3.10.10
Git: git version 2.18.0
Git LFS: git-lfs/2.5.1 (GitHub; darwin amd64; go 1.10.3)
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
GNU Wget 1.19.5 built on darwin17.5.0.
Homebrew 1.7.1
xctool 0.3.4
Bundler version 1.16.1
CocoaPods 1.5.3
xcpretty 0.2.8
Nomad CLI 2.7.6
Nomad CLI ipa 0.14.3
Mobile Center CLI 0.12.0
App Center CLI 1.1.1
fastlane 2.101.1
Carthage 0.30.1
Gradle 4.9
PowerShell v6.0.3
Yarn 1.9.4
java 1.7 jdk: 1.7.0_80
java 1.8 jdk: 1.8.0_181 (default)
java 9 jdk: 9.0.4
java 10 jdk: 10.0.2
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
.NET SDK 1.0.1 1.0.4 1.1.10 1.1.4 1.1.5 1.1.7 1.1.8 1.1.9 2.0.0 2.0.3 2.1.100 2.1.101 2.1.102 2.1.103 2.1.104 2.1.105 2.1.2 2.1.200 2.1.201 2.1.202 2.1.300 2.1.301 2.1.302 2.1.4
azure-cli (2.0.43)
Go 1.10.3
Subversion (SVN) 1.10.2
Miniconda 4.5.4
macOS toolcache Python 2.7.15 3.4.8 3.5.5 3.6.5 3.7.0

-- OS X info ----------------------------------

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77

system_profiler SPSoftwareDataType
Software:

System Software Overview:

System Version: macOS 10.13.5 (17F77)
Kernel Version: Darwin 17.6.0
Boot Volume: Macintosh HD
Boot Mode: Normal
Computer Name: Mac (136)
User Name: vsts (vsts)
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled
Time since boot: 2:15

-- Disk ---------------------------------------

Total size: 321262788608 bytes (299Gi)
Free: 44808802304 bytes (42Gi)

</pre>
</details>

**Comment by joshdholtz** [comment]
@SEnglishSMP Heyyy 👋 It looks like this bad JSON is failing in the `update_app_version` method. Can you try setting `skip_app_version_update: true` just to see if things start working for you? I'm curious if the error that you are seeing is just happening in that method or happening somewhere else too.

**Comment by SEnglishSMP** [comment]
This is still an issue and shouldn't have been closed.  I don't know why you have a bot that closes issues just because you haven't fixed them quickly.

**Comment by postmechanical** [comment]
@joshdholtz Just ran into this issue after _stupidly_ updating to latest `fastlane` version `2.109.0` and your suggestion [here](url
https://github.com/fastlane/fastlane/issues/13125#issuecomment-413504759) does not work.

**Comment by janpio** [comment]
See here @postmechanical: https://github.com/fastlane/fastlane/issues/13815
