### ISSUE TITLE
gym fails with error: You can only pass either a workspace or a project path, not both

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#1313]
I'm running version 1.57.0.
It didn't show me this before. Started today.

INFO [2016-02-13 08:13:51.65]: -----------------
INFO [2016-02-13 08:13:51.65]: --- Step: gym ---
INFO [2016-02-13 08:13:51.65]: -----------------
FATAL [2016-02-13 08:13:51.68]: Error resolving conflict between options: 'workspace' and 'project'
INFO [2016-02-13 08:13:51.68]: Moving to Error lane

Update using 'sudo gem update fastlane'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/ui/interface.rb:132:in `user_error!': [!] You can only pass either a 'workspace' or a 'project', not both (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.0/lib/gym/options.rb:27:in `block in plain_options'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:98:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:98:in `block (2 levels) in verify_conflicts'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:92:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:92:in `block in verify_conflicts'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:83:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:83:in `verify_conflicts'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/configuration/configuration.rb:147:in `load_configuration_file'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.0/lib/gym/detect_values.rb:19:in `block in set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.0/lib/gym/detect_values.rb:18:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.0/lib/gym/detect_values.rb:18:in `set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.0/lib/gym.rb:25:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.0/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:40:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure

This is my lane:
desc "Submit a new TEST Build to Hockeyapp"
  lane :test_hockeyapp do |options|
  	sh "./test_script.sh" # Upgrade build version

	# Build app
    gym(scheme: "PingID Test Enterprise", 
    	clean: true, 
    	configuration: "Adhoc", 
    	use_legacy_build_api: false, 
    	export_method: "enterprise",
    ) 
.......

**Comment by nmayafit** [comment]
Sorry, this is my bash:
fastlane --verbose test_hockeyapp username:'Jenkins'

**Comment by nmayafit** [comment]
Just added 'project: ..." to the gym conf. Resolved the issue.
Is that mandatory now? never used it before.

**Comment by vpolouchkine** [comment]
The latest version of `gym` (0.36.5) improves the detection of project / workspace.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
