### ISSUE TITLE
Can't upload to Crashlytics after match nuke

### ISSUE THREAD

**Issue by tomcalmon** [fastlane/fastlane#13145]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Today I needed to renew my development cert and since then I cannot upload my build to Crashlytics.

Lane that I'm using for upload to **Crashlytics**:

```
match(
    type: 'development',
    app_identifier: 'com.**********',
    force_for_new_devices: true
    )

gym(
    scheme: 'MyApp',
    configuration: 'Homolog',
    export_method: 'development',
    output_directory: './Build/Beta/',
    export_options: { compileBitcode: false }
    )

changelog = last_git_commit[:message]

crashlytics(
    api_token: '...',
    build_secret: '...',
    ipa_path: './Build/Beta/MyApp.ipa',
    groups: ['ios-tester-team'],
    notes: changelog,
    notifications: true
    )
```

After match and gym with success, Fastlane starts upload build:

> Uploading the build to Crashlytics Beta. Time for some ☕️.

It took less than few seconds, throwing the exception listed below:

```
Shell command exited with exit status 1 instead of 0.
WARN [2018-08-17 00:39:41.02]: Lane Context:
INFO [2018-08-17 00:39:41.02]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios distribute_beta", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>"232", :SIGH_PROFILE_TYPE=>"development", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"com..***************"=>"match Development com.***************", "com..***************.ShareExtension"=>"match Development com..***************.ShareExtension"}, :IPA_OUTPUT_PATH=>"/Users/thomas/Dev/myapp.app.ios/Build/Beta/MyApp HML.ipa", :DSYM_OUTPUT_PATH=>"/Users/thomas/Dev/myapp.app.ios/Build/Beta/MyApp HML.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/thomas/Library/Developer/Xcode/Archives/2018-08-17/MyApp HML 2018-08-17 00.34.38.xcarchive"}
ERROR [2018-08-17 00:39:41.02]: 2018-08-17 00:39:37.419 submit Crashlytics: Crashlytics.framework/submit 1.3.6 (19)
2018-08-17 00:39:40.841 submit Crashlytics: Unable to package source due to error: Error Domain=CLSIPABuilderErrorDomain Code=-6 "(null)" UserInfo={UnderlyingError=Error Domain=CLSCodeSignerErrorDomain Code=-2 "(null)" UserInfo={arguments=(
    "--sign",
    3322148EB806016230BF7F5578952651E65EDA7D,
    "--all-architectures",
    "--force",
    "--entitlements",
    "/var/folders/d1/sy63prmx3f98lpwjhjpzd6bw0000gp/T/com.crashlytics.ipas/30DFB6EC-9CF5-4F8C-809A-9265309B16E2/Payload/entitlements.xml",
    "/var/folders/d1/sy63prmx3f98lpwjhjpzd6bw0000gp/T/com.crashlytics.ipas/30DFB6EC-9CF5-4F8C-809A-9265309B16E2/Payload/MyApp.app"
), environment={
    "CODESIGN_ALLOCATE" = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate";
}, status=1, stderr=3322148EB806016230BF7F5578952651E65EDA7D: no identity found
, command=/usr/bin/codesign, stdout=}, SourcePath=/var/folders/d1/sy63prmx3f98lpwjhjpzd6bw0000gp/T/com.crashlytics.ipas/30DFB6EC-9CF5-4F8C-809A-9265309B16E2}
2018-08-17 00:39:41.017 submit Crashlytics: Failed to prepare the binary for release
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.14.0       |
| openssl                   | 2.1.0        |
| json                      | 2.1.0        |
| highline                  | 1.7.10       |
| excon                     | 0.61.0       |
| CFPropertyList            | 3.0.0        |
| plist                     | 3.4.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| fastimage                 | 2.1.1        |
</details>

*generated on:* **2018-08-17**
</details>

**Comment by marksiu** [comment]
Hi, can you upload the build to Crashlytics successfully by clicking the Archive in Xcode?

**Comment by marksiu** [comment]
Hi, 
the reason MAY relate to some cache issue of Xcode setting. 
I used to face some similar issue and I follow the following guideline to fix that. 
Hope it can help.

If possible, I suggest you 
1. update your crashlytic to the latest version
2. check the `certificate` and `provisioning profile` in the Apple developer account, make sure the provisioning profile is using the latest and correct certificates, it should have `match Development xxx` and `match adhoc xxx`, etc provisioning profile created by `Match`
3. delete your LOCAL `certificates` and `provisioning profile` 
❗❗**make sure you have the certicates and privacy key in your Match repo before you delete, otherwise, you need to re-create the certificates and provisioning profile** ❗❗
4. run `Fastlane match` to get the `certificates` and `provisioning profile` from your match repo
5. check the project are using correct provisioning profile in project setting page (e.g. Debug is using `match Development xxx`, Release is using `match adhoc xxx` or `match appstore xxx`)
6. clean and build the app
7. archive the project
8. use Fabric to upload the ipa to Crashlytics
9. re-run your script

**Comment by tomcalmon** [comment]
I just did all the steps you suggested me and It **didn't work**. Same problem!

**Comment by marksiu** [comment]
Hi, 
I did some research about the error code -6 and -2. (please refer to this post,[https://stackoverflow.com/questions/40754779/crashlytics-unable-to-package-source-due-to-error](url))
It seems the problem is about the signing issue. I can only think it may relate to the version of Fastlane, or you can send the log to crashlytics directly to see can they help the problem (please refer to this post, https://github.com/fastlane/fastlane/issues/11668)

**Comment by tomcalmon** [comment]
Ok! I just sent an email to Crashlytics support.

Thank you!

**Comment by tomcalmon** [comment]
I sent an email to Crashlytics support and they told me the problem could be my certificates or fastlane's configuration. As I can upload the build archived by Fastlane using the Fabric app, I suppose It's not a problem with my certificates, right?

I don't know where codesign _3322148EB806016230BF7F5578952651E65EDA7D_ is coming from, since I have only two identities locally, the same ones there are in the Apple Development Portal.

```
$ security find-identity -p codesigning

Policy: Code Signing
  Matching identities
  1) 2C1C409EB6AFB04BBB3A9817FCD78CB6EAFB0E21 "iPhone Developer: ... (...)"
  2) CFF9644BD99A577B803506A429EDA81B9B84FC39 "iPhone Distribution: ... (...)"
     2 identities found

  Valid identities only
  1) 2C1C409EB6AFB04BBB3A9817FCD78CB6EAFB0E21 "iPhone Developer: ... (...)"
  2) CFF9644BD99A577B803506A429EDA81B9B84FC39 "iPhone Distribution: ... (...)"
     2 valid identities found
```

**Comment by tomcalmon** [comment]
Do you have some clue why Fastlane is using cached identity? The identity _3322148EB806016230BF7F5578952651E65EDA7D_ isn't setted to any of my provisioning profiles. 

I've already tried to clean every cache I have in Xcode, reinstalled Fastalne and Fabric app, and It still doesn't work. 😢

**Comment by marksiu** [comment]
@tomcalmon happy to hear that 😄
