### ISSUE TITLE
Pilot test information not saving

### ISSUE THREAD

**Issue by julianoterres** [fastlane/fastlane#13151]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The pilot not have option to save the field below, in the test information tab.

- Information for the beta app evaluation team
First Name
Last Name
Number Phone
Email
Notes
License Agreement

You can add this options to that save this options in ITC?

**Comment by julianoterres** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.18.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.2       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| signet                    | 0.8.1        |
| googleauth                | 0.6.4        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| unicode-display_width     | 1.4.0        |
</details>


*generated on:* **2018-08-17**

**Comment by janpio** [comment]
Is this information required before submitting the app?
Was this data recently added or has this always been there?

**Comment by julianoterres** [comment]
Yes, these information are necessary, to could send the app to testflight and send the app to external testers.

If these informations not are saved before send app to testflight, the fastlane return a error, with a message that is necessary add these information in testflight.

Currently I need enter in testflithg and add these informations manually before of run the command upload_to_testflight.

Because this, I need that exist options in the action upload_to_testflight to save this before upload app to testflitgh.

**Comment by julianoterres** [comment]
@janpio Do you have some prevision that this be implemented?

**Comment by janpio** [comment]
It totally makes sense to be able to set this data - we just have "find" someone to jump into the code and implement it. I don't know enough both about `pilot` and especially those APIs to define if this is a small or major undertaking.

We could start by "designing" the implementation though:
1. Which action do you think should use this data?
2. Any suggestion on how to supply this data to this action? Param name, data structure etc.

**Comment by julianoterres** [comment]
@janpio I think the action should introduced in the pilot method, and use files txt to save the information that should be send.

**Comment by janpio** [comment]
Could you please take a screenshot of the form and post it here?

> and use files txt to save the information that should be send.

`pilot`/`upload_to_testflight` doesn't use any files for metadata (yet), so we would probably want to add this as action parameters first. 

(This is because historically Testflight didn't have any metadata or only very little, so it didn't make sense to version this on the file system. With all that new input, that might be worth changing. First step is still to add the parameters I think)

**Comment by julianoterres** [comment]
Hello @janpio 

Follow the screenshots in attachment.

![screen shot 2018-09-10 at 13 37 14](https://user-images.githubusercontent.com/6574949/45311620-10209b80-b500-11e8-939e-677acf8f9c7a.png)
![screen shot 2018-09-10 at 13 37 17](https://user-images.githubusercontent.com/6574949/45311621-10b93200-b500-11e8-9907-c72bf3f8f0b6.png)

These are the fields that we need add in pilot action.

**Comment by julianoterres** [comment]
This issue still continue exist

**Comment by jaimeohm** [comment]
+1 I'm interested in seeing this change, too. This affects first-time release to external beta testers for all apps. First-time release, the only solution I've found is to fill out this form manually. Here's the command I use in the lane, I pretty much use all the variables:

    pilot(
      app_identifier: metadata["SKU"],
      app_platform: metadata["PLATFORM"],
      beta_app_description: metadata["BETA_APP_DESCRIPTION"],
      beta_app_feedback_email: metadata["BETA_APP_FEEDBACK_EMAIL"],
      email: metadata["BETA_APP_FEEDBACK_EMAIL"],
      first_name:"Jaime",
      last_name:"Ohm",
      changelog: metadata["RELEASE_NOTES"],
      demo_account_required: true,
      dev_portal_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      distribute_external: metadata["DISTRIBUTE_EXTERNAL"],
      notify_external_testers: metadata["DISTRIBUTE_EXTERNAL"],
      reject_build_waiting_for_review: true,
      skip_submission: metadata["SKIP_SUBMISSION"],
      skip_waiting_for_build_processing: metadata["SKIP_WAITING_FOR_BUILD_PROCESSING"],
      team_id: metadata["ITC_TEAM_ID"],
      team_name: metadata["ITC_TEAM_NAME"],
      # testers_file_path: metadata["TESTERS_FILE_PATH"],
      groups: metadata["GROUPS"],
      username: metadata["USERNAME"],
      wait_for_uploaded_build: !metadata["SKIP_WAITING_FOR_BUILD_PROCESSING"]
    )

**Comment by jaimeohm** [comment]
@julianoterres It looks like spaceship may expose directly the options we need. https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md

**Comment by janpio** [comment]
Nah @fastlane-bot, that is definitely something that should be implemented to make usage more comfortable.
