### ISSUE TITLE
Add test_target_name parameter to run_tests action

### ISSUE THREAD

**Issue by mirkokg** [fastlane/fastlane#13157]
### Feature Request
Add test_target_name parameter to run_tests action (scan), same way it was implemented in snapshot. Needed when you want to run test against different targets.

**Comment by janpio** [comment]
> Needed when you want to run test against different targets.

If know these words, but what does it actually mean? What is the use case? (Just so I understand)

**Comment by mirkokg** [comment]
We have a project with many targets that use different data set so we need to run tests against specific target application. Snapshot has parameter test_target_name which can be used to run UI Test to take snapshots of the specific target, but there is no such option with scan.

**Comment by janpio** [comment]
Got it. Might you be up to create a pull request for this yourself?

Code is here:
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/options.rb
https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/test_command_generator_base.rb#L38
https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/test_command_generator.rb
