### ISSUE TITLE
Match ceretificates validity monitoring

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#13169]
#### Motivation Behind Feature
It would be nice to run such a thing daily to see if expiration is coming or smth was revoked.
Kind of health check for all the signing certs and profiles.

#### Feature Description
fastlane match check
- bundle_id1 devel: Ok (green, more than 30 days till expiration)
- bundle_id1 enterprise: Warning (yellow, less than 30 days till expiration)
- bundle_id2 devel:  Issue (red, no valid certificate found)

#### Alternatives or Workarounds
Currently, it can be done in 3 ways:
1) waiting for builds to fails or apps stop working/installing/deployment
2) watching Apple Developer Portal from time to time
3) writing a script around match repo to do the same

**Comment by stanBienaives** [comment]
Hello @yakimant  That would be a nice feature indeed. 

By any chance have you started to work on such thing? 
I am about to implement my own script but I would rather use/contribute a core feature of match.
