### ISSUE TITLE
Failing to init new project

### ISSUE THREAD

**Issue by TiagoVeloso** [fastlane/fastlane#1317]
I am trying to do a `fastlane init` on a new project.

I am getting this error:

```
/Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:268:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:45:in `teams'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:83:in `select_team'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.19.4/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup_ios.rb:173:in `detect_if_app_is_available'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup_ios.rb:29:in `run'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /Users/fork/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /Users/fork/.rbenv/versions/2.3.0/bin/fastlane:23:in `load'
	from /Users/fork/.rbenv/versions/2.3.0/bin/fastlane:23:in `<main>'
```

I don't know whats going on. I can login to developer.apple.com without issues with the credentials I've supplied. 

I am part of two teams could that be the issue?

**Comment by beheist** [comment]
I have the very same issue, and I'm also part of two teams. I've been seeing this issue for a while now. Here's a reference code: 73d6fb1887106701ce180e805fe4b10d

**Comment by TiagoVeloso** [comment]
> EDIT: It does work fine if I create the Appfile and Fastfile manually.

Yeah, for me too :S

**Comment by mgamber** [comment]
I've noticed that error, too, but it doesn't happen often and, when it does, it's usually mid afternoon or so, eastern time. I just try it again every 30 minutes or so and eventually it works. I suspect it's a problem at Apple since nothing changes at my end.

**Comment by TiagoVeloso** [comment]
I don't think so. When I use another AppleID to do the process it doesn't crash.

**Comment by otaran** [comment]
:+1: I am member of several teams and I get this crash when I run `fastlane init`, crash ID is `0517ff5ac7f2b4b33d337a3b7f114729`.

**Comment by legacy-code** [comment]
Same here -- I am a member in three teams (1 app store and 2 enterprise).  Right now, I can't get it to work at all.  Crash id:  'c6918fb648fe4dea2177db7d83adab53'.

**Comment by iheart2code** [comment]
I'm getting this, too. Crash ID 73cc542f2900a0b811b7a48358c23d53

**Comment by Quentiu** [comment]
Same here, crash id = `430ba8caf85a3f92cb79389fefc140ca`

**Comment by ohwutup** [comment]
just pushed a release which should allow for an easy fall back to manual initialization which should fix these issues. feel free to reopen if you all have any issues!

**Comment by otaran** [comment]
I can't verify this due to #1407
