### ISSUE TITLE
Two Auth SMS Support devices are not appearing

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#13188]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

When I run `fastlane cert`, fastlane attempts to login and returns the following message:

Two Factor Authentication for account '****' is enabled
Your session cookie has been expired.
Please enter the 6 digit code: 

Why doesn't it show the devices I want to send a SMS to? Do I need to enable some env variable?

**Comment by janpio** [comment]
Did it show the devices before?

For me personally, I get a "push" on all my iOS and macOS devices with a 6 digit code for 2FA. Does it work differently for you?

**Comment by pedro380085** [comment]
Hi @janpio, 

This account belongs to a customer of ours, so we don't have access to their iOS and macOS devices. What they did was adding one of our phone numbers as a trusted number on their account. So when we use fastlane, we can get the SMS on our mobile phone.

**Comment by janpio** [comment]
How does this work in the usual web interfaces of Apple? Do you have a dropdown of numbers?

**Comment by pedro380085** [comment]
On the web interfaces they automatically show the six digit box after login. Then I click on "didn't get the verification code?" link and they allow me to select the phone number.

**Comment by pedro380085** [comment]
I get, it's basically a flow on the client.

Maybe we can force `r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array...`  to be called before on `two_step_client.rb` @KrauseFx ?

**Comment by xster** [comment]
+1. Getting an SMS is a marginally more scalable way of sharing (via web phone numbers etc) 2FA than having devices signed in with Apple IDs and getting push notifications.

**Comment by pedro380085** [comment]
Yes, we would need a way for fastlane 2FA to be compatible with SMS.

**Comment by darek-phorest** [comment]
+1 would be great to have that selection of the phone number as in the web flow

**Comment by reeltimeapps** [comment]
+1 Now with Apple requiring developer accounts to have two-factor authentication being able to have SMS would be extremely helpful for us.

**Comment by dachev** [comment]
+1 This is very important to us too as we are building apps using client accounts and many of them are individuals so they are not allowed to invite team members.

**Comment by janpio** [comment]
Work on https://github.com/fastlane/fastlane/pull/13507 that implements this is progressing. But there are some questions, could use your input: https://github.com/fastlane/fastlane/pull/13507#issuecomment-440792764

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/pull/14011 is ready for testing.

**Comment by janpio** [comment]
Has been merged and should work now.

**Comment by janpio** [comment]
Hey everyone that posted here, I am currently working on a first improvement to the 2FA sms handling of fastlane/spaceship: [A way to define which phone number should automatically be selected for the 2FA token sms](https://github.com/fastlane/fastlane/issues/13980).

I need some help with the output on the Apple UI though: [#13980 (comment)](https://github.com/fastlane/fastlane/issues/13980#issuecomment-466402647) Would be great if some of your with "trusted phone numbers" in their accounts could take a look and reply. Thanks!
