### ISSUE TITLE
Trouble with google_play_track_version_codes in cli

### ISSUE THREAD

**Issue by Matthiax** [fastlane/fastlane#13184]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

fastlane google_play_track_version_codes

No

No
#### Question Description

I'm having trouble using the action 'google_play_track_version_codes' through Terminal. I am trying to retrieve the current version of the production track on the Play Store. This is the command I'm trying to run:

```/usr/local/bin/fastlane google_play_track_version_codes --package_name "com.company.product" --track production --json_key /path/to/the/key.json```

It returns an error "invalid option: --package_name". That parameter worked fine in a different 'supply' command, and is listed in the available commands for 'google_play_track_version_codes' but I can't seem to get it working. I'm not sure I'm running this correctly, or if this is a bug, or what. 

Any help would be appreciated!

**Comment by janpio** [comment]
`google_play_track_version_codes` is not a CLI command but an action. Using `fastlane run google_play_track_version_codes ...` should work.

**Comment by Matthiax** [comment]
Ahh, so not all actions can be used as commands. I tried adding in ```run``` which still returned ```invalid option: --package_name```. I plan on moving to a Fastfile someday, but it will require a good amount of reworking my pipeline. At the moment I only use a couple of actions. I appreciate the help though!

**Comment by janpio** [comment]
Oh, seems the param is supplie differently for actions:

`/usr/local/bin/fastlane run google_play_track_version_codes package_name:"com.company.product" track:"production" json_key:"/path/to/the/key.json"` might work

https://docs.fastlane.tools/advanced/actions/#run-actions-directly

**Comment by Matthiax** [comment]
Wow! This makes things so much easier! Thank you so much! I didn't realize there was a different syntax for it. Works like a charm now!

**Comment by janpio** [comment]
Same here. I also don't understand exactly why ;)
