### ISSUE TITLE
Fastlane Match Codesign for Frameworks is using the Login keychain, not the keychain I specified

### ISSUE THREAD

**Issue by joquerod** [fastlane/fastlane#13187]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane Match

No

No

#### Question Description

I use Fastlane Match to codesign my App
The App has two Frameworks (internal, not third party)
When Fastlane Match codesigns the App, the Frameworks are codesigned with a Development Certificate. The codesign syle in the target settings for these frameworks is 'Automatic'. I tried specifying profiles, but that is not allowed.
We run this process in a CI environment with several build machines, and as part of this new process, we need to use a custom keychain, and we can't use the Login keychain.

When I run match, I specify the keychain_name, keychain_password parameters.
These arguments work fine for the main app with the app_identifiers I provide.
But when the codesign happens for the frameworks, I will receive a prompt to unlock the Login keychain, and this breaks our Jenkins pipeline.

Any suggestion?

**Comment by zaro0508** [comment]
You might be getting this problem if you did not configure the keychain you want to use as the default and unlocked.  you want to create the keychain with these params..

```
  desc "Create keychains to store certificates"
  lane :keychains do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end
```

**Comment by joquerod** [comment]
Thank you! That works
