### ISSUE TITLE
RuntimeException: Unable to capture screenshot

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#13180]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to run an UIAutomation to take screenshots but the app is crashing when it calls `Screengrab.screenshot("0")`. It was working a month ago in a version of Fastlane that I don't remember.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
▸ java.lang.RuntimeException: Unable to capture screenshot.
▸ at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
▸ at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
  </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4 |
| Ruby                        | 2.3.3 |
| Bundler?                    | false |
| Git                         | git version 2.17.1 |
| Installation Source         | /usr/local/bin/fastlane |
| Host                        | Mac OS X 10.13.4 (17E199) |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7 |
| Is contained                | false |
| Is homebrew                 | false |
| Is installed via Fabric.app | false |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
Nope
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
Also nope
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| unicode-display_width     | 1.4.0        |
| dotenv                    | 2.5.0        |
</details>

*generated on:* **2018-08-21**
</details>
  </pre>
</details>

**Comment by janpio** [comment]
What command are you running?
What does your test look like?

**Comment by ppamorim** [comment]
@janpio 

```ruby
screengrab(
    android_home: "/Users/ppamorim/Library/Android/sdk",
    locales: ["en-GB"],
    app_package_name: packageName,
    clear_previous_screenshots: true,
    skip_open_summary: true,
    output_directory: "fastlane/fastlane/metadata/#{flavor}",
    use_tests_in_classes: ["com.me.android.ui.AutoScreenshot"],
    app_apk_path: "me/build/outputs/apk/#{flavor}/debug/me-#{flavor}-debug.apk",
    tests_apk_path: "me/build/outputs/apk/androidTest/#{flavor}/debug/me-#{flavor}-debug-androidTest.apk",
    reinstall_app: false,
    specific_device: adbDevicesId)

```
