### ISSUE TITLE
Enterprise key management

### ISSUE THREAD

**Issue by jleach** [fastlane/fastlane#13185]
I've read through the docs Fastlane seems promising. One thing I'm not sure of is if a developer does a build locally on there machine how are the keys / certificates secured? In our enterprise we tend to not give all developers all the keys because they often walk out the door at 5pm or as contractors cycle through. In our case not every project is in a build system so limiting access via a build server isn't an option just yet.

Thx.

**Comment by kirshanluhana** [comment]
following

**Comment by janpio** [comment]
If the developers don't have the files but there is also not second system to build, how could this work? The data has to be available on the system doing the build.

Most data can be supplied as direct params to actions that can come from an environment variable, but that's also not a solution in your case as this is also accessible to the developers. Same for maybe encrypting some file or database - as the lanes will need the data, they will have to decrypt the data as well and this again is accessible to the developer.
