### ISSUE TITLE
`fastlane supply init` gives Signet::RemoteServerError from google-api-client

### ISSUE THREAD

**Issue by bjornbjorn** [fastlane/fastlane#13198]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to set up my Flutter project with Fastlane and have been following the tutorial [here](https://flutter.io/fastlane-cd/) 

Running `fastlane supply init` gives me an `uninitialized constant Signet::RemoteServerError (NameError)` error.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[10:06:29]: 🕗  Downloading metadata, images, screenshots...
[10:06:29]: To not be asked about this value, you can specify it using 'json_key'
[10:06:29]: The service account json file used to authenticate with Google: ../google-play-api-secret.json
[10:06:55]: To not be asked about this value, you can specify it using 'package_name'
[10:06:55]: The package name of the application to use: com.myappname.android

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.23.5/lib/google/apis/core/http_command.rb:102:in `block in execute': [!] uninitialized constant Signet::RemoteServerError (NameError)
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.23.5/lib/google/apis/core/http_command.rb:93:in `execute'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.23.5/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.23.5/generated/google/apis/androidpublisher_v2/service.rb:200:in `insert_edit'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/client.rb:93:in `block in begin_edit'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/client.rb:397:in `call_google_api'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/client.rb:93:in `begin_edit'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/setup.rb:11:in `perform_download'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/commands_generator.rb:59:in `run'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/supply/lib/supply/commands_generator.rb:12:in `start'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
  from /Users/myusername/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/bin/fastlane:20:in `<top (required)>'
  from /Users/myusername/.fastlane/bin/bundle/bin/fastlane:22:in `load'
  from /Users/myusername/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.5       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.3        |
</details>

*generated on:* **2018-08-23**
</details>

**Comment by jrista** [comment]
I just encountered this issue as well. Never seen it before. Is it a temporal issue due to a server outage or something, or is it actually a bug?

**Comment by TriangleIL** [comment]
I'm also seeing this issue while running Supply.  As an aside, I downgraded fastlane and it fixed the problem for me until the library dependencies get fixed.

**Comment by jrista** [comment]
@TriangleIL Any idea what version specifically is working? I'm running into the issue on our CI, which is currently just installing the latest version of fastlane. If installing a specific version will resolve the issue, that would be great.

**Comment by ohtangza** [comment]
I am encountering this issue after a clean installation.

**Comment by unicornio8** [comment]
+1

**Comment by jrista** [comment]
I dropped back to fastlane 2.99.0 and things seem to work again.

**Comment by ohtangza** [comment]
Oh, in my case, I uninstalled the fastlane whch was installed with `homebrew` and re-installed with Ruby command. Then, it worked again!

**Comment by renatopeterman** [comment]
+1
Same here after updating fastlane.
