### ISSUE TITLE
How to modify the product bundle Identifier

### ISSUE THREAD

**Issue by sun6boys** [fastlane/fastlane#13199]
I need to change the bundle identifier, I used 'update_info_plist', but only changed the info. Plist, not the build setting-> product bundle identifier. How to modify build setting -> product bundle identifier

**Comment by sun6boys** [comment]
I've already used the "update_app_identifier"  ,But <Build Settings/Product Bundle Identifer> has not changed

**Comment by janpio** [comment]
Are you sure? Your initial message mentioned a different action `update_info_plist`. Did you try both?

**Comment by sun6boys** [comment]
Thx,I found the reason, as you said.
