### ISSUE TITLE
Unsupported workspace file reference type `SDK`

### ISSUE THREAD

**Issue by calkinssean** [fastlane/fastlane#13203]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I haven't generated screenshots for a little over a month so I don't know the exact version this last worked on. I can verify that the apps it used to work also experience the same issue.

These are the errors I get on every run

```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
RuntimeError: [!] Unsupported workspace file reference type `SDK`
```

##### Complete output when running fastlane, including the stack trace and command used

<details>

</details>

### Environment

<details>
  <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

	desc "Generate All Screenshots"
	lane :generate_all_screenshots do
		apps.each do |app|
			snapshot(
				clean: "true",
				number_of_retries: 3,
				reinstall_app: "true",
				scheme: app.scheme,
				output_directory: "../screenshots/#{app.output_name}")
		end
	end
	

</details>

<details><summary>`./fastlane/Appfile`</summary>

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
</details>


*generated on:* **2018-08-23**
</details>
</details>

**Comment by calkinssean** [comment]
Update, the last new app I created was on 07/17/2018, screenshots were generated as well meaning this was not an issue on whatever version was the current version on that day.

**Comment by calkinssean** [comment]
This is really strange to me.
In sublime it's referencing my android library for some reason...

[dir: /Users/seancalkins/****/********/iOS/**********/fastlane]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/seancalkins/Library/Android/sdk/platform-tools/]

**Comment by janpio** [comment]
What command are you running?
What is the complete output you are getting (with `--verbose`)?

**Comment by calkinssean** [comment]
I am running bundle exec fastlane ios generate_all_screenshots

desc "Generate All Screenshots"
	lane :generate_all_screenshots do
		apps.each do |app|
			snapshot(
				clean: "true",
				number_of_retries: 3,
				reinstall_app: "true",
				scheme: app.scheme,
				output_directory: "../screenshots/#{app.output_name}")
		end
	end

I managed to use the snapshot helper to find my screenshots. But trying to update today is giving me the same issue when running 


desc "Update All Apps"
	lane :update_all_apps do
		apps.each do |app|
			get_certificates(username: "*****@***.com")
			get_provisioning_profile(username: "*****@***.com", app_identifier: app.app_identifier)
			gym(scheme: app.scheme, output_directory: "../ipas", output_name: app.output_name)
			deliver(username: "*****@***.com", ipa: "../ipas/#{app.output_name}.ipa",
				# Comment out the line below to upload screenshots
				skip_screenshots: "true",
				overwrite_screenshots: "true", screenshots_path: "../screenshots/#{app.output_name}",
				app_identifier: app.app_identifier, force: "true", automatic_release: "true", reject_if_possible: "true")
		end
	end

**Comment by calkinssean** [comment]
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
RuntimeError: [!] Unsupported workspace file reference type `SDK`

**Comment by calkinssean** [comment]
The actual error is happening during the gym command

**Comment by calkinssean** [comment]
Error happens in gym command

**Comment by calkinssean** [comment]
Another update: I was able to fix the issue by deleting all pods and my workspace and recreating it the workspace. Not really sure what the original issue was but somehow my workspace got screwed up. Closing the issue.
