### ISSUE TITLE
Fastlane snapshot takes 2x2 pixels screenshots

### ISSUE THREAD

**Issue by osrl** [fastlane/fastlane#13225]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This issue is dupe of #11944 
I think it's related to this line. 

https://github.com/fastlane/fastlane/blob/daaf326ea8492b8e07a0315812c53219e046ebba/snapshot/lib/assets/SnapshotHelper.swift#L163

SnapshotHelper should select Main Window instead of first one. I'm taking screenshots of a cordova app and I can't update Firebase SDK as suggested in #11944.

`po app.windows` on line 163 outputs this

```
  Output: {
    Application, 0x600000197f80, pid: 28499, {{0.0, 0.0}, {375.0, 667.0}}, label: 'CSD'
  }
  ↪︎Find: Descendants matching type Window
    Output: {
      Window, 0x600000198050, {{0.0, 0.0}, {1.0, 1.0}}
      Window, 0x6000001987a0, Main Window, {{0.0, 0.0}, {375.0, 667.0}}
      Window, 0x6000001998b0, {{0.0, 0.0}, {375.0, 667.0}}
    }
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by osrl** [comment]
I've edited the mentioned line like this:

```
let window = app.windows.allElementsBoundByIndex.first { element in
                element.frame.width > 10
            }!
```

If anyone knows a better solution for this, please notify me.

**Comment by janpio** [comment]
So we probably want to go through the windows and get the `Main Window` or at least the biggest one / the one that matches the `Application` dimensions?

**Comment by osrl** [comment]
Yes, but I couldn't find a way to get the `Main Window`. Checking if it matches application dimensions may work.
