### ISSUE TITLE
Xcodeproj doesn't know about the following attributes

### ISSUE THREAD

**Issue by brenwell** [fastlane/fastlane#13220]
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

https://github.com/CocoaPods/Xcodeproj/issues/535 Now closed

### Issue Description
Building with Xcode 10 and using React-native Firebase crashyltics (which requires a build phase with `inputFiles` value) causes the following error

```
Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa. (RuntimeError)
```
It appears as though fastlane is referencing or ships with an older version of xcodeproj which doesn't have the fix for this issue 1.5.7

```from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'```

##### Complete output when running fastlane, including the stack trace and command used

```shell
[!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | register_devices       | 3           |
| 3    | clean_build_artifacts  | 0           |
| 4    | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 5    | increment_build_numbe  | 4           |
|      | r                      |             |
| 💥   | commit_version_bump    | 0           |
+------+------------------------+-------------+

+---------+--------------+----------------+
|        Plugin updates available         |
+---------+--------------+----------------+
| Plugin  | Your Version | Latest Version |
+---------+--------------+----------------+
| bugsnag | 1.3.2        | 1.3.4          |
+---------+--------------+----------------+
[10:18:37]: To update all plugins, just run
[10:18:37]: $ bundle exec fastlane update_plugins

[10:18:37]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:203:in `initialize_from_file'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:103:in `open'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/commit_version_bump.rb:60:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.102.0/bin/fastlane:20:in `<top (required)>'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13.6                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.17.1 (Apple Git-112)               |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.13.6 (17G65)                         |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 10.0                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status      |
| ----------------------- | ------- | ------------------ |
| fastlane-plugin-bugsnag | 1.3.2   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| xml-simple                | 1.1.5        |
| git                       | 1.4.0        |
| fastlane-plugin-bugsnag   | 1.3.2        |
</details>

*generated on:* **2018-08-27**
</details></pre>
</details>

**Comment by brenwell** [comment]
I forgot to add a big thanks for the awesome tool !!

**Comment by janpio** [comment]
Are you sure a newer version of xcodeproj fixes the issue?
Can you identify which newer version of xcodeproj fixes the issue? (see https://github.com/CocoaPods/Xcodeproj/releases)
(I don't know enough about ruby and bundle, but I guess you can maybe run `bundle update xcodeproj` to update to a newer version and try again - depending on how exactly you are using fastlane)

**Comment by brenwell** [comment]
Looks like [1.5.8](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.5.8)

> Warn when encountering unknown attributes instead of bailing out. *theoriginalgri* #535

https://github.com/CocoaPods/Xcodeproj/pull/570

I am not building fastlane on my machine, if I get a moment I can try. But I have deadline on Friday, and then 2 weeks off, so it would have to after - sorry

**Comment by brenwell** [comment]
I edited the xcodeproj inside fastlane locally to match the changes from the Pull Request below. Basically replacing the `raise` with `warn` and everything works

https://github.com/CocoaPods/Xcodeproj/pull/570/files

**Comment by janpio** [comment]
@brenwell The PR has been merged, look out for the next release that should include this and fix your problem.

**Comment by ChandniSharma** [comment]
I am also facing the same problem has any one idea how to resolve this issue in xcode 10.

**Comment by acalism** [comment]
use a higher version pod to run `pod deintegrate`, then you can use a lower version pod to `pod install`
I solved use the method as I said.
