### ISSUE TITLE
[Match] [!] SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by ptelad** [fastlane/fastlane#13233]
### New Issue Checklist

- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] Updated fastlane to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running match on out build mac, we get this error:
`[!] SSL_connect returned=1 errno=0 state=error: certificate verify failed`
on the match step.
This happens both when running from the Bamboo agent and when running manually.

It works fine on my Mac with the same env, so that's weird...
It worked before just fine, I even reverted the Mac back using time machine but the error is still thrown.

I've tried everything I found on Google but nothing works! This issue is my last hope.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
McBuildys-Mac-mini:ios mcbuildy$ bundle exec fastlane match appstore --verbose
[✔] 🚀 
Successfully loaded Appfile at path '/Users/mcbuildy/bamboo-agent-home/xml-data/build-dir/EAP-EAP-JOB1/ios/fastlane/Appfile'
- app_identifier: 'com.eko.App'
- apple_id: 'elad@helloeko.com'
- team_id: '32U3WAAGM3'
-------
INFO [2018-08-28 14:02:13.40]: Successfully loaded '/Users/mcbuildy/bamboo-agent-home/xml-data/build-dir/EAP-EAP-JOB1/ios/fastlane/Matchfile' 📄

+---------+----------------------------------------------------------+
|            Detected Values from './fastlane/Matchfile'             |
+---------+----------------------------------------------------------+
| git_url | <Censored>    |
| type    | development                                              |
+---------+----------------------------------------------------------+

+-----------------------+----------------------------------------------------------+
|                            Summary for match 2.102.0                             |
+-----------------------+----------------------------------------------------------+
| verbose               | true                                                     |
| type                  | appstore                                                 |
| git_url               | <Censored>    |
| git_branch            | master                                                   |
| app_identifier        | ["com.eko.App"]                                          |
| username              | elad@helloeko.com                                        |
| keychain_name         | login.keychain                                           |
| readonly              | false                                                    |
| team_id               | <Censored>                                               |
| force                 | false                                                    |
| skip_confirmation     | false                                                    |
| shallow_clone         | false                                                    |
| clone_branch_directly | false                                                    |
| force_for_new_devices | false                                                    |
| skip_docs             | false                                                    |
| platform              | ios                                                      |
+-----------------------+----------------------------------------------------------+

INFO [2018-08-28 14:02:13.41]: Cloning remote git repo...
INFO [2018-08-28 14:02:13.41]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-08-28 14:02:13.41]: $ GIT_TERMINAL_PROMPT=0 git clone '<Censored>' '/var/folders/pj/kbdbj9mx1nn16pw0r85279zm0000gn/T/d20180828-2595-1ak8knq'
INFO [2018-08-28 14:02:13.44]: ▸ Cloning into '/var/folders/pj/kbdbj9mx1nn16pw0r85279zm0000gn/T/d20180828-2595-1ak8knq'...
INFO [2018-08-28 14:02:15.74]: ▸ remote: Counting objects: 377, done.
INFO [2018-08-28 14:02:15.74]: ▸ remote: Compressing objects: 100% (45/45), done.
INFO [2018-08-28 14:02:16.76]: ▸ remote: Total 377 (delta 8), reused 0 (delta 0)
INFO [2018-08-28 14:02:16.76]: ▸ Receiving objects: 100% (377/377), 877.10 KiB | 866.00 KiB/s, done.
INFO [2018-08-28 14:02:16.76]: ▸ Resolving deltas: 100% (57/57), done.
INFO [2018-08-28 14:02:16.79]: 🔓  Decrypted 'UG63922Q3F.cer'
INFO [2018-08-28 14:02:16.79]: 🔓  Decrypted '76Q6L97NDM.cer'
INFO [2018-08-28 14:02:16.79]: 🔓  Decrypted 'UG63922Q3F.p12'
INFO [2018-08-28 14:02:16.79]: 🔓  Decrypted '76Q6L97NDM.p12'
INFO [2018-08-28 14:02:16.79]: 🔓  Decrypted 'AdHoc_com.eko.App-staging.mobileprovision'
INFO [2018-08-28 14:02:16.79]: 🔓  Decrypted 'AppStore_com.eko.App.mobileprovision'
INFO [2018-08-28 14:02:16.80]: 🔓  Decrypted 'Development_com.eko.App-dev.mobileprovision'
INFO [2018-08-28 14:02:16.80]: 🔓  Decrypted 'Development_com.eko.App-staging.mobileprovision'
INFO [2018-08-28 14:02:16.80]: 🔓  Successfully decrypted certificates repo
INFO [2018-08-28 14:02:16.80]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2018-08-28 14:02:20.59]: Installing certificate...
INFO [2018-08-28 14:02:20.59]: $ security list-keychains -d user
INFO [2018-08-28 14:02:20.63]: ▸     "/Users/mcbuildy/Library/Keychains/login.keychain-db"
INFO [2018-08-28 14:02:20.63]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/mcbuildy/Library/Keychains/login.keychain-db
INFO [2018-08-28 14:02:20.74]: ▸ keychain: "/Users/mcbuildy/Library/Keychains/login.keychain-db"
<Censored>   

+-------------------+------------------------------------------------------+
|                          Installed Certificate                           |
+-------------------+------------------------------------------------------+
| User ID           | 32U3WAAGM3                                           |
| Common Name       | iPhone Distribution: JBF Interlude Ltd. (32U3WAAGM3) |
| Organisation Unit | 32U3WAAGM3                                           |
| Organisation      | JBF Interlude Ltd.                                   |
| Country           | US                                                   |
| Start Datetime    | 2018-07-29 12:23:05 UTC                              |
| End Datetime      | 2019-07-29 12:23:05 UTC                              |
+-------------------+------------------------------------------------------+

INFO [2018-08-28 14:02:21.66]: Installing provisioning profile...
ERROR [2018-08-28 14:02:22.35]: -----------------------------------------------------------------------
ERROR [2018-08-28 14:02:22.35]: SSL_connect returned=1 errno=0 state=error: certificate verify failed
ERROR [2018-08-28 14:02:22.35]: 
ERROR [2018-08-28 14:02:22.35]: SSL errors can be caused by various components on your local machine.
ERROR [2018-08-28 14:02:22.35]: 
ERROR [2018-08-28 14:02:22.35]: The best solution is to use the self-contained fastlane version.
ERROR [2018-08-28 14:02:22.35]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
ERROR [2018-08-28 14:02:22.35]:  - Use Homebrew
ERROR [2018-08-28 14:02:22.35]:     - update brew with `brew update`
ERROR [2018-08-28 14:02:22.35]:     - install fastlane using:
ERROR [2018-08-28 14:02:22.35]:       - `brew cask install fastlane`
ERROR [2018-08-28 14:02:22.35]:  - Use One-Click-Installer:
ERROR [2018-08-28 14:02:22.35]:     - download fastlane at https://download.fastlane.tools
ERROR [2018-08-28 14:02:22.35]:     - extract the archive and double click the `install`
ERROR [2018-08-28 14:02:22.35]: -----------------------------------------------------------
ERROR [2018-08-28 14:02:22.35]: for more details on ways to install fastlane please refer the documentation:
ERROR [2018-08-28 14:02:22.35]: -----------------------------------------------------------
ERROR [2018-08-28 14:02:22.35]:         🚀       https://docs.fastlane.tools          🚀   
ERROR [2018-08-28 14:02:22.35]: -----------------------------------------------------------
ERROR [2018-08-28 14:02:22.35]: 
ERROR [2018-08-28 14:02:22.35]: You can also install a new version of Ruby
ERROR [2018-08-28 14:02:22.35]: 
ERROR [2018-08-28 14:02:22.35]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
ERROR [2018-08-28 14:02:22.35]: - If you use system Ruby:
ERROR [2018-08-28 14:02:22.35]:   - Run `brew update && brew install ruby`
ERROR [2018-08-28 14:02:22.35]: - If you use rbenv with ruby-build:
ERROR [2018-08-28 14:02:22.35]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
ERROR [2018-08-28 14:02:22.35]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
ERROR [2018-08-28 14:02:22.35]: - If you use rvm:
ERROR [2018-08-28 14:02:22.35]:   - First run `rvm osx-ssl-certs update all`
ERROR [2018-08-28 14:02:22.35]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
ERROR [2018-08-28 14:02:22.35]: 
ERROR [2018-08-28 14:02:22.35]: If that doesn't fix your issue, please google for the following error message:
ERROR [2018-08-28 14:02:22.36]:   'SSL_connect returned=1 errno=0 state=error: certificate verify failed'
ERROR [2018-08-28 14:02:22.36]: -----------------------------------------------------------------------
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Faraday::SSLError: [!] SSL_connect returned=1 errno=0 state=error: certificate verify failed
  /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
  /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
  /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
  /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:876:in `start'
  /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:694:in `block in send_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:529:in `with_retry'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:693:in `send_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:581:in `request'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/portal_client.rb:595:in `provisioning_profiles_via_xcode_api'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:317:in `all'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/spaceship_ensure.rb:57:in `profile_exists'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/runner.rb:179:in `fetch_provisioning_profile'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/runner.rb:63:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/runner.rb:62:in `loop'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/runner.rb:62:in `block in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/runner.rb:61:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/runner.rb:61:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/commands_generator.rb:61:in `block (3 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/commands_generator.rb:146:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/match/lib/match/commands_generator.rb:19:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.102.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.47.0"

default_platform :ios

platform :ios do
  before_all do |lane, options|
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Staging Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :staging do |options|
    version = get_version_from_git()
    puts "Setting version from git to: " + version
    update_build_number(build_number: options[:build_number], version: version)
    match(type: "adhoc", force_for_new_devices: true) # more information: https://codesigning.guide
    gym(scheme: "EkoApp - Staging") # Build your app - more options available
    hockey(api_token: options[:app_token], notify: "2")
    codepush(deployment: "Staging", version: version)

  end

  desc "Deploy a new version to the App Store"
  lane :release do |options|
    version = get_version_from_git()
    puts "Setting version from git to: " + version
    update_build_number(build_number: options[:build_number], version: version)
    match(type: "appstore")
    gym(scheme: "EkoApp") # Build your app - more options available
    deliver(
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true
    )
    codepush(deployment: "Production", version: version)
end

  lane :update_build_number do |options|
    increment_build_number(
      build_number: options[:build_number],
      xcodeproj: "EkoApp.xcodeproj"
    )
    increment_version_number(
      version_number: options[:version],
      xcodeproj: "EkoApp.xcodeproj"
    )
  end

  desc "Installs all the needed certificates"
  lane :certificates do
    match(app_identifier: "com.eko.App", type: "appstore", readonly: true)
    match(app_identifier: "com.eko.App", type: "development", readonly: true)
    match(app_identifier: "com.eko.App-staging", type: "adhoc", readonly: true)
    match(app_identifier: "com.eko.App-staging", type: "development", readonly: true)
    match(app_identifier: "com.eko.App-dev", type: "development", readonly: true)
  end

  desc "Release and update to CodePush"
  lane :codepush do |options|
    version = options[:version]
    code_push_release_react(
      app_name: "EkoApp",
      platform: "ios",
      deployment: options[:deployment],
      target_binary_version: version[0..2] + ".x",
      mandatory: false,
      execution_dir_path: "../",
      description: ""
    )
  end

  def get_version_from_git()
    ver_regexp = /(\d+\.\d+\.\d+)/
    m = nil
    branch = git_branch()
    if (branch =~ /(release|hotfix)(.*)/i)
      puts "in release/hotfix branch!"
      m = ver_regexp.match(branch)
    else
      puts "not in release branch"
      m = ver_regexp.match(last_git_tag())
    end

    if (m === nil)
      puts "Could not find version from git, this is a problem, exiting..."
      exit(1)
    end

    return m[0]
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.eko.App" # The bundle identifier of your app
apple_id "elad@helloeko.com" # Your Apple email address

team_id "32U3WAAGM3" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

for_lane :staging do
  app_identifier "com.eko.App-staging"
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-code_push | 0.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-code_push | 0.3.0        |
</details>

*generated on:* **2018-08-28**
</details>

**Comment by ptelad** [comment]
Sorry bot, it has nothing to do with code signing

**Comment by pajapro** [comment]
Hi @ptelad any luck solving the problem with `[!] SSL_connect returned=1 errno=0 state=error: certificate verify failed`? I am running into the same issue when using `sigh` within the corporate network

**Comment by ptelad** [comment]
@pajapro - unfortunately I did not solve it, still waiting for my savior

**Comment by ptelad** [comment]
Finally fixed it by running `brew cask reinstall fastlane` and restarting the Bamboo agent.
I've tried it before, I have no idea why it worked this time :/
