### ISSUE TITLE
How to upload dsym files to Dynatrace

### ISSUE THREAD

**Issue by spoddar85** [fastlane/fastlane#13236]
### Question Checklist

Yes- [ ] Updated fastlane to the latest version
Yes- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
Yes- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
Yes- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I want to upload dsym files to Dynatrace

No

Yes. I dont see any third party plugin which helps to dsym files to the appmon server using Fastlane or Jenkins

#### Question Description
<!-- 
>

Please include expected behavior and any relevant code samples with your question if possible --
I want to upload the dsym files to appmon server for dynatrace. This will help me to see the crash reports. Is there a way I can use fastlane to do this. I see fastlane suports craslytics but does it support Dynatrace?

**Comment by janpio** [comment]
Could you please provide some context on what Dynatrace exactly is and in what context it allows uploading dsym files? 
There don't seem to be _any_ actions that integrate with Dynatrace yet, correct?

**Comment by spoddar85** [comment]
Dynatrace is a monitoring tool which helps in live monitoring, crash
reports and performance management of live apps(mobile and web). Currently
we are using to analye our crash reports but it looks like we need to
upload the dsym file(ios) and mapping file(android). Just saw that the same
can be achieved for crashlytics using fastlane but yeah didnt find any
action to integrate with Dynatrace.



Thanks
Sandip
973.580.8676

**Comment by janpio** [comment]
Does Dynatrace have an API to upload those files?

This is the source code of the crashltics actions, which uses a locally installed tool to upload:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb

**Comment by spoddar85** [comment]
Thanks Jan. I am following up with Dynatrace to see if they have an API
which we can use to upload. Will get back to you as soon as I find it.


Thanks
Sandip
973.580.8676
