### ISSUE TITLE
download_dsyms does not retry errors

### ISSUE THREAD

**Issue by tmm1** [fastlane/fastlane#13241]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Getting lots of errors during download_dsyms recently.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Spaceship::UnexpectedResponse: [!] <HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;54273017&#46;1535504570&#46;2614afa
</BODY></HTML>
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:602:in `parse_response'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/tunes_client.rb:256:in `applications'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:67:in `all'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:73:in `find'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/download_dsyms.rb:19:in `run'
</pre>
</details>

**Comment by janpio** [comment]
There is some more information needed on this.

The error message mentions a proxy server - are you using one?
Any other output that could help? Do other commands that communicate with Apple work?

The stacktrace indicates that the error is already happening when `download_dsyms` tries to get the app you specified with `app_identifier`.

**Comment by tmm1** [comment]
I'm not using any proxies. The proxy error is coming from Apple's side, since they appear to be using nginx as a frontend for their backend services.

The error is intermittent. It has been happening more and more often recently, but does not always occur. Other actions talking to apple's servers (such as uploading builds) seem to work fine.

You're right that the error appears to be related to spaceship application querying and not necessarily specific to download_dsyms. Some sort of retry mechanism in this part of the code would go a long way.

**Comment by tmm1** [comment]
Another one:

<pre>
Spaceship::UnexpectedResponse: [!] <HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;54273017&#46;1535597694&#46;8135402
</BODY></HTML>

  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:602:in `parse_response'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/tunes_client.rb:256:in `applications'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:67:in `all'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:73:in `find'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/pilot/lib/pilot/manager.rb:50:in `fetch_app_id'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/pilot/lib/pilot/manager.rb:30:in `app'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/pilot/lib/pilot/build_manager.rb:27:in `upload'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
</pre>

**Comment by janpio** [comment]
I reference this issue in another issue that collects unhandled error messages. Based on this, someone can create a PR on spaceship to handle all these. Maybe you?

**Comment by tmm1** [comment]
I can do that, but will raising `InternalServerError` cause fastlane to retry or is it just going to blow up with that instead of `UnexpectedResponse`?

**Comment by tmm1** [comment]
With #13255 I have been able to upload builds to iTC reliably again.

**Comment by janpio** [comment]
Just to add a bit more context:
```
INFO [2018-09-01 20:48:14.10]: Checking app for precheck rule violations
ERROR [2018-09-01 20:53:14.51]: fastlane precheck just tried to inspect your app's metadata for App Store guideline violations and ran into a problem. We're not sure what the problem was, but precheck failed to finished. You can run it in verbose mode if you want to see the whole error. We'll have a fix out soon 🚀
DEBUG [2018-09-01 20:53:14.51]: #<Spaceship::UnexpectedResponse: <HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;b6317a5c&#46;1535827996&#46;a44d0e0
</BODY></HTML>
>
```

**Comment by janpio** [comment]
(Best create a new issue with all the template filled out, this will probably get lost here. Looks a bit like a new problem on Apple's side as well [Interesting that this has `&#63743;`,  as the h1])

**Comment by ahmgeek** [comment]
@tmm1 can u ref the new issue here if u created it ? I already face same issue as exactly as u..

**Comment by darhonbek** [comment]
Hi, I'm facing the same issue now?
`[06:25:40]: <HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference #........
</BODY></HTML>`
Shall I do anything on my end, or just resend the build a bit later?

**Comment by tmm1** [comment]
@darhonbek Your fastlane is very old. Update to the latest version and the error will go away.
