### ISSUE TITLE
iOS Target Extension creation automation?

### ISSUE THREAD

**Issue by sharonswli** [fastlane/fastlane#13243]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Is it currently possible to use fastlane to create Target extensions on an existing `.xcodeproj` file? By "creating extensions" I don't mean using methods like `produce` to register a new app on Developer Portal or App store connect, but a command that automates the manual xcode IDE `File > New > Target` step.

This would be very useful for projects such as Cordova where the `App.xcodeproj` is dynamically generated on a build command, therefore one could integrate app extension creation with a CI/CD system without having to use xcode in the middle of the process.

**Current behaviour**
1. One must open the `App.xcodeproj` file in Xcode IDE, choose `File > New > Target > Notification Service Extension` and fill in the app name (i.e. `com.x.app.notificationextension`). This will generate a `com.x.app.notificationextension` folder containing a `NotificationService.swift` template and `Info.plist` file, plus modify `App.xcodeproj/project.pbxproj` as necessary.
2. One can then use fastlane to `produce` and `match` the new app extension in developer portal and code sign the extension with the necessary certificates.

**Desired behaviour:**
1. With an existing `NotificationService.swift` file, we can call fastlane to automate the entire process with something like:
```
lane :addnotificationservice do
  create (
    username: 'user@x.com',
    app_identifier: 'com.x.app.notificationextension',
    app_name: 'com.x.app notificationextension',
    type: 'NotificationService',
    srcFile: 'path/to/NotificationService.swift'
  )
  produce(...)
  match (...)
end
```
Does anyone know if this is achievable with existing actions in fastlane? Thank you!

**Comment by janpio** [comment]
👋 

I am not aware of a ready made action for this (but my knowledge is of course limited).

The "manual" way would be to create the files and changes to `App.xcodeproj` manually by observing what changes and replicate it with ruby and gem methods (`xcodeproj` might be useful here), or other fastlane actions.

If this works in a lane, it might be worth extracting into a plugin so other users can benefit.

Can you maybe create a Github repo containing two folder of a super simple iOS project with the "before" and "after" state of the steps you described above?

**Comment by johnknapprs** [comment]
You might be looking for something like this: https://github.com/yonaskolb/XcodeGen

**Comment by janpio** [comment]
Wow, nice tool! I suspect this won't solve @sharonswli's problem as they already start out with a Cordova Xcode project and want to add things to it - which I couldn't find in `XcodeGen`. Correct?

**Comment by sharonswli** [comment]
Thanks @janpio. I have done as you suggested, and observed the files changes in `App.xcodeproj/xcuserdata/${user}.xcuserdatad/xcschemes/xcschememanagement.plist` and `App.xcodeproj/project.pbxproj`. The `com.x.app.extension` folder (which contains the swift file) could easily be copied over, but the difficult changes are in `App.xcodeproj/project.pbxproj`. There are many changes throughout the entire file and I'm not sure if I could determine a pattern for those yet ([Here](https://gist.github.com/sharonswli/6b38d4d6cb3a0fc8e4a3f7d4127617de) is a list of additions in the "after" file.)

**Comment by janpio** [comment]
Yeah, the project files are pretty "verbose" in diffed changes after minimal actual changes. Using `xcodeproj` to understand the before structure and compare to the after structure might help to find out, what modifications have done with it (I would start with https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project).
