### ISSUE TITLE
Can Deliver upload the iTunesConnect Review Notes attachments??

### ISSUE THREAD

**Issue by mylegfeelsfunny** [fastlane/fastlane#13249]
#### Motivation Behind Feature
It is the last piece of Metadata that prevents our release process from being fully automated.

#### Feature Description
Can you add the ability to include the attachments in Delivers meta data for the Review Notes?
It is a piece of information that is not carried over by creating a new version. 
![screen shot 2018-08-29 at 1 23 06 pm](https://user-images.githubusercontent.com/1091447/44804547-9dbecb80-ab8f-11e8-92f9-f31db86b263f.png)

#### Alternatives or Workarounds
When an engineer forgets to include this, we get rejected unfortunately. I would like to destroy all humans from this process.

![bitmoji](https://render.bitstrips.com/v2/cpanel/c2b30773-81da-48f8-a618-2ae9193aeb5c-21e3ae36-f135-4e01-95c7-d6bace4743ad-v1.png?transparent=1&palette=1&width=246)

**Comment by janpio** [comment]
Any suggestions on the parameter naming and data structure for this?

**Comment by eAi** [comment]
I'd like to have this feature after being rejected for forgetting to attach a file. 

The nicest solution would be a folder that lives inside the review_information folder called "attachment". If that folder contains a single item, that item is attached, if it contains multiple items then they are zipped up and attached.

Alternatively just a single file could be supported called attachment.* (where * is one of the file formats that Apple supports: .pdf, .doc, .docx, .rtf, .pages, .xls, .xlsx, .numbers, .zip, .rar, .plist, .crash, .jpg, .png, .mp4, or .avi.)
