### ISSUE TITLE
Ability to add custom text to generated docs.

### ISSUE THREAD

**Issue by osrl** [fastlane/fastlane#13245]
#### Motivation Behind Feature

I need to add some more install and setup instructions to the docs. But it's not possible right now. 

#### Feature Description

It should be possible to add docs from the Fastfile.

#### Alternatives or Workarounds

Only alternative is create an empty lane with a description. This shows the instructions under available actions title which is not good.

**Comment by janpio** [comment]
What do you refer to by "generated docs" exactly?

**Comment by osrl** [comment]
README.md. It's generated from Fastfile after running a lane or running `fastlane docs`

**Comment by janpio** [comment]
Some research:
https://github.com/fastlane/fastlane/blob/b2dffaf886dcd6061a88e872eca548a492ca92cc/fastlane/lib/fastlane/lane_manager.rb#L73
https://github.com/fastlane/fastlane/blob/b2dffaf886dcd6061a88e872eca548a492ca92cc/fastlane/lib/fastlane/documentation/docs_generator.rb#L3-L59
Currently not customization possible it seems.
