### ISSUE TITLE
ARCHIVE FAILED : CompileSwift normal armv7

### ISSUE THREAD

**Issue by michaelraffin** [fastlane/fastlane#13244]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>       

** BUILD FAILED **
 CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
CompileSwift normal armv7

</details>

### Environment

<details>
  <pre> 
| Key                         | Value                                     |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.13.3                                   |
| Ruby                        | 2.2.2                                     |
| Bundler?                    | false                                     |
| Git                         | git version 2.10.1                        |
| Installation Source         | ~/.rvm/gems/ruby-2.2.2/bin/fastlane       |
| Host                        | Mac OS X 10.13.3 (17D47)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.2/lib              |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                |
| Is contained                | false                                     |
| Is homebrew                 | false                                     |
| Is installed via Fabric.app | false                                     |
| Xcode Path                  | ~/Desktop/Xcode_9.app/Contents/Developer/ |
| Xcode Version               | 9.0                                       |
 
</pre>
</details>

This is a very common issue please help ive already in the page  11 in the google chrome search  still cant find solutions

**Comment by michaelraffin** [comment]
issue : Multple Xcode Installed

**Comment by janpio** [comment]
What exactly is? I don't really understand what you posted - what is the actual error and how is it caused?

**Comment by michaelraffin** [comment]
@janpio  the issue is 


<pre>
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal x86_64
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

</pre>

**Comment by michaelraffin** [comment]
@janpio  i finally fixed it took me 3  days 
scenario  :   
i have 3 version of Xcode 
 and **command line tools** was pointed to older version   

Xcode - > Preference -> Command Line tools ->   

<img width="753" alt="screen shot 2018-07-27 at 2 50 29 pm" src="https://user-images.githubusercontent.com/22662400/44789473-36287080-abcf-11e8-8207-b3255d3d8292.png">
