### ISSUE TITLE
deliver init failing

### ISSUE THREAD

**Issue by mgamber** [fastlane/fastlane#1324]
After an update to deliver yesterday morning, "deliver init" no longer works as it did. Here are three scenerios:

If I run "deliver init" in a terminal, it fails with a permissions error trying to create "./screenshots".

If I run "sudo deliver init" in a terminal, it works correctly and everything is downloaded.

If I run "deliver init" or "echo 'password' | sudo deliver init" from a node.js script, it fails.

**Comment by mgamber** [comment]
FYI, when I uninstalled 1.10.2, causing it to drop back to 1.9.0, everything went back to working fine. I can copy/paste the stderr output from the script if it helps.

**Comment by vpolouchkine** [comment]
Can you share the full log please?

**Comment by mgamber** [comment]
I had to drop back a version so it worked. Tomorrow morning I'll update and copy/paste the failure and then drop back down again.

Thanks!

**Comment by KrauseFx** [comment]
Cool, I'll close this issue for now :+1:
