### ISSUE TITLE
fastlane update_plugins failure

### ISSUE THREAD

**Issue by huweidong** [fastlane/fastlane#13252]
I runing fastlane update_plugins failure With

**Comment by huweidong** [comment]
Errno::EACCES: Permission denied @ rb_sysopen -
/Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/unf_ext-0.0.7.5/lib/unf_ext.rb
An error occurred while installing unf_ext (0.0.7.5), and Bundler
cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.5'` succeeds before bundling.

**Comment by huweidong** [comment]
fastlane add_plugin firim   have save problem

**Comment by janpio** [comment]
Great you could solve that problem yourself.
