### ISSUE TITLE
A 504 Gateway time-out error message appeared when uploading to testflight.

### ISSUE THREAD

**Issue by DevZhaoXin** [fastlane/fastlane#13260]
[18:20:56]: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | get_build_number | 0           |
| 3    | get_build_number | 0           |
| 💥   | deliver          | 64          |
+------+------------------+-------------+

[18:20:56]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  A 504 Gateway time-out error message appeared when uploading to testflight.
    https://github.com/fastlane/fastlane/issues/13259 [open] 8 💬
    48 minutes ago

➡️  Version getters
    https://github.com/fastlane/fastlane/pull/504 [closed] 4 💬
    04 Feb 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	34: from /usr/local/bin/fastlane:23:in `<main>'
	33: from /usr/local/bin/fastlane:23:in `load'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/bin/fastlane:20:in `<top (required)>'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:55:in `block (2 levels) in parsing_binding'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `new'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/runner.rb:25:in `initialize'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/detect_values.rb:14:in `run!'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/detect_values.rb:41:in `find_app'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:73:in `find'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:67:in `all'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/tunes_client.rb:256:in `applications'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/cli (Spaceship::UnexpectedResponse)[!] <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

上传至App Store,，发生504错误，如何解决？

**Comment by janpio** [comment]
See https://github.com/fastlane/fastlane/issues/13259
