### ISSUE TITLE
Hockey Action Remove ipa requirement

### ISSUE THREAD

**Issue by appveng3r** [fastlane/fastlane#1327]
Why is ipa a requirement? I'd suggest to make ipa or dsym required.
It's possible only to upload the dSYM and that should also be possible with the fastlane action.

**Comment by KrauseFx** [comment]
You mean when you also set the `upload_dsym_only` option, right? I'll prepare a fix :+1:

**Comment by irew** [comment]
Awesome!

**Comment by appveng3r** [comment]
Great! What do you think about the solution to remove the parameter upload_dsym_only and only upload the dSYM if no ipa path is provided but a dSYM path? I guess the user decides with the given paths what he likes to upload.

**Comment by irew** [comment]
That would work for what we need. Also, I'd also like to **push release notes even if it's dSYM upload only**. I push dSYM for the store app, and I'd like to have details in the notes pushed along with the symbols.

**Comment by KrauseFx** [comment]
Merged with https://github.com/fastlane/fastlane/pull/1353, this will be live in the next release

**Comment by irew** [comment]
@KrauseFx is it possible to add the release notes to a dSYM only upload via hockey?
