### ISSUE TITLE
noShortDescription error

### ISSUE THREAD

**Issue by mrsolodov** [fastlane/fastlane#13277]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Upload to Google Play returns error: "Google Api Error: noShortDescription: This app has no short description (promotional text) for language ru_Ru"

#### Question Description
I have an application that does not have a release, alpha or beta builds in Google Play.
My task is to publish builds for internal testing. The first build was successful, and the version for internal use for a limited number of testers appeared in Google Play. However, next tries to publish the application with the same script return an error: _"Google Api Error: noShortDescription: This app has no short description (promotional text) for language ru_Ru"_

I'm sure that the short and complete descriptions on the application page in Google console are filled. I also completely deleted the project, cloned it again, set up the Fastlane and tried task again, but the result was the same.

**Comment by mrsolodov** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.5                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.5 (17F77)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

# Internal Block 

  desc "Submit a new Internal Build to Google Play"
  lane :internal do
    gradle(task: "clean assembleRelease")  
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    package_name = "xxx.xxxxxxxxxx.xxx"
    upload_to_play_store(apk: apk_path, package_name: package_name, track: 'internal')
  end

# Release Block 

  desc "Deploy a new Release Build to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    package_name = "xxx.xxxxxxxxxx.xxx"
    upload_to_play_store(apk: apk_path, package_name: package_name, track: 'production')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane/google_play.json")
package_name(“xxx.xxxxxxxxxx.xxx”)

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>


*generated on:* **2018-09-05**
</details>

**Comment by janpio** [comment]
Hi @mrsolodov, you are running your `internal` lane, correct? Could you please run it again with `--verbose` added at the end and post the complete output?

Do you have any metadata in your `fastlane` directory, e.g. from running `fastlane supply init`? 

You could try adding: `skip_upload_metadata: false` to the params of `upload_to_play_store` and see if this fixes your issue. (This of course is not the solution, but a temporary workaround. We will still have to find the underlying issue later)

**Comment by mrsolodov** [comment]
Hi, @janpio, yes i'm running `internal` lane.
Yes i have metadata folder in `fastlane` directory.

I added `skip_upload_metadata: false` to the params of `upload_to_play_store` and start `fastlane internal --verbose`. 

The bottom of log:

ERROR [2018-09-05 12:53:56.75]: fastlane finished with errors
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: noShortDescription: This app has no short description (promotional text) for language ru_RU. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:398:in `rescue in call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:396:in `call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:118:in `commit_current_edit!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:43:in `perform_upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by janpio** [comment]
> I added skip_upload_metadata: false to the params of upload_to_play_store

Did it help?

> Yes i have metadata folder in fastlane directory.

Does the `ru_RU` language have a filled `short_description.txt` file?

> The bottom of log:
I need the complete output to be able to see what the action is reading or not.

**Comment by janpio** [comment]
Yes, that would be nice - maybe we can understand the behaviour then.

(Background: The error you are seeing is coming directly from the API, so the API for some reason _wants_ that data and is not getting it. Maybe because of the _empty_ file (vs. non-existant file)?)

**Comment by mrsolodov** [comment]
That's it:

fastlane internal --verbose
[✔] 🚀 
[13:44:04]: fastlane detected a Gemfile in the current directory
[13:44:04]: however it seems like you don't use `bundle exec`
[13:44:04]: to launch fastlane faster, please use
[13:44:04]: 
[13:44:04]: $ bundle exec fastlane internal --verbose
[13:44:04]: 
[13:44:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
DEBUG [2018-09-05 13:44:05.90]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
INFO [2018-09-05 13:44:06.40]: ------------------------------
INFO [2018-09-05 13:44:06.40]: --- Step: default_platform ---
INFO [2018-09-05 13:44:06.40]: ------------------------------
INFO [2018-09-05 13:44:06.40]: Driving the lane 'android internal' 🚀
INFO [2018-09-05 13:44:06.40]: --------------------
INFO [2018-09-05 13:44:06.40]: --- Step: gradle ---
INFO [2018-09-05 13:44:06.40]: --------------------

... gradle logs (sorry i can't show it)

INFO [2018-09-05 13:45:37.86]: ▸ BUILD SUCCESSFUL in 1m 31s
INFO [2018-09-05 13:45:37.86]: ▸ 59 actionable tasks: 58 executed, 1 up-to-date
INFO [2018-09-05 13:45:38.54]: ----------------------------------
INFO [2018-09-05 13:45:38.54]: --- Step: upload_to_play_store ---
INFO [2018-09-05 13:45:38.54]: ----------------------------------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------

+-------------------------+-----------------------------------------------------------+
|                             Summary for supply 2.103.0                              |
+-------------------------+-----------------------------------------------------------+
| apk                     | /Users/user/project/app/build/outputs/apk/gene  |
|                         | ral/release/app-general-release-v1.0.apk                  |
| package_name            | xxx.xxxxxxxxxxx.xxx                                 |
| track                   | internal                                                  |
| skip_upload_metadata    | false                                                     |
| metadata_path           | ./fastlane/metadata/android                               |
| json_key                | fastlane/google_play.json                                 |
| skip_upload_apk         | false                                                     |
| skip_upload_aab         | false                                                     |
| skip_upload_images      | false                                                     |
| skip_upload_screenshots | false                                                     |
| validate_only           | false                                                     |
| check_superseded_tracks | false                                                     |
| timeout                 | 300                                                       |
+-------------------------+-----------------------------------------------------------+

DEBUG [2018-09-05 13:45:39.55]: Fetching a new access token from Google...
INFO [2018-09-05 13:45:40.96]: Preparing to upload for language 'ru-RU'...
INFO [2018-09-05 13:45:41.85]: Updating changelog for code version '19' and language 'ru-RU'...
INFO [2018-09-05 13:45:42.50]: Preparing apk at path '/Users/user/project/app/build/outputs/apk/general/release/app-general-release-v1.0.apk' for upload...
WARN [2018-09-05 13:45:46.49]: Lane Context:
INFO [2018-09-05 13:45:46.49]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android internal", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/user/project/app/build/outputs/apk/develop/release/app-develop-release-v1.0.apk", "/Users/user/project/app/build/outputs/apk/general/release/app-general-release-v1.0.apk"], :GRADLE_ALL_AAB_OUTPUT_PATHS=>[], :GRADLE_APK_OUTPUT_PATH=>"/Users/user/project/app/build/outputs/apk/general/release/app-general-release-v1.0.apk"}
ERROR [2018-09-05 13:45:46.49]: Google Api Error: apkUpgradeVersionConflict: APK specifies a version code that has already been used.
INFO [2018-09-05 13:45:46.49]: Successfully generated documentation at path '/Users/user/project/fastlane/README.md'

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | gradle               | 92          |
| 💥   | upload_to_play_store | 7           |
+------+----------------------+-------------+

ERROR [2018-09-05 13:45:46.51]: fastlane finished with errors
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: apkUpgradeVersionConflict: APK specifies a version code that has already been used. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:398:in `rescue in call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:396:in `call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:222:in `upload_apk'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:175:in `upload_binary_data'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:139:in `block in upload_apks'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:138:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:138:in `upload_apks'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:27:in `perform_upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by mrsolodov** [comment]
```
INFO [2018-09-05 13:45:40.96]: Preparing to upload for language 'ru-RU'...
INFO [2018-09-05 13:45:41.85]: Updating changelog for code version '19' and language 'ru-RU'...
```

It looks strange, because in my project's `build.gradle` i have `versionCode 21`

**Comment by janpio** [comment]
Output is also pretty strange now as you already successfully uploaded once - so this returns a different error now. Can you maybe up the version code and try again?

**Comment by mrsolodov** [comment]
I raised versionCode to 22.

fastlane internal --verbose
[✔] 🚀 
[14:03:54]: fastlane detected a Gemfile in the current directory
[14:03:54]: however it seems like you don't use `bundle exec`
[14:03:54]: to launch fastlane faster, please use
[14:03:54]: 
[14:03:54]: $ bundle exec fastlane internal --verbose
[14:03:54]: 
[14:03:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
DEBUG [2018-09-05 14:03:56.29]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
INFO [2018-09-05 14:03:56.65]: ------------------------------
INFO [2018-09-05 14:03:56.65]: --- Step: default_platform ---
INFO [2018-09-05 14:03:56.65]: ------------------------------
INFO [2018-09-05 14:03:56.65]: Driving the lane 'android internal' 🚀
INFO [2018-09-05 14:03:56.66]: --------------------
INFO [2018-09-05 14:03:56.66]: --- Step: gradle ---
INFO [2018-09-05 14:03:56.66]: --------------------

.. gradle logs

INFO [2018-09-05 14:05:34.53]: ▸ BUILD SUCCESSFUL in 1m 37s
INFO [2018-09-05 14:05:34.53]: ▸ 59 actionable tasks: 58 executed, 1 up-to-date
INFO [2018-09-05 14:05:35.22]: ----------------------------------
INFO [2018-09-05 14:05:35.22]: --- Step: upload_to_play_store ---
INFO [2018-09-05 14:05:35.22]: ----------------------------------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------
Successfully loaded Appfile at path '/Users/user/project/fastlane/Appfile'
- json_key_file: 'fastlane/google_play.json'
- package_name: 'xxx.xxxxxxxxxxx.xxx'
-------

+-------------------------+-----------------------------------------------------------+
|                             Summary for supply 2.103.0                              |
+-------------------------+-----------------------------------------------------------+
| apk                     | /Users/user/project/app/build/outputs/apk/gene  |
|                         | ral/release/app-general-release-v1.0.apk                  |
| package_name            | xxx.xxxxxxxxxxx.xxx                                 |
| track                   | internal                                                  |
| skip_upload_metadata    | false                                                     |
| metadata_path           | ./fastlane/metadata/android                               |
| json_key                | fastlane/google_play.json                                 |
| skip_upload_apk         | false                                                     |
| skip_upload_aab         | false                                                     |
| skip_upload_images      | false                                                     |
| skip_upload_screenshots | false                                                     |
| validate_only           | false                                                     |
| check_superseded_tracks | false                                                     |
| timeout                 | 300                                                       |
+-------------------------+-----------------------------------------------------------+

DEBUG [2018-09-05 14:05:36.37]: Fetching a new access token from Google...
INFO [2018-09-05 14:05:37.86]: Preparing to upload for language 'ru-RU'...
INFO [2018-09-05 14:05:38.82]: Updating changelog for code version '19' and language 'ru-RU'...
INFO [2018-09-05 14:05:39.60]: Preparing apk at path '/Users/user/project/app/build/outputs/apk/general/release/app-general-release-v1.0.apk' for upload...
INFO [2018-09-05 14:05:44.66]: Updating track 'internal'...
INFO [2018-09-05 14:05:45.50]: Uploading all changes to Google Play...
WARN [2018-09-05 14:05:46.80]: Lane Context:
INFO [2018-09-05 14:05:46.80]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android internal", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/user/project/app/build/outputs/apk/develop/release/app-develop-release-v1.0.apk", "/Users/user/project/app/build/outputs/apk/general/release/app-general-release-v1.0.apk"], :GRADLE_ALL_AAB_OUTPUT_PATHS=>[], :GRADLE_APK_OUTPUT_PATH=>"/Users/user/project/app/build/outputs/apk/general/release/app-general-release-v1.0.apk"}
ERROR [2018-09-05 14:05:46.80]: Google Api Error: noShortDescription: This app has no short description (promotional text) for language ru_RU.
INFO [2018-09-05 14:05:46.81]: Successfully generated documentation at path '/Users/user/project/fastlane/README.md'

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | gradle               | 98          |
| 💥   | upload_to_play_store | 11          |
+------+----------------------+-------------+

ERROR [2018-09-05 14:05:46.81]: fastlane finished with errors
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: noShortDescription: This app has no short description (promotional text) for language ru_RU. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:398:in `rescue in call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:396:in `call_google_api'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/client.rb:118:in `commit_current_edit!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/supply/lib/supply/uploader.rb:43:in `perform_upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by janpio** [comment]
Ok, no useful output. 

The `INFO [2018-09-05 13:45:41.85]: Updating changelog for code version '19' and language 'ru-RU'...`  is confusing though - someone should look at the code of what is going on here. Is versionCode 19 somehow special?

**Comment by mrsolodov** [comment]
When i deleted project, clone it again and inited Fastlane, the versionCode was 19 in my project's code and also in published internal version.
Also 19 is the versionCode of first successful publish task via Fastlane (and generally first of any internal builds).
