### ISSUE TITLE
Match gets asked by apple for security questions

### ISSUE THREAD

**Issue by atomicus** [fastlane/fastlane#13289]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I know this is not a strictly related to fastlane and/or match, but out of nowhere apple asks for security questions during match auth phase.

Maybe some of you know how to fix it.

* Account was used for fastlane well for over a year
* Account has no 2FA enabled
* Account was made for CI only, it's not used for anything else.

#### Question Description

The related part of logs is:

```[11:14:14]: 🔓  Successfully decrypted certificates repo
[11:14:14]: Verifying that the certificate and profile are still valid on the Dev Portal...
Service key is empty
+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| ENVIRONMENT      | master        |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios hockeyapp |
+------------------+---------------+
[11:14:20]: Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>141, "question"=>"Who was your favorite singer or band in high school?", "number"=>1, "userDefined"=>false}, {"id"=>143, "question"=>"What was the first name of your first boss?", "number"=>2, "userDefined"=>false}]}, "rescueEmailAddress"=>"r•••••@jazzy.pro", "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"}```

**Comment by joshdholtz** [comment]
@atomicus We did swap from using the https://itunesconnect.apple.com API to https://appstoreconnect.apple.com API so this might be a weird side effect of that 🤔 Can you try a few more times for me and see if this goes away? (I know this sounds weird 😬 )

**Comment by dmitry-ivanov-rlt** [comment]
@joshdholtz have the same issue, tried a lot of times already :)

**Comment by joshdholtz** [comment]
😔 Going to close this issue and move this over to #13281 to keep all conversation in one place
