### ISSUE TITLE
Sigh Resigning with Fastlane after changing the bundle ID 

### ISSUE THREAD

**Issue by MirceaStroe** [fastlane/fastlane#13288]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The use case I'm trying to apply Fastlane to is as follows:

1. Build a master (original) ipa with bundle ID 1 which is signed with a Distribution Provisioning Profile A

2. The master ipa is processed by a Jenkins job that replaces various resources, customising the build for a specific app and performs a Fastlane resign with "sigh resign"
<at this point everything works as expected, regardless of the ipa being resigned with the initial Code Signing Identity or a different one, the build can be pushed to Testflight / AppStore succesfully and it works as expected>

3. The ipa generated at the previous step is unzipped and the team identifier associated with a Distribution Provisioning Profile B is manually updated in the Info & Entitlement.plist files. The initial bundle ID is also changed (the application_identifier in the Entitlement plist and the Bundle identifier in the Info plist). The ipa is packed up again and I manually resign it with Distribution Provisioning Profile B in the terminal (also with sigh resign). The resign is succesfull.

Now I attempt to upload the ipa generated at step 3 via AppLoader and I get resign errors on all frameworks, type:

"Invalid Code Signing Identity. The executable Payload/App name/Framework/.. must be signed with certificate that is contained in the provisioning profile"

Note: Both distribution provisioning profiles A & B are created under the same developer account.

The question is if Fastlane is expected to work in this fairly complicated scenario. 

Thanks!

**Comment by getaaron** [comment]
I haven’t worked with sigh resign much but check out https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/sigh/lib/sigh/resign.rb. It looks like it just resigns your IPA itself. But I think your app includes some frameworks with compiled binaries which are not being resigned by this command. So you would either need to manually resign those, or (preferably) update this code to look for nested binaries to resign for you also. All the binaries need to be signed with the same provisioning profile.
