### ISSUE TITLE
[Regression] [2.103.0] latest_testflight_build_number fails with privacy statement error

### ISSUE THREAD

**Issue by gobetti** [fastlane/fastlane#13282]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Description
Because we have `update_fastlane` in our Fastfile, our CI stopped working once 2.103.0 was released, with the following error log:
```
[19:42:45]: --- Step: latest_testflight_build_number ---
[19:42:45]: --------------------------------------------
[19:42:46]: Login to App Store Connect ([secure])
Service key is empty
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| DEFAULT_PLATFORM | ios        |
| PLATFORM_NAME    | ios        |
| LANE_NAME        | ios deploy |
| VERSION_NUMBER   | 1.4.0      |
+------------------+------------+
[19:42:50]: Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://appstoreconnect.apple.com) to acknowledge the statement.
[19:42:50]: fastlane finished with errors
```
Forcing the fastlane version back to 2.102.0 fixes the issue. Could this be related to 
#13272?

I am omitting further output for now in order to prevent posting sensitive information, but if this is not reproducible in other environments, let me know and I'll gladly share whatever is needed.

**Comment by chronweigle** [comment]
It could be related to #13272. The solution is simple, login to appstoreconnect.apple.com in a browser using the same account as your CI. There'll be a message for accepting the new license agreement.

**Comment by gobetti** [comment]
Hi @chronweigle, thanks for your reply! I understand it would be simple if I had access to that account, but in this project I actually depend on other teams who own this password and they already have a lot of communication to handle, so downgrading fastlane was definitely a faster solution. Also I assumed it was unintentional to start requiring all users to do a step they hadn't been required before, so I thought my best bet would be to share the issue here and together try to find a hybrid solution. Let me know if I can help any further. Thanks!

**Comment by janpio** [comment]
I agree with @chronweigle's assessment of the failure source, and also that theri PR #13286 should fix it. Thanks for reporting @gobetti, we will release an update as soon as possible.

**Comment by joshdholtz** [comment]
@gobetti This _should_ be fixed by this PR that I just merged in

**Comment by joshdholtz** [comment]
@gobetti Just released `2.103.1` - can you test this out to see if this fixes things for you?

**Comment by gobetti** [comment]
Just did - it worked great! Thank you very much all of you :)

**Comment by joshdholtz** [comment]
Woot! Glad to hear 😊 Ping me if you notice anything else
