### ISSUE TITLE
action about deleting invalid provisioning profile in dev portal?

### ISSUE THREAD

**Issue by plrthink** [fastlane/fastlane#1328]
Hi, folks, is there a approach or a fastlane action that can delete invalid provisioning profile in dev portal.
Since I am passing `force: true` option to sigh, there's a lot invalid provisioning profile remains. How can I delete those using faslane?

**Comment by cbowns** [comment]
`match nuke` should take care of cleaning out old profiles. https://github.com/fastlane/match#nuke

**Comment by plrthink** [comment]
@cbowns but it invalid all existing certificates and provisioning profiles, that's not what I want.

**Comment by KrauseFx** [comment]
Sorry, that's currently not implemented, however you can implement your own script using [spaceship](https://spaceship.airforce)

**Comment by plrthink** [comment]
@KrauseFx Yeah, I would have a try.
