### ISSUE TITLE
Fastlane sigh fails to reply to security questions

### ISSUE THREAD

**Issue by igorcferreira** [fastlane/fastlane#13292]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane sigh fails on `spaceship/two_step_client.rb:45:in 'handle_two_step'` by failing to reply to security questions:

```
[!] Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>139, "question"=>"<<QUESTION_1>>", "number"=>1, "userDefined"=>false}, {"id"=>131, "question"=>"<<QUESTION_2>>", "number"=>2, "userDefined"=>false}]}, "crResetEnabled"=>false}
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[13:03:51]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m

+-------------------------------------+---------------------------------+
|                       [32mSummary for sigh 2.103.0[0m                        |
+-------------------------------------+---------------------------------+
| username                            | <<username>>                    |
| team_id                             | <<team_id>>                     |
| app_identifier                      | <<app_identifier>>              |
| provisioning_name                   | <<provision_name>>              |
| filename                            | profile.mobileprovision         |
| ignore_profiles_with_different_name | true                            |
| skip_certificate_verification       | true                            |
| adhoc                               | false                           |
| development                         | false                           |
| skip_install                        | false                           |
| force                               | false                           |
| skip_fetch_profiles                 | false                           |
| platform                            | ios                             |
| readonly                            | false                           |
+-------------------------------------+---------------------------------+

[13:03:51]: Starting login with user '<<username>>'
Service key is empty

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	23: from /Users/igor/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	22: from /Users/igor/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	21: from /Users/igor/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	20: from /Users/igor/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	19: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/bin/fastlane:20:in `<top (required)>'
	18: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	17: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	16: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/sigh/lib/sigh/commands_generator.rb:138:in `run'
	15: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	13: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/sigh/lib/sigh/commands_generator.rb:60:in `block (2 levels) in run'
	 9: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/sigh/lib/sigh/manager.rb:8:in `start'
	 8: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/sigh/lib/sigh/runner.rb:19:in `run'
	 7: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
	 6: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	 5: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/client.rb:71:in `login'
	 4: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/client.rb:363:in `login'
	 3: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/client.rb:664:in `do_login'
	 2: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
	 1: from /Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/client.rb:463:in `send_shared_login_request'
/Users/igor/.rvm/gems/ruby-2.5.1/gems/fastlane-2.103.0/spaceship/lib/spaceship/two_step_client.rb:45:in `handle_two_step': [!] Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>134, "question"=>"<<QUESTION_1>>", "number"=>3, "userDefined"=>false}, {"id"=>131, "question"=>"<<QUESTION_2>>", "number"=>2, "userDefined"=>false}]}, "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"} (RuntimeError)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.2       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.3        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-09-05**
</details></pre>
</details>

**Comment by janpio** [comment]
The actual error is a bit earlier, "Service key is empty". 
There is already an issue for this at https://github.com/fastlane/fastlane/issues/13281

We are already working on a fix and testing it as we speak. Should be out soon.
