### ISSUE TITLE
One app, multiple Apple IDs for Continuous Deployment machine

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#13295]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Multiple AppleIDs for one target
I'm using Fastlane to distribute an iOS app to Crashlytics using a separate Continuous Deployment machine. I'd like it to have a separate AppleID and Certificate, independent of what developers use.

My FastFile is configured in the following fashion (unnecessary details ommited):

```Ruby
  desc "Submit a new Beta Build to Twitter Fabric, common methods for human and bot"
  lane :fabric_common do

    cert()
    sigh()

    #Disable bitcode to speedup build time
    includebitcode = false
    gym(scheme: "AppName",
    export_xcargs: "-allowProvisioningUpdates",
    include_symbols: true,
    include_bitcode: includebitcode,
      export_options: {
        compileBitcode: includebitcode,
        uploadBitcode: includebitcode
      }
    )

    crashlytics(
      crashlytics_path: './Pods/Crashlytics',
      api_token: 'Token',
      build_secret: 'Secret',
      groups: 'appgroup',
      notifications: false
    )

    upload_symbols_to_crashlytics(dsym_path: "./Appname.app.dSYM.zip")
  end
```

My AppFile looks like this:

```Ruby
app_identifier "AppID.iOS"
apple_id "developer@company.com" # This should change depending on the machine
```

I'd like to have a 2 apple IDs:
1. continuous.deployment@company.com for the CI machine
2. developer@company.com for the developer and if he/she distributes the app from a local machine

How that could be accomplished with the Fastlane?

**Comment by getaaron** [comment]
Yep, environment variables are the way to do this 👍🏼
