### ISSUE TITLE
Error while publishing app to testflight using adhoc------ "Provisioning profile is not an "iOS App Store" profile."

### ISSUE THREAD

**Issue by sushil-skycap123** [fastlane/fastlane#13294]
### Question Checklist

- [✅] Updated fastlane to the latest version
- [✅ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I am trying to upload Build on testFlight using AdHoc distribution certificate but When I build app through Jenkins, it fails with the below error

> error: exportArchive: Provisioning profile "myAdHoc_test" is not an "iOS App Store" profile.

This is the current content in my FastFile

```
default_platform(:ios)

platform :ios do    
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "testApp")
    gym(
    scheme: "testApp",
    export_options: {
    provisioningProfiles: {
      "com.testApp": "myAdHoc_test"
    }
  }
    )
    upload_to_testflight
  end
end
```

And here is few of my logs content

▸ Archive Succeeded
```
[13:50:59]: Generated plist file with the following values:
[13:50:59]: ▸ -----------------------------------------
[13:50:59]: ▸ {
[13:50:59]: ▸   "provisioningProfiles": {
[13:50:59]: ▸     "com.testApp": "myAdHoc_test"
[13:50:59]: ▸   },
[13:50:59]: ▸   "method": "app-store",
[13:50:59]: ▸   "signingStyle": "manual"
[13:50:59]: ▸ }



SLocalizedDescription=Provisioning profile "myAdHoc_test" is not an "iOS App Store" profile.}

** EXPORT FAILED **
[13:02:40]: [31mExit status: 70[0m

+---------------+-------------------------+
|            [32m[33mBuild environment[0m            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.103.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS11.3.sdk        |
+---------------+-------------------------+

```
In the logs, it shows method "app-store". I am wondering shouldn't it say "test-flight". I am not sure what  it means by method "app-store" and why it requires appStore provisioning profile. Because, it is possible to upload build on testFlight using AdHoc Distribution Certificate via Xcode.

**Comment by getaaron** [comment]
From https://help.apple.com/xcode/mac/current/#/devba5e7054d:

> You use an ad hoc provisioning profile to distribute your app to registered devices for testing.
>
> Note: As a member of the Apple Developer Enterprise Program, you don’t have an App Store Connect account and consequently, the ability to distribute an app using TestFlight.

From https://developer.apple.com/library/archive/technotes/tn2407/_index.html:

> Because apps submitted to TestFlight must be code signed with an App Store distribution provisioning profile, TestFlight cannot be used for the beta testing of Enterprise apps.

I'm not sure why you think you can build on TestFlight using an Ad Hoc cert. I can't find any docs that this is supported by TestFlight and I don't think fastlane supports it either.

**Comment by sushil-skycap123** [comment]
I think I have mixed the two things
Beta Testing 
and Internal testing

Can you please tell me how to release build for internal testers (on testFlight)?

**Comment by sushil-skycap123** [comment]
I don't want to send it to external testers an to apple for review. I just want to release it for Internal testers.
