### ISSUE TITLE
[BCEROR]Code Signing Error:" requires a provisioning profile

### ISSUE THREAD

**Issue by timrc** [fastlane/fastlane#13293]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
Command run: `fastlane staging_testing`

  <pre>
Building Staging
[✔] 🚀
[12:32:23]: fastlane detected a Gemfile in the current directory
[12:32:23]: however it seems like you don't use `bundle exec`
[12:32:23]: to launch fastlane faster, please use
[12:32:23]:
[12:32:23]: $ bundle exec fastlane staging_testing
[12:32:23]:
[12:32:23]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:32:25]: ------------------------------
[12:32:25]: --- Step: default_platform ---
[12:32:25]: ------------------------------
[12:32:25]: Driving the lane 'ios staging_testing' 🚀
[12:32:25]: -----------------------------
[12:32:25]: --- Step: update_fastlane ---
[12:32:25]: -----------------------------
[12:32:25]: Looking for updates for fastlane...
ERROR:  Loading command: update (Gem::LoadError)
    can't activate public_suffix-3.0.3, already activated public_suffix-2.0.5
ERROR:  Loading command: cleanup (Gem::LoadError)
    can't activate public_suffix-3.0.3, already activated public_suffix-2.0.5
[12:32:25]: It seems that your Gem directory is not writable by your current user.
[12:32:25]: fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
[12:32:25]: If you still want to use this action, please read the documentation on how to set this up:
[12:32:25]: https://docs.fastlane.tools/actions/#update_fastlane
[12:32:25]: -----------------------------------
[12:32:25]: --- Step: clean_build_artifacts ---
[12:32:25]: -----------------------------------
[12:32:25]: Cleaned up build artifacts 🐙
[12:32:25]: --------------------------------
[12:32:25]: --- Step: clear_derived_data ---
[12:32:25]: --------------------------------
[12:32:25]: Derived Data path located at: /Users/user/Library/Developer/Xcode/DerivedData
[12:32:25]: Successfully cleared Derived Data ♻️
[12:32:25]: -----------------------------------------------------
[12:32:25]: --- Step: Switch to ios assemble_testing_app lane ---
[12:32:25]: -----------------------------------------------------
[12:32:25]: Cruising over to lane 'ios assemble_testing_app' 🚖
[12:32:25]: Using profile
[12:32:25]: ------------------------------------
[12:32:25]: --- Step: automatic_code_signing ---
[12:32:25]: ------------------------------------

+-----------------------+-------------------------------+
|           Summary for Automatic Codesigning           |
+-----------------------+-------------------------------+
| path                  | App.xcodeproj                 |
| use_automatic_signing | false                         |
+-----------------------+-------------------------------+

[12:32:26]: Updating the Automatic Codesigning flag to disabled for the given project '/app/ios/App.xcodeproj/project.pbxproj'
[12:32:26]: Successfully updated project settings to use Code Sign Style = 'Manual'
[12:32:26]: Modified Targets:
[12:32:26]:      * AppTests
[12:32:26]:      * App
[12:32:26]:      * App-tvOS
[12:32:26]:      * App-tvOSTests
[12:32:26]:      * AppUITests
[12:32:26]: -------------------
[12:32:26]: --- Step: match ---
[12:32:26]: -------------------
[12:32:26]: Successfully loaded '/app/ios/fastlane/Matchfile' 📄

+----------------+--------------------------------------------------------+
|               Detected Values from './fastlane/Matchfile'               |
+----------------+--------------------------------------------------------+
| git_url        | https://github.com/company/certificates                |
| type           | development                                            |
| app_identifier | com.company.App                                        |
| username       | test@company.com                                       |
+----------------+--------------------------------------------------------+

+-----------------------+--------------------------------------------------------+
|                           Summary for match 2.103.0                            |
+-----------------------+--------------------------------------------------------+
| readonly              | true                                                   |
| type                  | appstore                                               |
| git_url               | https://github.com/company/certificates                |
| git_branch            | master                                                 |
| app_identifier        | ["com.company.App"]                                    |
| username              | test@company.com                                       |
| keychain_name         | login.keychain                                         |
| team_id               | EEXXXXXXXX                                             |
| verbose               | false                                                  |
| force                 | false                                                  |
| skip_confirmation     | false                                                  |
| shallow_clone         | false                                                  |
| clone_branch_directly | false                                                  |
| force_for_new_devices | false                                                  |
| skip_docs             | false                                                  |
| platform              | ios                                                    |
+-----------------------+--------------------------------------------------------+

[12:32:26]: Cloning remote git repo...
[12:32:26]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:32:27]: 🔓  Successfully decrypted certificates repo
[12:32:27]: Installing certificate...

+-------------------+-----------------------------------------------------------+
|                             Installed Certificate                             |
+-------------------+-----------------------------------------------------------+
| User ID           | EEXXXXXXXX                                                |
| Common Name       | iPhone Distribution: App Ltd (EEXXXXXXXX)                 |
| Organisation Unit | EEXXXXXXXX                                                |
| Organisation      | App Ltd                                                   |
| Country           | US                                                        |
| Start Datetime    | 2018-09-05 09:59:47 UTC                                   |
| End Datetime      | 2019-09-05 09:59:47 UTC                                   |
+-------------------+-----------------------------------------------------------+

[12:32:27]: Installing provisioning profile...

+---------------------+--------------------------------------------------------+--------------------------------------------------------+
|                                                    Installed Provisioning Profile                                                     |
+---------------------+--------------------------------------------------------+--------------------------------------------------------+
| Parameter           | Environment Variable                                   | Value                                                  |
+---------------------+--------------------------------------------------------+--------------------------------------------------------+
| App Identifier      |                                                        | com.company.App                                        |
| Type                |                                                        | appstore                                               |
| Platform            |                                                        | ios                                                    |
| Profile UUID        | sigh_com.company.App_apps                              | 12345678-1234-1234-1234-123456789012                   |
|                     | tore                                                   |                                                        |
| Profile Name        | sigh_com.company.App_apps                              | match AppStore                                         |
|                     | tore_profile-name                                      | com.company.App                                        |
| Profile Path        | sigh_com.company.App_apps                              | /Users/user/Library/MobileDevice/Provisioning          |
|                     | tore_profile-path                                      | Profiles/12345678-1234-1234-1234-123456789012.mobilep  |
|                     |                                                        | rovision                                               |
| Development Team ID | sigh_com.company.App_apps                              | EEXXXXXXXX                                             |
|                     | tore_team-id                                           |                                                        |
+---------------------+--------------------------------------------------------+--------------------------------------------------------+

[12:32:27]: All required keys, certificates and provisioning profiles are installed 🙌
[12:32:27]: Setting Provisioning Profile type to 'app-store'
[12:32:27]: ------------------------------
[12:32:27]: --- Step: get_certificates ---
[12:32:27]: ------------------------------

+---------------+--------------------------------------------------+
|                     Summary for cert 2.103.0                     |
+---------------+--------------------------------------------------+
| development   | false                                            |
| force         | false                                            |
| username      | test@company.com                                 |
| team_id       | EEXXXXXXXX                                       |
| keychain_path | /Users/user/Library/Keychains/login.keychain-db  |
| platform      | ios                                              |
+---------------+--------------------------------------------------+

[12:32:27]: Starting login with user 'test@company.com'
[12:32:31]: Successfully logged in
[12:32:32]: Certificate CXXXXXXXXX (iOS Distribution) can't be found on your local computer
[12:32:33]: Found the certificate FXXXXXXXXX (iOS Distribution) which is installed on the local machine. Using this one.
[12:32:33]: Verifying the certificate is properly installed locally...
[12:32:33]: Successfully installed certificate FXXXXXXXXX
[12:32:33]: Use signing certificate 'FXXXXXXXXX' from now on!
[12:32:33]: --------------------------------------
[12:32:33]: --- Step: get_provisioning_profile ---
[12:32:33]: --------------------------------------

+-------------------------------------+---------------------------------------------+
|                             Summary for sigh 2.103.0                              |
+-------------------------------------+---------------------------------------------+
| app_identifier                      | com.company.App                             |
| adhoc                               | false                                       |
| development                         | false                                       |
| skip_install                        | false                                       |
| force                               | false                                       |
| username                            | test@company.com                            |
| team_id                             | EEXXXXXXXX                                  |
| ignore_profiles_with_different_name | false                                       |
| cert_id                             | FXXXXXXXXX                                  |
| skip_fetch_profiles                 | false                                       |
| skip_certificate_verification       | false                                       |
| platform                            | ios                                         |
| readonly                            | false                                       |
+-------------------------------------+---------------------------------------------+

[12:32:33]: Starting login with user 'test@company.com'
[12:32:36]: Successfully logged in
[12:32:36]: Fetching profiles...
[12:32:37]: Provisioning Profile 'com.company.App AppStore' is not valid, skipping this one...
[12:32:38]: Verifying certificates...
[12:32:39]: Found 1 matching profile(s)
[12:32:39]: Downloading provisioning profile...
[12:32:40]: Successfully downloaded provisioning profile...
[12:32:40]: Installing provisioning profile...
/app/ios/AppStore_com.company.App.mobileprovision
[12:32:40]: Setting Provisioning Profile type to 'app-store'
[12:32:40]: ---------------------------
[12:32:40]: --- Step: build_ios_app ---
[12:32:40]: ---------------------------
[12:32:40]: $ xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme Staging -configuration Release
[12:32:43]: Detected provisioning profile mapping: {:"com.company.App"=>"match AppStore com.company.App"}

+---------------------------------------------------------------------------------+------------------------------------------------------------+
|                                                           Summary for gym 2.103.0                                                            |
+---------------------------------------------------------------------------------+------------------------------------------------------------+
| workspace                                                                       | App.xcworkspace                                            |
| scheme                                                                          | Staging                                                    |
| configuration                                                                   | Release                                                    |
| clean                                                                           | true                                                       |
| export_method                                                                   | development                                                |
| suppress_xcode_output                                                           | false                                                      |
| output_directory                                                                | ./build/                                                   |
| output_name                                                                     | Staging                                                    |
| export_options.provisioningProfiles.com.company.App                             | match AppStore com.company.App                             |
| destination                                                                     | generic/platform=iOS                                       |
| build_path                                                                      | /Users/user/Library/Developer/Xcode/Archives/2018-09-05    |
| silent                                                                          | false                                                      |
| skip_package_ipa                                                                | false                                                      |
| result_bundle                                                                   | false                                                      |
| buildlog_path                                                                   | ~/Library/Logs/gym                                         |
| skip_profile_detection                                                          | false                                                      |
| xcode_path                                                                      | /Applications/Xcode.app                                    |
+---------------------------------------------------------------------------------+------------------------------------------------------------+

[12:32:43]: $ set -o pipefail && xcodebuild -workspace App.xcworkspace -scheme Staging -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/user/Library/Developer/Xcode/Archives/2018-09-05/Staging\ 2018-09-05\ 12.32.43.xcarchive clean archive | tee /Users/user/Library/Logs/gym/App-Staging.log | xcpretty
[12:32:45]: ▸ Check Dependencies
....
[12:32:46]: ▸ Check Dependencies
[12:32:46]: ▸ Cleaning App/App [Release]
[12:32:46]: ▸ Check Dependencies
[12:32:46]: ▸ ❌  [BCEROR]Code Signing Error: "App" requires a provisioning profile with the Apple Pay and Push Notifications features. Select a provisioning profile for the "Release" build configuration in the project editor.
[12:32:46]: ▸ Cleaning App/AppTests [Release]

...

▸ Building App/App [Release]
▸ Check Dependencies

❌  Code Signing Error: "App" requires a provisioning profile with the Apple Pay and Push Notifications features. Select a provisioning profile for the "Release" build configuration in the project editor.

** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[12:35:33]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.103.0                 |
| export_method | development             |
| sdk           | iPhoneOS11.4.sdk        |
+---------------+-------------------------+

[12:35:33]: ▸ Check dependencies
[12:35:33]: ▸ Code Signing Error: "App" requires a provisioning profile with the Apple Pay and Push Notifications features. Select a provisioning profile for the "Release" build configuration in the project editor.
[12:35:33]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'
[12:35:33]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'
[12:35:33]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'
[12:35:33]:
[12:35:33]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[12:35:33]: 📋  For the complete and more detailed error log, check the full log at:
[12:35:33]: 📋  /Users/user/Library/Logs/gym/App-Staging.log
[12:35:33]:
[12:35:33]: Your `export_method` in gym is defined as `development`
[12:35:33]: which might cause problems when signing your application
[12:35:33]: Are you sure want to build and export for development?
[12:35:33]: Please make sure to define the correct export methods when calling
[12:35:33]: gym in your Fastfile or from the command line
[12:35:33]:
[12:35:33]:
[12:35:33]: Looks like fastlane ran into a build/archive error with your project
[12:35:33]: It's hard to tell what's causing the error, so we wrote some guides on how
[12:35:33]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[12:35:33]: Before submitting an issue on GitHub, please follow the guide above and make
[12:35:33]: sure your project is set up correctly.
[12:35:33]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[12:35:33]: the full commands printed out in yellow in the above log.
[12:35:33]: Make sure to inspect the output above, as usually you'll find more error information there
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.4       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-09-05**
</details>

### Fastfile

<details>
<pre>
#
# VARIABLES
#
staging_scheme = 'Staging'

default_platform(:ios)

platform :ios do

    #
    # INIT
    #
    before_all do
        update_fastlane
        clean_build_artifacts
        clear_derived_data
    end

    #
    # LANES - E2E
    #
    desc "Create a new testing build"
    private_lane :assemble_testing_app do |options|

        # use the UDID of the newly created provisioning profile
        ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
        puts "Using profile #{ENV["PROFILE_UDID"]}"

        disable_automatic_code_signing(path: "App.xcodeproj")

        match(
            readonly: true,
            type: "appstore"
        )
        get_certificates
        get_provisioning_profile(app_identifier: "com.company.App")
        build_ios_app(
            workspace: "App.xcworkspace",
            scheme: options[:scheme] || staging_scheme,
            configuration: 'Release',
            clean: true,
            export_method: 'development',
            suppress_xcode_output: false,
            output_directory:"./build/",
            output_name: options[:scheme] + ".ipa"
        
        enable_automatic_code_signing(path: "App.xcodeproj")
    end

    #
    # LANES - Staging
    #
    desc "New Staging build"
    lane :staging_testing do |options|
        assemble_testing_app(
            scheme: staging_scheme
        )
    end
end

</pre>
</details>

**Comment by timrc** [comment]
I tried with different options in the gym:
- setting export_options.provisioningProfiles to `"com.company.App" => "match Development com.company.App"`
- running with or without get_certificates and get_provisioning_profile
- setting configuration to Debug, Release
- setting export_method to development: app-store
- running match with type appstore, development and both or none

**Comment by timrc** [comment]
No matter what I do, I get `Code Signing Error: "App" requires a provisioning profile with the Apple Pay and Push Notifications features. Select a provisioning profile for the "Release" build configuration in the project editor.` or `Code Signing Error: "App" requires a provisioning profile with the Apple Pay and Push Notifications features. Select a provisioning profile for the "Debug" build configuration in the project editor.` if setting configuration to Debug

**Comment by timrc** [comment]
In my certificates repo I have
```
certs/development/LALA.cer
certs/development/LALA.p12
certs/distribution/LALA.cer
certs/distribution/LALA.p12
profiles/appstore/AppStore_com.company.App.mobileprovision
profiles/development/Development_com.company.App.mobileprovision
```
and I can see all of them being installed in my keychain when running match

**Comment by jdkanani** [comment]
Getting same error

**Comment by getaaron** [comment]
Does your provisioning profile have the entitlements specified in the error message?

**Comment by AshtonKem** [comment]
I'm having the same issue, but with Push Notifications alone instead of Apple Pay.

The provisioning profile has Push Notifications enabled according to my Apple Developer portal

![screen shot 2018-09-05 at 11 47 13 pm](https://user-images.githubusercontent.com/199201/45139923-317f3180-b166-11e8-9bf2-037ffa9da452.png)

And I have the capabilities set in XCode.

![screen shot 2018-09-05 at 11 48 52 pm](https://user-images.githubusercontent.com/199201/45139949-44920180-b166-11e8-886b-2db42fdf90ee.png)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "TriviaHedgeApp.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "TriviaHedgeApp.xcworkspace", scheme: "TriviaHedgeApp", xcargs: "-allowProvisioningUpdates",)
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.everest-agency.TriviaHedgeApp") # The bundle identifier of your app
apple_id("ashtonkemerling@gmail.com") # Your Apple email address

itc_team_id("119272006") # App Store Connect Team ID
team_id("YY47S6MTXV") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.1        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.8       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2018-09-05**
</details>

**Comment by timrc** [comment]
Yes, well I suppose so. I do have the two capabilities enabled. Comparing one generated using `fastlane match development`, and the one generated by xcode automatic signing, the two look the same. I would think that running `fastlane match development` and `fastlane match appstore` would generate the right provisioning profiles.

**Comment by AshtonKem** [comment]
I was under the impression that `fastlane match appstore` merely downloads and configures the provisioning keys. It doesn't actually change the provisioning profile _globally_.

**Comment by AshtonKem** [comment]
So, I figured it out.

The Bundle Identifier in XCode under the General tab did not match the Bundle Identifier that Fastlane was using. Take a look and make sure that both of those match.

**Comment by jdkanani** [comment]
@AshtonKem I have same Bundle Identifier and still the same error.
