### ISSUE TITLE
Prompt action is not working as expected with Jenkins  Shell and Groovy

### ISSUE THREAD

**Issue by vaibhavi-joshi** [fastlane/fastlane#1329]
When i execute Prompt action from terminal it waits for user input and working as expected.
When I try same action with Jenkins Execute shell or with workflow (Groovy file which will call fastlane prompt under sh command) , won't wait for user input, just prints the message on console and execute next command

I am newbie to FastLane and Jenkins, cant find any solution for this on google! can any one please provide a solution or root cause behind this behaviour! 

As far as i know jenkins shell is same as terminal shell !!!

**Comment by vpolouchkine** [comment]
Can you please share your setup? Versions, full log, Fastfile, etc.

**Comment by KrauseFx** [comment]
Yeah, this is by design, when running on Jenkins it can not receive any user input, so the action will just return an empty string.

**Comment by vaibhavi-joshi** [comment]
So is it possible to support Jenkins as well ?
Jenkins Pipeline provide one feature called "input" which allow manual intervention, i.e. Project manager's approval before distributing app !!! But i want to showcase it using FastFile. Is there any way to use Pipeline (or jenkins/cloubees) feature in our fastfile ???

**Comment by shaileshkanzariya** [comment]
Thanks @KrauseFx.
Can't we add support for that? That will be great feature to have and this will enable us to use Fastlane only for this and NOT non-fastlane tools.

**Comment by KrauseFx** [comment]
Sorry, this is currently not planned. However I'm more than happy to review any pull request adding this behavior. Check out [countdown](https://github.com/fastlane/countdown) on more information on how to contribute to `fastlane` :+1:
