### ISSUE TITLE
Automatically accept Apple's new privacy policy

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#13304]
### Feature Request
Automatically accept Apple's new privacy policy

#### Motivation Behind Feature
When a separate account is used for continuous integration machine, the user has to manually log in and accept a new privacy policy in order to release the build. This feature would give a new level of automation and remove the need to use manual labour.

The feature might be turned off by default, so the user could forward the new agreement to the legal department if needed.

#### Feature Description
```
[12:23:01]: Starting login with user 'apple-ci@google.com'
+------------------+----------------+
|           [33mLane Context[0m            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios fabric_bot |
+------------------+----------------+
[12:23:02]: [31mNeed to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement.[0m

```

#### Alternatives or Workarounds
Login and click through the privacy policy manually.

**Comment by Nov1kov** [comment]
probably it impossible do by itunes api. I using selenium for it. Tell me please, if I am wrong.

**Comment by richardtop** [comment]
@fastlane-bot doesn't work.

**Comment by richardtop** [comment]
@fastlane-bot doesn't work

**Comment by richardtop** [comment]
@fastlane-bot doesn't work.
