### ISSUE TITLE
xcode_server_get_assets failes to get the latest integration in After Trigger

### ISSUE THREAD

**Issue by appveng3r** [fastlane/fastlane#1330]
xcode_server_get_assets always uses the files of the integration before the current.
I use the action in the "After Integration Trigger" of the Xcode Server. Does anybody else sees the same problem? //cc @czechboy0

**Comment by czechboy0** [comment]
I think by then the integration isn't yet finished. This action is for downloading the archive from a separate machine (dev machine from the build machine, e.g.). If you have actions you want to run in the postbuild script, the archive's path should be in the env variable `XCS_ARCHIVE` and in the folder `XCS_OUTPUT_DIR`.

**Comment by appveng3r** [comment]
Thanks for the Information. Then I misunderstood the action. Works perfectly fine with the environment variables.
