### ISSUE TITLE
Supply seems to incorrectly deactivate lower tracks during rollout

### ISSUE THREAD

**Issue by tmtrademarked** [fastlane/fastlane#13313]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Supply appears to deactivate lower tracks when promoting to a new track. From what I can tell, this seems to result in APKs being unavailable to users who are whitelisted for the lower tracks.

Let's take an example here, where user A is whitelisted for the alpha track, but not the beta track. When an APK is promoted via supply from alpha to beta, we'd expect user A to be able to continue to receive the build. This doesn't appear to be the case - when looking at my Play Store console, it appears that the APK was removed from the alpha track during the promotion process.

I'm reasonably confident that this line (https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L67) is the source of this bug. It appears that Supply is *deliberately* clearing the original track when promoting, which appears to be causing unintentional behavior. Note that it doesn't matter if the user passes the `check_superseded_tracks` option or not - this happens *outside* of that block of logic.

It's possible that the behavior of the Google APIs have changed since this was authored two years ago - maybe it was necessary at one point? But it certainly seems like this is no longer needed.

I'd be happy to roll a PR adding a flag to bypass this line if we believe that's a reasonable fix. But I figured I would check with the experts here to see if my understanding is at all reasonable before attempting to fix.

**Comment by janpio** [comment]
Is there any reason why one would actually _want_ the current behavior?

**Comment by tmtrademarked** [comment]
Personally, I'm not sure the current behavior would ever really be desired. But maybe there's a specific reason out there with some setup of channels that would be helpful to have the deactivation. (Hard pressed to imagine a real use case, but I'm probably just being unimaginative)

**Comment by janpio** [comment]
I of course ask this because I saw you PR that adds a new option to get to the "probably correct" default state. If we really don't think anyone out there _really_ could expect this behavior with the current documentation, maybe we can just change the default behavior and add the option as a way to get the other behavior back if really wanted @joshdholtz ?

**Comment by tmtrademarked** [comment]
Sounds reasonable to me - I'm happy to make that change, but will leave that up to the core team's discretion here! Let me know if that's the direction we want to go, and what docs I should update.

**Comment by tmtrademarked** [comment]
Any updates here - I'd really like to get this submitted soon, since this is beginning to cause problems with our release process.

**Comment by joshdholtz** [comment]
@tmtrademarked I _thiiinnnkkkkk_ you are right. This is possibly started behaving differently/wrong after Google Play added more tracks and custom tracks 🧐 I would have to do some playing around with this but I _think_ it would probably be safe to see if removing that line fixes things.

IMO, that line seems like it has a little bit of a hack anyway so maybe its not needed anymore? If you want to try removing it and creating a PR and seeing if it works that would be 💯 Otherwise we may need to add an option for a track (or tracks) to demote 🤔

**Comment by tmtrademarked** [comment]
I've been running this locally for promoting my builds so far with the new option applied. (Effectively the same as just removing that line) So far, it seems to work just fine, and it matches my understanding of how this *should* work from the Play perspective.

My only concern here would be that removing that line *technically* results in a slight change in behavior. It's possible this breaks some workflow out there, although I'm hard pressed to imagine what could possibly be relying on this. 

So yeah - TLDR, I'm good with removing the line entirely and not adding the option if we think that's more correct. Just give me a thumbs up here if that's the approach we think makes the most sense, and I can update the PR.

**Comment by tmtrademarked** [comment]
For some evidence of this working, here's my Play release screen after using these changes:
![screen shot 2018-09-17 at 12 05 59 pm](https://user-images.githubusercontent.com/16063079/45635107-22f01e80-ba72-11e8-8975-2721cf16b6d2.png)

Before this change, the `Alpha` and `Beta` tracks would have had "fake" releases in them with a default name of the date - and notably, no binaries associated with them.

**Comment by joshdholtz** [comment]
@tmtrademarked If you wanna create a PR with this change that would be 💯 I would love to test it out 😊

**Comment by tmtrademarked** [comment]
Alright - #13351 has been updated. There's no more option, it just doesn't deactivate tracks when promoting.

**Comment by tmtrademarked** [comment]
@joshdholtz @janpio - any further thoughts here? (Sorry to keep nagging!)
