### ISSUE TITLE
Could not create another certificate, reached the maximum number of available certificates

### ISSUE THREAD

**Issue by Trane9991** [fastlane/fastlane#13318]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues). Related issues #3123 #3472

### Issue Description
Running `CERT_DEVELOPMENT=true fastlane cert` on 2 different devices with the same AppleID trying to create 2 Development certificates with the same name (`<AppleID user name>`) as the result command execution on one of the machines crashes with error `Could not create another certificate, reached the maximum number of available certificates`. But creating this certificate with XCode works because it names the certificates as `<AppleID user name> (<Device Name>)`.

Similar Issues exist when creating certificate manually with Apple Developers Portal, it automatically names the certificate with your username and when you are trying to generate the second one it returns the error `Maximum number of certificates generated`.

Is this related? Is Spaceship uses the above portal feature to generate the certificate or this can be fixed?

**Comment by gasziv131** [comment]
After running nuke im not able to recreate a Development cert. I the other hand im able to create Adhoc and Appstore.
