### ISSUE TITLE
Staged rollout percentage control

### ISSUE THREAD

**Issue by Salierik** [fastlane/fastlane#13311]
#### Motivation Behind Feature
The main problem of automatic android apps submission is halting previous rollout. So controlling of the Tracks would be very awesome!

Too many developers use Fastlane for release process automatisation and this is the awesome feature who will remove custom scripts with Google's SDK etc.

#### Feature Description
The main feature: Increase staged rollout percentage for selected Track (Production, Beta).
Something like that for Finish the rollout: 
`fastlane supply --track rollout --percentage 1 update-track`

#### Alternatives or Workarounds

Now it is possible only with manual actions in Google Play console or custom scripts who do it via [Publishing API](https://developers.google.com/android-publisher/).

**Comment by MartinGonzalez** [comment]
I have that issue too. I did a 5% rollout and worked fine, then i did a 20% rollout and rollout was halted in the dev console.
 Is ther eany fix for this?

**Comment by Salierik** [comment]
@MartinGonzalez , yes, **rollout**, sorry.

**Comment by Salierik** [comment]
UP

**Comment by Salierik** [comment]
UP

**Comment by Salierik** [comment]
UP!

**Comment by MartinGonzalez** [comment]
So basically you want to name the track you want to rollout right?

Can you have several rollouts in Google Play?
