### ISSUE TITLE
colored conflict with colorized

### ISSUE THREAD

**Issue by yishuiliunian** [fastlane/fastlane#13319]
### New Issue Checklist

- [V ] Updated fastlane to the latest version
```
➜  MacSwiss git:(master) ✗ fastlane --version
fastlane installation at path:
/Users/dongzhao/.rvm/gems/ruby-head/gems/fastlane-2.103.1/bin/fastlane
-----------------------------
[✔] 🚀
fastlane 2.103.1

```
- [ V] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [V ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [V ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane dependency a gem named "colored", it extension String class to output color. but the gem conflict with gem "coloried".

the method colorize defined both in colored and colorize, so it confuse which to use at runtime. in my try, it use colored one. but it only concept String params

```
  def colorize(string, options = {})
    colored = [color(options[:foreground]), color("on_#{options[:background]}"), extra(options[:extra])].compact * ''
    colored << string
    colored << extra(:clear)
  end
```
![image](https://user-images.githubusercontent.com/846525/45217217-d79d7980-b2d5-11e8-98ce-b7e6face794c.png)

##### Complete output when running fastlane, including the stack trace and command used

i use fastlane as a gem with 

```
require "fastlane"
```

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-head/bin/fastlane          |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-head/lib                 |
| OpenSSL Version             | OpenSSL 1.1.0i  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.1        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.8       |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| bundler                   | 1.16.4       |
| forwardable               | 1.2.0        |
| logger                    | 1.2.7        |
| ipaddr                    | 1.2.0        |
| openssl                   | 2.1.1        |
| ostruct                   | 0.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| rexml                     | 3.1.7.3      |
</details>

*generated on:* **2018-09-07**
</details></pre>
</details>

**Comment by janpio** [comment]
So you are also using the gem `coloried` in your app? 

Problem seems to be the `String.colorize` method is set in both, and fastlane can't really do anything to limit the scope of its `colored` use just to the fastlane gem - or can it? You might be able to manually overwrite `String.colorize` again after using fastlane (maybe by requiring the other gem again?).

**Comment by yishuiliunian** [comment]
I use 'ocoapods' in my app. it dependency 'colorize'. O check the gem 'colored' and 'colorized'. and 'colored' is very old (https://github.com/defunkt/colored). and the 'colorized' is newer (https://github.com/fazibear/colorize).  so  i have a advice ,  do you move to the 'colorized'? it can handle the confict.  please think about it.

btw: i overwrite the String.colorize and route the implimentation now. but it is very trick and dangerous.

**Comment by janpio** [comment]
We are pretty happy with `colored` - but if someone were to submit a Pull Request replacing it with `colorize`, no reason not to merge it I guess. It is the newer, maintained library so an improvement. Are you up to creating that PR?
