### ISSUE TITLE
FASTLANE_PASSWORD not working

### ISSUE THREAD

**Issue by bibekdari** [fastlane/fastlane#13317]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am using Jenkins for CI/CD, I get the error "Missing password for user tim.bib@gmail.com, and running in non-interactive shell" every time I try to build. I have set password using fastlane credential manager also but still I am getting the error. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[16:00:41]: [33mfastlane detected a Gemfile in the current directory[0m
[16:00:41]: [33mhowever it seems like you don't use `bundle exec`[0m
[16:00:41]: [33mto launch fastlane faster, please use[0m
[16:00:41]: 
[16:00:41]: [36m$ bundle exec fastlane env[0m
[16:00:41]: 
[16:00:41]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[16:00:41]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

PATH="/usr/local/bin:$PATH"

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "2.69.3"

default_platform :ios

platform :ios do

# increment_build_number
# enable_automatic_code_signing
#   build_app(
#    scheme: "B2",
#      workspace: "B2.xcworkspace",
##export_xcargs: "-allowProvisioningUpdates",
#      include_bitcode: true
#   )
    upload_to_testflight(
        username: "tim.bib@gmail.com"
    )
#   diawi(
#       token: "",
#       file: "B2.ipa"
#    )
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ek.ekder" # The bundle identifier of your app
apple_id "inf@ekna.com" # Your Apple email address

team_id "974PYWERWE" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.4       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.1        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.8       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| libxml-ruby               | 2.9.0        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-09-07**
</details>
[16:00:42]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[16:00:42]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m
[16:00:43]: [33mfastlane detected a Gemfile in the current directory[0m
[16:00:43]: [33mhowever it seems like you don't use `bundle exec`[0m
[16:00:43]: [33mto launch fastlane faster, please use[0m
[16:00:43]: 
[16:00:43]: [36m$ bundle exec fastlane [0m
[16:00:43]: 
[16:00:43]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[16:00:43]: [32m----------------------------------------[0m
[16:00:43]: [32m--- Step: Verifying fastlane version ---[0m
[16:00:43]: [32m----------------------------------------[0m
[16:00:43]: Your fastlane version 2.103.1 matches the minimum requirement of 2.69.3  ✅
[16:00:43]: [32m------------------------------[0m
[16:00:43]: [32m--- Step: default_platform ---[0m
[16:00:43]: [32m------------------------------[0m
[16:00:43]: [32m----------------------------------[0m
[16:00:43]: [32m--- Step: upload_to_testflight ---[0m
[16:00:43]: [32m----------------------------------[0m
[16:00:43]: Login to App Store Connect (tim.bib@gmail.com)
[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
[32mSee more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
[32m-------------------------------------------------------------------------------------[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': [31m[!] Missing password for user tim.bib@gmail.com, and running in non-interactive shell[0m (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/spaceship/lib/spaceship/client.rb:353:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/spaceship/lib/spaceship/client.rb:71:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/pilot/lib/pilot/manager.rb:23:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/pilot/lib/pilot/manager.rb:16:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/pilot/lib/pilot/build_manager.rb:13:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:117:in `platform'
	from Fastfile:21:in `parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:56:in `eval'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:56:in `block in parse'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:45:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:35:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane_manager.rb:16:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane_manager.rb:16:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
</pre>
</details>

**Comment by aln787** [comment]
What does your Jenkins execute shell contain?  

As a starting point you should address the warning in the log you provided.  Try using:

```
bundle install
bundle exec fastlane <lane name you wish to run>
```

**Comment by aln787** [comment]
Also how have you set the Fastlane credentials?  

Here is an example of how they should be set-up:
![screen shot 2018-09-07 at 7 45 38 am](https://user-images.githubusercontent.com/2243597/45217484-3a5d2980-b272-11e8-9a7b-4020b945fe1a.png)

**Comment by janpio** [comment]
> I have set password using fastlane credential manager also but still I am getting the error.

What does that mean exactly?

Could you please share all the details asked for in the issue template? We need more context to be able to analyze failures like this.
