### ISSUE TITLE
Is there a fastlane plugin for VMWare's AirWatch?

### ISSUE THREAD

**Issue by hisaac** [fastlane/fastlane#13312]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Is there a fastlane plugin for VMWare's AirWatch?

#### Question Description

We use AirWatch at my work to manage and deploy our internal iOS apps. I'd love to be able to integrate it with fastlane. According to the [`action_ranking.json`](https://github.com/fastlane/fastlane/blob/24fb2c9552a3367f41101764abf31ecc548e27d4/fastlane/assets/action_ranking.json#L1406) file, there is a plugin called `fastlane-plugin-airwatch`, but I can't find any other reference to it online. Is this a plugin that once existed, but is now deprecated?

**Comment by hisaac** [comment]
Dang, ok. Yeah, I wasn't sure what that `action_ranking.json` file was actually used for.

I'm going to be working on getting some sort of AirWatch integration with our CI/CD system, so if I figure it out, maybe it's something that I could add into Fastlane. ¯\\_(ツ)_/¯

**Comment by janpio** [comment]
Seems the `fastlane-plugin-airwatch` name is free to use 🚀

If you need any help, just create a new issue and ping me.

**Comment by hisaac** [comment]
Thanks @janpio, will do!

**Comment by jaleksynas** [comment]
It is possible that a plugin developed by others, but not released in open source, would report to action_ranking.json.
