### ISSUE TITLE
Capturing screenshots of Android toasts

### ISSUE THREAD

**Issue by AaronMT** [fastlane/fastlane#13358]
Currently if one wants to capture just a toast, a full-view screenshot is the default. It would be awesome if one can just capture a screenshot of a toast.

**Comment by janpio** [comment]
That seems out of scope for the screenshot functionality. It is meant to create screenshots for the stores. Screenshotting individual elements of a screen would require a lot of additional functionality to identify the elements and cropping the image created. You are probably better off, doing this in an additional step with some tool that can crop the screenshot created by fastlane.
