### ISSUE TITLE
Unsupported screen size [1242, 2688] (iPhone XS Max)

### ISSUE THREAD

**Issue by sisoje** [fastlane/fastlane#13355]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by sisoje** [comment]
We are missing iPhone XS Max screen size

**Comment by tattn** [comment]
I solved this problem 😄
https://github.com/fastlane/fastlane/pull/13366

**Comment by mirkokg** [comment]
These still need to be added to frameit though:

![apple iphone xs max gold](https://user-images.githubusercontent.com/1269927/45581727-9e4fa580-b8a3-11e8-813d-f6d6910c9548.png)
![apple iphone xs silver](https://user-images.githubusercontent.com/1269927/45581728-9e4fa580-b8a3-11e8-94d9-820d3f372833.png)
![apple iphone xs max silver](https://user-images.githubusercontent.com/1269927/45581729-9e4fa580-b8a3-11e8-950c-432254aa38d9.png)
![apple iphone xs gold](https://user-images.githubusercontent.com/1269927/45581730-9e4fa580-b8a3-11e8-9456-f74dbc58233c.png)

**Comment by tattn** [comment]
@mirkokg Oh, thank you!
Device frame images are generated by [frames_generator](https://github.com/fastlane/fastlane/tree/master/frameit/frames_generator).
The generator uses [Facebook frameset](http://facebook.design/devices), but the new device frames don't seem to be prepared yet...

**Comment by mirkokg** [comment]
Yeah, I'm aware of that, Facebook frameset was last updated on October 31st, 2017. That will probably take some time.

**Comment by mirkokg** [comment]
Added support for all of the devices: #13368
