### ISSUE TITLE
the Deliver build_number parameter does not uniquely specify which build to submit for review 

### ISSUE THREAD

**Issue by JimHowell20** [fastlane/fastlane#13356]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

According to the deliver docs, you can:

> Select a previously uploaded build and submit it for review.
> 
> fastlane deliver submit_build --build_number 830
> 

The issue with this is that the build number is only unique per version number.  So if you upload the following builds for example:

Version Number: 1.2.33
Build Number: 300

Version Number: 1.2.32
Build Number: 300

Version Number: 1.2.31
Build Number: 300

and then try to submit a previously uploaded build using:

 fastlane deliver submit_build --build_number 300

Then fastlane will not chose the latest build in this case.

This would be resolved if you could specify the "version_number" (CFBundleShortVersionString)  as well as the "build_number" (CFBundleVersion) in order to uniquely identify the build you're trying to submit for review.

**Comment by StefanoBiasu** [comment]
> This would be resolved if you could specify the "version_number" (CFBundleShortVersionString) as well as the "build_number" (CFBundleVersion) in order to uniquely identify the build you're trying to submit for review.

Apple shouldn't let you upload more than a single version of your app. You define beforehand the version to put to store, then you upload the ipa with the correct version, and the build number is the only discriminator between your uploads.

**Comment by JimHowell20** [comment]
The app store does allow you to upload multiple build versions with the same build number.   The build number only needs to be unique per build version.  There is no requirement to only upload a single build version before release.   The app submission metadata can only have a single version specified if that's what you mean, but that's not tied to the build version.  See the screenshot below:
<img width="811" alt="screen shot 2018-10-04 at 1 30 30 pm" src="https://user-images.githubusercontent.com/7559768/46491946-33c2c300-c7da-11e8-9073-8c3cfaadec5b.png">

**Comment by syedsmith** [comment]
is this issue solved now?
