### ISSUE TITLE
Fastlane init doesn't find app in ITC

### ISSUE THREAD

**Issue by focusedonfit** [fastlane/fastlane#1335]
On one of my projects when I run fastlane init it doesn't find the App Name or App Identifier. 
[14:10:21]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[14:10:21]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you

I'm not sure why this is occurring, anything I should be looking at to help troubleshoot?

Thank you

**Comment by vpolouchkine** [comment]
To confirm, your app has already been created manually (pre-fastlane)?

**Comment by focusedonfit** [comment]
Yes, it's been in the Appstore for almost a year.

**Comment by vpolouchkine** [comment]
Can you double check you're using the same Apple Id and App Id?

**Comment by focusedonfit** [comment]
Apple ID is the same, I'm not setting an AppID, The detected Values for App Name and App Identifier is empty. In other projects, fast lane detects this info correctly.

**Comment by vpolouchkine** [comment]
Can you please share the full output of `fastlane init`? Also, what are your user roles on Dev Center and iTC?

**Comment by focusedonfit** [comment]
I figured it out! 
I saw this error: [12:50:24]: xcrun xcodebuild -list -workspace './Simply Smoothies.xcworkspace'
xcodebuild: error: Scheme Smoothie Creator is not currently configured for the build action.
That scheme was from the original name of the project and no longer valid. Once I removed that scheme, fast lane detected everything correctly!
Thanks for your help.
