### ISSUE TITLE
Fastlane not working the Apperian plugin

### ISSUE THREAD

**Issue by atul7107** [fastlane/fastlane#13359]
Hello ,

I using the fastlane for by building , testing the iOS application and uploading the app to Hockey App , it works fine. Now I want to use fastlane to do auto deployment of app to Apperian store . I googled around the internet and found one plugin (https://github.com/tomiblank/fastlane-plugin-apperian). It is not able upload app to Apperian , there are not parameters defined for apperain api keys or token. Can some help me with this.

**Comment by janpio** [comment]
You should create an issue over at that plugin then: https://github.com/tomiblank/fastlane-plugin-apperian/issues

**Comment by atul7107** [comment]
Thanks for the comment , I would like to know is there any plugin with fastlane which supports the Apperian auto deployment of the app.
