### ISSUE TITLE
deliver fails to upload: Could not start delivery: all transports failed diagnostics

### ISSUE THREAD

**Issue by sumac13** [fastlane/fastlane#13398]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane deliver` is not completing successfully, however uploading through xCode 10 does work correctly. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[00:11:21]: Uploading binary to App Store Connect
[00:11:24]: Going to upload updated app to App Store Connect
[00:11:24]: This might take a few minutes. Please don't interrupt the script.
[00:13:46]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[00:13:46]: Transporter transfer failed.
[00:13:46]: 
[00:13:46]: Could not start delivery: all transports failed diagnostics
[00:13:46]: [iTMSTransporter] [2018-09-21 00:13:45 AEST] <Automatic reconnector> DEBUG: Transfer warning: Scheduling automatic restart in 1 minute

[00:13:46]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$2.run(TransferEngine.java:593)

[00:13:46]: [iTMSTransporter] 

[00:13:46]: [iTMSTransporter] [2018-09-21 00:13:45 AEST] <Automatic reconnector> DEBUG: Received failed transfer notification; aborting

[00:13:46]: [iTMSTransporter] [2018-09-21 00:13:45 AEST] <Automatic reconnector>  INFO: Scheduling automatic restart in 1 minute

[00:13:46]: [iTMSTransporter] [2018-09-21 00:13:46 AEST] <main> ERROR: Could not start delivery: all transports failed diagnostics

[00:13:46]: [iTMSTransporter] 

[00:13:46]: [iTMSTransporter] 

[00:13:46]: [iTMSTransporter] 

[00:13:46]: [iTMSTransporter] Package Summary:

[00:13:46]: [iTMSTransporter]  

[00:13:46]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[00:13:46]: [iTMSTransporter] 	/tmp/1218659851.itmsp - Error Messages:

[00:13:46]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics

[00:13:46]: [iTMSTransporter] [2018-09-21 00:13:46 AEST] <main> DBG-X: Returning 1

[00:13:46]: iTunes Transporter output above ^
[00:13:46]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    |             |
| LANE_NAME        | uploadStore |
+------------------+-------------+
[00:13:46]: Could not upload binary to App Store Connect. Check out the error above

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | deliver                    | 288         |
+------+----------------------------+-------------+

[00:13:46]: fastlane finished with errors
</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀 
[00:40:05]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[00:40:06]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.13.6 (17G2307)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :ios

lane :uploadStore do
deliver(
	username: "**************",
	force: true,
	app: "*******",
	metadata_path: "***********",
	screenshots_path: "**********")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.4       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.2        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-09-21**
</details></pre>
</details>

**Comment by askilondz** [comment]
This looks like a rehash of [11958]: https://github.com/fastlane/fastlane/issues/11958

I got this error today as well and resolved it by putting this in my Fastfile:
`ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"`

**Comment by IanHoar** [comment]
Same issue this morning.  I uploaded a build successfully yesterday afternoon, and this morning a second build for the same version failed.  No configuration changed between submissions

**Comment by DVSoftware** [comment]
Seems that the issue no longer occurs

**Comment by jromero** [comment]
Just got this issue today.
