### ISSUE TITLE
Using shared Apple ID for match, best practice of CI/CD with team.

### ISSUE THREAD

**Issue by marcuswu0814** [fastlane/fastlane#13409]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Hi everyone, I had some question about using match to manage cert. and provision profile, reference from [Code Signing Guide for Teams](https://codesigning.guide ),  I create a new Apple ID for my team, and I want to use this Apple ID for CI/CD and manage cert. by match.

If some days, a member leave my team, should I change password or do any other thing for this shared Apple ID? IMO, I don’t need to do any change for match, because the leave member can’t access the repo. of match used.  But leave member still know about shared Apple ID password and still can access iTunes connect and developer portal. So, what is the best practice when I doing CI/CD and manager cert. by using fastlane and match?

**Comment by tskulbru** [comment]
At my firm we change the match repo password when someone leaves. As for the shared appleid account, that password is stored in lastpass which will get shared to users who need it, without exposing password. That being said, we dont use that shared appleid for anything other than CI.

If thats best practice or not, idk. But it works great for us.
