### ISSUE TITLE
'$' was striped when passing parameter from the command line

### ISSUE THREAD

**Issue by 0x5e** [fastlane/fastlane#13408]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm passing value from command line but the value I get from lane is wrong.

Here's my lane:
```
lane :test do |c|
	value = c[:key]
	puts value
end
```

And run this:
`fastlane test key:"abcd 1234$efgh"`

Then output is only `abcd 1234`, not `abcd 1234$efgh`.

##### Complete output when running fastlane, including the stack trace and command used
» fastlane test key:"abcd 1234$efgh" --capture_output
[⠴] 🚀 NOTE: Gem.gunzip is deprecated; use Gem::Util.gunzip instead. It will be removed on or after 2018-12-01.
Gem.gunzip called from /usr/local/lib/ruby/gems/2.5.0/gems/unicode-display_width-1.3.0/lib/unicode/display_width/index.rb:5.
[✔] 🚀
[14:38:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-09-21 14:38:08.04]: Checking if there are any plugins that should be loaded...
DEBUG [2018-09-21 14:38:08.17]: Using key: abcd 1234
INFO [2018-09-21 14:38:08.45]: gem 'credentials_manager' is already installed
INFO [2018-09-21 14:38:08.45]: Driving the lane 'test' 🚀
INFO [2018-09-21 14:38:08.45]: abcd 1234
INFO [2018-09-21 14:38:08.45]: Successfully generated documentation at path '/Users/admin/Project/xxx/fastlane/README.md'
INFO [2018-09-21 14:38:08.45]: fastlane.tools finished successfully 🎉

**Comment by heartofagoof** [comment]
What I think is happening is this : 

when you run `fastlane test key:"abcd 1234$efgh"` shell is evaluating $efgh and since a variable of name efgh does not exist in the shell it's empty. 

To cross check that it is what's happening, I'd advise doing something like `export efgh=omgurright"`. And then running the command, you should see `abcd 1234omgurright`

This is the quirk of the shell not of fastlane itself. You need to escape $ for the shell. I looked into the fastlane code and i don't think fastlane worries about $ too much.

**Comment by 0x5e** [comment]
@heartofagoof thanks for your reply, actually I'm passing value from python to fastlane:
```python
subprocess.check_call('fastlane run import_certificate certificate_path:%s certificate_password:%s'%(json.dumps(cert_path), json.dumps(cert_password)), shell=True)
```

Everything goes fine until last week, a p12 file with '$' password failed to import. Now I know what to do, thanks again!
