### ISSUE TITLE
Add testers to existing build

### ISSUE THREAD

**Issue by GregTheGreek** [fastlane/fastlane#13406]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 Is there a way that I can add testers to an existing build?

#### Question Description
Is there a way to use pilot to add testers to an existing build on itunes connect?

**Comment by heartofagoof** [comment]
You can use command `:add` with appropriate inputs. This action can add testers ( internal/external) to a group. If this group is added to the build already ( like pilot would ) then the tester will be invited to that build ( as far as i can tell ).

**Comment by GregTheGreek** [comment]
Do you have a link to it? Can't seem to find it

**Comment by janpio** [comment]
https://docs.fastlane.tools/actions/pilot/#add-a-new-tester

**Comment by awgeorge** [comment]
@janpio Can you only add testers via the command line?

I'm trying this, but it fails as I'm not supplying an IPA

```
pilot(
      username: ENV["APP_STORE_USERNAME"],
      app_identifier: options[:app_identifier],
      testers_file_path: './fastlane/testers/' + options[:group] + '.csv',
      groups: [options[:group]]
    )
```

**Comment by janpio** [comment]
Yes @awgeorge, as far as I can see this is not available as a fastlane action but only via the command line tool `fastlane pilot`.
