### ISSUE TITLE
Update MiniMagick to 4.9.0 

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13410]
https://github.com/minimagick/minimagick/releases/tag/v4.9.0

Supports ImageMagick 7, which moved some things around.
Should probably check commands used here in code as well.

**Comment by sorianog** [comment]
@janpio Were you able to follow @fastlane-bot's request?

**Comment by sorianog** [comment]
@janpio Bad joke I guess 😞

**Comment by janpio** [comment]
I certainly didn't get it...
Sometimes @fastlane-bot is not the smartest. But we let him be, he's useful.

**Comment by janpio** [comment]
Found a code comment in one of my WIP branches that is relevant here:

```
      ...
      @image = MiniMagick::Image.open(screenshot.path)
      # TODO This throws "ImageMagick/GraphicsMagick is not installed" on Windows if no ImageMagick is installed
      # This should be handled better somehow - maybe during `frameit` loading/startup check already if MiniMagick is happy?
      # Install ImageMagick 6 (!)
      # https://legacy.imagemagick.org/script/download.php#windows
      # Install ImageMagick 7 and set checkbox "Install legacy utilities (e.g. convert)" during installation
      # https://imagemagick.org/script/download.php#windows

```
Source: frameit\lib\frameit\editor.rb
