### ISSUE TITLE
team id configuration

### ISSUE THREAD

**Issue by frranck** [fastlane/fastlane#1341]
How to avoid the "Multiple teams found on the Developer Portal, please enter the number of the team you want to use:" message in produce, sight, etc ?
Which global variable should I set ?
Thanks

**Comment by vpolouchkine** [comment]
You can pass `--team_id` to `produce` for example.

**Comment by KrauseFx** [comment]
Also, check out the Appfile docs: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
