### ISSUE TITLE
[Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)

### ISSUE THREAD

**Issue by jpghelfi** [fastlane/fastlane#13423]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
It's wierd. It´s not the first time I'm integrating fastlane. When it´s trying to upload the build to testflight, it ask me to enter the username (my Apple ID email I guess), and the password.. but it´s not working. 2FA It´s disable

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>➜  reponame git:(master) ✗ fastlane upload_ipa
[✔] 🚀 
[13:32:41]: ------------------------------
[13:32:41]: --- Step: default_platform ---
[13:32:41]: ------------------------------
[13:32:41]: Driving the lane 'ios upload_ipa' 🚀
[13:32:41]: ----------------------------------
[13:32:41]: --- Step: upload_to_testflight ---
[13:32:41]: ----------------------------------
[13:32:42]: Login to App Store Connect (myname@gmail.com)
[13:32:50]: Login successful
[13:32:51]: Ready to upload new build to TestFlight (App: 1437144293)...
[13:32:52]: Going to upload updated app to App Store Connect
[13:32:52]: This might take a few minutes. Please don't interrupt the script.
[13:33:09]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Username: myname@gmail.com
The login credentials for 'myname@gmail.com' seem to be wrong
Do you want to re-enter your password? (y/n)
y
Removing Keychain entry for user 'myname@gmail.com'...
keychain: "/Users/myname/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="deliver.myname@gmail.com"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="myname@gmail.com"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138303932343134353132385A00  "20180924145128Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138303932343134353132385A00  "20180924145128Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="deliver.myname@gmail.com"
    "type"<uint32>=<NULL>
password has been deleted.
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for myname@gmail.com): **********
[13:33:30]: Please run this tool again to apply the new password
[13:33:30]: [Transporter Error Output]: Error while processing package 1437144293.itmsp
[13:33:30]: Transporter transfer failed.
[13:33:30]: 
[13:33:30]: Your Apple ID or password was entered incorrectly. (-20101)
Error while processing package 1437144293.itmsp
[13:33:30]: [iTMSTransporter] [2018-09-24 13:33:09 ART] <main> DBG-X:   parameter ErrorCode = -20101

[13:33:30]: [iTMSTransporter] [2018-09-24 13:33:09 ART] <main> DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)

[13:33:30]: [iTMSTransporter] [2018-09-24 13:33:09 ART] <main> DBG-X:   parameter Success = false

[13:33:30]: [iTMSTransporter] [2018-09-24 13:33:09 ART] <main> ERROR: Your Apple ID or password was entered incorrectly. (-20101)

[13:33:30]: [iTMSTransporter] [2018-09-24 13:33:09 ART] <main> ERROR: Error while processing package 1437144293.itmsp

[13:33:30]: [iTMSTransporter] 

[13:33:30]: [iTMSTransporter] 

[13:33:30]: [iTMSTransporter] 

[13:33:30]: [iTMSTransporter] Package Summary:

[13:33:30]: [iTMSTransporter]  

[13:33:30]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[13:33:30]: [iTMSTransporter] 	/var/folders/1m/ntfwgz996sd2788yj62lc5y40000gn/T/d20180924-64797-cnui2s/1437144293.itmsp - Error Messages:

[13:33:30]: [iTMSTransporter] 		Your Apple ID or password was entered incorrectly. (-20101)

[13:33:30]: [iTMSTransporter] 		Error while processing package 1437144293.itmsp

[13:33:30]: [iTMSTransporter] [2018-09-24 13:33:09 ART] <main> DBG-X: Returning 1

[13:33:30]: iTunes Transporter output above ^
[13:33:30]: Your Apple ID or password was entered incorrectly. (-20101)
Error while processing package 1437144293.itmsp
Return status of iTunes Transporter was 1: Your Apple ID or password wa\nError while processing package 1437144293.itmsp
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios upload_ipa |
+------------------+----------------+
[13:33:30]: Error uploading ipa file, for more information see above

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 💥   | upload_to_testflig  | 48          |
|      | ht                  |             |
+------+---------------------+-------------+

[13:33:30]: fastlane finished with errors

[!] Error uploading ipa file, for more information see above</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.13.4                                       |
| Ruby                        | 2.4.2                                         |
| Bundler?                    | true                                          |
| Git                         | git version 2.13.5 (Apple Git-94)             |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane           |
| Host                        | Mac OS X 10.13.4 (17E199)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                  |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                    |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode90.app/Contents/Developer/ |
| Xcode Version               | 9.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	build_number = latest_testflight_build_number.to_i
  	ENV['FASTLANE_PASSWORD'] = 'jpyiooOO11'
  	ENV['DELIVER_PASSWORD'] = 'jpyiooOO11'
  	increment_build_number(build_number:  build_number + 1, xcodeproj: "Revista Palabras.xcodeproj")
  	ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
    build_app(workspace: "Revista Palabras.xcworkspace", scheme: "Revista Palabras")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :upload_ipa do
  	upload_to_testflight(skip_waiting_for_build_processing: true,
    	ipa: 'Revista Palabras.ipa')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.jp.revistapalabras") # The bundle identifier of your app
apple_id("myname@gmail.com") # Your Apple email address

itc_team_id("118759032") # App Store Connect Team ID
team_id("9DMM723BKP") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.2        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-09-24**
</details>

**Comment by jpghelfi** [comment]
Same issue : https://github.com/fastlane/fastlane/issues/13053

@KrauseFx  help us please!! thanks a lot

**Comment by jpghelfi** [comment]
Solved! delete the keychain password, and now it works!!

**Comment by yuanjilee** [comment]
password in keychain?  Can you describe the whole detail you did, thanks.
