### ISSUE TITLE
Allow to pass 2-factor auth code via command line argument

### ISSUE THREAD

**Issue by helloagain-dev** [fastlane/fastlane#13429]
#### Motivation Behind Feature
We have some clients, which use an individual developer account, so we are forced to build with a 2-factor authentication enabled account. This breaks our automated builds on Jenkins. We have looked into the solutions offered here: https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth

However, we have so many clients, that generating a token every month is very unpractical. Also our staff, which is responsible for building is not usually familiar with command line tools.

Therefore we wanted to include a Jenkins build step where they can enter the verification code received via SMS (https://jenkins.io/doc/pipeline/steps/pipeline-input-step/).
This does not work, because the input of fastlane waits and the input step is never called. Another more sophisticated option would be to register a SMS number that is connected via an API.

In order to do that we need the option to pass the verification code via command line.

This allows us the semi- or even fully automatize our build process.

#### Feature Description
Add an option to spaceauth that only requests the 2-factor authentication:
fastlane spaceauth --request-only -u user@email.com

This starts the 2-factor authentication process

In a second step I can call spaceauth again with the token:
fastlane spaceauth --auth-token A434GC -u user@email.com

The first call should either exit with a specific code or output a message to indicate that the 2-factor authentication process has started

#### Alternatives or Workarounds
Right now we have to connect to our build-server and call fastlane spaceauth from the command line manually as often as the session expires. We have several hundred Apps that get updated automatically, which can take a lot of time.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                        |
| Ruby                        | 2.5.1                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Ubuntu 18.04.1 LTS debian_based buster/sid (4.15.0-34-generic) |
| Ruby Lib Dir                | /usr/lib                                                       |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.5       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.10.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-10-01**
</details>

**Comment by AmauriC** [comment]
This will be very usefull.

Any tip on how I can enter the 2FA code remotely?
