### ISSUE TITLE
new format of UDID for Apple Watch Series 4 is not recognised

### ISSUE THREAD

**Issue by tompson** [fastlane/fastlane#13439]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I tried to add the UDID of my Apple Watch Series 4 to the devices.txt file and create new provisioning profiles

it looks like the format changed from the 40 character hex string like

e188d1db0d434695ffc0fc51812fbdf34aca6d9b

to 

00004016-002B2E022EA2001D

While it is possible to register the Watch in the Web Portal it is not possible to register it via fastlane

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
[11:04:21]: ----------------------------------------
[11:04:21]: --- Step: Verifying fastlane version ---
[11:04:21]: ----------------------------------------
[11:04:21]: Your fastlane version 2.105.2 matches the minimum requirement of 1.104.0  ✅
[11:04:21]: ------------------------------
[11:04:21]: --- Step: default_platform ---
[11:04:21]: ------------------------------
[11:04:21]: Driving the lane 'ios devices' 🚀
[11:04:21]: -----------------------
[11:04:21]: --- Step: xcversion ---
[11:04:21]: -----------------------
[11:04:22]: Setting Xcode version to /Applications/Xcode-10.app for all build steps
[11:04:22]: ------------------------------
[11:04:22]: --- Step: register_devices ---
[11:04:22]: ------------------------------
[11:04:25]: Fetching list of currently registered devices...

+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios devices |
+------------------+-------------+
[11:04:26]: Invalid device line, please provide a file according to the Apple Sample UDID file (http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip)

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | xcversion                  | 0           |
| 4    | ./replace_commit_hash.sh   | 0           |
| 💥   | register_devices           | 3           |
| 6    | ./revert_commit_hash.sh    | 0           |
+------+----------------------------+-------------+

[11:04:26]: fastlane finished with errors

[!] Invalid device line, please provide a file according to the Apple Sample UDID file (http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.14                                          |
| Ruby                        | 2.5.1                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.19.0                             |
| Installation Source         | /usr/local/bin/fastlane                        |
| Host                        | Mac OS X 10.14 (18A391)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib               |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode-10.app/Contents/Developer/ |
| Xcode Version               | 10.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.10.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.4.4        |
</details>

*generated on:* **2018-09-26**
</details></pre>
</details>

**Comment by janpio** [comment]
Yes, it is very possible that #13407 didn't touch the code you are executing or the regex doesn't match or something similar - someone will have to look into that.

**Comment by dkpalmer** [comment]
I just came across the UDID format change. Running `register_device` worked for me with 2.105.2.

**Comment by tompson** [comment]
tried it again, it worked, must have been a mistake in the format of the line (tab vs. space)
