### ISSUE TITLE
Add option to swiftlint action to pipe output to a file

### ISSUE THREAD

**Issue by gretzki** [fastlane/fastlane#1343]
In order to further process the result of the swiftlint action, I think it comes in handy to pass an argument specifying a report file to which the output is piped to.

That way, the lane definition can stay much cleaner and leaves the shell kungfu to the action definitions.
Proposal as pull request here: https://github.com/fastlane/fastlane/pull/1342

Cheers,
Chris :)

**Comment by vpolouchkine** [comment]
Great idea! I will share this with the team and see what we can do in a future release. I’ll reopen this ticket and keep you updated when we get a chance to revisit this, stay tuned :+1: If you want to tackle this yourself, check out the [countdown](https://github.com/fastlane/countdown) repo.
