### ISSUE TITLE
Fastlane does not recognize utf8

### ISSUE THREAD

**Issue by pickfire** [fastlane/fastlane#13438]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`export LANG=en_US.UTF-8` works but `export LANG=en_US.utf8` does not which should work as well.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
[16:38:00]: fastlane detected a Gemfile in the current directory
[16:38:00]: however it seems like you don't use `bundle exec`
[16:38:00]: to launch fastlane faster, please use
[16:38:00]:
[16:38:00]: $ bundle exec fastlane capture_output
[16:38:00]:
[16:38:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:38:00]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
+-----------------------+---------+--------+
|               Used plugins               |
+-----------------------+---------+--------+
| Plugin                | Version | Action |
+-----------------------+---------+--------+
| fastlane-plugin-ionic | 0.0.4   | ionic  |
+-----------------------+---------+--------+

[!] Could not find 'capture_output'. Available lanes: ios deploy, android deploy
[16:38:00]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀
[16:54:20]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[16:54:20]: Generating fastlane environment output, this might take a few seconds...
cat: /etc/issue.net: No such file or directory
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value
                                              |
| --------------------------- | ---------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux cti 4.18.8-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 15 20:34:48 UTC 2018 x86_64 GNU/Linux                       |
| Ruby                        | 2.5.1
                                              |
| Bundler?                    | true
                                              |
| Git                         | git version 2.19.0
                                              |
| Installation Source         | ~/.gem/bin/fastlane
                                              |
| Host                        | Linux cti 4.18.8-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 15 20:34:48 UTC 2018 x86_64 GNU/Linux (4.18.8-arch1-1-ARCH) |
| Ruby Lib Dir                | /usr/lib
                                              |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018
                                              |
| Is contained                | false
                                              |
| Is homebrew                 | false
                                              |
| Is installed via Fabric.app | false
                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  desc "Deploy ios app on the appstore"

  lane :deploy do
    match(type: "appstore")
    ionic(platform: 'ios')
    deliver(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :deploy do
    ionic(
      platform: 'android',
      keystore_path: './file.keystore',
      keystore_alias: 'alias',
      keystore_password: 'password'
    )
    supply(apk: './platforms/android/app/build/outputs/apk/release/app-release.apk')
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-ionic | 0.0.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.16.5       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.10.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-ionic     | 0.0.4        |
</details>

*generated on:* **2018-09-26**
</details>
[16:54:21]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[16:54:21]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
[16:54:21]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
</pre>
</details>

**Comment by pickfire** [comment]
@janpio Thanks a lot for suggesting the fix. I have fixed it using `locale` instead.

**Comment by janpio** [comment]
That looks even better ;)

**Comment by pickfire** [comment]
@janpio Updated the patch, please review it again.

**Comment by pickfire** [comment]
@janpio Any update?

**Comment by pickfire** [comment]
@janpio Can we merge this?
