### ISSUE TITLE
Xcode exporting

### ISSUE THREAD

**Issue by maurovc** [fastlane/fastlane#13435]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The app gets archived but not exported

##### Complete output when running fastlane, including the stack trace and command used
`INFO [2018-09-25 17:54:46.46]: $ set -o pipefail && xcodebuild -workspace ./Glovo\ Customer.xcworkspace -scheme Customer\ \β -destination 'generic/platform=iOS' -archivePath /Users/Mauro/Library/Developer/Xcode/Archives/2018-09-25/Glovo\ 2018-09-25\ 17.54.46.xcarchive clean archive CODE_SIGN_IDENTITY=iPhone\ Distribution:\ Glovoapp23\ SL | tee /Users/Mauro/Library/Logs/gym/Glovo-Customer\ \β.log | xcpretty
INFO [2018-09-25 17:54:47.38]: ▸ Could not find unf_ext-0.0.7.5 in any of the sources
INFO [2018-09-25 17:54:47.38]: ▸ Run `bundle install` to install missing gems.
Could not find unf_ext-0.0.7.5 in any of the sources
Run `bundle install` to install missing gems.
ERROR [2018-09-25 18:10:39.64]: Exit status: 7

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.105.2                 |
| export_method | enterprise              |
| sdk           | iPhoneOS12.0.sdk        |
+---------------+-------------------------+

WARN [2018-09-25 18:10:39.73]: Lane Context:
INFO [2018-09-25 18:10:39.73]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
INFO [2018-09-25 18:10:39.73]: Successfully generated documentation at path '/Users/Mauro/Glovo_iOS_Customer/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | carthage         | 26          |
| 3    | cocoapods        | 13          |
| 💥   | gym              | 969         |
+------+------------------+-------------+

ERROR [2018-09-25 18:10:39.82]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `each' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60each%27%20for%20nil+repo:fastlane/fastlane
➡️  Support for test-only runs for Snapshot using test binary only
    https://github.com/fastlane/fastlane/issues/12723 [closed] 10 💬
    a week ago

➡️  Type Checking error: got 'Fixnum' for attribute 'fileEncoding' and undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11016 [closed] 5 💬
    19 Jun 2018

➡️  undefined method `each' for #<Enumerable::Enumerator:0x007f9c8b6d87b8>
    https://github.com/fastlane/fastlane/issues/11114 [closed] 12 💬
    01 Jun 2018

and 135 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60each%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `each' for nil:NilClass
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/gym/lib/gym/error_handler.rb:147:in `print_full_log_path'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/gym/lib/gym/error_handler.rb:59:in `handle_build_error'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/gym/lib/gym/runner.rb:97:in `block in build_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/gym/lib/gym/runner.rb:93:in `build_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/gym/lib/gym/runner.rb:18:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/gym/lib/gym/manager.rb:19:in `work'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/build_ios_app.rb:64:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:77:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14 (18A389)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  ENV["GYM_WORKSPACE"] = "./Glovo\ Customer.xcworkspace"

  # Beta release lane
  desc "Creates Beta Live build for Customer App and uploads to Hockey"
  lane :beta do
    carthage(command: "bootstrap",
             platform: "iOS",
             use_binaries: false)
             
    cocoapods

    gym(scheme: "Customer β",
        clean: true,
        codesigning_identity: "IDENTITY",
        include_symbols: true,
        include_bitcode: false,
        export_method: "enterprise",
        skip_profile_detection: true,
		export_options:{
			compileBitcode: false,
			signingStyle: "manual",
  			provisioningProfiles:{
    				"com.glovo.glovoent": "Customer In House Live",
    				"com.glovo.glovoent.GlovoIntents": "Customer Intents In House Live",
    				"com.glovo.glovoent.GlovoIntentsUI": "Customer IntentsUI In House Live",
    				"com.glovo.glovoent.GlovoiMessage": "Customer iMessage In House Live"
  			}
		})

    hockey(api_token: "TOKEN",
           notify: "0",       # Notify testers? "1" for yes
           status: "1",       # Download status: "1" = No user can download; "2" = Available for download
           release_type: "3", # Enterprise
           mandatory: "1",
           notes: "#5.5.0 Test Fastlane")
  end
  
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXXXXXXX"       # The bundle identifier of your app

apple_dev_portal_id "XXXXXXXX"  # Apple Developer Account
itunes_connect_id "XXXXXXXXX"     # App Store Connect Account

team_id "XXXXXXXX" # Developer Portal Team ID

for_platform :ios do
  
  for_lane :beta do
  	team_id 'XXXXXXXX' # for all iOS related things
    app_identifier 'XXXXXXXX'
  end
  
end

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.10.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-09-27**
</details>

**Comment by maurovc** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14 (18A389)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  ENV["GYM_WORKSPACE"] = "./Glovo\ Customer.xcworkspace"

  # Beta release lane
  desc "Creates Beta Live build for Customer App and uploads to Hockey"
  lane :beta do
    carthage(command: "bootstrap",
             platform: "iOS",
             use_binaries: false)
             
    cocoapods

    gym(scheme: "Customer β",
        clean: true,
        codesigning_identity: "IDENTITY",
        include_symbols: true,
        include_bitcode: false,
        export_method: "enterprise",
        skip_profile_detection: true,
		export_options:{
			compileBitcode: false,
			signingStyle: "manual",
  			provisioningProfiles:{
    				"com.glovo.glovoent": "Customer In House Live",
    				"com.glovo.glovoent.GlovoIntents": "Customer Intents In House Live",
    				"com.glovo.glovoent.GlovoIntentsUI": "Customer IntentsUI In House Live",
    				"com.glovo.glovoent.GlovoiMessage": "Customer iMessage In House Live"
  			}
		})

    hockey(api_token: "TOKEN",
           notify: "0",       # Notify testers? "1" for yes
           status: "1",       # Download status: "1" = No user can download; "2" = Available for download
           release_type: "3", # Enterprise
           mandatory: "1",
           notes: "#5.5.0 Test Fastlane")
  end
  
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXXXXXXX"       # The bundle identifier of your app

apple_dev_portal_id "XXXXXXXX"  # Apple Developer Account
itunes_connect_id "XXXXXXXXX"     # App Store Connect Account

team_id "XXXXXXXX" # Developer Portal Team ID

for_platform :ios do
  
  for_lane :beta do
  	team_id 'XXXXXXXX' # for all iOS related things
    app_identifier 'XXXXXXXX'
  end
  
end

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.10.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2018-09-27**
</details>

**Comment by fishercraigj** [comment]
same issue here.
