### ISSUE TITLE
fastlane nuke development asks to remove certificates for another bundle id

### ISSUE THREAD

**Issue by bsarrazin** [fastlane/fastlane#13446]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running the command `bundle exec fastlane nuke development` asks to remove certificates for a bundle id that isn't specified in the `Matchfile`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ bundle exec fastlane match nuke development
[✔] 🚀
[17:10:29]: Successfully loaded '/Users/bsarrazin/Development/<REDACTED>/<REDACTED>/fastlane/Matchfile' 📄

+----------------+-------------------------------------------------------------------------+
|                       Detected Values from './fastlane/Matchfile'                        |
+----------------+-------------------------------------------------------------------------+
| app_identifier | ["<REDACTED>"]                                                          |
| git_url        | <REDACTED>-codesigning.git                                              |
| type           | development                                                             |
| username       | <REDACTED>                                                              |
+----------------+-------------------------------------------------------------------------+

[17:10:29]: Cloning remote git repo...
[17:10:29]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[17:10:30]: 🔓  Successfully decrypted certificates repo

+-----------------------+-------------------------------------------------------------------------+
|                                 Summary for match nuke 2.105.1                                  |
+-----------------------+-------------------------------------------------------------------------+
| git_url               | <REDACTED>-codesigning.git                                              |
| git_branch            | master                                                                  |
| type                  | development                                                             |
| username              | <REDACTED>                                                              |
| keychain_name         | login.keychain                                                          |
| readonly              | false                                                                   |
| team_id               | <REDACTED>                                                              |
| verbose               | false                                                                   |
| force                 | false                                                                   |
| skip_confirmation     | false                                                                   |
| shallow_clone         | false                                                                   |
| clone_branch_directly | false                                                                   |
| force_for_new_devices | false                                                                   |
| skip_docs             | false                                                                   |
| platform              | ios                                                                     |
+-----------------------+-------------------------------------------------------------------------+

[17:10:30]: Fetching certificates and profiles...

+-----------------+------------+-------------+------------+
|        Certificates that are going to be revoked        |
+-----------------+------------+-------------+------------+
| Name            | ID         | Type        | Expires    |
+-----------------+------------+-------------+------------+
| iOS Development | MZYLWFFJDC | Development | 2019-09-20 |
| iOS Development | L72D7A8Y4H | Development | 2019-09-24 |
+-----------------+------------+-------------+------------+

+------------------------------------------------+------------+---------+-----------------+------------+
|                          Provisioning Profiles that are going to be revoked                          |
+------------------------------------------------+------------+---------+-----------------+------------+
| Name                                           | ID         | Status  | Type            | Expires    |
+------------------------------------------------+------------+---------+-----------------+------------+
| <REDACTED>                                     | GW8W6923Y6 | Active  | iOS Development | 2019-09-21 |
| <REDACTED>                                     | 86QM2R5W26 | Active  | iOS Development | 2019-08-06 | <-- DIFFRENT BUNDLE ID, SHOULDN'T BE DELETED
+------------------------------------------------+------------+---------+-----------------+------------+

+---------------------+-----------------------------------------------+
|                 Files that are going to be deleted                  |
+---------------------+-----------------------------------------------+
| Type                | File Name                                     |
+---------------------+-----------------------------------------------+
| development cert    | <REDACTED>.cer                                |
| development cert    | <REDACTED>.p12                                |
| development profile | Development_<REDACTED>.mobileprovision |
+---------------------+-----------------------------------------------+

[17:10:33]: ---
[17:10:33]: Are you sure you want to completely delete and revoke all the
[17:10:33]: certificates and provisioning profiles listed above? (y/n)
[17:10:33]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
[17:10:33]: ---
[17:10:33]: Do you really want to nuke everything listed above? (y/n)
</pre>
</details>

### Environment

[✔] 🚀
[17:18:06]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.13.6 (17G2307)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
fastlane_version "2.95.0"

fastlane_require 'json'

platform :ios do

  # --------------------------------------------------
  # Set Up & Tear Down
  # --------------------------------------------------

  before_all do |lane, options|
  end

  after_all do |lane, options|
  end

  # --------------------------------------------------
  # Lanes
  # --------------------------------------------------

  import "lanes/build.rb"
  import "lanes/coverage.rb"
  import "lanes/enterprise.rb"
  import "lanes/metadata.rb"
  import "lanes/mock.rb"
  import "lanes/release.rb"
  import "lanes/symbols.rb"
  import "lanes/testflight.rb"
  import "lanes/tests.rb"

  # --------------------------------------------------
  # Error Handling
  # --------------------------------------------------

  error do |lane, exception, options|
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<REDACTED>"
apple_id "<REDACTED>"
team_id "<REDACTED>"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.105.1 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                         | Version | Update-Status |
| ---------------------------------------------- | ------- | ------------- |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-test_center                    | 3.5.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                            | Version      |
| ---------------------------------------------- | ------------ |
| did_you_mean                                   | 1.2.0        |
| bundler                                        | 1.16.5       |
| CFPropertyList                                 | 2.3.6        |
| concurrent-ruby                                | 1.0.5        |
| i18n                                           | 0.9.5        |
| minitest                                       | 5.11.3       |
| thread_safe                                    | 0.3.6        |
| tzinfo                                         | 1.2.5        |
| activesupport                                  | 4.2.10       |
| public_suffix                                  | 2.0.5        |
| addressable                                    | 2.5.2        |
| atomos                                         | 0.1.3        |
| babosa                                         | 1.0.2        |
| claide                                         | 1.0.2        |
| clamp                                          | 0.6.5        |
| fuzzy_match                                    | 2.0.4        |
| nap                                            | 1.1.0        |
| cocoapods-core                                 | 1.5.3        |
| cocoapods-deintegrate                          | 1.0.2        |
| cocoapods-downloader                           | 1.2.1        |
| cocoapods-plugins                              | 1.0.0        |
| cocoapods-search                               | 1.0.0        |
| cocoapods-stats                                | 1.0.0        |
| netrc                                          | 0.11.0       |
| cocoapods-trunk                                | 1.3.1        |
| cocoapods-try                                  | 1.1.0        |
| colored2                                       | 3.1.2        |
| escape                                         | 0.0.4        |
| fourflusher                                    | 2.0.1        |
| gh_inspector                                   | 1.1.3        |
| molinillo                                      | 0.6.6        |
| ruby-macho                                     | 1.2.0        |
| nanaimo                                        | 0.2.6        |
| xcodeproj                                      | 1.6.0        |
| cocoapods                                      | 1.5.3        |
| colored                                        | 1.2          |
| highline                                       | 1.7.10       |
| commander-fastlane                             | 4.4.6        |
| declarative                                    | 0.0.10       |
| declarative-option                             | 0.1.0        |
| unf_ext                                        | 0.0.7.5      |
| unf                                            | 0.1.4        |
| domain_name                                    | 0.5.20180417 |
| dotenv                                         | 2.5.0        |
| emoji_regex                                    | 0.1.1        |
| excon                                          | 0.62.0       |
| multipart-post                                 | 2.0.0        |
| faraday                                        | 0.15.3       |
| http-cookie                                    | 1.0.3        |
| faraday-cookie_jar                             | 0.0.6        |
| faraday_middleware                             | 0.12.2       |
| fastimage                                      | 2.1.4        |
| jwt                                            | 2.1.0        |
| memoist                                        | 0.16.0       |
| multi_json                                     | 1.13.1       |
| os                                             | 1.0.0        |
| signet                                         | 0.9.2        |
| googleauth                                     | 0.6.6        |
| httpclient                                     | 2.8.3        |
| mime-types-data                                | 3.2018.0812  |
| mime-types                                     | 3.2.2        |
| uber                                           | 0.1.0        |
| representable                                  | 3.0.4        |
| retriable                                      | 3.1.2        |
| google-api-client                              | 0.23.9       |
| json                                           | 2.1.0        |
| mini_magick                                    | 4.5.1        |
| multi_xml                                      | 0.6.0        |
| plist                                          | 3.4.0        |
| rubyzip                                        | 1.2.2        |
| security                                       | 0.1.3        |
| naturally                                      | 2.2.0        |
| simctl                                         | 1.6.5        |
| slack-notifier                                 | 2.3.2        |
| terminal-notifier                              | 1.8.0        |
| unicode-display_width                          | 1.4.0        |
| terminal-table                                 | 1.8.0        |
| tty-screen                                     | 0.6.5        |
| tty-cursor                                     | 0.6.0        |
| tty-spinner                                    | 0.8.0        |
| word_wrap                                      | 1.0.0        |
| rouge                                          | 2.0.7        |
| xcpretty                                       | 0.3.0        |
| xcpretty-travis-formatter                      | 1.0.0        |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1        |
| xctest_list                                    | 1.1.4        |
| fastlane-plugin-test_center                    | 3.5.7        |
| mini_portile2                                  | 2.3.0        |
| nokogiri                                       | 1.8.4        |
| slather                                        | 2.4.6        |
</details>

*generated on:* **2018-09-26**
</details>

**Comment by KrauseFx** [comment]
I think this is part of the output

> 17:10:33: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!

Maybe we should make the message more clear? As `fastlane match nuke` will revoke the certificates, all provisioning profiles will therefore get invalidated.

**Comment by bsarrazin** [comment]
@KrauseFx what is the correct way to set things up? Our org is using the same AppStore account for multiple apps. Other teams aren't using `fastlane` yet and I'm implementing it for my team. I really don't want to impact other teams in the same account.

It would be really useful for the nuke command to take the content of the `Matchfile` into account and only manage the certs that are associated with the bundle ids in that file.

Thoughts?
