### ISSUE TITLE
How silent is --silent ?

### ISSUE THREAD

**Issue by JesseScott** [fastlane/fastlane#13443]
The **Gym** action details that there is a _silent_ flag that "Hide all information that's not necessary while building"

I have set this to be true, but still get pages and pages of console output which seems to be the same regardless of how the flag is set.

What exactly is silent supposed to filter? And am I experiencing an anomaly (FL v 2.102.0) or are other people seeing this too? (I don't see any previous issues about this...)

**Comment by JesseScott** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

I wasn't sure that this was necessary for this question... happy to do so if needed though...

**Comment by ppamorim** [comment]
@JesseScott I agree with you, the "silent" mode is way too verbose.

**Comment by KrauseFx** [comment]
Hey that's a great question, could you prepare a list of things that you want to be hidden when using the `silent` flag, and we can make sure to update _gym_ to consider this 👍

**Comment by JesseScott** [comment]
Wait! I will get to this week!

**Comment by JesseScott** [comment]
@KrauseFx 
Really thinking about this some more, ultimately what I would like to see within Fastlane (as a whole, not just the Gym action) is a more detailed Linux-style log level subsystem --> ie. 
* `Log.Level.None`
* `Log.Level.Debug`
* `Log.Level.Info`
* `Log.Level.Warning`
* `Log.Level.Error`
... and this could be set within the `before_all` lane... and potentially overridden by each action, Eg.

```
before_all do
    Log.Level.Error

end

lane build do
    Gym(
        log_level: Info
    )
end
```

Failing that (as i understand this likely means a fairly large refactor to the way Fastlane handles logging, grepping from subsystems, piping to files, etc...), Silent should actually mean silent (logically), but I don't feel that this would be too useful for most users, so I think it should default to the "Info" level.

This level I imagine as simply annotating the switching of lanes, context headers, and lane results 
(think the ASCII table as seen in the docs at https://docs.fastlane.tools/actions/gym/ and then the final output of the lane... and that's it, none of the `xcodebuild` output...)

**Comment by JesseScott** [comment]
Still active!

**Comment by adrivernetta** [comment]
> @KrauseFx
> Really thinking about this some more, ultimately what I would like to see within Fastlane (as a whole, not just the Gym action) is a more detailed Linux-style log level subsystem --> ie.
> 
> * `Log.Level.None`
> * `Log.Level.Debug`
> * `Log.Level.Info`
> * `Log.Level.Warning`
> * `Log.Level.Error`
> ...
> This level I imagine as simply annotating the switching of lanes, context headers, and lane results
> (think the ASCII table as seen in the docs at https://docs.fastlane.tools/actions/gym/ and then the final output of the lane... and that's it, none of the `xcodebuild` output...)

This is exactly what I thought the --silent command actually did, as a matter of fact, so I find this approach by JesseScott an amazing suggestion to improve logging within Fastlane

**Comment by JesseScott** [comment]
Bump

**Comment by JesseScott** [comment]
Bump
