### ISSUE TITLE
Fastlane hangs forever on fresh Xcode 10 install

### ISSUE THREAD

**Issue by shepting** [fastlane/fastlane#13445]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When resetting simulators, the job hangs forever.

This occurs on Xcode 10 machines after it has first been installed if the `xcodebuild -runFirstLaunch` has not been run. This is only really an issue on CI machines, as local engineers always hit the "Install Command-Line Tools" prompt when it shows up.

##### Complete output when running fastlane, including the stack trace and command used
```
SNAPSHOT_FORCE_DELETE=true bundle exec fastlane snapshot reset_simulators
--
  | [✔] 🚀
```

Then it hangs forever.

If run without the `SNAPSHOT_FORCE_DELETE=true` we get a better idea of what's likely happening.

```
xcodebuild[11305:3136758]  DVTDownloadable: Failed to get authorization with error Error Domain=DVTDownloadableErrors Code=3 "The authorization was denied since no user interaction was possible." UserInfo={AuthorizationErrorCode=-60007, NSLocalizedDescription=The authorization was denied since no user interaction was possible.}
xcodebuild: error: The authorization was denied since no user interaction was possible.
```

### Environment

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-store_sizer | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-bugsnag     | 1.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| bundler                     | 1.16.1       |
| io-console                  | 0.4.5        |
| rake                        | 12.3.1       |
| CFPropertyList              | 3.0.0        |
| concurrent-ruby             | 1.0.5        |
| i18n                        | 0.9.5        |
| minitest                    | 5.11.3       |
| thread_safe                 | 0.3.6        |
| tzinfo                      | 1.2.5        |
| activesupport               | 4.2.10       |
| public_suffix               | 2.0.5        |
| addressable                 | 2.5.2        |
| ast                         | 2.4.0        |
| atomos                      | 0.1.3        |
| aws-eventstream             | 1.0.0        |
| aws-partitions              | 1.89.1       |
| aws-sigv4                   | 1.0.2        |
| jmespath                    | 1.4.0        |
| aws-sdk-core                | 3.21.2       |
| aws-sdk-kms                 | 1.5.0        |
| aws-sdk-s3                  | 1.10.0       |
| babosa                      | 1.0.2        |
| debug_inspector             | 0.0.3        |
| binding_of_caller           | 0.8.0        |
| multipart-post              | 2.0.0        |
| faraday                     | 0.15.3       |
| sawyer                      | 0.8.1        |
| buildkit                    | 1.3.0        |
| claide                      | 1.0.2        |
| fuzzy_match                 | 2.0.4        |
| nap                         | 1.1.0        |
| cocoapods-core              | 1.3.1        |
| cocoapods-deintegrate       | 1.0.2        |
| cocoapods-downloader        | 1.2.1        |
| cocoapods-plugins           | 1.0.0        |
| cocoapods-search            | 1.0.0        |
| cocoapods-stats             | 1.0.0        |
| netrc                       | 0.11.0       |
| cocoapods-trunk             | 1.3.0        |
| cocoapods-try               | 1.1.0        |
| colored2                    | 3.1.2        |
| escape                      | 0.0.4        |
| fourflusher                 | 2.0.1        |
| gh_inspector                | 1.1.3        |
| molinillo                   | 0.5.7        |
| ruby-macho                  | 1.2.0        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.6.0        |
| cocoapods                   | 1.3.1        |
| coderay                     | 1.1.2        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| diff-lcs                    | 1.3          |
| multi_json                  | 1.13.1       |
| dogapi                      | 1.29.0       |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20180417 |
| dotenv                      | 2.5.0        |
| emoji_regex                 | 0.1.1        |
| excon                       | 0.62.0       |
| facter                      | 2.5.1        |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.12.2       |
| fastimage                   | 2.1.4        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| os                          | 1.0.0        |
| signet                      | 0.10.0       |
| googleauth                  | 0.6.6        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2018.0812  |
| mime-types                  | 3.2.2        |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.23.9       |
| json                        | 2.1.0        |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.4.0        |
| rubyzip                     | 1.2.2        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.5        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 1.8.0        |
| unicode-display_width       | 1.4.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.6.5        |
| tty-cursor                  | 0.6.0        |
| tty-spinner                 | 0.8.0        |
| word_wrap                   | 1.0.0        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| git                         | 1.4.0        |
| xml-simple                  | 1.1.5        |
| fastlane-plugin-bugsnag     | 1.3.4        |
| fastlane-plugin-store_sizer | 0.2.0        |
| gli                         | 2.17.1       |
| hashie                      | 3.5.7        |
| htmlentities                | 4.3.4        |
| interception                | 0.5          |
| method_source               | 0.9.0        |
| mini_portile2               | 2.3.0        |
| nokogiri                    | 1.8.3        |
| octokit                     | 4.9.0        |
| parallel                    | 1.12.1       |
| parser                      | 2.5.1.0      |
| powerpack                   | 0.1.1        |
| pry                         | 0.11.3       |
| pry-rescue                  | 1.4.5        |
| pry-stack_explorer          | 0.4.9.2      |
| rainbow                     | 3.0.0        |
| redcarpet                   | 3.4.0        |
| rspec-support               | 3.7.1        |
| rspec-core                  | 3.7.1        |
| rspec-expectations          | 3.7.0        |
| rspec-mocks                 | 3.7.0        |
| rspec                       | 3.7.0        |
| ruby-progressbar            | 1.9.0        |
| rubocop                     | 0.56.0       |
| websocket-extensions        | 0.1.3        |
| websocket-driver            | 0.7.0        |
| slack-ruby-client           | 0.11.1       |
| vcr                         | 4.0.0        |
</details>

*generated on:* **2018-09-26**
</details>

**Comment by shepting** [comment]
Also, I don't think it hangs without the `SNAPSHOT_FORCE_DELETE=true`. It just isn't able to reset the simulators. Which is reasonable, and would be the ideal case.

**Comment by KrauseFx** [comment]
`SNAPSHOT_FORCE_DELETE` will just skip the confirmation step of _fastlane_ which asks you if you really want to delete all the simulators, so it shouldn't change the behavior of the actual thing.

**Comment by shepting** [comment]
Right, but in this case it also hid the logs with the ```xcodebuild[11305:3136758]  DVTDownloadable: Failed to get authorization with error Error Domain=DVTDownloadableErrors Code=3 "The authorization was denied since no user interaction was possible." UserInfo={AuthorizationErrorCode=-60007, NSLocalizedDescription=The authorization was denied since no user interaction was possible.}
xcodebuild: error: The authorization was denied since no user interaction was possible.``` error.

**Comment by shepting** [comment]
I love the feature by the way! This is super handy, and has saved use loads of time and effort and hand-wringing over the years.

**Comment by shepting** [comment]
I'm even fine if we close the issue as "unlikely to happen to others" . Just wanted the Github SEO to archive this for the public.

**Comment by nartiles** [comment]
We got hit by this also. Thanks for the tread with info.
