### ISSUE TITLE
SCP action doesn't allow patterns usage in paths

### ISSUE THREAD

**Issue by tomassliz** [fastlane/fastlane#1345]
I would like to copy multiple files with `scp`. With current implementation I have to specify special `src` line for each file. I can copy whole directory but I wish to copy only some files.

Here is the example, instead of this:
```ruby
scp(
   username: "tomas",
   host: "awesomeserver.com",
   upload: {
     src: "build/app1.ipa",
     src: "build/app2.ipa",
     src: "build/app3.ipa",
     dst: "/some/directory/"
   }
)
```
I would like to use this:
```ruby
scp(
   username: "tomas",
   host: "awesomeserver.com",
   upload: {
     src: "build/app*.ipa",
     dst: "/some/directory/"
   }
)
```

**Comment by vpolouchkine** [comment]
Great idea! I will share this with the team and see what we can do in a future release. I’ll reopen this ticket and keep you updated when we get a chance to revisit this, stay tuned :+1: If you want to tackle this yourself, check out the [countdown](https://github.com/fastlane/countdown) repo.

**Comment by hjanuschka** [comment]
a quick review showed that this would require to patch the net-scp gem.
as a workaround you could do the file-globing with normal ruby 

```
Dir.glob("*.txt").each do | file |
scp(
   username: "tomas",
   host: "awesomeserver.com",
   upload: {
     src: file,
     dst: "/some/directory/"
   }
)
end
```


or you shell out and call the scp your self using `sh`

**Comment by tomassliz** [comment]
Yes, this workaround is a temporary solution. I'm using shell with `scp` but there is a problem with password because `scp` does not have parameter for password. But thank you! The workaround is all I need at this moment.
