### ISSUE TITLE
Lazy loading for actions

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13455]
Currently _fastlane_ loads (`require`) all >200 actions and their helpers on each startup:
https://github.com/fastlane/fastlane/blob/1a0969d276a2a52ef493474b483283100993f675/fastlane/lib/fastlane.rb#L36-L44

This is not necessary and could be switched to a kind of "lazy loading", so the file is only loaded if the action it contains was actually called.

Executing actions from lanes happens here:
https://github.com/fastlane/fastlane/blob/1a0969d276a2a52ef493474b483283100993f675/fastlane/lib/fastlane/fast_file.rb#L148-L151
https://github.com/fastlane/fastlane/blob/1a0969d276a2a52ef493474b483283100993f675/fastlane/lib/fastlane/runner.rb#L125-L176
which ends up loading the action class here:
https://github.com/fastlane/fastlane/blob/1a0969d276a2a52ef493474b483283100993f675/fastlane/lib/fastlane/actions/actions_helper.rb#L79-L90
We would probably have to try to `require` the class in there, then continue as before.

This change might be pretty complex as there are lots of variations and entry points to this logic that has to be covered.

---
Notes: Plugins, local actions, switching lanes, variables that look like actions

**Comment by KrauseFx** [comment]
Yeah, this would be amazing. All the above information looks correct 👍 

In general, as you said, we will run into edge cases. For example `fastlane actions` to list the available actions and their available parameters.
