### ISSUE TITLE
Using Crashlytics Beta and setting notifications to YES or true is not triggering notifications.

### ISSUE THREAD

**Issue by brunorend** [fastlane/fastlane#1346]
Using latest version of Fastlane (v1.6.0) after building the app with Gym I call:

```	
crashlytics(
	  crashlytics_path: './Crashlytics.framework',
	  api_token: 'token',
	  build_secret: 'secret',
 	  ipa_path: './build/App.ipa',
 	  groups: 'internal',
 	  notifications: true
	)
```

It is uploading and adding the testers group successfully but is not sending any notifications. Same issue was happening before updating Fastlane (v1.59.0). Not sure if its a bug or if I'm doing something wrong.

Similar to issue #583 

[11:36:21]: ▸ 2016-02-18 11:36:21.100 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (15)
[11:36:26]: ▸ 2016-02-18 11:36:26.007 submit Crashlytics: Added Testers/Groups Successfully 200
[11:36:51]: ▸ 2016-02-18 11:36:51.881 submit Crashlytics: Uploaded Successfully 202
[11:36:51]: Build successfully uploaded to Crashlytics Beta

**Comment by brunorend** [comment]
I realised the problem was happening because of wrong provisioning profiles, after using cert and sigh this is no longer an issue

**Comment by KrauseFx** [comment]
Glad to see you got this resolved :+1:

**Comment by asoviche** [comment]
Hi! I am having the exact same issue, now working on it for +5 hours, tried a lot of answers proposed on the web, but nothing seems to work, the reason why I am posting here :) 

Here is my lane:
`    lane :beta_crashlytics do
        
        cert
        sigh
        gym
        crashlytics(
                    api_token: “token...",
                    build_secret: “secret...",
                    ipa_path: "./fastlane/test.ipa",
                    groups:"test",
                    notes: "Just uploaded to iTC for testing",
                    notifications: true,
                    )
                    
    end`

When running the lane, everything seems to work fine, but the tester are not notified at all (in group with alias “test”). And it’s like the .ipa is not really uploaded to Crashlytics because on my iPhone for the build it says “Not Available” instead of “Install” when everything is ok.

<img width="1552" alt="screen shot 2016-05-14 at 18 16 45" src="https://cloud.githubusercontent.com/assets/9138105/15269479/10dd25d6-1a00-11e6-9646-9dac1fe8e324.png">

Please help :)

Thanks a lot! Fastlane rocks!!! 👍

**Comment by TKBurner** [comment]
Hi @asoviche! Thanks for reaching out. Can you let me know how the app appears in your Fabric dashboard? We are showing a success message? Also, to be sure you are using Pods? 

Thanks!

**Comment by asoviche** [comment]
Thanks for the reply!

Yes we are using Pods with the small build script “"${PODS_ROOT}/Fabric/run” …keys…"

I’m not sure what you exactly mean by “appears in your Fabric dashboard”. Here is the message we have in the Fabric Beta dashboard:

<img width="708" alt="screen shot 2016-05-17 at 18 28 25" src="https://cloud.githubusercontent.com/assets/9138105/15330486/538fa138-1c5d-11e6-83a6-2445e6704fd1.png">

But I never got any email on my phone to test the App, and repeating the process 4/5 times did not change anything ;)

Thanks for the help,
Amaury

**Comment by TKBurner** [comment]
@asoviche Thanks for following up. Can you let me know if this could be explained by an email issue with Beta? Either way I can get you up and running, but I want to make sure we follow the right path to get you back up and running! 👍

**Comment by asoviche** [comment]
What do you call an "email issue" exactly? 

All I can say is that I used my personal email as usual and when doing the process manually (without fastlane), I always received the emails to notify me of a new deployment… 

Does that answer your question :) ?

**Comment by TKBurner** [comment]
HI @asoviche Thanks for following up. Beta uses a mail system and sometimes users end up in a 'bounce state' where our system no longer attempts delivery to that address. If this was impacting you, you would receive no emails from Fabric. Is this the case? Thanks!

**Comment by asoviche** [comment]
Indeed I receive no email, how do we solve that? :)

**Comment by TKBurner** [comment]
@asoviche Can you email me at support@fabric.io with your email address associated with your account. Hopefully I'll be able to resolve it with just your email address.

 You can ask for me. I want to move this to a private channel so I can get more details from you 👍

**Comment by asoviche** [comment]
@TKBurner I emailed you with the email used for the Fabric account :)

**Comment by TKBurner** [comment]
@asoviche I'll keep working with you over there so I'm going to go ahead and close this out. Thanks!

**Comment by gabzsa** [comment]
I am having the same issue. Build uploads fine to crashlytics, but no notifications are sent.

```
crashlytics(
        api_token: "...",
        build_secret: "...",
        groups: ["alpha"],
        notes: "Automatic Alpha Build",
        notifications: YES
      )
```

fastlane 1.106.2

**Comment by TKBurner** [comment]
@gabzsa Do the users receive notifications when you distribute through the fabric app? Thanks for working with me on this. Hope that you have a great day!

**Comment by gabzsa** [comment]
Thanks for the reply. Yes, they do receive notifications when I do it through the Fabric app.

**Comment by TKBurner** [comment]
@gabzsa Is this distributing to the same group? Can you add the --verbose flag to your run of the action. (You might need to remove your api keys from the output) I want to take a look what is going on. Thanks!

**Comment by gabzsa** [comment]
Sure, can I send you the output in private?

**Comment by gabzsa** [comment]
Nevermind, I've edited out the ipa name.

```
INFO [2016-11-03 10:20:30.50]: -------------------------
INFO [2016-11-03 10:20:30.50]: --- Step: crashlytics ---
INFO [2016-11-03 10:20:30.50]: -------------------------
INFO [2016-11-03 10:20:30.52]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2016-11-03 10:20:30.53]: ./Pods/Crashlytics/iOS/Crashlytics.framework/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath '[IPA].ipa' -notesPath '/var/folders/_c/4106dfkx25l_brjc3066xz980000gn/T/changelog20161103-1083-adesg0' -groupAliases 'alpha' -notifications YES -debug NO
DEBUG [2016-11-03 10:20:54.27]: 2016-11-03 10:20:30.567 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2016-11-03 10:20:38.250 submit Crashlytics: Added Release Notes Successfully 200
2016-11-03 10:20:38.898 submit Crashlytics: Added Testers/Groups Successfully 200
2016-11-03 10:20:54.200 submit Crashlytics: Uploaded Successfully 202

INFO [2016-11-03 10:20:54.27]: Build successfully uploaded to Crashlytics Beta 🌷
INFO [2016-11-03 10:20:54.27]: Visit https://fabric.io/_/beta to add release notes and notify testers.
INFO [2016-11-03 10:20:54.27]: Successfully generated documentation at path '[PATH]'
+------+-------------------------+-------------+
|               fastlane summary               |
+------+-------------------------+-------------+
| Step | Action                  | Time (in s) |
+------+-------------------------+-------------+
| 1    | default_platform        | 0           |
| 2    | ensure_git_status_clean | 2           |
| 3    | ensure_git_branch       | 0           |
| 4    | git_pull                | 9           |
| 5    | increment_build_number  | 3           |
| 6    | commit_version_bump     | 0           |
| 7    | add_git_tag             | 0           |
| 8    | push_to_git_remote      | 8           |
| 9    | gym                     | 174         |
| 10   | crashlytics             | 23          |
+------+-------------------------+-------------+

```

**Comment by juliorimo** [comment]
Same issue here.
