### ISSUE TITLE
Connection reset by peer - SSL_connect 

### ISSUE THREAD

**Issue by suoxj** [fastlane/fastlane#13460]
### New Issue Checklist

- [ x] Updated fastlane to the latest version 
- [x ] I read the [Contribution Guidelines] 
(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)  
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)      
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) 

### Issue Description

I get the error message "[!] Connection reset by peer - SSL_connect" when i use "fastlane deliver"command , and I have upgrade my ruby by excuting "brew install ruby", and the issue is still, pls give me some help, thanks

##### Complete output when running fastlane, including the stack trace and command used

[18:01:43]: fastlane finished with errors
[18:01:43]: -----------------------------------------------------------------------
[18:01:43]: Connection reset by peer - SSL_connect
[18:01:43]: 
[18:01:43]: SSL errors can be caused by various components on your local machine.
[18:01:43]: 
[18:01:43]: The best solution is to use the self-contained fastlane version.
[18:01:43]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
[18:01:43]:  - Use Homebrew
[18:01:43]:     - update brew with `brew update`
[18:01:43]:     - install fastlane using:
[18:01:43]:       - `brew cask install fastlane`
[18:01:43]:  - Use One-Click-Installer:
[18:01:43]:     - download fastlane at https://download.fastlane.tools
[18:01:43]:     - extract the archive and double click the `install`
[18:01:43]: -----------------------------------------------------------
[18:01:43]: for more details on ways to install fastlane please refer the documentation:
[18:01:43]: -----------------------------------------------------------
[18:01:43]:         🚀       https://docs.fastlane.tools          🚀   
[18:01:43]: -----------------------------------------------------------
[18:01:43]: 
[18:01:43]: You can also install a new version of Ruby
[18:01:43]: 
[18:01:43]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
[18:01:43]: - If you use system Ruby:
[18:01:43]:   - Run `brew update && brew install ruby`
[18:01:43]: - If you use rbenv with ruby-build:
[18:01:43]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
[18:01:43]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
[18:01:43]: - If you use rvm:
[18:01:43]:   - First run `rvm osx-ssl-certs update all`
[18:01:43]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
[18:01:43]: 
[18:01:43]: If that doesn't fix your issue, please google for the following error message:
[18:01:43]:   'Connection reset by peer - SSL_connect'
[18:01:43]: -----------------------------------------------------------------------

[!] Connection reset by peer - SSL_connect

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    resign(
 	 ipa: "xxx.ipa", # can omit if using the `ipa` action
  	 signing_identity: "iPhone Distribution: XXXXX (UE49XXX)",
         provisioning_profile: "xxxxxxxx.mobileprovision", # can omit if using the _sigh_ action
	 bundle_id: "com.wd.ebook"
	)
    deliver(
         ipa: "xxx.ipa",
	 skip_screenshots: true,
	 force: true
	)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxxxxxx”) # The bundle identifier of your app
apple_id("xxxxxxxxx") # Your Apple email address

itc_team_id("xxxxxx") # App Store Connect Team ID
team_id("xxxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-09-28**
</details>
<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Did you do all the other things suggested in the error message?
