### ISSUE TITLE
FASTLANE_USER and FASTLANE_PASSWORD values are missing in Fastfile environment

### ISSUE THREAD

**Issue by tomassliz** [fastlane/fastlane#1347]
I would like to use Fastlane **user** and **passwords** in the Fastfile but I can't get theirs values from the environment. I already saved the users password with the `credentials_manager`.

Here is code:
```ruby
scp(
  username: ENV["FASTLANE_USER"],
  password: ENV["FASTLANE_PASSWORD"],
  host: "awesomeserver.com",
   upload: {
    src: "app.ipa",
    dst: "/some/directory/"
  }
)
```

**Comment by KrauseFx** [comment]
```ruby
user = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
keychain_entry = CredentialsManager::AccountManager.new(user: user)
password = keychain_entry.password
```
Then you have those values in variables, ready to be used :+1:

**Comment by tomassliz** [comment]
This environments values are not set automatically? And I checked keychain and there is the record added with fastlane-credentials tool with prefix _deliver_. Is this ok? Maybe I should check environment values `DELIVER_USER` and `DELIVER_PASSWORD` instead?

**Comment by KrauseFx** [comment]
Oh this requires the password to be stored in the keychain.

**Comment by tomassliz** [comment]
OK, so env values for user and password are not set by default. I have to load it manually from the keychain and as a side effect they are set?

**Comment by KrauseFx** [comment]
Please share a reproducable setup so we can try it.

**Comment by tomassliz** [comment]
First run in the terminal this command and then fill a password:
```
fastlane-credentials add --user hudson
```
Then put these lanes in Fastfile. `fail` lane doesn't print password but `success` lane does. Maybe I miss something or I use env values wrong.

```ruby
lane :fail do
  puts ENV['FASTLANE_PASSWORD']
end

lane :success do
  keychain_entry = CredentialsManager::AccountManager.new(user: "hudson")
  password = keychain_entry.password
  puts password
end
```

**Comment by vpolouchkine** [comment]
@tomassliz Is this still an issue for you?

**Comment by tomassliz** [comment]
I don't know if I fully understand how Fastlane works with `ENV` values. I mentioned in my previous comment a way how to solve my problem with `CredentialsManager` but still I can't read `FASTLANE_PASSWORD` value from the `ENV`. I tried it in the version 1.80.0.

**Comment by TKBurner** [comment]
Hi @tomassliz! Here is the FAQ about ENV values, let me know if you have any other questions :+1: 

If you have one code base, but multiple branded applications

Create different .env files for each environment and reference those environment variables in the Deliverfile, Fastfile, etc.

Example: Create a .env.app1, .env.app2, and .env.app3. Define each of these like the following...

DLV_FIRST_NAME=Josh
DLV_LAST_NAME=Holtz
DLV_PRIM_CATG=Business
DLV_SCND_CATG=Games
Now your Deliver file should look something like this:

app_review_information(
  first_name: ENV['DLV_FIRST_NAME'],
  last_name: ENV['DLV_LAST_NAME']
)

primary_category ENV['DLV_PRIM_CATG']
secondary_category ENV['DLV_SCND_CATG']
Now to run this, all you need to do is specify the environment argument when running fastlane and it will pull from the .env file that matches the same name... Ex: fastlane build --env app1 will use .env.app1 Ex: fastlane build --env app2 will use .env.app2

You can also references these environment variables almost anywhere in fastlane.

You can even define a lane to perform actions on multiple targets:

desc "Deploy both versions"
lane :deploy_all do
    sh "fastlane deploy --env paid"
    sh "fastlane deploy --env free"
end
More on the .env file can be found here.

**Comment by tomassliz** [comment]
@TKBurner Thank you for this explanation but my question is about something different. What about Fastlane environment? If some Fastlane action saves some variable into `ENV` why code like this  https://github.com/fastlane/fastlane/issues/1347#issuecomment-186440758 does not work?

**Comment by prnewman** [comment]
I have to echo tomassliz's comments. According to the CredentialsManager documentation, FASTLANE_USER and FASTLANE_PASSWORD are accessible as environment variables:

https://github.com/fastlane/fastlane/tree/master/credentials_manager

How do we access these environment variables in lanes? I get an error if I add this to a lane:

puts ENV['FASTLANE_USER']

Is this documented somwehere?

Fastlane is terrific. Thanks in advance for your help.

**Comment by TKBurner** [comment]
@tomassliz Thanks for following up. I'm going to follow up with Felix about the specifics of this and we'll update this thread. 👍

**Comment by jbg** [comment]
I’m pretty sure that documentation is saying that you can specify the username and password using environment variables, not saying that the environment variables will be set to the entered (or retrieved from keychain) credentials. Looking at the code, that also looks like the intention.

We use it to specify the creds in a Travis CI environment.

**Comment by ios-ratio** [comment]
Can anybody from Fastlane confirm if jbg is correct in their assumption? Can this be clarified?
