### ISSUE TITLE
Does it work with free developer account?

### ISSUE THREAD

**Issue by llamafilm** [fastlane/fastlane#13484]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Does fastlane work with a free Apple developer account?

#### Question Description
I want to build an iOS app for personal use, and my certificate expires every 7 days.  I'm looking at fastlane sigh to help automate the process of renewing the certificate and re-signing my app.  When I try to init fastlane, I get an error similar to #10744 but that ticket is closed for new comments.

```
["Insufficient permissions for your Apple ID:", "User *xxx@xxx.com* doesn't have enough permission for the following action: user_details_data"]
```

**Comment by sneko** [comment]
@llamafilm did you get your answer :) ?

**Comment by janpio** [comment]
@llamafilm Can you maybe share your AppleScript here so other users in the future can benefit from it? That would be nice, then we can also close this issue here. Thanks.

**Comment by llamafilm** [comment]
It's really sloppy, but I'm happy to share if it helps someone.  This is the most streamlined thing I could think of, given Apple's limitation of free developer accounts.  This runs in bash.

```
open RPiCameraViewer.xcodeproj
sleep 10
xcodebuild -project RPiCameraViewer.xcodeproj/
osascript -e 'quit app "XCode"'
ios-deploy --justlaunch --bundle ./build/Release-iphoneos/RPiCameraViewer.app
```
