### ISSUE TITLE
[feature] additional verbosity for long-running tasks

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#13483]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since I can't re-open #8684, I had to create this one again. Is it possible to add some ping action that posts any output every desired period? Say, I need gym action to post something every minute during an export operation. It would be great if I could call `ping` action before `gym`, so it would post `PING` every minute in a background thread and then, after gym action is done, I could end ping action.

This will save me a lot of nerves... Right now having a large projects that time by time fails in Travis-CI or Jenkins because export operation take too much time, or ibtool takes too much time to compile all the storyboards, or a crashlytics uploads a binary for too long.

This really makes me too angry. A workaround for Travis does not work in Jenkins and a out-a-box solution is always better than a temporary workarounds.

**Comment by Sega-Zero** [comment]
It is not required here

**Comment by Sega-Zero** [comment]
@KrauseFx, may I hope for this feature to be implemented?

**Comment by Sega-Zero** [comment]
Have you ever tried this in Jenkins on macOS? Have you tried this inside Jenkinsfile? Fastfile? Shell script?
I did. And it doesn't work. It doesn't work in any case that does the whole thing using `&` or `nohup`. The workaround from #8684 doesn't work in Jenkins.

Also, when I did experimenting with all that stuff, it appears that fastlane isn't notifying Jenkins with a correct exit code on failure (I had a success status while having troubles with match, or crashlytics, or pilot).

This is why I would like to have a built-in feature that posts something (anything) to stdout, so any CI instance wouldn't fail the build due to inactivity timeout.

**Comment by janpio** [comment]
No, I have not tried - which is why I just gave the vague bits I remembered.

The problem implementing something like this in fastlane is that fastlane is just a ruby script that is executed from top to bottom, starting a few commands along the way and working with the results. There is no (event) loop afaik one could use to regularly trigger any output. 
And if you say the normal ways to run a command in the background that still outputs stuff don't work in your environments, triggering one of those from fastlane directly probably will not help as well.

**Comment by Sega-Zero** [comment]
As @mpirri mentioned in the [comment](
https://github.com/fastlane/fastlane/issues/8684#issuecomment-316820696), there might be an option to post something from a background thread. I'm not sure that's possible, just hoping for a better solution :)
