### ISSUE TITLE
How do I use fastlane with react-native-config ?

### ISSUE THREAD

**Issue by sonlexqt** [fastlane/fastlane#13494]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

Hi, currently in my react-native app I configure two lanes using `fastlane`: `beta` and `production`. I'm using [`react-native-config`](https://github.com/luggit/react-native-config) for different environment configs (stored in 2 files: `.env.beta` and `.env.production`). How can I let `fastlane` know which env file should be used for each lane ?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/xxxx/yyyy/zzzz"
end

default_platform(:ios)

platform :ios do
  desc "Fetch certificates and provisioning profiles"
  lane :certificates do
    match(
      app_identifier: "ai.songnhi.teachers",
      type: "appstore"
    )
  end

  desc "Build the iOS app"
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: "SNTeachersMobile.xcodeproj")
    gym(
      scheme: "SNTeachersMobile",
      workspace: "SNTeachersMobile.xcworkspace",
      clean: true
    )
  end

  desc "Ship to TestFlight"
  lane :beta do
    build
    pilot
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end

platform :ios do
  # TODO
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.myapp.fun") # The bundle identifier of your app
apple_id("dev@myapp.com") # Your Apple email address

itc_team_id("APPSTORE CONNECT TEAM ID") # App Store Connect Team ID
team_id("MY DEV PORTAL TEAM ID") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| uber                      | 0.1.0        |
| retriable                 | 3.1.2        |
| signet                    | 0.10.0       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-10-05**
</details>

**Comment by sonlexqt** [comment]
I updated the question with `fastlane env` output included.

**Comment by cmcaboy** [comment]
I'm trying to figure this out as well. Were you able to find anything?

**Comment by taylorwinfield** [comment]
I managed to get `react-native-config` picking up the correct config file using the [environment variables](https://docs.fastlane.tools/advanced/other/#environment-variables) feature provided by fastlane:

1. Add a matching `.env` file for each of your stages in your fastlane folder. e.g. `.env.beta` `.env.production`.
2. In the fastlane config, add the `ENVFILE` variable with the corresponding `react-native-config` env file, e.g. `ENVFILE=.env.beta`

Now running `fastlane [lane] --env beta` will use the `.env.beta` fastlane-specific config.

This will add the `ENVFILE=.env.beta` variable to the build environment, controlling which file `react-native-config` will pick up and use at runtime. 

Complete example below:

`[project-dir]/fastlane/.env.beta`
```
ENVFILE=.env.beta
```

`[project-dir]/.env.beta`
```
APP_STAGE=stage
```

Running fastlane using `fastlane [lane] --env beta` will result in `react-native-config` using the `.env.beta` file from the root of your React Native app when populating the object for use at runtime, in this case the `Config` will contain `{ APP_STAGE: 'stage' }`.

It's also possible to combine these two files and use one env file for each stage across fastlane and `react-native-config`, but I preferred the separation between build-time and runtime environment variables.

**Comment by sonlexqt** [comment]
Thanks @taylorwinfield ! I followed your instructions and it worked !
