### ISSUE TITLE
Could not find app with app identifier 'com.bundle.id' in your iTunes Connect account (apple_id@domain.com - Team: XXXXXX)

### ISSUE THREAD

**Issue by vincedev** [fastlane/fastlane#13493]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

This is a new issue, following #12055 because it's locked.
@joshdholtz It's been a while since we last interact on this. I'm ready to test anything if you need to.

**Comment by tbaranes** [comment]
I do think that's still an issue.

**Comment by samwize** [comment]
I confirm this is still an issue in 2.108.0

As a workaround, I added the platform 'osx' and it works. eg. `deliver(platform: 'osx')`

Fastlane should already know the platform, and it should now be 'mac' instead of 'osx'.
