### ISSUE TITLE
Unlock keychain fails on Jenkins CI with 51 status code

### ISSUE THREAD

**Issue by MaxRandom** [fastlane/fastlane#13492]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I run fastlane on jenkins CI with options below
```
setup_jenkins(
      force: true,
      keychain_path: **<path_env_var>**,
      keychain_password: **<pass_env_var>**,
      set_code_signing_identity: false,
      result_bundle: false
    )
```
_unlock_keychain_ function from corresponding fastlane action is failing with 51 shell error code.
```
00:00:38.088 INFO [2018-10-04 15:33:17.26]: Unlocking keychain: "codesign.keychain-db".
00:00:38.088 INFO [2018-10-04 15:33:17.32]: Unlocking keychain at path: /Users/jenkins/Library/Keychains/codesign.keychain-db
00:00:38.089 ERROR [2018-10-04 15:33:17.37]: Shell command exited with exit status 51 instead of 0.
```
**Only works when user is logged in on CI and active**

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Shell command exited with exit status 51 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/unlock_keychain.rb:28:in `run'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/setup_jenkins.rb:37:in `run'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
00:00:40.805 	from Fastfile:9:in `block (2 levels) in parsing_binding'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:281:in `execute_flow_block'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/fastlane-2.105.2/bin/fastlane:20:in `<top (required)>'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
00:00:40.805 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
00:00:40.806 	from /Users/jenkins/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.13.6                                        |
| Ruby                        | 2.3.1                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.13.0                             |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane            |
| Host                        | Mac OS X 10.13.6 (17G65)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                   |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode-10.app/Contents/Developer/ |
| Xcode Version               | 10.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.66.2"

default_platform :ios

platform :ios do
  before_all do
    xcversion(version: "10.0")
    bootstrap
    setup_jenkins(
      force: true,
      keychain_path: ENV['MATCH_KN_NAME'],
      keychain_password: ENV['MATCH_KN_PASS'],
      set_code_signing_identity: false,
      result_bundle: false
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "AppScheme")
    slather(output_directory: ENV['SCAN_OUTPUT_DIRECTORY']) if is_ci
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "adhoc")
    update_build_number
    gym
    hockey(api_token: "token")
    generate_hockey_link
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| bundler                   | 1.15.1       |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.10.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| clamp                     | 0.6.5        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| slather                   | 2.4.5        |
| xcode-install             | 2.3.1        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.16.2       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.8.0        |
| danger                    | 5.5.9        |
| danger-plugin-api         | 1.0.0        |
| danger-jira               | 0.2.0        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| cocoapods                 | 1.5.0        |
| artifactory               | 2.8.2        |
</details>

*generated on:* **2018-10-04**
</details></pre>
</details>

###
Could anyone help with this? I saw similar [issue](https://github.com/fastlane/fastlane/issues/12315)  but it was closed. Thanks in advance!

**Comment by punksta** [comment]
I solved the issue by creating new keychain for each build.

**Comment by MaxRandom** [comment]
Hey @punksta! 
Seems like it did the trick 😆

```
    delete_keychain(name: "some name")
    create_keychain(
      name: "some name",
      default_keychain: true,
      unlock: true,
      password:**pass**,
      timeout: 3600,
      lock_when_sleeps: false
    )
    setup_jenkins(
      keychain_path: "some name",
      keychain_password: **pass**,
    )
```

Here how it looks like with `setup_jenkins` lane, maybe will be helpful for someone ;)

**Comment by punksta** [comment]
the important thing is revering default keychain on end of build or error
```
error do |lane, exception, options|
  if lane == :build_appstore
    delete_keychain_safe(KEYCHAIN_NAME)
    revert_default_keychain
  end
end
```

**Comment by MaxRandom** [comment]
Ok, got it, thanks! It works without it but will add reverting for sure.
