### ISSUE TITLE
Modifying In-App Purchase fails with ITC.response.error.OPERATION_FAILED - spaceship

### ISSUE THREAD

**Issue by smbkr** [fastlane/fastlane#13501]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

This is basically a continuation of #10743 - I'd like to be able to modify the localisation data for approved IAPs with Spaceship like the creator of the original issue, however I'm facing the same problem as they did.

Has there been any movement on this issue? Is there some technical restriction that prevents this data from being modified? It's something that can be done in the iTunes connect UI, so I imagine there is some way of doing this programatically.

If this just needs someone to work on adding support, could you give me any guidance on what part of the codebase to start looking at?

**Comment by smbkr** [comment]
The issue is still ongoing so please don’t close.

**Comment by janpio** [comment]
The problem here is most probably just the complexity. `spaceship` is used deep inside fastlane, and isn't very easy to pick up, especially as Apple is moving and changing stuff around all the time recently.

Have you tried all the suggestions in the issue?
If so, can you paste the current code you are trying?

**Comment by smbkr** [comment]
Hi @janpio - What suggestion from the previous issue do you suggest I try? I'm experiencing the same issue as @wufire was in the previous issue, ie. IAPs that are approved for sale can't have localisation data updated  (other data can be modified, and IAPs with another status can be modified).

@kcornbower suggests on the previous issue, that modifying active IAPs is not currently supported, and "code would need to be redone in the future" to support this.

**Comment by smbkr** [comment]
I've tried all suggestions and the issue persists.

**Comment by frankiesimon** [comment]
@kcornbower I would love to reach out about this - stuck with the same issue. What's the best way to contact you?

**Comment by kcornbower** [comment]
@frankiesimon Sure, you can reach me via email, emma at the website listed on my Github profile.

**Comment by frankiesimon** [comment]
@kcornbower Thank you :) Sent you an email.
