### ISSUE TITLE
How to use Fastlane for iOS in Linux OS

### ISSUE THREAD

**Issue by dsrijan** [fastlane/fastlane#13502]
### Question Checklist

- [x] Updated fastlane to the latest version : Latest
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Can we use Fastlane tool for iOS in my Linux System. If yes then how will I get Xcode Envirornment in my Linux machine.

#### Question Description

I just want to use Fastlane for my iOS Application for automation of iOS App submission through my CentOS 7.

**Comment by punksta** [comment]
Some of ios parts of fastlane work on linux. For example `pem`. 
But everything what uses ios keychain, xcode or app transport fails. In theory it's possible to make `sigh` and `match` work on linux but you will need to fork fastlane for implementation.
