### ISSUE TITLE
Is there a way to force Fastlane to run in non-interactive mode?

### ISSUE THREAD

**Issue by Felipe-Banno** [fastlane/fastlane#13504]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Is there a way to force Fastlane to run in non-interactive mode?

#### Question Description

I have a few Apple Developer Accounts that are using 2FA and during my CI workflow Fastlane hangs waiting for an user to input the 2FA code.

Is there a way to force Fastlane to fail if there is need to manually enter any input?

I tried using CI=true like this
`CI=true fastlane myLane`
But it did not work.

Thanks

**Comment by KrauseFx** [comment]
```
CI=true fastlane lane
```

should work, are you sure that's what's running? Try exporting it using
```
export CI=1
```
and then running
```
fastlane lane
```

**Comment by Felipe-Banno** [comment]
@KrauseFx I've just tried both ways and still getting asked for the code
```
Two Factor Authentication for account 'XXXX' is enabled
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code:```

**Comment by Felipe-Banno** [comment]
This problem was not fixed, can we reopen the issue @KrauseFx ?
