### ISSUE TITLE
How to handle lane error/failure in fastlane.swift file?

### ISSUE THREAD

**Issue by yasodhar12590** [fastlane/fastlane#13515]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
Referencing,
[](https://stackoverflow.com/questions/37890582/how-to-continue-on-error-using-fastlane),
[](https://github.com/fastlane/fastlane/issues/12381
)
How can I achieve this in fastlane.swift?
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by yasodhar12590** [comment]
How can I handle command/lane failures in fastfile.swift?. suppose if my gym command fails with a codesigning issue how can I notify it in slack?

**Comment by yasodhar12590** [comment]
Hi @KrauseFx any update on this?

**Comment by creyes38-ford** [comment]
I would also be interested in something for errors. I want to integrate a slack webhook so that we can build notification when it fails. But I haven't seen a way to be able to do that

**Comment by jhandguy** [comment]
Looking at the LaneFile protocol:

`public protocol LaneFileProtocol: class {
    var fastlaneVersion: String { get }
    static func runLane(named: String, parameters: [String : String]) -> Bool

    func recordLaneDescriptions()
    func beforeAll()
    func afterAll(currentLane: String)
    func onError(currentLane: String, errorInfo: String)
}`

All you need to do is implement the method `func onError(currentLane: String, errorInfo: String)` in your Fastfile class and handle the error.

**Comment by jhandguy** [comment]
In you `Fastfile.swift`:

```
class Fastfile: LaneFile {
	func onError(currentLane: String, errorInfo: String) {
	    slack(message: errorInfo, slackUrl: "your-slack-webhook")
	}
}
```

**Comment by pballartzinio** [comment]
I found that even having it implemented for some reason it's never called as described in this issue: 
https://github.com/fastlane/fastlane/issues/12381

**Comment by jhandguy** [comment]
We might want to reopen this issue then 👍

**Comment by yasodhar12590** [comment]
@pballartzinio is right. `func onError(currentLane: String, errorInfo: String)` is never called when lane fails. @jhandguy  please look into it.
