### ISSUE TITLE
fastlane update_fastlane fails for fastlane installed via brew cask

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#13516]
### New Issue Checklist

- [ ] Updated fastlane to the latest version **Cannot update fastlane to latest version**
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`fastlane update_fastlane` fails
<details>
  <pre>fastlane update_fastlane
Updating installed gems
Updating fastlane
Building native extensions.  This could take a while...
ERROR:  Error installing fastlane:
Gems updated: msgpack
	ERROR: Failed to build gem native extension.

    current directory: ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/msgpack-1.2.4/ext/msgpack
~/.fastlane/bin/bundle/bin/ruby -r ./siteconf20181010-90683-12sjet0.rb extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
Gems already up-to-date: fastlanelibraries and/or headers.  Check the mkmf.log file for more details.  You may

need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=~/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/msgpack-1.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/msgpack-1.2.4 for inspection.
Results logged to ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/msgpack-1.2.4/gem_make.out
Cleaning up installed gems...
Clean Up Complete
</pre>
</details>

### Environment

<details>
  <pre>[15:50:47]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[15:50:47]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.105.2 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-10-10**
</details>
[15:50:48]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[15:50:48]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

#######################################################################
# fastlane 2.106.0 is available. You are on 2.105.2.
# You should use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################

[32m2.106.0 Improvements[0m
* [action] fix new try_create_device method (#13509) via John Gadbois
* [supply] take the AAB from Gradle in supply (#13496) via Jonas Schmid
* [match] add support for multiple storage and encryption providers (#13405) via Felix Krause
* [action] remove UDID format validation from register_device (#13459) via Thi
* [deliver,spaceship] Support a new screenshot (Apple Watch Series 4) (#13453) via Tatsuya Tanaka
* [action] new action `download_from_play_store` that does as an action what `fastlane supply init` does as a command (#13113) via Jan Piotrowski
* [core] improve fastlane startup time using bootsnap - behind feature flag (-61% on macOS, -65% on Ubuntu, -7% on Windows!) (#13167) via Jan Piotrowski
* [snapshot] improve screenshot rotation code (#13462) via Jan Piotrowski
* [frameit] fix downloading frames on Windows (#13464) via Jan Piotrowski
* [core] replace Shellwords.*(var) with var.* (#13467) via Jan Piotrowski
* [core] random .shellescape instead of hard coded wrapping in single quotes (#13468) via Jan Piotrowski
* [action[ escapes branch names in `push_to_git_remote` action (#13444) via Rishabh Tayal
* remove unused ItunesSearchApi (#13450) via Jan Piotrowski
* [core] update `fastlane spaceauth` command to work with new API (#13442) via Felix Krause
* [deliver] wait for candidate builds to appear if not available immediately (#13345) via mjovkovic
* [action] added missing keys to modify_services action. (#13415) via John Knapp
* [pilot] fixes issue with `-t DAV` upload parameter not being set in Pilot upload commands (#13404) via Robert MacEachern
* [core] make `Helper.ci?` return true when running on Azure DevOps (VSTS) (#13425) via Marius Ciocanel

[32mPlease update using `fastlane update_fastlane`[0m
</pre>
</details>

This is clearly another ruby version issue, but the reason I install `fastlane` via `brew cask install fastlane` is to avoid ruby version issues.

Output of `mkmf.log`:

```
"/usr/bin/clang -o conftest -I~/.fastlane/bin/bundle/include/ruby-2.2.0/x86_64-darwin15 -I~/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/backward -I~/.fastlane/bin/bundle/include/ruby-2.2.0 -I. -I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe conftest.c  -L. -L~/.fastlane/bin/bundle/lib -L. -L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib -fstack-protector     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
ld: warning: directory not found for option '-L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib'
ld: library not found for -lruby-static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by postmechanical** [comment]
Trying a clean `brew cask install fastlane` gives:

```
brew cask install fastlane
==> Satisfying dependencies
==> Downloading https://fastlane.tools/fastlane.zip
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'fastlane', skipping verification.
==> Installing Cask fastlane
==> Running installer script '/usr/local/Caskroom/fastlane/latest/install'
Installing fastlane to ~/.fastlane/bin... this might take a few seconds
Successfully copied fastlane to ~/.fastlane/bin

Updating installed gems
Updating fastlane
Successfully installed slack-notifier-2.3.2
Successfully installed atomos-0.1.3
Successfully installed claide-1.0.2
Successfully installed nanaimo-0.2.6
Successfully installed xcodeproj-1.6.0
Successfully installed rouge-2.0.7
Successfully installed xcpretty-0.3.0
Successfully installed tty-screen-0.6.5
Successfully installed tty-cursor-0.6.0
Successfully installed tty-spinner-0.8.0
Successfully installed commander-fastlane-4.4.6
Successfully installed gh_inspector-1.1.3
Successfully installed rubyzip-1.2.2
Successfully installed naturally-2.2.0
Successfully installed simctl-1.6.5
Successfully installed declarative-0.0.10
Successfully installed declarative-option-0.1.0
Successfully installed representable-3.0.4
Successfully installed signet-0.11.0
Successfully installed google-api-client-0.23.9
Successfully installed emoji_regex-0.1.1
Building native extensions.  This could take a while...
Gems updated: slack-notifier atomos claide nanaimo xcodeproj rouge xcpretty tty-screen tty-cursor tty-spinner commander-fastlane gh_inspector rubyzip naturally simctl declarative declarative-option representable signet google-api-client emoji_regex msgpack
Gems already up-to-date: fastlane
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/msgpack-1.2.4/ext/msgpack
~/.fastlane/bin/bundle/bin/ruby -r ./siteconf20181010-96302-194p4kz.rb extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=~/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from ~/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/msgpack-1.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/msgpack-1.2.4 for inspection.
Results logged to ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/msgpack-1.2.4/gem_make.out
Cleaning up installed gems...
Attempting to uninstall xcpretty-0.2.6
Successfully uninstalled xcpretty-0.2.6
Attempting to uninstall xcodeproj-1.4.4
Successfully uninstalled xcodeproj-1.4.4
Attempting to uninstall signet-0.7.3
Successfully uninstalled signet-0.7.3
Attempting to uninstall rubyzip-1.2.1
Successfully uninstalled rubyzip-1.2.1
Attempting to uninstall nanaimo-0.2.3
Successfully uninstalled nanaimo-0.2.3
Attempting to uninstall gh_inspector-1.0.3
Successfully uninstalled gh_inspector-1.0.3
Attempting to uninstall commander-fastlane-4.4.4
Successfully uninstalled commander-fastlane-4.4.4
Attempting to uninstall claide-1.0.1
Successfully uninstalled claide-1.0.1
Attempting to uninstall rouge-1.11.1
Successfully uninstalled rouge-1.11.1
Clean Up Complete
Detected shell config file at path '~/.bash_profile'
Please add the following line to your bash profile:

export PATH="$HOME/.fastlane/bin:$PATH"

After doing so close the terminal session and restart it to start using fastlane 🚀
🍺  fastlane was successfully installed!
```

**Comment by juanjoseluisgarcia** [comment]
Also fails to update via gem.The Error is stdio, h not found as reported in the past... a total waste of time...

**Comment by ryanbooker** [comment]
The missing `stdio.h` seems to be because the msgpack gem is looking for the MacOSX platform SDK inside Xcode 7.3.1.

**Comment by postmechanical** [comment]
@ryanbooker This happens on a system that only has Xcode 10 installed as well, but on the system the above logs are taken from ` xcode-select -p` gives `/Applications/Xcode.app/Contents/Developer` which is the correct path to Xcode 10.

**Comment by sjepifanov** [comment]
Same problem here. Using brew cask install to install a standalone package. After install with failed msgpack compilation Fastlane reports version 2.28.3. Build system broken. Please fix ASAP.

**Comment by postmechanical** [comment]
@ryanbooker The errors are actually linker errors not related to Xcode:

```
ld: warning: directory not found for option '-L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib'
ld: library not found for -lruby-static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by juanjoseluisgarcia** [comment]
This is obviously a bug not getting the correct path for dev tools for Xcode 10.

**Comment by ryanbooker** [comment]
@postmechanical I know, that was my point. :) What I meant is that something in the install process is looking for a hardcoded path to `Xcode-7.3.1.app` which is obviously wrong, and almost never going to exist. It would only exist on a system where someone purposely renamed an old Xcode.

**Comment by pionl** [comment]
I have the same problem with different error. New version of `msgpack` should fix this issue: https://github.com/msgpack/msgpack-c/issues/594

Mac OS High Siera (brew install ruby-install tried and no success).

```
Installing msgpack 1.2.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/private/var/folders/yt/w32j8g4n3s5g20vrtnn5mz4c0000gn/T/bundler20181012-8359-vknhgmmsgpack-1.2.4/gems/msgpack-1.2.4/ext/msgpack
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181012-8359-15moeiy.rb
extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler
failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in
try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in
have_header'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in
checking_for'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels)
in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in
postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/var/folders/yt/w32j8g4n3s5g20vrtnn5mz4c0000gn/T/bundler20181012-8359-vknhgmmsgpack-1.2.4/extensions/universal-darwin-17/2.3.0/msgpack-1.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/var/folders/yt/w32j8g4n3s5g20vrtnn5mz4c0000gn/T/bundler20181012-8359-vknhgmmsgpack-1.2.4/gems/msgpack-1.2.4 for
inspection.
Results logged to
/var/folders/yt/w32j8g4n3s5g20vrtnn5mz4c0000gn/T/bundler20181012-8359-vknhgmmsgpack-1.2.4/extensions/universal-darwin-17/2.3.0/msgpack-1.2.4/gem_make.out

An error occurred while installing msgpack (1.2.4), and Bundler cannot continue.
Make sure that `gem install msgpack -v '1.2.4' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.106.0, which depends on
    bootsnap was resolved to 1.3.2, which depends on
      msgpack
```

**Comment by sjepifanov** [comment]
gem install seems to be fixed, any ETA on fix with brew cask install?

**Comment by ryanbooker** [comment]
Brew install appears fixed now.

**Comment by juanjoseluisgarcia** [comment]
confirm that the gem install it is fixed too. So anyone closing this?

**Comment by pionl** [comment]
Fixed, thanks!

**Comment by wdcurry** [comment]
Just hit this issue, having to install fastlane via brew as the gem route failed on permissions issues. All seems fine until 75% through the fastlane init process. 

"clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'"

**Comment by tamasbazs** [comment]
OK

On 23 Dec 2018 20:54, "drew.." <notifications@github.com> wrote:

Just hit this issue, having to install fastlane via brew as the gem route
failed on permissions issues. All seems fine until 75% through the fastlane
init process.

"clang: warning: no such sysroot directory:
'/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fastlane/fastlane/issues/13516#issuecomment-449659923>,
or mute the thread
