### ISSUE TITLE
[Match] Manually manage the fastlane match Repo was broken

### ISSUE THREAD

**Issue by vitaminBW** [fastlane/fastlane#13521]
### New Regression Checklist

- [+] Updated fastlane to the latest version
- [+] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [+] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [+] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

Using this instruction [docs.fastlane](https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo) сommand `GitHelper.clone` not working. I'm trying to add existing certificates to the private git repository.

- Breaking version: [e.g. `2.106.0`]
- Last working version: [e.g. `2.105.2`]

##### Complete output when running fastlane, including the stack trace and command used

```
2.4.2 :023 > workspace = Match::GitHelper.clone(git_url, shallow_clone, manual_password: manual_password)
NameError: uninitialized constant Match::GitHelper
Did you mean?  Match::Helper
	from (irb):23
	from /Users/User1/.rvm/rubies/ruby-2.4.2/bin/irb:11:in `<main>'
```

### Environment

<details>
  <pre>Do this from an interactive Ruby console</pre>
</details>

**Comment by joshdholtz** [comment]
@vitaminBW Looking into!

**Comment by vitaminBW** [comment]
@joshdholtz i have found the method to download and decrypt repo from last commits
`fastlane match decrypt`
It would be fantastic if you would have method encrypt and upload also. For example -
`fastlane match encrypt`

**Comment by stanBienaives** [comment]
@vitaminBW the `Match::GitHelper.clone` method is not available since this commit cc282f264f8cefbd8561cd9b1388c75d073307a1

Here is a workaround I am using in my custom actions: 

```ruby
config = FastlaneCore::Configuration.create(Match::Options.available_options, {}).load_configuration_file('Matchfile').options

config[:clone_branch_directly] = true
config[:skip_docs] = true
config[:shallow_clone] = true

# clone repo to get path
storage = Match::Storage.for_mode('git', config)
storage.download

encryption = Match::Encryption.for_storage_mode('git', {
  git_url: config[:git_url],
  working_directory: storage.working_directory
})
encryption.decrypt_files

#use path to the directory to manipulate files: 
storage.working_directory

```
Hope it helps.  

In my opinion this is not very handy to have a wrapper that clone and decrypt.

**Comment by JCMais** [comment]
can we have a official word here? This was something that was supported, so I suppose this is a breaking change.

**Comment by tpoche** [comment]
Agreed, this was something we used often to incorporate existing certificates and provisioning profiles into Match.  Would love to have this working again or another way to achieve the same end result.

**Comment by lparenteau** [comment]
> @vitaminBW the `Match::GitHelper.clone` method is not available since this commit [cc282f2](https://github.com/fastlane/fastlane/commit/cc282f264f8cefbd8561cd9b1388c75d073307a1)
> 
> Here is a workaround I am using in my custom actions:
> 
> ```ruby
> config = FastlaneCore::Configuration.create(Match::Options.available_options, {}).load_configuration_file('Matchfile').options
> 
> config[:clone_branch_directly] = true
> config[:skip_docs] = true
> config[:shallow_clone] = true
> 
> # clone repo to get path
> storage = Match::Storage.for_mode('git', config)
> storage.download
> 
> encryption = Match::Encryption.for_storage_mode('git', {
>   git_url: config[:git_url],
>   working_directory: storage.working_directory
> })
> encryption.decrypt_files
> 
> #use path to the directory to manipulate files: 
> storage.working_directory
> ```
> 
> Hope it helps.
> 
> In my opinion this is not very handy. It was cleaner to call a wrapper that took care of both cloning and decrypting.

To save changes once you're done : 
```
encryption.encrypt_files
storage.save_changes!()
```

**Comment by tpoche** [comment]
@lparenteau Thanks for this workaround.  Note that in my case, I also had to add the following config value to get it working properly:
`config[:git_branch] = 'master'`

Seems like that should've been the default, but I was getting an exception when calling the `storage.download` method without that included.

**Comment by LizCira** [comment]
It's not ideal, but you can also just regress your Fastlane gem version, as the original post points out, it still works at 2.105.2

**Comment by JAManfredi** [comment]
We frequently use this as well, pleas fix.

**Comment by janpio** [comment]
Hey, could someone please summarize for me what exactly is broken? Whole manual management? Only decrypt, only encrypt? Where does this `Match::GitHelper.clone` thing come from?

**Comment by joshdholtz** [comment]
Hey everyone 👋 Just wanted to give the official response/announcement to this this...

`Match::GitHelper` was replaced a few _fastlane_ ago (since `2.106.0` which happened in https://github.com/fastlane/fastlane/pull/13405). This big internal rewrite was to allow for other storage and encryption schemes to be integrated in the near future - so that's its not only git storage and not only AES ecryption using OpenSSL.

`Match::GitHelper` was removed in this PR but we _could_ add something similar back in to help make this easier to do manually.

The docs have been updated accordingly here - https://docs.fastlane.tools/advanced/other/#decryption-instructions

**Comment by janpio** [comment]
(That link unfortunately does not work directly, you have to go to https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo first an un-collapse the "Instructions")

**Comment by janpio** [comment]
Hey all, the documentation linked above seems to work and have the expected result. Looks like you,  @JCMais, also updated your post at https://medium.com/@jonathancardoso/using-fastlane-match-with-existing-certificates-without-revoking-them-a325be69dac6 to include the new command.

Can we close this?

**Comment by JCMais** [comment]
I think so, thanks everyone for posting solutions and for adding that to the official docs.
