### ISSUE TITLE
[GYM] build_ios_app requires `project` even when generating an IPA from a preexisting archive

### ISSUE THREAD

**Issue by awgeorge** [fastlane/fastlane#13528]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using `build_ios_app` with an archive, it fails requiring a project (or scheme in an CI environment)

```
build_ios_app(
      project: options[:project], # Complains if not included 
      scheme: options[:scheme], # Complains if not included 
      skip_build_archive: true,
      skip_archive: true,
      archive_path: options[:archive_path]
)
```

The command it runs to generate the IPA doesn't need scheme or a project

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>➜  Fastlane git:(master) ✗ fastlane Test archive_path:/Users/will/iPhone/123133.xcarchive --capture_output
[✔] 🚀
[19:29:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-10-12 19:29:48.74]: Checking if there are any plugins that should be loaded...
DEBUG [2018-10-12 19:29:48.89]: Using archive_path: /Users/will/iPhone/123133.xcarchive
INFO [2018-10-12 19:29:48.90]: ------------------------------
INFO [2018-10-12 19:29:48.90]: --- Step: default_platform ---
INFO [2018-10-12 19:29:48.90]: ------------------------------
INFO [2018-10-12 19:29:48.90]: Driving the lane 'ios Test' 🚀
INFO [2018-10-12 19:29:48.90]: ---------------------------
INFO [2018-10-12 19:29:48.90]: --- Step: build_ios_app ---
INFO [2018-10-12 19:29:48.90]: ---------------------------
WARN [2018-10-12 19:29:48.95]: Couldn't automatically detect the project file, please provide a path:
WARN [2018-10-12 19:29:48.95]: Lane Context:
INFO [2018-10-12 19:29:48.95]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios Test"}
ERROR [2018-10-12 19:29:48.95]: Could not retrieve response as fastlane runs in non-interactive mode
INFO [2018-10-12 19:29:48.95]: Successfully generated documentation at path ' /Users/will/iPhone/fastlane/README.md'
ERROR [2018-10-12 19:29:48.95]: fastlane finished with errors</pre>
</details>

As far as I can tell, `build_ios_app` runs, the following before, the actual build command - but it's not necessary when the project is already archived.

```
xcodebuild -showBuildSettings -scheme SCHEME -project /Users/will/iPhone/project.xcodeproj
```

### Environment

<details>
  <pre>+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.106.1                 |
| export_method | app-store               |
| sdk           | iPhoneOS12.0.sdk        |
+---------------+-------------------------+</pre>
</details>

**Comment by janpio** [comment]
So `build_ios_app` currently requires `project` and `scheme` even when `archive_path` is set, which kind of makes this not necessary any more. Correct?

**Comment by vincentisambart** [comment]
I've got the same problem. When `skip_build_archive` is `true`, the project file should not be needed but you got asked for one if there's no detected project file and you don't specify one.

Currently, to work around it I'm creating an empty project using `Xcodeproj::Project.new(xcodeproj_path).save` and pass `project: xcodeproj_path` to `build_ios_app`. That does work, but that's ugly. Also it working proves that a project file should not be needed.

Cc @giginet

**Comment by awgeorge** [comment]
I'm pretty sure this will still be a problem. @all anybody have time to confirm?

**Comment by AbbyM** [comment]
Hello,
Yes it's still a problem, actually we can't export ipa from xcarchive properly.

**Comment by robnadin** [comment]
This is still an issue
