### ISSUE TITLE
[Regression] match --template_name option not available

### ISSUE THREAD

**Issue by pumapaul** [fastlane/fastlane#13520]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.106.0
- Last working version: 2.105.2.

### Regression Description

We use a provisioning profile template because of custom entitlements.
We included the line `template_name("REDACTED")` in our Matchfile.

As you can see in the output, the new update broke the `template_name` option of `match`, i.e. it somehow made the option itself unavailable.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

$ fastlane match development

`[!] Could not find option 'template_name' in the list of available options: git_url, git_branch, type, app_identifier, username, keychain_name, keychain_password, readonly, team_id, git_full_name, git_user_email, team_name, verbose, force, skip_confirmation, shallow_clone, workspace, force_for_new_devices, skip_docs, platform`

btw, running `$ fastlane match development --capture_output` produces: 
`invalid option: --capture_output`
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    before_all do
      if is_ci?
        setup_circle_ci
      end
    end

    desc "CI Build Staging"
    lane :ci do
      sh("cd ./../../ && NODE_ENV=production STAGE=staging node config.js")

      sh("curl -s -L $(curl -s https://api.github.com/repos/CirrusMD/badger/releases | grep browser_download_url | grep macOS | head -n 1 | cut -d '\"' -f 4) > badger.zip && unzip -o badger.zip")
      sh("./badger -alpha -glob ./../**/*.appiconset")

      sync_code_signing(type: "appstore")

      increment_build_number(xcodeproj: "wifiBahn.xcodeproj")

      cocoapods
      build_app(
        clean: true,
        include_bitcode: false,
        include_symbols: true,
        workspace: "wifiBahn.xcworkspace",
        scheme: "wifiBahn"
      )

      upload_to_testflight
    end

    after_all do
      sh("git checkout ../wifiBahn/Images.xcassets/AppIcon.appiconset/") # need to reset icons

      version = get_version_number(xcodeproj: "wifiBahn.xcodeproj")
      build_number = get_build_number(xcodeproj: "wifiBahn.xcodeproj")

      sh("git checkout -b version-bump-app-to-#{build_number}")
      commit_version_bump(message: "testflight #{version}-#{build_number} [skip ci]", xcodeproj: "./wifiBahn.xcodeproj", force: true)
      push_to_git_remote

      create_pull_request(
        api_token: ENV["GITHUB_TOKEN"],
        repo: "Bahn-X/bahn-x",
        title: "App version bump to #{version}-#{build_number}",
        base: "master",
        body: "CI just pushed a new app version to Testflight, so merge this PR"
      )
    end

    desc "Push a new beta build to Testflight"
    lane :alpha do
      #ensure_git_status_clean
      sh("cd ./../../ && NODE_ENV=production node config.js")
      sh("./badger -alpha -glob ./../**/*.appiconset")


      sync_code_signing(type: "appstore")    # see code signing guide for more information

      increment_build_number(xcodeproj: "wifiBahn.xcodeproj")

      build_app(
        clean: true,
        include_bitcode: false,
        include_symbols: true,
        workspace: "wifiBahn.xcworkspace",
        scheme: "wifiBahn"
      )

      upload_to_testflight
      sh("git checkout ../wifiBahn/Images.xcassets/AppIcon.appiconset/") # need to reset icons

      #version = get_version_number(xcodeproj: "wifiBahn.xcodeproj")
      #build_number = get_build_number(xcodeproj: "wifiBahn.xcodeproj")

      #commit_version_bump(message: "testflight #{version}-#{build_number}")
      #push_to_git_remote
    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("de.deutschebahn.wifiatdb") # The bundle identifier of your app
apple_id("tech@bahn-x.de") # Your Apple email address
team_id("98282PEV5S")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.11.0       |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2018-10-11**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@pumapaul Looking into!

**Comment by joshdholtz** [comment]
@pumapaul Your fastlane output actually shows that you are using `2.28.3` 🤔 
<img width="399" alt="screen shot 2018-10-11 at 7 30 38 am" src="https://user-images.githubusercontent.com/401294/46804193-9d395900-cd27-11e8-91cf-fb4f5392b354.png">

**Comment by pumapaul** [comment]
Oh, wow you're right. 

That means the distribution is broken. I upgraded via brew, a colleague via fastlane update. Both options got us 2.28.3

Seems someone uploaded the wrong artifact?

**Comment by joshdholtz** [comment]
Ah, I found the issue! It turns out there was a new dependency added that requires the building of native extensions. The brew installation process was failing at this so it ended up somehow reverting back to `2.28.3`. I think I'm going to revert the PR that added this since the solution to fix properly will take some time 🤔
