### ISSUE TITLE
Kotlin bug

### ISSUE THREAD

**Issue by Mp5A5** [fastlane/fastlane#13523]
My project is Android ,we use java and kotlin developed ,when use java fastlan is ok ,but kotlin will have
a bug,

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'UseEnergy'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
         > Could not get resource 'http://maven.enncloud.cn/content/repositories/releases/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
            > Could not GET 'http://maven.enncloud.cn/content/repositories/releases/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
               > Connect to 10.4.94.150:8080 [/10.4.94.150] failed: Connection refused (Connection refused)
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
         > Could not get resource 'http://maven.aliyun.com/nexus/content/groups/public/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
            > Could not GET 'http://maven.aliyun.com/nexus/content/groups/public/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
               > Connect to 10.4.94.150:8080 [/10.4.94.150] failed: Connection refused (Connection refused)
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
         > Could not get resource 'https://jitpack.io/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
            > Could not GET 'https://jitpack.io/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
               > Connect to 10.4.94.150:8080 [/10.4.94.150] failed: Connection refused (Connection refused)
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
               > Connect to 10.4.94.150:8080 [/10.4.94.150] failed: Connection refused (Connection refused)
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
               > Connect to 10.4.94.150:8080 [/10.4.94.150] failed: Connection refused (Connection refused)
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.61/kotlin-gradle-plugin-1.2.61.pom'.
               > Connect to 10.4.94.150:8080 [/10.4.94.150] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | Switch to android  | 0           |
|      | prepare lane       |             |
| 3    | git_pull           | 1           |
| 💥   | gradle             | 1           |
+------+--------------------+-------------+

[11:24:47]: fastlane finished with errors

**Comment by Mp5A5** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13.6                              |
| Ruby                        | 2.5.1                                |
| Bundler?                    | true                                 |
| Git                         | git version 2.13.0                   |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane  |
| Host                        | Mac OS X 10.13.6 (17G65)             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib         |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

ENV["JG_ANDROID_SDK_DIR"] = %x( echo $ANDROID_HOME ).chomp

platform :android do

  desc '构建前的准备工作'
  desc '这是一个私有任务，仅供 Fastfile 内部 lane 调用使用'
  private_lane :prepare do
    # 拉取最新代码
    git_pull
  end

  desc '构建后的准备工作'
  desc "钉钉机器人用来发送下载地址通知给测试群"
  private_lane :dingdingtalk do |options|

    #
    app_version = lane_context[SharedValues::ANALYZE_APK_VERSION_NAME]
    app_build_version = lane_context[SharedValues::ANALYZE_APK_VERSION_CODE]
    app_name    = lane_context[SharedValues::ANALYZE_APK_APP_NAME]

    UI.message("Start get app information from pgyer...")

    if options[:type] == "flavorRelease"
      params = {
        "_api_key" => "8c747e5f3605475b25e9fcff53aa09c5",
        "appKey" => "e4f6048edb2cfde87c5b4694e1267367"
      }
      app_desc = "生产版"
    elsif options[:type] == "flavorTest"
       params = {
        "_api_key" => "8c747e5f3605475b25e9fcff53aa09c5",
        "appKey" => "b48ddfef1b36cad0bf22c5763be26d10"
      }
      app_desc = "测试版版"
      elsif options[:type] == "flavorDev"
       params = {
        "_api_key" => "8c747e5f3605475b25e9fcff53aa09c5",
        "appKey" => "b48ddfef1b36cad0bf22c5763be26d10"
      }
      app_desc = "开发版"
    end

    # 获取App详细信息
    response = Net::HTTP.post_form URI('https://www.pgyer.com/apiv2/app/view'), params
    result = JSON.parse(response.body)

    status_code = result["code"]
    status_message = result["message"]

    if status_code != 0
      UI.error('pgyer error message: ' + status_message)
      return
    end

    UI.success("Successfully get app information from pgyer!")

    #
    app_url = "https://www.pgyer.com/" + result["data"]["buildShortcutUrl"]
    app_icon = "https://www.pgyer.com/image/view/app_icons/" + result["data"]["buildIcon"] + "/144"
    dingTalk_url = "https://oapi.dingtalk.com/robot/send?access_token=2d7f5962a839b2f9503db11c12d6b20c21349206a9e86e8550edcd6d05a43260"

    markdown =
    {
      msgtype: "link",
      link: {
          text: "已经更新啦，快来试试吧!",
          title: "Android #{app_name} #{app_version} (#{app_build_version}) #{app_desc}",
          picUrl: "#{app_icon}",
          messageUrl: "#{app_url}"
      }
    }

    uri = URI.parse(dingTalk_url)
    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true

    request = Net::HTTP::Post.new(uri.request_uri)
    request.add_field('Content-Type', 'application/json')
    request.body = markdown.to_json

    response = https.request(request)

    json = JSON.parse(response.body)

    if json["errcode"] != 0
      UI.error('ding talk error message: ' +  json["errmsg"])
      return
    end
    UI.success("Successfully send link message to ding talk!")
  end


  desc "拉取Git最新代码，打包APK，提交到蒲公英"
  lane :submit_to_pgy do |options|

    if options[:flavor].nil?
      UI.error('need flavor options')
    end

    prepare

    gradle(task: "clean")
    # gradle(task: "assembleRelease")
    gradle(task:'assemble', flavor:options[:flavor], build_type:'Release')

     analyze_apk(
      android_home: ENV["JG_ANDROID_SDK_DIR"],
      build_tools_version: '26.0.3',
      apk_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )

    pgyer(
      api_key: "8c747e5f3605475b25e9fcff53aa09c5",
      user_key: "28e1bb2b9e33a89116b5fae06023e42c",
      update_description: "android#{lane_context[SharedValues::ANALYZE_APK_APP_NAME]}内部测试版本发布 by fastlane"
    )

    dingdingtalk(type:options[:flavor])
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.fanneng.useenergy") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.106.0 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-pgyer       | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-analyze_apk | 0.2.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.2.0        |
| executable-hooks            | 1.5.0        |
| bundler-unload              | 1.0.2        |
| rubygems-bundler            | 1.4.5        |
| bundler                     | 1.16.2       |
| CFPropertyList              | 3.0.0        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.5.2        |
| atomos                      | 0.1.3        |
| babosa                      | 1.0.2        |
| msgpack                     | 1.2.4        |
| bootsnap                    | 1.3.2        |
| claide                      | 1.0.2        |
| colored                     | 1.2          |
| colored2                    | 3.1.2        |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20180417 |
| dotenv                      | 2.5.0        |
| emoji_regex                 | 0.1.1        |
| excon                       | 0.62.0       |
| multipart-post              | 2.0.0        |
| faraday                     | 0.15.3       |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.12.2       |
| fastimage                   | 2.1.4        |
| gh_inspector                | 1.1.3        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| multi_json                  | 1.13.1       |
| os                          | 1.0.0        |
| signet                      | 0.11.0       |
| googleauth                  | 0.6.6        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2018.0812  |
| mime-types                  | 3.2.2        |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.23.9       |
| json                        | 2.1.0        |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.4.0        |
| rubyzip                     | 1.2.2        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.5        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 1.8.0        |
| unicode-display_width       | 1.4.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.6.5        |
| tty-cursor                  | 0.6.0        |
| tty-spinner                 | 0.8.0        |
| word_wrap                   | 1.0.0        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.6.0        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| fastlane-plugin-analyze_apk | 0.2.0        |
| fastlane-plugin-pgyer       | 0.2.2        |
</details>


*generated on:* **2018-10-15**
</details>

**Comment by janpio** [comment]
Could you fix the problem or is this still a thing?

**Comment by Mp5A5** [comment]
> Could you fix the problem or is this still a thing?
yes  i did . because my gradle use https proxy,so when i use fastlane download kotlin cause this erro. for mac  you enter ~/.gradle delete file gradle.properties or comment out  https proxy may be fix. if you use flutter may be have same erro. solution to like this.
