### ISSUE TITLE
Cert with p12 Password

### ISSUE THREAD

**Issue by wahmedswl** [fastlane/fastlane#13535]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Hi, using fastlane to generate Certificate and Provisioning profile and then will be using phonegap build to actually build app. Its all worked well with ```cert``` and ```sigh``` but generated p12 is without password and phonegap build require password. I have checked issues and most of the references are for ```pem``` and commit https://github.com/fastlane-old/pem/commit/557747a8b91df6c8c300fda43aafad16fe957978

#### Question Description

Please help, what would be be possible option?

**Comment by RishabhTayal** [comment]
@wahmedswl you can use the `p12_password` option to specify your `pem` password for the p12 file. If you do not provide this option, it will use empty password as default value.

**Comment by wahmedswl** [comment]
@RishabhTayal thanks, so i have to add ```pem``` in fastfile and ```cert``` will use that?

Thanks for your quick response.

**Comment by wahmedswl** [comment]
@RishabhTayal i have added ```pem``` but p12 generated by ```pem``` doesn't match with the provisioning profile generated.

And when i also tried to upload the p12 of provisioning profile, i get password error on phonegap build. 

I just want to use the ```cert``` and ```sigh``` part of fastlane, and then build will be carried over by phonegap build service. 

Just want to generate valid p12 with password.

Thanks

**Comment by JesperBaltzersen** [comment]
I'm facing a similar issue, but will be uploading to MS AppCenter.
I'm creating a script which will be using commands `cert` and `sigh` for adhoc and production profiles.  
AppCenter also requires a p12 with a valid password that is known to me.

**Comment by JesperBaltzersen** [comment]
@wahmedswl did you get this to work? 
> @RishabhTayal thanks, so i have to add `pem` in fastfile and `cert` will use that?
>
Could you share how?

**Comment by wahmedswl** [comment]
@JesperBaltzersen nope, i have checked the api where that can be applied but still i am directly uploading right now and not using Phonegap Build due to this. I am also waiting for response.

**Comment by janpio** [comment]
Just to make sure I understood correctly:
Is the issue that you want `cert` to create a certificate in p12 format, set with a specific password?

**Comment by JesperBaltzersen** [comment]
@janpio I'm not sure if you're asking me or @wahmedswl but for me that is the case yes. 

The work around I'm using now, is just to let `cert` do most of the work and then extract the p12 manually from keychain.

**Comment by janpio** [comment]
I was asking you both as you seemed to agree you have the same issue - but I wasn't sure if I had properly understood it.

**Comment by wahmedswl** [comment]
Hi, can we please re-open this issue as its still not answered

Thanks

**Comment by wahmedswl** [comment]
Hi, is someone got any way or workaround for this. Either manual steps that can achieve this or anything.

Thanks

**Comment by wahmedswl** [comment]
Hi, can we please re-open this issue as its still not answered

Thanks

**Comment by janpio** [comment]
Please reply yourself when @fastlane-bot posts next time so it doesn't actually close the issue. Thanks.

**Comment by wahmedswl** [comment]
@wahmedswl this needs to be kept open as still not answered.

Thanks

**Comment by bhavincb** [comment]
does anyone have workaround? i'm also having same issue here.

**Comment by wahmedswl** [comment]
@bhavincb nope, still no luck with it. But, moved to fastlane match and it can generate certificates and provisioning profiles with password. Used that with phonegap build and its great 👍

**Comment by bhavincb** [comment]
@wahmedswl  can you please share the steps for that? it will really help me a lot.

**Comment by wahmedswl** [comment]
@bhavincb fastlane match official guide is awesome and available at https://docs.fastlane.tools/actions/match/

**Comment by bhavincb** [comment]
@wahmedswl but p12 file generated by match gives error `Too few bytes to read ASN.1 value.` that's why i had asked for help.

**Comment by wahmedswl** [comment]
@bhavincb its because fastlane match keep stuff encrypted. You need to follow https://docs.fastlane.tools/actions/match/#manual-decrypt to decrypt.

```
openssl aes-256-cbc -k "password" -in "certs/development/PFG6487A72.cer" -out "development/development.der" -a -d
openssl x509 -inform der -in development/development.der -out development/development.pem
openssl aes-256-cbc -k "password" -in "certs/development/PFG6487A72.p12" -out "development/development_key.pem" -a -d
openssl pkcs12 -export -out "development/development.p12" -inkey "development/development_key.pem" -in "development/development.pem" -password pass:password
openssl aes-256-cbc -k "password" -in "profiles/development/Development_com.app.id.mobileprovision" -out "development/Development_com.app.id.mobileprovision" -a -d

```

**Comment by bhavincb** [comment]
@wahmedswl  it's giving me error `error reading input file`. i have created certificates and provision using `match` action and issues follow command. password used is the same as github repo password.

`openssl aes-256-cbc -k "password" -in "U2M49JU375.cer" -out "cert.der"  -a -d`

**Comment by wahmedswl** [comment]
@bhavincb seems like you are at the root of the repo, you need to give full path like ```openssl aes-256-cbc -k "password" -in "certs/development/PFG6487A72.cer" -out "development/development.der" -a -d```

**Comment by bhavincb** [comment]
@wahmedswl  i'm using below command for match. and after navigating to `.cert` folder issuing decryption command.
```
match(type:"appstore",output_path:".cert/")
cd .cert
openssl aes-256-cbc -k "password" -in "U2M49JU375.cer" -out "cert.der" -a -d
```

**Comment by wahmedswl** [comment]
@bhavincb you don't need to use match now, just clone the certificates repo and do this at there.

**Comment by bhavincb** [comment]
@wahmedswl  after using above command it download certificates and provision to `.cert` folder. and i can see it is already decrypted as `.p12` file starts with `-----BEGIN RSA PRIVATE KEY-----`. 
so i don't think there is any need to decrypt. but still i'm getting the error.

**Comment by wahmedswl** [comment]
@bhavincb we go with the repo route and generated combined p12 and decrypted provisioning profile.

Do you get error on build.phonegap when unlocking certificate and it asks for password?

**Comment by bhavincb** [comment]
@wahmedswl  actually i'm using it with ionic build. in which i have to pass the path to p12 certificate ,provision and certificate password.

**Comment by bhavincb** [comment]
i was able to solve the issue by using following commands.

```
match(type:"appstore",output_path:".cert/")
cd .cert
openssl x509 -inform der -in development.cer -out development.pem
openssl pkcs12 -export -out cert.p12 -inkey development.p12 -in development.pem -password pass:password
```
and after that we will pass cert.p12 and provision profile to the build command.
