### ISSUE TITLE
Fastlane won't properly wait for 2FA code after call to prompt()

### ISSUE THREAD

**Issue by robinkunde** [fastlane/fastlane#13538]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In my fastfile, I gather build notes by calling prompt() right before calling latest_testflight_build_number(). latest_testflight_build_number() will then start the App Store Connect session. If my 2FA session has expired, it will show the prompt, but immediately process empty input and then fail with "Unauthorized access". If I skip prompt() or move it after the call to latest_testflight_build_number() the problem does not occur. I did not test other calls that have to initialize the App Store Connect session.

It appears to me like prompt() is not properly consuming the last newline character after the multi_line_end_keyword and leaving it in the input buffer.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
[10:08:15]: ----------------------------------------
[10:08:15]: --- Step: Verifying fastlane version ---
[10:08:15]: ----------------------------------------
[10:08:15]: Your fastlane version 2.106.2 matches the minimum requirement of 2.105.0  ✅
[10:08:15]: ------------------------------
[10:08:15]: --- Step: default_platform ---
[10:08:15]: ------------------------------
[10:08:15]: Driving the lane 'ios beta' 🚀
[10:08:15]: ----------------------------------
[10:08:15]: --- Step: ensure_xcode_version ---
[10:08:15]: ----------------------------------
[10:08:15]: $ xcversion selected
[10:08:16]: ▸ Xcode 9.4.1
[10:08:16]: ▸ Build version 9F2000
[10:08:16]: Selected Xcode version is correct: 9.4.1
[10:08:16]: -------------------------------------
[10:08:16]: --- Step: ensure_git_status_clean ---
[10:08:16]: -------------------------------------
[10:08:16]: $ git status --porcelain
[10:08:16]: Git status is clean, all good! 💪
[10:08:16]: --------------------
[10:08:16]: --- Step: prompt ---
[10:08:16]: --------------------
[10:08:16]: Changelog for beta review:
[10:08:16]: Submit inputs using "END"
some notes
END
[10:08:30]: --------------------------------------------
[10:08:30]: --- Step: latest_testflight_build_number ---
[10:08:30]: --------------------------------------------
[10:08:30]: Login to App Store Connect (test@test.com)
Two Factor Authentication for account 'test@test.com' is enabled
Your session cookie has been expired.
Please enter the 6 digit code: Requesting session...
+-----------------------------+----------+
|              Lane Context              |
+-----------------------------+----------+
| DEFAULT_PLATFORM            | ios      |
| PLATFORM_NAME               | ios      |
| LANE_NAME                   | ios beta |
| GIT_REPO_WAS_CLEAN_ON_START | true     |
+-----------------------------+----------+
[10:08:32]: Unauthorized Access

+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 1    | Verifying fastlane version     | 0           |
| 2    | default_platform               | 0           |
| 3    | ensure_xcode_version           | 0           |
| 4    | ensure_git_status_clean        | 0           |
| 5    | prompt                         | 14          |
| 💥   | latest_testflight_build_number | 2           |
+------+--------------------------------+-------------+

[10:08:32]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane cert fails with 'Unauthorized Access'
    https://github.com/fastlane/fastlane/issues/11570 [closed] 22 💬
    11 Aug 2018

➡️  Fastlane init: Unauthorized Access
    https://github.com/fastlane/fastlane/issues/9321 [closed] 3 💬
    29 Aug 2017

➡️  fastlane init error
    https://github.com/fastlane/fastlane/issues/9241 [closed] 25 💬
    29 Aug 2017

and 6 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Unauthorized Access</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14                                            |
| Ruby                        | 2.5.0                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.19.1                               |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane             |
| Host                        | Mac OS X 10.14 (18A391)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode9.4.1.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.105.0")

default_platform(:ios)

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Testing Build to Apple TestFlight"
  lane :beta do |options|
    # Check required version of Xcode command line tools
    ensure_xcode_version(version: "9.4.1")

    # Ensure that your git status is not dirty
    ensure_git_status_clean

    unless options[:skip_submission]
      changelog = prompt(
        text: "Changelog for beta review: ",
        multi_line_end_keyword: "END"
      )
    end

    # Increment the build number (not the version number)
    build_number = increment_build_number(build_number: latest_testflight_build_number.to_i + 1)

    # bump version number
    # parameters: patch, minor, major
    if options[:bump_version]
      increment_version_number(bump_type: options[:bump_version])
    end

    #
    build_app(scheme: "SchemeName", include_symbols: true, clean: true, include_bitcode: false)
    if options[:skip_submission]
      upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
    else
      upload_to_testflight(wait_for_uploaded_build: true, wait_processing_interval: 60, distribute_external: true, changelog: changelog)
    end

    # Commit the version bump
    version_number = get_version_number(target: "TargetName")
    commit_version_bump(message: "v#{version_number} build #{build_number}")

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # cleanup
    clean_build_artifacts
  end

  desc "Submit a new Production Build to Apple TestFlight"
  lane :release do |options|
    # Check required version of Xcode command line tools
    ensure_xcode_version(version: "9.4.1")

    # Ensure that your git status is not dirty
    ensure_git_status_clean

    unless options[:skip_submission]
      changelog = prompt(
        text: "Changelog for beta review: ",
        multi_line_end_keyword: "END"
      )
    end

    # Increment the build number (not the version number)
    build_number = increment_build_number(build_number: latest_testflight_build_number.to_i + 1)

    # bump version number
    # parameters: patch, minor, major
    if options[:bump_version]
      increment_version_number(bump_type: options[:bump_version])
    end

    #
    build_app(scheme: "SchemeName", include_symbols: true, clean: true, include_bitcode: false)
    if options[:skip_submission]
      upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
    else
      upload_to_testflight(wait_for_uploaded_build: true, wait_processing_interval: 60, distribute_external: true, changelog: changelog)
    end

    # Commit the version bump
    version_number = get_version_number(target: "TargetName")
    commit_version_bump(message: "v#{version_number} build #{build_number}")

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # cleanup
    clean_build_artifacts
  end

  desc "Register device with dev portal"
  lane :register_dev_device do |options|
    register_devices(devices: {options[:name] => options[:udid]})
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("AppID") # The bundle identifier of your app

itc_team_id("TeamID") # App Store Connect Team ID
team_id("TeamID") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.3       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.4.4        |
</details>

*generated on:* **2018-10-15**
</details>

**Comment by janpio** [comment]
Interesting. So the `prompt` itself is properly opened, input and used, but then on the next "prompt"/input it is automatically submitted with no content?

**Comment by robinkunde** [comment]
That's correct.

**Comment by janpio** [comment]
Whoah, that is curious.

Could you try a new lane with just two prompts - from my current understanding "submitting" the first one should automatically also submit the second one, right?

**Comment by robinkunde** [comment]
I was not able to make it happen with two prompt calls, so I dug deeper into the code. That allowed me to isolate the problem.

`prompt` uses the following code to collect input if you use a `multi_line_end_keyword`:
https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/lib/fastlane/actions/prompt.rb#L18
`end_tag` is treated as the record separator, meaning `gets` will read from `STDIN` until it encounters this string and then return. Everything after the record separator is left in the buffer.
If you don't use `multi_line_end_keyword`, `prompt` will block until it receives non-empty input after stripping whitespace, which is why I couldn't reproduce it with two prompt calls.

The 2FA prompt on the other hand uses the ```ask``` method (from the highline gem, I believe) which does accept empty input and so will consume the newline left in the buffer:
https://github.com/fastlane/fastlane/blob/1af33c0884e783867bdc07a324280ec6bef124ad/spaceship/lib/spaceship/two_step_client.rb#L67

You can reproduce the issue by with the following lane:
```ruby
desc "prompt test"
lane :prompt_test do |options|
  test1 = prompt(
      text: "Test 1: ",
      multi_line_end_keyword: "END"
    )
  test2 = ask("Test 2: ")

  puts("test2 contains '" + test1 + "'")
  puts("test2 contains '" + test2 + "'")
end
```

Or more directly:
```ruby
desc "prompt test"
lane :prompt_test do |options|
  test1 = STDIN.gets("END").chomp.gsub("END", "").strip
  test2 = ask("Test 2: ")

  puts("test2 contains '" + test1 + "'")
  puts("test2 contains '" + test2 + "'")
end
```
In both cases, `ask` should return without waiting for input.

I'm not sure what the best fix here is.
You could add a newline to the record separator, but I don't know if that's portable and work for non-interactive contexts. 

Sidebar: Is it intended behavior that the `multi_line_end_keyword` is *not* required to be on its own line? If I happen to place it in the middle of a line, it will be treated just the same.

**Comment by janpio** [comment]
> Everything after the record separator is left in the buffer.

This seems to be the bug here - if we empty the buffer there we should be fine, right?

> Sidebar: Is it intended behavior that the multi_line_end_keyword is not required to be on its own line? If I happen to place it in the middle of a line, it will be treated just the same.

Accidental feature I guess? Probably noone ever thought about it - but better look at the blame and history of the file to investigate a bit.

**Comment by robinkunde** [comment]
I think emptying the buffer should be fine for fine for interactive sessions, as it doesn't even prompt in non-interactive ones.

I checked the history and this code hasn't been changed since it was introduced.

**Comment by robinkunde** [comment]
I’m happy to give it a try once I’m done traveling, early next week.

**Comment by robinkunde** [comment]
@janpio Added PR.

**Comment by robinkunde** [comment]
Let's keep this open until the PR is merged.
