### ISSUE TITLE
pilot import CSV library wrong number of arguments

### ISSUE THREAD

**Issue by awgeorge** [fastlane/fastlane#13537]
https://github.com/fastlane/fastlane/issues/12403 is still a problem please reopen. Or stop locking issues!

**Comment by awgeorge** [comment]
@joshdholtz - Just a nudge to see if you can address the above. Thanks.

**Comment by janpio** [comment]
The original poster of that issue told us it was fixed for him. If you still encounter the problem, please open a proper bug issue with all the necessary information included (the bug issue template will ask you for it). Thanks.

**Comment by joshdholtz** [comment]
@awgeorge Can you paste your `fastlane env` output here please?
