### ISSUE TITLE
Can't find documentation for create In-App-Purchaces

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#13544]
Can't find documentation for create In-App-Purchaces related to this https://github.com/fastlane/fastlane/issues/1631

I have search both on github and on the docs site, but found nothing.

**Comment by janpio** [comment]
This is most probably a feature of `spaceship` only, the library fastlane uses internall to communicate with Apple's services. If you didn't find anything, the methods are not implemented as a fastlane action that can be used in lanes, but one must use the spaceship functionality directly.
