### ISSUE TITLE
Appfile.swift, how to access platform variable (`for_platform :ios`) ?

### ISSUE THREAD

**Issue by Valpertui** [fastlane/fastlane#13545]
### Question Subject

Question is about Fastlane Swift tool on Appfile Swift syntax

This question is about documentation

#### Question Description
How to I translate this Appfile content ruby syntax (specially `for_platform :ios` and `for_lane :test`) to the Swift syntax ?
```
for_platform :ios do
  team_id '123' # for all iOS related things
  for_lane :test do
    app_identifier 'com.app.test'
  end
end
```

**Comment by janpio** [comment]
@taquitos?

**Comment by taquitos** [comment]
Sorry, been super busy and will be for another week. Maybe @joshdholtz has a minute to check into it in the meantime?

**Comment by aberkunov** [comment]
I have the same question. How to translate ruby syntax `for_platform :ios do` to swift?

**Comment by taquitos** [comment]
`for_platform` isn't currently supported 😢
cc @janpio
