### ISSUE TITLE
Cannot find certificate in developer portal, can't resolve with nuke, fails

### ISSUE THREAD

**Issue by trops** [fastlane/fastlane#13542]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I tried to run my beta lane to submit a binary to the App Store, and I got no certificate found in the developer portal. I then ran

`fastlane match development` 

and get the same certificate not found error. 

I then ran 

`fastlane match nuke development`

and get the following error...

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[16:01:46]: Successfully deleted file
[16:01:46]: Deleting file 'AppStore_com.onq.mobile.mobileprovision'...
[16:01:46]: Failure to decode /var/folders/c3/bf7dnqys7234xvlwwzgr__sh0000gn/T/d20181015-49185-35hq89/profiles/appstore/AppStore_com.onq.mobile.mobileprovision. Exit: 1: security: failed to add data to decoder: UNKNOWN (-8183(d)
security: problem decoding

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Error parsing provisioning profile at path '/var/folders/c3/bf7dnqys7234xvlwwzgr__sh0000gn/T/d20181015-49185-35hq89/profiles/appstore/AppStore_com.onq.mobile.mobileprovision' (FastlaneCore::Interface::FastlaneCrash)
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/fastlane_core/lib/fastlane_core/provisioning_profile.rb:33:in `parse'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/nuke.rb:203:in `block in delete_files!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/nuke.rb:198:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/nuke.rb:198:in `delete_files!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/nuke.rb:185:in `nuke_it_now!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/nuke.rb:62:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/commands_generator.rb:152:in `block (3 levels) in run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/commands_generator.rb:159:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/match/lib/match/commands_generator.rb:22:in `start'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.106.2/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/                |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.54.3"

default_platform :ios

platform :ios do
  before_all do
    ENV["RCT_NO_LAUNCH_PACKAGER"] = "true"
  end

  desc "Generate app icons"
  lane :create_appicon do
    appicon(
      appicon_image_file: '../assets/AppIconSource.png',
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: '---------------------/Images.xcassets'
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sh "../bundle.sh"
    match(
      type: "appstore",
    )
    increment_build_number(
      # build number will always be the current *nix timestamp
      build_number: "`date +%s`"
    )
    gym(
      scheme: "-----------------",
      configuration: "Staging"
    )
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    sh "../bundle.sh"
    match(
      type: "appstore",
    )
    #snapshot(
    #  erase_simulator: true,
    #  ios_version: "11.0.1"
    #)
    increment_build_number(
      # build number will always be the current *nix timestamp
      build_number: "`date +%s`"
    )
    gym(
      scheme: "-----------------",
      configuration: "Release"
    )
    deliver(
      force: true,
    )
    # frameit
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.onq.mobile" # The bundle identifier of your app
apple_id "---------------------" # Your Apple email address

team_id "------------" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.13.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.3.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| fastlane-plugin-appicon   | 0.13.0       |
</details>

*generated on:* **2018-10-15**
</details></pre>
</details>

**Comment by pickettjd** [comment]
Same issue with same error output using fastlane match nuke development using 2.106.2

**Comment by joshdholtz** [comment]
@trops @pickettjd On it 💪

**Comment by pickettjd** [comment]
That fixed it.  You si,r are the wind beneath my wings.
