### ISSUE TITLE
General setting for Project-Directory

### ISSUE THREAD

**Issue by xstable** [fastlane/fastlane#13541]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
General Configuration

#### Question Description
I use `fastlane` for react-native Projects. There I have /ios and /android as first level below my Project-Root.
I've init `fastlane` in my Project-Root-Directory, but found that this makes more work as expected, because there is no (or I not found it yet) a config-flag to set the Project-Directories for gradle and xcode.

I've found an workaround for gradle if I use `gradle(project_dir:'./android')`.
For some IOS-Commands this work: `xcodeproj: './ios/MyProject.xcodeproj'`

But I really wonder if there is a way to set this globally in the platform section... like in `before_all` section.

If there isn't a way, please add it to the future-wishlist. Because in other way you would need to have an fastlane-installation for /android and for /ios, which is suboptimal.

Hope somebody can give me a hint, how to solve this.

**Comment by janpio** [comment]
Doesn't it make sense to explicitly define the project to be built for all commands?
