### ISSUE TITLE
[PEM] `fastlane pem` fails on multiple app_identifiers `no implicit conversion of Array into String`

### ISSUE THREAD

**Issue by bartolkaruza** [fastlane/fastlane#13559]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running `fastlane pem` the command causes the below error. This only happens when multiple app identifiers are specified. When forced to a single app identifier using the `-a` cli option, the command succeeds. If `fastlane pem` is intended to only work with a single identifier, a clearer error should be returned. 

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[✔] 🚀 
[11:02:41]: fastlane detected a Gemfile in the current directory
[11:02:41]: however it seems like you don't use `bundle exec`
[11:02:41]: to launch fastlane faster, please use
[11:02:41]: 
[11:02:41]: $ bundle exec fastlane pem
[11:02:41]: 
[11:02:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------+--------------------------------------------------+
|                       Summary for PEM 2.107.0                        |
+-------------------+--------------------------------------------------+
| development       | false                                            |
| generate_p12      | true                                             |
| active_days_limit | 30                                               |
| force             | false                                            |
| save_private_key  | true                                             |
| app_identifier    | ["xxx", "xxx"] |
| username          | xxx                      |
| team_id           | xxx                                       |
| output_path       | .                                                |
+-------------------+--------------------------------------------------+

[11:02:42]: Starting login with user 'xxx'
[11:02:44]: Successfully logged in
[11:02:45]: Creating a new push certificate for app '["xxx", "xxx"]'.

Looking for related GitHub issues on fastlane/fastlane...

➡️  Gym failing with "no implicit conversion of Symbol into Integer" in 2.45.0 when using sigh for profile selection
    https://github.com/fastlane/fastlane/issues/9684 [closed] 17 💬
    18 Nov 2017

➡️  Deliver: Add supply's `android` folder to list of excluded directories for language check
    https://github.com/fastlane/fastlane/pull/10267 [closed] 12 💬
    12 Dec 2017

➡️  fastlane snapshot with concurrent_simulators launches more simulators than it should
    https://github.com/fastlane/fastlane/issues/10457 [closed] 2 💬
    23 Dec 2017

and 9 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20Array%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/app.rb:112:in `casecmp': [!] no implicit conversion of Array into String (TypeError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/app.rb:112:in `block in find'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/app.rb:111:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/app.rb:111:in `find'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/app.rb:111:in `find'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/certificate.rb:296:in `create!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/pem/lib/pem/manager.rb:49:in `create_certificate'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/pem/lib/pem/manager.rb:33:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/pem/lib/pem/commands_generator.rb:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/pem/lib/pem/commands_generator.rb:43:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/pem/lib/pem/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1 (Apple Git-112)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'
require_relative '../../fastlane/version.rb'

Dotenv.load('../../' + (ENV['ENVFILE'] ? ENV['ENVFILE'] : ".env"))

default_platform(:ios)

platform :ios do
  desc "Push a new release build to Testflight"
  lane :acceptance do
    increment_version_number(
      version_number: getVersionName()
    )
    increment_build_number(
      build_number: ENV['BITRISE_BUILD_NUMBER']
    )
    build_app(
      scheme: ENV['IOS_RELEASE_SCHEME'] ? ENV['IOS_RELEASE_SCHEME'] : "thuis"
    )
    upload_to_testflight(
      distribute_external: false,
      app_identifier: "xxx",
      skip_waiting_for_build_processing: true
    )
  end

  lane :release do
      increment_version_number(
        version_number: getVersionName()
      )
      increment_build_number(
        build_number: ENV['BITRISE_BUILD_NUMBER']
      )
      build_app(
        scheme: ENV['IOS_RELEASE_SCHEME'] ? ENV['IOS_RELEASE_SCHEME'] : "thuis"
      )
      upload_to_testflight(
        changelog: ENV['BITRISE_GIT_MESSAGE'] ? ENV['BITRISE_GIT_MESSAGE'] : "nieuwe test build",
        distribute_external: true,
        groups: ["xxx"],
        app_identifier: "xxx",
        skip_waiting_for_build_processing: true
      )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(["xxx", "xxx"]) # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.2       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.4.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.4.0        |
</details>

*generated on:* **2018-10-18**
</details>
</pre>
</details>

**Comment by janpio** [comment]
How exactly are you executing `fastlane pem` @bartolkaruza?

**Comment by janpio** [comment]
How and where do you defines this array or app_identifiers?

From what I read in the documentation at https://docs.fastlane.tools/actions/pem/, `pem` is indeed only meant to be used for one app at a time. But you are right, a better error message wouldn't hurt - or if possible of course support for multiple apps at a time.

**Comment by bartolkaruza** [comment]
@janpio They are defined in the Xcode project (multiple targets with different app identifier values). fastlane (pem ?) internally interprets this into the array shown.

**Comment by janpio** [comment]
Do you have an `Appfile` that lists this array as the `app_identifier` for use with some other tool or command?

Besides that, I checked the code and `pem` definitely can not handle multiple `app_identifier`s. We could now a) check if `app_identifier` is an array and throw an error that tells people to use the `app_identifier` parameter/option of `pem`, or b) implement some logic that loops through the error and executes `pem` for each entry. 
I think I prefer a) as it needs an explicit decision of the user which of their apps need new push profiles. Agree?

**Comment by janpio** [comment]
> Do you have an Appfile that lists this array as the app_identifier for use with some other tool or command?

Could please check this as well? I couldn't find any code that really reads from the project in pem, so we have to make sure where these identifiers actually come from for you.

**Comment by bartolkaruza** [comment]
You are right, there are multiple app_identifiers specified in the `Appfile`, sorry for the confusion on that point.

**Comment by bartolkaruza** [comment]
app_identifier(["nl.***.thuis", "nl.***.thuis.acc"]) # The bundle identifier of your app

**Comment by janpio** [comment]
Which other actions/tools use this in that form? Maybe we can copy this handling...
