### ISSUE TITLE
"Add to Siri" is not localized when taking a snapshot

### ISSUE THREAD

**Issue by cherpake** [fastlane/fastlane#13558]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using INUIAddVoiceShortcutButton in the app and taking snapshots, its title appears in English for every language. This is not the case when running on simulator and setting a language via Edit Scheme -> Application Language.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14                                                          |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.18.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14 (18A389)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane(nightly: true)

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  lane :deploy do
	cocoapods
	increment_build_number
	commit_version_bump(xcodeproj: "./Control.xcodeproj")
	gym(include_bitcode: true, workspace: "Control.xcworkspace", scheme: "Control")
	deliver(skip_screenshots: false, force: true, edit_live: false, ignore_language_directory_validation: true)
	hockey(api_token: "59201ce99cf14fd0815375045faf839f", dsym: "./Control.ipa.dSYM", notes: "Changelog")
  end
  
  lane :upload do
	deliver(skip_screenshots: true, force: true, edit_live: false, ignore_language_directory_validation: true)
  end
  
  lane :previews do
    upload_previews
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.cherpake.macrc.adsfree" # The bundle identifier of your app
apple_id "d314127481@gmail.com" # Your Apple email address

team_id "MCKT7VHXP5"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| fastimage                 | 2.1.4        |
</details>

*generated on:* **2018-10-18**
</details></pre>
</details>

**Comment by cherpake** [comment]
https://www.dropbox.com/s/il9oghy6gwhuyug/iPhone%208%20Plus-05System_11ca7032-3ee3-4828-b573-8d67fb69d087_framed.jpg?dl=0

**Comment by mpdifran** [comment]
I'm noticing the same issue when I am generating screenshots for my Notification Content extension. It seems like the language is being set at an app level, instead of at the OS level.

**Comment by janpio** [comment]
Can you share a sample screenshot as well @mpdifran?

As you wrote, this could be a limitation on how snapshot currently sets the language.

**Comment by mpdifran** [comment]
![iphone x-5-teal](https://user-images.githubusercontent.com/1365987/48724288-d56d6a80-ebf6-11e8-80e5-9e47c3110d48.png)

**Comment by mpdifran** [comment]
This is still an issue (which actually costs me a lot of time, because I need to manually set the language on each simulator at the OS level, and I have 10+ languages and 6 simulators 😖).

**Comment by janpio** [comment]
Could you maybe investigate a bit how the language is currently set and why this doesn't affect Siri and notification extensions? Using some of the output you get when running the lane/action, you should be able to find the correct areas of the code and then simply follow what is going on. Maybe this can give us an idea what has to be changed.

**Comment by mpdifran** [comment]
Still looking into this.

**Comment by mpdifran** [comment]
Still trying to find time to look into this!

**Comment by mpdifran** [comment]
Still looking into this!

**Comment by shayneoneill** [comment]
Ping!
