### ISSUE TITLE
FrameIt without title or keyword?

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#13550]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about? - FrameIt

Is this a question about documentation? No

Is this a question about a third party plugin? (If so, please go to the plugin repository first) - No

#### Question Description

I'd like to omit either the title or keywords as I don't need both.

I've tried not providing the text values in my strings files but I get an error.

`Could not get title for screenshot ./en-US/iPhone 5s-main.png. Please provide one in your Framefile.json or title.strings`

I've also tried omitting the section for title / keyword.

I can't see an option to do this?

**Comment by janpio** [comment]
Very possible that this is currently not possible @Jules2010 - you would have to look at the code to understand what is going on. Looking for that error message (or pieces of it) should be a good start.

Have you tried using an empty string instead of removing the value?
