### ISSUE TITLE
XCode ends up using a "zombie" provisioning after a new profile was recreated with same name.

### ISSUE THREAD

**Issue by NoseKills** [fastlane/fastlane#13551]
We had a working build pipeline set up using 
`provisioningProfiles: {
	"com.company.product" => "Profile Name abcdef"
}`

After some device list clean-up and adding capabilities to an app, the profile needed to be recreated.

Now builds fail with 
`error: "Unity-iPhone" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor. (in target 'Unity-iPhone')`

When I open XCode afterwards, all the Provisioning Profile dropdowns show a red text containing the file name of the old deleted provisioning profile a la "345gege4-2434-fe42-fwe24232fawr3". 

I can manually click the dropdowns -> Download... -> Profile Name, and the profile gets downloaded and set so I can succesfully make a build.

Where does XCode get the ID of the deleted profile from? Wonder if there's a workaround other than again recreating the profiles but with different names this time?

I've tried deleting "DerivedData" and "ProvisioningProfiles" folders under /Library with no success.

**Comment by janpio** [comment]
Is it maybe still in your keychain? Have you cleaned that up as well?
