### ISSUE TITLE
Beginners documentation is lacking

### ISSUE THREAD

**Issue by dhoskins** [fastlane/fastlane#13566]
With frameworks such as Fastlane and Danger becoming more and more popular, it seems that for better or worse, a degree of Ruby knowledge seems to be a requirement for a senior iOS developer. 

I believe we badly need a document entitled "Everything an iOS developer needs to know about Ruby before touching Fastlane".

Having just spent quite a few days figuring much of this out for myself, I am not sure I am the best person to write it.

---

The iOS Getting Started document advises beginners to use sudo gem install fastlane. Is this not terrible advice? 

Beginners using this to set up their development machines or CI servers will obviously be OK to start with but run in to trouble when they have different projects in the same machine using different versions, or wish to have versions upgraded by non root users.

I think this documentation should spell out traps to avoid (such as using sudo to install, or using the system standard Ruby), and be opinionated on matters such as the best stack for new users (e.g. rbenv/bundler).

Too many guides online either assume knowledge, or spell out alternatives without indicating all pros and cons.

New users here would appreciate a clear steer on best practice.

**Comment by janpio** [comment]
> Having just spent quite a few days figuring much of this out for myself, I am not sure I am the best person to write it.

I disagree, just _because_ you just had to fight your way through it you are in the best position to create a list of things that are currently missing from the documentation. We would sure appreciate such a list over at https://github.com/fastlane/docs/issues

> The iOS Getting Started document advises beginners to use sudo gem install fastlane. Is this not terrible advice?

Yes and no. You listed a few reasons why this might get problematic for some users. But for the majority this will work just fine. Adding "Install rbenv / rmv / ..." would add an additional step for _all_ users, while the majority will probably never need and use it.

If I remember correctly, this is even mentioned somewhere in the docs... but maybe not surfaced in all the correct locations.
