### ISSUE TITLE
Unable to update metadata with deliver. The request could not be completed because: (Spaceship::Tunes::PotentialServerError 

### ISSUE THREAD

**Issue by ignazioc** [fastlane/fastlane#13567]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want update the description and release note of my iOS app on ITC. 
On ITC there is already a brand new version that is not submitted yet.

1. Downloaded the current metadata running `fastlane deliver download_metadata`
Result:  ✅ 
2. Downloaded the current screenshots running `fastlane deliver download_screenshots`
Result:  ✅ 
3. Changed few strings, and tried to upload executing this command:
```
fastlane deliver run \
  --username #my_username#> \
  --app_identifier #bundleID# \
  --skip_binary_upload true \
  --force true \
  --app_version 8.4.0 \
  --verbose \
```
or running the same via a lane:
```
desc "Update metadata"
lane :update_metadata do |options|
  deliver(
    app_identifier: ' #bundleID#',
    username: '#my_username#',
    force: true,
    submit_for_review: false,
    metadata_path: "./metadata",
    skip_screenshots: true,
    verbose: true,
    skip_binary_upload: true,
    app_version: '8.4.0'
    )
end
```

Expected:
The updated metadata are applied on the release `8.4.0`
Current result:
After few `invalid_request`
```
[⠙] Activating languages de-DE, en-US... Potential server error received: 'invalid_request'. Retrying after 10 seconds (remaining: 5)...
```
the script stops with the stacktrace and this log:
```
         1: from /Users/icalo/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/tunes_client.rb:436:in `block in update_app_version!'
/Users/icalo/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/tunes_client.rb:227:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::Tunes::PotentialServerError)
```

I know this comes from the spaceship error `Spaceship::TunesClient::ITunesConnectPotentialServerError`, it would be nice to have more info to properly debug the error.

Note: the same is happening also using the `spaceship playground`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
INFO [2018-10-21 16:31:38.01]: Successfully loaded '/Work/****/ios-client/fastlane/Deliverfile' 📄
WARN [2018-10-21 16:31:38.01]: No values defined in './fastlane/Deliverfile'
INFO [2018-10-21 16:31:38.01]: Login to App Store Connect (*******)
Loading session from '/Users/****/.fastlane/spaceship/****/cookie'
Looking for App Store Connect Team with ID *****
INFO [2018-10-21 16:31:40.75]: Login successful

+--------------------------------------+---------------------------+
|                     deliver 2.107.0 Summary                      |
+--------------------------------------+---------------------------+
| username                             | **************            |
| app_identifier                       | com.*****************.ebc |
| skip_binary_upload                   | true                      |
| force                                | true                      |
| app_version                          | 8.4.0                     |
| screenshots_path                     | ./fastlane/screenshots    |
| metadata_path                        | ./fastlane/metadata       |
| platform                             | ios                       |
| edit_live                            | false                     |
| use_live_version                     | false                     |
| skip_screenshots                     | false                     |
| skip_metadata                        | false                     |
| skip_app_version_update              | false                     |
| overwrite_screenshots                | false                     |
| submit_for_review                    | false                     |
| reject_if_possible                   | false                     |
| automatic_release                    | false                     |
| phased_release                       | false                     |
| run_precheck_before_submit           | true                      |
| precheck_default_rule_level          | warn                      |
| ignore_language_directory_validation | false                     |
| precheck_include_in_app_purchases    | true                      |
+--------------------------------------+---------------------------+

INFO [2018-10-21 16:31:41.74]: Making sure the latest version on App Store Connect matches '8.4.0' from the ipa file...
INFO [2018-10-21 16:31:44.55]: '8.4.0' is the latest version on App Store Connect
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/description.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/keywords.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/release_notes.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/support_url.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/marketing_url.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/promotional_text.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/name.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/subtitle.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/de-DE/privacy_url.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/description.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/keywords.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/release_notes.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/support_url.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/name.txt'...
INFO [2018-10-21 16:31:46.08]: Loading './fastlane/metadata/en-US/subtitle.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/copyright.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/primary_category.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/secondary_category.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
INFO [2018-10-21 16:31:46.09]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/trade_name.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/first_name.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/last_name.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/address_line1.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/address_line2.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/address_line3.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/city_name.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/state.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/country.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/postal_code.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/phone_number.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/email_address.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/first_name.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/last_name.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/phone_number.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/email_address.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/demo_user.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/demo_password.txt'...
INFO [2018-10-21 16:31:46.10]: Loading './fastlane/metadata/review_information/notes.txt'...
[⠙] Activating languages de-DE, en-US... Potential server error received: 'invalid_request'. Retrying after 10 seconds (remaining: 5)...
[⠙] Activating languages de-DE, en-US... Potential server error received: 'invalid_request'. Retrying after 10 seconds (remaining: 5)...
[⠙] Activating languages de-DE, en-US...
Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
        invalid_request

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09invalid_request+repo:fastlane/fastlane
[⠧] Activating languages de-DE, en-US... ➡️  Invalid request with fastlane deliver
    https://github.com/fastlane/fastlane/issues/11533 [closed] 1 💬
    13 Mar 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        22: from /Users/******/.rvm/gems/ruby-head/bin/ruby_executable_hooks:24:in `<main>'
        21: from /Users/******/.rvm/gems/ruby-head/bin/ruby_executable_hooks:24:in `eval'
        20: from /Users/******/.rvm/gems/ruby-head/bin/fastlane:23:in `<main>'
        19: from /Users/******/.rvm/gems/ruby-head/bin/fastlane:23:in `load'
        18: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
        17: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
        16: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
        15: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
        14: from /Users/******/.rvm/gems/ruby-head/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        13: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        12: from /Users/******/.rvm/gems/ruby-head/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        11: from /Users/******/.rvm/gems/ruby-head/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        10: from /Users/******/.rvm/gems/ruby-head/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         9: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
         8: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/runner.rb:38:in `run'
         7: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/runner.rb:120:in `upload_metadata'
         6: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/upload_metadata.rb:72:in `upload'
         5: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/deliver/lib/deliver/upload_metadata.rb:253:in `verify_available_languages!'
         4: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/app_version.rb:403:in `save!'
         3: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/tunes_client.rb:429:in `update_app_version!'
         2: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1433:in `with_tunes_retry'
         1: from /Users/******/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/tunes_client.rb:436:in `block in update_app_version!'
/Users/****/.rvm/gems/ruby-head/gems/fastlane-2.107.0/spaceship/lib/spaceship/tunes/tunes_client.rb:227:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::Tunes::PotentialServerError)
        invalid_request</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13.6                                          |
| Ruby                        | 2.6.0                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.17.1 (Apple Git-112)               |
| Installation Source         | ~/.rvm/gems/ruby-head/bin/fastlane               |
| Host                        | Mac OS X 10.13.6 (17G65)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-head/lib                      |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10.0.app/Contents/Developer/ |
| Xcode Version               | 10.0                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
fastlane_require 'fileutils'
fastlane_require 'shellwords'

fastlane_version "1.109.0"
default_platform :ios


desc "Update metadata"
lane :update_metadata do |options|
  deliver(
    app_identifier: 'com.ebaykleinanzeigen.ebc',
    username: 'development@ebay-kleinanzeigen.de',
    force: true,
    submit_for_review: false,
    metadata_path: "./metadata",
    skip_screenshots: true,
    verbose: true,
    skip_binary_upload: true,
    app_version: '8.4.0',
    itc_provider: 'Marktplaats BV'
    )
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-10-21**
</details></pre>
</details>

**Comment by janpio** [comment]
Spaceship error "surfacing" indeed is not very nice and causing problems with debugging actual problems all over the place. Any suggestion how exactly this could be improved? Very open to suggestions here.
