### ISSUE TITLE
provisioningProfiles duplicates

### ISSUE THREAD

**Issue by eXhausted** [fastlane/fastlane#13565]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about?
sigh & gym
Is this a question about documentation?
No
Is this a question about a third party plugin? (If so, please go to the plugin repository first)
No

#### Question Description

I have some `while` loop with `sigh` and `gym` inside. In first iteration `gym` outputs next:
`[13:24:05]: Generated plist file with the following values:`
`[13:24:05]: ▸ -----------------------------------------`
`[13:24:05]: ▸ {`
`[13:24:05]: ▸   "signingStyle": "manual",`
`[13:24:05]: ▸   "method": "app-store",`
`[13:24:05]: ▸   "provisioningProfiles": {`
`[13:24:05]: ▸     "<bundle_id>": "<bundle_id> AppStore 1520929003"`
`[13:24:05]: ▸   },`
`[13:24:05]: ▸   "teamID": "<team_id>"`
`[13:24:05]: ▸ }`
`[13:24:05]: ▸ -----------------------------------------`

In second iteration `gym` outputs next:
`[13:25:39]: Generated plist file with the following values:`
`[13:25:39]: ▸ -----------------------------------------`
`[13:25:39]: ▸ {`
`[13:25:39]: ▸   "signingStyle": "manual",`
`[13:25:39]: ▸   "method": "app-store",`
`[13:25:39]: ▸   "provisioningProfiles": {`
`[13:25:39]: ▸     "<another_bundle_id>": "<another_bundle_id> AppStore 1521047768",`
`[13:25:39]: ▸    "<bundle_id>": "<bundle_id> AppStore 1520929003"`
`[13:25:39]: ▸   },`
`[13:25:39]: ▸   "teamID": "<team_id>"`
`[13:25:39]: ▸ }`
`[13:25:39]: ▸ -----------------------------------------`
So in 20th iteration it will contain 20 provisioning profiles.

How can I clean `provisioningProfiles`? Because they crashes command line with `too much args` after 20+ iterations

**Comment by janpio** [comment]
Can you please share your `Fastfile` with the lane that contains this `while` loop? This is probably a use case that wasn't considered when creating the code that includes the profiles here.

**Comment by VBerko** [comment]
@janpio Sorry, but I have long afk period can't get into code base now. Currently can say how I've fixed it:
`Actions.lane_context[SharedValues::SIGH_PROFILE_PATHS] = nil`

**Comment by eXhausted** [comment]
@janpio Sorry, but I have long afk period can't get into code base now. Currently can say how I've fixed it:
`Actions.lane_context[SharedValues::SIGH_PROFILE_PATHS] = nil`

**Comment by janpio** [comment]
Yep, that's what I suspected - running `sigh` always adds the new paths to that array. We would have to find a way to have this reset on each new invocation - or similar. Please post your code when you get access back to it, then we can see if this would actually help here. (No pressure here, just respond to the issue when @fastlane-bot will try to close it in a month or two to keep it open.) Thanks!
