### ISSUE TITLE
Idea: fastlane action to lint Fastfiles

### ISSUE THREAD

**Issue by JaviSoto** [fastlane/fastlane#1357]
Context: I suck at Ruby.
I often make changes to the `Fastfile`, and while I'm getting better at it, I often make syntax errors that break the `Fastfile`. Sometimes it's tricky to verify this because it may involve executing a lane that may take a long time.

I tried `ruby-lint`, but it doesn't know of the functions that it calls. Example:

```
Fastfile: error: line 1, column 1: undefined method fastlane_version
Fastfile: error: line 3, column 1: undefined method default_platform
Fastfile: error: line 5, column 1: undefined method platform
Fastfile: error: line 6, column 5: undefined method after_all
Fastfile: error: line 7, column 9: undefined method push_git_tags
```

Would this be doable? My knowledge of Ruby is very limited, but my guess is that it could be possible if the linter is pointed to the definitions of all these functions in the fastlane gems?

It would be nice to be able to do:

```sh
fastlane lint
```

And have that check your `Fastfile` for syntax errors :)

**Comment by KrauseFx** [comment]
So `fastlane linit` would basically just make sure there is no syntax error? It can't really verify the actions, parameters, etc. Would that be enough?

**Comment by JaviSoto** [comment]
Yeah, static analysis can always only go so far. Whatever it can do is better than nothing. I often just have plain syntax errors, like a missing `end` at the end of a `lane` and stuff like that.

**Comment by lacostej** [comment]
@KrauseFx ruby-lint is able to generate definitions: https://github.com/YorickPeterse/ruby-lint/blob/master/doc/definitions.md#generating-definitions so it should be possible to add definitions to actions (even loaded / remote plugins when supported)

**Comment by ohwutup** [comment]
This would be really awesome! Maybe something to use the new plugin infrastructure for? Going to close this for now as it has been quiet for some time now, but we should think about implementing this as a plugin.
