### ISSUE TITLE
Snapshot: Configure amount of concurrent simulators

### ISSUE THREAD

**Issue by xaverlohmueller** [fastlane/fastlane#13578]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

Is there a way to configure how many concurrent simulators are launched when running `snapshot` with `concurrent_simulators` set to `true`?
We want to run snapshot against 4 devices and currently, fastlane will run 3 devices in parallel and 1 more after that.

We'd like to run all 4 of them in parallel, or run on 2 devices after one another, but we can't find a way to configure this anywhere...

**Comment by dstranz** [comment]
@xaverlohmueller It's defined as number of CPU cores - 1 with following explanation:
```
    # With Xcode 9's ability to run tests on multiple concurrent simulators,
    # this method sets the maximum number of simulators to run simultaneously
    # to avoid overloading your machine.
```
source: https://github.com/fastlane/fastlane/blame/master/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb#L31

It could be easily modified with some preference but I'm not sure if it's recommended considering above comment.

**Comment by xaverlohmueller** [comment]
Thanks for the pointer!
I suppose that default makes sense and, as you said, overriding it is likely a bad idea.

**Comment by koraktor** [comment]
I don‘t think the default is good in all situations and overriding should be possible if anyone really needs it.
A Mac mini with i7 (6 cores and hyper-threading), but only 8 GB RAM will choke on the default.
