### ISSUE TITLE
[Regression] Broken pipe when uploading binaries

### ISSUE THREAD

**Issue by allenhsu** [fastlane/fastlane#13572]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: [e.g. `2.107.0`]
- Last working version: [e.g. `2.105.2`]

### Regression Description
We're using fastlane to deploy iOS apps on CI server. We have proxy set up on CI server, I'm not sure about the root cause but we're not able to upload binaries with DAV option on, via this proxy. I noticed that in fastlane 2.106.0 (https://github.com/fastlane/fastlane/pull/13404) DAV is by default turned on, it makes our CI server not able to upload binaries. Is it possible to revert the default behavior so it's consistent with previous versions?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.4.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.19.1                          |
| Installation Source         | ~/.rbenv/versions/2.4.4/bin/fastlane        |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.4/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| awesome_print             | 1.8.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.3        |
| clipboard                 | 1.1.2        |
| gherkin                   | 4.1.3        |
| cucumber-core             | 1.5.0        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.13.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 2.99.0       |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.9        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| command_runner_ng         | 0.1.4        |
| thor                      | 0.20.0       |
| run_loop                  | 2.7.1        |
| slowhandcuke              | 0.0.3        |
| calabash-cucumber         | 0.21.5       |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.6        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.4.1        |
</details>

*generated on:* **2018-10-22**
</details>

**Comment by robmaceachern** [comment]
You should be able to use the Signiant delivery protocol by overriding the `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` environment variable.
```
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
```

**Comment by joshdholtz** [comment]
@allenhsu Does @robmaceachern solution solve your issue?

**Comment by allenhsu** [comment]
@joshdholtz yes thanks @robmaceachern

**Comment by joshdholtz** [comment]
@robmaceachern Thanks so much for answering that issue! ❤️

**Comment by janpio** [comment]
@robmaceachern Why does this work as a solution (besides that is reverting back to the old state)? Should we add this to some documentation somewhere?

**Comment by robmaceachern** [comment]
@janpio I'm not sure exactly why it was failing in this case but the issue description mentions DAV being disabled via a network proxy. I think each protocol has their own failure modes depending on local network/firewall settings. It looks like there is already a bit of documentation [here](https://docs.fastlane.tools/actions/pilot/#firewall-issues) but it could be improved to show all the available protocol options (DAV, Signiant, and (I think) Aspera).

Some other potential improvements I can think of:
- Figure out some way to verify network conditions are suitable for the selected protocol before attempting upload and provide better error messaging.
- Auto-retry with alternate protocol if we can detect a firewall-related failure.
- Promote the preferred Pilot protocol configuration to a regular parameter (instead of an environment variable).
