### ISSUE TITLE
Deliver States Waiting App Store Connect Processing Even though Build has been Processed Already.

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#13577]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using deliver to upload an app to App Store Connect with version 2.02.30(2.2.30) with the following parameters:
![image](https://user-images.githubusercontent.com/23205547/47324082-49761c00-d613-11e8-9698-fd60497e808a.png)

After the upload, I see that the console:

```
INFO [2018-10-23 00:48:30.07]: You can tweet: "App Store Connect #iosprocessingtime 51 minutes"
INFO [2018-10-23 00:49:07.19]: Waiting App Store Connect processing for build 2.2.30 (2.2.30)... this might take a while...
```

However, the build has already been processed. On the Activity section on App Store Connect, I see the version as **2.02.30** and the build as **2.2.30**. So it looks like Deliver command is truncating the leading zeros from the **CFBundleShortVersionString**. However, according to the Apple documentation the leading zeros are only truncated for [CFBundleVersion](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364) and not [CFBundleShortVersionString](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349).

**Comment by Nov1kov** [comment]
what fastlane build do you use?
probably the [same issue](https://github.com/fastlane/fastlane/issues/13372)

**Comment by janpio** [comment]
@pparmaei can you share the fastlane version you are using? Did similar version numbers cause problems in the past already?
The issues @Nov1kov linked to and created is very similar, and points to this being a regression of a change made in fastlane.

**Comment by pparmaei** [comment]
Hello @janpio 
Using version 2.107.0

I have come across the same issue with multiple different apps that have leading zeros in their release version.
