### ISSUE TITLE
`commit_version_bump` after setting `automatic_code_signing` to FALSE

### ISSUE THREAD

**Issue by Drwalcore** [fastlane/fastlane#13580]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I'd like to `increment_build_number` and `commit_version_bump` to repository after setting `automatic_code_signing` to *false*.

#### Question Description

 As I've observed both 
`automatic_code_signing(path: "*.xcodeproj", use_automatic_signing: false)`
and
`increment_build_number` [following documentation](
https://docs.fastlane.tools/actions/commit_version_bump/#commit_version_bump), are touching *.xcodeproj/project.pbxproj* file. 

As it is potentially allowed because no are no other uncommitted changes in repo, so it will commit `CODE_SIGN_MANUAL = Manual;` and similar changes to the current branch.
 Our testflight lane is in `fastlane env`

My teammate found **temporary** solution to this just to avoid manual version bumping and avoid AppStore connect problems.
```ruby
    increment_build_number({
      build_number: latest_testflight_build_number(username: username, team_id: team_id, app_identifier: app_identifier) + 1
    })
``` 
But I'd like to have bumped version committed by CI, because that how it should be done to avoid problems with build versions in future.
Is it possible to work around this to commit only bumped build number? I thought about setting back to automatic code signing, but that could crash next steps in my lane because I am exporting provisioning profile. 

With regards,
Drwalcore

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.rvm/gems/ruby-2.2.3/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
if !is_ci # To prevent potential updates that would crash CI build after fastlane update.
  update_fastlane
end
default_platform(:ios)

platform :ios do

  desc "Try to recover from build errors"
  lane :doctor do
    clean_cocoapods_cache
    sh "cd .. && rm -rf Pods"
    clear_derived_data
  end

  desc "Upload on-demand a new build to Testflight for internal testing."
  lane :testflight_release do

    username = "*****"
    team_id = "*****"
    app_identifier = "*****"
    scheme = "*****"
    provisioning_profile_specifier = "*****"
    match_git_branch = "appstore"

    xcode_select("/Applications/Xcode.app")

    automatic_code_signing(path: "***.xcodeproj", use_automatic_signing: false)
    match(
     username: username,
     team_id: team_id,
     app_identifier: app_identifier,
     git_branch: match_git_branch,
     force: false,
     readonly: false
     )

    doctor
    cocoapods

    #TODO: - commit version bump to repository.
    # build_number = increment_build_number
    # commit_version_bump(message:"[ci-skip] Version Bump to #{build_number}")

    increment_build_number({
      build_number: latest_testflight_build_number(username: username, team_id: team_id, app_identifier: app_identifier) + 1
    })

    #Explanation: https://github.com/fastlane/fastlane/issues/12849#issuecomment-404978983

    settings_to_override = {
      :BUNDLE_IDENTIFIER => app_identifier,
      :PROVISIONING_PROFILE_SPECIFIER => provisioning_profile_specifier,
      :DEVELOPMENT_TEAM => team_id
      }

    gym(
     scheme: scheme,
     clean: true,
     xcargs: settings_to_override,
     export_method: "app-store",
     export_options: {
        provisioningProfiles: {
            app_identifier => provisioning_profile_specifier
        }
      }
     )

    pilot(
     username: username,
     team_id: team_id,
     app_identifier: app_identifier,
     skip_submission: false,
     skip_waiting_for_build_processing: true
     )

  end
end

after_each do |lane|
  if is_ci && ENV["SLACK_URL"]
    payloads = [:test_result, :git_branch, :lane]
    slack(
      message: nil,
      success: true,
      icon_url: ENV["SLACK_ICON_URL"],
      default_payloads: payloads
      )

    push_to_git_remote(
      remote: "origin",
      local_branch: "HEAD",
      remote_branch: "development",
      force: true,
      tags: true
      )
  end

  clean_build_artifacts
end

error do |lane, exception|
  if is_ci && ENV["SLACK_URL"]
    payloads = [:message, :test_result, :git_branch, :lane]
    slack(
      message: exception.message,
      success: false,
      icon_url: ENV["SLACK_ICON_URL"],
      default_payloads: payloads
      )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.7.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| fastimage                 | 2.1.4        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.6       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
</details>

*generated on:* **2018-10-24**
</details>

**Comment by janpio** [comment]
I think I understood what you are doing and what commands/actions you are using, but what is the actual problem? Do you want to use this one specific action to commit something, but no include other uncommitted changes done by another action?

**Comment by Drwalcore** [comment]
@janpio Sorry for not getting there earlier before bots kicked in. In attached screenshot is screenshot of stash I have to apply afterwards, before **manually** committing version bump.
I cannot commit files automatically via fast lane, because changes from stash will be committed.
I am looking for a way to automatically revert those changes from Manual to Automatic, where Manual is a must during signing process in my project.
![zrzut ekranu 2019-01-02 10 03 53](https://user-images.githubusercontent.com/13233783/50585686-84e46080-0e76-11e9-8c39-1ce3e2481d07.png)
