### ISSUE TITLE
`join': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by eriadam** [fastlane/fastlane#13586]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The issue defined in [12789](https://github.com/fastlane/fastlane/issues/12789) still exists. It is not so rare anymore, happens now on a daily basis on different pipelines.

When restarting the pipeline, the same command runs just fine.

##### Complete output when running fastlane, including the stack trace and command used

```
+ fastlane scan
[14:38:51]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:50:in `join': no implicit conversion of nil into String (TypeError)
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:50:in `fastfile_path'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:167:in `available_lanes'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:74:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.3       |
| fastimage                 | 2.1.4        |
| bundler                   | 1.16.5       |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.10.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| openssl                   | 2.1.1        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-10-25**
</details>

**Comment by JesseScott** [comment]
I get this quite often with the `changelog_from_git_commits` command - because my Jenkins machine does a shallow clone, and the text for the changelog is based off of the commit messages since the last tag, if it doesn't grab the tag it won't be able to do the string diff...

**Comment by hactar** [comment]
Played around with this a bit. It appears that, at random `self.path` returns different values within the same run. I haven't been able to trigger the "nil" crash while having my little Debug message running, but I've caught weird situations none the less.

See https://github.com/fastlane/fastlane/blob/230cfa1d4a3d2360ca960decfc3ddb2948cd39e1/fastlane_core/lib/fastlane_core/fastlane_folder.rb#L8

Here is a "normal run" with outputting the self.path when ever it is called.:

```
fastlane scan
[✔] 🚀
[15:10:34]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: DEBUG: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[15:10:34]: Successfully loaded '/private/var/jenkins/workspace/eature_automated_ui_testing-HAUUQVMMPHV35SP6LKC42APFYTTSHL32RDFNRL2BCVVTHEQ5POUQ/fastlane/Scanfile'
```

Here's the exact same run, nothing changed, just run at a different moment in time:
```
$ fastlane scan
[✔] 🚀
[14:43:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:43:43]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:43]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:43]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:43]: Debug: self.path is now './' FOLDER_NAME was 'fastlane'
[14:43:43]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:43]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Debug: self.path is now './fastlane/' FOLDER_NAME was 'fastlane'
[14:43:44]: Successfully loaded '/private/var/jenkins/workspace/eature_automated_ui_testing-HAUUQVMMPHV35SP6LKC42APFYTTSHL32RDFNRL2BCVVTHEQ5POUQ/fastlane/Scanfile'
```

Notice how there's one call where self.path is suddenly './' in the middle of the run.

I have no clue what is causing this glitch.

**Workaround**
I've hardcoded self.path to return "./fastlane" in https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/fastlane_folder.rb#L8. Add `return './fastlane/'` as line 9 (make sure to set it to what ever you actually use as the fastlane path. ./fastlane/ is the default value).

**Comment by janpio** [comment]
Thanks @eriadam and @hactar - indeed a super strange one. Let's merge this issue into https://github.com/fastlane/fastlane/issues/12789 so we only have one location to track and discuss this.
