### ISSUE TITLE
cLint always failing to run

### ISSUE THREAD

**Issue by bmctigue** [fastlane/fastlane#1359]
Hi,

I'm trying to run ocLint in its own lane with the following parameters:

oclint(
  compile_commands: 'compile_commands.json',    # The JSON compilation database, use xctool reporter 'json-compilation-database'
  select_regex: /.*.m/,     # Select all files matching this regex
  exclude_regex: /.*Test.m/,              # Exclude all files matching this regex
  report_type: 'html',                   # The type of the report (default: html)
  max_priority_1: 10,                   # The max allowed number of priority 1 violations
  max_priority_2: 100,                  # The max allowed number of priority 2 violations
  max_priority_3: 1000,                 # The max allowed number of priority 3 violations
  thresholds: [                         # Override the default behavior of rules
    'LONG_LINE=200',
    'LONG_METHOD=200'
  ],
  enable_rules: [                       # List of rules to pick explicitly
    'DoubleNegative',
    "SwitchStatementsDon'TNeedDefaultWhenFullyCovered"
  ],
  disable_rules: ["GotoStatement"],     # List of rules to disable
  list_enabled_rules: true,             # List enabled rules
  enable_clang_static_analyzer: true,   # Enable Clang Static Analyzer, and integrate results into OCLint report
  enable_global_analysis: true,         # Compile every source, and analyze across global contexts (depends on number of source files, could results in high memory load)
  allow_duplicated_violations: true     # Allow duplicated violations in the OCLint report
)

The error I'm seeing is:
sh: line 1: 25307 Segmentation fault: 11  oclint -report-type=html -o=oclint_report.html -list-enabled-rules -rc=LONG_LINE=200 -rc=LONG_METHOD=200 -rule DoubleNegative -rule SwitchStatementsDon\'TNeedDefaultWhenFullyCovered -disable-rule GotoStatement -max-priority-1=10 -max-priority-2=100 -max-priority-3=1000 -enable-clang-static-analyzer -enable-global-analysis -allow-duplicated-violations ...

The issue number generated is 59bd4d6b3c71564fc2782c8a9aadf8e1.

Any ideas?

Thanks!

**Comment by vpolouchkine** [comment]
Does it run outside `fastlane`?

**Comment by bmctigue** [comment]
Hi, yes, it runs outside fastlane. I run the following command which include directories to exclude:
oclint-json-compilation-database -i .*.m -e betterupTests -e Pods -e betterup/vendor -e betterup/categories -e betterup/camera.
Thanks for responding.

**Comment by bmctigue** [comment]
This is working now, I suspect there was a problem with the rules to exclude. I had a working .oclint file and I copied the settings out of there to the fast file and oclint is working now. Sorry for the false alarm.
