### ISSUE TITLE
Supporting App Store Promotion images in App Store's in-app purchases

### ISSUE THREAD

**Issue by mmenu-mantano** [fastlane/fastlane#13590]
#### Motivation Behind Feature

I'm looking to automate the creation of an in-app purchase on the App Store with its Promotion Image. Unfortunately, it doesn't seem to be supported by Spaceship.

https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/iap.rb

#### Feature Description

It probably just requires to add a field similar to review_screenshot, for example "promotion_image" with dimensions 1024x1024.
I'm willing to contribute if you have any pointers on how to find the required fields to send to App Store Connect.

<img width="979" alt="bildschirmfoto 2018-10-25 um 18 34 27" src="https://user-images.githubusercontent.com/6561221/47516028-a62c3d80-d884-11e8-9c98-e49ee9ad699d.png">

**Comment by janpio** [comment]
Sounds like a useful feature.
