### ISSUE TITLE
Malformed version number string unknown error scan

### ISSUE THREAD

**Issue by starback** [fastlane/fastlane#13599]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`fastlane test` was working, but now it returns a `Malformed version number` error (pasted below). From what I can tell this error may be similar to #12734 (closed, fixes listed in #12734 do not resolve the issue).

I have also tried the following:
* `fastlane snapshot reset_simulators`
* Ensuring `xcode-select` path is properly set
* Removing simulators and manually adding our simulator of choice (specified by `ScanFile`) using `rm -rf ~/Library/Developer/CoreSimulator/Profiles/Runtimes/* && xcrun simctl create "iPhone 6" com.apple.CoreSimulator.SimDeviceType.iPhone-6 com.apple.CoreSimulator.SimRuntime.iOS-12-0`
* Running `killall "Simulator" 2> /dev/null; xcrun simctl erase all`
* Restarting / killing Xcode
* Updating all installed gems

##### Complete output when running fastlane, including the stack trace and command used

`$ fastlane test` output:
```
WARN [2018-10-26 14:25:44.36]: Lane Context:
INFO [2018-10-26 14:25:44.36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
ERROR [2018-10-26 14:25:44.36]: Malformed version number string unknown

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | opt_out_usage              | 0           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 💥   | scan                       | 10          |
+------+----------------------------+-------------+

ERROR [2018-10-26 14:25:44.36]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Malformed version number string unknown

URL: https://api.github.com/search/issues?q=Malformed%20version%20number%20string%20unknown+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/bin/fastlane)
ArgumentError: [!] Malformed version number string unknown
  /Users/distiller/.rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/version.rb:208:in `initialize'
  /Users/distiller/.rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/version.rb:199:in `new'
  /Users/distiller/.rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/version.rb:199:in `new'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/scan/lib/scan/detect_values.rb:84:in `block in filter_simulators'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/scan/lib/scan/detect_values.rb:83:in `select'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/scan/lib/scan/detect_values.rb:83:in `filter_simulators'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/scan/lib/scan/detect_values.rb:113:in `detect_simulator'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/scan/lib/scan/detect_values.rb:32:in `set_additional_default_values'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/scan/lib/scan/module.rb:17:in `config='
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/run_tests.rb:17:in `run'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:141:in `block (2 levels) in parsing_binding'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/bin/fastlane:23:in `load'
  /Users/distiller/project/vendor/bundle/bin/fastlane:23:in `<top (required)>'
Exited with code 1
```

### Environment

`fastlane env` output (only included relevant `test` lane from `Fastfile`):

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.13.6                                        |
| Ruby                        | 2.4.4                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.19.1                             |
| Installation Source         | ~/project/vendor/bundle/bin/fastlane           |
| Host                        | Mac OS X 10.13.6 (17G65)                       |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.4/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode-10.app/Contents/Developer/ |
| Xcode Version               | 10.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage
fastlane_version "2.107.0"
default_platform :ios
skip_docs

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(include_simulator_logs: false)
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| scoop-mobile-scripts      | 0.1.0        |
</details>

*generated on:* **2018-10-26**
</details>

**Comment by dreymonde** [comment]
Confirmed: the issue is still persisting

**Comment by ldiqual** [comment]
@joshdholtz Not completely sure how get the attention of the fastlane team here, but this issue seems to be affecting several other people now and we're resorting to using xcodebuild directly. Is there any way we can help you debugging this?

**Comment by aboodmufti** [comment]
Running the following commands fixed it for me:
```
sudo xcrun simctl shutdown all
```
```
sudo xcrun simctl erase all
```

**Comment by starback** [comment]
I ran the commands above and the same error still occurs.

Tool            | Tool version number command        | Output
----------- |------------------------------------|------------
ruby            | `ruby --version`                                 | `ruby 2.5.3p105`
Xcode         | `xcodebuild -version`                       | `Xcode 10.0 Build version 10A255`
Mac OS     | `sw_vers`                                            | `ProductName:Mac OS, ProductVersion:10.13.6, BuildVersion:	17G65`

@aboodmufti What is your output for the above?

**Comment by aboodmufti** [comment]
Command | Output
------------ | -------------
`ruby --version` | `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`
`xcodebuild -version` |  `Xcode 10.1` <br>`Build version 10B61`
`sw_vers` | `ProductName:	Mac OS X`<br>`ProductVersion:	10.13.6` <br>`BuildVersion:	17G65`

@starback from my research yesterday, it doesn't look like this error is fastlane specific. From what I saw, even cocoapods had this same error message at one point. It looks like more of a ruby/gems error? 

when I ran `sudo xcrun simctl shutdown all`, it started installing all simulators, it looks like they weren't installed properly? 
This error only appeared after Xcode got automatically updated to Xcode 10.1

**Comment by simnon** [comment]
| Tool   | Tool version number command | Output                                                                 |
|--------|-----------------------------|------------------------------------------------------------------------|
| ruby   | ruby --version              | ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17] |
| Xcode  | xcodebuild -version         | Xcode 10.0 Build version 10A255                                        |
| Mac OS | sw_vers                     | ProductName:,Mac OS X ProductVersion:,10.13.6 BuildVersion:,17G2307    |


Getting same issue. I have multiple versions of xcode installed on machine. 
<details>
```
[ERROR] ArgumentError: [!] Malformed version number string com.apple.CoreSimulator.SimRuntime.iOS-11-4
[ERROR]   /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/version.rb:207:in `initialize'
[ERROR]   /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/version.rb:199:in `new'
[ERROR]   /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/version.rb:199:in `new'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/scan/lib/scan/detect_values.rb:84:in `block in filter_simulators'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/scan/lib/scan/detect_values.rb:83:in `select'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/scan/lib/scan/detect_values.rb:83:in `filter_simulators'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/scan/lib/scan/detect_values.rb:113:in `detect_simulator'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/scan/lib/scan/detect_values.rb:32:in `set_additional_default_values'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/scan/lib/scan/module.rb:17:in `config='
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/run_tests.rb:17:in `run'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[ERROR]   /Users/scou0002/.gem/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'

```
</details>

**Comment by windaddict** [comment]
Quitting the Simulator app resolved this issue for me.

**Comment by dmarjanovic** [comment]
In our case suggestions suggestions above did not help. The problem originally appeared after installing newer Xcode version using xcversion so the problem automagically disappeared after macOS reboot.

**Comment by JoeAlamo** [comment]
I am still occasionally encountering this issue. For context, this is on a build runner with multiple versions of Xcode installed via `xcode-install` - 9.4.1, 10, 10.1.

`Malformed version number string com.apple.CoreSimulator.SimRuntime.iOS-12-0`
