### ISSUE TITLE
[sigh]  How to get the certificate cert_id?

### ISSUE THREAD

**Issue by THandsonwu** [fastlane/fastlane#13596]
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by janpio** [comment]
Can you provide some more context about what you are trying to achieve and why?

**Comment by THandsonwu** [comment]
> Can you provide some more context about what you are trying to achieve and why?

Thank you for your reply, my question is when sigh, my developer center team has two product certificate, if i don't specify the latest certificate, the default selection will be the first certificate ,which use to generated PP file, but I don't know how to use the API to get the certificate ID! Also  did not show the certificate code inside keychain.This is my problem.
` sigh(
         force:true,
         #skip_certificate_verification:true,
         username: "pcplatxxxx@163.com",
         app_identifier: app_identifier,
         team_id:"xxxxxxxxx",
         cert_id: "U6YSHRAXXX",#this parameter is my question！！！
         #provisioning_name:"#{app_identifier}pp",
         filename:"embedded.mobileprovision"
    )`

**Comment by jcislinsky** [comment]
+1
