### ISSUE TITLE
build_app. beta

### ISSUE THREAD

**Issue by JakeTorres** [fastlane/fastlane#13595]
Could not find lane 'ios beta'. Available lanes: ios custom_lane

I try it again, still not, work!

**Comment by janpio** [comment]
Does your `Fastfile` contain a lane `beta`? 
Seems you only have a lane `custom_lane` in there.
When you just run `fastlane`, it should return all the available lanes to you.

**Comment by janpio** [comment]
weikeyan = JakeTorres?

The `Fastfile` you posted doesn't include a `:beta` lane, so you won't be able to call `fastlane beta` on the command line until you add one.

What exactly are you trying to do?

**Comment by JakeTorres** [comment]
thanks, I try it!

**Comment by weikeyan** [comment]
> weikeyan = JakeTorres?
> 
> The `Fastfile` you posted doesn't include a `:beta` lane, so you won't be able to call `fastlane beta` on the command line until you add one.
> 
> What exactly are you trying to do?

already  fixed ，thanks
