### ISSUE TITLE
supply giving stagedCountryTargetingNotSupported

### ISSUE THREAD

**Issue by gwynjudd** [fastlane/fastlane#13602]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

A previously working setup has stopped working with this error. Prior to it stopping working, we had done a rollout to production in a different release track with the available countries set to Japan. This seems likely to have caused the issue as before this issue arose, we had not used staged country targeting.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[CI-CD Push Android Shell to play store] $ /bin/sh -xe /var/folders/01/nxnqrpnd6299tdg0f0cksgyw0000gp/T/jenkins12000835772066482332.sh
+ /usr/local/bin/fastlane supply --apk platforms/android/app/build/outputs/apk/release/StayinFront.Touch-release.apk --track internal --json_key '****' --skip_upload_images --skip_upload_screenshots --package_name stayinFront.touch
[12:21:41]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[12:21:41]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m

+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                         [32mSummary for supply 2.107.0[0m                                                                                          |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| apk                     | platforms/android/app/build/outputs/apk/release/StayinFront.Touch-release.apk                                                                                                     |
| track                   | internal                                                                                                                                                                          |
| json_key                | **** |
| skip_upload_images      | true                                                                                                                                                                              |
| skip_upload_screenshots | true                                                                                                                                                                              |
| package_name            | stayinFront.touch                                                                                                                                                                 |
| skip_upload_apk         | false                                                                                                                                                                             |
| skip_upload_aab         | false                                                                                                                                                                             |
| skip_upload_metadata    | false                                                                                                                                                                             |
| validate_only           | false                                                                                                                                                                             |
| check_superseded_tracks | false                                                                                                                                                                             |
| timeout                 | 300                                                                                                                                                                               |
| deactivate_on_promote   | true                                                                                                                                                                              |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

[31m
[!] Google Api Error: stagedCountryTargetingNotSupported: Staged rollout with country targeting cannot be updated via API[0m
[12:21:43]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
Build step 'Execute shell' marked build as failure
Finished: FAILURE</pre>
</details>

### Environment

<details>
  <pre>[CI-CD Push Android Shell to play store] $ /bin/sh -xe /var/folders/01/nxnqrpnd6299tdg0f0cksgyw0000gp/T/jenkins13634632029386674569.sh
+ /usr/local/bin/fastlane env
[13:43:56]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[13:43:56]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
[13:43:56]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.5.4 (Apple Git-61)                               |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/xCode/7.2.1/Xcode.app/Contents/Developer/        |
| Xcode Version               | 7.2.1                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.6       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 2.9.0        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-10-29**
</details>
[13:43:57]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[13:43:57]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m
[13:43:57]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
Finished: SUCCESS</pre>
</details>

**Comment by janpio** [comment]
The error message seems to come from the Google API directly:

> [!] Google Api Error: stagedCountryTargetingNotSupported: Staged rollout with country targeting cannot be updated via API

Can you elaborate on your "setup" of rollouts for this app please? Maybe this somehow influences what is happening here.

**Comment by janpio** [comment]
Is it possible that Google somehow "blocked" all rollouts via API as it currently doesn't support this specific case when limiting a rollout to a few countries?

**Comment by gwynjudd** [comment]
I think that is certainly possible. I just don't know for sure. Sometimes, it can be helpful to log an issue in this kind of situation as a way to help figure things out and document a behaviour.

**Comment by janpio** [comment]
Yes, absolutely - especially to see if other people also have this issue. 
If I ever stumble over it, I will remember this issue here for sure :)

If you want to go the extra mile, create a new app for a dummy project and try to recreate the situation there in as less steps as possible and post those here. THen it will be easier to recreate and follow.
