### ISSUE TITLE
Fastlane works fine on terminal but fails with jenkins pipeline  

### ISSUE THREAD

**Issue by praveenBirdzi** [fastlane/fastlane#13605]
My fastlane build works fine without any issue with terminal , but it always fails with jenkins pipeline 

Jenkins Consol Output
<img width="737" alt="screen shot 2018-10-29 at 12 02 03 pm" src="https://user-images.githubusercontent.com/39327273/47634665-52696f00-db78-11e8-84f8-5ce3a3bd9999.png">

Terminal Output
<img width="857" alt="screen shot 2018-10-29 at 12 09 16 pm" src="https://user-images.githubusercontent.com/39327273/47634706-7036d400-db78-11e8-9a7b-f20253e92a98.png">
<img width="957" alt="screen shot 2018-10-29 at 12 09 48 pm" src="https://user-images.githubusercontent.com/39327273/47634712-75941e80-db78-11e8-9425-b78b695e93a1.png">

Lane code :

lane :build do
	#sync_code_signing(type: "appstore")
	increment_build_number
	get_certificates           # invokes cert
  	get_provisioning_profile   # invokes sigh
  	build_app(export_xcargs: "-allowProvisioningUpdates")
end
appreciate quick response and help

**Comment by praveenBirdzi** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
before_all do
    ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
    ENV["FASTLANE_USER"] = “XXXXX”
    ENV["FASTLANE_PASSWORD"] = “XXXXXXX”
  end
  desc "Push a new beta build to TestFlight"
  lane :build do
	#sync_code_signing(type: "appstore")
	increment_build_number
	get_certificates           # invokes cert
  	get_provisioning_profile   # invokes sigh
  	build_app(export_xcargs: "-allowProvisioningUpdates")
    
    
  end
lane :pods do
    cocoapods(
  clean: true,
  podfile: "./Podfile"
)
  end
 lane :tests do
    #run_tests(‘XXX’)
	scan
  end

lane :deploy do
   build
   upload_to_testflight
   pilot(skip_waiting_for_build_processing: true)
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(“XXXX”) # The bundle identifier of your app
apple_id(“XXXX”) # Your Apple email address

itc_team_id(“XXXXX”) # App Store Connect Team ID
team_id(“XXX”) # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.5       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.2        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>


*generated on:* **2018-10-30**
</details>


Here is Fastlane Env

**Comment by praveenBirdzi** [comment]
> It seems like this issue might be related to code signing 🚫
> 
> Have you seen our new [Code Signing Troubleshooting Guide](https://docs.fastlane.tools/codesigning/getting-started/)? It will help you resolve the most common code signing issues 👍

if its Code signing issue then why the same lane is working on terminal

**Comment by olsonkaleb** [comment]
I had the same issue, though it also happened outside of Jenkins. Fastlane would randomly fail to finish just like your screenshot. It seems to be a threading issue related to analytics, specifically the finalize_session method in the analytics_sessions class responsible for closing all analytics threads.

I'm not smart enough to know what the real fix for this would be but I can tell you that turning off analytics entirely fixed it for me. You can do that by adding **opt_out_usage** to your fastfile or in my case i just set the environment variable **FASTLANE_OPT_OUT_USAGE** to **YES**.

Hope this helps!

**Comment by TouSC** [comment]
you may want to move your certification in keychain from system to login

**Comment by praveenBirdzi** [comment]
> you may want to move your certification in keychain from login to system

@TouSC The certificates are already there in both the keychain

**Comment by praveenBirdzi** [comment]
> I had the same issue, though it also happened outside of Jenkins. Fastlane would randomly fail to finish just like your screenshot. It seems to be a threading issue related to analytics. Specifically the finalize_session method in the analytics_sessions class responsible for closing all analytics threads, mine would hang there forever.
> 
> I'm not smart enough to know what the real fix for this would be but I can tell you that turning off analytics entirely fixed it for me. You can do that by adding **opt_out_usage** to your fastfile or in my case i just set the environment variable **FASTLANE_OPT_OUT_USAGE** to **YES**.
> 
> Hope this helps!

no luck after adding FASTLANE_OPT_OUT_USAGE to YES

**Comment by janpio** [comment]
Have you looked into using https://docs.fastlane.tools/actions/setup_jenkins/ @praveenBirdzi?
