### ISSUE TITLE
fastlane with Xcode 10 on OS Mojave reporting errors

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#13601]
Hi,

I have been using fastlane successfully. But after the latest OS update to Mojave and Xcode 10, the packing is falling. The archive succeeds and the log also shows that the archive succeeded. But I am getting this strange warning and error after the update. 

```
<unknown>:0: warning: using sysroot for 'MacOSX' but targeting 'Watch'
```

- lots of these warnings.

```
error: SwiftyJSON not found in dylib search path

Error Domain=IDEFoundationErrorDomain Code=1 "ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: Command exited with pid 87842 exit 1:

[31mError packaging up the application[0m
```

I updated to the latest version of fastlane but the error persists.

**Comment by janpio** [comment]
Could you please post the whole output you are getting?
Also follow what @fastlane-bot asked?

**Comment by santoshshetty2612** [comment]
@janpio Sorry for the delay. The reason for the error was that I added the SwiftyJSON framework in the watch target. I have resolve it. This is not an issue with Fastlane.
