### ISSUE TITLE
Fastlane and Cocoapods 1.0.0

### ISSUE THREAD

**Issue by oozbekta** [fastlane/fastlane#1361]
Hi,

Cocoapods 1.0.0.beta.3 depends on xcodeproj version 1.0.0.beta.1 which causes dependency issues with fastlane (expects xcodeproj anything less than 1.0.0). I know Cocoapods and xcodeproj are still in beta version and it doesn't make sense to bump those in fastlane until they are released. However, is there a fastlane branch which points to those versions so that we start our migration to Cocoapods 1.0?

**Comment by diegorozen** [comment]
I am facing the same problem. @KrauseFx is there a plan already for supporting Cocoapods 1.x? Thanks!!

**Comment by rtruxler** [comment]
me too. I would love to migrate to coacoapods 1.x but can't b/c of fastlane.

**Comment by KrauseFx** [comment]
Hey everyone, I prepared a fix, this will be available with the next release :+1: https://github.com/fastlane/fastlane/pull/1389

**Comment by rtruxler** [comment]
Thanks @KrauseFx !
