### ISSUE TITLE
Support with Fastlane Building and Code Signing using in React-Native Project

### ISSUE THREAD

**Issue by meehanman** [fastlane/fastlane#13613]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] Updated fastlane to the latest version
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### System Information
MacOS Seirra (10.12.6)
XCode 9.1 (9B55)
fastlane 2.107.0

### Question Subject
Support with Fastlane Building and Code Signing using React-Native. 

#### Question Description
Hi, I've been having trouble with our Deployment Process in regards to getting our iOS application signed and built. I believe this to be a configuration/code signing issue. 

##### CodeSigning

I'm currently using a **react-native** project that provides the appropate android and ios folders that are ready to be built. I have ran `Match Nuke` first for all deployment types (develoment, adhoc, appstore) and I deleted my keychain etc to give my Mac only the correct provisioing-profiles, certificates and private keys on my keychain / folders and these are all saved in the Match gitRepo. 

I've read the [codesigning.guide](https://codesigning.guide) and [Debugging Codesigning Issues](https://docs.fastlane.tools/codesigning/troubleshooting/#debugging-codesigning-issues) (I think in completeness)

##### ApplicationName

When I open up XCode I can see 4 targets (ApplicationName, ApplicationNameTests, ApplicationName-tvOS and ApplicationName-tvOSTests). I then can disable `Automatically manage signing` and set my provising profiles (Signing (Debug & Release)) to `match AppStore com.OrganisationName.ApplicationName`.
There are no errors showing and I can then set the device to `Generic iOS Device` and Archive the ipa to build the app. 

##### ApplicationNameTests
I'm not too sure if this is important to the building of the _ApplicationName_ but when I remove `Automatically manage signing` I can manually set the `Team` and `Signing certificate` and there are no errors shown.

#### Question Description Continued

I've tried using the lanes below to sign my application using `match` and build my app using `gym` but I get a wide range of errors (See below). _I've no idea where to go from now to get Fastlane building my app and getting the error message -fff...ffff is useless from XCode in a debugging standpoint._ 

**What can I do to further debug this problem?** 

[View Tail of Log 1 -ffffffffffffffff (Full Log can be provided on request)](https://gist.github.com/meehanman/79ba408fb9446a582287899ae8847529)

Ran after deleting *-tvOS and *tests by right-click TARGETS and clicking Delete
[View Full Log 1.1](https://gist.github.com/meehanman/cce5806b63e80da1ad80c14f151aca42)

#### Factfile

I've included 3 test lanes I've tried (I've tried many more) and a release lane I expect my final lane to look like for our CI (Teamcity).
1.  Turn Code Signing Off, Match appStore, Gym AppStore
2.  Same as 1 but with update_project_provisioning
3.  Essentially more update_project_provisioning and targeting the Tests project
4.  Release - After research, what I expect to have. 
```
default_platform(:ios)

	platform :ios do
		desc "Test Lane Fastlane 1"
		lane :test1 do 
			automatic_code_signing(code_sign_identity:"iPhone Distribution", use_automatic_signing: false)
			match(type:"appstore", readonly:true)
			gym(scheme:"CompanyName", export_method:"app-store", scheme: "CompanyName")
		end

		desc "Test Lane Fastlane 1.1"
		lane :test11 do 
			automatic_code_signing(code_sign_identity:"iPhone Distribution", use_automatic_signing: false)
			
			match(type:"development", readonly:true)
			match(type:"appstore", readonly:true)
			update_project_provisioning(
				xcodeproj: "CompanyName.xcodeproj",
				target_filter: "CompanyName",
				profile:ENV["sigh_com.CompanyName.myCompanyName_development_profile-path"],
				build_configuration: "Debug",
				code_signing_identity:"iPhone Developer: Company Name Retail (M400000003)"
			)
			
			update_project_provisioning(
				xcodeproj: "CompanyName.xcodeproj",
				target_filter: "CompanyName", 
				profile:ENV["sigh_com.CompanyName.myCompanyName_appstore_profile-path"],
				build_configuration: "Release",
				code_signing_identity:"iPhone Distribution: Company Name Retail (ZY00000000K)"
			)
			automatic_code_signing(use_automatic_signing: false)
			gym(scheme:"CompanyName", export_method:"app-store", scheme: "CompanyName")
		end
 
		desc "Test Lane Fastlane 2"
			lane :test2 do 
			automatic_code_signing(code_sign_identity:"iPhone Distribution", use_automatic_signing: false)
			match(
				app_identifier: "com.CompanyName.myCompanyName",
				type: "appstore",
				readonly:true
			)
			update_project_provisioning(
				xcodeproj: "CompanyName.xcodeproj",
				target_filter: "CompanyName*",
				profile:ENV["sigh_com.CompanyName.myCompanyName_appstore_profile-path"],
				build_configuration: "Debug",
				code_signing_identity:"iPhone Distribution: Company Name Retail (ZY00000000K)"
			)
			update_project_provisioning(
				xcodeproj: "CompanyName.xcodeproj",
				target_filter: "CompanyName*",
				profile:ENV["sigh_com.CompanyName.myCompanyName_appstore_profile-path"],
				build_configuration: "Release",
				code_signing_identity:"iPhone Distribution: Company Name Retail (ZY00000000K)"
			)
			gym(
				scheme:"CompanyName",
				configuration: "Release",
				clean: true,
				export_method: "app-store",
				output_directory:"./build/",
				export_options: {
				method: "app-store"},
				output_name: "test_prod.ipa"
			)
		end

		desc "Push a new beta build to TestFlight"
		lane :NewRelease do |options|
			CurrentBuildNumber = latest_testflight_build_number
			build_number = increment_build_number(
				build_number: 1 + CurrentBuildNumber
			)
			version_number = increment_version_number(
				version_number: options[:version_number]
			)
			sh(
			"echo ##teamcity[buildNumber '#{version_number}(#{build_number})']"
			)
			automatic_code_signing(team_id: "ZZTEAMIDZZK", code_sign_identity: "iPhone Distribution", use_automatic_signing:true)
			match(readonly:true)
			update_project_provisioning(
				xcodeproj: "CompanyName.xcodeproj",
				target_filter: "CompanyName.*",
				profile:ENV["sigh_com.CompanyName.myCompanyName_appstore_profile-path"],
				build_configuration: "Release"
			)

			build_app(
				scheme: "CompanyName",
				configuration: options[:configuration],
				clean: true,
				silent: true,
				output_directory: "/usr/local/Repos/OLS/artifacts/",
				output_name: "CompanyName.ipa",
				export_method: "app-store",
			)

			if options[:pushToStore]
				ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
				upload_to_testflight(
					ipa: "/usr/local/Repos/OLS/artifacts/CompanyName.ipa",
				)
		end
	end
end
```

Thank you
Dean Meehan

**Comment by meehanman** [comment]
I've followed this [tutorial](https://carloscuesta.me/blog/shipping-react-native-apps-with-fastlane/) (Creating a brand new React-Native Project) and I'm having the issue.

`Signing for "ProjectName" requires a development team` even though I ran the following Factfile lane

```
lane :certificates do
  match(app_identifier: 'com.CompanyName.ApplicationName', type: 'development', readonly: true)
  match(app_identifier: 'com.CompanyName.ApplicationName', type: 'appstore', readonly: true)
end

desc 'Build the iOS application.'
lane :build do
  certificates
  increment_build_number(xcodeproj: './ios/DeanProject.xcodeproj')
  gym(scheme: 'DeanProject', project: './ios/DeanProject.xcodeproj')
end

```

**Comment by meehanman** [comment]
I suspect adding may have worked for this instance
````
unlock_keychain(
  path: "login",
  password: "*********"
)
```

**Comment by janpio** [comment]
@meehanman Do you still have the same error as in your original post? Or did you solve this an the follow-up comments are new errors you are now getting?

**Comment by meehanman** [comment]
I solved it using the unlock keychain command even though my keychain should have already been unlocked. 

This was a with brand new keychain, react-native project and certs using match.
