### ISSUE TITLE
Seems to be a very old project file format 

### ISSUE THREAD

**Issue by jcdacampo** [fastlane/fastlane#13614]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi guys, when i execute `automatic_code_signing` returns this error bellow. I already updated my xcode.
`
Seems to be a very old project file format - please open your project file in a more recent version of Xcode `

**obs. this project is being done with Cordova.** 

### Environment
<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

lane :produzir do
  produce(
    username: 'ivornei@ixcsoft.com.br',
    app_identifier: 'com.teste.uploadixc',
    app_name: 'Teste Upload IXC',
    language: 'Portuguese',
    app_version: '1.0',
    sku: '123',
    enable_services: {
      push_notification: "on"
    }
  )
end

lane :geraIcone do
  appicon(
    appicon_image_file: './fastlane/metadata/appicon.png',
    appicon_devices: [:ipad, :iphone],
    appicon_path: "Central Assinante/Images.xcassets/"
  )
end

lane :registrar do
  cert(
    username: "ivornei@ixcsoft.com.br"
    )
  sigh(
    force: true,
    username: "ivornei@ixcsoft.com.br",
    app_identifier: "com.teste.uploadixc"
    )
end

lane :upar do
  enable_automatic_code_signing(path: "Central Assinante.xcodeproj",use_automatic_signing: false)
  team_id("3G3UFFD3LY")
  pem
  registrar
  geraIcone
  build_app(scheme: "Central Assinante",
            workspace: "Central Assinante.xcworkspace",
            include_bitcode: true)
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("ivornei@ixcsoft.com.br")
app_identifier("com.teste.uploadixc")
team_id("3G3UFFD3LY")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.13.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.4        |
| fastlane-plugin-appicon   | 0.13.0       |
</details>

**Comment by janpio** [comment]
Did you do what the error message tells you to do?

> ... please open your project file in a more recent version of Xcode

In general there is also a fastlane plugin to work around this that could help: https://github.com/ionic-zone/fastlane-plugin-upgrade_super_old_xcode_project
