### ISSUE TITLE
fastlane with terminal  is OK. but with Jenkins error "Missing password for user xxx, and running in non-interactive shell"

### ISSUE THREAD

**Issue by yuanjilee** [fastlane/fastlane#13617]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I run fastlane with terminal is OK, but with Jenkins wrong. with the Info, I guess there need **account credentials** , but I run in terminal is needn't. 

Addition, my Jenkins Worktilespace belongs to the user 'jenkins' not 'admin'.

I attempt:

- move keychain from login to system 
- and other

but none of them useful.  THANKS YOU.

##### Complete output when running fastlane, including the stack trace and command used

<details>
+ fastlane release
[15:14:54]: [33mfastlane detected a Gemfile in the current directory[0m
[15:14:54]: [33mhowever it seems like you don't use `bundle exec`[0m
[15:14:54]: [33mto launch fastlane faster, please use[0m
[15:14:54]: 
[15:14:54]: [36m$ bundle exec fastlane release[0m
[15:14:54]: 
[15:14:54]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[15:14:54]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
[15:14:55]: [32m------------------------------[0m
[15:14:55]: [32m--- Step: default_platform ---[0m
[15:14:55]: [32m------------------------------[0m
[15:14:55]: [32mDriving the lane 'ios release' 🚀[0m
[15:14:55]: [32m------------------------------[0m
[15:14:55]: [32m--- Step: get_certificates ---[0m
[15:14:55]: [32m------------------------------[0m

+---------------+-----------------------------------------------------------+
|                         [32mSummary for cert 2.107.0[0m                          |
+---------------+-----------------------------------------------------------+
| development   | false                                                     |
| force         | false                                                     |
| username      | 824528524@qq.com                                          |
| team_id       | GE35PAF7XQ                                                |
| keychain_path | /Users/Shared/Jenkins/Library/Keychains/login.keychain-db |
| platform      | ios                                                       |
+---------------+-----------------------------------------------------------+

[15:14:55]: Starting login with user '824528524@qq.com'
[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
[32mSee more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
[32m-------------------------------------------------------------------------------------[0m
+------------------+-------------+
|          [33mLane Context[0m          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios release |
+------------------+-------------+
[15:14:55]: [31mMissing password for user 824528524@qq.com, and running in non-interactive shell[0m

+------+------------------+-------------+
|           [32mfastlane summary[0m            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | [31mget_certificates[0m | 0           |
+------+------------------+-------------+

[15:14:55]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
[15:14:56]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
/Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': [31m[!] Missing password for user 824528524@qq.com, and running in non-interactive shell[0m (RuntimeError)
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/client.rb:353:in `login'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/client.rb:71:in `login'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/cert/lib/cert/runner.rb:24:in `login'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/cert/lib/cert/runner.rb:34:in `run'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/cert/lib/cert/runner.rb:13:in `launch'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/get_certificates.rb:17:in `run'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:28:in `block (2 levels) in parsing_binding'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/bin/fastlane:23:in `load'
	from /Users/worktilemobile/.rvm/rubies/ruby-2.5.1/bin/fastlane:23:in `<main>'
Build step '执行 shell' marked build as failure
Finished: FAILURE
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.5.1/bin/fastlane       |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  

  lane :release do

 	 get_certificates           
	 get_provisioning_profile(app_identifier: "com.xxx")
	 get_provisioning_profile(app_identifier: "com.xxx")

   scheme_name = "Worktile"
   configuration = 'Release'
   output_directory = File.expand_path("..", Dir.pwd) + File::Separator + 'build'

	 gym(
		clean: true,
	 	scheme: scheme_name,
                export_method: "app-store",
                configuration: configuration,
                output_directory: output_directory
	 )
   upload_to_testflight(skip_waiting_for_build_processing: true)

  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxx") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

itc_team_name "xxx"
team_id "xxx"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.2        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| bundler                   | 1.17.1       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-11-01**
</details>

**Comment by yuanjilee** [comment]
I run `fastlane fastlane-credentials add —username user@qq.com` not OK.

so I add `ENV["FASTLANE_USER"] = "user" & ENV["FASTLANE_PASSWORD"] = "password"`

 but error with **Two factor authentication fails**    https://github.com/fastlane/fastlane/issues/13603#issuecomment-435004953

**Comment by debeltranc** [comment]
How is Jenkins configured to run? Is the mac a Jenkins Slave? How does Fastlane runs from the Jenkins jobs? Are you using the credentials manager that comes with Jenkins?
This needs more details if you still need help with this issue.
