### ISSUE TITLE
Use "deliver --auto-release True" after appStore review

### ISSUE THREAD

**Issue by hakanyildizay** [fastlane/fastlane#13625]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I have a question about deliver action. 

This is not a question about documentation.

#### Question Description

We usually submit our application manually.
Is it possible to release the app after successful app store review with deploy?.
We submit the application with --auto-release **false**. Because we want to make sure that backend works correctly. After having review approval can we just say 
"deliver -ipa ... --automatic_release **true**"  to make our app live in app store? Is it possble to make this deliver call after app store review process?

Thank you.

**Comment by hakanyildizay** [comment]
Actually I am trying to automate this process..

![my_apps_manually_release](https://user-images.githubusercontent.com/1074740/47917280-0c831280-deba-11e8-8d28-54a6520895da.png)

**Comment by janpio** [comment]
Until now this doesn't exist. Reason is probably, that there was/is no API for this process (via iTMSTransporter for example).
