### ISSUE TITLE
Multiple profiles found with the name

### ISSUE THREAD

**Issue by Alarson93** [fastlane/fastlane#13629]
Hello! 

I'm hoping I can get by without needing to post our Fastfile/config because it is large (~500 lines) and contains private information that would be a pain to redact. With that in mind, today we received the following error while trying to make a build (omitted the bundle ID):

> {"responseId"=>"ff14fc7f-3152-426a-a4d1-7df0de5e6b33", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"Multiple profiles found with the name 'match AppStore com.redacted.foo'.  Please remove the duplicate profiles and try again.", "creationTimestamp"=>"2018-11-02T21:41:57Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"provisioningProfileName", "validationUserMessage"=>"Multiple profiles found with the name 'match AppStore com.redacted.foo.  Please remove the duplicate profiles and try again."}]}

I have deleted ALL of the certificates and provisioning profiles from this app, deleted the branch from our Match repo, and updated to the latest version of Fastlane.

Other app builds using the same work just fine. This is the only app that is having any issues.
I'm told by a coworker that we transferred this app from one Apple account to another, so is it possible that something is wrong on Apple's end?

I've never had an issue like this before.

Update:
I've confirmed this issue is on Apple. I tried to create a provisioning profile identical to what Match was doing and it failed with the same error mentioned in the above block.
Either we need to reach out to Apple and make them fix the issue or we need to change how match names profiles; is there something like a "nameOverride" parameter?

**Comment by BennettSmith** [comment]
I am running into this issue as well. Any progress on resolving the issue or identifying a workaround?

**Comment by Alarson93** [comment]
@BennettSmith Not as of yet.

**Comment by BennettSmith** [comment]
A workaround I found was to remove all of the locally cached profiles using this command:

```
$ rm -r ~/Library/MobileDevice/Provisioning\ Profiles/*
```

**Comment by janpio** [comment]
@BennettSmith How does that workaround to @Alarson93 's conclusion that this is a server side issue with Apple? Or did I misunderstand something?

**Comment by BennettSmith** [comment]
My hunch is that creating a profile manually that has the same name as the one FastLane Match creates would still cause the problem if there are older profiles with the same name still stores in the local cache of profiles on the machine. 

I believe this is a FastLane Match big and not an issue on Apple’s side. It seems like match is getting confused when it sees profiles with the same name already present on the machine. Or, I guess it could be a bug in one of Apple’s command-line tools that are run by match.

**Comment by Alarson93** [comment]
I tried to manually create the certificate on a different machine (one that doesn't have fastlane installed).

I tried to manually create the profile through Apple's web portal, so it definitely isn't an issue with Fastlane or Apple's command line tools.

**Comment by BennettSmith** [comment]
@alarson93 After you created the profile from a different machine, where did you see the error? Was it back on the first machine or somewhere else?

**Comment by eXhausted** [comment]
this issue came to me, any suggestions?

**Comment by Alarson93** [comment]
I had this happen for a second app.
Fortunately I was able to resolve it. Search your provisioning profiles for a profile with a name matching the one that throws an error.

Ex: 
1. You get an error saying the provisioning profile named "match AppStore my.app.iscool" has duplicates.
2. Search the profile list for "match AppStore my.app.iscool" and remove any profiles that you find.
3. Try to run your lane again.

While this worked for my second app, the first app (which led me to creating this thread) was unable to be fixed using these steps.

**Comment by bhavinmdesai** [comment]
This is also happening with me. I tried what @Alarson93 suggested and it resolved the problem for me.

**Comment by zineer** [comment]
I had this issue today as well. Doing a `fastlane sigh manage -e` removed the local copy (as it was expired), but the issue persisted. I went into developer.apple.com and deleted the profile there, then was able to successfully fun fastlane as usual.

**Comment by ftronnbe** [comment]
Had an expired provisioning profile with the same name in the developer portal. By deleting it in te portal signing was successful.

**Comment by ptuko** [comment]
Same problem here.
I have found out that command Spaceship::Portal.provisioning_profile.all doesn't find expired provision profiles so I'm not able to remove expired profiles automatically from ruby script.

I have tried this example and it did not work either:

# Select all 'Invalid' or 'Expired' provisioning profiles
broken_profiles = Spaceship::Portal.provisioning_profile.all.find_all do |profile|
  # the below could be replaced with `!profile.valid? || !profile.certificate_valid?`, which takes longer but also verifies the code signing identity
  (profile.status == "Invalid" or profile.status == "Expired")
end

**Comment by janpio** [comment]
@ptuko Please create a new issue, maybe we can make spaceship work for this case as well. Describe the problem a bit out of context of _this_ issue as well, so it is easier for a developer to go into it then. Thanks.
