### ISSUE TITLE
screengrab not compatible with androidx.test

### ISSUE THREAD

**Issue by tmm1** [fastlane/fastlane#13622]
I upgraded my project to use androidx, but `./gradle assembleAndroidTest` now fails to compile as long as I have `androidTestImplementation 'tools.fastlane:screengrab:1.2.0'` in my build.gradle:

```
> Task :app:transformDexArchiveWithExternalLibsDexMergerFoDebugAndroidTest FAILED
D8: Program type already present: androidx.test.uiautomator.AccessibilityNodeInfoHelper
```

**Comment by petrsvobodnikspider** [comment]
Hi, I had same issue, solved by specifying name of the runner in Screengrabfile:

test_instrumentation_runner 'androidx.test.runner.AndroidJUnitRunner'

The runner should be exactly same as they only changed packages structure.

I hope that will help.

**Comment by tmm1** [comment]
The problem for is that the project won't even compile. I already migrated all my code and dependencies to androidx, and have the new entires in my gradle.properties already.

**Comment by janpio** [comment]
If anyone else doesn't know about `androidx` yet: https://stackoverflow.com/questions/51280090/what-is-androidx

From your description @petrsvobodnikspider we should probably update some documentation, correct? Are you up to creating a PR that adds the changed strings when using Androidx?

**Comment by free5ty1e** [comment]
I am working in Kotlin and using the new AndroidX instrumentation / UI testing packages and test runner.

I have the 
`test_instrumentation_runner 'androidx.test.runner.AndroidJUnitRunner'`
set in the Screengrabfile and I have 
`testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"`
set in my build.gradle, I have example UI tests passing but as soon as I attempt to call the `Screengrab.screenshot()` function, even between UI actions (activity is launched and active), it always crashes on that screenshot line with: 

`java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
`
I'm using ActivityTestRule.  Can't seem to get the screenshot function to work.  

When I try to add in a LocaleTestRule():
`    @get:ClassRule val localeTestRule = LocaleTestRule()`

... it always crashes on THAT line with:
`java.lang.IllegalStateException: No instrumentation arguments registered! Are you running under an Instrumentation which registers arguments?`

Are there currently known workarounds or implementation tips for using Kotlin, AndroidX, and Fastlane?

**Comment by free5ty1e** [comment]
I'm creating a new issue for the above related comment.

**Comment by vanniktech** [comment]
This is still an issue. Created a PR a while ago to target 28 which is the first step towards AndroidX - https://github.com/fastlane/fastlane/pull/13231 - however it hasn't been merged yet.
