### ISSUE TITLE
Organize screenshots.html to compare all localizations for a screen?

### ISSUE THREAD

**Issue by claesjacobsson** [fastlane/fastlane#13626]
Wouldn't it be useful to be able to generate a version of the screenshots.html that organizes the screenshots so that we can can see all localizations of a screen next to each other?

#### Motivation Behind Feature
This would provide a great tool to verify translations and that they work on different device types.

Is this interesting? Is there already a way to do this? If not, I might give it a try.

**Comment by janpio** [comment]
Sounds useful. Any idea how to best implement this?
