### ISSUE TITLE
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD not working

### ISSUE THREAD

**Issue by jpghelfi** [fastlane/fastlane#13630]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to use FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD as an Env Variable in fastfile for my Developer Apple Account, but it's not working.

My Appstoreconnect account does not have TFA. The Developer Apple account (my clients account), does. I cannot remove it (I tried), all new Dev Account are set with TFA.

In my fastfile, on top of the lane upload_ipa is this:

`ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = 'xxxx-xxxx-xxxx-xxxx'`

This password was created in the Apple Dev Account.

If I use the dev account, as the appstore account, the only difference it at the beginning of the script, it asks for the 6 digit code.. whe it shoudn't, because I've already set the Specific Password

`[18:53:54]: Login to App Store Connect (devapple_user@gmail.com)
Two Factor Authentication for account 'devapple_user@gmail.com' is enabled
Your session cookie has been expired.
Please enter the 6 digit code: `

I'm 100% certain the Apple Specific password is Valid.

This is the output when the appstoreconnect user is different from the devaccount user

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode92.app/Contents/Developer/                  |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :upload_ipa do
  ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = 'zfvy-szgm-wqqk-pvsx'
    upload_to_testflight(skip_waiting_for_build_processing: true,
    	ipa: 'Revista Palabras.ipa')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.xxxx.revistapalabras") # The bundle identifier of your app
apple_id("devapple_user@gmail.com") # Your Apple email address

itc_team_id("V733ZRD5A4") # App Store Connect Team ID
team_id("V733ZRD5A4") # Developer Portal Team ID

ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = 'xxxx'

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.3       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.4        |
| bundler                   | 1.16.4       |
| unicode-display_width     | 1.4.0        |
</details>

*generated on:* **2018-11-03**
</details></pre>
</details>

<details>
  <pre>➜  Revista Palabras git:(master) ✗ bundle exec fastlane upload_ipa
[✔] 🚀 
[18:47:54]: ------------------------------
[18:47:54]: --- Step: default_platform ---
[18:47:54]: ------------------------------
[18:47:54]: Driving the lane 'ios upload_ipa' 🚀
[18:47:54]: ----------------------------------
[18:47:54]: --- Step: upload_to_testflight ---
[18:47:54]: ----------------------------------
[18:47:54]: Login to App Store Connect (appstoreconnect_user@gmail.com)
[18:47:57]: Login successful
[18:47:58]: Ready to upload new build to TestFlight (App: 1441226948)...
[18:48:04]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[18:48:04]: Going to upload updated app to App Store Connect
[18:48:04]: This might take a few minutes. Please don't interrupt the script.
[18:48:19]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Username: devappleaccount_user@gmail.com
The login credentials for 'devappleaccount_user@gmail.com' seem to be wrong
Do you want to re-enter your password? (y/n)
y
Removing Keychain entry for user 'devappleaccount_user@gmail.com...
keychain: "/Users/jp/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="deliver.xxxx@gmail.com"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="devapple_user@gmail.com"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138313130333231323433385A00  "20181103212438Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138313130333231323433385A00  "20181103212438Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="deliver.devapple_user@gmail.com"
    "type"<uint32>=<NULL>
password has been deleted.
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for devappleaccount_user@gmail.com): **********
[18:48:34]: Please run this tool again to apply the new password
[18:48:34]: [Transporter Error Output]: Error while processing package 1441226948.itmsp
[18:48:34]: Transporter transfer failed.
[18:48:34]: 
[18:48:34]: Your Apple ID or password was entered incorrectly. (-20101)
Error while processing package 1441226948.itmsp
[18:48:34]: [iTMSTransporter] [2018-11-03 18:48:19 ART] <main> DBG-X:   parameter ErrorCode = -20101

[18:48:34]: [iTMSTransporter] [2018-11-03 18:48:19 ART] <main> DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)

[18:48:34]: [iTMSTransporter] [2018-11-03 18:48:19 ART] <main> DBG-X:   parameter Success = false

[18:48:34]: [iTMSTransporter] [2018-11-03 18:48:19 ART] <main> ERROR: Your Apple ID or password was entered incorrectly. (-20101)

[18:48:34]: [iTMSTransporter] [2018-11-03 18:48:19 ART] <main> ERROR: Error while processing package 1441226948.itmsp

[18:48:34]: [iTMSTransporter] 

[18:48:34]: [iTMSTransporter] 

[18:48:34]: [iTMSTransporter] 

[18:48:34]: [iTMSTransporter] Package Summary:

[18:48:34]: [iTMSTransporter]  

[18:48:34]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[18:48:35]: [iTMSTransporter] 	/var/folders/v7/057m71q50kqf5wxjh9glpm800000gp/T/d20181103-43766-g3qar1/1441226948.itmsp - Error Messages:

[18:48:35]: [iTMSTransporter] 		Your Apple ID or password was entered incorrectly. (-20101)

[18:48:35]: [iTMSTransporter] 		Error while processing package 1441226948.itmsp

[18:48:35]: [iTMSTransporter] [2018-11-03 18:48:19 ART] <main> DBG-X: Returning 1

[18:48:35]: iTunes Transporter output above ^
[18:48:35]: Your Apple ID or password was entered incorrectly. (-20101)
Error while processing package 1441226948.itmsp
\nError while processing package 1441226948.itmsppple ID or password was entered incorrectly. (-20101)
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios upload_ipa |
+------------------+----------------+
[18:48:35]: Error uploading ipa file, for more information see above

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 💥   | upload_to_testflight | 40          |
+------+----------------------+-------------+

[18:48:35]: fastlane finished with errors

[!] Error uploading ipa file, for more information see above</pre>
</details>

**Comment by yuanjilee** [comment]
**Your session cookie has been expired**   I face the problem too, and it always tell me expired.

**Comment by jarrodparkes** [comment]
I'm also in this rut again. It was working fine until a few days ago. Now, regardless of FASTLANE_SESSION and FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD being set in the environment, it always says "Your session cookie has been expired." Almost positive that the regions are the same between my local and remote machines, so I don't think that is the issue.

**Comment by jarrodparkes** [comment]
Possible fix, this worked for me: https://github.com/fastlane/fastlane/issues/13603

**Comment by janpio** [comment]
Similar problem: https://github.com/fastlane/fastlane/issues/13705
