### ISSUE TITLE
I don't know this problem. What's the wrong?

### ISSUE THREAD

**Issue by BaekJinCho** [fastlane/fastlane#13636]
sh: xcprerry: command not found
Exit status: 127
[!] undefined method 'each' for nil"NilClass (NoMethodError)

**Comment by hjanuschka** [comment]
i think its a typo :D and should be called `xcpretty``
can you share your fastfile?


if the typo is just in the issue itself, check if `xcpretty` is installed -> https://github.com/supermarin/xcpretty
