### ISSUE TITLE
"Error Domain=IDEProvisioningErrorDomain Code=9 \"\"HanTalkShare.appex\" requires a provisioning profile with the App Groups feature.\" UserInfo={NSLocalizedDescription=\"HanTalkShare.appex\" requires a provisioning profile with the App Groups feature., NSLocalizedRecoverySuggestion=Add a profile to the \"provisioningProfiles\" dictionary in your Export Options property list.}"

### ISSUE THREAD

**Issue by caoyunxiao** [fastlane/fastlane#13634]
"Error Domain=IDEProvisioningErrorDomain Code=9 \"\"HanTalkShare.appex\" requires a provisioning profile with the App Groups feature.\" UserInfo={NSLocalizedDescription=\"HanTalkShare.appex\" requires a provisioning profile with the App Groups feature., NSLocalizedRecoverySuggestion=Add a profile to the \"provisioningProfiles\" dictionary in your Export Options property list.}"

**Comment by truted** [comment]
Any luck with this? I'm running into a similar issue. It looks like the command being run is:

```
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/3f/sbgcwvx14x53njc_zm5k695c0000gn/T/gym_config20181106-14919-cy6ht8.plist ...
```

When I look inside the file specified in `-exportOptionsPlist` I see:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>method</key>
        <string>app-store</string>
        <key>provisioningProfiles</key>
        <dict>
                <key>{ my bundle key }</key>
                <string>{ name of profile }</string>
        </dict>
        <key>signingStyle</key>
        <string>manual</string>
</dict>
</plist>
```

I can't figure out what xcode is complaining about because there is an entry in the provisioningProfiles dictionary.

**Comment by janpio** [comment]
What exactly _is_ the problem here?
What command are you running, what lane is being executed, what does this lane contain?
What is the full output of that execution?
What is your environment information?

Does the "requires a provisioning profile with the App Groups feature." part of the error message make any sense to you?

**Comment by JimmieWong** [comment]
Got same issue.

**Comment by JimmieWong** [comment]
### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.105.1 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status      |
| ----------------------- | ------- | ------------------ |
| fastlane-plugin-appicon | 0.13.0  | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.2       |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.2        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.4        |
| dotenv                    | 2.5.0        |
| fastlane-plugin-appicon   | 0.13.0       |

**Comment by JimmieWong** [comment]
<img width="1720" alt="screen shot 2018-12-30 at 1 50 01 pm" src="https://user-images.githubusercontent.com/1055066/50544688-01d6c680-0c3a-11e9-8a5d-efcfd70870cf.png">

**Comment by JimmieWong** [comment]
fastlane produce enable_services  -a com.xxx.mobile.xxx --app-group
fastlane produce enable_services  -a com.ixxx.mobile.xxx.notification --app-group
fastlane produce group -g group.xxx.app.xxx -n "xxx app group"
fastlane produce associate_group -a com.xxx.mobile.xxx group.xxx.app.xxx
fastlane produce associate_group -a com.xxx.mobile.xxx.notification group.xxx.app.xxx
fastlane ios do_app_generic_devices_build --env run profile:Appstore

**Comment by JimmieWong** [comment]
lane :do_app_generic_devices_build do |options|

      read_options(options)
      gym_build_app()

   end

   private_lane :gym_build_app do

      gym(
        scheme: ENV['SCHEME'],
        clean: false,
        export_method: ENV['EXPORT_METHOD'],#app-store, ad-hoc, package, enterprise
        include_bitcode: $include_bitcode_if_need,
        configuration: ENV['CONFIGURATION_ NAME'],
        export_options: ENV['EXPORT_OPTIONS'],
        output_directory: ENV['IPA_OUTSIDE_PROJECT_LOCATION'],
        destination:'generic/platform=iOS',
        skip_profile_detection: true
      )

   end

**Comment by JimmieWong** [comment]
@fastlane-bot  Can you reopen this issue?

**Comment by JimmieWong** [comment]
I configure provision files in portal and try to export .ipa for App Store and I am using App groups capability. 

the provision files are working if I archive and export from Xcode, but fails if using fastlane. 
please help.

**Comment by janpio** [comment]
No, this issue won't be reopened. Please update your fastlane and plugin first, if you still have this problem, open a new issue per the bug issue template and include a link to this issue for reference. Thanks.
