### ISSUE TITLE
Publishing Apple app after Review Succeed

### ISSUE THREAD

**Issue by MartinGonzalez** [fastlane/fastlane#13638]
### Question

Hi there! I just wanted to know if there is an action, or if deliver can publish an Apple app after review has succeed.

Thanks!

**Comment by hakanyildizay** [comment]
Hello guys..
I had the same problem.. :(.  [https://github.com/fastlane/fastlane/issues/13625](url)
Can you recommend any solution for that? As far as I know Apple does not provide any "itmstransporter commandline" for that situation.
