### ISSUE TITLE
Can not install fastlane on macOS 10.14.1 (Mojave)

### ISSUE THREAD

**Issue by 597579501** [fastlane/fastlane#13647]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by 597579501** [comment]
SevendeiMac:~ sevenmac$ sudo gem install -n /usr/local/bin fastlane
Password:
Building native extensions. This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181108-24183-a1m84s.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:535:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:532:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5/gem_make.out
SevendeiMac:~ sevenmac$

**Comment by 597579501** [comment]
SevendeiMac:~ sevenmac$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
SevendeiMac:~ sevenmac$

**Comment by whithajess** [comment]
Just encountered this same thing fresh installing fastlane via brew and from gems.

He is referencing macOS Mojave @janpio 

I definitely have command line tools installed and went so far as removing them and re-installing. @hjanuschka

**Comment by whithajess** [comment]
Can confirm a move to `ruby-2.5.1` without `sudo` fixes the problem however most people installing this especially using the `brew` option will use:

```$ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18

As thats what comes installed by default on a Mac.

**Comment by lmenus** [comment]
Can confirm @whithajess solution works, almost pulled all of my hair solving this, had a fresh macOS install too. (Related to #12905)

In my case I used `rbenv` to switch to `2.5.3.`

**Comment by joshdholtz** [comment]
I still have no updated to Mojave but I will do that over the weekend so I can look into this next week 🧐

**Comment by whithajess** [comment]
@janpio I just tried it with 
```ruby
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin18]
```
installed via `rvm` and it went through the install fine.

**Comment by janpio** [comment]
Thanks for trying that, so we really have to test this with Mojave.

**Comment by keith** [comment]
If you already have the Xcode command line tools installed with `xcode-select --install` but you're still getting a build error about `unf_ext` you can follow [these instructions](https://stackoverflow.com/questions/26434642/yosemite-upgrade-broke-ruby-h/53194299#53194299) to make sure the ruby headers are installed

**Comment by whithajess** [comment]
@keith `xcode` was definitely installed I even went so far as removing it completely and re-installing the latest. The other thing about headers could be right? - Maybe Mojave ruby by default does not have headers installed.

**Comment by keith** [comment]
Not just Xcode, the Xcode command line tools which aren't installed automatically

**Comment by whithajess** [comment]
Yeah sorry - both were definitely installed.

**Comment by keith** [comment]
Yea then you should try the instructions about the other header package which might already exist on your system at `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` and otherwise can be downloaded by re-installing the command line tools by downloading it from the developer portal

**Comment by whithajess** [comment]
Mine is now working as above - installed rvm and latest ruby worked perfect after I was just trying to say given that the out of the box Mojave ruby does not work this is going to cause problems for everyone who is not specifically doing ruby development who wants to use fastlane.

**Comment by airways** [comment]
This is still a problem on a vanilla install of 10.14.3 (Mojave latest update).

**Comment by whithajess** [comment]
@janpio - this get lost in the noise?

**Comment by janpio** [comment]
Is there a PR that we missed that would solve or change this in any way? Otherwise there really is nothing we can do. If this would be a widespread problem, there would be a lot more reports. But how it looks now, there really is no pressure to investigate this from people that don't have the problem themselves.

**Comment by whithajess** [comment]
Every single `Mac` running `Mojave (macOS)` without any custom ruby install will have this when installing via any of the install options - remember this is an install bug a lot of people going to try out fastlane will hit this and give up. As i said above 

> If the issue itself cannot be solved then there should likely be a suggestion in: https://docs.fastlane.tools/getting-started/ios/setup/ for those using iOS will run into this error both via Rubygems and brew install.

I personally am not using fastlane anymore (for other reasons) so really it is up to the fastlane team - I personally spent a bunch of time getting this running when first trying this out (maybe save others the same pain?)
