### ISSUE TITLE
How to set release name when using upload_to_play_store?

### ISSUE THREAD

**Issue by lakshin** [fastlane/fastlane#13643]
In play console when you create a release it is possible to provide a release name. But when using upload_to_play_store command i cannot see a parameter to provide a custom release name when pushing the apk, but takes the version name as the release name. How is it possible to achieve it? 

Please find an Image attached below which explain what release name is. 
![image](https://user-images.githubusercontent.com/9911515/48061040-b4af1900-e1e3-11e8-9c48-53c3fc77cfef.png)

### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by janpio** [comment]
Is this feature pretty new to the Play Console? If so, it is very possible this is not implemented yet or even not possible with the API the action is using in the background. Still, sounds like a reasonable feature to implement of course (if possible).
