### ISSUE TITLE
Fastlane SSL problem - unable to download fastlane gem

### ISSUE THREAD

**Issue by jamesmcn1** [fastlane/fastlane#13642]
Hi guys,

I'm having an issue with deploying my project with fastlane via Circle CI. Im running the following commands in my build pipeline:

```
      brew update
      brew install ruby
      sudo gem install fastlane
```

`sudo gem install fastlane `throws the error:
```
^D^DERROR:  Could not find a valid gem 'fastlane' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)
```

Any ideas of how to get this fixed?

I noticed that a new gem was made available (2.108.0) on November 5th, which is around the time when this error started occuring. Specifying version doesn't help either.

Also I tried to install fastlane via brew cask (`brew cask install fastlane`) but it gives me an outdated version (<2.60) which is not compatible with the rest of the pipeline.

Enviroment:
Docker shell
openSSL 1.0.2 version

The `sudo gem install fastlane ` command works on my local machine.

### New Issue Checklist

- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by hjanuschka** [comment]
github/rubygems dropped tlsv1 i think.

see: https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html a guide.
try to get a newer ruby and openssl version.

**Comment by jamesmcn1** [comment]
Thanks @hjanuschka  - that document is very helpful and identifies the problem occuring here but so far I've not found a solution.

I've just ran an SSL check and it appears as though the build phase commands aren't actually altering the environment on the virtual machine running in Circle CI. Here is the output of `ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'` : 

```^D^DHere's your Ruby and OpenSSL environment:

Ruby:           2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
RubyGems:       2.0.14.1
Bundler:        1.15.4
Compiled with:  OpenSSL 0.9.8zc 19 Mar 2015
Loaded version: OpenSSL 0.9.8zh 14 Jan 2016
SSL_CERT_FILE:  /System/Library/OpenSSL/cert.pem
SSL_CERT_DIR:   /System/Library/OpenSSL/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (SSL/TLS protocol version mismatch)
RubyGems connection to rubygems.org:      failed  ❌  (SSL/TLS protocol version mismatch)
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Your Ruby can't connect to rubygems.org because your version of OpenSSL is too old. You'll need to upgrade your OpenSSL install and/or recompile Ruby to use a newer OpenSSL.
Exited with code 1```

As you can see - this is contrary to the build commands above which are instilling latest versions of ruby and open ssl (1.0.2).

The problem is that the virtual machine is not using the updated versions but rather 0.9.8, which is below the compatibility requirements

**Comment by hjanuschka** [comment]
i guess you'd need to file an issue on circle then, i am afraid we can fix this from the fastlane side.

**Comment by hjanuschka** [comment]
or you could try to install and use RVM maybe this uses then than a newer ssl lib.

**Comment by jamesmcn1** [comment]
Finally managed to work out the problem :)

It was because the Circle ci mac os virtual machine didn't want to use the installed ruby version and only use the system ruby version. All that was required was to add a new file called `/.ruby-versions` which overrides the system version. The command is:

`echo "ruby-2.5.3" > ~/.ruby-version`

I hope this helps someone! thanks for your assistance @hjanuschka and feel free to close the issue
