### ISSUE TITLE
upload_to_play_store(track: "beta") Forbidden

### ISSUE THREAD

**Issue by ntk860** [fastlane/fastlane#13641]
Hello,
   
 I am trying to run the command upload_to_play_store(track: "beta"), and its saying that Google Api Error: forbidden: Forbidden

fastlane 2.108.0

Output with --verbose

/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: forbidden: Forbidden (FastlaneCore::Interface::FastlaneError)

Thank you!

**Comment by joshdholtz** [comment]
@ntk860 It sounds like your Google Service account didn't get the correct permissions/roles. Did you follow everything step for step at https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials? 🤔

**Comment by ntk860** [comment]
Hi @joshdholtz thank you for replying. Yes, I did, do you think I need to activate the billing for the google account for this to work ? Is it possible to use another google account or I must you the account associated with my android developer account ?

**Comment by joshdholtz** [comment]
@ntk860 You need to use an account that is associated with an active Google Play account. It can be another Google account but they must be invited into your Google Play account with proper roles. I wish I could help more but I am not an expert at figuring out any issues with Google Play service accounts 😔

**Comment by ntk860** [comment]
I think I found the solution and its a bug on supply code. To give permission to an account that this steps require https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials, we need to let people know who is the owner of the account. On your code you have something like this 

```
client = Google::Apis::AdminDirectoryV1::DirectoryService.new
client.authorization = Google::Auth::ServiceAccountCredentials.make_creds({
  json_key_io: File.open('./service_account.json'),
  scope: scope
})


its missing the following line 

```client.authorization.sub = <admin_email_in_organization>
````

in order for this to work, can you assign the person responsible for this part of the code, so we can check if its a bug on fastlane supply ?

**Comment by ntk860** [comment]
ERROR [2018-11-06 21:49:57.64]: fastlane finished with errors
/Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: forbidden: Forbidden (FastlaneCore::Interface::FastlaneError)
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/supply/lib/supply/client.rb:71:in `rescue in call_google_api'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/supply/lib/supply/client.rb:69:in `call_google_api'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/supply/lib/supply/client.rb:133:in `begin_edit'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:27:in `block (2 levels) in parsing_binding'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/bin/fastlane:22:in `load'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/bin/fastlane:22:in `<main>'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/vbtapper/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by janpio** [comment]
Hey @ntk860 can you share how your Google accounts are set up in your Play Store account? 
Did you try modifying the fastlane code yourself and confirm that this change works or was this line just from the issue you linked to?
