### ISSUE TITLE
Metadata.xml has app_platform set to "phoneos"

### ISSUE THREAD

**Issue by bengottlieb** [fastlane/fastlane#1364]
I've used Fastlane on a few projects, and had no issues. I just set it up on a new project today, and now I'm unable to upload to iTunes using Transporter. It says:

[20:02:02]: [Transporter Error Output]: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"

This is now happening in all projects. Is there a setting somewhere that got stomped on? Are others seeing this problem?

**Comment by asfalcone** [comment]
This is a duplicate of https://github.com/fastlane/spaceship/issues/247. Please follow that issue for updates. Thanks!

**Comment by bengottlieb** [comment]
Thanks, sorry for the dupe!

**Comment by KrauseFx** [comment]
Just pushed a fix https://github.com/fastlane/pilot/pull/148 :rocket: Sorry for the troubles!
