### ISSUE TITLE
deliver cannot upload a build due to an incorrect version

### ISSUE THREAD

**Issue by Skoti** [fastlane/fastlane#13651]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Current version _1.2.0_ is in Pending Developer Release.
Uploading _1.3.0_ ends with an error.

#### **Investigation:**
_verify_version_ in deliver sets the _1.3.0_ version successfully. (see output)
This is weird since _1.2.0_ is in _Pending Developer Release_ so it should not happen?

It seems like changing the version from _1.2.0_ to _1.3.0_ makes it Pending Developer Release?!? (_save!_ method finishes without an error). As I can see _ensure_version!_ is just setting a new version string without any check.
I think it should only do this if it is not _Waiting For Review_, _In Review_ and _Pending Developer Release_ state.

What is weird with this version change is that iTMSTransporter failed with a message:
`This bundle is invalid. The value for key CFBundleShortVersionString [1.3.0] in the Info.plist file must contain a higher version than that of the previously approved version [1.3.0].`
So it is confirming that setting a version was actually successful, however, after that I opened AppStoreConnect to see what is happening. There was still _1.2.0_ _Pending Developer Release_ displayed like changing it to _1.3.0_ never happened...

Running the same command again resulted in exactly the same behaviour and output.

I was able to reproduce this behaviour on over a dozen of accounts.

#### **Insight:**
Even though I have used _reject_if_possible_ flag set to true it did not happen as it is executed after an upload (which has failed).
Maybe it is worth moving it up? It would reject the _1.2.0_ version first and then upload _1.3.0_ version without an issue.
I rejected it manually to resolve this and then uploading _1.3.0_ was successful.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>Making sure the latest version on App Store Connect matches '1.3.0' from the ipa file...
ITC.apps.devReject.message.and.link.pendingDevRelease.canReject
[16:22:50]: Successfully set the version to '1.3.0'
[⠏] Activating languages en-GB, no... ITC.apps.devReject.message.and.link.pendingDevRelease.canReject
[✔] Activating languages en-GB, no...
[16:22:59]: Setting the app's age rating...
[⠼] Uploading metadata to App Store Connect ITC.apps.devReject.message.and.link.pendingDevRelease.canReject
[✔] Uploading metadata to App Store Connect
[16:23:02]: Successfully uploaded set of metadata to App Store Connect
[16:23:03]: Starting with the upload of screenshots...
[16:23:03]: Successfully uploaded screenshots to App Store Connect
[16:23:05]: Price Tier unchanged (tier 0)
[16:23:07]: Uploading app icon...
ITC.apps.devReject.message.and.link.pendingDevRelease.canReject
[16:23:14]: Uploading binary to App Store Connect
[16:23:14]: Going to upload updated app to App Store Connect
[16:23:14]: This might take a few minutes. Please don't interrupt the script.
[16:24:17]: [Transporter Error Output]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.3.0] in the Info.plist file must contain a higher version than that of the previously approved version [1.3.0]."
[16:24:18]: Transporter transfer failed.
[16:24:18]: [iTMSTransporter]  (1102)

[16:24:18]: [iTMSTransporter] [2018-11-07 16:24:17 CET] <main> DBG-X:   parameter Success = false

[16:24:18]: [iTMSTransporter] [2018-11-07 16:24:17 CET] <main> ERROR: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.3.0] in the Info.plist file must contain a higher version than that of the previously approved version [1.3.0]."

[16:24:18]: [iTMSTransporter] [2018-11-07 16:24:17 CET] <main> DBG-X: The error code is: 1102

[16:24:18]: [iTMSTransporter] [2018-11-07 16:24:17 CET] <main>  INFO: Done performing authentication.

[16:24:18]: [iTMSTransporter]

[16:24:18]: [iTMSTransporter]

[16:24:18]: [iTMSTransporter]

[16:24:18]: [iTMSTransporter] Package Summary:

[16:24:18]: [iTMSTransporter]

[16:24:18]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[16:24:18]: [iTMSTransporter] 	/tmp/{redacted_app_id}.itmsp - Error Messages:

[16:24:18]: [iTMSTransporter] 		ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.3.0] in the Info.plist file must contain a higher version than that of the previously approved version [1.3.0]."

[16:24:18]: [iTMSTransporter] [2018-11-07 16:24:18 CET] <main> DBG-X: Returning 1

[16:24:18]: iTunes Transporter output above ^
[16:24:18]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.3.0] in the Info.plist file must contain a higher version than that of the previously approved version [1.3.0]."
Return status of iTunes Transporter was 1: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.3.0] in the Info.plist file must contain a higher version than that of the previously approved version [1.3.0]."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
</pre>
</details>

**Comment by janpio** [comment]
@Skoti  I worry I am missing something, and don't fully understand. Can you share what command you are executing, what the content of the executed lane is and what is happing, step by step?

**Comment by Skoti** [comment]
@janpio Hi Jan, thanks for taking care of this issue.

The lane is only executing deliver. This is the only step.
"Investigation" paragraph describes my analysis of what is potentially happening inside deliver.
Basically, I had an app in version 1.2.0 in Pending Developer Release state but I did not want to use it and I wanted to upload a 1.3.0 build as a new version but got an error which I described above with iTMSTransporter output included.

Only these parameters were set to a non-default value:
```
force: true,
reject_if_possible: true,
run_precheck_before_submit: false
```

I was able to reproduce this many times during that day (on different accounts too) but maybe it was just a temporary AppStoreConnect issue?
It seems like the root cause of this issue is the version change. As a result a new version inherited the status of the previous version (Pending Developer Release) and that caused an iTMSTransporter error. But the weird thing is that when I entered AppStoreConnect there was still 1.2.0 displayed...

**Comment by janpio** [comment]
Thanks for the clarification. 

Can you post the complete lane that was executed (and a possibly existing `Scanfile`), just to make sure we don't overlook anything when replicating?

Also, can you maybe try yourself to replicate again? You will probably be a lot faster than me or any other team member.

**Comment by Skoti** [comment]
Right now I do not have any app in this state, but if this happens I will try to reproduce.
I also do not use `Scanfile`.

Here is the lane - although like I said the only non-default values (according to `deliver` description) where these I have mentioned above, the rest is just paths to files:
```
lane :deliver_build do |options|
    deliver(
      app_rating_config_path: "path_to_rating",
      automatic_release: options.fetch(:automatic_release, false),
      force: options.fetch(:force, false),
      ipa: "path_to_ipa",
      metadata_path: "path_to_metadata",
      overwrite_screenshots: options.fetch(:overwrite_screenshots, false),
      phased_release: options.fetch(:phased_release, false),
      price_tier: 0,
      reject_if_possible: options.fetch(:reject_if_possible, false),
      run_precheck_before_submit: options.fetch(:run_precheck_before_submit, true),
      screenshots_path: "path_to_screenshots",
      skip_app_version_update: options.fetch(:skip_app_version_update, false),
      skip_metadata: options.fetch(:skip_metadata, false),
      skip_screenshots: options.fetch(:skip_screenshots, false),
      submission_information: options.fetch(:update_submission_information, false) ? JSON.parse(File.read("path_to_submission")) : nil
    )
end
```

**Comment by Skoti** [comment]
I can mention that this lane works, when I am uploading a build for a new version while the previous version is in Ready For Sale state. It also works for uploading subsequent builds for that new version (while in Prepare for Submission).
I have not tried if this works/gives the same error when the previous version is in Waiting For Review or In Review.

Now I also remember that I had an issue when the previous version is rejected. Then uploading a new version was successful but the version on AppStoreConnect (in the General App Information section) did not change.
So it seems to be connected - this time upload was successful because the previous version was rejected and this does not cause an error like in Pending Developer Release case.

**Comment by Skoti** [comment]
I have once again tested the case when the previous version is Rejected.

Although this time version in General App Information section has changed, still a new version has inherited the AppStore status from the previous one instead of changing it to Prepare For Submission. (it is displaying Rejected for an uploaded new version which is totally misleading).

I am not sure whether this can be fixed on _fastlane_ side or this is only _AppStoreConnect_ issue.

**Comment by Skoti** [comment]
> Also, can you maybe try yourself to replicate again? You will probably be a lot faster than me or any other team member.

I tried to replicate the case when the previous version is Pending Developer Release, but they all were uploaded smoothly :) Seems like at least this case was a temporary issue.
