### ISSUE TITLE
Spaceship::UnauthorizedAccessError [from "testflight" action (ITC account without 2FA, sometimes works fine)]

### ISSUE THREAD

**Issue by rhcpfan** [fastlane/fastlane#13650]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Sometimes, I get "Unauthorized access" error while waiting for the build to be processed by ITC. My guess is that this happens if ITC takes very long to process the build.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>INFO [2018-11-06 16:21:11.48]: -----------------------------------------------------------------------------------------------------------
INFO [2018-11-06 16:21:11.48]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
INFO [2018-11-06 16:21:11.48]: -----------------------------------------------------------------------------------------------------------
INFO [2018-11-06 16:21:11.49]: Successfully uploaded the new binary to App Store Connect
INFO [2018-11-06 16:21:11.49]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
INFO [2018-11-06 16:21:21.73]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:21:54.64]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:22:25.52]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:22:56.42]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:23:27.73]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:23:58.90]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:24:30.63]: Waiting for App Store Connect to finish processing the new build (2.25.0 - 4)
INFO [2018-11-06 16:25:01.58]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:25:32.74]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:26:04.46]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:26:35.51]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:27:06.27]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:27:37.25]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:28:08.30]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:28:39.42]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:29:10.09]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-11-06 16:29:41.13]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
ERROR [2018-11-06 16:30:15.06]: Unauthorized Access

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | Verifying fastlane version               | 0           |
| 2    | default_platform                         | 0           |
| 3    | clear_derived_data                       | 10          |
| 4    | Switch to ios set_environment_variables  | 0           |
|      | lane                                     |             |
| 5    | ensure_git_status_clean                  | 0           |
| 6    | git_pull                                 | 3           |
| 7    | git checkout "$RELEASE_BRANCH"           | 0           |
| 8    | cocoapods                                | 209         |
| 9    | Switch to ios increment_build lane       | 0           |
| 10   | increment_build_number_in_plist          | 0           |
| 11   | slack                                    | 2           |
| 12   | Switch to ios beta lane                  | 0           |
| 13   | get_version_number_from_plist            | 0           |
| 14   | get_build_number_from_plist              | 0           |
| 15   | slack                                    | 0           |
| 16   | ./scripts/update-dependencies.sh         | 1           |
|      | "$ENGINE_VERSION" "$BUILD_FA             |             |
| 17   | slack                                    | 0           |
| 18   | match                                    | 12          |
| 19   | slack                                    | 0           |
| 20   | gym                                      | 661         |
| 21   | slack                                    | 3           |
| 22   | changelog_from_git_commits               | 9           |
| 💥   | testflight                               | 948         |
| 24   | slack                                    | 0           |
+------+------------------------------------------+-------------+

DEBUG [2018-11-06 16:30:15.12]: All plugins are up to date
ERROR [2018-11-06 16:30:15.12]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Unauthorized Access

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access+repo:fastlane/fastlane
➡️  Fastlane won't properly wait for 2FA code after call to prompt()
    https://github.com/fastlane/fastlane/issues/13538 [open] 0 💬
    3 weeks ago

➡️  Fastlane cert fails with 'Unauthorized Access'
    https://github.com/fastlane/fastlane/issues/11570 [closed] 22 💬
    11 Aug 2018

➡️  Fastlane init: Unauthorized Access
    https://github.com/fastlane/fastlane/issues/9321 [closed] 3 💬
    29 Aug 2017

and 7 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2018-11-06 16:30:16.09]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Spaceship::UnauthorizedAccessError: [!] The request could not be completed because:
	Unauthorized Access
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:706:in `block in send_request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:533:in `with_retry'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:700:in `send_request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:717:in `send_request_auto_paginate'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:584:in `request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/test_flight/client.rb:37:in `block in get_builds_for_train'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:533:in `with_retry'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/test_flight/client.rb:36:in `get_builds_for_train'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/test_flight/build.rb:113:in `builds_for_train'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/build_watcher.rb:45:in `matching_build'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/build_watcher.rb:23:in `block in wait_for_build_processing_to_be_complete'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/build_watcher.rb:22:in `loop'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/build_watcher.rb:22:in `wait_for_build_processing_to_be_complete'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/pilot/lib/pilot/build_manager.rb:55:in `upload'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:254:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:182:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.11.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E199)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.3                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|

    # Downloads and intstalls the provisioning profile and the distribution certificate from the git repository
    match(type: "appstore", app_identifier: ENV["APP_IDENTIFIER"], username: ENV["APPLE_ID"], git_branch: "objc-counting-app")
    
    slack(message: "User [" + ENV["APPLE_ID"] + "] succesfully fetched code signing identity for " + ENV["SCHEME"] + ". Starting building the project...")
    
    # Builds the project and creates an IPA file

    ipa_filename = ENV["SCHEME"] + "_" + version_number + "_" + build_number + ".ipa"

    gym(scheme: ENV["SCHEME"],
        configuration: "Release",
        output_directory: "./artifacts/products",
        export_team_id:   ENV["TEAM_ID"],
        silent: false,
        clean: false,
        buildlog_path: "./artifacts/buildlogs/",
        suppress_xcode_output: false,
        output_name: ipa_filename,
        disable_xcpretty: false
    ) # Build your app - more options available
        
    slack(message: "User [" + ENV["APPLE_ID"] + "] succesfully built the project and exported ./artifacts/products/" + ipa_filename + ". Uploading the build to TestFlight...")
        
     # Generate a changelog based on the commit history
     slack_change_log = changelog_from_git_commits(
      pretty: '* *%s* [*%cn* on *%cd*]',
      date_format: "short",
      merge_commit_filtering: "exclude_merges"
    )

    # Upload the IPA to TestFlight
    testflight(username: ENV["APPLE_ID"], app_identifier: ENV["APP_IDENTIFIER"], ipa: "./artifacts/products/" + ipa_filename, skip_submission: true, skip_waiting_for_build_processing: false, changelog: slack_change_log)

    slack(
      message: "User [#{ENV["APPLE_ID"]}] succesfully uploaded #{ENV["SCHEME"]}, version #{version_number} build #{build_number} on TestFlight.\nRelease notes:\n #{slack_change_log}"
    )

  error do |lane, exception|
    slack(message: exception.message, success: false)
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-versioning                 | 0.3.4   | ✅ Up-To-Date  |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| did_you_mean                               | 1.0.0        |
| bundler                                    | 1.17.1       |
| io-console                                 | 0.4.5        |
| CFPropertyList                             | 3.0.0        |
| concurrent-ruby                            | 1.0.5        |
| i18n                                       | 0.9.5        |
| minitest                                   | 5.11.3       |
| thread_safe                                | 0.3.6        |
| tzinfo                                     | 1.2.5        |
| activesupport                              | 4.2.10       |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.2        |
| atomos                                     | 0.1.3        |
| babosa                                     | 1.0.2        |
| claide                                     | 1.0.2        |
| fuzzy_match                                | 2.0.4        |
| nap                                        | 1.1.0        |
| cocoapods-core                             | 1.5.3        |
| cocoapods-deintegrate                      | 1.0.2        |
| cocoapods-downloader                       | 1.2.2        |
| cocoapods-plugins                          | 1.0.0        |
| cocoapods-search                           | 1.0.0        |
| cocoapods-stats                            | 1.0.0        |
| netrc                                      | 0.11.0       |
| cocoapods-trunk                            | 1.3.1        |
| cocoapods-try                              | 1.1.0        |
| colored2                                   | 3.1.2        |
| escape                                     | 0.0.4        |
| fourflusher                                | 2.0.1        |
| gh_inspector                               | 1.1.3        |
| molinillo                                  | 0.6.6        |
| ruby-macho                                 | 1.3.1        |
| nanaimo                                    | 0.2.6        |
| xcodeproj                                  | 1.7.0        |
| cocoapods                                  | 1.5.3        |
| colored                                    | 1.2          |
| highline                                   | 1.7.10       |
| commander-fastlane                         | 4.4.6        |
| declarative                                | 0.0.10       |
| declarative-option                         | 0.1.0        |
| unf_ext                                    | 0.0.7.5      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20180417 |
| dotenv                                     | 2.5.0        |
| emoji_regex                                | 0.1.1        |
| excon                                      | 0.62.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.15.3       |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.12.2       |
| fastimage                                  | 2.1.4        |
| jwt                                        | 2.1.0        |
| memoist                                    | 0.16.0       |
| multi_json                                 | 1.13.1       |
| os                                         | 1.0.0        |
| signet                                     | 0.11.0       |
| googleauth                                 | 0.6.7        |
| httpclient                                 | 2.8.3        |
| mime-types-data                            | 3.2018.0812  |
| mime-types                                 | 3.2.2        |
| uber                                       | 0.1.0        |
| representable                              | 3.0.4        |
| retriable                                  | 3.1.2        |
| google-api-client                          | 0.23.9       |
| json                                       | 2.1.0        |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.4.0        |
| rubyzip                                    | 1.2.2        |
| security                                   | 0.1.3        |
| naturally                                  | 2.2.0        |
| simctl                                     | 1.6.5        |
| slack-notifier                             | 2.3.2        |
| terminal-notifier                          | 1.8.0        |
| unicode-display_width                      | 1.4.0        |
| terminal-table                             | 1.8.0        |
| tty-screen                                 | 0.6.5        |
| tty-cursor                                 | 0.6.0        |
| tty-spinner                                | 0.8.0        |
| word_wrap                                  | 1.0.0        |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.3.0        |
| xcpretty-travis-formatter                  | 1.0.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| fastlane-plugin-versioning                 | 0.3.4        |
</details>

*generated on:* **2018-11-07**
</details>

**Comment by Sega-Zero** [comment]
Having the same issue here when running a build with a bot account without 2FA in Jenkins/Travis CI

**Comment by janpio** [comment]
What actually happens with the build? Is it processed as usual?

**Comment by rhcpfan** [comment]
> What actually happens with the build? Is it processed as usual?
> Any special options for the `testflight` action in use?

Yes, the build is processed fine and it shows in TestFlight after a while.

Running `testflight` with the following command (for more info see the `Fastfile` attached):

`# Upload the IPA to TestFlight`
`    testflight(username: ENV["APPLE_ID"], app_identifier: ENV["APP_IDENTIFIER"], ipa: "./artifacts/products/" + ipa_filename, skip_submission: true, skip_waiting_for_build_processing: false, changelog: slack_change_log)`

**Comment by mvanroon** [comment]
temporarily fixed this by removing the multi_line prompt

```
changelog = prompt(
  text: "Changelog: ",
  multi_line_end_keyword: "END"
)

upload_to_testflight(
  changelog: changelog <-- remove this line
)
```

**Comment by anushkmittal** [comment]
bump. am still getting this error. any permanent fix?

**Comment by janpio** [comment]
Open a new bug report issue please and include all the information it asks for.

**Comment by gtebbutt** [comment]
For those landing here from a search, the quick workaround is to run `fastlane spaceauth youremail@domain.com` - it'll allow you to input the 2FA code, and output an environment variable to use on other machines. You don't actually need to copy it, because running the command has cached it on your local machine and you can then use `fastlane` as normal for the next few weeks (until the session expires).
