### ISSUE TITLE
How to use deliver with fastlane swift

### ISSUE THREAD

**Issue by nickfedoroff** [fastlane/fastlane#13652]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Deliver with fastlane swift

No

No

#### Question Description

When initializing fastlane swift, a DeliverFile is created in the FastlaneRunner project. But when initializing Deliver, a non-swift `Deliverfile` is created in the fastlane directory. When running lanes thta call `deliver()` this non-swift (I assume Ruby) file is used in place of the auto-generated one in the FastlaneRunner project.

Additionally, the instructions in the auot-generated `Deliverfile.swift` aren't exactly clear on how to create a new `Deliverfile.swift` that will be used.

```
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
```

Following the above instructions will cause build errors in the FastlaneRunner Xcode project due to duplicate filenames.

What's the process for using deliver with fastlane swift?

**Comment by nickfedoroff** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {

	var username: String {
		return environmentVariable(set: nil, get: "username", remove: nil)
	}

	func beforeAll() {
		configure()
	}
	
	func betaLane(withOptions options:[String: String]?) {
		desc("Push a new beta build to TestFlight")
		
		bumpVersion()
		
		buildApp(workspace: "Simple Booth.xcworkspace", scheme: options?["scheme"] ?? "Halo")
		
		uploadToTestflight(username: username)
	}
	
	func betaUploadLane(withOptions options:[String: String]?) {
		uploadToTestflight(username: options?["username"] ?? "", ipa: "Simple Booth Halo.ipa")
	}

	func uploadMetadataLane() {
		deliver()
	}
	
	func playgroundLane(withOptions options:[String: String]?) {
		desc("Doesn't 'do' anything. Just a place to run commands and see what they do and how they work.")
		
		let version = getVersionNumber(xcodeproj: nil, target: "Halo", configuration: nil)
		puts(message: "🎸🎸🎸 VERSION: \(version) 🎸🎸🎸")

		let build = getBuildNumber()
		puts(message: "🎸🎸🎸 BUILD: \(build) 🎸🎸🎸")
		
		let user = environmentVariable(set: nil, get: "username", remove: nil)
		puts(message: "🎸🎸🎸 USER: \(user) 🎸🎸🎸")

	}
	
	func cleanLane() {
		desc("Clean project and delete derived data")
		xcclean()
		clearDerivedData()
	}

	func dsymLane(withOptions options:[String: String]?) {

		let buildNumber = options?["buildNumber"] ?? getBuildNumber()

		let versionNumber = options?["versionNumber"] ?? getVersionNumber(xcodeproj: nil, target: "Halo", configuration: nil)

		downloadDsyms(username: username, appIdentifier: appIdentifier, version: versionNumber, buildNumber: buildNumber)

		let dsymPath = "com.simplebooth.halo-\(versionNumber)-\(buildNumber).dSYM.zip"

		uploadSymbolsToCrashlytics(dsymPath: dsymPath, apiToken: nil, gspPath: nil, binaryPath: nil, platform: "ios", dsymWorkerThreads: 1)
	}

	// MARK: - Helpers
	
	/// Bump the build number and automatically commit and push the change.
	func bumpVersion() {
		
		ensureGitStatusClean()
		
		let buildNumber = incrementBuildNumber(xcodeproj: "Simple Booth.xcodeproj")
		
		commitVersionBump(message: "Bumping version from fastlane", xcodeproj: "Simple Booth.xcodeproj", include: [])
		
		let version = getVersionNumber(xcodeproj: nil, target: "Halo", configuration: nil)

		addGitTag(tag: "\(version)-(\(buildNumber))", buildNumber: buildNumber)
		
		pushToGitRemote()
	}


}

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>


*generated on:* **2018-11-08**
</details>

**Comment by janpio** [comment]
Can you maybe help out @taquitos here?

**Comment by andreyz** [comment]
+1 for the explanation on how to use delver with swift runner.

PS I can add that Swift side of Fastlane is poorly documented. Is it still a beta feature?

**Comment by janpio** [comment]
Yes: https://docs.fastlane.tools/getting-started/ios/fastlane-swift/

**Comment by andreyz** [comment]
@janpio yes to "Is it still a beta feature?" or to the lack of documentation?

I am well aware of the link you've shared, there is nothing there about how to call deliver or why does SwiftRunner doesn't read values from Deliver.swift and instead creates a "normal" Deliver file.

**Comment by janpio** [comment]
You asked a direct question, I replied with a link that mentions "Fastlane.swift (beta)" in the title. But I wouldn't disagree if you took my reply to an imaginary "Is fastlane.swift poorly documented?" question as well.

All the documentation is on GitHub, so if you have anything to add please open a PR and just add the missing information - that would be neat 💯 

And for your deliver problem this issue exists and I tried to pull someone in who might know more, see above.

**Comment by andreyz** [comment]
@nickfedoroff have you got to any resolution of your issue?
