### ISSUE TITLE
How to remove existing In-App Purchase item in App Store Connect?

### ISSUE THREAD

**Issue by vandit067** [fastlane/fastlane#13664]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by vandit067** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1212)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#comment this pry out. For Mike's debugging

require 'Nokogiri'
require 'Spaceship'
require 'pry'
require 'filewatcher'


Dir["**/*.rb"].select{ |file|
    file.downcase.include?("test") == false
}.each{ |file|
    require "./#{file}"
}

extend BuildFunctionsModule
extend DeliverFunctionsModule
extend SnapshotFunctionsModule

default_platform :ios

#Run this if there is any "There is already a transporter uploading..." type errors
#rm ~/.itmstransporter/UploadTokens/*.token

platform :ios do

    before_all do

        @root_dir = FileUtils.pwd
        puts @root_dir
        @FF = FastlaneFunctions.new
        @root_dir.slice! "/fastlane"
        puts @root_dir
        @time_stamp = Time.now.strftime("%m%d%Y")
    end

    lane :repl do |options|
        binding.pry
    end

    lane :remove_iap do |options|
      Spaceship::Tunes.login("xxx@xxx.com")
      # app_short_code = options[:app_short_code]
      apple_id = options[:apple_id]
      raise OptionParser::MissingArgument if apple_id.nil?
        begin
          error_file = File.new("errorLogs/remove_iap.txt", "w")
          # app_details = Spaceship::Tunes::Application.find(@FF.get_app_metadata_by_app_short_code(app_short_code)[properties][app_identifier])
          app_details = Spaceship::Application.find(apple_id)
          purch = app_details.in_app_purchases.all.first
          purch.is_editable = true
          iap = purch.edit
          # binding.pry
          puts iap.reference_name
          # purch.is_editable = true
          iap.cleared_for_sale = false
          iap.review_notes = "new notes 10 characters"
          iap.review_screenshot = "#{@root_dir}/screenshots/image.png"
          iap.save!
          # binding.pry
          # app_details.in_app_purchases.all.each do| purch |
          #   puts purch.reference_name
          # binding.pry
          # purch.edit
          # purch.cleared_for_sale = false
          # purch.save!
          # binding.pry
          # is_delete = purch.delete!
          # puts is_delete
          # end
        rescue Exception => e
            error_file.puts "Failed for #{apple_id} #{e.message}"
        end
        error_file.close
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV["APPLE_ID"]

#ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.6       |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| emoji_regex               | 0.1.1        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.6        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| io-console                | 0.4.6        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| psych                     | 2.2.4        |
</details>


*generated on:* **2018-11-12**
</details>

**Comment by vandit067** [comment]
any update?

**Comment by VanditPatel** [comment]
can anyone update me on this?

**Comment by janpio** [comment]
Update you on what exactly?
Android or iOS?
What does "How to remove IAP From App" mean? In the app? In the online administration from Apple?

**Comment by vandit067** [comment]
hey,

    It's seems like you didn't see the fast lane content which I uploaded.
Did you see the code which I written?

I am talking about iOS in app purchase remove using faslane. I written a
code for that and apply all possible solutions available online but it's
not working so I post this question here.

Thanks
Vandit

**Comment by janpio** [comment]
Ok, so you want to remove an existing In-App Purchase item in App Store Connect, correct? 
And you have already written some code in your `Fastfile`, the lane `remove_iap, but that doesn't work as intended, correct as well?
What did you try already? What were your sources?

**Comment by vandit067** [comment]
Yes I want to remove existing iap from app store connect.

Yes code which I written not showing any error but it's not delete iap from
that app.

Thanks
Vandit

**Comment by debeltranc** [comment]
You can do this using spaceship, you can begin from [here](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb#L285), that method should return an array that IIRC, has a `delete` method.
