### ISSUE TITLE
The recommended .gitignore works only for fastlane directory in repo root 

### ISSUE THREAD

**Issue by jhahn21** [fastlane/fastlane#13665]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

The recommended `.gitignore` in [Docs » Best Practices » Source Control](https://docs.fastlane.tools/best-practices/source-control/#source-control) should be changed to work recursively.

#### Question Description

The recommended `.gitignore` in [Docs » Best Practices » Source Control](https://docs.fastlane.tools/best-practices/source-control/#source-control) works only for `fastlane` directory where `.gitignore` exists (usually a repo root).

But in many cases, there are multiple fastlane directories in a repo like `.../ios/fastlane` or `.../android/fastlane`. 

I think it would be better to have`.gitignore` like
```
# fastlane specific
**/fastlane/report.xml

# deliver temporary files
**/fastlane/Preview.html

# snapshot generated screenshots
**/fastlane/screenshots

# scan temporary files
**/fastlane/test_output
```

**Comment by janpio** [comment]
This `.gitignore` file is probably meant to be placed into the mobile project itself, not in the level above. Do you disagree with this choice?

**Comment by jhahn21** [comment]
I understand your point, but it doesn't work in a cross-platform mobile development environment.
For example, we're using flutter, which includes ios and android directories like

```
app
   - android
       - fastlane
   - ios
       - fastlane
```
In this case, we have to have at least two `.gitingore` in `android` and `ios` directory for one project.

**Comment by janpio** [comment]
Exactly. Is this a problem?

**Comment by jhahn21** [comment]
My proposal was to make `.gitignore` general to cover all subdirectories instead of having `.gitignore` in every fastlane directory.

**Comment by janpio** [comment]
Ok, feel free to create a PR of https://github.com/fastlane/docs/edit/master/docs/best-practices/source-control.md with the changes you suggest.
