### ISSUE TITLE
gradle flags param not working as documented

### ISSUE THREAD

**Issue by jaimeagudo** [fastlane/fastlane#13661]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

`gradle flags`

Perhaps docs are wrong

#### Question Description

As per docs https://docs.fastlane.tools/actions/gradle/#parameters and this issue https://github.com/fastlane/fastlane/issues/6930 the `flags` parameter should be legal
Fastfaile
```
platform :android do

  desc "Runs a debug build"
  lane :debugbuild do
    gradle(task: "assembleDebug" flags: "--stacktrace")
  end
```

```
$ bundle exec fastlane debugbuild
[13:33:16]:     25:	  lane :debugbuild do
[13:33:16]:  => 27:	    gradle(task: "assembleDebug" flags: "--stacktrace")
[13:33:16]:     28:	  end
[13:33:16]:     29:

[!] Syntax error in your Fastfile on line 27: Fastfile:27: syntax error, unexpected tIDENTIFIER, expecting ')'
le(task: "assembleDebug" flags: "--stacktrace")
                              ^
Fastfile:27: syntax error, unexpected ')', expecting keyword_end
Debug" flags: " --stacktrace")
                              ^
Fastfile:66: syntax error, unexpected keyword_end, expecting end-of-input
Error: Exited with code 1
Step failed
```

I plan to use the flags this way to debug a non related CircleCI issue

**Comment by jaimeagudo** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.3.0                           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Runs a debug build"
  lane :debugbuild do
#    gradle(task: "clean")
    gradle(task: "assembleDebug" flags: " --stacktrace")
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    ensure_git_branch(branch: "master")
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("secret.package") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.2        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.1.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.2        |
| security              | 0.1.3        |
| emoji_regex           | 0.1.1        |
| tty-cursor            | 0.6.0        |
| tty-screen            | 0.6.5        |
| faraday               | 0.15.3       |
| openssl               | 2.0.5        |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| io-console            | 0.4.6        |
| excon                 | 0.62.0       |
| CFPropertyList        | 3.0.0        |
| plist                 | 3.4.0        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.7.0        |
| faraday_middleware    | 0.12.2       |
| signet                | 0.11.0       |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.9       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20180417 |
| memoist               | 0.16.0       |
| googleauth            | 0.6.7        |
| fastimage             | 2.1.4        |
| bundler               | 1.16.0.pre.2 |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.4.0        |
| addressable           | 2.5.2        |
| retriable             | 3.1.2        |
| mime-types            | 3.2.2        |
| mime-types-data       | 3.2018.0812  |
| multi_json            | 1.13.1       |
| jwt                   | 2.1.0        |
| os                    | 1.0.0        |
| psych                 | 2.2.4        |
| uber                  | 0.1.0        |
</details>


*generated on:* **2018-11-09**
</details>

**Comment by hosek** [comment]
You are missing comma between params
`gradle(task: "assembleDebug" , flags: "--stacktrace")`

**Comment by janpio** [comment]
Indeed. Did adding the comma fix your issue @jaimeagudo?

**Comment by jaimeagudo** [comment]
Sorry guys, yes, I realised it! Thanks
