### ISSUE TITLE
How to access environment variables in application?

### ISSUE THREAD

**Issue by nhgrif** [fastlane/fastlane#13677]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Setting values in `ProcessInfo.processInfo.environment` via Fastlane

#### Question Description

I have a need to set variables via Fastlane that are accessible in-app via `ProcessInfo.processInfo.environment`.  I need to do this so that I can modify the values before launching the app in UI tests.

So far, simply setting the values in my `.env` files doesn't get them to show up.  I can get the values into my Info.plist, and reference the values from there, but this doesn't work as a great solution for me, as I may need to modify values here during a test run, where the Info.plist won't be repopulated with values I need to modify to.

**Comment by janpio** [comment]
Hey @nhgrif - using `.env` will change the environment variables of the system running fastlane. If I understood you correctly, you want to set them on the simulator running the tests?

**Comment by nhgrif** [comment]
Whether it's a simulator or a real running device, I would like, for example, to grab the baseURL for my app out of `ProcessInfo.processInfo.environment`.  This works, if for example, I set a "USER DEFINED" variable in the "Build Settings" of my target.

![image](https://user-images.githubusercontent.com/6437208/49255461-b1c5d380-f3f1-11e8-8303-3d41184a02f0.png)

I'd like to be able to set this values via Fastlane .env files in some way.

**Comment by janpio** [comment]
So we are talking about iOS and Xcode here, correct?
Where exactly do you use `ProcessInfo.processInfo.environment` - in the code of your app? Liek [this](https://medium.com/@derrickho_28266/xcode-custom-environment-variables-681b5b8674ec)?

If I understood how this works correctly, you want to effectively modify your Xcode project using fastlane. I am not aware of an action that does this directly, but fastlane uses `xcodeproj` internally, so you can also use it in your `Fastfile`. 

It has 2 classes that seem relevant: https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/XCScheme/EnvironmentVariable + https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/XCScheme/EnvironmentVariables (which was added at https://github.com/CocoaPods/Xcodeproj/pull/326)

A good first step would be to make a backup copy of your code project, then use Xcode to create a environment variable like you want to manually. Then copy the new state of the Xcode project to the backup copy. What files changed? What got added?

If you know that, it will be easier to use `xcodeproj` to create the correct data and entries.

---

My guess is you will end up something like this:
```
xcode_project_path = '...'
scheme_name = '...'
proj = Xcodeproj::Project.open(xcode_project_path) || UI.user_error!("Unable to open Xcode project '#{xcode_project_path}'")
existing_scheme = Xcodeproj::XCScheme.shared_data_dir(xcode_project_path) + "/#{scheme_name}.xcscheme"
scheme = File.exist?(existing_scheme) ? Xcodeproj::XCScheme.new(existing_scheme) : Xcodeproj::XCScheme.new
scheme.environment_variables['key'] = 'value'; # not 100% sure about this line
scheme.save_as(xcode_project_path, scheme_name)
proj.save
```

**Comment by Skoti** [comment]
@nhgrif 
As I understand you're trying to pass some _environment variables_ via fastlane - I think it is possible if you're using `xcodebuild` directly, i.e.
`SOME_ENV_VAR="some_value" xcodebuild -workspace ...`
this is an equivalent of setting them in `Edit Scheme -> Arguments -> Environment Variables` in Xcode. These are accessible via `ProcessInfo.processInfo.environment`.

If you're not using `xcodebuild` directly then _fastlane_ supports only _build arguments_. (i.e. in `gym` or `scan`) via `xcargs` parameter.
This is an equivalent of:
`xcodebuild -workspace ... SOME_SETTING="some_value"`
And these are accessible via `Bundle.main.object(forInfoDictionaryKey:)`
mind that passing them like that will overwrite what you have defined in _xcconfig_ file and/or _User-Defined_ settings in Xcode.

So use what is more applicable in your situation.
Hope this clarifies things a bit.
