### ISSUE TITLE
gitlab-runner exec shell result FastlaneCrash

### ISSUE THREAD

**Issue by owdeveloper** [fastlane/fastlane#13675]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
command `gitlab-runner exec shell "JOB"` not working

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>MacBook-Pro-de-Fernando:gr1d-whitelabel-wallet-ios fernandohenrique$ gitlab-runner exec shell test_flight_build
Runtime platform                                    arch=amd64 os=darwin pid=12921 revision=cf91d5e1 version=11.4.2
WARNING: You most probably have uncommitted changes. 
WARNING: These changes will not be tested.         
Running with gitlab-runner 11.4.2 (cf91d5e1)
Using Shell executor...
Running on MacBook-Pro-de-Fernando.local...
Cloning repository...
Cloning into '/Users/fernandohenrique/Documents/_developer/ios/whitelabel-ios/builds/0/project-0'...
done.
Checking out 6a7b4f5d as feature/gitlab_ci...
Skipping Git submodules setup
$ fastlane certificates
[16:47:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:47:57]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?

Looking for related GitHub issues on fastlane/fastlane...

➡️  Run deliver without Deliverfile
    https://github.com/fastlane/fastlane/issues/13331 [closed] 2 💬
    3 weeks ago

➡️  [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/12355 [closed] 10 💬
    19 Sep 2018

➡️  How to make fastlane use http proxy?
    https://github.com/fastlane/fastlane/issues/12935 [closed] 7 💬
    a week ago

and 32 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:133:in `confirm'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:343:in `ensure_fastfile'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
ERROR: Job failed: exit status 1
FATAL: exit status 1 </pre>
</details>

### Environment

<details>
  <pre>                              
</pre>
</details>

**Comment by janpio** [comment]
Fastlane is complaining that it can't find its configuration, the `fastlane` folder. Can you double check in which folder you are executing `fastlane certificates` and make sure it contains this configuration folder?
