### ISSUE TITLE
suggestion: updates feed

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#1367]
It would be great to get an rss feed of updates (to all the fastlane tools)

**Comment by vpolouchkine** [comment]
Good idea. As a workaround, perhaps you can use some service to generate an RSS feed based on https://twitter.com/fastlanetools.

**Comment by KrauseFx** [comment]
Also, check out Libraries.io doing exactly that: https://libraries.io/rubygems/fastlane
Additionally you can use the GitHub RSS https://github.com/fastlane/fastlane/releases.atom

**Comment by ConfusedVorlon** [comment]
thanks - I found the github feed after posting. The only limitation is that I have to add each tool separately into feedly. (same thing with Libraries.io I think).

**Comment by KrauseFx** [comment]
:+1:
