### ISSUE TITLE
xcodebuild-safe.sh fails on CircleCI, Xcode 9 while xcodebuild works fine

### ISSUE THREAD

**Issue by peteris** [fastlane/fastlane#13673]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The `xcbuild-safe.sh` script fails when running it on CircleCI (`macOS`, `xcode: 9.4.1`), while `xcodebuild` works fine with the same parameters. 

I believe this is due to [`which rvm > /dev/null`](https://github.com/fastlane/fastlane/blob/master/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh#L25) returning an exit code in this environment, and `xcodebuild` at the bottom of the script never executing.

If I make a simple change to the script, it runs correctly:

### Broken
```
which rvm > /dev/null
# shellcheck disable=SC2181
if [[ $? -eq 0 ]]; then
  ...
fi
```

### Working
``` 
# shellcheck disable=SC2181
if which rvm > /dev/null; then
  ...
fi
```
AFAIK using `$?` in this scenario is considered an antipattern if the only purpose of the previous command is to be used in the `if` check. And [the rvm check in the same module](https://github.com/fastlane/fastlane/blob/master/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh#L38) is implemented in the proposed way – so hoping this is a simple change, I'm happy to open a PR if so!

##### Complete output when running fastlane, including the stack trace and command used
This happens when the `fastlane` call is executed by [`turtle-cli`](https://www.npmjs.com/package/turtle-cli) so I've included the exact line for reference.
```
$ /usr/bin/xcrun /Library/Ruby/Gems/2.3.0/gems/fastlane-2.108.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/gk/lkr9pm5b039fx6d3j9r52rv80000gn/T/gym_config20181113-1756-1d38qaw.plist' -archivePath /private/tmp/turtle/c15d5bc8-1344-451f-a0c8-819b6d211baf/archive.xcarchive -exportPath '/var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/gym_output20181113-1756-uopd4i' OTHER_CODE_SIGN_FLAGS="--keychain /private/tmp/xdl/e94c9e80-e751-11e8-b5cf-29a2acc8a038.keychain"
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

### Environment

<details>
  <pre>
<summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-9.4.1.app/Contents/Developer/              |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0        |
</details>

*generated on:* **2018-11-13**
</pre>
</details>

**Comment by janpio** [comment]
I have no real idea about shell scripts, but this looks like a reasonable change if it fixes a problem for you.

@lacostej It has been _only_ 3 years, do you remember if you chose this way to express this for a specific reason?
