### ISSUE TITLE
Suggestion: fastlane for window phone

### ISSUE THREAD

**Issue by Douvi** [fastlane/fastlane#1368]
Hi,

First i need to say a gid thanks for all the jobs you are doing. You save us a lot of time :)

I m already using your lib for ios and android. I guess you do not want to stop like that, right ? Do you know when you will start to do a fastlane for Window Phone

Thanks

**Comment by vpolouchkine** [comment]
Great idea! I will share this with the team and see what we can do in a future release. I’ll reopen this ticket and keep you updated when we get a chance to revisit this, stay tuned :+1: If you want to tackle this yourself, check out the [countdown](https://github.com/fastlane/countdown) repo to learn how to contribute to `fastlane`.
