### ISSUE TITLE
Generated .ipa size too big 

### ISSUE THREAD

**Issue by NSEGeorge** [fastlane/fastlane#13699]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Size of generated ipa by gym for AppStore is too large (500Mb). But size of ipa generated by xcode is less(116Mb)

### Lane
```
  lane :make_ipa_for_testflight do
    sh("cd .. && bundle exec env STATIC_LIBS=true pod install && cd fastlane")
    unlock_keychain if is_ci?
    output_name = "testflight_release.ipa"
    gym(
      scheme: "AlphaBank-Distribution",
      output_name: output_name,
      clean: true,
      codesigning_identity: "iPhone Distribution: AO ALFA-BANK",
      export_method: "app-store",
      export_options: EXPORT_OPTIONS_APPSTORE,
      output_directory: "."
    )
  end
```

### Environment

<details>

| Key                         | Value                                                            |
| --------------------------- | ---------------------------------------------------------------- |
| OS                          | 10.14                                                            |
| Ruby                        | 2.5.1                                                            |
| Bundler?                    | true                                                             |
| Git                         | git version 2.17.2 (Apple Git-113)                               |
| Installation Source         | ~/Documents/am-ios2/am-ios/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.14 (18A391)                                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib                                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                                      |
| Is contained                | false                                                            |
| Is homebrew                 | false                                                            |
| Is installed via Fabric.app | false                                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                      |
| Xcode Version               | 10.1                                                             |
</details>

**Comment by janpio** [comment]
Hey @NSEGeorge, can you share the output you get when running the `make_ipa_for_testflight` lane?

**Comment by NSEGeorge** [comment]
@janpio which part of output do you need? Just some outputs are private (e.g. files names) and I can't share they.

**Comment by janpio** [comment]
Remove whatever you have to - but this is basically the output that makes us understand what is going on and is the first thing we have to look at to see what commands are generated and executed.

**Comment by starburst997** [comment]
Have the same issue, my new machine have `2.107.0` installed and I noticed recently that my iOS build sent to iTune where much larger than before (+50-100MB), using the exact same process on my other machine with `2.106.0` installed results in the expected file size. Granted there is other difference between the two machine like mac os version, xcode version, etc. But basically `fastlane gym` now produce much larger binary (and for some reason I can't install version 106 on the new machine, 107 and 108 works).

**Comment by janpio** [comment]
(Can you create a new issue for the "I can't install version 106 on the new machine, 107 and 108 works" problem? Maybe we can debug that.)

**Comment by starburst997** [comment]
Of course, bit in a hurry since a have release to send so I'll do some day this week! I'm afraid to even upgrade fastlane on that other machine to see if upgrading to latest version is really the issue and not some kind of misconfiguration on my machine since I can't afford the time to debug atm!!

**Comment by janpio** [comment]
Good luck! Let us know if you made it ;)
