### ISSUE TITLE
How can i skip exportArchive after Archive succeeded 

### ISSUE THREAD

**Issue by ygyin-ivy** [fastlane/fastlane#13694]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How can i skip exportArchive after Archive succeeded 

#### Question Description
After Archive succeeded, fastlane will exportArchive using "xcrun \*/fastlane/\*/xcbuild-safe.sh -exportArchive *",
it will cost a huge time , because there are many pods installed in my project
Is it  possible to export ipa file without exportArchive ?

**Comment by janpio** [comment]
Please answer the question @fastlane-bot posed, so we can have a look at the lane you are executing and what action you are talking about. Then we can maybe investigate further.

**Comment by ygyin-ivy** [comment]
[log.txt](https://github.com/fastlane/fastlane/files/2593397/log.txt)
