### ISSUE TITLE
Wrong size for Ipad 2nd and 3rd generation

### ISSUE THREAD

**Issue by Radunani** [fastlane/fastlane#13698]
```
[!] Unsupported screen size [2048, 2730] for path './screenshots/en-AU/iPad Pro (12.9-inch) (2nd generation)-ExecuteExercise.png'
[!] Unsupported screen size [1241, 2688] for path './screenshots/de-DE/iPhone XS Max-ExecuteExercise.png'
[!] Unsupported screen size [1982, 2642] for path './screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-ExecuteExercise.png'
```

**Comment by Radunani** [comment]
[!] Unsupported screen size [2048, 2730] for path './screenshots/en-AU/iPad Pro (12.9-inch) (2nd generation)-ExecuteExercise.png'
[!] Unsupported screen size [1241, 2688] for path './screenshots/de-DE/iPhone XS Max-ExecuteExercise.png'
[!] Unsupported screen size [1982, 2642] for path './screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-ExecuteExercise.png'

**Comment by janpio** [comment]
Hey @Radunani, can you share what you were trying to do when you got this output? What command or action was executed?

**Comment by dcristolovean** [comment]
I also have the 1241 issue on xs max, instead of 1242.  How can we fix this?

**Comment by janpio** [comment]
Step 1: Tell me which action/tool is returning that error - then we can take a look at the code ;)

**Comment by janpio** [comment]
Ok, seems the error is from `deliver` and the screenshot were taken with `snapshot` I guess?

**Comment by koxon** [comment]
Yes we have this issue with Iphone XS Max. The width is 1241 instead of 1242 thus `deliver` fails as Apple rejects the screenshots. I checked the Fastlane code but I couldn't find the issue.
Any clue ?

**Comment by janpio** [comment]
Not the slightest. As far as I know the emulator is started with the device name, then scaled to 100%, the screenshots are taken. This should not give 1px smaller screenshots :/ Someone will have to look through the code for more information.

**Comment by dcristolovean** [comment]
Happens with the simplest lane:
capture_screenshots(test_target_name: org_id, scheme: scheme, output_directory: "./fastlane/metadata/#{org_id}/screenshots", number_of_retries:1

If I manually take a screenshot from the XS Max, the result is OK, 1242.  With fastlane, 1241.
I'm using also iPhone8+ and iPhoneX and the screenshots are OK for those. 

Happened on 2 different systems, so it's not probably something related to my env.

**Comment by dcristolovean** [comment]
hey guys, any news with this?  Can't believe we are the only ones trying to get XS Max screenshots considering that Apple only accepts those now....

**Comment by joncursi** [comment]
What is the correct size for the iPad 12.9 gen 2 given that it errors on `[1982, 2642]`?

**Comment by dcristolovean** [comment]
XSMax is off by 1pixel, 1241x2688 instead of 1242x2688
iPad PRO 12.9 3rd gen is off by 2 pixels,  2048x2730 instead of  2048x2732

No idea what that 1982x2642 is, lets focus on these 2 other issues.
At least 2 screenshots get messed up and at least 2 of them are OK (8+ and iX).  Didn't test others.

**Comment by janpio** [comment]
> No idea what that 1982x2642 is, lets focus on these 2 other issues.

The original issue you are replying to also mentioned `1982x2642` which seems to be a wrong size for `iPad Pro (12.9-inch) (3rd generation)`.

**Comment by dcristolovean** [comment]
I know, that's the odd one out. It's not even close to any iPads, 12.9, 11, 10.5 or 9.7.

**Comment by janpio** [comment]
Closing this one in favor of #13610, which is about the same problem. Please check over there for further inquiries from me about details. Thanks!
