### ISSUE TITLE
Invalid username and password combination. Used 'xxxx@xxxx.com' as the username.

### ISSUE THREAD

**Issue by royorange** [fastlane/fastlane#13707]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Before yesterday fastlane works well，but since last Friday, the CI environment  went wrong and throw
such error. 
The password of account is right. And We never set FASTLANE_PASSWD or FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD before. 
The password is combined with character and number.

Any advice? Thanks!

#### Question Description

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14                                                          |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14 (18A391)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
import_from_git(
  url: "git@gitlab.wisburg.com:mobile/fastlane.git",
  branch: "master",
  path: "fastlane/Fastfile"
)

```
</details>

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.3       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| fastimage                 | 2.1.4        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| os                        | 1.0.0        |
| psych                     | 2.1.0.1      |
</details>


*generated on:* **2018-11-18**
</details>

**Comment by maratgaliev** [comment]
+1 same

**Comment by janpio** [comment]
Just a guess: There is probably a cookie in the browser that allows connecting without triggering 2FA or another 2FA token - which is missing on CI. You might try to confirm by deleting cookies. (I am having similar issues at https://github.com/fastlane/fastlane/issues/13705 and don't fully understand yet what is going on here)

**Comment by royorange** [comment]
> Just a guess: There is probably a cookie in the browser that allows connecting without triggering 2FA or another 2FA token - which is missing on CI. You might try to confirm by deleting cookies. (I am having similar issues at #13705 and don't fully understand yet what is going on here)

The 2FA is triggered when I visit in browser, so I don't think the cookie can cause that.

**Comment by royorange** [comment]
@bolom In my case, I resolved it by disable my http proxy setting. The error message will be thrown when the login method of spaceship is wrong. So if your password is correct, maybe you should also check the network status(especially if you use proxy) when connecting to Dev Portal or App Store Connect.

**Comment by adilmalik393** [comment]
Hye, we are experiencing the same issue. @royorange Can you explain this proxy fix.

**Comment by royorange** [comment]
@adilmalik393 Do you have some proxy setting in your system?
 If not, you can try use spaceship login:
1. type irb in the terminal to open the interactive ruby
2. execute require "spaceship"
3. execute Spaceship::Tunes.login("your account", "your password")
It will return some information like "Two-step Verification" or else if you have correct account&password.
If the login success, it means fastlane will work properly.
Be careful, if you use the bash, the proxy setting for terminal is in ~/.bash_profile and ~/.zshrc for zsh.
Hope it can help 🤣

**Comment by adilmalik393** [comment]
@royorange  Thanks for your help. I solved it via copying session from local profile to remote machine.
