### ISSUE TITLE
Improve useful lane-chooser feature

### ISSUE THREAD

**Issue by mosesoak** [fastlane/fastlane#1370]
The lane chooser is an extremely useful feature. It lets me hand Fastlane to a fairly non-technical user, such as a producer, and now they have all the power to make builds and deploy them, with just `fastlane`. It also saves time for me and other developers, since I have so many commands and don't always remember exactly how they're named. 

We use it as a quick launch command, essentially.

This is the thing I'm referring to:
```
    # Lane chooser if user didn't provide a lane
    # @param platform: is probably nil, but user might have called `fastlane android`, and only wants to list those actions
    def self.choose_lane(ff, platform)
      loop do
        UI.error "You must provide a lane to drive. Available lanes:"
```

A few small tweaks would improve it:

1. **Show the lane description next to the name.** That's my main request. This makes it easy for a producer to figure out which command does what. (Pretty is good in this case. For example, using a plain `puts` to print the numbered choices without timestamps would make it feel less intimidating to non-technical users and would be more legible. Columnating the names and descriptions would make it even easier to read.)
2. **Add a Cancel option** after all the lanes (producers may not know how to ctrl-c out)
3. **Treat the lane chooser as a 1st-class feature, not a user mistake.** Other Fastlane features give positive feedback, and there's no real reason to discourage use of this great launcher tool.

Thanks for considering it, and sorry that I am unable to submit a PR for these changes right now!

**Comment by KrauseFx** [comment]
Hey @mosesoak, 

I really like this idea, thanks for your feedback! You're right, this was implemented to "recover" from a user mistake, but I can see your use-case. I'd love to see this feature, this would improve the fastlane experience :+1:

**Comment by mosesoak** [comment]
Awesome! In general, just tacking description onto name without any of the rest would be very helpful, and hopefully a very small change for you. Thanks Felix!

**Comment by KrauseFx** [comment]
Agreed, however it might require some UI adaption depending on how long the description is. I'm more than happy to review a PR adding this functionality, the code is all here: https://github.com/fastlane/fastlane/blob/master/lib/fastlane/lane_manager.rb#L105-L131
Also, check out https://github.com/fastlane/countdown on how to get started with contributing to `fastlane` :+1:

**Comment by hemal** [comment]
Just merged a solution, give it a try and let me know what you think!

**Comment by mosesoak** [comment]
:+1: :+1: :+1: :100: LOVE IT!!! Thanks so much guys!

**Comment by mosesoak** [comment]
![screen shot 2016-04-14 at 1 20 58 pm](https://cloud.githubusercontent.com/assets/24345/14542671/f6a18c66-0244-11e6-844c-3f680bde64b4.png)

**Comment by hemal** [comment]
Woot woot, there it is!
