### ISSUE TITLE
Cosmetic: screenshots.html label and link incorrect for iPad Pro 11-inch.

### ISSUE THREAD

**Issue by cortis** [fastlane/fastlane#13701]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Cosmetic Issue Only. Screenshots are actually correct.
If you specify "iPad Pro (11-inch)" in your devices list of your Snapfile and generate snapshots, the resultant screenshots.html file will insert the incorrect label for the generated snapshots.  
expected label:  "iPad Pro (11-inch)" 
actual label: "iPad Pro (12.9-inch)"

**Comment by janpio** [comment]
This should be fixed now. Can you confirm @cortis?
