### ISSUE TITLE
New Microsoft App Center

### ISSUE THREAD

**Issue by maurovc** [fastlane/fastlane#13704]
### Feature Request
Create a new AppCentre action to replace hockeyapp in the future

#### Motivation Behind Feature
Hockeyapp will be closed one year from now, but Microsoft already provides an API for AppCenter.

**Comment by janpio** [comment]
Microsoft offers a superb fastlane plugin for AppCenter already: https://github.com/Microsoft/fastlane-plugin-appcenter That should do the job :)
