### ISSUE TITLE
How to terminate background process upon lane is finished (Wiremock)

### ISSUE THREAD

**Issue by nebillo** [fastlane/fastlane#13700]
### Question Checklist

- [x] Updated fastlane to the latest version
- [] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How to terminate background process upon lane is finished (Wiremock)

#### Question Description
We have successfully managed to spin-up a Wiremock server to run our UI tests.
However we noticed the integration hangs perpetually causing a timeout exception on our CI (Bitrise).
This is caused by the Wiremock instance not being shut down.

Is there a way to achieve this using fast lane?

Here's the piece of code from our ruby script:

```
  WIREMOCK_PID = nil
  
  after_all do |lane, options|
     killMockServer
  end

  lane :runMockServer do
    mockServerPath = ENV['BITRISE_SOURCE_DIR'] + '/mobile-mock-server'
    cmd = 'java -jar ' + mockServerPath + '/wiremock-standalone-2.19.0.jar --port 1234 --root-dir '+ mockServerPath +' &'
    # system cmd
    system cmd do |status, result, command|
  	  unless status.success?
  	    UI.error "Command #{command} (pid #{status.pid}) failed with status #{status.exitstatus}"
  	  end
  	  UI.message "Output is #{result.inspect} (pid #{status.pid})"
          WIREMOCK_PID = status.pid
	end
  end

  def killMockServer
  	if WIREMOCK_PID
  		puts "killing process: " + WIREMOCK_PID
	  	sh("kill", WIREMOCK_PID)
  	end
  end
```

Thank you

**Comment by janpio** [comment]
Hey @nebillo, I am a bit lost: What is the connection to fastlane in your question?
