### ISSUE TITLE
Upload to playstore finished successfully but is not uploaded

### ISSUE THREAD

**Issue by HerrNiklasRaab** [fastlane/fastlane#13708]
Hello,

just tried to set up the lane for uploading to playstore, but it doesn't seem to work. It says it finished sucessfully, but on my playstore console. Nothing got uploaded.

This is what i get, when I execute my lane for uploading to playstore:
```
PS C:\Flutter\src\hapii\android> fastlane alpha
 [✔] 🚀
[18:01:05]: fastlane detected a Gemfile in the current directory
[18:01:05]: however it seems like you don't use `bundle exec`
[18:01:05]: to launch fastlane faster, please use
[18:01:05]:
[18:01:05]: $ bundle exec fastlane alpha
[18:01:05]:
[18:01:05]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:01:07]: -----------------------------
[18:01:07]: --- Step: update_fastlane ---
[18:01:07]: -----------------------------
[18:01:07]: Looking for updates for fastlane...
[18:01:09]: Nothing to update ✅
[18:01:09]:
[18:01:09]: Please help us test early releases of fastlane by opting into nightly builds 🌃
[18:01:09]: Just replace your `update_fastlane` call with
[18:01:09]:
[18:01:09]: ▸ update_fastlane(nightly: true)
[18:01:09]:
[18:01:09]: Nightly builds are reviewed and tested just like the public releases 🚂
[18:01:09]:
[18:01:09]: ------------------------------
[18:01:09]: --- Step: default_platform ---
[18:01:09]: ------------------------------
[18:01:09]: Driving the lane 'alpha' 🚀
[18:01:09]: ----------------------------------
[18:01:09]: --- Step: upload_to_play_store ---
[18:01:09]: ----------------------------------

+-------------------------+------------------------------------+
|                  Summary for supply 2.108.0                  |
+-------------------------+------------------------------------+
| track                   | beta                               |
| json_key                | googleServiceAccountPlayStore.json |
| skip_upload_images      | true                               |
| package_name            | com.hapi.hapiapp                   |
| metadata_path           | ./fastlane/metadata/android        |
| skip_upload_apk         | false                              |
| skip_upload_aab         | false                              |
| skip_upload_metadata    | false                              |
| skip_upload_screenshots | false                              |
| validate_only           | false                              |
| check_superseded_tracks | false                              |
| timeout                 | 300                                |
| deactivate_on_promote   | true                               |
+-------------------------+------------------------------------+

[18:01:10]: Preparing to upload for language 'de-DE'...
[18:01:11]: Updating changelog for code version '1' and language 'de-DE'...
[18:01:12]: Uploading all changes to Google Play...
[18:01:14]: Successfully finished the upload to Google Play

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | update_fastlane      | 2           |
| 2    | default_platform     | 0           |
| 3    | upload_to_play_store | 4           |
+------+----------------------+-------------+

[18:01:14]: fastlane.tools finished successfully 🎉
```

`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.5.3                        |
| Bundler?                    | false                        |
| Git                         | git version 2.19.1.windows.1 |
| Installation Source         | C:/Ruby25-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby25-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018   |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
  end
end

lane :alpha do
  upload_to_play_store(
    track: 'beta',
    json_key: "googleServiceAccountPlayStore.json",
    skip_upload_images: true
  )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name("com.hapi.hapiapp")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.6       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| addressable               | 2.5.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.2        |
| fiddle                    | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-11-18**`

**Comment by HerrNiklasRaab** [comment]
@janpio Uploading via "fastlane supply" **worked correctly now**, my internet connection was slow. The output "Preparing apk at path" is little bit missunderstanding, because it is not preparing it is uploading.

But uploading via the fastlane script with the function "upload_to_play_store" **is still not working** correctly. The output says that the command "fastlane alpha" finished successfully. But no apk is uploaded and as you see in the output the function "upload_to_play_store" takes 4s. 4s are to less to upload the apk. This i proved also in the play store developer console. Apk is not uploaded via the "fastlane alpha" command.

**Comment by janpio** [comment]
4s are more than enough for what you ask `upload_to_play_store` to do:

`fastlane alpha` is a command that executes the `alpha` lane (from your `Fastfile`):

```
lane :alpha do
  upload_to_play_store(
    track: 'beta',
    json_key: "googleServiceAccountPlayStore.json",
    skip_upload_images: true
  )
end
```

You are missing the path to the APK here, so it is just uploading and updating the metadata.

This will probably work just fine as it is if you run a lane that executes `gradle` right before, as this will set an environment variable with the APK path, and it will appear in the `Summary for supply ...` table. But to make sure this lane always works, you will have to set the the path to the apk in the `apk` option/parameter.

**Comment by HerrNiklasRaab** [comment]
@janpio  Thanks a lot, that was the problem. Thanks!
