### ISSUE TITLE
[snapshot] reset_simulators: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162): Incompatible device

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13710]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running `fastlane snapshot reset_simulators` I got this error multiple times:

```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162): 
Incompatible device
```

##### Complete output when running fastlane, including the stack trace and command used

```
MacBook-Pro:ios sujan$ fastlane snapshot reset_simulators
[✔] 🚀 
[20:11:35]: Are you sure? All your simulators will be DELETED and new ones will be created! (You can use `SNAPSHOT_FORCE_DELETE` to skip this confirmation) (y/n)
y

[20:11:51]: Deleting iPhone 5s
[20:11:53]: Deleting iPhone 6
[20:11:54]: Deleting iPhone 6 Plus
[20:11:55]: Deleting iPhone 6s
[20:11:55]: Deleting iPhone 6s Plus
[20:11:56]: Deleting iPhone 7
[20:12:00]: Deleting iPhone 7 Plus
[20:12:04]: Deleting iPhone 8
[20:12:08]: Deleting iPhone 8 Plus
[20:12:11]: Deleting iPhone SE
[20:12:12]: Deleting iPhone X
[20:12:15]: Deleting iPad Air
[20:12:15]: Deleting iPad Air 2
[20:12:16]: Deleting iPad (5th generation)
[20:12:18]: Deleting iPad Pro (9.7-inch)
[20:12:22]: Deleting iPad Pro (12.9-inch)
[20:12:24]: Deleting iPad Pro (12.9-inch) (2nd generation)
[20:12:25]: Deleting iPad Pro (10.5-inch)
[20:12:28]: Deleting Apple TV
[20:12:29]: Deleting Apple TV 4K
[20:12:29]: Deleting Apple TV 4K (at 1080p)
[20:12:30]: Deleting Apple Watch - 38mm
[20:12:30]: Deleting Apple Watch - 42mm
[20:12:31]: Deleting Apple Watch Series 2 - 38mm
[20:12:31]: Deleting Apple Watch Series 2 - 42mm
[20:12:31]: Deleting Apple Watch Series 3 - 38mm
[20:12:32]: Deleting Apple Watch Series 3 - 42mm
Creating iPhone 4s for iOS version iOS 11.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162):
Incompatible device
Creating iPhone 5 for iOS version iOS 11.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162):
Incompatible device
Creating iPhone 5s for iOS version iOS 11.2
Creating iPhone 6 for iOS version iOS 11.2
Creating iPhone 6 Plus for iOS version iOS 11.2
Creating iPhone 6s for iOS version iOS 11.2
Creating iPhone 6s Plus for iOS version iOS 11.2
Creating iPhone 7 for iOS version iOS 11.2
Creating iPhone 7 Plus for iOS version iOS 11.2
Creating iPhone 8 for iOS version iOS 11.2
Creating iPhone 8 Plus for iOS version iOS 11.2
Creating iPhone SE for iOS version iOS 11.2
Creating iPhone X for iOS version iOS 11.2
Creating iPad 2 for iOS version iOS 11.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162):
Incompatible device
Creating iPad Retina for iOS version iOS 11.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=162):
Incompatible device
Creating iPad Air for iOS version iOS 11.2
Creating iPad Air 2 for iOS version iOS 11.2
Creating iPad (5th generation) for iOS version iOS 11.2
Creating iPad Pro (9.7-inch) for iOS version iOS 11.2
Creating iPad Pro (12.9-inch) for iOS version iOS 11.2
Creating iPad Pro (12.9-inch) (2nd generation) for iOS version iOS 11.2
Creating iPad Pro (10.5-inch) for iOS version iOS 11.2
Creating Apple TV for tvOS version tvOS 11.2
Creating Apple TV 4K for tvOS version tvOS 11.2
Creating Apple TV 4K (at 1080p) for tvOS version tvOS 11.2
Creating Apple Watch - 38mm for watchOS version watchOS 4.2
Creating Apple Watch - 42mm for watchOS version watchOS 4.2
Creating Apple Watch Series 2 - 38mm for watchOS version watchOS 4.2
Creating Apple Watch Series 2 - 42mm for watchOS version watchOS 4.2
Creating Apple Watch Series 3 - 38mm for watchOS version watchOS 4.2
Creating Apple Watch Series 3 - 42mm for watchOS version watchOS 4.2
Creating device pair of 7B2D2EBC-3C81-4D3A-8E14-1A02FC2086CE and FF7E8F38-CD26-47C0-AC87-250674EF8740
MacBook-Pro:ios sujan$ 
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G3025)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform('ios')

lane :environment do
  UI.message(lane_context[SharedValues::ENVIRONMENT])
  UI.message(ENV['APP_IDENTIFIER'])
  UI.message(ENV['APPLE_ID'])
  UI.message(ENV['MATCH_REPO'])
  UI.message(ENV['FASTLANE_PASSWORD'])
end

platform :ios do
  lane :all do
    create_appfile

    # test
    run_scan_init
    config_scan
    run_scan
    tests

    # create
    run_produce
    create_app

    # certificates
    config_match
    run_match
    certificates

    # build
    run_gym_init
    config_gym
    run_gym
    build

    # screenshots
    run_snapshot_init
    config_snapshot
    run_snapshot
    screenshots

    # frame
    run_frameit_download_frames
    run_frameit
    run_frameit_silver
    frame

    # download
    run_deliver_init
    # TODO reset_deliver_data
    run_deliver_download_screenshots
    # TODO reset_deliver_data
    run_deliver_download_metadata
    # TODO reset_deliver_data

    # upload
    run_deliver
    upload
    run_deliver_submit_build

    # upload testflight
    run_pilot_upload
    upload_testflight

    # manage testflight
    run_pilot_builds
    run_pilot_list
    run_pilot_add
    run_pilot_list
    run_pilot_import
    run_pilot_list
    run_pilot_find
    run_pilot_export
    run_pilot_remove
    run_pilot_list
    run_pilot_distribute

    cleanup
  end

  #######################################################

  lane :create_appfile do
    create_file('Appfile')
    write_to_file('app_identifier("' + ENV['APP_IDENTIFIER'] + '")', 'Appfile')
    write_to_file('apple_id("' + ENV['APPLE_ID'] + '")', 'Appfile')
  end

  #######################################################

  lane :run_scan_init do
    run_fastlane('scan init')
  end

  lane :config_scan do
    write_to_file('project("iosapp/iosapp.xcodeproj")', 'Scanfile')
  end

  lane :run_scan do
    run_fastlane('scan')
  end

  lane :tests do
    run_tests
  end

  #######################################################

  # Apple Developer Console + App Store Connect
  # fastlane produce
  #   fastlane ios run_produce
  # fastlane ios create_app (create_app_online)

  lane :run_produce do
    run_fastlane('produce --app_name="Fastlane iOS ManInteg"')
  end

  lane :create_app do
    create_app_online(
      app_name: "Fastlane iOS ManInteg2"
    )
  end

  #######################################################

  lane :run_match_init do
    # ??? TODO
  end

  # TODO create certificates in empty repo

  lane :config_match do
    # TODO create new git branch on repo
    write_to_file('git_url("'+ ENV['MATCH_REPO'] + '")', 'Matchfile')
  end

  lane :run_match do
    run_fastlane('match')
  end

  # TODO
  #development
  #appstore
  #adhoc

  lane :certificates do
    sync_code_signing(
      #force: true
    )
  end

  # TODO: match nuke

  #######################################################

  lane :run_gym_init do
    run_fastlane('gym init')
  end

  lane :config_gym do
    write_to_file('project("iosapp/iosapp.xcodeproj")', 'Gymfile')
  end

  # TODO: Try on Mac - on Windows this is all a dead end of course

  lane :run_gym do
    run_fastlane('gym')
  end

  # TODO
  # debug
  # release

  lane :build do
    build_ios_app
  end

  # TODO
  # debug
  # release

  #######################################################

  # TODO: Try on Mac - on Windows this is all a dead end of course

  lane :run_snapshot_init do
    run_fastlane('snapshot init')
  end

  lane :config_snapshot do
    write_to_file('???', '???')
  end

  lane :run_snapshot do
    #run_fastlane('snapshot')
  end

  lane :screenshots do
    capture_ios_screenshots
  end

  # TODO fastlane snapshot update
  # TODO fastlane snapshot reset_simulators

  #######################################################

  lane :run_frameit_download_frames do
    run_fastlane('frameit download_frames')
  end

  lane :run_frameit do
    run_fastlane('frameit')
  end

  lane :run_frameit_silver do
    run_fastlane('frameit silver')
  end

  lane :frame do
    frame_screenshots(
      path: 'pseudoscreenshots'
    )
  end

  #######################################################

  lane :run_deliver_init do
    run_fastlane('deliver init')
  end

  lane :config_deliver do
    # TODO
  end

  lane :reset_deliver_data do
    # TODO
  end

  lane :run_deliver_download_screenshots do
    run_fastlane('deliver download_screenshots')
  end

  lane :run_deliver_download_metadata do
    run_fastlane('deliver download_metadata')
  end

  lane :run_deliver do
    run_fastlane('deliver --force')
  end

  lane :upload do
    upload_to_app_store(
      force: true,
      submit_for_review: true
    )
  end

  lane :run_deliver_submit_build do
    run_fastlane('deliver submit_build')
  end

  #######################################################

  # TODO Testflight

  lane :run_pilot_upload do
    #run_fastlane('pilot upload')
  end

  lane :upload_testflight do
    #upload_to_testflight
  end

  lane :run_pilot_builds do
    #run_fastlane('pilot builds')
  end

  lane :run_pilot_list do
    #run_fastlane('pilot list')
  end

  lane :run_pilot_add do
    #run_fastlane('pilot add x')
  end

  lane :run_pilot_import do
    #run_fastlane('pilot import')
  end

  lane :run_pilot_find do
    #run_fastlane('pilot find x')
  end

  lane :run_pilot_export do
    #run_fastlane('pilot export')
  end

  lane :run_pilot_remove do
    #run_fastlane('pilot remove x')
  end

  lane :run_pilot_distribute do
    #run_fastlane('pilot distribute')
  end

  #######################################################

  lane :cleanup do
    remove_file('Appfile')
    remove_file('Deliverfile')
    remove_file('Gymfile')
    remove_file('Scanfile')
  end

  #######################################################
end

#######################################################

import("../../Fastfile_common_methods")

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("tools.fastlane.iosapp")
apple_id("piotrowski@gmail.com")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.5       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-11-18**
</details>

**Comment by iosdevben** [comment]
This error has never gone away for me, even after updating Xcode.

I have Xcode 9.2, 9.4.1, 10 and 10.1 installed.
xcode-select is set to 10.1

I recommend that `snapshot reset_simulators` uses the correct iOS version for the device it's trying to create.

So for iPhone 4s, that should be iOS 9.3. For iPhone 5 it should be iOS 10.3.

Why would it try to create the sim with an unsupported iOS version in the first place?

**Comment by janpio** [comment]
Sure, we could put something like that in there (I have never looked at that part of the codebase - no idea how it currently _really_ works). Is this definition a thing that often changes? Can it be retrieved after installing Xcode somehow (manually)?
