### ISSUE TITLE
fastlane sigh repair ignores the arguments --ignore_profiles_with_different_name true --provisioning_name

### ISSUE THREAD

**Issue by sarastro-nl** [fastlane/fastlane#13719]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Steps to reproduce:
fastlane sigh repair --ignore_profiles_with_different_name true --provisioning_name "A"

Expected result:
it will try to repair provisioning profile "A" and no other profile

Actual result:
It tries to repair all profiles available for the user/team

Background:
We have a lot of profiles that are managed by different teams in our company. We only want to repair our profiles.

**Comment by janpio** [comment]
The documentation at https://docs.fastlane.tools/actions/sigh/ and especially the list of parameters there mostly only applies to the action (`sigh` or `get_provisioning_profile` when used in a `Fastfile`) or the `fastlane sigh` command. As you are using `fastlane sigh repair`, most/all of these parameters don't apply.

Actually, `sigh repair` is even documented to:

> ... repair all your existing provisioning profiles which are expired or just invalid.

https://docs.fastlane.tools/actions/sigh/#repair

This is also mirrored in the code, which only has a `repair_all` method:
https://github.com/fastlane/fastlane/blob/391ae8457eeb252afcf6d1c809193265b68be0b0/sigh/lib/sigh/repair.rb#L7-L32
https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/sigh/lib/sigh/commands_generator.rb#L86-L97

--- 

That being said, your use case makes total sense and being able to specify a profile to repair (if you already know which one is invalid/expired) sounds like a useful feature to have. Are you up for creating a Pull Request for this?
