### ISSUE TITLE
Fastlane add device fails for the new iPhone XS

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#13722]
I have the latest version of Fastlane.

Adding the new device ID for the iPhone XS, it fails with the below error.
Passed invalid UDID: 00008050-000867C90269002E for device: Test iPhone

**Comment by janpio** [comment]
Please fill this issue template: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md It asks your for all the relevant information we need to debug this.

**Comment by janpio** [comment]
Please fill this issue template: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md It asks your for all the relevant information we need to debug this.
