### ISSUE TITLE
create_app_on_managed_play_store Google Api Error: Invalid request

### ISSUE THREAD

**Issue by 7aduta** [fastlane/fastlane#13720]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when i try to create a new app with the action create_app_on_managed_play_store i get the error 
Google Api Error: Invalid request
##### Complete output when running fastlane, including the stack trace and command used

<details>

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Volumes/any/Work/Apps in PATH, mode 040777
[✔] 🚀 
[06:15:29]: fastlane detected a Gemfile in the current directory
[06:15:29]: however it seems like you don't use `bundle exec`
[06:15:29]: to launch fastlane faster, please use
[06:15:29]: 
[06:15:29]: $ bundle exec fastlane android createapp --capture_output
[06:15:29]: 
[06:15:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-11-20 06:15:31.28]: Checking if there are any plugins that should be loaded...
DEBUG [2018-11-20 06:15:31.37]: Loading 'fastlane-plugin-android_keystore' plugin
INFO [2018-11-20 06:15:31.40]: gem 'fastlane-plugin-android_keystore' is already installed
DEBUG [2018-11-20 06:15:31.42]: Loading 'fastlane-plugin-cordova_screenshots' plugin
INFO [2018-11-20 06:15:31.42]: gem 'fastlane-plugin-cordova_screenshots' is already installed
DEBUG [2018-11-20 06:15:31.45]: Loading 'fastlane-plugin-automated_test_emulator_run' plugin
INFO [2018-11-20 06:15:31.45]: gem 'fastlane-plugin-automated_test_emulator_run' is already installed
INFO [2018-11-20 06:15:31.89]: Driving the lane 'android createapp' 🚀
INFO [2018-11-20 06:15:31.89]: ----------------------------------------------
INFO [2018-11-20 06:15:31.89]: --- Step: create_app_on_managed_play_store ---
INFO [2018-11-20 06:15:31.89]: ----------------------------------------------
DEBUG [2018-11-20 06:15:31.90]: Fetching a new access token from Google...
WARN [2018-11-20 06:15:32.71]: Lane Context:
INFO [2018-11-20 06:15:32.71]: {:PLATFORM_NAME=>:android, :LANE_NAME=>"android createapp"}
ERROR [2018-11-20 06:15:32.71]: Google Api Error: Invalid request
INFO [2018-11-20 06:15:32.71]: Successfully generated documentation at path '/Volumes/any/Work/Apps/avendam/app/fastlane/README.md'
DEBUG [2018-11-20 06:15:32.74]: All plugins are up to date
ERROR [2018-11-20 06:15:32.74]: fastlane finished with errors
DEBUG [2018-11-20 06:15:32.74]: All plugins are up to date
```
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14                                                          |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14 (18A391)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :android do
	
	lane :createapp do
		apk_path = Dir.glob(File.join(Dir.pwd, "../platforms/android/app/build/outputs/apk/release/*-release.apk")).first
		app_title = "name"
		language = 'ar'
		apk = '/Volumes/any/Work/Apps/name/app/platforms/android/app/build/outputs/apk/release/app-release.apk'
		create_app_on_managed_play_store(
		  json_key: ENV['JSON_KEY_FILE'],
		  developer_account_id: ENV['android_developer_account_id'],
		  app_title: app_title,
		  language: language,
		  apk: apk
		)
	end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/Volumes/any/Work/Apps/name/app/fastlane/release_manager.json"
package_name "com.app.name"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-android_keystore            | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-cordova_screenshots         | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-automated_test_emulator_run | 1.6.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.0.0        |
| slack-notifier                              | 2.3.2        |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| terminal-notifier                           | 1.8.0        |
| unicode-display_width                       | 1.4.0        |
| terminal-table                              | 1.8.0        |
| plist                                       | 3.4.0        |
| CFPropertyList                              | 3.0.0        |
| public_suffix                               | 2.0.5        |
| addressable                                 | 2.5.2        |
| multipart-post                              | 2.0.0        |
| word_wrap                                   | 1.0.0        |
| tty-screen                                  | 0.6.5        |
| tty-cursor                                  | 0.6.0        |
| tty-spinner                                 | 0.8.0        |
| babosa                                      | 1.0.2        |
| colored                                     | 1.2          |
| highline                                    | 1.7.10       |
| commander-fastlane                          | 4.4.6        |
| excon                                       | 0.62.0       |
| faraday                                     | 0.15.3       |
| unf_ext                                     | 0.0.7.5      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20180417 |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| fastimage                                   | 2.1.4        |
| gh_inspector                                | 1.1.3        |
| mini_magick                                 | 4.5.1        |
| multi_json                                  | 1.13.1       |
| multi_xml                                   | 0.6.0        |
| rubyzip                                     | 1.2.2        |
| security                                    | 0.1.3        |
| xcpretty-travis-formatter                   | 1.0.0        |
| dotenv                                      | 2.5.0        |
| bundler                                     | 1.16.5       |
| faraday_middleware                          | 0.12.2       |
| naturally                                   | 2.2.0        |
| simctl                                      | 1.6.5        |
| uber                                        | 0.1.0        |
| declarative                                 | 0.0.10       |
| declarative-option                          | 0.1.0        |
| representable                               | 3.0.4        |
| retriable                                   | 3.1.2        |
| mime-types-data                             | 3.2018.0812  |
| mime-types                                  | 3.2.2        |
| httpclient                                  | 2.8.3        |
| google-api-client                           | 0.23.9       |
| emoji_regex                                 | 0.1.1        |
| json                                        | 2.1.0        |
| io-console                                  | 0.4.5        |
| libxml-ruby                                 | 2.9.0        |
| atomos                                      | 0.1.3        |
| claide                                      | 1.0.2        |
| colored2                                    | 3.1.2        |
| nanaimo                                     | 0.2.6        |
| xcodeproj                                   | 1.7.0        |
| jwt                                         | 2.1.0        |
| memoist                                     | 0.16.0       |
| os                                          | 1.0.0        |
| googleauth                                  | 0.6.7        |
| signet                                      | 0.11.0       |
| psych                                       | 2.1.0.1      |
| fastlane-plugin-android_keystore            | 0.1.0        |
| fastlane-plugin-cordova_screenshots         | 0.2.0        |
| fastlane-plugin-automated_test_emulator_run | 1.6.0        |
</details>

**Comment by janpio** [comment]
Are you trying to create an app on a Managed Play Store account, not a normal one?
Can you please post the complete output, including the stack trace?

**Comment by 7aduta** [comment]
sorry for miss understood the process i was using normal google play account

**Comment by janpio** [comment]
Thanks for the feedback. With normal Google Play accounts there unfortunately doesn't exist an API we can use to create apps - you have to do that manually in the Play Console UI.
