### ISSUE TITLE
sh action does not support sleep command

### ISSUE THREAD

**Issue by ZZHHAANNGG** [fastlane/fastlane#13729]
https://docs.fastlane.tools/actions/sh/#sh

I am trying to run a shell script that has `sleep` command. However, seems `sh` is not able to sleep. Should I change `sleep` to another command or I should use another action to run?

**Comment by janpio** [comment]
What command exactly are you executing and why do you think `sleep` doesn't work? YOur issue is a bit light on information right now.

**Comment by ZZHHAANNGG** [comment]
Hi,

I put  ‘sleep 5’ between two commands. The whole script is finished less than 5 seconds. I guess ‘sleep’ command is not being execuated.

Because I run the same script file in mya computer bash, it run as I expected.

**Comment by janpio** [comment]
Can you share a simple lane to reproduce what you describe?

**Comment by ZZHHAANNGG** [comment]
When I run following script by using `sh "./test.sh"`. I expect it sleeps 5 seconds after first function  `uploadipa $1` being executed.

`
#!/bin/bash

uploadipa(){
	exec 5>&1
	echo "Uploading $1"
	result=`curl -XPOST -s -u ${USER_NAME}:${USER_TOKEN} "${SEVER_URL}/apiv1/Application?verb=add" --form upload=@$1` 
	isSuccess=`echo $result | ack -o 'true|false'`
	asyncResponseId=`echo $result | ack -o '(?<=")[\w-]+(?="\}\})'`

	if [[ $isSuccess == false ]]; then
		return 1
	elif [[ -z $asyncResponseId ]]; then
		return 2
	fi

	sleep 5

	checkResult $asyncResponseId

	if [[ $? -eq 0  ]]; then
		echo "$1 Uploaded success"
	else
		echo "$1 Upload failed"
	fi
}


getLastestAppID(){
	echo "Get lastest app ID of $version_id"

	partten="(?<=\"id\":\")[\.\s\w,\"-_=+]*(?<=version\":\"$version_id)"

	APPLICATION_ID=$(curl -u ${USER_NAME}:${USER_TOKEN} "${SEVER_URL}/apiv1/Application" | ack -o $partten | ack -o '[\w-]+(?=")' | sed -n 1p)

	echo "applicationid: $APPLICATION_ID"
}

installAppID() {
	echo "Install the lastest app $1"

	ID=$(curl -XPOST -su ${USER_NAME}:${USER_TOKEN} "${SEVER_URL}/apiv1/Application?action=install&force=true&id=$APPLICATION_ID&deviceId=${DEVICE_ID}")

	echo $ID
}

checkResult(){
	echo "check the result of $1"
	
	curl -su ${USER_NAME}:${USER_TOKEN} "${SEVER_URL}/apiv1/Async\?id\=$1" | ack -o '(?<=isSuccess":)\w{1,5}(?=,)' > /dev/null 2>&1
}

version_id=$2

echo $version_id

uploadipa $1

########################
# should sleep 5 seconds
########################

getLastestAppID $version_id

installAppID $APPLICATION_ID

checkResult $ID
`

**Comment by janpio** [comment]
Can you strip that down in a simpler shell script that any of the members here can just copy to their local machine to test this?
