### ISSUE TITLE
[WIP] Investigation of fastlane iOS/Apple password/login problems

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13723]
Currently there are lots of issues reporting problems logging in to their Apple IDs. This issue is my investigation into what is going on.

--- 

Some relevant code searches:
https://github.com/fastlane/fastlane/search?q=FASTLANE_PASSWORD
https://github.com/fastlane/fastlane/search?q=CredentialsManager%3A%3AAccountManager.new
https://github.com/fastlane/fastlane/search?q=FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
https://github.com/fastlane/fastlane/search?q=FASTLANE_SESSION

---

Where a login/password is needed:

- produce
- deliver
- pilot
- register_device
- register_devices
- cert
- sigh
- pem
- ... many more.

---

What component is executed with the credentials:

`spaceship`:
- produce
- deliver
- pilot
- register_devices
- register_device
- ... many more

`ItunesTransporter`:
- deliver: Upload binary
- pilot: Upload binary

---

An overview of the available password input mechanisms:

### Prompt: Enter password

Triggered in https://github.com/fastlane/fastlane/blob/227c468b139ff7d18b23ff855c74a44bd2d594a9/credentials_manager/lib/credentials_manager/account_manager.rb#L137

### `FASTLANE_PASSWORD`

Used in https://github.com/fastlane/fastlane/blob/master/credentials_manager/lib/credentials_manager/account_manager.rb

### `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`

Only used in https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb

### `FASTLANE_SESSION`

Used in https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/two_step_client.rb

---

"2 Factor Authentication" and "2 step authentication" seem to be two different things:
https://github.com/fastlane/fastlane/blob/227c468b139ff7d18b23ff855c74a44bd2d594a9/spaceship/lib/spaceship/two_step_client.rb#L9-L47
https://github.com/fastlane/fastlane/blob/227c468b139ff7d18b23ff855c74a44bd2d594a9/spaceship/lib/spaceship/two_step_client.rb#L49-L86

**Comment by KrauseFx** [comment]
> Currently there are lots of issues reporting problems logging in to their Apple IDs

Do you have some links by hand? If so, would be good to attach them here 👍

**Comment by janpio** [comment]
See the `topic: login` tag that I also applied to this issue: https://github.com/fastlane/fastlane/labels/topic%3A%20login
