### ISSUE TITLE
how to use deliver commandline option --submission_information?

### ISSUE THREAD

**Issue by sesangsokuro** [fastlane/fastlane#13730]
Wherever I look, fastlane does not mention the value of this option file or string.

If the parameter is a string, I'm wondering how to pass a long string similar to json to a command line parameter, but all instructions only guide you through the use of a configuration file such as fastfile

Why is that?

This is clearly an entry in the command line options that comes with fastlane deiliver --help.

How can I set that option without config file such as fastfile?

The tables in the fastlane document only contain additional data and are not even instantiated.

**Comment by janpio** [comment]
The documentation on the `submission_information` option/param indeed seems to be a bit light - but it is "only" hidden in a non optimal way: Go to https://docs.fastlane.tools/actions/deliver/#more-options, open the "View all available options and their valid values" details, then use https://docs.fastlane.tools/actions/deliver/#submission_information to go to the correct headline.

This shows how the data can be supplied in a different way:
Besides directly supplying the param and its value to the command line (or calling the `deliver`/`upload_to_app_store` action in a `Fastfile`), you can also set it in the `Deliverfile` which will be read by `deliver` on command execution.

There is also a link to the underlying code, that shows all the different possible values.

> How can I set that option without config file such as fastfile?

I don't know if and how this can be supplied in the command line as a param directly.

> The tables in the fastlane document only contain additional data and are not even instantiated.

What does that mean?
