### ISSUE TITLE
Extend get_info_plist_value functionality or change get_build_number to read Info.plist instead of agvtool

### ISSUE THREAD

**Issue by Skoti** [fastlane/fastlane#13735]
#### Motivation Behind Feature
`get_version_number` is using `Xcodeproj::Plist.read_from_path` to obtain _CFBundleShortVersionString_ from a plist file which is great and usable for everyone.

However, for some reason `get_build_number` is using _agvtool_ which requires your project to be first configured appropriately so that _agvtool_ could work correctly.
While it makes sense to require _agvtool_ in increment actions (both version and build) it does not for just a read action.
`get_build_number` should just obtain a value from a plist file (_CFBundleVersion_) like `get_version_number` does which makes it usable for everyone.
Additionally, you get more flexibility by specifying optional target and configuration options (see [get_version_number docs](https://docs.fastlane.tools/actions/get_version_number/)).

#### Feature Description
So there are two possible ways of implementing this:
1. Change the implementation of `get_build_number` to read from a plist file instead of using _agvtool_.
One drawback of doing this is that it will have a different set of _available_options_ thus making it a non-backward compatible change.
Nevertheless, I think the advantages are compensating this - it is usable by everyone and there is a greater flexibility by specifying optional target and configuration options.
2. Extend `get_info_plist_value` to support target and configuration options and implement both `get_version_number` and `get_build_number` as convenient calls to `get_info_plist_value` with hardcoded values (_CFBundleShortVersionString_, _CFBundleVersion_) in _key_ parameter.
**Impact**: no change for current usage of `get_version_number`.
`get_info_plist_value` will no longer support plist parameter due to new xcodeproj, target and configuration options (or we could actually try to support both ways of selecting a plist).
Big advantage of get_info_plist_value being the most configurable action to read any value from a plist file.
Same drawbacks and advantages as above for `get_build_number`.

#### Alternatives or Workarounds
You can actually achieve the same thing by:
`get_info_plist_value(path: "./Info.plist", key: "CFBundleVersion")`
However, I like the idea used in `get_version_number` of no need for a plist path parameter or any other parameter in the simplest case scenario.
Plus there is no support for target/configuration options.

**Comment by janpio** [comment]
Does https://github.com/SiarheiFedartsou/fastlane-plugin-versioning have what you are looking for?

**Comment by Skoti** [comment]
It looks great.
However, is there any possibility to require that plugin from within a fastfile?

**Comment by Skoti** [comment]
Excuse me, I should have been more specific.

The case is I am using _a shared fastfile_ which is imported in multiple projects via `import_from_git` action and I would rather keep all dependencies defined there or loaded from a _Pluginfile_ like custom actions are loaded from a separate file.
It should be a fully configured, standalone shared fastfile. So I do not have to ponder what else is required to use it.

Otherwise updating a shared fastfile with usage of a plugin requires an update in a _Gemfile_ in each project that uses it. This is a bit inconvenient and not a safe way of introducing changes.

That is why I have asked about whether it is possible to require a plugin inside of a _fastfile_.
I was expecting something similar to `fastlane_require` like: `fastlane_require_plugin`.
Or make `import_from_git` to support _Pluginfile_ as mentioned here: #11200

**Comment by janpio** [comment]
Oh got it.

No idea unfortunately. Best open a new issue with just that question.
