### ISSUE TITLE
[resign.sh] Resign fails to generate valid entitlements

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#13740]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We want to use the resign tool to resign customized versions of our app for our clients. We provide `resign` an unsigned ipa that has been prepared for resign in the following way:
1. We customize the `Info.plist's` `CFBundleIdentifier`, and `AppIdentifierPrefix`, and `CFBundleVersion`, and `CFBundleDisplayName`.
1. We modify the `App.entitlements` file in the following way:
    1. `aps-environment` is removed _if_ Push is to be turned off.
    1. `com.apple.developer.icloud-container-identifiers`, `com.apple.developer.ubiquity-container-identifiers`, `com.apple.developer.icloud-services` are removed _if_ iCloud is to be turned off.
    1. We replace the app's bundle IDs that are values for the above keys with the client's bundle ID (if those entries still remain in the entitlements file after no. 1 and no. 2).
1. We then call the `resign` action with the client's bundle ID.

The problem is that the resigned app is rejected by Apple for the following reasons:
1. `value 'Development' for key 'com.apple.developer.icloud-container-environment' in 'Payload/App.app/App' is not supported."`
1. `key 'com.apple.developer.icloud-container-development-container-identifiers' in 'Payload/App.app/App' is not supported."`
1. `value '*' for key 'com.apple.developer.icloud-services' in 'Payload/App.app/App' is not supported.`
1. `the key 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/App.app/App' is not supported.`

Our app does not have these entries in the app binary, and has been successfully uploaded to the App Store.

Analyzing the `resign.sh` script, the code path goes through the [default conditional](https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L798) to embed the entitlements from the provisioning profile into the application binary. The problem with that seems to be that the provisioning profile's entitlements are a "template" for what could be, not what "is" in the current app. For example:

```xml
<key>Entitlements</key>
<dict>
    <key>keychain-access-groups</key>
    <array>
        <string>ABCDEFGHIJ.*</string>		
    </array>
    <key>get-task-allow</key>
    <false/>
    <key>application-identifier</key>
    <string>ABCDEFGHIJ.com.atomicboyapp.missionone</string>
    <key>com.apple.developer.ubiquity-kvstore-identifier</key>
    <string>ABCDEFGHIJ.*</string>
    <key>com.apple.developer.icloud-services</key>
    <string>*</string>
    <key>com.apple.developer.icloud-container-environment</key>
    <array>
        <string>Development</string>
        <string>Production</string>
    </array>
    <key>com.apple.developer.icloud-container-identifiers</key>
    <array>
        <string>iCloud.com.atomicboyapp.missionone</string>
    </array>
    <key>com.apple.developer.icloud-container-development-container-identifiers</key>
    <array>
        <string>iCloud.com.atomicboyapp.missionone</string>
    </array>
    <key>com.apple.developer.ubiquity-container-identifiers</key>
    <array>
        <string>iCloud.com.atomicboyapp.missionone</string>
    </array>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>group.com.atomicboyapp.missionone</string>
    </array>
    <key>com.apple.developer.team-identifier</key>
    <string>ABCDEFGHIJ</string>
    <key>aps-environment</key>
    <string>production</string>
    <key>beta-reports-active</key>
    <true/>
</dict>
```

It seems that the [`$USE_APP_ENTITLEMENTS` conditional](https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L592) for merging App entitlements and provisioning profile entitlements does remove _blacklisted_ keys, and selects the correct `icloud-container-environment` based on the type of certificate, and does some "mapping" of entitlements that I don't understand yet. In order to properly resign, would that conditional need to be refactored to methods that "default conditional" code block calls can use?

As a note, I tried using the "`$USE_APP_ENTITLEMENTS` conditional" to merge the entitlements that are embedded into the app binary with the entitlements in the provisioning profile, but it does not update the bundle IDs found in the app binary and thus the old and new bundle IDs end up in the entitlements. A signed app with mixed bundle IDs in the embedded entitlements will be rejected by Apple for upload to the App Store. Should it not update the bundle IDs to be those that are in the provisioning profile?

#### Some notes:

The source of this code, `buck` changed how entitlements are merged. They switched from using a blacklist to a white list in [this commit](https://github.com/facebook/buck/commit/86fec7f7b315d859452fd7668f34b5ad5aa89073#diff-7f1b6288eae99689b57e17abe45f7ab5).

#### Summary of Questions
1. Should the "default conditional" of the entitlements block embed the Entitlements from the provisioning directly into the app binary? Or should it modify them as the `$USE_APP_ENTITLEMENTS` block of code does?
1. Should the `$USE_APP_ENTITLEMENTS` block of code update the bundle IDs to all be the same as what was given in the provisioning profile?

**Comment by Nomeqc** [comment]
+1
