### ISSUE TITLE
`carthage build` command

### ISSUE THREAD

**Issue by uny** [fastlane/fastlane#1375]
Our project commits `Carthage/Checkouts` [to guarantee that the source checkouts of each dependency will always be accessible at a later date](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#carthagecheckouts).
Then, we would like to `carthage build` to use `Carthage/Checkouts` sources.

**Comment by vpolouchkine** [comment]
Closing in favor or https://github.com/fastlane/fastlane/pull/1394
