### ISSUE TITLE
Failed *fastlane beta* command

### ISSUE THREAD

**Issue by Paras-Chodavadiya** [fastlane/fastlane#13758]
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.  macos
<img width="1680" alt="screenshot 2018-11-23 at 6 09 29 pm" src="https://user-images.githubusercontent.com/589514/48944090-67ed7100-ef4b-11e8-8458-c66c1fee50ba.png">

**Comment by janpio** [comment]
Can you build this app outside of fastlane?
What your screenshot shows is unfortunately not enough to understand and debug your problem. Please look at the issue template for bugs, we ask for very specific data for that reason.
