### ISSUE TITLE
Buid app for App Store with gym + match

### ISSUE THREAD

**Issue by quver** [fastlane/fastlane#13759]
### Question Checklist

-  :white_check_mark: Updated fastlane to the latest version
-  :white_check_mark: I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
-  :white_check_mark: I read [docs.fastlane.tools](https://docs.fastlane.tools)
-  :white_check_mark: I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Problem
I'm trying to build an app for App Store with gym + match

**Error**
```
❌  error: "SomeTodayWidget" requires a provisioning profile with the App Groups feature. Select a provisioning profile for the "Release" build configuration in the project editor. (in target 'SomeTodayWidget')
❌  error: "SomeApp" requires a provisioning profile with the App Groups and Push Notifications features. Select a provisioning profile for the "Release" build configuration in the project editor. (in target 'SomeApp')
```

**Fastfile**
```
lane :publish_release do
    sync_code_signing
    disable_automatic_code_signing(path: SOME_XCODEPROJ)

    some_build_app(
      export_method: 'app-store',
      configuration: 'Release'
    )

    enable_automatic_code_signing(path: SOME_XCODEPROJ)
end

private_lane :some_build_app do |options|
  gym(
    workspace: SOME_WORKSPACE,
    clean: true,
    scheme: SOME_SCHEME_DEFAULT,
    output_directory: SOME_ARTIFACS_PATH,
    output_name: 'SOME_' + lane_context[SharedValues::VERSION_NUMBER].to_s.downcase.tr('.','_') + '_build_' + lane_context[SharedValues::BUILD_NUMBER] + '.ipa',
    include_symbols: true,
    export_method: options[:export_method],
    buildlog_path: SOME_REPORTS_PATH,
    configuration: options[:configuration]
  )
end
```

**Matchfile**
```
git_url "somerepo/codesign.git"

type "appstore"
app_identifier ["com.somecompany.someapp", "com.somecompany.someapp.sometodaywidget"]

username "someuser@somecompany.com"
team_id "SOME1234"

keychain_name "login"
keychain_password "SomePassword"
```

Match commands used
```
match init 
match appstore 
```

Thank you in advance for your help

**Comment by janpio** [comment]
Can you please share more of your output? https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md shows what information is usually necessary to debug a problem successfully.

**Comment by quver** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                 |
| --------------------------- | --------------------------------------------------------------------- |
| OS                          | 10.14.1                                                               |
| Ruby                        | 2.4.0                                                                 |
| Bundler?                    | true                                                                  |
| Git                         | git version 2.17.2 (Apple Git-113)                                    |
| Installation Source         | ~/---/---/vendor/bundle/ruby/2.4.0/bin/fastlane                       |
| Host                        | Mac OS X 10.14.1 (18B75)                                              |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                                          |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                                           |
| Is contained                | false                                                                 |
| Is homebrew                 | false                                                                 |
| Is installed via Fabric.app | false                                                                 |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                           |
| Xcode Version               | 10.1                                                                  |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date       |
| fastlane-plugin-trainer    | 0.4.0   | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| bundler                    | 1.17.1       |
| io-console                 | 0.4.6        |
| CFPropertyList             | 2.3.6        |
| concurrent-ruby            | 1.1.2        |
| i18n                       | 0.9.5        |
| minitest                   | 5.11.3       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.5        |
| activesupport              | 4.2.10       |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| atomos                     | 0.1.3        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| clamp                      | 0.6.5        |
| fuzzy_match                | 2.0.4        |
| nap                        | 1.1.0        |
| cocoapods-core             | 1.5.3        |
| cocoapods-deintegrate      | 1.0.2        |
| cocoapods-downloader       | 1.2.2        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| netrc                      | 0.11.0       |
| cocoapods-trunk            | 1.3.1        |
| cocoapods-try              | 1.1.0        |
| colored2                   | 3.1.2        |
| escape                     | 0.0.4        |
| fourflusher                | 2.0.1        |
| gh_inspector               | 1.1.3        |
| molinillo                  | 0.6.6        |
| ruby-macho                 | 1.3.1        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.7.0        |
| cocoapods                  | 1.5.3        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| unf_ext                    | 0.0.7.5      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| dotenv                     | 2.5.0        |
| emoji_regex                | 0.1.1        |
| excon                      | 0.62.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.15.3       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.12.2       |
| fastimage                  | 2.1.4        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| multi_json                 | 1.13.1       |
| os                         | 1.0.0        |
| signet                     | 0.11.0       |
| googleauth                 | 0.6.7        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2018.0812  |
| mime-types                 | 3.2.2        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.23.9       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.4.0        |
| rubyzip                    | 1.2.2        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.5        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.4.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.6.5        |
| tty-cursor                 | 0.6.0        |
| tty-spinner                | 0.8.0        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| trainer                    | 0.8.1        |
| fastlane-plugin-trainer    | 0.4.0        |
| fastlane-plugin-versioning | 0.3.4        |
| thor                       | 0.20.0       |
| fus                        | 0.0.3        |
| mini_portile2              | 2.3.0        |
| nokogiri                   | 1.8.5        |
| slather                    | 2.4.6        |
| xcov                       | 1.5.0        |
</details>


*generated on:* **2018-11-26**
</details>

**Comment by quver** [comment]
@janpio I'm asking for help with my configuration. I know that I did something wrong...
I need someone who know how to use match correctly with multi-target applications

**Comment by janpio** [comment]
And I am asking you for more of your output, so I can understand what is going on. The bug report template asks all the right questions to have an optimal starting point.
