### ISSUE TITLE
[iOS] [Match] Xcode couldn't find any provisioning profiles matching

### ISSUE THREAD

**Issue by Banck** [fastlane/fastlane#13760]
Hello!
I have a project with 2 targets and use cocoapods (if it matters).
I've enabled "match" and my fastlane file looks like:
```
lane :beta do
    match(type: "appstore")
    build_app(workspace: "myProject.xcworkspace", scheme: "myScheme")
    upload_to_testflight
  end
```

Matchfile:
```
git_url("url/certificates.git")

type("appstore") # The default type, can be: appstore, adhoc, enterprise or development
type("development")
app_identifier(["com.myBundle", "com.myBundle.devv"])
username("myEmail") # Your Apple Developer Portal username
```
When I run "sudo fastlane beta" all certificates and profiles are downloading fine and I can see in the log:
`All required keys, certificates and provisioning profiles are installed 🙌`
But then I see:
`error: No profile for team '385638K9**' matching 'match AppStore com.myApp' found: Xcode couldn't find any provisioning profiles matching '385638K9**/match AppStore com.myApp'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'MyTarget')`
![image](https://user-images.githubusercontent.com/6259254/48975874-91261280-f0ad-11e8-8d9a-45c10c2f65fa.png)

I can build/run/archive project directly from xcode without any errors.
What can be wrong?

**Comment by Banck** [comment]
fastlane env log:
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.2                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.2 (18C48a)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(workspace: "myProject.xcworkspace", scheme: "myScheme")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.myBundle") # The bundle identifier of your app
apple_id("myEmail") # Your Apple email address

itc_team_id("team_id") # App Store Connect Team ID
team_id("385638K9**") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.3       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| fastimage                 | 2.1.4        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| os                        | 1.0.0        |
| psych                     | 2.1.0.1      |
</details>


*generated on:* **2018-11-25**
</details>

**Comment by Banck** [comment]
Hm, very strange. With `sudo fastlane beta` i'm getting this error, but when I tried without sudo:` fastlane beta` build_app(**) is working fine. 
@janpio  do you know the reason?

**Comment by Banck** [comment]
@janpio  Hello! Thanks for your reply.
I was using sudo, because there is an error on the `match(type: "appstore")` line if don't write sudo:
`Permission denied @ rb_sysopen - /Users/egorsakhabaev/Library/MobileDevice/Provisioning Profiles/107e5ac3-6d50-48cd-ac0b-********.mobileprovision`
I've changed permissions for Provisioning Profiles folder and now I can run without sudo.

Now all is fine and all is working as expected. Thanks)

**Comment by ggirotto** [comment]
@Banck Have you had any issue like the process freezing when not using `sudo` ? I'm having a similar problem, but in my case the terminal doesn't output any kind of permission denied
