### ISSUE TITLE
How to escape FASTLANE_SESSION in Travis CI

### ISSUE THREAD

**Issue by HerrNiklasRaab** [fastlane/fastlane#13763]
At the moment, want to upload the build of my ios app to Testflight. For this i must provide a FASTLANE_SESSION to log in. For this, i created a new Apple Id in the region of were Travis CI is executed. Next step was to generate the session with spaceauth and i added it as an environment variable in the Travis CI System. The variable is picked up by fastlanes upload to playstore method. But failed with this error:

> did not find expected '-' indicator while parsing a block collection at line 2 column 1

Stacktrace:

```
 /Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/psych.rb:377:in `parse': [!] (<unknown): did not find expected '-' indicator while parsing a block collection at line 2 column 1 (Psych::SyntaxError)
 	from /Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
 	from /Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/psych.rb:325:in `parse'
 	from /Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/psych.rb:252:in `load'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/two_step_client.rb:107:in `load_session_from_env'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:411:in `send_shared_login_request'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/tunes/tunes_client.rb:124:in `send_login_request'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:667:in `do_login'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:363:in `login'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:71:in `login'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/pilot/lib/pilot/manager.rb:23:in `login'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/pilot/lib/pilot/manager.rb:16:in `start'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/pilot/lib/pilot/build_manager.rb:13:in `upload'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
 	from Fastfile:47:in `block (2 levels) in parsing_binding'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `load'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `<main'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
 	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main'
```

This error makes totally sense, because the environment variable must escape special characters. Which leads me to my question. How to escape folloing session for example (this is a expired session)?:

```
---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value:  DAWTKNV21233e11635995ddacc6c7befa184b50c3eaaa62d7475af4c010b4963c1f220785d2044965eb17332883f013536edc8729a299cb83e8fcd7ec0b470bbfc5b6c62fd97a76544d61260425ab750e5a0685b0870f2b1d9037ebec7c1e7db586982658590344db98a6c39d3362b2db7381a28a7dc5e4425b856a3eb92c5dbe0a83eaab4ec3ce555cdc072222f868721f3819bd85928444e17d70e61382bafcad4c25b71cb5f0f17179a290f9a30c29ad658f1e8bd4d42a54320f1c6607f985eb58785ecac4029bec195d228fc62225adbb19625e0d654afc62059a29ad9396cc8753ae0bca5eecf0765e2f112ea2370c541bcdd7ba3cf0fa7375962d781a5c303f8c8e537c3b584aa3e54fe8716de13f2a1340dac945c5b71bba90b0d2a0e039bb9661c656398534c2ac9fbfd335c60b982cb62313365343530363231363339313337653532313537383163396638356337376234316534386435MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2018-11-25 21:45:35.522826000 +01:00\n  accessed_at: 2018-11-25 21:45:35.533236000 +01:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJsaGxBZm9vTHdvODFNYTFJRzNMM2RRIn0.BgcaZ-rGBGajT8FnGrtGUCWygNx9rq4ng1rgWb7HqQY\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-11-25 21:45:36.362833000 +01:00\n  accessed_at: *1
```

I would be so gratefull, if someone could help me with this, because this would be my last step in setting fastlane up correctly.

PS: I am using Two Factor Verification, thats why i need this.

**Comment by janpio** [comment]
Usually this is all taken care of by `spaceship`, see the function:
https://github.com/fastlane/fastlane/blob/5c79a1691bcac895ee07456ca2ead581dd311a97/spaceship/lib/spaceship/two_step_client.rb#L98-L115

How exactly did you the the env var?

**Comment by HerrNiklasRaab** [comment]
Following i tried (difference are the qotes at the start and beginning):

**'** ---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value:  DAWTKNV21233e11635995ddacc6c7befa184b50c3eaaa62d7475af4c010b4963c1f220785d2044965eb17332883f013536edc8729a299cb83e8fcd7ec0b470bbfc5b6c62fd97a76544d61260425ab750e5a0685b0870f2b1d9037ebec7c1e7db586982658590344db98a6c39d3362b2db7381a28a7dc5e4425b856a3eb92c5dbe0a83eaab4ec3ce555cdc072222f868721f3819bd85928444e17d70e61382bafcad4c25b71cb5f0f17179a290f9a30c29ad658f1e8bd4d42a54320f1c6607f985eb58785ecac4029bec195d228fc62225adbb19625e0d654afc62059a29ad9396cc8753ae0bca5eecf0765e2f112ea2370c541bcdd7ba3cf0fa7375962d781a5c303f8c8e537c3b584aa3e54fe8716de13f2a1340dac945c5b71bba90b0d2a0e039bb9661c656398534c2ac9fbfd335c60b982cb62313365343530363231363339313337653532313537383163396638356337376234316534386435MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2018-11-25 21:45:35.522826000 +01:00\n  accessed_at: 2018-11-25 21:45:35.533236000 +01:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJsaGxBZm9vTHdvODFNYTFJRzNMM2RRIn0.BgcaZ-rGBGajT8FnGrtGUCWygNx9rq4ng1rgWb7HqQY\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-11-25 21:45:36.362833000 +01:00\n  accessed_at: *1 **'**

**"**---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value:  DAWTKNV21233e11635995ddacc6c7befa184b50c3eaaa62d7475af4c010b4963c1f220785d2044965eb17332883f013536edc8729a299cb83e8fcd7ec0b470bbfc5b6c62fd97a76544d61260425ab750e5a0685b0870f2b1d9037ebec7c1e7db586982658590344db98a6c39d3362b2db7381a28a7dc5e4425b856a3eb92c5dbe0a83eaab4ec3ce555cdc072222f868721f3819bd85928444e17d70e61382bafcad4c25b71cb5f0f17179a290f9a30c29ad658f1e8bd4d42a54320f1c6607f985eb58785ecac4029bec195d228fc62225adbb19625e0d654afc62059a29ad9396cc8753ae0bca5eecf0765e2f112ea2370c541bcdd7ba3cf0fa7375962d781a5c303f8c8e537c3b584aa3e54fe8716de13f2a1340dac945c5b71bba90b0d2a0e039bb9661c656398534c2ac9fbfd335c60b982cb62313365343530363231363339313337653532313537383163396638356337376234316534386435MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2018-11-25 21:45:35.522826000 +01:00\n  accessed_at: 2018-11-25 21:45:35.533236000 +01:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJsaGxBZm9vTHdvODFNYTFJRzNMM2RRIn0.BgcaZ-rGBGajT8FnGrtGUCWygNx9rq4ng1rgWb7HqQY\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-11-25 21:45:36.362833000 +01:00\n  accessed_at: *1 **"**

---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value:  DAWTKNV21233e11635995ddacc6c7befa184b50c3eaaa62d7475af4c010b4963c1f220785d2044965eb17332883f013536edc8729a299cb83e8fcd7ec0b470bbfc5b6c62fd97a76544d61260425ab750e5a0685b0870f2b1d9037ebec7c1e7db586982658590344db98a6c39d3362b2db7381a28a7dc5e4425b856a3eb92c5dbe0a83eaab4ec3ce555cdc072222f868721f3819bd85928444e17d70e61382bafcad4c25b71cb5f0f17179a290f9a30c29ad658f1e8bd4d42a54320f1c6607f985eb58785ecac4029bec195d228fc62225adbb19625e0d654afc62059a29ad9396cc8753ae0bca5eecf0765e2f112ea2370c541bcdd7ba3cf0fa7375962d781a5c303f8c8e537c3b584aa3e54fe8716de13f2a1340dac945c5b71bba90b0d2a0e039bb9661c656398534c2ac9fbfd335c60b982cb62313365343530363231363339313337653532313537383163396638356337376234316534386435MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2018-11-25 21:45:35.522826000 +01:00\n  accessed_at: 2018-11-25 21:45:35.533236000 +01:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJsaGxBZm9vTHdvODFNYTFJRzNMM2RRIn0.BgcaZ-rGBGajT8FnGrtGUCWygNx9rq4ng1rgWb7HqQY\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-11-25 21:45:36.362833000 +01:00\n  accessed_at: *1

Also i tried to set the Environment variable in the script, for this i created a script, **set_fastlane_session.sh**, with following content:

export FASTLANE_SESSION=**'**---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value:  DAWTKNV21233e11635995ddacc6c7befa184b50c3eaaa62d7475af4c010b4963c1f220785d2044965eb17332883f013536edc8729a299cb83e8fcd7ec0b470bbfc5b6c62fd97a76544d61260425ab750e5a0685b0870f2b1d9037ebec7c1e7db586982658590344db98a6c39d3362b2db7381a28a7dc5e4425b856a3eb92c5dbe0a83eaab4ec3ce555cdc072222f868721f3819bd85928444e17d70e61382bafcad4c25b71cb5f0f17179a290f9a30c29ad658f1e8bd4d42a54320f1c6607f985eb58785ecac4029bec195d228fc62225adbb19625e0d654afc62059a29ad9396cc8753ae0bca5eecf0765e2f112ea2370c541bcdd7ba3cf0fa7375962d781a5c303f8c8e537c3b584aa3e54fe8716de13f2a1340dac945c5b71bba90b0d2a0e039bb9661c656398534c2ac9fbfd335c60b982cb62313365343530363231363339313337653532313537383163396638356337376234316534386435MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2018-11-25 21:45:35.522826000 +01:00\n  accessed_at: 2018-11-25 21:45:35.533236000 +01:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJsaGxBZm9vTHdvODFNYTFJRzNMM2RRIn0.BgcaZ-rGBGajT8FnGrtGUCWygNx9rq4ng1rgWb7HqQY\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-11-25 21:45:36.362833000 +01:00\n  accessed_at: *1**'**

The script is called in travis.yml:

**- source ci/set_fastlane_session.sh**

**Comment by janpio** [comment]
You definitely have to use `'` to set the value, as `"` is included in the string.

How do you set the env var if not using a script?

**Comment by HerrNiklasRaab** [comment]
In Travis you can define environment variables in the settings. (In the GUI)

Jan Piotrowski <notifications@github.com> schrieb am Mo. 26. Nov. 2018 um
17:15:

**Comment by dale-french** [comment]
I am having the same issue setting the env var on Bitrise

**Comment by HerrNiklasRaab** [comment]
Hello @dale-french ,

i didn't get it working, but you can use the fastlane altool plugin: https://github.com/XCTEQ/fastlane-plugin-altool

This works for uploading to testflight, without session. You have to provide an application specific password to instead of your appstoreconnect user password, to get it work.

Hopefully it helps!

**Comment by HerrNiklasRaab** [comment]
Accidently closed

**Comment by janpio** [comment]
For Travis I could get it to accept the var by copying the first of the two outputs (make sure it is just one long line, sometimes it copies it with line breaks) and wrapping it in `'`. Then Travis accepted it and loaded it on start of the build and it could be used.
