### ISSUE TITLE
Pilot upload fails with Server error got 500. build.processed? returns true even though the build is still being processed on App Store Connect

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#13776]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am using `fastlane pilot upload --verbose` to upload several different apps. I have noticed for apps that are larger in size after a couple of waiting for App Store Connect to finish processing the new build:
```
INFO [2018-11-28 08:46:27.04]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:46:57.98]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:47:29.25]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:48:00.05]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:48:30.92]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:49:01.86]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:49:33.29]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:50:04.51]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:50:34.96]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
INFO [2018-11-28 08:51:05.47]: Waiting for App Store Connect to finish processing the new build (1.3.0 - 1.3.0)
```
I get a `Server error 500` `[31m[!] The request could not be completed because: (Spaceship::InternalServerError)`. 

As stated earlier this happens for larger binaries, the apps with smaller binaries do not have any issues. Hence I do not think it is related to setting <key>ITSAppUsesNonExemptEncryption</key><false/> in the info.plist file. As both larger and smaller binaries do not have this key set. 

I have tried to investigate further using Spaceship and have noticed that `build.processed?` returns `true` and `build.processing?` returns `false` even though on App Store Connect I see that the build is still being processed:
![image](https://user-images.githubusercontent.com/23205547/49185789-b1590a00-f317-11e8-97a1-81446ef321bb.png)

Are there other attributes that I should look at? Why is the state inconsistent? 

##### Complete output when running fastlane, including the stack trace and command used

<details>
</details>

### Environment

<details>
  <pre>
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.3       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.10.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.4        |
| unicode-display_width     | 1.4.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| os                        | 1.0.0        |
| psych                     | 2.0.17       |
</details>
</pre>
</details>

**Comment by kkw4** [comment]
We seem to be noticing the same issue in our fastlane uploads as well

**Comment by anushkmittal** [comment]
bump same

**Comment by techopsway2b1** [comment]
Same thing is happening here too.  Building manually using xcodebuild from CLI with altool manually works fine... Looks like fastlane is timing out due to build processing taking so long in App Store Connect.

When the dust finally settled I had the "Missing Compliance" Warning in the App Store Connect.

To fix that you need to add

<key>ITSAppUsesNonExemptEncryption</key>
<false/>

to your Info.plist.

Im not sure if this is what solved it, but when I added that and reran the build it uploaded fine.  I will need to remove it and test it again to see if it gives the same time out error.  I will test it tomorrow and post back my findings.  Good Luck!

**Comment by kevinm90** [comment]
I can confirm the same, this kind of screws up our CD-Pipelines now. Setting the key does not really help, sometimes yes, sometimes not. Any other hints here?
Is it an issue on Apples side, so would raising an issue from multiple developers maybe help?

**Comment by janpio** [comment]
Spaceship logs to `/tmp/spaceship`. Anything useful or interesting in there? I rewrote a good part of that logging recently, but it hasn't been released yet - so this will only get improved with the next release.

**Comment by techopsway2b1** [comment]
@kevinm90 - If you are seeing this sporadically and you have the compliance flag set to false, can you confirm which upload tool you are using?  Im using the default Fastlane one, iMSTransporter.  I have my own CLI tool that uses altool and I have never encountered this problem.  So if you are have the flag set to false and are using iMSTransporter then my gut says its the iMSTransporter component thats timing out or Fastlane's logic that wraps that process.  Can anyone from Fastlane comment on this?

**Comment by tguidon** [comment]
Seeing this same issue when running my builds through Bitrise. Have about 10 apps that need to process and keep manually rebuilding until they go through.

**Comment by janpio** [comment]
That unfortunately indicates a problem on Apple's side - this usually is returned when they have server problems.

**Comment by tguidon** [comment]
Yeah it looks like the web interface is also throwing that same error. Seems like we gotta wait it out.

**Comment by pparmaei** [comment]
@tguidon yes, seeing the same issue as you now. This seems to be a (hopefully) temporary issue on Apple's side.

But the original issue raised here should not be related to Apple's server. It seems to me that the core issue is that spaceship `build.processed?` returns `true` even though the build is actually not processed.

**Comment by pparmaei** [comment]
> @kevinm90 - If you are seeing this sporadically and you have the compliance flag set to false, can you confirm which upload tool you are using? Im using the default Fastlane one, iMSTransporter. I have my own CLI tool that uses altool and I have never encountered this problem. So if you are have the flag set to false and are using iMSTransporter then my gut says its the iMSTransporter component thats timing out or Fastlane's logic that wraps that process. Can anyone from Fastlane comment on this?

As I said in the original issue. It does not seem to be related to setting `ITSAppUsesNonExemptEncryption` to `false`. As for our apps that have a smaller size binary, we do not see the issue but we see it for other apps that have larger binaries. 

Basically, you are more likely to see this issue if your app takes longer to process on App Store Connect.

**Comment by techopsway2b1** [comment]
@pparmaei - Based on your statement then, its the code that wraps the transporter not waiting long enough for the processing to finish or its the transporter itself timing out.  Either way this a real problem that Fastlane needs to solve as I can not have my pipeline falling over because of a timeout with the upload.   Has anyone used the altool plugin that Jagtap talks about in this article?

https://dzone.com/articles/new-fastlane-plugin-to-upload-ios-binary-with-alto

My only thought here is that altool simply sends the upload and once its finished it states its completed.  In the App Store Connect dashboard its still processing...  Not sure which is better here, but for me the altool route doesn't break my pipeline or provide a false positive because the Fastlane jobs exits with a failure, but the upload has finished and will still be available in the appstore once the processing has finished.

**Comment by pparmaei** [comment]
@techopsway2b1 thanks for providing the link to altool. 

However, for our use case, we need the pipeline to be end-to-end. So it is important to know when the build has finished processing so that we can actually submit the app for TestFlight review. We use Spaceship commands in order to that. With `fastlane pilot upload` if you pass the `skip_waiting_for_build_processing` flag then there will be no issues either.

The issue is specifically with waiting for processing. I think it is related to **build.processed?** returning a false positive.  Hopefully, someone from Fastlane can comment soon.

**Comment by janpio** [comment]
> I have tried to investigate further using Spaceship and have noticed that `build.processed?` returns `true` and `build.processing?` returns `false` even though on App Store Connect I see that the build is still being processed:
> ![image](https://user-images.githubusercontent.com/23205547/49185789-b1590a00-f317-11e8-97a1-81446ef321bb.png)
> 
> Are there other attributes that I should look at? Why is the state inconsistent?

Can you elaborate on that please, what exactly are you doing to get these values (spaceship code) and what exactly did you do to get the app in this state - just upload a big binary?

**Comment by techopsway2b1** [comment]
@janpio - This process is generating the .ipa file that is signed and uploading to App Store Connect.

**Comment by janpio** [comment]
I don't follow @techopsway2b1. What is this responding to or explaining?

**Comment by Skoti** [comment]
@janpio
@techopsway2b1 is explaining the last question you asked to @pparmaei.
To get a build in a processing state it is enough to upload it.
After uploading a binary to AppStoreConnect it always needs to be processed first before it is available for other actions.

@pparmaei 
> Are there other attributes that I should look at? Why is the state inconsistent?

Could you please check `processing_state` parameter of such a build?

According to this:
https://github.com/fastlane/fastlane/blob/1af33c0884e783867bdc07a324280ec6bef124ad/spaceship/lib/spaceship/tunes/build_train.rb#L95-L104
It can be set to _processing_, maybe this one is more correct?

**Comment by pparmaei** [comment]
> @pparmaei
> 
> > I have tried to investigate further using Spaceship and have noticed that `build.processed?` returns `true` and `build.processing?` returns `false` even though on App Store Connect I see that the build is still being processed:
> > ![image](https://user-images.githubusercontent.com/23205547/49185789-b1590a00-f317-11e8-97a1-81446ef321bb.png)
> > Are there other attributes that I should look at? Why is the state inconsistent?
> 
> Can you elaborate on that please, what exactly are you doing to get these values (spaceship code) and what exactly did you do to get the app in this state - just upload a big binary?

Sure, so I first run the command `fastlane pilot upload`. Since we have many apps, I have noticed that sometimes this command fails while it is waiting for the build to be processed. Therefore, if that does happen I use some Spaceship commands to ensure whether the pilot command failed intermediately while it was waiting for the build to be processed or if there was an actual error, the commands I run are:

```
bundle_id = *******
release_version = *******
build_version = *******
app = Spaceship::Tunes::Application.find bundle_id
train = app.build_trains[release_version]
build = train.select {|n|n.build_version == build_version}[0]

#I check build.processed? | build.processing? | build.internal_state | build.external_state
```
The issue now is that build.processed? return a false positive. It will return true, but when I check on App Store Conncet UI, the build is still being processed.

@Skoti I just checked and there is no attribute processing_state for build. 

I assume that the `fastlane pilot upload` command is using the same underlying spaceship calls to check to see if the build is processed. Therefore, it sees that build.processed is set to true. It tries to distribute it internally but then it fails since the build is actually not processed.

**Comment by Skoti** [comment]
@pparmaei
If you use `tunes_all_build_trains(app_id:platform:)`
then you will get Tunes::BuildTrain and Tunes::Build instances and the parameter should be available.

**Comment by helloabinash** [comment]
@tguidon , Yes I also faced the "Bad Gateway" issue
The iTunes Connect also said the same, When I tried to login and see/refresh the activity page.

**Comment by pparmaei** [comment]
https://github.com/fastlane/fastlane/blob/1af33c0884e783867bdc07a324280ec6bef124ad/fastlane_core/lib/fastlane_core/build_watcher.rb#L59 

The core of the issue is that `build.export_compliance_missing?` returns `true`. This is assumed to mean that the build has finishes processing. But that is not the case. 

This is affecting almost every TestFlight upload that we do!

**Comment by pparmaei** [comment]
any updates on this issue. It is affecting the majority of our uploads.

**Comment by janpio** [comment]
I am a bit lost about the current state here. What kind of update are you expecting? 

If there is some bug in our code, could you please create a Pull Request with a fix?

If it is not really clear yet what is happening, so nothing to fix yet, we would have to go into debugging mode again I think. A full log of the output you are getting from executing the command until you encounter the problem (with a current version of fastlane) would be required.

Additionally [Spaceship logs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md#logging) or a [Charles session of the requests](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md#proxy-support) (send to piotrowski@gmail.com if you don't want to post publicly as it includes session cookies etc) could help to properly understand what is going on. Those would help to better understand what is being returned from Apple's server when and why.

**Comment by Skoti** [comment]
@pparmaei 
I have just checked the `processing_state` on _Tunes::Build_ instance of a freshly uploaded build and it is set to `processing`.
I got this by using:
```
Spaceship::Tunes.login("username", "password")
app = Spaceship::Tunes.find "bundle_id"

builds = app.tunes_all_builds_for_train(train: "specific_version")
// specified version is the one freshly uploaded
// or you can use
// train = app.tunes_all_build_trains.max_by(&:version_string)
// builds = app.tunes_all_builds_for_train(train: train.version_string)

latest_build = builds.max_by(&:build_version)
latest_build.processing_state
```
So this check seems to return correct value as oppose to _TestFlight::Build_ instance which is used in _build_watcher.rb_. 

Interestingly, when I tried to use:
`app.all_processing_builds` it returned an empty array

and when I tried to use:
`app.build_trains`
or `app.all_builds_for_train(train: "specific_version")`
I got `Spaceship::InternalServerError (Server error got 500)`

**Comment by patrikdevlin** [comment]
`upload_to_testflight` is failing with `Server error got 500`

I can see that the binary has been uploaded to iTunes Connect but fastlane is returning

```
[13:34:35]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2018.12.21)
[13:35:06]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2018.12.21)
[13:35:36]: Successfully finished processing the build 3.0.2 - 2018.12.21
[13:35:36]: Distributing new build to testers: 3.0.2 - 2018.12.21
[13:35:37]: Server error got 500
```

even though the build has not finished processing. This causes it to error.

Thoughts?

**Comment by wilrnh** [comment]
I also got the `Bad Gateway` error (fastlane 2.108) turns out I just had to login as the testflight user to itunes connect in the browser and accept a terms of service notice. Hope that helps someone.
