### ISSUE TITLE
What to do about Apple rejecting device frames generated by frameit?

### ISSUE THREAD

**Issue by aehlke** [fastlane/fastlane#13773]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 Frameit
 No
 No

#### Question Description

I've used frameit successfully in the past, however Apple just rejected my binary for this reason: 

```
Guideline 2.3.4 - Performance - Accurate Metadata

Your app preview includes content that does not sufficiently reflect the app in use. Specifically, your preview:

- Includes device images and/or device frames.
```

What do people do about this?

I've seen other apps use "flat" iPhone device frames (Uber, AirBnB, Kijiji are examples). Is there a way I could use this kind of device frame with frameit? I couldn't find a documented way to customize the frames.

**Comment by janpio** [comment]
Does this rejection refer to the screenshots or a preview video?

I am not sure if there is a proper way to customize the device frames. But I know the files are downloaded to `~/.fastlane/frameit/latest` and loaded from there. Messing with a picture should probably tell you if it is still used for framing - I think so.

**Comment by aehlke** [comment]
@janpio my preview video has no device frame, so it must be the screenshots.

Thanks for the tip. If it’s that hacky I may need to find a different tool.

**Comment by aehlke** [comment]
Gosh, I missed that I have a brief photo of someone holding an iPhone in a news article in my preview video. That must be it.

**Comment by janpio** [comment]
Ha, great I could nudge you in the right direction.

> If it’s that hacky I may need to find a different tool.

That would not have been _that_ hacky even, replacing the images should be pretty easy. (Actually something that `frameit` could/should support out of the box...)

**Comment by aehlke** [comment]
Yeah - I would love to be able to replace the iPhone device frame with a slightly more abstract device frame rather than a distractingly skeuomorphic one.

**Comment by janpio** [comment]
Check `~/fastlane/frameit/latest` - there you can just replace the frame that is being used. If the "hole" where the screenshot should be placed is not in the exact same place, edit `offsets.json` to fix the placement of the screenshot.
