### ISSUE TITLE
How to create enterprise development profile using match?

### ISSUE THREAD

**Issue by pragnesh-is** [fastlane/fastlane#13785]
Using match how can I create development certificate and development profile instead of InHouse profile ?

**Comment by pragnesh-is** [comment]
@janpio so you mean normal development type will also work with enterprise account ?

**Comment by janpio** [comment]
Example #4 in what I linked to:

```
match(git_url: "https://github.com/fastlane/certificates",
      type: "enterprise",
      app_identifier: "tools.fastlane.app")
```

**Comment by pragnesh-is** [comment]
> Example No 4 in what I linked to:
> 
> ```
> match(git_url: "https://github.com/fastlane/certificates",
>       type: "enterprise",
>       app_identifier: "tools.fastlane.app")
> ```

This will create InHouse profile or development ? I think this will create InHouse profile, if not that how can I create InHouse profile ?

**Comment by janpio** [comment]
There is a difference?

**Comment by pragnesh-is** [comment]
> There is a difference? What exactly does "inhouse" mean? Is this a special version of an enterprise profile?

InHouse is distribution profile, when you specify type as "enterprise" it is creating InHouse profile, I have not checked "development" with enterprise account so I am not sure it works with enterprise account or not.
