### ISSUE TITLE
How to mock fastlane actions in order to test Fastfile

### ISSUE THREAD

**Issue by josecostamartins** [fastlane/fastlane#13788]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

First: I'm not extremely proficient neither in Ruby nor in testing, so bear it with me.

My scenario: I'm trying to have tests for my Fastfile. We have many lanes and deploy 30 iOS apps using this Fastfile, it is growing complex each time... It's 900 lines long and takes care of creating new apps, submitting to testflight, submitting to the store, release approved apps, submitting to our testing environment, etc. It accepts external parameters, download json's, and with all this functionality came the need to make tests for it in order to ensure our CI and CD does not break too often because of our fastfile.

What I have done so far: Searching for fastlane tests is really difficult, once you search google or even github issue for fastlane tests, the majority of results are for using fastlane to test iOS or android code. But, after some persistence, I've hit a jackpot when finding this file: [fast_file_spec](https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/spec/fast_file_spec.rb) which is a huge help to know how to test my own fastfile.

My problem: Mocking. How do I mock fastlane actions? The aforementioned example uses fixtures that do not contain any fastlane action (it write to files).

#### Question Description

To illustrate my problem here is a snippet of code (modified), the idea is how to mock the **produce** command in the bottom.

```ruby
lane :my_lane do |options|
    environment = "production"
    if not ["sandbox", "production"].include?(options[:env])
        UI.user_error!("Environment #{environment} not recognized, valid values are 'sandbox' and 'production'")
    else
        environment = options[:env]
    end

    list_targets = download_whitelabel_json(environment)
    
    app_id = options[:app_id]
    if app_id.to_s.empty?
        UI.warning "app_id not defined, doing for all apps"
    end

    app_to_create = // logic to get specific app from apps list

    if not apps_to_create.any?
        UI.user_error!("Specified app_id not found...")
    elsif apps_to_create.size > 1
        UI.user_error!("Only one app can be created at each time...")
    end

    apps_to_create.each_with_index do |app_to_create, index|

    developer_team_id = app_to_create["id1"]
    appstore_team_id = app_to_create["id2"]
    store_name = app_to_create["name"]
    bundle_id = app_to_create["id3"]
    
    if store_name.to_s.empty?
        UI.user_error!("App name cannot be nil...")
    end

    if defined?(developer_team_id).nil?
        UI.user_error!("dev team id cannot be nil")
    end

    if defined?(appstore_team_id).nil?
        UI.user_error!("appstore_team_id cannot be nil")
    end
      
    begin
        produce #how to mock this guy
    rescue => ex
        message = "Error creating #{app["app_name"]} with produce\n```Error: #{ex}```"
        stops_execution = index == target.size-1
        send_slack_message(message = message, stops_execution = stops_execution)
      end
end
```

**Comment by josecostamartins** [comment]
@janpio,

First of all: Thank you for taking the time to answer
Second: Sorry for the late reply...

Actual reply: If I override **produce** on my `Fastfile`, that will affect real execution, won't it? Maybe I'm not seeing something here. 

Finally, I've actually have other problems, the [fast_file_spec](https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/spec/fast_file_spec.rb) I've linked previously has many dependencies to run the Fastfile by itself. One of them being the source code, apparently. 

Again, my lack of ruby knowledge might be getting in the way. If you can point to any learning materials that can help me achieve my goal, I'd much appreciate that.

**Comment by janpio** [comment]
> Actual reply: If I override **produce** on my `Fastfile`, that will affect real execution, won't it? Maybe I'm not seeing something here.

Yes, that would of course only be a temporary workaround for you to enable to write some "tests". But that is pretty much what actually mocking would do - remove the actual implementation and replace it with something else.

The file you linked to, https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/spec/fast_file_spec.rb, is actually the set of tests for https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/lib/fastlane/fast_file.rb.

The fastlane tests are written with rspec: https://blog.teamtreehouse.com/an-introduction-to-rspec

Looking as your `Fastfile` above again, you can probably "extract" most of the actual logic into individual methods that are imported from another file into the `Fastfile` - which then only calls one after another and finally calls `produce`. Then you can write normal tests for that file and its methods.

(Although I of course am not sure if this is the _best_ way to test a `Fastfile`)
