### ISSUE TITLE
Resign is giving an undefined method "shellescape" (NoMethodError) error

### ISSUE THREAD

**Issue by najidebian** [fastlane/fastlane#13789]
<details>
  <pre>Traceback (most recent call last):
	33: from /Users/user/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	32: from /Users/user/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	31: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
	30: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	29: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	28: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	27: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	26: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	25: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	24: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	23: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	22: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	21: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	20: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	19: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:2:in `block in parsing_binding'
	14: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	13: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	 9: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	 7: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/resign.rb:9:in `run'
	 6: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:19:in `resign'
	 5: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:34:in `resign'
	 4: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:132:in `create_provisioning_options'
	 3: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:132:in `map'
	 2: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:132:in `each'
	 1: from /Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:138:in `block in create_provisioning_options'
/Users/user/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/sigh/lib/sigh/resign.rb:138:in `map': [!] undefined method `shellescape' for :"com.appsandgames.dummyswiftappnaji":Symbol (NoMethodError)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :resigh do
resign(ipa:"./3844259376154_1543320149_1.ipa",signing_identity:
"iPhone Distribution: Name (teamid)",
provisioning_profile:{
"com.appsandgames.dummyswiftappnaji":"AdHoc_com.appsandgames.dummyswiftappnaji.mobileprovision"
})
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "appleemail@gmail.com"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-11-30**
</details></pre>
</details>

**Comment by janpio** [comment]
Can you please share the rest of the output you are getting? What is before the stacktrace is also relevant for context. Thanks.

**Comment by najidebian** [comment]
Hi janpio. Below is what you asked for. By the way resign works if the provisioning_profile attribute is not json (in the case of an app without extensions). Hope this helps.

Driving the lane 'resigh' 🚀
[17:37:20]: --------------------
[17:37:20]: --- Step: resign ---
[17:37:20]: --------------------
+---------------+--------+
|      Lane Context      |
+---------------+--------+
| PLATFORM_NAME |        |
| LANE_NAME     | resigh |
+---------------+--------+

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 💥   | resign | 0           |
+------+--------+-------------+

[17:37:20]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):

**Comment by janpio** [comment]
I noticed something. You are doing:
```
provisioning_profile:{ "com.appsandgames.dummyswiftappnaji":"AdHoc_com.appsandgames.dummyswiftappnaji.mobileprovision" })
```
but the examples lookes like this:
```
resign(ipa: "path", signing_identity: "identity", provisioning_profile: {
  "com.example.awesome-app" => "App.mobileprovision",
  "com.example.awesome-app.app-extension" => "Extension.mobileprovision"
})
```
I think you have to replace the `:` with ` => ` - this is not really JSON but a ruby hash ;)

**Comment by najidebian** [comment]
Thanks a lot janpio :) this solved it.
