### ISSUE TITLE
slack last_git_commit_hash brings with it last_git_commit as well

### ISSUE THREAD

**Issue by Skjalgsm** [fastlane/fastlane#13784]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running
slack(default_payloads: [:git_branch, :last_git_commit_hash])

The slack plugin prints 3 payloads ('git_branch', 'last_git_commit_hash' and _'last_git_commit'_).

I think it is because when checking to see if it should include the 'last_git_commit' it returns true because it finds '**last_git_commit**_hash'

https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slack.rb line 187

**Comment by janpio** [comment]
Indeed, that code seems to be faulty. Are you up to creating a PR to fix this maybe? That would be awesome 🤖

**Comment by Skjalgsm** [comment]
I'm not familiar enough with ruby to easily or comfortably make the change to fix this issue I'm afraid.

**Comment by janpio** [comment]
Ok. If someone else comes along:
https://github.com/fastlane/fastlane/blob/93202553fe83c176a7791b7189144e3ab04733bc/fastlane/lib/fastlane/actions/slack.rb#L187
1. Find out if there are tests for this action
2. If there are, add the above described case a failing test
3. Change this line to some better logic that doesn't match on partial matches
