### ISSUE TITLE
[Regression] scan `fail_build` set to false still fails on failed tests if Xcode 10 parallel tests is enabled

### ISSUE THREAD

**Issue by p4checo** [fastlane/fastlane#13781]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Setting the `fail_build` to `false` when invoking scan when parallel testing is enabled on Xcode and tests fail still fails the build.

This _might_ be related to #13414 and #13631.

Thanks! 🙏 

```
+----------------------------+----------------------------------------------------------+
|                               Summary for scan 2.108.0                                |
+----------------------------+----------------------------------------------------------+
| scheme                     | AppTests                                                 |
| device                     | iPhone 8                                                 |
| skip_slack                 | true                                                     |
| output_directory           | ./unit-test-report                                       |
| buildlog_path              | ~/Library/Logs/scan/scan.log                             |
| fail_build                 | false                                                    |
| workspace                  | ./App.xcworkspace                                        |
| skip_detect_devices        | false                                                    |
| clean                      | true                                                     |
| code_coverage              | true                                                     |
| skip_build                 | false                                                    |
| include_simulator_logs     | false                                                    |
| disable_concurrent_testing | false                                                    |
| derived_data_path          | ./DerivedData/                                           |
| should_zip_build_products  | false                                                    |
| result_bundle              | true                                                     |
| open_report                | false                                                    |
| slack_only_on_failure      | false                                                    |
| use_clang_report_name      | false                                                    |
| app_identifier             | com.my.app-identifier                                    |
| reinstall_app              | false                                                    |
| xcode_path                 | /Applications/Xcode.app                                  |
+----------------------------+----------------------------------------------------------+
```

#### Parallel testing

```
[2018-11-28 20:36:27.263 xcodebuild[23877:9033462] [MT] IDETestOperationsObserverDebug: (B4BD45A8-5189-4A91-932B-1ED942CBA8AC) Beginning test session AppTests-B4BD45A8-5189-4A91-932B-1ED942CBA8AC at 2018-11-28 20:36:27.263 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7f89cb573fd0> {
SimDevice: Clone 1 of iPhone 8 (7DFC1033-5C04-40CE-B29A-764F817B2DDC, iOS 12.1, Shutdown)
} (12.1 (16B91))
2018-11-28 20:36:48.267 xcodebuild[23877:9043391]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/path/to/code/unit-test-report/AppTests.test_result/3_Test/Diagnostics/AppTests-F759B84A-3BB8-4699-B099-F4521E244771/AppTests-CC3FD352-E909-4ADC-BF68-CF112394D379/Session-AppTests-2018-11-28_203648-YGk3hM.log
2018-11-28 20:36:48.267 xcodebuild[23877:9033462] [MT] IDETestOperationsObserverDebug: (50FA3F07-C4C3-4C98-865F-167B21D79E04) Beginning test session AppTests-50FA3F07-C4C3-4C98-865F-167B21D79E04 at 2018-11-28 20:36:48.267 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7f89cbacc0e0> {
SimDevice: Clone 2 of iPhone 8 (FE1F41BF-A34D-4BD7-BA91-63B9216E9A31, iOS 12.1, Shutdown)
} (12.1 (16B91))
2018-11-28 20:37:26.572 xcodebuild[23877:9043393] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f89cb84f7b0>
2018-11-28 20:38:24.810 xcodebuild[23877:9033462] [MT] IDETestOperationsObserverDebug: 117.606 elapsed -- Testing started completed.
2018-11-28 20:38:24.810 xcodebuild[23877:9033462] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2018-11-28 20:38:24.810 xcodebuild[23877:9033462] [MT] IDETestOperationsObserverDebug: 117.606 sec, +117.606 sec -- end
Failing tests:
URLTestCase.testKaboom()
** TEST FAILED **
[20:38:37]: Exit status: 65
+----------------------------+----------------+
|                Lane Context                 |
+----------------------------+----------------+
| DEFAULT_PLATFORM           | ios            |
| ENVIRONMENT                | default        |
| PLATFORM_NAME              | ios            |
| LANE_NAME                  | ios unit_tests |
| BUILD_NUMBER               | 2              |
| SCAN_DERIVED_DATA_PATH     | ./DerivedData/ |
| SCAN_GENERATED_PLIST_FILES | []             |
| SCAN_GENERATED_PLIST_FILE  |                |
+----------------------------+----------------+
[20:38:37]: Error building/testing the application - see the log above
```

#### Serial testing

```
AppTests.URLTestCase
testKaboom, failed - Kaboom 🧨💥
/path/to/code/AppTests/Sources/Shared/Foundation/URLTestCase.swift:13

    func testKaboom() {
        XCTFail("Kaboom 🧨💥")
    }


	 Executed 1027 tests, with 1 failure (0 unexpected) in 24.271 (25.692) seconds

2018-11-29 12:15:48.271 xcodebuild[55243:9232978] [MT] IDETestOperationsObserverDebug: 54.800 elapsed -- Testing started completed.
2018-11-29 12:15:48.271 xcodebuild[55243:9232978] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2018-11-29 12:15:48.271 xcodebuild[55243:9232978] [MT] IDETestOperationsObserverDebug: 54.800 sec, +54.800 sec -- end
Failing tests:
URLTestCase.testKaboom()
** TEST FAILED **
[12:15:56]: Exit status: 65
+--------------------+------+
|       Test Results        |
+--------------------+------+
| Number of tests    | 1027 |
| Number of failures | 1    |
+--------------------+------+
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'fastlane'
fastlane_require 'colorize'

fastlane_version "2.26.0"

default_platform :ios

platform :ios do
  before_all do
    reset_git_repo(force: true)
  end

  desc "Runs all the Unit Tests"
  lane :unit_tests do
    killsimulator
    resetsims(devices_regexp: reset_regexp)

    scan(
      scheme: ENV["UT_SCHEME"],
      device: ENV["UT_DEVICE"],
      skip_slack: true,
      output_directory: "./unit-test-report",
      buildlog_path: "~/Library/Logs/scan/#{ENV['BUILD_TAG']}-unit",
      fail_build: false
    )

    slather(
      scheme: ENV["UT_SCHEME"],
      workspace: ENV["WORKSPACE_PATH"],
      proj: ENV["PROJECT_PATH"],
      ignore: "App/Sources/View/*",
      html: true,
      build_directory: ENV["DERIVED_DATA_PATH"],
      output_directory: "./unit-coverage-test-report"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"]

apple_id ENV["APPLE_ID"]

itc_team_id ENV["ITC_TEAM_ID"]
team_id ENV["TEAM_ID"]

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-resetsims     | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-killsimulator | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.0.0        |
| io-console                    | 0.4.5        |
| CFPropertyList                | 2.3.6        |
| concurrent-ruby               | 1.1.3        |
| i18n                          | 0.9.5        |
| minitest                      | 5.11.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.5        |
| activesupport                 | 4.2.11       |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.5.2        |
| atomos                        | 0.1.3        |
| babosa                        | 1.0.2        |
| bundler                       | 1.16.0       |
| claide                        | 1.0.2        |
| clamp                         | 0.6.5        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| cocoapods-core                | 1.5.3        |
| cocoapods-deintegrate         | 1.0.2        |
| cocoapods-downloader          | 1.2.2        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.0.0        |
| netrc                         | 0.11.0       |
| cocoapods-trunk               | 1.3.1        |
| cocoapods-try                 | 1.1.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.0.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.3.1        |
| nanaimo                       | 0.2.6        |
| xcodeproj                     | 1.7.0        |
| cocoapods                     | 1.5.3        |
| colored                       | 1.2          |
| colorize                      | 0.8.1        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.10       |
| declarative-option            | 0.1.0        |
| unf_ext                       | 0.0.7.5      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20180417 |
| dotenv                        | 2.5.0        |
| emoji_regex                   | 0.1.1        |
| excon                         | 0.62.0       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.15.4       |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.12.2       |
| fastimage                     | 2.1.4        |
| jwt                           | 2.1.0        |
| memoist                       | 0.16.0       |
| multi_json                    | 1.13.1       |
| os                            | 1.0.0        |
| signet                        | 0.11.0       |
| googleauth                    | 0.6.7        |
| httpclient                    | 2.8.3        |
| mime-types-data               | 3.2018.0812  |
| mime-types                    | 3.2.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.23.9       |
| json                          | 2.1.0        |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.4.0        |
| rubyzip                       | 1.2.2        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.5        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 1.8.0        |
| unicode-display_width         | 1.4.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.6.5        |
| tty-cursor                    | 0.6.0        |
| tty-spinner                   | 0.8.0        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.0        |
| fastlane-plugin-cosigner      | 2.0.1        |
| fastlane-plugin-killsimulator | 0.1.0        |
| fastlane-plugin-logme         | 0.1.6        |
| fastlane-plugin-resetsims     | 0.1.1        |
| mini_portile2                 | 2.3.0        |
| nokogiri                      | 1.8.5        |
| slather                       | 2.4.6        |
</details>

*generated on:* **2018-11-29**
</details>

**Comment by janpio** [comment]
Ping @benasher44 as you were the author of these two PRs. Maybe you have some insight. Thanks! 🎢

**Comment by benasher44** [comment]
Yep this is a dup of #13414. I recommend close this issue. The PR linked to that issue checks for `Failing tests:` (shown in your output), which covers this issue.

**Comment by p4checo** [comment]
Thought it had already been released, sorry. 🙈 

In that case, I think we can close this. Any ETA for a new release containing the above fix?

**Comment by benasher44** [comment]
No idea sorry! I think I recommend a patch you could add to your `Fastfile` in the meantime in #13414

**Comment by p4checo** [comment]
Damn, completely missed that too! 😓 
Thank you very much 🙏

**Comment by benasher44** [comment]
No prob!
