### ISSUE TITLE
How is the platform decided?

### ISSUE THREAD

**Issue by Skjalgsm** [fastlane/fastlane#13793]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Platform ios vs android

#### Question Description
How is the platform decided? 

Right now I am trying to create a Fastfile that will work for both ios and android platforms. What I am seeing is that while running on a mac mini with Mojave it will print 
`PLATFORM_NAME=>:ios`
while on Windows 10 it will print
`PLATFORM_NAME=>nil`

Should I just run fastlane and send in the platform as an option - and if so, how does for_platform work? How can i specify the current platform myself?

**Comment by Skjalgsm** [comment]
`### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.5.3                        |
| Bundler?                    | true                         |
| Git                         | git version 2.16.1.windows.1 |
| Installation Source         | E:/Ruby25-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | E:/Ruby25-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018   |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |`

**Comment by getaaron** [comment]
the platform is decided based on the `platform` block your lane is inside of.

For example from https://carloscuesta.me/blog/shipping-react-native-apps-with-fastlane/:

```ruby
fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
end

platform :android do
  # Android Lanes
end
```

**Comment by Skjalgsm** [comment]
Ah okay, so having one lane that is run for both ios and android won't make sense, then.

I was thinking I could have a fastfile like this (pseudo code)

`lane build_app
    if platform == ios
        gym
    elseif platform == android
        gradle
    end
end `

But I am seeing now that I have to rethink my approach.

But this begs the question, what does setting the default platform do, if what platform you chose is decided by which platform the block is inside of? Is this in case you are not using the platform block?

**Comment by getaaron** [comment]
Yes, in case you are not using the platform block, that will be the default instead of `nil`.

If whether the build server is a Mac mini or a Windows machine determines which you want to use, you could use:

```ruby
if FastlaneCore::Helper.is_mac?
    gym
elseif FastlaneCore::Helper.is_windows?
    gradle
end
```

But of course, then you won't be able to run your Android builds on your Mac 🙃

**Comment by Skjalgsm** [comment]
Nah thats probably exactly what I am going to do :)
