### ISSUE TITLE
Error: no implicit conversion of Integer into String 

### ISSUE THREAD

**Issue by razalur** [fastlane/fastlane#13799]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello! When I run fastlane (even without args) I have an error. Don't know why...(

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>GitLabCI-MacMini:retail-mobile-ios jenkins$ fastlane
[✔] 🚀 
[16:55:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

Looking for related GitHub issues on fastlane/fastlane...

➡️  [PEM] `fastlane pem` fails on multiple app_identifiers `no implicit conversion of Array into String`
    https://github.com/fastlane/fastlane/issues/13559 [open] 13 💬
    a week ago

➡️  latest_testflight_build_number + 1 -> [!] no implicit conversion of Fixnum into String 
    https://github.com/fastlane/fastlane/issues/12097 [closed] 11 💬
    23 May 2018

➡️  Couldn't automatically detect the provisioning profile mapping
    https://github.com/fastlane/fastlane/issues/11703 [closed] 9 💬
    02 Aug 2018

and 20 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20Integer%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	23: from /Users/jenkins/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	22: from /Users/jenkins/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	21: from /Users/jenkins/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	20: from /Users/jenkins/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	19: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
	18: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	17: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	15: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	 9: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	 8: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:16:in `cruise_lane'
	 7: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:16:in `new'
	 6: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:35:in `initialize'
	 5: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:45:in `parse'
	 4: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:45:in `chdir'
	 3: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:56:in `block in parse'
	 2: from /Users/jenkins/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:56:in `eval'
	 1: from Fastfile:13:in `parsing_binding'
Fastfile:13:in `[]=': [!] no implicit conversion of Integer into String (TypeError)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"]=60
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"]=60

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Clean the project"
  lane :clean do
  	xcclean
  end

  lane :aaa do
  	puts "aaa"
  end

  desc "Update app version from commit tag"
  lane :update_version do |options|
  	git_tag_version = options[:version]

    puts git_tag_version

    major = ""
    minor = ""
    patch = ""
    build = ""

    pattern = /\Av(\d+).(\d+).(\d+)\((\d+)\)\z/
    if match = pattern.match(git_tag_version)
  		major, minor, patch, build = match.captures
  	else
  		UI.user_error!("Wrong version number: \"#{git_tag_version}\"!\nPlese use versioning like v{major_number}.{minor_number}.{patch_number}({build_number})")
    end

	if major.to_s.empty? || minor.to_s.empty? || patch.to_s.empty? || build.to_s.empty?
  		UI.user_error!("Wrong version number: \"#{git_tag_version}\"!\nPlese use versioning like v{major_number}.{minor_number}.{patch_number}({build_number})")
	end

	  version = "#{major}.#{minor}.#{patch}"

	  increment_version_number_in_plist(
	    version_number: "#{version}",
	    target: "mobileRetail"
	  )

	  increment_version_number_in_plist(
	    version_number: "#{version}",
	    target: "mobileRetailRelease"
	  )

	  increment_version_number_in_plist(
	    version_number: "#{version}",
	    target: "SiriIntentsExtension"
	  )

	  increment_version_number_in_plist(
	    version_number: "#{version}",
	    target: "SiriIntentsExtensionUI"
	  )

	  increment_version_number_in_plist(
	    version_number: "#{version}",
	    target: "NotificationServiceExtension"
	  )

	  increment_build_number_in_plist(
	    build_number: "#{build}",
	    target: "mobileRetail"
	  )

	  increment_build_number_in_plist(
	    build_number: "#{build}",
	    target: "mobileRetailRelease"
	  )

	  increment_build_number_in_plist(
	    build_number: "#{build}",
	    target: "SiriIntentsExtension"
	  )

	  increment_build_number_in_plist(
	    build_number: "#{build}",
	    target: "SiriIntentsExtensionUI"
	  )

	  increment_build_number_in_plist(
	    build_number: "#{build}",
	    target: "NotificationServiceExtension"
	  )
  end

  desc "Create archive and export ipa"
  lane :archive do |options|
  	filename = options[:filename]
  	puts "11111"
  	puts "#{filename}"
  	puts "22222"

	build_ios_app(
		workspace: "mobileRetail.xcworkspace",
		configuration: "Release",
		scheme: "mobileRetailRelease",
		silent: true,
		clean: true,
		output_directory: "./", # Destination directory. Defaults to current directory.
		output_name: "#{filename}",       # specify the name of the .ipa file to generate (including file extension)
		export_options: "./ExportOptions.plist"
	)
  end

  desc "Push to testflight"
  lane :beta do |options|
	user_name = options[:itunes_username]
	build_descr = options[:build_descr]
	filename = options[:filename]

	puts "#{filename}"
	puts "#{build_descr}"

	if user_name.to_s.empty? 
		UI.user_error!("Need to pass ITUNES_USERNAME to testflight lane")
	end 

	# Commit description
	# commit = last_git_commit
	# message = commit[:message]

	upload_to_testflight(
		username: "#{user_name}",
		ipa: "#{filename}"
		# beta_app_feedback_email: "RazzhivaykinAY@incbt.ru",
		# beta_app_description: "#{build_descr}"
	)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("psbank.ru") # The bundle identifier of your app
apple_id("RazzhivaykinAY@incbt.ru") # Your Apple email address

itc_team_id("832375") # iTunes Connect Team ID
team_id("2BP4J5FJYJ") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-12-03**
</details>
</pre>
</details>

**Comment by janpio** [comment]
As the error occurs when you are just running `fastlane`, this seems to be a problem with your `Fastfile`. Unfortunately the error reporting there isn't very good, so there is no line number available.

**Comment by janpio** [comment]
Quickly checked for you:

```
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"]="60"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"]="60"
```

Env vars are always strings.
