### ISSUE TITLE
how to specify branch name for git_pull

### ISSUE THREAD

**Issue by pranay1494** [fastlane/fastlane#13794]
$ git pull && git fetch --tags
[17:26:10]: ▸ There is no tracking information for the current branch.
[17:26:10]: ▸ Please specify which branch you want to merge with.
[17:26:10]: ▸ See git-pull(1) for details.
[17:26:10]: ▸ git pull <remote> <branch>
[17:26:10]: ▸ If you wish to set tracking information for this branch you can do so with:
[17:26:10]: ▸ git branch --set-upstream-to=origin/<branch> master

**Comment by pranay1494** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

```
### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.1                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.19.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.1 (18B75)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

    # api_token: ENV["271675b748ccfa2affbfd029ab6f632db2072bd9"],
    # owner_name: ENV["pranay1494-gmail.com"],

platform :android do

before_all do
  import_from_git(url:"{touchwonders_git_repo}:/library/fastlane.git", path:"Fastfile")
    ENV["APPCENTER_API_TOKEN"] = "271675b748ccfa2affbfd029ab6f632db2072bd9"
    ENV["APPCENTER_OWNER_NAME"] = "pranay1494-gmail.com"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    ensure_git_status_clean
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "generates Debug Apk"
  lane :generateDebugApk do |options|
    # git_pull
    # git_branch

    current_branch = git_branch
    puts "current branch is " + current_branch

if !options[:remote_branch].nil? && options[:remote_branch] != current_branch
      puts "Checkout new branch #{options[:remote_branch]}"
      sh "git checkout " + options[:remote_branch]
    else
      sh "git pull origin " + options[:remote_branch] 
end

    # git_checkout(remote_branch: options[:remote_branch]) 
    increment_version_code
    current_version_name = android_get_version_name 
    gradle(
      properties: {
    'versionName' => if options[:versionName].nil? || options[:versionName].empty?
      current_version_name
    else
      options[:versionName]
    end
  },
      task: "clean assemble",
      build_type: 'release',
      flavor: 'prod'
      )
#     dropbox(
#     file_path: './app/build/outputs/apk/prod/release/app-prod-release-unsigned.apk',
#     app_key: '8nnpf72yosc0fox',
#     app_secret: 'zs3cngy1d2ytx4r',
#     dropbox_path: '/path/to/Dropbox/destination/folder',
# )

    appcenter_upload(
    api_token: ENV["APPCENTER_API_TOKEN"],
    owner_name: ENV["APPCENTER_OWNER_NAME"],
    app_name: "Dummy-release",
    apk: "./app/build/outputs/apk/prod/release/app-prod-release-unsigned.apk"
)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.example.pranaybansal.mvvm_sample") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android     | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-appcenter              | 0.1.7   | ✅ Up-To-Date  |
| fastlane-plugin-dropbox                | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-publish_dropbox        | 0.1.4   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.0.0        |
| slack-notifier                         | 2.3.2        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.0        |
| claide                                 | 1.0.2        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.7.0        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 1.8.0        |
| unicode-display_width                  | 1.4.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.4.0        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.5.2        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.6.5        |
| tty-cursor                             | 0.6.0        |
| tty-spinner                            | 0.8.0        |
| babosa                                 | 1.0.2        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.62.0       |
| unf_ext                                | 0.0.7.5      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20180417 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| fastimage                              | 2.1.4        |
| gh_inspector                           | 1.1.3        |
| mini_magick                            | 4.5.1        |
| multi_json                             | 1.13.1       |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.2.2        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.0        |
| dotenv                                 | 2.5.0        |
| bundler                                | 1.17.1       |
| faraday_middleware                     | 0.12.2       |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.5        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| mime-types-data                        | 3.2018.0812  |
| mime-types                             | 3.2.2        |
| signet                                 | 0.11.0       |
| memoist                                | 0.16.0       |
| os                                     | 1.0.0        |
| googleauth                             | 0.6.7        |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.23.9       |
| emoji_regex                            | 0.1.1        |
| faraday                                | 0.15.3       |
| json                                   | 2.1.0        |
| io-console                             | 0.4.5        |
| libxml-ruby                            | 2.9.0        |
| jwt                                    | 2.1.0        |
| psych                                  | 2.1.0.1      |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-versioning_android     | 0.1.0        |
| fastlane-plugin-appcenter              | 0.1.7        |
| fastlane-plugin-dropbox                | 0.2.0        |
| dropbox_api                            | 0.1.12       |
| rack                                   | 2.0.6        |
| oauth2                                 | 1.4.1        |
| bigdecimal                             | 1.2.8        |
```

**Comment by getaaron** [comment]
This is really a git question, not a fastlane question

- whatever branch you have checked out locally when running `git_pull` needs to have a remote tracking branch

- if you're not sure you can run `git status` to see (or `git branch -vv` if you are running an older version of git)

if `git pull` works on the command line then the fastlane `git_pull` action will work as well

also, you probably should reset your dropbox secret ASAP since you just posted it publicly on github. best practice is to use environment variables rather than hardcoding the secrets in your fastfile.

**Comment by pranay1494** [comment]
> if `git pull` works on the command line then the fastlane `git_pull` action will work as well

`git pull` is working but `git_pull` is not that why as you can see in the fastfile i have added sh command for git pull.

so there must be something i am doing wrong any help would be appreciated.
