### ISSUE TITLE
Does ITMSTransporter change the name of .ipa files?

### ISSUE THREAD

**Issue by marlenabowen** [fastlane/fastlane#13802]
### Question Checklist

- [ ] Updated fastlane to the latest version (I am not allowed to do this at my company, we are pinned to 2.105.2)
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Does ITSMTransporter change the file name of .ipa files during upload? Is there a way to prevent this?

No. 

No, I don't think ITSMTransporter is considered a plugin, and I don't see how I'd be able to fix this issue outside of fastlane.

#### Question Description

It seems like, during upload to TestFlight, transporter is changing the name of my .ipa file. I am passing my .ipa to `upload_to_testflight` like so: `ipa: "folder/name_of_ipa.ipa"`, but during execution, I see this in my console:

```
DEBUG [2018-12-03 10:24:11.89]: [Transporter]: DEBUG:   <really long and seemingly random alphanumeric file name>.ipa will be verified by Apple's web service to determine if it is a valid file.
```

and then in App Store Connect, under `Activity`, the `Original File Name` for the .ipa shows up as `<really long and seemingly random alphanumeric file name>.ipa`.  My Release Management team relies on `Original File Name` to verify that the correct binary was uploaded. Is there a way to prevent this rename? I can't figure out how/where it is happening.

**Comment by janpio** [comment]
I looked into this, the code responsible for the rename is this:
https://github.com/fastlane/fastlane/blob/e57a8238850de562a69161bc1ce46df71d3fed1e/fastlane_core/lib/fastlane_core/ipa_upload_package_builder.rb#L14-L50

In `generate` it calls `copy_ipa`, which then calls `unique_ipa_path` to get a unique path where your original ipa is copied to. 

Before that new, unique path also included the original filename - but as these can be anything the users decides, this was causing problems and changed here to only be the hash: https://github.com/fastlane/fastlane/pull/12334/files

Going further back I see that this `unique_ipa_path` is also pretty new, but there are comments that this was causing issues as well: https://github.com/fastlane/fastlane/commit/ebe1da0023a2ac3fbe020838401618d1c218f5a0

So - going back to working with what the users has as the `ipa` filename seems like a bad idea. In the past, someone thought it was a good idea to replace the filename with something safe - a md5 and later sha256 hash of the existing name.

What exactly is your requirement from the Release Management team - do they check if the uploaded file matches a version you were told to build, or could you supply them with the hash of the uploaded file and they would compare these two?

Alternatively fastlane could change the filename from the computed hash to something safe that only contains allowed characters (probably meaning we remove anything that is not `[a-Z0-9]`) - but that could create pretty ugly file names as well.
