### ISSUE TITLE
[spaceship] Enable trusted number SMS verification

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13800]
There are currently 2 PRs implementing this, but both have problems.

https://github.com/fastlane/fastlane/pull/13507 + https://github.com/fastlane/fastlane/pull/13554

I created this issue to extract the discussion from the PR.

**Comment by jgadbois** [comment]
So on my end, when I add two trusted phone numbers - they both send 4 digit SMS message in the `TrustedDevices` API response, not 6 digit `TrustedPhoneNumber` codes.  

With that set up I have no way of knowing that there are both `TrustedDevices` *and* `TrustedPhoneNumbers`.

In both mine and @mariannegru 's setup, I don't think there's a way to know that we need to give both options to the user.

**Comment by janpio** [comment]
Ok, I know a bit about this as I just rewrote the login logic for spaceship:

- Everything 4 digit is "2 step verification": https://support.apple.com/en-us/HT204152
- Everything 6 digit is "2 factor authentication": https://support.apple.com/en-us/HT204915

In https://github.com/fastlane/fastlane/pull/13507#issuecomment-440794407 I described the process for 2 factor authentication with 6 digit codes: You login in and get your push, if you tell the system you can't access that you get the option to send SMS.

How does it work for your with 2 step verification?

**Comment by mariannegru** [comment]
I suggest to add a last option to the devices list (if any present into the response) as  SMS authentication that will show the phones. Can I have an example of two step verification account response? Unfortunately I do not have one.

**Comment by janpio** [comment]
What do you mean exactly with "add a last option to the devices list (if any present into the response) as SMS authentication that will show the phones"? 

Are you on 2FA @mariannegru, 6 digit codes?
And you @jgadbois, you are using 4 digit codes so 2 step verification, correct?

--- 

For 2 factor authentication, which I am using, on the web UI directly after username + password you get the token via push and should enter it. Only if you click another button, you get the option to choose a phone to receive an SMS (See https://github.com/fastlane/fastlane/pull/13507#issuecomment-440794407) - we will have to figure out a way to go from "input 6 digit code" to "choose phone to receive sms" but I am not really sure how, without make the login process harder for _everyone_ (I guess 99% of all logins will use the 6 digit code via push, not via SMS).

---

What does the 2 step verification flow look like exactly?

**Comment by mariannegru** [comment]
@janpio Yes I'm on 2FA, the account is not mine so I need to select the phone number that is not the default number. As I understand you want to leave the current flow but to be able to support selecting a different phone number. Therefore we have the following options:
1. Add a command line option that will enable the phone selection when used so by default will ask for code
2. When asking for code to support adding a sentence like 'phone' that will show phone list

**Comment by mariannegru** [comment]
@jgadbois can you post an authorized response to see the diffrencies? I think the difference is in the security code definition.

**Comment by janpio** [comment]
> As I understand you want to leave the current flow but to be able to support selecting a different phone number.

I see no other option how to implement this. The web UI can offer the input and a link to the phone flow at the same time, but in the console we have to go to the token input and allow a good "exit" to the phone flow.

**Comment by mariannegru** [comment]
For CI integrations the command line option would be preferred, so we might have to implement both options command line for CI and an exit for console.

**Comment by janpio** [comment]
Can you elaborate how that would help? On CI you need to use a app specific password anyway as you can't input anything, right? Why do you need a flag to enable login via sms sent token? (Or do I miss something?)

**Comment by mariannegru** [comment]
@janpio isn't FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD  password for uploading to store?

**Comment by mariannegru** [comment]
I have a working solution with twilio and I only need the functionality to show the phone list so I can force SMS send and this is for developer portal

**Comment by janpio** [comment]
@mariannegru Yes, you are right: `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is indeed for uploading. The other calls can use `FASTLANE_SESSION` which is described here: https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification So you might not need your Twilio work around - although that is a really interesting hack (I assume you wanted to get the sent token via an API and use that as the param somehow?).

**Comment by mariannegru** [comment]
Yes @janpio I wait for the token using Twilio API and redirect that to the stdin of the bundle exec ..... I do that in nodejs because I do not know how to do the stdin redirect to a stream in ruby (I'm not an experienced ruby developer).

**Comment by rlam3** [comment]
@janpio is this similar to the following issue? https://github.com/fastlane/fastlane/pull/13743

**Comment by janpio** [comment]
No @rlam3. That PR fixes the use of `FASTLANE_SESSION` which was semi broken. Here we are talking about how to best implement a way to let users send their 2FA/2SV tokens via SMS as they can in the Apple web login UI.

**Comment by rlam3** [comment]
@janpio Thank you for clearing this up. I removed the link.

**Comment by janpio** [comment]
Random thought: Could Ctrl+S (or similar) work as a way to trigger the SMS flow?

**Comment by janpio** [comment]
Ok, so I thought about this some more: The only proper way to "escape" the normal x digit input is to type e.g. `sms` and hit Enter, then the new "display SMS numbers" logic takes over. (For CI we could implement a new option or env variable that skips the normal input and goes to SMS directly).

I am currently working on getting an account with 2 step verification, so I can test and understand both flows better.

**Comment by janpio** [comment]
Ok, got it via a super old iPhone 4S with iOS6 running...

Here was my documentation on how 2FA works:
https://github.com/fastlane/fastlane/pull/13507#issuecomment-440794407

And here is it for 2SV:
![2_choose](https://user-images.githubusercontent.com/183673/50365185-ac345700-0573-11e9-9758-19d38a8ac358.PNG)
![3_device](https://user-images.githubusercontent.com/183673/50365186-ac345700-0573-11e9-88c6-037acbbe9d2a.PNG)

---

So for 2FA after login you automatically get a 6 digit code pushed to your devices. You can manually switch to the list of phone numbers and select one to retrieve a text message with a 6 digit code.

2SV works differently and you get a selection of methods directly after login: You can chose a device or a phone number (by default there is only a phone number after registration, you can add devices that you added to "Find my Phone" manually). Depending on what you chose, you get the 4 digit code pushed to your device or sent a text message.

**Comment by janpio** [comment]
Status update before I leave for the holidays 🎄: I have it all connected together, using bits of #13507 and #13554 plus the missing pieces and some general cleanup on the 2SV/FA code. 

Everything works, but during testing I got Apple to block my account from login which is currently not handled by the login code but probably should be ;) Probably a new issue though, so expect a PR with just adding this functionality first thing next year 🎆

**Comment by jgadbois** [comment]
Awesome, thanks @janpio !

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/pull/14011 is ready for testing.

**Comment by janpio** [comment]
PR #14011 has been merged and this will be included in the next release 👍

**Comment by janpio** [comment]
Hey everyone that posted here, I am currently working on a first improvement to the 2FA sms handling of fastlane/spaceship: [A way to define which phone number should automatically be selected for the 2FA token sms](https://github.com/fastlane/fastlane/issues/13980).

I need some help with the output on the Apple UI though: [#13980 (comment)](https://github.com/fastlane/fastlane/issues/13980#issuecomment-466402647) Would be great if some of your with "trusted phone numbers" in their accounts could take a look and reply. Thanks!
