### ISSUE TITLE
fastlane finished with errors ABOUT "commit_version_bump"

### ISSUE THREAD

**Issue by shirebella** [fastlane/fastlane#13806]
![image](https://user-images.githubusercontent.com/20533768/49435478-af98b600-f7f1-11e8-9a00-77d1bec2ab32.png)

![image](https://user-images.githubusercontent.com/20533768/49435138-d7d3e500-f7f0-11e8-9d05-bf3c421a650e.png)

In my Fastfile, i have do this 

```
   increment_build_number(
        xcodeproj: "myProjectName.xcodeproj"
   )
```

but In the end, I successfully uploaded the file to the third-party publishing website.

Just can't stand the error.

Thanks all!!!!

**Comment by janpio** [comment]
Using `commit_version_bump` only works if only the expected files are changed. The error message tells you that you have 2 additional unexpected files: `pygyer/PingShenMe.app.dSYM.zip` and `pygyer/PingShenMe.ipa`. 

Get rid of those, then the version bump should be commited.  
(A simple way might be to change the order of your last two actions so the commit is first bumped, then uploaded to pgyer - which possibly creates these files)

pgyer is something like HockeyApp, a 3rd party beta testing service?
