### ISSUE TITLE
Lane `crashlytics` returns with error.

### ISSUE THREAD

**Issue by laxmorek** [fastlane/fastlane#13803]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```ruby
lane :beta do
  getCertificates
  getProvisioningProfile(bundleId: "XXX")
  buildApp(schemeName: "XXX")
  sendToCrashlytics()
end

private_lane :getCertificates do 
  get_certificates(
    username: "XXX",
    team_id: "XXX",
    output_path: "fastlane/cert/"
  )
end

private_lane :getProvisioningProfile do |options|
  get_provisioning_profile(
    adhoc: true,
    app_identifier: options[:bundleId],
    username: "XXX",
    output_path: "fastlane/cert/"
  )
end

private_lane :buildApp do |options|
  build_app(
    scheme: options[:schemeName],
    clean: true,
    output_directory: "fastlane/ipa/",
    include_symbols: true,
    export_method: "ad-hoc",
    export_xcargs: "-allowProvisioningUpdates",
    silent: true
  )
end

private_lane :sendToCrashlytics do 
  crashlytics(
    api_token: "XXX",
    build_secret: "XXX",
    emails: "tester1@abc.com,tester2@abc.com,tester3@abc.com"
  )
end 
```

When I run `bundle exec fastlane beta` I get this error message on the very end of log (get_certificates, get_provisioning_profile, build_app pass without problems):

```code
[19:08:29]: fastlane finished with errors
[!] 2018-12-03 19:08:07.725 submit Crashlytics: Crashlytics.framework/submit 1.4.0 (20)
2018-12-03 19:08:12.107 submit Crashlytics: Added Testers/Groups Successfully 200
2018-12-03 19:08:29.335 submit Crashlytics: Unable to submit build. Response code: 0
2018-12-03 19:08:29.356 submit Crashlytics: Failed to upload binary
```

It is strange because build will be successfully uploaded and all testers will be added. I can see it on the Fabric webpage. Why this lane finish with the error when it looks like it's working?

I found a few issues in this repo with similar problem but all of them was reloaded to older versions of Fastlane and Crashlytics. Also none of them described the behavior that build was sending out correctly despite the error messages. That's way I decided to start new issue. 

I use Crashlytics via Cocoapods in the latest version: `pod 'Crashlytics', '3.12.0'`

#### Update 1

I have realized that build is visible on Fabric but it is not available to install.

![img_0d2a6bb1fa16-1](https://user-images.githubusercontent.com/4774319/49394891-566b4c80-f735-11e8-9910-71857de9a0a4.jpeg)

#### Update 2

I run lane with `--verbose` flag.

This is calling under the hood.
```code
./Pods/Crashlytics/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath '/Users/kamilharasimowicz/Documents/projects/XXX/fastlane/ipa/XXX.ipa' -emails 'tester1@abc.com,tester2@abc.com,tester3@abc.com' -notifications YES -debug NO
```

Stacktrace 
```code
ERROR [2018-12-03 22:54:51.84]: fastlane finished with errors
Traceback (most recent call last):
	42: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	41: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	40: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	39: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	38: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
	37: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	36: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	35: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	34: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	33: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	32: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	31: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	30: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	29: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	28: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	27: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	26: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	25: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	24: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	23: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	22: from Fastfile:9:in `block in parsing_binding'
	21: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	20: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	19: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	18: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:24:in `block in parsing_binding'
	16: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	15: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	14: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	13: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:81:in `block in parsing_binding'
	11: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	10: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 8: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 7: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	 6: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 5: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	 4: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
	 3: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
	 2: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
	 1: from /Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/kamilharasimowicz/.rvm/gems/ruby-2.5.1/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] 2018-12-03 22:54:30.318 submit Crashlytics: Crashlytics.framework/submit 1.4.0 (20) (FastlaneCore::Interface::FastlaneError)
2018-12-03 22:54:34.452 submit Crashlytics: Added Testers/Groups Successfully 200
2018-12-03 22:54:51.808 submit Crashlytics: Unable to submit build. Response code: 0
2018-12-03 22:54:51.829 submit Crashlytics: Failed to upload binary
```

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1  

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
 </pre>
</details>

**Comment by janpio** [comment]
What happens if you execute the generated command manually on the command line?

**Comment by SimonSimya** [comment]
I have the same problem. It worked until a few days ago and now my build is failing with the same error despite successful upload.

**Comment by laxmorek** [comment]
@janpio I have updated Fastlane to `2.111.0` and it works now. 

@SimonSimya FYI
