### ISSUE TITLE
Could not find faraday-0.15.4 in any of the sources (Bundler::GemNotFound) 

### ISSUE THREAD

**Issue by UZheng** [fastlane/fastlane#13819]
version:  fastlane-2.109.0

work for:  iOS in Mac

There is no problem with fastlane on the command line, but it will get an error when called on Jenkins.
the error infomation like this:

```
bundle exec fastlane for_pgyAdhoc 'des: test' buildID:1
/Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find faraday-0.15.4 in any of the sources (Bundler::GemNotFound)
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:171:in `specs'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:238:in `specs_for'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:227:in `requested_specs'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:20:in `setup'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler.rb:107:in `setup'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/admin/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.109.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.4       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.4       |
| openssl                   | 2.1.1        |
| json                      | 2.1.0        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| addressable               | 2.5.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| fastimage                 | 2.1.4        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| os                        | 1.0.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-12-05**
</details>

**Comment by UZheng** [comment]
I tried again.  
I use delete the command "bundle exec" and just run "fastlane for_pgyAdhoc 'des: test' buildID:1" , then it worked with Jenkins Ci environment. But, I dont know Why.

**Comment by janpio** [comment]
Is `fastlane env` different from `bundle exec fastlane env`?

**Comment by UZheng** [comment]
> Is `fastlane env` different from `bundle exec fastlane env`?

They are the same.
In fact, I have multiple projects on Jenkins that are packaged using fastlane. The rest are valid. Only the current project executing the bundle exec fastlane command will report an error. The difference is that the current project was created using fastlane 2.108.0, while the others are using older versions.

**Comment by UZheng** [comment]
> Can you compare the `Gemfile.lock` of an older and the new project? Are they identical?
> How did you install and update fastlane?

> The the `Gemfile.lock` of  the new project include the ` faraday (0.15.4) multipart-post (>= 1.2, < 3)`,but the older doesn't. As the error infomation in Jenkins , it can't find faraday-0.15.4.
> I update fastlane just run ' bundle update fastlane'

**Comment by UZheng** [comment]
I find the version 1.17.1 of  bundler is not in the same path as the old versions.
When fastlane  run in Jenkins , bundler can't use version 1.17.1, so how can I fix it?
![snip20181206_4](https://user-images.githubusercontent.com/10076220/49564843-fd333100-f95f-11e8-891a-647cf6a26be4.png)
![snip20181206_3](https://user-images.githubusercontent.com/10076220/49564854-058b6c00-f960-11e8-8b7f-e18dd344cbef.png)

**Comment by joshdholtz** [comment]
@UZheng Heyyyy 👋 Your command that you put in your description shows you using `bundle exec` but your fastlane output shows bundler not installed. Can you try running `bundle exec fastlane env` and past that in here so we have the exact same environment that you are using?

Also, have you tried running `bundle update fastlane` or `bundle upate` to see if that helps with anything?

**Comment by UZheng** [comment]
> @UZheng Heyyyy👋您在说明中输入的命令显示您正在使用，`bundle exec`但您的fastlane输出显示未安装bundler。你可以尝试`bundle exec fastlane env`在这里跑步和过去，所以我们有完全相同的环境吗？
> 
> 此外，你试过跑步`bundle update fastlane`或`bundle upate`看看是否有任何帮助吗？

Thank you very much for your help, this should be a problem with Jenkins.
