### ISSUE TITLE
[2.109.0] Could not upload with fastlane deliver: source sequence is illegal / malformed utf-8 (JSON :: GeneratorError)

### ISSUE THREAD

**Issue by kazuhidet** [fastlane/fastlane#13815]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`source sequence is illegal / malformed utf-8 (JSON :: GeneratorError)` error occurs when uploading ipa to iTunes connect with fastlane deliver.

The problem is in the following part modified by fastlane - 2.109.0, and to_json is in error because there is a character string which is not normally escaped in body.
(The difference is meaningless because it is an ad hoc modification that I added.)

<pre>
--- client.rb	2018-12-05 10:44:31.000000000 +0900
+++ /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/client.rb	2018-12-05 10:37:32.000000000 +0900
@@ -780,7 +780,11 @@
       params_to_log = params_to_log.collect do |key, value|
         "{#{key}: #{value}}"
       end
+      begin
       logger.info(">> #{method.upcase} #{url}: #{body.to_json} #{params_to_log.join(', ')}")
+      rescue Exception => e
+        logger.info(">> #{method.upcase} #{url}: [Broken body!] #{params_to_log.join(', ')}")
+      end
     end

     def log_response(method, url, response, headers = nil, &block)
</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[08:55:49]: Successfully loaded '/Users/Shared/Develop/AutoBuild/workspace/**********/fastlane/Deliverfile' 📄

+-----------------------+---------------------------+
|   Detected Values from './fastlane/Deliverfile'   |
+-----------------------+---------------------------+
| app_identifier        | ********** |
| username              | ********** |
+-----------------------+---------------------------+

[08:55:49]: Login to App Store Connect (**********)
[08:55:50]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.109.0 Summary                           |
+--------------------------------------+--------------------------------------+
| username                             | ********** |
| dev_portal_team_id                   | ********** |
| app_identifier                       | ********** |
| app_version                          | 2.5.0                                |
| app_icon                             | arucocoron/Assets.xcassets/iTunesAr  |
|                                      | twork.imageset/iTunesArtwork@2x.png  |
| force                                | true                                 |
| screenshots_path                     | ./fastlane/screenshots               |
| metadata_path                        | ./fastlane/metadata                  |
| platform                             | ios                                  |
| edit_live                            | false                                |
| use_live_version                     | false                                |
| skip_binary_upload                   | false                                |
| skip_screenshots                     | false                                |
| skip_metadata                        | false                                |
| skip_app_version_update              | false                                |
| overwrite_screenshots                | false                                |
| submit_for_review                    | false                                |
| reject_if_possible                   | false                                |
| automatic_release                    | false                                |
| phased_release                       | false                                |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+

[08:55:51]: Making sure the latest version on App Store Connect matches '2.5.0' from the ipa file...
[08:55:51]: '2.5.0' is the latest version on App Store Connect
[08:55:52]: Loading './fastlane/metadata/ja/description.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/keywords.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/release_notes.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/support_url.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/marketing_url.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/name.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/subtitle.txt'...
[08:55:52]: Loading './fastlane/metadata/ja/privacy_url.txt'...
[08:55:52]: Loading './fastlane/metadata/copyright.txt'...
[08:55:52]: Loading './fastlane/metadata/primary_category.txt'...
[08:55:52]: Loading './fastlane/metadata/secondary_category.txt'...
[08:55:56]: Successfully uploaded set of metadata to App Store Connect
[08:55:56]: Starting with the upload of screenshots...
[08:55:56]: Successfully uploaded screenshots to App Store Connect
[08:55:57]: Uploading app icon...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Uploading metadata to iTunes Connect error: source sequence is illegal/malformed utf-8
    https://github.com/fastlane/fastlane/issues/13608 [open] 3 💬
    3 weeks ago

➡️  Uploading metadata to iTunes Connect error: source sequence is illegal/malformed utf-8
    https://github.com/fastlane/fastlane/issues/13125 [closed] 5 💬
    5 weeks ago

➡️  Uploading metadata to iTunes Connect error: source sequence is illegal/malformed utf-8
    https://github.com/fastlane/fastlane/issues/11961 [closed] 3 💬
    08 Jun 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/client.rb:783:in `to_json': [!] source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/client.rb:783:in `log_request'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/client.rb:658:in `request'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/du/du_client.rb:75:in `upload_file'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/du/du_client.rb:29:in `upload_large_icon'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/tunes/tunes_client.rb:774:in `upload_large_icon'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/spaceship/lib/spaceship/tunes/app_version.rb:446:in `upload_large_icon!'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/deliver/lib/deliver/upload_assets.rb:16:in `upload'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/deliver/lib/deliver/runner.rb:123:in `upload_metadata'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/deliver/lib/deliver/runner.rb:38:in `run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/fastlane-2.109.0/bin/fastlane:23:in `<top (required)>'
	from /opt/local/bin/fastlane:22:in `load'
	from /opt/local/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /opt/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1618)                  |
| Ruby Lib Dir                | /opt/local/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.109.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2018-12-05**
</details></pre>
</details>

**Comment by kazuhidet** [comment]
As a result of further analysis of the code, the 'body' of 'block' passed to this function 'log_request' contains information that is not JSON, such as uploaded PNG file. so if you try to convert it to JSON unconditionally it will cause problems.

**Comment by janpio** [comment]
Thanks, that code was added by me. I will look into this asap.

**Comment by janpio** [comment]
Ok, I understood the issue: 
When uploading an app icon, the `body` of the request is present but can not be encoded as json, which crashes the current logging functionality. 
Your PR #13823 suggests to not log requests whose bodies are not JSON.
Correct?

**Comment by kazuhidet** [comment]
That’s right!

**Comment by bimusiek** [comment]
Having exactly the same issue 😞

**Comment by janpio** [comment]
The same problem occurs when uploading Screenshots.

**Comment by janpio** [comment]
PR fixing this issue is at https://github.com/fastlane/fastlane/pull/13825. It would be great if you could have a look 👀 at it as well @kazuhidet.

We are going to review and merge this as fast as possible and release 2.109.1.

Sorry for the trouble, I am ashamed (and confused) that I didn't catch this while testing the new logging code. Shouldn't have happened 🙇‍♀️

**Comment by postmechanical** [comment]
Thanks for owning the issue @janpio but my biggest complaint about `fastlane` in general is that almost every update breaks in one way or another that I am pretty close to abandoning the tool together because it so frequently fails me when I need it the most. I wish the team could address that issue in general. Build tools fundamentally should never break anyone's build. I write this as a former build tools engineer myself.

**Comment by janpio** [comment]
We are working hard on achieving that of course. That being said: For mission critical deployments of fastlane I definitely advise to wait with updating for a few days. Try it first on your staging environment with development variants of your app. And if something did go wrong, you can always downgrade without the fear of losing any data or incompatibilities.

But as this is an open source project, the only real response of course has to be a link to https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md - I am definitely _not_ a former build tools engineer, so your insight and contributions might be very helpful.

---

And: 2.109.1 is out! https://rubygems.org/gems/fastlane/versions/2.109.1 Please let us know if this fixes your issues. Thanks.
