### ISSUE TITLE
Error on raise_if_conflicts

### ISSUE THREAD

**Issue by pragnesh-is** [fastlane/fastlane#13813]
I am getting following errors, I have checked similar error: https://github.com/fastlane/fastlane/issues/11657, But suggested solutions on it will not work in my case because I can not run [sudo] bundle install/update commands on my ci machine. 

So is there any other solution like, I can find both different versions of slack_notifier and remove one of it.

```
fastlane finished with errors
/Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate xcov-1.3.0, because slack-notifier-2.3.2 conflicts with slack-notifier (~> 1.3) (Gem::ConflictError)
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems.rb:196:in `rescue in try_activate'
```

**Comment by janpio** [comment]
Please post all the information asked for in our [bug report template](https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md), we need the whole output (including the command you are running) and your fastlane env to be able to understand what is happening here. Thanks.
