### ISSUE TITLE
Add `created by` to Certificate

### ISSUE THREAD

**Issue by cturner35** [fastlane/fastlane#13829]
### Feature Request
Can the created by field that is displayed in the developer portal be added to the Certificate.rb object?

I tried to find the property in the attr returned by the service call but I can't find anything in there.

#### Motivation Behind Feature
I need to be able to tell who created a cert.

**Comment by janpio** [comment]
Are you referring to https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/certificate.rb?

Super quick research in the dev tools of my browser indicates that https://developer.apple.com/services-account/QH65B2/account/ios/certificate/getCertificate.action includes the "Created by" (as `requesterNickName`, `requesterFirstName `, `requesterLastName `, `requesterEmail`) information. But in the codebase of spaceship we only have https://developer.apple.com/services-account/QH65B2/account/ios/certificate/listCertRequests.action - which is probably used to populate the data you see in `certificate.rb` there. So getting the data would probably mean individual requests per certificate - unless there exists a better endpoint that I missed or misunderstood in general how it works.

**Comment by cturner35** [comment]
Yes, that is the certificate.rb file that I was looking at. 

That requesterEmail could be what I need! I have no idea how to add that call myself in fastlane, so any help you can provide would be awesome.

Thanks!

**Comment by janpio** [comment]
How are you currently using spaceship? Via a fastlane action or directly in a lane?

---

The current `certificates` action that gets all the certificates is implemented here:
https://github.com/fastlane/fastlane/blob/f125b0c4d1e22a30a9b8ba8d9194be6ee9c8728f/spaceship/lib/spaceship/portal/portal_client.rb#L564-L575 (found via searching for `listCertRequests.action` in the codebase)

You would probably want to duplicate that and convert it into `certificate` (singular) that makes a request to `getCertificate.action` with the correct headers and data. (Use your browser's dev tools to find out what is being sent to Apple when getting the list of certificates, and when you look at the detail data of one - those are the two relevant requests). 

Then also see what tests there are for `listCertRequests.action` (same search results as before) and duplicate those as well so this is well tested.

After that I am lost as well for now: No idea how to integrate this with `certificate.rb` which seems to be the `Certificate` class, but also has an `all()` method that returns all certificates of an account... So you possible have to refactor that somehow, or introduce a new `SingleCertificate` that mirrors some of the functionality or implements `Certificate` and overwrites some stuff. Here it gets messy ;)

**Comment by cturner35** [comment]
I am using spaceship directly in a lane.

So you're saying I should add a new method to the portal_client file and piggy back off of how certificates is?

**Comment by janpio** [comment]
That's at least how I would start - fork `fastlane`, try to implement stuff locally, then create a PR here to include it. It might be possible to do some of this in a lane itself, I don't really have an overview what people are doing with spaceship - reading through a few dozen issues that mention it might give you an idea.

**Comment by cturner35** [comment]
Thanks for the help!

I need the email address for all of them.

**Comment by janpio** [comment]
Then it might be worth first to continue looking if there is not a better API endpoint that returns that data for all of them at a time instead of having to do individual requests.

But if not, you could go into `certificates()` above and iterate through the result and add the data by requesting each one individually (hide this behind a new flag or option to make sure it is only done when really needed).
