### ISSUE TITLE
[spaceship] Add support for iOS app bundles

### ISSUE THREAD

**Issue by max-ott** [fastlane/fastlane#13826]
### Feature Request
Currently support for iOS app bundles is not present with `spaceship`. This issue is to check if there is interested/need in the community and also see if we have devs/people interested in working on this.

#### Motivation Behind Feature
App bundles are still a great marketing tool for a lot of (game) developers. Adding support via `spaceship` would one of the few last missing areas into the fastlane universe.

#### Feature Description

- [x] Create new app bundles (#2071)
- Metadata (name, description, marketing url)
- Availability and price (Cleared for sale, price)
- General information (App icon)
- Adding new languages
- _Probably a lot of other things I forgot_

**Comment by janpio** [comment]
Just stumbled over some code we have to _not_ support it right now: https://github.com/fastlane/fastlane/blob/cd88359fa9b6772f91a31a290f8f3c790a716dc0/spaceship/lib/spaceship/tunes/app_version.rb#L278 ;)

**Comment by janpio** [comment]
App bundle support would be nice.

**Comment by max-ott** [comment]
This can indeed be closed, as basic support got added via my PR over at https://github.com/fastlane/fastlane/pull/14292
