### ISSUE TITLE
[match] How to use match with gitlab CE

### ISSUE THREAD

**Issue by JadianZheng** [fastlane/fastlane#13820]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

How to use `match` with gitlab CE？

#### Question Description

I try to creat a private project in own gitlab CE, and run as the document say.
But as the follow show, it cycled run. 

I found the `code signing identity` had created in my account, but the gitlab project has nothing change.

```shell
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) XXXX "XXX DEVELOPMENT LIMITED" (Company/Organization)
2) XXXX "XXX TECHNOLOGY CO., LIMITED" (Company/Organization)
2
[11:38:32]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+--------------------------------------+
|               Summary for cert 2.108.0               |
+---------------+--------------------------------------+
| development   | true                                 |
| force         | true                                 |
| username      | xxx@xxx.com                       |
| keychain_path | /Users/xxx/Library/Keychains/log  |
|               | in.keychain-db                       |
| platform      | ios                                  |
+---------------+--------------------------------------+

[11:38:32]: Starting login with user 'xxx@xxx.com'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) XXXX "XXX DEVELOPMENT LIMITED" (Company/Organization)
2) XXXX "XXX TECHNOLOGY CO., LIMITED" (Company/Organization)
.......
```

**Comment by janpio** [comment]
Seems the account you are using is part of multiple teams. `match` has 2 params to enable it to decide which one to use:

team_id = The ID of your Developer Portal team if you're in multiple teams
team_name = The name of your Developer Portal team if you're in multiple teams

https://docs.fastlane.tools/actions/match/#parameters
