### ISSUE TITLE
In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. There is an error for 1 of your localizations.

### ISSUE THREAD

**Issue by jacobjiangwei** [fastlane/fastlane#13832]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I use fastlane deliver to upload screenshot, I download via fastlane deliver and commit into code, so it definitely match apple requirement, it's DPI 72

But sometime it failed in jenkins slave.

```
INFO [2018-12-06 08:47:03.21]: Starting with the upload of screenshots...
[✔] Activating languages de-DE, en-US, es-ES, es-MX, fr-CA, fr-FR, it, ja, pt-BR, zh-Hans, zh-Hant... 
INFO [2018-12-06 08:47:11.38]: Uploading 18 screenshots for language de-DE
INFO [2018-12-06 08:47:11.38]: Uploading './screenshots/de-DE/1_ipadPro_1.iPad_1.png'...
INFO [2018-12-06 08:47:21.52]: Uploading './screenshots/de-DE/1_iphone65_1.iPhoneX1.png'...
INFO [2018-12-06 08:47:30.01]: Uploading './screenshots/de-DE/1_iphone6Plus_1.6plus1.png'...
INFO [2018-12-06 08:47:38.47]: Uploading './screenshots/de-DE/2_ipadPro_2.iPad_2.png'...
INFO [2018-12-06 08:47:50.26]: Uploading './screenshots/de-DE/2_iphone65_2.iPhoneX2.png'...
INFO [2018-12-06 08:48:01.22]: Uploading './screenshots/de-DE/2_iphone6Plus_2.6plus2.png'...
INFO [2018-12-06 08:48:08.90]: Uploading './screenshots/de-DE/3_ipadPro_3.iPad_3.png'...
INFO [2018-12-06 08:48:18.79]: Uploading './screenshots/de-DE/3_iphone65_3.iPhoneX3.png'...
INFO [2018-12-06 08:48:28.64]: Uploading './screenshots/de-DE/3_iphone6Plus_3.6plus3.png'...
INFO [2018-12-06 08:48:35.29]: Uploading './screenshots/de-DE/4_ipadPro_4.iPad_4.png'...
INFO [2018-12-06 08:48:55.61]: Uploading './screenshots/de-DE/4_iphone65_4.iPhoneX4.png'...
INFO [2018-12-06 08:49:11.97]: Uploading './screenshots/de-DE/4_iphone6Plus_4.6plus4.png'...
INFO [2018-12-06 08:49:23.72]: Uploading './screenshots/de-DE/5_ipadPro_5.iPad_5.png'...
INFO [2018-12-06 08:49:33.16]: Uploading './screenshots/de-DE/5_iphone65_5.iPhoneX5.png'...
INFO [2018-12-06 08:49:40.82]: Uploading './screenshots/de-DE/5_iphone6Plus_5.6plus5.png'...
INFO [2018-12-06 08:49:47.08]: Uploading './screenshots/de-DE/6_ipadPro_6.iPad_6.png'...
INFO [2018-12-06 08:49:54.69]: Uploading './screenshots/de-DE/6_iphone65_6.iPhoneX6.png'...
INFO [2018-12-06 08:50:02.05]: Uploading './screenshots/de-DE/6_iphone6Plus_6.6plus6.png'...
[✔] Saving changes 
INFO [2018-12-06 08:50:23.80]: Uploading 18 screenshots for language en-US
INFO [2018-12-06 08:50:23.80]: Uploading './screenshots/en-US/1_ipadPro_1.iPad_1.png'...
INFO [2018-12-06 08:50:35.21]: Uploading './screenshots/en-US/1_iphone65_1.iPhoneX1.png'...
INFO [2018-12-06 08:50:44.16]: Uploading './screenshots/en-US/1_iphone6Plus_1.6plus1.png'...
INFO [2018-12-06 08:50:51.92]: Uploading './screenshots/en-US/2_ipadPro_2.iPad_2.png'...
INFO [2018-12-06 08:51:04.02]: Uploading './screenshots/en-US/2_iphone65_2.iPhoneX2.png'...
INFO [2018-12-06 08:51:14.02]: Uploading './screenshots/en-US/2_iphone6Plus_2.6plus2.png'...
INFO [2018-12-06 08:51:24.97]: Uploading './screenshots/en-US/3_ipadPro_3.iPad_3.png'...
INFO [2018-12-06 08:51:34.08]: Uploading './screenshots/en-US/3_iphone65_3.iPhoneX3.png'...
INFO [2018-12-06 08:51:43.03]: Uploading './screenshots/en-US/3_iphone6Plus_3.6plus3.png'...
INFO [2018-12-06 08:51:50.88]: Uploading './screenshots/en-US/4_ipadPro_4.iPad_4.png'...
INFO [2018-12-06 08:52:15.48]: Uploading './screenshots/en-US/4_iphone65_4.iPhoneX4.png'...
INFO [2018-12-06 08:52:29.56]: Uploading './screenshots/en-US/4_iphone6Plus_4.6plus4.png'...
INFO [2018-12-06 08:52:41.92]: Uploading './screenshots/en-US/5_ipadPro_5.iPad_5.png'...
INFO [2018-12-06 08:52:52.40]: Uploading './screenshots/en-US/5_iphone65_5.iPhoneX5.png'...
INFO [2018-12-06 08:53:02.18]: Uploading './screenshots/en-US/5_iphone6Plus_5.6plus5.png'...
INFO [2018-12-06 08:53:09.47]: Uploading './screenshots/en-US/6_ipadPro_6.iPad_6.png'...
INFO [2018-12-06 08:53:15.11]: Uploading './screenshots/en-US/6_iphone65_6.iPhoneX6.png'...
INFO [2018-12-06 08:53:21.36]: Uploading './screenshots/en-US/6_iphone6Plus_6.6plus6.png'...
[✔] Saving changes 
INFO [2018-12-06 08:53:39.84]: Uploading 18 screenshots for language es-ES
INFO [2018-12-06 08:53:39.84]: Uploading './screenshots/es-ES/1_ipadPro_1.iPad_1.png'...
INFO [2018-12-06 08:53:51.61]: Uploading './screenshots/es-ES/1_iphone65_1.iPhoneX1.png'...
INFO [2018-12-06 08:53:56.73]: Uploading './screenshots/es-ES/1_iphone6Plus_1.6plus1.png'...
INFO [2018-12-06 08:54:05.15]: Uploading './screenshots/es-ES/2_ipadPro_2.iPad_2.png'...
INFO [2018-12-06 08:54:21.14]: Uploading './screenshots/es-ES/2_iphone65_2.iPhoneX2.png'...
INFO [2018-12-06 08:54:29.46]: Uploading './screenshots/es-ES/2_iphone6Plus_2.6plus2.png'...
INFO [2018-12-06 08:54:35.70]: Uploading './screenshots/es-ES/3_ipadPro_3.iPad_3.png'...
INFO [2018-12-06 08:54:43.75]: Uploading './screenshots/es-ES/3_iphone65_3.iPhoneX3.png'...
INFO [2018-12-06 08:54:50.50]: Uploading './screenshots/es-ES/3_iphone6Plus_3.6plus3.png'...
INFO [2018-12-06 08:54:56.81]: Uploading './screenshots/es-ES/4_ipadPro_4.iPad_4.png'...
INFO [2018-12-06 08:55:15.16]: Uploading './screenshots/es-ES/4_iphone65_4.iPhoneX4.png'...
INFO [2018-12-06 08:55:29.52]: Uploading './screenshots/es-ES/4_iphone6Plus_4.6plus4.png'...
INFO [2018-12-06 08:55:46.99]: Uploading './screenshots/es-ES/5_ipadPro_5.iPad_5.png'...
INFO [2018-12-06 08:55:53.06]: Uploading './screenshots/es-ES/5_iphone65_5.iPhoneX5.png'...
INFO [2018-12-06 08:56:00.26]: Uploading './screenshots/es-ES/5_iphone6Plus_5.6plus5.png'...
INFO [2018-12-06 08:56:05.90]: Uploading './screenshots/es-ES/6_ipadPro_6.iPad_6.png'...
INFO [2018-12-06 08:56:12.91]: Uploading './screenshots/es-ES/6_iphone65_6.iPhoneX6.png'...
INFO [2018-12-06 08:56:19.41]: Uploading './screenshots/es-ES/6_iphone6Plus_6.6plus6.png'...
[✔] Saving changes 
INFO [2018-12-06 08:56:40.91]: Uploading 18 screenshots for language es-MX
INFO [2018-12-06 08:56:40.91]: Uploading './screenshots/es-MX/1_ipadPro_1.iPad_1.png'...
INFO [2018-12-06 08:56:51.53]: Uploading './screenshots/es-MX/1_iphone65_1.iPhoneX1.png'...
INFO [2018-12-06 08:57:06.42]: Uploading './screenshots/es-MX/1_iphone6Plus_1.6plus1.png'...
INFO [2018-12-06 08:57:21.70]: Uploading './screenshots/es-MX/2_ipadPro_2.iPad_2.png'...
INFO [2018-12-06 08:57:35.20]: Uploading './screenshots/es-MX/2_iphone65_2.iPhoneX2.png'...
INFO [2018-12-06 08:57:47.34]: Uploading './screenshots/es-MX/2_iphone6Plus_2.6plus2.png'...
INFO [2018-12-06 08:57:55.07]: Uploading './screenshots/es-MX/3_ipadPro_3.iPad_3.png'...
INFO [2018-12-06 08:58:01.67]: Uploading './screenshots/es-MX/3_iphone65_3.iPhoneX3.png'...
INFO [2018-12-06 08:58:11.41]: Uploading './screenshots/es-MX/3_iphone6Plus_3.6plus3.png'...
INFO [2018-12-06 08:58:18.85]: Uploading './screenshots/es-MX/4_ipadPro_4.iPad_4.png'...
INFO [2018-12-06 08:58:39.61]: Uploading './screenshots/es-MX/4_iphone65_4.iPhoneX4.png'...
INFO [2018-12-06 08:58:52.09]: Uploading './screenshots/es-MX/4_iphone6Plus_4.6plus4.png'...
INFO [2018-12-06 08:59:05.91]: Uploading './screenshots/es-MX/5_ipadPro_5.iPad_5.png'...
INFO [2018-12-06 08:59:16.03]: Uploading './screenshots/es-MX/5_iphone65_5.iPhoneX5.png'...
INFO [2018-12-06 08:59:23.99]: Uploading './screenshots/es-MX/5_iphone6Plus_5.6plus5.png'...
INFO [2018-12-06 08:59:31.83]: Uploading './screenshots/es-MX/6_ipadPro_6.iPad_6.png'...
INFO [2018-12-06 08:59:40.27]: Uploading './screenshots/es-MX/6_iphone65_6.iPhoneX6.png'...
INFO [2018-12-06 08:59:47.08]: Uploading './screenshots/es-MX/6_iphone6Plus_6.6plus6.png'...
[✔] Saving changes 
INFO [2018-12-06 09:00:07.38]: Uploading 18 screenshots for language fr-CA
INFO [2018-12-06 09:00:07.38]: Uploading './screenshots/fr-CA/1_ipadPro_1.iPad_1.png'...
INFO [2018-12-06 09:00:19.32]: Uploading './screenshots/fr-CA/1_iphone65_1.iPhoneX1.png'...
INFO [2018-12-06 09:00:31.81]: Uploading './screenshots/fr-CA/1_iphone6Plus_1.6plus1.png'...
INFO [2018-12-06 09:00:39.08]: Uploading './screenshots/fr-CA/2_ipadPro_2.iPad_2.png'...
INFO [2018-12-06 09:00:50.23]: Uploading './screenshots/fr-CA/2_iphone65_2.iPhoneX2.png'...
INFO [2018-12-06 09:01:06.64]: Uploading './screenshots/fr-CA/2_iphone6Plus_2.6plus2.png'...
INFO [2018-12-06 09:01:17.68]: Uploading './screenshots/fr-CA/3_ipadPro_3.iPad_3.png'...
INFO [2018-12-06 09:01:30.64]: Uploading './screenshots/fr-CA/3_iphone65_3.iPhoneX3.png'...
INFO [2018-12-06 09:01:38.97]: Uploading './screenshots/fr-CA/3_iphone6Plus_3.6plus3.png'...
INFO [2018-12-06 09:01:47.17]: Uploading './screenshots/fr-CA/4_ipadPro_4.iPad_4.png'...
INFO [2018-12-06 09:02:06.93]: Uploading './screenshots/fr-CA/4_iphone65_4.iPhoneX4.png'...
INFO [2018-12-06 09:02:23.83]: Uploading './screenshots/fr-CA/4_iphone6Plus_4.6plus4.png'...
INFO [2018-12-06 09:02:44.18]: Uploading './screenshots/fr-CA/5_ipadPro_5.iPad_5.png'...
INFO [2018-12-06 09:02:55.91]: Uploading './screenshots/fr-CA/5_iphone65_5.iPhoneX5.png'...
INFO [2018-12-06 09:03:12.19]: Uploading './screenshots/fr-CA/5_iphone6Plus_5.6plus5.png'...
INFO [2018-12-06 09:03:21.94]: Uploading './screenshots/fr-CA/6_ipadPro_6.iPad_6.png'...
INFO [2018-12-06 09:03:33.79]: Uploading './screenshots/fr-CA/6_iphone65_6.iPhoneX6.png'...
INFO [2018-12-06 09:03:40.72]: Uploading './screenshots/fr-CA/6_iphone6Plus_6.6plus6.png'...
[✔] Saving changes 
INFO [2018-12-06 09:04:00.69]: Uploading 18 screenshots for language fr-FR
INFO [2018-12-06 09:04:00.69]: Uploading './screenshots/fr-FR/1_ipadPro_1.iPad_1.png'...
INFO [2018-12-06 09:05:04.09]: Uploading './screenshots/fr-FR/1_iphone65_1.iPhoneX1.png'...
INFO [2018-12-06 09:05:14.42]: Uploading './screenshots/fr-FR/1_iphone6Plus_1.6plus1.png'...
INFO [2018-12-06 09:05:22.78]: Uploading './screenshots/fr-FR/2_ipadPro_2.iPad_2.png'...
INFO [2018-12-06 09:05:34.02]: Uploading './screenshots/fr-FR/2_iphone65_2.iPhoneX2.png'...
INFO [2018-12-06 09:05:45.21]: Uploading './screenshots/fr-FR/2_iphone6Plus_2.6plus2.png'...
INFO [2018-12-06 09:05:54.39]: Uploading './screenshots/fr-FR/3_ipadPro_3.iPad_3.png'...
INFO [2018-12-06 09:06:05.76]: Uploading './screenshots/fr-FR/3_iphone65_3.iPhoneX3.png'...
INFO [2018-12-06 09:06:16.55]: Uploading './screenshots/fr-FR/3_iphone6Plus_3.6plus3.png'...
INFO [2018-12-06 09:06:23.60]: Uploading './screenshots/fr-FR/4_ipadPro_4.iPad_4.png'...
INFO [2018-12-06 09:06:47.16]: Uploading './screenshots/fr-FR/4_iphone65_4.iPhoneX4.png'...
INFO [2018-12-06 09:06:59.91]: Uploading './screenshots/fr-FR/4_iphone6Plus_4.6plus4.png'...
INFO [2018-12-06 09:07:14.93]: Uploading './screenshots/fr-FR/5_ipadPro_5.iPad_5.png'...
INFO [2018-12-06 09:07:22.69]: Uploading './screenshots/fr-FR/5_iphone65_5.iPhoneX5.png'...
INFO [2018-12-06 09:07:35.34]: Uploading './screenshots/fr-FR/5_iphone6Plus_5.6plus5.png'...
INFO [2018-12-06 09:07:43.74]: Uploading './screenshots/fr-FR/6_ipadPro_6.iPad_6.png'...
INFO [2018-12-06 09:07:53.16]: Uploading './screenshots/fr-FR/6_iphone65_6.iPhoneX6.png'...
INFO [2018-12-06 09:07:58.77]: Uploading './screenshots/fr-FR/6_iphone6Plus_6.6plus6.png'...
[⠴] Saving changes Potential server error received: 'In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. [fr-FR]: In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 5)...
[⠴] Saving changes Potential server error received: 'In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. [fr-FR]: In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 5)...
[⠼] Saving changes 
Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. [fr-FR]: In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. There is an error for 1 of your localizations.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09In%20order%20to%20save%20your%20changes%2C%20all%20s%20must%20be%20a%20.jpeg%2C%20.jpg%2C%20or%20.png%20file%20that%20is%20%40%40DIMENSION_VALUE%40%40%20pixels%2C%20at%20least%2072%20DPI%2C%20and%20in%20the%20RGB%20color%20space.%20%5Bfr-FR%5D%3A%20In%20order%20to%20save%20your%20changes%2C%20all%20s%20must%20be%20a%20.jpeg%2C%20.jpg%2C%20or%20.png%20file%20that%20is%20%40%40DIMENSION_VALUE%40%40%20pixels%2C%20at%20least%2072%20DPI%2C%20and%20in%20the%20RGB%20color%20space.%20There%20is%20an%20error%20for%201%20of%20your%20localizations.+repo:fastlane/fastlane
[⠹] Saving changes ERROR [2018-12-06 09:08:39.84]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
Did you mean?  tap
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::Tunes::PotentialServerError)
	In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. [fr-FR]: In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. There is an error for 1 of your localizations.
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/tunes/tunes_client.rb:439:in `block in update_app_version!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1436:in `with_tunes_retry'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/tunes/tunes_client.rb:432:in `update_app_version!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/tunes/app_version.rb:403:in `save!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/upload_screenshots.rb:73:in `block in upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/upload_screenshots.rb:49:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/upload_screenshots.rb:49:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/runner.rb:38:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.109.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2018-12-06**
</details>

**Comment by jacobjiangwei** [comment]
I searched a lot places, some were old, resolved in 2015

I don't understand, which part which file is wrong?

**Comment by janpio** [comment]
The last file in the output before you got the error should be the culprit:

> INFO [2018-12-06 09:07:58.77]: Uploading './screenshots/fr-FR/6_iphone6Plus_6.6plus6.png'...

But: This upload method is marked as "flaky" in the code itself, which is also why there is this retry logic. You could probably fix this by just retrying the upload a bit later.

**Comment by pparmaei** [comment]
same. 
This has been happening with a higher frequency for us lately. But seems like the only solution would be to retry.
This is a false negative, there is usually nothing wrong with the screenshot.

**Comment by roostr** [comment]
I've tried submitting 4 times today, and I hit this each time. It's always stopping on a different file, which is evidence that it's a server problem, not because of an error in a file.

I'm guessing the only thing that could be done about it is adding a graceful retry, or just trying to submit again later.

**Comment by janpio** [comment]
We already have 3 tries with 10 sec pause:
https://github.com/fastlane/fastlane/blob/cd88359fa9b6772f91a31a290f8f3c790a716dc0/spaceship/lib/spaceship/tunes/tunes_client.rb#L1435-L1455

To make sure our error handling is not broken here, can you please look for your [spaceship logs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md#logging) of a failing run and upload the relevant portion (failing requests with a few working before). Thanks!

**Comment by roostr** [comment]
I looked through those logs, and I can see the errors. If there are specific pieces you'd like me to upload, I can share them, but I'm reluctant to paste in whole lines because I can't tell which values are private/need redacted.

My deliver finally worked! (325 screenshots total). I've heard from other iOS developers today that App Store Connect servers were experiencing problems, so hopefully this was just a transient issue.

Whenever I saw the error, it would always error out three times in a row. There was never a time when it failed on a file once or twice and then succeeded. And I was never changing the screenshot files between attempts. That makes me think that perhaps the issue was that they had a few servers that were running a bad version of their backend software, and if the load balancer sent me to a bad server, then I was bound to fail? Perhaps a longer pause could have solved it (5 min instead of 10 sec), but honestly I don't think it's worth trying to come up with a better retry strategy if this turns out to be a one-day transient issue.

**Comment by janpio** [comment]
The failing requests would be nice, maybe 1 or 2 before. The private data is in the cookies only usually, I think when uploading files there is not much stuff in the POST body - so the interesting thing here are the responses.

**Comment by jacobjiangwei** [comment]
so is there some data can show this code's failure rate? If this tool has high failure rate on upload screenshot, we would consider not using this feature.

**Comment by janpio** [comment]
The code is not failing, Apple's API is @jacobjiangwei. This means that the normal web UI is probably also returning errors. Usually this is quite stable though. If it was failing for all users of fastlane all the time, you would see hundreds of issues here every day.

---

If this error is "image bound", meaning that only this one specific image is erroring out right now and will keep doing so, it might be possible to just skip this one image and point it out to the user for manual handling (uploading via web UI or some specific, not yet implemented, command that uploads just this one image) OR reimplement the code to just work on a queue of images to be uploaded, and just skip a failing image and continue with all the others and try at the end again.

What happens if you just restart the process - does it fail for the exact same image and all the others are reuploaded just fine?

**Comment by janpio** [comment]
It might help if you could post (or email me to piotrowski@gmail.com) your [spaceship logs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md#logging), best of multiple runs that did fail.

**Comment by jacobjiangwei** [comment]
@janpio I did send you

**Comment by liscio** [comment]
Hey all—I had the same problem over the weekend, and I think I got a decent fix for it (or, at least the start of one.)

What appears to happen here is that one of the screenshot uploads fails quietly, and then the save operation reports a failure. This is a huge problem when—like me—you have a metric buttload (320) of screenshots to upload and don't want to keep restarting the process on failure.

So instead, the uploads need to be retried instead of the save operation. I decided to "batch" the saves by device in every language. This worked well for me with 4 screenshots per device. I think that saving on every language would not be ideal for me because each retry would require re-uploading 40 shots on each attempt.

This works well enough, but could be done better. For instance, I would prefer if the save operation didn't retry itself for 3 times before I finally catch the error and re-upload.

You can see how I fixed this here: https://github.com/fastlane/fastlane/compare/master...liscio:master

Unfortunately I don't have the bandwidth right now to massage this PR and write tests for it right now. Hopefully my fork will help someone else get un-stuck when facing this problem!

**Comment by liscio** [comment]
@janpio Hmm—I didn't even notice I could check whether the uploads could possibly fail or fire exceptions. That would allow us to instead maintain the retry logic inside the individual upload_screenshot functions rather than re-trying batches like I currently have it set up.

My "understanding" is quite limited, unfortunately. I based my approach on my own experiences with Apple's web UI. Sometimes I would upload some screenshots and the UI would appear to stall—with one screenshot less than I dragged. Only when I hit 'Save' did I get a notice that one of the screenshot uploads failed.

**Comment by janpio** [comment]
I have no idea if we actually _can_ catch the failing upload in our code currently, but that is where I will start my mitigation try. I am also not sure if just retrying the upload would really work - but we will see.

If your web UI observations match @jacobjiangwei 's logfiles, even better. And what you described, sounds like it quite a lot. You can check your own logfiles in `/tmp`, they all begin with `spaceship` and have a timestamp in the filename (to connect the ones that belong together). It could simply look for the failing image upload (status 500) and then look at the following POST calls to save the app - which failed multiple times.

**Comment by liscio** [comment]
@janpio That is mostly correct, yes.

Unfortunately I cannot control whether `save` retries or not—that retry logic is handled internally. 

So I the exception that eventually fires after the `save` command fails for the 3rd time. It would be better if we could stop the save call from retrying so that it just re-uploads right away.

**Comment by jacobjiangwei** [comment]
Thanks for the digging into this issue.

Is there something i can help with?

发自我的 iPhone

**Comment by janpio** [comment]
Thanks for asking: The one thing that might help, would be a Charles session of an upload that is failing. Your logfiles already helped _a lot_ as you can see above, but having the full headers and bodies of the requests might help to find a proper solution: https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md#setting-up-charles-web-proxy

**Comment by jacobjiangwei** [comment]
@janpio but you said it failed while upload one single screenshot
why not just add retry mechanism for every screenshots?

I have successfully delivered sometimes, not reproducible every time

**Comment by janpio** [comment]
> but you said it failed while upload one single screenshot
> why not just add retry mechanism for every screenshots?

That is exactly what I suggested above and will tackle as soon as possible.

> I have successfully delivered sometimes, not reproducible every time

Ok, no hurry - maybe just set up Charles once so it is easy to activate when you are trying to deliver next time.

**Comment by jacobjiangwei** [comment]
> > but you said it failed while upload one single screenshot
> > why not just add retry mechanism for every screenshots?
> 
> That is exactly what I suggested above and will tackle as soon as possible.
> 
> > I have successfully delivered sometimes, not reproducible every time
> 
> Ok, no hurry - maybe just set up Charles once so it is easy to activate when you are trying to deliver next time.

I tried your tools.
The tutorial can work on appleconnect.apple.com

but when the fastlane works, I don't see it's being tracked in Charles.

Do you know why? How?

**Comment by janpio** [comment]
Did you set the environment variable `SPACESHIP_DEBUG` to some value (e.g. `=1`) before calling `bundle exec fastlane`?
https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md#compare-the-api-requests
This is required so spaceship uses the proxy your are running.

**Comment by jacobjiangwei** [comment]
i tried a couple of times, all failed but charles timeout 30 minutes
i buy charles, then it never failed

so frustrating

**Comment by janpio** [comment]
Oh wow, that is terrible. On the other hand - Charles is an awesome tool. I am sure you will get your money's worth over time. (Does your upload process take more than 30 minutes?)

**Comment by jacobjiangwei** [comment]
yes, more than 30 minutes in China

but anyway, it's success now. damn network
