### ISSUE TITLE
Support export IPA file that can  be installed on the iPhone Simulator

### ISSUE THREAD

**Issue by Neojoke** [fastlane/fastlane#13835]
Hi ~
  I want to find a way that can use fastlane export IPA file can be installed on the iPhone Simulator.
  Can someone help me?

**Comment by johnknapprs** [comment]
You don't want an ipa file as those are specifically for devices. 
 https://en.m.wikipedia.org/wiki/.ipa 

You want to generate a .app package.  Should be as simple as setting the sdk target to `iphonesimulator`. 

You didn't mention your use case, but you'll likely want to zip it up as well if you need to transport that data anywhere else.

**Comment by Neojoke** [comment]
@johnknapprs 
I see~
I am using appium to automate the app, and I used xcrun to export IPA files that support x86-64 architecture, And fastlane only export IPA files that support real devices architecture.
At the moment it seems that I just need to find a way to let Appium install the .app file.
