### ISSUE TITLE
Why there is a support for two default .env files?

### ISSUE THREAD

**Issue by Skoti** [fastlane/fastlane#13849]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

From my understanding the purpose of loading _.env_ automatically is to have a _default_ environment which is always loaded - this is cool but why _.env.default_ is loaded automatically as well?

I do not understand the need for using _.env.default_ file. If one wants to have some default environment variables it is reasonable to put them just in one file.
There is no difference whether you will **only** put them in _.env_ or _.env.default_ file - or am I missing something?
There is no option to use _.env_ or _.env.default_ separately so it is the same like keeping all the values from both of these files just in _.env_ which is meant to be a _default_ one by the _dotenv_ authors.

#### Question Description

https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/lib/fastlane/helper/dotenv_helper.rb#L29-L32
Looking at these lines it also means that if one is using two files, then it can lead to a greater confusion. In example if keys in both files are not disjoint then only values from _.env_ for these keys will be loaded which might not be intuitive.
However, like I said above if these are the _default_ values why keeping them in two files which are **always** loaded?

**Comment by janpio** [comment]
> but why .env.default is loaded automatically as well?

Possibly a misunderstanding ~4 years ago when this code was first added:
https://github.com/fastlane/fastlane/commit/a571512ce69dbfe141e48c92fb13597220589fb8#diff-685e939a0c766697a0a7eb8539782195R13 Today changing the behavior ould break backwards compatibility.

Is this causing any actual problems?

**Comment by janpio** [comment]
Yes, the only way to break compatibility would be to do it with the next major release of fastlane.

To close this off, did you encounter any documentation of fastlane switching between the two methods? That we could fix by defaulting to one of the two files and removing the mention of the other already.

**Comment by Skoti** [comment]
Only [here](https://docs.fastlane.tools/advanced/other/#environment-variables).

**Comment by Skoti** [comment]
@joshdholtz I think a warning with an explanation would be nice.
I also don't want to remove it now as it is a breaking change. At least until the next major fastlane release. The warning could also remind that it will use just one file after such a release.
Is that an acceptable solution? Is there a good way to save/remember about it when major release will come?
