### ISSUE TITLE
[spaceship] Implement error handling for `429 too many requests` with body `Rate limit has been exceeded for: testflight|default|APPLE_CONNECT:10464547290` for Testflight requests

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13841]
Logfile via https://github.com/fastlane/fastlane/issues/12845#issuecomment-445042964

```
INFO  [13:31:07]: >> GET providers/105762816/apps/917397071/platforms/ios/trains/2.0.105/builds: [undefined body] 
DEBUG [13:31:07]: << GET providers/105762816/apps/917397071/platforms/ios/trains/2.0.105/builds: 429 Rate limit has been exceeded for: testflight|default|APPLE_CONNECT:10464547290
```

We currently can't do that much about it, but we can display a proper error message and maybe link to an issue that asks for spaceship logfiles so we can understand what was going on _before_ the rate limiting kicked in.

Suggestions?

**Comment by bpollock-vida** [comment]
Proper error message + link  would be 100x helpful since googling 'testflight|default|APPLE_CONNECT:10464547290' doesn't give much.

**Comment by bpollock-vida** [comment]
that's just because it hasn't been addressed
