### ISSUE TITLE
match hanging after 2 factor authentification

### ISSUE THREAD

**Issue by Holbanner** [fastlane/fastlane#13848]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when running match with an account that has 2-factor auth set up, i' prompted to enter the 6 digit code. I do it but then nothing happens, the terminal just hang there.
Nothing is created anywhere. The git repo stays  empty, no cookies are created at ~/.fastlane/spaceship/[email]/cookie

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.109.1"
require 'xcodeproj'

package_name = ENV['PACKAGE_NAME']
itunes_id = ENV['ITUNES_ID']
app_name = ENV['APP_NAME']
team_id = ENV['TEAM_ID']
keystore = ENV['KEYSTORE_PATH']
# xcodeprojpath = "./platforms/ios/" + app_name + ".xcodeproj"

##########################################################
####                                                  ####
####                       IOS                        ####
####                                                  ####
##########################################################

default_platform :ios

platform :ios do

  lane :testMatch do
    match()
  end

end


##########################################################
####                                                  ####
####                    ANDROID                       ####
####                                                  ####
##########################################################
platform :android do

  desc "Build Debug"
  lane :build_debug do
    ionic(
      platform: 'android',
      prod: true,
      release: false
    )
  end

  desc "Build Release : génère un apk signé et un non signé"
  lane :build_release_android do
    ionic(
      platform: 'android',
      prod: true,
      release: true,

      keystore_path: keystore,
      keystore_password: ENV['KEYSTORE_PWD'],
      keystore_alias: ENV['KEY_ALIAS'],
      key_password: ENV['KEYSTORE_PWD']
    )
  end

  desc "Deploy to prod google play"
  lane :prod do
    ionic(
      platform: 'android',
      prod: true,
      release: true,

      keystore_path: keystore,
      keystore_password: ENV['KEYSTORE_PWD'],
      keystore_alias: ENV['KEY_ALIAS'],
      key_password: ENV['KEYSTORE_PWD']
    )
    supply(track: 'production',
          apk: ENV['PATH_TO_APK'])
  end;

  desc "Deploy a new version to the Google Play BETA"
  lane :beta do
    ionic(
      platform: 'android',
      prod: true,
      release: true,

      keystore_path: keystore,
      keystore_password: ENV['KEYSTORE_PWD'],
      keystore_alias: ENV['KEY_ALIAS'],
      key_password: ENV['KEYSTORE_PWD']
    )
    supply(track: 'beta')
  end;

  desc "Deploy a new version to the Google Play ALPHA"
  lane :pushAlpha do
    ionic(
      platform: 'android',
      prod: true,
      release: true,

      keystore_path: keystore,
      keystore_password: ENV['KEYSTORE_PWD'],
      keystore_alias: ENV['KEY_ALIAS'],
      key_password: ENV['KEYSTORE_PWD']
    )
    supply(track: 'alpha')
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
ID=ENV['CUSTOM_APP_ID']

# app_identifier ID # The bundle identifier of your app !!important, configure la signature de l'application
# apple_id "xxxxxx" # Your Apple ID Email address
# team_id "xxxxxx"  # Developer Portal Team ID
# itc_team_id "xxxxxxx" # Your iTunes Connect Team ID



json_key_file "./fastlane/compte-service-publication-google.json" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name ID # nom package de l'app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.109.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-ionic | 0.0.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-ionic     | 0.0.4        |
</details>

*generated on:* **2018-12-07**
</details></pre>
</details>

**Comment by janpio** [comment]
What exact command are you running?
Can you please include the complete output of that command above?
Did this work before for you?

**Comment by Holbanner** [comment]
I kind of managed to pinpoint the cause of my problem.
Since i'm part of multiple teams, I think i got confused by the part of the dock that said to managed the different teams with git branches like this :
match(git_branch: "team1", username: "user@team1.com")
I thought the git_branch option inferred the name of the team or something along the line. Setting the team name in .ENV got me unstuck

**Comment by janpio** [comment]
Yay! Could you describe what settings had gut you stuck though? Because that sounds like something we should probably fix for future uses that make similar assumptions.

**Comment by Holbanner** [comment]
Hi, I thought i add it but it seems i didn't.
I planned to have describe my solution but here is the details of my problem:

i'm trying to run match(type: 'development', username:'xxxxx', team_name:'xxxxxx', git_branch:'xxxxx').
I've tried with this either with the settings directly in the lane as written above, in the match file, in the ENV or from command line.
I need this setup because I'm part of multiple teams and I want manage them via git branches.

I can't give you --capture_output because it gives me an error saying that it's not a command
So here is my terminal output instead

+-----------------------+---------+--------+
|               Used plugins               |
+-----------------------+---------+--------+
| Plugin                | Version | Action |
+-----------------------+---------+--------+
| fastlane-plugin-ionic | 0.0.4   | ionic  |
+-----------------------+---------+--------+

(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
[09:27:55]: You have required a gem, if this is a third party gem, please use `fastlane_require 'xcodeproj'` to ensure the gem is installed locally.
[09:27:55]: ----------------------------------------
[09:27:55]: --- Step: Verifying fastlane version ---
[09:27:55]: ----------------------------------------
[09:27:55]: Your fastlane version 2.109.1 matches the minimum requirement of 2.109.1  ✅
[09:27:55]: ------------------------------
[09:27:55]: --- Step: default_platform ---
[09:27:55]: ------------------------------
[09:27:55]: Driving the lane 'ios testMatch' 🚀
[09:27:55]: -------------------
[09:27:55]: --- Step: match ---
[09:27:55]: -------------------
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
(eval):2: warning: already initialized constant CredentialsManager::AppfileConfig::ID
(eval):2: warning: previous definition of ID was here
[09:27:55]: Successfully loaded '/Users/gilles/workspace/tempWorkspace/m-city/fastlane/Matchfile' 📄
```

+----------------+-------------------------------------+
|     Detected Values from './fastlane/Matchfile'      |
+----------------+-------------------------------------+
| git_url        | git@moovgitlab:moov/certificats.git |
| type           | development                         |
| app_identifier | ["com.moov.mcity"]                  |
| username       | dev@moov-city.fr                    |
| team_name      | moov-City                           |
| git_branch     | moov-City                           |
+----------------+-------------------------------------+


+-----------------------+-------------------------------------+
|                  Summary for match 2.109.1                  |
+-----------------------+-------------------------------------+
| git_url               | git@myGitRepo.git|
| git_branch            | myBranchName                           |
| type                  | development                         |
| storage_mode          | git                                 |
| app_identifier        | ["myAppId"]                  |
| username              | myUserName                    |
| keychain_name         | login.keychain                      |
| keychain_password     | ********                            |
| readonly              | false                               |
| team_name             | myTeamName                           |
| verbose               | false                               |
| force                 | false                               |
| skip_confirmation     | false                               |
| shallow_clone         | false                               |
| clone_branch_directly | false                               |
| force_for_new_devices | false                               |
| skip_docs             | false                               |
| platform              | ios                                 |
+-----------------------+-------------------------------------+

[09:27:55]: Cloning remote git repo...
[09:27:55]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[09:27:55]: Checking out branch moov-City...
[09:27:55]: 🔓  Successfully decrypted certificates repo
[09:27:55]: Verifying that the certificate and profile are still valid on the Dev Portal...
Available session is not valid any more. Continuing with normal login.

Two-step Verification (4 digits code) or Two-factor Authentication (6 digits code) is enabled for account 'dev@moov-city.fr'
More information about Two-step Verification (4 digits code): https://support.apple.com/en-us/HT204152
More information about Two-factor Authentication (6 digits code): https://support.apple.com/en-us/HT204915

Two-factor Authentication (6 digits code) is enabled for account 'dev@moov-city.fr'
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: 905450
```
After entering the code and pressing enter it just hangs there indefinitely
When i thought i had it settle, it was because it prompted me that i had reached the maximum number of dev certificates, so i thought things where going but i had to wait for apple to accepte the removal of older certificats I asked for.Now that it's done i'm back to the hanging part

**Comment by janpio** [comment]
Could you try `match` without any parameters first to make sure it _then_ works? If it does, we can debug what the params are breaking, if it doesn't we have much lees to debug and look at.

**Comment by Holbanner** [comment]
ok, so for whatever reason this seem to have settle things.
`match` alone worked. Then rerunning with params worked. So my guess is that you need to init the git repo with the first match before using branches

**Comment by janpio** [comment]
Hm, that would be interesting and a bit unexpected. Can you maybe try again with a new repo to help us debug this?

**Comment by Holbanner** [comment]
Sure, I'll come back to you as soon as I find time to try this
