### ISSUE TITLE
React Native: snapshot/screengrab support

### ISSUE THREAD

**Issue by Cnordbo** [fastlane/fastlane#13859]
(Issue opened by request from https://github.com/fastlane/docs/issues/626)

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description - (Only tested Screenshot (iOS), not Screengrab (Android))
Setting up RN build/release lanes with existing guides works fine out of the box! :) (standard guides)

Having huge issues with screenshot, which was the entire reason for looking at fastlane to begin with.
Would love it if there were to be a how-to on supporting this, without introducing invisible hacks that depends on libraries like redux and therefore also react navigation with redux (which seems to be a deprecated feature). Or removing accessible features within the app.

As stated elsewhere, i added the prop `testID="<name or key>"` to the elements, especially those where which i would interact with. I also tried decorating it with `accessible={false}`. 

Sometimes it says "Timestamped event matching error failed to find matching element", other times it seems to capture an element, but instead of refering to the element by the testID, it seems to create its own identifier which just contains all the text.

I think this is more of a recording issue, but since it was asked to be created as an issue here by one of the contributors, i did so. 

### Workaround
Its mentioned elsewhere to create a nearly invisible "button" which gets tapped, and updates the redux navigation state. By doing so, you can just refer to the same element, and tap it on each screen to go to the appropriate screen afterwards. 

This might work for redux users, but not all apps use redux. And i dont believe that adding the "complexity" of redux to the app, for the benefit of trying to use this feature. 

React-Navigation will also stop supporting this behavior in the next version of React-Navigation: 
https://reactnavigation.org/docs/en/redux-integration.html

### Workaround 2 (Have not managed to get this to work myself - but suggested somewhere)
Set `accessible={false}` on elements which gives you a hard time. 
Applications are actually required to be accessible in Norway (and from 1.1.2019 - The entire EU). 
Hacking the app, and thereby making it less accessible is therefore not a wanted operation. Neither is making this change back and forth everytime a new screenshot is to be taken. 

I can see that i would be a well invested effort in the later game of any application (adding and removing accessibilty for the sake of the screenshots) - But in the early stages of the app, screenshots might rapidly change - and therefore it would be very time consuming if we were to do this "dance" everytime. 

### Reason for using screenshot: 
Localization of app and framing w/ localized text.

### Environment

Issue is not directly related to anything fastlane, as i dont get far enough in the setup.

**Comment by janpio** [comment]
What exactly is the problem - taking the screenshots or getting the app into the state to take a screenshot of (running the UI test)?

**Comment by Cnordbo** [comment]
Recording the UI test is the actual problem. Which is why i put a disclaimer here saying: 

> I think this is more of a recording issue, but since it was asked to be created as an issue here by one of the contributors, i did so.

My original request was for the docs to be updated with a how-to, as i, and others, seem to struggle setting this up. As there are none, and i might have missed something.

**Comment by janpio** [comment]
We are very interested in supporting all kinds of apps, which is why I am asking questions and trying to understand the problem. I have never touched a React Native app before, so I might not know things.

Are you trying to follow one of our normal screenshots guides?
https://docs.fastlane.tools/getting-started/ios/screenshots/
https://docs.fastlane.tools/getting-started/android/screenshots/
https://docs.fastlane.tools/actions/snapshot/
https://docs.fastlane.tools/actions/screengrab/

If so, at which step are you currently experiencing problem? 

From your above description I understand you have integrated the respective tool just fine, but are now having problems to write the code that interact with your UI, correct? The elements you want to tap are not recognized, also correct? Can you share some of the code you have right now that is _not_ working?

**Comment by janpio** [comment]
Ok, such problem I do know from working with Cordova/Ionic applications. There the recording function also is pretty useless, as it just doesn't properly recognize the elements in the UI, and what it recognizes doesn't work on replay later.

I "fixed" this by learning how to use `XCUIApplication` with Ionic apps: giving explicit `id` and/or `id` attributes to objects and using a `forceTapElement`, [a function I got from StackOverflow](https://stackoverflow.com/a/33534187/252627): `app.buttons["close add"].forceTapElement()`. That works pretty often.

Googling for "react native XCUIApplication" gives some promising results, or is this what you are/were already doing?

**Comment by Cnordbo** [comment]
Heres a repro for reproducing the error in its simplest form.
https://github.com/Cnordbo/RNFailedUITesting

I could always program the entire UI navigation myself using the ID buttons - BUT, they seem to appear in different subclasses / objects (as you demonstrate when using `app.buttons["close add"]`,  so it might be hard navigating an unknown structure. Maybe google has a few more answers there. :)

**Comment by Cnordbo** [comment]
Got it working, your tip using your own setup with ionic really helped! Thanks @janpio !

I updated the repository to, hopefully, explain how to do screenshots using react-native! 
https://github.com/Cnordbo/React-Native-Fastlane-Screenshot

**Comment by janpio** [comment]
Awesome 💃
