### ISSUE TITLE
`--capture_output` is only implemented for some commands

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13862]
Issue template:
```
##### Complete output when running fastlane, including the stack trace and command used
<!-- You can use: `--capture_output` as the last commandline argument to get that collected for you -->
```

But `--capture_output` is only implemented for some commands, so this regularly creates confusion. We should find a better way to communicate or implement this.

**Comment by jsorge** [comment]
Yep, this bit me on a snapshot issue I'm trying to figure out.
