### ISSUE TITLE
how to delete an app from itunes connect?

### ISSUE THREAD

**Issue by MTBug** [fastlane/fastlane#13870]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
spaceship

#### Question Description

The new version of iTunes Connect already supports removing apps, Any corresponding  API to  implement this function in fastlane?
like this:
```
app = Spaceship::Tunes::Application.find('xxx')    
app.delete!
```

**Comment by joshdholtz** [comment]
@MTBug Heyyy 👋  I was actually not aware that the new version of App Store Connect allow you to do this 😱 This does use the new API which we don't fully support yet but we should be able to add this in somehow. I will add this to my list 💪

**Comment by MTBug** [comment]
@joshdholtz Good luck, Looking forward to your completion 💪

**Comment by wdcurry** [comment]
Note: you will not be able to re-use the same bundleID again though (as far as I know at present). You **can** resuse the released app name string, just not the bundleID. So for logically-minded folks who think a workflow like: app causing issues, wipe app, reinstall same app, carry on ... may help, it won't, not directly.
