### ISSUE TITLE
resign fail on versions fastlane 2.110.0 ,our app appear crash

### ISSUE THREAD

**Issue by tang814496917** [fastlane/fastlane#13875]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@tang814496917 Heyyyy 👋  If you could provide some more into with output of you running `resign` and your `fastlane env` that would be great 😊 Otherwise there isn't much for us to look into
