### ISSUE TITLE
[spaceship] Body is logged as not-really-JSON

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13876]
Although we use `.to_json` on the body:
https://github.com/fastlane/fastlane/blob/cd88359fa9b6772f91a31a290f8f3c790a716dc0/spaceship/lib/spaceship/client.rb#L775

We get something like that in the logs:
```
DEBUG [22:06:25]: << GET ra/apps/715886894/overview: 200 {"data"=>{"sectionErrorKeys"=>[], "sectionInfoKeys"=>[], "sectionWarningKeys"=>[], "value"=>nil, "adamId"=>"715886894", ..
```

That is just a "serialized hash" (note the `=>` instead of the `: ` we would expect with JSON).

---

We use the same method in other places, e.g.
https://github.com/fastlane/fastlane/blob/cd88359fa9b6772f91a31a290f8f3c790a716dc0/spaceship/lib/spaceship/client.rb#L444-L472
or
https://github.com/fastlane/fastlane/blob/cd88359fa9b6772f91a31a290f8f3c790a716dc0/fastlane/lib/fastlane/actions/github_api.rb#L225-L229
so I am sure I am just missing something.

**Comment by joshdholtz** [comment]
@janpio Is this happening all the time or just sometimes?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janpio** [comment]
In all the logfiles I looked at in the last few days, for all the responses.

**Comment by janpio** [comment]
D'oh, the response is logged separately: 
https://github.com/fastlane/fastlane/blob/cd88359fa9b6772f91a31a290f8f3c790a716dc0/spaceship/lib/spaceship/client.rb#L790-L794
