### ISSUE TITLE
Running shell script from Fastlane.

### ISSUE THREAD

**Issue by gellertbiro** [fastlane/fastlane#13892]
I am running a simple shell script which will generate for me a custom changelog based on the git commits of the previous day then simply echo it.

```desc "Deploy a new nightly version to Beta by Crashlytics"
   lane :nightly do
     changes = sh "bash ./changelog.sh"

     if !changes.nil? && !changes.empty? && changes != "\n"
         do some work...
     end
   end
```

When I run it on the CI server I get the following string attached to the front of the changelog:
`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`

I am assumnig that the locale should be set correctly in the CI side. (My problem here is that I don't really have access to do it), so my question would be that how can I get rid of the warning in a most effective way. Can I tell the `sh` command to avoid warnings or something like that?

**Comment by janpio** [comment]
You can always strip that string from what you are getting when it is present. Quick and easy fix if you can't solve the underlying problem.
