### ISSUE TITLE
Target names for only_testing/skip_testing in scan doesn't handle whitespace correctly

### ISSUE THREAD

**Issue by CodyDunlap** [fastlane/fastlane#13899]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am using the scan tool in my fastfile. I want fastlane to run my unit tests, but not my ui tests, so to do that I use: run_tests(scheme: "My App", code_coverage: true, only_testing: "My App Unit Tests")

This fails with the error "Unknown build action 'App'". 

After looking through the command that is actually being used against xcodebuild, it appears fastlane is using escape characters for white space in the scheme target, but not for white space in the only_testing/skip_testing targets. 

I have verified this by changing my command to run_tests(scheme: "My App", code_coverage: true, only_testing: "My\\ App\\ Unit\\ Tests"). When I use this command, it works as expected, though this is weird to deal with because it is inconsistent with other commands using app targets.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 0.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.2.7        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.15.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.6        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| nap                       | 1.1.0        |
| naturally                 | 2.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-spinner               | 0.8.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.6.0        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-12-12**
</details></pre>
</details>

**Comment by janpio** [comment]
Thanks. Your description matches a missing `.shellescape` call on the `only_testing` value. I will fix this tomorrow and create a Pull Request.

Could you please add the complete output of the command to your issue? That would make it a bit easier to find the correct spot in the code and check for other issues at the same time.

**Comment by CodyDunlap** [comment]
Unfortunately, I can't upload the output of the command because it has private information in it.

**Comment by janpio** [comment]
Could you try to redact? Without it, I have no idea where to start looking :/

**Comment by CodyDunlap** [comment]
Here is the output if I remove the escape characters in the only_testing option: 

[09:08:47]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:08:49]: ----------------------------------------
[09:08:49]: --- Step: Verifying fastlane version ---
[09:08:49]: ----------------------------------------
[09:08:49]: Your fastlane version 2.112.0 matches the minimum requirement of 1.109.0  ✅
[09:08:49]: ------------------------------
[09:08:49]: --- Step: default_platform ---
[09:08:49]: ------------------------------
[09:08:49]: Driving the lane 'test' 🚀
[09:08:49]: ------------------
[09:08:49]: --- Step: scan ---
[09:08:49]: ------------------
[09:08:49]: $ xcodebuild -showBuildSettings -workspace ./myapp.xcworkspace -scheme My\ App
[09:08:52]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[09:08:55]: Found simulator "iPhone 5s (12.1)"
[09:08:55]: $ xcodebuild -showBuildSettings -workspace ./myapp.xcworkspace -scheme My\ App
[09:08:58]: Found simulator "iPhone 5s (12.1)"

+----------------------------+-------------------------------+
|                  Summary for scan 2.112.0                  |
+----------------------------+-------------------------------+
| scheme                     | My App                |
| code_coverage              | true                          |
| clean                      | true                          |
| only_testing               | ["My App Unit Tests"] |
| derived_data_path          | ./fastlane/test_output        |
| workspace                  | ./myapp.xcworkspace   |
| skip_detect_devices        | false                         |
| reinstall_app              | false                         |
| open_report                | false                         |
| output_directory           | ./fastlane/test_output        |
| output_types               | html,junit                    |
| buildlog_path              | ~/Library/Logs/scan           |
| include_simulator_logs     | false                         |
| should_zip_build_products  | false                         |
| result_bundle              | false                         |
| use_clang_report_name      | false                         |
| disable_concurrent_testing | false                         |
| skip_build                 | false                         |
| skip_slack                 | false                         |
| slack_only_on_failure      | false                         |
| fail_build                 | true                          |
| xcode_path                 | /Applications/Xcode.app       |
+----------------------------+-------------------------------+

[09:08:58]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./myapp.xcworkspace -scheme My\ App -destination 'platform=iOS Simulator,id=8D4272D5-2399-4F12-B141-0AA4077C65D8' -derivedDataPath './fastlane/test_output' -enableCodeCoverage YES -only-testing:My App Unit Tests clean build test | tee '/Users/<redacted>/Library/Logs/scan/My App-My App.log' | xcpretty  --report html --output '/Users/<redeacted>/Documents/Development/Projects/MyApp/fastlane/test_output/report.html' --report junit --output '/Users/<redacted>/Documents/Development/Projects/MyApp/fastlane/test_output/report.junit' --report junit --output '/var/folders/b3/ktyxy3993_vdm77kkmqtfggm0000gn/T/junit_report20190109-10694-hyctv2'
[09:08:58]: ▸ Loading...
[09:08:58]: ▸ xcodebuild: error: Unknown build action 'App'.
xcodebuild: error: Unknown build action 'App'.
[09:08:58]: Exit status: 65
+----------------------------+------------------------+
|                    Lane Context                     |
+----------------------------+------------------------+
| DEFAULT_PLATFORM           | ios                    |
| PLATFORM_NAME              |                        |
| LANE_NAME                  | test                   |
| SCAN_DERIVED_DATA_PATH     | ./fastlane/test_output |
| SCAN_GENERATED_PLIST_FILES | []                     |
| SCAN_GENERATED_PLIST_FILE  |                        |
+----------------------------+------------------------+
[09:08:59]: Error building/testing the application - see the log above

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | scan                       | 9           |
+------+----------------------------+-------------+

[09:08:59]: fastlane finished with errors

[!] Error building/testing the application - see the log above

**Comment by janpio** [comment]
Got it an PR created. Thanks!
