### ISSUE TITLE
match doesn't install certificate for provisioning profile

### ISSUE THREAD

**Issue by Holbanner** [fastlane/fastlane#13895]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi,
I'm encountering a problem when trying to build an IPA
I get the error: `Code Signing Error: Provisioning profile "match AppStore com.company.name" doesn't include signing certificate "iPhone Distribution: app-Name (XXXXXXX)`

while `fastlane match` returns : 
```
+-----------------------+-------------------------------------+

[15:47:38]: Cloning remote git repo...
[15:47:38]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[15:47:39]: Checking out branch branch-Name...
[15:47:39]: 🔓  Successfully decrypted certificates repo
[15:47:39]: Verifying that the certificate and profile are still valid on the Dev Portal...
[15:47:41]: Installing certificate...

+-------------------+---------------------------------------------+
|                      Installed Certificate                      |
+-------------------+---------------------------------------------+
| User ID           | XXXXXXX                                  |
| Common Name       | iPhone Distribution: app-Name (XXXXXXX) |
| Organisation Unit | XXXXXXX                                  |
| Organisation      | org-Name                                  |
| Country           | FR                                          |
| Start Datetime    | 2018-12-11 14:01:14 UTC                     |
| End Datetime      | 2019-12-11 14:01:14 UTC                     |
+-------------------+---------------------------------------------+

[15:47:45]: Installing provisioning profile...

+---------------------+-------------------------------------------+---------------------------------------------------------------+
|                                                 Installed Provisioning Profile                                                  |
+---------------------+-------------------------------------------+---------------------------------------------------------------+
| Parameter           | Environment Variable                      | Value                                                         |
+---------------------+-------------------------------------------+---------------------------------------------------------------+
| App Identifier      |                                           | com.company.name                                                |
| Type                |                                           | appstore                                                      |
| Platform            |                                           | ios                                                           |
| Profile UUID        | sigh_com.company.name_appstore              | 0c7c8002-ff04-442c-a5b7-ead28cee5459                          |
| Profile Name        | sigh_com.company.name_appstore_profile-name | match AppStore com.company.name                                 |
| Profile Path        | sigh_com.company.name_appstore_profile-path | /Users/me/Library/MobileDevice/Provisioning               |
|                     |                                           | Profiles/0c7c8002-ff04-442c-a5b7-ead28cee5459.mobileprovisio  |
|                     |                                           | n                                                             |
| Development Team ID | sigh_com.company.name_appstore_team-id      | XXXXXXXXXX                                                   |
+---------------------+-------------------------------------------+---------------------------------------------------------------+

[15:47:46]: All required keys, certificates and provisioning profiles are installed 🙌

```
Since i can see both cert and profile created by match i believe they are supposed to be linked to each other in some way but it doesn't seem so at signning time.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-12-12**
</details></pre>
</details>

**Comment by janpio** [comment]
Did you correctly set up your Xcode project?

> fastlane will work out of the box with Xcode 9 and up if you selected manual code signing and choose a provisioning profile name for each of your targets

https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up

**Comment by Holbanner** [comment]
I did, but Xcode prompt with the error : Signing for "app-Name" requires a development team.
Select a development team in the build settings editor that matches the selected profile "match AppStore com.company.name".

**Comment by janpio** [comment]
Then do so.

**Comment by Holbanner** [comment]
Already did, 
Same results

**Comment by janpio** [comment]
Please fill the complete issue template, you left out the complete output of the command you are running.

**Comment by Holbanner** [comment]
Well, i guess there is something going on with --capture_output at the moment since this is the only output i get is this:
```
fastlane testMatch --capture_output
[✔] 🚀 
```
I kept fidgetting around and ended up with this in Xcode : 
Provisioning profile "match AppStore com.comnpany.name" doesn't include signing certificate "iPhone Distribution: app-Name (XXXXXXXX)
with the cert being the one shown installing during match()

**Comment by Holbanner** [comment]
ok, i got my build running by manually removing every certs/profiles on my teams git branch, then running`fastlane match nuke` and then fastlane match again
So i'm closing this
