### ISSUE TITLE
How can I get a complete list of Apple domains to whitelist at my company proxy?

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#13900]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) 

### Question Subject

How can I get a complete list of Apple domains to whitelist at my company proxy?

#### Question Description

We have quite a tight proxy and we'd need to whitelist all Apple domains to be able to use `spaceship` and `fastlane` tools in general.
We have already whitelisted a bunch of domains, but meanwhile rolled out new REST API with new domains.

I was looking into Spaceship readme for a complete list, but I've noticed that readme seems to be listing old domain names.

For example, this page (https://github.com/fastlane/fastlane/tree/master/spaceship) mentions `https://idmsa.apple.com`, while the actual endpoint seems to be `https://olympus.itunes.apple.com`.

Is the Spaceship readme the right place to look for the complete list of domains to whitelist?

Is there more comprehensive list or even a link to official Apple documentation page (I couldn't find one).

**Comment by janpio** [comment]
Spaceship is indeed the correct place to look at, and yes, the documentation didn't get too much love in the past. I started to fix this, but it will take a lot of time and effort to get to a place where questions like yours can be answered by only looking at the docs.

Meaning: Probably best go through the spaceship code and look for hostnames.
You can also go through the spaceship logs in `/tmp`, many of them should now include the hostname as well. (Probably not all of them, I don't think I properly fixed the hostname logging yet)
If you are done, pleeeease also update the documentation with your new list 🥇
