### ISSUE TITLE
Fastlane match passphrase encrypt/decrypt error

### ISSUE THREAD

**Issue by kelvinlauKL** [fastlane/fastlane#13904]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I am asking about `fastlane match`.

#### Question Description

I ran match and at one point I was given the following prompt:

```
[16:55:38]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[16:55:38]: This passphrase is specific per repository and will be stored in your local keychain
[16:55:38]: Make sure to remember the password, as you'll need it when you run match on a different machine
[16:55:38]: Passphrase for Git Repo: ****
[16:56:06]: Type passphrase again: ****
security: SecKeychainAddInternetPassword <NULL>: The specified item already exists in the keychain.
```

This prompt repeated over and over again, until I gave up and gave empty string for passphrase. It then terminated and gave me the following error:

```
[!] No password supplied
```

Afterwards, I tried calling match again and was greeted with the following error:

```
[!] Could not create another Development certificate, reached the maximum number of available Development certificates.
```

At this point, I'm unable to proceed with match.

**Comment by janpio** [comment]
You should be able to delete the development certificates that were created in the Apple Developer Console manually, then try again.

The first error indicates that it couldn't save your password to the keychain as the element it wanted to create already existed - this seems to be the code being executed here: https://github.com/fastlane/fastlane/blob/f4849a575c07b7931f2832d2214c95751996e151/match/lib/match/encryption/openssl.rb#L56-L58 I am not sure if this should result in an error when the entry is already there, or how this could happen in the first place.

You might want to try that entry in the Keychain manually was well, if I read the code correctly it will consist of `match_` and then your git repo URL or something like that.
