### ISSUE TITLE
Recurring IAP "grandfathered" allowed values documentation?

### ISSUE THREAD

**Issue by timothycosta** [fastlane/fastlane#13906]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using spaceship to update in app purchases, what are the allowed values for "grandfathered"?  The only value I've been able to find is `grandfathered: { value: "FUTURE_NONE" }`.  I could *guess* that `FUTURE_ALL` is allowed, but I still wouldn't know what either of those mean.   I'm looking to ensure that all our current subscribers are grandfathered in.  @hjanuschka Do you know by chance? 

```
    pricing_intervals: [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: 20,
        grandfathered: { value: "FUTURE_NONE" }
      }
    ],
```

**Comment by janpio** [comment]
I looked into this a bit, I found this issue with an additional example: https://github.com/fastlane/fastlane/issues/11169#issue-281078149
