### ISSUE TITLE
How to deliver iOS app as B2B app for VPP?

### ISSUE THREAD

**Issue by benzman81** [fastlane/fastlane#13901]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
We don't want to submit the app to the official apple app store but as B2B app for VPP.

#### Question Description
We have not found any documentation on how to do this using fastlane but we noticed #12420 which indicates that there is code for B2B apps.

**Comment by janpio** [comment]
From a quick loot at the PR you linked to and searching through the codebase, this seems to be "only" implemented in spaceship, our library that talks to Apple servers. It is not explicitly exposed via any fastlane actions or commands. I unfortunately don't know anything about B2B/VPP to investigate further, but that might focus your search.

**Comment by heartofagoof** [comment]
I authored those changes. And yes, it is only in spaceship. You could either use it as is or try to propagate this option upto `deliver`.

**Comment by benzman81** [comment]
Could you point me to the easiest solution. Just gost started with fastlane and only know how ro use it by its documentation, but we have the requirement to publish via b2b/vpp.

**Comment by benzman81** [comment]
@heartofagoof any tips?

**Comment by benzman81** [comment]
Still waiting for tips @heartofagoof as I habe mo clue where to look for an example.
