### ISSUE TITLE
Remotely enter 2FA code

### ISSUE THREAD

**Issue by AmauriC** [fastlane/fastlane#13911]
#### Motivation Behind Feature
Fastlane is perfect to build and upload apps without any human action.
Now Apple force 2FA, and I have to get back behind my mac to enter the code, that's annoying.

#### Feature Description
Do not request a 2FA code, get it from the Appfile and request the session.

**Comment by janpio** [comment]
How would that work? The 2FA code is only sent _after_ fastlane requests the login.

**Comment by AmauriC** [comment]
This will not work if fastlane do not request login and just send the code for verification?

I can request a code from my browser, same as described [here](https://docs.fastlane.tools/best-practices/continuous-integration/#bypass-trusted-device-and-use-sms-for-verification) for text code.

**Comment by AmauriC** [comment]
Yes the code is valid ~10mns but I can request the code and use it instantly.

1- The client request a code
2- The client send this code to the server
3- The server start a spaceauth with the code

This can be done in few seconds.

**Comment by AmauriC** [comment]
Yes, I want the token in the fastfile or environnement variable.

It will be possible to execute `handle_two_factor_with_token` instead of `handle_two_step_or_factor` if `ENV['FASTLANE_2FA_CODE']` exist.

No new code generation
No need to manually enter the code



```
    def handle_two_factor_with_token

      code = ENV['FASTLANE_2FA_CODE']
      puts("Requesting session...")

      # Send securityCode back to server to get a valid session
      r = request(:post) do |req|
        req.url("https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode")
        req.headers['Content-Type'] = 'application/json'
        req.body = { "securityCode" => { "code" => code.to_s } }.to_json

        update_request_headers(req)
      end

      # we use `Spaceship::TunesClient.new.handle_itc_response`
      # since this might be from the Dev Portal, but for 2 step
      Spaceship::TunesClient.new.handle_itc_response(r.body)

      store_session

      return true
    end
```

Nothing change if the code is wrong or expired, the lane will fail.

**Comment by janpio** [comment]
Wouldn't be a better way to implement this to just skip the prompting in the existing code and use the value of this env variable instead? Then it would work for both 2FA and 2 step verification, and all the rest of the flow would be identical to how it is implemented right now (which follows the requests of the web site).

(Although to be fair this then would still actually _request_ the token to be sent to a device)

**Comment by AmauriC** [comment]
My example was just here to clarify my purpose, it worked 😉

No technical issue if a new code is requested but it will be better imho to avoid useless requests.

**Comment by AmauriC** [comment]
As a dirty workaround `fastlane publish<<<$TOKEN` do the job.

But not really a clean way to handle that point 🤪
