### ISSUE TITLE
It create a new provisioning profile in Apple Developer ，EveryTime build.

### ISSUE THREAD

**Issue by UZheng** [fastlane/fastlane#13910]
```
[16:33:25]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[16:33:27]: The name 'cn.xxxx AdHoc' is already taken, using another one.
[16:33:27]: Creating new provisioning profile for 'cn.xxxx' with name 'cn.xxxx AdHoc 1544776407' for 'ios' platform
[16:33:28]: Downloading provisioning profile...
```

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status      |
| --------------------- | ------- | ------------------ |
| fastlane-plugin-pgyer | 0.2.1   | 🚫 Update available |
| fastlane-plugin-pgyer | 0.2.1   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.3       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-pgyer     | 0.2.1        |
</details>

*generated on:* **2018-12-14**
</details></pre>
</details>

**Comment by jianghui1** [comment]
me too

**Comment by janpio** [comment]
Please update your post to include all the things asked for in https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md @UZheng. There is a reason why we ask for the complete output and all the other information. Thanks. 

If you have the same problem @jianghui1, please do the same in your response so we have 2 cases to inspect. Thanks.

**Comment by janpio** [comment]
@jianghui1 created a new issue at https://github.com/fastlane/fastlane/issues/13914 This reproduces the relevant parts of the issue: ##### Complete output when running fastlane, including the stack trace and command used




<details>
  <pre>[17:40:49]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[17:40:51]: The name '1' is already taken, using another one.
[17:40:51]: Creating new provisioning profile for 'com.zutuan.app.1' with name '1 1544780451' for 'ios' platform
[17:40:52]: Downloading provisioning profile...
[17:40:52]: Successfully downloaded provisioning profile...
[17:40:53]: Installing provisioning profile...</pre>
</details>

### Environment



<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.2                           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :registerDevice do
  register_device(
    name: "23",
    udid: "xxxxxxxxxxxxxxx",
    username: "xxxxxxxxxxx"
  )
  end
  lane :newProvision do
    sigh(force: true,
    adhoc: true,
    app_identifier: "xxxxxxxx",
    username: "xxxxxxxxx",
    provisioning_name: "1",
    filename: "1.mobileprovision"
  )
  end
  desc "One-dragon" 
  lane :oneDragon do
    registerDevice
    newProvision
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.3       |
| openssl                   | 2.0.2        |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| fastimage                 | 2.1.4        |
| bundler                   | 1.16.6       |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| psych                     | 2.2.2        |
</details>


*generated on:* **2018-12-14**
</details></pre>
</details>

**Comment by janpio** [comment]
@jianghui1 You are missing both the complete output and the actual command or lane you are running in what you posted.

**Comment by TheMetalCode** [comment]
@UZheng do your builds fail when this "new every time" profile creation occurs? Similar to https://github.com/fastlane/fastlane/issues/13915?

**Comment by mouhao** [comment]
me too

`+-------------------------------------+-------------------------+
|                   Summary for sigh 2.111.0                       |
+-------------------------------------+-------------------------+
| username                                | mouhao@icloud.com       |
| adhoc                                      | true                    |
| force                                        | false                   |
| app_identifier                          | com.wbfwtop.buyer       |
| provisioning_name                   | com.wbfwtop.buyer AdHoc |
| filename                                  | com.wbfwtop.buyer       |
|                                                | AdHoc.mobileprovision   |
| developer_id                          | false                   |
| development                          | false                   |
| skip_install                             | false                   |
| ignore_profiles_with_different_name | false                   |
| cert_id                                    | Q669W5JXRA              |
| skip_fetch_profiles                 | false                   |
| skip_certificate_verification       | false                   |
| platform                                 | ios                     |
| readonly                                 | false                   |
+-------------------------------------+-------------------------+

[14:31:57]: Starting login with user 'mouhao@icloud.com'
[14:32:00]: Successfully logged in
[14:32:00]: Fetching profiles...
[14:32:01]: Verifying certificates...
[14:32:01]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[14:32:03]:The name 'com.wbfwtop.buyer AdHoc' is already taken, using another one.
[14:32:03]:Creating new provisioning profile for 'com.wbfwtop.buyer' with name 'com.wbfwtop.buyer AdHoc 1545028323' for 'ios' platform
[14:32:03]:Downloading provisioning profile...
[14:32:04]:Successfully downloaded provisioning profile...
[14:32:04]:Installing provisioning profile...`

**Comment by UZheng** [comment]
> Please update your post to include all the things asked for in https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md @UZheng. There is a reason why we ask for the complete output and all the other information like what command you are running. Thanks.
> 
> If you have the same problem @jianghui1, please do the same in your response so we have 2 cases to inspect. Thanks.


- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description


##### Complete output when running fastlane, including the stack trace and command used




<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment



<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

#update_fastlane

default_platform(:ios)

platform :ios do


  before_all do |lane, options|
   
    # sh("pod install")
    sh("git branch -l")
    branchname = git_branch  
    lastcommit = last_git_commit
    UI.success "当前选择的分支为#{branchname}" 
    UI.success "最新的commit信息为#{lastcommit}"
  end

 desc "start"
  lane :for_pgyAdhoc do |options|
    #infomation 
    info = options[:des] 
    UI.success "蒲公英提交信息为#{info}"

    isDebug = options[:isDebug]
    ipapath =  build(isAdHoc: true, build_model: isDebug)
  end

  desc "archive lane"
  lane :build do |options|

    debug = false

    if options[:build_model] == true 

    puts "build_model: #{options[:build_model]}--->"
    debug = true
    elsif options[:build_model] == false
    puts "build_model: #{options[:build_model]}--->"
    debug = false
    else
    puts "build_model: #{options[:build_model]}--->c"
    debug = false
    end

    sh "pwd"
    sh"/usr/libexec/PlistBuddy -c 'Set :Debug #{debug}' ../ccc/Global/GlobalConfig.plist"
    increment_build_number  
    newbuild = get_build_number()
    newversion = get_version_number() 
    date = Time.new.strftime("%Y.%m.%d") 
    ipaname = "C.v#{newversion}.build#{newbuild}.#{date}.ipa"  
    path = "../C_ipas/"  
    ipapath = "#{path}#{ipaname}"
    cert(output_path: "../C_cers/")  

    puts "#{options[:isAdHoc]}"
     if options[:isAdHoc]
      puts "adhock build"
      sigh(adhoc: true, force: true, output_path: "../C_cers/") 
      gym(export_method: "ad-hoc",clean: true,silent: true,output_name: ipaname,output_directory: path) 
    else
      puts "生产 进行打包"
      sigh(output_path: "../C_cers/") 
      gym(export_method: "app-store",clean: true,silent: true,output_name: ipaname,output_directory: path)
    end
    
    ipapath

  end

 
error do |lane, exception, options|
  if options[:debug]
    puts "#{exception}"
  end
end

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("ccc") # The bundle identifier of your app
apple_id("ccc") # Your Apple email address

itc_team_id("ccc") # App Store Connect Team ID
team_id("ccc") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                | Version | Update-Status      |
| --------------------- | ------- | ------------------ |
| fastlane-plugin-pgyer | 0.2.1   | 🚫 Update available |
| fastlane-plugin-pgyer | 0.2.1   | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.1        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-pgyer     | 0.2.1        |
</details>


*generated on:* **2018-12-17**
</details></pre>
</details>

**Comment by janpio** [comment]
What you posted is still missing the complete output and information what command you are actually running @UZheng. 

Same for @mouhao - we need the _complete_ output and some information what command you are executing in the first place. Also the `fastlane env` information is vital for us to understand what is going on.

**Comment by shihkai-tony-wei** [comment]
You should first check the correct cert is installed on the machine.

To address this specific issue, you can set `readonly` to true; that way the build will fail instead of creating new profile.

**Comment by UZheng** [comment]
> What you posted is still missing the complete output and information what command you are actually running @UZheng.
> 
> Same for @mouhao - we need the _complete_ output and some information what command you are executing in the first place. Also the `fastlane env` information is vital for us to understand what is going on.

I execut the commend   `fastlane start des:'new build' isDebug:true --capture_output` , but nothing out put. so I miss the  complete output.

**Comment by UZheng** [comment]
> You should first check the correct cert is installed on the machine.
> 
> To address this specific issue, you can set `readonly` to true; that way the build will fail instead of creating new profile.



> @UZheng do your builds fail when this "new every time" profile creation occurs? Similar to #13915?

It build success，and  just creat another one. The old one is still available in Apple Developer.

**Comment by mouhao** [comment]
> What you posted is still missing the complete output and information what command you are actually running @UZheng.
> 
> Same for @mouhao - we need the _complete_ output and some information what command you are executing in the first place. Also the `fastlane env` information is vital for us to understand what is going on.

ok. 

`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.6.3                           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 lane :beta do
    get_certificates(
        username:"mouhao@icloud.com"
      )  
    get_push_certificate(
        username:"mouhao@icloud.com",
        app_identifier: "com.wbfwtop.buyer"
        )
    get_provisioning_profile(
       username:"mouhao@icloud.com",
       adhoc: true,
       force: false,
       app_identifier: "com.wbfwtop.buyer",
       provisioning_name: "com.wbfwtop.buyer AdHoc",
       filename: "com.wbfwtop.buyer AdHoc.mobileprovision"
        )   
    build_app(export_method: "ad-hoc",
             clean: true,
             silent:true,
            export_xcargs: "-allowProvisioningUpdates",
            export_options: {
                method: "ad-hoc",
                provisioningProfiles: {
                    "com.wbfwtop.buyer" => "com.wbfwtop.buyer AdHoc"
                }
            }
             )
  end
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.2       |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.7.0        |
| unicode-display_width     | 1.4.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.1.0        |
| dotenv                    | 2.5.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
| nokogiri                  | 1.5.11       |
| psych                     | 2.2.2        |
</details>


*generated on:* **2018-12-18**
</details>`

**Comment by yuewah** [comment]
we also have the same problem as @UZheng once updated to 2.111.0

**Comment by janpio** [comment]
> I execut the commend `fastlane start des:'new build' isDebug:true --capture_output` , 

`start` is not a lane in the `Fastfile` you posted.

> but nothing out put. so I miss the complete output.

You posted some lines from output in your initial post: https://github.com/fastlane/fastlane/issues/13910#issue-391017613 We need everything that was output before and after.

---

To be honest this issue is a real mess now, it is pretty much impossible to understand what is going on.

So I am going to close this now, and ask each of you @yuewah @mouhao @UZheng @shihkai-tony-wei @jianghui1 to create a new one using this link: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md 

Please make sure that you include 1. the command you are executing on the command line, 2. the _complete_ output it is giving you (from when you execute the command until you can start a new command) - including the error! and 3. include the complete output of `fastlane env` which includes the `Fastfile` you are running (which has to include the lane/command you executed for 1). And 4. include a link to this issue here, so it is easier to connect it all together. Thanks.

**Comment by janpio** [comment]
Then please do exactly the same @squintanadev what I told the others: Create a new issue and include the necessary information so we can try to understand what is going on. Thanks.
