### ISSUE TITLE
Problem when install fastlane

### ISSUE THREAD

**Issue by ChieLi** [fastlane/fastlane#1392]
get problem when i try to install fastlane

i run 
`sudo gem install fastlane`
then i got 
`ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/commander`

on OS X EI Captan

what should i do?

**Comment by ChieLi** [comment]
resolved

reason：With OS X EI Capitan, there is a new security function that prevents you from modifying system files called Rootless

1.
`sudo gem install -n /usr/local/bin fastlane
`
or  
2.disable rootless function and install gems after the reboot using:
`sudo nvram boot-args="rootless=0"; sudo reboot
`

**Comment by ohwutup** [comment]
Hey @ChieLi are you still having this issue? It looks like it was resolved. I am going to close it for now, but please leave another comment if there is an issue and we will reopen it! Thanks! :rocket:
