### ISSUE TITLE
[Action] Integrate Lokalise

### ISSUE THREAD

**Issue by jhandguy** [fastlane/fastlane#13924]
### Feature Request

Integrate Lokalise actions bundled in the Fastlane repository.
See: https://github.com/lokalise/lokalise-fastlane-actions.

#### Motivation Behind Feature

I'd like to see Lokalise (a widely used translation service) actions to be part of the Fastlane repository.
This would mean having the Lokalise actions available in Swift as well. 
See: https://github.com/lokalise/lokalise-fastlane-actions.

**Comment by janpio** [comment]
Actions like those are prime candidates for a fastlane plugin, as only a small part of the users will be interested in those, and they are coupled to an external service. With the actions already existing, it should be pretty straight forward to turn them into a plugin: https://docs.fastlane.tools/plugins/create-plugin/

(As far as I know, this won't actually solve your problem as fastlane swift doesn't support plugins yet, correct?)

**Comment by jhandguy** [comment]
Got it 👍
Yes, exactly, Fastlane Swift does not support plugins yet.
Guess we’ll have to support Swift plugins then 😉
Should we close this and reopen only once plugins are supported?

**Comment by janpio** [comment]
Well, someone would have to create that plugin first anyway... Do you want to take a shot at it?

**Comment by jhandguy** [comment]
For sure! 👍
Will only be able to do so after the 1st of Jan though...

**Comment by janpio** [comment]
We are not in a hurry here ;) Just post a link to your repo when done, _then_ we can close this issue.
