### ISSUE TITLE
The request could not be completed because:Unauthorized Access

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#13923]
I have updated the Xcode to 10.1. After updating this I got Unauthorized Access error in Fastlane. But I can able to upload the build successfully in testflight.

```
[10:06:24]: Unauthorized Access

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 8           |
| 3    | build_app              | 1057        |
| 💥   | upload_to_testflight   | 252         |
+------+------------------------+-------------+

[10:06:24]: fastlane finished with errors


**[!] The request could not be completed because:
	Unauthorized Access**

**Comment by janpio** [comment]
Can you please post the complete output you are getting, and the command you are running?
Please also include your `fastlane env` information. Thanks.

Note: Possibly related to #13903

**Comment by nihp** [comment]
I am using fastlane ios beta command to upload the app in testflight

```
+-------------------------------------------------------+------------------------------------------------------------+
| Summary for gym 2.101.1 |
+-------------------------------------------------------+------------------------------------------------------------+
| scheme | App |
| workspace | ./App.xcworkspace |
| destination | generic/platform=iOS |
| export_options.provisioningProfiles.bundleId | match AppStore bundleId  |
| output_name | App |
| build_path | /Library/Developer/Xcode/Archives/2018-12-17 |
| clean | false |
| output_directory | . |
| silent | false |
| skip_package_ipa | false |
| result_bundle | false |
| buildlog_path | ~/Library/Logs/gym |
| skip_profile_detection | false |
| xcode_path | /Applications/Xcode.app |
+-------------------------------------------------------+------------------------------------------------------------+

+-----------------------------------------------------------------------------------+----------------------+
| Generated Build Command |
+-----------------------------------------------------------------------------------+----------------------+
| Option | Value |
+-----------------------------------------------------------------------------------+----------------------+
| set -o pipefail && | |
| xcodebuild | |
| -workspace ./App.xcworkspace | |
| -scheme App | |
| -destination | generic/platform=iOS |
| -archivePath /Library/Developer/Xcode/Archives/2018-12-17/App\ | |
| 2018-12-17\ 12.15.14.xcarchive | |
| archive | |
| | tee /Library/Logs/gym/App | |
| | xcpretty | |
+-----------------------------------------------------------------------------------+----------------------+
```

**Comment by nihp** [comment]
Above unauthorized error is resolved. But I don't know the exact reason why it happens and what is the fix for this. Kindly let me know any thoughts about this

**Comment by janpio** [comment]
Impossible to answer as you didn't post the complete output you are getting or your `fastlane env` information.

**Comment by nihp** [comment]
Fastlane Env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

|```
 Key                         | Value                                     |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.14.2                                   |
| Ruby                        | 2.5.1                                     |
| Bundler?                    | false                                     |
| Git                         | git version 2.19.2                        |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane       |
| Host                        | Mac OS X 10.14.2 (18C54)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib              |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018               |
| Is contained                | false                                     |
| Is homebrew                 | false                                     |
| Is installed via Fabric.app | false                                     |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                      |

```

```
### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.101.1 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.5.9        |
| unicode-display_width     | 1.4.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| faraday                   | 0.15.2       |
| dotenv                    | 2.5.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.8.1        |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.4        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

```

**Comment by janpio** [comment]
> | fastlane | 2.101.1 | 🚫 Update available |

You are using an old version of fastlane. You should update.

**Comment by BeshBashBosh** [comment]
I got this same error with using pilot launched via a CI.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/25281325/53562993-b7df6380-3b4a-11e9-9de9-aec4a9f3cae4.png">

Below are my `fastlane env` details as this may still be an issue?

Also the build did actually successfully upload to testflight, but the changelog I passed in did not get transmitted.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.3 (18D42)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-trainer | 0.4.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.14.5       |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.1.4        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11       |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| awesome_print             | 1.8.0        |
| babosa                    | 1.0.2        |
| backports                 | 3.11.4       |
| builder                   | 3.2.3        |
| clipboard                 | 1.3.3        |
| cucumber-tag_expressions  | 1.1.1        |
| gherkin                   | 5.1.0        |
| cucumber-core             | 3.2.1        |
| cucumber-expressions      | 6.0.1        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.13.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 3.1.2        |
| edn                       | 1.1.1        |
| geocoder                  | 1.5.1        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| command_runner_ng         | 0.1.4        |
| thor                      | 0.20.3       |
| run_loop                  | 2.7.1        |
| slowhandcuke              | 0.0.3        |
| calabash-cucumber         | 0.20.5       |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.6.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| cocoapods                 | 1.6.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| trainer                   | 0.8.1        |
| fastlane-plugin-trainer   | 0.4.1        |
</details>


*generated on:* **2019-02-28**
</details>

**Comment by janpio** [comment]
Best create a new bug report issue @BeshBashBosh and include all the information it asks for. You can link to this closed issue for reference of cours.

**Comment by marceloogeda** [comment]
@BeshBashBosh are you still facing that problem?

**Comment by yurykorzun** [comment]
I started seeing this issue with upload_to_testflight

**Comment by anushkmittal** [comment]
bump same,

just started out of the blue today

**Comment by janpio** [comment]
Please open new issues with all the information the issue template asks for - then we can take a look.

Quick thought: Do you have an `apple_id` parameter for `upload_to_testflight` maybe? If so, is it an Apple Login Email address or an Apple App ID? The second one would be correct.
