### ISSUE TITLE
Using UITests with Match

### ISSUE THREAD

**Issue by jbehrens94** [fastlane/fastlane#13921]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about?
Fastlane with match

Is this a question about documentation?
In part, it is, I imagine it would be good to mention this in the documentation.

#### Question Description

What is the suggested way of using match to create provisioning profiles for the UITests target? Do I just add a wildcard provisioning profile, or should I specify it to the target's bundleID itself? What do you recommend?

**Comment by janpio** [comment]
Huh, how did you setup and want to run your UITests? I am not aware I had to do anything to make `scan`/`run_tests` work.

**Comment by jbehrens94** [comment]
I have the UITests target, that needs to be code signed, but it has a unique bundle ID. I'd like to know more about the code signing for that target with match, as I don't want to auto sign it, obviously.
