### ISSUE TITLE
[deliver] Can't upload tvOS Apple TV 4k screenshots 

### ISSUE THREAD

**Issue by mariohahn** [fastlane/fastlane#13925]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
expected behavior: 
Upload Screenshots to AppStore Connect 

happening:
Unsupported Screen size

```
ERROR [2018-12-17 16:39:44.89]: Unsupported screen size [3840, 2160] for path './screenshots/tvOS/de-DE/Apple TV 4K-0-TV.png'
```

my lane: 
<pre>  
  lane :tvOSUploadScreenshots do
    deliver(skip_binary_upload: true,
                 skip_metadata: true,
                      platform: "appletvos",
              screenshots_path: "./screenshots/tvOS")
  end
</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[16:39:16]: fastlane detected a Gemfile in the current directory
[16:39:16]: however it seems like you don't use `bundle exec`
[16:39:16]: to launch fastlane faster, please use
[16:39:16]: 
[16:39:16]: $ bundle exec fastlane tvOSUploadScreenshots --capture_output
[16:39:16]: 
[16:39:16]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-12-17 16:39:17.63]: Checking if there are any plugins that should be loaded...
DEBUG [2018-12-17 16:39:17.72]: Loading 'fastlane-plugin-appicon' plugin
INFO [2018-12-17 16:39:17.77]: gem 'fastlane-plugin-appicon' is already installed
DEBUG [2018-12-17 16:39:17.79]: Loading 'fastlane-plugin-versioning' plugin
INFO [2018-12-17 16:39:17.79]: gem 'fastlane-plugin-versioning' is already installed
DEBUG [2018-12-17 16:39:17.82]: Loading 'fastlane-plugin-google_drive' plugin
INFO [2018-12-17 16:39:17.82]: gem 'fastlane-plugin-google_drive' is already installed
INFO [2018-12-17 16:39:18.13]: ------------------------------
INFO [2018-12-17 16:39:18.13]: --- Step: default_platform ---
INFO [2018-12-17 16:39:18.13]: ------------------------------
INFO [2018-12-17 16:39:18.14]: Driving the lane 'ios tvOSUploadScreenshots' 🚀
INFO [2018-12-17 16:39:18.14]: ---------------------------
INFO [2018-12-17 16:39:18.14]: --- Step: xcode_install ---
INFO [2018-12-17 16:39:18.14]: ---------------------------
INFO [2018-12-17 16:39:18.14]: gem 'xcode-install' is already installed
INFO [2018-12-17 16:39:18.68]: Xcode 10.1 is already installed ✨
INFO [2018-12-17 16:39:19.06]: Using Xcode 10.1 on path '/Applications/Xcode.app'
INFO [2018-12-17 16:39:19.19]: ---------------------
INFO [2018-12-17 16:39:19.19]: --- Step: deliver ---
INFO [2018-12-17 16:39:19.19]: ---------------------
INFO [2018-12-17 16:39:19.23]: Successfully loaded '/Users/mariohahn/Documents/work/fastlane/Deliverfile' 📄
INFO [2018-12-17 16:39:19.23]: Login to App Store Connect
INFO [2018-12-17 16:39:21.77]: Login successful
INFO [2018-12-17 16:39:44.89]: Currently not running on CI system, skipping keychain cleanup
WARN [2018-12-17 16:39:44.89]: Lane Context:
INFO [2018-12-17 16:39:44.89]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios tvOSUploadScreenshots", :XCODE_INSTALL_XCODE_PATH=>#<Pathname:/Applications/Xcode.app>}
ERROR [2018-12-17 16:39:44.89]: Unsupported screen size [3840, 2160] for path './screenshots/tvOS/de-DE/Apple TV 4K-0-TV.png'
INFO [2018-12-17 16:39:44.89]: Successfully generated documentation at path '/Users/mariohahn/Documents/work/fastlane/README.md'
DEBUG [2018-12-17 16:39:44.90]: All plugins are up to date
ERROR [2018-12-17 16:39:44.90]: fastlane finished with errors
DEBUG [2018-12-17 16:39:44.90]: All plugins are up to date</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀 </pre>
</details>

**Comment by janpio** [comment]
Apple TV is indeed only listed as 
https://github.com/fastlane/fastlane/blob/cdfdc2e5d7e46008c56018ec46274d2d12ed5745/deliver/lib/deliver/app_screenshot.rb#L269-L271

I don't have experience with Apple TV, do you upload those 4K screenshots additionally to the normal ones or just the 4K ones that are then downscaled by Apple?

**Comment by mariohahn** [comment]
I only use both Screenshots, 4K und normal, is it just adding the Size here?

**Comment by janpio** [comment]
Reference: https://help.apple.com/app-store-connect/#/devd274dd925
