### ISSUE TITLE
AppStore Connect changes upload date for build (=> "Build doesn't show up in the build list anymore")

### ISSUE THREAD

**Issue by rhcpfan** [fastlane/fastlane#13933]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

 
Fastlane uploaded a build at **2018-12-17 22:49:29.40**. This build was showing in AppStore Connect as being uploaded at **"Dec 17, 2018 at 10:49 PM"**. Later, the "Upload Date" value changed in AppStore Connect to **"Dec 17, 2018 at 11:03 PM"** (the same time fastlane started reporting that "Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)"). 

Any idea why AppStore Connect changes the upload date? Is it possible to detect that the build with the new upload date is the same one as the previous? 

<details>
  <pre>INFO [2018-12-17 22:49:29.25]: iTunes Transporter successfully finished its job
DEBUG [2018-12-17 22:49:29.25]: [Transporter]: DBG-X: Returning 0
INFO [2018-12-17 22:49:29.40]: ------------------------------------------------------------------------------------------------------------------
INFO [2018-12-17 22:49:29.40]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
INFO [2018-12-17 22:49:29.40]: ------------------------------------------------------------------------------------------------------------------
INFO [2018-12-17 22:49:29.40]: Successfully uploaded the new binary to App Store Connect
INFO [2018-12-17 22:49:29.40]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
INFO [2018-12-17 22:49:39.70]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:50:10.48]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:50:41.19]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:51:11.97]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:51:42.75]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:52:13.42]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:52:44.17]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:53:14.96]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:53:45.77]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:54:17.38]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:54:48.28]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:55:19.08]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:55:50.46]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:56:21.87]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:56:52.49]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:57:23.29]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:57:54.08]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:58:25.78]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:58:56.68]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:59:27.88]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 22:59:58.84]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:00:29.72]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:01:00.65]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:01:31.34]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:02:02.11]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:02:33.13]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:03:03.92]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:03:34.80]: Waiting for App Store Connect to finish processing the new build (2.28.0 - 3)
INFO [2018-12-17 23:04:05.69]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:04:36.48]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:05:07.31]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:05:38.03]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:06:08.80]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:06:39.67]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:07:10.52]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:07:41.34]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:08:12.31]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:08:43.19]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:09:13.84]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:09:45.42]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:10:16.19]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:10:46.98]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:11:17.84]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:11:48.65]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:12:19.43]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:12:50.16]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:13:20.83]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:13:51.54]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:14:22.19]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:14:53.16]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:15:24.00]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:15:54.67]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:16:25.58]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:16:56.39]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:17:27.06]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:17:57.99]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:18:28.79]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:18:59.66]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
INFO [2018-12-17 23:19:30.40]: Successfully finished processing the build 2.28.0 - 3
INFO [2018-12-17 23:19:33.55]: Successfully set the changelog for build
</pre>
</details>

**Comment by janpio** [comment]
You were using `pilot`/`upload_to_testflight` to upload the build?

Did the upload work in the end as expected?
Did you get any emails from Google regarding that build?

**Comment by rhcpfan** [comment]
> You were using `pilot`/`upload_to_testflight` to upload the build?

I'm uploading the build using the `testflight` action
``` ruby
# Upload the IPA to TestFlight
testflight(username: ENV["APPLE_ID"], app_identifier: ENV["APP_IDENTIFIER"], ipa: "./artifacts/products/" + ipa_filename, skip_submission: true, skip_waiting_for_build_processing: false, changelog: itunes_change_log)
```

> Did the upload work in the end as expected?

Yes, the upload worked as expected.

> Did you get any emails from Google regarding that build?

Did not receive any emails from **Apple** regarding the build (I hope that **Google** doesn't know that I'm uploading builds to TestFlight 😅).

**Comment by janpio** [comment]
Good point re Google 🙈 

Could you maybe get the spaceship logs from `/tmp/spaceship-*.log` for this session? Would be interesting to see the requests and responses being exchanged here.

Your observation of the Upload Date in the Apple UI changing is new to me and could offer insights on how to improve this process here 🚀 👍

**Comment by rhcpfan** [comment]
Unfortunately, I don't seem to find any logs related to spaceship...
