### ISSUE TITLE
FrameIt for Android Apps in Linux Ubuntu 16.04

### ISSUE THREAD

**Issue by mahesh2015** [fastlane/fastlane#13930]
I am using Linux Ubuntu 16.04 for my android app, i have captured all screens while using **fastlane frameit** command and receiving error/wrong output.
I am attaching screenshot regarding my issue. 

Kindly share details how can i fixed this issue for my Android apps?

![beforefabclick_1545111630339_framed](https://user-images.githubusercontent.com/10514274/50139667-5425f800-02c8-11e9-8f74-e304c7735024.png)
![beforefabclick_1545111630339](https://user-images.githubusercontent.com/10514274/50139669-54be8e80-02c8-11e9-9dcc-4ed4b1e9575a.png)

**Comment by janpio** [comment]
What is your error or wrong output?

In general `frameit` is currently more for iOS apps, as you can see with the frame being used. If you want to use it on Android screenshots, you have to make sure they are the same resolution an iOS screenshot would be.

**Comment by mahesh2015** [comment]
Hi janpio,

Thanks for your reply.

I need Frame as Android device and screenshot fit to the frame. But i am getting iOS frame and there is gap from bottom and right after frameif the screenshot.
 
Is there any possibility for support to Android Platform?
or 
Any alternative to fix above mentioned problem.
Please suggest.

**Comment by janpio** [comment]
As I said before, `frameit` only supports iOS frames as far as I know:

> frameit allows you to put a gorgeous device frame around your iOS and macOS screenshots just by running one simple command.

https://docs.fastlane.tools/actions/frameit/

There were multiple tries in the past to add Android support, but nobody actually went through with it and created a PR to add the functionality to `frameit` unfortunately.

**Comment by mahesh2015** [comment]
Hi janpio,

Any possibility to support other platform(**Android**) in near future?

Thanks,
Mahesh.

**Comment by janpio** [comment]
Possible, of course. But nobody is actively working on it right now as far as I know. Would be awesome if you could take a look at it though, if you could use the feature!
