### ISSUE TITLE
New App Store Connect languages

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13938]
![image](https://user-images.githubusercontent.com/183673/50168410-acbabc80-02eb-11e9-9d0e-db3b66bb69ed.png)

Links to https://help.apple.com/app-store-connect/#/deve6f78a8e2

**Comment by iOSGeekster** [comment]
I would like to give this a go, if that's ok?

**Comment by iOSGeekster** [comment]
So.. after diving into the code, as the newbie I am, I'm not sure where to take action. I'm assuming this is regarding Deliver?. Could you give me some pointers? Cheers.

**Comment by janpio** [comment]
Yep, App Store Connect is `deliver` and `pilot` (for the Testflight metadata, if languages are relevant there as well). I would try to find a complete list of languages that were already supported before and look for that in the codebase. Deliver stuff all lives in a `deliver` subfolder, so you should be able to find something there. Then look where it is used and understand what it influences.
