### ISSUE TITLE
Error on pilot

### ISSUE THREAD

**Issue by donnib** [fastlane/fastlane#13932]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I run fastlane pilot and now it fails, it used to work. I am running Fastlane 2.111.
I get ```Spaceship::UnexpectedResponse``` in ```post_for_testflight_review```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[18-Dec-2018 08:18:50 | [08:18:50]: Login to App Store Connect (ixx@xx.com)
-- | --
18-Dec-2018 08:18:52 | [08:18:52]: Login successful
18-Dec-2018 08:18:53 | [08:18:53]: Ready to upload new build to TestFlight (App: xxxxx)...
18-Dec-2018 08:18:54 | [08:18:54]: Going to upload updated app to App Store Connect
18-Dec-2018 08:18:54 | [08:18:54]: This might take a few minutes. Please don't interrupt the script.
18-Dec-2018 08:20:14 | [08:20:14]: iTunes Transporter successfully finished its job
18-Dec-2018 08:20:14 | [08:20:14]: --------------------------------------------------------------------
18-Dec-2018 08:20:14 | [08:20:14]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
18-Dec-2018 08:20:14 | [08:20:14]: --------------------------------------------------------------------
18-Dec-2018 08:20:14 | [08:20:14]: Successfully uploaded the new binary to App Store Connect
18-Dec-2018 08:20:14 | [08:20:14]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
18-Dec-2018 08:20:27 | [08:20:27]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:20:58 | [08:20:58]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:21:29 | [08:21:29]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:22:00 | [08:22:00]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:22:31 | [08:22:31]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:23:01 | [08:23:01]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:23:32 | [08:23:32]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:24:03 | [08:24:03]: Waiting for App Store Connect to finish processing the new build (0.1.2 - 0.1.2.99)
18-Dec-2018 08:24:34 | [08:24:34]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:25:04 | [08:25:04]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:25:36 | [08:25:36]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:26:06 | [08:26:06]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:26:37 | [08:26:37]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:27:08 | [08:27:08]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:27:38 | [08:27:38]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:28:09 | [08:28:09]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
18-Dec-2018 08:28:40 | [08:28:40]: Successfully finished processing the build 0.1.2 - 0.1.2.99
18-Dec-2018 08:28:44 | [08:28:44]: Successfully set the changelog for build
18-Dec-2018 08:28:44 | [08:28:44]: Distributing new build to testers: 0.1.2 - 0.1.2.99
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 | Looking for related GitHub issues on fastlane/fastlane...
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/test_flight/client.rb:330:in `handle_response': [!] <!DOCTYPE html><html lang="en"> (Spaceship::UnexpectedResponse)
18-Dec-2018 08:28:45 | <head>
18-Dec-2018 08:28:45 | <title></title>
18-Dec-2018 08:28:45 | <link rel="stylesheet" href="/styles/main.css">
18-Dec-2018 08:28:45 | <style type='text/css'>
18-Dec-2018 08:28:45 | /*include ../../dist/styles/main.css*/
18-Dec-2018 08:28:45 | </style>
18-Dec-2018 08:28:45 | </head>
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 | <body><div id="wrapper" class="j42">
18-Dec-2018 08:28:45 | <h2>Not Found</h2></div>
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 | <div class="footer">
18-Dec-2018 08:28:45 | <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
18-Dec-2018 08:28:45 | <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
18-Dec-2018 08:28:45 | </div>
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 | <script type='text/javascript'>(function() {
18-Dec-2018 08:28:45 | var isIos = navigator.userAgent.match(/(iPod\|iPhone\|iPad)/);
18-Dec-2018 08:28:45 | document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
18-Dec-2018 08:28:45 | var yearEl = document.getElementById('year');
18-Dec-2018 08:28:45 | if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
18-Dec-2018 08:28:45 | })();
18-Dec-2018 08:28:45 | </script>
18-Dec-2018 08:28:45 |  
18-Dec-2018 08:28:45 | </body>
18-Dec-2018 08:28:45 | </html>
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/test_flight/build.rb:217:in `submit_for_testflight_review!'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/pilot/lib/pilot/build_manager.rb:183:in `distribute_build'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/pilot/lib/pilot/build_manager.rb:108:in `distribute'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
18-Dec-2018 08:28:45 | from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.111.0/bin/fastlane:23:in `<top (required)>'
18-Dec-2018 08:28:45 | from /usr/local/bin/fastlane:22:in `load'
18-Dec-2018 08:28:45 | from /usr/local/bin/fastlane:22:in `<main>'
18-Dec-2018 08:28:45 | An error occurred when executing task 'Fastlane-Deliver'.
18-Dec-2018 08:28:45 | Error: One or more errors occurred.
18-Dec-2018 08:28:45 | fastlane: Process returned an error (exit code 1).]</pre>
</details>

### Environment

<details>
  <pre>[
### Stack

| Key                         | Value                                                                                                                   |
| --------------------------- | ------------------------------------------------                                                         -------------- |
| OS                          | 10.14                                                                                                                   |
| Ruby                        | 2.3.7                                                                                                                   |
| Bundler?                    | false                                                                                                                   |
| Git                         | git version 2.13.0                                                                                                      |
| Installation Source         | ~/.gems/bin/fastlane                                                                                                    |
| Host                        | Mac OS X 10.14 (18A391)                                                                                                 |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versio                                                         ns/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                                                                          |
| Is contained                | false                                                                                                                   |
| Is homebrew                 | false                                                                                                                   |
| Is installed via Fabric.app | false                                                                                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                                             |
| Xcode Version               | 10.1                                                                                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.3       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| signet                    | 0.11.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.4        |
| bundler                   | 1.17.1       |
| unicode-display_width     | 1.4.0        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2018-12-18**
]</pre>
</details>

**Comment by mjooms** [comment]
I am experiencing the same. When the log says 'distributing new build to testers it stops with a 404 Not found page. I looked in the spaceship log and it seems it can't find the following URL:
`DEBUG [17:23:07]: << POST providers/****/apps/*****/builds/****/review: 404 <!DOCTYPE html><html lang="en">`

**Comment by donnib** [comment]
@mjooms hmm, maybe apple changed something...

**Comment by janpio** [comment]
See https://github.com/fastlane/fastlane/issues/13903. Fixed with the next release 🚀
