### ISSUE TITLE
Add notarize action

### ISSUE THREAD

**Issue by berkcebi** [fastlane/fastlane#13949]
Hello, hello. 👋

### Feature Request

Adding macOS specific action to notarize packages.

#### Motivation Behind Feature

Along with macOS Mojave, a notarization service was introduced to validate packages outside of App Store. This service automatically scans Developer ID-signed packages and performs security checks: https://developer.apple.com/developer-id/

There's currently no built-in action that facilitates this process.

#### Feature Description

A new action called `notarize` would:
1. Upload the package to the notarization service, using `xcrun altool`.
2. Query the notarization request perodically using the same command, until it's complete—which currently takes 1 to 2 minutes.
3. In case of failure, download the JSON log file (provided as a url in the response) and pretty print it along with the status message.
4. In case of success, staple the package, using `xcrun stapler staple`.

Here's how it would look like in action, *pun intended*:

<img width="755" alt="screen shot 2018-12-19 at 10 22 56 am" src="https://user-images.githubusercontent.com/447045/50205259-927af000-0378-11e9-9223-ffd89c7fa7fa.png">

As a new action, this change won't have any effect on existing users.

#### Alternatives or Workarounds

As the notarize commands under `xcrun altool` are pretty new, there are currently no built-in actions to perform any of the steps mentioned above. At Zeplin, we're currently notarizing builds using a local action following these steps.

**Comment by berkcebi** [comment]
Happy to open a pull request with the local action we're currently using, let me know!

**Comment by janpio** [comment]
That sounds like a pretty good candidate for a fastlane plugin! You can read more about creating a plugin here: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by berkcebi** [comment]
Just published the plugin at [zeplin/fastlane-plugin-notarize](https://github.com/zeplin/fastlane-plugin-notarize)! 🚀

Let me know if you have any feedback @janpio, or if there's anything left to do, like adding it to the list of available plugins.

**Comment by berkcebi** [comment]
I did, awesome. Thanks for your help!
