### ISSUE TITLE
Log gets truncated

### ISSUE THREAD

**Issue by regetskcob** [fastlane/fastlane#13950]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since a few month out logs get truncated in jenkins. I does not matter whether we use xcpretty or not, the log gets truncated. 

These are the last lines we can see in the formatted log-output
<details>
  <pre>09:34:16 [09:34:16]: ----------------------------------------
09:34:16 [09:34:16]: --- Step: Verifying fastlane version ---
09:34:16 [09:34:16]: ----------------------------------------
09:34:16 [09:34:16]: Your fastlane version 2.111.0 matches the minimum requirement of 2.1.1  ✅
09:34:16 [09:34:16]: ------------------------------
09:34:16 [09:34:16]: --- Step: default_platform ---
09:34:16 [09:34:16]: ------------------------------</pre>
</details>
<br/>
The unformatted log contains the hole log, so these are the last lines from there:
<details>
  <pre>
[09:34:16]: [32m----------------------------------------[0m
[09:34:16]: [32m--- Step: Verifying fastlane version ---[0m
[09:34:16]: [32m----------------------------------------[0m
[09:34:16]: Your fastlane version 2.111.0 matches the minimum requirement of 2.1.1  ✅
[09:34:16]: [32m------------------------------[0m
[09:34:16]: [32m--- Step: default_platform ---[0m
[09:34:16]: [32m------------------------------[0m
[09:34:16]: [32mDriving the lane 'ios alpha' 🚀[0m
[09:34:16]: [32m--------------------------------[0m
[09:34:16]: [32m--- Step: clear_derived_data ---[0m
[09:34:16]: [32m--------------------------------[0m
[09:34:16]: Derived Data path located at: /Users/********-ios/Library/Developer/Xcode/DerivedData
[09:34:16]: [32mSuccessfully cleared Derived Data ♻�?[0m
[09:34:16]: [32m-----------------------------[0m
[09:34:16]: [32m--- Step: unlock_keychain ---[0m
[09:34:16]: [32m-----------------------------[0m
[09:34:16]: Unlocking keychain at path: /Users/********-ios/Library/Keychains/login.keychain-db
[09:34:16]: [32m------------------[0m
[09:34:16]: [32m--- Step: sigh ---[0m
[09:34:16]: [32m------------------[0m
  </pre>
</details>

We do not know why the get get's displayed that creepy: `[32m------------------[0m`

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G3025)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.1.1"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Create Adhoc-Distribution-build for upload to www.winworker.de"
  lane :alpha do
    # match(type: "adhoc") # more information: https://codesigning.guide
    clear_derived_data
    unlock_keychain(path: "/Users/_compiler-ios/Library/Keychains/login.keychain", password: ENV["CompileriOS"])
    sigh(app_identifier: 'de.WinWorker.SiebertScale', team_id: 'W938JVZ8EQ', ignore_profiles_with_different_name:true, provisioning_name: 'SiebertScale AdHoc Profile', filename: 'de.WinWorker.SiebertScale-AdHoc.mobileprovision', output_path: '/Users/_compiler-ios/Library/MobileDevice/Provisioning Profiles', skip_install: true, adhoc:true)
    gym(scheme: "SiebertScale-AdHoc", export_method: 'ad-hoc', clean: true) # Build your app - more options available
    # gym(scheme: "AppStore", clean: true, verbose: true, disable_xcpretty: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "de.WinWorker.SiebertScale" # The bundle identifier of your app
apple_id "xxxxxxxxxxx" # Your Apple email address

team_id "xxxxxxx"  # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.2.7        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.15.0       |
| googleauth                | 0.6.7        |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.7.0        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-12-19**
</details>

**Comment by minuscorp** [comment]
Those `�[32m` and `�[0m` are color sequences for the terminal, you can disable color formatting on your logs with the following environment variable: `FASTLANE_DISABLE_COLORS=1`

**Comment by janpio** [comment]
> The unformatted log contains the hole log,

What does "unformatted log" refer to here? Where are you getting these logs from?
Does the lane actually run and finish as it should and produce the expected output?
