### ISSUE TITLE
[question] Can I addings folders or files to xcode project using fastlane without open xcode.app

### ISSUE THREAD

**Issue by plrthink** [fastlane/fastlane#1395]
I want add files for folders dynamically into xcode project, can I do this using fastlane?

**Comment by KrauseFx** [comment]
Sorry, that's not something `fastlane` can do and it's not something we want to implement for now. You should be able to do that using the [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) gem :+1:

**Comment by jcampbell05** [comment]
There are also gems you can use to generate project files based on a template :)
