### ISSUE TITLE
produce wont use my company_name

### ISSUE THREAD

**Issue by PkcDom23** [fastlane/fastlane#13952]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello, 

so Im using fastlane produce to create a new app on dev portal, and on Appstore connect. Since its first app for that account, I need to provide company_name. I do that, I even see fastlane using that company name: 

DEBUG [2018-12-19 13:38:05.64]: Using company_name: xxxx

But the produce action still fails with: 

ERROR [2018-12-19 13:38:13.64]: You must provide a company name to use on the App Store. You must provide a company name to use on the App Store.

Any ideas? 

<details>
  <pre>[[✔] 🚀 
DEBUG [2018-12-19 13:38:05.37]: Checking if there are any plugins that should be loaded...
DEBUG [2018-12-19 13:38:05.37]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2018-12-19 13:38:05.37]: gem 'fastlane-plugin-appcenter' is already installed
+------------------------+---------+------------------+
|                    Used plugins                     |
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-appce  | 0.1.7   | appcenter_upload |
| nter                   |         |                  |
+------------------------+---------+------------------+

DEBUG [2018-12-19 13:38:05.63]: Using username: xxxx
DEBUG [2018-12-19 13:38:05.63]: Using app_identifier: xxx
DEBUG [2018-12-19 13:38:05.63]: Using app_version: 1.0.0
DEBUG [2018-12-19 13:38:05.63]: Using app_name: xxx
DEBUG [2018-12-19 13:38:05.63]: Using team_id: xxx
DEBUG [2018-12-19 13:38:05.64]: Using itc_provider: xx
DEBUG [2018-12-19 13:38:05.64]: Using ipa: /Users/.../Events.ipa
DEBUG [2018-12-19 13:38:05.64]: Using company_name: xxx
INFO [2018-12-19 13:38:05.66]: ------------------------------
INFO [2018-12-19 13:38:05.66]: --- Step: default_platform ---
INFO [2018-12-19 13:38:05.67]: ------------------------------
INFO [2018-12-19 13:38:05.67]: Driving the lane 'ios create_new_xxxx' 🚀
INFO [2018-12-19 13:38:05.67]: 
INFO [2018-12-19 13:38:05.67]: ---------------------
INFO [2018-12-19 13:38:05.67]: --- Step: produce ---
INFO [2018-12-19 13:38:05.67]: ---------------------

+-----------------------------------+---------------------------------------+
|                        Summary for produce 2.111.0                        |
+-----------------------------------+---------------------------------------+
| username                          | xxx                 |
| app_name                          | xxx          |
| app_identifier                    | xxx |
| team_id                           | xxx                            |
| itc_team_id                       | xxx                             |
| enable_services.push_notification | on                                    |
| sku                               | xxx                            |
| platform                          | ios                                   |
| language                          | English                               |
| skip_itc                          | false                                 |
| skip_devcenter                    | false                                 |
+-----------------------------------+---------------------------------------+

Reading keychain entry, because either user or password were empty
Loading session from '/.../cookie'
INFO [2018-12-19 13:38:09.34]: [DevCenter] App 'cxxx' already exists, nothing to do on the Dev Center
Reading keychain entry, because either user or password were empty
Loading session from '/Users/.../cookie'
Looking for App Store Connect Team with ID xxx
INFO [2018-12-19 13:38:12.86]: Creating new app 'xxx' on App Store Connect
WARN [2018-12-19 13:38:13.64]: Lane Context:
INFO [2018-12-19 13:38:13.64]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios create_new_xxx"}
ERROR [2018-12-19 13:38:13.64]: You must provide a company name to use on the App Store. You must provide a company name to use on the App Store.
INFO [2018-12-19 13:38:13.64]: Successfully generated documentation at path '/Users/.../fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | produce          | 7           |
+------+------------------+-------------+

DEBUG [2018-12-19 13:38:13.66]: All plugins are up to date
ERROR [2018-12-19 13:38:13.66]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	You must provide a company name to use on the App Store. You must provide a company name to use on the App Store.]</pre>
</details>

### Environment

<details>
  <pre>[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G4015)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#bundle exec update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lane used for uploading renamed dsym file to appcenter"
  lane :upload_dsym_only do |options| 
    UI.message(options[:dsymPath]) 
    UI.message("\n\n\n=====================================\n uploading dsym to appcenter \n=====================================")
    appcenter_upload(
    api_token: ENV["APPCENTER_API_TOKEN"],
    owner_name: ENV["APPCENTER_OWNER_NAME"],
    app_name: "xxx",
    upload_dsym_only: true,
    dsym: options[:dsymPath]
    )
  end

platform :ios do
  desc "Lane for updating apps under xxx"
  lane :update_xxx_app do |options|
    #UI.message(print(metadata_path))
    produce(
      username: options[:username],
      app_identifier: options[:app_identifier],
      team_id: options[:team_id],
      skip_itc: "true",
      skip_devcenter: "true",
      enable_services: {
        push_notification: "on"
      }
    )
    pem(
      username: options[:username],
      app_identifier: options[:app_identifier],
      active_days_limit: "90",
      p12_password: "xxx",
      generate_p12: true,
      force: true
    )
    cert(
      username: options[:username],
      team_id: options[:team_id]
    )
    sigh(
      username: options[:username],
      app_identifier: options[:app_identifier],
      #readonly: true,
      force: true
    )
    deliver(
      username: options[:username],
      app_identifier: options[:app_identifier],
      app_version: options[:versionNumber],
      team_id: options[:team_id],
      ipa: options[:ipa],
      force: true
    )
  end
    
  desc "Lane for updating apps under xxxx account"
  lane :update_xxxxr_app do |options|
    #UI.message(print(metadata_path))
    produce(
      username: options[:username],
      app_name: options[:app_name],
      app_identifier: options[:app_identifier],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id],
      enable_services: {
        push_notification: "on"
        }
    )
    pem(
      username: options[:username],
      app_identifier: options[:app_identifier],
      active_days_limit: "90",
      p12_password: "xxx",
      generate_p12: true,
      force: true
    )
    cert(
      username: options[:username],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id]
    )
    sigh(
      username: options[:username],
      app_identifier: options[:app_identifier],
      #readonly: true,
      force: true
    )
    deliver(
      username: options[:username],
      app_identifier: options[:app_identifier],
      app_version: options[:versionNumber],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id],
      ipa: options[:ipa],
      force: true
    )
  end

  desc "Lane for creating new apps under an account managed by appmanager"
  lane :create_new_appmanager_app do |options|
    UI.message(options[:company])
    produce(
      username: options[:username],
      app_name: options[:app_name],
      app_identifier: options[:app_identifier],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id],
      company_name: options[:company],
      enable_services: {
        push_notification: "on"
      }
    )
    pem(
      username: options[:username],
      app_identifier: options[:app_identifier],
      active_days_limit: "90",
      p12_password: "xxx",
      generate_p12: true,
      force: true
    )
    cert(
      username: options[:username],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id]
    )
    sigh(
      username: options[:username],
      app_identifier: options[:app_identifier],
      #readonly: true,
      force: true
    )
  end

  desc "Uploading deliverables for new apps under appmanager account"
  lane :upload_new_appmanager_app do |options|
    deliver(
      username: options[:username],
      app_identifier: options[:app_identifier],
      app_version: options[:versionNumber],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id],
      ipa: options[:ipa],
      force: true
    )
  end
end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 0.1.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.4       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| fastimage                 | 2.1.5        |
| bundler                   | 1.17.1       |
| unicode-display_width     | 1.4.0        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| os                        | 1.0.0        |
| psych                     | 2.1.0.1      |
| fastlane-plugin-appcenter | 0.1.7        |
</details>

*generated on:* **2018-12-19**
</details>]</pre>
</details>

**Comment by janpio** [comment]
> DEBUG [2018-12-19 13:38:05.64]: Using company_name: xxx`
is not output from the actual action. Do you have any configuration files besides the `Fastfile`?  Your `fastlane env` didn't include an `Appfile` where I would have expected this to be set. What lane did you execute to get this output?

From looking at the actual `produce` output, this might be a problem because of the app already existing in the dev center. Can you try deleting it there and see if it can then correctly create the app in App Store Connect? (If this works we of course still have a bug to fix, but know what is causing it)

**Comment by janpio** [comment]
How did you supply options to this lane when executing?

Can you try to reproduce with a new app? If it works, then try again with the app already existing only in dev center?

**Comment by PkcDom23** [comment]
Hello!

Today I had a chance to try it with an app that hasn't been created on a dev center either, fastlane was able to create the app on the devcenter, but not on appstore connect. Appstore connect says that I need to provide a company name. 

I supply the options via a python script that gets all the data from our backend, and then this python script calls fastlane through bash... it works for all of the options... except this one, apparently :-)

**Comment by janpio** [comment]
Can you share the complete call that is being generated and then executed? I think that was missing from your previous post.

**Comment by PkcDom23** [comment]
This is the call in from the python script (all the variables are populated when this call is being made):

"os.system("bundle exec fastlane create_new_appmanager_app username:{APPLEUSERNAME} app_identifier:{APPID} app_version:{VERSIONNUMBER} app_name:{APP_NAME} team_id:{TEAM_ID} itc_provider:{ITC_PROVIDER} ipa:{IPA} company_name:{COMPANY}" .format(APPLEUSERNAME=appleusername, APP_NAME="'"+app_name+"'", APPID=app_id, VERSIONNUMBER=version_number, TEAM_ID=team_id, ITC_PROVIDER=team_id_member_center, IPA=ipa, COMPANY=))"

and my fastfile for this lane:

desc "Lane for creating new apps under an account managed by appmanager"
  lane :create_new_appmanager_app do |options|
    UI.message(options[:company])
    produce(
      username: options[:username],
      app_name: options[:app_name],
      app_identifier: options[:app_identifier],
      team_id: options[:itc_provider],
      itc_team_id: options[:team_id],
      company_name: options[:company],
      enable_services: {
        push_notification: "on"
      }
    )

although I do not see the company name in the summary in the console:

[15:56:05]: Driving the lane 'ios create_new_appmanager_app' 🚀
[15:56:05]: 
[15:56:05]: ---------------------
[15:56:05]: --- Step: produce ---
[15:56:05]: ---------------------

+-----------------------------------+--------------------------------------+
|                       Summary for produce 2.114.0                        |
+-----------------------------------+--------------------------------------+
| username                          | appmanager@xxxx.com                |
| app_name                          | The xxx app                |
| app_identifier                    | com.x xxx app
|                                   | hon                                  |
| team_id                           | xxx                           |
| itc_team_id                       | xxx                            |
| enable_services.push_notification | on                                   |
| sku                               | xxx                           |
| platform                          | ios                                  |
| language                          | English                              |
| skip_itc                          | false                                |
| skip_devcenter                    | false                                |
+-----------------------------------+--------------------------------------+


is there an easy way in Ruby how I could tell fastfile to print the variables that it uses for that lane?

**Comment by janpio** [comment]
Are you sure 100% your resulting call actually includes a value for the company?

Also: Your python code adds `company_name` as a param to the call, but your lane seems to expect `options[:company]`.

**Comment by PkcDom23** [comment]
Yes, you are correct ;) That might be it actually, unfortunately I have already submitted that one app. I will test it and let you guys know. 

Its easy to make a mistake like that when I have it heavily parametrized like this, would you happen to know of an easier way, maybe? :-)

**Comment by janpio** [comment]
I would definitely make sure that all the fastlane stuff uses the param names from fastlane, and use the python code that builds the command to switch from your variable naming to the fastlane variables. `team_id: options[:itc_provider], itc_team_id: options[:team_id],` would confuse me as well ;)
