### ISSUE TITLE
setup_circle_ci - upload_to_testflight skip_waiting_for_build_processing: true default 

### ISSUE THREAD

**Issue by export-mike** [fastlane/fastlane#13953]
### Feature Request
Make skip_waiting_for_build_processing: true for CI services or improve documentation. 

#### Motivation Behind Feature
I'm using circle ci and my monthly usage is through the roof for a single project due to apple testflight submissions not being accepted for at least 20minutes. Apple are being quiet about why submissions take so long. 

During this wait period Circle CI or any other CI services will be idle and clocking up wasted billable minutes.

#### Feature Description
Maybe enable skip_waiting_for_build_processing: true as default when environment variable CI=true? 
Or improve documentation for upload_to_testflight for users that will be running this on time based CI services.

#### Alternatives or Workarounds
I'm setting  ```upload_to_testflight(skip_waiting_for_build_processing: true)``` but have only just discovered this option after hitting my Circle CI monthly limit. frustrated by this it would be super useful for other people that follow to not come across this issue.

**Comment by janpio** [comment]
> Or improve documentation for upload_to_testflight for users that will be running this on time based CI services.

How should this be documented in your opinion?

**Comment by export-mike** [comment]
@janpio I would recommend against making it the default behaviour as some people using it right now might be expecting the build to complete when Apple has verified. 

I would though put it in **bold** text in the docs and even display a console output to say: 

> "Uploading and verifying submissions to TestFlight can take sometime, it may use up unexpected minutes in your allotted CI plans. Use skip_waiting_for_build_processing: true to reduce used minutes"

**Comment by janpio** [comment]
Sounds good to me. Are you up to creating a PR? Should be not to hard to find the correct location in code (and docs of course). Let me know if you need any help.

**Comment by export-mike** [comment]
@janpio I've added the docs, my environment is not geared up for ruby i'm getting random errors setting up, as I tried to run bundle.

here's the changes I've made: https://github.com/export-mike/fastlane/commit/f9025d177e96dff6af1d9b14230e7664cfc55bfc

**Comment by janpio** [comment]
Just create a PR here and prefix it with `[WIP]`, then we can go over the change and I can give some feedback.
