### ISSUE TITLE
[action] register_devices: Fastlane rejects new device id for iPhone XS

### ISSUE THREAD

**Issue by halleynora** [fastlane/fastlane#13968]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@halleynora Heyyyyyy 👋 Can you private more details (output of your fastlane execution) and your `fastlane env`? Thanks!

**Comment by halleynora** [comment]
Happy New Year @joshdholtz - sorry for the delay on this.  Let me clean the log a bit and will send you the info shortly

**Comment by halleynora** [comment]
Attempting to add a device for iPhone XS with the following uuid format:
00008020-00142XXXXXXXXXXX        TL iPhone XS

Based on a couple apple support articles:
https://forums.developer.apple.com/thread/108871 
https://forums.developer.apple.com/thread/108848

let me know if you need anything else.. Thanks!

[18:38:16]: --- Step: register_devices ---
[18:38:16]: ------------------------------
Available session is not valid any more. Continuing with normal login.
[18:38:18]: Fetching list of currently registered devices...
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | ios                 |
| PLATFORM_NAME    | ios                 |
| LANE_NAME        | ios ****_distrib |
| VERSION_NUMBER   | 1.0.0               |
+------------------+---------------------+
[18:38:18]: Invalid device line, please provide a file according to the Apple Sample UDID file (http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip)

+------+-------------------------------------------------+-------------+
|                           fastlane summary                           |
+------+-------------------------------------------------+-------------+
| Step | Action                                          | Time (in s) |
+------+-------------------------------------------------+-------------+
| 1    | Verifying fastlane version                      | 0           |
| 2    | default_platform                                | 0           |
| 3    | xcversion                                       | 1           |
| 4    | Switch to ios verify_version_number lane        | 0           |
| 5    | Switch to ios verify_version_number_common lane | 0           |
| 6    | get_version_number                              | 0           |
| 7    | Switch to ios register_test_devices lane        | 0           |
| 💥   | register_devices                                | 2           |
+------+-------------------------------------------------+-------------+

[18:38:18]: fastlane finished with errors

[!] Invalid device line, please provide a file according to the Apple Sample UDID file (http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip)
[18:38:18]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

**Comment by guiportooo** [comment]
Hello,

We are having the same problem when trying to add an iPhone XS UDID to the register_devices action.

We tried using both alternatives (device.txt file or adding the devices directly to the action body) but neither worked.

**Comment by halleynora** [comment]
I upgraded to the latest and this is still a issue.
