### ISSUE TITLE
IOS Supply fail to upload to appstore/testflight - Transporter transfer failed

### ISSUE THREAD

**Issue by DanGDroid** [fastlane/fastlane#13960]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
uploading ipa with testflight action fails after 8 min wait:

``` 
[11:52:51]: Going to upload updated app to App Store Connect
[11:52:51]: This might take a few minutes. Please don't interrupt the script.
[12:00:17]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[12:00:17]: Transporter transfer failed.
[12:00:17]:
[12:00:17]: Could not start delivery: all transports failed diagnostics
[12:00:18]: [iTMSTransporter]   at com.signiant.interactivetransfer.engine.TransferEngine$8.run(TransferEngine.java:4060)

[12:00:18]: [iTMSTransporter]

[12:00:18]: [iTMSTransporter] [2018-12-20 12:00:17 IST] <Transport Protocol> DEBUG: Received failed transfer notification; aborting

[12:00:18]: [iTMSTransporter] [2018-12-20 12:00:17 IST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED

[12:00:18]: [iTMSTransporter] [2018-12-20 12:00:17 IST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED

[12:00:18]: [iTMSTransporter] [2018-12-20 12:00:17 IST] <main> ERROR: Could not start delivery: all transports failed diagnostics

[12:00:18]: [iTMSTransporter]

[12:00:18]: [iTMSTransporter]

[12:00:18]: [iTMSTransporter]

[12:00:18]: [iTMSTransporter] Package Summary:

[12:00:18]: [iTMSTransporter]

[12:00:18]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[12:00:18]: [iTMSTransporter]   /var/folders/n8/lxck8kbx0lg4kfbcf27qkbg40000gn/T/d20181220-36585-19oebu8/1327728378.itmsp - Error Messages:

[12:00:18]: [iTMSTransporter]           Could not start delivery: all transports failed diagnostics

[12:00:18]: [iTMSTransporter] [2018-12-20 12:00:17 IST] <main> DBG-X: Returning 1

[12:00:18]: iTunes Transporter output above ^
[12:00:18]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.59.0"

default_platform :ios

platform :ios do
  lane :beta do |options|

  # build your iOS
  gym(
    scheme: "Farmer",
  )

  if options[:tag]
    add_git_tag(
      tag: options[:tag]
    )
    end
    if options[:dropbox_path]
      puts "ipa has been saved to your Dropbox path: "+options[:dropbox_path]+"/QA/ipas/"+options[:tag]
        copy_artifacts(
          target_path: options[:dropbox_path]+"/QA/apks/"+options[:tag],
          artifacts: ["*.ipa"]
        )
    end
 
  if options[:push]
       push_to_git_remote(
          local_branch: git_branch
       )
    end
    
  if options[:upload]
    # upload to testFlight
    testflight(distribute_external: false, skip_submission: true, skip_waiting_for_build_processing: true)
    # if set  skip_waiting_for_build_processing: true // cannot distribute_external.
    #  To show the documentation in your terminal, run:
    # $ fastlane action testflight

    # upload bugsnag sourcemap
    sh "../../bugsnag-mapsource-uploader-ios.sh"
  end
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.example" # The bundle identifier of your app
apple_id "me@example.com" # Your Apple email address

team_id "[team_id]" # Developer Portal Team ID
itc_team_name "[team_name]" 

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md



```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.101.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-12-20**
</details></pre>
</details>

when uploading with xcode it takes a long time but success

**Comment by minuscorp** [comment]
Hi! This could mean lots of things, but as it happened to me a while ago, please check that the signing profiles are still active in the Developer Portal, as they can be valid in the local machine but unable to be verified by Apple in the upload process.

**Comment by DanGDroid** [comment]
@minuscorp hi, thanx
i can upload ipa manually and sign and export but fail with fastlate only

**Comment by minuscorp** [comment]
Have you checked that fastlane is using the same conde signing identities that you use to archive manually the ipa?

**Comment by janpio** [comment]
1. You should update your fastlane to a recent version - your are using `2.101.1` which is outdated.
2. `supply` is our tool "for updating Android apps and their metadata on the Google Play Store" - so this can't be right. Are you using `deliver`?
3. If you are, have you tried this: https://docs.fastlane.tools/actions/deliver/#firewall-issues?

**Comment by DanGDroid** [comment]
My mistake
I ment testflight action as you can see in fastfile attached above
Will updating fastlane realy make the difference?

**Comment by janpio** [comment]
The same what I mentioned in 3 applies to Testflight a well: https://docs.fastlane.tools/actions/testflight/#firewall-issues

>  Will updating fastlane realy make the difference?

Possibly. We release new versions of the software when something breaks. Investing time to debug and understand an issue is a waste of time, if it could possibly be resolved by just using the newest version of fastlane. Please update and report back if the problem persists.

**Comment by DanGDroid** [comment]
update to fastlane 2.112.0 solved the issue
thanx
