### ISSUE TITLE
Errors with fastlane match change_password

### ISSUE THREAD

**Issue by Diarrhio** [fastlane/fastlane#13963]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to change the password of our match git repo as described here https://docs.fastlane.tools/actions/match/:

```fastlane match change_password```

I am guided through setting a new password and confirming it, and then entering the url of the git repo. However, it fails to successfully push the changes to the git repo.

I see the following error:

>  Neither files_to_commit nor files_to_delete were provided to the save_changes! method call

Googling that result hasn't turned up anything.

Note that I have the MATCH_PASSWORD environment variable set to the old password. If I remove the environment variable, I get a "bad decrypt. couldn't decrypt the repo" error. I've also removed anything match related from my keychain.

I have also tried running this from both inside and outside a directory that has a fastlane enabled project it in. Same result.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane match change_password
[✔] 🚀 
[12:26:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:26:26]: New passphrase for Git Repo: ************
[12:26:31]: Type passphrase again: ************
[12:26:32]: To not be asked about this value, you can specify it using 'git_url'
[12:26:32]: URL to the git repo containing all the certificates: git@bitbucket.org:XXXXXX/XXXXXXXXXXX.git
[12:26:35]: Cloning remote git repo...
[12:26:35]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:26:40]: 🔓  Successfully decrypted certificates repo
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[12:26:40]: 🔒  Successfully encrypted certificates repo

[!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.3_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.7.0        |
| unicode-display_width     | 1.4.0        |
| plist                     | 3.4.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| dotenv                    | 2.5.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.9.1        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-12-20**
</details></pre>
</details>

**Comment by janpio** [comment]
Can you still get the certificates etc. with the old password from your git repo?

Can you run and post your command with `--verbose` added at the end please?
Can you also post the output of the run without the env var where you get the `bad decrypt` error? (Best also with `--verbose`)

**Comment by Diarrhio** [comment]
> Can you still get the certificates etc. with the old password from your git repo?
Yeah that still works. It looks like it might be successfully changing the encryption of the repo locally and then failing?

> Can you run and post your command with `--verbose` added at the end please?

`MATCH_PASSWORD=XXXXXXX fastlane match change_password --verbose
[✔] 🚀 
[14:37:59]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
 [2018-12-21 14:38:01.02]: New passphrase for Git Repo: ************
 [2018-12-21 14:38:12.36]: Type passphrase again: ************
WARN [2018-12-21 14:38:13.37]: To not be asked about this value, you can specify it using 'git_url'
 [2018-12-21 14:38:13.37]: URL to the git repo containing all the certificates: git@bitbucket.org:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXs.git
INFO [2018-12-21 14:38:16.96]: Cloning remote git repo...
INFO [2018-12-21 14:38:16.96]: If cloning the repo takes too long, you can use the 'clone_branch_directly' option in match.
INFO [2018-12-21 14:38:16.96]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@bitbucket.org:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.git' '/var/folders/cd/05p90gz5595194tblgjd1tgm0000gn/T/d20181221-9082-xwiof1'
INFO [2018-12-21 14:38:16.97]: ▸ Cloning into '/var/folders/cd/05p90gz5595194tblgjd1tgm0000gn/T/d20181221-9082-xwiof1'...
INFO [2018-12-21 14:38:18.68]: ▸ remote: Counting objects: 524, done.
INFO [2018-12-21 14:38:18.87]: ▸ remote: Compressing objects: 100% (174/174), done.
INFO [2018-12-21 14:38:19.51]: ▸ remote: Total 524 (delta 62), reused 0 (delta 0)
INFO [2018-12-21 14:38:19.51]: ▸ Receiving objects: 100% (524/524), 816.62 KiB | 1.25 MiB/s, done.
INFO [2018-12-21 14:38:19.52]: ▸ Resolving deltas: 100% (172/172), done.
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'U93J3972E9.cer'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'T6MHW44RDZ.cer'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'U93J3972E9.p12'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'T6MHW44RDZ.p12'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.55]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.56]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.57]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.57]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.57]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.57]: 🔓  Decrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.57]: 🔓  Successfully decrypted certificates repo
keychain: "/Users/dario/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@bitbucket.org:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138313232313138333735305A00  "20181221183750Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138313232313138333735305A00  "20181221183750Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@bitbucket.org:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.git"
    "type"<uint32>=<NULL>
password has been deleted.
INFO [2018-12-21 14:38:19.67]: 🔒  Encrypted 'U93J3972E9.cer'
INFO [2018-12-21 14:38:19.67]: 🔒  Encrypted 'T6MHW44RDZ.cer'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'U93J3972E9.p12'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'T6MHW44RDZ.p12'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.68]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.69]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.70]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.70]: 🔒  Encrypted 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mobileprovision'
INFO [2018-12-21 14:38:19.70]: 🔒  Successfully encrypted certificates repo
Traceback (most recent call last):
	17: from /usr/local/bin/fastlane:23:in '<main>'
	16: from /usr/local/bin/fastlane:23:in 'load'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/bin/fastlane:23:in '<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in 'take_off'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/commands_generator.rb:24:in 'start'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/commands_generator.rb:172:in 'run'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in 'run!'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in 'run_active_command'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/commands_generator.rb:103:in 'block (2 levels) in run'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/change_password.rb:44:in 'update'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/storage/interface.rb:54:in 'save_changes!'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/storage/interface.rb:54:in 'chdir'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/match/lib/match/storage/interface.rb:76:in 'block in save_changes!'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in 'method_missing'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in 'user_error!': [!] Neither 'files_to_commit' nor 'files_to_delete' were provided to the 'save_changes!' method call (FastlaneCore::Interface::FastlaneError)`

> Can you also post the output of the run without the env var where you get the bad decrypt error? 
Just enters an endless loop of failing to decrypt and prompting me for password
`$ fastlane match change_password --verbose
[✔] 🚀 
[14:47:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
 [2018-12-21 14:47:34.40]: New passphrase for Git Repo: ************
 [2018-12-21 14:47:42.16]: Type passphrase again: ************
WARN [2018-12-21 14:47:43.51]: To not be asked about this value, you can specify it using 'git_url'
 [2018-12-21 14:47:43.51]: URL to the git repo containing all the certificates: git@bitbucket.org:XXXXXXXXXXXXXX.git
INFO [2018-12-21 14:47:47.42]: Cloning remote git repo...
INFO [2018-12-21 14:47:47.42]: If cloning the repo takes too long, you can use the 'clone_branch_directly' option in match.
INFO [2018-12-21 14:47:47.43]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@bitbucket.org:XXXXXXXXXXXXXX.git' '/var/folders/cd/05p90gz5595194tblgjd1tgm0000gn/T/d20181221-9171-18z1k04'
INFO [2018-12-21 14:47:47.45]: ▸ Cloning into '/var/folders/cd/05p90gz5595194tblgjd1tgm0000gn/T/d20181221-9171-18z1k04'...
INFO [2018-12-21 14:47:49.29]: ▸ remote: Counting objects: 524, done.
INFO [2018-12-21 14:47:49.48]: ▸ remote: Compressing objects: 100% (174/174), done.
INFO [2018-12-21 14:47:50.20]: ▸ remote: Total 524 (delta 62), reused 0 (delta 0)
INFO [2018-12-21 14:47:50.20]: ▸ Receiving objects: 100% (524/524), 816.62 KiB | 1.12 MiB/s, done.
INFO [2018-12-21 14:47:50.20]: ▸ Resolving deltas: 100% (172/172), done.
ERROR [2018-12-21 14:47:50.29]: bad decrypt
DEBUG [2018-12-21 14:47:50.29]: Error decrypting '/var/folders/cd/05p90gz5595194tblgjd1tgm0000gn/T/d20181221-9171-18z1k04/certs/enterprise/U93J3972E9.cer'
ERROR [2018-12-21 14:47:50.29]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/dario/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@bitbucket.org:XXXXXXXXXXXXXX.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138313232313138333831395A00  "20181221183819Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138313232313138333831395A00  "20181221183819Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@bitbucket.org:XXXXXXXXXXXXXX.git"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2018-12-21 14:47:50.38]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2018-12-21 14:47:50.38]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2018-12-21 14:47:50.38]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2018-12-21 14:47:50.38]: Passphrase for Git Repo: ************
 [2018-12-21 14:48:25.76]: Type passphrase again: ************
ERROR [2018-12-21 14:48:28.39]: bad decrypt
DEBUG [2018-12-21 14:48:28.39]: Error decrypting '/var/folders/cd/05p90gz5595194tblgjd1tgm0000gn/T/d20181221-9171-18z1k04/certs/enterprise/U93J3972E9.cer'
ERROR [2018-12-21 14:48:28.39]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/dario/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@bitbucket.org:XXXXXXXXXXXXXX.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303138313232313138343832385A00  "20181221184828Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303138313232313138343832385A00  "20181221184828Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@bitbucket.org:XXXXXXXXXXXXXX.git"
    "type"<uint32>=<NULL>`

One thing of note is that the git url I gave it starts with "git@", but the logs show "match_git@". I have no idea if that is of any importance

**Comment by sadiq81** [comment]
I'm also having the same problem both in CI and local mac

**Comment by janpio** [comment]
I looked into the code of this, it looks to me that this is indeed broken:

https://github.com/fastlane/fastlane/blob/713f46dda7c87f6f15b2dd8af0ca6358d3fbb5e3/match/lib/match/change_password.rb#L31-L44
https://github.com/fastlane/fastlane/blob/713f46dda7c87f6f15b2dd8af0ca6358d3fbb5e3/match/lib/match/storage/interface.rb#L49-L79

`save_changes!` does need a param of files to delete or add - and none is supplied from `match change_password`.

This code was recently refactored to introduce a new storage method besides Git (Google Cloud Storage), I suspect this problem was introduced back then.

**Comment by sadiq81** [comment]
Downgrading to "2.108.0" got me working again

**Comment by janpio** [comment]
This is the change that change the behavior during the big rework: https://github.com/fastlane/fastlane/commit/cc282f264f8cefbd8561cd9b1388c75d073307a1#diff-9247345aa448bf200fb963a9cb472922

**Comment by janpio** [comment]
Huh @sadiq81 - the change I pinpointed this to was released with 2.106.0. Maybe I got it wrong... (I notified the correct people that something is broken here)

**Comment by janpio** [comment]
Ok, I found further changes in 2.109.0 that changed the underlying implementation here, so these could also have caused this to break: https://github.com/fastlane/fastlane/pull/13646

**Comment by sadiq81** [comment]
I think it was a work in progress an did not break with 2.106.0

**Comment by joshdholtz** [comment]
Fixing now! 💪
