### ISSUE TITLE
Gem update stuck

### ISSUE THREAD

**Issue by victor** [fastlane/fastlane#1396]
I discovered this after an update of fastlane on my Travis builds got stuck and the build would timeout.
I tried it locally and I can reproduce it as well (so it's not Travis' problem)

When I issue the command `gem update fastlane`, It starts fetching and installing gems but after a while it gets stuck at this point:

```
…
Parsing documentation for retriable-2.1.0
Installing ri documentation for retriable-2.1.0
Installing darkfish documentation for retriable-2.1.0
Parsing documentation for google-api-client-0.9.2
Installing ri documentation for google-api-client-0.9.2
Installing darkfish documentation for google-api-client-0.9.2

```

and then nothing happens. The thing is, I don't even pretend to upload anything to Google Play Store (if that is what the gem is for, I don't even know). Or perhaps it is unrelated and that is just the last gem installed before it breaks?

If I `^C` out of the gem update command and try again, then it says 'nothing to update'. But I can't do that on Travis, so I'd like to know how to avoid that in the future.

**Comment by siemensikkema** [comment]
I encountered this too. I was on 1.59.0 and it happened when updating to 1.62.0.

**Comment by akaralar** [comment]
I encountered this too and was about to post here but it completed as I was typing this. I don't know what took so long though.

**Comment by ohwutup** [comment]
Im going to close this issue as this was likely an issue with ruby gems. `gem update` is unfortunately not something in our control :(.
