### ISSUE TITLE
[Pilot] - Add Testflight Groups to an Existing Build - Possible?

### ISSUE THREAD

**Issue by alombard** [fastlane/fastlane#13970]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Pilot

#### Question Description

My situation:

- I have "Trusted Testers" who are a select group of Beta testers who get builds in advance of general beta testers.  This is a specific group in Testflight.

- I have "External Beta Testers" (also a group in Testflight) who are a wider group of Beta testers who get builds after being vetted by "Trusted Testers".

At the moment I'm building and distributing **two builds** so that after email approval (we are using Azure Release Pipelines) I can kick off a Fastlane deployment to "External Beta Testers".  

The challenge is that this takes twice as long as to generate two builds, as well as needing to wait for processing and submission to ITC when the build is actually **identical** (aside from an incremented build number).  

My question - is this the most efficient way to do this?  
Can I run a Pilot command to simply add a Testflight group to an existing build?

Thanks in advance and sorry if I missed this anywhere in the docs!

Andrew

**Comment by nachocifu** [comment]
+ 1

**Comment by olyckne** [comment]
I was just looking for this feature. Have you tried to make it work @alombard?
My ruby skills are quite poor but I might be able to take a stab at it otherwise :)

**Comment by janpio** [comment]
Welcome to the club @olyckne - didn't prevent me from becoming a regular contributor here. Just post here if you have any questions, always to happy to help and point newbies in the right direction ❤️

**Comment by risQQ** [comment]
Maybe it helps somebody.
As my ruby skills are not that good, I created a lane that submits the last uploaded build for an app for review, adds a single group by name and pushes a git tag for that app version. 
It is used for multiple targets by the help of the wonderful [ENV](https://docs.fastlane.tools/faqs/#multiple-targets-of-the-same-underlying-app) to determine the various identifiers for the different Targets/Teams.
You could create a second lane without the "submit_for_testflight_review" part to just add another group.

```
lane :pushLastBuildToExternalBeta do | options |

	UI.message("Login to ITC")
	Spaceship::Tunes.login
	Spaceship::Tunes.client.team_id = ENV['TEAM_IDENTIFIER_ITC']
	
	UI.message("Load App")
	app = Spaceship::Tunes::Application.find(ENV['BUNDLE_IDENTIFIER'])
	
	UI.message("App trains: #{app.all_build_train_numbers}")
	all_trainNumbers = app.all_build_train_numbers.sort
	
	train = app.build_trains[all_trainNumbers.last]
	build = train.first
	UI.message("Selected build #{build.train_version} (#{build.build_version})")
    
        UI.message("Submitting to Beta App Review...")
	build.submit_for_testflight_review!
	
	UI.message("Adding group #{options[:group]}...")
	group = Spaceship::TestFlight::Group.find(app_id: app.apple_id, group_name:"#{options[:group]}")
	build.add_group!(group)

	add_git_tag(tag: "Beta/#{ENV['SCHEME']}_#{build.build_version}")
	push_git_tags
end
```

You would call it like this:
` bundle exec fastlane pushLastBuildToExternalBeta group:yourGroup --env yourEnv `

**Comment by feef** [comment]
This is gold ^^ just one note, for anyone Ruby-incompetent like me, you need to have this at the top of the file containing this method:
> require 'spaceship'

**Comment by risQQ** [comment]
Thank you @feef, you are absolutely right. 
I updated my comment to respect that important part.

**Comment by dill0wn** [comment]
@risQQ Thank you so much for the example! I just tried out some of these commands, but I am getting a bad response on the `Spaceship::TestFlight::Group.find(app_id: app.apple_id, group_name:"#{options[:group]}")` step.

```<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/1407649/apps/1200586542/groups. Reason:
<pre>    Gone</pre></p>
</body>```

I'm not 100% using your script, but stepping through the calls. Both `Group.find` nor `Group.all(app_id: app_id)` give the same response :/

Just curious if you're seeing this also (like a change in the testflight API or something related), or if it's just a configuration issue on my end.

**Comment by risQQ** [comment]
@dill0wn I haven't seen this  before but you don't seem to be alone with this issue. 
See https://github.com/fastlane/fastlane/issues/14521

**Comment by dill0wn** [comment]
thanks @risQQ !
