### ISSUE TITLE
upload_to_testflight failing with `Server error got 500`. Itunes connect says binary is still processing, even though fastlane exits with error 500

### ISSUE THREAD

**Issue by patrikdevlin** [fastlane/fastlane#13977]
### New Issue Checklist

- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`upload_to_testflight` also is failing with `Server error got 500`

I can see that the binary has been uploaded to iTunes Connect but fastlane is returning

```
[13:34:35]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2018.12.21)
[13:35:06]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2018.12.21)
[13:35:36]: Successfully finished processing the build 3.0.2 - 2018.12.21
[13:35:36]: Distributing new build to testers: 3.0.2 - 2018.12.21
[13:35:37]: Server error got 500
```

even though the build has not finished processing. This causes it to error.

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
[13:03:44]: Going to upload updated app to App Store Connect
[13:03:44]: This might take a few minutes. Please don't interrupt the script.
[13:08:37]: iTunes Transporter successfully finished its job
[13:08:37]: --------------------------------------------------------------------
[13:08:37]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[13:08:37]: --------------------------------------------------------------------
[13:08:37]: Successfully uploaded the new binary to App Store Connect
[13:08:37]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[13:08:44]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:09:14]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:09:44]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:10:15]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:10:45]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:11:16]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:11:46]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:12:17]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:12:47]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:13:18]: Waiting for App Store Connect to finish processing the new build (3.0.1 - 2)
[13:13:48]: Successfully finished processing the build 3.0.1 - 2
[13:13:48]: Distributing new build to testers: 3.0.1 - 2
+-----------------------------+--------------------------------------+
|                            Lane Context                            |
+-----------------------------+--------------------------------------+
| DEFAULT_PLATFORM            | ios                                  |
| PLATFORM_NAME               | ios                                  |
| LANE_NAME                   | ios beta                             |
| GIT_REPO_WAS_CLEAN_ON_START | true                                 |
| VERSION_NUMBER              | 3.0.1                                |
| BUILD_NUMBER                | 2                                    |
| IPA_OUTPUT_PATH             | /Users/...  |
|                             | b/..            |
| DSYM_OUTPUT_PATH            | /Users/... |
| XCODEBUILD_ARCHIVE          | /Users/.. |
|                             | ..  |
|                             | ..    |
+-----------------------------+--------------------------------------+
[13:13:49]: Server error got 500

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 3    | ensure_git_branch      | 0           |
| 4    | Switch to ios          | 0           |
|      | build_bump lane        |             |
| 5    | increment_version_num  | 0           |
|      | ber                    |             |
| 6    | increment_build_numbe  | 1           |
|      | r                      |             |
| 7    | build_app              | 172         |
| 💥   | upload_to_testflight   | 609         |
+------+------------------------+-------------+

[13:13:49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Server error got 500, but IPA file still success in TestFlight
    https://github.com/fastlane/fastlane/issues/13452 [open] 21 💬
    2 days ago

➡️  beta_pa path is relative to the fastlane directory, not the project directory
    https://github.com/fastlane/fastlane/issues/500 [closed] 4 💬
    22 Sep 2016

➡️  Pilot upload fails with Server error got 500. build.processed? returns true even though the build is still being processed on App Store Connect
    https://github.com/fastlane/fastlane/issues/13776 [open] 25 💬
    3 days ago

and 6 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Server error got 500
</pre>
</details>

### Environment

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.5        |
| addressable               | 2.5.2        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| multi_json                | 1.13.1       |
| jwt                       | 2.1.0        |
| os                        | 1.0.0        |
| psych                     | 2.0.8        |
| uber                      | 0.1.0        |
</details>

**Comment by patrikdevlin** [comment]
@janpio Moved the issue of here. Thank you for the quick response! Let me know if you need anything else

**Comment by janpio** [comment]
What command are you executing?  
If it does not include it yet, rerun with `--verbose` and post its output here.

Spaceship, the library doing the request in the background, has logfiles at `/tmp/spaceship-*.log`. Can you look for the 500 there and post the request and a few requests before and after? The error response should us tell a bit more what is going on here.

**Comment by patrikdevlin** [comment]
@janpio Figured out the issue! Thank you for pointing me to `/tmp/spaceship-*.log`, I was able to debug the issue there. The request was getting blocked because I was missing the encryption compliance in my app. Adding "App Uses Non-Exempt Encryption" in your info.plist and setting it to "NO" did the job

**Comment by janpio** [comment]
Oh, I just saw a comment in spaceship somewhere that this line would be the correct place to handle exactly this case... I guess I should look for that again and make it an issue ;)

**Comment by janpio** [comment]
Could you maybe post the request response you used to understand this problem? I think it would be nice if we could probably handle that case in spaceship and offer a better error message than what you got.

**Comment by patrikdevlin** [comment]
Correct! That does match the output I was getting before the error. And yes see below:

```
INFO  [13:35:05]: >> GET providers/11903123340/apps/1365912788/platforms/ios/trains/3.0.2/builds: [undefined body] 
DEBUG [13:35:06]: << GET providers/11903123340/apps/1365912788/platforms/ios/trains/3.0.2/builds: 200 {"data"=>[{"id"=>nil, "bundleId"=>nil, "trainVersion"=>"3.0.2", "buildVersion"=>"2018.12.21", "uploadDate"=>"2018-12-21T18:31:21.000+0000", "appAdamId"=>1365951788, "providerId"=>119034340, "providerName"=>nil, "developerName"=>nil, "sizeInBytes"=>nil, "internalExpireTime"=>nil, "externalExpireTime"=>nil, "platform"=>"ios", "minOsVersion"=>nil, "iconAssetToken"=>nil, "inviteCount"=>0, "installCount"=>0, "activeTesterCount"=>0, "crashCount"=>0, "internalState"=>"testflight.build.state.processing", "externalState"=>"testflight.build.state.processing", "binaryState"=>nil, "autoNotifyEnabled"=>false, "didNotify"=>false, "cfBundleShortVersion"=>"3.0.2", "cfBundleVersion"=>"2018.12.21"}], "error"=>nil}
INFO  [13:35:36]: >> GET providers/11903123340/apps/1365912788/platforms/ios/trains/3.0.2/builds: [undefined body] 
DEBUG [13:35:36]: << GET providers/11903123340/apps/1365912788/platforms/ios/trains/3.0.2/builds: 200 {"data"=>[{"id"=>37356482, "bundleId"=>"{{BUNDLE ID}}", "trainVersion"=>"3.0.2", "buildVersion"=>"2018.12.21", "uploadDate"=>"2018-12-21T18:35:16.000+0000", "appAdamId"=>1365951788, "providerId"=>119034340, "providerName"=>"{{PROVIDER NAME}}, "developerName"=>"{{NAME}}", "sizeInBytes"=>0, "internalExpireTime"=>"2019-03-21T17:35:16.000+0000", "externalExpireTime"=>"2019-03-21T17:35:16.000+0000", "platform"=>"ios", "minOsVersion"=>"11.0", "iconAssetToken"=>"Purple/v4/61/98/11/61981182-e20c-919e-1e3f-4e481cda5554/Icon-76@2x.png.png", "inviteCount"=>5, "installCount"=>0, "activeTesterCount"=>0, "crashCount"=>0, "internalState"=>"testflight.build.state.export.compliance.missing", "externalState"=>"testflight.build.state.export.compliance.missing", "binaryState"=>"Validated", "autoNotifyEnabled"=>true, "didNotify"=>false, "cfBundleShortVersion"=>"3.0.2", "cfBundleVersion"=>"2018.12.21"}], "error"=>nil}
INFO  [13:35:36]: >> GET providers/119034340/apps/1365951788/builds/37356482: [undefined body] 
DEBUG [13:35:37]: << GET providers/119034340/apps/1365951788/builds/37356482: 500 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /v2/providers/119034340/apps/1365951788/builds/37356482. Reason:
<pre>    Internal Server Error</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

Specifically this part `"internalState"=>"testflight.build.state.export.compliance.missing"`

Does that help at all? Happy to provide more information. Ignore the curly brackets. I replaced project data with that

**Comment by janpio** [comment]
Yes, that's perfect.

We have the `testflight.build.state.export.compliance.missing` string already implemented somehow: https://github.com/fastlane/fastlane/search?q=testflight.build.state.export.compliance.missing&unscoped_q=testflight.build.state.export.compliance.missing Someone will have to look into that if this should cover your case or not - and if so why it's not doing what it should.

**Comment by jhandguy** [comment]
I am experiencing the same issue, here are the logs:

```
[01:28:33]: --------------------------------------------------------------------
[01:28:33]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[01:28:33]: --------------------------------------------------------------------
[01:28:33]: Successfully uploaded the new binary to App Store Connect
[01:28:33]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[01:28:34]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
[01:29:05]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:29:36]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:30:08]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:30:39]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:31:10]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:31:42]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:32:12]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:32:43]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:33:14]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 7)
[01:33:45]: Successfully finished processing the build 1.0.0 - 7
[01:33:46]: Could not set changelog: Server error got 500
```

Maybe you could point me to where the problem stands and I could take a look, I'm not a Ruby expert but who knows 😉

**Comment by janpio** [comment]
Ok, let's start to investigate:

Your and @patrikdevlin's output show an upload, then a polling "Waiting for App Store Connect ..." and then a "Successfully finished processing the build". Then a next request fails with an error 500.

But here your output and @patrikdevlin 's are different: He has an additional "Distributing new build to testers: 3.0.1 - 2" line and then the error "Server error got 500", you do **not** have this line and then as error "Could not set changelog: Server error got 500".

So your problem is not identical, although it can of course have the same underlying reason.

---

@patrikdevlin posted the last few requests from his spaceship logs https://github.com/fastlane/fastlane/issues/13977#issuecomment-449524289. If you compare the second and forth line of this log, you see that the build _did_ leave `testflight.build.state.processing` state, but went to `testflight.build.state.export.compliance.missing`:

![image](https://user-images.githubusercontent.com/183673/50651945-37a2e480-0f85-11e9-8ef9-eb1f3a4e8a6a.png)

`testflight.build.state.export.compliance.missing` is not handled and accounted for in https://github.com/fastlane/fastlane/blob/0ee7c6629c60d71c8cbef4787bc534fabfe7b4d2/pilot/lib/pilot/build_manager.rb#L174, which is why the next request will fail with an error 500 for @patrikdevlin.

---

The solution for @patrikdevlin 's problem thus will be to understand what we could do at that moment: Just give the user a friendly pointer to add the it to the Info.plist?
https://github.com/fastlane/fastlane/search?q=testflight.build.state.export.compliance.missing also indicates that we already do some kind of handling for this, so we have to understand what is going on there and see if this is relevant for this problem as well.

---

For you @jhandguy, you should check your spaceship logs as well and see if those are similar. If so, let us know here. If not, best directly create a new issue with all your information and then link to it here - then we can take another look.

**Comment by anushkmittal** [comment]
bump same issue.

**Comment by anushkmittal** [comment]
same issue even though I have export compliance. running on latest release.


```
19:17:30]: ----------------------------------
[19:17:30]: --- Step: upload_to_testflight ---
[19:17:30]: ----------------------------------
[19:17:30]: Login to App Store Connect (anushk@memeois.com)
[19:17:33]: Login successful
[19:17:33]: Ready to upload new build to TestFlight (App: 1444740049)...
[19:17:39]: Going to upload updated app to App Store Connect
[19:17:39]: This might take a few minutes. Please don't interrupt the script.
[19:20:00]: iTunes Transporter successfully finished its job
[19:20:00]: ------------------------------------------------------------------------------------------------------------------
[19:20:00]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[19:20:00]: ------------------------------------------------------------------------------------------------------------------
[19:20:00]: Successfully uploaded the new binary to App Store Connect
[19:20:00]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[19:20:03]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:20:33]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:21:04]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:21:35]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:22:05]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:22:36]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:23:06]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:23:37]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:24:08]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:24:39]: Waiting for App Store Connect to finish processing the new build (1.0 - 7)
[19:25:09]: Successfully finished processing the build 1.0 - 7
[19:25:09]: Distributing new build to testers: 1.0 - 7
+--------------------+---------------------------------------------------------------------------------+
|                                             Lane Context                                             |
+--------------------+---------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                             |
| PLATFORM_NAME      | ios                                                                             |
| LANE_NAME          | ios beta                                                                        |
| IPA_OUTPUT_PATH    | /Users/anushkmittal/Google Drive (anushk@memeois.com)/memeois social/memeois    |
|                    | social.ipa                                                                      |
| DSYM_OUTPUT_PATH   | /Users/anushkmittal/Google Drive (anushk@memeois.com)/memeois social/memeois    |
|                    | social.app.dSYM.zip                                                             |
| XCODEBUILD_ARCHIVE | /Users/anushkmittal/Library/Developer/Xcode/Archives/2019-01-24/memeois social  |
|                    | 2019-01-24 19.15.43.xcarchive                                                   |
+--------------------+---------------------------------------------------------------------------------+
[19:25:10]: Server error got 500

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | build_app            | 109         |
| 💥   | upload_to_testflight | 459         |
+------+----------------------+-------------+

[19:25:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  upload_to_testflight failing with `Server error got 500`. Itunes connect says binary is still processing, even though fastlane exits with error 500
    https://github.com/fastlane/fastlane/issues/13977 [open] 9 💬
    11 minutes ago

➡️  Server error got 500, but IPA file still success in TestFlight
    https://github.com/fastlane/fastlane/issues/13452 [open] 23 💬
    6 hours ago

➡️  beta_pa path is relative to the fastlane directory, not the project directory
    https://github.com/fastlane/fastlane/issues/500 [closed] 4 💬
    22 Sep 2016

and 8 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Server error got 500

```

**Comment by janpio** [comment]
Ugh @anushkmittal. Can you also have a look at your spaceship logs as @patrikdevlin did above? It'S described in the previous comments. Thanks!

**Comment by giann** [comment]
@anushkmittal as mentionned in another issue I managed to go around that issue with this:
```
wait_processing_interval: 100
```
