### ISSUE TITLE
Easier installation of fastlane

### ISSUE THREAD

**Issue by wdcurry** [fastlane/fastlane#13987]
#### Motivation Behind Feature
Installation of, and getting started with fastlane is far too involved and complicated. Sure I can save "a few hours a week" but it may take a few weeks of drudgery, scanning posts, chasing arcane and lengthy terminal commands, and essentially redoing what thousands of other non-deeply-terminal-friendly devs must do.

#### Feature Description
 Pull back and see why all the various stacks are required and see where this can be streamlined, and spend more time removing all the roadblocks, drop a ui in front of it, and make it far easier to start using

#### Alternatives or Workarounds

i LOVE the premise of fastlane, but for techs who work in smaller shops or who prefer to stay above the need to be deep into Ruby/Terminal, this is just so much more work than expected. You need eyes on this who are NOT versed in the tech to show you were this is gone "off the rails".

**Comment by wdcurry** [comment]
Well that wasn’t very helpful. Very bot-centric.

**Comment by KrauseFx** [comment]
Hey @wdcurry,

Thanks for the feedback, and yes I very much understand the problem, and how it might not be optimal for those cases. 

We actually made sure that _fastlane_ works out of the box on the default macOS installation with the pre-installed Ruby, on a new Mac all you need is to install Xcode, and then run

```
sudo gem install fastlane -NV
```

When you talk about `various stacks`, could you tell us a bit more about what you refer to? Ruby is one dependency, and then if you want to build iOS apps, you also need Xcode. Are there any other requirements?

**Comment by wdcurry** [comment]
My comments relate more to the target demographic that fastlane is generally aimed at: mobile app devs. Many of us have little Ruby exposure, and the advanced level of knowledge required to make the magic happens is challenging. 

Like i mentioned, having a fastlane for fastlane, or a wrapper around the requirements was something that i wished i had had before i invested what seemed like more than a week just to get it working "out of the box".  That was a big, thick, solid box :)

Love the energy and effort of it though, and appreciate it.
