### ISSUE TITLE
Provide path to oClint binary 

### ISSUE THREAD

**Issue by ssmiech** [fastlane/fastlane#1399]
First of all, thanks for all the work on Fastlane. We were able to rebuild the pipeline in no time at all, first time in my life didn't have to mess around with provisioning profiles, etc.

We also use `fastlane` to run `oClint` and had to tweak the action slightly. The issue is that we try to follow the [12 factor App](http://12factor.net) specificaly where it comes to dependencies: 
`A twelve-factor app never relies on implicit existence of system-wide packages`, so having a system wide `oClint` is not an option for us. Here's the proposed feature(s):

- `oclint` action could have an option to pass the path to oclint binary that a User can provide,  

- Another option could be for fastlane to come with compiled `oClint` binary and use this one if no path was provided

**Comment by vpolouchkine** [comment]
Great idea! I will share this with the team and see what we can do in a future release. I’ll reopen this ticket and keep you updated when we get a chance to revisit this, stay tuned :+1: If you want to tackle this yourself, check out the [countdown](https://github.com/fastlane/countdown) repo to learn how to contribute to `fastlane`.

**Comment by ssmiech** [comment]
I actually have a solution in place, will send a PR your way later today.

**Comment by vpolouchkine** [comment]
Thanks @ssmiech :+1:
