### ISSUE TITLE
Fastlane deliver init  ||  fastlane init   fails for Mac-app: "cannot find app" with correct identifier and team_id which work for fastlane deliver of iOS-app

### ISSUE THREAD

**Issue by doRadiology** [fastlane/fastlane#13999]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Both 'fastlane init' and 'fastlane deliver init' fail for a MacOS app, for a project and team_id that works fine for the corresponding iOS app (same AppStore account, same team_id).
Message: Could not find app with app identifier '>redacted<' in your App Store Connect account

'fastlane release' correctly builds the app, but creates and .ipa instead of a .pkg and similarly fails to find the app.
Message: Could not find app with app identifier '>redacted<' in your App Store Connect account

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ fastlane deliver init
[16:12:53]: To not be asked about this value, you can specify it using 'username'
[16:12:53]: Your Apple ID Username: redacted
[16:13:01]: Login to App Store Connect (redacted)
[16:13:04]: Login successful
[16:13:04]: The Bundle Identifier of your App: redacted

[!] Could not find app with app identifier 'redacted' in your App Store Connect account (redacted - Team: redacted)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.14.1                                        |
| Ruby                        | 2.2.4                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.17.2 (Apple Git-113)             |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane            |
| Host                        | Mac OS X 10.14.1 (18B75)                       |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                     |
| Is contained                | false                                          |
| Is homebrew                 | true                                           |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode101.app/Contents/Developer/ |
| Xcode Version               | 10.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do

    build_app(workspace: "redacted.xcworkspace", scheme: "redacted",
              include_bitcode: false)

    upload_to_app_store(skip_metadata: true, 
		        skip_screenshots: true,
			submit_for_review: true,
                        automatic_release: true,
                        force: false)

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("redacted") # The bundle identifier of your app
apple_id("redacted") # Your Apple email address

itc_team_id("redacted") # App Store Connect Team ID
team_id("redacted") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.1          |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2018-12-28**
</details></pre>
</details>

**Comment by janpio** [comment]
The `"` in your `Appfile`, `app_identifier` look wrong.

> Both 'fastlane init' and 'fastlane deliver init' fail on Mac, for a project and team_id that works fine for iOS projects.

What does that mean? If it fails on Mac, on what operating system can you successfully run it?

**Comment by doRadiology** [comment]
@janpio 
Thanks for the reply.

> The " in your Appfile, app_identifier look wrong.

The actual app-identifier was redacted. This is not the cause of the problem. 
I had attempted to make this more clear. The text in the uploaded file read:

_Could not find app with app identifier '<redacted>' in your App Store Connect account_

However, GitHub redacted the word <redacted> !! leading to the more unclear empty quotes.


> What does that mean? If it fails on Mac, on what operating system can you successfully run it?

I have edited the sentence to make that more clear. The OS is MacOS. What was meant is: 'fastlane deliver' and 'fastlane init' fail for a MacOS app, even though on the same Mac, using the same AppStore account, 'fastlane deliver' works fine for the corresponding iOS app.

**Comment by janpio** [comment]
> > The " in your Appfile, app_identifier look wrong.
> 
> The actual app-identifier was redacted. This is not the cause of the problem.

... which is why I referred to the `"` characters that look wrong, not the actual app identifier. Did these also change when redacting things?

(The "Complete output when running fastlane, including the stack trace and command used" still is not readable)

**Comment by janpio** [comment]
I edited your issue to just use `redacted` where you redacted some sensitive values, instead of `<redacted>` which browsers don't display as they handle it as HTML tags or Github removes it for the same reasons.

**Comment by josechen01** [comment]
same issue

**Comment by doRadiology** [comment]
This still happens after updating to fastlane-2.116.0
Fastlane release compiles, successfully logs in, then fails to find the app that exists, is referenced using the correct identifier, from the correct team ID

`Could not find app with app identifier 'com.Correct.Identifier' in your App Store Connect account (correct@email.com - Team: 1234567)`

**Comment by doRadiology** [comment]
This still happens after updating to fastlane 2.117.1.
Added 2FA account to AppStoreConnect. Fastlane uses an AppManager Account that does not require 2FA. Login is indeed successful

`Could not find app with app identifier 'com.Correct.Identifier' in your App Store Connect account (correct@email.com - Team: 1234567
`
The app exists, the identifier is correct, the team is the same team mentioned for the iOS counter part of this MacOS app that IS successfully delivered via fastlane.

**Comment by doRadiology** [comment]
This still happens after updating to fastlane 2.119.0
2FA is setup on AppStoreConnect. Fastlane uses an AppManager Account that does not require 2FA. Login is indeed successful

`Could not find app with app identifier 'com.Correct.Identifier' in your App Store Connect account (correct@email.com - Team: 1234567`

The app exists, the identifier is correct, the team is the same team mentioned for the iOS counterpart of this MacOS app that IS successfully delivered via fastlane.

**Comment by labolado** [comment]
I updated to 2.120.0, and met the same problem.

**Comment by FelixII** [comment]
Adding the `platform` parameter resolved a similar issue for me. Try this:

`fastlane deliver init --platform=osx`

**Comment by doRadiology** [comment]
Thanks. Using the platform parameter 'fastlane deliver init' runs successfully. Downloads all metadata and screenshots and the app icon....

a subsequent 'fastlane release' however results in the same error as always: 'Could not find app with app identifier etc' for the exact same app that it just downloaded all metadata for...

**Comment by FelixII** [comment]
You have to add the `platform` parameter to your `Fastfile` as well, e.g.

```
platform :mac do
  lane :release do
    deliver(
      app_identifier: "<Your-Bundle-Identifier>",
      platform: "osx"
    )
  end
end
```

You call this lane by executing `fastlane mac release`.

**Comment by doRadiology** [comment]
Thanks for the follow-up. I had already added the platform parameter to my Fastfile:

```
default_platform(:mac)
platform :mac do
  lane :release do
    build_app(scheme: "SomeScheme")
    upload_to_app_store(skip_metadata: true, 
		        skip_screenshots: true,
			submit_for_review: true,
                        automatic_release: true,
                        force: true)
  end
end
```

I now changed to using deliver:

```
default_platform(:mac)
platform :mac do
  lane :release do
   build_app(scheme: "SomeScheme")
   deliver(
      app_identifier: "com.identifier.app",
      platform: "osx",
      submit_for_review: true,
      force: true,
      run_precheck_before_submit: false,
      automatic_release: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
  end
end
```

Which, as before, successfully builds the app and creates and .ipa and zipped symbols, but now fails with: `Could not find a version to edit for app ...`

This feels like progress, because previously it could not find the app at all. Obviously still getting this wrong.

**Comment by janpio** [comment]
(`deliver` and `upload_to_app_store` are the same thing with different names, so that change makes no difference.)

**Comment by doRadiology** [comment]
@janpio Thanks for enlightening me on the fastlane lingo :-)

As far as the `Could not find app with app identifier com.Correct.Identifier in your App Store Connect account` error goes, this was fixed by adding`app_identifier `to the fastfile!

However, in contrast to using `deliver` for iOS, deliver for mac does not subsequently read the new app version from the project, so I had to manually set that by adding `app_version` to the fastfile.

Then, again in constrat to using `deliver` for iOS apps, when using it as shown above for delivering a mac app, it does not actually create or upload an .ipa but just starts `Waiting for candidate builds to appear...`

This despite that the previous `build_app` step has correctly created an .xcarchive, and the subsequent `deliver` step mentions: `Making sure the latest version on App Store Connect matches 'x.x.x' from the ipa file...`, but as far as I can tell an .ipa was not actually created. Thus: Icon and metadata are successfully delivered but instead of creating and uploading an ipa as deliver for iOS does, with the current settings, deliver just waits for builds to appear, as indicated above.

**Comment by janpio** [comment]
> @janpio Thanks for enlightening me on the fastlane lingo :-)

Yeah, that's all pretty awkward and messy.

`deliver`/`upload_to_app_store` should never actually build anything, not for iOS or Mac. The build has to be done by `gym`/`build_app` so it can later be picked up by following actions.

**Comment by doRadiology** [comment]
I will look into how to have gym create a .pkg for deliver to upload for a MacOS project.
I will shortly mark this issue as resolved, because the original issue has indeed been resolved.

`Could not find app with app identifier 'com.Correct.Identifier' in your App Store Connect account` was solved by adding `app_identifier:  'com.Correct.Identifier' ` as a parameter to `deliver` in the fastfile.

**Comment by janpio** [comment]
Is there anything fastlane could or should do better here, automatically pick up stuff that it does for iOS that it is not doing for Mac? If so, we can create a new issue and try to get this fixed.

**Comment by doRadiology** [comment]
I would love to open a new issue for giving that feedback. What is the best way to do that? Just open a new issue with title 'Suggestions for fastlane for Mac compared to iOS' ?

**Comment by janpio** [comment]
Yep, that works for me.
