### ISSUE TITLE
sigh can't find adhoc

### ISSUE THREAD

**Issue by ermik** [fastlane/fastlane#13997]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane fails to code-sign in sigh after provisioning new identity. Tried both latest and pre #13915 (109.1 output below). We haven't changed our Fastfile/Appfile or our environment prior to this failure, only changes were the update to latest fastlane which didn't help.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>+-------------------------------------+---------------------------------------+
|                          Summary for sigh 2.109.1                           |
+-------------------------------------+---------------------------------------+
| app_identifier                      | [private]             |
| username                            | [private]       |
| force                               | true                                  |
| cert_id                             | [private]                            |
| provisioning_name                   | match AdHoc [private] |
| ignore_profiles_with_different_name | true                                  |
| team_id                             | [private]                            |
| platform                            | ios                                   |
| adhoc                               | true                                  |
| developer_id                        | false                                 |
| development                         | false                                 |
| skip_install                        | false                                 |
| skip_fetch_profiles                 | false                                 |
| skip_certificate_verification       | false                                 |
| readonly                            | false                                 |
+-------------------------------------+---------------------------------------+

INFO [2018-12-28 04:03:28.95]: Starting login with user '[private]'
To run _spaceship_ through a local proxy, use SPACESHIP_DEBUG
Reading keychain entry, because either user or password were empty
Loading session from environment variable
Session loaded from environment variable is not valid. Continuing with normal login.
INFO [2018-12-28 04:03:31.14]: Successfully logged in
INFO [2018-12-28 04:03:31.14]: Fetching profiles...
WARN [2018-12-28 04:03:31.77]: Lane Context:
INFO [2018-12-28 04:03:31.77]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build_only", :ORIGINAL_DEFAULT_KEYCHAIN=>"\"/Users/distiller/Library/Keychains/login.keychain-db\""}
ERROR [2018-12-28 04:03:31.77]: Can't find class 'adhoc'
INFO [2018-12-28 04:03:31.77]: Successfully generated documentation at path '/Users/distiller/repo/fastlane/README.md'

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | git_branch                      | 0           |
| 3    | default_platform                | 0           |
| 4    | setup_circle_ci                 | 0           |
| 5    | upgrade_super_old_xcode_project | 0           |
| 6    | automatic_code_signing          | 0           |
| 7    | update_info_plist               | 0           |
| 8    | Switch to ios build_debug lane  | 0           |
| 💥   | match                           | 7           |
+------+---------------------------------+-------------+
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
RuntimeError: [!] Can't find class 'adhoc'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:207:in `factory'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:321:in `block in all'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:321:in `map!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:321:in `all'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:369:in `find_by_bundle_id'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/sigh/lib/sigh/runner.rb:70:in `fetch_profiles'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/sigh/lib/sigh/runner.rb:24:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/sigh/lib/sigh/manager.rb:8:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/generator.rb:76:in `generate_provisioning_profile'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:188:in `fetch_provisioning_profile'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:77:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:76:in `loop'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:76:in `block in run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:75:in `each'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:75:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:74:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:222:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
Exited with code 1</pre>
</details>

### Environment
CircleCI (locally seeing same issues 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.19.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-10.app/Contents/Developer/                 |
| Xcode Version               | 10.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.109.1 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status      |
| ----------------------------------------------------- | ------- | ------------------ |
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.2   | 🚫 Update available |
| fastlane-plugin-upgrade_super_old_xcode_project       | 0.0.2   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.0.0        |
| bundler                                               | 1.16.6       |
| io-console                                            | 0.4.5        |
| CFPropertyList                                        | 3.0.0        |
| public_suffix                                         | 2.0.5        |
| addressable                                           | 2.5.2        |
| atomos                                                | 0.1.3        |
| babosa                                                | 1.0.2        |
| claide                                                | 1.0.2        |
| colored                                               | 1.2          |
| colored2                                              | 3.1.2        |
| highline                                              | 1.7.10       |
| commander-fastlane                                    | 4.4.6        |
| declarative                                           | 0.0.10       |
| declarative-option                                    | 0.1.0        |
| digest-crc                                            | 0.4.1        |
| unf_ext                                               | 0.0.7.5      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20180417 |
| dotenv                                                | 2.5.0        |
| emoji_regex                                           | 0.1.1        |
| excon                                                 | 0.62.0       |
| multipart-post                                        | 2.0.0        |
| faraday                                               | 0.15.4       |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| faraday_middleware                                    | 0.12.2       |
| fastimage                                             | 2.1.5        |
| gh_inspector                                          | 1.1.3        |
| jwt                                                   | 2.1.0        |
| memoist                                               | 0.16.0       |
| multi_json                                            | 1.13.1       |
| os                                                    | 1.0.0        |
| signet                                                | 0.11.0       |
| googleauth                                            | 0.6.7        |
| httpclient                                            | 2.8.3        |
| mime-types-data                                       | 3.2018.0812  |
| mime-types                                            | 3.2.2        |
| uber                                                  | 0.1.0        |
| representable                                         | 3.0.4        |
| retriable                                             | 3.1.2        |
| google-api-client                                     | 0.23.9       |
| google-cloud-env                                      | 1.0.5        |
| google-cloud-core                                     | 1.2.7        |
| google-cloud-storage                                  | 1.15.0       |
| json                                                  | 2.1.0        |
| mini_magick                                           | 4.5.1        |
| multi_xml                                             | 0.6.0        |
| plist                                                 | 3.4.0        |
| rubyzip                                               | 1.2.2        |
| security                                              | 0.1.3        |
| naturally                                             | 2.2.0        |
| simctl                                                | 1.6.5        |
| slack-notifier                                        | 2.3.2        |
| terminal-notifier                                     | 1.8.0        |
| unicode-display_width                                 | 1.4.0        |
| terminal-table                                        | 1.8.0        |
| tty-screen                                            | 0.6.5        |
| tty-cursor                                            | 0.6.0        |
| tty-spinner                                           | 0.9.0        |
| word_wrap                                             | 1.0.0        |
| nanaimo                                               | 0.2.6        |
| xcodeproj                                             | 1.7.0        |
| rouge                                                 | 2.0.7        |
| xcpretty                                              | 0.3.0        |
| xcpretty-travis-formatter                             | 1.0.0        |
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.2        |
| fastlane-plugin-upgrade_super_old_xcode_project       | 0.0.2        |
</details>

*generated on:* **2018-12-28**
</details>

**Comment by ermik** [comment]
The original issue we tried to resolve was immediately after sigh in gym: 
``` 
❌  error: No profile for team '[private]' matching 'match AdHoc [private]' found: Xcode couldn't find any provisioning profiles matching '[private]/match AdHoc [private]'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target '[private]')
```
Seemingly xcode (10) couldn't find the profile that was just installed.

**Comment by johnknapprs** [comment]
Check out the same issue reported here: https://github.com/fastlane/fastlane/issues/13905

Updating fastlane should correct the problem for `cant find class adhoc`

**Comment by bytenik** [comment]
> Check out the same issue reported here: #13905
> 
> Updating fastlane should correct the problem for `cant find class adhoc`

We've tried latest. That was mentioned in the original post by @ermik.

**Comment by ermik** [comment]
So I suggested this to @bytenik earlier today because`.112` failed locally with same error and it turns out `.112` in CircleCI seems to be working fine. Can you guys please track this as a candidate for future regressions? Thanks.
