### ISSUE TITLE
Passing --version-number=X.X.X doesn't update during Xcode build (gym)

### ISSUE THREAD

**Issue by dombarnes** [fastlane/fastlane#1400]
I am trying to upload a testflight build with fastlane. When I pass 
`fastlane testflight --version-number=3.3.1`
It correctly gets the latest TestFlight build number, increments it, but doesn't set that as the version number when building the project in Xcode, so the upload fails because version 3.3 (currently set in Xcode) is already released in iTunes Connect.
Am I misunderstanding the purpose of the action or have I got something misconfigured in my project/lane perhaps?
````
lane :testflight  
  increment_build_number({  
    build_number: latest_testflight_build_number + 1  
  }) 
  gym(scheme: "TrilbyTV", workspace: "../TrilbyTV.xcworkspace")  
  # snapshot  
  sigh  
  pilot(  
    skip_submission: false,   
    distribute_external: false,  
    changelog: release_notes  
  )  
````
````
[Transporter Error Output]: ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '3.3' is closed for new build submissions"
[16:46:48]: [Transporter Error Output]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [3.3] in the Info.plist file must contain a higher version than that of the previously approved version [3.3]."
````
Sentry: e3ce0a5c0342e1c41a18418ac3dcd7d6

**Comment by vpolouchkine** [comment]
@dombarnes Is this still an issue for you?

**Comment by phpmaple** [comment]
I also have problem

**Comment by vpolouchkine** [comment]
@phpmaple Could you fill in some details per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks.
