### ISSUE TITLE
Not able to run test using fastlane

### ISSUE THREAD

**Issue by animesh1991** [fastlane/fastlane#14008]
> Task :app:dataBindingExportFeaturePackageIdsLiveRelease UP-TO-DATE
> Task :app:dataBindingMergeDependencyArtifactsLiveRelease UP-TO-DATE
> Task :app:transformDataBindingBaseClassLogWithDataBindingMergeGenClassesForLiveRelease UP-TO-DATE
> Task :app:dataBindingGenBaseClassesLiveRelease UP-TO-DATE
> Task :app:javaPreCompileLiveRelease UP-TO-DATE
> Task :app:compileLiveReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**What went wrong:
Execution failed for task ':app:compileLiveReleaseJavaWithJavac'.
> javax/xml/bind/JAXBException**

Can you please explain what went wrong. I tried almost 100 things but not able to figureout

**Comment by janpio** [comment]
Please open a new issue and include all the information that is asked for when using the "bug report" template: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md Thanks.
