### ISSUE TITLE
Error when trying to upload to hockey after gym

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#1401]
Hi,

This is my gym:
`gym(scheme: "PingID Test Enterprise", 
    	clean: true, 
    	configuration: "Adhoc", 
    	use_legacy_build_api: true, 
    	export_method: "enterprise",
    	project: 'myproj.xcodeproj',
    	output_directory: "TEST_BUILD"
    ) `

And this is my hockey:
`hockey(
    	api_token: ENV['HOCKEY_API_TOKEN'],
    	release_type: '3', # Enterprise
    	notes: release_notes,
    	public_identifier: ENV['HOCKEY_TEST_APP_ID'],
    	notify: '0',
    	ipa: "TEST_BUILD/Myapp-TEST.ipa",
    )`

I can see that gym is creating the folder and the ipa inside as it should, but hockey returns error:

/Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/actions/hockey.rb:60:in `run': [!] Error when trying to upload ipa to HockeyApp: {"status"=>"error", "message"=>"Bundle version could not be determined. Please check your meta data and make sure that the bundle identifier matches the value on HockeyApp."} (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:99:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure

**Comment by vpolouchkine** [comment]
Can you try updating to the latest version of `fastlane`?

**Comment by nmayafit** [comment]
Just did. Same issue.
I must say that I build gym 3 times in a row (3 environments) and only if all build success I upload to hockey all 3 versions in a row.
When I tried build->upload only one time for one environment it worked fine.

**Comment by nmayafit** [comment]
This is my exact lane:

`desc "Submit a new Build to Hockeyapp"
  lane :hockeyapp do |options|
  
  	release_notes = File.read("../hockeyapp_release_notes.txt")
    destination = "Hockeyapp"
    
    ##TEST
  	sh "./test_script.sh" # Upgrade build version
    gym(scheme: "MyApp Test Enterprise", 
    	clean: true, 
    	configuration: "Adhoc", 
    	use_legacy_build_api: true, 
    	export_method: "enterprise",
    	project: 'MyApp.xcodeproj',
    	output_directory: "TEST_BUILD"
    ) 
    
	##ORT
    sh "./ort_script.sh" # Upgrade build version
    gym(scheme: "MyApp ORT Enterprise", 
    	clean: true, 
    	configuration: "Adhoc", 
    	use_legacy_build_api: true, 
    	export_method: "enterprise",
    	project: 'MyApp.xcodeproj',
    	output_directory: "ORT_BUILD"
    )
    
    ##PROD
    sh "./prod_script.sh" # Upgrade build version
    gym(scheme: "MyApp Prod", 
    	clean: true, 
    	configuration: "Adhoc", 
    	use_legacy_build_api: true, 
    	export_method: "ad-hoc",
    	project: 'MyApp.xcodeproj',
    	output_directory: "PROD_BUILD"
    ) 
    
    hockey(
    	api_token: ENV['HOCKEY_API_TOKEN'],
    	release_type: '3', # Enterprise
    	notes: release_notes,
    	public_identifier: ENV['HOCKEY_TEST_APP_ID'],
    	notify: '0',
    	ipa: "TEST_BUILD/MyApp-TEST.ipa",
    )
    
    hockey(
    	api_token: ENV['HOCKEY_API_TOKEN'],
    	release_type: '3', # Enterprise
    	notes: release_notes,
    	public_identifier: ENV['HOCKEY_ORT_APP_ID'],
    	notify: '0',
    	ipa: "ORT_BUILD/MyApp-ORT.ipa",
    )
    
    hockey(
    	api_token: ENV['HOCKEY_API_TOKEN'],
    	release_type: '0', # Beta
    	notes: release_notes,
    	public_identifier: ENV['HOCKEY_PROD_APP_ID'],
    	notify: '0',
    	ipa: "PROD_BUILD/MyApp.ipa",
    )
    
    plist = "../Plists/en.lproj/MyApp-test-enterprise-info.plist"
    post_to_slack(scheme: "MyApp Test", destination: destination, plist: plist, username:options[:username])
    
    plist = "../Plists/en.lproj/MyApp-ort-enterprise-info.plist"
    post_to_slack(scheme: "MyApp ORT", destination: destination, plist: plist, username:options[:username])
    
    plist = "../Plists/en.lproj/MyApp-prod-info.plist"
    post_to_slack(scheme: "MyApp Production", destination: destination, plist: plist, username:options[:username])
    
  end`

**Comment by nmayafit** [comment]
The reason I do it like this is that I only want to upload to hockey if all 3 succeeded with building.

**Comment by nmayafit** [comment]
ok,
I don't know how its related to this error, but I put "dsym" file path in hockey config and now it works.

**Comment by vpolouchkine** [comment]
Glad to hear you're up and running.
