### ISSUE TITLE
Fastlane upload to saucelabs

### ISSUE THREAD

**Issue by jplazcano87** [fastlane/fastlane#14013]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How To upload  a build ipa to Sauce labs using curl?

#### Question Description
i have a lane to run appium test in Sauce Labs but before the test can run i need to upload a .ipa file to saucelabs, in the oficial docs there's a curl example https://wiki.saucelabs.com/display/DOCS/Uploading+Mobile+Applications+to+Sauce+Storage+for+Testing

`curl -u <sauce_username>:<sauce_access_key> -X POST -H "Content-Type: application/octet-stream" https://saucelabs.com/rest/v1/storage/<sauce_username>/<upload_filename>?overwrite=true --data-binary @<path/to/your_file_name>` 

but don't know where is the path of the .ipa generated by fastlane or any guide to custom url upload

**Comment by janpio** [comment]
That depends how you are creating your ipa. What does your lane look like that builds your ipa?
