### ISSUE TITLE
PEM crash when exporting certificate with "\x82" from ASCII-8BIT to UTF-8 error

### ISSUE THREAD

**Issue by pballartzinio** [fastlane/fastlane#14019]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When generating a push certificate with pem it seems to generate it but fails on the export. You end up with two files (.pkey and .p12) that are corrupted and the error "\x82" from ASCII-8BIT to UTF-8 is shown.
The expected behavior is to have the certificates generated and exported correctly without errors.

I am using fastlane swift version 2.112 and rvm with ruby 2.4.5.

If you run normal fastlane in ruby (not using swift) it works fine.

##### Command executed

pem(force: force,
            appIdentifier: Constants.bundleId,
            username: Constants.appleID,
            teamId: Constants.bundleId.teamId,
            p12Password: "**********",
            outputPath: Constants.bundleId.outputPath)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>+-------------------+---------------------------------------+
|                  Summary for PEM 2.112.0                  |
+-------------------+---------------------------------------+
| development       | false                                 |
| generate_p12      | true                                  |
| active_days_limit | 30                                    |
| force             | true                                  |
| save_private_key  | true                                  |
| app_identifier    | ******** |
| username          | ********               |
| team_id           | ********                            |
| p12_password      | ********                              |
| output_path       | ./Signing/                            |
+-------------------+---------------------------------------+

[13:46:59]: Starting login with user '********'
[13:47:04]: Successfully logged in
[13:47:04]: Existing push notification profile for '********' is valid for 219 more days.
[13:47:04]: You already have an existing push certificate, but a new one will be created since the --force option has been set.
[13:47:04]: Creating a new push certificate for app '********'.
[13:47:05]: Private key: /Users/********/Signing/********.pkey
+---------------------------+--------------------------------------------------------+
|                                    Lane Context                                    |
+---------------------------+--------------------------------------------------------+
| LANE_NAME                 | generatePushCertificate                                |
| ORIGINAL_DEFAULT_KEYCHAIN | "/Users/********/Library/Keychains/login.keychain-db" |
+---------------------------+--------------------------------------------------------+
[13:47:05]: "\x82" from ASCII-8BIT to UTF-8</pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by mortenholmgaard** [comment]
I have the exact same problem. @joshdholtz

**Comment by mortenholmgaard** [comment]
Please have a look at this - critical error when using fastlane for swift. @janpio

**Comment by mortenholmgaard** [comment]
Please someone take a look at this..

**Comment by janpio** [comment]
I have no experience with Fastlane Swift, most of the other people aroung here have the same problem.

If you want someone to look into this, please provide _all_ necessary steps from installing fastlane to reproducing this problem - including your environment information of course. Then I might be able to invest the time to take a look.

**Comment by mortenholmgaard** [comment]
Install with `fastlane init swift`

Open the Xcode project found under `fastlane/swift/FastlaneSwiftRunner/`
Your fastlane file should have something like this:
```
class Fastfile: LaneFile {
    private func testPushLane() {
        getPushCertificate(development: true,
                           generateP12: true,
                           force: false,
                           savePrivateKey: true,
                           appIdentifier: "com.app.id",
                           username: "appleUsername@mail.com",
                           teamName: "teamName",
                           p12Password: "",
                           outputPath: "./fastlane/certificates/")
    }
}
```

Then run `fastlane testPush` in terminal

I use match so there might be needed something before to make it work - but not sure. See my environment or ask if questions.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1                          |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | da_DK.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    let appleUsername = "x"
    let teamName = "x"

    func firstRunOnNewMachineLane() {
        desc("Setup on new machine")

        let keystorePassword = FastlaneHelper.getAnswerText(
                question: "We need your keystore password this once to avoid asking for it all the time. " +
                        "Type in keystore password (same as mac account password usually)",
                secure: true)
        say(text: environmentVariable(set: ["KeystorePassword": keystorePassword]))
        say(text: "Keystore password: \(environmentVariable(get: "KeystorePassword"))")

        say(text: "Initial setup done - start using the other lanes")
    }

    func setupForDevelopmentLane() {
        desc("Setup Dev, Test and ProdTest")

        say(text: "Keystore password: \(environmentVariable(get: "KeystorePassword"))") //ONLY for test

        ensureAppCreated(configuration: .dev)
        updateSigning(configuration: .dev)
        ensurePush(configuration: .dev, forceCreateNewPushCertificate: true)

        ensureAppCreated(configuration: .test)
        updateSigning(configuration: .test)
        ensurePush(configuration: .test)

        ensureAppCreated(configuration: .prodTest)
        updateSigning(configuration: .prodTest)
        ensurePush(configuration: .prodTest)
    }

    func setupForReleaseLane() {
        desc("Setup Prod")

        let forceCreateNewPushCertificate = FastlaneHelper.getAnswer(
                question: "Create a new push certificate even if it is not expired?")
        ensureAppCreated(configuration: .prod)
        updateSigning(configuration: .prod)
        ensurePush(configuration: .prod, forceCreateNewPushCertificate: forceCreateNewPushCertificate)
    }

    func deployToTestLane(withOptions options: [String: String]?) {
        desc("Distribute test version")

        FastlaneHelper.ensureGitStatus(options: options)

        let isOnReleaseBranch = gitBranch().starts(with: "release")
        let isOnDevelopBranch = gitBranch() == "develop"

        if !isOnReleaseBranch && !isOnReleaseBranch {
            say(text: "Not possible to distribute test version from other that 'develop' branch or a 'release' branch. " +
                    "You are on branch '\(gitBranch())'.")
            return
        }
        if !FastlaneHelper.getAnswer(question: "You are about to make a new test version from '\(gitBranch())' branch. Proceed?") {
            return
        }
        if isOnReleaseBranch {
            sh(command: "git pull --ff-only")
            incrementBuildNumber()
        } else {
            FastlaneHelper.updateVersionNumber(target: "x", alwaysIncrementBuildNumber: true)
            sh(command: "git flow release start release/\(getVersionNumber(target: "x"))")
        }

        var testNotes = FastlaneHelper.getAnswerText(question: "Write a message to the testers here: (End with enter)")
        guard let emails = XHelper.getCrashlyticsEmails() else {
            return
        }

        updateSigning(configuration: .test)
        updateSigning(configuration: .prodTest)

        buildAndSendToCrashlytics(buildConfiguration: "Test", notes: "Test data. \(testNotes)", emails: emails, notifications: true)
        buildAndSendToCrashlytics(buildConfiguration: "ProdTest", notes: "Prod data. \(testNotes)", emails: emails, notifications: false)

        gitAdd()
        gitCommit(path: "*", message: "release: \(getVersionNumber(target: "x")) (\(getBuildNumber()))")
        pushToGitRemote()
        sh(command: "git checkout develop")

        say(text: "Test version send to: \(emails)")
    }

    // swiftlint:disable function_body_length
    func deployToAppstoreLane(withOptions options: [String: String]?) {
        desc("Deploy to Appstore")

        FastlaneHelper.ensureGitStatus(options: options)

        let currentBranch = gitBranch()
        if !currentBranch.starts(with: "release") {
            say(text: "Not possible to distribute version to App store from other that a 'release' branch. " +
                    "You are on branch '\(currentBranch)'.")
            return
        }
        if !FastlaneHelper.getAnswer(question: "You are about to deploy a new version to App store. Proceed?") {
            return
        }
        if FastlaneHelper.getAnswer(question: "Is this a redeploy of this version to App store? (change my build number)") {
            incrementBuildNumber()
        }

        let forceCreateNewPushCertificate = FastlaneHelper.getAnswer(question: "Create a new push certificate even if it is not expired?")
        ensureAppCreated(configuration: .prod)
        updateSigning(configuration: .prod)
        ensurePush(configuration: .prod, forceCreateNewPushCertificate: forceCreateNewPushCertificate)

        let shouldSubmitForReview = FastlaneHelper.getAnswer(question: "Submit for review?")
        let whatsIsNewText = FastlaneHelper.getAnswerText(question: "New in this version - text to Appstore. (End with enter)")

        buildApp(scheme: "x",
                clean: true,
                configuration: "Release",
                silent: true,
                exportMethod: "app-store")

        uploadToAppStore(
                username: appleUsername,
                skipScreenshots: true,
                skipMetadata: true,
                submitForReview: shouldSubmitForReview,
                submissionInformation: """
                                       { add_id_info_limits_tracking: false,
                                       add_id_info_serves_ads: false,
                                       add_id_info_tracks_action: false,
                                       add_id_info_tracks_install: false,
                                       add_id_info_uses_idfa: false,
                                       content_rights_contains_third_party_content: false,
                                       content_rights_has_rights: false,
                                       export_compliance_is_exempt: false,
                                       export_compliance_uses_encryption: false,
                                       export_compliance_encryption_updated: false }
                                       """,
                teamName: teamName,
                releaseNotes: whatsIsNewText,
                app: environmentVariable(get: "PRODUCE_APPLE_ID"))

        gitAdd()
        gitCommit(path: "*", message: "release: \(getVersionNumber(target: "x")) (\(getBuildNumber()))")
        pushToGitRemote()
        sh(command: "git flow release finish \(currentBranch)")
        pushToGitRemote() // will push develop as previous command ends with checkout develop
        sh(command: "git checkout master")
        pushToGitRemote()
        addGitTag(tag: "\(getVersionNumber(target: "x"))_\(getBuildNumber())", buildNumber: "")
        pushGitTags()
        sh(command: "git checkout develop")
    }

    func addTestDeviceLane() {
        desc("Add test device")

        let deviceId = FastlaneHelper.getAnswerText(question: "Device id?")
        let deviceTitle = FastlaneHelper.getAnswerText(question: "Device title? (Name - Device type - Company)")
        registerDevice(name: deviceTitle,
                udid: deviceId,
                teamName: teamName,
                username: appleUsername)

        updateSigning(configuration: .dev)
        updateSigning(configuration: .test)
        updateSigning(configuration: .prodTest)
    }
    
    private func buildAndSendToCrashlytics(buildConfiguration: String, notes: String, emails: String, notifications: Bool) {
        buildApp(scheme: "x",
                clean: true,
                configuration: buildConfiguration,
                silent: true)

        crashlytics(
                crashlyticsPath: "./Crashlytics.framework",
                apiToken: "x",
                buildSecret: "x",
                notes: notes,
                emails: emails,
                notifications: notifications
        )
    }

    private func updateSigning(configuration: Configuration) {
        say(text: "Keystore password: \(environmentVariable(get: "KeystorePassword"))")

        // require that lane firstRunOnNewMachine has been run
        let keychainPassword = environmentVariable(get: "KeystorePassword")

        match(type: configuration == .prod ? "appstore" : "development",
                readonly: false,
                appIdentifier: [configuration.appIdentifier()],
                keychainPassword: keychainPassword)
    }

    private func ensurePush(configuration: Configuration, forceCreateNewPushCertificate: Bool = false) {
        getPushCertificate(development: configuration != .prod,
                generateP12: true,
                force: forceCreateNewPushCertificate,
                savePrivateKey: true,
                appIdentifier: configuration.appIdentifier(),
                username: appleUsername,
                teamName: teamName,
                p12Password: "",
                outputPath: "./fastlane/certificates/")
    }

    private func ensureAppCreated(configuration: Configuration) {
        createAppOnline(
                username: appleUsername,
                appIdentifier: configuration.appIdentifier(),
                appName: "x",
                appVersion: getVersionNumber(target: "x"),
                sku: configuration.appIdentifier(),
                language: "Danish",
                skipItc: configuration != .prod,
                skipDevcenter: false,
                teamName: teamName)
    }
}

enum Configuration {
    case dev, test, prodTest, prod

    func appIdentifier() -> String {
        let identifier = "x"
        switch self {
        case .dev:
            return "\(identifier).dev"
        case .test:
            return "\(identifier).test"
        case .prodTest:
            return "\(identifier).prodtest"
        default:
            return identifier
        }
    }
}

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.17.3       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-02-18**
</details>

**Comment by mortenholmgaard** [comment]
Any news no this?

**Comment by janpio** [comment]
If there are no responses to an issue, nothing happened.

**Comment by mortenholmgaard** [comment]
There is some old issues that has the same error like this issue https://github.com/fastlane/fastlane/issues/3519
They might be releated.
