### ISSUE TITLE
"Can't find class 'adhoc' (RuntimeError)" when running "fastlane sigh" to download profiles

### ISSUE THREAD

**Issue by LizCira** [fastlane/fastlane#14014]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is definitely related to https://github.com/fastlane/fastlane/issues/13997 but seems like a different use case, since I'm only trying to download profiles using sigh, but not as part of a bigger build script (I have a script that downloads profiles to a mac server farm that makes sure all the machines have the same profiles.) This has worked for over a year with very minimal maintenance, so thank you!

I run the below loop to log in and download several accounts, and I believe the only relevant part is the "system" command

```
def sync_profiles_with_s3(apple_account)
  @bucket_name = "my-bucket"
  @directory_path = "/Users/me/mobileprovision_master/all_profiles"

  apple_account.each do |account_name, account_number |
    puts "STARTING DOWNLOAD: #{account_name}"
    FileUtils.mkdir_p(@directory_path)
    puts @directory_path
    Dir.chdir(@directory_path)
    system("echo '#{account_number}' | fastlane sigh download_all --skip_install -o '/Users/me/mobileprovision_master/all_profiles'")
    puts "DONE DOWNLOADING #{account_name}"
    delete_empty_profiles
    s3_amazon_upload
    FileUtils.rm_rf(Dir.glob("#{@directory_path}/*"))
  end
end 
```
My theory is apple added another possible return value here (https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/provisioning_profile.rb#L197) "adhoc" with a recent backend update that's not provided for (maybe it was previously covered with 'store' since Appstore and Adhoc are very similar)? 

If I add an "adhoc" case that returns "Appstore" my script seems to download everything as expected. 

```
          klass = case attrs['distributionMethod']
                  when 'limited'
                    Development
                  when 'store'
                    AppStore
                  when 'inhouse'
                    InHouse
                  when 'direct'
                    Direct # Mac-only
                  when 'adhoc'
                    AppStore
                  else
                    raise "Can't find class '#{attrs['distributionMethod']}'"
                  end
```
Unfortunately I don't have time to uderstand why this works any better right now, but hopefully it will help with troubleshooting the issue. 

##### Complete output when running fastlane, including the stack trace and command used

I get the following error when it tries to log into ONE of three, accounts, which is very odd--the two other accounts perform as expected, and all three accounts include many Adhoc, Appstore, and Dev profiles. 

```
and 2 more at: https://github.com/fastlane/fastlane/search?q=uninitialized%20constant%20Class%3A%3AAppstore&type=Issues&utf8=✓
/usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.39.0/lib/spaceship/portal/provisioning_profile.rb:168:in `factory': [31m[!] uninitialized constant Class::adhoc[0m (NameError)
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.39.0/lib/spaceship/portal/provisioning_profile.rb:256:in `block in all'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.39.0/lib/spaceship/portal/provisioning_profile.rb:255:in `map'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.39.0/lib/spaceship/portal/provisioning_profile.rb:255:in `all'
	from /usr/local/rvm/gems/ruby-2.1.2/bundler/gems/fastlane-b71a8e03e78c/sigh/lib/sigh/download_all.rb:10:in `download_all'
	from /usr/local/rvm/gems/ruby-2.1.2/bundler/gems/fastlane-b71a8e03e78c/sigh/lib/sigh/manager.rb:34:in `download_all'
	from /usr/local/rvm/gems/ruby-2.1.2/bundler/gems/fastlane-b71a8e03e78c/sigh/lib/sigh/commands_generator.rb:66:in `block (2 levels) in run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/rvm/gems/ruby-2.1.2/bundler/gems/fastlane-b71a8e03e78c/sigh/lib/sigh/commands_generator.rb:120:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/bundler/gems/fastlane-b71a8e03e78c/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /usr/local/rvm/gems/ruby-2.1.2/bundler/gems/fastlane-b71a8e03e78c/sigh/bin/sigh:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/sigh:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/sigh:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

Returns an error :( 

<details>
  <pre>[⠦] 🚀 ^C/usr/local/rvm/gems/ruby-2.1.2/gems/fastlane-2.112.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
	from /usr/local/rvm/gems/ruby-2.1.2/gems/fastlane-2.112.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/fastlane-2.112.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'</pre>
</details>

**Comment by LizCira** [comment]
"fastlane env" returns the error from my original post.

**Comment by Neonkoala** [comment]
Updating to the latest fastlane (2.112.0) fixed this issue for me.

**Comment by renatobenks** [comment]
can we close this one? 🤔 

switching the fastlane version to 2.112.0 solved to me as well.
