### ISSUE TITLE
Documentation about Google credentials should mention "Project Lead" as well as "Release Manager" role

### ISSUE THREAD

**Issue by ChuckTownsend** [fastlane/fastlane#14015]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Documentation about Google credentials should mention "Project Lead" as well as "Release Manager".
I think it would be a good idea for these instructions:
https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials
to mention other roles beside Release Manager in this step:

7. Choose Release Manager from the Role dropdown

because the Release Manager role allows one to modify the production track APK.  People reading this documentation may not want to modify (or may not want to be able to modify) the production track.  The Project Lead role allows one to modify all tracks except the production track which is what I found was appropriate for what I need to do.

##### Command executed

fast lane apply -b path-to-APK

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Output was as expected for successful update of the APK in Google Play.
Not relevant for this documentation change request </pre>
</details>

### Environment

<details>
  <pre>Not relevant for this documentation change request.</pre>
</details>

**Comment by janpio** [comment]
Good point. Could you create a PR to https://github.com/fastlane/docs/blob/master/docs/includes/google-credentials.md with the appropriate description? Thanks.

**Comment by janpio** [comment]
Did you have time to find out if you are allowed to do this @ChuckTownsend? Or could you possible do it after work?

**Comment by ChuckTownsend** [comment]
Sorry for the delay. I now have permission to make this change and will create the PR shortly.
