### ISSUE TITLE
[spaceship] Uploading app trailer fails with NoMethodError

### ISSUE THREAD

**Issue by tutipeti** [fastlane/fastlane#14020]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to create a custom action for uploading trailers to App Store Connect - as far as I could see this feature is part of spaceship but isn't being exposed anywhere with an easy to use action.

A quick recap of what I'm doing (for the complete Fastfile see the env section below):

```ruby
app = Spaceship::Tunes::Application.find(app_identifier)
editedVersion = app.edit_version
editedVersion.upload_trailer!(
	video_path,   		   # path to the video
	1,			   # sorting of the video, has to be between 1-3
	"en-US",		   # language where this video needs to be uploaded
	device			   # device to which this video belongs to
)
```

After a long time (uploading these videos really takes long) I get an error in the utilities class of spaceship (see the full stack trace below):
```
/Users/peter.tutervai/.gems/gems/fastlane-2.112.0/spaceship/lib/spaceship/du/utilities.rb:36:in `portrait?': [!] undefined method `[]' for nil:NilClass (NoMethodError)
```

I checked out the fastlane repo and did some debugging. It seems that the temporary file created ([here](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/du/utilities.rb#L47)) for the video preview file is deleted by the time the upload finishes.
Actually it's deleted rather early on, I could confirm this by running the same command with `RUBYOPT=-d` which enables debug mode in the `Tempfile` class.
According to the [documentation](http://ruby-doc.org/stdlib-2.5.0/libdoc/tempfile/rdoc/Tempfile.html#class-Tempfile-label-Explicit+close) the Tempfile will be deleted once Ruby decides to garbage collect the object, which is I guess what happens here.

##### Command executed
Trying to run a custom lane here, see the Fastfile in the Environment section.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ fastlane uploadVideo
[✔] 🚀
[15:23:11]: ----------------------------------------
[15:23:11]: --- Step: Verifying fastlane version ---
[15:23:11]: ----------------------------------------
[15:23:11]: Your fastlane version 2.112.0 matches the minimum requirement of 2.112.0  ✅
[15:23:11]: Driving the lane 'uploadVideo' 🚀
[15:23:11]: /Users/peter.tutervai/code/private/fastlane_video/fastlane/video.mp4
[15:23:11]: Login to App Store Connect (john@appleseed.com)
[15:23:13]: Login successful
[15:23:13]: Looking for application my.app.identifier
[15:23:14]: Selecting version to be edited
[15:23:15]: Uploading trailer... this will take a long time. Go get a 🍺
+---------------+-------------+
|        Lane Context         |
+---------------+-------------+
| PLATFORM_NAME |             |
| LANE_NAME     | uploadVideo |
+---------------+-------------+

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
+------+----------------------------+-------------+

[15:29:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️   undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13959 [open] 8 💬
    a day ago

➡️  Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13877 [open] 1 💬
    3 weeks ago

➡️  [deliver] submit_build, promote build to production: undefined method `select_build' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13809 [open] 12 💬
    3 weeks ago

and 375 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	20: from /usr/local/bin/fastlane:23:in `<main>'
	19: from /usr/local/bin/fastlane:23:in `load'
	18: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/bin/fastlane:23:in `<top (required)>'
	17: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	16: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	15: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	13: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 9: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	 8: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	 7: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	 6: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	 5: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	 4: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	 3: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	 2: from Fastfile:45:in `block in parsing_binding'
	 1: from /Users/peter.tutervai/.gems/gems/fastlane-2.112.0/spaceship/lib/spaceship/tunes/app_version.rb:593:in `upload_trailer!'
/Users/peter.tutervai/.gems/gems/fastlane-2.112.0/spaceship/lib/spaceship/du/utilities.rb:36:in `portrait?': [!] undefined method `[]' for nil:NilClass (NoMethodError)

</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.112.0"

require 'spaceship'

lane :uploadVideo do

	UI.user_error!("ffmpeg needs to be installed for this action - use brew install ffmpeg") if `which ffmpeg`.length == 0

	app_identifier = "my.app.identifier"
	username = "john@appleseed.com"
	device = "iphone6Plus"
	video_path = "video.mp4"

	UI.message("Login to App Store Connect (#{username})")
	Spaceship::Tunes.login(username)
	Spaceship::Tunes.select_team
	UI.success("Login successful")

	UI.message("Looking for application #{app_identifier}")
	app = Spaceship::Tunes::Application.find(app_identifier)

	UI.message("Selecting version to be edited")
	editedVersion = app.edit_version
	UI.user_error!("Could not find a version to edit for app '#{app_identifier}'") unless editedVersion
	
	UI.message("Uploading trailer... this will take a long time. Go get a 🍺")
	editedVersion.upload_trailer!(
		video_path,   		   # path to the video
		1,			   # sorting of the video, has to be between 1-3
		"en-US",		   # language where this video needs to be uploaded
		device			   # device to which this video belongs to
	)

	UI.success("Trailer uploaded, saving..")
	editedVersion.save!
	UI.success("Saved!")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.7.0        |
| unicode-display_width     | 1.4.1        |
| plist                     | 3.5.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| multi_json                | 1.13.1       |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-01-04**
</details>
</pre>
</details>

**Comment by janpio** [comment]
Have you tried with a much smaller video file, if it works then?

**Comment by tutipeti** [comment]
@janpio the video I used was about 78mb (sometimes taking a whopping 7 minutes to upload), I got it down to 12mb now. This one uploads under 90 seconds, but the error is the same.
I'll open a PR with a workaround, but someone needs to check it as I'm not a ruby expert.
