### ISSUE TITLE
Gateway error when downloading reviews

### ISSUE THREAD

**Issue by hhoweson** [fastlane/fastlane#14022]
Ok, so I worked on issue #9968 where I created the functionality to get reviews from all storefronts at once, I have been using this for a while but on some connections, eg. one wifi network but not another,  there will be a gateway error. I would have thought that this would rule out it being a fault at the server end since using a vpn or a different wifi will allow you to connect to the server flawlessly. Is apple blocking Ips or anything? One last thought was that the server may be timing out due to downloading too much data at once? perhaps lowering the number of reviews sent at once from the default 100 would help? I have attached the error it produces:

```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/spaceship/lib/spaceship/client.rb:642:in `parse_response’: <HTML><HEAD> (Spaceship::Client::UnexpectedResponse)
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;ad49d117&#46;1546519269&#46;209f8301
</BODY></HTML>
    from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/spaceship/lib/spaceship/tunes/tunes_client.rb:244:in `applications’
    from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/spaceship/lib/spaceship/tunes/application.rb:53:in `all’
    from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/spaceship/lib/spaceship/tunes/application.rb:59:in `find’
    from ruby/downloadReviews.rb:43:in `block in <main>'
    from ruby/downloadReviews.rb:39:in `each’
    from ruby/downloadReviews.rb:39:in `<main>
```

**Comment by hhoweson** [comment]
Oh and I think I may have just discovered a bug in the latest version where fastlane throws the following error when trying to get reviews from an app with no reviews:

```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/tunes/tunes_client.rb:380:in `block in get_reviews': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/tunes/tunes_client.rb:371:in `loop'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/tunes/tunes_client.rb:371:in `get_reviews'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/tunes/app_ratings.rb:50:in `reviews'
	from ruby/downloadReviews.rb:58:in `block in <main>'
	from ruby/downloadReviews.rb:50:in `each'
	from ruby/downloadReviews.rb:50:in `<main>'
```

I have no idea which version this issue may have crept in, gonna see if i can spot anything in the source code tomorrow after i've had some sleep (:

**Comment by hhoweson** [comment]
Narrowed it down to this line:

`last_review_date = Time.at(all_reviews[-1]['value']['lastModified'] / 1000)`

When the length of the array (all_reviews) is 0 fetching the last element returns undefined so getting parameters of it doesn't go down well, some code needs to be added to check if there are any reviews first and then skip to returning and empty array if there aren't.

**Comment by hhoweson** [comment]
Have created a merge request for the second issue i found concerning getting reviews for an app with no reviews: #14027

Just to be clear: My original issue with the gateway timeout is still at large so help still needed on that please ( :

**Comment by hhoweson** [comment]
Anyone got any advice?

**Comment by joshdholtz** [comment]
@hhoweson Heyyyy 👋 I don't think I have much knowledge on how to help with this one 😔 Have you tried putting some timeouts/sleeps in between paging to see if that helps at all? And what were the results of lowering page size? Did that seem to help at all?

**Comment by hhoweson** [comment]
Haven't tried anything yet, I am starting to suspect the wifi network of the server that runs an automated daily task to get reviews from has been ip banned since It still works well from home, is this something anyone is aware about and is there anything I can do about it?
