### ISSUE TITLE
'ensure in take_off': unintialized constant Fastlane::VERSION

### ISSUE THREAD

**Issue by singhpratik** [fastlane/fastlane#14038]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've updated fastlane to the latest version (2.113.0) and am now getting the following error when running any fastlane command (e.g. fastlane info):
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> 
I am not using any version manager for ruby. My ruby version is 
`ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]`

Xcode version 10.1
Running on MacOS High Sierra 10.13.6
Already tried
Uninstalling ruby and fastlane and re-installing using sudo gem install fastlane
 </pre>
</details>

**Comment by joshdholtz** [comment]
@singhpratik Do you happen to be using the homebrew installation of _fastlane_?

**Comment by singhpratik** [comment]
I used he command `sudo gem install fastlane -NV` 

I was able to resolve the issue by taking the following steps:

1. uninstalled fastlane using `sudo gem uninstall fastlane`
2. Installed rbenv 
3. installed ruby 2.6.0
4. installed fastlane using `sudo gem install fastlane -NV`
