### ISSUE TITLE
[sigh] Sigh is not finding existing and attempts to create a new (Adhoc) provision profile

### ISSUE THREAD

**Issue by sungjin0213** [fastlane/fastlane#14036]
### New Issue Checklist

- [ v ] Updated fastlane to the latest version
- [ v ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ v ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ v ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running fastlane sigh to download a provision profile, it's failing to find existing provision profile and it's trying to create new provision profile almost every time. The provision profile have correct name and the Mac that I'm running this command have correct distribution certificate installed. 

Sometimes this problem does not occurs, but once this problem occurs, it will always try to generate new provision profiles.

As a work around, when I delete the existing provision profile from Apple Developer console and let fastlane generates the provision profile and it seems to be working for at that time, but when I have an Apple Developer account that I don't have admin privilege, it's pain to tell the admin user to do this for me. I don't see why it would make difference whether fastlane creates the provision profile vs manually creating profile in Apple Developer portal since both look identical when I look at them in provision profile section in Apple Developer portal.

Also I have seen this problem resurfacing with provision profiles that have been working flawlessly suddenly not working today.

##### Command executed
export FASTLANE_PASSWORD=#{PASSWORD} && fastlane sigh -n #{PROFILE_NAME} --adhoc -u #{USER_NAME} -q "#{PROFILE_NAME}.mobileprovision" -a #{BUNDLE_ID} -z  --cert_id #{CERT_ID}

##### Complete output when running fastlane, including the stack trace and command used
When Command executed following output prints. I obfuscated sensitive information.

<details>
  <pre>
[14:05:23]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------------------+--------------------------------------+
|                          Summary for sigh 2.113.0                          |
+-------------------------------------+--------------------------------------+
| provisioning_name                   | #{PROFILE_NAME}            |
| adhoc                               | true                                 |
| username                            | #{USER_NAME}  |
| filename                            | #{PROFILE_NAME}.mobileprovision  |
| app_identifier                      | #{BUNDLE_ID}            |
| skip_certificate_verification       | true                                 |
| cert_id                             | #{CERT_ID}                           |
| developer_id                        | false                                |
| development                         | false                                |
| skip_install                        | false                                |
| ignore_profiles_with_different_name | false                                |
| skip_fetch_profiles                 | false                                |
| platform                            | ios                                  |
| readonly                            | false                                |
+-------------------------------------+--------------------------------------+

[14:05:23]: Starting login with user '#{USER_NAME}'
Available session is not valid any more. Continuing with normal login.
[14:05:26]: Successfully logged in
[14:05:26]: Fetching profiles...
[14:05:27]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[14:05:28]: The name '#{USER_NAME}' is already taken, using another one.
[14:05:28]: Creating new provisioning profile for '#{BUNDLE_ID}' with name '#{PROFILE_NAME} 1546977928' for 'ios' platform

Looking for related GitHub issues on fastlane/fastlane...

➡️  Better errors for cert run with insufficient access
    https://github.com/fastlane/fastlane/issues/8325 [closed] 1 💬
    30 May 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Apple provided the following error info:
	You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.113.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| faraday_middleware        | 0.11.0       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| faraday                   | 0.15.4       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| json                      | 2.0.2        |
| bundler                   | 1.16.2       |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2019-01-08**
</details>

**Comment by janpio** [comment]
Does this only happen for `adhoc` profiles?

**Comment by sungjin0213** [comment]
@janpio as far as I seen, yes. I have not seen this fail on non-AdHoc profile.

**Comment by davidattias** [comment]
I have the same issue here when building an app with App Store profile.

**Comment by bitjeep** [comment]
Removing the `adhoc: true` parameter when calling `sigh` to grab the specific provisioning profile I need for adhoc builds fixed the problem for me.
