### ISSUE TITLE
Invalid App Store Icon. The App Store Icon in the asset catalog in 'ExpoKitApp.app' can't be transparent nor contain an alpha channel

### ISSUE THREAD

**Issue by FiveStar0909** [fastlane/fastlane#14047]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane pilot upload issue

##### Command executed
In Expo project, After run expo build:ios , execute fastlane pilot upload
then Invalid App Store Icon. The App Store Icon in the asset catalog in 'ExpoKitApp.app' can't be transparent nor contain an alpha channel happen.
How can fix it?
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by jeromediaz** [comment]
Open your .png icon app with Preview, then File -> Export
select png as format and uncheck the Alpha option
then you will have a png image file without an alpha channel that can be used.

**Comment by FiveStar0909** [comment]
This is expo project, not Xcode project.  Can i see expo project in Xcode?

**Comment by FiveStar0909** [comment]
Resolved this.
