### ISSUE TITLE
Allow no fastfile to be present

### ISSUE THREAD

**Issue by RobDay** [fastlane/fastlane#1404]
We have a whole bunch of smaller frameworks separated out into smaller repositories. It would be pretty cool for Fastlane to have the ability to perform centralized lane actions without the need for a repository-specific fastfile. For our use case, only scan and slack notification will be performed on each of these repositories. 

It may be cool for this feature to utilize the `import_from_git` for doing this. If fastlane is passed a "--fastfile_repo" parameter, it could pull all lanes and actions available from the repository without the need of a Fastfile. It would be something like:
`fastlane --fastfile_repo "someRepository" test`  

It would then run the test lane in the current directory.
I'm not sure if others wild benefit from this functionality. Does anyone have thoughts?

**Comment by KrauseFx** [comment]
One thing you can already do is run actions directly: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#run-actions-directly :+1:

**Comment by RobDay** [comment]
Oh definitely! We've been using that and it's pretty cool. Correct me if I'm wrong, but I don't believe you can run custom actions in the same way. We have a few custom actions in a centralized repository and I wasn't able to call them. If it is not supported, that would be another great feature. 

Running each action serially would be a doable solution, but it may prove useful to define shared lanes across many different projects where the only difference is the scheme being built. It may be a nicer solution to have these actions encapsulated into a shared lane.

**Comment by lacostej** [comment]
@RobDay out of curiosity, what do you earn by having do pass parameter to fastlane instead of an explicit Fastfile containing the `import_from_git` action (https://github.com/fastlane/fastlane_core/blob/master/fastlane/Fastfile) ? The ability to change repository easily ? Note: you could combine this with a FASTLANE_REPO env variable if you wanted.

I am asking because I usually try to avoid having too many parameters to my CLI.

**Comment by RobDay** [comment]
We have a whole bunch of smaller projects that my team builds out (mostly frameworks, a few app targets).  Aside from that, we also build some internal smaller projects for other teams.  Instead of passing around our signing identity, we do the builds to keep our keys secure.  

I'd like to be able to avoid modifying each of these smaller projects to configure Fastlane.  It would be really cool to make a pretty generic shared Fastfile that has common tasks (with a few parameters) that would work across all of these projects.  Then, whenever we needed to build a small project, it would not require any modification to the individual project.

There is definitely utility in having a fastfile for more complex situations for us.  Our bigger apps have a pretty complex fastfile and it does a lot of cool stuff.  For our really small internal apps, however, an entirely shared fastfile would suffice.

My request could also be completed a different way.  Instead of importing the repo from the command line, passing a fastfile as a command line parameter would also allow you to override the default behavior of looking in the current directory.  This would allow our CI box to have a default Fastlane config checked out locally.  Each common job could then simply refer to the fastfile.  The disadvantage of this, though, is that you'd have to manually update the checked out code.

**Comment by ohwutup** [comment]
Hey @RobDay, this is a great suggestion. We are currently working on a new plugin infrastructure that maybe eventually be able to handle cases similar to this. I am going to close this issue for now, but stay on the lookout for the upcoming changes that may help make this easier!
