### ISSUE TITLE
Deliver result into invalid_request while uploading metadata

### ISSUE THREAD

**Issue by jeromediaz** [fastlane/fastlane#14049]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

With deliver
[!] The request could not be completed because:
	invalid_request

on multiple projects.

Might be related to my upgrade to ruby 2.6.0 but not sure.
Bundler version 1.17.3

##### Command executed

bundle exec fastlane deploy

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> DEBUG [2019-01-12 01:25:02.03]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/jod/.rvm/gems/ruby-2.6.0/bin/fastlane)
Spaceship::Tunes::PotentialServerError: [!] The request could not be completed because:
	invalid_request
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/spaceship/lib/spaceship/tunes/tunes_client.rb:443:in `block in update_app_version!'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1458:in `with_tunes_retry'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/spaceship/lib/spaceship/tunes/tunes_client.rb:436:in `update_app_version!'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/spaceship/lib/spaceship/tunes/app_version.rb:403:in `save!'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/deliver/lib/deliver/upload_metadata.rb:253:in `verify_available_languages!'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/deliver/lib/deliver/upload_metadata.rb:72:in `upload'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/deliver/lib/deliver/runner.rb:120:in `upload_metadata'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/deliver/lib/deliver/runner.rb:38:in `run'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:180:in `block (2 levels) in parsing_binding'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/jod/.rvm/gems/ruby-2.6.0/gems/fastlane-2.113.0/bin/fastlane:23:in `<top (required)>'
  /Users/jod/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
  /Users/jod/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :ios


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = 'false'
    
    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
    notification(title: ENV['XCODE_SCHEME'], message: "Screenshots taken")
  end
  
  desc "Quality"
  
  lane :quality do
    #xctool [
    #  "--reporter", "json-compilation-database:compile_commands.json",
    #  "-workspace ../src/Woodpuzzles.xcworkspace",
    #  "-scheme taquin",
    #  "clean",
    #  "build"
    #].join(" ")
    # xctool ["test", "-workspace ../src/Woodpuzzles.xcworkspace", "-scheme taquin", "-sdk iphonesimulator"].join(" ")
    oclint(
      compile_commands: '../deploy-taquin/compile_commands.json',
      select_reqex: /^((?!Pods)[\s\S])*$/,               # Select all files matching this regex
      report_type: 'html',
      max_priority_1: 10,                # The max allowed number of priority 1 violations
      max_priority_2: 100,               # The max allowed number of priority 2 violations
      max_priority_3: 1000,              # The max allowed number of priority 3 violations
      rc: 'LONG_LINE=200'                # Override the default behavior of rules
    ) 
  end
  
  desc "Create push certificates"
  lane :apns do
    pem(development: true, force: true, app_identifier: ENV['XCODE_BUNDLE'], username: ENV['USERNAME'], pem_name: ENV['DEV_PEM'], output_path: 'apns/', generate_p12: false, save_private_key: false)
    pem(development: false, force: true, app_identifier: ENV['XCODE_BUNDLE'], username: ENV['USERNAME'], pem_name: ENV['PROD_PEM'], output_path: 'apns/', generate_p12: false, save_private_key: false)

  end


  desc "Create all screenshots"
  lane :screenshots_all do
    sh "fastlane screenshots --env soho"
    sh "fastlane screenshots --env sdo"
  end

  desc "Create screenshots"
  lane :screenshots do
    snapshot( 
      clear_previous_screenshots: true,
      skip_open_summary: false,
    )
    
    notification(title: ENV['XCODE_SCHEME'], message: "Screenshots taken")
  end

  desc "Resize screenshots"
  lane :resizescreenshots do
    appli = ENV['APPLI']

    sh "./resize.py #{appli} screenshots"
  end

  desc "Upload all screenshots"
  lane :uploadscreenshots_all do
    sh "fastlane uploadscreenshots --env soho"
    sh "fastlane uploadscreenshots --env sdo"
  end

  desc "Upload screenshots"
  lane :uploadscreenshots do
    deliver
    notification(title: ENV['XCODE_SCHEME'], message: "Screenshots and metadata uploaded")
  end
  
  desc "Test screenshots"
  lane :testscreenshots do
    snapshot(languages: (["en-US"]))
  end

  desc "Create all launch images"
  lane :launchimages_all do
    sh "fastlane launchimages --env soho"
    sh "fastlane launchimages --env sdo"
  end
  
  desc "Create launch images"
  lane :launchimages do
    appli = ENV['APPLI']
    
    snapshot(launch_arguments: (["launchimages"]), 
        languages: (["en-US"]), 
        skip_open_summary: true,
        output_directory: "./fastlane/" + appli + "/launchimages",
        devices: ([
            "iPhone 6",
            "iPhone 6 Plus",
            "iPhone SE",
            "iPad Pro (9.7-inch)",
            "iPhone X",
            "iPhone 4s",
            "iPad 2",
            "iPhone XR",
            "iPhone XS Max"
        ]),
        clear_previous_screenshots: true)


    sh "./resize.py #{appli} launchimages"
        
    sh "./copy-launch-images.sh #{appli}"
    
    notification(title: ENV['XCODE_SCHEME'], message: "Launchimages taken")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type:'appstore', app_identifier: ENV['XCODE_BUNDLE'])
    increment_build_number({
      build_number: latest_testflight_build_number({initial_build_number: 0}) + 1
    })
    gym(scheme: ENV['XCODE_SCHEME'], workspace: ENV['XCODE_WORKSPACE']) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy all applications"
  lane :deploy_all do
    sh "fastlane deploy --env soho"
    sh "fastlane deploy --env sdo"
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    match(type:'appstore', app_identifier: ENV['XCODE_BUNDLE'])
    
    #increment_version_number(version_number: ENV['VERSION'])
    #increment_build_number({
    #  build_number: latest_testflight_build_number(version: ENV['VERSION'], initial_build_number: 0) + 1
    #})

    increment_version_number(version_number: ENV['VERSION'])
    get_build_number
    increment_build_number

    gym(scheme: ENV['XCODE_SCHEME'], workspace: ENV['XCODE_WORKSPACE'], export_xcargs: "-allowProvisioningUpdates") # Build your app - more options available
    deliver(force: true, skip_screenshots: true, skip_metadata: false, submit_for_review: true, automatic_release: true)
    
    refresh_dsyms
    
    notification(title: ENV['XCODE_SCHEME'], message: "Deploy finished")

    
  end

  desc "Full deploy all applications"
  lane :fulldeploy_all do
    sh "fastlane fulldeploy --env soho"
    sh "fastlane fulldeploy --env sdo"
  end

  desc "Full deploy"
  lane :fulldeploy do
    match(type:'appstore', app_identifier: ENV['XCODE_BUNDLE'])
    
    #increment_version_number(version_number: ENV['VERSION'])
    #increment_build_number({
    #  build_number: latest_testflight_build_number(version: ENV['VERSION'], initial_build_number: 0) + 1
    #})

    increment_version_number(version_number: ENV['VERSION'])
    get_build_number
    increment_build_number

    gym(scheme: ENV['XCODE_SCHEME'], workspace: ENV['XCODE_WORKSPACE'], export_xcargs: "-allowProvisioningUpdates") # Build your app - more options available
    deliver(force: true, skip_screenshots: false, skip_metadata: false, submit_for_review: true, automatic_release: true)
    
    refresh_dsyms

    notification(title: ENV['XCODE_SCHEME'], message: "Deploy finished")
  end


  lane :refresh_dsyms do
    download_dsyms(app_identifier: ENV['XCODE_BUNDLE'])                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics(api_token: ENV['CRASHLYTICS_API_TOKEN'])   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    notification(title: ENV['XCODE_SCHEME'], subtitle: lane_context[SharedValues::LANE_NAME], message: exception.message)
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['XCODE_BUNDLE'] # The bundle identifier of your app
apple_id  ... # Your Apple email address

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.113.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-appicon                    | 0.14.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| bundler                                    | 1.17.3       |
| forwardable                                | 1.2.0        |
| CFPropertyList                             | 3.0.0        |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.2        |
| atomos                                     | 0.1.3        |
| babosa                                     | 1.0.2        |
| claide                                     | 1.0.2        |
| colored                                    | 1.2          |
| colored2                                   | 3.1.2        |
| highline                                   | 1.7.10       |
| commander-fastlane                         | 4.4.6        |
| declarative                                | 0.0.10       |
| declarative-option                         | 0.1.0        |
| digest-crc                                 | 0.4.1        |
| unf_ext                                    | 0.0.7.5      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20180417 |
| dotenv                                     | 2.6.0        |
| emoji_regex                                | 0.1.1        |
| excon                                      | 0.62.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.15.4       |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.12.2       |
| fastimage                                  | 2.1.5        |
| gh_inspector                               | 1.1.3        |
| jwt                                        | 2.1.0        |
| memoist                                    | 0.16.0       |
| multi_json                                 | 1.13.1       |
| os                                         | 1.0.0        |
| signet                                     | 0.11.0       |
| googleauth                                 | 0.6.7        |
| httpclient                                 | 2.8.3        |
| mime-types-data                            | 3.2018.0812  |
| mime-types                                 | 3.2.2        |
| uber                                       | 0.1.0        |
| representable                              | 3.0.4        |
| retriable                                  | 3.1.2        |
| google-api-client                          | 0.23.9       |
| google-cloud-env                           | 1.0.5        |
| google-cloud-core                          | 1.2.7        |
| google-cloud-storage                       | 1.15.0       |
| json                                       | 2.1.0        |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.5.0        |
| rubyzip                                    | 1.2.2        |
| security                                   | 0.1.3        |
| naturally                                  | 2.2.0        |
| simctl                                     | 1.6.5        |
| slack-notifier                             | 2.3.2        |
| terminal-notifier                          | 1.8.0        |
| unicode-display_width                      | 1.4.1        |
| terminal-table                             | 1.8.0        |
| tty-screen                                 | 0.6.5        |
| tty-cursor                                 | 0.6.0        |
| tty-spinner                                | 0.9.0        |
| word_wrap                                  | 1.0.0        |
| nanaimo                                    | 0.2.6        |
| xcodeproj                                  | 1.7.0        |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.3.0        |
| xcpretty-travis-formatter                  | 1.0.0        |
| fastlane-plugin-appicon                    | 0.14.0       |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
</details>

*generated on:* **2019-01-12**
</details>

**Comment by jeromediaz** [comment]
I can add that this issue appears now on all my projects.

**Comment by mrgrauel** [comment]
Do try to live on the edge. It works for me with the latest nightly build.

_Your fastlane version 2.114.0.beta.20190113200019_

**Comment by jeromediaz** [comment]
tested fastlane nightly build with no luck (but thanks for the suggestion @mrgrauel )
downgraded to ruby 2.5.3 => no more issues ... 👍

**Comment by SEnglishSMP** [comment]
We're having the same issue, but downgrading to a previous version of Ruby isn't an option.

**Comment by SEnglishSMP** [comment]
@mrgrauel, thanks for the suggestion.  Unfortunately, I'm not able to do that.  We're using a Visual Studio Team Services hosted build server. It uses fastlane as part of its iOS publishing task, and that task automatically installs fastlane using the gem installation.

**Comment by nighthawk** [comment]
I'm having the same issue on the latest `fastlane`.

**Comment by nighthawk** [comment]
`deliver` works when I enable `skip_metadata`, but anything related to uploading metadata fails for me with the same `Potential server error received: 'invalid_request'`.

**Comment by eXhausted** [comment]
@nighthawk read above, or use ruby not greater than 2.5.3
