### ISSUE TITLE
Precheck copyright_date issue with conversion of Symbol into Integer

### ISSUE THREAD

**Issue by sase007** [fastlane/fastlane#14046]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

So, I am having issues with precheck fastlane option - I have custom set  `copyright_date: "2017"`, since copyright date in Appstore is set to `2017 company_name`. 
My code is following: 
  <pre>  desc "Check, if build will pass App Store rules"
  lane :check_rules do
    precheck(
      app_identifier: "com.xxx.xxx",
      copyright_date: "2017"
    )
  end
</pre>

  
and it ends up like this: 

  <pre> /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/rule_processor.rb:60:in `[]': [!] no implicit conversion of Symbol into Integer (TypeError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/rule_processor.rb:60:in `block in process_rules'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/rule_processor.rb:58:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/rule_processor.rb:58:in `process_rules'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/rule_processor.rb:49:in `process_app_and_version'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/runner.rb:101:in `check_for_rule_violations'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/precheck/lib/precheck/runner.rb:33:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:14:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.113.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
</pre>

btw. It seems really similar to this issue: 
https://github.com/fastlane/fastlane/issues/9490

Am I doing everything right? 
I think so :-/

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14                                                          |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.18.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14 (18A391)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Update this, if you use features of a newer version
fastlane_version "2.64.0"

default_platform :ios

platform :ios do

  before_all do
    update_fastlane
  end

  desc "Check, if build will pass App Store rules"
  lane :check_rules do
    precheck(
      app_identifier: "com.xxx.xxx",
      copyright_date: "2017"
    )
  end

  desc "Set changelog for all languages"
  lane :changelog do
    set_changelog(
      app_identifier: "com.xxx.xxx"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(
      workspace: "xxx.xcworkspace",
      scheme: "xxx",
    ) 

    upload_symbols_to_crashlytics(
      api_token: "xxx"
    )
    
    testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
    )

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

app_identifier "com.xxx.xxx" # The bundle identifier of your app

apple_id "xxx@xxx.com" # Your Apple email address

team_id "xxx" # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.113.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| bundler                   | 2.0.1        |
| psych                     | 3.1.0        |
</details>

*generated on:* **2019-01-10**
</details>

**Comment by janpio** [comment]
Please post the complete output you are getting, not just the broken part.

**Comment by mollyIV** [comment]
Hey @sase007 @janpio 👋 

I had a look at the code and played a bit with unit tests of `rule_processor.rb` and noticed that the value of parameter `copyright_date` in your lane @sase007 seems to be wrong 😬 

`copyright_date` expects to be set to one of `RULE_LEVELS`:

https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/precheck/lib/precheck/rule.rb#L14-L20

@sase007 could you please try to change your lane to:

```ruby
desc "Check, if build will pass App Store rules"
  lane :check_rules do
    precheck(
      app_identifier: "com.xxx.xxx",
      copyright_date: [level: :skip]
    )
  end
```
🙏 🙇 

As an improvement, maybe we could add an example with copyright date ingnoring to [docs](https://docs.fastlane.tools/actions/precheck/#example)?

```ruby
...
# set to skip to not run the `copyright_date` rule
copyright_date(level: :skip)
```

WDYT?

**Comment by sase007** [comment]
@mollyIV 
Okey, thanks for the reply! I will try it and let you know, but I expect it to be working 👍 

Oh and yes, the lack of documentation for `precheck` is the real problem here as @janpio pointed out. Updating it with examples would be great :-)

**Comment by mollyIV** [comment]
Hey @sase007 , any news about this one? 🤔
