### ISSUE TITLE
Beta upload did not work

### ISSUE THREAD

**Issue by wixvii** [fastlane/fastlane#14045]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
  Yesterday I forced to quit an upload to test flight and after that no longer I can not upload a new build to testflight. The problem is : 
[14:24:17]: ----------------------------------
[14:24:17]: --- Step: upload_to_testflight ---
[14:24:17]: ----------------------------------
[14:24:17]: Login to App Store Connect ********8@icloud.com)
[14:24:21]: Login successful
[14:24:22]: Ready to upload new build to TestFlight (App: ******)...
[14:24:35]: Going to upload updated app to App Store Connect
[14:24:35]: This might take a few minutes. Please don't interrupt the script

It didnt anything after 1-2 hour. It still waiting. There is no problem with my internet connection. I have 150 mb/s upload speed. Fastlane did not do anything after this line, Its just waiting
What should I do ? 

##### Command executed
upload_to_testflight

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by ppamorim** [comment]
I am getting the same problem. Eventually it worked but it's very rare.

**Comment by wixvii** [comment]
> I am having the same problem. Eventually it worked but it's very rare. I was able to upload an app after many tries, I don't know if this is a problem at Apple or on Fastlane.
> What version of Fastlane are you? I was on `2.112.0` and upgraded it right now to `2.113.0`. Will let you know if it works.

Do not know which version is it but  its the last version I checked the update.

**Comment by ppamorim** [comment]
@wixvii Try to downgrade, maybe can solve if it's not a problem at Apple.

**Comment by wixvii** [comment]
Problem was the old version, after I got this problem I updated. Its says "update to upload test flight" what could I do

**Comment by joshdholtz** [comment]
@wixvii Can you provide your the output of `fastlane env`? Its easier to helping knowing what kind of environment you were working on 😊 

Also, were you able to get this working at all after trying multiple time? Or does it get stuck every single time? If it is still getting stuck, can you try running your command with `--verbose` and paste the whole output here so I can see everything that is going on?

Thanks! 💪

**Comment by ppamorim** [comment]
@joshdholtz Updating it to the latest version solved the issue.
