### ISSUE TITLE
Permanently Assigned Specific Bundle ID to Wildcard Enterprise Profile -- Not Intended Behavior (Sigh/ Gym build)

### ISSUE THREAD

**Issue by LizCira** [fastlane/fastlane#1405]
We typically use a wildcard app ID with our Enterprise program. I used “sigh” to manage the profiling while I was trying to prototype Fastlane for our build servers—however, now when I try to build anything with our wildcard bundle ID it’s saying that our wildcard ID is associated with a profile used by the app I was building with our prototype fastfile, and all of our existing builds are failing. 

In the prototype, I used sigh, set credentials for both ITC and the Apple Dev portal with my work Apple ID, and I tried setting the Bundle ID for my demo to “com.[mycompany].randomApp” while using our existing wildcard Enterprise profile. 

The sigh command is:

     sigh( app_identifier: bundle_ID, provisioning_name: xcode_profile )

With the values passed in being a unique bundle ID ("com.[mycompany].randomApp") and the wildcard enterprise profile “Team2_InHouse"

Now any production builds using the wildcard enterprise profile are failing with this error:
  
ERROR: Code Sign error: Provisioning profile does not match bundle identifier: The provisioning profile specified in your build settings (“Team2_InHouse”) has an AppID of “com.[mycompany].randomApp” which does not match your bundle identifier “com.[mycompany].assignedID”.

Do you have any idea where in the Apple dev portal or even iTunes Connect Fastlane may have created this setting? The profile in the dev portal looks normal.  I’ve regenerated the profile and reinstalled it on our build servers, but the error persists, and I feel like it must be stored somewhere on Apple's side now. It seems like com.[mycompany].randomApp is now permanently assigned to this Wildcard profile, but the App ID  com.[mycompany].randomApp doesn’t even really exist in our Enterprise Apple dev account.

Any help much appreciated!

**Comment by KrauseFx** [comment]
Can you share a screenshot of your Xcode project code signing settings? Additionally please install the Quick Look plugin (linked in the `sigh` repo) and send a screenshot of the generated provisioning profile. Also, please share a screenshot of your Bundle ID settings of your project :+1:

**Comment by LizCira** [comment]
Thank you so much for the quick response! We actually set our profiling through our own ruby build scripts in Jenkins (I'm looking at Fastlane because of the excellent community support!) 

I've configured the project in xcode the way it should look, but the building and signing is being done with xcodebuild after checking out the project, and the settings the developer checks the code in with are not the settings it's built with. 

![screen shot 2016-02-23 at 6 16 03 pm](https://cloud.githubusercontent.com/assets/7120551/13270192/7026e3e6-da5a-11e5-96f5-3fa7554fa7ea.png)

![screen shot 2016-02-23 at 6 18 29 pm](https://cloud.githubusercontent.com/assets/7120551/13270194/733ae7e4-da5a-11e5-8411-c6f99428e655.png)
 
![team2_inhouse_quicklook](https://cloud.githubusercontent.com/assets/7120551/13270201/7d9d206c-da5a-11e5-854c-e1c84adc076f.jpg)

Another strange behavior is that the error only occurs 75% of the time, and a few Enterprise builds using this profile have succeeded since the error first appeared. It did start occurring after I was playing with Fastlane builds, and only my prototype project uses "“com.[mycompany].randomApp" so I'm fairly certain this is where it came from.

**Comment by KrauseFx** [comment]
Does that mean you're not using `gym` to build and sign your app? Can you try using it?

**Comment by LizCira** [comment]
I was only using Gym to build and sign my prototype app locally on my laptop.

The error is appearing with unrelated app builds on our Jenkins servers using the same profile I was using for my prototype. 

The gym command from my prototype is: 

    gym(
      scheme: scheme, 
      configuration: configuration, 
      clean: true, 
      include_bitcode: false,
      workspace: ENV["APP_WORKSPACE"],
      output_directory: "./.fastlane/Build/iPAs",
      output_name: scheme + ".ipa",
      codesigning_identity: identity,
      xcargs: "ARCHIVE=YES",
      use_legacy_build_api: true
    )

I don't care about building the prototype for now, I'd just like to repair the previously existing wildcard profile that seems to be linked to the prototype app ID now. In theory, the Jenkins builds that are failing with the codesigning error have no knowledge of my local prototype build, the only link is that I was trying to use the same wildcard profile that we use in production.

**Comment by vpolouchkine** [comment]
@LizCira Is this still an issue?

**Comment by LizCira** [comment]
@vpolouchkine no longer and issue, sorry, I should have closed this. 

For completeness, the problem was that my company has an Enterprise and a standard Apple Developer account. The Enterprise profile I'd specified to sign with was being created in the standard account because of incorrect Fastlane configs on my part. We have a six-unit build cluster, and a cron job that syncs profiles across them--the way it's set up, sometimes the correct profile was present at build time, but sometimes the incorrect one was. An obscure error, but ultimately nothing to do with Fastlane. I was totally stumped at the time. Automation is powerful tool. Thank you for the prompt responses, though!

**Comment by TKBurner** [comment]
@LizCira Thanks for following up. I'm glad to hear you got up and running. Really glad to have you using Fastlane 👍
