### ISSUE TITLE
[Documentation] create_pull_request return value description is wrong

### ISSUE THREAD

**Issue by Robuske** [fastlane/fastlane#14055]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The create_pull_request return value is described as `The parsed JSON when successful` when it actually return the URL of the new pull request.
It's obviously a one line fix, I even thought about creating a PR, but seems easier for someone else to fix with another thing than to go through all the process of creating a PR just for this.

##### Command executed
```
fastlane action create_pull_request
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[✔] 🚀 
Loading documentation for create_pull_request:

+-----------------------------------------------+
|              create_pull_request              |
+-----------------------------------------------+
| This will create a new pull request on GitHub |
|                                               |
| Created by seei, tommeier                     |
+-----------------------------------------------+

+-----------+--------------------+--------------------+--------------------+
|                       create_pull_request Options                        |
+-----------+--------------------+--------------------+--------------------+
| Key       | Description        | Env Var            | Default            |
+-----------+--------------------+--------------------+--------------------+
| api_token | Personal API       | GITHUB_PULL_REQUE  | *                  |
|           | Token for GitHub   | ST_API_TOKEN       |                    |
|           | - generate one at  |                    |                    |
|           | https://github.co  |                    |                    |
|           | m/settings/tokens  |                    |                    |
| repo      | The name of the    | GITHUB_PULL_REQUE  |                    |
|           | repository you     | ST_REPO            |                    |
|           | want to submit     |                    |                    |
|           | the pull request   |                    |                    |
|           | to                 |                    |                    |
| title     | The title of the   | GITHUB_PULL_REQUE  |                    |
|           | pull request       | ST_TITLE           |                    |
| body      | The contents of    | GITHUB_PULL_REQUE  |                    |
|           | the pull request   | ST_BODY            |                    |
| labels    | The labels for     | GITHUB_PULL_REQUE  |                    |
|           | the pull request   | ST_LABELS          |                    |
| head      | The name of the    | GITHUB_PULL_REQUE  | topic/fastlane-im  |
|           | branch where your  | ST_HEAD            | provements *       |
|           | changes are        |                    |                    |
|           | implemented        |                    |                    |
|           | (defaults to the   |                    |                    |
|           | current branch     |                    |                    |
|           | name)              |                    |                    |
| base      | The name of the    | GITHUB_PULL_REQUE  | master             |
|           | branch you want    | ST_BASE            |                    |
|           | your changes       |                    |                    |
|           | pulled into        |                    |                    |
|           | (defaults to       |                    |                    |
|           | `master`)          |                    |                    |
| api_url   | The URL of GitHub  | GITHUB_PULL_REQUE  | https://api.githu  |
|           | API - used when    | ST_API_URL         | b.com              |
|           | the Enterprise     |                    |                    |
|           | (default to        |                    |                    |
|           | `https://api.gith  |                    |                    |
|           | ub.com`)           |                    |                    |
+-----------+--------------------+--------------------+--------------------+
* = default value is dependent on the user's system

+----------------------------------+
| create_pull_request Return Value |
+----------------------------------+
| The parsed JSON when successful  |
+----------------------------------+

More information can be found on https://docs.fastlane.tools/actions/create_pull_request
</pre>
</details>

### Environment

Does not seem relevant in this case

**Comment by janpio** [comment]
Please do go ahead and create a PR for this - we would not want to mix that in with other changes anyway.

**Comment by Robuske** [comment]
Ok, do I need to download the repo, run all the tests and everything else? Or can I just do everything through GitHub since it's a line change?

Also, my intention is to change it to
"The pull request URL when successful"

**Comment by janpio** [comment]
Github UI is fine of course! CI will run the tests :)

**Comment by Robuske** [comment]
Solved by #14068

**Comment by KrauseFx** [comment]
🎉
