### ISSUE TITLE
How do i force fastlane to run in interactive mode?

### ISSUE THREAD

**Issue by GammaCodeX** [fastlane/fastlane#14057]
### Question Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question
I have for legacy reasons a need to export the variable TEAMCITY_VERSION to a machine that I run fastlane on in INTERACTIVE mode, but when the variable is set fastlane thinks its on a CI machine and runs in NON-INTERACTIVE mode. How do I force it to run in interactive despite the presence of this env variable?

**Comment by janpio** [comment]
Hm, that won't be easy. This code is the reason:
https://github.com/fastlane/fastlane/blob/c6513d100e21a6751f647874aea217541305387f/fastlane_core/lib/fastlane_core/helper.rb#L73-L79
If one of these ENV vars are available, fastlane assumes it is running in a CI environment.

This is then (among other things) used to decide if interactive mode should be used or not:
https://github.com/fastlane/fastlane/blob/c6513d100e21a6751f647874aea217541305387f/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L120-L125

What exactly and how do you use `TEAMCITY_VERSION`? Maybe there is a way to work around this from that angle...

**Comment by GammaCodeX** [comment]
Thanks for your quick reply.
The reason is we have a swiftlint step as a build action in xcode on over 500 branches, and the only way to bypass this step is that it happens to check for if its in our CI (teamcity) env using the same check.

I'm making a machine for us to create test/debug builds from any branch (A lane prompts the user for a branch name, does an infix search on all open branches checks it out and builds to the first connected ipad) but since the different branches require different lint versions there is an issue in our build failing in the lint step. My thought was that because we don't care about lint in this context it would be nice to skip this check... But making the script believe we are in CI skips all the prompts so the user can't chose a branch

Couldn't you make a commandline flag for fastlane so you could invoke it something like
`bundle exec fastlane --interactive` ? or do we not have support for commandline parameters?

I might take the time to look at the code in my spare time, but if we don't even parse for commandline param this is probably quite invasive. And I do have a workaround in my specific usecase; after checkouting a branch i simply remove the line in swiftlint identifying what linter version to use.

**Comment by janpio** [comment]
What would other possible use cases for these options be?

**Comment by GammaCodeX** [comment]
Honestly I think the --non-interactive version might be more useful than --interactive, an example could be if i want to run fastlane on a CI system that doesnt have any of the env variables fastlane knows. In that case I would still be able to just run it non-interactive. (there is a workaround in making a .env file for this though)

I think its also possible to imagine wanting to run a script in non-interactive to see how well it works that way. (again its easier to force it into non-interactive so there is a workaround)

My use case is that I have a machine that may LOOK like a CI server but isn't, although the reason is that we exactly have another program that "guesses" run mode in the exact same way. 

I guess the main point though is for completeness sake? We have a program that can run in two distinct modes interactive and non-interactive, but currently no way to specify which way we want the program to run. So we rely on the program guessing it from system context. It does a great job in doing so and I agree my usecase is fringe, but having the option to tell the program what mode you want just seems like a missing feature. But a very low priority one, which is why I'm saying I might make a PR to lessen the work burden involved for you :)

**Comment by GammaCodeX** [comment]
So given this and the fact that I managed to find a workaround do you think this will be a useful addition if I write (and create a spec for) this or should I just close this question?

**Comment by janpio** [comment]
I personally don't see much use in this. I feel this would be some additional code that has to be maintained and documented, that doesn't add much (or any) benefit. (The completionist in me of course says that it can't hurt to have it - but I try to not follow that urge most of the time. I think this is one of them.)

**Comment by GammaCodeX** [comment]
Thats completely fair. I consider my question answered and i will close this. Thanks for your time!
