### ISSUE TITLE
Staged rollout percentage control

### ISSUE THREAD

**Issue by Salierik** [fastlane/fastlane#14059]
### Feature Request
[Previous issue](https://github.com/fastlane/fastlane/issues/13311) had no answers (From 6 Sep 2018!) and has been closed 13 Jan 2019.

#### Motivation Behind Feature
The main problem of automatic android apps submission is halting previous rollout. So controlling of the Tracks would be very awesome!

Too many developers use Fastlane for release process automatisation and this is the awesome feature who will remove custom scripts with Google's SDK etc.

#### Feature Description
The main feature: Increase staged rollout percentage for selected Track (Production, Beta).
Something like that for Finish the rollout: 
`fastlane supply --track rollout --percentage 1 update-track`

#### Alternatives or Workarounds

Now it is possible only with manual actions in Google Play console or custom scripts who do it via [Publishing API](https://developers.google.com/android-publisher/).

**Comment by henningBunk** [comment]
I don't really understand the question / requested feature. You can switch to rollout and up the percent already:

Beta to 10% Rollout: `-a beta --track_promote_to rollout --rollout 0.1`  
Up Rollout to 50%: `-a rollout --track_promote_to rollout --rollout 0.5`
