### ISSUE TITLE
[snapshot/deliver] iPhone XR screenshots size mismatch

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14067]
While investigating #13610/#13698 I encountered a problem regarding the iPhone XR screenshots:

- The actual resolution of the device is 828x1792: 
![image](https://user-images.githubusercontent.com/183673/51181403-609f6f80-18cb-11e9-8689-4ea55ae2e51b.png)
   https://www.apple.com/iphone-xr/specs/
- But App Store Connect screenshot specifications list the iPhone XR screenshots as "1242 x 2688 pixels (portrait) / 2688 x 1242 pixels (landscape)": 
![image](https://user-images.githubusercontent.com/183673/51181465-84fb4c00-18cb-11e9-9cf6-48ed5f8d14a2.png)
   https://help.apple.com/app-store-connect/#/devd274dd925

So `snapshot` takes a XR screenshot as 828x1792, but App Store Connect expects a XR screenshot as 1242x2688 from `deliver` - which is causing problems for fastlane users.

---

Why does Apple expect a different resolution than the actual device has? The problem is that they don't _really_ support the iPhone XR in App Store Connect at all: The actual Device is 6.1 inches, but in the screenshot specification it is grouped with the 6.5 inch iPhone XS Max. 

(Reasoning behind this is that because of the different ppi the both devices use to display their screenshots, the _actual_, real world size is pretty similar.)

---

So, what should we do about this?

The XR is a real device, so being able to take screenshots with `snapshot` in its device resolution makes sense. 
But we can't let users upload those screenshots to App Store Connect via `deliver`, because it will fail.

**Comment by dcristolovean** [comment]
That means something else. They expect the same image for XS Max and XR, because they have the exact aspect ratio.  And usually they expect the big one, XSMax

This is the same as when they expect the 5.5'' image (1242x2208) also for 4'' and for 4.7''.  Doesn't mean that iPhone8 has 1242x2208.

The problem here is that people generate XR screenshots, but those are not needed in AppStore, you should upload XSMax screenshots for both phones.

Move your tests to XSMax, not XR.  fastlane will generate 1241x2688 instead of 1242x2688 (if I remember correctly now)

**Comment by dcristolovean** [comment]
To sum up, you basically need 2 screenshots in the appstore:  the 5.5'' (16:9) and the 6.5'' (19:9?) ones.  All the rest are automatically done by Apple, by sizing down.

**Comment by janpio** [comment]
No, it means exactly what I wrote above @dcristolovean. What you are writing here is noe wrong, and also directly related, but it doesn't mean that what I wrote above was wrong.

The list what screenshots of what size can or have to be uploaded can be found here: https://help.apple.com/app-store-connect/#/devd274dd925

But fastlane can/should do something about the unexpected reality that `deliver` tells them the iPhone XR screenshots should be a different size than they actually are.

**Comment by dcristolovean** [comment]
Well, yes, you can upload screenshots for all res, no one is stopping you. But the minimum requirement, which should be enough, is what I said, unless you have really different screens on each size.
I think the XR delivery problem is real, but it's also the least important here, since the main issue is that even the XR screenshots are not 100% correct, even if Apple would accept that size.  They still miss 1-2px on a side, just like the XS Max ones.

Here, we manually added a script that resizes them to the correct size after fastlane finishes, but it's just a workaround to hide a problem.

**Comment by janpio** [comment]
In this issue _only_ the iPhone XR problem is important. This is about making sure that fastlane supports all use cases, not just yours. Please go to #13610 to talk about other devices.

> the XR screenshots are not 100% correct, even if Apple would accept that size. They still miss 1-2px on a side

That is new information and hasn't been reported yet. Can you elaborate?

Until now we had 3 people (@sebleclerc, @wdcurry, @endresjd) report the exactly correct screen size for iPhone XR of `[828, 1792]`:
https://github.com/fastlane/fastlane/issues/13610#issuecomment-448001072 + https://github.com/fastlane/fastlane/issues/13610#issuecomment-453763163 + https://github.com/fastlane/fastlane/issues/13610#issuecomment-450016186
And 1 person (@armcknight) reporting a very different height of `[828, 1472]`:
https://github.com/fastlane/fastlane/issues/13610#issuecomment-434132609
(which sounds like a separate problem to be honest - or maybe a typo @armcknight?)

**Comment by sebleclerc** [comment]
Alright, this is the output of my `fastlane env`:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.14.2                                        |
| Ruby                        | 2.4.1                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.17.2 (Apple Git-113)             |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane            |
| Host                        | Mac OS X 10.14.2 (18C54)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                   |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode 10.app/Contents/Developer/ |
| Xcode Version               | 10.1                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

platform :ios do
  xcWorkspace = ''
  exportPath = ''

  desc "Set build number to some value"
  lane :set_build_number do |options|
    increment_build_number(
      xcodeproj: ''
    )
  end

  desc "Create snapshots and upload to iTunes Connect"
  lane :screenshots do
    snapshot
  end

  desc "Deploy a new version to the App Store"
  lane :prod do |options|
    set_build_number

    clear_derived_data

    gym(
      scheme: '42Bieres',
      workspace: xcWorkspace,
      output_directory: exportPath,
      output_name: '',
      export_method: 'app-store',
      xcargs: '-allowProvisioningUpdates'
    )

    screenshots

    deliver(
      submit_for_review: false,
      ipa: '',
      app_version: options[:appVersion],
      metadata_path: ''
      force: false,
      overwrite_screenshots: true
    )
  end
end

platform :android do
  projectDir = ''

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # Upload to Google Play Store
    supply(
      track: 'alpha',
      metadata_path: '' 
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address
team_id ""  # Developer Portal Team ID

# Android
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.113.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bundler                   | 1.16.1       |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-01-15**
</details>

**Comment by sebleclerc** [comment]
I thought it would be helpful to have fastlane env here 😃 You can remove my comment on both issues

**Comment by janpio** [comment]
Oh right, you actually only reported problems with iPhone XR, so your information is at the right place here:

> Alright, this is the output of my `fastlane env`:
> 
> <details><summary>✅ fastlane environment ✅</summary>
> 
> ### Stack
> 
> | Key                         | Value                                          |
> | --------------------------- | ---------------------------------------------- |
> | OS                          | 10.14.2                                        |
> | Ruby                        | 2.4.1                                          |
> | Bundler?                    | true                                           |
> | Git                         | git version 2.17.2 (Apple Git-113)             |
> | Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane            |
> | Host                        | Mac OS X 10.14.2 (18C54)                       |
> | Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                   |
> | OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                    |
> | Is contained                | false                                          |
> | Is homebrew                 | false                                          |
> | Is installed via Fabric.app | false                                          |
> | Xcode Path                  | /Applications/Xcode 10.app/Contents/Developer/ |
> | Xcode Version               | 10.1                                           |
> 
> 
> ### System Locale
> 
> | Variable | Value       |   |
> | -------- | ----------- | - |
> | LANG     | fr_CA.UTF-8 | ✅ |
> | LC_ALL   |             |   |
> | LANGUAGE |             |   |
> 
> 
> ### fastlane files:
> 
> <details><summary>`./fastlane/Fastfile`</summary>
> 
> ```ruby
> 
> platform :ios do
>   xcWorkspace = ''
>   exportPath = ''
> 
>   desc "Set build number to some value"
>   lane :set_build_number do |options|
>     increment_build_number(
>       xcodeproj: ''
>     )
>   end
> 
>   desc "Create snapshots and upload to iTunes Connect"
>   lane :screenshots do
>     snapshot
>   end
> 
>   desc "Deploy a new version to the App Store"
>   lane :prod do |options|
>     set_build_number
> 
>     clear_derived_data
> 
>     gym(
>       scheme: '42Bieres',
>       workspace: xcWorkspace,
>       output_directory: exportPath,
>       output_name: '',
>       export_method: 'app-store',
>       xcargs: '-allowProvisioningUpdates'
>     )
> 
>     screenshots
> 
>     deliver(
>       submit_for_review: false,
>       ipa: '',
>       app_version: options[:appVersion],
>       metadata_path: ''
>       force: false,
>       overwrite_screenshots: true
>     )
>   end
> end
> 
> platform :android do
>   projectDir = ''
> 
>   desc "Deploy a new version to the Google Play"
>   lane :deploy do
>     # Upload to Google Play Store
>     supply(
>       track: 'alpha',
>       metadata_path: '' 
>     )
>   end
> end
> 
> ```
> </details>
> 
> <details><summary>`./fastlane/Appfile`</summary>
> 
> ```ruby
> # iOS
> app_identifier "" # The bundle identifier of your app
> apple_id "" # Your Apple email address
> team_id ""  # Developer Portal Team ID
> 
> # Android
> json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
> package_name("") # e.g. com.krausefx.app
> 
> ```
> </details>
> 
> ### fastlane gems
> 
> | Gem      | Version | Update-Status |
> | -------- | ------- | ------------- |
> | fastlane | 2.113.0 | ✅ Up-To-Date  |
> 
> 
> ### Loaded fastlane plugins:
> 
> **No plugins Loaded**
> 
> 
> <details><summary><b>Loaded gems</b></summary>
> 
> | Gem                       | Version      |
> | ------------------------- | ------------ |
> | did_you_mean              | 1.1.0        |
> | io-console                | 0.4.6        |
> | CFPropertyList            | 3.0.0        |
> | concurrent-ruby           | 1.0.5        |
> | i18n                      | 0.9.1        |
> | minitest                  | 5.10.1       |
> | thread_safe               | 0.3.6        |
> | tzinfo                    | 1.2.4        |
> | activesupport             | 4.2.10       |
> | public_suffix             | 2.0.5        |
> | addressable               | 2.5.2        |
> | atomos                    | 0.1.3        |
> | babosa                    | 1.0.2        |
> | bundler                   | 1.16.1       |
> | claide                    | 1.0.2        |
> | fuzzy_match               | 2.0.4        |
> | nap                       | 1.1.0        |
> | cocoapods-core            | 1.5.3        |
> | cocoapods-deintegrate     | 1.0.2        |
> | cocoapods-downloader      | 1.2.1        |
> | cocoapods-plugins         | 1.0.0        |
> | cocoapods-search          | 1.0.0        |
> | cocoapods-stats           | 1.0.0        |
> | netrc                     | 0.11.0       |
> | cocoapods-trunk           | 1.3.0        |
> | cocoapods-try             | 1.1.0        |
> | colored2                  | 3.1.2        |
> | escape                    | 0.0.4        |
> | fourflusher               | 2.0.1        |
> | gh_inspector              | 1.1.3        |
> | molinillo                 | 0.6.5        |
> | ruby-macho                | 1.1.0        |
> | nanaimo                   | 0.2.6        |
> | xcodeproj                 | 1.7.0        |
> | cocoapods                 | 1.5.3        |
> | colored                   | 1.2          |
> | highline                  | 1.7.10       |
> | commander-fastlane        | 4.4.6        |
> | declarative               | 0.0.10       |
> | declarative-option        | 0.1.0        |
> | digest-crc                | 0.4.1        |
> | unf_ext                   | 0.0.7.5      |
> | unf                       | 0.1.4        |
> | domain_name               | 0.5.20180417 |
> | dotenv                    | 2.6.0        |
> | emoji_regex               | 0.1.1        |
> | excon                     | 0.62.0       |
> | multipart-post            | 2.0.0        |
> | faraday                   | 0.15.4       |
> | http-cookie               | 1.0.3        |
> | faraday-cookie_jar        | 0.0.6        |
> | faraday_middleware        | 0.12.2       |
> | fastimage                 | 2.1.5        |
> | jwt                       | 2.1.0        |
> | memoist                   | 0.16.0       |
> | multi_json                | 1.13.1       |
> | os                        | 1.0.0        |
> | signet                    | 0.11.0       |
> | googleauth                | 0.6.7        |
> | httpclient                | 2.8.3        |
> | mime-types-data           | 3.2018.0812  |
> | mime-types                | 3.2.2        |
> | uber                      | 0.1.0        |
> | representable             | 3.0.4        |
> | retriable                 | 3.1.2        |
> | google-api-client         | 0.23.9       |
> | google-cloud-env          | 1.0.5        |
> | google-cloud-core         | 1.2.7        |
> | google-cloud-storage      | 1.15.0       |
> | json                      | 2.1.0        |
> | mini_magick               | 4.5.1        |
> | multi_xml                 | 0.6.0        |
> | plist                     | 3.5.0        |
> | rubyzip                   | 1.2.2        |
> | security                  | 0.1.3        |
> | naturally                 | 2.2.0        |
> | simctl                    | 1.6.5        |
> | slack-notifier            | 2.3.2        |
> | terminal-notifier         | 1.8.0        |
> | unicode-display_width     | 1.4.1        |
> | terminal-table            | 1.8.0        |
> | tty-screen                | 0.6.5        |
> | tty-cursor                | 0.6.0        |
> | tty-spinner               | 0.9.0        |
> | word_wrap                 | 1.0.0        |
> | rouge                     | 2.0.7        |
> | xcpretty                  | 0.3.0        |
> | xcpretty-travis-formatter | 1.0.0        |
> </details>
> 
> 
> *generated on:* **2019-01-15**
> </details>

Although that problem really is a more general thing: Fastlane has no concept of the screenshot mapping Apple is doing as far as I know, which is the underlying problem of the iPhone XR problem.

**Comment by sebleclerc** [comment]
I did some testing and found that simulator screenshot size for iPhone XR is 828x1792 and iPhone XS Max is 1242x1688. The resolution for iPhone XR is what snapshot create.

Based on the link @janpio provided, it is clearly stated that for iPhone XS Max and iPhone XR, we need to provide a screenshot of `1242 x 2688 pixels (portrait), 2688 x 1242 pixels (landscape)` which is the size of the iPhone XS Max because both have the same ratio.  There is nothing about a iPhone XR size screenshot. This is why if we try to send iPhone XR screenshot to iTunes connect, we get an error. We shouldn't.

**Comment by sebleclerc** [comment]
I'll try with iPhone XS Max screenshots during lunch and post here if it's working

**Comment by janpio** [comment]
... which is exactly what I wrote in this issue. `snapshot` creates the correct screenshots, but `deliver` (App Store Connect) doesn't actually want them. We need a way to protect users that create XR screenshots from `deliver` picking them up to upload.

**Comment by janpio** [comment]
#13774 might already solve this problem.

**Comment by sebleclerc** [comment]
Indeed, it's seems to be fixed

**Comment by sebleclerc** [comment]
👍

**Comment by janpio** [comment]
Great, so we can close this @sebleclerc?

**Comment by sebleclerc** [comment]
Yes! Thanks @janpio !

**Comment by janpio** [comment]
🚀
