### ISSUE TITLE
[frameit] Document option `force_orientation_block`

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14076]
#11161 added a `force_orientation_block` parameter to enable better customization of the screenshot orientation (and to fix #10928). Unfortunately this is pretty much undocumented right now.

Some default behaviour of frameit is defined via the default value of that parameter:
https://github.com/fastlane/fastlane/blob/c4def9f78622851b7c51bdfbc55080659b38b8fe/frameit/lib/frameit/options.rb#L60-L67

The PR has 2 examples of blocks that can be used:
https://github.com/fastlane/fastlane/pull/11161#issuecomment-353684428
https://github.com/fastlane/fastlane/pull/11161#issuecomment-353728307

The file to be edited: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/frame_screenshots.md

A good headline could maybe be "Screenshot orientation" or similar, then an explanation of the default behavior and an introduction of the param, how it works and a few simple examples.

**Comment by mollyIV** [comment]
Hey @janpio 👋 

I had a chance to play with `force_orientation_block` today - it works very well 💪 
The one very minor thing I found was a duplicated log on console `[⠋] Framing screenshot ...`:

```bash
[20:22:03]: ------------------------------
[20:22:03]: --- Step: default_platform ---
[20:22:03]: ------------------------------
[20:22:03]: Driving the lane 'ios frameit_force_orientation_block' 🚀
[20:22:03]: -------------------------------
[20:22:03]: --- Step: frame_screenshots ---
[20:22:03]: -------------------------------
[20:22:03]: Framing screenshots at path /path/screenshots (via frameit)
[20:22:03]: Using device frames version 'latest'
[✔] Framing screenshot './screenshot_6_plus.png'
[20:22:08]: Added frame: '/path/screenshots/screenshot_6_plus_framed.png'
[⠋] Framing screenshot './screenshot_xs_landscape.png' Forced orientation: landscape_left
Forced orientation: landscape_left
[⠴] Framing screenshot './screenshot_xs_landscape.png' Forced orientation: landscape_left
Forced orientation: landscape_left
[✔] Framing screenshot './screenshot_xs_landscape.png'
[20:22:11]: Added frame: '/path/screenshots/screenshot_xs_landscape_framed.png'
```
I'd like to tackle this ticket, although I have two follow-up questions:
1. Do you think we should introduce a headline "Screenshot orientation" in an "Advanced Usage (optional)" section, after "Example" subsection? If not, could you suggest a proper place? 🙏 
2. Would you like to focus on overall default screenshot behaviour, not only for the landscape orientation, right? After that we could make a smooth transition to the `force_orientation_block` parameter, just like you suggested 🙂 
> then an explanation of the default behavior

Thanks!

**Comment by janpio** [comment]
> I had a chance to play with force_orientation_block today - it works very well 💪

Phew, no blocking bug this time 💃 

> The one very minor thing I found was a duplicated log on console [⠋] Framing screenshot ...:

That is a general problem with the spinner: If you output things while it is spinning (`Forced orientation: landscape_left` twice in this case), it will have to restart in a new line and continue spinning there. No real solution for that yet - this output probably just shouldn't be there unless you request it with `--verbose` which then should not show a spinner, but a normal output.

> Do you think we should introduce a headline "Screenshot orientation" in an "Advanced Usage (optional)" section, after "Example" subsection? If not, could you suggest a proper place? 🙏

Nah, that sounds fine to me.

> Would you like to focus on overall default screenshot behaviour, not only for the landscape orientation, right? After that we could make a smooth transition to the force_orientation_block parameter, just like you suggested 

Yep, something like that. Whatever makes sense in the flow of the text. But mentioning the default without any params first, then explain the options to change that sounds useful.
