### ISSUE TITLE
Multiple Google Play Accounts?

### ISSUE THREAD

**Issue by hakansuluoglu** [fastlane/fastlane#14074]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Fastlane supply - Google play release deployment

#### Question Description
I have a project that creates more than one application with different applicationID via using flavors. **Google Play accounts are all different**(Company specific application). I read documentation. I didn't find multiple google play account support for release deployment.

I understand multiple metada file for each flavor. However there is no information about multiple Google Play account. So, I have to put more than one **json_key_file** into project. Do you have any idea?

**Comment by hakansuluoglu** [comment]
I have a project that creates more than one application with different applicationID via using flavors. **Google Play accounts are all different**(Company specific application).  I read documentation. I didn't find multiple google play account support for release deployment.

I understand multiple metada file for each flavor. However there is no information about multiple Google Play account. So, I have to put more than one **json_key_file** into project.  Do you have any idea?

**Comment by joshdholtz** [comment]
@hakansuluoglu Heyyy 👋 Multiple Google Play accounts are definitely supported 😊 `supply` has the `json_key` option which you can pass a path to your json key file. In my example below I'm passing a different path into `supply` which is how you would go about supporting multiple accounts. 

```rb
# Google Play account "Hello"
supply(
  json_key: "./google_play_hello_account.json"
)
```

```rb
# Google Play account "World"
supply(
  json_key: "./google_play_world_account.json"
)
```

If you do not want to have them get passed by a path, there is also an option for `json_key_data` if you would rather pass by actual contents.

Happy fastlaning 😊🚀
