### ISSUE TITLE
[frameit] Can't properly frame iPad Pro 11, 10.5 and 9.7

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14079]
`frameit` currently can't properly frame iPad Pro 11, 10.5 and 9.7:

```
...
[⠋] Framing screenshot './iPad Pro (10.5-inch)-01StartScreen.png' ERROR [2019-01-17 16:31:41.48]: Unknown device type for size iOS-iPad-10.5 for path './iPad Pro (10.5-inch)-01StartScreen.png'
ERROR [2019-01-17 16:31:41.55]: Unknown device type for size iOS-iPad-10.5 for path './iPad Pro (10.5-inch)-01StartScreen.png'
ERROR [2019-01-17 16:31:41.55]: Unknown device type for size iOS-iPad-10.5 for path './iPad Pro (10.5-inch)-01StartScreen.png'
DEBUG [2019-01-17 16:31:41.55]: Looking for Apple true Space Gray and found 0 template(s)
ERROR [2019-01-17 16:31:41.55]: Couldn't find template for screenshot type 'Apple true Space Gray'
ERROR [2019-01-17 16:31:41.55]: Please run `fastlane frameit download_frames` to download the latest frames
ERROR [2019-01-17 16:31:41.56]: Unknown device type for size iOS-iPad-10.5 for path './iPad Pro (10.5-inch)-01StartScreen.png'
[✖] Framing screenshot './iPad Pro (10.5-inch)-01StartScreen.png'
[⠋] Framing screenshot './iPad Pro (11-inch)-01StartScreen.png' ERROR [2019-01-17 16:31:41.56]: Unknown device type for size iOS-iPad-11 for path './iPad Pro (11-inch)-01StartScreen.png'
ERROR [2019-01-17 16:31:41.63]: Unknown device type for size iOS-iPad-11 for path './iPad Pro (11-inch)-01StartScreen.png'
ERROR [2019-01-17 16:31:41.63]: Unknown device type for size iOS-iPad-11 for path './iPad Pro (11-inch)-01StartScreen.png'
DEBUG [2019-01-17 16:31:41.63]: Looking for Apple true Space Gray and found 0 template(s)
ERROR [2019-01-17 16:31:41.63]: Couldn't find template for screenshot type 'Apple true Space Gray'
ERROR [2019-01-17 16:31:41.63]: Please run `fastlane frameit download_frames` to download the latest frames
ERROR [2019-01-17 16:31:41.63]: Unknown device type for size iOS-iPad-11 for path './iPad Pro (11-inch)-01StartScreen.png'
[✖] Framing screenshot './iPad Pro (11-inch)-01StartScreen.png'
...
```

Reason for this is that the Facebook Frames, and thus our frames repository, do not include those frames.

This leads to the error message pasted above for iPad Pro 11 and iPad Pro 10.5. For iPad Pro 9.7 it (ab)uses the iPad Air 2 frames, as the screenshots of those devices have the same size.

**Comment by ZevEisenberg** [comment]
+1 would like to be able to use frameit with latest devices. Would it be possible to use frameit with the Apple-provided PSD files from here? https://developer.apple.com/app-store/marketing/guidelines/#appstore

**Comment by janpio** [comment]
The problem is more complicated than just missing frame images unfortunately.

**Comment by ZevEisenberg** [comment]
Would you mind elaborating? Is it about ambiguous file names? Or programmatically editing Apple's PSD files without access to Photoshop? Something else?

**Comment by janpio** [comment]
Frameit is a really complicated piece of code that interacts with deliver to get informaion about which devices are available, Its own logic to identify devices and match it witch frame graphics is pretty brittle, see the `Couldn't find template for screenshot type 'Apple true Space Gray'` output above.

If you want to jump in here, a first step would be do get the Apple device frames and add the to the local frame cache at `~/.fastlane/frameit/latest`. Give the file the correct name (has to be .png). There is a file `offsets.json` that needs an entry about the file with the "offset" of the transparent area where the screenshot should be placed, and a width of the transparent area. Lets us know what happens then when you tried to frame one of the devices mentioned in the title - maybe this really works.

**Comment by ZevEisenberg** [comment]
Thanks! Not sure if I have time to work on this right now, but hopefully either I will soon or someone else will pick it up. I anticipate problems with the 12.9” iPad Pro 2nd vs 3rd generation, since they have the same pixel dimensions but different semantics regarding the home indicator and corner rounding.

If it works with Apple’s images, would we need to include a download step for those? Or is that premature to even be thinking about? It may be tricky since their images are layered PSDs with multiple devices per file.

**Comment by janpio** [comment]
First we would have to check the licence and make sure we _can_ actually incorporate and modify those files. If yes, we could first add them manually to the repository that contains the frame. (Note: We should double check if Facebook, where the current frames come from, didn't add those in the meantime!) Then if we keep working with those files, it would sure be neat to have the export from PSD to PNG and everything automated, indeed.

**Comment by Bersaelor** [comment]
We're currently waiting for the 11-inch screens too, I just checked https://facebook.design/devices#filters and they still haven't added any frames for the new ipads without a home button.
