### ISSUE TITLE
[action] slack: Using Member ID as the recipient of a slack message is not supported

### ISSUE THREAD

**Issue by johngun3** [fastlane/fastlane#14071]
When using the slack integration in fastlane one cannot use a member id to send a message directly to a user as the fastlane implementation [prepends "#" to the channel name](https://github.com/fastlane/fastlane/blob/551a82fe22bfbadb8e044d95c09b5d47d78f522c/fastlane/lib/fastlane/actions/slack.rb#L29) unless the given channel name already starts with "#" or "@". If multiple users in an organization have configured their display name (@name) to be the same then it is not possible to send someone a direct message via fastlane without a custom workaround.

**Comment by joshdholtz** [comment]
Huh, I actually did not know that they changed this around but here is a blog post mentioned this - https://api.slack.com/changelog/2017-09-the-one-about-usernames

**Comment by johngun3** [comment]
One possible solution is to split out the channel input field and allow for multiple keys that would specify different types of recipients. Notifying a whole channel is still a use case so the channel key should stay but messaging a specific person by member ID or by display name if you want to (but see below quote from article) is also a use case and you should be able to specify that. In summary, having to specify at least one of channel id, member id, or display name (for backwards compatibility) would allow things to be more flexible

You could also change the functionality of the channel key input to assume that it is going to be a channel or member ID and create a new key input called `legacy_channel` that uses the current implementation of the channel key.

From the article: 

`Don't provide an username in the channel field when trying to direct a message to a specific user. Use im.open to create a direct message and then specify the direct message "channel" ID instead.`

`Consider a future where mentioning channels required using only its ID and channel names were not necessarily unique or following the same structure as #channel names today. That future will one day arrive. Get ahead of the curve and use channel IDs for all indexing and storage organization.` This is already the case with display names (@names).

**Comment by janpio** [comment]
This sounds like a useful feature, that could be implemented with a little effort understanding how Slack's API works and thinking of a good parameter implementation - so I am reopening this.

**Comment by crazymanish** [comment]
Hi @johngun3  
You can send a direct message now:) Please let me know if you need any help! 😍
https://github.com/crazymanish/fastlane-plugin-slack_bot

Thanks, @joshdholtz for unlocking the issue! 🙏🏻
