### ISSUE TITLE
Rate limit has been exceeded for: itunes-connect|nonauth_url_spamControl|<my_ip_address>

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#14070]
I am also getting this error - `Message: Rate limit has been exceeded for: itunes-connect|nonauth_url_spamControl|<my_ip_address>`

I am trying to get a list of all users and their permissions using Spaceship
```ruby
all_users = Spaceship::Tunes::Members.all
user = all_users[0] # for example
account_permissions = {}
account_permissions[:name] = teamname
account_permissions[:islive] = !user.not_accepted_invitation
account_permissions[:permissions] = user.roles
account_permissions[:apps] = user.has_all_apps ? ["all"] : user.selected_apps.map { |a| a.name if !a.nil? }
account_permissions[:lastupdated] = Time.now.strftime("%Y-%m-%d")
```

My code gets the details for first 15 or so users, and fails after with the above error message. Was able to find this information - https://stackoverflow.com/a/41377650/1946418; but not sure how true that is. The number seems too low?

Let me know if you need more information, please!

This is my Fastlane's version - `fastlane 2.113.0`

**Comment by janpio** [comment]
Can you check the spaceship logfiles in `/tmp/spaceship-*.log` and post them here? This should show what requests are being generated and which one is giving you the exact error you are seeing.

Do the requests being generated by spaceship match the requests sent by the web UI when doing the same task manually?

**Comment by scorpion35** [comment]
This is the last line - 
`DEBUG [14:14:21]: << GET ra/apps/manageyourapps/summary/v2: 429 Rate limit has been exceeded for: itunes-connect|nonauth_url_spamControl|<my_ip_address>`

Is this what you are looking for?

(Sorry, I cannot post the full file as it seems to contain sensitive information!)

**Comment by janpio** [comment]
Can you filter it down to show all the requests (`...: >> ...`)? I am trying to understand what kind of request profile your code produces.

**Comment by scorpion35** [comment]
@janpio Sorry for the delay! Please find the attached file.

[spaceship_requests_spamcontrol.log](https://github.com/fastlane/fastlane/files/2768732/spaceship_requests_spamcontrol.log)

This line is fetching apps each user has access to. Could it be this line is causing the issue? 
`account_permissions[:apps] = user.has_all_apps ? ["all"] : user.selected_apps.map { |a| a.name if !a.nil? }`

**Comment by scorpion35** [comment]
Confirmed. If I remove the above line, I am not running into this error anymore. 

Do you have any suggestions to make this work, please? I need to fetch each user's apps. 

@janpio @taquitos @KrauseFx @joshdholtz Any help is appreciated!

**Comment by janpio** [comment]
I looked into the code (which I didn't know at all before):

`user.selected_apps` effectively seems to create a call for each app (and requesting all apps each time):

https://github.com/fastlane/fastlane/blob/c4def9f78622851b7c51bdfbc55080659b38b8fe/spaceship/lib/spaceship/tunes/member.rb#L57-L63

https://github.com/fastlane/fastlane/blob/c4def9f78622851b7c51bdfbc55080659b38b8fe/spaceship/lib/spaceship/tunes/application.rb#L70-L77

https://github.com/fastlane/fastlane/blob/c4def9f78622851b7c51bdfbc55080659b38b8fe/spaceship/lib/spaceship/tunes/application.rb#L66-L68

You can probably call `Application.all` once, then do what `selected_apps` does without triggering a request for each app.

(If this works, we would appreciate a pull request to update `selected_apps` to work that way as well)

**Comment by joshdholtz** [comment]
@scorpion35 That `user.has_all_apps` and `user.selected_apps` is the problem. Both of those end up calling https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb#L72-L77 so...

For each user you loop through you are also querying each app. Probably best to find a different approach or put a `sleep` in there between calls if you have spare time to kill 😝

Also, if you could refrain from mass mentioning all the lead maintainers on a non-regression issue in the future or if a question hasn't been helped relied to recently (which this one is pretty active) that would be 💯 🙏

**Comment by scorpion35** [comment]
Copy that :)

**Comment by scorpion35** [comment]
Was able to test your suggestion @janpio and submitted a PR with changes - https://github.com/fastlane/fastlane/pull/14084

Note I am still running into this error. It's very random when this block is applied on Apple's side. I get the error on 150th user one time and on 86th user another time. However, the PR does optimize GET requests sent very nicely. **Only one GET request per user** with the fix!

I did change code in my script as well to - 
```ruby
user_apps = user.selected_apps
fresh_account_permissions[:apps] = user_apps.length == 0 ? ["all"] : user_apps.map { |a| a.name if !a.nil? }
```
Not calling user.has_all_apps anymore, as it triggers another GET request, and making Apple block my script even sooner.

I will implement a smart sleeping solution as suggested by Josh as well.

Please take a look at the PR and let me know if you need anything else from me!

**Comment by scorpion35** [comment]
Ah, I meant the sleep for x mins is on my side, not in Fastlane code. The PR only contains the fix for optimizing GET requests sent.

**Comment by janpio** [comment]
Yep, I got that - but I would like it if fastlane would be able to handle those `429` responses better in general.

**Comment by scorpion35** [comment]
Got it. Usually `429` error code comes with the time limit we can try after, but Apple doesn't seem to include it. I have implemented incremental sleep on my side, not a perfect solution, but is getting the job done!

This is my code for reference,

```ruby
total_tries = 0
max_tries = 5 # Comes from a config file

begin
  get_all_users()
  $logger.info("")
  $logger.info("Script completed.")
rescue Exception => ex
  $logger.error("Message: #{ex.message}")
  $logger.error("Callstack: ")
  ex.backtrace.each do |cs| 
    $logger.error("\t\t#{cs}")
  end

  if ex.message.include?("nonauth_url_spamControl")
    total_tries = total_tries + 1 
    sleep(total_tries * 60) # Incrementally sleep, to give enough gap between each try.
    retry if total_tries <= max_tries # Retry blocked by Apple
  end # if ex.message.include?("nonauth_url_spamControl")

end # begin 
```

If it fails even after `max_tries` has been reached, then 🤷‍♂️

Not sure if it's possible, but can we request Apple to include a time limit in the header when they block the calls? This way we can implement the above sleeping solution in Fastlane itself?

Also, do you have any update on my PR, please? I am currently referencing my script to local fastlane changes, would have to move it to Jenkins build farm soon. Would appreciate if it's merged soon.

**Comment by scorpion35** [comment]
Thanks again janpio and josh for taking a look and merging my PR! 

The PR just optimizes the requests sent to potentially 'avoid' getting blocked by Apple, but doesn't completely fix it. My incremental sleep solution above is working for me, but wondering if you guys have any ideas on fixing this for good. 

> Not sure if it's possible, but can we request Apple to include a time limit in the header when they block the calls? This way we can implement the above sleeping solution in Fastlane itself?

Do you think this would be possible? :)

**Comment by janpio** [comment]
A thought: I used to work on online games, and for the rate limiting / anti DDoS system we had there, the _last_ thing we wanted to do was to tell the "attacker" the optimal time frame after which to try again as the ban gets removed.

I think the next step here would be to look at the generated requests again and see if anything can further be optimized. (Using Charles would probably be more comfortable than looking at the logfiles: https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md#setting-up-charles-web-proxy)

**Comment by scorpion35** [comment]
Makes sense! Didn't think of it from 'attacking' perspective :)

I will look into this over the weekend (have to get used to Charles as well)!

**Comment by scorpion35** [comment]
Working on other high priority projects at the moment. I am still running into this issue, but my smart sleep method gets all the data!

Closing this for now. Will revisit if it becomes an issue again.

Thanks again janpio and josh for your help 🙇
