### ISSUE TITLE
[snapshot] screenshots.html can't differentiate between iPad Pro 12.9 and iPad Pro 12.9 (3rd gen)

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14085]
Running snapshot for all available simulators via `devices(["iPad (5th generation)", "iPad (6th generation)", "iPad Air", "iPad Air 2", "iPad Pro (9.7-inch)", "iPad Pro (10.5-inch)", "iPad Pro (11-inch)", "iPad Pro (12.9-inch)", "iPad Pro (12.9-inch) (2nd generation)", "iPad Pro (12.9-inch) (3rd generation)", "iPhone 5s", "iPhone 6", "iPhone 6 Plus", "iPhone 6s", "iPhone 6s Plus", "iPhone 7", "iPhone 7 Plus", "iPhone 8", "iPhone 8 Plus", "iPhone SE", "iPhone X", "iPhone XR", "iPhone XS", "iPhone XS Max", "Apple TV", "Apple TV 4K", "Apple TV 4K (at 1080p)"])` gives you a row for "iPad Pro (12.9-inch)" in `screenshots.html` with 2 screenshots:

![screen shot 2019-01-17 at 7 36 46 pm](https://user-images.githubusercontent.com/183673/51340458-444c3000-1a8f-11e9-8e1b-c84d2cbad1a5.png)

(My test app outputs the device name in a label on a nice colored background. Normally each device should only have exactly one screenshot here.)

**Comment by ZevEisenberg** [comment]
+1. This also affects uploads to App Store Connect. Two images show up in the slot for ** iPad Pro (2nd Generation) 12.9-inch Display**, and none show up in the slot for ** iPad Pro (3rd Generation) 12.9-inch Display** (assuming you are uploading one screenshot per device, as in the original post).

**Comment by ZevEisenberg** [comment]
I'm still having this problem with latest Fastlane. When I run snapshot, the images for 12.9" and 12.9" (third generation) show up in the same slot in screenshots.html. Snapshot should be able to tell the difference, given that it names the files correctly, like this:

- iPad Pro (12.9-inch) (3rd generation)-0.png
- iPad Pro (12.9-inch)-0.png

So it looks like there's a mismatch between the thing generating the files, and the thing creating the HTML page to display the files.

**Comment by ZevEisenberg** [comment]
Still having this problem.
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/464574/57986031-a452e300-7a3d-11e9-9526-50670ec592d4.png">

**Comment by claesjacobsson** [comment]
I'll try submitting a PR for this soon.

**Comment by mollyIV** [comment]
The PR has been merged: https://github.com/fastlane/fastlane/pull/14847, thanks again @claesjacobsson  🙇 

Closing the issue.
