### ISSUE TITLE
[frameit] Unknown devices get name `true`

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14081]
In https://github.com/fastlane/fastlane/issues/14079#issue-400328753 you can see the output of `frameit` when trying to frame unknown devices:

```
ERROR [2019-01-17 16:31:41.55]: Unknown device type for size iOS-iPad-10.5 for path './iPad Pro (10.5-inch)-01StartScreen.png'
DEBUG [2019-01-17 16:31:41.55]: Looking for Apple true Space Gray and found 0 template(s)
ERROR [2019-01-17 16:31:41.55]: Couldn't find template for screenshot type 'Apple true Space Gray'
```

Unknown names being returned as `true` doesn't seem like a really good idea - we might to want to throw an exception there with a better error message that points out the actual problem (device is unknown) instead of letting this fall through and then just not being able to get a device frame.

**Comment by mollyIV** [comment]
Hey @janpio 👋 

I'd like to help with this one 🙂 so basically what we are doing now is just displaying an error:

https://github.com/fastlane/fastlane/blob/3935c59229f68b28bfbdff95fdd3af42cf46a586/frameit/lib/frameit/screenshot.rb#L53

You mentioned that:
> we might to want to throw an exception there with a better error message

Was wondering if simply interrupting the lane would do? 🤔 

```ruby
    ...
    else
        UI.error!("Unknown device type for size #{@screen_size} for path '#{path}'")
    end
```

Another option might be rising an exception:

```ruby
    ...
    else
        rise "Unknown device type for size #{@screen_size} for path '#{path}'")
    end
```

Although the above ☝️would provide just a log on the console with ruby exception (if not handled in other places), so I'd vote for a solution with `UI.error!` usage (lane failure with a nice red output) 🙇 

If we give a go for this change, it means that whenever there is an unsupported screenshot (unknown device type), the frame creation will be interrupted - is that okay? 🤔

**Comment by janpio** [comment]
The real problem here is that it somehow decides that `true` is the name of the device type.

(Although with my incoming PR this might already be fixed, so let me assign this to me and see where we're at when I pushed that one)
