### ISSUE TITLE
fastlane pilot app store connect login error through Jenkins with FASTLANE_USER FASTLANE_PASSWORD Credential Bindings

### ISSUE THREAD

**Issue by davidwadge** [fastlane/fastlane#14089]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm running `fastlane pilot` through Jenkins on a Ubuntu machine, passing the app store details through `FASTLANE_USER` and `FASTLANE_PASSWORD` env. variables (using Credential Bindings in Jenkins). I'm getting invalid username and password as a response, despite checking and double checking they're correct. 

I've also ssh'd into the box and attempted to authenticate via `fastlane spaceauth` and I get a similar error in response - `The login credentials for 'xxxx@xxx.com' seem to be wrong`. Again, they're not wrong. I can get this working fine on my local machine (a Mac).

##### Command executed

`        fastlane pilot upload 
            --username ${FASTLANE_USER} 
            --verbose 
            --ipa ${IPA_BUILD}
`

##### Complete output when running fastlane, including the stack trace and command used
<pre>
INFO [2019-01-17 21:49:34.67]: Login to App Store Connect (****)
Reading keychain entry, because either user or password were empty
The login credentials for '****' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Invalid username and password combination. Used '****' as the username.

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/var/lib/gems/2.4.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/client.rb:488:in `send_shared_login_request': [!] The request could not be completed because: (Spaceship::InvalidUserCredentialsError)
	Invalid username and password combination. Used '****' as the username.[0m
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/client.rb:753:in `do_login'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/client.rb:384:in `login'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/client.rb:346:in `login'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/pilot/lib/pilot/manager.rb:23:in `login'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/pilot/lib/pilot/manager.rb:16:in `start'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/pilot/lib/pilot/build_manager.rb:13:in `upload'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /var/lib/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /var/lib/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	from /var/lib/gems/2.4.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
</pre>

### Environment
<details><summary>✅ fastlane environment ✅</summary>
<pre>
### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based jessie/sid                                         |
| Ruby                        | 2.4.5                                                           |
| Bundler?                    | false                                                           |
| Git                         | git version 1.9.1                                               |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 14.04.5 LTS debian_based jessie/sid (3.13.0-144-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.0.1f 6 Jan 2014                                       |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.9        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2019-01-17**
</pre>
</details>

**Comment by davidwadge** [comment]
If I can't get it working, the solution seems to be to submit to HockeyApp and distribute to stores via that channel.

**Comment by Slicit** [comment]
No more progress on my side, was able to upload one App, then now IP gets banned again ...
@davidwadge have you made some progress on your side?

**Comment by davidwadge** [comment]
@Slicit I'm afraid not. We've chosen to use App Center (previously known as HockeyApp) to manage the distributions instead. You can publish to fastlane with something like:

`fastlane run appcenter_upload api_token:${APPCENTER_API_TOKEN} owner_name:${ACCOUNT_OWNER} app_name:${APP_NAME}  ipa:${IPA_BUILD}  release_notes:${RELEASE_NOTES}`
