### ISSUE TITLE
ERROR ITMS-90164: Invalid Code Signing Entitlements. 

### ISSUE THREAD

**Issue by bnns** [fastlane/fastlane#1409]
`The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile.`

I'm trying to use `match` in my build to target multiple apps (using `dotenv` as described [here](https://github.com/fastlane/fastlane/blob/master/docs/FAQs.md)). I get the above when I run `fastlane appstore --env app`. Here's my Fastfile:

```ruby
  lane :appstore do
    produce(
      username: ENV['PRODUCE_USERNAME'],
      app_identifier: ENV['APP_ID'],
      app_name: ENV['PRODUCE_APP_NAME'],
      language: ENV['PRODUCE_LANGUAGE'],
      app_version: ENV['PRODUCE_APP_VERSION'],
      sku: ENV['PRODUCE_SKU']
    )

    match(
      git_url: "git@github.com:my-organization/mobile-certs",
      type: "appstore",
      app_identifier: ENV['APP_ID'],
      username: ENV['PRODUCE_USERNAME']
    )

   # had to include this because there was a different error with bundle ID in the .plist file
    set_info_plist_value(
      key: 'CFBundleIdentifier',
      path: ENV['PLIST_PATH'],
      value: ENV['APP_ID']
    )

    gym(
      use_legacy_build_api: true,
      scheme: ENV['GYM_SCHEME'],
      project: './ios/mobileTest.xcodeproj'
    )

    deliver(
      primary_category: ENV['DELIVER_PRIM_CATG'],
      secondary_category: ENV['DELIVER_SCND_CATG'],
      metadata_path: ENV['METADATA_FOLDER'],
      app_identifier: ENV['APP_ID'],
      skip_binary_upload: false,
      app_icon: ENV['APP_ICON'],
      submit_for_review: false,
    )
  end
```

**Comment by bnns** [comment]
My app id should be `com.mobile-app.app`. Here's what I see when I run `ipa info mobileApp.ipa`

```bash
...
| Entitlements                | keychain-access-groups: ["55555TEAM.*"]
|                             | get-task-allow: false
|                             | application-identifier: 55555TEAM.mobile-app
|                             | com.apple.developer.team-identifier: 55555TEAM.mobile-app
|                             | aps-environment: production
|                             | beta-reports-active: true
...
```

Notice that the application-identifier looks different. Isn't `match` supposed to take care of that?

**Comment by joecdimas** [comment]
im working with @bnns  on this issue.

I was able to get around this by doing this:
`     produce(
      username: ENV['PRODUCE_USERNAME'],
      app_identifier: ENV['APPLE_ID'],
      app_name: ENV['PRODUCE_APP_NAME'],
      language: ENV['PRODUCE_LANGUAGE'],
      app_version: ENV['PRODUCE_APP_VERSION'],
      sku: ENV['PRODUCE_SKU']
    )

    match(
      git_url: "git@github.com:bloomfire/mobile-certs",
      type: "appstore",
      app_identifier: ENV['APPLE_ID'],
      username: ENV['PRODUCE_USERNAME']
    )

    increment_build_number(
      xcodeproj: './ios/mobileTest.xcodeproj',
      build_number: latest_testflight_build_number + 1
    )

    set_info_plist_value(
      key: 'CFBundleIdentifier',
      path: ENV['PLIST_PATH'],
      value: ENV['APPLE_ID']
    )

    gym(
      use_legacy_build_api: true,
      scheme: ENV['GYM_SCHEME'],
      project: './ios/mobileTest.xcodeproj'
    )

    update_app_identifier(
      app_identifier: ENV['APPLE_ID'],
      xcodeproj: './ios/mobileTest.xcodeproj',
      plist_path: ENV['UPDATE_PLIST_PATH'],
    )

    deliver(
      primary_category: ENV['DELIVER_PRIM_CATG'],
      secondary_category: ENV['DELIVER_SCND_CATG'],
      metadata_path: ENV['METADATA_FOLDER'],
      app_identifier: ENV['APPLE_ID'],
      skip_binary_upload: false,
      app_icon: ENV['APP_ICON'],
      submit_for_review: false,
    ) `

I also changed the project.pbxproj by using `update_app_identifier` and update this line `PRODUCT_BUNDLE_IDENTIFIER = "";` 
I feel that Gym or Deliver should have taken care of that

Also: plist_path takes the plist `Path to info plist, relative to your Xcode project:` In this case, I couldn't use the `PLIST_PATH` variable so I had to create a new variable for this.
Any reason why I couldn't use the `PLIST_PATH` instead ?

**Comment by vpolouchkine** [comment]
@joecdimas Are you still running into this?

**Comment by bnns** [comment]
It was fixed, though I've forgotten how. We run into this whenever we update react-native though. It seems to be an xcode setting.
