### ISSUE TITLE
[frameit] Automate measuring of "slot" offsets and width

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14094]
Currently we have to manually measure the offsets and width of the "slot" where the screenshots will be placed. We should automate that as part of the frame update process.

Manual process: E.g. use paint.net to open the file, then use the magic wand tool on the slot area to get both the offsets and dimensions, write that data to the file `offsets.json`.

The file used to update the frames is this: https://github.com/fastlane/fastlane/blob/master/frameit/frames_generator/Rakefile `MiniMagick` is already used to trim the whitespace around the device frames (which has its own problems, see #14093), maybe there is a way to "measure" an area similar to the "magic wand technique" described above as well.

**Comment by janpio** [comment]
iPhone X, XR, XS, XS Max have rounded corners (and that silly notch) which luckily didn't worry paint.net at all - but might complicate a solution via code a bit. Just something to keep in mind.

**Comment by janpio** [comment]
This could be a starting point: http://www.fmwconcepts.com/imagemagick/magicwand/index.php (especially see the commands behind the scenes at the bottom)

**Comment by joshdholtz** [comment]
@janpio I looovvvveeee this idea so much! I had to do the same manual process awhile back and it was not fun and didn't scale very well 😉

**Comment by mollyIV** [comment]
👋 after some docs tickets, I guess it's about time to do some coding 😅 

@janpio  could you please give me a bit more context about `frames_generator` steps? 
As far as I understood, you modify `offsets.json` file manually once you download the images from [Facebook frameset](https://facebook.design/devices) by running `rake` command? 🤔 

The goal of this task is to put the correct values into `offsets.json` file automatically. It's not about getting rid of the json file, right? I can imagine we are going to add some code (`MiniMagick` magic wand) before writing the offsets to the json file:

```ruby
...

cp("offsets.json", File.join(output, "offsets.json"))
  puts("Copied over offsets.json")
```

🙏 🙇

**Comment by janpio** [comment]
I have actually never generated frames myself, so @joshdholtz has to fill you in on that, he did that just recently. But the rest of what you wrote follow my understanding - when we update the frames, the process should automatically update `offsets.json` for you to confirm manually. `MiniMagick` is already used in some other places of frameit, so it makes sense to also use it here, and has that magicwand thing that looked similar to what I used manually in paint.net.

**Comment by mollyIV** [comment]
I had a chance to play a bit with [magicwand](http://www.fmwconcepts.com/imagemagick/magicwand/index.php) script. I have been trying to get a selection of "slot" (screen space) area. 

![output](https://user-images.githubusercontent.com/10795657/52180651-44fff880-27e9-11e9-94dc-0e7bfe8e7180.png)
_The original image comes from [Facebook devices](https://facebook.design/devices")_

As you can see, the red border is visible also on the outside of the frame. When I used [SketchBook](https://sketchbook.com/) magic wand tool, the selection was correct - only the inner frame (aka "slot") has been selected.

I was looking for a way to get a frame (rectangle size) of inner red selection however couldn't find anything in [minimagick docs](https://github.com/minimagick/minimagick) (I was checking CLI API of ImageMagick). I will dive deeper into ImageMagick and GraphicsMagick API.

Do you guys have other ideas (starting points other than magicwand) how we could tackle this? 🤔 

🙇 🙇

**Comment by janpio** [comment]
Some very hack-ish logic: If pixel right to red border is transparent, we are at the correct red border. If it's the left one, its the outer thing.

**Comment by mollyIV** [comment]
So another solution might be transparent area detection. I found interesting thread on [stackoverflow](https://stackoverflow.com/questions/26244191/imagemagick-detect-coordinates-of-transparent-areas). I tired it for iPhone 5c:

```bash
$ convert Apple\ iPhone\ 5c\ Blue.png -alpha extract -negate           \
   -define connected-components:verbose=true       \
   -define connected-components:area-threshold=100 \
   -connected-components 8 -auto-level  result.png
Objects (id: bounding-box centroid area mean-color):
  494: 640x1136+67+239 386.5,806.5 727040 srgb(255,255,255)
  4: 767x1605+0+0 385.4,801.2 478199 srgb(0,0,0)
  522: 115x1004+0+601 12.1,1244.6 10023 srgb(255,255,255)
  0: 517x232+0+0 125.3,36.3 8303 srgb(255,255,255)
  8: 131x115+636+0 731.1,26.2 3908 srgb(255,255,255)
  561: 108x108+659+1497 740.4,1578.0 2954 srgb(255,255,255)
  500: 7x48+0+301 3.0,323.7 325 srgb(255,255,255)
  511: 7x42+0+454 3.0,473.7 283 srgb(255,255,255)
```
By parsing the verbose, we can get the info we need:
* `494: 640x1136+67+239 386.5,806.5 727040 srgb(255,255,255)` --> width = 640, x = 67, y = 239. 

The values matches with the current `offset.json` file and the magic wand values from a third party program. The solution seems to be a bit hack-ish, since we put the values manually now, I'd give it a try. WDYT?

**Comment by janpio** [comment]
Phew, I definitely don't understand it. But if it works, why not.
Best test it with some more devices, especially the newer ones with rounded corners - those might get interesting.

**Comment by mollyIV** [comment]
👋 PR has been created: https://github.com/fastlane/fastlane/pull/14184
CC: @janpio @joshdholtz
