### ISSUE TITLE
[frameit] Currently iffy areas

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14098]
While working with `frameit` a bit I noticed several areas that might need some work:

- "Smart" device frame selection has its limits #14097
- Device frames have inconsistent dimensions #14093
- `offsets.json`: Automate measuring of "slot" offsets and width #14094
- Documentation of options is missing: #14076 #14077 #14078 
- Certain screenshots can't be framed: iPhone XR #14080, iPad Pro 11, 10.5 and 9.7 #14079
- Advanced functionality is intermingled with basic framing #14088 
- `resize_frame!`? What is it used for?
- `force_device_type` list of available options is pretty outdated (which means one can not actually force the wanted device frame)
- Configuring and understanding `Framefile.json` is pain
- Frame color selection possibility is rudimentary (especially for the action)
- I could not find a way to use different frames per screenshot
- `padding` has no default, the documented `50` does not appear anywhere

Missing features:

- Output directory
- Better Filtering screenshots to frame/wrap
- Use custom frames
- More custom screenshot placement on background/frame (similar to macOS handling)

**Comment by janpio** [comment]
- Minimal `Framefile.json` to not crash (but still goes into simple mode):
```
{
  "default": {
  },
  "data": [
  ]
}
```
-

**Comment by Jerland2** [comment]
@janpio this should be added to the documentation, as the current documentation always fails to frame with title.  Reproduction steps:  Download any of the sample apps -> put screenshots to be framed -> in terminal run fastlane framit -> Errors: Could not get title for screenshot ./en-US/iPhone SE-0-Screenshot.png. Please provide one in your Framefile.json or title.strings

**Comment by janpio** [comment]
Can you elaborate? I am not sure I understood everything.
