### ISSUE TITLE
`IMG_APPEARS_CORRUPT`on Screenshot Upload

### ISSUE THREAD

**Issue by joshuajung** [fastlane/fastlane#14109]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

iOS Screenshot upload fails with error message:
`[!] [IMG_APPEARS_CORRUPT] That file is corrupt. It may help to open it in an image editor and resave it before trying again. (Spaceship::UnexpectedResponse)`

##### Command executed

`bundle exec fastlane deliver`

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
jajmbp2:Curry jaj$ bundle exec fastlane deliver
[✔] 🚀 
[14:36:40]: Successfully loaded '/Users/jaj/Repositories/curry-ios/Curry/Deliverfile' 📄

+-------------------------+-----------------------+
|      Detected Values from './Deliverfile'       |
+-------------------------+-----------------------+
| skip_binary_upload      | true                  |
| skip_metadata           | true                  |
| skip_app_version_update | true                  |
| app_identifier          | com.joshua-jung.Curry |
| username                | (Redacted)   |
+-------------------------+-----------------------+

[14:36:40]: Login to App Store Connect ((Redacted))
[14:36:43]: Login successful

+--------------------------------------+-----------------------+
|                   deliver 2.114.0 Summary                    |
+--------------------------------------+-----------------------+
| screenshots_path                     | ./screenshots         |
| metadata_path                        | ./metadata            |
| username                             | (Redacted)   |
| app_identifier                       | com.joshua-jung.Curry |
| platform                             | ios                   |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_binary_upload                   | true                  |
| skip_screenshots                     | false                 |
| skip_metadata                        | true                  |
| skip_app_version_update              | true                  |
| force                                | false                 |
| overwrite_screenshots                | false                 |
| submit_for_review                    | false                 |
| reject_if_possible                   | false                 |
| automatic_release                    | false                 |
| phased_release                       | false                 |
| run_precheck_before_submit           | true                  |
| precheck_default_rule_level          | warn                  |
| ignore_language_directory_validation | false                 |
| precheck_include_in_app_purchases    | true                  |
+--------------------------------------+-----------------------+

[14:36:47]: Verifying the upload via the HTML file can be disabled by either adding
[14:36:47]: `force true` to your Deliverfile or using `fastlane deliver --force`
[14:36:47]: Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[14:36:50]: HTML file confirmed...
[14:36:52]: Starting with the upload of screenshots...
[✔] Activating language en-US... 
[14:36:55]: Uploading 4 screenshots for language en-US
[14:36:55]: Uploading './screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-0-IndicatorMap.png'...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	25: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	24: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	23: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	22: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	21: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	20: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	19: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	18: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	17: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	16: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	15: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	14: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	13: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	12: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	11: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/runner.rb:38:in `run'
	10: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
	 9: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:50:in `upload'
	 8: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:50:in `each'
	 7: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:52:in `block in upload'
	 6: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:52:in `each'
	 5: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:65:in `block (2 levels) in upload'
	 4: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/tunes/app_version.rb:497:in `upload_screenshot!'
	 3: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/tunes/tunes_client.rb:823:in `upload_screenshot'
	 2: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/du/du_client.rb:21:in `upload_screenshot'
	 1: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/du/du_client.rb:96:in `upload_file'
/Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/du/du_client.rb:172:in `parse_upload_response': [IMG_APPEARS_CORRUPT] That file is corrupt. It may help to open it in an image editor and resave it before trying again. (Spaceship::UnexpectedResponse)
	25: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	24: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	23: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	22: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	21: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	20: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	19: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	18: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	17: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	16: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	15: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	14: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	13: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	12: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	11: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/runner.rb:38:in `run'
	10: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
	 9: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:50:in `upload'
	 8: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:50:in `each'
	 7: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:52:in `block in upload'
	 6: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:52:in `each'
	 5: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/deliver/lib/deliver/upload_screenshots.rb:65:in `block (2 levels) in upload'
	 4: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/tunes/app_version.rb:497:in `upload_screenshot!'
	 3: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/tunes/tunes_client.rb:823:in `upload_screenshot'
	 2: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/du/du_client.rb:21:in `upload_screenshot'
	 1: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/du/du_client.rb:96:in `upload_file'
/Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/spaceship/lib/spaceship/du/du_client.rb:172:in `parse_upload_response': [!] [IMG_APPEARS_CORRUPT] That file is corrupt. It may help to open it in an image editor and resave it before trying again. (Spaceship::UnexpectedResponse)
```

</details>

Manual upload to App Store Connect works fine, and re-saving the images in Photoshop did not solve the issue.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bundler                   | 1.17.2       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-01-20**
</details>

**Comment by joshuajung** [comment]
> Could you take a look at the spaceship logs at `/tmp/spaceship-*.log` and see what Apple is returning before this crashes? Anything strange going on in there?

Last log before the error is
```
INFO  [14:36:56]: >> GET /WebObjects/iTunesConnect.woa/ra/apps/version/ref: [undefined body] 
DEBUG [14:36:56]: << GET /WebObjects/iTunesConnect.woa/ra/apps/version/ref: 200 {"data"=>{"ssoTokenForVideo"=>"pkXSLXNyLjRfBrCZcUb+Z7fk+eXE4ihEsCkNYJPJCUE=", "ssoTokenForImage"=>"te+fQl7IcAV69k8q6IuyrhCJdEqYIOS2aH0Lj61C2JU="}, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>nil}, "statusCode"=>"SUCCESS"}
```

Full error log then reads:
```
INFO  [14:36:56]: >> POST https://du-itc.itunes.apple.com/upload/image: [non JSON body] 
DEBUG [14:36:58]: << POST https://du-itc.itunes.apple.com/upload/image: 400 {"statusCode"=>400, "errorCodes"=>["IMG_APPEARS_CORRUPT"], "suggestionCode"=>"IMG_RESAVE_CORRUPTED", "nonLocalizedMessage"=>"The image file is corrupt. Please edit the image and re-save it.", "localizedMessage"=>"That file is corrupt. It may help to open it in an image editor and resave it before trying again.", "width"=>nil, "height"=>nil}
```

Thanks @ramnac for the hint - will try with Ruby 2.5.0 on next opportunity.

**Comment by janpio** [comment]
Ok, this is then really a normal "error" response from Apple's server, not a follow up error of a previous problem (which we also already had in that part of the code...). Sorry :/

**Comment by gmcdowell** [comment]
this is still an issue. Running fastlane 2.119.0 and ruby-2.6.0

**Comment by bartoszhernas** [comment]
I think this started happening recently when apple switched screenshots requirements.

> Starting March 27, 2019, all app submissions for iPhone or iPad, including universal apps, will require screenshots for iPhone XS Max or the 12.9-inch iPad Pro (3rd generation).

Trying to add screenshots manually, I am getting an error that size is not correct.

**Comment by bartoszhernas** [comment]
The solution: provide screenshots for iPhone XS Max
