### ISSUE TITLE
Would love to get a "dest" path for "download" action and allow for other file types not just JSON.

### ISSUE THREAD

**Issue by Vincent033** [fastlane/fastlane#1410]
My ultimate goal is to allow for build assets/configurations to be on a remote server and the build machine to access that. Right now I am using the download action to get a JSON from a remote server that can assign some plist items, flags to build and credentials to upload to itc. However, I'd like to ultimately have the ability to download app icons (png), splash screens, and even plists overtop my existing plists (because the update_plist_xxx seems to be limited to strings - not bools or dictionaries).

**Comment by KrauseFx** [comment]
The `Fastfile` is a Ruby file, meaning you can do just about anything there. You can use `curl` by using the `sh` action or you can take a look at the [download action](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/download.rb#L9-L21) and basically copy the code to your `Fastfile` to fit your needs :+1:

**Comment by KrauseFx** [comment]
Let me know if you need any help with that :+1:
