### ISSUE TITLE
[crashlytics] support for aab (android app bundle) 

### ISSUE THREAD

**Issue by IslamSalah** [fastlane/fastlane#14107]
Although I found added support for aab in [supply] action #12568, I didn't find a counterpart support in [crashlytics] action.

One POV may suggest shipping APKs to QA the same way as before aab and ship aab only to the play store. But the argument is that:
1- The QA team won't test the end user actual scenario.
2- This skips [google](https://youtu.be/bViNOUeFuiQ?t=1183) support to facilitate testing aab.

I'll appreciate any help with this issue.

**Comment by joshdholtz** [comment]
@IslamSalah Heyyy! I totally agree that this would be 💯 but Crashlytics doesn't support aab and doesn't look like its in their road map according to https://stackoverflow.com/a/52410188/2464643. Supporting aabs for test distribution services requires them to build the apk on their side for users from the aab which is just one more thing to do 🙃 If you want your QA team to test the same thing that is going to production I would suggest using the internal/alpha/beta testing that is available on Google Play 💪 

Happy fastlaning 🚀
