### ISSUE TITLE
download_dsyms with version: "latest" downloads from latest submission version

### ISSUE THREAD

**Issue by ggirotto** [fastlane/fastlane#14106]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm facing the same problem that [this issue here](https://github.com/fastlane/fastlane/issues/12966), which is basically that the `version: 'latest'` used in the lane use the latest version delivered for deploy. In my case I have the beta app in a separate bundle, which means that in the beta bundle I'll never have a release app.

What I was expecting of the "latest" is that it fetches the latest build processed from the AppStore Connect **Activity** tab ,not related with the app submissions for App Store.

As you can see in the log output, it's fetching the dsyms from version 1.3.0, while I have recently uploaded the version 3.0.0. Actually the `latest` flag is fetching the exactly opposite in my case, which is the first version I have released.

##### Command executed

```
download_dsyms(
    app_identifier: "my.beta.bundle",
    version: "latest"
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [10:51:44]: ------------------------------
[10:51:44]: --- Step: default_platform ---
[10:51:44]: ------------------------------
[10:51:44]: Driving the lane 'ios teste' 🚀
[10:51:44]: ----------------------------
[10:51:44]: --- Step: download_dsyms ---
[10:51:44]: ----------------------------
[10:51:44]: Login to App Store Connect (myemail@email.com)
[10:51:48]: Login successful
[10:51:49]: Looking for latest version...
[10:51:55]: Looking for dSYM files for my.beta.bundle v1.3.0
[10:52:02]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 5 to 'my.beta.bundle-1.3.0-5.dSYM.zip'
[10:52:05]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 4 to 'my.beta.bundle-1.3.0-4.dSYM.zip'
[10:52:07]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 0 to 'my.beta.bundle-1.3.0-0.dSYM.zip'
[10:52:10]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 1 to 'my.beta.bundle-1.3.0-1.dSYM.zip'
[10:52:13]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 8 to 'my.beta.bundle-1.3.0-8.dSYM.zip'
[10:52:16]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 2 to my.beta.bundle-1.3.0-2.dSYM.zip'
[10:52:19]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 6 to 'my.beta.bundle-1.3.0-6.dSYM.zip'
[10:52:22]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 7 to 'my.beta.bundle-1.3.0-7.dSYM.zip'
[10:52:25]: 🔑  Successfully downloaded dSYM file for 1.3.0 - 3 to 'my.beta.bundle-1.3.0-3.dSYM.zip' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    lane :testingdsyms do
        download_dsyms(
           app_identifier: "my.beta.bundle",
           version: "latest"
        )
        upload_symbols_to_crashlytics(
            api_token: "key",
            binary_path: "./fastlane/upload-symbols"
        )
        clean_build_artifacts
    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("my.release.bundle") # The bundle identifier of your app
apple_id("myemail@email.com") # Your Apple email address

itc_team_id("ic_teamid") # App Store Connect Team ID
team_id("teamid") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

for_platform :ios do
  team_id 'teamid' # for all iOS related things
  for_lane :beta do
    app_identifier 'my.beta.bundle'
  end
  for_lane :release do
    app_identifier 'my.release.bundle'
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.6.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.1          |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-01-20**
</details> </pre>
</details>

**Comment by joshdholtz** [comment]
@ggirotto The fix for this was just merged in on PR https://github.com/fastlane/fastlane/pull/14092. This will be be included in the next release early next week 😊
