### ISSUE TITLE
Inconsistent exportOptions file manifest output

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#14102]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running gym w/ exportOptions, I'm having an issue that the `manifest.plist` file is not being moved properly. 

After some digging, I (think) I've found the error:

When gym is running and xcode is being built, at [xcodebuild.rb](https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/lib/fastlane/actions/xcodebuild.rb#L317) line 317 the file is being generated as `ExportOptions.plist`.

But at [runner.rb](https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/gym/lib/gym/runner.rb) it gets the information from [package_command_generator_xcode7](https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/gym/lib/gym/generators/package_command_generator_xcode7.rb#L95) which is declared as `manifest.plist` at line 95. I've printed the output at the `move_manifest` and it is consistent with this scenario.

Thanks,

**Comment by joshdholtz** [comment]
@pedro380085 Heyyy 👋  Are you able to provide a sample/example for me to test out with this? An example `manifest.plist` with what your output looks like would be 💯 or an example project would be 💯 💯 😊 This would help me debug this faster and help provide you with a solution faster to make sure I'm solving the right thing 💪

**Comment by pedro380085** [comment]
Hi @joshdholtz, yes, here follows an example project on my Fastfile lane:

```
profileFile = "my.bundle.mobileprovision"

    profileDirectory = "#{Dir.home}/Library/MobileDevice/Provisioning Profiles"
    result = `grep -lr 'my.bundle' '#{profileDirectory}'`

    if result.length != 0
        profilePath = result.strip
    else
        profileDirectory = "path/fastlane/Profiles"
        sigh(
            skip_certificate_verification: false,
            output_path: profileDirectory,
            filename: profileFile
        )
        profilePath = profileDirectory + "/" + profileFile
    end

    profileSpecifier = Plist.parse_xml(`security cms -D -i '#{profilePath}'`)['Name'];

    xargs = [
        "PROVISIONING_PROFILE_SPECIFIER='#{profileSpecifier}'",
        "PROVISIONING_PROFILE=''",
        "DEVELOPMENT_TEAM=XXXXXXXXX",
        "CODE_SIGN_IDENTITY='iPhone Distribution'"
    ].join(" ")

    gym(
        xcargs: xargs,
        export_options: {
            provisioningProfiles: {
                "my.bundle": profileSpecifier
            },
            manifest: {
                appURL: "my.bundle.ipa",
                displayImageURL: "iTunesArtwork.png",
                fullSizeImageURL: "iTunesArtwork@2x.png"
            }
        }
    )
```
