### ISSUE TITLE
Can't upload to Crashlytics

### ISSUE THREAD

**Issue by RedPlumber** [fastlane/fastlane#14113]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Let's start to say that everything was working fine and that I did not touch anything when at some point Friday last week I started to have this issue when uploading a build to crashlytics.

``` 
[12:50:23]: [31m2019-01-21 12:49:46.039 submit Crashlytics: Crashlytics.framework/submit 1.4.0 (20)
2019-01-21 12:50:12.813 submit Crashlytics: Unable to find application in Crashlytics. Response code: 0
2019-01-21 12:50:12.814 submit Crashlytics: Does this app belong to this org?
 We couldn't validate app with bundle ID com.digitaslbi.eonenergy in the selected organization, so make sure you've first added your app through the Crashlytics app.
 You can check that your API key and build secret are correct by going here: https://crashlytics.com/settings/organizations
 Then select the org and click on API key or build secret underneath the org name.
```


I have also updated now
- fastlane to 2.114.0
- crashlytics to 3.12.0
- fabric to 1.9.0

everything updated to latest and it's still not working.

##### Command executed

`bundle exec fastlane iOS build_mocks`

**Comment by janpio** [comment]
That looks and sounds more like a server side response from Crashlytics. As you also didn't change anything on your side before it broke, maybe something did on Crashlytics server or your account?

**Comment by johnknapprs** [comment]
Possibly the path to the correct fabric binary changed in your project.  

Happened to me recently.  A cached directory kept the old binary working for awhile, didn't notice the change.  Then when the cache got cleared it broke, even though everything looked up to date. 

Fixing the path to the upload binary to the new location in my project fixed it. So maybe heck your paths and parameters to make sure they are all correct?

**Comment by RedPlumber** [comment]
> That looks and sounds more like a server side response from Crashlytics. As you also didn't change anything on your side before it broke, maybe something did on Crashlytics server or your account?

No changes were made in Crashlytics account neither on fastlane for months.

**Comment by RedPlumber** [comment]
> Possibly the path to the correct fabric binary changed in your project.
> 
> Happened to me recently. A cached directory kept the old binary working for awhile, didn't notice the change. Then when the cache got cleared it broke, even though everything looked up to date.
> 
> Fixing the path to the upload binary to the new location in my project fixed it. So maybe heck your paths and parameters to make sure they are all correct?

@johnknapprs Thanks, I will have a look at the path but I suspect that specific issue would not give the same error.

**Comment by RedPlumber** [comment]
it was a path issue. Thanks.
