### ISSUE TITLE
Support all xcode languages with Deliver

### ISSUE THREAD

**Issue by lucarge** [fastlane/fastlane#14114]
### Feature Request

Hi 👋 
Recently I noticed that deliver does not support all available languages that, indeed, are available inside xcode.

Looks like all basic languages are supported, but not all languages (see screenshots below).

#### Screenshots

Basic languages
![basic languages](https://user-images.githubusercontent.com/25553165/51488712-8d112b00-1da6-11e9-8c3c-b6d09262d23c.png)

All available languages
![all languages](https://user-images.githubusercontent.com/25553165/51488713-8d112b00-1da6-11e9-89b8-e552ee20f016.png)

It would be useful to add support to all of them.

#### Motivation Behind Feature
At my organisation we categorise i18n flavours by **language and country**. This means that, as an example, we do not use 'it' for Italy and Switzerland, but we use **it-IT** and **it-CH** instead. This allows us to change small things according to which country the user is from, even for the same language (eg: SplashScreen wording).

#### Feature Description
Simply add the missing languages to Deliver, with an effort similar to [this one](https://github.com/fastlane/fastlane/pull/14110)

#### Alternatives or Workarounds
I did not found any workaround to this limitation unfortunately 😞

**Comment by lucarge** [comment]
Hi @janpio, thanks for labelling this issue.

I just [started working](https://github.com/lucarge/fastlane/commit/e1b5133be14f264bf02dd0ad122b6f0b88f48028) on this and I have some doubts about how to proceed: mainly I'm missing the reason why the language mappings differs so much from the ones provided by XCode; I suppose there are constraints of which I'm not aware.

Can you provide me some context on this?

@KrauseFx you pop up often inside the git blame of these files, maybe you have some suggestions/heads up too?

Thanks 🙏

**Comment by lucarge** [comment]
Hi guys 👋 

Further investigations on this issue led me to discover that App Store Connect does not support country based metadata. The languages that fastlane already supports, with the recent additions linked in the issue description, are all it's available on App Store Connect at the moment.

I'll probably go ahead and file a feature request to Apple directly, but I think I should close this issue since it has no actionable at the moment.

I'm sorry for the noise caused by opening this issue: I'll follow up with another feature request if something changes on Apple side. 🙌

**Comment by janpio** [comment]
Don't worry about the issue, we all learned something here - so thanks! Keep us posted.
