### ISSUE TITLE
Fastlane  to upload snapshots and images

### ISSUE THREAD

**Issue by ninaa0718** [fastlane/fastlane#14112]
hi,
how can i upload snapshots/images on playstore to production track  and just save it without rolling out?.

thanks!

```
lane :deploy do
gradle(task: "assembleRelease")
supply(
skip_upload_apk :  true,
skip_upload_aab : true,
skip_upload_metadata: true,
skip_upload_images: false,
skip_upload_screenshots: false
validate_only : false      
 check_superseded_tracks:  true
)end
```

**Comment by janpio** [comment]
Good question, I am not sure if this is currently possible. 

There is the `rollout` parameter, but I am not sure if this can be set to 0.
