### ISSUE TITLE
Fastlane deliver upload only screenshots 

### ISSUE THREAD

**Issue by ninaa0718** [fastlane/fastlane#14126]
How can i upload only screenshots and skip submission in fastlane deliver? I added below lane in my fast file,please correct me if this is wrong:

```
lane: Upload_Appstore do
  desc "Upload to appstore"

  deliver(
    ipa: "",
    skip_screenshots: false,
    skip_metadata: true,
    submit_for_review: false,
    )
```

should I add anything in my deliver file?

**Comment by janpio** [comment]
From my understanding of the documentation, this should work - `submit_for_review` is defined as "Submit the new version for Review after uploading everything" and you set that to `false`.
