### ISSUE TITLE
Impact of the unification of App Store Connect and Developer program teams?

### ISSUE THREAD

**Issue by elviin** [fastlane/fastlane#14125]
How the unification of these services will affect Fastlane?  I have not read anything about the team ID's, will be there a single team ID per application?

https://developer.apple.com/support/teams/

**Comment by lbrownell-gpsw** [comment]
I have one impact, that appears to be new (within the last week).

App Store Connect now reports the users enterprise team, if there is one.  As a result, our uploads to App Store Connect via Pilot have been failing, with this:
```
Login to App Store Connect (ourbuildaccount@ourcompany.com)
Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "<app-store-itc-team-id>"
or
  itc_team_name "<app-store-team-name>"
 
"<app-store-team-name>" (<app-store-itc-team-id>)
"<enterprise-team-name>" (<enterprise-itc-team-id>)

Multiple teams found on App Store Connect, Your Terminal is running in non-interactive mode! Cannot continue from here.
Please check that you set FASTLANE_ITC_TEAM_ID or FASTLANE_ITC_TEAM_NAME to the right value.
```
We've solved it by setting one of the above environment variables as suggested, but might want to update Pilot's docs to describe this new phenomenon.

Thanks.
