### ISSUE TITLE
Fastlane is still running version 2.114 instead of 2.110 after a reinstall

### ISSUE THREAD

**Issue by dfiggtns** [fastlane/fastlane#14124]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
After uninstalling/reinstalling an older version of Fastlane, it still appears to be running the latest version.

#### Question Description
I recently updated Fastlane to version 2.114, but when I ran my ionic ios build script, it failed on the get_provisioning_profile step. It had worked fine just before I ran the update.

I uninstalled it using gem uninstall fastlane, then reinstalled it using gem install fastlane -v 2.110.0, gem list fastlane showed only version 2.110.0.

Then I ran the script again and the box in the get_provisioning_profile step still showed version 2.114.0 and the step failed with the same error.

Does anyone know how to make Fastlane use version 2.110.0, instead of the latest version?

To uninstall/reinstall Fastlane:

    gem uninstall fastlane
    gem install fastlane -v 2.110.0

The result of gem list fastlane:

    *** LOCAL GEMS ***

    commander-fastlane (4.4.6)
    fastlane (2.110.0)

Expected result:

    +-------------------------------------+--------------------------+
    |                    Summary for sigh 2.110.0                    |
    +-------------------------------------+--------------------------+

and the Fastlane script to work successfully as before.

Actual result:

An example of one of the Fastlane boxes showing v2.114:

    +-------------------------------------+--------------------------+
    |                    Summary for sigh 2.114.0                    |
    +-------------------------------------+--------------------------+

The Fastlane error messages:

    [13:47:24]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you

    [13:47:25]: No certificates for filter: Certificate ID: '433NN4XZ66' 

    [13:47:25]: Could not find a matching code signing identity for type 'AdHoc'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide. If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert

**Comment by dfiggtns** [comment]
fastlane env output:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.112.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

**Comment by janpio** [comment]
Your `fastlane env` mentions `2.112.0` - another version.

What is the output of `fastlane -v`? It should output a path - are there any other `fastlane` folders in the `gem` folder of that path?

**Comment by dfiggtns** [comment]
Yes, I've been trying ither ideas to get it to work and that was my latest attempt - to install another version, but it made no difference.

That's interesting:

fastlane -v output:

    fastlane 2.112.0

but bundle exec fastlane -v output:

    fastlane installation at path:
    /Users/path_to_project/vendor/cache/ruby/2.5.0/gems/fastlane-2.114.0/bin/fastlane
    -----------------------------
    fastlane 2.114.0

How do I get rid of that one, as gem uninstall/install is what produced the first output, so it obviously didn't touch the second location?

**Comment by janpio** [comment]
Are you 100% sure your `fastlane -v` output is complete? I specifically asked for "including the command being executed." because it should also output a `fastlane installation at path:"` string right after the command is executed.

Besides that, this looks pretty consistent now.

Please run your lane via `fastlane` now and post the _complete_ output of you are getting.

**Comment by dfiggtns** [comment]
Oh yes, oops, sorry I missed that line. Here's the full output:

    $ fastlane -v
    fastlane installation at path:
    /Users/myuserid/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/bin/fastlane
    -----------------------------
    fastlane 2.112.0

    #######################################################################
    # fastlane 2.114.0 is available. You are on 2.112.0.
    # You should use the latest version.
    # Please update using `sudo gem install fastlane`.
    #######################################################################

**Comment by dfiggtns** [comment]
The question now, I guess, is how do I uninstall the fastlane version in the project folder, so I only have the one version in the global folder that is controlled by gem install?

**Comment by janpio** [comment]
That should generally only be used if you execute fastlane via `bundle exec fastlane ...`. That tells ruby to use the dependencies from the local `Gemfile`, which you (or fastlane) installed via `bundle install`. It is usually a much faster way to run fastlane, so it is recommended.

I want to understand how the 114 version can appear in your plain `fastlane ...` call. Can you please run your lane via `fastlane` now and post the complete output of you are getting?

Also have a look at your `Gemfile` in your project and best post its output here.

**Comment by dfiggtns** [comment]
Ahah, now you mention gemfile, there was one in the root folder of the project. When I removed it and the lock file, fastlane was run with v2.112.0.

When I looked at the lock file, it did have v2.114.0 specified, so that was obviously being ignored by the gem install and update commands.

So, now I've found the way to get it to use the correct version, how can I get the project's gem file to be updated with the gem update command?

**Comment by janpio** [comment]
- `gem install` is global: `fastlane ...`
- `Gemfile` + `bundle install/update` is local: `bundle exec fastlane ...`.

So everything you do with `gem` only influences `fastlane ...`, and everything you do in the `Gemfile` and then via `bundle ...` only influences `bundle exec fastlane ...`.

But that does not explain why it was running fastlane 2.112 but then using sigh 2.114 as you wrote above.

**Comment by dfiggtns** [comment]
I can only surmise that there was some confusion going on, which has been solved by removing the gem files from the project root folder.

As bundle exec ... seems to work in the platforms/ios folder without the gem files and uses the global fastlane version, am I right in thinking that I can do without the project level gem files?

**Comment by janpio** [comment]
> platforms/ios folder

Cordova project?

> project level gem files

What does that mean?

Could you please describe your folder structure, where you have a `fastlane` folder with a `Fastfile`, where you have a `Gemfile` and from which folder you are executing the commands?

**Comment by dfiggtns** [comment]
It's the typical ionic folder structure:

    project-folder (top level)
    gemfile
    gemfile.lock
    ->platforms
      ->android
      ->ios
        ->fastlane
          fastfile
    ...
-> = subfolder
project level means directly in the top level folder as shown above.

**Comment by dfiggtns** [comment]
As I said, in the top level and platforms/ios folders.

With the gem files present, it doesn't work; with them absent, it does work.

**Comment by janpio** [comment]
Why in two location? Why do you run `fastlane` in a folder where there is no `fastlane` folder and configuration? I still don't really understand.

That `Gemfile` in the top folder should not apply to running the command in the subfolder. I guess this is where a big part of the confusion comes from.

A suggestion: 
Put your `fastlane` folder in the root of your Ionic/Cordova project (`project-folder`), and supply the path to your iOS project to the `gym`/`build_app` actions via parameters like `project` or `workspace`. The projects are generated in Cordova and using the wrong command can delete the whole folder, and in general your current setup complicates things. Then you can also run the fastlane commands from the same folder where you would use `ionic` or `cordova` CLI.

**Comment by dfiggtns** [comment]
By two locations, I was referring to my tests that I mentioned above when I figured out what made it work, as that's what I thought you referring to.

I normally run the fastlane command from the platforms/ios folder, where the fastlane folder is. This is where the documentation says to put the fastlane folder and run the commands from.

I can't put the fastlane files in the project root, as there are different settings for bith ios and android. That's why they need to be in the respective platforms folder.

**Comment by dfiggtns** [comment]
It turned out that when I deleted the gemfile in the root dir, it used the global fastlane and worked properly.
