### ISSUE TITLE
Pushing to hockeyApp returns '"api token invalid"

### ISSUE THREAD

**Issue by ksairi** [fastlane/fastlane#14127]
There is something weird between Appcenter and hockeyApp, there is going to a merge by the end of the year so maybe that explains why. I'm providing any `api_token` that is in my appcenter profile and the response of fastlane is still:
`Error when trying to upload file(s) to HockeyApp: 400 - {"errors"=>{"credentials"=>["api token invalid"]}}`

Here is the important part of my Fastfile which is trying to push to hockeyApp:
```
desc "Deploy a new beta version to the HockeyApp"
  lane :deployReleaseStaging do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
    puts "increment version code to #{versionCode + 1}"
    gradle(
      task: "assembleReleaseStaging"
    )
    hockey(apk: 'app/build/outputs/apk/app-releaseStaging.apk', api_token:'...........', mandatory:'1')
    slack(message: "Successfully pushed beta version to HockeyApp (android).")
  end
```
If I shouldn't be using the appcenter api_token, where can I create a hockeyApp api_token?
Or where is the method `hockey` trying to push? To the appcenter or hockeyApp?

**Comment by janpio** [comment]
`hockeyapp` is all HockeyApp - so I assume you have to create the API Key in the HockeyApp UI still.
Appcenter has its own action via this plugin: https://github.com/Microsoft/fastlane-plugin-appcenter/

**Comment by ksairi** [comment]
amazing @janpio. It is working with that plugin!
I think fastlane documentation should mention about this plugin and remove `hockey` because it looks is not working anymore and eventually will merge with appcenter.

**Comment by janpio** [comment]
Good point. 

Do you maybe want to create a PR for that? On the documentation of the `hockeyapp` action is a link that opens the correct file in Github - just add some text in the description of the plugin and open a PR 🚀

**Comment by ksairi** [comment]
@janpio I just tried to add some description to the docs but the docs are hosted on `https://docs.fastlane.tools/actions/hockey/`. How can I edit that file?
There is an option to `Edit on github` but it opens `https://github.com/fastlane/fastlane/edit/master/fastlane/lib/fastlane/actions/hockey.rb` which is not the documentation, is the actual hockeyApp development in ruby

**Comment by janpio** [comment]
Code and documentation are one and the same here - scroll down a bit and you find `self.description` and the list of options and their description. This is used to generate the https://docs.fastlane.tools/actions/hockey/ page you mentioned.
