### ISSUE TITLE
crashlytic to support uploading both apk and ipa at the same time

### ISSUE THREAD

**Issue by suesitran** [fastlane/fastlane#14138]
#### Motivation Behind Feature
To support the grow of Flutter framework, I need/wish to upload both Android and iOS app in the same lane.

#### Feature Description
Currently the Crashlytics allows taking both apk_path and ipa_path value at the same time, but actual setup depends on platform name (code from here: https://github.com/fastlane/fastlane/blob/6cf7c2afcd5b6532257ff23b797bd098a337c67b/fastlane/lib/fastlane/actions/crashlytics.rb)

So if I call crashlytic like this
`crashlytics(
    api_token: "{{MY_TOKEN}}",
    build_secret: "{{MY_BUILD_SECRET"",
    apk_path: "{{path/to/apk/file}}",
    ipa_path: "{{path/to/ipa/file}}"
  )
`
Then both files will be uploaded to Crashlytics after this call, as long as token and build secret match.

#### Alternatives or Workarounds
Currently I have to use 2 fastlane, 1 for android and 1 for ios, and run 2 lanes when I wanna upload both files to Crashlytics.

flutter/android/fastlane/Fastfile <=== to upload apk file to Crashlytics
flutter/ios/fastlane/Fastfile <=== to upload ipa file to Crashlytics

**Comment by janpio** [comment]
Oh, interesting use case. As Fastlane got Android support after already supporting iOS for quite some time, many things are built as "either iOS _or_ Android" - which is also the reason why the global `platform` is used here to decide which platform to upload for and thus what file to use.

We will have to look into if the actual crashlytics command line tool can support the upload of both files at the same time though - if not we might have to call the crashlytics CLI twice.

**Comment by janpio** [comment]
Or would it maybe be better to introduce a new `platform` parameter that can overwrite the platform from the context, so you can just call the action twice, once with the APK and once with the IPA path? Would probably be much simpler and quicker to implement on our side.

**Comment by suesitran** [comment]
Is there any plan for this issue?

**Comment by janpio** [comment]
Have you tried the workaround I provided above?

I also suggested two different possible implementations, do you have an opinion on which of those would be better?
