### ISSUE TITLE
MacOS Mojave (V 10.14.1) Gradle 4.10.1 requires Java 7 or later to run. You are currently using Java 6.

### ISSUE THREAD

**Issue by asterixorobelix** [fastlane/fastlane#14135]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Error is that Gradle 4.10.1 requires Java 7 or later to run. Installing Java 7 results in a popup saying that Java command line tools are not installed. However, according to [this article](https://www.theitsage.com/fix-java-command-line-tool-popup-mac/) and [this article](https://java.com/en/download/faq/yosemite_java.xml) Java 6 is the latest version for Mac which includes command line tools. When I run fastlane with Java 6 I get the error. 

##### Command executed
bundle exec fastlane test

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[21:02:02]: ------------------------------
[21:02:02]: --- Step: default_platform ---
[21:02:02]: ------------------------------
[21:02:02]: Driving the lane 'android test' 🚀
[21:02:02]: --------------------
[21:02:02]: --- Step: gradle ---
[21:02:02]: --------------------
[21:02:02]: $ /Users/cobi/Documents/PersonalProjects/afrikaburn.kotlin/afrikaburn/gradlew test -p .
[21:02:03]: ▸ FAILURE: Build failed with an exception.
[21:02:03]: ▸ * What went wrong:
[21:02:03]: ▸ Gradle 4.10.1 requires Java 7 or later to run. You are currently using Java 6.
[21:02:03]: ▸ * Try:
[21:02:03]: ▸ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[21:02:03]: ▸ * Get more help at https://help.gradle.org
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android test |
+------------------+--------------+
[21:02:03]: Exit status of command '/Users/cobi/Documents/PersonalProjects/afrikaburn.kotlin/afrikaburn/gradlew test -p .' was 1 instead of 0.

FAILURE: Build failed with an exception.

* What went wrong:
Gradle 4.10.1 requires Java 7 or later to run. You are currently using Java 6.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | gradle           | 0           |
+------+------------------+-------------+

[21:02:03]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command '/Users/cobi/Documents/PersonalProjects/afrikaburn.kotlin/afrikaburn/gradlew test -p .' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

FAILURE: Build failed with an exception.

* What went wrong:
Gradle 4.10.1 requires Java 7 or later to run. You are currently using Java 6.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/actions/gradle.rb:52:in `run'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:21:in `block (2 levels) in parsing_binding'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
	from /Users/cobi/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	from /Users/cobi/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/cobi/.fastlane/bin/bundle/bin/fastlane:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> [<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.1 (18B75)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease ")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("io.github.asterixorobelix.afrikaburn") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 1.0.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.5.0        |
| fastimage                 | 2.1.5        |
| addressable               | 2.6.0        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| multi_json                | 1.13.1       |
| jwt                       | 2.1.0        |
| os                        | 1.0.0        |
| psych                     | 2.0.8        |
| uber                      | 0.1.0        |
</details>

*generated on:* **2019-01-24**
</details> </pre>
</details>

**Comment by janpio** [comment]
Do you have Android Studio installed? Can you build with it?

**Comment by janpio** [comment]
The `gradle` action "just" uses the `gradlew` command line tool from Android and executes it, without any special parameter or anything: 

https://github.com/fastlane/fastlane/blob/b7be8b126f79152ea03e000496b1f7f21480952d/fastlane/lib/fastlane/actions/gradle.rb#L25-L32

https://github.com/fastlane/fastlane/blob/b7be8b126f79152ea03e000496b1f7f21480952d/fastlane/lib/fastlane/actions/gradle.rb#L44-L56

https://github.com/fastlane/fastlane/blob/b7be8b126f79152ea03e000496b1f7f21480952d/fastlane/lib/fastlane/helper/gradle_helper.rb#L28-L33

Which means that if you run `gradlew test -p .` in `/Users/cobi/Documents/PersonalProjects/afrikaburn.kotlin/afrikaburn/` you will get the same result unfortunately, which is completely out of control of Fastlane. This sounds more like a Android and Path problem.

Does running the command manually return the same error message as your initial issue here? If so, can you run `javac -version` and `which javac` for some more information?

**Comment by asterixorobelix** [comment]
@janpio gradle has not been added to my path variables (see output in command line below)
Last login: Fri Jan 25 15:54:05 on ttys000
Cobis-MacBook-Pro-2:afrikaburn cobi$ gradlew test -p
-bash: gradlew: command not found
Cobis-MacBook-Pro-2:afrikaburn cobi$ ./gradlew test -p

FAILURE: Build failed with an exception.

* What went wrong:
Gradle 4.10.1 requires Java 7 or later to run. You are currently using Java 6.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Cobis-MacBook-Pro-2:afrikaburn cobi$ gradle test
-bash: gradle: command not found

**Comment by asterixorobelix** [comment]
@janpio 

I can build and run in Android Studio by clicking the run button.

However, as [suggested here](https://stackoverflow.com/questions/27094492/how-to-run-gradle-from-the-command-line-on-mac-bash) I installed gradle via homebrew (`brew install gradle`) and java which was a requirement for the homebrew gradle install (`brew cask install java`)

**Comment by janpio** [comment]
Android Studio manages its own Gradle and Java it seems. And the homebrew version of gradle you installed seems to have these limitations with Java.

Sorry, I can't help you further here - I am on Windows where we have our own gradle problems, but they are different ;) Good luck!

**Comment by janpio** [comment]
Yeah, again the problem might be that Android Studio has its own Gradle - and you are running another one on the command line :/ If you get the same one running it manually, you might be able to post on Stackoverflow and get more Android developers looking at it.

**Comment by asterixorobelix** [comment]
I finally got this fixed, I will try detail the process in case others encounter the same issue. For some reason, the latest Java version (11.02) does not work properly with Gradle. Online research indicates that Java 8 works properly, and my error has disappeared with Java 8.

It appears that Android Studio has its own instance of Java, which fastlane does not have access to via the terminal. 
You therefore need to install Java via Homebrew in the terminal. Additionally, the Java version should be Java 8 and not Java 11, as mentioned [here](https://stackoverflow.com/questions/52689100/data-binding-with-kotlin-processdatabinding-unable-to-get-public-no-arg-constru) and [here](https://github.com/fastlane/fastlane/issues/12496)

In order to do this via Homebrew,  now that Java 8 is no longer the most current version [as discussed here](https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac)

`brew tap caskroom/versions`
`brew cask install java8`

The terminal command: `javac -version` should now return `javac 1.8.0_202-ea` 

If this is not the case, your JAVA_HOME environment variable likely refers to a more recent version of Java. Identify the path on disc of your java 8 jdk (it will be something like: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home) this location should contain a folder called `bin` with a number of java binaries inside. Use the `export JAVA_HOME=example/path/to/java` to update environment variable. An example might be: `export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home`

Another alternative might be to uninstall all java instances via Homebrew with `brew cask uninstall java` and then install java 8 with Homebrew with `brew cask install java8`

Finally, bask in the glory of your success!

**Comment by asterixorobelix** [comment]
Basically, in summary - Android Studio seems to maintain its own instances of Gradle and Java, so for fastlane to work:
* Install your own version of Gradle via Homebrew for the terminal
* Install your own version of Java 8 via Homebrew for the terminal

`bundle exec fastlane test` should now succeed

**Comment by janpio** [comment]
Should we maybe add that to the `gradle` documentation?

**Comment by svanzoest** [comment]
Just FYI, these are my instructions for setting up Android on MacOS. Feel free to use however you want.

### Install Java JRE 8

Look for the latest in the [Java SE 8](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)

- [jre-8u172-macosx-x64.dmg](http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jre-8u172-macosx-x64.dmg)

Easiest way to install this is via Homebrew.

```bash
# http://davidcai.github.io/blog/posts/install-multiple-jdk-on-mac/
brew update
brew tap caskroom/cask
brew tap caskroom/versions
# brew cask info java8
brew cask install java8
```

### Install Android Studio (or the SDK tools package)

Download the latest version of [Android Studio](https://developer.android.com/studio/) or the SDK tools package if you don't need to full blown IDE.
Easiest way to install this is via Homebrew.

```bash
brew cask install android-studio
brew cask install android-sdk
brew cask install intel-haxm
```

For just the SDK tools use

```bash
brew cask install android-sdk
```

This installs the sdk tools in `/usr/local/share/android-sdk`

## Configure and setup the Android SDK

With the above SDK tools installed (either standalone or via Android Studio), you can now run `sdkmanager` to install the needed SDK components.

Install the Android SDK, see [Android Studio: CLI tools](https://developer.android.com/studio/command-line/index.html)

```bash
# create empty file to supress warning
mkdir ~/.android && touch ~/.android/repositories.cfg

export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-27" "sources;android-27"
sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools"
sdkmanager --sdk_root=$ANDROID_SDK_ROOT "build-tools;27.0.3"
sdkmanager --sdk_root=$ANDROID_SDK_ROOT "emulator" 
sdkmanager --sdk_root=$ANDROID_SDK_ROOT "system-images;android-27;google_apis;x86" "system-images;android-27;google_apis_playstore;x86"
```

This will build against the latest target API, which in this case is API 27.
The minimal SDK version is determined by the [Android Manifest](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html) file (and of course the minimum plugin requirements) which can be found in [cordova-android](https://github.com/apache/cordova-android/blob/7.1.0/bin/templates/project/AndroidManifest.xml#L48) and currently is 19 (Android 4.4 KitKat) which [supports 94.3% of the Google Play Store devices](https://developer.android.com/about/dashboards/index.html#Platform)

## Install Gradle

Gradle is the new Android build tool that has replaced `ant`. To install gradle use homebrew:

`brew install gradle` 

## Setup an Android Emulator

If you are running an old (v25) version, look at [update your path for the new android emulator location](https://www.stkent.com/2017/08/10/update-your-path-for-the-new-android-emulator-location.html)

```bash
sdkmanager "system-images;android-27;google_apis;x86"
avdmanager create avd -n x86 -d pixel_xl -c "100M" -k "system-images;android-27;google_apis;x86"
```

**Comment by asterixorobelix** [comment]
Thanks @janpio @svanzoest I'll make a PR this weekend.

I'm wondering if you could help me with something else. I can now run `fastlane test` in my repo and fastlane successfully makes a build. However, I'm struggling to find where on disc the resulting apk can be found. Since its a separate Gradle instance to Android Studio, it doesnt put the apk in the usual android studio location. It might be nice if the terminal output mentioned where the apk output can be found.

I've tried googling how to change or identify the gradle build location from the terminal but havent found much. Any ideas?

**Comment by janpio** [comment]
We just output what gradle outputs - so wen don't _really_ know what it is doing. So if gradle doesn't output the path, we have no real access to it. Sorry :/

**Comment by asterixorobelix** [comment]
How does one specify the path to the key store and key store password + key password for android apk signing? Does this info go into the Appfile?

**Comment by janpio** [comment]
Create a new issue for this new question please.
