### ISSUE TITLE
Mailgun permission error 

### ISSUE THREAD

**Issue by chetan-arvindinternet** [fastlane/fastlane#14130]
###  You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
+------------------+----------+
<<attached [image>>-](url) [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines]

<img width="822" alt="screenshot 2019-01-24 at 13 44 59" src="https://user-images.githubusercontent.com/42667971/51664090-9258ba80-1fde-11e9-9fa7-b20912fd5334.png">

(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by janpio** [comment]
Please open a new issue with the bug report template and include all the data it asks for: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md
Thanks 🚀
