### ISSUE TITLE
p12 format issue, security: security: SecKeychainItemImport: Unknown format in import.

### ISSUE THREAD

**Issue by krish722** [fastlane/fastlane#14136]
### New Issue Checklist

fastlane 2.114.0
 
## Issue Description

There is a issue created but it was closed for either for creating own keychain / failure in keychain

I have done complete exploration of the bug.

The command which failes
`security import AAAAAAAA.p12  -P '' -k '/----------Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security`

if the same file is rename to p12 to pem/key it works perfectly.

This particular certSigningRequest is from a system which always have this issue, when we do it from other system i don't have the same problem. 

##### Command executed

`security import AAAAAAAA.p12  -P '' -k '/----------Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security`

 
if i run the same file after renaming to .key it works perfectly.
`security import AAAAAAAA.key  -P '' -k '/----------Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security`

### Problem

1. security import always take file format by following the extension.
2, p12 is always RSA in the Public-Key Cryptography Standards
3. key - plain file, is the private key file.
4. pem - is also plain file key but for used for public

Most of the files go through p12 , but from one system only i have problem as of now

I can create a Pull request can you guys please have a look.

**Comment by janpio** [comment]
Umm, what fastlane action or command are you talking about? I am missing a bit of context here to understand :/ But if you know how to fix your problem, of course go ahead and create a PR so we can look at the code!
