### ISSUE TITLE
Ability to change success text for build upload

### ISSUE THREAD

**Issue by zakhej** [fastlane/fastlane#14147]
#### Motivation Behind Feature
Current text is "Uploading the build to Crashlytics Beta. Time for some ☕️." and it's hardcoded. Sometimes build uploads quickly and you have no time for tea, somebody may not like tea and so on.

#### Feature Description
It would be great to make this line changeable from Fastfile.

**Comment by janpio** [comment]
Hm, we are always open for feature requests and most importantly pull requests that implement these feature requests. But to be honest, I am not sure if the added code is worth the benefit here 🙈
