### ISSUE TITLE
Gradle action not working on iOS

### ISSUE THREAD

**Issue by AndreyNikiforov** [fastlane/fastlane#1414]
Adding Android compilation to my React Native (RN) project. Fastlane gradle action fails:

Action 'gradle' doesn't support required operating system 'ios'

fl 0.61.0

Am I missing anything or gradle does not work on ios for some reason?

**Comment by asfalcone** [comment]
Hi @AndreyNikiforov The `gradle` action is currently specified for android only here: https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/gradle.rb#L94

If you want to build and run from source (check out [countdown](/fastlane/countdown)) and change that behavior to see if you can get gradle working for RN, we'd be happy to review a PR that allows it work for iOS as well!

**Comment by AndreyNikiforov** [comment]
i just used `sh 'cd ../android && ./gradlew assembleRelease --info'`

**Comment by asfalcone** [comment]
:+1: I'm going to close this issue since you've got a solution that works!

**Comment by AndreyNikiforov** [comment]
I am wondering if I am not using concept of 'platform' from fastlane correctly OR this concept does not work well for React Native. I want to compile both Android & iOS and then deploy if both compilations are successful.
