### ISSUE TITLE
slack message escaping not respected

### ISSUE THREAD

**Issue by youngpayters** [fastlane/fastlane#14141]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Newline escaping in slack message is not respected in slack and appear as `\n`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :beta do
    add_badge(dark: true)
    build
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(message: "New Beta client released to TestFlight\nVersion: #{ENV['APP_VERSION']}\n"
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS Settings
# Not relevant

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| faraday_middleware        | 0.13.0       |
| bundler                   | 2.0.1        |
| unicode-display_width     | 1.4.1        |
| addressable               | 2.6.0        |
| psych                     | 2.0.17       |
| curb                      | 0.9.7        |
| badge                     | 0.10.0       |
| fastlane-plugin-badge     | 1.2.0        |
</details>

*generated on:* **2019-01-25**
</details></pre>
</details>

**Comment by janpio** [comment]
Surface the code that is causing the problem from the `Fastfile`:
```
slack(message: "New Beta client released to TestFlight\nVersion: #{ENV['APP_VERSION']}\n"
```

**Comment by youngpayters** [comment]
Can also be reproduced with cli run:

```
fastlane run slack message:"Testing fastlane\nVersion: 1.2.3" channel:"#general" slack_url:"https://hooks.slack.com/services/redacted" --capture_output
```
<img width="290" alt="screen shot 2019-01-25 at 16 14 14" src="https://user-images.githubusercontent.com/917711/51757828-5136d800-20bc-11e9-8ae8-7bb26198cd8f.png">

**Comment by janpio** [comment]
Let's see if someone wants to work on that, shouldn't be too hard.

**Comment by albertbass86** [comment]
Hi I have only experience as a Fastlane user but I would love to try and contribute with something. This looks like a good candidate.

**Comment by janpio** [comment]
Go for it! If you have any questions, just reply to this issue and I will try to help.

**Comment by albertbass86** [comment]
Hi @janpio first thanks for the trust and in advance for the help. I did not want to bother but I have been working on the issue and believe I have solved it.

However when preparing for the PR and trying to execute all the rspec tests I am finding the 'scan' specific tests are failing.

Here is what I see when running the first spec:

```
Failures:

  1) Scan Scan::DetectValues Xcode config handling fetches the path from the Xcode config
     Failure/Error: Scan.config = FastlaneCore::Configuration.create(Scan::Options.available_options, options)
     
     FastlaneCore::Interface::FastlaneError:
       No simulators found on local machine
     # ./fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
     # ./fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
     # ./scan/lib/scan/detect_values.rb:116:in `block in detect_simulator'
     # ./scan/lib/scan/detect_values.rb:114:in `tap'
     # ./scan/lib/scan/detect_values.rb:114:in `detect_simulator'
     # ./scan/lib/scan/detect_values.rb:36:in `set_additional_default_values'
     # ./scan/lib/scan/module.rb:17:in `config='
     # ./scan/spec/detect_values_spec.rb:11:in `block (4 levels) in <top (required)>'

Finished in 6 minutes 43 seconds (files took 3.51 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./scan/spec/detect_values_spec.rb:15 # Scan Scan::DetectValues Xcode config handling fetches the path from the Xcode config
```

Inspecting further in detect_values_spec.rb I see on line 9 that #{ENV['USER']} in my case appears as nil but I cannot find anywhere in the repo or docs how am I supposed to have the variable set.

The lines in detect_values_spec.rb are the ones from master branch plus two because I had added pry.

Furthermore, the specific message `No simulators found on local machine` really bothers me as I have installed one. It seems clear something is wrong with my environment but I am not sure where to look at for insight.

Thank you!
