### ISSUE TITLE
How to set "Apple Generic Versioning" from Fastlane (without opening Xcode)

### ISSUE THREAD

**Issue by hydraSlav** [fastlane/fastlane#14143]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Setting "Apple Generic Versioning" through Fastlane

#### Question Description
I am building a Unity Xcode project. The Xcode project is generated from scratch every time Unity runs a build. 

In order to use Fastlane's increment_build_number action, the Xcode project must be configured to use "Apple Generic Versioning". Yes, I have read the document how to enable this through Xcode. However, I am building a CI system, so I cannot manually setup the Xcode project everytime.

Is there no way to set Xcode to use "Apple Generic Versioning" through some Fastlane action?

**Comment by hydraSlav** [comment]
Right now, my only option is to run sed or perl outside of fastlane. However fastlane already provides actions for things like enabling/disabling automatic signing, so why not this?

p.s. what's the best action to run perl from within a fastlane file?

**Comment by rajivshah3** [comment]
You can change the build settings using the `Xcodeproj` module. We do this in our app to manually change the signing settings: https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/ios/fastlane/Fastfile#L12. In this case, you could try:
```ruby
item.build_settings['VERSIONING_SYSTEM'] = "Apple Generic"
```

To get the name that the `Xcodeproj` module will use, go to the Build Settings tab and then go to Editor > Show Setting Names. That will change the titles to their actual names, e.g. `Versioning System` -> `VERSIONING_SYSTEM`

**Comment by hydraSlav** [comment]
> You can change the build settings using the `Xcodeproj` module.

That is very helpful!

How can I make sure Xcodeproj module (from what I understand, it's a Ruby library, rather than Fastlane) remains uptodate when Xcode version changes?
