### ISSUE TITLE
Precheck complains about Google in keywords

### ISSUE THREAD

**Issue by marcinolawski** [fastlane/fastlane#14148]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The precheck complains when the keywords.txt contains text like google, example:

`röst,dyslexi,google`

Writing about other platforms is prohibited in the description of the app, not in keywords.

##### Command executed
`fastlane deliver`

##### Complete output when running fastlane, including the stack trace and command used

[15:04:34]:   Failed: No mentioning  competitors-> mentioning other platforms, like Android or Blackberry

|          Potential problems          |
+---------------------+----------------+
| Field               | Failure reason |
+---------------------+----------------+
| keywords: (pt-BR)   | found: google  |
| keywords: (zh-Hans) | found: google  |
| keywords: (sv)      | found: google  |

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.115.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 3.0.0        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.2.7        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.15.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.10       |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 2.1.0        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 1.0.0        |
| plist                     | 3.4.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| uber                      | 0.1.0        |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.5      |
| unicode-display_width     | 1.4.0        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.7.0        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-01-28**
</details>

**Comment by janpio** [comment]
Can you provide a link to some documentation on that?

**Comment by marcinolawski** [comment]
[https://developer.apple.com/app-store/review/guidelines/](url), the only restrictions on keywords are described in point 2.3.7. The point says nothing about  competitors.
Anyway, thinking logically, keywords are invisible to the App Store users. Even if I write in the keywords 'I love Google, I hate Apple' nobody will see it.

**Comment by janpio** [comment]
For some historical context, see https://github.com/fastlane/fastlane/pull/13754

**Comment by marcinolawski** [comment]
This pull request explains a bit where the problem came from. But in my opinion problem from this issue can be solved much easier. Checking the keywords for `OtherPlatformsRule` is not justified either in logic or in the App Store Review Guidelines. For this reason this check can be safely removed.

**Comment by marcinolawski** [comment]
I can report something better. In the App Annie portal (I'm not related to them) you can see what keywords are used by apps. Look for 'google' [(https://www.appannie.com/intelligence/marketing/aso/ios/keyword-top/?country=US&device=iphone&date=2019-01-28&word=google),](url) you'll find over 250 apps that use this keyword. Some of the apps are from Google, but not all of them.
In addition, I've argued with Apple many times. Always when they block the app, they refer to the 'App Store Review Guidelines', always! If something is not prohibited there, it is allowed.

**Comment by janpio** [comment]
I am not disagreeing with you, I am just collecting all the relevant information.

> Always when they block the app, they refer to the 'App Store Review Guidelines', always! If something is not prohibited there, it is allowed.

Ok, can you refer me to the section in the App Store Review Guidelines that defines the prohibition to use references to competitors like Android?

**Comment by marcinolawski** [comment]
Yes:

> 2.3.10 Make sure your app is focused on the iOS, Mac, Apple TV or Apple Watch experience, and don’t include names, icons, or imagery of other mobile platforms in your app or metadata, unless there is specific, approved interactive functionality.

The point clearly speaks of **mobile platforms**, not companies as such.

**Comment by marcinolawski** [comment]
OK, I did a quick research and everything cleared up. In 2016 there was such a point:

> 3.1 Apps or metadata that mentions the name of any other mobile platform will be rejected

The point disappeared somewhere between 2016 and 2019, no matter when, it is gone now.
