### ISSUE TITLE
"Can't find class 'adhoc' when generating new profiles with match

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#14152]
My version of Fastlane is 2.115.0.

When generating the new profiles with match, I am getting the error "Can't find class 'adhoc".

I saw couple of closed issue where it was mentioned that the issue was resolved in 2.112.0

My fastlane is upto date and still facing this issue.

**Comment by santoshshetty2612** [comment]
Hi

Any help on this?

**Comment by ricsantos** [comment]
Have you tried updating to fastlane 2.116.0? This fixed the issue for me.

**Comment by jvervier** [comment]
Update solved our issues too

**Comment by santoshshetty2612** [comment]
@ricsantos @jvervier  Thanks it worked.
