### ISSUE TITLE
Resigning an app-store IPA for enterprise

### ISSUE THREAD

**Issue by MattCheetham** [fastlane/fastlane#14158]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Resign

No

No

#### Question Description
What I am trying to do is make one build of my app, using the app store identities/credentials and then after that IPA is created, re-sign that IPA with my enterprise account certificates. This way I can upload to testflight but also distribute an enterprise version internally.

As it stands, I have a workflow (in bitrise) where I create my IPA with app store settings, push it up to App Store Connect fine, then run a fastlane lane which resigns the app using my enterprise account. Now, obviously due to the enterprise account needing to use a different bundle ID, I am editing the bundle ID in the resign.  So where my app is originally built as "com.app.identifier", I resign it as "com.app.identifier.enterprise" So, my resign flow is:

```
default_platform(:ios)

platform :ios do
  desc "Resigns the App Store build with the enterprise account details"
  lane :enterpriseResign do
    resign(
  	ipa: "app.ipa",
  	signing_identity: "iPhone Distribution: xxx LTD",
  	provisioning_profile: {
    		"com.app.identifier.enterprise" => "APP_Enterprise_In_House.mobileprovision"
  	},
	bundle_id: "com.app.identifier.enterprise",
	use_app_entitlements: true
)
  end
end
```

The command runs fine, the app is resigned and I can install it on to a device. I have to accept the profile in the device settings as expected but on launch, the app crashes. The console is giving me barely anything other than telling me that the process exited. I have tried using `use_app_entitlements` as true and false and nothing seems to help.

I have tried everything I can think of, and I am starting to wonder if it's actually a security feature that prevents IPAs signed for App Store being re-signed for enterprise. 

Any input would be greatly appreciated.

N.B. I also exported an enterprise build from xcode manually, then compared that to my build that i had re-signed. The entitlements, identities etc all look identical. Only difference was that one app was 11mb (The manual export) which installs and then the app store export that was re-signed was 150mb. Assuming thats an architecture/bitcode/dysm thing though.

**Comment by MattCheetham** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Resigns the App Store build with the enterprise account details"
  lane :enterpriseResign do
    resign(
  	ipa: "app.ipa",
  	signing_identity: "iPhone Distribution: xxx LTD",
  	provisioning_profile: {
    		"com.app.identifier.enterprise" => "APP_Enterprise_In_House.mobileprovision"
  	},
	bundle_id: "com.app.identifier.enterprise",
	use_app_entitlements: true
)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.115.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 1.0.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.5.0        |
| fastimage                 | 2.1.5        |
| addressable               | 2.6.0        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| multi_json                | 1.13.1       |
| jwt                       | 2.1.0        |
| os                        | 1.0.0        |
| psych                     | 2.0.8        |
| uber                      | 0.1.0        |
</details>


*generated on:* **2019-01-30**
</details>

**Comment by mgrebenets** [comment]
@MattCheetham 

It may not be clear from the `sigh resign` help or the action doco, but the the expected provisioning profile mapping is:

**OLD**_BUNDLE_ID => **New** provisioning profile

Resign will figure out new bundle ID(s) from the provisioning profile(s).

And I'd recommend _not_ to use `bundle_id`, I personally think it should be removed.
This argument only works when there is no nested apps or app extensions.

**Comment by MattCheetham** [comment]
@mgrebenets Thank you, this is all really helpful. I will have another go at it soon and see if I can get it to work. In the example you give, with the workaround. Is that a use case where you are successfully resigning an app store build for enterprise?

**Comment by mgrebenets** [comment]
We have been resigning Enterprise to AppStore, mostly cause it’s how it has been set up for years and there’s no time and big wins in it to change it to be the other way around.

**Comment by MattCheetham** [comment]
@mgrebenets Great. I just need confirmation that someone was doing it successfully! Also, the `.xcarchive` has a `embedded.mobileprovision`. I'm assuming that's replaced and taken care of by the resign.

**Comment by mgrebenets** [comment]
@MattCheetham 
The resign scripts in fastlane depend on the folder layout, e.g. it has to be `Payload/MyApp.app`.
IIRC even apple tools want that kind of layout

So what we do is zip the .app into .ipa and then resign .ipa.

This is a Ruby helper that we use to convert .app to .zip, it's self-contained and doesn't depend on anything extra.

```ruby
      # Creates .ipa zip archive for .app at given path and returns .ipa path.
      def self.app_to_ipa(app_path)
        UI.message("Converting #{File.basename(app_path).yellow} to .ipa")
        tmp_dir = Dir.mktmpdir
        payload_dir = File.join(tmp_dir, "Payload")
        FileUtils.mkdir_p(payload_dir)
        FileUtils.cp_r(app_path, "#{payload_dir}/")

        ipa_path = File.join(tmp_dir, basename(app_path)) + ".ipa"
        cmd = [
          "pushd #{tmp_dir} 1>/dev/null",
          "zip -qry #{ipa_path.shellescape} Payload",
          "popd 1>/dev/null"
        ].join(" && ")
        sh(cmd)

        FileUtils.rm_rf(payload_dir)
        ipa_path # Return
      end
```

then we got the helper that does the opposite (.ipa to .app)

```ruby
      # Unzips .ipa and returns .app path.
      def self.ipa_to_app(ipa_path)
        UI.message("Converting #{File.basename(ipa_path).green} to .app")
        tmp_dir = Dir.mktmpdir
        UI.message("Converting #{ipa_path.yellow} to .app")
        sh("unzip -q #{ipa_path.shellescape} -d #{tmp_dir}")
        app_path = find_app_path_in_ipa(ipa_path)
        File.join(tmp_dir, app_path)
      end
```

the code for resigning archive is along these lines:

```ruby
            app_path = File.join(package, "Products", "Applications", basename(package)) + ".app"
            result = resign_ipa(app_to_ipa(app_path), params)
            new_app_path = ipa_to_app(result[:path])

            # Overwrite .app inside archive
            FileUtils.rm_rf(app_path)
            FileUtils.mv(new_app_path, app_path)
```

`resign_ipa` is something is what is currently heavily customized for our setup, but it calls `fastlane sigh resign` in the end with the correct signing identity and profiles.

After this we run the code that patches `Info.plist` in the archive and then `xcodebuild -exportArchive`.

The `embedded.mobileprovision` that you mention is inside the `.app`, right? (it should be).
If so the `sigh resign` will take care of updating it during resigning.
