### ISSUE TITLE
fastlane init for Android is borked

### ISSUE THREAD

**Issue by lukepighetti** [fastlane/fastlane#14151]
`fastlane init` in a Flutter project `android` directory produces this error.

I installed fastlane with `brew cask install fastlane` following these instructions. https://flutter.io/docs/deployment/fastlane-cd

I know nothing about Ruby.

```
Using addressable 2.6.0
Using commander-fastlane 4.4.6
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```
```
To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/lukepighetti/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

```
```

An error occurred while installing unf_ext (0.0.7.5), and Bundler
cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.5'` succeeds before bundling.
[21:35:35]: Exit status: 5
[21:35:35]: Something went wrong when running `bundle update` for you
[21:35:35]: Please take a look at your Gemfile at path `Gemfile`
[21:35:35]: and make sure you can run `bundle update` on your machine.
```

**Comment by FireZenk** [comment]
Same here (but with a standard Android project): 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 10.14.3                                             |
| Ruby                        | 2.2.4                                               |
| Bundler?                    | false                                               |
| Git                         | git version 2.7.4 (Apple Git-66)                    |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                 |
| Host                        | Mac OS X 10.14.3 (18D109)                           |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                          |
| Is contained                | true                                                |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | ~/../../Applications/Xcode7.app/Contents/Developer/ |
| Xcode Version               | 7.3.1                                               |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.16.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.8.0        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2019-02-18**
</details>

And the `--verbose`:

```
DEBUG [2019-02-18 11:41:28.03]: Checking if there are any plugins that should be loaded...
ERROR [2019-02-18 11:41:28.87]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
ERROR [2019-02-18 11:41:28.87]: Please `cd` into the directory of the intended Xcode project you wish to use.
/Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again (FastlaneCore::Interface::FastlaneError)
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/setup/setup.rb:93:in `start'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by janpio** [comment]
Hi @FireZenk, your problem looks very different. Can you please open a new bug report issue and include all the information it asks for? Thanks.

**Comment by FireZenk** [comment]
Dona @janpio https://github.com/fastlane/fastlane/issues/14261 thank you

**Comment by lukepighetti** [comment]
Sorry everyone, I hung up fastlane for the time being due to this bug. Will update this thread when I have more time.

**Comment by lukepighetti** [comment]
Hey everyone, I'm going to close this. Will reopen if I run into it again next time I try out Fastlane.
