### ISSUE TITLE
Failing HockeyApp action

### ISSUE THREAD

**Issue by AndreyNikiforov** [fastlane/fastlane#1415]
In my Hockey app action started receiving the following error:

/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate krausefx-shenzhen-0.14.7, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)

Does not seem like related to any of code changes, but may be env change at hosting CI provider (e.g. FL upgrade etc).

Error appears on FL 0.61.0

Any help is appreciated.

**Comment by KrauseFx** [comment]
Can you try running `[sudo] gem cleanup`?

**Comment by AndreyNikiforov** [comment]
neither `gem cleanup` nor updating FL to 0.63.1 helped

**Comment by AndreyNikiforov** [comment]
tried `sudo gem install plist --version "=3.1.0"` followed by `sudo gem install plist --version "=3.2.0"` (without `gem cleanup`) and got same error.

I don't know ruby ecosystem to identify cause of the issue.

**Comment by AndreyNikiforov** [comment]
found workaround (sequence):
- `sudo gem install plist --version "=3.1.0"`
- `sudo gem uninstall plist --version "=3.2.0" --executables`
