### ISSUE TITLE
Match creates new provisioning profiles every time, appending timestamp to profile name

### ISSUE THREAD

**Issue by JanBrinker** [fastlane/fastlane#14157]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) (I found some, but none solved my problem)

### Issue Description
Ever since sometime November or December last year my team is having issues with match. When we run our lane so create new provisioning profiles we get the following warnings: 

```
[13:41:55]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[13:41:57]: The name 'match AdHoc com.acme.myapp.prod.adhoc' is already taken, using another one.
[13:41:57]: Creating new provisioning profile for 'com.acme.myapp.Prod.adhoc' with name 'match AdHoc com.acme.myapp.Prod.adhoc 1548765717' for 'ios' platform
```

For some reason our setup worked before and then started to behave like this after we had to use a new Apple ID for our team as a code signing identity. Sometimes match was able to create the profile with the correct name, sometimes it used a timestamp at the end. I was not able to find a pattern here so far.

I was able to get rid of this issue by using `force: true` in my match call for all other bundle IDs (we use different bundle IDs for dev, stage and prod and prod_adhoc [for testers who need access to live data]). However for this single bundle ID the issues remain. Any ideas what's the issue?

##### Command executed
    match(
        type: "adhoc",
        app_identifier: "com.acme.myapp.Prod.adhoc",
        force_for_new_devices: true,
        force: force,
        keychain_password: keychain_password
    )

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
wookieebook:MyApp jan$ bundle exec fastlane register_devices_generate_certificates
[✔] 🚀 
+---------------------------+---------+------------------+
|                      Used plugins                      |
+---------------------------+---------+------------------+
| Plugin                    | Version | Action           |
+---------------------------+---------+------------------+
| fastlane-plugin-appcenter | 0.1.7   | appcenter_upload |
| fastlane-plugin-badge     | 1.0.0   | add_badge        |
+---------------------------+---------+------------------+

[14:28:24]: ----------------------------------------
[14:28:24]: --- Step: Verifying fastlane version ---
[14:28:24]: ----------------------------------------
[14:28:24]: Your fastlane version 2.115.0 matches the minimum requirement of 2.115.0  ✅
[14:28:24]: ------------------------------
[14:28:24]: --- Step: default_platform ---
[14:28:24]: ------------------------------
[14:28:24]: Driving the lane 'ios register_devices_generate_certificates' 🚀
[14:28:24]: Loading secrets
[14:28:24]: --------------------
[14:28:24]: --- Step: prompt ---
[14:28:24]: --------------------
[14:28:24]: Please enter your keychain password: 
[14:28:32]: ------------------------------
[14:28:32]: --- Step: register_devices ---
[14:28:32]: ------------------------------
[14:28:34]: Fetching list of currently registered devices...
[14:28:39]: Successfully registered new devices.
[14:28:39]: -------------------
[14:28:39]: --- Step: match ---
[14:28:39]: -------------------
WARNING: You are running Ruby 2.2.4, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
[14:28:39]: Successfully loaded '/Users/jan/Documents/Dev/ACME/MyApp/fastlane/Matchfile' 📄

+---------+------------------------------------------------+
|       Detected Values from './fastlane/Matchfile'        |
+---------+------------------------------------------------+
| git_url | git@github.com:acme/myapp-secrets  |
|         | .git                                           |
+---------+------------------------------------------------+

+-----------------------+------------------------------------------------+
|                       Summary for match 2.115.0                        |
+-----------------------+------------------------------------------------+
| type                  | development                                    |
| app_identifier        | ["com.acme.myapp.Dev"]                  |
| force_for_new_devices | true                                           |
| force                 | true                                           |
| keychain_password     | ********                                       |
| readonly              | false                                          |
| username              | asdf@acme.com                      |
| team_id               | ouruserid                                     |
| storage_mode          | git                                            |
| git_url               | git@github.com:acme/myapp-secrets  |
|                       | .git                                           |
| git_branch            | master                                         |
| shallow_clone         | false                                          |
| clone_branch_directly | false                                          |
| keychain_name         | login.keychain                                 |
| skip_confirmation     | false                                          |
| skip_docs             | false                                          |
| platform              | ios                                            |
| verbose               | false                                          |
+-----------------------+------------------------------------------------+

[14:28:39]: Cloning remote git repo...
[14:28:39]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:28:44]: 🔓  Successfully decrypted certificates repo
[14:28:44]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:28:46]: Installing certificate...
security: SecKeychainItemImport: The specified item already exists in the keychain.
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 

+-------------------+-----------------------------------------------+
|                       Installed Certificate                       |
+-------------------+-----------------------------------------------+
| User ID           | M6LUPT3BC4                                    |
| Common Name       | iPhone Developer: Our Team User (team user id) |
| Organisation Unit | ouruserid                                    |
| Organisation      | ACME inc   |
| Country           | US                                            |
| Start Datetime    | 2018-12-10 15:44:26 UTC                       |
| End Datetime      | 2019-12-10 15:44:26 UTC                       |
+-------------------+-----------------------------------------------+

+-------------------------------------+---------------------------------------------+
|                             Summary for sigh 2.115.0                              |
+-------------------------------------+---------------------------------------------+
| app_identifier                      | com.acme.myapp.Dev                   |
| username                            | asdf@acme.com                   |
| force                               | true                                        |
| cert_id                             | cert id                                  |
| provisioning_name                   | match Development com.acme.myapp.Dev |
| ignore_profiles_with_different_name | true                                        |
| team_id                             | ouruserid                                  |
| platform                            | ios                                         |
| development                         | true                                        |
| adhoc                               | false                                       |
| developer_id                        | false                                       |
| skip_install                        | false                                       |
| skip_fetch_profiles                 | false                                       |
| skip_certificate_verification       | false                                       |
| readonly                            | false                                       |
+-------------------------------------+---------------------------------------------+

[14:29:51]: Starting login with user 'asdf@acme.com'
[14:29:52]: Successfully logged in
[14:29:52]: Fetching profiles...
[14:29:54]: Verifying certificates...
[14:29:55]: Found 1 matching profile(s)
[14:29:55]: Recreating the profile
[14:29:59]: Creating new provisioning profile for 'com.acme.myapp.Dev' with name 'match Development com.acme.myapp.Dev' for 'ios' platform
[14:30:01]: Downloading provisioning profile...
[14:30:02]: Successfully downloaded provisioning profile...
[14:30:02]: Installing provisioning profile...
/var/folders/09/t5skpwbj0_98fyt0gyjln0940000gn/T/d20190129-15957-1ydk27i/profiles/development/Development_com.acme.myapp.Dev.mobileprovision
[14:30:02]: Installing provisioning profile...
[14:30:03]: 🔒  Successfully encrypted certificates repo
[14:30:03]: Pushing changes to remote git repo...
[14:30:17]: Finished uploading files to Git Repo [git@github.com:acme/myapp-secrets.git]

+---------------------+-------------------------------+-------------------------------+
|                           Installed Provisioning Profile                            |
+---------------------+-------------------------------+-------------------------------+
| Parameter           | Environment Variable          | Value                         |
+---------------------+-------------------------------+-------------------------------+
| App Identifier      |                               | com.acme.myapp.Dev     |
| Type                |                               | development                   |
| Platform            |                               | ios                           |
| Profile UUID        | sigh_com.acme.myapp.D  | 628117e0-6dbc-4b8a-a9b5-2240  |
|                     | ev_development                | 630164b2                      |
| Profile Name        | sigh_com.acme.myapp.D  | match Development             |
|                     | ev_development_profile-name   | com.acme.myapp.Dev     |
| Profile Path        | sigh_com.acme.myapp.D  | /Users/jan/Library/MobileDev  |
|                     | ev_development_profile-path   | ice/Provisioning              |
|                     |                               | Profiles/628117e0-6dbc-4b8a-  |
|                     |                               | a9b5-2240630164b2.mobileprov  |
|                     |                               | ision                         |
| Development Team ID | sigh_com.acme.myapp.D  | ouruserid                    |
|                     | ev_development_team-id        |                               |
+---------------------+-------------------------------+-------------------------------+

[14:30:17]: All required keys, certificates and provisioning profiles are installed 🙌
[14:30:17]: Setting Provisioning Profile type to 'development'
[14:30:17]: -------------------
[14:30:17]: --- Step: match ---
[14:30:17]: -------------------
[14:30:17]: Successfully loaded '/Users/jan/Documents/Dev/ACME/MyApp/fastlane/Matchfile' 📄

+---------+------------------------------------------------+
|       Detected Values from './fastlane/Matchfile'        |
+---------+------------------------------------------------+
| git_url | git@github.com:acme/myapp-secrets  |
|         | .git                                           |
+---------+------------------------------------------------+

+-----------------------+------------------------------------------------+
|                       Summary for match 2.115.0                        |
+-----------------------+------------------------------------------------+
| type                  | adhoc                                          |
| app_identifier        | ["com.acme.myapp.Stage"]                |
| force_for_new_devices | true                                           |
| force                 | true                                           |
| keychain_password     | ********                                       |
| readonly              | false                                          |
| username              | asdf@acme.com                      |
| team_id               | ouruserid                                     |
| storage_mode          | git                                            |
| git_url               | git@github.com:acme/myapp-secrets  |
|                       | .git                                           |
| git_branch            | master                                         |
| shallow_clone         | false                                          |
| clone_branch_directly | false                                          |
| keychain_name         | login.keychain                                 |
| skip_confirmation     | false                                          |
| skip_docs             | false                                          |
| platform              | ios                                            |
| verbose               | false                                          |
+-----------------------+------------------------------------------------+

[14:30:17]: Cloning remote git repo...
[14:30:17]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:30:26]: 🔓  Successfully decrypted certificates repo
[14:30:26]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:30:30]: Installing certificate...
security: SecKeychainItemImport: The specified item already exists in the keychain.
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 

+-------------------+-------------------------------------------------------------------------------+
|                                       Installed Certificate                                       |
+-------------------+-------------------------------------------------------------------------------+
| User ID           | ouruserid                                                                    |
| Common Name       | iPhone Distribution: ACME inc (ouruserid) |
| Organisation Unit | ouruserid                                                                    |
| Organisation      | ACME inc                                   |
| Country           | US                                                                            |
| Start Datetime    | 2018-12-10 15:45:22 UTC                                                       |
| End Datetime      | 2019-12-10 15:45:22 UTC                                                       |
+-------------------+-------------------------------------------------------------------------------+

+-------------------------------------+-----------------------------------------+
|                           Summary for sigh 2.115.0                            |
+-------------------------------------+-----------------------------------------+
| app_identifier                      | com.acme.myapp.Stage             |
| username                            | asdf@acme.com               |
| force                               | true                                    |
| cert_id                             | cert id                              |
| provisioning_name                   | match AdHoc com.acme.myapp.Stage |
| ignore_profiles_with_different_name | true                                    |
| team_id                             | ouruserid                              |
| platform                            | ios                                     |
| adhoc                               | true                                    |
| developer_id                        | false                                   |
| development                         | false                                   |
| skip_install                        | false                                   |
| skip_fetch_profiles                 | false                                   |
| skip_certificate_verification       | false                                   |
| readonly                            | false                                   |
+-------------------------------------+-----------------------------------------+

[14:31:33]: Starting login with user 'asdf@acme.com'
[14:31:36]: Successfully logged in
[14:31:36]: Fetching profiles...
[14:31:37]: Verifying certificates...
[14:31:39]: Found 1 matching profile(s)
[14:31:39]: Recreating the profile
[14:31:43]: Creating new provisioning profile for 'com.acme.myapp.Stage' with name 'match AdHoc com.acme.myapp.Stage' for 'ios' platform
[14:31:45]: Downloading provisioning profile...
[14:31:45]: Successfully downloaded provisioning profile...
[14:31:45]: Installing provisioning profile...
/var/folders/09/t5skpwbj0_98fyt0gyjln0940000gn/T/d20190129-15957-ahv2cw/profiles/adhoc/AdHoc_com.acme.myapp.Stage.mobileprovision
[14:31:46]: Installing provisioning profile...
[14:31:47]: 🔒  Successfully encrypted certificates repo
[14:31:47]: Pushing changes to remote git repo...
[14:31:53]: Finished uploading files to Git Repo [git@github.com:acme/myapp-secrets.git]

+---------------------+-------------------------------+-------------------------------+
|                           Installed Provisioning Profile                            |
+---------------------+-------------------------------+-------------------------------+
| Parameter           | Environment Variable          | Value                         |
+---------------------+-------------------------------+-------------------------------+
| App Identifier      |                               | com.acme.myapp.Stage   |
| Type                |                               | adhoc                         |
| Platform            |                               | ios                           |
| Profile UUID        | sigh_com.acme.myapp.S  | 33f007a4-8435-4702-9363-c5f2  |
|                     | tage_adhoc                    | 19c0adb8                      |
| Profile Name        | sigh_com.acme.myapp.S  | match AdHoc                   |
|                     | tage_adhoc_profile-name       | com.acme.myapp.Stage   |
| Profile Path        | sigh_com.acme.myapp.S  | /Users/jan/Library/MobileDev  |
|                     | tage_adhoc_profile-path       | ice/Provisioning              |
|                     |                               | Profiles/33f007a4-8435-4702-  |
|                     |                               | 9363-c5f219c0adb8.mobileprov  |
|                     |                               | ision                         |
| Development Team ID | sigh_com.acme.myapp.S  | ouruserid                    |
|                     | tage_adhoc_team-id            |                               |
+---------------------+-------------------------------+-------------------------------+

[14:31:53]: All required keys, certificates and provisioning profiles are installed 🙌
[14:31:53]: Setting Provisioning Profile type to 'ad-hoc'
[14:31:53]: -------------------
[14:31:53]: --- Step: match ---
[14:31:53]: -------------------
[14:31:53]: Successfully loaded '/Users/jan/Documents/Dev/ACME/MyApp/fastlane/Matchfile' 📄

+---------+------------------------------------------------+
|       Detected Values from './fastlane/Matchfile'        |
+---------+------------------------------------------------+
| git_url | git@github.com:acme/myapp-secrets  |
|         | .git                                           |
+---------+------------------------------------------------+

+-----------------------+------------------------------------------------+
|                       Summary for match 2.115.0                        |
+-----------------------+------------------------------------------------+
| type                  | adhoc                                          |
| app_identifier        | ["com.acme.myapp.Prod.adhoc"]           |
| force_for_new_devices | true                                           |
| force                 | true                                           |
| keychain_password     | ********                                       |
| readonly              | false                                          |
| username              | asdf@acme.com                      |
| team_id               | ouruserid                                     |
| storage_mode          | git                                            |
| git_url               | git@github.com:acme/myapp-secrets  |
|                       | .git                                           |
| git_branch            | master                                         |
| shallow_clone         | false                                          |
| clone_branch_directly | false                                          |
| keychain_name         | login.keychain                                 |
| skip_confirmation     | false                                          |
| skip_docs             | false                                          |
| platform              | ios                                            |
| verbose               | false                                          |
+-----------------------+------------------------------------------------+

[14:31:53]: Cloning remote git repo...
[14:31:53]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:32:06]: 🔓  Successfully decrypted certificates repo
[14:32:06]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:32:08]: Installing certificate...
security: SecKeychainItemImport: The specified item already exists in the keychain.
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 

+-------------------+-------------------------------------------------------------------------------+
|                                       Installed Certificate                                       |
+-------------------+-------------------------------------------------------------------------------+
| User ID           | ouruserid                                                                    |
| Common Name       | iPhone Distribution: ACME inc (ouruserid) |
| Organisation Unit | ouruserid                                                                    |
| Organisation      | ACME inc                                   |
| Country           | US                                                                            |
| Start Datetime    | 2018-12-10 15:45:22 UTC                                                       |
| End Datetime      | 2019-12-10 15:45:22 UTC                                                       |
+-------------------+-------------------------------------------------------------------------------+

+-------------------------------------+----------------------------------------------+
|                              Summary for sigh 2.115.0                              |
+-------------------------------------+----------------------------------------------+
| app_identifier                      | com.acme.myapp.Prod.adhoc             |
| username                            | asdf@acme.com                    |
| force                               | true                                         |
| cert_id                             | cert id                                   |
| provisioning_name                   | match AdHoc com.acme.myapp.Prod.adhoc |
| ignore_profiles_with_different_name | true                                         |
| team_id                             | ouruserid                                   |
| platform                            | ios                                          |
| adhoc                               | true                                         |
| developer_id                        | false                                        |
| development                         | false                                        |
| skip_install                        | false                                        |
| skip_fetch_profiles                 | false                                        |
| skip_certificate_verification       | false                                        |
| readonly                            | false                                        |
+-------------------------------------+----------------------------------------------+

[14:33:12]: Starting login with user 'asdf@acme.com'
[14:33:15]: Successfully logged in
[14:33:15]: Fetching profiles...
[14:33:15]: Verifying certificates...
[14:33:15]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[14:33:19]: The name 'match AdHoc com.acme.myapp.Prod.adhoc' is already taken, using another one.
[14:33:19]: Creating new provisioning profile for 'com.acme.myapp.Prod.adhoc' with name 'match AdHoc com.acme.myapp.Prod.adhoc 1548768799' for 'ios' platform
[14:33:22]: Downloading provisioning profile...
[14:33:22]: Successfully downloaded provisioning profile...
[14:33:22]: Installing provisioning profile...
/var/folders/09/t5skpwbj0_98fyt0gyjln0940000gn/T/d20190129-15957-1soqs0k/profiles/adhoc/AdHoc_com.acme.myapp.Prod.adhoc.mobileprovision
[14:33:23]: Installing provisioning profile...
[14:33:24]: 🔒  Successfully encrypted certificates repo
[14:33:24]: Pushing changes to remote git repo...
[14:33:28]: Finished uploading files to Git Repo [git@github.com:acme/myapp-secrets.git]

+---------------------+-------------------------------+-------------------------------+
|                           Installed Provisioning Profile                            |
+---------------------+-------------------------------+-------------------------------+
| Parameter           | Environment Variable          | Value                         |
+---------------------+-------------------------------+-------------------------------+
| App Identifier      |                               | com.acme.myapp.Prod.a  |
|                     |                               | dhoc                          |
| Type                |                               | adhoc                         |
| Platform            |                               | ios                           |
| Profile UUID        | sigh_com.acme.myapp.P  | 10e030cc-3d49-475e-9c36-eedf  |
|                     | rod.adhoc_adhoc               | bbfca1c5                      |
| Profile Name        | sigh_com.acme.myapp.P  | match AdHoc                   |
|                     | rod.adhoc_adhoc_profile-name  | com.acme.myapp.Prod.a  |
|                     |                               | dhoc 1548768799               |
| Profile Path        | sigh_com.acme.myapp.P  | /Users/jan/Library/MobileDev  |
|                     | rod.adhoc_adhoc_profile-path  | ice/Provisioning              |
|                     |                               | Profiles/10e030cc-3d49-475e-  |
|                     |                               | 9c36-eedfbbfca1c5.mobileprov  |
|                     |                               | ision                         |
| Development Team ID | sigh_com.acme.myapp.P  | ouruserid                    |
|                     | rod.adhoc_adhoc_team-id       |                               |
+---------------------+-------------------------------+-------------------------------+

[14:33:28]: All required keys, certificates and provisioning profiles are installed 🙌
[14:33:28]: Setting Provisioning Profile type to 'ad-hoc'
[14:33:28]: --------- Cleaning up ---------

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | prompt                     | 7           |
| 4    | register_devices           | 6           |
| 5    | match                      | 98          |
| 6    | match                      | 96          |
| 7    | match                      | 94          |
+------+----------------------------+-------------+

+--------+--------------+----------------+
|        Plugin updates available        |
+--------+--------------+----------------+
| Plugin | Your Version | Latest Version |
+--------+--------------+----------------+
| badge  | 1.0.0        | 1.2.0          |
+--------+--------------+----------------+
[14:33:28]: To update all plugins, just run
[14:33:28]: $ bundle exec fastlane update_plugins

[14:33:28]: fastlane.tools finished successfully 🎉
</pre>
</details>

### Environment

Because of reasons I can't paste my whole Fastfile here, but the important parts are in the output below.

<details>
  <pre>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                   |
| --------------------------- | ----------------------------------------------------------------------- |
| OS                          | 10.14.2                                                                 |
| Ruby                        | 2.2.4                                                                   |
| Bundler?                    | true                                                                    |
| Git                         | git version 2.16.1                                                      |
| Installation Source         | ~/Documents/Dev/ACME/MyApp/vendor/bundle/ruby/2.2.0/bin/fastlane |
| Host                        | Mac OS X 10.14.2 (18C54)                                                |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                                            |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                                              |
| Is contained                | false                                                                   |
| Is homebrew                 | false                                                                   |
| Is installed via Fabric.app | false                                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                             |
| Xcode Version               | 10.1                                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
...
<pre>
    lane :register_devices_generate_certificates do |options|
      # Get users keychain password
      keychain_password = prompt(text: "Please enter your keychain password: ", secure_text: true)

      register_devices(devices_file: './fastlane/devices.txt')
      # The configs hash map contains bundle IDs and related information like whether to use dev, adhoc or distrubution profiles etc.
      configs.each do |key, config|
        match(
          type: config[:cert_type],
          app_identifier: config[:bundle_id],
          force_for_new_devices: true,
          force: true,
          keychain_password: keychain_password
        )

      end
    end
</pre>
...
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.115.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status      |
| ------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter | 0.1.7   | ✅ Up-To-Date       |
| fastlane-plugin-badge     | 1.0.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.2       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.4        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11       |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.8        |
| fastimage                 | 2.1.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.0       |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.8.4        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| cocoapods                 | 1.5.3        |
| fastlane-plugin-appcenter | 0.1.7        |
| fastlane-plugin-badge     | 1.0.0        |
</details>

</pre>
</details>

I hope the provided information helps to track down this issue. Apparently quite a few people have had similar issues recently. Just somehow the other issues in this repo don't really point to solutions. 🤔

**Comment by JanBrinker** [comment]
Anyone has ideas on what's happening and how I can solve this?

**Comment by mollyIV** [comment]
The same issue happened recently at our team. We were adding new devices by calling [register_devices](https://docs.fastlane.tools/actions/register_devices/) and syncing the provisioning profiles by calling [match](https://docs.fastlane.tools/actions/match/). Even though we were setting `force` parameter of `match` lane to true, we were still getting a new ad-hoc profile: 

```
> Creating new provisioning profile for 'com.bundle.id.app' with name 'match AdHoc com.bundle.id.app 1549997990' for 'ios' platform
```

The workaround that worked for us was just removing all the ad-hoc profiles and calling `match` lane again ✨Although it's just a workaround, not a fix for this issue 🤷‍♂️

**Comment by justMaku** [comment]
I've looked into this closely, and it seems that at some point Apple changed the `distributionMethod` property of the profile to 'store'. I'm not sure why did that happen, but the only way I was able to fix that was to delete the existing adhoc profiles and let fastlane recreate them. Looks like a broken migration on Apple side.

**Comment by JanBrinker** [comment]
Hm, I'm not sure whether this really is an Apple issue. The problem keeps cropping back up.

**Comment by BennettSmith** [comment]
This doesn't seem to have been resolved. I agree with @JanBrinker that this seems to keep cropping up again. The workaround we use here is to essentially nuke everything and run our script again to regenerate the full set of certificates and profiles.  But, this only works once. If we later need to go in and add new devices, we end up receiving the error again and a new batch of profiles are added instead of just updating the ones that are already there. So, we nuke again.  We manage our fast lane match repo with a set of fastlane commands that had been serving us very well until a few months ago. It seems like something has regressed in match.  :-(

**Comment by eastsss** [comment]
this issue is super annoying, it recreates the profiles everytime i need to add a new device..

**Comment by Nezz** [comment]
This is still an issue that can be only worked around by calling `fastlane match nuke`.

**Comment by NikhilManapure** [comment]
+1

Same issue happening with me.
