### ISSUE TITLE
Mailgun load custom templates

### ISSUE THREAD

**Issue by RahulKatariya** [fastlane/fastlane#1416]
Is there any way i can use mailgun action to send custom mails.?

**Comment by ohwutup** [comment]
Hey @RahulKatariya, I am not so familiar with the maligun action as it was created by @thiagolioy. But maybe they can chime in and see if we can get some advice on that?

**Comment by RahulKatariya** [comment]
Yes, It would be great.

**Comment by oronbz** [comment]
I'm on it.

**Comment by tettoffensive** [comment]
@oronbz how do you structure the template so that it fills in the values like message and app_link, etc?

**Comment by RahulKatariya** [comment]
@oronbz Can you please provide an example because i am not able to set the template path right.

**Comment by oronbz** [comment]
Hi guys @tettoffensive  @RahulKatariya ,
I've just cloned the original fastlane email template and edited it to my will, you can check the original here:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/mailgun_html_template.erb

Let me know if something isn't clear

**Comment by tettoffensive** [comment]
@oronbz thanks! I was just using an html file per mailgun's advice. Didn't know about the erb.
