### ISSUE TITLE
Mailgun not working

### ISSUE THREAD

**Issue by chetan-arvindinternet** [fastlane/fastlane#14162]
### Question Checklist
My Mailgun ruby code 

platform :ios do
lane :testEmail do |values|

 mailgun(
      postmaster: "iosappreleased.arvindinternet.com",
      apikey: "key-xxxxxxxxxxxx", 
      to: "xmen@arvindinter.com",
<img width="1239" alt="screenshot 2019-01-30 at 11 30 36" src="https://user-images.githubusercontent.com/42667971/51961365-7e9bd100-2482-11e9-81cd-dae5da97abb9.png">

      from: "Chetan <chetan.b@arvindinternet.com>",
      success: true,  
      message: "Release Email Test")

  end
end
- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by JamysonFreirejf** [comment]
Just add "gem rest-client" in your Gemfile and try again
