### ISSUE TITLE
Is it possible to build iOS app by another compiler rather than gym ?

### ISSUE THREAD

**Issue by luoqiaojoe** [fastlane/fastlane#14166]
Gym is great!
But......
**Is it possible to build iOS app by another compiler rather than gym ?**

**Comment by joshdholtz** [comment]
@luoqiaojoe Heyyyy 👋 You have a few options! You could use:
- https://docs.fastlane.tools/actions/xcodebuild/#xcodebuild
- https://docs.fastlane.tools/actions/xcbuild/#xcbuild

Happy fastlaning! 🚀

**Comment by mgrebenets** [comment]
Or just run `sh` action and give it an exact build command
