### ISSUE TITLE
Match fails to find the created cert

### ISSUE THREAD

**Issue by salmanasiddiqui** [fastlane/fastlane#14178]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Have multiple apps in different teams, using match to create certs/profile. Sometimes it works and sometimes it doesn't.

##### Command executed

bundle exec fastlane build_ipa bundle_version:1109

##### Complete output when running fastlane, including the stack trace and command used

(--capture_output doesn't work, it swallows the output completely and nothing is printed on terminal)
<details>
<pre>
[✔] �
+-------------------------+---------+-------------------------+
|                        Used plugins                         |
+-------------------------+---------+-------------------------+
| Plugin                  | Version | Action                  |
+-------------------------+---------+-------------------------+
| fastlane-plugin-appicon | 0.14.0  | android_appicon appicon |
| fastlane-plugin-brew    | 0.1.1   | brew                    |
+-------------------------+---------+-------------------------+

[20:02:48]: ---------------------------
[20:02:48]: --- Step: opt_out_usage ---
[20:02:48]: ---------------------------
[20:02:48]: Disabled upload of used actions
[20:02:48]: Driving the lane 'build_ipa' �
[20:02:48]: ------------------------------------------
[20:02:48]: --- Step: Switch to should_build? lane ---
[20:02:48]: ------------------------------------------
[20:02:48]: Cruising over to lane 'should_build?' �
[20:02:48]: --------------------------------------------------
[20:02:48]: --- Step: Switch to validate_app_version! lane ---
[20:02:48]: --------------------------------------------------
[20:02:48]: Cruising over to lane 'validate_app_version!' �
[20:02:48]: Cruising back to lane 'should_build?' �
[20:02:48]: Cruising back to lane 'build_ipa' �
[20:03:00]: ----------------------------------------------
[20:03:00]: --- Step: Switch to certs_and_profile lane ---
[20:03:00]: ----------------------------------------------
[20:03:00]: Cruising over to lane 'certs_and_profile' �
[20:03:00]: -------------------------------
[20:03:00]: --- Step: sync_code_signing ---
[20:03:00]: -------------------------------
+-----------------------+----------------------------------------------------+
|                         Summary for match 2.115.0                          |
+-----------------------+----------------------------------------------------+
| git_url               | git@gitlab.com:xyz/xyz.git |
| git_branch            | K74YH36VR8                                         |
| type                  | appstore                                           |
| app_identifier        | ["x.y.z"]                       |
| username              | xyz@xyz.com                           |
| team_id               | K74YH36VR8                                         |
| clone_branch_directly | true                                               |
| readonly              | false                                              |
| storage_mode          | git                                                |
| shallow_clone         | false                                              |
| keychain_name         | login.keychain                                     |
| keychain_password     | ********                                           |
| force                 | false                                              |
| force_for_new_devices | false                                              |
| skip_confirmation     | false                                              |
| skip_docs             | false                                              |
| platform              | ios                                                |
| verbose               | false                                              |
+-----------------------+----------------------------------------------------+

[20:03:01]: Cloning remote git repo...
[20:03:02]: Checking out branch K74YH36VR8...
[20:03:02]: �  Successfully decrypted certificates repo
[20:03:02]: Verifying that the certificate and profile are still valid on the Dev Portal...
[20:03:07]: Couldn't find a valid code signing identity for distribution... creating one for you now

+-------------------+----------------------------------------------------------------+
|                              Summary for cert 2.115.0                              |
+-------------------+----------------------------------------------------------------+
| development       | false                                                          |
| force             | true                                                           |
| username          | xyz@xyz.com                                       |
| team_id           | K74YH36VR8                                                    |
| keychain_path     | $HOME/Library/Keychains/login.keychain-db |
| keychain_password | ********                                                       |
| platform          | ios                                                            |
+-------------------+----------------------------------------------------------------+

[20:03:07]: Starting login with user 'xyz@xyz.com'
[20:03:10]: Successfully logged in
security: SecKeychainItemImport: User interaction is not allowed.
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
[20:03:14]: Successfully generated YD9HS5RDMA which was imported to the local machine.
[20:03:15]: Verifying the certificate is properly installed locally...
+---------------+-----------+
|       Lane Context        |
+---------------+-----------+
| PLATFORM_NAME |           |
| LANE_NAME     | build_ipa |
+---------------+-----------+
[20:03:15]: Could not find the newly generated certificate installed

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | opt_out_usage                        | 0           |
| 2    | Switch to should_build? lane         | 0           |
| 3    | Switch to validate_app_version! lane | 0           |
| 4    | Switch to certs_and_profile lane     | 0           |
| �   | sync_code_signing                    | 14          |
+------+--------------------------------------+-------------+

[20:03:15]: fastlane finished with errors

[!] Could not find the newly generated certificate installed
</pre>
</details>

### Environment

<details>
  <pre>
[✔] �
[20:13:37]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack 

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.13.6 (17G3025)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby   
opt_out_usage
import 'DroidFastfile'
import 'IosFastfile'

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.115.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.14.0  | ✅ Up-To-Date  |
| fastlane-plugin-brew    | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.17.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| mini_mime                 | 1.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| rack                      | 2.0.5        |
| rack-test                 | 1.0.0        |
| xpath                     | 3.0.0        |
| capybara                  | 2.18.0       |
| claide                    | 1.0.2        |
| cliver                    | 0.3.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| connection_pool           | 2.2.1        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.0       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.14.0       |
| fastlane-plugin-brew      | 0.1.1        |
| git                       | 1.5.0        |
| jaro_winkler              | 1.5.1        |
| parallel                  | 1.12.1       |
| parser                    | 2.5.1.2      |
| websocket-extensions      | 0.1.3        |
| websocket-driver          | 0.7.0        |
| poltergeist               | 1.12.0       |
| powerpack                 | 0.1.2        |
| rack-protection           | 2.0.1        |
| rainbow                   | 3.0.0        |
| redis                     | 4.0.1        |
| rest-client               | 2.0.2        |
| ruby-progressbar          | 1.10.0       |
| rubocop                   | 0.58.2       |
| sidekiq                   | 5.1.3        |
</details> 
</pre>
</details>

**Comment by kas-kad** [comment]
I have the same issue, I suppose

```
INFO [2019-02-16 00:14:05.65]: $ security import /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190216-6332-1ioyk3o/certs/distribution/7ZUP5JU74H.cer -k '/Users/mobile_ci/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
DEBUG [2019-02-16 00:14:05.75]: '7ZUP5JU74H.cer' is already installed on this machine
INFO [2019-02-16 00:14:05.75]: $ security import /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190216-6332-1ioyk3o/certs/distribution/7ZUP5JU74H.p12 -k '/Users/mobile_ci/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
ERROR [2019-02-16 00:14:05.85]: security: SecKeychainItemImport: User interaction is not allowed.

+-------------------+--------------------------------------------------+
|                        Installed Certificate                         |
+-------------------+--------------------------------------------------+
| User ID           | [*******]                                       |
| Common Name       | iPhone Distribution: XXXXX ([*******]) |
| Organisation Unit | [*******]                                       |
| Organisation      | XXXXX                                   |
| Country           | XX                                               |
| Start Datetime    | 2019-02-15 15:51:09 UTC                          |
| End Datetime      | 2020-02-15 15:51:09 UTC                          |
+-------------------+--------------------------------------------------+

INFO [2019-02-16 00:14:05.85]: Installing provisioning profile...
....
```
later on, when gym starts, it fails with error:
```
❌  error: Missing private key for signing certificate. Failed to locate the private key matching certificate
```

**Comment by kas-kad** [comment]
solved my issue by manually removing all certificates from keychain
