### ISSUE TITLE
Cannot get lane shared values for ios bundleid

### ISSUE THREAD

**Issue by hydraSlav** [fastlane/fastlane#14182]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Lane SharedValues

#### Question Description
In short, I am trying to get the following to work
`puts Actions.lane_context[SharedValues::SIGH_PROFILE_PATH]`
However that prints nothing.

My Match is configured and works fine otherwise. Here is a snippet of Fastfile
``` 
   match(type: "development", readonly: true)
    puts Actions.lane_context[SharedValues::SIGH_PROFILE_PATH]
    puts Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    puts ENV["SIGH_PROFILE_PATH"]
    puts ENV["sigh_com.blah.blah_development_profile-name"]
```

And the output
```INFO [2019-02-01 17:08:56.60]: All required keys, certificates and provisioning profiles are installed 🙌
INFO [2019-02-01 17:08:56.61]: Setting Provisioning Profile type to 'development'
Successfully loaded Appfile at path '/Users/blah/Documents/Xcode Projects/blah-fastlane/fastlane/Appfile'

app_identifier: com.blah.blah 
 apple_id: blah@blah.com 
 itc_team_id: XXXX 
 team_id: ZZZZZ 
```
```
INFO [2019-02-01 17:08:56.62]:
INFO [2019-02-01 17:08:56.62]: {"com.blah.blah"=>"match Development com.blah.blah"}
INFO [2019-02-01 17:08:56.62]:
INFO [2019-02-01 17:08:56.62]: match Development com.blah.blah
```

So, as you can see, Match successfully does its thing. What I **need** is the **PROFILE_PATH**. I I need the profile_path for the following:
`automatic_code_signing(
      use_automatic_signing: false,
      team_id: "ZZZZZ",
      code_sign_identity: "iPhone Developer",
      profile_name: profile_path_here
    )`

I can get a mapping string. Or I can get profile path if I supply the bundle id in the environment variable ENV["sigh_com.blah.blah_development_profile-name"], but I don't want to hardcode the bundle ID anywhere.

Other actions have no problem figuring out the bundle ID, but I can't get anything to actually output the bundle ID.

**Comment by hydraSlav** [comment]
Yes, I have read code signing guide, and I am using Match

**Comment by janpio** [comment]
Does match actually fill `SIGH_PROFILE_PATH`?

**Comment by janpio** [comment]
That doesn't meant it uses it like it would be used when using it directly in fastlane lane. It just means that parts of its code are used to produce the certificates for match. It could very well be that the "write info into environment variables" is only implemented in a part of `sigh` that `match` doesn't execute.

Looking through the codebase to understand where `SIGH_PROFILE_PATH` is set should be simple, and if you limit a search for `sigh` to the `match` folder it should be possible to find out where and how sigh is called as well. This should give some context.

**Comment by janpio** [comment]
So I took a look:

- `sigh` is also known as `get_provisioning_profile`
- The action `get_provisioning_profile` does this: https://github.com/fastlane/fastlane/blob/4a8cf2a81cc71a556cf20183a5071294921d6731/fastlane/lib/fastlane/actions/get_provisioning_profile.rb#L17-L30
- `match` is also known as `sync_code_signing`
- That one does _not_ set the correct `SIGH` env var in the action: 
https://github.com/fastlane/fastlane/blob/0ee1f22e3c8c0c69f7fa242c8a57b19080cccded/fastlane/lib/fastlane/actions/sync_code_signing.rb#L50
https://github.com/fastlane/fastlane/blob/0ee1f22e3c8c0c69f7fa242c8a57b19080cccded/fastlane/lib/fastlane/actions/sync_code_signing.rb#L26
- `Sigh` is used by `match` here: https://github.com/fastlane/fastlane/blob/4a8cf2a81cc71a556cf20183a5071294921d6731/match/lib/match/generator.rb#L73-L77

So to get what you want and expect to work, we would either set the sigh env vars in `    * Sigh::Manager.start` already, or duplicate part of the `get_provisioning_profile` action code in the `sync_code_signing` action code.

Does this make sense?

**Comment by hydraSlav** [comment]
> Does this make sense?

Yes I understand. 

Could you do that? It's rather confusing cause **some** of `sigh` variables are available (:SIGH_PROFILE_TYPE) and some aren't, and when documentation says "uses `sigh` and `cert` in the background", my first (albeit wrong) assumption is that it's an advanced wrapper around the two

This would make so many things so much either

Thank you

**Comment by janpio** [comment]
Could you maybe take a shot at implementing this? I can't really invest much time here right now. 

Simplest way to build this would probably be to extract the `Actions.lane_context` management of `sigh` into a method, then make sure that method is also called in `match`.

**Comment by hydraSlav** [comment]
> Could you maybe take a shot at implementing this? I can't really invest much time here right now.
> 
> Simplest way to build this would probably be to extract the `Actions.lane_context` management of `sigh` into a method, then make sure that method is also called in `match`.

I've been using Fastlane for 2 weeks now, Ruby for 1.5 weeks :relaxed: , I wouldn't even know where to start. But I appreciate all the work you guys put into the free tool. Saves me tons of time.

**Comment by janpio** [comment]
So you didn't learn a new thing for a week now - time to start ;)

Of course it's fine if you don't want to jump in, please allow us a bit of time to take care of this. I added the `you can do this` tag to the issue, maybe someone else notices and creates a PR.

**Comment by mollyIV** [comment]
Hey guys 👋 I will jump on it and see what I can do, although I am not very familiar with `match` and `sigh` code, so it might take a bit 🙂 🙇

**Comment by mollyIV** [comment]
Before I start implementing the changes, gonna ask a few follow-up questions 😊

**1. Are there any conventions / rules when we should set the values for shared hash?** 

According to Lane Context [documentation](https://docs.fastlane.tools/advanced/lanes/#lane-context):

> The different actions can communicate with each other using a shared hash.

Wondering whether `match` should expose the same shared hash values that `sigh` does 🤔 The one way of looking at it is if one lane executes another under the hood, it should expose the same shared hash values. WDYT?  

**2. Testing changes in `match` and `sigh` lanes**

Do you know what's the best way to test the changes in those two lanes? Is it adding new unit tests? Or it's just running and debugging, because unit testing might be quite hard in those cases?  

**3. Implementation details**
I'd vote for the solution where we would put all `Actions.lane_context[SharedValues::...]` value settings to `Sigh::Manager.start` static method 👍 Although we'd need to investigate how many different components are calling `Sigh::Manager.start` as well, and what impact it has. 

WDYT? 🙇 

cc: @janpio , @hydraSlav

**Comment by hydraSlav** [comment]
> Before I start implementing the changes, gonna ask a few follow-up questions 😊

My 2 cents, although I am not a contributor or even an expert:
- If people use `sigh`, they are probably not using `match`, and vice-versa, so IMHO there shouldn't be conflicts with `match` setting the same variables names.
- Since `sigh` and `match` are separate actions, if someone really **is** using both, they can save the variables after `sigh` before they run `match`. The other way around is not applicable as `sigh` would just overwrite whatever `match` may have set.
- Maybe have an option to pass to `match` indicating the prefix for variables, defaults to `MATCH_` to avoid breaking anything existing. But then I can specify prefix `SIGH_` and then other actions would integrate with `match` just as they do with `sigh`.

Even if all `match` lane variables are prefixed with `MATCH_`, I can utilize them in other actions. It wouldn't be seamless as I would have to pass lane variable as parameter to other actions, but at least it would be doable.

Thank you

**Comment by janpio** [comment]
> The one way of looking at it is if one lane executes another under the hood, it should expose the same shared hash values. WDYT?

Yep, that is a valid justification. `match` also already does this, but only partially.

> Do you know what's the best way to test the changes in those two lanes? Is it adding new unit tests? Or it's just running and debugging, because unit testing might be quite hard in those cases?

Have a look at the unit tests that exist - if you can put new stuff in there, great. In this specific case I think that those ENV vars and shared values are probably not tested for, so the best way to test for them will be to create a lane that reproduces the problem and checks if the value is available after your changes.

> I'd vote for the solution where we would put all `Actions.lane_context[SharedValues::...]` value settings to `Sigh::Manager.start` static method 👍 Although we'd need to investigate how many different components are calling `Sigh::Manager.start` as well, and what impact it has.

Yep, sounds good. If it's not super easy, feel free to copy paste the "set the value" lines over from one to another. No reason to invest to much time here.

So just go ahead @mollyIV! 🚀 

I agree with your first and second point @hydraSlav, but the third suggesting an option is not necessary here. Keep it simple.

**Comment by mollyIV** [comment]
@janpio @hydraSlav 

When I was implementing the changes, I found new findings. I think what we are trying to do in this ticket is not doable 😬 

We'd like to set `Actions.lane_context[SharedValues::SIGH_PROFILE_PATH]` value after calling a `match(type: "development", readonly: true)`. `SIGH_PROFILE_PATH` variable represents a path to the **downloaded provisioning profiles**, right? If so, let's have a quick look at the documentation of `sigh` and `match` very quickly:

> match is the implementation of the https://codesigning.guide concept. match creates all required certificates & provisioning profiles and stores them in a separate git repository.

> sigh can create, renew, download and repair provisioning profiles (with one command).

The difference here is that `match` stores the profiles on a remote location like Git or Google Cloud and `sigh` stores the profiles locally. That's why we can provide a provisioning profile path after calling a `sigh`, but not for `match`. 

`sync_code_signing.rb` calls `Match::Runner.new.run(params)` under the hood. The runner downloads the profiles and certificates to temp catalog, does decryption, installs them and removes them from the temp catalog by calling `storage.clear_changes`. 

However I'd love to hear other thoughts on that with more `match` and `sigh` knowledge ☝️

**Comment by janpio** [comment]
Hm, that is very much possible @mollyIV - if `match` only leaves it in the keychain, it will indeed be difficult. 

Maybe it is time to take a step back and think about how to solve @hydraSlav 's original problem another way then:

> I need the profile_path for the following:
> `automatic_code_signing( use_automatic_signing: false, team_id: "ZZZZZ", code_sign_identity: "iPhone Developer", profile_name: profile_path_here )`

**Comment by hydraSlav** [comment]
>The difference here is that `match` stores the profiles on a remote location like Git or Google Cloud and `sigh` stores the profiles locally. That's why we can provide a provisioning profile path after calling a `sigh`, but not for `match`.

@janpio @mollyIV 

`match` _does_ store profiles (and certs) in a remote repo, however it also **installs** them locally into the default location same as what Xcode uses, i.e `/Users/username/Library/MobileDevice/Provisioning Profiles/`

This below is from running `match(type: "adhoc")`
```
13:05:54 INFO [2019-02-15 13:05:54.86]: Installing provisioning profile...
13:05:55 WARN [2019-02-15 13:05:55.32]: Setting environment variable 'sigh_com.blah_adhoc' to '97c39a3e-ZZZ-111-222'
13:05:55 WARN [2019-02-15 13:05:55.32]: Setting environment variable 'sigh_com.blah_adhoc_team-id' to 'ZZZZZ11111'
13:05:55 WARN [2019-02-15 13:05:55.32]: Setting environment variable 'sigh_com.blah_adhoc_profile-name' to 'match AdHoc com.blah'
13:05:55 WARN [2019-02-15 13:05:55.32]: Setting environment variable 'sigh_com.blah_adhoc_profile-path' to '/Users/username/Library/MobileDevice/Provisioning Profiles/97c39a3e-ZZZ-111-222.mobileprovision'
```

**Comment by mollyIV** [comment]
I had another look at the code. Please correct me if I am wrong, but the path `match` sets as environment variable is where it **installed** the provisioning profiles and `sight` sets the path (lane context `SIGH_PROFILE_PATH`) to **downloaded** provisioning profiles. The location for both is different, isn't it? 🤔

**Comment by janpio** [comment]
Well, does that really make a difference? Both are paths to the provisioning file in question. And @hydraSlav needs access to the file to be able to use it with another action.

But still, doesn't match also "download" the profile by decrypting it from git?

**Comment by mollyIV** [comment]
It does, however just after installing them, it clears the storage by calling

https://github.com/fastlane/fastlane/blob/69c04c5093175ca646e3b91c42107f239bfb5cd9/match/lib/match/runner.rb#L123

Maybe @hydraSlav could simply use an environment variable in that case? According to the code:

https://github.com/fastlane/fastlane/blob/69c04c5093175ca646e3b91c42107f239bfb5cd9/match/lib/match/runner.rb#L290-L293

https://github.com/fastlane/fastlane/blob/69c04c5093175ca646e3b91c42107f239bfb5cd9/match/lib/match/utils.rb#L31

The convention name is `sigh_applicationId_profile-path`.

**Comment by janpio** [comment]
@hydraSlav Did you have time to look into the ENV variable that @mollyIV found?

**Comment by hydraSlav** [comment]
> @hydraSlav Did you have time to look into the ENV variable that @mollyIV found?

@janpio @mollyIV 

This is pretty much the amount of code I am forced to use:

```
match_type = Actions.lane_context[SharedValues::SIGH_PROFILE_TYPE]
if match_type.to_s == "ad-hoc"
    match_type = "adhoc"  
  end
  if match_type.to_s == "app-store"
    match_type = "appstore"
  end
  sigh_profile_key = "sigh_"+CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)+"_#{match_type}"
  return File.join(FastlaneCore::ProvisioningProfile.profiles_path, "#{ENV[sigh_profile_key]}.mobileprovision")
```

And that's without any nil checks yet.

Thanks for looking into this guys, I get that this isn't a priority

**Comment by janpio** [comment]
Either I don't get your attitude or I misunderstood your tone. 

In the timeframe of ~2 weeks two different people no only looked at your problem, but tried to understand and solve it. If I interpret your last reply correctly, what @mollyIV uncovered actually does work _right now_ and solves your problem. 

If this is the case, we now know what could/should be implemented to streamline usecases similar to yours.

**Comment by hydraSlav** [comment]
> Either I don't get your attitude or I misunderstood your tone.

I don't know what I said wrong, but if it offended anyone, I apologize.
I used molly's solution, thanked both of you, and even acknowledged that I understand you spent time on this despite it not being a high priority (so, double gratitude).

Please tell me what part of my reply was offensive, and I will edit it out.

Sorry and thank you.

**Comment by janpio** [comment]
Then I definitely misunderstood your tone - happens sometimes after reading >50 issues from sometimes angry people from the internet :) Sorry 🙇‍♀️ 

Let's keep this open, maybe @mollyIV (can think of and) wants to implement a better solution.

This issue here actually triggered a bigger investigation at https://github.com/fastlane/fastlane/issues/14255 into how ENV vars and lane_context are intended to be used. Murky area as we found out, so we invest a bit of time to maybe be able to clean that up.

**Comment by hydraSlav** [comment]
> Then I definitely misunderstood your tone

Internet and non-verbal communication... am I right? :smiley:

> This issue here actually triggered a bigger investigation at #14255 into how ENV vars and lane_context are intended to be used. 

That's a great question and something that definitely got confusing for me while studying the documentation

**Comment by mollyIV** [comment]
I am glad proposed solution did work 💪 at the same time I agree - it does not look pretty and would be great to improve it. 

One solution might be adding ENV variable `ENV["MATCH_INSTALLED_PROFILE_PATH"]` to the `match` lane. It is what we basically do in `runner.rb` (ENV it is named differently though):

https://github.com/fastlane/fastlane/blob/c3e1d4e0a956c655da1dc037f8c34d120707aef0/match/lib/match/runner.rb#L298-L301

The question is if we should add the new ENV variable? I believe it will be clear once we figure out https://github.com/fastlane/fastlane/issues/14255 issue 👍 

WDYT guys?

**Comment by janpio** [comment]
Isn't the problem here that match could install x profiles?

**Comment by mollyIV** [comment]
You are right @janpio , that's why we create an ENV name dynamically ✨ So I guess maybe we could expose a different types: `ENV["MATCH_INSTALLED_PROFILE_PATH_DEVELOPMENT"]`, `ENV["MATCH_INSTALLED_PROFILE_PATH_ADHOC"]`, etc. 

Since our workaround solution did the job, I'd suggest to continue the discussion and ENV variables clarification in #14255 to have a one source of truth 🙏 🙏

**Comment by janpio** [comment]
Nah, here it's about the specific use case of match, so we are good first hashing the details here I think.

I meant that match can actually download and install the certificates of several apps, or does it limit its activity to the current app id?

**Comment by mollyIV** [comment]
@janpio according to the documentation `match` supports [multiple teams](https://docs.fastlane.tools/actions/match/#git-storage_1):

> Use one git branch per team. match also supports storing certificates of multiple teams in one repo, by using separate git branches.

`app_identifier` parameter allows you to fetch code signing for a given application identifier:

```ruby
match(type: "adhoc",
      app_identifier: "tools.fastlane.app")
```
so it seems by using `match` we can download and install the certificates of several apps.

**Comment by janpio** [comment]
Meaning what exactly?
