### ISSUE TITLE
Resign action insists on requiring a provisioning profile, even though documentation says it's optional

### ISSUE THREAD

**Issue by hydraSlav** [fastlane/fastlane#14183]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Resign action documentation says that if I am using sigh, then providing provisioning profile is optional
https://docs.fastlane.tools/actions/resign/
`provisioning_profile | Path to your provisioning_profile. Optional if you use sigh`

However every time I run it after match, it insists on entering the profile

```
INFO [2019-02-04 12:37:47.98]: All required keys, certificates and provisioning profiles are installed 🙌
INFO [2019-02-04 12:37:47.98]: Setting Provisioning Profile type to 'app-store'
INFO [2019-02-04 12:37:47.98]: --------------------
INFO [2019-02-04 12:37:47.98]: --- Step: resign ---
INFO [2019-02-04 12:37:47.98]: --------------------
WARN [2019-02-04 12:37:48.00]: To not be asked about this value, you can specify it using 'provisioning_profile'
 [2019-02-04 12:37:48.00]: Path to your provisioning_profile. Optional if you use _sigh_:
ERROR [2019-02-04 12:39:11.57]: Error setting value '' for option 'provisioning_profile'
Couldn't find provisiong profile at path ''
```

My Fastfile does this:

```
match(type: "adhoc", readonly: true)
    build_app(
      scheme: "Unity-iPhone", 
      output_name: "blah.ipa",
      include_symbols: false,
      include_bitcode: true,
      export_method: "ad-hoc"
    )
    match(type: "appstore", readonly: true)
    resign(signing_identity: "iPhone Distribution")
```

**Comment by janpio** [comment]
Does it have the same problem if you actually use _sigh_ directly (instead of via `match`)? That might be the cause for the confusing behavior - or an actual problem that the stuff shold be picked up from match as well but isn't.

**Comment by hydraSlav** [comment]
> Does it have the same problem if you actually use _sigh_ directly (instead of via `match`)? That might be the cause for the confusing behavior - or an actual problem that the stuff shold be picked up from match as well but isn't.

No, there is no problem with _sigh_ that I remember, however all the documentation pushes you to use _match_ and that's what I am trying to do.

_Sigh_ creates a mobile provisioning file locally (not under ~/Library like _match_ does). The two tools also use different naming conventions for the profiles. So they really don't play together well.

**Comment by janpio** [comment]
Well, match uses sigh under the hood ;)

But: The docs say the param is not required if you use sigh. But you use match, so the param is required. Am I missing anything?

(Not saying that this _should_ not possible work when using match)

**Comment by hydraSlav** [comment]
> Well, match uses sigh under the hood ;)

Like you said, param not required if using _sigh_, and I use _match_ (which uses _sigh_ under the hood)

**Comment by janpio** [comment]
Same comment as over at https://github.com/fastlane/fastlane/issues/14182#issuecomment-461381268:

> That doesn't meant it uses it like it would be used when using it directly in fastlane lane. It just means that parts of its code are used to produce the certificates for match.

Have a look at the code:
https://github.com/fastlane/fastlane/blob/0ee1f22e3c8c0c69f7fa242c8a57b19080cccded/fastlane/lib/fastlane/actions/resign.rb#L65-L80

So the default logic for `provisioning_profile` actually just uses `Actions.lane_context[SharedValues::SIGH_PROFILE_PATH]` - so this issue is similar to #14182. If that value is not set by `match`'s usage of `sigh`, it is of course also missing here.

Let's continue the investigation in the other issue then. If we fix that, this here will also automatically be solved.

---

> Is there no other way to resign?

You can always supply `provisioning_profile` to the action.

**Comment by hydraSlav** [comment]
> You can always supply `provisioning_profile` to the action.

I am doing this now:
I am using `match` to create, store, and retrieve both the certs and the profiles. Technically, I have zero knowledge of what names `match` may use for them

```
resign(
      ipa: appstore_ipa_name,
      signing_identity: "iPhone Distribution: TEAM (ZZZZZZ)",
      provisioning_profile: ENV["sigh_"+CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)+"_appstore_profile-path"]
    )
```

Two problems here. 

First, the `signing_identity` value is not exposed by `match` anywhere. I have to hardcode it here.  I can get the team-id from another variable, but not the team name. Granted teams don't change often, but what if they did. This situation becomes worse for dev builds, cause for development builds I can get neither the developer name nor the developer id (the part of brackets)

Second, I have to hardcode the `provisioning_profile`. It's unsightly (I know I am needlessly picky here :) ), and I cannot even use the value of `:SIGH_PROFILE_TYPE` to automate the selection, because it has the value of **ad-hoc** whereas the environment value for `*profile-path` uses **adhoc**. 

Just as with #14182, it's missing some consistency.

I really appreciate you looking into this. Thank you
