### ISSUE TITLE
Where is the action update_android_package finished?

### ISSUE THREAD

**Issue by nobady90** [fastlane/fastlane#14195]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I was looking for an android action as it is for ios: **update_info_plist**.

#### Question Description

I need to be able to change the app name and app ID for Android when I run a lane.
For ios I found **update_info_plist** while for Android I found this action created in 2016: https://github.com/fastlane/fastlane/pull/4963/files#diff-ead59bca4a2dd36baa2b6f026b0b2ba0R1313
but I can not find information about it in the Actions.md ... has it been deprecated? or does it always work and for some reason it has been deleted from the list of actions?

otherwise there is an action usable to change App name and identifier on android?

Thank you

**Comment by janpio** [comment]
The PR you linked to was never actually part of fastlane, see https://github.com/fastlane/fastlane/pull/4963 - it was deferred to a plugin. 

There are actually several plugins that do similar things now listed on https://docs.fastlane.tools/plugins/available-plugins/:
- https://github.com/MaximusMcCann/fastlane-plugin-android_change_string_app_name
- https://www.rubydoc.info/gems/fastlane-plugin-android_change_package_identifier/0.1.0
- https://github.com/beplus/fastlane-plugin-versioning_android

Do these solve your needs?

**Comment by nobady90** [comment]
ok, perfect was what I was looking for, thanks @janpio
