### ISSUE TITLE
Sigh can't log in "403 Forbidden"

### ISSUE THREAD

**Issue by sardzoski** [fastlane/fastlane#14192]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 Sigh
 No

#### Question Description

I have fastlane setup in my project and it works completely on my local machine. I want to transfer it to a company Jenkins server in order to have Continues Deployment to TestFlight. Our Jenkins servers have an IP filter that probably prevents fastlane (sigh specifically) to log in to the developer portal. 

```
[09:40:04]: Starting login with user '[xxxxxxxx]'
403 "Forbidden"
403 "Forbidden"
403 "Forbidden"
403 "Forbidden"
403 "Forbidden"

+------------------+------------------+
|            [33mLane Context[0m             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios deliver_test |
+------------------+------------------+
[09:41:18]: [31mCould not receive latest API key from App Store Connect, this might be a server issue.[0m

+------+---------------------------------------+-------------+
|                      [32mfastlane summary[0m                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | default_platform                      | 0           |
| 2    | Switch to ios build_test lane         | 0           |
| 3    | Switch to ios setup_version lane      | 0           |
| 4    | ../build_number.sh                    | 0           |
| 5    | cd .. && agvtool new-version -all 697 | 0           |
| 6    | Switch to ios setup_signing lane      | 0           |
| 7    | unlock_keychain                       | 0           |
| 💥   | [31msigh[0m                                  | 73          |
+------+---------------------------------------+-------------+
```

Using Charles Proxy on my computer I isolated all hostnames that fastlane tried to access and whitelisted them in the IP Filter. Still nothing but I am able to log in to developer.apple.com and appstoreconnect.apple.com using Safari.

Any ideas on how to proceed?

**Comment by janpio** [comment]
Does your proxy return "Forbidden" when it doesn't know a request?

You best look at the spaceship logfiles at `/tmp/spaceship*.log` - there it should probably list the requests that get a 403 Forbidden and you can then check and whitelist their IP.
