### ISSUE TITLE
Travis "no output" problem

### ISSUE THREAD

**Issue by leoMehlig** [fastlane/fastlane#1420]
I use fastlane and travis to build my app.
My carthage action takes on travis (because of building all dependencies) over 10 min. 

The problem is that travis stops the build if there was no output for more then 10 min.

If I set the carthage action to verbose the output is too large and travis stops recording it.

Is there a way that the output gets printed to the console directly or some other workaround.

thanks in advance.

**Comment by vpolouchkine** [comment]
Relevant: https://github.com/travis-ci/travis-ci/issues/3161#issuecomment-72520914

**Comment by leoMehlig** [comment]
Thanks, this is a nice workaround. I'll try to integrate it in a nice way with fastlane :+1:

**Comment by ohwutup** [comment]
Thanks @leoMehlig! I am going to close this issue for now, but if things go sour with that work around, feel free to reopen the issue and let us know. Either way, it would be nice to see how you make this work to share with the community! :100:
