### ISSUE TITLE
Caught error... 65: Screenshots not building for more than one device

### ISSUE THREAD

**Issue by adi101010** [fastlane/fastlane#14201]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Snapshot throws a Exit 65 error, tests failed when I try to do it for 2 devices, "iPad Pro (12.9-inch) (2nd generation)", "iPhone X". If I run it for one device it runs perfectly fine but not for two devices.

##### Command executed

fastlane snapshot
##### Complete output when running fastlane, including the stack trace and command used

Failing tests:
HansSoloUITests.test_Snapshot_All()
```
** TEST FAILED **
[17:52:21]: Exit status: 65
[17:52:21]: Copying '/Users/Hans/Documents/HansSolo/fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (2nd generation)-02_CategoryScreen.png'...
[17:52:21]: Copying '/Users/Hans/Documents/HansSolo/fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (2nd generation)-04_MemoryGameScreen.png'...
[17:52:21]: Copying '/Users/Hans/Documents/HansSolo/fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (2nd generation)-05_HardGameScreen.png'...
[17:52:21]: Copying '/Users/Hans/Documents/HansSolo/fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (2nd generation)-01_MainScreen.png'...
[17:52:21]: Copying '/Users/Hans/Documents/HansSolo/fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (2nd generation)-03_PracticeScreen.png'...
[17:52:21]: Tests failed while running on: iPad Pro (12.9-inch) (2nd generation), iPhone X
[17:52:21]: For more detail about the test failures, check the logs here:
[17:52:21]: /Users/Hans/Library/Logs/snapshot/HansSolo-HansSolo.log
[17:52:21]:  
[17:52:21]: You can also find the test result data here:
[17:52:21]: /var/folders/ys//T/Logs/Test
[17:52:21]:  
[17:52:21]: You can find the incomplete screenshots here:
[17:52:21]: /Users/Hans/Library/Caches/tools.fastlane/screenshots
[17:52:21]: /Users/Hans/Documents/HansSolo/fastlane/screenshots
[17:52:21]: Caught error... 65

+----------------------------+-------+
|          snapshot results          |
+----------------------------+-------+
| Device                     | es-MX |
+----------------------------+-------+
| iPad Pro (12.9-inch) (2nd  |  ❌   |
| generation)                |       |
| iPhone X                   |  ❌   |
+----------------------------+-------+
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G4015)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.115.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-02-06**
</details>
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by adi101010** [comment]
The way I got around this is by:

1. Removing all the device names from the snapfile.
2. Adding the below to the snapfile:
reinstall_app true
clean true
erase_simulator true

3. Writing a bash script for the devices

#!/bin/bash
fastlane snapshot --devices "iPhone X"
fastlane snapshot --devices "iPhone XS Max"
fastlane snapshot --devices "iPad Pro (12.9-inch) (2nd generation)"
fastlane snapshot --devices "iPad Pro (9.7-inch)"
fastlane snapshot --devices "iPhone 4s"
fastlane snapshot --devices "iPhone SE"
fastlane snapshot --devices "iPhone 7"
fastlane snapshot --devices "iPhone 7 Plus"

It all seems to work fine by using this bash script.

**Comment by emovla** [comment]
I had the same issue. Resolved disabling concurrent simulators:

fastlane snapshot --concurrent_simulators false
