### ISSUE TITLE
upload_to_play_store documentation is misleading

### ISSUE THREAD

**Issue by therealjake** [fastlane/fastlane#14206]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The tool is working as intended, but I'd like to suggest that the documentation on this particular page should be reviewed and some clarity added:

https://docs.fastlane.tools/getting-started/android/release-deployment/

Specifically, running the command `upload_to_play_store` with no extra arguments with immediately roll the build out to all production users. That's a surprising default. I wouldn't argue that the default behavior be changed, not at this state - but maybe that particular page could have some language added to make the "running this will roll out a build to all users" really clear.  Just a suggestion:

```
lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  upload_to_play_store # Uploads the APK built in the gradle step above and rolls the release out to all production users
end
```

**Comment by janpio** [comment]
Hm, adding it to the comment seems a bit easy to miss. Why not a new sentence under the code sample? A bit below it shows how to use `rollout: '0.5'`.

**Comment by therealjake** [comment]
Honestly I think mentioning it twice on the page would be wise. It's a big detail and (I can only speak for myself), not immediately obvious. So yes - if it was mentioned in the comment AND below in prose, I think that would be excellent.

There's a bullet point list preceeded by "This will also upload" - perhaps that could be reworked as:
```
This will also do the following:
- Upload app metadata ...
- Upload expansion files ...
- Upload screenshots ...
- Create a new production build
- Release the production build to all users
```
Too much?

**Comment by janpio** [comment]
No, that is actually the perfect solution!
