### ISSUE TITLE
Exporting xcarchive VS resigning an IPA?

### ISSUE THREAD

**Issue by hydraSlav** [fastlane/fastlane#14205]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

gym
resign

#### Question Description

**TL;DR:** Is there a benefit to **_gym export_** Appstore build from xcarchive, as opposed to simply **_resigning_** a development IPA with Appstore credentials/entitlements

So I compile my app, and I get an Xcode Archive out of it. This takes time, but is necessary.
Next I need to package at least 2 IPAs, one for development testing, one for AppStore.
I can combine build (to Xcode Archive) and export (to IPA) in a single _gym_ command. Great.

Now I need to just get the second IPA. I have two options here

```
match(type: "development")
gym(export_method: "development")
match(type: "appstore")
gym(skip_build_archive: true,
      archive_path: xcarchive_path,
      export_method: "app-store"
    )
```
**OR**

```
match(type: "development")
gym(export_method: "development")
mathc(type: "appstore")
resign(whatever_params)
```

The first option has 2 exports. The second options has export and resign.
The second options is tons faster (10 minutes in my case)

So the question is: is there any practical reason I shouldn't just resign a development build with appstore credentials? Am I missing something? Will it fail iTunesConnect validation if it wasn't "exported" as appstore but instead was resigned?

Using ProvisionQL quicklook on the resigned IPA shows everything is in order (the certificate and profile are correct. Entitlements are correctly applied.

I did see one [SO question](https://stackoverflow.com/questions/45432550/resigning-appstore-exported-ipas-with-development-certificate) that explains doing it the other way (export appstore, then resign for development) won't work due to appstore builds being encrypted. But what about export development, resign appstore? Doesn't iTunesConnect recompile builds anyways?

**Comment by hydraSlav** [comment]
Thanks bot

In my tests, doing a `gym export` of appstore IPA makes its size much larger than a `resign` of dev IPA to appstore

**Comment by johnknapprs** [comment]
It's doable, but unadvisable.

Think of it this way, when you package an .iOS file that is a "finished product".  Whether it's for a certain configuration or just signing, it is packaged by Apples tools. 

When you do something like resigning, you are opening a completed product and modifying it.  You hope that it will all go back into the packaging the right way, but you no longer have that assurance. 

By opening that package you are inherently modifying it.  That can cause problems you might never expect. 

If you're comfortable with the risk factory then resigning works.  If you want to have full confidence in what you package, you should not modify anything after it's created.

That all said, I do resigning on my projects when I need a quick solution that is not mission critical.  I never do it with a release candidate.
