### ISSUE TITLE
Does Gym automatically changes Xcode Build Settings?

### ISSUE THREAD

**Issue by Andre113** [fastlane/fastlane#14213]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Some questions about some flags inside Xcode build configurations and how Gym will work with them.

#### Question Description

So, Xcode has a lot of build configurations which can be set according to the selected configuration (like debug or release).
I was wondering if **Gym** will automatically changes some of these values automatically, like:
- `Build Active Architecture Only`: This should be `no` on release versions to make sure the app will be built for all the allowed architectures, but we usually keep it `yes` to make our local builds faster. Do we have to configure it manually on our settings or will fastlane change it? Can we force Gym to change this flag before building?

**Comment by joshdholtz** [comment]
@Andre113 Yes yes, `gym` will 100% look at those build settings 😊 `gym` uses `xcodebuild` under the hood which is Apple command line tool for integrating with Xcode so it will make use of all of the Xcode build stuff that it can 💪

**Comment by Andre113** [comment]
Sorry, I'm still a little bit confused.

So, for example if I set `Build Active Architecture Only` to `no` in my xcode build settings, `Gym` will use this value? 🤔

Thanks for your answer! :smile:

**Comment by joshdholtz** [comment]
@Andre113 That is correct! `gym` will use those changes

**Comment by Andre113** [comment]
I see. Thanks, @joshdholtz! 😄
The last thing, is there anyway to force `gym` to change these values?
