### ISSUE TITLE
is_ci documentation not clear — how does it identify a CI system?

### ISSUE THREAD

**Issue by fatuhoku** [fastlane/fastlane#1421]
e.g. I'm starting to use bitrise for continuous integration but it's not clear how is_ci would identify bitrise.

**Comment by asfalcone** [comment]
Hi @fatuhoku `is_ci?` checks for [environment variables](https://github.com/fastlane/fastlane_core/blob/master/lib/fastlane_core/helper.rb#L62) to determine if it is running on CI. You can set the `CI` environment variable and should be all set! 👷
