### ISSUE TITLE
WARNING: You are running Ruby 2.2.4

### ISSUE THREAD

**Issue by jbrodriguez** [fastlane/fastlane#14212]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm getting a warning that I'm running ruby 2.2.4, although I can't find that version in my system

```
⟩ which ruby
/usr/bin/ruby

⟩ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
```

I have also ```brew install ruby```, put in the path, but it doesn't make a difference.

##### Command executed
⟩ fastlane ios test

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> ⟩ fastlane ios test
[02:45:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[02:45:36]: ----------------------------------------
[02:45:36]: --- Step: Verifying fastlane version ---
[02:45:36]: ----------------------------------------
[02:45:36]: Your fastlane version 2.116.0 matches the minimum requirement of 1.99.0  ✅
[02:45:36]: ------------------------------
[02:45:36]: --- Step: default_platform ---
[02:45:36]: ------------------------------
[02:45:36]: Driving the lane 'ios test' 🚀
[02:45:36]: -------------------
[02:45:36]: --- Step: match ---
[02:45:36]: -------------------
WARNING: You are running Ruby 2.2.4, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
 </pre>
</details>

### Environment
⟩ fastlane env
[02:52:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[02:52:46]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

**Comment by janpio** [comment]
Hmm, this is actually output from https://github.com/googleapis/google-cloud-ruby - but your `fastlane env` also says you are running Ruby 2.2.4 - so fastlane is definitely running via Ruby 2.2.4. Something is wonky here.

**Comment by jbrodriguez** [comment]
Thanks !

I found ruby 2.2.4 in the ~/.fastlane folder

```
⟩ ~/.fastlane/bin/bundle/bin/ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
```

I also tried moving .fastlane/bin order in the $PATH

```
# previously
$HOME/.fastlane/bin /usr/bin

# now 
/usr/bin $HOME/.fastlane/bin 
```

That didn't work either 🤷🏼‍♂️

**Comment by janpio** [comment]
Maybe that's the idea of the brew install, that it comes with its own ruby? Don't know much about that. @joshdholtz ?

That being said: The warning is just that - a warning. The library works totally fine with that version of Ruby.

**Comment by joshdholtz** [comment]
@jbrodriguez Yup yup, this is because of using the homebrew installation! The homebrew installation of _fastlane_ is bundled with that version of ruby 😊 We provide the homebrew installation for fastlane for easy use but the recommended approach is definitely to use a `Gemfile` with `bundler` so that you have the most control of which Ruby versions and dependencies that you use 💪

**Comment by jbrodriguez** [comment]
Ok, I'll close the issue and adjust accordingly. Thanks !
