### ISSUE TITLE
set_info_plist_value changes Info.plist XML header to "... Apple Computer"; PlistBuddy changes it to "Apple" = diff annoyance

### ISSUE THREAD

**Issue by fatuhoku** [fastlane/fastlane#1422]
I use the [GIT_COMMIT_COUNT trick for build numbers](http://stackoverflow.com/a/9294933/590767) powered by `PlistBuddy` in the Xcode build phases normally.

But I found the version doesn't stick around if I run `gym`.

So I resort to wrapping another pair of  `set_info_plist_value` steps around `gym` in my Fastfile like so:

```ruby
  # Set build version  (A)
  build_number = number_of_commits
  set_info_plist_value(path: 'MakeEatSeeApp/Info.plist', key: 'CFBundleVersion', value: build_number.to_s)

  gym(
    workspace: workspace,
    scheme: scheme,
    configuration: configuration,
    output_directory: '/tmp',
    output_name: output_name
  )

  # Reset the build version  (B)
  set_info_plist_value(path: 'MakeEatSeeApp/Info.plist', key: 'CFBundleVersion', value: "GIT_COMMIT_COUNT")
```

When I run this, the value of `CFBundleVersion` sure enough gets updated as I desired:

```
GIT_COMMIT_COUNT    # this value is checked into Git
12345                               # Xcode Build Phase replaces GIT_COMMIT_COUNT with `git rev-list --count HEAD`
GIT_COMMIT_COUNT    # end of Xcode Build Phases, sets the value back
12345                               # Fastlane's set_info_plist_value doing its magic (A) above
GIT_COMMIT_COUNT    # end of lane: set_info_plist_value sets it back again.
```

So all is well, except I get this undesired diff as a side-effect:

```diff
-<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

What can I do here? :(

**Comment by vpolouchkine** [comment]
@fatuhoku Is this still an issue for you?

**Comment by fatuhoku** [comment]
@vpolouchkine yes it is. Every deploy I must revert the changes to the file. Not a very major change but it does get a little bit annoying.

**Comment by vpolouchkine** [comment]
Thanks for confirming @fatuhoku. We'll look into this.

**Comment by jkyin** [comment]
Me too.

My app target 'General' build number setting can not use the correct value in info.plist. Maybe because of this problem.
