### ISSUE TITLE
Replace all occurence of "Developer Portal Team ID" (and probably any remaining ITC teams) as everything using unified App Store Connect team id

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#14229]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The "Developer Portal Team ID" is no more. Everything is unified under App Store Connect team id. All tools and actions that explicitly required "Developer Portal Team ID" will need to get deprecated or wording reworked.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by regetskcob** [comment]
Is there already another parameter to pass the App Store Connect Team ID?

**Comment by joshdholtz** [comment]
@regetskcob Some tools just the developer center so their description for `team_id` mention something about the "Developer Portal Team ID" (like _sigh_ and _cert_) where tools like _deliver_ will mention "App Store Connect Team ID". These used to be different but since the recent unification it appears that anywhere that mentioned "Developer Portal Team ID" will actually now just use the "App Store Connect Team ID". I made this issue so that everything is uniform in all tool/action options. So you should still be able to use the same parameter but just change it to use your App Store Connect team id.

The one major exception however is _produce_ (since it access both Developer Portal to create the app there and also App Store Connect to create the listing). 

<img width="1153" alt="screen shot 2019-02-13 at 1 19 27 am" src="https://user-images.githubusercontent.com/401294/52693982-ed226980-2f2d-11e9-8939-d7c94b422bce.png">

This is one will need more cleanup that others since these are now one in the same 😊

**Comment by RR12** [comment]
Hi @joshdholtz , After apple announced the Unified thing, I start failing to get certificates with this kind of error

```
[14:07:35]: Starting login with user 'abc@def.com'
[14:07:39]: Successfully logged in
[14:07:40]: Couldn't find an existing certificate... creating a new one
```

From the discussion above, still not fully understand what should I change in my configuration. 
Can you please help me to clarify what changes should I make?

**Comment by tsafrir** [comment]
> * That user has `Developer` role
You will need him to be 'App Manager' or 'Admin' to create distribution certificates/profiles.

**Comment by RR12** [comment]
> @tsafrir 
> 
> You will need him to be 'App Manager' or 'Admin' to create distribution certificates/profiles.

But previously it just works fine with only Developer role, I dont need it to create certificates, it just failed to find existing certificates which should be available.

**Comment by tsafrir** [comment]
@RR12 I had the same error, and it turns out to be the permission issue.
If you are using match or automatic provisioning in gym/build_app then that’s probably the issue.

**Comment by RR12** [comment]
Ok then. so for now the only way to solve this is by upgrade the account role to be App Manager or Admin.
Thank you @tsafrir

**Comment by atitovdev** [comment]
@joshdholtz any _produce_ fix estimations? :) looks like there is no issue created for this.

**Comment by nihp** [comment]
@tsafrir  Kindly clarify if I use developer account can I able to upload the build to testflight?

Also in my testflight all the builds get disappeared suddenly. But I can see that build in activity tab? What is the reason for that?
