### ISSUE TITLE
Fastlane gives less screenshots on iPhoneX as compared to other devices.

### ISSUE THREAD

**Issue by sushantubale** [fastlane/fastlane#14223]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by janpio** [comment]
Can you add a bit more description @sushantubale? What command are you executing that "gives" screenshots?

**Comment by sushantubale** [comment]
I use Fastlane screenshot.

**Comment by janpio** [comment]
Please create a new issue using this template: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md and fill all the information it is asking for. Your current issue is missing all relevant information. Thanks.
