### ISSUE TITLE
Include % of iOS phased rollout in the Spaceship's app status

### ISSUE THREAD

**Issue by rockmobile** [fastlane/fastlane#14220]
### Feature Request
Include % of iOS phased rollout in the Spaceship's app status response

#### Motivation Behind Feature
We would like to notify the teams on the status of our phased rollout as that is critical to asses the adoption perentage. We were able to get the app status but not the rollout %. It would be fantastic to have that included.

#### Feature Description
Today get app status via Spaceship only provides if the app status like ready for sale, wait for review etc but it would be nice to know the % of phased of phased release when the app is already in 'ready for sale' status.

#### Alternatives or Workarounds
Alternate work around is to run a cron job to update the status every 24 hours after the initial phased release was done for next 7 days but again its not ideal as someone needs to kill the cron process if we halt the rollout.

**Comment by joshdholtz** [comment]
@rockmobile This is a duplicate issue of #12973 so I'm going to close 🙃 

This is not possible to view from the dashboard or available via an API (that we are aware of) but Apple describes the phased rollout percentage here - https://itunespartner.apple.com/en/apps/news/31070842
