### ISSUE TITLE
Appfile rules don't apply if you switch lanes

### ISSUE THREAD

**Issue by maxmeyers** [fastlane/fastlane#1423]
I have a separate `team_id` set for a specific lane. It works great if I run the lane directly, but if I get to that lane from another lane, the Appfile is ignored.

For example, here's what the Appfile looks like:

```
app_identifier "com.example.app"
apple_id "ios@example.com"
team_id "developer_team_id"

for_platform :ios do
  for_lane :beta do
    app_identifier "com.example.beta.app"
    team_id "enterprise_team_id"
  end
end
```

And the entry lane:
```
  lane :nightly do
    increment_build_number
    beta
    adhoc
  end
```

If you run `sigh` from within the `beta` lane, it will still be using the default `app_identifier` and `team_id`.

**Comment by ohwutup** [comment]
hey @maxmeyers would you mind sharing a bit more of your `Fastfile`? It would be great to see a bit more context about how those lanes are configured. Thanks! :octopus:

**Comment by mccarron** [comment]
We noticed this too, because of how we configure Fastlane with Circle CI we start on one lane and change the lane based on various things. The Appfile is only processed the first run and not after lanes are changed.

We do lane changes in the Fastfile because of how Circle does Tests and builds to reduce the amount of time the build takes by going with Fastlane only. So we fire off fastlane on the `circle` lane. 

Here's the logic we use for that if that helps:
```
lane :circle do
    if is_ci
      if ENV['CIRCLE_BRANCH'] == 'master'
        beta
      elsif ENV['CIRCLE_BRANCH'] == 'deployed'
        production
      else 
        justbuild
      end
    else
        puts "Run this lane on Circle CI only"
    end
  end
```

**Comment by maxmeyers** [comment]
Sure thing. It's not a huge deal, but the basic issue is that we have to declare the bundle id and the team id in the `sigh` call in `beta`. Though we define those variables in `Appfile`, they don't get used when switching to `beta` from `nightly`. If we run the `beta` lane directly, they do work.

```
  desc "Executes a nightly build"
  lane :nightly do
    increment_build_number
    beta
    adhoc
  end

  desc "Builds an Ad Hoc version and uploads it to Hockey & Crashlytics"
  lane :adhoc do
    sigh(
      adhoc: true,
      app_identifier: 'com.ifttt.ifttt'
    )
    gym(
      scheme: "IFTTT Ad Hoc",
      export_method: 'ad-hoc'
    )
    hockey(
      api_token: 'xxxx',
      public_identifier: 'xxxx',
      notify: '0'
    )
    crashlytics(
      api_token: 'xxxx',
      build_secret: 'xxxx',
      groups: 'ifttt-team',
      notifications: false
    )
  end

  desc "Builds a Beta Enterprise version and uploads it to Hockey & Crashlytics"
  lane :beta do
    sigh(
      app_identifier: 'com.ifttt.beta.ifttt',
      team_id: 'C7G23YU5BK'
    )
    gym(
      scheme: "IFTTT Beta",
      export_method: 'enterprise'  
    )
    hockey(
      api_token: 'xxxx',
      public_identifier: 'xxxx',
      notify: '0'
    )
    crashlytics(
      api_token: 'xxxx',
      build_secret: 'xxxx',
      groups: 'ifttt-team',
      notifications: false
    )
  end
```

**Comment by ohwutup** [comment]
Hey @maxmeyers! I think we are going to go ahead and close this issue for now as we have a bunch of other things in the pipeline right now. But please feel free to submit a PR and we would be happy to review it! Thanks!
