### ISSUE TITLE
Slack last_git_commit_hash brings with it last_git_commit as well

### ISSUE THREAD

**Issue by MartyCatawiki** [fastlane/fastlane#14234]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running
slack(default_payloads: [:git_branch, :last_git_commit_hash])

The slack plugin prints 3 payloads ('git_branch', 'last_git_commit_hash' and _'last_git_commit'_).

In the following line `should_add_payload[:last_git_commit]` should be `should_add_payload[:last_git_commit_message]`. 
https://github.com/fastlane/fastlane/blob/19779dbd4131f9bad5efddd9dd90ba92f178fa11/fastlane/lib/fastlane/actions/slack.rb#L249

This is because `last_git_commit` is part of `last_git_commit_hash` and `last_git_commit_message` is stated in the example to be used. 

This issue is also related to: #13784

**Comment by mollyIV** [comment]
👋 I'll have a look at it  👀

**Comment by mollyIV** [comment]
Okay, I think we got it 👍a new pull request has been created  https://github.com/fastlane/fastlane/pull/14241 😎
