### ISSUE TITLE
Store APNs certificates in match repo?

### ISSUE THREAD

**Issue by kpavankotesh** [fastlane/fastlane#14232]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This feature was requested in the past. Check [#6658](https://github.com/fastlane/fastlane/issues/6658)
Wanted to know if this feature is being implemented?

**Comment by janpio** [comment]
No, there is no active implementation work on this happening right now.

We would need answers to the following questions to be able to think about it:

1. How are you using `pem` right now? What is the workflow and the related lane code?
1. How would this be improved with `match`?
 
1. What additional parameters are needed in what actions? How would those be used in lanes?
1. What is all the logic behind creating, downloading, replacing of APN certificates?

**Comment by kpavankotesh** [comment]
> 1. How are you using `pem` right now? What is the workflow and the related lane code?

We simply use `pem` once to generate the push notifications certs for my applications. Having multiple developers, we would want to install these certificates on various machines to continue developing the features that require push notifications. 

> 2. How would this be improved with `match`?

`match` should have option to, store push certificates in the same repository and should have the feature to install them. It can be inside a folder `/certs/push` or you can have a separate folder specifically for `push_certs/` storing all the generated files.

> 3. What additional parameters are needed in what actions? How would those be used in lanes?

 `match(type: "apns", app_id:"my.example.app")` is good enough.
Else it can be a direct command `match apns appstore`, `match apns development` etc. with rest of the options as tags available in `pem` can be attached to this command.

> 4. What is all the logic behind creating, downloading, replacing of APN certificates?

Main purpose is to distribute among developers, and be accessible every time we need to setup on new machine. Creating only when necessary and avoid unnecessary revoke due to lack of access to the old certs. 

@janpio

**Comment by janpio** [comment]
Sounds absolutely reasonable and useful. Will try to get some more feedback from people that know their way around fastlane.

**Comment by janpio** [comment]
Ok, after thinking about this a bit more: What do you need the push certificates for on the developer machines? Usually those are only uploaded to a push provider, and then used by them. What is the local use you are thinking of?

**Comment by kpavankotesh** [comment]
Some of our application features start with push notifications. As you receive the push notification to start the tutorial for new feature added in this release / take the user to messaging screen etc

We use the development push certs to test push notification with an apps like [Knuff](https://github.com/KnuffApp/Knuff) or [Pusher](https://github.com/noodlewerk/NWPusher). For that developer needs to install the certs in local machine.

Sometimes we don't have access to previously `pem` generated files because of various reasons.

**Comment by janpio** [comment]
Ok, so you have your own "local push provider" that requires the push certificate like a normal push provider would?

I don't think this is in scope of match. Match doesn't really download anything, but installs it in the correct places which would make it a bad fit for taking care of the push certificates.

I suggest you create a plugin that can store the `pem` created files in another folder of the `match` repository. I don't think this will trip up match, and you can use the plugin's action to up- and download the files to/from the repository you are already using.

This should serve your specific use case while reusing existing functionality.

What do you think? 🙇‍♀️

**Comment by kpavankotesh** [comment]
Okay. 

Apps like [Knuff](https://github.com/KnuffApp/Knuff) and [Pusher](https://github.com/noodlewerk/NWPusher) are popular among the iOS community and they are even listed in the fastlane `pem` docs. I see it as a popular use case. If there is more demand for this, you may consider adding this feature in match itself. Thanks.
