### ISSUE TITLE
How do you pass -UseModernBuildSystem=NO to gym

### ISSUE THREAD

**Issue by jamesvec** [fastlane/fastlane#14230]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

When using gym can I just pass "-UseModernBuildSystem=NO " along with other params or is there another way to do this?
Currently I have other params in xcargs such as "BUNDLE_ID_SUFFIX='.dev' " and I am not sure if it is using the new build system or not

**Comment by dholsch** [comment]
just pass it in together with your other xcargs :)

**Comment by jamesvec** [comment]
Thank you!
