### ISSUE TITLE
Does Fastlane support Apple's mandatory two factor authentication?

### ISSUE THREAD

**Issue by joelgetaction** [fastlane/fastlane#14239]
### Question Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane and its management of certs and signing.

No

No

#### Question Description

Apple is making  two factor authentication MANDATORY for all use of the developer portal and starting February 27, 2019.  See https://support.apple.com/en-us/HT204915

Will this break Fastlane?  Will Fastlane still be able to manage certs etc?  If not, how can we update Fastlane so that it can still work with 2FA?

**Comment by abotkin-cpi** [comment]
@janpio This ties to what I was saying in #14200 that there will be a segment of fastlane users looking for a 2FA upgrade guide given the recommendation in the [CI Best Practices](https://docs.fastlane.tools/best-practices/continuous-integration/) that setting up without 2FA with a CI-specific Apple ID is the easier way to go (and first on the page).

**Comment by joelgetaction** [comment]
@abotkin-cpi and @janpio I think we should probably work on the assumption that Apple will require 2FA on ***all*** developer accounts because that feels safest and the most likely to succeed for all Fastlane users.  So ideally we need to make Fastlane work with 2FA.

The reason I doubt that a CI-specific Apple ID is doable and practical for most Fastlane users is:

* On https://support.apple.com/en-us/HT204915 it says:
  * "Because your password alone is no longer enough to access your account ..."
  * They refer to two-step authentication at https://support.apple.com/en-us/HT204152
* On https://support.apple.com/en-us/HT204152 they say:
  * "If you use two-step verification for your Apple ID, and then you upgrade to iOS 11 or later, or macOS High Sierra or later, your security settings may be automatically upgraded to two-factor authentication."  - Does this mean that if you access your CI-specific account that you setup two-step authentication for on an iOS 11 device or macOS High Sierra or later, even once, that you ability to use that CI-specific account without 2FA will be blocked now?
  * You can generate app-specific passwords for two-step verification and these might work with Fastlane
  * Can the trusted device used to verify two-step authentication codes also be signed in to an apple ID that itself uses 2FA?  Many devs can't feasibly afford to keep an Apple device just for two-step authentication

I may be making more out of this than there really is, but it sounds concerning to me.  I've filed support and forums issues with Apple asking these same questions and I'll report back here with what I find.

Thanks for your hard work on Fastlane, it is a very cool and useful tool and I really appreciate it!  :-)

**Comment by janpio** [comment]
Fastlane already fully supports 2FA (and the older 2SV).

If you use it in an interactive shell, it will just ask you for the 2FA code or 2SV token exactly as the website does.

On CI (or other systems where you can't just input some code) there are alternative solutions available: https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

We are in the process of updating that documentation to be clearer and reflect the new reality of required 2FA.

**Comment by janpio** [comment]
@joelgetaction See my first response. 

A lot of your confusion is probably because 2FA (2 factor authentication) and 2SV (2 step verification) are two different things at Apple. 2SV is the old system, where you get a 4 digit code to verify that worked on devices older than iOS 11. 2FA is the newer system, you get a 6 digit code, and only works for devices from iOS 11. So the link in your second bullet point is mostly about their upgrade path from 2SV to 2FA.

Fastlane supports both 2SV _and_ 2FA, so we are good there.

**Comment by 18padx08** [comment]
So starting in December we had this issue [Two factor sessions only lasting a few hours ](https://github.com/fastlane/fastlane/issues/13833), so we started to go back to non 2fa setups, since it was not feasible for us to manually update the sessions every few hours. Do you have any solution yet? I could not find any updates on it, and the issue was auto-closed...

**Comment by janpio** [comment]
From my observation, this was a temporary thing. But I haven't worked too much with two factor sessions in the last few weeks. So we need your observations here to be able to make any statements.

**Comment by ScottRobbins** [comment]
I'm curious if the hassle of 2FA requirements may change fastlane's position on using the app store connect api / api keys

**Comment by janpio** [comment]
What do you refer to @ScottRobbins? What alternative do you have in mind?

**Comment by jeremyspatrick** [comment]
Is there any way to use an application specific password (FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD) for cert, sigh etc. and not just deliver?

**Comment by ScottRobbins** [comment]
@janpio It's mainly the same as this issue: https://github.com/fastlane/fastlane/issues/12713 

[ITMS Transporter](https://help.apple.com/itc/transporteruserguide/#/apdATD1E1026-D1E1A1303-D1E1026A1126) and [App Store Connect API](https://developer.apple.com/app-store-connect/api/) allows the use of API keys for authentication as opposed to using username/password of a dummy CI user. 

Theoretically you then wouldn't need to generate a session token once a month. But this conversation can be continued on that thread.

**Comment by janpio** [comment]
Oh, we would love to be able to switch over!

But for now most functionality is just not available via the API. @joshdholtz is working on implementing the Testflight part I think, but besides that the important things are still missing: Creating, managing and downloading certificates and profiles, app IDs and app metadata etc.

PS: Do you have a source on the iTMS Transporter usage of API keys? If so, please open a new issue for this and we can start working on it. Although iTMSTransporter uses and still works with app specific passwords, getting rid of that part of the codebase might be a good idea.

**Comment by stevekohls** [comment]
@janpio @ScottRobbins I did a little sleuthing:
Make your way to `/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin`
And do a:
```
$ ./iTMSTransporter -help upload
```
And you'll see:
```
...
 -apiIssuer <arg>                      The -apiIssuer option specifies your App Store
                                       Connect Issuer ID.  You must also include the
                                       -apiKey option.
 -apiKey <arg>                         The -apiKey option specifies your App Store
                                       Connect API Key ID.  You must also include the
                                       -apiIssuer option. This option will search the
                                       following directories in sequence for a private
                                       key file with the name of AuthKey_<apiKey>.p8:
                                       ./private_keys, or <user home>/private_keys, or
                                       <user home>/.private_keys, or <user
                                       home>/.appstoreconnect/private_keys.
...
 -jwt <arg>                            The -jwt option specifies a JSON web token.
                                       You cannot use the -jwt option with the
                                       apiIssuer and apiKey options.
```

**Comment by ScottRobbins** [comment]
made an issue [here](https://github.com/fastlane/fastlane/issues/14244)

**Comment by joshdholtz** [comment]
The response @janpio gave is correct. We would **love** to switch over to using the new auth system with the API keys but the API keys are not backwards compatible with the private APIs that most of fastlane is built upon. 

So what we currently have to do is use the username/password sessions as those work with the private APIs and because the username/password sessions also work with **most** of the new App Store Connect API (as this is what the App Store Connect website uses).

If we were to add the use of the App Store Connect APIs, fastlane would currently lose about 90%+ functionality 😔 We are working on slowly adding new APIs that we need in order to keep things working. We may add support for the API keys here soon but it would only provided a limit set of things that _fastlane_ and all of its tools can actually do.

This may have been a longer answer than needed but this is the current state of the new App Store Connect APIs in fastlane 😇

**Comment by gholias** [comment]
Is it possible to have an Env Var with the 2FA code? Something like **FASTLANE_2FA_CODE** and when Fastlane tries to login and the 2FA is requested it uses that env var instead of asking the user to input it?
I have a crazy idea to make my CI server to be waiting for the code from the 2FA SMS and when it gets it, start a session using **fastlane spaceauth -u user@email.com** and then kick the CI build.

**Comment by Wouter33** [comment]
@gholias Apple probably links a 2FA code to a login session. If that is the case you can't have a 2FA code before fastlane triggers the login with username and password. 

What maybe could work in a (semi)automated way is that fastlane breaks up the singin in into two steps:
1. Login with username and password. 2FA required, send status/webhook/event and end process.
2. Second command resumes the login session with a 2FA code provided via CLI/ENV.

**Comment by 18padx08** [comment]
@janpio As soon as I have some time I will check what the current state is for the session thing for our projects and will respond here 👍

**Comment by janpio** [comment]
@gholias We have thought about similar ideas (and talked about it in some issue) before, so yes this would probably be doable - although with the constraints @Wouter33 mentioned as far as I know. 

But we can definitely work on something to improve the `spaceauth` process. Could you please create a new feature request issue and pull me in so we can discuss the further details? Thanks!

**Comment by gholias** [comment]
@janpio I created the feature request issue https://github.com/fastlane/fastlane/issues/14249

**Comment by garylai** [comment]
> So starting in December we had this issue [Two factor sessions only lasting a few hours ](https://github.com/fastlane/fastlane/issues/13833), so we started to go back to non 2fa setups, since it was not feasible for us to manually update the sessions every few hours. Do you have any solution yet? I could not find any updates on it, and the issue was auto-closed...

I generated a session last Friday and it worked for the whole day (office hours I mean). But it has expired when I come back this morning. There is a `max_age: 1800` in the session so I assume that the session is now only valid for 30 hours...

**Comment by garylai** [comment]
It looks like only `account holder`'s account is affected by this Apple change: https://www.bleepingcomputer.com/news/apple/apple-requiring-2-factor-authentication-on-developer-account-holders/

Only our `account holder` Apple IDs received emails about mandatory 2FA. `admin` Apple IDs haven't had it. So it looks like it is really the case. We are trying to contact Apple to confirm as well.

**Comment by 18padx08** [comment]
@janpio @garylai 
Same for me, I created a session last Friday, which wasn't valid anymore today.

@garylai Could you post an update as soon as you get any response by Apple? :)

**Comment by janpio** [comment]
> The session prints by `fastlane spaceauth -u <apple_id>` is different from the one in `~/.fastlane/spaceship/<apple_id>/cookie`. There are only 2 domains: `apple.com` and `olympus.itunes.apple.com` in the former while there more like `idmsa.apple.com` in the latter. The `max_age` for `idmsa.apple.com` is longer as well.

Very complicated topic, seems we have to look into this again. Might help if you contact me with the cookies you are seeing, then I am not only looking at my own data.

**Comment by garylai** [comment]
@18padx08 confirmed with Apple that only `Account Holders` are affected:

```After reviewing your Apple ID, it appears as though you are not currently listed as an account holder for an Apple Developer team. This new requirement will not currently affect you or your account access. If in the future you decide you would like to be an account holder of an Apple Developer Program membership, you will then need to enable two-factor authentication.```

**Comment by garylai** [comment]
@janpio My team is not going to pursue further at this point so I will not be looking into the cookie anymore. Thanks you for your help. If you need more data to investigate the cookie please let me know. I am happy to help.

**Comment by gholias** [comment]
If Apple is only forcing on the account holder it means I dont need to change my current CI workflow. I will keep using the secondary account for the CI builds

**Comment by janpio** [comment]
Thanks for that confirmation from Apple @garylai - that "suboptimal" first communication from Apple cause a few very busy days for us all. Phew.

Will create a roundup issue for this later so more people learn about it.

**Comment by 18padx08** [comment]
@garylai  Thank you very much!

**Comment by rlindner** [comment]
This has just been officially confirmed again here: ‪https://developer.apple.com/news/?id=02202019a‬

**Comment by ZonD80** [comment]
What if just ping apple after entering 2FA code every N hours to keep session alive? is it an option?

**Comment by janpio** [comment]
Even further via mail from Apple:

> You are receiving this email because you have the Account Holder role in a developer program, with full access to tools, resources, and benefits included with your membership. In an effort to keep accounts more secure, two-factor authentication will be required to sign in to your Apple Developer account and Certificates, Identifiers & Profiles starting February 27, 2019. This extra layer of security for your Apple ID helps ensure that you're the only person who can access your account. 

(The account that received this has 2FA activated already...)

---

@ZonD80 That depends on if they actually extend the session length, and if spaceship correctly handles updating the session cookie. Some testing there would be greatly appreciated!

**Comment by ZonD80** [comment]
@janpio okay, i'm on it. We will test it on Friday.

**Comment by ZonD80** [comment]
@janpio here are some tests:
_Spaceship::Portal.login(email, password)_ - acquires 2FA session cookie and with second login it remains the same - so no cookie is updated after login. However, via browser, apple sends the same cookies, but with another expiration date (+year). **I guess we need to change behavior to updating of local session cookies with every login/request.**

Upon cookie deletion (removal of file) - it requires new 2FA PIN code, so i guess their "Trust" button is only cookie life extension, because it is not working if i using incognito mode.

I've placed a worker in our system to auth on dev portal every 600 seconds, let's take a look, will it survive till Monday or not.

**Comment by janpio** [comment]
Hey everyone that posted here, I am currently working on a first improvement to the 2FA handling of fastlane/spaceship: [A way to define which phone number should automatically be selected for the 2FA token](https://github.com/fastlane/fastlane/issues/13980). 

I need some help with the output on the Apple UI though: https://github.com/fastlane/fastlane/issues/13980#issuecomment-466402647 Would be great if some of your with "trusted phone numbers" in their accounts could take a look and reply. Thanks!

**Comment by janpio** [comment]
@ZonD80 I created https://github.com/fastlane/fastlane/issues/14301 to continue this discussion and observations, so we don't spam all the other people that were involved in this issue. Everyone interested in our findings should subscribe to this issue. Thanks.

**Comment by janpio** [comment]
@zargox posted in the wrong topic, so I copy it over here:

> Regarding "Account Holder role", it is needed to have this for "individual" companies for creating session cookies in Fastlane. For other organizations it is not needed to work with fastlane session cookies, you can add your email address as a member, and access the account.

So yes, for "individual" accounts there is no way around 2FA for certificates etc. For App Store Connect, you can also use additional accounts though.

**Comment by ericnondahl** [comment]
I had trouble getting fastlane to work for our simple use case of just uploading an IPA on CI. New Apple ID accounts seem to require two factor in the setup process now, so a "dummy" account without two factor becomes less of an option if you don't already have one.

For this very simple use case, the `altool` from apple is good enough.
https://help.apple.com/itc/apploader/#/apdATD1E53-D1E1A1303-D1E53A1126

Using the altool, you can send in an Apple ID username (that has two factor enabled) with an app-specific password and there is no prompt for two factor. Looks something like this on jenkins:

`sh "\"/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool\" --upload-app -f ${ipaPath} -u username@email.com -p ${UPLOAD_PASS}"`

**Comment by fishercraigj** [comment]
Hey friends - Figured out a work around.  Create a new user in AppStoreConnect.  Make sure to only add them as an App Manager that has access to the certs and provisioning profiles (there's a little check box for that.  Make sure your new user credentials are stored however your usually store yours for your fastlane runs.  Kick off a build and you should be back to normal.

What I've found, despite what Apple actually says, are two different things.  IE: Whey the say only the Account Holder will be required to use 2FA.  While that is true, if your user is an Admin, you still ironically don't have access when running things like sigh.  Watch your build logs and you'll see what I mean.  I think there is a bug differentiating Account Holders/Admins on Apple side.  So even though the admin doesn't require 2FA, you don't have all the access that you need.

But if you take a lower access of "App Manager" with access to certificates and provisioning profiles then you're good to go.  Hope this helps someone!

**Comment by ZonD80** [comment]
Thank you! That's so odd, what's the point of having 2FA then?

**Comment by fishercraigj** [comment]
I think the intent is only to basically block something bad happening with whomever has the "account holder" credentials.

**Comment by RacingWang** [comment]
Hi all, I only run the upload action in my fastfile, and I setup the FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD env already. However, it still requires me entering the password and 2FA code of my Apple ID before uploading. Why?

**Comment by janpio** [comment]
What upload action are you talking about @RacingWang? Best create a new issue and mention me there, so we don't notify all the people that participated in this issue here. (Probable answer: Anything that touches metadata does not work with an app specific password)

**Comment by madfingo** [comment]
As with @ericnondahl, I needed to use altool to bypass the annoying prompt and login only with the user and app_specific password.

fastlane upload_to_testflight and fastlane pilot upload should be able to do the same.

**Comment by janpio** [comment]
They are able to do that @madfingo, if you don't do anything that uses a different API. I created https://github.com/fastlane/fastlane/issues/14342 to create its own action that by default is "application specific password" safe.
