### ISSUE TITLE
Is it possible to get junit logs from Snapshot?

### ISSUE THREAD

**Issue by lukewakeford** [fastlane/fastlane#14236]
I'm using fastlane to run unit tests using `scan` and UI tests (including screenshot capture) using `snapshot` on our build servers using Jenkins.

`scan` outputs a nice junit file that Jenkins can display however I can't find a way to get `snapshot` to do the same.

Can `snapshot` do this? or is there another tool I should be using to do the ui testing?

**Comment by janpio** [comment]
(I know _very_ little about iOS testing)

`snapshot` was built to take screenshots of your app, and only runs UI tests because that is the best way to do that. Isn't it possible to run the UI tests with `scan` itself?

**Comment by lukewakeford** [comment]
Hey 👋 thanks for the reply.

Yeah `scan` alone would do the job but I like the screenshots, kinda seems odd to have to run them twice? - I assumed `snapshot` would be using scan in the background to run the tests in the first place but 🤷‍♂️.

**Comment by janpio** [comment]
Yeah, that point of view makes sense. Someone would have to go into the code and have a look around what is actually going on, I don't know `snapshot` by heart. Could you take a look? It starts here: https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/runner.rb#L18 Then pretty much just follow the method and class names in the same folder.

**Comment by lukewakeford** [comment]
Thanks, I've had a look at he `snapshot` and `scan` runners and looked up a directory and found that they both have `test_command_generator.rb` files which are generating the "fully working xcodebuild command" for each tool.

So they don't share their test running code.

I did also spot the most recent commit in the snapshot repo was this: #12825 which mentions a `result_bundle` - @joshdholtz do you know if this contains junit test results?

I'll give this a test at some point anyway.
