### ISSUE TITLE
Spaceship::InsufficientPermissions error when I try to access team_members on client

### ISSUE THREAD

**Issue by lawliet616** [fastlane/fastlane#14235]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If I log in then try to access the team members I get the following error:

```ruby
<Spaceship::InsufficientPermissions: User xy@gmail.com (Team ID XXXXXXXXXX) doesn't have enough permission for the following action: team_members (You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support)>
    /Users/xy/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/client.rb:758:in `raise_insufficient_permission_error!'
    /Users/xy/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/client.rb:721:in `parse_response'
    /Users/xy/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/portal/portal_client.rb:433:in 'team_members'
```

This is the code I use for logging in:

```ruby
def login(username, password, team_id, team_name)
    Spaceship::Portal.login(username, password)
    ENV['FASTLANE_TEAM_ID'] = team_id
    Spaceship::Portal.select_team
    
    itc_login = Spaceship::Tunes.login(username, password)
    itc_team = itc_login.teams.find {|t| t["contentProvider"]["name"] == team_name}
    itc_team_id = itc_team["contentProvider"]["contentProviderId"].to_s
    ENV['FASTLANE_ITC_TEAM_ID'] = itc_team_id
    Spaceship::Tunes.select_team`
end
```

And this is the line which gives me the error:

```ruby
Spaceship::Portal.client.team_members
# It fires a request to https://developer.apple.com/services-account/QH65B2/account/getTeamMembers
```

The account I'm using is an Admin and Account Holder so it should have every permission.

I suspect that this issue has something to do with the [recent changes](https://developer.apple.com/support/teams/) around Apple Developer & App Store Connect because up until now I haven't had any problems with my code.

Is there any workaround I could use for getting team members?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.0i  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| dotenv                    | 2.6.0        |
| faraday_middleware        | 0.13.1       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.1       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-02-13**
</details>

**Comment by joshdholtz** [comment]
@lawliet616 Thanks for posting this issue! This looks somewhat related to https://github.com/fastlane/fastlane/issues/14228 but also a little. It different 🤔 I will look into this a bit more this morning 💪

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sander-m** [comment]
I have the exact same issue with an enterprise account. Are there any known workarounds?

**Comment by Jay86724** [comment]
I am getting the error when retrieving the members from the developer portal as well.
`Spaceship::Portal::Persons.all`

**Comment by vinitsample** [comment]
I am getting the error when retrieving the members from the developer portal as well.
Spaceship::Portal::Persons.all 
I am using Enterprise Developer Account and script was running well and all of sudden it's throwing me

 `Spaceship::InsufficientPermissions: User XXXX@XYZ.COM (Team ID ABCUKD123) doesn't have enough permission for the following action: team_members (You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support)`
