### ISSUE TITLE
Is Sigh needed when using Match

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14248]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Do I need to use **Sigh** when using **Match**
#### Question Description
Currently I'm storing all the PPs and Certificates in a separate git repository. Do I need to run Sigh after running Match with a specific PP type (i.e. AdHoc, or AppStore) ? Or will the Provisioning Profile be generated automatically if needed.

**Comment by janpio** [comment]
`match`/`sync_code_signing` does everything by itself (which includes calling the code of `sigh`), no other actions needed really - just build your app.

**Comment by richardtop** [comment]
Thanks for the clarification.
