### ISSUE TITLE
[spaceship] 2FA fastlane spaceship -u returns back Ruby object instead of session token

### ISSUE THREAD

**Issue by levibostian** [fastlane/fastlane#14247]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Fastlane version `2.116.0`

### Issue Description
I updated my Apple account this morning with 2FA after they are now requiring it for developer accounts. 

I use a CI server regularly for building, testing, and deploying of my apps via fastlane. Therefore, I must get a CI server to work with my account. I read the docs on Fastlane about 2FA and CI servers, I [subscribed to this Github issue](https://github.com/fastlane/fastlane/issues/14239), and am working through the fastlane docs to attempt the 2FA directions. 

After running `fastlane spaceauth -u` to get a session, fastlane prints out to the console this: 

```
Successfully logged in to App Store Connect

---

Pass the following via the FASTLANE_SESSION environment variable:
---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value: DUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTNDUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTNDUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTN\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2019-02-15 06:08:52.016987000 -06:00\n  accessed_at: 2019-02-15 06:28:11.368527000 -06:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: DUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTN\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2019-02-15 06:28:13.148697000 -06:00\n  accessed_at: *1\n
```

I am assuming this is a bug where fastlane meant to print out the properties of the ruby object not the actual ruby object? 

##### Command executed
```
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=password-here bundle exec fastlane spaceauth -u my@email.com
```

##### Complete output when running fastlane, including the stack trace and command used
```
Logging into to App Store Connect (my@email.com)...
Successfully logged in to App Store Connect

---

Pass the following via the FASTLANE_SESSION environment variable:
---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value: DUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTNDUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTNDUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTN\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2019-02-15 06:08:52.016987000 -06:00\n  accessed_at: 2019-02-15 06:28:11.368527000 -06:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: DUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTN\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2019-02-15 06:28:13.148697000 -06:00\n  accessed_at: *1\n


Example:
export FASTLANE_SESSION='---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value: DUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTNDUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTNDUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTN\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2019-02-15 06:08:52.016987000 -06:00\n  accessed_at: 2019-02-15 06:28:11.368527000 -06:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: DUFWXFPXNYCRJUHCSPDBLJWZLKDYUGZYIZPMESAFMBJNQWRWSYKMIVAVAHVKPPKUZFEXFOGADCGPJZRIAVZSBSWIQWPBFHNZRMOLNQBWKEJNNIQHBVFWGDGOJDXLMUTN\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2019-02-15 06:28:13.148697000 -06:00\n  accessed_at: *1\n'
🙄 Should fastlane copy the cookie into your clipboard, so you can easily paste it? (y/n)
```

### Environment

<details>
  <pre> 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rbenv/versions/2.5.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status      |
| ----------------------- | ------- | ------------------ |
| fastlane-plugin-appicon | 0.13.0  | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.17.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.4        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| cocoapods                 | 1.5.3        |
| cocoapods-check           | 1.0.2        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.5.0        |
| kramdown                  | 1.17.0       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.12.0       |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| danger                    | 5.6.7        |
| danger-plugin-api         | 1.0.0        |
| danger-ios_version_change | 0.1.7        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.13.0       |
| net-ssh                   | 5.1.0        |
| trent                     | 0.3.0        |
</details>

*generated on:* **2019-02-15**
</details>
 </pre>
</details>

**Comment by janpio** [comment]
No, this is pretty much exactly what it should look like - that file is read by fastlane/ruby and being in that serialized object form makes it simple to work with the data without having to parse or process it.

Are you having problem using it?
