### ISSUE TITLE
Google Api Error: apkSignedWithDifferentCertificate: APK has been signed with a different certificate to previous APKs.

### ISSUE THREAD

**Issue by hamsterpie** [fastlane/fastlane#14246]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane do not upload apk file int store. This error is on upload lane. So, when i try to upload manually - all ok. From Fastlane - no success, i see error about wrong certificate. Path is 100% correct, no apk other files in project. What can be wrong ?

**Comment by janpio** [comment]
Could you please open a "bug report" issue and include all the information it asks for? Without that it is impossible to answer such a question. Thanks!
