### ISSUE TITLE
Fastlane action verify_build making invalid assertion

### ISSUE THREAD

**Issue by RobDay** [fastlane/fastlane#1424]
Hey All,

I've been playing with the new `verify_build` action (we were very excited to see it as we have our own custom scripts that do something similar).

I don't believe the following exception is valid: 
```
raise "Inconsistent identifier found" unless plist['Entitlements']['application-identifier'] == "#{values['team_identifier']}.#{values['bundle_identifier']}"
```

Our app's bundle identifier is not prefixed by our team identifier but is prefixed with another value.  This makes the entire action unusable since the exception is raised regardless of whether or not you passed in 'bundle_identifier' to be verified.

**Comment by vpolouchkine** [comment]
@RobDay Is this still an issue for you?
