### ISSUE TITLE
Support API keys for iTMSTransporter

### ISSUE THREAD

**Issue by ScottRobbins** [fastlane/fastlane#14244]
### Feature Request

As a result of [this conversation](https://github.com/fastlane/fastlane/issues/14239#issuecomment-463801382), it was brought up that using API keys for the transporter part of fastlane may be useful.

#### Motivation Behind Feature
Required 2FA by apple means that users have to once a month generate a session token to use for their CI. Fastlane provides a wrapper around transporter to upload builds to testflight, so you _should_ be able to use api keys with transporter to avoid that problem for this feature of fastlane.

**Comment by ScottRobbins** [comment]
Just for easier visibility, copying over the post by @stevekohls

> @janpio @ScottRobbins I did a little sleuthing:
Make your way to `/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin`
And do a:

```
$ ./iTMSTransporter -help upload
```
And you'll see:

```
...
 -apiIssuer <arg>                      The -apiIssuer option specifies your App Store
                                       Connect Issuer ID.  You must also include the
                                       -apiKey option.
 -apiKey <arg>                         The -apiKey option specifies your App Store
                                       Connect API Key ID.  You must also include the
                                       -apiIssuer option. This option will search the
                                       following directories in sequence for a private
                                       key file with the name of AuthKey_<apiKey>.p8:
                                       ./private_keys, or <user home>/private_keys, or
                                       <user home>/.private_keys, or <user
                                       home>/.appstoreconnect/private_keys.
...
 -jwt <arg>                            The -jwt option specifies a JSON web token.
                                       You cannot use the -jwt option with the
                                       apiIssuer and apiKey options.
```

**Comment by ScottRobbins** [comment]
This is not in the [iTMSTransporter docs](https://help.apple.com/itc/transporteruserguide/#/apdATD1E1026-D1E1A1303-D1E1026A1126) (yet)

**Comment by janpio** [comment]
Awesome, didn't know that.

We have to decide if it is worth to invest much time here - iTMSTransporter is currently "only" used to upload apps in `deliver` and `pilot` - so for TestFlight and the AppStore itself. And most importantly you can work around 2FA perfectly by just using an app specific password, no messing around with the session necessary. So iTMSTransporter is already pretty nice!

(Was that unknown to you? Maybe we have to work on our error messages and notices a bit?)

That being said:

The code lives here: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb

It should be easy enough to introduce a few new ENV variables that can be used instead of the username + password (or app specific password) combination that is used right now.

**Comment by ScottRobbins** [comment]
> And most importantly you can work around 2FA perfectly by just using an app specific password, no messing around with the session necessary. So iTMSTransporter is already pretty nice!

If i'm reading https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth right

> because your CI machine will not be able to prompt you for your two-step or two-factor auth information, you also need to generate a login session for your CI machine in advance. You can get this by running:

`fastlane spaceauth -u user@email.com`

This seems to indicate that you need to generate this login session before running, and above it says: 

> Again, the session should be valid for about one month, however there is no way to test this without actually waiting for over a month.

So you'll have to manually do that once a month, correct?

This isn't a terribly large amount of work to do once a month, but it'd be nice for people who only need to upload the build to iTunes Connect to not have to do it.

---

> The code lives here: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb

> It should be easy enough to introduce a few new ENV variables that can be used instead of the username + password (or app specific password) combination that is used right now.

Great! Hopefully soon I can open up a PR to add that option if it's something other people would benefit from.

**Comment by janpio** [comment]
Nah, you just proved that we have to work on https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth to make this clearer 👍 

iTMSTransporter, the upload part of `deliver` and `pilot`, _just_ needs the application specific password to work with 2FA accounts. All the complicated session stuff, that has to be updated from time to time, is for the normal API that is used to upload metadata etc, not for iTMSTransporter.

(PR that hopefully will improve this lives here: https://github.com/fastlane/docs/pull/779)

Clearer?

**Comment by ScottRobbins** [comment]
Yes, that is much clearer, thank you!

**Comment by stevekohls** [comment]
@ScottRobbins You mentioned:
> Great! Hopefully soon I can open up a PR to add that option if it's something other people would benefit from.
Let me know if that's in progress, or if I or my teammates can provide any help. I certainly could provide a review.

**Comment by stevekohls** [comment]
For background, our team develops a white label app that is distributed to _many_ customers. Each customer has their own developer account, so 2FA is not a feasible option for us. Using an API key approach would be much smoother.

**Comment by ScottRobbins** [comment]
> Let me know if that's in progress, or if I or my teammates can provide any help. I certainly could provide a review.

I'm going to  work on that this weekend 👍 I'll let you know if i run into trouble or don't think I will be able to work on it.

**Comment by janpio** [comment]
I am curious @stevekohls, just so I am understanding correctly: 
Where do you see the benefit in using API keys vs. application specific passwords (which is already possible, see https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth)?

**Comment by kimdv** [comment]
@janpio I still get prompted with 2FA even I have added `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` to my environment variables.

I just want to upload binaries to the AppStore. 

My lane is

``` ruby
  lane :beta do
    build_app(scheme: "MyApp",
              include_bitcode: true)
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
```

**Comment by janpio** [comment]
@kimdv Please open a new issue for your problem, then we can discuss this in detail. (You probably also have to do the second part of https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth with `spaceauth`, as `upload_to_testflight` also uses the normal Spaceship login to talk to Apple, not just iTMSTransporter which is happy with the app specific password.)

**Comment by kimdv** [comment]
> @kimdv Please open a new issue for your problem, then we can discuss this in detail. (You probably also have to do the second part of https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth with `spaceauth`, as `upload_to_testflight` also uses the normal Spaceship login to talk to Apple, not just iTMSTransporter which is happy with the app specific password.)

Open new issue for discussion #14258

**Comment by ScottRobbins** [comment]
Note with the API Keys: Using transporter, your API key must be given the "Admin" or "App Manager" role. "Developer" won't let you upload builds, will error with: 

> You must be an App Store Connect Admin or App Manager user in order to deliver content or metadata. (1150)

This contradicts apple's [documentation](https://developer.apple.com/support/roles/)
