### ISSUE TITLE
google-cloud-storage gem ConflictError

### ISSUE THREAD

**Issue by Skoti** [fastlane/fastlane#14242]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
_fastlane_ dependencies constraints allow to use `google-cloud-storage` in version `1.17.0`:
`google-cloud-storage (>= 1.15.0, < 2.0.0)`

However, `google-cloud-storage` in version `1.17` requires `google-api-client` to be `(~> 0.26)` which conflicts with _fastlane_ requirement of:
`google-api-client (>= 0.21.2, < 0.24.0)`

I am able to run _fastlane_ if I install `google-cloud-storage` in version `1.16.0` that is fine.

Whether dependencies should be constrained for `google-cloud-storage` or extended for `google-api-client` is contributors decision to make.

**Comment by janpio** [comment]
(Labeled as `match` because match uses the `google-cloud-storage` gem)

**Comment by mironal** [comment]
I have same problem.

### Details

fastlane version: 2.116.0


```
$ fastlane help
Traceback (most recent call last):
	9: from /usr/local/var/rbenv/versions/2.5.3/bin/fastlane:23:in `<main>'
	8: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	7: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
	6: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
	5: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	4: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	3: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	2: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	1: from /usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
/usr/local/var/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate google-cloud-storage-1.17.0, because google-api-client-0.23.9 conflicts with google-api-client (~> 0.26) (Gem::ConflictError)
```

**Comment by joshuapoq** [comment]
Temporary fix:
```
gem install google-cloud-storage -v 1.15.0
gem uninstall google-cloud-storage -v 1.17.0
gem cleanup
```

**Comment by Skoti** [comment]
You don't have to uninstall version `1.17.0` if you want to use it for other dependencies. It is enough to have `1.16.0` installed and it will work.

**Comment by ylokhande82** [comment]
Any got any solution, getting following error

# sudo gem install fastlane -NVV
HEAD https://rubygems.org/latest_specs.4.8.gz
200 OK
GET https://rubygems.org/latest_specs.4.8.gz
200 OK
HEAD https://rubygems.org/specs.4.8.gz
200 OK
GET https://rubygems.org/specs.4.8.gz
200 OK
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires google-api-client (< 0.24.0, >= 0.21.2); google-cloud-storage requires google-api-client (~> 0.26)
