### ISSUE TITLE
[pilot] Uploading an IPA to TestFlight fails under Linux

### ISSUE THREAD

**Issue by TPXP** [fastlane/fastlane#14256]
🔑 

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running fastlane on Gitlab-CI on a Linux Host (I think any Linux host will have the same issue), fastlane fails to upload an IPA to the iTunes store.

##### Command executed
```
$ fastlane pilot upload --username "$FASTLANE_APPLE_LOGIN" --ipa "myapp.ipa"
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[11:58:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:58:48]: Sending anonymous analytics information
[11:58:48]: Learn more at https://docs.fastlane.tools/#metrics
[11:58:48]: No personal or sensitive data is sent.
[11:58:48]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[11:58:48]: Login to App Store Connect (****@example.com)
[11:58:52]: Login successful
[11:58:52]: Ready to upload new build to TestFlight (App: ******)...
[11:58:53]: Going to upload updated app to App Store Connect
[11:58:53]: This might take a few minutes. Please don't interrupt the script.

[11:58:53]: Error accessing file, this might be due to fastlane's directory handling
[11:58:53]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/usr/local/lib/ruby/2.6.0/fileutils.rb:128:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:293:in `execute'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:387:in `upload'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /usr/local/bundle/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /usr/local/bundle/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	from /usr/local/bundle/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bundle/bin/fastlane:23:in `load'
	from /usr/local/bundle/bin/fastlane:23:in `<main>' </pre>
</details>

### Environment
Running under Gitlab-ci with the lastest ruby image.

Here is the relevant `.gitlab-ci.yml` section:
```
testflight:
  stage: deploy
  image: ruby:latest
  variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
  before_script:
  - gem install fastlane -NV
  script:
  - fastlane pilot upload --username "$FASTLANE_APPLE_LOGIN" --ipa "app.ipa"
```
(app.ipa is an artifact provided by a previous stage, it is present as confirmed by running `ls -la` before).

**Comment by TPXP** [comment]
I think something is wrong in the iTMS helper : under linux, there is no path returned https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/helper.rb#L222

**Comment by janpio** [comment]
Yes, there is no default path configure for Linux. For macOS iTMSTransporter is installed by default with Xcode, and for Windows there is an installer (and at least I installed it to the location that is specified in the code). 

As I am not a Linux user (and don't know too much about it to be honest, besides how to break servers and make them unreachable 🐒 ) I just left that empty for now - but you can just set your own personal value by using the env variable `FASTLANE_ITUNES_TRANSPORTER_PATH`:
https://github.com/fastlane/fastlane/blob/69a77679a58868d202e36fa14317e841cda4f5ef/fastlane_core/lib/fastlane_core/helper.rb#L202

A first step to get a bit further would be to set the env var to _any existing path_, like we do in our Circle CI configuration: https://github.com/fastlane/fastlane/blob/69a77679a58868d202e36fa14317e841cda4f5ef/.circleci/config.yml#L67 CI and tests don't actually use iTMSTransporter (as it always communicates with Apple and is quite slow, which you don't want in CI) so setting it to a folder we know exists is enough.

As you want to actually use it, you should follow these instructions and then configure fastlane to use the path you used: https://help.apple.com/itc/transporteruserguide/#/apdAbeb95d60

Let me know how this works out for you!

(And yes, we should not only document this properly but also include these instructions in the output of fastlane so potential users can discover it by themselves.)

**Comment by janpio** [comment]
And as a barter trade for this long comment, could you maybe open a new issue and describe your Expo/Turtle CI setup? That sounds super interesting and we would love to hear more how you use fastlane in that setting! 😍

**Comment by TPXP** [comment]
Thanks a lot for your reply, I'll try to elaborate on our setup once I get to the bottom of this. :smile: 

I agree that we need iTunes transporter to get the app to App Store Connect. However, we need the "app developer" version (see that little note at the beginning of the [manual page](https://help.apple.com/itc/transporteruserguide/#/apdAbeb95d60)?)[1]. The relevant page to get iTunes Transporter is [this one](https://help.apple.com/itc/transporteruserguide/#/apdA3ae5a8b0?sub=apdA687d545d) and... the only available package is a package for OSX: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__OSX/bin/ . It requires to login as an Apple developer which is not automation-friendly but, just in case the file is free one day, here is how you can install it manually on a Linux host.
To manually install that pkg file, you need to build [xar](http://mackyle.github.io/xar/) (make sure to use a [fork that builds](https://github.com/mackyle/xar/pull/21)), then [decompress everything](https://stackoverflow.com/questions/11298855/how-to-unpack-and-pack-pkg-file) to get this `itms` folder.

Altenatively, install XCode on a Mac and get the `Applications/Xcode.app/Applications/Application Loader.app/Contents/itms` fiolder, it has the exact same content.

For speed purposes, and because I don't feel like building `xar` everytime in my CI pipeline, I put the contents of the `itms` file in a `tar` archive[2] so that installing it is as easy as a `curl` call followed by `tar -xf itms.tar`.

After that, we need to set  `FASTLANE_ITUNES_TRANSPORTER_PATH` to the iTunes transporter path, which gets our package recognised by fastlane ! :tada: 

Not so fast! Actually, to launch iTunes Transporter, fastlane directly dalls [the java binary bundled with the package](https://github.com/fastlane/fastlane/blob/2545fd0225b85c1204b30061f01a30ebd21d45d3/fastlane_core/lib/fastlane_core/helper.rb#L175), which in our case is broken since this binary is for OSX. This can be fixed by using the `iTMStransporter` script in the `bin` directory of the setup (:wink:), which has a little logic to use the system-wide Java on Linux (and windows?), and the bundled Java on OSX. In the meantime, just hack it :tm: with a symbolic link to the system-wide java binary.
```sh
 rm itms/java/bin/java
 rm itms/java/bin/keytool
 ln -s $(which java) itms/java/bin/java
 ln -s $(which keytool) itms/java/bin/keytool
```
_Acute readers will notice that a bash loop also does the trick. However in CI environments bash might not be the shell._

Now, it almost works, just a few java errors...
```
$ fastlane pilot upload --username "$FASTLANE_APPLE_LOGIN" --ipa "app.ipa"
[04:43:37]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[04:43:37]: Sending anonymous analytics information
[04:43:37]: Learn more at https://docs.fastlane.tools/#metrics
[04:43:37]: No personal or sensitive data is sent.
[04:43:37]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[04:43:37]: Login to App Store Connect (******@example.com)
[04:43:41]: Login successful
[04:43:41]: Ready to upload new build to TestFlight (App: ******)...
[04:43:43]: Going to upload updated app to App Store Connect
[04:43:43]: This might take a few minutes. Please don't interrupt the script.
[04:43:43]: [iTMSTransporter] Error: Could not find or load main class com.apple.transporter.Application

[04:43:43]: iTunes Transporter output above ^
[04:43:43]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

[!] Error uploading ipa file, for more information see above
```

I'll try to investigate this later.

---
<details>
<summary>Additional, salty notes, just in case Apple is willing to help one day</summary>
[1] Also, check out the links on this page. None of them actually point to a location where you can download iTunes transporter. So much for "Windows an Linux support". :laughing:

[2] I guess that's what Apple would do if they were to provide a package for Windows and Linux. :man_shrugging: </details>

**Comment by janpio** [comment]
Thanks for this description. 

(I am happy I mostly tried it on Windows, where things seemed to be a bit easier ;))

Seems I have to dig up how and where exactly I got my iTMSTransporter installers. I know that I locally have some builds for Linux as well, and we had also experimented with `xar` and alike when getting the fastlane tests running on Windows and Linux and gotten pretty far - until I noticed we don't actually _execute_ the tool. But as this was a few months ago and I never got it "production ready", stuff might have changed under us or it didn't really work after all.

That's what we got for trying to do things Apple doesn't want us to do 🐒

**Comment by janpio** [comment]
Some googling might help you:

1. https://stackoverflow.com/a/31420580/252627 gives you a download path for a Windows version
2. https://shashikantjagtap.net/working-with-ios-app-metadata-from-linux-using-transporter/ gives your the filename of the Linux package

Now use 1 with 2 ayou get a URL to download a proper Linux archive. For Windows, the current version is `1.9.8`, but seems the Linux package is not available there. Further research could tell us if they change the filename etc.

But: itms is also selfupdating and old versions seem to still be supported, so that should not be too much of a hurdle anyway.

Let me know how it goes!

**Comment by janpio** [comment]
> fastlane directly calls [the java binary bundled with the package](https://github.com/fastlane/fastlane/blob/2545fd0225b85c1204b30061f01a30ebd21d45d3/fastlane_core/lib/fastlane_core/helper.rb#L175),

> The iTMSTransporter script always outputs the `-jar` option of the [java_code_option](https://github.com/fastlane/fastlane/blob/3ba59ef4d17baac094e56d0d4e27f44556d9f732/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L273). This succeeds in launching iTMS on my Linux host. Is there any reason this is restricted to OSX ? It seems that the current version of iTMSTransporter never runs "-classpath .... com.apple.transporter.Application".
>
> In fact, the only similar string I could find in the current release of iTMSTransporter is `com.apple.transporter.launcher.Application`.
>
> Anyway, adding `|| Helper.linux?` to [the condition](https://github.com/fastlane/fastlane/blob/3ba59ef4d17baac094e56d0d4e27f44556d9f732/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L274) makes it run the jar file, and gets iTMSTransporter to start and run! 🚀

If you ever figure out _why_ fastlane is doing it this way, let me know. I guess I wrote part of that code, and I have no idea why I did it this way. It worked back then, but may very well be that this should work very differently. I am very open to improvements here!

**Comment by TPXP** [comment]
> If you ever figure out _why_ fastlane is doing it this way, let me know. I guess I wrote part of that code, and I have no idea why I did it this way. It worked back then, but may very well be that this should work very differently. I am very open to improvements here!

I think that launching transporter the other way (with "-classpath") used to work for previous versions (pre-Xcode 9, according to the condition), and that an update changed to the jar method. As you probably know, jar files are just a zip archive with class files inside, so it doesn't change much, except it cleans up the command a little (no need to specify the class name).

I see two possible patches:
* change the [java_code_option](https://github.com/fastlane/fastlane/blob/3ba59ef4d17baac094e56d0d4e27f44556d9f732/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L273) function to something that uses the old method only for old XCodes:
```    def java_code_option
      if Helper.mac? && !Helper.xcode_at_least?(9)
        return "-classpath #{Helper.transporter_java_jar_path.shellescape} com.apple.transporter.Application"
      else
        return "-jar #{Helper.transporter_java_jar_path.shellescape}"
      end
    end
```
* use the iTMS transporter wrapping script whenever available (this is the case for the current version of iTMS transporter). This seems more future-proof to me since even file name changes won't break fastlane, but I don't know if the `iTMStransporter` script is available in every build. So we might still have to keep the previous code (collect metrics about it? Drop pre-Xcode 9 support?). Another cool thing about using this wrapper is that it might work on windows as well (we just have to use the ".cmd" version).

Either way, since we need the `AppStoreInfo.plist` file, which cannot be generated on Windows and Linux, we also need to add a parameter to the upload command.

Regarding the setup of iTMStransporter, I'm not confident in installing it automatically. It should be easier to document how to install it (and this is a one-time setup anyway).

**Comment by janpio** [comment]
Sorry, I am not sure what your current state is now. Do we need to change anything on fastlane side?

I also found theses instructions again that list how to get a working setup on Linux: https://discussions.apple.com/thread/4960669?answerId=28313296022#28313296022 (ignore the bad English obviously).

Can you elaborate on how you found that `AppStoreInfo.plist` is missing as well? I am pretty sure I uploaded builds from Windows successfully before (but am not in a position to retry that _right now_ unfortunately).

**Comment by ineentho** [comment]
Thanks to all the directions in this and other issues, I managed to upload a .ipa using this dockerfile: https://github.com/ineentho/fastlane-docker/blob/master/Dockerfile

And then running it using
```
docker run --rm -itv `pwd`:/home/builder/workspace:rw --user $(id -u):$(id -g) fastlane-docker sh -c 'bundle install && bundle exec fastlane deliver --ipa my-app.ipa'
```

**Comment by TPXP** [comment]
I tried @ineentho 's image and -to my surprise- it worked and managed to deliver the app to TestFlight! Looks like using the Windows Installer instead of the OSX bundle does the trick. I added a few suggestions [here](https://github.com/ineentho/fastlane-docker/issues/1).

Using the `FASTLANE_ITUNES_TRANSPORTER_PATH` enables us to tell fastlane where itms is, and `FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT` tells fastlane to use the shell script instead of trying to call the transporter directly. I think fastlane should use the script in all cases (even on OSX), which would simplify the code and make it crossplatform. Also, clarifiying the error messages if itms cannot be found on Windows and Linux could make it easier to use Fastlane to deliver apps on these platforms.

Anyway, we got it to work! :tada:

**Comment by frederikbosch** [comment]
For Linux there is a problem with the iTMSTransporter, see [this issue](https://github.com/fastlane/fastlane/issues/14349). It is required to supply `-assetDescription` when uploading an ipa. This assetDescription needs to be generated by `swinfo` which is an OSX application. The result of `swinfo` is AppStoreInfo.plist file and that has is the value for the assetDescription argument.

@ineentho How did you solve that issue? According to the [iTMSTransporter documentation by Apple](https://help.apple.com/itc/transporteruserguide/?lang=en#/apdAa073cb45) the assetDescription is also required for Windows. Fastlane is not creating such a file if I am not mistaken.

A little more about the AppStoreInfoi.plist can be found in the [Archive export files documentation](https://help.apple.com/xcode/mac/current/#/deva1f2ab5a2).

**Comment by frederikbosch** [comment]
@ineentho The version of the iTMSTransporter you are using in your Docker is an older version. It does not contain the possibility to use API keys. It also lacks the assetDescription option, which is probably why it works for now on that Linux Docker.

**Comment by janpio** [comment]
What is the current version of iTMSTransporter for Windows in your opinion @frederikbosch?

We generally don't expect Apple to disable older (or any) versions for quite some time, so this is not really a problem.

**Comment by frederikbosch** [comment]
@janpio I am referring to the one [inside the Docker](https://github.com/ineentho/fastlane-docker/blob/master/Dockerfile) mentioned by @ineentho in this conversation. That Docker is using version 1.9.8, while my machine is on 1.13.0.

**Comment by janpio** [comment]
As far as I know there is no 1.13.0 for Windows. The version numbers across platforms are no equal in iTMS land afaik. If you have 1.13.0 on your Windows machine, can you share where you got it?

**Comment by frederikbosch** [comment]
Sorry, it is complicated. That Docker is using the Windows installer, see [this line](https://github.com/ineentho/fastlane-docker/blob/master/Dockerfile#L27), while on my machine (Ubuntu) I am using 1.13.0. The last version is probably because iTMSTransporter does auto-updates on start, which is disable for the Docker.

**Comment by janpio** [comment]
Ok, so the auto update feature also breaks existing iTMSTransporter installations on Linux. That's a problem :/

**Comment by frederikbosch** [comment]
Yes.

**Comment by frederikbosch** [comment]
But, there is also an opportunity in the newer version of the iTMSTransporter: it supports api key usage. That is really an advantage because while 2FA is wonderful for non-computers, it really sucks for automated CI processes like fastlane.

**Comment by janpio** [comment]
iTMSTransporter also works with app specific passwords, so this is not really an issue.
The other APIs for uploading metadata, screenshots etc are what require actual 2FA.

**Comment by TPXP** [comment]
Thanks for the explanation, it brings a new light on the reasons why uploading uploading worked. Version numbers did not come to mind but, indeed, that makes sense.

I believe iTMSTransporter is a universal software since it's written in Java. That's why I tried using the OSX variant but, since it's a too recent version, it didn't work and complained about missing`-assetDescription`. The OSX version ran properly though, and besides the bundled Java binary that needs to be replaced (or bypassed using the shell script) everything is OK with it.

I believe we should find a way to generate this `AppStoreInfo.plist` file on Linux/Windows before bundling the latest version. At least, that's what my use case (building an IPA on an external CI then uploading it under Linux) would suggest doing. Maybe the CI system could be adapted too, so giving both options could be another possibility.

**Comment by frederikbosch** [comment]
@TPXP I have exactly the same use-case. For me the solution will be generating that `AppStoreInfo.plist` on that external CI, because I see no way for generating such a file by code.

**Comment by TPXP** [comment]
Yup, generating the `AppStoreInfo.plist` file on the external CI could be an other solution. In that case, we need to be able to pass it to FastLane, and FastLane should pass it to iTMStransporter. This requires the addition of another option to the `deliver` and `pilot` commands.

**Comment by lilili87222** [comment]
http://www.appuploader.net works on windows and linux to upload ipa

**Comment by TPXP** [comment]
The latest fastlane build does not fix this issue. Please do not close this issue 🙏
