### ISSUE TITLE
Exact file format specs for text files synced from Google Play?

### ISSUE THREAD

**Issue by eighthave** [fastlane/fastlane#14251]
### Question Checklist

- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Weblate has implemented support for the native Fastlane text files so the can be easily translated.  Weblate is based on git repos, so whitespace changes can cause merge conflicts and unnecessary noise.  So it is important to minimize whitespace changes as much as possible for a smooth, automated workflow.  Towards that end, we'd like to know more about how Fastlane handles the text files so that Weblate does the same thing.  Is there a canonical format for _title.txt_, _summary.txt_, etc. regarding leading and trailing spaces? Does fastlane write out _title.txt_,  _summary.txt_, etc. based on the data from Google Play without modifying it?  Does anyone know if submitting to Google Play, then fetching from Google Play will strip whitespace?

For more info:
https://github.com/WeblateOrg/weblate/issues/1525#issuecomment-464086454
@janpio  @nijel

**Comment by janpio** [comment]
Data is downloaded here: 
https://github.com/fastlane/fastlane/blob/39e3f9bc32a69e8c2ced04b248ca351766c76446/deliver/lib/deliver/setup.rb#L43-L45
And then written to files here: 
https://github.com/fastlane/fastlane/blob/39e3f9bc32a69e8c2ced04b248ca351766c76446/deliver/lib/deliver/setup.rb#L59-L128

Lets focus on one specific example:
https://github.com/fastlane/fastlane/blob/39e3f9bc32a69e8c2ced04b248ca351766c76446/deliver/lib/deliver/setup.rb#L65-L73
First it gets the data. Then it adds a `\n` at the end, and writes the result to the file.

So my guess: The API returns a trimmed string, fastlane/`deliver` adds the last line break before writing to the file (Linux style).

You should be able to confirm by testing this with your own apps. Best also try to add a few empty lines at the description for example - my guess is that Google strips those when saving anyway so the API always returns trimmed values.
