### ISSUE TITLE
Unable to sign/build ios react-native application 

### ISSUE THREAD

**Issue by alikor** [fastlane/fastlane#14259]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Unable to sign/build ios react-native application 

##### Complete output when running fastlane, including the stack trace and command used

--capture_output

<details>
  <pre>
fastlane beta 
[21:39:23]: $ set -o pipefail && xcodebuild -scheme APP -project ./ios/APP.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/XXX/Library/Developer/Xcode/Archives/2019-02-17/APP\ 2019-02-17\ 21.39.23.xcarchive BUNDLE_IDENTIFIER=com.APP PROVISIONING_PROFILE_SPECIFIER=XXXXXX/APP\ AppStore\ iOS\ Distribution DEVELOPMENT_TEAM=XXXXXX archive | tee /Users/XXXX/Library/Logs/gym/APP-APP.log | xcpretty
[21:39:27]: ▸ ❌  error: No profile for team 'XXXXXXX' matching 'APP AppStore iOS Distribution' found: Xcode couldn't find any provisioning profiles matching 'XXXXXXX/APP AppStore iOS Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'APP')
[21:39:27]: ▸ ** ARCHIVE FAILED **

❌  error: No profile for team 'T85GZD447R' matching 'BabyPoint AppStore iOS Distribution' found: Xcode couldn't find any provisioning profiles matching 'T85GZD447R/BabyPoint AppStore iOS Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'BabyPoint')

[21:39:27]: ▸ note: Using new build system
[21:39:27]: ▸ note: Planning build
[21:39:27]: ▸ note: Constructing build description
[21:39:27]: ▸ Build system information
[21:39:27]: ▸ error: No profile for team 'XXXXXXXX' matching 'APP AppStore iOS Distribution' found: Xcode couldn't find any provisioning profiles matching 'XXXXXXXXXX/APP AppStore iOS Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'BabyPoint')
[21:39:27]: 
[21:39:27]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[21:39:27]: 📋  For the complete and more detailed error log, check the full log at:
[21:39:27]: 📋  /Users/madu/Library/Logs/gym/BabyPoint-BabyPoint.log
[21:39:27]: 
[21:39:27]: Looks like fastlane ran into a build/archive error with your project
[21:39:27]: It's hard to tell what's causing the error, so we wrote some guides on how
[21:39:27]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[21:39:27]: Before submitting an issue on GitHub, please follow the guide above and make
[21:39:27]: sure your project is set up correctly.
[21:39:27]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[21:39:27]: the full commands printed out in yellow in the above log.
[21:39:27]: Make sure to inspect the output above, as usually you'll find more error information there
[21:39:27]: 
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.2                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.2 (18C54)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.116.0'

MY_APP_ID = 'com.xxxxapp'
MY_PROFILE = 'T85XXXXXXX/APP AppStore iOS Distribution'
MY_TEAM = 'T85XXXXXXX'

settings_to_override = {
  :BUNDLE_IDENTIFIER => MY_APP_ID,
  :PROVISIONING_PROFILE_SPECIFIER => MY_PROFILE,
  :DEVELOPMENT_TEAM => MY_TEAM
}

# before_all do
#   ensure_git_branch
#   ensure_git_status_clean
#   git_pull
# end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "./ios/APP.xcodeproj")
    build_app(scheme: "APP")
    upload_to_testflight
  end
end



platform :android do
  # Android Lanes
end

git_url = "git@github.com:XXXX/cert.git"
username = "XXX@gmail.com"

desc 'Fetch certificates and provisioning profiles'
lane :certificates do
  match(app_identifier: 'com.xxxxapp', type: 'development', username: username, git_url: git_url, readonly: false)
  match(app_identifier: 'com.xxxxapp', type: 'appstore', username: username,  git_url: git_url, readonly: false)
end

desc 'Build the iOS application.'
private_lane :build do
  certificates
  increment_build_number(xcodeproj: './ios/APP.xcodeproj')
  build_app(
    export_method: 'app-store',
    xcargs: settings_to_override,
    scheme: 'APP', 
    project: './ios/APP.xcodeproj',
    export_options: {
        provisioningProfiles: { 
            MY_APP_ID => MY_PROFILE
        }
    }
  )
end

desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/APP.xcodeproj')
    push_to_git_remote
end

desc "Register new device"
lane :register_new_device do 
    register_devices(
      devices: {
        "XXXiPhone" => "XXXXXX"
      })
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.xxxxapp") # The bundle identifier of your app
apple_id("madu.alikor@gmail.com") # Your Apple email address

itc_team_id("106264803") # App Store Connect Team ID
team_id("T85XXXXXXX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-02-17**
</details>

**Comment by alikor** [comment]
Not helpful i know its todo with signing and have checked the guide no help

**Comment by janpio** [comment]
How did you create and install the provisioning profile mentioned in the error message?

> [21:39:27]: ▸ ❌  error: No profile for team 'XXXXXXX' matching 'APP AppStore iOS Distribution' found: Xcode couldn't find any provisioning profiles matching 'XXXXXXX/APP AppStore iOS Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'APP')

> ❌  error: No profile for team 'T85GZD447R' matching 'BabyPoint AppStore iOS Distribution' found: Xcode couldn't find any provisioning profiles matching 'T85GZD447R/BabyPoint AppStore iOS Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'BabyPoint')

**Comment by alikor** [comment]
I using the 
    lane :certificates do

Lane

**Comment by janpio** [comment]
So you used `match`.

Is the development team ID correct?
Do the app names match?
Are the profile names mentioned correct?
