### ISSUE TITLE
scan: error: unable to spawn process (Argument list too long)

### ISSUE THREAD

**Issue by frederic-adda** [fastlane/fastlane#14250]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We have a **big** target to build for tests (around 1.700 swift files)
We use fastlane through gitlab, and particularly `scan` to run our unit tests.

The issue we have: when scan runs, and tries to build all of our files, it issues a `swiftc` command including the path of all files to build. The number of files, plus the fact that the command includes the full path of each files, passes the threshold of allowed characters in a command.
As a result, our scan fails, with the error message: 
`error: unable to spawn process (Argument list too long)`

Is there an option in `scan` that would let us include the relative path of files instead of the absolute path? (for example instead of `/Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Assemblies/ContractToSign/CancelContract/CancelContractServiceAssembly.swift`, get only `./Core/Assemblies/ContractToSign/CancelContract/CancelContractServiceAssembly.swift`) 

##### Command executed
In our fastfile: 

```
# Lane for tests
    lane :tests do |options|
        scheme = options[:tests_scheme]

        scan(
            scheme: "#{scheme}",
            skip_build: true,            
            derived_data_path: "fastlane/artefacts/derivedData"
            )
    end
```

##### Complete output when running fastlane, including the stack trace and command used
This is the end of the `scan` log

<details>
  <pre> CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target: Core)
    cd /Users//builds/e045fde4/0/firstname.lastname/projectname
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Core -Onone -whole-module-optimization -enforce-exclusivity=none -DDEBUG -Onone -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -target x86_64-apple-ios9.3-simulator -g -module-cache-path /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/fastlane/artefacts/derivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -profile-coverage-mapping -profile-generate -enable-testing -index-store-path /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/fastlane/artefacts/derivedData/Index/DataStore -swift-version 4.2 -I /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/fastlane/artefacts/derivedData/Build/Products/development-iphonesimulator -I /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Common/ProjectModule -F /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/fastlane/artefacts/derivedData/Build/Products/development-iphonesimulator -F /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Carthage/Build/iOS -F /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Vendors/Fabric -F /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Vendors/KeyPass -F /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Service/LifeInsurance/LiveInsuranceArbitrage/LiveInsuranceArbitrageRoute.swift /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Service/Transfer/CountryCurrency/Servicing/Parameters/CountryCurrencyServiceParameters.swift /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Service/BlockDebit/Web/BlockDebitAccountWebService.swift /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Entity/Edoc/Collection/EdocType.swift /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Service/DataProtection/GDPRInformationNote/Web/GDPRInformationNoteWebService.swift /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Service/Checkbook/Ordering/Order/Servicing/CheckbookInitializeOrderServicing.swift /Users/companyname/builds/e045fde4/0/firstname.lastname/projectname/Core/Assemblies/ContractToSign/CancelContract/CancelContractServiceAssembly.swift ...
(this goes on with 1.700 files appended like the previous one: `/Users/...`)

    error: unable to spawn process (Argument list too long) </pre>
</details>
NB: names and companies have been redacted.

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D42)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.116.0 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-02-15**
</details> </pre>
</details>

**Comment by janpio** [comment]
Huh, interesting problem. 

I don't know much about how scan works internally, and with the snippets you posted I could not find the relevant code parts that generate that command that it tries to execute here. Could you maybe share some more context? The `swiftc` command is possibly not created by fastlane directly, but indirectly by something it calls.

If this command is really created by fastlane, we should be able to optimize it to use relative paths instead of absolute ones. Maybe there is also a better way to achieve the same result in general.

**Comment by augie09** [comment]
I am seeing this same issue.  We added two extension targets to our iOS project, which already had one extension.  Adding either one by itself builds fine, but adding both puts us over.
