### ISSUE TITLE
Should we able to display upload percentage?

### ISSUE THREAD

**Issue by Ilesh** [fastlane/fastlane#14254]
#### Motivation Behind Feature

"This might take a few minutes. Please don't interrupt the script." Sometimes this message displays a long time due to a slow internet connection and worried about it. :(

#### Feature Description

The progress bar is help developer to keeps patients doing things, maybe user needs progress when they compiling, uploading the binary, etc...

**Comment by janpio** [comment]
Where exactly are you getting that output? There are multiple locations where we upload things, context might help to pinpoint if we might be able to adda a progress bar there.

**Comment by joshdholtz** [comment]
@Ilesh If you are uploading something through `deliver` or `pilot`, it will show upload percent if you run with `--verbose` 🤔

**Comment by Ilesh** [comment]
Thanks, guys for your reply. Will check and let you know. :)
