### ISSUE TITLE
disable_automatic_code_signing not work in xcode duplicate target

### ISSUE THREAD

**Issue by marksiu** [fastlane/fastlane#14263]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am not sure this is Xcode issue or not, please let me know if the issue should not be asked in here.
I have read the following issues.
[#9062](https://github.com/fastlane/fastlane/issues/9062)
[#10497](https://github.com/fastlane/fastlane/issues/10497)
[#11217](https://github.com/fastlane/fastlane/issues/11217)

There are 3 targets in my workspace (I use cocoapods).
1. MyAppTargetA
2. MyAppTestingTargetB (Unit Test Target for MyAppTargetA)
3. MyAppTargetC (duplicate MyAppTargetA)

I can use Xcode to run and archive `MyAppTargetA` and `MyAppTargetC` without any problems.

I would like to use `disable_automatic_code_signing` to disable automatic code sign in `MyAppTargetA` and `MyAppTargetC`

```
lane :disable_auto_sign do
      disable_automatic_code_signing(
         path: "MyApp.xcodeproj",
         use_automatic_signing: false,
         targets: ["MyAppTargetA", "MyAppTargetC"]
     )
end
```

After run `bundle exec fastlane ios disable_auto_sign`
`fastlane` can only search 2 targets  `MyAppTargetA` and `MyAppTestingTargetB`
(please see the below fastlane output)

I checked the code in **fastlane/fastlane/lib/fastlane/actions/automatic_code_signing.rb**
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/automatic_code_signing.rb
In Line 21, the project targets are found in `TargetAttributes` in `MyApp.xcodeproj/project.pbxproj`

Therefore, I opened the file (use git blame to see the code instead of UI)
found there are only 2 targets are listed within `TargetAttributes`.
The duplicate target, `MyAppTargetC`, is not listed within `TargetAttributes`.
```
TargetAttributes = {
	XXXXXXXXXXXXXXXXXTargetA = {
		CreatedOnToolsVersion = 9.4.1;
		DevelopmentTeam = xxxxxxxxxx;
		ProvisioningStyle = Manual;
	};
	XXXXXXXXXXXXXXXXXTargetB = {
		CreatedOnToolsVersion = 9.4.1;
		ProvisioningStyle = Manual;
		TestTargetID = XXXXXXXXXXXXXXXXXTargetA;
	};
};
```

In the same file, when I search `targets`, I can see the following targets 
```
targets = (
	XXXXXXXXXXXXXXXXXTargetA /* MyAppTargetA */,
	XXXXXXXXXXXXXXXXXTargetB /* MyAppTestingTargetB */,
	XXXXXXXXXXXXXXXXXTargetC /* MyAppTargetC */,
);
```

After that, I manually add the following code to `MyApp.xcodeproj/project.pbxproj` 
( I don't prefer this way)
and run `bundle exec fastlane ios disable_auto_sign` again, it works.
```TargetAttributes = {
	XXXXXXXXXXXXXXXXXTargetA = {
		CreatedOnToolsVersion = 9.4.1;
		DevelopmentTeam = xxxxxxxxxx;
		ProvisioningStyle = Manual;
	};
	XXXXXXXXXXXXXXXXXTargetB = {
		CreatedOnToolsVersion = 9.4.1;
		ProvisioningStyle = Manual;
		TestTargetID = XXXXXXXXXXXXXXXXXTargetA;
	};
	XXXXXXXXXXXXXXXXXTargetC = {
		CreatedOnToolsVersion = 9.4.1;
		DevelopmentTeam = xxxxxxxxxx;
		ProvisioningStyle = Manual;
	};
};
```

I have search  `MyApp.xcodeproj/project.pbxproj`  and other files, but it seems not any other places I can find the target list except `TargetAttributes`.

Can anyone help for that?
 
##### Command executed

`bundle exec fastlane ios disable_auto_sign`

##### Complete output when running fastlane, including the stack trace and command used

  <pre> [✔] 🚀
[11:56:19]: ------------------------------
[11:56:19]: --- Step: default_platform ---
[11:56:19]: ------------------------------
[11:56:19]: Driving the lane 'ios disable_auto_sign' 🚀
[11:56:19]: ------------------------------------
[11:56:19]: --- Step: automatic_code_signing ---
[11:56:19]: ------------------------------------

+-----------------------+----------------------------------+
|            Summary for Automatic Codesigning             |
+-----------------------+----------------------------------+
| path                  | MyApp.xcodeproj                  |
| use_automatic_signing | false                            |
| targets               | ["MyAppTargetA", "MyAppTargetC"] |
+-----------------------+----------------------------------+

[11:56:19]: Updating the Automatic Codesigning flag to disabled for the given project '/Users/x/MyApp.xcodeproj/project.pbxproj'
[11:56:19]: Skipping MyAppTestingTargetB not selected (MyAppTargetA,MyAppTargetC)
[11:56:19]: Successfully updated project settings to use Code Sign Style = 'Manual'
[11:56:19]: Modified Targets:
[11:56:19]: 	 * MyAppTargetA

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | automatic_code_signing | 0           |
+------+------------------------+-------------+

[11:56:19]: fastlane.tools finished successfully 🎉 </pre>

### Environment

  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.1                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.1 (18B75)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           | </pre>

**Comment by janpio** [comment]
Did using `disable_automatic_code_signing` break your `MyApp.xcodeproj/project.pbxproj`?

**Comment by marksiu** [comment]
Hi, @janpio 
thank you for your reply.
I am not sure your meaning of "break", would you mind to explain more? 😄

I run the lane in the question and it doesn't update the target because Xcode doesn't generate the reference in `TargetAttributes` inside `MyApp.xcodeproj/project.pbxproj`.

I can use Xcode and cmd to build/archive the app without any problem.
So I am wonder it is Xcode issue or not.

Thank you very much.

**Comment by janpio** [comment]
I had misunderstood your issue then, sorry.

**Comment by marksiu** [comment]
The problem is solved by using the following script.

Before run `disable_automatic_code_signing()`, it needs to run the following ruby file to add the missing target to `MyApp.xcodeproj`

`ruby ./add_missing_target.rb`

```
#!/usr/bin/env ruby
require 'xcodeproj'

puts "\n"
puts "+-----------------------------------------------------+"
puts "+       Add Missing Targets to TargetAttributes       +"
puts "+-----------------------------------------------------+"


# Target name, MUST same as Xcode target name
target_c_name = "MyAppTargetC"

puts "Update the following targets"
puts "    ** " + target_c_name

# get project path
projectpath = "./MyAPP.xcodeproj"

# open project
puts "\nOpen project at " + projectpath + "..."
project = Xcodeproj::Project.open(projectpath)

# add MyAppTargetC target to the project
puts "\nStart search targets ...\n"
project.targets.each do |target|

    if target.name == target_c_name

    	puts "  -- Found target " + target.name + ", start update ..."

        # add the element you need in here
    	
    	created_on_tools_version = {}
    	created_on_tools_version = {"CreatedOnToolsVersion" => "9.4.1"}

    	target_attributes = project.root_object.attributes['TargetAttributes']
    	target_attributes[target.uuid] = system_capabilities.merge(created_on_tools_version)

    	puts "     > Finished add " + target.name + " to project.pbxproj TargetAttributes"

	else 
		puts "  -- Skip target " + target.name + " (not match with " + target_c_name + " and " + production_target_name + ")"
	end
end

puts "\nStart save project"
project.save
puts "Finish save project"
puts "\n"
```

**Comment by atereshkov** [comment]
The same problem is here for me.
