### ISSUE TITLE
How to set/unset "Reset iOS Summary Rating" option?

### ISSUE THREAD

**Issue by andreyz** [fastlane/fastlane#14266]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Fastlane, App Store submission "Reset iOS Summary Rating" property setter?

#### Question Description
There is an ability in Spaceship to set Reset iOS Summary Rating property on a new App Store build with the following [Feature Request: Reset iOS Summary Rating](https://github.com/fastlane/fastlane/issues/10422). After search in the docs and source code, I didn't find any way to set that particular option via Fastlane configuration files. Does one exist?

**Comment by andreyz** [comment]
@fastlane-bot no idea why that's relevant, but here it goes

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.20.1                                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | Mac OS X 10.14.3 (18D109)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-10.1.app/Contents/Developer/               |
| Xcode Version               | 10.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// Customize this file, documentation can be found here:
// https://docs.fastlane.tools/
// All available actions: https://docs.fastlane.tools/actions
// can also be listed using the `fastlane actions` command

import Foundation

class Fastfile: LaneFile {
    // This is the minimum version number required.
    // Update this, if you use features of a newer version
    var fastlaneVersion: String { return "2.108.0" }

    func beforeAll() {
        // environmentVariables["SLACK_URL"] = "https://hooks.slack.com/services/..."
        // cocoapods()
        // carthage()
        // updateFastlane()
    }

    func deliverLane() {
        desc("Uploads metadata")
        deliver()
    }
    
    func testLane() {
        desc("Runs all the tests")
        runTests()
    }

    func betaLane(withOptions options:[String: String]?) {
        desc("Submit a new Beta Build to Apple TestFlight. This will also make sure the profile is up to date")
        
        ensureGitStatusClean()
        
        let changelog = prompt(text: "Changelog: ", multiLineEndKeyword: "END")
        
        buildApp(scheme: "App",
                 clean: true,
                 silent: true,
                 includeSymbols: true,
                 includeBitcode: true,
                 exportMethod: "app-store")
        
        uploadToTestflight(username: appleID,
                           changelog: changelog,
                           waitForUploadedBuild: true)
    }

    func releaseLane() {
        desc("Deploy a new version to the App Store")

        ensureGitStatusClean()
        
        buildApp(scheme: "App",
                 clean: true,
                 silent: true,
                 includeSymbols: true,
                 includeBitcode: true,
                 exportMethod: "app-store")

        //        captureScreenshots()
        //        frameScreenshots()
        
        precheck(appIdentifier: appIdentifier, username: appleID, teamId: teamID, includeInAppPurchases: false)
        
        uploadToAppStore(username: appleID, metadataPath: "Fastlane/metadata", screenshotsPath: "Fastlane/screenshots", force: true, app: appIdentifier)
    }

    // You can define as many lanes as you want

    func afterAll(currentLane: String) {
        notification(message: "\(currentLane): Successfully deployed.")
        // This block is called, only if the executed lane was successful
        // slack(
        //     message: "Successfully deployed new App Update.",
        //     slackUrl: "slackURL"
        // )
    }

    func onError(currentLane: String, errorInfo: String) {
        notification(message: "\(currentLane): Failed with \(errorInfo)")
        // slack(
        //     message: errorInfo,
        //     slackUrl: "slackUrl",
        //     success: false
        // )
    }

    // All available actions: https://docs.fastlane.tools/actions

    // fastlane reports which actions are used. No personal data is recorded.
    // Learn more at https://github.com/fastlane/fastlane/#metrics
}

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.1        |
| bundler                   | 2.0.1        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-02-19**
</details>

**Comment by mollyIV** [comment]
Hey @andreyz 👋 

I had a look at [AppStoreConnect.md docs](https://github.com/fastlane/fastlane/blob/d738d74a1070b8a8eb8ffb69374589d929364ef2/spaceship/docs/AppStoreConnect.md) and `AppVersions` section might help to answer to your question 🙂

```ruby
v = app.edit_version # the version that's in `Prepare for Submission` mode
v.ratings_reset = true # reset the ratings

# Push the changes back to the server
v.save!
```

I think you could try to give it ☝️a shot 🙂

**Comment by andreyz** [comment]
Thanks @mollyIV, I'm aware that Spaceship exposes that property. What I'm looking for is a way to set the same property in a Fastfile or by any other mean beyond scripting Spaceship in Ruby...

**Comment by mollyIV** [comment]
Oh I see, sorry @andreyz  😬 in that case there's a [`deliver`](https://docs.fastlane.tools/actions/deliver/) (part of a fastlane) which uses `spaceship` under the hood. Unfortunately I couldn't find the option to reset the ratings in the [docs](https://docs.fastlane.tools/actions/deliver/#parameters) and in the code [`upload_metadata.rb`](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/upload_metadata.rb). 

I think we could make a pull request where we would add a new input param (option) for `deliver` like `reset_ratings # reset your rating`. I would be happy to help with it 🤚 

As a workaround that you can do right now is just using a `spaceship` directly in your Fastfile:

```ruby
# Fastfile
require 'spaceship'

...

lane :reset_ratings do
    Spaceship::Tunes.login
    Spaceship::Tunes.select_team

    v = app.edit_version
    v.ratings_reset = true
    v.save!
end
```

I'd like to also hear someone with more experience with `deliver` that could confirm the above findings 🙏

**Comment by andreyz** [comment]
Thank you for such extensive reply @mollyIV !

I'm using Fastlane Swift (which is in eternal beta), so referencing Spaceship directly from there is out of the question. 

On the other hand, if `deliver` would support `reset_ratings` option, then the Swift wrapper would pick that change up, I think.

**Comment by mollyIV** [comment]
@andreyz I create the [pull request](https://github.com/fastlane/fastlane/pull/14289) for this feature. Could you please help me out with manual testing? 🙏 

To do so I believe you need to modify your `Gemfile` to get the fastlane from my branch:

```ruby
source "https://rubygems.org"

gem "fastlane", git: "https://github.com/mollyIV/fastlane", branch: "deliver-reset-summary-rating"
```

Please let me know in a case of any problems 🙇

**Comment by andreyz** [comment]
@mollyIV you're a super-⭐️!
