### ISSUE TITLE
fastlane init not working on Android

### ISSUE THREAD

**Issue by FireZenk** [fastlane/fastlane#14261]
### Issue Description
Tried to execute `fastlane init` on an Android (standar project using the SDK) project with:
```
minSdk = 23
targetSdk = 28
compileSdk = 28
```
##### Command executed
`fastlane init`

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
DEBUG [2019-02-18 11:41:28.03]: Checking if there are any plugins that should be loaded...
ERROR [2019-02-18 11:41:28.87]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
ERROR [2019-02-18 11:41:28.87]: Please `cd` into the directory of the intended Xcode project you wish to use.
/Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again (FastlaneCore::Interface::FastlaneError)
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/setup/setup.rb:93:in `start'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details>
<pre>
<summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 10.14.3                                             |
| Ruby                        | 2.2.4                                               |
| Bundler?                    | false                                               |
| Git                         | git version 2.7.4 (Apple Git-66)                    |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                 |
| Host                        | Mac OS X 10.14.3 (18D109)                           |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                          |
| Is contained                | true                                                |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | ~/../../Applications/Xcode7.app/Contents/Developer/ |
| Xcode Version               | 7.3.1                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.16.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.8.0        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2019-02-18**
</pre>
</details>

**Comment by janpio** [comment]
Can you post the `tree` output of where you are running the `fastlane init` command?
Is it a new Android project or an existing one? Anything special about it?

**Comment by FireZenk** [comment]
Dependencies tree
<details>
<pre>
releaseRuntimeClasspath - Runtime classpath of compilation 'release' (target  (androidJvm)).
+--- androidx.databinding:databinding-common:3.3.1
+--- androidx.databinding:databinding-runtime:3.3.1
|    +--- androidx.lifecycle:lifecycle-runtime:2.0.0-alpha1 -> 2.0.0
|    |    +--- androidx.lifecycle:lifecycle-common:2.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    +--- androidx.arch.core:core-common:2.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    +--- androidx.collection:collection:1.0.0-alpha1 -> 1.0.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    \--- androidx.databinding:databinding-common:3.3.1
+--- androidx.databinding:databinding-adapters:3.3.1
|    +--- androidx.databinding:databinding-common:3.3.1
|    \--- androidx.databinding:databinding-runtime:3.3.1 (*)
+--- project :data
|    +--- project :kit
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21
|    |    |    \--- org.jetbrains:annotations:13.0 -> 16.0.1
|    |    +--- org.koin:koin-core:1.0.2
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71 -> 1.3.21 (*)
|    |    +--- com.jakewharton.timber:timber:4.7.1
|    |    |    \--- org.jetbrains:annotations:16.0.1
|    |    \--- com.google.code.gson:gson:2.8.5
|    +--- project :domain
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
|    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.20 -> 1.3.21 (*)
|    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.1.1
|    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.20 -> 1.3.21
|    |    +--- org.koin:koin-core:1.0.2 (*)
|    |    \--- io.arrow-kt:arrow-core:0.8.2
|    |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.11
|    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 -> 1.3.21 (*)
|    |         \--- io.arrow-kt:arrow-annotations:0.8.2
|    |              +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 -> 1.3.21 (*)
|    |              \--- io.kindedj:kindedj:1.1.0
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1 (*)
|    +--- org.koin:koin-core:1.0.2 (*)
|    +--- androidx.room:room-common:2.0.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    +--- androidx.room:room-runtime:2.0.0
|    |    +--- androidx.room:room-common:2.0.0 (*)
|    |    +--- androidx.sqlite:sqlite-framework:2.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    \--- androidx.sqlite:sqlite:2.0.0
|    |    |         \--- androidx.annotation:annotation:1.0.0
|    |    +--- androidx.sqlite:sqlite:2.0.0 (*)
|    |    +--- androidx.arch.core:core-runtime:2.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    \--- androidx.arch.core:core-common:2.0.0 (*)
|    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0-rc01 -> 1.0.0
|    |         +--- androidx.annotation:annotation:1.0.0
|    |         +--- androidx.core:core:1.0.0
|    |         |    +--- androidx.annotation:annotation:1.0.0
|    |         |    +--- androidx.collection:collection:1.0.0 (*)
|    |         |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0 (*)
|    |         |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0
|    |         |         +--- androidx.annotation:annotation:1.0.0
|    |         |         \--- androidx.collection:collection:1.0.0 (*)
|    |         +--- androidx.documentfile:documentfile:1.0.0
|    |         |    \--- androidx.annotation:annotation:1.0.0
|    |         +--- androidx.loader:loader:1.0.0
|    |         |    +--- androidx.annotation:annotation:1.0.0
|    |         |    +--- androidx.core:core:1.0.0 (*)
|    |         |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0
|    |         |    |    +--- androidx.arch.core:core-runtime:2.0.0 (*)
|    |         |    |    +--- androidx.lifecycle:lifecycle-livedata-core:2.0.0
|    |         |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 (*)
|    |         |    |    |    +--- androidx.arch.core:core-common:2.0.0 (*)
|    |         |    |    |    \--- androidx.arch.core:core-runtime:2.0.0 (*)
|    |         |    |    \--- androidx.arch.core:core-common:2.0.0 (*)
|    |         |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0
|    |         |         \--- androidx.annotation:annotation:1.0.0
|    |         +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
|    |         |    \--- androidx.annotation:annotation:1.0.0
|    |         \--- androidx.print:print:1.0.0
|    |              \--- androidx.annotation:annotation:1.0.0
|    +--- io.arrow-kt:arrow-core:0.8.2 (*)
|    \--- com.google.code.gson:gson:2.8.5
+--- project :domain (*)
+--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.20 -> 1.3.21 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1 (*)
+--- androidx.appcompat:appcompat:1.0.0
|    +--- androidx.annotation:annotation:1.0.0
|    +--- androidx.core:core:1.0.0 (*)
|    +--- androidx.collection:collection:1.0.0 (*)
|    +--- androidx.cursoradapter:cursoradapter:1.0.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    +--- androidx.fragment:fragment:1.0.0
|    |    +--- androidx.core:core:1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    +--- androidx.customview:customview:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    \--- androidx.core:core:1.0.0 (*)
|    |    |    +--- androidx.viewpager:viewpager:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.interpolator:interpolator:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    \--- androidx.core:core:1.0.0 (*)
|    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    +--- androidx.annotation:annotation:1.0.0
|    |    +--- androidx.loader:loader:1.0.0 (*)
|    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 (*)
|    +--- androidx.vectordrawable:vectordrawable:1.0.0
|    |    +--- androidx.annotation:annotation:1.0.0
|    |    \--- androidx.core:core:1.0.0 (*)
|    \--- androidx.vectordrawable:vectordrawable-animated:1.0.0
|         +--- androidx.vectordrawable:vectordrawable:1.0.0 (*)
|         \--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
+--- com.google.android.material:material:1.0.0
|    +--- androidx.annotation:annotation:1.0.0
|    +--- androidx.core:core:1.0.0 (*)
|    +--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
|    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    +--- androidx.fragment:fragment:1.0.0 (*)
|    +--- androidx.transition:transition:1.0.0
|    |    +--- androidx.annotation:annotation:1.0.0
|    |    \--- androidx.core:core:1.0.0 (*)
|    +--- androidx.appcompat:appcompat:1.0.0 (*)
|    +--- androidx.cardview:cardview:1.0.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    \--- androidx.recyclerview:recyclerview:1.0.0
|         +--- androidx.annotation:annotation:1.0.0
|         +--- androidx.core:core:1.0.0 (*)
|         \--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
+--- androidx.cardview:cardview:1.0.0 (*)
+--- androidx.constraintlayout:constraintlayout:1.1.3
|    \--- androidx.constraintlayout:constraintlayout-solver:1.1.3
+--- androidx.constraintlayout:constraintlayout-solver:1.1.3
+--- com.jakewharton.timber:timber:4.7.1 (*)
+--- com.karumi:dexter:4.2.0
|    +--- androidx.appcompat:appcompat:1.0.0 (*)
|    \--- com.google.android.material:material:1.0.0 (*)
+--- org.koin:koin-core:1.0.2 (*)
+--- org.koin:koin-android:1.0.2
|    \--- org.koin:koin-core:1.0.2 (*)
+--- org.koin:koin-androidx-viewmodel:1.0.2
|    +--- org.koin:koin-core-ext:1.0.2
|    |    \--- org.koin:koin-core:1.0.2 (*)
|    +--- org.koin:koin-androidx-scope:1.0.2
|    |    +--- org.koin:koin-android:1.0.2 (*)
|    |    \--- androidx.lifecycle:lifecycle-common:2.0.0-rc01 -> 2.0.0 (*)
|    \--- androidx.lifecycle:lifecycle-extensions:2.0.0-rc01 -> 2.0.0
|         +--- androidx.lifecycle:lifecycle-runtime:2.0.0 (*)
|         +--- androidx.arch.core:core-common:2.0.0 (*)
|         +--- androidx.arch.core:core-runtime:2.0.0 (*)
|         +--- androidx.fragment:fragment:1.0.0 (*)
|         +--- androidx.lifecycle:lifecycle-common:2.0.0 (*)
|         +--- androidx.lifecycle:lifecycle-livedata:2.0.0 (*)
|         +--- androidx.lifecycle:lifecycle-process:2.0.0
|         |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0 (*)
|         +--- androidx.lifecycle:lifecycle-service:2.0.0
|         |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0 (*)
|         \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 (*)
+--- io.arrow-kt:arrow-core:0.8.2 (*)
+--- com.squareup.okhttp3:logging-interceptor:3.11.0
|    \--- com.squareup.okhttp3:okhttp:3.11.0
|         \--- com.squareup.okio:okio:1.14.0
+--- androidx.lifecycle:lifecycle-extensions:2.0.0 (*)
+--- android.arch.navigation:navigation-fragment:1.0.0-alpha06
|    +--- android.arch.navigation:navigation-runtime:1.0.0-alpha06
|    |    +--- android.arch.navigation:navigation-common:1.0.0-alpha06
|    |    |    \--- androidx.core:core:1.0.0 (*)
|    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    \--- androidx.fragment:fragment:1.0.0 (*)
+--- android.arch.navigation:navigation-ui:1.0.0-alpha06
|    +--- android.arch.navigation:navigation-runtime:1.0.0-alpha06 (*)
|    \--- com.google.android.material:material:1.0.0 (*)
+--- android.arch.navigation:navigation-ui-ktx:1.0.0-alpha06
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.50 -> 1.3.21 (*)
|    +--- android.arch.navigation:navigation-ui:1.0.0-alpha06 (*)
|    \--- android.arch.navigation:navigation-runtime-ktx:1.0.0-alpha06
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.50 -> 1.3.21 (*)
|         +--- android.arch.navigation:navigation-runtime:1.0.0-alpha06 (*)
|         \--- android.arch.navigation:navigation-common-ktx:1.0.0-alpha06
|              +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.50 -> 1.3.21 (*)
|              \--- android.arch.navigation:navigation-common:1.0.0-alpha06 (*)
+--- com.github.bumptech.glide:glide:4.8.0
|    +--- com.github.bumptech.glide:gifdecoder:4.8.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    +--- com.github.bumptech.glide:disklrucache:4.8.0
|    +--- com.github.bumptech.glide:annotations:4.8.0
|    \--- androidx.fragment:fragment:1.0.0 (*)
+--- me.relex:circleindicator:2.1.0
|    \--- androidx.annotation:annotation:1.0.0
+--- uk.co.chrisjenx:calligraphy:2.3.0
|    \--- androidx.appcompat:appcompat:1.0.0 (*)
+--- com.brandongogetap:stickyheaders:0.5.1-androidx
+--- io.fotoapparat:fotoapparat:2.6.1
|    +--- androidx.annotation:annotation:1.0.0
|    +--- androidx.exifinterface:exifinterface:1.0.0
|    |    \--- androidx.annotation:annotation:1.0.0
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.0 -> 1.3.21 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.0 -> 1.1.1 (*)
+--- me.zhanghai.android.materialprogressbar:library:1.6.0
|    +--- androidx.appcompat:appcompat:1.0.0 (*)
|    \--- androidx.annotation:annotation:1.0.0
+--- jp.wasabeef:glide-transformations:4.0.1
|    \--- com.github.bumptech.glide:glide:4.8.0 (*)
\--- com.readystatesoftware.chuck:library-no-op:1.1.0
     \--- com.squareup.okhttp3:okhttp:3.6.0 -> 3.11.0 (*)
</pre>
</details>

-----
Is an existing Android project, also uses the last version of the NDK

**Comment by janpio** [comment]
Uh, `tree` should output an overview of the file structure of that project usually. `fastlane init` is only looking at the folder and file structure, and then making an educated guess about the project type. Seems it can't recognize your project as Android, and then is unhappy that it is not an iOS project either.

(To work around this: Just create `fastlane/Fastfile` and create your content manually. Init doesn't do much more but offer you a bit of a wizard to prepopulate the `Fastfile`.)
