### ISSUE TITLE
automatic skip Preview.html

### ISSUE THREAD

**Issue by Wbqqqq** [fastlane/fastlane#14264]
When I upload ipa to appstore ，fastlane always show “Does the Preview on path './fastlane/Preview.html' look okay for you?” and let me to select.

hhhh ,  it let me can't take it easy to go to the toilet .

so , how can i automatic skip or let let it remember me before choice.

thanks very much .

**Comment by marksiu** [comment]
Hi, @Wbqqqq 
Please check #10078 for more information
You can set the param `force=true` if you are using `delivery`
Doc: https://docs.fastlane.tools/actions/deliver/

**Comment by ricardopereira** [comment]
@Wbqqqq Please change the issue title to something more explicit and related with the issue.

**Comment by Wbqqqq** [comment]
thanks , @marksiu .
