### ISSUE TITLE
Google::Apis::AuthorizationError: [!] Unauthorized

### ISSUE THREAD

**Issue by iammatis** [fastlane/fastlane#14268]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

`bundle exec fastlane internal`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ bundle exec fastlane internal
[13:02:57]: ------------------------------
[13:02:57]: --- Step: default_platform ---
[13:02:57]: ------------------------------
[13:02:57]: Driving the lane 'android internal' 🚀
[13:02:57]: ----------------------------------
[13:02:57]: --- Step: upload_to_play_store ---
[13:02:57]: ----------------------------------

+-------------------------+-----------------------------------------------+
|                       Summary for supply 2.116.0                        |
+-------------------------+-----------------------------------------------+
| track                   | internal                                      |
| apk                     | app/build/outputs/apk/release/app-release.apk |
| package_name            | com.pakcage.name                              |
| json_key                | ./fastlane/google_play_api_key.json           |
| skip_upload_apk         | false                                         |
| skip_upload_aab         | false                                         |
| skip_upload_metadata    | false                                         |
| skip_upload_images      | false                                         |
| skip_upload_screenshots | false                                         |
| validate_only           | false                                         |
| check_superseded_tracks | false                                         |
| timeout                 | 300                                           |
| deactivate_on_promote   | true                                          |
+-------------------------+-----------------------------------------------+

+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | android          |
| PLATFORM_NAME    | android          |
| LANE_NAME        | android internal |
+------------------+------------------+
[13:02:58]: Unauthorized

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 💥   | upload_to_play_store | 1           |
+------+----------------------+-------------+

[13:02:58]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️   The request could not be completed because:Unauthorized Access
    https://github.com/fastlane/fastlane/issues/14122 [closed] 1 💬
    4 weeks ago

➡️  The request could not be completed because:Unauthorized Access
    https://github.com/fastlane/fastlane/issues/13923 [closed] 8 💬
    3 weeks ago

➡️  [pilot] The transport has been detected as having stalled and has been aborted.
    https://github.com/fastlane/fastlane/issues/13768 [closed] 8 💬
    3 weeks ago

and 76 more at: https://github.com/fastlane/fastlane/search?q=Unauthorized&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/user1/.gem/bin/fastlane)
Google::Apis::AuthorizationError: [!] Unauthorized
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:212:in `check_status'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/api_command.rb:118:in `check_status'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:183:in `process_response'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:299:in `execute_once'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
  /Users/user1/.gem/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  /Users/user1/.gem/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  /Users/user1/.gem/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'
  /Users/user1/.gem/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  /Users/user1/.gem/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  /Users/user1/.gem/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'
  /Users/user1/.gem/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
  /Users/user1/.gem/gems/google-api-client-0.23.9/generated/google/apis/androidpublisher_v2/service.rb:200:in `insert_edit'
  /Users/user1/.gem/gems/fastlane-2.116.0/supply/lib/supply/client.rb:133:in `block in begin_edit'
  /Users/user1/.gem/gems/fastlane-2.116.0/supply/lib/supply/client.rb:69:in `call_google_api'
  /Users/user1/.gem/gems/fastlane-2.116.0/supply/lib/supply/client.rb:133:in `begin_edit'
  /Users/user1/.gem/gems/fastlane-2.116.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:27:in `block (2 levels) in parsing_binding'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/user1/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/user1/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/user1/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/user1/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/user1/.gem/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
  /Users/user1/.gem/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
  /Users/user1/.gem/bin/fastlane:22:in `load'
  /Users/user1/.gem/bin/fastlane:22:in `<top (required)>'
  </pre>
</details>

### Environment

<details>
<table>
  <tr>
    <th>Key</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>OS</td>
    <td>10.14.3</td>
  </tr>
  <tr>
    <td>Ruby</td>
    <td>2.3.7</td>
  </tr>
  <tr>
    <td>Bundler?</td>
    <td>true</td>
  </tr>
  <tr>
    <td>Git</td>
    <td>git version 2.17.2 (Apple Git-113)</td>
  </tr>
  <tr>
    <td>Installation Source</td>
    <td>~/.gem/bin/fastlane</td>
  </tr>
  <tr>
    <td>Host</td>
    <td>Mac OS X 10.14.3 (18D109)</td>
  </tr>
  <tr>
    <td>Ruby Lib Dir</td>
    <td>/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib</td>
  </tr>
  <tr>
    <td>OpenSSL Version</td>
    <td>LibreSSL 2.6.4</td>
  </tr>
  <tr>
    <td>Is contained</td>
    <td>false</td>
  </tr>
  <tr>
    <td>Is homebrew</td>
    <td>false</td>
  </tr>
  <tr>
    <td>Is installed via Fabric.app</td>
    <td>false</td>
  </tr>
  <tr>
    <td>Xcode Path</td>
    <td>/Applications/Xcode.app/Contents/Developer/</td>
  </tr>
  <tr>
    <td>Xcode Version</td>
    <td>10.1</td>
  </tr>
</table>
</details>

### Appfile
```
json_key_file("./fastlane/google_play_api_key.json")
package_name("...")
```

I have the json file that I got following the steps at [Supply setting up](https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply) in that folder.

### Fastfile
```
default_platform(:android)

platform :android do

    desc "Builds the release code"
    lane :buildRelease do
        gradle(task: "assembleRelease")
    end

    desc "Submit a new Internal Build to Play Store"
    lane :internal do
        upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/release/app-release.apk')
    end

    desc "Promote Internal to Alpha"
    lane :promote_internal_to_alpha do
        upload_to_play_store(
            track: "internal",
            track_promote_to: "alpha"
        )
    end

    desc "Promote Alpha to Beta"
    lane :promote_alpha_to_beta do
        upload_to_play_store(
            track: "alpha",
            track_promote_to: "beta"
        )
    end

end
```

**Comment by scorpion35** [comment]
Does your service account have at least `Release Manager` access in Google Play Developer Console?

**Comment by iammatis** [comment]
@scorpion35 Yes, there is an account created with Release manager permissions, but that account is never mentioned in the fastlane files, nor in the google api key json file, or is it ? Or do I have to put that account's email address somewhere ?

**Comment by scorpion35** [comment]
Can you check if your json works with the following cmd - 

`fastlane supply init -m android -p "<your_bundleid>" -j "<your_json>"`

(The cmd downloads metadata for your app into `$PWD\android`)

**Comment by iammatis** [comment]
No, I get the same error `Google::Apis::AuthorizationError: [!] Unauthorized`.

**Comment by scorpion35** [comment]
I would redo the JSON then. 

My JSON file has these accesses -
Google Cloud console -> `Editor`
Google play -> `Release Manager`

**Comment by kbrandwijk** [comment]
I'm having this issue too, but in my case, executing the 'long' command, `fastlane supply init -m android -p "<your_bundleid>" -j "<your_json>"` that @scorpion35 suggested does work, that's why I'm hijacking this thread.

I have both `package_name(...)` and `json_key_file(...)` in my Appfile

**Comment by iammatis** [comment]
We solved it, we understood it wrong and assigned a new email account to the permissions not the address of the service account. Both `supply init` and `upload_to_play_store` are now working, thanks!

**Comment by awgeorge** [comment]
Same issue - following @scorpion35 advice, after setting the correct permissions, all good.

**Comment by nikolas7892** [comment]
+1

**Comment by gedeagas** [comment]
i facing the same problem :(

**Comment by scorpion35** [comment]
:wave: 

Did you try debugging your permissions, and service json file?
