### ISSUE TITLE
Fastlane Pilot should ensure that the selected build version matches the active version

### ISSUE THREAD

**Issue by bvirlet** [fastlane/fastlane#14265]
### Feature Request

It's currently possible to assign a TestFlight build for review with a different version number than the public version number.

For instance:
0. I publish a TestFlight 5.0 build (build 5555)
1. I publish a TestFlight 5.1 build (build 6666)
2. I create a 5.0 version on the App Store
3. I can select build 6666 and publish it under version 5.0 

#### Motivation Behind Feature

This behavior isn't desirable because it can lead to releasing a future version early. In the example above, version 5.1 was just meant to be tested in private beta, but ended up being published by mistake.

#### Feature Description

Pilot should check that the version of the selected build matches the version of the app submitted for review.

#### Alternatives or Workarounds
Currently I don't have a good workaround. I was thinking of using `fastlane pilot builds` to least existing builds and create a deliver command with the correct version number but this pilot subcommand isn't exposed to Ruby. If this subcommand was exposed to Ruby, it would be a good workaround.

**Comment by janpio** [comment]
What should happen if the versions do _not_ match?

Just to make sure I really understand:
What command or action would you use for step 3? What params would it have?

**Comment by bvirlet** [comment]
I @janpio. Thanks for your reply.

If versions do not match, I believe fastlane deliver should fail with an error message.
I would have expected it to be the default behavior of `deliver` when `build_number` is specified.

Eg.
```
# Build Number 3333 has bundle version 5.0
deliver(build_number: 3333, app_version: 5.0) # OK

# Build Number 3334 has bundle version 5.0
deliver(build_number: 3334, app_version: 5.1) # Error

# Build Number 3334 has bundle version 5.0
# App store version "prepare for upload" is 5.0
deliver(build_number: 3334) # OK

# Build Number 3334 has bundle version 5.0
# App store version "prepare for upload" is 5.1
deliver(build_number: 3334) # Error
```

If there are some scenarios where it would be acceptable, then `deliver` could have a flag `--force-despite-mismatching-version`.
