### ISSUE TITLE
Supply - download screenshots

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#14271]
I am wondering about screenshots for Android. Currently `supply` only downloads `IMAGES_TYPES` from **[supply.rb](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply.rb#L18)**

If I use/extend the same code for `supply.rb/SCREENSHOT_TYPES`, it's downloading screenshots too! (Need to implement some more logic to name the screenshots)

`SCREENSHOT_TYPES` downloaded are compressed as well.

![screen shot 2019-02-19 at 4 42 44 pm](https://user-images.githubusercontent.com/18679225/53049618-876e3a00-3465-11e9-9f15-282f0427a08b.png)
(^ testing code)

However, I've noticed this [comment](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/setup.rb#L46) - 
```ruby
# We cannot download existing screenshots as they are compressed
# But we can at least download the images
```

What do you think about downloading screenshots as well? I mean, whatever is downloaded is compressed anyway :)

**Comment by janpio** [comment]
If you can get the screenshots as well, that would be really awesome. Seems this didn't work in the past, but if you can make it work, we would sure love to accept a PR adding that functionality. 🚀

**Comment by scorpion35** [comment]
Awesome! I will get back soon, have some final touches. It adds a dependency on https://github.com/minimagick/minimagick. I hope that is fine :)

I am open to any feedback/suggestions once I get the PR in!

**Comment by janpio** [comment]
Oh, we already have that for frameit and all the other places where we work with images. Make sure to use the same lib and version as those and you are fine.

**Comment by scorpion35** [comment]
Oh cool, I will look into that. Thank you for the tip!

**Comment by scorpion35** [comment]
Submitted the PR! https://github.com/fastlane/fastlane/pull/14322

Please take a look and let me know if you have any questions or feedback :)

Also, CLA started to harass me again :D

**Comment by scorpion35** [comment]
More discussion in https://github.com/fastlane/fastlane/pull/14322

**Comment by scorpion35** [comment]
Think these changes would benefit everyone, hopeful these will be merged soon.

janpio, let me know if you need anything else from me!

**Comment by scorpion35** [comment]
No closing please!

**Comment by rogerluan** [comment]
Closing this stale PR as https://github.com/fastlane/fastlane/pull/15269 got merged and released a long time ago 😊
