### ISSUE TITLE
setup_ci

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14279]
We have `setup_travis` and `setup_circle` which are doing almost the same thing, so we should probably just have a `setup_ci` and the other two can become aliases to that.

**Comment by mollyIV** [comment]
Nice idea @janpio 💪 I had a look at the code and there's quite a difference in terms of setting environment variables 😬 `setup_circle_ci` sets a bunch of envs that `setup_travis` does not:

```ruby
root = Pathname.new(ENV["FL_OUTPUT_DIR"])
ENV["SCAN_OUTPUT_DIRECTORY"] = (root + "scan").to_s
ENV["GYM_OUTPUT_DIRECTORY"] = (root + "gym").to_s
ENV["FL_BUILDLOG_PATH"] = (root + "buildlogs").to_s
ENV["SCAN_INCLUDE_SIMULATOR_LOGS"] = true.to_s
```

I guess would be nothing wrong in unifying those, right? By making a single `setup_ci`, travis would just expose those envs as well 🤷‍♂️

**Comment by janpio** [comment]
Yes, although it might be worth understanding more why those exist (by looking at when and how they were added).

My guess was that `setup_travis` or `setup_circle` also sets some CI provider specific values, which possibly has to be handled. If this is the case `setup_ci` could have a `provider` param to handle that.

**Comment by mollyIV** [comment]
I did a bit more research on the usage of ENV variables in `setup_travis` and `setup_circle` actions. 

According to the `circleci` [docs](https://circleci.com/docs/2.0/testing-ios/#example-configuration-for-using-fastlane-on-circleci): 

> The environment variable FL_OUTPUT_DIR is the artifact directory where FastLane logs should be stored. Use this to set the path in the store_artifacts step to automatically save logs such as Gym and Scan.

By settings `FL_OUTPUT_DIR` we can easily collect the logs from `scan` and `gym`. 

Couldn't find the similar ENV variable in `.travis.yml`. 

The common part of `setup_travis` and `setup_circle` actions are two things:
* temporary keychain for use with match
* `readonly` mode for `match` to not create new profiles/cert on CI

Speaking about the technical details, I'd vote for adding `provider` param (subclassing + string defining a type of ci: `travis`, `circleci`? 🤔)  to handle the differences - setting an additional ENV vars by `setup_circle` action.

WDYT?

**Comment by janpio** [comment]
Yes, sounds reasonable. If other CI providers have similar setups, we can add that to `setup_ci` later to customize the experience.

**Comment by mollyIV** [comment]
@janpio I created a [draft pull request](https://github.com/fastlane/fastlane/pull/14346) - would be great if you could have a 👀Thanks! 🙇

**Comment by janpio** [comment]
PR is still work in progress.
