### ISSUE TITLE
[deliver,spaceship] Upload a file attachment to iOS app store submission metadata

### ISSUE THREAD

**Issue by billfeth** [fastlane/fastlane#14285]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I would like to request that fastlane add the ability to upload a file attachment to the deliver metadata that is submitted to the app store for review. With each review, our team must submit a legal document stating that we are permitted to use the content shown in our app. Without this document, reviewers have rejected our app for a "Copycat violation" (pretending to be the "real thing" when an app may not be directly affiliated with the 3rd party content it contains).

##### Complete output when running fastlane, including the stack trace and command used
N/A

### Environment

N/A

**Comment by max-ott** [comment]
Great catch @billfeth Something I'm missing as well. Last time I checked `spaceship` this wasn't implemented, so we have no way to communicate with Apple's servers for this "action". For anyone wondering, where to find this or what the purpose is, here's the screenshot from App Store Connect.

<img width="990" alt="screen shot 2019-02-21 at 10 27 05" src="https://user-images.githubusercontent.com/6481790/53158242-71768b80-35c3-11e9-8107-edd042ef2311.png">

**Comment by janpio** [comment]
Thanks you two.

How could this be added to the API of `deliver`? What would a param be called and how would it be used? Do we alredy "upload a file" anywhere (besides the apps itself of course)?

**Comment by billfeth** [comment]
@max-ott @janpio Thank you for your quick responses.

Deliver already uploads the app icon by specifying a path with the `app_icon` parameter. It might make sense to mimic the `app_icon` API, which expects a path to a single png file. Perhaps Deliver could take an `app_attachment` path in its DeliverFile or as a command-line parameter, which it expects to point to a single file (of any type?).

If you think fastlane users would need to upload more than one file attachment, maybe we could make it so that if you specify a folder instead of a file, Fastlane would then zip the folder contents (not following symlinks) and upload the resulting .zip file as a single attachment.

It might also make sense to have a maximum file size (e.g. 10MB? 100MB? 1GB?) beyond which users would need to upload their file manually through the website, or figure out how to reduce the attachment size.

What do you think?

**Comment by janpio** [comment]
Sounds good, although both the zipping and size limitation actually are optional features we don't really need in a first version (zipping the user can also do manually, as they would have to with the web UI. And fastlane is fine with uploading gigantic files, as long as the web UI accepts them).

Can you go through the process manually and log the HTTP requests (either manually in your browser's dev tools or via a tool like Charles web proxy) that are sent when using the file selector and then submitting the form, so we know which endpoints with which params spaceship has to implement?

**Comment by krish722** [comment]
I got this sample using google chrome. Some data are masked with xx or 33.

POST: https://du-itc.itunes.apple.com/upload/app-resolution-file

Request Header
Accept: application/json, text/plain, */*
Content-Type: text/plain
Origin: https://appstoreconnect.apple.com
Referer: https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1278429203/ios/versioninfo
User-Agent: Mozilla/5.0 .......
X-Apple-Request-UUID: 557axxxx-xxxxx-xxxxx
X-Apple-Upload-AppleId: 1233329203
X-Apple-Upload-ContentProviderId: 118740439
X-Apple-Upload-itctoken: data
X-Apple-Upload-Referrer: https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1233329203/ios/versioninfo
X-Csrf-Itc: itc
X-Original-Filename: readme.txt

Do we need anything else?

**Comment by janpio** [comment]
Implement this in spaceship ;)

@max-ott Can you point out the correct location in the code where this would probably fit in?

**Comment by max-ott** [comment]
@janpio https://github.com/fastlane/fastlane/blob/f5da2837ecf10c48ce8f2516c86c3204490ac80c/spaceship/lib/spaceship/tunes/app_version.rb#L131 is where the `app review` information is currently getting "processed". Only part currently missing is the file upload.

**Comment by janpio** [comment]
Thanks. Maybe the uploaded file has to be added there _after_ it actually uploaded? @krish722 Did you find out if the result of that upload is used anywhere?

From searching for `du-itc` in the code I found https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/du/du_client.rb which seems to the file where those uploads are actually handled. We would have to add the request @krish722 posted above (and see if the current logic matches) and then find out how and where this has to be added (how are the current existing methods used?).

**Comment by billfeth** [comment]
Thank you Krish722!

I was going to try to record these messages this week, and you beat me to
it! Much appreciated!

Let me know if I can be of assistance in testing/debugging.
-Bill


On Mar 4, 2019, at 12:48 AM, krish722 <notifications@github.com> wrote:

I got this sample using google chrome. Some data are masked with xx or 33.

POST: https://du-itc.itunes.apple.com/upload/app-resolution-file

Request Header
Accept: application/json, text/plain, */*
Content-Type: text/plain
Origin: https://appstoreconnect.apple.com
Referer: https://appstoreconnect.apple.com/WebObjects/iTunesConnect.
woa/ra/ng/app/1278429203/ios/versioninfo
User-Agent: Mozilla/5.0 .......
X-Apple-Request-UUID: 557axxxx-xxxxx-xxxxx
X-Apple-Upload-AppleId: 1233329203
X-Apple-Upload-ContentProviderId: 118740439
X-Apple-Upload-itctoken: data
X-Apple-Upload-Referrer: https://appstoreconnect.apple.
com/WebObjects/iTunesConnect.woa/ra/ng/app/1233329203/ios/versioninfo
X-Csrf-Itc: itc
X-Original-Filename: readme.txt

Do we need anything else?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fastlane/fastlane/issues/14285#issuecomment-469137836>,
or mute the thread

**Comment by krish722** [comment]
Created a PR
https://github.com/fastlane/fastlane/pull/14411

**Comment by billfeth** [comment]
Dear Krish722,
Thank you so much for the PR! This is really cool!

I am looking at the patch now, and I’ll see if I can try it out this week.

Thanks again,
-Bill

**Comment by krish722** [comment]
Please refer this PR
https://github.com/fastlane/fastlane/pull/14412

**Comment by billfeth** [comment]
Ok, thank you Krish722. Will do!
-Bill

**Comment by billfeth** [comment]
Thanks for the great effort on this everyone! I just successfully uploaded a file attachment for the first time as part of our build and App Store submission scripts! Thank you, THANK YOU, Krish and all who tested, reviewed, and approved!

**Comment by billfeth** [comment]
Looks like this feature request was a duplicate of #11136 "[Feature] Allow uploading an attachment as part of App Review Information". It's finally implemented, yay!
