### ISSUE TITLE
Rename/Alias `import_certificate` to `import_into_keychain`

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14280]
Our action `import_certificate` could/should correctly be named `import_into_keychain` as it can be used to import both certificates and private keys, with different file formats even, into the keychain.

**Comment by mollyIV** [comment]
Hey 👋 when I first read `import_into_keychain` without more context, I was wondering what you can actually import into the keychain? 🤔 

According to the example from the docs:

```ruby
import_certificate(certificate_path: "certs/AppleWWDRCA.cer")

import_certificate(
            certificate_path: "certs/dist.p12",
            certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
          )
```

we allow to import `.cer` and `.p12` files. From a technical point of view `.p12` can also [contain certificate file](https://en.wikipedia.org/wiki/PKCS_12): 

>  It is commonly used to bundle a private key with its X.509 certificate or to bundle all the members of a chain of trust.

So taking that into account, I guess `import_certificate` makes sense. 

I looked at the `keychain_importer.rb` class and under the hood we call [`security import ...` command](https://ss64.com/osx/security-export.html). According to the docs we can import following file types:

```bash
Import types are: cert, pub, priv, session, cert, and agg. Pub, priv, and session refer to keys; agg is one of the aggregate types (pkcs12 and PEM sequence).
```

If we'd like to support all of the above files, then I think we could indeed rename the lane to `import_file_into_keychain` or something like that - more general name than `import_certificate`. 

WDYT? 🤔

**Comment by janpio** [comment]
Yeah, I have no idea of all that iOS stuff 🙊 

@joshdholtz told me the same thing yesterday, that the `.p12` of only the key is also a certificate and that the certificate can (and is!) exported as a `.p12` file - which just shows how confusing this all is.

`keychain_importer` probably already supports all those files, and as `security import` is described as "Import one or more items from inputfile into a keychain. If keychain isn't provided, items will be imported into the user's default keychain." the new naming would be correct, right?

**Comment by mollyIV** [comment]
Yes @janpio, I think the new name would still be correct 👍 Maybe I was just missing the context, because let's have a look at the example of calling the lane:

```ruby
import_into_keychain(
    certificate_path: "certs/dist.p12",
    certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
)
```

it is clear what do we import into the keychain 💪

**Comment by janpio** [comment]
The confusing thing is, that you actually also use `certificate_path` when importing a private key (as it is included in a certificate as well I guess).

**Comment by mollyIV** [comment]
You think we should also rename the params? What about compatibility breaking changes? 🤔

```ruby
import_into_keychain(
    inputfile: "certs/dist.p12",
    passphrase: ENV["CERTIFICATE_PASSWORD"] || "default"
)
```

**Comment by janpio** [comment]
Ugh, interesting idea. (although `inputfile` would probably not be my choice)
If we keep `import_certificate` as it was before, this would not really be a problem.

**Comment by mollyIV** [comment]
Hmm, not sure I get it 🤔 @janpio could you please write down what API you have in mind (the code snippet would do)? 🙂

**Comment by janpio** [comment]
`import_certificate` stays as it is, we add an alias `import_into_keychain` that has improved parameter names (TBD).

**Comment by mollyIV** [comment]
`import_into_keychain` alias sounds good 👍 Let's talk about parameters name then. Below I listed all of the params from [the documentation](https://docs.fastlane.tools/actions/import_certificate/#parameters) and I'd like to propose a new naming: 

```ruby
keychain_name ✅
keychain_path ✅
keychain_password ✅
certificate_path --> file_path 🤔
certificate_password --> passphrase 🤔
log_output ✅
```

**Comment by janpio** [comment]
Didn't we have a PR about this @mollyIV?

**Comment by mollyIV** [comment]
@janpio I think we didn't 🤔 I think we were discussing  parameter names: https://github.com/fastlane/fastlane/issues/14280#issuecomment-466742530. 

Once we agree on the new naming, I will prepare PR 🙌
