### ISSUE TITLE
Transporter is slow and gives no progress

### ISSUE THREAD

**Issue by paiv** [fastlane/fastlane#14282]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm experiencing slow transporter uploads, while on different networks, for at least 6 months now.
Xcode uploads are 5-10 minutes.

It sits on this line:
```
[18:39:18]: Going to upload updated app to App Store Connect
[18:39:18]: This might take a few minutes. Please don't interrupt the script.
```
... and reports no progress.

Last successful upload took **2 hours**.

The latest upload failed with
```
[18:39:18]: This might take a few minutes. Please don't interrupt the script.
[19:03:13]: [Transporter Error Output]: An error occurred while uploading the package: abcdef.itmsp.
[19:03:13]: [Transporter Error Output]: An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
[19:03:16]: Transporter transfer failed.
```

Is this a common issue?
Why is it so slower than Xcode upload?
What might be the cause?
Could it be improved with new apis #12713 ?
Can transporter give more info/ upload progress?

##### Command executed

```
fastlane ios qa
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | 10.13.6                                                |
| Ruby                        | 2.2.10                                                 |
| Bundler?                    | true                                                   |
| Git                         | git version 2.16.3                                     |
| Installation Source         |                                                        |
| Host                        | Mac OS X 10.13.6 (17G5019)                             |
| Ruby Lib Dir                | /opt/local/lib                                         |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/            |
| Xcode Version               | 10.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform :ios

code_path = File.expand_path('..', File.dirname(__FILE__))
build_path = "#{code_path}/build" 
cert_path = "#{code_path}/certs"
workspace_path = "#{code_path}/some.xcworkspace"
project_path = "#{code_path}/some.xcodeproj"

platform :ios do
  
  lane :qa do
    scheme = 'some-QA'
    
    ensure_git_status_clean()
        
    get_certificates(output_path: cert_path)
    get_provisioning_profile(output_path: cert_path)
    
    build_app(workspace: workspace_path, scheme: scheme, output_directory: build_path,
      clean: true)
    
    upload_to_testflight(changelog: "changelog", wait_for_uploaded_build: true)
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| bundler                    | 1.16.1       |
| CFPropertyList             | 3.0.0        |
| concurrent-ruby            | 1.1.4        |
| i18n                       | 0.9.5        |
| minitest                   | 5.11.3       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.5        |
| activesupport              | 4.2.11       |
| public_suffix              | 2.0.5        |
| addressable                | 2.6.0        |
| atomos                     | 0.1.3        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| fuzzy_match                | 2.0.4        |
| nap                        | 1.1.0        |
| cocoapods-core             | 1.6.0        |
| cocoapods-deintegrate      | 1.0.2        |
| cocoapods-downloader       | 1.2.2        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.1.0        |
| netrc                      | 0.11.0       |
| cocoapods-trunk            | 1.3.1        |
| cocoapods-try              | 1.1.0        |
| colored2                   | 3.1.2        |
| escape                     | 0.0.4        |
| fourflusher                | 2.2.0        |
| gh_inspector               | 1.1.3        |
| molinillo                  | 0.6.6        |
| ruby-macho                 | 1.3.1        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.8.1        |
| cocoapods                  | 1.6.0        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| digest-crc                 | 0.4.1        |
| unf_ext                    | 0.0.7.5      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| dotenv                     | 2.6.0        |
| emoji_regex                | 1.0.1        |
| excon                      | 0.62.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.15.4       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.5        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| multi_json                 | 1.13.1       |
| os                         | 1.0.0        |
| signet                     | 0.11.0       |
| googleauth                 | 0.6.7        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2018.0812  |
| mime-types                 | 3.2.2        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.23.9       |
| google-cloud-env           | 1.0.5        |
| google-cloud-core          | 1.3.0        |
| google-cloud-storage       | 1.16.0       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.5.0        |
| rubyzip                    | 1.2.2        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.5        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.4.1        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.6.5        |
| tty-cursor                 | 0.6.0        |
| tty-spinner                | 0.9.0        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-versioning | 0.3.4        |
</details>

*generated on:* **2019-02-20**
</details>

**Comment by paiv** [comment]
Thanks to #14254 I've discovered `--verbose`

Current progress:
```
DEBUG [2019-02-20 20:59:46.18]: [Transporter]: INFO: Starting upload of file: /var/folders/cg/1mdfwy594255f6pv45ccxpsw0000gn/T/d20190220-78022-16ozauj/1367150228.itmsp/4781634efc19ed937759a60f8dd0e229bc11b982c9adaf21733bbfca885a1575.ipa ...
DEBUG [2019-02-20 21:04:34.35]: [Transporter]: INFO:      File: 4781634efc19ed937759a60f8dd0e229bc11b982c9adaf21733bbfca885a1575.ipa 10485760/194388116, 5% completed
DEBUG [2019-02-20 21:10:35.82]: [Transporter]: INFO:      File: 4781634efc19ed937759a60f8dd0e229bc11b982c9adaf21733bbfca885a1575.ipa 20971520/194388116, 10% completed
DEBUG [2019-02-20 21:20:28.09]: [Transporter]: INFO:      File: 4781634efc19ed937759a60f8dd0e229bc11b982c9adaf21733bbfca885a1575.ipa 31457280/194388116, 16% completed
```

**Comment by paiv** [comment]
I guess I have to move to [altool](https://help.apple.com/itc/apploader/#/apdATD1E53-D1E1A1303-D1E53A1126):

```
$ time xcrun altool --upload-app -f 'some.ipa'
2019-02-20 22:29:48.658 altool[96107:28250454] No errors uploading 'some.ipa'

real	4m31.005s
user	1m18.234s
sys	0m37.142s
```

#2166
https://github.com/fastlane/fastlane/issues/11865#issuecomment-367090573

It should be a (default) option in `upload_to_testflight`

**Comment by janpio** [comment]
There is a plugin for altool at https://github.com/XCTEQ/fastlane-plugin-altool that you can use.

In general using iTunes Transporter is pretty stable for most people, for some it seems to be problematic. Reason is probably the strange way it connects to these upload providers and uploads the data to them.

**Comment by paiv** [comment]
`fastlane-plugin-altool` is a mere wrapper, not even using credentials manager.
`transporter` is hard-coded into `pilot`, and `fastlane-plugin-altool` is not a replacement for `pilot`. So your suggestion could not be easily applied. To use `altool` one would have to write proper plugin, and patch `pilot`

> Transporter is pretty stable for most people
It is not for me, and I feel sorry for other people that have to walk this path.

**Comment by paiv** [comment]
Link with #14342 #14353

**Comment by naftalibeder** [comment]
For anyone having this issue, [this solution](https://stackoverflow.com/questions/22443425/application-loader-stuck-at-authenticating-with-the-itunes-store-when-uploadin/43695235#43695235) worked for me:

1. Delete the file `~/.itmstransporter`.
2. Run `/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter` to regenerate that file.
3. Retry the upload.

**Comment by paiv** [comment]
@naftalibeder You should have mentioned here that your "solution" is not working for you. #14838 #14993

To debug this, run `fastlane --verbose` and check iTMSTransporter output.

**Comment by naftalibeder** [comment]
@paiv is correct, my mistake. My above suggested solution does not work - it was just coincidence that the transporter started working again when I tried that fix.
