### ISSUE TITLE
Crash when trying to add already existing device with `register_devices` action

### ISSUE THREAD

**Issue by brad** [fastlane/fastlane#1429]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running the `register_devices` action with a device that already exists, the process crashes. It worked great once (when the device did not yet exist) but fails on subsequent runs. I have confirmed that I have [this fix](https://github.com/fastlane/spaceship/commit/15cee8e2b801e31eabf4e916b6fd0c8cea0a4a5a)
##### Complete output when running fastlane, including the stack trace and command used

The relevant portion of the crash log
```
"message": "Spaceship::Client::UnexpectedResponse: {\"responseId\"=>\"3f23088b-a114-4317-9f76-b6b21870cc24\", \"resultCode\"=>35, \"resultString\"=>\"There were errors in the data supplied. Please correct and re-submit.\", \"userString\"=>\"A device with number 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' already exists on this team.\", \"creationTimestamp\"=>\"2016-02-27T02:36:22Z\", \"protocolVersion\"=>\"QH65B2\", \"requestId\"=>nil, \"userLocale\"=>\"en_US\", \"requestUrl\"=>\"https://developerservices2.apple.com/services/QH65B2/ios/addDevice.action\", \"httpCode\"=>200, \"validationMessages\"=>nil}"

"culprit": "spaceship/client.rb in parse_response at line 300",

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
    register_devices(
      devices_file: './fastlane/devices.txt'
    )
```

devices.txt:
```
Device ID	Device Name
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX	Bilbo Baggins' iPhone
```

### Environment

fastlane version (fastlane -v): 1.63.1
Do you use bundler, rbenv or rvm? No

**Comment by ohwutup** [comment]
Hey @brad, I am not able to reproduce this on my own machine with my own dev account. Can you verify that you are using `spaceship` version `0.21.1`? You can do this with `gem list spaceship`. Thank you! :rabbit:

**Comment by brad** [comment]
Hmm, I had 0.21.0. After updating to 0.21.1 I still have the same error.

**Comment by brad** [comment]
@ohwutup I placed some debug `puts` statements in the `find_by_udid` method and found that there was no match because the UDIDs from Apple were all lowercase whereas the UDID in my `devices.txt` is all UPPERCASE. After changing the case in `devices.txt` everything works fine :smile: 

Perhaps it would be a good idea to make the comparison case-insensitive since the `register_devices` docs use lowercase UDIDs but the [example devices](https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip) linked to by the docs are all UPPERCASE.

**Comment by ohwutup** [comment]
Ah, thanks for checking that out! We ill update that for sure. Thanks!

**Comment by ohwutup** [comment]
https://github.com/fastlane/spaceship/pull/266
