### ISSUE TITLE
first time run fastlane init

### ISSUE THREAD

**Issue by yuzhidi** [fastlane/fastlane#14297]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

$ fastlane init
/Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:482:in `rescue in eval_gemspec':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `fastlane.gemspec`: uninitialized constant Fastlane::RUBOCOP_REQUIREMENT. Bundler cannot continue.

 #  from /Users/wangliang/Study/fastlane/fastlane.gemspec:113
 #  -------------------------------------------
 #    spec.add_development_dependency('coveralls', '~> 0.8.13')
 >    spec.add_development_dependency('rubocop', Fastlane::RUBOCOP_REQUIREMENT)
 #    spec.add_development_dependency('rubocop-require_tools', '>= 0.1.2')
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /Users/wangliang/Study/fastlane/Gemfile:8
 #  -------------------------------------------
 #
 >  gemspec(path: ".")
 #
 #  -------------------------------------------
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:474:in `eval_gemspec'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:422:in `block in load_gemspec_uncached'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/shared_helpers.rb:55:in `chdir'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/shared_helpers.rb:55:in `block in chdir'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/shared_helpers.rb:54:in `chdir'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:417:in `load_gemspec_uncached'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:407:in `load_gemspec'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:60:in `block in gemspec'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:60:in `map'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:60:in `gemspec'
	from /Users/wangliang/Study/fastlane/Gemfile:8:in `eval_gemfile'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:41:in `instance_eval'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:41:in `eval_gemfile'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:11:in `evaluate'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/plugins/plugin_manager.rb:57:in `available_gems'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/plugins/plugin_manager.rb:64:in `available_plugins'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/plugins/plugin_manager.rb:270:in `load_plugins'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:39:in `start'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/wangliang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
	from /Users/wangliang/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/wangliang/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by janpio** [comment]
How did you install fastlane?
What is you `fastlane env` output?
