### ISSUE TITLE
How to submit the "What to Test" by fastlane deliver?

### ISSUE THREAD

**Issue by a295053193** [fastlane/fastlane#14299]
### Feature Request
fastlane deliver cann't  submit the  "What to Test" to testflight.
This field is very important for our testers to know what has been changed and should be tested in the new beta build.

**Comment by janpio** [comment]
Do you mean `pilot` or `upload_to_testflight`? How are you uploading things to Testflight with `deliver`?

**Comment by mollyIV** [comment]
[`deliver`](https://docs.fastlane.tools/actions/deliver/) seems to not support uploading builds to TestFlight:

> To upload builds to TestFlight check out [pilot](https://docs.fastlane.tools/actions/pilot/).

The easiest way to upload the application to TestFlight is to do it via `pilot`. According to [the documentation](https://docs.fastlane.tools/actions/testflight/#parameters) you can set a `changelog` parameter to add your text to "What to Test" section on TestFlight:

> changelog | Provide the 'what's new' text when uploading a new build

```ruby
upload_to_testflight(
  changelog: "Something that is new here"
)
```

Both `pilot` and `testflight` are aliases for `upload_to_testflight` action. 

You can find more examples on [the documentation page](https://docs.fastlane.tools/actions/pilot/#5-examples) 🙇

**Comment by a295053193** [comment]
I finished it by pilot changelog.  but I found that pilot upload is very slower than deliver. Do you meet the same issue?

**Comment by janpio** [comment]
If there is a problem with `pilot`'s upload being slow, please open a new issue and describe the problem so we can look into that and fix it.

**Comment by lemonkey** [comment]
Pilot might seem slow because it has to wait until the build has finished processing before it can post the change log details...

**Comment by denismullaraj** [comment]
> [`deliver`](https://docs.fastlane.tools/actions/deliver/) seems to not support uploading builds to TestFlight:
> 
> > To upload builds to TestFlight check out [pilot](https://docs.fastlane.tools/actions/pilot/).
> 
> The easiest way to upload the application to TestFlight is to do it via `pilot`. According to [the documentation](https://docs.fastlane.tools/actions/testflight/#parameters) you can set a `changelog` parameter to add your text to "What to Test" section on TestFlight:
> 
> > changelog | Provide the 'what's new' text when uploading a new build
> 
> ```ruby
> upload_to_testflight(
>   changelog: "Something that is new here"
> )
> ```
> 
> Both `pilot` and `testflight` are aliases for `upload_to_testflight` action.
> 
> You can find more examples on [the documentation page](https://docs.fastlane.tools/actions/pilot/#5-examples) 🙇

@mollyIV Can I do this?
```
changelog_from_git_commits(commits_count: 20, merge_commit_filtering: "exclude_merges")
upload_to_testflight
```

Or do I have to do it like this?
```
changes = changelog_from_git_commits(commits_count: 20, merge_commit_filtering: "exclude_merges")
upload_to_testflight(changelog: changes)
```

**Comment by mollyIV** [comment]
👋 @denismullaraj , 

Actually both should work 🙂 

`changelog_from_git_commits` lane saves changelog in [`lane_context`](https://docs.fastlane.tools/actions/lane_context/):

https://github.com/fastlane/fastlane/blob/46dea0dabd915525c2e43ac5e8c5b6b9ba2e23b4/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L46

If you do not specify `changelog` parameter for `upload_to_testflight` lane, the lane will try to get a value from `lane_context`:

https://github.com/fastlane/fastlane/blob/46dea0dabd915525c2e43ac5e8c5b6b9ba2e23b4/fastlane/lib/fastlane/actions/upload_to_testflight.rb#L8-L9

which is available as the output from `changelog_from_git_commits` 👍 

You can read more about `SharedValues` [here](https://github.com/fastlane/fastlane/issues/14255).

Cheers 🦁

**Comment by denismullaraj** [comment]
> 👋 @denismullaraj ,
> 
> Actually both should work 🙂
> 
> `changelog_from_git_commits` lane saves changelog in [`lane_context`](https://docs.fastlane.tools/actions/lane_context/):
> 
> https://github.com/fastlane/fastlane/blob/46dea0dabd915525c2e43ac5e8c5b6b9ba2e23b4/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L46
> 
> If you do not specify `changelog` parameter for `upload_to_testflight` lane, the lane will try to get a value from `lane_context`:
> 
> https://github.com/fastlane/fastlane/blob/46dea0dabd915525c2e43ac5e8c5b6b9ba2e23b4/fastlane/lib/fastlane/actions/upload_to_testflight.rb#L8-L9
> 
> which is available as the output from `changelog_from_git_commits` 👍
> 
> You can read more about `SharedValues` [here](https://github.com/fastlane/fastlane/issues/14255).
> 
> Cheers 🦁

So in both cases:

- changes = changelog_from_git_commits(commits_count: 20, merge_commit_filtering: "exclude_merges")

- changelog_from_git_commits(commits_count: 20, merge_commit_filtering: "exclude_merges")

If I do not specify a `changelog` parameter in `upload_to_testflight` than it will use the `changelog_from_git_commits(...)` right? Or just in the second case when it's not assigned the result to a variable?

Thanks @mollyIV

**Comment by mollyIV** [comment]
### Solution 1

```ruby
changelog_from_git_commits(commits_count: 20, merge_commit_filtering: "exclude_merges")
upload_to_testflight
```

☝️ `upload_to_testflight` will use `Actions.lane_context[SharedValues::FL_CHANGELOG]` under the hood (the value of it is provided by `changelog_from_git_commits` output)

### Solution 2

```ruby
changes = changelog_from_git_commits(commits_count: 20, merge_commit_filtering: "exclude_merges")
upload_to_testflight(changelog: changes)
```

☝️ will use `changes` value, **not** `Actions.lane_context[SharedValues::FL_CHANGELOG]`.

**Comment by denismullaraj** [comment]
@mollyIV Thank you so much!
