### ISSUE TITLE
How do I create a release note for each language on the command line?

### ISSUE THREAD

**Issue by sesangsokuro** [fastlane/fastlane#14296]
### Question Checklist

#7016 

How do I create a release note for each language on the command line?

#### Question Description

I recently updated fastlane, and suddenly I get an error telling me to write the release notes in the correct language. How can I fix this?

I do not want to write a file. In the past, the command line option -release_note was enough, but why does not it support command line option and force file creation?

**Comment by janpio** [comment]
Please provide more information. What command are you executing? What are you inputting where and how? What error message are you getting?
