### ISSUE TITLE
[Swift] Output to console

### ISSUE THREAD

**Issue by kelvinlauKL** [fastlane/fastlane#14298]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

According to #11537, you should be able to print to the console by using `puts`. However, it isn't working.

#### Question Description

In my `Fastfile.swift`, I have the following:

```
class Fastfile: LaneFile {
  func createLane(withOptions options: [String: String]?) {
    puts("hi")
  }
}
```

I'm expecting to see "hi" as the output in the console. However, running `fastlane create` all I get is:

```
[✔] 🚀 
[00:27:11]: loading manifest: /Users/kelvinlau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.116.1/fastlane/swift/upgrade_manifest.json
[00:27:11]: FastlaneSwiftRunner project is up-to-date
[00:27:11]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[00:27:12]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/kelvinlau/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[00:27:15]: $ ./fastlane/FastlaneRunner lane create swiftServerPort 2000 > /dev/null
[00:27:15]: fastlane.tools finished successfully 🎉
```

## Fastlane env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.3.7                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rbenv/versions/2.3.7/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.7/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

final class Fastfile: LaneFile {

    func createLane(withOptions options: [String: String]?) {
        puts("hi")
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.6       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.5        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| unicode-display_width     | 1.4.1        |
| addressable               | 2.6.0        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| jwt                       | 2.1.0        |
| os                        | 1.0.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-02-22**
</details>

**Comment by mollyIV** [comment]
Hey @kelvinlauKL  👋 

The thing is you used incorrect method to print something out to the console 😬

![image](https://user-images.githubusercontent.com/10795657/53549521-a8edb680-3b34-11e9-9e50-bb3b63bf9cf4.png)

Please try this out:

```Swift
class Fastfile: LaneFile {
    func customLane() {
        puts(message: "hi ☺️")
    }
}
```
![image](https://user-images.githubusercontent.com/10795657/53549563-c91d7580-3b34-11e9-9f3c-fdf3fe86e6ca.png)

It's quite easy to miss that out, so maybe as the future improvement you could tweak the name of the method? 🤔
