### ISSUE TITLE
[screengrab] More screenshots than expected are getting taken

### ISSUE THREAD

**Issue by carstenhag** [fastlane/fastlane#14308]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
4 Screenshots are getting taken instead of 2. I have called `Screengrab.screenshot()` only twice in my Test.

I think this is related to #14307. Likely screengrab is taking 2 screenshots for each locale, but as it doesn't change locals, it creates 4 for de-DE.

##### Command executed
`fastlane screenshots`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
Screengrabfile:

locales ['en-US', 'de-DE']
ending_locale 'de-DE'
clear_previous_screenshots true

use_tests_in_packages = 'de.chagemann.regexcrossword.screenshots'

tests_apk_path 'app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
app_apk_path 'app/build/outputs/apk/debug/app-debug.apk'

test_instrumentation_runner 'androidx.test.runner.AndroidJUnitRunner'

</pre>
</details>

<details>
  <pre>
package de.chagemann.regexcrossword.screenshots

// imports

@Suppress("BooleanLiteralArgument")
@RunWith(AndroidJUnit4::class)
class ScreenshotTest {

    @get:Rule
    var activityRule =
            ActivityTestRule(CategoryActivity_::class.java, false, false)

    @Test
    fun testTakeScreenshot() {

        activityRule.launchActivity(null)
        Screengrab.setDefaultScreenshotStrategy(UiAutomatorScreenshotStrategy())

        Screengrab.screenshot("select-category")

        onView(
                withId(R.id.categoryRecyclerView)
        ).perform(RecyclerViewActions.actionOnItemAtPosition<CategoryAdapter.ViewHolder>(0, click()))

        Screengrab.screenshot("select-level")
    }

    companion object {

        @get:ClassRule
        val localeTestRule = LocaleTestRule()
    }
}

</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.19.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  lane :screenshots do
    capture_android_screenshots
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("playstoreapi.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("de.chagemann.regexcrossword") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 3.0.0        |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.6.0        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.7.1        |
| dotenv                    | 2.2.0        |
| emoji_regex               | 1.0.1        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.5        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.16.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.10       |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2018.0812  |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.13.1       |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 1.0.0        |
| os                        | 0.9.6        |
| plist                     | 3.5.0        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.1.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.4.1        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.8.1        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2019-02-25**
</details></pre>
</details>

**Comment by carstenhag** [comment]
I've thought this was due to the device only showing one language in the languages tab, so I've added two more like this:
![](https://i.imgur.com/HfI7nlt.png)

So yeah, still broken with that. Generates 4 screenshots with en-US locale, instead of 2 for de-DE and 2 for en-US.

**Comment by janpio** [comment]
> I have called `Screengrab.screenshot()` only twice in my Test.

+

> `locales ['en-US', 'de-DE']`

Makes 4 screenshots.

If your app isn't changing locales, this doesn't make the behavior of 4 screenshots getting taken a bug - your app not changing locales is the problem.

Or did I misunderstand something?

**Comment by carstenhag** [comment]
Console output says this (sorry, had not included it yet). First it says `Running tests for locale: de-DE` and it takes screenshots. Then it says changing to en-US and it takes screenshots, but without having changed locales.

Note: I have changed my test. Expected screenshot amount per locale is now 4, actual screenshot amount for de-DE is 8.

```
+-----------------------------+--------------------------------------+
|                   Summary for screengrab 2.116.1                   |
+-----------------------------+--------------------------------------+
| tests_package_name          | de.chagemann.regexcrossword.test     |
| android_home                | /Users/chag0709/Library/Android/sdk  |
| locales                     | ["en-US", "de-DE"]                   |
| clear_previous_screenshots  | true                                 |
| output_directory            | fastlane/metadata/android            |
| skip_open_summary           | false                                |
| app_package_name            | de.chagemann.regexcrossword          |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRu  |
|                             | nner                                 |
| ending_locale               | de-DE                                |
| app_apk_path                | app/build/outputs/apk/debug/app-deb  |
|                             | ug.apk                               |
| tests_apk_path              | app/build/outputs/apk/androidTest/d  |
|                             | ebug/app-debug-androidTest.apk       |
| device_type                 | phone                                |
| exit_on_test_failure        | true                                 |
| reinstall_app               | false                                |
+-----------------------------+--------------------------------------+

[18:08:02]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[18:08:02]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[18:08:02]: Clearing phoneScreenshots within fastlane/metadata/android
[18:08:02]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb devices -l
[18:08:02]: ▸ List of devices attached
[18:08:02]: ▸ 192.168.2.159:5555     device product:OnePlus5 model:ONEPLUS_A5000 device:OnePlus5 transport_id:3
[18:08:02]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell echo \$EXTERNAL_STORAGE
[18:08:02]: ▸ /sdcard
[18:08:02]: Cleaning screenshots on device
ls: /sdcard/de.chagemann.regexcrossword/screengrab: No such file or directory
[18:08:02]: Exit status: 1
ls: /data/data/de.chagemann.regexcrossword/app_screengrab: No such file or directory
[18:08:02]: Exit status: 1
[18:08:02]: Validating app APK
[18:08:02]: $ /Users/chag0709/Library/Android/sdk/build-tools/28.0.3/aapt dump permissions app/build/outputs/apk/debug/app-debug.apk
[18:08:02]: ▸ package: de.chagemann.regexcrossword
[18:08:02]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[18:08:02]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[18:08:02]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[18:08:02]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[18:08:02]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[18:08:02]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[18:08:02]: Installing app APK
[18:08:02]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 install -t -r app/build/outputs/apk/debug/app-debug.apk
[18:08:07]: ▸ Success
[18:08:07]: Installing tests APK
[18:08:07]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 install -t -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[18:08:12]: ▸ Success
[18:08:12]: Granting the permission necessary to change locales on the device
[18:08:12]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell pm grant de.chagemann.regexcrossword android.permission.CHANGE_CONFIGURATION
[18:08:12]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell getprop ro.build.version.sdk
[18:08:12]: ▸ 28
[18:08:12]: Granting the permissions necessary to access device external storage
[18:08:12]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell pm grant de.chagemann.regexcrossword android.permission.WRITE_EXTERNAL_STORAGE
[18:08:12]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell pm grant de.chagemann.regexcrossword android.permission.READ_EXTERNAL_STORAGE
[18:08:12]: Running tests for locale: en-US
[18:08:12]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale de_DE \
de.chagemann.regexcrossword.test/androidx.test.runner.AndroidJUnitRunner
[18:08:15]: ▸ de.chagemann.regexcrossword.CrosswordDatabaseTest:...
[18:08:20]: ▸ de.chagemann.regexcrossword.screenshots.ScreenshotTest:.
[18:08:20]: ▸ Time: 5,933
[18:08:20]: ▸ OK (4 tests)
[18:08:21]: Running tests for locale: de-DE
[18:08:21]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 shell am instrument --no-window-animation -w \
-e testLocale de_DE \
-e endingLocale de_DE \
de.chagemann.regexcrossword.test/androidx.test.runner.AndroidJUnitRunner
[18:08:23]: ▸ de.chagemann.regexcrossword.CrosswordDatabaseTest:...
[18:08:28]: ▸ de.chagemann.regexcrossword.screenshots.ScreenshotTest:.
[18:08:28]: ▸ Time: 5,786
[18:08:28]: ▸ OK (4 tests)
[18:08:28]: Pulling captured screenshots from the device
[18:08:29]: $ /Users/chag0709/Library/Android/sdk/platform-tools/adb -s 192.168.2.159:5555 pull /sdcard/de.chagemann.regexcrossword/screengrab /var/folders/ql/qg8k5v3j5_l163wcpq49m0wc0000gn/T/d20190226-23537-7h3wxf
ls: /data/data/de.chagemann.regexcrossword/app_screengrab: Permission denied
[18:08:29]: Exit status: 1
[18:08:29]: Screenshots copied to fastlane/metadata/android/de-DE/images/phoneScreenshots
[18:08:29]: Generating HTML Report
[18:08:29]: Successfully created HTML file with an overview of all the screenshots: '/Users/chag0709/git/privat/regex-crossword-kotlin/fastlane/metadata/android/screenshots.html'
[18:08:29]: Captured 8 screenshots! 📷✨

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | capture_android_scree  | 27          |
|      | nshots                 |             |
+------+------------------------+-------------+

[18:08:29]: fastlane.tools finished successfully 🎉
```

**Comment by janpio** [comment]
Yes, but this means that exactly the correct amount of screenshots are getting taken. It just means that half of those are saved under the wrong locale, correct?

**Comment by carstenhag** [comment]
It *says* that it's switching locales, but it really isn't, as described in https://github.com/fastlane/fastlane/issues/14307. It's taking 8 screenshots with de-DE.

That's why I think we need to solve #14307 first, and then this one is gone too with it.

**Comment by janpio** [comment]
So I repeat: You are getting exactly the number of screenshots that are expected to be taken. (But the screenshots are broken for your because of #14307)

No need to track this twice, I will close this issue now.
