### ISSUE TITLE
[screengrab] Locales not getting changed; perhaps due to CHANGE_CONFIGURATION permission?

### ISSUE THREAD

**Issue by carstenhag** [fastlane/fastlane#14307]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Screenshots on my real device are only taken on de-DE locale, but not en-US.  
Screenshots on my emulator are only taken on en-US, but not de-DE.

I found https://github.com/fastlane/fastlane/issues/11696 but that has been closed due to inactivity.

I think the locales are not getting changed at all, perhaps due to the configuration permission not being available for the app.

##### Command executed
`fastlane screenshots`

##### Complete output when running fastlane, including the stack trace and command used

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dist="http://schemas.android.com/apk/distribution"
    xmlns:tools="http://schemas.android.com/tools"
    package="de.chagemann.regexcrossword">

    <dist:module dist:instant="true" />

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <!-- Allows unlocking your device and activating its screen so UI tests can succeed -->
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <!-- Allows for storing and retrieving screenshots -->
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <!-- Allows changing locales -->
    <uses-permission android:name="android.permission.CHANGE_CONFIGURATION" />

    <application  ... >
```

<details>
  <pre>
Screengrabfile:

locales ['en-US', 'de-DE']
ending_locale 'de-DE'
clear_previous_screenshots true

use_tests_in_packages = 'de.chagemann.regexcrossword.screenshots'

tests_apk_path 'app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
app_apk_path 'app/build/outputs/apk/debug/app-debug.apk'

test_instrumentation_runner 'androidx.test.runner.AndroidJUnitRunner'

</pre>
</details>

<details>
  <pre>
package de.chagemann.regexcrossword.screenshots

// imports

@Suppress("BooleanLiteralArgument")
@RunWith(AndroidJUnit4::class)
class ScreenshotTest {

    @get:Rule
    var activityRule =
            ActivityTestRule(CategoryActivity_::class.java, false, false)

    @Test
    fun testTakeScreenshot() {

        activityRule.launchActivity(null)
        Screengrab.setDefaultScreenshotStrategy(UiAutomatorScreenshotStrategy())

        Screengrab.screenshot("select-category")

        onView(
                withId(R.id.categoryRecyclerView)
        ).perform(RecyclerViewActions.actionOnItemAtPosition<CategoryAdapter.ViewHolder>(0, click()))

        Screengrab.screenshot("select-level")
    }

    companion object {

        @get:ClassRule
        val localeTestRule = LocaleTestRule()
    }
}

</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.19.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  lane :screenshots do
    capture_android_screenshots
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("playstoreapi.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("de.chagemann.regexcrossword") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 3.0.0        |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.6.0        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.7.1        |
| dotenv                    | 2.2.0        |
| emoji_regex               | 1.0.1        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.5        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.16.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.10       |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2018.0812  |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.13.1       |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 1.0.0        |
| os                        | 0.9.6        |
| plist                     | 3.5.0        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.1.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.4.1        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.8.1        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2019-02-25**
</details></pre>
</details>

**Comment by carstenhag** [comment]
You can pull https://gitlab.com/carstenhag/regex-crossword-kotlin and try to repro it there.

If that doesn't work, I can do a minimal project too, sure :)

**Comment by janpio** [comment]
I would sure prefer a more minimal example (new Android project in Android Studio with minimal changes to reproduce) - but maybe someone else will be happy with this example project as well.

**Comment by carstenhag** [comment]
Here's a minimal broken example: https://github.com/carstenhag/bug-report-screengrab-locales

https://i.imgur.com/sfzsmqx.png

**Comment by janpio** [comment]
From a quick look it seems you didn't follow the documentation: https://docs.fastlane.tools/actions/screengrab/#configuring-your-ui-tests-for-screenshots

**Comment by carstenhag** [comment]
It would have been pretty nice if you had given me a pointer as to what I am not following :)

Anyway: You likely meant `LocaleTestRule` missing. I forgot to include it in the sample, but in the original repo it is included and there it doesn't work either.

**Comment by carstenhag** [comment]
Experimented some more, *how* I declared the LocalTestRule was wrong.

For Kotlin, this should be used (as per [this article](https://proandroiddev.com/fix-kotlin-and-new-activitytestrule-the-rule-must-be-public-f0c5c583a865)):

```kotlin
@Rule @JvmField
val localeTestRule = LocaleTestRule()
```

The important part is the `@JVMField` annotation. It won't work like this:

```kotlin
companion object {
    @get:ClassRule
    val localeTestRule = LocaleTestRule()
}

```

**Comment by janpio** [comment]
I linked exactly to the headline that contains the information about `LocaleTestRule` ;)

You can either create a PR yourself, the file is here: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/capture_android_screenshots.md#configuring-your-ui-tests-for-screenshots 

Or you create a new issue - but as you are probably the one with the most Kotlin + screengrab knowledge right now I would really prefer if you could directly create a PR and make all the necessary changes so that the documentation is also valid for Kotlin.
