### ISSUE TITLE
Credentials Manager custom

### ISSUE THREAD

**Issue by brenwell** [fastlane/fastlane#14300]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Hey fastlane team, thanks for the awesome tools !!

I am trying to solve the following problem. I want to grab a password from my keychain and use it in a lane. I was trying to use the credentialsManager but I am not sure if it actually does what I want. Note: The solution needs to work on mac and linux.

Here's what I wanted to do:

Add some custom passwords to the credentials manager

```ruby

CredentialsManager::AccountManager.new(
    user: 'alias',
    password: 'fake_password',
    prefix: `custom`
).add_to_keychain

CredentialsManager::AccountManager.new(
    user: 'store',
    password: 'fake_password',
    prefix: `custom`
).add_to_keychain

```
Then later use them to sign apks

```ruby

gradle(
    task: 'assemble',
    properties: {
        "android.injected.signing.store.file" => "my.keystore",
        "android.injected.signing.store.password" => ENV["custom_store"],     
        "android.injected.signing.key.alias" => "UploadKey",
        "android.injected.signing.key.password" => ENV["custom_alias"],    
    }
)
```

Is there some way of doing this? Its my understanding that CredentialsManager works across platforms so such a solution would work with CIs easy, does that sound correct?

Thanks again!

**Comment by brenwell** [comment]
I did work out a solution for mac, but I would need something for linux, if anyone has any ideas i am open.

```ruby
def getPassword(account, where)
    `security -q find-generic-password -a #{account} -s #{where} -w`
end
```

then use it like so

```ruby
gradle(
    task: 'assemble',
    properties: {
        "android.injected.signing.store.file" => "my.keystore",
        "android.injected.signing.store.password" => getPassword('account","store_entry"),     
        "android.injected.signing.key.alias" => "UploadKey",
        "android.injected.signing.key.password" => getPassword('account","alias_entry"),     
    }
)
```

**Comment by janpio** [comment]
Keychains don't really exist on Linux, so this can not work properly. 
I don't think any of the keychain functionality used by Fastlane actually works on Linux, does it?

Where do you want to use this? On CI you usually have a different mechanism to store and use secrets like e.g. key passwords.

Where and how would you first _write_ that passowrd? The credential manager only works locally (afaik, or via iCloud) and not via a file. Or did I misunderstand something myself?

**Comment by mollyIV** [comment]
👋 

> I did work out a solution for mac, but I would need something for linux, if anyone has any ideas i am open.
> ```ruby
> def getPassword(account, where)
>     pass = `security -q find-generic-password -a #{account} -s #{where} -w`
>     pass.gsub("\n",'')
> end
> ```

I wrote a wrapper on the keychain access. It uses [security command](https://www.unix.com/man-page/mojave/1/security/) under the hood. It is a fastlane plugin and you can find it [here](https://github.com/mollyIV/fastlane-plugin-secret_keeper). I think it could improve the readability of your code and provide an extra functionality: reading, storing and removing passwords. 

> Keychains don't really exist on Linux, so this can not work properly.

AFAIK they do not. I was looking for an alternative on Linux and found [Keyring](https://wiki.gnome.org/Projects/GnomeKeyring):

```
GNOME Keyring is a collection of components in GNOME that store secrets, passwords, keys, certificates and make them available to applications.
```

Maybe this ☝️ will spark some ideas. 

> Its my understanding that CredentialsManager works across platforms so such a solution would work with CIs easy, does that sound correct?

In order to inject the secrets on CIs, one of the popular way of doing it is setting environment variables in repository settings. As an example, you can have a look at Travis documentation: [Define Variables in Repository Settings](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings)

Please let us know if that helped 🙇 🙇

**Comment by brenwell** [comment]
Thanks for all the suggestions and input guys. Yes I see, I can use Environment variables on CI and keychain on mac. Doesn't quite solve local linux users as they will have to secure passwords in plaintext. But that will cover most of my team.

This looks cool: https://github.com/mollyIV/fastlane-plugin-secret_keeper Will check it!

I am using the fastlane cryptex plugin to share the java keystore and wanted to use the keychain or maybe even 1password to manage the store & alias passwords.

Ideally I would have 2 branches of the git repo, match on one and cryptex on the other and all the passwords for fastlane would be i the keychain

Thanks again

**Comment by bhavincb** [comment]
@brenwell  do you have any alternatives for keychain on linux platform?

**Comment by brenwell** [comment]
No sorry. Never found an ideal solution. I am using the cryptex plugin though. Which is pretty awesome. Maybe it’s enough then to just use env cars ??

**Comment by bhavincb** [comment]
@brenwell  we actually need to create certificates and upload ipa using linux platform. any thoughts you can help with?

**Comment by brenwell** [comment]
Hard for me to give any suggestions because we always need a mac to build our react native apps, so we obviously always have keychain. But I though about using something like https://wiki.gnome.org/action/show/Projects/GnomeKeyring?action=show&redirect=GnomeKeyring and the fastlane cryptex plugin for the linux/android guys

I also considered 1password and their cli for a while

sorry if that's no help
