### ISSUE TITLE
Automatically update FASTLANE_SESSION Environment Variable

### ISSUE THREAD

**Issue by LanceMcCarthy** [fastlane/fastlane#14305]
### Feature Request
Provide a command switch for Fastlane when using `spaceauth -u user@email.com` to automatically set the `FASTLANE_SESSION` environment variable on the machine 

For example:

```
fastlane spaceauth -u user@email -setFastlaneSessionVariable
```

Where the `-setFastlaneSessionVariable` flag will automatically set/update the value of `FASTLANE_SESSION` on that machine using the same export command it already shows you as a tip 

Preview of what the export command looks like when you're done using spaceauth:
```
export FASTLANE_SESSION='cookie is shown here'
```

#### Motivation Behind Feature
When using Fastlane in a user-less environment (e.g. CI/CD), the Fastlane session cookie expires in about 8-16 hours.

The essentially breaks any attempt to use Fastlane in a CI/CD workflow when the user account has 2FA enabled because you'll need to manually update the `FASTLANE_SESSION` every 8 hours.

Visit the following related discussions

* #14301 
* #14239

#### Feature Description

Fastlane itself seems to stay authorized for about 30 days before being asked to provide a 2FA code again. However, the session cookies is only valid for ~8 hours.

By having the `fastlane spaceauth -u user@email` command automatically set the `FASTLANE_SESSION` variable's value, you can simply add a **one liner** command Task of code to the CI/CD tasks before the Fastlane task.

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D109)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.116.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |

**Comment by janpio** [comment]
Thanks for moving this over here.

My current understanding:

`fastlane spaceauth` is a method to output the cookie that is created and set when any method uses `Spaceship.login`, so you can transfer it from one computer (where you can do the 2FA flow) to another (where you can't). The ENV variable was only chosen, because it is simpler than to copy a file to a specific location.

If you _can_ to the 2FA flow on a machine, you don't need to set the ENV variable on that machine. When using `fastlane spaceauth`, you also get a new session cookie in the correct file on that machine - you only also additionally get its content output for the user to transfer to another machine. But all other actions that use `Spaceship.login` do the exact same thing, minus the output part.

> Fastlane itself seems to stay authorized for about 30 days before being asked to provide a 2FA code again. However, the session cookies is only valid for ~8 hours.

Is this you own observation or a deduction from what is written down in the documentation and issues?

**Comment by LanceMcCarthy** [comment]
I have personally experienced the session cookie not working the day after I generated it. 

Here's my workflow:

Note: all of these steps I list below take place on my Mac, which is on-premises. Azure DevOps uses a concept called **Self-Hosted Agent** that connects to my Mac instead of using their online VMs (this is for legal and stability purposes)

_Stage 1 -_ 
I have a Xamarin.Forms application in a private git repo that gets built by Azure DevOps. A successful build will trigger Stage 2.
_Stage 2 -_ 
The compiled application packages get downloaded to the Mac and the Fastlane commands are executed using the credentials store in the Environment Variables.

- Username
- Password
- AppSpecific Password
- Faslane Session Cookie

this worked fine for months.

However, my iOS releases started getting stuck one day after Apple migrated to the new App Center roles (this started rolling out on Feb1 but didnt affect me until ~ Feb 7th).  My Mac was stuck, typing up the queue for other builds and releases.

After looking at the logs, I saw that the Fastlane command was stuck on "_Waiting for 2FA code, if this is not an interactive session..._" after the session was declared invalid.

So I followed the link to the CI/CD docs, followed the instructions to manually use Web Session to generate and copied the Session Cookie. I restarted the Release and YAY! It gets pushed to App Center.

Then the very next day, when I pushed a new build, it gets stuck again (hanging for ~12 hours before I noticed). I repeated the same process, generated a new session cookie and things get published again.

That has happened every single time so far, which is why I started looking for a more permanent fix.

I don't mind going in there once every 30 days to insert a new 2FA code to reauthorize Fastlane, but I can't keep getting new session cookies every time I need to push a build to TestFight.

### Temporary Solution
This is where your information might be the cure for me. As long as Fastlane updates the value of the FASTLANE_SESSION variable on that mac, I can just run a command `fastlane spaceauth -u xxx` right before I use Fastlane to update the build.

**Comment by janpio** [comment]
I don't really understand. 

If you have a persistent (CI) machine where you can input things when logging in, why go the detour of the ENV variable? As I wrote before, using `spaceauth` does update the actual cookie file, so not having the ENV variable set should have the exact same effect as automatically setting the ENV variable.

**Comment by LanceMcCarthy** [comment]
I think the problem is `spaceauth -u` is not run before the upload attempt, which means Fastlane attempts to use the last known good value (in an ENV var or in the cookie file).

Looking at the YAML for the task

```
steps:
- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
  displayName: 'Publish to the App Store'
  inputs:
    serviceEndpoint: 'AppStore Connect (Lance)'
    appIdentifier: redacted
    shouldSkipWaitingForProcessing: true
    teamId: redacted
    teamName: 'redacted'
    fastlaneArguments: '--verbose'
```

The only flags passed to Fastlane is `--verbose`. I think I can solve this by adding the `spaceauth -u user@email.com` to the fastlaneArguments 

This will force Fastlane to update the session every time.

**Comment by janpio** [comment]
`spaceauth` just does a normal login, then outputs the cookie value (which should be the existing one if the session still worked, and a new one if a new login (with 2FA) was needed.

The `FASTLANE_SESSION` is only used in one place: After the cookie itself was not enough to get a working request - it is used as a fallback if the file based session doesn't work.

---

What exactly the Azure stuff does that you mentioned and showed the screenshot you would have to investigate yourself, the step definition is probably available somewhere. My guess is that this really just sets the `FASTLANE_SESSION` value to whatever you put in there.

**Comment by LanceMcCarthy** [comment]
Yep! That's precisely what it does.

This is why my initial inquiry is how to get spaceauth to always set the ENV variable by using a flag. The example would be `fastlane spaceauth -u user@email.com -setSessionEnvVariable` kind of idea.

From what I can see, the only way to get the ENV variable set is to use `export` and then take that copy/pasted value to manually set the `FASTLANE_SESSION" with that string.

If I could get fastlane to always overwrite the ENV var (and not just the spaceauth.login file), it would be a solution to making sure the ENV variable has the most recent value.

**Comment by janpio** [comment]
I repeat: If you call `fastlane spaceauth` and input any 2FA stuff that might pop up, you don't need to set the ENV var as the cookie is being written to the harddisk - which has the exact same effect as setting the ENV var.

**Comment by LanceMcCarthy** [comment]
Understood. It just seems that because the ENV variable is already set, it uses it instead of the file. 

In any case, all I can do is postulate at this point, I'll wait a couple days and try again.

That way, I can provide actual evidence for you (logs, console output etc). It makes a lot more sense when you see the process because it does seem like we're explaining the same thing over and over :)

Thanks for the prompt follow-ups.

**Comment by janpio** [comment]
>  because the ENV variable is already set, it uses it instead of the file.

That might indeed be true, although the existence of the local cookie file should not let the code come that far.

We will need to spend some time to pull that system apart and understand it better to maybe improve or fix it. Something isn't really right here :/

**Comment by bonebox** [comment]
> I repeat: If you call `fastlane spaceauth` and input any 2FA stuff that might pop up, you don't need to set the ENV var as the cookie is being written to the harddisk - which has the exact same effect as setting the ENV var.

Has this been tested? It doesn't work for me. I still have to manually set FASTLANE_SESSION with the output of `fastlane spaceauth` otherwise fastlane fails with a two-factor auth error.

**Comment by yuriferretti** [comment]
@bonebox I complete understand what you mean. I'm experiencing the same issue and realised that session expires in less than a day. So I also would like to see a way to get the output of `fastlane space auth -u email` and set it to the `ENV` or other better solution
Did you found any workaround?

**Comment by LanceMcCarthy** [comment]
@yuriferretti @bonebox We could work around this if there's a way to copy out the cookie value when space auth is finished.

Currently, I only see a way to do it manually by entering "Y" when the refresh is complete.

If that value can be pulled out at that time, you can update an ENV variable by simply using `set` inthe Terminal

**Comment by yuriferretti** [comment]
Hi @LanceMcCarthy , I just found [this gist](https://gist.github.com/TheMetalCode/d5bc698ef13dc9c1d5fdda698ec33123) in a related issue and it's working as expected.
I removed circle ci related code and the result is:
```ruby
lane :retrieve_fastlane_session do
    # runs shell
    spaceauth_output = `bundle exec fastlane spaceauth`
    # regex the output for the value we need
    fastlane_session_regex = %r{Pass the following via the FASTLANE_SESSION environment variable:\n(?<session>.+)\n\n\nExample:\n.+}
    new_session = nil
    if match = spaceauth_output.match(fastlane_session_regex)
      # Strip out the fancy formatting
      new_session = match[:session].gsub("\e[4m\e[36m", "").gsub("\e[0m\e[0m", "")
    end

    # Yell and quit if unable to parse out session from spaceauth output
    if new_session.nil?
      puts "Unable to obtain new session via fastlane spaceauth"
      exit 1
    else
      new_session
    end
  end
```
hope it helps!

**Comment by Westacular** [comment]
I haven't looked at the code but I suspect the issue here is that there are multiple cookies at play: there's the access token, which looks like it has only a 30 minute lifetime, and a refresh token which lasts much longer (~30 days maybe?).

If you have the cookies stored in `~/.fastlane/spaceship/.../cookie`, it seems that when Fastlane connects and the access token has expired, it will automatically refresh the access token, updating most of the cookies in the process, and then proceed to do whatever you need it to do, _without requiring a new 2FA code_.

Meanwhile, if you pass a `FASTLANE_SESSION` environment variable but the access token it contains is expired (i.e. an hour or two old), Fastlane appears to fail at updating the access token. I'm guessing this is because the environment variable is treated as immutable, and is overriding any other local state, so it continues to try to use the expired access token stored in that variable, even after Apple's servers hand it an updated one. As a result, Fastlane resorts to attempting a new login session and asking for a 2FA code if you generated the `FASTLANE_SESSION` variable more than an hour ago.

This makes `FASTLANE_SESSION` completely broken for CI usage. Which is a shame, because I'd like to have my CI systems set up such that:
- the individual CI runners don't need any manual configuration or updating
- the individual CI runners don't persistently store any confidential information, and are instead provided sensitive data as-needed from the CI coordinator (i.e. through environment variables)

Having to store a cookie file in `~/.fastlane/spaceship/...` (which must occasionally be updated by interactively running a command locally) fails on both those points.

**Comment by janpio** [comment]
A thought:
Could it be the basic problem behind this that `FASTLANE_SESSION` _is static_ on CI systems? You can't change those "runtime environment variables" in Circle CI, Travis, Azure Pipelines (without additional handling, maybe at all). You can only set them via UI or API, and they get supplied to each CI run in their set form.

(This partly matches what you wrote @Westacular)

I don't really see any way to fix this in a simple way.

**Comment by yuriferretti** [comment]
@LanceMcCarthy the script start failing after 24h and I have to run `spaceauth` on ci and follow the 2FA auth flow. Are you experiencing any issues?

**Comment by LanceMcCarthy** [comment]
@yuriferretti This is going to fix it by using the long lived cookie (which is essentially the refresh_token instead of the access_token). https://github.com/fastlane/fastlane/pull/14525

**Comment by mgrebenets** [comment]
Definitely the original complication is that all CI servers configuration params are static.

E.g. in out case we use TeamCity and set and env variable like `env.FASTLANE_SESSION`.
We can't just update this job parameter directly from the build job, but I think there are workarounds.

1. Keep all keys/secrets in a separate repo. I.e. keep the Fastlane session cookie in said repo. Either limit access to the repo or encrypt its contents to make it more secure. Then set up a recurring once a month job that will run `spaceauth` using current session and saved updated cookie into the repo and push it out. Then all CI jobs can pull in this secrets repo and use the Fastlane session stored in it.

1. Use CI server's REST API to update the value of `FASTLANE_SESSION` configuration parameter. In our case we have it defined in one place and it gets reused by all jobs that need to auth to Dev Center / App Store Connect. I haven't looked into details, but I'm sure there's a way to update the job/project parameter via REST call. Then again, have a scheduled job that runs `spaceauth` and uses REST API to set the new value.

1. Just like first option, only instead of a git repo with secrets use something like [Vault](https://www.vaultproject.io/) and push updated session to the vault.
