### ISSUE TITLE
[screengrab] Add an option to disable suffixes to screenshots

### ISSUE THREAD

**Issue by carstenhag** [fastlane/fastlane#14309]
### Feature Request
Add an option to disable suffixes to screengrab screenshots.

Has already been mentioned on https://github.com/fastlane/fastlane/issues/5988 but that was closed due to inactivity (I really hate activitybot!)

#### Motivation Behind Feature
Currently, a timestamp suffix is added to all screenshots, and this suffix is not configurable. I don't want there to be a suffix, because it increases git diffs.

I include all my app resources into one folder (that's the https://github.com/Triple-T/gradle-play-publisher/ concept) and yeah, having change diffs instead of remove/add ones would be nicer.

```
phone-screenshots/1-select-category_1551116523886.png
phone-screenshots/2-select-level_1551116524717.png
phone-screenshots/3-tutorial-level_1551116525847.png
phone-screenshots/4-tutorial-experienced_1551116528575.png
```

#### Feature Description
Add a Parameter to disable suffixes on the screenshots.

#### Alternatives or Workarounds
See https://github.com/fastlane/fastlane/issues/5988

**Comment by carstenhag** [comment]
See https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/FileWritingScreenshotCallback.java#L60-L63 for the relevant code

**Comment by janpio** [comment]
What is the parameter you suggest to be implemented to control this behavior?

**Comment by carstenhag** [comment]
What do you think about `disable_timestamp_suffix`?

**Comment by janpio** [comment]
Maybe invert it and do it via a parameter that is `true` by default and can be set `false` to not suffix?

**Comment by carstenhag** [comment]
Or that, sure. Seems good to me!

**Comment by carstenhag** [comment]
Yes, this issue still exists. It's a feature request.

**Comment by carstenhag** [comment]
Yes, this issue still exists. It's a feature request. I really dislike @fastlane-bot.

**Comment by carstenhag** [comment]
Still exists.

**Comment by carstenhag** [comment]
Still open.
