### ISSUE TITLE
Error: 'No such file or directory @ dir_chdir', git_storage issues caused by Dir.chdir block delete directory.  Also when delete clear_changes is not called at all.

### ISSUE THREAD

**Issue by krish722** [fastlane/fastlane#14312]
### New Issue Checklist

- [✅ ] Updated fastlane to the latest version
- [ ✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In some cases I get 'No such file or directory @ dir_chdir - /private/var/folders/...'

##### Command executed
storage.save_changes

<details>
I will be creating the PR ASAP.
</details>

**Comment by janpio** [comment]
Your issues currently does not include nearly enough information to understand what is going on. Please create a new one that follows the bug report issue template and includes all the information it asks for. Thanks.
