### ISSUE TITLE
Action for creating web page with app version history

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#1431]
Do we have an action that enables you to create and update a web page that lists all of the versions that were released in enterprise (e.g. S3)?
There is obviously the auto-generated html page that serves the latest binary, but what if you want to provide access to previous versions?

Does anyone know a fast way to achieve that? or is it worth creating one?

**Comment by ohwutup** [comment]
That would definitely be sweet. Right now there is no way to make that happen, but I think it could fit nicely into `boarding` also, as that creates pages for TestFlight signups too. I think this is definitely worth creating, I am going to mark it as a feature request and close it for now and we will pull it as soon as we get a chance for a later release, but if you can/want to get to this faster than we might be able to it would be amazing!
