### ISSUE TITLE
Notify on a successful release

### ISSUE THREAD

**Issue by Pranit-Harekar** [fastlane/fastlane#14316]
#### Motivation Behind Feature
Currently, we can notify dev team after a successful deployment (_and not a release_) of the build to Appstore/Testflight, however we cannot know when the build is successfully reviewed and is pushed to Appstore/Testflight (_i.e. released_). The motivation behind this is we would like to setup slack notifications for internal teams when the app is available on Appstore/Testflight to use.

#### Feature Description
I was wondering if there is any feature being built that lets developers know that their app is successfully released on a particular platform. (TestFlight/Appstore/other) 

This can be similar to [watchbuild](https://github.com/fastlane/watchbuild), just taking one step further.

I am happy to present ideas, brainstorm & contribute for this feature, unless it's being built internally or is built already and I'm unaware of it.

#### Alternatives or Workarounds
I'm not sure if there is any Apple's way of doing this (meaning idk if there are any AppStore's APIs that we can use), however as an alternative we could add a dummy user in Testflight `user@email.com` who will receive emails when the app is available in Testflight and using slack-email integration we can create slack notifications. But there are some drawbacks - you will also get notified on password reset request or some other misc Appstore actions. I'm sure there must be other ways to achieve this. Please post your thoughts on this feature.

Thanks,

**Comment by max-ott** [comment]
We built something internally which basically checks the version information (edit/live/rawVersion etc.) every XX minutes and compares it with what we have on record/in the database. There is no way for Spaceship/Fastlane to get this information similar to `watchbuild`.

As this requires a full infrastructure (database, server etc.) I don't think it makes sense to add this directly to `spaceship` or the `fastlane` ecosystem.
