### ISSUE TITLE
Integrate fastlane with jenkins

### ISSUE THREAD

**Issue by tanvirhannan** [fastlane/fastlane#14323]
**Issue**
I'm have a Jenkins job running (not locally, it's on aws on a separate computer) every time I merge a pull request from a repo. This repo contains a fastfile. How exactly can I call specific lanes 
(ex. fastlane mylane) in the job? Under "build execution" in jenkins, I tried to 

`gem install fastlane
fastlane mylane`

but got this error:
`+ gem install fastlane
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires google-api-client (< 0.24.0, >= 0.21.2); google-cloud-storage requires google-api-client (~> 0.26)`

When I try (in Jenkins) to run the command: 
`which fastlane`

the output in console is:
`+ which fastlane
which: no fastlane in {...random....path}`

Does anyone know how I can properly integrate my lanes to be called in this Job? Also, I cannot install any plugins and my server is using a different version of ruby than what I am running locally -- but I don't know if that should matter if I have to install fastlane again anyways (had trouble tryin to install r vm in the build execution script area for jenkins too).

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.6.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.116.1"

# require 'rubygems'
# require 'httparty'

default_platform :ios

# class EdutechionalResty
#   include HTTParty
#   base_uri "http://edutechional-resty.herokuapp.com"
#
#   def posts
#     self.class.get('/posts.json')
#   end
# end
#
# lane :api do
#   api = EdutechionalResty.new
#   print "hi"
#   puts api.posts[0]['title']
# end

lane :example do
  puts("this is my first 🚀 lane")
end

lane :hello do
  ENV['OUTFILE'] = "newease.ipa"

  archive_path = UI.input "Name of the app"
  sh "rm -rf " + archive_path + "/" + "*.ipa"
  sh "mv " + ENV['OUTFILE'] + " " + archive_path
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status  |
| -------------------------- | ------- | -------------- |
| fastlane-plugin-fetch_file | 0.1.8   | 💥 Check failed |
| fastlane-plugin-keyman     | 0.1.5   | 💥 Check failed |
| fastlane-plugin-airwatch   | 0.2.4   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| executable-hooks           | 1.6.0        |
| bundler-unload             | 1.0.2        |
| rubygems-bundler           | 1.4.5        |
| bundler                    | 1.17.3       |
| etc                        | 1.0.1        |
| forwardable                | 1.2.0        |
| CFPropertyList             | 3.0.0        |
| concurrent-ruby            | 1.1.4        |
| i18n                       | 0.9.5        |
| minitest                   | 5.11.3       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.5        |
| activesupport              | 4.2.11       |
| public_suffix              | 2.0.5        |
| addressable                | 2.6.0        |
| atomos                     | 0.1.3        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| fuzzy_match                | 2.0.4        |
| nap                        | 1.1.0        |
| cocoapods-core             | 1.6.1        |
| cocoapods-deintegrate      | 1.0.3        |
| cocoapods-downloader       | 1.2.2        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.1.0        |
| netrc                      | 0.11.0       |
| cocoapods-trunk            | 1.3.1        |
| cocoapods-try              | 1.1.0        |
| colored2                   | 3.1.2        |
| escape                     | 0.0.4        |
| fourflusher                | 2.2.0        |
| gh_inspector               | 1.1.3        |
| molinillo                  | 0.6.6        |
| ruby-macho                 | 1.4.0        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.8.1        |
| cocoapods                  | 1.6.1        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| digest-crc                 | 0.4.1        |
| unf_ext                    | 0.0.7.5      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| dotenv                     | 2.7.0        |
| emoji_regex                | 1.0.1        |
| excon                      | 0.62.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.15.4       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.5        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| multi_json                 | 1.13.1       |
| os                         | 1.0.0        |
| signet                     | 0.11.0       |
| googleauth                 | 0.6.7        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2018.0812  |
| mime-types                 | 3.2.2        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.23.9       |
| google-cloud-env           | 1.0.5        |
| google-cloud-core          | 1.3.0        |
| google-cloud-storage       | 1.16.0       |
| json                       | 2.2.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.5.0        |
| rubyzip                    | 1.2.2        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.5        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.4.1        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.6.5        |
| tty-cursor                 | 0.6.0        |
| tty-spinner                | 0.9.0        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-airwatch   | 0.2.4        |
| fastlane-plugin-fetch_file | 0.1.8        |
| fastlane-plugin-keyman     | 0.1.5        |
| xcode-install              | 2.5.0        |
</details>

*generated on:* **2019-02-27**
</details>

Since my local env is different from the one running in Jenkins, do I need to move my ruby version file with all of its gems into the repo that Jenkins is reading so Jenkins knows what I'm trying to run locally?

**Comment by marlenabowen** [comment]
This might be related to [this issue re: setting PATH](https://github.com/fastlane/fastlane/issues/9409).

Also, are you using a declarative Jenkins pipeline? You can call your lanes from within a [Jenkinsfile](https://jenkins.io/doc/book/pipeline/jenkinsfile/).
