### ISSUE TITLE
add_git_tag should return the newly created tag name

### ISSUE THREAD

**Issue by vafada** [fastlane/fastlane#14328]
### Feature Request
`add_git_tag` should return the newly created tag name

#### Motivation Behind Feature
so we can specify which tag to push using `push_git_tags` instead of pushing all tags in local ref

**Comment by mollyIV** [comment]
Hey @vafada 👋 not sure I understand the issue 🤔 when you use `add_git_tag` you can provide a tag name: 

```ruby
add_git_tag(
  tag: "my_custom_tag"
)
```

In [`push_git_tags`](https://docs.fastlane.tools/actions/push_git_tags/#parameters) you can provide a tag you want to push, so the lane could look like:

```ruby 
lane :custom_lane do
    add_git_tag(tag: "my_custom_tag")
    push_git_tags(tag: "my_custom_tag")
end
```

Could you please provide an example how do you use those two lanes to better understand your issue? 🙏

**Comment by vafada** [comment]
Hi @mollyIV 

we don't mind the naming convention that `add_git_tag` creates e.g. `builds/iosbeta/530`

basically we want to do:

```ruby
   new_tag = add_git_tag()
   push_to_git_remote(tag: new_tag)
```

right now we doing:

```ruby
   add_git_tag()
   push_to_git_remote
```

And a lot of times, git is error-ing out if there are conflicts:

```
[10:59:57]: Exit status of command 'git push origin fix-branch:fix-branch --tags' was 1 instead of 0.
To github.com:Foo/foo.git
   ee0d86baa..8318225eb  fix-branch -> fix-branch
 * [new tag]             builds/iosbeta/531 -> builds/iosbeta/531
 * [new tag]             builds/iosbeta/532 -> builds/iosbeta/532
 * [new tag]             builds/iosbeta/533 -> builds/iosbeta/533
 ! [rejected]            builds/androidalpha/443 -> builds/androidalpha/443 (already exists)
 ! [rejected]            builds/androidalpha/530 -> builds/androidalpha/530 (already exists)
error: failed to push some refs to 'git@github.com:Foo/foo.git'
hint: Updates were rejected because the tag already exists in the remote.
```

We don't want to push all tags in our local environment, we just want to push the single tag that was created by `add_git_tag()`

**Comment by mollyIV** [comment]
I see, thank you for the context 🙇 I think you can try to use 
[`last_git_tag`](https://docs.fastlane.tools/actions/last_git_tag/) action 👍 

```ruby
add_git_tag
push_to_git_remote(tag: last_git_tag)
```

I will have a look at the code and make a PR ✨

**Comment by vafada** [comment]
@mollyIV Aha! thanks, `last_git_tag` should work... closing this Feature Request

**Comment by vafada** [comment]
@mollyIV I have to re-open this. the argument `tag` is invalid for `push_to_git_remote`

Sorry, it took a while to test:

```
[15:00:22]: --------------------------------
[15:00:22]: --- Step: push_to_git_remote ---
[15:00:22]: --------------------------------
[15:00:22]: You passed invalid parameters to 'push_to_git_remote'.
[15:00:22]: Check out the error below and available options by running `fastlane action push_to_git_remote`
```
