### ISSUE TITLE
latest_testflight_build_number fails with "Could not find a build on iTC" message

### ISSUE THREAD

**Issue by prasanthu** [fastlane/fastlane#14320]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
latest_testflight_build_number started failing to fetch the build number

##### Command executed
fastlane run latest_testflight_build_number app_identifier:"abc.def.dev.selfcare" version:"1.0"

##### Complete output when running fastlane, including the stack trace and command used

fastlane run latest_testflight_build_number app_identifier:"sg.redotter.dev.selfcare" version:"1.0"
[✔] 🚀
[18:57:55]: fastlane detected a Gemfile in the current directory
[18:57:55]: however it seems like you don't use `bundle exec`
[18:57:55]: to launch fastlane faster, please use
[18:57:55]:
[18:57:55]: $ bundle exec fastlane run latest_testflight_build_number app_identifier:sg.redotter.dev.selfcare version:1.0
[18:57:55]:
[18:57:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:57:56]: --------------------------------------------
[18:57:56]: --- Step: latest_testflight_build_number ---
[18:57:56]: --------------------------------------------
[18:57:56]: Login to App Store Connect (ios-dev@redotter.sg)
[18:57:58]: Login successful
[18:57:59]: Fetching the latest build number for version 1.0
[18:58:00]: Could not find a build on iTC. Using supplied 'initial_build_number' option
[18:58:00]: Latest upload for version 1.0 is build: 1
[18:58:00]: Result: 1

<details>
  <pre>
 sg.redotter.dev.selfcare already has 25 versions uploaded in testflight. Now this fails always with
"Could not find a build on iTC. Using supplied 'initial_build_number' option" message
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D109)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Push a new beta build to TestFlight (Used by CircleCI)"
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "ostelco-ios-client.xcodeproj"
    )
    # call certifcates lane
    certificates
    # build and upload dev app
    build_app(scheme: "dev-ostelco-ios-client")
    upload_to_testflight
    # Commit the version bump
    commit_version_bump(xcodeproj: "ostelco-ios-client.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    # add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote(
      remote: "origin",
      local_branch: "HEAD",
      remote_branch: "master",
      force: true,
      tags: true
    )
  end

  desc "Push beta build to TestFlight from developer machine"
  lane :localbeta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    build_number = latest_testflight_build_number(
      app_identifier: "sg.redotter.dev.selfcare",
      version: "1.1"
    )
    increment_build_number(
      build_number: build_number + 1,
      xcodeproj: "ostelco-ios-client.xcodeproj"
    )
    # build and upload dev app
    build_app(scheme: "dev-ostelco-ios-client")
    upload_to_testflight
    # Commit the version bump
    commit_version_bump(xcodeproj: "ostelco-ios-client.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote
  end

  desc "Installs the certificates and profiles locally"
  lane :certificates do
    match(
      app_identifier: ["sg.redotter.dev.selfcare", "sg.redotter.selfcare"],
      type: "development",
      readonly: true
    )
    match(
      app_identifier: ["sg.redotter.dev.selfcare", "sg.redotter.selfcare"],
      type: "appstore",
      readonly: true
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "dev-ostelco-ios-client",
      devices: ["iPhone X"]
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("sg.redotter.selfcare") # The bundle identifier of your app
apple_id("ios-dev@redotter.sg") # Your Apple email address

itc_team_id("119183331") # App Store Connect Team ID
team_id("2R8HFAXUXD") # Developer Portal Team ID

for_platform :ios do
  for_lane :beta do
    app_identifier 'sg.redotter.dev.selfcare'
  end
  for_lane :localbeta do
    app_identifier 'sg.redotter.dev.selfcare'
  end
end

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.17.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-02-26**
</details>
 </pre>
</details>

**Comment by bguidolim** [comment]
Do you have extensions is your app? (eg. Share extension). If so, could you check if the version number is the same as your app target? If it's different, probably that is the issue, but anyway it should be fixed.

**Comment by prasanthu** [comment]
> Share extension

No we don't use any extensions.
