### ISSUE TITLE
Detect warnings from `cocoapods`/`pod install` output

### ISSUE THREAD

**Issue by 72A12F4E** [fastlane/fastlane#14321]
### Feature Request

Add the ability to detect warnings from `cocoapods`/`pod install` output. 

#### Motivation Behind Feature

Often times on our large iOS project, running `fastlane run cocoapods` we get misc warnings from the `pod install` that happens. I would like to fail a build CI build if something like this happens.

*Example Error during a pod install*
```
...
[!] `<PBXSourcesBuildPhase UUID=`6AE08D0019CCC6FD005D5A47`>` attempted to initialize an object with an unknown UUID. `6A89CAAF22122DDE006E5AAF` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.
...
```

#### Feature Description

A method parameter like this would be sufficient.

```
cocoapods(fail_on_warning: true)
```

**Comment by janpio** [comment]
Is there a simple way to identify those that should cause it to fail?

**Comment by 72A12F4E** [comment]
I hacked something together in a CI build where I just `grep`'d the pod install output for `[!]`, and failed a build if I detected any instances of that pattern. I don't know if the same approach would work here?

**Comment by janpio** [comment]
If `[!]` is a reliable indicator of a problem, then this would be a viable path to implement this.
