### ISSUE TITLE
[run_tests] error msg: "Possibly there are two concurrent builds running in the same filesystem location"

### ISSUE THREAD

**Issue by laxmorek** [fastlane/fastlane#14337]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I can't run `run_tests`.  

First part of console output:
```
[10:42:12]: -----------------------
[10:42:12]: --- Step: run_tests ---
[10:42:12]: -----------------------
[10:42:12]: $ xcodebuild -showBuildSettings -workspace ./XYZ.xcworkspace -scheme XYZ
[10:42:15]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
2019-03-04 10:42:16.903 xcodebuild[13988:5155539]  DTDeviceKit: deviceType from 130a75ef3afba4b6d6f2695923f8081050a66082 was NULL
[10:42:18]: $ xcodebuild -showBuildSettings -workspace ./XYZ.xcworkspace -scheme XYZ
```
I am not sure, but it looks like `xcodebuild` runs twice.

After that next part of console output:
```
[10:42:23]: ▸ Loading...
[10:42:29]: ▸ Clean Succeeded
[10:42:35]: ▸ ❌  error: unable to attach DB: error: accessing build database "/Users/kamilharasimowicz/Library/Developer/Xcode/DerivedData/XYZ-fhvemzgzmzjduxdvjrxwcpfvfrsr/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
[10:42:35]: ▸ ** BUILD FAILED **
[10:42:40]: ▸ ❌  error: unable to attach DB: error: accessing build database "/Users/kamilharasimowicz/Library/Developer/Xcode/DerivedData/XYZ-fhvemzgzmzjduxdvjrxwcpfvfrsr/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
[10:42:40]: ▸ 2019-03-04 10:42:40.135 xcodebuild[14024:5157050]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks_Fall2018/IDEFrameworks-14460.46/IDEFoundation/Logging/ActivityLog/IDEActivityLogSectionRecorder.m:1050
[10:42:40]: ▸ Details:  log recorder was sent -stopRecordingWithInfo:completionBlock: after it had already been asked to stop recording.
[10:42:40]: ▸ Object:   <IDEActivityLogSectionRecorder: 0x7fed97906790>
[10:42:40]: ▸ Method:   -stopRecordingWithInfo:completionBlock:
[10:42:40]: ▸ Thread:   <NSThread: 0x7fed96ff88e0>{number = 29, name = (null)}
[10:42:40]: ▸ Please file a bug at https://bugreport.apple.com with this warning message and any useful information you can provide.
[10:42:40]: ▸ Testing failed:
[10:42:40]: ▸ unable to attach DB: error: accessing build database "/Users/kamilharasimowicz/Library/Developer/Xcode/DerivedData/XYZ-fhvemzgzmzjduxdvjrxwcpfvfrsr/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
[10:42:40]: ▸ Testing cancelled because the build failed.
[10:42:40]: ▸ ** TEST FAILED **
▸ Clean Succeeded

❌  error: unable to attach DB: error: accessing build database "/Users/kamilharasimowicz/Library/Developer/Xcode/DerivedData/XYZ-fhvemzgzmzjduxdvjrxwcpfvfrsr/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.


** BUILD FAILED **


❌  error: unable to attach DB: error: accessing build database "/Users/kamilharasimowicz/Library/Developer/Xcode/DerivedData/XYZ-fhvemzgzmzjduxdvjrxwcpfvfrsr/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
```

An again. I can see doubled `Clean Succeeded` and ` unable to attach DB: error: accessing build database `. 

I don't understand what is wrong. 

##### Command executed
`fastlane test_build`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.0/bin/fastlane       |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
### PUBLIC SCOPE ###

## test
lane :test_build do 

    # ensure proper git state
    ensure_git_status_clean

    # check code style
    swiftlint(
      strict: true,
      executable: "./Pods/SwiftLint/swiftlint"
    )

    # run unit tests
    run_tests(
      scheme: "XYZ",
      device: "iPhone XR",
      clean: true,
      reset_simulator: true
    )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.117.1 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bundler                   | 1.17.2       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.1        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-03-04**
</details>

**Comment by bengilroy** [comment]
@laxmorek I've had the same issue, switching back to legacy build system in `File -> Workspace Settings` seems to have fixed it for now – although I'm still not sure what the ideal solution is.

**Comment by laxmorek** [comment]
it works in the newest version
