### ISSUE TITLE
Screenshots Not showing in AppStoreConnect after successful upload

### ISSUE THREAD

**Issue by MrBenFTW** [fastlane/fastlane#14336]
Hello, I am using the latest version of Fastlane. The command I ran was `snapshot reset_simulator` and then `fastlane deliver` 

Everything is successful and I can see the screenshots in the folder. However when I check AppStore Connect, nothing is there. 

Pictures:
https://ibb.co/n3qzKRq
https://ibb.co/Krb4jPv
https://ibb.co/DMnRyRk
https://ibb.co/JxNFmwD

The weird thing is, Fastlane downloaded some screenshots and they even showed up in the folder. Yet I don't know where they came from because they are not on AppStore Connect and this is a separate machine.

**Comment by max-ott** [comment]
Hi Ben, from the last screenshot, I can only see that you are trying to upload screenshots for iPhone X (which is not the XS category you have selected in App Store Connect). Could you please go to the "Media Manager" and check all screenshot sizes/categories if they ended up there.

**Comment by MrBenFTW** [comment]
Hi, sorry for the lack of formatting and late reply, I’ve been super busy. 

I am using all default settings. 

I have checked the media manager and nothing is there, not even iPads etc

**Comment by MrBenFTW** [comment]
Hi, the issue was that by default I was using english(UK), I didn't notice that you can manually drop down to select english US in the App Store connect panel. Lo and behold there were the screenshots. I have now specified that it should be English UK.
