### ISSUE TITLE
iTMSTransporter: Unable to perform software analysis on Linux.

### ISSUE THREAD

**Issue by frederikbosch** [fastlane/fastlane#14349]
While uploading the app with the `iTMSTransporter` for Linux I receive the following error.

`Unable to perform software analysis on Linux. Export an AppStoreInfo.plist from Xcode, and use the -assetDescription option.`

What step am I missing? My .itmsp directory looks good. It contains an ipa and a metadata.xml. By the way, I am executing the command `/usr/local/itms/bin/iTMSTransporter -m upload` directly because I am using the `-apiIssuer` and `-apiKey`.

**Comment by frederikbosch** [comment]
Apparently, one needs to pass `-assetDescription` with a .plist as argument. This .plist has to be generated with `swinfo`, which is an osx application.

**Comment by frederikbosch** [comment]
If such a file could be generated without swinfo, that could make fastlane compatible with Linux.

**Comment by janpio** [comment]
Can you share what this file should look like? Maybe it isn't that big of a deal to manually generate.

**Comment by frederikbosch** [comment]
It is a hell of a file....

**Comment by frederikbosch** [comment]
It's a plist of 10000+ lines, containing metadata about every file in the IPA.

**Comment by frederikbosch** [comment]
The solution for Fastlane to this problem would be that the user should include the `AppStoreInfo.plist` in the IPA, and then it can be extracted by Fastlane in order to pass it to the Linux version of iTMSTransporter.

When building the app with `xcode` it is possible to generate this `AppStoreInfo.plist` by passing `-exportOptionsPlist exportOptions.plist` to `xcodebuild` and in the `exportOptions.plist` one should include option `<key>generateAppStoreInformation</key><true/>`.

**Comment by janpio** [comment]
> It's a plist of 10000+ lines, containing metadata about every file in the IPA. That includes specific meta data around images., splash screens etc. Not something you would generate easily.

Is it equally complicated for a barebones iOS app?

How does the upload on macOS work when you do not trigger `xcodebuild`/Xcode to create this file?

Adding `<key>generateAppStoreInformation</key><true/>` to the `exportOptions.plist` should not be that hard - look at the `gym` sourcecode to find out how fastlane builds iOS projects. Also extracting the `.ipa` before uploading and extracting this file also seems very doable (it's just a rename `.zip`).

(Did I understand correctly that you _build_ your ipa on a Mac but want to upload it on Linux?)

**Comment by janpio** [comment]
So to recap: There is an newer version of iTMSTransporter that wants to have additional information about the IPA. On macOS it does that on the fly, but for Linux it requires an additional file included in the IPA to be created during the app build, which can be triggered via an additional entry in `exportOptions.plist`. Correct?

**Comment by frederikbosch** [comment]
100%. See also.

- [iTMSTransporter documentation by Apple](https://help.apple.com/itc/transporteruserguide/?lang=en#/apdAa073cb45), see the remark on `-assetDescription`.
- [Archive export files documentation](https://help.apple.com/xcode/mac/current/#/deva1f2ab5a2), see the remark on `AppStoreInfo.plist`.

**Comment by janpio** [comment]
Ok, so what is the problem then? What do you need fastlane to change here for this to work for you?

Does iTMSTransporter for Linux work when you build the app in a way so that it includes the file?

**Comment by frederikbosch** [comment]
Well, I already closed the issue, because I recognized that I had to make sure that the `AppStoreInfo.plist` was generated. The issue is that deliver does not work on Linux, with support/solution for the `-assetDescription` here [in the itunes_transporter.rb](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L167), it could also support deliveries on Linux.

**Comment by janpio** [comment]
Ok, I missed that bit: You can supply `-assetDescription` with a path to iTMSTransporter so uploads work on Windows and Linux (in current versions of iTMSTransporter, 1.13.0 and similar).

Is the .plist generated as an external file or part of the .ipa that has to be extracted first? Implementing a new optional parameter for anything using iTMSTransporter under the hood should not be that hard. But if we have to extract the file first it might be a bit more work (and logic).

**Comment by frederikbosch** [comment]
@janpio The .plist can be generated during the build with Xcode, through the exportOptions, or you generate it afterwards with `swinfo` which is an Apple application (located in the same dir as `altool`).

**Comment by TPXP** [comment]
Just in case, this is the issue I stumbled on when trying to run the OSX bundle on Linux (it's the final part of https://github.com/fastlane/fastlane/issues/14256#issuecomment-464416918)

**Comment by frederikbosch** [comment]
@TPXP It's the same issue as this one. I was in the unfortunate position to read your experiences after I experienced the same thing. Took hours. You probably know how that goes...

**Comment by TPXP** [comment]
This issue has not been resolved with latest updates, don't close this bug please 🙏
