### ISSUE TITLE
upload_binary_to_app_store

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14342]
We currently have [`pilot`/`upload_to_testflight`](https://docs.fastlane.tools/actions/upload_to_testflight/) and [`deliver`/`upload_to_app_store`](https://docs.fastlane.tools/actions/upload_to_app_store/) to upload binaries to App Store Connect / Testflight (among other things).

The code doing the actual binary uploading is pretty similar:

https://github.com/fastlane/fastlane/blob/69a77679a58868d202e36fa14317e841cda4f5ef/pilot/lib/pilot/build_manager.rb#L31-L38

https://github.com/fastlane/fastlane/blob/69a77679a58868d202e36fa14317e841cda4f5ef/deliver/lib/deliver/runner.rb#L140-L162

Both create the "package" via `FastlaneCore::IpaUploadPackageBuilder.new.generate`, then use `FastlaneCore::ItunesTransporter.new` and `.upload` to actually upload this to Apple.

I suggest we extract that logic into a new `upload_binary_to_app_store` action that can be used independently from the currently existing actions as well (and is used here of course).

### Why? 

3 reasons:

1. The other App Store Connect stuff doesn't work with application specific passwords. ItunesTransporter does, so this would make it easier to show people a way to not have to worry about 2FA if they _just_ want to upload a binary to Apple.
1. Having this as its own action would enable users to just upload a binary build of their app, without anything else. No metadata, no changelog, no icons etc.
1. There is an alternative upload mechanism available via `altool` that we ignored in fastlane for now, but that would be nice to add anyway as it has some advantages over ItunesTransporter.

### How?

Find other uses of `FastlaneCore::ItunesTransporter.new` and `.upload` to make sure we have the full picture, then extract a generalized version into its own action, then replace the current code in pilot and deliver with a call to that action. Done.

**Comment by joshdholtz** [comment]
@janpio I do like the idea of combining these into one shared thing but don't think we can make this an "action" if we want it to also be used in _pilot_ and _deliver_. Those are things that I don't think we want being dependent on an action. If anything, this new shared code should probably live in `fastlane` or `fastlane_core` and _pilot_ and _deliver_ should access it there.

I do like the idea of having an action that does not touch any of the legacy or new App Store Connect APIs (if all people want to do is upload binary) but I'm pretty sure _deliver_ can do that already if you set all meta stuff to false. I would prefer to not introduce another action for uploading App Store Connect binaries if we don't need to 😇 But it would be cool if we could make it easier for people to upload just the binary from _deliver_ if that is what they want 🙃

**Comment by janpio** [comment]
Sure, it makes more sense for the code to live somewhere in `fastlane` or `fastlane_core` - and if we decide to introduce the new action it can also just use it.

And yes, _deliver_ probably can achieve a similar result with some specific collection of parameters. But looking at the list of available parameters, I have no idea which ones exactly have to be set to what values to achieve that. And to be honest I was not aware that _deliver_ could also be used to upload builds for Testflight.

Because of these reasons I think the added overhead of a new action is justified. (We would probably add some documentation to all 3 actions here that crosslink between each other ("if you want to also update metadata, look at ..." or "if you only want to upload a binary and use an app specific password, look at ...").

**Comment by janpio** [comment]
This still sounds like a great idea to me.
