### ISSUE TITLE
Is opt_out_usage broken?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14348]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

![image](https://user-images.githubusercontent.com/183673/53877605-e7d6ad00-4009-11e9-8f3a-750748f01993.png)

Don't have the time to investigate this right now, will look at it later.

##### Command executed
`bundle exec fastlane build --verbose`

**Comment by mgrebenets** [comment]
Could this one be related in any way?
https://github.com/fastlane/fastlane/issues/13510

**Comment by janpio** [comment]
I wouldn't rule that out, yeah. Same general "topic".
