### ISSUE TITLE
Fastlane ignores non-interactive mode and asks for 2FA code

### ISSUE THREAD

**Issue by Felipe-Banno** [fastlane/fastlane#14345]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a few Apple Developer Accounts that are using 2FA and during my CI workflow Fastlane hangs waiting for an user to input the 2FA code.

I tried to force run in no-interactive mode with 
```
export CI=1
export TRAVIS=1
```
and also with
```
export CI=true
export TRAVIS=true
```

in both cases, Fastlane is asking for the 2FA code 
```
Two Factor Authentication for account 'XXXX' is enabled
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code:
```

Is there a way to force Fastlane to fail if there is need to manually enter any input?

##### Command executed
```
CI=true fastlane lane
```

```
TRAVIS=true fastlane lane
```

**Comment by Felipe-Banno** [comment]
One more piece of information
the action `is_ci` is returning true

```
if is_ci?
  puts "I'm a computer"
else
  say "Hi Human!"
end
```

I see `I'm a computer` but still Fastlane is waiting for the 2FA code to be entered by the user.

**Comment by Felipe-Banno** [comment]
Looking at the Fastlane source code, looks like we could solve the issue by adding this lines to *two_step_client.rb* at line 50

```
      if Helper.ci?
        raise Tunes::Error.new, "2FA code input is not supported when running in non-interactive."
      end
```

**Comment by janpio** [comment]
Is `Helper` available in the _spaceship_ context? If not, we will have to clone the logic as spaceship should work independently to fastlane. But maybe not the actual CI check, but the interactivity check? Because _that_ is what causing this to fail (which is also true on CI of course).

I think it makes sense to fail hard here as there is no way to recover.

**Comment by Felipe-Banno** [comment]
Can we keep this issue open? The problem is still happening and blocking my workflow

**Comment by janpio** [comment]
Sure, you just have to reply to @fastlane-bot every time he posts this.

**Comment by sonjz** [comment]
Ran into similar problem recently and hit an endless loop with `select_team`.  I have `ENV['CI'] = 'true'` set.  This produced 80GB of logs over the weekend!

```
Could not find team with name 'XXXXX', trying to fallback to default team
Multiple App Store Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "XXXX"

or

  itc_team_name "2026833 Alberta LTD"

1) "XXXX" (XXXX)
...

```

I recently updated to 2.121.1 last week, is this a possible regression?

To break out of the loop, I added the following hack to force non-interactive (and raise error) to:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L109-L113
```
        puts("HACK: currently broken in 2.121.1 interactive?: #{!Spaceship::Client::UserInterface.interactive?} or ci?: #{Spaceship::Client::UserInterface.ci?} (ENV['CI'] = #{ENV['CI']})".yellow)
        if true
        #unless Spaceship::Client::UserInterface.interactive?
          puts("Multiple teams found on App Store Connect, Your Terminal is running in non-interactive mode! Cannot continue from here.")
          puts("Please check that you set FASTLANE_ITC_TEAM_ID or FASTLANE_ITC_TEAM_NAME to the right value.")
          raise "Multiple App Store Connect Teams found; unable to choose, terminal not interactive!"
        end
```
Results:
**HACK: currently broken in 2.121.1 interactive?: false or ci?: false (ENV['CI'] = true)**
Multiple teams found on App Store Connect, Your Terminal is running in non-interactive mode! Cannot continue from here.
Please check that you set FASTLANE_ITC_TEAM_ID or FASTLANE_ITC_TEAM_NAME to the right value.
	**Error authenticating with iTunes Connect: Multiple App Store Connect Teams found; unable to choose, terminal not interactive!**

**Comment by janpio** [comment]
@sonjz Best create a new issue so we can properly debug and investigate this.

**Comment by daniellockard** [comment]
lets keep this open, we still have issues (I work with @Felipe-Banno)

**Comment by Felipe-Banno** [comment]
Yeah, this is still a big problem

**Comment by fjcaetano** [comment]
I stumbled upon this same issue when trying to deploy from Travis CI. I was able to work around this by creating a new apple id, without 2FA and I'm using that only for deployment.

**Comment by sonjz** [comment]
possible to implement @Felipe-Banno's fix?
https://github.com/fastlane/fastlane/issues/14345#issuecomment-469800654

`CI=true` got getting picked up.

**Comment by janpio** [comment]
Yes please, open a quick PR and we will look into it again.
