### ISSUE TITLE
[supply] version_codes_to_retain error

### ISSUE THREAD

**Issue by asglachung** [fastlane/fastlane#14341]
Keeps giving me error

Error setting value '["141"]' for options 'version_codes_to_retain' 
[!] Version code '141' is not an integer

The following is what I ran

`fastlane supply --package_name "com.packagename.xxx" --track alpha --json_key "/Users/path/xxx.json" --version_codes_to_retain 141 --apk_paths "/Users/path/xxx.apk"`

I also tried putting 141 as follows
- ["141"]
- ['141']
- "141"
- '141'
- {141}

None worked.

**Comment by janpio** [comment]
The one you didn't try yet was `[141]`. Maybe do that, although I don't really thing this will help. But let's see first before diving deeper.

**Comment by asglachung** [comment]
> The one you didn't try yet was `[141]`. Maybe do that, although I don't really thing this will help. But let's see first before diving deeper.
> 
> Workaround would probably be to use a `Fastfile` and a lane to define the parameters for the action.


Yup Tried 141 with and without [ ] brackets

Still doesn't work.

**Comment by janpio** [comment]
Ok, so the error is triggered her:
https://github.com/fastlane/fastlane/blob/1ee7467293ddf4afb7f0272d7d3f402ad681d694/supply/lib/supply/options.rb#L236-L241

I am actually not sure how one can specify an array with integers via command line parameters. As a workaround you might have success creating a `Fastfile` with a lane and then configure `supply` identical to your CLI call.

**Comment by asglachung** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1815)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| json                      | 2.1.0        |
| dotenv                    | 2.6.0        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.6        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.1       |
| psych                     | 3.0.2        |
</details>


*generated on:* **2019-03-06**
</details>
