### ISSUE TITLE
unterminated string meets end of file

### ISSUE THREAD

**Issue by aabanaag** [fastlane/fastlane#14355]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running fastlane test fails for android.
![image](https://user-images.githubusercontent.com/2245822/53910227-58bfa880-408e-11e9-98af-a195270e7616.png)

##### Command executed
fastlane test

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
    [✔] 🚀
[04:08:30]: fastlane detected a Gemfile in the current directory
[04:08:30]: however it seems like you don't use `bundle exec`
[04:08:30]: to launch fastlane faster, please use
[04:08:30]:
[04:08:30]: $ bundle exec fastlane test
[04:08:30]:
[04:08:30]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Traceback (most recent call last):
        21: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        20: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
        19: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/fastlane:23:in `<main>'
        18: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/fastlane:23:in `load'
        17: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/bin/fastlane:23:in `<top (required)>'
        16: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        15: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        14: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        13: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        12: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:73:in `run!'
        11: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:21:in `context_for_action_name'
        10: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:21:in `new'
         9: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:17:in `initialize'
         8: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:56:in `android_app_identifier'
         7: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:73:in `guess_package_name'
         6: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:38:in `guess_package_name_from_appfile'
         5: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:10:in `try_fetch_value'
         4: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:10:in `new'
         3: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:34:in `initialize'
         2: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:34:in `chdir'
         1: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:46:in `block in initialize'
/Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:46:in `eval': (eval):2: syntax error, unexpected tIDENTIFIER, expecting ')' (SyntaxError)
package_name("com.tennisconnect")
              ^~~
(eval):3: unterminated string meets end of file
  </pre>
</details>

### Environment

<details>
  <pre>
   [04:09:42]: fastlane detected a Gemfile in the current directory
[04:09:42]: however it seems like you don't use `bundle exec`
[04:09:42]: to launch fastlane faster, please use
[04:09:42]:
[04:09:42]: $ bundle exec fastlane env
[04:09:42]:
[04:09:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Traceback (most recent call last):
        21: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        20: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
        19: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/fastlane:23:in `<main>'
        18: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/bin/fastlane:23:in `load'
        17: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/bin/fastlane:23:in `<top (required)>'
        16: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        15: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        14: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        13: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        12: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:73:in `run!'
        11: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:21:in `context_for_action_name'
        10: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:21:in `new'
         9: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:17:in `initialize'
         8: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:56:in `android_app_identifier'
         7: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:73:in `guess_package_name'
         6: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:38:in `guess_package_name_from_appfile'
         5: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:10:in `try_fetch_value'
         4: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:10:in `new'
         3: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:34:in `initialize'
         2: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:34:in `chdir'
         1: from /Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:46:in `block in initialize'
/Users/jongbanaag/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/appfile_config.rb:46:in `eval': (eval):2: syntax error, unexpected tIDENTIFIER, expecting ')' (SyntaxError)
package_name("com.tennisconnect")
              ^~~
(eval):3: unterminated string meets end of file
  </pre>
</details>

**Comment by janpio** [comment]
What does your `Fastfile` look like?

**Comment by aabanaag** [comment]
![image](https://user-images.githubusercontent.com/2245822/53915491-fcaf5100-409a-11e9-9135-164565d1096d.png)

I just initialized fastlane with `fastlane init` then just wanted to test out the lane but then the error occures. Happened when I was using 2.4.1 ruby version same as the current one 2.6.1

**Comment by janpio** [comment]
Any other configuration files for fastlane? `Appfile`, `Gymfile` or similar?

**Comment by aabanaag** [comment]
No. Appfile is minimal. No gym file either. Also would it matter as I skipped setting up supply? I have not playstore account yet so no json file I was under the assumption that it would be good as I can run fastlane supply init later once I procured the necessary account

**Comment by janpio** [comment]
Please post the complete `Appfile`, per the error message this is the cause of your error:
![image](https://user-images.githubusercontent.com/183673/53920602-f951a080-406d-11e9-8e68-5e96c6bc90a3.png)

**Comment by aabanaag** [comment]
![image](https://user-images.githubusercontent.com/2245822/53949057-3b2d2600-4104-11e9-8786-9cbd1952fe7c.png)

I even tried using the sample package_name `com.krause.app` but same error.

**Comment by janpio** [comment]
`\"` is escaping the `"`, thus making it "invisible". 

What are you trying to achieve with this line?

**Comment by aabanaag** [comment]
![image](https://user-images.githubusercontent.com/2245822/53954021-e98a9880-410f-11e9-959e-52045a45c329.png)

I asked a colleague of mine to send his Appfile and noticed the issue with the json_key_file so I removed it but got this instead. Just would like to run fastlane test on my app to test the implementation.

**Comment by janpio** [comment]
That just means that your Android project is not properly setup. You have to have Gradle installed, which usually happens by default if you have your project built once. Otherwise gradle.org/install should help.

**Comment by aabanaag** [comment]
Thank you for the response. But the issue with _gradlew_ is that I haven't created a build for my app yet. Running `flutter build apk` created _gradlew_ which then eliminates the error when running `fastlane test`
