### ISSUE TITLE
How do I localise individual_metadata_items to see which app name isnt getting accepted?

### ISSUE THREAD

**Issue by adi101010** [fastlane/fastlane#14354]
### Question Checklist
I am trying to use deliver to upload all the app names, but I keep on getting the message
"Error in app name.  Try using 'individual_metadata_items' to identify the problem language."

How do I use individual_metadata_items in my deliverfile?

Thanks

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by janpio** [comment]
From the docs:

> An array of localized metadata items to upload individually by language so that errors can be identified. E.g. ['name', 'keywords', 'description']. Note: slow

So in your case probably just `['name']`.

**Comment by adi101010** [comment]
Hi
Thanks for replying. I did not understand how to use that / localise that. 

Can you please give me an example as to how i can use it for multiple localisations. 

Many thanks

**Comment by janpio** [comment]
`deliver(
  ...
  individual_metadata_items: ['name']
)`

**Comment by adi101010** [comment]
I use a deliverfile. How can I use it in that?

Sorry if its a stupid question. 

Thanks

**Comment by janpio** [comment]
You can try adding `individual_metadata_items(['name'])`, but I am not sure this will work.

**Comment by adi101010** [comment]
I tried this it doesnt work. 

Also I dont know how will localisations be added to this.

**Comment by janpio** [comment]
This will submit the metadata items individually for the key you specified, thus making it easier to identify the reason for any problems.

**Comment by adi101010** [comment]
Hey 

I just tried it again and it worked with the deliverfile. Many thanks for helping out.

individual_metadata_items ['name']

Worked!

**Comment by janpio** [comment]
nice!
