### ISSUE TITLE
git actions - clone repository by URL

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14358]
#### Motivation Behind Feature
Sometimes it's important to work with another repository (not the one in which Fastlane is currently running).

For example, in this setup:
1. Clone sources from a remote repository (not the one where Fastlane is installed)
2. Compile sources
3. Put the artifacts into current repository, replace old artifacts
4. Commit & Push changes to current repository

Git actions, such as [git_pull](https://docs.fastlane.tools/actions/git_pull/) cannot help with the step 1, so I have to resort to `sh` scripts to achieve the desired result.

#### Feature Description

Accept additional parameters such as:
- source URL
- branch
- etc, e.g. commit / tag

in git commands.

Code example:
```Ruby
git_pull(source: "https://github.com/fastlane/fastlane", folder: "fastlane_repository")
```

This won't break anything for the current users.

#### Alternatives or Workarounds
```Ruby
    # Getting Proto files
    sh('git clone https://github.com/fastlane/fastlane')

    # Getting version number
    last_tag = sh("
                        cd fastlane
                        git describe --abbrev=0 --tags | tr -d '\n'
                      ")
```

**Comment by mollyIV** [comment]
👋 @richardtop Thanks for posting the proposal 👍 

>1. Clone sources from a remote repository (not the one where Fastlane is installed)
> 2. Compile sources
> 3. Put the artifacts into current repository, replace old artifacts
> 4. Commit & Push changes to current repository

Please correct me if I am wrong, but the feature ☝️sounds like something that you might achieve with a help of [`carthage` action](https://docs.fastlane.tools/actions/carthage/). If you haven't heard about Carthage it is 
> a simple, decentralized dependency manager for Cocoa. 

You can find more info on [Carthage repository](https://github.com/Carthage/Carthage). 

Please let us know if that might work for you 🙇

**Comment by richardtop** [comment]
Can Carthage action clone an arbitrary repository, which is not a Carthage dependency? I wasn't able to find a way to specify an arbitrary URL address.

**Comment by johnknapprs** [comment]
Why not Submodules?  I personally don't like working with them, but they might suit your needs. 

Or you can make a plug-in for git cloning and it'll get indexed on the docs site for fastlane.

**Comment by mollyIV** [comment]
> Can Carthage action clone an arbitrary repository, which is not a Carthage dependency?

I thought that you need `git_clone` action in order to download the project (your dependency) from GitHub and eventually compile it and add it to your project. With that in mind, that's why I suggested to use Carthage. You can easily add GitHub dependencies to your `Cartfile`:

```
github "Alamofire/Alamofire" ~> 4.7.2
```
