### ISSUE TITLE
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD is being ignored by upload_to_testflight step

### ISSUE THREAD

**Issue by mpdifran** [fastlane/fastlane#14365]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've set the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` environment variable (using TravisCI's tools) with a properly generated password, but it seems `upload_to_testflight` is ignoring this value, and prompting me for my regular password (which will not work on Travis). The only environment variables set in Travis are `MATH_PASSWORD` and `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.

**Note**: The issue occurs in the last step of my `beta` lane (`upload_to_testflight`). Output below has been limited to that step.

##### Command executed
`fastlane run upload_to_testflight`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> $ fastlane upload_to_testflight
[20:18:40]: ----------------------------------
[20:18:40]: --- Step: upload_to_testflight ---
[20:18:40]: ----------------------------------
[20:18:40]: Login to App Store Connect (me@email.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
+------------------------------------+-----------------------------------------------------------------------------------------------+
|                                                            Lane Context                                                            |
+------------------------------------+-----------------------------------------------------------------------------------------------+
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/travis/Library/Keychains/fastlane_tmp_keychain-db"                                    |
| DEFAULT_PLATFORM                   | ios                                                                                           |
| PLATFORM_NAME                      | ios                                                                                           |
| LANE_NAME                          | ios beta                                                                                      |
| BUILD_NUMBER                       | 94                                                                                            |
| SIGH_PROFILE_TYPE                  | app-store                                                                                     |
| MATCH_PROVISIONING_PROFILE_MAPPING | {[redacted]}                                                                                  |
| IPA_OUTPUT_PATH                    | /Users/travis/build/Faire/ios-Retailer/Faire.ipa                                              |
| DSYM_OUTPUT_PATH                   | /Users/travis/build/Faire/ios-Retailer/Faire.app.dSYM.zip                                     |
| XCODEBUILD_ARCHIVE                 | /Users/travis/Library/Developer/Xcode/Archives/2019-03-07/Faire 2019-03-07 20.16.57.xcarchive |
+------------------------------------+-----------------------------------------------------------------------------------------------+
[20:18:40]: Missing password for user me@email.com, and running in non-interactive shell
+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 💥   | upload_to_testflight   | 0           |
+------+------------------------+-------------+
[20:18:40]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': [!] Missing password for user me@email.com, and running in non-interactive shell (RuntimeError)
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:374:in `login'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/pilot/lib/pilot/manager.rb:23:in `login'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/pilot/lib/pilot/manager.rb:16:in `start'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/pilot/lib/pilot/build_manager.rb:13:in `upload'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.117.1/bin/fastlane:23:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
The command "fastlane upload_to_testflight" exited with 1. </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Sets up Match locally for development ensuring no new certificates are created."
  lane :setupMatch do
  	match(readonly: true)
  end

desc "Sign the app for release and distribute it to TestFlight. Meant to be run by TravisCI."
  lane :beta do
  	setup_travis
  	increment_build_number(build_number: ENV["TRAVIS_BUILD_NUMBER"])
  	match(type: "appstore")
  	gym
  	upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("[redacted]")
apple_id("[redacted]")


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-03-07**
</details> </pre>
</details>

**Comment by janpio** [comment]
`upload_to_testflight` does not completely work with just an app specific password as it also uses APIs that require a password (only uploading the binary can be done with an app specific password, updating a changelog or polling the build status etc uses a different API)

As you are on CI, have a look at this: https://docs.fastlane.tools/best-practices/continuous-integration/#authentication-with-apple-services

**Comment by mpdifran** [comment]
Ah ok, I was wondering if that was the case, but I was misled a bit by this section of the docs you linked: 

```
If you want to upload builds to App Store Connect (actions upload_to_app_store and deliver) or TestFlight (actions upload_to_testflight, pilot or testflight) from your CI machine, you need to generate an application specific password:
```

I can open a PR to reword it.

I ended up creating a CI user that does not have 2FA enabled and authenticated with user & pass.

**Comment by Speakus** [comment]
The new description is not so clear. which options are allowed to use only FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD and no anything else?

**Comment by janpio** [comment]
What do you refer to @Speakus? `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` only affects the "upload binary" portion of the logic, everything else uses the usual other options.

**Comment by Speakus** [comment]
I mean: should we use option `skip_submission: true` only if we want to use pass from FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD only?

**Comment by janpio** [comment]
You can always use `skip_submission: true`, but if you want have something uploaded via the usage of an application specific password, and not use a normal password (and potentially 2FA) you _have_ to use it.

**Comment by Speakus** [comment]
I want pilot to do not use FASTLANE_PASSWORD and only use FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD. is it possible?
The code does not work:
```
upload_to_testflight(skip_waiting_for_build_processing: true, skip_submission: true)
```
It still try to use FASTLANE_PASSWORD on my side :(

**Comment by janpio** [comment]
Currently probably not possible, as I rediscovered my 1 month old comments after https://github.com/fastlane/fastlane/issues/14258#issuecomment-466162639
Someone will have to implement https://github.com/fastlane/fastlane/issues/14342 based on the current code to make this possible reliably.

**Comment by mykyta-bondarenko-gl** [comment]
hi @janpio. I have the similar issue 
```
package_path = FastlaneCore::ITMSPUploadPackageBuilder.new.generate(app_id: [id],
                                                                    app_archive_path: [path],
                                                                    itmsp_package_path: '/tmp',
                                                                    platform: [platform])
transporter = FastlaneCore::ItunesTransporter.new([USERNAME], [PASSWORD_ITC])
result = transporter.upload({app_apple_id], package_path)
```

I've generated a session and put it to the `FASTLANE_SESSION` variable to log in. Also, I put previously generated a specific password to the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` variable. Login complete successfully but not `transporter.upload`

Output
```
[Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
Transporter transfer failed.

Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)

Application specific password you provided using
environment variable FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
is invalid, please make sure it's correct

Invalid application specific password provided
```


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.117.1 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.1        |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.1        |
| faraday_middleware        | 0.13.1       |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| emoji_regex               | 1.0.1        |
</details>


*generated on:* **2019-03-21**
</details>

**Comment by janpio** [comment]
Please open a new issue @mykyta-bondarenko-gl and answer these question there: What is the code you included here? Are you not using a fastlane action but rolling your own?

**Comment by mykyta-bondarenko-gl** [comment]
@janpio done: https://github.com/fastlane/fastlane/issues/14445

**Comment by wstewartii** [comment]
Is there any update on this?
