### ISSUE TITLE
bitrise  react native build fastlane error /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1

### ISSUE THREAD

**Issue by sarayut999** [fastlane/fastlane#14368]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
You will have to give us more information than what you posted in the title. Best fill the issue template with what it asks for, then we can maybe help you.
