### ISSUE TITLE
sigh repair fails as App had been moved to other account

### ISSUE THREAD

**Issue by koxon** [fastlane/fastlane#14361]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to clean my old profiles but sigh fails as the App has been moved to another Apple developer team.

I run this:
`bundle exec fastlane sigh repair -b E3XWH3A9EA -l "bFAN Sports" --force`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
✔] 🚀
[14:37:27]: Starting login with user 'dev-ios@bfansports.com'
[14:37:31]: Successfully logged in
[14:37:32]: Going to repair 44 provisioning profiles
[14:37:32]: Repairing profile 'match AdHoc com.bfansports.sectionpaloise.ios.qa'...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] Apple provided the following error info:
	There is no IOS App ID with ID '3KMWCT5999' on this team.

</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Isn't this expected? When the app ID is not there any more, there is nothing to fix here, right?

**Comment by koxon** [comment]
Well I have old provisioning profiles that remains that I'd like to clean.
Sounds like a legit need.

**Comment by janpio** [comment]
Yes, I get that. But you are calling `repair` - Is removing old provisioning profiles a repair task?

**Comment by koxon** [comment]
correct @janpio my bad. sorry

**Comment by janpio** [comment]
Don't worry.

Is there actually some command to "clean up" as you wanted to? Maybe this makes sense to add!
