### ISSUE TITLE
Fastlane Boarding still actively maintained?

### ISSUE THREAD

**Issue by FinHorsley** [fastlane/fastlane#14376]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Fastlane Boarding

#### Question Description
Apologies for posting this here. I have been working on some new features for [FastLane Boarding](https://github.com/fastlane/boarding/find/master), but since making a PR, I haven't heard anything. Could someone please confirm that Boarding is still being actively maintained?

**Comment by janpio** [comment]
It definitely hasn't been on my radar, but I am following the repo now.

But I also don't see any recent issues or pull requests, so there doesn't seem to much to do right now.

**Comment by FinHorsley** [comment]
Haven't had the time to make any changes recently, but some are on the way!
