### ISSUE TITLE
Can app-specific password be used for developer portal login?

### ISSUE THREAD

**Issue by 0x5e** [fastlane/fastlane#14377]
Two-step/two-factor auth is really unfriendly to ci system. I have a requirement to login varies of apple accounts to create certificate, create/edit appid, create/update mobileprovision (in ci system), just like Cydia Impactor do. It has capability to login with app-specific password, is it possible that spaceship can support app-specific password login for apple developer portal too?

**Comment by jaimeohm** [comment]
@0x5e I'm pretty sure I'm doing this using the environment variable "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD". I hope this helps!

**Comment by jaimeohm** [comment]
Ah! I see you're looking for the developer portal, not appstoreconnect. I'm using match and I've created a different branch for each team I need to login to. This direction might work for your needs, too.

**Comment by 0x5e** [comment]
@jackbrown actually i'm create certificate for my customers' accounts, they are not developers, and there's always new accounts added in. branches may not suit me. two-factor login works fine at present, if app-specific can be used will be much better. :-)

**Comment by janpio** [comment]
App specific password only work for uploading binaries, as this is done via an external app. All the metadata or codesigning stuff uses an API that does not accept app specific passwords.

**Comment by jaimeohm** [comment]
@0x5e I use match to manage my certificates for multiple customers. See "Multiple teams" and this tool "https://docs.fastlane.tools/actions/match/" for scripting the developer portal.
