### ISSUE TITLE
Idea: Finally Block

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/fastlane#1437]
Is it nesseccery to add a `final_code` block similar to before_all, after_all and error block ?

fastlane : `before_all`, `after_all`, `error`.

I compare it with java or other languages 

```java
  try {
      before_all
      some_lane
      after_all
  }catch(Exception e){
      error
  }finally{
      final_code
  }
```

For example, I usually **`reset_git_repo`** whatever success or failure. so I need to add **`reset_git_repo`** action in both **`after_all`** and **`error`** , so I think it is a common need for developers

**Comment by ohwutup** [comment]
Hey @MickeyHub, this is a really nice idea! Definitely we could use something to do any final cleanup no matter the result. We will keep this marked as a feature request and close the issue for now but we will reopen it and update it as soon as we can tackle this on a new release. If you want to submit a PR with this functionality, that would also be awesome! :tangerine:
