### ISSUE TITLE
promote_track with custom version code

### ISSUE THREAD

**Issue by danilobuerger** [fastlane/fastlane#14374]
#### Motivation Behind Feature

Currently `promote_track` takes the active version code of `track` and promotes that to `track_promote_to`. However, the play console allows promoting previous versions too. This would help with CI / CD when manually promoting to a track that is not the current one.

#### Feature Description

There should be an additional flag used by `promote_track` that skips `client.track_version_codes` and uses that instead when executing `client.update_track`.

#### Alternatives or Workarounds

No workaround known.

**Comment by janpio** [comment]
Suggestion on what this flag/option/param should be called?

That being said: 
What `promote_track` action are you talking about? I only found a `track_promote_to` option for supply/upload_to_play_store.

**Comment by danilobuerger** [comment]
@janpio https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L65-L71
I don't really have an opinion on what the flag should be called.

**Comment by janpio** [comment]
Hm, what would a `supply` call look like that can _currently_ be used to promote an app and what would a new usage of this feature look like? (I am really not very fluent with Android and the tracks in Play Console)

**Comment by danilobuerger** [comment]
@janpio So right now you can do:
```
upload_to_play_store(
  track: "beta",
  track_promote_to: "production"
)
```
This would take the current active versions and promote them from beta to production. But usually you would want to promote a certain version to production that has been tested and might not be the newest beta version. I imagine doing something like this then:
```
upload_to_play_store(
  track: "beta",
  track_promote_to: "production",
  track_promote_version_codes: [1,2,3] 
)
```
This would then promote the versions 1, 2 and 3 from beta to production. (In most use cases this would just be one, but multiple active versions are allowed).

I don't know ruby, but possibly this is just a one liner change at:
```
version_codes = client.track_version_codes(Supply.config[:track])
```
to check first if `track_promote_version_codes` (or whatever its name is) is set and use that instead of calling `client.track_version_codes`.

**Comment by janpio** [comment]
Yes, the implementation is probably pretty simple - but the API for the user is complicated.

Would it make sense to extract that promotion stuff to its own action maybe? This doesn't really have to do anything with "upload to play store", right?

**Comment by danilobuerger** [comment]
Personally, I would agree. Even without this feature request (just having `track_promote_to`) it feels like it should be its own action.

**Comment by janpio** [comment]
You know more about tracks and related things than me, what else would be part of the current parameters/options to consider for this new action? `promote_track_on_play_store` a fitting name?

**Comment by danilobuerger** [comment]
Since everything else can still be done through `upload_to_play_store`, it feels like you would just need:
```
promote_track_on_play_store(
    from: "beta",
    to: "production",
    version_codes: [1,2,3] // optional, if not set use active versions of `from`,
    rollout: 0.1 // optional, see comment in `promote_track`
)
```

**Comment by janpio** [comment]
What happens if one of the version codes is not part of `from`? Error message? Ignore?

**Comment by danilobuerger** [comment]
Personally, I would say error. I like failing in an obvious way instead of something happening silently that I have to chase down.

**Comment by danilobuerger** [comment]
Feature request.

**Comment by awgeorge** [comment]
Would love to have this feature.

**Comment by danilobuerger** [comment]
Feature request.

**Comment by danilobuerger** [comment]
Feature request.
