### ISSUE TITLE
[onesignal] Updating an OneSignal app (PUT request)

### ISSUE THREAD

**Issue by anh1979** [fastlane/fastlane#14381]
#### Motivation Behind Feature
Push notification certificates expire after a certain time (one year). The onesignal action can only create new apps via OneSignal API, but not update existing ones.

#### Feature Description
It would be nice to be able to update an existing OneSignal app (created by the onesignal action, which is using a POST request to the Onesignal API) with a newly created .p12 by using the PUT request on the OneSignal API with the same params. 
https://documentation.onesignal.com/reference#update-an-app

This might be even possible by just adding a new param / flag identifying whether the action should create or update an app.

#### Alternatives or Workarounds
Creating the certificate on the command line, when the old one is expired and manually editing the OneSignal App via browser interface (or via curl).

Thank you.

**Comment by anh1979** [comment]
Still a valid feature request

**Comment by revolter** [comment]
@anh1979, Could you test [my branch](https://github.com/revolter/fastlane/tree/feature/onesignal-update) before the PR #15288 gets merged?

**Comment by anh1979** [comment]
Sorry, @revolter --> saw this just now - will check it out during the next days. Thank you

**Comment by anh1979** [comment]
Works like a charm - thank you.
