### ISSUE TITLE
Able to get the current Android and ios build numbers from `master` branch, even if on feature branch?

### ISSUE THREAD

**Issue by dbarner1** [fastlane/fastlane#14389]
### Question Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question
Is it possible to get the current ios and android build numbers on the master branch?  Say, I'm developing on branch `123-feature-awesome`.  I'd like `123-feature-awesome` to get the `master` branch build number, increment by 1, and push a version bump to master and my feature branch (so all branches can be kept up to date).  Possible?  Thank you!!!

**Comment by janpio** [comment]
What is the context to fastlane here? Are you talking about a specific action?

**Comment by dbarner1** [comment]
Yes - Say I'm on feature branch "123-product-change".  I'm hoping when I
deploy it to ios beta that when I call `get_build_number` I could call it
from `master`, and then `commit_version_bump` with that number, to keep
`123-product-change` and `master` in sync (and all other future branches).

Hopefully makes sense?

**Comment by janpio** [comment]
More than before in any case - as https://docs.fastlane.tools/actions/get_build_number/ is an action in fastlane 👍 

So although you have `123-product-change` checked out, you want the `get_build_number` return value for the `master` branch?

**Comment by dbarner1** [comment]
yup!

**Comment by janpio** [comment]
Hm, the command actually uses [`agvtool`](https://developer.apple.com/library/ios/qa/qa1827/_index.html) to get the version out of the Xcode project file - and it works on the local checkout you have. 

So to apply that on `master`, you either have to a) checkout `master` temporarily, or b) clone `master` into a subfolder and then use the `xcodeproj` param to specify the Xcode project file.

**Comment by dbarner1** [comment]
Great, thanks @janpio !
