### ISSUE TITLE
No multi scan support for fastlane swift

### ISSUE THREAD

**Issue by MurtazaSaify** [fastlane/fastlane#14385]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
Going to close this issue since no issue since there is not description of the issue, question, or requested feature. Please open another issue with all requested information and I will be happy to look into 😊
