### ISSUE TITLE
I got a 'Potential server error received: 'Unexpected Error'' when uploading metadata to App Store Connect 

### ISSUE THREAD

**Issue by iamhyw** [fastlane/fastlane#14382]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I uploading the metadata, I got 'Potential server error received: 'Unexpected Error''. But yesterday,I can upload the metadata successfully. What happen to the App Store Connect? Or maybe my network was broken? Is anybody got the same problem?

##### Command executed

uploadInstance = Deliver::UploadMetadata.new
uploadInstance.upload(metadata)
##### Complete output when running fastlane, including the stack trace and command used

Potential server error received: 'Unexpected Error'
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.5.0/bin/fastlane       |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.0       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-03-11**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by iamhyw** [comment]
is anybody home?

**Comment by janpio** [comment]
Your issue is missing information required to understand what is going on.
Are you using deliver out of the context of fastlane?
What is the complete output you get when running your code?

**Comment by iamhyw** [comment]
I'm sorry for what I said before. 
These are my  code.   @janpio 

    sendRequest[:app] = app

	languagePath = metaDataPath + 'languages.xlsx'
	baseInfoPath = metaDataPath + 'base.xlsx'

 	reviewInfoPath = metaDataPath + 'review_information/'
 	tradeInfoPath = metaDataPath + 'trade_representative_contact_information/'

	languages = []
	necessaryText = [:name, :subtitle, :keywords, :description, :support_url, :promotional_text, :release_notes, :privacy_url]

	doc = SimpleXlsxReader.open(languagePath)
	sheet = doc.sheets.first

	languagesPos = 0

	sendRequest[:privacy_url] = {}
	
	sheet.rows.each { |row| 
		languageStr = row[languagesPos]
		if not languageStr
			break
		end
		languageData = languageStr.split(",")
		language = languageData[0]
		
		languages.push(language)

		curPos = 0
		necessaryText.each do |key|
			curPos = curPos + 1
			if row and row[curPos] and row[curPos].length > 0 then 
				if not sendRequest.has_key?key then
					sendRequest[key] = {}
				end

				sendRequest[key][language] = row[curPos].strip()
			end
		end
	}

 	sendRequest[:languages] = languages

 	noLanguageValues = [:primary_category, :primary_first_sub_category, :primary_second_sub_category,:secondary_category, :copyright]

 	if File::exists?(baseInfoPath) then
	 	doc = SimpleXlsxReader.open(baseInfoPath)
		row = doc.sheets.first.headers

		curPos = 0
		if row then 
			noLanguageValues.each do |key|
		    	if row[curPos] and row[curPos].length > 0 then 
		    		sendRequest[key] = row[curPos]
		    	end
		    	curPos = curPos + 1
		    end
		end

		reviewInfos = [:demo_user,:demo_password,:email_address,:phone_number,:first_name,:last_name]

		if row then 
			curIndex = 0
			reviewInfos.each do |key|
		    	if row[curPos] and row[curPos].length > 0 then 

		    		if not sendRequest[:app_review_information] then 
		    			sendRequest[:app_review_information] = {}
		    		end 

		    		sendRequest[:app_review_information][key] = row[curPos]

		    		if curIndex > 1 then 
		    			if not sendRequest[:trade_representative_contact_information] then 
			    			sendRequest[:trade_representative_contact_information] = {}
			    		end
			    		sendRequest[:trade_representative_contact_information][key] = row[curPos]
		    		end
		    	end

		    	curPos = curPos + 1
		    	curIndex = curIndex + 1
		    end
		end
	end

    sendRequest[:automatic_release] = false

    sendRequest[:app_rating_config_path] = $commonDir + '_rating_config.json'

    uploadInstance = Deliver::UploadMetadata.new
    uploadInstance.upload(sendRequest)

I use my own way for upload metadata for all the languages. 
I got this problem all the time -> Uploading metadata to App Store Connect Potential server error received: 'Unexpected Error'. Retrying after 10 seconds (remaining: 2)... 
pls help me!

**Comment by janpio** [comment]
Ah interesting!

Do you have any other output from your script?
What does the spaceship logs at `/tmp/spaceship*.log` contain?

**Comment by iamhyw** [comment]
[spaceship1553860376_12063_70113974030040.log](https://github.com/fastlane/fastlane/files/3022541/spaceship1553860376_12063_70113974030040.log)
This is my log.

The last line is '{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unexpected Error"]}, "statusCode"=>"ERROR"}'

I can not get conclusion from the log.I have no idea. @janpio

**Comment by janpio** [comment]
Your `POST` to `ra/apps/1456716070/platforms/ios/versions/830664123` is failing for some reason. 

With that URL (and the calls before it) it should be possible to manually go through the code of `uploadInstance.upload` to understand what call triggers the call to the URL that fails - and then understand what data it is sending there and why.

Looking at the request before and the one failing, it seems the code is getting an array from Apple, modifying it slightly and sending it back. And when you send the object back, it doesn't like the content and respond with a 500 error.

My guess is that something in the `sendRequest` you created doesn't match what Apple is expecting and what fastlane would create. Maybe try to do a similar process with fastlane and look at the content of the spaceship logs of those, successful requests and compare to what you have.

Good luck!

**Comment by iamhyw** [comment]
I test what you say. So I just use these code to find out where is wrong.
    sendRequest = {}
    sendRequest[:app] = app
    uploadInstance = Deliver::UploadMetadata.new
    uploadInstance.upload(sendRequest)

But I got the same errors.My guess is that **uploadInstance.upload(sendRequest)**  method got some problem.What does statusCode 500 mean? 

BTY, I had to fill infomation in 37 languages.it is crazy!

**Comment by iamhyw** [comment]
And my code was usable two months ago.I've noticed this week that it doesn't work.
OMG!I got no idea!

**Comment by janpio** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500, but in you case it just means that Apple can't handle whatever you sent to it.

I can't help you further here. Fastlane uses the same method internally, and it works fine.

**Comment by iamhyw** [comment]
Still thanks! @janpio

**Comment by iamhyw** [comment]
I fix it!

**Comment by janpio** [comment]
Can you share what was broken?
