### ISSUE TITLE
Can fastlne be used to change bundle identifier and target capabilities

### ISSUE THREAD

**Issue by manujbahl** [fastlane/fastlane#14399]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

I read the documentation and could not figure out if fastlne allows to change bundle identifier and capabilities information. 
From what I gather, bundle I'd needs to be changed in the project PBX file on iOS and plist just refers to that.

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by max-ott** [comment]
Hi @manujbahl 👋 This is not something `fastlane` is supposed to handle. You can use for example
https://github.com/CocoaPods/Xcodeproj
