### ISSUE TITLE
Unable to upload even after multiple retries

### ISSUE THREAD

**Issue by joelgetaction** [fastlane/fastlane#14396]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm running a simple Fastfile that has succeeded many times and now it has failed 3 times in a row with some ITMS security errors.  However test uploads from Xcode still work, so the issue is NOT with ITC but with Fastlane.  I need to upload using Fastlane and get a build to some high value testers ...

##### Command executed

fastlane iOS testflight_deploy

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
[12:29:56]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[12:29:56]: Going to upload updated app to App Store Connect
[12:29:56]: This might take a few minutes. Please don't interrupt the script.
[12:30:21]: [Transporter Error Output]: unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[12:30:22]: [Transporter Error Output]: An error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[12:30:22]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[12:30:22]: Transporter transfer failed.
[12:30:22]:
[12:30:22]: unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
An error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Could not start delivery: all transports failed diagnostics
[12:30:22]: [iTMSTransporter] [2019-03-14 12:30:21 MDT] <main> DBG-X:   testing host/port: https://itmsdav.apple.com/443 (tcp)

[12:30:22]: [iTMSTransporter] [2019-03-14 12:30:22 MDT] <main> ERROR: An error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[12:30:22]: [iTMSTransporter] [2019-03-14 12:30:22 MDT] <main>  INFO: Done performing transport diagnostic test.

[12:30:22]: [iTMSTransporter] [2019-03-14 12:30:22 MDT] <main> ERROR: Could not start delivery: all transports failed diagnostics

[12:30:22]: [iTMSTransporter]

[12:30:22]: [iTMSTransporter]

[12:30:22]: [iTMSTransporter]

[12:30:22]: [iTMSTransporter] Package Summary:

[12:30:22]: [iTMSTransporter]

[12:30:22]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[12:30:22]: [iTMSTransporter] 	/var/folders/2q/z5vj2cqn4nq7yrxn0_11hsfh0000gn/T/d20190314-36921-1eim971/1456085012.itmsp - Error Messages:

[12:30:22]: [iTMSTransporter] 		unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[12:30:22]: [iTMSTransporter] 		An error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[12:30:22]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics

[12:30:22]: [iTMSTransporter] [2019-03-14 12:30:22 MDT] <main> DBG-X: Returning 1

[12:30:22]: iTunes Transporter output above ^

[12:30:22]: unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
An error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: unable to verify WebDAV transport: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provid\nAn error occurred while connecting to the transport host https://itmsdav.apple.com: sun.security.validator.ValidatorException: PKIX path building failed: sun.securit\nCould not start delivery: all transports failed diagnosticsnd valid certification path to requested target
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.117.1'

# Documentation
#   Version and build numbers:
#     https://developer.apple.com/library/archive/technotes/tn2420/_index.html
#   Changelog:
#     https://keepachangelog.com/en/1.0.0/
#     https://github.com/pajapro/fastlane-plugin-changelog
#   Fastlane:
#     https://docs.fastlane.tools/
#   Gym:
#     https://docs.fastlane.tools/actions/gym/#gym
#   upload_to_testflight:
#     https://docs.fastlane.tools/actions/upload_to_testflight/#upload_to_testflight
#   Advanced Fastlane:
#     https://github.com/fastlane/docs/blob/master/docs/advanced.md

# Constants
workspace = './ios/BidVidClientMobile.xcworkspace'
xcodeproj = './ios/BidVidClientMobile.xcodeproj'
target = 'BidVidClientMobile'
scheme = 'BidVidClientMobile'
sdk = "iphoneos12.1"

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc "Download and sync development provisioning profiles and certificates."
  lane :development_certificates do
    match(
      type: "development",
      app_identifier: [
        "com.getactionllc.BidVidDevo",
      ],
      readonly: true,
    )
  end

  desc "Download and sync appstore provisioning profiles and certificates."
  lane :appstore_certificates do
    match(
      type: "appstore",
      app_identifier: [
        "com.getactionllc.BidVidBeta",
      ],
      readonly: true,
    )
  end

  desc "Perform a development build."
  lane :development_build do
    gym(
      workspace: workspace,
      scheme: scheme,
      configuration: "Debug",
      sdk: sdk,
      export_method: "development",
      clean: true,
    )
  end

  desc "Perform a release build."
  lane :release_build do
    gym(
      workspace: workspace,
      scheme: scheme,
      configuration: "Release",
      sdk: sdk,
      export_method: "app-store",
      clean: true,
    )
  end

  desc "Gather the changelog for the current version number."
  lane :gather_changelog do
    version = get_version_number(
      xcodeproj: xcodeproj,
      target: target,
    )
    
    changelog = read_changelog(
      changelog_path: './CHANGELOG.md',
      section_identifier: "[#{version}]",
    )

    changelog
  end


  desc "Create and upload a new build to TestFlight."
  lane :testflight_deploy do
    appstore_certificates

    build_number = increment_build_number(xcodeproj: xcodeproj)
    version_number = increment_version_number(xcodeproj: xcodeproj, bump_type: "patch")

    changelog = gather_changelog
    UI.message "using changelog #{changelog}"
    UI.user_error!("missing or empty changelog, aborting") if changelog.nil? || changelog.length < 1

    notify_it(title: "#{version_number} (#{build_number}) Starting Release Build", message: "Building the app for TestFlight.")

    release_build

    notify_it(title: "#{version_number} (#{build_number}) Uploading to TestFlight", message: "Uploading the app to TestFlight.")

    upload_to_testflight(
      app_identifier: "com.getactionllc.BidVidBeta",
      username: "joel@getaction.tv",
      changelog: changelog,
    )

    notify_it(title: "#{version_number} (#{build_number}) Committing Version", message: "Committing the version to git and pushing to github.")

    commit_version_bump(message: 'Bump build', xcodeproj: xcodeproj)
    add_git_tag(prefix: "v")
    push_to_git_remote

    notify_it(title: "#{version_number} (#{build_number}) Done", message: "Deploy to TestFlight is complete.")
  end
end

platform :android do
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.14.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.1        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-changelog | 0.14.0       |
</details>

*generated on:* **2019-03-14**
</details>
</pre>
</details>

I have run network diagnostics and my network is fine, no issues.  There are also no issues with ITC that I can see.  This seems to be a Fastlane bug.  Fastlane should retry here instead of bailing so soon ...

**Comment by ronJobox** [comment]
I have the same issue. Manual uploads work fine.

**Comment by joelgetaction** [comment]
Thanks for confirming @ronJobox .  So this seems like a bug in Fastlane then, maybe Apple changed their API?

Fastlane team, any ideas how to fix this?

**Comment by prsolucoes** [comment]
Hi,

Same problem here too. Our apps stop upload with the same error.

Thanks.

**Comment by rafsouzap** [comment]
I've the same problem here. Manual uploads OK.

**Comment by joelgetaction** [comment]
I just watched Fastlane fail to upload, then instantly switched to Xcode and manually uploaded the same build and it worked just fine.  So the ITC API is working just fine, the issue is clearly with Fastlane ... :-(

**Comment by tprevost-phunware** [comment]
Yep, all my uploads are failing today with this same error.

**Comment by tprevost-phunware** [comment]
Update: seems to be working now, since my uploads are working now. I guess Apple changed/fixed something on their end.

**Comment by joshdholtz** [comment]
Is everything working for everyone now?! I saw some weird stuff today where all of my builds were in a processing state so I wonder if that was related 🤔

**Comment by janpio** [comment]
Hey everyone, is this still failing for you @joelgetaction @ronJobox @prsolucoes @rafsouzap @tprevost-phunware?

**Comment by prsolucoes** [comment]
Hi,

For me it is ok now.

Thanks.

**Comment by rafsouzap** [comment]
> Hey everyone, is this still failing for you @joelgetaction @ronJobox @prsolucoes @rafsouzap @tprevost-phunware?

That's OK!

**Comment by janpio** [comment]
Thanks for the feedback.
