### ISSUE TITLE
There is no way to retry the download_dsyms task

### ISSUE THREAD

**Issue by gregkerzhner** [fastlane/fastlane#14393]
### Feature Request
The download_dsyms task can fail because the dsyms are not ready for download.  In this case, it is useful to wait a certain amount of time and retry the download again.  However, the current task does not throw an error if the download fails, it just prints a message to the console.  

We could either add an extra option as `should_fail_if_dsyms_not_ready`, or maybe better, have the task itself return a value `{did_fetch_dsyms: true/false ...}`.  This way, tasks have a way of retrying failed dsyms downloads automatically. 

We have forked this task locally to have this feature, and I am happy to submit a pull request back.  
#### Motivation Behind Feature
This would allow us to keep running a task until the dsym download succeeds.

#### Alternatives or Workarounds
There are no workarounds currently, except for maybe monkeypatching the IO module and trying to read the last message.

**Comment by joshdholtz** [comment]
@gregkerzhner Heyyyyy! There is actually a PR out for this right now 😊 https://github.com/fastlane/fastlane/pull/14137

I have to make one change in this PR to add an option that is similar to your `should_fail_if_dsyms_not_ready` to not wait for them and then this will be shipped. Does this sound like it will work for your request? 😊

**Comment by gregkerzhner** [comment]
Hey @joshdholtz good to hear its already in progress!  I think in our usecase I would be fine with or without the option to wait, since we are always looking to wait, but I can see how its a useful option for others, so if possible we should add it.

**Comment by bryanstearns** [comment]
For what it's worth - I hit this problem to, and worked around it for now by wrapping the `downloaded_dsym` call with retrying, looking for the downloaded file:
```ruby
    downloaded_dsym = "../#{BUILD_DIR}/#{BUNDLE_ID}-#{VERSION}-#{BUILD_NUMBER}.dSYM.zip"
    File.delete downloaded_dsym if File.exist?(downloaded_dsym)
    while true
      download_dsyms(
        version: VERSION,
        build_number: BUILD_NUMBER,
        output_directory: BUILD_DIR,
      )
      break if File.exist?(downloaded_dsym)
      puts "Waiting a bit before retrying..."
      sleep(30)
    end
```
