### ISSUE TITLE
Supply gets stuck and fails to upload apks

### ISSUE THREAD

**Issue by mwajeeh** [fastlane/fastlane#14390]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

supply(
        track: "beta",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
    )
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> | 💥   | supply                           | 667         |
+------+----------------------------------+-------------+

[12:05:19]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  I got a 'Potential server error received: 'Unexpected Error'' when uploading metadata to App Store Connect
    https://github.com/fastlane/fastlane/issues/14382 [open] 1 💬
    13 hours ago

➡️  Fastlane Upload : Unexpected Error
    https://github.com/fastlane/fastlane/issues/14214 [open] 4 💬
    3 hours ago

➡️  fastlane pilot app store connect login error through Jenkins with FASTLANE_USER FASTLANE_PASSWORD Credential Bindings
    https://github.com/fastlane/fastlane/issues/14089 [open] 6 💬
    a week ago

and 677 more at: https://github.com/fastlane/fastlane/search?q=Server%20error&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/mwajeeh/.rbenv/versions/2.5.1/bin/fastlane)
Google::Apis::ServerError: [!] Server error
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:221:in `check_status'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/api_command.rb:118:in `check_status'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:183:in `process_response'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:170:in `process_response'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:249:in `execute_once'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/generated/google/apis/androidpublisher_v2/service.rb:631:in `upload_apk'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/client.rb:257:in `block in upload_apk'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/client.rb:80:in `call_google_api'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/client.rb:256:in `upload_apk'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/uploader.rb:184:in `upload_binary_data'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/uploader.rb:141:in `block in upload_apks'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/uploader.rb:140:in `each'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/uploader.rb:140:in `upload_apks'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/supply/lib/supply/uploader.rb:27:in `perform_upload'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:108:in `block (2 levels) in parsing_binding'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/mwajeeh/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.117.1/bin/fastlane:23:in `<top (required)>'
  /Users/mwajeeh/.rbenv/versions/2.5.1/bin/fastlane:23:in `load'
  /Users/mwajeeh/.rbenv/versions/2.5.1/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

#https://docs.fastlane.tools/actions/hockey/
   #android channel hook
  ENV["SLACK_URL"]  = "https://hooks.slack.com/services/x/x/x"
  #testing
#  ENV["SLACK_URL"]  = "https://hooks.slack.com/services/x/x/x"
  desc "Build and Deploy a new version to the Hockeyapp"
  lane :deployHockey do
    # clean everything
    ensure_git_status_clean
    gradle(task: "clean")
    gradle(
        task: "assemble",
        flavor: "slow",
        build_type: "staging"
    )
    tagBuild(tagFolder: "staging")
    hockey(
      api_token: "token",
      create_update: false,
      ipa: "./baymax/build/outputs/apk/slow/staging/baymax-slow-armeabi-v7a-staging.apk",
      dsym: "./baymax/build/outputs/mapping/slow/staging/mapping.txt",
      status: "2",
      notify: "0"
    )
    slack(
        slack_url: ENV["SLACK_URL"],
        message: "New Some Staging build is out." ,
        payload: {"Download"=> lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK] },
        default_payloads: [],
        success: true
    )
  end

#  desc "Deploy a new production version to the Google Play"
#  lane :productionPlaystore do
#    gradle(task: "clean")
#    gradle(
#        task: "assemble",
#        flavor: "slow",
#        build_type: "release"
#    )
#    supply(
#        track: "rollout",
#        rollout: "0.5",
#        skip_upload_metadata: true,
#        skip_upload_images: true,
#        skip_upload_screenshots: true
#
#     )
#    slack(
#        slack_url: "https://hooks.slack.com/services/x/x/x",
#        message: "New Some Production version is out." ,
#        payload: {"Download"=> "https://play.google.com/store/apps/details?id=com.some.messenger"},
#        default_payloads: [],
#        success: true
#    )
#   end

  desc "Run release unit tests"
  lane :unitTests do
  gradle(
        task: "test",
        flavor: "slow",
        build_type: "release"
  )
  end

  desc "Deploy a new beta version to the Google Play"
  lane :betaPlaystore do
    # clean everything
    ensure_git_status_clean
    ensure_git_branch(
      branch: 'master'
    )
    gradle(task: "clean")
    # run unit tests
    unitTests
    # assemble build
    gradle(
        task: "assemble",
        flavor: "slow",
        build_type: "release"
    )
    tagBuild(tagFolder: "release")
    # upload build
    supply(
        track: "beta",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
    )
    #post notification to product-support
    slack(
        slack_url: "https://hooks.slack.com/services/x/x/x",
        message: "New Some Beta version is out." ,
        payload: {"Download"=> "https://play.google.com/apps/testing/com.some.messenger"},
        default_payloads: [],
        success: true
    )
  end

  private_lane :tagBuild do |options|
      #add tag
      properties = property_file_read(file: "version.properties")
      add_git_tag(
              tag: "#{options[:tagFolder]}/#{properties['git_tag']}"
      )
      push_git_tags
  end

  desc "Download latest schema and place it in graphql folders"
  lane :updateSchema do
  sh('pwd')
  sh("rm -f ./schema.json")
  sh("rm -f ./schema_sorted.json")
  schema = `curl https://msg-api.some-dev.com/schema`
  if $?.exitstatus == 0
    File.write('./../baymax/schema.graphql', schema)
  else
    raise schema
  end
  sh("apollo service:download --endpoint=https://msg-api.some-dev.com/graphql schema.json")
  #sh("cat ./schema.json | jq --sort-keys -c '.' >> schema_sorted.json")
  sh("cp ./schema.json ./../domain/src/main/graphql/com/some/messenger/domain/apollo/schema.json")
  sh("cp ./schema.json ./../baymax/src/main/graphql/com/some/messenger/apollo/schema.json")
  sh("rm ./schema.json")
  #sh("rm ./schema_sorted.json")
  end

  desc "For testing slack integration"
  lane :testSlack do
    slack(
        slack_url: ENV["SLACK_URL"],
        message: "New Some Production version is out." ,
        payload: {
            "Version Name": get_version_number,
            "Download": "https://play.google.com/store/apps/details?id=com.some.messenger"
            },
        default_payloads: [],
        success: true
    )
  end
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.some.messenger" # e.g. com.krausefx.app
json_key_file "./baymax/fastlane_playstore_access.json"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-property_file_read | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.2.0        |
| slack-notifier                     | 2.3.2        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 1.8.0        |
| terminal-table                     | 1.8.0        |
| CFPropertyList                     | 3.0.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| public_suffix                      | 2.0.5        |
| tty-screen                         | 0.6.5        |
| babosa                             | 1.0.2        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| excon                              | 0.62.0       |
| unf_ext                            | 0.0.7.5      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20180417 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| gh_inspector                       | 1.1.3        |
| mini_magick                        | 4.5.1        |
| multi_json                         | 1.13.1       |
| multi_xml                          | 0.6.0        |
| rubyzip                            | 1.2.2        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.0        |
| bundler                            | 1.16.4       |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.5        |
| nanaimo                            | 0.2.6        |
| colored2                           | 3.1.2        |
| claide                             | 1.0.2        |
| atomos                             | 0.1.3        |
| xcodeproj                          | 1.8.1        |
| unicode-display_width              | 1.5.0        |
| plist                              | 3.5.0        |
| addressable                        | 2.6.0        |
| tty-cursor                         | 0.6.1        |
| tty-spinner                        | 0.9.0        |
| faraday                            | 0.15.4       |
| fastimage                          | 2.1.5        |
| json                               | 2.2.0        |
| dotenv                             | 2.7.1        |
| faraday_middleware                 | 0.13.1       |
| httpclient                         | 2.8.3        |
| jwt                                | 2.1.0        |
| signet                             | 0.11.0       |
| os                                 | 1.0.0        |
| memoist                            | 0.16.0       |
| googleauth                         | 0.6.7        |
| mime-types-data                    | 3.2018.0812  |
| mime-types                         | 3.2.2        |
| retriable                          | 3.1.2        |
| declarative-option                 | 0.1.0        |
| declarative                        | 0.0.10       |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| google-api-client                  | 0.23.9       |
| digest-crc                         | 0.4.1        |
| google-cloud-env                   | 1.0.5        |
| google-cloud-core                  | 1.3.0        |
| google-cloud-storage               | 1.16.0       |
| emoji_regex                        | 1.0.1        |
| openssl                            | 2.1.0        |
| date                               | 1.0.0        |
| fileutils                          | 1.0.2        |
| ipaddr                             | 1.2.0        |
| psych                              | 3.0.2        |
| fastlane-plugin-property_file_read | 1.0.1        |
</details>

*generated on:* **2019-03-13**
</details> </pre>
</details>

### My Gemfile.lock

<details>
<pre>
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.0)
    addressable (2.6.0)
      public_suffix (>= 2.0.2, < 4.0)
    atomos (0.1.3)
    babosa (1.0.2)
    claide (1.0.2)
    colored (1.2)
    colored2 (3.1.2)
    commander-fastlane (4.4.6)
      highline (~> 1.7.2)
    declarative (0.0.10)
    declarative-option (0.1.0)
    digest-crc (0.4.1)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.1)
    emoji_regex (1.0.1)
    excon (0.62.0)
    faraday (0.15.4)
      multipart-post (>= 1.2, < 3)
    faraday-cookie_jar (0.0.6)
      faraday (>= 0.7.4)
      http-cookie (~> 1.0.0)
    faraday_middleware (0.13.1)
      faraday (>= 0.7.4, < 1.0)
    fastimage (2.1.5)
    fastlane (2.117.1)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.3, < 3.0.0)
      babosa (>= 1.0.2, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander-fastlane (>= 4.4.6, < 5.0.0)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 2.0)
      excon (>= 0.45.0, < 1.0.0)
      faraday (~> 0.9)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 0.9)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-api-client (>= 0.21.2, < 0.24.0)
      google-cloud-storage (>= 1.15.0, < 2.0.0)
      highline (>= 1.7.2, < 2.0.0)
      json (< 3.0.0)
      mini_magick (~> 4.5.1)
      multi_json
      multi_xml (~> 0.5)
      multipart-post (~> 2.0.0)
      plist (>= 3.1.0, < 4.0.0)
      public_suffix (~> 2.0.0)
      rubyzip (>= 1.2.2, < 2.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      slack-notifier (>= 2.0.0, < 3.0.0)
      terminal-notifier (>= 1.6.2, < 2.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.6.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    fastlane-plugin-property_file_read (1.0.1)
    gh_inspector (1.1.3)
    google-api-client (0.23.9)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.7.0)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      signet (~> 0.9)
    google-cloud-core (1.3.0)
      google-cloud-env (~> 1.0)
    google-cloud-env (1.0.5)
      faraday (~> 0.11)
    google-cloud-storage (1.16.0)
      digest-crc (~> 0.4)
      google-api-client (~> 0.23)
      google-cloud-core (~> 1.2)
      googleauth (>= 0.6.2, < 0.10.0)
    googleauth (0.6.7)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.7)
    highline (1.7.10)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    json (2.2.0)
    jwt (2.1.0)
    memoist (0.16.0)
    mime-types (3.2.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2018.0812)
    mini_magick (4.5.1)
    multi_json (1.13.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    nanaimo (0.2.6)
    naturally (2.2.0)
    os (1.0.0)
    plist (3.5.0)
    public_suffix (2.0.5)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rouge (2.0.7)
    rubyzip (1.2.2)
    security (0.1.3)
    signet (0.11.0)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.5)
      CFPropertyList
      naturally
    slack-notifier (2.3.2)
    terminal-notifier (1.8.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    tty-cursor (0.6.1)
    tty-screen (0.6.5)
    tty-spinner (0.9.0)
      tty-cursor (~> 0.6.0)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    unicode-display_width (1.5.0)
    word_wrap (1.0.0)
    xcodeproj (1.8.1)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.2.6)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.0)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  fastlane
  fastlane-plugin-property_file_read

BUNDLED WITH
   1.16.4
</pre>
</details>

**Comment by davidfrasch** [comment]
I have the same problem right now, so i tried to upload my apk file manually and it also got stuck. I´m pretty sure its some Problem with the google play console. I guess the best thing we can do is just wait and try it again in a few hours.

**Comment by eduardo-calzado-agentero** [comment]
me too

**Comment by mwajeeh** [comment]
Seems like the issue was with Google's backend. Seems to be fixed now. So closing this issue.
