### ISSUE TITLE
pilot error: Could not set team ID

### ISSUE THREAD

**Issue by KleMiX** [fastlane/fastlane#14395]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I had a simple script to upload builds to TestFlight, it looked like this:
```
export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="some_password"
export DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"

bundle exec fastlane pilot upload -u "my@username.com" -i $1 -q "ABCDE" --dev_portal_team_id "12345" --skip_waiting_for_build_processing true
```

it was working fine. Now when I run it, I get an error:
```
[!] The request could not be completed because:
	Could not set team ID to 'ABCDE', only found the following available teams:

- 12345 (SomeCompany)
- 123456 (SomeOtherCompany)
```
That seems odd, but ok, I changed `ABCDE` in the script to `12345`, still the same error. I went to Appfile and changed `team_id` there to `12345`, no more `ABCDE` in any configs, nor scripts, still the same error. 
It seems it gets this id somewhere from the Apple's servers, and this might be related to recent developer id changes.

##### Command executed
`bundle exec fastlane pilot upload`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> [✔] 🚀 
[13:41:56]: Login to App Store Connect (my@username.com)

Looking for related GitHub issues on fastlane/fastlane...

➡️  Execution fails on fastlane-0.1.14
    https://github.com/fastlane/fastlane/issues/79 [closed] 5 💬
    22 Sep 2016

➡️  Documentation - ipa vs. ipa (shenzhen)?
    https://github.com/fastlane/fastlane/issues/72 [closed] 2 💬
    22 Sep 2016

➡️  Extension Support
    https://github.com/fastlane/fastlane/issues/76 [closed] 6 💬
    11 Dec 2016

and 14336 more at: https://github.com/fastlane/fastlane/search?q=edited✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Could not set team ID to 'ABCDE', only found the following available teams:

- 12345 (SomeCompany)
- 123456 (SomeOtherCompany) </pre>
</details>

### Environment
<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D109)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#ENV['FASTLANE_DISABLE_COLORS'] = 1

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta_sa do
    upload_to_testflight(ipa: ENV["BUILT_IPA_PATH"])
  end

  desc "Download dSYMs from AppStore Connect and upload to Crashlytics"
  lane :refresh_dsyms_sa do
    download_dsyms(version: "latest")   # Download dSYM files from iTC
    upload_symbols_to_crashlytics      # Upload them to Crashlytics
    clean_build_artifacts               # Delete the local dSYM files
  end
  lane :upload_dsyms_sa do
    download_dsyms(version: ENV["DSYM_VERSION"], build_number: ENV["DSYM_BUILD_NUMBER"])   # Download dSYM files from iTC
    upload_symbols_to_crashlytics      # Upload them to Crashlytics
    clean_build_artifacts               # Delete the local dSYM files
  end

  lane :upload_hockey do
    hockey(api_token: ENV["HOCKEY_TOKEN"],
      public_identifier: ENV["HOCKEY_APP_ID"],
      notify: "0",
      ipa: ENV["BUILT_IPA_PATH"],
      dsym: ENV["BUILT_DSYM_PATH"],
      notes: ENV["BUILD_NOTES"],
      notes_type: "0",
      bypass_cdn: false)
  end
end

platform :android do
  lane :upload_hockey do
    hockey(api_token: ENV["HOCKEY_TOKEN"],
      public_identifier: ENV["HOCKEY_APP_ID"],
      notify: "0",
      apk: ENV["BUILT_IPA_PATH"],
      notes: ENV["BUILD_NOTES"],
      notes_type: "0",
      bypass_cdn: false)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxxx") # The bundle identifier of your app
apple_id("my@username.com") # Your Apple email address

itc_team_id("12345") # App Store Connect Team ID
team_id("12345") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.17.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.3        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11       |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.3.1        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.1        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-03-14**
</details> </pre>
</details>

**Comment by joshdholtz** [comment]
@KleMiX Heyyyy! This is totally related to recent developer changes. The team ids that were used for developer portal are no more and the ones that were originally on App Store Connect (iTunesConnect) are now also used in the developer portal. I would try either using "12345" for both or use `-team_name "SomeCompany"` 

I personally use the team name 😊

**Comment by KleMiX** [comment]
Hi @joshdholtz, thanks for the info! Though adding `-team_name` gave me an error:
```
OptionParser::AmbiguousOption: ambiguous option: -team_name
``` 
But I tried to remove `-q` parameter at all, and it worked! So it is enough to pass `dev_portal_team_id` for uploading a build.
