### ISSUE TITLE
Watch build in separate lane without .ipa

### ISSUE THREAD

**Issue by OdNairy** [fastlane/fastlane#14406]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
FastlaneCore
Spaceship

#### Question Description
Hi there.  
Currently I have the main lane which builds my app and upload it to TestFlight. However, I can not make it wait till process since number of CI runners is limited. That's why I got an idea to create separate lane which would be runned on separate CI Runner. This lane (lets name it `wait_and_upload_changelog`) would take app version, build number and changelog data from special configured json which would be passed by CI runners functionality. Lane would take app version and build number from file and wait till the processing completion. Afterwards, it should update changelog for concrete build.

This behaviour would make me keep changelogs for all build correct and reduce job time duration on build runners (which a limited).

The problem is the API. I cannot find correct FastlaneCore API I should call. The [build_watcher.rb](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/build_watcher.rb) looks the most promising. However, `Spaceship::TestFlight::Build.all_processing_builds` call failed with `undefined method 'client' for Spaceship::Tunes:Module` error. In `bundle exec fastlane spaceship` mode it fails with `Faraday::ParsingError: 785: unexpected token at '<!DOCTYPE html><html lang="en">`

What is the most efficient way to implemented requested behaviour? 

Notes:
It was decided to use `.json` instead of `ipa` (which is support OOB) cause full `ipa` has 400 MB size.  
`watchbuild` works closely I want. However, it could not wait concrete build version and waiting for the latest instead.

**Comment by OdNairy** [comment]
P.S. Possible, it would be useful addition to `pilot`? Some API to update post processed build data (as `changelog`) with a single call for a concrete build.

**Comment by johnknapprs** [comment]
Would this help you?

https://github.com/fastlane/watchbuild

**Comment by OdNairy** [comment]
> watchbuild works closely I want. However, it could not wait concrete build version and waiting for the latest instead.

**Comment by OdNairy** [comment]
I have created my own action for this purpose. Here the link if somebody interested in the same solution: https://gist.github.com/OdNairy/13dc5132ae3a59dde372114224645484
