### ISSUE TITLE
Any iTunes Connect application status checker?

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#1441]
Hi,
I would like to know if there is any `iTunes Connect ` application status checker/sampler?
I would like to know if the application is `ready for sale` or any rejection came up from Apple by sample my app status.

I checked already some `fastlane` tools like `deliver`, `produce`  and `watchbuild` (not really `fastlane` tool but was worth to try), and didn't find any solution.

Does `fastlane` provide any solution to this case?

My "super" fallback will be to analyse the email getting from Apple about the application status. But it's not cool, and `fastlane` is cool, so let's be cool :)

Thanks in advance.

**Comment by lacostej** [comment]
Hello @gran33 , this PR: https://github.com/fastlane/spaceship/pull/255 should allow you to implement it easily. See the attached code example. Maybe @asfalcone can have a look ? :)

**Comment by ohwutup** [comment]
Hi all, going to close this issue as it has been quite for some time. :crickets:
