### ISSUE TITLE
[Swift] PEM Unresolved conflict between options: 'website_push' and 'development'

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#14427]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I run fastlane swift command `get_push_certificate` I now get the error: 

> You passed invalid parameters to 'get_push_certificate'.
> Check out the error below and available options by running `fastlane action get_push_certificate`
> **Unresolved conflict between options: 'website_push' and 'development'**

I have development set to true and website_publish is as default false. This error has not been there for that long, as I have been getting this error the past few months: https://github.com/fastlane/fastlane/issues/14019 (now it seems I do not get that far)

##### Command executed
`fastlane setupForDevelopment`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> [13:52:23]: ----------------------------------
[13:52:23]: --- Step: get_push_certificate ---
[13:52:23]: ----------------------------------
[13:52:23]: You passed invalid parameters to 'get_push_certificate'.
[13:52:23]: Check out the error below and available options by running `fastlane action get_push_certificate`
+------------------------------------+--------------------------------------+
|                               Lane Context                                |
+------------------------------------+--------------------------------------+
| LANE_NAME                          | setupForDevelopment                  |
| VERSION_NUMBER                     | 1.0                                  |
| PRODUCE_APPLE_ID                   |                                      |
| SIGH_PROFILE_TYPE                  | development                          |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"dk.molslinjen.kombardo.dev"=>"mat  |
|                                    | ch Development                       |
|                                    | dk.molslinjen.kombardo.dev"}         |
+------------------------------------+--------------------------------------+
[13:52:23]: Unresolved conflict between options: 'website_push' and 'development'
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1                          |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | da_DK.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    let appleUsername = "xxx"
    let teamName = "xxx"

    func firstRunOnNewMachineLane() {
        desc("Setup on new machine")
        
        let keystorePassword = FastlaneHelper.getAnswerText(question: "We need your keystore password this once to avoid asking for it all the time. Type in keystore password (same as mac account password usually)", secure: true)
        say(text: environmentVariable(set: ["KeystorePassword": keystorePassword]))
        say(text: "Keystore password: \(environmentVariable(get: "KeystorePassword"))")
        
        say(text: "Initial setup done - start using the other lanes")
    }

    func setupForDevelopmentLane() {
        desc("Setup Dev, Test and ProdTest")
        
        say(text: "Keystore password: \(environmentVariable(get: "KeystorePassword"))") //ONLY for test
        
        let forceCreateNewPushCertificate = FastlaneHelper.getAnswer(question: "Create a new push certificate even if it is not expired?")
        ensureAppCreated(configuration: .Dev)
        updateSigning(configuration: .Dev)
        ensurePush(configuration: .Dev, forceCreateNewPushCertificate: forceCreateNewPushCertificate)

        ensureAppCreated(configuration: .Test)
        updateSigning(configuration: .Test)
        ensurePush(configuration: .Test, forceCreateNewPushCertificate: forceCreateNewPushCertificate)

        ensureAppCreated(configuration: .ProdTest)
        updateSigning(configuration: .ProdTest)
        ensurePush(configuration: .ProdTest, forceCreateNewPushCertificate: forceCreateNewPushCertificate)
    }

    func setupForReleaseLane() {
        desc("Setup Prod")

        let forceCreateNewPushCertificate = FastlaneHelper.getAnswer(question: "Create a new push certificate even if it is not expired?")
        ensureAppCreated(configuration: .Prod)
        updateSigning(configuration: .Prod)
        ensurePush(configuration: .Prod, forceCreateNewPushCertificate: forceCreateNewPushCertificate)
    }

    func deployToTestLane(withOptions options: [String: String]?) {
        desc("Distribute test version")

        if let ignoreGitClean = options?["ignoreGitClean"], ignoreGitClean == "true" { // ignore git clean: fastlane deploytotest ignoreGitClean:true
            //no action
        } else {
            ensureGitStatusClean()
        }

        updateSigning(configuration: .Test)
        updateSigning(configuration: .ProdTest)

        FastlaneHelper.updateVersionNumber(alwaysIncrementBuildNumber: true)

        var testNotes = FastlaneHelper.getAnswerText(question: "Write a message to the testers here: (End with enter)")
        let emails = KombardoHelper.getCrashlyticsEmails()

        for i in 0...1 {
            if i == 0 {
                testNotes = "Test data. \(testNotes)"
            } else {
                testNotes = "Prod data. \(testNotes)"
            }

            buildApp(scheme: "xxx",
                     clean: true,
                     configuration: i == 0 ? "Test" : "ProdTest",
                     silent: true)
            
            crashlytics(
                    crashlyticsPath: "./Crashlytics.framework",
                    apiToken: "xxx",
                    buildSecret: "xxx",
                    notes: testNotes,
                    emails: emails,
                    notifications: i == 0
            )
        }
    }

    func deployToAppstoreLane(withOptions options: [String: String]?) {
        desc("Deploy to Appstore")

        if let ignoreGitClean = options?["ignoreGitClean"], ignoreGitClean == "true" { // ignore git clean: fastlane deploytotest ignoreGitClean:true
            //no action
        } else {
            ensureGitStatusClean()
        }

        let forceCreateNewPushCertificate = FastlaneHelper.getAnswer(question: "Create a new push certificate even if it is not expired?")
        ensureAppCreated(configuration: .Prod)
        updateSigning(configuration: .Prod)
        ensurePush(configuration: .Prod, forceCreateNewPushCertificate: forceCreateNewPushCertificate)
        FastlaneHelper.updateVersionNumber()

        let shouldSubmitForReview = FastlaneHelper.getAnswer(question: "Submit for review?")
        let whatsIsNewText = FastlaneHelper.getAnswerText(question: "New in this version - text to Appstore. (End with enter)")

        uploadToAppStore(
                username: appleUsername,
                skipScreenshots: true,
                skipMetadata: true,
                submitForReview: shouldSubmitForReview,
                submissionInformation: """
                                       { add_id_info_limits_tracking: false,
                                       add_id_info_serves_ads: false,
                                       add_id_info_tracks_action: false,
                                       add_id_info_tracks_install: false,
                                       add_id_info_uses_idfa: false,
                                       content_rights_contains_third_party_content: false,
                                       content_rights_has_rights: false,
                                       export_compliance_is_exempt: false,
                                       export_compliance_uses_encryption: false,
                                       export_compliance_encryption_updated: false }
                                       """,
                teamName: teamName,
                releaseNotes: whatsIsNewText,
                app: environmentVariable(get: "PRODUCE_APPLE_ID"))
    }

    func addTestDeviceLane() {
        desc("Add test device")

        let deviceId = FastlaneHelper.getAnswerText(question: "Device id?")
        let deviceTitle = FastlaneHelper.getAnswerText(question: "Device title? (Name - Device type - Company)")
        registerDevice(name: deviceTitle,
                       udid: deviceId,
                       teamName: teamName,
                       username: appleUsername)
        
        updateSigning(configuration: .Dev)
        updateSigning(configuration: .Test)
        updateSigning(configuration: .ProdTest)
    }

    private func updateSigning(configuration: Configuration) {
        say(text: "Keystore password: \(environmentVariable(get: "KeystorePassword"))")
        match(type: configuration == .Prod ? "appstore" : "development",
              readonly: false,
              appIdentifier: [configuration.appIdentifier()],
              keychainPassword: environmentVariable(get: "KeystorePassword")) // require that lane firstRunOnNewMachine has been run
    }

    private func ensurePush(configuration: Configuration, forceCreateNewPushCertificate: Bool) {
        getPushCertificate(development: configuration != .Prod,
                generateP12: true,
                force: forceCreateNewPushCertificate,
                savePrivateKey: true,
                appIdentifier: configuration.appIdentifier(),
                username: appleUsername,
                teamName: teamName,
                p12Password: "")
        // pem(development: configuration != .prod, websitePush: false, generateP12: true, activeDaysLimit: 30, force: forceCreateNewPushCertificate, savePrivateKey: true, appIdentifier: configuration.appIdentifier(), username: appleUsername, teamId: nil, teamName: teamName, p12Password: "", pemName: nil, outputPath: "./fastlane/certificates/", newProfile: nil) // also tested with this - same error
    }

    private func ensureAppCreated(configuration: Configuration) {
        createAppOnline(
                username: appleUsername,
                appIdentifier: configuration.appIdentifier(),
                appName: "xxx",
                appVersion: getVersionNumber(),
                sku: configuration.appIdentifier(),
                language: "Danish",
                skipItc: configuration != .Prod,
                skipDevcenter: false,
                teamName: teamName)
    }
}

enum Configuration {
    case Dev, Test, ProdTest, Prod

    func appIdentifier() -> String {
        let identifier = "xxx"
        switch self {
        case .Dev:
            return "\(identifier).dev"
        case .Test:
            return "\(identifier).test"
        case .ProdTest:
            return "\(identifier).prodtest"
        default:
            return identifier
        }
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.118.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.17.3       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.1        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |

</details>

**Comment by janpio** [comment]
`website_push` is new in 2.118.0: https://github.com/fastlane/fastlane/pull/10597

The relevant bit of the PR is probably https://github.com/fastlane/fastlane/pull/10597/files#diff-b9692338f09dc2dd256f9606e99f24cfR18 (and the following lines)

But I don't know anything about the Swift part of Fastlane, so no idea how this could be causing this error message. Doesn't it support conflicting options?

**Comment by mortenholmgaard** [comment]
@janpio I don't know much about the swift implementation, but it seems like just a wrapper on top of the ruby code, so the code difference seems very small. 

I don't know anything about conflicting options as I have never hit that before - but as I see the code the problem seems to be that `development `and `websitePush `is mapped as `Bool `and not nullable types. 
So it is not possible from swift not to specify both of them. The solution as I expected it would be that `websitePush = false` was the same as `not specified / null`, but there I don't know about the ruby site of the implementation.

Swift interface:
```
func getPushCertificate(development: Bool = false,
                        websitePush: Bool = false,
                        generateP12: Bool = true,
                        activeDaysLimit: Int = 30,
                        force: Bool = false,
                        savePrivateKey: Bool = true,
                        appIdentifier: String,
                        username: String,
                        teamId: String? = nil,
                        teamName: String? = nil,
                        p12Password: String,
                        pemName: String? = nil,
                        outputPath: String = ".",
                        newProfile: String? = nil)
```

**Comment by janpio** [comment]
So on the Swift side you _have_ to supply both `development` and `websitePush`?

**Comment by mortenholmgaard** [comment]
Yes, either true or false to each of them.

**Comment by janpio** [comment]
Interesting. So `conflicting` with booleans is no good for Swift. No idea how to fix that - in Ruby most of the options/parameters are optional.

Could the param `websitePush` default to `nil`/null/undefined in Swift theoretically?

**Comment by mortenholmgaard** [comment]
Yes that could just be made a nullable Bool - like this: `websitePush: Bool? = nil`
But both development and website push should then be made nullable as else you would get this error the other way around when wanting websitePush.

**Comment by janpio** [comment]
Can you think of a reason why one would _not_ want to have a "nullable Bool" for an option?

**Comment by mortenholmgaard** [comment]
Generally I would never want a nullable Bool as the nullable state should generally be the same as false. And also required arguments should never be nullable for documentation. 
But in this case I think it makes sense. 
But is the swift api auto generated? When I look around e.g. buildApp has both nullable and not nullable Bool, so there seems to be a natural distinction.

**Comment by janpio** [comment]
As far as I know the Swift API is generated, yes. 

Could you maybe look into differences between the (ruby) pem options and the (ruby) gym (buildApp) options and see what exactly makes it to generate the correct or wrong Swift definition?

**Comment by mortenholmgaard** [comment]
I found the problem :) (even though I have a hard time navigating ruby code)

The `optional: true` argument is missing in the ruby definition for both development and website_push. I would actually expect that to be a problem for the ruby code as well if it is validated. You can compare the code to the swift code in Fastfile.swift.

https://github.com/fastlane/fastlane/blob/04ef48fad041eb6c62e8015264df781d3bfc9983/gym/lib/gym/options.rb
```
FastlaneCore::ConfigItem.new(key: :skip_package_ipa,
                                     env_name: "GYM_SKIP_PACKAGE_IPA",
                                     description: "Should we skip packaging the ipa?",
                                     is_string: false,
                                     default_value: false),
        FastlaneCore::ConfigItem.new(key: :include_symbols,
                                     short_option: "-m",
                                     env_name: "GYM_INCLUDE_SYMBOLS",
                                     description: "Should the ipa file include symbols?",
                                     is_string: false,
                                     type: Boolean,
                                     optional: true),
```

https://github.com/fastlane/fastlane/blob/04ef48fad041eb6c62e8015264df781d3bfc9983/pem/lib/pem/options.rb
```
        FastlaneCore::ConfigItem.new(key: :development,
                                     env_name: "PEM_DEVELOPMENT",
                                     description: "Renew the development push certificate instead of the production one",
                                     is_string: false,
                                     default_value: false),
        FastlaneCore::ConfigItem.new(key: :website_push,
                                     env_name: "PEM_WEBSITE_PUSH",
                                     description: "Create a Website Push certificate",
                                     is_string: false,
                                     conflicting_options: [:development],
                                     default_value: false),
```

**Comment by janpio** [comment]
I am not sure this is the solution, I thought the default was `optional: true` (@joshdholtz?)

But the `type: Boolean` looks interesting, maybe this is handled differently when you explicitly specify the type instead of using `is_string: false`. I think Josh also has a PR open to replace is_string with type: Boolean and create  rubocop rule - maybe because of that exact reason.

**Comment by mortenholmgaard** [comment]
It could be that as well - you know more about that than me.
- I just stopped looking when I saw the optional property :)
