### ISSUE TITLE
[pod_push] push to private specs repository in any operating system (e.g. Linux)

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14422]
#### Motivation Behind Feature
Deploying a new CocoPod consist of 3 steps:
1. Commit new sources
2. Update & commit `.podspec` file
3. Push `.podspec` to the Private / Master CocoPods repository.

Steps 1 and 2 are possible to run in any environment (macOS, Linux, Windows). However, step 3 is available only on macOS as it triggers the CocoaPods command:

`pod repo push RepoName SpecName.podspec`

... which does validations before pushing spec to a repository.

**Having a Fastlane action to deploy a `.podspec` to a repository would allow deploying a new CocoaPod version in any hosted environment (i.e. on Linux).**

#### Feature Description

1. Create a Fastlane command for pushing a CocoaPod that works on any OS, the syntax could be as follows:
```Ruby
    pod_push_crossplatform(path: "name.podspec",
      repo: "MyPrivateSpecs",
      sources: ["my-pospec-source"])
```

2. Alternatively, use a parameter for `pod_push` command that would fall back to the built-in script for pushing a Pod if CocoaPods is not available:

```Ruby
    pod_push(path: "name.podspec",
      use_builtin_script: true, # Uses built-in script to deploy a pod instead of the one provisioned with CocoaPods
      repo: "MyPrivateSpecs",
      allow_warnings: true,
      verbose: false,
      use_libraries: true,
      sources: ["some-private-spec.git"])
```

#### Alternatives or Workarounds

The only alternative/workaround now is to use `pod_push` command which triggers built-in CocoaPods script:

```Ruby
    pod_push(path: "name.podspec",
      repo: "MyPrivateSpecs",
      allow_warnings: true,
      verbose: false,
      use_libraries: true,
      sources: ["some-private-spec.git"])
```

This works only on macOS, there are no workarounds for Linux / Windows, except to write a similar script (or a Fastlane plugin).

**Comment by janpio** [comment]
> command that would fall back to the built-in script for pushing a Pod if CocoaPods is not available

Does this "built-in script" already exist?

**Comment by richardtop** [comment]
@janpio no, that script doesn't exist and it is the point of this task.

**Comment by richardtop** [comment]
@fastlane-bot hi

**Comment by richardtop** [comment]
@fastlane-bot issue still persists.

**Comment by richardtop** [comment]
@fastlane-bot doesn’t work 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
@fastlane-bot  doesn't work.

**Comment by janpio** [comment]
I looked into the `pod_push` action and this indeed is just a light wrapper around some `pod` commands: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/pod_push.rb 

I don't think making these work on non-macOS will ever be a focus of fastlane, so I would probably say this is better solved with a plugin (which I will make clear with a label in a minute).

Even better of course would be if Cocoapods itself could support that on all platforms, then the plugin will not even be necessary at all.

**Comment by richardtop** [comment]
Hi, I agree. Neither I see it as the focus of CocoaPods, since it's a macOS / iOS specific tool, so the plugin works best here.

**Comment by richardtop** [comment]
@fastlane-bot hi

**Comment by richardtop** [comment]
@fastlane-bot

**Comment by richardtop** [comment]
@fastlane-bot 123

**Comment by richardtop** [comment]
Doesn’t work 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
@fastlane-bot
