### ISSUE TITLE
Fastlane Deliver submitted wrong build for review

### ISSUE THREAD

**Issue by balrajo** [fastlane/fastlane#14428]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Apple had rejected our app version 1.23 build 1, so we recompiled our code to fix issue report by Apple and used FASTLANE DELIVER to upload and submit version 1.23 build 2. Fastlane Deliver started the upload for version 1.23 build 2. While the build was in processing, DELIVER submitted the version 1.23 build 1 for review.  

##### Command executed
fastlane deliver  --force true --app_identifier <> --ipa "" --submit_for_review true --skip_binary_upload false --verbose

##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2019-03-15 14:45:27.04]: [32miTunes Transporter successfully finished its job[0m
DEBUG [2019-03-15 14:45:27.04]: [Transporter]: DBG-X: Returning 0
INFO [2019-03-15 14:45:27.17]: [32m-----------------------------------------------------[0m
INFO [2019-03-15 14:45:27.17]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
INFO [2019-03-15 14:45:27.17]: [32m-----------------------------------------------------[0m
INFO [2019-03-15 14:45:27.18]: [32mFinished the upload to App Store Connect[0m
INFO [2019-03-15 14:45:27.18]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
INFO [2019-03-15 14:45:27.18]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫
 
+--------------------------+------------------------------+
|              [32mSummary for precheck 2.117.1[0m               |
+--------------------------+------------------------------+
| default_rule_level       | warn                         |
| include_in_app_purchases | true                         |
| app_identifier           |          |
| username                 |  |
+--------------------------+------------------------------+
 
INFO [2019-03-15 14:45:27.18]: Checking app for precheck rule violations
INFO [2019-03-15 14:45:37.62]: Reading in-app purchases. If you have a lot, this might take a while
INFO [2019-03-15 14:45:37.62]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
INFO [2019-03-15 14:45:38.58]: Done reading in-app purchases
INFO [2019-03-15 14:45:39.43]: ✅  Passed: No negative  sentiment
INFO [2019-03-15 14:45:39.43]: ✅  Passed: No placeholder text
INFO [2019-03-15 14:45:39.44]: ✅  Passed: No mentioning  competitors
INFO [2019-03-15 14:45:39.44]: ✅  Passed: No future functionality promises
INFO [2019-03-15 14:45:39.44]: ✅  Passed: No words indicating test content
INFO [2019-03-15 14:45:39.44]: ✅  Passed: No curse words
INFO [2019-03-15 14:45:39.44]: ✅  Passed: No words indicating your IAP is free
DEBUG [2019-03-15 14:45:39.44]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
DEBUG [2019-03-15 14:45:39.44]: 😭  CopyrightDateRule didn't find words "2019"
WARN [2019-03-15 14:45:39.44]: [33m😵  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date[0m
WARN [2019-03-15 14:45:40.40]: [33m😵  Failed: No broken urls-> unreachable URLs in app metadata[0m
+------------------------+-------------------------------------+
|                      [33mPotential problems[0m                      |
+------------------------+-------------------------------------+
| Field                  | Failure reason                      |
+------------------------+-------------------------------------+
| copyright              | [33mmissing: 2019[0m                       |
| support URL: (en-US)   | [33m[0m |
| marketing URL: (en-US) | [33m[0m |
+------------------------+-------------------------------------+
WARN [2019-03-15 14:45:40.40]: [33m[33mprecheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍[0m
INFO [2019-03-15 14:45:42.93]: Selecting the latest build...
INFO [2019-03-15 14:45:46.97]: Selecting build 1.23 (1)...
INFO [2019-03-15 14:45:49.26]: [32mSuccessfully selected build[0m
INFO [2019-03-15 14:45:49.26]: Submitting the app for review...
INFO [2019-03-15 14:45:56.80]: Setting 'add_id_info_uses_idfa' to 'false'...
INFO [2019-03-15 14:45:56.80]: Setting 'content_rights_has_rights' to 'false'...
INFO [2019-03-15 14:45:56.80]: Setting 'export_compliance_uses_encryption' to 'false'...
INFO [2019-03-15 14:45:56.80]: Setting 'export_compliance_encryption_updated' to 'false
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.2                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.2 (18C54)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | ~/xcode10_1/Xcode.app/Contents/Developer/                      |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.118.1 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.4       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| signet                    | 0.9.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.6       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

**Comment by janpio** [comment]
Please post the complete output of the command so we can understand what it was doing before and after the bits you currently included in your issue. Thanks.

**Comment by joshdholtz** [comment]
@balrajo Were you able to get this resolved on your end?

**Comment by balrajo** [comment]
Nope!!!

**Comment by joshdholtz** [comment]
@balrajo Can you run your command again with `--verbose` on the end and paste the whole output here so we can take a closer look to help you out? 😊
