### ISSUE TITLE
Search query: undefined method `strip' for <teamid>:Fixnum

### ISSUE THREAD

**Issue by hanumanAbacus** [fastlane/fastlane#14433]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Search query: undefined method `strip' for <teamId>:Fixnum
 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
  | NoMethodError: [!] undefined method `strip' for <teamId>:Fixnum
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/spaceship/lib/spaceship/tunes/tunes_client.rb:65:in `select_team'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/spaceship/lib/spaceship/tunes/spaceship.rb:35:in `select_team'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/pilot/lib/pilot/manager.rb:24:in `login'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/pilot/lib/pilot/manager.rb:16:in `start'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/pilot/lib/pilot/build_manager.rb:13:in `upload'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  | ../../../../../../../../../../var/folders/vh/f2k2h7gx75x2x1rpt4fcy1180000gn/T/fl_clone20190319-32470-28lopc/fastlanesetting.git/Fastfile:443:in `block (2 levels) in parsing_binding'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  | ../../../../../../../../../../var/folders/vh/f2k2h7gx75x2x1rpt4fcy1180000gn/T/fl_clone20190319-32470-28lopc/fastlanesetting.git/Fastfile:406:in `block (2 levels) in parsing_binding'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  | ../../../../../../../../../../var/folders/vh/f2k2h7gx75x2x1rpt4fcy1180000gn/T/fl_clone20190319-32470-28lopc/fastlanesetting.git/Fastfile:281:in `block (2 levels) in parsing_binding'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  | /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  | /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  | /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  | /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  | /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/bin/fastlane:23:in `<top (required)>'
  | /usr/local/bin/fastlane:22:in `load'
  | /usr/local/bin/fastlane:22:in `<top (required)>']</pre>
</details>

### Environment

<details>
  <pre>[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14                                                          |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14 (18A391)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.118.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.4       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| tty-spinner               | 0.9.0        |
| tty-cursor                | 0.6.1        |
| faraday                   | 0.15.4       |
| json                      | 2.2.0        |
| io-console                | 0.4.6        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| signet                    | 0.11.0       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| unicode-display_width     | 1.5.0        |
| addressable               | 2.6.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-03-19**
</details>]</pre>
</details>

**Comment by hanumanAbacus** [comment]
`    gym(workspace: WORK_SPACE_NAME,
           scheme: using_scheme,
    configuration: build_configuration,
           xcargs: "-allowProvisioningUpdates",
            clean: true) # Build your app - more options available
    testflight(changelog: change_log,
         skip_submission: true,
     distribute_external: false,
                 team_id: 117267629)
`

**Comment by hanumanAbacus** [comment]
`gym(workspace: WORK_SPACE_NAME, scheme: using_scheme, configuration: build_configuration, xcargs: "-allowProvisioningUpdates", clean: true) # Build your app - more options available testflight(changelog: change_log, skip_submission: true, distribute_external: false, team_id: 1234)`

**Comment by janpio** [comment]
Please fill the issue template - what command did you execute? What was the _complete_ output you were getting? What does your second comment have to do with all this?

**Comment by hanumanAbacus** [comment]
@janpio  the second comment is the command I executed

**Comment by hanumanAbacus** [comment]
@janpio The issue is fixed, when using Fastlane without `bundle exec`, it was working for `testflight` command when `team_id` was passed as integer, but it requires as string "" in bundle exec
