### ISSUE TITLE
git_commit - continue execution if there is nothing to commit

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14437]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

**git_commit** action

#### Question Description

I use the [git_commit action][1]:

> git_commit(path: "*", message: "message")

This action fails if there is nothing to commit. How can I continue executing my Fastlane script even if there is nothing to commit?

What I'm looking for could be accomplished with the any of the two options:

1. Add some parameter to the `git_commit` action so it would not crash the script if there is nothing to commit (but rather, continue)
2. Check if there are any changes and only then invoke `git_commit`.

I didn't find any way to get this done using method 1, so **I'm looking for an implementation with the second approach.**

Also, is it possible to add any flag to continue execution, or use a similar action:

```Bash
git_commit_if_needed.....
```

  [1]: https://docs.fastlane.tools/actions/git_commit/

**Comment by janpio** [comment]
How does it "fail" or "crash the script"? Please post the output you are currently getting. Thanks.

**Comment by mollyIV** [comment]
👋 @richardtop @janpio  

I did a quick test:

<img width="589" alt="Screenshot 2019-03-21 at 08 54 03" src="https://user-images.githubusercontent.com/10795657/54739052-f058e700-4bb6-11e9-831f-00a09754afaa.png">

I think adding new parameter to `git_commit` action like `skip_when_nothing_to_commit` can be helpful. 

Please tell me what you think about the name of suggested param and of course share your ideas 🙇 

If we agree on the solution, I will be happy to implement it 🤚

**Comment by richardtop** [comment]
Hi @mollyIV, your proposed solution looks great. Thanks a lot!

**Comment by janpio** [comment]
Agree with @richardtop. Might be worth going through other existing actions though if there are similar options in other actions so we can use consistent naming. (I am not aware of any, but I also don't really know many action params)

**Comment by mollyIV** [comment]
Here we go guys https://github.com/fastlane/fastlane/pull/14501 🎁
