### ISSUE TITLE
fastlane crashlytics group doesn't work with spaces

### ISSUE THREAD

**Issue by sudeepkzd** [fastlane/fastlane#14446]
I'm using fastlane to release app to crashlytics. 

```
lane :dogfooders_release do |options|
	get_certificates(username:"someone@gmail.com")
	get_provisioning_profile(username:"someone@gmail.com", app_identifier: 'com.zendrive.ZDDogfood')
	build_app(scheme: "ZDDogfood",
	        workspace: "ZendriveUnifiedDemo.xcworkspace",
			configuration: "Release",
	        include_bitcode: false)
	crashlytics(api_token: "something",
	          build_secret: "also_something",
			  groups: "iOS Dogfood", notifications: "true")
end
```

However when upload to crashlytics, it's trying to push it to "Dogfood" group rather than "iOS Dogfood". How do I get it to use the complete group name?

**Comment by janpio** [comment]
Maybe this is relevant here:

> Distributing to Groups: When using the groups parameter, it's important to use the group alias names for each group you'd like to distribute to. A group's alias can be found in the web UI. If you're viewing the Beta page, you can open the groups dialog by clicking the 'Manage Groups' button

From https://docs.fastlane.tools/actions/crashlytics/
