### ISSUE TITLE
Gym fails to find embedded workspace schemes in select_scheme even with "shared schemes" enabled

### ISSUE THREAD

**Issue by LizCira** [fastlane/fastlane#14447]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi, this is definitely an edge case but of course I have a couple legacy projects our CI setup needs to support, and they are embedded workspaces. 

More info about Xcode embedded workspaces here: 
https://developer.nevercode.io/docs/sharing-ios-project-schemes

And this isn't the first time it's caused unusual behavior: 
https://github.com/CocoaPods/Xcodeproj/issues/605

I did local debugging and the problem is in how @schemes is processed and assigned here: 
https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/project.rb#L118

The embedded workspace project structure can't see the schemes, even if they're shared, so it takes the project name instead. 

Resulting in failure and error text like this: 

```
[11:13:35]: -----------------
[11:13:35]: --- Step: gym ---
[11:13:35]: -----------------
[11:13:35]: Couldn't find specified scheme 'MyProject_iPad'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3
[11:13:35]: $ xcodebuild -showBuildSettings -workspace /Users/me/build/workspace/iOS/xcode/MyProject.xcodeproj/project.xcworkspace -scheme MyProject -configuration Release
xcodebuild: error: The workspace named "MyProject" does not contain a scheme named "MyProject". The "-list" option can be used to find the names of the schemes in the workspace.
[11:13:36]: Could not read build settings. Make sure that the scheme "MyProject" is configured for running by going to Product → Scheme → Edit Scheme…, selecting the "Build" section, checking the "Run" checkbox and closing the scheme window.

```
So you see, the "Couldn't find specified schemes" error uses options[:scheme] but the actual logic is using @schemes and they're not the same thing anymore. Xcodeproj is used to parse the workspace hash (https://github.com/CocoaPods/Xcodeproj/blob/7cebf2b73492fae7ec7a3ae280af7f1ab7c471b9/lib/xcodeproj/workspace.rb)

It seems using xcodeproj and @schemes is an attempt to validate the scheme parameter assigned by a user, but is that really necessary? Would it be possible to instead have gym fail after attempting to use the assigned parameter, instead of the parsed variable? Perhaps remove xcodeproj entirely from this piece of the process? I admit, I'm not sure what else may depend on this. 

I've changed the code locally at projects.rb line 131 and it works for my projects, but of course this isn't ideal. 

```
      if options[:scheme].to_s.length > 0
        # Verify the scheme is available
        schemes = options[:scheme] <-- MY CHANGE
        unless schemes.include?(options[:scheme].to_s)
          UI.error("Couldn't find specified scheme '#{options[:scheme]}'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3")
          options[:scheme] = nil
        end
      end

```
If you're not opposed to removing how @schemes is assigned via xcodeproj, I'd be happy to open a PR. Thank you for your time! 

##### Command executed

Here's the gym configuration (we use a shared Fastfile for dozens of projects)

```
      gym(
        scheme: scheme,
        configuration: configuration,
        clean: true,
        include_bitcode: bitcode,
        workspace: ENV["APP_WORKSPACE"],
        output_directory: "#{ENV['FASTLANE_DIRECTORY']}/output",
        buildlog_path: "#{ENV['FASTLANE_DIRECTORY']}/logs/",
        output_name: ipa_name,
        codesigning_identity: identity,
        export_method: export_method,
            export_options: {
              provisioningProfiles: {
                "#{ENV["APP_BUNDLEID"]}" => "#{profile_name}",
              }
            },
        derived_data_path: "#{ENV['FASTLANE_DIRECTORY']}/DerivedData/",
        xcargs: ENV["XCARGS"]
      )

```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[11:13:35]: --- Step: gym ---
[11:13:35]: -----------------
[11:13:35]: Couldn't find specified scheme 'MyProject_iPad'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3
[11:13:35]: $ xcodebuild -showBuildSettings -workspace /Users/me/build/workspace/iOS/xcode/MyProject.xcodeproj/project.xcworkspace -scheme MyProject -configuration Release
xcodebuild: error: The workspace named "MyProject" does not contain a scheme named "MyProject". The "-list" option can be used to find the names of the schemes in the workspace.
[11:13:36]: Could not read build settings. Make sure that the scheme "MyProject" is configured for running by going to Product → Scheme → Edit Scheme…, selecting the "Build" section, checking the "Run" checkbox and closing the scheme window.
 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.6                                      |
| Ruby                        | 2.1.2                                        |
| Bundler?                    | true                                         |
| Git                         | git version 2.13.6 (Apple Git-96)            |
| Installation Source         | ~/.rvm/gems/ruby-2.1.2/bin/fastlane          |
| Host                        | Mac OS X 10.12.6 (16G1815)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.1.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.1g 7 Apr 2014                    |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode9.app/Contents/Developer/ |
| Xcode Version               | 9.1                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.118.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-teams | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.1        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-teams     | 0.2.0        |
</details>

*generated on:* **2019-03-21**
</details></pre>
</details>

**Comment by Gi0rgi0s** [comment]
I am seeing this issue as well

**Comment by ale-fante** [comment]
I ran into this issue too.

**Comment by jkschuetz** [comment]
HI Liz we are seeing the same issue in one of our projects.

I made the same change and it has resolved the issue and hasn't caused other issues for our unaffected projects. 

Please open a PR :)

**Comment by gaurav17281** [comment]
Same here. We're seeing this issue with one of our projects and the fix shared here resolves the issue. Summary - 
- There're two schemes, pointing to different targets, in my project. Fastlane is not able to pick one of the schemes.

**Comment by RahathCherukuri** [comment]
Facing the same issue

**Comment by xmucyp** [comment]
I ran into this issue too

**Comment by owurman** [comment]
I'm also hitting this with fastlane 2.126.0. It's a regression. Your change above, applied to project.rb, worked. I can pass the scheme just fine into snapshot, but not gym.

**Comment by tomspee** [comment]
I have the same issues but what do you mean with:
> changed the code locally at projects.rb line 131

Where can I find this file? @LizCira

**Comment by LizCira** [comment]
@tomspee if you type "gem env" in your terminal, you should see a path for "INSTALLATION DIRECTORY"--this is where all of your gems are installed (for example, mine is /Users/liz/.rvm/gems/ruby-2.1.2/gems but I use rvm, so yours could be different.)  

In the gems directory, you should see your local copies of the fastlane gem. In whichever version you are currently using, edit the file fastlane/fastlane_core/lib/fastlane_core/project.rb

I did try forking the repo to make this change and open a PR, but it led to over 100 failing tests, and I don't currently have the capacity to spend more time on it, unfortunately.

**Comment by tomspee** [comment]
Thanks @LizCira that works perfect.
