### ISSUE TITLE
verify_block not invoked when using environment variables

### ISSUE THREAD

**Issue by jaleksynas** [fastlane/fastlane#14449]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Similar to #11017 I can confirm that values set via environment variables are not validated by the verify_block. This allows invalid values to get into the `run` of an action where the validation should be assumed.

##### Sample code
https://github.com/jaleksynas/VerifyBlockBroken

##### Command executed
`fastlane test`
`fastlane test_env`

**Comment by janpio** [comment]
Difficult from #11017 to retrace if this once worked differently or if there were just related changes that might have fixed (or not fixed) the issue back then.

This is where it seems to get the values from the option or ENV var alternatively:
https://github.com/fastlane/fastlane/blob/4ad2e58e41b11c8197f517d902bd0fbdb90f8e71/fastlane_core/lib/fastlane_core/configuration/configuration.rb#L219-L227

The verification seems to happen here:
https://github.com/fastlane/fastlane/blob/4ad2e58e41b11c8197f517d902bd0fbdb90f8e71/fastlane_core/lib/fastlane_core/configuration/config_item.rb#L207-L228

Which the first one connects to via `set` (`valid?` is wrapped in `verify!`):
https://github.com/fastlane/fastlane/blob/4ad2e58e41b11c8197f517d902bd0fbdb90f8e71/fastlane_core/lib/fastlane_core/configuration/configuration.rb#L265-L277

I don't really understand where the readinf of the var and the verification come together - but maybe that _is_ the problem.

**Comment by jaleksynas** [comment]
@janpio That _is_ the problem!  Setting the value in other ways `verify!`'s  correctly.  It looks like the value from the env is read during fetch (but without the verification).

Adding `&& option.verify!(ENV[option.env_name])` on line 221 of configuration.rb does the trick.

**Comment by janpio** [comment]
That is a great first step!

Is this maybe where all the "normal" parameters are validated? 
https://github.com/fastlane/fastlane/blob/4ad2e58e41b11c8197f517d902bd0fbdb90f8e71/fastlane_core/lib/fastlane_core/configuration/configuration.rb#L80-L89 
I don't really understand the code flow here...

**Comment by jaleksynas** [comment]
I believe that block is handling command-line arguments only, therefore values are each of the `--key value` pairs.

**Comment by joshdholtz** [comment]
This is merged and released in `2.119.0` 💪 Thanks for making the fix!
