### ISSUE TITLE
changelog length truncation should be bytes length instead of character length in pilot

### ISSUE THREAD

**Issue by sunwei415** [fastlane/fastlane#14443]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.gems/bin/fastlane                        |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.3_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.116.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.1.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-03-21**
</details> </pre>
</details>

**Comment by sunwei415** [comment]
I have changelog containing Chinese characters, it failed the changelog uploading though its length is below 4k, but its bytes length is over 4k.

**Comment by janpio** [comment]
So you have a changelog you tried to upload, and the upload failed. 
The reason for the failure was that the changelog is >4k bytes, correct?
Because of some code we have? Or because of something on Apple's side?

**Comment by sunwei415** [comment]
@janpio Because of some code we have in fastlane. We can see the code in this merged pull request (https://github.com/fastlane/fastlane/pull/7187)  which is mainly from issue #3956

**Comment by janpio** [comment]
Ok, that points to the code that does the truncating.

But how did this cause the upload to fail?

**Comment by sunwei415** [comment]
I have change log that is very long, around 3k-4k Chinese characters, its character length is below the condition for the current truncating implementation, but its byte length (6k-8k) is above Apple's limit(4k bytes).

**Comment by janpio** [comment]
Ok, but how did this fail for your then? Do you have some output from fastlane that shows the failure?

Is there any official Apple documentation on that 400 _byte_ limit on changelogs that we can refer to? Any website where they mention it?

**Comment by sunwei415** [comment]
No doc for the limit from Apple. I tested from the web UI on Apple Store Connect, it is true.

I truncated by myself while generating my release notes. It was long because it is from commit history and it is the first time doing it.

The error message from fastlane pilot was not take down, no clue to the limit from the message.

**Comment by sunwei415** [comment]
Issue #3956 is a reference to the 4K limit

**Comment by janpio** [comment]
Can you provide a "Lorem ipsum" style changelog example in Chinese that shows the problem (being less than 4k characters, but more than 4k bytes)? Then we can confirm the problem and implement a fix (and also create tests so this behavior is codified).

**Comment by sunwei415** [comment]
Here is it:
`
'我'*3000
`

**Comment by sunwei415** [comment]
<pre>
irb(main):003:0> ('我'*3000).length
=> 3000
</pre>

**Comment by sunwei415** [comment]
<pre>
irb(main):005:0> ('我'*3000).bytesize
=> 9000
</pre>

**Comment by janpio** [comment]
Simple and effective, thanks.

**Comment by janpio** [comment]
So, if someone is looking to contribute to fastlane, this here is a very good issue:

First best confirm manually in the web UI of Apple first that @sunwei415 's observations are correct. Then add a fixture (similar to the one added in the PR linked to in https://github.com/fastlane/fastlane/issues/14443#issuecomment-475181739) that represents https://github.com/fastlane/fastlane/issues/14443#issuecomment-475199630 and that confirms that the old behavior is broken. Then fix the code to work for that fixture as well (probably by using `.bytesize` instead of `.length` to measure the length of the changelog).

If there are any questions, feel free to reply here and ping me.

**Comment by sunwei415** [comment]
Here is the error message from fastlane pilot. I took it from build log in [Drone](https://drone.io/). 
<pre>
[!] Could not set changelog: 765: unexpected token at '<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>'

</pre>

**Comment by albertbass86** [comment]
I could try and tackle this one if that’s okay

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janpio** [comment]
This has a PR waiting to get merged.
