### ISSUE TITLE
Screenshots are only generated with 1x1 pixel

### ISSUE THREAD

**Issue by MartinEberl** [fastlane/fastlane#14444]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When creating a screenshot with multiple build targets, they are only being created with 1x1 pixel. (some even mention screenshots with 2x2 px being created)

My solution was, that in the SnapshotHelper.swift: 172
i changed the code from app.windows.firstMatch to app.screenshot() 
since the app also implements the XCUIScreenshotProviding protocol. 

##### Command executed
fastlane snapshot

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>  </pre>
</details>

### Environment
Xcode: 10.1

<details>
  <pre>  </pre>
</details>

**Comment by janpio** [comment]
So is this a bug in our `SnapshotHelper.swift` that only works in the default setting but not with "multiple build targets"? 

What does " since the app also implements the XCUIScreenshotProviding protocol." mean exactly? Is this a default thing or something you did explicitly?

**Comment by MartinEberl** [comment]
@janpio It is from my point of view.

To be more precise on the second part; XCUIApplication implements the XCUIScreenshotProviding protocol, so all you need is to call `app.screenshot()`. But i'm not quite sure and i didn't test it yet, if it works for other build targets like the Apple Watch. Best regards
