### ISSUE TITLE
Application specific password is ignored

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [fastlane/fastlane#14445]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I generated application specific password and set it to the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` env variable but when I am trying to upload a new build I get an error.

I have a ruby script where I build and uplod an application. 
Before the login, I set 2 variables 
```
ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = 'xxxx-xxxx-xxxx-xxxx'
ENV['FASTLANE_SESSION'] = '[session]'
```

and when I am already logged in and ipa file is ready I upload it 
```
package_path = FastlaneCore::ITMSPUploadPackageBuilder.new.generate(app_id: [app_id],
                                                                    app_archive_path: [archive_path],
                                                                    itmsp_package_path: '/tmp',
                                                                    platform: [platform])
transporter = FastlaneCore::ItunesTransporter.new([USERNAME], [PASSWORD])
result = transporter.upload([apple_id], package_path)
 ```

here is a final output:

```
Going to upload updated app to App Store Connect
This might take a few minutes. Please don't interrupt the script.
[Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
Transporter transfer failed.

Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
 
Application specific password you provided using environment variable FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD is invalid, please make sure it's correct

Invalid application specific password provided
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.118.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.1        |
| faraday_middleware        | 0.13.1       |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| emoji_regex               | 1.0.1        |
</details>

*generated on:* **2019-03-21**
</details>

**Comment by janpio** [comment]
If you have your own script, you don't have to use the environment variables, you can just supply your app specific password to your snippet of code yourself.

I also don't really see why you might need `FASTLANE_SESSION` for what you described, or did I miss anything?

**Comment by mykyta-bondarenko-gl** [comment]
@janpio 
- sorry, I didn't mention it. before building the app I get the latest version. To do it I log in. I user `FASTLANE_SESSION` because I have 2FA.
> you can just supply your app specific password to your snippet of code yourself
sorry, I didn't find where I can pass it as a parameter. Could you point me in pls?

**Comment by janpio** [comment]
> sorry, I didn't find where I can pass it as a parameter. Could you point me in pls?

Well, your code from above:

```
transporter = FastlaneCore::ItunesTransporter.new([USERNAME], [PASSWORD])
```

looks like the second param is the password.

**Comment by mykyta-bondarenko-gl** [comment]
@janpio hmm, everything that I should have to do is to pass a specific password instead of just a password (facepalm). 
Sorry, I thought that fastlane gets it from environments when it needs.

**Comment by janpio** [comment]
Fastlane does indeed, but possibly before it calls the method you "copied". Your code is much more stable this way too, so it's a good change any way.
