### ISSUE TITLE
Cert doesn't use custom keychain to find certificate

### ISSUE THREAD

**Issue by jcavar** [fastlane/fastlane#14453]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Cert checker supports custom keychain via `in_keychain` parameter:
https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/cert_checker.rb#L9

This is however not used from cert:

https://github.com/fastlane/fastlane/blob/master/cert/lib/cert/runner.rb#L15
https://github.com/fastlane/fastlane/blob/master/cert/lib/cert/runner.rb#L95

The result of this is that if you pass custom keychain to cert and already have certificate and key imported, cert is not able to find them and it either:
- fails because of certificate limit
- creates new certificate

**Comment by janpio** [comment]
Do you have a solution in mind and want/can create a pull request fixing this?

**Comment by jcavar** [comment]
It believe it should be simple:

In first instance:
`installed = FastlaneCore::CertChecker.installed?(ENV["CER_FILE_PATH"], in_keychain: ENV["CERT_KEYCHAIN_PATH"])`

in second move keychain path up before if statement and pass it in as well.

`keychain = File.expand_path(Cert.config[:keychain_path])`

`if FastlaneCore::CertChecker.installed?(path, in_keychain: keychain)`

**Comment by jcavar** [comment]
I can create PR but I will need some time to set up environment and everything as I don't have much experience with ruby.

**Comment by janpio** [comment]
No hurry, let me know here when you need any help.
