### ISSUE TITLE
Archive works when using Xcode, but fails with fastlane.

### ISSUE THREAD

**Issue by howardwkim** [fastlane/fastlane#14461]
### Issue Description
Archive works when using Xcode, but fails with fastlane. `react-native-xcode.sh` script fails on bundle command. It seems that the `mementum.app` link from --bundle-output` does not exist.

##### Command executed
`npm run ios:beta`

##### Complete output when running fastlane, including the stack trace and command 
```
▸ Running script 'Bundle React Native code and images'

❌  error: No such file or directory (os error 2)

❌  error: EOF while parsing a value at line 1 column 0


▸ Generating 'mementum.app.dSYM'
▸ Running script 'Upload Debug Symbols to Sentry'
▸ Touching mementum.app (in target: mementum)
** ARCHIVE FAILED **
[18:50:43]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.118.1                 |
| export_method | app-store               |
| sdk           | iPhoneOS12.1.sdk        |
+---------------+-------------------------+

[18:50:43]: ▸     builtin-validationUtility /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/InstallationBuildProductsLocation/Applications/mementum.app
[18:50:43]: ▸ Touch /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/InstallationBuildProductsLocation/Applications/mementum.app (in target: mementum)
[18:50:43]: ▸     cd /Users/howardwkim/mementum/client/ios
[18:50:43]: ▸     /usr/bin/touch -c /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/InstallationBuildProductsLocation/Applications/mementum.app
[18:50:43]:
[18:50:43]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[18:50:43]: 📋  For the complete and more detailed error log, check the full log at:
[18:50:43]: 📋  /Users/howardwkim/Library/Logs/gym/mementum-mementum.log
```

Additional details from `mementum-mementum.log`
```
+ type /Users/howardwkim/mementum/client/node_modules/@sentry/cli/sentry-cli
+ BUNDLE_FILE=/Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/BuildProductsPath/Release-iphoneos/mementum.app/main.jsbundle
+ /Users/howardwkim/mementum/client/node_modules/@sentry/cli/sentry-cli /Users/howardwkim/mementum/client/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/BuildProductsPath/Release-iphoneos/mementum.app/main.jsbundle --assets-dest /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/BuildProductsPath/Release-iphoneos/mementum.app
error: No such file or directory (os error 2)

thread 'unnamed' panicked at 'Config not bound yet': src/libcore/option.rs:1008

stack backtrace:
/Users/howardwkim/mementum/client/node_modules/react-native/scripts/react-native-xcode.sh: line 129: 20282 Abort trap: 6           "$NODE_BINARY" $NODE_ARGS "$CLI_PATH" $BUNDLE_COMMAND $CONFIG_ARG --entry-file "$ENTRY_FILE" --platform ios --dev $DEV --reset-cache --bundle-output "$BUNDLE_FILE" --assets-dest "$DEST" $EXTRA_PACKAGER_ARGS
+ [[ false != true ]]
+ [[ ! -f /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/BuildProductsPath/Release-iphoneos/mementum.app/main.jsbundle ]]
error: EOF while parsing a value at line 1 column 
```

`/Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/BuildProductsPath/Release-iphoneos/mementum.app/main.jsbundle`

Inside `/Release-iphoneos/`, mementum.app is linked:

`mementum.app -> /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/InstallationBuildProductsLocation/Applications/mementum.app`

But that file/folder does not exist. 

If I cd into `/Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/`

I see `/mementum.build`, but no `/mementum`

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Fastfile is where lanes are coded
# Lanes contain group of ctions executed synchronously
# Action is a function that performs a task

fastlane_version '2.118.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes

  before_all do
    ENV['SLACK_URL'] = 'https://hooks.slack.com/services/***'
  end


  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: '****', type: 'development', readonly: true)
    match(app_identifier: '****', type: 'appstore', readonly: true)
    # get_provisioning_profile(username: '***', app_identifier: '****')
  end

  desc 'Build iOS application'
  private_lane :build do
    certificates
    increment_build_number(
      build_number: latest_testflight_build_number(username: '***', app_identifier: '****') + 1,
      xcodeproj: './ios/mementum.xcodeproj'
    )
    gym(
      scheme: 'mementum',
      workspace: './ios/mementum.xcworkspace'
      # export_method: 'app-store', 
      # export_options: {
      #   'signingStyle' => 'manual', 
      #   provisioningProfiles: { 
      #     "****" => "mementum", 
      #   }
      # }
    )
  end  

  desc 'Ship to Testflight'
  lane :beta do
    build
    pilot(username: '***')
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/mementum.xcodeproj')
    clean_build_artifacts
    add_git_tag()
    push_to_git_remote
    slack(message: 'App successfully released to Testflight!')
  end
end

platform :android do
  # Android Lanes
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.118.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-03-22**
</details>

##### Complete Output

**Comment by janpio** [comment]
Could you please post the _complete_ output?
I assume `npm run ios:beta` somehow triggers fastlane?
And I assume your lane is failing in the `build` step?

**Comment by howardwkim** [comment]
@janpio Thank you for looking into this!

[Link to _complete_ output](https://github.com/howardwkim/fastlane_output/blob/master/complete_output)
`npm run ios:beta` triggers `fastlane ios beta`
Yes, the lane appears to be failing in the `build` step.

I ran `npm run ios:beta` again to get the _complete_ output. The errors seem to originate from the same place, but a few things have changed from the original **Issues Description** above. I can now see the `mementum` directory, and I no longer see `mementum.build`.  This time I do not see `mementum/InstallationBuildProductsLocation`.  Not sure whether this matters.

```
lrwxr-xr-x   1 howardwkim  staff   209B Mar 28 10:50 mementum.app -> /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/InstallationBuildProductsLocation/Applications/mementum.app
drwxr-xr-x   3 howardwkim  staff    96B Mar 28 10:50 mementum.app.dSYM
drwxr-xr-x   3 howardwkim  staff    96B Mar 28 10:49 react-native-async-storage
drwxr-xr-x   3 howardwkim  staff    96B Mar 28 10:49 react-native-camera
drwxr-xr-x   3 howardwkim  staff    96B Mar 28 10:49 react-native-splash-screen
➜  Release-iphoneos pwd
/Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/BuildProductsPath/Release-iphoneos
➜  Release-iphoneos /Users/howardwkim/Library/Developer/Xcode/DerivedData/mementum-bjouhfsaexfycacfjscrvhtxakfs/Build/Intermediates.noindex/ArchiveIntermediates/mementum/
➜  mementum l
total 0
drwxr-xr-x   4 howardwkim  staff   128B Mar 28 10:51 .
drwxr-xr-x   3 howardwkim  staff    96B Mar 28 10:47 ..
drwxr-xr-x@  3 howardwkim  staff    96B Mar 28 10:47 BuildProductsPath
drwxr-xr-x@ 19 howardwkim  staff   608B Mar 28 10:50 IntermediateBuildFilesPath
```

**Comment by howardwkim** [comment]
@janpio is there anything else I can provide?

**Comment by janpio** [comment]
In general it is super hard to investigate and help with individual build problems.

- The `build` action outputs the `xcodebuild` command, try to run that yourself and see what happens. If this also fails this pretty much has nothing to do with fastlane.
- Isolate the problem. Minimum lane, minimum stuff around it that we have to sift through to understand the problem.
