### ISSUE TITLE
Set a p12 password for ios_distribution

### ISSUE THREAD

**Issue by julien-hedoux** [fastlane/fastlane#14468]
Hi, 

I am trying to generate an iOS Distribution certificat. I succeed to get .certsigningRequest, .p12 and .cer files with the following source code : 

`````
	get_certificates(
	  development: false,
	  force: true,
	  username: "****@****",
	  output_path: iOS_Distribution_path,
	  filename: "ios_distribution"
	)
`````

When I forward the p12 file, the keychain tell me there is a problem about the password. 
I have to set a password. 
`p12_password` is available for push certificats but I don't know how to do with distribution certificat. 

Someone know how to set a p12 password on the distribution cert? 
Thank you,
Julien

**Comment by julien-hedoux** [comment]
I Saw this link in the doc : https://docs.fastlane.tools/actions/get_push_certificate/#note-about-empty-p12-passwords-and-keychain-accessapp

But I have this error : 

```
4569077356:error:0DFFF0A8:asn1 encoding routines:CRYPTO_internal:wrong tag:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/crypto/asn1/tasn_dec.c:1125:
4569077356:error:0DFFF03A:asn1 encoding routines:CRYPTO_internal:nested asn1 error:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/crypto/asn1/tasn_dec.c:306:Type=PKCS12
```

**Comment by snatchev** [comment]
@julien-hedoux what is the command that us used that resulted in that message?
Was it `openssl pkcs12 -info -in my.p12` ?

**Comment by julien-hedoux** [comment]
yes it is. just replaces the my.p12 by my local p12 name ;)
