### ISSUE TITLE
cli_tools_distributor.rb:122:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)

### ISSUE THREAD

**Issue by Ahmadalkhwaja** [fastlane/fastlane#14463]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane beta --verbose
[⠹] 🚀 /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.118.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> I also updated the ruby on my machine </pre>
</details>

**Comment by Ahmadalkhwaja** [comment]
gem update fastlane
Updating installed gems
Nothing to update

**Comment by janpio** [comment]
How did you install fastlane?
What does `fastlane env` return?

**Comment by ima747** [comment]
I just updated to mojave yesterday and am in the process of updating all sorts of other things. I ran fastlane lanes and it worked but threw all kinds of gems errors, so I ran gems update, and now I'm getting this issue as well. I also get this when I run fastlane env, seems one of the ruby or gems updates broke fastlane?

**Comment by ima747** [comment]
Tried some older versions of fastlane (2.118.x, 2.117.1, 2.116.1) and getting the same issue. Quite convinced it's a gem and not fastlane itself, but no idea where to begin looking for that...

**Comment by ima747** [comment]
I seem to have gotten it working by removing a google gem (I have no idea why this worked)

,,,
sudo gem uninstall google-cloud-storage --version 1.17.0
,,,

I hacked in Fastlane::VERSION and it got past the first failure but then was blowing up complaining about not being able to activate that google package. I deleted the package, ran fastlane install again to remove my hack, and success.

I know not the workings of ruby, and solutions like this convince me that a lack of knowledge keeps me sane.

**Comment by alex-taras** [comment]
I was able to fix it the same way @ima747 did, by removing google-cloud-storage 1.17.0. 1.16.0 seems to be fine.

**Comment by Calvin-Shen** [comment]
I face this problem too.
my solution,wish can help
1.rvm remove ruby;
2.rvm install ruby;
3.gem install fastlane

**Comment by Kaakati** [comment]
Actually I didn't have the Gem installed, after I saw @Calvin-Shen comment, It worked for me, thanks man, I wonder why the brew didn't work from the first time.
