### ISSUE TITLE
Spaceship::Portal.login with just the username can't find the keychain-item

### ISSUE THREAD

**Issue by geraldeersteling** [fastlane/fastlane#14466]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

I'm getting a weird issue when trying to login with the method `Spaceship::Portal.login` using only the `user` parameter. My problem is fairly the same as [this issue](https://github.com/fastlane/fastlane/issues/3543).

At runtime I only know the username of the current user I'm running fastlane for, which I'm using to log in at the Developer Portal. But the method ultimately can't find the corresponding keychain-item for the user, because the `server_name` is literally `deliver.{:user=>"myUser@email.com"}" (instead of `deliver.myUser@email.com`).

> The `deliver.myUser@email.com` is an internet-password item in my keychain and exists

In the source (`account_manager.rb`) I manually entered the correct server_name and then everything works—the correct keychain-item is being found in the `password` method.

I debugged a bit further and noticed that after calling `Spaceship::portal.login user: 'myUser@email.com'`—the `user:` param _somehow_ becomes a hash: `{:user=>"myUser@email.com"}`...this is the reason it doesn't work.

I've got no clue how to fix this, am I doing something wrong by calling this method directly?

**Comment by joshdholtz** [comment]
@geraldeersteling Heyyy 👋 `Spaceship::Portal.login` doesn't actually used the named parameters so if you just do `Spaceship::Portal.login("myUser@email.com")` it should work for you 😊

**Comment by geraldeersteling** [comment]
@joshdholtz  Nice, that seems to do the trick! Many thanks!

Maybe, just maybe the docs about this one can be updated?

In any case, thanks for the quick response 🙏

**Comment by joshdholtz** [comment]
@geraldeersteling Docs look to be up-to-date here - https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md#login 😊

But glad you got it working! Let me know if you havev any other issues/questions. Always happy to help 💪

**Comment by geraldeersteling** [comment]
Oh you're right...then somehow my Dash's docsets are outdated 😕 (they do state version 2.119.0 though)

Ah well, all well that's good. I will check the docs online next time before posting an issue! Thanks again.

**Comment by joshdholtz** [comment]
@geraldeersteling Can you send me a screenshot of what your docs look like?! Maybe its wrong in a different place then 🤔

**Comment by geraldeersteling** [comment]
@joshdholtz Of course, here they are:

![CleanShot 2019-03-25 at 15 58 44](https://user-images.githubusercontent.com/5538718/54930067-e583b680-4f16-11e9-9b02-99d14c3410aa.png)

> ☝️ this is what my Dash shows me for `Spaceship::Portal.login` 

And these are the docs downloaded with the gems:

![CleanShot 2019-03-25 at 16 00 01](https://user-images.githubusercontent.com/5538718/54930172-17951880-4f17-11e9-982f-9a1d0e2ccb34.png)

Which point to the actual docsets:

![CleanShot 2019-03-25 at 16 00 45](https://user-images.githubusercontent.com/5538718/54930212-2b407f00-4f17-11e9-9c38-2c2e53c243d4.png)

**Comment by joshdholtz** [comment]
@geraldeersteling Ahhh, those are correct! 

`login(user = nil, password = nil)` is like `login("user", "password")`

where

`login(user: nil, password: nil)` is like `login(user: "user", password: "password")` 🙃

**Comment by geraldeersteling** [comment]
Oooh crap, now you mention it I totally overlooked that 😑 Sigh, well sorry for this mistake.  
Either way still thanks for the quick responses, appreciated!

**Comment by joshdholtz** [comment]
@geraldeersteling No worries at all! Happy fastlaning 🚀❤️
