### ISSUE TITLE
add docs on how to use with nativescript

### ISSUE THREAD

**Issue by yahyaKacem** [fastlane/fastlane#14477]
### Question Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

How to set up fastlane with a nativescipt project.

#### Question Description
How to set up fastlane with a nativescipt project the correct paths and available variables for someone that didn't work with Gradle or separate IOS and Android apps.

**Comment by janpio** [comment]
Is there any documentation out there that works?

**Comment by yahyaKacem** [comment]
@janpio not that I'm aware of.

**Comment by janpio** [comment]
That's a shame, I am not aware of an NativeScript developers here.

Can you create an super simple Hello World project and put it on Github? Maybe I or someone else finds the time to play with it a bit and set it up for fastlane.

**Comment by yahyaKacem** [comment]
Actually I figured it out, the build is done with nativescript-cli and only the upload is done with fastlane, and that's simple enough, just use the `apk` option of the `upload_to_play_store` action.
I used this configurations:
```
upload_to_play_store(track: 'beta', apk: './app-release.apk')
```
Nativescript-cli generates an app in the root folder named `app-release.apk` with a command like this:
```
tns build android --release --key-store-path 'keystore-file.keystore' --key-store-password 'ketStorePassword' --key-store-alias 'ketStoreAlias' --key-store-alias-password 'ketStoreAliasPassword' --copy-to './' --bundle
```

**Comment by janpio** [comment]
You could either write a blog post and link to it in a new page in https://github.com/fastlane/docs/tree/master/docs/getting-started/cross-platform, or even write it down on a new page there directly in the Fastlane docs. 

Would also love to get some information on iOS as well!
