### ISSUE TITLE
latest_testflight_build_number fails to get correct number if previous version has been manually expired

### ISSUE THREAD

**Issue by doogilasovich** [fastlane/fastlane#14476]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The versioning plugin is not getting the highest build number, if the highest build number is on a build that has been manually expired by an account user (in iTunesConnect). 

Result:
the plugin returns the build number of the highest non-expired build. 

Expected:
I would expect that the plugin would get the highest number for any build for that version number.

Specifically in this case, the highest build number was 4230 (manually expired, but still shown in iTunesConnect), but the plugin returned the second highest number (4210, not expired). 

##### Command executed
fastlane run latest_testflight_build_number app_identifier:my.app.ID

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀 
[12:41:12]: fastlane detected a Gemfile in the current directory
[12:41:12]: however it seems like you don't use `bundle exec`
[12:41:12]: to launch fastlane faster, please use
[12:41:12]: 
[12:41:12]: $ bundle exec fastlane run latest_testflight_build_number app_identifier:my.app.ID
[12:41:12]: 
[12:41:12]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+----------------------------+---------+---------------------------------------------------+
|                                       Used plugins                                       |
+----------------------------+---------+---------------------------------------------------+
| Plugin                     | Version | Action                                            |
+----------------------------+---------+---------------------------------------------------+
| fastlane-plugin-versioning | 0.3.4   | get_version_number_from_git_branch                |
|                            |         | get_version_number_from_plist                     |
|                            |         | get_build_number_from_plist ci_build_number       |
|                            |         | increment_version_number_in_plist                 |
|                            |         | get_app_store_version_number get_info_plist_path  |
|                            |         | increment_build_number_in_plist                   |
+----------------------------+---------+---------------------------------------------------+

[12:41:13]: --------------------------------------------
[12:41:13]: --- Step: latest_testflight_build_number ---
[12:41:13]: --------------------------------------------
[12:41:13]: Login to App Store Connect (myemail@redacted.com)
[12:41:15]: Login successful
[12:41:20]: Fetching the latest build number for version 2.7
[12:41:21]: Latest upload for version 2.7 is build: 4210
[12:41:21]: Result: 4210
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.3                                          |
| Ruby                        | 2.5.0                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.17.2 (Apple Git-113)               |
| Installation Source         | /usr/local/bin/fastlane                          |
| Host                        | Mac OS X 10.14.3 (18D109)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib               |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.10.1.app/Contents/Developer/ |
| Xcode Version               | 10.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |

*generated on:* **2019-03-26**
</details>

**Comment by janpio** [comment]
This is the code that produces the output above: 
https://github.com/fastlane/fastlane/blob/30be4096f3c9a84c9fee3cf4a73c71a7508313f4/fastlane/lib/fastlane/actions/app_store_build_number.rb#L8-L70

The relevant part is this:
https://github.com/fastlane/fastlane/blob/30be4096f3c9a84c9fee3cf4a73c71a7508313f4/fastlane/lib/fastlane/actions/app_store_build_number.rb#L55-L67

It seems `all_builds_for_train` from spaceship doesn't return manually expired versions.

If you follow the method calls, you end up at https://github.com/fastlane/fastlane/blob/0e52f122da641c5984faf88049e65f79f2ac9b46/spaceship/lib/spaceship/test_flight/client.rb#L34-L40

Could you please take a look at your spaceship logs at `/tmp/spaceship*.log`, search for this URL and then check if the response includes the expired build or not? 

I expect it to _not_ include it, as I didn't see any code that removes expired builds from the result. But that would also mean that it is not possible for fastlane to actually include expired builds - at least not with the requests we are sending right now.

If this is indeed true, then we would have to investigate if the web UI of Apple actually returns the expired builds somewhere and if and how we can request them as well and if it makes sense to include that in the methods above or similar.

**Comment by Zycon42** [comment]
We have a build with processing issue and indeed `latest_testflight_build_number` action doesn't return it, but it's there because uploading to testflight fails due to duplicate build number.

I checked the `/tmp/spaceship*.log` and unfortunately that expired build is not present in the rest call response :( I also looked around in appstoreconnect UI and I didn't find expired build anywhere :(

**Comment by janpio** [comment]
Thanks @Zycon42, that would unfortunately mean that we don't have many options here. Maybe @doogilasovich can confirm if it is the same for manually expired builds.

**Comment by nklausni** [comment]
I have a similar issue, when the build is denied by Apple (for example when a purpose string in Info.plist is missing)

**Comment by aruggles** [comment]
I don't know if this is related but I just started having an issue getting the build number today.  Here is what I'm seeing in the logs:

```
# Logfile created on 2019-04-03 13:02:29 -0700 by logger.rb/56438
INFO  [13:02:29]: >> GET providers/118004236/apps/973741088/platforms/ios/trains/2.7.0/builds: [undefined body] 
DEBUG [13:02:31]: << GET providers/118004236/apps/973741088/platforms/ios/trains/2.7.0/builds: 410 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/118004236/apps/973741088/platforms/ios/trains/2.7.0/builds. Reason:
<pre>    Gone</pre></p>
</body>
</html>
```

**Comment by lumaxis** [comment]
@aruggles To me, this seems like a separate issue. But looking at the number of 👍🏼, a bunch of people seem to be hitting it. Do you want to use that info and open a new issue here?

**Comment by lumaxis** [comment]
Looks like there is #14521 now, to cover this 🔍

**Comment by aruggles** [comment]
Thanks

**Comment by BenWildeman** [comment]
can confirm that the changes made for #14521 has fixed this issue for me

**Comment by janpio** [comment]
Which issue @BenWildeman? The original one this post is about, or the one that I hid because it was offtopic and related to the "Error 410 Gone" problem?

**Comment by BenWildeman** [comment]
sorry, should have mentioned. the original issue of not getting the highest build number
