### ISSUE TITLE
Expired provision profiles are not visible from spaceship

### ISSUE THREAD

**Issue by ptuko** [fastlane/fastlane#14475]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have ruby script that is using Spaceship to generate and download distribution provision profiles. 

```
#Login into spaceship and select correct teamID
Spaceship::Portal.login(username, password)
Spaceship::Portal.client.team_id = team_id

#Check if AppID exists
app = Spaceship::Portal.app.find(bundle_id)

if app == nil
    
    #If AppID doesn't exists create it
    app = Spaceship::Portal.app.create!(bundle_id: bundle_id, name: application_name)
    
else
    #AppID exists
end

#Check if provision profile exists
profile = Spaceship::Portal.provisioning_profile.app_store.all.find { |p| p.name == "#{bundle_id} AppStore" }

if profile != nil
    #If provision profile exists delete it
    #This will reset 1 year expiration and select all new devices for AdHoc builds
    profile.delete!
end

# Find AppStore distribution certificate
certificate = Spaceship::Portal.certificate.production.all.find { |c| "#{c.expires}" == "#{certificate_expires}" }

if certificate != nil
    
    #Create new distribution provision profile
    profile = Spaceship::Portal.provisioning_profile.app_store.create!(bundle_id: bundle_id, certificate: certificate)
    
else

    puts "Correct certificate could not be found!"
    
end

#Check if distribution provision profile was created
if profile != nil
    
    #download profile
    File.write("#{root}/Resources/ProvisionProfiles/#{application_name}.mobileprovision", profile.download)
    puts "Profile downloaded!"
    
else
    
    puts "Profile cannot be created!"
    
end
```

Unfortunately, when provision certificates are expired, command
`profile = Spaceship::Portal.provisioning_profile.app_store.all.find { |p| p.name == "#{bundle_id} AppStore" }`
will set profile to nil, even when this profile exists on developer.apple.com,
Then script tries to create provision profile with this name and it will fail with error:

> {"responseId"=>"a5e88fa7-95b1-4e94-ad58-7895313dbb11", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"Multiple profiles found with the name 'com.***.***** AppStore'.  Please remove the duplicate profiles and try again.", "creationTimestamp"=>"2019-03-26T15:26:51Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"provisioningProfileName", "validationUserMessage"=>"Multiple profiles found with the name 'com.***.***** AppStore'.  Please remove the duplicate profiles and try again."}]} (Spaceship::UnexpectedResponse)

When using sample code from url https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md -> same result (broken_profiles are empty)
```
# Select all 'Invalid' or 'Expired' provisioning profiles
broken_profiles = Spaceship::Portal.provisioning_profile.all.find_all do |profile|
  # the below could be replaced with `!profile.valid? || !profile.certificate_valid?`, which takes longer but also verifies the code signing identity
  (profile.status == "Invalid" or profile.status == "Expired")
end

# Iterate over all broken profiles and repair them
broken_profiles.each do |profile|
  profile.repair! # yes, that's all you need to repair a profile
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.0/bin/fastlane       |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 1.17.2       |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-03-26**
</details>

**Comment by janpio** [comment]
Have you looked at the code of `Spaceship::Portal.provisioning_profile.app_store.all.find` why it doesn't include expired profiles?

**Comment by vscafuto** [comment]
I have the same issue!
When its certificate is expired (and the provisioning profile expires too), the command:
**Spaceship::Portal.provisioning_profile.app_store.all**
doesn't provide the profile, even if it exists on developer.apple.com
So, how can we remove the expired profile with Spaceship?

Thank you.

**Comment by janpio** [comment]
Have you looked at the code of `Spaceship::Portal.provisioning_profile.app_store.all` why it doesn't include expired profiles?

**Comment by imanf** [comment]
I'm having the same issue as well, except when I run the following:
Spaceship.provisioning_profile.find_by_bundle_id(bundle_id: "#{$app_id}").map!(&:delete!)

It works if the profile is not expired, but does not work if the profile is expired.
