### ISSUE TITLE
[action] Android: add JVM options parameter for crashlytics

### ISSUE THREAD

**Issue by radikpsb** [fastlane/fastlane#14488]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have to pass corporate proxy's username and password to java executable when uploading a build to crashlytics. Is there a chance to add an option to crashlytics method which I invoke from Fastfile?

E.g. crashlytics(api_key: key, build_secret: secret, vmopts: "-Dhttps.proxyHost=proxy.local -Dhttps.proxyPort=443 -Dhttps.proxyUser=admin -Dhttps.proxyPassword=qwerty")

**Comment by janpio** [comment]
Hm interesting. Is there no way to configure this externally via an environment variable? We probably have many more Java tools that might require this, so adding this to all actions manually seems like a lost fight.

**Comment by radikpsb** [comment]
You are right, the env variable JAVA_TOOL_OPTIONS can contain all necessary flags. The problem is that JVM always prints out this variable including my proxy password. There is no way to turn off this behavior. At least I haven't found it.

There's is a parameter for gradle in fastlane (https://docs.fastlane.tools/actions/gradle/) called system_properties. It would be great to have smth similar for crashlytics.

**Comment by janpio** [comment]
Understood.

Is "system properties" a common name for these `-D` parameters in the Java world? If yes, I think you can go ahead and create a Pull Request with that naming scheme. 

(When you are at it, could you maybe add an example and improve the description of `gradle` as well so this becomes a bit more discoverable what this param is meant to be used for? The proxy thing or the example from the original PR seem to be good examples: https://github.com/fastlane/fastlane/pull/10883)
