### ISSUE TITLE
Ruby error while trying to install on Fedora Linux

### ISSUE THREAD

**Issue by mareklowy** [fastlane/fastlane#14482]
Hey, I have tried following the install instructions on Fedora 29:

> Se here are the installation steps for anyone stumbling here trying to figure out how to do this on Ubuntu 18.04:
> 
> ### Install ruby and ruby-dev headers
> ```
> sudo apt install ruby ruby-dev
> ```
> ### Set environment language variables
> #### Add these lines to the top of `~/.profile`
> ```
> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> ```
> #### Check that you didn't break the environment and restart
> run `source ~/.profile` in the terminal. If no output, you are safe. Otherwise, check for what you broke in the .profile file 
> 
> ### Install fastlane
> ```
> sudo gem install fastlane -NV
> ```
> From there do the normal Fastlane Setup:
> https://docs.fastlane.tools/getting-started/android/setup/

However when I tried running the `sudo gem install fastlane -NV` I get folling error log:
```
    Building native extensions. This could take a while...
    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
    /usr/bin/ruby -r ./siteconf20190327-12548-b9qtga.rb extconf.rb
    checking for -lstdc++... no
    creating Makefile
    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
    make "DESTDIR=" clean
    rm -f 
    rm -f unf_ext.so  *.o  *.bak mkmf.log .*.time
    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
    make "DESTDIR="
    g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall - 
    Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS 
    fexceptions  -
    fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 - 
    specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack- 
    clash-protection -fcf-protection -m64 -o unf.o -c unf.cc
    make: g++: Command not found
    make: *** [Makefile:211: unf.o] Error 127
    ERROR:  Error installing fastlane:
    ERROR: Failed to build gem native extension.
    Building has failed. See above output for more information on the failure.
    make failed, exit code 2
    Gem files will remain installed in /usr/local/share/gems/gems/unf_ext-0.0.7.5 for inspection.
    Results logged to /usr/local/lib64/gems/ruby/unf_ext-0.0.7.5/gem_make.out
```
I have installed gcc, make, ruby, ruby-devel, but something seems to be missing and I can-t figure out what. I have also added language variables into my profile file. 
I have noticed the log stating "checking for -lstdc++... no", however I don't knwo where to get it.
Thank you for your help.

**Comment by janpio** [comment]
Found an old issue, unfortunately no answer but a question: https://github.com/fastlane/fastlane/issues/6172

**Comment by mareklowy** [comment]
So, I have managed to fix the missing lstdc++ with `sudo yum install libstdc++-static`, however the installation will still result with an error.
```
Building native extensions. This could take a while...
current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
/usr/bin/ruby -r ./siteconf20190328-32446-1gj136w.rb extconf.rb
checking for -lstdc++... yes
creating Makefile
current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
make "DESTDIR=" clean
rm -f 
rm -f unf_ext.so  *.o  *.bak mkmf.log .*.time
current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.5/ext/unf_ext
make "DESTDIR="
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -m64 -o unf.o -c unf.cc
make: g++: Command not found
make: *** [Makefile:211: unf.o] Error 127
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2

Gem files will remain installed in /usr/local/share/gems/gems/unf_ext-0.0.7.5 for inspection.
Results logged to /usr/local/lib64/gems/ruby/unf_ext-0.0.7.5/gem_make.out
```

**Comment by mareklowy** [comment]
I have managed to fix the issue with missing g++. The problem was that the package is called little different in Fedora. `sudo dnf install gcc-c++` installed correct package and fixed the installation problem.

**Comment by janpio** [comment]
Great!

Would be awesome if you could post the full, updated instructions for Fedora Linux in the issue where you originally commented - then other users can benefit from it as well.
