### ISSUE TITLE
Not possible to call `xcode_select` from Swift

### ISSUE THREAD

**Issue by iandundas** [fastlane/fastlane#14489]
## Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

## Question Subject

It does not seem to be possible to call `xcodeSelect` in the Swift version of fastlane.

#### Background: 
From Ruby, `xcode_select`requires an unnamed parameter to be provided, you call it like:

`xcode_select("/Applications/Xcode10.2.0.app")`.

This appears to be unusual in fastlane (to have an unnamed parameter) - usually there is either no parameters or they are named, e.g. `build_ios_app(
  scheme: "Release",
  ...
)`

Unfortunately I don't think this is supported in Swift Fastlane.

#### The Problem:

In the Swift version of fastlane, the equivalent of `xcode_select` does not take any parameters at all: `func xcodeSelect(){}`. This means it cannot be used, as you cannot provide the Xcode path that is required by the underlying action.

Calling it logs the error:

> Path to Xcode application required (e.g. `xcode_select("/Applications/Xcode.app")`) 

I tried to modify the function myself to take a parameter, but digging into the code, the [RubyCommand](https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/swift/RubyCommand.swift) itself doesn't seem to support passing an unnamed parameter, so at that point I was stumped.

So I guess the way the Swift function stubs/bridging functions (not sure of term) are being generated are not supporting this edge-case

**Comment by janpio** [comment]
I agree.

Here is the code of the ruby action: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/xcode_select.rb

A possible solution would probably be to add a real, optional parameter to the action that is used as a fallback (although I am not sure how compatible that would or could be with the current way it works). That could then create code in Swift that works...

But looking at the ruby code, the action only seems to set `ENV["DEVELOPER_DIR"]` and nothing else, is this correct? If so, you should be able to replicate that easily.

**Comment by iandundas** [comment]
Haha good point, `xcode_select` itself is very simple - I'll look into just doing that manually from Swift then. Thanks for your help
