### ISSUE TITLE
Team does not show up for Apple ID

### ISSUE THREAD

**Issue by bestimmaa** [fastlane/fastlane#14497]
### Question Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### One of my teams for the Apple ID is not showing up

I have an Apple ID I use in 3 different teams on Apple Developer Portal. When I do _fastlane init_ I get prompted for the Apple ID and get the selection for teams. After selecting the team I want to use, I get the prompt again but without the team I want to choose. The account has the 'Admin' role in the team I want to use. Is this a bug or do I miss something here? Used a similar setup in the past without problems. Might be worth mentioning that we use the same company name for an InHouse (Enterprise) and a regular account.

#### Log output

```
[16:04:56]: Please enter your Apple ID developer credentials
[16:04:56]: Apple ID Username:
mobile_dev@OURDOMAIN.com
[16:05:02]: Logging in...
Multiple App Store Connect teams found, please enter the number of the team you want to use:
1) "CORP GmbH" (118719146)
2) "CORP GmbH - 44N2W24B6J" (119610774)
3) "CORP Lab GmbH" (117861784)
1
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) 44N2W24B6J "CORP GmbH" (In-House)
2) 94MSG646AN "CORP Lab GmbH" (Company/Organization)

```

**Comment by bestimmaa** [comment]
The issue can be resolved by deselecting, saving and selecting 'Access to Certificates, Identifiers & Profiles' in App Store Connect for the account in question. Issue can be closed.

**Comment by max-ott** [comment]
For reference here are the official docs /links:
https://help.apple.com/app-store-connect/#/devad498718e
https://developer.apple.com/support/roles/

@bestimmaa you should be able to close the issue yourself as you are the author.

**Comment by bestimmaa** [comment]
Thanks will close it. I'm aware of the roles, just wanted to share that someone might need to toggle this feature once if he encounters this issue.
