### ISSUE TITLE
[push_to_git_remote] Add optional upstream reference when pushing to remote

### ISSUE THREAD

**Issue by ishegg** [fastlane/fastlane#14491]
#### Motivation Behind Feature
I'm trying to automate my dev workflow as much as possible. So when designing it, I thought about adding a lane that bumps the version and build number, then creates a `release/vVERSION` branch, commits the bump, and finally pushes the new branch to the remote (which should trigger CI). Digging around the docs I see that there's no option to set the `-u` flag for the `push_to_git_remote` action.

#### Feature Description
The request basically entails adding a single parameter to the command:

    # optionally add the set-upstream component
    command << '--set-upstream' if params[:upstream]

#### Alternatives or Workarounds
Right now the alternative is to do everything in the lane and when it's done simply push manually.

#### Unrelated

I recently discovered fastlane and just wanted to say thanks. It's incredibly useful, well done, and documented. Great work guys!

**Comment by janpio** [comment]
Thanks 💐 

---

Your suggestions sounds good, but I use Sourcetree as a git GUI because I can never remember and parameters, so 🤷‍♀️ Could you maybe explain the use case a bit? Why do you want to set the upstream?

**Comment by ishegg** [comment]
The `--set-upstream` flag is needed when the branch doesn't exist in the remote, i.e. it's new. It's so the remote knows how to relate the two branches. If you try to simply push a new brand it'll complain:

    fatal: The current branch feature/test has no upstream branch.
    To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature/test

So in the suggested workflow, the branch would need to be set upstream on the remote because it's a new one.

I see you added the "you can do this" label. I've never written Ruby but the change seems easy enough, I'll give it a try and run the tests. Thanks for your response!

**Comment by ishegg** [comment]
@janpio I had some time after work so gave it a shot. PR #14496.
