### ISSUE TITLE
I want to use xml in my Fastfile, so I add rexml in that file, but why the include can't be recognized?

### ISSUE THREAD

**Issue by Santiago0412** [fastlane/fastlane#14505]
#### Question Description
I want use REXML, code like this:
#!/usr/bin/ruby
require 'rexml/document'
include REXML

this is the mistake
[!] Could not find action, lane or variable 'include'. Check out the documentation for more details: https://docs.fastlane.tools/actions

**Comment by Santiago0412** [comment]
require "rexml/document"
file = File.new( "mydoc.xml" )
doc = REXML::Document.new file

using this other than include solve my problem.

**Comment by janpio** [comment]
Because `include` in Ruby works different than e.g. in PHP or C. This eplxains it quite well: https://stackoverflow.com/questions/318144/what-is-the-difference-between-include-and-require-in-ruby
