### ISSUE TITLE
Fastlane Swift fails after upgrading to XCode 10.2

### ISSUE THREAD

**Issue by IchordeDionysos** [fastlane/fastlane#14515]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running any fastlane Swift lane after upgrading to XCode 10.2 fails.

##### Command executed
`fastlane beta --capture_output`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀 
[13:32:45]: fastlane detected a Gemfile in the current directory
[13:32:45]: however it seems like you don't use `bundle exec`
[13:32:45]: to launch fastlane faster, please use
[13:32:45]: 
[13:32:45]: $ bundle exec fastlane beta --capture_output
[13:32:45]: 
[13:32:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2019-04-02 13:32:45.99]: Successfully loaded custom action '/Users/denniskugelmann/develop/simpleclub-ios-app/fastlane/actions/add_keys_to_lokalise.rb'.
INFO [2019-04-02 13:32:45.99]: Successfully loaded custom action '/Users/denniskugelmann/develop/simpleclub-ios-app/fastlane/actions/lokalise.rb'.
INFO [2019-04-02 13:32:46.00]: Successfully loaded custom action '/Users/denniskugelmann/develop/simpleclub-ios-app/fastlane/actions/lokalise_metadata.rb'.
DEBUG [2019-04-02 13:32:46.00]: Checking if there are any plugins that should be loaded...
INFO [2019-04-02 13:32:46.59]: loading manifest: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/swift/upgrade_manifest.json
DEBUG [2019-04-02 13:32:46.70]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2019-04-02 13:32:46.71]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.44/0.9.44
DEBUG [2019-04-02 13:32:46.71]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.6/0.9.6
DEBUG [2019-04-02 13:32:46.71]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.71]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.5/0.9.5
DEBUG [2019-04-02 13:32:46.71]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2019-04-02 13:32:46.71]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.9/0.9.9
DEBUG [2019-04-02 13:32:46.72]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2019-04-02 13:32:46.72]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.4/0.9.4
DEBUG [2019-04-02 13:32:46.72]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.72]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.72]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.72]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.72]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.72]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.73]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.73]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.73]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.73]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.73]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-04-02 13:32:46.73]: Checking for new user-provided tool configuration files
INFO [2019-04-02 13:32:46.74]: FastlaneSwiftRunner project is up-to-date
INFO [2019-04-02 13:32:46.75]: Successfully loaded custom action '/Users/denniskugelmann/develop/simpleclub-ios-app/fastlane/actions/add_keys_to_lokalise.rb'.
INFO [2019-04-02 13:32:46.75]: Successfully loaded custom action '/Users/denniskugelmann/develop/simpleclub-ios-app/fastlane/actions/lokalise.rb'.
INFO [2019-04-02 13:32:46.75]: Successfully loaded custom action '/Users/denniskugelmann/develop/simpleclub-ios-app/fastlane/actions/lokalise_metadata.rb'.
DEBUG [2019-04-02 13:32:46.75]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2019-04-02 13:32:47.00]: $ ./fastlane/FastlaneRunner lane beta logMode verbose swiftServerPort 2000 > /dev/null
INFO [2019-04-02 13:32:47.02]: ▸ dyld: Library not loaded: @rpath/libswiftCore.dylib
INFO [2019-04-02 13:32:47.02]: ▸ Referenced from: /Users/denniskugelmann/develop/simpleclub-ios-app/./fastlane/FastlaneRunner
INFO [2019-04-02 13:32:47.02]: ▸ Reason: image not found
INFO [2019-04-02 13:32:47.02]: ▸ sh: line 1: 33041 Abort trap: 6           ./fastlane/FastlaneRunner lane beta logMode verbose swiftServerPort 2000 > /dev/null
WARN [2019-04-02 13:32:51.75]: Lane Context:
INFO [2019-04-02 13:32:51.76]: {:LANE_NAME=>"beta"}
ERROR [2019-04-02 13:32:51.76]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
ERROR [2019-04-02 13:32:51.76]: fastlane finished with errors
</pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D109)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

enum ReleaseType: String {
    case major = "major"
    case minor = "minor"
    case patch = "patch"
}

class Fastfile: LaneFile {
    func beforeAll() {
        setupCircleCi()
    }

    func betaLane(withOptions options:[String: String]?) {
        buildSimpleclub(withOptions: options)
    }

    func releaseLane(withOptions options:[String: String]?) {
        let newBuildNumber = getNewBuildNumber()
        sh(command: "git checkout -b release/\(newBuildNumber) develop")
        
        buildSimpleclub(withOptions: options)

        let buildNumber = getBuildNumber(xcodeproj: "simpleclub.xcodeproj")
        let versionNumber = getVersionNumber()

        sh(command: "git add -A && git commit -m \"Version \(versionNumber) (\(buildNumber))\"")
        sh(command: "git checkout master")
        sh(command: "git merge --no-ff release/\(newBuildNumber)")
        sh(command: "git tag \"v\(versionNumber)-beta\"")
        sh(command: "git checkout develop")
        sh(command: "git merge --no-ff release/\(newBuildNumber)")
        sh(command: "git branch -d release/\(newBuildNumber)")

        pushToGitRemote(localBranch: "develop")
        pushToGitRemote(localBranch: "master")
    }

    func buildSimpleclub(withOptions options:[String: String]?) {
        ensureGitStatusClean()
        guard let releaseType = ReleaseType(rawValue: options?["type"] ?? "") else {
            fatalError("Please define a release type either type:major, type:minor or type:patch")
        }
        match(type: "appstore", readonly: true, gitUserEmail: "user@example.com")
        desc("Push a new beta build to TestFlight")
        let newBuildNumber = getNewBuildNumber()

	    incrementBuildNumber(xcodeproj: "simpleclub.xcodeproj")
        incrementVersionNumber(bumpType: releaseType.rawValue)
	    buildApp(workspace: "simpleclub.xcworkspace", scheme: "simpleclub")
    }

    func getNewBuildNumber() -> Int {
        return (Int(getBuildNumber(xcodeproj: "simpleclub.xcodeproj")) ?? 0) + 1
    }

    func restLane() {
        let oldVersionNumber = "4.2.3"

        let versionNumber = getVersionNumber()
        let buildNumber = getBuildNumber(xcodeproj: "simpleclub.xcodeproj")

        sh(command: "git checkout master")
        sh(command: "git merge --no-ff release/\(oldVersionNumber)")
        sh(command: "git tag -a v\(versionNumber)-beta")
        sh(command: "git merge --no-ff release/\(oldVersionNumber)")
        sh(command: "git branch -d release/\(oldVersionNumber)")

        pushToGitRemote(localBranch: "develop")
        pushToGitRemote(localBranch: "master")
    }

    func ciBetaLane(withOptions options:[String: String]?) {
        uploadToTestflight(username: "user@example.com", ipa: "./simpleclub.ipa")

        let versionNumber = getVersionNumber()
        let buildNumber = getBuildNumber(xcodeproj: "simpleclub.xcodeproj")
        refreshDsymsLane(withOptions: [
            "version": versionNumber,
            "build": buildNumber
        ])
    }

    func refreshDsymsLane(withOptions options:[String: String]?) {
        guard let version = options?["version"] else {
            fatalError("Please define the app version for the dsyms")
        }
        guard let build = options?["build"] else {
            fatalError("Please define the app build number for the dsyms")
        }
        downloadDsyms(
                username: "user@example.com",
                appIdentifier: "de.thesimpleclub.thesimpleclub.ios",
                version: version)
        uploadSymbolsToCrashlytics(dsymPath: "./de.thesimpleclub.thesimpleclub.ios-\(version)-\(build).dSYM.zip")
        cleanBuildArtifacts()
    }
	
	/// Downloades all localilizables from lokalise and updates Localizables.string
	func updateLocalizablesLane() {
		sh(command: "fastlane run lokalise api_token:our_token project_identifier:our_identifier destination:./simpleclub")
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.3       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-04-02**
</details>

**Comment by nickfedoroff** [comment]
I have a similar issue, only with
`dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib`

**Comment by paiv** [comment]
From [Swift 5 Release Notes for Xcode 10.2](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2)

> **Swift 5 Runtime Support for Command Line Tools Package**
Starting with Xcode 10.2, Swift command line tools require the Swift libraries in macOS. They’re included by default starting with macOS Mojave 10.14.4. In macOS Mojave 10.14.3 and earlier, there’s an optional package to provide these runtime support libraries for Swift command line tools that you can download from [More Downloads for Apple Developers](https://developer.apple.com/download/more/). If you installed the beta version of this package, replace it with the release version. This package is only needed for Swift command line tools, not for apps with graphical user interfaces.

**Comment by janpio** [comment]
Thanks @paiv. Did this help you @nickfedoroff and @IchordeDionysos?
If so, should this be added to the Fastlane Swift (Beta) docs somewhere?

**Comment by IchordeDionysos** [comment]
@paiv @janpio Thanks so much.
That helped at least for me.
I talked to a collegue who had the same issue and for him the issue resolved after some time without installing anything else.
Maybe he has a newer version of macOS or something. Not quite sure.

This should be a temporary issue right?
As this has to do something with having updated XCode but not yet macOS?!
So I'm not sure if this is something that you include in your docs if this only affects a small portion of users for rather limited time.

**Comment by moglistree** [comment]
Is there a way to install Swift 5 Runtime Support for Command Line Tools Package over the command line? For CI purposes.

**Comment by dan-ryan** [comment]
"For CI purposes."
I updated from 10.2.0 to 10.2.1 in CircleCI and it fixed this issue.
