### ISSUE TITLE
2FA 6 digit when entered does not proceed

### ISSUE THREAD

**Issue by devpascoe** [fastlane/fastlane#14520]
Its been a while so my login seems to have expired. When pushing to testflight for Apple i get the following:

```
[15:54:23]: Starting login with user 'myemailhere@domain.com'
Available session is not valid any more. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account 'myemailhere@domain.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)
Please enter the 6 digit code:
```
Naturally i enter the code that was sent by SMS. Nothing happens, the build/submission never proceeds, just hangs there.

Anyone else facing this? I'm running on latest fastlane.

**Comment by janpio** [comment]
Did you get the initial code via SMS? Usually that is pushed to a device - at least that was the assumption when I added auth via SMS.

Have you tried typing `sms` to escape to the SMS flow and then finish that one?

Maybe your account setup is not currently covered correctly. Can you show what the "Security" section on appleid.apple.com looks like to you?

![image](https://user-images.githubusercontent.com/183673/55516877-e4692c80-566e-11e9-8e88-0b048558e341.png)

**Comment by bedhub** [comment]
We experience similar issue. I received a code on the iOS device, entered it but nothing happens

**Comment by janpio** [comment]
Did you receive the code via SMS or "push" (where you first have to tap "Allow" under a map of your location) @bedhub? Do the numbers show up when you type them? And then you confirm with Enter and nothing happens?

**Comment by janpio** [comment]
I just saw that @RichardFevrier, @aarshaw, @ChristopherStephan and @kirillpisarev also upvoted the initial issue here. Could you add some more information that may allow me to understand what is going on here? Currently I only have this report "stuff is broken" but not further information to go on :/

**Comment by max-ott** [comment]
SMS works 100% for me test with multiple accounts. Please let us know your complete setup.

**Comment by zhxf2012** [comment]
I have get the same case After I update fastlane to the latest.

fastlane env  below 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.122.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.0       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>


*generated on:* **2019-05-09**
</details>

**Comment by janpio** [comment]
What does "same case" mean exactly @zhxf2012?
What exactly are you doing and what exactly is happening (or not happening?)
What is the _complete_ output you are getting?

It might also help if oyu answer the other questions I left above:
https://github.com/fastlane/fastlane/issues/14520#issuecomment-479678614
https://github.com/fastlane/fastlane/issues/14520#issuecomment-487571746

**Comment by zhxf2012** [comment]
My case : when I run   bundle exec fastlane DownloadMetadata , It ask me to   Please enter the 6 digit code:  ,then I get the code from my phone and I allow, after I input the  6 digit code and enter.It hangs for hours nothing happend,I have try sever times. and also remove the cach but no result. Before update fastlane ,I can get sign in and Download Metadata.

So  I am sure I have  received the code via SMS or "push" (where you first have to tap "Allow" under a map of your location) Do the numbers show up when you type them? And then you confirm with Enter and nothing happens.  And my fastlane work fine a month ago so it has been setup correctly.

**Comment by janpio** [comment]
Thanks for the feedback @zhxf2012 - this is _really_ strange.

Can you please run `bundle exec fastlane run spaceship_logs` so we know what requests fastlane is sending to Apple? (and what it is getting back).

---

@devpascoe, @RichardFevrier, @aarshaw, @ChristopherStephan and @kirillpisarev could you please also post your `fastlane env` output? Maybe there is something common with @zhxf2012 that will help us understand what is going on.

**Comment by max-ott** [comment]
So I just tried out both ways (2 Step via device and SMS) with the latest `fastlane` version `2.122.0` and it worked both ways.

Steps to reproduce:
1. Make sure you are on latest version
2. `bundle exec irb`
3. `Spaceship::Tunes.login("your@email.com", "password")`
4a. Accept on Mac or iOS device and enter code in console
4b. Type `sms` in the console and confirm phone number with `1` etc. Enter code from SMS

Responses in console should look something like:
```>> Spaceship::Tunes.login("•••••@•••••.com", "•••••••••••••••")
Two-factor Authentication (6 digits code) is enabled for account '•••••@•••••.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
sms
Please select a trusted phone number to send code to:
1. +49 ••••• •••••12
?  1

Successfully requested text message to +49 ••••• •••••12
Please enter the 6 digit code you received at +49 ••••• •••••12:
701122
Requesting session...
```

If you enter the "push" code, the part after `sms` won't be there and you should get the `Requesting session...`

**Comment by zhxf2012** [comment]
> Thanks for the feedback @zhxf2012 - this is _really_ strange.
> 
> Can you please run `bundle exec fastlane run spaceship_logs` so we know what requests fastlane is sending to Apple? (and what it is getting back).
> 
> @devpascoe, @RichardFevrier, @aarshaw, @ChristopherStephan, @bedhub and @kirillpisarev could you please also post your `fastlane env` output? Maybe there is something common with @zhxf2012 that will help us understand what is going on.

Hi , I run   bundle exec fastlane run spaceship_logs and get logs belown 

 Logfile created on 2019-05-09 11:11:55 +0800 by logger.rb/56438
INFO  [11:11:55]: >> GET https://olympus.itunes.apple.com/v1/session: [undefined body] 
DEBUG [11:11:56]: << GET https://olympus.itunes.apple.com/v1/session: 401 Unauthenticated

Request ID: HCCSULHKA7D6I7ZTWMWZURHB.0.0

WARN  [11:11:56]: Auth lost
INFO  [11:11:56]: >> POST https://idmsa.apple.com/appleauth/auth/signin: {"accountName":"XXXXXX@gmail.com","password":"***","rememberMe":true} 
DEBUG [11:11:57]: << POST https://idmsa.apple.com/appleauth/auth/signin: 409 {"authType"=>"hsa2"}
INFO  [11:11:57]: >> GET https://idmsa.apple.com/appleauth/auth: [undefined body] 
DEBUG [11:11:58]: << GET https://idmsa.apple.com/appleauth/auth: 200 {"trustedPhoneNumbers"=>[{"numberWithDialCode"=>"+86 ••• •••• ••58", "pushMode"=>"sms", "obfuscatedNumber"=>"••• •••• ••58", "id"=>1}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=XXXXXX@gmail.com&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=XXXXXX@gmail.com&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=XXXXXX@gmail.com&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "autoVerified"=>false, "showAutoVerificationUI"=>false, "managedAccount"=>false, "trustedPhoneNumber"=>{"numberWithDialCode"=>"+86 ••• •••• ••58", "pushMode"=>"sms", "obfuscatedNumber"=>"••• •••• ••58", "id"=>1}, "hsa2Account"=>true, "restrictedAccount"=>false, "supportsRecovery"=>true}

**Comment by janpio** [comment]
Thanks @zhxf2012. 

This looks like you never enter the pushed code and hit [Enter] - it never sends a request back to Apple to ask if this code you entered is correct.

What terminal application/console/command line are you using?

Another idea:
What happens if you do _not_ enter the number you got pushed, but enter `sms` and hit [Enter]?

**Comment by zhxf2012** [comment]
I have input . and enter. But the console hangs.      I use  terminal 2.9.4 (421.1.1) © 1991–2019 Apple Inc.  of MacOS 10.14.4 . Now I have change my password and get new trouble when try agin 

The login credentials for"MyAcout email" seem to be wrong
[21:55:37]: ▸ Do you want to re-enter your password? (y/n)
[21:55:37]: ▸ stty: stdin isn't a terminal
[21:55:37]: ▸ stty: stdin isn't a terminal

input y hangs too.

I also try Make sure you are on latest version
bundle exec irb
Spaceship::Tunes.login("youremail.com", "password")
4a. Accept on Mac or iOS device and enter code in console
4b. Type sms in the console and confirm phone number with 1 etc. Enter code from SMS

but get :
irb(main):001:0> Spaceship::Tunes.login("acount", "password")
NameError: uninitialized constant Spaceship .

Maybe I Should uninstall fastlane and reinstall .

**Comment by max-ott** [comment]
You'll need to load `spaceship` in `irb`:

`bundle exec irb`
`require "spaceship"`
...

With regards to `[21:55:37]: ▸ stty: stdin isn't a terminal` This looks like an issue of your terminal (config)

**Comment by janpio** [comment]
Something is strange. Have you rebooted your machine recently? Maybe try that to make sure nothing is just hanging.

Then try this:

>  What happens if you do not enter the number you got pushed, but enter sms and hit [Enter]?

**Comment by zhxf2012** [comment]
> You'll need to load `spaceship` in `irb`:
> 
> `bundle exec irb`
> `require "spaceship"`
> ...
> 
> With regards to `[21:55:37]: ▸ stty: stdin isn't a terminal` This looks like an issue of your terminal (config)

Thank you,I have try your solution  use spaceship to get sign in successful .Then fastlane.tools finished successfully 🎉 .

**Comment by zhxf2012** [comment]
> Something is strange. Have you rebooted your machine recently? Maybe try that to make sure nothing is just hanging.
> 
> Then try this:
> 
> > What happens if you do not enter the number you got pushed, but enter sms and hit [Enter]?

I had tried this two.The sms also hangs.
Finally I use  solution below and  get sign in successful .Then fastlane.tools finished successfully 🎉 .

thank you and max-ott

Make sure you are on latest version
bundle exec irb
Spaceship::Tunes.login("your@email.com", "password")
4a. Accept on Mac or iOS device and enter code in console
4b. Type sms in the console and confirm phone number with 1 etc. Enter code from SMS
Responses in console should look something like:

Two-factor Authentication (6 digits code) is enabled for account '•••••@•••••.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
sms
Please select a trusted phone number to send code to:
1. +49 ••••• •••••12
?  1

**Comment by janpio** [comment]
Ok, so you used `irb` to run `Spaceship::Tunes.login` manually, correct? 
Did you then input the pushed code (that requires "Allow" and shows the map) (4a) or did you use the code via SMS (4b)?

**Comment by zhxf2012** [comment]
yes,I input the code via sms (4b)


| |
兴发
|
|
邮箱：zhxf2005307@163.com
|

签名由 网易邮箱大师 定制

On 05/09/2019 22:23, Jan Piotrowski wrote:

Ok, so you used irb to run Spaceship::Tunes.login manually, correct?
Did you then input the pushed code (that requires "Allow" and shows the map) (4a) or did you use the code via SMS (4b)?

**Comment by bedhub** [comment]
Hi, sorry for the late response. We have solved our issue. The problem for us was that we have started fastlande as another process from a node script and we didn't forward the standard input from our node process to the fastlane process. It looked like we had entered the 2FA successfully but actually the code never reached fastlane. After forwarding stdio to fastlane we don't have problems anymore.
