### ISSUE TITLE
latest_testflight_build_number returns 1

### ISSUE THREAD

**Issue by victormihaita** [fastlane/fastlane#14527]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to retrieve the version number of the last version on testFlight always returns 1.

##### Command executed
`bundle exec fastlane run latest_testflight_build_number version: x.x.x`

<details>
  <pre> If I run the `Beta` build, is asking at some point to select a version number and this is crashing in CI (`You have to specify a new version number, as there are multiple to choose from`)  </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.119.0"
skip_docs

desc "Download all dependencies and setup the environment"
lane :dependencies do
  sync_code_signing(type: "appstore")
  cocoapods(try_repo_update_on_error: true)
  download_schema
end

desc "Build the project and run all tests"
lane :test do
  dependencies
  run_tests(scheme: "SCHEME")
end

desc "Build the project and upload the app to the TestFlight"
lane :beta do
  dependencies
  increment_build
  gym(scheme: "OUR_SCHEME", configuration: "Release")
  upload_to_testflight(skip_waiting_for_build_processing: true)
  refresh_dsyms
end

desc "Build the project and upload the app to the AppStore"
lane :release do
  dependencies
  increment_build
  gym(scheme: "OUR_SCHEME", configuration: "Release")
  upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  refresh_dsyms
end

desc "Refresh dSYMs in Crashlytics"
lane :refresh_dsyms do
  upload_symbols_to_crashlytics
end

desc "Increment build number"
lane :increment_build do
  increment_build_number(build_number: latest_testflight_build_number + 1)
end

desc "Increment version number"
lane :increment_version do |options|
  increment_version_number(bump_type: options[:type], version_number: options[:version_number])
end

desc “Download GraphQL schema”
lane :download_schema do
  sh("npm install -g apollo@1.9")
  sh("apollo schema:download ../Sources/API/Generated/schema.json --endpoint=API_ENDPOINT --header=\"x-api-key: KEY_HERE"")
  sh("touch ../Sources/API/Generated/API.swift")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("APP_IDENTIFIER")
apple_id("APP_ID")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.2        |
| unicode-display_width     | 1.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-04-05**
</details>

**Comment by EquiisTiago** [comment]
This started happening to me 2 days ago. Back then the appstoreconnect website was really slow. I assumed it could be that but it is still happening and the website is fine.

**Comment by victormihaita** [comment]
I think is an issue from App Store Connect. Probably it has nothing to do with fastlane. It's just annoying that the builds are failing every time on CI because of this.. (+ if I run it locally and specify the version, I get it uploaded to TestFlight, but the build number is 2...)

**Comment by Oisann** [comment]
We are having this problem too.
Think it is related to #14521 somehow. When calling the api urlmanually, we get the 410 Gone error.

**Comment by victormihaita** [comment]
> We are having this problem too.
> Think it is related to #14521 somehow. When calling the api url manually, we get the 410 Gone error.

You are right. It seems to be related to #14521 . In this case, I will close this issue. Cheers.
