### ISSUE TITLE
import_from_git with authentication specified?

### ISSUE THREAD

**Issue by CubicNitrous** [fastlane/fastlane#14534]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
  import_from_git
 No
 no

#### Question Description

I currently have the following code in our iOS apps fastfiles linked in using import_from_git. We bundle together some Fastlane functions in sequence that only ask for parameters that are needed from the developers (ex bundle identifier)

```
import_from_git(url: "git@githubenterprise.mycompany/myOrg/FastfileCommon.git", branch: 'master', path: 'FastfileCommon')
```

On our mac slave we have removed ssh keys and are switching to https, is there a way that I can pass credentials to the https path so that it can do the clone? Our github setup requires a token for https

**Comment by CubicNitrous** [comment]
@fastlane-bot im not sure my env would help in this situation, can someone answer the question perhaps?

**Comment by CubicNitrous** [comment]
@janpio can you shed some light?

**Comment by janpio** [comment]
Have a look at the code being executed from `import_from_git`: https://github.com/fastlane/fastlane/blob/0de811cec8bc50e266b2724d96a3a3852c845e6e/fastlane/lib/fastlane/fast_file.rb#L235-L287 This effectively just calls `git clone` (line 258)

**Comment by CubicNitrous** [comment]
@janpio i was using username:token instead of just token, my bad.

**Comment by janpio** [comment]
Can you share an example of what turned out to work for you? Just for future developer googling and landing here ;)

**Comment by CubicNitrous** [comment]
`import_from_git(url: "https://{ENV['GITHUB_TOKEN']}@yourgithubserver.com/yourOrg/yourSharedFastfileRepo.git", branch: 'someBranch', path: 'yourFile')
