### ISSUE TITLE
[Spaceship] Documentation - How to upload App Previews (trailers) to ITC.

### ISSUE THREAD

**Issue by xhairbait** [fastlane/fastlane#14535]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about?
Spaceship

Is this a question about documentation?
Yes

Is this a question about a third party plugin? (If so, please go to the plugin repository first)
No

#### Question Description

I'm looking for documentation on how to upload preview trailers to ITC. I've seen multiple bugs that have been fixed about uploading issues, but I don't see any documentation instructing how to generally upload trailers.

Is there documentation on how to perform the action of uploading trailers?
Is there documentation on setting the same trailer to another language using another languages trailer's URL? Attempting to utilize this for when trailers are exactly the same across multiple languages.

**Comment by janpio** [comment]
@max-ott, can you point to the correct file (or source code)?

**Comment by max-ott** [comment]
You might want to check out https://github.com/fastlane/fastlane/issues/9775 There is no documentation in there. Please feel free to create a pull request.

**Comment by xhairbait** [comment]
Should we close this issue and re-open #9775?

**Comment by max-ott** [comment]
I don’t think it makes sense to re-open the old issue. The trailer upload is working, it’s just missing the documentation. I currently don’t have time to do this. Please feel free to create a pull request with your suggestions.

**Comment by xhairbait** [comment]
Sorry, I'm not super familiar on how to do a pull request. I'll look into how to do that.

**Comment by janpio** [comment]
If it is just one file, you can pretty much do it all in the GitHub UI: https://help.github.com/en/articles/editing-files-in-another-users-repository

**Comment by xhairbait** [comment]
I made a pull request to the Spaceship README.md file.

Now that I think of it, I probably should've made the pull request on AppStoreConnect.md...

**Comment by danramteke** [comment]
@xhairbait Could you can post a link to your pull request? Would love to see the documentation for how to use spaceship. Thanks!

**Comment by xhairbait** [comment]
@danramteke Unfortunately I don't know how to use spaceship to upload App Previews (Trailers)...
My pull request was just adding a TODO. :\

**Comment by xhairbait** [comment]
@javibm 
I noticed you made fixes for uploading App Previews (Trailers) to ITC using spaceship in issue #10546.
Would you be able to add documentation on how to use spaceship to do that task?

**Comment by danramteke** [comment]
@xhairbait try adding this to your `Fastfile`
```
  lane :upload_iphone58_video do 
    fastlane_require 'spaceship'

    Spaceship.login
    Spaceship::Tunes.login()
    app_version = Spaceship::Tunes::Application.find(your_app_id).edit_version
    puts app_version.upload_trailer!(iphone58_video_path, 1, "en-US", "iphone58", "00:00")
end
```

i don't get any errors, but I don't see the videos in App Store Connect

**Comment by xhairbait** [comment]
So your code works just fine. I manually typed it into spaceship since I don't run through a Fastfile...

The reason why your upload didn't save is because you didn't call 

`app_version.save!`

I did it and it saved my upload just fine.

Also, I realized I need to install ffmpeg or else none of this process works. You'll run into the Video Stream error because 'ffmpeg' command doesn't exist.

**Comment by xhairbait** [comment]
Odd... it worked once... now when I do the same steps it doesn't work...

**Comment by xhairbait** [comment]
And now it worked. I think it just took a little bit to process.

**Comment by xhairbait** [comment]
Thanks for that code snippet. I can go ahead and cancel my pull request and then at least note how to upload to a single language. It saves about a minute or so from using the Web UI.


On a side note...
Does anyone know if you can create a deliver command that run spaceship code?

Ideally this is the more intuitive method for uploading things that way non-coder's can stick with one fastlane module for App Store related updates.

I'm going to look into maybe writing something that checks the folder structure created by deliver init for a folder called trailers that has the same folder structure as metadata.

**Comment by janpio** [comment]
@xhairbait That is exactly what deliver and all the other fastlane tools do - they prepare the data and then hand it over to _spaceship_ if it has to be uploaded to the App Store. (Best open a new issue about what you want to implement, I am sure we can guide you along.)

**Comment by xhairbait** [comment]
@janpio 
I think at least I'll keep this one open until I add documentation for the spaceship side of how upload_trailer!() works as an example for more people to understand. As well as the pitfalls why mine didn't work (missing installed ffmpeg command).

Otherwise, would you be able to point me into the direction of hooking things into deliver.

Also I don't really know Ruby... but I could probably (hopefully) figure it out.

**Comment by janpio** [comment]
Best figure out where in the process (output of a normal `deliver` execution) you want to put yours in, and then search the codebase for a string that is output there. That should give you a pointer where to start reading through the code (which should be pretty readable if you know any programming language - ruby is nice that way).
