### ISSUE TITLE
upload_to_testflight - Server error got 500

### ISSUE THREAD

**Issue by Hanstad** [fastlane/fastlane#14548]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After upgrading to fastlane 2.120.0 I get "Server error got 500" when uploading to testflight.

##### Command executed
upload_to_testflight(
      ipa: _iOSpath_to_ipa,
      wait_processing_interval: 100,
      team_name: ENV['TEAM_NAME'])

##### Complete output when running fastlane, including the stack trace and command used

I have omitted 5,520 chars of changelog that I cannot share. I know it is a long changelog, but it used to work with the old API in fastlane 2.119

<details>
  <pre>

[2019-04-10T08:53:22.317Z] [10:53:20]: [32m--------------------------------------------------------------------[0m
[2019-04-10T08:53:22.317Z] [10:53:20]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
[2019-04-10T08:53:22.317Z] [10:53:20]: [32m--------------------------------------------------------------------[0m
[2019-04-10T08:53:22.317Z] [10:53:20]: [32mSuccessfully uploaded the new binary to App Store Connect[0m
[2019-04-10T08:53:22.317Z] [10:53:20]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[2019-04-10T08:53:22.317Z] [10:53:21]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
[2019-04-10T08:55:13.941Z] [10:55:02]: Waiting for App Store Connect to finish processing the new build (1.1.0 - 65)
[2019-04-10T08:56:50.526Z] [10:56:43]: Waiting for App Store Connect to finish processing the new build (1.1.0 - 65)
[2019-04-10T08:58:27.126Z] [10:58:23]: Waiting for App Store Connect to finish processing the new build (1.1.0 - 65)
[2019-04-10T09:00:18.717Z] [11:00:04]: Waiting for App Store Connect to finish processing the new build (1.1.0 - 65)
[2019-04-10T09:01:55.268Z] [11:01:45]: Waiting for App Store Connect to finish processing the new build (1.1.0 - 65)
[2019-04-10T09:03:31.873Z] [11:03:26]: [32mSuccessfully finished processing the build 1.1.0 - 65[0m
[2019-04-10T09:03:31.873Z] +--------------------------+-----------+ 
[2019-04-10T09:03:31.873Z] |   xxxxxxxxxxx                            
[2019-04-10T09:03:31.873Z] +--------------------------+-----------+
[2019-04-10T09:03:31.873Z] | FL_CHANGELOG             | - xxxxxxxxxxxxxxx 
[2019-04-10T09:03:31.967Z] | ENVIRONMENT              | store              
[2019-04-10T09:03:31.967Z] | LANE_NAME                | ios publish_build
[2019-04-10T09:03:31.967Z] [11:03:28]: [31mCould not set changelog: Server error got 500[0m </pre>
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.3                                          |
| Ruby                        | 2.6.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.21.0                               |
| Installation Source         | /usr/local/bin/fastlane                          |
| Host                        | Mac OS X 10.14.3 (18D109)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10.1.app/Contents/Developer/ |
| Xcode Version               | 10.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US:en    | 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.2        |
| bundler                   | 2.0.1        |
| mime-types-data           | 3.2019.0331  |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
</details>

*generated on:* **2019-04-10**
</details>

**Comment by JoeAlamo** [comment]
Last time I checked, TestFlight's changelog limit is 3600 characters. It is possible you are running into this limit here? In the past I have had to create a method to truncate my release notes for TF.

**Comment by Hanstad** [comment]
But the previous version of fastlane took care of this. I believe the new version should do that as well, not that anyone should add so large changelog, but if/when we do it would be nice if it did not break anything.

**Comment by janpio** [comment]
Is there more output about the error it is getting? If not, could you please check `/tmp/spaceship*.log` for the requests being sent by pilot/spaceship and their responses? Maybe this will tell us more.

**Comment by ShurupuS** [comment]
@janpio Please check https://github.com/fastlane/fastlane/issues/14755 for detailed info regarding this issue

**Comment by ivanicspeter92** [comment]
I am facing the same error on one of our lanes of a project. Here's the last couple of lines from the spaceship logfile, I hope this helps. 

> 
> INFO  [12:42:01]: >> GET builds: [undefined body] 
> DEBUG [12:42:02]: << GET builds: 200 {"data"=>[{"type"=>"builds", "id"=>"7c516035-1a6a-4d4e-88e1-2d53a8618f8f", "attributes"=>{"version"=>"29", "uploadedDate"=>"2019-05-23T03:34:52-07:00", "expirationDate"=>"2019-08-21T03:34:52-07:00", "expired"=>false, "minOsVersion"=>"9.0", "iconAssetToken"=>{"templateUrl"=>"https://is2-ssl.mzstatic.com/image/thumb/Purple/v4/4c/6f/e7/4c6fe715-a8bf-1a86-9468-72ce02eee64a/Icon-60@2x.png.png/{w}x{h}bb.{f}", "width"=>120, "height"=>120}, "processingState"=>"VALID", "usesNonExemptEncryption"=>false, "qcState"=>"BETA_INTERNAL_TESTING"}, "relationships"=>{"preReleaseVersion"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/preReleaseVersion", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/preReleaseVersion"}}, "individualTesters"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/individualTesters", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/individualTesters"}}, "betaBuildMetrics"=>{"meta"=>{"paging"=>{"total"=>1, "limit"=>10}}, "data"=>[{"type"=>"betaBuildMetrics", "id"=>"7c516035-1a6a-4d4e-88e1-2d53a8618f8f"}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/betaBuildMetrics", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/betaBuildMetrics"}}, "betaGroups"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/betaGroups", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/betaGroups"}}, "betaBuildLocalizations"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/betaBuildLocalizations", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/betaBuildLocalizations"}}, "appEncryptionDeclaration"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/appEncryptionDeclaration", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/appEncryptionDeclaration"}}, "betaAppReviewSubmission"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/betaAppReviewSubmission", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/betaAppReviewSubmission"}}, "app"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/app", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/app"}}, "buildBetaDetail"=>{"data"=>{"type"=>"buildBetaDetails", "id"=>"7c516035-1a6a-4d4e-88e1-2d53a8618f8f"}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/buildBetaDetail", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/buildBetaDetail"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/7c516035-1a6a-4d4e-88e1-2d53a8618f8f"}}], "included"=>[{"type"=>"betaBuildMetrics", "id"=>"7c516035-1a6a-4d4e-88e1-2d53a8618f8f", "attributes"=>{"installCount"=>0, "crashCount"=>0, "inviteCount"=>10, "sevenDayTesterCount"=>0}, "relationships"=>{"build"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/build", "related"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/build"}}, "betaGroup"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/betaGroup", "related"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/betaGroup"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/7c516035-1a6a-4d4e-88e1-2d53a8618f8f"}}, {"type"=>"buildBetaDetails", "id"=>"7c516035-1a6a-4d4e-88e1-2d53a8618f8f", "attributes"=>{"autoNotifyEnabled"=>true, "didNotify"=>false, "internalBuildState"=>"IN_BETA_TESTING", "externalBuildState"=>"READY_FOR_BETA_SUBMISSION"}, "relationships"=>{"build"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/buildBetaDetails/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/relationships/build", "related"=>"https://appstoreconnect.apple.com/iris/v1/buildBetaDetails/7c516035-1a6a-4d4e-88e1-2d53a8618f8f/build"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/buildBetaDetails/7c516035-1a6a-4d4e-88e1-2d53a8618f8f"}}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds?include=betaBuildMetrics%2CbuildBetaDetail&filter%5Bexpired%5D=false&filter%5Bversion%5D=29&filter%5BpreReleaseVersion.version%5D=1.0&limit=10&sort=uploadedDate&filter%5BprocessingState%5D=PROCESSING%2CVALID&filter%5Bapp%5D=1457821587"}, "meta"=>{"paging"=>{"total"=>1, "limit"=>10}}}
> INFO  [12:42:02]: >> POST betaAppReviewSubmissions: {"data":{"type":"betaAppReviewSubmissions","relationships":{"build":{"data":{"type":"builds","id":"7c516035-1a6a-4d4e-88e1-2d53a8618f8f"}}}}} 
> DEBUG [12:42:03]: << POST betaAppReviewSubmissions: 500 {"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
