### ISSUE TITLE
[spaceship] `fetch_program_license_agreement_messages` is not working correctly

### ISSUE THREAD

**Issue by salmanasiddiqui** [fastlane/fastlane#14542]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Recently a method was added to `Spaceship` which should download the pending license agreements (#14159). The method is `fetch_program_license_agreement_messages`. This method is returning an empty list while on developer portal, I get a red alertbar with the message that the team agent needs to accept the updated apple agreement.

##### Command executed

```
bundle console
Spaceship::Portal.login(<username>, <password>)
Spaceship::Portal.client.team_id = <portal_team_id>
Spaceship::Portal.client.fetch_program_license_agreement_messages
```
Does this method only works if the user being used is account holder?

**Comment by salmanasiddiqui** [comment]
seems like the API being used by `fetch_program_license_agreement_messages` (olympus.itunes.apple.com/v1/contractMessages) doesn't use team_id. When I open this URL on browser, i get contractMessages sometimes, sometimes I dont. Not sure which team it uses, my user is part of 100+ teams. When I changed to a team having expired membership on developer.apple.com I was not getting any contractMessages, and then I started getting contractMessages later, but then I changed to a team having active membership and this API was still returning contractMessages. It seems unreliable and unclear to me. If anyone has more info on this API let me know.

I just wanted to know if a team has active membership or not, so I ended up writing the following function:
```
    def self.has_pending_agreements?(team_id)
      Spaceship::Portal.client.team_id = team_id
      Spaceship::Portal.client.team_information['status'] != 'active'
    end
```

If it makes sense, I can add this function to `PortalClient`.

**Comment by janpio** [comment]
@keehun, you wrote that method for spaceship. Do you have some insight here?

**Comment by keehun** [comment]
I know for a fact that the user doesn't have to be an account owner/holder. (This continues to work for me every day for warnings and my accounts are not owner/holder types.) I was under the impression that the red bar/error messages were caught elsewhere and these only caught the warnings.

**Comment by salmanasiddiqui** [comment]
@keehun warnings for which team are returned? warnings across all teams my user is part of?

**Comment by akkhilns** [comment]
`fetch_program_license_agreement_messages` is working based on the team id?

**Comment by CaptainJeff** [comment]
Has there been any updates on this?

I'm still getting an empty list when hitting `fetch_program_license_agreement_messages`

```
Spaceship::Portal.login(<username>, <password>)
Spaceship::Portal.client.team_id = <portal_team_id>
Spaceship::Portal.client.fetch_program_license_agreement_messages
```

**Comment by salmanasiddiqui** [comment]
@janpio I think this can be closed..
there has been a bit more detailed discussion on this issue [here](https://github.com/fastlane/fastlane/issues/14880)

**Comment by CaptainJeff** [comment]
@salmanasiddiqui and @janpio 

I don't think its ready to be closed

As that ticket doesn't work entirely. I have tried to duplicate the steps for several teams (one that does have the license agreement signed and three that don't) and all four return an empty list

Following these steps

```
>> Spaceship::Tunes.select_team
1) "Acme Crop" (123)
2) "Random Inc" (321)
2
=> "321"
Spaceship::Tunes.client.fetch_program_license_agreement_messages
=> []
```

**Comment by salmanasiddiqui** [comment]
I agree that this function doesn't work as expected. But at same time, I don't know what is expected of this function?
It seems that it only returns agreement msgs when an error/warning strip is visible on appstoreconnect for the team. When its only visible on portal then this function doesnt return those agreement msgs.

I was expecting it to return any kind of pending agreements. But I am sure it doesnt work that way.

By closing this I meant to take the whole discussion in one place.. Might be better if you post your above msg in other issue so the whole discussion is there.

link to other issue: https://github.com/fastlane/fastlane/issues/14880

**Comment by CaptainJeff** [comment]
Ahh understood @salmanasiddiqui 

I'm in agreement with you there

**Comment by CaptainJeff** [comment]
For anyone interested I just came up with this solution that seems to work. Note: I'm part of multiple teams

```
    client = Spaceship::Portal.login(@appleID, @applePassword)

    i = 0
    loop do
        i += 1

        begin
            Spaceship.select_team(team_id: client.teams[i]["teamId"])
            Spaceship::Portal.client.apps
        rescue StandardError => error
            puts error
            puts "Org Name: " + client.teams[i]["name"]
        end

        if client.teams[i + 1] == nil
            return
        end

    end

```

This will give a list of organizations that need to sign the agreement and output the error

**Comment by salmanasiddiqui** [comment]
the solution suggested by @CaptainJeff  can be improved by catching specific exception `Spaceship::ProgramLicenseAgreementUpdated`. But that won't work right now cause there seems to be a bug described [here](14973).

Closing this issue as the other duplicate [issue](14880) has more info on this.
