### ISSUE TITLE
latest_testflight_build_number

### ISSUE THREAD

**Issue by nanshanyi** [fastlane/fastlane#14540]
### Issue Description
latest_testflight_build_number
Use action (latest_testflight_build_number), I can't get the right build_number. It aways 1

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/bin/fastlane                                              |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(url: 'git@gitlab.corp.cootek.com:pgd_portfolio/sdk/ios/fastlane-for-release.git', branch: 'master')


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("ios.step.tracker.stepcounter.caloriecounter.pedometer") # The bundle identifier of your app

apple_id("muse@fekagame.com")
#apple_id("theo.chen@cootek.cn")

itc_team_id("119138503") # App Store Connect Team ID
team_id("NG76ZL6YRF") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.2        |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
| fastlane-plugin-pgyer     | 0.2.2        |
</details>

*generated on:* **2019-04-09**
</details>

**Comment by dennispost** [comment]
Will be addressed in #14521

**Comment by sourabhguptavc** [comment]
I am having the same issue

**Comment by invoodoo** [comment]
Same for me. Also tried to use app_store_build_number(version: app_version, live: false, initial_build_number: live_build) but it returns last live build not edit one.

**Comment by ggallotti** [comment]
Same issue

**Comment by ramnac** [comment]
@sourabhguptavc @invoodoo @ggallotti 

you can use my private lane which I posted here. Will solve your problem (for now)

**Comment by nanshanyi** [comment]
update to 2.120.0  fixed the issue

**Comment by tarbayev** [comment]
I'm still getting `Latest upload for version 1.0 is build: 1` on `fastlane 2.120.0`

I'm using it like this:
```
    latest_build_number = app_store_build_number(
      app_identifier: app_id,
      initial_build_number: 0,
      version: get_version_number,
      live: false
    )
```
