### ISSUE TITLE
Define app_identifier project wise

### ISSUE THREAD

**Issue by blackjid** [fastlane/fastlane#1454]
Is there any way to define the app_identifier from inside an action instead from the `AppFile` so that actions know about it??
 
I don't want to set the `app_identifier` on every action I call, but I don't want to use the AppFile neither.

Any suggestions?

**Comment by vpolouchkine** [comment]
Perhaps you can create an Appfile with

```ruby
app_identifier ENV["APP_IDENTIFIER"]
```

Fastfile:
```ruby
ENV["APP_IDENTIFIER"] = "com.foo.bar"
```

**Comment by blackjid** [comment]
Nice, I thought that the Appfile was evaluated first....

Is there any way to import the Appfile alongside the Fastfile using the `import` or `import_from_git` actions??

**Comment by KrauseFx** [comment]
You can't import the Appfile, it's always loaded from the local directory

**Comment by KrauseFx** [comment]
Can you describe more on what you're trying to do?

**Comment by blackjid** [comment]
of course...

I want to have a base configuration to import in all our projects...
https://github.com/platanus/fastlane-cordova

There I have a `Fastfile` file and a couple of actions...

All this is for cordova projects. The `app_identifier` is already defined in the `config.xml` for cordova so I don't want to duplicate it and set it again in the `Appfile`

One of the actions gets the id from the `config.xml` file from cordova and I use it as base to build other id. For example if I have this config 

```xml
# config.xml
<widget id="tools.fastlane.cordova">
....
</widget.\>
```

I will use that id as is for production but something like `tools.fastlane.cordova.staging` for testing...

The idea is not to define that id anywhere else...

Now what I'm doing is to use the action to get the id inside a global method ([here](https://github.com/platanus/fastlane-cordova/blob/master/fastlane/Fastfile#L46-L52)) that use to build the id to be used on all actions that need the `app_identifier` attribute.... (for example [here](https://github.com/platanus/fastlane-cordova/blob/master/fastlane/Fastfile#L89) and [here](https://github.com/platanus/fastlane-cordova/blob/master/fastlane/Fastfile#L73))

I would like just set some shared variable at the beginning of the `Fastfile` that every actions is aware of.

thanks!

**Comment by ohwutup** [comment]
Hey @blackjid! I marked this issue as a feature request as it seems like what is needed here is some enhancement to initialization to do what you're looking for. I think that creating templates for all new projects to be able to bootstrap them with `fastlane` is really awesome though! If you want to submit a PR that can handle this type of case, that would be awesome! I am going to close the issue for now, but please feel free to reopen if you decide to bite off the work to get a PR going! 👍 🐙
