### ISSUE TITLE
Snapshot screenshoting method to make device screenshot

### ISSUE THREAD

**Issue by viktorasl** [fastlane/fastlane#14555]
#### Motivation Behind Feature
I'd like to produce screenshots w/ notch (and other elements that are now excluded with current method)

#### Feature Description
Now screenshot is done by making a screenshot of first window, though it captures only the content without notch, extended margins (if layout does not support iPad Pro 3rd generation), etc.

https://github.com/fastlane/fastlane/blob/875e3482906044a4f9806dc869c8813d3a2e9a57/snapshot/lib/assets/SnapshotHelper.swift#L177
has to be replaced with
```swift
let screenshot = XCUIScreen.main.screenshot()
```

But I assume the change should be backwards compatible so this feature should be hidden under some option passed to `capture_ios_screenshots` lane.
I've already prepared a solution so if you'll approve I'll make PR.

#### Alternatives or Workarounds
Currently I have `SnapshotHelper.swift` modified locally.

**Comment by janpio** [comment]
That seems like a reasonable feature suggestion.

I am not really up to date in the iOS world, what are the "other elements" besides the notch that are currently not included in the screenshots?

**Comment by ppamorim** [comment]
Please make it optional by settings, I add the frame doing post processing with the frames provided by third party.

**Comment by janpio** [comment]
I don't think this was about adding the device frame (image of the actual device) automatically, correct @viktorasl?

**Comment by viktorasl** [comment]
Correct. Currently I've found two things that are missing: notch and extended layout offset which is included if app target is not configured to support it (i.e iPhone X and iPad Pro (12.9-inch) (3rd generation). Furthermore, if offset is excluded then screenshot size does not match actually required.

|**current method**|**XCUIScreen.main.screenshot()**|
|-|-|
|<img width="1307" alt="iPad Pro (12 9-inch) (3rd generation)-6 copy" src="https://user-images.githubusercontent.com/3721061/55934988-1e23cf80-5c3b-11e9-9f3b-245230a4df82.png">|<img width="1366" alt="iPad Pro (12 9-inch) (3rd generation)-6" src="https://user-images.githubusercontent.com/3721061/55935001-23811a00-5c3b-11e9-8d0a-873ada82b0ea.png">|
|2613 × 1959|2732 × 2048|

**Comment by janpio** [comment]
That size difference is massive, so yes we are definitely interested in a PR that gives a way to switch between these behaviors or just changes the behavior so we can compare. 

Then we can decide if this is indeed a new feature that should be behind a parameter or if this is "just" a bugfix and it was just broken until now.

**Comment by viktorasl** [comment]
Great! I'll make PR
