### ISSUE TITLE
IOS : Travis with Fastlane, double build?

### ISSUE THREAD

**Issue by PierreBrisorgueil** [fastlane/fastlane#14550]
### Question Checklist
- [ ] disable default xcodebuild from travis

### Question Subject
- double build with default xcodebuild from travis and xcodebuild from Fastlane scan

#### Question Description
Hello, I have not found anything about this, sorry if the subject has already been mentioned.

I would like to run my ios tests with Fastlane, however it seems that we are now obliged to specified in travis.yml : xcode_workspace, xcode_scheme, xcode_destination

as indicated in the documentation : 

> Travis CI runs xcodebuild and xcpretty by default to execute your tests. In order for xcodebuild to work, you need to tell it where to find your project or workspace ... 

So travis execute default xcodebuild , Then comes my fastlane scan that performs approximately the same thing.

my obejctif was therefore to delete the default build in order to gain 1 or 2 minutes during the build. I am wrong ? is there a solution to make this double build?

I tried to delete xcode_workspace, xcode_scheme, xcode_destination of my travis.yml, so as not to run the xcodebuild by default ... the build is broken, with this warning : 

> 0.01sWARNING: Using Objective-C testing without specifying a scheme and either a workspace or a project is deprecated.

**Comment by janpio** [comment]
If you don't need the default build, you should be able to just set e.g. `language: node_js`, `os: osx` and `osx_image: xcode9` to get an environment where `xcode_workspace` etc are not relevant because this default behavior is not present.

**Comment by PierreBrisorgueil** [comment]
Hum, yes but it requires to install brew etc ... And an inconsistency, in the .travis.yml file ..

Thank you for the time!

I will leave it in the case, lost 2min at every build. I find that it is an inconsistency on the Travis side not to allow us to disable this kind of default commands ...

**Comment by janpio** [comment]
Have you contacted Travis support? There might be a way, their documentation is not the easiest to understand and parse sometimes.

**Comment by PierreBrisorgueil** [comment]
Yep, [issue](https://github.com/travis-ci/travis-ci/issues/10416) was closed, and [post](https://travis-ci.community/t/ios-travis-with-fastlane-double-build/2968) on community have no answer yet.
