### ISSUE TITLE
[Pilot] TestFlight Upload issue 

### ISSUE THREAD

**Issue by shuppert** [fastlane/fastlane#14559]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This seems to be related to Apple's Transporter API changes.  In the last week or 2 I started getting errors in Pilot.  We have multiple apps and they're getting this error in the Pilot step:

[08:53:34][Step 1/1] [08:53:33]: -------------------
[08:53:34][Step 1/1] [08:53:33]: --- Step: pilot ---
[08:53:34][Step 1/1] [08:53:33]: -------------------
[08:53:34][Step 1/1] [08:53:34]: Login to App Store Connect (user@domain.com)
[08:53:36][Step 1/1] [08:53:36]: Login successful
[08:53:37][Step 1/1] [08:53:37]: Ready to upload new build to TestFlight (App: xxxxxxxxx)...
[08:53:38][Step 1/1] [08:53:38]: Going to upload updated app to App Store Connect
[08:53:38][Step 1/1] [08:53:38]: This might take a few minutes. Please don't interrupt the script.
[08:53:44][Step 1/1] [08:53:44]: [Transporter Error Output]: Resolver: Install error - org.bitbucket.b_c.jose4j Exception's name: org.osgi.framework.BundleException, Exception's message: Error occurred installing a bundle.
[08:53:44][Step 1/1] 
[08:53:44][Step 1/1] [08:53:44]: [iTMSTransporter] [2019-04-10 08:53:42 MDT] <main>  INFO: Transporter is searching for new software components.
[08:53:44][Step 1/1] 
[08:53:44][Step 1/1] [08:53:44]: [iTMSTransporter] [2019-04-10 08:53:43 MDT] <main>  INFO: Update check complete.
[08:53:44][Step 1/1] 
[08:53:44][Step 1/1] [08:53:44]: [iTMSTransporter] could not find the service with interface (com.apple.transporter.osgi.TransporterService)
[08:53:44][Step 1/1] 
[08:53:44][Step 1/1] [08:53:44]: [iTMSTransporter] [2019-04-10 08:53:44 MDT] <OSGi> ERROR: Resolver: Install error - org.bitbucket.b_c.jose4j Exception's name: org.osgi.framework.BundleException, Exception's message: Error occurred installing a bundle.
[08:53:44][Step 1/1] 
[08:53:44][Step 1/1] [08:53:44]: iTunes Transporter output above ^
[08:53:44][Step 1/1] [08:53:44]: Resolver: Install error - org.bitbucket.b_c.jose4j Exception's name: org.osgi.framework.BundleException, Exception's message: Error occurred installing a bundle.
[08:53:44][Step 1/1] The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

##### Command executed

      pilot(username: "user@domain.com",
          skip_waiting_for_build_processing: true)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

#default_platform :ios
app_name = "MyAppName"
ROOT = "/users/buildagent"
BuildTemp = "${ROOT}/SABUILDTEMP"
BuildOutput = "${ROOT}/SAClient_Builds"
APKRootFolder = "#{BuildTemp}/platforms/android/app/build/outputs/apk"

platform :ios do
  lane :debug do |options|
    Dir.chdir ".." do
      sh("cordova prepare ios")
    end

    # build your iOS app
    gym(
      scheme: "MyScheme",
      project: "platforms/ios/#{app_name}.xcodeproj",
      export_method: "development",
      export_options: {
        provisioningProfiles: {         
          "com.Company.AppName" => "match Development com.Company.AppName"
        }
      }
    )

    # Copy the IPA to the builds folder
    Dir.chdir ".." do
      if options[:version]
        sh("cp -f MyAppName.ipa #{BuildOutput}/MyAppName-debug-#{options[:version]}.ipa")
      else
        sh("cp -f MyAppName.ipa #{BuildOutput}/MyAppName-debug-#{Time.now.strftime('%F-%H-%M-%S')}.ipa")
      end
    end  

    # upload to Testflight
    #pilot(username: "user@domain.com",
    #    skip_waiting_for_build_processing: true)
  end

  lane :release do |options|
    # build the release variant

    Dir.chdir ".." do
      sh("cordova prepare ios")
    end

    # build your iOS app
    gym(
      scheme: "MyScheme",
      project: "platforms/ios/#{app_name}.xcodeproj",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {         
          "com.Company.MyAppName" => "match AppStore com.Company.MyAppName"
        }
      }
    )

    # Copy the IPA to the builds folder
    Dir.chdir ".." do
      if options[:version]
        sh("cp -f MyAppName.ipa #{BuildOutput}/MyAppName-release-#{options[:version]}.ipa")
      else
        sh("cp -f MyAppName.ipa #{BuildOutput}/MyAppName-release-#{Time.now.strftime('%F-%H-%M-%S')}.ipa")
      end
    end

    if options[:testFlightEnabled]
      # upload to Testflight
      pilot(username: "user@domain.com",
          skip_waiting_for_build_processing: true)  
    end
  end
end

platform :android do 
  lane :debug do |options|
    # build the debug variant

    sh("cordova build android --debug")

    # Copy the APK to the builds folder
    Dir.chdir ".." do
      if options[:version]
        sh("cp -f #{APKRootFolder}/debug/app-debug.apk #{BuildOutput}/MyAppName-debug-#{options[:version]}.apk")
      else
        sh("cp -f #{APKRootFolder}/debug/app-debug.apk #{BuildOutput}/MyAppName-debug-#{Time.now.strftime('%F-%H-%M-%S')}.apk")
      end      
    end
  end

  lane :release do |options|
    # build the release variant

    sh("cordova build android --release")    

    # Copy the APK to the builds folder
    Dir.chdir ".." do
      if options[:version]
        sh("cp -f #{APKRootFolder}/release/app-release.apk #{BuildOutput}/MyAppName-release-#{options[:version]}.apk")
      else
        sh("cp -f #{APKRootFolder}/release/app-release.apk #{BuildOutput}/MyAppName-release-#{Time.now.strftime('%F-%H-%M-%S')}.apk")
      end      
    end    
  end  
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-storage      | 1.16.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.3        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.8.1        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2019-04-10**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
@shuppert Heyyyy 👋 Do you happen to be behind some sort of corporate firewall by any chance?: 🤔

**Comment by shuppert** [comment]
@joshdholtz I am, but that's actually not the issue.  I finally stumbled onto the answer on StackOverflow [here](https://stackoverflow.com/questions/54681248/install-error-when-uploading-app-with-xcode-10-1/54708029#54708029).  My build machine has been upgraded across multiple versions of XCode and somehow the .itmstransporter folder wasn't upgrading.
