### ISSUE TITLE
fastlane with HockeyApp 400 error..

### ISSUE THREAD

**Issue by SeongminHeo** [fastlane/fastlane#14551]
### Question Checklist
fastlane ver 2.120.0
- [V] Updated fastlane to the latest version
- [V] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [V] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [V] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Hockey interlocking issue

#### Question Description
error description
[!] Error when trying to upload file(s) to HockeyApp: 400 - {"errors"=>{"credentials"=>["api token invalid"]}}
....
but, there is no problem with the token.
please help me...

Fastfile description
>
 	desc "Submit a new Beta Build to Hockey App"
 	 lane :beta do
  	  if !is_ci?
   	   changelog = prompt(text: "Please enter what's changed in one sentenence: ")
  	  end
    	increment_build_number
  	  gym(
  	    scheme: "AppUnify",
   	   export_method: "ad-hoc",
           ...
   	 )

   	 hockey(
    	  api_token:"1120fc9a9eec6aa33fc09cc90a07e19d09exxxxx",
    	  ipa: './AppUnify.ipa',
    	  dsym: './AppUnify.app.dSYM.zip',
     	  notify: "0",
     	  notes: changelog,
   	  )
 	  end

**Comment by lumaxis** [comment]
Hey @SeongminHeo! I work on HockeyApp.
Have you already tried reaching out to us at https://rink.hockeyapp.net/help ? If you send us a support request with your App ID, we can take a close look what's up. Also, please include a link to this issue so we'll be able to more easily recognize you.

**Comment by SeongminHeo** [comment]
> 이봐 @ 남미 ! 저는 HockeyApp에서 일합니다. 
> 이미 https://rink.hockeyapp.net/help 에서 문의 해 보셨습니까 ? 앱 ID와 함께 지원 요청을 보내 주시면 최대한 자세히 살펴볼 수 있습니다. 또한이 문제에 대한 링크를 포함시켜보다 쉽게 ​​귀하를 알아볼 수 있도록하십시오.

Thank you for your reply :)
