### ISSUE TITLE
Invalid Provisioning Profile

### ISSUE THREAD

**Issue by krismort** [fastlane/fastlane#1455]
Hi there 

I'm getting this sort of error when trying to upload a build via pilot.

[Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.tastybits.CameraCaptureKit [Payload/CameraCaptureKit.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

This is the section from the Fastlane file .

```ruby
lane :testflight do
    cert
    udid = sigh(app_identifier: "com.tastybits.CameraCaptureKit", force: true )
    puts "udid = " + udid
    update_project_provisioning(
        xcodeproj: "Unity-iPhone.xcodeproj",
        build_configuration_filter: "iPhone-target",
        build_configuration: "Release"
    )
    ENV["PROFILE_UUID"] = udid
    pilot(verbose:true)
  end
```

Please can anyone help with this ? What is the reason behind the error ? and what can be done in terms of fixing the fastlane setup?

**Comment by vpolouchkine** [comment]
It is recommended to use `match` to generate and maintain your certificates and provisioning profiles.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by bolom** [comment]
@vpolouchkine i have got the same error

1.84.0

[Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle tv.expertise.webinars [Payload/webinars.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."


`  desc "Build and upload a new build to Apple TestFlight"
  desc "This action will also do a build version bump and push it to git."
  desc "This will **not** send an email to all testers, it will only be uploaded to the new TestFlight."
  lane :beta do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    match( type: "appstore")
    git_pull
    version_number = get_version_number

    build_number = increment_build_number
    complete_version_number = version_string(version_number, build_number)
    gym(scheme: "webinars" ,
        use_legacy_build_api: true )


     # Increment build number to current date

    clear_derived_data

    pilot(skip_submission: true ,
         distribute_external: false,
         changelog: "Please remove the previous version. Check the issus with the label QA")


     # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

    # push to GitHub

    version = `/usr/libexec/plistbuddy -c Print:CFBundleShortVersionString '../Project/Project-Info.plist'`.strip
   build_number = `cd ..;agvtool what-version -terse`.strip

    git_commit(path: ".",
              message: "Deploying build #{build_number}.")

     add_git_tag(
        grouping: 'fastlane-builds',
        prefix: 'v',
        build_number: "v#{version_number}-b#{build_number}"
      )

    push_to_git_remote

   end`

**Comment by TKBurner** [comment]
Hi @bolom! Great to hear from you. Can you add cert and sigh to your lane? This will guarantee you pull down a valid code signing identity and have a provisioning profile bundled with your app. Let me know how it goes!

**Comment by bolom** [comment]
ok @TKBurner but i thoudh we should use match

> It is recommended to use match to generate and maintain your certificates and provisioning profiles.

**Comment by bolom** [comment]
https://github.com/fastlane/fastlane/tree/master/cert#installation

i am confuse i should use cert or match

**Comment by TKBurner** [comment]
@bolom Thanks for following up. If you'd like to stick to match that's great. Can you provide your matchfile or the output of match init?

Thanks!

**Comment by bolom** [comment]
@TKBurner i was able to resolve my issue.

**Comment by TKBurner** [comment]
@bolom Awesome! So glad to hear you got up and running. Have a great week!
