### ISSUE TITLE
Lost connection to the application on snapshot

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#14563]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Similar issue: #14096
Recreated to let the developers know that the issue has not been solved.

When running `snapshot`, I get this error:

```
All tests
Test Suite Screenshots_XXX.xctest started
Screenshots
✗ testScreenshots, Lost connection to the application (pid 8852).


Screenshots_XXX.Screenshots
testScreenshots, Lost connection to the application (pid 8852).
SnapshotHelper.swift:278


	 Executed 1 test, with 1 failure (0 unexpected) in 14.298 (14.313) seconds

2019-04-10 23:33:17.550 xcodebuild[8419:499782] [MT] IDETestOperationsObserverDebug: 23.783 elapsed -- Testing started completed.
2019-04-10 23:33:17.550 xcodebuild[8419:499782] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-04-10 23:33:17.550 xcodebuild[8419:499782] [MT] IDETestOperationsObserverDebug: 23.783 sec, +23.783 sec -- end

Failing tests:
Screenshots_testScreenshots:
Screenshots.testScreenshots()

Test session results and logs:
/Users/xxx/Library/Developer/Xcode/Logs/Test/Run-Screenshots_XXX-2019.04.10_23-30-26-+0100.xcresult
```

##### Command executed
```ruby
snapshot(
      workspace: "XXX.xcworkspace",
      scheme: ENV["SCREENSHOT_SCHEME"],
      derived_data_path: "/Users/xxx/Library/Developer/Xcode",
      output_simulator_logs: false,
      skip_open_summary: true,
      erase_simulator: false,
      clear_previous_screenshots: true,
      test_without_building: false,
      reinstall_app: true,
      concurrent_simulators: false,
      stop_after_first_error: false)
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# HIDDEN
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# HIDDEN

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| slack-notifier        | 2.3.2        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.8.2        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| terminal-table        | 1.8.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.2        |
| security              | 0.1.3        |
| google-cloud-env      | 1.0.5        |
| google-cloud-core     | 1.2.7        |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.15.0       |
| emoji_regex           | 0.1.1        |
| tty-cursor            | 0.6.0        |
| tty-spinner           | 0.9.0        |
| tty-screen            | 0.6.5        |
| faraday               | 0.15.4       |
| openssl               | 2.0.3        |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| io-console            | 0.4.6        |
| excon                 | 0.62.0       |
| CFPropertyList        | 3.0.0        |
| plist                 | 3.5.0        |
| faraday_middleware    | 0.12.2       |
| signet                | 0.11.0       |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.9       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20180417 |
| memoist               | 0.16.0       |
| googleauth            | 0.6.7        |
| fastimage             | 2.1.5        |
| bundler               | 1.16.6       |
| unicode-display_width | 1.4.1        |
| dotenv                | 2.6.0        |
| simctl                | 1.6.5        |
| addressable           | 2.5.2        |
| retriable             | 3.1.2        |
| mime-types            | 3.2.2        |
| mime-types-data       | 3.2018.0812  |
| multi_json            | 1.13.1       |
| jwt                   | 2.1.0        |
| os                    | 1.0.0        |
| psych                 | 2.2.2        |
| uber                  | 0.1.0        |
</details>

*generated on:* **2019-04-10**
</details>

**Comment by lewis-smith** [comment]
@ppamorim did you find a solution to this?
