### ISSUE TITLE
fastlane pilot add: Error 410 Gone / 405 Method Not Allowed

### ISSUE THREAD

**Issue by wuftymerguftyguff** [fastlane/fastlane#14562]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When trying to add testflight testers to an existing group getting "Error 410 Gone" 

##### Command executed

bundle exec fastlane pilot add --username red@acted.com -a com.red.acted -f Thomas -l DAVID -e red.acted@gmail.com -a com.red.acted -g ITC.apps.tf.labels.CustomGroup1

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [22:10:02]: Login to App Store Connect (redacted@gmail.com)
[22:10:05]: Login successful
[22:10:08]: Could not create tester red.acted@gmail.com
[22:10:08]: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/8989898989/apps/89898989898/testers. Reason:
<pre>    Gone</pre></p>
</body>
</html>

[!] Some operations failed: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/89898989898/apps/898989898989/testers. Reason:
<pre>    Gone</pre></p>
</body>
</html>
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.3                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-04-10**
</details></pre>
</details>

**Comment by rajivshah3** [comment]
#14564 might help here

**Comment by bart-powers** [comment]
Just checking in and didnt see anyon post any issues here so thought I'd pass along the ENV and error:
`fastlane pilot add some.one@gmail.com --groups "Public"`

<details><summary>Error</summary>
Could not create tester some.one@gmail.com
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/119043696/apps/1375547999/testers. Reason:
<pre>    Gone</pre></p>
</body>
</html>


[!] Some operations failed: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/119043696/apps/1375547999/testers. Reason:
<pre>    Gone</pre></p>
</body>
</html>
</details>

My FastFile contains a workaround which is also currently not working for me.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
require 'spaceship'

default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_USER"] = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
    ENV["APP_IDENTIFIER"] = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    ENV["APP_ID"] = CredentialsManager::AppfileConfig.try_fetch_value(:app_id)
  end

#Main functions
# fastlane deploy submit:false screenshots:true version:1.1

  desc "Builds IPA, generates screenshots, and uploads to app store \n fastlane deploy submit:false screenshots:true version:1.1"
  lane :deploy do |options|
    if options[:submit]
      # submit_review
      exit 0
    end
    if options[:screenshots]
      screenshots
    end
    # increment_build_number({
    #   build_number: latest_testflight_build_number(version:options[:version]) + 1
    # })
    build_ipa
    upload_ipa(options)
  end

  desc "Add new tester \n bundle exec fastlane add_tester email:email@invite.com first_name:John last_name:Smith"
  lane :add_tester do |options|
    Spaceship::Tunes.login(ENV["FASTLANE_USER"], ENV["FASTLANE_PASSWORD"])
    app = Spaceship::Tunes::Application.find(ENV["APP_IDENTIFIER"])
    current_user = Spaceship::Tunes::Members.find(ENV["FASTLANE_USER"])

    default_group = Spaceship::TestFlight::Group.default_external_group(app_id: app.apple_id)

    puts default_group

    response = Spaceship::TestFlight::Group.client.request(:post) do |req|
      req.url("/iris/v1/bulkBetaTesterAssignments")
      req.body = {
        "data" => {
          "type" => "bulkBetaTesterAssignments",
          "attributes" => {
            "betaTesters" => [
              {
                "id" => nil,
                "email" => options[:email],
                "firstName" => '',
                "lastName" => '',
                "assignmentResult" => nil,
                "errors" => []
              }
            ]
          },
          "relationships" => {
            "betaGroup" => {
              "data" => {
                "type" => "betaGroups",
                "id" => default_group
              }
            }
          }
        }
      }.to_json
      req.headers['Content-Type'] = 'application/json'
    end

    if (200...300).cover?(response.status)
      return
    end

    raise "Error got #{response.status}"

    UI.success("Successfully added tester: #{options[:email]} to app")
    # sh("bundle exec fastlane run pilot add #{options[:email]} first_name:'#{options[:first_name]}' last_name:'#{options[:last_name]}' app_identifier:'#{ENV["APP_IDENTIFIER"]}'")
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
      workspace: "app.xcworkspace",
      scheme: "app",
      erase_simulator: true,
      reinstall_app: true,
      skip_open_summary: true,
      clean: true,
      clear_previous_screenshots: true
    )
    # frame_screenshots(white: true)
  end

#Helpers
  desc "Generates a new ipa"
  lane :build_ipa do
    build_ios_app(
      workspace: "app.xcworkspace",
      configuration: "Release",
      scheme: "app",
      silent: true,
      clean: true,
      output_name: "app.ipa"
    )
  end

  desc "Uploads an ipa"
  lane :upload_ipa do |options|
    deliver(
      ipa: "app.ipa",
      app_version: options[:version],
      force: true,
      metadata_path: "./metadata",
      screenshots_path: "./screenshots",
      submit_for_review: false,
      automatic_release: false, #Do you want this?
      phased_release: false#Do you want this?
    )
  end

  desc "Submits app for review"
  lane :submit_review do
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("app.io") # The bundle identifier of your app
apple_id("redacted.com") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| mime-types-data           | 3.2019.0331  |
| psych                     | 2.1.0.1      |
</details>


*generated on:* **2019-04-17**
</details>

Thanks for all the help!!

**Comment by janpio** [comment]
Hey @wuftymerguftyguff @bart-powers, could you please check if this problem still exists with a current release of fastlane? We tried to fix a lot of these "error 410 gone" errors, and now need your feedback if this covered yours as well. Thanks!

**Comment by wuftymerguftyguff** [comment]
Hi,

I updated last night and still had the issue then, but I will double check to make sure I have 2.121.1, retest and let you know.

**Comment by wuftymerguftyguff** [comment]
Hi,

Still fails but error now different.

`[19:10:07]: Could not create tester red.acted@gmail.com
[19:10:07]: <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Method Not Allowed</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>

[!] Some operations failed: <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Method Not Allowed</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>
`

**Comment by janpio** [comment]
Great, and not great. Can you please use https://docs.fastlane.tools/actions/spaceship_logs/ to get some more information what request is failing this way?

**Comment by wuftymerguftyguff** [comment]
Hi,

This the info you need?
` $ bundle exec fastlane betausers
[✔] 🚀 
[20:38:44]: ------------------------------
[20:38:44]: --- Step: default_platform ---
[20:38:44]: ------------------------------
[20:38:44]: Driving the lane 'ios betausers' 🚀
[20:38:44]: ----------------------------
[20:38:44]: --- Step: spaceship_logs ---
[20:38:44]: ----------------------------
[20:38:44]: Storing '# Logfile created on 2019-04-24 20:29:41 +0100 by logger.rb/61378
INFO  [20:29:41]: >> GET providers/117135851/apps/952866509/testers?order=asc&search=red.acted%40gmail.com&sort=status: [undefined body] 
DEBUG [20:29:42]: << GET providers/117135851/apps/952866509/testers?order=asc&search=red.acted%40gmail.com&sort=status: 200 {"data"=>[], "error"=>nil}
INFO  [20:29:42]: >> POST providers/117135851/apps/952866509/testers: {"email":"red.acted@gmail.com","firstName":"Red","lastName":"Acted"} 
DEBUG [20:29:42]: << POST providers/117135851/apps/952866509/testers: 405 <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Met' in the clipboard 🎨

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | spaceship_logs   | 0           |
+------+------------------+-------------+`

**Comment by janpio** [comment]
Yes, that's perfect. Thanks, someone will have to look into that :/

**Comment by wuftymerguftyguff** [comment]
Any progress on this?

**Comment by janpio** [comment]
Did we miss a Pull Request that fixes this? Otherwise nobody has looked deeper into this yet, otherwise it would have been noted here.

**Comment by johisco** [comment]
Any updates ?

**Comment by wuftymerguftyguff** [comment]
Fastlane pilot add issue is now resolved

**Comment by brayanL** [comment]
That seems the error go back again: `Error 410 Gone / 405 Method Not Allowed`, Yesterday I tried to upload with circle ci and Fastlane throw the same error. That error missed for a few three months, but here is again :(. What in the world.

**Comment by janpio** [comment]
I'm pretty sure that is something else @brayanL - could you please create a new issue with all necessary ifnformation? Thanks.

**Comment by pravinarr** [comment]
Hi,
Using spaceship::ConnectAPI to add a build to a test group in testflight results in 410
```app = Spaceship::ConnectAPI::App.find("bundle_id")
    groups = app.get_beta_groups(filter: {name: "Internal Testing Group"})
    builds = app.get_builds()
    groups_to_push = [ groups.first.id ]
    app.add_beta_groups_to_build(
      build_id: builds.first.id,
      beta_group_ids: groups_to_push
    )```

```Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `add_beta_groups_to_build' for Spaceship::ConnectAPI::App

URL: https://api.github.com/search/issues?q=undefined%20method%20%60add_beta_groups_to_build%27%20for%20Spaceship%3A%3AConnectAPI%3A%3AApp+repo:fastlane/fastlane
➡️  [spaceship, pilot] Getting "410 gone"
    https://github.com/fastlane/fastlane/issues/14521 [closed] 177 💬
    6 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `add_beta_groups_to_build' for #<Spaceship::ConnectAPI::App:0x00007fe9754b1138>
  Fastfile:50:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'```

Someelse facing this issue ?
