### ISSUE TITLE
Add new devices in the snapshot example

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#14565]
The current snapshot example doesn't contain all the devices required by appstore connect e.g. iPhone 6.5" display.

https://github.com/fastlane/fastlane/blob/1d0155730dd3a788ce5db097dc8a89bcd120e3a3/snapshot/example/fastlane/Fastfile#L5

**Comment by tyten** [comment]
`iPhone Xs Max` should get you what you need.

**Comment by Kjuly** [comment]
`iPhone Xs Max`, lowercase `s` here.

**Comment by gersonmdesouza** [comment]
I added `iPhone Xs Max` to my snapfile, but it take screenshots with 1241px width, instead of 1242px. Any solution for this error?

**Comment by Kjuly** [comment]
@gersonmdesouza my 9 screenshots of iPhone Xs Max also got 1241px width as well, only one is 1242px. Seems a bug, I just resize those correctly manually, so they can be used w/ `frameit`.
