### ISSUE TITLE
One keychain PASSWORD environment variable to rule them all

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#14561]
#### Motivation Behind Feature

```
$ git grep _PASSWORD\" | grep KEYCHAIN  | sed -e 's/.*"\(.*PASSWORD\)".*/\1/g' | sort -u
CERT_KEYCHAIN_PASSWORD
FL_IMPORT_CERT_KEYCHAIN_PASSWORD
FL_UNLOCK_KEYCHAIN_PASSWORD
KEYCHAIN_PASSWORD
MATCH_KEYCHAIN_PASSWORD
```

Why?

Is there a real need?

If yes, could we also add a common environment variable for all those elements?
If no, could we deprecate everything and migrate everything to a common environment variable?

#### Feature Description

A single environment variable (name to agree upon, but maybe FASTLANE_KEYCHAIN_PASSWORD) to replace / complement all those environment variables.

One issue could be if users already use this variable for something else. This is always a risk when defining new env vars anyway.
#### Alternatives or Workarounds

We pass a single environment entry to fastlane and map it to the various environment variables in the Fastfile...

**Comment by janpio** [comment]
Probably part of the reason: https://github.com/fastlane/fastlane/issues/14255
