### ISSUE TITLE
[supply] Update to Google Play Developer API v3 (v2 end of life Dec 2019)

### ISSUE THREAD

**Issue by sschendel** [fastlane/fastlane#14573]
Google Play Developer Developer Publishing API v2 (currently used by supply) will end of life Dec 2019.

https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by brenwell** [comment]
https://github.com/fastlane/fastlane/blob/a8a602e8ab70fa86b70167965e85d44b49c77cd3/supply/lib/supply/client.rb#L2

Spent a few minutes running through my server code this morning trying to find references to `v2` pleased its only here in the `supply` lib. 

Thanks for the awesome lib *Team Fastlane!*

**Comment by janpio** [comment]
Ruby client is available for v3: https://developers.google.com/api-client-library/ruby/apis/androidpublisher/v3

A diff of https://developers.google.com/apis-explorer/#p/androidpublisher/v2/ vs https://developers.google.com/apis-explorer/#p/androidpublisher/v3/ shows that some methods seem to be gone:

```
androidpublisher.edits.apklistings.delete	Deletes the APK-specific localized listing for a specified APK and language code.
androidpublisher.edits.apklistings.deleteall	Deletes all the APK-specific localized listings for a specified APK.
androidpublisher.edits.apklistings.get	Fetches the APK-specific localized listing for a specified APK and language code.
androidpublisher.edits.apklistings.list	Lists all the APK-specific localized listings for a specified APK.
androidpublisher.edits.apklistings.patch	Updates or creates the APK-specific localized listing for a specified APK and language code. This method supports patch semantics.
androidpublisher.edits.apklistings.update	Updates or creates the APK-specific localized listing for a specified APK and language code.
```

We will have to look into if our code uses any of those.

**Comment by janpio** [comment]
Here is another blog post from Google that highlights some of the changes in the API: https://android-developers.googleblog.com/2018/06/automating-your-app-releases-with.html

---

API docs v2: https://developers.google.com/android-publisher/archive/v2/
API docs v3: https://developers.google.com/android-publisher/api-ref/

Comparing this gives a more positive outlook: 

- `apklisting` seems to have been the place for release notes, which are now part of the `track`.
- there is a new `bundle` endpoint collection

So stuff we had still seems to be there in one way or another.

**Comment by lidorDF** [comment]
> Google Play Developer Developer Publishing API v2 (currently used by supply) will end of life Dec 2019.
> 
> https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

Any estimations regarding this issue?

**Comment by janpio** [comment]
What are you asking for @lidorDF?

It will be a problem, we created an issue about it, now someone can do the work and fix it.

**Comment by gwynjudd** [comment]
This doesn't appear to be resolved, a quick search shows that supply is still using the v2 API

**Comment by iagorm** [comment]
First of all, great work Fastlane team, the product it's fantastic, now, what is the release of the new version that uses V3 of Google Play Developer API as we will have until December 1 of 2019 to finish it

**Comment by BrianJVarley** [comment]
> This doesn't appear to be resolved, a quick search shows that supply is still using the v2 API

Also following this thread for update

**Comment by alexgarret** [comment]
Hi Fastlane team,

I am also following this thread, to be notified when the update supporting **Google API V3** will be ready.
Looking forward to update Fastlane  🚀

**Comment by matthewkrueger** [comment]
The Play Store started showing a warning recently about this issue

> We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date.


I imagine there are many people who scratched their heads for a minute to figure out what was using the Google Play Developer API, only to realize it's fastlane. I'm just commenting here to help others save time tracking down what's going on. Thanks fastlane team!

**Comment by janpio** [comment]
Thanks for the update @matthewkrueger, and thanks to Google Play Store actually being so communicative on this.

**Comment by scorpion35** [comment]
Started some work. Got the download (`supply init`) part down. Any contributions are more than welcome!

Branch: https://github.com/scorpion35/fastlane/tree/androidpublisherv3

Tracking doc: https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/androidpublisherv3_tracking.md

Next: Migrate `supply run` stuff.

**Comment by ThomasGHenry** [comment]
Following. Thank, all!

**Comment by janpio** [comment]
Possibly relevant context for you @scorpion35 on how a tool doing similar things solved this: https://github.com/microsoft/google-play-vsts-extension/issues/129

**Comment by scorpion35** [comment]
Thanks, @janpio! Didn't know there's competition 😁 

Think I got halfway through `supply run` stuff. Updated the tracking doc with all changes so far. Can you take a look when you get a min, please? Would like early feedback if possible :) Added comments on each commit!

Everything above [uploader.rb#L36*](https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/lib/supply/uploader.rb#L36) is working. Let me know if you have any questions!

*except, bundles stuff. Getting some test bundles to test tomorrow!

**Comment by scorpion35** [comment]
Hit a road block. Helpppp :) 
https://github.com/fastlane/fastlane/issues/15222

**Comment by SimonErich** [comment]
Sorry guys, just to make sure:
There is work being done on upgrading the internal workings of fastlane to go with v3 right now, right?
Or is there a solution already available, that we can use to get fastlane working, without having to relace it with another tool?

**Comment by janpio** [comment]
Yes, there is work going on, in this case by contributor @scorpion35. But there will also be a directed effort by the fastlane team to get this fixed before EOL in Dec 2019 if need be.

**Comment by joshdholtz** [comment]
@scorpion35 Hey! Do you mind creating a draft PR for this with the work you have currently done? I would love to contribute to this with you so that we can get this out the door? 😊

**Comment by scorpion35** [comment]
@joshdholtz That is awesome! :) Created a PR here - https://github.com/fastlane/fastlane/pull/15269

We are blessed with a baby boy on Aug 31st, bit busy with him now. He's winning so far haha. I wouldn't be able to come online for a month or so, hope you understand!

**Comment by joshdholtz** [comment]
@scorpion35 No problem at all and congrats!! 🎊🎉👶 I really appreciate all the work you've done on this so far 😊 Enjoy fatherhood!

**Comment by Putin12345** [comment]
> Ruby client is available for v3: https://developers.google.com/api-client-library/ruby/apis/androidpublisher/v3
> Code for that at the expected place: https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis/androidpublisher_v3
> 
> A diff of https://developers.google.com/apis-explorer/#p/androidpublisher/v2/ vs https://developers.google.com/apis-explorer/#p/androidpublisher/v3/ shows that some methods seem to be gone:
> 
> ```
> androidpublisher.edits.apklistings.delete	Deletes the APK-specific localized listing for a specified APK and language code.
> androidpublisher.edits.apklistings.deleteall	Deletes all the APK-specific localized listings for a specified APK.
> androidpublisher.edits.apklistings.get	Fetches the APK-specific localized listing for a specified APK and language code.
> androidpublisher.edits.apklistings.list	Lists all the APK-specific localized listings for a specified APK.
> androidpublisher.edits.apklistings.patch	Updates or creates the APK-specific localized listing for a specified APK and language code. This method supports patch semantics.
> androidpublisher.edits.apklistings.update	Updates or creates the APK-specific localized listing for a specified APK and language code.
> ```
> 
> We will have to look into if our code uses any of those.
> 
> Quick look through a diff of https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis/androidpublisher_v2 vs. https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis/androidpublisher_v3:
> 
> * `classes.rb`:
>   
>   * `ApkListing` and `ListApkListingsResponse` are indeed gone
>   * some renaming
>   * new `CountryTargeting` and `LocalizedText`
>   * `SubscriptionPurchase` has new accessor `auto_resume_time_millis`
>   * `Track` has several new accessors
> * `representations.rb`
>   
>   * similar to `classes.rb`
> * `service.rb`
>   
>   * `delete_apk_listing`, `delete_all_apk_listings`, `get_apk_listing`, `list_apk_listings`, `patch_apk_listing`, `update_apk_listing` are gone
>   * many other methods are (slightly) renamed
> 
> Unfortunately we are using some of these methods and classes that seem to be gone:
> https://github.com/fastlane/fastlane/blob/a8a602e8ab70fa86b70167965e85d44b49c77cd3/supply/lib/supply/client.rb#L215
> 
> 
> https://github.com/fastlane/fastlane/blob/a8a602e8ab70fa86b70167965e85d44b49c77cd3
D

![KmcLQ1g3N3Q](https://user-images.githubusercontent.com/37267817/64320671-79829f80-cfd8-11e9-9709-7143a7009737.jpg)

uplicate of /supply/lib/supply/client.rb#L344
> 
> So this definitely will not be a drop in replacement.

**Comment by Putin12345** [comment]
I

**Comment by puneetsdsharma65** [comment]
Hi Fastlane team,

I am also following this thread, to be notified when the update supporting Google API V3 will be ready.
Looking forward to update Fastlane
Thanks

**Comment by claudioviola** [comment]
Hi great team
I follow this post to have notification about the supporting of Google API V3.
Thanks

**Comment by iamareebjamal** [comment]
For future reference, there is a subscribe button on the right-hand side of GitHub issues, using which you can subscribe to the issues without commenting so that other people who have subscribed don't get notification thinking there's some progress from maintainers and the conversation remains on topic. :+1:

**Comment by scorpion35** [comment]
Hey Fastlane team! How's it going? 

Just came back from my PTO, and moving to a different team. No longer have access to AppStore Connect. Will leave the rest in your capable hands :) Thanks again for your awesome support. It was a pleasure! 

I am still around, let me know if you have any questions about the PR!

**Comment by SimonErich** [comment]
Thanks scorpion for your work.
Sorry to be annoying, but I have to make the change in the near future.
Will there be support in the next 1-2 months or should we change to a different deployment tool?
Or has somebody found a working workaround to use v3?

**Comment by scorpion35** [comment]
Hey 👋 I was using the changes I made for a couple of months already. We needed to find version details that has AAB files. Just point to the branch I made in your Gemfile like this,

```ruby
gem 'fastlane', :require => ['spaceship', 'supply'], :git => 'https://github.com/scorpion35/fastlane.git', :branch => 'androidpublisherv3'
```

Please note there is still some work to be done. You can find the work completed here - https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/androidpublisherv3_tracking.md. I think joshdholtz is working on wrapping it up!

**Comment by Panajev** [comment]
Sorry for being annoying, but is this on Fastlane's roadmap?

**Comment by panpanini** [comment]
@Panajev Like @janpio has already said, this is on the roadmap for Fastlane to be fixed before EOL if need be.

https://github.com/fastlane/fastlane/issues/14573#issuecomment-527417806

**Comment by andrewsdv** [comment]
@panpanini What do you mean by "EOL"??

Fastlane users expect it to be done by the end of the year and even earlier, to have time for updating the projects,making sure update is working fine. Otherwise it doesn't make sense.

**Comment by mieliespoor** [comment]
EoL is 1 December 2019. Today is 23 October which leaves less than 6 weeks. This should've been fixed and ready months ago! Just being on the roadmap is not a good enough answer at this point.

**Comment by jschmid** [comment]
Dear Fastlane contributors,

Thank you very much for working on Fastlane, either on your own time or as a Google employee.

I am sorry that you have to endure people **demanding** an open source project to be fixed, without ever providing any help to fix the problem they have.

Keep up the good work. ❤💪

**Comment by bnxio** [comment]
Fastlane users shouldn't expect anything. It's being worked on, if you're that desperate then do the work and create a PR!

**Comment by Enrico204** [comment]
Correct me if I'm wrong @mieliespoor @andrewsdv , you're not paying for support, right? So, what gives you the right to say how things should be done? Fastlane is a free/open source project. Instead of write critics and awful messages, you should thanks all fastlane devs for this amazing product.

@ fastlane devs: thanks for your work! :-) Unfortunately I can't help you with ruby, but if there is anything that we can do, we're here to support you :-)

**Comment by andrewsdv** [comment]
Agree with what you're saying, unfortunately. :-) At the same time it sounds strange to me that such an important request of such a great product is being postponed till deadline.  I'm thankful to Fastlane team, nevertheless. Thank you, without any doubt.

**Comment by kassim** [comment]
I guess its more along the lines of "Google owns Fastlane, Google gets huge amounts of money from dev contributions to Android, devs have a right to demand improvement on the tool" train of thought. There will of course be an argument of whether things should be demanded and how driven by the "open source community" something is.

In any case, we're all devs which means we probably know that information of needs from other sources (users, other departments in your organisation, etc) is valuable but you feel much better about your job if it doesn't come with a negative tone. 


Anyways you guys are doing a great job with Fastlane. Looking forward to API v3 integration so I can use it for Internal App Sharing.

**Comment by wman1980** [comment]
Hi,

sorry if I repeat other commenters here, but is this work in progress and will be fixed until EOD?

Thanks for some infos ...

**Comment by Enrico204** [comment]
> Hi,
> 
> sorry if I repeat other commenters here, but is this work in progress and will be fixed until EOD?
> 
> Thanks for some infos ...

I think that you want to read this (previous) comment: https://github.com/fastlane/fastlane/issues/14573#issuecomment-527417806

**Comment by scorpion35** [comment]
Hey all 👋 

Also read this comment: https://github.com/fastlane/fastlane/issues/14573#issuecomment-536022612

**Work done so far by me:** https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/androidpublisherv3_tracking.md

**Bonus feature:** This PR downloads full size screenshots from Google Play! (Part 2.1: Downloading full size screenshots, https://tinyurl.com/yxoqg9nn)

**How to use my branch:** https://github.com/fastlane/fastlane/issues/14573#issuecomment-540133148

Would love to help out wrap it up, but I no longer have access to Google Play console (I am on a different team now that doesn't deal with submissions). Please be patient folks. joshdholtz is working on wrapping it up I think!

**Comment by joshdholtz** [comment]
Heyyy, I'm currently working off of @scorpion35 branch. He laid out some great ground work for this 💪  The change from Android Publisher V2 is Android Publisher V3 is a pretty big change. It is for the better as it will allow `supply` to do a lot more things but it's not as straight forward as we'd like. There is a lot of testing and verifying that needs to be done in order to make sure that all current setups that use `supply` work 100% with the upgrade to Android Publisher V3 so that there is absolutely no migration that needs to happen for any _fastlane_ users.

I'm getting close to having this done but there are quite a bit of issues and changes to other _fastlane_ tools that also demand attention at the same time. I appreciate everyone's patience 😊 ❤️ I'm planning on having the PR out and ready for testing next week.

**Comment by joshdholtz** [comment]
Hello, again! I wanted to give a little bit more information and the in-and-outs and status of this changes while my 🧠 is warming up with a cup of ☕ this morning 😊

## Task Status

### Working/Fixed
- Release APK
  - With and without rollout
  - With uploading main and patch OBB
  - With referencing existing main and patch OBB
- Release bundle (AAB)
  - With and without rollout
- Update rollout of track
- Promote
  - Move release from one track to another
  - Also can update rollout

### Untested/Working On
- Change log
- Images
- Screenshots
- Metadata
- Updating unit tests

---- 

## Why is this change taking so long?
The update from `Google::Apis::AndroidpublisherV2` to `Google::Apis::AndroidpublisherV3` is not as simple of a replacement as just updating a gem/module (even though some updates have been in the past 😇). V2 to V3 had a name change to almost everything service method that `supply` uses and it also included a different data model change to tracks, releases, and version codes (which are pretty much the heart of `supply`). What this meant was that pretty much nothing ran when changing to the new module 🙃

The replacement process had to start at our lowest level of services and slowly work its way up the higher functional. Some of these new additions included explicitly creating tracks that didn't exist yet (things that we didn't need to do in V2) and manually creating releases (which wasn't as complicated but still a change). Rollout and promoting tracks also took a pretty big chunk of time since the APIs and logic behind these were almost a 100% change. Releases in a track can also now be custom named meaning they are no longer the "version name" which also forced an internal change of things are looked up.

The last big change was that tracks can have multiple releases which can have multiple versions. What this meant was that we could always say just "promote beta to production". Beta might have multiple version codes in it so we had to add a new optional configuration into `supply` called `version_code` which can be used to specify which release you would like to promote up from a track.

This isn't even all of the changes from `Google::Apis::AndroidpublisherV2` to `Google::Apis::AndroidpublisherV3` that had to happen but just the ones that come to mind 😊 But all of these changes had to be backwards compatible with the existing `supply` interface and docs so that none our users existing setups broke.

Along with all of this, there were also the yearly Xcode and iOS updates that required new support from _fastlane_ and its other tools along with handling other changes/fixes that our users reported 😇 We always true to do things as quick as we can for our users so you are all the reason we make _fastlane_ ❤️ Its always hard balancing what to give our attention to and sadly this fix kept getting interrupted.

I can't thank @scorpion35 enough for starting the PR (and congrats on fatherhood!). The ground work that @scorpion35 laid out was amazing. Finishing up the PR with the features that still need fixing, making sure its backwards compatible, fixing the unit tests, and updating documentation was still however a pretty big task **but its my highest priority** right now 💪

I could have definitely provided more transparency about these updates to my sincerest apology to the community for not providing that 😔 _fastlane_ is my passion and my life so I'm taking this as a lesson learned and going to grow from it 📈 

Can't wait to get these changes out to everyone who needs them. I will post back next week the PR is ready for some early testing (with instructions provided on how to do that). I appreciate everyone's patience ❤️ 

Now its time to get back to development now that I'm warmed up 😏🚀

**Comment by mieliespoor** [comment]
Thank you for the comprehensive feedback and status update. Much appreciated!

**Comment by Putin12345** [comment]
Суббота, 26 октября 2019, 17:33 +05:00 от Josh Holtz <notifications@github.com>:
>Hello, again! I wanted to give a little bit more information and the in-and-outs and status of this changes while my 🧠 is warming up with a cup of ☕ this morning 😊
>Task Status
>Working/Fixed
>*  Release APK
>*  With and without rollout
>*  With uploading main and patch OBB
>*  With referencing existing main and patch OBB
>*  Release bundle (AAB)
>*  With and without rollout
>*  Update rollout of track
>*  Promote
>*  Move release from one track to another
>*  Also can update rollout
>Untested/Working On
>*  Change log
>*  Images
>*  Screenshots
>*  Metadata
>*  Updating unit tests
>----------------------------------------------------------------------
>Why is this change taking so long?
>The update from Google::Apis::AndroidpublisherV2 to Google::Apis::AndroidpublisherV3 is not as simple of a replacement as just updating a gem/module (even though some updates have been in the past 😇). V2 to V3 had a name change to almost everything service method that supply uses and it also included a different data model change to tracks, releases, and version codes (which are pretty much the heart of supply). What this meant was that pretty much nothing ran when changing to the new module 🙃
>The replacement process had to start at our lowest level of services and slowly work its way up the higher functional. Some of these new additions included explicitly creating tracks that didn't exist yet (things that we didn't need to do in V2) and manually creating releases (which wasn't as complicated but still a change). Rollout and promoting tracks also took a pretty big chunk of time since the APIs and logic behind these were almost a 100% change. Releases in a track can also now be custom named meaning they are no longer the "version name" which also forced an internal change of things are looked up.
>The last big change was that tracks can have multiple releases which can have multiple versions. What this meant was that we could always say just "promote beta to production". Beta might have multiple version codes in it so we had to add a new optional configuration into supply called version_code which can be used to specify which release you would like to promote up from a track.
>This isn't even all of the changes from Google::Apis::AndroidpublisherV2 to Google::Apis::AndroidpublisherV3 that had to happen but just the ones that come to mind 😊 But all of these changes had to be backwards compatible with the existing supply interface and docs so that none our users existing setups broke.
>Along with all of this, there were also the yearly Xcode and iOS updates that required new support from  fastlane and its other tools along with handling other changes/fixes that our users reported 😇 We always true to do things as quick as we can for our users so you are all the reason we make  fastlane ❤️ Its always hard balancing what to give our attention to and sadly this fix kept getting interrupted.
>I can't thank  @scorpion35 enough for starting the PR (and congrats on fatherhood!). The ground work that  @scorpion35 laid out was amazing. Finishing up the PR with the features that still need fixing, making sure its backwards compatible, fixing the unit tests, and updating documentation was still however a pretty big task  but its my highest priority right now 💪
>I could have definitely provided more transparency about these updates to my sincerest apology to the community for not providing that 😔  fastlane is my passion and my life so I'm taking this as a lesson learned and going to grow from it 📈
>Can't wait to get these changes out to everyone who needs them. I will post back next week the PR is ready for some early testing (with instructions provided on how to do that). I appreciate everyone's patience ❤️
>Now its time to get back to development now that I'm warmed up 😏🚀
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

Алексей Путенихин

**Comment by joshdholtz** [comment]
Hello, everyone 👋

I _thhiinnnkkkk_ PR #15269 is ready for some early testers if anybody wants to give `AndroidpublisherV3` a shot 🙃 All the functionality _should_ be working but I"m sure there are some edge cases that may have been missed 😇 

I have to get unit tests all fixed up yet but hopefully that's the easy part 🙏 If anybody has any issues when testing this out, please post them in the PR for me to see 👌 

### How to use this PR
Updated your `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`
```
gem 'fastlane', :git => 'https://github.com/scorpion35/fastlane.git', :branch => 'androidpublisherv3'
```

**Comment by joshdholtz** [comment]
Hello!

Another update for you all today 😊 PR #15269 is pretty much code complete and all functionality has been tested and _seems_ like it should be zero work for most people. There are some new options and some deprecated options but nothing that will be a breaking change.

I'm doing one more final pairing session with @snatchev today to code review and integration test. After this it should be pretty much 💯 to release.

The tests in `supply` have always been lacking so there aren't _a ton_ of tests to fix for this but *we are going to improve the test coverage*. It may or may not be in this PR but there will be improved test coverage coming 💪 

This PR will probably be good to release on Friday but will probably wait until next Monday or Tuesday so that nothing could possibly break over the weekend 😇 

Thanks again for the patience ❤️

**Comment by joshdholtz** [comment]
Alright, _fastlane_ fam! PR #15269 is ready 💪 All the things in _supply_ work, all the actions that also use _supply_ have been tested and fixed if needed, tests pass, and migration doc has been added explaining what new, what changed, and what is deprecated. This should not be a breaking change for majority of users 🤞 

I'm not expecting any major issues with most users upgrading to this but I'm sure things will come up as software is software 🙃 I'm going to merge this tomorrow but will releasing this on Monday under version `2.135.0`. I'll be paying **super** close attention to issues the whole week 😝 

🙏 Please mention me in the issue if you see anything
😱 If its super bad you can tweet me a link to the GitHub issue at [@joshdholtz](https://twitter.com/joshdholtz) but don't abuse 😇

And a huge thanks to @scorpion35 for getting this PR started and @snatchev for pairing and code reviewing with me ❤️

**Comment by markwongsoontorn** [comment]
Thanks guys, totally understand that this requires more testing on edge cases to get it right, patience is the key.
Keep up the good work fastlane !

**Comment by wman1980** [comment]
@joshdholtz awesome and its very appreciated. Looking forward for the release and have a nice and relaxed weekend until next week ;)

**Comment by joshdholtz** [comment]
Last comment! This migration has now been released in `2.135.0` 😊 Please create any new issues and mentioned me in them if you have any issues 🙏  Thanks again for all the patience! ❤️

**Comment by Saifullah6** [comment]
> 
> 
> The Play Store Developer console started showing a warning recently about this issue
> 
> > We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date.
> 
> I imagine there are many people who scratched their heads for a minute to figure out what was using the Google Play Developer API, only to realize it's fastlane. I'm just commenting here to help others save time tracking down what's going on. Thanks fastlane team!

Hi i have same problem i don't know how to resolve the problem could you resolve please 
ACTION REQUIRED: Your automated publishing to Google Play will stop working on 1 December 2019

Your app is using an old version of the Google Play Developer API. From 1 December 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date

**Comment by wman1980** [comment]
@Saifullah6 if you are using Fastlane to deploy your App to Goople Play Store just update your Fastlane to latest version 2.136.0 and deploy your app again with Fastlane. The issue should be gone then otherwise its something else within your app.

**Comment by Saifullah6** [comment]
@wman1980  Thank You very much 
but i don't know what is Fastlane

**Comment by Saifullah6** [comment]
@wman1980 Thank You
but i dont use Fastlane 
i don't know what is the problem 
here is the link details
https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by mieliespoor** [comment]
@Saifullah6 if you don't use fastlane, then this is not the place to get your issue resolved. You can follow the instructions in the link you posted to get your integrations using the latest version of the api, or you can start using fastlane.

**Comment by claudioviola** [comment]
Hey guys
I updated to `fastlane-2.135.0` but I still see the warning message in the Google Play Console Page

Look at my build log here
![Schermata 2019-11-21 alle 18 43 41](https://user-images.githubusercontent.com/6689594/69362646-32c74c00-0c8f-11ea-8eb1-d12a113614d2.png)
![Schermata 2019-11-21 alle 18 44 08](https://user-images.githubusercontent.com/6689594/69362648-3529a600-0c8f-11ea-9a9b-f66a7992c299.png)
![Schermata 2019-11-21 alle 18 45 57](https://user-images.githubusercontent.com/6689594/69362663-3955c380-0c8f-11ea-8ecd-c9b7e7eb1884.png)


This my simple supply
```
supply(
   package_name: 'my.app.package',
   track: "assembleRelease",
   apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
)
```

Can I provide any other staff to help for understanding if I made a mistake?

Thank you

**Comment by freewil** [comment]
@claudioviola If you click the `Learn more` link in the warning banner I believe it explains what you are seeing: the banner warning appears if the old api has been used at all in last 7 days, so it may be outdated relative to current state

**Comment by janpio** [comment]
Also please open a new issue for your problem instead of posting in a closed issue - then we can properly investigate and possibly help.

**Comment by Saifullah6** [comment]
> 
> 
> Also please open a new issue for your problem instead of posting in a closed issue - then we can properly investigate and possibly help.

Thank You @janpio 

I don't know how to update version 3
and tomuch spend time on google for searching the solution but did not get any solution  

ACTION REQUIRED: Your automated publishing to Google Play will stop working on 1 December 2019
Your app is using an old version of the Google Play Developer API. From 1 December 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. 

https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html
