### ISSUE TITLE
Spaceship::InsufficientPermissions. User XYZ@xyz.com (Team ID AUADS7343) doesn't have enough permission for the following action: team_members 

### ISSUE THREAD

**Issue by vinitsample** [fastlane/fastlane#14581]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

Spaceship::InsufficientPermissions issue occurred when retrieving the members from the developer portal `Spaceship::Portal::Persons.all`

I am using Enterprise Developer Account and script was running well and all of sudden it's throwing me this error. I have accepted agreement on all apple portal.
This are the portal 
- https://developer.apple.com/
- https://itunesconnect.apple.com/

I am admin in both the portal and still causing the issue.
Can you please look into it ?

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by vinitsample** [comment]
It seems, apple have made changes to there API and domain.
As from Developer portal - `https://developer.apple.com/account/ ` when you try to access People it redirects you to `https://itunesconnect.apple.com/access/developers` and when you click **_Users Access & Roles_** on top left side, it will redirect to `https://appstoreconnect.apple.com/access/developers` . Thereby connecting all 3 portals together. While for Certificate and Identifier, the portal still remains the same and never redirects `https://developer.apple.com/account/ios/certificate/?teamId?=XYZ`

**Comment by vinitsample** [comment]
Since you are able to find and tag all Spaceship issue due to Apple Portal Changes. It will great , if you can look into this issue @joshdholtz . I upgraded my fastlane to latest 2.121.0 version and I thought this was a part of temporary fix by your git commits but its not resolved.
I run this command 
```
fastlane spaceship
Spaceship::Portal::Persons.all
```
and I receive the above permission error. It used to work perfectly fine for a year without any issue. Any hints on how I can get email address of people who are registered in my Enterprise Apple Portal ?
Thanks in advance.

**Comment by max-ott** [comment]
@vinitsample If your Apple ID is part of the Apple Enterprise Developer program, you should not have access to App Store Connect. Is your Apple ID part of both the Enterprise and the "normal/standard" program? 

What do you get if you run https://github.com/fastlane/fastlane/blob/08b539854c575e891c18af173ea2bae229a720ad/spaceship/docs/AppStoreConnect.md#login `select.team`?

**Comment by vinitsample** [comment]
```
[2]` pry(#<Spaceship::Playground>)> Spaceship::Tunes.select_team
=> "11912638"
```
I get the Team Number and the username I used for spaceship login is from Enterprise account. 
When I try to run this
`Spaceship::Portal::Persons.all`
I still receive same permission issue. 
Fastlane v2.122.0

**Comment by vinitsample** [comment]
Nope. There is no standard program. It's only Enterprise Account

**Comment by max-ott** [comment]
With the Enterprise Account you do not have access to App Store Connect. Therefore you get an error. This is working as intended.

`Spaceship::Tunes.select_team` includes `Tunes`, which tries to access App Store Connect. Feel free to make a pull request to add any functionality to the `Portal` class or adapt to the changes.

**Comment by vinitsample** [comment]
Sorry @max-ott , I did not understand it completely. In past it was working well without any issue on Enterprise account. All of sudden what changed that we are facing this issue. Beside, Can you suggest me how to fix it or point me in right direction ? What needs to be changed ? Some changes in Spaceship or Apple Portal ?

**Comment by max-ott** [comment]
What was the last time it was working? Apple changed some stuff with the unification of teams a couple of months ago, so this might be related. What is your role on the developer portal? Can you see all people there when manually logged in at https://developer.apple.com/account ?

**Comment by vinitsample** [comment]
Yes, It happened during last month of March. I am 100% sure as it was embedded in script and after end week of march it started failing. I assume when they had event at end of March.
I am currently Admin of the Developer Portal and yes, I can see all the employees who are logged in and my script was used to find out email address of all the people who are logged in Apple Portal. I agree with your unification process as when I login to above URL, I have two options which are `People` and `Certificate,Identifiers & Profile` . When I click `People` the above URL changes from `https://developer.apple.com/account/#/overview/XYZID123` to `https://itunesconnect.apple.com/access/developers` which never used to happen in past. But due to integration of itunesconnect this whole issue is caused as far as my knowledge.  However, if you click on `Certificates,Identifiers & Profiles` the url remains with same domain `https://developer.apple.com/account/ios/certificate/`

**Comment by max-ott** [comment]
Just check it out myself with our own Enterprise developer account. Looks like Apple completely changed this. There is now actually access to App Store Connect, or at latest to the team section ("Users & Access") and there is no longer a team page over at the developer center. This likely broke the existing way and would probably require some major changes in Fastlane/Spaceship.

@janpio Could you add the label feature request to this? (If appropriate) Yes, this worked before, but as far as I know enterprise usage is rather low compared to the standard developer program.

**Comment by janpio** [comment]
We could, but I think it would be easier on any potential contributor if you or @vinitsample created a new issue with the feature request template and summarized the wanted change in a few sentences. Then this starts from a clean slate, instead of a discussion that has to be understood first.

**Comment by vinitsample** [comment]
Hi @janpio , Sorry for the confusion. As mentioned by @max-ott , this is not a new request. This used to work great in the past which is getting developer (Persons) information from Apple Developer Portal. It broke in month of March and it’s still broken as Apple made multiple changes to Apple Dev Portal and did unification of its portal. It’ s not a new feature but the one which was previously built and is no longer working. You can try it yourself by running this command `Spaceship::Portal::Persons.all` over your Spaceship command prompt and it will be throwing you incorrect error that you do not have permission even though you being the admin of the whole portal

**Comment by janpio** [comment]
... which means it is a new feature for fastlane. It requires new code written to new APIs. Before it came for free with some of the existing functionality, after Apple changed the APIs under us it does not any more.

But of course I am happy to tag this here as "Feature Request" as well. The chance of this getting implemented if someone has to read through (and understand) all these comments instead of a clear feature request issue is a lot smaller though.

**Comment by vinitsample** [comment]
Tried and Tested multiple versions of fastlane. None of latest versions worked and waiting for new feature to be added soon in order to fix this issue.

**Comment by max-ott** [comment]
@vinitsample It actually works, but you need to use a different method. The old endpoint no longer exists.

```
bundle exec irb
require "spaceship"
Spaceship::Tunes.login("enterprise@email.com", "password")
Spaceship::Tunes.select_team 
1) Acme Corp (1234567890)
2) Acme Corp - F9D1K9Dl01 (0987654321) // This was the enterprise account for us; if the Apple ID is only part of the enterprise account this step is not needed
Spaceship::Tunes::Members.all
=> You will receive all members now
```

So basically `Spaceship::Tunes::Members.all` is the "new" `Spaceship::Portal::Persons.all`. Please check if this works and if so close the issue! 🙏

**Comment by vinitsample** [comment]
Hi @max-ott , Thank you so much for your time. 
That work's for me without any issue. 
I had figured this few days ago by trying some code changes and learning about Tunes API. 
Two primary changes to use this feature is
```
Spaceship::Tunes.login("xyz@enterprise.com",ENV["FAST_PASSWORD"])
Spaceship::Tunes.select_team
allPersons = Spaceship::Tunes::Members.all
```
