### ISSUE TITLE
[frameit,snapshot,deliver] New strategy for storing and identifying screenshots

### ISSUE THREAD

**Issue by liamnichols** [fastlane/fastlane#14598]
### Issue Description

In light of the recent iPad lineup introduction, it has become apparent that relying on image resolution alone is no longer a sufficient way to identify the device (frame or display family) and further consideration will be required to correctly address this in a reasonable way. 

The current problem is that the iPad Pro 12.9 inch (3rd generation) is considered by App Store Connect as a different display family to the 2nd generation despite the fact that they both share the exact screen resolution. This means that functionality in deliver and frameit can no longer provide a complete flow to uploading and framing all required screenshots (related issue: #14116).

---

An extremely short term solution to address the issue with deliver is to just search for '(3rd generation)'  in the filename if the dimensions are of an iPad Pro 12.9 inch (#14576) however its not a very sustainable solution given that Apple show no signs of making their future product roadmap easy for us to identify 😅 

---

A viable solution aimed towards fixing the problem **within deliver alone** is to start embedding screenshots 1 level deeper within the language directory and use the name of this sub-directory to identify the display family in App Store Connect. For example: 

```
fastlane/screenshots/en-GB/ipadPro/01_Home.png # 1st and 2nd generation
fastlane/screenshots/en-GB/ipadPro129/01_Home.png # 3rd generation
```

However this solution doesn't consider other parts of the process such as snapshot and frameit. Frameit has some additional levels of complexity since it supports the iPhone XR and deliver technically shouldn't know nothing about this device or its screen resolution since it isn't available as a display family in App Store Connect (it uses the 6.5 inch slot instead). 

---

Instead of trying to come up with the perfect sub-directory naming convention, I wonder if a better solution would be to let our users decide? Instead, a simple `info.json` file can be used to store relevant metadata about the screenshots within a given directory. This metadata format could then be expanded upon in the future should we need to but also allows the flexibility across each tool within the current Fastlane collection.

Let's take a look at some examples of some scenarios today: 

### The iPad Pro Scenario

**screenshots/en-GB/iPadPro_12_9_HomeButton/info.json**
```json
{
  "deliver_display_family": "ipadPro"
}
```

**screenshots/en-GB/iPadPro_12_9_3rdGeneration/info.json**
```json
{
  "deliver_display_family": "ipadPro129"
}
```

### Framing Also

**screenshots/en-GB/5.8 inch iPhone Display/info.json**
```json
{
  "deliver_display_family": "iphone58",
  "frameit_device_name": "iPhone XS"
}
```

### Standalone Frameit
**website/my_old_product/screenshots/iPhone/info.json**
```json
{
  "frameit_device_name": "iPhone 5c"
}
```

**website/new_product/screenshots/iPhone/info.json**
```json
{
  "frameit_device_name": "iPhone XR"
}
```

---

In order for the introduction of this system to be backwards compatible, i'd expect it to behave in the following ways (note i might have made some wrong assumptions): 

- If used with snapshot, the directories must be named after the simulator names. Snapshot will auto create the info.json file with the correct values for `deliver_display_name`.
- Frameit will fallback to original behaviour if it doesn't detect the info.json file in the directory that it's framing.
- Deliver will support the previous behaviour in the root of each language directory but will require all subdirectories to have an info.json file. It'll skip those directories that don't have the `deliver_display_name` set but fail if its a bad value. 

I do however still have some unanswered questions:

- Downloading screenshots via deliver won't be able to create directories with the same name as the ones that might already exist, is this going to be a problem? 
 
I might have also missed a lot more and the idea might not be that great but hopefully this a start for looking at more sustainable approach moving forward 🤔

**Comment by janpio** [comment]
>     * Downloading screenshots via deliver won't be able to create directories with the same name as the ones that might already exist, is this going to be a problem?

We will have to check deliver, but I think some `init`/`download` calls refuse to run when there already is a metadata folder with data in it.

**Comment by janpio** [comment]
Thanks Liam for writing down your thoughts, and recapping the problem we are having.

Unfortunately I do not like the idea of introducing an `info.json` file per folder. I wouldn't want to have to create those for my own projects, nor help people debug this via issues when things go wrong for them - the complexity is just too much. The beauty of screenshot dimensions was that it "just worked" (well enough), not matter what a user did.

If we do need folders anyway, I think we we should think really hard if we can't find a solution that allows the folder names to replace the job ob screenshot dimensions. Are there any other cases besides the iPhone XR that would cause problems right now? (For the iPhone XR, I think it would be fine to create a "mock" device family that can be used to put its screenshot under, if one ever decides to create them. This device family has no functionality for deliver, but lets snapshot and frameit do its job as they should do).

Or do you see any other use for the `info.json` file that could justify this complexity?

**Comment by liamnichols** [comment]
Yeah its a fair point.. I was hoping that if snapshot created the directory structure and info.json files automatically, it would mean that there there is often no need for a user to create the files themselves. 

But saying that, the other approach is to go with naming directories after devices:

Folder Name|Display Family|Frameit Template
---|---|---
iPhone 4s|iphone35||
iPhone 5|iphone4||
iPhone 5s|iphone4|iPhone 5s|
iPhone 6|iphone6||
iPhone 6 Plus|iphone6Plus||
iPhone 6s|iphone6|iPhone 6s|
iPhone 6s Plus|iphone6Plus|iPhone 6s Plus|
iPhone 7|iphone6|iPhone 7|
iPhone 7 Plus|iphone6Plus|iPhone 7 Plus|
iPhone 8|iphone6|iPhone 8|
iPhone 8 Plus|iphone6Plus|iPhone 8 Plus|
iPhone SE|iphone4|iPhone SE|
iPhone X|iphone58|iPhone X|
iPhone XS|iphone58|iPhone XS|
iPhone XS Max|iphone65|iPhone XS Max|
iPhone XR||iPhone XR|
iPad mini (5th generation)|ipad||
iPad Air (3rd generation)|ipad105||
iPad 2|ipad||
iPad Retina|ipad||
iPad Air|ipad||
iPad mini 2|ipad||
iPad mini 3|ipad||
iPad mini 4|ipad|iPad Mini 4|
iPad Air 2|ipad|iPad Air 2|
iPad (5th generation)|ipad||
iPad Pro (9.7-inch)|ipad||
iPad Pro (12.9-inch)|ipadPro|iPad Pro|
iPad Pro (12.9-inch) (2nd generation)|ipadPro|iPad Pro|
iPad Pro (10.5-inch)|ipad105||
iPad (6th generation)|ipad||
iPad Pro (11-inch)|ipadPro11||
iPad Pro (12.9-inch) (3rd generation)|ipadPro129||
Apple TV|appleTV||
Apple TV 4K|appleTV||
Apple TV 4K (at 1080p)|appleTV||
Apple Watch - 38mm|watch||
Apple Watch - 42mm|watch||
Apple Watch Series 2 - 38mm|watch||
Apple Watch Series 2 - 42mm|watch||
Apple Watch Series 3 - 38mm|watch||
Apple Watch Series 3 - 42mm|watch||
Apple Watch Series 4 - 40mm|watchSeries4||
Apple Watch Series 4 - 44mm|watchSeries4||
Mac|desktop||

This still leaves us with an unknown about how download_screenshots works with deliver.. I took a quick look and it looks like deliver will download the screenshots even if there is content in the screenshots directory. It's going to be hard/impossible to work out which one of the above directory names to put it into.. 

I guess that it could check over the existing directories, find the directory that matches the display family in the order of the newest device first (i.e if "iPhone 8" and "iPhone 6" directories both exist, put "iphone6" display family screenshots in the iPhone 8 directory) and if no directories matching exist then just drop them in the root of each language directory like it already does?

**Comment by janpio** [comment]
Why do you prefer device names over display families?

**Comment by liamnichols** [comment]
I was thinking of cleaning up something else off the list also...

Frameit currently requires you to use the `use_legacy_iphone5s`, `use_legacy_iphone6s`, or `use_legacy_iphonex` parameters to fallback to older device frames and I saw two problems with that:

1. It means that some frames actually get skipped (i.e the iPhone 8 template are still supported (but exists in the downloaded templates) and also the iPhone 6 template is not possible to be used.
2. It technically breaks backwards compatibility if a user is required to add a 'use_legacy_' flag to get the previous behaviour 

I thought that by taking things up a level and storing screenshots based on device, it gave us flexibility with our mappings and also it would be easier (i hope) to keep them updated as it would all exist in a single mapping. 

A 'mock' display family didn't really sit well with me since i think it might lead to being in the exact situation a few device releases later

**Comment by janpio** [comment]
I think for frameit we should/could free ourselves even a bit more from what is currently there, the whole frame selection is pretty crappy (and broken if you look into the details). But that's a real rats nest, and I am not sure if I really _want_ to look deeper into that or just not break to much stuff in there.

> A 'mock' display family didn't really sit well with me since i think it might lead to being in the exact situation a few device releases later

That's true, the only _real_ thing there is are the devices. But as so many devices share the same device family and screen dimensions, this just feels _wrong_, one level to far away from how I usually think about the screenshots I guess.

**Comment by liamnichols** [comment]
> I am not sure if I really want to look deeper into that or just not break to much stuff in there.

After looking into it, I see why you say that 😅 but if that’s the case, then maybe we should just be looking for further quick fixes such as #14576 instead? 

I was hoping that this issue could try to plan out more long term cleanups/fixes for the entire flow across all three of the tools and the bottom line is this:

1. Snapshot applies to all simulators
2. Frameit works with a variety of device models 
3. Deliver works with a selection of display families 

The only thing that all of them can be uniquely distinguished by now is the model of device so really we have to distinguish at that level.

From a basic implementation perspective, running snapshot without specifying devices will try to pick one simulator of each display family so really it shouldn’t bring any extra complications to the user. The table above should be pretty self explanatory for users who then want to do more advanced things though

**Comment by janpio** [comment]
> After looking into it, I see why you say that 😅 but if that’s the case, then maybe we should just be looking for further quick fixes such as #14576 instead?

Yep, basically what I have been thinking on and off for the last few days: Is it more probable to find a great "proper" solution or should we just find a dirty hack that works right now?

> From a basic implementation perspective, running snapshot without specifying devices will try to pick one simulator of each display family so really it shouldn’t bring any extra complications to the user.

Does it do that already? I thought snapshot was more uncoupled from the whole "Take screenshots for App Store" task.

**Comment by janpio** [comment]
Just looked into what `deliver init` does when downloading screenshots:

```
[22:07:43]: Downloading existing screenshot '1_iphone6Plus_1.iPhone 8 Plus-01StartScreen.png' for language 'en-US'
[22:07:43]: Downloading existing screenshot '1_ipadPro_1.iPad Pro (12.9-inch) (2nd generation)-01StartScreen.png' for language 'en-US'
[22:07:43]: Downloading existing screenshot '1_iphone65_1.iPhone XS Max-01StartScreen.png' for language 'en-US'
[22:07:43]: Downloading existing screenshot '1_ipadPro129_1.iPad Pro (12.9-inch) (3rd generation)-01StartScreen.png' for language 'en-US'
```

This reminded me that we would have no way to assign a downloaded screenshot to a device, only to a display family :/

**Comment by liamnichols** [comment]
> Does it do that already? I thought snapshot was more uncoupled from the whole "Take screenshots for App Store" task.

I think it might be slightly outdated now, but thats what this code is supposed to be doing I believe:

https://github.com/fastlane/fastlane/blob/1f1fb1fbdf57442c48ac0b6a4eb07128dbc8369d/snapshot/lib/snapshot/detect_values.rb#L34-L68

> This reminded me that we would have no way to assign a downloaded screenshot to a device, only to a display family :/

Yeah... I did mention that at the bottom of https://github.com/fastlane/fastlane/issues/14598#issuecomment-484134199... 

I think that we could probably do the following things:

- If a directory doesn't exist that maps to the relevant display family, create the directory using the latest device model name (i.e for display family `iphone6`, we'd create `iPhone 8` today since that's the latest model)
- If one or more directories exist for the given display family (i.e `iPhone 7` and `iPhone 8` both exist), we could:
  1. Prompt the user to chose which directory to download the screenshots into
  2. Automatically pick the latest model for that display family

I agree that it all seems a little complicated, however in practice I think that most things will be handled for the user automatically. The only thing that might be worth considering is that if a user changes the devices when running snapshot and is not using the `:clear_previous_screenshots` config, then they'll need to go and clear things up... But thinking twice about it, that problem exists anyway since the filenames change.

**Comment by janpio** [comment]
I see the biggest problem for users that want to use `deliver`, but didn't download any existing screenshots and also don't use snapshot to create the screenshots but do it manually or some other way. Right now they can just put all the screenshots into the screenshots directory.

**Comment by liamnichols** [comment]
> Right now they can just put all the screenshots into the screenshots directory.

So as we're going to keep the old approach functioning for backwards compatibility, that approach would continue to work for everything apart from the 3rd generation 12.9 inch iPad Pro. 

If/when the user wonders why the iPad Pro is not working, they'll still have to refer to the docs to find the one-off solution... I was thinking that seeing a table of supported directories might be a nicer approach to a few random workarounds 🤔 

I guess that most of my thinking is more tailored towards larger projects since in my case, we currently are maintaining 24 screenshots for each of the 16 supported languages and its a bit messy having it all at the top level of the language directory. 

But, I guess that there is no reason why we can't maintain support for a variety of approaches:

1. Infer from the image resolution of files in the top level directory 
    - Warn if we detect ambiguity (12.9 inch iPad Pro screenshots that aren't resolved by approach 2) 
2. Search for device names or display families at the beginning of the filename
3. Allow nesting of screenshots in directories titled after device names
4. Allow nesting of screenshots in directories titled after display families

Approaches 3 and 4 are kind of optional.. I don't expect all users to want to do this, but I expect it will be useful for those who maintain larger projects. We could have a new option in snapshot for example like `:use_subdirectories` that allows people to enable this if they want to.

**Comment by janpio** [comment]
> 1. Warn if we detect ambiguity (12.9 inch iPad Pro screenshots that aren't resolved by approach 2)

I think this will be a big part of any solution: Warning about possible problems, and offer a link to the correct documentation. For example: If we recognize an iPad Pro screenshot, output a warning that points the people to the 2nd gen/3rd gen solution strategy/ies.

> We could have a new option in snapshot for example like `:use_subdirectories` that allows people to enable this if they want to.

That's a great idea.

I mentioned you in a PR that tries to "hack" a solution strategy for the 3rd gen problem - I think this would be approach 2 from your list. I think this would be a "quick fix" we could use to buy us some time to get the bigger solution implemented and tested.

**Comment by chnbr** [comment]
Is anybody working on this ? 'frameit' still fails for 3rd generation devices. One problem is the missing device template and the other is the integration of "3rd generation iPad device type" seems to be corrupt or even missing ? 

It looks like 'snapshot' and 'deliver' can already handle the 3rd generation iPads...

Anybody who can comment on the current code status and when we can expect to have a solution for 'frameit' too ?

**Comment by liamnichols** [comment]
My understanding is that it’s not being worked on yet and we haven’t really decided on a definite way forward.

Frameit won’t be able to support iPad Pro frames however until the assets are actually available (via facebook.design) and I have no idea how to make that happen

**Comment by janpio** [comment]
As @liamnichols mentioned the biggest problem for frameit are the missing frame files with a licence that allows us to use them. Then we could add those to the frames repository, and adapt the actual code to properly handle the screenshots as well.

Best create an issue _just_ for frameit, and we can start looking into all these issues. (Maybe we can skip the frame file + license issue, and assume all users take care of that by themselves somehow for example. Then it is _just_ a bit a code left to do).

**Comment by chnbr** [comment]
> Frameit won’t be able to support iPad Pro frames however until the assets are actually available (via facebook.design) and I have no idea how to make that happen

I have contacted a person from facebook.design and pointed out that the iPadPro3rd image is missing and that a huge community is waiting for it. I don't know is this drives things forward but the try was worth it. We'll see...

**Comment by liamnichols** [comment]
Sorry for not really being able to dedicate much more time to this over the last month or so... I wonder if this ticket should remain open though? 🤔

**Comment by janpio** [comment]
Any response @chnbr?

**Comment by trevoriancox** [comment]
I'm raising this here as it is another example of where users can run into an issue with the current screenshots. Could we consider also detecting iPad Pro 3rd gen with this string: "iPad-Pro--12-9-inch---3rd-generation-"? Since fastlane snapshots doesn't work with Xamarin, Xamarin developers will likely use Xamarin UITest which outputs screenshots with this text in the name.

**Comment by janpio** [comment]
Sounds reasonable, but please open a new issues so we can properly look into the details.
