### ISSUE TITLE
2.120.0: Build.beta_review_info.reload -> HTTP 410 Gone

### ISSUE THREAD

**Issue by beefon** [fastlane/fastlane#14597]
`Build.beta_review_info` calls `reload`, which leads to `410 GONE`.

```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response': [31m[!] <html> (Spaceship::UnexpectedResponse)
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/404046/apps/417281773/builds/1555330334. Reason:
<pre>    Gone</pre></p>
</body>
</html>
[0m
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/client.rb:50:in `get_build'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/build.rb:105:in `find'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/build.rb:141:in `reload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/build.rb:183:in `beta_review_info'
```

**Comment by adamtester** [comment]
Just got exactly the same response

```
bundler: failed to load command: fastlane (/Users/adamtester/.rbenv/versions/2.3.8/bin/fastlane)
Spaceship::UnexpectedResponse: [!] <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/119389050/apps/1439801102/platforms/ios/trains. Reason:
<pre>    Gone</pre></p>
</body>
</html>

  /Users/adamtester/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response'
  /Users/adamtester/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/test_flight/client.rb:31:in `get_build_trains'
  /Users/adamtester/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/test_flight/build_trains.rb:16:in `all'
  /Users/adamtester/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/test_flight/build.rb:110:in `all'
  /Users/adamtester/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/test_flight/build.rb:121:in `all_processing_builds'
```

**Comment by beefon** [comment]
Build is uploading fine, I can't set the what's new after that as it fails with 410.

**Comment by dipkasyap** [comment]
12:30:09 /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/spaceship/lib/spaceship/test_flight/client.rb:330:in `handle_response': [!] <html> (Spaceship::UnexpectedResponse)
12:30:09 <head>
12:30:09 <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
12:30:09 <title>Error 410 Gone</title>
12:30:09 </head>
12:30:09 <body><h2>HTTP ERROR 410</h2>
12:30:09 <p>Problem accessing /v2/providers/118095219/apps/1081678481/platforms/ios/trains. Reason:
12:30:09 <pre>    Gone</pre></p>
12:30:09 </body>
12:30:09 </html>

Having same here

**Comment by snatchev** [comment]
@dipkasyap @adamtester Looks like you should be able to resolve this your issue by updating to the latest version of fastlane.

@dipkasyap looks like you identified a bug. Could you test a fix for us?
Change:
build.rb#140
```ruby
def reload
  self.raw_data = self.class.find(app_id: app_id, build_id: id).raw_data
end
```
To:
```ruby
def reload
  self.raw_data = find_app_store_connect_build
end
```

**Comment by janpio** [comment]
Hey @beefon @adamtester @dipkasyap, could you please check if this problem still exists with a current release of fastlane? We tried to fix a lot of these "error 410 gone" errors, and now need your feedback if this covered yours as well. Thanks!

**Comment by dipkasyap** [comment]
@janpio  Yea, its fine after update , Cheers  :)

**Comment by janpio** [comment]
Awesome, thanks for the update @dipkasyap.

What about you @beefon and @adamtester?

**Comment by beefon** [comment]
I've used this as an opportunity to implement this functionality using AppStore Connect APIs, and not using Fastlane anymore. Can't confirm now.

**Comment by janpio** [comment]
Awesome.

Can you share a bit @beefon? This might help getting fastlane updated (or give others a starting point).

**Comment by adamtester** [comment]
@janpio I don't have an update to push just yet, will let you know!

**Comment by beefon** [comment]
https://developer.apple.com/documentation/appstoreconnectapi/modify_a_beta_build_localization

I’ve been using this Swift sdk:

https://github.com/AvdLee/appstoreconnect-swift-sdk
