### ISSUE TITLE
Companies using Fastlane?

### ISSUE THREAD

**Issue by knutnyg** [fastlane/fastlane#1459]
Hi.

I'm writing a piece on Fastlane for our company's technology radar. I tried to find information on any known companies that relies on Fastlane as part of their workflow, but I could not find any. Do you have any examples for me? :)

Best regards,
Knut

**Comment by jcampbell05** [comment]
supmenow.com uses it but you can also see companies in the https://github.com/fastlane/examples as well.

:)

**Comment by knutnyg** [comment]
Ah, cheers!

**Comment by KrauseFx** [comment]
It's actually linked twice in the fastlane main README: https://github.com/fastlane/fastlane#examples :wink:
