### ISSUE TITLE
[frameit] Unable to frame iPhone XR screenshot with black frame

### ISSUE THREAD

**Issue by liamnichols** [fastlane/fastlane#14590]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running frameit without any parameters (default to black), the following error is printed: 

```
[⠋] Framing screenshot './fastlane/screenshots/es-MX/iPhone XR-0Launch.png' [21:14:15]: Couldn't find template for screenshot type 'Apple iPhone XR Black'
[21:14:15]: Please run `fastlane frameit download_frames` to download the latest frames
```

It looks like the actual template is named "Apple iPhone XR Space Gray" so its thinks that it doesn't exist. 

##### Command executed
`bunde exec fastlane frameit`

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
bundle exec fastlane frameit
[✔] 🚀
[21:12:53]: Using device frames version 'latest'
[✔] Framing screenshot './fastlane/screenshots/es-MX/iPhone 8 Plus-0Launch.png'
[21:13:07]: Added frame: '/Users/liamnichols/Code/Local/ScreenshotTest/fastlane/screenshots/es-MX/iPhone 8 Plus-0Launch_framed.png'
[✔] Framing screenshot './fastlane/screenshots/es-MX/iPhone XS Max-0Launch.png'
[21:13:23]: Added frame: '/Users/liamnichols/Code/Local/ScreenshotTest/fastlane/screenshots/es-MX/iPhone XS Max-0Launch_framed.png'
[✔] Framing screenshot './fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (3rd generation)-0Launch.png'
[21:13:49]: Added frame: '/Users/liamnichols/Code/Local/ScreenshotTest/fastlane/screenshots/es-MX/iPad Pro (12.9-inch) (3rd generation)-0Launch_framed.png'
[✔] Framing screenshot './fastlane/screenshots/es-MX/iPad Pro (12.9-inch)-0Launch.png'
[21:14:15]: Added frame: '/Users/liamnichols/Code/Local/ScreenshotTest/fastlane/screenshots/es-MX/iPad Pro (12.9-inch)-0Launch_framed.png'
[⠋] Framing screenshot './fastlane/screenshots/es-MX/iPhone XR-0Launch.png' [21:14:15]: Couldn't find template for screenshot type 'Apple iPhone XR Black'
[21:14:15]: Please run `fastlane frameit download_frames` to download the latest frames
```

</details>

### Environment

<details>
  <pre>Loaded fastlane plugins</pre>
</details>

**Comment by Embraser01** [comment]
The problem is still present on the latest version (2.123.0) 🙂

**Comment by janpio** [comment]
I think there already is some handling code for Black => Space Grey, probably it just doesn't apply to iPhone XR (yet).

**Comment by liamnichols** [comment]
I think it’s a matter of making this line: 

https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/screenshot.rb#L63

Return `Space Gray` instead of `Black`

And maybe adding a test or something

**Comment by Embraser01** [comment]
I could make a PR to remove the `elsif` (as it should be enough I think). But I have no idea how to write a test (don't know ruby at all 😄)...

**Comment by janpio** [comment]
Ummm, does one of you understand why this was added in the first place? https://github.com/fastlane/fastlane/commit/dcc95a64edde0bf616a62bcc62f3737f7981d3e9#diff-31f55c7b2572839daddfa36385dfaa44R62

**Comment by janpio** [comment]
Oh, that's interesting: https://github.com/fastlane/fastlane/pull/13774/commits/4a50c7c3645a446205d99781da036e8d1d5373b3#r238531607 Seems this was already recognized as a bug, but then slipped through anyway :/

@Embraser01 Removing the `elsif` line and next should be enough. For tests @liamnichols cna hopefully point us to the correct file.

**Comment by liamnichols** [comment]
Sorry, bit late to reply here but I’m not sure about the frameit test coverage 🙈
