### ISSUE TITLE
Unable to upload build to bugsnag using fastlane

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#14593]
I am using the fastlane to upload the build in bugsnag. Here I am getting this error and it failed to upload the build in bugsnag.

```

 fastlane finished with errors

[!] Could not find action, lane or variable 'upload_symbols_to_bugsnag'. Check out the documentation for more details: https://docs.fastlane.tools/actions
```

Fastlane env

details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                     |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.14.2                                   |
| Ruby                        | 2.5.1                                     |
| Bundler?                    | true                                      |
| Git                         | git version 2.19.2                        |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane       |
| Host                        | Mac OS X 10.14.2 (18C54)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib              |
| OpenSSL Version             | OpenSSL               |
| Is contained                | false                                     |
| Is homebrew                 | false                                     |
| Is installed via Fabric.app | false                                     |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "App.xcodeproj")
    build_app(scheme: "App")
    upload_symbols_to_bugsnag
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("identifier") # The bundle identifier of your app
apple_id("apple_id") # Your Apple email address

itc_team_id("itcid") # iTunes Connect Team ID
team_id("jeehefhejfhejhf") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.63.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

**Comment by janpio** [comment]
Well, what the error message says:

> [!] Could not find action, lane or variable 'upload_symbols_to_bugsnag'.

Your `Fastfile` doesn't have a lane `upload_symbols_to_bugsnag`.

You might be trying to use a plugin, that offers an _action_. Here are the docs: https://docs.bugsnag.com/build-integrations/fastlane/ which also describe how to create a lane and use that action in it.

**Comment by nihp** [comment]
I found it. Unfortunately it get removed from the plugins.
