### ISSUE TITLE
Documentation does not mention that upload_symbols_to_sentry is deprecated

### ISSUE THREAD

**Issue by christhegrand** [fastlane/fastlane#14608]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Documentation does not mention that upload_symbols_to_sentry is deprecated

##### Command executed
upload_symbols_to_sentry

##### Complete output when running fastlane, including the stack trace and command used

As part of our CI process, we upload debug symbols to Sentry using the upload_symbols_to_sentry function:

<details>
  <pre>     upload_symbols_to_sentry(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG'],
      project_slug: ENV['SENTRY_PROJECT']
    ) </pre>
</details>

After upload_symbols_to_sentry was called, I saw this appear in our CI logs:

```
[15:52:31]: --------------------------------------
[15:52:31]: --- Step: upload_symbols_to_sentry ---
[15:52:31]: --------------------------------------
==========================================
This action (upload_symbols_to_sentry) is deprecated
Please use the `sentry` plugin instead.
Install using `fastlane add_plugin sentry`.
Replace `upload_symbols_to_sentry(...)` with `sentry_upload_dsym(...)`.
==========================================

[15:52:31]: It's recommended to use the official Sentry Fastlane plugin
[15:52:31]: GitHub: https://github.com/getsentry/fastlane-plugin-sentry
[15:52:31]: Installation: fastlane add_plugin sentry
[15:52:31]: Missing gem 'rest-client', please add the following to your local Gemfile:
[15:52:31]: 
[15:52:31]: ▸ gem "rest-client"
[15:52:31]: 
```

Neither the [Fastlane documentation](https://docs.fastlane.tools/actions/upload_symbols_to_sentry/) nor the [Sentry documentation](https://docs.sentry.io/clients/cocoa/dsym/) mention that this function is deprecated. The Fastlane documentation should be updated to reflect this. 

(I'm also a bit surprised about the rest-client message - rest-client was not included in the Gemfile.lock that was generated when I upgraded fastlane with gem.)

**Comment by janpio** [comment]
Uhh:

> Please use the sentry plugin instead.
> Install using fastlane add_plugin sentry.
> Replace upload_symbols_to_sentry(...) with sentry_upload_dsym(...).

From https://docs.fastlane.tools/actions/upload_symbols_to_sentry/
