### ISSUE TITLE
latest_testflight_build_number returns random data

### ISSUE THREAD

**Issue by bsarrazin** [fastlane/fastlane#14606]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: 2.120.0
- Last working version: 2.119.0

### Regression Description
Running the `latest_testflight_build_number` action returns random data when no version is passed in. It used to return the latest build number from the latest version.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ bundle exec fastlane run latest_testflight_build_number
[✔] 🚀
+------------------------------------------------+---------+------------------------------------------------------------+
|                                                     Used plugins                                                      |
+------------------------------------------------+---------+------------------------------------------------------------+
| Plugin                                         | Version | Action                                                     |
+------------------------------------------------+---------+------------------------------------------------------------+
| fastlane-plugin-appconfig                      | 0.3.0   | push_config pull_config                                    |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1   | setup_fragile_tests_for_rescan                             |
| fastlane-plugin-test_center                    | 3.6.3   | suppressed_tests suppress_tests suppress_tests_from_junit  |
|                                                |         | tests_from_xctestrun collate_test_result_bundles           |
|                                                |         | tests_from_junit multi_scan collate_html_reports           |
|                                                |         | collate_junit_reports collate_json_reports                 |
+------------------------------------------------+---------+------------------------------------------------------------+

[10:13:03]: --------------------------------------------
[10:13:03]: --- Step: latest_testflight_build_number ---
[10:13:03]: --------------------------------------------
[10:13:03]: Login to App Store Connect (ios@email.com)
Available session is not valid any more. Continuing with normal login.
[10:13:08]: Login successful
[10:13:10]: Fetching the latest build number for version 10.0.0 // this version doesn't exist in our portal
[10:13:12]: Latest upload for version 10.0.0 is build: 4 // we're at build number 160+, no idea where this 4 comes from
[10:13:12]: Result: 4</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.6.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.6.2/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
fastlane_version '2.120.0'

fastlane_require 'json'

platform :ios do

  # --------------------------------------------------
  # Set Up & Tear Down
  # --------------------------------------------------

  before_all do |lane, options|
  end

  after_all do |lane, options|
  end

  # --------------------------------------------------
  # Lanes
  # --------------------------------------------------

  import 'utils/shared_utils.rb'
  import 'lanes/assemble.rb'
  import 'lanes/build.rb'
  import 'lanes/bump.rb'
  import 'lanes/config.rb'
  import 'lanes/coverage.rb'
  import 'lanes/install.rb'
  import 'lanes/metadata.rb'
  import 'lanes/mock.rb'
  import 'lanes/release.rb'
  import 'lanes/sauce.rb'
  import 'lanes/symbols.rb'
  import 'lanes/testflight.rb'
  import 'lanes/tests.rb'

  # --------------------------------------------------
  # Error Handling
  # --------------------------------------------------

  error do |lane, exception, options|
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "[REDACTED]"
apple_id "[REDACTED]"
team_id "[REDACTED]"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                         | Version | Update-Status  |
| ---------------------------------------------- | ------- | -------------- |
| fastlane-plugin-appconfig                      | 0.3.0   | 💥 Check failed |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1   | ✅ Up-To-Date   |
| fastlane-plugin-test_center                    | 3.6.3   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                                            | Version      |
| ---------------------------------------------- | ------------ |
| did_you_mean                                   | 1.3.0        |
| bundler                                        | 1.17.3       |
| etc                                            | 1.0.1        |
| forwardable                                    | 1.2.0        |
| fileutils                                      | 1.1.0        |
| CFPropertyList                                 | 3.0.0        |
| concurrent-ruby                                | 1.1.5        |
| i18n                                           | 0.9.5        |
| minitest                                       | 5.11.3       |
| thread_safe                                    | 0.3.6        |
| tzinfo                                         | 1.2.5        |
| activesupport                                  | 4.2.11.1     |
| public_suffix                                  | 2.0.5        |
| addressable                                    | 2.6.0        |
| atomos                                         | 0.1.3        |
| babosa                                         | 1.0.2        |
| claide                                         | 1.0.2        |
| clamp                                          | 1.3.0        |
| fuzzy_match                                    | 2.0.4        |
| nap                                            | 1.1.0        |
| cocoapods-core                                 | 1.6.1        |
| cocoapods-deintegrate                          | 1.0.4        |
| cocoapods-downloader                           | 1.2.2        |
| cocoapods-plugins                              | 1.0.0        |
| cocoapods-search                               | 1.0.0        |
| cocoapods-stats                                | 1.1.0        |
| netrc                                          | 0.11.0       |
| cocoapods-trunk                                | 1.3.1        |
| cocoapods-try                                  | 1.1.0        |
| colored2                                       | 3.1.2        |
| escape                                         | 0.0.4        |
| fourflusher                                    | 2.2.0        |
| gh_inspector                                   | 1.1.3        |
| molinillo                                      | 0.6.6        |
| ruby-macho                                     | 1.4.0        |
| nanaimo                                        | 0.2.6        |
| xcodeproj                                      | 1.8.2        |
| cocoapods                                      | 1.6.1        |
| colored                                        | 1.2          |
| colorize                                       | 0.8.1        |
| highline                                       | 1.7.10       |
| commander-fastlane                             | 4.4.6        |
| declarative                                    | 0.0.10       |
| declarative-option                             | 0.1.0        |
| digest-crc                                     | 0.4.1        |
| unf_ext                                        | 0.0.7.5      |
| unf                                            | 0.1.4        |
| domain_name                                    | 0.5.20180417 |
| dotenv                                         | 2.7.2        |
| emoji_regex                                    | 1.0.1        |
| excon                                          | 0.64.0       |
| multipart-post                                 | 2.0.0        |
| faraday                                        | 0.15.4       |
| http-cookie                                    | 1.0.3        |
| faraday-cookie_jar                             | 0.0.6        |
| faraday_middleware                             | 0.13.1       |
| fastimage                                      | 2.1.5        |
| jwt                                            | 2.1.0        |
| memoist                                        | 0.16.0       |
| multi_json                                     | 1.13.1       |
| os                                             | 1.0.0        |
| signet                                         | 0.11.0       |
| googleauth                                     | 0.6.7        |
| httpclient                                     | 2.8.3        |
| mime-types-data                                | 3.2019.0331  |
| mime-types                                     | 3.2.2        |
| uber                                           | 0.1.0        |
| representable                                  | 3.0.4        |
| retriable                                      | 3.1.2        |
| google-api-client                              | 0.23.9       |
| google-cloud-env                               | 1.0.5        |
| google-cloud-core                              | 1.3.0        |
| google-cloud-storage                           | 1.16.0       |
| json                                           | 2.2.0        |
| mini_magick                                    | 4.5.1        |
| multi_xml                                      | 0.6.0        |
| plist                                          | 3.5.0        |
| rubyzip                                        | 1.2.2        |
| security                                       | 0.1.3        |
| naturally                                      | 2.2.0        |
| simctl                                         | 1.6.5        |
| slack-notifier                                 | 2.3.2        |
| terminal-notifier                              | 2.0.0        |
| unicode-display_width                          | 1.5.0        |
| terminal-table                                 | 1.8.0        |
| tty-screen                                     | 0.6.5        |
| tty-cursor                                     | 0.6.1        |
| tty-spinner                                    | 0.9.0        |
| word_wrap                                      | 1.0.0        |
| rouge                                          | 2.0.7        |
| xcpretty                                       | 0.3.0        |
| xcpretty-travis-formatter                      | 1.0.0        |
| git                                            | 1.5.0        |
| fastlane-plugin-appconfig                      | 0.3.0        |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1        |
| xctest_list                                    | 1.1.7        |
| fastlane-plugin-test_center                    | 3.6.3        |
| mini_portile2                                  | 2.4.0        |
| nokogiri                                       | 1.10.2       |
| slather                                        | 2.4.7        |
</details>

*generated on:* **2019-04-16**
</details>

**Comment by ramnac** [comment]
Still the latest_testflight_build_number issue exists.

Just as a workaround (Took me a lot of time though), i have created a method which can solve the problem (Temporarily) - later this can be merged to the core spaceship.

Add this method to your fastfile. Call this method by passing three parameters.
version:
appleId:
appIdentifier:

You will get the appropriate build number. Uses the AppStoreconnect API

```
private_lane :latestTestflightBuildNumber do |options|
    require "spaceship"
    UI.message("Login to App Store Connect (#{options[:appleId]})")
    Spaceship::Tunes.login(user = options[:appleId])
    Spaceship::Tunes.select_team
    UI.message("Login successful")
    spaceshipClient = Spaceship::ConnectAPI::Base.client
    params = spaceshipClient.build_params(filter: { bundleId: options[:appIdentifier]})
    appsResponse = spaceshipClient.request(:get, "apps") do |req|
      req.options.params_encoder = Faraday::NestedParamsEncoder
      req.params = params
    end 
    UI.user_error!("The bundle identifier - #{options[:appIdentifier]} does not exist in the AppStoreConnect!!!") if appsResponse.body["data"].count==0
    UI.user_error!("Looks like there is some problem with the input provided. Please check the app identifier!!!") if appsResponse.body["data"].count>1
    appIdFromAppsResponse=appsResponse.body["data"][0]["id"]
    preReleaseVersionsResponse = spaceshipClient.request(:get, "apps/#{appIdFromAppsResponse}/preReleaseVersions")
    preReleaseFilteredResponse = preReleaseVersionsResponse.body["data"].select { |k| k["attributes"]["version"] == options[:version] }
    begin
      preReleaseVersionId = preReleaseFilteredResponse[0]["id"]
      nonExpiredBuildsResponse = spaceshipClient.get_builds(filter: { expired: false, processingState: "PROCESSING,VALID", preReleaseVersion: "#{preReleaseVersionId}" },limit: 200, includes: "preReleaseVersion")
      latestTestflightBuildNumber = (nonExpiredBuildsResponse.max_by{|k| k["attributes"]["version"].to_i }["attributes"]["version"]).to_i
    rescue
      latestTestflightBuildNumber = "0".to_i
    end
  end
```
Let me know if anyone faces any issue with this.

**Comment by janpio** [comment]
Hey @bsarrazin @ramnac, could you please check if this problem still exists with a current release of fastlane? We tried to fix a lot of these "error 410 gone" errors, and now need your feedback if this covered yours as well. Thanks!

**Comment by bsarrazin** [comment]
@janpio negative, still getting the same behaviour with fastlane 2.121.0:
```
$ bundle exec fastlane run latest_testflight_build_number
[✔] 🚀
+------------------------------------------------+---------+------------------------------------------------------------+
|                                                     Used plugins                                                      |
+------------------------------------------------+---------+------------------------------------------------------------+
| Plugin                                         | Version | Action                                                     |
+------------------------------------------------+---------+------------------------------------------------------------+
| fastlane-plugin-appconfig                      | 0.3.0   | push_config pull_config                                    |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1   | setup_fragile_tests_for_rescan                             |
| fastlane-plugin-test_center                    | 3.6.3   | suppressed_tests suppress_tests suppress_tests_from_junit  |
|                                                |         | tests_from_xctestrun collate_test_result_bundles           |
|                                                |         | tests_from_junit multi_scan collate_html_reports           |
|                                                |         | collate_junit_reports collate_json_reports                 |
+------------------------------------------------+---------+------------------------------------------------------------+

[08:17:14]: --------------------------------------------
[08:17:14]: --- Step: latest_testflight_build_number ---
[08:17:14]: --------------------------------------------
[08:17:14]: Login to App Store Connect ([REDACTED]@[REDACTED].com)
Available session is not valid any more. Continuing with normal login.
[08:17:18]: Login successful
[08:17:19]: Fetching the latest build number for version 10.0.0
[08:17:20]: Latest upload for version 10.0.0 is build: 4
[08:17:20]: Result: 4
```

**Comment by janpio** [comment]
For some context, it might help to have the content of your spaceship logfile from `/tmp/spaceship*.log` (you can also use https://docs.fastlane.tools/actions/spaceship_logs/). Maybe this helps understand where those numbers are coming from.

**Comment by bsarrazin** [comment]
I ran `bundle exec fastlane run spaceship_logs`:
```
# Logfile created on 2019-04-24 08:17:19 -0700 by logger.rb/66358
INFO  [08:17:19]: >> GET preReleaseVersions: [undefined body] 
DEBUG [08:17:19]: << GET preReleaseVersions: 200 {"data"=>[{"type"=>"preReleaseVersions", "id"=>"69b6213c-a2ca-111b-e053-5b8c7c11c0fe", "attributes"=>{"version"=>"10.0.0", "platform"=>"IOS"}, "relationships"=>{"builds"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions/69b6213c-a2ca-111b-e053-5b8c7c11c0fe/relationships/builds", "related"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions/69b6213c-a2ca-111b-e053-5b8c7c11c0fe/builds"}}, "app"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions/69b6213c-a2ca-111b-e053-5b8c7c11c0fe/relationships/app", "related"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions/69b6213c-a2ca-111b-e053-5b8c7c11c0fe/app"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions/69b6213c-a2ca-111b-e053-5b8c7c11c0fe"}}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions?limit=1&sort=-version&filter%5Bapp%5D=1161533637", "next"=>"https://appstoreconnect.apple.com/iris/v1/preReleaseVersions?cursor=AQ.a-II-Q&limit=1&sort=-version&filter%5Bapp%5D=1161533637"}, "meta"=>{"paging"=>{"total"=>98, "limit"=>1}}}
INFO  [08:17:19]: >> GET builds: [undefined body] 
DEBUG [08:17:20]: << GET builds: 200 {"data"=>[{"type"=>"builds", "id"=>"69ae25a2-477c-fce9-e053-5b8c7c111149", "attributes"=>{"version"=>"4", "uploadedDate"=>"2017-10-11T14:03:31-07:00", "expirationDate"=>"2018-01-09T14:03:31-08:00", "expired"=>true, "minOsVersion"=>"9.0", "iconAssetToken"=>{"width"=>120, "templateUrl"=>"https://is2-ssl.mzstatic.com/image/thumb/Newsstand128/v4/a0/ca/8a/a0ca8af4-20c9-1ea5-1a3e-f65e07dcf5b8/Icon-60@2x.png.png/{w}x{h}bb.{f}", "height"=>120}, "processingState"=>"VALID", "usesNonExemptEncryption"=>false, "qcState"=>"BETA_INTERNAL_TESTING"}, "relationships"=>{"preReleaseVersion"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/preReleaseVersion", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/preReleaseVersion"}}, "individualTesters"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/individualTesters", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/individualTesters"}}, "betaBuildMetrics"=>{"meta"=>{"paging"=>{"total"=>1, "limit"=>10}}, "data"=>[{"type"=>"betaBuildMetrics", "id"=>"69ae25a2-477c-fce9-e053-5b8c7c111149"}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/betaBuildMetrics", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/betaBuildMetrics"}}, "betaGroups"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/betaGroups", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/betaGroups"}}, "betaBuildLocalizations"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/betaBuildLocalizations", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/betaBuildLocalizations"}}, "appEncryptionDeclaration"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/appEncryptionDeclaration", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/appEncryptionDeclaration"}}, "betaAppReviewSubmission"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/betaAppReviewSubmission", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/betaAppReviewSubmission"}}, "app"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/app", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/app"}}, "buildBetaDetail"=>{"data"=>{"type"=>"buildBetaDetails", "id"=>"69ae25a2-477c-fce9-e053-5b8c7c111149"}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/buildBetaDetail", "related"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149/buildBetaDetail"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds/69ae25a2-477c-fce9-e053-5b8c7c111149"}}], "included"=>[{"type"=>"betaBuildMetrics", "id"=>"69ae25a2-477c-fce9-e053-5b8c7c111149", "attributes"=>{"installCount"=>0, "crashCount"=>0, "inviteCount"=>0, "sevenDayTesterCount"=>0}, "relationships"=>{"build"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/build", "related"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/69ae25a2-477c-fce9-e053-5b8c7c111149/build"}}, "betaGroup"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/betaGroup", "related"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/69ae25a2-477c-fce9-e053-5b8c7c111149/betaGroup"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/betaBuildMetrics/69ae25a2-477c-fce9-e053-5b8c7c111149"}}, {"type"=>"buildBetaDetails", "id"=>"69ae25a2-477c-fce9-e053-5b8c7c111149", "attributes"=>{"autoNotifyEnabled"=>true, "didNotify"=>false, "internalBuildState"=>"EXPIRED", "externalBuildState"=>"EXPIRED"}, "relationships"=>{"build"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/buildBetaDetails/69ae25a2-477c-fce9-e053-5b8c7c111149/relationships/build", "related"=>"https://appstoreconnect.apple.com/iris/v1/buildBetaDetails/69ae25a2-477c-fce9-e053-5b8c7c111149/build"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/buildBetaDetails/69ae25a2-477c-fce9-e053-5b8c7c111149"}}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/builds?include=betaBuildMetrics%2CbuildBetaDetail&filter%5BpreReleaseVersion%5D=69b6213c-a2ca-111b-e053-5b8c7c11c0fe&limit=1&sort=-uploadedDate&filter%5Bapp%5D=1161533637", "next"=>"https://appstoreconnect.apple.com/iris/v1/builds?cursor=AQ.GXQEGw&include=betaBuildMetrics%2CbuildBetaDetail&filter%5BpreReleaseVersion%5D=69b6213c-a2ca-111b-e053-5b8c7c11c0fe&limit=1&sort=-uploadedDate&filter%5Bapp%5D=1161533637"}, "meta"=>{"paging"=>{"total"=>2, "limit"=>1}}}

**Comment by janpio** [comment]
Looking into those now.

**Comment by janpio** [comment]
Ok, so the first `preReleaseVersions` request returns the `10.0.0`, and `builds` then a version `4` - so somehow Apple is returning these numbers. Someone that knows more about how that action works will have to look into if this makes any sense.

**Comment by bsarrazin** [comment]
@janpio that makes sense, I made sure to go back into the portal and see if we had an old version for `10.0.0` and build `4` and I can't see neither. However, doesn't mean it's not there but hidden in the UI by Apple.

Thank for looking into this! 🍻

**Comment by janpio** [comment]
Ok, there definitely is some new-ish code that is responsible for that `10.0.0` in your case:
https://github.com/fastlane/fastlane/blame/be55c12077fe91f4eecb64e8ee3a3fa4b8085048/fastlane/lib/fastlane/actions/app_store_build_number.rb#L41-L43

Can you share what versions _are_ there?
Can you try to supply the correct version and see if it at least then gets the correct build no?

**Comment by mdavidsen** [comment]
Hi,

I'm currently trying to debug some issues & fallout after the API removal by Apple. The results you get from the preReleaseVersions endpoint is due to the sorting of the returned versions `sort: "-versions"`. This I'm fairly sure is the best way to handle defaults. When using `latest_testflight_build_number` it defaults to the highest version submitted, you can override that by using `latest_testflight_build_number(version: "3.4.0")` to get the latest build number for a specific version on AppStore Connect. 

BTW: You should be able to see all the previous versions here:
https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/<AppID>/activity/ios/builds

However, there are some inconsistencies further down the line here:
the call to `get_builds` defaults to searching for the latest uploaded build for the given version, and NOT the highest build_number (version) that's uploaded.
https://github.com/fastlane/fastlane/blame/be55c12077fe91f4eecb64e8ee3a3fa4b8085048/fastlane/lib/fastlane/actions/app_store_build_number.rb#L52

I'm guessing this might be a slight of thought while writing that part, as you might end up in a constantly failing upload if you base your uploaded build_number on that. In our case, we had never uploaded build 0 or 1, and with the issues the last weeks ended up with uploading build_number 1, however, since that's the first response when sorting by `"-uploadedDate"` the next upload may never get uploaded as version 2 (build_number) is already uploaded. 

I'll open a separate issue for this, but it *might* be useful to be aware of.

**Comment by ramnac** [comment]
@janpio I am not using the latest fastlane rather I am using my own solution (which I posted above ) for getting the latest TestFlight build number. 

Which is working properly. I also extended that to accomodate expired builds as well. 

I am using max_by to determine the latest version as we cannot use sort by uploadeddate anymore.

**Comment by janpio** [comment]
Would be great if you could see if you can apply what you learned with your custom code back to fixing or improving fastlane - a PR would be very welcome.

**Comment by ramnac** [comment]
Sure @janpio will do that.

**Comment by ramnac** [comment]
@janpio I did the changes and I have raised a PR for this.

https://github.com/fastlane/fastlane/pull/14683

**Comment by ramnac** [comment]
@bsarrazin @mdavidsen @janpio 

Whoever facing this problem, can make use of my forked repo branch and let me know if this solves your problem.

**Comment by janpio** [comment]
👍 @ramnac 

(You can do so by replacing `gem 'fastlane'` with `gem 'fastlane', :git => 'https://github.com/ramnac/fastlane', :branch => 'master' and then running `bundle update`)

**Comment by bsarrazin** [comment]
@janpio @ramnac same issue:

Gemfile.lock:
```
GIT
  remote: https://github.com/ramnac/fastlane
  revision: e01c136f71b04512105d4458e2c94c08602055bd
  branch: master
```

output:
``` 
$ bundle exec fastlane run latest_testflight_build_number
[✔] 🚀
+------------------------------------------------+---------+------------------------------------------------------------+
|                                                     Used plugins                                                      |
+------------------------------------------------+---------+------------------------------------------------------------+
| Plugin                                         | Version | Action                                                     |
+------------------------------------------------+---------+------------------------------------------------------------+
| fastlane-plugin-appconfig                      | 0.3.0   | push_config pull_config                                    |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1   | setup_fragile_tests_for_rescan                             |
| fastlane-plugin-test_center                    | 3.6.3   | suppressed_tests suppress_tests suppress_tests_from_junit  |
|                                                |         | tests_from_xctestrun collate_test_result_bundles           |
|                                                |         | tests_from_junit multi_scan collate_html_reports           |
|                                                |         | collate_junit_reports collate_json_reports                 |
+------------------------------------------------+---------+------------------------------------------------------------+

[08:01:45]: --------------------------------------------
[08:01:45]: --- Step: latest_testflight_build_number ---
[08:01:45]: --------------------------------------------
[08:01:45]: Login to App Store Connect ([REDACTED]@[REDACTED].com)
Available session is not valid any more. Continuing with normal login.
[08:01:48]: Login successful
[08:01:49]: Fetching the latest build number for version 10.0.0
[08:01:51]: Latest upload for version 10.0.0 is build: 4
[08:01:51]: Result: 4

**Comment by ramnac** [comment]
@bsarrazin are you saying it still doesn’t work even when you use my forked repo?

Can you please give us more information to understand the problem ?

Isn’t the latest version is 10.0.0 for your app. Also isnt the latest build number is 4 ? 

What is the appstoreconnect latest version and latest build. It looks like it works fine.

**Comment by mdavidsen** [comment]
> @janpio I did the changes and I have raised a PR for this.
> 
> #14683

@ramnac Seems like the same PR i made for the exact same issue: https://github.com/fastlane/fastlane/pull/14670 vs https://github.com/fastlane/fastlane/pull/14683

But I see you also included a check for whether `Spaceship::Tunes::Application.find()` actually returns something. I'll close my PR in favor of yours

**Comment by ramnac** [comment]
Thank you @mdavidsen

**Comment by bsarrazin** [comment]
@ramnac correct, it still doesn't work with your forked repo.
We do not have a version 10.0.0 in the portal at all...

![2019-04-27 at 10 53 AM](https://user-images.githubusercontent.com/1077441/56851264-102caa80-68db-11e9-9a58-2a5d71cac51d.png)

Perhaps there was a typo at some point and version 10.0.0 was a thing in the past (before I joined the company) but I cannot tell from the Apple UI.

Regarding the build number: we are _way_ passed build 4, we're currently at build 180-something.


The action works as expected only if I give it the version. If I don't give it a version I get the `10.0.0 (4)` value. This started happening recently.

```ruby
latest_testflight_build_number().to_i # was working perfectly fine before
latest_testflight_build_number(version: version_number).to_i # now required otherwise I get 10.0.0 (4)
```

**Comment by ramnac** [comment]
@bsarrazin as you said you have 10.0.0 version. Which is why apple is sending that in the prerelease response and since we sort that with the version ( when no version is passed ) we are getting 10.0.0

Can you please check activity in appstoreconnect. I am sure you might see 10.0.0 there with the build 4.

So I don’t think this is an issue from fastlane end. This is how it should work.

**Comment by bsarrazin** [comment]
@ramnac \*gasp\* you're RIGHT!
I hadn't checked the activity tab! dammit!
Why wasn't it picking it up before? `10.0.0 (4)` dates all the way back to 2017...

Any known way to remove these? Otherwise, I might have to contact Apple...

**Comment by ramnac** [comment]
@bsarrazin Thanks.

though the version existed, why previous version of fastlane wouldn't have picked could be because of the sort - previously the sort was based on Uploaded date, But now it is based on the version. That is the reason.

Regarding the removal of the build / version, I am not sure - please contact Apple.
