### ISSUE TITLE
502 Bad Gateway Issue with spaceship login

### ISSUE THREAD

**Issue by adilmalik393** [fastlane/fastlane#14602]
I am running fastlane with docker container for creating WebPushId's and Certificates.  

### Here is my docker file.

```
FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y man vim ruby-full make g++
RUN gem install fastlane --version 2.119.0 --no-document
```

You can also checkout the image  `adilmalik393/spaceship:2.119.0`

### Docker run command

`docker run --name spaceship -d -t adilmalik393/spaceship:2.119.0 bash`

## What's weird 

So when I am running container on my local machine and executing below command to login to Apple Developer Portal, Its working absolutely fine. But when I am running on any digitalocean droplet. Its giving me `502 Gateway Error`. I don't know whats wrong. Please let me know what else do you need from me to figure out what's wrong. 

`require "spaceship"`
`Spaceship::Portal.login("user@domain.com", "*******")`

```
Spaceship::Tunes::Error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>Apple</center>
</body>
</html>

from /var/lib/gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/client.rb:510:in `send_shared_login_request'
from /var/lib/gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
from /var/lib/gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/client.rb:770:in `do_login'
from /var/lib/gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/client.rb:384:in `login'
from /var/lib/gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/client.rb:346:in `login'
from /var/lib/gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
from (irb):4
from /usr/bin/irb:11:in `<main>'
```

**Comment by adilmalik393** [comment]
#### UPDATE
I just launched an ec2-instance on aws and its working fine over there. I think there is some network issues. Apple is not accepting calls from digital ocean droplets.

**Comment by janpio** [comment]
Not really anything we can do I guess, so closing. 

Thanks for reporting anyway!
