### ISSUE TITLE
Getting rid of that 2FA on my CI Server when use match to manage certificates and profiles

### ISSUE THREAD

**Issue by yuanhh90** [fastlane/fastlane#14613]
### Question Checklist 

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

managing certificates and profiles without 2FA

#### Question Description
I use match to manage certificates and profiles, How I can get rid of that 2FA on my CI Server?

**Comment by janpio** [comment]
What output are you getting exactly that requires 2FA?

**Comment by salmanasiddiqui** [comment]
@yuanhh90 imo the easiest way to get around that 2FA thing is to invite a new user to your apple team as Admin and use that user on CI. 2FA is only required for users who are Account Holders for any team.

**Comment by yuanhh90** [comment]
> 11:23:24 [11:23:24]: Verifying that the certificate and profile are still valid on the Dev Portal...
11:23:26 Two-factor Authentication (6 digits code) is enabled for account 'user@email.com'
11:23:26 More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915
11:23:26 
11:23:26 If you're running this in a non-interactive session (e.g. server or CI)
11:23:26 check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
11:23:26 
11:23:26 (Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)
11:23:26 Please enter the 6 digit code:
11:23:26 +------------------+----------+
11:23:26 |        [33mLane Context[0m         |
11:23:26 +------------------+----------+
11:23:26 | DEFAULT_PLATFORM | ios      |
11:23:26 | ENVIRONMENT      | jenkins  |
11:23:26 | PLATFORM_NAME    | ios      |
11:23:26 | LANE_NAME        | ios beta |
11:23:26 | BUILD_NUMBER     | 12       |
11:23:26 | VERSION_NUMBER   | 4.0.8    |
11:23:26 +------------------+----------+
11:23:26 
11:23:26 +------+--------------------------+-------------+
11:23:26 |               [32mfastlane summary[0m                |
11:23:26 +------+--------------------------+-------------+
11:23:26 | Step | Action                   | Time (in s) |
11:23:26 +------+--------------------------+-------------+
11:23:26 | 1    | default_platform         | 0           |
11:23:26 | 2    | Switch to ios build lane | 0           |
11:23:26 | 3    | increment_build_number   | 1           |
11:23:26 | 4    | get_version_number       | 1           |
11:23:26 | 5    | get_build_number         | 0           |
11:23:26 | 💥   | [31mmatch[0m                    | 5           |
11:23:26 +------+--------------------------+-------------+
11:23:26 
11:23:26 [11:23:26]: [31mfastlane finished with errors[0m
11:23:26 
11:23:26 Looking for related GitHub issues on fastlane/fastlane...
11:23:26 
11:23:30 ➡️  [33mTwo factor sessions only lasting a few hours / "Session loaded from environment variable is not valid. Continuing with normal login."[0m
11:23:30     https://github.com/fastlane/fastlane/issues/13833 [[32mclosed[0m] 25 💬
11:23:30     5 days ago
11:23:30 
11:23:30 ➡️  [33mTwo factor authentication fails after 2.106.0[0m
11:23:30     https://github.com/fastlane/fastlane/issues/13603 [[32mclosed[0m] 14 💬
11:23:30     24 Feb 2019
11:23:30 
11:23:30 ➡️  [33mFastlane match template_name[0m
11:23:30     https://github.com/fastlane/fastlane/issues/11881 [[32mclosed[0m] 6 💬
11:23:30     22 May 2018
11:23:30 
11:23:30 and 2 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60strip%27%20for%20nil%0ADid%20you%20mean%3F%20%20String&type=Issues&utf8=✓
11:23:30 
11:23:30 🔗  You can ⌘ + double-click on links to open them directly in your browser.
11:23:30 /Users/macpro/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace': [31m[!] undefined method `strip' for nil:NilClass (NoMethodError)
11:23:30 Did you mean?  String[0m

That is output for match. The fastlane version is latest version - 2.120.0. It is doable without session before that must require 2FA. Has any way to get rid of that using the way that like uploading app?Thanks!

**Comment by yuanhh90** [comment]
Year, Thanks! @salmanasiddiqui ,  I'll try this way! But I'm curious that this is bug by use Admin Account without Account Holders. Then Apple could fix this later?

**Comment by salmanasiddiqui** [comment]
@yuanhh90 no this is not a bug, the actual Apple announcement (atleast the email we received from apple) mentions that 2FA is only being enforced on users who are Account Holders.

**Comment by yuanhh90** [comment]
Thanks for give this information!

**Comment by matelo** [comment]
@yuanhh90 try this (section about CI):
https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

**Comment by jamesrogers93** [comment]
Adding an admin user to the Apple team for match requires it to also have a paid developer account right?

**Comment by janpio** [comment]
Can you manually manage certificates without a paid developer account at all?

**Comment by jamesrogers93** [comment]
"If you’re enrolled as an organization, you have the option of adding additional members to your team" - https://developer.apple.com/support/roles/

You need a paid license, but I think you may be able to do it with an additional team member without any additional cost. So I think you can do this with one license as long as you're registered as an organisation and not an individual license. I'm not sure though

**Comment by acrabb** [comment]
@yuanhh90 did you see and go through this part?
> 11:23:26 If you're running this in a non-interactive session (e.g. server or CI)
> 11:23:26 check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

**Comment by yuanhh90** [comment]
@acrabb  I go through that part with session, but the session is only valid for up to a month. So i used another account to replace the user  who are Account Holders.

> An Apple ID session is only valid for up to a month, meaning you'll have to generate a new session every month. Usually you'd only know about it when your build starts failing.
