### ISSUE TITLE
Should wait_for_uploaded_build really be deprecated?

### ISSUE THREAD

**Issue by simonbengtsson** [fastlane/fastlane#14619]
In the docs the `wait_for_uploaded_build` option is listed as deprecated since you can use the app store connect API to get info from the ipa file.

> DEPRECATED! No longer needed with the transition over to the App Store Connect API - Use version info from uploaded ipa file to determine what build to use for distribution. If set to false, latest processing or any latest build will be used

We use this option to be able to download dsyms and upload them to Crashlytics after the build has been processed. Is this use case covered in some other way or does this mean the option should not be deprecated?

**Comment by snatchev** [comment]
@simonbengtsson the `wait_for_uploaded_build` option was introduced to ensure that we got the expected build from the API. Previously, builds would disappear from the response during some kind of state transition. This is no longer the case and the API responds with the full expected list.

This change should have no other side-effects, and should be unrelated to downloading dsyms. Could you please explain your workflow so I can understand it better?

**Comment by simonbengtsson** [comment]
Our workflow is something like this:
```
    build_ios_app
    upload_to_testflight(
      wait_for_uploaded_build: true
    )
    download_dsyms
    upload_symbols_to_crashlytics
```

Basically we need the script to wait until the build is processed so we can download the dsyms. But it seems that I might be missing something here?

**Comment by salmanasiddiqui** [comment]
@simonbengtsson `upload_to_testflight` always waits for the uploaded build unless `skip_waiting_for_build_processing=true`.

Is that not working as expected?

**Comment by simonbengtsson** [comment]
Then I was just confused. Removed that option from our config now. Thanks for clarifying!
