### ISSUE TITLE
Fastlane deliver download_metadata not downloading screenshots?

### ISSUE THREAD

**Issue by steveharman** [fastlane/fastlane#14624]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

"fastlane deliver"

no

no

#### Question Description

i've been using fastlane for years (thank you!) but only just started using `deliver`.

after reading the docs I launched `fastlane deliver download_metadata` and received a directory full of metadata for my specified Store-released iOS app.   I have a directory full of relevant data, review information and so on.

i also have a "screenshots" directory too, but it's empty.    is that expected?  i couldn't find any arguments to `deliver download_metadata` where i needed to specify that i wanted to download my screens from the App Store.   Screenshot attached

Thanks.

![klassar](https://user-images.githubusercontent.com/12557929/56374561-6161dd80-61fb-11e9-9355-6da12ee062c6.png)

**Comment by janpio** [comment]
There is a separate command line command `fastlane deliver download_screenshots`: https://docs.fastlane.tools/actions/deliver/#usage Let us know if this downloaded the screenshots as expected.
