### ISSUE TITLE
latest_testflight_build_number returns always 0

### ISSUE THREAD

**Issue by UPCman** [fastlane/fastlane#14621]
1. Using this code on Fastfile:
```
    build_number = latest_testflight_build_number(
      version: 2.3.1,
      team_id: XXXXXXX,
      initial_build_number: 0
    )

```

2. Always I get build number 0.

```
[14:32:08]: --------------------------------------------
[14:32:08]: --- Step: latest_testflight_build_number ---
[14:32:08]: --------------------------------------------
[14:32:09]: Login to App Store Connect XXXXXXXXXXXXXX
[14:32:11]: Login successful
[14:32:12]: Fetching the latest build number for version 2.3.1
[14:32:13]: Latest upload for version 2.3.1 is build: 0

```

I'm using version 2.119.0 of Fastlane. 
With the same code, it worked until a few weeks ago. Since then it always fails with the same result. 
The result is the same with or without any active builds numbers on Testflight.

**Checklist**
- [x]  I read the similar issues. Closed as solved, but i have not exactly the same issue.
- [x]  Change the version number.
- [x]  Try on another project with the same Fastfile.

**Comment by janpio** [comment]
Please upgrade to the latest version of fastlane and report if you still have issues. The Testflight stuff was greatly rewritten there because Apple changed a lot on their side, so it is expected that you have to use fastlane 2.120.0.

**Comment by janpio** [comment]
Hey @UPCman, could you please check if this problem still exists with a current release of fastlane? We tried to fix a lot of these "error 410 gone" errors, and now need your feedback if this covered yours as well. Thanks!

**Comment by UPCman** [comment]
I update my fastlane to v2.120.0 and the issue is solved.
Thanks!!

**Comment by jakubpetrik** [comment]
@janpio happening also on `2.121.1`

**Comment by janpio** [comment]
Awesome 🥇 All credit goes to @joshdholtz who did a great job fixing this mess.
