### ISSUE TITLE
[Bug][Plugin][appcenter][Fastfile.swift] appcenter_upload method not found

### ISSUE THREAD

**Issue by AnandWalvekar** [fastlane/fastlane#14632]
**Background**
I am using Fastfile.swift (which is in beta) and not sure if plugging are supported

**Steps Followed**
- fastlane add_plugin appcenter
- bundle exec fastlane install_plugins
- opened {project_directory}/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj & verified Autogenerated Fastlane.swift to see if **appcenter_upload** method autogenerated.
- Confirmed no such method found

**Issue**
- Since **appcenter_upload**  method is not generated in Fastlane.swift, I am unable invoke **appcenter_upload** from Fastfile.swift to upload build to appcenter

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by AnandWalvekar** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                                             |
| --------------------------- | ------------------------------------------------------------------------------------------------- |
| OS                          | 10.14.4                                                                                           |
| Ruby                        | 2.5.0                                                                                             |
| Bundler?                    | true                                                                                              |
| Git                         | git version 2.15.1                                                                                |
| Installation Source         | ~/iCloud-Drive-Archive/Desktop/Project_Name/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.14.4 (18E226)                                                                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib                                                                  |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                                                        |
| Is contained                | false                                                                                             |
| Is homebrew                 | false                                                                                             |
| Is installed via Fabric.app | false                                                                                             |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                       |
| Xcode Version               | 10.2                                                                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.104.0 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 0.2.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| dotenv                    | 2.5.0        |
| osx_keychain              | 1.0.2        |
| cocoapods-keys            | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.2        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appcenter | 0.2.1        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| slather                   | 2.4.5        |
| xcode-install             | 2.4.4        |
</details>


*generated on:* **2019-04-22**
</details>

**Comment by AnandWalvekar** [comment]
Any updates?

**Comment by janpio** [comment]
As far as I know plugins are not supported for Fastlane.swift yet.
