### ISSUE TITLE
Boarding Heroku - Test Flight User Signup Form - Error 410 Gone

### ISSUE THREAD

**Issue by cyuill** [fastlane/fastlane#14635]
Sorry if this is not the right place for this.

Am using Boarding with Heroku for easy test flight signup, the app has built ok and the form is being displayed on a web site. 

When signing up with a test apple id I am getting the following error...

`Something went wrong, please contact the application owner: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 410 Gone</title> </head> <body><h2>HTTP ERROR 410</h2> <p>Problem accessing /v2/providers/119996938/apps/1176200778/testers. Reason: <pre> Gone</pre></p> </body> </html>`

Is this related?

**Comment by joshdholtz** [comment]
@cyuill Made a fix for this over at https://github.com/fastlane/boarding/pull/246 😊

**Comment by cyuill** [comment]
Awesome! Thank you!!! Sorry for the total noob question but how do I implement the fix? When I use my existing Heroku build I still get the same error. Should I rebuild / deploy new instance?

**Comment by janpio** [comment]
That is just a Pull Request for now, it has to be merged to become part of `boarding`.
