### ISSUE TITLE
upload to testflight failed 

### ISSUE THREAD

**Issue by hGhostD** [fastlane/fastlane#14633]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Please open a new issue where you include the information the bug report template asks for, otherwise there is no way we can understand the problem and possibly help you.
