### ISSUE TITLE
[pilot] Removing Testflight Users fails

### ISSUE THREAD

**Issue by Jerrot** [fastlane/fastlane#14645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
While trying to remove a TestFlight user via `fastlane pilot`, HTML is returned to the console stating an internal server error. This only seems to happen when the given TestFlight User actually exists, otherwise it just returns the correct error message. I updated to the latest fastlane version right before trying this, it might be coincidence though.

##### Command executed
fastlane pilot remove [email address of existing testflight user]

##### Complete output when running fastlane, including the stack trace and command used
 

<details>
  <pre>[✔] 🚀
[12:25:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:25:55]: Login to App Store Connect (xxxxx@xxxxx.xxxxx)
[12:25:56]: Login successful
[12:26:21]: 785: unexpected token at '<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>

<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>'

[!] Some operations failed: 785: unexpected token at '<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>

<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>'</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.14.4                                            |
| Ruby                        | 2.5.0                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.20.1 (Apple Git-117)                 |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane               |
| Host                        | Mac OS X 10.14.4 (18E226)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                        |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-10.2.1.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.0 | ✅ Up-To-Date  |

*generated on:* **2019-04-23**
</details>

**Comment by janpio** [comment]
Can you have a look at your spaceship logfiles at `/tmp/spaceship*.log` and see what request gets this response? That would be really helpful.

**Comment by Jerrot** [comment]
This is what I can see, I only replaced the given e-mail address for privacy here:
```
INFO  [14:00:52]: >> GET providers/347643/apps/454415640/testers?order=asc&search=test%40test.test&sort=status: [undefined body]
WARN  [14:00:54]: Internal Server Error received: 'Faraday::ParsingError', '785: unexpected token at '<!DOCTYPE html><html lang="en">
```

**Comment by janpio** [comment]
That's perfect @Jerrot, now we know the call to get/search testers is failing for some reason and we will have to see if there was a change there. Thanks.

**Comment by prnewman** [comment]
I get this response when I run `fastlane pilot remove user@example.com` (I've replaced the valid email address):

`[10:09:27]: Could not remove user@example.com from app:`
```<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>

**Comment by tbodt** [comment]
I get this in the log:

```
DEBUG [14:46:56]: << POST providers/[redacted]/apps/[redacted]/deleteTesters: 404 <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>
```

**Comment by prnewman** [comment]
This is still happening in fastlane 2.123.0. Any updates?

**Comment by fireearl** [comment]
We would like to clean up our testflight testers and this bug is blocking us. Would be nice if it could be fixed.

**Comment by tbodt** [comment]
FYI I was able to delete a batch of testflight testers using the old "open network inspector, delete one tester, right click and copy as curl, replace one tester with 2000" trick.
