### ISSUE TITLE
latest_testflight_build_number fails with "Could not find a build number for version"

### ISSUE THREAD

**Issue by marlonchalegre** [fastlane/fastlane#14649]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In the latest version of Fastlane (2.121.0) the latest_testflight_build_number does not show build number when the version does not yet exist in testflight.

In the version 2.108.0, when latest_testflight_build_number were called and the version does not exist in TestFlight, the latest_testflight_build_number returned the initial build number.

The latest_testflight_build_number  fails with the message:

[!] Could not find a build number for version x.y.z

**Comment by marlonchalegre** [comment]
This problem appears to be introduced in this commit 78fd2b1b5e5414251cd8c08c042f4af36d9ca70e 

Could we use the solution provided by gregersn in #14650?

**Comment by joshdholtz** [comment]
Looking into this now!
