### ISSUE TITLE
[snapshot] iPad Pro (12.9-inch) (3rd generation) simulators never detected

### ISSUE THREAD

**Issue by AndreiTich** [fastlane/fastlane#14656]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
iPad Pro (12.9-inch) (3rd generation) simulators are not detected by Fastlane Snapshot. Adding, renaming, and removing 3rd gen iPad devices does not fix the issue. Other devices can be added and removed with no issues, and fast lane always detects them.

##### Command executed
fastlane snapshot

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> USER$ fastlane snapshot
[✔] 🚀 
[11:09:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:10:00]: Successfully loaded '/Users/USER/Documents/git/ios/Project/fastlane/Snapfile' 📄

+----------------------------+-----------------------------------------------------------------------------+
|                                Detected Values from './fastlane/Snapfile'                                |
+----------------------------+-----------------------------------------------------------------------------+
| devices                    | ["iPhone 8 Plus", "iPhone Xs Max", "iPad Pro (12.9-inch) (3rd generation)"] |
| languages                  | ["en-US"]                                                                   |
| scheme                     | TestsForScreenshots                                                   |
| output_directory           | ./screenshots                                                               |
| clear_previous_screenshots | true                                                                        |
| erase_simulator            | true                                                                        |
| localize_simulator         | true                                                                        |
| concurrent_simulators      | false                                                                       |
+----------------------------+-----------------------------------------------------------------------------+

[11:10:01]: Error setting value '["iPhone 8 Plus", "iPhone Xs Max", "iPad Pro (12.9-inch) (3rd generation)"]' for option 'devices'

[!] Device 'iPad Pro (12.9-inch) (3rd generation)' not in list of available simulators 'iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, thisIsanIphone6s, iPhone 6s Plus, iPhone 7, iPhone 7 Plus, iPhone 8, iPhone 8 Plus, iPhone SE, iPhone X, iPhone Xʀ, iPhone Xs, iPhone 10s Max, iPhone Xs Max, iPad Air, iPad Air 2, iPad (5th generation), iPad Pro (9.7-inch), iPad Pro (12.9-inch), iPad Pro (10.5-inch), iPad (6th generation), Apple TV, Apple TV 4K, Apple TV 4K (at 1080p), Apple Watch Series 2 - 38mm, Apple Watch Series 2 - 42mm, Apple Watch Series 3 - 38mm, Apple Watch Series 3 - 42mm, Apple Watch Series 4 - 40mm, Apple Watch Series 4 - 44mm'
 </pre>
</details>

### Environment

<details>
  <pre> [✔] 🚀 
[11:19:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:19:34]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1 (Apple Git-112)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.6       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-04-23**
</details>
</pre>
</details>

**Comment by janpio** [comment]
What is your `iPad Pro (12.9-inch) (3rd generation)` simulator currently called?
What do you get when you run `xcrun simctl list devices` in the terminal?

**Comment by AndreiTich** [comment]
It is currently named the default name, and I have tried recreating it with other names. Running the list command, the issue may have to something to do with the device profile not being found? output is below.

```
== Devices ==
-- iOS 12.1 --
    iPhone 5s (DE217DD1-B0C7-44E4-A440-335E6ECEAF77) (Shutdown) 
    iPhone 6 (134208D1-9AA2-439F-8A2B-567E115DA611) (Shutdown) 
    iPhone 6 Plus (F9F10AAC-68DD-451B-9ECA-9A59B536D9FD) (Shutdown) 
    iPhone 6s (91BD4D88-41E1-49D1-91A5-FFA24B37869C) (Shutdown) 
    thisIsanIphone6s (A38D1214-5DF5-4358-9E51-30E0577057DB) (Shutdown) 
    iPhone 6s Plus (E4AB0642-A454-4690-AC48-93FFBC877B58) (Shutdown) 
    iPhone 7 (07DA53D6-564E-49BE-A31B-A1B81AA3B0D9) (Shutdown) 
    iPhone 7 Plus (5498E925-4BA4-4233-B7CB-6934F2061E0D) (Shutdown) 
    iPhone 8 (C73D6D52-2A9C-49BD-B262-E540520BDAB0) (Shutdown) 
    iPhone 8 Plus (CD810BCE-0CE3-46D6-9F06-6A602CB4D2D2) (Shutdown) 
    iPhone SE (DBFA2D97-E6B3-4405-8216-3D41B778E866) (Shutdown) 
    iPhone X (453D0E9B-2238-4923-B3AB-93C05860F051) (Shutdown) 
    iPhone Xʀ (2914E290-C6C8-4C0C-8A92-6C2150DE5619) (Shutdown) 
    iPhone Xs (92D892E4-4A74-4253-94D1-3F88E57AACF4) (Shutdown) 
    iPhone 10s Max (A228B906-557A-4714-93CB-F30602FCED54) (Shutdown) 
    iPhone Xs Max (88931C04-4EB3-4C44-B873-793BE6EF358B) (Shutdown) 
    iPad Air (09658F5B-CFD4-4DEA-BD5E-4B46DC2127D9) (Shutdown) 
    iPad Air 2 (6AB53F71-AAE1-40F5-ADAB-D8A1F11FD044) (Shutdown) 
    iPad (5th generation) (A78B5D0E-6298-4DCF-9FEF-978229EDAC73) (Shutdown) 
    iPad Pro (9.7-inch) (6DE67CB7-5947-40E4-BB6D-ACB375569021) (Shutdown) 
    iPad Pro (12.9-inch) (8137CE3E-5F15-4CDC-8EBC-73DFEBE7EBFC) (Shutdown) 
    iPad Pro (10.5-inch) (1BC45E20-35DC-407B-86E3-A83EF38F5342) (Shutdown) 
    iPad (6th generation) (2950A7D9-1C1F-4C4A-B977-27F4E6DBEEC0) (Shutdown) 
    iPad Pro (11-inch) (4054D106-2F3B-4C5B-97AE-123B5E447190) (Shutdown) (unavailable, device type profile not found)
    iPad Pro (12.9-inch) (3rd generation) (F5147439-A0A3-4BF9-94D9-AA345FBA445D) (Shutdown) (unavailable, device type profile not found)
```

**Comment by janpio** [comment]
Yep, that sounds reasonable: snapshot removes all simulators with `unavailable`. But no idea what "device type profile not found" actually means :/

**Comment by AndreiTich** [comment]
This issue had something to do with my simulator setup because I have several versions of Xcode installed at once. To fix it I deleted the unavailable simulators

`xcrun simctl delete unavailable`

Then made sure simctl was pointing to the intended version of Xcode

`sudo xcode-select -s /Applications/Xcode_10.1`

and re-added the simulators in Xcode. This ensured snapshot can see all visible simulators. Still not sure what it means for a simulator be be "unavailable, device type profile not found", but the above process fixes the issue.
