### ISSUE TITLE
Upload to SMB plugin

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14664]
#### Motivation Behind Feature
After archiving the build it might be needed to upload it to the external server using the SMB protocol.

#### Feature Description

1. Have an option of executing simple "upload to smb" action and pass a file(s) to be uploaded.
2. Action should work with protected servers, requiring username and password.

#### Alternatives or Workarounds

Current workaround is to use a custom-written ruby script.

**Comment by janpio** [comment]
Do you already have that custom ruby script, maybe already used in a lane or even as a custom action? Then it would be pretty simple to convert that in a tiny fastlane plugin: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by richardtop** [comment]
I don't have a custom ruby script, however, I've seen a couple of ruby libraries for the SMB support.

Currently I use a shell script executing inside of `sh()` action of the Fastlane

**Comment by janpio** [comment]
It would be awesome if you would take a shot at implementing this. Usually it's pretty simple to get going with existing ruby gems, so you shouldn't hit too much trouble there. Again: If you need any help or pointers, just respond to this issue.

**Comment by richardtop** [comment]
Unfortunately, I don't have time for implementing it and the shell script works just fine.
I first actually thought about making a plugin, however, didn't find the `smb` client supporting macOS. The way I implemented it in my shell script is to mount smb drive using `mount_smbfs`.

**Comment by janpio** [comment]
Could you maybe post your shell script here? If someone actually googles for "fastlane smb" I am quite sure this issue will come up.

**Comment by richardtop** [comment]
Here it is:
```Shell
      mkdir ios
      mount_smbfs //user:$FASTLANE_USER_PASSWORD@server.com/ios ios
      cp AppName.ipa ios/AppName.ipa
      rm -rf AppName.app
      cp -a DerivedData/Build/Products/Debug-iphonesimulator/AppName.app AppName.app
      ditto -c -k --sequesterRsrc --keepParent AppName.app AppName.zip
      cp AppName.zip ios/AppName.zip
      diskutil unmount force ios
```
