### ISSUE TITLE
uninitialized constant Spaceship::Pathname (NameError) after upgrading from 2.120.0 to 2.121.1

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#14661]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

 After upgrading Fastlane from version 2.120.0 to 2.121.1 using the command
```gem install fastlane -NV```, I am now seeing the error:
```.../.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/module.rb:2:in `<module:Spaceship>': uninitialized constant Spaceship::Pathname (NameError)```

#### Question Description

We have been using simple ruby scripts to use Spaceship for a while now, the template of such a script is as below: 
```
require "spaceship"
Spaceship::Tunes.login(username, password)
```

Today after upgrading from version 2.120.0 to 2.121.1, all our ruby scripts that require spaceship are failing with the following error:
```
/users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/module.rb:2:in `<module:Spaceship>': uninitialized constant Spaceship::Pathname (NameError)
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/module.rb:1:in `<top (required)>'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/display_family.rb:1:in `require_relative'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/display_family.rb:1:in `<top (required)>'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/du/du_client.rb:2:in `require_relative'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/du/du_client.rb:2:in `<top (required)>'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/tunes_client.rb:3:in `require_relative'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/tunes_client.rb:3:in `<top (required)>'
	from /users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.121.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:2:in `require_relative'
	from /users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.121.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:2:in `<top (required)>'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/client.rb:892:in `<top (required)>'
	from /users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.121.1/spaceship/lib/spaceship.rb:3:in `require_relative'
	from /users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.121.1/spaceship/lib/spaceship.rb:3:in `<top (required)>'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from test.rb:5:in `<main>'
```

We have upgraded Fastlane dozens of times in the past, this is the first time we see this issue. 

I am not too familiar with Ruby, therefore I apologize if this question is too simplistic.

**Comment by sn3ek** [comment]
Same here. The problem was introduced 2 days ago with this file:

https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/display_family.rb#L1

I do not know how to fix it, but this might help?

**Comment by aszentpeteri** [comment]
Same error here. We rolled back to 2.120.0 until it's solved.

Also as far as I understand the error comes from here:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/module.rb

Since the Pathname variable does not exist or contain any data? Maybe some file is missing from the commit introducing this file?

**Comment by janpio** [comment]
Thanks for reporting, this seems to be a regression. Somehow a `require 'pathname'` seems to have gotten lost in the code path to the spaceship module - but I am not sure yet how.

**Comment by liamnichols** [comment]
Oh yikes! Sorry about this 😞 Is it as simple as adding `require 'pathname'` into `module.rb`? I can stick up a PR if it helps? 

I'm not too knowledgable on import structures in ruby but I've just realised that I don't import `display_family` in `tunes.rb`.. Is that related?

**Comment by janpio** [comment]
I have no idea, I hope somebody with more ruby experience will be able to help out here.
Can you go ahead and try and create a PR?

**Comment by viktorasl** [comment]
Yeah, probably it's best to add
```ruby
require 'fastlane_core/helper'
```
as in other `module.rb` files (in other modules).
`helper.rb` includes `pathname`

**Comment by viktorasl** [comment]
There is one more file `spaceship/lib/spaceship/tunes/language_converter.rb` which relatively includes `module.rb` and would produce the same error if used directly from `spaceship` module (if publicly accessible).

**Comment by liamnichols** [comment]
I copied `language_converter.rb` assuming that the require it used was enough but apparently I was wrong 🙈 

Does that helper need importing in `module.rb` to fix the issue? 

I tried to reproduce the issue in a simple script but I'm unable to do so so I don't want to make a PR without being sure that I can 1) reproduce the issue and 2) I've actually fixed it. Can somebody help with replication?

**Comment by joshdholtz** [comment]
I also can't reproduce this error with a `Gemfile`. It seems like bundler ends up requiring the correct stuff that everything needs but without bundler the proper requires aren't happening. Also looking into over here as well!

**Comment by viktorasl** [comment]
I managed to reproduce. I did not use bundler and installed gem directly.
```
/Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/module.rb:2:in `<module:Spaceship>': uninitialized constant Spaceship::Pathname (NameError)
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/module.rb:1:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/display_family.rb:1:in `require_relative'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/display_family.rb:1:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/du/du_client.rb:2:in `require_relative'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/du/du_client.rb:2:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/tunes_client.rb:3:in `require_relative'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/tunes/tunes_client.rb:3:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:2:in `require_relative'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:2:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship/client.rb:892:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship.rb:3:in `require_relative'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.121.1/spaceship/lib/spaceship.rb:3:in `<top (required)>'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/viktoraslaukevicius/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from test.rb:1:in `<main>'
```

**Comment by joshdholtz** [comment]
I got a PR coming for this 💪

**Comment by liamnichols** [comment]
@joshdholtz, @viktorasl Thank you! 🙇🙇🙇🙇
