### ISSUE TITLE
[action] update_app_identifier fails to search for curly brace variables in Info.plist

### ISSUE THREAD

**Issue by macblazer** [fastlane/fastlane#14672]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The update_app_identifier action does not properly detect all uses of PRODUCT_BUNDLE_IDENTIFIER in the Info.plist file.  Older Xcode projects and many examples show curly braces being used for variables inside the Info.plist file like ${PRODUCT_BUNDLE_IDENTIFIER}.  update_app_identifier only searches very specifically for parenthesis like $(PRODUCT_BUNDLE_IDENTIFIER) and fails to find the curly brace instance of this variable.

This leads to codesigning issues and other hard to diagnose problems because the Info.plist curly brace variable has been replaced with the new bundle identifier, but the project.pbxproj file still has instances of the old bundle identifier.  Xcode gets very confused as to what the actual bundle identifier is.

##### Command executed
bundle exec fastlane change_bundle_id

##### Complete output when running fastlane, including the stack trace and command used

This is the failed example output where the Info.plist is using curly braces:

<details>
  <pre> 16:37:49 ExampleApp$ defaults read `pwd`/ExampleApp/Info.plist CFBundleIdentifier
${PRODUCT_BUNDLE_IDENTIFIER}
16:38:16 ExampleApp$ fgrep PRODUCT_BUNDLE_IDENTIFIER ExampleApp.xcodeproj/project.pbxproj 
				PRODUCT_BUNDLE_IDENTIFIER = com.example.original.ExampleApp;
				PRODUCT_BUNDLE_IDENTIFIER = com.example.original.ExampleApp;
16:38:19 ExampleApp$ bundle exec fastlane change_bundle_id
[✔] 🚀 
[16:38:44]: ------------------------------
[16:38:44]: --- Step: default_platform ---
[16:38:44]: ------------------------------
[16:38:44]: Driving the lane 'ios change_bundle_id' 🚀
[16:38:44]: -----------------------------------
[16:38:44]: --- Step: update_app_identifier ---
[16:38:44]: -----------------------------------
[16:38:44]: Updated ExampleApp/Info.plist 💾.

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | default_platform      | 0           |
| 2    | update_app_identifier | 0           |
+------+-----------------------+-------------+

[16:38:44]: fastlane.tools finished successfully 🎉
16:38:44 ExampleApp$ defaults read `pwd`/ExampleApp/Info.plist CFBundleIdentifier
com.example.changed
16:38:48 ExampleApp$ fgrep PRODUCT_BUNDLE_IDENTIFIER ExampleApp.xcodeproj/project.pbxproj 
				PRODUCT_BUNDLE_IDENTIFIER = com.example.original.ExampleApp;
				PRODUCT_BUNDLE_IDENTIFIER = com.example.original.ExampleApp;
16:38:51 ExampleApp$ </pre>
</details>

This is the correct output where the Info.plist is using parenthesis:

<details>
	<pre> 16:38:51 ExampleApp → defaults read `pwd`/ExampleApp/Info.plist CFBundleIdentifier
$(PRODUCT_BUNDLE_IDENTIFIER)
16:40:54 ExampleApp$ fgrep PRODUCT_BUNDLE_IDENTIFIER ExampleApp.xcodeproj/project.pbxproj 
				PRODUCT_BUNDLE_IDENTIFIER = com.example.original.ExampleApp;
				PRODUCT_BUNDLE_IDENTIFIER = com.example.original.ExampleApp;
16:40:58 ExampleApp$ bundle exec fastlane change_bundle_id
[✔] 🚀 
[16:41:04]: ------------------------------
[16:41:04]: --- Step: default_platform ---
[16:41:04]: ------------------------------
[16:41:04]: Driving the lane 'ios change_bundle_id' 🚀
[16:41:04]: -----------------------------------
[16:41:04]: --- Step: update_app_identifier ---
[16:41:04]: -----------------------------------
[16:41:04]: Updated ExampleApp.xcodeproj 💾.

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | default_platform      | 0           |
| 2    | update_app_identifier | 0           |
+------+-----------------------+-------------+

[16:41:04]: fastlane.tools finished successfully 🎉
16:41:05 ExampleApp$ defaults read `pwd`/ExampleApp/Info.plist CFBundleIdentifier
$(PRODUCT_BUNDLE_IDENTIFIER)
16:41:08 ExampleApp$ fgrep PRODUCT_BUNDLE_IDENTIFIER ExampleApp.xcodeproj/project.pbxproj 
				PRODUCT_BUNDLE_IDENTIFIER = com.example.changed;
				PRODUCT_BUNDLE_IDENTIFIER = com.example.changed;
16:41:10 ExampleApp$ </pre>
</details>

### Environment

  <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :change_bundle_id do
    update_app_identifier(
      xcodeproj: "ExampleApp.xcodeproj",
      app_identifier: "com.example.changed",
      plist_path: "ExampleApp/Info.plist"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.2        |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.2        |
| date                      | 2.0.0        |
| fileutils                 | 1.2.0        |
| ipaddr                    | 1.2.2        |
| psych                     | 3.1.0        |
</details>

*generated on:* **2019-04-24**
</details>

**Comment by mollyIV** [comment]
👋 @macblazer , thanks for reporting the issue!

You did mention that:

> Older Xcode projects and many examples show curly braces being used for variables inside the Info.plist file like ${PRODUCT_BUNDLE_IDENTIFIER}.

Do you know since what Xcode version Apple switched from curly braces to $(...)? 🤔 

I was looking for it, but just found [this resource](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-SW4) where they are showing $(...). 

 I also checked GNU documentation and according to [Basics of Variable References](https://www.gnu.org/software/make/manual/html_node/Reference.html#Reference):

> To substitute a variable’s value, write a dollar sign followed by the name of the variable in parentheses or braces: either ‘$(foo)’ or ‘${foo}’ is a valid reference to the variable foo.

So I guess it's gonna be fine to support both 👍 I will have a look at it 👀

**Comment by mollyIV** [comment]
Here we go https://github.com/fastlane/fastlane/pull/14687 🎁 

@macblazer feel free to test my changes. All you need to do is to change your `Gemfile`

```
gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'mollyIV-fix-action-update-app-identifier-curly-brackets'
```

Thanks 🙇 🙇
