### ISSUE TITLE
sync_code_signing not able to find newly created certificate when nested in a lane

### ISSUE THREAD

**Issue by salmanasiddiqui** [fastlane/fastlane#14671]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a lane `certs_and_profile` which calls `sync_code_signing` action. The lane works fine  when called from terminal as
```
bundle exec fastlane certs_and_profile
```
But if I call `certs_and_profile` lane from another lane `initialize_app` then it always fails to find the newly created certificate 😞 

Another thing is, that `sync_code_signing` isn't able to find certificate if there are two certificates with same *name* in keychain.

##### Command executed

```
bundle exec fastlane initialize_app
```

Fastfile#lanes:
```
lane :initialize_app do |options|
  create_app_online(
      username: <apple_username>,
      app_identifier: <app_id>,
      app_name: "Test - Preview",
      company_name: <itc_team_name>,
      app_version: '14671',
      sku: <app_id>,
      team_id: <portal_team_id>,
      itc_team_name: <itc_team_name>,
      enable_services: {
          game_center: 'on',
          in_app_purchase: 'on',
          push_notification: 'on'
      }
  )
  certs_and_profile(
      app_id: <app_id>,
      portal_team_id: <portal_team_id>,
  )
end

lane :certs_and_profile do |options|
  UI.abort_with_message!('env var MATCH_KEYCHAIN_PASSWORD is not set') unless ENV['MATCH_KEYCHAIN_PASSWORD']
  UI.abort_with_message!('env var MATCH_PASSWORD is not set') unless ENV['MATCH_PASSWORD']

  sync_code_signing(
    git_url: <repo_url>,
    git_branch: <portal_team_id>,
    type: 'appstore',
    app_identifier: <app_id>,
    username: <apple_username>,
    team_id: <portal_team_id>,
    clone_branch_directly: false,
    readonly: false
  )
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[master]: [13:33:30]: Cruising over to lane 'certs_and_profile' �
[master]: [13:33:30]: -------------------------------
[master]: [13:33:30]: --- Step: sync_code_signing ---
[master]: [13:33:30]: -------------------------------
[master]:
[master]: +-----------------------+--------------------------------------+
[master]: |                  Summary for match 2.115.0                   |
[master]: +-----------------------+--------------------------------------+
[master]: | git_url               | git@gitlab.com:company/repo          |
[master]: |                       | a-wlappinfo.git                      |
[master]: | git_branch            | PORTALID                             |
[master]: | type                  | appstore                             |
[master]: | app_identifier        | ["com.company.app"]                  |
[master]: | username              | email@company.com                    |
[master]: | team_id               | PORTALID                             |
[master]: | clone_branch_directly | false                                |
[master]: | readonly              | false                                |
[master]: | storage_mode          | git                                  |
[master]: | shallow_clone         | false                                |
[master]: | keychain_name         | login.keychain                       |
[master]: | keychain_password     | ********                             |
[master]: | force                 | false                                |
[master]: | force_for_new_devices | false                                |
[master]: | skip_confirmation     | false                                |
[master]: | skip_docs             | false                                |
[master]: | platform              | ios                                  |
[master]: | verbose               | false                                |
[master]: +-----------------------+--------------------------------------+
[master]:
[master]: [13:33:30]: Cloning remote git repo...
[master]: [13:33:30]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[master]: [13:33:45]: Checking out branch PORTALID...
[master]: [13:33:47]: �  Successfully decrypted certificates repo
[master]: [13:33:47]: Verifying that the certificate and profile are still valid on the Dev Portal...
[master]: [13:33:48]: Couldn't find a valid code signing identity for distribution... creating one for you now
[master]:
[master]: +-------------------+--------------------------------------+
[master]: |                 Summary for cert 2.115.0                 |
[master]: +-------------------+--------------------------------------+
[master]: | development       | false                                |
[master]: | force             | true                                 |
[master]: | username          | email@company.com                    |
[master]: | team_id           | PORTALID                             |
[master]: | keychain_path     | /Users/apps_builder_master/Library/  |
[master]: |                   | Keychains/login.keychain-db          |
[master]: | keychain_password | ********                             |
[master]: | platform          | ios                                  |
[master]: +-------------------+--------------------------------------+
[master]:
[master]: [13:33:48]: Starting login with user 'email@company.com'
[master]: [13:33:50]: Successfully logged in
[master]: security: SecKeychainItemImport: User interaction is not allowed.
[master]: [13:33:59]: Successfully generated 223D4VJ44Y which was imported to the local machine.
[master]: [13:34:15]: Verifying the certificate is properly installed locally...
[master]: +---------------+----------------+
[master]: |       Lane Context             |
[master]: +---------------+----------------+
[master]: | PLATFORM_NAME |                |
[master]: | LANE_NAME     | initialize_app |
[master]: +---------------+----------------+
[master]: [13:34:15]: Could not find the newly generated certificate installed
[master]:
[master]: +------+------------------------+-------------+
[master]: |              fastlane summary               |
[master]: +------+------------------------+-------------+
[master]: | Step | Action                 | Time (in s) |
[master]: +------+------------------------+-------------+
[master]: | 1    | opt_out_usage          | 0           |
[master]: | 2    | Switch to              | 0           |
[master]: |      | certs_and_profile      |             |
[master]: |      | lane                   |             |
[master]: | �    | sync_code_signing      | 44          |
[master]: +------+------------------------+-------------+
[master]:
[master]: [13:34:15]: fastlane finished with errors
[master]:
[master]: [!] Could not find the newly generated certificate installed
</pre>
</details>

### Environment

 <details>  <pre><summary>� fastlane environment �</summary>

### Stack 

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.13.6 (17G6030)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby   
opt_out_usage
import 'DroidFastfile'
import 'IosFastfile'

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.115.0 | � Update available |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.14.0  | ✅ Up-To-Date  |
| fastlane-plugin-brew    | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.17.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| mini_mime                 | 1.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| rack                      | 2.0.6        |
| rack-test                 | 1.0.0        |
| xpath                     | 3.0.0        |
| capybara                  | 2.18.0       |
| claide                    | 1.0.2        |
| cliver                    | 0.3.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.6.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| cocoapods                 | 1.6.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| connection_pool           | 2.2.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.14.0       |
| fastlane-plugin-brew      | 0.1.1        |
| git                       | 1.5.0        |
| jaro_winkler              | 1.5.2        |
| openssl                   | 2.1.2        |
| parallel                  | 1.16.1       |
| parser                    | 2.6.2.0      |
| websocket-extensions      | 0.1.3        |
| websocket-driver          | 0.7.0        |
| poltergeist               | 1.12.0       |
| psych                     | 3.1.0        |
| rack-protection           | 2.0.5        |
| rainbow                   | 3.0.0        |
| redis                     | 4.1.0        |
| rest-client               | 2.0.2        |
| ruby-progressbar          | 1.10.0       |
| rubocop                   | 0.66.0       |
| sidekiq                   | 5.2.5        |
</details>

*generated on:* **2019-04-24**
 </pre>
</details>

**Comment by janpio** [comment]
Can you check the values of the environment variables `CER_FILE_PATH` and `CER_KEYCHAIN_PATH` after your ran these lanes (on directly, and once via the other one)? 

Those are used to check if it was properly installed: https://github.com/fastlane/fastlane/blob/be55c12077fe91f4eecb64e8ee3a3fa4b8085048/cert/lib/cert/runner.rb#L15-L17 and something seems to go wrong with those I guess.

**Comment by salmanasiddiqui** [comment]
@janpio I will test it out today and let you know. One difference I noticed in the logs is:
```
[master]: [13:33:48]: Starting login with user 'email@company.com'
[master]: [13:33:50]: Successfully logged in
[master]: security: SecKeychainItemImport: User interaction is not allowed.
[master]: [13:33:59]: Successfully generated 223D4VJ44Y which was imported to the local machine.
[master]: [13:34:15]: Verifying the certificate is properly installed locally...
```
the third line, this is what I see when certificate is is not found, where as when I run the lane directly from shell then I don't get this line in logs instead there is a line about `Setting partition list ...`  something like that.

----------------

I have updated that part of my initial post, sure I will create a separate issue for that.

**Comment by salmanasiddiqui** [comment]
@janpio I will test it out today and let you know. One difference I noticed in the logs is:
```
[master]: [13:33:48]: Starting login with user 'email@company.com'
[master]: [13:33:50]: Successfully logged in
[master]: security: SecKeychainItemImport: User interaction is not allowed.
[master]: [13:33:59]: Successfully generated 223D4VJ44Y which was imported to the local machine.
[master]: [13:34:15]: Verifying the certificate is properly installed locally...
```
the third line, this is what I see when certificate is is not found, where as when I run the lane directly from shell then I don't get this line in logs instead there is a line about `Setting partition list ...`  something like that.

----------------

I have updated that part of my initial post, sure I will create a separate issue for that.

**Comment by salmanasiddiqui** [comment]
Hey @janpio ,

the values of these ENV vars when calling `sync_code_signing` from a lane (`certs_and_profile`) which is called by another lane (`initialize_app`):
```
[slave0]: [19:27:50]: Successfully logged in
[slave0]: security: SecKeychainItemImport: User interaction is not allowed.
[slave0]: [19:27:58]: Successfully generated 583T8L4AM3 which was imported to the local machine.
[slave0]: [19:27:59]: Verifying the certificate is properly installed locally...
[slave0]: [19:27:59]: CER_FILE_PATH: /var/folders/kf/6mwq411j6kl7wcltf77mbjv80000gn/T/d20190505-8051-1f0f33w/certs/distribution/583T8L4AM3.cer
[slave0]: [19:27:59]: CER_KEYCHAIN_PATH: 
```
the values of these ENV vars when calling `certs_and_profile` directly (without deleting previously created certificate from keychain):
```
[19:35:20]: Successfully logged in
security: SecKeychainItemImport: User interaction is not allowed.
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[19:35:27]: Successfully generated 4BFG895V8P which was imported to the local machine.
[19:35:28]: Verifying the certificate is properly installed locally...
[19:35:28]: CER_FILE_PATH: /var/folders/kf/6mwq411j6kl7wcltf77mbjv80000gn/T/d20190505-8214-1lxto0n/certs/distribution/4BFG895V8P.cer
[19:35:28]: CER_KEYCHAIN_PATH: 
```
the values of these ENV vars when calling `certs_and_profile` directly (after cleaning up existing certificate from keychain):
```
[20:01:31]: Successfully logged in
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[20:01:39]: Successfully generated AKH66K5XUW which was imported to the local machine.
[20:01:41]: Verifying the certificate is properly installed locally...
[20:01:41]: Successfully installed certificate AKH66K5XUW

+-------------------------------------+---------------------------------------------------+
|                                Summary for sigh 2.115.0                                 |
+-------------------------------------+---------------------------------------------------+
| app_identifier                      | com.company.someappid                             |
| username                            | email@domain.com                                  |
| force                               | true                                              |
| cert_id                             | AKH66K5XUW                                        |
| provisioning_name                   | match AppStore com.company.someappid              |
| ignore_profiles_with_different_name | true                                              |
| team_id                             | PORTALID                                          |
| platform                            | ios                                               |
| adhoc                               | false                                             |
| developer_id                        | false                                             |
| development                         | false                                             |
| skip_install                        | false                                             |
| skip_fetch_profiles                 | false                                             |
| skip_certificate_verification       | false                                             |
| readonly                            | false                                             |
+-------------------------------------+---------------------------------------------------+

[20:01:41]: Starting login with user 'email@domain.com'
[20:01:42]: Successfully logged in
[20:01:42]: Fetching profiles...
[20:01:43]: Verifying certificates...
[20:01:43]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[20:01:46]: Creating new provisioning profile for 'com.company.someappid' with name 'match AppStore com.company.someappid' for 'ios' platform
[20:01:46]: Downloading provisioning profile...
[20:01:47]: Successfully downloaded provisioning profile...
[20:01:47]: Installing provisioning profile...
/var/folders/kf/6mwq411j6kl7wcltf77mbjv80000gn/T/d20190505-8425-1q8mnbw/profiles/appstore/AppStore_com.company.someappid.mobileprovision
[20:01:47]: Installing provisioning profile...
[20:01:48]: 🔒  Successfully encrypted certificates repo
[20:01:48]: Pushing changes to remote git repo...
[20:01:49]: Finished uploading files to Git Repo [git@gitlab.com:company/some-repo.git]

+---------------------+---------------------------------------------------------+---------------------------------------------------------+
|                                                     Installed Provisioning Profile                                                      |
+---------------------+---------------------------------------------------------+---------------------------------------------------------+
| Parameter           | Environment Variable                                    | Value                                                   |
+---------------------+---------------------------------------------------------+---------------------------------------------------------+
| App Identifier      |                                                         | com.company.someappid                                   |
| Type                |                                                         | appstore                                                |
| Platform            |                                                         | ios                                                     |
| Profile UUID        | sigh_com.company.someappid_appstore                     | df668ead-1124-4adb-8b52-d6ef92fbcdea                    |
| Profile Name        | sigh_com.company.someappid_appstore_profi               | match AppStore com.company.someappid                    |
|                     | le-name                                                 |                                                         |
| Profile Path        | sigh_com.company.someappid_appstore_profi               | /Users/apps_builder_0/Library/MobileDevice/Provisionin  |
|                     | le-path                                                 | g                                                       |
|                     |                                                         | Profiles/df668ead-1124-4adb-8b52-d6ef92fbcdea.mobilepr  |
|                     |                                                         | ovision                                                 |
| Development Team ID | sigh_com.company.someappid_appstore_team-               | V22Z94RBWA                                              |
|                     | id                                                      |                                                         |
+---------------------+---------------------------------------------------------+---------------------------------------------------------+

[20:01:49]: All required keys, certificates and provisioning profiles are installed 🙌
[20:01:49]: Setting Provisioning Profile type to 'app-store'
[20:01:49]: CER_FILE_PATH: /var/folders/kf/6mwq411j6kl7wcltf77mbjv80000gn/T/d20190505-8425-1q8mnbw/certs/distribution/AKH66K5XUW.cer
[20:01:49]: CER_KEYCHAIN_PATH: 
```

**Comment by salmanasiddiqui** [comment]
@janpio The issue has been fixed for me, I used the `unlock_keychain` action before using `sync_code_signing` action and that fixed the issue for me (even when using `sync_code_signing` via nested lanes).

**Comment by janpio** [comment]
Interesting. Shouldn't we have gotten a more obvious error message then? @joshdholtz?

**Comment by salmanasiddiqui** [comment]
Just fyi,
I was getting various random issues, by random I mean code signing or building ipa would randomly start failing and then I had to restart machine, open Keychain app and close it etc.. All those issues seems to be resolved by just invoking `unlock_keychain` action before `sync_code_signing`.

May be add this in code signing troubleshooting page:
`Try invoking unlock_keychain action before sync_code_signing`
