### ISSUE TITLE
about multi-targets problem.

### ISSUE THREAD

**Issue by xclidongbo** [fastlane/fastlane#14684]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

I want to update one of targets version number. But after I execute command `fastlane #{lane_name}`.
Both of targets plist`s version changed. This is not what I want.

``` 
desc "release lane"
  lane :xxxxxRel do |options|

    schemeType = options[:schemeType]
    schemeType ||= "1"
    version_number ||= "1.0.1"
    plist_path ||= "Info.plist"
    app_identifier ||= "xxxxxxx"

    if schemeType == "1"
      scheme = "xxxxxx"
      version_number = "1.0.1"
      plist_path =  "#{PROJECT_NAME}/Info.plist"
      app_identifier = "xxxxxxxx"
    else
      scheme = "second_xxxxxxx"
      version_number = "1.0.9"
      plist_path = "#{PROJECT_NAME}/Second-Info.plist"
      app_identifier = "com.xxxxxxx"
    end
    # puts("************plist_path: #{plist_path}, app_identifier: #{app_identifier}")


    update_info_plist( # update app identifier string
      plist_path: "#{plist_path}",
      app_identifier: "#{app_identifier}"
    )

    increment_version_number(
      version_number: "#{version_number}"
    )
    increment_build_number
    btstoreBase(
      output_directory: OUTPUT_DIR,
      export_method: "app-store",
      configuration: "Release",
      scheme: "#{scheme}"
    )
    appstore
    slack(message: "Successfully uploaded a new App Store build")
  end

```

**Comment by janpio** [comment]
Here is an older issue about the same topic https://github.com/fastlane/fastlane/issues/9229, and a response that explains why this is unfortunately not possible: https://github.com/fastlane/fastlane/issues/9229#issuecomment-303543303. Fortunately it also links to a plugin that solves this as well: https://github.com/fastlane/fastlane/issues/9229#issuecomment-319903690

**Comment by xclidongbo** [comment]
@janpio  Thanks. Good job. I will close this.
