### ISSUE TITLE
"No such file or directory - pod" when using jenkins --- but "pod install" in command line works fine

### ISSUE THREAD

**Issue by HoustonDuane** [fastlane/fastlane#14694]
### Issue Description
No such file or directory - pod

##### Command executed
fastlane ent_build config:InHouse build_number:1297 output_dir:/Users/Shared/Jenkins/Home/jobs/Jenkinsfile/builds/1297/archive

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [22:36:09]: [33mfastlane detected a Gemfile in the current directory[0m
[22:36:09]: [33mhowever it seems like you don't use `bundle exec`[0m
[22:36:09]: [33mto launch fastlane faster, please use[0m
[22:36:09]: 
[22:36:09]: [36m$ bundle exec fastlane ent_build config:InHouse build_number:1297 output_dir:/Users/Shared/Jenkins/Home/jobs/Jenkinsfile/builds/1297/archive[0m
[22:36:09]: 
[22:36:09]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[22:36:10]: [32m------------------------------[0m
[22:36:10]: [32m--- Step: default_platform ---[0m
[22:36:10]: [32m------------------------------[0m
[22:36:10]: [32mDriving the lane 'ios ent_build' 🚀[0m
[22:36:10]: [32m-----------------------[0m
[22:36:10]: [32m--- Step: cocoapods ---[0m
[22:36:10]: [32m-----------------------[0m
[22:36:10]: [36m$ pod install[0m
+------------------+---------------+
|           [33mLane Context[0m           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios ent_build |
+------------------+---------------+
[22:36:10]: [31mNo such file or directory - pod[0m

+------+------------------+-------------+
|           [32mfastlane summary[0m            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | [31mcocoapods[0m        | 0           |
+------+------------------+-------------+

[22:36:10]: [31mfastlane finished with errors[0m

[22:36:10]: [33mError accessing file, this might be due to fastlane's directory handling[0m
[22:36:10]: [33mCheck out https://docs.fastlane.tools/advanced/#directory-behavior for more details[0m

#######################################################################
 fastlane 2.121.1 is available. You are on 2.114.0.
 You should use the latest version.
 Please update using `sudo gem install fastlane`.
#######################################################################

[32m2.121.1 Improvements[0m
* [deliver] screenshots are binary data, write as such (#14655) via Jan Piotrowski
* [action] app_store_build_number (and latest_testflight_build_number) don't raise error if using :initial_build_number (#14654) via Josh Holtz
* [spaceship] Authentication documentation (#14524) via Jan Piotrowski
* [deliver] fix ipad 3rd gen naming to prevent future collisions (#14653) via Josh Holtz
* [frameit] add missing documentation for title_min_height option (#14651) via Bruno Virlet
* [pilot] fix typo in message (#14646) via Piet Jaspers

[32m2.121.0 Improvements for deliver, spaceship, and actions[0m
* [action] allow modify_services to enable data_protection (#14571) via martinkasa
* [deliver] apple tv privacy policy upload and download handling added (#14569) via aniketgaur
* [deliver] iPad Pro (12.9-inch) (3rd generation) ambiguity resolution (#14576) via Viktoras Laukevičius
* [spaceship] make Spaceship::Tunes::DisplayFamily main data source for screenshot information (#14574) via Liam Nichols
* [action] cert: Prevent from crash when keychain_path param wasn't passed (#14620) via Dmitrii Celpan
* [frameit] fix frameit percentage padding (#14596) via Christophe Wagner
* [action] pod_lib_lint: Add support for use_module_headers and subspecs (#14599) via Raymond Hoagland
* [action] app_store_build_number: Pass teamID when selecting itunes team (#14604) via Dmitrii Celpan
* [spaceship] Include 'DES' cookie into FASTLANE_SESSION (#14301) (#14525) via Maksym Grebenets
* [spaceship] Automate phone number selection for "request code via SMS" in 2FA with `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` env var (#14436) via Jan Piotrowski
* [deliver] Test Deliver::AppScreenshot methods and fix uncovered bugs (#14588) via Liam Nichols
* [action] Post line break characters as actual interpreted line break through slack integration (#14612) via Albert
* [action] artifactory: Add a read timeout option (#14580) via Raymond Hoagland
* [action] pod_lib_lint: Add new cocoapods 1.7 parameters of the lint command (#14579) via Martin Fiebig
* [action] sonar: new optional param for branch name (#14611) via Husyn
* [action] register_devices changed to actions/register_devices/ (#14582) via Morten Bøgh
* [deliver] upload_screenshots_spec to test screenshot collection (#14533) via Liam Nichols
* [deliver] Fix builds whose versions have components with leading zeros infinitely wait for submission (#14513) via Justin Hill

[32m2.120.0 Fix pilot, fix build watcher, and other improvements[0m
* [spaceship] [spaceship] migrate "olympus" authentication endpoint to appstoreconnect api (#14509) via Stefan Natchev
* [pilot + spaceship] fix pilot, build watcher, and beta groups to use new App Store Conneect API  (#14523) via Josh Holtz
* [fastlane] add the ability to specify Step Name for all actions (#14423) via Adrien Becchis
* [gym] fix provisioning profile detection for projects based on inherited xcconfigs (#14360) via José Miguel Brocal Gallego
* [spaceship] Add app screenshot download endpoint to README.md (#14519) via Maksym Grebenets
* [action] Continue git_commit action execution if there is nothing to commit (#14501) via Daniel Jankowski
* [fastlane] fix syntax error changes introduced in ruby 2.6 (#14508) via Stefan Natchev
* [fastlane] git: more responsible, Windows-compatible shellout (#14471) via Artem Sheremet
* [snapshot] Make the `sleep` waiting for animations optional (#14498) via Xaver Lohmüller
* [deliver] do not set ratings_resets to null if not specified. (#14490) via Carlos Fonseca
* [scan] added env_name values for commonly used options (#14492) via Jacob Aleksynas
* [action] add --set-upstream option to push_to_git_remote (#14496) via Guillermo García
* [sign] fix sigh not using custom keychain path (#14462) via Josip Ćavar

[32mTo see all new releases, open https://github.com/fastlane/fastlane/releases[0m

[32mPlease update using `sudo gem install fastlane`[0m
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - pod (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:190:in `popen2e'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/actions/cocoapods.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy)
Stage "Deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
One way or another, I have finished
[Pipeline] echo
I failed :(
[Pipeline] sh
[Docs_App_Jenkinsfile] Running shell script
Error when executing failure post condition:
hudson.AbortException: script returned exit code 1
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.exited(DurableTaskStep.java:512)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$HandlerImpl.exited(DurableTaskStep.java:593)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask$Watcher.run(FileMonitoringTask.java:488)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

+ python /Users/Shared/Jenkins/Home/workspace/Jenkinsfile/../bin/lark-robot-push.py 2 InHouse
Traceback (most recent call last):
  File "/Users/Shared/Jenkins/Home/workspace/Jenkinsfile/../bin/lark-robot-push.py", line 4, in <module>
    import requests
ImportError: No module named requests
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
  end

  desc "Docs App Build If Need"
  lane :build_upload_if_needed do |options|
    branch = options[:current_branch]
    build_if_needed(current_branch: branch, key_commit: "--pipeline")

    user_email = options[:user_email]

    # https://docs.fastlane.tools/actions/cocoapods/
    cocoapods(
      use_bundle_exec: false,
      podfile: "../Podfile",
      try_repo_update_on_error: true
    )

    gym(
      workspace: "Docs.xcworkspace",
      configuration: "Beta",
      export_method: "enterprise",
      scheme: "Docs",
      output_directory: "~/Desktop/docs_ipa",
      output_name: "Docs.ipa",
      clean: true
    )

    upload_to_ee(author_email: user_email, last_commit: last_git_commit[:message])
  end

  # https://docs.fastlane.tools/actions/gym/
  desc "Docs App Build And Upload"
  lane :build_upload do |options|
    user_email = options[:user_email]

    # https://docs.fastlane.tools/actions/cocoapods/
    cocoapods(
      use_bundle_exec: false,
      try_repo_update_on_error: true
    )

    gym(
      workspace: "Docs.xcworkspace",
      configuration: "Beta",
      export_method: "enterprise",
      scheme: "Docs",
      output_directory: "~/Desktop/docs_ipa",
      output_name: "Docs.ipa",
      clean: true
    )

    upload_to_ee(author_email: user_email, last_commit: last_git_commit[:message])
  end

  desc "Enterprise Build"
  lane :ent_build do |options|
    cocoapods(
      use_bundle_exec: false,
      try_repo_update_on_error: true
    )

    # begin
    #   xcodebuild(
    #     test: true,
    #     scheme: "Docs",
    #     workspace: "Docs.xcworkspace",
    #     destination: "platform=iOS Simulator,name=iPhone 8,OS=12.0"
    #   )
    # rescue => ex
    #   UI.error("docs test fail for: #{ex}")
    # end


    config = options[:config]
    build_number = options[:build_number]
    output_dir = options[:output_dir]

    increment_build_number(
      build_number: build_number,
      xcodeproj: "Docs.xcodeproj"
    )

    gym(
      workspace: "Docs.xcworkspace",
      configuration: config,
      export_method: "enterprise",
      scheme: "Docs",
      output_directory: output_dir,
      output_name: "Docs.ipa",
      clean: true
    )
  end

  desc "Development Build"
  lane :dev_build do |options|
    cocoapods(
      use_bundle_exec: false,
      try_repo_update_on_error: true
    )

    config = options[:config]
    build_number = options[:build_number]
    output_dir = options[:output_dir]

    increment_build_number(
      build_number: build_number,
      xcodeproj: "Docs.xcodeproj"
    )

    gym(
      workspace: "Docs.xcworkspace",
      configuration: config,
      export_method: "development",
      scheme: "Docs",
      output_directory: output_dir,
      output_name: "Docs.ipa",
      clean: true
    )
  end

  # desc "仅供本地测试，不作远程服务"
  # lane :just_for_local_test do |options|
  #   upload_to_ee(author_email: "xurunkang@bytedance.com", last_commit: last_git_commit[:message])
  # end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| unf_ext                   | 0.0.7.6      |
| json                      | 2.2.0        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.5        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.1.0        |
</details>

*generated on:* **2019-04-30**
</details> </pre>
</details>

**Comment by HoustonDuane** [comment]
btw, workaround in issue#4247 does not help

**Comment by janpio** [comment]
1. Could you update your fastlane to the most recent version please?
2. Can you run your lane with `--verbose` added at the end and post its output? Maybe that tells us what is happening during `pod install`.

**Comment by HoustonDuane** [comment]
I solved this by not letting fastlane do the pod stuff.
