### ISSUE TITLE
[spaceship] Spaceship::TestFlight::Group.filter_groups: (Spaceship::UnexpectedResponse) client.rb:321:in `handle_response'

### ISSUE THREAD

**Issue by pparmaei** [fastlane/fastlane#14697]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using Spaceship::TestFlight::Groups, we currently face a `(Spaceship::UnexpectedResponse)` error. We are currently on version **2.120.0**
 of fastlane (due to a regression in version **2.121.1** #14661 ). Nevertheless, it was suggested that I still create this issue (https://github.com/fastlane/fastlane/issues/14666#issuecomment-487857584) 
 

##### Command executed

 `groups = Spaceship::TestFlight::Group.filter_groups(app_id: xxx)`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [/Users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response': <!DOCTYPE html><html lang="en"> (Spaceship::UnexpectedResponse)
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>

<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>
	from /Users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/client.rb:90:in `get_groups'
	from /Users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/group.rb:40:in `all'
	from /Users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/group.rb:55:in `filter_groups'
	from precheck.rb:82:in `<main>'] </pre>
</details>

### Environment

<details>
  <pre> [[⠹] 🚀 /Users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/build.rb:91: warning: already initialized constant Spaceship::TestFlight::Build::BUILD_STATES
/Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.120.0/spaceship/lib/spaceship/test_flight/build.rb:91: warning: previous definition of BUILD_STATES was here
[✔] 🚀 
[19:40:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
/Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.120.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: already initialized constant CredentialsManager::AccountManager::DEFAULT_PREFIX
/Users/user/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.120.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: previous definition of DEFAULT_PREFIX was here
[19:40:25]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.120.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.3       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| signet                    | 0.11.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| fastimage                 | 2.1.4        |
| unicode-display_width     | 1.4.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| os                        | 1.0.0        |
| psych                     | 2.0.17       |
</details>

*generated on:* **2019-04-30**
</details>
] </pre>
</details>

**Comment by tastafur** [comment]
Hello,
I have the same problem, I am using version 2.101.1, I am going to update Fastlane to the latest version, to see if I fix the error
