### ISSUE TITLE
[action] cocoapods: Add a new flag argument to install beta/pre version of cocoapods

### ISSUE THREAD

**Issue by BabyAzerty** [fastlane/fastlane#14692]
#### Motivation Behind Feature
Allow the usage of Beta/Pre versions of Cocoapods by adding a "pre_version" argument to the cocoapods action.

#### Feature Description
It would be called like this:
```
cocoapods(
  pre_version: true  // false by default
)
```
And would trigger `install cocoapods --pre`.

#### Alternatives or Workarounds
Nothing AFAIK

**Comment by janpio** [comment]
That sounds like a reasonable feature to add to this action.
Are there any other flags/options that would be useful here?

Do you want to take a shot at implementing this yourself? All the logic of that action lives in https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/cocoapods.rb and it should be pretty straight forward to implement your suggestion.

**Comment by BabyAzerty** [comment]
I would gladly be happy to help.

However while I understand most logic inside [https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/cocoapods.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/cocoapods.rb), I don't really see where the "installation" of the gem cocoapods can be done?

When I check [https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/gem_helper.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/gem_helper.rb), I don't see how the action **cocoapods** can tell the verify_gem to install a specific version.

**Comment by janpio** [comment]
Ohoh, seems I misunderstood. I thought this was a flag that would be given to `pod install`, but if I understand you correctly this is actually about installing a different `pod`? That might be a lot trickier...
