### ISSUE TITLE
fastlane deliver on Windows - Could not receive latest API key from App Store Connect

### ISSUE THREAD

**Issue by mattallscripts** [fastlane/fastlane#14704]
### Question Checklist
- ✅ Updated fastlane to the latest version
- ✅ I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- ✅ I read [docs.fastlane.tools](https://docs.fastlane.tools)
- ✅ I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Why are we seeing this error when running **fastlane deliver** on Windows 10.
"_Could not receive latest API key from App Store Connect, this might be a server issue._"

#### Question Description
After reading through the documentation we understand that fastlane deliver is compatible with Windows and does not require Xcode. However when using fastlane on Windows 10 we are seeing an error when trying to upload an ipa to App Store Connect

> fastlane deliver --ipa "App.ipa" --force --username <Apple ID>
> [13:02:12]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
> [13:02:13]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
> [13:02:14]: Login to App Store Connect (<Apple ID>)
> Please provide your Apple Developer Program account credentials
> You can also pass the password using the `FASTLANE_PASSWORD` environment variable
> Password (for <Apple ID>): *******************
> No such file or directory @ rb_sysopen - /tmp/spaceship1556816536_26084_20934880.log
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> ➡️  Confusion about setting SSL Options
>     https://github.com/fastlane/fastlane/issues/10261 [closed] 3 💬
>     29 Dec 2017
> 
> ➡️  Unable to connect to itunes connect - Environment issue
>     https://github.com/fastlane/fastlane/issues/9109 [closed] 5 💬
>     25 Sep 2017
> 
> ➡️  deliver: there is no web session to update
>     https://github.com/fastlane/fastlane/issues/6826 [closed] 55 💬
>     05 Dec 2016
> 
> 
> [!] The request could not be completed because:
>         **Could not receive latest API key from App Store Connect, this might be a server issue.**
> [13:02:16]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

To try to fix this, I've tried at least the following:
- Reinstalling ruby / gems
- Different Windows machine
- Turning off firewall
- Generating and using an app-specific password from Apple ID
- Installing fastlane on macOS and running same command. It works, but we need this on our Windows build machine!
- Using either Command Prompt or PowerShell
- Setting the locale to UTF-8. We've not gotten this to work neither on Command Prompt nor Powershell, however from what I've read this only really affects output and fastlane should be able to read input successfully anyways so this probably shouldn't affect us.
- Setting environment variable to get around firewall: $env:DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS = "-t DAV"

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.5.5                        |
| Bundler?                    | false                        |
| Git                         | git version 2.10.1.windows.1 |
| Installation Source         | C:/Ruby25-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby25-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| fiddle                    | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-05-02**
</details>

**Comment by janpio** [comment]
Is this the complete output you are getting? Try with `--verbose` added at the end to see if you get more.

> After reading through the documentation we understand that fastlane deliver is compatible with Windows and does not require Xcode.

Where did you read that?
We are generally working on multi platform support, but are not nearly ready - especially things like uploading to the App Store are still very fragile (or even broken).

>  **Could not receive latest API key from App Store Connect, this might be a server issue.**

Can you request https://appstoreconnect.apple.com/olympus/v1/app/config?hostname=itunesconnect.apple.com manually?

Try creating a folder `tmp` on the harddisk your project lives and on `C:` manually and see if this fixes something.

**Comment by mattallscripts** [comment]
Wow, that last one did it. I manually created a 'tmp' folder on hard-disk and now I'm onto the next unrelated error. Thank you!

**Comment by janpio** [comment]
The reliance on `tmp` here is a bug, as this is present for macOS and Linux - but not Windows. This should probably be changed to `user directory/.fastlane`, we already use that in some places.

**Comment by mattallscripts** [comment]
Does fastlane even work on Windows? Now I'm getting this error:
2019-05-03T11:56:07.0799456Z [!] Could not find transporter at usual locations. Please use environment variable `FASTLANE_ITUNES_TRANSPORTER_PATH` to specify your installation path.

After writing to Apple yesterday they responded, "_I understand that you are inquiring about the possibility of downloading **iTMS Transporter** to your windows device. Upon review, I confirmed that since this is a part of Xcode, you cannot download it to your windows device as of now._"

**Comment by janpio** [comment]
Not everything works, no.

Which is why in my previous comment I wrote this:

> > After reading through the documentation we understand that fastlane deliver is compatible with Windows and does not require Xcode.
> 
> Where did you read that?
> We are generally working on multi platform support, but are not nearly ready - especially things like uploading to the App Store are still very fragile (or even broken).

That being said, there are versions of iTMSTransporter for Windows available: https://stackoverflow.com/a/31420580/252627 That doesn't mean they are fully supported by Apple, and it doesn't mean that Fastlane will magically work on Windows. But some functionality might with this.
