### ISSUE TITLE
Specify Provisioning Profile without bundle id

### ISSUE THREAD

**Issue by Jon889** [fastlane/fastlane#14700]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Description
We're using gym to build our app, but not using match. It's an in house Enterprise app so we use a provisioning profile with a wildcard. Currently to specify the provisioning profile name we use the export options plist and have all the bundle id's (there are different variations of the app, about 12 in total) and the value of them are all identical to the name of the wildcard provisioning profile.

Is there a way to avoid having to list all the bundle id's I tried using a wildcard in the key but that didn't work.

If I was using xcodebuild directly I would just specify the `exportProvisioningProfile` parameter. What is the equivalent of this option when using gym?

**Comment by janpio** [comment]
Can you share a bit of code that makes it easier to understand what you are doing?
Same for the potential `xcodebuild` command. Thanks.
