### ISSUE TITLE
Swift build - variable itcTeam not being picked up as set.

### ISSUE THREAD

**Issue by dan-ryan** [fastlane/fastlane#14719]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm getting the same problem as an auto-closed created by @benrudhart where you still get the warning:
`Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile` even though it was set. 
https://github.com/fastlane/fastlane/issues/12586

Because of this, I have to choose which team on the console. 

I searched in the code for `itcTeam` and it looks like it should be `itcTeamId` instead. But changing it to that doesn't fix the issue.

**Comment by janpio** [comment]
Can you provide some more context? What does your Fastfile look like?

**Comment by dan-ryan** [comment]
My Fastfile is basically the default built one with `fastlane init swift`.

```
import Foundation

class Fastfile: LaneFile {
	func betaLane() {
	desc("Push a new beta build to TestFlight")
		buildApp(workspace: "X.xcworkspace", scheme: "X")
		uploadToTestflight(username: "X")
	}
}
```

**Comment by dan-ryan** [comment]
I've looked at the codebase and I can't see where any of the "Appfile.swift" file is being used. But maybe I missed something.
I generated "Matchfile.swift" and can see where those values are used.

**Comment by janpio** [comment]
It might be possible that the configuration files (Appfile, Deliverfile, Matchfile...) do not work identically in fastlane Swift to normal ruby fastlane.

**Comment by dan-ryan** [comment]
Yeah seems to be the case. I just don't think this swift version is ready yet (being beta and all). I think I should move to Ruby.

**Comment by janpio** [comment]
It would sure give you less surprises of this type.

In this case, it would probably be worth finishing the investigation into `Appfile` and add something to the fastlane Swift documentation.

**Comment by dan-ryan** [comment]
I've moved to Ruby and everything is now working perfectly. All the settings are being correctly read :)
