### ISSUE TITLE
"HockeyApp will be retired on November 16, 2019"

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14729]
> Last year, we announced that HockeyApp features and functionality would move to Visual Studio App Center, a single solution for continuously building, testing, releasing, and monitoring your apps. Because HockeyApp’s distribution, crash reporting, and analytics services are now available in App Center, HockeyApp will be retired on November 16, 2019.

https://hockeyapp.net/faq/

**Comment by lumaxis** [comment]
I work on both HockeyApp and App Center and just wanted to add a little to this:

We are very committed to helping users make a successful transition from HockeyApp to App Center. There are currently still a number of feature gaps but we plan to close a lot of them before the sunset in November, see our roadmap here: https://github.com/microsoft/appcenter/wiki/Roadmap#hockeyapp

Additionally, I wanted to mention that App Center also already has a [fastlane plugin](https://github.com/microsoft/fastlane-plugin-appcenter) and we've recently significantly increased our own investment in that 😊

If there are any open questions or issues, feel free to open an issue in our GitHub repo https://github.com/microsoft/appcenter or ping me or @derpixeldan here 👍🏼

**Comment by janpio** [comment]
Thanks @lumaxis for the additional insight - I expected nothing less from you ;)

I assume https://rink.hockeyapp.net and https://upload.hockeyapp.net will stop working November 16, thus breaking the current [`hockey`](https://docs.fastlane.tools/actions/hockey/) action? 

We already have deprecation messages on that documentation page as you know, but it would probably then be sensible to disable the actual functionality of the action and just output a deprecation message for people still using the action (in old projects etc) that leads to your new plugin?

Any other thoughts from your side?

**Comment by lumaxis** [comment]
@janpio We're actually not yet 100% certain what will happen to those APIs come November 16th so I think doing anything right now would be premature.

We'll come back to this once our plans for the upload APIs manifest and the shutdown date comes a little closer.

**Comment by janpio** [comment]
Great. @fastlane-bot will complain about this issue and try to close it every few weeks/months, that should give us a nice reminder via a GitHub notification ;) If there are no news, just reply with that and the bot will back off for another month. That should make sure we don't drop anything here.

**Comment by lumaxis** [comment]
Cool, sounds good 👌🏼 Thanks for getting the ball rolling on this 🙂
