### ISSUE TITLE
Frameit Font Size

### ISSUE THREAD

**Issue by Alarson93** [fastlane/fastlane#14724]
### Feature Request

It would be nice if there was a way to make the font size for framing consistent between screenshots. I've done a fair bit of reading in related issues and it seems like nobody has seen the discussion through to the end.

#### Motivation Behind Feature

Consistent font sizes between screenshots would look a lot better.

There are many issues asking for very similar behavior (though it seems that they have often died from inactivity).

#### Feature Description

I completely understand the desire to have auto-sizing text. The devices are all different sizes, so a single point size does not make sense. 

What I'm looking for is a **font ratio** - the ratio of font height to device height. (I would prefer the term "font scale" but that is already taken.) 
I assume that the space between a device frame and the top of the framed screenshot is a constant (assuming text exists at all) based on the current autosizing behavior. I'm going to call this the **font gap**.

For example:
Let's say I have a **font ratio** of 0.1 and I'm using a device that has a height of 1000 pixels.
I should use a font point size that results in my font being 100 pixels tall on a single line.
If my line wraps, then I have 2 lines totaling 200 pixels.
If I have too much text (i.e. it takes up more space than the **font gap** allows) then it runs over my screenshot and I must change my wording. 

This gives developers and designers far more control over the sizing while keeping things relatively simple. This in theory should work across all device sizes that will ever exist because it is just a simple ratio. 

If I do not specify a **font ratio**, then Fastlane defaults to the current autosizing behavior.

I would prefer that this be a property that exists in the "defaults" of the Framefile.json, but would be open to the "data" fields as well for more granular control.

#### Alternatives or Workarounds

1. Add whitespace around short titles in order to try to make everything consistent.
a. Doesn't work because Fastlane trims starting and trailing whitespace. Also a bit hacky.
2. Set font scale for each individual label.
a. Doesn't work and, even if it did, it requires manually calculations (or at least visually estimating) and font change requires scale change.
3. Writing my own framing script and foregoing Frameit.
a. I could do this, but lacks the scalability that Frameit offers. Plus - it is a specific solution to something that could be solved more abstractly and benefit others in similar situations.
4. Modify my titles do be similar lengths.
a. This is my short term solution, but requires extra work for other languages. Philosophically it removes create freedom when there is no technical limitation; the feature just needs be made.
5. Specific a font size per device (Framefile.json "defaults" and/or "data")
a. I haven't thoroughly explored this, but I think this would be viable. Perhaps it would be easier to implement than the above approach too.
6. Set the "font scale" in defaults.
a. The size of the text does change, but it is scaled across all screenshots. It does not result in a consistent size.

#### After-thought

Either what I mentioned above or workaround 5 are both good behaviors IMO, but I understand that they may differ in technical challenges. In either case I would love to see Fastlane support such functionality as it seems weird to lack such behavior. (Setting a font without the ability to also set the font size tripped me up when I was first reading the docs.)

For the time being we are going to change our wording to make the font sizes mostly consistent, but that is a bandaid. In the future I will need to have support for consistent font sizes (largely as a consequence of the scale of our product(s)).

If Fastlane doesn't implement the functionality, then I will do my best to build my own solution. I would hope I can create a pull request to add this feature, but it is also possible I could be forced down workaround 3 because it is much more straightforward. 

I'm quite busy with tasks aside from screenshot automation, so I don't know when I will get to this. If it isn't a feature by the time I must address the font size issue, I will do my best to ensure that I build something that works for our company and for Fastlane as a whole. 🚀

I'd love to get some feedback as to:
1. Is this a good idea?
2. What are the primary technical hurdles? 
3. Which is easier to implement?
4. Alternative implementations and/or workarounds

Thank you for your time!

**Comment by GraemeAllanBryce** [comment]
I have been struggling with this issue for a while and reflect the OPs opinion.  I really want to arrive at a consistent font size on all screenshots.

I would accept that if I have specified a font size then it is my responsibility to ensure that the given text c/w carriage returns will indeed fit inside the frame.  If frameIt was forced to use a given size it would be expected to overwrite the edges of the frame if i was stupid!

The alternative would be for frameIt to auto wrap the given text at a fixed size and that would also be acceptable.

The lack of control or consistency of font size removes the magic that this product otherwise promises.
