### ISSUE TITLE
Fastlane Does Not Recognize Gemfile Dependencies

### ISSUE THREAD

**Issue by adamfisher** [fastlane/fastlane#14728]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
*Fastlane does not respect the Gemfile in a project repository*

#### Question Description

I am attempting to install [cocoapods-art](https://github.com/jfrog/cocoapods-art) on our build box which is used to connect cocoa pods to Artifactory for package management. The problem is there is a need for both Ruby gems and cocoapods to be resolved using our internal Artifactory instance.

I [opened an issue](https://github.com/jfrog/cocoapods-art/issues/24) with them and they recommended using `bundle install` and the output I get is:

```
Using CFPropertyList 3.0.0
...
Using cocoapods-art 1.0.2
...
Using fastlane 2.119.0
Bundle complete! 2 Gemfile dependencies, 66 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
43534752mac:ios teamcity$ bundle info cocoapods-art
  * cocoapods-art (1.0.2)
	Summary: Artifactory support for CocoaPods
	Homepage: https://github.com/JFrogDev/cocoapods-art
	Path: /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-art-1.0.2
```

So far so good. The plugin is showing as installed. I then proceed to run `bundle exec fastlane beta` for our beta build lane and it should respect the Gemfile according to the [Fastlane docs on this](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile) but I get:

```
[15:17:22]: ----------------------------------------
[15:17:22]: --- Step: Verifying fastlane version ---
[15:17:22]: ----------------------------------------
[15:17:22]: Your fastlane version 2.122.0 matches the minimum requirement of 2.64.0  ✅
[15:17:22]: ------------------------------
[15:17:22]: --- Step: default_platform ---
[15:17:22]: ------------------------------
[15:17:22]: Driving the lane 'ios beta' 🚀
[15:17:22]: -----------------------
[15:17:22]: --- Step: cocoapods ---
[15:17:22]: -----------------------
[15:17:22]: $ pod install
[15:17:23]: ▸ [!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.
[15:17:23]: Exit status of command 'pod install' was 1 instead of 0.
[!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.

[15:17:23]: $ pod install --repo-update
[15:17:24]: ▸ [!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.
[15:17:24]: Exit status of command 'pod install --repo-update' was 1 instead of 0.
[!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.

+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[15:17:24]: [!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | default_platform    | 0           |
| 💥   | cocoapods           | 2           |
+------+---------------------+-------------+

[15:17:24]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/teamcity/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.122.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] [!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again. (FastlaneCore::Interface::FastlaneShellError)

	from /Users/teamcity/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.122.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
```

So my questions are:

1. How do you get Fastlane's version of Ruby to use a custom Gem repo (Artifactory in this case)?
2. How do you install gems into Fastlane's custom version of Ruby?

**Comment by janpio** [comment]
`pod install` should actually be `bundle exec pod install` in this case for to work. `cocoapods` has an `use_bundle_exec` for this: https://docs.fastlane.tools/actions/cocoapods/#parameters

**Comment by adamfisher** [comment]
In my beta lane I added:

```
cocoapods(
      use_bundle_exec: true,
      try_repo_update_on_error: true
    )
```

and the build commands are:

```
bundle install
bundle exec pod install
bundle exec fastlane beta
```

But it still gives this error even though I see `cocoapods-art` in the installation list output of the `bundle install` command:

> Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.

**Comment by janpio** [comment]
> But it still gives this error even though I see `cocoapods-art` in the installation list output of the `bundle install` command:
> 
> > Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.

Is the command that is executed by the `cocoapods` action done in the same folder as the others?

**Comment by adamfisher** [comment]
I ended up having to shim ruby and install fastlane into the shimmed version. It was kind of hacky. I wish there was an easier way to do this.

**Comment by janpio** [comment]
Suggestions how this could be solved on the fastlane level?
