### ISSUE TITLE
Changelog between branches instead of commits

### ISSUE THREAD

**Issue by badoualy** [fastlane/fastlane#14737]
#### Motivation Behind Feature
Depending on your release flow, retrieving commits between commits might not be enough.

If you:
- hotfix master
- tag a new version on master (the hotfix)
- Merge master in develop
- Run the `changelog_from_git_commits` action: you'll lose the commits that might've happened between the previous release and the hotfix in the develop branches.

#### Feature Description
Add the possibility to list commits between branches instead of commits. In the above scenario, we can just use the commit diff between develop and master to build the changelog.

**Comment by janpio** [comment]
Is this for an existing action or should this be a new one?

**Comment by badoualy** [comment]
Sorry forgot to mention, I was thinking of adding a parameter to `changelog_from_git_commits`.

**Comment by janpio** [comment]
Would be a bit of a misnomer then... But that's not a problem. We can then just create an alias `changelog_from_git` that does the same thing.

I like the idea I think.

**Comment by badoualy** [comment]
Why would it be a misnomer? The only difference is that the commit list would come from comparing two branches instead of two revisions

**Comment by janpio** [comment]
Yeah, you'r right - would probably work as well. `commits` is vague enough that this also applies to comparing two branches. Nice!
