### ISSUE TITLE
[Documentation] The `output` table is visible in the action's documentation 

### ISSUE THREAD

**Issue by mollyIV** [fastlane/fastlane#14730]
## Motivation Behind Feature

As a user / developer I would like to know what `output` (aka `SharedValues` / `lane_context`) is produced by an action by having a look at the documentation. 

Nowadays the only way to know what `SharedValues` are available when an action is finished is to execute `fastlane action [action_name]` command. Below you can find an output for `fastlane action changelog_from_git_commits` command:

```bash
...

+--------------+------------------------------------------+
|       changelog_from_git_commits Output Variables       |
+--------------+------------------------------------------+
| Key          | Description                              |
+--------------+------------------------------------------+
| FL_CHANGELOG | The changelog string generated from the  |
|              | collected git commit messages            |
+--------------+------------------------------------------+
Access the output values using `lane_context[SharedValues::VARIABLE_NAME]`

...
```

The `output` section should be generated automatically. 

## Technical details

The `output` table should be added to the [`ActionDetails.md.erb` template](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/ActionDetails.md.erb) and populated with data in [`markdown_docs_generator.rb`](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb). 

_Special thanks to_ @janpio 🤘 🙇 🙇

**Comment by janpio** [comment]
Just a note: When this is done, we should check our documentation for `SharedValues` in general and make sure the generated table links there for usage instructions (besides the minimal ones that sure will be next to the table anyway).

**Comment by mollyIV** [comment]
@janpio I found the following docs about `SharedValues`:
* https://docs.fastlane.tools/actions/lane_context/
* https://docs.fastlane.tools/advanced/lanes/#lane-context

I would suggest adding the following before the generated `output` table:

```
The different actions can communicate with each other using a shared hash. To get more information check [Lanes documentation](https://docs.fastlane.tools/advanced/lanes/#lane-context). 
```

That would be 
> the minimal ones that sure will be next to the table anyway

WDYT? 🤔

**Comment by janpio** [comment]
That sounds perfect. You could think about adding one example with a dummy SharedValue, so it might be enough to read this text to understand how one can access this in code. But the link of course is the main thing.

The documentation you link to could be improved by adding the information that each action documentation contains a table of the SharedValues it produces with an explanation what they are used for.
