### ISSUE TITLE
Exit fastlane successfully early

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14740]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

How to exit fastlane with a successful status code when no further actions needed?

#### Question Description
Imagine, you have a 3 actions in a lane:
**A
B
C**

How to exit fastlane successfully after **A**, without throwing an error?

**Comment by philhinco** [comment]
This might be something for you: [Stop executing a lane early](https://docs.fastlane.tools/advanced/lanes/#stop-executing-a-lane-early)

**Comment by richardtop** [comment]
Thanks, I think, `next` keyword would fit me well.
