### ISSUE TITLE
[action] slather: [!] 'binary_file' value must be a String! Found Array instead.

### ISSUE THREAD

**Issue by robnadin** [fastlane/fastlane#14747]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.122.0`]
- Last working version: [e.g. `2.121.1`]

### Regression Description

The PR #14677 introduced a regression where passing an array to the `binary_file` parameter of the `slather` action fails with the error:
```
'binary_file' value must be a String! Found Array instead.
```

Slather supports multiple values as shown in the source [link](https://github.com/SlatherOrg/slather/blob/69b74115aa3e0166230332e548d81aaeb669c973/lib/slather/command/coverage_command.rb#L31)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle exec fastlane ios code_coverage scheme:"Testable Targets" derived_data_path:"build-out"
[✔] 🚀
+----------------------------+---------+-------------------------------------------------------------------+
|                                               Used plugins                                               |
+----------------------------+---------+-------------------------------------------------------------------+
| Plugin                     | Version | Action                                                            |
+----------------------------+---------+-------------------------------------------------------------------+
| fastlane-plugin-badge      | 1.2.0   | add_badge                                                         |
| fastlane-plugin-versioning | 0.3.4   | get_version_number_from_git_branch get_version_number_from_plist  |
|                            |         | get_build_number_from_plist ci_build_number                       |
|                            |         | increment_version_number_in_plist get_app_store_version_number    |
|                            |         | get_info_plist_path increment_build_number_in_plist               |
| fastlane-plugin-xcconfig   | 1.0.0   | set_xcconfig_value get_xcconfig_value                             |
+----------------------------+---------+-------------------------------------------------------------------+

[15:37:05]: ----------------------------------------
[15:37:05]: --- Step: Verifying fastlane version ---
[15:37:05]: ----------------------------------------
[15:37:05]: Your fastlane version 2.122.0 matches the minimum requirement of 2.115.0  ✅
[15:37:05]: ------------------------------
[15:37:05]: --- Step: default_platform ---
[15:37:05]: ------------------------------
[15:37:05]: Driving the lane 'ios code_coverage' 🚀
[15:37:05]: --------------------------------
[15:37:05]: --- Step: ensure_bundle_exec ---
[15:37:05]: --------------------------------
[15:37:05]: Using bundled fastlane ✅
[15:37:05]: -----------------------
[15:37:05]: --- Step: xcversion ---
[15:37:05]: -----------------------
[15:37:05]: Setting Xcode version to /Applications/Xcode.app for all build steps
[15:37:05]: ---------------------
[15:37:05]: --- Step: slather ---
[15:37:05]: ---------------------
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios code_coverage |
+------------------+-------------------+
[15:37:06]: 'binary_file' value must be a String! Found Array instead.

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | ensure_bundle_exec         | 0           |
| 4    | xcversion                  | 0           |
| 💥   | slather                    | 0           |
+------+----------------------------+-------------+

[15:37:06]: fastlane finished with errors

[!] 'binary_file' value must be a String! Found Array instead.</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.4.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.4.4/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.4/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Fastlane Constants
min_fastlane_version '2.115.0'
default_platform :ios

# Constants
DEFAULT_WORKSPACE = '<redacted>.xcworkspace'
DEFAULT_CONFIGURATION = 'Debug'

platform :ios do

  before_all do |lane, options|
    ensure_bundle_exec

    Dotenv.overload '.env.local'
    xcversion
  end

  lane :code_coverage do |options|
    workspace = options[:workspace] ||= DEFAULT_WORKSPACE
    scheme = options[:scheme]
    configuration = options[:configuration] ||= DEFAULT_CONFIGURATION
    output_directory = options[:output_directory] ||= ENV['SCAN_OUTPUT_DIRECTORY']
    derived_data_path = options[:derived_data_path] ||= ENV['SCAN_DERIVED_DATA_PATH']

    # Get the path to build directory, if it's an absolute path we take it as is, if it's relative we assume it's relative to the root directory
    build_directory = if Pathname.new(derived_data_path).absolute?
      File.expand_path(derived_data_path)
    else
      File.expand_path(File.join('..', derived_data_path))
    end
    # puts "build_directory: #{build_directory}"

    products_path = "#{build_directory}/Build/Products/#{configuration}-iphonesimulator"
    # puts "products_path: #{products_path}"

    # The glob pattern used to search for all frameworks in the project
    bundle_paths = Dir.glob("#{products_path}/*.{app,xctest}")
    # puts "bundle_paths: #{bundle_paths}"

    frameworks = bundle_paths.map { |bundle|
      name = File.basename(bundle).split(/[ _-]|Tests/)[0]
      Dir["#{bundle}/Frameworks/#{name}.framework"].first
    }.compact

    binary_files = frameworks.map { |bundle_file|
      if File.directory? bundle_file
        bundle_file_noext = File.basename(bundle_file, File.extname(bundle_file))
        Dir["#{bundle_file}/**/#{bundle_file_noext}"].first
      else
        bundle_file
      end
    }.sort.reject { |path| path.nil? }

    UI.verbose "Found #{binary_files.count} files:\n" + binary_files.join("\n")

    slather(
      build_directory: build_directory,
      workspace: workspace,
      scheme: scheme,
      configuration: configuration,
      llvm_cov: true,
      output_directory: output_directory,
      use_bundle_exec: true,
      binary_file: binary_files
    )
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.122.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-badge      | 1.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |
| fastlane-plugin-xcconfig   | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                          | Version      |
| ---------------------------- | ------------ |
| did_you_mean                 | 1.1.0        |
| io-console                   | 0.4.6        |
| CFPropertyList               | 3.0.0        |
| concurrent-ruby              | 1.1.5        |
| i18n                         | 0.9.5        |
| minitest                     | 5.11.3       |
| thread_safe                  | 0.3.6        |
| tzinfo                       | 1.2.5        |
| activesupport                | 4.2.11.1     |
| public_suffix                | 2.0.5        |
| addressable                  | 2.6.0        |
| atomos                       | 0.1.3        |
| babosa                       | 1.0.2        |
| curb                         | 0.9.10       |
| fastimage                    | 2.1.5        |
| bundler                      | 1.17.1       |
| colored                      | 1.2          |
| highline                     | 1.7.10       |
| commander-fastlane           | 4.4.6        |
| dotenv                       | 2.7.2        |
| emoji_regex                  | 1.0.1        |
| excon                        | 0.64.0       |
| multipart-post               | 2.0.0        |
| faraday                      | 0.15.4       |
| unf_ext                      | 0.0.7.6      |
| unf                          | 0.1.4        |
| domain_name                  | 0.5.20180417 |
| http-cookie                  | 1.0.3        |
| faraday-cookie_jar           | 0.0.6        |
| faraday_middleware           | 0.13.1       |
| gh_inspector                 | 1.1.3        |
| jwt                          | 2.1.0        |
| memoist                      | 0.16.0       |
| multi_json                   | 1.13.1       |
| os                           | 1.0.1        |
| signet                       | 0.11.0       |
| googleauth                   | 0.6.7        |
| httpclient                   | 2.8.3        |
| mime-types-data              | 3.2019.0331  |
| mime-types                   | 3.2.2        |
| declarative                  | 0.0.10       |
| declarative-option           | 0.1.0        |
| uber                         | 0.1.0        |
| representable                | 3.0.4        |
| retriable                    | 3.1.2        |
| google-api-client            | 0.23.9       |
| digest-crc                   | 0.4.1        |
| google-cloud-env             | 1.0.5        |
| google-cloud-core            | 1.3.0        |
| google-cloud-storage         | 1.16.0       |
| json                         | 2.2.0        |
| mini_magick                  | 4.5.1        |
| multi_xml                    | 0.6.0        |
| plist                        | 3.5.0        |
| rubyzip                      | 1.2.2        |
| security                     | 0.1.3        |
| naturally                    | 2.2.0        |
| simctl                       | 1.6.5        |
| slack-notifier               | 2.3.2        |
| terminal-notifier            | 2.0.0        |
| unicode-display_width        | 1.6.0        |
| terminal-table               | 1.8.0        |
| tty-screen                   | 0.6.5        |
| tty-cursor                   | 0.6.1        |
| tty-spinner                  | 0.9.0        |
| word_wrap                    | 1.0.0        |
| claide                       | 1.0.2        |
| colored2                     | 3.1.2        |
| nanaimo                      | 0.2.6        |
| xcodeproj                    | 1.9.0        |
| rouge                        | 2.0.7        |
| xcpretty                     | 0.3.0        |
| xcpretty-travis-formatter    | 1.0.0        |
| badge                        | 0.10.0       |
| clamp                        | 1.3.0        |
| fuzzy_match                  | 2.0.4        |
| nap                          | 1.1.0        |
| cocoapods-core               | 1.7.0.rc.1   |
| cocoapods-deintegrate        | 1.0.4        |
| cocoapods-downloader         | 1.2.2        |
| cocoapods-plugins            | 1.0.0        |
| cocoapods-search             | 1.0.0        |
| cocoapods-stats              | 1.1.0        |
| netrc                        | 0.11.0       |
| cocoapods-trunk              | 1.3.1        |
| cocoapods-try                | 1.1.0        |
| escape                       | 0.0.4        |
| fourflusher                  | 2.2.0        |
| molinillo                    | 0.6.6        |
| ruby-macho                   | 1.4.0        |
| cocoapods                    | 1.7.0.rc.1   |
| cocoapods-update-if-you-dare | 0.2.0        |
| fastlane-plugin-badge        | 1.2.0        |
| fastlane-plugin-versioning   | 0.3.4        |
| fastlane-plugin-xcconfig     | 1.0.0        |
| mini_portile2                | 2.4.0        |
| mustache                     | 1.1.0        |
| nokogiri                     | 1.10.3       |
| slather                      | 2.4.7        |
| xcode-install                | 2.5.0        |
</details>

*generated on:* **2019-05-12**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@robnadin Will fix this!

**Comment by robnadin** [comment]
Hi @joshdholtz, what's the latest with this? There are some new features introduced in later releases but we are currently blocked from updating due to this issue.
