### ISSUE TITLE
export_options in Gymfile not respected properly

### ISSUE THREAD

**Issue by philhinco** [fastlane/fastlane#14741]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I was revamping and reworking our Fastlane setup today.
Our Fastfile was quite cluttered, so when I found out about for_lane (which can be used in config files such as Appfile, Matchfile and Gymfile) I reworked our lanes to set specific values for different options for match and gym.

In this case, our Gymfile looks like this (for one of the lanes)
<pre>
for_lane :adhoc_local do
    scheme("...")
    configuration("AdHoc")
    export_options({iCloudContainerEnvironment: "Development"})
end
</pre>

The lane looks like this:

<pre>
desc "Builds new Adhoc app for local use"
lane :adhoc_local do |options|
    increment_build_number(
      build_number: options[:bn],
      xcodeproj: "...",
    )
    sync_code_signing
    build_ios_app
end
</pre>

I moved everything we passed in `sync_code_signing` and `build_ios_app` to their respective config files (`Matchfile` and `Gymfile`). All besides `export_options` in the `Gymfile` worked without issues.

**!!! When I pass `export_options` during the `build_ios_app` call everything works !!!.**

In the console output I see the following in both cases:

<pre>
+------------------+----------------------------------------------+
|            Detected Values from './fastlane/Gymfile'            |
+------------------+----------------------------------------------+
| workspace        | REDACTED/REDACTED.xcworkspace                |
| scheme           | REDACTED ci                                  |
| configuration    | AdHoc                                        |
| export_options   | {:iCloudContainerEnvironment=>"Development"} |
| output_directory | ./                                           |
+------------------+----------------------------------------------+
</pre>

Though only the one where I pass `export_options` during the `build_ios_app` call shows the following line the "Summary of gym" table:
<pre>
| export_options.iCloudContainerEnvironment | Development |
</pre>
##### Command executed

`fastlane adhoc_local bn:10052019`
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ fastlane adhoc_local bn:10052019
[✔] 🚀 
[16:23:17]: ----------------------------------------
[16:23:17]: --- Step: Verifying fastlane version ---
[16:23:17]: ----------------------------------------
[16:23:17]: Your fastlane version 2.122.0 matches the minimum requirement of 1.91.0  ✅
[16:23:17]: ------------------------------
[16:23:17]: --- Step: default_platform ---
[16:23:17]: ------------------------------
[16:23:17]: Driving the lane 'ios adhoc_local' 🚀
[16:23:17]: ------------------------------------
[16:23:17]: --- Step: increment_build_number ---
[16:23:17]: ------------------------------------
Current version of project REDACTED is: 
    10052019

[16:23:18]: $ cd /Users/philhinco/Documents/REDACTED && agvtool new-version -all 10052019 && cd -
[16:23:18]: ▸ Setting version of project REDACTED to:
[16:23:18]: ▸ 10052019.
[16:23:18]: ▸ Also setting CFBundleVersion key (assuming it exists)
[16:23:18]: ▸ Updating CFBundleVersion in Info.plist(s)...
[16:23:18]: ▸ Updated CFBundleVersion in "REDACTED.xcodeproj/../REDACTED/Info.plist" to 10052019
[16:23:18]: ▸ Updated CFBundleVersion in "REDACTED.xcodeproj/../REDACTEDTests/Info.plist" to 10052019
[16:23:18]: ▸ /Users/philhinco/Documents/REDACTED
[16:23:18]: -------------------------------
[16:23:18]: --- Step: sync_code_signing ---
[16:23:18]: -------------------------------
[16:23:18]: Successfully loaded '/Users/philhinco/Documents/REDACTED/fastlane/Matchfile' 📄

+----------------+---------------------------------------------------------------+
|                  Detected Values from './fastlane/Matchfile'                   |
+----------------+---------------------------------------------------------------+
| git_url        | GIT_URL |
| readonly       | true                                                          |
| type           | adhoc                                                         |
| app_identifier | IDENTIFIER                                     |
+----------------+---------------------------------------------------------------+

+-----------------------+---------------------------------------------------------------+
|                               Summary for match 2.122.0                               |
+-----------------------+---------------------------------------------------------------+
| type                  | adhoc                                                         |
| readonly              | true                                                          |
| app_identifier        | ["IDENTIFIER"]                                 |
| username              | USERNAME                                            |
| team_id               | TEAMID                                                    |
| storage_mode          | git                                                           |
| git_url               | GIT_URL |
| git_branch            | master                                                        |
| shallow_clone         | false                                                         |
| clone_branch_directly | false                                                         |
| keychain_name         | login.keychain                                                |
| force                 | false                                                         |
| force_for_new_devices | false                                                         |
| skip_confirmation     | false                                                         |
| skip_docs             | false                                                         |
| platform              | ios                                                           |
| verbose               | false                                                         |
+-----------------------+---------------------------------------------------------------+

[16:23:18]: Cloning remote git repo...
[16:23:18]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:23:20]: 🔓  Successfully decrypted certificates repo
[16:23:20]: Installing certificate...

+-------------------+----------------------------------------------+
|                      Installed Certificate                       |
+-------------------+----------------------------------------------+
| User ID           | TEAMID                                   |
| Common Name       | REDACTED |
| Organisation Unit | TEAMID                                   |
| Organisation      | REDACTED                                   |
| Country           | REDACTED                                           |
| Start Datetime    | 2019-04-04 12:00:22 UTC                      |
| End Datetime      | 2020-04-03 12:00:22 UTC                      |
+-------------------+----------------------------------------------+

[16:23:21]: Installing provisioning profile...

+---------------------+---------------------------------------------------+-----------------------------------------------------+
|                                                Installed Provisioning Profile                                                 |
+---------------------+---------------------------------------------------+-----------------------------------------------------+
| Parameter           | Environment Variable                              | Value                                               |
+---------------------+---------------------------------------------------+-----------------------------------------------------+
| App Identifier      |                                                   | IDENTIFIER                           |
| Type                |                                                   | adhoc                                               |
| Platform            |                                                   | ios                                                 |
| Profile UUID        | sigh_com.IDENTIFIER_adhoc              | b7d47211-9974-4ae0-b695-95ee9bb60db3                |
| Profile Name        | sigh_IDENTIFIER_adhoc_profile-name | match AdHoc IDENTIFIER               |
| Profile Path        | sigh_IDENTIFIER_profile-path | /Users/philhinco/Library/MobileDevice/Provisioning  |
|                     |                                                   | Profiles/b7d47211-9974-4ae0-b695-95ee9bb60db3.mobi  |
|                     |                                                   | leprovision                                         |
| Development Team ID | sigh_IDENTIFIER_adhoc_team-id      | TEAM ID                                          |
+---------------------+---------------------------------------------------+-----------------------------------------------------+

[16:23:21]: All required keys, certificates and provisioning profiles are installed 🙌
[16:23:21]: Setting Provisioning Profile type to 'ad-hoc'
[16:23:21]: ---------------------------
[16:23:21]: --- Step: build_ios_app ---
[16:23:21]: ---------------------------
[16:23:21]: Successfully loaded '/Users/philhinco/Documents/REDACTED/fastlane/Gymfile' 📄

+------------------+----------------------------------------------+
|            Detected Values from './fastlane/Gymfile'            |
+------------------+----------------------------------------------+
| workspace        | REDACTED/REDACTED.xcworkspace                  |
| scheme           | REDACTED ci                                   |
| configuration    | AdHoc                                        |
| export_options   | {:iCloudContainerEnvironment=>"Development"} |
| output_directory | ./                                           |
+------------------+----------------------------------------------+

[16:23:21]: $ xcodebuild -showBuildSettings -workspace WORKSPACE -scheme SCHEME -configuration AdHoc
[16:23:23]: Detected provisioning profile mapping: {:"IDENTIFIER"=>"match AdHoc IDENTIFIER"}

+---------------------------------------------------------------+--------------------------------------------------------------+
|                                                   Summary for gym 2.122.0                                                    |
+---------------------------------------------------------------+--------------------------------------------------------------+
| export_method                                                 | ad-hoc                                                       |
| export_options.provisioningProfiles.IDENTIFIER | match AdHoc IDENTIFIER                        |
| destination                                                   | generic/platform=iOS                                         |
| output_name                                                   | REDACTED                                                      |
| build_path                                                    | /Users/philhinco/Library/Developer/Xcode/Archives/2019-05-10 |
| workspace                                                     | WORKSPACE                                  |
| scheme                                                        | SCHEME                                                   |
| clean                                                         | false                                                        |
| output_directory                                              | ./                                                           |
| configuration                                                 | AdHoc                                                        |
| silent                                                        | false                                                        |
| skip_package_ipa                                              | false                                                        |
| result_bundle                                                 | false                                                        |
| buildlog_path                                                 | ~/Library/Logs/gym                                           |
| skip_profile_detection                                        | false                                                        |
| xcode_path                                                    | /Applications/Xcode.app                                      |
+---------------------------------------------------------------+--------------------------------------------------------------+

[16:23:24]: $ set -o pipefail && xcodebuild -workspace WORKSPACE -scheme SCHEME -configuration AdHoc -destination 'generic/platform=iOS' -archivePath /Users/philhinco/Library/Developer/Xcode/Archives/2019-05-10/REDACTED.xcarchive archive | tee /Users/philhinco/Library/Logs/gym/REDACTED-SCHEMEi.log | xcpretty
[16:23:27]: ▸ Processing ResourceBundle-HockeySDKResources-HockeySDK-Info.plist
>>> LOTS OF COMPILING 
[16:24:42]: ▸ Touching REDACTED.app (in target: REDACTED)
[16:24:42]: ▸ Archive Succeeded
[16:24:43]: Generated plist file with the following values:
[16:24:43]: ▸ -----------------------------------------
[16:24:43]: ▸ {
[16:24:43]: ▸   "provisioningProfiles": {
[16:24:43]: ▸     "IDENTIFIER": "match AdHoc IDENTIFIER"
[16:24:43]: ▸   },
[16:24:43]: ▸   "method": "ad-hoc",
[16:24:43]: ▸   "signingStyle": "manual"
[16:24:43]: ▸ }
[16:24:43]: ▸ -----------------------------------------
[16:24:43]: $ /usr/bin/xcrun /Users/philhinco/.rvm/gems/ruby-2.5.3/gems/fastlane-2.122.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/z0/_zm7r_r136l_rwkkbxyz10040000gn/T/gym_config20190510-17622-1yvo0xm.plist' -archivePath /Users/philhinco/Library/Developer/Xcode/Archives/2019-05-10/REDACTED\ 2019-05-10\ 16.23.23.xcarchive -exportPath '/var/folders/z0/_zm7r_r136l_rwkkbxyz10040000gn/T/gym_output20190510-17622-1um62n9' 
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/z0/_zm7r_r136l_rwkkbxyz10040000gn/T/gym_config20190510-17622-1yvo0xm.plist -archivePath '/Users/philhinco/Library/Developer/Xcode/Archives/2019-05-10/REDACTED 2019-05-10 16.23.23.xcarchive' -exportPath /var/folders/z0/_zm7r_r136l_rwkkbxyz10040000gn/T/gym_output20190510-17622-1um62n9
2019-05-10 16:24:44.510 xcodebuild[20077:3588966] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/z0/_zm7r_r136l_rwkkbxyz10040000gn/T/SCHEME_2019-05-10_16-24-44.510.xcdistributionlogs'.
error: exportArchive: exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided}

** EXPORT FAILED **
[16:24:45]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.122.0                 |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS12.2.sdk        |
+---------------+-------------------------+

[16:24:45]: ▸ Validate /Users/philhinco/Library/Developer/Xcode/DerivedData/REDACTED-dbtprjqweaewvibgyyqxyyeypdhr/Build/Intermediates.noindex/ArchiveIntermediates/SCHEME/InstallationBuildProductsLocation/Applications/REDACTED.app (in target: REDACTED)
[16:24:45]: ▸     cd /Users/philhinco/Documents/REDACTED
[16:24:45]: ▸     builtin-validationUtility /Users/philhinco/Library/Developer/Xcode/DerivedData/REDACTED-dbtprjqweaewvibgyyqxyyeypdhr/Build/Intermediates.noindex/ArchiveIntermediates/SCHEME/InstallationBuildProductsLocation/Applications/REDACTED.app
[16:24:45]: ▸ ** ARCHIVE SUCCEEDED **
[16:24:45]: 
[16:24:45]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[16:24:45]: 📋  For the complete and more detailed error log, check the full log at:
[16:24:45]: 📋  /Users/philhinco/Library/Logs/gym/REDACTED-SCHEME.log
[16:24:45]: 
[16:24:45]: Looks like fastlane ran into a build/archive error with your project
[16:24:45]: It's hard to tell what's causing the error, so we wrote some guides on how
[16:24:45]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[16:24:45]: Before submitting an issue on GitHub, please follow the guide above and make
[16:24:45]: sure your project is set up correctly.
[16:24:45]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[16:24:45]: the full commands printed out in yellow in the above log.
[16:24:45]: Make sure to inspect the output above, as usually you'll find more error information there
[16:24:45]: 
+------------------------------------+------------------------------------------------------------------------+
|                                                Lane Context                                                 |
+------------------------------------+------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                    |
| PLATFORM_NAME                      | ios                                                                    |
| LANE_NAME                          | ios adhoc_local                                                        |
| BUILD_NUMBER                       | 10052019                                                               |
| SIGH_PROFILE_TYPE                  | ad-hoc                                                                 |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"IDENTIFIER"=>"match AdHoc IDENTIFIER"} |
+------------------------------------+------------------------------------------------------------------------+
[16:24:45]: Error packaging up the application

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | increment_build_number     | 1           |
| 4    | sync_code_signing          | 2           |
| 💥   | build_ios_app              | 83          |
+------+----------------------------+-------------+

[16:24:45]: fastlane finished with errors

[!] Error packaging up the application
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.3/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_CH.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.122.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-05-10**
</details>

**Comment by philhinco** [comment]
@fastlane-bot Not related to code signing. Code signing works without issues

**Comment by janpio** [comment]
Interesting, I don't actually know how the configuration files work in this regard - if they support a) _all_ options of all actions, or b) only a specific set. 

If a, then you found a problem. But if b, you might have accidentally only used supported ones _besides_ `export_options`.

**Comment by philhinco** [comment]
@janpio I _think_ its a), because according to the [Gym docs on export_options](https://docs.fastlane.tools/actions/gym/#export-options) they are supposed to work (since they use them in the second example, the first one loading a Plist file).

And as I mentioned in the issue, according to the table for "Detected values from Gymfile", both cases _detect_ the value, but it seems like only when passing it directly to Gym it actually gets used.

**Comment by philhinco** [comment]
Though it could also be that they don't quite work well with `for_lane` possibly?

**Comment by janpio** [comment]
I currently don't have the time to investigate, but you might make it easier for others (and future me) to do that by creating a demo repository here on Github with a minimal project and lane that shows what is going on. (project doesn't have to build, seeing the different `xcodebuild` commands should be enough to follow along).

**Comment by philhinco** [comment]
I'll try and get a minimal setup up in a repo, though it might take me a while due to work and other commitments. It's not a super important issue since it still works when passing it during the call, so at least building our app still works.

**Comment by markus-mohemian** [comment]
Any updates on this one? Have the same problem.

**Comment by janpio** [comment]
Then see https://github.com/fastlane/fastlane/issues/14741#issuecomment-491572426 @markus-mohemian
