### ISSUE TITLE
Couldn't download certificate, got this instead: {"responseId"=>"XXX", "resultCode"=>7100, "resultString"=>"Certificate 'VGXXXXXX7' not found", "userString"=>"There is no certificate with ID &#x27

### ISSUE THREAD

**Issue by kikolobo** [fastlane/fastlane#1474]
Updated to latest version, including sigh 4.. Fixed the problem of **["cert fails with: Couldn't download certificate,"](https://github.com/fastlane/fastlane/issues/1469)**

But now I am getting :
_Couldn't download certificate, got this instead: {"responseId"=>"XXX", "resultCode"=>7100, "resultString"=>"Certificate 'VGFB8JESL7' not found", "userString"=>"There is no certificate with ID &#x27;VGPP8XXXXX&#x27;_

It used to work perfectly before this, however I don't know if this is an issue on my part or FastLane.

The #x27 makes me wonder since this is in reality a '   However I don't know if this is junk by the verbose output or a real problem.

Any help welcomed!

**Comment by asfalcone** [comment]
@kikolobo Thanks for reporting your issue. Please refer to the [issue template](https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md) and provide the additional details of your configuration and the full ouput.

**Comment by JackieQi** [comment]
I still have this error. Any help please?

**Comment by asfalcone** [comment]
@JackieQi Please refer to the [issue template](https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md) and open a new issue details of your configuration and the full output.

**Comment by JackieQi** [comment]
Alright, found the issue, this error message is directly from Apple. If you go to apple developer portal, and download the certificate which you specify for fastlane, you will see that error message from the website. So you have to revoke it and generate a new one.

**Comment by seapy** [comment]
@JackieQi Great! you save me

**Comment by truth3** [comment]
Interestingly enough, I ran into the same thing on one of my accounts. The better question is how did Apple lose the cert?
