### ISSUE TITLE
Automatically accept Apple's new privacy policy

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14743]
### Feature Request
Automatically accept Apple's new privacy policy
#### Motivation Behind Feature

When a separate account is used for continuous integration machine, the user has to manually log in and accept a new privacy policy in order to release the build. This feature would give a new level of automation and remove the need to use manual labour.

The feature might be turned off by default, so the user could forward the new agreement to the legal department if needed.
#### Alternatives or Workarounds

```Shell
[12:23:01]: Starting login with user 'apple-ci@google.com'
+------------------+----------------+
|           �[33mLane Context�[0m            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios fabric_bot |
+------------------+----------------+
[12:23:02]: �[31mNeed to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement.�[0m
```

Login and click through the privacy policy manually.

**Comment by janpio** [comment]
That sounds like a pretty good candidate for a fastlane plugin!

That way the actual logic could be implemented and tested without any commitment needed from the core contributors, and if it turns out to be super popular and used very often it can maybe still be integrated to the core action further down the line.

You can read more about creating a plugin here: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by snatchev** [comment]
I am not a lawyer, but I don't think we should automatically accept the Privacy policy.
By clicking the Accept button, you assumes legal liability of the policy. If fastlane did this for you, then fastlane would be assuming this liability, and we cannot accept that. Also, I don't think Apple would be too happy about this either.
Sorry, this is a necessary inconvenience.

**Comment by richardtop** [comment]
> If hammer did this for you, then hammer would be assuming this liability, and we cannot accept that. Also, I don't think Apple would be too happy about this either.
