### ISSUE TITLE
How's the cer/p12 identifier generated?

### ISSUE THREAD

**Issue by cuongta** [fastlane/fastlane#14745]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How's the cer/p12 identifier generated?

#### Question Description
How's the cer/p12 identifier generated?
<IDENTIFIER>.cer and <IDENTIFIER>.p12 stored in the repo.

The identifier seems to be different from the identifier that I see in the Keychain Access. How can I verify if it's the same certificate between the keychain and the stored repo when the identifiers are different/renamed?

Thanks

**Comment by janpio** [comment]
> How's the cer/p12 identifier generated?

Where? There are multiple places that generate certificates in fastlane.

**Comment by bhavincb** [comment]
@cuongta @janpio  do you know how the password is generated? i want the password of certificate generated by `cert` action. is there any way?

**Comment by snatchev** [comment]
@bhavincb The password is supplied by the user at the time of creation. It is not stored anywhere, besides possibly Keychain Access, at the user's discretion.

**Comment by bhavincb** [comment]
@snatchev , there is no parameter for supplying password to the `cert` action.  how to supply password to the `cert` action?

**Comment by snatchev** [comment]
@bhavincb looks like you are correct, there is no password in the `cert` action. The password is only applied when the certificate is turned into a p12 file.

@cuongta could you try using `openssl pkcs12 -info -in my.p12` to get more info about the certificates so you can cross-reference them to the ones in the repo?

As far as I know, fastlane does not change any identifiers for existing certificates. It may be the case that Keychain Access applies some identifiers for the UI, but I do not understand how that works.

**Comment by bhavincb** [comment]
@snatchev  `cert` action also generates p12 certificate. so which password it uses when generating this file?

**Comment by snatchev** [comment]
it is a blank password
https://docs.fastlane.tools/actions/pem/#note-about-empty-p12-passwords-and-keychain-accessapp
