### ISSUE TITLE
Retrieve password of certificate generate by action "cert"

### ISSUE THREAD

**Issue by bhavincb** [fastlane/fastlane#14752]
### Question Checklist

- [ * ] Updated fastlane to the latest version
- [ * ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ * ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ * ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Cert and Sigh

#### Question Description

we want to use third party build service for IOS build. which requires certificate and provision profile. for that we are using `cert` and `sigh` action to generate certificates. Now we have certificate and don't have it's password which is required for any future manual signing.
so how to retrieve password of certificate made by `cert` action?

**Comment by snatchev** [comment]
As far as I know, it is not possible to retrieve the password. The password is not stored anywhere on Apple's systems.

**Comment by bhavincb** [comment]
@snatchev  so what are the other option for this type of situation?

**Comment by snatchev** [comment]
@bhavincb I am not understanding your requirements. If you have don't have a password for an existing cert, you will have to create a new certificate.

Any passwords that do get stored are in the Keychain https://docs.fastlane.tools/actions/cert/#how-is-my-password-stored

**Comment by bhavincb** [comment]
@snatchev  let me give you brief explanation.

1. there is thirdparty service which build the ios and sign them. but it will require certificate, it's password and provision profile.
2. we are using combination of `cert` and `sigh` actions to generate certificate and provision profile which will be passed to the thirdparty build service.

hence we will also require for the password of the certificate which is generated by the cert. as you have said that we can't retrieve password the afterword and also there is no way of manually setting password at the time of creation.
so is there any other workaround?

**Comment by snatchev** [comment]
Can you confirm that the password is not actually the empty-string?

Try: `openssl pkcs12 -info -in certificate.p12`
