### ISSUE TITLE
Unknown format in import

### ISSUE THREAD

**Issue by Wei18** [fastlane/fastlane#14757]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have the same issue like
Fastlane match fails to import private key into keychain [#13242](https://github.com/fastlane/fastlane/issues/13242)
Dose someone has the solution, please~~

I have tried both version `LibreSSL 2.6.4` and `OpenSSL 1.0.2r  26 Feb 2019` 

##### Command executed

```
$newssl pkcs12 -nocerts -nodes -out key.pem -in $certificates.p12 -password pass:$MATCH_PASSWORD

$newssl aes-256-cbc -k $MATCH_PASSWORD -in key.pem -out $CERT_ID.p12 -a

$newssl aes-256-cbc -k $MATCH_PASSWORD -in $certificates.cer -out $CERT_ID.cer -a


#Verify 
openssl aes-256-cbc -k $MATCH_PASSWORD -in $CERT_ID.cer -out cert.der -a -d
openssl x509 -inform der -in cert.der -out cert.pem

openssl aes-256-cbc -k $MATCH_PASSWORD -in $CERT_ID.p12 -out key.pem -a -d

openssl pkcs12 -export -out verify.p12 -inkey key.pem -in cert.pem -password pass:$MATCH_PASSWORD

security import verify.p12 -k $keychain -P $MATCH_PASSWORD -T /usr/bin/codesign -T /usr/bin/security

#output 
# OpenSSL 1.0.2r  26 Feb 2019
# MAC verified OK
# MAC verified OK
# 1 identity imported.
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  
```
INFO [2019-05-14 22:10:50.40]: 🔓  Successfully decrypted certificates repo
DEBUG [2019-05-14 22:10:50.40]: Your certificate 'F8P577QRL9.cer' is valid
INFO [2019-05-14 22:10:50.40]: Installing certificate...
INFO [2019-05-14 22:10:50.40]: $ security list-keychains -d user
INFO [2019-05-14 22:10:50.42]: ▸     "/Users/wei/Library/Keychains/login.keychain-db"
INFO [2019-05-14 22:10:50.42]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/wei/Library/Keychains/login.keychain-db
INFO [2019-05-14 22:10:50.46]: ▸ keychain: "/Users/wei/Library/Keychains/login.keychain-db"
INFO [2019-05-14 22:10:50.46]: ▸ version: 512
INFO [2019-05-14 22:10:50.46]: ▸ class: 0x80001000 
INFO [2019-05-14 22:10:50.46]: ▸ attributes:
INFO [2019-05-14 22:10:50.46]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2019-05-14 22:10:50.46]: ▸     "cenc"<uint32>=0x00000003 
INFO [2019-05-14 22:10:50.46]: ▸     "ctyp"<uint32>=0x00000001 
INFO [2019-05-14 22:10:50.46]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2019-05-14 22:10:50.46]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2019-05-14 22:10:50.46]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2019-05-14 22:10:50.46]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2019-05-14 22:10:50.46]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2019-05-14 22:10:50.46]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
DEBUG [2019-05-14 22:10:50.61]: Certificate 'F8P577QRL9.cer' is already installed on this machine
INFO [2019-05-14 22:10:50.61]: $ security import /var/folders/zc/dqsp1xl52qs6c0czv978wcl00000gn/T/d20190514-65753-19y4s84/certs/development/F8P577QRL9.p12 -k '/Users/wei/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
ERROR [2019-05-14 22:10:50.67]: security: SecKeychainItemImport: Unknown format in import.
```

</details>

### Environment

<details>
 <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D109)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    func registerLane(){
        match(type: "development", readonly: true, verbose: true)
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.119.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.4       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| tty-spinner               | 0.9.0        |
| tty-cursor                | 0.6.1        |
| faraday                   | 0.15.4       |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| faraday_middleware        | 0.13.1       |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| fastimage                 | 2.1.5        |
| unicode-display_width     | 1.5.0        |
| addressable               | 2.6.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-05-14**
</details>
</details>

**Comment by Wei18** [comment]
And almost has the same description like: [#13242](https://github.com/fastlane/fastlane/issues/13242)
Question Description
We have fastlane setup and working with a private certificates repo. Our certificate expired about two weeks ago so we created new ones on apple developer site, encrypted them, and committed them to our private repo. Now when we run fastlane match it fails to import the private key with the following error "security: SecKeychainItemImport: Unknown format in import". We've verified that the certificate files in our repo have been encrypted correctly and contains the correct password. We verified by manually decrypting them and importing them to our keychain which worked fine. We are wondering if anybody else has seen this issue and been able to resolve it?
----
And verify by [link]
(https://docs.fastlane.tools/actions/match/#export-distribution-certificate-and-private-key-as-single-p12-file)

**Comment by Wei18** [comment]
Updated:

I follow this section to solve my problems.
https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo

**Comment by snatchev** [comment]
@Wei18 thank you for updating. Do you have an idea of why the `security` command complained about the format?

**Comment by Wei18** [comment]
@snatchev,

I guess.
Although file can be successfully encrypted/decrypted different version of openssl, it do not working to import.
I can't verify my thought, due to I dunno exact version of openssl used on fastlane. 
(From docs, I known version as same as on MacOS.)

Thanks.
