### ISSUE TITLE
Use frameit on screen recordings

### ISSUE THREAD

**Issue by fawzirifai** [fastlane/fastlane#14759]
Can I use frameit on a screen recording or gif?

**Comment by max-ott** [comment]
Hi @fawzirifai and welcome to fastlane! `Frameit` currently only supports screenshots. You might want to check out the docs over at https://docs.fastlane.tools/actions/frameit/

**Comment by jeromediaz** [comment]
supposing your screen recording respect screenshots size, you should be able to use ffmpeg to extract all images from your video
(https://www.bugcodemaster.com/article/extract-images-frame-frame-video-file-using-ffmpeg)

then use frameit

and reconstruct back a video with the framed images
https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg
