### ISSUE TITLE
upload to testflight stuck

### ISSUE THREAD

**Issue by gsagwan** [fastlane/fastlane#14758]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

i am trying to upload my ipa generated and it is stuck in transporter software download step.

DEBUG [2019-05-15 00:40:23.92]: [Transporter]: INFO: Downloading com.apple.transporter.aspera-macos-64/3.7.3.143062...

##### Command executed

bundle exec fastlane ios beta
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Hi @gsagwan and welcome to Fastlane! Could you please add your `spaceship` logs so we can learn more about what's going on? You might want to check out https://docs.fastlane.tools/actions/spaceship_logs/#spaceship_logs

**Comment by gsagwan** [comment]
HI @max-ott thanks for your response.

would need your help in generating logs with bundle exec fastlane ios beta
added in a lane, but it didn't generate.

  lane :upload do
    upload_to_testflight
    spaceship_logs(
      copy_to_path: "/Users/jenkins/spaceship.lop"
    )
  end

**Comment by janpio** [comment]
@gsagwan Can you please update your issue to include the _complete_ output you are getting, and also your `fastlane env` output so we have some context? Thanks.
