### ISSUE TITLE
Allow for parallel lane execution

### ISSUE THREAD

**Issue by mieliespoor** [fastlane/fastlane#14769]
### Feature Request
Allow for parallel lane execution

#### Motivation Behind Feature
This would allow for certain tasks to run concurrently and cut down on build execution times.

#### Feature Description
If the ability existed to execute lanes in parallel/currently with other lanes, it would allow for build times to be reduced. After build and testing, things like file uploading etc can be done concurrently and there is no reason some of these lanes/tasks cannot be executed at the same time. It would cut down on build times, if allowed.

#### Alternatives or Workarounds
Don't know of any.

**Comment by max-ott** [comment]
Great idea, but I think there are some technical limitations: For example you will get an error when there are multiple Transporter instances trying to upload an app/IPA. Possible that there are more occurrences where Apple has set some limits and therefore limiting `Fastlane`.

**Comment by mieliespoor** [comment]
Just after the build, we do a number of things that can run concurrently such as:
 - copy apk/ipa to file share
 - upload to browserstack
 - upload to crashlyitcs

There are one or two more of these that can run concurrently,  but yes, there are a few that shouldn't as you've mentioned.

**Comment by max-ott** [comment]
As `fastlane` is completely open source, feel free to open any pull requests to enable this. More than happy to test and give feedback if possible!

**Comment by salmanasiddiqui** [comment]
imo thats adding extra complexity into fastlane which will cost alot in terms of maintaining this gem (which I feel is already too high)..  fastlane is already overloaded with things and should probably be cleaned up a little to reduce some actions, and to split some actions.

the concurrency thing can be done by using gems like sidekiq on top of fastlane.

**Comment by janpio** [comment]
`Fastfile` is just a ruby file (more or less at least), so if this is possible in plain ruby it might be worth trying to do this in a `Fastfile` as well. If it works, this certainly sounds like something we would want to add to the advanced documentation.

(I don't know enough about ruby to know if and how this could work, but if some of you do, please help us out here!)
