### ISSUE TITLE
automatic_code_signing targets are missing

### ISSUE THREAD

**Issue by nemno** [fastlane/fastlane#14765]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I would like to run automatic_code_signing function, but targets are missing in the "Modified Targets:" list.

Let's say I have 8 targets for my projects.
When I try to update the signing details of my project's targets 4 of them gets just updated.
I tried to find what can be wrong. All the schemes are shared.

I found if I add a new target manually it will be listed in the "Modified Targets:" list. BUT!
If I duplicate a target, and rename it and set it up as a different target it won't be in that list.

What can cause this issue?

##### Command executed

the code I use in my lane is:

	# set code sygning to automatic
	automatic_code_signing(
		use_automatic_signing: false,
		code_sign_identity: 'iPhone Distribution',
	)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre></pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14                                                          |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14 (18A391)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
###############
## run tests ##
###############
lane :run_unit_test do |lane, options|
	run_tests(
		scheme: 'pampers-rewards-ios-us',
	)
end

##########################################
## Update Project Code Signing Settings ##
##########################################
lane :update_signing_settings do |options|

	# set code sygning to automatic
	automatic_code_signing(
		use_automatic_signing: false,
		code_sign_identity: 'iPhone Distribution',
		team_id: 'ATGGD88ZP3'
	)

	# update app prov. profile
	update_project_provisioning(
		build_configuration: 'Sandbox',
		target_filter: options[:target_filter_prov],
		profile: options[:profile_path],
	)

	# update Notification Service prov. profile
	update_project_provisioning(
		build_configuration: 'Sandbox',
		target_filter: 'Notification Service',
		profile: options[:notification_profile_path],
	)

end

##############################
## PROD build to TestFlight ##
##############################
lane :release_testflight do |lane, options|
	# TBD
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.114.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| tty-spinner               | 0.9.0        |
| tty-cursor                | 0.6.1        |
| faraday                   | 0.15.4       |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.64.0       |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.6.0        |
| mime-types-data           | 3.2019.0331  |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-05-15**
</details></pre>
</details>

**Comment by max-ott** [comment]
Hi there, could you please include the full error message as well as your stack trace and environment details? This would help us with eventually helping you! 👍

**Comment by nemno** [comment]
Hi! 

There is no error.

 As I described above, the issue is with the given code I wanted to update the code signing, and got the response:

[16:32:39]: Set Code Sign identity to: iPhone Distribution for target: xxx-xxx-xxx-1
[16:32:39]: Set Code Sign identity to: iPhone Distribution for target: Notification Service
[16:32:39]: Set Code Sign identity to: iPhone Distribution for target: xxx-xxx-xxx-2
[16:32:39]: Set Code Sign identity to: iPhone Distribution for target: xxx-xxx-xxxTests
[16:32:39]: Set Code Sign identity to: iPhone Distribution for target: xxx-xxx-xxxUITests
[16:32:39]: Set Code Sign identity to: iPhone Distribution for target: xxx-xxx-xxx-3
[16:32:40]: Successfully updated project settings to use Code Sign Style = 'Manual'
[16:32:40]: Modified Targets:
[16:32:40]: 	 * xxx-xxx-xxx-1
[16:32:40]: 	 * Notification Service
[16:32:40]: 	 * xxx-xxx-xxx-2
[16:32:40]: 	 * xxx-xxx-xxxTests
[16:32:40]: 	 * xxx-xxx-xxxUITests
[16:32:40]: 	 * xxx-xxx-xxx-3

so 
xxx-xxx-xxx-1
xxx-xxx-xxx-2
xxx-xxx-xxx-3

targets are ok, but I have 

xxx-xxx-xxx-4
xxx-xxx-xxx-5
xxx-xxx-xxx-6
xxx-xxx-xxx-7
xxx-xxx-xxx-8

targets and they are not in the list of the response and they are not updated of course. And as I mentioned I realised, if I create a new target with adding one it will be in the list of the response and it will be updated, but if I duplicate one, and try to update it, it won't be int the list of the response and won't be updated.

**Comment by max-ott** [comment]
You might want to check out the examples and add the targets in there: https://docs.fastlane.tools/actions/automatic_code_signing/#8-examples

**Comment by nemno** [comment]
But if I add a target explicitly in the **targets** field, it does not find it, so it does not matter.
You mean targets: [xxx-xxx-xxx-4, xxx-xxx-xxx-5] ... right?
I tried it. Did not work.

**Comment by janpio** [comment]
@nemno Can you please specify a non-existing target explicitly and post the _complete_ output you get when running the command/lane? This should give us an overview what targets are actually recognized by the code. If we know that, we can continue to debug this.

**Comment by nemno** [comment]
Here is the log with one duplicated target!
It's clearly visible it recognizes only 1 target, but I have 2:

DEBUG [2019-06-28 11:05:23.53]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/norbertnemes/Documents/Work/FastlaneTestProject/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/norbertnemes/Documents/Work/FastlaneTestProject/fastlane/Appfile'
-------
INFO [2019-06-28 11:05:23.84]: Driving the lane 'update_signing_settings' 🚀
INFO [2019-06-28 11:05:23.85]: ------------------------------------
INFO [2019-06-28 11:05:23.85]: --- Step: automatic_code_signing ---
INFO [2019-06-28 11:05:23.85]: ------------------------------------

+-----------------------+-------------------------------+
|           Summary for Automatic Codesigning           |
+-----------------------+-------------------------------+
| use_automatic_signing | false                         |
| code_sign_identity    | iPhone Distribution           |
| team_id               | ATGGD88ZP3                    |
| path                  | FastlaneTestProject.xcodeproj |
+-----------------------+-------------------------------+

INFO [2019-06-28 11:05:23.93]: Updating the Automatic Codesigning flag to disabled for the given project '/Users/norbertnemes/Documents/Work/FastlaneTestProject/FastlaneTestProject.xcodeproj/project.pbxproj'
WARN [2019-06-28 11:05:23.93]: Set Team id to: ATGGD88ZP3 for target: FastlaneTestProject
WARN [2019-06-28 11:05:23.94]: Set Code Sign identity to: iPhone Distribution for target: FastlaneTestProject
INFO [2019-06-28 11:05:23.95]: Successfully updated project settings to use Code Sign Style = 'Manual'
INFO [2019-06-28 11:05:23.95]: Modified Targets:
INFO [2019-06-28 11:05:23.95]: 	 * FastlaneTestProject
INFO [2019-06-28 11:05:23.95]: -----------------------------------------
INFO [2019-06-28 11:05:23.95]: --- Step: update_project_provisioning ---
INFO [2019-06-28 11:05:23.95]: -----------------------------------------

**Comment by nemno** [comment]
And here is the log when I explicitly added a new target.
It's in the list:

`DEBUG [2019-06-28 11:09:13.32]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/norbertnemes/Documents/Work/FastlaneTestProject/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/norbertnemes/Documents/Work/FastlaneTestProject/fastlane/Appfile'
-------
INFO [2019-06-28 11:09:13.48]: Driving the lane 'update_signing_settings' 🚀
INFO [2019-06-28 11:09:13.49]: ------------------------------------
INFO [2019-06-28 11:09:13.49]: --- Step: automatic_code_signing ---
INFO [2019-06-28 11:09:13.49]: ------------------------------------

+-----------------------+-------------------------------+
|           Summary for Automatic Codesigning           |
+-----------------------+-------------------------------+
| use_automatic_signing | false                         |
| code_sign_identity    | iPhone Distribution           |
| team_id               | ATGGD88ZP3                    |
| path                  | FastlaneTestProject.xcodeproj |
+-----------------------+-------------------------------+

INFO [2019-06-28 11:09:13.56]: Updating the Automatic Codesigning flag to disabled for the given project '/Users/norbertnemes/Documents/Work/FastlaneTestProject/FastlaneTestProject.xcodeproj/project.pbxproj'
WARN [2019-06-28 11:09:13.56]: Set Team id to: ATGGD88ZP3 for target: FastlaneTestProject
WARN [2019-06-28 11:09:13.56]: Set Code Sign identity to: iPhone Distribution for target: FastlaneTestProject
WARN [2019-06-28 11:09:13.57]: Set Team id to: ATGGD88ZP3 for target: ExplicitlyAddedTarget
WARN [2019-06-28 11:09:13.57]: Set Code Sign identity to: iPhone Distribution for target: ExplicitlyAddedTarget
INFO [2019-06-28 11:09:13.58]: Successfully updated project settings to use Code Sign Style = 'Manual'
INFO [2019-06-28 11:09:13.58]: Modified Targets:
INFO [2019-06-28 11:09:13.58]: 	 * FastlaneTestProject
INFO [2019-06-28 11:09:13.58]: 	 * ExplicitlyAddedTarget
INFO [2019-06-28 11:09:13.59]: -----------------------------------------
INFO [2019-06-28 11:09:13.59]: --- Step: update_project_provisioning ---
INFO [2019-06-28 11:09:13.59]: -----------------------------------------
`

**Comment by nemno** [comment]
And I have 3 targets, so the update should work on all of them
<img width="421" alt="Screenshot 2019-06-28 at 11 10 55 AM" src="https://user-images.githubusercontent.com/417450/60331675-7abe9d00-9995-11e9-89dc-6488255e0a64.png">

**Comment by nemno** [comment]
Also a suspicious thing:
**update_project_provisioning** command lists all the targets!

**Comment by janpio** [comment]
Interesting, so the other one is probably using some slightly different way to get it or something else is going wrong down the line. (I unfortunately don't have the time to go deeper here right now.)

**Comment by nemno** [comment]
I found the issue!

While I was browsing for solution I found these:

https://github.com/Mindera/fastlane-plugin-cosigner/pull/14/files

https://www.bountysource.com/issues/45555385-disable_automatic_code_signing-problem-seems-to-be-a-very-old-project-file-format-please-use-xcode-to-upgrade-to-atlease-0800

So I checked the TargetAttributes field in pbxproj file. And the suplicated target has no data in that container, so I placed the record there and the tool worked like a charm.

				TargetAttributes = {
					5AD6E03F22C60E2800B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
					5AD6E06622C610AE00B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
					5AD6E0B022CB6CC200B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};

So maybe this can be a spot to review in the code:

        # make sure TargetAttributes exist for all targets
        target_dictionary.each do |props|
          unless target_attributes.key?(props[:uuid])
            target_attributes[props[:uuid]] = {}
          end
        end

**Comment by janpio** [comment]
Can you show the before state of the `TargetAttributes` for documentation?

**Comment by nemno** [comment]
Before:
				TargetAttributes = {
					5AD6E03F22C60E2800B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
					5AD6E06622C610AE00B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
				};

After:

				TargetAttributes = {
					5AD6E03F22C60E2800B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
					5AD6E06622C610AE00B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
					5AD6E0B022CB6CC200B08184 = {
						CreatedOnToolsVersion = 10.1;
						DevelopmentTeam = XXXXXXXXXX;
						ProvisioningStyle = Manual;
					};
				};

**Comment by janpio** [comment]
Any idea how your project file got into this state? Seems to be non standard I guess.

**Comment by nemno** [comment]
This is a fresh test project made by me just to highlight this issue. So this is the standard behaviour.

**Comment by janpio** [comment]
Oh 💣 Then this is probably a bug on our side that should be fixed pretty quickly.

Can you describe the steps you took to create this project?

**Comment by nemno** [comment]
You can see it above!

Create a new project
 then duplicate a target, 
then try to use automatic_code_signing tool.

**Comment by janpio** [comment]
Thanks, when a contributor has the time they will try to recreate this and look into the code on how to solve this.
