### ISSUE TITLE
Unable to rollout to because it does not allow any existing users to upgrade to newly added APKS

### ISSUE THREAD

**Issue by dantesolis** [fastlane/fastlane#14776]
### Question Checklist

- [x] Updated fastlane to the latest version 
 
- At the moment running `fastlane 2.121.0`

- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

- Yes

- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)

- Yes

- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues

- Yes

### Question Subject
What tool/action do you have a question about?

- `fastlane supply`

Is this a question about documentation?
- No

Is this a question about a third party plugin? (If so, please go to the plugin repository first)
- No

#### Question Description

I'm trying to use `fastlane upload_to_play_store()` command using `circleci`, but for some  reason I keep getting the following message on my circleci: 

```
Google Api Error: apkNoUpgradePaths: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs. - You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.
```

Here is how I'm calculating the version code:

```ruby
# android/Fastlane

default_platform(:android)

platform :android do
  before_all do
    ENV["VERSION_NAME"] = "1.0.#{ENV['CIRCLE_BUILD_NUM']}"
    if ENV["CIRCLE_BRANCH"] == "prod" then
      ENV["VERSION_CODE"] = (ENV["CIRCLE_BUILD_NUM"].to_i + 1000).to_s
      ENV["VERSION_NAME_SUFFIX"] = "-prod"
    elsif ENV["CIRCLE_BRANCH"] == "staging" then
      ENV["VERSION_CODE"] = (ENV["CIRCLE_BUILD_NUM"].to_i + 2000).to_s
      ENV["VERSION_NAME_SUFFIX"] = "-beta"
    elsif ENV["CIRCLE_BRANCH"] == "master" then
      ENV["VERSION_CODE"] = (ENV["CIRCLE_BUILD_NUM"].to_i + 3000).to_s
      ENV["VERSION_NAME_SUFFIX"] = "-alpha"
    else
      ENV["VERSION_CODE"] = (ENV["CIRCLE_BUILD_NUM"].to_i * 10000).to_s
      ENV["VERSION_NAME_SUFFIX"] = "-internal"
    end
  end

  desc "Build the Android APK"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Deploy to Google Play"
  lane :deploy do
    upload_to_play_store(
      track: case ENV["CIRCLE_BRANCH"]
        when "prod"
          "production"
        when "staging"
          "beta"
        when "master"
          "alpha"
        else
          "internal"
      end,
      json_key: "key.json",
      apk: "app/build/outputs/apk/release/app-release.apk",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
```

```java
# app/build.gradle

...omitted_code

versionNameSuffix (System.env.VERSION_NAME_SUFFIX ? System.env.VERSION_NAME_SUFFIX : "-internal")

...omitted_code
```

Thanks

**Comment by YajJackson** [comment]
@dantesolis I am in a similar situation, I'm going to assume you're using cordova based on your apk output. I was able to successfully upload an apk to play store while using the `android-versionCode` attribute in config.xml, but obviously needed to find a way to increment the versionCode on circleci. 

Since there isn't a solid way to auto increment the android versionCode I decided to try using the approach outlined here: https://synaptiklabs.com/posts/auto-updating-an-android-projects-versioncode/

In app/build.gradle:
```
def buildVersionCode = Integer.parseInt(new Date().format("yyMMddHH"))
android {
...
    defaultConfig {
        ...
        versionCode buildVersionCode
        ...
    }
...
```
Initially I received the same error you posted:
`Google Api Error: apkNoUpgradePaths: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs. - You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.`

After some digging I found that this is usually because the versionCode of the new apk is lower than the one currently in the app store.

Previously my versionCode was 20190000. after adding an extra digit to my buildVersionCode I was able to successfully upload my apk to Google Play.

As an extra note: I tried using [fastlane-plugin-increment_version_code](https://github.com/Jems22/fastlane-plugin-increment_version_code) and found the lack of documentation infuriating. If anyone has a real example of how to use this plugin I would love to see it.

**Comment by janpio** [comment]
> As an extra note: I tried using [fastlane-plugin-increment_version_code](https://github.com/Jems22/fastlane-plugin-increment_version_code) and found the lack of documentation infuriating. If anyone has a real example of how to use this plugin I would love to see it.

You should open an issue over at the plugin: https://github.com/Jems22/fastlane-plugin-increment_version_code/issues

**Comment by dantesolis** [comment]
@YajJackson glad you got it to work as well. I'm using `react-native` I think this issue can be closed since the problem was, both for you and me I think, in the way we calculated the `versionCode apk` vs the one that was already on the play store, not with `fastlane` itself.

@janpio thanks for the pointer, will try to add some docs down there. 👍 

The problem was fixed with the below code, posted here as a reference for those who might use `circleci` + `fastlane` for their build and/or would like and example.

```java
# android/app/build.gradle

     ... omitted_code

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

     defaultConfig {

       ... omitted_code

        versionCode (System.env.VERSION_CODE ? Integer.parseInt(System.env.VERSION_CODE) : 0) //  this comes from CIRCLE_BUILD_NUMBER see `fastlane below`
        versionName (System.env.VERSION_NAME ? System.env.VERSION_NAME : "1.0")
        versionNameSuffix (System.env.VERSION_NAME_SUFFIX ? System.env.VERSION_NAME_SUFFIX : "-internal")
    
       ... omitted_code
    }
```

```ruby

# android/fastlane 

default_platform(:android)

platform :android do

  def is_correct_branch?(branch)
    return ensure_git_branch(branch: branch)
  end

  before_all do
    ENV["VERSION_NAME"] = "1.0.#{ENV['CIRCLE_BUILD_NUM']}"
    ENV["VERSION_CODE"] = (ENV["CIRCLE_BUILD_NUM"].to_i + 600000000).to_s
    if ENV["CIRCLE_BRANCH"] == "staging" then
      ENV["VERSION_NAME_SUFFIX"] = "-beta"
    elsif ENV["CIRCLE_BRANCH"] == "master" then
      ENV["VERSION_NAME_SUFFIX"] = "-alpha"
    elsif ENV["CIRCLE_BRANCH"] == "pentest" then
      ENV["VERSION_NAME_SUFFIX"] = "-pentest"
    else
      ENV["VERSION_NAME_SUFFIX"] = "-internal"
    end
  end


  desc "Build the Android APK"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Deploy to Google Play"
  lane :deploy do

    supply(  # alias for_upload_to_play_store
      track: case ENV["CIRCLE_BRANCH"]
        when "prod"
          is_correct_branch?(ENV["CIRCLE_BRANCH"])
          "production"
        when "staging"
          is_correct_branch?(ENV["CIRCLE_BRANCH"])
          "beta"
        when "master"
          is_correct_branch?(ENV["CIRCLE_BRANCH"])
          "alpha"
        when "pentest"
          is_correct_branch?(ENV["CIRCLE_BRANCH"])
          "internal"
        else
          is_correct_branch?(ENV["CIRCLE_BRANCH"]) # all other branches in addition to master
          "alpha"
      end,
      json_key: "key.json",
      apk: "app/build/outputs/apk/release/app-release.apk",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    slack(
      message: "Android app successfully built and released! Go and have a drink 🥤",
      payload: {
        "Build Date" => Time.new.to_s,
        "Built by" => "CircleCI + Fastlane"
      }
    )
  end
end
```
