### ISSUE TITLE
[deliver] iOS screenshot uploader: wrong order

### ISSUE THREAD

**Issue by Semmu** [fastlane/fastlane#14785]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When uploading 10 screenshots to the iOS App Store, deliver uploaded them in the wrong order. It listed files in lexical order, not numerical, so the upload order was 1, 10, 2, 3, ...

This obviously resulted in wrong ordering of screenshots on the App Store.

##### Command executed

We executed a custom shell script, which calls a lane, which calls deliver like this:

```ruby
deliver(
  metadata_path: ENV['METADATA_PATH'],
  screenshots_path: ENV['SCREENSHOTS_PATH'],
  skip_binary_upload: true,
  skip_metadata: true,
  build_number: ENV['BUILD_NUMBER'], 
  app_version: ENV['VERSION_NUMBER'],
  force: true
)
```

##### Complete output when running fastlane, including the stack trace and command used

Can't provide stacktrace and command now, sample output here (with sensitive information replaced with `[...]`)

<details>
  <pre>[18:21:46]: Making sure the latest version on App Store Connect matches '[...]' from the ipa file...
[18:21:52]: '[...]' is the latest version on App Store Connect
[18:21:59]: Starting with the upload of screenshots...
[✔] Activating language de-DE...
[18:22:10]: Uploading [...] screenshots for language de-DE
[18:22:10]: Uploading '[...]/ios/.fastlane/store_metadata/main/screenshots/de-DE/1
DE_iPad2nd_AS0 - [...].png'...
[18:22:48]: Uploading '[...]/ios/.fastlane/store_metadata/main/screenshots/de-DE/1
ipadPro129_DE_iPad3rd_AS0 - [...].png'...
[18:23:29]: Uploading '[...]/ios/.fastlane/store_metadata/main/screenshots/de-DE/10
 DE_iPad2nd_AS10 - [...].png'...
[18:23:40]: Uploading '[...]/ios/.fastlane/store_metadata/main/screenshots/de-DE/10
 ipadPro129_DE_iPad3rd_AS10 - [...].png'...
[18:23:45]: Uploading '[...]/ios/.fastlane/store_metadata/main/screenshots/de-DE/2
DE_iPad2nd_AS0 - [...].png'...
[18:24:15]: Uploading '[...]/ios/.fastlane/store_metadata/main/screenshots/de-DE/2
ipadPro129_DE_iPad3rd_AS0 - [...].png'...
</pre>
</details>

### Environment

Part of the output, sensitive information removed.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                       |
| --------------------------- | ----------------------------------------------------------- |
| OS                          | 10.14.1                                                     |
| Ruby                        | 2.3.1                                                       |
| Bundler?                    | true                                                        |
| Git                         | git version 2.20.1                                          |
| Installation Source         | [...]/vendor/bundle/ruby/2.3.0/bin/fastlane                 |
| Host                        | Mac OS X 10.14.1 ([...])                                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                                |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                                 |
| Is contained                | false                                                       |
| Is homebrew                 | false                                                       |
| Is installed via Fabric.app | false                                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                 |
| Xcode Version               | 10.1                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./.fastlane/Fastfile`</summary>

(removed, contains sensitive information)

</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.6.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

(removed as well)

</details>

*generated on:* **2019-05-20**
</details>

### Workaround

To solve the issue without manually renaming a lot of files, I wrote this code to append a `0` to the files which do not begin with 2 numerical characters. Obviously this modifies filenames, which is not a good solution in the long run, but quickly solved my problem. And then the upload order was 01, 02, 03, ..., 09, 10.

```ruby
def ensure_numerical_order_for_screenshots
  get_languages.each { |lang|
    path = get_images_folder_for_language(lang)
    images = get_image_files_for_language(lang)
    images.each { |image|
      if image =~ /^[0-9]{1}[^0-9]{1}.*$/ # if only the first char is numeric
        File.rename("#{path}/#{image}", "#{path}/0#{image}")
      end
    }
  }
end
```

**Comment by Semmu** [comment]
Am I the only one affected by this bug? Or is there a trivial solution I missed/didn't use?

**Comment by janpio** [comment]
We should probably look into how we order the files before upload, and fix the cases you mentioned when you use more then 9 screenshots to work as expected.
