### ISSUE TITLE
[Match] Fastlane-Swift Match does not use `Matchfile.swift`

### ISSUE THREAD

**Issue by iandundas** [fastlane/fastlane#14789]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
[This commit](https://github.com/fastlane/fastlane/commit/d59dd6eac43225e68ca0e23dc138b9ec8070a0d1) adds the ability to run `bundle exec fastlane match init swift` to generate a `Matchfile.swift` file.

However, running `bundle exec fastlane match` does not make use of this generated file, and I can't find an alternative command that does. Am I correct that it's not been implemented yet?

##### Command executed

`bundle exec fastlane match` 
No error, just a prompt asking for more information (given already in Matchfile.swift)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀

+-----------------------+----------------+
|       Summary for match 2.121.1        |
+-----------------------+----------------+
| type                  | development    |
| readonly              | false          |
| storage_mode          | git            |
| git_branch            | master         |
| shallow_clone         | false          |
| clone_branch_directly | false          |
| keychain_name         | login.keychain |
| force                 | false          |
| force_for_new_devices | false          |
| skip_confirmation     | false          |
| skip_docs             | false          |
| platform              | ios            |
| verbose               | false          |
+-----------------------+----------------+

[15:42:33]: To not be asked about this value, you can specify it using 'git_url'
[15:42:33]: URL to the git repo containing all the certificates:
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.14.4                                         |
| Ruby                        | 2.6.1                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.18.0                              |
| Installation Source         | ~/.rbenv/versions/2.6.1/bin/fastlane            |
| Host                        | Mac OS X 10.14.4 (18E226)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode10_2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    
    func beforeAll() {
        xcodeVersion.becomeActive()
    }

    func lintLane(withOptions options: [String: String]?) {
        desc("This lane will lint the codebase and report violations to the associated PR")

        let outputFile = "linter_output"

        swiftlint(
            outputFile: outputFile,
            configFile: ".swiftlint.yml",
            ignoreExitStatus: true,
            executable: "Pods/SwiftLint/swiftlint"
        )

        let violations = lint(path: outputFile)

        guard violations.isEmpty else {
            // Only report to PR when running on CI:
            guard options?.isCI ?? false else { return }

            reportLintingToPR(violations: violations, options: options)
            return // or fatalError() ?
        }
    }
    
    func testLane(withOptions options: [String: String]?) {
        desc("This lane will create a test build and run the tests")
        
        if options?.isCI ?? false {
            // We're running on CI so we don't want anything remaining from the last execution.
            println(message: "Resetting to git HEAD")
            resetGitRepo(force: true)
        }
        
        runTests(
            scheme: "Development",
            clean: true
        )
    }

    func developmentLane(withOptions options: [String: String]?) {
        desc("This lane will create a development build and upload it to hockeyapp (Enterprise build)")

        let releaseNotes = createReleaseNotes(fromCommit: options?["from_commit"], toCommit: options?["to_commit"])

        setVersionAndBuildNumber(versionModifier: options?["version_modifier"])
        
        syncCodeSigning(
            type: "development",
            readonly: true,
            appIdentifier: matchfile.appIdentifier,
            username: matchfile.username,
            teamId: matchfile.teamId,
            gitUrl: matchfile.gitUrl)
        
        syncCodeSigning(
            type: "enterprise",
            readonly: true,
            appIdentifier: matchfile.appIdentifier,
            username: matchfile.username,
            teamId: matchfile.teamId,
            gitUrl: matchfile.gitUrl)
        
        // Using Match we make sure that all provisioning profiles are synced
        buildIosApp(scheme: "Development", clean: true, exportMethod: "enterprise")

        hockey(apiToken: hockeyApiToken,
               notes: releaseNotes,
               notesType: "Markdown",
               teams: hockeyTeamID,
               publicIdentifier: hockeyAppIdentifier,
               bypassCdn: true)
    }

    func testFlightLane(withOptions options: [String: String]?) {
        desc("This lane will create a development build and upload it to hockeyapp (Enterprise build)")
        
        createAppStoreBuild(withOptions: options)
        
        pilot(username: matchfileAppStore.username, appIdentifier: matchfileAppStore.appIdentifier.first!, appleId: matchfileAppStore.teamId, distributeExternal: false)
    }
    
    func appStoreLane(withOptions options: [String: String]?) {
        desc("This lane will create a AppStore build and upload it to the sAppStore")
        
        createAppStoreBuild(withOptions: options)
        
        uploadToAppStore(username: matchfileAppStore.username, app: matchfileAppStore.appIdentifier.first!)
    }
    
    private func createAppStoreBuild(withOptions options: [String: String]?) {
        
        setVersionAndBuildNumber(versionModifier: options?["version_modifier"])
        
        // Using Match we make sure that all provisioning profiles are synced
        syncCodeSigning(
            type: "development",
            readonly: true,
            appIdentifier: matchfileAppStore.appIdentifier,
            username: matchfileAppStore.username,
            teamId: matchfileAppStore.teamId,
            gitUrl: matchfileAppStore.gitUrl)
        
        syncCodeSigning(
            type: "appstore",
            readonly: true,
            appIdentifier: matchfileAppStore.appIdentifier,
            username: matchfileAppStore.username,
            teamId: matchfileAppStore.teamId,
            gitUrl: matchfileAppStore.gitUrl)
        
        buildIosApp(scheme: "Store", clean: true, exportMethod: "app-store")
        
        // The AppStore build will also be uploaded to HockeyApp to be able monitor the crashes
        hockey(apiToken: hockeyApiToken, teams: nil, publicIdentifier: hockeyAppIdentifierAppStore)
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.1        |
| etc                       | 1.0.1        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.6.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| cocoapods                 | 1.6.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-05-22**
</details>

**Comment by dan-ryan** [comment]
I had issues with "Appfile.swift" not being read. I moved to Ruby instead.
with https://github.com/fastlane/fastlane/issues/14719
