### ISSUE TITLE
[deliver] Screenshot upload: purge screenshots for same device type

### ISSUE THREAD

**Issue by Semmu** [fastlane/fastlane#14784]
### Feature Request

(Hi everyone! 👋 )

#### Motivation Behind Feature
It would be great if deliver removed screenshots for devices which it uploads new set of screenshots for, without touching others.

#### Feature Description
We ran into issues when uploading new iOS screenshots: if the new set for a specific device type had less images than the previously uploaded one, then it would not remove all the images from the previous set, but "merge" them by overwriting the first pictures with the new set. This results in the final screenshot set containing leftover images from the previous set, which is not desirable.

There is an option for deliver to remove screenshots before uploading the new set (`overwrite_screenshots `), but that removes screenshots [for every device](https://github.com/fastlane/fastlane/blob/bbc26e716010e48871e692436a4e2b22e259cc01/deliver/lib/deliver/upload_screenshots.rb#L23), which is also not desirable if we want to upload a new set of screenshots for only specific devices.

So it would be awesome if there was an other option (or it was the default) to purge screenshots per device if that device is going to get a new set of screenshots.

If this is the current behaviour, then something strange happened in our systems and sorry for wasting your time 😄 

#### Alternatives or Workarounds
We had to manually remove device specific screenshots before uploading the new set using deliver.

**Comment by Semmu** [comment]
What do you think? Am I the only one who would like to see this feature or am I completely missing something?

**Comment by janpio** [comment]
> So it would be awesome if there was an other option (or it was the default) to purge screenshots per device if that device is going to get a new set of screenshots.

That sounds like a reasonable request. I am not sure what is documented, if `deliver` should already _replace_ the screenshots (which indicated removal of old ones) or _overwrite_ them (which could be used to justify the current behavior) - but I agree what you describe is certainly more what one would expect.

I guess this is one of these edge cases that loads of people run into, but noone really figures out what was going on and just fixes it manually. Thanks for reporting!
