### ISSUE TITLE
[pilot] Rename `apple_id` option to `apple_app_id` (or similar)

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14788]
Pilot having an `apple_id` option that is something else than the [`apple_id` in `Appfile`](https://docs.fastlane.tools/advanced/Appfile/#appfile) is pretty confusing (as for example https://github.com/fastlane/fastlane/issues/14783#issuecomment-494370288 showed).

We should deprecate `apple_id` (we can't just remove it as this would not be backwards compatible), move it to the end of the option list and add a new option `apple_app_id` to take its place. 

(The code around `apple_id` in _pilot_ could probably also use a good cleanup at the same time to make sure those two can not be confused any more).

**Comment by mollyIV** [comment]
> (The code around apple_id in pilot could probably also use a good cleanup at the same time to make sure those two can not be confused any more).

Quite a big PR is coming: https://github.com/fastlane/fastlane/pull/14791 and it relates to `pilot` module. I think it contains more than the cleanup that we would like to do in this ticket, right? 🤔 

Taking into account the above, I would suggest just to add `apple_app_id ` to `options` and modify only the parts that should use a new parameter in `pilot`. 

WDYT @janpio ?

**Comment by janpio** [comment]
Yes, it probably makes sense for #14791 to be merged before this is tackled - otherwise this will probably cause merged conflicts over there, or code that is touched here is totally removed etc.

**Comment by joshdholtz** [comment]
@janpio @mollyIV I can deprecate it in my PR and add a new one called `app_id` 😊 Thoughts?

**Comment by mollyIV** [comment]
@joshdholtz sounds good 💪 The refactoring is already pretty big, so one more small change cannot hurt 🙂 `app_id` will do 👍

**Comment by janpio** [comment]
Is `app_id` unique? I have something in the back of my mind that there were different app IDs in use somewhere, which is why this was called the "apple app id".

**Comment by salmanasiddiqui** [comment]
`app_id` is usually used for app identifier..  this apple_id is store id..
what do you guys think about having one file of base parameters that fastlane supports
- app_id
- store_id
- app_name
- team_name
- team_id
- username
- password
- etc etc
All actions should use these params definition so that these params are consistent across actions? those actions can have their own custom params definition ofcourse. But these base params will be shared then, same env vars will be used across actions etc.

**Comment by janpio** [comment]
Having a consistent parameter/option naming scheme sure would be beneficial, the problem will be to go through all existing actions and get an overview. Also, changing things is hard as we don't want to break backwards compatibility (existing fastlane setups should keep working). But if you want to look into improving this, you are more than welcome - fastlane would greatly benefit from it.

**Comment by mollyIV** [comment]
https://github.com/fastlane/fastlane/pull/14791 has been merged 🙌 

Cannot see an `apple_id` parameter deprecation in `pilot`'s options though (@joshdholtz please correct me if I am wrong) 🤔 

If it wasn't, we would still need to agree on the new parameter name. I would vote for @janpio suggestion: `apple_app_id` 👍 

Once we agree on the new param name, I could tackle this one 💪
