### ISSUE TITLE
Export error, exportOptionsPlist error, Exit code 70 on Travis

### ISSUE THREAD

**Issue by ashfurrow** [fastlane/fastlane#14798]
🔑 

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`gym` is failing with the following error:

```
xcodebuild -exportArchive -exportOptionsPlist /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/gym_config20190522-7155-lu6ej8.plist -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2019-05-22/Emission 2019-05-22 18.38.59.xcarchive' -exportPath /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/gym_output20190522-7155-465ami
2019-05-22 18:46:43.155 xcodebuild[12139:24336] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/Emission_2019-05-22_18-46-43.154.xcdistributionlogs'.
2019-05-22 18:46:43.266 xcodebuild[12139:24336] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store
```

I can run the command locally and it works fine. It lists Exit code 70. The archive appears to succeed, but exporting it fails. 

<details><summary>More error details</summary>

```
[18:46:32]: ▸ Archive Succeeded
[18:46:33]: Generated plist file with the following values:
[18:46:33]: ▸ -----------------------------------------
[18:46:33]: ▸ {
[18:46:33]: ▸   "provisioningProfiles": {
[18:46:33]: ▸     "net.artsy.Emission": "match AppStore net.artsy.Emission"
[18:46:33]: ▸   },
[18:46:33]: ▸   "method": "app-store",
[18:46:33]: ▸   "signingStyle": "manual"
[18:46:33]: ▸ }
[18:46:33]: ▸ -----------------------------------------
RVM detected, forcing to use system ruby
Now using system ruby.
** Updating RubyGems to the latest compatible version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
+xcodebuild -exportArchive -exportOptionsPlist /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/gym_config20190522-7155-lu6ej8.plist -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2019-05-22/Emission 2019-05-22 18.38.59.xcarchive' -exportPath /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/gym_output20190522-7155-465ami
2019-05-22 18:46:43.155 xcodebuild[12139:24336] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/Emission_2019-05-22_18-46-43.154.xcdistributionlogs'.
2019-05-22 18:46:43.266 xcodebuild[12139:24336] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}
** EXPORT FAILED **
[18:46:43]: Exit status: 70
```

</details>

The CI build is open source, so you can see the failure here: https://travis-ci.org/artsy/emission-nebula/builds/535885073#L3253 (Note that we attempt the build twice, so Travis lists that build as "cancelled", though it would've failed the second time too.)

I've looked around the internet and can't find anyone else with this problem, Fastlane or otherwise. Any help would be appreciated.

##### Command executed

`bundle exec fastlane ci_deploy`

##### Complete output when running fastlane, including the stack trace and command used

You can see the raw build log here: https://api.travis-ci.org/v3/job/535885074/log.txt 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-10.2.1.app/Contents/Developer/             |
| Xcode Version               | 10.2.1                                                         |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is documented in the Artsy Blog:
# http://artsy.github.io/blog/2017/07/31/fastlane-travis-weekly-deploys/
require 'cgi'
# Clones Emission and sets it up
lane :setup do
  Dir.chdir("..") do
    sh "rm -rf emission" if Dir.exist? "emission"
    sh "git clone https://github.com/artsy/emission.git"
    Dir.chdir("emission") do
      sh ". ~/.nvm/nvm.sh && nvm use && npm install yarn --global"
      sh "yarn install"
      sh "yarn relay"
      sh "yarn bundle-with-storybooks"
    end
    Dir.chdir("emission/Example") do
      if ENV['ARTSY_API_KEY'] && ENV['ARTSY_API_SECRET'] && ENV['STRIPE_PUBLISHABLE_KEY']
        sh "bundle exec pod keys set ArtsyAPIClientKey $ARTSY_API_KEY"
        sh "bundle exec pod keys set ArtsyAPIClientSecret $ARTSY_API_SECRET"
        sh "bundle exec pod keys set StripePublishableKey $STRIPE_PUBLISHABLE_KEY"
      end
      sh "bundle exec pod repo update"
      # Run `pod install` twice, otherwise pre-patch is not applied and build will fail with CocoaPods-Keys problems.
      sh "bundle exec pod install"
      sh "bundle exec pod install"
    end
    stamp_plist
  end
end
# Lets the CI run a bunch of jobs, and share ENV vars between them
lane :ci_deploy do
  setup_signing
  stamp_plist
  ship
end
# The main job for Fastlane in this repo, you can run this on your computer
# You can run it via `bundle exec fastlane ship`
lane :ship do
  # We were having issues with building an a few folders deep.
  # The /Pods bit is because we can rely on it being there, see
  # this link: https://docs.fastlane.tools/advanced/#directory-behavior
  #
  Dir.chdir("../emission/Example/Pods") do
    disable_automatic_code_signing(
      path: 'Emission.xcodeproj',
      team_id: '23KMWZ572J',
      targets: ['Emission'],
      profile_name: 'match AppStore net.artsy.Emission'
    )
    begin
      gym(workspace: "Emission.xcworkspace",
        configuration: "Deploy",
        scheme: "Emission",
        silent: true, # Travis cuts off our logs because they're too long.
        export_method: "app-store",
        )
      sh "set +e" # Workaround for Travis bug. See https://github.com/travis-ci/travis-ci/issues/6522
      # Right now the second build of the entire CI seems to work,
      # so maybe we can shortcut that by doing it inside the one CI run.
    rescue => exception
      gym(workspace: "Emission.xcworkspace",
        configuration: "Deploy",
        scheme: "Emission",
        silent: true,
        export_method: "app-store",
      )
      sh "set +e" # Workaround for Travis bug. See https://github.com/travis-ci/travis-ci/issues/6522
    end
  end
  # Get the current master changes from the CHANGELOG, filtering out HTML comments, for sending to Testflight
  changelog = "../emission/CHANGELOG.md"
  upcoming_release_notes = CGI.escape_html(File.read(changelog).gsub(/<![^>]*>/, '').split("\n### ")[1])
  # Ship to testflight
  pilot(changelog: upcoming_release_notes,
    itc_provider: 'ArtsyInc',
    distribute_external: true,
    groups: ['Artsy Collaborators'])
  # Log into iTunes connect, get the latest version of the app we shipped, and how many builds we've sent
  client = Spaceship::Tunes.login(ENV["FASTLANE_USERNAME"], ENV["FASTLANE_PASSWORD"])
  client.team_id = "479887"
  app = Spaceship::Tunes::Application.find("net.artsy.Emission")
  latest_version = app.build_trains.versions.sort.last
  # Do a tag, we use a http git remote so we can have push access
  # as the default remote for travis is read-only. This needs to be
  # inside the emission repo, instead of our own.
  Dir.chdir("../emission/Example/") do
    tag = "deploy-#{latest_version}-#{Time.new.strftime("%Y.%m.%d.%H")}"
    add_git_tag(tag: tag)
    if ENV["GITHUB_SUBMODULES_USER"]
      writable_remote = "https://#{ENV['GITHUB_SUBMODULES_USER']}@github.com/artsy/emission.git"
      sh "git remote add http #{writable_remote}"
    else
      sh "git remote add http https://github.com/artsy/emission.git"
    end
    push_git_tags(remote: "http")
  end
  slack message: "There is a new Emission beta available on Testflight.",
        payload: {
          "Version" => latest_version,
          "What's new" => upcoming_release_notes
        },
        default_payloads: []
end
# In case you need to update the signing profiles for this app
lane :update_signing do
  match(type: "appstore")
end
# Used by CI, will not sneakily update (the CI only has read-only access to the repo anyway)
lane :setup_signing do
  setup_travis
  match(type: "appstore")
end
# Minor plist modifications
lane :stamp_plist do
  plist = "emission/Example/Emission/Info.plist"
  # Increment build number to current date
  build_number = Time.new.strftime("%Y.%m.%d.%H")
  `/usr/libexec/PlistBuddy -c "Set CFBundleVersion #{build_number}" "#{plist}"`
end
# Mainly so we don't forget to include these vars in the future
lane :validate_env_vars do
  unless ENV["FASTLANE_USERNAME"] && ENV["FASTLANE_PASSWORD"] && ENV["MATCH_PASSWORD"]
    raise "You need to set FASTLANE_USERNAME, FASTLANE_PASSWORD and MATCH_PASSWORD in your environment"
  end
  unless ENV["SLACK_URL"]
    raise "You need to set SLACK_URL (#{ENV['SLACK_URL']}) in your environment."
  end
end
# If the weekly task fails, then ship a message, a success would also send
error do |_, exception|
  slack(message: "Error Deploying Emission: #{exception}",
        success: false,
        payload: { Output: exception.to_s })
end
```

</details>
<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "net.artsy.Emission"
apple_id "[secure]"
team_name "Art.sy Inc."
team_id "23KMWZ572J"
itc_team_id '479887'
```

</details>

### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:
**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version       |
| -------------------------- | ------------- |
| did_you_mean               | 1.0.0         |
| bundler                    | 2.0.1         |
| io-console                 | 0.4.5         |
| CFPropertyList             | 3.0.0         |
| ZenTest                    | 4.11.2        |
| RubyInline                 | 3.12.4        |
| concurrent-ruby            | 1.1.5         |
| i18n                       | 0.9.5         |
| minitest                   | 5.11.3        |
| thread_safe                | 0.3.6         |
| tzinfo                     | 1.2.5         |
| activesupport              | 4.2.11.1      |
| public_suffix              | 2.0.5         |
| addressable                | 2.6.0         |
| atomos                     | 0.1.3         |
| babosa                     | 1.0.2         |
| claide                     | 1.0.2         |
| fuzzy_match                | 2.0.4         |
| nap                        | 1.1.0         |
| cocoapods-core             | 1.6.1         |
| cocoapods-deintegrate      | 1.0.3         |
| cocoapods-downloader       | 1.2.2         |
| cocoapods-plugins          | 1.0.0         |
| cocoapods-search           | 1.0.0         |
| cocoapods-stats            | 1.1.0         |
| netrc                      | 0.11.0        |
| cocoapods-trunk            | 1.3.1         |
| cocoapods-try              | 1.1.0         |
| colored2                   | 3.1.2         |
| escape                     | 0.0.4         |
| fourflusher                | 2.2.0         |
| gh_inspector               | 1.1.3         |
| molinillo                  | 0.6.6         |
| ruby-macho                 | 1.4.0         |
| nanaimo                    | 0.2.6         |
| xcodeproj                  | 1.9.0         |
| cocoapods                  | 1.6.1         |
| cocoapods-fix-react-native | 2019.03.19.11 |
| dotenv                     | 2.7.2         |
| osx_keychain               | 1.0.2         |
| cocoapods-keys             | 2.1.0         |
| coderay                    | 1.1.2         |
| colored                    | 1.2           |
| highline                   | 1.7.10        |
| commander-fastlane         | 4.4.6         |
| declarative                | 0.0.10        |
| declarative-option         | 0.1.0         |
| digest-crc                 | 0.4.1         |
| unf_ext                    | 0.0.7.6       |
| unf                        | 0.1.4         |
| domain_name                | 0.5.20180417  |
| emoji_regex                | 1.0.1         |
| excon                      | 0.64.0        |
| multipart-post             | 2.0.0         |
| faraday                    | 0.15.4        |
| http-cookie                | 1.0.3         |
| faraday-cookie_jar         | 0.0.6         |
| faraday_middleware         | 0.13.1        |
| fastimage                  | 2.1.5         |
| jwt                        | 2.1.0         |
| memoist                    | 0.16.0        |
| multi_json                 | 1.13.1        |
| os                         | 1.0.1         |
| signet                     | 0.11.0        |
| googleauth                 | 0.6.7         |
| httpclient                 | 2.8.3         |
| mime-types-data            | 3.2019.0331   |
| mime-types                 | 3.2.2         |
| uber                       | 0.1.0         |
| representable              | 3.0.4         |
| retriable                  | 3.1.2         |
| google-api-client          | 0.23.9        |
| google-cloud-env           | 1.0.5         |
| google-cloud-core          | 1.3.0         |
| google-cloud-storage       | 1.16.0        |
| json                       | 2.2.0         |
| mini_magick                | 4.5.1         |
| multi_xml                  | 0.6.0         |
| plist                      | 3.5.0         |
| rubyzip                    | 1.2.2         |
| security                   | 0.1.3         |
| naturally                  | 2.2.0         |
| simctl                     | 1.6.5         |
| slack-notifier             | 2.3.2         |
| terminal-notifier          | 2.0.0         |
| unicode-display_width      | 1.6.0         |
| terminal-table             | 1.8.0         |
| tty-screen                 | 0.7.0         |
| tty-cursor                 | 0.6.1         |
| tty-spinner                | 0.9.0         |
| word_wrap                  | 1.0.0         |
| rouge                      | 2.0.7         |
| xcpretty                   | 0.3.0         |
| xcpretty-travis-formatter  | 1.0.0         |
| method_source              | 0.9.2         |
| pry                        | 0.12.2        |

</details>
*generated on:* **2019-05-22**

</details>

**Comment by OxenBoxen** [comment]
I don't have a solution to this, but I wanted to post that I too, am running into this issue.

gymfile: 

`default_platform(:ios)

desc "Create ipa"

lane :build do
  build_ios_app(
    codesigning_identity: "iPhone Distribution: XXX ",
    export_options: {
      method: "app-store",
      teamID: "XXX",
      compileBitcode: false,
      uploadSymbols: false,
      uploadBitcode: false,
      signingCertificate: "iPhone Distribution: XXX",
      signingStyle: "manual",
      provisioningProfiles: { 
        "com.xxx.xxx" => "XXX"
      }
    }
  )
end`

**Comment by younes200** [comment]
I'm running in the same issue. works fine with xcode archive

**Comment by janpio** [comment]
@OxenBoxen @younes200 Are you on Travis CI as well?

@ashfurrow Can you compare the Circle CI output with your local output? Anything jumps out to you being different that could cause this?

**Comment by ashfurrow** [comment]
I’m travelling right now so I’ll get back to you next week with a more precise answer, but I did notice that on CI, logs would indicate that the Ruby version was being switched right before the error happened. It’s included in the logs above.

**Comment by younes200** [comment]
@janpio I'm on GitLab CI, same local output except on CI, xcode ended with `error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store`

**Comment by janpio** [comment]
> same local output except on CI, xcode ended with `error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store`

That's strange, isn't it? That makes it sound like the CI Xcode seems to expect a different parameter in the exportOptions than the local one - or am I misreading something here?

**Comment by ashfurrow** [comment]
@janpio Here's some more details – below I have the local and CI versions of the same command (`bundle exec fastlane ship`).

<details><summary>Local version, works as expected</summary>

```
[16:07:34]: ▸ Archive Succeeded
[16:07:34]: Generated plist file with the following values:
[16:07:34]: ▸ -----------------------------------------
[16:07:34]: ▸ {
[16:07:34]: ▸   "provisioningProfiles": {
[16:07:34]: ▸     "net.artsy.Emission": "match AppStore net.artsy.Emission"
[16:07:34]: ▸   },
[16:07:34]: ▸   "method": "app-store",
[16:07:34]: ▸   "signingStyle": "manual"
[16:07:34]: ▸ }
[16:07:34]: ▸ -----------------------------------------
warning: /Users/ashfurrow/Library/Developer/Xcode/Archives/2019-06-03/App 2019-06-03 16.04.52.xcarchive/BCSymbolMaps/Emission-armv7.bcsymbolmap: No such file or directory. Not unobfuscating.
warning: /Users/ashfurrow/Library/Developer/Xcode/Archives/2019-06-03/App 2019-06-03 16.04.52.xcarchive/BCSymbolMaps/Emission-arm64.bcsymbolmap: No such file or directory. Not unobfuscating.

[16:08:11]: Successfully exported and compressed dSYM file
[16:08:11]: Successfully exported and signed the ipa file:
[16:08:11]: /Users/ashfurrow/bin/emission-nebula/emission/Example/App.ipa
```

</details>

<details><summary>CI version, doesn't work</summary>

```
[18:46:32]: ▸ Archive Succeeded
[18:46:33]: Generated plist file with the following values:
[18:46:33]: ▸ -----------------------------------------
[18:46:33]: ▸ {
[18:46:33]: ▸   "provisioningProfiles": {
[18:46:33]: ▸     "net.artsy.Emission": "match AppStore net.artsy.Emission"
[18:46:33]: ▸   },
[18:46:33]: ▸   "method": "app-store",
[18:46:33]: ▸   "signingStyle": "manual"
[18:46:33]: ▸ }
[18:46:33]: ▸ -----------------------------------------
RVM detected, forcing to use system ruby
Now using system ruby.
** Updating RubyGems to the latest compatible version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
+xcodebuild -exportArchive -exportOptionsPlist /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/gym_config20190522-7155-lu6ej8.plist -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2019-05-22/Emission 2019-05-22 18.38.59.xcarchive' -exportPath /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/gym_output20190522-7155-465ami
2019-05-22 18:46:43.155 xcodebuild[12139:24336] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/Emission_2019-05-22_18-46-43.154.xcdistributionlogs'.
2019-05-22 18:46:43.266 xcodebuild[12139:24336] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}
** EXPORT FAILED **
[18:46:43]: Exit status: 70
```

</details>

**Comment by janpio** [comment]
Ugh, those don't help at all. Somehow stuff is broken and the way the output is doesn't help.

Googling for the error message lead to these:
https://github.com/fastlane/fastlane/issues/10559
https://github.com/fastlane/fastlane/issues/1855 (ancient but points to some things to try)
Here is a SO answer that points to earlier stuff being strange: https://stackoverflow.com/a/32841301/252627

Maybe post the _complete_ output, maybe there is something visible in there.

**Comment by ashfurrow** [comment]
As I pointed out in the issue description, the CI builds for this app are open source and one such failure is available [here](https://travis-ci.org/artsy/emission-nebula/builds/535885073#L3253), with the raw build log available [here](https://api.travis-ci.org/v3/job/535885074/log.txt). `gym` is called twice but fails both times, and the log truncates the output from the second call, but it's all there. I'm happy to modify any part of that our CI process to investigate further.

**Comment by janpio** [comment]
Sorry, missed that.

Still I have no idea what is going on here. From the links I posted, I guess the initial archive step produces a broken archive (`/Users/travis/Library/Developer/Xcode/Archives/2019-05-22/Emission 2019-05-22 18.38.59.xcarchive` and similar), that then can not be properly exported. No idea how to confirm or further debug that though :/

**Comment by ashfurrow** [comment]
No worries – I will try to retrieve the build artefacts and confirm if/how the archive is invalid.

**Comment by ashfurrow** [comment]
Okay, this is weird. The archive generated is _definitely_ invalid because the only file it contains is `Info.plist`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ArchiveVersion</key>
        <integer>2</integer>
        <key>CreationDate</key>
        <date>2019-06-04T18:27:12Z</date>
        <key>Name</key>
        <string>Emission</string>
        <key>SchemeName</key>
        <string>Emission</string>
</dict>
</plist>
```

Not sure what that means. Could be a problem with Travis' artifact uploads?

**Comment by janpio** [comment]
You can try the export command that is failing on Travis locally with that archive - if you get the exact same error message, I would say you actually got the correct archive and something is going wrong during the archive phase (that somehow doesn't crash the process although it definitely should).

**Comment by ashfurrow** [comment]
Hmm, okay! It's going to be tricky because the `-exportOptionsPlist` option is a file that's not included in the archive. I'm going to archive locally and compare the two archives, and try the export command as you suggested. I'll let you know how it goes – might not get back to you until tomorrow.

**Comment by ashfurrow** [comment]
Yeah it looks like the archive is missing most of its contents. Here are the CI and local archives side-by-side:

<img width="1181" alt="Screen Shot 2019-06-04 at 3 32 11 PM" src="https://user-images.githubusercontent.com/498212/58908344-4cbfa300-86de-11e9-95e5-90cd8b593f1d.png">

So it appears that the initial archive creation is the source of the problem? I'm continuing to look into this further and hopefully reproduce locally. @janpio do you have any suggestions on how I can generate additional debug output?

**Comment by janpio** [comment]
>  It's going to be tricky because the `-exportOptionsPlist` option is a file that's not included in the archive.

You should be able to use the local one - there shouldn't be too much stuff in there.

> So it appears that the initial archive creation is the source of the problem?

That looks like a valid assumption, yes.

I would compare the local vs Travis output of the first build step next to spot differences and see if they could be related.

**Comment by ashfurrow** [comment]
Okay! So I'm happy to report back that I've been able to intermittently reproduce the invalid archive locally. If I run the following command, it will generate a **valid archive**:

```
xcodebuild -workspace Emission.xcworkspace -scheme Emission -configuration Deploy -destination 'generic/platform=iOS' -archivePath /Users/ashfurrow/Desktop/test4.xcarchive archive
```

And if I run it again, but change the `-archivePath` option, then it will generate another valid archive. But, if I use the _same_ path, it generates an **invalid archive**:

```
xcodebuild -workspace Emission.xcworkspace -scheme Emission -configuration Deploy -destination 'generic/platform=iOS' -archivePath /Users/ashfurrow/Desktop/test4.xcarchive archive
# This generates the following archive, which matches what we see on Travis:
# - Info.plist
# - Empty Products and dSYMs directories
```

Looks like `xcodebuild` doesn't like archiving to the same path more than once.

So my guess is that the archive that Travis is uploading as a build artefact is incorrect not because of this bug, necessarily, but because we run `gym` twice is the first run fails. I'm going to remove that second invocation and see what the uploaded archive looks like. I'll keep you posted.

@janpio thank you for your help on this. I know CI issues are particularly difficult, and I appreciate your guidance.

**Comment by janpio** [comment]
You're welcome. I know how frustrating these can be, especially because even you, running the process, don't have direct access to what is going on. Glad you could replicate at least part of the problem, and have a path forward. Let us know how it goes!

**Comment by ashfurrow** [comment]
Okay, I wanted to follow up with some more info. I can reproduce the archive failure intermittently using `xcodebuild` but haven't been able to pinpoint the cause. I've got a raw build log of a failure (from CI) and a success (locally) and will compare them for obvious differences. I'll report back with more findings after I investigate, but the logs are very different sizes: CI is 9MB while local is 11MB. CI's log also is missing some `PhaseScriptExecution` that we have defined in our Xcode project, including the check for CocoaPods' `Manifest.lock` file, so something is definitely going on.

**Comment by janpio** [comment]
Some of the answers/comments on the links I posted mentioned problems with different CocoaPods versions. Those had been from years ago, so I doubt you have the _same_ problem, but maybe you can check if it could be a similar problem. 

(Another thought: In the export phase we had the "using system ruby" output, does this also affect the archive phase maybe? That could scramble dependencies quite a lot)

**Comment by ashfurrow** [comment]
Yeah, definitely – I've looked into those resources to try to pinpoint the issue. Because I'm able to intermittently reproduce the empty archive problem on my machine locally, using `xcodebuild`, I don't think it has to do with the system Ruby. I've only seen the invalid archives happen from `xcodebuild` and not from Xcode itself. I'll keep at it 👍

**Comment by setoff** [comment]
Hi! I'd like to share my experience with this kind of problem with my project. It might be one of the reason mentioned, so please double check these cases:
- make sure that `Skip Install` value is setup properly (should be `NO` for app targets and `YES` otherwise: test targets, framework targets). Links about it somewhere in this topic.
-  you have latests tools installed.

In my project we use different schemes to build app for different environments. We produce these schemes by duplicating default and fine tune it after.
For some reason in new scheme in `Build` setup we've got two targets to build: default and copy of it.
<img width="1235" alt="copy_scheme_setup" src="https://user-images.githubusercontent.com/1941619/59738347-5e767e00-927a-11e9-865a-bc6c0f9ba743.png">

Archiving with this setup cause to produce _"Generic Archive"_ which is failed to export with error: `error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc`
This is understandable because archive contained two apps and it is not clear how to export this to IPA.
<img width="507" alt="generic_archive" src="https://user-images.githubusercontent.com/1941619/59738397-8f56b300-927a-11e9-8a0c-23d3aed2e5b3.png">

Fix is simple: just remove unnecessary target from `Build` setup for one of the schemes (or at least uncheck it from archiving).

Hope this help someone ✋

**Comment by ntk860** [comment]
I am having the same problem. It is archiving the ipa file as Generic Xcode Archive.

**Comment by ntk860** [comment]
@setoff I only have 1 archived file but it still not working. It is archiving as Generic, I do not know. I had my subscription paid expired, I just paid and trying to submit to testflight but it is not working. Can you help me please ?

**Comment by ntk860** [comment]
@janpio can you help me please ?

**Comment by janpio** [comment]
Please open a new issue and include all the information it asks for @ntk860 - maybe we can help you debug this as well.

**Comment by ntk860** [comment]
@janpio it was a library that was causing the problem. I downgraded it and fastlane successfully worked. I'm sorry ☹️

**Comment by janpio** [comment]
Solved problems are the best problems 🍡

**Comment by ashfurrow** [comment]
I did try invoking `fastlane` twice [here](https://github.com/artsy/emission-nebula/commit/5fe76ed6cdfdfbd869c0053e5f1e9340f168c1fd) but got the same result. I'll hopefully have more time next week to dig into this.

**Comment by M4rcos** [comment]
Open xcode and select Generic iOS Device and run Archive solved the export issue in local for me.

**Comment by ashfurrow** [comment]
Last time I checked, this is still happening. I'll re-trigger a build to verify, and send a link to the build logs if that's helpful.

**Comment by janpio** [comment]
No, you're good here - the bot just doesn't know better. I hope we will find time to look into this deeper soon.

**Comment by ashfurrow** [comment]
@fastlane-bot yes, the problem persists with the latest version.

**Comment by matthewlloyd** [comment]
I still see this issue almost daily, with the latest version of Fastlane.

**Comment by ashfurrow** [comment]
Yup, still happening.

**Comment by ashfurrow** [comment]
This is still happening as of this morning, but has fallen off my radar as a priority. This will be the last time that I tell @fastlane-bot to keep the issue open, so if someone else care about the bug, they'll need to take over.

Let me know if I can provide more context. Thanks again everyone 🙇‍♂️
