### ISSUE TITLE
upload_to_play_store hangs

### ISSUE THREAD

**Issue by UFOnaut** [fastlane/fastlane#14794]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Uploading new version of android app bundle goes to message "Uploading all changes to Google Play..." and then does nothing until Bitbucket Pipeline stops with it's timeout (15 min is set for that step). Authorization works fine, because other info is taken from google play (metadata, versionCode ...)

##### Command executed
selected_track=''production'
upload_to_play_store(
      track: selected_track,
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
  )

No error is shown. Android app bundle uploading process hangs on message "Uploading all changes to Google Play..."

##### Complete output when running fastlane, including the stack trace and command used
[05:58:53]: fastlane detected a Gemfile in the current directory
[05:58:53]: however it seems like you don't use `bundle exec`
[05:58:53]: to launch fastlane faster, please use
[05:58:53]: 
[05:58:53]: $ bundle exec fastlane publish_to_google_play --capture_output
[05:58:53]: 
[05:58:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-05-22 05:58:53.71]: Checking if there are any plugins that should be loaded...
INFO [2019-05-22 05:58:53.75]: Driving the lane 'publish_to_google_play' 🚀
INFO [2019-05-22 05:58:53.75]: ---------------------------------------------
INFO [2019-05-22 05:58:53.75]: --- Step: google_play_track_version_codes ---
INFO [2019-05-22 05:58:53.75]: ---------------------------------------------
DEBUG [2019-05-22 05:58:53.76]: Fetching a new access token from Google...
INFO [2019-05-22 05:58:55.97]: Found '566' version codes in track 'production'
INFO [2019-05-22 05:58:55.97]: --------------------
INFO [2019-05-22 05:58:55.97]: --- Step: gradle ---
INFO [2019-05-22 05:58:55.97]: --------------------
INFO [2019-05-22 05:58:55.97]: $ /opt/atlassian/pipelines/agent/build/gradlew bundleLiveRelease -p . -PversionCode=567
INFO [2019-05-22 05:58:55.99]: ▸ Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
INFO [2019-05-22 05:58:56.07]: ▸ Downloading https://services.gradle.org/distributions/gradle-4.10.1-all.zip
INFO [2019-05-22 05:58:58.88]: ▸ ...............................................................................................................
INFO [2019-05-22 05:58:58.88]: ▸ Unzipping /root/.gradle/wrapper/dists/gradle-4.10.1-all/455itskqi2qtf0v2sja68alqd/gradle-4.10.1-all.zip to /root/.gradle/wrapper/dists/gradle-4.10.1-all/455itskqi2qtf0v2sja68alqd
INFO [2019-05-22 05:59:00.87]: ▸ Set executable permissions for: /root/.gradle/wrapper/dists/gradle-4.10.1-all/455itskqi2qtf0v2sja68alqd/gradle-4.10.1/bin/gradle
INFO [2019-05-22 05:59:01.20]: ▸ Welcome to Gradle 4.10.1!
INFO [2019-05-22 05:59:01.20]: ▸ Here are the highlights of this release:
INFO [2019-05-22 05:59:01.20]: ▸ - Incremental Java compilation by default
INFO [2019-05-22 05:59:01.20]: ▸ - Periodic Gradle caches cleanup
INFO [2019-05-22 05:59:01.20]: ▸ - Gradle Kotlin DSL 1.0-RC6
INFO [2019-05-22 05:59:01.20]: ▸ - Nested included builds
INFO [2019-05-22 05:59:01.20]: ▸ - SNAPSHOT plugin versions in the `plugins {}` block
INFO [2019-05-22 05:59:01.20]: ▸ For more details see https://docs.gradle.org/4.10.1/release-notes.html
INFO [2019-05-22 05:59:01.35]: ▸ Starting a Gradle Daemon (subsequent builds will be faster)
INFO [2019-05-22 05:59:12.26]: ▸ > Configure project :app
INFO [2019-05-22 05:59:12.26]: ▸ VersionCode is set to 567
INFO [2019-05-22 05:59:13.06]: ▸ File /root/.android/repositories.cfg could not be loaded.
INFO [2019-05-22 05:59:13.96]: ▸ Checking the license for package Android SDK Build-Tools 28.0.3 in /opt/android-sdk/licenses
INFO [2019-05-22 05:59:13.96]: ▸ License for package Android SDK Build-Tools 28.0.3 accepted.
INFO [2019-05-22 05:59:14.06]: ▸ Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
INFO [2019-05-22 05:59:16.36]: ▸ "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
INFO [2019-05-22 05:59:16.36]: ▸ Installing Android SDK Build-Tools 28.0.3 in /opt/android-sdk/build-tools/28.0.3
INFO [2019-05-22 05:59:16.36]: ▸ "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
INFO [2019-05-22 05:59:16.36]: ▸ "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
INFO [2019-05-22 05:59:16.36]: ▸ Checking the license for package Android SDK Platform 28 in /opt/android-sdk/licenses
INFO [2019-05-22 05:59:16.36]: ▸ License for package Android SDK Platform 28 accepted.
INFO [2019-05-22 05:59:16.36]: ▸ Preparing "Install Android SDK Platform 28 (revision: 6)".
INFO [2019-05-22 05:59:27.46]: ▸ "Install Android SDK Platform 28 (revision: 6)" ready.
INFO [2019-05-22 05:59:27.46]: ▸ Installing Android SDK Platform 28 in /opt/android-sdk/platforms/android-28
INFO [2019-05-22 05:59:27.46]: ▸ "Install Android SDK Platform 28 (revision: 6)" complete.
INFO [2019-05-22 05:59:27.46]: ▸ "Install Android SDK Platform 28 (revision: 6)" finished.
INFO [2019-05-22 05:59:27.55]: ▸ Checking the license for package Android SDK Platform-Tools in /opt/android-sdk/licenses
INFO [2019-05-22 05:59:27.56]: ▸ License for package Android SDK Platform-Tools accepted.
INFO [2019-05-22 05:59:27.56]: ▸ Preparing "Install Android SDK Platform-Tools (revision: 28.0.3)".
INFO [2019-05-22 05:59:28.66]: ▸ "Install Android SDK Platform-Tools (revision: 28.0.3)" ready.
INFO [2019-05-22 05:59:28.66]: ▸ Installing Android SDK Platform-Tools in /opt/android-sdk/platform-tools
INFO [2019-05-22 05:59:28.66]: ▸ "Install Android SDK Platform-Tools (revision: 28.0.3)" complete.
INFO [2019-05-22 05:59:28.66]: ▸ "Install Android SDK Platform-Tools (revision: 28.0.3)" finished.
INFO [2019-05-22 05:59:29.55]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
INFO [2019-05-22 05:59:29.56]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
INFO [2019-05-22 05:59:29.56]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
INFO [2019-05-22 05:59:29.56]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
INFO [2019-05-22 05:59:30.06]: ▸ > Task :app:mergeLiveReleaseShaders
INFO [2019-05-22 05:59:30.06]: ▸ > Task :app:compileLiveReleaseShaders
INFO [2019-05-22 05:59:30.06]: ▸ > Task :app:generateLiveReleaseAssets
INFO [2019-05-22 05:59:30.06]: ▸ > Task :piggycore:mergeReleaseShaders
INFO [2019-05-22 05:59:30.06]: ▸ > Task :piggycore:compileReleaseShaders
INFO [2019-05-22 05:59:30.06]: ▸ > Task :piggycore:generateReleaseAssets
INFO [2019-05-22 05:59:30.06]: ▸ > Task :piggycore:packageReleaseAssets
INFO [2019-05-22 05:59:42.16]: ▸ > Task :app:mergeLiveReleaseAssets
INFO [2019-05-22 05:59:42.16]: ▸ > Task :app:processLiveReleaseGoogleServices
INFO [2019-05-22 05:59:42.16]: ▸ Parsing json file: /opt/atlassian/pipelines/agent/build/app/google-services.json
INFO [2019-05-22 05:59:44.56]: ▸ > Task :app:checkLiveReleaseClasspath
INFO [2019-05-22 05:59:44.56]: ▸ > Task :app:preBuild UP-TO-DATE
INFO [2019-05-22 05:59:44.56]: ▸ > Task :piggycore:preBuild UP-TO-DATE
INFO [2019-05-22 05:59:44.56]: ▸ > Task :piggycore:preReleaseBuild UP-TO-DATE
INFO [2019-05-22 05:59:44.56]: ▸ > Task :piggycore:checkReleaseManifest
INFO [2019-05-22 05:59:44.66]: ▸ > Task :piggycore:processReleaseManifest
INFO [2019-05-22 05:59:44.66]: ▸ > Task :app:preLiveReleaseBuild
INFO [2019-05-22 05:59:44.66]: ▸ > Task :app:checkLiveReleaseManifest
INFO [2019-05-22 05:59:44.66]: ▸ > Task :app:createLiveReleaseCompatibleScreenManifests
INFO [2019-05-22 05:59:44.66]: ▸ > Task :app:mainApkListPersistenceLiveRelease
INFO [2019-05-22 05:59:44.86]: ▸ > Task :app:processLiveReleaseManifest
INFO [2019-05-22 05:59:44.96]: ▸ > Task :app:fabricGenerateResourcesLiveRelease
INFO [2019-05-22 05:59:44.96]: ▸ > Task :piggycore:packageReleaseRenderscript NO-SOURCE
INFO [2019-05-22 05:59:45.06]: ▸ > Task :app:compileLiveReleaseRenderscript
INFO [2019-05-22 05:59:45.06]: ▸ > Task :app:generateLiveReleaseResValues
INFO [2019-05-22 05:59:45.06]: ▸ > Task :app:generateLiveReleaseResources
INFO [2019-05-22 05:59:45.06]: ▸ > Task :piggycore:compileReleaseRenderscript
INFO [2019-05-22 05:59:45.06]: ▸ > Task :piggycore:generateReleaseResValues
INFO [2019-05-22 05:59:45.06]: ▸ > Task :piggycore:generateReleaseResources
INFO [2019-05-22 05:59:45.46]: ▸ > Task :piggycore:packageReleaseResources
INFO [2019-05-22 05:59:47.25]: ▸ > Task :app:mergeLiveReleaseResources
INFO [2019-05-22 05:59:47.76]: ▸ warn: removing resource nl.piggy.klantenapp:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
INFO [2019-05-22 05:59:47.76]: ▸ > Task :app:bundleLiveReleaseResources
INFO [2019-05-22 05:59:47.76]: ▸ > Task :piggycore:compileReleaseAidl NO-SOURCE
INFO [2019-05-22 05:59:47.76]: ▸ > Task :app:compileLiveReleaseAidl NO-SOURCE
INFO [2019-05-22 05:59:47.76]: ▸ > Task :app:generateLiveReleaseBuildConfig
INFO [2019-05-22 05:59:47.76]: ▸ > Task :app:prepareLintJar
INFO [2019-05-22 05:59:47.76]: ▸ > Task :app:splitsDiscoveryTaskLiveRelease
INFO [2019-05-22 05:59:48.06]: ▸ > Task :piggycore:generateReleaseRFile
INFO [2019-05-22 05:59:48.55]: ▸ warn: removing resource nl.piggy.klantenapp:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
INFO [2019-05-22 05:59:48.65]: ▸ > Task :app:processLiveReleaseResources
INFO [2019-05-22 05:59:48.66]: ▸ > Task :app:generateLiveReleaseSources
INFO [2019-05-22 05:59:48.66]: ▸ > Task :piggycore:generateReleaseBuildConfig
INFO [2019-05-22 05:59:48.66]: ▸ > Task :piggycore:prepareLintJar
INFO [2019-05-22 05:59:48.66]: ▸ > Task :piggycore:generateReleaseSources
INFO [2019-05-22 05:59:51.05]: ▸ > Task :piggycore:javaPreCompileRelease
INFO [2019-05-22 05:59:55.76]: ▸ > Task :piggycore:compileReleaseJavaWithJavac
INFO [2019-05-22 05:59:55.76]: ▸ Note: Some input files use or override a deprecated API.
INFO [2019-05-22 05:59:55.76]: ▸ Note: Recompile with -Xlint:deprecation for details.
INFO [2019-05-22 05:59:55.76]: ▸ Note: Some input files use unchecked or unsafe operations.
INFO [2019-05-22 05:59:55.76]: ▸ Note: Recompile with -Xlint:unchecked for details.
INFO [2019-05-22 05:59:57.66]: ▸ > Task :piggycore:processReleaseJavaRes NO-SOURCE
INFO [2019-05-22 05:59:57.76]: ▸ > Task :piggycore:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
INFO [2019-05-22 06:00:00.16]: ▸ > Task :app:javaPreCompileLiveRelease
INFO [2019-05-22 06:00:02.16]: ▸ > Task :app:compileLiveReleaseJavaWithJavac
INFO [2019-05-22 06:00:02.16]: ▸ Note: Some input files use or override a deprecated API.
INFO [2019-05-22 06:00:02.16]: ▸ Note: Recompile with -Xlint:deprecation for details.
INFO [2019-05-22 06:00:02.16]: ▸ Note: Some input files use unchecked or unsafe operations.
INFO [2019-05-22 06:00:02.16]: ▸ Note: Recompile with -Xlint:unchecked for details.
INFO [2019-05-22 06:00:09.47]: ▸ /root/.gradle/caches/transforms-1/files-1.1/play-services-measurement-impl-16.4.0.aar/a8e627b6a085fdc498c842a335462319/jars/classes.jar: D8: Type `libcore.io.Memory` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.measurement.zzhw$zzb.zza(long, byte)`
INFO [2019-05-22 06:00:09.97]: ▸ /root/.gradle/caches/transforms-1/files-1.1/play-services-measurement-impl-16.4.0.aar/a8e627b6a085fdc498c842a335462319/jars/classes.jar: D8: Type `libcore.io.Memory` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.measurement.zzhw$zza.zza(long, byte)`
INFO [2019-05-22 06:00:15.06]: ▸ D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
INFO [2019-05-22 06:00:15.37]: ▸ D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
INFO [2019-05-22 06:00:17.35]: ▸ > Task :app:transformClassesWithDexBuilderForLiveRelease
INFO [2019-05-22 06:00:19.96]: ▸ > Task :app:transformClassesWithMultidexlistForLiveRelease
INFO [2019-05-22 06:00:21.95]: ▸ > Task :app:transformDexArchiveWithDexMergerForLiveRelease
INFO [2019-05-22 06:00:21.96]: ▸ > Task :app:compileLiveReleaseNdk NO-SOURCE
INFO [2019-05-22 06:00:21.96]: ▸ > Task :app:mergeLiveReleaseJniLibFolders
INFO [2019-05-22 06:00:21.96]: ▸ > Task :piggycore:compileReleaseNdk NO-SOURCE
INFO [2019-05-22 06:00:21.96]: ▸ > Task :piggycore:mergeReleaseJniLibFolders
INFO [2019-05-22 06:00:21.96]: ▸ > Task :piggycore:transformNativeLibsWithMergeJniLibsForRelease
INFO [2019-05-22 06:00:21.96]: ▸ > Task :piggycore:transformNativeLibsWithIntermediateJniLibsForRelease
INFO [2019-05-22 06:00:22.76]: ▸ > Task :app:transformNativeLibsWithMergeJniLibsForLiveRelease
INFO [2019-05-22 06:00:22.76]: ▸ > Task :app:checkLiveReleaseLibraries
INFO [2019-05-22 06:00:22.76]: ▸ > Task :app:processLiveReleaseJavaRes NO-SOURCE
INFO [2019-05-22 06:00:23.25]: ▸ > Task :app:transformResourcesWithMergeJavaResForLiveRelease
INFO [2019-05-22 06:00:24.25]: ▸ > Task :app:buildLiveReleasePreBundle
INFO [2019-05-22 06:00:24.26]: ▸ > Task :app:validateSigningLiveRelease
INFO [2019-05-22 06:00:28.31]: ▸ > Task :app:packageLiveReleaseBundle
INFO [2019-05-22 06:00:28.31]: ▸ > Task :app:bundleLiveRelease
INFO [2019-05-22 06:00:28.31]: ▸ BUILD SUCCESSFUL in 1m 32s
INFO [2019-05-22 06:00:28.31]: ▸ 48 actionable tasks: 48 executed
INFO [2019-05-22 06:00:28.68]: ----------------------------------
INFO [2019-05-22 06:00:28.68]: --- Step: upload_to_play_store ---
INFO [2019-05-22 06:00:28.68]: ----------------------------------
DEBUG [2019-05-22 06:00:28.69]: Fetching a new access token from Google...
INFO [2019-05-22 06:00:30.21]: Preparing to upload for language 'de-DE'...
INFO [2019-05-22 06:00:30.43]: Preparing to upload for language 'en-GB'...
INFO [2019-05-22 06:00:30.59]: Preparing to upload for language 'nl-NL'...
INFO [2019-05-22 06:00:30.70]: Preparing aab at path '/opt/atlassian/pipelines/agent/build/app/build/outputs/bundle/liveRelease/app.aab' for upload...
INFO [2019-05-22 06:01:07.13]: Updating track 'production'...
INFO [2019-05-22 06:01:07.38]: Uploading all changes to Google Play...

### Environment

[05:58:51]: fastlane detected a Gemfile in the current directory
[05:58:51]: however it seems like you don't use `bundle exec`
[05:58:51]: to launch fastlane faster, please use
[05:58:51]: 
[05:58:51]: $ bundle exec fastlane env
[05:58:51]: 
[05:58:51]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[05:58:52]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                                       |
| --------------------------- | ----------------------------------------------------------- |
| OS                          | debian_based buster/sid                                     |
| Ruby                        | 2.5.1                                                       |
| Bundler?                    | false                                                       |
| Git                         | git version 2.17.1                                          |
| Installation Source         | /usr/local/bin/fastlane                                     |
| Host                        | Ubuntu 18.04.2 LTS debian_based buster/sid (4.19.43-coreos) |
| Ruby Lib Dir                | /usr/lib                                                    |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                                  |
| Is contained                | false                                                       |
| Is homebrew                 | false                                                       |
| Is installed via Fabric.app | false                                                       |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |
### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>
```ruby
lane :tests do
  gradle(task: "test")
end
lane :build_bundle do
  gradle(
      task: 'bundle',
      flavor: 'Live',
      build_type: 'Release'
  )
end
lane :build_apk do
  gradle(
      task: 'assemble',
      flavor: 'Live',
      build_type: 'Debug'
    )
end
lane :publish_to_fabric_beta do
  gradle(task: "assembleLiveDebug crashlyticsUploadDistributionLiveDebug")
end
lane :publish_to_google_play do
  selected_track = 'production'
  selected_version_code = google_play_track_version_codes(track: selected_track).first + 1
  gradle(
      task: 'bundle',
      flavor: 'Live',
      build_type: 'Release',
      properties: {
          'versionCode' => selected_version_code
      }
  )
  upload_to_play_store(
      track: selected_track,
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
  )
end
lane :report do
  gradle(task: "cleanTestAndReportToSonar")
end
```
</details>
<details><summary>`./fastlane/Appfile`</summary>
```ruby
json_key_file "actual path to service account json file"
package_name "actual package name"
```
</details>
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>
*generated on:* **2019-05-22**
</details>
[05:58:52]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[05:58:52]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by UFOnaut** [comment]
Authorization with service account is ok. Version codes fetched well. Metadata fetched well. 
Generated app.aab had been added to artifacts, then I had downloaded it and uploaded with Google Play Dev Console web interface without any problems.

**Comment by boozi2** [comment]
I'm getting this on iOS:

[16:28:48]: [32m----------------------------------[0m

[16:28:48]: [32m--- Step: upload_to_testflight ---[0m

[16:28:48]: [32m----------------------------------[0m

[16:28:48]: Login to App Store Connect ([secure])

[16:28:51]: Login successful

[16:28:51]: [32mReady to upload new build to TestFlight (App: XXXXXXXX)...[0m

[16:28:54]: Going to upload updated app to App Store Connect

[16:28:54]: [32mThis might take a few minutes. Please don't interrupt the script.[0m


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated

**Comment by UFOnaut** [comment]
I had ideas, that possibly Bitbucket CI servers have problems while connecting to Google Play Developer's API. But I had started Fastlane in local Docker and the result was the same as on Bitbucket CI.

**Comment by boozi2** [comment]
My problems are from Travis CI

**Comment by UFOnaut** [comment]
Problem was in Google Play Developer Console. Somehow 3 active drafts with *.apks of very very old version of app were preventing to upload new version of application. Removed them and everything works well now!
