### ISSUE TITLE
I want to use Transporter Diagnostic

### ISSUE THREAD

**Issue by chatwyn** [fastlane/fastlane#14795]
https://help.apple.com/itc/transporteruserguide/#/apdATD1E6724-D1E1A1303-D1E6724A1126 

How can i use transporter other methods

**Comment by janpio** [comment]
Fastlane only uses `upload`, `lookupMetadata` and `provider` of Transporter, see the code for it here: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb

What is your use case for `-m diagnostic`?
You can always build the Transporter command yourself and then run it using https://docs.fastlane.tools/actions/sh/ if you want.
