### ISSUE TITLE
Adding a non-ASC certificate to Match

### ISSUE THREAD

**Issue by matcartmill** [fastlane/fastlane#14792]
### Adding non-ASC certificate to `match`

Hello,

We are using `match` to manage our certificates for `development` and `appstore` builds. My team currently has an ask to enable Enterprise builds using a specific certificate that's not available in ASC.

Is there a way to manually add a certificate to `match` for our Enterprise efforts and have `match` only ever retrieve it from Git?

I feel like simply encrypting the files and then adding the appropriate `profiles` and `certs` listing to the repo should be enough, but I want to check here before I start messing around with stuff that could affect our devs.

Thanks.

**Comment by janpio** [comment]
I can't answer your question if this will actually work the way you want, but I know that we have documentation on how to manually decrypt and encrypt stuff for the match git repo: https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo ("Instructions" hides them)

**Comment by janpio** [comment]
Did this help @matcartmill?
