### ISSUE TITLE
Which field in deliver-metadata corresponds to What's New in appstore connect?

### ISSUE THREAD

**Issue by dineshkrishna** [fastlane/fastlane#14790]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the https://docs.fastlane.tools/actions/deliver/
- [x] I searched for examples across the web

### Deliver metadata field for What's New
I have been looking for the exact field in deliver - metadata properties which should be used for uploading the Whats new field in Appstore connect

#### What's New example
For instance if you see this app, there is a field called What's New in this app link. We have localized content for multiple languages for this What's New content. Which one in deliver should be used to upload the metadata content?

https://itunes.apple.com/us/app/microsoft-word/id586447913?mt=8

**Comment by mollyIV** [comment]
Hey @dineshkrishna 👋 

I believe `Localized Metadata` is what you are looking for. According to [the documentation](https://docs.fastlane.tools/actions/deliver/#available-metadata-folder-options):

> deliver allows for metadata to be set through .txt files in the metadata folder.

You can prepare your localized release notes and put them under `<metadata_path>/<lang>/release_notes.txt`. 

Another solution might be using `release_notes` parameter: 

https://github.com/fastlane/fastlane/blob/46dea0dabd915525c2e43ac5e8c5b6b9ba2e23b4/deliver/lib/deliver/options.rb#L367-L370

You could use it like this:

```Ruby
deliver(
  languages: ['en-AU', 'en-CA', 'en-GB'],
  release_notes: {
          'default' => 'something',
          'en-US' => 'something else',
          'es-MX' => 'something else else'
        },
  ...
)
```

Please let us know if that helped, cheers 🙇

**Comment by janpio** [comment]
Did this answer your question @dineshkrishna?
