### ISSUE TITLE
Unauthorized Access

### ISSUE THREAD

**Issue by yangjiayu** [fastlane/fastlane#1480]
i always have the problem.
### Issue Description
![image](https://cloud.githubusercontent.com/assets/13096687/13560096/894ed670-e456-11e5-87a6-a77d88b3433d.png)

i dont know why?

**Comment by lacostej** [comment]
Hello, there are probably 2 issues here:
* your account is probably not configured properly, in particular if your appleid might not be confirmed
* you are probably running an outdated version of spaceship. There was an issue in spaceship a few release ago that caused that configuration issue to cause spaceship to loop forever.

**Comment by yangjiayu** [comment]
@lacostej 
 I'm sure my appleid is confirmed, and my spaceship is not outdate. But it dones't work. it also has the issue.
But there is a new question. it is recommended me to update fastlane to use "sudo gem update fastlane". 
fastlane 1.66.0 is available. i'm on 1.64.0.  when i update, it does't work, too.

**Comment by asfalcone** [comment]
@yangjiayu Can you provide more detailed output including the command you are running and what the errors/what is not working? Thanks!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (448/400 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:35135 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKsU-002lKk-K7
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:21:59 +0200
Date: Sat, 18 Jun 2016 11:21:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274073;
	bh=zjkIBjwAOgU8RHXayc14j8lsN5KHNFUY9QQu58Ny3kE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=A/65Y+NKjEjyE21VfPDu4R5E0TB0HSwHVDmtrA30uDKMjfdaMltPAtvvcNZPu0ZPM
	 KptthNrf0oRRd6yQU+iXlfxMjQCiDEQC0b2qqk1kX2UQf7ASXZNfqyEnsdEWU3TImj
	 zUYgTcNtnOw7qZ+FTNXeFFIZaDLuB54y6t9qa3F0=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (449/400 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:58724 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKsV-002lKs-8V
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:01 +0200
Date: Sat, 18 Jun 2016 11:21:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274074;
	bh=pMlC4naxv/K6SizM/NLcvamC6pZUFQy+kGTJIdErUTI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TTuiECbLYPFSipWmJGINY/QRIZHVsPCRNxMoI7fGFge2E9myIQuRQfk8sYemELJ1V
	 zibxOtijJTcPojAITuWQ7uLI2u2sNp21yd6X8FsVdGJ0gPgtzg2iHHCd9s3QBciIVD
	 HPBezi/RWxRBgSbabKQraGMoWRZHYhSRcBMoEkNA=
