### ISSUE TITLE
(FastlaneCore::Interface::FastlaneShellError) on travis ci build

### ISSUE THREAD

**Issue by jamfly** [fastlane/fastlane#14809]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My local `bundle exec fastlane build` is work fine. But, while I build my project on travis ci, the build just failed with error message 
```
/Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'set -o pipefail && xcodebuild -workspace "myAPP.xcworkspace" -scheme "myAPP" -configuration "Debug" build -destination "generic/platform=iOS" | tee '/Users/travis/Library/Logs/fastlane/xcbuild/2019-05-27/26176/xcodebuild.log' | xcpretty --color --simple' was 65 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
```
##### Command executed

`bundle exec fastlane build` 
##### Complete output when running fastlane, including the stack trace and command used

runs on travis ci 
<details>
  <pre>  
   
The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/travis/Library/Developer/Xcode/DerivedData/myAPP-cijiloxtoaolloerneooytbwzgoy/Build/Intermediates.noindex/myAPP.build/Debug-iphoneos/myAPP.build/Script-3B17AEC2228E5C0F004287F0.sh
(1 failure)
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/actions/xcodebuild.rb:273:in `run'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:62:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/gems/fastlane-2.123.0/bin/fastlane:23:in `<top (required)>'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/bin/fastlane:23:in `load'
	from /Users/travis/build/jamfly/myAPP/vendor/bundle/ruby/2.4.0/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'

  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    clear_derived_data
    setup_travis
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    reset_simulators

    capture_screenshots(workspace: "myAPP.xcworkspace", scheme: "myAPP")
    frameit  # brew install imagemagick
  end

  desc "Submit a new beta build to apple TestFlight"
  lane :beta do
    build_app(
      scheme: "myAPP",
      workspace: "myAPP.xcworkspace",
      include_bitcode: true,
      xcargs: "-allowProvisioningUpdates"
      )
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    build_app(scheme: "myAPP",
              workspace: "myAPP.xcworkspace",
              include_bitcode: true,
              xcargs: "-allowProvisioningUpdates")

    deliver
  end
  
  desc "Build the project"
  lane :build do |options|
    match(type: 'development')
    xcodebuild(
      workspace: "myAPP.xcworkspace",
      scheme: "myAPP",
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      destination: "generic/platform=iOS"
    )
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.jamfly.myAPP") # The bundle identifier of your app
apple_id("myAPP@gmail.com") # Your Apple email address


# For more information about the Appfile, see:
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| jwt                       | 2.2.1        |
| signet                    | 0.11.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-05-27**
</details>

**Comment by janpio** [comment]
> PhaseScriptExecution Run\ Script /Users/travis/Library/Developer/Xcode/DerivedData/myAPP-cijiloxtoaolloerneooytbwzgoy/Build/Intermediates.noindex/myAPP.build/Debug-iphoneos/myAPP.build/Script-3B17AEC2228E5C0F004287F0.sh

Is this possibly a custom script of your iOS project?

**Comment by jamfly** [comment]
Hi @janpio 

You save my day! 
I could build my project in local with this command but I still don't understand why my CI failed with the script, currently I remove all script in my project.

Thank you again.
Jamfly

**Comment by janpio** [comment]
You're welcome, glad I could help.
