### ISSUE TITLE
How to get the last released app version

### ISSUE THREAD

**Issue by NikKovIos** [fastlane/fastlane#14801]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
I checked https://github.com/fastlane/fastlane/issues/8878
https://docs.fastlane.tools/actions/latest_testflight_build_number/
https://docs.fastlane.tools/actions/get_version_number/
https://github.com/fastlane/fastlane/issues/5114
but didn't found an answer.

Example: I have an app, did upload version 1.0.0 to test flight. Uploaded build 1, then 2, then 3. After that somebody did release version 1.0.0 build 3, but i don't know about this. if i would upload 1.0.0 build 4, the app store would send an error, that i must increase version.  
Expected tool: Check version of the package in release. When releasing we have to unrelated numbers: live version and package version (look at the screenshot). The goal is to get the version of the package, that is already in live. At screenshot it is on the right (2.8.8-4). It is needed to check if i need to increment the minor version next time and upload 1.0.1 build 1.
![Снимок экрана 2019-05-23 в 11 12 00](https://user-images.githubusercontent.com/16647690/58236516-bb4e4980-7d4b-11e9-8a61-6f797849111f.png)

**Comment by Cyberuben** [comment]
I think this is what you need:

https://docs.fastlane.tools/actions/app_store_build_number/

If you want the latest live version, you can use this function as-is (because `live` defaults to `true`), and if you want the latest testflight version, you use `live: false`

**Comment by NikKovIos** [comment]
@Cyberuben 
Nope. In my example this lane would return 4.8.2, build 4 with live is true. And with live false 2.8.9-1 if i've already pushed version above or 2.8.8-4 if not.

**Comment by NikKovIos** [comment]
Still need a tool which would show the version of the build that is already in the review.
To prevent error when the version is already in air.
