### ISSUE TITLE
before_all execution order

### ISSUE THREAD

**Issue by rkrim** [fastlane/fastlane#14802]
#### Motivation Behind Feature
Make execution order of `before_all` follows common comprehension of global/platform scope

A question was asked here #5446 about current behavior, but no indication about the ability to change this in future.

#### Feature Description
With the following code 
```ruby
before_all do
  puts "global before_all insruction"
end

platform :ios do
  before_all do
    puts "platform specific before_all insruction"
  end

  lane :foo do
    puts "lane insruction"
  end
end
```
command `fastlane ios foo` output is currently:
```
platform specific before_all insruction
global before_all insruction
lane insruction
```

It should be:
```
global before_all insruction
platform specific before_all insruction
lane insruction
```

**Note 1**
This can break users scripts

**Note 2**
Current implementation is 
> We do platform specific actions before the other before_all

So this must not just invert this logic, otherwise we'll have same issue with `after_all`

**Comment by janpio** [comment]
> command `fastlane ios foo` output is currently:
> 
> ```
> platform specific before_all insruction
> global before_all insruction
> lane insruction
> ```

That definitely sounds unexpected.

Is there any way to change the more correct behavior without introducing a breaking change?
