### ISSUE TITLE
deliver fails to load Deliverfile with 403 Forbidden error

### ISSUE THREAD

**Issue by joulupukki** [fastlane/fastlane#14805]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I've got a fairly complicated Fastlane script set up that builds and submits my app using CircleCI. Months ago I had it working with building and submitting screenshots (with snapshot) but that broke and I haven't had time to look more into it.

This week I decided to dig in a little more. If I run Fastlane from my local machine everything works correctly. But, in the CircleCI environment using Xcode 10.2.1 and Fastlane 2.123.0 (same thing happened in some older versions as well, at least back to 2.116.x) I get a 403 Forbidden error when deliver attempts to open Deliverfile.

Locally, I get this output when deliver runs:

INFO [2019-05-24 11:57:15.91]: ---------------------
INFO [2019-05-24 11:57:15.91]: --- Step: deliver ---
INFO [2019-05-24 11:57:15.91]: ---------------------
INFO [2019-05-24 11:57:16.41]: Successfully loaded '/Users/boyd/projects/mtg-ios/fastlane/Deliverfile' 📄
...
and it all works after this.

Strangely, this only happens if I have the script generate screenshots. If I don't generate screenshots, it uploads the .ipa and metadata normally.

##### Command executed

bundle exec fastlane circle_ci --verbose

##### Complete output when running fastlane, including the stack trace and command used

On CircleCI, as soon as deliver attempts to run, it exits and fastlane stops after outputting this stack trace (as if it can't find Deliverfile). I've saved off the fastlane/ directory where I keep Deliverfile and it matches exactly what I have locally.

<details>
  <pre>On CircleCI I never see the success message saying that deliver was able to load Deliverfile. Instead, I get this stack trace after fastlane fails:

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
OpenURI::HTTPError: [!] 403 Forbidden
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `eval'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
  (eval):42:in `initialize'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `eval'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `initialize'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `new'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `load_configuration_file'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/actions/upload_to_app_store.rb:11:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:440:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:177:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
Exited with code 1
</pre>
</details>

### Environment

<details>
  <pre>CircleCI with Xcode 10.2.1</pre>
</details>

**Comment by janpio** [comment]
What does your `Deliverfile` look like?

Somehow doing `eval` on your `Deliverfile` content seems to `open` something that it interprets as an URL, that seems to return the 403.

**Comment by joulupukki** [comment]
@janpio You're a genius! We were loading in the App Store image from an Amazon S3 URL. Our build runs long enough (when building the app to make screenshots) that by the time `deliver` runs, the S3 Authorized URL had expired (10 minute timeout).

**Comment by janpio** [comment]
:D
