### ISSUE TITLE
Avoid 2FA during login with app-specific password using Xcode APIs

### ISSUE THREAD

**Issue by xoridius** [fastlane/fastlane#14803]
### Feature Request
Implement alternative login flow that uses app-specific password, does not require manual actions to complete 2FA and can be used with both App Store Connect and Apple Developer Portal.

#### Motivation Behind Feature
Enforcement of 2FA during portal login breaks automation, and current best practices [still require manual actions.](https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth)

#### Feature Description

The following API was found in multiple jailbreak tools that perform resigning. For more examples on usage one can search github ([by app id key](https://github.com/search?q=ba2ec180e6ca6e6c6a542255453b24d6e6e5b2be0cc48bc1b0d8ad64cfe0228f&type=Code), [portal attempt?](https://github.com/search?l=Ruby&q=clientDAW&type=Code)). Surprisingly, I did not find any references of those in fastlane issues, please add a link if it was discussed.

    curl -A "Xcode" --data "appIdKey=ba2ec180e6ca6e6c6a542255453b24d6e6e5b2be0cc48bc1b0d8ad64cfe0228f&appleId=APPLE_ID&password=APP_SPECIFIC_PASSWORD&protocolVersion=A1234&userLocale=en_US&format=plist" --header "application/x-www-form-urlencoded" "https://idmsa.apple.com/IDMSWebAuth/clientDAW.cgi"

API working with both `format=plist` and `format=json`. Example of successful json response:

    {
      "firstName": "John",
      "lastName": "Appleseed",
      "myacinfo": "myacinfo-working-with-portals",
      "creationTimeStamp": "2019-24-05 06:01:01",
      "responseID": "2813e878-4a46-4fc9-9983-5dc4ff1e24bc",
      "userLocale": "US-EN",
      "resultCode": "0",
      "resultString": "",
      "userString": "",
      "personId": 10541913234,
      "protocolVersion": "A1234"
    }

Obtained `myacinfo` works with fastlane portals once injected in cookies.

Q: Are there any drawbacks? Will this break anything for existing users?
Need to dig deeper into origin of this API to ensure all parameters are stable, but this one seem to be available long enough.

#### Alternatives or Workarounds
Alternative solutions like setting up twilio-like environment is hard to implement and likely to break (it does feasible with 2FA call verification though, but fastlane currently only support `mode=sms`).

https://github.com/fastlane/fastlane/issues/14249 https://github.com/fastlane/fastlane/issues/12713 https://github.com/fastlane/fastlane/issues/14617 https://github.com/fastlane/fastlane/issues/2053

**Comment by janpio** [comment]
Oh wow, that is an interesting API endpoint. 

The code you linked to is a bit ... strange, but if it works, it works. Would appreciate some more investigation where this API comes from, if it is stable/documented somewhere etc though.

> (it does feasible with 2FA call verification though, but fastlane currently only support `mode=sms`).

Feel free to create a feature request for this, I had a lot of "fun" implementing `mode=sms` ;)

**Comment by xoridius** [comment]
@janpio, agree on code quality of examples, but so are most jb tools ¯\\_(ツ)_/¯

I've found traces of the API in `ITunesConnectFoundation.framework` of Application Loader shipped with latest XCode.

<img width="839" alt="Screenshot 2019-05-24 at 16 18 17" src="https://user-images.githubusercontent.com/50968012/58354471-93401280-7e3f-11e9-9d97-a59159732fe6.png">

```
otool -L Application\ Loader 
Application Loader:
	@rpath/ITunesConnectAppKit.framework/Versions/A/ITunesConnectAppKit
	@rpath/ITunesConnectFoundation.framework/Versions/A/ITunesConnectFoundation
```

The only thing alarming is that it uses NSURLConnection (which has long been deprecated), so presumably this framework is to be replaced/updated sooner or later.

Regarding 2fa `mode=voice` verification - it would be nice to have for voice phone numbers!

**Comment by xoridius** [comment]
Updates after WWDC 2019:

Application Loader app was deprecated and transporter tool is now embedded within Xcode 11 frameworks. Updated `ITunesConnectFoundation.framework` uses `NSURLSession`, located at `Xcode-Beta/Contents/SharedFrameworks/ContentDeliveryServices.framework/Frameworks/ITunesConnectFoundation.framework`.

@janpio, any thoughts/updates on integration plans?

**Comment by janpio** [comment]
Deprecated or removed?
Do you have a link to a video recording of a session that mentioned that by chance?

**Comment by xoridius** [comment]
@janpio 

Not removed, but moved to Xcode frameworks. Application Loader is not present as part of Xcode/Applications. Contents of transporter tool (`iTMSTransporter` etc) are now in `ContentDeliveryServices.framework` (checked Xcode 11 beta 2)

Related session - [What's New in App Store Connect](https://developer.apple.com/videos/play/wwdc2019/301/) at 2:00.
