### ISSUE TITLE
Support multiple apple id

### ISSUE THREAD

**Issue by RacingWang** [fastlane/fastlane#1481]

**Comment by lacostej** [comment]
You can probably solve your issue using environment variables and --env

See https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#environment-variables

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (452/400 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:40585)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKsh-002lOq-3a
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:11 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Qk9zTub7UPtrzhWHwEzr7Acel+E=; b=pP/K4tGVGihQwP3E
	jzaaEurqId6Bhw9f9Wpi/PixmcAI8eDAuOv5mQprB5KPGHHAYsRQCLN5Pp1gARAo
	gHS/d6rLWgbrMpEblSbouh6qd7X5tuGKkyJ9+rXyYm1FHqXJyLa5MzwmCG3MvYNp
	aZqfmqT+sHwL7zd8mahEQuH1VXw=
Received: by filter0444p1mdw1.sendgrid.net with SMTP id filter0444p1mdw1.30868.5765911F18
        2016-06-18 18:21:19.272068598 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id WItyKT_-T6OlKnaBXYRvSQ
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:19.222 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:19 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (456/400 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:42892)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKss-002lSX-MW
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:22 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=W/vLa8UAoLZ+VDF/AUDhpGbizPA=; b=nW3jp46uREvzvVCk
	3yHifStRuuYWGLVs+CZr9NoVua8YnfERe9uF2C5hOjb+muAjoCsKtfxP/zawVH3g
	fgH+Lkfuc2wvO8zCUpc4AUO05+Woj4HiXrFNZeNnDO1Z0q3946war2b4PBrai7Bj
	zP9eae92egUgHsAH/s8ud7N9eAU=
Received: by filter0847p1mdw1.sendgrid.net with SMTP id filter0847p1mdw1.22236.5765911F1F
        2016-06-18 18:21:19.368502543 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 2Qc5Wi6iTtqfoMJxpr0xUg
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:19.245 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:19 -0700
