### ISSUE TITLE
fastlane match  failed in development 

### ISSUE THREAD

**Issue by littertwo** [fastlane/fastlane#14819]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

	platform :ios do
	#lane之前的操作
	before_all do
		# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
	end

	def prepare_version(options)
		if options[:version]
    increment_version_number(
        version_number: options[:version]
    )
		end
		if options[:build]
    increment_build_number(
        build_number: options[:build]
    )
		end
	end


	def uploadbugly(options)
		upload_app_to_bugly(# file_path, app_key, exp_id, title, desc, secret, users, password, download_limit
			app_id:ENV["BUGLY_APP_ID"],
			file:options[:file_path],
			fileName:options[:build] + "_" +options[:platform] + ".app.dSYM.zip",
			app_key:ENV["BUGLY_APP_KEY"],
			bundleId:ENV["BUNDLE_ID"],
			productVersion:options[:version]
		)
		end

	desc "test"
	lane :test do |options|
		options[:version] = "1.0.0"
		options[:build] = ""
		options[:platform] = ""
		options[:file_path] = "./dist/" + options[:platform] + "/" + options[:build] + "_" +options[:platform] + ".app.dSYM.zip"
		uploadbugly(options)
	end

	#打包到所有平台
	desc "Push a new release build to the all"
		lane :packageall do |options|
			
		options[:platform] = "testflight"
		options[:file_path] = "./dist/" + options[:platform] + "/" + options[:build] + "_" +options[:platform] + ".app.dSYM.zip"
		prepare_version(options)
		gym(clean:true, #打包前clean项目
			export_method: "app-store", #导出方式
			scheme:ENV["SCHEME"], #scheme
			configuration: "Release",#环境
			output_directory:"./dist/testflight/",#ipa的存放目录
			output_name: get_build_number() + "_" + options[:platform],#输出ipa的文件名为当前的build号
			include_bitcode: false,
			export_options:{
				compileBitcode: false,#尤为重要！！！
				provisioningProfiles: {
                ENV["BUNDLE_ID"] => ENV["APPSTORE_PROVISIONINGPROFILENAME"],
            }
				}
			)
		upload_to_testflight(
			ipa:"./dist/testflight/" + get_build_number() + "_" + options[:platform] + ".ipa",
      skip_waiting_for_build_processing: true  #是否跳过等待apple处理的过程
		)
		uploadbugly(options)

		options[:platform] = "pgyer"
		options[:file_path] = "./dist/" + options[:platform] + "/" + options[:build] + "_" +options[:platform] + ".app.dSYM.zip"
		prepare_version(options)
		gym(clean:true, #打包前clean项目
			export_method: "ad-hoc", #导出方式
			scheme:ENV["SCHEME"], #scheme
			configuration: "Release",#环境
			output_directory:"./dist/pgyer/",#ipa的存放目录
			output_name: get_build_number() + "_" + options[:platform],#输出ipa的文件名为当前的build号
			include_bitcode: false,
			export_options:{
				compileBitcode: false,#尤为重要！！！
				provisioningProfiles: {
                ENV["BUNDLE_ID"] => ENV["ADHOC_PROVISIONINGPROFILENAME"],
            }
				}
			)
		pgyer(api_key: ENV["PGYER_APIKEY"], user_key: ENV["PGYER_USERKEY"])
		uploadbugly(options)
		end

	#打包到蒲公英
	desc "Push a new release build to the pgyer"
		lane :packagepgyer do |options|
			options[:platform] = "pgyer"
			options[:file_path] = "./dist/" + options[:platform] + "/" + options[:build] + "_" +options[:platform] + ".app.dSYM.zip"
			prepare_version(options)
			gym(clean:true, #打包前clean项目
				export_method: "ad-hoc", #导出方式
				scheme:ENV["SCHEME"], #scheme
				configuration: "Release",#环境
				output_directory:"./dist/pgyer/",#ipa的存放目录
				output_name: get_build_number() + "_" + options[:platform],#输出ipa的文件名为当前的build号
				include_bitcode: false,
				export_options:{
					compileBitcode: false,#尤为重要！！！
					provisioningProfiles: {
									ENV["BUNDLE_ID"] => ENV["ADHOC_PROVISIONINGPROFILENAME"],
							}
					}
				)
			pgyer(api_key: ENV["PGYER_APIKEY"], user_key: ENV["PGYER_USERKEY"])
			uploadbugly(options)
		end

	#打包到TestFlight
	desc "Push a new release build to the pgyer"
		lane :packagetestflight do |options|
			options[:platform] = "testflight"
			options[:file_path] = "./dist/" + options[:platform] + "/" + options[:build] + "_" +options[:platform] + ".app.dSYM.zip"
			prepare_version(options)
			gym(clean:true, #打包前clean项目
				export_method: "app-store", #导出方式
				scheme:ENV["SCHEME"], #scheme
				configuration: "Release",#环境
				output_directory:"./dist/testflight/",#ipa的存放目录
				output_name: get_build_number() + "_" + options[:platform],#输出ipa的文件名为当前的build号
				include_bitcode: false,
				export_options:{
					compileBitcode: false,#尤为重要！！！
					provisioningProfiles: {
									ENV["BUNDLE_ID"] => ENV["APPSTORE_PROVISIONINGPROFILENAME"],
							}
					}
				)
			upload_to_testflight(
				ipa:"./dist/testflight/" + get_build_number() + "_" + options[:platform] + ".ipa",
				skip_waiting_for_build_processing: true  #是否跳过等待apple处理的过程
			)
			uploadbugly(options)
		end	


	#配置证书
	desc "update profile of appstore,adhoc,dev when udid added or renew dev account"
	  lane :pps do
	          match(git_url: ENV["CERTS_ADDRESS"],
	                git_branch:ENV["CERTS_BRANCH"],
									storage_mode:"git",
									app_identifier:ENV["BUNDLE_ID"],
									username:ENV["APPLEID"],
									type: "appstore")
	          match(git_url: ENV["CERTS_ADDRESS"],
	                git_branch:ENV["CERTS_BRANCH"],
									type: "development",
	                storage_mode:"git",
									app_identifier:ENV["BUNDLE_ID"],
									username:ENV["APPLEID"],
	     						force_for_new_devices: true)
	          match(git_url: ENV["CERTS_ADDRESS"],
	                git_branch:ENV["CERTS_BRANCH"],
									type: "adhoc",
									storage_mode:"git",
									app_identifier:ENV["BUNDLE_ID"],
									username:ENV["APPLEID"],
	     						force_for_new_devices: true)
	            end

	#同步证书
	desc "sync profile of appstore,adhoc,dev when admin has update cert and pps"
	  lane :syn do
	          match(git_url: ENV["CERTS_ADDRESS"],
	                type: "appstore" , 
									git_branch:ENV["CERTS_BRANCH"],
									storage_mode:"git",
									app_identifier:ENV["BUNDLE_ID"],
									username:ENV["APPLEID"],
	                readonly: true)
	          match(git_url: ENV["CERTS_ADDRESS"],
	                type: "development",
									git_branch:ENV["CERTS_BRANCH"],
									storage_mode:"git",
									app_identifier:ENV["BUNDLE_ID"],
									username:ENV["APPLEID"],
	                readonly: true)
	          match(git_url: ENV["CERTS_ADDRESS"],
	                type: "adhoc",
									git_branch:ENV["CERTS_BRANCH"],
									storage_mode:"git",
									app_identifier:ENV["BUNDLE_ID"],
									username:ENV["APPLEID"],
	                readonly: true)
	            end

	#添加设备
	desc "regist new device"
		lane :registdc do
			register_devices(
			  devices_file: "./fastlane/devices.txt"
			)
			match(git_url: ENV["CERTS_ADDRESS"],
	              type: "development",
								git_branch:ENV["CERTS_BRANCH"],
	              app_identifier: ENV["BUNDLE_ID"],
	     	      force_for_new_devices: true)
            match(git_url: ENV["CERTS_ADDRESS"],
                  type: "adhoc",
									git_branch:ENV["CERTS_BRANCH"],
                  app_identifier: ENV["BUNDLE_ID"],
     			  force_for_new_devices: true)
		end

		#更新设备
		desc "update new devices"
			lane :updatedc do
				match(git_url: ENV["CERTS_ADDRESS"],
							type: "development",
							git_branch:ENV["CERTS_BRANCH"],
							storage_mode:"git",
							app_identifier: ENV["BUNDLE_ID"],
							username:ENV["APPLEID"],
							force_for_new_devices: true)
				match(git_url: ENV["CERTS_ADDRESS"],
							type: "adhoc",
							git_branch:ENV["CERTS_BRANCH"],
							storage_mode:"git",
							username:ENV["APPLEID"],
							app_identifier: ENV["BUNDLE_ID"],
							force_for_new_devices: true)
			end

	#lane执行完的操作
	after_all do
		#slack(
		# message:"Successfully deloyed new App Update"
		#)
			  end

	error do |lane,exception|
		#slack(
		#  message: exxception,message,
		#  success: false
		#)
		  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.saicmobility.driver") # The bundle identifier of your app
apple_id("jiangjie@saicmobility.com") # Your Apple email address

itc_team_id("686519") # App Store Connect Team ID
team_id("QFJ7PWAWS8") # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.3        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| jwt                       | 2.2.1        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
| fastlane-plugin-pgyer     | 0.2.2        |
</details>

*generated on:* **2019-05-28**
</details>

<details>
  
![image](https://user-images.githubusercontent.com/17488101/58446003-8cf8b180-8131-11e9-835e-836d4175def5.png)

</details>

**Comment by max-ott** [comment]
Hi there, please provide us some more information to be able to help you. The issue template asks for all required data.
