### ISSUE TITLE
Doubt about how to use "Spaceship" to improve the speed comparison of "Fastlane" login to the "App Store".

### ISSUE THREAD

**Issue by sigelion** [fastlane/fastlane#14828]
### 4、 Thank you.

**Comment by max-ott** [comment]
Hi @sigelion and welcome to `fastlane`. All our code is open source and you can therefore check the login flow and similar.

1) `Fastlane` uses `Spaceship` under the hood as well `fastlane_core`

2) It is exactly happening what the UI tells you. Cookie / session is no longer possible. Not sure what your question is.

2.1 and 2.2. There is no "slow" and "fast" login. There is only a login method, which speed is based on a tons of factors: Your own internet speed, latency, proximity to Apple's servers etc.

3) See above

**Comment by sigelion** [comment]
How long will the Cookie / session  last before it expires, and the cumulative duration will start from the first connection or the last disconnect.

**Comment by sigelion** [comment]
And、When is the session disconnected depending on "/Users/cp/.fastlane/spaceship/xxxxxx.com/cookie"  this file?

**Comment by janpio** [comment]
> When is the session disconnected depending on "/Users/cp/.fastlane/spaceship/xxxxxx.com/cookie" this file?

spaceship will try to use that Cookie. If the authentication fails, you will get the `Available session is not valid any more. Continuing with normal login.` error message you mentioned in your first post.
