### ISSUE TITLE
Support Puck with HockeyApp

### ISSUE THREAD

**Issue by AymenFarrah** [fastlane/fastlane#1482]
Hockey action actually dont support puck.
We need to use puck in "notes" value here instead of "Changelog" : 
hockey(
          api_token:@hockeyAppAPIKey,
          ipa:ipaPath,
          notes:"Changelog"
          )

Puck automatically provide markdown formatted release notes!

Thank you

**Comment by AymenFarrah** [comment]
# Upload to HockeyApp
 /usr/local/bin/puck -submit=auto -download=true -collect_notes_type=jenkins_aggregate -collect_notes_path="${WORKSPACE}" -notes_type=markdown -source_path="${WORKSPACE}" -repository_url=http://repository.server/repository-path -api_token=10101010101010101010101010101010 -app_id=01010101010101010101010101010101 "$ARCHIVE_PACKAGE"

**Comment by tagyro** [comment]
Aditionally it would be nice if we could grep the result from a hockey upload and get the download link.

For example, this is a default hockey step output:
```
[11:33:56]: Starting with ipa upload to HockeyApp... this could take some time.  
[11:47:59]: Public Download URL: https://upload.hockeyapp.net/apps/XXXXXXXXX  
[11:47:59]: Build successfully uploaded to HockeyApp!  
```
and we could use the "public download url" in a subsequent step like Slack integration etc.

**Comment by KrauseFx** [comment]
@tagyro you can, just use the following:
```ruby
url = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
build_info = lane_context[SharedValues::HOCKEY_BUILD_INFORMATION]
```
more information via
```
fastlane action hockey
```

**Comment by tagyro** [comment]
@KrauseFx Thanks, much appreciated!
