### ISSUE TITLE
Is that possible to keep match in the same repo as code

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#14826]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Using Match in the same repo as code

#### Question Description
I want to use match in the same repo as my code, is that possible how to correctly set it up?

**Comment by janpio** [comment]
I have no experience with it and don't really understand why you want to do that, but I don't see any reason why it should not work. You just have to make sure that your actual project doesn't clash with the files and folders that match creates: https://docs.fastlane.tools/actions/match/#folder-structure Note that having more files than necessary in the match repository might also slow down the action.

Setup should be identical to how it is documented.

**Comment by romk1n** [comment]
@janpio thanks for response. The biggest reason is that giving access to one repository you don't need to provide access to another repository. If you have many clients and keep all of the in one repository it may have advantages and disadvantages. Advantage is that all in one places. But disadvantage is that you have to provide access to that repository and potentially leak the names of the clients.

Anyway I have re-read some docs and it is indeed possible. I just needed to specify a branch other then master to keep things clean.

**Comment by janpio** [comment]
Oh of course, using a branch is of course the proper solution.
