### ISSUE TITLE
Android build with fastlane calls InvalidUserDataException

### ISSUE THREAD

**Issue by nikolaypopadiuksigma** [fastlane/fastlane#14822]
I run android build with command in root project dir

`rvm_sh 'bundle exec fastlane android build_play_store --verbose'`
And I have error

> Project directory '/private/tmp/jenkins/workspace/Android-Build-GPlay_master/Build/Android/Test Box/fastlane' is not part of the build defined by settings file '/private/tmp/jenkins/workspace/Android-Build-GPlay_master/Build/Android/Test Box/settings.gradle'. If this is an unrelated build, it must have its own settings file

.

In dir Test Box/fastlane/ I have only this files:

- Appfile
- Fastfile
- Gymfile
- Matchfile
- README.md
- report.xml

My settings.gradle contains only this lines

- include 'answers'
- include 'beta'
- include 'crashlytics'
- include 'crashlytics-wrapper'
- include 'fabric'
- include 'fabric-init'

Do you have any idea how resolve this error?

**Comment by janpio** [comment]
Can you please post the complete command, output and environment you are running/getting? Currently your issue does not have enough information to properly understand and/or debug this.
