### ISSUE TITLE
Updating pilot at the same time as fastlane

### ISSUE THREAD

**Issue by mark5422** [fastlane/fastlane#1483]
I've noticed that a couple of things that fastlane can use aren't updated when doing

``` sudo gem update fastlane ```

pilot being on that springs to mind. Can that be added so that it any anything else that fastlane can use such as gym will be updated in one command?

**Comment by asfalcone** [comment]
Hi @mark5422 it looks like the [gemspec](https://github.com/fastlane/fastlane/blob/master/fastlane.gemspec) got a little behind. I've updated the gems here #1485

**Comment by mark5422** [comment]
Thanks.
