### ISSUE TITLE
Simplified Chinese show incompletely on windows

### ISSUE THREAD

**Issue by MagicalWater** [fastlane/fastlane#14831]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
File - .env
```
ANDROID_NAME='简体中文名称'
ANDROID_NAME2='簡體中文名稱'
```

Action - update_info.rb
```
module Fastlane
  module Actions
    module SharedValues
      UPDATE_INFO_CUSTOM_VALUE = :UPDATE_INFO_CUSTOM_VALUE
    end

    class UpdateInfoAction < Action
      def self.run(params)
        androidName = params[:android_name]
        androidName2 = params[:android_name2]
        puts "#{androidName}"
        puts "#{androidName2}"
      end

      def self.description
      end

      def self.details
        "You can use this action to do cool things..."
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :android_name,
                                       env_name: "ANDROID_NAME",
                                       description: "Android App Name",
                                       is_string: true,
                                       optional: false),
          FastlaneCore::ConfigItem.new(key: :android_name2,
                                       env_name: "ANDROID_NAME2",
                                       description: "Android App Name2",
                                       is_string: true,
                                       optional: false),
        ]
      end

      def self.output
      end

      def self.return_value
      end

      def self.authors
        ["Your GitHub/Twitter Name"]
      end

      def self.is_supported?(platform)
        platform == :android
      end
    end
  end
end
```

File - Fastfile
```
fastlane_require 'dotenv'

before_all do |_lane, _options|
  Dotenv.load(".env.#{ENV['ENV']}.secret")
end

platform :android do
  lane :update do
    update_info()
  end
end
```

type command
```
fastlane android update
```

and output is
```
?体中文名?
簡體中文名稱
```

**Comment by janpio** [comment]
What command line are you using? When I try to input or output any of the characters you posted above with `cmd.exe`, I only get displayed blocks with `?` inside:

![image](https://user-images.githubusercontent.com/183673/58702341-d5200a00-83a5-11e9-8187-8ae462a25e9a.png)

But when I copy the data out, I again get the correct characters:

```
C:\Users\Jan>set ANDROID_NAME=简体中文名称

C:\Users\Jan>echo %ANDROID_NAME%
简体中文名称

C:\Users\Jan>cd Desktop

C:\Users\Jan\Desktop>ruby lala.rb
簡體中文名稱
```

**Comment by MagicalWater** [comment]
i am running on Android Studio terminal,
but i have a same issue on cmd,

![image](https://user-images.githubusercontent.com/16315102/58714664-c6fad980-83f7-11e9-916f-5c9e228f6fcd.png)

and my Fastfile

```
fastlane_require 'dotenv'

before_all do |_lane, _options|
  Dotenv.load(".env.#{ENV['ENV']}.secret")
end

platform :android do
  lane :update do
    update_info()
  end
end
```

**Comment by janpio** [comment]
Interesting.

Can you maybe try to output an environment variable you set outside of Fastlane, instead of via Dotenv? Maybe this is not about Fastlane at all, but Dotenv?

**Comment by MagicalWater** [comment]
ok, is like with this?

![image](https://user-images.githubusercontent.com/16315102/58718940-227d9500-8401-11e9-9971-c15ca9d9132f.png)

![image](https://user-images.githubusercontent.com/16315102/58718888-05e15d00-8401-11e9-8831-47df0346ba9c.png)

**Comment by MagicalWater** [comment]
ok, is like with this?

![image](https://user-images.githubusercontent.com/16315102/58719112-7daf8780-8401-11e9-869b-e126465ab601.png)

![image](https://user-images.githubusercontent.com/16315102/58719100-77b9a680-8401-11e9-9576-24f134707f87.png)

**Comment by janpio** [comment]
`set FOO=简体中文名称` in the command line, then `puts ENV['FOO']` in your lane directly to see if it can output the ENV var without the loading stuff in between.

**Comment by MagicalWater** [comment]
OK,

![image](https://user-images.githubusercontent.com/16315102/58719735-ff53e500-8402-11e9-90d0-dd7ae0bf55f9.png)

**Comment by janpio** [comment]
next with a simple ruby file `foo.rb`:

```
puts ENV['FOO']
```

**Comment by MagicalWater** [comment]
ok, 
![image](https://user-images.githubusercontent.com/16315102/58720090-d1bb6b80-8403-11e9-9e4d-bb0a1ad0c98f.png)

**Comment by janpio** [comment]
Ok, this effectively means that this is a pure ruby problem, not something fastlane can fix unfortunately. Depending on how you installed Ruby on your machine, you should report it to the creators of the distribution or maybe even to Ruby itself.

Sorry I can't be of help here.

**Comment by MagicalWater** [comment]
Ok, i got it.
Thank you so much.
