### ISSUE TITLE
Manually encrypt/decrypt repository

### ISSUE THREAD

**Issue by ir2pid** [fastlane/fastlane#14832]
### Question Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
I'm trying to manually encrypt a repo using the fastlane match commands
Here the in the code I do:
1. download an empty repo.
2. create a out.txt file with a timestamp
3. encrypt the repo directory
4. commit the repo back

But the repo out.txt file isn't encrypted. Seems `encryption.encrypt_files` didn't work.

<details><summary>**code:**</summary>

  ```
desc "Encrypt git"
  lane :test do  
    UI.success "Encrypting git!"
    storage = Match::Storage.for_mode("git", { git_url: git_url, shallow_clone: shallow_clone, git_branch: branch, clone_branch_directly: true})  
    storage.download
    encryption = Match::Encryption.for_storage_mode("git", { git_url: git_url, working_directory: storage.working_directory})
    encryption.decrypt_files
    file = "#{storage.working_directory}/out.txt"
    out_file = File.new("#{file}", "w")
    out_file.puts("version:#{Time.now.to_i}")
    out_file.close 
    files_to_commit = Dir[File.join(storage.working_directory, "**", "*.{txt}")]
    if files_to_commit.count > 0 # && !params[:readonly]
      encryption.encrypt_files
      storage.save_changes!(files_to_commit: files_to_commit)
    end
  end 
```

</details>

<details><summary>**output:**</summary>

```
Successfully loaded Appfile at path '/Users/xx/Workspace/yy/ci/zz/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/xx/Workspace/yy/ci/zz/fastlane/Appfile'
-------
WARN [2019-05-31 03:15:16.70]: You have required a gem, if this is a third party gem, please use `fastlane_require 'match'` to ensure the gem is installed locally.
INFO [2019-05-31 03:15:17.00]: ------------------------------
INFO [2019-05-31 03:15:17.00]: --- Step: default_platform ---
INFO [2019-05-31 03:15:17.00]: ------------------------------
INFO [2019-05-31 03:15:17.01]: Driving the lane 'mac test' 🚀
INFO [2019-05-31 03:15:17.01]: Encrypting git!
INFO [2019-05-31 03:15:17.01]: Cloning remote git repo...
INFO [2019-05-31 03:15:17.01]: $ git clone ./../gitrepo/.git /var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael -b master --single-branch
INFO [2019-05-31 03:15:17.02]: ▸ Cloning into '/var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael'...
INFO [2019-05-31 03:15:17.13]: ▸ done.
INFO [2019-05-31 03:15:17.15]: 🔓  Successfully decrypted certificates repo
INFO [2019-05-31 03:15:17.15]: 🔒  Successfully encrypted certificates repo
INFO [2019-05-31 03:15:17.15]: Pushing changes to remote git repo...
INFO [2019-05-31 03:15:17.15]: $ git add /var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael/match_version.txt
INFO [2019-05-31 03:15:17.17]: $ git add /var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael/out.txt
INFO [2019-05-31 03:15:17.19]: $ git commit -m \[fastlane\]\ Updated\ \ and\ platform\ 
INFO [2019-05-31 03:15:17.24]: ▸ [master 6bdc078] [fastlane] Updated  and platform
INFO [2019-05-31 03:15:17.25]: ▸ 1 file changed, 1 insertion(+), 1 deletion(-)
INFO [2019-05-31 03:15:17.25]: $ git push origin master
INFO [2019-05-31 03:15:17.31]: ▸ Enumerating objects: 5, done.
INFO [2019-05-31 03:15:17.31]: ▸ Counting objects: 100% (5/5), done.
INFO [2019-05-31 03:15:17.31]: ▸ Delta compression using up to 8 threads.
INFO [2019-05-31 03:15:17.31]: ▸ Compressing objects: 100% (2/2), done.
INFO [2019-05-31 03:15:17.32]: ▸ Writing objects: 100% (3/3), 289 bytes | 144.00 KiB/s, done.
INFO [2019-05-31 03:15:17.32]: ▸ Total 3 (delta 1), reused 0 (delta 0)
INFO [2019-05-31 03:15:17.37]: ▸ To /Users/xx/Workspace/yy/ci/zz/fastlane/./../gitrepo/.git
INFO [2019-05-31 03:15:17.37]: ▸ cac225c..6bdc078  master -> master
INFO [2019-05-31 03:15:17.37]: Finished uploading files to Git Repo [./../gitrepo/.git]
INFO [2019-05-31 03:15:17.44]: Successfully generated documentation at path '/Users/xx/Workspace/yy/ci/zz/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

INFO [2019-05-31 03:15:17.45]: fastlane.tools finished successfully 🎉
```
</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'match'

git_url = './../gitrepo/.git'
shallow_clone = false
branch = 'master'

default_platform(:mac)

platform :mac do

  desc "Encrypt git"
  lane :test do  
    UI.success "Encrypting git!"
    storage = Match::Storage.for_mode("git", { git_url: git_url, shallow_clone: shallow_clone, git_branch: branch, clone_branch_directly: true})  
    storage.download
    encryption = Match::Encryption.for_storage_mode("git", { git_url: git_url, working_directory: storage.working_directory})
    encryption.decrypt_files
    file = "#{storage.working_directory}/out.txt"
    out_file = File.new("#{file}", "w")
    out_file.puts("version:#{Time.now.to_i}")
    out_file.close 
    files_to_commit = Dir[File.join(storage.working_directory, "**", "*.{txt}")]
    if files_to_commit.count > 0 # && !params[:readonly]
      #password = "#{ENV["MATCH_PASSWORD"]}"
      #encryption.clear_password
      #encryption.store_password(password)
      encryption.encrypt_files
      storage.save_changes!(files_to_commit: files_to_commit)
    end
  end 
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.123.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.2        |
| bundler                   | 1.17.1       |
| faraday_middleware        | 0.13.1       |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| jwt                       | 2.2.1        |
| os                        | 1.0.1        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-05-31**
</details>

**Comment by janpio** [comment]
Please run the lane with `--verbose` added at the end and post the new output you are getting.

**Comment by ir2pid** [comment]
> Please run the lane with `--verbose` added at the end and post the new output you are getting.
here
<detail><summary>output verbose</summary>
```
Successfully loaded Appfile at path '/Users/xx/Workspace/yy/ci/zz/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/xx/Workspace/yy/ci/zz/fastlane/Appfile'
-------
WARN [2019-05-31 03:15:16.70]: You have required a gem, if this is a third party gem, please use `fastlane_require 'match'` to ensure the gem is installed locally.
INFO [2019-05-31 03:15:17.00]: ------------------------------
INFO [2019-05-31 03:15:17.00]: --- Step: default_platform ---
INFO [2019-05-31 03:15:17.00]: ------------------------------
INFO [2019-05-31 03:15:17.01]: Driving the lane 'mac test' 🚀
INFO [2019-05-31 03:15:17.01]: Encrypting git!
INFO [2019-05-31 03:15:17.01]: Cloning remote git repo...
INFO [2019-05-31 03:15:17.01]: $ git clone ./../gitrepo/.git /var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael -b master --single-branch
INFO [2019-05-31 03:15:17.02]: ▸ Cloning into '/var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael'...
INFO [2019-05-31 03:15:17.13]: ▸ done.
INFO [2019-05-31 03:15:17.15]: 🔓  Successfully decrypted certificates repo
INFO [2019-05-31 03:15:17.15]: 🔒  Successfully encrypted certificates repo
INFO [2019-05-31 03:15:17.15]: Pushing changes to remote git repo...
INFO [2019-05-31 03:15:17.15]: $ git add /var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael/match_version.txt
INFO [2019-05-31 03:15:17.17]: $ git add /var/folders/7s/s7248n8j0yz0lth821hx4bdm0000gp/T/d20190531-95641-60lael/out.txt
INFO [2019-05-31 03:15:17.19]: $ git commit -m \[fastlane\]\ Updated\ \ and\ platform\ 
INFO [2019-05-31 03:15:17.24]: ▸ [master 6bdc078] [fastlane] Updated  and platform
INFO [2019-05-31 03:15:17.25]: ▸ 1 file changed, 1 insertion(+), 1 deletion(-)
INFO [2019-05-31 03:15:17.25]: $ git push origin master
INFO [2019-05-31 03:15:17.31]: ▸ Enumerating objects: 5, done.
INFO [2019-05-31 03:15:17.31]: ▸ Counting objects: 100% (5/5), done.
INFO [2019-05-31 03:15:17.31]: ▸ Delta compression using up to 8 threads.
INFO [2019-05-31 03:15:17.31]: ▸ Compressing objects: 100% (2/2), done.
INFO [2019-05-31 03:15:17.32]: ▸ Writing objects: 100% (3/3), 289 bytes | 144.00 KiB/s, done.
INFO [2019-05-31 03:15:17.32]: ▸ Total 3 (delta 1), reused 0 (delta 0)
INFO [2019-05-31 03:15:17.37]: ▸ To /Users/xx/Workspace/yy/ci/zz/fastlane/./../gitrepo/.git
INFO [2019-05-31 03:15:17.37]: ▸ cac225c..6bdc078  master -> master
INFO [2019-05-31 03:15:17.37]: Finished uploading files to Git Repo [./../gitrepo/.git]
INFO [2019-05-31 03:15:17.44]: Successfully generated documentation at path '/Users/xx/Workspace/yy/ci/zz/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

INFO [2019-05-31 03:15:17.45]: fastlane.tools finished successfully 🎉

```

</detail>

**Comment by janpio** [comment]
Before `🔒  Successfully encrypted certificates repo` you should get `🔒  Encrypted '...'` for reach file - https://github.com/fastlane/fastlane/blob/2545fd0225b85c1204b30061f01a30ebd21d45d3/match/lib/match/encryption/openssl.rb#L31-L40 - so something is going wrong here. Looking at the further code I don't really understand why this is not working.

**Comment by salmanasiddiqui** [comment]
match only encryptes `*.{cer,p12,mobileprovision}` files.

https://github.com/fastlane/fastlane/blob/master/match/lib/match/encryption/openssl.rb#L73
```
def iterate(source_path)
  Dir[File.join(source_path, "**", "*.{cer,p12,mobileprovision}")].each do |path|
    next if File.directory?(path)
    yield(path)
  end
end
```

**Comment by janpio** [comment]
Thanks for catching that @salmanasiddiqui! That of course explains the behaviour.

You can of course encrypt the files manually @ir2pid by encrypting them explicitly with https://github.com/fastlane/fastlane/blob/2545fd0225b85c1204b30061f01a30ebd21d45d3/match/lib/match/encryption/openssl.rb#L35
