### ISSUE TITLE
FastLane 2.124 FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by rickthefree** [fastlane/fastlane#14835]
### New Issue Checklist

- [X] Updated fastlane to the latest version 2.124
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Yesterday we started seeing this error in 2.124.  We ran our build locally using version 2.123 and everything works successfully.  This failure started happening after fastlane was updated in the build to 2.124.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[20:38:24]: Resetting iPhone 8
[20:38:25]: App Identifier: 
[20:38:26]: -------------------
[20:38:26]: --- Step: slack ---
[20:38:26]: -------------------
[20:38:26]: Successfully sent Slack notification
+----------------------------+---------------------------+
|                      Lane Context                      |
+----------------------------+---------------------------+
| DEFAULT_PLATFORM           | ios                       |
| PLATFORM_NAME              | ios                       |
| LANE_NAME                  | ios test_without_building |
| SCAN_DERIVED_DATA_PATH     | ./DerivedData             |
| SCAN_GENERATED_PLIST_FILES | []                        |
| SCAN_GENERATED_PLIST_FILE  |                           |
+----------------------------+---------------------------+
[20:38:26]: Could not retrieve response as fastlane runs in non-interactive mode

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | run_tests        | 16          |
| 3    | slack            | 0           |
+------+------------------+-------------+

[20:38:26]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Supply isn't working on CI with Google auth .p12 files
    https://github.com/fastlane/fastlane/issues/14128 [closed] 2 💬
    6 weeks ago

➡️  gitlab-runner exec shell result FastlaneCrash
    https://github.com/fastlane/fastlane/issues/13675 [closed] 4 💬
    24 Feb 2019

➡️  [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/12355 [closed] 10 💬
    19 Nov 2018

and 34 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (<our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:128:in `input'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/scan/lib/scan/runner.rb:43:in `test_app'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/scan/lib/scan/runner.rb:22:in `run'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/scan/lib/scan/manager.rb:18:in `work'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/actions/run_tests.rb:23:in `run'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:60:in `block (2 levels) in parsing_binding'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/gems/fastlane-2.124.0/bin/fastlane:23:in `<top (required)>'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/bin/fastlane:23:in `load'
  <our_workspace_dir>/<our_job_name>/vendor/bundle/ruby/2.5.0/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details>
  <pre> NOTE: I added the 'fastlane env' command to one of our other jobs to get output.  Not sure if you need information specifically from the fastfile in the failing build, or just the info about the system.

+ fastlane env
[09:18:19]: fastlane detected a Gemfile in the current directory
[09:18:19]: however it seems like you don't use `bundle exec`
[09:18:19]: to launch fastlane faster, please use
[09:18:19]: 
[09:18:19]: $ bundle exec fastlane env
[09:18:19]: 
[09:18:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:18:22]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.124.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.2.1        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-05-31**
</details>
[09:18:22]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
 </pre>
</details>

**Comment by janpio** [comment]
Can you run the same lane locally and see if it prompts you for something?
Can you please share your `Fastfile`? Especially around line 60 if I read that trace correctly.

**Comment by rickthefree** [comment]
Hey @janpio here is the section from the Fastfile.  Let me know if you need more.

  desc "Run tests without building"
  lane :test_without_building do

    run_tests(
      clean: false,
      configuration: "Debug",
      derived_data_path: @derived_data_path,
      scheme: @test_scheme,
      skip_slack: true,
      reinstall_app: true,
      reset_simulator: true,
      test_without_building: true,
      workspace: "iPhone/#{@project}.xcworkspace",
    )
  end

**Comment by janpio** [comment]
Running the lane locally would be the simplest way to find out what is happening.
And to the snippet you posted: Which one is line 60?

**Comment by rickthefree** [comment]
Apologies.  edited with line numbers.
