### ISSUE TITLE
Building android with gradle and remote keystore

### ISSUE THREAD

**Issue by JayCantyEMoney** [fastlane/fastlane#14833]
### Question Subject
Fastlane gradle

#### Question Description
I am following your steps to bundle a android project and sign it with keystore like;

```
gradle(
  task: "bundle",
  build_type: "Release",
  properties: {
    "android.injected.signing.store.file" => "keystore.jks",
    "android.injected.signing.store.password" => "store_password",
    "android.injected.signing.key.alias" => "key_alias",
    "android.injected.signing.key.password" => "key_password",
  }
)
```

I am using a cd server (bitrise) to store the keystore.jks.

My question is, is there a way to use the remote url for `"android.injected.signing.store.file" => "some http url",`

Would I maybe have to copy it somewhere local, then use a path?

Thanks

**Comment by janpio** [comment]
If you can provide a remote URL I don't know, as this part is handled by gradle.

But yes, downloading the file and using that path sounds like a reasonable solution. Many CI providers also provide a mechanism to handle secret files (upload in a web UI, then have a env var with its URL to use during the build for example).

**Comment by JayCantyEMoney** [comment]
Ahhh, this is more of a gradle question than a fastlane question, sorry.  I can ask in a gradle forum.

I did manage to work around it by using `gradle('bundle')` -> pass the .aab path to Bitrise:sign_apk:step -> pass signed .aad path to `supply`

Tiny trick, to get fastlane .aab path(s), add these lines after `gradle(bundle)`

 ```
gradle(task: 'bundle')....
```

Please feel free to close.

**Comment by janpio** [comment]
Where does `Bitrise:sign_apk:step` get the signing credentials from? Can you upload them for it on Bitrise?

**Comment by JayCantyEMoney** [comment]
Yesir, they have code signing storage and vars

**Comment by janpio** [comment]
Ok, then that sounds like probably the simpler workaround.



> puts "AABs: #{Actions.lane_context[SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS]}"
> puts "AAB: #{Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"

Yay, we just added those to the documentation: https://docs.fastlane.tools/actions/gradle/#lane-variables @mollyIV <3
