### ISSUE TITLE
Feature request: List all commits in Slack message after last build

### ISSUE THREAD

**Issue by jaroslavas** [fastlane/fastlane#1484]
I'm pushing a notification to Slack after successful build and upload. It would be super useful, if I could send not only the last commit message, but all commit massages until there is some special commit (in my case that would be "Version bump to %i".
Example git history:
* Version bump to 457
* New feature 125
* Fixed feature 99
* New feature 124
* Version bump to 456
* Fixed bug 52
* ...

Now, its possible to send only `Version bump to 457` git message. What I would like is to send everything from `Version bump to 457` down to `New feature 124`

**Comment by ohwutup** [comment]
Hey @jaroslavas! Thanks for submitting the issue. This would be a great enhancement to the slack action. I would be happy to review a PR if you wanted to give it a go! I am going to close this for now, but if you do decide to bite off the work, feel free to reopen the issue!

**Comment by CavalcanteLeo** [comment]
+1
