### ISSUE TITLE
Can fastlane run on macos virtual machine OR Linux?

### ISSUE THREAD

**Issue by sigelion** [fastlane/fastlane#14843]
### Can Fastlane's actions:"register_device()" and  "get_provisioning_profile()" run on  Linux System OR macos virtual machine? and How to install?

**Comment by janpio** [comment]
> Can Fastlane's actions:"register_device()" and "get_provisioning_profile()" run on Linux System OR macos virtual machine?

Yes, both these actions should work on all operating systems. (If `get_provisioning_profile` also tries to install the profile, this will of course not work)

> How to install?

Install ruby, then install according to the documentation.

**Comment by sigelion** [comment]
> > Can Fastlane's actions:"register_device()" and "get_provisioning_profile()" run on Linux System OR macos virtual machine?
> 
> Yes, both these actions should work on all operating systems. (If `get_provisioning_profile` also tries to install the profile, this will of course not work)
> 
> > How to install?
> 
> Install ruby, then install according to the documentation.

Now, Fastlane is already installed on the Linux system, but there is a problem when storing information on the keychain. Because there is no keychain in Linux.

**Comment by janpio** [comment]
Of course, what did you expect? But it shouldn't throw any errors and work as far as possible.

**Comment by sigelion** [comment]
> Of course, but that is expected, isn't it?
> But it shouldn't throw any errors and work as far as possible.

I want to get the latest ".mobileprovision" file on Linux via Fastlane's "get_provisioning_profile()" action. Instead of installing it, I use this file to execute "code-resign" on the ".ipa" package.

**Comment by janpio** [comment]
`get_provisioning_profile` has an parameter `output_path` where you can set a path where it should put the file.

**Comment by sigelion** [comment]
> `get_provisioning_profile` has an parameter `output_path` where you can set a path where it should put the file.

### You are right, the problem is that there is an error in executing "get_provisioning_profile()": 
Available session is not valid any more. Continuing with normal login.
[09:29:52]: error
+------------------+----------------------------+
| Lane Context |
+------------------+----------------------------+
| DEFAULT_PLATFORM | ios |
| PLATFORM_NAME | ios |
| LANE_NAME | ios cp_get_mobileprovision |
+------------------+----------------------------+
### [09:29:52]: Unauthorized Access

+------+--------------------------+-------------+
| fastlane summary |
+------+--------------------------+-------------+
| Step | Action | Time (in s) |
+------+--------------------------+-------------+
| 1 | default_platform | 0 |
| 💥 | get_provisioning_profile | 11 |
+------+--------------------------+-------------+

[09:29:52]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️ The request could not be completed because: Unauthorized Access
    Https://github.com/fastlane/fastlane/issues/13923 [closed] 14 💬
    2 days ago

➡️ The request could not be completed because: Unauthorized Access
    Https://github.com/fastlane/fastlane/issues/14122 [closed] 1 💬
    01 Apr 2019

➡️ Google::Apis::AuthorizationError: [!] Unauthorized
    Https://github.com/fastlane/fastlane/issues/14268 [closed] 14 💬
    3 weeks ago

And 11 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓


[!] The request could not be completed because:
###  Unauthorized Access

**Comment by janpio** [comment]
Please post the complete output, what you posted only tell what kind of error is happening, not what is causing it.

**Comment by janpio** [comment]
ping @sigelion
