### ISSUE TITLE
latest_testflight_build_number crashes in 2.125.0

### ISSUE THREAD

**Issue by jcharr1** [fastlane/fastlane#14846]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.125.0
- Last working version: 2.124.0

### Regression Description

Running latest_testflight_build_number (or app_store_build_number with `live` set to false) crashes with `undefined method '[]' for Spaceship::ConnectAPI::PreReleaseVersion` with fastlane 2.125.0.
 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle exec fastlane run latest_testflight_build_number --verbose                 
[✔] 🚀 
DEBUG [2019-06-03 02:14:41.48]: Checking if there are any plugins that should be loaded...
DEBUG [2019-06-03 02:14:41.48]: Loading 'fastlane-plugin-trainer' plugin
INFO [2019-06-03 02:14:41.48]: gem 'fastlane-plugin-trainer' is already installed
+-------------------------+---------+---------+
|                Used plugins                 |
+-------------------------+---------+---------+
| Plugin                  | Version | Action  |
+-------------------------+---------+---------+
| fastlane-plugin-trainer | 0.4.1   | trainer |
+-------------------------+---------+---------+

Successfully loaded Appfile at path '/Volumes/DATA/My Documents/ILL/iPhone/Projects/ILL for iOS/git/IL101 for iOS/InnovativeLanguage.com/fastlane/Appfile'
- app_identifier: [REDACTED]
- apple_id: [REDACTED]
- team_id: [REDACTED]
-------
INFO [2019-06-03 02:14:41.75]: --------------------------------------------
INFO [2019-06-03 02:14:41.75]: --- Step: latest_testflight_build_number ---
INFO [2019-06-03 02:14:41.75]: --------------------------------------------
INFO [2019-06-03 02:14:41.90]: Login to App Store Connect ([REDACTED])
Reading keychain entry, because either user or password were empty
Loading session from '/Users/jason/.fastlane/spaceship/[REDACTED]/cookie'
Looking for App Store Connect Team with ID [REDACTED]
INFO [2019-06-03 02:14:43.06]: Login successful

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method '[]' for Spaceship::ConnectAPI::PreReleaseVersion

URL: https://api.github.com/search/issues?q=undefined%20method%20%60%5B%5D%27%20for%20Spaceship%3A%3AConnectAPI%3A%3APreReleaseVersion+repo:fastlane/fastlane
➡️  latest_testflight_build_number returns random data
    https://github.com/fastlane/fastlane/issues/14606 [open] 25 💬
    a day ago

➡️  [spaceship/pilot] New Spaceship::ConnectAPI module and removal of Spaceship::TestFlight from Pilot and BuildWatcher
    https://github.com/fastlane/fastlane/pull/14566 [closed] 6 💬
    a day ago

➡️  [spaceship, pilot] Getting "410 gone"
    https://github.com/fastlane/fastlane/issues/14521 [closed] 177 💬
    6 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2019-06-03 02:14:48.43]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/opt/gems/bin/fastlane)
NoMethodError: [!] undefined method `[]' for #<Spaceship::ConnectAPI::PreReleaseVersion:0x00007f96c88801b0>
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:47:in `get_build_number'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:11:in `run'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:11:in `run'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
  /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/opt/gems/gems/fastlane-2.125.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/opt/gems/gems/fastlane-2.125.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/opt/gems/bin/fastlane:23:in `load'
  /usr/local/opt/gems/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/opt/gems/bin/fastlane            |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# fastlane Fastfile - Contains lane definitions for batch fastlane actions.
#                     This is fastlane's main point of entry.
# Author: Jason Charrier
# Created: April 10, 2017

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

my_hostname = sh "hostname"

# default slack channel #il101-ios
ENV["SLACK_URL"] = "[REDACTED]"	

# import shared lanes
import_from_git(url: '[REDACTED]',
               path: 'fastlane/Fastfile-ios')

# define things unique to this project
def test_on_simulator(device_type, the_hostname)
	my_hostname = the_hostname
	batch_count = 3
	
	# default to iPhone config
	devices = ["iPhone X"]
	# #il101-iphone-tests
	ENV["SLACK_URL"] = "[REDACTED]"
	slack_url = "--slack_url [REDACTED]"
		
	if device_type == "iPad"
		# #il101-ipad-tests
		ENV["SLACK_URL"] = "[REDACTED]"
		slack_url = "--slack_url [REDACTED]"		
		devices.clear()
		devices = ["iPad (6th generation)"]
		#batch_count = 2
	end
	
	# enable Slack notificaitons only when running under CI server
	if !is_ci?
		slack_url = "https://"
		ENV["SLACK_URL"] = "https://"
	end

	if is_ci?
		slack(
			message: "#{device_type} Tests started on host: #{my_hostname}",
			#default_payloads: [],
			attachment_properties: { color: "#509BD2" }
		)
	end
	
	# make sure we have a valid dev cert and profile
	begin
		match(type: "development", readonly: true)
	rescue => ex
		UI.error("#{ex} - retry match and attempt to force recreate the profile")
		match(type: "development", force: true)
	end
	
	# run the tests
	run_tests(
		devices: devices,
		#only_testing: ["InnovativeUITests/HomeScreenUITests"]
	)
	trainer(
		output_directory: "test_output",
		extension: ".junit",
		fail_build: false
	)	
	
	# gather code coverage
	begin
		xcov(
			scheme: "Innovative", 
			only_project_targets: true,
			slack_url: ENV["SLACK_URL"]
		)
	rescue => ex
		UI.error("#{ex} - xcov action failed. Trying long form command")
		sh "xcov --scheme Innovative --workspace ../Innovative.xcworkspace --output_directory ./xcov_report --only_project_targets true #{slack_url}"
	end
	
	slather(
		scheme: "Innovative",
		workspace: "Innovative.xcworkspace",
		proj: "Innovative.xcodeproj",
		cobertura_xml: "true",
		jenkins: "true",
		output_directory: "slather_output",
		ignore: "ipadTest/openssl/*"
	)
end # // test_on_simulator

platform :ios do	
	# Define lanes unique to this project
	desc "Runs ALL the iPhone tests"
	lane :"iphone-tests" do
		test_on_simulator "iPhone", my_hostname
	end # // iphonetests
	
	desc "Runs ALL the iPad tests"
	lane :"ipad-tests" do
		test_on_simulator "iPad", my_hostname
	end # // ipadtests	
	
	after_all do |lane|
		# This block is called, only if the executed lane was successful
		
		# cleanup
			
	end # // after_all
	
end # // platform ios


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# fastlane Appfile - Contains some basic app info for all fastlane actions
# Author: Jason Charrier
# Created: April 10, 2017

app_identifier "[REDACTED]" # The bundle identifier of your app
apple_id "[REDACTED]" # Your Apple email address

team_id "[REDACTED]" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-trainer | 0.4.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 2.0.1        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 1.3.0        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| cocoapods                 | 1.7.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| trainer                   | 0.8.2        |
| fastlane-plugin-trainer   | 0.4.1        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| slather                   | 2.4.7        |
| xcov                      | 1.5.0        |
</details>

*generated on:* **2019-06-03**
</details></pre>
</details>

**Comment by janpio** [comment]
Duplicate at https://github.com/fastlane/fastlane/issues/14845
