### ISSUE TITLE
Generic Error on iOS Submission

### ISSUE THREAD

**Issue by koensayr** [fastlane/fastlane#14840]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Attempting to submit an application to the iOS store returns a generic error: "Problem processing review submission"

##### Command executed

bundle exec fastlane ios deploy submit:true screenshots:false version:1.1

##### Complete output when running fastlane, including the stack trace and command used

<details>
[✔] 🚀 
[23:42:33]: You have required a gem, if this is a third party gem, please use `fastlane_require 'spaceship'` to ensure the gem is installed locally.
[23:42:33]: ------------------------------
[23:42:33]: --- Step: default_platform ---
[23:42:33]: ------------------------------
[23:42:33]: Driving the lane 'ios deploy' 🚀
[23:42:33]: ----------------------------------------------
[23:42:33]: --- Step: Switch to ios submit_review lane ---
[23:42:33]: ----------------------------------------------
[23:42:33]: Cruising over to lane 'ios submit_review' 🚖
[23:42:33]: ---------------------
[23:42:33]: --- Step: deliver ---
[23:42:33]: ---------------------
[23:42:33]: Successfully loaded '/Users/administrator/Projects/clubzz/ios/fastlane/Deliverfile' 📄

+------------------------+-------------------------------------------------------+
|                 Detected Values from './fastlane/Deliverfile'                  |
+------------------------+-------------------------------------------------------+
| submission_information | {:export_compliance_encryption_updated=>false,        |
|                        | :export_compliance_uses_encryption=>false,            |
|                        | :content_rights_contains_third_party_content=>false,  |
|                        | :add_id_info_uses_idfa=>false}                        |
| automatic_release      | false                                                 |
+------------------------+-------------------------------------------------------+

[23:42:33]: Login to App Store Connect (ios-ci@clubzz.com)
[23:42:34]: Login successful

+--------------------------------------------------------------------+------------------------+
|                                   deliver 2.125.0 Summary                                   |
+--------------------------------------------------------------------+------------------------+
| metadata_path                                                      | ./fastlane/metadata    |
| reset_ratings                                                      | false                  |
| app_version                                                        | 1.1                    |
| submit_for_review                                                  | true                   |
| automatic_release                                                  | true                   |
| force                                                              | true                   |
| skip_screenshots                                                   | true                   |
| skip_binary_upload                                                 | true                   |
| screenshots_path                                                   | ./fastlane/screenshots |
| username                                                           | ios-ci@clubzz.com      |
| app_identifier                                                     | Clubzz.io              |
| ipa                                                                | clubzz.ipa             |
| platform                                                           | ios                    |
| edit_live                                                          | false                  |
| use_live_version                                                   | false                  |
| skip_metadata                                                      | false                  |
| skip_app_version_update                                            | false                  |
| overwrite_screenshots                                              | false                  |
| reject_if_possible                                                 | false                  |
| phased_release                                                     | false                  |
| submission_information.export_compliance_encryption_updated        | false                  |
| submission_information.export_compliance_uses_encryption           | false                  |
| submission_information.content_rights_contains_third_party_content | false                  |
| submission_information.add_id_info_uses_idfa                       | false                  |
| run_precheck_before_submit                                         | true                   |
| precheck_default_rule_level                                        | warn                   |
| individual_metadata_items                                          | []                     |
| ignore_language_directory_validation                               | false                  |
| precheck_include_in_app_purchases                                  | true                   |
+--------------------------------------------------------------------+------------------------+

[23:42:35]: Making sure the latest version on App Store Connect matches '1.1' from the ipa file...
[23:42:36]: '1.1' is the latest version on App Store Connect
[23:42:37]: Loading './fastlane/metadata/en-US/description.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/keywords.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/support_url.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/name.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[23:42:37]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[23:42:37]: Loading './fastlane/metadata/copyright.txt'...
[23:42:37]: Loading './fastlane/metadata/primary_category.txt'...
[23:42:37]: Loading './fastlane/metadata/secondary_category.txt'...
[23:42:37]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[23:42:37]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[23:42:37]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[23:42:37]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/trade_name.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/first_name.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/last_name.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/address_line1.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/address_line2.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/address_line3.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/city_name.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/state.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/country.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/postal_code.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/phone_number.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/email_address.txt'...
[23:42:37]: Loading './fastlane/metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/first_name.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/last_name.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/email_address.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[23:42:37]: Loading './fastlane/metadata/review_information/notes.txt'...
[⠋] Activating language en-US... ITC.apps.devReject.message.and.link.waitingForReview.canReject
[✔] Activating language en-US... 
[⠏] Uploading metadata to App Store Connect ITC.apps.devReject.message.and.link.waitingForReview.canReject
[✔] Uploading metadata to App Store Connect 
[23:42:46]: Successfully uploaded set of metadata to App Store Connect
[23:42:46]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[23:42:46]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+-------------------+
|         Summary for precheck 2.125.0         |
+--------------------------+-------------------+
| default_rule_level       | warn              |
| include_in_app_purchases | true              |
| app_identifier           | Clubzz.io         |
| username                 | ios-ci@clubzz.com |
+--------------------------+-------------------+

[23:42:46]: Checking app for precheck rule violations
[23:42:50]: Reading in-app purchases. If you have a lot, this might take a while
[23:42:50]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[23:42:51]: Done reading in-app purchases
[23:42:51]: ✅  Passed: No negative  sentiment
[23:42:51]: ✅  Passed: No placeholder text
[23:42:51]: ✅  Passed: No mentioning  competitors
[23:42:51]: ✅  Passed: No future functionality promises
[23:42:51]: ✅  Passed: No words indicating test content
[23:42:51]: ✅  Passed: No curse words
[23:42:51]: ✅  Passed: No words indicating your IAP is free
[23:42:51]: ✅  Passed: Incorrect, or missing copyright date
[23:42:53]: ✅  Passed: No broken urls
[23:42:53]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[23:42:54]: Selecting the latest build...
[23:43:00]: Selecting build 1.1 (2019.5.24)...
ITC.apps.devReject.message.and.link.waitingForReview.canReject
[23:43:03]: Successfully selected build
[23:43:03]: Submitting the app for review...
ITC.apps.devReject.message.and.link.waitingForReview.canReject
[23:43:07]: Setting 'export_compliance_encryption_updated' to 'false'...
[23:43:07]: Setting 'export_compliance_uses_encryption' to 'false'...
[23:43:07]: Setting 'content_rights_contains_third_party_content' to 'false'...
[23:43:07]: Setting 'add_id_info_uses_idfa' to 'false'...
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| DEFAULT_PLATFORM | ios        |
| PLATFORM_NAME    | ios        |
| LANE_NAME        | ios deploy |
+------------------+------------+
[23:43:10]: Problem processing review submission.

+------+----------------------------------+-------------+
|                   fastlane summary                    |
+------+----------------------------------+-------------+
| Step | Action                           | Time (in s) |
+------+----------------------------------+-------------+
| 1    | default_platform                 | 0           |
| 2    | Switch to ios submit_review lane | 0           |
| 💥   | deliver                          | 37          |
+------+----------------------------------+-------------+

[23:43:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  does Pilot::BuildManager.distribute not support initialization of "Testflight Information"?
    https://github.com/fastlane/fastlane/issues/14600 [open] 3 💬
    13 hours ago

➡️  upload_to_testflight failed with API forbidden error, though ipa sucessfully uploaded to TestFlight
    https://github.com/fastlane/fastlane/issues/14372 [open] 28 💬
    13 hours ago

➡️  [spaceship, pilot] Getting "410 gone"
    https://github.com/fastlane/fastlane/issues/14521 [closed] 177 💬
    5 weeks ago

and 10 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Problem%20processing%20review%20submission.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
        Problem processing review submission.
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
require 'spaceship'

default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_USER"] = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
    ENV["APP_IDENTIFIER"] = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    ENV["APP_ID"] = CredentialsManager::AppfileConfig.try_fetch_value(:app_id)
  end

#Main functions
  desc "Builds IPA, generates screenshots, and uploads to app store \n fastlane deploy submit:false screenshots:true version:1.1"
  lane :deploy do |options|
    options[:skip_screenshots] = true
    if options[:submit]
      submit_review(options)
      exit
    end
    if options[:screenshots]
      screenshots
      options[:skip_screenshots] = false
    end
    build_ipa
    upload_ipa(options)
  end

  desc "Add new tester \n bundle exec fastlane add_tester email:email@invite.com first_name:John last_name:Smith"
  lane :add_tester do |options|
    sh("bundle exec fastlane run pilot add #{options[:email]} first_name:'#{options[:first_name]}' last_name:'#{options[:last_name]}' app_identifier:'#{ENV["APP_IDENTIFIER"]}'")
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
      workspace: "Clubzz.xcworkspace",
      scheme: "Clubzz",
      erase_simulator: true,
      reinstall_app: true,
      skip_open_summary: true,
      clean: true,
      clear_previous_screenshots: true
    )
  end

#Helpers
  desc "Generates a new ipa"
  lane :build_ipa do

    # Increment build number to current date
    build_number = Time.new.strftime("%Y.%m.%d")
    increment_build_number build_number: build_number

    build_ios_app(
      workspace: "Clubzz.xcworkspace",
      configuration: "Release",
      scheme: "Clubzz",
      silent: true,
      clean: true,
      output_name: "clubzz.ipa"
    )
  end

  desc "Uploads an ipa"
  lane :upload_ipa do |options|
    deliver(
      ipa: "clubzz.ipa",
      app_version: options[:version],
      force: true,
      metadata_path: "./metadata",
      screenshots_path: "./screenshots",
      skip_screenshots: options[:skip_screenshots],
      submit_for_review: false,
      automatic_release: false, #Do you want this?
      phased_release: false#Do you want this?
    )
  end

  desc "Submits app for review"
  lane :submit_review do |options|
    deliver(
      metadata_path: "./fastlane/metadata",
      reset_ratings: false,
      app_version: options[:version],
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("Clubzz.io") # The bundle identifier of your app
apple_id("ios-ci@clubzz.com") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.64.0       |
| rubyzip                   | 1.2.3        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-06-01**
</details>

**Comment by koensayr** [comment]
FWIW running the same command with a --verbose just left me with a stack trace at the end. Perhaps this is helpful too:

```
Spaceship::Tunes::Error: [!] The request could not be completed because:
	Problem processing review submission.
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1117:in `send_app_submission'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/spaceship/lib/spaceship/tunes/app_submission.rb:152:in `complete!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/deliver/lib/deliver/submit_for_review.rb:27:in `submit!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/deliver/lib/deliver/runner.rb:172:in `submit_for_review'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/deliver/lib/deliver/runner.rb:50:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:84:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:20:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

**Comment by koensayr** [comment]
Any thoughts here?

**Comment by koensayr** [comment]
This happened again this evening:

```
[22:45:37]: You can tweet: "App Store Connect #iosprocessingtime 9 minutes"
[22:46:14]: Selecting build 1.1 (2019.6.4)...
ITC.apps.devReject.message.and.link.waitingForReview.canReject
[22:46:16]: Successfully selected build
[22:46:16]: Submitting the app for review...
ITC.apps.devReject.message.and.link.waitingForReview.canReject
[22:46:21]: Setting 'export_compliance_encryption_updated' to 'false'...
[22:46:21]: Setting 'export_compliance_uses_encryption' to 'false'...
[22:46:21]: Setting 'content_rights_contains_third_party_content' to 'false'...
[22:46:21]: Setting 'add_id_info_uses_idfa' to 'false'...
+--------------------+---------------------------------------------------------+
|                                 Lane Context                                 |
+--------------------+---------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                     |
| PLATFORM_NAME      | ios                                                     |
| LANE_NAME          | ios deploy                                              |
| BUILD_NUMBER       | 2019.06.04                                              |
| IPA_OUTPUT_PATH    | /Users/administrator/Projects/clubzz/ios/clubzz.ipa     |
| DSYM_OUTPUT_PATH   | /Users/administrator/Projects/clubzz/ios/clubzz.app.dS  |
|                    | YM.zip                                                  |
| XCODEBUILD_ARCHIVE | /Users/administrator/Library/Developer/Xcode/Archives/  |
|                    | 2019-06-04/clubzz 2019-06-04 22.23.55.xcarchive         |
+--------------------+---------------------------------------------------------+
[22:46:24]: Problem processing review submission.
```

**Comment by getaaron** [comment]
Does the `ios-ci@clubzz.com` have App Manager permissions? They might only have Developer permissions.

**Comment by trumpet2012** [comment]
I'm running into this problem as well. I did verify that the user I'm using is an App Manager.

**Comment by janpio** [comment]
> FWIW running the same command with a --verbose just left me with a stack trace at the end. Perhaps this is helpful too:
> ```
> Spaceship::Tunes::Error: [!] The request could not be completed because:
>	Problem processing review submission.
>  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response'
> ```

It is indeed, it tells us that this is an error message directly from the API. Can you please use https://docs.fastlane.tools/actions/spaceship_logs/ to get the request to and response from Apple and post it here for us to look at?

**Comment by koensayr** [comment]
> Does the `ios-ci@clubzz.com` user have App Manager permissions? They might only have Developer permissions.

I have double checked and indeed the user in question does have (both) App Manager and Developer Permissions

**Comment by koensayr** [comment]
Working on getting the Spaceship logs as requested by @janpio

**Comment by gmatkovitch** [comment]
Hey guys, any progress with this issue?
I encountered the same message yesterday...
Thanks!

**Comment by janpio** [comment]
@gmatkovitch You can help out as well: https://github.com/fastlane/fastlane/issues/14840#issuecomment-502762621

**Comment by koensayr** [comment]
I haven't actually been able to reproduce this. Perhaps this was a problem withe iTunes API at the time. If I run into this again, I'll reopen this
