### ISSUE TITLE
Can Fastlane's action support responding executed concurrently?

### ISSUE THREAD

**Issue by sigelion** [fastlane/fastlane#14855]
#### If you consider these two actions as a single task, does Fastlane support responding to 100 tasks simultaneously on a single computer?

**Comment by janpio** [comment]
Fastlane generally is not written to be executed in parallel, but both these actions are probably save as there is no local state or really complicated logic. But as they use APIs from Apple that are not meant to be used in parallel either, you might hit problems there - they have rate limiting and throttling in place that might be triggered by to many parallel requests.

Only reason to find out and to be sure is to try though.

**Comment by sigelion** [comment]
> Fastlane generally is not written to be executed in parallel, but both these actions are probably save as there is no local state or really complicated logic. But as they use APIs from Apple that are not meant to be used in parallel either, you might hit problems there - they have rate limiting and throttling in place that might be triggered by to many parallel requests.
> 
> Only reason to find out and to be sure is to try though.
> 
> If you have a specific use case, it might be worth posting about it so we can check if there is a better way to do things (or if we could change something to better support that use case).

Now we want to provide an automated re-signing service. The idea is to get the user's UDID, add it to an Apple account via Fastlane's action register_device(), then download the latest .mobileprovision file via the action get_provisioning_profile(), and finally complete the automated re-signature . The problem is that if you want to provide 7*24 hours of service, the problem of high concurrency needs to be solved. Do you have any good suggestions?

**Comment by janpio** [comment]
Not really - but if it's normal usage that a normal developer team could have, you should be fine.

But a word of caution: Depending on if this is planned to be a public (paid) service, this might very well be against Apple's (Developer) TOS and put your Apple Developer account in danger. Fastlane generally should not be used for such things.

**Comment by sigelion** [comment]
> Not really - but if it's normal usage that a normal developer team could have, you should be fine.
> 
> But a word of caution: Depending on if this is planned to be a public (paid) service, this might very well be against Apple's (Developer) TOS and put your Apple Developer account in danger. Fastlane generally should not be used for such things.

I see, Thank you.

**Comment by sigelion** [comment]
> Not really - but if it's normal usage that a normal developer team could have, you should be fine.
> 
> But a word of caution: Depending on if this is planned to be a public (paid) service, this might very well be against Apple's (Developer) TOS and put your Apple Developer account in danger. Fastlane generally should not be used for such things.

Have you encountered a problem with remote push failure after re-signing?
