### ISSUE TITLE
Running `fastlane pilot builds` results in "undefined method `map' for nil:NilClass"

### ISSUE THREAD

**Issue by dalemyers** [fastlane/fastlane#14856]
Regression:

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running the following command generates an error: `fastlane pilot builds --username "email@example.com" --app_identifier "com.example.myapp" --verbose`

This command started failing for us some point between Friday and about 12 hours ago. 

We are seeing this on multiple machines.

##### Command executed
`fastlane pilot builds --username "email@example.com" --app_identifier "com.example.myapp" --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀
INFO [2019-06-04 08:50:34.48]: Login to App Store Connect ([snipped])
Reading keychain entry, because either user or password were empty
Loading session from '/Users/dalemy/.fastlane/spaceship/[snipped]/cookie'
Looking for App Store Connect Team with ID 80423
INFO [2019-06-04 08:50:37.01]: Login successful
DEBUG [2019-06-04 08:50:37.01]: App identifier ([snipped])

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `map' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60map%27%20for%20nil+repo:fastlane/fastlane
➡️  Rate limit has been exceeded for: testflight|default|APPLE_CONNECT
    https://github.com/fastlane/fastlane/issues/12845 [open] 62 💬
    2 days ago

➡️  Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13877 [closed] 3 💬
    20 Mar 2019

➡️  Rate limit has been exceeded for: itunes-connect|nonauth_url_spamControl|<my_ip_address>
    https://github.com/fastlane/fastlane/issues/14070 [closed] 19 💬
    6 weeks ago

and 75 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60map%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
NoMethodError: [!] undefined method `map' for nil:NilClass
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/pilot/lib/pilot/build_manager.rb:160:in `block in list'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/pilot/lib/pilot/build_manager.rb:156:in `map'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/pilot/lib/pilot/build_manager.rb:156:in `list'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/pilot/lib/pilot/commands_generator.rb:90:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/pilot/lib/pilot/commands_generator.rb:166:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/pilot/lib/pilot/commands_generator.rb:18:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<top (required)>'
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.14.4                                            |
| Ruby                        | 2.6.3                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.21.0                                 |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib                   |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_10.2.1.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.1        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.6.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| cocoapods                 | 1.6.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcpretty-json-formatter   | 0.1.1        |
</details>

*generated on:* **2019-06-04**
</details>

**Comment by joshdholtz** [comment]
@dalemyers Could you do me a favor and try this again? I was able to replicate this earlier this morning but it looks like the API response that was causing this is now "fixed" for me 😬 Does this work for you know with the _fastlane_ version that you already have installed?

**Comment by dalemyers** [comment]
I'm still seeing the same issue.

**Comment by dalemyers** [comment]
@joshdholtz Any update on this?

**Comment by aperomingo** [comment]
I'm getting this error with `v2.125.2`

It was strange because my app is submit on Testflight but i get this error...

**Comment by dalemyers** [comment]
@joshdholtz This continues to be an issue for us. Any update would be appreciated. 😊

**Comment by dalemyers** [comment]
Still seeing this. We are having to do all of our releases manually for the time being.

**Comment by rikur** [comment]
+1

**Comment by atom-wintermute** [comment]
+1

**Comment by Goles** [comment]
+1

**Comment by fssilva** [comment]
+1

**Comment by fruitcoder** [comment]
+1

**Comment by dalemyers** [comment]
This has actually gotten worse for us today. Previously it was only `pilot builds` that was failing, but now `pilot upload` is failing with the same issue.

**Comment by adamirowe** [comment]
Just got this as well (was not yesterday).
