### ISSUE TITLE
languageMappingReadable.json missing new languages

### ISSUE THREAD

**Issue by max-ott** [fastlane/fastlane#14865]
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/assets/languageMappingReadable.json is missing new languages.

Question: Is this file still used?
- Wasn't used for https://github.com/fastlane/fastlane/commit/19779dbd4131f9bad5efddd9dd90ba92f178fa11#diff-29181cf79f59dd2b2d2a231de3389c8f
- Wasn't used for https://github.com/fastlane/fastlane/pull/14864

**Comment by janpio** [comment]
Quick investigation:

Only used in https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/spaceship/lib/spaceship/tunes/language_converter.rb

Which is only used by `produce` in https://github.com/fastlane/fastlane/blob/e617959beacb526332ad88cf20831f3a71374e81/produce/lib/produce/itunes_connect.rb#L76-L90

Theses lines have not been touched for very long, same for the `languageMappingReadable.json` - so very possible that the API is cleaner today and is not actually used.

---

If you want, you can modify your local copy to not use the LanguageConverter any more and see if anything breaks. (As this only creates problems when the API is actually used, this probably won't be caught by the tests :/ )
