### ISSUE TITLE
Spaceship::Tunes cannot find iOS app by bundle id

### ISSUE THREAD

**Issue by jmei08** [fastlane/fastlane#14866]
fastlane_require 'spaceship'
    Spaceship::Tunes.login("xxx")
    app = Spaceship::Tunes::Application.find("xx.xx.xx")
    puts app

It returns nothing.

**Comment by max-ott** [comment]
Hi there, could you please post your whole fastfile and environment? I'm not sure where you are using those commands. They will not work in `irb`, because they are not correct. 

```
irb
require "spaceship"
Spaceship::Tunes.login("email", "password")
app = Spaceship::Tunes::Application.find("123456789") // can also use bundle ID Here
=> You should directly get some info as response
```

**Comment by jmei08** [comment]
There are two apps in different team using the same account. 

fastlane_require 'spaceship'
Spaceship::Tunes.login("xxx")
app = Spaceship::Tunes::Application.find("com.xx.A")  // in team A
puts app  ==> it outputs the app info
app = Spaceship::Tunes::Application.find("com.xx.B") // in team B
puts app ==>  it outputs nothing


ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
fastlane 2.125.2

**Comment by max-ott** [comment]
You’ll need to switch teams before you can access app b: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#login
