### ISSUE TITLE
[Homebrew] Catalina Fastlane Ruby Error

### ISSUE THREAD

**Issue by kelvinlauKL** [fastlane/fastlane#14860]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Attempting to install fastlane on a brand new machine on Catalina leads to an error prompt stating:

<img width="532" alt="Screen Shot 2019-06-05 at 12 56 51 am" src="https://user-images.githubusercontent.com/11384608/58931320-4ad10080-872d-11e9-9f62-7a9039996aac.png">

Terminal Output:

<img width="682" alt="Screen Shot 2019-06-05 at 1 01 24 am" src="https://user-images.githubusercontent.com/11384608/58931440-b3b87880-872d-11e9-809b-546f0171eea1.png">

##### Command executed

```
fastlane

sudo fastlane
```

##### Complete output when running fastlane, including the stack trace and command used

N / A

### Environment

N / A

**Comment by max-ott** [comment]
@kelvinlauKL What happens if you open System Preferences > Security & Privacy ? 

There you can accept and "untrusted" scripts. `sudo` won't help here.

**Comment by kelvinlauKL** [comment]
Solved!

<img width="780" alt="Screen Shot 2019-06-05 at 7 36 58 pm" src="https://user-images.githubusercontent.com/11384608/58997176-5f62d680-87c9-11e9-8b6a-e324780254bc.png">
