### ISSUE TITLE
Deliver: Invalid request when selecting build

### ISSUE THREAD

**Issue by HaeSeongPark** [fastlane/fastlane#14863]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The upload_to_app_store could not be completed because Invalid request when selecting build. 
The build is available at ITC but it cannot be selected because of invalid request. I searched a lot but couldn't solve this. Anyone else knowing this issue?

##### Command executed

fastlane release --verbose
<details>
  <pre>
default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number
    build_app(workspace: "MY_WORKSAPCE", scheme: "MY_SCHEME")
    upload_to_app_store(
	skip_metadata: true,
        force:true,
	skip_screenshots: true,
	submit_for_review: true,
	automatic_release: false,
	skip_binary_upload:false,
	submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: false,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
   )
  end
end

 </pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
INFO [2019-06-06 17:59:30.90]: Selecting build 1.2 (8)...
Potential server error received: 'invalid_request'. Retrying after 10 seconds (remaining: 2)...
Potential server error received: 'invalid_request'. Retrying after 10 seconds (remaining: 1)...
WARN [2019-06-06 17:59:55.37]: Lane Context:
INFO [2019-06-06 17:59:55.37]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release", :BUILD_NUMBER=>"8", :IPA_OUTPUT_PATH=>"/Users/rhinoq/Desktop/develop/BowsCount108/BowsCount108.ipa", :DSYM_OUTPUT_PATH=>"/Users/rhinoq/Desktop/develop/BowsCount108/BowsCount108.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/rhinoq/Library/Developer/Xcode/Archives/2019-06-06/BowsCount108 2019-06-06 17.15.16.xcarchive"}
ERROR [2019-06-06 17:59:55.37]: invalid_request
----
/Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/tunes/tunes_client.rb:228:in `handle_itc_response': invalid_request (Spaceship::Tunes::PotentialServerError)
	37: from /Users/rhinoq/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	36: from /Users/rhinoq/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	35: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/bin/fastlane:23:in `<main>'
	34: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/bin/fastlane:23:in `load'
	33: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
	32: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	31: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	30: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	29: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	28: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	27: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	26: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	25: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	24: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	23: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	21: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:23:in `block (2 levels) in parsing_binding'
	16: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	15: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	13: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	12: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	11: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	10: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 9: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
	 8: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/deliver/lib/deliver/runner.rb:50:in `run'
	 7: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/deliver/lib/deliver/runner.rb:172:in `submit_for_review'
	 6: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
	 5: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/deliver/lib/deliver/submit_for_review.rb:50:in `select_build'
	 4: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/tunes/app_version.rb:403:in `save!'
	 3: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/tunes/tunes_client.rb:438:in `update_app_version!'
	 2: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/tunes/tunes_client.rb:1466:in `with_tunes_retry'
	 1: from /Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/tunes/tunes_client.rb:445:in `block in update_app_version!'
/Users/rhinoq/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/tunes/tunes_client.rb:228:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::Tunes::PotentialServerError)
	invalid_request

 </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.0/bin/fastlane       |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number
    build_app(workspace: "BowsCount108.xcworkspace", scheme: "BowsCount108")
    upload_to_app_store(
	skip_metadata: true,
        force:true,
	skip_screenshots: true,
	submit_for_review: true,
	automatic_release: false,
	skip_binary_upload:false,
	submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: false,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
   )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.rhino.108BowsCounter") # The bundle identifier of your app
apple_id("cord7894@gmail.com") # Your Apple email address

itc_team_id("119514566") # App Store Connect Team ID
team_id("Q7MBG3B536") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.0.1        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-06-06**
</details>
 </pre>
</details>

**Comment by HaeSeongPark** [comment]
Downgrading ruby version 2.6.0 to 2.5.3 solved this problem

**Comment by zintus** [comment]
Downgrading to 2.5.5 worked well too.
