### ISSUE TITLE
XCUITest with React Native - Lagging + Won't write actions into test

### ISSUE THREAD

**Issue by bernhardt1** [fastlane/fastlane#14862]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Snapshot with React Native

no

#### Question Description

I followed the guides and successfully set up XCUITest to work with snapshot. I was able to capture screenshots of my onboarding screen using snapshot. These rendered nicely into the HTML file as expected.

However, I began running into serious issues as I tried to automate screenshots throughout  my app:
Navigation tabs issues: https://github.com/react-navigation/tabs/issues/52     tabBarTestID to fix
Accessibility on touchables: https://medium.com/@csovis/writing-ui-test-in-ios-with-xcuitest-in-objective-c-for-react-native-c622dcfed0c2		accessible={Platform.OS == ‘ios’ ? false : true} to fix
many crashes when trying to record the UI test.
my actions were not written to the test when I tried to record them.

I followed many issues to try to get CXUITest to behave with snapshot. After ~1 day there continues to be issue after issue to get the screenshots automated.

I'm wondering if others ran into this? I could see this behavior being fine for a test app, but with a larger codebase, it became a huge hurdle to get this system set up. Is there a better to set up snapshot? Is there something I can change within my xcode environment or react native project to make XCUITest behave more smoothly?

**Comment by janpio** [comment]
>  my actions were not written to the test when I tried to record them.

What does that mean? I don't understand.

In general, your question sounds more like "How do I use XCUITest with my React Native app?", correct? Or is there something fastlane/snapshot specific that is not working as expected?
