### ISSUE TITLE
Update certificates near to expiration date

### ISSUE THREAD

**Issue by cianiandreadev** [fastlane/fastlane#14870]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Action: Spaceship/Match ??

CI Automation to renew certificates that are close to an expiration date.

#### Question Description

In our team we have to often deliver updates for our apps and can happen that the CI publish apps that are really close to the expiration date of the Provisioning and Distribution certificates.

I would like to schedule a task that automatically check the expiration date of the certificates and automatically renew them.

Is there a way to have this?

**Comment by max-ott** [comment]
Hi and welcome to `fastlane`. If you want to schedule tasks, you might want to look into using `sidekiq` or a similar to tool wrap around `fastlane`. (Or probably `spaceship` to loose the overhead)

**Comment by cianiandreadev** [comment]
Thanks @max-ott. The problem is not about scheduling the task itself, rather then how to get the certificates and check their expiring date and see if it is within (i.e.,) 20 days.

I checked that currently `spaceship` is able to get the certificates, but I don't know how to do the rest.

**Comment by max-ott** [comment]
There is no out of the box solution available. You would need to check for the certificates, validity etc. Should all be possible with `spaceship`. https://stackoverflow.com/questions/39150389/command-line-way-to-test-ios-mobile-provisioning-profile-is-still-valid provides some hints and https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md gives an overview what you can do on the developer portal.

**Comment by cianiandreadev** [comment]
Thanks for the help. I will start from that!

**Comment by janpio** [comment]
Let us know if you make any progress here @cianiandreadev - I am sure other developers would benefit from having some examples how to solve something like this.

**Comment by cianiandreadev** [comment]
I'm facing a big issue right now. I can't find the provisioning certificates (using Spaceship) that are automatically generated by Xcode.

Is that a Spaceship issue or a AppstoreConnect API limitation?
