### ISSUE TITLE
[Spaceship] Support cross-platform certificates

### ISSUE THREAD

**Issue by barakwei** [fastlane/fastlane#14878]
#### Motivation Behind Feature
As part of the recent changes to the Apple ecosystem, a new kind of certificate was introduced. While the existing certificates are `iOS Development` and `Mac Development`, the new one is just `Development` and is probably to help users create iPad apps for macOS. These certificates can be added to a provisioning profile. See screenshot from the developer portal.
![image](https://user-images.githubusercontent.com/5232161/59232218-363cae80-8bec-11e9-8531-47b32ce65b22.png)

#### Feature Description
So `Spaceship::Portal.certificate.all` right now returns only `iOS development` certificates. It should now return the new certificates in addition to the iOS certificates. The same goes for `Spaceship::Portal.certificate.all(mac: True`, although we should probably not be using a boolean flag here.

#### Alternatives or Workarounds
Unknown.

**Comment by janpio** [comment]
Anyone who wants to take a shot at this: Find out if the old API being used here also returns these new types of certificates: https://github.com/fastlane/fastlane/blob/11257afda89b4f4447d76279d6ec263f0f2f9af6/spaceship/lib/spaceship/portal/portal_client.rb#L564-L575 

If so, this shouldn't be too hard to add.
If not, we will have to wait until the new API has been implemented in spaceship.

**Comment by barakwei** [comment]
Regardless of the new API or not, I purposed that these certs will be returned always, regardless of the `mac` parameters. Does this sound good?

**Comment by janpio** [comment]
Sounds good, yes.

![image](https://user-images.githubusercontent.com/183673/59265318-6a908900-8c45-11e9-9a51-c9574341f61f.png)

We _might_ need to guard these for environments running Xcode 11 though. Should be tested if they also work with current versions of Xcode 10.

**Comment by barakwei** [comment]
Spaceship doesn't have a notion of Xcode version, so I'm not sure what can be done here.

Regarding implementation, the endpoint is `account/#{platform_slug(mac)}/certificate/listCertRequests.action` so it's actually dependent on the platform. Another endpoint needed for these new certificates.

**Comment by janpio** [comment]
Ok, then this is definitely a child of https://github.com/fastlane/fastlane/issues/14881

**Comment by janpio** [comment]
@joshdholtz implemented parts of the new API, including certificate creation. Turns out the new official Connect API does not support these new cross-platform certificates yet :/ See here for my comment on his PR and some investigation into the matter: https://github.com/fastlane/fastlane/pull/14888#discussion_r293452245

**Comment by barakwei** [comment]
From what I can see, the 2 new certificate types exist. Maybe they're not documented but a certificate with type `DEVELOPMENT` exists. It's worth to add them.
Also, it's a bit unrelated, but the new AppStoreConnect API may be missing connections between provisioning profiles and certificates/devices.

**Comment by barakwei** [comment]
resolved by #15130
