### ISSUE TITLE
Error "undefined method `[]' for nil:NilClass" when trying to use command "fastlane frameit"

### ISSUE THREAD

**Issue by lucashoeft** [fastlane/fastlane#14876]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to generate framed screenshots with background and title for my existing screenshots. Creating screenshots works and also to simply frame them (if Framefile.json is empty).

##### Command executed
<pre>fastlane frameit</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[⠧] Framing screenshot './screenshots/en-US/iPhone Xs Max-05-Settings.png' [14:52:20]: undefined method `[]' for nil:NilClass.</pre>
(Removed sensitive output)
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.9.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.5       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.10.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-06-10**
</details>

<details>
  <pre>
[⠧] Framing screenshot './screenshots/en-US/iPhone Xs Max-05-Settings.png' [14:52:20]: undefined method `[]' for nil:NilClass
</pre>

Framefile.json
<pre>
{
  "default": {
  	"title": {
  		"color" : "#545454"
  	},
    "background": "./background.jpg",
    "padding": 50
  },
  "data": [
  	{
  		"filter": "iPhone Xs Max-05-Settings",
  		"keywords": {
  			"color": "#545454"
  		}
  	}
  ]
}
</pre>

keyword.strings
<pre>
"iPhone Xs Max-05-Settings" = "Settings";
</pre>

title.strings
<pre>
"iPhone Xs Max-05-Settings" = "Settings";
</pre>
</details>

**Comment by janpio** [comment]
Can you post more of the output you are getting? There should be a stacktrace that points us to a line in a specific file, so we can understand what is going on here.

**Comment by lucashoeft** [comment]
Output after running `bundle exec fastlane frameit`:

[✔] 🚀 
[15:59:14]: Using device frames version 'latest'
[15:59:14]: Skipping framing of screenshot ./en-US/iPhone 8 Plus-05-Settings.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (3rd generation)-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (3rd generation)-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (3rd generation)-05-Settings.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPhone 8 Plus-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (2nd generation)-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (3rd generation)-02-MultipleChoice.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPhone 8 Plus-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPhone 8 Plus-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPhone Xs Max-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (2nd generation)-05-Settings.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPhone Xs Max-02-MultipleChoice.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (3rd generation)-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (2nd generation)-02-MultipleChoice.png.  No title provided in your Framefile.json or title.strings.
[15:59:14]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (2nd generation)-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
[⠏] Framing screenshot './en-US/iPhone Xs Max-05-Settings.png' [15:59:18]: undefined method `[]' for nil:NilClass
[15:59:18]: Skipping framing of screenshot ./en-US/iPhone Xs Max-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
[15:59:18]: Skipping framing of screenshot ./en-US/iPad Pro (12.9-inch) (2nd generation)-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
[15:59:18]: Skipping framing of screenshot ./en-US/iPhone Xs Max-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.

**Comment by janpio** [comment]
Ugh, no useful output. Can you try the same command with `--verbose` added at the end please?

**Comment by lucashoeft** [comment]
Sure, here is the output: 

```
[✔] 🚀 
DEBUG [2019-06-19 22:34:56.25]: Parsing config file './screenshots/Framefile.json'
INFO [2019-06-19 22:34:56.25]: Using device frames version 'latest'
DEBUG [2019-06-19 22:34:56.25]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.27]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.27]: Skipping framing of screenshot ./screenshots/en-US/iPhone 8 Plus-05-Settings.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.27]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.29]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.29]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.29]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.31]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.31]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.31]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.32]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.32]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-05-Settings.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.32]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.34]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.34]: Skipping framing of screenshot ./screenshots/en-US/iPhone 8 Plus-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.34]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.36]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.36]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (2nd generation)-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.36]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.38]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.38]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-02-MultipleChoice.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.38]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.39]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.39]: Skipping framing of screenshot ./screenshots/en-US/iPhone 8 Plus-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.39]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.41]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.41]: Skipping framing of screenshot ./screenshots/en-US/iPhone 8 Plus-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.41]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.42]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.42]: Skipping framing of screenshot ./screenshots/en-US/iPhone Xs Max-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.42]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.44]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.44]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (2nd generation)-05-Settings.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.44]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.46]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.46]: Skipping framing of screenshot ./screenshots/en-US/iPhone Xs Max-02-MultipleChoice.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.46]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.47]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.47]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.47]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.49]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.49]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (2nd generation)-02-MultipleChoice.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.49]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:34:56.51]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:34:56.51]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (2nd generation)-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:34:56.51]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
[⠋] Framing screenshot './screenshots/en-US/iPhone Xs Max-05-Settings.png' DEBUG [2019-06-19 22:34:56.54]: Looking for Apple iPhone XS Max Space Gray and found 1 template(s)
[⠹] Framing screenshot './screenshots/en-US/iPhone Xs Max-05-Settings.png' ERROR [2019-06-19 22:35:00.86]: undefined method `[]' for nil:NilClass
ERROR [2019-06-19 22:35:00.86]: Backtrace:
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:539:in `font'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:412:in `block in build_text_images'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:402:in `each'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:402:in `build_text_images'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:324:in `put_title_into_background'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:161:in `complex_framing'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/editor.rb:41:in `frame!'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/runner.rb:42:in `block in run'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/runner.rb:28:in `each'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/runner.rb:28:in `run'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/commands_generator.rb:43:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/commands_generator.rb:103:in `run'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/frameit/lib/frameit/commands_generator.rb:19:in `start'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
	/usr/local/bin/fastlane:22:in `load'
	/usr/local/bin/fastlane:22:in `<top (required)>'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
	/usr/local/bin/bundle:22:in `load'
	/usr/local/bin/bundle:22:in `<main>'
DEBUG [2019-06-19 22:35:00.86]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:35:00.88]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:35:00.88]: Skipping framing of screenshot ./screenshots/en-US/iPhone Xs Max-03-DeckView.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:35:00.88]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:35:00.89]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:35:00.89]: Skipping framing of screenshot ./screenshots/en-US/iPad Pro (12.9-inch) (2nd generation)-01-HomeScreen.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-06-19 22:35:00.90]: Parsing config file '/Users/lucas/Documents/Development/Xcode/multiplechoice/fastlane/screenshots/Framefile.json'
DEBUG [2019-06-19 22:35:00.91]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-06-19 22:35:00.91]: Skipping framing of screenshot ./screenshots/en-US/iPhone Xs Max-04-PractiseView.png.  No title provided in your Framefile.json or title.strings.
```

**Comment by lucashoeft** [comment]
The issue was that I didn't add any font to my Framefile and my folder
