### ISSUE TITLE
The pod_push action is failing with "Could not find a `ios` simulator" error

### ISSUE THREAD

**Issue by bonebox** [fastlane/fastlane#14883]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The `pod_push` action began failing with a "Could not find a `ios` simulator error" after updating to Xcode 10.2.1 and the latest Fastlane. It fails with the same error from both a Fastfile and command line, and was working prior to the upgrades. I confirmed the iOS simulators are installed and visible to Xcode, per the error. Also, running the `pod push` command directly outside of Fastlane works as expected.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Allogy-Mac-Build-Server:com.allogy.Rucksack ios$ fastlane run pod_push path:Rucksack.podspec repo:allogy
[22:01:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[22:01:46]: ----------------------
[22:01:46]: --- Step: pod_push ---
[22:01:46]: ----------------------
[22:01:46]: $ pod repo push allogy 'Rucksack.podspec'
[22:01:48]: ▸ Validating spec
[22:02:06]: ▸  -> Rucksack (0.8.3)
[22:02:06]: ▸ - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.
[22:02:06]: ▸ [!] The `Rucksack.podspec` specification does not validate.

Looking for related GitHub issues on fastlane/fastlane...

/Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'pod repo push allogy 'Rucksack.podspec'' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

Validating spec
 -> Rucksack (0.8.3)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

[!] The `Rucksack.podspec` specification does not validate.

	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/pod_push.rb:50:in `run'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/ios/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
	from /Users/ios/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/ios/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.45.0"

default_platform :ios

platform :ios do

  before_all do

    ENV["SLACK_URL"] = REDACTED

    setup_jenkins 

  end

  desc "Runs all the tests"

  lane :test do

    scan

  end

  desc "Build the framework and update/push podspec with a _patch_ version level."

  lane :podspec_patch do

    # Build normally first to ensure it succeeds before incrementing the version.
    gym(
	scheme: "Rucksack", 
        skip_package_ipa: true
    ) 

    increment_version_number
    increment_build_number
    commit_version_bump(
	force: true
    )
    push_to_git_remote

    version_number = get_version_number
    build_number = get_build_number

    add_git_tag(
	tag: "#{version_number}"
    )
    push_git_tags

    version_bump_podspec(
	path: "Rucksack.podspec",
	version_number: "#{version_number}"
    )

    pod_push(
       path: "Rucksack.podspec",
       repo: "allogy",
       allow_warnings: true
    )

    sh "echo APP_VERSION_NUMBER=#{version_number} > version.properties"

  end

  desc "Build the framework and update/push podspec with a _minor_ version level."

  lane :podspec_minor do

    # Build normally first to ensure it succeeds before incrementing the version.
    gym(
	scheme: "Rucksack", 
        skip_package_ipa: true
    ) 

    increment_version_number(
	bump_type: 'minor'
    ) 
    increment_build_number
    commit_version_bump(
	force: true
    )
    push_to_git_remote

    version_number = get_version_number
    build_number = get_build_number

    add_git_tag(
	tag: "#{version_number}"
    )
    push_git_tags

    version_bump_podspec(
	path: "Rucksack.podspec",
	version_number: "#{version_number}"
    )

    pod_push(
       path: "Rucksack.podspec",
       repo: "allogy",
       allow_warnings: true
    )

    sh "echo APP_VERSION_NUMBER=#{version_number} > version.properties"

  end

  desc "Build the framework and update/push podspec with a _major_ version level."

  lane :podspec_major do

    # Build normally first to ensure it succeeds before incrementing the version.
    gym(
	scheme: "Rucksack", 
        skip_package_ipa: true
    ) 

    increment_version_number(
	bump_type: 'major'
    ) 
    increment_build_number
    commit_version_bump(
	force: true
    )
    push_to_git_remote

    version_number = get_version_number
    build_number = get_build_number

    add_git_tag(
	tag: "#{version_number}"
    )
    push_git_tags

    version_bump_podspec(
	path: "Rucksack.podspec",
	version_number: "#{version_number}"
    )

    pod_push(
       path: "Rucksack.podspec",
       repo: "allogy",
       allow_warnings: true
    )

    sh "echo APP_VERSION_NUMBER=#{version_number} > version.properties"

  end

  lane :build_universal do

    sh "cd .. && ./build.sh ios-dynamic"

  end

  lane :podspec_universal do

    version_number = get_version_number
    build_number = get_build_number

    version_bump_podspec(
	path: "Rucksack-framework.podspec",
	version_number: "#{version_number}"
    )

    pod_push(
       path: "Rucksack-framework.podspec",
       repo: "allogy-precompiled",
       allow_warnings: true
    )

    slack_message = "Successfully released [Rucksack framework v#{version_number} (#{build_number})] :rocket:"
    slack(
        message: slack_message
    )

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

#    version_number = get_version_number
#    build_number = get_build_number

#    slack_message = "Successfully released [Rucksack framework v#{version_number} (#{build_number})] :rocket:"
#    slack(
#        message: slack_message
#    )

  end

  error do |lane, exception|

     slack_message = "Failure releasing Rucksack framework: #{exception.message}"
     slack(
       message: slack_message,
       success: false
     )
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-06-11**
</details> </pre>
</details>

**Comment by bonebox** [comment]
It appears the issue is with the version of Cocoapods that Fastlane is using. I was able to get around this by using a Gemfile with the following:

```
source "https://rubygems.org"
gem 'fastlane'
gem 'cocoapods', '1.7.1'
```

**Comment by janpio** [comment]
Uhh, I feel pretty dumb right now but I couldn't really find where fastlane _currently_ defines the version of cocoapods that should be used. Can you help?
