### ISSUE TITLE
[Spaceship] `fetch_program_license_agreement_messages` is working based on team ID ?

### ISSUE THREAD

**Issue by akkhilns** [fastlane/fastlane#14880]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In my Apple account, more than one team id is used as invited by others. I want to check the account who is not accepted the license agreement. I am using `Spaceship::Portal.client.fetch_program_license_agreement_messages` to know the license agreement is accepted or not. My question is `fetch_program_license_agreement_messages` is running based on the team ID? if any account accepts the license agreement will it affect others

**Comment by janpio** [comment]
@max-ott Can you help out here maybe?

**Comment by max-ott** [comment]
Hi @akkhilns If your Apple ID is part of more teams, you will need to run `Spaceship::Portal.select_team` to select the right team. (It will display all teams and you can then choose one by number) As the agreements are on a per team level, there is no influence from one team to another.

As far as I know only the account holder can accept the license agreement and you can't be the account holder for multiple teams. So this method only allows you to check if the account holder has to accept it.

**Comment by salmanasiddiqui** [comment]
@max-ott I tested, it is not working as you explained.

After selecting a team with pending license agreement:
```
Spaceship::Portal.client.fetch_program_license_agreement_messages
=> ["Your membership has expired, and your apps have been removed from the App Store until you renew your membership. To renew, a user with the Account Holder role must <a href='http://developer.apple.com/membercenter/index.action' target='_blank'>sign in</a> and renew the membership on the Apple Developer website. <a href='https://developer.apple.com/support/renewal/' target='_blank'>Learn More</a>."]
```

Selecting team with no pending agreement/contracts:
```
Spaceship::Portal.client.fetch_program_license_agreement_messages
=> ["Your membership has expired, and your apps have been removed from the App Store until you renew your membership. To renew, a user with the Account Holder role must <a href='http://developer.apple.com/membercenter/index.action' target='_blank'>sign in</a> and renew the membership on the Apple Developer website. <a href='https://developer.apple.com/support/renewal/' target='_blank'>Learn More</a>."]
```

I can confirm from the code that it doesn't pass `team_id` in the request:
```
    # Get contract messages from App Store Connect's "olympus" endpoint
    def fetch_program_license_agreement_messages
      all_messages = []

      messages_request = request(:get, "https://appstoreconnect.apple.com/olympus/v1/contractMessages")
      body = messages_request.body
      if body
        body = JSON.parse(body) if body.kind_of?(String)
        body.map do |messages|
          all_messages.push(messages["message"])
        end
      end

      return all_messages
    end
```

**Comment by max-ott** [comment]
Please try with active accounts. This message probably blocks any acceptance of agreements.

**Comment by salmanasiddiqui** [comment]
can you please clarify what you mean by active accounts? do you mean team with active membership?

my account is part of 200 teams, I have tried changing team_id to teams with expired membership, to teams with pending license agreement, to teams with everything up-to-date; getting same response

**Comment by max-ott** [comment]
@salmanasiddiqui Please post the full code you used here to reproduce as well as link the one you “found” and think it does not choose the team. For most calls the team id is set in the cookie, so it won’t be “visible” in the actual call.

**Comment by salmanasiddiqui** [comment]
```
bundle console
require 'spaceship'
Spaceship.login
Spaceship.select_team(team_id: team_id)
Spaceship::Portal.client.fetch_program_license_agreement_messages

Spaceship.select_team(team_id: team_id_2)
Spaceship::Portal.client.fetch_program_license_agreement_messages
```

same output on both, but one team has no issues while other has pending agreement

**Comment by max-ott** [comment]
@salmanasiddiqui the code you posted is incorrect and mixing up different things. `select_team` is requiring either `Tunes` for App Store Connect or `Portal` for Apple Developer Portal. I assume that you are not actually changing teams and therefore getting the same response. 

```
bundle exec irb
require "spaceship"
Spaceship::Tunes.login("apple@apple.id", "password")
Spaceship::Tunes.select_team
1) "Acme Crop" (123)
2) "Random Inc" (321)
1
=> "123"
Spaceship::Tunes.client.fetch_program_license_agreement_messages
=> ["<b>The updated Apple Developer Program License Agreement needs to be reviewed.</b><br />In order to update your existing apps and submit new apps to the App Store, the user with the Legal role (Team Agent) must review and accept the updated agreement in their <a href=\"http://developer.apple.com/membercenter/index.action\">account on the developer website</a>.<br />"
>> Spaceship::Tunes.select_team
1) "Acme Crop" (123)
2) "Random Inc" (321)
2
=> "321"
Spaceship::Tunes.client.fetch_program_license_agreement_messages
=> []
```

Should be possible to do the same with `Spaceship::Portal`, but you must make sure that you are using it all the time and not mixing up with `Tunes`.

**Comment by salmanasiddiqui** [comment]
hmm.. well I even tried:
```
bundle console
require 'spaceship'
Spaceship.login
Spaceship::Portal.client.team_id = team_id
Spaceship::Portal.client.fetch_program_license_agreement_messages

Spaceship::Portal.client.team_id = team_id_2
Spaceship::Portal.client.fetch_program_license_agreement_messages
```
But as you can guess that doesn't work too.
The code you shared above is working. I guess my source of confusion was the fact that this function exists in base client but actually only works for appstoreconnect not developer portal.

**Comment by max-ott** [comment]
Great, can you close the issue as it's now resolved?

**Comment by salmanasiddiqui** [comment]
im not the one who created this issue 😅
