### ISSUE TITLE
Accessing build information via `Spaceship::Tunes::Application` now results in errors

### ISSUE THREAD

**Issue by cooksimo** [fastlane/fastlane#14884]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.125.2`
- Last working version: `2.124.0`

### Regression Description
Accessing build information via `Spaceship::Tunes::Application` now results in errors

```
bundle exec fastlane spaceship
app = Spaceship::Tunes::Application.find('<bundle_id>')
app.build_trains

NoMethodError: undefined method `[]' for #<Spaceship::ConnectAPI::Response:0x007fd1dcb7a3a8>
from /Users/scook/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/test_flight/build_trains.rb:24:in `block in all'

app.builds

NoMethodError: undefined method `[]' for #<Spaceship::ConnectAPI::Response:0x007fd1ddb6f948>
from /Users/scook/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.125.2/spaceship/lib/spaceship/test_flight/build_trains.rb:24:in `block in all'
```

**Comment by joshdholtz** [comment]
@cooksimo Heyyyy! We are currently undergoing some API changes between legacy Apple APIs and the new App Store Connect APIS. I will get a fix out for this in a build either later today or tomorrow so the this keeps working but just as a heads up, stay tuned for future releases where you will probably want to use `Spaceship::ConnectAPI` 😊

**Comment by cooksimo** [comment]
Oh of course, I didn't even think of that as a way of moving forward. I'll experiment with moving our direct spaceship code to the ConnectAPI.

**Comment by joshdholtz** [comment]
I'm going to put some examples of how to use it in my PR and then soon I'll be creating better doc on how to use it and migrate from `Spaceship::TestFlight`

**Comment by iliao58** [comment]
any updates on this? when is the next release?
