### ISSUE TITLE
App Center deployment fails due to bad uri when app has spaces in the name

### ISSUE THREAD

**Issue by seanmcneil** [fastlane/fastlane#14882]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
URI is not properly formatted to account for spaces in the app name when submitting to App Center.

##### Command executed
   appcenter_upload(
      api_token: "tokengoeshere",
      owner_name: "mynamegoeshere",
      app_name: "My Awesome App"
    )

##### Complete output when running fastlane, including the stack trace and command used
```
Traceback (most recent call last):
	42: from /usr/local/bin/fastlane:23:in `<main>'
	41: from /usr/local/bin/fastlane:23:in `load'
	40: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
	39: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	38: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	37: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	36: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	35: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	34: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	33: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	24: from Fastfile:18:in `block (2 levels) in parsing_binding'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:54:in `block (2 levels) in parsing_binding'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.0.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:201:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.0.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:173:in `get_or_create_app'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.0.1/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:359:in `get_app'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:196:in `build_env'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:416:in `build_exclusive_url'
	 3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/generic.rb:1101:in `merge'
	 2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
	 1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': [!] bad URI(is not URI?): /v0.1/apps/mynamehere/My App Name (URI::InvalidURIError)
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Take screenshots for app store"
  lane :screenshots do
    capture_screenshots(reinstall_app: true, app_identifier: "com.bd.MyAppName")
    frame_screenshots(white: true)
    upload_to_app_store
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    tests
    build
    upload_to_testflight
    appcenter
  end

  desc "Push a new build to AppStore for review"
  lane :release do
    tests
    build
    
    upload_to_app_store(
      reject_if_possible: true,
      submit_for_review: true
    )

    appcenter
  end

  desc "Run unit & UI tests and lint project"
  lane :tests do
    reset_simulator_contents
    run_tests(scheme: "My App Name",
              devices: ["iPhone Xs", "iPad Air"])
    swiftlint(
      strict: true
    )
  end

  desc "Setup and build app"
  private_lane :build do
    ensure_git_status_clean
    build_app(workspace: "My App Name.xcworkspace", 
              scheme: "My App Name",
              output_directory: "/path/to/output")
  end

  desc "Upload to appcenter"
  private_lane :appcenter do
    appcenter_upload(
      api_token: "token",
      owner_name: "myusername",
      app_name: "My App Name"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.bd.MyAppName") # The bundle identifier of your app
apple_id("masked") # Your Apple email address

itc_team_id("masked") # App Store Connect Team ID
team_id("masked") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| httpclient                | 2.8.3        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.1.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
| fastlane-plugin-appcenter | 1.0.1        |
</details>

*generated on:* **2019-06-11**
</details>

<details>
  <pre> App Center has the URL formatted like this:
https://appcenter.ms/users/myname/apps/My-App-Name

But the value generated in fastlane is:
/v0.1/apps/mynamehere/My App Name
 </pre>
</details>

**Comment by seanmcneil** [comment]
On the plus side, you can work around this issue if you simply add the hyphens to the app name in your fastfile. For my example, using app_name: "My-Awesome-App" will result in a successful upload.

**Comment by janpio** [comment]
I think this method is coming from their plugin, not fastlane directly: https://github.com/microsoft/fastlane-plugin-appcenter You should probably report this issue in their repository.
