### ISSUE TITLE
Fastlane finished with errors Too long with no output

### ISSUE THREAD

**Issue by AfanasievN** [fastlane/fastlane#14886]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

``` 
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :tests do
    run_tests(scheme: "STRAUS", workspace: './ios/STRAUS.xcworkspace')
  end

end
``` 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [`[04:58:17]: ▸ Running script 'Bundle React Native code and images'
[04:58:18]: ▸ the transform cache was reset.
[04:59:25]: ▸ Copying /Users/distiller/Library/Developer/Xcode/DerivedData/STRAUS-hjmwfaqdniruurdvuutdkppjtvwr/Build/Products/Release-iphonesimulator/OneSignalNotificationServiceExtension.appex
[04:59:25]: ▸ skipping copy phase strip, binary is code signed: /Users/distiller/Library/Developer/Xcode/DerivedData/STRAUS-hjmwfaqdniruurdvuutdkppjtvwr/Build/Products/Release-iphonesimulator/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension
[04:59:26]: ▸ Linking STRAUSTests
[04:59:26]: ▸ Linking STRAUSTests
[04:59:26]: ▸ Generating 'STRAUSTests.xctest.dSYM'
[04:59:27]: ▸ 2019-06-12 04:59:27.290 xcodebuild[1161:19870]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[04:59:27]: ▸ /Users/distiller/Library/Developer/Xcode/DerivedData/STRAUS-hjmwfaqdniruurdvuutdkppjtvwr/Logs/Test/Run-STRAUS-2019.06.12_04-51-58--0700.xcresult/2_Test/Diagnostics/STRAUSTests-DC16930B-33A0-4C5F-9581-27FD6F287E4B/STRAUSTests-630C2948-80EC-49E9-9964-EE1D17828741/Session-STRAUSTests-2019-06-12_045927-1vTzjy.log
[04:59:27]: ▸ 2019-06-12 04:59:27.291 xcodebuild[1161:6744] [MT] IDETestOperationsObserverDebug: (3FE5F640-78FC-4803-86D5-93186BB267F6) Beginning test session STRAUSTests-3FE5F640-78FC-4803-86D5-93186BB267F6 at 2019-06-12 04:59:27.291 with Xcode 10A255 on target <DVTiPhoneSimulator: 0x7fc5d3bd64e0> {
[04:59:27]: ▸ SimDevice: iPhone 5s (0897050A-99CF-48CA-BA2A-6758F7C020EE, iOS 12.0, Shutdown)
[04:59:27]: ▸ } (12.0 (16A366))
[04:59:47]: ▸ All tests
[04:59:47]: ▸ Test Suite STRAUSTests.xctest started
[04:59:47]: ▸ STRAUSTests
+----------------------------+------------------------------------------------------------------------------------------+
|                                                     Lane Context                                                      |
+----------------------------+------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                                      |
| PLATFORM_NAME              | ios                                                                                      |
| LANE_NAME                  | ios tests                                                                                |
| ORIGINAL_DEFAULT_KEYCHAIN  | "/Users/distiller/Library/Keychains/login.keychain-db"                                   |
| SCAN_DERIVED_DATA_PATH     | /Users/distiller/Library/Developer/Xcode/DerivedData/STRAUS-hjmwfaqdniruurdvuutdkppjtvwr |
| SCAN_GENERATED_PLIST_FILES | []                                                                                       |
| SCAN_GENERATED_PLIST_FILE  |                                                                                          |
+----------------------------+------------------------------------------------------------------------------------------+

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | setup_circle_ci  | 0           |
| 3    | run_tests        | 1090        |
+------+------------------+-------------+

[05:09:47]: fastlane finished with errors
Too long with no output (exceeded 10m0s)`] </pre>
</details>

### Environment

<details>
  <pre> [version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test] </pre>
</details>

**Comment by AfanasievN** [comment]
Cannot understand why fastlane tests cannot be passed ... 

I just updated native code in my react-native project

**Comment by janpio** [comment]
How long to these tests run locally?
Do you usually get output in the console while the tests are running?

**Comment by AfanasievN** [comment]
@janpio It stops here --> 
[04:59:47]: ▸ Test Suite STRAUSTests.xctest started
[04:59:47]: ▸ STRAUSTests

and then no output for 10 mins and then there is output that ---> 
[05:09:47]: fastlane finished with errors
Too long with no output (exceeded 10m0s)`]

**Comment by janpio** [comment]
I see that, this is why Travis kills the process.

But:



> How long to these tests run locally?
> Do you usually get output in the console while the tests are running?

**Comment by AfanasievN** [comment]
@janpio Thanks for your time.

Fixed the issue by reproducing it on my local machine. 
Fixed the native Tests file by running it.

Then I had an issue with [11:12:27]: Exit status: 74, but everything said that is was successful.
I removed folder ./fastlane/test_output & ./fastlane/report.xml and everything worked fine

**Comment by AfanasievN** [comment]
Also I edited my fastlane file like this --> 
` default_platform :ios

app_name = "YOUR APP NAME"

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/<TOKEN_SLACK>" # Webhook URL created in Slack

    setup_circle_ci
  end

  desc "Installs FixCode which disables the \"Fix Issue\" button in Xcode"
    lane :xcode do
      install_xcode_plugin(
        url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
      )
  end

  lane :tests do
     run_tests(
                workspace: "ios/WORKSPACE_NAME.xcworkspace",
                scheme: "YOUR SCHEME NAME",
                device: "iPhone 8",
                include_simulator_logs: true
     )

     clean_build_artifacts
  end

  after_all do |lane|
     # This block is called, only if the executed lane was successful
     slack(
           message: "Tests was successful :rocket:",
           success: true,
           default_payloads: [:lane, :test_result, :git_branch, :git_author]
     )

  end

  error do |lane, exception|
      if is_ci
        slack(
          message: exception.message,
          success: false
        )
      end
    end
end
`
