### ISSUE TITLE
Sending to (not public) beta testing without uploading

### ISSUE THREAD

**Issue by agcmdl** [fastlane/fastlane#14896]
Is there a way to move specified build to specific beta testers group, without uploading again?
ie

```
send_to_beta_test(
   version: "1.2.0",
   build: "435",
   beta_testers_group_name: "SpecialBetaTesters"
)
```

ie do the same as can be done in AppStoreConnect here
![image](https://user-images.githubusercontent.com/48117162/59424277-5cc13c00-8ddc-11e9-9ba3-5f91627d7795.png)
So if i click there - _add a build to start testing_ - it allows me to select existing build and assigns it to that beta-testers group for testing.
Is it possible to do with some fastlane commands? Tried to search the documentation but all options I did find required uploading the build again.

**Comment by janpio** [comment]
I don't think this is possible with `testflight`/`pilot` in fastlane yet. The current functionality is more tester focused, not group focused. But this sounds like a useful feature, we should definitely look into supporting this.
