### ISSUE TITLE
Update uiautomator-v18

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#14897]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
UIAutomator from `screengrab` uses the outdated uiautomator-v18:2.1.2 and is crashing my compilation, updating to 2.2.0-alpha1 should solve the issue. Version 2.1.2 is not available for androidx.

<img width="488" alt="Screenshot 2019-06-13 at 17 42 51" src="https://user-images.githubusercontent.com/5521682/59451442-6316de80-8e03-11e9-97f6-97956649e206.png">

Edit:

Replacing the dependency to this solves the compilation problem:

```groovy
androidTestImplementation('tools.fastlane:screengrab:1.2.0') {
  exclude group: 'com.android.support.test.uiautomator', module: 'uiautomator-v18'
}
```

Will screengrab work without this?

##### Complete output when running fastlane, including the stack trace and command used

<img width="651" alt="Screenshot 2019-06-13 at 17 41 07" src="https://user-images.githubusercontent.com/5521682/59451439-601bee00-8e03-11e9-92da-f040d088b526.png">

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

Private

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/Users/ppamorim/Documents/fastlane-android/Google Play Android Developer-06b1d2357461.json"
package_name ""

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.0       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| tty-cursor                | 0.6.1        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| json                      | 2.2.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| os                        | 1.0.1        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
</details>

*generated on:* **2019-06-13**
</details>

**Comment by janpio** [comment]
Can I pull you in here @vanniktech to take a look? We really need to look into Androidx stuff more, but don't have the time right now.

**Comment by vanniktech** [comment]
I'd advertise to merge my open PR, cut a new release and then switch to AndroidX only by updating everything. I can help out with it

**Comment by vanniktech** [comment]
Nope

**Comment by colintheshots** [comment]
We're broke on this with the upgrade to Android Gradle Plugin 3.5.0. UI tests started erroring on non-AndroidX dependencies like UIAutomator. When we upgraded, we now get a screenful of Duplicate Class errors between the AndroidX and non-AndroidX versions of UIAutomator.

There should be a new version of Screengrab to update this dependency as I'm sure a lot of users' screenshot tests broke.

**Comment by janpio** [comment]
Your PR #15217 would solve the initial problem that @ppamorim reported @colintheshots?

**Comment by colintheshots** [comment]
Yes, that's correct.

**Comment by hauthorn** [comment]
Is there something I can do to help in this process? I have lurked a bit for a while and I'm personally feeling the pain of this one at the moment.

**Comment by janpio** [comment]
Feel free to jump over to #15217 and see if you can give something to the discussion going on over there as well. Just saying "this all makes sense and should work" would be a valuable contribution as well ;)

**Comment by plastiv** [comment]
Screengrab lib was updated. Now  `'tools.fastlane:screengrab:2.0.0'` depends on `androidx.test.uiautomator:uiautomator:2.2.0` so this issue can be closed I believe 🎉

Before you jump on the update please note, that there are issues with pulling screenshots from/into correct folders tracked here:

* https://github.com/fastlane/fastlane/issues/15690
* https://github.com/fastlane/fastlane/issues/14584
* https://github.com/fastlane/fastlane/issues/13810#issuecomment-553668985
