### ISSUE TITLE
Renew developer profiles with all devices and developer certificates

### ISSUE THREAD

**Issue by rockmobile** [fastlane/fastlane#14890]
### Feature Request
Renew developer profiles with all devices and developer certificates even when the status of the profile is valid.

#### Motivation Behind Feature

I see the option to renew the profiles when they are invalid or expired but there are situations where developers create new certificate or register a device and that needs to be included in the developer profile. In this situation the profile is still valid but need an option to regenerate with  all devices and dev certs.

**Comment by janpio** [comment]
Where should this functionality be added?

**Comment by rockmobile** [comment]
Hi @janpio, Thanks for looking into this ticket. I think it's best to add this to 'sigh'. Sign provides, options to repair expired/invalid profiles and generate new profiles. 
It would be a nice place to add option to renew/regenerate profile irrespective of the profile status to include devices and certs.

**Comment by janpio** [comment]
Can you suggest an API/option naming that would make sense?

**Comment by rockmobile** [comment]
we can call it as `regenerate` ?
we can  perform `fastlane sigh regenerate`  with supporting flags `--development`, `--force` & so on.
