### ISSUE TITLE
fastlane not support macOS Catalina (beta) 10.15

### ISSUE THREAD

**Issue by icpsteams** [fastlane/fastlane#14901]
When i used on terminals : **fastlane test**  
                                                                                                                                                                                      
I got this error.

```
Traceback (most recent call last):
 	2: from /usr/local/bin/fastlane:22:in `<main>'
 	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:262:in `bin_path'
 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem fastlane (>= 0.a) with executable fastlane (Gem::GemNotFoundException)
```

**NOTE:  it's worked good before update masOS Catalian.**

**Comment by max-ott** [comment]
Hi @icpsteams and welcome to `fastlane` This is usually an issue of `bundler`and the `gemfile.lock`. You might want to delete it and do a fresh `bundle install`: https://stackoverflow.com/questions/47026174/find-spec-for-exe-cant-find-gem-bundler-0-a-gemgemnotfoundexception
