### ISSUE TITLE
get_version_number gets the wrong version number

### ISSUE THREAD

**Issue by jakedunc** [fastlane/fastlane#1490]
My iOS project has two targets, one is my project, one is my Kiwi unit testing target. get_version_number uses _agvtool what-marketing-version -terse1_. This tells agvtool to return the version number of the first target that it finds. In my case this is the version number found in the plist of my testing target and I cannot change which order the targets are evaluated by agvtool to get this.

Would it make sense to use _what-version -terse_ instead here?

fastlane version (fastlane -v): fastlane-1.66.0
bundler

**Comment by KevinVitale** [comment]
+1: I have a Mac target & iOS target. Was suspecting it was pulling the wrong value...thanks for confirming.

**Comment by KrauseFx** [comment]
Should be fixed with https://github.com/fastlane/fastlane/pull/3944, right? 👍
