### ISSUE TITLE
execute multiple lanes in loop

### ISSUE THREAD

**Issue by bhavyahmehta** [fastlane/fastlane#14908]
I have white labeled android app code base.
and like to execute multiple lanes as per different product flavors using one command.
Is there any way for that ?

I do not want to use
_fastlane lane1 && fastlane lane2 etc.._

Is there any way like..
_lane :Release_all do
// here I want to loop through different lanes
end_

so if I use
 _fastlane Release_all_ 
then it will build and deploy each of my product flavors to playstore..

**My sample app file**

```
for_lane "Product1" do
  json_key_file "./fastlane/keys/product1.json"
  package_name "com.example.procuuct1"
end

for_lane "Product2" do
  json_key_file "./fastlane/keys/product2.json"
  package_name "com.example.procuuct2"
end

```

**My sample fast file**

```
update_fastlane
default_platform(:android)

desc "Deploy Product1 on Google Play Beta"
lane :Product1 do
      gradle(task: "clean")
      gradle(task: "assemble",
      build_type: "Release",
      flavor:"Product1")
      upload_to_play_store(track:"beta",
      skip_upload_screenshots: "true",
      skip_upload_metadata: "true",
      skip_upload_images:"true")
end

desc "Deploy Product2 on Google Play Beta"
lane :Product2 do
      gradle(task: "clean")
      gradle(task: "assemble",
      build_type: "Release",
      flavor:"Product2")
      upload_to_play_store(track:"beta",
      skip_upload_screenshots: "true",
      skip_upload_metadata: "true",
      skip_upload_images:"true")
end
..

```
Also need help to optimize fastfile code..

**Comment by janpio** [comment]
Yes, of course - `Fastfile` is just ruby code.

If you need to keep the `for_lane` construct to set `json_key_file` and `package_name` you can just create a `Release_all` lane that first calls `Product1` and then `Product2` as this will switch to those lanes.

```
lane :Release_all do
	Product1
	Product2
end
```

might already be enough.

**Comment by janpio** [comment]
Did this work for your @bhavyahmehta?

**Comment by bhavyahmehta** [comment]
Hello..  Apologize for late reply.. 

Got following error..
Fastfile:153 :in `block in parsing_binding': [!] uninitialized constant Fastlane::FastFile::Product1 (NameError)

**Comment by janpio** [comment]
Did you put that into the same `Fastfile`? This was trying to use the "lane switching" feature: https://docs.fastlane.tools/advanced/lanes/#switching-lanes

(In general lanes are usually written lowercase, but that shouldn't really influence the result here.)

**Comment by bhavyahmehta** [comment]
Here is my new sample fastfile

```
update_fastlane
default_platform(:android)

desc "Deploy Product1 on Google Play Beta"
lane :product1 do
      gradle(task: "clean")
      gradle(task: "assemble",
      build_type: "Release",
      flavor:"Product1")
      upload_to_play_store(track:"beta",
      skip_upload_screenshots: "true",
      skip_upload_metadata: "true",
      skip_upload_images:"true")
end

desc "Deploy Product2 on Google Play Beta"
lane :product2 do
      gradle(task: "clean")
      gradle(task: "assemble",
      build_type: "Release",
      flavor:"Product2")
      upload_to_play_store(track:"beta",
      skip_upload_screenshots: "true",
      skip_upload_metadata: "true",
      skip_upload_images:"true")
end

lane :release_all do
	product1
        product2 
end
```
I want after product1 lane completes it task , product2's task get start automatically.
I want like `fastlane release_all`  command execute all mention lanes (like product 1 and product 2).. one by one..

**Comment by janpio** [comment]
> I want after product1 lane completes it task , product2's lane task starts automatically.
> Like `fastlane release_all` command execute all mention lanes (like product 1 and product 2).. one by one..

Isn't this the same thing and exactly what is happening?

**Comment by bhavyahmehta** [comment]
Got same error.. as previous..

'block in parsing_binding': [!] uninitialized constant Fastlane::FastFile::product1 (NameError)

**Comment by bhavyahmehta** [comment]
Following code works..

```
lane :release_all do
      sh "fastlane product1"
      sh "fastlane product2"
end
```
