### ISSUE TITLE
Installing fast lane takes ages

### ISSUE THREAD

**Issue by jpike88** [fastlane/fastlane#14902]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Installing fast lane takes ages

I have a fast computer with a fast connection.

```Installing ri documentation for google-api-client``` Took over 5 minutes.

That's an insane amount of time... is there a way to skip documentation downloads altogether when installing? My CI takes way longer than it needs to just because of that line.

**Comment by max-ott** [comment]
Hi @jpike88 and welcome to `fastlane`. You might want to look into https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile There should also be options to install gems without their docs: https://stackoverflow.com/questions/1381725/how-to-make-no-ri-no-rdoc-the-default-for-gem-install

**Comment by janpio** [comment]
What command did you use to install fastlane @jpike88?

**Comment by jpike88** [comment]
oh ok thanks
