### ISSUE TITLE
Investigate usage of ENV vars in actions

### ISSUE THREAD

**Issue by mollyIV** [fastlane/fastlane#14915]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Actions can communicate with each other using a shared hash `lane_context`, that can be accessed in other actions, plugins or your lanes: `lane_context[SharedValues:XYZ]`. [This PR](https://github.com/fastlane/fastlane/pull/14746) documented Lane Variables. 

Some actions write output information to `ENV` variables though (we are not talking about `ENV` variables for the input options here). It might be interesting to get an overview of these. 

We would like to start with the answers to the following questions:

* How many unique `ENV` variables are set? 
* How many unique `FASTLANE_UNIQUE_KEY` variables are set? 
* What `ENV` variables are used for?

**Comment by mollyIV** [comment]
With a help of crafted `rubocop` rule to detect `ENV` variable assignments and a few `grep` commands, I was able to discover a few interesting things. 

* There are **48 unique** output `ENV` variables set by the actions;
* There are **12 unique** output `FASTLANE_UNIQUE_KEY` variables set by the actions.

```
FASTLANE_ENV_PRINTER
FASTLANE_HIDE_LOGIN_INFORMATION
FASTLANE_HIDE_TEAM_INFORMATION
FASTLANE_ITC_TEAM_ID
FASTLANE_ITC_TEAM_NAME
FASTLANE_LANE_NAME
FASTLANE_ONBOARDING_IN_PROCESS
FASTLANE_OPT_OUT_USAGE
FASTLANE_PLATFORM_NAME
FASTLANE_SKIP_DOCS
FASTLANE_TEAM_ID
FASTLANE_TEAM_NAME
```

```
BACKUP_XCARCHIVE_DESTINATION
CER_CERTIFICATE_ID
CER_FILE_PATH
CER_KEYCHAIN_PATH
CI
CREATED_NEW_APP_ID
CREATED_NEW_GROUP_ID
DANGER_GITHUB_API_TOKEN
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS
DERIVED_DATA_PATH
DEVELOPER_DIR
FL_BUILDLOG_PATH
FL_CARTHAGE_DERIVED_DATA
FL_SLATHER_BUILD_DIRECTORY
FORK_XCODE_WRITING
GITHUB_TOKEN
GYM_BUILD_PATH
GYM_CODE_SIGNING_IDENTITY
GYM_DERIVED_DATA_PATH
GYM_OUTPUT_DIRECTORY
GYM_RESULT_BUNDLE
MATCH_KEYCHAIN_NAME
MATCH_KEYCHAIN_PASSWORD
MATCH_READONLY
PRODUCE_APPLE_ID
SCAN_DERIVED_DATA_PATH
SCAN_INCLUDE_SIMULATOR_LOGS
SCAN_OUTPUT_DIRECTORY
SCAN_RESULT_BUNDLE
SIGH_CERTIFICATE_ID
SIGH_NAME
SIGH_PROFILE_ENTERPRISE
SIGH_UUID
XCODE_DERIVED_DATA_PATH
XCODE_INSTALL_TEAM_ID
XCODE_INSTALL_USER
```

**Comment by janpio** [comment]
Awesome @mollyIV!

Looked into the `FASTLANE` ones:

- `FASTLANE_ENV_PRINTER` seems to be for internal communication so that `fastlane env` does not get the used plugins printed
- `FASTLANE_HIDE_LOGIN_INFORMATION` and `FASTLANE_HIDE_TEAM_INFORMATION` do a similar job for login output during onboarding
- `FASTLANE_ITC_TEAM_ID` and `FASTLANE_ITC_TEAM_NAME` are used to "elevate" configuration options from the action to be used in spaceship, (also) possibly for other actions that do not have the ITC team id or name explicitly set
- `FASTLANE_LANE_NAME` used for the `for_lane` method/feature
- `FASTLANE_ONBOARDING_IN_PROCESS` hides an output during onboarding
- `FASTLANE_OPT_OUT_USAGE` set by `opt_out_usage` action, then read by Analytics code
- `FASTLANE_PLATFORM_NAME` used for the `for_platform` method/feature
- `FASTLANE_SKIP_DOCS` = `skip_docs` action
- `FASTLANE_TEAM_ID` and `FASTLANE_TEAM_NAME` are used to "elevate" configuration options, but also input ENV name for some options of some actions

---

Then when peeking into the other ENV vars I found this:
https://github.com/fastlane/fastlane/blob/457c5d647c77f0e078dafa5129da616914e002c5/fastlane/lib/fastlane/actions/setup_jenkins.rb#L1-L18
Seems someone else had the same idea some time before @mollyIV - this sure looks similar to `SharedValues` is used for by the docs now.

---

What is you conclusion of these first findings?

I was surprise how "little" ENV vars are used. I was expecting many more, used in more complicated ways. Still will be quite some work to untangle and then document this (probably manually I guess?).

**Comment by mollyIV** [comment]
Thank you @janpio for your research and explaining the usage context 🙇 

> I was surprise how "little" ENV vars are used.

The stats from my findings are about the actions that **set** the ENV variable and they do not include the actions that **read** the ENV variable. Thought it is worth highlighting again 🙂  

> What is you conclusion of these first findings?

I was also expecting many more ENV variables in usage. Since we documented `Lane Variables`, I think we might treat `ENV` variables in a similar manner - at the end it is an **output** that the action produces. 

However in a case of `ENV` variables, I would bet on centralised approach because of "cross usage" and interdependencies between the actions. I can imagine if a given action set an `ENV` variable, we could force the docs by leveraging `rubocop` rule - just like we did for `SharedValues`. 

WDYT? 🤔

**Comment by janpio** [comment]
> The stats from my findings are about the actions that **set** the ENV variable and they do not include the actions that **read** the ENV variable. Thought it is worth highlighting again 🙂

Oh, so there could be other ENV vars that are e.g. documented to do x, but are only read and not written in the code that this would not list?

> However in a case of `ENV` variables, I would bet on centralised approach because of "cross usage" and interdependencies between the actions. I can imagine if a given action set an `ENV` variable, we could force the docs by leveraging `rubocop` rule - just like we did for `SharedValues`.

Hm, I don't know how useful this would be. The idea behind our documentation of `SharedValues` was to enable users to discover that they can use those. For this to work, it needs to be on the action page. (Or do you just mean to define it in a central place, but still render it on the action pages in the docs?)

**Comment by mollyIV** [comment]
> Oh, so there could be other ENV vars that are e.g. documented to do x, but are only read and not written in the code that this would not list?

Indeed 👍 I just searched for `ENV` variables that are set by the actions. You think there might be different `ENV` variables that are only read by a given action (coming from external source)? 🤔 

> Or do you just mean to define it in a central place, but still render it on the action pages in the docs?

Exactly 👍

**Comment by mollyIV** [comment]
I talked with @janpio and we would like to propose the following action plan:

### New `output_env` method

New `output_env` method would be added to `Action` class which is a base class for every actions. 

```ruby
def self.output_env
      # Return the environment variable keys you set in the action
      # [
      #   ['GYM_BUILD_PATH', 'The directory in which the ipa file should be stored in']
      # ]
      nil
end
```

### New `rubocop` rule

New `rubocop` rule would be added to our custom cops. The rule would look for `ENV` variable assignments (only in action code, it would skip spec and rake files). If `ENV` variable key was not added to the `output_env` method, it would add an offense. The behaviour would be very similar to what we did in [the PR about `SharedValues`](https://github.com/fastlane/fastlane/pull/14610). 

### Documentation 

The documentation would be generated automatically, per action, based on `output_env` method. 

Please share your thoughts guys 🙏 🙇

**Comment by janpio** [comment]
I like it. 

(I can't really gauge the impact, and also don't know if we will be able to find good descriptions for all variables though, so this could still break when trying to implement it.)

**Comment by joshdholtz** [comment]
To be honest, ENV variables being used as output is something that always made me cringe 😬 IMO, anything that wants to output values in ENV should end up using `SharedValues` instead. I would actually argue that the rubocop rule should probably just error out on these and instead tell the developer to use `ShareValues` instead 🙃 

One of the big benefits of this is that `SharedValues` allows storing of any type of object where ENV can only store primitives. 

The biggest abuser of storing ENVs for output is `cert` and `sigh`.

I would totally be down for that rule that catches these and tells the user to used `SharedValues` instead because even though documenting the use of ENVs being modified is better than not, I don't think its a behavior we should  condone 😇 **But*, this thought is probably a huge breaking change that we would need to include in "fastlane 3.0" if this is the approach we wanted to go 🙃

@mollyIV @janpio  Thoughts?

**Comment by janpio** [comment]
Isn't there a useful usecase for using ENV vars for stuff you want to use _after_ fastlane is finished? Paths for IPAs, certificates etc?

(But yes, internally we should probably switch to SharedValues)

**Comment by mollyIV** [comment]
> I would actually argue that the rubocop rule should probably just error out on these and instead tell the developer to use ShareValues instead 🙃

@joshdholtz, ❤️ that idea. 

> *But, this thought is probably a huge breaking change that we would need to include in "fastlane 3.0" if this is the approach we wanted to go 🙃

Actually I didn't even think about introducing breaking changes 🤔This indeed can open a lot more options to consider. 

> Isn't there a useful usecase for using ENV vars for stuff you want to use after fastlane is finished? Paths for IPAs, certificates etc?

@janpio I thought that it is the main purpose of using `ENV` - making values available even though a `fastlane` process is finished. It can be very hard to figure out how many users use `ENV` vars in that way. 

> (But yes, internally we should probably switch to SharedValues)

Absolutely 👍 The question is how to identify `ENV` vars used internally - we do not know what `ENV` vars someone uses in the workflow. 

Having a clear guidelines and documentation about action's output would be very valuable. We did pretty good progress on that - documented Lane Variables (aka `SharedValues`) and rubocop rules to prevent missing documentation in the future. By getting rid of `ENV` variables used as output from actions (which are basically another way of outputting values), we would standardise the action's  output. 

If someone needed to use `ENV` variable in the workflow, he could make the `ENV` export in `Fastfile` very easily:

```
some_action(param: 'value') # `some_action` would output `SharedValues::KEY` (output documented in the documentation)
ENV['KEY'] = lane_context[SharedValues::KEY] # 🎉 
```

The biggest benefit of providing the rules for action's output would be **standardisation**, **documentation** and **clear public API**. 

`ENV` - input, `Lane Variables` - output 🎊 

And btw, speaking about `ENV` as input parameters - cannot see any docs for them💡🤔

**Comment by janpio** [comment]
> The question is how to identify `ENV` vars used internally - we do not know what `ENV` vars someone uses in the workflow.

"internally" referred to other _actions_ using ENV vars to get data set by earlier actions. No idea if this even exists.

**Comment by mollyIV** [comment]
I did a bit more investigation on internal usage. Analysed **no** `FASTLANE` ones. 

### Used internally 

**What it means that an `ENV` variable is used internally?** 

It means that `fastlane` code base (actions / helpers) is reading and using `ENV` variable to perform a code logic. The value of `ENV` variable is read either from action's `available_options` `env_name` input parameters or directly in an action's code logic (i.e. 
`get_certificates.rb` `CER_FILE_PATH`): 

```
BACKUP_XCARCHIVE_DESTINATION
CER_CERTIFICATE_ID
CER_FILE_PATH
CER_KEYCHAIN_PATH
DERIVED_DATA_PATH
DEVELOPER_DIR
FL_BUILDLOG_PATH
FL_CARTHAGE_DERIVED_DATA
FL_SLATHER_BUILD_DIRECTORY
GYM_BUILD_PATH
GYM_CODE_SIGNING_IDENTITY
GYM_DERIVED_DATA_PATH
GYM_OUTPUT_DIRECTORY
GYM_RESULT_BUNDLE
MATCH_KEYCHAIN_NAME
MATCH_KEYCHAIN_PASSWORD
MATCH_READONLY
SCAN_DERIVED_DATA_PATH
SCAN_INCLUDE_SIMULATOR_LOGS
SCAN_OUTPUT_DIRECTORY
SCAN_RESULT_BUNDLE
SIGH_CERTIFICATE_ID
SIGH_NAME
SIGH_PROFILE_ENTERPRISE
SIGH_UUID
XCODE_DERIVED_DATA_PATH
XCODE_INSTALL_TEAM_ID
XCODE_INSTALL_USER
```

Detected **28** ENV variables.

### Not used internally 

We do export the following lanes, but do not use them internally:

```
CREATED_NEW_APP_ID
CREATED_NEW_GROUP_ID
DANGER_GITHUB_API_TOKEN
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS
FORK_XCODE_WRITING
PRODUCE_APPLE_ID
```

Detected **6** ENV variables.

## Not used at all 

It turned out that a `rubocop` lane detected two `ENV` vars which are used only in a `test_sample_code`:

```
CI
GITHUB_TOKEN
```

Detected **2** ENV variables.

To detect above values, I did manual searching. It would be great to automate it somehow by more sophisticated `rubocop` rule or custom script which would simply analyse the text (code files).

**Comment by janpio** [comment]
> Used internally

When you looked at that code, would those be examples that should better be solved with `lane_context` variables?

**Comment by mollyIV** [comment]
Yes, I believe so 👍 

What's more we are already doing that for some actions - setting a default value via `SharedValues`:

https://github.com/fastlane/fastlane/blob/793a0fdb123fd15d48326dd84b93d6da3e94afea/fastlane/lib/fastlane/actions/backup_xcarchive.rb#L66-L76

Let's remember that replacing an internal usage of `ENV` with `SharedValues` would still be a breaking change.

**Comment by janpio** [comment]
We could probably first _add_ the `lane_context` and still fallback to the ENV var, and change the location that sets it from ENV to `SharedValue`. Then when we remove the reading from the ENV, only that would be a breaking change.

**Comment by mollyIV** [comment]
@fastlane-bot we are still working on this one 👍

**Comment by mollyIV** [comment]
@fastlane-bot work in progress 🤚
