### ISSUE TITLE
Facing bad [!] bad URI(is not URI?): issue. 

### ISSUE THREAD

**Issue by v2Nitesh** [fastlane/fastlane#14916]
### New Issue Checklist

- [ 2.125.2 ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[Traceback (most recent call last):
	39: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	38: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	37: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/bin/fastlane:23:in `<main>'
	36: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/bin/fastlane:23:in `load'
	35: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1@global/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
	34: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	33: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	31: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	23: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:25:in `block (2 levels) in parsing_binding'
	18: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	17: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	16: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	15: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	14: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	13: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	12: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	11: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-mobile_center-0.1.5/lib/fastlane/plugin/mobile_center/actions/mobile_center_upload_action.rb:384:in `run'
	10: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-mobile_center-0.1.5/lib/fastlane/plugin/mobile_center/actions/mobile_center_upload_action.rb:341:in `get_or_create_app'
	 9: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-mobile_center-0.1.5/lib/fastlane/plugin/mobile_center/actions/mobile_center_upload_action.rb:311:in `get_app'
	 8: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	 7: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	 6: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	 5: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:196:in `build_env'
	 4: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:416:in `build_exclusive_url'
	 3: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/generic.rb:1101:in `merge'
	 2: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
	 1: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': [!] bad URI(is not URI?): /v0.1/apps/Nitesh Meshram/ (URI::InvalidURIError)]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
What command are you running? Is this the full output you are getting? Please post your `fastlane env` output.

**Comment by v2Nitesh** [comment]
I am running : - fastlane beta and trying to upload build on mobile_center_upload. I was able to upload build on to the HockeyApp but it's fail while building it for "mobile_center_upload"

Example : - 
 mobile_center_upload(
    api_token: "XXX",
    owner_name: "Nitesh Meshram",
    app_name: "ABC",
    ipa: "./DemoApp.ipa",
    release_notes: "Pops!"
  )

fastlane env - Output below 
=====>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.5.1/bin/fastlane       |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    gym(export_method: "ad-hoc")
    build_app(workspace: "DemoApp.xcworkspace", scheme: "DemoApp")
    #upload_to_testflight

    hockey(
      api_token: "9a172758bdfe4fe4b10299bfc9ea519a",
      ipa: "./DemoApp.ipa",
      notes: "Changelog"
    )
   
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.v2solutions.gps.qa") # The bundle identifier of your app
apple_id("nitesh.meshram@v2solutions.com") # Your Apple email address

itc_team_id("118724289") # App Store Connect Team ID
team_id("X5E35DL2Y9") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-mobile_center | 0.1.5   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.2.0        |
| executable-hooks              | 1.5.0        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 1.16.2       |
| CFPropertyList                | 3.0.0        |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.6.0        |
| atomos                        | 0.1.3        |
| babosa                        | 1.0.2        |
| claide                        | 1.0.2        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.10       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.4.1        |
| unf_ext                       | 0.0.7.6      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20180417 |
| dotenv                        | 2.7.2        |
| emoji_regex                   | 1.0.1        |
| excon                         | 0.64.0       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.15.4       |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.13.1       |
| fastimage                     | 2.1.5        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.1.0        |
| memoist                       | 0.16.0       |
| multi_json                    | 1.13.1       |
| os                            | 1.0.1        |
| signet                        | 0.11.0       |
| googleauth                    | 0.6.7        |
| httpclient                    | 2.8.3        |
| mime-types-data               | 3.2019.0331  |
| mime-types                    | 3.2.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.23.9       |
| google-cloud-env              | 1.1.0        |
| google-cloud-core             | 1.3.0        |
| google-cloud-storage          | 1.16.0       |
| json                          | 2.2.0        |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.5.0        |
| rubyzip                       | 1.2.3        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.5        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.6.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.7.0        |
| tty-cursor                    | 0.7.0        |
| tty-spinner                   | 0.9.1        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.2.6        |
| xcodeproj                     | 1.10.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.0        |
| fastlane-plugin-mobile_center | 0.1.5        |
</details>


*generated on:* **2019-06-18**
</details>

**Comment by janpio** [comment]
You didn't include the full output you are getting.

But: `mobile_center_upload` is not really a thing any more, as Microsoft has an official updated plugin now: https://github.com/microsoft/fastlane-plugin-appcenter You should probably try that one.

**Comment by v2Nitesh** [comment]
I have updated "mobile_center_upload" this with below : 

    appcenter_upload(
      api_token: "e6c1edcb9603a673e535f13d0354f7b69b60f205",
      owner_name: "Nitesh Meshram",
      app_name: "<your app name>",
      apk: "./DemoApp.ipa",
      notify_testers: true 
    )
 But still getting below Error : [17:25:37]: fastlane finished with errors

[!] Could not find action, lane or variable 'appcenter_upload'. Check out the documentation for more details: https://docs.fastlane.tools/actions

**Comment by janpio** [comment]
You have to install the plugin like the documentation on https://github.com/microsoft/fastlane-plugin-appcenter tells you to.

**Comment by v2Nitesh** [comment]
Yes, below is the output for same. 

✘ niteshmeshram@NitMac  ~/Documents/V2Apps/DemoApp  fastlane add_plugin appcenter
[✔] 🚀
+-------------------------------+---------+----------------------+
|                          Used plugins                          |
+-------------------------------+---------+----------------------+
| Plugin                        | Version | Action               |
+-------------------------------+---------+----------------------+
| fastlane-plugin-mobile_center | 0.1.5   | mobile_center_upload |
+-------------------------------+---------+----------------------+

[17:34:21]: Plugin 'fastlane-plugin-appcenter' was added to './fastlane/Pluginfile'
[17:34:21]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Successfully installed plugins

I have again installed plugin.

**Comment by janpio** [comment]
Then the action is available and can be used in your custom lanes.
(Running the command again should also list the plugin now. You might want to uninstall the old one as well.)

**Comment by v2Nitesh** [comment]
> Then the action is available and can be used in your custom lanes.
>>>>>I am new for Fastlane let me check how to do that. 
> (Running the command again should also list the plugin now. You might want to uninstall the old one as well.)
>>>>> Which one I have to uninstall, can you help me out? Can you share command.

**Comment by janpio** [comment]
> Which one I have to uninstall, can you help me out? Can you share command.

Just remove it from `fastlane/Pluginfile` and run `bundle update`.

**Comment by v2Nitesh** [comment]
I have followed above and run "fastlane beta". Got below error : 

 Could not find action, lane or variable 'appcenter_upload'. Check out the documentation for more details: https://docs.fastlane.tools/actions

**Comment by janpio** [comment]
Share your current `fastlane env` please.

**Comment by v2Nitesh** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.5.1/bin/fastlane       |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    gym(export_method: "ad-hoc")
    build_app(workspace: "DemoApp.xcworkspace", scheme: "DemoApp")
    #upload_to_testflight

    appcenter_upload(
      api_token: "e6c1edcb9603a673e535f13d0354f7b69b60f205",
      owner_name: "Nitesh Meshram",
      app_name: "<your app name>",
      apk: "./DemoApp.ipa",
      notify_testers: true 
    )
   
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.v2solutions.gps.qa") # The bundle identifier of your app
apple_id("nitesh.meshram@v2solutions.com") # Your Apple email address

itc_team_id("xxxxx") # App Store Connect Team ID
team_id("xxxxxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.2       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.1.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-06-18**
</details>

**Comment by janpio** [comment]
> Loaded fastlane plugins:
> No plugins Loaded

So the plugin didn't successfully install. Please follow the instructions of the plugin again.

**Comment by v2Nitesh** [comment]
How to resolve this...do you have any idea ??

**Comment by v2Nitesh** [comment]
I have resolved that Plugin issue after that got this error. 

[10:37:52]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Facing bad [!] bad URI(is not URI?): issue.
    https://github.com/fastlane/fastlane/issues/14916 [open] 14 💬
    10 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	39: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	38: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	37: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/bin/fastlane:23:in `<main>'
	36: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/bin/fastlane:23:in `load'
	35: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1@global/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
	34: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	33: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	31: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	23: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:25:in `block (2 levels) in parsing_binding'
	18: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	17: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	16: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	15: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	14: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	13: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	12: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	11: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-appcenter-1.0.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:201:in `run'
	10: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-appcenter-1.0.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:173:in `get_or_create_app'
	 9: from /Users/niteshmeshram/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-appcenter-1.0.1/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:359:in `get_app'
	 8: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	 7: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	 6: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	 5: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:196:in `build_env'
	 4: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:416:in `build_exclusive_url'
	 3: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/generic.rb:1101:in `merge'
	 2: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
	 1: from /Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/Users/niteshmeshram/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': [!] bad URI(is not URI?): /v0.1/apps/Nitesh Meshram/DemoApp (URI::InvalidURIError)

**Comment by janpio** [comment]
That is an error message from the Microsoft AppCenter servers, so you should probably ask over at https://github.com/microsoft/fastlane-plugin-appcenter
