### ISSUE TITLE
[supply] Add Support for Playstore's Internal app sharing.

### ISSUE THREAD

**Issue by iamBedant** [fastlane/fastlane#14924]
#### Motivation Behind Feature
Add support for publishing apk/AppBundles to Playstore's [Internal app sharing](https://support.google.com/googleplay/android-developer/answer/9303479) track.

#### Feature Description
Google announced a new Internal app sharing track for build distribution. It would be great to be able to upload apks and aabs and get the public URL as the output in case of success.

#### Alternatives or Workarounds
The current workaround is to upload apk/bundles manually to [internalappsharing](https://play.google.com/apps/publish/internalappsharing/) page.

### Environment

Gem | Version | Update-Status
-- | -- | --
fastlane | 2.127.2 | ✅ Up-To-Date

**Comment by iamBedant** [comment]
The feature is not added yet. I have updated the `env`

**Comment by martinjuhasz** [comment]
you can publish apps to the internal testing track using supply.

```supply(track: 'internal', apk: ...)```

not sure how if/how to receive the test url tho

**Comment by futabooo** [comment]
upload Internal app sharing needs Google Play Developer API v3.
so #14573 needs to be resolved

**Comment by dt-chris** [comment]
i would also be interested in getting support for play store's internal app sharing. to be clear, this is different from the internal test track - it's not part of the test/release track at all, it's a new-ish feature google added under development tools. it lets you upload one-off builds without needing to bump the version number, and you can distribute a link to install it without needing to be a part of any beta test program. very useful for distributing staging builds to internal testers.

**Comment by gneokleous** [comment]
Open a new issue regarding this featured request:  https://github.com/fastlane/fastlane/issues/15636
