### ISSUE TITLE
Specify Cocoapods version

### ISSUE THREAD

**Issue by JayCantyEMoney** [fastlane/fastlane#14926]
### Feature Request

A lot of pain can be avoided if you add a version field to `cocoapods` lane.  https://docs.fastlane.tools/actions/cocoapods/

#### Motivation Behind Feature

I tried to add a comment to https://github.com/fastlane/fastlane/issues/3671 and several other similar but is locked to collaborators.  

I am not a ruby dev, I love fastlane for it's convenience in automation....

Yesterday, our builds started failing at a bad time.  It was due to a new version of cocoapods being available, `fastlane cocoapods` uses the latest.

I tried to follow these steps to lock down the cocoapods version:

> To achieve this, you should use a Gemfile as described in the CocoaPods docs. This way you specify the actual dependency which is being resolved using bundler 👍

Worked fine on local machine, but on remote cd, all hell broke loose.  First I needed to get the correct `bundle` to match my Gemfile.lock.  Then, I think due to a react native project and a bit different directory structure than standard ios, fastlane called `cd ./ios && bundle exec` and `bundle` could not be found.

After hours of trying to become a ruby dev, I gave up and used the CD (Bitirse) services' `run cocoapods step`.    

I have always though of fastlane as an easy tool to use, and not yet another dev time sync. 

#### Feature Description

If it isn't too much of a lift, it would be very nice to be able to specify `version` of cocoapods.
```
cocoapods(podfile: './ios/Podfile', version: '1.7.1')
```

#### Alternatives or Workarounds

Become an expert at ruby or use cd's cocoapods step.....

**Comment by richardtop** [comment]
I currently use the following setup to specify the CocoaPods version:
- RVM
- Bundler

When CI checks out a new commit to the repository, it first runs `bundle install`, so it mimics the exact setup I have on my local machine.

In case I update CocoaPods locally, (and only in that case) and commit that change to the repository (via `Gemfile.lock`), the CI machine would download and install a new version.

Also, what's interesting, some older branches can run in parallel with the newer ones which might use different versions of CocoaPods while both integrated on the same CI machine.

**Comment by joshdholtz** [comment]
@JayCantyEMoney Heyyy 👋 Using bundler is the best and coorect answer here like @richardtop has mentioned 👌 Lock the versions in your `Gemfile`, run `bundle install`, and run with `bundle exec fastlane <platform> <lane>` and you should be good 💯 

Issues like this is exactly why bundler was made and is highly used in the ruby ecosystem 💪

**Comment by janpio** [comment]
Also worth to note that it is just not possible to use a `version` option for the `cocoapods` action to specify which version should be used, as the action just uses what ever `pod` is installed and available on the machine you are running on. If that is a specific one via `Gemfile` and `bundle install`, then is uses this - otherwise whatever it finds.

@joshdholtz Wouldn't this also require to [use the `use_bundle_exec` option](https://github.com/fastlane/fastlane/blob/6b7251d7346f3e2e1014dacb0640ba43dcb94f0a/fastlane/lib/fastlane/actions/cocoapods.rb#L17-L18) for `cocoapods` though?
