### ISSUE TITLE
Screenshot resume feature

### ISSUE THREAD

**Issue by fulldecent** [fastlane/fastlane#14921]
Requesting a resume feature. Screenshots can take hours. One time my computer ran out of juice in the process. It was painful.

**Comment by janpio** [comment]
Taking screenshots or uploading screenshot?
How should this work for the users?
How could this work on the tech side?

(The [issue template](https://github.com/fastlane/fastlane/issues/new?template=FEATURE_REQUEST.md) is there for a reason, it helps you create issues with the information necessary.)

**Comment by fulldecent** [comment]
Sorry about that.

During the taking screenshots part.

For the user, the default behavior could be:

> Existing screenshots found, skipping these configurations:
> en-US—iPhone 5s, en-US—iPhone 6...
>
> To recreate those screenshots, delete them from the directory or add "clear_previous_screenshots(true)" to your Snapfile.

On the tech side, this could be implemented by using a glob to check for existing files before beginning to target a device+language combination.

**Comment by janpio** [comment]
I have the vague feeling that we already have something similar somewhere, but I can't pinpoint it right now.

Your request looks reasonable and useful. 

The current suggested implementation details might be a breaking change, so we would probably prefer to add an option like e.g. `skip_existing_screenshots` or similar - but I would have to look deeper into the details of this.
