### ISSUE TITLE
Fastlane Bot: Do not ask for "fastlane env" in "feature request" issues

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#14928]
#### Motivation Behind Feature
`fastlane env` is irrelevant for the majority of feature requests.

#### Feature Description
Fastlane bot wouldn't reply with [these messages](https://github.com/fastlane/fastlane/issues/14922#issuecomment-503656267) when the issue is a feature request.

Since current user's environment is not relevant to the new feature spec. If the feature is valid only for a particular environment, that would be included in the feature request itself. Therefore, the bot only clutters the discussion.

#### Alternatives or Workarounds
None

**Comment by richardtop** [comment]
@fastlane-bot 💖 you! so smart

**Comment by janpio** [comment]
Valid point, although relying on "Feature Request" in the description is probably the only measure that can be used here - which of course will be imperfect. Still worth to implement.

**Comment by richardtop** [comment]
@janpio that's as close as you could get

**Comment by mollyIV** [comment]
Hey @janpio , @richardtop  👋

I think we can leverage the issue template and a label `type: feature`. According to [the documentation](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) it is possible to automatically apply labels to your issue template 🙌 

So if a user created a new feature request, we would apply the label `type: feature` automatically. Bot would identify the label and not add add a comment `It seems like you have not included the output of...`

WDYT? 

I worked on our bot a little, so will be happy to make this improvement 🙂

**Comment by janpio** [comment]
Great in theory, not that great in practice: We don't want to label automatically based on template usage, as people tend to use the wrong template all the time, also being labeled is my measure of "this issue has been triaged".

**Comment by mollyIV** [comment]
Oh, I see 👍 

> We don't want to label automatically based on template usage, as people tend to use the wrong template all the time.

I guess searching for "Feature Request" word in the description won't help either in that case 🤔 

> Also being labeled is my measure of "this issue has been triaged

Adding labels automatically would definitely not help 😉 

Another idea might be to come up with the new label 🤔

**Comment by janpio** [comment]
It doesn't really make a difference if we look for e.g. `### Feature Request` or a label `feature`, both might be abused. But as labels have another job as well, I think we are fine to go with the text string here. 

Can the bot work on that @mollyIV?

**Comment by mollyIV** [comment]
Makes sense 👍 

I had a quick look into bot's code:

https://github.com/fastlane/issue-bot/blob/40d57f82d60fe063ed6d6aaafd54baf5b9de6464/bot.rb#L312-L324

There should be no issue to search for `### Feature Request` in PR's body 🙌

**Comment by richardtop** [comment]
I don't think we should think that much about the abuse.

> I guess searching for "Feature Request" word in the description won't help either in that case 🤔

I think, it's a great idea. Just by checking the "feature request" with specific pattern (i.e. in the header) should do the job for the majority of cases.

Since the bot aims to quicken the time it takes to resolve the issue, but currently, it slows things down for a big portion of feature requests.

**Comment by richardtop** [comment]
Testing pat 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janpio** [comment]
(Additional feature request: If "Do you agree, @fastlane-bot ?", reply with "Yes." 🐒)

**Comment by mollyIV** [comment]
[The PR](https://github.com/fastlane/issue-bot/pull/64) has been created 🎁

**Comment by janpio** [comment]
PR https://github.com/fastlane/issue-bot/pull/64 has been merged and tested - thanks @richardtop for the idea!
