### ISSUE TITLE
dsym still missing in firebase but upload symbols success

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#14929]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

upload_symbols_to_crashlytics reports Successfully uploaded dSYM files to Crashlytics . but when i check in firebase it still reports dsym missing
##### Command executed

upload_symbols_to_crashlytics(dsym_path:<path_dsym>, gsp_path: <path_plist>)
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.117.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.5       |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.1       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

**Comment by vastopa** [comment]
I am experiencing a similar issue with dSYM files for Sentry. My xcode project has a Sentry Build Phase. In this script I am using the environment variable `$DWARF_DSYM_FOLDER_PATH` to find the path to the dSYMs from my build and then using `sentry-cli` to upload the dSYMs at that location. This script works as expected when building/archiving the app from xcode but when archiving the app using `gym`, I get an error stating that my app dSYM is not at the specified location (but all my framework dependency dSYMs exist). 

I validate that the app dSYM does exist at this folder location after the script runs. So after a lot of experimenting, I found that adding an 8s sleep to the script before it looks for the dSYM. This actually resolves the issue, and the app dSYM is found after the delay.

Is it possible that fastlane is holding/moving the app dSYM until after a certain build/archive step?

the lane that I am running is:
```
desc "Archive the app"
lane :archive do |options|
  gym(
      clean: options[:clean],
      scheme: options[:scheme],
      configuration: 'Release',
      sdk: "iphoneos#{ENV["FL_LATEST_OS_VERSION"]}",
      xcargs: options[:xcargs]
  )
end
```

Any help/insights would be greatly appreciated!

**Comment by janpio** [comment]
@pavm035 You should upgrade your fastlane to a recent version before we try to debug this.

**Comment by taschik** [comment]
I experience a very similar issue. During my build I see that the files are getting uploaded:
```

[18:11:20]: -------------------------------------------
--
  | [18:11:20]: --- Step: upload_symbols_to_crashlytics ---
  | [18:11:20]: -------------------------------------------
  | [18:11:22]: Using 8 threads for Crashlytics dSYM upload 🏎
  | [18:11:22]: Extracting '/Users/user/buildkite/MeiBookPro-local-1/app/app-app/dist/app.app.dSYM.zip'...
  | [18:11:22]: $ unzip -qo /Users/user/buildkite/MeiBookPro-local-1/app/app-app/dist/app.app.dSYM.zip
  | [18:11:23]: Uploading '2E620B08-C68F-3E00-9306-357DBCF2A870.dSYM'...
  | [18:11:23]: Uploading 'app.app.dSYM'...
  | [18:11:23]: Uploading '2D6C5B90-D384-3FC3-B5DF-0730E1FE0E45.dSYM'...
  | [18:11:23]: Uploading 'C3779DDF-94B0-3AD0-B8A4-40781828A481.dSYM'...
  | [18:11:23]: Uploading 'D0E46DF3-C068-3136-A5C6-8E9B7067F143.dSYM'...
  | [18:11:37]: Successfully uploaded dSYM files to Crashlytics 💯
```

But when I look into the Firebase console I see that Firebase misses DSYMs for exactly that build number:
<img width="847" alt="app  – Crashlytics – Firebase console 2019-08-06 17-47-38" src="https://user-images.githubusercontent.com/351623/62586406-58f8e580-b872-11e9-8cd1-ff3cc2ec9b6e.png">

But as you can see, `2D6C5B90-D384-3FC3-B5DF-0730E1FE0E45.dSYM` got uploaded before. Any idea?

**Comment by pavm035** [comment]
@taschik  i think i got answer from firebase team regarding this is that if your app is migrated from crashlytics to firebase then you need to use different way of uploading dsym to firebase to work with and their reply is

> Upon checking this with the team, if you're working with an app that you previously linked from Fabric to Firebase Crashlytics, you need to pass your Fabric API Key to run the upload symbols script. You should replace “/path/to/GoogleService-Info.plist" with “-a fabric-api-key”.

> Could you try to run this script “/path/to/pods/directory/Fabric/upload-symbols -a fabric-api-key -p ios /path/to/dSYMs” and see if the issue still `persist?`

**Comment by taschik** [comment]
Thanks @pavm035 is this the `api_token` that I can pass into the `upload_symbols_to_crashlytics` module?

**Comment by pavm035** [comment]
@taschik yes

**Comment by apanagar** [comment]
I'm also experiencing this issue. @pavm035 Could you provide an example of how that would be done from the Fastfile? Or should I just call the script as you've described at the end of my build process?

**Comment by pavm035** [comment]
@apanagar Yes i called that script from fastfile after building
