### ISSUE TITLE
@fastlane-bot should not handle issues that have `status: has-pr` label

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14927]
@fastlane-bot unfortunately also tries to handle/close issues that have a PR waiting to be merged. It should look at the labels present, and not do anything for issues with label `status: has-pr`.

**Comment by mollyIV** [comment]
Great idea, I will tackle this @janpio if you do not mind 🙂

**Comment by janpio** [comment]
Yes please!

**Comment by mollyIV** [comment]
https://github.com/fastlane/issue-bot/pull/65 🎁 🙂
