### ISSUE TITLE
"exportOptionsPlist error for key 'method': expected one of {}, but found app-store" 

### ISSUE THREAD

**Issue by ntk860** [fastlane/fastlane#14931]
I am trying to build my project to send it to testflight, it was working before, but I had my apple developer account expired, after I paid it stoped working.

##### Command executed
fastlane beta

##### Complete output when running fastlane, including the stack trace and command used

```
2019-06-20 07:55:56.388 xcodebuild[5027:533805] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.2/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.2/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    sync_code_signing(
        git_url: "xxxxxxxx",
        type: "appstore",
        app_identifier: "xxxxxxxx",
        username: "xxxxxxxx",
        keychain_password: "xxxxxx",
        force: true,
        platform: "ios"
    )
    disable_automatic_code_signing(path: "kiambote.xcodeproj")
    build_app(
      scheme: "kiambote",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
    )
    increment_build_number
    enable_automatic_code_signing(path: "kiambote.xcodeproj")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("com.nossapps.products.kiambote") # The bundle identifier of your app
# apple_id("nossapps@gmail.com") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.0       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.1.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-06-20**
</details>

**Comment by ntk860** [comment]
Kind of @fastlane-bot I just looked over and I saw that everything is ok with code signing. The logs shows that everything is ok with the code signing.

**Comment by ntk860** [comment]
Yes @fastlane-bot, and it still not working.

**Comment by ntk860** [comment]
@fastlane-bot I also revoked the certificate, created a brand new but it is not working.

**Comment by sinsin91** [comment]
me too

**Comment by janpio** [comment]
Please both of you post the _complete_ output you are getting when running fastlane.

**Comment by sinsin91** [comment]
I had resolved it by adding another signing provision profile to my custom SDK.

**Comment by ashfurrow** [comment]
@sinsin91 Could you expand on that a little bit? What do you mean, "adding another signing provision profile to my custom SDK"?

**Comment by ashfurrow** [comment]
@ntk860 This seems similar to a problem I'm seeing too, but just on CI: https://github.com/fastlane/fastlane/issues/14798

**Comment by matthewlloyd** [comment]
I'm seeing the same. The relevant portion of the fastlane output is below. Curiously, it only seems to happen the first time each time I do a release - rerunning the fastlane usually fixes it.

```
[17:03:46]: ▸ Signing /Users/<redacted>/Library/Developer/Xcode/DerivedData/Runner-dfnmvnajlcptzrezueyrxucxfnnt/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks/App.framework
[17:03:47]: ▸ Running script 'Thin Binary'
[17:03:47]: ▸ Running script '[CP] Embed Pods Frameworks'
[17:03:52]: ▸ Signing /Users/<redacted>/Library/Developer/Xcode/DerivedData/Runner-dfnmvnajlcptzrezueyrxucxfnnt/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks/Flutter.framework
[17:03:52]: ▸ Running script '[CP] Copy Pods Resources'
[17:03:53]: ▸ Touching Runner.app
[17:03:55]: ▸ Signing /Users/<redacted>/Library/Developer/Xcode/DerivedData/Runner-dfnmvnajlcptzrezueyrxucxfnnt/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app
[17:03:56]: ▸ Touching Runner.app.dSYM
[17:03:57]: ▸ Archive Succeeded
[17:03:58]: Generated plist file with the following values:
[17:03:58]: ▸ -----------------------------------------
[17:03:58]: ▸ {
[17:03:58]: ▸   "method": "app-store"
[17:03:58]: ▸ }
[17:03:58]: ▸ -----------------------------------------
[17:03:58]: $ /usr/bin/xcrun /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/rr/w61prq0d7jj395_p29sxh_gm0000gn/T/gym_config20190703-84937-1xtq47e.plist' -archivePath /Users/<redacted>/Library/Developer/Xcode/Archives/2019-07-03/Runner\ 2019-07-03\ 17.00.28.xcarchive -exportPath '/var/folders/rr/w61prq0d7jj395_p29sxh_gm0000gn/T/gym_output20190703-84937-1nj97yl'
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/rr/w61prq0d7jj395_p29sxh_gm0000gn/T/gym_config20190703-84937-1xtq47e.plist -archivePath '/Users/<redacted>/Library/Developer/Xcode/Archives/2019-07-03/Runner 2019-07-03 17.00.28.xcarchive' -exportPath /var/folders/rr/w61prq0d7jj395_p29sxh_gm0000gn/T/gym_output20190703-84937-1nj97yl
2019-07-03 17:03:58.705 xcodebuild[88406:14243962] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/rr/w61prq0d7jj395_p29sxh_gm0000gn/T/Runner_2019-07-03_17-03-58.704.xcdistributionlogs'.
2019-07-03 17:03:58.732 xcodebuild[88406:14243962] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}

** EXPORT FAILED **
[17:03:58]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.126.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS12.2.sdk        |
+---------------+-------------------------+
```

**Comment by M4rcos** [comment]
Open xcode and select Generic iOS Device solved the export issue for me.

**Comment by M4rcos** [comment]
Open xcode and select Generic iOS Device and run Product > Archive solved the export issue for me.

**Comment by matthewlloyd** [comment]
I just saw this issue again yesterday. Fastlane 2.128.1.

**Comment by matthewlloyd** [comment]
I still see this issue almost daily with the latest version of fastlane.

**Comment by ashish-naik** [comment]
@matthewlloyd go to developer.apple.com and see if you haven’t accepted updated terms.  

I started getting this error today without any change in setup  and tried searching everywhere for solution.  The error message is very cryptic. I went to developer.apple.com to check if there was any issue with certificate etc and accepted the changed terms. 

I ran fastlane after that and error went away !! 

Ashish

**Comment by matthewlloyd** [comment]
Thanks Ashish, it's true that the terms need to be updated from time to time. However for me, the error in this issue is intermittent, i.e. I only see if about 50% of the time. Usually, if I rerun fastlane a couple of times over a few minutes, it will eventually clear and work. But then it will stop working again a subsequent time. This is all in a single session. So I don't think this is related to terms acceptance.

**Comment by ashish-naik** [comment]
Okay, got it.
