### ISSUE TITLE
fastlane not generating ipa and outputting "no output path received from gym" message

### ISSUE THREAD

**Issue by DavidBrunow** [fastlane/fastlane#14932]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using `gym` to create an IPA file for our iOS app we are seeing the "no output path received from gym" message. We would expect an IPA file to be created. 

<details>
  <pre> We've been using fastlane in our project for months without any issues. Right now we are making changes to our large and complicated project structure and therefore changing items in the build list of our Xcode schemes. We have a number of frameworks inside a workspace and those need to be built before our app is built. Recently we removed a framework from the list and after that change gym stopped creating the IPA. After troubleshooting for hours we found that the issue is related to the first framework in our build list -- if that framework is targeting watchOS then the IPA is not created but if the framework is targeting iOS then it is. I'd like to help resolve this issue or make the error message more helpful so others don't spend time on this -- can anyone point me to a good starting place?</pre>
</details>

**Comment by tvongeldern** [comment]
Try providing the `output_directory` field?

https://docs.fastlane.tools/actions/gym/#parameters

example:

```
gym(
      workspace: 'ios/myapp.xcworkspace',
      scheme: 'myapp',
      export_method: 'app-store',
      output_directory: 'dist/ios', <-- this guy
      clean: true
    )
```

**Comment by DavidBrunow** [comment]
Our `Fastfile` already has the `output_directory` field. The only thing that made a difference was changing the first framework in the build order.

**Comment by joshdholtz** [comment]
@DavidBrunow Heyyy 👋 Can you post what your `Fastfile` looks like? Would like see what kind of settings you are using because this seems odd

**Comment by DavidBrunow** [comment]
This is the lane that I'm running (with some small changes to remove company information):

```
platform :ios do
    desc "Create an archive using QA - iOS - Debug scheme"
    lane :create_debug_archive do
    gym(
        scheme: "QA - iOS - Debug",
        archive_path: "build/QADebug.xcarchive",
        output_directory: "build/",
        configuration: "QADebug",
        export_options: "QaDebugAdHocExportOptions.plist",
        output_name: "QA - iOS - Debug.ipa"
    )
    end
end
```
