### ISSUE TITLE
Get the URL of ipa file upleaded to fabric

### ISSUE THREAD

**Issue by MaksimLapshyn87** [fastlane/fastlane#14936]
We upload our ipa files to Fabric via fastlane.
Fastlane version - 2.101.1
Does Fastlane have functional possibility to publish url of uploaded file  to Jenkins job log (screenshot in attachment)
![fabric](https://user-images.githubusercontent.com/52031555/59906073-6bc57100-9410-11e9-9c85-29f59fb3e122.png)

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.101.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| rubyzip                   | 1.2.2        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.1        |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.8       |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.5        |
</details>

**Comment by joshdholtz** [comment]
@MaksimLapshyn87 It does not look like there is a way to currently get the published url from the `crashlytics` action. Other actions/services do allow this but it doesn't look like this was built into `crashlytics`. This is probably something that we won't add since crashlytics/fabric is getting shut down in mid 2019 (now ish) - https://fabric.io/blog/the-future-of-fabric

Sorry about that and happy fastlaning 😊
