### ISSUE TITLE
Using sh to run a command

### ISSUE THREAD

**Issue by karltaylor** [fastlane/fastlane#14930]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)

### Question Subject

[sh](https://docs.fastlane.tools/actions/sh/)

#### Question Description

I am trying to implement a shell command in my lane. Running the command as such works fine:

```bash
sh('ls')
# prints directory
```

However I want to disable logs, as the [sh docs for parameters](https://docs.fastlane.tools/actions/sh/#parameters) it says you can do the following but it errors.

```bash
sh(command: "ls", log: false)
# [12:58:32]: unknown keyword: command
```

**Comment by joshdholtz** [comment]
@karltaylor That is a great find 😱 I totally knew what the problem was and I will make a PR to fix it but in the meantime you can use `sh("ls", log: false)` and that will work for you 😇

**Comment by raymondhoagland** [comment]
Am I right in thinking this also currently blocks the use of the `step_name` argument for the `sh` action?
