### ISSUE TITLE
Unable to run upload_symbols_to_crashlytics due to permission

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#14934]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when i run fastlane action upload_symbols_to_crashlytics on my machine it throws permission issue for this action however it works fine for other actions

Error: .../ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `[]': [!] Operation not permitted - ./Pictures/Photos Library.photoslibrary (Errno::EPERM)

##### Command executed

fastlane action upload_symbols_to_crashlytics

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ..../ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `[]': [!] Operation not permitted - ./Pictures/Photos Library.photoslibrary (Errno::EPERM) </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.5       |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.9.0        |
| unicode-display_width     | 1.6.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| google-cloud-env          | 1.2.0        |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.1       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

**Comment by joshdholtz** [comment]
@pavm035 Heyyy 👋 Can you please post your `Fastfile` if you have one and/or what command you are using to run this? Its hard to debug without that information 😊

**Comment by pavm035** [comment]
@joshdholtz Here is the command for uploading dSYM in fastfile

    upload_symbols_to_crashlytics(
      {
        dsym_path: ENV["DSYM_OUTPUT_PATH"],
        gsp_path: "./firebase/GoogleService-Info-enterprise.plist"
      }
    )

**Comment by janpio** [comment]
Any idea where `./Pictures/Photos Library.photoslibrary` could come from @pavm035? That looks really strange.

Please post the complete output you are getting and your complete `Fastfile` land that is being executed.

**Comment by pavm035** [comment]
@janpio I have no idea how this is trying to access `./Pictures/Photos Library.photoslibrary` but it works fine for other fastlane commands, BTW i'm not executing this action in fastfile it's generic action exectuting outside as mentioned here.
https://docs.fastlane.tools/actions/upload_symbols_to_crashlytics/

`❯ fastlane run upload_symbols_to_crashlytics dsym_paths:"<dSYM>" gsp: <plist_path>
[✔] 🚀
[09:11:17]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:11:19]: -------------------------------------------
[09:11:19]: --- Step: upload_symbols_to_crashlytics ---
[09:11:19]: -------------------------------------------
[09:11:19]: You passed invalid parameters to 'upload_symbols_to_crashlytics'.
[09:11:19]: Check out the error below and available options by running `fastlane action upload_symbols_to_crashlytics`

Looking for related GitHub issues on fastlane/fastlane...

➡️  Unable to run upload_symbols_to_crashlytics due to permission
    https://github.com/fastlane/fastlane/issues/14934 [open] 3 💬
    5 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	23: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	22: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	21: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	20: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	19: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1@global/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
	18: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	17: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	15: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 9: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 8: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 7: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 6: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 5: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 4: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 3: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:241:in `block (2 levels) in execute_action'
	 2: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	 1: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `available_options'
/Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `[]': [!] Operation not permitted - ./Pictures/Photos Library.photoslibrary (Errno::EPERM)`

**Comment by janpio** [comment]
This is a very different error than what you posted before:

> [09:11:19]: You passed invalid parameters to 'upload_symbols_to_crashlytics'.

In your command you have to replace `gsp` with `gsp_path`. Also, if you only supply one dSYM, the correct parameter is called `dsym_path` without the final `s`.

**Comment by pavm035** [comment]
@janpio  Oh sorry forgot to mention before this time i just tested with default gsp from current folder, but originally i posted all parameters in both case error remains same

**Comment by janpio** [comment]
Then please post the output of a run that shows your actual error and doesn't use a parameter that doesn't exist.

**Comment by pavm035** [comment]
@janpio Looks still it's same
`❯ Sudo fastlane run upload_symbols_to_crashlytics dsym_path:"/Users/kumar.pavan/Downloads/iOSIchiba660003.app.dSYM.zip" gsp_path:"/Users/kumar.pavan/Downloads/GoogleService-Info.plist"
[✔] 🚀
[18:17:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:17:05]: -------------------------------------------
[18:17:05]: --- Step: upload_symbols_to_crashlytics ---
[18:17:05]: -------------------------------------------
[18:17:05]: You passed invalid parameters to 'upload_symbols_to_crashlytics'.
[18:17:05]: Check out the error below and available options by running `fastlane action upload_symbols_to_crashlytics`

Looking for related GitHub issues on fastlane/fastlane...

➡️  Unable to run upload_symbols_to_crashlytics due to permission
    https://github.com/fastlane/fastlane/issues/14934 [open] 7 💬
    an hour ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	23: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	22: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	21: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	20: from /Users/kumar.pavan/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	19: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
	18: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	17: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	15: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 9: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 8: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 7: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 6: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 5: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 4: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 3: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:241:in `block (2 levels) in execute_action'
	 2: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	 1: from /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `available_options'
/Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `[]': [!] Operation not permitted - ./Pictures/Photos Library.photoslibrary (Errno::EPERM)`

**Comment by janpio** [comment]
Ok, I have to apologize: I didn't see the actual error you were talking about because I was 
confused by `You passed invalid parameters to 'upload_symbols_to_crashlytics'.` which was a red herring. 

Here is the real problem that you mentioned in the title:

> ```
> /Users/kumar.pavan/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:154:in `[]': [!] Operation not permitted - ./Pictures/Photos Library.photoslibrary (Errno::EPERM)`
> ```

This comes from:
https://github.com/fastlane/fastlane/blob/242b2bd059b7dee8912ff6210c903ee92092f0f4/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb#L154

(Unrelated ping @mollyIV: Look at how this combines `ENV` and `SharedValues`!?)

Do you have `ENV['DSYM_OUTPUT_PATH']` set? What value does it have? 
What directory are you running the command in?

In general it is a bit surprising that the default value of the option is evaluated, although you explicitly set a value.

Can you try running this via a lane with options to the action instead of parameters to `fastlane run`?

**Comment by pavm035** [comment]
@janpio Aha in jenkins we set `ENV['DSYM_OUTPUT_PATH']` but when i run manually i didn't set that value but i wonder why this command looking for photo library inside? but sure will i try to run this lane and let you know thanks for your help

**Comment by janpio** [comment]
> Aha in jenkins we set `ENV['DSYM_OUTPUT_PATH']` but when i run manually i didn't set that value but i wonder why this command looking for photo library inside?

When the ENV var is not set, it runs `(Dir["./**/*.dSYM"] + Dir["./**/*.dSYM.zip"]).sort_by`. Depending on where you run this command, it might possibly try to access the folder `./Pictures/Photos Library.photoslibrary` - for example if you run it in `/` or `/Picture` - hence my question were you are running the command.

If this is the case, you will get the same error running the command via a lane that uses the action - but still definitely worth to try out so we can get to the base of this problem.

**Comment by pavm035** [comment]
@janpio You are right when i run this command in home directory i'm having above error but when i run inside my project folder it just works fine i guess you suspected right, but still it looks strange fastlane to throw this weird error when that env is not set, but thanks a lot for your kind help

**Comment by janpio** [comment]
The error not being shown when the ENV var is set is just a lucky side effect, not intended behavior. We might have to look into skipping folders with permission problems somehow - but I am not sure how.

**Comment by pavm035** [comment]
Thank you
