### ISSUE TITLE
Invalid option creating custom fastlane action

### ISSUE THREAD

**Issue by cianiandreadev** [fastlane/fastlane#14947]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Custom Action `ConfigItem` not reading parameter

#### Question Description
I am trying to create a custom action for a specific case I need (#14870) and I would like to have an argument `--readonly` giving the possibility to avoid destructive operations in the script.

I checked how this is implement in `match` and I ended up with the following configuration:

```ruby
def self.available_options
# Define all options your action supports. 
  [
  FastlaneCore::ConfigItem.new(key: :readonly,
       env_name: "FL_PROVSCAN_READONLY",
       description: "Run script without destructive operations",
       is_string: false,
       default_value: false)
  ]
end
```
I also tried to add the parameters `short_option: '--readonly'` but in every case when I run the command `fastlane run provscan --readonly` I have the following error:

`invalid option: --readonly`

Am I doing something wrong?

I just want to say that I had never wrote Ruby or extended Fastlane before, so I may miss some basics.

**Comment by janpio** [comment]
The `--readonly` you see from `match` is different the one you would use on an action: https://docs.fastlane.tools/actions/match/#new-machine

Note that the use as `--readonly` is used in the command `fastlane match development --readonly` which runs a sub CLI of fastlane called `match`. When used on the action `match`, you actually supply `readonly: true` as a key value pair.

If you want to execute an action directly via the command line, you use `run` (as you described) but have to provide the options/parameters in a different way: https://docs.fastlane.tools/actions/match/#cli `fastlane run match parameter1:"value1" parameter2:"value2"`

So for you, it would probably be `fastlane run provscan readonly:true` or similar.

**Comment by cianiandreadev** [comment]
All clear.

Thanks @janpio

**Comment by janpio** [comment]
Yay, easy fixes are the best.
