### ISSUE TITLE
Plugin how to configure Fastlane.swift

### ISSUE THREAD

**Issue by errorUserInfo** [fastlane/fastlane#14940]
![屏幕快照 2019-06-22 下午4 31 04](https://user-images.githubusercontent.com/13981183/59962260-7e759e00-9515-11e9-8c59-3c84ec1e8a8c.png)
How to transfer Swift?

**Comment by joshdholtz** [comment]
@errorUserInfo Third party plugins are currently not support in `Fastlane.swift` but it is on a set of features that I would like to include soon 😊

**Comment by philCc** [comment]
@errorUserInfo 

```swift
let command = RubyCommand(
	commandID: "", methodName: "pgyer", className: nil, 
	args: [
		RubyCommand.Argument(name: "api_key", value: "xxxx"),
		RubyCommand.Argument(name: "user_key", value: "xxx"),
		RubyCommand.Argument(name: "ipa", value: "xxx"),
		RubyCommand.Argument(name: "update_description", value: "xxx"),
	])
_ = runner.executeCommand(command)
```
// reference: ${project_dir}/fastlane/Fastlane.swift
