### ISSUE TITLE
 Can I resign ipa under the Linux system without codesign and security?

### ISSUE THREAD

**Issue by Mosquito1123** [fastlane/fastlane#14942]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by janpio** [comment]
No. The resign action(s) from fastlane use `security` as can be seen here: https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/resign.rb
