### ISSUE TITLE
[scan] Specify iOS versions

### ISSUE THREAD

**Issue by SpacyRicochet** [fastlane/fastlane#14953]
### Feature Request
Add the option to specify the iOS versions that the tests should be run for. For example;

```bash
fastlane scan devices=["iPhone 5s", "iPhone 7"] ios_versions=["11.3", 12.0"]
# The above would run the tests for;
# iPhone 5s, iOS 11.3
# iPhone 5s, iOS 12.0
# iPhone 7, iOS 11.3
# iPhone 7, iOS 12.0
```

#### Motivation Behind Feature
Certain test setups feature taking automated snapshots, which can vary between iOS versions. Other setups attempt to test code that is available or unavailable on certain iOS versions. 

In order to accommodate this, one can use the singular `destination` parameter, but we are apparently discouraged from doing this. More so, it isn't possible to select multiple destinations, so one would have to run the same action twice multiple times with different destinations, instead of letting `scan` figure this out.

This would be analogous to the `devices` parameter, which allows the user to specify devices.

#### Feature Description

* Add a `ios_versions` parameter to scan, which allows the user to set one or more iOS versions to run the tests on; e.g. `fastlane scan ios_versions=["12.0", "11.0"]`.
* Scan would check against the available simulators, and create a set of destinations that satisfy the versions (and devices, if also specified).
  * It should skip version + device combinations that are not available, with a warning.
  * If no destinations are available, scan should exit with an error.

#### Alternatives or Workarounds
Specify the scan action multiple, with different destinations.

**Comment by Speakus** [comment]
As workaround it is possible to use xcode_select() before and after running tests (before to set desired xcode with default desired simulator and after to set back to default xcode).
In my case I build with one Xcode and test builded code with another.
