### ISSUE TITLE
Ignore certain folders on init and print ios sub-directory

### ISSUE THREAD

**Issue by topalavlad** [fastlane/fastlane#14954]
#### Motivation Behind Feature
Calling `fastlane init` on a ionic project fails because of `node_modules` and `plugins` folders that contain plugins suitable for ios because they contain files with `xcworkspace` or other xCode extensions.

The error message is very generic and doesn't say what triggered the error (even if using --verbose):
```
It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
Please `cd` into the directory of the intended Xcode project you wish to use.

[!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again
```
#### Feature Description

1. Add sub-directory(s) to error message 
2. Ignore `node_modules` by default and maybe `plugins` also if it's at root level
3. Add a `fastlane init --force` option that only looks at top level

#### Alternatives or Workarounds
Delete `node_modules` and `plugins`, run `fastlane init` and reinstall dependencies

**Comment by janpio** [comment]
Thanks for your report.

> 1. Add sub-directory(s) to error message

That definitely makes sense.

> 2\. Ignore `node_modules` by default and maybe `plugins` also if it's at root level

`node_modules` I agree, `plugins` is pretty specific. Works for Cordova apps, but I am not sure we might not break some other scenarios here?

>     3\. Add a `fastlane init --force` option that only looks at top level

Why does `--force` mean "only top level" here?

In general it would make sense if `fastlane init` could handle Cordova projects a bit smarter by looking for e.g. `config.xml` and similar identifiers.

**Comment by topalavlad** [comment]
I was thinking that in this case `--force` means that fastlane should not look through sub-directories, only the directory you're running in. Maybe `--force` is not right here. It might be something like recursive=false

**Comment by janpio** [comment]
Yes, that sounds more sensible. But to be honest, `fastlane init` is more a convenience feature than an essential part, so I don't think it might be worth implement this really. It "just" creates some initial files.
