### ISSUE TITLE
upload_to_testflight with specified account

### ISSUE THREAD

**Issue by jasperjorna** [fastlane/fastlane#14950]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Upload to testflight

First of all, am I correct in thinking that uploading to testflight is only possible nowadays with a 2-factor enabled account?

I'm trying to upload to testflight with the `upload_to_testflight` tool, but I'm struggling to get i  working. Currently I'm using an Store Connect account without 2-factor for most of the lanes, with the credentials specified in `FASTLANE_USER` and `FASTLANE_PASSWORD`.

However, I have a different user for the `upload_to_testflight` lane, with credentials set in `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` in order to use the  application specific password.

It doesn't seem to pick this up correctly though, and errors out with `[!] The request could not be completed because:
	Invalid username and password combination. Used 'other_user@with_2_factor.com' as the username.`

Is this the correct approach?

```
upload_to_testflight(
  username: 'other_user@with_2_factor.com',
  skip_waiting_for_build_processing: true
)
```

**Comment by janpio** [comment]
> First of all, am I correct in thinking that uploading to testflight is only possible nowadays with a 2-factor enabled account?

No, under specific circumstances you can also use an Application Specific Password: https://docs.fastlane.tools/actions/pilot/#use-an-application-specific-password-to-upload

Having set the `FASTLANE_USER` and `FASTLANE_PASSWORD` variables might confuse the `upload_to_testflight` though - let me know if the error persists after you followed the documentation link I posted above and I can start investigating deeper if necessary.

**Comment by joshdholtz** [comment]
@jasperjorna Your use case should totally work. What I would maybe try as well is printing out your environment variables before calling `upload_to_testflight` to make sure they are being set/loaded correctly.

```rb
puts "FASTLANE_USER: #{ENV["FASTLANE_USER"]}"
puts "FASTLANE_PASSWORD: #{ENV["FASTLANE_PASSWORD"]}"
puts "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: #{ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]}"
```

**But,** now that I think about it... `upload_to_testflight` might be trying to use `other_user@with_2_factor.com` with your other password in `FASTLANE_PASSWORD`. You want me to reset `FASTLANE_PASSWORD` before calling `upload_to_testflight` with the correct password for your `other_user@with_2_factor.com` account.

Hopefully I'm interpreting what you are explaining correctly 😊

**Comment by janpio** [comment]
> **But,** now that I think about it... `upload_to_testflight` might be trying to use `other_user@with_2_factor.com` with your other password in `FASTLANE_PASSWORD`. You want me to reset `FASTLANE_PASSWORD` before calling `upload_to_testflight` with the correct password for your `other_user@with_2_factor.com` account.

Exactly what I was thinking of. Maybe it "prefers" `FASTLANE_PASSWORD` over `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` in the code. Which wouldn't be too surprising, how should it know which one to use when both are set...

**Comment by jasperjorna** [comment]
Thanks for the quick replies!

I tried to set `FASTLANE_PASSWORD` to the one corresponding to the `other_user@with_2_factor.com` account just before calling `upload_to_testflight`, but I seems like it ignores the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` and prompts for the 2-factor code.

Additionally, I tried setting `ENV['FASTLANE_PASSWORD'] = nil` just before `upload_to_testflight`, but then it just prompts me for the password.

**Comment by janpio** [comment]
Did you follow an read the link I posted? https://docs.fastlane.tools/actions/pilot/#use-an-application-specific-password-to-upload Only under specific circumstances it can depend on only the app specific password, otherwise it has to do a normal login first which will trigger 2FA if it is enabled for your account.

**Comment by joshdholtz** [comment]
@jasperjorna Adding on to what @janpio posted above, you need to set the `apple_id` option (which is the ID that appears in App Store Connect) for it to not prompt you for 2FA

**Comment by jasperjorna** [comment]
@joshdholtz @janpio I tried to implement it according to the docs as follows:
```
private_lane :reset_pass do
  ENV['FASTLANE_USER'] = nil
  ENV['FASTLANE_PASSWORD'] = nil
end
```

```
reset_pass
upload_to_testflight(
  apple_id: '123456789',
  skip_waiting_for_build_processing: true
)
```

I'm getting the error:
```
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Username: 
```

**Comment by janpio** [comment]
Small misunderstanding here I guess, you still need a username either via `FASTLANE_USER` or the `username` option of `upload_to_testflight`.

**Comment by jasperjorna** [comment]
I managed to get it working with the code as follows:

```
private_lane :reset_pass do
  ENV['FASTLANE_USER'] = nil
  ENV['FASTLANE_PASSWORD'] = nil
end
```
```
reset_pass
upload_to_testflight(
  username: 'other_user@with_2_factor.com',
  app_identifier: 'com.foo.bar',
  apple_id: '123456789',
  skip_waiting_for_build_processing: true
)
```

Thanks for helping out!
