### ISSUE TITLE
IntelliJ and fastlane integration

### ISSUE THREAD

**Issue by OleksandrKucherenko** [fastlane/fastlane#14961]
# Question Subject
Installed IntelliJ IDEA Ultimate 2019.1 with Ruby support

## Question Description
Is it possible to configure intellij to recognize fastlane script as a ruby properly?

expected:
- all actions should be properly mapped to the source code, Cmd+Click should navigate developer to implementation
- private_lane and lane declaration should be recognized by IDE as methods
- debugger support
- (Optional) Support unit tests for fastlane script

the max I achieve so far is - https://medium.com/@olku/fastlane-setup-in-intellij-enterprise-ffb56051065a

**Comment by janpio** [comment]
That's an interesting question. 

I have no idea, but my guess would be that the way fastlane works does not make it easy for any IDE to properly connect the action names to the code that is executed behind the scenes automatically - there is quite a lot of magic involved to go from the "method" call to the executed code.
