### ISSUE TITLE
sh: read command won't get terminated

### ISSUE THREAD

**Issue by xingheng** [fastlane/fastlane#14960]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My custom bash script gets stuck when executing to `read` shell command, it seems to receive my input text but I don't know how to terminate the input, it works well in general bash script. It  should be escaped by `Enter` in general, I tried `Ctrl + D` with no luck, either.

##### Command executed
In my Fastlane file,
```
sh('bash', '../path/to/custom_script.sh')
```

##### Complete output when running fastlane, including the stack trace and command used
Since I don't know how to get the stuck error, the following stack are reported when pressing `Ctrl + C`.
```
ERROR [2019-06-27 11:17:22.79]: fastlane finished with errors
Traceback (most recent call last):
	28: from /usr/local/bin/fastlane:23:in `<main>'
	27: from /usr/local/bin/fastlane:23:in `load'
	26: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
	25: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	24: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	23: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	22: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	21: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	20: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	10: from Fastfile:53:in `block (2 levels) in parsing_binding'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/fast_file.rb:186:in `sh'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/fast_file.rb:191:in `sh'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/fast_file.rb:192:in `block in sh'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	 3: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
	 2: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `block in sh_control_output'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `each': Interrupt
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Archive the product for app-store"
  lane :store do
    build_ios_app(
      workspace: "youyue.xcworkspace",
      configuration: "Release-AppStore",
      scheme: "youyue-appstore",
      silent: true,
      clean: true,
      output_directory: "build",
      output_name: "youyue-appstore.ipa",
      export_options: {
        method: "app-store"
      }
    )
  end

  desc "Archive the product for enterprise"
  lane :enterprise do
    build_ios_app(
      workspace: "youyue.xcworkspace",
      configuration: "Release-Enterprise",
      scheme: "youyue-enterprise",
      silent: true,
      clean: true,
      output_directory: "build",
      output_name: "youyue-enterprise.ipa",
      export_options: {
        method: "enterprise"
      }
    )
  end

  desc "Upload the selected dSYM file to Bugly"
  lane :dsym do
    sh('bash', '../bugly/upload.sh')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.126.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.10.0       |
| unicode-display_width     | 1.6.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.64.0       |
| unf_ext                   | 0.0.7.6      |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.4        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| os                        | 1.0.1        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
</details>

*generated on:* **2019-06-27**
</details>

**Comment by xingheng** [comment]
BTW, I found the `BUNDLER_ORIG_PATH` environment variable is only available in fastlane sh context, it's ok for me to make compatibility for fastlane in my custom script base on that variable, but which command should I use to replace the builtin `read` command usage.

**Comment by janpio** [comment]
I think @joshdholtz had some recent experience with `sh` only being usable for output, not for input, correct?
