### ISSUE TITLE
Frameit for Android

### ISSUE THREAD

**Issue by milhauscz** [fastlane/fastlane#14968]
#### Motivation Behind Feature
Fastlane Frameit currently supports Apple devices. A lot of Android developers would benefit from Android support. The changes required to support Android are relatively easy and all the code handling adding frames, texts etc. can be easily reused. ([Based on discussion in issue 14796](https://github.com/fastlane/fastlane/issues/14796)).

#### Feature Description
The new feature would simply add support for selected Android devices, such as Samsung Galaxy SX, Nexus devices and Google Pixels.

I have already started familiarizing myself with Ruby and Frameit source code and created a new standalone [Frameit_android module in my fork](https://github.com/milhauscz/fastlane/tree/master/frameit_android) (with its own gemfile so it can be built and installed separately). Please note this is only an experimental module where I wanted to test some stuff and the final feature can be done completely differently, based on the discussion in this thread. In this module I modified several files to add the Android support, namely:
- frames_generator/Rakefile - added Android colors and changed filters to filter out "Apple" devices; the generated files are in a separate repository https://github.com/milhauscz/frameit-android-frames
- app_screenshot_android.rb - modified copy of app_screenshot.rb from the deliver module, where I added selected Android devices, refactored the code a bit, modified the calculate_screen_size which takes into account resolution, file name and a hardcoded device priority
- device_types.rb - added Android colors
- frame_downloader.rb - changed URL to download frames from the repository above
- screenshot.rb - use app_screenshot_android.rb instead of deliver module
- template_finder.rb - use default color if frame with the selected color not found

So besides adding Android devices together with their resolutions and default colors, the most important change is in determining which frame to add around a screenshot. Originally only resolution was considered. The new code also considers screenshot file name if multiple devices have the same resolution and in case the file name doesn't contain useful information, a hardcoded priority is used (presuming e. g. user would prefer Google Pixel device frame to Nokia frame). Of course I am open to other ideas.

Now I would like to discuss with you how to proceed in case of implementing this feature in the main fastlane repo. The main question is whether to have two separate actions for Apple and Android, or whether to modify the current module to add the support for Android. Since the docs state that no new actions are accepted, I guess the feature should be rather added to the current frameit action. In this case some extra command option / setting would be necessary so that Frameit will know whether it should prefer Apple or Android frames.

**Comment by janpio** [comment]
Awesome!

Some thoughts:

---

> Now I would like to discuss with you how to proceed in case of implementing this feature in the main fastlane repo. 

This question has 2 aspects: 
a) Where should the code live? And: 
b) How do users use the new logic?

For a) it is quite clear: In the folder of the `frameit` tool
For b) we can discuss if the existing action should be modified or if a new action should be added.

> Since the docs state that no new actions are accepted, I guess the feature should be rather added to the current frameit action.

That is a very soft limitation by the way - if it makes sense to add a new action, we can do that.

> In this case some extra command option / setting would be necessary so that Frameit will know whether it should prefer Apple or Android frames.

What are you thinking about here? What could possible indicators be to choose Android instead of iOS? (Probably: location, filename, size, "platform" of the lane - correct?)

---

One important thing to note is that the implementation should work both via actions and also the `fastlane frameit` CLI that exists. 
---

Where do the frames come from? Are they under a license that will let us include them in one of our repos?

**Comment by milhauscz** [comment]
Thanks for the feedback. I've noticed that for example regarding automatic upload to the Play Stores, there are two different actions: _deliver_ for iOS and _supply_ for Android. But that is probably because these two stores have completely different API etc. I think for _frameit_ we can go for a single action where we add an extra Android command. 

****

My idea for those indicators is:

1. Check the resolution (the same as now)
2. Check current custom commands and options (e. g. force_device_type, use_legacy_iphone5s etc., still the same)
3. Check screenshot file name whether it contains one of the matching devices
4. Add new options: ios and android, in case one of them is used, filter only those devices
5. Check a hardcoded device priority and choose the highest one ([you can see this idea here](https://github.com/milhauscz/fastlane/blob/master/frameit_android/lib/frameit_android/app_screenshot_android.rb) - each supported device has an assigned priority, e. g. we assume user would prefer a newer device to an older one etc.)

What do you think? Another aspect to consider is whether we use the "ios" option as default so that the current iOS users do not need to change anything, or whether default means searching both Android and iOS frames.

Next problem is that the _frameit_ depends on _deliver_, whose app_screenshot.rb contains an enum of supported devices. Since we want to add the support for Android and _deliver_ is exclusive for Apple, I suggest we decouple them.

> Where do the frames come from? Are they under a license that will let us include them in one of our repos?

The frames come from the same source as Apple frames, i. e. Facebook device frames. No need to consider the licence :-)

I will start working on the integration and a pull request now so that later we can continue the discussion on something specific and all the diff is clearly visible. Thanks.

**Comment by janpio** [comment]
> What do you think? Another aspect to consider is whether we use the "ios" option as default so that the current iOS users do not need to change anything, or whether default means searching both Android and iOS frames.

We require pretty much all additional to be backwards compatible, so that option would have to default to `ios` or at least always end up with iOS framings for existing setups out there.

**Comment by milhauscz** [comment]
Successfully created PRs:
- [Add Android support to fastlane frameit](https://github.com/fastlane/fastlane/pull/15087)
- [Add Android device frames](https://github.com/fastlane/frameit-frames/pull/10)

**Comment by mollyIV** [comment]
@fastlane-bot The PRs are in-review 😉

**Comment by BalkiX** [comment]
any update on this? still in review?

**Comment by janoist1** [comment]
+1

**Comment by RicardoBelchior** [comment]
+1

**Comment by BalkiX** [comment]
@janpio, @mollyIV: in review for more than half a year?

**Comment by graux** [comment]
+1
Please review/implement this feature, it would be a great help.

**Comment by rogerluan** [comment]
Closing this stale issue as https://github.com/fastlane/fastlane/pull/15087 got merged and released a long time ago 😊
