### ISSUE TITLE
SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER matcher doesn't work for Belarus 

### ISSUE THREAD

**Issue by atitovdev** [fastlane/fastlane#14969]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Looks like matcher works incorrectly with Belarus phone numbers
Valid format is +375 (it's country code) ** (GSM carrier code - 2 digits) ******* (actual phone number - 7 digits) 

##### Complete output when running fastlane, including the stack trace and command used

```
Environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` is set, automatically requesting 2FA token via SMS to that number
SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER = +375 ** ***-**-**   (This format is shown in AppleID)

Looking for related GitHub issues on fastlane/fastlane...

[!] The request could not be completed because:

Could not find a matching phone number to +375**#####80 in [{"numberWithDialCode"=>"+375 • ••• •••-••-59", "pushMode"=>"sms", "obfuscatedNumber"=>"• ••• •••-••-59", "id"=>1}, {"numberWithDialCode"=>"+375 • ••• •••-••-80", "pushMode"=>"sms", "obfuscatedNumber"=>"• ••• •••-••-80", "id"=>2}].
Make sure your environment variable is set to the correct phone number.
If it is, please open an issue at https://github.com/fastlane/fastlane/issues/new and include this output so we can fix our matcher. Thanks.
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.2                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.2 (18C54)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.126.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-07-02**
</details>

**Comment by janpio** [comment]
Hi @atitovdev, that's very possible - it was very difficult to find enough test data.

Could you please post again what value the ENV var is set to and the full output you are getting - just replace the actual numerals (that you of course don't want to show) with `0` (instead of `##`, `**` or similar) this time so I know exactly what is defined and output how.

Thanks.

**Comment by atitovdev** [comment]
Hi @janpio.
ENV var is "+375 00 000-00-00"

Full Output:
Available session is not valid any more. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account 'myemail@email.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` is set, automatically requesting 2FA token via SMS to that number
SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER = +375 00 000-00-00

/Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:229:in `phone_id_from_number':  (Spaceship::Tunes::Error)
Could not find a matching phone number to +375000000000 in [{"numberWithDialCode"=>"+375 • ••• •••-••-59", "pushMode"=>"sms", "obfuscatedNumber"=>"• ••• •••-••-59", "id"=>1}, {"numberWithDialCode"=>"+375 • ••• •••-••-80", "pushMode"=>"sms", "obfuscatedNumber"=>"• ••• •••-••-80", "id"=>2}].
Make sure your environment variable is set to the correct phone number.
If it is, please open an issue at https://github.com/fastlane/fastlane/issues/new and include this output so we can fix our matcher. Thanks.
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:135:in `handle_two_factor'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/client.rb:770:in `do_login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/client.rb:384:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from ./generate_certificates.rb:194:in `block in <main>'
	from ./generate_certificates.rb:129:in `each'
	from ./generate_certificates.rb:129:in `<main>'

**Comment by janpio** [comment]
Thanks, got it.

Usually the masked phone number (`+375 • ••• •••-••-80`) being returned from Apple either is a direct match to the actual number or has one more `•` than there are real numbers in the phone number. In your case, it seems there are always _two_ more `•` in the masked number - so our current regex doesn't match.

I will create a Pull Request to relax that for one more character, shouldn't have any negative side effects.
