### ISSUE TITLE
Create "appstore" alias to "app-store" option for export_method in gym.

### ISSUE THREAD

**Issue by Katsz** [fastlane/fastlane#14971]
### Feature Request
Create "appstore" alias to "app-store" option for `export_method` in `gym`.
#### Motivation Behind Feature
When you are using same Fastfile in multiple projects (as I do) where some of them are distributed through enterprise program when others are regular appstore ones its quite a hassle to manage which fastlane method takes "app-store" and which takes "appstore" string (as an certificate type or export method).

#### Feature Description
As neither gym takes "appstore" as valid export_method parameter, nor match does with "app-store" I am proposing to add "appstore" alias to gym. Not the other way around, because match uses `type` as substring in environmental variable, i.e. 
```ruby
ENV["sigh_#{bundle_identifier}_#{sign_type}_profile-path"]
```
As current workaround I use 
```ruby
# Fastfile 
sign_type = "app-store"
sign_type_escaping = sign_type.dup.sub!("-", "")
<...>
match(type: sign_type_escaping, <...>)
<...>
gym(export_method: sign_type, <...>)
```
As for my knowledge there are no drawbacks if it will be implemented as follows 
```ruby
# Somewhere in gym arguments handler
export_method = options[:export_method]
if export_method == "appstore"
   export_method = "app-store"
end
```

**Comment by janpio** [comment]
I guess this is (historically) because the underlying tool behind `gym` expect this exact string as a param. But we should be able to change that and output a warning or note so the users becomes aware.
