### ISSUE TITLE
Spaceship::Portal raising UnexpectedResponse instead of ProgramLicenseAgreementUpdated

### ISSUE THREAD

**Issue by salmanasiddiqui** [fastlane/fastlane#14973]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using `Spaceship::Portal`, it is raising `Spaceship::UnexpectedResponse` exception if there are pending agreements instead of `Spaceship::ProgramLicenseAgreementUpdated`.

The reason behind that is, the code:
https://github.com/fastlane/fastlane/blob/b4f34772f48e5ad17604e831192b2157af3a2d5b/spaceship/lib/spaceship/client.rb#L741-L743
is looking for `Program License Agreement` in `resultString` field, while the error message is in `userString`. Error I get:
```
Spaceship::UnexpectedResponse ({
  "responseId"=>"78ad8f20-7806-4afb-9130-1d6c276068a0",
  "resultCode"=>4550,
  "resultString"=>"Access Unavailable",
  "userString"=>"You currently don't have access to this membership resource. To resolve this issue, your team's Account Holder, John Doe, must agree to the latest Program License Agreement.",
  "creationTimestamp"=>"2019-07-02T19:34:13Z",
  "protocolVersion"=>"QH65B2",
  "userLocale"=>"en_US",
  "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/listAppIds.action",
  "httpCode"=>200
})
```

##### Command executed

```
bundle console
require 'spaceship'
Spaceship.login
Spaceship::Portal.client.team_id = team_id
Spaceship::Portal::App.find('com.company.appid')
```

**Comment by max-ott** [comment]
Please check the error message. If you don’t have access to program resources it looks like you cannot execute that command.

**Comment by salmanasiddiqui** [comment]
i have updated my post to include all commands i am running to reproduce this issue

**Comment by max-ott** [comment]
Should be related to https://github.com/fastlane/fastlane/issues/14880#issuecomment-509367895 Can we close this?

**Comment by salmanasiddiqui** [comment]
I dont think this is related to that.

**Comment by fullsailor** [comment]
Agreed, this is a different issue. As said in the original post, the code only looks at `resultString`, but the response from the API that includes "Program License Agreement" is in `userString`.

**Comment by alif-bae** [comment]
Would appreciate if we can reopen discussion on this as this bug is still prevalent. So far i've had to patch `Spaceship::Client.detect_most_common_errors_and_raise_exceptions(body)` with the suggested fix by @salmanasiddiqui to be able to raise the appropriate `ProgramLicenseAgreementUpdated` exception when there are pending agreements.

**Comment by max-ott** [comment]
Make a pull request with your patch, so we can review it and integrate it.

**Comment by alif-bae** [comment]
@max-ott here's the pull request: https://github.com/fastlane/fastlane/pull/15193
