### ISSUE TITLE
@fastlane-bot should link to "contribution guides" in stale issues comment

### ISSUE THREAD

**Issue by mollyIV** [fastlane/fastlane#14979]
#### Motivation Behind Feature

Nowadays, when a bot adds a comment to [the stale issues](https://github.com/fastlane/issue-bot/blob/ae3bf592ecfdd236971256c0f4a9edd2be5a3589/bot.rb#L303-L304), most of the time the issue is closed a few days after that by the bot. Adding link to "contribution guides" in the comment would suggest that the best way to get the issue done is by opening a PR. It might encourage new contributors to work on the project. 

#### Feature Description

Feature is inspired by @rally25rs comment in https://github.com/yarnpkg/yarn/issues/7110#issuecomment-473467670. 

The idea is modify a bot's message about the idle issues to include a kindly nudge to contribute. A sentence or two would do 💪 

As an example, here is the message that [`gatsbyjs`](https://github.com/gatsbyjs) implemented for their bot: https://github.com/gatsbyjs/peril-gatsbyjs/pull/87

> As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](${CONTRIBUTION_GUIDE_LINK}) for more information about opening PRs, triaging issues, and contributing!

**Suggested change:**

>There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
>
>Please make sure to update to the latest fastlane version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
>
>Kindly reminder: contributions are always welcome, so check out CONTRIBUTING.md for more information on how to help with fastlane and feel free to tackle this issue yourself 💪 

Please share your ideas about the message 🙏

**Comment by joshdholtz** [comment]
@mollyIV I really like this idea 👍 Maybe a small adjustment like 👇 otherwise its 💯

>Friendly reminder: contributions are always welcome! Check out CONTRIBUTING.md for more information on how to help with _fastlane_ and feel free to tackle this issue yourself 💪

**Comment by mollyIV** [comment]
https://github.com/fastlane/issue-bot/pull/66 🎁 🙇
