### ISSUE TITLE
 Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?

### ISSUE THREAD

**Issue by srashish** [fastlane/fastlane#14974]
I've having fastlane folder is able to run fastlane match development and fastlane match appstore but receiving this error while running bundle exec fastlane $FASTLANE ios beta on circleci.
 What else do I need to configure in order to make this work?

Output of the error:-

[12:32:24]: All required keys, certificates and provisioning profiles are installed 🙌
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [⠦] 🚀 [✔] 🚀 
[12:32:27]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlain Android screengrab. Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14869 [open] 4 💬
    2 weeks ago

➡️  FastLane 2.124 FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14835 [open] 4 💬
    2 weeks ago

➡️  Supply isn't working on CI with Google auth .p12 files
    https://github.com/fastlane/fastlane/issues/14128 [closed] 2 💬
    20 Apr 2019

and 36 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:133:in `confirm'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:343:in `ensure_fastfile'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
Exited with code 1

**Comment by max-ott** [comment]
How can we help you? There is no real question here.

**Comment by srashish** [comment]
I've having fastlane folder is able to run fastlane match development and fastlane match appstore but receiving this error while running bundle exec fastlane $FASTLANE ios beta on circleci.

**Comment by srashish** [comment]
> How can we help you? There is no real question here.

I've having fastlane folder is able to run fastlane match development and fastlane match appstore but receiving this error while running bundle exec fastlane $FASTLANE ios beta on circleci.

**Comment by max-ott** [comment]
Please do not delete the issue template. For getting started on fastlane check out https://docs.fastlane.tools/getting-started/ios/setup/ and https://docs.fastlane.tools/best-practices/continuous-integration/circle-ci/ for CircleCI setup

The error message should be pretty self-explanatory.

**Comment by srashish** [comment]
> Please do not delete the issue template. For getting started on fastlane check out https://docs.fastlane.tools/getting-started/ios/setup/ and https://docs.fastlane.tools/best-practices/continuous-integration/circle-ci/ for CircleCI setup
> 
> The error message should be pretty self-explanatory.

I've already followed the tutorial and was able to run fastlane match development and fastlane match appstore successfully, only getting such error with bundle exec fastlane $FASTLANE ios beta command

**Comment by janpio** [comment]
Please create a new issue using an appropriate issue template, so we have all the information required to understand your problem. Thanks.
