### ISSUE TITLE
[IOS] If app was bundled via Fastlane, it crash on startup 

### ISSUE THREAD

**Issue by xstable** [fastlane/fastlane#14983]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Question about build-issues with fastlane

#### Question Description
I run my fastlane and all working like expected. At least the App is uploaded to the Apple-Store and I'm able to download it via Testflight.
But if I start the App, it crashed with an error like: 

> You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.crashlytics(). Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added „pod 'undefined'“ to your Podfile

If I bundle the App via XCode it works at my local device... even If i do `archive` in XCode and deploy it to the app-store, load it from there and run the app... all working well.

But only If I use Fastlane to deploy, the app crash immediately after startup.

Here is the cut from my fastfile: 
```

  lane :deploy_internal do |options|
    git_pull
    ensure_git_status_clean
    get_certificates           # invokes cert - must be installed locally in your mac-keychain
    get_provisioning_profile   # invokes sigh - must be installed locally in your mac-keychain

    if options[:version] == "minor" || options[:version] == "major"
      puts options[:version]
      bumpVersion(version: options[:version])
    else
      bumpVersion(version: "patch")
    end
	increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: ENV["XCODEPROJ"]
  	)
	build_app(
	  scheme: "MyNiceApp",
	  workspace: ENV["XCWORKSPACE"],
	  include_symbols: true,
	  include_bitcode: true
	)
    upload_to_testflight(skip_waiting_for_build_processing: true)
    refresh_dsyms
    commit_version_bump(message: 'Bump build IOS', xcodeproj: ENV["XCODEPROJ"])
    push_to_git_remote
  end
end
```

BTW: If I bundle on XCode, I use the same Scheme: `MyNiceApp`.

Might the issue depend on build_app, or upload_to_testflight parameters?

**Comment by janpio** [comment]
What output are you getting when running your lane?
Please also see what @fastlane-bot posted.

**Comment by mrvisser** [comment]
I experienced a similar issue where I would archive and distribute to the app store with xcode and it worked fine, but distributing through fastlane would result in the app crashing during startup.

I have a watchOS companion app and as a result I have 2 separate schemes: one for the iPhone app and the Watch app. I would normally use the watchOS scheme to archive and distribute, however when I initialized fastlane in the project, it chose the iphone scheme to archive and distribute, which had a problem.

So check your Fastfile and look at what scheme it is using:

`build_app(workspace: "MyApp.xcworkspace", scheme: "MyApp")`

... and try to Archive and Distribute with _that_ scheme through xcode and that version might crash the same way as the fastlane version.

So you can either change your Fastfile to point to the right scheme, or fix the scheme that Fastfile chose, but at least this will eliminate fastlane as a variable 😅

**Comment by rogerluan** [comment]
Very interesting scenario  @mrvisser thanks for sharing. Any clue why building & archiving for watchOS is the right choice here? Is this still the case as of Xcode 12? 🤔

**Comment by mrvisser** [comment]
I'm not sure which is the "right" scheme for archiving an iOS app with a watch companion, they both appear to do the same thing when it comes to archiving.

I just actually had a misconfiguration in my iPhone app scheme that caused an issue. Once I knew it wasn't fastlane at fault I managed to track down the issue in my iPhone app scheme (the Archive task in the scheme had "Debug" build configuration instead of "Release").

**Comment by rogerluan** [comment]
Got it! Thanks for the explanation @mrvisser 😊 that makes sense!
