### ISSUE TITLE
fastlane crashes on CircleCI

### ISSUE THREAD

**Issue by srashish** [fastlane/fastlane#14987]
Whenever I run fastlane init on CircleCI it crashes. It works perfectly fine on my local machine but facing troubles on circleci pipeline.

`/Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:133:in `confirm'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:343:in `ensure_fastfile'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'`

**Comment by max-ott** [comment]
Could you please include all the required information for the issue template? Did you already check out https://docs.fastlane.tools/best-practices/continuous-integration/circle-ci/ ?

**Comment by srashish** [comment]
> Could you please include all the required information for the issue template? Did you already check out https://docs.fastlane.tools/best-practices/continuous-integration/circle-ci/ ?

Yes I went through all the documentations.

**Comment by janpio** [comment]
Please open a new issue where you don't delete the issue template but fill the information we require to be able to help you. Thanks.
