### ISSUE TITLE
get_provisioning_profile not working from Jenkins

### ISSUE THREAD

**Issue by ranksahoo** [fastlane/fastlane#14989]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

I am using fastlane from Jenkins. I am trying to create new app at app store and try to create required provisional for new app.
Here are actions:
- Create new app at app, it is working
- Create bundle id and provisional profile at Apple developer account, it is working
- Download provisional profile to system, it is working
- Install  provisional profile it is not working.
I am getting error: 
security: cert import failed: write permissions error
security: Problem decoding
Error parsing provisional profile at path 

![snapshot](https://user-images.githubusercontent.com/52650652/60795872-17e5b680-a18a-11e9-913f-47609e94ecc7.png)

**Comment by janpio** [comment]
You should probably use https://docs.fastlane.tools/actions/setup_jenkins/.
