### ISSUE TITLE
Support APNs Auth Key in pem.(reopen)

### ISSUE THREAD

**Issue by Eric-NZ** [fastlane/fastlane#14999]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Hi @Eric-NZ, do you want to report a bug or suggest a new feature?

What does `Support APNs Auth Key in pem.(reopen)` refer to? What fastlane action or tool would this apply to?

**Comment by janpio** [comment]
Ping @Eric-NZ
