### ISSUE TITLE
Screengrab auto retry on error

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#14995]
### Feature Request
Add support to retry function when multiple languages are set.

#### Motivation Behind Feature

Add retry policy for screengrab when multiple languages are set on the settings, currently the script will stop on the first crash of the instrumented test, it would rather retry or skip.

#### Feature Description

```ruby
     screengrab(
        android_home: "/Users/me/Library/Android/sdk",
        test_instrumentation_runner: "androidx.test.runner.AndroidJUnitRunner",
        locales: ["en-GB", "pt-BR"], #Problem here
        ending_locale: "en-GB",
        app_package_name: packageName,
        clear_previous_screenshots: true,
        skip_open_summary: true,
        output_directory: "fastlane/fastlane/metadata",
        use_tests_in_classes: ["foo"],
        app_apk_path: "....debug.apk",
        tests_apk_path: "....debug-androidTest.apk",
        reinstall_app: false,
        specific_device: adbDevicesId,
        retry: true,
        retry_count: 10)
```

#### Alternatives or Workarounds

Multiple `screengrab` configuration is one alternative but makes the script verbose, what's the best choice for this situation?

**Comment by janpio** [comment]
> ```ruby
>         retry: true,
>         retry_count: 10)
> ```

Those are the two options your suggest to be added?

> ... or skip.

How would this be set with these options?

**Comment by ppamorim** [comment]
> Those are the two options your suggest to be added?

Yes

> How would this be set with these options?

Maybe with a `skip` flag, it will not work with `retry` is true or the retry count is bigger than the default value (0?).

**Comment by ppamorim** [comment]
This is not an issue but a suggestion.
