### ISSUE TITLE
Provide metadata to Pilot via text files

### ISSUE THREAD

**Issue by fl0cke** [fastlane/fastlane#15005]
### Feature Request

Provide metadata to Pilot via text files (similar to deliver). 

#### Motivation Behind Feature
Pilot currently lacks a way of providing metadata via text files, which leads to a lot of clutter in my Fastfiles. Also, since both pilot and deliver basically do the same (i.e. upload builds and set metadata), they should provide a similar interface to minimise developer confusion.

#### Feature Description
See https://docs.fastlane.tools/actions/deliver/#available-metadata-folder-options
for a description of this feature. Pilot should accept a `metadata_path` parameter and automatically parse the required information from the provided text files.

#### Alternatives or Workarounds
Manually parse the information from the metadata files and pass it to pilot.

**Comment by janpio** [comment]
Which of the [available parameters of `pilot`](https://docs.fastlane.tools/actions/pilot/#parameters) would be covered by that?

**Comment by fl0cke** [comment]
This is taken straight from the documentation: 
```
upload_to_testflight(
  beta_app_review_info: {
    contact_email: "email@email.com",
    contact_first_name: "Connect",
    contact_last_name: "API",
    contact_phone: "5558675309",
    demo_account_name: "demo@email.com",
    demo_account_password: "connectapi",
    notes: "this is review note for the reviewer <3 thank you for reviewing"
  },
  localized_app_info: {
    "default": {
      feedback_email: "default@email.com",
      marketing_url: "https://example.com/marketing-defafult",
      privacy_policy_url: "https://example.com/privacy-defafult",
      description: "Default description",
    },
    "en-GB": {
      feedback_email: "en-gb@email.com",
      marketing_url: "https://example.com/marketing-en-gb",
      privacy_policy_url: "https://example.com/privacy-en-gb",
      description: "en-gb description",
    }
  },
  localized_build_info: {
    "default": {
      whats_new: "Default changelog",
    },
    "en-GB": {
      whats_new: "en-gb changelog",
    }
  }
)
```
This is almost exactly the same information that is needed by Deliver. So the parameters covered by this change are `beta_app_review_info`, `localized_build_info`, and `localized_app_info`.

**Comment by janpio** [comment]
What would useful filenames be? Where could these files live?

**Comment by fl0cke** [comment]
Since the required information is basically the same, i would suggest to use the same folder structure and filenames as described in https://docs.fastlane.tools/actions/deliver/#available-metadata-folder-options.
