### ISSUE TITLE
No title provided in your Framefile.json or title.strings

### ISSUE THREAD

**Issue by shivakrishnach31** [fastlane/fastlane#15002]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have downloaded example Frameit code from fastlane github project and added set of my screenshots to the screenshots folder. Make a few changes to framefile.json. but screenshots are just added with frames, not with texts. 

##### Command executed
fastlane frameit
bundle exec fastlane frameit

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> PCHBLINGSUY01:mac chippas$ fastlane frameit --verbose
[✔] 🚀 
[14:42:11]: fastlane detected a Gemfile in the current directory
[14:42:11]: however it seems like you don't use `bundle exec`
[14:42:11]: to launch fastlane faster, please use
[14:42:11]: 
[14:42:11]: $ bundle exec fastlane frameit --verbose
[14:42:11]: 
[14:42:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb:4: warning: already initialized constant Fastlane::Actions::SharedValues::FL_CHANGELOG
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/make_changelog_from_jenkins.rb:4: warning: previous definition of FL_CHANGELOG was here
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/xcodebuild.rb:5: warning: already initialized constant Fastlane::Actions::SharedValues::XCODEBUILD_ARCHIVE
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/build_ios_app.rb:6: warning: previous definition of XCODEBUILD_ARCHIVE was here
DEBUG [2019-07-10 14:42:12.77]: Parsing config file './Framefile.json'
INFO [2019-07-10 14:42:12.77]: Using device frames version 'latest'
DEBUG [2019-07-10 14:42:12.77]: Parsing config file '/Users/chippas/Downloads/examples-master/MindNode/mac/Framefile.json'
DEBUG [2019-07-10 14:42:12.78]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-07-10 14:42:12.78]: Skipping framing of screenshot ./en-US/iPhone6-Edit_Split Port.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-07-10 14:42:12.78]: Parsing config file '/Users/chippas/Downloads/examples-master/MindNode/mac/Framefile.json'
DEBUG [2019-07-10 14:42:12.79]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-07-10 14:42:12.79]: Skipping framing of screenshot ./en-US/iPhone6-Recording Port.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-07-10 14:42:12.80]: Parsing config file '/Users/chippas/Downloads/examples-master/MindNode/mac/Framefile.json'
DEBUG [2019-07-10 14:42:12.81]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-07-10 14:42:12.81]: Skipping framing of screenshot ./en-US/iPhone6-MyRecordings Port.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-07-10 14:42:12.81]: Parsing config file '/Users/chippas/Downloads/examples-master/MindNode/mac/Framefile.json'
DEBUG [2019-07-10 14:42:12.82]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-07-10 14:42:12.82]: Skipping framing of screenshot ./en-US/iPhone6-Mic Setup Port.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-07-10 14:42:12.82]: Parsing config file '/Users/chippas/Downloads/examples-master/MindNode/mac/Framefile.json'
DEBUG [2019-07-10 14:42:12.83]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-07-10 14:42:12.83]: Skipping framing of screenshot ./en-US/iPhone6-Edit_Trim Port.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-07-10 14:42:12.83]: Parsing config file '/Users/chippas/Downloads/examples-master/MindNode/mac/Framefile.json'
DEBUG [2019-07-10 14:42:12.85]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-07-10 14:42:12.85]: Skipping framing of screenshot ./en-US/iPhone6-Now playing DetailView Port.png.  No title provided in your Framefile.json or title.strings.</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| faraday                   | 0.15.4       |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.64.0       |
| rubyzip                   | 1.2.3        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| googleauth                | 0.6.7        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| faraday_middleware        | 0.13.1       |
| signet                    | 0.11.0       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| fastimage                 | 2.1.5        |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2019.0331  |
</details>

*generated on:* **2019-07-10**
</details></pre>
</details>

My Framefile:
```
{
  "default": {
    "keyword": {
      "font": "./fonts/Calibri.ttf"
    },
    "title": {
      "font": "./fonts/calibrii.ttf",
      "color": "#545454"
    },
    "background": "background.jpg",
    "padding": 0,
    "offset": {
      "offset": "+676+479",
      "titleHeight": 320
    }
  },


  "data": [
    {
      "filter": "Brainstorming",
      "keyword": {
        "color": "#d21559"
      }
    },
    {
      "filter": "Organizing",
      "keyword": {
        "color": "#feb909"
      }
    },
    {
      "filter": "Sharing",
      "keyword": {
        "color": "#aa4dbc"
      }
    },
    {
      "filter": "Styling",
      "keyword": {
        "color": "#31bb48"
      },
      "offset": {
        "offset": "+390+366",
        "width": 2095
      }
    }
  ]
}
```

Keyword.strings file:

```
"Brainstorming" = "BRAINSTORMING";

"Organizing" = "ORGANIZING";

"Sharing" = "SHARING";

"Styling" = "STYLING";
```

title.strings file:

```
"Brainstorming" = "Let Your Ideas Grow";

"Organizing" = "Think Content, Not Layout";

"Sharing" = "Spread Your Ideas Easily";

"Styling" = "Say It Your Way";
```

**Comment by janpio** [comment]
> INFO [2019-07-10 14:42:12.85]: Skipping framing of screenshot ./en-US/iPhone6-Now playing DetailView Port.png.  No title provided in your Framefile.json or title.strings.

My guess is that none of the `filter` values you have in your `Framefile` apply to this filename `iPhone6-Now playing DetailView Port.png`, thus you have no title for that screenshot. If you change your `filter` values to match your screenshot, that should do it.
