### ISSUE TITLE
[pilot] Add support for delivering existing builds to external testers

### ISSUE THREAD

**Issue by fl0cke** [fastlane/fastlane#15006]
### Feature Request

Add support for delivering existing builds to Pilot via a `build_number` parameter.

#### Motivation Behind Feature
Using pilot to distribute a TestFlight build to external testers always selects the latest one, which might not be the desired behaviour. For example, in our CI pipeline every development build is automatically made available to internal testers, which quickly leads to a situation where the build that we want to make available as beta is a few versions behind.

#### Feature Description
Add a `build_number` parameter to Pilot (similar to Deliver).
This should not trigger a new upload, but instead use an existing build for actions like setting the metadata and distributing to external testers.

#### Alternatives or Workarounds
There is currently no workaround.

**Comment by janpio** [comment]
Makes sense.

Could you post an example of a `pilot` call that would use this new parameter?

**Comment by fl0cke** [comment]
Here you go:

`fastlane pilot distribute --build_number 10 --distribute_external true -g "Team1" -w "Changelog"`

This command would require build number 10 to already be present in testflight and distribute it to external testers in "Team1" with the changelog "Changelog".

**Comment by janpio** [comment]
Should this also be usable with the `pilot`/`upload_to_testflight` actions somehow?

**Comment by fl0cke** [comment]
That would be quite useful. Here is an example lane:

```
lane :beta do
  upload_to_testflight (
    build_number: 10,
    distribute_external: true,
    notify_external_testers: true,
    groups: ["Team1"],
  )
end
```

This would basically skip the upload, fetch build number 10 and jump right to the internal distribute action.

**Comment by robertherber** [comment]
Was just looking for this! My usecase is to upload - then add a git tag for the build - and then distribute the build. 

Right now adding the tag takes longer than necessary since it requires waiting for the processing to complete for releasing a new beta.

**Comment by awgeorge** [comment]
Sounds like: #12984
