### ISSUE TITLE
@fastlane-bot should not close issues that are assigned

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15009]
When an issue is assigned to a contributor, it doesn't make sense to just close it.

**Comment by janpio** [comment]
Instead, it could post a new kind of comment that @ mentions the assigned person and asks them to take care of the issue (close if done, unassign if not working on it any more etc)

**Comment by mollyIV** [comment]
@janpio @fastlane-bot I believe we are not done here 😉

**Comment by janpio** [comment]
q.e.d ;)
