### ISSUE TITLE
@fastlane-bot could also update linked issues when a PR is released

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15001]
Currently @fastlane-bot already posts a comment to a PR thread when its changes are released. This could theoretically also be done in issue threads that are referenced in the PR description via `closes #123` - then all the users that commented on the issue would also get a notification about the release and be motivated to try it. 

We could also add some wording that tells them to maybe report success or failures so we get some verification.

**Comment by janpio** [comment]
This would replace issues like this: https://github.com/fastlane/fastlane/issues/15007#issuecomment-510507783

**Comment by mollyIV** [comment]
I will be happy to tackle this one if you do not mind 💪

**Comment by janpio** [comment]
I created this issue especially for you 🙈

**Comment by mollyIV** [comment]
https://github.com/fastlane/issue-bot/pull/67 :gift: :wink:
