### ISSUE TITLE
Provisioning Profile update fails if it's already available in the Developer Program

### ISSUE THREAD

**Issue by kristinagenova** [fastlane/fastlane#15004]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
STR
1. Have an iOS app with 2 existing provisioning profiles in developer portal
2. Sign an iOS version

Expected
App gets signed

Actual
Provisioning profile update fails with

  <pre> 
[Error message: 
[31m
[!] Apple provided the following error info:
	There were errors in the data supplied. Please correct and re-submit.
	Multiple profiles found with the name 'appNameHere InHouse'.  Please remove the duplicate profiles and try again.

] </pre>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
What fastlane action or tool are you taking about?
What command are you executing?
What (complete!) output are you getting?
What is your `fastlane env` information?
