### ISSUE TITLE
upload_to_app_store takes very long time

### ISSUE THREAD

**Issue by prgorasiya** [fastlane/fastlane#15018]
```
lane :release do
    # sync_code_signing(type: "appstore")
    #capture_screenshots
    build_app(
	scheme: "Driver",
	export_method: "app-store",
	output_directory: "/Users/paras/Desktop",
	output_name: "Driver.ipa"
    )
    upload_to_app_store(
	force: true,
	skip_screenshots: true,
	skip_metadata: true,
	reject_if_possible: true,
	submit_for_review: true,
	precheck_include_in_app_purchases: false,
	run_precheck_before_submit: false
    )
    slack(message: "Successfully Uploaded Ryde Driver App to AppStore🚀🚀!!")
    # frame_screenshots
  end
```

I cant figure out whether its an actual issue or some configuration issue!
Fastlane takes much more time than uploading an app directly from Xcode.
It exports ipa successfully and when its starts to upload it to itunesconnect it takes like 20-25 minutes from there.

I have similar kind of fast lane environment for my other iOS app and it also takes longer than Xcode.

Anybody please help me here to understand why its taking too long time.

Thanks

**Comment by lexusilia** [comment]
If you set 'submit_for_review' fastlane script waits when build processed by Apple. Try to set this parameter 'false' and check again.

**Comment by janpio** [comment]
Fastlane uses other methods to upload to the App Store, and depending on your location that might have different upload performance than uploading from Xcode directly. Not much we can do about that unfortunately.

**Comment by prgorasiya** [comment]
@lexusilia If I set that variable to false I will have to manually submit for review which I dont want to do.
Is there any other way?

**Comment by prgorasiya** [comment]
@janpio If i remember correctly it was working fine with a few versions back.

**Comment by janpio** [comment]
This has nothing to do with versions, but that Apple currently has slower upload times for these services. Nothing was changed in fastlane regarding the app upload for ages.

**Comment by prgorasiya** [comment]
@janpio But it doesn't explain why I am able to upload from Xcode quickly as compared to significantly longer time with fastlane!
I suspect there's something wrong with my fast file or system configuration?

**Comment by prgorasiya** [comment]
@lexusilia I even tried with "submit_for_review = false" but its still taking the same time

**Comment by janpio** [comment]
Yes it does:

> Fastlane uses other methods to upload to the App Store

Uploading with iTunes Transporter manually you would have the same (non)performance.

**Comment by ppamorim** [comment]
I noticed this too, in the past the upload was 8 min, but not the similar binary takes about 25min (ipa files is the same). I think it's something on Apple's side. My network uploads at 15mb/s but the transfer is stuck around 500kb/s-1mb/s.

**Comment by prgorasiya** [comment]
@ppamorim I also have same ipa file size as before and even though my internet is gigabit speed every time my upload takes much longer than before OR direct upload from Xcode. Its making my a bit furious.

**Comment by ppamorim** [comment]
@prgorasiya It's taking about 900 to 1100 seconds to upload a 518mb IPA file, which the speed is about 450-600kb/s. I keeps like this for the entire time.

**Comment by ppamorim** [comment]
This is stopping me from work since I need to leave my machine offside while the script runs, I need to upload 8-10 IPAs per run, which just the upload process takes about 10.000 seconds (almost 3 hours to upload my apps).

**Comment by prgorasiya** [comment]
My issue is similar but not too much like yours.
So I still suspect there is some issue with the script which causes the longer time in uploading ipa to itunes connect.
Any help from fastlane team would be appreciated.
Thanks

**Comment by janpio** [comment]
Fastlane is doing nothing special when calling iTunes Transporter. Any slowdowns are caused by something between your iTunes Transporter and Apple as far as we know.

**Comment by pcholberg** [comment]
After bunch of tests I changed transfer protocol from DAV to Aspera and upload speed increased dramatically. 
You can try this line to fastfile before `deliver` (`upload_to_appstore`) command call
`ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t Aspera'`
Or `ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t Signiant'` for Signiant protocol

**Comment by ppamorim** [comment]
@pcholberg Thank you, do you prefer to use Aspera or Signiant?

**Comment by pcholberg** [comment]
@ppamorim in my case Aspera was faster in 3x times compared with Signiant and 13x faster compared with DAV. But I tried only few times, so in other environment values may be different.

**Comment by ppamorim** [comment]
@pcholberg Thank you, I will test too soon.

**Comment by prgorasiya** [comment]
Thanks @pcholberg I will also give it a try.

**Comment by janpio** [comment]
If this turns out to work for many people, we will have to take another look at this: https://github.com/fastlane/fastlane/blob/d7e02e48e74c754d9d9194025815324d7380a479/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L151-L161

**Comment by alexmngn** [comment]
We're limited to using DAV in our company due to firewall restrictions. Do we have an idea what is causing this sudden upload speed decrease? It used to take us about 2-3 minutes per upload and now we're around 12-13 minutes per upload

**Comment by janpio** [comment]
No idea, but nothing on fastlane side and probably also not on iTunes Transporter client - most probably something in the routing from your machine to Apple's upload infrastructure. Super hard to debug :/

**Comment by prgorasiya** [comment]
@pcholberg @janpio After trying several times I can say that using `ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t Aspera'` worked for me. Now it takes about 4mins for the upload process to finish, but I get this error for one of my app
```
[Transporter Error Output]: The session's status is FAILED and the error description is 'Failed to open TCP connection for SSH (44)'
[Transporter Error Output]: The session's status is FAILED and the error description is 'failed to authenticate (19)'
```
and this error 
```
[Transporter Error Output]: The session's status is FAILED and the error description is 'failed to authenticate (19)'
```
 for my other app, but fastlane finishes successfully.

If I use `ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t Signiant'` it takes a little longer time for upload process to finish.

**Comment by janpio** [comment]
Thanks for reporting back these results - this is really one of those "we have to try it, to understand it" situations.

**Comment by prgorasiya** [comment]
@janpio Totally agree with you. Any pointers on why I see those errors?

**Comment by janpio** [comment]
Unfortunately not the slightest idea. There might be a bad server in Apple's rotation and you are hitting it.

**Comment by prgorasiya** [comment]
But the strange thing is I am getting this error every time and in the end it finished successfully, though.

**Comment by janpio** [comment]
Oh, then I misunderstood. 

That doesn't really make sense. Apple 🤷‍♀ 
Can you post the complete output?

**Comment by prgorasiya** [comment]
I will post it soon.
