### ISSUE TITLE
Crash running fastlane snapshot helper from Jenkins shell script

### ISSUE THREAD

**Issue by jltx** [fastlane/fastlane#15019]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to run 

>fastlane snapshot helper 

as part of an iOS build script, so the snapshot helper will be updated every time. It works fine when run outside of jenkins on a normal command prompt. I've also tried running it like

 `echo "y" | fastlane snapshot update`

to automatically enter a yes response at the prompt it shows, but still get the same error. 
Please note, when searching existing tickets there are others which show the same error but they are all related to different commands, and the suggested fixes do not apply to fastlane snapshot update. 

##### Command executed

`fastlane snapshot update`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> [SimpleTestBuild] $ /bin/bash -l /var/folders/2m/t6261sj54p74dm_kk7fnyp3w0000gp/T/jenkins6833972574748240224.sh
[07:38:32]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[07:38:33]: Found the following SnapshotHelper:
[07:38:33]: 	./AMPApp/AMPAppUITests/SnapshotHelper.swift
[07:38:33]: [33mAre you sure you want to automatically update the helpers listed above?[0m
[07:38:33]: This will overwrite all its content with the latest code.
[07:38:33]: The underlying API will not change. You can always migrate manually by looking at
[07:38:33]: https://github.com/fastlane/fastlane/blob/master/snapshot/lib/assets/SnapshotHelper.swift
[07:38:33]: [33mOverwrite configuration files?[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mFastlain Android screengrab. Could not retrieve response as fastlane runs in non-interactive mode[0m
    https://github.com/fastlane/fastlane/issues/14869 [[31mopen[0m] 4 💬
    3 weeks ago

➡️  [33mFastLane 2.124 FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode[0m
    https://github.com/fastlane/fastlane/issues/14835 [[31mopen[0m] 4 💬
    3 weeks ago

➡️  [33m Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?[0m
    https://github.com/fastlane/fastlane/issues/14974 [[32mclosed[0m] 5 💬
    a week ago

and 39 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [31m[!] Could not retrieve response as fastlane runs in non-interactive mode[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:133:in `confirm'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/snapshot/lib/snapshot/update.rb:25:in `update'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/snapshot/lib/snapshot/commands_generator.rb:62:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/snapshot/lib/snapshot/commands_generator.rb:104:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/snapshot/lib/snapshot/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre> [07:38:36]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 2.9.0        |
| io-console                | 0.4.5        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-07-12**</pre>
</details>

**Comment by janpio** [comment]
Possible that nobody tried to run this on CI yet.

This is the code for the confirmation: https://github.com/fastlane/fastlane/blob/5780dae27dd17e51f06e069a7ecaaa04271ba203/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L132-L135
https://github.com/fastlane/fastlane/blob/5780dae27dd17e51f06e069a7ecaaa04271ba203/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L152-L156
https://github.com/fastlane/fastlane/blob/5780dae27dd17e51f06e069a7ecaaa04271ba203/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L120-L125

So either `$stdout.isatty == false` or `Helper.ci?` trigger this to crash as designed.

Not sure what the workaround is here...

**Comment by janpio** [comment]
We could probably introduce a `-y` or `-force` to `fastlane snapshot update` by adding it here: https://github.com/fastlane/fastlane/blob/5780dae27dd17e51f06e069a7ecaaa04271ba203/snapshot/lib/snapshot/update.rb#L25
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/update.rb

**Comment by jltx** [comment]
This is still an issue for us - our Jenkins build breaks every time an update is needed for SnapshotHelper

**Comment by janpio** [comment]
We're happy to review any PR that adds some of this functionality.
