### ISSUE TITLE
cannnot upload and take long time

### ISSUE THREAD

**Issue by qoli** [fastlane/fastlane#15025]
### Question Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

This problem has been going on for a week. It can be successfully uploaded with Xcode's Upload tool.

##### Fastlane Config
```
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh("open","./changelog.txt")
    xcode_select("/Applications/Xcode.app")
    # xcode_select("/Applications/Xcode-beta.app")
    increment_build_number(xcodeproj: "dailyVerse.xcodeproj")
    build_app(workspace: "dailyVerse.xcworkspace", scheme: "dailyVerse", export_xcargs: "-allowProvisioningUpdates")
    changelog = File.read("./changelog.txt")
    upload_to_testflight(
      changelog: changelog,
      distribute_external: true,
      groups: "Open Beta"
      )
  end

  desc "Push a new release build to the App Store"
  lane :store do
    xcode_select("/Applications/Xcode.app")
    increment_build_number(xcodeproj: "dailyVerse.xcodeproj")
    build_app(workspace: "dailyVerse.xcworkspace", scheme: "dailyVerse", export_xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      force: true
    )
  end
  
end
```

```
[14:07:37]: Successfully exported and compressed dSYM file
[14:07:37]: Successfully exported and signed the ipa file:
[14:07:37]: /Users/qoli/Documents/Xcode/dailyVerse/dailyVerse.ipa
[14:07:37]: ----------------------------------
[14:07:37]: --- Step: upload_to_testflight ---
[14:07:37]: ----------------------------------
[14:07:38]: Login to App Store Connect (llqoli@gmail.com)
[14:07:41]: Login successful
[14:07:43]: Ready to upload new build to TestFlight (App: 1313606731)...
[14:07:45]: Going to upload updated app to App Store Connect
[14:07:45]: This might take a few minutes. Please don't interrupt the script.
[14:41:52]: [Transporter Error Output]: An error occurred while uploading the package: 1313606731.itmsp.
[14:41:52]: [Transporter Error Output]: An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
[14:41:58]: Transporter transfer failed.
[14:41:58]: 
[14:41:58]: An error occurred while uploading the package: 1313606731.itmsp.
An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
[14:41:58]: [iTMSTransporter] [2019-07-13 14:41:58 CST] <main> DBG-X: Apple's web service operation return value:

[14:41:58]: [iTMSTransporter] [2019-07-13 14:41:58 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false

[14:41:58]: [iTMSTransporter] [2019-07-13 14:41:58 CST] <main> DBG-X:   parameter SessionExpiration = 2019-07-17T06:41:56.779Z

[14:41:58]: [iTMSTransporter] [2019-07-13 14:41:58 CST] <main> DBG-X:   parameter Success = true

[14:41:58]: [iTMSTransporter] [2019-07-13 14:41:58 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}

[14:41:58]: [iTMSTransporter] 

[14:41:58]: [iTMSTransporter] 

[14:41:58]: [iTMSTransporter] 

[14:41:58]: [iTMSTransporter] Package Summary:

[14:41:58]: [iTMSTransporter]  

[14:41:58]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[14:41:58]: [iTMSTransporter] 	/var/folders/xn/hc2_m1vn715fb2559rsfyhmr0000gn/T/d20190713-27582-k7aj3q/1313606731.itmsp - Error Messages:

[14:41:58]: [iTMSTransporter] 		An error occurred while uploading the package: 1313606731.itmsp.

[14:41:58]: [iTMSTransporter] 		An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.

[14:41:58]: [iTMSTransporter] [2019-07-13 14:41:58 CST] <main> DBG-X: Returning 1

[14:41:58]: iTunes Transporter output above ^
[14:41:58]: An error occurred while uploading the package: 1313606731.itmsp.
An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
\nAn exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.5                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.21.0 (Apple Git-120)               |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.14.5 (18F132)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 11.0                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh("open","./changelog.txt")
    xcode_select("/Applications/Xcode.app")
    # xcode_select("/Applications/Xcode-beta.app")
    increment_build_number(xcodeproj: "dailyVerse.xcodeproj")
    build_app(workspace: "dailyVerse.xcworkspace", scheme: "dailyVerse", export_xcargs: "-allowProvisioningUpdates")
    changelog = File.read("./changelog.txt")
    upload_to_testflight(
      changelog: changelog,
      distribute_external: true,
      groups: "Open Beta"
      )
  end

  desc "Push a new release build to the App Store"
  lane :store do
    xcode_select("/Applications/Xcode.app")
    increment_build_number(xcodeproj: "dailyVerse.xcodeproj")
    build_app(workspace: "dailyVerse.xcworkspace", scheme: "dailyVerse", export_xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      force: true
    )
  end
  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.qoli.dailyVerse") # The bundle identifier of your app
apple_id("llqoli@gmail.com") # Your Apple email address

itc_team_id("118880701") # App Store Connect Team ID
team_id("WQY45CL427") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-07-13**
</details>

**Comment by janpio** [comment]
You can try to set this environment variable, similar to described here: https://docs.fastlane.tools/actions/deliver/#firewall-issues (but not run `deliver` afterwards, but your normal lane)

**Comment by qoli** [comment]
@janpio 
I add `ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'` in my fastfile and try again.

it still tell me:

```
[00:07:13]: Successfully exported and compressed dSYM file
[00:07:13]: Successfully exported and signed the ipa file:
[00:07:13]: /Users/qoli/Documents/Xcode/dailyVerse/dailyVerse.ipa
[00:07:13]: ----------------------------------
[00:07:13]: --- Step: upload_to_testflight ---
[00:07:13]: ----------------------------------
[00:07:13]: Login to App Store Connect (llqoli@gmail.com)
Available session is not valid any more. Continuing with normal login.
[00:07:21]: Login successful
[00:07:23]: Ready to upload new build to TestFlight (App: 1313606731)...
[00:07:24]: Going to upload updated app to App Store Connect
[00:07:24]: This might take a few minutes. Please don't interrupt the script.
[00:37:45]: [Transporter Error Output]: An error occurred while uploading the package: 1313606731.itmsp.
[00:37:45]: [Transporter Error Output]: An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
[00:37:47]: Transporter transfer failed.
[00:37:47]: 
[00:37:47]: An error occurred while uploading the package: 1313606731.itmsp.
An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
[00:37:48]: [iTMSTransporter] [2019-07-14 00:37:47 CST] <main> DBG-X: Apple's web service operation return value:

[00:37:48]: [iTMSTransporter] [2019-07-14 00:37:47 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false

[00:37:48]: [iTMSTransporter] [2019-07-14 00:37:47 CST] <main> DBG-X:   parameter SessionExpiration = 2019-07-17T16:37:46.584Z

[00:37:48]: [iTMSTransporter] [2019-07-14 00:37:47 CST] <main> DBG-X:   parameter Success = true

[00:37:48]: [iTMSTransporter] [2019-07-14 00:37:47 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}

[00:37:48]: [iTMSTransporter] 

[00:37:48]: [iTMSTransporter] 

[00:37:48]: [iTMSTransporter] 

[00:37:48]: [iTMSTransporter] Package Summary:

[00:37:48]: [iTMSTransporter]  

[00:37:48]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[00:37:48]: [iTMSTransporter] 	/var/folders/xn/hc2_m1vn715fb2559rsfyhmr0000gn/T/d20190714-45591-odhl7o/1313606731.itmsp - Error Messages:

[00:37:48]: [iTMSTransporter] 		An error occurred while uploading the package: 1313606731.itmsp.

[00:37:48]: [iTMSTransporter] 		An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.

[00:37:48]: [iTMSTransporter] [2019-07-14 00:37:47 CST] <main> DBG-X: Returning 1

[00:37:48]: iTunes Transporter output above ^
[00:37:48]: An error occurred while uploading the package: 1313606731.itmsp.
An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
\nAn exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+--------------------+--------------------------------------+
|                       Lane Context                        |
+--------------------+--------------------------------------+
| DEFAULT_PLATFORM   | ios                                  |
| PLATFORM_NAME      | ios                                  |
| LANE_NAME          | ios beta                             |
| BUILD_NUMBER       | 47                                   |
| IPA_OUTPUT_PATH    | /Users/qoli/Documents/Xcode/dailyVe  |
|                    | rse/dailyVerse.ipa                   |
| DSYM_OUTPUT_PATH   | /Users/qoli/Documents/Xcode/dailyVe  |
|                    | rse/dailyVerse.app.dSYM.zip          |
| XCODEBUILD_ARCHIVE | /Users/qoli/Library/Developer/Xcode  |
|                    | /Archives/2019-07-14/dailyVerse      |
|                    | 2019-07-14 00.05.36.xcarchive        |
+--------------------+--------------------------------------+
[00:37:48]: Error uploading ipa file, for more information see above
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.5                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.21.0 (Apple Git-120)               |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.14.5 (18F132)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 11.0                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh("open","./changelog.txt")
    xcode_select("/Applications/Xcode.app")
    # xcode_select("/Applications/Xcode-beta.app")
    increment_build_number(xcodeproj: "dailyVerse.xcodeproj")
    build_app(workspace: "dailyVerse.xcworkspace", scheme: "dailyVerse", export_xcargs: "-allowProvisioningUpdates")
    changelog = File.read("./changelog.txt")
    upload_to_testflight(
      changelog: changelog,
      distribute_external: true,
      groups: "Open Beta"
      )
  end

  desc "Push a new release build to the App Store"
  lane :store do
    xcode_select("/Applications/Xcode.app")
    increment_build_number(xcodeproj: "dailyVerse.xcodeproj")
    build_app(workspace: "dailyVerse.xcworkspace", scheme: "dailyVerse", export_xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      force: true
    )
  end
  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.qoli.dailyVerse") # The bundle identifier of your app
apple_id("llqoli@gmail.com") # Your Apple email address

itc_team_id("118880701") # App Store Connect Team ID
team_id("WQY45CL427") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>


*generated on:* **2019-07-16**
</details>

**Comment by qoli** [comment]
if I downgraded to 2.15.1 version.

it tell me:
```
[15:49:45]: [Transporter Error Output]: An error occurred while uploading the file 4d9404c7f231968f6b35272a6fe91e9b3afb0eccc15cbd9f8616b2a690f76106.ipa.
[15:49:45]: [Transporter Error Output]: An exception has occurred: Broken pipe (Write failed)
[15:49:45]: [Transporter Error Output]: Failed to upload file: /var/folders/xn/hc2_m1vn715fb2559rsfyhmr0000gn/T/d20190716-18924-1gliw5g/1313606731.itmsp/4d9404c7f231968f6b35272a6fe91e9b3afb0eccc15cbd9f8616b2a690f76106.ipa
[15:50:37]: Transporter transfer failed.
[15:50:37]: 
[15:50:37]: An error occurred while uploading the file 4d9404c7f231968f6b35272a6fe91e9b3afb0eccc15cbd9f8616b2a690f76106.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /var/folders/xn/hc2_m1vn715fb2559rsfyhmr0000gn/T/d20190716-18924-1gliw5g/1313606731.itmsp/4d9404c7f231968f6b35272a6fe91e9b3afb0eccc15cbd9f8616b2a690f76106.ipa
```

**Comment by qoli** [comment]
Sorry. This is my IPS problem.
