### ISSUE TITLE
Promoting iOS app to App Store throws NoMethodError: [!] undefined method `candidate_builds' for nil:NilClass

### ISSUE THREAD

**Issue by fezu54** [fastlane/fastlane#15029]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When promoting our iOS App from TestFlight to the App Store it fails with 
```
bundler: failed to load command: fastlane (/Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/xetics-fusion/tracking-flutter/ios/vendor/bundle/ruby/2.6.0/bin/fastlane)
NoMethodError: [!] undefined method `candidate_builds' for nil:NilClass
```

I've checked the two issues suggested by fastlane, but it didn't helped me out:
* https://github.com/fastlane/fastlane/issues/3889
* https://github.com/fastlane/fastlane/pull/6991

The App was already published once manually to the App Store. 
I'm trying to promote the App via Gitlab-CI. It calls `:submit_review` of the following Fastfile:
```
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # This var is needed to work around proxy problems on our Gitlab instance. See https://github.com/fastlane/fastlane/issues/13572
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
    # build the binary
    gym(
      scheme: 'Release',
      export_method: 'app-store',
      export_options: { compileBitcode: false},
      output_directory: './build',
      output_name: 'app-beta'
    )
    # submit to TestFlight
    pilot(
      ipa: './build/app-beta.ipa',
      app_identifier: ENV['APP_IDENTIFIER'],
      skip_submission: false,
      changelog: ENV['CI_COMMIT_MESSAGE'],
      apple_id: ENV['APPLE_ID']
    )
  end
  desc "Promote the beta build to App Store"
  lane :submit_review do
    deliver(
      build_number: ENV['CI_PIPELINE_ID'],
      app_identifier: ENV['APP_IDENTIFIER'],
      submit_for_review: true,
      automatic_release: true,
      force: true, # This skips the HTML report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ bundle exec fastlane submit_review
[09:55:47]: -----------------------------
[09:55:47]: --- Step: update_fastlane ---
[09:55:47]: -----------------------------
[09:55:47]: Looking for updates for fastlane...
[09:55:49]: Nothing to update ✅
[09:55:49]: 
[09:55:49]: Please help us test early releases of fastlane by opting into nightly builds 🌃
[09:55:49]: Just replace your `update_fastlane` call with
[09:55:49]: 
[09:55:49]: ▸ update_fastlane(nightly: true)
[09:55:49]: 
[09:55:49]: Nightly builds are reviewed and tested just like the public releases 🚂
[09:55:49]: 
[09:55:49]: ------------------------------
[09:55:49]: --- Step: default_platform ---
[09:55:49]: ------------------------------
[09:55:49]: Driving the lane 'ios submit_review' 🚀
[09:55:49]: ---------------------
[09:55:49]: --- Step: deliver ---
[09:55:49]: ---------------------
[09:55:49]: Login to App Store Connect (user@company.com)
[09:55:51]: Login successful

+--------------------------------------+-------------------------------------------+
|                             deliver 2.127.1 Summary                              |
+--------------------------------------+-------------------------------------------+
| build_number                         | 20267                                     |
| app_identifier                       | com.company.app.identifier |
| submit_for_review                    | true                                      |
| automatic_release                    | true                                      |
| force                                | true                                      |
| skip_metadata                        | true                                      |
| skip_screenshots                     | true                                      |
| skip_binary_upload                   | true                                      |
| screenshots_path                     | ./fastlane/screenshots                    |
| metadata_path                        | ./fastlane/metadata                       |
| username                             | user@company.com                        |
| platform                             | ios                                       |
| edit_live                            | false                                     |
| use_live_version                     | false                                     |
| skip_app_version_update              | false                                     |
| overwrite_screenshots                | false                                     |
| reject_if_possible                   | false                                     |
| phased_release                       | false                                     |
| reset_ratings                        | false                                     |
| team_id                              | Team123456                                 |
| dev_portal_team_id                   | ABCDEFGHIJ                                |
| run_precheck_before_submit           | true                                      |
| precheck_default_rule_level          | warn                                      |
| individual_metadata_items            | []                                        |
| ignore_language_directory_validation | false                                     |
| precheck_include_in_app_purchases    | true                                      |
+--------------------------------------+-------------------------------------------+

[09:55:52]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[09:55:52]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+-------------------------------------------+
|                     Summary for precheck 2.127.1                     |
+--------------------------+-------------------------------------------+
| default_rule_level       | warn                                      |
| include_in_app_purchases | true                                      |
| app_identifier           | com.company.app.identifier |
| username                 | user@company.com                        |
| team_id                  | Team123456                                 |
+--------------------------+-------------------------------------------+

[09:55:52]: Checking app for precheck rule violations
[09:55:58]: Reading in-app purchases. If you have a lot, this might take a while
[09:55:58]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[09:55:58]: Done reading in-app purchases
[09:55:59]: ✅  Passed: No negative  sentiment
[09:55:59]: ✅  Passed: No placeholder text
[09:55:59]: ✅  Passed: No mentioning  competitors
[09:55:59]: ✅  Passed: No future functionality promises
[09:55:59]: ✅  Passed: No words indicating test content
[09:55:59]: ✅  Passed: No curse words
[09:55:59]: ✅  Passed: No words indicating your IAP is free
[09:55:59]: ✅  Passed: Incorrect, or missing copyright date
[09:56:01]: ✅  Passed: No broken urls
[09:56:01]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[09:56:01]: Selecting existing build-number: 20267
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios submit_review |
+------------------+-------------------+

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | update_fastlane  | 2           |
| 2    | default_platform | 0           |
| 💥   | deliver          | 12          |
+------+------------------+-------------+

[09:56:01]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Spaceship: Exception in v0.24 when calling candidate_builds
    https://github.com/fastlane/fastlane/issues/3889 [closed] 6 💬
    22 Sep 2016

➡️  Remove Shenzhen dependency
    https://github.com/fastlane/fastlane/pull/6991 [closed] 19 💬
    13 Mar 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/xetics-fusion/tracking-flutter/ios/vendor/bundle/ruby/2.6.0/bin/fastlane)
NoMethodError: [!] undefined method `candidate_builds' for nil:NilClass
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/deliver/lib/deliver/submit_for_review.rb:39:in `select_build'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/deliver/lib/deliver/runner.rb:172:in `submit_for_review'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/deliver/lib/deliver/runner.rb:50:in `run'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:42:in `block (2 levels) in parsing_binding'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-2.127.1/bin/fastlane:23:in `<top (required)>'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/gitlab-ci/builds/oNxG8gfR/0/ci/gitlab/app/ios/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre> [11:16:15]: fastlane detected a Gemfile in the current directory
[11:16:15]: however it seems like you don't use `bundle exec`
[11:16:15]: to launch fastlane faster, please use
[11:16:15]: 
[11:16:15]: $ bundle exec fastlane env
[11:16:15]: 
[11:16:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile                                                                                         
/Users/gitlab-ci/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb:4: warning: already initialized constant Fastlane::Actions::SharedValues::FL_CHANGELOG
/Users/gitlab-ci/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/make_changelog_from_jenkins.rb:4: warning: previous definition of FL_CHANGELOG was here
/Users/gitlab-ci/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/xcodebuild.rb:5: warning: already initialized constant Fastlane::Actions::SharedValues::XCODEBUILD_ARCHIVE
/Users/gitlab-ci/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/build_ios_app.rb:6: warning: previous definition of XCODEBUILD_ARCHIVE was here
[11:16:16]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # This var is needed to work around proxy problems on our Gitlab instance. See https://github.com/fastlane/fastlane/issues/13572
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
    # build the binary
    gym(
      scheme: 'Release',
      export_method: 'app-store',
      export_options: { compileBitcode: false},
      output_directory: './build',
      output_name: 'app-beta'
    )
    # submit to TestFlight
    pilot(
      ipa: './build/app-beta.ipa',
      app_identifier: ENV['APP_IDENTIFIER'],
      skip_submission: false,
      changelog: ENV['CI_COMMIT_MESSAGE'],
      apple_id: ENV['APPLE_ID']
    )
  end
  desc "Promote the beta build to App Store"
  lane :submit_review do
    deliver(
      build_number: ENV['CI_PIPELINE_ID'],
      app_identifier: ENV['APP_IDENTIFIER'],
      submit_for_review: true,
      automatic_release: true,
      force: true, # This skips the HTML report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.company.app.identifier") # The bundle identifier of your app
apple_id("user@company.com") # Your Apple email address

itc_team_id("Team123456") # App Store Connect Team ID
team_id("ABCDEFGHIJ") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.127.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-07-16**
</details>
</pre>
</details>

**Comment by janpio** [comment]
Related code is here: https://github.com/fastlane/fastlane/blob/da84b370190d75e6edcb6ae13e3e8f62e0ab354f/deliver/lib/deliver/submit_for_review.rb#L32-L39

I remember we had similar issues in the past where `v` just stayed empty :/

Just to make sure: `build-number: 20267` does exist?

**Comment by fezu54** [comment]
Hey @janpio ,
thanks for you reply. I just double checked in TestFlight. The build number is definitely there. There is already a newer version existing, but that shouldn't be a problem or? As far as I remember I got the exception also when 20267 was the latest one.

![image](https://user-images.githubusercontent.com/4998526/61519468-46765380-aa0c-11e9-8898-a2a9c63db056.png)

**Comment by simonbengtsson** [comment]
Just ran into this myself so debugged it a bit. Setting `app_version` option for deliver fixed it for us but would be nice with a better error message.

**Comment by fezu54** [comment]
@simonbengtsson Indeed, this fixed the issue. Thank you very much :slightly_smiling_face:

**Comment by janpio** [comment]
Let's keep this open as there is no error message that should probably be there. Any idea about wording @simonbengtsson?
