### ISSUE TITLE
Error `security: SecKeychainItemCopyAccess: A missing value was detected.` while running match

### ISSUE THREAD

**Issue by RetepV** [fastlane/fastlane#15028]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

While running `fastlane match appstore`, I was getting the following error:

```
security: SecKeychainItemCopyAccess: A missing value was detected.
```

Running with `--verbose`, I found the error was generated by the following call:

```
security set-key-partition-list -S apple-tool:,apple: -k [password] /Users/peter/Library/Keychains/login.keychain-db 1> /dev/null
```

After some fiddling around, I found that I needed to add an extra option `-s`.

* **I am running macOS Catalina, maybe this is now a requirement for running `security`?**

To fix this, I changed the following line in `keychain_importer.rb` from:

```
      if Helper.backticks('security -h | grep set-key-partition-list', print: false).length > 0
        command = "security set-key-partition-list"
        command << " -S apple-tool:,apple:"
        command << " -k #{keychain_password.to_s.shellescape}"
        command << " #{keychain_path.shellescape}"
        command << " 1> /dev/null" # always disable stdout. This can be very verbose, and leak potentially sensitive info
```

into:

```
      if Helper.backticks('security -h | grep set-key-partition-list', print: false).length > 0
        command = "security set-key-partition-list"
        command << " -S apple-tool:,apple:"
        command << " -s"
        command << " -k #{keychain_password.to_s.shellescape}"
        command << " #{keychain_path.shellescape}"
        command << " 1> /dev/null" # always disable stdout. This can be very verbose, and leak potentially sensitive info
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
Can you post the documentation/help of `security` on Catalina?
