### ISSUE TITLE
Difference between include_bitcode and enable_bitcode?

### ISSUE THREAD

**Issue by apanagar** [fastlane/fastlane#15020]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
For iOS, Is the `include_bitcode` different than `enable_bitcode`? I am confused what the difference here is; the only parameter I see in Xcode's build settings is `enable_bitcode` but no `include_bitcode`

**Comment by janpio** [comment]
`include_bitcode` is an option of [`build_ios_app`/`gym`](https://docs.fastlane.tools/actions/build_ios_app/) ("Should the ipa file include bitcode?"), `enable_bitcode` is not.

From looking at the code, `include_bitcode` influences if `uploadBitcode` is set in the export options.
