### ISSUE TITLE
[match] fastlane match nuke development does not delete certificates in storage

### ISSUE THREAD

**Issue by apstygo** [fastlane/fastlane#15030]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Expected: I wanted to nuke my existing Development provisioning and recreate all of that using **match** later. 
nuke failed to delete provisioning files from storage. I tried that twice, didn't work. 

##### Command executed

`fastlane match nuke development`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ➜  rubeacon-app fastlane match nuke development
[✔] 🚀
[16:03:57]: Successfully loaded '/Users/apstygo/Developer/XCodeProjects/Work-Projects/rubeacon-app/fastlane/Matchfile' 📄

+--------------+-------------------------------------------------+
|          Detected Values from './fastlane/Matchfile'           |
+--------------+-------------------------------------------------+
| git_url      | https://bitbucket.org/rubeacon/ios-certificates |
| storage_mode | git                                             |
| type         | appstore                                        |
+--------------+-------------------------------------------------+

[16:03:57]: Cloning remote git repo...
[16:03:57]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:04:08]: 🔓  Successfully decrypted certificates repo

+-----------------------+-------------------------------------------------+
|                     Summary for match nuke 2.127.1                      |
+-----------------------+-------------------------------------------------+
| type                  | appstore                                        |
| readonly              | false                                           |
| username              | diachenko.e.s@yandex.ru                         |
| team_id               | CFC5W9WZ23                                      |
| storage_mode          | git                                             |
| git_url               | https://bitbucket.org/rubeacon/ios-certificates |
| git_branch            | master                                          |
| shallow_clone         | false                                           |
| clone_branch_directly | false                                           |
| keychain_name         | login.keychain                                  |
| force                 | false                                           |
| force_for_new_devices | false                                           |
| skip_confirmation     | false                                           |
| skip_docs             | false                                           |
| platform              | ios                                             |
| verbose               | false                                           |
+-----------------------+-------------------------------------------------+

[16:04:08]: Fetching certificates and profiles...

+-----------------+------------+-------------+------------+
|        Certificates that are going to be revoked        |
+-----------------+------------+-------------+------------+
| Name            | ID         | Type        | Expires    |
+-----------------+------------+-------------+------------+
| iOS Development | 368V972Y95 | Development | 2020-07-15 |
+-----------------+------------+-------------+------------+

[16:04:15]: ---
[16:04:15]: Are you sure you want to completely delete and revoke all the
[16:04:15]: certificates and provisioning profiles listed above? (y/n)
[16:04:15]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
[16:04:15]: ---
[16:04:15]: Do you really want to nuke everything listed above? (y/n)
y
[16:04:21]: ----------------------------------
[16:04:21]: --- Revoking 1 certificates... ---
[16:04:21]: ----------------------------------
[16:04:21]: Revoking certificate 'iOS Development' (368V972Y95)...
[16:04:23]: Successfully deleted certificate
[16:04:23]: 🔒  Successfully encrypted certificates repo

[!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A501i)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.2        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| cocoapods                 | 1.7.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| cocoapods-binary          | 0.4.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.4        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| google_drive              | 3.0.3        |
| translit                  | 0.1.5        |
</details>

*generated on:* **2019-07-16**
</details> </pre>
</details>

**Comment by janpio** [comment]
That is definitely not the expected output of this command. Can you please rerun it with `--verbose` so we maybe get some additional output to understand what is going on?

**Comment by apstygo** [comment]
Sorry for the delay. Here's this command run with `--verbose`. 
```bash
➜  auto fastlane match nuke distribution --verbose
[✔] 🚀
Successfully loaded Appfile at path '/Users/apstygo/Developer/XCodeProjects/Work-Projects/auto/fastlane/Appfile'
- app_identifier: '#########'
- apple_id: '##########'
- itc_team_id: '########'
- team_id: '########'
-------
INFO [2019-07-30 21:05:41.75]: Successfully loaded '/Users/apstygo/Developer/XCodeProjects/Work-Projects/auto/fastlane/Matchfile' 📄

+--------------+-------------------------------------------------+
|          Detected Values from './fastlane/Matchfile'           |
+--------------+-------------------------------------------------+
| git_url      | https://bitbucket.org/rubeacon/ios-certificates |
| storage_mode | git                                             |
| type         | appstore                                        |
+--------------+-------------------------------------------------+

INFO [2019-07-30 21:05:41.77]: Cloning remote git repo...
INFO [2019-07-30 21:05:41.77]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2019-07-30 21:05:41.77]: $ git clone https://bitbucket.org/rubeacon/ios-certificates /var/folders/t2/w61bqrn961g0vcf9yn5kb7w80000gn/T/d20190730-48709-12fb6om
INFO [2019-07-30 21:05:41.80]: ▸ Cloning into '/var/folders/t2/w61bqrn961g0vcf9yn5kb7w80000gn/T/d20190730-48709-12fb6om'...
INFO [2019-07-30 21:05:45.06]: ▸ remote: Counting objects: 918, done.
INFO [2019-07-30 21:05:46.26]: ▸ remote: Compressing objects: 100% (775/775), done.
INFO [2019-07-30 21:05:49.07]: ▸ remote: Total 918 (delta 149), reused 0 (delta 0)
INFO [2019-07-30 21:05:49.07]: ▸ Receiving objects: 100% (918/918), 1.24 MiB | 455.00 KiB/s, done.
INFO [2019-07-30 21:05:49.08]: ▸ Resolving deltas: 100% (149/149), done.
INFO [2019-07-30 21:05:49.10]: 🔓  Successfully decrypted certificates repo

+-----------------------+-------------------------------------------------+
|                     Summary for match nuke 2.128.1                      |
+-----------------------+-------------------------------------------------+
| verbose               | true                                            |
| type                  | appstore                                        |
| readonly              | false                                           |
| username              | shishkinaleksandr92@gmail.com                   |
| team_id               | 3NR49K36QL                                      |
| storage_mode          | git                                             |
| git_url               | https://bitbucket.org/rubeacon/ios-certificates |
| git_branch            | master                                          |
| shallow_clone         | false                                           |
| clone_branch_directly | false                                           |
| keychain_name         | login.keychain                                  |
| force                 | false                                           |
| force_for_new_devices | false                                           |
| skip_confirmation     | false                                           |
| skip_docs             | false                                           |
| platform              | ios                                             |
+-----------------------+-------------------------------------------------+

INFO [2019-07-30 21:05:49.11]: Fetching certificates and profiles...
Reading keychain entry, because either user or password were empty
Loading session from '/Users/apstygo/.fastlane/spaceship/shishkinaleksandr92@gmail.com/cookie'

+------------------+------------+------------+------------+
|        Certificates that are going to be revoked        |
+------------------+------------+------------+------------+
| Name             | ID         | Type       | Expires    |
+------------------+------------+------------+------------+
| iOS Distribution | VKYPXSKPL4 | Production | 2020-04-10 |
| iOS Distribution | Y9H62JY928 | Production | 2020-07-29 |
+------------------+------------+------------+------------+

+-----------------------+------------+--------+------------------+------------+
|             Provisioning Profiles that are going to be revoked              |
+-----------------------+------------+--------+------------------+------------+
| Name                  | ID         | Status | Type             | Expires    |
+-----------------------+------------+--------+------------------+------------+
| match AppStore        | KLSXBFG6QC | Active | iOS Distribution | 2020-04-10 |
| com.shishkin.mushmula |            |        |                  |            |
+-----------------------+------------+--------+------------------+------------+

ERROR [2019-07-30 21:05:54.16]: ---
ERROR [2019-07-30 21:05:54.17]: Are you sure you want to completely delete and revoke all the
ERROR [2019-07-30 21:05:54.17]: certificates and provisioning profiles listed above? (y/n)
ERROR [2019-07-30 21:05:54.17]: Warning: By nuking distribution, both App Store and Ad Hoc profiles will be deleted
ERROR [2019-07-30 21:05:54.17]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
ERROR [2019-07-30 21:05:54.17]: ---
 [2019-07-30 21:05:54.17]: Do you really want to nuke everything listed above? (y/n)
y
INFO [2019-07-30 21:05:56.81]: -------------------------------------------
INFO [2019-07-30 21:05:56.81]: --- Deleting 1 provisioning profiles... ---
INFO [2019-07-30 21:05:56.81]: -------------------------------------------
INFO [2019-07-30 21:05:56.81]: Deleting profile 'match AppStore com.shishkin.mushmula' (KLSXBFG6QC)...
INFO [2019-07-30 21:05:59.37]: Successfully deleted profile
INFO [2019-07-30 21:05:59.37]: ----------------------------------
INFO [2019-07-30 21:05:59.37]: --- Revoking 2 certificates... ---
INFO [2019-07-30 21:05:59.37]: ----------------------------------
INFO [2019-07-30 21:05:59.37]: Revoking certificate 'iOS Distribution' (VKYPXSKPL4)...
INFO [2019-07-30 21:06:01.22]: Successfully deleted certificate
INFO [2019-07-30 21:06:01.22]: Revoking certificate 'iOS Distribution' (Y9H62JY928)...
INFO [2019-07-30 21:06:01.73]: Successfully deleted certificate
INFO [2019-07-30 21:06:01.73]: 🔒  Successfully encrypted certificates repo
bundler: failed to load command: fastlane (/Users/apstygo/.rbenv/versions/2.5.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/storage/interface.rb:81:in `block in save_changes!'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/storage/interface.rb:59:in `chdir'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/storage/interface.rb:59:in `save_changes!'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/nuke.rb:213:in `nuke_it_now!'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/nuke.rb:74:in `run'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/commands_generator.rb:179:in `block (3 levels) in run'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/commands_generator.rb:186:in `run'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/match/lib/match/commands_generator.rb:25:in `start'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/apstygo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
  /Users/apstygo/.rbenv/versions/2.5.0/bin/fastlane:23:in `load'
  /Users/apstygo/.rbenv/versions/2.5.0/bin/fastlane:23:in `<top (required)>'
```

**Comment by apstygo** [comment]
The issue is still bothering me every single time I run nuke now

**Comment by apstygo** [comment]
Is there any other way to resolve this besides just deleting the files from the repository myself?
