### ISSUE TITLE
Supply - Updating AndroidPublisher to V3

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#15037]
https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**TL;DR:** v1 and v2 won't work from Dec 1st, 2019

The issue I ran into at the moment is we are converting from APK's to AAB's slowly, and `V2` doesn't seem to have much support for AAB's (e.g.: only version codes are available in `v2`. But `v3` has the corresponding version number, release notes, etc. - `Edits.Tracks`)

Wondering what is the plan to update `fastlane` from `v2` to `v3`. Can you let me know, please? 

V3 documentation: https://developers.google.com/android-publisher/api-ref/edits

**Comment by janpio** [comment]
Someone has to implement it, then we merge and release it ;)

There has been an earlier issue at https://github.com/fastlane/fastlane/issues/14573, I did some initial investigation over there as well.

I hope to have some dedicated time for this soon, then I might tackle it. But if you want to go ahead, I would be more than happy to review a PR.

**Comment by scorpion35** [comment]
https://github.com/scorpion35/fastlane/tree/androidpublisherv3

**Comment by janpio** [comment]
<3

I assume you will create a PR when done?

**Comment by scorpion35** [comment]
> <3
> 
> I assume you will create a PR when done?

Yes! :) Making this doc to track progress - https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/androidpublisherv3_tracking.md
