### ISSUE TITLE
Unable to resolve dependencies on gem install

### ISSUE THREAD

**Issue by NoRamadon** [fastlane/fastlane#15039]
I install by gem command 'sudo gem install fastlane -NV'

but I always got error with google api client

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires google-api-client (< 0.24.0, >= 0.21.2); google-cloud-storage requires google-api-client (~> 0.26)

**Comment by janpio** [comment]
Please fill the issue template and don't just remove it - there is a reason it (and the bot reply) ask for some information. We need this to debug a problem.
