### ISSUE TITLE
--overwrite_screenshots does not work if any video preview present

### ISSUE THREAD

**Issue by namepunk** [fastlane/fastlane#15036]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I get error uploading screenshots because i have video with preview

##### Command executed
i download my screenshots using
`fastlane deliver download_screenshots --username username@company.com --app_identifier my.app.id --app_version 2.3.0 --force`

after this, i upload them using

`fastlane deliver --username username@company.com --app_identifier my.app.id --build_number 2.3.0 --force --skip_binary_upload --run_precheck_before_submit false --overwrite_screenshots`

and get error message

```
[!] The request could not be completed because:
        Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.
```

I connect to appstore and remove videos, and run upload again - it works
i upload video, and run upload screenshots again - it fails again

##### Complete output when running fastlane, including the stack trace and command used

Output
<details>

```
[10:09:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:09:30]: Login to App Store Connect (username@company.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
-------------------------------------------------------------------------------------
Password (for username@company.com): *************
[10:09:44]: Login successful

+--------------------------------------+--------------------+
|                  deliver 2.127.1 Summary                  |
+--------------------------------------+--------------------+
| username                             | username@company.com|
| app_identifier                       | my.app.id          |
| build_number                         | 2.3.0              |
| force                                | true               |
| skip_binary_upload                   | true               |
| run_precheck_before_submit           | false              |
| overwrite_screenshots                | true               |
| screenshots_path                     | ./screenshots      |
| metadata_path                        | ./metadata         |
| platform                             | ios                |
| edit_live                            | false              |
| use_live_version                     | false              |
| skip_screenshots                     | false              |
| skip_metadata                        | false              |
| skip_app_version_update              | false              |
| submit_for_review                    | false              |
| reject_if_possible                   | false              |
| automatic_release                    | false              |
| phased_release                       | false              |
| reset_ratings                        | false              |
| precheck_default_rule_level          | warn               |
| individual_metadata_items            | []                 |
| ignore_language_directory_validation | false              |
| precheck_include_in_app_purchases    | true               |
+--------------------------------------+--------------------+

[?] Uploading metadata to App Store Connect
[10:09:54]: Successfully uploaded set of metadata to App Store Connect
[10:09:56]: Starting with the upload of screenshots...
[10:09:56]: Removing all previously uploaded screenshots...
[?] Activating languages en-AU, en-CA, en-GB, en-US... Potential server error received: 'Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 2)...
[?] Activating languages en-AU, en-CA, en-GB, en-US... Potential server error received: 'Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 1)...
[?] Activating languages en-AU, en-CA, en-GB, en-US...
Looking for related GitHub issues on fastlane/fastlane...

[?] Activating languages en-AU, en-CA, en-GB, en-US...
[!] The request could not be completed because:
        Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-US]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.
```
</details>

### Environment

<details><summary>fastlane environment</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | debian_based 9.9                                    |
| Ruby                        | 2.3.3                                               |
| Bundler?                    | false                                               |
| Git                         | git version 2.11.0                                  |
| Installation Source         | /usr/local/bin/fastlane                             |
| Host                        | Debian GNU/Linux 9 debian_based 9.9 (4.9.0-9-amd64) |
| Ruby Lib Dir                | /usr/lib                                            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                         |
| Is contained                | false                                               |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ? |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.1 | ? Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.4        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| psych                     | 2.1.0        |
</details>

*generated on:* **2019-07-17**
</details>

**Comment by janpio** [comment]
I edited your issue a bit, please check if it is still all correct.

There might be a logic error with the app preview videos, someone will have to reproduce this. Thanks for reporting!

**Comment by namepunk** [comment]
Thank you, everything is correct

**Comment by max-ott** [comment]
*Might* be related: https://github.com/fastlane/fastlane/pull/14738

**Comment by namepunk** [comment]
@max-ott thanks so much. I test @xpy fix on my test environment, and it works fine! I look forward to include this patch on main fastline, for setup on my prod servers
