### ISSUE TITLE
Need help with Spaceship stuff that used to work

### ISSUE THREAD

**Issue by lbrownell-gpsw** [fastlane/fastlane#15033]
### Question Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
We used spaceship to do a few things to an app once it had finished processing in TestFlight. Those stopped working quite a while ago, and have not come back from the dead.  Asking for some guidance as to how to move forward in the new _App Store Connect API_ world.

#### Question Description
The three things we used to do, and can't now, are:
* Add "What's New" info to the app
* Submit for beta review if needed, potentially setting the demo-account-required status to false (not sure this is required anymore)
* Add external testers to the group, if any such were required

These three steps work!  Woot!
```
Spaceship::Tunes.login(<user-id>)
Spaceship::Tunes.select_team
app = Spaceship::ConnectAPI::App.find(options[:bundle_id])
```

These don't; they are from the old Spaceship::TestFlight command repertoire.  Some of them *may* still work, but I haven't gotten past the first one.

```
all_version_builds = Spaceship::TestFlight::Build.builds_for_train(app_id: app.apple_id, platform: "iOS", train_version: <app-version-id>)
build_array = all_version_builds.select { |b| b.build_version.eql? <build-number> }
build.update_build_information!(whats_new: changelog.encode('iso-8859-1').encode('utf-8'))
if build.external_state == "testflight.build.state.submit.ready"
    if build.beta_review_info.demo_account_name.nil?
      build.beta_review_info.demo_account_required = false
    end
    submitRes = build.submit_for_testflight_review!()
end
group = Spaceship::TestFlight::Group.find(app_id: app.apple_id, group_name: team)
build.add_group! group
```
@joshdholtz, You've said elsewhere "Let me know if there's something else that isn't working and I'll try to provide something."  Be careful what you wish for, here it is!

PS -- I took to trying to use the App Store Connect API directly. Adding a group to a build looks doable, not so clear about adding the What's New info.

TIA

**Comment by janpio** [comment]
Ping @max-ott

**Comment by lbrownell-gpsw** [comment]
This is, of course, a bug too (looking at the labels), but, per recent precedence, I'm asking if there is a different way to accomplish the same thing.

**Comment by max-ott** [comment]
@lbrownell-gpsw This is working for me:
```
app = Spaceship::ConnectAPI::App.find("com.sample.app")
builds = Spaceship::ConnectAPI::Build.all(
    app_id: app.id,
    version: "1.0.0", # optional, but highly recommended
    build_number: "1", # optional
    processing_states: "VALID" # Optional
)
```
This should you get started with the ConnectAPI. I recommend diving into https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/testflight/testflight.rb

E.g. 
```builds.first.get_build_beta_details```
I'm pretty sure @joshdholtz could add way more here.

**Comment by lbrownell-gpsw** [comment]
Thanks @max-ott!  Will give it a go.

**Comment by awgeorge** [comment]
@lbrownell-gpsw - did you work this out? We're trying to fix the same thing but are having problems accessing the TestFlight functions.

undefined method `get_app' for Spaceship::ConnectAPI::TestFlight:Module :/

**Comment by lbrownell-gpsw** [comment]
@awgeorge I *think* so, but the final proof is when we have a build that pushes to TF.  For various reasons, we haven't (builds pushing to HockeyApp, but not TF rn), so the entire process hasn't happened end-to-end.  Here's pretty much everything I'm doing now; hope this helps.

```
Spaceship::Tunes.login(user)
Spaceship::Tunes.select_team
build_array = Spaceship::ConnectAPI::Build.all(app_id: options[:app_id], version: options[:version], build_number: options[:build_number])

if build_array.length > 0
  build = build_array.first

  if build.get_beta_build_localizations[0].whats_new == "" || build.get_beta_build_localizations[0].whats_new == default_changelog || options[:changelog] == 'No Changelog'
    changelog = options[:changelog]
  else
    changelog = nil
  end

  if ! changelog.to_s.empty?
    build.get_beta_build_localizations[0].whats_new = changelog.encode('iso-8859-1').encode('utf-8'))
  end

  groups = build.app.get_beta_groups
  options[:teams].each do |team|
    groups.each do |group|
      if group.name == team
        Spaceship::ConnectAPI.add_beta_groups_to_build(build_id: build.id, beta_group_ids: [group.id])
    build.add_group! group
  end
end
```

**Comment by lbrownell-gpsw** [comment]
Hey @max-ott @joshdholtz -- 

Update:  There was a key part of the above I'd glossed over, until now, and I can't get that working:  Updating the "What's New" field for an app in TestFlight.

DISCLAIMER:  Not a Ruby developer, or, really, a developer.  Build wrangler/scripter is more like it.

First, note that this shows me what's currently in TF:
```
puts build_localizations.first.whats_new
```
Good, right?  But this:
```
Spaceship::ConnectAPI.patch_beta_build_localizations(localization_id: build_localizations.first, feedbackEmail: nil, attributes: { whats_new: changelog } )
```
is failing like this:
``` 
Spaceship::UnexpectedResponse: The request method is not valid for the resource path. - The request method used for this request is not valid for the resource path. Please consult the documentation.
  /Users/builder-mobile/.rvm/gems/ruby-2.6.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/connect_api/client.rb:134:in `handle_response'
  /Users/builder-mobile/.rvm/gems/ruby-2.6.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/connect_api/client.rb:105:in `patch'
  /Users/builder-mobile/.rvm/gems/ruby-2.6.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:150:in `patch_beta_build_localizations'
  scripts/fastlane/util/distribute_to_testflight_external_group.rb:79:in `<top (required)>'
```
Most of my many attempts to get this working have gone very far south, but this seems promising, as at least the traceback looks like its in the right area.

Ruby newbie that I am, I also tried a variant of that call like this, figuring I'd get that automatic hash parameter creation Ruby thing going on:
```
Spaceship::ConnectAPI.patch_beta_build_localizations(localization_id: build_localizations.first, feedbackEmail: nil, whats_new: changelog)
```
But that resulted in:
```
ArgumentError: unknown keyword: whats_new
  /Users/builder-mobile/.rvm/gems/ruby-2.6.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:141:in `patch_beta_build_localizations'
  scripts/fastlane/util/distribute_to_testflight_external_group.rb:78:in `<top (required)>'
```
Any help greatly appreciated.  Any updated docs, if I've missed them, also appreciated.

**Comment by max-ott** [comment]
@lbrownell-gpsw you can’t simply use the old commands and add Connect:API before them. These are (unfortunately) two completely different APIs with different information. Unfortunately I haven’t worked with the new Connect API yet, so hopefully @joshdholtz can shed some light here.

**Comment by lbrownell-gpsw** [comment]
Yeah, sorry, as far as I can tell, I *am* using the new APIs and their methods. :-(

**Comment by MostafaEl-Sayed** [comment]
If I don't have any external tester group, how I can create one group at the beginning ..!?

**Comment by janpio** [comment]
Open a new issue for this question please @MostafaEl-Sayed

**Comment by MostafaEl-Sayed** [comment]
already opened :(
