### ISSUE TITLE
Is it possible to force supply to save after uploading screenshots and metadata to Google Play between each language upload?

### ISSUE THREAD

**Issue by xhairbait** [fastlane/fastlane#15047]
#### Motivation Behind Feature
When uploading lots of languages and localized screenshots for each language if supply fails after uploading most of the languages, it will ditch/reset all progress.

#### Feature Description
Add an option, or update its default behavior, to perform a save/upload after each language.

More time added to the overall screenshot/metadata upload process.

#### Alternatives or Workarounds
Only work around I have right now is:
1. Create metadata-done and metadata-pending folders.
2. Moving  5 to 8 languages at a time I want to upload to metadata-pending.
3. Start the upload. 
4. Pray nothing fails due to connection dropping or Google API errors.
5. When it's done I move all the language folders in metadata to metadata-done.
6. Repeat steps 2 through 5 until metadata-pending is empty.

**Comment by janpio** [comment]
What are the reasons why `supply` files regularly?
How would you resume after it failed and the first batch of changes were already saved?

**Comment by max-ott** [comment]
@xhairbait What's the error message you are getting and/or why is `supply` failing?

**Comment by xhairbait** [comment]
Sometimes if a screenshot fails to upload due to a time out on multiple attempts or if a screenshot resolution is incorrect, it will fail to save any screenshots or metadata that it has staged an upload to Google.

When I say "staged" what I've seen is that terminal states files are being uploaded, but they aren't saved until the entire screenshot and metadata process has completely been uploaded to Google.

**Comment by xhairbait** [comment]
One error I got was that there was a Google API error. Very vague and not specific to what went wrong. Just retrying with only some language folders worked just fine. It eventually worked for every folder (without editing it's contents).

**Comment by xhairbait** [comment]
@janpio 
For you question about what I would do if there was a failure, would be to only have certain language folders in the metadata folder when trying to upload (~6 with a stable internet connections seems to be safe and not an utter waste of time if there is some sort of failure that occurs).

**Comment by xhairbait** [comment]
This is also an issue when working with a team and someone modifies the Google Play Store listing in any way. Which interrupts the upload. Therefor, reverting all progress. :'(

**Comment by max-ott** [comment]
@xhairbait Unfortunately that's a "feature" and the standard behaviour from the Google Play Publishing API. Each edit is only valid for a specific time and changing something on the web overrides it. (Basically creates a new one and the old one is no longer valid)

**Comment by xhairbait** [comment]
Oh this was definitely meant as a feature request, rather than a bug in fastlane/supply.
