### ISSUE TITLE
Action(s) to check if iOS codesigning setup is valid for app?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15041]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question

Is there an action (or combination of actions) that can be used to confirm that the iOS codesigning setup (installed provisioning profiles, installed certificates etc.) on a machine is valid for a app (with a specific bundle identifier) _without just starting a build_ and seeing if it works or crashes?

**Comment by max-ott** [comment]
I don't think there are any actions available out of the box. You would need to define your own logic (check for cert validity, check of cert if available etc.) and then run the respective `spaceship/fastlane` actions I would assume.
