### ISSUE TITLE
Add 'gem "slather"' to your Gemfile and restart fastlane

### ISSUE THREAD

**Issue by deepforu47** [fastlane/fastlane#15065]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Getting below expiation, even after installing the slather and adding that to Gemfile as well.

Add 'gem "slather"' to your Gemfile and restart fastlane

##### Command executed

$bundle exec fastlane Lane_Name

##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec fastlane generate_code_coverage_report
[18:03:50]: It seems like you wanted to load some plugins, however they couldn't be loaded
[18:03:50]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
[18:03:50]: ------------------------------
[18:03:50]: --- Step: default_platform ---
[18:03:50]: ------------------------------
[18:03:50]: --------------------------
[18:03:50]: --- Step: xcode_select ---
[18:03:50]: --------------------------
[18:03:50]: Setting Xcode version to /Applications/Xcode.app for all build steps
[18:03:50]: Driving the lane 'ios generate_code_coverage_report' 🚀
[18:03:50]: ---------------------
[18:03:50]: --- Step: slather ---
[18:03:50]: ---------------------
[18:03:50]: Missing gem 'slather', please add the following to your local Gemfile:
[18:03:50]: 
[18:03:50]: ▸ gem "slather"
[18:03:50]: 
+------------------+-----------------------------------+
|                     Lane Context                     |
+------------------+-----------------------------------+
| DEFAULT_PLATFORM | ios                               |
| PLATFORM_NAME    | ios                               |
| LANE_NAME        | ios generate_code_coverage_report |
+------------------+-----------------------------------+
[18:03:50]: Add 'gem "slather"' to your Gemfile and restart fastlane

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | xcode_select     | 0           |
| 💥   | slather          | 0           |
+------+------------------+-------------+

[18:03:50]: fastlane finished with errors

[!] Add 'gem "slather"' to your Gemfile and restart fa
```
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration : BBL Modern App iOS

default_platform(:ios)

xcode_select("/Applications/Xcode.app")

branch_name=nil
build_directory= "build/"
output_directory= "output/"

platform :ios do



    # ------------------------ TESTS
    #desc "Runs all the tests"
    lane :execute_test_cases do
        scan(scheme: "FIPhoneASP",
            workspace: "source/iOS.xcworkspace",
            code_coverage: true,
            clean: true,
            devices: ["iPhone 8"],
            output_style: "standard",
            output_types: "junit.html",
            output_files: "junit.xml",
            output_directory: "#{output_directory}",
            xcargs: {VALID_ARCHS:"x86_64", ONLY_ACTIVE_ARCH:"YES"}
        )
    end
        
  
        
    # ------------------------ Generate Coverage report in SonarQube
    desc "Generate Code Coverage Report"
    lane :generate_code_coverage_report do
        slather(scheme: "FIPhoneASP",
            binary_file: "/Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/bin/slather",
            workspace: "source/iOS.xcworkspace",
            proj: "source/FIPhoneASP/FIPhoneASP.xcodeproj",
            llvm_cov: true,
            output_directory: "#{output_directory}"
        )
    end

    
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app on appcenter
# apple_id("[[APPLE_ID]]") # Your Apple email address



```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.7.2        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-07-22*

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
Could you please post the full output with the full stacktrace?

**Comment by nishabe** [comment]
@deepforu47 , is the issue still persist or resolved?
