### ISSUE TITLE
carthage checkout support

### ISSUE THREAD

**Issue by Igor-Palaguta** [fastlane/fastlane#15063]
### New Issue Checklist

- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Carthage Action does not support checkout

##### Command executed
carthage(command: 'checkout')

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
Error setting value 'checkout' for option 'command'
You passed invalid parameters to 'carthage'.
Check out the error below and available options by running `fastlane action carthage`
</pre>
</details>

### Environment

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| faraday                   | 0.15.4       |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.64.0       |
| rubyzip                   | 1.2.3        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| googleauth                | 0.6.7        |
| signet                    | 0.11.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| faraday_middleware        | 0.13.1       |
| google-cloud-env          | 1.2.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| fastimage                 | 2.1.5        |
| bundler                   | 2.0.1        |
| unicode-display_width     | 1.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2019.0331  |
| badge                     | 0.10.0       |
| fastlane-plugin-badge     | 1.2.0        |
| fastlane-plugin-xcconfig  | 2.0.0        |
| fastlane-plugin-sentry    | 1.5.0        |
| fastlane-plugin-appcenter | 1.1.0        |
</details>

**Comment by janpio** [comment]
As documented:

>  command: "bootstrap",       # One of: build, bootstrap, update, archive. (default: bootstrap)

I don't know anything about Carthage, is this use regularly and does it fit the rest of the action's functionality?

**Comment by Igor-Palaguta** [comment]
For my case I wanted to add custom build setting to all carthage xcode projects before build

So I made this:
```
carthage checkout
modify project
carthage build
```

But then found official workaround for such cases
 
https://github.com/Carthage/Carthage/issues/2825#issuecomment-513160923

But in case if not just build setting should be modified before build. Adding checkout still can be useful
