### ISSUE TITLE
Can ConnectAPI be used to get dsym download url?

### ISSUE THREAD

**Issue by mwoollard** [fastlane/fastlane#15062]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Can ConnectAPI be used to get dsym download url?
#### Question Description
We had a script using Spaceship to transfer dlsym files from iTunes to Crashlytics. This broke a few months back when Apple changed their api. Am looking for alternative way of doing this and seems that ConnectAPI would be the way forward but I don't see a means of getting the dsym download url. Is this currently supported in some way? If not is it something that can be added?

Thanks
Mark

**Comment by max-ott** [comment]
I don't think that's a functionality that's currently available on the API: https://developer.apple.com/documentation/appstoreconnectapi

Therefore it won't be included in `Spaceship::ConnectAPI`

**Comment by mwoollard** [comment]
Very frustrating - having to manually transfer dSYM files across to Firebase for every internal test build + final builds across multiple apps will be a pain. Was working great before Apple broke things! Will file a request to add this with Apple but won't hold out much help :-(

Unless anyone else has suggestion as how to do this (we don't want to turn bitcode off).

**Comment by max-ott** [comment]
https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/lib/fastlane/actions/dsym_zip.rb is not doing the job? At least the action sounds like pretty much what you want to do, just not via `Connect:API`

**Comment by mwoollard** [comment]
I believe that just sends up the dSYM from your xcarchive file. If you use bitcode then you need to use the one provided by Apple in iTunes Connect after they've processed the binary since they re-build from bitcode and the one from building the binary before submitting is no longer valid.

**Comment by janpio** [comment]
@mwoollard Plese for context share your old script, even if the endpoints that was using are not there any more.

**Comment by mwoollard** [comment]
Will do - won't have access to it until tomorrow though. The odd thing is it missing api call occasionally works - seems like Apple have load balancer and some instances still have the old API...

**Comment by mwoollard** [comment]
Apologies for the delay but here is the script that no longer works. It was used to get a list of dSYM links, the output of this was used by a python script to do the actual transfer.

```#
# FASTLANE_ITC_USERNAME     The iTunes account username
# FASTLANE_ITC_PASSWORD     The iTunes account password
# FASTLANE_ITC_TEAM_ID      The team ID (needed when account associated with multiple teams)
#
# Output is one build per line with format:
#
# <bundle-id>,<build-number>,<dsym download url>
#

require "spaceship"

username = ENV["FASTLANE_ITC_USERNAME"]
password = ENV["FASTLANE_ITC_PASSWORD"]

Spaceship::Tunes::login(username, password)
Spaceship::Tunes.select_team

Spaceship::Tunes::Application.all.collect do |app|
    if app.live_version != nil
        train=app.live_version.version
        app.all_builds_for_train(train: train).sort { |a,b| a.build_version <=> b.build_version }.collect do |build|
            build.reload
            if !build.processing?
                puts app.bundle_id + ',' + build.build_version + ',' + build.dsym_url
            end
        end
    end
    if app.edit_version != nil
        app.all_build_train_numbers
        app.edit_version.candidate_builds.sort { |a,b| a.build_version <=> b.build_version }.collect do |build|
            if !build.processing && build.details.dsym_url != nil && build.build_version.to_i > last_build
                puts app.bundle_id + ',' + build.build_version + ',' + build.details.dsym_url
            end
        end
    end
end
```

**Comment by max-ott** [comment]
What's the error you are getting? `dsym_url` is definitely something you can get via Fastlane/Spaceship. I've just recently added even more retrievable information via this PR: https://github.com/fastlane/fastlane/pull/15094

**Comment by mwoollard** [comment]
Unexpected response and a dump of html. The odd thing is individual calls sometime work, sometimes fail but it never holds together to run the whole process. The above was working fine until the changes Apple's end earlier in the year. If there is now an alternative way to get the dsym_url that will be great - will check the PR.

**Comment by max-ott** [comment]
I think the train part is no longer working reliably, but might be wrong.
