### ISSUE TITLE
"2.128.0 broke our match config in our Bitrise CI pipeline"

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15072]
### Regression Information

- Breaking version: 2.128.0
- Last working version: 2.127.2

### Regression Description
See https://github.com/fastlane/fastlane/pull/15023#issuecomment-514211867

**Comment by tomaszbak-binar** [comment]
@joshdholtz `2.128.1` haven't propagated yet to the Rubygems. Is this overlook or issue on Rubygems side?

https://rubygems.org/gems/fastlane

**Comment by janpio** [comment]
Definitely an oversight. Ping @joshdholtz
