### ISSUE TITLE
How to add Android Release notes in the script and same thing with iOS

### ISSUE THREAD

**Issue by anveshreddy87** [fastlane/fastlane#15082]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Need help to include the Release notes in the script for Android (Google play store).
i need help with script to add release notes

#### Question Description
here is my script:

```
lane :stage do
    # Increment version code
     path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close

    sh("cd ..")
   # git_commit(path: "./app/build.gradle", message: "Version code bump to #{versionCode}")
   # push_to_git_remote

    # Build the release version of the Android app
    
    sh "../stage/fastlanebuild.sh"
    gradle(task: "clean")
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'QA')
  end

**Comment by janpio** [comment]
What do you mean by "release notes"? Android has changelogs, and there is documentation on how to use them here: https://docs.fastlane.tools/actions/upload_to_play_store/#changelogs-whats-new For iOS, `upload_to_app_store` even has its own param: https://docs.fastlane.tools/actions/upload_to_app_store/#parameters

**Comment by anveshreddy87** [comment]
Thanks for the info....Now i'm able to see release notes in play store with the fastlane build...
