### ISSUE TITLE
Slack message fail_on_error is not working

### ISSUE THREAD

**Issue by rnkhouse** [fastlane/fastlane#15083]
Below is my current configuration to send a message on slack on error. But, it's not sending an error message. However, the success message is working if the build is successful.

    lane :playstore do
      gradle(task: "clean")
      gradle(
        task: 'assemble',
        build_type: 'Release',
        properties: {
          "android.injected.signing.store.file" => "Keystore.jks",
          "android.injected.signing.store.password" => "abc",
          "android.injected.signing.key.alias" => "abc",
          "android.injected.signing.key.password" => "abc"
        }
      )
      upload_to_play_store(track: 'alpha')
      slack(
        message: "custom message",
        channel: "#automation",
        slack_url: "https://slack_url"
      )
    end
    error do |lane, exception|
      slack(
        message: exception.to_s, 
        channel: "#automation",
        slack_url: "https://slack_url",
        success: false, 
        # Output containing extended log output
        payload: { "Output" => exception.error_info.to_s }
      )
    end

Error in the console:

    16:39:41  [20:39:41]: [31mfastlane finished with errors[0m
    Could not determine the dependencies of task ':app:processReleaseResources'.
    16:39:41  > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
    16:39:41     > Could not find com.google.firebase:firebase-perf:18.0.1ddd.
    16:39:41       Required by:
    16:39:41           project :app
    16:39:41  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by janpio** [comment]
Have you tried to put a `puts` in there to see if that code is executed?
https://docs.fastlane.tools/advanced/lanes/#passing-parameters

**Comment by janpio** [comment]
How did you solve the problem @rnkhouse?

**Comment by rnkhouse** [comment]
@janpio Actually, now it's working. I didn't make any changes. Maybe I misconfigured something earlier.
