### ISSUE TITLE
fastlane "download_all" doesn't include mac profiles :(  

### ISSUE THREAD

**Issue by nancy-gomez** [fastlane/fastlane#15084]
### New Issue Checklist

- [ ] Updated fastlane to the latest version 
No, but basing this off master commit source code
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We have a scheduled job to download all the provisioning profiles from the Apple Developer Portal and we are just now noticing none of the Mac profiles have been downloaded. We are running as follows:

##### Command executed
`fastlane sigh download_all --readonly --skip_install --output_path /tmp/profiles/`

##### Complete output when running fastlane, including the stack trace and command used

The output of the command is not necessary as it is just a huge list of our profiles and this would mean nothing to you, but looking through the output I am searching for a profile that I generated for macOS and it is nowhere to be found. After looking at the source code: https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/download_all.rb I can see why! I have been playing around with Spaceship and I know that in order to download mac specific stuff you need to pass `mac: true` as such:

`Spaceship.provisioning_profile.all(mac: true)` but this is for all of the mac profiles, this doesn't include the ios ones. So the source code would have to be updated to combine the two collections of profiles

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.2.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.126.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.14.6       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| excon                     | 0.64.0       |
| rubyzip                   | 1.2.3        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| faraday_middleware        | 0.13.1       |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.0.8        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| uber                      | 0.1.0        |
</details>

*generated on:* **2019-07-23**
</details>

**Comment by nancy-gomez** [comment]
About to try and make a PR: https://github.com/nancy-gomez/fastlane/commit/cfd71daef589a9fe0ebbe8caa857cb11c8a4eb6b

But I got dependency issues 😭 Will deal with it tomorrow I guess

**Comment by nancy-gomez** [comment]
I have submitted a Pull Request with this adjustment: https://github.com/fastlane/fastlane/pull/15091 🙏 pls helppp

**Comment by nancy-gomez** [comment]
I have submitted an additional PR based off feedback from the new one. Opened up a new one as the overall feature was a smidge different (make `download_all` include mac profiles vs make `download_all` support the `platform` flag)

**Comment by rogerluan** [comment]
Closing this stale issue as https://github.com/fastlane/fastlane/pull/15175 got merged and released a long time ago 😊
