### ISSUE TITLE
How I can create production certificate from existing csr

### ISSUE THREAD

**Issue by me10001** [fastlane/fastlane#15088]
### Question Checklist

- [ 2.128.0 ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

How I can create production certificate from existing csr

**Comment by me10001** [comment]
How I can create production certificate from existing csr  file

**Comment by janpio** [comment]
`get_certificates` doesn't seem to have the option to use an existing CSR: https://docs.fastlane.tools/actions/get_certificates/#parameters 

Why is it important for you to use that one instead of creating a new one?
