### ISSUE TITLE
Could not find apk file at path

### ISSUE THREAD

**Issue by ahmadmssm** [fastlane/fastlane#15097]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to upload new build to the internal testing track to Google play store and I'm using this lane 
```
desc "Submit a new internal beta Build"
lane :deploy_playstore_internal_testing do |args|
    #read from arguments
    apkPath = args[:APK_PATH] 
    #
    upload_to_play_store(
     track: "internal",
     apk: apkPath
   )
end
```
##### Command executed
And I'm executing it by this way
```
fastlane deploy_playstore_internal_testing "APK_PATH:/Users⁩/myUserName/pathTo⁩MyProject⁩/app⁩/build⁩/outputs/apk/myFalvourFolder/apkName.appk"
```
##### Complete output when running fastlane, including the stack trace and command used
but it is not working and i get those errors:
```
Error setting value '/Users⁩/myUserName/pathTo⁩MyProject⁩/app⁩/build⁩/outputs/apk/myFalvourFolder/apkName.appk' for option 'apk'
[13:39:27]: You passed invalid parameters to 'upload_to_play_store'.
[13:39:27]: Check out the error below and available options by running `fastlane action upload_to_play_store`
```
```
Could not find apk file at path /Users⁩/myUserName/pathTo⁩MyProject⁩/app⁩/build⁩/outputs/apk/myFalvourFolder/apkName.appk'
```
Although there is an APK at this path, so what is going wrong ?

### Environment
Mac OS

Thanks in advance

**Comment by janpio** [comment]
Uh, that's strange. You made sure the file _really_ exists? Can you `puts apkPath` before the call to the action just to make sure there is nothing funny going on with the value?
