### ISSUE TITLE
Fastlane action google_play_track_version_codes is not giving the latest version code available on Play Store.

### ISSUE THREAD

**Issue by ishantsagar** [fastlane/fastlane#15090]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane action `google_play_track_version_codes` is not giving the latest version code available on Play Store.
Step 1: I have uploaded my build with versionCode 10 on internal track and I rolled it out for testing. So far when I call action `google_play_track_version_codes` it is giving `Found '10' version codes in track 'internal'`

Step2: When I upload a new build with versionCode 11, but I do not rollout this build, and I again call action `google_play_track_version_codes`, it is still giving `Found '10' version codes in track 'internal'`, which is not the case as I have higher build with version code 11 on the store in internal track.

How can I make sure I do not end up putting a wrong versionCode on basis of this fastlane action in my build as I am auto incrementing the versionCode on the basis of this action result and play store will not take the build with same versionCode again.

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                   |
| --------------------------- | --------------------------------------- |
| OS                          | 10.13.6                                 |
| Ruby                        | 2.2.4                                   |
| Bundler?                    | false                                   |
| Git                         | git version 2.10.1                      |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane     |
| Host                        | Mac OS X 10.13.6 (17G65)                |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib              |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016              |
| Is contained                | false                                   |
| Is homebrew                 | true                                    |
| Is installed via Fabric.app | false                                   |
| Xcode Path                  | ~/Desktop/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.127.1'

# 'Ensure code setup is ready'
def ensure_code_setup(platform)
  if Dir.exist?('../node_modules')
    puts 'node_modules already available'
  else
    if platform =='ios'
     sh('npm run project:clean:setup')
     return
    else 
      sh('npm run project:setup:android')
    end
  end

  if platform == 'ios' 
    if Dir.exist?('../ios/Pods')
      puts 'ios/Pods already available'
    else
      sh('npm run project:setup:ios')
    end
  end
end

# 'Read the specs from the file'
def read_spec(key)
  file = File.read('fastlanespec.json')
  specs = JSON.parse(file)
  specs[key]
end 


before_all do
  # ENV["MATCH_READONLY"] = false.to_s
  ENV["FASTLANE_DONT_STORE_PASSWORD"] = 1.to_s
  ENV["FASTLANE_ITC_TEAM_NAME"] = read_spec('apple_team_name')
  ENV["SLACK_URL"] = read_spec('slack_url')
end


platform :ios do
  # 'xcode project current app version number'
  def app_version_number
    get_version_number(xcodeproj: read_spec('xcodeproj'), target: read_spec('scheme'))
  end

  # 'github tag, make sure `increment_build_number` already run'
  def github_tag
    new_build_no = get_build_number(xcodeproj: read_spec('xcodeproj'))
    "iOS_v#{app_version_number}(#{new_build_no})"
  end

  # 'Get Provision Profile Path, make sure `manage_sign` already run'
  def get_provisioning_profile_path
    ENV["sigh_#{read_spec('ios_bundle_id')}_appstore_profile-path"]
  end

  # 'Get Provision Profile Name, make sure `manage_sign` already run'
  def get_provisioning_profile_name
    ENV["sigh_#{read_spec('ios_bundle_id')}_appstore_profile-name"]
  end

  # 'Get Provision Profiles, make sure `manage_sign` already run'
  def get_provisioning_profiles
      { read_spec('ios_bundle_id') => lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING][read_spec('ios_bundle_id')] }
  end

  # 'Get Distribution cert name, make sure `manage_sign` already run'
  def get_distribution_cert_name
    "iPhone Distribution: #{read_spec("apple_team_name")} (#{read_spec("team_id")})"
  end

  desc 'Install the essential project setup dependencies'
  lane :setup do
    ensure_code_setup('ios')
  end

  desc 'Increment the build number (not the version number)'
  lane :update_build_number do
    current_build_number = latest_testflight_build_number(
      version: app_version_number,
      app_identifier: read_spec('ios_bundle_id'), 
      team_name: read_spec('apple_team_name'),
      initial_build_number: 0
    )
    new_build_number = current_build_number + 1;
    increment_build_number(build_number: new_build_number, xcodeproj: read_spec('xcodeproj'))
    new_build_number
  end

  desc 'Create React Native bundle for iOS'
  lane :create_rn_ios_bundle do
    sh('npm run build-ios')
  end

  desc 'Manage certificates and provisioning profiles'
  lane :manage_sign do
    sync_code_signing(git_url: read_spec('git_certandprov'),
          git_branch: read_spec('git_cert_branch'),
          type: read_spec('cert_type'),
          app_identifier: read_spec('ios_bundle_id'),
          team_name: read_spec('apple_team_name'),
          clone_branch_directly: true,
          readonly: true,
          verbose: true
        )
  end

  desc 'create ios build as .ipa'
  lane :create_ios_build do
    manage_sign
    disable_automatic_code_signing(path: read_spec('xcodeproj'))
    update_project_team(path: read_spec('xcodeproj'), teamid: read_spec('team_id'))
    update_project_provisioning(
          xcodeproj: read_spec('xcodeproj'),
          target_filter: read_spec('scheme'),
          profile: get_provisioning_profile_path,
          build_configuration: "Release"
        )
    build_app(
      workspace: read_spec('workspace'), 
      scheme: read_spec('scheme'), 
      export_options: {
        method: "app-store",
        provisioningProfiles: get_provisioning_profiles
      },
      codesigning_identity: get_distribution_cert_name,
      silent: true,
      clean: true,
      )
    enable_automatic_code_signing(path: read_spec('xcodeproj'))
  end

  desc 'upload build to test flight, make sure `create_ios_build` already run'
  lane :upload_build do
    upload_to_testflight(skip_waiting_for_build_processing: true, skip_submission: true)
  end
  
  desc 'github version bump, create tag and push code; make sure `update_build_number` is already run'
  lane :manage_github_commit do
    add_git_tag(tag: github_tag)
    push_git_tags
  end

  desc 'ios build creation with increment build number and push to testflight'
  lane :release do
    setup
    update_build_number
    create_rn_ios_bundle
    create_ios_build
    upload_build
    notify_progress
    manage_github_commit
  end

  desc 'Notify progress to all communication channel as slack'
  private_lane :notify_progress do
    slack(message: 'Successfully uploaded a new App Store build: ' + github_tag)
  end
end

platform :android do

  desc 'Create React Native bundle for android'
  lane :create_rn_android_bundle do
    sh('npm run build-android')
  end

  desc 'Increment Android version code'
  lane :increment_android_version_code do
    if(File.exist?('release_manager.json')) 
      increment_version_code(version_code: fetch_store_version_code, gradle_file_path: read_spec('gradle_file_path'))
    end
  end

  desc 'keystore cloning from github and saving to keystores of android'
  lane :clone_save_keystore_to_android do
   ENV["keystore"] = read_spec('android_bundle_id')+".jks"
   sh("chmod +x scripts/downloadKeystore.sh")
   sh("scripts/downloadKeystore.sh $keystore")
 end

  desc 'Create android build'
  lane :create_android_build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/') #For Android App Bundle(PlayStore and MS-AppCenter)
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/') #For Android APK(Hockey Only)
  end

  desc 'Install the essential project setup dependencies'
  lane :setup do
    ensure_code_setup('android')
  end

  desc 'Upload android build to HockeyApp'
  lane :upload_android_build_hockey do
    hockey(api_token: read_spec('hockey_api_token'), apk: "android/app/build/outputs/apk/release/app-release.apk")
  end

  desc 'Upload android build to AppCenter'
  lane :upload_android_build_appcenter do
    appcenter_upload(api_token: read_spec('appcenter_api_token'), owner_name: "code-j7nj", app_name:read_spec('scheme'), 
    app_os: "Android", app_platform: "React-Native") 
  end

  desc 'Upload android build to PlayStore'
  lane :create_and_upload_android_build do
    sh("chmod +x scripts/publishBundle.sh")
    if(File.exist?('release_manager.json'))   
      sh("scripts/publishBundle.sh publish")
    else 
      sh("scripts/publishBundle.sh")
    end
   # supply(package_name: read_spec('android_bundle_id'), skip_upload_apk: true, track: 'internal', json_key: read_spec('release_manager_json_path'))
  end

  desc 'github version bump, create tag and push code; make sure update_build_number is already run'
  lane :create_github_android_tag do
    android_tag = github_android_tag
    set_github_release(
      repository_name: "punchh/"+read_spec("git_repo"),
      api_token: ENV["GITHUB_PAT"],
      name: android_tag,
      tag_name: android_tag,
      description: "Android Build generated via Fastlane",
      is_prerelease: true,
      commitish: "master",
      upload_assets: ["android/app/build/outputs/bundle/release/app.aab", "android/app/build/outputs/apk/release/app-release.apk"])
  end

  desc 'Notify progress to all communication channel as slack'
  lane :notify_android_progress do
    slack(message: 'Successfully uploaded a new Play Store build: ' + github_android_tag)
  end

  def fetch_store_version_code
    # pcode = google_play_track_version_codes(package_name: read_spec('android_bundle_id'), track: "production", json_key: read_spec('release_manager_json_path'))
    # acode = google_play_track_version_codes(package_name: read_spec('android_bundle_id'), track: "alpha", json_key: read_spec('release_manager_json_path'))
    icode = google_play_track_version_codes(package_name: read_spec('android_bundle_id'), track: "internal", json_key: read_spec('release_manager_json_path'))
    # bcode = google_play_track_version_codes(package_name: read_spec('android_bundle_id'), track: "beta", json_key: read_spec('release_manager_json_path'))
    # rcode = google_play_track_version_codes(package_name: read_spec('android_bundle_id'), track: "rollout", json_key: read_spec('release_manager_json_path'))
   
    if pcode.nil? || pcode.empty?
      pcode = [0]
    end

    if acode.nil? || acode.empty?
      acode = [0]
    end

    if icode.nil? || icode.empty?
      icode = [0]
    end

    if bcode.nil? || bcode.empty?
      bcode = [0]
    end

    if rcode.nil? || rcode.empty?
      rcode = [0]
    end

    updatedVersionCode = [pcode.max, icode.max, acode.max, bcode.max, rcode.max].max + 1
  end

  def github_android_tag
    versionCode = get_version_code(gradle_file_path: read_spec('gradle_file_path'))
    versionName = get_version_name(gradle_file_path: read_spec('gradle_file_path'))
    "android_v#{versionName}(#{versionCode})"
  end
  
  lane :release do
    setup
    create_rn_android_bundle
    increment_android_version_code
    # create_android_build
    # upload_android_build_hockey
    # upload_android_build_appcenter
    clone_save_keystore_to_android
    create_and_upload_android_build
    create_github_android_tag
    notify_android_progress
  end
end


error do |lane, exception|
  enable_automatic_code_signing(path: read_spec('xcodeproj'))
  slack(message: exception.message, success: false)
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.127.1 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status      |
| -------------------------------------- | ------- | ------------------ |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date       |
| fastlane-plugin-get_version_name       | 0.2.2   | ✅ Up-To-Date       |
| fastlane-plugin-get_version_code       | 0.2.0   | ✅ Up-To-Date       |
| fastlane-plugin-appcenter              | 1.1.1   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| slack-notifier                         | 2.3.2        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 2.3.5        |
| claide                                 | 1.0.2        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.11.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.1.3        |
| terminal-table                         | 1.7.3        |
| plist                                  | 3.2.0        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.5.1        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.7.0        |
| tty-cursor                             | 0.7.0        |
| tty-spinner                            | 0.9.1        |
| babosa                                 | 1.0.2        |
| colored                                | 1.2          |
| highline                               | 1.7.8        |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.55.0       |
| faraday                                | 0.12.1       |
| unf_ext                                | 0.0.7.4      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20170404 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| fastimage                              | 2.1.0        |
| gh_inspector                           | 1.1.3        |
| json                                   | 1.8.1        |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.2.3        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 0.0.4        |
| dotenv                                 | 2.2.0        |
| bundler                                | 1.14.6       |
| faraday_middleware                     | 0.11.0.1     |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.5        |
| jwt                                    | 2.1.0        |
| uber                                   | 0.0.15       |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 2.1.0        |
| mime-types-data                        | 3.2016.0521  |
| mime-types                             | 3.1          |
| multi_json                             | 1.12.1       |
| signet                                 | 0.11.0       |
| memoist                                | 0.16.0       |
| os                                     | 0.9.6        |
| googleauth                             | 0.6.7        |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.23.9       |
| google-cloud-env                       | 1.2.0        |
| google-cloud-core                      | 1.3.0        |
| digest-crc                             | 0.4.1        |
| google-cloud-storage                   | 1.16.0       |
| emoji_regex                            | 1.0.1        |
| libxml-ruby                            | 3.0.0        |
| psych                                  | 2.0.8        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-get_version_name       | 0.2.2        |
| fastlane-plugin-get_version_code       | 0.2.0        |
| fastlane-plugin-appcenter              | 1.1.1        |
</details>

*generated on:* **2019-07-24**
</details></pre>
</details>

**Comment by ishantsagar** [comment]
Is there any update over it>?

**Comment by raiffeisennet** [comment]
Same problem here.. We need the functionality to retrieve the highest version code over all (published or not on any track) artifacts available on Google Play

**Comment by gauravds** [comment]
Pleaes reopen
