### ISSUE TITLE
App Released Accidentally to Google Play due to Silently Ignoring Rollout

### ISSUE THREAD

**Issue by ahimta** [fastlane/fastlane#15099]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I think Fastlane have some silent behavior that can result in erroneous unexpected behavior. For example, the code below ignores the `rollout` option silently and releases the app to Google Play to all users:sweat_smile:.

```ruby
upload_to_play_store(
  track: 'beta',
  track_promote_to: 'production',
  # `rollout` is ignored silently because the promotion track is
  # `production` instead of `rollout`and the app is released to
  # all users in the store when the intended behavior is a 5% rollout.
  rollout: '0.05'
)
```

And safety and explicit errors are especially important for Fastlane's usecases. And this can be easier because Fastlane has limited op-sensitive operations as compared to other tools that have a much larger surface area (e.g: Terraform and other IaC tools):sweat_smile:.

I understand that these changes (if approved) can only happen with the next major update and hope the bigger problem of silent unexpected behavior is more thoroughly  mitigated:smiley:.

2019-08-06: content unrelated to the issue moved to a new issue https://github.com/fastlane/fastlane/issues/15147

**Comment by janpio** [comment]
These are two unrelated issues, correct? Could you please spin out one of them into its own issue, that will make it much easier for us to track and fix eventually. Thanks.

**Comment by ahimta** [comment]
I just first comment in place to save the time of everyone who's going to participate in this issue and added a note that references the other issue:sweat_smile:.

I was actually hoping for more of a milestone where there would be a checklist for changes that can make fastlane safer and many of these changes that are non-backwards compatible could be released with the next major release:sweat_smile:.

Because a small step leading to a release of an app with incorrect options could compromise safety depending on what it does:sweat_smile:. And only someone familiar with most of the project can tell whether local fixes are enough or not:sweat_smile:.

**Comment by janpio** [comment]
Thanks for cleaning up the second issue.

Fastlane doesn't really use milestones in that way (yet...), what I did was also just a informal "categorization" of the issue for later review (when the time comes).

**Comment by ahimta** [comment]
@fastlane-bot I think you may have closed this by mistake:sweat_smile: or maybe I'm just mistaken:thinking:.
