### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by luigisaggese** [fastlane/fastlane#15092]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

```
SGS-xxxxx:a its-xxxx-xxxx$ fastlane run upload_to_play_store package_name:"com.xxxx.xxxxx.xxx" track:"alpha" apk:"xxxxx.apk" json_key_data:"{
    \"type\": \"service_account\",
    \"project_id\": \"api-xxxx-xxxx\",
    \"private_key_id\": \"xxxxx\",
    \"private_key\": \"-----BEGIN PRIVATE KEY-----\xxxxxxxxx=\n-----END PRIVATE KEY-----\n\",
    \"client_email\": \"xxxxx@xxxxx.xxx.xxxx.com\",
    \"client_id\": \"xxxxx\",
    \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",
    \"token_uri\": \"https://oauth2.googleapis.com/token\",
    \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",
    \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/xxxx-xxxx-xxxx-2%40api-xxxxx-xxxxx.iam.gserviceaccount.com\"
  }" 
[✔] 🚀 
[13:09:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:09:58]: ----------------------------------
[13:09:58]: --- Step: upload_to_play_store ---
[13:09:58]: ----------------------------------

+-------------------------+-------------------------------+
|               Summary for supply 2.126.0                |
+-------------------------+-------------------------------+
| package_name            | com.xxxx.xxxx.dev     |
| track                   | alpha                         |
| apk                     | xxxxx.apk |
| json_key_data           | ********                      |
| skip_upload_apk         | false                         |
| skip_upload_aab         | false                         |
| skip_upload_metadata    | false                         |
| skip_upload_images      | false                         |
| skip_upload_screenshots | false                         |
| validate_only           | false                         |
| check_superseded_tracks | false                         |
| timeout                 | 300                           |
| deactivate_on_promote   | true                          |
+-------------------------+-------------------------------+

[13:09:58]: -----------------------------------------------------------------------
[13:09:58]: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
[13:09:58]: 
[13:09:58]: SSL errors can be caused by various components on your local machine.
[13:09:58]: 
[13:09:58]: The best solution is to use the self-contained fastlane version.
[13:09:58]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
[13:09:58]:  - Use Homebrew
[13:09:58]:     - update brew with `brew update`
[13:09:58]:     - install fastlane using:
[13:09:58]:       - `brew cask install fastlane`
[13:09:58]:  - Use One-Click-Installer:
[13:09:58]:     - download fastlane at https://download.fastlane.tools
[13:09:58]:     - extract the archive and double click the `install`
[13:09:58]: -----------------------------------------------------------
[13:09:58]: for more details on ways to install fastlane please refer the documentation:
[13:09:58]: -----------------------------------------------------------
[13:09:58]:         🚀       https://docs.fastlane.tools          🚀   
[13:09:58]: -----------------------------------------------------------
[13:09:58]: 
[13:09:58]: You can also install a new version of Ruby
[13:09:58]: 
[13:09:58]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
[13:09:58]: - If you use system Ruby:
[13:09:58]:   - Run `brew update && brew install ruby`
[13:09:58]: - If you use rbenv with ruby-build:
[13:09:58]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
[13:09:58]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
[13:09:58]: - If you use rvm:
[13:09:58]:   - First run `rvm osx-ssl-certs update all`
[13:09:58]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
[13:09:58]: 
[13:09:58]: If that doesn't fix your issue, please google for the following error message:
[13:09:58]:   'SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)'
[13:09:58]: -----------------------------------------------------------------------

[!] SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/XCode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.126.0 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.2       |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.10.0       |
| unicode-display_width     | 1.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.64.0       |
| unf_ext                   | 0.0.7.6      |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.4        |
| mime-types-data           | 3.2019.0331  |
| os                        | 1.0.1        |
| google-cloud-env          | 1.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-07-25**
</details>

**Comment by max-ott** [comment]
Did you already try the steps in the error message?

**Comment by luigisaggese** [comment]
Yes, I have tried it without success.
