### ISSUE TITLE
How to set release name when using upload_to_play_store?

### ISSUE THREAD

**Issue by vnen** [fastlane/fastlane#15096]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How to set the release name as seen in the Google Play Console?

#### Question Description

In the Google Play console I can set a specific name for the release. When I deploy with fastlane, the name is the current date. I assume this is being set internally somewhere but looking at the docs I see no option to set my own.

This is the same as #13643, but that issue was auto-closed and locked without solution.

**Comment by janpio** [comment]
I can repeat my comment from the closed issue here: https://github.com/fastlane/fastlane/issues/13643#issuecomment-439702169

But we will update to a newer version of the underlying API soon-ish, so maybe this will be possible there: https://github.com/fastlane/fastlane/issues/14573

**Comment by vnen** [comment]
Seems like the new API version allows to set the release name: https://android-developers.googleblog.com/2018/06/automating-your-app-releases-with.html

**Comment by janpio** [comment]
@scorpion35 is currently working on implementing the new API over at https://github.com/fastlane/fastlane/issues/14573#issuecomment-518464278, so maybe they can add that to their TODO list 🙊

**Comment by scorpion35** [comment]
It's possible I think! I have added `-n` flag to specify version number when downloading - https://github.com/scorpion35/fastlane/commit/779b45b78195d4704b5d402f6ad6d6e57d4fab64. 

Will reuse it when running `supply run`. I should be able to put some more time this Friday!

**Comment by scorpion35** [comment]
Quick update: We can now set version name when using `supply run` - https://github.com/scorpion35/fastlane/commit/2a67cfdcbac0a781a51a077e48501f6de5017b40#commitcomment-34750110

**Comment by kschults** [comment]
Don't think this should be closed. It may be blocked by the API upgrade, but please keep it around for tracking so those of us waiting on it know when it becomes available

**Comment by vnen** [comment]
This is dependent on the API version change (#14573) but it should not be closed until it's added.

**Comment by joshdholtz** [comment]
This is now available as of `2.136.0` 😊
