### ISSUE TITLE
Linux 'cert' 'match' working fail

### ISSUE THREAD

**Issue by JuniorSecond** [fastlane/fastlane#15103]
### Question Checklist

- [ ✔️] Updated fastlane to the latest version
- [✔️ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✔️ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ✔️] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Hi,I'm want to using cert and match  in Linux. But Linux it not support "keychain" module. 

match errors tip like it:
`** [!] Could not locate the provided keychain. Tried:
	/root/Library/Keychains/login-db
	/root/Library/Keychains/login.keychain-db
	/root/Library/Keychains/login
	/root/Library/Keychains/login.keychain
	/root/fastlane/login-db
	/root/fastlane/login.keychain-db
	/root/fastlane/login
	/root/fastlane/login.keychain**`

cert errors tip  like it:
`**Available session is not valid any more. Continuing with normal login.
[11:44:12]: Successfully logged in
[11:44:13]: To not be asked about this value, you can specify it using 'keychain_path'
[11:44:13]: Path to a custom keychain: 

[11:44:26]: Error accessing file, this might be due to fastlane's directory handling
[11:44:26]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/helper.rb:277:in ``': No such file or directory - security (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/helper.rb:277:in `backticks'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/cert_checker.rb:98:in `block in wwdr_keychain'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/cert_checker.rb:97:in `each'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/cert_checker.rb:97:in `wwdr_keychain'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/cert_checker.rb:58:in `wwdr_certificate_installed?'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/cert_checker.rb:24:in `installed_identies'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/cert_checker.rb:12:in `installed?'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/runner.rb:98:in `block in find_existing_cert'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/runner.rb:87:in `each'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/runner.rb:87:in `find_existing_cert'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/runner.rb:38:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/runner.rb:13:in `launch'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/commands_generator.rb:38:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/commands_generator.rb:56:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/cert/lib/cert/commands_generator.rb:16:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'**`

May I ask how to modify them so that they can be used normally?

**Comment by janpio** [comment]
They can't yet - only macOS is fully supported. We are working on improving this, but currently there is not much time for that. I hope this will change in the near future.

**Comment by JuniorSecond** [comment]
> They can't yet - only macOS is fully supported. We are working on improving this, but currently there is not much time for that. I hope this will change in the near future.

thanks, I know someone has done it.I'm trying to fix it and get it to work.
