### ISSUE TITLE
update_fastlane causing (Errno::EACCES) Permission denied

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#15109]
### New Issue Checklist

- [ ] Updated fastlane to the latest version <- Blocker
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When a new Fastlane version is available and I run `update_fastlane` as an step. The script crashes and I need to manually update fastlane.

##### Command executed
Simply run `update_fastlane` inside a lane.
Running `sudo gem install fastlane` solves the problem but also updates fastlane, stopping the issue. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> MacBook-Pro:myApp ppamorim$ fastlane something
[✔] 🚀 
[16:04:01]: fastlane detected a Gemfile in the current directory
[16:04:01]: however it seems like you don't use `bundle exec`
[16:04:01]: to launch fastlane faster, please use
[16:04:01]: 
[16:04:01]: $ bundle exec fastlane galway
[16:04:01]: 
[16:04:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:04:02]: -----------------------------
[16:04:02]: --- Step: update_fastlane ---
[16:04:02]: -----------------------------
[16:04:02]: Looking for updates for fastlane...
[16:04:05]: Updating fastlane from 2.128.0 to 2.128.1... 🚀
#<Thread:0x00007f80016d1518@/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        8: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
        7: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        6: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        5: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        3: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        2: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
        1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/fastlane-2.128.1.gem (Errno::EACCES)

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

\#######################################################################
\# fastlane 2.128.1 is available. You are on 2.128.0.
\# You should use the latest version.
\# Please update using `sudo gem install fastlane`.
\#######################################################################

2.128.1 Hotfix for match readonly issue
* [match] fix for match username not found if readonly (#15073) via Josh Holtz

Please update using `sudo gem install fastlane`
Traceback (most recent call last):
        8: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
        7: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        6: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        5: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        3: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        2: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
        1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/fastlane-2.128.1.gem (Errno::EACCES)
        8: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
        7: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        6: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        5: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        3: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        2: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
        1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/open-uri.rb:37:in `initialize': [!] Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/fastlane-2.128.1.gem (Errno::EACCES)</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.6 (18G84)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

Private

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.128.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.11.0       |
| unicode-display_width     | 1.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.65.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.4        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| os                        | 1.0.1        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
</details>

*generated on:* **2019-07-29**
</details>

**Comment by janpio** [comment]
The action has some documentation on how to fix some problems, maybe this helps? https://docs.fastlane.tools/actions/update_fastlane/#update_fastlane

The problem might be that you installed fastlane with sudo, but are running it without? And somehow the logic that should detect that doesn't fire for whatever reason.

The Traceback is also totally unrelated to fastlane, and looking at the code this is actually using the `Gem::CommandManager` from rubygems - so this might actually be a problem there - but I am not sure as I don't fully understand what is going on there.

**Comment by ppamorim** [comment]
@janpio Firstly thank you for the answer.

So far I remember, Fastlane wasn't installed with sudo. I will try to reinstall and the fix from the documentation to see if solves this issue.
 
Thank you.
