### ISSUE TITLE
Fastlane install error

### ISSUE THREAD

**Issue by Orgbrat** [fastlane/fastlane#15100]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Fastlane install error on macOS mojave 10.14.6

#### Question Description
I used https://download.fastlane.tools to install fastlane. But near the end of the install, I received the below error.
`sed: /Users/orgbrat/.fastlane/bin/bundle/bin/bundle-env: Permission denied
Updating installed gems
Updating fastlane
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Users/orgbrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0 directory.
Cleaning up installed gems...
Clean Up Complete
`
Can some tell me what to do to fix this error?
I understand it is telling me I have permission issues but I need help on how to fix this as I am a Xamarin developer that has the mac for build and am not very savy about the macOS.

Orgbrat

**Comment by janpio** [comment]
The simplest solution is probably to use another install method as documented on docs.fastlane.tools.

**Comment by Orgbrat** [comment]
I used the "sudo gem install fastlane -NV" command and it seems to have installed with no errors.
