### ISSUE TITLE
Option to auto remove Provisioning Profile with the same name if Cert doesn't match

### ISSUE THREAD

**Issue by Antol** [fastlane/fastlane#15108]
### Feature Request
To add an option to allow Sigh automatically delete existing Provisioning Profile if it already exists and doesn't match currently installed certificate, or fail instead

#### Motivation Behind Feature
I have a pretty neat configuration in my Xcode Proj file with manual code signing like this "match AppStore $(PRODUCT_BUNDLE_IDENTIFIER)". It works perfectly for most of the cases, but if for some reason (many projects with different certs in the same team) may happen situation in which currently selected cert is not the one which was used to create prov profile. In that case match (or Sigh to be precise) create new prov profile, that instead of solving my problem gives me one more - garbage profile with a bad name.

#### Feature Description
I want to be able to catch this situation or fix it. So in function "def create_profile!" in file sigh/lib/runner.rb I want instead:   

      unless Sigh.config[:skip_fetch_profiles]
        if Spaceship.provisioning_profile.all.find { |p| p.name == name }
          UI.error("The name '#{name}' is already taken, using another one.")
          name += " #{Time.now.to_i}"
        end
      end   

Something like this

      unless Sigh.config[:skip_fetch_profiles]
        profile = Spaceship.provisioning_profile.all.find { |p| p.name == name }
        if profile
          if Sigh.config[:remove_profiel_with_same_name]
            profile.delete!
          else
            UI.error("The name '#{name}' is already taken, using another one.")
            name += " #{Time.now.to_i}"
          end
        end
      end

No drawbacks or changes in current default behavior, just one more option to configure

#### Alternatives or Workarounds
As an alternative, it may just fail the script. At least, in that case, I wouldn't need to go to dev portal and delete the garbage profile.

**Comment by Antol** [comment]
:(

**Comment by husyn** [comment]
I think it's useful to have this feature.
