### ISSUE TITLE
use force:true but create new adhoc profiles

### ISSUE THREAD

**Issue by mlijin9011** [fastlane/fastlane#15116]
ERROR [2019-07-31 12:43:16.58]: The name 'match AdHoc com.xxx' is already taken, using another one.
WARN [2019-07-31 12:43:16.58]: Creating new provisioning profile for 'com.xxx' with name 'match AdHoc com.xxx 1564548196' for 'ios' platform

**Comment by mlijin9011** [comment]
+-------------------------------------+-------------------------------------------+
|                            Summary for sigh 2.128.1                             |
+-------------------------------------+-------------------------------------------+
| app_identifier                      | com.xxx             |
| username                            | xxx               |
| force                               | true                                      |
| cert_id                             | xxx                                |
| provisioning_name                   | match AdHoc com.xxx |
| ignore_profiles_with_different_name | true                                      |
| team_id                             | xxx                                |
| platform                            | ios                                       |
| adhoc                               | true                                      |
| developer_id                        | false                                     |
| development                         | false                                     |
| skip_install                        | false                                     |
| skip_fetch_profiles                 | false                                     |
| skip_certificate_verification       | false                                     |
| readonly                            | false                                     |
+-------------------------------------+-------------------------------------------+

**Comment by janpio** [comment]
What is the problem here?

Also, please don't delete the issue template but fill it. It asks for important data and information we need to be able to help you.
