### ISSUE TITLE
iPhone XS Max screenshot shown under iPhone X section in screenshots.html

### ISSUE THREAD

**Issue by davidrothera** [fastlane/fastlane#15117]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When viewing the snapshot summary iPhone Xs and iPhone Xs Max screenshots are lumped in with the iPhone X screenshots.

Whilst this isn't an issue for X vs Xs as you usually only have one of them selected but having Xs Max shots not in their own area is a little annoying.

##### Command executed
`fastlane snapshot`

##### Complete output when running fastlane, including the stack trace and command used
n/a

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.6                                          |
| Ruby                        | 2.6.3                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.20.1 (Apple Git-117)               |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane             |
| Host                        | Mac OS X 10.14.6 (18G84)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10.3.app/Contents/Developer/ |
| Xcode Version               | 10.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    carthage(
      use_binaries: true,
      platform: "iOS",
      configuration: "Release",
      cache_builds: true)
    sync_code_signing(type: "appstore")
    build_app(scheme: "PillBoxPlus")
    commit_version_bump
    add_git_tag
    push_to_git_remote
    upload_to_testflight
  end

  desc "Update App Icon"
  lane :icon do
    appicon(
      appicon_devices: [:iphone, :ipad, :ios_marketing],
      appicon_path: "Source/Resources/Assets.xcassets"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("co.supratude.PillBoxPlus") # The bundle identifier of your app
apple_id("david.rothera@gmail.com") # Your Apple email address

itc_team_id("613942") # App Store Connect Team ID
team_id("YX97W249KL") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.14.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.4        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 1.0.1        |
| excon                     | 0.65.0       |
| json                      | 2.2.0        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.2.0        |
| io-console                | 0.4.8        |
| zlib                      | 1.0.0        |
| rexml                     | 3.2.2        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| fastlane-plugin-appicon   | 0.14.1       |
</details>

*generated on:* **2019-07-31**
</details>

**Comment by smykytyn** [comment]
I see the same thing.  I very much doubt that code signing has anything to do with this.

**Comment by apstygo** [comment]
Same here

**Comment by janpio** [comment]
Can someone share a quick screenshot showing the problem just so we have it on file? Maybe also a `snapshot` setup/call that executes the screenshots for the relevant devices. Thanks.

**Comment by smykytyn** [comment]
![Screen Shot 2019-08-05 at 2 09 03 PM](https://user-images.githubusercontent.com/329815/62495517-f547bd00-b78a-11e9-9520-334d8f2bd689.png)
Hope this is what you are looking for - shows the Xs and Xs Max screenshots in one line across...

**Comment by janpio** [comment]
What iOS version are you using on your simulator?

If it's 12.2:, I think this already has an (unmerged) PR at https://github.com/fastlane/fastlane/pull/14963

**Comment by smykytyn** [comment]
The screenshots were from the 12.4 simulator.
