### ISSUE TITLE
Empty message for `Google Api Error - `

### ISSUE THREAD

**Issue by gzssince1990** [fastlane/fastlane#15119]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Trying to run supply function for uploading app to google play store. But got an `Google Api Error - ` without any error message and then I turned on the verbose mode and the error stack trace is not that helpful.

##### Command executed

`bundle exec fastlane build_and_upload_to_app_store --verbose`
``` ruby 
  desc "Builds the production app and uploads to Google Play"
  lane :build_and_upload_to_app_store do
    buildRelease
    supply(package_name: "com.xxxxx.app", skip_upload_metadata: true, skip_upload_screenshots:true, skip_upload_images:true)
  end
```

##### Complete output when running fastlane, including the stack trace and command used

<img width="1360" alt="Screen Shot 2019-07-31 at 1 41 33 PM" src="https://user-images.githubusercontent.com/12590308/62236802-c9e55c80-b39d-11e9-8f09-29e98d04f4f6.png">

<details>
  <pre> No other information </pre>
</details>

### Environment

<details>
  <pre> <summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.5                                          |
| Ruby                        | 2.4.2                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.21.0                               |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2@vydia-mobile/bin/fastlane |
| Host                        | Mac OS X 10.14.5 (18F132)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 10.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| byebug                    | 9.1.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| cocoapods                 | 1.5.3        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.15.0       |
| no_proxy_fix              | 0.1.1        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.5.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.4        |
| emoji_regex               | 1.0.1        |
| equatable                 | 0.5.0        |
| excon                     | 0.65.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| hitimes                   | 1.2.6        |
| httparty                  | 0.15.6       |
| mimemagic                 | 0.3.2        |
| httmultiparty             | 0.3.16       |
| method_source             | 0.9.0        |
| necromancer               | 0.4.0        |
| tty-color                 | 0.4.2        |
| pastel                    | 0.7.1        |
| pry                       | 0.11.1       |
| pusher-signature          | 0.1.8        |
| pusher                    | 1.3.1        |
| semantic                  | 1.6.0        |
| timers                    | 4.1.2        |
| tty-command               | 0.6.0        |
| wisper                    | 2.0.0        |
| tty-reader                | 0.1.0        |
| tty-prompt                | 0.13.2       |
</details>

*generated on:* **2019-07-31**
</pre>
</details>

**Comment by janpio** [comment]
Unfortunately not much we can do here - as the output just tells us the server literally returned "Server error". If this persists, you can try to find a way to look at the actual server response somehow and see what http status code is returned.

**Comment by gzssince1990** [comment]
@janpio Thanks for your response. Do you have any suggestion for how to debug this? Anyone else met similar problem before?

**Comment by janpio** [comment]
Unfortunately it doesn't seem like we have the `proxy` functionality of the API we are using implemented:
https://github.com/fastlane/fastlane/blob/d1b7d853dc35ecff77bee0c0a754a577f084c26a/supply/lib/supply/client.rb#L45-L75
https://www.rubydoc.info/gems/google-api-client/Google/Apis/ClientOptions

That means, that you will have to try to find a different way to get the request and its response. I would try Charles Web Proxy and see if it captures the traffic by default already.

You should also share the _complete_ output of the command, maybe there is something interesting in there already that helps us understand what is going on.
