### ISSUE TITLE
Enable custom prefix to xcodebuild command

### ISSUE THREAD

**Issue by mattlock83** [fastlane/fastlane#15115]
### Feature Request
Allow a custom prefix to be added to the xcodebuild command in Scan for objective-c analysis with Sonarqube.

#### Motivation Behind Feature
For Objective-C scanning sonarqube requires the xcodebuild command to be prefixed with a wrapper (see [here](https://docs.sonarqube.org/display/PLUG/SonarCFamily+for+Objective-C))
Without this prefix sonar cannot scan Objective-C code.

#### Feature Description
Create a scan option that allows us to pass a string to be prefixed to the xcodebuild command, which can then be used to pass in the location of the sonar build wrapper.

#### Alternatives or Workarounds
I currently have this working by monkey patching scan within our fastfile.

**Comment by mollyIV** [comment]
Hello @mattlock83 👋 

I think the thing you are looking for is a parameter called `xcodebuild_command`. According to [the documentation](https://docs.fastlane.tools/actions/scan/):

> xcodebuild_command | Allows for override of the default xcodebuildcommand | env NSUnbufferedIO=YES xcodebuild

You can check [this PR](https://github.com/fastlane/fastlane/pull/14874) and [this issue](https://github.com/fastlane/fastlane/issues/14861) to get more details 😉 

Please let us know if that helped 🙇

**Comment by mattlock83** [comment]
Awesome thanks so much for pointing that out, exactly what I was after. 1 more hack I can remove :)
