### ISSUE TITLE
fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down

### ISSUE THREAD

**Issue by hstdt** [fastlane/fastlane#15121]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using swift fastlane. The latetest version does not work, an error happened 'fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down'.

##### Command executed
`fastlane release`
![image](https://user-images.githubusercontent.com/10215098/62340112-fd94c380-b510-11e9-81f7-9525af4bea06.png)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
hbhstdt:trunk work$ fastlane release --verbose

[10:28:10]: fastlane detected a Gemfile in the current directory
[10:28:10]: however it seems like you don't use `bundle exec`
[10:28:10]: to launch fastlane faster, please use
[10:28:10]: 
[10:28:10]: $ bundle exec fastlane release --verbose
[10:28:10]: 
[10:28:10]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-08-02 10:28:13.25]: Checking if there are any plugins that should be loaded...
INFO [2019-08-02 10:28:13.51]: loading manifest: /Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane/swift/upgrade_manifest.json
DEBUG [2019-08-02 10:28:13.68]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2019-08-02 10:28:13.69]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.54/0.9.54
DEBUG [2019-08-02 10:28:13.69]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.8/0.9.8
DEBUG [2019-08-02 10:28:13.69]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.3/0.9.3
DEBUG [2019-08-02 10:28:13.69]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.5/0.9.5
DEBUG [2019-08-02 10:28:13.69]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2019-08-02 10:28:13.69]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.11/0.9.11
DEBUG [2019-08-02 10:28:13.69]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2019-08-02 10:28:13.69]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.4/0.9.4
DEBUG [2019-08-02 10:28:13.69]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.69]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.69]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2019-08-02 10:28:13.70]: Checking for new user-provided tool configuration files
INFO [2019-08-02 10:28:13.74]: FastlaneSwiftRunner project is up-to-date
DEBUG [2019-08-02 10:28:13.75]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2019-08-02 10:28:14.00]: $ ./fastlane/FastlaneRunner lane release logMode verbose swiftServerPort 2000 > /dev/null
INFO [2019-08-02 10:28:16.03]: ▸ Fatal error: file /*********/fastlane/swift/Runner.swift, line 79
INFO [2019-08-02 10:28:16.03]: ▸ sh: line 1: 53591 Illegal instruction: 4  ./fastlane/FastlaneRunner lane release logMode verbose swiftServerPort 2000 > /dev/null
WARN [2019-08-02 10:28:18.76]: Lane Context:
INFO [2019-08-02 10:28:18.76]: {:LANE_NAME=>"release"}
ERROR [2019-08-02 10:28:18.76]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
ERROR [2019-08-02 10:28:18.76]: fastlane finished with errors
/Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down (FastlaneCore::Interface::FastlaneError)
	from /Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
	from /Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
	from /Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	from /Users/work/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'

 </pre>
</details>

### Environment

<details>
  <pre> 
 hbhstdt:trunk work$ fastlane env
[10:24:52]: fastlane detected a Gemfile in the current directory
[10:24:52]: however it seems like you don't use `bundle exec`
[10:24:52]: to launch fastlane faster, please use
[10:24:52]: 
[10:24:52]: $ bundle exec fastlane env
[10:24:52]: 
[10:24:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:24:54]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {

    func releaseLane() {
        desc("Push a new release beta build to TestFlight")

        incrementBuildNumber()

        //build&upload
        buildApp(workspace: "*****", scheme: "******")
        uploadToTestflight(username: "*****", betaAppDescription: "******)", skipWaitingForBuildProcessing: true, teamId: "******")
    }

    func bothLane() {
        debugLane()
        releaseLane()
    }

}


```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.7.2        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-08-02**
</details>

 </pre>
</details>

**Comment by janpio** [comment]
What version of fastlane used to work for you? Can you try to reproduce the problem on another computer?

**Comment by hstdt** [comment]
@janpio Maybe 2.128.0 or 2.127.2. Just the version a few days ago. And I update Xcode 10.2.1 to Xcode 10.3 these days. Reproduce on another computer is difficult for me.

**Comment by janpio** [comment]
The Xcode version should not really influence this.
Does using `bundle exec fastlane release --verbose` help maybe?

**Comment by hstdt** [comment]
@janpio Yes, this helps.

```
hbhstdt:trunk work$ bundle exec fastlane release --verbose
Traceback (most recent call last):
	1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle (LoadError)
```

According to the information, I find this issue https://github.com/bundler/bundler/issues/6311#issuecomment-491494081, after updating to the latest RubyGems, problem solved.

**Comment by janpio** [comment]
Yay 💯 👍 

Glad we could fix this for you. Still wondering why and how that happened though...
