### ISSUE TITLE
创建证书

### ISSUE THREAD

**Issue by zwhl** [fastlane/fastlane#15120]
# Create a new certificate signing request
csr, pkey = Spaceship.certificate.create_certificate_signing_request

# Use the signing request to create a new distribution certificate
Spaceship.certificate.production.create!(csr: csr)

操作完成后，将证书安装到钥匙串没有专用密钥。

**Comment by zwhl** [comment]
> 看起来这个问题可能与代码签名有关 🚫
> 
> 您是否看过我们的新[代码签名故障排除指南](https://docs.fastlane.tools/codesigning/getting-started/)？它将帮助您解决最常见的代码签名问题👍



> 看起来这个问题可能与代码签名有关 🚫
> 
> 您是否看过我们的新[代码签名故障排除指南](https://docs.fastlane.tools/codesigning/getting-started/)？它将帮助您解决最常见的代码签名问题👍

[12] pry(#<Spaceship::Playground>)> csr, pkey = Spaceship::Portal.certificate.create_certificate_signing_request
=> [#<OpenSSL::X509::Request:0x0000***29e28de0>,
 #<OpenSSL::PKey::RSA:0x00007fc4***8e08>]
[13] pry(#<Spaceship::Playground>)> Spaceship::Portal.certificate.production.create!(csr: csr)
=> <Spaceship::Portal::Certificate::Production 
	id="5ZD***DW8", 
	name="Srinivasan ***vedi", 
	status="Issued", 
	created="2019-08-02T03:46:26Z", 
	expires="2020-08-01T03:36:26Z", 
	owner_type="team", 
	owner_name="Srinivasan ***vedi", 
	owner_id="KRRT***3N9", 
	type_display_id="R58UK***SO", 
	can_download=nil>

代码签名故障排除指南 确实没找到关于这方面的介绍，有的只是通过cert可以解决我的问题，难道通过Spaceship的API无法解决我的问题吗？  另外我想问问，没有命令可以控制退出Spaceship （pry(#<Spaceship::Playground>)>  ）吗？

**Comment by dumbass-cn** [comment]
Using `exit` to escap pry

**Comment by janpio** [comment]
What is the actual problem with what spaceship produces here @zwhl? I don't see what is wrong about what is happening here. You can look at the `cert` code to understand better how to use the spaceship certificate related code.
