### ISSUE TITLE
[snapshot] Add option for clean status bar

### ISSUE THREAD

**Issue by mathebox** [fastlane/fastlane#15124]
#### Motivation Behind Feature
In order to produce a consistent appearance of the status bar in screenshots, developers often use [Status Bar Magic](https://github.com/shinydevelopment/SimulatorStatusMagic) to modify the displayed information.

With Xcode 11, this will be supported by the simulator and, thus, removing the need for an external dependency:
```
xcrun simctl status_bar <device> override --time "9:41" --batteryState charged --batteryLevel 100
```
(taken from the [release notes for Xcode 11 beta 5](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_5_release_notes))

#### Feature Description
Add an additional option to the snapshot config which will let the simulator launch with the set of parameter for a clean status bar.

#### Alternatives or Workarounds
An alternative would be the give the user more freedom in defining the parameters for the simulator. Here we could have an option in the snapshot config to specify the parameters for the simulator manually.

**Comment by janpio** [comment]
A new feature totally makes sense, I expect lots of people will want to use this. Do you have a suggestion for a good name? We will probably need to detect the Xcode version and output an error if <Xcode11 I guess?

**Comment by mathebox** [comment]
Here are my naming suggestion:
- `show_clean_status_bar` or `clean_status_bar` (type: bool)
- `simulator_arguments` (for the alternative approach)

You have to decide which approach aligns the best with fastlane's other functionalities.

Unfortunately, I don't have the time right now to work on this.

**Comment by janpio** [comment]
[`launch_arguments`](https://docs.fastlane.tools/actions/snapshot/#parameters) already exists, we have to find out if this is similar to the suggested `simulator_arguments` to avoid duplication.

After looking into the command, it would probably even make sense to implement both your suggestions - the `show_clean_status_bar` option can use the common defaults you used above, and a comment can point to `simulator_arguments` and use an example of a different, more uncommon setup.

If someone tackles this, the documentation should be updated as well to point to this new parameter: https://github.com/fastlane/fastlane/blob/875e3482906044a4f9806dc869c8813d3a2e9a57/fastlane/lib/fastlane/actions/docs/capture_ios_screenshots.md#use-a-clean-status-bar

**Comment by colejd** [comment]
I just finished writing a command line utility to do this. I think I could be of some help here -- I'll give it a shot.

**Comment by julianschiavo** [comment]
Hey, does anyone have a solution for now to get it working with fastlane snapshot before an official PR is merged in?

**Comment by omastny** [comment]
I used this very nice solution which uses scheme pre- and post-actions -> [Fixing Simulator Status Bars for App Store Screenshots With Xcode 11 and iOS 13](https://www.detroitlabs.com/blog/2019/09/19/fixing-simulator-status-bars-for-app-store-screenshots-with-xcode-11-and-ios-13/)

Works also with automation :)

**Comment by benck** [comment]
This command works when building and running apps from Xcode:
`xcrun simctl status_bar "iPhone 11" override --time "9:41" --dataNetwork "lte" --cellularBars 4 --batteryLevel 100`

But however, fastlane snapshot seems to reset the status bar every time running, here is the possible dirty fix for that
[http://paulofierro.com/blog/2019/9/18/automating-screenshots-with-pretty-good-ios-simulator-status-bars-with-xcode-11](url)

**Comment by mezhevikin** [comment]
> I used this very nice solution which uses scheme pre- and post-actions -> [Fixing Simulator Status Bars for App Store Screenshots With Xcode 11 and iOS 13](https://www.detroitlabs.com/blog/2019/09/19/fixing-simulator-status-bars-for-app-store-screenshots-with-xcode-11-and-ios-13/)
> 
> Works also with automation :)

Thanks. It works like a charm.

**Comment by mmdumi** [comment]
Hi,
Can you give me for how you got the above instructions to work ?
fastlane's capture_ios_screenshots still reset the status bar even if I have the `xcrun simctl status_bar` script in the pre-actions option of my XCUITests target.

**Comment by mezhevikin** [comment]
Hi @mathebox 
Look at my screenshot and compare it with your settings.
Maybe you did not select the target (marked red).

![Image of Yaktocat](https://i.imgur.com/hnueRty.png)

**Comment by mmdumi** [comment]
Thank you @mezhevikin that helped.
For some reason the time is not set on the latest 13.1 iPhone simulator. If i run the command from the terminal when simulator is open the time is set correctly but from the pre-actions it does not. 
Have you seen this before ?

**Comment by mathebox** [comment]
The `time` argument also accepts a valid ISO date string. This is especially useful as the date is shown in the iPad's status bar.

If you also want to adjust the date to the initial iPhone presentation (2007-01-09 Tuesday), you can use `date -r 1168330440 +%FT%T%z` as the value for the time argument. This will set the correct date with respect to your current timezone.

Example command:
```bash
xcrun simctl status_bar booted override --time "$(date -r 1168330440 +%FT%T%z)" 
```
