### ISSUE TITLE
Appfile for_lane doesn't work for referenced lanes

### ISSUE THREAD

**Issue by matcartmill** [fastlane/fastlane#15133]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Specifying `for_lane` in `Appfile` doesn't work for referenced lanes.

#### Question Description
In my `Appfile` I have the following:

```
app_identifier 'com.mycompany.myapp'
apple_id 'me@mycompany.com'

for_lane :alpha do
    app_identifier 'com.mycompany.alphaapp'
end
```

This works fine if doing `fastlane alpha`, however when referencing the lane from another lane (eg `fastlane cicd`, where the `cicd` lane has `alpha` in it), the `for_lane` is not respected and my `app_identifier` parameter is `com.mycompany.myapp` instead of the Alpha version.

An example of my `cicd` lane is:

```
lane :cicd do
    install
    unittests
    codecoverage
    alpha
end
```

When debugging, I see that the lane name when `alpha` is run is `cicd`. This mostly makes sense, I guess, but I'm not sure if there is a better way around this.

**Comment by janpio** [comment]
Interesting problem, that probably wasn't considered when implementing switching lanes (a long time ago). Maybe it was also a conscious decision for some reason.

The question now is, could this break anything if we change this behavior? Should it be considered a bug or an existing feature? I am not sure :/

**Comment by matcartmill** [comment]
Yeah, given the history other Fastlane oddities (see the Advanced section of the doc website) I'm not sure it would be fixable without impacting a larger number of users.

What I may have to do is simply not use `app_identifier` in the `Appfile`, which wouldn't be optimal but at least would get me past this issue.

Unless you have another suggestion? I'd love to leverage Fastlane as much as possible.

**Comment by janpio** [comment]
Might be using `cicd` in `for_lane` be a workaround?

I read up on it, and the documentation might indicate that this is actually intended behavior - or the docs are accidentally written in a way that makes it sound like that:

> for_lane blocks will be called when the **name of lane invoked on the command line** matches the one specified by the block. 

(emphasis mine)

https://docs.fastlane.tools/advanced/lanes/#control-configuration-by-lane-and-by-platform

Still counterintuitive really.
