### ISSUE TITLE
build log export

### ISSUE THREAD

**Issue by jainsid24** [fastlane/fastlane#15134]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How to capture output build log of a lane?

#### Question Description
I want to capture the fastlane summary table log into a file, but I can't seem to find anything related in the documentation. Any help would be greatly appreciated.

**Comment by janpio** [comment]
Just the fastlane summary table? I don't think there is a way to do this by default, but you always save the _complete_ output (e.g. by piping to a file) and then grepping your way to what you want. What is the use case you are trying to solve here?

**Comment by jainsid24** [comment]
@janpio  Thanks for replying. Yes, we are using fastlane in our jenkins pipeline and are trying to have a UI representation of lane build progress just like Jenkins BlueOcean. Something along these lines. 
![image](https://user-images.githubusercontent.com/31519573/62670551-77c9ab80-b948-11e9-93d4-c9792786cc60.png)

Would be great if fastlane currently have that feature or we can get dynamic build logs during the lane execution.

**Comment by janpio** [comment]
So each "Browser Test" would be one of the steps in the summary here then?

**Comment by jainsid24** [comment]
This is just a representation, consider a lane with 4 steps, build, test, sign and publish, the above representation will demonstrate if these processes are successful or not by getting values during the execution of that particular lane.

**Comment by janpio** [comment]
Is there a common format that is consumed by Jenkins?

**Comment by jainsid24** [comment]
Even an html output would be fine for now.

**Comment by jainsid24** [comment]
@janpio Can you point me in the right direction here?

**Comment by janpio** [comment]
No. Besides what I already mentioned (`fastlane lane > file.txt`) there is no way to capture the output that I am aware of. If there was a specific format, we could possibly implement that as a plugin somehow maybe.

**Comment by jainsid24** [comment]
Is there a way to dynamically capture it? ie. when a lane is executing?

**Comment by janpio** [comment]
Not that I am aware of. 
The whole output logic is routed through one file in fastlane, so one would have to modify that to add this functionality somehow.
