### ISSUE TITLE
Stop reseting repositoriers as default and had a flag

### ISSUE THREAD

**Issue by brianoqr** [fastlane/fastlane#15137]
### Feature Request
Currently when you run the fastlane command it automagically resets your git repo to head with no-questions asked, killing any changes you may have made and not yet committed
#### Motivation Behind Feature

This current implementation is a dangerous and can cause people to lose work, and makes implementation awkward when you fastfile is also in the repo
#### Feature Description

Reseting the git repo should be added as flag to the command line if you want and by default fastlane can abort if there are changes that are not checked in the repository, or better just run with warning. 

The best soludtion is:
Fastlane aborts if there are changes in the Repo
A flag to run it with a forced reset
A flag to run it on a project with uncommitted changes

#### Alternatives or Workarounds
Don't debug you fastlane file on a local machine while you have uncommitted work :(

**Comment by janpio** [comment]
What command are you talking about? Just running `fastlane` definitely doesn't do anything of what you mentioned. Are you running a specific tool, action or lane you defined?
