### ISSUE TITLE
Checkout a new git branch

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#15136]
While taking a checkout of a new branch I wrapped that command in "sh ()". Is there any way I can do this without sh? because I have some long sh commands which I need to execute and i don't want to use "" for every word in that command.
```
lane :takeCheckout do | options |
	if options[:branchName]
		sh("git", "checkout", "-b", options[:branchName])
	else
		UI.user_error!("Send the branch name as: <fastlane takeCheckout branchName:NewBranchName>")
	end
end
```

**Comment by janpio** [comment]
Have you tried giving the whole command to `sh` as a simple string? Might be that this is just missing as an [example on the action page](https://docs.fastlane.tools/actions/sh/#2-examples).

**Comment by userException** [comment]
> Have you tried giving the whole command to `sh` as a simple string? Might be that this is just missing as an [example on the action page](https://docs.fastlane.tools/actions/sh/#2-examples).

Nope, I tried with sh(git checkout "master") and I get this error:

Could not find action, lane or variable 'checkout'.

**Comment by janpio** [comment]
`sh("git checkout master")` would be what I meant.

**Comment by userException** [comment]
But that is not dynamic. I want to pass the branch name dynamically via options key

**Comment by janpio** [comment]
`sh("git checkout " + options[:branchName])` or if it can contain spaces maybe `sh('git checkout " + options[:branchName] + "'")` (not sure if bot hare valid ruby)

**Comment by janpio** [comment]
That being said:

> and i don't want to use "" for every word in that command.
Why not?

**Comment by userException** [comment]
This worked: sh("git checkout -b" + branchName), thanks. No need of adding double quotes for every word.

**Comment by janpio** [comment]
Be aware that this might break depending on the `branchName`.

**Comment by userException** [comment]
Yes I have nil and empty checks to prevent this at the very start of another lane which triggers this as one of the subsequent lanes.

**Comment by janpio** [comment]
Some branch names might also have spaces or special characters that need quotes around it for `-b` to pick it up correctly.
