### ISSUE TITLE
onesignal get [ONESIGNAL APP ID]

### ISSUE THREAD

**Issue by DevFatani** [fastlane/fastlane#15135]
How to get [ONESIGNAL APP ID] after run
`onesignal(
  auth_token: "Your OneSignal Auth Token",
  app_name: "Name for OneSignal App",
  android_token: "Your Android GCM key (optional)",
  android_gcm_sender_id: "Your Android GCM Sender ID (optional)",
  apns_p12: "Path to Apple .p12 file (optional)",
  apns_p12_password: "Password for .p12 file (optional)",
  apns_env: "production/sandbox (defaults to production)"
)`

**Comment by mollyIV** [comment]
Hey @DevFatani , 

you can read a value of `ONE_SIGNAL_APP_ID` via [`Lane Context`](https://docs.fastlane.tools/advanced/lanes/#lane-context). According to [the documentation](https://docs.fastlane.tools/actions/onesignal/#lane-variables):

> Actions can communicate with each other using a shared hash `lane_context`, that can be accessed in other actions, plugins or your lanes: `lane_context[SharedValues:XYZ]`.

To wrap it up, you can get the value of `ONE_SIGNAL_APP_ID` via:

```ruby 
onesignal( auth_token: ... // calling a onesignal action

// after calling onesignal action you can read a value of one signal app id
one_signal_app_id = lane_context[SharedValues: ONE_SIGNAL_APP_ID]
```

Hope that helped 🙂
