### ISSUE TITLE
HTML report gives wrong test case count with Earlgrey

### ISSUE THREAD

**Issue by hiteshjain4** [fastlane/fastlane#15143]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

With Earlgrey, Wrong test count is being shown in html report when there is any test case failure.
For failing test cases, Earlgrey shows 2 error messages (exception and Failed message). xcpretty treat these 2 messages as separate test case failure, causing wrong test case count in the report.

I opened the same bug for xcpretty as well [#351](https://github.com/xcpretty/xcpretty/issues/351), but there is no update.

##### Command executed

fastlane xcpretty_issue

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
#####Pass scenario:

[11:55:22]: Running Tests: ▸ Touching BlibliMobileUITests.xctest (in target: BlibliMobileUITests)
[11:55:38]: ▸ Selected tests
[11:55:38]: ▸ Test Suite BlibliMobileUITests.xctest started
[11:55:38]: ▸ S010_myCase_UITests
[11:55:50]: ▸ ✓ test01 (12.467 seconds)
[11:55:51]: ▸ ✓ test02 (0.644 seconds)
[11:55:51]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 13.110 (13.114) seconds
[11:55:51]: ▸ 

#####Fail Scenario:

Selected tests
Test Suite BlibliMobileUITests.xctest started
S010_myCase_UITests
✗ test01, Exception: NoMatchingElementException
✗ test01, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
✗ test02, Exception: NoMatchingElementException
✗ test02, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"

BlibliMobileUITests.S010_myCase_UITests
test01, Exception: NoMatchingElementException
/mycase-automation/BlibliMobile-iOS/BlibliMobileUITests/myCase/steps-myCase/S010_myCase_UITests.swift:25
```
    func test01(){
        EarlGrey.selectElement(with: grey_text("Account")).assert(grey_sufficientlyVisible())
    }
  ```

test01, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
<unknown>:0

test02, Exception: NoMatchingElementException
/mycase-automation/BlibliMobile-iOS/BlibliMobileUITests/myCase/steps-myCase/S010_myCase_UITests.swift:28
```
    func test02(){
        EarlGrey.selectElement(with: grey_text("Account")).assert(grey_sufficientlyVisible())
    }
  ```

test02, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
<unknown>:0

	 Executed 2 tests, with 4 failures (4 unexpected) in 19.324 (19.354) seconds

 </pre>
</details>

### Environment

With Earlgrey, whenever there is a failure in any of test case, it counts that particular test case as 2 test case, and thus increases the overall test count.
In above details i'm executing total 2 test case. If there are no issues it gives proper results in html report. But if there is any failure then it gives wrong result (for my case it is giving test case count as 4, and failed test case count also as 4).

<details>
  <pre> Hiteshs-MacBook-Pro:~ hiteshjain$ fastlane env
[12:54:19]: fastlane detected a Gemfile in the current directory
[12:54:19]: however it seems like you don't use `bundle exec`
[12:54:19]: to launch fastlane faster, please use
[12:54:19]: 
[12:54:19]: $ bundle exec fastlane env
[12:54:19]: 
[12:54:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:54:22]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G7024)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required. Update this, if you use features of a newer version
fastlane_version "2.121.1"

default_platform :ios

platform :ios do
lane :xcpretty_issue do
  run_tests(scheme: "BlibliMobile-iOS",
    device: "iPad Pro (12.9-inch) (3rd generation)",
    output_directory: "/xcpretty_report/try2",
    # output_types: "html",
    workspace: "/mycase-automation/BlibliMobile-iOS/BlibliMobile-iOS.xcworkspace")
end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.abc.efg" # The bundle identifier of your app
apple_id "abc@mail.com" # Your Apple email address

team_id "XXXXXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-teams                      | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-latest_hockey_build_number | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-test_center                | 3.7.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| slack-notifier                             | 2.3.2        |
| atomos                                     | 0.1.3        |
| colored2                                   | 3.1.2        |
| nanaimo                                    | 0.2.6        |
| xcodeproj                                  | 1.11.0       |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.3.0        |
| terminal-notifier                          | 2.0.0        |
| unicode-display_width                      | 1.1.3        |
| terminal-table                             | 1.7.3        |
| multipart-post                             | 2.0.0        |
| word_wrap                                  | 1.0.0        |
| public_suffix                              | 2.0.5        |
| tty-screen                                 | 0.7.0        |
| tty-cursor                                 | 0.7.0        |
| tty-spinner                                | 0.9.1        |
| babosa                                     | 1.0.2        |
| colored                                    | 1.2          |
| commander-fastlane                         | 4.4.6        |
| faraday                                    | 0.12.1       |
| unf_ext                                    | 0.0.7.4      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20170404 |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| gh_inspector                               | 1.1.3        |
| json                                       | 1.8.1        |
| mini_magick                                | 4.9.5        |
| multi_xml                                  | 0.6.0        |
| rubyzip                                    | 1.2.3        |
| security                                   | 0.1.3        |
| xcpretty-travis-formatter                  | 0.0.4        |
| bundler                                    | 1.14.6       |
| faraday_middleware                         | 0.11.0.1     |
| naturally                                  | 2.2.0        |
| simctl                                     | 1.6.5        |
| jwt                                        | 2.1.0        |
| declarative                                | 0.0.10       |
| declarative-option                         | 0.1.0        |
| representable                              | 3.0.4        |
| mime-types                                 | 3.1          |
| signet                                     | 0.11.0       |
| memoist                                    | 0.16.0       |
| googleauth                                 | 0.6.7        |
| httpclient                                 | 2.8.3        |
| google-api-client                          | 0.23.9       |
| google-cloud-env                           | 1.2.0        |
| google-cloud-core                          | 1.3.0        |
| digest-crc                                 | 0.4.1        |
| google-cloud-storage                       | 1.16.0       |
| emoji_regex                                | 1.0.1        |
| highline                                   | 1.7.10       |
| excon                                      | 0.65.0       |
| CFPropertyList                             | 3.0.0        |
| libxml-ruby                                | 3.0.0        |
| plist                                      | 3.5.0        |
| claide                                     | 1.0.3        |
| fastimage                                  | 2.1.5        |
| dotenv                                     | 2.7.5        |
| addressable                                | 2.6.0        |
| multi_json                                 | 1.13.1       |
| os                                         | 1.0.1        |
| psych                                      | 2.0.8        |
| retriable                                  | 3.1.2        |
| mime-types-data                            | 3.2019.0331  |
| uber                                       | 0.1.0        |
| fastlane-plugin-teams                      | 0.2.0        |
| fastlane-plugin-latest_hockey_build_number | 0.1.1        |
| xctest_list                                | 1.1.8        |
| fastlane-plugin-test_center                | 3.7.0        |
</details>

*generated on:* **2019-08-06**
</details> </pre>
</details>

**Comment by janpio** [comment]
Is `run_tests` doing anything else than triggering other libraries here? If not, there is probably not much we can do about this here as the problem should be fixed "upstream".

**Comment by hiteshjain4** [comment]
Hey @janpio , this is what Fastfile lane entry is : 

> default_platform :ios
> platform :ios do
> lane :xcpretty_issue do
>   run_tests(scheme: "BlibliMobile-iOS",
>     device: "iPad Pro (12.9-inch) (3rd generation)",
>     output_directory: "/xcpretty_report/try2",
>     # output_types: "html",
>     workspace: "/mycase-automation/BlibliMobile-iOS/BlibliMobile-iOS.xcworkspace")
> end
> end

The issue here is with xcpretty only. I did open one bug for the same but there is no response from anyone. [#351](https://github.com/xcpretty/xcpretty/issues/351).
