### ISSUE TITLE
Progress bar when uploading to App Store

### ISSUE THREAD

**Issue by royberris** [fastlane/fastlane#15140]
#### Motivation Behind Feature

My network is slow, might fail sometimes and most of the time the app takes over 30 minutes to upload so I don't know if the connection is lost / very slow or if it stopped working. Sometimes it just does stop without warning.

#### Feature Description

Simple progress dialog when uploading to the app store.

#### Alternatives or Workarounds

None

**Comment by janpio** [comment]
The simple progress bar is unfortunately not simple at all to implement, as the tool that is used to upload the file doesn't give us any usable feedback about the upload that is happening as far as I know.

**Comment by royberris** [comment]
Is this something you would put in a backlog for future implementation? If you might switch tools for any reason in the future.On 5 Aug 2019 22:43, Jan Piotrowski <notifications@github.com> wrote:The simple progress bar is unfortunately not simple at all to implement, as the tool that is used to upload the file doesn't give us any usable feedback about the upload that is happening as far as I know.

**Comment by janpio** [comment]
This issue now exists, but this doesn't change anything that it is very possible that the feature just is not possible to be implemented if the information is not available. There is no big development team here that manages a big backlog with commitments to implement something - maybe someone from the fastlane community will look into it, maybe not.
