### ISSUE TITLE
Carthage archive action fails with "Unrecognized arguments: --derived-data" in case setup_jenkins action is used

### ISSUE THREAD

**Issue by rockebee** [fastlane/fastlane#15145]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
As part of https://github.com/fastlane/fastlane/issues/4173 back in 2016, carthage action has been provided with an option for supporting carthage parameter ```--derived-data```. This parameter is not supported as part of ```carthage archive``` command, but fastlane is adding it automatically to the execution parameters in case ```setup_jenkins``` action is used via env variable ```FL_CARTHAGE_DERIVED_DATA``` (which is fine for ```bootstrap```, ```update``` and ```build``` actions, just not for ```archive``` action :/)

Hence, IMHO the ```derived-data``` parameter should only by added by ```setup_jenkins``` action for the carthage commands that support it.

##### Command executed
````
    setup_jenkins(
        unlock_keychain: false,
        set_code_signing_identity: false,
        result_bundle: true
    )
    [...]
    carthage(
        command: "bootstrap",   ## --> working fine
        use_binaries: false,
        no_build: true,
        project_directory: project_directory,
        platform: platform,
        configuration: configuration
    )
    carthage(
        command: "build",       ## --> working fine
        use_binaries: false,
        no_skip_current: true,
        project_directory: project_directory,
        platform: platform,
        configuration: configuration
    )
    [...]
    frameworks = ["libPhoneNumberiOS", "ObjectMapper", "OHHTTPStubs", "Version", "BoschEsSdk"]
    carthage(
        command: "archive",     ## --> failing in case setup_jenkins is used
        frameworks: frameworks,
        project_directory: "MyOwnSdk",
        output: "./MyOwnSdk/Carthage/Build/iOS/MyApp-#{version_number}-#{build_number}-SDK-ios-#{configuration}.framework.zip"
    )
````

##### Complete output when running fastlane, including the stack trace and command used
````
$ fastlane release
[...]
INFO [2019-08-05 18:06:55.06]: -----------------------------------------------------
INFO [2019-08-05 18:06:55.06]: Step: Switch to ios archive_sdk_framework_carthage lane
INFO [2019-08-05 18:06:55.06]: -----------------------------------------------------
INFO [2019-08-05 18:06:55.06]: Cruising over to lane 'ios archive_sdk_framework_carthage' 🚖
INFO [2019-08-05 18:06:55.06]: ----------------------
INFO [2019-08-05 18:06:55.06]: --- Step: carthage ---
INFO [2019-08-05 18:06:55.06]: ----------------------
INFO [2019-08-05 18:06:55.06]: $ carthage archive libPhoneNumberiOS ObjectMapper OHHTTPStubs Version MyOwnSdk --output ./MyOwnSdk/Carthage/Build/iOS/MyApp-1.4.0-3-SDK-ios-Production.framework.zip --derived-data /Users/jenkins/workspace/myapp-ios-sdk/build-release-sdk/MyOwnSdk/derivedData --project-directory MyOwnSdk
INFO [2019-08-05 18:06:55.44]: ▸ Unrecognized arguments: --derived-data
````

##### For reference: Carthage help on command line parameters
````
$ carthage help archive
Archives built frameworks into a zip that Carthage can use

[--output (string)]
        the path at which to create the zip file (or blank to infer it from the first one of the framework names)

[--project-directory (string)]
        the directory containing the Carthage project

[--color (color)]
        whether to apply color and terminal formatting (one of 'auto', 'always', or 'never')

[<framework names…>]
        the names of the built frameworks to archive without any extension (or blank to pick up the frameworks in the current project built by `--no-skip-current`)
````

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.14.5                                         |
| Ruby                        | 2.4.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.20.1 (Apple Git-117)              |
| Installation Source         | /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane     |
| Host                        | Mac OS X 10.14.5 (18F132)                       |
| Ruby Lib Dir                | /usr/local/rvm/rubies/ruby-2.4.1/lib            |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode10.2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
[...] ## relevant parts provided above
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
[...]
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| json                      | 2.0.2        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| jwt                       | 2.1.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.4       |
| openssl                   | 2.0.3        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.2       |
| plist                     | 3.4.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| bundler                   | 2.0.2        |
| unicode-display_width     | 1.4.0        |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| psych                     | 2.2.2        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| simctl                    | 1.6.5        |
</details>

*generated on:* **2019-08-06**
</details>

**Comment by janpio** [comment]
I think `setup_jenkins` setting that ENV variable (ping @mollyIV) is fine, but the way the `carthage` action applies it even for `archive` should probably be fixed!? Was `archive` maybe only recently added as functionality and this just wasn't considered?

**Comment by mollyIV** [comment]
> I think setup_jenkins setting that ENV variable (ping @mollyIV) is fine, but the way the carthage action applies it even for archive should probably be fixed!?

I agree, I would suggest to apply the fix in `carthage` action itself. It's what we are doing for some params already:

https://github.com/fastlane/fastlane/blob/d1b7d853dc35ecff77bee0c0a754a577f084c26a/fastlane/lib/fastlane/actions/carthage.rb#L12-L16

I had a look at `carthage archive` command source code and indeed there's no `derived-data` parameter support.

https://github.com/Carthage/Carthage/blob/55e416a9905b3541153aeb24312334aba06259db/Source/carthage/Archive.swift#L10-L35

@rockebee would you like to try and make a PR with `carthage` action fix? 🙂 I will be happy to support you and help you on that 🙇

**Comment by iOSGeekster** [comment]
If @rockebee isn't up for the task, I would be happy to give it a go.

**Comment by iOSGeekster** [comment]
I've added a draft pull request ☝️ 
I'm not that familiar with rspec, so I need some hints of how to test the functionality. I guess the test somehow has to mock the ENV variable set by `setup_jenkins`?

**Comment by rockebee** [comment]
@mollyIV, @iOSGeekster, at first many thanks to the two of you for your speedy help, and sorry for not coming back earlier. Next time I'd be happy to try fixing this kind of issues myself :)

Looking forward to getting this merged and released!
