### ISSUE TITLE
Upload iOS Screenshots to the Play Store

### ISSUE THREAD

**Issue by fuhrmann2** [fastlane/fastlane#15146]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Is it possible to upload the iOS Screenshots to the Play Store with Fastlane?

#### Question Description

I want to create the iOS Screenshots with the Fastlane Snapshot tool and directly upload them to the App Store and also Google Play Store. Is that possible?

So something like this:
`capture_screenshots`
`upload_to_play_store`
`upload_to_app_store`

**Comment by max-ott** [comment]
Hi @fuhrmann2 you might want to checkout `supply` -> https://docs.fastlane.tools/actions/supply/#supply

**Comment by janpio** [comment]
Should be possible just fine by copying the files to the right locations before using `upload_to_play_store` (although your users might not be too happy if the UI doesn't match (which of course doesn't have to be the case depending on your app, just mentioning it))
