### ISSUE TITLE
Running fastlane on precommit hook

### ISSUE THREAD

**Issue by aabanaag** [fastlane/fastlane#15156]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Running fastlane on precommit hook

#### Question Description

I created a script as my precommit hook which basically runs `fastlane test` on my terminal everything works as is as soon as I call `git commit` it runs the hook but on Xcode it fails it says. Also I installed fastlane via homebrew

```
Running precommit hook
.git/hooks/pre-commit: line 4: fastlane: command not found
Commit not authorized
```

**Comment by janpio** [comment]
The fastlane command from Homebrew doesn't seem to be available in the contetx of the precommit hook. You should probably try one of the other installation methods and see if this fixes the problem.
