### ISSUE TITLE
[register_devices] Format of devices file is outdated

### ISSUE THREAD

**Issue by mkj-is** [fastlane/fastlane#15150]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

_In short:_ The file format required by `register_devices` is outdated.

Register devices action checks for a file header containing [exact two columns](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/register_devices.rb#L34). It also links to a [server, which has invalid certificate](https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip).

I want to use file which is compatible both with the developer portal and Fastlane. This is not possible at the moment, I was not able upload new sample file using Fastlane. Adding devices using file supported by Fastlane to developer portal does not work either.

The sample file I downloaded today from Apple looks like this:

```
Device ID	Device Name	Device Platform
A123456789012345678901234567890123456789	NAME1	ios
B123456789012345678901234567890123456789	NAME2	ios
A5B5CD50-14AB-5AF7-8B78-AB4751AB10A8	NAME3	mac
A5B5CD50-14AB-5AF7-8B78-AB4751AB10A7	NAME4	mac
```

It is accessible without developer account here, so there is no reason not to link to developer portal directly:

https://developer.apple.com/account/resources/downloads/Multiple-Upload-Samples.zip

**What I propose:**

- If the file contains third column then use it for the device platform, otherwise use the default platform (backward compatible solution).
- Update the links to official sample files.

I am offering to invest time in this and open a PR. I am only concerned about writing tests and I might need some guidance if they are required. There are currently none for this action, at least I could not find them.

##### Command executed

`fastlane run register_devices devices_file:multiple-device-upload.txt --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[19:53:50]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:53:50]: ------------------------------
[19:53:50]: --- Step: register_devices ---
[19:53:50]: ------------------------------
[19:53:50]: To not be asked about this value, you can specify it using 'username'
[19:53:50]: Optional: Your Apple ID: ▓▓▓▓▓▓▓▓▓▓
Available session is not valid any more. Continuing with normal login.
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) ▓▓▓▓▓▓▓▓▓▓ "▓▓▓▓▓▓▓▓▓▓" (Company/Organization)
2) ▓▓▓▓▓▓▓▓▓▓ "▓▓▓▓▓▓▓▓▓▓" (Company/Organization)
4) ▓▓▓▓▓▓▓▓▓▓ "▓▓▓▓▓▓▓▓▓▓" (In-House)
1
[19:54:18]: Fetching list of currently registered devices...
Traceback (most recent call last):
	21: from /usr/local/bin/fastlane:23:in `<main>'
	20: from /usr/local/bin/fastlane:23:in `load'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/actions/register_devices.rb:34:in `run'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Please provide a file according to the Apple Sample UDID file (https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip) (FastlaneCore::Interface::FastlaneError)
	21: from /usr/local/bin/fastlane:23:in `<main>'
	20: from /usr/local/bin/fastlane:23:in `load'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/actions/register_devices.rb:34:in `run'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Please provide a file according to the Apple Sample UDID file (https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip) (FastlaneCore::Interface::FastlaneError) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.6                                          |
| Ruby                        | 2.6.3                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.22.0                               |
| Installation Source         | /usr/local/bin/fastlane                          |
| Host                        | Mac OS X 10.14.6 (18G87)                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 11.0                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.12.0       |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.6.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.65.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| mime-types-data           | 3.2019.0331  |
| os                        | 1.0.1        |
| google-cloud-env          | 1.2.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
</details>

*generated on:* **2019-08-06**
</details> </pre>
</details>

**Comment by janpio** [comment]
Seems Apple changed both the URL and the format back in May - so this sounds like a very reasonable thing to do.

We definitely don't require you to add new tests just to fix something, so go ahead and do it without tests - but of course feel free to add some if you feel the urge to do so 🙈
