### ISSUE TITLE
Coveralls always shows 0% when xcov shows 40% ?

### ISSUE THREAD

**Issue by jackjpark** [fastlane/fastlane#15154]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Completing a coverage report with xcov then uploading to coveralls.io results in 0% for all coveralls files and project overall (xcov output will report the correct value though), all looks correct on the fastlane build and its successfully uploaded to coveralls.io

##### Command executed

Fastlane xcov

```  
xcov(
      workspace: ".xcworkspace",
      scheme: "",
      output_directory: "./fastlane/xcov_output",
      html_report: true,
      only_project_targets: true,
      coveralls_service_name: "travis-pro",
      skip_slack: true,
      ignore_file_path: "./fastlane/.xcovignore",
      coveralls_service_job_id: ENV["TRAVIS_JOB_ID"]
    )
```

**Comment by janpio** [comment]
What output are you getting when running the lane that includes that action call? (best with `--verbose`)
