### ISSUE TITLE
fastlane crashing

### ISSUE THREAD

**Issue by dragonfly-net** [fastlane/fastlane#15157]
I need only upload .ipa to appstore, file in same dir, run as root

# fastlane pilot upload

```
[⠼] 🚀 /usr/local/rvm/gems/ruby-2.1.10/gems/fastimage-2.1.5/lib/fastimage.rb:68: warning: already initialized constant URI::DEFAULT_PARSER
/usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[✔] 🚀
[01:32:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[01:32:07]: To not be asked about this value, you can specify it using 'username'
[01:32:07]: Your Apple ID Username: user@domain.com
[01:32:13]: Login to App Store Connect (user@domain.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
-------------------------------------------------------------------------------------
Password (for user@domain.com): *********
[01:32:19]: Login successful
[01:32:20]: Ready to upload new build to TestFlight (App: 1401049399)...
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
-------------------------------------------------------------------------------------
Password (for user@domain.com): *********
[01:32:39]: Going to upload updated app to App Store Connect
[01:32:39]: This might take a few minutes. Please don't interrupt the script.

[01:32:39]: Error accessing file, this might be due to fastlane's directory handling
[01:32:39]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/fileutils.rb:125:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)
        from /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/fileutils.rb:125:in `cd'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:324:in `execute'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:420:in `upload'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/build_manager.rb:34:in `upload'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/fastlane:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/fastlane:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:24:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:24:in `<main>'
```

os: amazon linux (centos based)

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/blob/d1b7d853dc35ecff77bee0c0a754a577f084c26a/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L324

Can you run the command with `--verbose` for additional output?

In general Linux is not fully supported for all the iOS stuff. You might be able to work around that by manually getting and installing iTunes Transporter under the path it is looking at.

**Comment by dragonfly-net** [comment]
when fastlane pilot upload --verbose

INFO [2019-08-09 20:21:56.17]: Going to upload updated app to App Store Connect
INFO [2019-08-09 20:21:56.17]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2019-08-09 20:21:56.17]: /java/bin/java -Djava.ext.dirs=/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -classpath /lib/itmstransporter-launcher.jar com.apple.transporter.Application -m upload -u denis@savonix.com -p YourPassword -f /tmp/d20190809-2052-1e589pi/1401049399.itmsp -t DAV -t Signiant -k 100000 2>&1

WARN [2019-08-09 20:21:56.17]: Error accessing file, this might be due to fastlane's directory handling
WARN [2019-08-09 20:21:56.17]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/fileutils.rb:125:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)
        from /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/fileutils.rb:125:in `cd'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:324:in `execute'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:420:in `upload'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/build_manager.rb:34:in `upload'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/fastlane:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/fastlane:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:24:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:24:in `<main>'

**Comment by janpio** [comment]
> I was able to find an old version after some Googling, but decided trying to get an old version working would be a fool's errand.

Old versions usually auto update themselves to a current version. iTMS for Linux still exists, it is just hidden behind contracts and logins.

**Comment by dragonfly-net** [comment]
> but that fails as itms_path is an empty string when not running on Mac or Windows.
Maybe add non-empty check for itms_path and return some instructions if empty?

**Comment by janpio** [comment]
Yes, we currently don't know what these instructions could/should look like though. "Google until you find a binary for your system" is not really a valid solution here for all users ;)

**Comment by dragonfly-net** [comment]
> iTMS for Linux still exists, it is just hidden behind contracts and logins.

I can't found it, can you give a link?

**Comment by dragonfly-net** [comment]
Transporter is no longer included with Xcode 11
At least, need support for altool
And what about linux users?

**Comment by yakimant** [comment]
> Transporter is no longer included with Xcode 11

It is included, but changed the path:

> /Applications/Xcode-10.3.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter
> /Applications/Xcode-11.GM.Seed.app/Contents/Developer/usr/bin/iTMSTransporter

**Comment by giginet** [comment]
Could you try `extern FASTLANE_ITUNES_TRANSPORTER_PATH=/Applications/Xcode-11.GM.Seed.app/Contents/Developer/usr/bin/iTMSTransporter` ?
