### ISSUE TITLE
Produce <-> associate_group

### ISSUE THREAD

**Issue by NikhilManapure** [fastlane/fastlane#15151]
```
produce(
      username: 'asdf@gmail.com',
      app_identifier: "com.asdf.xyz",
      app_name: "Asdf",
      language: 'English',
      app_version: "1.0",
      sku: "asdf",
      enable_services: {
        app_group: "on",
        associated_domains: "on",
        push_notification: "on"
      }
)

sh("fastlane produce associate_group -a com.asdf.xyz group.com.my")
    
```

Is there any way to do these two things in one call.

**Comment by janpio** [comment]
As far as I know the `associate_group` command is only available via the `produce` CLI tool and not via an action. But you of course can put these to action calls into one lane, then it is just one call of fastlane for that lane to do it both.

**Comment by NikhilManapure** [comment]
Actually problem I am facing is, if the app is already present and group is already associated, still `associate_group` would edit the app on developer portal, so the profiles become invalid every time and needs to get created again. So I should get to know if the app is already present or not. Is there any way for that?

@janpio
