### ISSUE TITLE
Suppport for submitting draft pull request?

### ISSUE THREAD

**Issue by iOSGeekster** [fastlane/fastlane#15167]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Create pull request action

#### Question Description
Hi guys.
I would just like to ask, if there are plans of adding a `draft` option to `create_pull_request` when the functionality in the GitHub API, moves out of preview?

**Comment by janpio** [comment]
No plans yet, but obviously makes a lot of sense. Can you maybe provide a link to the documentation page of GitHub'S API that would be relevant here?

**Comment by iOSGeekster** [comment]
Sure.
It is described here https://developer.github.com/v3/pulls/#create-a-pull-request

So basically right now, when it's still in preview, it requires a custom media type, in the `Accept` header, and is still subject to change.

**Comment by iOSGeekster** [comment]
As the GitHub Api for draft pull request, is still in preview, I guess we can close this issue, and take up the subject again, when/if it gets out of preview?

**Comment by janpio** [comment]
We can also keep it open, so we don't forget. Your choice @iOSGeekster

**Comment by iOSGeekster** [comment]
> We can also keep it open, so we don't forget. Your choice @iOSGeekster

Well, you've got a point there. ☺️ I'll reopen it, and keep and eye on the GitHub API.

**Comment by iOSGeekster** [comment]
So it seems like draft Pull Request are available for some users.
>Draft pull requests are available in public repositories with GitHub Free and GitHub Pro, and in public and private repositories with GitHub Team and GitHub Enterprise Cloud. For more information, see GitHub's billing plans in the GitHub Help documentation.

So I guess now's the time for a PR 😉
We've already got a private action which creates PR's in draft mode, so I'll like to give this a go.
Any thoughts or comments?

**Comment by janpio** [comment]
Go for it @iOSGeekster!

**Comment by iOSGeekster** [comment]
Oh right! I’ll fix it!

**Comment by iOSGeekster** [comment]
It seems as this feature is actually still in preview at github. So for this to work, the Github Action would still need to have this:
`headers: {
            "Accept": "application/vnd.github.shadow-cat-preview+json"
          }`

So my take on this, is to wait for it to go out of preview, entirely.
What do you guys think?

**Comment by janpio** [comment]
Yes, probably not worth it to add it to the action while still in preview.
