### ISSUE TITLE
Hockeyapp Upload failing for the dsym files size with msg "413 Request Entity Too Large"

### ISSUE THREAD

**Issue by sree86** [fastlane/fastlane#15161]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to upload the iOS artifact along with the dsym file to hockeyapp but failing with the msg "413 Request Entity Too Large". We have dsym file size to be >300M and ipa >60M.
##### Command executed

We are running the upload command via gradle script
./gradlew deploy-hockeyapp --buildPlatform=ios -PappEnvironment=qa

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Starting a Gradle Daemon (subsequent builds will be faster)

Loading QA properties

Reckoned version: 0.1.0-dev.0.7099+20190812T055839Z

:scaffold

:deploy-hockeyapp

PATH: /usr/local/bin/fastlane

PROJECT: /Users/admin/Jenkins/workspace/GSNCasino_Development

TARGET PLATFORM: ios

Android ID: xxxxxxxx

iOS ID: xxxxxxx

Amazon ID: xxxxxxxx

Found binary at: ./build/iOS/QA_xxxx_iOS.ipa

[/usr/local/bin/fastlane, ios, deployHockey, path:./build/iOS/QA_xxxx_iOS.ipa, hockeyAppId:xxxxx, hockeyAppApiToken:xxxxx, environment:qa]

Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5

[22:58:42]: fastlane detected a Gemfile in the current directory

[22:58:42]: however it seems like you don't use `bundle exec`

[22:58:42]: to launch fastlane faster, please use

[22:58:42]: 

[22:58:42]: $ bundle exec fastlane ios deployHockey path:./build/iOS/QA_xxxx_iOS.ipa hockeyAppId:xxxxx hockeyAppApiToken:xxxxx environment:qa

[22:58:42]: 

[22:58:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[22:58:44]: ------------------------------

[22:58:44]: --- Step: default_platform ---

[22:58:44]: ------------------------------

[22:58:44]: Driving the lane 'ios deployHockey' 🚀

[22:58:44]: uploading iOS

[22:58:44]: --------------------

[22:58:44]: --- Step: hockey ---

[22:58:44]: --------------------

[22:58:44]: Starting with file(s) upload to HockeyApp... this could take some time.

+------------------+------------------+

|            Lane Context             |

+------------------+------------------+

| DEFAULT_PLATFORM | ios              |

| PLATFORM_NAME    | ios              |

| LANE_NAME        | ios deployHockey |

+------------------+------------------+

[22:58:57]: Error when trying to upload file(s) to HockeyApp: 413 - <html>

<head><title>413 Request Entity Too Large</title></head>

<body bgcolor="white">

<center><h1>413 Request Entity Too Large</h1></center>

<hr><center>nginx</center>

</body>

</html>

+------+------------------+-------------+

|           fastlane summary            |

+------+------------------+-------------+

| Step | Action           | Time (in s) |

[!] Error when trying to upload file(s) to HockeyApp: 413 - <html>

+------+------------------+-------------+

<head><title>413 Request Entity Too Large</title></head>

| 1    | default_platform | 0           |

<body bgcolor="white">

| 💥   | hockey           | 13          |

<center><h1>413 Request Entity Too Large</h1></center>

<hr><center>nginx</center>

+------+------------------+-------------+

</body>

</html>

[22:58:57]: fastlane finished with errors

#######################################################################

# fastlane 2.128.1 is available. You are on 2.111.0.

# You should use the latest version.

# Please update using `sudo gem install fastlane`.

#######################################################################

2.128.1 Hotfix for match readonly issue

* [match] fix for match username not found if readonly (#15073) via Josh Holtz

2.128.0 Improvements

* [match] import certs and p12 files into match repo (#15023) via Josh Holtz

* [spaceship] fix `Spaceship::Portal.provisioning_profile.all` not reporting expired profiles (#14904) via Radek Pietruszewski

* [snapshot] fix warning about unused variable in SnapshotHelper.swift (#15045) via Morten Bjerg Gregersen

* [actions] fix variable usage in `increment_build_number` call (#15032) via Ram Nadella

* [spaceship] fix typo in `ready_for_beta_submission?` error mes… (#15054) via Steven Sherry

2.127.2 Update mini_magick to prevent vulnerability

* [fastlane] update mini_magick (#15042) via Daniel

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`

:deploy-hockeyapp FAILED

:cleanfastlane

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':deploy-hockeyapp'.

> Fastlane finished with non-zero exit value 1

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

3 actionable tasks: 3 executed </pre>
</details>

### Environment

<details>
  <pre> Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5[⠸] 🚀 
[✔] 🚀 
[00:43:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[00:43:17]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G84)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-10.2.1.app/Contents/Developer/             |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.111.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.17.2       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-08-12**
</details>
[00:43:17]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[00:43:17]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)

 </pre>
</details>

**Comment by sree86** [comment]
I dont think its code signing issue as i am able to create ios ipa file and while upload it fails with the message "Request Entity Too Large". If i am uploading only the ipa it works, but when i add dsym as well it fails.

**Comment by janpio** [comment]
1. You should really update your fastlane version.
2. How exactly are you going from gradle to fastlane? I didn't understand that.
3. Can you upload these files to HockeyApp manually?
4. Don't exactly know about the state of the HockeyApp to AppCenter move, but that doesn't influence this, right?

**Comment by sree86** [comment]
Thank you @janpio . Yeah what you said is true, we will need to update the fastlane version. Now we can see the upload is working with the same current version of fastlane. Also we are working on reducing the size of the ipa as its not good to have such a huge size. Thanks again :)
