### ISSUE TITLE
New Github actions and match

### ISSUE THREAD

**Issue by hackdie** [fastlane/fastlane#15160]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Im trying to use the new github actions but im having some issues using `match` 

```
INFO [2019-08-10 22:41:16.62]: ▸ Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
INFO [2019-08-10 22:41:16.70]: ▸ git@github.com: Permission denied (publickey).
INFO [2019-08-10 22:41:16.70]: ▸ fatal: Could not read from remote repository.
INFO [2019-08-10 22:41:16.70]: ▸ Please make sure you have the correct access rights
INFO [2019-08-10 22:41:16.70]: ▸ and the repository exists.
```

does anyone have found any solution for this?

**Comment by janpio** [comment]
What exactly are you executing there and how?

**Comment by hackdie** [comment]
```
 match(
      app_identifier: ["com.xxxxxx", "com.xxxx.yyyyy"],
      type: "development", #appstore, development
      git_url: "git@github.com:my_company/my_project_where_i_store_my_cert.git",
      username: 'xxxxxxxxxx',
      shallow_clone: true,
      force_for_new_devices: !is_ci, # update only forced on non-CI systems, and only if there is a new device
      readonly: true,  #readonly mode to be sure it won't create any new certificates or profiles.
      keychain_name: 'xxxxxxx',
      keychain_password: 'yyyyyyyyy',
    )
````

**Comment by hackdie** [comment]
it works fine on CircleCi when i try to clone the project where i have my `certs` but in the new Github actions i need to change the `git_url` with a token to make it work

**Comment by janpio** [comment]
How did you setup the actions? What is containing this `match` call?

Right now I am missing context - never actually played with Github Actions yet.

**Comment by hackdie** [comment]
running this before running my fastlane did the magic. 

`mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config`

now everything is up and running :)

**Comment by janpio** [comment]
Uh interesting, care to explain what does and safe me from googling it?

**Comment by andrewtheis** [comment]
@hackdie Did you create a new keychain, and if so how did you get it to find the WWDR certificate?
