### ISSUE TITLE
Compile error ONLY using Fastlane.

### ISSUE THREAD

**Issue by fernandohbrasil** [fastlane/fastlane#15163]
### Question Checklist

- [x] Updated fastlane to the latest version;
- [x] I read the [Contribution; Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md);
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools);
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues);
- [x] I re-clone and re-compile everything;

### Question Subject
I am having troubles for compile JUST using fastlane, when I use android Studio to compile everything works perfectly.

The error happens when I execute this command: “bundle exec fastlane beta variant:Release flavor:Staging”

This is the technologies that I am using and think relevant to analyse this error: Android Studio, Dagger 2, Kotlin, Gradle and fastlane. 

I am use all this in other project, except Kotlin.

And the error happens in the folders that Dagger should create.  

#### Question Description
Here the error and some files that I think relevant. 

### **Error:** 

oidx.constraintlayout:constraintlayout:1.1.3) with AarTransform
> Transform sqlite.aar (androidx.sqlite:sqlite:2.0.0) with AarTransform
> Transform sqlite-framework.aar (androidx.sqlite:sqlite-framework:2.0.0) with AarTransform
 
a lot of this …..

> Task :app:mergeStagingReleaseShaders
> Task :app:compileStagingReleaseShaders
> Task :app:generateStagingReleaseAssets
> Task :app:mergeStagingReleaseAssets
> Task :app:createStagingReleaseCompatibleScreenManifests

> Task :app:processStagingReleaseManifest
/.../app/src/main/AndroidManifest.xml:19:5-134:19 Warning:
        application@android:allowBackup was tagged at AndroidManifest.xml:19 to replace other declarations but no other declaration present

> Task :app:fabricGenerateResourcesStagingRelease
> Task :app:generateStagingReleaseResValues
> Task :app:generateStagingReleaseResources
> Task :app:mergeStagingReleaseResources
> Task :app:processStagingReleaseResources
> Task :app:kaptGenerateStubsStagingReleaseKotlin
> Task :app:kaptStagingReleaseKotlin

> Task :app:compileStagingReleaseKotlin
w: /.../app/src/main/java/com/ocrex/autoentry/view/AutoFitPreviewBuilder.kt: (96, 17): Name shadowed: viewFinder
w: /.../app/src/main/java/com/ocrex/autoentry/view/AutoFitPreviewBuilder.kt: (117, 17): Name shadowed: viewFinder
w: /.../app/src/main/java/com/ocrex/autoentry/view/AutoFitPreviewBuilder.kt: (154, 13): Name shadowed: textureView

> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateStagingReleaseSources
> Task :app:javaPreCompileStagingRelease

> Task :app:compileStagingReleaseJavaWithJavac
/.../app/build/generated/source/kapt/stagingRelease/com/ocrex/autoentry/viewmodel/ExpenseViewModel_MembersInjector.java:5: error: package javax.annotation.processing does not exist
import javax.annotation.processing.Generated;
                                  ^
/.../app/build/generated/source/kapt/stagingRelease/com/ocrex/autoentry/viewmodel/ExpenseViewModel_MembersInjector.java:8: error: cannot find symbol
@Generated(
 ^
  symbol: class Generated
/.../app/build/generated/source/kapt/stagingRelease/com/ocrex/autoentry/viewmodel/PhotoPreviewViewModel_MembersInjector.java:6: error: package javax.annotation.processing does not exist
import javax.annotation.processing.Generated;
                                  ^
/.../app/build/generated/source/kapt/stagingRelease/com/ocrex/autoentry/viewmodel/PhotoPreviewViewModel_MembersInjector.java:9: error: cannot find symbol
@Generated(
 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors

> Task :app:compileStagingReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileStagingReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
23 actionable tasks: 22 executed, 1 up-to-date

  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `sh'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/actions/gradle.rb:52:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:13:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.127.2/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'

### **fastfile**

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Uploads build to Fabric Beta"
  lane :beta do |options|
    gradle(task: "clean")

    gradle(
      task: "assemble",
      build_type: options[:variant],
      flavor: options[:flavor],
      print_command: false
    )

    release_notes = File.read("../CHANGELOG.md")

    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      groups: "autoentry-android---internal",
      notifications: true,
      notes: release_notes)

    post_on_slack
  end

  desc "Post notification to Slack"
  lane :post_on_slack do
    release_notes = File.read("../CHANGELOG.md")
    commit = last_git_commit
    commit_hash = commit[:abbreviated_commit_hash]
    slack(
          slack_url: ENV["SLACK_URL"],
          message: "Android build uploaded to Beta",
          success: true,
          payload: {
            'Flavor & Variant' => "#{lane_context[SharedValues::GRADLE_FLAVOR]} #{lane_context[SharedValues::GRADLE_BUILD_TYPE]}",
            'Commit' => commit_hash,
            "Build Date" => Time.new.to_s,
            'Pull request' => ENV["CI_PULL_REQUEST"],
            'What\'s new' => release_notes
          },
          default_payloads: [])
  end

end

### **app/build.gradle**

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'
apply plugin: "androidx.navigation.safeargs"

android {
    compileSdkVersion 28
    flavorDimensions "default"
    defaultConfig {
        applicationId "..."
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 97
        versionName "2.3.45"
        testInstrumentationRunner "..."
    }

    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }

    signingConfigs {
        release {
            //datas
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    productFlavors {
        staging {
          //datas           
        }

        production {
          //datas
        }
    }
}

dependencies {
    // Kotlin lang
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1'

    implementation "androidx.appcompat:appcompat:1.0.2"
    implementation "androidx.vectordrawable:vectordrawable-animated:1.0.0"
    implementation "androidx.media:media:1.0.1"
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.0.0"
    implementation "androidx.annotation:annotation:1.1.0"
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.constraintlayout:constraintlayout-solver:1.1.3'
    implementation "androidx.work:work-runtime:2.0.1"

    def lifecycle_version = "2.2.0-alpha02"
    implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    kapt "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"

    implementation "com.google.android.material:material:1.0.0"
    implementation "com.google.android.gms:play-services-analytics:16.0.8"
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    implementation 'com.squareup.picasso:picasso:2.71828'

    implementation 'io.intercom.android:intercom-sdk-base:5.4.0'

    implementation 'com.github.nguyenhoanglam:ImagePicker:1.3.3'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.11.1'

    def retrofit_version = "2.4.0"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-scalars:$retrofit_version"
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"

    def okhttp_version = "3.13.1"
    implementation "com.squareup.okhttp3:okhttp:$okhttp_version"
    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp_version"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:$okhttp_version"

    // RxJava
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.2.0'

    implementation 'com.google.dagger:dagger:2.22.1'
    kapt 'com.google.dagger:dagger-compiler:2.22.1'

    implementation 'com.jakewharton.timber:timber:4.7.1'
    implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'
    implementation 'com.jakewharton:butterknife:10.1.0'
    kapt 'com.jakewharton:butterknife-compiler:10.1.0'

    implementation 'com.github.Omega-R:OmegaRecyclerView:1.9.1@aar'

    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.8.0'
    kapt 'com.github.bumptech.glide:compiler:4.9.0'

    // CameraX
    def camerax_version = "1.0.0-alpha03"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"

    implementation 'com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'

    implementation('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }

    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0-alpha4', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testImplementation 'junit:junit:4.12'
}

### **build.gradle**

buildscript {
    ext.kotlin_version = '1.3.41'

    repositories {
        jcenter()
        google()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath "io.realm:realm-gradle-plugin:5.10.0"
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.fabric.tools:gradle:1.28.1'
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.0.0"
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://maven.google.com" }
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by fernandohbrasil** [comment]
### Fastlane env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.22.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G87)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Uploads build to Fabric Beta"
  lane :beta do |options|
    gradle(task: "clean")

    gradle(
      task: "assemble",
      build_type: options[:variant],
      flavor: options[:flavor],
      print_command: false
    )

    release_notes = File.read("../CHANGELOG.md")

    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      groups: "autoentry-android---internal",
      notifications: true,
      notes: release_notes)

    post_on_slack
  end

  desc "Post notification to Slack"
  lane :post_on_slack do
    release_notes = File.read("../CHANGELOG.md")
    commit = last_git_commit
    commit_hash = commit[:abbreviated_commit_hash]
    slack(
          slack_url: ENV["SLACK_URL"],
          message: "Android build uploaded to Beta",
          success: true,
          payload: {
            'Flavor & Variant' => "#{lane_context[SharedValues::GRADLE_FLAVOR]} #{lane_context[SharedValues::GRADLE_BUILD_TYPE]}",
            'Commit' => commit_hash,
            "Build Date" => Time.new.to_s,
            'Pull request' => ENV["CI_PULL_REQUEST"],
            'What\'s new' => release_notes
          },
          default_payloads: [])
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.ocrex.autoentry") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 2.0.2        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-08-13**
</details>

**Comment by janpio** [comment]
So this question is why it fails with `gradle` action in Fastlane but not when building manually via `gradlew` on the command line?

**Comment by fernandohbrasil** [comment]
I don't use command line to compile, but I use Android Studio. And through this I can generate apk or install the app directly on my Mobile Phone;

**Comment by janpio** [comment]
So does it work if you execute the same command (that fastlane generates and executes) manually in the command line?

**Comment by fernandohbrasil** [comment]
I am using the Android Studio to compile and works;

**Comment by janpio** [comment]
Yes, I know that - you said that before. But does using the `gradlew` command line tool directly, not via fastlane, work?

**Comment by fernandohbrasil** [comment]
I had not taken this test. But I did and it didn't work either, so the problem is not fastlane but gradle. Sorry about this ...  

Thank you very much

**Comment by janpio** [comment]
Don't worry, that's what we are here for - help you find the actual problem and solve it.
