### ISSUE TITLE
Match can't handle multiple apple ID's without --readonly? 

### ISSUE THREAD

**Issue by chriscombs** [fastlane/fastlane#15168]
### Question Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Fastlane match and using more than once apple ID for code signing

#### Question Description

Our issue is as follows: 

Dev A creates runs `fastlane match appstore` and logs in using their own Apple ID, which creates a new distribution certificate, and provisioning profile. Two months later, Dev B needs to update the profile to include Push Notifications capability, so they run `fastlane match appstore` using their (different) Apple ID. Instead of using the existing distribution certificate, `match` tries to create a new distribution certificate, presumably because the Apple IDs are different.

I have read the docs and seen that you recommend using one shared Apple ID for codesigning in our organization. This creates a security risk for us, and would prefer to not have a shared account with a public password. Is it intentional that we *must* use a shared account? Or is there a way to be able to use individual accounts that reuse a certificate?

**Comment by janpio** [comment]
So many hard questions in there ;)

Can you reproduce the problem without the 2 months wait in between, just with 2 different accounts doing specific things? That would greatly help to be able to understand what is going on here.

**Comment by chriscombs** [comment]
We tried to reproduce the issue now and it seems to be working fine. I'll reopen it if we run into the issue again or find a better way to reproduce the issue.
