### ISSUE TITLE
Google Play developer API need newer verion

### ISSUE THREAD

**Issue by T1000MG** [fastlane/fastlane#15170]
### Question Checklist

- [x ] Updated fastlane to the latest version (2.128.1)
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Got a message in the google play console over my app releases
"We’ve detected that your app is using an old version of the Google Play developer API. From 1 December 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date."

#### Question Description
What do I have to do to use the API version 3?
I find no way to adjust this.

**Comment by joshdholtz** [comment]
@T1000MG Hello 👋 I will be migrating the usage of the v2 API that `supply` uses to use v3 within the next month so the only thing you will need to do is update to the latest version of _fastlane_ when that is ready 😊
