### ISSUE TITLE
Fastlane not working on MacOS Catalina Dev beta

### ISSUE THREAD

**Issue by prgorasiya** [fastlane/fastlane#15183]
I was using fastlane perfectly before I upgraded to MacOS 10.15 Developer beta.
Since upgrade I cant get fastlane to work.
Every time I run any lane I am getting this error :

`zsh: /usr/local/bin/fastlane: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory`

Not sure what's wrong here.
I even updated ruby gems but still no luck.

**Comment by max-ott** [comment]
You might want to check out these issues:
- https://github.com/fastlane/fastlane/issues/14860
- https://github.com/fastlane/fastlane/issues/14901
- https://github.com/fastlane/fastlane/issues/14887

**Comment by prgorasiya** [comment]
Yeah i checked those but nothing works for me. getting the same error every time
When I run `fastlane -v` I got this

`zsh: /usr/local/bin/fastlane: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory`

**Comment by thefaj** [comment]
macOS Catalina beta 6 is still broken…not sure what's up.

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem fastlane (>= 0.a) with executable fastlane (Gem::GemNotFoundException)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:262:in `bin_path'
	from /Users/alexfajkowski/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by comeonyoh** [comment]
please save me...

**Comment by tadasbub** [comment]
gem update --system

gem install bundler
gem install fastlane

2.1 you may want to use local if your /usr/bin needs extra permissions:
gem install -n /usr/local/bin/ bundler
gem install -n /usr/local/bin/ fastlane

Load up xCode (assuming you have it installed)
Once open, click on xCode -> Preferences -> Locations
On this window find "Command Line Tools" select latest version (11.0)
Restart

**Comment by prgorasiya** [comment]
Thanks for the update @tadasbub. I got it working now.

**Comment by Apocryphon** [comment]
I was able to get past this issue by selecting 11.0 for Command Line Tools (as above), and then installing the gem to `/usr/local/bin`, as in [this solution](https://stackoverflow.com/questions/18599889/error-while-executing-gem-gemfilepermissionerror).

**Comment by duanhjlt** [comment]
Thanks for the update @tadasbub. I got it working now.

**Comment by junyang95** [comment]
I use Jenkins + Fastlane, and update to macOS Catalina. I got this error as well:
Solution:

1. Installing RVM and Ruby on macOS, instead of using macOS ruby
1.1 $ brew install gnupg
1.2 follow - https://rvm.io/rvm/install , to complete the installation
1.3 $ source ~/.rvm/scripts/rvm , to configure rvm in the terminal
1.4 $ rvm install ruby
1.5 $ rvm --default use ruby

2. Delete "Gemfile" and "Gemfile.lock" in the WORKSPACE

3. $ echo $PATH - Copy all the paths

4. Jenkins - Manage Jenkins - Configure System - Global properties - Environment variables - Name: PATH, Value: Paste all the paths

**Comment by danie11am** [comment]
Hi @tadasbub - thanks for your instructions above. When I ran `sudo gem install -n /usr/local/bin/ fastlane` I got the following errors, any suggestions?

```
$ sudo gem install -n /usr/local/bin/ fastlane
Building native extensions. This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.6/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20191013-10818-prk0i8.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.6/ext/unf_ext
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.6/ext/unf_ext
make "DESTDIR="
make: *** No rule to make target `"/Applications/Xcode', needed by `unf.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.6 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6/gem_make.out
```

**Comment by hcassar93** [comment]
Im having the same issue as danie11am. Any suggestions?

**Comment by dmcyk** [comment]
This is because Catalina no longer supports including macOS headers in command line tools, they have to be explicitly used through Xcode SDK. You can do so by running `gem` through the `xcrun` tool like:
```
xcrun gem install fastlane
```

**Comment by dipkasyap** [comment]
gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

Still the same for me . Mac OS catalina

**Comment by tombaranowicz** [comment]
@dipkasyap this helped me with above error: https://programmingzen.com/installing-rbenv-on-zsh-on-macos/

**Comment by dipendra-sharma** [comment]
I solved it with commands as mentioned.

`gem unistall fastlane`
`sudo gem install fastlane -NV -n /usr/local/bin`

**Comment by lishahan** [comment]
> I solved it with commands as mentioned.
> 
> `gem unistall fastlane`
> `sudo gem install fastlane -NV -n /usr/local/bin`

I got -sh: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory 

> This fixed my issue.

> 

>

**Comment by cinder92** [comment]
```
gem unistall fastlane
sudo gem install fastlane -NV -n /usr/local/bin
```

`open ~/.bash_profile` and copy follow command

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH=/usr/local/bin/fastlane:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/<youruser>/.rvm/bin:/Users/<youruser>/.rvm/bin



```

**Comment by lewis-smith** [comment]
I had to add `export GEM_HOME="$HOME/.gem"` to my `.zprofile` file

**Comment by ahmed-alnaami** [comment]
`sudo xcrun gem install fastlane -NV -n /usr/local/bin` worked for me

**Comment by SebastianBoldt** [comment]
2.1 of @tadasbub solved it for me ;)

**Comment by saviour123** [comment]
Solved

- open vscode settings and uncheck or set this to false
`"solargraph.useBundler": false`

**Comment by Alex366** [comment]
I solved it with the following line:

xcrun gem install -n /usr/local/bin/ fastlane

The idea is to install fastlane in local directory and using xcrun tool

**Comment by ainame** [comment]
A note for people reaching this page with installation issues:

We've recently updated the document about the installation. We now don't recommend using "sudo" to install fastlane. Please try rbenv + Bundler to set up the project. System Ruby is already deprecated by Apple so you won't be able to use fastlane in that way soon.
https://docs.fastlane.tools/getting-started/ios/setup/

If you really don't want to install Ruby, there is a way to install RubyGems to your own directories introduced by CocoaPods team. You can do the same for fastlane. This is much safer than using "sudo" but do that at your own risk. Again this won't work with future macOS that don't include system Ruby.
https://guides.cocoapods.org/using/getting-started.html#sudo-less-installation
