### ISSUE TITLE
On macOS Catalina, we now see error: "ruby" can't be opened because its integrity cannot be verified.

### ISSUE THREAD

**Issue by appatappa** [fastlane/fastlane#15186]
When running fastlane, I receive an error that says:

On macOS Catalina, we now see error: "ruby" can't be opened because its integrity cannot be verified.
This software needs to be updated. Contact the developer for more information.

Homebrew Cask downloaded this file on August 1, 2019 from fastlane.tools.

I have attached a screen shot of the message:

<img width="411" alt="Screen Shot 2019-08-15 at 11 46 27 AM" src="https://user-images.githubusercontent.com/29978956/63111316-0b0b6e00-bf53-11e9-9250-edaedaea44f8.png">

This appears to be an issue with the version of ruby that fastlane uses. How can we change this to fix the issue?

This occurs any time we use any fastlane command, such as:

fastlane ios

OR

fastlane ios beta

Even fastlane env causes the same issue.

**Comment by janpio** [comment]
This might help: https://github.com/fastlane/fastlane/issues/14860

**Comment by appatappa** [comment]
@fastlane-bot, the reason the output of `fastlane env` was not included is that `fastlane env` gives the same error. In fact, ANY fastlane command produces this same error.

**Comment by appatappa** [comment]
> #14860

Yep. That did it. 

Just FYI, there must be a time expiration for that to show up, because I thought about it and that option wasn't there in the Settings | Security & Privacy area. I re-ran fastlane and it showed back up. 

Thanks.

**Comment by vijjuk** [comment]
Hi Guys - what is the solution for this? I am having the same issue with both Minishift and MiniKube

**Comment by appatappa** [comment]
Try running it, then going into Preferences | Security and agree to run the
app. That option will go away if you don't do it right away. Then it should
run. This had me stumped before someone gave me that simple solution.

Eddie Andrews
me@eddieandrews.com
515-729-7293 mobile

Haz el bien, y no mires a quién .~. Do what's right, no matter who's looking
