### ISSUE TITLE
[Match] Storing provisioning profiles and certificates on S3

### ISSUE THREAD

**Issue by erneestoc** [fastlane/fastlane#15188]
### Feature Request
Match s3 storage for provisioning profiles and certificates.

#### Motivation Behind Feature
Some people uses S3 to store this kind of credentials, and prefer to use it instead google cloud storage, or git to store credentials. Since I am not in control of the the repos, I have to sell the idea that git is a good way to store this credentials, or explain why I need to create a google cloud account.

#### Feature Description
Implement a `Match::Storage::Interface` that uses s3 bucket instead of google cloud or git.

#### Alternatives or Workarounds
* Not using match for app signing.
* Convince the ops team `git` is a good alternative.

**Comment by joshdholtz** [comment]
@erneestoc I am not opposed to this 😊 I would also prefer to use S3 over Google Cloud. I will add this to our radar 💪

**Comment by erneestoc** [comment]
@joshdholtz thanks! I opened a PR for the functionality I need. I didn't update `Match::Migrate`, but I think that would need changes to its API to support migrating from X to Y (s3 to gc, gc to git, git to s3, etc..).

https://github.com/fastlane/fastlane/pull/15200

I'd love to get some feedback if someone has time to review. 🙏🏻
