### ISSUE TITLE
Flutter Module Complied succeeds but App.framework not copied to Frameworks

### ISSUE THREAD

**Issue by damoncoo** [fastlane/fastlane#15192]
I'm using Flutter module in my IOS project. Project can be compiled succeeded, bu  the flutter pages can't be showed properly,It does not crash ,just staying white. And when I archive it manually, it works just fine

Here is my fastlane env:

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.3_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.117.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.11.0       |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.1        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| emoji_regex               | 1.0.1        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
</details>

**Comment by janpio** [comment]
1. You are using an old fastlane version.
2. What does your lane actually look like?

**Comment by damoncoo** [comment]
I updated my falstlane to the latest version, but still no luck.
Here is my lane:

lane :beta do    
    device_id = ENV['DEVICES_STRING']    
    if device_id && !device_id.empty?
      add_device 
    end    
    ipa_name = ENV['IPA_PATH']
    work_space = ENV['WORK_SPACE']
    configuration = "Debug"
    method = "development"

    gym(
      workspace: work_space,
      scheme:"AntBrand",clean: true, configuration: configuration,
      output_name: ipa_name, export_method: method, export_options: { compileBitcode: false}
    )  
end


> 1. You are using an old fastlane version.
> 2. What does your lane actually look like?

**Comment by damoncoo** [comment]
Just notice a fact, I put a "echo" in the flutter script section, when I archive the project manually, it just showed the log，It did not show log when I build with fastlane. I think sone how it didn't run the script.

Script in xcode
![1566031322705](https://user-images.githubusercontent.com/4880373/63209036-72b9e880-c10e-11e9-8e36-9f602296ae13.jpg)

Archive in xcode
![1566031372911](https://user-images.githubusercontent.com/4880373/63209041-7baaba00-c10e-11e9-9d4e-8b73fd12a0ae.jpg)

Build with fastlane
![1566031434431](https://user-images.githubusercontent.com/4880373/63209042-7f3e4100-c10e-11e9-9b66-6a6c39fee3ce.jpg)

**Comment by janpio** [comment]
It is very possible that this output is just collapsed there.

Can you post the whole output you are getting?

**Comment by damoncoo** [comment]
I did double check the log, it was not collapsed.

**Comment by damoncoo** [comment]
I think I solved the problem, I didn't run:
`flutter build ios --release --no-codesign
`
It's a little confusing, Because I didn't run this command either when archive
