### ISSUE TITLE
match change_password - Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call

### ISSUE THREAD

**Issue by josh-m-sharpe** [fastlane/fastlane#15198]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```
INFO [2019-08-18 12:38:35.47]: 🔒  Successfully encrypted certificates repo
bundler: failed to load command: fastlane (/Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
```

##### Command executed
`bundle exec fastlane match change_password --verbose`
Run against a brand new certificate repo.

##### Complete output when running fastlane, including the stack trace and command used
```
bundle exec fastlane match change_password --verbose
[✔] 🚀
Successfully loaded Appfile at path '/Users/jsharpe/Ys/mobile/fastlane/Appfile'
- apple_id: 'apps@yshq.com'
-------
INFO [2019-08-18 12:38:18.84]: Successfully loaded '/Users/jsharpe/Ys/mobile/fastlane/Matchfile' 📄

+--------------+-------------------------------------------------------------+
|                Detected Values from './fastlane/Matchfile'                 |
+--------------+-------------------------------------------------------------+
| git_url      | git@github.com:YsApps/fastlane_certificates_v2.git |
| storage_mode | git                                                         |
| type         | development                                                 |
| username     | apps@yshq.com                                      |
+--------------+-------------------------------------------------------------+

 [2019-08-18 12:38:18.85]: New passphrase for Git Repo: ************
 [2019-08-18 12:38:23.71]: Type passphrase again: ************
INFO [2019-08-18 12:38:24.02]: Cloning remote git repo...
INFO [2019-08-18 12:38:24.02]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2019-08-18 12:38:24.02]: $ git clone git@github.com:YsApps/fastlane_certificates_v2.git /var/folders/tr/b1508pgj5gz1dq3b0g2ds34r0000gn/T/d20190818-82023-pqgr7b
INFO [2019-08-18 12:38:24.04]: ▸ Cloning into '/var/folders/tr/b1508pgj5gz1dq3b0g2ds34r0000gn/T/d20190818-82023-pqgr7b'...
INFO [2019-08-18 12:38:34.51]: ▸ warning: You appear to have cloned an empty repository.
INFO [2019-08-18 12:38:35.34]: 🔓  Successfully decrypted certificates repo
keychain: "/Users/jsharpe/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:YsApps/fastlane_certificates_v2.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303139303831383130333630325A00  "20190818103602Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303139303831383130333630325A00  "20190818103602Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:YsApps/fastlane_certificates_v2.git"
    "type"<uint32>=<NULL>
password has been deleted.
INFO [2019-08-18 12:38:35.47]: 🔒  Successfully encrypted certificates repo
bundler: failed to load command: fastlane (/Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/storage/interface.rb:81:in `block in save_changes!'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/storage/interface.rb:59:in `chdir'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/storage/interface.rb:59:in `save_changes!'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/change_password.rb:44:in `update'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/commands_generator.rb:186:in `run'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/match/lib/match/commands_generator.rb:25:in `start'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/gems/fastlane-2.129.0/bin/fastlane:23:in `<top (required)>'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/bin/fastlane:23:in `load'
  /Users/jsharpe/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 10.14.6                                                   |
| Ruby                        | 2.4.2                                                     |
| Bundler?                    | true                                                      |
| Git                         | git version 2.21.0                                        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2@Ys-mobile_v2/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G87)                                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                               |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/               |
| Xcode Version               | 10.3                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'byebug'

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APPS = {
  "29" => {
    app_identifier: 'com.yshq.district.www',
    git_branch: 'Ys',
    team_id: '9DF2XQJMD5'
  }
}

default_platform(:ios)

platform :ios do
  desc "Build IOS apps"
  lane :build do |options|
    if options[:org_id].nil?
      puts "org_id not set (org_id:1234)"
      exit 1
    end

    app = APPS[options[:org_id]]

    match(
      force_for_new_devices: true,
      type: (options[:release] ? 'appstore' : 'development'),
      git_branch: app[:git_branch],
      app_identifier: app[:app_identifier],
      team_id: app[:team_id]
    )

    ionic_args = {
      team_id: app[:team_id],
      platform: 'ios',
      prod: true
    }

    if options[:release]
      ionic_args[:release] = true
    else
      ionic_args[:release] = false
      ionic_args[:type] = 'development'
    end

    ionic(ionic_args)
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("apps@yshq.com")


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-ionic | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.4        |
| i18n                      | 0.8.0        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 5.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| byebug                    | 9.0.6        |
| claide                    | 1.0.3        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-ionic     | 0.1.0        |
| ffi                       | 1.9.25       |
| formatador                | 0.2.5        |
| rb-fsevent                | 0.10.3       |
| rb-inotify                | 0.9.10       |
| ruby_dep                  | 1.5.0        |
| listen                    | 3.1.5        |
| lumberjack                | 1.0.13       |
| nenv                      | 0.3.0        |
| shellany                  | 0.0.1        |
| notiffany                 | 0.1.1        |
| method_source             | 0.9.0        |
| pry                       | 0.11.3       |
| thor                      | 0.20.0       |
| guard                     | 2.14.2       |
| temple                    | 0.8.0        |
| tilt                      | 2.0.8        |
| haml                      | 5.0.4        |
| guard-haml                | 1.1.2        |
| hashie                    | 3.4.6        |
| httparty                  | 0.14.0       |
</details>

*generated on:* **2019-08-18**
</details>
```

**Comment by josh-m-sharpe** [comment]
I think this is happening when the certificate repo is empty.

**Comment by janpio** [comment]
> 
> 
> I think this is happening when the certificate repo is empty.

That would make sense, probably nobody even checked that to be honest as the password encrypts individual files. Should be simple enough to fix.
