### ISSUE TITLE
Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing

### ISSUE THREAD

**Issue by josh-m-sharpe** [fastlane/fastlane#15197]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

```
[09:02:16]: Installing certificate...
[⠙] Setting key partition list... (this can take a minute if there are a lot of keys installed) [09:02:16]:
[09:02:16]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/jsharpe/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[09:02:16]:
[09:02:16]: Please look at the following docs to see how to set a keychain password:
[⠹] Setting key partition list... (this can take a minute if there are a lot of keys installed) [09:02:16]:  - https://docs.fastlane.tools/actions/sync_code_signing
[09:02:16]:  - https://docs.fastlane.tools/actions/get_certificates
```

Honestly, it's unclear if my password was set correctly.  I haven't seen a UI popup either. The two links there don't say much about this issue, so generally, I think this warning/messaging could be updated with something a bit more useful.

Thinking it was a bit of a stretch, I even went so far as to create a new credentials repo, but the first time that was used I didn't get a popup about a password either.

Please advise

**Comment by janpio** [comment]
Sharing your `fastlane env` and the _complete_ output would give us a first idea about your environment and what is going on.

The `security` stuff (which is the command that is being executed in the background) is particularly fiddly unfortunately, so it is very hard to fix it in a way that works for everybody - but we can of course try.
