### ISSUE TITLE
Change app_identifier to bundle_identifier

### ISSUE THREAD

**Issue by MikeBenton2** [fastlane/fastlane#15196]
#### Motivation Behind Feature
So apple is clear when they say what the difference is between an App Identifier and a Bundle Identifier. From apple docs:
An App ID is a two-part string used to identify one or more apps from a single development team. The string consists of a Team ID and a bundle ID search string, with a period (.) separating the two parts.  

Where a bundle identifier is just the bundle ID. I found this confusing when using match when the parameter **app_identifier** is really asking for the bundle identifier.

**Comment by janpio** [comment]
Unfortunately Apple has been much less clear about this in the past, and depending on how deep you go in their systems you will encounter "app identifier" and "app id" used in many different use cases.

But you are right, especially for `match`, which even includes the information that this **is** the `bundle identifier` in the description of the `app_identifier` parameter it definitely make sense to clean this up.

First step would be to add a new `bundle_identifier` parameter and make sure it can be used interchangeably with `app_identifier` everywhere (which includes `Matchfile` and probably many other locations).

When this works, we can deprecate `app_identifier` with a warning message that is output to users, then later with a breaking release possibly even remove it.

**Comment by MikeBenton2** [comment]
Awesome, thanks!
