### ISSUE TITLE
'SCAN_GENERATED_PLIST_FILE ' lane context is nil with Xcode 11 Beta 5

### ISSUE THREAD

**Issue by hakota** [fastlane/fastlane#15209]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
```
macos:
  xcode: 11.0.0
```

If you change to the above, scan will be error.

The run_test action does not generate SCAN_GENERATED_PLIST_FILE lane context with Xcode 11 Beta 5. 
[This implementation](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/run_tests.rb#L88 ) doesn't seem to take Xcode 11 into account.
This seems to be the same issue as in [trainer](https://github.com/xcpretty/trainer/issues/32).

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ▸ Test Succeeded
+--------------------+-----+
|       Test Results       |
+--------------------+-----+
| Number of tests    | 469 |
| Number of failures | 0   |
+--------------------+-----+

 ------------------------------
 --- Collecting system logs ---
 ------------------------------

 $ xcrun simctl spawn 026D0D30-4FA0-499E-BFE0-7A72E03C06A6 log collect --output /Users/distiller/project/output/scan/system_logs-iPhone\ 8_iOS_13.0.logarchive 2>/dev/null

 Exit status: 165
+----------------------------+--------------------------------------------------------+
|                                    Lane Context                                     |
+----------------------------+--------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                    |
| PLATFORM_NAME              | ios                                                    |
| LANE_NAME                  | ios test                                               |
| ORIGINAL_DEFAULT_KEYCHAIN  | "/Users/distiller/Library/Keychains/login.keychain-db" |
| SCAN_DERIVED_DATA_PATH     | Build/DerivedData                                      |
| SCAN_GENERATED_PLIST_FILES | []                                                     |
| SCAN_GENERATED_PLIST_FILE  |                                                        |
+----------------------------+--------------------------------------------------------+
 Exit status: 165

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | setup_circle_ci            | 0           |
| 💥   | scan                       | 508         |
+------+----------------------------+-------------+

 fastlane finished with errors

[!] Exit status: 165
Exited with code 1 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                    |
| --------------------------- | ------------------------------------------------------------------------ |
| OS                          | 10.15                                                                    |
| Ruby                        | 2.6.1                                                                    |
| Bundler?                    | true                                                                     |
| Git                         | git version 2.21.0 (Apple Git-122)                                       |
| Installation Source         | ~App/Vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15 (19A526h)                                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                                              |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                                              |
| Is contained                | false                                                                    |
| Is homebrew                 | false                                                                    |
| Is installed via Fabric.app | false                                                                    |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/                         |
| Xcode Version               | 11.0                                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.2       |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| semantic                  | 1.6.0        |
| synx                      | 0.2.1        |
| thor                      | 0.20.0       |
</details>

*generated on:* **2019-08-22**
</details>

**Comment by bvirlet** [comment]
This could be due to a change in the result format of Xcode 11:

>  The format of result bundles changed in Xcode 11. A result bundle is an asset produced by Xcode 11 with the xcresult file extension that contains information about the build, tests, code coverage, and more. Any xcresult files produced with Xcode 10 or earlier cannot be read by Xcode 11. A result bundle can be produced by passing -resultBundlePath ./Example.xcresult to an xcodebuild invocation and the Example.xcresult can then be opened in Xcode. Xcode also creates result bundles in Derived Data. The current result bundle version number is 3, which can be specified by passing the xcodebuild flag -resultBundleVersion 3. Version 3 is the default in Xcode 11, but it is still recommended for automation to explicitly pass the flag, so that any potential future versions that become the default do not cause issues to existing tools. Result bundles can be inspected using xcresulttool. A JSON representation of the root object of the result bundle can be exported using xcrun xcresulttool get --format json --path ./Example.xcresult and any nested object, identified by its reference found in the JSON output, can be exported by adding the flag --id REF. xcresulttool also provides the description of its format using xcrun xcresulttool formatDescription. (41633595)

(see: https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_7_release_notes).

**Comment by hakota** [comment]
@janpio

Should I use this?
https://github.com/xcpretty/trainer/releases/tag/0.9.0

**Comment by janpio** [comment]
Ping @joshdholtz, who I think did that release.

**Comment by hakota** [comment]
As a result of various tests, the scan process was successfully completed by explicitly setting `include_simulator_logs` to `false` without using trainer.
