### ISSUE TITLE
Pilot - undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by sindhu238** [fastlane/fastlane#15204]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*]  I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [*] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [*] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to upload build to TestFlight using pilot.

##### Command executed
Here is my fastfile:

    lane :beta_live do |options|
    changelog = sh("git log --pretty=format:'* %s <%an>%n' --first-parent --abbrev-commit # . 
    {ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD^^^^^'}..HEAD")

    increment_build_number(build_number: ENV["CIRCLE"])

    automatic_code_signing(
      code_sign_identity: "iPhone Distribution",
      profile_name: "Adhoc(Live)",
      bundle_identifier: "com.xxx.xyz"
    )

    gym(
      workspace: "xxx.xcworkspace",
      scheme: "ETXCapital",
      configuration: options[:configuration],
      export_method: "ad-hoc",
      output_name: "ETXCapital",
      clean: true,
      output_directory: "output"
    )

    pilot
    end

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/bin/fastlane)
NoMethodError: [!] undefined method `strip' for nil:NilClass
  /Users/distiller/project/vendor/bundle/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace'
  /Users/distiller/project/vendor/bundle/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
  /Users/distiller/project/vendor/bundle/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
  /Users/distiller/project/vendor/bundle/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `ask'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:196:in `ask_for_2fa_code'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:145:in `handle_two_factor'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/client.rb:770:in `do_login'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/client.rb:384:in `login'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/client.rb:346:in `login'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/pilot/lib/pilot/manager.rb:23:in `login'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/pilot/lib/pilot/manager.rb:16:in `start'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:68:in `block (2 levels) in parsing_binding'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/distiller/project/vendor/bundle/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/distiller/project/vendor/bundle/gems/fastlane-2.129.0/bin/fastlane:23:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/bin/fastlane:22:in `load'
  /Users/distiller/project/vendor/bundle/bin/fastlane:22:in `<top (required)>'
Exited with code 1  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Ensure we are using minimum version
fastlane_version "2.68.0"

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
    )
  end

  ####### Testing #######

  desc "Run all the tests"
  lane :test do
    scan(
      workspace: "ETXCapital.xcworkspace",
      scheme: "ETXCapital",
      devices: ["iPhone 8"],
      code_coverage: true,
      clean: true,
      output_directory: "output/xcode"
    )
  end

  ####### Builds #######

  desc "Deploy a new UAT Beta Build to Apple TestFlight"
  lane :beta_uat do |options|
    changelog = sh("git log --pretty=format:'* %s <%an>%n' --first-parent --abbrev-commit #{ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD^^^^^'}..HEAD")

    increment_build_number(build_number: ENV["CIRCLE_BUILD_NUM"])

    automatic_code_signing(
      code_sign_identity: "iPhone Distribution",
      profile_name: "Adhoc(UAT)",
      bundle_identifier: "com.etx.traderpro.uat"
    )

    gym(
      workspace: "ETXCapital.xcworkspace",
      scheme: "ETXCapital UAT",
      configuration: options[:configuration],
      export_method: "ad-hoc",
      output_name: "ETXCapital",
      clean: true,
      output_directory: "output"
    )

    pilot(app_identifier: "com.etx.traderpro")

  end

  desc "Deploy a new Live Beta Build to Apple TestFlight"
  lane :beta_live do |options|
    changelog = sh("git log --pretty=format:'* %s <%an>%n' --first-parent --abbrev-commit #{ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD^^^^^'}..HEAD")

    increment_build_number(build_number: ENV["CIRCLE_BUILD_NUM"])

    automatic_code_signing(
      code_sign_identity: "iPhone Distribution",
      profile_name: "Adhoc(Live)",
      bundle_identifier: "com.etx.traderpro"
    )

    gym(
      workspace: "ETXCapital.xcworkspace",
      scheme: "ETXCapital",
      configuration: options[:configuration],
      export_method: "ad-hoc",
      output_name: "ETXCapital",
      clean: true,
      output_directory: "output"
    )

    pilot
  end

  desc "Deploy a new version to iTunes Connect"
  lane :release do |options|
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )

    gym(
      verbose: true,
      workspace: "ETXCapital.xcworkspace",
      scheme: "ETXCapital",
      configuration: "Release",
      clean: true,
      include_symbols: true,
      export_method: "app-store",
      output_directory: "output"
    )

    appstore(
      app_identifier: "com.etx.traderpro"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

team_id "8W8SU5P44L"
apple_id "iosdev@etxcapital.co.uk"
itunes_connect_id "iosdev@etxcapital.co.uk"
itc_team_name "Monecor (London) LTD"
itc_team_id "1157702"

for_lane :beta_uat do
  app_identifier "com.etx.traderpro.uat"
end

for_lane :beta_live do
  app_identifier "com.etx.traderpro"
end

for_lane :release do
  app_identifier "com.etx.traderpro"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.66.0       |
| rubyzip                   | 1.2.3        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| unicode-display_width     | 1.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-08-19**
</details>

**Comment by janpio** [comment]
Can you please post the _complete_ output? Did it prompt you for some data - what did you input?

**Comment by sindhu238** [comment]
No. I am running fast lane from my circle ci script.

**Comment by janpio** [comment]
> Can you please post the _complete_ output?

**Comment by tjjfvi** [comment]
@sindhu238 I had this problem, in my case running manually fixed the problem; I had to input a new verification code as the session had expired.

**Comment by tjjfvi** [comment]
Relatedly, when it is running automatically (not in a terminal), it would be nice if instead of this cryptic error, it said something like "The session has expired; please run `fastlane` in a terminal to enter a verification code."

**Comment by sindhu238** [comment]
@janpio , @tjjfvi ,

I added a simple lane in my fastfile as below:
```
desc "test deployment to TestFlight"
  lane :testFlightUpload do
    pilot(ipa: "/Users/sindhu/Documents/ipa/xxx/xyz.ipa")
  end
```

When i try to run from terminal using command: 
**bundle exec fastlane testFlightUpload**

Below is the error message i got with full output:
[✔] 🚀 
[09:40:39]: fastlane detected a Gemfile in the current directory
[09:40:39]: however it seems like you don't use `bundle exec`
[09:40:39]: to launch fastlane faster, please use
[09:40:39]: 
[09:40:39]: $ bundle exec fastlane testFlightUpload
[09:40:39]: 
[09:40:39]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:40:41]: ----------------------------------------
[09:40:41]: --- Step: Verifying fastlane version ---
[09:40:41]: ----------------------------------------
[09:40:41]: Your fastlane version 2.129.0 matches the minimum requirement of 2.68.0  ✅
[09:40:41]: ------------------------------
[09:40:41]: --- Step: default_platform ---
[09:40:41]: ------------------------------
[09:40:41]: Driving the lane 'ios testFlightUpload' 🚀
[09:40:41]: -------------------
[09:40:41]: --- Step: pilot ---
[09:40:41]: -------------------
[09:40:41]: Login to App Store Connect (abc@xyz.co.uk)
[09:40:57]: Login successful
[09:40:59]: Ready to upload new build to TestFlight (App: 14593xxxxx)...
+------------------+----------------------+
|              Lane Context               |
+------------------+----------------------+
| DEFAULT_PLATFORM | ios                  |
| PLATFORM_NAME    | ios                  |
| LANE_NAME        | ios testFlightUpload |
+------------------+----------------------+

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | pilot                      | 20          |
+------+----------------------------+-------------+

[09:41:01]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  some wrong happen when I use fastlane to upload an ipa file
    https://github.com/fastlane/fastlane/issues/14272 [closed] 6 💬
    11 Jun 2019

➡️  Pilot fails to upload ipa: itunes_transporter can't initialise
    https://github.com/fastlane/fastlane/issues/11605 [closed] 5 💬
    22 Mar 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:359:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/pilot/lib/pilot/build_manager.rb:280:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/pilot/lib/pilot/build_manager.rb:280:in `transporter_for_selected_team'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/pilot/lib/pilot/build_manager.rb:33:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:121:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by sindhu238** [comment]
I dont know if this might be useful to know, the apple account is having two-factor authentication enabled

**Comment by tjjfvi** [comment]
@sindhu238 Yes, that is the same error I had gotten. Has this worked in the past and it recently stopped working? Also, have you noticed any "your apple account is being used to sign in to a new account near ABC, DEF"? I am not familiar with the `bundle exec`, so you may want to try running fastlane without it. Also, if you directed the command into a file so you could put the output here (e.g. `bundle exec fastlane testFlightUpload > output.txt`), it will not prompt. You have to run in directly in your terminal, because if fastlane detects that it's output is not a terminal, it will not prompt.

**Comment by sindhu238** [comment]
@tjjfvi ,

Thank you for your help.
I fixed the issue in the following way:
As two factor authentication has been enabled, we need to add 
**FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD** and **FASTLANE_SESSION** to CI that is running the fastlane script.

After adding those, the build has been running successfully.

**Comment by janpio** [comment]
You still were  getting an error that should not happen, so I reopen this for someone to look into.
