### ISSUE TITLE
Building an Xcode project in docker under a linux environment

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#15218]
Till now what I have understood and accomplished is fastlane incorporates app store connect [API](https://developer.apple.com/app-store-connect/api/) to create certs and profiles. What I would like to do is build my app from a non mac-OS machine using docker, probably a linux environment with ruby and fastlane installed on it as dependencies. 

Will fastlane be able to build my XCode project? or does it need a macOS environment and XCode installed with it to do so?

**Comment by janpio** [comment]
No, to build iOS apps it needs Xcode, as there is not other way to build Xcode projects than by using Xcode which only runs on macOS.
