### ISSUE TITLE
require generates warning for stdlib libraries

### ISSUE THREAD

**Issue by lsegal** [fastlane/fastlane#15211]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Reproduction steps:

1. Place the following in a Fastfile:

```ruby
require 'yaml'

lane :test do
end
```

You will see the following warning:

```
[18:23:43]: You have required a gem, if this is a third party gem, please use `fastlane_require 'yaml'` to ensure the gem is installed locally.
```

This warning should not display on Ruby core or Ruby stdlib files.

2. Run `bundle exec fastlane test`

##### Command executed

```sh
bundle exec fastlane test
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle exec fastlane test
 [✔] �
[18:23:43]: You have required a gem, if this is a third party gem, please use `fastlane_require 'yaml'` to ensure the gem is installed locally.
[18:23:43]: ------------------------------
[18:23:43]: --- Step: default_platform ---
[18:23:43]: ------------------------------
[18:23:43]: Driving the lane 'test' �

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[18:23:43]: fastlane.tools finished successfully �
</pre>
</details>

### Environment

<details><summary>≡ƒÜ½ fastlane environment ≡ƒÜ½</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.6.1                        |
| Bundler?                    | true                         |
| Git                         | git version 2.19.1.windows.1 |
| Installation Source         | C:/tools/ruby26/bin/fastlane |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/tools/ruby26/lib          |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found ≡ƒÜ½ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'yaml'

lane :test do
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | Γ£à Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-08-20**
</details>

**Comment by janpio** [comment]
Code is here:
https://github.com/fastlane/fastlane/blob/f892ca98af7ee316e563d07a93a54c96c58b6a47/fastlane/lib/fastlane/fast_file.rb#L29-L33

How can one differentiate between third party and standard libraries? 
Is there a definitive list to use for that check?

**Comment by lsegal** [comment]
> How can one differentiate between third party and standard libraries?

You realistically cannot, and should not try to differentiate. There are many ways to confuse any kind of check, like `$LOAD_PATH` modifications which can pre-empt the loading of a RubyGem, or trigger it, depending.

> Is there a definitive list to use for that check?

No. Don't maintain a list of white listed libraries to require. These depend on Ruby version, the OS you're on, the specific configure flags you used to compile Ruby, your Gemfile, etc. (i.e. sometimes rdoc is a stdlib sometimes it's a gem, same for json and more).

IMO you should not warn for normal require usage. The easy fix here is to disable the warning because it provides no value and only confuses users and actually recommends an action that will _break_, not fix, their setup.

If you _really_ need to do this, the only "reliable" way would be to either monkeypatch into [RubyGems' `require` implementation](https://github.com/rubygems/rubygems/blob/a90989f70aa8843d1fac2e35ce83bd8e47cd5328/lib/rubygems/core_ext/kernel_require.rb) or basically reimplement the full lookup semantics for how RubyGems decides whether a path is a gem or just a normal Ruby file. Reliable is in quotes because both of these things will need you to maintain compatibility across RubyGems versions, Ruby version, and it's quite a bit of work and _will_ break over time.

So you really shouldn't.

**Comment by janpio** [comment]
I see.

**Comment by lsegal** [comment]
Whose reply do we need for this to move forward?

**Comment by janpio** [comment]
Any reply keeps this open.
Only a PR can really move this forward.

**Comment by lsegal** [comment]
Would you accept a PR to remove this warning?

**Comment by janpio** [comment]
Removing the warning doesn't seem like a solution to the actual problem, as this is a useful feature in normal usage of fastlane.

**Comment by lsegal** [comment]
@janpio can you provide information about when this warning is actually useful? I can't think of any case where warning a user about a missing gem is useful. If the gem is actually missing they will get an error instead of the warning, and the error will be more accurate.

But if this is a nonstarter, can you provide some guidance on what type of PR would be accepted to resolve this? I'm all for doing the work if the fastlane team doesn't want to, but if y'all are also setting restrictions on how this is resolved it would be useful to know what those are up front-- again my approach would have be to rip out the false-positive-prone warning, and that seems to be problematic.

**Comment by janpio** [comment]
This is not about missing gems, but about using `require ...` to use one in a `Fastfile`. Here is the documentation for `fastlane_require`: https://docs.fastlane.tools/advanced/Fastfile/#using-fastlane_require I don't know all the reasoning behind this feature and how and where it is useful, but I am aware it exists and sets the context where this warning is useful.

**Comment by lsegal** [comment]
PR opened to resolve this in #15354 without changing any existing behaviors.
