### ISSUE TITLE
fastlane sigh action does not include apple cert when regenerating development profiles

### ISSUE THREAD

**Issue by chongj615** [fastlane/fastlane#15214]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using fastlane sigh to regenerate development profiles, it will remove all apple certificates and only include iOS certificates on the new development profiles

eg.
`fastlane sigh --development -a com.company.App -u myemail@company.com --team_id XXXXXXXXX --skip_certificate_verification --skip_install --provisioning_name='Universal iOS Development' --force --template_name 'Special Service (Dev)' -q "Universal_iOS_Development.mobileprovision" -o provision`

will create a development profile that only include all the account iOS certs, and leaving all apple certs out of the new profile.

##### Command executed
`fastlane sigh --development -a com.company.App -u myemail@company.com --team_id XXXXXXXXX --skip_certificate_verification --skip_install --provisioning_name='Universal iOS Development' --force --template_name 'Special Service (Dev)' -q "Universal_iOS_Development.mobileprovision" -o provision`

##### Complete output when running fastlane, including the stack trace and command used

```
[21:23:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------------------+--------------------------------------+
|                          Summary for sigh 2.129.0                          |
+-------------------------------------+--------------------------------------+
| development                         | true                                 |
| app_identifier                      | com.company.App                  |
| username                            | myemail@company.com                   |
| team_id                             | XXXXXXXXX                           |
| skip_certificate_verification       | true                                 |
| skip_install                        | true                                 |
| provisioning_name                   | Universal iOS Development            |
| force                               | true                                 |
| template_name                       |Core Service (Dev)       |
| filename                            | Universal_iOS_Development.mobilepro  |
|                                     | vision                               |
| adhoc                               | false                                |
| developer_id                        | false                                |
| ignore_profiles_with_different_name | false                                |
| skip_fetch_profiles                 | false                                |
| platform                            | ios                                  |
| readonly                            | false                                |
+-------------------------------------+--------------------------------------+

[21:23:43]: Starting login with user 'myemail@company.com'
[21:23:44]: Successfully logged in
[21:23:44]: Fetching profiles...
[21:23:44]: Found 1 matching profile(s)
[21:23:44]: Recreating the profile
[21:23:45]: Creating new provisioning profile for 'com.company.App' with name 'Universal iOS Development' for 'ios' platform
[21:23:46]: Downloading provisioning profile...
[21:23:46]: Successfully downloaded provisioning profile...
/Users/myname/Universal_iOS_Development.mobileprovision
```

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G3025)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-08-21**
</details>

**Comment by Westacular** [comment]
This appears to be because sigh [uses](https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb#L158)
```ruby
      when 'ios', 'tvos'
        if profile_type == Spaceship.provisioning_profile.Development
          certificates = Spaceship.certificate.development.all
```
and `Spaceship.certificate.development.all` in turn filters certs [using](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/certificate.rb#L279)

```ruby
types = [CERTIFICATE_TYPE_IDS.key(self)]
```

thus returning _only_ the old-style "iOS Development" certs.

There's two general ways I see to fix this:

1) Update `Spaceship.certificate.development.all` and `Spaceship.certificate.mac_development.all` to also include `AppleDevelopment` certs.

2) Update `sigh` (and anywhere else that matters) to merge the list from `Spaceship.certificate.apple_development.all` into the certs list for development profiles.

... then repeat either for `AppleDistribution` certs as well.
