### ISSUE TITLE
[Spaceship] Error 'undefined method `each' for nil:NilClass' when using Spaceship::Portal::Persons

### ISSUE THREAD

**Issue by llamaluvr** [fastlane/fastlane#15216]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to use the Person Management tools described here: https://github.com/fastlane/fastlane/pull/8047

Any Spaceship::Portal::Persons method results in the following error:
```
/Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/persons.rb:44:in `factory_member': [!] undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/persons.rb:11:in `all'
	from Fastfile:106:in `block (2 levels) in parsing_binding'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/keith/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.129.0/bin/fastlane:23:in `<top (required)>'
	from /Users/keith/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/keith/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

##### Command executed
I created the following lane in my fastfile:
```
  lane :teststuff do
    Spaceship::Portal.login
    Spaceship::Portal.client.team_id = ENV['TEAM_ID']
    Spaceship::Portal::Persons.all
  end
```
and ran it with `fastlane iOS teststuff`

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G87)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require "spaceship"

default_platform :ios

platform :ios do
  lane :teststuff do
    Spaceship::Portal.login
    Spaceship::Portal.client.team_id = ENV['TEAM_ID']
    Spaceship::Portal::Persons.all
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app
apple_id ENV['APPLE_ID'] # Your Apple email address
itc_team_id ENV['ITC_TEAM_ID']
itc_team_name ENV['ITC_TEAM_NAME']

team_id ENV['TEAM_ID']  # Developer Portal Team ID
json_key_file ENV["JSON_KEY_FILE"]
package_name ENV["APP_IDENTIFIER"]

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

**Comment by janpio** [comment]
It is very possible this functionality broke with Apple's updates to their APIs. @joshdholtz? (Ping @max-ott, maybe you know a bit about this as well)

**Comment by max-ott** [comment]
That's now all done over at App Store Connect, so `Portal` won't work.

**Comment by llamaluvr** [comment]
@max-ott Thanks for the tip! The following worked for me, displaying the members on the team on adding a new member:
```
Spaceship::Tunes.login
    Spaceship::Tunes.client.team_id = ENV['ITC_TEAM_ID']
    p Spaceship::Tunes::Members.all
    Spaceship::Tunes::Members.create!(
      firstname: "First",
      lastname: "Last",
      email_address: "somebody@whatever.com",
      roles: ["developer"],
      apps: []
    )
```
