### ISSUE TITLE
Get rid of @fastlane-bot's comment about potential code signing issue

### ISSUE THREAD

**Issue by mollyIV** [fastlane/fastlane#15226]
### Issue Description

@fastlane-bot analyses an issue description and if it finds the words `signing` or `provisioning`, it will add the following comment (only if there are no comments at all):

![image](https://user-images.githubusercontent.com/10795657/63698976-31b58880-c820-11e9-9071-ed3922012d70.png)

Most of those comments now seem to be false positives and a bit annoying for the users. 
Let's consider getting rid of bot's comment about potential code signing issue 💣 

That's gonna help to migrate a bot's code to GitHub Actions proposed [here](https://github.com/fastlane/fastlane/issues/15078).

**Comment by richardtop** [comment]
Fantastic idea... Love it
