### ISSUE TITLE
upload testflight error

### ISSUE THREAD

**Issue by shyh5** [fastlane/fastlane#15224]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "ipa 文件打包"
  lane :createipa do
  #cocoapods
  gym(
    scheme:"Bank",
    workspace:"Bank.xcworkspace",
    configuration:"Debug",
    clean:true,
    output_directory:"/Users/SHyH5/Desktop/星管家测试包",#ipa的存放目录
    output_name:"BankDebug__#{Time.now.strftime('%Y%m%d%H%M%S')}",
    export_xcargs:"-allowProvisioningUpdates",
    export_options: {
      method:"development",
      provisioningProfiles:{
        "cn.com.starpos.www":"StarPosTest",
	      "cn.com.starpos.www.NotificationServiceStarpos":"extensionDev"
      }
    }
  )
  end

  desc "上传测试包到fir"
  lane :beta do
   gym(
    scheme:"Bank",
    workspace:"Bank.xcworkspace",
    configuration:"Debug",
    clean:true,
    output_directory:"/Users/SHyH5/Desktop/星管家测试包",#ipa的存放目录
    output_name:"BankDebug__#{Time.now.strftime('%Y%m%d%H%M%S')}",
    export_xcargs:"-allowProvisioningUpdates",
    export_options: {
      method:"development",
      provisioningProfiles:{
        "cn.com.starpos.www":"StarPosTest",
	      "cn.com.starpos.www.NotificationServiceStarpos":"extensionDev"
      }
    }
  )
   firim(firim_api_token: "4995a8a6c0ae1b57fba71c2c50126e57")
  end

  desc "上传生产包到fir"
  lane :release do
   gym(
    scheme:"Bank",
    workspace:"Bank.xcworkspace",
    configuration:"Release",
    clean:true,
    output_directory:"/Users/SHyH5/Desktop/星管家生产包",#ipa的存放目录
    output_name:"BankRelease__#{Time.now.strftime('%Y%m%d%H%M%S')}",
    export_xcargs:"-allowProvisioningUpdates",
    export_options: {
      method:"ad-hoc",
      provisioningProfiles:{
        "cn.com.starpos.www":"dis_pos",
	      "cn.com.starpos.www.NotificationServiceStarpos":"extension_dis"
      }
    }
  )
   firim(firim_api_token: "4995a8a6c0ae1b57fba71c2c50126e57")
  end

  desc "上传生产包到testFlight"
  lane :flight do
   #保证推送证书可用
    #get_push_certificate
    #pod资源更新
    #cocoapods
    #代码签名方式,"app-store", "ad-hoc", "package", "enterprise", "development", "developer-id"]
    #sync_code_signing(type: "appstore")
    #自动增加build号
    #increment_build_number_in_plist
    #scheme_name
    scheme_name = "Bank"
    #workspace_name
    workspace_name  = "Bank.xcworkspace"
    #导出ipa路径
    output_directory = "/Users/SHyH5/Desktop/星管家生产包"
    #building app
    build_app(scheme: scheme_name,
              workspace: workspace_name,
              include_bitcode: false,
              clean: true,
              configuration:"Release",
              output_name: "#{scheme_name}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa",
              output_directory: output_directory,
              export_xcargs:"-allowProvisioningUpdates",
              export_options: {
                  method:"app-store",
                  provisioningProfiles:{
                     "cn.com.starpos.www":"appSotre_dis",
	                   "cn.com.starpos.www.NotificationServiceStarpos":"extention_appstore"
              }
    })
    #上传到Testflight
    upload_to_testflight(skip_waiting_for_build_processing: true)
    #slack(message: "Successfully distributed a new beta build")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-firim | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.66.0       |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| dotenv                    | 2.7.5        |
| psych                     | 2.1.0.1      |
| firim                     | 0.2.1        |
| fastlane-plugin-firim     | 0.2.0        |
</details>

*generated on:* **2019-08-26**
</details>

[!] Failed to open TCP connection to idmsa.apple.com:443 (Operation timed out - connect(2) for "idmsa.apple.com" port 443)

how to solve this problem

**Comment by janpio** [comment]
Can you access https://idmsa.apple.com in your browser?

**Comment by shyh5** [comment]
@janpio 
hi，when i visit this page, it says "The page you’re looking for can’t be found". 
Is it because of this?

**Comment by janpio** [comment]
No, that is actually the redirect that is expected. If the domain and host was totally blocked for you, you would have gotten a different error message.
