### ISSUE TITLE
Supply - AndroidPublisherV3 - Cannot update an existing track

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#15222]
Currently working on migrating `supply` to androidpublisherv3 - https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/androidpublisherv3_tracking.md

Hit a road block trying to update the rollout of a version 😬 

Code:
https://github.com/scorpion35/fastlane/commit/9a7f12cda9e02104c99c446c8e0b764a53d8dc1a

Use case & test results:
https://github.com/scorpion35/fastlane/commit/9a7f12cda9e02104c99c446c8e0b764a53d8dc1a#commitcomment-34808835

Here's the object before uploading it - 
![Screen Shot 2019-08-23 at 8 21 13 AM](https://user-images.githubusercontent.com/18679225/63594163-b5067e00-c583-11e9-829c-eb238690c707.png)

After making all changes in memory during my debugging session, I call `client.commit_current_edit!` to apply these changes on Google Play (https://github.com/scorpion35/fastlane/blob/androidpublisherv3/supply/lib/supply/uploader.rb#L54)

Does anyone know how to increment the rollout, please? Many thanks in advance!

**Comment by gabrielittner** [comment]
You need to send `"status": "inProgress"` in the release object of the request body. I also think that the `send("track=", 'rollout')` isn't a thing anymore because both the beta and the production track can have rollouts, so that should be the actual track where you perform the rollout.

For the status thing see `releases[].status` her:
https://developers.google.com/android-publisher/api-ref/edits/tracks

**Comment by scorpion35** [comment]
Ah right! That's what I was thinking too and added it to my notes - https://github.com/scorpion35/fastlane/blob/9a7f12cda9e02104c99c446c8e0b764a53d8dc1a/supply/androidpublisherv3_tracking.md (but removed it because I wasn't 100%)

I have tried `track = 'production'` prior to setting it to `rollout`, and that doesn't seem to do anything at all (i.e. it didn't change any thing for the release on google play console). Let me try a couple of more tests. 

Thank you very much for fast reply :)

**Comment by scorpion35** [comment]
I give up 😞 Tried many different combinations - 
- user_fraction = 0.51, status='inProgress', track = 'production', preserved existing release notes
- user_fraction = 0.51, status='inProgress', track = 'production', removed existing release notes and only tried to update with `user_fraction`
- user_fraction = 0.51, status='inProgress', track = 'rollout', preserved existing release notes
- user_fraction = 0.51, status='inProgress', track = 'rollout', removed existing release notes and only tried to update with `user_fraction`

One thing I noticed is something seems to be invalidating the track and it makes sense for Google to not apply an invalid object to the track.
![Screen Shot 2019-08-24 at 9 02 04 AM](https://user-images.githubusercontent.com/18679225/63637726-f8c5ba00-c64d-11e9-917a-8c3cb0a2ca7c.png)
(^ this track is supposed to have much more information, but when I try to fetch the track information after updating the track, I am getting an empty)

Does anyone know how to properly update a track (rollout or update the release notes for a version that is already in progress, etc.)? 

Thanks in advance for your help!!

**Comment by gabrielittner** [comment]
Do you set the track in the request body?

**Comment by gabrielittner** [comment]
In Google's sample they don't actually set there when updating the rollout percentage (you can see it in the part that @Xexiz quoted). Maybe that is the issue.
