### ISSUE TITLE
Use Variable created in Fastfile to other file like Scanfile

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#15230]
Hello

In Fastfile I create an variable like that
default_platform :ios

```
platform :ios do
  before_all do    
    build_time = Time.new.strftime("%Y.%m.%d")
 end
end
```

Then, I want to use this variable in Scanfile like:

```
uildlog_path "./test_reports_#{"build_time"}"
custom_report_file_name "#{ENV["APP_NAME"]}_#{"build_time"}.html"
```
But it doesn't work.

I work around by add it to .env file and load this file

default_platform :ios

```
platform :ios do
  before_all do    
    
    PROJECT_DIR= ".."
    build_time = Time.new.strftime("%Y.%m.%d")
    sh "echo BUILD_TIME=#{build_time} >> .env"
    Dotenv.load('local.properties', '.env', '.env.secret')
   end
end
```

and Scanfile
```
buildlog_path "./test_reports_#{ENV["BUILD_TIME"]}"
custom_report_file_name "#{ENV["APP_NAME"]}_#{ENV["BUILD_TIME"]}.html"
```

is there a way to use directly from Fastfile to Scanfile without using environment file ?

**Comment by janpio** [comment]
You might be able to just use `ENV["BUILD_TIME"] = Time.new.strftime("%Y.%m.%d")` in your `Fastfile` - never tried that.
